Fix getImage method when sending product alert email
magento/magento2 pull request #10208
Opened 2017-07-11 12:52 UTC by JeroenVanLeusden

### Description
When sending product alert emails from cron jobs it will do so from the backend area. An exception is thrown `Unable to resolve the source file for 'frontend/_view/nl_NL/Magento_Catalog/images/product/placeholder/.jpg'` because the product image can't be loaded.

Although Magento will mark the subscription send, in fact it's not. To solve this I created an emulation to the product image is loaded in the fronted area.

### Fixed Issues (if relevant)
1. None that I could find.

### Manual testing scenarios
1. Add yourself to the mailing list for product alerts (e.g. out of stock products).
2. Run the cron job which is responsible for sending the email if a product is back in stock.
3. Magento will mark the subscription as send but in fact it's not.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-07-11 12:58 UTC, ihor-sviziev commented on app/code/Magento/ProductAlert/Block/Email/AbstractEmail.php
> +        $image = $this->imageBuilder->setProduct($product)
Would be great to wrap this part with try-catch block, similar to this:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Payment/Helper/Data.php#L218

2017-07-11 13:13 UTC, JeroenVanLeusden commented on app/code/Magento/ProductAlert/Block/Email/AbstractEmail.php
> +        $image = $this->imageBuilder->setProduct($product)
Will do!

2017-07-11 13:14 UTC, JeroenVanLeusden commented
See unit tests are failing, will update these shortly.

2017-07-11 13:46 UTC, ishakhsuvarov commented on app/code/Magento/ProductAlert/Block/Email/AbstractEmail.php
> +     * @param       $product
Looks like you removed types from the DocBlock by mistake. Please revert it

2017-07-11 13:56 UTC, ishakhsuvarov commented on app/code/Magento/ProductAlert/Block/Email/AbstractEmail.php
> +        \Magento\Store\Model\App\Emulation $appEmulation,
* New constructor argument may only be added as the last on the list due to backwards compatibility policy
* Additional argument must be nullable for the same reason.

Please follow [Backwards Compatible Development Guide](http://devdocs.magento.com/guides/v2.1/ext-best-practices/extension-coding/backwards-compatible-development/index.html#adding-a-constructor-parameter) for examples and more information

2017-07-11 13:57 UTC, ishakhsuvarov commented on app/code/Magento/ProductAlert/Block/Email/AbstractEmail.php
> +     * @param \Magento\Store\Model\App\Emulation               $appEmulation
Please use same DocBlock notation as all over Magento to increase consistency

2017-07-11 13:59 UTC, ishakhsuvarov requested changes
Please check Travis CI build results and fix errors identified by tests, also please consider covering new code with test.

2017-07-11 16:15 UTC, JeroenVanLeusden commented
@ishakhsuvarov Updated the PR. I'm having a hard time fixing the unit tests, any idea why `$this->_storeManager->getStore()` is `null`?

2017-07-12 05:15 UTC, ishakhsuvarov commented
@JeroenVanLeusden I am going to look into it shortly

2017-07-12 07:57 UTC, JeroenVanLeusden commented
@ishakhsuvarov Static tests still fail because the coupling between objects have a value of 14 and should be reduced to 12. What is the preferred way to achieve this?

2017-07-12 08:19 UTC, ishakhsuvarov commented
@JeroenVanLeusden I am currently looking into ways to refactor the code to reduce that number. It may be needed to extract a part of this class to a different one, in case we do not find a way to reduce number of dependencies in other way.

I've updated the unit test. The problem occurred due to not initialized mock object for store manager.

2017-07-12 08:41 UTC, JeroenVanLeusden commented
@ishakhsuvarov I saw the tests, really useful for next time! If there is anything I can do please let me know.

2017-07-12 13:25 UTC, ishakhsuvarov approved these changes

2017-07-12 13:29 UTC, ishakhsuvarov commented
@JeroenVanLeusden I've fixed the Coupling issue by extracting image building logic into the separate class with the single responsibility.
Could you please check, that your initial issue is fixed after the refactoring?
Thanks!

2017-07-12 13:44 UTC, JeroenVanLeusden commented
@ishakhsuvarov Just tested and can confirm this patch fixes the issue!

2017-07-12 13:46 UTC, ishakhsuvarov commented
@JeroenVanLeusden Great!
We will proceed with the merge procedures then.

2017-07-14 21:30 UTC, merged

2017-10-09 23:13 UTC, daniel-ifrim reviewed
In constructor, array $data = [], shouldn't come after ImageProvider $imageProvider = null ?

2017-10-10 08:16 UTC, JeroenVanLeusden commented
It does regarding the [backward compatible guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/backward-compatible-development/index.html).