[WIP]Google Sitemap refactoring - introduce item resolver
magento/magento2 pull request #10288
Opened 2017-07-19 20:18 UTC by piotrkwiecinski

Refactoring to introduce injectable item resolver as way to add items to sitemap

### Description
- Introduce SitemapItemResolverInterface with concrete implementations for cms pages, products, categories and aggregate
- Introduce SitemapItemInterface as representation of single sitemap item
- Remove addSitemapItems as it was introduced in develop branch and wasn't used yet as public API
- Deprecate helper (suggested by @vrann). Getting data from configuration is part of introduced concrete implementations. (WIP)

### Fixed Issues (if relevant)

1. magento/magento2##10045: Refactoring: Adding items to the Sitemap

### Manual testing scenarios

1. Go to Marketing > SEO > Sitemap
2. Add sitemap - provide path and filename
3. Click generate & save sitemap
4. Check if content is properly generated.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

This is still work in progress as I need to fix main SitemapTest or at least try, but I wanted to get some feedback as I most likely I'll finish work over the weekend.

2017-07-19 21:25 UTC, Koc commented on app/code/Magento/Sitemap/Model/ProductSitemapItemResolver.php
> +        $items = array_map(function ($item) use ($storeId) {
Does we need exclude disabled products also? And this code will not work on large collections

2017-07-20 22:07 UTC, okorshenko commented
Hi @piotrkwiecinski Could you please look at broken tests?

2017-07-24 22:37 UTC, piotrkwiecinski commented
@vrann, @okorshenko tests should be green now. Last one was static.

2017-07-25 21:15 UTC, vrann commented
@piotrkwiecinski finished code review, looks good. Running internal builds.

2017-07-25 21:15 UTC, vrann approved these changes

2017-07-26 20:21 UTC, vrann requested changes

2017-07-26 20:21 UTC, vrann commented on app/code/Magento/Sitemap/Model/Sitemap.php
> -     * Add a sitemap item to the array of sitemap items
Please restore these two public methods:
- they are in the class marked as @api
- the class will be released as is in 2.2 release
- current pull request will get to the 2.3 release

2017-07-27 20:20 UTC, merged

2019-03-16 21:05 UTC, Ctucker9233 commented
@magento-team Will this get backported to 2.2?

2019-03-17 01:03 UTC, piotrkwiecinski commented
If it would be useful and there is no objections from  @magento-team I could port it back on Monday or Tuesday

2019-03-18 16:39 UTC, Ctucker9233 commented
@piotrekkaminski Thanks