WIP: Admin Config Search
magento/magento2 pull request #10335
Opened 2017-07-26 13:18 UTC by maximgubar

### Description
This feature will provide a possibility to find the config fields in Magento in a fast and easy way (e.g. live search).

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-07-26 14:40 UTC, maghamed requested changes

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config.php
> +    public function findInStructure(ElementIterator $structureElementIterator, $needle, $pathLabel = '')
why does this method declared as public? 
We use it just inside this class

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config.php
> +            }
why do we have this check? 

Magento\Config\Model\Config\Structure\Element\Iterator returns  \Magento\Config\Model\Config\Structure\ElementInterface by contract, do we have any reasons not to trust the declared contract and make additional check? 
```php
    /**
     * Return the current element
     *
     * @return \Magento\Config\Model\Config\Structure\ElementInterface
     */
    public function current()
    {
        return $this->_flyweight;
    }
```

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config.php
> +    public function findInStructure(ElementIterator $structureElementIterator, $needle, $pathLabel = '')
don't think "needle" is a good name.
Unless we call $structureElementIterator as haystack

It's the user's search term, so let's call it this way

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config.php
> +            if (stripos((string)$structureElement->getLabel(), $needle) !== false) {
it's better to use 
mb_stripos than stripos
Magento requires        ` "ext-mbstring": "*",` to be installed

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config.php
> +        }
if we will move a check for the empty query into the findInStructure function, we could end-up with 
```php
    public function load()
     {
         $this->findInStructure($this->configStructure->getTabs(), $this->getQuery());
         $this->setResults($this->resultBuilder->getAll());
         return $this;
     }
```

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config/Result/Builder.php
> +    ];
it's better not to hard code supported elements, but accept an additional parameter, which is configured through the DI.

So, if some new supported component would be added in future we could easily add this new type with DI configuration.

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config/Result/Builder.php
> +                ];
it's better to introduce an interface and provide implementation for each of the type.
To have an ability to add new supported type in future. 
For now, we hardcoded existing structure elements

2017-07-26 14:40 UTC, maghamed commented on app/code/Magento/Config/Block/System/Config/Edit.php
> +        Json $jsonSerializer = null
it's better to have a dependency on the interface instead?
`Magento\Framework\Serialize\SerializerInterface`

2017-07-27 07:30 UTC, korostii commented on app/code/Magento/Config/Block/System/Config/Edit.php
> +        Json $jsonSerializer = null
As mentioned on https://github.com/magento/magento2/pull/8331#discussion_r99838100 and referenced on [#10342 (comment)](https://github.com/magento/magento2/pull/10342/files#r129688126) , `SerializerInterface` is not guaranteed to return a _JSON_ serializer in the future. And `\Magento\Config\Block\System\Config` uses it in a [method explicitly named `getConfigSearchParamsJson`](https://github.com/liip-forks/magento2/blob/94b423bf985dbd210a5eb13a43ff4dd92a8cc3ca/app/code/Magento/Config/Block/System/Config/Edit.php#L124)

2017-08-22 15:01 UTC, maghamed commented on app/code/Magento/Config/Model/Config/Structure/ElementNewInterface.php
> +interface ElementNewInterface extends ElementInterface
Don't think that naming is very good in this case ElementInterface -> ElementNewInterface

2017-08-22 15:01 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config/Result/Builder.php
> +    const STRUCTURE_ELEMENT_TYPE_FIELD   = 'field';
why do we need these constants if they not used

2017-08-22 15:01 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config.php
> + * @method Config setResults(array $results)
it's better to have all these methods as a part of Object contract, not relying on `__call` usage

2017-08-22 15:01 UTC, maghamed commented on app/code/Magento/Backend/Model/Search/Config.php
> + * @method array getResults()
it's better to have these methods in class contract, not relying on `__call` method

2017-08-22 15:09 UTC, maximgubar commented on app/code/Magento/Config/Model/Config/Structure/ElementNewInterface.php
> +interface ElementNewInterface extends ElementInterface
I'll move it up and name it StructureElementInterface, wdyt ?

2017-08-22 15:20 UTC, maghamed approved these changes

2017-08-30 10:54 UTC, ishakhsuvarov commented
Hi @maximgubar 
Please check the `Magento\Backend\Model\Search\ConfigTest` failures. Looks like search result in the test is always empty. Let us know if you need any assistance.
Thank you.

2017-09-11 12:02 UTC, ishakhsuvarov commented
@maximgubar Thank you for the update

2017-09-20 14:22 UTC, vrann commented
@maximgubar 

- [ ] add description to the pull request
- [ ] please fix static test:
```
Magento\Test\Php\XssPhtmlTemplateTest::testXssSensitiveOutput
Passed: 1172, Failed: 1, Incomplete: 0, Skipped: 0.
Data set: /opt/bamboo/agents/agent1/xml-data/build-dir/M2-AT2472-SLE1/magento2/app/code/Magento/Config/view/adminhtml/templates/system/config/edit.phtml
Potentially XSS vulnerability. Please verify that output is escaped at lines 391
Failed asserting that a string is empty.
/opt/bamboo/agents/agent1/xml-data/build-dir/M2-AT2472-SLE1/magento2/dev/tests/static/testsuite/Magento/Test/Php/XssPhtmlTemplateTest.php:48
/opt/bamboo/agents/agent1/xml-data/build-dir/M2-AT2472-SLE1/magento2/lib/internal/Magento/Framework/App/Utility/AggregateInvoker.php:56
/opt/bamboo/agents/agent1/xml-data/build-dir/M2-AT2472-SLE1/magento2/dev/tests/static/testsuite/Magento/Test/Php/XssPhtmlTemplateTest.php:51
(4 more lines...)
```

2017-09-25 21:53 UTC, vrann commented
added changes per UX request:
1. `.highlighted` should be added to tr around the input
2. `.highlighted` color should be #DFF7FF

2017-09-27 22:35 UTC, merged