Update Configurable.php - add check for null in getProductForThumbnail()
magento/magento2 pull request #10483
Opened 2017-08-09 20:08 UTC by pbaylies

Check to make sure that $this->getChildProduct() isn't null here before trying to call any class methods on it.

2017-08-09 20:24 UTC, orlangur requested changes

2017-08-09 20:24 UTC, orlangur commented on app/code/Magento/ConfigurableProduct/Block/Cart/Item/Renderer/Configurable.php
>              !($this->getChildProduct()->getThumbnail() && $this->getChildProduct()->getThumbnail() != 'no_selection')
I suggest rewriting it in more readable form
```
!($this->getChildProduct() && $this->getChildProduct()->getThumbnail() && $this->getChildProduct()->getThumbnail() != 'no_selection')
```

When `$this->getChildProduct()` can be null by the way?

2017-08-09 20:39 UTC, pbaylies commented on app/code/Magento/ConfigurableProduct/Block/Cart/Item/Renderer/Configurable.php
>              !($this->getChildProduct()->getThumbnail() && $this->getChildProduct()->getThumbnail() != 'no_selection')
@orlangur We ran into this in production this morning, had a 500 error on /checkout/cart/ for a user and traced it back to this code. It was being called from the view/frontend/templates/cart/item/default.phtml template in the  checkout module.

2017-08-09 20:41 UTC, orlangur commented
Thanks for the quick change 👍 Please provide answer to the

> When `$this->getChildProduct()` can be null by the way?

question to assure such change is really necessary.

2017-08-09 20:45 UTC, pbaylies commented
@orlangur We ran into this in production this morning, had a 500 error on /checkout/cart/ for a user and traced it back to this code. It was being called from the view/frontend/templates/cart/item/default.phtml template in the checkout module.

2017-08-09 20:48 UTC, orlangur commented
@pbaylies do you have a stack trace maybe? As from `\Magento\Quote\Model\Quote\Item\AbstractItem::getProduct` there should have been fatal error on line 153 in such case. 

Currently according to PHPDocs `\Magento\Checkout\Block\Cart\Item\Renderer::getProduct` and `\Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable::getChildProduct` can return product model only and I would like to understand whether it's problem with implementation or documentation.

2017-08-09 20:51 UTC, pbaylies commented
@orlangur We have a partial stack trace from the logs:

Call to a member function getThumbnail() on null in /var/app/current/htdocs/vendor/magento/module-configurable-product/Block/Cart/Item/Renderer/Configurable.php:68

Stack trace:
#0 /var/app/current/htdocs/var/view_preprocessed/html/vendor/magento/module-checkout/view/frontend/templates/cart/item/default.phtml(1): Magento\\ConfigurableProduct\\Block\\Cart\\Item\\Renderer\\Configurable->getProductForThumbnail()
#1 /var/app/current/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/app/curren...')
#2 /var/app/current/htdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(Magento\\ConfigurableProduct\\Block\\Cart\\Item\\Renderer\\Configurable), '/var/app/curren...', Array)
#3 /var/app/current/htdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\\Framework\\View\\Element\\Template->fetchView('/var/app/curren...')

2017-08-09 20:55 UTC, orlangur commented
Do you see an approximate way it can happen in vanilla Magento 2 CE? No customization could cause such behavior? Maybe you have access to database to observe quote item and execution flow in `\Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable::getChildProduct` and deeper.

2017-08-09 20:57 UTC, pbaylies commented
@orlangur We are running EE with a lot of modules and customizations, so we can't really rule that out as a possibility. That said, there is a null value getting returned here, and it is causing a 500 error on the cart page, so, seems that is some cause for concern in this code.

2017-08-10 10:58 UTC, orlangur commented
Long story short, with the help of @maghamed I noticed that `$option->getProduct()` call does not follow `OptionInterface` thus it can potentially return `null` in some circumstances.

A better fix would be to find out when `$option->getProduct()` becoming `null` and fix this making proposed check redundant. If you won't manage to achieve this, let's just polish up current code:

1. Move `||` to next line and format code accordingly so that there are no trailing spaces
2. Change PHPDoc of \Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable::getChildProduct marking it can return product model or `null`

2017-08-10 14:19 UTC, pbaylies commented
@orlangur Thanks for tracking that down!

2017-08-10 14:32 UTC, orlangur commented
Hi @pbaylies,

> A better fix would be to find out when $option->getProduct() becoming null and fix this making proposed check redundant

No luck with such approach or didn't try it? Please share your findings if any, if you're not going to try ue to lack of time/motivation this is absolutely ok too.

2017-08-10 14:48 UTC, pbaylies commented
@orlangur With this fix, at least I know it catches all the cases where getChildProduct() might be null in this function. Figuring out when getProduct() might be null as well would be a bigger job for another ticket.

2017-08-10 16:04 UTC, orlangur commented
Aha, ok, let's leave as is (although we are fixing symptom and not a root of the problem here).

2017-08-10 17:48 UTC, orlangur approved these changes

2017-08-10 17:56 UTC, pbaylies commented
@orlangur Thank you!

2017-08-10 20:55 UTC, merged

2018-01-02 14:47 UTC, kilis commented
Hey!
Had the same issue and this was the fix for us also.
FYI this needs also needs to be fixed in here also Magento\ConfigurableProduct\CustomerData\ConfigurableItem:getProductForThumbnail() The same way.