Translate order getCreatedAtFormatted() to store locale
magento/magento2 pull request #10491
Opened 2017-08-11 08:03 UTC by JeroenVanLeusden

### Description
Updated version of #10390, added new interface method en deprecated the current one.

Add `getDefaultStoreLocale()` to allow fetching scoped values. Use this in `getCreatedAtFormatted()` so `created_at` date of order will be translated in emails to locale being used in that store view.

### Fixed Issues (if relevant)
1. None that I could find.

### Manual testing scenarios
1. Set default locale of your store to any language but English.
2. Create order and send confirmation email.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2017-08-11 08:12 UTC, orlangur commented
You cannot add new methods into existing `@api` interfaces as it will break every existing interface implementation. Please check http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#introduction-of-a-method-to-a-class-or-interface

2017-08-11 12:10 UTC, Jeroenll commented
@orlangur creating a new implementation and use that in `\Magento\Framework\Locale\Resolver` would be the way to go? If so, I will update the PR when I have the time.

2017-08-14 15:59 UTC, orlangur commented
I think `\Magento\Framework\Locale\ResolverInterface` should not be touched (changed/deprecated) for the sake of the fix even if we didn't have BC constraints.

Any idea why `\Magento\Framework\Locale\Resolver` and `\Magento\Backend\Model\Locale\Resolver` does not cover this case with order model properly? From implementation it looks like correct locale should be already there.

So, I wouldn't recommend to introduce any `StoreAwareLocaleResolverInterface` unless really necessary.

2017-08-14 17:54 UTC, JeroenVanLeusden commented
@orlangur After some more debugging I found the real issue.

`\Magento\Framework\Locale\Resolver::__construct()` will set the locale using `$this->setLocale($locale);` where `$locale` is `null` since no argument is set in the `di.xml`. 

Then in the `Magento\Backend\Model\Locale\Resolver::setLocale()` will get `$local` as `null`. In there it will load the session locale which is also null and the user locale which is `en_US` (Magento backend locale). So there it will set the locale to `en_US` although our store locale is `nl_NL`.  The changes I've made aren't neccesary because the `getDefaultLocale()` will fetch the correct value. So this issue is only relevant is backend and frontend locales don't match.

In my opinion the best solution would be to emulate the store locale in `\Magento\Sales\Model\OrdergetCreatedAtFormatted()` and change it back after the date is formatted. If you agree on this one I will implement this.

2017-08-14 18:02 UTC, orlangur commented
Do we need to really emulate locale or it's enough to pass proper locale in
```
-            null,
 +            $this->localeResolver->getDefaultStoreLocale($this->getStore()),
```
?

2017-08-14 18:14 UTC, JeroenVanLeusden commented
@orlangur Yes, if you have the proper locale you can insert it there.

2017-08-14 18:40 UTC, orlangur commented
Not sure, please try it.

Please go this way, if `getDefaultLocale` will not work do something like `$locale = $this->scopeConfig->getValue($this->getDefaultLocalePath(), $this->scopeType, $store);` in place (just a fix in order model, no need in additional interfaces/classes).

Please force push into the same branch with a single commit when it is ready (i.e. works & builds are green).

2017-08-15 09:36 UTC, JeroenVanLeusden commented
@orlangur Tested and works. Tests are green, only one job exceeded the maximum time limit for jobs, and has been terminated.

2017-08-15 09:51 UTC, orlangur requested changes

2017-08-15 09:51 UTC, orlangur commented on app/code/Magento/Sales/Model/Order.php
> +    protected $_eavConfig;
Thanks for noticing this 👍

2017-08-15 09:51 UTC, orlangur commented on app/code/Magento/Sales/Model/Order.php
> +    protected $localeResolver;
Please make it private (this is a rule for any new class properties/methods).

2017-08-15 09:51 UTC, orlangur commented on app/code/Magento/Sales/Model/Order.php
> +            $this->localeResolver->getDefaultLocale(),
Seems like this public method can be easily covered with unit test, however, as there is no logic and we just call method of another class with a bunch of arguments I do not insist.

2017-08-15 09:52 UTC, orlangur commented on app/code/Magento/Sales/Model/Order.php
> +    protected $_eavConfig;
No need to make it private I believe, not sure it will even pass the tests this way.

2017-08-15 09:55 UTC, orlangur commented
@JeroenVanLeusden cool job! Please do an amend commit + force push (only protected -> private for one field is a necessary field, other is at your discretion) and I will proceed with merging.

2017-08-15 09:55 UTC, JeroenVanLeusden commented on app/code/Magento/Sales/Model/Order.php
> +    protected $_eavConfig;
It was dynamically declared (read: public), making it private may break things in 3rd party code?

2017-08-15 10:02 UTC, JeroenVanLeusden commented on app/code/Magento/Sales/Model/Order.php
> +            $this->localeResolver->getDefaultLocale(),
It indeed calls public methods, making a test would be duplicate I guess?

2017-08-15 10:06 UTC, orlangur commented on app/code/Magento/Sales/Model/Order.php
> +            $this->localeResolver->getDefaultLocale(),
Nope, mock this dependency, the only thing to be asserted that we are passing concrete locale and not `null`.

2017-08-15 10:08 UTC, JeroenVanLeusden commented on app/code/Magento/Sales/Model/Order.php
> +            $this->localeResolver->getDefaultLocale(),
Will do that later today and notify you when ready!

2017-08-15 12:19 UTC, orlangur commented on app/code/Magento/Sales/Model/Order.php
> +            $this->localeResolver->getDefaultLocale(),
Thanks for keeping me updated, waiting for a ping.

2017-08-15 14:12 UTC, orlangur commented on app/code/Magento/Sales/Model/Order.php
> +    protected $_eavConfig;
I would give it a try and if no core tests are broken leave it `private`.

I believe if any extension relied on this property as public it's totally weird, inheritance from core classes is not recommended and property is not marked as `@api`.

2017-08-15 16:11 UTC, JeroenVanLeusden commented
@orlangur Want to test if the dependency is not `null` like
```
$localeResolver = $this->getMockBuilder(\Magento\Framework\Locale\ResolverInterface::class)
    ->disableOriginalConstructor()
    ->getMock();
$this->assertNotNull($localeResolver);
```

Or if the `getDefaultLocale()` returns a `string`?

2017-08-15 16:54 UTC, orlangur commented
@JeroenVanLeusden NotNull is bad practice, some good-looking locale string like `'nl_NL'` please.

2017-08-15 19:25 UTC, JeroenVanLeusden commented
@orlangur Still getting used to Magento's tests please bare with me :)
```
$localeResolver = $this->getMockBuilder(\Magento\Framework\Locale\ResolverInterface::class)
    ->disableOriginalConstructor()
    ->getMock();

$localeResolver->expects($this->once())
     ->method('getDefaultLocale')
    ->willReturn('en_US');
```

Taken this looking from other tests but this doesn't work, method isn't being called. Also would like to test with some different languages then just `en_US`, what would be the way to approach this?

2017-08-15 19:50 UTC, orlangur commented
@JeroenVanLeusden just make sure that you passed `localeResolver` into object under test.

As I mentioned, better use some non-default locale like `'nl_NL'`. No need to test multiple cases I believe.

There is no need to assert that `getDefaultLocale` method was called, such checks are fragile, just check that correct locale is passed into called method of other mock dependency (timeWhatever->someMethod(..., locale instead of null, ...).

2017-08-15 22:24 UTC, orlangur commented
@JeroenVanLeusden feel free to push your test even if it does not work yet, I'll do necessary changes, push and then you'll squash all changes into single commit again.

2017-08-16 07:52 UTC, JeroenVanLeusden commented
@orlangur Pushed my changes so far. `getDefaultLocale()` returns `null` so that will need some work. Waiting for you ping to squash all changes :)

2017-08-18 15:19 UTC, JeroenVanLeusden commented
@orlangur Any progress with the tests? Would love to see this merged.

2017-08-18 15:33 UTC, orlangur commented
@JeroenVanLeusden, yeah, I'll have some time to work on this today, stay tuned.

2017-08-18 21:29 UTC, orlangur commented
So, here is an example of appropriate test: https://github.com/orlangur/magento2/commit/9e58ec25211c53e740ee20c13f5a311aaf44a279

Main idea behind unit tests is that we call only public methods of object under test and all other classes should be replaced with mocks (so, for example, `setDefaultLocale` of `localeResolver` does not work as it does nothing).

Please rebase against `develop` branch, adopt test to PHPUnit 6 to minimize merging efforts (`getMock` -> `createMock`, maybe something else) and then amend all changes into your first commit.

2017-08-19 07:43 UTC, JeroenVanLeusden commented
@orlangur Getting an `Error: Call to undefined method getMock()` on almost all calls. Any idea where this might be coming from?

2017-08-19 15:22 UTC, orlangur commented
@JeroenVanLeusden, I mentioned this, it is called now `createMock`. More details in https://thephp.cc/news/2017/02/migrating-to-phpunit-6

2017-08-20 10:28 UTC, JeroenVanLeusden commented
@orlangur My bad, all good now!

2017-08-22 13:30 UTC, merged