Option to send currency in Google Adwords when using dynamic value
magento/magento2 pull request #10558
Opened 2017-08-16 21:53 UTC by DominicWatts

Introduces option to send currency in adwords when using dynamic value to cope with multisite scenario where base currency differs between websites

### Description
Introduce option to send currency in adwords when using dynamic value.   Configurable via backend. Defaults to off.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/6708

### Manual testing scenarios
1. Enable via API config screen
2. Switch currency
3. Add to basket
4. Complete checkout
5. Observe results within Adwords

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [] All automated tests passed successfully (all builds on Travis CI are green)

2017-08-17 13:30 UTC, ishakhsuvarov commented
@DominicWatts Thank you for this PR. Please take a look at the failed unit and static tests.

2017-08-17 22:51 UTC, DominicWatts commented
The additional changes to the tests I made aren't quite right and I can't work out what's wrong

2017-08-18 07:16 UTC, ishakhsuvarov commented
@DominicWatts I will look into those issues and let you know what is wrong shortly.

2017-08-18 13:35 UTC, ishakhsuvarov requested changes

2017-08-18 13:35 UTC, ishakhsuvarov commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> +    const XML_PATH_SEND_CURRENCY = 'google/adwords/send_currency';
Please add a docblock to the constant with the description of this setting.

2017-08-18 13:35 UTC, ishakhsuvarov commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> +    public function hasSendCurrency()
This naming is ambiguous, I would suggest looking for more descriptive method name.

2017-08-18 13:35 UTC, ishakhsuvarov commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> +     * @return float
Docblock states return type `float` however method returns `string` or `bool`

2017-08-19 15:23 UTC, ishakhsuvarov approved these changes

2017-08-21 18:40 UTC, merged

2019-03-16 23:34 UTC, Ctucker9233 commented
@magento-team Will this be backported to 2.2?