Created memory efficient iterator for importexport_importdata table
magento/magento2 pull request #10918
Opened 2017-09-17 10:59 UTC by diwipl

Default iterator for importexport_importdata table was loading whole table contents to memory, resulting in huge memory usage when importing large numbers of products.

### Description
Additional iterator was created. It gets all rows ids from table and then uses them to return "current" row in memory optimized way.

### Fixed Issues (if relevant)
1. magento/magento2#10914: Huge memory usage when importing large quantities of products

### Manual testing scenarios
1. 1 500 000 entities import should easily run on 8GB RAM server

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-09-17 10:59 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=10918) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=10918) before we can accept your contribution.<br/><hr/>**Krzysztof Kurzydlo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-09-17 11:51 UTC, ishakhsuvarov commented on app/code/Magento/ImportExport/Model/ResourceModel/Import/Data/Iterator.php
> +     * @param null $connectionName
Type hint for this parameter should be `string` as in parent constructor

2017-09-17 12:02 UTC, ishakhsuvarov commented on app/code/Magento/ImportExport/Model/ResourceModel/Import/Data/Iterator.php
> +        $this->rowsIds = $this->getRowsIds();
According to [Magento Technical Guidelines](http://devdocs.magento.com/guides/v2.1/coding-standards/technical-guidelines/technical-guidelines.html#class-design) it is strongly discouraged to perform any operations in the constructor of the class with the exception of Dependency Assignment and Dependency Validation operations.

2017-09-17 12:14 UTC, ishakhsuvarov commented on app/code/Magento/ImportExport/Model/ResourceModel/Import/Data/Iterator.php
> +class Iterator extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
Looks like this iterator may be decomposed into actual iterator and resource model which provides data to the iterator. Current implementation has multiple responsibilities which does not follow SOLID principles.

2017-09-17 12:17 UTC, ishakhsuvarov commented on app/code/Magento/ImportExport/Model/ResourceModel/Import/Data.php
> +        return $this->iteratorFactory->create();
Iterator factory should produce `\Iterator` objects accodring to the method docblock

2017-09-17 12:22 UTC, ishakhsuvarov commented on app/code/Magento/ImportExport/Model/ResourceModel/Import/Data/Iterator.php
> +class Iterator extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
This class should implement `\Iterator`

2017-09-18 10:50 UTC, orlangur requested changes

2017-09-18 10:50 UTC, orlangur commented on app/code/Magento/CustomerImportExport/Model/ResourceModel/Import/CustomerComposite/Data.php
> +        \Magento\ImportExport\Model\ResourceModel\Import\Data\IteratorFactory $iteratorFactory,
See http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter for a correct way to add new dependency.

2017-09-18 10:50 UTC, orlangur commented on app/code/Magento/ImportExport/Model/ResourceModel/Import/Data/DataProvider.php
> +class DataProvider extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
Please name classes properly, not a word-per-folder.

2017-09-18 10:50 UTC, orlangur commented on app/code/Magento/ImportExport/Model/ResourceModel/Import/Data/Iterator.php
> +class Iterator implements \Iterator
Please name classes properly, not a word-per-folder.

2017-10-25 22:08 UTC, orlangur commented
Hi @diwipl, are you going to continue work on this PR?

2017-10-26 06:11 UTC, diwipl commented
Yes, I will. Sorry for the delay.

2017-11-10 12:36 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on pull request and it will be reopened.

2017-11-10 12:36 UTC, closed without merging