Issue #5144 - fix add to cart product and validation required attribute for version CE 2.1
magento/magento2 pull request #10917
Opened 2017-09-17 10:58 UTC by anqaka

Fix add to cart product and validation required attribute for version CE 2.1

### Description
While ajax add to cart on product page is enable, the validation of required arguments not working properly - is doubled, first it shows errors message in empty inputs, then reload the page. 
In version 2.2. this problem doesn't appear.  

### Fixed Issues (if relevant)

#5144

1. magento/magento2#5144: Ajax cart doesn't work

### Manual testing scenarios

1.  Add configurable product to cart from product page with required attributes chosen
2. Add configurable product to cart from product page without required attributes chosen

2017-09-17 10:58 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=10917) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=10917) before we can accept your contribution.<br/>

2017-09-17 21:15 UTC, Igloczek commented on app/code/Magento/Catalog/view/frontend/templates/product/view/addtocart.phtml
> +        <div class="actions siedem">
`siedem` 😉

2017-09-17 21:16 UTC, Igloczek requested changes
Some debugging stuff is still there.

2017-09-18 05:40 UTC, omiroshnichenko commented
Hi, @anqaka! As I know this issue already fixed in develop branch. I found [commit](https://github.com/magento/magento2/commit/690c59d5f1c150440475b02c2b32fbfb8c200c1e) that fix it. Maybe will better if you make backport for this?

2017-09-18 07:06 UTC, omiroshnichenko commented
Also we have internal issue MAGETWO-70892 that currently resolved and in process of delivery.

2017-10-12 12:35 UTC, anqaka commented
@omiroshnichenko I've tried to implement solution from the [commit](https://github.com/magento/magento2/commit/690c59d5f1c150440475b02c2b32fbfb8c200c1e) you had mentioned but it didn't work in 2.1. I think it requires more changes. So if we already have 2.2 released, we can close this issue

2017-10-12 15:43 UTC, anqaka commented
My mistake. In updated 2.1-develop adding to cart using ajax and validation working fine. No more issue here

2017-10-12 15:43 UTC, closed without merging