Handle transparncy correctly for watermark
magento/magento2 pull request #11060
Opened 2017-09-26 13:05 UTC by elzekool

Handle alpha transparency correctly for 24-bit PNG image

### Description
The watermark functionality uses imagecopymerge for copying the
watermark into the image, this function loses the alpha information.

Therefor use imagecopy for 100% opacity and use imagefilter in other
cases.

### Fixed Issues (if relevant)
1. magento/magento2#10661: Opacity png watermark became white box on product images

### Manual testing scenarios
1. Create a 24-bit PNG image with alpha transparency (or use the image in issue in #10661)
2. Configure the image under "Product image watermarks"
3. Leave size empty, set image position to something different than stretch
4. Create a product with a JPEG image
5. See that the watermark is applied with the correct transparency.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-09-30 20:45 UTC, orlangur requested changes

2017-09-30 20:45 UTC, orlangur commented on lib/internal/Magento/Framework/Image/Adapter/Gd2.php
> +            $this->imagecopymergeWithAlphaFix(
I believe the proper name for this function should be something like `copyImage` as we are not even using `imagecopymerge` anymore.

2017-09-30 20:45 UTC, orlangur commented on lib/internal/Magento/Framework/Image/Adapter/Gd2.php
> +    private function imagecopymergeWithAlphaFix(
Please just mention in PHPDoc of this method that signature matches http://php.net/manual/en/function.imagecopymerge.php function but name arguments properly: `$destinationImage`, `$sourceImage`, `$destinationX`, etc.

2017-09-30 20:45 UTC, orlangur commented on lib/internal/Magento/Framework/Image/Adapter/Gd2.php
> +        if (false === $sizeX || false === $sizeY) {
Please convert all Yoda-style conditions to normal ones.

Is checking for `false` really necessary here - do we need to continue execution flow when `$sizeX === 0`?

2017-09-30 20:47 UTC, orlangur commented
Thanks, fix looks quite good in general, especially that you changed all the places. Probably we should even add `imagecopymerge` function to list of disallowed functions :)

Would be really nice to cover fix with integration test using mentioned image. Please tell us if you need any assistance with that.

2017-10-06 13:37 UTC, Koc commented
Have checked manually this PR on my env - works perfectly, thanx.

Does image magick also requires changes?

2017-10-19 07:05 UTC, orlangur commented
Hi @elzekool, are you going to continue work on this PR?

2017-10-20 16:08 UTC, orlangur commented
@Koc no as problematic function `imagecopymerge` belongs to `gd` extension :)

As you already tested this PR, maybe you will be interested in fixing CR notes so that it can be merged? You just need to checkout it locally as described in https://help.github.com/articles/checking-out-pull-requests-locally/, commit your changes on top and create a new PR. With merge of new PR they both will be marked as Merged.

2017-10-29 21:15 UTC, orlangur commented
Ping @Koc @elzekool :)

2017-11-10 12:21 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on pull request and it will be reopened.

2017-11-18 07:20 UTC, elzekool commented
Hi, sorry for the late response. Been realy busy, want to pick it up again

2017-11-19 19:04 UTC, orlangur commented
@elzekool no problem, please go ahead 👍

2018-01-26 20:57 UTC, magento-engcom-team commented
@elzekool thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-01-26 20:58 UTC, okorshenko approved these changes

2018-01-29 17:42 UTC, merged