allow use of changed baseurl instead of storecode append
magento/magento2 pull request #11071
Opened 2017-09-26 14:40 UTC by BlackIkeEagle

Our case:

We want the "default store" to use the website url without appending the
store code.

nl: http://magento2.test/
fr: http://magento2.test/fr/
en: http://magento2.test/en/

The issue:

when you configure your storeview baseurl's as described above you get
404's when switching to the en or fr storeview.

The solution:

When no store is found based on the storecode, try to find and match a
store based on the url given. For our example configuration you also
have to match the longest since the nl store given will also match when
going to the fr or en store.

Append Storecode:

Since the storecode is mandatory in magento we cannot use the append
storecode to achieve our goal.

Signed-off-by: BlackEagle <ike.devolder@gmail.com>

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-09-26 16:57 UTC, orlangur commented on app/code/Magento/Store/App/Request/PathInfoProcessor.php
> +                $pathInfo = preg_replace('#^' . $baseUrlPath . '#', '', $pathInfo);
`preg_replace` is misused here. Just compare string beginning and then do `str_replace`.

2017-09-26 16:58 UTC, orlangur commented on app/code/Magento/Store/App/Request/PathInfoProcessor.php
> +                $store = $this->storeManager->getStoreByUrl($requestUri);
Implementation must rely on `StoreManagerInterface`, not on current implementation of `StoreManager`.

2017-09-26 16:59 UTC, orlangur commented on app/code/Magento/Store/App/Request/PathInfoProcessor.php
> +                $pathInfo = preg_replace('#^' . $baseUrlPath . '#', '', $pathInfo);
`preg_replace` is misused here. Just compare string beginning and then do `str_replace`.

2017-09-26 16:59 UTC, orlangur requested changes

2017-09-26 16:59 UTC, orlangur commented on app/code/Magento/Store/App/Request/PathInfoProcessor.php
> +                $store = $this->storeManager->getStoreByUrl($requestUri);
Implementation must rely on `StoreManagerInterface`, not on current implementation of `StoreManager`.

2017-10-07 21:20 UTC, BlackIkeEagle commented
@orlangur and @vrann I need to update this further, I'll look at it later next week.

2017-11-10 15:06 UTC, ishakhsuvarov commented
Hi @BlackIkeEagle
Are you still interested in working on this?

2017-11-11 07:28 UTC, BlackIkeEagle commented
@ishakhsuvarov No I'm sorry, When I have the time I'll create a new PR with a proper solution

2017-11-11 07:28 UTC, closed without merging