Added minimal price to configurable product upon fetching via API
magento/magento2 pull request #11123
Opened 2017-09-28 16:13 UTC by rogyar

Description

Upon getting a configurable product via API (/rest/V1/products/:sku) the product does not contain any useful information about the price. The minimal price is useful here in order to avoid additional requests to the API for getting the configurable product price information.

Fixed Issues

magento/magento2#10644: REST API Configurable Product has price
Manual testing scenarios

Create a configurable product accessible on the storefront
Get the product information via API using GET request to the rest/V1/products/:sku
You should get a minimal price among the custom attributes for the configurable product.

2017-09-28 16:16 UTC, orlangur requested changes

2017-09-28 16:16 UTC, orlangur commented on app/code/Magento/Catalog/Model/ProductRepository.php
> +use Magento\ConfigurableProduct\Model\Product\Type\Configurable;
You cannot refer to `ConfigurableProduct` module in `Catalog`.

2017-09-28 16:18 UTC, rogyar commented
The magento/magento2#10644 issue is fixed only partially in this PR. But I guess this PR can be reviewed as a separate improvement. 
As for the configurable products in the list (related to the mentioned issue), it's quite difficult to have a minimal price only for the configurable products without making "tweaks" like adding minimal price to the collection and then loop through the products from the loaded collection to remove the minimal price from the simple products.

2017-09-28 16:26 UTC, orlangur commented on app/code/Magento/Catalog/Model/ProductRepository.php
> +use Magento\ConfigurableProduct\Model\Product\Type\Configurable;
As far as I remember I already asked in previous PR but it was force pushed or something.

I don't see a good way to move such addition to `ConfigurableProduct` module and I don't see disadvantages of having `min_price` for simple product (for example, if simple product has non-free custom options, price without any of them would be minimal).

@vrann thoughts?

2017-11-24 15:56 UTC, vkublytskyi commented
@rogyar Please fix failed tests

2018-02-01 15:15 UTC, LSERRE reviewed
I need it so much

2018-02-04 08:45 UTC, rogyar commented
Hello @LSERRE. Unfortunately, at this moment I don't have enough time to fix all tests because many tests are related to this issue and the new behaviour is not acceptable.

2018-02-04 11:43 UTC, LSERRE commented
Hello @rogyar. I simply did a plugin in a custom module on app/code/Magento/ConfigurableProduct/Model/Product/Type/Configurable/Price.php. I used your logic so thank you anyway, my problem is resolved.

2018-04-23 16:22 UTC, magento-engcom-team commented
Hi @rogyar 
We are closing this Pull Request now due to inactivity.
If you would like to revisit this in the future – please take a look at the failed tests and reopen.

Thank you for collaboration

2018-04-23 16:22 UTC, closed without merging