Recollect totals on customer address save #10567
magento/magento2 pull request #11217
Opened 2017-10-04 12:48 UTC by tprocter-ldg

Recollect totals on customer address save. This refreshes the minicart and cart totals when a new customer group is assigned on address save. The customer group can have different tax classes assigned to it and this pull request will recollect the totals to reflect these changes. 

The outer if statement has been removed from the getRateRequest() method so that if the customerId is not set then it retrieves the customer tax class from the customer session. 

An update to the Customer/../sections.xml so that on address formPost, the cart and checkout-totals are refreshed. 

And in the afterSave() method the recollect totals flag is set. 

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/10567

Testing steps can be found on the above link. (It's quite lengthy sorry!)

2017-10-04 12:48 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=11217) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11217) before we can accept your contribution.<br/>

2017-10-04 18:15 UTC, convenient commented on app/code/Magento/Customer/Model/Address.php
> +        $quote->getResource()->save($quote);
I don't work for magento but have worked on this kind of issue before.

Would it not be safer to apply the `trigger_recollect` flag on the quote, and let the next interaction of the checkout session handled the collection and saving as part of its normal flow?

2017-10-05 12:38 UTC, vrann commented
@tprocter-ldg can you please clarify steps to reproduce:

Why should the price be different for the General and Zero VAT Customer groups if 'Rate Percent: 0.00' and no other settings are enabled out of the box?

2017-10-05 12:51 UTC, tprocter-ldg commented
Hi @vrann

Steps to reproduce:
Product example being used:
 - Including VAT price 447,00 €
 - Excluding VAT price 369,42 €

1. Go to the frontend as a guest and add an item to your basket.
2. Minicart shows product as 447,00 €
3. Go to login as a new customer.
4. Add your address & vat number when prompted (default functionality).
5. You should receive the 'Your vat id has been successfully validated. You will not be charged tax' message. At this point you are assigned the Zero VAT customer group.
6. Go back to the frontend and notice that all the prices in the category and product pages are now showing the VAT discount (369,42 €).
7. Go to the cart and/or the minicart to view the product you added prior to registration

Expected result:
1. Prices and totals are updated to reflect the VAT discount
ie: product price and total should be 369,42 €.
2. Add another product and view the cart and/or minicart. This product should show the VAT discount price which is reflected on the product page.

Actual result:
1. Prices and totals still show the full price in cart/minicart (447,00 €).
2. Add another product and view the cart and/or minicart. This product also shows as including full vat.
3. Go through to the checkout. Choose your shipping option and click next button.
4. Before proceeding with payment go back to the homepage.
5. Click the minicart and update your product quantity.
6. The prices and totals refresh to show the correct discounted price (369,42 €).

2017-10-06 15:11 UTC, vrann requested changes

2017-10-06 15:11 UTC, vrann commented on app/code/Magento/Customer/Model/Address.php
> +        Session $checkoutSession,
please introduce dependency in backward compatible way
http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter

2017-10-06 16:01 UTC, TomashKhamlai commented
Hello, @tprocter-ldg, I found a problem when tried to test this code in real use cases.
Can you try this steps on your developing environment? I've got Fatal Error when tried to save Customer with VAT number on CentOS with
PHP 7.0.23 from Webtatic repo and got when tried to save Customer with VAT number. Have any idea why this could happen?

**Steps to Reproduce:**

1. Go to Stores -> Taxes -> Tax Rules
2. Click button 'Add New Tax Rule'
> Tax Rule Information:
- Name: Zero VAT
- Tax Rate: Click ‘Add New Tax Rate’
- Tax Identifier: Zero VAT
- Zip/Post is Range: unticked
- Zip/Post Code: **
- State: **
- Country: United States
- Rate Percent: 0.00
> Additional Settings:
- Customer Tax Class: Click ‘Add New Tax Class’
- Zero VAT Customer
Press the tick
- Ensure this is the only tax class highlighted
- Product Tax Class: Click ‘Add New Tax
- Zero VAT Product
Press the tick
- Ensure this is the only tax class highlighted
- Priority: 0
- Calculate Off Subtotal Only: unticked
- Sort Order: 0
'Save Rule'
3. Go to Stores -> Other Settings -> Customer Groups
4. Click 'Add New Customer Group'
> Group Information:
- Group Name: Zero VAT Customer Group
- Tax Class: Zero VAT Customer
'Save Customer Group'
5. Go to Stores -> Configuration -> Customers -> Customer Configuration -> Create New Account Options
- Enable Automatic Assignment to Customer Group : YES
- Group for Valid VAT ID - Domestic : Zero VAT Customer Group
- Group for Valid VAT ID - Intra-Union : Zero VAT Customer Group
- Group for Invalid VAT ID : General
- Validation Error Group : General
-  Validate on Each Transaction : NO
- Show VAT Number on Storefront : YES
'Save Config'
6, Go to Stores -> Configuration -> Sales -> Tax
> Calculation Settings:
- Catalog Prices: (!) Including Tax
- Shipping Prices: (!) Including Tax
- Apply Discount On Prices: (!) Including Tax
> Price Display Settings
- Display Product Prices In Catalog : Including Tax
- Display Shipping Prices : Including Tax
- Shopping Cart Display Settings
- Display Prices : Including and Excluding Tax
- Display Subtotal : Including and Excluding Tax
- Display Shipping Amount : (!) Including Tax
'Save Config'
7. Go to Stores -> Configuration -> General -> Curreency Setup -> Currency Options
- Base Currency: Euro
- Default Display Currency: Euro
- Make sure that US Dollar and Euro are enabled in Allowed Currencies multiselect list
'Save Config'
8. Go to Catalog -> Catalog -> Products
9. Click 'Add New Product'
- Product Name: simple1
- SKU: simple1
- Price: 447€
- Tax Class: Taxable Goods
- Quantity: 1000
- Weight: 1
Categories: Click 'New Category'
- Category Name: cat1
- Parent Category: Default Category
- 'Create Category'
'Save & Close'
10. Go to Storefront
11. Add simple1 product to the Shopping Cart
12. Click 'Create an Account'
- First Name: John
- Last Name: Doe
- Email: John.Doe@example.com
- Password: Any(Password Strength should be Strong
'Create an Acount'
(!) If you are a registered VAT customer, please click *here* to enter your billing address for proper VAT calculation.
13. Click on 'click here' link and then fill all the necessary fields and VAT Number
- Phone Number: 555-55-555-55
- Street Address: 6161, West Sentinella
- VAT Number: 815302464
- City: Culver City
- State/Province: California
- Zip/Postal Code: 90230
- Country: United States
'Save Address'

Expected result: You saved the address.
Actual result: ???

2017-10-24 19:39 UTC, vrann commented
@tprocter-ldg can you please help us to test this issue?

2017-11-28 22:13 UTC, okorshenko commented
Hi @tprocter-ldg 
We are closing this PR due to inactivity. Feel free to reopen this PR once ready

2017-11-28 22:13 UTC, closed without merging