The quote address fields length expanded in the database
magento/magento2 pull request #11286
Opened 2017-10-07 09:21 UTC by rogyar

### Description
The following fields length has been expanded in the `quote_address` database table:
- telephone
- fax
- region
- city

### Fixed Issues (if relevant)
1. magento/magento2#10869: field lengths differ across many tables
2. magento/magento2#10868: field lengths differ across many tables

### Manual testing scenarios
1. Add some products to the shopping cart and go to checkout
2. Put some long value into the city field (or region, telephone, fax) up to 255 chars.
3. Place the order.
4. The corresponding fields values should not be cut in the `quote_address` database table

2017-10-16 07:38 UTC, orlangur approved these changes
Looks great to me, for the reference - values restored are the same as in https://github.com/magento/magento2/commit/cb3914bc3a9e5e60e32306466bc054900c014909#diff-78dad85ac24baac9f8f56748e920549e.

2017-10-16 08:00 UTC, orlangur requested changes

2017-10-16 08:00 UTC, orlangur commented on app/code/Magento/Quote/Setup/UpgradeSchema.php
> +                    'length' => 255,
Currently this method is not passing PHPMD:
```
1) Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/home/travis/build/magento/magento2/app/code/Magento/Quote/Setup/UpgradeSchema.php:25	The method upgrade() has 111 lines of code. Current threshold is set to 100. Avoid really long methods.
```

Please try to reformet method in more compact manner, import `\Magento\Framework\DB\Ddl\Table` (`Alt + Enter` in PhpStorm) and you can easily fit `['type => ..., 'length' => ...]` in one line and make it more readable.

Feel free to reformat lines not introduced in your PR, if polishing up will be not enough to fit into 100 lines - refactor contents of `if (version_compare($context->getVersion(), '2.0.7', '<')) {` into a private method.

Please use a commit amend + force push.

2017-10-26 10:54 UTC, orlangur commented
Hi @rogyar, please tell us if any assistance is needed.

2017-10-29 15:21 UTC, rogyar commented
I've refactored the solution in order to have the static tests green. Thanks

2017-10-30 09:12 UTC, orlangur approved these changes

2017-11-28 20:04 UTC, merged