Duplication of Grouped Products does not work as expected
magento/magento2 pull request #11321
Opened 2017-10-09 21:30 UTC by crissanclick

### Description
When grouped product is duplicated the simple products links doesn't copied.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/10679

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-13 14:56 UTC, crissanclick commented
What information do you need? @vkublytskyi @magento-team

2017-10-13 15:15 UTC, vkublytskyi commented
@crissanclick, needs update label was added by mistake. Sorry for disturbing you. We are still verifying your fix.

2017-10-13 15:43 UTC, crissanclick commented
Ok!!! Thanks!

2017-11-21 14:21 UTC, vkublytskyi requested changes
Provided fix is not full and does not cover next scenario:
1. Go to Admin > Catalog > Product > Add Simple Product
2. Fill all required fields and click Save button
1. Go to Admin > Catalog > Product > Add Grouped Product
2. Fill all required fields and add created simple product as Grouped product.
3. Click SAve & Duplicate.

Duplicated product will not have linked simple product.

If Grouped product already exists and new product added to group and after this click on Save & Duplicate then duplicated broduct will not have added products.

The same issue occurs with other "linked" products (up-sells, cross-sells, ralated).

Product links are properly stored only if they are available in product during product save.

```php
//\Magento\Catalog\Model\Product\Link\SaveHandler::execute

$productLinks = $entity->getProductLinks();
if (count($productLinks) > 0) {
     foreach ($entity->getProductLinks() as $link) {
          $this->productLinkRepository->save($link);
     }
}
```

As duplicate product does not have links they are missed in duplicate.

In some flows, this issue may be hidden by cache usage but cache is not an issue and it should be cleaned on product save as after saving some properties may expects reload.

To provide a valid fix seems we should add one more implementation of `\Magento\Catalog\Model\Product\CopyConstructorInterface` which will copy product links on product duplication.

2017-12-13 10:57 UTC, okorshenko commented
Hi @crissanclick 
We are closing this PR due to inactivity. Feel free to reopen it once ready

2017-12-13 10:57 UTC, closed without merging