#11211 Fix Store View switcher
magento/magento2 pull request #11337
Opened 2017-10-10 11:45 UTC by thiagolima-bm

Store View switcher not working on front-end and it throws an error #11211

2017-10-20 08:59 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=11337) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11337) before we can accept your contribution.<br/><hr/>**Thiago Lima** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-10-20 15:07 UTC, vkublytskyi requested changes

2017-10-20 15:07 UTC, vkublytskyi commented on app/code/Magento/Store/Model/Store.php
> +        if ($this->getCode() !== $this->_storeManager->getStore()->getCode()) {
@thiagolima-bm Please explain why usage of `__from_store` query parameter should be used.

2017-10-20 15:07 UTC, vkublytskyi commented on app/code/Magento/Store/Model/Store.php
> +            $currentUrl .= $requestString;
`$requestCode` also contains path and this data may be lost

STR:
- go to Privacy and Cookie Policy
- switch store view (store view switched, user still on Privacy and Cookie Policy)
- switch store view again (store view switched, user on main page but should be on Privacy and Cookie Policy)

2017-10-20 15:07 UTC, vkublytskyi commented on app/code/Magento/Store/Model/Store.php
> +        $currentUrl .= ($storeParsedQuery ? '?' . http_build_query($storeParsedQuery, '', '&amp;') : '');
I think the source of the issue is concatenation with `?` while `$requestString` may contain query. To fix this I propose:
1. Split `$requestString` into path and query:
```php
$requestStringParts = explode('?', $requestString, 2);
$requestStringPath = $requestStringParts[0];
if (isset($requestStringParts[1])) {
   parse_string($requestStringParts[1], $requestStringQuery);
} else {
    $requestStringQuery = []
}
```
2. Merge original query params and store parsed query
```php
$currentUrlQueryParams = array_merge($requestStringQuery, $storeParsedQuery);
```
3. Safely concatenate all parts of url:
```php
$currentUrl = $storeParsedUrl['scheme']
    . '://'
    . $storeParsedUrl['host']
    . (isset($storeParsedUrl['port']) ? ':' . $storeParsedUrl['port'] : '')
    . $storeParsedUrl['path']
    . $requestStringPath
    . ($currentUrlQueryParams ? '?' . http_build_query($currentUrlQueryParams, '', '&amp;') : '');
```

2017-10-21 11:59 UTC, thiagolima-bm commented on app/code/Magento/Store/Model/Store.php
> +        if ($this->getCode() !== $this->_storeManager->getStore()->getCode()) {
for tracking, maybe?

2017-10-21 12:04 UTC, thiagolima-bm commented
@vkublytskyi fixes applied.

2017-10-30 12:54 UTC, vkublytskyi approved these changes

2017-10-31 17:05 UTC, merged

2017-12-22 09:03 UTC, chiragit007 commented
45

2018-02-05 17:17 UTC, rsulym commented
Gents, still not able to manage this issue to get it work ((
Version 2.2.1, cannot upgrade to 2.2.2
Is this file (Store.php) is complete fix which i need?
https://github.com/thiagolima-bm/magento2/blob/84729b581638e00459fcca63bb6d7a1c77f252b9/app/code/Magento/Store/Model/Store.php