PHP Livecodetest testCodeStyle() method does not use whitelist files
magento/magento2 pull request #11362
Opened 2017-10-11 05:10 UTC by adrian-martinez-interactiv4

### Description
\Magento\Test\Php\LiveCodeTest::testCodeStyle method does not use whitelist files, as it does \Magento\Test\Php\LiveCodeTest::testCodeMess. Because of that, it takes ages to complete when you only want to test code style for a few modified files.

### Fixed Issues (if relevant)
Improvement

### Manual testing scenarios
1. Create (manually, via git diff, via get_github_changes.php script) Magento/Test/_files/changed_files_local.txt, with references to real modified files to be tested.
2. Run vendor/bin/phpunit --verbose -c dev/tests/static/phpunit-all.xml.dist.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-11 07:18 UTC, orlangur commented
It was done intentionally in https://github.com/magento/magento2/pull/8685 and should not be ever changed in order to avoid regression of fixed problem. PHPCS run takes only few minutes while PHPMD would take hours.

Behavior of `$changedFiles = self::getChangedFilesList($changedFilesBaseDir);` can be slightly changed in your particular project if current one does not work well.

2017-10-11 13:02 UTC, orlangur commented
Current implementation needs to be changed so that:
- 100% whitelisted files check is preserved on any CI
- it is possible to run a reduced check locally

2017-10-11 13:48 UTC, orlangur requested changes

2017-10-11 13:48 UTC, orlangur commented on dev/tests/static/phpunit.xml.dist
> +        <env name="phpunit.static.testcodestyle.use_whitelist" value="0"/>
I suggest changing it to `testcodestyle.is_full_scan` and default `1` value.

I'm not sure whether it's better to use env or const, like we do in integration tests `<const name="TESTS_CLEANUP" value="enabled"/>`.

2017-10-11 13:48 UTC, orlangur commented on dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php
> +            && $_ENV['phpunit.static.testcodestyle.use_whitelist'] === '1';
Simply `$whitelist = !empty(...is_full_scan...) ? ... `

Please use both `php` and `phtml`.

2017-10-11 14:27 UTC, orlangur approved these changes

2017-10-12 22:42 UTC, adrian-martinez-interactiv4 commented
@vrann I updated this PR to include new const also in phpunit-all.xml.dist file, and add comments, could you check the commit associated to this PR? https://github.com/magento/magento2/pull/11362/commits/205c2f902456a1dea6753916afec7b8cd57d62b0

The one added in MAGETWO-81646 - https://github.com/magento/magento2/commit/bf50355dc656bb9b3b192d63fc413964b066865d does not include the last change, and due to this, conflicts have raised: https://github.com/magento/magento2/pull/11362/conflicts.

2017-10-13 10:30 UTC, orlangur commented
@adrian-martinez-interactiv4 it cannot be reverted, please apply these additional changes on top of new `develop` and force push to the same branch.

2017-10-13 12:06 UTC, adrian-martinez-interactiv4 commented
@orlangur Done

2017-10-16 09:00 UTC, orlangur commented
@adrian-martinez-interactiv4 

```
Magento\Test\Php\LiveCodeTest::testCodeStyle
PHPUnit\Framework\Exception: Warning: file_get_contents(.../magento2/dev/tests/static/report/phpcs_report.txt): failed to open stream: No such file or directory in .../magento2/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php:212.

...1/magento2/dev/tests/static/framework/bootstrap.php:56
.../magento2/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php:212
```

Somehow it is not passing on Bamboo currently, I need some time to find out why. No action required from your side, just some patience :)

2017-11-22 06:08 UTC, ihor-sviziev commented
@orlangur it looks like after https://github.com/magento/magento2/commit/f59cfe252d2f04fcc7a7e04dea95202d1e8ffc15 issue should gone away. Could you re-check?

2017-11-22 15:34 UTC, orlangur commented
@ihor-sviziev it is just a workaround, I need to find out how such changes broke the Bamboo CICD loop.

2018-02-03 04:01 UTC, merged