FIX #11022 in 2.1-develop: Filter Groups of search criteria parameter have not been included for further processing
magento/magento2 pull request #11432
Opened 2017-10-13 13:27 UTC by davidverholen

### Description

The Filter Groups and the Sort Order of the $searchCriteria parameter have not been included in the searchCriteria Object that is finally provided for the eav set repository.

This Pull request sets the filtergroups and sort order in the searchCriteriaBuilder

### Fixed Issues (if relevant)

1. magento/magento2#11022: GET v1/products/attribute-sets/sets/list inconsistent return result

### Manual testing scenarios

1. Create an additional product attribute set
1. call to GET http://URL/rest/v1/products/attribute-sets/sets/list?searchCriteria[filter_groups][0][filters][0][field]=attribute_set_name&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=default
2. Result should be only the default attribute set (before it always returned all product attribute sets)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

//cc @dmanners

2017-10-27 12:05 UTC, dmanners requested changes
This does not actually seem to fix this problem in 2.1

2017-10-27 12:06 UTC, dmanners commented
@davidverholen after testing this with 2.1 it does not actually seem to fix the issue. When you call the described API endpoints you still get all the data back. Unlike the 2.2 fix which showed only those that match the search.

2017-11-03 09:13 UTC, davidverholen commented
@dmanners the problem is, that the filters of the search criteria are ignored in the eav attribute repository getList function in 2.1.

I've added a workaround which should fix this until it's replaced by the CollectionProcessor in 2.2

2017-11-04 10:32 UTC, dmanners commented on app/code/Magento/Eav/Test/Unit/Model/AttributeSetRepositoryTest.php
>          $filterGroupMock->expects($this->once())->method('getFilters')->willReturn([$filterMock]);
@davidverholen I think this is the method that needs to be called more than once in the tests.

2017-11-09 21:09 UTC, merged