Cart Price Rule Label is not working
magento/magento2 pull request #11438
Opened 2017-10-13 16:45 UTC by mrodespin

Description

Cart Price Rule Label is not working. The Total label for discounts was not the correct one, after this fix the label was "Discount" and with this change is the Cart Rule Label.

Steps to reproduce

1. While creating the cart price rule, I have given the Label value as "Buy 2 and Get 1 Free".
2. In front end, Checkout page, It will show only the label as "Discount" not the given name has been reflected.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-13 18:44 UTC, adrian-martinez-interactiv4 commented
I leave here a reference to the related issue: #11428

2017-10-16 05:33 UTC, ghost requested changes
We have tested with this solution it's working but it's displayed "Discount" Before label. I think It's should not be display If a label is set. @mrodespin  Please consider covering the updated flow with the test.

2017-10-16 11:56 UTC, mrodespin commented
@emiprotech I didn't remove the Discount label because it how it works in previous magento versions.

2017-10-17 18:24 UTC, mrodespin commented
@magento-team i seen than you added a needs update label, but i don't know why. What i have to modify??

2017-10-17 19:04 UTC, okorshenko commented
Hi @mrodespin we are trying to align your solution with the documentation http://docs.magento.com/m2/ce/user_guide/marketing/price-rules-cart.html

2017-10-17 19:10 UTC, mrodespin commented
@okorshenko ok  i  will wait then. Can you add the partner contribution label to my commits?

2017-10-19 18:09 UTC, okorshenko commented
Hi @mrodespin, unfortunately, we can not accept this changes. Please see the comment here: https://github.com/magento/magento2/issues/11428#issuecomment-337990525

2017-10-19 18:09 UTC, closed without merging

2017-10-20 13:41 UTC, pmoreno1980 commented
@okobchenko here we have 2 situations for this issue (Cart Price Rule Label is not working):

Shopping Cart Rules with Coupon Code and this is the solution for that https://github.com/magento/magento2/issues/6244

Shopping Cart Rules without Coupon Code, i mean automatic discount, we don't have solution for this yet, this #11438 doesn't work.

this is a very important problem that is not solved in Magento 2. we didn't have this issue on Magento 1

thanks for you help

2017-10-26 20:22 UTC, pmoreno1980 commented
any update here? its a big bug, i know that is fixed on enterprise version.

please let me know

2018-03-05 06:31 UTC, versdivers commented
I have the same issue.  Filled in all the labels. Frontend just says 'Discount'

2023-10-18 00:16 UTC, soniclouds commented
Any updates on this???  Using 2.4.2 and same exact issue.  Labels not working when applying cart rule without coupon code.