Fix Support for new Email address domain #4547
magento/magento2 pull request #11576
Opened 2017-10-20 09:00 UTC by elachino

### Description
Fix support for all new domain in email address validation. This solution can be apply to rewrite all Zend_Validate::is with ZendFramework2. I propose only change to fix email validation in this PR.
You have to upgrade zend-validator module to last version from 2.5 to up, or you can get from magento 2.2.

### Fixed Issues (if relevant)

1. magento/magento2#4547: Support for new .tech TLD and others required

### Manual testing scenarios
1. try to recover a password from an email with some new domain like .shop or .srl

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-20 09:00 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=11576) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11576) before we can accept your contribution.<br/>**5** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: vkublytskyi<br/>:white_check_mark: Januszpl<br/>:white_check_mark: szafran89<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: Igloczek<br/>:x: VladimirZaets<br/>:x: viktym<br/>:x: OlgaVasyltsun<br/>:x: kandy<br/>:x: Stas Kozar<hr/>**Stas Kozar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-10-20 09:17 UTC, orlangur commented
> You have to upgrade zend-validator module to last version from 2.5 to up, or you can get from magento 2.2.

This should be done in scope of this PR: https://github.com/magento/magento2/blob/2.1-develop/composer.json#L17 Commit both `composer.json` and `composer.lock`. Please use least version suitable, `2.5.x` should be fine probably.

2017-10-20 09:28 UTC, orlangur requested changes

2017-10-20 09:28 UTC, orlangur commented on app/code/Magento/Config/Model/Config/Backend/Email/Address.php
> +        if(!$validator->isValid($value)){
Please fix formatting in all changed lines. 4 spaces must be used as indentation, there should be a space after `if` etc.

2017-10-20 09:28 UTC, orlangur commented on app/code/Magento/Config/Model/Config/Backend/Email/Address.php
> +        if(!$validator->isValid($value)){
Great 👍 Besides formatting changes look good to me.

Please also fix `\Magento\Newsletter\Controller\Subscriber\NewAction::validateEmailFormat`.

2017-10-23 16:30 UTC, elachino commented
I update with your requests, please re-check

2017-10-23 16:55 UTC, orlangur commented
@elachino, https://github.com/magento/magento2/pull/11576/files - formatting is still not fixed, `composer.lock` is not committed.

Please check integration and static tests failures on Travis also, they must be green for this PR to be processed.

After all changes are made and all builds are green, please squash all changes into single commit and force push to the same branch.

2017-10-24 13:23 UTC, orlangur commented on composer.lock
> +                "zendframework/zend-validator": "^2.6",
Did you change this file manually? I don't see `content-hash` updated.

2017-10-24 13:27 UTC, elachino commented
Yes, i do.
I copy only different row from my repository.
If you prefer i update with composer.


Alessandro Scavella | Co-founder @COODER | E-commerce & Mobile | Cooder.it <http://cooder.it/> | Personal number: 327/5431980




____________________________________________________
Avviso di riservatezza
questo messaggio è destinato unicamente alla persona o al soggetto ai quali è indirizzato e può contenere informazioni riservate e/o coperte da segreto professionale, la cui divulgazione è proibita. Qualora non siate i destinatari designati non dovrete leggere, utilizzare, diffondere o copiare le informazioni trasmesse (D.Lgs n.196/2003). Nel caso aveste ricevuto questo messaggio per errore, vogliate cortesemente contattare il mittente e cancellare il materiale dai vostri computer.
Notice of confidentiality
this message is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged information, the disclosure of which is prohibited. If you are not the intended recipient you may not read, use, disseminate or copy the information transmitted. If you have received this message in error, please contact the sender and delete the material from any computer.

> Il giorno 24 ott 2017, alle ore 15:24, Vlad Veselov <notifications@github.com> ha scritto:
> 
> @orlangur commented on this pull request.
> 
> In composer.lock <https://github.com/magento/magento2/pull/11576#discussion_r146557427>:
> 
> > @@ -2003,7 +2003,7 @@
>                  "zendframework/zend-servicemanager": "~2.4.0",
>                  "zendframework/zend-session": "~2.4.0",
>                  "zendframework/zend-text": "~2.4.0",
> -                "zendframework/zend-validator": "~2.4.0",
> +                "zendframework/zend-validator": "^2.6",
> Did you change this file manually? I don't see content-hash updated.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/magento/magento2/pull/11576#pullrequestreview-71515688>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AHFTpIEYFT2jRYrPIP6cpgJ8g-puk56wks5sveT_gaJpZM4QAYQe>.
>

2017-10-24 13:30 UTC, orlangur commented
@elachino, yeah, it does not work this way, just run `composer update zendframework/zend-validator` with your updated `composer.json`.

2018-04-23 19:36 UTC, ihor-sviziev commented
Hi @orlangur  do you need any help in reviewing this PR?

2018-07-10 22:59 UTC, orlangur approved these changes
I wasn't sure `composer require zendframework/zend-validator:^2.6.0` can actually work on `2.1-develop`.

Now I checked it worked, conflict in `composer.lock` can be fixed on our side.

2018-08-01 13:51 UTC, orlangur approved these changes

2018-08-13 15:35 UTC, josefbehr commented
@elachino please resolve the merge conflict

2018-08-14 13:25 UTC, orlangur commented
@josefbehr not needed, it's better to be resolved on our side as I mentioned.

2018-08-14 13:48 UTC, ihor-sviziev approved these changes

2018-08-14 17:43 UTC, elachino commented
I'm out for holiday, when return on 21 august I try to resolve it.
Kind regards

Il lun 13 ago 2018, 17:35 Josef Behr <notifications@github.com> ha scritto:

> @elachino <https://github.com/elachino> please resolve the merge conflict
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/11576#issuecomment-412561070>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHFTpMVq4NVWYvTviiVCznKlVi31bkYGks5uQZzYgaJpZM4QAYQe>
> .
>

2018-09-14 10:31 UTC, ihor-sviziev commented
Hi @elachino,
I tried to merge conflicts in your PR, but got an issue that another zendframework/zend-* packages has dependencies to zendframework/zend-validator: "~2.5", so actually we can't update it without updating another modules

2018-09-18 05:12 UTC, merged

2018-09-18 05:13 UTC, magento-engcom-team commented
Hi @elachino. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.16. 
Please check the release notes for final confirmation.