Changed Validation to get store for block
magento/magento2 pull request #11601
Opened 2017-10-20 23:03 UTC by osrecio

Changed validation to `getIsUniqueBlockToStores`
### Description

Changed validation to get `DEFAULT_STORE_ID` when the app is setted with `SingleStoreMode` in the other cases get store from object

### Fixed Issues (if relevant)
1. magento/magento2#4831: Inconsistent cms block validation and save methods
2. ...

### Manual testing scenarios
1. Make sure that you have only one store view and SingleStoreMode option to `no`
2. Create cms block example for All Store views
3. Create another cms block example for first store view only

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-26 11:29 UTC, dmanners commented
So as far I a see this fixes the issue raised but there is another issue with the block validation. In my testing I setup a multi store system so there are two store views for a website. I then added 2 blocks with the id example for store 1 and store 2. I then went to add a 3rd block to store 2 with the id example and the system lets me do this. My thinking is that the validation should check to make sure you are not adding the same block twice to the same store.

![blocks](https://user-images.githubusercontent.com/1572836/32050596-ae41ebac-ba51-11e7-85a5-289a17f462e8.png)

2017-10-26 11:56 UTC, dmanners commented on app/code/Magento/Cms/Model/ResourceModel/Block.php
>              $stores = (array)$object->getData('stores');
The store validation seems to be broken here as the data set on the object is under `store_id` and not `stores`.

2017-10-26 11:56 UTC, dmanners requested changes
Store validation seems to not work anyway.

2017-10-26 12:01 UTC, dmanners commented on app/code/Magento/Cms/Model/ResourceModel/Block.php
>              $stores = (array)$object->getData('stores');
Or maybe better still would be to use the `getStores` method that is against the Block model.

2017-10-27 10:08 UTC, dmanners approved these changes
The validation issue I raised has been solved in https://github.com/magento/magento2/pull/11802

2017-10-27 23:00 UTC, osrecio commented
Yes is my teamate @thiagolima-bm , You can close this ticket he was more fast than me hehe

2017-10-28 12:26 UTC, dmanners commented
@osrecio nothing to do now with this pr. We will process both of them to improve/fix the cms block admin experience. Thank you for your code.

2017-10-30 16:29 UTC, osrecio commented
Solved this PR in magento/magento2/pull/11802

2017-10-30 17:39 UTC, closed without merging