Typo: fix https://github.com/magento/magento2/pull/11296#commitcomment-25105509
magento/magento2 pull request #11609
Opened 2017-10-21 04:14 UTC by ajpevers

Typo: fix https://github.com/magento/magento2/pull/11296#commitcomment-25105509

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-21 15:18 UTC, orlangur approved these changes

2017-10-21 15:22 UTC, orlangur requested changes
Please fix all occurrences, another one in `app/code/Magento/Store/i18n/en_US.csv` 😉

2017-10-22 08:03 UTC, ajpevers commented
Thanks @orlangur.

2017-10-23 10:29 UTC, orlangur approved these changes

2017-10-24 02:09 UTC, merged