2.2 develop 11032 Unable to add new options to swatch attribute
magento/magento2 pull request #11628
Opened 2017-10-22 09:30 UTC by springerin

ProductAttributeOptionManagementInterface#add() doesn't do anything.

### Description

On the beforeBeforeSave(Attribute $attribute) in the case of a swatch attribute, expects an array with key swatchtext / swatchvisual ( first in case of textswatch, second in case of visualswatch) that overwrites the option array originally given, so if this is empty, it will be emptied as well. So I added a plugin that right before doing this, creates the expected array that will be used later for the creation of the actual option. 

### Fixed Issues (if relevant)

1. magento/magento2#11032: Unable to add new options to swatch attribute
2. magento/magento2#9410: Impossible to add swatch options via Service Contracts if there is no existing swatch option for attribute

### Manual testing scenarios

1.  Call the rest api http://<magento-url>/index.php/rest/V1/products/attributes/color/options to add a new color option with the following input 
`{
  "option": {
    "label": "new color",
    "value": "",
    "sort_order": 0,
    "is_default": true,
    "store_labels": [
      {
        "store_id": 0,
        "label": "new color"
      },
      {
        "store_id": 1,
        "label": "new color"
      }
    ]
  }
}`
2. Check from the admin area that your new option is there or call the rest api http://<magento-url>/index.php/rest/V1/products/attributes/color/options

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-26 07:37 UTC, springerin commented
gonna fix what failed this weekend.

2017-10-27 11:35 UTC, dmanners requested changes
There are a couple of comments that should be addressed, also I am still not 100% sure about this PR if it is the "correct" way to fix this bug.

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected $eavConfig;
since we have a new class here the default is to stay away from protected in properties and functions. Recommended is private unless the method is needed outside the class.

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        $this->eavConfig                   = $eavConfig;
spacing looks a bit off here

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        if (!empty($isSwatch) && $attribute->getData($optionKey) === null
Could you maybe update this to look as follows for readability:

```
if (
    !empty($isSwatch)
    && $attribute->getData($optionKey) === null
    && $attribute->getData($swatchKey) === null
) {
```

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        return $attributeData;
You could just `return $this->getOptionsForSwatch($options, $optionKey);` here rather than set `$attributeData`.

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        $connection                  = $optionCollection->getConnection();
Again spacing seems a bit off

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        $this->optionCollection = $attrOptionCollectionFactory;
Technically at this point this is the factory still right? Might be good to keep that obvious in the naming of the property.

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected function isSwatch($attribute)
The naming of this method is a bit confusing to me. `is` would suggest to me that it will return a boolean but it actually returns a mix of string and null. I think it might be a bit more readable if there was two methods, 1 for returning a boolean and one for getting the swatch type or something like that.

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected function getStoreLabels($optionId)
Part of me thinks that both this method and `getOptionsByAttributeIdWithSortOrder` should not be in the plugin but in another class.

2017-10-27 11:35 UTC, dmanners commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected function getOptionsForSwatch($options, $optionKey)
we can make sure an array is passed in here with `array $options` if it is always going to be an array.

2017-10-29 09:44 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected $eavConfig;
fixed

2017-10-29 09:44 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        $this->eavConfig                   = $eavConfig;
fixed

2017-10-29 09:45 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        $this->optionCollection = $attrOptionCollectionFactory;
fixed

2017-10-29 09:45 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        if (!empty($isSwatch) && $attribute->getData($optionKey) === null
fixed

2017-10-29 09:45 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected function isSwatch($attribute)
fixed

2017-10-29 09:45 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        return $attributeData;
fixed

2017-10-29 09:46 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected function getOptionsForSwatch($options, $optionKey)
fixed

2017-10-29 09:46 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +    protected function getStoreLabels($optionId)
fixed for getOptionsByAttributeWithSortOrder but still to be fixed for storeLabels

2017-10-29 09:47 UTC, springerin commented on app/code/Magento/Swatches/Plugin/Catalog/AddSwatchDataToAddOption.php
> +        $connection                  = $optionCollection->getConnection();
fixed

2017-11-22 12:49 UTC, dmanners commented
@springerin the following API test is failing. `dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductAttributeOptionManagementInterfaceTest.php` could you have a quick look into this failure for me?

2017-11-22 13:06 UTC, springerin commented
sure I will check it out today and let you know.

2017-11-23 07:55 UTC, EliasZ commented
:+1:  It is just embarrassing what kind of code you currently need to add a swatch.

2017-11-30 15:33 UTC, springerin commented
locally tested with the last updates and still green for me. Waiting for more info to reproduce the error.

2017-12-13 15:31 UTC, dmanners commented
@springerin it seems that this has now be fixed by https://github.com/magento/magento2/pull/12036. Using the `2.2-develop` branch I followed your test case and now the swatch options have been added.

2017-12-13 15:31 UTC, closed without merging