MAGETWO-9007: Get MAGETWO-52856 into Magento 2.1.x
magento/magento2 pull request #11640
Opened 2017-10-23 08:50 UTC by nmalevanec

Backport MAGETWO-52856 from 2.2.0 to 2.1 - develop

### Description
Provide seamless experience on checkout with large amount of customer addresses.

### Fixed Issues (if relevant)
1. magento/magento2#9007: Get MAGETWO-52856 into Magento 2.1.x

### Manual testing scenarios
1. Log in as a customer
2. Create 581 addresses
3. Go to checkout

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-23 08:50 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=11640) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11640) before we can accept your contribution.<br/>

2017-10-23 16:02 UTC, ishakhsuvarov requested changes

2017-10-23 16:02 UTC, ishakhsuvarov commented on app/code/Magento/Checkout/Model/PaymentInformationManagement.php
> +    private function getCartRepository()
Please try injecting this dependency as an optional constructor argument. Please refer to [Backwards Compatible Development Guide](http://devdocs.magento.com/guides/v2.1/ext-best-practices/extension-coding/backwards-compatible-development/index.html#adding-a-constructor-parameter) for more information

2017-10-24 07:44 UTC, magento-engcom-team commented on app/code/Magento/Checkout/Model/PaymentInformationManagement.php
> +    private function getCartRepository()
@ishakhsuvarov Done.

2017-10-24 07:48 UTC, nmalevanec commented on app/code/Magento/Checkout/Model/PaymentInformationManagement.php
> +    private function getCartRepository()
@ishakhsuvarov Done.

2017-10-24 13:22 UTC, nmalevanec commented on app/code/Magento/Checkout/Model/PaymentInformationManagement.php
> +    private function getCartRepository()
@ishakhsuvarov Done.

2017-10-27 14:50 UTC, merged

2018-03-01 09:33 UTC, elioermini commented on app/code/Magento/Checkout/Model/PaymentInformationManagement.php
> +        $this->cartRepository = $cartRepository ? : \Magento\Framework\App\ObjectManager::getInstance()
Why using the object manager in the constructor?