#9768: Admin dashboard Most Viewed Products Tab only gives default attribute set's products
magento/magento2 pull request #11725
Opened 2017-10-25 13:27 UTC by RomaKis

Admin dashboard Most Viewed Products Tab only gives default attribute set's products

### Fixed Issues (if relevant)
1. magento/magento2#<9768>: Admin dashboard Most Viewed Products Tab only gives default attribute set's products

### Manual testing scenarios
1. Login to Customer Account
2. Visited Product "Minerva LumaTech™ V-Tee"
3. Login to magento admin panel
4. Check magento dashboard "Most Viewed Product" grid

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-25 13:37 UTC, orlangur commented
@miguelbalparda please process this PR together with https://github.com/magento/magento2/pull/11597. Implementation is identical, but this PR has a test 💪

2017-10-25 20:21 UTC, miguelbalparda commented
@RomaKis any chance you can take a look at the failing tests? If you need any help just let us know. Thanks!

2017-10-26 14:27 UTC, RomaKis commented
@miguelbalparda, yes of course. I fixed it. Hope Jenkins won't fail again.

2017-10-26 14:49 UTC, orlangur requested changes

2017-10-26 14:49 UTC, orlangur commented on app/code/Magento/Reports/Test/Unit/Model/ResourceModel/Product/CollectionTest.php
> + * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
While coupling is unavoidable you cannot suppress `ExcessiveMethodLength` in new code, please refactor test accordingly.

Use imports actively (Alt+Enter in PhpStorm) to fit method calls in one line, `getMockForAbstractClass` for interface could be replaced with `createMock`.

After that please squash changes into single commit and force push into the same branch.

2017-10-27 08:39 UTC, RomaKis commented
@orlangur, fixed "SuppressWarnings(PHPMD.ExcessiveMethodLength)" and squashed commits.
I cann't use createMock()(1) or createPartialMock()(2) instead of getMockForAbstractClass() for interfaces:
1. I haven't ability to setMethods().
2. I need to configure all methods which exists in interface, but i don't need all of them.

2017-10-27 08:41 UTC, orlangur commented
@RomaKis ok, I remember I was using `getMock` for interfaces but these new methods seem to be different.

2017-11-08 12:45 UTC, miguelbalparda commented
This is good to go and going to be merged soon, can you please backport these changes to 2.1 and 2.0 please?

2017-11-08 22:37 UTC, merged

2017-11-09 11:55 UTC, RomaKis commented
@miguelbalparda, yes, I'll do it.