signing in after selecting checkout button, will not end up to checko…
magento/magento2 pull request #11823
Opened 2017-10-27 20:14 UTC by bohemiorulo

…ut page! #10834

signing in after selecting checkout button, will not end up to checkout page! #10834

### Description
Apparently I was not taking into account the "context" parameter that comes in the form with the value of "checkout", and not controlling this did not have a url to redirect.

### Fixed Issues (if relevant)
1.- After login redirect the checkout page, previously clicking on the checkout button

### Manual testing scenarios
1.- disable guest checkout
2.- open magento store
3.- add product to your cart and select checkout button
4.- fill the login window details
5.- and you should select checkout button once again after signing in

result: after signing in, user should redirected to checkout page, as he want this before signing in

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-27 20:14 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=11823) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11823) before we can accept your contribution.<br/>

2017-11-01 02:47 UTC, okorshenko commented
Similar PR https://github.com/magento/magento2/pull/11045

2017-11-02 13:08 UTC, bohemiorulo commented
I'm not sure why it did not pass the TEST_SUITE = static (https://travis-ci.org/magento/magento2/jobs/295922237), they could help me detect what was my mistake so I could fix it, thanks.

2017-11-02 14:59 UTC, ihor-sviziev requested changes

2017-11-02 14:59 UTC, ihor-sviziev commented on app/code/Magento/Customer/Controller/Ajax/Login.php
> +    protected $_url;
1. New properties should be private
2. properties should not be prefixed with underscore

2017-11-02 14:59 UTC, ihor-sviziev commented on app/code/Magento/Customer/Controller/Ajax/Login.php
> +                $url_checkout = $this->_url->getUrl('checkout', ['_secure' => true]);
Variable names should be in camel case ($urlCheckout or $checkoutUrl is better)

2017-11-02 15:04 UTC, ihor-sviziev commented
@bohemiorulo looks at https://github.com/magento/magento2/pull/11045#issuecomment-333969727. Your change is doing the same. Probably you need to update this with proposed changes to get accepted

2017-11-02 22:26 UTC, okorshenko commented
Hi @bohemiorulo 
Please reiew @ihor-sviziev comment. This is valid consern. Currently Customer module has a dependency on Checkout, but it make sense to redirect the user to the page, where it came from. This partial fix of the problem.
Please reopen PR when you want to make needed changes

2017-11-02 22:26 UTC, closed without merging