#10440: Missing $debugHintsPath when sending email via command line
magento/magento2 pull request #11852
Opened 2017-10-29 19:45 UTC by nemesis-back

Fix for #10440 

### Description
Exception "'BadMethodCallException' with message 'Missing required argument $debugHintsPath of Magento\Developer\Model\TemplateEngine\Plugin\DebugHints.'" triggered while running console command and sending email message with "layout" handle. It happens b/c there is no value for "debugHintsPath" variable of  in "base" di.xml, but it exist in frontend/di.xml and adminhtml/di.xml.
There are 2 possible solutions: declare $debugHinthsPath variable in base di.xml or add default value in constructor. I decided to add default value in constructor.

### Fixed Issues (if relevant)
1. magento/magento2#10440: Missing $debugHintsPath when sending email via command line

### Manual testing scenarios
1. Create console with the following code:
`
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->state->setAreaCode('frontend');
        $transport = $this->transportBuilder
            ->setTemplateIdentifier('sales_email_order_guest_template')
            ->setTemplateOptions(
                [
                    'area' => 'frontend',
                    'store' => $this->storeManager->getStore()->getId()
                ]
            )
            ->setTemplateVars([])
            ->setFrom(['email' => 'webmaster@magento.dev', 'name' => 'webmaster'])
            ->addTo('user@magento.dev')
            ->setReplyTo('webmaster@magento.dev', 'webmaster')
            ->getTransport();

        $transport->sendMessage();
    }
`
2. execute command from console (assuming command name is "bugfix:10440")
$ magento bugfix:10440
3. Email sent, exception wasn't triggered
### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-29 20:29 UTC, orlangur requested changes

2017-10-29 20:29 UTC, orlangur commented on app/code/Magento/Developer/Model/TemplateEngine/Plugin/DebugHints.php
> +            $this->scopeConfig->getValue($this->debugHintsPath, ScopeInterface::SCOPE_STORE, $storeCode)
> `$this->state->setAreaCode('frontend');`

Value from frontend area should have been used here, why it didn't work?

2017-10-30 00:13 UTC, nemesis-back commented
@orlangur , it also requires reloading object manager configuration, something like this
```php
$this->state->setAreaCode('frontend');
$objectManager->configure($configLoader->load('frontend'));
```
only object manager configuration contains correct parameters.
but anyway, the main problem is b/c Dependency Injection is not configured for "$debugHintsPath"in global area (see
https://github.com/magento/magento2/blob/373bd019b3efc02825d3b0e349fb4a58eec65d9f/app/code/Magento/Developer/etc/frontend/di.xml#L14
https://github.com/magento/magento2/blob/373bd019b3efc02825d3b0e349fb4a58eec65d9f/app/code/Magento/Developer/etc/adminhtml/di.xml#L14
https://github.com/magento/magento2/blob/373bd019b3efc02825d3b0e349fb4a58eec65d9f/app/code/Magento/Developer/etc/di.xml#L8) , therefore when magento object manager creates plugin class (Magento\Developer\Model\TemplateEngine\Plugin\DebugHints) in global area it triggers errors

2017-10-30 09:38 UTC, orlangur commented
It is not configured in global area because it has no sense in gloabl area:
```
* Allowed values:
       *     dev/debug/template_hints_storefront
       *     dev/debug/template_hints_admin
```

Plugin itself is also declared in frontend and adminhtml only. Why is it executed but without correct parameters?

2017-10-30 13:27 UTC, nemesis-back commented
@orlangur when object manager creates an instance of "Magento\Framework\View\TemplateEngineFactory" it always creates "Magento\Framework\View\TemplateEngineFactory\Intercepter" NOT depending of the app state area. It happens b/c plugin configuration di.xml  from all scopes are merged w/o reference to a scope, see https://github.com/magento/magento2/blob/373bd019b3efc02825d3b0e349fb4a58eec65d9f/lib/internal/Magento/Framework/Interception/Config/Config.php#L126

2017-12-06 21:14 UTC, nemesis-back commented
hey @orlangur , any updates on this?

2017-12-07 10:08 UTC, orlangur commented
Hi @nemesis-back, I want to check
> It happens b/c plugin configuration di.xml from all scopes are merged w/o reference to a scope, see

and whether it makes sense to make a base preference. Will do this weekend.

2018-04-23 16:31 UTC, magento-engcom-team commented
Hi @orlangur 
Do you have any updates on this?

2018-06-28 12:43 UTC, sergy-gzh commented
As a side for this issue.
It can be avoided if you just define area global in your command line script.
`$this->state->setAreaCode(Area::AREA_GLOBAL);`
Then magento will just pick up the proper design folder from email template configuration.
So for sales_email_order_guest_template, it always gonna be frontend.
`<template id="sales_email_order_guest_template" label="New Order for Guest" file="order_new_guest.html" type="html" module="Magento_Sales" area="frontend"/>`

2018-06-28 15:03 UTC, orlangur requested changes
In Magento 1 this feature existed only for storefront.

In Magento 2, due to a bug, it became affecting admin as well and product owners decided to leave such feature but control it with separate option.

So, please just move `debugHintsPath` from `frontend` to a base `di.xml`, do amend commit and force push.

2018-07-10 23:22 UTC, orlangur commented
@nemesis-back please apply necessary changes.

2018-08-01 13:56 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

2018-08-01 13:56 UTC, closed without merging