[Backport 2.3] #11825: Generate new FormKey and replace for oldRequestParams Wishlist
magento/magento2 pull request #12042
Opened 2017-11-05 12:47 UTC by osrecio

Generate new FormKey afterLogin and set to the beforeRequest(Wishlist)

### Description
Generate new FormKey afterLogin and set to the beforeRequest(Wishlist)

### Fixed Issues (if relevant)
1. magento/magento2#11825: 2.1.9 Item not added to the Wishlist if the user is not logged at the moment he click on the button to add it
2. magento/magento2#11908: Adding to wishlist doesn't work when not logged in

### Manual testing scenarios
1. Create an user account.
2. Logout from the user account
3. Add a product to your Wishlist , you will get redirected to the login page
4. Login

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-06 17:27 UTC, vkublytskyi commented
@osrecio tests failed as this fix introduces dependency for PageCache on Customer module. We should avoid this for bugfixes. Also we should avoid this as Customer module already has a dependency on PageCashe module and we must avoid circular dependencies. As a solution, I may suggest make a plugin on \Magento\PageCache\Observer\FlushFormKey in a customer module

2017-11-26 11:52 UTC, osrecio commented
Hi @vkublytskyi I added a Plugin in Customer Module to make the same logic.

2017-11-27 09:22 UTC, vkublytskyi commented on app/code/Magento/Customer/Model/Plugin/CustomerFlushFormKey.php
> +     * @param $args
Please add `@SuppressWarnings(PHPMD.UnusedFormalParameter)` to avoid static tests failure

2017-11-27 21:15 UTC, osrecio commented
@vkublytskyi @ihor-sviziev 
1. Added `@SuppressWarnings(PHPMD.UnusedFormalParameter)` to avoid static tests failure
2. Deleted not related changes
3. Added Unit Tests

2017-11-28 06:25 UTC, ihor-sviziev approved these changes

2017-11-28 12:57 UTC, vkublytskyi requested changes
Unit test should be updated to fix issue with passed invalid argument. See https://github.com/magento/magento2/pull/12038#discussion_r153482897

2017-12-01 10:59 UTC, vkublytskyi approved these changes

2017-12-01 12:33 UTC, osrecio commented
Thanks @vkublytskyi I was going to work on the changes this weekend. Busy Week

2017-12-01 18:52 UTC, merged