Add command to view mview state and queue
magento/magento2 pull request #12050
Opened 2017-11-05 20:58 UTC by convenient

This is similar to the magerun1 command here: https://github.com/netz98/n98-magerun/pull/891

I like the ability to view the mview queue in realtime as its being processed, it can be quite helpful when debugging indexing issues.

This command will actually show how many items are in the list pending processing, as well information from the `mview_state` table.

```
php bin/magento indexer:status:mview
+---------------------------+----------+--------+---------------------+------------+---------+
| ID                        | Mode     | Status | Updated             | Version ID | Backlog |
+---------------------------+----------+--------+---------------------+------------+---------+
| catalog_category_product  | enabled  | idle   | 2017-11-02 10:00:00 | 1          | 0       |
| catalog_product_attribute | enabled  | idle   | 2017-11-02 10:00:00 | 1          | 1       |
| catalog_product_category  | disabled | idle   | 2017-11-02 10:00:00 | 1          | 0       |
| catalog_product_price     | enabled  | idle   | 2017-11-02 10:00:00 | 1          | 0       |
+---------------------------+----------+--------+---------------------+------------+---------+
```

I'll point this PR into 2.1.x and raise a separate PR to pop it into 2.2.x.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-06 11:34 UTC, ihor-sviziev commented
Really good idea. Would be great to have something similar in the magento admin.

2017-11-06 12:05 UTC, convenient commented
> Would be great to have something similar in the magento admin

@ihor-sviziev That would definitely be neat, however I'll focus on getting this command and potentially deal with admin UI in a separate PR at a later.

2017-11-06 14:11 UTC, ihor-sviziev requested changes

2017-11-06 14:11 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Console/Command/IndexerStatusMviewCommand.php
> +        \Magento\Framework\Mview\View\CollectionInterface $collection
You need to use \Magento\Framework\Mview\View\CollectionFactory there. Also would be great to import this class.

2017-11-06 14:11 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Console/Command/IndexerStatusMviewCommand.php
> +                    $indexer->getData('view_id'),
Would be better to use $indexer->getId()

2017-11-06 14:11 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Console/Command/IndexerStatusMviewCommand.php
> +            foreach ($this->mviewIndexersCollection as $indexer) {
Actually it's not indexer, it's view. So it's better to use one name for this object type

2017-11-06 14:11 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Console/Command/IndexerStatusMviewCommand.php
> +                    $state->getData('mode'),
$state->getMode()

2017-11-06 14:11 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Console/Command/IndexerStatusMviewCommand.php
> +                    $state->getData('status'),
$state->getStatus()

2017-11-06 14:11 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Console/Command/IndexerStatusMviewCommand.php
> +                    $state->getData('updated'),
$state->getUpdated()

2017-11-06 14:11 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Console/Command/IndexerStatusMviewCommand.php
> +                    $state->getData('version_id'),
$state->getVersionId()

2017-11-06 15:44 UTC, convenient commented
Thanks for the review @ihor-sviziev I'll action these later. 

Quick Q: why is it your preference to use `$obj->getFoo()` rather than `$obj->getData('foo')` ? I've a personal dislike for those magic methods but it'd just a style thing for me. Is this to keep it more inline with the rest of M2?

2017-11-06 15:55 UTC, ihor-sviziev commented
You're looking on implementation. If you look on interface - you'll see
that there is no method getData, but has all methods that I wrote you.

On Nov 6, 2017 5:45 PM, "Luke Rodgers" <notifications@github.com> wrote:

Thanks for the review @ihor-sviziev <https://github.com/ihor-sviziev> I'll
action these later.

Quick Q: why is it your preference to use $obj->getFoo() rather than
$obj->getData('foo') ? I've a personal dislike for those magic methods but
it'd just a style thing for me. Is this to keep it more inline with the
rest of M2?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/magento/magento2/pull/12050#issuecomment-342188633>,
or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AByXUbpdrZpd3nLefpZ84Gs-LDXXcRimks5szymagaJpZM4QSh4G>
.




On Nov 6, 2017 5:45 PM, "Luke Rodgers" <notifications@github.com> wrote:

Thanks for the review @ihor-sviziev <https://github.com/ihor-sviziev> I'll
action these later.

Quick Q: why is it your preference to use $obj->getFoo() rather than
$obj->getData('foo') ? I've a personal dislike for those magic methods but
it'd just a style thing for me. Is this to keep it more inline with the
rest of M2?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/magento/magento2/pull/12050#issuecomment-342188633>,
or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AByXUbpdrZpd3nLefpZ84Gs-LDXXcRimks5szymagaJpZM4QSh4G>
.



On Nov 6, 2017 5:45 PM, "Luke Rodgers" <notifications@github.com> wrote:

> Thanks for the review @ihor-sviziev <https://github.com/ihor-sviziev>
> I'll action these later.
>
> Quick Q: why is it your preference to use $obj->getFoo() rather than
> $obj->getData('foo') ? I've a personal dislike for those magic methods
> but it'd just a style thing for me. Is this to keep it more inline with the
> rest of M2?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/12050#issuecomment-342188633>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AByXUbpdrZpd3nLefpZ84Gs-LDXXcRimks5szymagaJpZM4QSh4G>
> .
>

2017-11-06 20:04 UTC, convenient commented
@ihor-sviziev thank you for the clarification, you were right I was not considering the interface.

i've updated the PR to address your concerns and the test suite is green, please review.

2017-11-06 20:14 UTC, ihor-sviziev approved these changes

2017-11-08 20:25 UTC, convenient commented
Cool, now that this is going green I'll port it to 2.2.

2017-11-08 20:50 UTC, convenient commented
Done. Raised #12122 for the 2.2 series.

2017-11-22 21:52 UTC, convenient commented
FYI I'll not do any further work on this PR until everyone's happy with the changes and discussion that will be happening in #12122 .

2017-12-11 16:05 UTC, merged