9768: Admin dashboard Most Viewed Products Tab only gives default attribute set's products (backport for 2.1)
magento/magento2 pull request #12137
Opened 2017-11-09 12:07 UTC by RomaKis

Admin dashboard Most Viewed Products Tab only gives default attribute set's products. Backport from https://github.com/magento/magento2/pull/11725.

### Fixed Issues (if relevant)
1. magento/magento2#9768: Admin dashboard Most Viewed Products Tab only gives default attribute set's products

### Manual testing scenarios
1. Login to Customer Account
2. Visited Product "Minerva LumaTech™ V-Tee"
3. Login to magento admin panel
4. Check magento dashboard "Most Viewed Product" grid

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-09 14:29 UTC, miguelbalparda requested changes
This seems to differ from the other 2 PRs for this fix. Can you double check it please?

2017-11-09 15:17 UTC, RomaKis commented
@miguelbalparda, changes are different only in unit test, bacause 2.1.x use \PHPUnit_Framework_TestCase class instead of \PHPUnit\Framework\TestCase in 2.2.

2017-11-26 20:18 UTC, miguelbalparda approved these changes

2017-11-30 16:45 UTC, miguelbalparda commented
@dmanners can you check this one? All the other backports are already merged, I suspect this one hasn't been picked up yet because of the request for changes but now should be good to go.

2017-12-01 20:28 UTC, merged