magento/magento2#7627: Cookie expiration time is not extended when browsing the frontend
magento/magento2 pull request #12166
Opened 2017-11-10 08:42 UTC by p-bystritsky

### Description
On frontend framework will update session expiration time on every request after session cookie is set.

### Fixed Issues (if relevant)
1. magento/magento2##7627: Cookie expiration time is not extended when browsing the frontend.

### Manual testing scenarios
1. Browse frontend until PHPSESSID is set. Take a look on PHPSESSID expiration time.
2. Open any page.
3. Make sure PHPSESSID expiration time is updated.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-10 13:53 UTC, ishakhsuvarov requested changes
Please review the comments and rework this PR if you wish to continue.

2017-11-10 13:53 UTC, ishakhsuvarov commented on app/code/Magento/Cookie/Model/App/Response/HttpPlugin.php
> +        // Blank. Creating object that implements SessionManagerInterface is enough.
Please provide more detailed background for this kind of fix, adding a plugin to Http Response seems to be an overhead.

2017-11-10 13:53 UTC, ishakhsuvarov commented on app/code/Magento/Cookie/etc/frontend/di.xml
> +<?xml version="1.0"?>
Module `Cookie` is not responsible for managing Session Cookies.
It's only purpose is to display a warning, that website uses cookies, when configured accordingly.

2017-11-10 13:53 UTC, ishakhsuvarov commented on app/code/Magento/Cookie/Model/App/Response/HttpPlugin.php
> +    public function __construct(
Doc Block is missing

2017-11-10 13:53 UTC, ishakhsuvarov commented on app/code/Magento/Cookie/Model/App/Response/HttpPlugin.php
> +        $this->sessionManager = $sessionManager;
Dependency which is not used anywhere in the class should not be injected.
It is a good idea to look for an alternative solution.

2017-11-10 14:38 UTC, p-bystritsky commented
@ishakhsuvarov  Moved changes to /lib/internal/Magento/Framework/App/Response/Http.php

2017-12-05 16:33 UTC, omiroshnichenko commented
Hi, @p-bystritsky. This fix will not work with Varnish or another cache server. Correct fix is to implement mechanism where some JS will make a request on Magento controller that will check session and prolong it. So, will you plan to make such implementation or I can close this PR?

2017-12-11 09:54 UTC, p-bystritsky commented
@omiroshnichenko, yes, this PR should be closed.

2017-12-11 09:54 UTC, closed without merging