Add price rule attributes when hydrating product during price calcula…
magento/magento2 pull request #12423
Opened 2017-11-23 20:39 UTC by scazz010

…tion

### Description
Column in `catalog_eav_attribute` is `is_used_for_price_rules`. This PR means that all attributes used for price calculation are fetched by the `lowestPriceOptionsProvider()` (which is called inside `module-configurable-product/Pricing/Price/ConfigurablePriceResolver.php`->`resolvePrice`) 

Backstory / justification: 

I was adding a feature to control price visibility (for some products, we don't want to display the price on our magento store). This includes for some options of configurable products.  Despite setting `is_used_for_price_rules` to be true, the product model is hydrated with only some default attributes (special prices, tax class), but we need to be able to add some extra processing to check we're allowed to display to price

### Manual testing scenarios
1. Create a new attribute, for example, `price_visibility`, and ensure that it's corresponding entry in `catalog_eav_attribute` has `is_used_for_price_rules` to be true
2. Add this attribute to a configurable product's attribute set, and set some of the simple products to have this as false
3. Create a new configurable price resolver and attempt to filter sub products so that only those with price_visibility of true are considered. 

### Contribution checklist
 - [/] Pull request has a meaningful description of its purpose
 - [/] All commits are accompanied by meaningful commit messages
 - [/] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-23 20:39 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=12423) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12423) before we can accept your contribution.<br/>

2017-11-30 06:23 UTC, avoelkl commented
Hi @scazz010 
Thanks for your PR! There is a failing codestyle check - could you please have a look and fix it? Thanks!

2017-11-30 22:24 UTC, scazz010 commented
@avoelkl Sure, have fixed!

2018-02-21 07:04 UTC, ihor-sviziev requested changes

2018-02-21 07:04 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Config.php
> +    protected $_usedForPriceRules;
1. Please change property visibility from protected to private
2. Please remove underscore for variable name

2018-02-21 07:04 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Pricing/Price/LowestPriceOptionsProvider.php
> +        Config $catalogConfig
This change is not backward compatible. Please make this parameter optional with fallback of getting this object instance from objectManager

2018-02-21 07:04 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Pricing/Price/LowestPriceOptionsProvider.php
> +    public function getPriceRuleAttributes()
Could you change visibility to private?

2018-03-21 08:44 UTC, ihor-sviziev commented
Hi @scazz010,
Are you interested in finalizing this PR?

2018-05-14 14:52 UTC, sidolov commented
@scazz010 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration!

2018-05-14 14:52 UTC, closed without merging