Format generated config files using the short array syntax
magento/magento2 pull request #12499
Opened 2017-11-30 14:36 UTC by cykirsch

### Description

1. Magento is following a standard of new code using short array syntax (https://github.com/magento/magento2/issues/758).
2. Magento has an automated checker to enforce the short array syntax precommit (https://github.com/magento/magento2/blob/2.2/.php_cs.dist#L31). 
3. Magento recommends checking in `app/etc/config.php` (http://devdocs.magento.com/guides/v2.2/config-guide/config/config-php.html)
>Check this file in to source control and use it in your development, staging, and production systems.
4. Magento's auto-generated `app/etc/config.php` uses the long array syntax.

Put that all together and the auto-generated config doesn't match the required standards to be checked in. The change made in this PR is to modify `PhpFormatter` to recursively return the array representation using short array syntax `[]` instead of long `array()`. If the given variable is not an array, it uses the standard `var_export` behavior.

### Manual testing scenarios

1. bin/magento setup:upgrade
2. app/etc/config.php should use the short array syntax

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-30 14:47 UTC, cykirsch commented
As an added note, I did attempt to do this using `Zend\Code\Generator\ValueGenerator` instead of `var_export`, but the array depth wasn't being tracked properly. The unit test array would look like this

    [
      'ns1' => [
            's1' => [
                's11',
                's12',
            ],
            's2' => [
                's21',
                's22',
            ],
        ],
      'ns2' => [
            's1' => [
                's11',
            ],
        ],
      'ns3' => 'just text',
      'ns4' => 'just text',
    ]

2017-11-30 23:18 UTC, ghost approved these changes

2017-12-01 13:35 UTC, ishakhsuvarov requested changes

2017-12-01 13:35 UTC, ishakhsuvarov commented on lib/internal/Magento/Framework/App/DeploymentConfig/Writer/PhpFormatter.php
> +            $r = [];
Please avoid variables with unclear names. `$r` does not really describe what is it for.

2017-12-01 13:35 UTC, ishakhsuvarov commented on lib/internal/Magento/Framework/App/DeploymentConfig/Writer/PhpFormatter.php
> +    private function varExportShort($var, $depth = 0)
Please take advantage of PHP 7.0 syntax (type hints and return types for methods)

2017-12-01 13:35 UTC, ishakhsuvarov commented on lib/internal/Magento/Framework/App/DeploymentConfig/Writer/PhpFormatter.php
> +        if (gettype($var) === 'array') {
Is there any specific reason not to use `is_array`?
Additionally, readability may be slightly improved by reversing the logic like

```php
if (!is_array($var)) {
    return var_export($var, true);
}
/// Transforming to short array syntax here
...
```

2017-12-01 13:35 UTC, ishakhsuvarov commented on lib/internal/Magento/Framework/App/DeploymentConfig/Writer/PhpFormatter.php
> +    const INDENT = '  ';
Please add a description for the constant (docBlock)

2017-12-01 14:34 UTC, ishakhsuvarov approved these changes

2017-12-01 20:28 UTC, merged

2017-12-13 15:14 UTC, cykirsch commented
@ishakhsuvarov @okorshenko I was more or less expecting these changes would be in 2.2.2. Is it odd to you that it is on the 2.2.2-preview branch but not on the 2.2.2 tag? Or does that happen often?

2018-03-26 08:32 UTC, clementblanco commented
What if we want 4 spaces tab indentation?

2018-03-26 21:27 UTC, cykirsch commented
@clementblanco That did cross my mind, and I would prefer it as well, but I neglected to do it...I think because I was continuing to use `var_export` and I didn't want to mix 4 and 2.