Prevent empty label when element has no label set
magento/magento2 pull request #12498
Opened 2017-11-30 14:30 UTC by sanderjongsma

### Description
Knockout checks if element has a label. When it has not a label set, the emtpy <label></label> tags are still generated in the dom. This is unnecessary, so the knockout if statement can be placed around the label itself.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-30 14:30 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=12498) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12498) before we can accept your contribution.<br/>

2017-11-30 21:15 UTC, fooman commented
Thanks @sanderjongsma for this contribution. Do you think that some people might rely on the presence of the label attribute, even if it's empty, to get their layout right?

2017-12-01 10:39 UTC, sidolov requested changes

2017-12-01 10:39 UTC, sidolov commented on app/code/Magento/Ui/view/frontend/web/templates/form/field.html
> +    <!-- ko if: element.label -->
Replace old style logic operator to new. 
Example:  
```
<label if="element.label" class="label" data-bind="attr: { for: element.uid }">
    ...
</label>
```

2017-12-01 11:11 UTC, sidolov approved these changes

2017-12-01 11:13 UTC, sidolov commented
Hey @sanderjongsma, I fixed minor issue, thank you for contribution!

2017-12-04 09:18 UTC, sanderjongsma commented
@fooman yes I think there are a few people relying on it (if they float the label left from the input, and don't use float right for the input itself). In my opinion it is always better to fix the styling without a label attribute. The reason for this pr is because now the streetaddress field(s) renders an extra label tag, which can cause unwanted html. I know the default checkout isn't affected, because labels are above the inputs. I know it's about preferences, but let me know what you think.

2017-12-08 12:01 UTC, sidolov commented
Hi @sanderjongsma , after the long discussion, according to web accessibility basics, we decide that we always need label tag for all inputs (including cases with empty label value). 
For example, simple case: designer can style label with icon but without text, with provided solution label will not be rendered. 
Thank you for your contribution!

2017-12-08 12:01 UTC, closed without merging