Add customer login url from Customer Url model to checkout config so …
magento/magento2 pull request #12631
Opened 2017-12-11 14:38 UTC by quisse

…it contains the referer url if necessary

### Description
Use the url created in the customer model instead of creating a new one with the url builder. The current way isn't adding a referrer parameter when required

### Fixed Issues (if relevant)

1. magento/magento2#12627: Referer is not added to login url in checkout config

### Manual testing scenarios

1. Enable `Redirect Customer to Account Dashboard after Logging in` in the Magento backend.
2. Retrieve the login url from the `window.checkout` object (key is customerLoginUrl)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2017-12-13 08:32 UTC, dmanners commented
Backport for https://github.com/magento/magento2/pull/12630

2017-12-13 15:54 UTC, omiroshnichenko commented on app/code/Magento/Customer/Model/Checkout/ConfigProvider.php
> -    protected $urlBuilder;
You must deprecate it instead of remove.

2017-12-13 15:55 UTC, omiroshnichenko commented on app/code/Magento/Customer/Model/Checkout/ConfigProvider.php
> +    protected $customerUrl;
New property must be private or public, in current case private.

2017-12-13 16:02 UTC, omiroshnichenko commented on app/code/Magento/Customer/Model/Checkout/ConfigProvider.php
> -        UrlInterface $urlBuilder,
According to [Backward compatible development guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter), you can't modify existing parameters. Add `Url` like optional parameter.

2017-12-13 16:04 UTC, omiroshnichenko requested changes
Please, make this changes for all related PRs.

2017-12-14 09:09 UTC, quisse commented
@omiroshnichenko Changes applied.

2017-12-14 10:42 UTC, omiroshnichenko commented on app/code/Magento/Customer/Model/Checkout/ConfigProvider.php
> +     * @param Url $customerUrl
`$customerUrl` also can be `null`.

2017-12-14 10:42 UTC, omiroshnichenko commented on app/code/Magento/Customer/Model/Checkout/ConfigProvider.php
> +        $this->urlBuilder=$urlBuilder;
Add spaces.

2017-12-14 11:05 UTC, omiroshnichenko commented on app/code/Magento/Customer/Model/Checkout/ConfigProvider.php
> +        $this->customerUrl = $customerUrl ?? \Magento\Framework\App\ObjectManager::getInstance()
Move ObjectManager to use instead of using fully qualified name.

2017-12-14 13:30 UTC, quisse commented
Build probably failed for no reason?

2017-12-20 10:37 UTC, merged