[Backport 2.3] #12625: Add Current Date to update_time Field for Block and Pages
magento/magento2 pull request #12637
Opened 2017-12-11 17:12 UTC by osrecio

Set Current Date Time to update_time field

### Description
add current date time to 'update_time' in `_beforeSave` method  for Page and Block

### Fixed Issues (if relevant)
1. magento/magento2#12625: when saving a page in magento 2.2.1, 'Modified' date field is not getting updated

### Manual testing scenarios
1. Login to magento admin
2. Go to Content > Pages
3. In Action column, click select > edit
4. Make changes to that page and click 'Save Page'

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds on Travis CI are green)

2017-12-12 09:10 UTC, dmanners commented
This is a backport of https://github.com/magento/magento2/pull/12636

2017-12-14 13:55 UTC, sidolov requested changes

2017-12-14 13:55 UTC, sidolov commented on app/code/Magento/Cms/Model/ResourceModel/Page.php
> +        $date = (new \DateTime())->format(DateTime::DATETIME_PHP_FORMAT);
Please, use framework implementation for date value \Magento\Framework\Stdlib\DateTime\DateTime::date

2017-12-14 14:48 UTC, osrecio commented
@sidolov Changes made, and added integration tests for Cms Block 😃

2017-12-18 13:21 UTC, sidolov commented
Hi @osrecio , i investigated this issue deeper and find that field 'update_time' should be automatically updated by Mysql engine. In db this field has type timestamp and must be automatically updated after row has been changed. We had the same issue with quote (bf9ea28eef07046fabb78dcde84951382b7f0716). 
This behavior fixing by unset 'update_time' field before model save: 

```
if ($this->hasDataChanges()) {
    $this->unsUpdateTime();
}
```

2017-12-18 13:56 UTC, osrecio commented
Hi @sidolov I changed Models to add in method `beforeSave`:

```
if ($this->hasDataChanges()) {
    $this->unsUpdateTime();
}
```
Thanks for catch it, I made my life complicated changing Resource Model :)

2017-12-19 07:01 UTC, sidolov approved these changes

2017-12-20 10:37 UTC, merged