#12514 Impossible to set source model when create new attribute
magento/magento2 pull request #12746
Opened 2017-12-15 13:52 UTC by OleksiiStepanov

### Description
Pull request fix bug when unable create new attribute via api with custom source model

### Fixed Issues (if relevant)
#12514 Impossible to set source model when create new attribute

This pull request also will fix issue when unable create attribute with custom BackendType  and custom BackendModel 

### Manual testing scenarios
create new attribute via api  using \Magento\Catalog\Api\ProductAttributeRepositoryInterface
like this
`
$attribute = $this->attributeFactory->create();

$this->dataObjectHelper->populateWithArray(
    $attribute,
    [
        'attribute_code' => 'select_attribute',
        'source_model' => '\Custom\Model',
        'default_frontend_label' => 'select_attribute_label',
        'frontend_input' => 'select',
        'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_STORE,
    ],
    ProductAttributeInterface::class
);
$this->attributeRepository->save($attribute);

`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-12-15 13:52 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=12746) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12746) before we can accept your contribution.<br/>

2017-12-18 07:13 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/Catalog/Model/Product/Attribute/CreateAttributeViaApi.php
> +        $attribute_code='select_with_custom_source';
Use camel case names instead of underscore

2017-12-18 07:16 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/Catalog/Model/Product/Attribute/CreateAttributeViaApi.php
> +class CreateAttributeViaApi extends \PHPUnit\Framework\TestCase
Change name to Repository (you testing \Magento\Catalog\Model\Product\Attribute\Repository behavior, test namespace and name must be the same)

2017-12-18 07:17 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/Catalog/Model/Product/Attribute/CreateAttributeViaApi.php
> +    private $attributeRepository;
Add property type

2017-12-18 07:17 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/Catalog/Model/Product/Attribute/CreateAttributeViaApi.php
> +    private $dataObjectHelper;
Add property type

2017-12-18 07:19 UTC, sidolov requested changes
Also cover logic with backendType and backendModel by integration test

2017-12-18 07:20 UTC, sidolov requested changes

2017-12-18 07:20 UTC, sidolov commented on app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute.php
> +            if ($object->getFrontendInput() == 'select' && !$object->hasSourceModel()) {
Cover changes with unit test

2017-12-18 08:47 UTC, nmalevanec commented
@OleksiiStepanov , @sidolov 
I see couple problems with such fix. First - there is no ability to set source model for user defined attributes via admin Ui, but this fix make it possible via API, which IMHO brings some inconsistency.
Second one is [here]( https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Eav/Block/Adminhtml/Attribute/Edit/Options/Options.php#L68). This method won't allow to display predefined in source model options for user defined attributes. And they will be user defined, because of this [line](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/Product/Attribute/Repository.php#L168). So user won't be able to see predefined options on attribute edit page, but will see them on product page, when try to assign attribute value to product, which is also inconsistent.

2017-12-18 08:50 UTC, nmalevanec reviewed
@OleksiiStepanov , @sidolov
I see couple problems with such fix. First - there is no ability to set source model for user defined attributes via admin Ui, but this fix make it possible via API, which IMHO brings some inconsistency.
Second one is [here]( https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Eav/Block/Adminhtml/Attribute/Edit/Options/Options.php#L68). This method doesn't allow to display predefined in source model options for user defined attributes. And they will be user defined, because of this [line](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/Product/Attribute/Repository.php#L168). So user won't be able to see predefined options on attribute edit page, but will see them on product page, when try to assign attribute value to product, which is also inconsistent.

2018-01-03 15:29 UTC, vkublytskyi commented
@OleksiiStepanov would you describe use case when it is necessary to create attribute with custom source model?

2018-01-11 10:18 UTC, sidolov commented
@OleksiiStepanov , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2018-01-11 10:18 UTC, closed without merging