Config parsing fails - Braintree - Issue #12298
magento/magento2 pull request #12761
Opened 2017-12-15 15:05 UTC by DaniloEmpire

After setup:upgrade, during the config import, an exception interrupt the upgrade for a non-parsed config value.

### Description
This pull request fix this problem during config import:
`Import failed: Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/magento/module-braintree/Model/Adminhtml/System/Config/CountryCreditCard.php on line 70`

### Fixed Issue
1. magento/magento2#12298

### Manual testing scenarios
1. Configure Braintree payment system
2. magento app:config:dump
3. magento setup:upgrade

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds on Travis CI are green)

2017-12-18 16:07 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=12761) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12761) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: DaniloEmpire<br/>:x: Andrae Gentili<hr/>**Andrae Gentili** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-12-18 16:18 UTC, bluvertigo commented
I agreed the CLA

2017-12-19 13:46 UTC, YevSent requested changes

2017-12-19 13:46 UTC, joni-jones commented on app/code/Magento/Braintree/Model/Adminhtml/System/Config/CountryCreditCard.php
> +            unset($e);
Please, log exception instead of ignoring it.

2017-12-19 13:47 UTC, joni-jones commented
Please, fix failed tests.

2017-12-26 10:43 UTC, YevSent approved these changes

2018-03-08 16:07 UTC, closed without merging

2018-08-13 18:24 UTC, muckee commented
Just got this problem on 2.2.5 when trying to execute `setup:upgrade`. It occured when I updated the (un)secure URL parameters via the database, then added the configuration manually to env.php, as well as adding settings to use redis for default and page caching.

I also noticed that there are duplicate entries in my env.php file for the secure and unsecure base URLs.
One set existed alongside declarations of static, media etc. URLs, the other declaration was at the end of the file, with just the base URLs. I changed both instances manually.
~
At no point before completing the above steps did I execute any magento commands, i.e. `setup:upgrade`. I then executed the following commands in the following order:
`setup:upgrade`, `setup:di:compile`, `indexer:reindex`, `cache:flush` and `setup:static-content:deploy`.

I am also fighting a redirect loop on the admin page at the moment so I don't know if that has something to do with it.