magento/magento2#12699: Multiselect Attribute is not saved
magento/magento2 pull request #12767
Opened 2017-12-15 15:16 UTC by awarche

fixed attribute loading for different entities in AbstractEntity

2017-12-15 15:26 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=12767) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12767) before we can accept your contribution.<br/><hr/>**awarche** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-12-18 18:32 UTC, osrecio requested changes

2017-12-18 18:32 UTC, osrecio commented on app/code/Magento/Eav/Model/Entity/AbstractEntity.php
> +    protected $attributesByScope = [];
This attribute should be private

2017-12-19 10:29 UTC, sidolov commented
Refactored according to backward compatible development requirements

2017-12-19 10:37 UTC, osrecio approved these changes

2017-12-22 09:05 UTC, merged