Fix/imposible customize product collection
magento/magento2 pull request #12770
Opened 2017-12-15 15:57 UTC by dvynograd

Reopen https://github.com/magento/magento2/pull/8485
original description:

Right now it's impossible to customize product collection on the catalog products list page.

As i can see, Magento supposed to provide this ability in \Magento\Catalog\Block\Product\ListProduct::_beforeToHtml

``` 
$this->_eventManager->dispatch(
'catalog_block_product_list_collection',
['collection' => $this->_getProductCollection()]
);

    $this->_getProductCollection()->load();
```

but due to Magento has the observer CatalogBlockProductCollectionBeforeToHtmlObserver wich listen this event and loads collection. So it prevent to collection modifications in future customizations.

Following PR is fixing that issue.

2018-02-01 11:31 UTC, dmanners requested changes

2018-02-01 11:31 UTC, dmanners commented on app/code/Magento/Catalog/Block/Product/ListProduct.php
> +    protected $collectionLoader;
New class parameter should be private as we are trying to avoid using protected.

2018-02-01 11:31 UTC, dmanners commented on app/code/Magento/Catalog/Block/Product/ListProduct.php
> +        CollectionLoader $collectionLoader,
New injections should come last in the construct and should also default to null so as to not break backwards compatibility. More information and examples can be found at http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter

2018-02-01 11:31 UTC, dmanners commented on app/code/Magento/Catalog/Block/Product/ProductList/Promotion.php
> +        CollectionLoader $collectionLoader,
New injections should come last in the construct and should also default to null so as to not break backwards compatibility. More information and examples can be found at http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter

2018-02-01 11:31 UTC, dmanners commented on app/code/Magento/Catalog/Block/Product/ProductList/Random.php
> +            $collectionLoader,
New injections should come last in the construct and should also default to null so as to not break backwards compatibility. More information and examples can be found at http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter

2018-03-13 06:05 UTC, orlangur commented
Closing due to inactivity. @dvynograd, feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

2018-03-13 06:05 UTC, closed without merging