Change _getHtml to append class rather than overwrite for children
magento/magento2 pull request #12862
Opened 2017-12-22 18:50 UTC by jonshipman

Change _getHtml to append class rather than overwrite for children

### Description
When creating a dependency injection for the Magento\Theme\Block\Html\Topmenu class, we are unable to change class names on children in a beforeGetHtml method because the protected method _getHtml declares setClass() on all children items. What this contribution changes is checking each child for an existing class and appends the $outermostClass if true.

### Manual testing scenarios
1. Create a di.xml in a custom module that creates a plugin for the Magento\Theme\Block\Html\Topmenu class.
2. In a beforeGetHtml injection, add a loop over the (Magento\Theme\Block\Html\Topmenu) $subject->getMenu()->getChildren() and ->setClass() on each one.
3. With this contribution, each child gets the class specified. Without, it gets overwritten.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2017-12-22 18:50 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=12862) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12862) before we can accept your contribution.<br/>

2018-01-02 15:52 UTC, dmanners commented
@jonshipman thank you for the pull request. Could you sign the CLA and then we can start to progress this pull request.

2018-01-02 15:58 UTC, jonshipman commented
I give my consent, the CLA button says I sign it but this PR doesn't seem to update. Attached is the image I see.

https://imgur.com/9mMXGXC

2018-01-03 12:44 UTC, dmanners commented
@jonshipman it seems that the account the commit is assigned to (https://github.com/jonshipmansmc) is different from the account you are creating the pr and signing the CLA with (https://github.com/jonshipman). If you change the author or the commit and repush the branch it should pick up the changes and cla signing.

2018-01-03 13:45 UTC, jonshipman commented
Signed.

2018-01-03 17:56 UTC, dmanners requested changes

2018-01-03 17:56 UTC, dmanners commented on app/code/Magento/Theme/Block/Html/Topmenu.php
> +                $current_class = $child->getClass();
could you update this variable to be `$currentClass`

2018-01-04 11:13 UTC, dmanners approved these changes

2018-01-07 07:02 UTC, merged