#8810 - REST API - Attribute option creation -> no ID returned
magento/magento2 pull request #12920
Opened 2017-12-29 10:59 UTC by sanjay-wagento

Set option_id in value field to attributeoptioninterface return type
### Description

I have changed return type of add function and set value to option. So when we do REST or SOAP api then it will return option_id in 'value' field to attributeoptioninterface return type.

### Fixed Issues (if relevant)

1. magento/magento2#8810: REST API - Attribute option creation -> no ID returned

### Manual testing scenarios

1. Fresh install
2. Make following REST request:
`POST /rest/default/V1/products/attributes/manufacturer/options`
with following Body:
`{
  "option": {
    "label": "Manufacturer 1"
  }
}`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-07 15:25 UTC, mzeis commented
Hi @sanjay-wagento,

a few functional tests are failing and have to be adjusted because the result is not `true` anymore but a data array:

* [Magento\Catalog\Api\ProductAttributeOptionManagementInterfaceTest::testAdd()](https://github.com/magento/magento2/blob/4b7af270c2e3b1e84f1daf270a8b5f2e0e4ece8a/dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductAttributeOptionManagementInterfaceTest.php#L77)
* [Magento\Catalog\Api\ProductSwatchAttributeOptionManagementInterfaceTest::testAdd()](https://github.com/magento/magento2/blob/4b7af270c2e3b1e84f1daf270a8b5f2e0e4ece8a/dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductSwatchAttributeOptionManagementInterfaceTest.php#L45)

It would be awesome if you are able to fix this. If not, please let us know.

Thanks!

2018-01-28 09:34 UTC, mzeis commented
@sanjay-wagento Short update: results of the performance test suite indicate this change might cause a performance degradation. We are investigating at the moment.

2018-03-15 21:20 UTC, okorshenko requested changes

2018-03-15 21:20 UTC, okorshenko commented on app/code/Magento/Catalog/Api/ProductAttributeOptionManagementInterface.php
> +     * @return \Magento\Eav\Api\Data\AttributeOptionInterface
please return the  option ID instead of object

2018-03-15 21:20 UTC, okorshenko commented on app/code/Magento/Eav/Api/AttributeOptionManagementInterface.php
> +     * @return \Magento\Eav\Api\Data\AttributeOptionInterface
please return the option ID instead of object

2018-04-25 14:29 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=12920) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12920) before we can accept your contribution.<br/>**1** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: sanjay-wagento<br/>:x: svitja<br/>:x: OlgaVasyltsun<br/>:x: Stas Kozar<br/>:x: ameysar<hr/>**Stas Kozar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-07-03 21:39 UTC, merged

2018-07-03 21:40 UTC, magento-engcom-team commented
Hi @sanjay-wagento. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

2018-09-25 19:11 UTC, hostep commented
Hi all involved

Something seems to have gone wrong here.
This was discovered totally by accident btw.

In Magento 2.2-develop, when you create a new attribute option using the REST API, it returns either:
- `true`
- `false`

In Magento 2.3-develop, when you create a new attribute option using the REST API, it returns either:
- `"new_option"`
- `false`

The purpose of this PR (correct me if I'm wrong) was to return either:
- `{"label":"some label","value":"123"}`
- `false`

Reading @okorshenko remarks, I think the following needed to be returned (but might be wrong about that):
- `123`
- `false`

After git bisecting, it looks like 5eef1d9fd7fbe7a39344a02fab6e3795465d5af1 caused the problem.

So what was ultimately decided what needed to be returned? I assume `"new_option"` isn't really correct?

Would be great if either @sanjay-wagento or @sidolov could review and make sure that the correct thing happens here.

If I need to turn this into a new issue, please let me know.

Thanks!

2019-01-11 08:48 UTC, milindsingh commented
> Hi all involved
> 
> Something seems to have gone wrong here.
> This was discovered totally by accident btw.
> 
> In Magento 2.2-develop, when you create a new attribute option using the REST API, it returns either:
> 
> * `true`
> * `false`
> 
> In Magento 2.3-develop, when you create a new attribute option using the REST API, it returns either:
> 
> * `"new_option"`
> * `false`
> 
> The purpose of this PR (correct me if I'm wrong) was to return either:
> 
> * `{"label":"some label","value":"123"}`
> * `false`
> 
> Reading @okorshenko remarks, I think the following needed to be returned (but might be wrong about that):
> 
> * `123`
> * `false`
> 
> After git bisecting, it looks like [5eef1d9](https://github.com/magento/magento2/commit/5eef1d9fd7fbe7a39344a02fab6e3795465d5af1) caused the problem.
> 
> So what was ultimately decided what needed to be returned? I assume `"new_option"` isn't really correct?
> 
> Would be great if either @sanjay-wagento or @sidolov could review and make sure that the correct thing happens here.
> 
> If I need to turn this into a new issue, please let me know.
> 
> Thanks!

@hostep You are correct as original discussion was not to just return the id but the complete option data.
But as suggested by @mbrinton01 in https://github.com/magento/magento2/issues/6300#issuecomment-451190623 I have backported this PR.

I still believe that it should return the complete option data.