resolved default country selection issue while creating new customer …
magento/magento2 pull request #13024
Opened 2018-01-07 04:18 UTC by pradeep-wagento

Backend Works

### Description
Insert the "is_default" field country options based on website scope into country option array.
Used the "is_default" value in customer edit address form to pre selected the country. 

### Fixed Issues (if relevant)
1. magento/magento2#3483: Default country selection issue while creating new customer from backend

### Manual testing scenarios
1. Fresh Install
2. Tested in all Modes
3. Ran Successfull Test Cases

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-07 04:18 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13024) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13024) before we can accept your contribution.<br/>

2018-01-07 05:12 UTC, ishakhsuvarov requested changes

2018-01-07 05:12 UTC, ishakhsuvarov commented on app/code/Magento/Directory/Model/ResourceModel/Country/Collection.php
> +    protected $storeManager;
Please avoid adding new `protected` methods and properties. This may be made private.

2018-01-07 05:12 UTC, ishakhsuvarov commented on app/code/Magento/Directory/Model/ResourceModel/Country/Collection.php
> +        \Magento\Store\Model\StoreManagerInterface $storeManager,
Adding a new required parameter to the constructor may break compatibility for any client code that already extends it.
To try and avoid it please refactor it in the backward compatible way. More information is available in the [devdocs](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter).

2018-01-07 05:12 UTC, ishakhsuvarov commented on app/code/Magento/Directory/Model/ResourceModel/Country/Collection.php
> +        foreach ($this->storeManager->getWebsites() as $website) {
Is it required to load configurations for all the websites at once?

2018-01-07 05:12 UTC, ishakhsuvarov commented on app/code/Magento/Ui/view/base/web/js/form/element/country.js
> +                _.each(result, function (item) {
Do you think it is possible to refactor this using `_.filter`?

2018-01-07 05:14 UTC, ishakhsuvarov commented
Hi @pradeep-wagento 
Thank you for your contribution. Please fix the following so we will be able to proceed with the processing:
 - [ ] PR review comments
 - [ ]  Failing Jenkins CI tests for the PR: https://travis-ci.org/magento/magento2/jobs/325956047, https://travis-ci.org/magento/magento2/jobs/325956049

2018-03-09 10:02 UTC, sidolov commented
Applied changes requested by @ishakhsuvarov

2018-03-14 16:47 UTC, merged