Resolved Checkout-Payment-Wrong promo code cancelled issue
magento/magento2 pull request #13030
Opened 2018-01-07 06:12 UTC by chiragp-wagento

Wrong promo code cancelled issue on Checkout > Payment and Cart page.

### Description
Disabled the input box for promo code when promo code is already applied to the site.

### Manual testing scenarios

1. Create one cart price rule from admin side Marketing > Cart Price Rules and use Specific Coupon for Coupon field or use any existing promo code to use in front side.
2. Add any product in cart
3. Apply promo code from cart page
4. Once promo code is applied then input box for add promo code will be disabled, we need to cancel the existing applied promo code then we apply new one.
5. Same with checkout page, apply any promo code on checkout page.

### Expected result
Promo code input box will be disabled once we apply any promo code.

### Actual result
Promo code removed

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-07 06:12 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13030) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13030) before we can accept your contribution.<br/>

2018-01-07 08:01 UTC, ishakhsuvarov requested changes

2018-01-07 08:01 UTC, ishakhsuvarov commented on app/code/Magento/SalesRule/view/frontend/web/template/payment/discount.html
> +                        <!-- ko ifnot: isApplied() -->
This whole condition may be simplified to something like `data-bind="attr:{disabled:isApplied()}"`.
This will allow to avoid copy-pasting the code

2018-01-09 14:57 UTC, ishakhsuvarov approved these changes

2018-01-10 18:01 UTC, merged