Eliminate the need for inheritance for action controllers.
magento/magento2 pull request #13045
Opened 2018-01-07 18:01 UTC by Vinai

### Description
Kindly see issue https://github.com/magento/community-features/issues/9 for detailed information.

### Fixed Issues (if relevant)
All the CE unit and integration tests pass. The big question is how the EE will do.
When this PR is merged, frontend action controllers don't have to extend AbstractAction, they only have to implement the ActionInterface.

Backend action controllers still have to extend the backend module abstract Action for authentication - moving that to a plugin will be a separate PR.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-08 10:50 UTC, Vinai commented
The failing Codacity quality review is a false positive, since using the object manager in integration tests is necessary.

2018-01-09 18:35 UTC, dmanners commented
@Vinai thanks for this and for fixing the false positive. I have message @antonkril about taking a look over this PR since he was the first one that raised this problem.

2018-01-09 19:34 UTC, Vinai commented
Did supressing the check work? Anyway, if there’s something I can do to make the PR better so it can be accepted let me know please.

2018-01-10 06:49 UTC, Vinai commented
Adding the `@SuppressWarnings(PHPMD.StaticAccess)` annotation to the method PHPDoc block did not suppress the warning. I've amended the commit with the annotation on the whole class - maybe that works in Codacity.

2018-02-07 00:39 UTC, paliarush requested changes
1. Please add php docs for all new methods and classes (except for tests)

2. The following plugins should be rewritten as well:
CE: `\Magento\Customer\Model\Plugin\CustomerNotification::beforeDispatch`
EE: `\Magento\Logging\App\Action\Plugin\Log::beforeDispatch`
`\Magento\CustomerSegment\Model\App\Action\ContextPlugin::aroundDispatch`
B2B: `\Magento\Company\Plugin\Framework\App\Action\AbstractActionPlugin::aroundDispatch`
CE should be fixed in scope of current PR. 
Related PRs should be created for EE and B2B.

3. Migration steps should be added to the list of backward incompatible changes on the dev docs for someone who declares plugins for `dispatch()`

4. What do you think about deprecating `\Magento\Framework\App\Action\AbstractAction::dispatch` and not invoking it anymore from `\Magento\Framework\App\FrontController::dispatch` (after moving authentication)?

5. In the PhpDoc of `\Magento\Framework\App\ActionInterface::execute()` we promise to add 'request' as an argument in the future. I don't think it will be possible because of backward compatibility issues for all existing action controllers. Do you see any solution for this? If not, let's remove that comment

2018-02-07 00:39 UTC, paliarush commented on app/code/Magento/Customer/Test/Unit/Model/App/Action/ContextPluginTest.php
> +        $this->plugin->beforeExecute($this->subjectMock, $this->requestMock);
`beforeExecute` does not accept second argument.

2018-02-07 00:39 UTC, paliarush commented on app/code/Magento/Store/Test/Unit/App/Action/Plugin/StoreCheckTest.php
> +        $this->_plugin->beforeExecute($this->subjectMock, $this->requestMock);
`beforeExecute` does not accept second argument

2018-02-07 00:39 UTC, paliarush commented on app/code/Magento/Theme/Test/Unit/Model/Theme/Plugin/RegistrationTest.php
> +        $this->plugin->beforeExecute($this->action, $this->request);
Request argument should be removed.

2018-02-07 00:39 UTC, paliarush commented on app/code/Magento/Weee/Test/Unit/App/Action/ContextPluginTest.php
> +        $this->contextPlugin->beforeExecute($action, $request);
Second argument should be removed (including other occurrences below)

2018-02-07 00:39 UTC, paliarush commented on lib/internal/Magento/Framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php
> +class ActionFlagNoDispatchPlugin
Please add php doc

2018-02-07 00:39 UTC, paliarush commented on lib/internal/Magento/Framework/App/Action/Plugin/EventDispatchPlugin.php
> +class EventDispatchPlugin
Please add php doc

2018-02-07 00:39 UTC, paliarush commented on lib/internal/Magento/Framework/App/Action/Plugin/EventDispatchPlugin.php
> +        return [];
Should return void when arguments are not modified.

2018-02-07 09:18 UTC, Vinai commented on app/code/Magento/Customer/Test/Unit/Model/App/Action/ContextPluginTest.php
> +        $this->plugin->beforeExecute($this->subjectMock, $this->requestMock);
Fixed

2018-02-07 09:22 UTC, Vinai commented on app/code/Magento/Store/Test/Unit/App/Action/Plugin/StoreCheckTest.php
> +        $this->_plugin->beforeExecute($this->subjectMock, $this->requestMock);
Fixed

2018-02-07 09:26 UTC, Vinai commented on app/code/Magento/Theme/Test/Unit/Model/Theme/Plugin/RegistrationTest.php
> +        $this->plugin->beforeExecute($this->action, $this->request);
Fixed.

2018-02-07 09:34 UTC, Vinai commented on app/code/Magento/Weee/Test/Unit/App/Action/ContextPluginTest.php
> +        $this->contextPlugin->beforeExecute($action, $request);
Fixed.

2018-02-07 09:37 UTC, Vinai commented on lib/internal/Magento/Framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php
> +class ActionFlagNoDispatchPlugin
What goes there? Looking at other classes I find not all have a PHPDoc class comment. It only seems to be present if there is an `@api` annotation or a `@SuppressWarnings` annotation.
Can you point me to some documentation maybe?

2018-02-07 09:38 UTC, Vinai commented on lib/internal/Magento/Framework/App/Action/Plugin/EventDispatchPlugin.php
> +class EventDispatchPlugin
I have the same question as for the `ActionFlagNoDispatchPlugin` above.

2018-02-07 09:40 UTC, Vinai commented on lib/internal/Magento/Framework/App/Action/Plugin/EventDispatchPlugin.php
> +        return [];
Fixed.

2018-02-07 09:51 UTC, Vinai commented
Thank you for your review, @paliarush!  

Regarding your non-inline comments I have a couple of questions:

> 1. Please add php docs for all new methods and classes (except for tests)

I think I've added PHPDoc blocks to all non-test methods. What do I set for classes that don't have `@api` or `@SuppressWarnings` annotations? I can't find consistent examples using the core code.

> 3. Migration steps should be added to the list of backward incompatible changes on the dev docs for someone who declares plugins for `dispatch()`

I don't think there are any backward incompatible changes introduced by this PR.

> 4. What do you think about deprecating `\Magento\Framework\App\Action\AbstractAction::dispatch` and not invoking it anymore from `\Magento\Framework\App\FrontController::dispatch` (after moving authentication)?

That would be a nice change. Not calling `dispatch` any more would break soooooo much third party code, I think it will probably have to stay in place for a very long time.
That said, I would love adding a `@deprecated` annotation to `\Magento\Framework\App\Action\AbstractAction::dispatch`. But is this PR the right scope for that? I think probably not.

> 5. In the PhpDoc of \Magento\Framework\App\ActionInterface::execute() we promise to add 'request' as an argument in the future. I don't think it will be possible because of backward compatibility issues for all existing action controllers. Do you see any solution for this? If not, let's remove that comment.

I don't see a way to do that either without causing massive disruption, and that change is not worth it. A consequence of that is that the request object should be declared an injectable (which is how it is already used in much third party code anyway). This is only a devdocs change I guess.

I'm working on patching `\Magento\Customer\Model\Plugin\CustomerNotification::beforeDispatch` and will update the PR when I'm done.

2018-02-07 10:31 UTC, Vinai commented
Ready for next review (if the build is green).

2018-02-07 13:34 UTC, Vinai commented
`\Magento\Customer\Model\Plugin\CustomerNotification::beforeDispatch()` refactored and the static tests are fixed. Ready for next review.

2018-02-07 15:00 UTC, paliarush commented
@Vinai Thank you for such a valuable PR.

1. I meant adding some description to PhpDoc for every new method and class, not just annotations.

2. So how do we make sure that corresponding PRs to EE and B2B will be merged along with current one? This requirement should be made clear for Community Engineering team, before they merge

3. This PR is backward incompatible from SPI point of view. Scenario: someone creates a new plugin for `dispatch()` in their extension. After this PR, such customizations will be ignored for all controllers not extending from the abstract controller. That's why we must make sure this will be highlighted in the  backward compatibility guide

4. Could you please explain the scenario when it will break 3rd party extensions (assuming we accept corresponding PR for the backend controllers)? I believe it is a good PR to mark `dispatch()` as deprecated

2018-02-07 15:46 UTC, Vinai commented
> 1. I meant adding some description to PhpDoc for every new method and class, not just annotations.

Thanks for clarifying, done.

> 2. how do we make sure that corresponding PRs to EE and B2B will be merged along with current one? This requirement should be made clear for Community Engineering team, before they merge.

I don't know. Do you have a suggestion how to proceed? maybe it can be coordinated via slack?

> 3. This PR is backward incompatible from SPI point of view. Scenario: someone creates a new plugin for dispatch() in their extension. After this PR, such customizations will be ignored for all controllers not extending from the abstract controller. That's why we must make sure this will be highlighted in the backward compatibility guide

This is already the case since 2.0. Any frontend action that didn't return a `Layout` or `Page` result already could simply implement the `ActionInterface` and it worked just fine. I know of several cases where the `Action` class wasn't used. In those cases `dispatch()` already isn't called.
But okay, I see your point - probably many developers where not aware of this.
On what devdocs page are such changes collected? What branch? If you want I can add PR.

> 4. Could you please explain the scenario when it will break 3rd party extensions (assuming we accept corresponding PR for the backend controllers)? I believe it is a good PR to mark dispatch() as deprecated

Marking the `dispatch` method as deprecated will not break 3rd party extensions, just adding the request as an argument to `ActionIngerface::execute()` would.   
When this PR is merged I hope to make another PR that moves the backend authentication into plugins. That would probably be the right PR to mark the `dispatch()` method as `deprecated()`.

> 5. Please remove the promise from DocBlock of `\Magento\Framework\App\ActionInterface::execute()`

2018-02-07 17:26 UTC, Vinai commented
The travis build is hanging. Can you restart it?

2018-02-07 19:55 UTC, paliarush commented
@Vinai thank you for making changes, PR looks good to me now.

@ishakhsuvarov please take care of items 2 and 3 from the list above before merging the PR.

2018-03-24 12:36 UTC, mcspronko commented
Hi @Vinai, I've merged the latest mainline with new integration tests, checked and fixed them. Also, fixed PHPDoc for the EventDispatchPlugin class.

2018-03-25 08:46 UTC, Vinai commented
Thanks @mcspronko.

@paliarush, I think I addressed all changes you requested, yet the review is still marked as pending? Can you check please?

2018-06-16 19:00 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13045) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13045) before we can accept your contribution.<br/>**7** out of **13** committers have signed the CLA.<br/><br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: VitaliyBoyko<br/>:white_check_mark: chirag-wagento<br/>:white_check_mark: hitesh-wagento<br/>:white_check_mark: NamrataChangani<br/>:white_check_mark: Radio<br/>:white_check_mark: rogyar<br/>:x: wert2all<br/>:x: aakimov<br/>:x: ameysar<br/>:x: magento-engcom-team<br/>:x: Mariana Lashch<br/>:x: olysenko<hr/>**Mariana Lashch** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-06-16 19:01 UTC, Vinai commented
I've resolve the merge conflicts. How to proceed with this PR?

2018-06-18 09:25 UTC, Vinai commented
Why is the Travis build not starting?

2018-06-20 11:41 UTC, Vinai commented
Closing in favor of PR #16268 to the 2.3-develop branch.

2018-06-20 11:41 UTC, closed without merging