Fix missing discount label in checkout
magento/magento2 pull request #13141
Opened 2018-01-11 16:33 UTC by ihor-sviziev

### Description
The discount label was not being shown in the shopping cart totals description
Continuing of https://github.com/magento/magento2/pull/11883

### Fixed Issues
1. magento/magento2#11497: Discount Rule does not show Default Rule Label
2. magento/magento2#11428: Cart Price Rule Label is not working

### Manual testing scenarios
1. Add a discount to quote
2. Go to the shopping cart and now see the discount label in the totals description

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-11 18:15 UTC, rogyar requested changes

2018-01-11 18:15 UTC, rogyar commented on app/code/Magento/SalesRule/view/frontend/web/js/view/summary/discount.js
> +            var discountSegments = this.totals()['total_segments'].filter(function (segment) {
All variables declarations must be at the top of the function scope. Please, try to move the variable declaration to the beginning of the getTitle() function

2018-01-11 18:15 UTC, rogyar commented on app/code/Magento/SalesRule/view/frontend/web/js/view/summary/discount.js
> +                return (segment.code === 'discount');
I guess, the parenthesis is redundant here. This fact is the reason of failing static tests

2018-01-11 20:40 UTC, okorshenko commented
@rogyar Thank you for the review! 👍

2018-01-13 09:45 UTC, rogyar approved these changes

2018-01-17 17:12 UTC, merged

2018-04-13 07:40 UTC, pemann commented
Is this part of the upcoming 2.2.4 release?

2018-06-12 12:45 UTC, rsantellan commented
This fix is part of the release 2.2.4 and now my custom discount is shown but the label discount is not. Is there a way to fix that ? Because it only check the word discount not any thing containing discount.

2018-06-13 07:00 UTC, ihor-sviziev commented
@rsantellan feel free to create PR with your changes