Typo cleanup for dev
magento/magento2 pull request #13300
Opened 2018-01-21 20:17 UTC by akiojalehto

### Description
Cleanups continue. No breaking changes, just misspellings.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-25 15:20 UTC, dmanners requested changes

2018-01-25 15:20 UTC, dmanners commented on dev/tests/functional/tests/app/Magento/Catalog/Test/Handler/CatalogProductSimple/Curl.php
> +     * Preparation weather product 'Is Virtual'.
Guess this should actually be whether.

2018-01-25 17:49 UTC, akiojalehto commented on dev/tests/functional/tests/app/Magento/Catalog/Test/Handler/CatalogProductSimple/Curl.php
> +     * Preparation weather product 'Is Virtual'.
Whoops, reverted this one :)

2018-01-26 08:44 UTC, dmanners approved these changes

2018-01-28 16:22 UTC, merged