Experius 2.1 patch empty country options in checkout
magento/magento2 pull request #13363
Opened 2018-01-25 13:06 UTC by experius-nl

In the checkout, the country select contains empty values. This commit will fix this issue.

### Description
In the country select option in the checkout there are empty values.

### Manual testing scenarios

1. Enable country in checkout
2. Have at least 2 or more available countries configured
3. Add a product to your cart
4. Go to the checkout
5. Open the country select
![country](https://user-images.githubusercontent.com/5173161/35389656-d71cd158-01d8-11e8-9e50-3e9e49122996.png)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [x ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-25 13:06 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13363) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13363) before we can accept your contribution.<br/><hr/>**Maikel Bakker** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-01-25 15:46 UTC, miguelbalparda commented
@experius-nl keep in mind you will need to sign the CLA with the same user who did the commits.

2018-03-22 10:40 UTC, sidolov requested changes
Please, sign CLA, otherwise we can't process your PR

2018-03-22 10:40 UTC, sidolov commented on app/code/Magento/Directory/Model/ResourceModel/Country/Collection.php
> +    public function toOptionArray($emptyLabel = false)
Provided changes are backward incompatible, please, follow [Backward compatible development documentation](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/#modifying-the-default-values-of-optional-arguments-in-public-and-protected-methods)

2018-04-18 16:44 UTC, okorshenko commented
Hi @experius-nl 
Thank you for your contribution. We cann't accept such changes due to backward compatibility policy

2018-04-18 16:44 UTC, closed without merging