2.3 develop 13296
magento/magento2 pull request #13402
Opened 2018-01-28 10:09 UTC by vinayshah

- Fixed Issue with double quotes in category URL rewrite tree
- Issue regarding test resolved

merge request for 2.2-develop submitted (#13397)
### Description

Escape special character with double quotes or single quotes while displaying tree in the URL rewrite page.

### Fixed Issues (if relevant)

1. magento/magento2#13296: Category name with special characters brakes in url rewrites category tree

### Manual testing scenarios

1. Create a category with quotes (") in its name. eg. Test "Category"
2. Try to create a URL rewrite (Go to Admin>>Marketing>>URL Rewrites>>Add URL Rewrite)
3. Select For Category in the drop-down
4. Then category tree get's loaded below

Review [screenshot](https://drive.google.com/file/d/1NB4XQpuXL7dTnD_mheRcHc4YuQmFM8Xx/view)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-28 21:00 UTC, ishakhsuvarov commented
Hi @vinayshah 
I have removed your assignment from the Pull Requests as it is intended to assign people who are doing actual processing and merging of the PR.
Thanks

2018-01-30 03:49 UTC, vinayshah commented
Hi @ishakhsuvarov ,
Okay, no problem. I didn't knew about it.
Thanks.

2018-04-02 16:40 UTC, VladimirZaets requested changes

2018-04-02 16:40 UTC, VladimirZaets commented on lib/web/underscore.js
> +    '`': '&#x60;',
Hi @vinayshah. Underscore.js is a separate library, we can't make changes to it. I think we can add a wrapper to this method inside `mageUtils`.

2018-04-02 16:41 UTC, VladimirZaets requested changes

2018-04-02 16:41 UTC, VladimirZaets commented on lib/web/underscore.js
> +    '`': '&#x60;',
Hi @vinayshah. Underscore.js is a separate library, we can't make changes to it. I think we can add a wrapper to this method inside `mageUtils`.

2018-04-16 22:07 UTC, merged

2018-04-16 22:09 UTC, magento-engcom-team commented
Hi @vinayshah. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.