Execute collection tasks only when a valid collection is passed to th…
magento/magento2 pull request #13574
Opened 2018-02-08 20:31 UTC by mgarciaavz

…e data source of a UI Component form. This prevents ui forms not attached to collections to crash on filtering

### Description

There should be some check in order to perform collection actions only if the data source of UI Componet forms contents and actual valid collection, and avoiding them if not. This keeps model-collections forms working as usual, and avoids crashes on stand-alone forms.

### Fixed Issues (if relevant)

1. magento/magento2#13573: UI Component forms not related with any model throw fatal error

### Manual testing scenarios

1. Starting from a vanilla Magento, download, install and enable your own sample Form UI Component, following the instructions given at: https://github.com/magento/magento2-samples/tree/master/sample-module-form-uicomponent
2. Go to the URL provided by the extension, which is [magento2-admin-url]/sampleform
3. You should now get the expected form: 
![sample_form](https://user-images.githubusercontent.com/11211929/35996437-d53d4450-0d16-11e8-8b31-13685ca1df2e.png)

### Contribution checklist
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [-] All new or changed code is covered with unit/integration tests (if applicable)
 - [-] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-08 20:31 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13574) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13574) before we can accept your contribution.<br/>

2018-03-16 16:13 UTC, rogyar requested changes

2018-03-16 16:13 UTC, rogyar commented on app/code/Magento/Ui/Component/Form.php
> +            $this->getContext()->getDataProvider()
I believe we don't need invoking  `$this->getContext()->getDataProvider()` once again since we have added `$dataProvider` variable

2018-03-16 16:14 UTC, rogyar commented
@mgarciaavz thank you for your contribution.
Please, consider fixing the failing tests and the issues described above.

2018-03-24 11:08 UTC, mgarciaavz commented
Thank you for your comment @rogyar, I already implemented as you mentioned and fixed the failing tests (still waiting for Travis' results 🤞)

2018-03-26 12:55 UTC, rogyar approved these changes

2018-03-26 12:57 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-1092](https://jira.corp.magento.com/browse/ENGCOM-1092) has been created to process this Pull Request

2018-08-09 10:13 UTC, rogyar commented
Hi @mgarciaavz. Unfortunately, the provided changes bring failing performance tests. The form UI component changes significantly slow down the rendering time:

Server Side EE Admin Customer Management:
Edit Customer 886.00ms +135.6% (+510ms) DEGRADATION
Server Side EE Admin Edit Product:
Edit Simple Product 560.00ms +34.3% (+143ms) DEGRADATION
Edit Simple Product Save 1043.00ms +16.0% (+144ms) DEGRADATION
Edit Configurable Product 730.00ms +21.9% (+131ms) DEGRADATION

So, we need to adjust the approach in order to avoid performance issues. Thank you.

2018-08-22 08:29 UTC, rogyar commented
I'm closing this PR due to inactivity. Please, feel free to reopen it if you decide to proceed. Thank you

2018-10-08 10:33 UTC, mgarciaavz commented
Reopening this issue. I'll try a different approach.

2018-11-19 10:56 UTC, sivaschenko commented
Hi @mgarciaavz , thanks for collaboration! If you'd like to continue working on this contribution, please port this pull request to 2.3-develop branch as this improvement should first be introduced to 2.3: https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules

2018-12-06 17:02 UTC, sidolov commented
Hi @mgarciaavz , will you continue with the PR?

2018-12-09 16:00 UTC, sidolov commented
Hi @mgarciaavz , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-12-09 16:00 UTC, closed without merging