[Forwardport] magento/magento2#13498 issue #13497 - Method getUrl in Magento\Catalog\Model\Product\Attribute\Frontend\Image
magento/magento2 pull request #13635
Opened 2018-02-13 12:13 UTC by nmalevanec

### Original Pull Request
https://github.com/magento/magento2/pull/13498 (created by @igortregub)

### Included Commits
1. 220ad974a2f440c428a15c87a861483b83a23154
### Fixed Issues (if relevant)
1. magento/magento2#13498: Method getUrl in Magento\Catalog\Model\Product\Attribute\Frontend returns image url with double slash

### Manual testing scenarios
1. Try to get product image via method getUrl from class Magento\Catalog\Model\Product\Attribute\Frontend\Image. Example(console command):
```
protected function execute(InputInterface $input, OutputInterface $output)
    {
        ObjectManager::getInstance()->get(State::class)->setAreaCode(Area::AREA_ADMINHTML);
        //Be sure, you have simple product with sku = "s1" with image.
        $product = ObjectManager::getInstance()->get(ProductRepositoryInterface::class)->get('s1');
        $attributeRepository = ObjectManager::getInstance()->get(AttributeRepositoryInterface::class);
        $imageAttribute = $attributeRepository->get(4, 'image');
        $image = ObjectManager::getInstance()->get(\Magento\Catalog\Model\Product\Attribute\Frontend\Image::class);
        $image->setAttribute($imageAttribute);
        $output->writeln($image->getUrl($product));
    }
```
2. Check, image url has only single slashes ex: "http://domain/pub/media/catalog/product/t/e/test.jpg".

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-16 15:49 UTC, ihor-sviziev approved these changes

2018-02-16 15:52 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[MAGETWO-87979](https://jira.corp.magento.com/browse/MAGETWO-87979) has been created to process this Pull Request

2018-02-16 21:01 UTC, orlangur requested changes
@nmalevanec please rewrite branch so that original commit author is preserved (for example, with cherry pick)

2018-02-19 14:24 UTC, nmalevanec commented
@orlangur, done.

2018-02-19 14:33 UTC, orlangur approved these changes

2018-02-19 14:36 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[MAGETWO-87979](https://jira.corp.magento.com/browse/MAGETWO-87979) has been created to process this Pull Request

2018-02-21 02:17 UTC, merged