Fix de_CH case of FormatTest::getPriceFormatDataProvider
magento/magento2 pull request #13708
Opened 2018-02-17 17:13 UTC by peteraba

Fix unit test FormatTest::getPriceFormatDataProvider, 1 out 4 cases currently fail on my machine forked from 2.2.2.

2018-02-17 17:13 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13708) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13708) before we can accept your contribution.<br/>

2018-03-13 13:15 UTC, orlangur requested changes

2018-03-13 13:15 UTC, orlangur commented on lib/internal/Magento/Framework/Locale/Test/Unit/FormatTest.php
> -            ['de_CH', ['decimalSymbol' => '.', 'groupSymbol' => '\'']],
This needs to be investigated further.

This case is failing on my local machine as well but it is passing on Bamboo and Travis CI.

Please rework a test in such a way that it passes both on Travis CI https://travis-ci.org/magento/magento2/jobs/342788625 and your local machine.

2018-03-24 14:48 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

2018-03-24 14:48 UTC, closed without merging