fix for EAV ReadHandler
magento/magento2 pull request #13752
Opened 2018-02-20 16:43 UTC by marcinfr

Fix for issue #6958

### Description
Function of Magento\Eav\Model\ResourceModel\ReadHandler the attribute values were sort by store_id desc and then merged by a union query. In the following loop the store view values can be overwritten by default store value.

### Fixed Issues (if relevant)

1. magento/magento2#6958: Magento\Eav\Model\ResourceModel\ReadHandler wrong sort of entityData

### Manual testing scenarios

1. Create an attribute value_id for a store_view lower than value_id of store_view 0 for attribute "name" of product 
2. Edit Product in backend and switch store_view from default to specific store_view

2018-02-20 16:43 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13752) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13752) before we can accept your contribution.<br/><hr/>**Marcin Frymark** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-08-16 09:48 UTC, magento-engcom-team commented
@marcinfr thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-08-16 20:19 UTC, larsroettig commented
@marcinfr can you sign pls our Contributor License Agreement: https://cla.dev.magento.com/magento/magento2?pullRequest=13752

2018-08-16 20:28 UTC, larsroettig requested changes

2018-08-16 20:28 UTC, larsroettig commented on app/code/Magento/Eav/Model/ResourceModel/ReadHandler.php
> +                $attributeValues = array_merge($attributeValues, $attrTablesValues);
Dont use array merge in foreach it is very slow 

See: https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-function-used-in-loop

Better soultion 
```php
 foreach ($attributeTables as $attributeTable) {
                $select = $connection->select()
                    ->from(
                        ['t' => $attributeTable],
                        ['value' => 't.value', 'attribute_id' => 't.attribute_id']
                    )
                    ->where($metadata->getLinkField() . ' = ?', $entityData[$metadata->getLinkField()]);
                foreach ($context as $scope) {
                    //TODO: if (in table exists context field)
                    $select->where(
                        $metadata->getEntityConnection()->quoteIdentifier($scope->getIdentifier()) . ' IN (?)',
                        $this->getContextVariables($scope)
                    )->order('t.' . $scope->getIdentifier() . ' ASC');
                }
                $attributeValues[]  = $connection->fetchAll($select);
            }

            $attributeValues = array_merge(...$attributeValues);
			foreach ($attributeValues as $attributeValue) {
            ....
```

2018-10-10 09:47 UTC, marcinfr commented
@larsroettig Thank You for this knowledge, i did fix it in my code. Can You check again?

2018-10-10 09:59 UTC, larsroettig commented
HI @marcinfr, no Problem I will check this PR today at the evening. 

Best regards, 

Lars

2018-11-19 11:04 UTC, sivaschenko commented
Hi @marcinfr , this pull request is causing performance degradation:

    Get Configurable Product Options (Add To Cart By Guest): 13.3% (mainline = 30 | team = 34) -> DEGRADATION
    Simple Product 1 Add To Wishlist (Add to Wishlist): 17.8% (mainline = 45 | team = 53) -> DEGRADATION
    Simple Product 2 Add To Wishlist (Add to Wishlist): 15.4% (mainline = 52 | team = 60) -> DEGRADATION
    Simple Product 3 Add To Wishlist (Add to Wishlist): 15.7% (mainline = 51 | team = 59) -> DEGRADATION
    Simple Product 4 Add To Wishlist (Add to Wishlist): 15.7% (mainline = 51 | team = 59) -> DEGRADATION
    Simple Product 5 Add To Wishlist (Add to Wishlist): 15.7% (mainline = 51 | team = 59) -> DEGRADATION
    Simple Product 1 Comparison Add (Compare Products): 15.4% (mainline = 26 | team = 30) -> DEGRADATION
    Simple Product 2 Comparison Add (Compare Products): 18.2% (mainline = 22 | team = 26) -> DEGRADATION
    Configurable Product 1 Comparison Add (Compare Products): 14.3% (mainline = 28 | team = 32) -> DEGRADATION
    Get Configurable Product Options (Checkout By Guest): 13.8% (mainline = 29 | team = 33) -> DEGRADATION
    Get Configurable Product Options (Checkout By Customer): 13.8% (mainline = 29 | team = 33) -> DEGRADATION
    Get Configurable Product Options (Add To Cart By Customer): 13.8% (mainline = 29 | team = 33) -> DEGRADATION
    New Bundle Product Validate (Admin Create Product): 21.1% (mainline = 19 | team = 23) -> DEGRADATION
    New Bundle Product Save (Admin Create Product) - Another one: 10.6% (mainline = 226 | team = 250) -> DEGRADATION
    New Configurable Product Validate (Admin Create Product): 21.1% (mainline = 19 | team = 23) -> DEGRADATION
    New Downloadable Product Validate (Admin Create Product): 22.2% (mainline = 18 | team = 22) -> DEGRADATION
    New Simple Product Validate (Admin Create Product): 22.2% (mainline = 18 | team = 22) -> DEGRADATION
    Edit Simple Product Validate (Admin Edit Product): 20% (mainline = 20 | team = 24) -> DEGRADATION
    Edit Simple Product Save (Admin Edit Product): 12.7% (mainline = 221 | team = 249) -> DEGRADATION
    Edit Configurable Product Validate (Admin Edit Product): 13.3% (mainline = 30 | team = 34) -> DEGRADATION
    Get category (API Catalog Browsing): 30.8% (mainline = 13 | team = 17) -> DEGRADATION
    Search for simple product on frontend (API Search): 11.4% (mainline = 35 | team = 39) -> DEGRADATION
    Check product (API Product Management): 14.8% (mainline = 27 | team = 31) -> DEGRADATION
    Check product with extensible data objects (API Product Management): 14.8% (mainline = 27 | team = 31) -> DEGRADATION
    Create category (Admin Category Management): 21.8% (mainline = 293 | team = 357) -> DEGRADATION
    Move category (Admin Category Management): 44.2% (mainline = 181 | team = 261) -> DEGRADATION
    Delete category (Admin Category Management): 22.2% (mainline = 36 | team = 44) -> DEGRADATION

Could you take a look if there is a way to optimize this fix?

2018-12-06 17:03 UTC, sidolov commented
Hi @marcinfr , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-12-06 17:03 UTC, closed without merging