Catalog price rule save is too slow #13378, ignore on demand reindex …
magento/magento2 pull request #13764
Opened 2018-02-21 05:12 UTC by pkodithuwakku

Fixes the performance issue occurs when creating a new catalog rule with a large catalog. the catalog rule indexer mode is set to "Update on Schedule"

### Description
When creating a catalog rule, Magento tries to retrieve matching products ids and pass the collected product ids to the indexer. However, the Magento\CatalogRule\Model\Rule:afterSave() method doesn't consider the indexer mode, and even when the catalogrule indexer is set to "Update on Schedule", Magento unnecessarily calls the "getMatchingProductIds" method and tries to collect the product ids.  Calling to "getMatchingProductIds" is unnecessary when the indexer mode is set to "Update on Schedule". When there is larger catalog this creates a performance issue that might then throws timeout errors.

This fix was done as part of the #MLAU18 contribution day.

### Fixed Issues (if relevant)
https://github.com/magento/magento2/issues/13378, (1st issue)

### Manual testing scenarios
1 Setup a Magento environment with a large catalog, ex: 20,000 products 
2 Create a catalog rule
3 Set rule condition, ex: category is 3
4 try to save the new Catalog Rule
5 Catalog rule saving is too slow, sometime it might give a timeout

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-21 05:12 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13764) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13764) before we can accept your contribution.<br/>

2018-02-22 22:31 UTC, mslabko requested changes

2018-02-22 22:31 UTC, mslabko commented on app/code/Magento/CatalogRule/Model/Rule.php
> +                $this->getMatchingProductIds();
please, refactore this: use returned value for comparing instead of using internal property

2018-03-07 15:52 UTC, magento-engcom-team commented
@pkodithuwakku thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-03-09 07:00 UTC, sidolov commented
Refactored according to @mslabko review

2018-03-09 07:01 UTC, sidolov commented
Hi @pkodithuwakku , please sign CLA, otherwise a can't accept your pull request

2018-03-15 11:06 UTC, sidolov commented
Hi @pkodithuwakku , any updates?

2018-03-23 13:32 UTC, sidolov commented
@user_name, unfortunately, I can't process this PR without signed CLA. 
Please reopen and update if you wish to continue.
Thank you for collaboration!

2018-03-23 13:32 UTC, closed without merging