Inconsistent Redirect
magento/magento2 pull request #13828
Opened 2018-02-23 14:38 UTC by chickenland

This controller has an inconsistent redirect mechanism (than other controllers in admin-notification).  This means that if the admin has a different URL, the admin user is returned to the frontend URL of the default store instead.

### Manual testing scenarios
1) Setup admin to run on a separate domain to the main site
2) Attempt to mass remove all notifications within admin

2018-02-27 15:34 UTC, ihor-sviziev requested changes

2018-02-27 15:34 UTC, ihor-sviziev commented on app/code/Magento/AdminNotification/Controller/Adminhtml/Notification/MassRemove.php
> +        return;
This is the end of the method. No need for return here

2018-02-28 06:28 UTC, ihor-sviziev approved these changes

2018-02-28 06:31 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-589](https://jira.corp.magento.com/browse/ENGCOM-589) has been created to process this Pull Request

2018-02-28 06:31 UTC, magento-engcom-team commented
@chickenland thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-02-28 21:29 UTC, merged