[Improvement] Implement customer group form on ui component
magento/magento2 pull request #13887
Opened 2018-02-28 11:59 UTC by simpleadm

### Description
Several versions ago backend grid widgets (`\Magento\Backend\Block\Widget\Grid`) were marked as 
deprecated in favour of UI component implementation. This PR refactors customer group form to use UI components. Also was added "Save and Continue Edit" button.
At least it will save time of third party developers who needs to extend customer groups form :)

### Manual testing scenarios
Before changes:
![image](https://image.prntscr.com/image/oBMGNBSnSHmUdZXNKH3ayw.png)

After changes:
![image](https://image.prntscr.com/image/QJ2aAibvRU2WVp8vJJmt-w.png)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-28 17:17 UTC, okorshenko commented
Hi @simpleadm thank you for this improvement. We will start review process now

2018-02-28 18:15 UTC, simpleadm commented
Please pay attention about backward compatibility in save controller and let me know if it should be fixed.
p.s. Functional test update will be commited soon.

2018-03-15 21:14 UTC, okorshenko commented
Hi @simpleadm 
We are ok with renaming request parameter for the controller in release 2.3.0. This might affect some tests, but we will try to fix them as well. New code must be covered with tests (unit or integration).
Please stabilize your current implementation and tests. Once branch is stable, we will proceed with testing and acceptance

2018-03-15 21:16 UTC, okorshenko requested changes
Please, fix broken tests

2018-03-29 10:22 UTC, sidolov commented
Hi @simpleadm , any updates?

2018-03-29 11:53 UTC, simpleadm commented
Hi @sidolov ,
I will be able continue this task next week

2018-04-03 12:20 UTC, sidolov commented
Hi @simpleadm , thanks for the information!

2018-04-17 13:00 UTC, simpleadm commented
Sorry, hope to start this task on current week :(

2018-04-17 14:11 UTC, VladimirZaets commented
Hi @simpleadm , do you have some update?

2018-06-02 08:12 UTC, sidolov commented
@simpleadm , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration!

2018-06-02 08:12 UTC, closed without merging