#5463 - Use specified hashing algo in \Magento\Framework\Encryption\Encryptor::getHash
magento/magento2 pull request #13884
Opened 2018-02-28 10:43 UTC by k4emic

### Description
\Magento\Framework\Encryption\Encryptor::getHash would previously ignore the specified hashing algorithm version that was supplied

### Fixed Issues (if relevant)
1. magento/magento2#5463: The ability to store passwords using different hashing algorithms is limited

### Manual testing scenarios
N/A, Magento currently has no support for specifying hashing algorithms by default.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-28 10:43 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13884) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13884) before we can accept your contribution.<br/>

2018-02-28 10:50 UTC, ihor-sviziev requested changes
Why haven't you passed $version variable at line 146?
https://github.com/magento/magento2/pull/13884/files#diff-07981c7827bdf60bd9649fa9f8ec974dR146

2018-02-28 11:37 UTC, k4emic commented
@ihor-sviziev This was an oversight on my part. I've updated the code and added coverage for it in the unit test.

2018-02-28 12:21 UTC, ihor-sviziev commented
@k4emic now your changes looks good. Could you squash your changes into 1 commit and force push to your branch?
Then I'll approve them

2018-02-28 13:36 UTC, k4emic commented
@ihor-sviziev Done. Let me know if I missed something.

2018-02-28 17:32 UTC, ihor-sviziev approved these changes

2018-02-28 17:34 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-618](https://jira.corp.magento.com/browse/ENGCOM-618) has been created to process this Pull Request

2018-02-28 17:34 UTC, magento-engcom-team commented
@k4emic thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-03-15 15:17 UTC, magento-engcom-team commented
@k4emic thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-03-16 14:21 UTC, merged