MAGETWO-59112 Backport 2.1.x
magento/magento2 pull request #13896
Opened 2018-02-28 21:12 UTC by Ctucker9233

Backport MAGETWO-59112 to 2.1.x

### Description
Backport MAGETWO-59112 to 2.1.x

### Fixed Issues (if relevant)
Invoice Address formating Issue

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-28 21:12 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=13896) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13896) before we can accept your contribution.<br/>

2018-02-28 21:20 UTC, Ctucker9233 commented
#6771 This is a backport to fix this issue

2018-02-28 22:47 UTC, Ctucker9233 commented
Travis build failed and I'm not sure why. Can someone take a look, please?

2018-03-01 12:46 UTC, magento-engcom-team commented
@Ctucker9233 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-03-01 13:59 UTC, sidolov requested changes

2018-03-01 13:59 UTC, sidolov commented on dev/tests/functional/tests/app/Magento/Catalog/Test/TestCase/Product/AddToCartCrossSellTest.xml
> +            <data name="tag" xsi:type="string">test_type:acceptance_test, test_type:extended_acceptance_test, stable:no</data>
Please, remove 'stable: no' tag and try to run test with backported fix.

2018-03-01 13:59 UTC, sidolov commented on dev/tests/functional/tests/app/Magento/Catalog/Test/TestCase/Product/NavigateRelatedProductsTest.xml
> +            <data name="tag" xsi:type="string">test_type:acceptance_test, test_type:extended_acceptance_test, stable:no</data>
Please, remove 'stable: no' tag and try to run test with backported fix.

2018-03-01 13:59 UTC, sidolov commented on dev/tests/functional/tests/app/Magento/Catalog/Test/TestCase/Product/NavigateUpSellProductsTest.xml
> +            <data name="tag" xsi:type="string">test_type:acceptance_test, test_type:extended_acceptance_test, stable:no</data>
Please, remove 'stable: no' tag and try to run test with backported fix.

2018-03-01 13:59 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/UrlRewrite/Block/Catalog/Edit/FormTest.php
> +        $this->markTestSkipped('Skipped until MAGETWO-63018');
Please, unskip test and try to run it.

2018-03-01 13:59 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/UrlRewrite/Block/Catalog/Edit/FormTest.php
> +        $this->markTestSkipped('Skipped until MAGETWO-63018');
Please, unskip test and try to run it.

2018-03-04 00:03 UTC, Ctucker9233 commented on dev/tests/integration/testsuite/Magento/UrlRewrite/Block/Catalog/Edit/FormTest.php
> +        $this->markTestSkipped('Skipped until MAGETWO-63018');
OK, let me try that.

2018-03-04 00:18 UTC, Ctucker9233 commented
@sidolov Made changes and waiting to see how the build goes.

2018-03-05 13:31 UTC, sidolov approved these changes

2018-03-05 21:28 UTC, merged