Send order email for Braintree Paypal orders
magento/magento2 pull request #13898
Opened 2018-03-01 03:50 UTC by pmclain

### Description
This commits adds a frontend observer for sending new order emails.

Order emails are sent using observers on the
`sales_model_service_quote_submit_success` event, but only in the
`webapi_rest` and `webapi_soap` areas. When customers checkout with
Braintree Paypal the order placement occurs in the `frontend` area with
a request to `Magento\Braintree\Controller\Paypal\PlaceOrder`, so these
orders were not sent a new order email.

### Fixed Issues (if relevant)
1. magento/magento2#13778 Braintree Paypal Method No Order Confirmation Email Sent
2. magento/magento2#12792 [2.1.10] No order confirmation email after paying with PayPal Express

### Manual testing scenarios
1. Enable Braintree including PayPal through Braintree
2. Complete PayPal purchase on store frontend. The redirect back to the store from PayPal should be to `braintree/paypal/review`
3. Completing the order place process should result in final request to `braintree/paypal/placeorder`
4. Will receive the new order email

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-01 13:30 UTC, sidolov commented on app/code/Magento/Quote/Observer/Frontend/SubmitObserver.php
> +    protected $logger;
Please avoid using protected properties, it may be private

2018-03-01 13:30 UTC, sidolov commented on app/code/Magento/Quote/Observer/Frontend/SubmitObserver.php
> +    protected $orderSender;
Please avoid using protected properties, it may be private

2018-03-01 13:40 UTC, sidolov requested changes
Avoid copy past of observer Magento/Quote/Observer/Webapi/SubmitObserver.php
Just move it from Webapi namespace and define configuration in Magento/Quote/etc/frontend/events.xml

2018-03-01 14:09 UTC, pmclain commented
@sidolov Moved the observer out of the Webapi namespace and updated the event configs.

2018-03-01 14:44 UTC, sidolov requested changes
Provide correct namespace for unit test (Magento\Quote\Test\Unit\Observer\Webapi -> Magento\Quote\Test\Unit\Observer)

2018-03-01 15:41 UTC, pmclain commented
@sidolov Wow that was sloppy. I've punished myself accordingly 😄

2018-03-01 16:01 UTC, sidolov approved these changes

2018-03-01 16:04 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-643](https://jira.corp.magento.com/browse/ENGCOM-643) has been created to process this Pull Request

2018-03-03 23:31 UTC, ghost approved these changes

2018-03-03 23:31 UTC, Achirawi commented
<iframe src="https://www.facebook.com/plugins/follow?href=https%3A%2F%2Fwww.facebook.com%2Fprofile.php%3Fid%3D100023737004476&amp;layout=standard&amp;show_faces=true&amp;colorscheme=light&amp;width=450&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>

2018-03-07 20:19 UTC, merged