Fix cache issue for currencies with no symbol
magento/magento2 pull request #13894
Opened 2018-02-28 17:29 UTC by evgk

Using getCurrencySymbol() leads to a bug for currencies where there is no currency symbol - cache ends up being non-unique. Using currency code for caching is a more foolproof way.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-28 19:11 UTC, orlangur requested changes
Please adopt corresponding test by fixing existing case and also add a new one, with empty currency symbol.

As always, please do amend commit and force push.

2018-03-05 14:58 UTC, evgk commented
@orlangur, I fixed the test and submitted an issue with instructions on how to reproduce the problem. Regarding a separate test with an empty currency-symbol, doesn't seem like it makes sense in the context of this fix, since the whole idea is to stop using currency-symbol and use currency-code for caching.

2018-03-09 12:41 UTC, orlangur commented
@evgk ok, looks like there is quite low probability of regression in this place.

2018-03-09 12:41 UTC, orlangur approved these changes

2018-03-09 12:43 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-826](https://jira.corp.magento.com/browse/ENGCOM-826) has been created to process this Pull Request

2018-03-09 12:43 UTC, magento-engcom-team commented
@evgk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-03-16 14:21 UTC, merged