Add a link to the cart to the success message when adding a product
magento/magento2 pull request #13904
Opened 2018-03-01 09:20 UTC by avstudnitz

### Description
If I add a product to the shopping cart, I want to go the cart directly after that in many cases without having to search for a link. Thus, the link has been added to the success message now.

### Manual testing scenarios
1. Go to a product view page
2. Click "Add to Cart"
3. Check if the success message contains a link to the compare list:
![grafik](https://user-images.githubusercontent.com/662059/36836592-1c94e398-1d3a-11e8-9ab6-210948937aae.png)

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [] All new or changed code is covered with unit/integration tests (if applicable)
 - [] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-01 10:24 UTC, ihor-sviziev commented
@avstudnitz Magento can be configured to redirect customer to shopping cart after adding product. In this case adding link to shopping cart will be not a good idea. What do you think?

2018-03-01 10:26 UTC, avstudnitz commented
@ihor-sviziev You are right, I'll change that.

2018-03-05 10:43 UTC, avstudnitz commented
@ihor-sviziev I added that, the link will now only be added if the customer doesn't get redirected to cart.

2018-03-06 07:30 UTC, ihor-sviziev requested changes
In general - looks good, only one small issue still there.

Could you cover your changes with tests?

2018-03-06 07:30 UTC, ihor-sviziev commented on app/code/Magento/Checkout/Controller/Cart.php
> +    protected function shouldRedirectToCart()
New protected properties/methods are not allowed. Could you change visibility to private? I see it also used in Cart/Add.php controller, so please add it there too

2018-03-10 13:50 UTC, avstudnitz commented
@ihor-sviziev I added two integration tests, one for enabled redirect to cart, one for disabled redirect to cart.

2018-03-10 15:01 UTC, ihor-sviziev commented
Hi @avstudnitz, 
Please fix your code or just ignore these failures in changed code. In general - looks good!

2018-03-10 17:04 UTC, avstudnitz commented
@ihor-sviziev Fixed.

2018-03-10 17:33 UTC, ihor-sviziev approved these changes

2018-03-10 17:35 UTC, ihor-sviziev commented
Hi @avstudnitz ,
I approved your changes, they will be merged soon.
Could you please create PR to `2.3-develop` branch with the same changes?

2018-03-10 17:35 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-840](https://jira.corp.magento.com/browse/ENGCOM-840) has been created to process this Pull Request

2018-03-12 14:50 UTC, avstudnitz commented
@ihor-sviziev I created a pull request to 2.3-develop at https://github.com/magento/magento2/pull/14059. I cherry-picked my commit - would there have been a better method?

2018-03-12 15:05 UTC, ihor-sviziev commented
@avstudnitz it is good option

2018-05-12 07:37 UTC, merged

2018-05-12 07:38 UTC, magento-engcom-team commented
Hi @avstudnitz. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.