Fix issue when cache is the same for each admin user role but restrictions to attributes can be different
magento/magento2 pull request #14099
Opened 2018-03-14 13:29 UTC by nuzil

### Important

Preconditions described in this PR are described for Magento EE Edition, but problem come from Magento CE implementation of caching system, so PR is made for CE version

### Preconditions

magento 2.2.2 - Enterprise
2 websites (test1 and test2)
2 admin user roles: 1 admin user role with access to only website test1 (user-role-1) and second with access to website test2 (user-role-2)

Enabled "eav" cache type

Login to admin panel via user-role-1 account and go to Magento->Customers->All Customers and check options in Filter dropdown "Website". 

Login in second browser  to admin panel via user-role-2 account and go to Magento->Customers->All Customers and check options in Filter dropdown "Website". 

### Expected
user-role-1 will see in website dropdown only option "test1".
user-role-2 will see in website dropdown only option "test2".

Result: user-role-2 will see the same website options as user-role-1.

### Solution
Issue caused by cache key generated in Magento\Customer\Model\Metadata\AttributeMetadataCache. Cache key and cache the same for all user roles but must be different because of different user role rights. So for fix this we need  save and load cache by user role id also. Fix check current role id and add role_id value t cache key suffix. Now we have different cache key and cache for each admin role.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-14 13:29 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14099) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14099) before we can accept your contribution.<br/>

2018-03-15 22:32 UTC, miguelbalparda commented
@nuzil thanks for the PR! @dmanners not sure if this is the right place for an EE issue?

2018-03-16 09:11 UTC, nuzil commented
Hi @miguelbalparda , @dmanners also though about this question. Discussed with @vrann and in case if fix make sense and correct, guess its right location

2018-03-16 09:11 UTC, nuzil commented
Also as note: I see Codacy test is failed, but it failed because of default core variable, not something that were touched by us

2018-03-16 12:48 UTC, vrann commented
@miguelbalparda the issue is reproduced in EE only, however the root cause is in CE codebase.

2018-04-03 16:01 UTC, miguelbalparda approved these changes

2018-04-03 16:04 UTC, magento-engcom-team commented
Hi @miguelbalparda, thank you for the review.
[ENGCOM-1227](https://jira.corp.magento.com/browse/ENGCOM-1227) has been created to process this Pull Request

2018-05-23 15:59 UTC, nuzil commented
@miguelbalparda sorry for disturbing. Any update here?

2018-11-19 13:09 UTC, sivaschenko commented
Hi @nuzil , there is a performance degradation introduces by these changes in the following areas:

    Login (Catalog Browsing By Customer): 34.8% (mainline = 66 | team = 89) -> DEGRADATION
    Login (Catalog Browsing By Customer): 20.6% (mainline = 201336 | team = 242877) -> DEGRADATION
    Create quote (API Checkout): 100% (mainline = 0 | team = 2) -> DEGRADATION
    Login (Catalog Browsing By Customer): 43.2% (mainline = 1968 | team = 2819) -> DEGRADATION
    Create customer (API Create Customer): 12.9% (mainline = 801 | team = 904) -> DEGRADATION
    Create quote (API Checkout): 156.1% (mainline = 1098 | team = 2812) -> DEGRADATION
    Login (Catalog Browsing By Customer): 37.5% (mainline = 56 | team = 77) -> DEGRADATION
    Create customer (API Create Customer): 12% (mainline = 50 | team = 56) -> DEGRADATION
    Create quote (API Checkout): 13.3% (mainline = 15 | team = 17) -> DEGRADATION

I propose to perform call to backend session only in backend area and/or move the implementation to a higher level to ensure no performance degradation is introduced on fronted side

2018-12-04 02:27 UTC, sidolov commented
Hi @nuzil , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-12-04 10:49 UTC, nuzil commented
Hi @sidolov thanks for message. Unfortunately I didnt get notifications about comments :-(
I reopen this PR and we will apply changes

2019-02-11 13:56 UTC, sivaschenko commented
Hi @nuzil have you completed the optimization?

I have relaunched the performance tests on the latest revision and they still indicate a major performance decrease:


    Login (Catalog Browsing By Customer): 32.8% (mainline = 67 | team = 89) -> DEGRADATION
    Login (Catalog Browsing By Customer): 20.6% (mainline = 201853 | team = 243394) -> DEGRADATION
    Create quote (API Checkout): 100% (mainline = 0 | team = 2) -> DEGRADATION
    Login (Catalog Browsing By Customer): 43.2% (mainline = 1972 | team = 2823) -> DEGRADATION
    Create customer (API Create Customer): 12.3% (mainline = 811 | team = 911) -> DEGRADATION
    Create quote (API Checkout): 155.4% (mainline = 1103 | team = 2817) -> DEGRADATION
    Login (Catalog Browsing By Customer): 37.5% (mainline = 56 | team = 77) -> DEGRADATION
    Create customer (API Create Customer): 12% (mainline = 50 | team = 56) -> DEGRADATION
    Create quote (API Checkout): 13.3% (mainline = 15 | team = 17) -> DEGRADATION

2019-03-05 11:01 UTC, sivaschenko requested changes
Hi @nuzil please see my review notes.

As for performance implications, I understand that adding more cache variations may have some negative performance impact, however, lets try to minimize it.

2019-03-05 11:01 UTC, sivaschenko commented on app/code/Magento/Customer/etc/adminhtml/di.xml
> +    <type name="Magento\Customer\Model\Metadata\AttributeMetadataCache">
What is the reason for creating a plugin customizing functionality within the same module?  I think the cache key can be modified directly in `Magento\Customer\Model\Plugin\AttributeMetadataCacheByAdminRole` to keep the code less complicated

2019-03-05 11:01 UTC, sivaschenko commented on app/code/Magento/Customer/Model/Plugin/AttributeMetadataCacheByAdminRole.php
> +     * @param \Magento\Backend\Model\Auth\Session $session
It will be better to depend on `Magento\Backend\Model\Auth\StorageInterface` than on concrete implementation

2019-03-05 11:01 UTC, sivaschenko commented on app/code/Magento/Customer/Model/Plugin/AttributeMetadataCacheByAdminRole.php
> +            $suffix = $suffix . '_ROLEID_' . $roleId;
It would be better to move the suffix construction to a separate private function and cache the result

2019-04-05 14:58 UTC, orlangur commented
@vrann,

> the issue is reproduced in EE only, however the root cause is in CE codebase.

I believe in such case issue is still non-verifiable for Community members and needs to be delivered in other way (partner program or something).

Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

@nuzil, I believe you will finish it one day :)

2019-04-05 14:58 UTC, closed without merging