MAGETWO-84414 indexer DefaultStock
magento/magento2 pull request #14139
Opened 2018-03-16 14:04 UTC by m-milewski

### Description
Deleting old records before each update index table.

### Fixed Issues (if relevant)
1. magento/magento2#84414: Stock inventory reindex bug

### Manual testing scenarios
1. Mass update over 1000 products.

2018-03-16 14:04 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14139) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14139) before we can accept your contribution.<br/>

2018-04-02 15:12 UTC, rogyar commented
Hello @m-milewski. Please, consider fixing the failing integration tests. Thank you

2018-04-27 06:01 UTC, m-milewski commented
@rogyar I fixed fails in integration tests

2018-05-02 16:37 UTC, rogyar requested changes

2018-05-02 16:37 UTC, rogyar commented on app/code/Magento/CatalogInventory/Model/ResourceModel/Indexer/Stock/DefaultStock.php
> +        if (is_array($data) && !empty($data)) {
If we are considering fix for the following issue https://github.com/magento/magento2/issues/12205, it's already fixed withing a scope of 2.2-develop. It should be enough to remove all records at the very beginning of the index update operation without performing a separate delete in a loop. 

Please, check the latest commit here https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/CatalogInventory/Model/ResourceModel/Indexer/Stock/DefaultStock.php for the clarification.

Thank you

2018-06-18 14:49 UTC, sidolov commented
@m-milewski , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration!

2018-06-18 14:49 UTC, closed without merging