Add website- and storeview-code in stores admin grid
magento/magento2 pull request #14156
Opened 2018-03-17 10:38 UTC by aschrammel

This PR adds the webiste- and storeview-code in the stores admin grid like in Magento 1 stores overview.

### Description
The PR joins additionally the `code` field from the `store` table to the admin grids row and adds the website code as well as the store view code in the respective renderers.

### Fixed Issues (if relevant)
-

### Manual testing scenarios
1. Go to "Stores" > "Settings / All Stores"
2. Before applying the PR there are only listed Website, Store and StoreView by their names
3. After applying the PR there are the respective codes shown beneath the Website and StoreView names

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-17 13:01 UTC, mzeis commented
Hi @aschrammel,

thank you very much for your contribution! Would you consider adding the store name, too?

2018-03-17 13:16 UTC, aschrammel commented
Hi @mzeis,

thanks for your feedback. 
I think you mean the store code, as the name is already shown - am i right?

2018-03-17 13:18 UTC, mzeis commented
@aschrammel Exactly :)

2018-03-17 13:23 UTC, aschrammel commented
@mzeis Done :)

2018-03-18 09:39 UTC, mzeis commented
@magento-engcom-team give me new test instance

2018-03-18 09:41 UTC, magento-engcom-team commented
Hi @mzeis, here is your [new test Magento instance](http://pr-14156.engcom.dev.magento.com)

2018-03-18 10:12 UTC, mzeis requested changes

2018-03-18 10:12 UTC, mzeis commented on app/code/Magento/Backend/Block/System/Store/Grid/Render/Group.php
> +        . '(Code: ' . $row->getGroupCode() . ')';
@aschrammel Please can you make "Code" translatable in all 3 places (like "Edit Store" here: [Group.php](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Backend/Block/System/Store/Grid/Render/Group.php#L23-L25) and [en_US.csv](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Backend/i18n/en_US.csv)?

Then we should be good to go. Thanks!

2018-03-19 07:00 UTC, aschrammel commented
@mzeis Code is translatable now 🌐

2018-03-19 17:42 UTC, mzeis commented
@magento-engcom-team give me new test instance

2018-03-19 17:43 UTC, magento-engcom-team commented
Hi @mzeis, here is your [new test Magento instance](http://pr-14156.engcom.dev.magento.com)

2018-03-19 17:49 UTC, mzeis approved these changes

2018-03-19 17:50 UTC, mzeis commented
@aschrammel Thanks for you improvements, looking good! 👍 I'm handing over to QA & merging.

2018-03-19 17:51 UTC, magento-engcom-team commented
Hi @mzeis, thank you for the review.
[ENGCOM-968](https://jira.corp.magento.com/browse/ENGCOM-968) has been created to process this Pull Request

2018-03-20 18:02 UTC, aschrammel commented
@magento-engcom-team thanks for acceptance 😄
In #14157 is the respective forward port to 2.3 if wanted.

2018-03-20 21:44 UTC, mzeis commented
Thanks! I'll process it once the merge for this one is completed :)

2018-03-23 03:27 UTC, merged

2018-03-23 08:01 UTC, mzeis commented
Hi @aschrammel, thanks again for your PR! It has been merged into `2.2-develop`. We now can proceed with #14157.