Update date.js
magento/magento2 pull request #14200
Opened 2018-03-20 12:01 UTC by ArtiDjeims

### Description
Date format doesn't make sense (AM/PM).

### Fixed Issues 
Before: 23:20:21 PM
After: 23:20:21

2018-03-20 12:01 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14200) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14200) before we can accept your contribution.<br/>

2018-03-21 07:59 UTC, sidolov commented
Hi @ArtiDjeims , please, sign CLA, otherwise, I can't process you pull request, thank you!

2018-03-21 08:01 UTC, magento-engcom-team commented
@ArtiDjeims thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-03-21 09:37 UTC, ArtiDjeims commented
Done 💯

2018-03-21 13:20 UTC, VladimirZaets approved these changes

2018-03-21 14:25 UTC, VladimirZaets requested changes

2018-03-21 14:25 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/grid/columns/date.js
> +            dateFormat: 'MMM d, YYYY h:mm:ss'
@ArtiDjeims In the current case, we use h:mm:ss format, in this the case 'h' means that we use 12h time format, so we should use A to show PM/AM abbreviation. 
You can look documentation of monent.js library that we use for work with a date and time.
https://momentjs.com/docs/#the-rfc-2822-date-time-format

2018-03-22 12:29 UTC, closed without merging