Avoid page image jumps in fotorama gallery
magento/magento2 pull request #14282
Opened 2018-03-23 08:38 UTC by DaniloEmpire

On mobile devises: when you scroll down on the product page and you are about half way of the product image the page jumps up to the top. Movement should be fluid always.  (copied from issue #10518)

### Description
This pull request makes movement fluid on mobile devices.

### Fixed Issues
1. magento/magento2#10518: Mobile product page image jumps

### Manual testing scenarios (copied from issue #10518)
1. Open a product page
2. Scroll down to approximately 50% of the image height and the page jumps back to the top. Issue also occurs when scrolling up
3. Bug is intermittent and glitchy and can take a few atrempts to reproduce. Mainly occurs when you use a flick style scroll past the 50% mark.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-23 09:36 UTC, ihor-sviziev commented
Hi @DaniloEmpire I tested your changes, unfortunately I still have issue that you've described. Also as for me it looks like your changes are not related to it. Could you re-check it?

2018-03-23 09:44 UTC, DaniloEmpire commented
Hi @ihor-sviziev ,
sure, I'll check it asap.

2018-03-23 13:11 UTC, FreekVandeursen commented
Hey @DaniloEmpire , we have just tried your changes, and it seems to have worked for us. We haven't seen the problem occur anymore since applying this change.
Thanks a lot!

2018-03-23 17:37 UTC, DaniloEmpire commented
Hi @ihor-sviziev ,
Please check again. It seems to work.
Thank you.

2018-03-23 22:37 UTC, ihor-sviziev commented
@DaniloEmpire I recorded video where I'm reproducing this issue. It is reproducing much harder, but issue is still there

https://photos.app.goo.gl/HLsPKgnmDR1UHUVK2

2018-03-28 13:48 UTC, DaniloEmpire commented
Hi @ihor-sviziev ,
can you re-try?

2018-03-29 16:09 UTC, ihor-sviziev commented
@magento-engcom-team give me new test instance

2018-03-29 16:11 UTC, magento-engcom-team commented
Hi @ihor-sviziev, here is your [new test Magento instance](http://pr-14282.engcom.dev.magento.com)

2018-03-30 03:24 UTC, ihor-sviziev requested changes
Hi,
One think looks not good enough. Will test this solution and will give you feedback

2018-03-30 03:24 UTC, ihor-sviziev commented on app/code/Magento/Catalog/view/frontend/templates/product/view/gallery.phtml
> +<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder" style="min-height: <?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium',
This value should be escaped

2018-03-30 10:47 UTC, ihor-sviziev commented
Hi @DaniloEmpire,
I tested it again, still have this issue on my Android device, I have the same steps to reproduce and the same reproducing rate as previous time.

I think main issue - chrome's top navigation that hides once you're scrolling down the page. What if we will check only device width?

You can try to reproduce it here: http://pr-14282.engcom.dev.magento.com/test.html

2018-04-20 08:46 UTC, ihor-sviziev commented
Hi @DaniloEmpire , are you interested in finalizing your PR?

2018-06-02 08:33 UTC, sidolov commented
@DaniloEmpire , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration!

2018-06-02 08:33 UTC, closed without merging

2019-06-12 13:10 UTC, amjadm61 commented
@magento give me test instance

2019-06-12 13:11 UTC, magento-engcom-team commented
Hi @amjadm61. Thank you for your request. I'm working on Magento instance for you