Issue-5077: Store View (language) switch leads to 404
magento/magento2 pull request #14326
Opened 2018-03-24 14:11 UTC by tolyantrain

### Fixed Issues (if relevant)
1. magento/magento2#5077: Store View (language) switch leads to 404

## Steps to reproduce
1. Install Magento 2.0.7
2. Add several store views e.g. "English", "French", "German"
3. Create a CMS page for "English" store view - e.g. "About Us" with Url Key `about-s`
4. Now create the same CMS page for "French" store view e.g. "À propos de nous" with Url Key `a-propos-de-nous`
## Expected result
1. I can open "About Us" page
2. I am redirected to homepage when I switch store view (language) as CMS pages are not linked n any way
## Actual result
1. I can open "About Us" page
2. 404 page is show when I switch store view (language)

Product categories are general with possibility to translate them in each store view but CMS pages does not work like that. For CMS pages I would expect that user is redirected to homepage as Magento2 can't know which pages represent the same content in different store view.

One way to resolve this would be to use the same Url Key in all store views for the same page but that's a hack rather then a solution (also SEO suffers).

Is there at least a way how to fix this for now?

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-24 14:11 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14326) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14326) before we can accept your contribution.<br/>

2018-03-24 14:28 UTC, o-iegorov requested changes

2018-03-24 14:28 UTC, o-iegorov commented on app/code/Magento/Cms/Controller/Router.php
> +                $this->_response->setRedirect('/');
Bad practice to hardcode home Url, better way to use \Magento\Store\Model\Store::getHomeUrl() method

2018-04-14 07:52 UTC, sidolov commented
@tolyantrain , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2018-04-14 07:52 UTC, closed without merging

2021-07-28 07:57 UTC, mnowakCode commented
I have the same problem, is there anyone who can help us?