Fixed anchor categories showing products of disabled subcategories #9002
magento/magento2 pull request #14320
Opened 2018-03-24 13:32 UTC by drashmk

### Description
Incomplete query for the temporary table `temp_catalog_category_tree_index_xxxx` was causing products  of disabled subcategories to be visible on anchor categories. It was missing the check for `is_active` category attribute on the child category when creating the temporary category. 

### Fixed Issues (if relevant)

#9002: Anchor categories are showing products of disabled subcategories

### Manual testing scenarios
1. Create a simple product 'Test' that is in stock and visible on catalog
2. Create a category A (don't add products to it) 
3. Create a subcategory B (parent is A) and add our 'Test' product to it
4. Goto category A on frontend
5. 'Test' product  is not visible in category A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-26 05:43 UTC, sidolov requested changes
Please, cover provided changes at least by unit test

2018-03-26 05:43 UTC, sidolov commented on app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php
> +    protected function makeTempCategoryTreeIndex(\Magento\Store\Model\Store $store)
We can't add/remove any parameters to public and protected method, please, use guide for [backward compatible developpmenet](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/)

2018-03-26 05:43 UTC, sidolov commented on app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php
> +    protected function fillTempCategoryTreeIndex($temporaryName, \Magento\Store\Model\Store $store)
See previous comment

2018-04-10 14:13 UTC, sidolov commented
@drashmk , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2018-04-10 14:13 UTC, closed without merging

2018-04-10 14:15 UTC, magento-engcom-team commented
Hi @drashmk. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.