Fixing wrong sitemap product url #4788
magento/magento2 pull request #14338
Opened 2018-03-24 15:28 UTC by DenisSaltanahmedov

### Description
Fixed issue #4788
https://github.com/magento/magento2/issues/4788

### Fixed Issues (if relevant)
Fixed wrong sitemap product URL

### Manual testing scenarios
1. "Use Categories Path for Product URLs" set to NO in configuration -> catalog -> catalog -> Search  Engine Optimization
2. Create Categories with products
3. Generate sitemap

2018-03-24 15:28 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14338) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14338) before we can accept your contribution.<br/>

2018-03-26 05:28 UTC, sidolov requested changes

2018-03-26 05:28 UTC, sidolov commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +    protected $scopeConfig;
It's would be better use private property here

2018-03-26 05:28 UTC, sidolov commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +        ConfigInterface $scopeConfig,
Please, inject new dependencies according to our [backward compatibility policy](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/)

2018-03-26 05:28 UTC, sidolov commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +    protected function getCategoryProductURLsConfig($storeId)
This method is not a part of api, so, make it private, please

2018-03-26 05:29 UTC, magento-engcom-team commented
@DenisSaltanahmedov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-04-04 09:54 UTC, sidolov requested changes

2018-04-04 09:54 UTC, sidolov commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
Please, inject new dependencies according to our [Backward compatible development policy](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter)

2018-04-04 09:56 UTC, sidolov commented
Hi @DenisSaltanahmedov , please, fix issues from the review and take a look to failed static test

2018-04-14 12:51 UTC, sidolov approved these changes

2018-04-14 12:53 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-1073](https://jira.corp.magento.com/browse/ENGCOM-1073) has been created to process this Pull Request

2018-04-17 10:46 UTC, merged

2018-04-17 10:47 UTC, magento-engcom-team commented
Hi @DenisSaltanahmedov. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.