Add support to associative arrays as output at REST API
magento/magento2 pull request #14340
Opened 2018-03-24 15:36 UTC by mespinosaz

At REST API the associative arrays are not supported.

### Description
In class ServiceOutputProcessor I am using the index of the arrays to build the output, before they were ignored.

### Fixed Issues (if relevant)

- The index of associative arrays were ignored. Now they are being ussed

1. magento/magento2#5659: REST API Associative Array Not Supporting

### Manual testing scenarios
Tried the following output with the resulting json responses:

| Output array | JSON Response |
|--------------|-----------------|
|['X' => 1, 'Y' => 3] | {"X":1,"Y":3}|
|['X','Y']|["X","Y"]|
|['X' => 1, 'Y' => 3, 'J' => ['K' => 4]]|{"X":1,"Y":3,"J":{"K":4}}|
|['X' => 1, 'Y' => 3, 'J' => ['K' => 4, 'H' => [1,3,4]]]|{"X":1,"Y":3,"J":{"K":4,"H":[1,3,4]}}|
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-24 15:36 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14340) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14340) before we can accept your contribution.<br/>

2018-03-26 18:35 UTC, larsroettig requested changes
Hi @mespinosaz can you add please a **unit test case** for it to improve the quality. 
If you need help you can ask me in the Magento Slack Channel.

Best regards,

 Lars

2018-03-27 11:15 UTC, mespinosaz commented
@larsroettig I would love to but I was unassigned and cannot push anymore

2018-03-27 12:00 UTC, sidolov commented
Hi @mespinosaz , we can accept PR only from your own fork. Please, fork Magento repository and create new PR

2018-03-27 12:00 UTC, closed without merging

2018-03-27 13:35 UTC, mespinosaz commented
sure #14392