Add ability to set custom product option with negative price
magento/magento2 pull request #14342
Opened 2018-03-24 16:04 UTC by mszydlo

### Description
Enabled ability to set negative prices for custom product options.

### Fixed Issues
1. magento/magento2#7333: Unable to set negative custom option fixed price in admin view

### Manual testing scenarios

1. Create product.
2. Add custom option and set negative value.
3. Save product. For fixed price absolute value of option's price cannot exceed product's special/regular price and if it does - 'Invalid option value' message is shown. For percentage the value of 100 cannot be exceeded.
4. If negative value is in proper range product saves correctly and option is displayed in storefront with proper + or - sign

2018-03-24 16:07 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14342) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14342) before we can accept your contribution.<br/><hr/>**Maksymilian Szydło** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-03-24 20:57 UTC, ihor-sviziev commented
Related PR: https://github.com/magento/magento2/pull/13393

2018-03-27 05:52 UTC, ihor-sviziev requested changes
I reviewed your changes, looks good, but in some parts it's not clear. Also unit tests are failing currently. Could you adjust them to be consistent with your changes + cover new cases?

2018-03-27 05:52 UTC, ihor-sviziev commented on app/code/Magento/Catalog/view/base/web/js/price-options.js
> +        '<% if (data.finalPrice.value > 0) { %>' +
I didn't get, why do we need this change?

2018-03-27 05:52 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Product/Option/Validator/Select.php
> +                $price += 100.0;
Could you describe why do we need to add +100 there?

2018-03-27 05:52 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper.php
> +            $customOption->setProduct($product);
Why do we need this change?

2018-03-27 05:52 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Product/Option/Validator/DefaultValidator.php
> +        if ($option->getPriceType() === ProductPriceOptionsInterface::VALUE_PERCENT) {
Could you cover these changes with tests?

2018-06-27 10:04 UTC, dmanners commented
Hi @mszydlo thank you for this PR. I am currently doing a couple of things.

1. Checking with the core team about the history of not allowing negative prices to make sure we do not miss something,
1. Working out the differences between this PR and https://github.com/magento/magento2/pull/15267 and https://github.com/magento/magento2/pull/13393 to see as to which one is the preferred fix.

I will update you via this PR once I have some more information. Thank you for your patience.

2018-07-11 12:30 UTC, dmanners commented
Hi @mszydlo thank you for your pull request. I am closing this pull request as it has been covered by https://github.com/magento/magento2/pull/15267.

2018-07-11 12:30 UTC, closed without merging