Add getShippingAddress and setShippingAddress functions to Order interface
magento/magento2 pull request #14375
Opened 2018-03-26 15:16 UTC by VincentMarmiesse

Hello,

### Description
I just noticed functions `getShippingAddress()` and `setShippingAddress()` are missing from the Order interface (class `Magento\Sales\Api\Data\OrderInterface`).

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-26 19:12 UTC, larsroettig commented
Hi @VincentMarmiesse,
thank you for contribution looks for me well. But we must change the target branch to 2.3-develop (Backward-Compatible) see guideline: 

http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#introduction-of-a-method-to-a-class-or-interface


Best regards,

Lars

2018-03-26 19:16 UTC, larsroettig requested changes
Hi @VincentMarmiesse,
thank you for contribution looks for me well. But we must change the target branch to 2.3-develop (Backward-Compatible) see guideline: 

http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#introduction-of-a-method-to-a-class-or-interface


Best regards,

Lars

2018-03-27 07:14 UTC, sidolov commented
Hi @VincentMarmiesse , described methods were removed from OrderInterface in order to implement multi-shipping functionality. 

Currently, if you need access to order shipping address you may get it from Order extension attributes (attribute name: `shipping_assignments`). 

Attribute implements interface `\Magento\Sales\Api\Data\ShippingAssignmentInterface` and will be populated after order load `\Magento\Sales\Model\OrderRepository::get`

2018-03-27 07:14 UTC, closed without merging

2018-03-27 09:40 UTC, VincentMarmiesse commented
Hi @sidolov,

Ok thanks for the explanation, I didn't think about multi-shipping!