Don't throw shipping method exception when creating quote with only virtual products in API
magento/magento2 pull request #14384
Opened 2018-03-27 08:33 UTC by Maikel-Koek

### Description
When creating a quote (and order) via the API with only virtual products, the following error is thrown:

> Carrier with such method not found: <carrier_code>, <method_code>

Because there are no shipping rates available, since they're not necessary.

### Fixed Issues (if relevant)
When creating a quote with only virtual products (`$quote->getIsVirtual() === true`), it skips the check for available shipping method when saving address information.

### Manual testing scenarios
Follow the steps listed here:
http://devdocs.magento.com/guides/v2.2/get-started/order-tutorial/order-intro.html
Only add the `Magento/Catalog/_files/product_virtual_in_stock.php` fixture product to the quote, and save the address information (http://devdocs.magento.com/guides/v2.2/get-started/order-tutorial/order-prepare-checkout.html#set-addresses)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-27 08:33 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14384) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14384) before we can accept your contribution.<br/>

2018-03-27 09:10 UTC, orlangur requested changes
> Only add the `Magento/Catalog/_files/product_virtual_in_stock.php` fixture product to the quote, and save the address information

Great, we are almost there :) Now just add this finding as an integration test. You an even do it in a TDD way: make first commit containing only such test so that we see it broken on Travis CI and next commit will make test passed.

2018-03-27 09:10 UTC, orlangur commented on app/code/Magento/Checkout/Model/ShippingInformationManagement.php
> +        if (!$shippingAddress->getShippingRateByCode($shippingAddress->getShippingMethod()) && !$quote->getIsVirtual()) {
I believe it would be more logical to swap condition (so that we do not even look for shipping rates in case of virtual quote).

2018-03-27 09:55 UTC, Maikel-Koek commented
@orlangur See the integration test I've just added! This test throws an exception when the check for the virtual quote isn't there.

2018-03-27 10:56 UTC, Maikel-Koek commented
I'm not sure how to solve the Codacy issue, the same is done in all other test files, for example:

https://github.com/magento/magento2/blob/2.2-develop/dev/tests/integration/testsuite/Magento/Checkout/Model/SessionTest.php

2018-05-02 15:00 UTC, Maikel-Koek commented
@orlangur Any idea how to prevent the Codacy error? See my previous comment.

2018-06-13 23:42 UTC, orlangur requested changes
There is no need to fix this Codacy warning.

Such test for API should be `api-functional`, not `integration`.

Also, any changes should be delivered into `2.2-develop` branch first.

2018-06-26 08:30 UTC, orlangur commented
Ping @Maikel-Koek :)

2018-07-10 23:37 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

2018-07-12 09:14 UTC, rogersv commented
The issue exists also in magento 2.2.4. 
It is not possible to finalize a quote using the API if all the products are virtual products.

2018-07-12 09:16 UTC, Maikel-Koek commented
Sorry, haven't found the time yet to create a new pull request to the correct branch and change the integration test.

2019-05-06 13:26 UTC, Maikel-Koek commented
@orlangur Reopening this PR, I just committed a change to fix the integration test, and being on the `2.3-develop` branch isn't a problem anymore now I suppose!

2019-05-20 12:21 UTC, Maikel-Koek commented
@magento-engcom-team give me 2.3-develop instance

2019-05-20 12:21 UTC, magento-engcom-team commented
Hi @Maikel-Koek. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-05-20 12:22 UTC, magento-engcom-team commented
Hi @Maikel-Koek, here is your [Magento instance](https://i-14384-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14384-2-3-develop.instances.magento-community.engineering/admin](https://i-14384-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-05-20 12:26 UTC, Maikel-Koek commented
@sidolov @orlangur 
Since this is moved to 'changes requested', what still needs changing?

I see the Travis continuous integration failing with the following error, but I'm not sure what to do about that one:
```
Fatal error: Uncaught PHPUnit\Framework\Exception: Warning: exec(): Unable to fork [tasklist.exe /fi 'PID eq 8640' /fo CSV /nh 2>&1] in /home/travis/build/magento/magento2/lib/internal/Magento/Framework/Shell.php:58.
```

2019-05-20 14:53 UTC, sidolov approved these changes

2019-05-20 14:54 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5138](https://jira.corp.magento.com/browse/ENGCOM-5138) has been created to process this Pull Request

2019-05-20 14:54 UTC, magento-engcom-team commented
@Maikel-Koek thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-05-21 13:12 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-21 13:54 UTC, Nazar65 commented
HI @Maikel-Koek thank you for collaboration, can you please sign  with CLA ?

2019-05-21 13:58 UTC, Maikel-Koek commented
@Nazar65 Done!

2019-05-21 14:05 UTC, Nazar65 commented
@Maikel-Koek could you sign  this link ? https://cla.dev.magento.com/magento/magento2?pullRequest=14384

2019-05-21 14:07 UTC, Maikel-Koek commented
@Nazar65 Done again!

2019-05-21 14:09 UTC, Nazar65 commented
@Maikel-Koek  ok thank you.

2019-06-07 03:09 UTC, merged