Fix for Issue #14404
magento/magento2 pull request #14405
Opened 2018-03-27 21:44 UTC by lillockey

Added video to configuration to compensate for changes in Fotorama.  Please note that I've only added 'video' and not replaced 'videoUrl'.  I expect it to be entirely possible that cached versions of Fotorama will still want the old structure and it's relatively inexpensive to simply add the field.

### Description
Added 'video' field for Fotorama video data.  Fotorama is not checking for videoUrl

### Fixed Issues (if relevant)
1. magento/magento2#14404: With Fotorama, product gallery videos not pulling in
Currently only has changes for 2.2.  Looks like these changes would apply to 2.1 and 2.3 as well.

### Manual testing scenarios
1. Completely clear cache
2. Attempt to look at a product detail page with a video in the gallery (I was able to reproduce this issue on an unaltered product detail page)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-27 21:44 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14405) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14405) before we can accept your contribution.<br/><hr/>**chris_goehrs** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-03-28 09:33 UTC, orlangur requested changes
There is no need to duplicate data on PHP data, you can just fill both keys `video` and `videoUrl` with the same data prior to Fotorama initialization on JavaScript side.

But, first we need to find out why `videoUrl` was used by Magento in the first place. Was it named this way in older versions of Fotorama?

2018-03-28 17:00 UTC, lillockey commented
@orlangur Forgive me if this is an obvious question.  Are you saying that I should remove the videoURL fields in the 3 php files and, instead, have only the video field?

2018-06-04 00:46 UTC, orlangur commented
@lillockey yeah, there is no sense in passing the same data from PHP side using a different array key.

2018-06-26 08:30 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

2018-06-26 08:30 UTC, closed without merging