Try to fix calculation #10790
magento/magento2 pull request #14468
Opened 2018-03-30 14:04 UTC by ilnytskyi

Removed rounding of $priceInclTax

### Description
Removed rounding for $priceInclTax in app/code/Magento/Tax/Model/Calculation/AbstractAggregateCalculator.php:151 to have correct price and row_total value to apply a discount correctly.
I suppose rounding is applied later.

### Fixed Issues (if relevant)

1. magento/magento2#10790 Tax rate + 100% discount results in negative grand total

### Manual testing scenarios
1. Create product A with price = 2 762,71
2. Create product B with price = 2 542,37
3. Setup tax rule 18%
4. Create coupon code that adds 100% discount.
5. Add both products to the cart with qty = 2
6. Apply coupon code
7. Total Order should be 0

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-30 14:04 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14468) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14468) before we can accept your contribution.<br/>

2018-04-01 09:44 UTC, larsroettig requested changes
Hi @ilnytskyi, 
thank you for your contribution. Currently, we can not accept this pull request, because  the Integration Test is red see: https://travis-ci.org/magento/magento2/jobs/360298715

Also, you have currently the CLA not signed:
https://cla.dev.magento.com/magento/magento2?pullRequest=14468

If you need any help please write me.

Best regards,

Lars

2018-04-01 21:21 UTC, larsroettig approved these changes

2018-04-01 21:24 UTC, magento-engcom-team commented
Hi @larsroettig, thank you for the review.
[ENGCOM-1201](https://jira.corp.magento.com/browse/ENGCOM-1201) has been created to process this Pull Request

2018-04-02 06:47 UTC, sidolov requested changes
Please, cover logic at least by one integration test

2018-04-25 12:12 UTC, ilnytskyi commented
@larsroettig @sidolov could you give me some advice how to create a test properly ?
e.g. `app/code/Magento/SalesRule/Test/Unit/Model/UtilityTest.php` here we have the method `testDeltaRoundignFix`, but it covers only changed function. 
Should we add extra test into there with certain values and check it?

or it would be better to make a separate test with full flow. 
e.g. create a product with a certain price, create tax rule, create quote, put products into quote, collect its totals with applied taxes and discounts ?

2018-08-05 11:26 UTC, sidolov approved these changes

2018-08-05 11:27 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-1201](https://jira.corp.magento.com/browse/ENGCOM-1201) has been created to process this Pull Request

2018-08-10 08:06 UTC, merged

2018-08-10 08:07 UTC, magento-engcom-team commented
Hi @ilnytskyi. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.