magento/magento2#12250: View.xml is inheriting image sizes from paren…
magento/magento2 pull request #14537
Opened 2018-04-04 12:55 UTC by quisse

View.xml is inheriting image sizes from parent (so an optional field is replaced by the value of parent)

- removed read method which replaces array recursively. Now the parent read method gets used and this one only reads the first available theme view.xml (so no combining of all view.xml’s)

### Description

### Fixed Issues (if relevant)

1. magento/magento2#12250: View.xml is inheriting image sizes from parent (so an optional field is replaced by the value of parent)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-05 09:12 UTC, sidolov commented
Hi @quisse , described behavior is expected, nodes in view.xml file will be overwritten by parent theme if they wasn't defined. For your case with `image` tag for overriding `height` field you may define empty height tag, in that case parent `height` will be ignored. Proposed changes are backward incompatible and may affect all existing themes.

2018-04-05 10:46 UTC, quisse commented
Hi @sidolov, ok i understand. Now i've made it possible to add nulllable attributes.

2018-05-16 09:42 UTC, quisse commented
Any update on this, @sidolov?

2018-05-20 08:42 UTC, sidolov requested changes
Hi @quisse , fix looks good for me, but I think it would be better review all properties from view.xsd and make nillable all elements that make sense for override in 3d party extensions

2018-06-19 13:25 UTC, quisse commented
I've refactored for more nillable attributes and to me it looks like that's all. Do you agree? If not can you please suggest others?

2018-07-04 10:03 UTC, quisse commented
@sidolov ?

2018-08-05 10:31 UTC, sidolov approved these changes

2018-08-05 10:32 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-2650](https://jira.corp.magento.com/browse/ENGCOM-2650) has been created to process this Pull Request

2018-08-08 10:51 UTC, merged

2018-08-08 10:52 UTC, magento-engcom-team commented
Hi @quisse. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

2018-08-08 11:11 UTC, quisse commented
Already implemented in 2.3 by magento-architects/MAGETWO-91314-validate-new