Improve code structure in relation to else / if statements.
magento/magento2 pull request #14576
Opened 2018-04-06 10:05 UTC by nuzil

### Description
This PR improves code structure for usage of if / else statements

### Fixed Issues (if relevant)
No, code improvements

### Manual testing scenarios
No, code improvements

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-08 04:52 UTC, orlangur requested changes

2018-04-08 04:52 UTC, orlangur commented on app/code/Magento/AdminNotification/Block/Window.php
>                  $this->_latestItem = $items[0];
Ternary operator would fit better here.

2018-04-08 04:52 UTC, orlangur commented on app/code/Magento/AdvancedPricingImportExport/Model/Export/AdvancedPricing.php
> +        return $this->_groupRepository->getById($groupId)->getCode();
Ternary operator would fit better here.

2018-04-08 04:52 UTC, orlangur commented on app/code/Magento/Analytics/Model/Config/Backend/Enabled.php
> +                $enabled ? $this->subscriptionHandler->processEnabled() : $this->subscriptionHandler->processDisabled();
Ternary operator is NOT really suitable here as it decreases code readability. it is better to be used in assignments only.

2018-04-10 10:11 UTC, merged

2018-04-10 10:13 UTC, magento-engcom-team commented
Hi @nuzil. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.