788: Integration test rework. Shipment controller refactor.
magento/magento2 pull request #14634
Opened 2018-04-11 08:35 UTC by nmalevanec

### Description
Integration test rework and Shipment controller refactor in order to support magento-engcom/msi#788

### Fixed Issues (if relevant)
1. none

### Manual testing scenarios
1. none.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-11 10:59 UTC, maghamed approved these changes

2018-04-11 11:02 UTC, magento-engcom-team commented
Hi @maghamed, thank you for the review.
[ENGCOM-1257](https://jira.corp.magento.com/browse/ENGCOM-1257) has been created to process this Pull Request

2018-04-11 11:05 UTC, maghamed commented
In the scope of Pull Request https://github.com/magento-engcom/msi/pull/788 on MSI project, extension point (`ShipmentProviderInterface`) which provides Shipment Data from Request object has been introduced. This extension point supposed to be substituted in MSI.

The initial behavior of a Single Stock system is preserved.

Also, there was a slight refactoring of existing Integration tests which instantiated Shipment model via ObjectManager but not via ShipmentFactory:
`$objectManager->create(\Magento\Sales\Model\Order\Shipment::` 
and
`$shipment = Bootstrap::getObjectManager()->create(Shipment::class);`

2018-04-12 13:18 UTC, sidolov requested changes

2018-04-12 13:18 UTC, sidolov commented on app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/NewAction.php
> +        \Magento\Shipping\Model\ShipmentProviderInterface $shipmentProvider
Please, inject new dependencies according to [Backward Compatible Development Guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/)

2018-04-12 13:18 UTC, sidolov commented on app/code/Magento/Shipping/Model/ShipmentProvider.php
> +    public function getShipment(): array
Rename method to `getShipmentData` because the current name may confuse developers, `getShipment` in most cases means object instead of the array

2018-04-12 13:18 UTC, sidolov commented on app/code/Magento/Shipping/Model/ShipmentProviderInterface.php
> +    public function getShipment(): array;
Rename method to `getShipmentData` because the current name may confuse developers, `getShipment` in most cases means object instead of the array

2018-04-12 13:18 UTC, sidolov commented on app/code/Magento/Shipping/Model/ShipmentProviderInterface.php
> + * Provide shipment items data from request.
I think it would be better remove the request from comment as a source for shipment data because interface shouldn't contain implementation details.

2018-04-12 13:18 UTC, sidolov commented on app/code/Magento/Shipping/Model/ShipmentProviderInterface.php
> +     * Retrieve shipment items from request.
The same as above

2018-04-12 13:31 UTC, nmalevanec commented on app/code/Magento/Shipping/Model/ShipmentProviderInterface.php
> +     * Retrieve shipment items from request.
Removed

2018-04-12 13:31 UTC, nmalevanec commented on app/code/Magento/Shipping/Model/ShipmentProviderInterface.php
> + * Provide shipment items data from request.
Removed

2018-04-12 13:31 UTC, nmalevanec commented on app/code/Magento/Shipping/Model/ShipmentProviderInterface.php
> +    public function getShipment(): array;
Renamed

2018-04-12 13:31 UTC, nmalevanec commented on app/code/Magento/Shipping/Model/ShipmentProvider.php
> +    public function getShipment(): array
Renamed

2018-04-12 13:31 UTC, nmalevanec commented on app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/NewAction.php
> +        \Magento\Shipping\Model\ShipmentProviderInterface $shipmentProvider
Fixed

2018-04-12 13:54 UTC, sidolov approved these changes

2018-04-13 21:32 UTC, merged

2018-04-13 21:34 UTC, magento-engcom-team commented
Hi @nmalevanec. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.