Enable Magento 2 to connect MySQL through SSL.
magento/magento2 pull request #14660
Opened 2018-04-12 11:18 UTC by bnymn

Enable Magento 2 to connect MySQL through SSL.

### Description
We have made some modification to enable Magento 2 connect MySQL through SSL.

During the installation, there was no option to force MySQL connection through SSL. With this PR, the following options will be enabled for you to use SSL.
```
bin/magento setup:install \
	--db-host=<MYSQL_HOST> \
	--db-name=<MYSQL_DATABASE> \
	--db-user=<MYSQL_USERNAME> \
	--db-password=<MYSQL_PASSWORD> \
	--db-ssl-key=<MYSQL_CLIENT_KEY> \
	--db-ssl-cert=<MYSQL_CLIENT_CERT> \
	--db-ssl-ca=<MYSQL_SERVER_CERT>
```
### Fixed Issues (if relevant)
1. magento/magento2#13561: Magento 2 and SSL connection to MySQL

### Manual testing scenarios
1. Install a MySQL server which accepts connections through SSL.
2. Copy these files into a folder which is accessible by Magento: `client-key.pem`, `client-cert.pem`, `ca.pem`.
3. Install a fresh Magento with the following command-line command:
```
bin/magento setup:install \
	--db-host=<MYSQL_HOST> \
	--db-name=<MYSQL_DATABASE> \
	--db-user=<MYSQL_USERNAME> \
	--db-password=<MYSQL_PASSWORD> \
	--db-ssl-key=<PATH/TO/CLIENT-KEY.pem> \
	--db-ssl-cert=<PATH/TO/CLIENT-CERT.pem> \
	--db-ssl-ca=<PATH/TO/CA.pem>
```

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-12 11:18 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=14660) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14660) before we can accept your contribution.<br/>

2018-04-12 15:10 UTC, sidolov requested changes
Please, add a possibility to specify SSL configuration via UI install

2018-04-12 15:10 UTC, sidolov commented on setup/src/Magento/Setup/Validator/AdminCredentialsValidator.php
> +        $driverOptionKeys = [
Try to avoid copy/paste, extract logic to separate class and use in current place and in setup/src/Magento/Setup/Model/ConfigOptionsList.php

2018-04-12 15:10 UTC, sidolov commented on setup/src/Magento/Setup/Validator/DbValidator.php
> +    public function checkDatabaseConnection($dbName, $dbHost, $dbUser, $dbPass = '', $driverOptions = [])
Such changes are backward incompatible, please, use [Backward Compatible Development Guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/#adding-parameters-in-public-methods) for adding new parameters to public methods.

2018-05-14 06:31 UTC, jee1mr commented
Hi, what's the progress on this? Need help?

2018-05-14 12:50 UTC, bnymn commented
Hi @jee1mr ,

I could not find any suitable time to complete change requests. I am planning to complete them end of this month. Any help will be appreciated of course.

2018-05-20 18:42 UTC, bnymn commented on setup/src/Magento/Setup/Validator/DbValidator.php
> +    public function checkDatabaseConnection($dbName, $dbHost, $dbUser, $dbPass = '', $driverOptions = [])
I added a default value to the `$driverOptions` parameter so that it would be backward compatible.

2018-06-12 18:52 UTC, bnymn commented
Hi @sidolov,

I have completed your change requests. Would you please review again?

2018-07-12 11:07 UTC, VladimirZaets requested changes

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigGenerator.php
> +        DriverOptions $driverOptions,
Due to [Magento backward-compatible development guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't add required params to constructor.

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Controller/DatabaseCheck.php
> +    protected function isDriverOptionsGiven($params)
Due to [Magento backward-compatible development guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't declare protected methods. Please make this method private.

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigOptionsList.php
> +    public function __construct(
Due to [Magento backward-compatible development guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't add required params to constructor.

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigOptionsList.php
> +                'Client certificate for SSL',
Please, clarify the description of the field. Currently its unclear, whether file path, file contents or anything else should be filled in the field.

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigOptionsList.php
> +                'Client key file for SSL',
Please clarify, that this relates to the database and that file path is expected

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigOptionsList.php
> +                'Server sertificate for SSL',
Looks like it's "certificate"

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigOptionsList.php
> +                'Verify server sertification'
Again, this is not a very clear description

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigOptionsList/DriverOptions.php
> +use Magento\Framework\Config\ConfigOptionsListConstants;
Due to [Magento technical guidelines](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html) we should use strict type declaration  (`declare(strict_types=1)`) for all new files.

2018-07-12 11:07 UTC, VladimirZaets commented on setup/src/Magento/Setup/Model/ConfigOptionsList/DriverOptions.php
> +    protected function optionExists($options, $driverOptionKey)
Due to [Magento backward-compatible development guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't declare protected methods. Please make this method private.

2018-07-12 11:09 UTC, magento-engcom-team commented
@bnymn thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-09-16 11:47 UTC, bnymn commented on setup/src/Magento/Setup/Model/ConfigOptionsList.php
> +    public function __construct(
Required parameter is changed to optional

2018-09-16 12:16 UTC, bnymn commented
Hi @VladimirZaets ,

Thank you for you review. I have just fixed those issue you have addressed.

2018-09-16 12:20 UTC, okorshenko commented
Please create new PR to 2.3-develop branch

2018-09-16 12:20 UTC, closed without merging

2019-06-20 08:19 UTC, robert-schmidt commented
Why is this not available in 2.3.1? 

The "--db-ssl-key" option does not exist.

2020-01-07 14:54 UTC, mitcht commented
How did this pull request not get merged into the release?