Add "min"/"max"/"step" attributes to add to cart qty.
magento/magento2 pull request #14708
Opened 2018-04-14 15:47 UTC by likemusic

### Description

Add attributes for qty input box related to min/max/step for input[type=number].

### Fixed Issues (if relevant)

I was not looking for.

### Manual testing scenarios

1. Go to Admin > Catalog > Product and open any product for edit. Click "Advanced Inventory" link under " Quantity" field. In "Advanced Inventory" popup modal windows set values for:
 - Minimum Qty Allowed in Shopping Cart - any number
 - Maximum Qty Allowed in Shopping Cart - any number
 - Enable Qty Increments: "Yes"
 - Qty Increments: any number
 - Click "Done" button in molal and "Save" button to save product config.

2. Go to product frontend page and type some number in Qty input. Press Up/Down button, and check step for increment/decrement value, maximum and minimum values.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
Not tested,  sorry (no time).

2018-04-17 13:52 UTC, miguelbalparda requested changes
Can you check the failing tests and the codacy please?

2018-04-19 13:32 UTC, likemusic commented
Seems that would be better to overwrite getters for StockItem, because values from it also used in $block->getQuantityValidators() (in \Magento\CatalogInventory\Block\Plugin\ProductView::afterGetQuantityValidators()).

Or add new getters to OrderItem that return adjusted by qty increments values (like getAdjustedMinSaleQty()).

2018-04-20 14:12 UTC, miguelbalparda commented
Feel free to pursue that @likemusic in this PR or create a new one.

2018-05-03 13:54 UTC, miguelbalparda commented
Closing this one for lack of feedback, feel free to reopen if anything changes.

2018-05-03 14:40 UTC, likemusic commented
@miguelbalparda I don't understand why not completed/bad pull-requests with fixes for some issues closed without any special labels attached or without creating opened issue attached to them?

Or maybe contributors should create issue before create pull-request?

2018-05-03 18:47 UTC, miguelbalparda commented
We close unmerged PRs to maintain an ordered repository and every issue and PR, open and closed, is searchable through GitHub search bar.
Regarding your question about PRs and issues, you haven't checked for any other occurrence since you wrote

> Fixed Issues (if relevant)
> 
> I was not looking for. 

I tried to follow up with you and you showed up only after I closed this PR. Please don't reopen a PR unless you are actively working on it. Is there anything I can do to help you complete this one or is it safe to close?

2018-05-03 20:19 UTC, likemusic commented
> We close unmerged PRs to maintain an ordered repository.

@miguelbalparda  I still don't understand why bad-pull-request closed without special label or linked opened issue or created new.

In my mind:
 - issue on github = bug report;
 - pull-request = bug report + fix for that bug;

If pull-request is bad that doesn't mean that there is no bug. I mean that bug reported in pull-request in any case should be tested by Q&A, and closed just if it not reproduced. When you close pull-request without routines like for issues, you close/hide bug-reports without any investigating.

> open and closed, is searchable through GitHub search bar.

You are right, but by default it has filter: `is:open`. And there is no way to filter closed pull-requests that contains real bug-report but have bad fix and all other hundreds closed pull-requests.

If I had created before pull request separated issue with bug report, then it would be investigated despite a closed pull-request. Isn't it?

> Fixed Issues (if relevant)
> I was not looking for.

Finding related issues not trivial and may take a long time. I think that bad bug-report is better then hidden bugs in product. Am I wrong? Some other contributors can improve bad issue/pull-request. It can helps me to find issue/pull-request and improve it when I have time for it. And label like 'improvement wanted"  even for closed pull-request will help all.

> Is there anything I can do to help you complete this one or is it safe to close?

Unfortunately I don't have time for work on my opened pull-request right now, therefore it can be closed, if it should.

2018-05-04 11:31 UTC, closed without merging

2018-05-04 11:36 UTC, miguelbalparda commented
The [process](https://github.com/magento/magento2/blob/2.2-develop/.github/CONTRIBUTING.md) is simple and won't be changed for you. If you can't/won't work on a PR, it's going to be closed. If someone finds it useful, it will be reopened or a new PR will be submitted. 
A lot of developers know how to search on GitHub using filters and triage bugs, so most of your opinion seems to be invalid.