Unable to call getAllIds() on \Magento\Eav\Model\ResourceModel\Entity\Attribute\Collection if the AllAttributeSetsFilter is applied
magento/magento2 pull request #15158
Opened 2018-05-11 15:35 UTC by raisaev

### Description

When the filter **AllAttributeSetsFilter** is used for **Attribute\Collection**, then method call **getAllIds()** causes the following mysql syntax error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count' in 'having clause'

### Manual testing scenarios
`
$attributeCollection = \Magento\Framework\App\ObjectManager::getInstance()
            ->get(\Magento\Catalog\Model\ResourceModel\Product\Attribute\CollectionFactory::class)
            ->create();

$attributeSetsCollection = \Magento\Framework\App\ObjectManager::getInstance()
            ->get(\Magento\Eav\Model\ResourceModel\Entity\Attribute\Set\CollectionFactory::class)
            ->create();

$attributeSetsCollection->getSelect()->limit(5);
$attributeSetIds = $attributeSetsCollection->getColumnValues('attribute_set_id');

$attributeCollection->addVisibleFilter();
$attributeCollection->setInAllAttributeSetsFilter($attributeSetIds);

var_dump($attributeCollection->getAllIds());
die;
`
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-11 15:35 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15158) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15158) before we can accept your contribution.<br/><hr/>**4wjal7rhnqt6s** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-05-12 06:28 UTC, rogyar requested changes

2018-05-12 06:28 UTC, rogyar commented on app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Collection.php
> +            $idsSelect->columns(array(
Please, use the short array syntax: [] instead of array()

2018-05-15 07:44 UTC, raisaev commented
Hi @rogyar, thank you. Requested changes have been applied.

2018-07-11 01:12 UTC, orlangur commented
@rogyar please proceed with review if you wish :)

2018-11-19 14:18 UTC, sivaschenko requested changes
Thanks for your contribution, please see the code review notes

2018-11-19 14:18 UTC, sivaschenko commented on lib/internal/Magento/Framework/Model/ResourceModel/Db/Collection/AbstractCollection.php
> +    protected function _getAllIdsSelect()
Please add a phpdoc for this function

2018-11-19 14:18 UTC, sivaschenko commented on app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Collection.php
> +     * {@inheritdoc}
Please remove the curly brackets

2018-11-19 14:18 UTC, sivaschenko commented on app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Collection.php
> +    protected $_setFilterApplied = false;
Please remove the single underscore from property name (https://www.php-fig.org/psr/psr-2/#42-properties) also I propose to rename property to $filterApplied to correspond the value of the property (not reference to an action)

2018-11-19 14:33 UTC, sivaschenko commented
Hi @raisaev , thanks for the contribution. Could you please resolve the code review comments and resolve the conflicts with the mainline branch.

2018-12-04 02:28 UTC, sidolov commented
Hi @raisaev , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-12-04 02:28 UTC, closed without merging