Fix #5730 - added new system option to set default sort by in search …
magento/magento2 pull request #15175
Opened 2018-05-12 13:52 UTC by sRuchlewicz

### Description

This PR adds a new option in `admin -> stores -> configuration -> catalog -> catalog -> catalog search -> Product Listing Sort by` for setting a default sort order for search results page. The `admin -> stores -> configuration -> catalog -> catalog -> Product Listing Sort by` setting should stay a separate option as it makes no sense to change sorting on both pages (category page and search page) with one option.
### Fixed Issues (if relevant)

1. magento/magento2#5730: Changing sort order in admin doesn't work for catalog search

### Manual testing scenarios

1. Login to magento store admin
2. Navigate to Stores->Configuration->Catalog->Catalog->Catalog Search
3. Change Product Listing Sort by to Price
4. Clear Cache
5. Goto magento store frontend and search by keyword
6. Verify that default sorting is the one set in admin

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-12 13:52 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15175) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15175) before we can accept your contribution.<br/>

2018-05-24 10:10 UTC, dmanners commented
Hi @sRuchlewicz thank you for this pull request. Would you be able to look into the unit test failures.

```
Time: 49.67 seconds, Memory: 1164.00MB
There were 4 errors:
1) Magento\CatalogSearch\Test\Unit\Block\ResultTest::testGetSearchQueryText
TypeError: Argument 5 passed to Magento\CatalogSearch\Block\Result::__construct() must be an instance of Magento\Catalog\Model\Config, none given, called in /home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php on line 58
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Block/Result.php:64
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php:58
2) Magento\CatalogSearch\Test\Unit\Block\ResultTest::testGetNoteMessages
TypeError: Argument 5 passed to Magento\CatalogSearch\Block\Result::__construct() must be an instance of Magento\Catalog\Model\Config, none given, called in /home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php on line 58
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Block/Result.php:64
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php:58
3) Magento\CatalogSearch\Test\Unit\Block\ResultTest::testGetNoResultText with data set #0 (true, 'Minimum Search query length is 5')
TypeError: Argument 5 passed to Magento\CatalogSearch\Block\Result::__construct() must be an instance of Magento\Catalog\Model\Config, none given, called in /home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php on line 58
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Block/Result.php:64
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php:58
4) Magento\CatalogSearch\Test\Unit\Block\ResultTest::testGetNoResultText with data set #1 (false, null)
TypeError: Argument 5 passed to Magento\CatalogSearch\Block\Result::__construct() must be an instance of Magento\Catalog\Model\Config, none given, called in /home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php on line 58
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Block/Result.php:64
/home/travis/build/magento/magento2/app/code/Magento/CatalogSearch/Test/Unit/Block/ResultTest.php:58
```

2018-05-24 10:15 UTC, dmanners requested changes
Thank you for this pull request could you please take a look over my comments.

2018-05-24 10:15 UTC, dmanners commented on app/code/Magento/CatalogSearch/Block/Result.php
> +    protected $catalogConfig;
Could you update this to private please.

2018-05-24 10:15 UTC, dmanners commented on app/code/Magento/CatalogSearch/Block/Result.php
> +        Config $catalogConfig,
Can you please inject this as an optional parameter at the end of the `__construct` method. See  https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter

2018-05-24 10:15 UTC, dmanners commented on app/code/Magento/CatalogSearch/Model/Config/Source/ListSort.php
> +    protected $catalogConfig;
Can you update this to be private please.

2018-05-24 10:15 UTC, dmanners commented on app/code/Magento/CatalogSearch/Model/Config/Source/ListSort.php
> +    protected function getCatalogConfig()
Is there any reason for this to be a protected method. I would recommend:

1. Public if it is needed outside this class,
2. Private if only this class needs it,

2018-05-24 10:15 UTC, dmanners commented on app/code/Magento/CatalogSearch/Model/Config/Source/ListSort.php
> +        foreach ($this->getCatalogConfig()->getAttributesUsedForSortBy() as $attribute) {
Is it not possible to call `$this->catalogConfig->getAttributesUsedForSortBy()` instead of `$this->getCatalogConfig()->getAttributesUsedForSortBy()`

2018-06-18 14:52 UTC, sidolov commented
@sRuchlewicz , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration!

2018-06-18 14:52 UTC, closed without merging