Error 500 in Module Manager
magento/magento2 pull request #15211
Opened 2018-05-15 06:59 UTC by flancer64

There is an error in Module Manager (http://store.com/setup/index.php/moduleGrid/modules) if some module has no "moduleName" property:
```
{
  "name": "amzn\/amazon-pay-and-login-magento-2-module",
  "type": "magento2-module",
  "version": "2.0.4"
}
```

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-15 08:08 UTC, rogyar requested changes

2018-05-15 08:08 UTC, rogyar commented on setup/src/Magento/Setup/Model/Grid/Module.php
> +            $item['moduleName'] = isset($item['moduleName']) ? $item['moduleName'] : $this->packageInfo->getModuleName($item['name']);
The line length exceeds 120 characters. According to PSR-2 coding style, a line length must be  <= 120 characters. Also as an improvement, I would recommend using null coalescing operator to simplify the construction (http://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce)

2018-05-15 08:10 UTC, rogyar commented
Hello @flancer64. Thank you for your collaboration. Please, consider fixing issues mentioned in the review. Also, create a PR description using the template you have upon the PR creation which includes Fixed Issues, Steps to Reproduce and other required sections. 
Thank you

2018-05-15 10:24 UTC, flancer64 commented
Hi, guys. Thanks for your responses. Feel free to change this code as you wish. It is just my proposal to fix the bug.

2018-05-21 14:29 UTC, magento-engcom-team commented
@flancer64 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-05-21 16:29 UTC, hostep commented
@flancer64: can you edit your opening post, follow the [template](https://github.com/magento/magento2/blob/2.2-develop/.github/PULL_REQUEST_TEMPLATE.md) and add issue https://github.com/magento/magento2/issues/15192 under the `Fixed Issues (if relevant)` so that issue automatically gets marked as fixed when this PR gets approved.

Thanks for the fix!

2018-05-21 16:46 UTC, flancer64 commented
@hostep , done.

2018-05-21 16:49 UTC, flancer64 commented
@magento-engcom-team , done.

2018-05-25 07:39 UTC, merged

2018-05-25 07:40 UTC, magento-engcom-team commented
Hi @flancer64. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

2018-05-30 13:19 UTC, Donnerberg commented
I am having same problem Screenshoot: http://prntscr.com/jojvx0

But changing module.php line 181 did not solved my problem.

Does any1 have any other idea ?

Many thanks.
Nikola

2018-05-30 14:06 UTC, flancer64 commented
PHP version? `??` is a 7.x feature. Try to get error message from web server error log, not from browser console.

2018-05-30 14:16 UTC, Donnerberg commented
There is nothing in log files: http://prntscr.com/jokvek
( At least nothing when I press Module Manager button )

My PHP version is 7.0. I can upgrade it to version 7.1 if I need.

2018-05-30 14:44 UTC, flancer64 commented
No, not in Magento logs. Try to look up for error message in `/var/log/[apache2|nginx]/your_host_error.log`

2018-05-30 14:53 UTC, Donnerberg commented
Hm,

I'm going to find apache log files.

For now I have found only this: http://prntscr.com/jolgx0

2018-05-30 17:10 UTC, flancer64 commented
Does the file `/usr/home/donner/www_logs/donnerber.net/error.log` exist?

2018-05-31 08:05 UTC, Donnerberg commented
[error.log.20180530.gz](https://github.com/magento/magento2/files/2057299/error.log.20180530.gz)
I found log files at exactly location.

Before I downloaded log files, I have initiated Module Manager a few times.

Is there anything which could tell where is the problem ?

2018-05-31 08:52 UTC, flancer64 commented
Sorry, @Donnerberg , I see nothing in error log. Could you give me an access log? We need to found request with HTTP result code 500.

2018-05-31 11:06 UTC, Donnerberg commented
[access.log.20180530.gz](https://github.com/magento/magento2/files/2057907/access.log.20180530.gz)

Oh, I should send you both. I hope there is something what could help.

Many thanks for helping me with this.

1day older access log file you could find here:
[access.log.20180529.gz](https://github.com/magento/magento2/files/2057918/access.log.20180529.gz)

2018-05-31 11:38 UTC, flancer64 commented
Sorry, @Donnerberg . I see that these error log & access log are from one server but I cannot see the error message in the log. Did you try to go directly to the URL "http://donnerberg.net.dedivirt595.your-server.de/setup/index.php/module-grid" under admin account (authorized)? You should see smth. like

![image](https://user-images.githubusercontent.com/5052385/40780069-e089cfd8-64df-11e8-8473-1f616d7ce74d.png)

If you will not see & will get error 500 try to debug app. Set breakpoint in `./setup/src/Magento/Setup/Controller/ModuleGrid.php` (if you will go down to this class without errors).

2018-05-31 13:01 UTC, Donnerberg commented
Yes you were right: http://prntscr.com/jp0tpm

But I am not sure how to set breakpoint in ./setup/src/Magento/Setup/Controller/ModuleGrid.php  ?

2018-05-31 13:43 UTC, flancer64 commented
I suppose, you can't if you ask me about it. Perhaps, nobody can, if this server is not under your full control. The last thing I can advise to you - try to look into the HTTP response (this is Dev tools in Chrome - Ctrl + Shift + I):
![image](https://user-images.githubusercontent.com/5052385/40785632-b97f2b88-64f1-11e8-9573-db2d27cbc849.png)

2018-05-31 13:52 UTC, Donnerberg commented
Dear Flancer,

I have full access SSH and FTP control of server.

This is error from Network:  http://prntscr.com/jp1vk8

What do you think about that ?

2018-05-31 14:06 UTC, flancer64 commented
@Donnerberg , do you have "root" access?

You need to click on entry with error (red one) then go to tab "Response".

2018-05-31 14:26 UTC, Donnerberg commented
@flancer64 , Yes I have full root access.

Here is screenshoot of response tab: http://prntscr.com/jp2f8u

2018-06-01 10:47 UTC, flancer64 commented
Try to setup [remote debugging](https://xdebug.org/docs/remote) then walk through the code starting from `./setup/index.php`