Fix for issue-6578
magento/magento2 pull request #15304
Opened 2018-05-18 11:19 UTC by bartoszherba

- set min. string length of address.telephone to 0
- set is_required pn address.telephone to 0
- update ut/integration tests

### Description
I simply change requirements for telephone on address model.
- 1-255 -> 0 - 255 chars
- is_required -> not_required

### Fixed Issues
Now in case that for some reasons, like after data migration from M1, telephone field is empty, then password reset will work as expected.

### Manual testing scenarios
1. Register a customer and log in
2. Create an address with empty phone number
3. Log out
4. Go to login view and try to reset your password

As a result you should be able to receive email with further instructions as expected.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-18 11:19 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15304) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15304) before we can accept your contribution.<br/><hr/>**Bartosz Herba** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-05-18 11:37 UTC, orlangur commented
> Now in case that for some reasons, like after data migration from M1, telephone field is empty

Phone field is required in both M1 and M2. If migration produces invalid data, it should be fixed instead of hacking core.

Making phone field not required, on the other hand, seems a huge backward-incompatible change for all assuming it was required.

> the real, underlying exception message is hidden, in our case, it was: "Phone" is a required value. "Phone" length must be equal or greater than 1 characters.. as a fix, full field validation must be ignored during password resets.

Please rework a fix in such a way that changing phone is_required flag is not needed.

2018-05-18 18:21 UTC, bartoszherba commented
@orlangur 
I changed the approach to the issue. Please, evaluate it again.

2018-11-07 04:29 UTC, orlangur requested changes
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

2018-11-19 09:28 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-11-19 09:28 UTC, closed without merging

2019-03-18 10:04 UTC, joinso commented
The issue is still present in 2.3
It happens with any required customer field.
The solution proposed in https://github.com/magento/magento2/pull/15304/commits/e6050641e00b77b96a5fe3de03edbb9644f7dbb5 does not work because the exception fires on this line:
$this->customerResource->save($customer);
when trying to save token.

Regards,
JOINSO