Fixed review list ajax if product not exist redirect to 404 page #13102
magento/magento2 pull request #15369
Opened 2018-05-19 10:44 UTC by Ananth747

### Description
Issue was review list ajax call giving php error log or error number if invalid product id. It should be 404 page.

### Fixed Issues (if relevant)
1. magento/magento2#13102, Page was not redirect to 404 page.

### Manual testing scenarios
1. Use invalid product id in review list ajax
2. For example: `<Magento store url>/review/product/listAjax/id/{{non existent id}/`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-19 10:44 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15369) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15369) before we can accept your contribution.<br/>

2018-07-11 17:22 UTC, larsroettig commented
Hi @Ananth747, can you sign pls our contributor License Agreement.
I start now with review and testing.

best regards,

Lars

2018-07-11 17:40 UTC, larsroettig requested changes

2018-07-11 17:40 UTC, larsroettig commented on app/code/Magento/Review/Controller/Product/ListAjax.php
>          } else {
It unnecessary else statement you remove this. 

```php
 /**
     * Show list of product's reviews
     *
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        if (!$this->initProduct()) {
            /** @var \Magento\Framework\Controller\Result\Forward $resultForward */
            $resultForward = $this->resultFactory->create(ResultFactory::TYPE_FORWARD);
            $resultForward->forward('noroute');
            return $resultForward;
        }

        return $this->resultFactory->create(ResultFactory::TYPE_LAYOUT);
    }
```

2018-07-12 11:47 UTC, larsroettig approved these changes

2018-08-02 17:28 UTC, Ananth747 commented
@larsroettig @magento-cicd2 I've signed CLA when it will be accepted?

2018-08-10 08:11 UTC, sidolov commented
Hi @Ananth747 , looks like your commits were pushed with the different email than on GitHub profile, please, add email from commits to your account and issue with CLA will be fixed.

2018-08-13 17:55 UTC, Ananth747 commented
@magento-cicd2 @sidolov @larsroettig 
I've added the email that was used for commit. Now CLA check is passed.
Sorry for the misunderstanding.

2018-08-14 14:16 UTC, merged

2018-08-14 14:17 UTC, magento-engcom-team commented
Hi @Ananth747. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.