issue fixed #8258 - assign indices for all array inputs so that validation works properly
magento/magento2 pull request #15383
Opened 2018-05-19 13:40 UTC by jayankaghosh

Form validation with identical field names does not work as expected

### Description
Assign indices to array inputs and later remove them before submitting as a workaround for the validation library to work properly.

### Fixed Issues (if relevant)
1. magento/magento2#8258 Form validation with identical field names does not work as expected

### Manual testing scenarios
1. Create a form with identical fields and add JavaScript validation
2. Submit the form with improper values in fields.
3. Validation should work properly now

2018-05-21 04:36 UTC, gautamkrishnar requested changes

2018-05-21 04:36 UTC, gautamkrishnar commented on lib/web/mage/validation.js
Please add function documentation comment.

2018-05-25 13:29 UTC, VladimirZaets commented on lib/web/mage/validation.js
> +        _workaroundForArrayInputs: function () {
Please rename the method to something like "prepareArrayInputs" and add the `@see` annotation to doc block with link to issue (https://github.com/jquery-validation/jquery-validation/pull/717)

2018-05-25 13:31 UTC, VladimirZaets commented on lib/web/mage/validation.js
> +                var originalName = input.attr('name');
Please move all var declaration to the top of the function.

2018-06-18 11:07 UTC, VladimirZaets commented
Hi @jayankaghosh  , thanks for fixes.

2018-06-18 11:51 UTC, gautamkrishnar approved these changes
Awesome

2018-06-20 13:12 UTC, jayankaghosh commented
Oh didn't follow on this for a long time. So this is fixed now? Cool!
P.S I can see the Travis CI failed due to code standard not being proper. So does that need to be reworked on?

2019-01-28 23:01 UTC, VladimirZaets commented
Hi @jayankaghosh. Thanks for collaboration.

After the testing we found the next problem:

This fix doesn't work with checkbox input, for instance with downloadable product.
Manual failing scenario:
1. Create downloadable product with two links and enabled "Links can be purchased separately" checkbox.
2. Navigate to storefront and try to add created product to cart with only one link checked on PDP.

Expected result:
Product added successfully to cart with only one link selected.

Actual result: 
Validation failed with message: "Please select one of the options."

2019-01-29 10:04 UTC, jayankaghosh commented
> Hi @jayankaghosh. Thanks for collaboration.
> 
> After the testing we found the next problem:
> 
> This fix doesn't work with checkbox input, for instance with downloadable product.
> Manual failing scenario:
> 
> 1. Create downloadable product with two links and enabled "Links can be purchased separately" checkbox.
> 2. Navigate to storefront and try to add created product to cart with only one link checked on PDP.
> 
> Expected result:
> Product added successfully to cart with only one link selected.
> 
> Actual result:
> Validation failed with message: "Please select one of the options."

I am working on this

2019-01-29 10:19 UTC, jayankaghosh commented
@magento-engcom-team give me magento2.3 instance

2019-01-29 10:22 UTC, jayankaghosh commented
@magento-engcom-team give me 2.3.0 instance

2019-01-29 10:22 UTC, magento-engcom-team commented
Hi @jayankaghosh. Thank you for your request. I'm working on Magento 2.3.0 instance for you

2019-01-29 10:23 UTC, magento-engcom-team commented
Hi @jayankaghosh, here is your [Magento instance](https://i-15383-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-15383-2-3-0.instances.magento-community.engineering/admin](https://i-15383-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-01-29 10:30 UTC, jayankaghosh commented
@VladimirZaets I couldn't reproduce the issue with the steps mentioned

2019-01-31 16:24 UTC, sdzhepa commented
@magento-engcom-team give me test instance

2019-01-31 16:24 UTC, magento-engcom-team commented
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

2019-01-31 16:24 UTC, magento-engcom-team commented
Hi @sdzhepa, here is your [new Magento instance](https://pr-15383.instances.magento-community.engineering).
Admin access: [https://pr-15383.instances.magento-community.engineering/admin](https://pr-15383.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-31 16:30 UTC, magento-engcom-team commented
Hi @sdzhepa, here is your [Magento instance](https://i-15383-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-15383-2-3-0.instances.magento-community.engineering/admin](https://i-15383-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-01-31 16:31 UTC, sdzhepa commented
@magento-engcom-team give me 2.3-develop instance

2019-01-31 16:31 UTC, magento-engcom-team commented
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-01-31 16:31 UTC, magento-engcom-team commented
Hi @sdzhepa, here is your [Magento instance](https://i-15383-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-15383-2-3-develop.instances.magento-community.engineering/admin](https://i-15383-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-01-31 16:48 UTC, sdzhepa commented
Hello @jayankaghosh 

I have double checked scenario described here https://github.com/magento/magento2/pull/15383#issuecomment-458337123 

And can confirm:
1. scenario works on `2.3-develop` branch now. Product is added to cart with only one link
2. scenarion does not work on branch with this PR.  Product is NOT added to cart with only one link

I also see in https://github.com/magento/magento2/pull/15383#issuecomment-458486719 that you requested 
> give me 2.3.0 instance

And it could be an reason why it is not reproduces.  More details [Deploy instance based on PR changes](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist)

> To verify and test changes completed in a pull request..
> @magento-engcom-team give me test instance

Could you please confirm and fix found issue?


Thank you for contribution and collaboration!

2019-01-31 16:48 UTC, magento-engcom-team commented
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

2019-01-31 16:48 UTC, magento-engcom-team commented
Hi @sdzhepa, here is your [new Magento instance](https://pr-15383.instances.magento-community.engineering).
Admin access: [https://pr-15383.instances.magento-community.engineering/admin](https://pr-15383.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-14 12:30 UTC, jayankaghosh commented
@sdzhepa I have identified the problem. Will think of a solution and push when I get time.

2019-02-14 12:58 UTC, jayankaghosh commented
@magento-engcom-team  give me test instance

2019-02-14 17:36 UTC, VladimirZaets commented
Hi @jayankaghosh. We will retest tour PR and leave feedback. Thanks.

2019-03-15 14:20 UTC, p-bystritsky commented
@jayankaghosh, thank you for contribution.
Unfortunately, we have faced an issue. You can reproduce it by the next steps:
1. Create a Product.
2. Create a Cart Price Rule with some Discount Code.
3. Go to the Storefront.
4. Add the Product to Cart.
5. Edit Cart.
6. Try to apply the Discount Code.
An error message appears: 
![Screenshot_5](https://user-images.githubusercontent.com/22593218/54437848-3557c600-473e-11e9-998d-f848f3a652e8.png)

2019-03-19 19:42 UTC, jayankaghosh commented
@magento-engcom-team give me test instance

2019-03-19 19:42 UTC, magento-engcom-team commented
Hi @jayankaghosh. Thank you for your request. I'm working on Magento instance for you

2019-03-19 19:43 UTC, magento-engcom-team commented
Hi @jayankaghosh, here is your [new Magento instance](https://pr-15383.instances.magento-community.engineering).
Admin access: [https://pr-15383.instances.magento-community.engineering/admin](https://pr-15383.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-03-19 19:51 UTC, jayankaghosh commented
@p-bystritsky I couldn't reproduce the issue. Could you please have a look again and/or mention a more detailed steps to reproduce

2019-04-11 08:38 UTC, p-bystritsky commented
@jayankaghosh, I have a clean installation of Magento 2 with preconditions, visible below:
![invalid_form_key](https://user-images.githubusercontent.com/22593218/55943000-5c76ba00-5c4e-11e9-9c32-5858a94fe44f.gif)

2019-04-22 06:09 UTC, jayankaghosh commented
@p-bystritsky Thanks for informing. I'll have a look

2019-05-08 16:09 UTC, VladimirZaets commented
Hi @jayankaghosh, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-05-16 08:00 UTC, jayankaghosh commented
@magento-engcom-team give me test instance

2019-05-16 08:01 UTC, magento-engcom-team commented
Hi @jayankaghosh. Thank you for your request. I'm working on Magento instance for you

2019-05-16 08:01 UTC, magento-engcom-team commented
Hi @jayankaghosh, here is your [new Magento instance](https://pr-15383.instances.magento-community.engineering).
Admin access: [https://pr-15383.instances.magento-community.engineering/admin](https://pr-15383.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-05-28 10:56 UTC, VladimirZaets approved these changes

2019-05-28 10:57 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5174](https://jira.corp.magento.com/browse/ENGCOM-5174) has been created to process this Pull Request

2019-05-29 10:40 UTC, VasylShvorak commented
Hi @jayankaghosh Unfortunately PR changes cause new issues.
**Case 1:**
- Create a Product.
- Create a Cart Price Rule with some Discount Code.
- Go to the Storefront.
- Add the Product to Cart.
- Edit Cart.
- Enter discount code
- Click button Apply Discount
**Result:** 
:x: Nothing happen. Discount cannot be applied from cart page.

**Case 2:**
- Go to Create New Customer Account page or Customer Login page
- Fiil all fields
- Try login or create account
**Result:**
:x: Buttons Create an Account and Sign In are not working. Customer cannot be created or logged in.

2019-05-31 16:09 UTC, jayankaghosh commented
@VasylShvorak This issue is resolved now. 
The only drawback is, if the `mage/validation` plugin is used on a form, no other form submit listeners should be attached to the form, or, a `submitHandler` has to be explicitly mentioned where the further form submit listeners need to be specified. 
I believe this is a very particular and rare scenario and should not happen that often. It should work with all existing Magento's forms which are using the `mage/validation`

2019-06-06 14:49 UTC, VladimirZaets approved these changes

2019-06-06 14:50 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5174](https://jira.corp.magento.com/browse/ENGCOM-5174) has been created to process this Pull Request

2019-06-07 10:48 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-06-10 11:08 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15383) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15383) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: jayankaghosh<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: p-bystritsky<br/>:x: ysapiga

2019-06-10 11:56 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15383) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15383) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: jayankaghosh<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: p-bystritsky<br/>:x: ysapiga

2019-07-07 08:52 UTC, merged