Fix method name (typo)
magento/magento2 pull request #15514
Opened 2018-05-25 09:23 UTC by avoelkl

### Description
This PR deprecates a current method with a typo and introduces the new method with correct spelling

### Fixed Issues (if relevant)
none

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-25 09:25 UTC, magento-engcom-team commented
@avoelkl thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-05-25 11:38 UTC, dmanners requested changes
Just one small change

2018-05-25 11:38 UTC, dmanners commented on app/code/Magento/Multishipping/Block/Checkout/Overview.php
> -     * @return mixed
I think we might want to keep the return here

2018-05-25 13:51 UTC, avoelkl commented
Hi @dmanners, I updated the PR and re-added the return in the doc.
Please note that I also reverted one commit that accidentally made it into this branch.

2018-05-25 13:56 UTC, dmanners commented
Thanks @avoelkl I will process this now.

2018-05-28 08:17 UTC, dmanners approved these changes

2018-05-28 08:19 UTC, magento-engcom-team commented
Hi @dmanners, thank you for the review.
[ENGCOM-1675](https://jira.corp.magento.com/browse/ENGCOM-1675) has been created to process this Pull Request

2018-06-01 06:00 UTC, merged

2018-06-01 06:01 UTC, magento-engcom-team commented
Hi @avoelkl. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

2018-06-01 16:24 UTC, ihor-sviziev commented on app/code/Magento/Multishipping/Block/Checkout/AbstractMultishipping.php
> + * Mustishipping checkout base abstract block
Multishipping was correct

2018-06-01 16:24 UTC, ihor-sviziev commented on app/code/Magento/Multishipping/Block/Checkout/Shipping.php
> + * Mustishipping checkout shipping
Multishipping was correct

2018-06-01 16:24 UTC, ihor-sviziev commented on app/code/Magento/User/Model/Backend/Config/ObserverConfig.php
> +     * Get admin maxiumum security failures from config
Maximum was correct