Add the Symfony VarDumper component to allow the use of `dump()`
magento/magento2 pull request #15538
Opened 2018-05-26 13:49 UTC by jacquesbh

Allow the use of `dump()` in our code.

### Description

It's always cool as a developer of being able to debug some variables.
In M1 we used `Zend_Debug::dump()` and in M2 I wanted to use the `dump()` function from the Symfony VarDumper Component, because it's great.

So I added the dependency into the Developer module as a dev dependency. That way it's possible to not install it with the `--no-dev` option in composer.

![var-dump](https://user-images.githubusercontent.com/858611/40576777-42180c34-60fc-11e8-8fee-be6b9981bc45.gif)

### Manual testing scenarios

Just try `dump("foo");` or `dump($object);` in your code.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-26 14:25 UTC, vkublytskyi commented on app/code/Magento/Developer/composer.json
> +    "require-dev": {
This is won't have any effect as `require-dev` section used only for root composer package  so it will be ignored for git based installations and for composer based installations

2018-05-26 20:12 UTC, jacquesbh commented on app/code/Magento/Developer/composer.json
> +    "require-dev": {
Hum. Good point. I'll fix that.

2018-05-27 08:57 UTC, jacquesbh commented
@vkublytskyi I made the change.

The addition of the PHP 7.2 Polyfill by the component is breaking the tests in PHP 7.2. So, I have to take a look at it before merging obviously.

2018-07-11 01:40 UTC, orlangur requested changes
Changes must be applied to `2.2-develop` first.

Simply add it to `require-dev` section of root `composer.json`.

2018-08-02 12:23 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

2018-08-02 12:23 UTC, closed without merging