[Backport] Removed comma(,) from translate attribute
magento/magento2 pull request #15615
Opened 2018-05-31 06:32 UTC by dmytro-ch

### Original Pull Request 
 https://github.com/magento/magento2/pull/14363
There should be space instead of the comma(,) for separating two tag name inside the value of translate attribute.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-31 09:34 UTC, rogyar requested changes

2018-05-31 09:34 UTC, rogyar commented on app/code/Magento/Sales/etc/adminhtml/system.xml
> +            <group id="dashboard" translate="label comment" sortOrder="60" showInDefault="1" showInWebsite="0" showInStore="0">
I would recommend removing the `comment` completely. We don't have this section within a scope of the current node. The same is actual for  "Orders Cron Settings" group as well

2018-05-31 09:42 UTC, rogyar commented on app/code/Magento/Sales/etc/adminhtml/system.xml
> +            <group id="dashboard" translate="label comment" sortOrder="60" showInDefault="1" showInWebsite="0" showInStore="0">
Also, it's a good idea to add `comment` value to the child 'field' node

2018-06-01 06:45 UTC, dmytro-ch commented
Thank you @rogyar. This is a good point :)
I've applied the changes.

2018-06-01 07:07 UTC, rogyar approved these changes

2018-06-02 12:59 UTC, merged

2018-06-02 13:00 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.