Forward pull for issue 4803 2.1->2.2
magento/magento2 pull request #15691
Opened 2018-06-02 14:28 UTC by cream-julian

### Description
Forward pull of PR #15688 

@vkublytskyi Suggested this fix to resolve issue 4803, 

### Fixed Issues (if relevant)
1. magento/magento2#4803: Incorrect return value from Product Attribute Repository

### Manual testing scenarios
1. This can be tested by calling the function Magento\Catalog\Model\Product\Attribute\Repository::getCustomAttributesMetadata and check return type.

### Contribution checklist
 - [✓] Pull request has a meaningful description of its purpose
 - [✓] All commits are accompanied by meaningful commit messages
 - [✓] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-11 00:57 UTC, orlangur requested changes
@cream-julian please fix coding style and force push as a single commit.

2018-08-02 23:58 UTC, orlangur approved these changes

2018-08-02 23:59 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-2642](https://jira.corp.magento.com/browse/ENGCOM-2642) has been created to process this Pull Request

2018-08-08 10:51 UTC, merged

2018-08-08 10:52 UTC, magento-engcom-team commented
Hi @cream-julian. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.