Feature : Add tracking URL to sales_shipment_track and expose via API…
magento/magento2 pull request #15740
Opened 2018-06-04 07:39 UTC by RhodriOwainDavies

### Description
As a merchant I want to be able to add third party tracking URLs to the Shipment Track to help customers track their Shipments which do not have a Tracking Updates via The Tracking pop-up API request.

### Manual testing scenarios
Preconditions
- A shippable order exists for a registered Customer
- Merchant has navigated to the Ship Order page

Actions
- Merchant enters Tracking URL in the new field, and clicks Submit Shipment 

Expectations
* Merchant can see valid URL on View Shipment page
* Customer can see and click valid URL on View Shipments page
* API User can see tracking URL in response

### Contribution checklist
 - [X ] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-04 07:39 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15740) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15740) before we can accept your contribution.<br/>

2018-06-04 07:51 UTC, VladimirZaets commented
Hi @RhodriOwainDavies, please, sign CLA, otherwise, we can't process your pull request

2018-07-04 12:26 UTC, RhodriOwainDavies commented
Hi @VladimirZaets I've signed CLA and remaining filed tests seem to be not linked to my code.  Can you please spend a moment to perform an initial investigation and let me know of a suitable plan?

2018-07-12 15:20 UTC, ishakhsuvarov requested changes

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Api/Data/ShipmentTrackInterface.php
> +    const TRACK_URL = 'track_url';
It's best to avoid adding new constants, methods and anything else covered by the [Backward Compatible Development guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/index.html) to the interfaces and classes marked with `@api`.

It may be better to implement this solution using extension attributes of this interface.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Api/Data/TrackInterface.php
> +     * @since 100.1.2
`@since` tags are added automatically during release procedure. It's best not to introduce it manually, as we can not know beforehand which module version would be at the moment of the Pull Request merge.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Api/Data/TrackInterface.php
> +    public function setTrackUrl($trackUrl);
According to the [Technical Guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html) type hints for arguments and return types are required for every new method.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Api/Data/TrackInterface.php
> +    public function setTrackUrl($trackUrl);
Please consider using extension attributes for the new entity instead of adding new methods to the `@api` interface or it's default implementation.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Model/Order/Shipment/Track.php
> +    protected $_zendValidatorUri;
* [Technical Guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html) do encourage composition over inheritance, therefore `protected` properties are discouraged.
* Using underscore in property names is an outdated convention. It's not encouraged anymore.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Model/Order/Shipment/Track.php
> +        \Zend\Validator\Uri $zendValidatorUri,
Adding a new required argument to the constructor would break backwards compatibility. It's possible to preserve it in this case by adding an optional argument at the end of the list.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Model/Order/Shipment/Track.php
> +        $this->_zendValidatorUri->setAllowAbsolute(true)->setAllowRelative(false);
All initialization operations are prohibited in the constructors according to [Technical Guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html). Only dependency assignment and type validation are allowed.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Model/Order/Shipment/Track.php
> +        \Zend\Validator\Uri $zendValidatorUri,
It's considered to be the best practice to implement a wrapper or adapter for a third-party library to be used in the core components. This allows for better maintainability in the future.

For this case there is already a validator in the Magento Framework inside the `Magento\Framework\Url` namespace.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Model/Order/Shipment/Track.php
> +    public function getValidTrackUrl()
It's not considered a good practice to add any methods to the DataInterface implementation other then getters and setters for the predefined properties.

Additionally, adding method only to interface implementation would force it's clients to always rely on this specific implementation and not the interface.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Model/Order/Shipment/Track.php
> +    public function getValidTrackUrl()
Looks like this method's only usage occurs in the block. Therefore it may be moved to the block or even a separate service.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/etc/db_schema.xml
> +        <column xsi:type="varchar" name="track_url" nullable="true" length="255" comment="Url"/>
Implementing this feature as an extension attribute would allow to avoid schema modification for the existing table.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Test/Unit/Model/Order/Shipment/TrackTest.php
> +            'zendValidatorUri' => $zendValidatorUri,
While this test may now pass, it's best to also cover the clients of this dependency.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Shipping/Block/Items.php
> +    protected $_zendValidatorUri;
This property, together with it's assignment does not seem to have any clients. This may be an error.

2018-07-12 15:20 UTC, ishakhsuvarov commented on app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/ShipmentLoaderTest.php
> +                ['number' => 'jds0395', 'title' => 'DHL', 'carrier_code' => 'dhl', 'track_url' => ''],
Looks like this test does not test the feature which is added in this PR, as track url may be valid or not.

2018-07-12 15:20 UTC, ishakhsuvarov commented on dev/tests/integration/testsuite/Magento/Sales/Api/ShipmentTrackRepositoryInterfaceTest.php
> +            ->setValue('track url 5')
It would be best to test multiple cases, which appear from this PR: without track url, with valid and invalid track url.

2018-07-12 15:24 UTC, ishakhsuvarov commented
Hi @RhodriOwainDavies 
Please take a look at the review comments. Generally, I would suggest using extension attributes or dedicated API for this case, to preserve backwards compatibility.

Failed test jobs have been restarted.

2018-07-12 22:25 UTC, RhodriOwainDavies commented on app/code/Magento/Sales/Api/Data/TrackInterface.php
> +    public function setTrackUrl($trackUrl);
Isn't upgrading the Major version of the module the _perfect_ time for introducing new methods to the @api and making schema modifications?

2018-07-13 16:18 UTC, ishakhsuvarov commented on app/code/Magento/Sales/Api/Data/TrackInterface.php
> +    public function setTrackUrl($trackUrl);
I would say it's a perfect time for completely rethinking the existing API, but adding methods 1-by-1 is not the exact approach we are trying to stick to.

Generally we are attempting to keep as much contracts intact as possible, even if the release is upgrading module version. 

It's always best to design and implement "desired state" for an API or feature, when introducing incompatible changes to it.

2018-08-05 11:02 UTC, sidolov commented
Hi @RhodriOwainDavies , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-08-05 11:02 UTC, closed without merging