Admin product attribute set save controller refactor
magento/magento2 pull request #15850
Opened 2018-06-05 13:01 UTC by AnshuMishra17

### Description
Removed the direct use of object Manager from class Save in namespace Magento\Catalog\Controller\Adminhtml\Product\Set using controller dependency injection

### Manual testing scenarios
1. Added a new attribute set from Admin: Stores -> Attribute Set -> Add Attribute Set
2. Updated the attribute set in Stores -> Attribute Set

2018-06-05 13:01 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15850) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15850) before we can accept your contribution.<br/>

2018-06-05 15:09 UTC, ihor-sviziev requested changes

2018-06-05 15:09 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Set/Save.php
> +        \Magento\Framework\Json\Helper\DataFactory $jsonHelperFactory = null
We don't have any places where this class was created via factory.

Example: https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Checkout/Controller/Sidebar/UpdateItemQty.php#L44

2018-06-05 15:09 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Set/Save.php
> +        \Magento\Framework\Filter\FilterManagerFactory $filterManagerFactory = null,
We don't have any places where this class was created via factory.


Example:
https://github.com/magento/magento2/blob/268dce1cded190e7083d8ec9c864500dec254147/app/code/Magento/Store/Model/Address/Renderer.php#L48

2018-06-05 15:11 UTC, ihor-sviziev requested changes
Could you squash all your changes into one commit and force push?

2018-06-06 05:05 UTC, closed without merging

2018-06-06 05:07 UTC, AnshuMishra17 commented
@ihor-sviziev  I don't know how to squash all commits and force push, I have tried couple of times but I was unsuccessful. It would be helpful if you can share the the commands for it and little explanation.
For now, I am closing this PR and will generate a new one.

2018-06-06 05:19 UTC, ihor-sviziev commented
Hi @AnshuMishra17,
Here is example: https://github.com/magento/magento2/pull/15337#issuecomment-394604296 but you need to use 2.2-develop branch and your changes