Fix issue #14112
magento/magento2 pull request #15981
Opened 2018-06-10 09:21 UTC by riccardougolini

- set null OptionId
- set null all ProductLink
- updated unit test

to prevent overwrite of duplicated bundle product in table `catalog_product_bundle_selection`

2018-06-10 09:21 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=15981) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15981) before we can accept your contribution.<br/>

2018-11-19 14:31 UTC, sivaschenko requested changes
Thank you for the contribution. Please see the code review notes.

2018-11-19 14:31 UTC, sivaschenko commented on app/code/Magento/Bundle/Model/Product/CopyConstructor/Bundle.php
> +    public function build(Product $product, Product $duplicate): void
Please remove the strict :) "void" return type declaration as it can result in a warning on instances where the class is extended

2018-12-04 02:28 UTC, sidolov commented
Hi @riccardougolini , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-12-04 02:28 UTC, closed without merging