To Do: Enable creditmemo feature for zero order total
magento/magento2 pull request #16005
Opened 2018-06-11 10:32 UTC by viral-wagento

### Description

When customer place an order of zero ordertotal using Zero Subtotal Checkout Payment method and Admin create an invoice - order goes into Processing. After we can't cancel order. 

At such scenario, requirement comes to create creditmemo and return ordered item back in stock.
Magento doesn't allow to create a creditmemo for zero order total. So creating credit memo is required to return ordered items back in stock.

### Fixed Issues (if relevant)

1. magento/magento2#13153 : Credit memo for orders with zero TotalPaid

### Manual testing scenarios

1. Place an order of Zero amount using Zero Subtotal Checkout Payment method.
2. Create an invoice for that order.
3. As per Magento behaviour, we can't see Credit Memo Option for Zero Total Order.
4. But Now, you can see 'Credit Memo' option, create credit memo for that order and return item back to stock.
5. We can check same steps for Order of amount greater than zero, It will work proper for them too.

### Actual Result
For Zero Order Total, we can't see Credit Memo Option Available, and so we are unable to generate it.
![actual-result](https://user-images.githubusercontent.com/39254899/40906678-253a0eaa-67ff-11e8-8ed2-9a9375bc47ba.png)

### Expected Result
One should be able to generate Credit Memo even for Zero OrderTotal. 
![expected-result](https://user-images.githubusercontent.com/39254899/40906693-2f66f19a-67ff-11e8-8b0e-383c9114bae9.png)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-11 18:19 UTC, larsroettig commented on app/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save.php
> +        \Psr\Log\LoggerInterface $logger
It is Major Pull Request pls change the taget branch or 

`\Psr\Log\LoggerInterface $logger = null`

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/codebase-changes.html
New required constructor scalar argument (without pre-configured value)

2018-07-11 18:23 UTC, larsroettig requested changes
Hi @viral-wagent,

- Pls fix the static test
https://travis-ci.org/magento/magento2/jobs/394470047

- Pls fix the Integration Tests
https://travis-ci.org/magento/magento2/jobs/394470051


-  Manual Testing
:white_check_mark: Order and Credimemo Zero Subtotal
:white_check_mark: Order and Credimemo Zero Subtotal mixed

2018-07-11 18:26 UTC, larsroettig commented
@magento-engcom-team give me test instance

2018-07-11 18:26 UTC, magento-engcom-team commented
Hi @larsroettig. Thank you for your request. I'm working on Magento instance for you

2018-07-11 18:27 UTC, magento-engcom-team commented
Hi @larsroettig, here is your [new Magento instance](https://pr-16005.engcom.dev.magento.com).
Admin access: [https://pr-16005.engcom.dev.magento.com/admin](https://pr-16005.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

2018-07-12 03:54 UTC, viral-wagento commented
@larsroettig 
Thanks for review, I will work on your requested changes and update branch asap.

Currently I am working on Static Test - app/code/Magento/Sales/Model/Order.php:612.
[The method canCreditmemo() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.]

2018-11-19 14:45 UTC, sivaschenko requested changes
Hi @viral-wagento , thanks for your contribution! Please see the review notes, fix failing tests, ensure proper code style in all the changed files (including tests), update the branch and resolve conflicts.

2018-11-19 14:45 UTC, sivaschenko commented on app/code/Magento/Sales/Model/Order.php
> +        $hasActinFlag = $this->getActionFlag(self::ACTION_FLAG_EDIT) === false;
Please fix the variable nambe typo: $hasActinFlag -> $hasActionFlag

2018-11-19 14:45 UTC, sivaschenko commented on app/code/Magento/Sales/Model/Order.php
> +     *
Please remove this blank line

2018-11-19 14:45 UTC, sivaschenko commented on app/code/Magento/Sales/Model/Order.php
> +        $state1 = $dueAmountCondition || $paidAmtIsRefunded;
Please use meaningful variable names, avoid generic names like `$state1` and `$state2`

2018-11-19 14:45 UTC, sivaschenko commented on app/code/Magento/Sales/Model/Order/Creditmemo.php
> +
Please remove the blank line

2018-11-20 04:38 UTC, viral-wagento commented
Thanks @sivaschenko for reviewing. I will be implementing you changes and update my branch asap.

2018-11-20 06:43 UTC, viral-wagento commented
@sivaschenko  @larsroettig and @ishakhsuvarov 

I was trying to work on @sivaschenko 's given changes and conflicts. Then I found that my changes are already there in 2.2-develop branch. 

When did some investigation, I came to know that @SeruyV has copied my code and his code already merged in 2.2-develop now.

@sivaschenko  - you can see that, he has added same variable names, same function name, and has same typo in 'hasActionFlag' variable. He only did some changes after coying my code.

I was working for this, but unfortunately I didn't get credit for this. ¯\_(ツ)_/¯
 
Commit from @SeruyV can be seen here: https://github.com/magento/magento2/commit/9fe5066481ba9aee47c921d8e1ac64b18ee7b8c7#diff-6f2b3927e6511c70ebb080c37d84c2d3

2018-11-20 06:57 UTC, viral-wagento commented
@SeruyV  - when some juniors developers / new contributors are trying to contribute something, and facing issue, you can simple guide / help them. Magento is an open community to help and grow each other.

I am new to magento 2 and facing cyclomatic complexity issue in this PR, apart from that, my solution was working perfect. 

What you did is, just rearranged code, but the logic and everything is just as mine, even the comments for code (/Magento/Sales/Model/Order.php)  :( :(

2018-11-20 10:27 UTC, larsroettig commented
It is already fixed see:
https://github.com/magento/magento2/commit/b613382e6f2baa698e4e6bc9af279a81f698a49e

2018-11-20 10:27 UTC, closed without merging

2018-11-20 12:31 UTC, sivaschenko commented
Hi @viral-wagento we are very sorry that your contribution was reused without your credentials. It was first forward ported and merged to 2.3 - https://github.com/magento/magento2/commit/b613382e6f2baa698e4e6bc9af279a81f698a49e and then backported to 2.2. That's why that situation occurred.

I did raise this case with the teams to prevent such situations in the future.

Again, thank you very much for your contribution and sorry for the unfair situation.

2018-11-20 12:37 UTC, viral-wagento commented
Thank you for your response, @sivaschenko .!!

2018-11-20 12:54 UTC, sivaschenko commented
@viral-wagento, unfortunately, we do not have a way to assign points for closed pull requests, but I see your new https://github.com/magento/magento2/pull/19280 that will be rewarded once merged

2018-11-20 12:57 UTC, viral-wagento commented
@sivaschenko Okay no problem.
I asked for points of this PR, because this should be considered as new feature.
Anyway, It is fine, if you have no way.
Thanks!