Fix type hint of customer-data updateSectionId parameters
magento/magento2 pull request #16115
Opened 2018-06-14 07:56 UTC by Vinai

### Description

The type hint wrongly indicates the parameter should be a number, where in fact it is a boolean.
It is passed through to the server side to the controller action
`\Magento\Customer\Controller\Section\Load::execute()`
where it is cast to a bool and passed as the `$updateIds` parameter to
`\Magento\Customer\CustomerData\SectionPool::getSectionsData()`,
and from there as the boolean parameter `$forceUpdate  to the
`\Magento\Customer\CustomerData\Section\Identifier::initMark()` method.

This PR introduces no backward incompatibilities, it only fixes the type
hint to make the code more readable and improve compatibility with static
code analysis tools.

### Fixed Issues (if relevant)

I didn't bother first opening an issue about this small change.

### Manual testing scenarios

None, since it's only a comment change.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-14 07:56 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=16115) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16115) before we can accept your contribution.<br/>

2018-06-14 07:56 UTC, magento-engcom-team commented
Hi @Vinai. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-06-14 08:08 UTC, Vinai commented
I already signed the contributor license agreement years ago.

2018-06-14 20:34 UTC, orlangur commented
@Vinai maybe CLA was changed? :) I had to re-sign few days ago as well.

2018-06-14 20:38 UTC, orlangur requested changes
```
getFromServer: function (sectionNames, updateSectionId) {
            var parameters;

            sectionNames = sectionConfig.filterClientSideSections(sectionNames);
            parameters = _.isArray(sectionNames) ? {
                sections: sectionNames.join(',')
            } : [];
            parameters['update_section_id'] = updateSectionId;
```
The code looks quite confusing currently. Yeah, I see that second parameter of `reload()` is `true` or `false` but it does not really help when you read the method code.

Could you please rename those into something like

```
parameters['is_section_id_update_required'] = isSectionIdUpdateRequired;
```

(I didn't check exact semantics, naming is up to you). I believe such change will not be a BC break as well.

2018-06-16 18:53 UTC, Vinai commented
I renamed the variable to be more intent revealng. The `is` or `has` prefix does not really work here, as it's not a state description, but rather a command. I chose `forceNewSectionTimestamp` since that is a name that clearly identifies the purpose and type of the parameter for me.

2018-06-18 09:25 UTC, Vinai commented
Why is the Travis build not starting? And it’s not only this PR...

2018-06-22 12:31 UTC, Vinai commented
For reference a copy of a chat on slack:

> orlangur [8:23 AM]
> I already looked into that PR
> `parameters['update_section_id'] = forceNewSectionTimestamp;`
> had a talk with core guys regarding BC and left part of this
> what do you think about renamin request parameter as well?
> according to my understanding it will not break anything, just will require additional request for section data once
> 
> Vinai Kopp [8:25 AM]
> Well, wouldn’t a parameter name change be a bc break?
> Personally I think it would be good to choose a more expressive name.
> Any customizations that might use that parameter would break.
>
> orlangur [8:26 AM]
> there is no such explicit rule and in this case it will break only in rare chance of customization of this controller
> so, please change parameter name as well
> 
> Vinai Kopp [8:27 AM]
> Okay, will do.

2018-06-22 13:20 UTC, orlangur approved these changes

2018-06-22 13:22 UTC, orlangur commented
> Why is the Travis build not starting? And it’s not only this PR...

@Vinai no idea yet, Magento guys are aware of it.

2018-06-22 13:22 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-2104](https://jira.corp.magento.com/browse/ENGCOM-2104) has been created to process this Pull Request

2018-10-10 20:41 UTC, merged

2018-10-10 20:42 UTC, magento-engcom-team commented
Hi @Vinai. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.