FIX for apparently random API failures while using array types
magento/magento2 pull request #16137
Opened 2018-06-14 15:02 UTC by phoenix128

### Description
Magento2 web-api is based on the Interface doctype, but if the developer is using CR+LF end-of-line, the `\Magento\Framework\Reflection\TypeProcessor` class is not able to determine the class name on array types.

This was caused by a wrong regex non including `\r` in `\Magento\Framework\Reflection\TypeProcessor::getParamType`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-14 15:02 UTC, magento-engcom-team commented
Hi @phoenix128. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-06-14 18:32 UTC, hostep commented
Hi @phoenix128 

> Additional note: Magento 2.2-develop seems to be not affected by this.

I was triggered by this notice, so I started digging somewhat, and found this PR: https://github.com/magento/magento2/pull/12324 which completely removes those regexes.

It seems this was only applied to the 2.2-develop branch and not to the 2.3-develop branch.

Maybe it would be better if that PR is forward ported to 2.3?


(I have no idea what all the code in these PR's is about, so if what I say makes no sense, then ignore me ;))

2018-06-14 19:44 UTC, phoenix128 commented
Hello @hostep ,
this makes sense. Probably the best option is to forwardport that PR. I do not know why it was not made actually.

2018-06-16 16:00 UTC, larsroettig approved these changes
It fixes https://github.com/magento-engcom/msi/issues/1377

2018-06-16 16:01 UTC, magento-engcom-team commented
Hi @larsroettig, thank you for the review.
[ENGCOM-1998](https://jira.corp.magento.com/browse/ENGCOM-1998) has been created to process this Pull Request

2018-06-19 09:06 UTC, orlangur requested changes
@phoenix128 please provide scenario for a supported operating system when this situation may happen. Note that absence of Windows line-endings is enforced by `phpcs`.

Looks like affected developer forgot to configure git properly with `core.autocrlf` = `input` (see https://help.github.com/articles/dealing-with-line-endings/#global-settings-for-line-endings).

2018-06-19 09:22 UTC, merged

2018-06-19 09:23 UTC, magento-engcom-team commented
Hi @phoenix128. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.