Resolve meta asset urls in additional meta assets
magento/magento2 pull request #16187
Opened 2018-06-16 11:12 UTC by therouv

### Description
It is currently not possible to additional meta assets (e.g. a msapplication-TileImage) to the <head> as the image path of this assets are not resolved, since this meta value uses the `content` attribute instead of `src` or `href` and is used to specify the path for the tile images for Windows devices.

This pull requests fixes this behavior and resolves the url for the defined meta assets. The meta key `msapplication-TileImage` was added by default since it is a very common meta asset.

### Fixed Issues (if relevant)
1. magento/magento2#5023: It is not possible to add MS tile image meta via default_head_blocks.xml

### Manual testing scenarios
1. Open `default_head_blocks.xml` of your theme.
2. Add additional meta asset image, e.g. *msapplication-TileImage* like this: `<meta name="msapplication-TileImage" content="images/favicons/default/mstile-144x144.png"/>`
3. If you inspect the rendered html code of the generated page, the asset url will now be resolved and the image will be found.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-16 11:12 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=16187) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16187) before we can accept your contribution.<br/>

2018-06-16 11:12 UTC, magento-engcom-team commented
Hi @therouv. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-11-07 04:41 UTC, orlangur requested changes
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

2018-11-19 09:39 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-11-19 09:39 UTC, closed without merging