Covered Magento\Checkout\Model\Cart\CollectQuote by Unit Test
magento/magento2 pull request #16271
Opened 2018-06-20 13:38 UTC by eduard13

### Description
This PR adds an unit test for \Magento\Checkout\Model\Cart\CollectQuote class.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-20 13:38 UTC, magento-engcom-team commented
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-05 11:50 UTC, rogyar requested changes

2018-07-05 11:50 UTC, rogyar commented on app/code/Magento/Checkout/Test/Unit/Model/Cart/CollectQuoteTest.php
> +        $this->estimateAddressFactoryMock = $this->getMockBuilder(EstimateAddressInterfaceFactory::class)
You can simplify this part of the code by using `createPartialMock` instead of the chain with `disableOriginalConstructor` and other methods.

2018-07-05 11:54 UTC, rogyar commented
Hi @eduard13. Thank you for your contribution. Please, make the minor improvements mentioned in the review. 
Also, in the future, I would recommend using `with()` in the mock expectation chain to make the stub's  assertion more strict (https://github.com/magento/magento2/blob/ffa3df12a9eec50084ffdec792bdb9a2d3fce3dc/app/code/Magento/Catalog/Test/Unit/Block/NavigationTest.php#L100).

2018-07-09 07:36 UTC, eduard13 commented
Hi @rogyar, thank you for suggestions, I've updated the Unit Test regarding your recommendations.

2018-07-10 11:34 UTC, rogyar approved these changes

2018-07-10 11:35 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-2255](https://jira.corp.magento.com/browse/ENGCOM-2255) has been created to process this Pull Request

2018-07-13 07:16 UTC, merged

2018-07-13 07:17 UTC, magento-engcom-team commented
Hi @eduard13. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.