Fix issues with setup:install command if scopes are defined in config.php
magento/magento2 pull request #16317
Opened 2018-06-22 08:08 UTC by jalogut

# Preconditions

* Core Magento, no additional modules
* Tested on 2.2-develop with PHP 7.0 and 2.3-develop with PHP 7.1

# Steps to reproduce

Create `app/etc/config.php` with the following:

- Default store name different than "default". For example "custom"
- One extra store

```
return [
    'modules' => [
       /* All core modules enabled */
      ...
    ],
    'scopes' => [
        'websites' => [
            'admin' => [
                'website_id' => '0',
                'code' => 'admin',
                'name' => 'Admin',
                'sort_order' => '0',
                'default_group_id' => '0',
                'is_default' => '0'
            ],
            'base' => [
                'website_id' => '1',
                'code' => 'base',
                'name' => 'Main Website',
                'sort_order' => '0',
                'default_group_id' => '1',
                'is_default' => '1'
            ]
        ],
        'groups' => [
            [
                'group_id' => '0',
                'website_id' => '0',
                'code' => 'default',
                'name' => 'Default',
                'root_category_id' => '0',
                'default_store_id' => '0'
            ],
            [
                'group_id' => '1',
                'website_id' => '1',
                'code' => 'main_website_store',
                'name' => 'Main Website Store',
                'root_category_id' => '2',
                'default_store_id' => '1'
            ]
        ],
        'stores' => [
            'admin' => [
                'store_id' => '0',
                'code' => 'admin',
                'website_id' => '0',
                'group_id' => '0',
                'name' => 'Admin',
                'sort_order' => '0',
                'is_active' => '1'
            ],
            'custom' => [
                'store_id' => '1',
                'code' => 'custom',
                'website_id' => '1',
                'group_id' => '1',
                'name' => 'Default Store View',
                'sort_order' => '0',
                'is_active' => '1'
            ],
            'extra' => [
                'store_id' => '3',
                'code' => 'extra',
                'website_id' => '1',
                'group_id' => '1',
                'name' => 'Extra Store',
                'sort_order' => '1',
                'is_active' => '1'
            ]
        ]
    ]
];
```

run `bin/magento setup:install`

# Expected result
Magento being installed and additional store created

# Actual result

## First Error
```
[Progress: 405 / 754]
Module 'Magento_Payment':
[Progress: 406 / 754]
Module 'Magento_CatalogRule':
Installing data... Upgrading data...
[Progress: 407 / 754]
Module 'Magento_CatalogSearch':
Installing data...

  [LogicException]
  There is no such engine:
```
### Reason

- `Magento_CatalogSearch` setup scripts calls `scopeConfig->getValue()` on store scope. This method request the value for the default store set in `config.php` which in this example will be `custom`
- Store values are retrieved in the `Fallback` class with the following code:

```
// app/code/Magento/Store/Model/Config/Processor/Fallback.php
public function process(array $data)
{
    if ($this->deploymentConfig->isDbAvailable()) {//read only from db
        $this->storeData = $this->storeResource->readAllStores();
        $this->websiteData = $this->websiteResource->readAllWebsites();
}
```

As we can see, list of stores is here retrieved from the database, where our `custom` store does not exists yet. 

### Solution
- [Link to code changed in this PR]()
- Retrieve lists of stores always from `scopes` object. If I am not wrong, this object contains the list of stores from `config.php` or from the Database if they are not defined in `config.php`

## Second Error
After fixing the previous error, if we try to run `setup:install` again, no we get the following error

```
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin
Processing configurations data from configuration file...

Import failed: Requested store is not found

```

### Reason

- After creating the new `extra` Store, the method `Magento\Store\Model\StoreManager::reinitStores()` is executed. This method calls `$this->scopeConfig->clean()`. Which will first clean the `scopes`.
- When cleaning the scopes, they are also loaded again because one `logging` submethod is calling `scopeConfig->getValue()`.
- When loading the scopes again, the list of stores however is different on different objects. 

```
// Magento\Store\App\Config\Type\Scopes
public function get($path = '')
{
    if (null === $this->data) {
        $this->data = new DataObject($this->source->get());
    }
}
```

`$this-data` contains the list of scopes. The for the `storeRepository` object, this list is still the old one without the new store added.

### Solution

Option 1:
- The right solution will be to clear the `storeRepository` object and `Magento\Config\App\Config\Type\System` before the `Magento\Store\App\Config\Type\Scopes` -> That is not possible however because another race condition is trigger when the `System` is cleared before the `Scopes`

Option 2:
- Do not call `scopeConfig->getValue()` during the `Magento\Store\App\Config\Type\Scopes` to check whether the logs are enabled.

Option 3:
- Execute `app:config:import` in a new thread, where the objects are all clean.
- That is the actual solution of this PR because I did not manage to find a better way after 10 hours working on it. See [Link to code in this PR]()

## Fixed Issues
1. #156862

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-22 08:08 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=16317) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16317) before we can accept your contribution.<br/>

2018-06-22 08:08 UTC, magento-engcom-team commented
Hi @jalogut. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-11-07 04:42 UTC, orlangur requested changes
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

2018-11-19 09:41 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-11-20 09:06 UTC, jalogut commented
Destination branch has been updated. I guess I can reopen this PR ;)

2018-11-21 13:40 UTC, sivaschenko commented
@jalogut I think It's better to [port](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting) to 2.3-develop branch as your current code base is 2.2 and is not compatible with 2.3

2018-12-06 17:03 UTC, sidolov commented
Hi @jalogut , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-12-06 17:03 UTC, closed without merging