magento/magento2#15505: Interceptor class methods do not support nullable return types
magento/magento2 pull request #16337
Opened 2018-06-22 14:15 UTC by swnsma

…able return types.

- improve code generation for proxies, loggers and interceptors;
- fix not supported nullable return types in interceptors and literals like 'parent' and 'self';
- add support of return types for loggers and interceptors;

Code generation improvements.
### Description
Improve code generation for proxies, loggers and interceptors.
Fix not supported nullable return types in interceptors and return types like 'parent' and 'self'.
Add support of return types for loggers and interceptors.

### Fixed Issues (if relevant)

1. magento/magento2#15505: Interceptor class methods do not support nullable return types

### Manual testing scenarios
Steps to reproduce well described in related issue.
In additional, PR have impact on Logger and Proxies generation.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-22 14:15 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=16337) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16337) before we can accept your contribution.<br/>

2018-06-22 14:15 UTC, magento-engcom-team commented
Hi @swnsma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-11-07 03:22 UTC, orlangur requested changes
@swnsma, please rework this PR as backport of corresponding commits in `2.3-develop`: https://github.com/magento/magento2/commits/2.3-develop/lib/internal/Magento/Framework/Interception/Code/Generator/Interceptor.php

It looks like `self` return type is already supported in `2.2-develop` but nullable return types not.

2018-11-19 10:14 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-11-19 10:14 UTC, closed without merging