admin checkout agreement controllers refactor
magento/magento2 pull request #16505
Opened 2018-07-03 12:30 UTC by AnshuMishra17

### Description
Refactor the code by removing the direct use of ObjectManager and includes the dependencies using Constructor Dependency Injection

### Manual testing scenarios
1. Created, updated and deleted checkout agreements from the admin-end.

2018-07-03 12:30 UTC, magento-engcom-team commented
Hi @AnshuMishra17. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-06 12:12 UTC, miguelbalparda approved these changes

2018-07-06 12:14 UTC, magento-engcom-team commented
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2210](https://jira.corp.magento.com/browse/ENGCOM-2210) has been created to process this Pull Request

2018-07-13 07:28 UTC, sidolov requested changes

2018-07-13 07:28 UTC, sidolov commented on app/code/Magento/CheckoutAgreements/Controller/Adminhtml/Agreement.php
> +    protected $_agreementRepository;
Please, inject dependencies in classes when they are really needed. 
Make new properties private and try to avoid usage leading underscore in var and methods name.

2018-07-27 11:36 UTC, AnshuMishra17 commented on app/code/Magento/CheckoutAgreements/Controller/Adminhtml/Agreement.php
> +    protected $_agreementRepository;
This has been fixed.

2018-07-31 06:41 UTC, sidolov approved these changes

2018-07-31 06:44 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-2210](https://jira.corp.magento.com/browse/ENGCOM-2210) has been created to process this Pull Request

2018-08-01 16:31 UTC, merged

2018-08-01 16:32 UTC, magento-engcom-team commented
Hi @AnshuMishra17. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.