Resolved : JS files located outside the web/js directory
magento/magento2 pull request #16708
Opened 2018-07-11 09:12 UTC by hitesh-wagento

### Description
Some JS files are direct children of `web` rather than `web/js`. This does not follow instructions from the [dev docs](https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/custom_js.html) thus is confusing.

### Fixed Issues (if relevant)

1. <https://github.com/magento/magento2/issues/16302>: JS files located outside the web/js directory

### Expected result
1. JS files to be inside `web/js` as per the dev docs.

### Actual result
1. JS files are direct children of `web`, this is inconsistent with the dev docs.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-11 09:13 UTC, magento-engcom-team commented
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-11 09:14 UTC, hitesh-wagento commented
Hi @VladimirZaets

As per you comment in https://github.com/magento/magento2/pull/16582 I have created new PR based on 2.3-develop branch.

2018-07-11 18:13 UTC, ihor-sviziev commented
@VladimirZaets @hitesh-wagento what if we will just create map between old and new paths? In this case - this change will be backward compatible. Am I wrong?
Example:
```javascript
var config = {
    map: {
        '*': {
            'Magento_Payment/transparent': 'Magento_Payment/js/transparent'
        }
    }
};
```

2018-07-11 20:22 UTC, larsroettig commented
@magento-engcom-team give me test instance

2018-07-11 20:23 UTC, magento-engcom-team commented
Hi @larsroettig. Thank you for your request. I'm working on Magento instance for you

2018-07-11 20:23 UTC, magento-engcom-team commented
Hi @larsroettig, here is your [new Magento instance](https://pr-16708.engcom.dev.magento.com).
Admin access: [https://pr-16708.engcom.dev.magento.com/admin](https://pr-16708.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

2018-07-11 20:34 UTC, larsroettig commented
Manual Testing 
- Create new Produkt Backend
- Checkout Produkt
- Register Account
- Captcha Passoword Forget
- Captcha Register
- Captcha Login 
- Order Grid
- Forget Password


Manual Testing looks very good

2018-07-17 07:07 UTC, hitesh-wagento commented
@larsroettig 

Any update in this PR ?

Thanks

2018-07-18 11:25 UTC, ihor-sviziev requested changes
1. Please create PR to `2.2-develop` branch first

2. Please implement changes in all requirejs-config.js files that I described in https://github.com/magento/magento2/pull/16708#issuecomment-404262484 (in 2.2-develop PR only)

3. Please create separate commit for separate module in order to have ability apply these changes as described in https://support.magento.com/hc/en-us/articles/360005484154-Create-a-patch-for-a-Magento-2-Composer-installation-from-a-GitHub-commit

2018-07-18 11:34 UTC, hitesh-wagento commented
Hi @ihor-sviziev 

Previously I have created  PR based to 2.2-develop but @VladimirZaets told me created PR based on 2.3-develop. could you please suggest what can I do ?

https://github.com/magento/magento2/pull/16582#issuecomment-403016268

_______________
3. Please create separate commit for separate module in order to have ability apply these changes as described in https://support.magento.com/hc/en-us/articles/360005484154-Create-a-patch-for-a-Magento-2-Composer-installation-from-a-GitHub-commit
==> Means do you need to 27 (Specific Module requirejs-config.js or rename files) files commit in one branch but different commit ID ?

2018-07-18 11:45 UTC, ihor-sviziev commented
Hi @hitesh-wagento ,
1. These changes were requested to be done in 2.3-develop because they are not backward compatible. Now I added comment with info how we can make them backward compatible. So let's add backward compatible changes to 2.2-develop, 
2. I thought it will be few commits. Let's  **not** split it to commit per module

If you have any questions - feel free to contact me in slack

2018-07-18 14:03 UTC, ihor-sviziev commented
Hi @hitesh-wagento,
We are having discussion about this specific case with @VladimirZaets, so please wait once we will finalize out general vision how it should be done. I will update you after discussion.

2018-07-18 16:16 UTC, VladimirZaets commented
Hi @hitesh-wagento. Please apply the fix provided by @ihor-sviziev to Magento 2.2 release line. 
For Magento 2.3 release line your fix is ok and will be processed after PR to Magento 2.2 will be merged.

2018-07-19 03:38 UTC, hitesh-wagento commented
@VladimirZaets Thanks for reply.

2018-07-19 11:05 UTC, hitesh-wagento commented
Hi @VladimirZaets 

I have completed all changes `2.2-develop` related https://github.com/magento/magento2/pull/16582

Thanks

2018-08-07 12:54 UTC, ihor-sviziev requested changes
I can't find changes that you did in: https://github.com/magento/magento2/pull/16582/files#diff-ce4bc7c513c965385f8696ebc9545f42
Everything else looks good

2018-08-09 11:31 UTC, hitesh-wagento commented
Hi @ihor-sviziev 

you can find changes in https://github.com/magento/magento2/pull/16708/commits/0ce439b1ecc2906dd840f37989c7c8ccf84dc6bf

Thanks

2018-08-09 11:54 UTC, ihor-sviziev commented
Hi @hitesh-wagento,
Sorry, but I can't see changes in send friend module

2018-08-24 06:02 UTC, hitesh-wagento commented
Hello @ihor-sviziev 

I have checked again all module and added send friend module changes.

Thanks

2018-08-28 15:35 UTC, ihor-sviziev approved these changes

2018-09-05 11:44 UTC, hitesh-wagento commented
@ihor-sviziev 

Any update in this PR ?

Thanks

2018-09-05 11:47 UTC, ihor-sviziev approved these changes

2018-09-05 13:50 UTC, ihor-sviziev commented
Hi @hitesh-wagento,
Looks like we have conflict during merging 2.3-develop and your PR. Probably it caused 

Could squash all your changes into single commit and force push your changes or merge 2.3-develop branch?

2018-09-05 13:55 UTC, hitesh-wagento commented
Hello @ihor-sviziev 

Could you please share with me steps how to merge all commits in one commit?

Thanks

2018-09-07 06:14 UTC, ihor-sviziev commented
Hi @hitesh-wagento  could you just merge 2.3-develop branch from magento/magneto2 repository?

2018-09-07 07:19 UTC, ihor-sviziev requested changes

2018-09-07 07:19 UTC, ihor-sviziev commented on app/code/Magento/Captcha/view/frontend/web/js/onepage.js
> +/**
This file was removed in https://github.com/magento/magento2/commit/efdc2e39a07828c505611ceb8f537ee35eb8aeae#diff-90e2539e902c667160d28b2cb3c56486
No need to create it again.

2018-09-07 07:37 UTC, hitesh-wagento commented on app/code/Magento/Captcha/view/frontend/web/js/onepage.js
> +/**
Removed and push again

2018-09-10 06:08 UTC, ihor-sviziev approved these changes

2018-09-10 06:09 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2895](https://jira.corp.magento.com/browse/ENGCOM-2895) has been created to process this Pull Request

2018-09-12 10:18 UTC, merged

2018-09-12 10:19 UTC, magento-engcom-team commented
Hi @hitesh-wagento. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.