Allow use special chars in FTP connection string
magento/magento2 pull request #16743
Opened 2018-07-12 11:40 UTC by javierperezm

### Description

FTP connections can't use user or password strings with special characters, like @ or #.
$user = 'my@mail.com';
$pass = '#my@pass';
$host = 'ftphost.com';
$ftp->connect("ftp://{$user}:{$pass}@{$host}");

connect() calls parse_url() and this will break down bad the special chars...

Solution:
// ...
$user = urlencode($user);
$pass = urlencode($pass);
$ftp->connect( ... );

But connect() method calls ftp_login() without decode the $user and $pass vars

### Manual testing scenarios

1. $ftp->connect("ftp://my%23mail.com:mypass@myhost.com"); // this works
2. $ftp->connect("ftp://no_special_chars:mypass@myhost.com"); // this works too

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-12 11:40 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=16743) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16743) before we can accept your contribution.<br/>

2018-07-12 11:40 UTC, magento-engcom-team commented
Hi @javierperezm. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-16 16:05 UTC, aleron75 requested changes

2018-07-16 16:05 UTC, aleron75 commented on lib/internal/Magento/Framework/System/Ftp.php
> +            $this->login(urldecode($params['user']), urldecode($params['pass']));
What about moving this kind of operation inside the `validateConnectionString()` method?
After all, it's where we validate the connection string and extract its components.
Let me know.

2018-07-17 10:23 UTC, javierperezm commented on lib/internal/Magento/Framework/System/Ftp.php
> +            $this->login(urldecode($params['user']), urldecode($params['pass']));
You are right :)

2018-07-17 10:37 UTC, javierperezm commented on lib/internal/Magento/Framework/System/Ftp.php
> +            $this->login(urldecode($params['user']), urldecode($params['pass']));
May I create another pull-request?

2018-07-17 13:01 UTC, aleron75 commented on lib/internal/Magento/Framework/System/Ftp.php
> +            $this->login(urldecode($params['user']), urldecode($params['pass']));
Hi @javierperezm, you can continue working on your fork/branch and new pushed commits should automatically be added to current PR.

2018-07-18 12:27 UTC, closed without merging

2018-07-18 12:28 UTC, javierperezm commented on lib/internal/Magento/Framework/System/Ftp.php
> +            $this->login(urldecode($params['user']), urldecode($params['pass']));
I did a new pull request inthe 2.3-dev branch. Thanks :)