Add compare list link to success message after adding a product
magento/magento2 pull request #16757
Opened 2018-07-12 16:40 UTC by gelanivishal

### Original Pull Request
#13862

### Description
If I add a product to the compare list, I want to go the compare list directly after that in many cases without having to search for a link. Thus, the link has been added to the success message now.

### Manual testing scenarios
1. Go to a product view page
2. Click "Add to compare"
3. Check if the success message contains a link to the compare list:
![grafik](https://user-images.githubusercontent.com/662059/36728546-6012f1d4-1bc1-11e8-8554-1aebae427ede.png)

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-12 16:40 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-13 08:07 UTC, orlangur commented
@gelanivishal don't forget to add Backport/Forwardport into issue title.

2018-07-13 08:23 UTC, nuzil commented
@gelanivishal please fix Static and integration tests

2018-07-13 08:25 UTC, nuzil requested changes

2018-07-13 08:25 UTC, nuzil commented on app/code/Magento/Catalog/etc/frontend/di.xml
> -            <argument name="galleryImagesConfig" xsi:type="array">
Looks like you wrongly resolved conflicts while doing this Forwardport. Can you please check this part and resolve it correctly?

2018-07-13 17:22 UTC, gelanivishal commented
@nuzil I have fixed request chagnes.

2018-07-15 20:37 UTC, nuzil requested changes
@gelanivishal can you please fix failed tests?

2018-07-15 20:37 UTC, nuzil commented on app/code/Magento/Catalog/etc/frontend/di.xml
> -                <item name="small_image" xsi:type="array">
Hi
Looks like you accidentally removed working part of code, can you please review your changes? As reference you can use this commit from original PR 
https://github.com/magento/magento2/pull/13862/files#diff-da4fdd9a985964091b2bbe0a3722ab77

2018-07-16 02:52 UTC, gelanivishal commented
@nuzil Please review at once.

2018-07-21 03:50 UTC, gelanivishal commented
@orlangur Please review requested changes.

2018-07-23 15:45 UTC, nuzil commented
Hi @gelanivishal you still have failed Static tests, can you please review this changes?

2018-08-10 08:06 UTC, merged

2018-08-10 08:07 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.