[Forwardport] Fixed condition with usage isPost method
magento/magento2 pull request #16823
Opened 2018-07-15 01:54 UTC by gelanivishal

### Original Pull Request 
#12626

- removed private function isPost
- removed unused imports
- added request method isPost
- added interface that expands HTTP request class

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-15 01:54 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-16 14:27 UTC, ihor-sviziev requested changes

2018-07-16 14:27 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/App/HttpRequestInterface.php
> +namespace Magento\Framework\App;
Please define strict type declaration for this file

2018-07-20 05:30 UTC, ihor-sviziev commented
Hi @gelanivishal I fixed this issue myself. Let's wait when Travis will run all tests

2018-07-20 06:08 UTC, ihor-sviziev approved these changes

2018-07-20 06:09 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2431](https://jira.corp.magento.com/browse/ENGCOM-2431) has been created to process this Pull Request

2018-08-10 08:06 UTC, merged

2018-08-10 08:07 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.