clean code
magento/magento2 pull request #16841
Opened 2018-07-16 02:54 UTC by GraysonChiang

### Description

Just modify some code, and make it Cleaner more...

2018-07-16 02:54 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=16841) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16841) before we can accept your contribution.<br/>

2018-07-16 02:55 UTC, magento-engcom-team commented
Hi @GraysonChiang. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-16 07:03 UTC, ihor-sviziev approved these changes

2018-07-16 07:05 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2366](https://jira.corp.magento.com/browse/ENGCOM-2366) has been created to process this Pull Request

2018-07-16 07:05 UTC, magento-engcom-team commented
@GraysonChiang thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-07-18 07:47 UTC, ihor-sviziev requested changes

2018-07-18 07:47 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Helper/Image.php
> +        return $this->attributes[$name]?? : null;
1. Please add space there before `??`
2. Looks like there should not be `:`

2018-07-18 07:53 UTC, GraysonChiang commented
Sor, I fixed it and commit that again.

2018-07-18 11:22 UTC, ihor-sviziev requested changes

2018-07-18 11:22 UTC, ihor-sviziev commented on app/code/Magento/Backend/Model/Menu/Builder.php
> +        return $params[$paramName]?? $defaultValue;
Please add space before `??`

2018-07-18 11:22 UTC, ihor-sviziev commented on app/code/Magento/BundleImportExport/Model/Export/RowCustomizer.php
> +        return $this->typeMapping[$type]??  self::VALUE_DYNAMIC;
1. Please add space before `??`
2. Remove 2nd space after `??`

2018-07-18 11:22 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Helper/Output.php
> +        return $this->_handlers[$method] ?? : [];
Please remove `:` (and space hear it)

2018-07-18 11:22 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Product/Option.php
> +        return $optionGroupsToTypes[$type] ?? : '';
please remove `:` (and space near it)

2018-07-18 11:22 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php
> +        return $conditionsMap[$conditionType] ??  $conditionType;
please remove 2nd space after `??`

2018-07-18 11:22 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Ui/Component/Listing/Columns.php
> +        return $this->filterMap[$frontendInput] ??  $this->filterMap['default'];
please remove 2nd space after `??`

2018-07-18 11:22 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/DataObject/Copy/Config.php
> +        return $fieldsets[$name] ??  null;
Please remove 2nd space after `??`

2018-07-18 11:22 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/View/Page/Config/Structure.php
> +        return $array[$key] ??  [];
Please remove 2nd space after `??`

2018-07-19 01:31 UTC, GraysonChiang commented
I fixed.

2018-07-19 02:38 UTC, ihor-sviziev approved these changes

2018-07-19 02:40 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2366](https://jira.corp.magento.com/browse/ENGCOM-2366) has been created to process this Pull Request

2018-07-23 10:10 UTC, merged

2018-07-23 10:11 UTC, magento-engcom-team commented
Hi @GraysonChiang. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.