[Forwardport] Corrected return message from ProductRuleTest.php
magento/magento2 pull request #16853
Opened 2018-07-16 08:29 UTC by sanganinamrata

### Original Pull Request 
 https://github.com/magento/magento2/pull/16721

### Description

Corrected return message from ProductRuleTest.php

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-16 08:29 UTC, magento-engcom-team commented
Hi @sanganinamrata. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-16 08:37 UTC, ihor-sviziev requested changes

2018-07-16 08:37 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/CatalogRule/Model/Indexer/ProductRuleTest.php
> +            "Catalog price rule doesn't ap product with visibility value \"Not Visibility Individually\""
It looks like mistake

2018-07-27 12:07 UTC, gelanivishal commented on dev/tests/integration/testsuite/Magento/CatalogRule/Model/Indexer/ProductRuleTest.php
> +            "Catalog price rule doesn't ap product with visibility value \"Not Visibility Individually\""
Done.

2018-07-28 21:53 UTC, ihor-sviziev approved these changes

2018-07-28 21:55 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2592](https://jira.corp.magento.com/browse/ENGCOM-2592) has been created to process this Pull Request

2018-07-29 14:05 UTC, merged

2018-07-29 14:06 UTC, magento-engcom-team commented
Hi @sanganinamrata. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.