Fix blocked a frame with origin
magento/magento2 pull request #16887
Opened 2018-07-17 15:52 UTC by iGerchak

### Preconditions
1. Magento 2.2.3 or 2.2.4 or 2.2.5
2. Add  the following script to the product page: 
`<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

### Steps to reproduce
1. Flush cache
2. Open dev-console in your browser
3. Reload page many times

### Expected result
Console without errors

### Actual result
1. Sometime we'll have this error:
![console](https://user-images.githubusercontent.com/34220204/42828390-280d8f80-89f1-11e8-93d9-25559082edfc.png)

### Tech notes
Time to time created iframe on following line: https://github.com/magento/magento2/blob/2.2-develop/lib/web/jquery.js#L3123

Our change add try-catch to this method, and when error appears - we just returning an empty array.

2018-07-17 15:52 UTC, magento-engcom-team commented
Hi @iGerchak. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-22 05:23 UTC, ihor-sviziev requested changes
As we discussed with @VladimirZaets in slack - probable root of the issue - using object by refference that could change during the validation and cause such issue, another thing - validation might be not really good. Lets try to improve validation or clone iframe element before validation just to have only one state during processing. But currently solution is not really good because it's hiding an actual issue.

2018-07-23 12:30 UTC, magento-engcom-team commented
@iGerchak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-07-24 10:22 UTC, iGerchak commented
@ihor-sviziev, I tried to make a clone of the object and work with it, but this solution does not fix the issue with the jQuery error in console.

2018-08-14 11:42 UTC, ihor-sviziev requested changes

2018-08-14 11:42 UTC, ihor-sviziev commented on app/code/Magento/PageCache/view/frontend/web/js/page-cache.js
> +                        return [];
Please add logging of this exception as "warning" using "Magento/Ui/view/base/web/js/lib/logger/console-logger.js"

2018-08-30 10:20 UTC, sidolov commented
Hi @iGerchak , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-09-14 05:51 UTC, ihor-sviziev approved these changes

2018-09-14 05:53 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2973](https://jira.corp.magento.com/browse/ENGCOM-2973) has been created to process this Pull Request

2018-09-14 05:57 UTC, ihor-sviziev approved these changes

2018-09-14 05:58 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2973](https://jira.corp.magento.com/browse/ENGCOM-2973) has been created to process this Pull Request

2018-11-06 18:13 UTC, merged

2018-11-06 18:14 UTC, magento-engcom-team commented
Hi @iGerchak. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.