[Fix] Do not modify current list of countries with require states during setup upgrade
magento/magento2 pull request #16885
Opened 2018-07-17 14:40 UTC by jalogut

Upgrading from any version `<2.2.0` to any version `>=2.2.0` results in modifications of `general/region/state_required` value.

## How to reproduce

- Having a Magento project in any version `<2.2.0`
- Set custom values in `core_config_data` for `general/region/state_required`
- Upgrade Magento project to any version `>=2.2.0`

### Expected result

- `general/region/state_required` are not modified

### Actual result

- `general/region/state_required` are overridden with all enabled countries in `general/country/allow`

## Fixed Issues

- Checkout not working after upgrade for existing users that do no have a state in their address
- State is a mandatory for all allowed countries which might break other functionalities depending on that (sign up, reset password, customer import...)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-17 14:40 UTC, magento-engcom-team commented
Hi @jalogut. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-18 05:49 UTC, fooman commented on app/code/Magento/Directory/Setup/UpgradeData.php
> +            $this->addCountryRegions($setup, 'IN', $this->getDataForCroatia());
I believe IN and HR should be swapped here

2018-09-05 06:39 UTC, dmanners requested changes
I have 1 question on this review and there is still one outstanding from FooMan.

2018-09-05 06:39 UTC, dmanners commented on app/code/Magento/Directory/etc/di.xml
> -                <item name="FR" xsi:type="string">FR</item>
What was the reasoning behind making this change?

2018-09-05 06:39 UTC, dmanners commented
Hi @jalogut do you have time to  look into the feedback on this pull request?

Thanks

2018-09-06 14:13 UTC, jalogut commented
Hi, sorry that was a mistake. I updated the PR with some changes. It should be ok now. Thanks for checking.

2018-09-19 10:56 UTC, dmanners commented
During testing we had the following cases fail

```
I tried to upgrade from 2.2-develop to PR, - "general/region/state_required" is not modified.

When I upgraded from 2.2.3 to PR, - in addition to our value, IN is added to "general/region/state_required".

When upgrading from 2.1-develop to PR, - in addition to our value, HR and IN are added to "general/region/state_required"
```

@jalogut could you please look at these failures for us.

Thank you.

2018-09-19 12:39 UTC, jalogut commented
What do you mean with failing? That is right behaviour. This setup scripts are depending on the current version of `Magento_Directory` module.

`HR` is added on 2.0.1 and `IN` in 2.0.2

2018-09-20 09:23 UTC, dmanners commented
@jalogut are IN and HR added to "general/region/state_required" in earlier versions? Just going from your description:

```
general/region/state_required is not modified
```

If it was reported as a failure as in two cases it is modified.

2018-09-20 10:02 UTC, jalogut commented
Well I meant “do not overwrite current value”. Before the PRs, the current value is overwritten with the default magento ones. This PRs only adds the new countries while keeping previous value. Should I update the PR title?

2018-09-26 08:14 UTC, dmanners commented
Ah I see @jalogut thanks for the clarification.

2018-09-28 12:17 UTC, merged

2018-09-28 12:18 UTC, magento-engcom-team commented
Hi @jalogut. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.