Resolved special character issue for sidebar
magento/magento2 pull request #17070
Opened 2018-07-24 14:10 UTC by deepjoshi94

### Description
Side bar for wishlist on catalog page or my account page, if product name contains special character like TM it will display `&trade;` instead of special character.

### Manual testing scenarios

1. Verified My Account page wishlist sidebar with product in wishlist having special character.
2. Verified Catalog page wishlist sidebar with product in wishlist having special character.
3. Verified Catalog Search page wishlist sidebar with product in wishlist having special character.
4. Verified Wishlist page wishlist sidebar with product in wishlist having special character.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-24 14:10 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=17070) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=17070) before we can accept your contribution.<br/><hr/>**Deep A. Joshi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-07-24 14:10 UTC, magento-engcom-team commented
Hi @deepjoshi94. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-24 14:32 UTC, deepjoshi94 commented
@magento-engcom-team give me test instance

2018-07-24 14:32 UTC, magento-engcom-team commented
Hi @deepjoshi94. Thank you for your request. I'm working on Magento instance for you

2018-07-24 14:33 UTC, magento-engcom-team commented
Hi @deepjoshi94, here is your [new Magento instance](https://pr-17070.engcom.dev.magento.com).
Admin access: [https://pr-17070.engcom.dev.magento.com/admin](https://pr-17070.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

2018-08-01 12:56 UTC, orlangur requested changes
What if product name contains `<`, `>` or `&`? What is current behavior and what will be the changed one?

2018-08-02 06:32 UTC, deepjoshi94 commented
@orlangur If product name contains <, > or & it will display as it is in product name, for reference you can see Product 1 in after-fix image.
If we are using ASCII value for the given characters that is:
**&lt; for <
&gt; for >
&amp; for &**
it will convert HTML name into symbol.

You can check image before-fix here it displays ASCII code instead of converting it into HTML element.
For example: **&lt; Product &amp; 2 &gt;** instead of **< Product & 2 >**

![after-fix](https://user-images.githubusercontent.com/37620096/43566126-f82ddb74-964a-11e8-926b-f025073b8018.png)
![before-fix](https://user-images.githubusercontent.com/37620096/43566127-f85a8b56-964a-11e8-8042-8a50e7caac3f.png)

2018-08-02 12:05 UTC, orlangur commented
@deepjoshi94 after the fix if we use `<script>alert(1);</script>` as product name, will we see the alert?

2018-08-02 12:43 UTC, deepjoshi94 commented
@orlangur No we won't see any alert, I have created a product with the given name in instance provided.

Please find the link below:
[https://pr-17070.engcom.dev.magento.com/](url)

2018-08-02 13:37 UTC, orlangur approved these changes
@VladimirZaets would be really nice if you take a quick look into this.

2018-08-02 13:38 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-2636](https://jira.corp.magento.com/browse/ENGCOM-2636) has been created to process this Pull Request

2018-08-02 13:38 UTC, magento-engcom-team commented
@deepjoshi94 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-08-07 10:31 UTC, merged

2018-08-07 10:32 UTC, magento-engcom-team commented
Hi @deepjoshi94. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.