Refactory to Magento_Backend module class.
magento/magento2 pull request #17101
Opened 2018-07-24 19:15 UTC by tiagosampaio

Refactory of a class in Magento_Backend module.

### Description
Simple refactory to Magento_Backend module class.
- Turning protected properties into private ones.
- Using dependency injection rather than using Object Manager directly.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-24 19:15 UTC, magento-engcom-team commented
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-25 03:15 UTC, ihor-sviziev requested changes

2018-07-25 03:15 UTC, ihor-sviziev commented on app/code/Magento/Backend/Helper/Dashboard/Order.php
> +    private $orderCollection;
This change is not backward compatible. Please revert it.
More details: https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/

2018-07-25 03:15 UTC, ihor-sviziev commented on app/code/Magento/Backend/Helper/Dashboard/Order.php
> +    private $storeManager;
This change is not backward compatible. Please revert it.
More details: https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development

2018-07-25 03:15 UTC, ihor-sviziev commented on app/code/Magento/Backend/Helper/Dashboard/Order.php
> +        \Magento\Store\Model\StoreManagerInterface $storeManager
Please make new constructor argument optional and as retrieve it by fallback from object manager.
More details: https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development

2018-07-28 13:57 UTC, tiagosampaio commented
@ihor-sviziev changes were reverted.

2018-07-28 21:27 UTC, ihor-sviziev requested changes
In general looks good, but there still backward incompatible changes

2018-07-28 21:27 UTC, ihor-sviziev commented on app/code/Magento/Backend/Helper/Dashboard/Order.php
> +    private $_orderCollection;
Please revert this change, it's not backward compatible

2018-07-28 21:27 UTC, ihor-sviziev commented on app/code/Magento/Backend/Helper/Dashboard/Order.php
> +    private $_storeManager;
Please revert this change, it's not backward compatible

2018-07-28 21:30 UTC, ihor-sviziev commented
I fixed these small issues myself. Let's wait for Travis results

2018-08-07 13:00 UTC, ihor-sviziev approved these changes

2018-08-07 13:01 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2687](https://jira.corp.magento.com/browse/ENGCOM-2687) has been created to process this Pull Request

2018-08-07 15:17 UTC, tiagosampaio commented
Thanks @ihor-sviziev.

2018-08-08 14:56 UTC, merged

2018-08-08 14:57 UTC, magento-engcom-team commented
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.