[Backport] Removed double occurrence of keywords in sentences.
magento/magento2 pull request #17157
Opened 2018-07-26 05:06 UTC by gelanivishal

### Original Pull Request
https://github.com/magento/magento2/pull/16182

### Description

Removed double occurrence of keywords "to, the" from sentences.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-26 08:30 UTC, sidolov requested changes

2018-07-26 08:30 UTC, sidolov commented on app/code/Magento/Customer/view/frontend/web/js/password-strength-indicator.js
> +            this.options.cache.email = $(this.options.formSelector).find(this.options.emailSelector);
Looks like this changes not related to current PR, please, revert.

2018-07-27 06:15 UTC, gelanivishal commented
@sidolov Please review it.

2018-07-27 07:21 UTC, gelanivishal commented on app/code/Magento/Customer/view/frontend/web/js/password-strength-indicator.js
> +            this.options.cache.email = $(this.options.formSelector).find(this.options.emailSelector);
Done.

2018-07-27 14:57 UTC, merged

2018-07-27 14:58 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

2026-10-24 23:26 UTC, dukesice19-ai commented on app/code/Magento/Customer/view/frontend/web/js/password-strength-indicator.js
> +            this.options.cache.email = $(this.options.formSelector).find(this.options.emailSelector);
Mmm