[Backport] Admin user auth controller refactor
magento/magento2 pull request #17156
Opened 2018-07-26 04:37 UTC by gelanivishal

### Original Pull Request
#16560

### Description
Refactor the code by removing the direct use of ObjectManager and includes the dependencies using Constructor Dependency Injection

### Manual testing scenarios
1. Created a new admin user
2. Login and logout using new admin user
3. Clicked on forgot password and provided new admin user email id.
4. Clicked on reset password link in email.
5. Created new password from reset password page.
6. Login using new password.

2018-07-26 08:28 UTC, sidolov requested changes

2018-07-26 08:28 UTC, sidolov commented on app/code/Magento/User/Controller/Adminhtml/Auth/Forgotpassword.php
> +     * @param CollectionFactory $userCollectionFactory
Please, add missing parameter to doc block

2018-07-27 06:20 UTC, gelanivishal reviewed
@sidolov I have added missing parameter, Please review it.

2018-07-27 06:20 UTC, gelanivishal commented on app/code/Magento/User/Controller/Adminhtml/Auth/Forgotpassword.php
> +     * @param CollectionFactory $userCollectionFactory
Done.

2018-07-27 06:54 UTC, sidolov approved these changes

2018-07-27 06:56 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-2557](https://jira.corp.magento.com/browse/ENGCOM-2557) has been created to process this Pull Request

2018-07-27 09:42 UTC, sidolov commented
Hi @gelanivishal , one of static tests failing with provided changes: 
```
Magento\Test\Integrity\Di\CompilerTest::testConstructorIntegrity
Passed: 7792, Failed: 2, Incomplete: 0, Skipped: 0.
Data set: array (
  0 => '\\Magento\\User\\Controller\\Adminhtml\\Auth\\Forgotpassword',
)
Incorrect dependency in class \Magento\User\Controller\Adminhtml\Auth\Forgotpassword in /var/www/html/app/code/Magento/User/Controller/Adminhtml/Auth/Forgotpassword.php
\Magento\Backend\Helper\Data already exists in context object

Data set: array (
  0 => '\\Magento\\User\\Controller\\Adminhtml\\Auth\\ResetPasswordPost',
)
Incorrect dependency in class \Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost in /var/www/html/app/code/Magento/User/Controller/Adminhtml/Auth/ResetPasswordPost.php
\Magento\Backend\Helper\Data already exists in context object
```

Please, take a look and fix your solution according to test rules.
Thank you!

2018-08-10 07:54 UTC, sidolov commented
Hi @gelanivishal , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-08-10 07:54 UTC, closed without merging