Fixed a grammatical error on the vault tooltip
magento/magento2 pull request #17200
Opened 2018-07-27 16:56 UTC by mage2pratik

### Description

Fixed a grammar error in the "What is this" tooltip for Braintree save for later. Changed "you" to "your".

### Fixed Issues (if relevant)

1. magento/magento2#17151: Fixed a grammatical error on the vault tooltip

### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-28 20:24 UTC, ihor-sviziev requested changes

2018-07-28 20:24 UTC, ihor-sviziev commented on app/code/Magento/Braintree/view/frontend/web/template/payment/form.html
> +                             translate="'We store your payment information securely on Braintree servers via SSL.'"></div>
Hi @mage2pratik,
We don't have this change in 2.2-develop and original PR.
Please create revert this part in scope of this PR as we don't have this change in original PR and create new PR into 2.2-develop.

2018-07-29 14:07 UTC, ihor-sviziev approved these changes

2018-07-29 14:09 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2598](https://jira.corp.magento.com/browse/ENGCOM-2598) has been created to process this Pull Request

2018-07-31 06:18 UTC, merged

2018-07-31 06:19 UTC, magento-engcom-team commented
Hi @mage2pratik. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.