[Backport] Fix for #14593 (second try #16431)
magento/magento2 pull request #17223
Opened 2018-07-28 04:31 UTC by gelanivishal

### Original Pull Request 
 https://github.com/magento/magento2/pull/16477
### Description

#### Preconditions: 

Magento version 2.2.4 with luma theme

#### Step to reproduce:

 - Open chrome developer console
 - Add a product to the cart.
 - From the mini cart in the upper right click the trash icon.
 - A confirmation modal will open.
 - Press Esc button

#### Expected Result
- Close the confirm

#### Actual result
- js error

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Checkout/view/frontend/web/js/sidebar.js#L96

~~~
Uncaught TypeError: Cannot read property 'stopImmediatePropagation' of undefined
~~~
![2018-06-21 15-50-01](https://user-images.githubusercontent.com/412612/41720145-cbfd9e28-756a-11e8-9c4a-1500171c3788.png)

### Fixed Issues 

1. magento/magento2#14593

### P.S.

First, pull request - https://github.com/magento/magento2/pull/16431

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-28 23:02 UTC, ihor-sviziev requested changes

2018-07-28 23:02 UTC, ihor-sviziev commented on app/code/Magento/Checkout/view/frontend/web/js/sidebar.js
> +                        always: function (e) {
Could you describe why this code was added? I can't find this change in original PR.

2018-07-28 23:07 UTC, ihor-sviziev approved these changes

2018-07-28 23:07 UTC, ihor-sviziev commented on app/code/Magento/Checkout/view/frontend/web/js/sidebar.js
> +                        always: function (e) {
Ah, just in order to be the same across all release lines. It's a good idea.

2018-07-28 23:08 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2595](https://jira.corp.magento.com/browse/ENGCOM-2595) has been created to process this Pull Request

2018-08-01 06:20 UTC, merged

2018-08-01 06:21 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.