Fixed typo mistakes
magento/magento2 pull request #17274
Opened 2018-07-30 12:50 UTC by jignesh-baldha

### Description
I've fixed typo mistakes.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-30 12:50 UTC, magento-engcom-team commented
Hi @jignesh-baldha. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-07-30 13:07 UTC, jignesh-baldha commented
@magento-engcom-team Don't need the test instance, I've just fixed typo mistakes.

2018-07-30 21:30 UTC, dverkade requested changes
Hi, please check my comments for this PR.

2018-07-30 21:30 UTC, dverkade commented on dev/tests/integration/testsuite/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsertTest.php
> +    public function testExecutewithStaticUrls()
Please use camel case, so this should be: testExecuteWithStaticUrls

2018-07-30 21:30 UTC, dverkade commented on dev/tests/integration/testsuite/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsertTest.php
> +    public function testExecutewithoutStaticUrls()
Please use camel case, so this should be: testExecuteWithoutStaticUrls

2018-07-31 07:54 UTC, sidolov commented
Hi @jignesh-baldha , unfortunately, we can't accept such Pull Requests to 2.2 release line, all code cleanup like typos, spelling mistakes, etc should be delivered to 2.3 release line. For more information, please, refer to [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules)

2018-07-31 07:54 UTC, closed without merging

2018-07-31 13:29 UTC, dverkade commented
I have created a PR for Magento 2.3 here: #17293