fixing : Translation not working in catalog-add-to-cart.js
magento/magento2 pull request #17381
Opened 2018-08-06 06:40 UTC by septa-setiawan

### Description

Fixing : Translation not working in catalog-add-to-cart.js

### Fixed Issues (if relevant)

1. magento/magento2#14024: Translation not working in catalog-add-to-cart.js
2. ...

### Manual testing scenarios

1. Adding the translation in app/i18n/<vendor>/en_GB.csv
2. Apply changes in app/code/Magento/Catalog/view/frontend/web/js/catalog-add-to-cart.js
3. Deploy then flush cache

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-06 06:40 UTC, magento-engcom-team commented
Hi @septa-setiawan. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-08-06 06:40 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=17381) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=17381) before we can accept your contribution.<br/>

2018-08-06 06:47 UTC, sidolov requested changes

2018-08-06 06:47 UTC, sidolov commented on app/code/Magento/Catalog/view/frontend/web/js/catalog-add-to-cart.js
> -                addToCartButton.attr('title', addToCartButtonTextDefault);
It' not a good idea to remove the extension point for button title, the title may be redefined by 3d party extension via `self.options.addToCartButtonTextDefault` and will be broken after such changes

2018-08-06 06:56 UTC, septa-setiawan commented on app/code/Magento/Catalog/view/frontend/web/js/catalog-add-to-cart.js
> -                addToCartButton.attr('title', addToCartButtonTextDefault);
OK will trying another way, thanks.

2018-08-06 16:28 UTC, Karlasa commented
@septa-setiawan  Are you sure it's even broken in latest 2.2 release?

2018-08-20 07:40 UTC, sidolov commented
Hi @septa-setiawan , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-08-20 07:40 UTC, closed without merging