Fix sending duplicate emails
magento/magento2 pull request #17484
Opened 2018-08-10 07:28 UTC by iGerchak

### Preconditions
1. Magento 2.2.4 or 2.2.5
2. Wyomind Cron Scheduler v1.4.0 

### Description
We installed Wyomind Cron Scheduler v1.4.0 and in the result, we have duplicates email (5-6 emails for 1 order).
This hotfix warns against similar situations with sending duplicate emails and adds a limit of 50 emails per cronjob.

### Steps to reproduce:
1. Disable crontab
2. Make 2 or more orders
3. Enable crontab

### Expected result
No duplicate Emails.

### Actual result
Duplicate Emails.

2018-08-10 07:28 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=17484) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=17484) before we can accept your contribution.<br/><hr/>**Ivan Gerchak** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-08-10 07:28 UTC, magento-engcom-team commented
Hi @iGerchak. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-08-10 08:13 UTC, ihor-sviziev requested changes

2018-08-10 08:13 UTC, ihor-sviziev commented on app/code/Magento/Sales/Model/EmailSenderHandler.php
> +            $this->entityCollection->clear();
As we discussed - it's not good idea to clean collection every time. It's better to fix root of the issue - this object should NOT be shared. Please add `shared="false"` to https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Sales/etc/di.xml#L355-L395

2018-08-10 08:13 UTC, ihor-sviziev commented on app/code/Magento/Sales/Model/EmailSenderHandler.php
> +            $this->entityCollection->setPageSize(50)->setCurPage(1);
1. AFAIK current page is set to 1 by default, no need to specify it
2. Could you extract `50` to system configuration, near `sales_email/general/async_sending` and make it configurable via admin? Please make it configurable globally only (the same as `sales_email/general/async_sending`)

2018-08-13 15:14 UTC, ihor-sviziev commented
Reopened this PR just to restart Travis builds

2018-08-14 10:41 UTC, ihor-sviziev requested changes

2018-08-14 10:41 UTC, ihor-sviziev commented on app/code/Magento/Sales/etc/adminhtml/system.xml
> +                    <label>Limit to sending emails</label>
You're not limiting email sending, you're limiting how many entities (orders/shipments/etc) will be processed per one cron run.
Please Update label and description

2018-08-14 13:32 UTC, ihor-sviziev approved these changes

2018-08-14 13:34 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2787](https://jira.corp.magento.com/browse/ENGCOM-2787) has been created to process this Pull Request

2018-08-14 13:34 UTC, magento-engcom-team commented
@iGerchak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-08-15 06:41 UTC, ihor-sviziev requested changes
Build on travis failed. Could you update tests?

2018-08-15 10:46 UTC, merged

2018-08-15 10:47 UTC, magento-engcom-team commented
Hi @iGerchak. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.