Link logo in web setup wizard to back-end base URL
magento/magento2 pull request #17543
Opened 2018-08-11 21:45 UTC by arnoudhgz

### Description
When you get to the web setup wizard from the Magento back-end it was not possible to get back to the back-end from this page.

This commit makes the logo clickable and when you click it you will return the Magento back-end.

### Fixed Issues (if relevant)
1. magento/magento2#13948: 
Sidebar shortcut to admin dashboard (Magento logo on top left) has no link in web setup wizard
2. ...

### Manual testing scenarios
1. Admin dashboard > System > Web Setup Wizard
2. Click Magento logo on top left
3. You get back to admin dashboard

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-11 21:45 UTC, magento-engcom-team commented
Hi @arnoudhgz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-08-12 10:19 UTC, mzeis requested changes

2018-08-12 10:19 UTC, mzeis commented on setup/view/magento/setup/navigation/side-menu.phtml
> -        class="logo logo-static"
Hi @arnoudhgz, thanks for your contribution!
When you remove the CSSclass `logo-static` from the template, it should be possible to remove its declaration in the LESS file. Please can you look into this?

Thanks!

2018-08-12 14:07 UTC, arnoudhgz commented on setup/view/magento/setup/navigation/side-menu.phtml
> -        class="logo logo-static"
@mzeis thank you for the feedback, this was indeed possible. 

It was also set in the `setup/pub/styles/setup.css` file (which was actually loaded on the page).

I removed it from both locations.

![image](https://user-images.githubusercontent.com/10864061/44002843-c41d08ee-9e49-11e8-905e-557cab4b1d1b.png)

2018-08-14 18:51 UTC, merged

2018-08-14 18:52 UTC, magento-engcom-team commented
Hi @arnoudhgz. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.