Prakash282 develop 2.2 patch 17465
magento/magento2 pull request #17577
Opened 2018-08-13 13:29 UTC by prakash282

### Description
Added proper logic to create and update bundle product option title value store wise.

### Fixed Issues (if relevant)
magento/magento2#17465: Not able to set bundle product option title value store wise in magento 2 #17465

### Manual testing scenarios

On any bundle product, we need to set different store view title as per store.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-13 13:29 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=17577) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=17577) before we can accept your contribution.<br/>

2018-08-13 13:29 UTC, magento-engcom-team commented
Hi @prakash282. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-09-05 06:45 UTC, dmanners requested changes
I have some questions raised on this PR. Thanks for your feedback.

2018-09-05 06:45 UTC, dmanners commented on app/code/Magento/Bundle/Model/ResourceModel/Option.php
> +            'store_id = ?' => $object->getStoreId(),
Is there any chance that the `getStoreId` is not set? In this case if it is not set what would happen here?

2018-09-05 06:45 UTC, dmanners commented on app/code/Magento/Bundle/Model/ResourceModel/Option.php
> +                    $conditions['store_id = ?'] = 0;
If the store id on the object is not 0 why set the conditions store id to be 0?

2018-09-06 13:24 UTC, mageprakash commented on app/code/Magento/Bundle/Model/ResourceModel/Option.php
> +            'store_id = ?' => $object->getStoreId(),
if we use this 'store_id = ? OR store_id = 0' => $object->getStoreId() then we always get deafult store entry while we update store view title for a particular store. First We checked current store tile exits or not.

2018-09-06 13:24 UTC, mageprakash commented on app/code/Magento/Bundle/Model/ResourceModel/Option.php
> +                    $conditions['store_id = ?'] = 0;
This code allow to update default_title, while we save store_view title for a particular store.
 
if ($object->getStoreId() != '0')
{
    $conditions['store_id = ?'] = 0;
    $connection->update(
        $this->getTable('catalog_product_bundle_option_value'),
        [
            'title' => $object->getDefaultTitle()
        ],
        $conditions
    );
}

2019-04-04 20:10 UTC, orlangur commented
@prakash282 please create PR for `2.3-develop` first.

2019-04-04 20:10 UTC, closed without merging