[Forwardport] Refactor JS code and added JS component file
magento/magento2 pull request #17630
Opened 2018-08-15 12:42 UTC by Yogeshks

### Original Pull Request 
 https://github.com/magento/magento2/pull/17527

### Description
Created a new JS component with the callback function.
Replaced `<script/>` tag with `<script type="text/x-magento-init" />`

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios

1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-15 12:42 UTC, magento-engcom-team commented
Hi @Yogeshks. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-08-15 12:45 UTC, sidolov requested changes

2018-08-15 12:45 UTC, sidolov commented on app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/form.phtml
> +        '#edit_form': {
Single quotes are not allowed in JSON configuration

2018-08-15 12:45 UTC, sidolov commented on app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/form.phtml
> +                validationUrl: '<?= /* @escapeNotVerified */ $block->getValidationUrl() ?>'
Single quotes are not allowed in JSON configuration

2018-08-15 12:45 UTC, sidolov commented on app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/edit/action/attribute.phtml
> +                validationUrl: '<?= /* @escapeNotVerified */ $block->getValidationUrl() ?>'
Single quotes are not allowed in JSON configuration

2018-08-15 12:45 UTC, sidolov commented on app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/form.phtml
> +            "Magento_Ui/catalog/product/edit/attribute": {
File `catalog/product/edit/attribute.js` located in Magento_Catalog module instead of Magento_Ui

2018-08-15 12:45 UTC, sidolov commented on app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/edit/action/attribute.phtml
> +            "Magento_Ui/catalog/product/edit/attribute": {
File catalog/product/edit/attribute.js located in Magento_Catalog module instead of Magento_Ui

2018-08-15 14:48 UTC, ihor-sviziev commented
Just add following commit:
01ed8364031dacbdf42c7a5333947410a729fc3c

2018-08-30 10:21 UTC, sidolov commented
Hi @Yogeshks , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-09-13 20:57 UTC, merged

2018-09-13 20:59 UTC, magento-engcom-team commented
Hi @Yogeshks. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.