Use route ID when creating secret keys in backend menus instead of route name
magento/magento2 pull request #17650
Opened 2018-08-16 18:43 UTC by lfolco

### Description

If you use a different route ID and front name in the _adminhtml/routes.xml_ file, you will get redirected to the dashboard when clicking on the menu link.

This is because the route front name is used to generate the secret key when creating the menu, and route ID is used to generate the secret key for key validation.

The method `\Magento\Backend\Model\Url::getSecretKey()` takes three parameters: route ID, action path, and action. When creating links for the menu, `Magento\Backend\Block\Menu::_callbackSecretKey($match)` is reading the URL paths from XML, which are using front names. I have injected `\Magento\Framework\App\Route\ConfigInterface` in order to use `getRouteByFrontName($routeName)` in order to get the proper route ID.

### Fixed Issues (if relevant)
1. magento/magento2#7557: Backend Security key broken for controllers with front name not equal to route ID

### Manual testing scenarios

1. Create a module with an _adminhtml/routes.xml_ file that has a different route ID and front name.
2. Add an _adminhtml/menu.xml_ file that uses the front name in the `action` attribute.
3. Click on the new menu link; you will be taken to the correct admin page.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-16 18:43 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=17650) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=17650) before we can accept your contribution.<br/>

2018-08-16 18:43 UTC, magento-engcom-team commented
Hi @lfolco. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

2018-08-17 13:47 UTC, miguelbalparda commented
Thanks a lot Laura! I'll process this and let you know if we have any questions.

2018-08-20 14:00 UTC, miguelbalparda approved these changes

2018-08-20 14:03 UTC, magento-engcom-team commented
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2838](https://jira.corp.magento.com/browse/ENGCOM-2838) has been created to process this Pull Request

2018-08-20 14:03 UTC, magento-engcom-team commented
@lfolco thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-09-03 11:52 UTC, sidolov requested changes

2018-09-03 11:52 UTC, sidolov commented on app/code/Magento/Backend/Block/Menu.php
> +        \Magento\Framework\App\Route\ConfigInterface $routeConfig,
Please, inject new dependencies according to our [Backward compatible development guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/)

2018-09-04 20:38 UTC, lfolco commented
Please check now, I have committed the requested changes.

2018-09-11 10:19 UTC, merged

2018-09-11 10:20 UTC, magento-engcom-team commented
Hi @lfolco. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.