[Backport] CMS: Add missing unit tests for model classes
magento/magento2 pull request #17682
Opened 2018-08-18 22:39 UTC by dmytro-ch

### Original PR: #17678

### Description
This PR adds missing unit tests for CMS model class:
- `\Magento\Cms\Model\Block`

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-20 08:55 UTC, rogyar requested changes

2018-08-20 08:55 UTC, rogyar commented on app/code/Magento/Cms/Test/Unit/Model/BlockTest.php
> +        );;
Please, remove the extra semicolon

2018-08-20 19:21 UTC, dmytro-ch commented
@rogyar, I've updated the PR. Thank you!

2018-08-21 06:03 UTC, rogyar approved these changes

2018-08-21 07:12 UTC, rogyar requested changes

2018-08-21 07:12 UTC, rogyar commented on app/code/Magento/Cms/Test/Unit/Model/BlockTest.php
> +declare(strict_types=1);
We cannot use `strict_types` for Magento 2.1 since it's compatible with PHP 5.6. The strict_types introduced in PHP 7. Please, remove the declaration

2018-08-21 07:21 UTC, dmytro-ch commented on app/code/Magento/Cms/Test/Unit/Model/BlockTest.php
> +declare(strict_types=1);
Thank you! I've fixed it.

2018-08-22 08:26 UTC, rogyar approved these changes

2018-08-22 08:27 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-2844](https://jira.corp.magento.com/browse/ENGCOM-2844) has been created to process this Pull Request

2018-08-23 11:08 UTC, merged

2018-08-23 11:09 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.16. 
Please check the release notes for final confirmation.