[Forwardport] Review: Adding missing unit test for Observer
magento/magento2 pull request #17704
Opened 2018-08-20 13:35 UTC by eduard13

Original PR #17693

### Description
This PR adds missing unit test for Review observer classes:
- \Magento\Review\Observer\ProcessProductAfterDeleteEventObserver

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-20 13:35 UTC, magento-engcom-team commented
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-08-21 07:22 UTC, rogyar requested changes

2018-08-21 07:22 UTC, rogyar commented on app/code/Magento/Review/Test/Unit/Observer/ProcessProductAfterDeleteEventObserverTest.php
> +    private $_resourceReviewMock;
Please, remove underscores from the private properties. It's not a way to go if we want to be PSR-2 compatible ;)
https://www.php-fig.org/psr/psr-2/#42-properties

2018-08-21 07:31 UTC, eduard13 commented on app/code/Magento/Review/Test/Unit/Observer/ProcessProductAfterDeleteEventObserverTest.php
> +    private $_resourceReviewMock;
@rogyar the naming was fixed.
I thought that it should be kept the naming as it is in the testable class.
Thank you.

2018-08-22 08:24 UTC, rogyar approved these changes

2018-08-22 08:25 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-2845](https://jira.corp.magento.com/browse/ENGCOM-2845) has been created to process this Pull Request

2018-08-26 07:15 UTC, merged

2018-08-26 07:16 UTC, magento-engcom-team commented
Hi @eduard13. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.