[Forwardport] Fix Missing meta title tag and doesn't show product name if meta title is empty
magento/magento2 pull request #17771
Opened 2018-08-23 15:29 UTC by nmalevanec

### Original Pull Request
https://github.com/magento/magento2/pull/15532

### Description
The current Magento behaviour does not allow to specify a title meta tag and the "Meta Title" option in the product's page is binded to the page's title.

This PR adds the meta tile tag and allows to use title and meta title independently.

### Fixed Issues (if relevant)
1. magento/magento2#15501: M2.2.4 missing meta title tag and doesn't show product name if meta title is empty

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-23 15:29 UTC, magento-engcom-team commented
Hi @nmalevanec. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-06 13:44 UTC, sidolov requested changes
Hi @nmalevanec , why you skipped code fragment in ``processMetadataContent` method from original PR? Looks like this changes should be ported too

2018-09-06 14:25 UTC, nmalevanec commented
@sidolov, because  'processMetadataContent' in 2.3-develop seems more flexible and basically 'processMetadataContent' from original pr doesn't work because doesn't considering 'title' case.
```
 if ($name === 'title') {
            if (!$content) {
                $content = $this->escaper->escapeHtml($this->pageConfig->$method()->get());
            }
            return $content;
        }
```

2018-09-11 16:09 UTC, sidolov approved these changes

2018-09-11 16:10 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-2874](https://jira.corp.magento.com/browse/ENGCOM-2874) has been created to process this Pull Request

2018-09-13 20:57 UTC, merged

2018-09-13 20:59 UTC, magento-engcom-team commented
Hi @nmalevanec. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.