17656- Show free shipping method with error if method not applicable
magento/magento2 pull request #17779
Opened 2018-08-24 07:40 UTC by saravananvelu

### Description

Display error message and show free shipping method in checkout if the Show Shipping Method if not applicable option is enabled.

### Fixed Issues (if relevant)
1. magento/magento2#17656: Magento 2.2.4 Free Shipping Enable “Show Method” do not show
2. magento/magento2#16312: Magento 2.2.4 Free Shipping Enable “Show Method” do not show

### Manual testing scenarios

1. Navigate to Admin => Stores => Configuration => Sales => Shipping Methods.
2. Enable Free shipping
3. Add the product to cart
4. Set the minimum amount greater than the cart amount in free shipping method settings.
5. Set Show Method if Not Applicable options as Yes
6. Set Ship to Applicable Countries option as All Allowed Countries
5. Go to checkout page. It should show the shipping method with error.

2018-08-24 07:40 UTC, magento-engcom-team commented
Hi @saravananvelu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-21 18:06 UTC, sivaschenko requested changes
The proper place for this validation is extending \Magento\Shipping\Model\Carrier\AbstractCarrier::processAdditionalValidation

2018-11-21 18:09 UTC, sivaschenko commented
@saravananvelu thank you for the contribution! Please see my review comment. I think it'd be better to extend the \Magento\Shipping\Model\Carrier\AbstractCarrier::processAdditionalValidation and implement the validation for free shipping there. Then the algorithm will be similar to checking for applicable countries and consistend with existing design.

2018-12-06 16:58 UTC, sidolov commented
Hi @saravananvelu , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-12-06 16:58 UTC, closed without merging