17754-Fixed validation while creating new product attributes in admin
magento/magento2 pull request #17806
Opened 2018-08-27 05:16 UTC by saravananvelu

Fixed validation issues while creating the new product attribute in admin

### Description
Changed the validation logic to accept the alphabets in both lower and upper case formats

### Fixed Issues (if relevant)
1. magento/magento2#17754: Misleading error in Add Product Attribute screen

### Manual testing scenarios
1. Navigate to Admin -> Stores -> Products under Attributes
2. Create the new attribute with the code as Foo_Bar and click save
3. It should save without any error.

2018-08-27 05:17 UTC, magento-engcom-team commented
Hi @saravananvelu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-07 07:41 UTC, aleron75 requested changes

2018-09-07 07:41 UTC, aleron75 commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Save.php
> +                    ['pattern' => '/^[a-zA-Z\x{600}-\x{6FF}][a-zA-Z\x{600}-\x{6FF}_0-9]{0,30}$/u']
This is not the only place this kind of validation happens.
I know that this PR is for creating a product in admin but I think that we should be consistent with validation and apply it also to Web API, that is, in `\Magento\Catalog\Model\Product\Attribute\Repository::validateCode()`

2018-09-07 07:41 UTC, aleron75 commented on lib/web/mage/validation.js
> +                return $.mage.isEmptyNoTrim(v) || /^[a-zA-Z]+[a-zA-Z0-9_]+$/.test(v);
What about adding the `{0,30}` constraint also in the JavaScript regex? Just to be consistent with PHP validation.
Speaking of which, is it correct that the range starts at `0`? I think an empty attribute code shouldn't be allowed.

2018-09-19 04:25 UTC, saravananvelu commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Save.php
> +                    ['pattern' => '/^[a-zA-Z\x{600}-\x{6FF}][a-zA-Z\x{600}-\x{6FF}_0-9]{0,30}$/u']
Thanks for the update

2018-09-23 09:27 UTC, aleron75 approved these changes

2018-09-23 09:27 UTC, aleron75 approved these changes

2018-09-23 09:29 UTC, magento-engcom-team commented
Hi @aleron75, thank you for the review.
[ENGCOM-3029](https://jira.corp.magento.com/browse/ENGCOM-3029) has been created to process this Pull Request

2018-12-19 17:25 UTC, merged

2018-12-19 17:26 UTC, magento-engcom-team commented
Hi @saravananvelu. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.