Optimize code to remove phpmd suppress warnings
magento/magento2 pull request #17805
Opened 2018-08-26 18:47 UTC by arnoudhgz

### Description
By making the order of some checks more efficient the suppress warnings in these two files about CyclomaticComplexity and NPathComplexity.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-26 18:47 UTC, magento-engcom-team commented
Hi @arnoudhgz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-08-27 15:21 UTC, orlangur commented on app/code/Magento/Customer/Model/Metadata/Form/Text.php
> +     * @param StringUtils $stringHelper
It's better to avoid such changes, they should be done as separate efforts.

2018-08-29 17:01 UTC, arnoudhgz commented
@orlangur I updated the PR to only solve the suppress warnings issues, the import statements have been undone.

2018-09-21 08:00 UTC, ihor-sviziev requested changes
Hi @arnoudhgz,
In general - looks good, but there are some tests that are failing. Could you look into it?

2018-10-01 02:58 UTC, ihor-sviziev commented
Hi @arnoudhgz,
Will you be able to look at failing tests? Maybe you need some help? Of so - you can contact me at Slack

2018-10-01 12:54 UTC, arnoudhgz commented
@ihor-sviziev I think later this week I will look into it. Have been busy for a while.

2018-10-14 17:54 UTC, arnoudhgz commented
@ihor-sviziev I used a wrong method, it is solved now

2018-10-29 14:49 UTC, ihor-sviziev approved these changes

2018-10-29 14:50 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3326](https://jira.corp.magento.com/browse/ENGCOM-3326) has been created to process this Pull Request

2018-11-05 14:23 UTC, merged

2018-11-05 14:24 UTC, magento-engcom-team commented
Hi @arnoudhgz. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.