Sales: Add unit test for validator model class
magento/magento2 pull request #17876
Opened 2018-08-31 07:35 UTC by dmytro-ch

### Description
This PR adds missing unit test for:
``\Magento\Sales\Model\Validator``

### Fixed Issues
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-31 07:35 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-08-31 08:20 UTC, rogyar requested changes

2018-08-31 08:20 UTC, rogyar commented on app/code/Magento/Sales/Test/Unit/Model/ValidatorTest.php
> +
Please, remove the extra empty line

2018-08-31 08:25 UTC, dmytro-ch commented on app/code/Magento/Sales/Test/Unit/Model/ValidatorTest.php
> +
@rogyar, thank you! I've fixed it.

2018-09-04 10:03 UTC, merged

2018-09-04 10:05 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.