Feature/17705
magento/magento2 pull request #17936
Opened 2018-09-05 14:49 UTC by deefco

### Description

This patch should fix the issue described in #17705 
### Fixed Issues (if relevant)

1. magento/magento2#17705

2018-09-05 14:49 UTC, magento-engcom-team commented
Hi @deefco. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-06 08:04 UTC, rogyar requested changes

2018-09-06 08:04 UTC, rogyar commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +        if (!$billing->getCustomerAddressId() && $shippingAddress) {
The `$shippingAddress` variable might not be set at this point if all previous conditions are not set. We need to check if this variable is set.

2018-09-06 08:04 UTC, rogyar commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +
Please, remove this extra line

2018-09-06 11:21 UTC, deefco commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +        if (!$billing->getCustomerAddressId() && $shippingAddress) {
Changed to $shipping which will either be set to the shipping address or null which means we never enter the check.

2018-09-06 11:21 UTC, deefco commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +
Removed

2018-10-03 21:07 UTC, slavvka commented
hey @deefco, thank you fo the contribution! Please fix failed tests. they seem to be failing due to your changes. Also please consider covering the case fixed with a test.

2018-10-23 18:59 UTC, slavvka commented
Hey @deefco are you planning to complete this PR?

2018-11-19 09:46 UTC, VladimirZaets commented
Hi @deefco, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2018-11-19 09:46 UTC, closed without merging