Don't format Special Price value for Bundle Product
magento/magento2 pull request #17971
Opened 2018-09-07 14:55 UTC by magently

### Description
Pull Request solves the problem with incorrect rounding of Special Price in case of Bundle Product. In Bundle Products, Special Price is a percentage value, not a price that can be formatted (such as rounding).
The solution is not to format the value in this case as a price.

### Fixed Issues (if relevant)

1. magento/magento2#17638: Bundle Special Prices not correctly rounded

### Manual testing scenarios
Same as in the issue

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-07 14:55 UTC, magento-engcom-team commented
Hi @magently. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-08 10:06 UTC, rogyar requested changes

2018-09-08 10:06 UTC, rogyar commented on app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php
> +                        if ($this->locator->getProduct()->getTypeId() !== ProductType::TYPE_BUNDLE
By adding an additional complex condition here we increase the cyclomatic complexity of the method. This approach needs to be refactored (moved to a private method or so).

2018-09-08 10:06 UTC, rogyar commented on app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php
> +                            || $attribute->getAttributeCode() !== ProductAttributeInterface::CODE_SPECIAL_PRICE
So, we have the condition like "either if product type is bundle or the attribute is special price" which means that the condition is true for all special prices regardless of the product type?

2018-09-08 10:07 UTC, rogyar commented
Hi @magently. Thank you for your contribution. Please, consider fixing the mentioned issues

2018-09-14 09:19 UTC, magently commented
Hello @rogyar 

We fixed the cyclomatic complexity like you asked.

I hope it is more clear now. It will skip the price formatting only in case of special prices in bundle products.

2018-10-02 21:20 UTC, slavvka commented
Hey @magently I still can see cyclomatic complexity is 10. Please fix that
`/home/travis/build/magento/magento2/app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php:387	The method modifyData() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.`

2018-10-17 14:16 UTC, sidolov commented
Hi @magently , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-10-29 11:31 UTC, merged

2018-10-29 11:33 UTC, magento-engcom-team commented
Hi @magently. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.