Adding trimming sku value function to sku backend model.
magento/magento2 pull request #18019
Opened 2018-09-11 17:45 UTC by bartoszkubicki

### Description
I have added function to sku backend model which trimms value from whitespace.

### Fixed Issues (if relevant)

1. magento/magento2#<16572>: Trim whitespace on SKU when saving product

### Manual testing scenarios

1. Edit sku, by adding some whitespace
2. Save product.
3. Sku will be trimmed and saved in changed form.
4. Messsage that sku has been changed will be displayed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-11 17:46 UTC, magento-engcom-team commented
Hi @bartoszkubicki. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-14 05:20 UTC, ihor-sviziev commented
Hi @bartoszkubicki,
We already have PR for fixing the same issue and it looks absolutely different. https://github.com/magento/magento2/pull/16592

@VladimirZaets could you check this PR?

2018-09-14 20:38 UTC, bartoszkubicki commented
@ihor-sviziev Actuallly haven't noticed that. I looked at this PR, but I am not sure - adding `trim` function everywhere seems to be quite redundant, in my opinion backend model is proper place for validation/modyfing attribute value. It should cover most of use-cases, but actually I can't make sure it covers all.

2018-09-15 15:07 UTC, rogyar commented
@magento-engcom-team give me 2.3-develop instance

2018-09-15 15:07 UTC, magento-engcom-team commented
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2018-09-15 15:07 UTC, magento-engcom-team commented
Hi @rogyar, here is your [Magento instance](https://i-18019-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18019-2-3-develop.engcom.dev.magento.com/admin](https://i-18019-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2018-09-15 15:21 UTC, rogyar commented
@magento-engcom-team give me test instance

2018-09-15 15:21 UTC, magento-engcom-team commented
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

2018-09-15 15:22 UTC, magento-engcom-team commented
Hi @rogyar, here is your [new Magento instance](https://pr-18019.engcom.dev.magento.com).
Admin access: [https://pr-18019.engcom.dev.magento.com/admin](https://pr-18019.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

2018-09-15 15:36 UTC, rogyar commented
I found this solution more universal than in #16592
The only issue I found is when we create a configurable product with whitespace in SKU and generate child products (before the parent product is saved), the whitespace will be included in the child products SKU. However, the main issue is fixed

2018-09-15 15:37 UTC, rogyar requested changes

2018-09-15 15:37 UTC, rogyar commented on app/code/Magento/Catalog/Model/Product/Attribute/Backend/Sku.php
> +
Please, remove this extra line

2018-09-15 22:24 UTC, bartoszkubicki commented on app/code/Magento/Catalog/Model/Product/Attribute/Backend/Sku.php
> +
Done.

2018-09-15 23:42 UTC, bartoszkubicki commented
Maybe I could include fix also for not resolved case? I could modify summary.js, just like [here](https://github.com/magento/magento2/pull/16592/files)?
It is also possible to modify this:
Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/General.php:364

and add to array modyfing sku field some custom validation, but the problem is, that there is no rule for whitespace before and after the value.

2018-09-18 10:01 UTC, VladimirZaets approved these changes

2018-09-18 10:02 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-2998](https://jira.corp.magento.com/browse/ENGCOM-2998) has been created to process this Pull Request

2018-09-18 15:11 UTC, rogyar approved these changes

2018-09-18 15:12 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-2998](https://jira.corp.magento.com/browse/ENGCOM-2998) has been created to process this Pull Request

2018-09-19 09:44 UTC, bartoszkubicki commented
@magento-engcom-team Is it possible to add this fix to earlier Magento versions? Does it require my action or you can do it internally?

2018-10-27 10:18 UTC, merged

2018-10-27 10:19 UTC, magento-engcom-team commented
Hi @bartoszkubicki. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.