Add Missing Methods
magento/magento2 pull request #18066
Opened 2018-09-15 13:46 UTC by hryvinskyi

### Description
Add Missing Methods

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-15 13:46 UTC, magento-engcom-team commented
Hi @hryvinskyi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-15 13:51 UTC, ishakhsuvarov commented
Hi @hryvinskyi 
Why do you think that these methods are missing? Could you please provide more background for this fix?

Thank you

2018-09-15 14:27 UTC, hryvinskyi commented
Many of them are used in the code, but they are not explicitly implemented in the class. This does not allow you to write a plugin for them. And also, in my opinion, all methods should be explicit.

Sorry for my bad english :)

2018-10-17 22:38 UTC, orlangur requested changes

2018-10-17 22:38 UTC, orlangur commented on app/code/Magento/Quote/Model/Quote/Item/AbstractItem.php
> +        $this->setData('has-children', $status);
Such change is backward-incompatible, by the way...

I see `$this->setHasChildren(true);` in code, there is no need in explicit methods implementation, just add them as `@method` annotation.

2018-10-29 08:37 UTC, sidolov commented
Hi @hryvinskyi , I'm closing this event as not relevant according to comment from @orlangur. 
Thank you for the contribution!

2018-10-29 08:37 UTC, closed without merging