Fix bool scope config and update throws and update use clases
magento/magento2 pull request #18065
Opened 2018-09-15 11:35 UTC by hryvinskyi

### Description
Fix bool scope config
Update throws
Update use class

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-15 11:35 UTC, magento-engcom-team commented
Hi @hryvinskyi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-18 14:23 UTC, ihor-sviziev commented
Hi @hryvinskyi,
Please look at failed tests and adjust tests or your code.

2018-09-18 18:33 UTC, hryvinskyi commented
@magento-engcom-team give me test instance

2018-09-18 18:33 UTC, magento-engcom-team commented
Hi @hryvinskyi. Thank you for your request. I'm working on Magento instance for you

2018-09-18 18:34 UTC, magento-engcom-team commented
Hi @hryvinskyi, here is your [new Magento instance](https://pr-18065.engcom.dev.magento.com).
Admin access: [https://pr-18065.engcom.dev.magento.com/admin](https://pr-18065.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

2018-10-02 20:02 UTC, slavvka requested changes
Please fix the comments and other similar places

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/AdvancedSearch/Model/Recommendations/DataProvider.php
> +     * Get Items
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/CatalogInventory/Model/Configuration.php
> +     * Default Scope Id
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/Elasticsearch/Model/DataProvider/Suggestions.php
> +     * Get Items
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/Elasticsearch/Model/DataProvider/Suggestions.php
> +     * Is Results Count Enabled
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/GiftMessage/Model/GiftMessageConfigProvider.php
> +     * Get Config
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/NewRelicReporting/Model/Config.php
> +        return $this->scopeConfig->getValue('newrelicreporting/general/enable');
Why did you just remove type casting and leave the method `getValue` as is?

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/NewRelicReporting/Model/Config.php
> +        return $this->scopeConfig->getValue('newrelicreporting/cron/enable_cron');
The same

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/Store/Model/HeaderProvider/UpgradeInsecure.php
> +     * Whether the header should be attached to the response
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/Store/Model/HeaderProvider/Hsts.php
> +     * Whether the header should be attached to the response
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Set current default store
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Allow or disallow single store mode
The same

2018-10-02 20:02 UTC, slavvka commented on app/code/Magento/Wishlist/Model/Rss/Wishlist.php
> +     * Is Auth Required
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-02 20:02 UTC, slavvka commented on lib/internal/Magento/Framework/Session/SidResolver.php
> +            $this->_useSessionInUrl = $this->scopeConfig->getValue(
The same. You removed type casting and left the method intact

2018-10-03 13:17 UTC, hryvinskyi commented
@slavvka done

2018-10-03 15:56 UTC, slavvka requested changes
You probably missed some of my comments. Also there are the same changes that should be fixed. Please look through all your changes thoroughly and fix all them. Thank you!

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Customer/Ui/Component/DataProvider/Document.php
> -     * @inheritdoc
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Customer/Ui/Component/DataProvider/Document.php
> +     * Get Custom Attribute
You probably missed that

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Elasticsearch/Model/DataProvider/Suggestions.php
> +     * Is Results Count Enabled
You probably missed that

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Check if store has only one store view
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Check if system is run in the single store mode
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Retrieve application store object
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Retrieve stores array
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Retrieve application website object
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Get loaded websites
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Reinitialize store list
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Retrieve default store for default group and website
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Retrieve application store group object
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Prepare array of store groups
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 15:56 UTC, slavvka commented on app/code/Magento/Store/Model/StoreManager.php
> +     * Get assigned to website store
Please revert the comment and just remove curly braces `{}`. Please refer to the guide https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc

2018-10-03 16:32 UTC, hryvinskyi commented
@slavvka done

2018-10-03 16:55 UTC, slavvka commented
@hryvinskyi Thank you! Let's wait for the tests

2018-10-09 16:29 UTC, slavvka commented
hey @hryvinskyi you still have failing tests. Also please merge the latest mainline code and resolve the conflict.

2018-10-11 14:40 UTC, slavvka approved these changes

2018-10-11 14:42 UTC, magento-engcom-team commented
Hi @slavvka, thank you for the review.
[ENGCOM-3164](https://jira.corp.magento.com/browse/ENGCOM-3164) has been created to process this Pull Request

2018-10-16 14:46 UTC, merged

2018-10-16 14:47 UTC, magento-engcom-team commented
Hi @hryvinskyi. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

2018-10-16 15:46 UTC, slavvka commented
@hryvinskyi thank you. Could you please consider porting this PR to 2.2? Yuo can use the automatic tool https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool