#14530 Removing destroy current customer session command on reset password
magento/magento2 pull request #18078
Opened 2018-09-16 15:32 UTC by LucasCalazans

### Description
Removing the destroy current session command on reset password method. This was the [commit](https://github.com/magento/magento2/commit/772acf1f53036b313225300fe5e48e7f3af1c6a0#diff-5cd5a61664bf74a46f1e1bf261e3fdca) that has added this line, we don't necessarialy need to remove the current guest session, just the logged customer sessions to force the re-login on other computers.

### Fixed Issues (if relevant)
1. magento/magento2#14530: Shopping cart is emptied after reset password procedure

### Manual testing scenarios

1. Keep as a guest user (Without log in)
2. Add any product in the cart.
3. Proceed to reset the password.
4. Click on the email's URL to change your password.
5. Set a new password.
6. You will be redirected to the login page. At this moment the cart needs to keep the products that you have added.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-16 15:32 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18078) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18078) before we can accept your contribution.<br/>

2018-09-16 15:32 UTC, magento-engcom-team commented
Hi @LucasCalazans. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-16 15:33 UTC, LucasCalazans commented
@magento-engcom-team give me test instance

2018-09-16 15:33 UTC, magento-engcom-team commented
Hi @LucasCalazans. Thank you for your request. I'm working on Magento instance for you

2018-09-16 15:34 UTC, magento-engcom-team commented
Hi @LucasCalazans, here is your [new Magento instance](https://pr-18078.engcom.dev.magento.com).
Admin access: [https://pr-18078.engcom.dev.magento.com/admin](https://pr-18078.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

2018-09-18 14:08 UTC, ihor-sviziev commented
Here is PR that was fixing the same issue: https://github.com/magento/magento2/pull/17517

2018-09-19 13:41 UTC, phoenix128 commented
Checking if this PR may have unexpected security impacts.

2018-09-20 14:30 UTC, phoenix128 commented
@LucasCalazans , I am closing this PR because this is a duplicated PR of: https://github.com/magento/magento2/pull/17517 .

I wish to thank you anyway for your contribution and for your time.

2018-11-07 03:59 UTC, orlangur commented
Not sure why the dup wasn't reviewed though :D

2018-11-07 03:59 UTC, orlangur approved these changes

2018-11-07 04:03 UTC, orlangur requested changes
@LucasCalazans please check if original issue still reproduces after https://github.com/magento/magento2/commit/bc8d3d5d0ead9779cb22d19201cd731719a79b0c.

2018-11-22 10:48 UTC, sidolov commented
Hi @LucasCalazans , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-03 09:56 UTC, orlangur requested changes

2019-04-03 09:56 UTC, orlangur commented on app/code/Magento/Customer/Model/AccountManagement.php
>          $this->destroyCustomerSessions($customer->getId());
I don't think removing `destroy` is a right solution.

> Removed a code which were destroying session for current customer rather then for customer who requesting password reset

Can we destroy a proper session instead?

2019-04-30 18:47 UTC, sdzhepa commented
Hello @LucasCalazans @orlangur 

The initial Issue #14530 was fixed by Magento team.
Delivered to `2.3-develop` branch and should be available with **2.3.2 release**
Please see details in the next commits:

- a5635a2
- 02a65d0
- 4921f45
- 184191f
- a74b0c1

2019-04-30 18:47 UTC, closed without merging