Customer Name Prefix shows white space when extra separator is addes.…
magento/magento2 pull request #18077
Opened 2018-09-16 14:59 UTC by ivanbastos

… #17861

### Description
When we configure the Customer Name Prefix and leave at the end of the field the separator ";" Magento renders a white field. When we set the option with required is impossible leave the white field so I filter the values and clean the white option to have only the prefix defined

Honestly I believe that is not a bug but only a way to work with Magento. If you simple not ends the options with the separator the problem will not happens but once some users are not familiar with this logic I believe is better filter the options and remove the white spaces

### Fixed Issues (if relevant)
1. magento/magento2#17861: Customer Name Prefix shows white space when extra separator is addes.
2. Issue fixed: https://github.com/magento/magento2/issues/17861

### Manual testing scenarios
1. Enable the customer name prefix on Store>Configuration>Customer>Customer Configuration.
2. Go to Name and Address Option
3. Select in Show Prefix the option Required
4. Insert the prefixes desired in Prefix Dropdown Options using the separator ; and leave the ; at the end like (Mr;Ms;Mrs;)
5. Go to the frontend page and create a new user to see that the white option will not appear

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-16 14:59 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18077) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18077) before we can accept your contribution.<br/>

2018-09-16 15:00 UTC, magento-engcom-team commented
Hi @ivanbastos. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-21 08:39 UTC, dmanners commented
@ivanbastos thanks for this PR. I remember an older issue and PR with regards to this. I think we need to make sure that we can still add an empty option when we choose prefix as optional. If that is not the case with your code changes then I would suggest it will need to be updated.

Previous Issue: https://github.com/magento/magento2/issues/7241
Previous PR: https://github.com/magento/magento2/pull/11462

2018-09-28 13:50 UTC, sidolov commented
Hi @ivanbastos , please, take a look at comment from @dmanners 
Thanks!

2018-10-07 09:27 UTC, josefbehr commented
@magento-engcom-team give me test instance

2018-10-07 09:47 UTC, josefbehr commented
@magento-engcom-team give me test instance

2018-10-07 10:43 UTC, josefbehr commented
@ivanbastos I think this is not a bug, but intended behavior. It should be possible to have an empty option. But you're also right in that this is a problem if the field is set to required. Due to the PR @dmanners mentioned (https://github.com/magento/magento2/pull/11462), an empty option is added in the optional case automatically, so I do not see a problem filtering it out, in general. I'll just have to check that optional prefix/suffix still offers the empty option with your change.

2018-10-08 11:36 UTC, josefbehr commented
@dmanners @ivanbastos I just verified that this change does not break PR https://github.com/magento/magento2/pull/11462
After my requested change is implemented, I see no reason not to accept this PR.

2018-10-08 12:08 UTC, josefbehr requested changes

2018-10-08 12:08 UTC, josefbehr commented on app/code/Magento/Customer/Model/Options.php
> +            $result = array_filter($result);
Please move this outside the loop.

2018-10-29 08:29 UTC, sidolov commented
Hi @ivanbastos , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-10-29 08:29 UTC, closed without merging