18057: Fix adding switch options via API
magento/magento2 pull request #18114
Opened 2018-09-18 11:34 UTC by jakubderdziak

### Description
This change allows to create correct options in text swatch attribute via REST API or PHP.
### Fixed Issues (if relevant)
1. magento/magento2#18057: Swatch Text attributes options not created correctly via api

### Manual testing scenarios
For steps to reproduce, please check bug report: https://github.com/magento/magento2/issues/18057

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### TODO
That change will require update for unit tests.

2018-09-18 11:34 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18114) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18114) before we can accept your contribution.<br/><hr/>**Jakub Derdziak** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-09-18 11:34 UTC, magento-engcom-team commented
Hi @jakubderdziak. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-07 05:26 UTC, orlangur requested changes
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

2018-11-19 09:46 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-11-19 09:46 UTC, closed without merging

2019-02-11 18:18 UTC, rguedes commented
With this fix, can I create a Visual Swatch? How I upload the "image" ??