Clean code
magento/magento2 pull request #18124
Opened 2018-09-18 21:39 UTC by hryvinskyi

### Description
Just modify some code, and make it cleaner

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-18 21:40 UTC, magento-engcom-team commented
Hi @hryvinskyi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-19 08:08 UTC, sidolov requested changes

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Catalog/Ui/Component/ColumnFactory.php
> +	 * @param \Magento\Catalog\Api\Data\ProductAttributeInterface          $attribute
Please, remove extra spaces from doc block

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/CatalogUrlRewrite/Model/ObjectRegistry.php
> +     * Get
Please, add a comment that describes service method

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/CatalogUrlRewrite/Model/ObjectRegistry.php
> +     * List
Please, add a comment that describes service method

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Customer/Block/Adminhtml/Edit/Tab/View/Sales.php
> +	 * @param float    $price
Please, remove extra spaces from doc block

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Catalog/Ui/Component/ColumnFactory.php
> +	 * @param \Magento\Catalog\Api\Data\ProductAttributeInterface          $attribute
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Customer/Block/Adminhtml/Edit/Tab/View/Sales.php
> +	 * @param float    $price
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Fedex/Model/Carrier.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Remove extra spaces from the comment

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Remove extra spaces

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation and remove extra spaces

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
and remove extra spaces

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> +	 */
Please, check comment indentation

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Widget/Model/ResourceModel/Layout/Update.php
> +	 */
Please, check comment indentation and remove extra spaces

2018-09-19 08:08 UTC, sidolov commented on app/code/Magento/Widget/Model/ResourceModel/Layout/Update.php
> +	 */
Please, check comment indentation

2018-09-23 12:00 UTC, hryvinskyi commented
@sidolov done

2018-09-25 08:55 UTC, sidolov requested changes

2018-09-25 08:55 UTC, sidolov commented on app/code/Magento/ReleaseNotification/Ui/DataProvider/NotificationDataProvider.php
> +     * @return mixed
Please, revert changes related to @inheritdoc. Replace {@inheritdoc} with @inheritdoc

2018-09-25 08:55 UTC, sidolov commented on app/code/Magento/Sales/Model/Order/Address.php
> +     * Set Parent ID
Please, revert changes related to @inheritdoc. Replace {@inheritdoc} with @inheritdoc

2018-09-25 08:55 UTC, sidolov commented on app/code/Magento/Sales/Model/Order/Payment/Transaction.php
> +     * Set Transaction ID
Please, revert changes related to @inheritdoc. Replace {@inheritdoc} with @inheritdoc

2018-09-25 08:55 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> -     * {@inheritdoc}
Please, revert changes related to @inheritdoc. Replace {@inheritdoc} with @inheritdoc

2018-10-04 09:07 UTC, sidolov commented
Hi @hryvinskyi , will you continue progress with PR?

2018-10-04 19:21 UTC, hryvinskyi commented
@sidolov done

2018-10-08 15:54 UTC, sidolov requested changes

2018-10-08 15:54 UTC, sidolov commented on app/code/Magento/ReleaseNotification/Ui/DataProvider/NotificationDataProvider.php
> -     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
Removing this annotation will cause static test failures because parameters are not used in the method.

2018-10-08 15:54 UTC, sidolov commented on app/code/Magento/ReleaseNotification/Ui/DataProvider/NotificationDataProvider.php
> -     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
Removing this annotation will cause static test failures because parameters are not used in the method.

2018-10-08 15:54 UTC, sidolov commented on app/code/Magento/Sales/Model/Order/Address.php
> -     * @param \Magento\Sales\Api\Data\OrderAddressExtensionInterface $extensionAttributes
Please, don't remove type hints for the method because the parent method has annotation with generic interface

2018-10-08 15:54 UTC, sidolov commented on app/code/Magento/Sales/Model/Order/Payment/Transaction.php
> -     * @return \Magento\Sales\Api\Data\TransactionExtensionInterface|null
Please, don't remove type hints for the method because the parent method has annotation with generic interface

2018-10-08 15:54 UTC, sidolov commented on app/code/Magento/Store/Model/Store.php
> -     * @since 100.1.0
Please, revert back the @since tag

2018-11-14 14:06 UTC, sivaschenko requested changes
Please return the deleted phpdoc annotations

2018-11-14 14:06 UTC, sivaschenko commented on app/code/Magento/Sales/Model/Order/Payment/Transaction.php
> -     * @param \Magento\Sales\Api\Data\TransactionExtensionInterface $extensionAttributes
Please revert the param and return annotation for phpdoc

2018-11-14 14:06 UTC, sivaschenko commented on app/code/Magento/Sales/Model/Order/Address.php
> -     * @return \Magento\Sales\Api\Data\OrderAddressExtensionInterface|null
Please revert the return annotation for phpdoc

2018-11-14 14:08 UTC, sivaschenko commented
Hi, @hryvinskyi , please resolve the code review notes, fix the Travis build (static tests fails) and resolve the conflicts on your branch, so that we can process your pull request!

2018-11-26 12:12 UTC, sivaschenko approved these changes

2018-11-26 12:13 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3567](https://jira.corp.magento.com/browse/ENGCOM-3567) has been created to process this Pull Request

2018-12-12 20:42 UTC, merged

2018-12-12 20:43 UTC, magento-engcom-team commented
Hi @hryvinskyi. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.