Fixed issue with Swatches not showing when product is out of stock an…
magento/magento2 pull request #18184
Opened 2018-09-21 16:08 UTC by abhaykhatariya

…d in backend configuration it is set to display out of stock product yes

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-21 16:08 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18184) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18184) before we can accept your contribution.<br/><hr/>**Abhay Khatariya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-09-21 16:08 UTC, magento-engcom-team commented
Hi @abhaykhatariya. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-21 16:38 UTC, abhaykhatariya commented
@magento-admin @magento-engcom-team 
Please review my commit and let me know if you need further details.

2018-09-23 15:54 UTC, abhaykhatariya commented
@engcom-backlog-nazar 
Hello can you please review and let me know what i have to push ?

2018-10-06 12:09 UTC, josefbehr commented
@abhaykhatariya Thanks for your contribution. Can you please fix the failing tests?

2018-10-06 18:32 UTC, abhaykhatariya commented
@josefbehr 
Yes I will do it soon

2018-10-29 08:25 UTC, sidolov requested changes

2018-10-29 08:25 UTC, sidolov commented on app/code/Magento/ConfigurableProduct/Block/Product/View/Type/Configurable.php
> -class Configurable extends \Magento\Catalog\Block\Product\View\AbstractView
Please, revert code style changes for this file

2018-10-29 08:25 UTC, sidolov commented on app/code/Magento/ConfigurableProduct/Plugin/Model/ResourceModel/Attribute/InStockOptionSelectBuilder.php
> +        StockConfigurationInterface $stockConfiguration
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2018-11-14 13:48 UTC, sivaschenko commented
@abhaykhatariya can you please resolve the code review comments and sign the [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18184) so we can process this pull request

2018-11-14 16:10 UTC, abhaykhatariya commented
@sivaschenko Sure will do this week and update you here

2019-01-17 15:08 UTC, sivaschenko commented
Hi @abhaykhatariya I am closing this pull request due to inactivity. Feel free to reopen should you wish to continue progress on this contribution

2019-01-17 15:08 UTC, closed without merging