Changes for shopby block on category is still present also mode is to just show static block
magento/magento2 pull request #18301
Opened 2018-09-28 10:46 UTC by priti2jcommerce

### Description

### Fixed Issues (if relevant)

### Manual testing scenarios

2018-09-28 10:46 UTC, magento-engcom-team commented
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-09-28 12:24 UTC, sidolov commented
Hi @priti2jcommerce , please, fill PR template to understand the purpose of the changes and steps for the issue that you are trying to resolve. 
Thank you!

2018-09-28 12:29 UTC, priti2jcommerce commented
Hi @sidolov ,

Please check I have updated PR template please check and process accordingly.

Thank You!

2018-11-06 18:24 UTC, sivaschenko requested changes
The fix is straight, however there is a change to json translation preprocessor that I cannot map to the ticket. Also, the fix is applied to a single template rather than to block in general.

Please review the individual comments in the code.

2018-11-06 18:24 UTC, sivaschenko commented on app/code/Magento/Translation/Model/Json/PreProcessor.php
> +            $area->load(\Magento\Framework\App\Area::PART_DESIGN);
Can you please explain how this change is related to the ticket?

2018-11-06 18:24 UTC, sivaschenko commented on app/code/Magento/Catalog/view/frontend/templates/navigation/left.phtml
> +<?php if($block->canShowBlock()):?>
Ideally, I would do this check inside the block class _toHtml method body to prevent the block from rendering despite of the template used for it.

2018-11-06 18:26 UTC, sivaschenko commented
Hi @priti2jcommerce , thanks for collaboration! Please take a look at the code review notes. Looking forward to your updates/response!

2018-11-07 06:12 UTC, orlangur requested changes
Why this implementation differ from https://github.com/magento/magento2/commit/39e0fd9a5366a6d25bc3b9f9ae324aa9be026cb9 `2.2.x` fix?

2018-11-09 07:41 UTC, priti2jcommerce reviewed
Hi @orlangur ,
this changes for
the shop by category navigation is not shown - as there are no products shown in the category just a cms block.

2018-11-09 07:41 UTC, priti2jcommerce commented on app/code/Magento/Translation/Model/Json/PreProcessor.php
> +            $area->load(\Magento\Framework\App\Area::PART_DESIGN);
Hi @sivaschenko ,
This changes are not related to this ticket.

2018-11-09 15:01 UTC, sivaschenko requested changes
Please remove changes that are not related to the case

2018-11-09 15:01 UTC, sivaschenko commented on app/code/Magento/Translation/Model/Json/PreProcessor.php
> +            $area->load(\Magento\Framework\App\Area::PART_DESIGN);
Hi @priti2jcommerce , please remove this chananges then

2018-11-13 07:31 UTC, priti2jcommerce reviewed
Unwanted code has been removed

2018-11-13 07:31 UTC, priti2jcommerce commented on app/code/Magento/Translation/Model/Json/PreProcessor.php
> +            $area->load(\Magento\Framework\App\Area::PART_DESIGN);
Hi @sivaschenko ,

changes has been removed, Please check .

2018-11-13 10:18 UTC, sivaschenko commented
@priti2jcommerce please take a look at @orlangur code review comment. I think the fix in https://github.com/magento/magento2/commit/39e0fd9a5366a6d25bc3b9f9ae324aa9be026cb9 is more appropriate for the issue. I think it will make sense to port that commit to 2.3-develop branch

2018-11-13 11:55 UTC, priti2jcommerce commented
Hi @sivaschenko ,

Yes I have applied changes accordingly to @orlangur  code review comment. As per his recommendation changes made in block rather than to manage from phtml file and merge in 2.3-develop branch can you please check further and let me know.

2018-11-13 12:35 UTC, orlangur commented
@priti2jcommerce,

> the fix in 39e0fd9 is more appropriate for the issue. I think it will make sense to port that commit to 2.3-develop branch

Please rewrite all commits in current branch with cherry pick of that commit.

2018-11-14 07:01 UTC, priti2jcommerce commented
Hi @orlangur ,

Yes ,I have merged the changes of  #39e0fd9 to my current working branch and pushed on 2.3-develop branch. Please check and let me know.

2018-11-14 11:47 UTC, sivaschenko requested changes
Thank you for adding the fix for \Magento\LayeredNavigation\Block\Navigation. Please fix the code styles according to PSR2.

2018-11-14 11:47 UTC, sivaschenko commented on app/code/Magento/LayeredNavigation/Test/Unit/Block/NavigationTest.php
> +use Magento\Catalog\Model\Category;
There MUST be one blank line after the namespace declaration, and there MUST be one blank line after the block of use declarations. https://www.php-fig.org/psr/psr-2/

2018-11-14 11:47 UTC, sivaschenko commented on app/code/Magento/Catalog/Block/Navigation.php
> +        return parent::_toHtml();
```suggestion
        return $this->canShowBlock() ? parent::_toHtml() : '';
```

2018-11-14 11:47 UTC, sivaschenko commented on app/code/Magento/Catalog/Block/Navigation.php
> +        return $displayMode ;
```suggestion
        return $this->getCurrentCategory()->getDisplayMode() != \Magento\Catalog\Model\Category::DM_PAGE;
```

2018-11-14 11:47 UTC, sivaschenko commented on app/code/Magento/Catalog/Block/Navigation.php
> -
There should be a blank line between function declarations

2018-11-14 11:47 UTC, sivaschenko commented on app/code/Magento/LayeredNavigation/Block/Navigation.php
> +        return $this->getLayer()->getCurrentCategory()->getDisplayMode() !== \Magento\Catalog\Model\Category::DM_PAGE
Please fix the styles and ensure lines does not exceed the 120 character limit https://www.php-fig.org/psr/psr-2/#1-overview

2018-11-14 12:31 UTC, priti2jcommerce commented
Hi @sivaschenko ,

Made the changes as per suggested, Please check

2018-11-14 12:41 UTC, sivaschenko requested changes

2018-11-14 12:41 UTC, sivaschenko commented on app/code/Magento/LayeredNavigation/Block/Navigation.php
> +        return $this->getLayer()->getCurrentCategory()->getDisplayMode() !== \Magento\Catalog\Model\Category::DM_PAGE;
@priti2jcommerce I think both conditions should be checked here: display mode and visibility flag

2018-11-14 12:42 UTC, sivaschenko commented
@priti2jcommerce thank you for your fixes! However, there is still one review comment that needs your attention

2018-11-14 14:18 UTC, priti2jcommerce commented
Hi @sivaschenko ,

Please check now..

2018-11-14 14:47 UTC, sivaschenko commented
Thanks for your updates, @priti2jcommerce . The functionality looks fine, however, there are no code style updates in your latest commit. Please fix the code styles to avoid static tests fails.

2018-11-14 17:32 UTC, orlangur commented
@priti2jcommerce please read https://github.com/magento/magento2/pull/18301#issuecomment-438250792 again. I see 7 commits in PR currently while here should be only one properly authored commit.

2018-11-15 09:53 UTC, priti2jcommerce commented
Hi @sivaschenko ,

Please check made the changes for it.

2018-11-15 12:44 UTC, sivaschenko commented
@priti2jcommerce please see my commits with formatting fixes required to comply with standards and our policies. Please [squash](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) all the commits (yours and mine) to a single commit to make it solid and clean.

@orlangur I think it makes sence to provide fix for `Magento\Catalog\Block\Navigation` (included in this pull request) in addition to changes introduced in https://github.com/magento/magento2/commit/39e0fd9a5366a6d25bc3b9f9ae324aa9be026cb9 as that block is also responsible for rendering left hand navigation.

2018-11-15 14:06 UTC, priti2jcommerce commented
Hi @sivaschenko 

Could you please guide how I can pull your commits in my repository to squash them.

2018-11-15 14:17 UTC, sivaschenko commented
@priti2jcommerce My commits are already in your repository: https://github.com/priti2jcommerce/magento2/commits/changes-for-shopby-block-on-category-is-still-present-also-mode-is-to-just-show-static-block

2018-11-16 08:11 UTC, priti2jcommerce commented
Hi @sivaschenko ,

I have squashed your commits
Please  check

2018-11-16 12:59 UTC, sivaschenko commented
@orlangur please approve changes if you are happy with the pull request

2018-11-16 13:52 UTC, orlangur commented
@priti2jcommerce I don't see squashed commits. Probably you did it locally but didn't perform a force push?

Again, in this PR there must be cherry pick of https://github.com/magento/magento2/commit/39e0fd9a5366a6d25bc3b9f9ae324aa9be026cb9 authored by @RomaKis, cherry picks of any other relevant commits from `2.2-develop` and all other changes needed for `2.3-develop` as a separate commit.

Without such branch history fix PR cannot be merged.

2019-01-11 07:04 UTC, closed without merging

2019-01-11 13:41 UTC, orlangur commented
@priti2jcommerce do you need any help with rewriting branch history maybe?