Support of error pages behind a load balancer that serves HTTPS
magento/magento2 pull request #18333
Opened 2018-10-01 20:40 UTC by stkams

Support of error pages behind a load balancer that serves HTTPS but accesses the webserver on HTTP. Without this css is loaded on HTTP from a document loaded over HTTPS

### Description

If you run magento on webservers serving on HTTP while the loadbalancer serves on HTTPS then base is set to a URL using HTTP which the page is HTTPS. The css is then blocked by browsers.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-01 20:40 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18333) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18333) before we can accept your contribution.<br/><hr/>**stefank** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-10-03 14:48 UTC, ihor-sviziev requested changes

2018-10-03 14:48 UTC, ihor-sviziev commented on pub/errors/processor.php
> +        // HTTP_X_FORWARDED_PROTO to check whether a webserver using HTTP is behind a load balancer serving HTTPS
I think comment is not needed there, it's pretty obvious for what this header is needed.

2018-10-03 14:48 UTC, ihor-sviziev commented on pub/errors/processor.php
> +        $isSecure = (!empty($_SERVER['HTTPS'])) && ($_SERVER['HTTPS'] != 'off') || $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https';
Please add checking that `$_SERVER['HTTP_X_FORWARDED_PROTO']` exists, otherwise we'll have notice there

2018-10-03 14:53 UTC, ihor-sviziev commented
Hi @stkams,

Could you sign CLA? In case if you already signed CLA, but commit was done from your another email - please add this email to your github account and sign CLI.

Unfortunately we can't accept PRs from people who didn't signed CLA.

2018-10-03 15:18 UTC, stkams commented
Thanks for the review. All done

2018-10-04 02:50 UTC, ihor-sviziev commented
Hi @stkams did you signed CLA?
Also looks like this changed by you file failing in static tests, could you fix it?

2018-10-04 10:48 UTC, stkams commented
Yes, I signed the CLA using my hotmail email address

2018-10-04 10:54 UTC, ihor-sviziev commented
Hi @stkams your commits contains email no in Hotmail. Please add that email as secondary in your github account

2018-10-07 05:48 UTC, ihor-sviziev approved these changes

2018-10-12 09:00 UTC, ihor-sviziev approved these changes

2018-10-12 09:02 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3170](https://jira.corp.magento.com/browse/ENGCOM-3170) has been created to process this Pull Request

2018-10-12 09:02 UTC, magento-engcom-team commented
@stkams thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-10-25 15:22 UTC, merged

2018-10-25 15:23 UTC, magento-engcom-team commented
Hi @stkams. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.