Resolve typo despatch event
magento/magento2 pull request #18372
Opened 2018-10-04 07:03 UTC by neeta-wagento

### Description

### Fixed Issues (if relevant)

1. magento/magento2#18355: Typo in dispatched event name

### Manual testing scenarios

1.  method Magento\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider::getSearchableAttributes dispatches event with typo in its name
2. catelogsearch_searchable_attributes_load_after
instead of
catalogsearch_searchable_attributes_load_after

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-04 07:03 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18372) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18372) before we can accept your contribution.<br/>**2** out of **13** committers have signed the CLA.<br/><br/>:white_check_mark: magento-engcom-team<br/>:white_check_mark: dmytro-ch<br/>:x: svitja<br/>:x: StasKozar<br/>:x: DianaRusin<br/>:x: zakdma<br/>:x: dmitriyprime<br/>:x: OlgaVasyltsun<br/>:x: Nikita Fomin<br/>:x: aakimov<br/>:x: mastiuhin-olexandr<br/>:x: rostyslav-hymon<br/>:x: Stas Puga<hr/>**Nikita Fomin, Stas Puga** seem not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-10-04 07:43 UTC, orlangur commented
Unfortunately such change is not allowed: https://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#magento-apis

Checking in Slack whether it's possible to introduce a new event deprecating this one.

2018-10-05 07:20 UTC, neeta-wagento commented
@orlangur  Hello, Is there any update on this?

2018-10-17 13:25 UTC, orlangur requested changes

2018-10-17 13:25 UTC, orlangur commented on app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Action/DataProvider.php
> +                'catalogsearch_searchable_attributes_load_after',
As event cannot be removed, add a comment near old one that it is deprecated and add one more event dispatching, with corrected name.

2018-10-19 06:20 UTC, neeta-wagento commented on app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Action/DataProvider.php
> +                'catalogsearch_searchable_attributes_load_after',
@orlangur Thankyou for review. I have added add a comment near old one that it is deprecated and add one more event dispatching, with corrected name.

2018-10-27 13:26 UTC, orlangur requested changes

2018-10-27 13:26 UTC, orlangur commented on app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Action/DataProvider.php
> +                'catalogsearch_searchable_attributes_load_after',
After the change, old event must still be dispatched.

Also, do not specify version near deprecation tag, it is done automatically when needed.

2018-10-29 15:20 UTC, orlangur approved these changes

2018-10-29 15:22 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3327](https://jira.corp.magento.com/browse/ENGCOM-3327) has been created to process this Pull Request

2018-10-31 11:36 UTC, merged

2018-10-31 11:37 UTC, magento-engcom-team commented
Hi @neeta-wagento. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.