added config for newsletter in frontend
magento/magento2 pull request #18407
Opened 2018-10-05 20:33 UTC by torhoehn

### Description

Until now there wasn't a config field to hide newsletter elements from frontend. I orientated at the wishlist module, because for wishlist it was already possible.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. Open Backend
2. Go to Stores -> Configuration -> Customers -> Newsletter
3. Set 'Enabled' to 'No'
4. Newsletter will be hidden from footer, customer registration, customer account and customer account sidebar

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-06 10:45 UTC, larsroettig requested changes

2018-10-06 10:45 UTC, larsroettig commented on app/code/Magento/Customer/Block/Form/Register.php
> +        if ($this->_moduleManager->isOutputEnabled('Magento_Newsletter')
Pls Replace  this function with this impl.
```php

 /**
     * Newsletter module availability
     *
     * @return bool
     */
    public function isNewsletterEnabled()
    {
        return $this->_moduleManager->isOutputEnabled('Magento_Newsletter')
            && $this->getConfig('newsletter/general/active');
    }

```

2018-10-06 10:46 UTC, larsroettig commented
Hi @torhoehn,
for your contribution currently the unit tests are failed can you fix this this ?

best regards,

Lars

2018-10-07 11:08 UTC, torhoehn commented
@larsroettig The functional test could not start correctly I think, but the rest looks fine for me now.

2018-10-08 11:58 UTC, larsroettig commented
@torhoehnI restarted the test if it is done I will check again

2018-10-08 12:41 UTC, larsroettig approved these changes

2018-10-08 12:42 UTC, magento-engcom-team commented
Hi @larsroettig, thank you for the review.
[ENGCOM-3134](https://jira.corp.magento.com/browse/ENGCOM-3134) has been created to process this Pull Request

2018-10-09 12:23 UTC, sidolov commented
Hi @torhoehn , we found one more scenario that should be covered in scope of the provided changes: 

**Steps:**
1. Create User 'John'
2. Disable Newsletter Subscription
3. Login as John
4. Navigate to /newsletter/manage/ directly on the browser

 **Expected:**
404 - Page not found

 **Actual:**
Newsletter Subscription page opens

2018-10-09 18:18 UTC, torhoehn commented
@sidolov I‘ll implement this later this month.

2018-10-25 06:56 UTC, sidolov commented
Hi @torhoehn , will you continue progress with PR?

2018-10-25 08:06 UTC, torhoehn commented
@sidolov Yes, I'm just back from vacation.

2018-10-29 08:23 UTC, sidolov requested changes

2018-10-29 08:23 UTC, sidolov commented on app/code/Magento/Newsletter/Observer/PredispatchNewsletterObserver.php
> +class PredispatchNewsletterObserver implements \Magento\Framework\Event\ObserverInterface
Please, cover new logic with unit test

2018-11-14 14:14 UTC, sivaschenko commented
Hi @torhoehn , are you going to continue the progress with this PR?

2018-11-16 19:17 UTC, torhoehn commented
@sivaschenko Yes, I'm just a little stuck with the unit test.

2018-11-16 20:16 UTC, sivaschenko commented
@torhoehn great! Feel free to contact me in slack if you need any help with the unit tests

2018-11-22 08:12 UTC, sivaschenko requested changes
Thanks for collaboration! Can you please fix the code styles to comply with PSRs and be consistent with the codebase

2018-11-22 08:12 UTC, sivaschenko commented on app/code/Magento/Customer/Block/Form/Register.php
> +            && $this->getConfig('newsletter/general/active');
it would be nice to have a constant that stores 'newsletter/general/active'

2018-11-22 08:12 UTC, sivaschenko commented on app/code/Magento/Customer/Test/Unit/Block/Form/RegisterTest.php
> +     * @param $isNewsletterActive
Please add the parameter types

2018-11-22 08:12 UTC, sivaschenko commented on app/code/Magento/Newsletter/Observer/PredispatchNewsletterObserver.php
> +namespace Magento\Newsletter\Observer;
There should be a blank line before the namespace declaration

2018-11-22 08:12 UTC, sivaschenko commented on app/code/Magento/Newsletter/Test/Unit/Observer/PredispatchNewsletterObserverTest.php
> +namespace Magento\Newsletter\Test\Unit\Observer;
Please add a blank line before the namespace

2018-11-22 08:12 UTC, sivaschenko commented on app/code/Magento/Newsletter/Test/Unit/Observer/PredispatchNewsletterObserverTest.php
> +                                 ->disableOriginalConstructor()
Please fix the indentation, see other tests in the code base for example

2018-11-22 08:12 UTC, sivaschenko commented on app/code/Magento/Newsletter/Test/Unit/Observer/PredispatchNewsletterObserverTest.php
> +                'url'         => $this->urlMock
```suggestion
                'url' => $this->urlMock
```

2018-11-22 18:16 UTC, sivaschenko requested changes

2018-11-22 18:16 UTC, sivaschenko commented on app/code/Magento/Customer/Block/Form/Register.php
> +    private const XML_PATH_NEWSLETTER_ACTIVE = 'newsletter/general/active';
The reason for adding a constant is mostly to easily reuse the config path in the code base, so I think it should be public. It should be used to replace all the `newsletter/general/active` occurrences in PHP code. And probably the newsletter observer would be a better place to put this constant to, as it is closer to newsletter than to customer module

2018-11-22 18:40 UTC, sivaschenko approved these changes

2018-11-22 18:42 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3134](https://jira.corp.magento.com/browse/ENGCOM-3134) has been created to process this Pull Request

2018-12-12 19:05 UTC, torhoehn commented
@magento-engcom-team What kind of response is needed here?

2018-12-12 22:45 UTC, sivaschenko commented
Hi @torhoehn sorry, looks like I forgot to remove the "needs update" label.

2019-01-07 19:16 UTC, merged

2019-01-07 19:17 UTC, magento-engcom-team commented
Hi @torhoehn. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.