[BACKPORT] type casted $qty to float in \Magento\Catalog\Model\Produc…
magento/magento2 pull request #18424
Opened 2018-10-06 16:14 UTC by lewisvoncken

…t::setQty()

type casted $qty to float in \Magento\Catalog\Model\Product::setQty()

### Description
Backport PR #18149

 \Magento\Catalog\Model\Product::getQty() should return float/double now, as mentioned in it's Doc-block 

### Fixed Issues (if relevant)
1. magento/magento2#18094: Should getQty() return int/float or string?

### Manual testing scenarios

1. Observe any event like `checkout_cart_product_add_after`
2. In the Observer, get an instance of `\Magento\Catalog\Model\Product`
3. Calling the `getQty` method of the above-mentioned class would return a `float`/`double` instead of `string`, as expected

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-07 10:10 UTC, okorshenko requested changes

2018-10-07 10:10 UTC, okorshenko commented on app/code/Magento/Catalog/Model/Product.php
> +            $this->setData('qty', (float)$qty);
Hi @lewisvoncken 
Could you please consider discussion about setters from this PR https://github.com/magento/magento2/pull/18149

2018-10-19 19:03 UTC, okorshenko commented on app/code/Magento/Catalog/Model/Product.php
> +            $this->setData('qty', (float)$qty);
fixed

2018-10-19 19:03 UTC, okorshenko approved these changes

2018-10-19 19:04 UTC, magento-engcom-team commented
Hi @okorshenko, thank you for the review.
[ENGCOM-3230](https://jira.corp.magento.com/browse/ENGCOM-3230) has been created to process this Pull Request

2018-10-23 17:02 UTC, merged

2018-10-23 17:03 UTC, magento-engcom-team commented
Hi @lewisvoncken. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.