[#2291]:+ fixed inconsistent plugin placement.
magento/magento2 pull request #18450
Opened 2018-10-08 08:08 UTC by StevenGuapaBV

Moved all the plugins to have Plugins folder as root. Fixed folder structure for plugins to be placed in a root Plugin folder. Also removed duplicate plugins in adminhtml di which were already present in etc/di

### Description
To be consistent in the location where plugins are kept I updated the module CatalogUrlRewrite where a some model plugins where not in the Plugins root folder. 

### Fixed Issues (if relevant)
1. magento/magento2#2291: Inconsistent location for plugins

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-10 17:26 UTC, miguelbalparda approved these changes

2018-10-11 08:44 UTC, sidolov requested changes

2018-10-11 08:44 UTC, sidolov commented on app/code/Magento/Customer/view/frontend/templates/widget/name.phtml
> -        <div class="fields">
Looks like this changes are not related to the PR. Please, revert

2018-10-18 06:17 UTC, StevenGuapaBV commented
Hi @sidolov,

I reverted the change.

2018-10-22 09:03 UTC, sidolov approved these changes

2018-10-23 08:58 UTC, sidolov commented
Hi @StevenGuapaBV , unit tests place should be consistent with plugins place,  please, move tests according to new plugin namespace

2018-11-06 09:24 UTC, sidolov commented
Hi @StevenGuapaBV , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-11-06 09:24 UTC, closed without merging