Add x-www-form-urlencoded content type for ApiRest request
magento/magento2 pull request #18463
Opened 2018-10-08 12:54 UTC by i4rebecamartinez

### Description

Content type x-www-form-urlencoded for API Rest calls are not allowed as Magento does not have any deserializer.

### Proposed solution

Add new deserializer class for this type of request, and include new type in deserializers argument of Magento\Framework\Webapi\Rest\Request\DeserializerFactory.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-08 12:54 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18463) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18463) before we can accept your contribution.<br/>

2018-10-08 13:48 UTC, misha-kotov commented
@i4rebecamartinez can you elaborate on the use cases and the impact of this issue? it's not very clear from the description.

2018-10-27 06:33 UTC, sidolov commented
Hi @i4rebecamartinez , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-11-13 15:11 UTC, paulpartington-cti commented
I have recently come across a need for this were we provided an API endpoint for a payment gateway to notify us of order statuses. Unfortunately I had no control of the headers they sent in their updates and the API would throw a 500 error when the header was `application/x-www-form-urlencoded`.

I brought this change into my project and it worked.

I'd like to re-open this PR as it would be a useful change to incorporate.

2020-02-10 12:58 UTC, novikor commented
Hi, @i4rebecamartinez ! Thank you for your contribution.
Please sign the Adobe CLA

2020-02-11 08:47 UTC, novikor requested changes
Good job, @i4rebecamartinez !
Please check my comments.

It seems that the changes must be covered with [WebApi](Magento\Framework\Webapi\Rest\Request\DeserializerInterface) tests.

What do you think about implementing the test coverage and updating the description with more specific steps to reproduce?

2020-02-11 08:47 UTC, novikor commented on lib/internal/Magento/Framework/Webapi/Rest/Request/Deserializer/FormUrlencoded.php
> + * Class FormUrlencoded
It seems that the class PHPDoc could be removed or replaced by its description

2020-02-11 08:47 UTC, novikor commented on lib/internal/Magento/Framework/Webapi/Rest/Request/Deserializer/FormUrlencoded.php
> + */
Please use strict type mode [(1.3.1)](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#1-basic-programming-principles)

2020-06-04 06:21 UTC, ihor-sviziev commented
Please also use \Laminas\ instead of \Zend\

2020-06-04 06:36 UTC, ihor-sviziev commented
Hi @i4rebecamartinez @paulpartington-cti,

In case if you need to get some requests from external services you have two options:
1. implement API endpoint and client should correctly use it
2. implement controller that will handle requests from external system, and you could put any logic in here
3. you could apply such change in your custom extension, if you really need it

Looks like you tried to do 1st option, but client wasn't correctly using it. So in this case you need to switch to 2nd option.

Personally I don't think such change should be merged to Magento and also this PR and original issue were created in 2018 and didn't get any attention from community - so it means it's not frequent issue that will be helpful for many people, but will definitely additional cases -> will increase complexity and potentially new issues could appear because of that.

Thank you for understanding. If you'll have any other use cases - please feel free to describe them.

2020-06-04 06:36 UTC, closed without merging