Added option to exclude discount amount from minimum order amount calculation
magento/magento2 pull request #18524
Opened 2018-10-11 10:09 UTC by ccasciotti

### Description

This PR adds option for store manager to include or exclude discount amount from minimum order amount calculation. Sometimes client wants to exclude discount amount from minimum order and want that only subtotal is used. The default option is set to "Yes" so Magento will use the current behavior.

### Fixed Issues (if relevant)

none

### Manual testing scenarios

1. Access backend
2. Go to Stores > Configuration > Sales > Sales > Minimum Order Amount
3. Leave "Yes" in "Include Discount Amount" field to test normal behavior.
4. Set "No" in "Include Discount Amount" field to test new behavior without discount.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-11 10:09 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18524) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18524) before we can accept your contribution.<br/>

2018-10-23 08:21 UTC, ccasciotti commented
@magento-engcom-team give me test instance

2018-10-23 08:21 UTC, magento-engcom-team commented
Hi @ccasciotti. Thank you for your request. I'm working on Magento instance for you

2018-10-23 08:22 UTC, magento-engcom-team commented
Hi @ccasciotti, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18524/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18524//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18524//admin)
Login: `admin` Password: `123123q`

2018-10-23 22:17 UTC, ccasciotti commented
@magento-engcom-team manual test was successful, please review code

2018-11-07 05:27 UTC, orlangur requested changes
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

2019-01-28 08:30 UTC, ccasciotti commented
Hi @orlangur,
I've ported the change request's commit of the merged #19136 PR here, you can review code and eventually unlock this PR for the `2.2-develop`.

Thanks.

2019-01-28 16:23 UTC, sidolov approved these changes

2019-01-28 16:24 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-3986](https://jira.corp.magento.com/browse/ENGCOM-3986) has been created to process this Pull Request

2019-02-11 16:36 UTC, merged