Update documentation for Order#getAppliedRuleIds
magento/magento2 pull request #18573
Opened 2018-10-12 20:07 UTC by zack6849

### Description (*)
Update the documentation for getAppliedRuleIds, as it is not immediately clear if this is a single number in a string, or several that are comma separated.

### Manual testing scenarios (*)
- Attempt to getAppliedRuleIds on an OrderInterface object
- Consult the documentation, and see it contains a string
- Scratch your head because you're not sure if it can contain multiple IDs or not, and if so how they're separated 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-12 20:07 UTC, magento-engcom-team commented
Hi @zack6849. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-15 11:09 UTC, rodrigowebjump requested changes

2018-10-15 11:09 UTC, rodrigowebjump commented on app/code/Magento/Sales/Api/Data/OrderInterface.php
> +     * Rules are comma separated if there are more than one.
Please include a blank line before or add the "(comma separated)" information in return line, removing this one.

2018-10-15 11:09 UTC, rodrigowebjump commented on app/code/Magento/Sales/Api/Data/OrderItemInterface.php
> +     * Rules are comma separated if there are more than one.
Please include a blank line before or add the "(comma separated)" information in return line, removing this one.

2018-10-15 11:09 UTC, rodrigowebjump commented on app/code/Magento/Sales/Model/Order.php
> +     * Rules are comma separated if there are more than one.
Please include a blank line before or add the "(comma separated)" information in return line, removing this one.

2018-10-15 11:09 UTC, rodrigowebjump commented on app/code/Magento/Sales/Model/Order/Item.php
> +     * Rules are comma separated if there are more than one.
Please include a blank line before or add the "(comma separated)" information in return line, removing this one.

2018-10-18 00:32 UTC, rodrigowebjump reviewed
Hi, you include an empty line before long description, but removed the line after.

Please, include the empty line after long description :-)

Refer: https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html

2018-10-18 00:32 UTC, rodrigowebjump commented on app/code/Magento/Sales/Api/Data/OrderInterface.php
> +     * Rules are comma separated if there are more than one.
You should keep an empty line between description and return

2018-10-18 00:32 UTC, rodrigowebjump commented on app/code/Magento/Sales/Api/Data/OrderItemInterface.php
> +     * Rules are comma separated if there are more than one.
You should keep an empty line between description and return

2018-10-18 00:32 UTC, rodrigowebjump commented on app/code/Magento/Sales/Model/Order.php
> +     * Rules are comma separated if there are more than one.
You should keep an empty line between description and return

2018-10-18 00:32 UTC, rodrigowebjump commented on app/code/Magento/Sales/Model/Order/Item.php
> +     * Rules are comma separated if there are more than one.
You should keep an empty line between description and return

2018-10-18 21:31 UTC, rodrigowebjump approved these changes
Hi @zack6849 Thanks for your contribution

2018-10-18 21:34 UTC, magento-engcom-team commented
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3199](https://jira.corp.magento.com/browse/ENGCOM-3199) has been created to process this Pull Request

2018-10-22 21:40 UTC, merged

2018-10-22 21:52 UTC, okorshenko commented
merged

2018-10-22 21:55 UTC, magento-engcom-team commented
Hi @zack6849. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.