Fixed Issue: Customer name in admin order management is "Guest"
magento/magento2 pull request #18640
Opened 2018-10-16 06:20 UTC by maheshWebkul721

Fixed Issue of Place an order as an guest, the displayed customer name in the admin order management is "Guest". If the guest has created an account after placing the order, it is a link that points to the customer's account management. Invoice and shipping are also affected.

### Description (*)
If Order is placed by Guest user in admin Order view, Invoice view, Shipment view, displaying Customer
name as "Guest", issue was in the quote management, its only set email for the customer, Now i have it 
in this pull request.

### Fixed Issues (if relevant)
1. #18616: Customer name in adminhtml's order management is "Guest"

### Manual testing scenarios (*)
1. Created a new order as Guest for simple product, now Customer name is visible in admin order view.
2. Created a new order as Guest for virtual product as well, now Customer name is visible in admin order view.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-16 06:20 UTC, magento-engcom-team commented
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-16 06:58 UTC, maheshWebkul721 commented
#SQUASHTOBERFEST

2018-10-26 16:22 UTC, slavvka commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Save.php
> +            if ($model->getIsUserDefined() === null || $model->getIsUserDefined() != 0) {
Could you please tell what is the reason of changes in this file? How is it related to the original issue?

2018-10-26 16:55 UTC, maheshWebkul721 commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Save.php
> +            if ($model->getIsUserDefined() === null || $model->getIsUserDefined() != 0) {
@slavvka you are right, I cloned my previous fixes and pushed in that so the previous files are also reflecting..... i will update it...

2018-10-29 09:32 UTC, maheshWebkul721 commented
@slavvka update the other files which is not relevant to this issue.

2018-10-29 15:51 UTC, slavvka commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Save.php
> +            if ($model->getIsUserDefined() === null || $model->getIsUserDefined() != 0) {
@maheshWebkul721 Thank you! And please revert all empty lines that you removed.

2018-10-29 16:18 UTC, slavvka requested changes

2018-10-29 16:18 UTC, slavvka commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Save.php
> +            if ($model->getIsUserDefined() === null || $model->getIsUserDefined() != 0) {
@maheshWebkul721 I would suggest you recreated your fix from the scratch and force-pushed it to ensure you don't have not needed changes.

2018-10-29 16:52 UTC, maheshWebkul721 commented
@slavvka here i reference PR for this: #18928

2018-10-29 16:53 UTC, closed without merging