[Feature] Add Google Optimize support
magento/magento2 pull request #18663
Opened 2018-10-17 07:03 UTC by ihor-sviziev

### Description (*)
This PR adds support of Google Optimize by following instructions:
https://support.google.com/optimize/answer/6262084

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Create new account in https://optimize.google.com/
2. Go to Admin >> Stores >> Configuration >> Sales >> Google API >> Analytics Tab
3. Configure "Google Optimize container ID" from created account
4. Verify if Google Optimize works good

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-17 07:03 UTC, magento-engcom-team commented
Hi @ihor-sviziev. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-25 19:46 UTC, slavvka requested changes

2018-10-25 19:46 UTC, slavvka commented on app/code/Magento/GoogleAnalytics/Block/Ga.php
> +    public function getOptimizeContainerId()
@ihor-sviziev you made it breaking compatibility since the class is marked with `@api`

2018-10-25 19:46 UTC, slavvka commented on app/code/Magento/GoogleAnalytics/Helper/Data.php
> +    const XML_PATH_OPTIMIZE_CONTAINER_ID = 'google/analytics/optimize_container_id';
@ihor-sviziev you made it breaking compatibility since the class is marked with `@api`

2018-10-25 19:46 UTC, slavvka commented on app/code/Magento/GoogleAnalytics/Helper/Data.php
> +    const XML_PATH_OPTIMIZE_CONTAINER_ID = 'google/analytics/optimize_container_id';
Please consider moving it into another class

2018-10-25 19:46 UTC, slavvka commented on app/code/Magento/GoogleAnalytics/Block/Ga.php
> +    public function getOptimizeContainerId()
Consider please doing it in a compatible way or just add a new block for this functionality

2018-10-25 19:48 UTC, slavvka requested changes
@ihor-sviziev Thank you for this contribution. Please refactor the solution according to the comments. Also I requested a review from Product side whether we need such the functionality.

2018-11-07 16:20 UTC, slavvka commented
hey @ihor-sviziev Are you going to proceed with this PR?

2018-11-07 17:44 UTC, ihor-sviziev commented
Hi @slavvka,
I'll close this issue for now, will reopen if will have free time for fixing it

2018-11-07 17:44 UTC, closed without merging

2018-11-07 18:00 UTC, slavvka commented
@ihor-sviziev ok, thank you!