issue fixed - Tierprice can't save float percentage value #18651
magento/magento2 pull request #18661
Opened 2018-10-17 05:15 UTC by anujwebkul

Tierprice can't save float percentage value

### Description (*)
Add/edit a product and add new tierprice with "discount" value "12.5" and then save the product then it is converted it to integer value  then saved it in the database. I have fixed this issue in this pull request.

### Fixed Issues (if relevant)
1. #18651 

### Manual testing scenarios (*)
1. Add/Edit a product.
2. Add new tierprice with "discount" value "12.5"
3. Save Product.
4. Saving the tierprice as float "12.5".

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-17 05:15 UTC, magento-engcom-team commented
Hi @anujwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-17 05:20 UTC, anujwebkul commented
#SQUASHTOBERFEST

2018-10-17 05:21 UTC, anujwebkul commented
SQUASHTOBERFEST

2018-10-17 05:52 UTC, mhauri commented
@magento-engcom-team give me test instance

2018-10-17 05:52 UTC, magento-engcom-team commented
Hi @mhauri. Thank you for your request. I'm working on Magento instance for you

2018-10-17 05:52 UTC, magento-engcom-team commented
Hi @mhauri, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18661/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18661//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18661//admin)
Login: `admin` Password: `123123q`

2018-10-22 08:03 UTC, mhauri commented
Hi @anujwebkul thank you for your contribution, can you also update the tests, as some of them still expect integer values.

2018-10-22 08:04 UTC, mhauri requested changes
Hi @anujwebkul thank you for your contribution, can you also update the tests, as some of them still expect integer values.

2018-10-26 11:25 UTC, anujwebkul commented
Hi @mhauri I am working on it.

2019-04-04 20:07 UTC, orlangur commented
Fix is going to be delivered in https://github.com/magento/magento2/pull/19584.

2019-04-04 20:08 UTC, closed without merging