Added Unit Test for WindowsSmtpConfig Plugin
magento/magento2 pull request #18694
Opened 2018-10-19 06:55 UTC by vasilii-b

### Description

This PR cover `Magento\Email\Test\Unit\Model\Plugin\WindowsSmtpConfig` plugin with unit test.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-19 06:55 UTC, magento-engcom-team commented
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-19 11:47 UTC, rogyar requested changes

2018-10-19 11:47 UTC, rogyar commented on app/code/Magento/Email/Test/Unit/Model/Plugin/WindowsSmtpConfigTest.php
> +
Please, declare the strict types.

2018-10-19 11:47 UTC, rogyar commented on app/code/Magento/Email/Test/Unit/Model/Plugin/WindowsSmtpConfigTest.php
> +        $this->windowsSmtpConfigMock = $objectManager->getObject(
It does not look like a "mock". We test the real object. Please, fix the naming.

2018-10-19 11:47 UTC, rogyar commented
Hello @vasilii-b. Thank you for your contribution. Please, consider fixing a few minor issues mentioned in the review

2018-10-19 11:52 UTC, vasilii-b commented
Thank you @rogyar, will do.

2018-10-19 17:39 UTC, vasilii-b commented
Hi @rogyar , I have added requested changes, but I see the Codacy failed with a strange issue. Could you please have a look and advice what to do there ? 🤔  Thank you!

2018-10-20 09:44 UTC, rogyar commented
I've double checked the result and see no issue. So, no worries

2018-10-20 09:44 UTC, rogyar approved these changes

2018-10-20 09:45 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-3234](https://jira.corp.magento.com/browse/ENGCOM-3234) has been created to process this Pull Request

2018-10-25 15:23 UTC, merged

2018-10-25 15:24 UTC, magento-engcom-team commented
Hi @vasilii-b. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.