[Forwardport] Module Catalog URL Rewrite: fix issue with product URL Rewrites re-generation after changing product URL Key for product with existing url_path attribute value
magento/magento2 pull request #18711
Opened 2018-10-19 19:36 UTC by mage2pratik

### Original Pull Request 
 https://github.com/magento/magento2/pull/18566

Hiving saved product attribute `URL Path` value causes broken Product URL Rewrites regeneration after changing product `URL key`.

### Description (*)

If there is a product with set `URL Path` attribute value, product URL Rewrites can't be re-generated clearly after changing product `URL Key` from Admin panel.
For example, after migrating from Magento 1, there are a lot of values for product attribute `URL Path`.

### Fixed Issues (if relevant)

magento/magento2#5929: Saving Product does not update URL rewrite in Magento 2.1.0.

### Causes Issues
magento/magento2#18532: Module Catalog: product "Save and Duplicate" causes getting infinite loop.

### Manual testing scenarios (*)

1. Set attribute `URL Path` value for any product.
1.1. For example, execute following SQL query:
```sql
SET @catalogProductEntityTypeId = (SELECT `entity_type_id`
                                   FROM `eav_entity_type`
                                   WHERE entity_type_code = 'catalog_product');

SET @productUrlPathAttributeId = (SELECT `attribute_id`
                                  FROM `eav_attribute`
                                  WHERE `attribute_code` = 'url_path'
                                    AND entity_type_id = @catalogProductEntityTypeId);

SET @productUrlKeyAttributeId = (SELECT `attribute_id`
                                 FROM `eav_attribute`
                                 WHERE `attribute_code` = 'url_key'
                                   AND `entity_type_id` = @catalogProductEntityTypeId);

SET @storeId = 1; -- change Store ID if it's required

SET @testProductId = 1; -- change Product ID if it's required

SET @existingProductUrlKey = (SELECT `value`
                              FROM `catalog_product_entity_varchar`
                              WHERE `entity_id` = @testProductId
                                AND `attribute_id` = @productUrlKeyAttributeId); -- any value could be there

INSERT INTO `catalog_product_entity_varchar` (`attribute_id`, `store_id`, `entity_id`, `value`)
    VALUES (@productUrlPathAttributeId, @storeId, @testProductId, @existingProductUrlKey);

```
2. Go to Admin panel -> Catalog -> Inventory -> Products.
3. Find and open testable product.
4. Change `URL Key` field value.
5. Save product.
6. Go to product page on frontend by new `URL Key`.

### Expected result
Product is available by the new `URL Key`.

### Actual result
Product is not available by the new `URL Key`, but available by the previous one.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-19 19:36 UTC, magento-engcom-team commented
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-19 19:47 UTC, okorshenko requested changes
Thank you for your contribution.

Could you please cover this solution with the tests.
Thank you

2018-10-25 19:19 UTC, slavvka submitted a review, later dismissed

2018-10-25 19:20 UTC, magento-engcom-team commented
Hi @slavvka, thank you for the review.
[ENGCOM-3277](https://jira.corp.magento.com/browse/ENGCOM-3277) has been created to process this Pull Request

2018-11-06 20:05 UTC, slavvka commented
hey @mage2pratik are you going to proceed with this PR?

2018-11-07 05:08 UTC, orlangur commented
@slavvka let's wait with merging this until we understand what is going on in https://github.com/magento/magento2/pull/18567#issuecomment-436506426.

2018-11-07 15:54 UTC, orlangur commented
Closing as there is no response from contributor on review note for over 19 days.

Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-11-07 15:54 UTC, closed without merging