Convert paths registered to their realpath
magento/magento2 pull request #18747
Opened 2018-10-22 16:00 UTC by navarr

### Description (*)

Many Magento tools expect that the path given to the ComponentRegistrar be the real path of the directory.  As such, it is possible for extension developers to make mistakes that are difficult to debug but result in issues (such as a third party module having its Test classes compiled [BUNDLE-1798]

This change makes Magento a little less error-prone.

### Fixed Issues (if relevant)

1. BUNDLE-1798

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-22 19:29 UTC, magento-engcom-team commented
Hi @navarr. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-22 19:52 UTC, navarr commented
#squashtoberfest

2018-11-01 18:00 UTC, orlangur commented
@navarr,

> Many Magento tools expect that the path given to the ComponentRegistrar be the real path of the directory

How it could happen if it was never true before?

2018-11-01 18:05 UTC, navarr commented
@orlangur Maybe "real path" is the wrong phrase.  Let's say registered path is "blah/blah/../blah2" - it'll work for registration, but certain other tooling will fail (e.g. auto-generated regex patterns for excluding automated tests from DI compilation)

2018-11-19 10:00 UTC, sivaschenko commented
Hi @navarr , thanks for your contribution! It would be great if you update the https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Component/Test/Unit/ComponentRegistrarTest.php to cover cases when realpath usage is necessary.

2018-11-19 10:22 UTC, orlangur requested changes

2018-11-19 10:22 UTC, orlangur commented on lib/internal/Magento/Framework/Component/ComponentRegistrar.php
> +            self::$paths[$type][$componentName] = realpath(str_replace('\\', '/', $path));
We must not operate with absolute file paths.

@navarr could you provide details of `BUNDLE-1798` please?

2018-12-11 14:41 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-12-11 14:41 UTC, closed without merging