Fixed tierprice discount not calculated correctly if has specialprice
magento/magento2 pull request #18743
Opened 2018-10-22 12:59 UTC by gelanivishal

### Description (*)
Added tierprice discount on speacial price, Check below link
**Before:** https://www.screencast.com/t/NyBdfLCb
**After:** https://www.screencast.com/t/na7rpDoKPvN

### Fixed Issues (if relevant)

1. magento/magento2#18652: Tierprice discount not calculated correctly if has specialprice

### Manual testing scenarios (*)

1. Add new product with price $18.42
2. Add special price $14
3. Add tier price with qty=2, type = "Discount" and value = "%12"
4. Add tier price with qty=300, type = "Discount" and value = "%25"
4. Add tier price with qty=1000, type = "Discount" and value = "%50"
6. Save the product

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-22 18:46 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-30 11:30 UTC, phoenix128 requested changes

2018-10-30 11:30 UTC, phoenix128 commented on app/code/Magento/Catalog/Model/Product/Attribute/Backend/Tierprice.php
> +                $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {
You have a failing static test, I think you should use `$specialPriceToDate === null` instead of `is_null`.

2018-11-01 12:29 UTC, gelanivishal commented on app/code/Magento/Catalog/Model/Product/Attribute/Backend/Tierprice.php
> +                $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {
Done.

2018-11-05 14:31 UTC, phoenix128 approved these changes

2018-11-05 14:32 UTC, magento-engcom-team commented
Hi @phoenix128, thank you for the review.
[ENGCOM-3392](https://jira.corp.magento.com/browse/ENGCOM-3392) has been created to process this Pull Request

2018-11-12 11:10 UTC, merged

2018-11-12 11:11 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.