Set the correct tier price for alternative website (not default) on admin order create
magento/magento2 pull request #18784
Opened 2018-10-24 13:40 UTC by nicobatty

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#18577: On sales/order_create/loadBlock/block Customer tier price remove

### Manual testing scenarios (*)

1. The reproducing scenario is specified here: https://github.com/magento/magento2/issues/18577#issuecomment-430662428
2. The changes done on the Configurable module fix the add to cart for a tier priced configurable product.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-24 13:40 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18784) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18784) before we can accept your contribution.<br/>

2018-10-24 13:40 UTC, magento-engcom-team commented
Hi @nicobatty. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-25 08:22 UTC, sidolov requested changes

2018-10-25 08:22 UTC, sidolov commented on app/code/Magento/Catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php
> +    public function setPriceData($object, $priceData, $storeId = null)
Unfortunately, we are not allowed to modify any public method according to our [Backward compatible development guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/). Consider to define new method, fix all usages and deprecate this one
Thank you!

2018-11-08 14:44 UTC, sidolov commented
Hi @nicobatty , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-11-08 14:44 UTC, closed without merging