Make the function to import shipping rate data public
magento/magento2 pull request #18828
Opened 2018-10-26 10:10 UTC by avstudnitz

### Description
There should be an option to create shipping rate data programmtically (i.e. via Setup Script) without having to create a CSV file. This PR just makes a private method public in order to archieve that.

### Manual testing scenarios
1. Create a setup script
2. Add `\Magento\OfflineShipping\Model\ResourceModel\Carrier\Tablerate` to the constructor, create a class variable `$tablerate` and assign the retrieved object to it in the constructor.
3. Call `$this->tablerate->importData($fields, $values)` from your own method.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-26 10:10 UTC, magento-engcom-team commented
Hi @avstudnitz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-26 11:08 UTC, orlangur requested changes

2018-10-26 11:08 UTC, orlangur commented on app/code/Magento/OfflineShipping/Model/ResourceModel/Carrier/Tablerate.php
> +    public function importData(array $fields, array $values)
Such change may lead to data inconsistency due to lack of deleting old data:
https://github.com/magento/magento2/blob/121640f1cab195c0a1a44babf10bbaeebeeb7adb/app/code/Magento/OfflineShipping/Model/ResourceModel/Carrier/Tablerate.php#L277

Why need to make this method public as all what this method does is ```$this->getConnection()->insertArray($this->getMainTable(), $fields, $values);```?

2018-11-09 08:04 UTC, sidolov commented
Hi @avstudnitz , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-11-09 08:04 UTC, closed without merging