Resolves 6731 by adding a custom message for refunding shipping
magento/magento2 pull request #18844
Opened 2018-10-26 19:55 UTC by Rus0

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#6731: 'Exception' with message 'Warning: Division by zero in vendor/magento/module-sales/Model/Order/Creditmemo/Total/Discount.php on line 32' in vendor/magento/framework/App/ErrorHandler.php:61

### Manual testing scenarios (*)

1. Create a order with free shipment
2. Invoice the order
3. Create new creditmemo
4. Refund $10 in Refund Shipping

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-26 19:55 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18844) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18844) before we can accept your contribution.<br/><hr/>**Rus0** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-10-26 19:55 UTC, magento-engcom-team commented
Hi @Rus0. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-26 20:58 UTC, okorshenko requested changes

2018-10-26 20:58 UTC, okorshenko commented on app/code/Magento/Sales/Model/Order/Creditmemo/Total/Discount.php
> +        if ( $baseShippingAmount && $order->getBaseShippingAmount() <= 0 ) {
```suggestion
        if ($baseShippingAmount && $order->getBaseShippingAmount() <= 0) {
```
according to our code style, if statement condition should be without spaces

2018-10-26 20:58 UTC, okorshenko commented on app/code/Magento/Sales/Model/Order/Creditmemo/Total/Discount.php
> +                new \Magento\Framework\Phrase("You can not refund shipping if there is no shipping amount.",[])
```suggestion
                new \Magento\Framework\Phrase("You can not refund shipping if there is no shipping amount.", [])
```
there should be a space between parameters

2018-10-26 20:58 UTC, okorshenko commented on app/code/Magento/Sales/Model/Order/Creditmemo/Total/Discount.php
> +         *      throw exception with differente message
```suggestion
         * throw exception with different message
```
removed spaces and fixed typo

2018-10-26 20:58 UTC, okorshenko commented on app/code/Magento/Sales/Model/Order/Creditmemo/Total/Discount.php
> +            throw new \Magento\Framework\Exception\LocalizedException(
it would be great if we can cover this case with unit test at least

2018-10-27 03:55 UTC, okorshenko approved these changes

2018-10-27 03:56 UTC, magento-engcom-team commented
Hi @okorshenko, thank you for the review.
[ENGCOM-3294](https://jira.corp.magento.com/browse/ENGCOM-3294) has been created to process this Pull Request

2018-10-31 20:11 UTC, merged

2018-10-31 20:12 UTC, magento-engcom-team commented
Hi @Rus0. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.