Fixed subscribe to newsletter if you already have an account issue #8952
magento/magento2 pull request #18912
Opened 2018-10-29 07:40 UTC by ravi-chandra3197

### Description (*)

Fixed subscribe to newsletter if you already have an account issue
### Fixed Issues (if relevant)

1. magento/magento2#8952: You can't subscribe to newsletter if you already have an account

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-29 07:40 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-29 09:22 UTC, sidolov requested changes

2018-10-29 09:22 UTC, sidolov commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +        if ($this->_customerSession->getCustomerDataObject()->getEmail()) {
Please, combine two `if` statements to one

2018-10-29 09:39 UTC, ravi-chandra3197 commented
Hello @sidolov 
I have update change as per your suggestion can review it.

2018-11-03 13:26 UTC, ravi-chandra3197 commented
Hello @sidolov
can you guide how to add the custom test case in magento2 like my Travis fail due to default test case I need to add custom test case so can you guide

2018-11-05 13:07 UTC, ravi-chandra3197 commented
Hello @sidolov
I have update change as per your suggestion can review it.

2018-11-07 05:48 UTC, orlangur requested changes
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

2018-11-12 09:12 UTC, ravi-chandra3197 commented
Fixed subscribe to newsletter if you already have an account issue #8952 -2.3 develop #19164

2018-11-12 09:14 UTC, ravi-chandra3197 commented
#19164

2018-11-12 10:18 UTC, orlangur commented
@ravi-chandra3197 after 2.3 PR is merged, please rewrite history of this branch to reflect it (cherry pick the only meaningful commit).

2018-12-12 09:04 UTC, ravi-chandra3197 commented
Hello, @orlangur I have rewrite branch history with single commit can review it.

2018-12-12 17:20 UTC, orlangur approved these changes

2018-12-12 17:21 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3680](https://jira.corp.magento.com/browse/ENGCOM-3680) has been created to process this Pull Request

2019-01-02 21:06 UTC, merged

2019-01-02 21:07 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.