2.2.6 Use batches and direct queries to fix sales address upgrade
magento/magento2 pull request #18945
Opened 2018-10-30 10:10 UTC by rikwillems

### Description (*)
Magento Commerce compatible fix for sales address upgrade script.

### Fixed Issues (if relevant)

1. magento/magento2#16570: enhance performance on large catalog
[(comment)](https://github.com/magento/magento2/pull/16570#issuecomment-429830198)

2018-10-30 10:10 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=18945) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18945) before we can accept your contribution.<br/><hr/>**** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-10-30 10:10 UTC, magento-engcom-team commented
Hi @rikwillems. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-30 10:18 UTC, ihor-sviziev commented
Hi @rikwillems,
Please sign CLA, otherwise we can't accept your PR

2018-11-02 09:51 UTC, rikwillems commented
@ihor-sviziev I did that and see it reflected in the ticket now.

2018-11-07 08:12 UTC, ihor-sviziev commented
Hi @rikwillems,
Here is some failures in static and integration tests, looks like there is some issue in your implementation. Could you looks on it?

Your implementation actually not so easy. Could you describe how your solution works to be sure we're on the same page?

2018-11-07 08:13 UTC, ihor-sviziev requested changes

2018-11-07 08:13 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +        $sql = "update `{$setup->getTable('sales_order_address')}` set `quote_address_id` = :quoteAddressId where `entity_id` = :orderAddressId";
Looks like there is mistake:
```suggestion
        $sql = "update `{$setup->getTable('sales_order_address', 'sales')}` set `quote_address_id` = :quoteAddressId where `entity_id` = :orderAddressId";
```

2018-11-07 08:13 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +        $this->fillQuoteAddressIdInSalesOrderAddressByType($setup,Address::TYPE_SHIPPING);
```suggestion
        $this->fillQuoteAddressIdInSalesOrderAddressByType($setup, Address::TYPE_SHIPPING);
```

2018-11-07 08:13 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +        $this->fillQuoteAddressIdInSalesOrderAddressByType($setup,Address::TYPE_BILLING);
```suggestion
        $this->fillQuoteAddressIdInSalesOrderAddressByType($setup, Address::TYPE_BILLING);
```

2018-11-07 08:37 UTC, rikwillems commented
@ihor-sviziev 
It basically does the same thing as the other implementations. It works on raw queries but does not join between quote and sales. Also it works in batches to precent memory limits.

2018-11-07 09:10 UTC, ihor-sviziev commented
Hi @rikwillems,
Your first commit has different commiter email, as result - CLA showing that you didn't signed. Could you add that email to your github account OR just squash all your changes into single commit and force-push it?

2018-11-07 09:37 UTC, rikwillems commented
I added PR #19098

2018-11-07 12:42 UTC, ihor-sviziev commented
@rikwillems  thank you!
I'll close this PR as it is duplicates https://github.com/magento/magento2/pull/19098

2018-11-07 12:42 UTC, closed without merging