Improve code by removing unnecessary curly braces
magento/magento2 pull request #18955
Opened 2018-10-30 17:03 UTC by mage2pratik

### Description (*)

Improve code by removing unnecessary curly braces.
### Fixed Issues (if relevant)

1. magento/magento2#18813: Add curly braces to indirect variables to make them clear to understand

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-10-30 17:03 UTC, magento-engcom-team commented
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-10-30 17:22 UTC, orlangur requested changes

2018-10-30 17:22 UTC, orlangur commented on dev/tests/functional/tests/app/Magento/Backend/Test/Block/Messages.php
> +            ->find($this->$messageType . 'Message', Locator::SELECTOR_CSS)
Please fix these two occurrences (commit amend + force push).

2018-10-30 17:22 UTC, orlangur commented on dev/tests/functional/tests/app/Magento/Sales/Test/Block/Adminhtml/Order/Create/Items/ItemProduct.php
> +            )->$this->actions[$key]();
Please introduce a variable (commit amend + force push)

2018-10-30 17:22 UTC, orlangur commented on lib/internal/Magento/Framework/ObjectManager/Code/Generator/Persistor.php
> +        $body = "\$entity = \$this->\$this->_getSourceFactoryPropertyName()->create(['data' => \$data]);\n"
Here curly braces are essential, please just revert changes.

2018-10-30 17:22 UTC, orlangur commented on lib/internal/Magento/Framework/ObjectManager/Code/Generator/Repository.php
> +        $body = "\$this->\$this->_getSourcePersistorPropertyName()->registerDeleted(\$entity);";
Here (in this file) curly braces are essential, please just revert changes.

2018-10-30 18:34 UTC, orlangur commented
@mage2pratik looks good, waiting for builds.

2018-11-01 17:59 UTC, orlangur requested changes
@mage2pratik there are some failing integration tests, so, code behavior was unintentionally changed - please fix it.

After all builds are green, please squash all changes into a single commit.

2018-11-14 14:42 UTC, sivaschenko commented
Hi @mage2pratik , would you like to continue working on this PR's progress?

2018-11-14 17:33 UTC, orlangur commented
@sivaschenko looks like no but we should wait one more day :)

2018-11-18 10:01 UTC, sidolov commented
Hi @mage2pratik , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-11-18 10:01 UTC, closed without merging