2.3 develop
magento/magento2 pull request #19020
Opened 2018-11-02 11:52 UTC by OleksiiStepanov

### Description (*)

Pull request fix bug when unable create new attribute via api with custom source model
### Fixed Issues (if relevant)

1. magento/magento2#12514 : Impossible to set source model when create new attribute

### Manual testing scenarios (*)

create new attribute via api using \Magento\Catalog\Api\ProductAttributeRepositoryInterface
like this

```
$attribute = $this->attributeFactory->create();

$this->dataObjectHelper->populateWithArray(
$attribute,
[
'attribute_code' => 'select_attribute',
'source_model' => '\Custom\Model',
'default_frontend_label' => 'select_attribute_label',
'frontend_input' => 'select',
'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_STORE,
],
ProductAttributeInterface::class
);
$this->attributeRepository->save($attribute);
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-02 11:52 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19020) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19020) before we can accept your contribution.<br/>

2018-11-02 11:52 UTC, magento-engcom-team commented
Hi @OleksiiStepanov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-02 17:37 UTC, sivaschenko approved these changes
Changes allow to set custom backend_type, source_model and backend_model when creating a new attribute. Tests could be styled and organized better, as in my opinion, they lack readability.

2018-11-02 17:39 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3376](https://jira.corp.magento.com/browse/ENGCOM-3376) has been created to process this Pull Request

2018-11-09 08:41 UTC, sidolov requested changes

2018-11-09 08:41 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/Catalog/Model/Product/Attribute/RepositoryTest.php
> +            $this->attributeRepository->deleteById($attrCode);
Please, use data fixtures for creating and removing test data.

2018-11-09 08:41 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/Catalog/Model/Product/Attribute/RepositoryTest.php
> +<?php
Please, fix code style in the whole file

2018-11-28 21:18 UTC, sidolov commented
Hi @OleksiiStepanov , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2018-11-28 21:18 UTC, closed without merging