17759 CustomerRepository getList does not load custom attribute if the name is "company"
magento/magento2 pull request #19031
Opened 2018-11-02 14:30 UTC by nik4152

### Description (*)
fix method getList customer repository field Company  form billing address 

### Fixed Issues (if relevant)

1. magento/magento2#17759: M2.2.5 : CustomerRepository::getList() does not load custom attribute if the name is "company"

2018-11-02 14:30 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19031) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19031) before we can accept your contribution.<br/>

2018-11-02 14:30 UTC, magento-engcom-team commented
Hi @nik4152. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-02 15:09 UTC, VladimirZaets commented
Hi @nik4152  , please, sign CLA, otherwise, we can't process your pull request

2018-11-02 23:34 UTC, orlangur approved these changes

2018-11-07 04:57 UTC, orlangur requested changes
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

2018-11-19 10:02 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2018-11-19 10:02 UTC, closed without merging