Cache key fix
magento/magento2 pull request #19033
Opened 2018-11-02 14:58 UTC by novikor

### Description (*)
Optimized cache usage for TopMenu block.
Previously, it was cached for ALL pages in order to highlight current category in navigation bar, however since 2.2 it was replaced with JS solution.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-02 14:59 UTC, magento-engcom-team commented
Hi @novikor. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-02 23:20 UTC, orlangur requested changes
@novikor it needs to de done for 2.2 as backport of https://github.com/magento/magento2/commit/61d81a8e07b627eb7f3850529767e1427461f52b#diff-454601ea9afd086413ac90923ae9ccaa and https://github.com/magento/magento2/commit/fcb3d675ea3df97f8935cc5a560a396ac9ae7db2

2018-11-03 18:15 UTC, alejagapatrick10 commented
Thanks

2018-11-03 19:17 UTC, alejagapatrick10 commented
NY_license.pdf
<https://drive.google.com/file/d/1GI9XvBeBVBG96h2Xn7xrl9wnqO5DaLFR/view?usp=drivesdk>



Noong Lin, Nob 4, 2018, 02:15 alejagapatrick10 Isinulat ni <
notifications@github.com ang:

> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/19033#issuecomment-435609449>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQaQcIl9hWGv6ZZ0at3zstfA78dTfx4yks5urd1RgaJpZM4YLz2q>
> .
>

2018-11-07 18:36 UTC, novikor commented
@orlangur, will be done. Thank you for review.

2018-11-10 18:18 UTC, novikor commented
@orlangur , please check

2018-11-19 10:31 UTC, orlangur commented
@novikor commits are not properly author yet. Please cherry-pick them and force push to the same branch.

2018-11-24 15:26 UTC, novikor commented
@orlangur , please review again

2018-11-24 22:02 UTC, orlangur approved these changes

2018-11-24 22:03 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3557](https://jira.corp.magento.com/browse/ENGCOM-3557) has been created to process this Pull Request

2018-12-10 18:35 UTC, sidolov requested changes

2018-12-10 18:35 UTC, sidolov commented on app/code/Magento/Theme/Block/Html/Topmenu.php
> -    public function getCacheKeyInfo()
Unfortunately, we can't remove the public methods according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2018-12-11 15:23 UTC, orlangur commented on app/code/Magento/Theme/Block/Html/Topmenu.php
> -    public function getCacheKeyInfo()
@sidolov I don't think it's applicable. We have a parent method `parent::getCacheKeyInfo`, isn't it?

2018-12-11 15:25 UTC, orlangur requested changes
@novikor there are still unnecessary merge commits.

Could you please force push a branch with clean history?

Let's wait for reply of @sidolov regarding removal first.

2018-12-17 19:32 UTC, sidolov commented
Hi @novikor , @orlangur , looks like the same fix was delivered in commit d30ae920ac10b1382a66763a2e0222af4f5dd731 and delkivered to the mainline. 
I'm closing this PR as not relevant. 
Thank you for the contribution!

2018-12-17 19:32 UTC, closed without merging

2018-12-18 07:06 UTC, orlangur commented
@sidolov thanks! Would be nice if internal contributors will do proper cherry-picks during backport as well ;)

2018-12-18 15:06 UTC, sidolov commented
@orlangur I have raised this problem in our internal team and we will try to avoid such situations in the future! Thank you for the input!