19016 double extension point v22
magento/magento2 pull request #19042
Opened 2018-11-02 15:54 UTC by chrom

Fix double extension point of product conversion service when generating simple products through the wizard in product page.
https://github.com/magento/magento2/issues/19016

2018-11-02 15:54 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19042) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19042) before we can accept your contribution.<br/>

2018-11-02 15:54 UTC, magento-engcom-team commented
Hi @chrom. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-02 23:53 UTC, orlangur requested changes
I see three lines of code encapsulated in a new class and a lot of unrelated changes. Where are the changes related to `TypeTransition`? I don't see extension points decreased.

Currently all changes needs to be applied to `2.3-develop` first.

2018-11-02 23:53 UTC, orlangur commented on app/code/Magento/ConfigurableProduct/Model/Product/VariationHandler.php
> + *
Such changes must be reverted.

2018-11-02 23:53 UTC, orlangur commented on app/code/Magento/ConfigurableProduct/Model/Product/VariationHandler.php
> +        $productsData        = $this->duplicateImagesForVariations($productsData);
Such changes must be reverted.

2018-11-02 23:53 UTC, orlangur commented on app/code/Magento/ConfigurableProduct/Model/Product/VariationHandler.php
> +        ProductFactory $productFactory,
No need to revert but generally please avoid such changes mixed with change of logic. We will get rid of FQCN at some point but it should be a separate effort.

2018-11-05 16:24 UTC, chrom commented
@orlangur This makes it possible to disable the autoconversion of products using the plugin. We discussed this with @maghamed  and @naydav.

2018-11-07 00:12 UTC, orlangur commented
@chrom,

> makes it possible to disable the autoconversion of products using the plugin

When this may be needed? Please provide a complete use case. What's the problem with specifying weight, for instance?

2018-11-07 17:59 UTC, chrom commented
@orlangur When the customer needs to disable the autoconversion of the product. As an example, we have such a client who asked to turn off autoconversion as it does not have downloaded or virtual products and due to the human factor - when managers forgot to put weight, autoconversion occurred.

2018-11-08 14:18 UTC, orlangur commented
@chrom just make weight a mandatory field then.

> when managers forgot to put weight, autoconversion occurred

Proper weight may be added afterwards.

2018-11-08 15:11 UTC, chrom commented
when generating simple products through the wizard, default attribute
values are not set

чт, 8 нояб. 2018 г. в 16:18, Vlad Veselov <notifications@github.com>:

> @chrom <https://github.com/chrom> just make weight a mandatory field then.
>
> when managers forgot to put weight, autoconversion occurred
>
> Proper weight may be added afterwards.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/19042#issuecomment-437008662>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5otmmFy_YwXcWP5dDRfWVYeSMKyyLQks5utD0-gaJpZM4YL6aD>
> .
>

2018-11-13 20:54 UTC, orlangur commented
@chrom,

> when generating simple products through the wizard, default attribute
values are not set

I would rather treat it as a bug and fix.

2018-11-14 08:01 UTC, chrom commented
Yes, but it still does not allow you to disable the conversion - say, based
on dynamic rules

вт, 13 нояб. 2018 г. в 22:54, Vlad Veselov <notifications@github.com>:

> @chrom <https://github.com/chrom>,
>
> when generating simple products through the wizard, default attribute
> values are not set
>
> I would rather treat it as a bug and fix.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/19042#issuecomment-438432773>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5otifKDzJnDjKcqfN9DU9wAerH1sJLks5uuzF1gaJpZM4YL6aD>
> .
>

2018-11-14 14:20 UTC, orlangur commented
> based on dynamic rules

@chrom the whole idea was that merchant should not care about product type at all, conversion occurs transparently and automatically. Please provide scenario where it is really essential whether configurable product child products are virtual or simple.

2018-11-19 09:17 UTC, orlangur commented
Closing as this PR does not seem to achieve goal described in issue: having a single product type conversion extension point.

Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened. Thanks for collaboration!

2018-11-19 09:17 UTC, closed without merging