Combined commit
magento/magento2 pull request #19098
Opened 2018-11-07 09:36 UTC by rikwillems

### Description (*)
Magento Commerce compatible fix for sales address upgrade script.

### Fixed Issues (if relevant)
1. magento/magento2#16570: enhance performance on large catalog
[(comment)](https://github.com/magento/magento2/pull/16570#issuecomment-429830198)
2. https://github.com/magento/magento2/pull/18945

2018-11-07 09:36 UTC, magento-engcom-team commented
Hi @rikwillems. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-07 15:23 UTC, ihor-sviziev requested changes

2018-11-07 15:23 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +        $query = $salesConnection
Checked, this part generates following SQL example:
```sql
SELECT sales_order_address.entity_id, sales_order_address.address_type, sales_order.quote_id as quote_id
FROM sales_order_address sales_order_address
INNER JOIN sales_order sales_order ON (sales_order_address.parent_id = sales_order.entity_id)
WHERE sales_order_address.quote_address_id IS NULL
  AND sales_order_address.address_type = 'shipping'
ORDER BY sales_order_address.entity_id;
```

Result example:
```php
[
    'order address id' => [
        'entity_id' => 'order address id',
        'address_type' => 'order address type',
        'quote_id' => 'quote id'
    ],
    ...
]

2018-11-07 15:23 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +        $query = $quoteConnection
This query will be following 
```sql
SELECT quote_address.quote_id, quote_address.address_id
FROM quote_address quote_address
INNER JOIN quote quote ON (quote_address.quote_id = quote.entity_id)
WHERE quote.entity_id in (<order_address_ids>)
  AND address_type = 'shipping'
```


Looks like you did some mistake in "<order_address_ids>". Please check it

2018-11-07 15:30 UTC, ihor-sviziev commented
Also looks like CLA showing as "not signed", so probably we have some issue there. Could you contact me in Slack?

2018-11-07 15:32 UTC, orlangur commented
@ihor-sviziev is this not relevant or already delivered to 2.3?

2018-11-07 15:34 UTC, ihor-sviziev commented
@orlangur this PR was just re-created from https://github.com/magento/magento2/pull/18945 by author

2018-11-08 08:25 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19098) <br/>All committers have signed the CLA.

2018-11-08 08:34 UTC, rikwillems commented
This CLA is giving me a headache. I tried a new PR fix this as I cannot modify existing commits with new emailaddress. https://github.com/magento/magento2/pull/19114

2018-11-08 10:05 UTC, orlangur commented
@rikwillems,

> cannot modify existing commits with new email address

```
git reset --soft HEAD^
git commit -m'Message'
git force push
```

should do the trick for arbitrary amount of last commits.

2018-11-08 11:57 UTC, ihor-sviziev requested changes

2018-11-08 11:57 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +        $this->fillQuoteAddressIdInSalesOrderAddressByType($setup, Address::TYPE_SHIPPING);
In integration tests we have following fail:
> PHP Fatal error:  Uncaught Error: Class 'Magento\Sales\Setup\Address' not found in 

Please import `Address` class

2018-11-08 11:57 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +    public function fillQuoteAddressIdInSalesOrderAddressProcessBatch(ModuleDataSetupInterface $setup, array $orderAddresses, $addressType)
According to static tests failure - this line is too long. Please format this function declaration in few lines

2018-11-21 06:44 UTC, ihor-sviziev commented
Hi @rikwillems,
Could you update your PR by squashing all commits into single one and force push, as @orlangur  showed above?

2018-11-21 14:54 UTC, rikwillems commented
@ihor-sviziev I tried this now. Please see it that works.

2018-11-21 15:02 UTC, ihor-sviziev commented
Hi @rikwillems,
Looks like you pushed without force option, as result - it merged changes.

2018-11-21 15:09 UTC, rikwillems commented
@ihor-sviziev this is quote a pain. Not sure why it is not working out. Tried it again.

2018-11-21 15:19 UTC, ihor-sviziev commented
@rikwillems, now you force-pushed, but pushed the same commits as before, but we want to have one squashed commit from you.
In order to verify if you did everything is ok - on the commits section all commit authors should be clickable, now we have two commits from email not linked to your github account
https://github.com/magento/magento2/pull/19098/commits

2018-11-21 15:29 UTC, rikwillems commented
@ihor-sviziev this should do it...

2018-11-21 19:38 UTC, ihor-sviziev requested changes
Issues with commit author is gone, that's good 👍
One small thing still there. Please check it.
Also please create PR to 2.3-develop branch, because it should be merged at first

2018-11-21 19:38 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> -        AddressCollectionFactory $addressCollFactory,
Removing constructor dependencies is not backward compatible change, please revert it

2018-12-05 07:05 UTC, ihor-sviziev commented
Hi @rikwillems,
Are you interested in finalizing this PR?

2019-01-30 07:15 UTC, ihor-sviziev commented
Created PR https://github.com/magento/magento2/pull/20785 with the same changes to 2.3-develop branch, as it should be merged first.

2019-02-20 17:57 UTC, ihor-sviziev approved these changes

2019-02-20 17:59 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4344](https://jira.corp.magento.com/browse/ENGCOM-4344) has been created to process this Pull Request

2019-02-20 17:59 UTC, magento-engcom-team commented
@rikwillems thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-03-12 09:09 UTC, p-bystritsky commented
@rikwillems @ihor-sviziev there is not such column as "orderAddressId" in "sales_order_address" table, used in 'where' clause in https://github.com/magento/magento2/pull/19098/files#diff-0815805b2d40fcf0d22ebd639e0d73c4R247. Which will lead to an error during update.

2019-03-12 09:39 UTC, ihor-sviziev commented on app/code/Magento/Sales/Setup/UpgradeData.php
> +                'orderAddressId' => $orderAddress['entity_id']
```suggestion
                'entity_id' => $orderAddress['entity_id']
```

2019-03-12 09:41 UTC, ihor-sviziev approved these changes

2019-03-12 09:43 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4344](https://jira.corp.magento.com/browse/ENGCOM-4344) has been created to process this Pull Request

2019-03-12 18:09 UTC, ihor-sviziev approved these changes

2019-03-12 18:11 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4344](https://jira.corp.magento.com/browse/ENGCOM-4344) has been created to process this Pull Request

2019-03-14 15:31 UTC, merged