Cache Magento product version
magento/magento2 pull request #19133
Opened 2018-11-09 13:53 UTC by tdgroot

Cache Magento product version to improve performance.

### Description (*)
Fetching the product version is quite a slow process. It can take up to 200 milliseconds, which is quite slow for such a simple method. I added caching, because this totally is something that could be cached, since the value doesn't change very often.

A few questions from my side:
- Do I need  to add some tests?
- I think the cache lifetime should be 24 hours, because it's such a static value. What are your thoughts?

### Manual testing scenarios (*)

1. Create a module which calls getVersion() two times.
2. In the first request, the second call should be faster than the first.
3. In a second request, the first should be as fast as the second one.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-09 13:53 UTC, magento-engcom-team commented
Hi @tdgroot. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-11 14:35 UTC, orlangur requested changes
@tdgroot please provide scenarios in which such version may be frequently used.

2018-12-11 14:51 UTC, tdgroot commented
@orlangur thank you for checking. 

In Magento core I cannot think of such scenarios. 

However, in third party modules actually do make use of fetching the Magento version.

For example the module TIG_Buckaroo. They override a function and change functionality based on Magento version here: [CartTotalRepository](https://github.com/tig-nl/buckaroo-magento2/blob/master/Model/Cart/CartTotalRepository.php#L115) and [CartTotalRepository::isCorrectMagentoVersion](https://github.com/tig-nl/buckaroo-magento2/blob/master/Model/Cart/CartTotalRepository.php#L163).

In one project, I found that multiple third party modules were doing similar things to provide stability or work around Magento issues.

This could slow down checkout actions (select shipping method, payment method, etc.) up to 600 milliseconds.

2018-12-11 15:22 UTC, orlangur commented
Thanks for quick response @tdgroot!

As there is no use for this in core, I don't think such logic should be introduced (as whenever we introduce a cache we should always think about its invalidation).

There is internal caching as a class property in `\Magento\Framework\App\ProductMetadata::getVersion`which is enough.

> For example the module TIG_Buckaroo. They override a function and change functionality based on Magento version here: CartTotalRepository and CartTotalRepository::isCorrectMagentoVersion.

Thanks for a real-world example, however, it goes against best practices. Normally this should be achieved using Composer constraints so that different module versions are used for corresponding Magento version instead of such checks inside.

2018-12-11 15:22 UTC, closed without merging