Reference PL for #19192 fixed for 2.2-develop
magento/magento2 pull request #19193
Opened 2018-11-13 16:14 UTC by maheshWebkul721

Incorrect quote_item_id saved on order items during multiple address checkout issue fixed.

### Description (*)

When order placed using Multiple address checkout then there were incorrect **quote_item_id**  in 
sales_order_item table.
### Fixed Issues (if relevant)

1. #18349 

### Manual testing scenarios (*)

1. Placed and Order with Multi address checkout, now **quote_item_id** is correct.
2. Placed an order with Onestep checkout **quote_item_id** is correct as well.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-13 16:14 UTC, magento-engcom-team commented
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-21 09:56 UTC, sivaschenko commented
This pull request is a backport of https://github.com/magento/magento2/pull/19192

2019-04-01 11:40 UTC, sivaschenko requested changes
Hi @maheshWebkul721 can you please add missing commits to this pull request from the 2.3-develop PR (https://github.com/magento/magento2/pull/19192)

2019-04-15 14:20 UTC, sidolov commented
@maheshWebkul721 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-15 14:20 UTC, closed without merging