Don't return categoryId from registry if the product doesn't belong in the current category
magento/magento2 pull request #19232
Opened 2018-11-15 17:47 UTC by ErikPel

### Description (*)

 I added is_array check to \Magento\Catalog\Model\Product:getCategoryId that check whether the product belongs to the current_category set in registry. This fixes getProductUrl function not returning correct url since there isn't url rewrite for product in that category.

### Fixed Issues (if relevant)

1. magento/magento2#17819: Wrong product url from getProductUrl when current category has not product object

### Manual testing scenarios (*)

1. Create two category category1 and category2 with url-keys category-1 and category-2 respectively
2. Create product with url key product-1, assign it to category1
3. Add created categories to topmenu (turn on "include to menu" checkbox)
5. Create custom module Vendor_Module I have example here if you want to get it fast https://github.com/ErikPel/17819-TestScenario
6. Create template; add it to category layout
7. In the template get product collection with all products in it
8. In foreach loop call $product->getCategory() or $product->getProductUrl()
9. Before getCategory would return the current_category from registry even though the product doesn't belong to the category we are in. And getProductUrl would return http://example.com/catalog/product/view/id/1/s/product-1/category/2 instead of  http://example.com/product-1

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-15 17:47 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19232) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19232) before we can accept your contribution.<br/>

2018-11-15 17:47 UTC, magento-engcom-team commented
Hi @ErikPel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-15 21:21 UTC, magento-engcom-team commented
@ErikPel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-11-15 22:11 UTC, okorshenko commented
@magento-engcom-team give me test instance

2018-11-15 22:11 UTC, magento-engcom-team commented
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

2018-11-15 22:12 UTC, magento-engcom-team commented
Hi @okorshenko, here is your [new Magento instance](http://34.228.235.121/pr-19232/).
Admin access: [http://34.228.235.121/pr-19232//admin](http://34.228.235.121/pr-19232//admin)
Login: `admin` Password: `123123q`

2018-11-16 00:19 UTC, slavvka commented
Hey @ErikPel Could you please take a look at failing integration tests?

2018-11-17 13:09 UTC, ErikPel commented
> Hey @ErikPel Could you please take a look at failing integration tests?

Fixed the integration tests

2018-11-20 04:22 UTC, slavvka requested changes

2018-11-20 04:22 UTC, slavvka commented on dev/tests/integration/etc/install-config-mysql.php.dist
> -<?php
Why did you remove this file?

2018-11-20 16:50 UTC, ErikPel commented on dev/tests/integration/etc/install-config-mysql.php.dist
> -<?php
Must have accidentally removed it, sorry :(
Reseted my branch to origin/2.3-develop and then readded my changes so the new commit doesn't have any changes to that file. Should be fine now

2018-12-22 23:41 UTC, merged

2018-12-22 23:42 UTC, magento-engcom-team commented
Hi @ErikPel. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.