#19093 Add Plugin for SalesOrderItemRepository gift message
magento/magento2 pull request #19250
Opened 2018-11-16 18:26 UTC by larsroettig

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#19093: API: salesOrderItemRepository does not include gift message

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-16 18:26 UTC, magento-engcom-team commented
Hi @larsroettig. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-16 21:27 UTC, orlangur requested changes
@larsroettig nice!

Please cover new implementation with automated test, I would prefer `api-functional` one.

2018-11-16 21:27 UTC, orlangur commented on app/code/Magento/GiftMessage/Model/Plugin/OrderItemGet.php
> +namespace Magento\GiftMessage\Model\Plugin;
Please move it to `...\GiftMessage\Plugin\...`

2018-11-16 21:27 UTC, orlangur commented on app/code/Magento/GiftMessage/Model/Plugin/OrderItemGet.php
> +            : $this->orderItemExtensionFactory->create();
Simplify it with `?:`.

2018-11-19 09:19 UTC, larsroettig commented
@orlangur Jep i will cover this tomorrow with a Test and Fix the Review comments  - thanks for the fast review

2018-11-26 21:38 UTC, larsroettig commented on app/code/Magento/GiftMessage/Model/Plugin/OrderItemGet.php
> +namespace Magento\GiftMessage\Model\Plugin;
All Plugins from this Module is currently placed in` Model\Plugin`

2018-11-26 21:38 UTC, larsroettig commented on app/code/Magento/GiftMessage/Model/Plugin/OrderItemGet.php
> +            : $this->orderItemExtensionFactory->create();
yep this is true i will fix this

2018-11-28 18:51 UTC, closed without merging