Fixed typo in interface method.
magento/magento2 pull request #19314
Opened 2018-11-21 19:55 UTC by tiagosampaio

Fixed typo in interface method. The method name was changed from proccessAdditionalValidation() to processAdditionalValidation().

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-21 19:55 UTC, magento-engcom-team commented
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-22 01:38 UTC, orlangur commented
@tiagosampaio as I mentioned in https://github.com/magento/magento2/pull/19284#issuecomment-440489904, we are trying to understand currently if it is possible to change something like this even in 2.3.

2018-11-22 01:44 UTC, tiagosampaio commented
@orlangur sorry. I didn't get it when you said that. Anyway this is a fix that is required to be done once the classes that implement this interface are already changed and using the new method name. The old one needs to be deprecated.

2018-11-22 01:49 UTC, orlangur commented
@tiagosampaio the problem is that we cannot add new methods into interface as it will break any existing implementation.

2019-01-08 18:49 UTC, tiagosampaio commented
@orlangur any news about this?

2019-02-06 22:47 UTC, sidolov requested changes

2019-02-06 22:47 UTC, sidolov commented on app/code/Magento/Shipping/Model/Carrier/AbstractCarrierInterface.php
> +    public function processAdditionalValidation(\Magento\Framework\DataObject $request);
Unfortunately, we are not able to change public methods signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-02-21 12:59 UTC, sivaschenko commented
Closing this pull request due to inactivity, feel free to reopen if you'd like to continue progress

2019-02-21 12:59 UTC, closed without merging

2019-02-21 13:57 UTC, orlangur commented
@sidolov @sivaschenko guys, I still didn't receive any answer in Slack of here whether we can apply such kind of changes at all or the only way is to deprecate interface completely and introduce a new one?

2019-02-22 15:14 UTC, sivaschenko commented
@orlangur we cannot change/add/remove public and protected methods of API classes (in patch releases)

2019-02-22 17:04 UTC, orlangur commented
@sivaschenko I know what we CANNOT do :) Could you please tell me what is an easiest way to fix such typo?

Not in the patch release, but at least in `2.4.0`.

2019-02-25 17:25 UTC, sivaschenko commented
@orlangur the only way I know currently is to get an architect approval.

2019-02-26 12:14 UTC, orlangur commented
Thanks @sivaschenko!