Fixed the issue #19347.
magento/magento2 pull request #19351
Opened 2018-11-22 20:01 UTC by tiagosampaio

After removing the Estimate Shipping Costs and Tax from cart using layout the totals were not displayed.

### Description (*)
Please check all the description in issue #19347.

### Fixed Issues (if relevant)

1. magento/magento2#19347: Removing "Estimate shipping costs and tax" from cart removes cart totals
2. ...

### Manual testing scenarios (*)
The testing scenarios are described in the issue page.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-22 20:01 UTC, magento-engcom-team commented
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-23 10:51 UTC, sivaschenko requested changes

2018-11-23 10:51 UTC, sivaschenko commented on app/code/Magento/Checkout/Block/Cart/Totals.php
> +     * @param \Magento\Checkout\Block\Cart\Helper\Config $cartConfig
Please ensure the correct sequence of params in the phpdoc, it should correspond to the sequence of parameters in constructor

2018-11-23 10:51 UTC, sivaschenko commented on app/code/Magento/Checkout/Block/Cart/Totals.php
> +    protected $cartConfig;
Please change the access level to private

2018-11-23 10:51 UTC, sivaschenko commented on app/code/Magento/Checkout/Block/Cart/Helper/ConfigProvider.php
> +        return json_encode($this->getCheckoutConfig(), JSON_HEX_TAG);
Please use the serializer

2018-11-23 10:51 UTC, sivaschenko commented on app/code/Magento/Checkout/view/frontend/templates/cart/totals.phtml
> +        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
Can this javascript be moved to a js file?

2018-11-23 10:51 UTC, sivaschenko commented on app/code/Magento/Checkout/Block/Cart/Helper/ConfigProvider.php
> +class ConfigProvider
This class look more like a model than a block. Can you please move it to the Model namespace, also avoid `Helper` in class naming as it is too general, try to pick meaningful namespace and class name. Also, please add comment header for class and enable strict mode.

2018-11-23 17:23 UTC, tiagosampaio commented on app/code/Magento/Checkout/Block/Cart/Helper/ConfigProvider.php
> +class ConfigProvider
@sivaschenko done.

2018-11-23 17:23 UTC, tiagosampaio commented on app/code/Magento/Checkout/Block/Cart/Helper/ConfigProvider.php
> +        return json_encode($this->getCheckoutConfig(), JSON_HEX_TAG);
@sivaschenko done.

2018-11-23 17:23 UTC, tiagosampaio commented on app/code/Magento/Checkout/Block/Cart/Totals.php
> +    protected $cartConfig;
@sivaschenko done.

2018-11-23 17:23 UTC, tiagosampaio commented on app/code/Magento/Checkout/Block/Cart/Totals.php
> +     * @param \Magento\Checkout\Block\Cart\Helper\Config $cartConfig
@sivaschenko done.

2018-11-23 17:25 UTC, tiagosampaio commented on app/code/Magento/Checkout/view/frontend/templates/cart/totals.phtml
> +        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
@sivaschenko this would demand other improvements to the code. This can be done in some other task. It's resolving the bug perfectly.

2018-12-09 15:45 UTC, tiagosampaio commented
I'm still working on this.

2018-12-28 20:54 UTC, tiagosampaio commented
Hey guys, please I need you to review this PR.

2019-01-02 21:00 UTC, sivaschenko commented
This pull request should be on hold until the up port is merged

2019-07-10 16:47 UTC, VladimirZaets commented
Hi @tiagosampaio. The branch `2.2-develop` will be closed for contribution from **July 15, 2019**. Please finish all your Pull Requests till this date, otherwise, they will be closed.
Thanks for collaboration.

2019-07-15 10:30 UTC, orlangur commented
@VladimirZaets same here, it looks like https://github.com/magento/magento2/pull/19393 is stuck on @sivaschenko side.

2019-07-15 22:30 UTC, VladimirZaets commented
Hi @tiagosampaio. 
The next 2.2 release will be the last of functional releases.
Due to it, we are closing 2.2-develop for contribution and all not ready for delivery Pull Requests. 
Thanks for collaboration.

2019-07-15 22:30 UTC, closed without merging