[Backport-2.2] Code generation improvement for php 7.1
magento/magento2 pull request #19398
Opened 2018-11-24 15:21 UTC by swnsma

Code generation improvements.
### Description
Improve code generation for proxies and interceptors.
Fix not supported nullable return types and parameters in interceptors, variadics and return types like 'self'.
Make changes compatible with PHP 7.0.
Rework of #16337

### Fixed Issues

1. magento/magento2#15505: Interceptor class methods do not support nullable return types
2. MAGETWO-89899: Proxy/Interceptor generator does not understand PHP 7.1 syntax
3. MAGETWO-95415: Can't generate Plugin if object method returns self

### Manual testing scenarios
Create class with usage:
1. variadics
2. nullable type return/parameter
3. return type 'self'
Check in scope of PHP7.0 and PHP7.1

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-24 15:22 UTC, magento-engcom-team commented
Hi @swnsma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-26 08:55 UTC, orlangur requested changes
Great @swnsma, almost perfect! Thanks for combining so many improvements in a single backport.

2018-11-26 08:55 UTC, orlangur commented on lib/internal/Magento/Framework/Interception/Code/Generator/Interceptor.php
> + ˚*
Some junk.

2018-11-26 08:55 UTC, orlangur commented on dev/tests/integration/testsuite/Magento/Framework/Code/GeneratorTest.php
> +            $this->assertTrue(true);
`markTestSkipped` must be used in case of lower PHP version instead, please fix all occurrences.

2018-11-26 09:36 UTC, swnsma commented
Hi @orlangur,
Thank you for your review.
Requested changed have been applied.

2018-11-26 12:39 UTC, orlangur approved these changes
Wow, man, I didn't even know of this feature :O 👍 

https://phpunit.readthedocs.io/en/7.3/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests-requires-tables-api looks like a lot of manual checks in our tests may be refactored.

2018-11-26 12:40 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3568](https://jira.corp.magento.com/browse/ENGCOM-3568) has been created to process this Pull Request

2018-11-29 08:51 UTC, merged

2018-11-29 08:52 UTC, magento-engcom-team commented
Hi @swnsma. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.