Fix for incorrectly escapeHtml'd JSON in commit b8f78cc6
magento/magento2 pull request #19422
Opened 2018-11-27 15:57 UTC by insanityinside

This commit fixes a bug where the resize JSON configuration was incorrectly being HTML encoded before being output, preventing CMS image uploads in the admin due to the Javascript failing on the encoded single quote -> &#039; in the code. Relates to new resize code introduced in MAGETWO-94988, commit b8f78cc6.

2018-11-27 15:58 UTC, magento-engcom-team commented
Hi @insanityinside. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-28 09:34 UTC, orlangur requested changes
Hi @insanityinside,

Please add annotation similar to https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Cms/view/adminhtml/templates/browser/content/uploader.phtml#L156 and add more details on steps to reproduce to reveal an issue.

2018-11-28 11:07 UTC, insanityinside commented
Changes made as requested.

Loading the upload image page on the latest 2.2-develop from the CMS page editor results in a javascript error in the console, due to the JSON being incorrectly encoded and being unable to be parsed. Attempting to add an image will trigger the error as soon as the AJAX page tries to load.

2018-11-28 12:24 UTC, orlangur approved these changes

2018-11-28 12:25 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3582](https://jira.corp.magento.com/browse/ENGCOM-3582) has been created to process this Pull Request

2018-11-29 08:51 UTC, merged

2018-11-29 08:53 UTC, magento-engcom-team commented
Hi @insanityinside. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

2018-11-29 10:44 UTC, insanityinside commented
Forward port unnecessary, code is already fixed in 2.3-develop.