add opportunity to cancel  invoice if invoice state == STATE_PAID
magento/magento2 pull request #19439
Opened 2018-11-28 19:53 UTC by omaxmo

### Description (*)
We can cancel invoice if invoice state ==  self::STATE_OPEN but we can't cancelled invoice if invoice state == STATE_PAID.

### Fixed Issues (if relevant)

1. #18509 Can't cancelled invoice if invoice state == STATE_PAID

### Manual testing scenarios (*)
1. Load an invoice programmatically where state == STATE_PAID
2. Call $invoice->cancel()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-28 19:53 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19439) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19439) before we can accept your contribution.<br/>

2018-11-28 19:53 UTC, magento-engcom-team commented
Hi @omaxmo. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-11-28 20:05 UTC, sivaschenko commented
@omaxmo thanks for the contribution!

I see there is an open question in the issue https://github.com/magento/magento2/issues/18509#issuecomment-442535722

Can invoice be cancelled if it is paid? If yes then should cancellation create a credit memo ond refund the paid sum?

2018-11-28 21:47 UTC, omaxmo commented
> @omaxmo thanks for the contribution!
> 
> I see there is an open question in the issue [#18509 (comment)](https://github.com/magento/magento2/issues/18509#issuecomment-442535722)
> 
> Can invoice be cancelled if it is paid? If yes then should cancellation create a credit memo ond refund the paid sum?

@sivaschenko Magento had opportunity to cancel  invoice with state == STATE_PAID. The opportunity has been lost in  #9968 #11261 . 

Not sure about credit memo and refund.
Before we just 
     ```
   if ($this->getState() == self::STATE_PAID) {
            $order->setTotalPaid($order->getTotalPaid() - $this->getGrandTotal());
            $order->setBaseTotalPaid($order->getBaseTotalPaid() - $this->getBaseGrandTotal());
        }
```

Anyway we have some code which will never be used if we not have  opportunity to cancel invoice if invoice state == STATE_PAID
     ```
   if ($this->getState() == self::STATE_PAID) {
            $order->setTotalPaid($order->getTotalPaid() - $this->getGrandTotal());
            $order->setBaseTotalPaid($order->getBaseTotalPaid() - $this->getBaseGrandTotal());
        }
```

2018-11-28 21:56 UTC, larsroettig requested changes
This PR will break the most PSP-Provider we should close.

For more Information see:
https://github.com/magento/magento2/pull/11261/files

2018-11-29 03:21 UTC, rodrigowebjump commented
@omaxmo Could you double check if these changes break PR 11261?

@larsroettig From my perspective, this will not break the PR, since isCanceled will prevent invoice to be canceled again.

2018-11-29 07:10 UTC, SikailoISM commented
Duplicate copy of another pull request
https://github.com/magento/magento2/pull/19433

2018-11-29 08:57 UTC, VladimirZaets commented
@omaxmo As I see the button to cancel invoice is also available only in the case when status is open

2018-11-29 09:48 UTC, orlangur commented
@omaxmo this is not a valid change, reported issue is closed as invalid, see https://github.com/magento/magento2/issues/18509#issuecomment-442742113 for more details.

Thanks for collaboration!

2018-11-29 09:48 UTC, closed without merging