Fix issue 19492 - Catalog Product - Customizable Options label alignment issue
magento/magento2 pull request #19493
Opened 2018-12-01 06:28 UTC by speedy008

### Description (*)

Magento 2.3-develop 
 Catalog Product - Customizable Options label alignment issue 
### Fixed Issues (if relevant)

1.magento/magento2#19492 : Catalog Product - Customizable Options label alignment issue 

### Manual testing scenarios (*)

1.N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-01 06:28 UTC, magento-engcom-team commented
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-01 06:45 UTC, orlangur commented
@speedy008 could you please make one commit instead of four?

2018-12-02 09:57 UTC, sivaschenko requested changes
@speedy008 thanks for the contribution!  Please remove the blank line and squash changes to a single commit.

2018-12-02 09:57 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/web/css/source/forms/_fields.less
> +
Please remove empty line

2018-12-02 10:03 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/web/css/source/forms/_fields.less
> +
Please remove the blank line

2018-12-03 04:57 UTC, speedy008 commented
Hi @sivaschenko 
I have updated code kindly review it.

2018-12-05 10:23 UTC, sivaschenko commented
@speedy008 can you also take a look at https://github.com/magento/magento2/pull/19493#issuecomment-443404710 comment. Please squash commits into a single one

2018-12-08 07:07 UTC, speedy008 commented
Hi @VladimirZaets 
I have Squash 4 commit to one.

2018-12-10 15:02 UTC, sivaschenko approved these changes

2018-12-10 15:03 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3659](https://jira.corp.magento.com/browse/ENGCOM-3659) has been created to process this Pull Request

2018-12-12 20:43 UTC, merged

2018-12-12 20:44 UTC, magento-engcom-team commented
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.