Fix issue 19501 - Sales order Bundle product item alignment issue
magento/magento2 pull request #19502
Opened 2018-12-01 11:04 UTC by abrarpathan19

### Description (*)

1. Magento 2.3 Develop
Sales order Bundle product item alignment issue

### Fixed Issues (if relevant)

1. magento/magento2#19501: Sales order Bundle product item alignment issue

### Manual testing scenarios (*)

1. Admin -> Sales -> Order -> Create New Order
2. Select Customer -> Add Product
3. Choose Bundle Product -> Configure

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-01 11:04 UTC, magento-engcom-team commented
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-02 10:17 UTC, sivaschenko requested changes
@abrarpathan19 thanks for the contribution, please see the review notes

2018-12-02 10:17 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/web/css/source/forms/_fields.less
> +    &.composite-bundle{
Please move styles related to bundle product to `app/design/aminhtml/Magento_Bundle/web/css/source/_module.less`. Also, please add spaces before opening brackets.

2018-12-02 10:17 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/web/css/source/forms/_fields.less
> +            padding-top: 7px;
If the change is actual only for bundle product form, it would be better to use more strict selector

2018-12-05 10:48 UTC, sivaschenko approved these changes

2018-12-05 10:49 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3621](https://jira.corp.magento.com/browse/ENGCOM-3621) has been created to process this Pull Request

2018-12-05 13:27 UTC, sivaschenko commented
Hi @abrarpathan19 please take a look at the screenshot:
![image](https://user-images.githubusercontent.com/2028541/49516383-2e4d2c00-f8a2-11e8-9325-8d63de60ab1b.png)
After applying the fix all the bundle items options are shifted to the top.

2018-12-06 08:46 UTC, abrarpathan19 commented
@sivaschenko 
I have updated code, please review.

2018-12-06 11:28 UTC, sivaschenko commented
@magento-engcom-team give me test instance

2018-12-06 11:28 UTC, magento-engcom-team commented
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

2018-12-06 11:28 UTC, magento-engcom-team commented
Hi @sivaschenko, here is your [new Magento instance](https://pr-19502.instances.magento-community.engineering).
Admin access: [https://pr-19502.instances.magento-community.engineering/admin](https://pr-19502.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-29 03:49 UTC, merged

2019-01-29 03:50 UTC, magento-engcom-team commented
Hi @abrarpathan19. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.