Fix issue 19499 - Catalog bundle product Bundle Items quantity textbox width
magento/magento2 pull request #19500
Opened 2018-12-01 07:53 UTC by abrarpathan19

### Description (*)

Catalog bundle product Bundle Items quantity textbox width set
Currently, quantity textbox width is very large it should be small as per other quantity boxes.
Please review link : http://prntscr.com/lp9jpw

### Fixed Issues (if relevant)

1.magento/magento2#19499 : Catalog bundle product Bundle Items quantity textbox width

### Manual testing scenarios (*)

1.Catalog -> Product -> add/edit (Bundle product)
2.Bundle Items -> add options -> adding product
3.Check quatity box

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-01 07:54 UTC, magento-engcom-team commented
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-02 10:10 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/web/css/source/forms/fields/_control-table.less
> +             .admin__field-control{
Please add space before the bracket

2018-12-02 10:10 UTC, sivaschenko approved these changes

2018-12-02 10:12 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3604](https://jira.corp.magento.com/browse/ENGCOM-3604) has been created to process this Pull Request

2019-01-04 22:32 UTC, sidolov requested changes

2019-01-04 22:32 UTC, sidolov commented on app/design/adminhtml/Magento/backend/web/css/source/forms/fields/_control-table.less
> +        div[data-index='selection_qty'] {
Please, move Bundle related styles . to corresponded module instead of Backend

2019-01-23 19:17 UTC, sidolov commented
Hi @abrarpathan19 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-01-24 05:33 UTC, abrarpathan19 commented
@sidolov Should I move this CSS code to backend\Magento_Catalog\_module.less ?
Thanks

2019-01-28 19:46 UTC, sidolov commented
Hi @abrarpathan19 , you should move it to the Bundle module

2019-02-14 10:26 UTC, abrarpathan19 commented
Hello @sivaschenko, @sidolov 
Thank you for the suggestions, I have moved code to  Magento_Sales, please review

2019-02-14 12:20 UTC, abrarpathan19 commented
@sivaschenko 
I have created Magento_Bundle and moved style, please review.

2019-02-18 13:51 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/Magento_Sales/web/css/source/module/order/_address.less
> -}
Please revert this unnecessary change

2019-02-18 13:56 UTC, sivaschenko requested changes
Hi @abrarpathan19 thanks for the update, please see the code review notes. Can you please squash all the commits into a single one after completing the changes. Thanks!

2019-02-18 13:56 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/Magento_Bundle/web/css/source/_module.less
> +
Please remove extra blank lines, add a blank line at the end of the file and fix the formatting (indents)

2019-02-18 13:56 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/Magento_Sales/web/css/source/module/order/_address.less
> -}
Please revert this change

2019-02-18 13:56 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/Magento_Bundle/web/css/source/_module.less
> +.admin__dynamic-rows {
This selector is too general and can impact element that are not related to bundle product, can you please make it more specific

2019-03-14 17:32 UTC, sidolov commented
@abrarpathan19 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-14 17:32 UTC, closed without merging