magento/magento2#16852 Attribute option does not validate for existin…
magento/magento2 pull request #19511
Opened 2018-12-01 13:36 UTC by otsmyh

### Description (*)

When creating product attribute and their options dynamically magento does not validate the data before inserting it into the database,

1. Magento2.2.3
2. 

### Steps to reproduce

1. Create a product eav attribute dynamically using class (Magento\Catalog\Model\ResourceModel\Eav\Attribute) and set the entity type Id to the type id of catalog_product (See sample code below)  (eg: attribute code = colors)
2. generate a list of possible options and then add those options into that product EAV attribute by using (Magento\Eav\Setup\EavSetup -> AddOption()) (optionarray = 'Black, Blue, White')
3. Generate some more options (pick some of those which are already existed) and add then add them into the product attribute by following the same step describe in step 2. ('White, Green, Purple')

### Expected result

1. Magento should validate the option Array and check if any of the item already exist or not, If it exist then it should not insert that (Possible options need to be in the attribute code should be 'Black, Blue, White, Green, Purple')

### Actual result

1. Magento create duplicate option for the same store even the option already exists. Data in the current option array are ( 'Black, Blue, White, White,  Green, Purple')) check the repetative entry for the option value 'White.'

![image](https://user-images.githubusercontent.com/12829227/42747766-47391122-8910-11e8-90b0-8970e8ce459b.png)

here are the sample code:

For step 1: 

Inject the EaV Attribute Factory in your constructor and perform this action
```
$attributeData = [
                    'attribute_code' => $code,
                    'is_global' => 1,
                    'frontend_label' => $code,
                    'frontend_input' => 'select',
                    'default_value_text' => '',
                    'default_value_yesno' => 0,
                    'default_value_date' => '',
                    'default_value_textarea' => '',
                    'is_unique' => 0,
                    'apply_to' => 0,
                    'is_required' => 0,
                    'is_configurable' => 1,
                    'is_searchable' => 1,
                    'is_comparable' => 1,
                    'is_user_defined' => 1,
                    'is_visible_in_advanced_search' => 1,
                    'is_used_for_price_rules' => 0,
                    'is_wysiwyg_enabled' => 0,
                    'is_html_allowed_on_front' => 1,
                    'is_visible_on_front' => 0,
                    'used_in_product_listing' => 0,
                    'used_for_sort_by' => 1,
                    'is_filterable' => 1,
                    'is_filterable_in_search' => 1,
                    'backend_type' => 'varchar'
                ];
/*** Magento\Catalog\Model\ResourceModel\Eav\AttributeFactory  */ 
                $this->_eavAttributeFactory->create()
                    ->addData($attributeData)
                    ->setEntityTypeId($this->getEntityTypeId('catalog_product'))
                    ->save();
```
Step 2: 
```
        $attribute_code = 'COLOURS';
        $options        =   array('Black', 'Green');

  /*** Magento\Eav\Setup\EavSetup  */
        $this->eavSetupFactory->create()
            ->addAttributeOption(
                [
                    'values' => $options,
                    'attribute_id' => $this->getAttributeIdbyCode($attribute_code) := '4'
                ]
            );
```
Step 3:
```
        $attribute_code = 'COLOURS';
        $options        =   array('Black', 'White');

  /*** Magento\Eav\Setup\EavSetup  */
        $this->eavSetupFactory->create()
            ->addAttributeOption(
                [
                    'values' => $options,
                    'attribute_id' => $this->getAttributeIdbyCode($attribute_code) := '4'
                ]
            );
```

Has been implemented suggested solution.

### Fixed Issue

1. magento/magento2#16852: Magento2 Attribute option does not validate for existing records before insert

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-01 13:36 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19511) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19511) before we can accept your contribution.<br/>

2018-12-01 13:37 UTC, magento-engcom-team commented
Hi @otsmyh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-02 08:11 UTC, orlangur requested changes

2018-12-02 08:11 UTC, orlangur commented on app/code/Magento/Eav/Setup/EavSetup.php
> +                $this->setup->getConnection()->delete($optionTable, ['attribute_id =?' =>$option['attribute_id'], 'sort_order =?' => $sortOrder]);
Removing existing options by sort order is not a reliable solution.

2019-04-03 10:32 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2019-04-03 10:32 UTC, closed without merging