Stringify possible integer of repository label
magento/magento2 pull request #19526
Opened 2018-12-03 12:58 UTC by poveu

In my case line 151 was causing an error with integer given to strtolower function, so I added the missing casting to string

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-03 12:58 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19526) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19526) before we can accept your contribution.<br/>

2018-12-03 12:58 UTC, magento-engcom-team commented
Hi @poveu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-03 12:59 UTC, VladimirZaets commented
Hi @poveu, please, sign CLA, otherwise, we can't process your pull request

2018-12-03 13:32 UTC, orlangur commented
@poveu also, please provide exact steps to reproduce a problem on a vanilla Magento instance.

2018-12-03 13:49 UTC, poveu commented
@magento-engcom-team give me {2.3-develop} instance

2018-12-03 13:56 UTC, orlangur commented
@poveu such instance is not really helpful as there is no CLI access.

Please investigate on your local instance with something like

```
if (!is_string($label)) {
    var_dump($label);
    die;
}
```

2018-12-03 14:13 UTC, poveu commented
> @poveu such instance is not really helpful as there is no CLI access.
> 
> Please investigate on your local instance with something like
> 
> ```
> if (!is_string($label)) {
>     var_dump($label);
>     die;
> }
> ```

Right! Sorry.
var_dump'ing $label gives only "int(0)".
However var_dump'ing $composerData['repositories'] gives:

> array(2) {
>   [0]=>
>   array(2) {
>     ["type"]=>
>     string(8) "composer"
>     ["url"]=>
>     string(25) "https://repo.magento.com/"
>   }
>   ["firegento_extendedimport2"]=>
>   array(2) {
>     ["type"]=>
>     string(3) "vcs"
>     ["url"]=>
>     string(54) "https://github.com/firegento/FireGento_ExtendedImport2"
>   }
> }

2018-12-03 14:22 UTC, orlangur commented
@poveu https://github.com/magento/magento2-community-edition/blob/master/composer.json#L12 wondering how it wasn't found earlier O>o

2018-12-03 14:23 UTC, orlangur requested changes

2018-12-03 14:23 UTC, orlangur commented on dev/tools/UpgradeScripts/pre_composer_update_2.3.php
> +            if (strpos(strtolower((string) $label), 'mage') !== false || strpos($repo['url'], '.mage') !== false) {
There is no sense to search for "mage" in numeric string, please change to

```
if (is_string($label) && strpos(strtolower($label), 'mage') !== false || strpos($repo['url'], '.mage') !== false) {
```

and do commit amend + force push.

2018-12-03 15:26 UTC, orlangur commented
@poveu could you please squash changes into a single commit as I requested? Just tell if you need any assistance with that.

2018-12-03 19:40 UTC, poveu commented
> @poveu could you please squash changes into a single commit as I requested? Just tell if you need any assistance with that.

Actually I have no idea how to squash two commits if I created them via GitHub website GUI... ;)

2018-12-04 05:20 UTC, orlangur approved these changes
@poveu yeah, just noticed there is no real branch behind. Two commits is lesser evil than 2 PRs ;)

2018-12-11 14:53 UTC, orlangur approved these changes

2018-12-11 16:08 UTC, orlangur requested changes
@poveu, sorry, we cannot process contribution from an `unknown repository`.

Could you please re-create this PR using a proper fork? Just apply similar changes via GitHub UI and do no remove fork until PR is merged.

2018-12-11 16:28 UTC, poveu commented
@orlangur haha sure, no problem :) #19711

2018-12-11 16:33 UTC, closed without merging