Set free shipping to all items if address has free shipping
magento/magento2 pull request #19619
Opened 2018-12-07 15:43 UTC by JeroenVanLeusden

### Description (*)
Set free shipping to all quote/order items when address has free shipping flag. In current situation no items will be marked if address has the free shipping flag.

### Fixed Issues (if relevant)
1. None I could find.

### Manual testing scenarios (*)
#### Our use case
1. Create after plugin on `\Magento\OfflineShipping\Model\SalesRule\Calculator::processFreeShipping()`.
2. Set free shipping in that plugin: `$item->getAddress()->setFreeShipping(1);`
3. Items do not receive free shipping flag.

#### Also possible use case
1. Create cart price rule and enable Free Shipping option "For shipment with matching items".
3. Items do not receive free shipping flag.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-07 15:43 UTC, magento-engcom-team commented
Hi @JeroenVanLeusden. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-07 16:12 UTC, sivaschenko commented
@JeroenVanLeusden thanks for the contribution. Is there any manual testing scenario that can be used to reporduce the issue and verify the fix?

2018-12-07 16:26 UTC, Jeroenll commented
@sivaschenko We set the freeShipping flag in an after plugin of `\Magento\OfflineShipping\Model\SalesRule\Calculator::processFreeShipping()`.

We import orders from another sales channel and want to use magaento's shipping methods but force free shipping because that will be included in the product prices.

In the plugin we do:
```PHP
$link = true /* Do some checks here to determine if the order is imported from different sales channel .*/

if ($link !== null) {
    $cartItem->getAddress()->setFreeShipping(1);
    $cartItem->setFreeShipping(1);
}
```

This will set the flag on the first product only. Where we expect it to be on every order item since we set it to the address.

### Manual testing scenarios
1. Activate flatrate shipping method and set a price.
2. Programmatically create an order with multiple products.
3. Set flatrate shipping method and convert quote to order.
4. Shipping costs should be 0 but they're not.

2018-12-07 16:37 UTC, sivaschenko approved these changes

2018-12-07 16:39 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3637](https://jira.corp.magento.com/browse/ENGCOM-3637) has been created to process this Pull Request

2019-02-25 15:06 UTC, sivaschenko commented
@magento-engcom-team give me test instance

2019-02-25 15:06 UTC, magento-engcom-team commented
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

2019-02-25 15:07 UTC, magento-engcom-team commented
Hi @sivaschenko, here is your [new Magento instance](https://pr-19619.instances.magento-community.engineering).
Admin access: [https://pr-19619.instances.magento-community.engineering/admin](https://pr-19619.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-01 11:29 UTC, sivaschenko requested changes
Hi @JeroenVanLeusden there is an issue on the pull request code base: all shipping methods became free if free shipping method is applied:

![image](https://user-images.githubusercontent.com/2028541/55324355-b5d63080-5479-11e9-8ec7-c905082c745c.png)

2019-04-05 14:54 UTC, JeroenVanLeusden commented
Will look into this in the coming weeks.

2019-04-17 12:53 UTC, JeroenVanLeusden commented
@sivaschenko What steps did you follow to get that result? When i try this on the test instance created on 25 Feb it will show me $5 for flat rate.

![Schermafbeelding 2019-04-17 om 14 53 05](https://user-images.githubusercontent.com/14925052/56289119-8897ac80-6120-11e9-8805-2e2e233ff4a4.png)

2019-04-17 16:04 UTC, sivaschenko commented
@magento-engcom-team give me test instance

2019-04-17 16:04 UTC, magento-engcom-team commented
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

2019-04-17 16:05 UTC, magento-engcom-team commented
Hi @sivaschenko, here is your [new Magento instance](https://pr-19619.instances.magento-community.engineering).
Admin access: [https://pr-19619.instances.magento-community.engineering/admin](https://pr-19619.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-17 16:19 UTC, sivaschenko commented
I wasn't able to reproduce the issue during the retest. @nmalevanec can you please take a look if you can reproduce it?

2019-04-18 10:13 UTC, nmalevanec commented
@sivaschenko, I've done such steps:
1. Enable Free shipping method
2. Create simple product.
3. Create cart price rule with coupon and action like:
![image](https://user-images.githubusercontent.com/11520943/56353938-3ff0f980-61db-11e9-95e8-07de44f818cc.png)
4. Add product to cart on storefront
5. Navigate to cart and apply coupon
6. Observe result
![image](https://user-images.githubusercontent.com/11520943/56353997-644cd600-61db-11e9-9859-ae8cc9b45575.png)
The same result on 2.3-develop mainline.
Also, such result I've got with plugin mentioned in manual testing scenarios without rules.

2019-04-23 12:05 UTC, sivaschenko commented
Hi @JeroenVanLeusden can you please check if the information provided in the comment above helps you to reproduce the issue

2019-04-23 12:20 UTC, JeroenVanLeusden commented
Yes will do, thanks for the additional information.

2019-06-25 22:04 UTC, sidolov commented
@JeroenVanLeusden , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-25 22:04 UTC, closed without merging