Fixed URL pre-selection of configurable product swatches with associated product images throws JavaScript error #18017 In Magento 2.2
magento/magento2 pull request #19627
Opened 2018-12-08 05:26 UTC by niravkrish

### Description (*)

When pre-selecting a configurable product swatch that has an image, Magento will try to load that image in the product gallery before it is initialized, throwing a JavaScript error.

### Fixed Issues (if relevant)

1. magento/magento2#18017: URL pre-selection of configurable product swatches with associated product images throws JavaScript error

### Manual testing scenarios (*)

1. Hit Url With Url domain.com/montana-wind-jacket.html#93=53
2. Test with normal configurable product on listing page as well as on Product Details Page

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-08 05:27 UTC, magento-engcom-team commented
Hi @niravkrish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-11 10:15 UTC, VladimirZaets commented on app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js
> +            if (eventName === undefined && gallery !== undefined) {
Hi @niravkrish, thanks for collaboration. Please use `typeof` (typeof gallery === undefined) or cast value to bolean uses !! (!!galery).

2018-12-26 13:37 UTC, VladimirZaets approved these changes

2018-12-26 13:40 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3751](https://jira.corp.magento.com/browse/ENGCOM-3751) has been created to process this Pull Request

2018-12-26 13:48 UTC, DanielRuf requested changes
Please use `"undefined"`.

2018-12-27 05:43 UTC, niravkrish commented
Hello @DanielRuf 

undefined is a keyword. as per your suggestion "undefined" is treat as string.

so please give me reason to change undefined to "undefined"

2018-12-27 07:31 UTC, DanielRuf commented
> undefined is a keyword

This is not correct. There is no variable `undefined`, please see the strict cide on JavaScript. Also `typeof` returns a string, eg `"undefined"`.

2018-12-27 07:31 UTC, DanielRuf commented
> undefined is a keyword

This is not correct. There is no variable `undefined`, please see the strict mode in JavaScript. Also `typeof` returns a string, eg `"undefined"`.

2019-01-17 14:56 UTC, sdzhepa commented
Hello @niravkrish 
During testing our QA engineer faced an issue.
Could you please have a look and fix it?

Please see the quote of QA comment after testing on branch with the PR

**Problem:** _PR doesn't fix issue #18017_

**Manual testing scenario:**

1. Create two option for configurable product based on Visual Swatch attribute
2. Set Use Web Server Rewrites=No
3. Open the configurable product page, with the option pre-selected.
` magento_site/index.php/conf1.html#135=4`

**Actual Result:** Not OK,
![19635pr](https://user-images.githubusercontent.com/3409584/51323729-9f6f2a00-1a71-11e9-9f04-d3f5b8791b52.png)




Thank you for contribution and collaboration

2019-01-31 05:06 UTC, niravkrish commented
I have already change code suggested by reviewer.
 
Please review it and let me know for further changes.

2019-02-05 14:09 UTC, sivaschenko commented
Hi @niravkrish can you please merge the mainline and resolve conflicts.
Looks like there is a partial resolution of the issue already present in mainline.

2019-02-11 18:42 UTC, sivaschenko commented
Hi @niravkrish thanks for branch update. I wonder if issue was fixed on fresh 2.2-develop? It contained very similar code to this pull request that was replaced by the merge commit: https://github.com/magento/magento2/pull/19627/commits/c25be183d3af9ccc3e9d1fb4688bb88df2a6829b

2019-02-12 13:35 UTC, niravkrish commented
I think someone already solve this issue.
so I am closing this ticket.

2019-02-12 13:35 UTC, closed without merging