Fixed - Lifetime update syntax error #13309
magento/magento2 pull request #19634
Opened 2018-12-08 06:30 UTC by ssp58bleuciel

### Description (*)
Fixed issue of Lifetime update syntax error

### Fixed Issues (if relevant)
1. magento/magento2#13309: Lifetime update syntax error

### Manual testing scenarios (*)
magento2/lib/internal/Magento/Framework/Cache/Backend/Database.php

Line 435
['id=?' => $id, 'expire_time = 0 OR expire_time>' => time()] 

Should be (question sign is missing):
['id=?' => $id, 'expire_time = 0 OR expire_time>?' => time()]

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-08 06:30 UTC, magento-engcom-team commented
Hi @ssp58bleuciel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-08 23:51 UTC, orlangur requested changes
@ssp58bleuciel please squash changes into a single commit and we are good to go.

2018-12-11 09:13 UTC, ssp58bleuciel commented
@orlangur I have squash the changes into a single commit as per your suggestion.

2018-12-11 12:58 UTC, orlangur approved these changes

2018-12-11 12:59 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3666](https://jira.corp.magento.com/browse/ENGCOM-3666) has been created to process this Pull Request

2018-12-19 17:26 UTC, merged

2018-12-19 17:27 UTC, magento-engcom-team commented
Hi @ssp58bleuciel. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.