Menu - Hover effect Stretch
magento/magento2 pull request #19654
Opened 2018-12-08 11:46 UTC by hardik-krish

### Description (*)

Menu - Hover effect Stretch
### Fixed Issues (if relevant)

1. magento/magento2#19652: Menu - Hover effect Stretch

### Manual testing scenarios (*)

1) Hover on Women (Top menu main category)
2) Go directly on the right of the "Tops" button (without hovering over the Tops text) and try the hover, it 
show the sub-menu.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-08 11:47 UTC, magento-engcom-team commented
Hi @hardik-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-08 13:12 UTC, rogyar requested changes

2018-12-08 13:12 UTC, rogyar commented on lib/web/mage/menu.js
> +            hideDelay: 0,
Unfortunately, we cannot simply remove the delay here. It's done for a purpose (I've described the main point in the original issue https://github.com/magento/magento2/issues/19652). We need another solution here.

2018-12-22 16:34 UTC, rogyar commented
I'm closing this PR due to inactivity. Please, feel free to reopen it if you are going to proceed.

2018-12-22 16:34 UTC, closed without merging