fix: simplify literal boolean checks
magento/magento2 pull request #19674
Opened 2018-12-08 23:05 UTC by DanielRuf

### Description (*)

We can typecast to boolean and check the result directly.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-08 23:05 UTC, magento-engcom-team commented
Hi @DanielRuf. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-08 23:45 UTC, orlangur requested changes

2018-12-08 23:45 UTC, orlangur commented on app/code/Magento/Analytics/Test/Unit/Model/ExportDataHandlerTest.php
> +                (bool) $isArchiveSourceDirectory
It's already boolean, no need in typecasting.

2018-12-08 23:45 UTC, orlangur commented on app/code/Magento/Analytics/ReportXml/DB/ColumnsResolver.php
> +                if ((bool) $attributeData['distinct']) {
Will throw notice when not set, `(bool)` casting is redundant here.

Correct replacement: `!empty($attributeData['distinct'])`

2018-12-10 13:42 UTC, closed without merging

2018-12-10 13:42 UTC, magento-engcom-team commented
Hi @DanielRuf
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/19672 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.