[TASK] Return Order Increment Id when placing order so this is correc…
magento/magento2 pull request #19713
Opened 2018-12-11 19:09 UTC by lewisvoncken

…tly displayed in PWA

### Description (*)

When you place an order it should return the Increment Id and not the entity id

### Before changes
![image](https://user-images.githubusercontent.com/6040343/49823697-9909d600-fd80-11e8-917c-ce43535ad9b0.png)

### After Changes
![image](https://user-images.githubusercontent.com/6040343/49823645-7a0b4400-fd80-11e8-95fd-87eae819fd22.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-11 19:09 UTC, magento-engcom-team commented
Hi @lewisvoncken. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-11 19:18 UTC, orlangur requested changes

2018-12-11 19:18 UTC, orlangur commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +        return $order->getIncrementId();
This change is incorrect: https://github.com/magento/magento2/blob/65a8c75ba70bcb446865ce183e9d5b3c020d51ed/app/code/Magento/Quote/Api/CartManagementInterface.php#L64

Please apply a fix in a proper place.

2018-12-12 11:18 UTC, lewisvoncken commented
@orlangur 
Thanks for the Feedback! I have created a separate API call to retrieve the Last Order Information, which is used in the pr https://github.com/magento-research/pwa-studio/pull/649

2018-12-12 13:41 UTC, orlangur commented
@antonkril @buskamuza please review new API addition.

Shouldn't we retrieve OrderID and then obtain IncrementID with a separate API call instead of this?

2018-12-12 14:09 UTC, lewisvoncken commented
@orlangur That was my first solution but when you have guest order you are not authorised to retrieve the order information.

2018-12-12 15:36 UTC, nuzil commented
Hi here, if we are talking about creating REST API call for PWA usecase, I may think its a wrong approach. As I know main idea of PWA in the future is to be fully dependent from GraphQL API and not to REST. My thoughts that we need it on only in GraphQL, or in this case in both implementations.

2018-12-12 15:36 UTC, nuzil commented
@zetlen can you maybe add something? or I'm wrong here?

2018-12-12 15:41 UTC, Vinai commented
I would like it if the naming of the classes would be a bit more descriptive.

For one, there is no management capability involved, the class is only about querying information.
I suggest dropping the `Management` from the name.

And since the use case is coupled to the current session, I think the name `LastOrderInformationInterface` is lacking.
Just looking at the interface, I expect to be able to retrieve the last order information for the currently logged in customer, regardless if the last order was placed during the current session or in a previous session. 

So how about naming the API endpoint and class  `CurrentSessionLastOrderInformationInterface`?

2018-12-12 16:02 UTC, zetlen commented
@nuzil is right; any customer-facing use cases should be implemented in GraphQL from now on. @lewisvoncken Thanks for proactively opening this issue! We need to rephrase it and open it in https://github.com/magento/graphql-ce/ instead.

2018-12-12 17:22 UTC, lewisvoncken commented
> @nuzil is right; any customer-facing use cases should be implemented in GraphQL from now on. @lewisvoncken Thanks for proactively opening this issue! We need to rephrase it and open it in https://github.com/magento/graphql-ce/ instead.

@zetlen , @nuzil , @Vinai and @orlangur 
I have just ported it to GraphQL but I haven't implemented it in PWA Studio do you have any advice how to do so?
https://github.com/magento/graphql-ce/pull/298

2018-12-12 17:57 UTC, lewisvoncken commented
@zetlen , @nuzil , @Vinai and @orlangur

I think this PR can be closed because the new one is created.

2018-12-12 17:57 UTC, closed without merging

2018-12-12 18:06 UTC, nuzil commented
@lewisvoncken as I see from PWA pull request update you already found how? :-)