Use repository to load order when manually creating an invoice
magento/magento2 pull request #19727
Opened 2018-12-12 14:34 UTC by JeroenVanLeusden

### Description (*)
Use repository to load order when manually creating an invoice. This way extension attributes are set and can be used later in the flow (e.g. observers).

### Fixed Issues (if relevant)
1. None I could find.

### Manual testing scenarios (*)
1. Create extension attribute on Order entity.
2. Place order and manually capture the invoice.
3. Order + extension attributes should be loaded but they're not.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-12 14:34 UTC, magento-engcom-team commented
Hi @JeroenVanLeusden. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-12 15:22 UTC, orlangur requested changes

2018-12-12 15:22 UTC, orlangur commented on app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/NewAction.php
> +        OrderRepositoryInterface $orderRepository
Please inject new dependencies in backward-compatible manner: https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter

2018-12-12 15:22 UTC, orlangur commented on app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/NewAction.php
> +        parent::__construct($context);
Please call parent constructor first whenever possible.

2018-12-12 15:28 UTC, Jeroenll commented
@orlangur Updated the PR.

2018-12-12 15:33 UTC, orlangur approved these changes

2018-12-12 15:35 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3679](https://jira.corp.magento.com/browse/ENGCOM-3679) has been created to process this Pull Request

2019-01-04 22:30 UTC, sidolov requested changes

2019-01-04 22:30 UTC, sidolov commented on app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/NewAction.php
>              if (!$order->getId()) {
This check doesn't make sense anymore because `orderRepository` will throw an exception in case when order does not exist.

2019-01-16 10:38 UTC, JeroenVanLeusden commented on app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/NewAction.php
>              if (!$order->getId()) {
@sidolov I've removed the check.

2019-01-16 14:54 UTC, sidolov approved these changes

2019-01-16 14:56 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-3679](https://jira.corp.magento.com/browse/ENGCOM-3679) has been created to process this Pull Request

2019-03-21 16:59 UTC, sivaschenko commented
@kandy can you please approve the performance degradation introduced by this PR:

`Invoice Start (Admin Returns Management) - Another one: 35.6% (mainline = 45 | team = 61) -> DEGRADATION`

2019-03-21 17:27 UTC, kandy commented
@sivaschenko Degradation on Invoice Start Scenario is approved

2019-03-21 19:11 UTC, orlangur approved these changes

2019-03-21 19:13 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3679](https://jira.corp.magento.com/browse/ENGCOM-3679) has been created to process this Pull Request

2019-03-26 16:55 UTC, merged