Fixed #19605 Don't static compile disabled modules
magento/magento2 pull request #19751
Opened 2018-12-13 12:31 UTC by shikhamis11

Fixed issue #19605 Don't static compile disabled modules

Summary (*)
 When running static-content:deploy, there are disabled module content in pub/static.
Examples (*)

Disable modules that have frontend resources.
Run bin/magento setup:static-content:deploy
Observe that pub/static/... contains the resources.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-13 12:31 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-13 12:39 UTC, milindsingh commented
@orlangur why "Community Insider: Cedcommerce" label is not added automatically by @magento-engcom-team ?

2018-12-13 12:48 UTC, shikhamis11 commented
@orlangur may I know why you have added "Progress: on hold" label.

2018-12-14 18:09 UTC, orlangur requested changes
@shikhamis11 looks really clean and nice!

Please apply some minor review notes and do commit amend + force push.

`on hold` was to get a small feedback in Slack if there could be some undesired consequences by this change. For example, URL Rewrites are created even for disabled products so that you can enable them later without any collision.

2018-12-14 18:09 UTC, orlangur commented on app/code/Magento/Deploy/Collector/Collector.php
> +     * Module Manager object
Such comment is not really useful, please leave type hint only.

2018-12-14 18:09 UTC, orlangur commented on app/code/Magento/Deploy/Collector/Collector.php
> +        Manager $moduleManager
Please inject new dependencies in backward-compatible manner: https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter

2018-12-15 06:48 UTC, shikhamis11 commented
@orlangur I have made changes please check

2018-12-15 09:19 UTC, orlangur approved these changes

2018-12-15 09:20 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-3701](https://jira.corp.magento.com/browse/ENGCOM-3701) has been created to process this Pull Request

2018-12-21 23:41 UTC, merged

2018-12-21 23:43 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.