Fixed minicart cancel button area overlapping issue
magento/magento2 pull request #19839
Opened 2018-12-17 09:23 UTC by gelanivishal

Fixed minicart cancel button area overlapping issue on v2.3

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#19836: Minicart cancel button area overlapping to cart subtotal label

### Manual testing scenarios (*)

Step 1: Go to base url (frontend)
Step 2: add any product in cart fron catagory page aor any sigle product
Step 3: click to minicart icon in header
Step 4: Move mouse over the close button
![2018-12-17_14-48-04](https://user-images.githubusercontent.com/12389799/50077811-74dc4800-020b-11e9-8be8-050d093ecd12.jpg)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-17 09:23 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-17 10:07 UTC, milindsingh reviewed
I have updated with the proper changes.

2018-12-17 10:09 UTC, milindsingh requested changes
Can you squash and update

2018-12-17 11:22 UTC, VladimirZaets approved these changes

2018-12-17 11:24 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3706](https://jira.corp.magento.com/browse/ENGCOM-3706) has been created to process this Pull Request

2018-12-19 17:26 UTC, merged

2018-12-19 17:27 UTC, magento-engcom-team commented
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.