MUI controller lacks JSON response, instead returns status 200 with empty body
magento/magento2 pull request #19859
Opened 2018-12-18 10:29 UTC by woutersamaey

### Description (*)
Example URL http://hostname/admin/mui/index/render/key/xxx/?namespace=notification_area&sorting%5Bfield%5D=created_at&sorting%5Bdirection%5D=asc&isAjax=true

Can return status 200 with an empty body, when it should return JSON. This later causes a JavaScript error because data.items does not exist.

This happens when the admin user does not have enough ACL rights to this controller.

### Fixed Issues (if relevant)
1. Valid JSON response 
2. Correct HTTP status code

### Manual testing scenarios (*)
1. Create an admin with very limited access rights (only orders for example)
2. Go to the orders page.
3. Look for error

data-storage.js:270 Uncaught TypeError: Cannot read property 'items' of null
    at UiClass.onRequestComplete (data-storage.js:270)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at done (jquery.js:9840)
    at XMLHttpRequest.callback (jquery.js:10311)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-18 10:29 UTC, magento-engcom-team commented
Hi @woutersamaey. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-18 10:42 UTC, woutersamaey commented
Forgot the return line at the end. Added it to the PR. Sorry.

2018-12-18 16:16 UTC, sidolov commented
@magento-engcom-team give me 2.3-develop instance

2018-12-18 16:16 UTC, magento-engcom-team commented
Hi @sidolov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2018-12-18 16:16 UTC, magento-engcom-team commented
Hi @sidolov, here is your [Magento instance](https://i-19859-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19859-2-3-develop.instances.magento-community.engineering/admin](https://i-19859-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2018-12-19 11:39 UTC, sivaschenko commented
@magento-engcom-team give me test instance

2018-12-19 11:40 UTC, magento-engcom-team commented
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

2018-12-19 11:40 UTC, magento-engcom-team commented
Hi @sivaschenko, here is your [new Magento instance](https://pr-19859.instances.magento-community.engineering).
Admin access: [https://pr-19859.instances.magento-community.engineering/admin](https://pr-19859.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2018-12-19 11:49 UTC, sivaschenko commented
Hi @woutersamaey thanks for your contribution! Could you please fix the code style for static tests to pass.

With your fix an admin with limited permissions will see the screen like:
![image](https://user-images.githubusercontent.com/2028541/50218453-eb9c5100-0383-11e9-9f27-c293bf4844ab.png)

It would be nice to have an appropriate error (Not enough permissions), however, that's probably out of this pull request scope.

2018-12-19 11:56 UTC, woutersamaey commented
@sivaschenko You're right about this error message and indeed, it is out of scope. This error can come up in a number of situations and it's always vague. A more thorough refactoring is needed.

Also, the notifications should not try to load in the first place, as the user doesn't have the required rights, so dealing with the root cause would be best.

These could be 2 new separate issues.

About the code style, this is just another one of those "i dont like else-statements" messages. We've ignored those in the past due to an overzealous Codacy.

2018-12-20 13:40 UTC, sivaschenko requested changes
Hi @woutersamaey thanks for your reply. We will not be able to merge the pull request to mainline without code style fixes. Please see my code suggestions. All you need to to do is to add these suggestions to batch and then commit them using github UI.

2018-12-20 13:40 UTC, sivaschenko commented on app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php
> +            }else {
```suggestion
            } else {
```

2018-12-20 13:40 UTC, sivaschenko commented on app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php
> +                        'errorcode' => 403]
```suggestion
                        'errorcode' => 403
```

2018-12-20 13:40 UTC, sivaschenko commented on app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php
> +                );
```suggestion
                ]);
```

2018-12-20 13:52 UTC, woutersamaey commented
@sivaschenko OK, now I see what you mean. Thanks for preparing this for me. I have commited your suggestions.

Is everything OK now? Honestly I'm not 100% familiar with Github so please excuse me if I didn't understand correctly.

2018-12-20 13:54 UTC, sivaschenko approved these changes

2018-12-20 13:55 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3725](https://jira.corp.magento.com/browse/ENGCOM-3725) has been created to process this Pull Request

2019-03-16 15:01 UTC, merged