Added required error message.
magento/magento2 pull request #19870
Opened 2018-12-19 09:10 UTC by vinogcs

If any JSON error occurs user will be be shown error message if the app mode is not in Production.

### Description (*)

Added error description in JSON serialization. 

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-19 09:10 UTC, magento-engcom-team commented
Hi @vinogcs. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-19 09:10 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19870) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19870) before we can accept your contribution.<br/>

2018-12-19 11:29 UTC, sivaschenko commented
Hi @vinogcs thanks for your contribution! In my opinion the error message should be the same for production and dev environments. For production/frontend such errors should be properly handled on the higher layer catching that exception and adding a message that is understandable for user (as I think both error message and added description are not user-friendly).

2018-12-20 04:32 UTC, vinogcs commented
Hi @sivaschenko, I agree to your point that it has to be taken care by developers at their end and the error message I've added are not clearly understandable. But many non-technical people are adopting Magento for their E-Commerce and non E-Commerce application today. There are few places where these are directly shown to end users who don't have any idea what the error is.

Yesterday, one of my MIS team tried to import products from CSV, they got this error and had no idea what the actual problem was and internet and stack overflow failed when they searched with the error message "Unable to serialize value". 

So I thought it could be better to have little more description on error. The error I've added will tell that the problem was with input file, if it is(in my case it was malformed UTF characters).  And I think it will also help developers to include better response to their exception management without worrying about validating input file separately. 

Maybe I'm wrong, it's just my 2 cents.. :)

2018-12-20 13:48 UTC, sivaschenko commented
@vinogcs thanks for details. I completely agree with your point of view! I meant that I don't think `isOnProduction` check is necessary. Considering that the error message is anyway technical, I'd output the detailed error message on both dev and production environments.

If you don't think it's appropriate to output all the details on production environments I'd suggest to dump the details to the log.

Please let me know what do you think about it.

2018-12-20 14:15 UTC, vinogcs commented
@sivaschenko I think you're right. It would consume more resources to check the state of the app just to show the error message. We can just go for showing error irrespective of the environment.

2019-01-02 17:59 UTC, sivaschenko commented on lib/internal/Magento/Framework/Serialize/Serializer/Json.php
> +    }
Removing trailing spaces
```suggestion
    }
```

2019-01-02 18:03 UTC, sivaschenko requested changes
Hi @vinogcs , thanks for your update! Please consider removing of added trailing spaces as per my suggestio

2019-01-03 06:53 UTC, vinogcs commented
Oops!. My Bad.

2019-01-03 14:01 UTC, sivaschenko approved these changes

2019-01-03 14:03 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3782](https://jira.corp.magento.com/browse/ENGCOM-3782) has been created to process this Pull Request

2019-01-03 14:03 UTC, magento-engcom-team commented
@vinogcs thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-01-19 06:56 UTC, merged

2019-01-19 06:58 UTC, magento-engcom-team commented
Hi @vinogcs. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.