Fixed issue #19905 Issue fixed of checkbox alignment in newsletter tab
magento/magento2 pull request #19920
Opened 2018-12-21 05:19 UTC by GovindaSharma

Fixed Issue #19905 Newsletter label and checkbox not aligned proper in admin panel while any customer editing

### Description (*)

Fixed Issue #19905 Newsletter label and checkbox not aligned proper in admin panel while any customer editing

### Fixed Issues (if relevant)

1.magento/magento2 #19905: Newsletter label and checkbox not aligned proper in admin panel while any customer editing

### Manual testing scenarios (*)
Step 1: Go to admin url
Step 2: login to admin panel
Step 3: click on Customers link from left side and under customers click on all customers
Step 4: You see all registered customer grid now you edit any one of them.
Step 5: Now click on newsletter tab and check Newsletter checkbox is not aligned properly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-21 05:19 UTC, magento-engcom-team commented
Hi @GovindaSharma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-21 11:38 UTC, milindsingh approved these changes

2018-12-26 13:29 UTC, VladimirZaets approved these changes

2018-12-26 13:30 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3750](https://jira.corp.magento.com/browse/ENGCOM-3750) has been created to process this Pull Request

2019-01-04 22:25 UTC, sidolov requested changes

2019-01-04 22:25 UTC, sidolov commented on app/design/adminhtml/Magento/backend/web/css/source/forms/_fields.less
> +        &.field-subscription{
Please, move newsletter related styles to corresponded module instead of Backend

2019-01-05 05:27 UTC, GovindaSharma commented
Hello @sidolov There is no css in module newsletter, that's why i put css in backend and since it is backend part i don't think it it is wrong.Please update on this.

2019-01-07 16:11 UTC, sidolov commented
@GovindaSharma , please, create Newsletter folders under app/design and place the new css file there.

2019-01-14 10:23 UTC, GovindaSharma commented
@sidolov i have added only 2 line css code,so is it required to add new css file for the 2 line of css code?please advice me on this.
Thanks

2019-01-28 22:20 UTC, sidolov commented
Hi @GovindaSharma , we are trying to keep all module-related files in one place - module folder to follow modularity principles. So, yes, you should create the new file and move Newsletter related styles to the new file instead of the Backend module. 
Thank you!

2019-02-14 22:47 UTC, sidolov commented
@GovindaSharma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-02-14 22:47 UTC, closed without merging