Refactoring-Magento-AdminNotification-module
magento/magento2 pull request #19939
Opened 2018-12-22 08:23 UTC by agorbulin

### Description (*)
enrich/fix PHPDocs, small refactoring in Magento_AdminNotification

### Fixed Issues (if relevant)
none

### Manual testing scenarios (*)
not necessary

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-22 08:23 UTC, magento-engcom-team commented
Hi @agorbulin. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-24 15:46 UTC, orlangur requested changes

2019-03-24 15:46 UTC, orlangur commented on app/code/Magento/AdminNotification/Model/Feed.php
> +     * @return bool|\SimpleXMLElement
Please inverse order of types as normally this method returns xml.

2019-03-24 15:46 UTC, orlangur commented on app/code/Magento/AdminNotification/Model/Inbox.php
> + * @method setIsRemove(int $value)
There should be `$this` return type for all the setters I believe.

2019-03-24 15:46 UTC, orlangur commented on app/code/Magento/AdminNotification/Model/Inbox.php
> +     * @return array|mixed|null|string
You can do better :)

2019-03-24 15:46 UTC, orlangur commented on app/code/Magento/AdminNotification/Model/Inbox.php
> +     * @return $this|\Magento\Framework\Notification\NotifierInterface
Just `$this`, please. Fix all.

2019-03-24 15:46 UTC, orlangur commented on app/code/Magento/AdminNotification/Model/ResourceModel/Grid/Collection.php
> +     * @return $this|\Magento\AdminNotification\Model\ResourceModel\Inbox\Collection
Just `$this`.

2019-03-24 15:46 UTC, orlangur commented on app/code/Magento/AdminNotification/Model/ResourceModel/Inbox/Collection/Critical.php
> +     * @return $this|\Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
Just `$this`.

2019-03-24 15:46 UTC, orlangur commented on app/code/Magento/AdminNotification/Model/ResourceModel/System/Message/Collection.php
> +     * @param \Magento\Framework\Model\ResourceModel\Db\AbstractDb|null $resource
Nope, `null` must not be passed.

2019-04-08 15:06 UTC, sidolov commented
@agorbulin , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-08 15:06 UTC, closed without merging