Fix swatch overflow issue
magento/magento2 pull request #19933
Opened 2018-12-21 16:35 UTC by JamieRuroc

### Description (*)

   When dealing with multiple store views with different languages the swatch input fields become too small to use and they move off the screen with no way to get to them. This fix adds a min-width to the input fields and handles swatch overflow with a scrollbar.

### Manual testing scenarios (*)

1. Add multiple store views and languages to your store.
2. Open an attribute page within the Backend (Stores > Product > "Attribute").
3. Add more store views / languages until overflow happens.

2018-12-21 16:35 UTC, magento-engcom-team commented
Hi @JamieRuroc. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-21 16:35 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=19933) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19933) before we can accept your contribution.<br/>

2018-12-21 22:08 UTC, sidolov requested changes

2018-12-21 22:08 UTC, sidolov commented on app/code/Magento/Swatches/view/adminhtml/web/css/swatches.css
> +  min-width: 150px;
Please, use correct indentation for styles

2018-12-21 22:25 UTC, JamieRuroc commented on app/code/Magento/Swatches/view/adminhtml/web/css/swatches.css
> +  min-width: 150px;
Indentation has been corrected.

2019-01-03 00:10 UTC, JamieRuroc commented
@sidolov this version has also been updated, thank you.

2019-01-03 15:42 UTC, sidolov commented
Hi @JamieRuroc , thank you for the update! We have the rule that all changes should be delivered to the 2.3-develop first, so, I added "on hold" label for this pull request right now and I'll remove it once #19932 will be merged.
Thank you!

2019-02-07 03:40 UTC, sidolov commented
Hi @JamieRuroc , I am closing this PR because original was closed due to inactivity. 
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-02-07 03:40 UTC, closed without merging