Fix broken widget placeholders after upgrading from 2.2
magento/magento2 pull request #19987
Opened 2018-12-27 09:29 UTC by vovayatsyuk

Affects backend editor when WYSIWYG is enabled and widget declarations are from Magento < 2.3.

### Description (*)
This PR makes two things:
1. Makes visible widget placeholder when `type_name` is not available in widget declaration
2. Makes visible widget name when `type_name` is not available in widget declaration

### Manual testing scenarios (*)
1. Navigate to _Content > Pages_ and create a new page
2. Disable WYSIWYG editor
3. Fill content field with following value (It's a widget code from Magento < 2.3):

   ```
   <div>{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" }}</div>
   ```

4. Enable WYSIWYG editor
5. You will see an error icon instead of widget image

Without patch | With patch
--------------|-----------
![image](https://user-images.githubusercontent.com/306080/50474530-ea91a200-09c9-11e9-828f-c456251db2fd.png) | ![image](https://user-images.githubusercontent.com/306080/50474602-4825ee80-09ca-11e9-85bd-1089e43a1274.png)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-27 09:29 UTC, magento-engcom-team commented
Hi @vovayatsyuk. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2018-12-27 12:00 UTC, orlangur requested changes
@vovayatsyuk old widget declarations should be migrated automatically during upgrade, isn't it?

2018-12-27 12:13 UTC, vovayatsyuk commented
@orlangur oops, didn't test it, I just copy-paste a widget from third-party instructions :)

However, I still think that the code introduced in 2.3 should be improved to be compatible with 2.2 when it's possible.

Additionally, adding a new internal property ("type_name") is not a good solution because it doesn't work well for multiple backend users with different locales.

p.s. We already have a "type" in widget declaration and it's enough to do the rest of work, why pollute widget declaration with new variables?

2018-12-27 12:36 UTC, vovayatsyuk commented
Just checked updated store (2.2 to 2.3). Standard widget wasn't updated in store homepage:

```
{{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="new_products" products_count="8" template="product/widget/new/content/new_grid.phtml"}}
```

2018-12-28 15:51 UTC, orlangur commented
Considering https://github.com/magento/magento2/commit/e4f6d5b2c25e146a11f2c869ecdd4ddbc18476b0#diff-7f5941d4c18c5f77dbccea6c32c5e6b5, @danmooney2 @irenelagno could you please evaluate this suggestion?

2019-03-24 16:11 UTC, orlangur commented
Ping @danmooney2 @irenelagno.

@melnikovi would appreciate your help as you seem to own `Widget` module.

2019-03-25 17:04 UTC, danmooney2 commented
This looks fine.  Ideally type_name should be retained as a fallback for the sake of providing feedback when a type is uninstalled, skipped, etc.

2019-03-25 17:04 UTC, danmooney2 approved these changes

2019-03-26 09:58 UTC, orlangur approved these changes

2019-03-26 09:59 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4584](https://jira.corp.magento.com/browse/ENGCOM-4584) has been created to process this Pull Request

2019-03-28 13:40 UTC, VasylShvorak commented
✔️ QA passed

2019-04-08 11:38 UTC, merged