Added setResources method.
magento/magento2 pull request #20047
Opened 2019-01-02 15:15 UTC by robbertstevens

2019-01-02 15:15 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=20047) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20047) before we can accept your contribution.<br/>

2019-01-02 15:15 UTC, magento-engcom-team commented
Hi @robbertstevens. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-03 13:29 UTC, ihor-sviziev commented
Hi @robbertstevens,
Why it's needed?

2019-01-03 15:04 UTC, robbertstevens commented
@ihor-sviziev Autocompletion

2019-01-04 13:06 UTC, orlangur requested changes

2019-01-04 13:06 UTC, orlangur commented on app/code/Magento/Authorization/Model/Rules.php
> + * @method setResources(array $resource)
Please add return type here and add corresponding getter in form `int[]` or something - as specific as possible.

As always, please do amend commit and force push.

2019-01-09 02:56 UTC, orlangur requested changes

2019-01-09 02:56 UTC, orlangur commented on app/code/Magento/Authorization/Model/Rules.php
> + * @method \Magento\Authorization\Model\Rules setResources(string[] $resource)
Should be `resources`, I believe? Please squash changes into single commit and force push.

2019-01-23 19:16 UTC, sidolov commented
Hi @robbertstevens , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-01-23 19:16 UTC, closed without merging