[2.2] #20068 move caching of source models into abstract source
magento/magento2 pull request #20088
Opened 2019-01-05 12:19 UTC by davidverholen

### Description (*)

Moved caching of source models into abstract source (suggested here: https://github.com/magento/magento2/issues/20068)
2.2 Backport of https://github.com/magento/magento2/pull/20087

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-05 12:19 UTC, magento-engcom-team commented
Hi @davidverholen. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-06 23:16 UTC, sivaschenko commented
Hi @davidverholen , thank you for the contribution. I think the feature introduced in this pull request is suitable for merging to 2.3 only. Please see the pull request acceptance rules for versions here: https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules

2019-01-06 23:21 UTC, sivaschenko requested changes
Hi @davidverholen , thanks for the contribution please see my code review note

2019-01-06 23:21 UTC, sivaschenko commented on app/code/Magento/Eav/Model/Entity/Attribute/Source/AbstractSource.php
> +        if (empty($this->_options)) {
I'd suggest using the default `_options` value that is `null` in the condition to avoid multiple calls to `loadOptions` if no options are available.
```suggestion
        if (null === $this->_options) {
```

2019-01-06 23:25 UTC, sivaschenko commented
@davidverholen please ignore my code review here, as this pull request should be closed, see my comment: https://github.com/magento/magento2/pull/20088#issuecomment-451784742

Please proceed with https://github.com/magento/magento2/pull/20087 instead

2019-01-07 09:23 UTC, closed without merging