[2.3] #20068 move caching of source models into abstract source
magento/magento2 pull request #20087
Opened 2019-01-05 12:11 UTC by davidverholen

### Description (*)

Moved caching of source models into abstract source (suggested here: https://github.com/magento/magento2/issues/20068)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-05 12:11 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=20087) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20087) before we can accept your contribution.<br/>

2019-01-05 12:11 UTC, magento-engcom-team commented
Hi @davidverholen. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-06 23:22 UTC, sivaschenko requested changes
Hi @davidverholen , thanks for the contribution please see my code review note

2019-01-06 23:22 UTC, sivaschenko commented on app/code/Magento/Eav/Model/Entity/Attribute/Source/AbstractSource.php
> +        if (empty($this->_options)) {
I'd suggest using the default _options value that is null in the condition to avoid multiple calls to loadOptions if no options are available.
```suggestion
        if (null === $this->_options) {
```

2019-01-09 02:20 UTC, orlangur commented on app/code/Magento/Eav/Model/Entity/Attribute/Source/AbstractSource.php
> +        if (empty($this->_options)) {
@sivaschenko please avoid Yoda-style conditions

2019-01-09 02:22 UTC, orlangur requested changes
I would suggest changing existing source models also to eliminate unneeded caching logic.

2019-01-09 06:16 UTC, davidverholen commented
@orlangur starting with that, I found a special case pretty fast. Should I just ignore them for now? FOr example \Magento\Eav\Model\Entity\Attribute\Source\Table has 2 additional method parameters for getAllOptions. Also the options are cached by store id and attribute id.
So I would assume in this case it makes sense that the implementation of getAllOptions is overridden with the custom caching mechanic

2019-01-11 18:57 UTC, sivaschenko commented
Hi @davidverholen thanks for your updates! I don't have any code review notes from my side, however, Travis tests should be fixed before we can process the pull request further.

2019-01-11 20:36 UTC, davidverholen commented
@sivaschenko right, but Im' really not sure, why they are failing.

The warnings state:
> Trying to configure method "getAllOptions" which cannot be configured because it does not exist, has not been specified, is final, or is static

but the getAllOptions is just a new public method in the abstract class, which was defined in the interface before, anyway. So did not even change the public api.

also the method definitely exists (since now defined in the abstract class) and is not static or final. I'll try to investigate further but it seems to be an issue with either the tests or with the phpunit mocking mechanism

2019-01-16 21:29 UTC, sivaschenko commented
@davidverholen thanks for the update. I will approve this issue to continue the processing internally.

2019-01-16 21:29 UTC, sivaschenko approved these changes

2019-01-16 21:30 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3886](https://jira.corp.magento.com/browse/ENGCOM-3886) has been created to process this Pull Request

2019-02-14 12:49 UTC, sivaschenko commented
Hi @davidverholen can you please update the branch and resolve conflicts?

2019-04-01 11:05 UTC, sivaschenko requested changes
Hi @davidverholen Unfortunately, we were not able to approve the refactoring and adding new protected methods (that is against backward compatibility policy for patch releases).

We come up with a decision that caching should be implemented for each model separately.

Options caching for models that are missing that can be added in scope of this pull request.

2019-04-15 12:33 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2019-04-15 12:33 UTC, closed without merging