Order API resources updated. #20169
magento/magento2 pull request #20170
Opened 2019-01-10 12:00 UTC by milindsingh

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#20169: Issue title

### Manual testing scenarios (*)

1. Validate Order API actions 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-10 12:00 UTC, magento-engcom-team commented
Hi @milindsingh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-10 12:49 UTC, sivaschenko requested changes
Hi @milindsingh thanks for the contribution! Please see my code review notes

2019-01-10 12:49 UTC, sivaschenko commented on app/code/Magento/Sales/etc/webapi.xml
> +            <!--TODO: review-->
Looks OK to me, please remove the TODO

2019-01-10 12:49 UTC, sivaschenko commented on app/code/Magento/Sales/etc/webapi.xml
> +            <resource ref="Magento_Sales::transactions" />
I think `Magento_Sales::transactions_fetch` is more appropriate for viewing transactions (read only).

2019-01-10 12:49 UTC, sivaschenko commented on app/code/Magento/Sales/etc/webapi.xml
> +            <resource ref="Magento_Sales::transactions" />
I think `Magento_Sales::transactions_fetch` is more appropriate for viewing transactions (read only).

2019-01-10 12:49 UTC, sivaschenko commented on app/code/Magento/Sales/etc/webapi.xml
> +            <resource ref="Magento_Sales::comment" />
Should we use `Magento_Sales::actions_view` here, considering that `Magento_Sales::comment` is used only for adding comments currently?

2019-01-10 13:32 UTC, milindsingh commented
@sivaschenko Thanks for the review. I have updated the code as suggested.

2019-01-11 14:25 UTC, sivaschenko approved these changes

2019-01-11 14:26 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3834](https://jira.corp.magento.com/browse/ENGCOM-3834) has been created to process this Pull Request

2019-01-23 17:49 UTC, merged

2019-01-23 17:50 UTC, magento-engcom-team commented
Hi @milindsingh. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.