3846: Table sales_order field store_name has 32 bytes
magento/magento2 pull request #20204
Opened 2019-01-11 09:25 UTC by nmalevanec

### Original Pull Request
https://github.com/magento-engcom/magento2ce/pull/1113

### Description
Increase store_name length in sales_order, in order to be able to include full information about store e.g:
Main Website
Main Website Store
Default Store View
and not just:
Main Website
Main Website Store
as it is currently.

### Fixed Issues (if relevant)

1. magento/magento2#3846: Table sales_order field store_name has 32 bytes

### Manual testing scenarios

1. Create order from storefront or backend.
2. Observe sales_order.store_name
3. Check, it includes full store information like:
WebsiteName
StoreGroupName
StoreName

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-11 09:25 UTC, magento-engcom-team commented
Hi @nmalevanec. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-25 12:18 UTC, orlangur requested changes
Just noticed I have an older review pending.

@nmalevanec, please check comments.

2019-02-25 12:18 UTC, orlangur commented on app/code/Magento/Sales/Setup/Patch/Schema/UpdateStoreNameLength.php
> +        $connection->modifyColumn(
Why we do not update it via schema change?

2019-02-25 12:18 UTC, orlangur commented on app/code/Magento/Sales/Setup/Patch/Data/UpdateStoreName.php
> +                    ['store_name' => implode(PHP_EOL, $storeName)],
Update it on SQL side instead of a loop in PHP.

2019-03-27 10:57 UTC, orlangur commented
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

2019-04-05 13:44 UTC, nmalevanec commented on app/code/Magento/Sales/Setup/Patch/Data/UpdateStoreName.php
> +                    ['store_name' => implode(PHP_EOL, $storeName)],
@orlangur, I'm not sure I totally understand how to move sql update for multiple tables outside a PHP loop. Could you please give me more details?

2019-04-05 13:55 UTC, orlangur commented on app/code/Magento/Sales/Setup/Patch/Data/UpdateStoreName.php
> +                    ['store_name' => implode(PHP_EOL, $storeName)],
https://stackoverflow.com/questions/4361774/mysql-update-multiple-tables-with-one-query

2019-04-05 14:40 UTC, nmalevanec commented on app/code/Magento/Sales/Setup/Patch/Data/UpdateStoreName.php
> +                    ['store_name' => implode(PHP_EOL, $storeName)],
It's not possible to do such thing with magento adapter, like $connection->update(). Should I do it explicitly with sql query?

2019-04-22 14:35 UTC, orlangur commented on app/code/Magento/Sales/Setup/Patch/Data/UpdateStoreName.php
> +                    ['store_name' => implode(PHP_EOL, $storeName)],
@nmalevanec yep, do it on MySQL side with only one `->query` (just obtain store ids on PHP side).

2019-05-22 23:32 UTC, orlangur requested changes
After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-06-06 08:50 UTC, Nazar65 commented
Hi @orlangur  please review.

2019-06-06 09:51 UTC, orlangur approved these changes

2019-06-06 11:47 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-06-07 21:30 UTC, sidolov commented
Hi @nmalevanec , looks like the issue was fixed in commit https://github.com/magento/magento2/commit/eecedddf13acf2c59978a6817b86b7a7fe045880
I'm closing current PR as not relevant, thank you for your contribution!

2019-06-07 21:30 UTC, closed without merging