patch-14492 : Fixed Create Customer without password is direct confirmed.
magento/magento2 pull request #20250
Opened 2019-01-12 11:49 UTC by ansari-krish

Creating Customer without password is directly confirmed #14492

### Description (*)
Fixed issue when Creating Customer without password is directly confirmed #14492

### Fixed Issues (if relevant)
1. magento/magento2#14492: Creating Customer without password is directly confirmed #14492

### Manual testing scenarios (*)

1. Set Customer Account Confirmation Required from admin
2. Create customer programatically without password using AccountManagementInterface
3. Go to Admin and open Customer from admin (Customer -> All customer), Newly created customer account is confirmed directly.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-12 11:49 UTC, magento-engcom-team commented
Hi @ansari-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-30 11:33 UTC, swnsma requested changes
This check:
$customer->getPasswordHash() == ''

Can be totally removed.

2019-01-30 11:49 UTC, swnsma commented
Hi @ansari-krish 
Thank you for your contribution!
Sorry for delay, there is some time required to communicate with Product Owner of customer functionality.

Please:
1. Check my comment in review.
2. According to new behavior of customer confirmation, we need to do next (in case of confirmation is required):
- if customer have been **created with backoffice**: customer need to be confirmed when he or she enter his/her password (customer will receive link for changing password in email, after account will be created).
- if customer have been **created** with frontend****: customer need to be confirmed **also** when he/she change the password with 'forgot password' functionality.

2019-01-31 05:21 UTC, ansari-krish commented
@swnsma Thanks for the review. I have updated code as per your suggestion. 
Please review.

2019-01-31 08:37 UTC, swnsma commented
Hi @ansari-krish,
Thank you for your changes.

Technically, fix is OK and your fix important bug, but this fix leads to some functional problems.

Please check process of creating account with Admin Panel by Admin.
How it works with your fix:

0. 'Require Emails Confirmation' is set to 'Yes'.
1. Admin creates account for the Customer in Admin Panel.
2. The Customer receives email with ask to change password for newly created account.
3. The Customer does not receive email for account confirmation.
4. The Customer successfully changes password for the account.
5. The Customer tries to login.
6. The Customer can not login and receive message 'This account is not confirmed. Click here to resend confirmation email.'.
7. The Customer asks to resend confirmation email.
8. The Customer receive confirmation email.
9. The Customer confirm account via email link.
10. The Customer able to loggin for his account.

From this scenario, we need to make changes in point n. 4 and confirm account when customer changes a password for his/her account.
Also, account confirmation should work during changing password with 'reset password' functionality.

2019-01-31 09:57 UTC, ansari-krish commented
Hi @swnsma,
Ok, I will check all the scenario which you have sent.

2019-02-01 07:50 UTC, swnsma commented
Hi @ansari-krish 
Thanks!
Please check the expected scenarios.

**Admin Panel**
0. 'Require Emails Confirmation' is set to 'Yes'.
1. Admin creates account for the Customer in Admin Panel.
2. The Customer receives email with ask to change password for newly created account.
3. The Customer does not receive email for account confirmation.
4. The Customer successfully changes password for the account. The account becomes confirmed.
5. The Customer tries to login.
6. The Customer able to loggin for his/her account.

**Frontend**
_Case 1_
0. 'Require Emails Confirmation' is set to 'Yes'.
1. The Customer register account with frontend registration.
2. The Customer receives confirmation email.
3. The Customer do not confirm account.
4. The Customer tries to login.
6. The Customer can not login and receive message 'This account is not confirmed. Click here to resend confirmation email.'.
7. The Customer try to reset his/her password with'forgotpassword' functionality.
8. The Customer receive email for password reset procedure and use link from email.
9. The Customer change his password. The account becomes confirmed.
10. The Customer tries to login.
11. The Customer able to loggin for his/her account.

_Case 2_
0. 'Require Emails Confirmation' is set to 'Yes'.
1. The Customer register account with frontend registration.
3. The Customer receives email for account confirmation and use link from email.
4. The Customer confirm account.
5. The Customer tries to login.
6. The Customer able to loggin for his account.

2019-02-04 08:43 UTC, ansari-krish commented
Hi @swnsma 
Thanks for Review,
I will update you as soon as possible.

2019-02-15 21:46 UTC, sidolov commented
@ansari-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-02-15 21:46 UTC, closed without merging