Fixed issue #20317 : Magento_CheckoutAgreement wysiwyg: true not working
magento/magento2 pull request #20320
Opened 2019-01-15 17:42 UTC by shikhamis11

Fixed issue #20317 : Magento_CheckoutAgreement wysiwyg: true not working

### Preconditions (*)
1. 2.3
3. OS is Manjaro Linux

### Steps to reproduce (*)
1. Edit Magento\CheckoutAgreements\Block\Adminhtml\Agreement\Edit\Form.php _prepareForm() method
2. Change 'content' field to have a true value on 'wysiwyg' key

### Expected result (*)
1. Expected checkout agreements content field to be displayed using the wysywig

### Actual result (*)
1. No changes.
2.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-15 17:42 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-15 17:42 UTC, shikhamis11 commented
@magento-engcom-team give me test instance

2019-01-15 17:42 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

2019-01-15 17:43 UTC, magento-engcom-team commented
Hi @shikhamis11, here is your [new Magento instance](https://pr-20320.instances.magento-community.engineering).
Admin access: [https://pr-20320.instances.magento-community.engineering/admin](https://pr-20320.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-15 17:47 UTC, shikhamis11 commented
I have add default editor ..and once wysiwyg variable is set to set to true . It will also display wysiwyg editor

2019-01-17 14:11 UTC, sivaschenko commented
Hi @shikhamis11 thanks for your contribution, what is the point of providing wysiwyg configuration if wysiwyg is disabled and there is no way to use wysiwyg from the user enterface.

In my opinion, the necessary configuration should be provided when enabling wysiwyg programmatically.

2019-01-17 14:49 UTC, shikhamis11 commented
Hello @sivaschenko
Thanks for the review .Yes you are right there must be configuration for enabling wysiwyg editor in Agreement forms.

2019-01-18 10:58 UTC, sivaschenko commented
HI @shikhamis11 , do you plan to add such configuration in this pull request?

2019-01-18 14:42 UTC, shikhamis11 commented
@sivaschenko yes I am working on that soon I will update changes at this branch

2019-01-18 17:30 UTC, shikhamis11 commented
@magento-engcom-team give me test instance

2019-01-18 17:30 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

2019-01-18 17:31 UTC, magento-engcom-team commented
Hi @shikhamis11, here is your [new Magento instance](https://pr-20320.instances.magento-community.engineering).
Admin access: [https://pr-20320.instances.magento-community.engineering/admin](https://pr-20320.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-18 19:04 UTC, shikhamis11 commented
it seems wyswig content not converted at checkout I have updated code for that too

2019-01-18 19:04 UTC, shikhamis11 commented
@magento-engcom-team give me test instance

2019-01-18 19:05 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

2019-01-18 19:05 UTC, magento-engcom-team commented
Hi @shikhamis11, here is your [new Magento instance](https://pr-20320.instances.magento-community.engineering).
Admin access: [https://pr-20320.instances.magento-community.engineering/admin](https://pr-20320.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-18 19:16 UTC, shikhamis11 commented
@sivaschenko, I have added the changes  Please check

2019-01-19 18:17 UTC, sivaschenko requested changes
Hi @shikhamis11 thanks for your updates! Please see my code review notes.

2019-01-19 18:17 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +    protected $_wysiwygConfig;
Please change the property access level to `private` and remove the `_` prefix from the property name (as recommended by PSR-2 https://www.php-fig.org/psr/psr-2/#42-properties)

2019-01-19 18:17 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
To maintain backward compatibility, please add new dependencies to the end of the list as optional parameters. See "Adding a constructor parameter" section of [Backward Compatibility Policy](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#php) for more details.

2019-01-19 18:17 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +        $showEditor = $this->scopeConfig->getValue(self::XML_PATH_SHOW_EDITOR);
I don't think these variables are necessary as they are used only once, feel free to perform a call directly in the place when the return is needed

2019-01-19 18:17 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Model/AgreementsConfigProvider.php
> +    protected $templateProcessor;
Please change the access level to protected and add this new dependency in a backward compatible way as mentioned in comments above

2019-01-19 18:17 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/etc/module.xml
> +             <module name="Magento_Cms"/>
Please add a new dependency to the `require` section of `composer.json` as well

2019-01-19 18:17 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/etc/adminhtml/system.xml
> +                <field id="enable_editor" translate="label" type="select" sortOrder="25" showInDefault="1" showInWebsite="0" showInStore="0">
please add the introduced configuration node to config.xml with the default value of 0.
I would also suggest renaming the setting to `enable_wysiwyg_editor` and label to "Enable WYSIWYG Editor".

2019-01-21 10:00 UTC, shikhamis11 commented
@sivaschenko Thanks for your review . I have updated the changes but I have doubt for the backward compatibility on file app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php 
I think this is only being used in the CheckoutAgreements modules so is it required to add new dependency as backward compatibility manner ?

2019-01-21 12:16 UTC, sivaschenko commented
@shikhamis11 thanks for your updates! `app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php` may have been extended by the third party developers and we'd like to ensure that there will be no upgrade issues for instances where this class is extended.

2019-01-21 12:22 UTC, sivaschenko requested changes
Hi @shikhamis11 thanks for your updates, please see my code style improvement suggestions

2019-01-21 12:22 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Model/AgreementsConfigProvider.php
> +
Removing spaces
```suggestion

```

2019-01-21 12:22 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/composer.json
> +        "magento/module-cms": "*",
I think that last comma could lead to issues and/or warnings
```suggestion
        "magento/module-cms": "*"
```

2019-01-21 12:22 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Model/AgreementsConfigProvider.php
> +        \Magento\Widget\Model\Template\Filter $templateProcessor = null,
```suggestion
        \Magento\Widget\Model\Template\Filter $templateProcessor = null
```

2019-01-21 12:22 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +         array $data = [],
Fixed alignment
```suggestion
        array $data = [],
```

2019-01-21 12:22 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +         \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig = null,
```suggestion
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig = null,
```

2019-01-21 12:22 UTC, sivaschenko commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +       }else{
```suggestion
       } else {
```

2019-01-21 12:56 UTC, shikhamis11 commented
@sivaschenko Thanks for commit suggestion . I have added the commits . should I squash all commits into single one ?? 

and about the backward compatibility I think we should use that  for the files which are used multiple times inside magento core modules only

2019-01-28 16:47 UTC, sivaschenko approved these changes

2019-01-28 16:48 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3990](https://jira.corp.magento.com/browse/ENGCOM-3990) has been created to process this Pull Request

2019-01-29 12:49 UTC, sivaschenko commented
Hi @shikhamis11 there is an exception on attempt to add new Terms and Conditions, can you please check it. Also, Travis build requires a fix. Thank you.

2019-01-29 12:56 UTC, shikhamis11 commented
@sivaschenko yes I will work on that

2019-01-29 14:28 UTC, shikhamis11 commented
@magento-engcom-team give me test instance

2019-01-29 14:28 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

2019-01-29 14:29 UTC, magento-engcom-team commented
Hi @shikhamis11, here is your [new Magento instance](https://pr-20320.instances.magento-community.engineering).
Admin access: [https://pr-20320.instances.magento-community.engineering/admin](https://pr-20320.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-29 15:03 UTC, shikhamis11 commented
@magento-engcom-team give me test instance

2019-01-29 15:03 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

2019-01-29 15:04 UTC, magento-engcom-team commented
Hi @shikhamis11, here is your [new Magento instance](https://pr-20320.instances.magento-community.engineering).
Admin access: [https://pr-20320.instances.magento-community.engineering/admin](https://pr-20320.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-30 11:30 UTC, shikhamis11 commented
@sivaschenko Please check now I have update changes

2019-01-31 07:37 UTC, sivaschenko commented
@shikhamis11 thank you

2019-03-05 19:20 UTC, sidolov requested changes

2019-03-05 19:20 UTC, sidolov commented on app/code/Magento/CheckoutAgreements/Model/AgreementsConfigProvider.php
> +        Filter $templateProcessor = null
It's better to use `\Magento\Framework\Filter\Template` instead of `Magento\Widget\Model\Template\Filter` and avoid dependency to the `Widget` module

2019-03-05 19:20 UTC, sidolov commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +    const XML_PATH_SHOW_EDITOR = 'checkout/options/enable_wysiwyg_editor';
Please, make this const private

2019-03-05 19:20 UTC, sidolov commented on app/code/Magento/CheckoutAgreements/Block/Adminhtml/Agreement/Edit/Form.php
> +    protected $scopeConfig;
Please, make this property private

2019-03-05 19:20 UTC, sidolov commented on app/code/Magento/CheckoutAgreements/composer.json
> +        "magento/module-cms": "*",
It would be great to find the way to avoid new hard dependency for the module

2019-03-06 06:25 UTC, shikhamis11 commented
@sidolov Thanks for the review. I will work on the changes

2019-03-19 21:03 UTC, sidolov commented
@shikhamis11 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-19 21:03 UTC, closed without merging