aclResource for UIComponent buttons
magento/magento2 pull request #20408
Opened 2019-01-18 14:11 UTC by kassner

### Description

Currently is not possible to hide buttons based on the user role in the admin panel. As the example from this Pull Request, the `Create new Order` button is always shown, even when the user does not have the permission for it. Clicking on the button gives a permission denied page, as expected.

This PR introduces the possibility of defining an `aclResource` for UIComponents buttons, the same way that a [dataSource](https://github.com/magento/magento2/blob/e5c1527902e1cb69ef4da0e4ff50b25355068813/app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_grid.xml#L31) can have.

### Manual testing scenarios

1. Create an admin role without the `Magento_Sales::create` permission;
2. Assign the created role to a new (or existing) user;
3. Login on admin panel with the previous user;
4. Access the sales order grid on admin;
5. The `Create New order` button should not be available;

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-18 14:11 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=20408) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20408) before we can accept your contribution.<br/>

2019-01-18 14:11 UTC, magento-engcom-team commented
Hi @kassner. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-18 14:15 UTC, sivaschenko requested changes
Hi @kassner thanks for your contribution! Please see my code review notes.

2019-01-18 14:15 UTC, sivaschenko commented on lib/internal/Magento/Framework/View/Element/UiComponent/Context.php
> +    protected $authorization;
Please change the access level to private

2019-01-18 14:15 UTC, sivaschenko commented on lib/internal/Magento/Framework/View/Element/UiComponent/Context.php
> +        AuthorizationInterface $authorization,
Please add new dependency to constructor as the last optional parameter (backward compatibility)

2019-01-18 14:17 UTC, sivaschenko commented on lib/internal/Magento/Framework/View/Element/UiComponent/Context.php
> +        AuthorizationInterface $authorization,
Please see "Adding constructor parameters" section for details https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#php

2019-01-18 14:22 UTC, kassner commented
@sivaschenko also, are you able to remove the partner label? I'm not assigned to that partner anymore (I left the team on Github, dunno why it still assigned to).

2019-01-19 17:44 UTC, sivaschenko approved these changes

2019-01-19 17:47 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-3918](https://jira.corp.magento.com/browse/ENGCOM-3918) has been created to process this Pull Request

2019-01-19 17:47 UTC, magento-engcom-team commented
@kassner thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-01-26 20:52 UTC, merged

2019-01-26 20:53 UTC, magento-engcom-team commented
Hi @kassner. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.