[Backport ]issue fixed #20337 Option Title breaking in two line because applying…
magento/magento2 pull request #20420
Opened 2019-01-19 08:49 UTC by irajneeshgupta

… wrong css for manage width

issue fixed #20337 Option Title breaking in two line because applying wrong css for manage width

### Description (*)
issue fixed #20337 Option Title breaking in two line because applying wrong css for manage width

### Manual testing scenarios (*)

1. Login to admin panel
2. Go in Catalog > product section
3. Create new product and go to tab Customizable Options and click on Add option button
    and see first label Option Title (See screenshot shown)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-19 08:49 UTC, magento-engcom-team commented
Hi @irajneeshgupta. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-08 10:05 UTC, rogyar approved these changes

2019-03-08 10:07 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-4459](https://jira.corp.magento.com/browse/ENGCOM-4459) has been created to process this Pull Request

2019-03-12 12:03 UTC, sivaschenko requested changes
Hi @irajneeshgupta thanks for the backport! Can you please include the last commit from the original PR

2019-03-14 15:49 UTC, irajneeshgupta commented
@sivaschenko 
sure

2019-03-26 17:09 UTC, sidolov commented
@irajneeshgupta , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-26 17:09 UTC, closed without merging