'fixes-for-#20414' :: Recent orders grid not aligned from left in mob…
magento/magento2 pull request #20429
Opened 2019-01-21 07:56 UTC by nainesh2jcommerce

…ile as all content aligned from left

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#20414: Recent orders grid not aligned from left in mobile as all content aligned from left
2. ...

### Manual testing scenarios (*)

1. Open frontend
2. Login as customer and go to my account in mobile
3. see Recent Orders section

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-21 07:56 UTC, magento-engcom-team commented
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-24 09:30 UTC, nainesh2jcommerce commented
Hi @magento-engcom-team,
Any news on this PR? thanks!

2019-01-29 07:41 UTC, nainesh2jcommerce commented
Hi @magento-engcom-team,
Any news on this PR?

Thanks!

2019-01-30 13:04 UTC, nainesh2jcommerce commented
Hi @magento-engcom-team please review this PR

2019-02-01 06:33 UTC, nainesh2jcommerce commented
Hi @magento-engcom-team please review this PR.

2019-02-04 11:35 UTC, nainesh2jcommerce commented
@magento-engcom-team any news on this PR?

2019-02-05 18:36 UTC, torhoehn commented
@nainesh2jcommerce Your PR will not progressed faster if you ask for it again and again. At the moment there're quite a lot PRs to be reviewed, so please be patient.

2019-02-06 21:47 UTC, torhoehn commented
@magento-engcom-team give me test instance

2019-02-06 21:47 UTC, magento-engcom-team commented
Hi @torhoehn. Thank you for your request. I'm working on Magento instance for you

2019-02-06 21:48 UTC, magento-engcom-team commented
Hi @torhoehn, here is your [new Magento instance](https://pr-20429.instances.magento-community.engineering).
Admin access: [https://pr-20429.instances.magento-community.engineering/admin](https://pr-20429.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-06 21:55 UTC, torhoehn approved these changes

2019-02-06 21:56 UTC, magento-engcom-team commented
Hi @torhoehn, thank you for the review.
[ENGCOM-4161](https://jira.corp.magento.com/browse/ENGCOM-4161) has been created to process this Pull Request

2019-03-01 12:34 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=20429) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20429) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:x: Nainesh<hr/>**Nainesh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-03-04 11:31 UTC, sivaschenko commented
Hi @nainesh2jcommerce thanks for the pull request. Can you please recommit the changes for this pull request using the GitHub configuration matching your actual GitHub account (author commit email should match email of GitHub account). Also please make sure to include the static tests fix added to the pull request by @nmalevanec 

Once all commits in the pull request are linked to accounts, we'll be able to process the PR further

2019-03-04 11:32 UTC, sivaschenko requested changes
Hi @nainesh2jcommerce thanks for the pull request. Can you please recommit the changes for this pull request using the GitHub configuration matching your actual GitHub account (author commit email should match email of GitHub account). Also please make sure to include the static tests fix added to the pull request by @nmalevanec

Once all commits in the pull request are linked to accounts, we'll be able to process the PR further

2019-03-05 12:44 UTC, nainesh2jcommerce commented
HI @sivaschenko,

I have commit and push this PR again, can you please review.

Thanks!

2019-03-05 13:03 UTC, sivaschenko commented
Hi @nainesh2jcommerce , commits still do not link to your account, please make sure you local git email is configured correctly. See https://help.github.com/en/articles/setting-your-commit-email-address-in-git

2019-03-05 13:11 UTC, nainesh2jcommerce commented
Hi @sivaschenko,

Thanks for the guidance, I have done again commit and push for this PR, can you please review.

2019-03-05 13:18 UTC, sivaschenko commented
@nainesh2jcommerce last commit if fine, thanks! However there are still 3 not linked commits. Can you please remove reset the branch a push all using  single correct commit

2019-03-05 13:58 UTC, nainesh2jcommerce commented
Hi @sivaschenko,

I have made changes as per your request, reset all previous commit and push single commit for this PR, can you please review.

Thanks

2019-03-05 14:10 UTC, sivaschenko approved these changes
Thanks @nainesh2jcommerce

2019-03-05 14:11 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-4161](https://jira.corp.magento.com/browse/ENGCOM-4161) has been created to process this Pull Request

2019-03-07 11:50 UTC, VasylShvorak commented
✔️ QA passed

2019-03-14 19:47 UTC, merged