[Backport]Sorting by Websites not working in product grid in backoffice
magento/magento2 pull request #20514
Opened 2019-01-23 11:44 UTC by XxXgeoXxX

Issue https://github.com/magento/magento2/issues/20511

### Description (*)
#### Preconditions (*)
Magento Version : CE 2.2X
Magento Version : CE 2.3.X

#### Steps to reproduce (*)
Navigate to admin catalog product grid
Using "Columns" selection add Websites'' column in the grid
#### Expected result (*)
Sort by 'Websites' should be working fine.

#### Actual result (*)
Sort by 'websites' product attribute not working. 

### Fixed Issues (if relevant)
Backport for https://github.com/magento/magento2/pull/20512

### Manual testing scenarios (*)
Navigate to admin catalog product grid
Using "Columns" selection add Websites'' column in the grid

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-23 11:44 UTC, magento-engcom-team commented
Hi @XxXgeoXxX. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-24 09:18 UTC, XxXgeoXxX commented
@magento-engcom-team give me 2.2.2 instance

2019-01-24 09:18 UTC, magento-engcom-team commented
Hi @XxXgeoXxX. Thank you for your request. I'm working on Magento 2.2.2 instance for you

2019-03-22 10:37 UTC, rogyar requested changes

2019-03-22 10:37 UTC, rogyar commented on app/code/Magento/Catalog/Ui/Component/Listing/Columns/Websites.php
> +        Helper $resourceHelper,
Please, do not change arguments order. This change goes against backward compatibility. Add the resourceHelper to the very end of the arguments set

2019-04-05 14:12 UTC, sidolov commented
@XxXgeoXxX , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-29 15:42 UTC, sidolov commented
@XxXgeoXxX , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-29 15:42 UTC, closed without merging