Fix custom_options Import doesn't correctly handle '=' and multi-value separators in fields #17597
magento/magento2 pull request #20536
Opened 2019-01-23 15:58 UTC by DenisSaltanahmedov

### Description (*)
The import function in System -> Import doesn't correctly handle custom_options with the multi-value separator field in a value as well as the '='. A simplistic patch attached. Also attached sample data.

### Fixed Issues (if relevant)
1. magento/magento2#17597: custom_options Import doesn't correctly handle '=' and multi-value separators in fields

### Manual testing scenarios (*)
Steps to reproduce
1. Create a Product with options containing '=' in Title.
2. Export products.
3. Import product CSV, created in Step 2, selecting 'Add/Update' Import Behavior.
4. Observe Product options.
##### Expected result
Options are the same as before export.
##### Actual result
Options are modified - '=' and all text after it is absent.

##### Examples
eg. name=EN = #10 Envelope

Expected:
EN = #10 Envelope

Actual:
EN

eg. option_title=10,000

Expected:
10,000

Actual:
10

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-23 15:58 UTC, magento-engcom-team commented
Hi @DenisSaltanahmedov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-24 13:14 UTC, rogyar approved these changes

2019-01-24 13:15 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-3962](https://jira.corp.magento.com/browse/ENGCOM-3962) has been created to process this Pull Request

2019-01-29 11:35 UTC, sivaschenko commented
Hi @DenisSaltanahmedov thanks for the pull request!

There is an issue found by us on the pull request code base: Option values are trimmed after "," during import. I.e. importing `option_title=10,000 will result in `option_title=10`

2019-02-12 21:03 UTC, sidolov commented
Hi @DenisSaltanahmedov , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-27 08:50 UTC, DenisSaltanahmedov commented
I have fixed the case with "," in "option_title" could you check my changes.

2019-04-01 12:16 UTC, sivaschenko requested changes
Hi @DenisSaltanahmedov thanks for the updates! 

The `_parseCustomOptions` function is too long and compex in my opinion. Would you be able to extract the added code to i.e. `getOptionValueParams` private method (the pattern may also be extracted to a private constant) for better readability

2019-04-01 12:19 UTC, DenisSaltanahmedov commented
Hi @sivaschenko thanks
I will add the changes as soon as possible.

2019-04-15 14:21 UTC, sidolov commented
Hi @DenisSaltanahmedov , will you continue work on the pull request?

2019-05-02 13:45 UTC, DenisSaltanahmedov commented
@sidolov yes, I will you continue work soon

2019-05-02 14:11 UTC, DenisSaltanahmedov commented
@sivaschenko I have refactored the code a bit.

2019-05-20 12:00 UTC, sivaschenko requested changes
@DenisSaltanahmedov Thanks for the update! Please see my review notes.

It would be really great if `getOptionValueOptions` method can be refactored with possibly further functions extractions to avoid suppressing the static tests warnings.

2019-05-20 12:00 UTC, sivaschenko commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +    const OPTION_TITLE_PATTERN = '/option_title\=[+-]?([0-9]*.)?[0-9]+/';
Lets make this constant private for complete backward compatibility
```suggestion
    private const OPTION_TITLE_PATTERN = '/option_title\=[+-]?([0-9]*.)?[0-9]+/';
```

2019-05-20 12:00 UTC, sivaschenko commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
The goal is to avoid this `@SuppressWarning`. Will you be able to refactor the method to reduce the cyclomatic complexity?

2019-05-29 05:06 UTC, DenisSaltanahmedov commented
Thanks @sivaschenko
I will add the changes as soon as possible.

2019-06-19 07:20 UTC, engcom-Golf commented
@iivashchenko please review changes

2019-09-19 15:54 UTC, sidolov commented
@DenisSaltanahmedov please, resolve merge conflicts

2019-09-20 12:37 UTC, sivaschenko requested changes
Hi @DenisSaltanahmedov thanks for the updates, can you please add strict types and resolve static test failures (add ignore annotation if it is not possible to avoid array_merge calls).

Also there are several new private methods that looks very similar. Is there a way to extract a generic method there?

Thank you!

2019-09-20 12:37 UTC, sivaschenko commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +    private function getOldOptionsErrorRows(array $options, $productId): array
```suggestion
    private function getOldOptionsErrorRows(array $options, int $productId): array
```

2019-09-20 12:37 UTC, sivaschenko commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +    private function getTypeMismatchErrorRows(array $options, $productId): array
```suggestion
    private function getTypeMismatchErrorRows(array $options, int $productId): array
```

2019-09-20 12:37 UTC, sivaschenko commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +    private function parseOptionValueOption($optionValue)
```suggestion
    private function parseOptionValueOption(string $optionValue): array
```

2019-09-20 12:37 UTC, sivaschenko commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +    private function getOptionValueOptions($optionValues, $rowData)
```suggestion
    private function getOptionValueOptions(array $optionValues, array $rowData): array
```

2019-10-04 15:12 UTC, sidolov commented
@DenisSaltanahmedov I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-10-04 15:12 UTC, closed without merging