magento/magento2#12817: [Forwardport] Coupon code with canceled order.
magento/magento2 pull request #20579
Opened 2019-01-24 13:10 UTC by p-bystritsky

Forwardport for https://github.com/magento-engcom/magento2ce/pull/1095

### Description

The number of coupon code uses is decreased if an order, that previously used this coupon code, is canceled.

### Fixed Issues (if relevant)

1. magento/magento2#12817: Coupon code with canceled order

### Manual testing scenarios

1. Create a Cart Price Rule with Specific Coupon. Set Uses per Coupon to 1.
2. Create Order (1st Order).
3. Apply the Coupon to 1st Order.
4. Place the 1st Order.
5. Create Order (2nd Order).
6. Apply the Coupon to 2nd Order.
7. Message "Coupon code is not valid" appears.
8. Cancel 1st Order.
9. Apply the Coupon to 2nd Order.
10. Message "Your coupon was successfully applied." appears.
11. Create a Cart Price Rule with Specific Coupon. Set Uses per Customer to 1.
12. Repeat steps 2-10 with this Coupon (note than orders must be placed by logged customer). 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-24 13:11 UTC, magento-engcom-team commented
Hi @p-bystritsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-20 12:56 UTC, PascalBrouwers commented
@slavvka Can you just approve this? Because it comes from 2.2.4 branch.

2019-05-25 19:53 UTC, davidverholen commented
closed and reopened to trigger new checks

2019-06-02 11:29 UTC, davidverholen requested changes

2019-06-02 11:29 UTC, davidverholen commented on app/code/Magento/SalesRule/Model/Coupon/UpdateCouponUsages.php
> +    public function execute(Order $subject, bool $increment)
method should have explicit return type
```suggestion
    public function execute(Order $subject, bool $increment): Order
```

2019-06-02 11:29 UTC, davidverholen commented on app/code/Magento/SalesRule/Model/Coupon/UpdateCouponUsages.php
> +    private function updateCustomerRuleUsages(bool $increment, int $ruleId, int $customerId)
```suggestion
    private function updateCustomerRuleUsages(bool $increment, int $ruleId, int $customerId): void
```

2019-06-02 11:29 UTC, davidverholen commented on app/code/Magento/SalesRule/Model/Coupon/UpdateCouponUsages.php
> +    private function updateCouponUsages(Order $subject, bool $increment, int $customerId)
```suggestion
    private function updateCouponUsages(Order $subject, bool $increment, int $customerId): void
```

2019-06-02 11:29 UTC, davidverholen commented on app/code/Magento/SalesRule/Model/ResourceModel/Coupon/Usage.php
> +    public function updateCustomerCouponTimesUsed($customerId, $couponId, $increment = true)
```suggestion
    public function updateCustomerCouponTimesUsed($customerId, $couponId, $increment = true): void
```

2019-06-04 09:19 UTC, p-bystritsky commented
@davidverholen our suggestions committed.

2019-06-05 17:58 UTC, davidverholen approved these changes

2019-06-05 18:01 UTC, magento-engcom-team commented
Hi @davidverholen, thank you for the review.
[ENGCOM-5171](https://jira.corp.magento.com/browse/ENGCOM-5171) has been created to process this Pull Request

2019-06-06 07:06 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-06-06 13:27 UTC, davidverholen commented
@p-bystritsky why did you move it back to changes requested?

2019-06-11 12:26 UTC, p-bystritsky commented
> @p-bystritsky why did you move it back to changes requested?

@davidverholen we had some non-public issues, but now it seems like they are fixed.

2019-07-11 12:16 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-07-14 21:11 UTC, merged