Fixed #18812  Unable to update simple product custom option in cart when quantity is 1
magento/magento2 pull request #20623
Opened 2019-01-25 17:07 UTC by shikhamis11

Fixed #18812  Unable to update simple product custom option in cart when quantity is 1

### Preconditions (*)

1. Magento CE 2.2.5
2. Although reproduced in 2.2.2-2.2.4
3. Backorders disabled, minimum order qty is 1.
4. A simple product with at least one custom option, e.g. size - 1,2,3; price type fixed.

### Steps to reproduce (*)

1. Go to product page and select options and click add to cart. 
2. Go to cart and select "Edit/Update Item"
3. Select different option from original and click update.

### Expected result (*)

1. Redirected back to cart
2. Product custom option updated.

### Actual result (*)

1. Error message on product page.
![image](https://user-images.githubusercontent.com/1066322/47514211-bbe73600-d877-11e8-963e-1d429115c4ee.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-25 17:08 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-25 17:11 UTC, shikhamis11 commented
@magento-engcom-team give me test instance

2019-01-25 17:11 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

2019-01-25 17:11 UTC, magento-engcom-team commented
Hi @shikhamis11, here is your [new Magento instance](https://pr-20623.instances.magento-community.engineering).
Admin access: [https://pr-20623.instances.magento-community.engineering/admin](https://pr-20623.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-01-25 17:51 UTC, shikhamis11 commented
@magento-engcom-team give me test instance

2019-01-25 17:51 UTC, magento-engcom-team commented
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

2019-01-25 17:52 UTC, magento-engcom-team commented
Hi @shikhamis11, here is your [new Magento instance](https://pr-20623.instances.magento-community.engineering).
Admin access: [https://pr-20623.instances.magento-community.engineering/admin](https://pr-20623.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-04 21:58 UTC, orlangur requested changes

2019-04-04 21:58 UTC, orlangur commented on app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator/Initializer/StockItem.php
> +                $origquoteItemId = $this->request->getParam('id');
We must not rely on request and registry as it makes fix quite unreliable.

2019-04-19 16:22 UTC, sidolov commented
@shikhamis11 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-19 16:22 UTC, closed without merging