Fixed issue 13971 Country values missing in admin customer grid for multi-store configuration
magento/magento2 pull request #20812
Opened 2019-01-30 13:13 UTC by Dharmeshvaja91

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#13971: Country values missing in admin customer grid for multi-store configuration
### Manual testing scenarios (*)

1. Manual Testing

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-30 13:13 UTC, magento-engcom-team commented
Hi @Dharmeshvaja91. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-31 22:49 UTC, slavvka requested changes
Hey @Dharmeshvaja91 Thank you for the contribution. Please look at the comments.

2019-01-31 22:49 UTC, slavvka commented on app/code/Magento/Directory/Model/ResourceModel/Country/Collection.php
> +    public function loadByAllStore($store = null)
1. This is [backward incompatible change](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/) as this class has `@api` annotation and you introduced a public method.
1. Does that mean that for any customer there will be shown all countries that even maybe absent for a specific store?

2019-02-15 21:45 UTC, sidolov commented
@Dharmeshvaja91 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-02-18 21:51 UTC, sidolov commented
@Dharmeshvaja91 will you continue progress on this PR?

2019-02-20 04:47 UTC, Dharmeshvaja91 commented
> @Dharmeshvaja91 will you continue progress on this PR?

yes i am working on this.

2019-03-08 15:38 UTC, sidolov commented
@Dharmeshvaja91 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-08 15:38 UTC, closed without merging