Date range validation not happening with CMS page's custom design update
magento/magento2 pull request #20868
Opened 2019-01-31 20:21 UTC by maddumarala

### Description (*)
In the process of creating CMS page, if user wants to  add custom design update, the from_date and to_date validation is not happening. Added a fix for that.

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

Go to Admin>content>pages>Add new page
Add required info
Add custom design update with from date(02/1/2019) and to date(01/20/2019)
No error message given.But in other places which uses this functionality validate the date range(Catalog price rules)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-31 20:21 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=20868) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20868) before we can accept your contribution.<br/><hr/>**Gayajith Maddumarala** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-01-31 20:21 UTC, magento-engcom-team commented
Hi @maddumarala. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-31 22:28 UTC, slavvka commented
Hey @maddumarala thank you for the contribution. Please consider covering the fix with automated tests. Thanks

2019-02-01 08:23 UTC, maddumarala commented
> Hey @maddumarala thank you for the contribution. Please consider covering the fix with automated tests. Thanks

Hi @slavvka , Could you please explain on how to cover this fix with automated tests ? I thought since Travis CI still pending means testing is still running ?

2019-02-01 16:38 UTC, slavvka commented
> > Hey @maddumarala thank you for the contribution. Please consider covering the fix with automated tests. Thanks
> 
> Hi @slavvka , Could you please explain on how to cover this fix with automated tests ? I thought since Travis CI still pending means testing is still running ?

Hey @maddumarala your are right. Travis tests are running. But you added additional validations which should be tested as well - they didn't exist previously and therefore weren't tested. In your case I would suggest adding an integration test to check the validation on the resource model level.

2019-02-15 21:46 UTC, sidolov commented
@maddumarala , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-02-21 12:51 UTC, sivaschenko requested changes
Hi @maddumarala please see the review note. Let us know what help do you need to complete the pull request.

2019-02-21 12:51 UTC, sivaschenko commented on app/code/Magento/Cms/Model/ResourceModel/Page.php
> +    protected function validateDateRange(AbstractModel $object)
Please change the access level of this method to private and cover this validation with integration tests

2019-03-08 15:39 UTC, sidolov commented
@maddumarala , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-08 15:39 UTC, closed without merging