Fixed Checkbox radio shadow 20859
magento/magento2 pull request #20861
Opened 2019-01-31 14:06 UTC by abrarpathan19

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#20859 Luma theme - Input Box and Radio Button shadow is not proper 

### Manual testing scenarios (*)

1. Magento luma theme frontend in all the form
2. You can find checkbox, Radio input box shaddow
3. Reproduce pages : create account page, cart page and chekout page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-31 14:06 UTC, magento-engcom-team commented
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-01-31 19:19 UTC, VladimirZaets approved these changes

2019-01-31 19:20 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4074](https://jira.corp.magento.com/browse/ENGCOM-4074) has been created to process this Pull Request

2019-01-31 22:39 UTC, Karlasa requested changes

2019-01-31 22:39 UTC, Karlasa commented on lib/web/css/source/lib/_resets.less
> +            .lib-css(box-shadow, none);
Hi! 
1) .lib-css(); wrapping is not needed as it has no variables inside to check
2) I would just change line 101 to instead  (just my opinion) 
`input:not([disabled]):not([type="radio"]):not([type="checkbox"])`
Cheers

2019-01-31 22:40 UTC, Karlasa commented
@VladimirZaets Could you double check please ;)

2019-02-01 05:28 UTC, abrarpathan19 commented
@VladimirZaets  & @Karlasa 
I have updated code as per the suggestion can you please review 
Thanks :)

2019-02-01 06:32 UTC, Karlasa approved these changes

2019-02-01 16:40 UTC, VladimirZaets commented
@Karlasa @abrarpathan19  thanks!

2019-02-10 18:22 UTC, merged