Fixed Issue #14633 Sub-admin role related issue in order view page in magento 2 admin
magento/magento2 pull request #20903
Opened 2019-02-03 06:33 UTC by GovindaSharma

Fixed Issue #14633 Sub-admin role related issue in order view page in magento 2 admin

### Description (*)
Fixed Issue #14633 Sub-admin role related issue in order view page in magento 2 admin

### Fixed Issues (if relevant)

1. magento/magento2 #14633: Sub-admin role related issue in order view page in magento 2 admin
2. ...

### Manual testing scenarios (*)

I have created one sub admin user from Magento admin. This user can only view orders, add a comment and operate on shipping. I gave some permissions for sub admin user. Please check the below image:
![screenshotacl](https://user-images.githubusercontent.com/25526052/52173490-896ca380-27ab-11e9-8f80-359601ae262d.png)

So as you can see I have disabled Invoice and Credit memo role of this sub-admin.
But when I logged in as sub admin and go to order view page.Sometime Pop will come with "Something Went Wrong" and sometimes js error comes in console

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-03 06:33 UTC, magento-engcom-team commented
Hi @GovindaSharma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-06 18:48 UTC, sivaschenko requested changes
Thanks for the pull requests @GovindaSharma ! Please take a look at the code review notes. Please apply the fixes not only on the commented line but use the same approach for all the files in the pull request in general.

2019-02-06 18:48 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php
> +        if($this->authorization->isAllowed('Magento_Sales::invoice'))
it is fine to shorten this construction to `return $this->authorization->isAllowed('Magento_Sales::creditmemo');`

2019-02-06 18:48 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php
> +    public function __construct(
Please consider that parent class has constructor
(\Magento\Framework\View\Element\AbstractBlock::__construct), please ensure you call it.

2019-02-06 18:48 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php
> +        $this->authorization = $authorization?: \Magento\Framework\App\ObjectManager::getInstance()->get(Magento\Framework\AuthorizationInterface::class);
Please declare the property

2019-02-06 18:48 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Shipments.php
> +        \Magento\Framework\AuthorizationInterface $authorization = null,
New constructor parameters should be at the end of the list (after $data in this case)

2019-02-09 07:10 UTC, GovindaSharma commented
hi @sivaschenko i have updated all the changes suggested by you.Please check and let me know on this
Thank You

2019-02-12 14:11 UTC, sivaschenko requested changes
Thanks for updates @GovindaSharma ! Please see my code review notes.

2019-02-12 14:11 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Shipments.php
> +    protected $authorization;
please change the access level to private

2019-02-12 14:11 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php
> +    protected $authorization;
please change the access level to private

2019-02-12 14:11 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php
> +    protected $authorization;
please change the access level to private

2019-02-12 14:11 UTC, sivaschenko commented on app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php
> +	     $this->authorization = $authorization ?  : \Magento\Framework\App\ObjectManager::getInstance ()->get ( Magento\Framework\AuthorizationInterface::class );
Please fix code style/formatting for all files

2019-02-12 14:16 UTC, sivaschenko commented
Hi @GovindaSharma it would be great if you can squash all changes to one commit with a meaningful name after the update.

2019-02-12 14:59 UTC, GovindaSharma commented
Hi @sivaschenko sure i will do and update you.
Thanks

2019-02-22 14:44 UTC, sivaschenko requested changes
@GovindaSharma thanks for updates. Please fix code style and use meaningful commit message, i.e. 'magento/magento2#20903: Fixed Issue #14633 Sub-admin role related issue in order view page in magento 2 admin'

2019-03-08 15:28 UTC, sidolov commented
@GovindaSharma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-08 15:28 UTC, closed without merging