Issue#20915: check for undefined index
magento/magento2 pull request #20916
Opened 2019-02-03 08:46 UTC by vinayshah

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#20915: Import Product through CSV from extended module, face un index issue from Abstract Class

### Manual testing scenarios (*)

Facing specific through our extension, though it's a general fix.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-03 08:46 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=20916) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20916) before we can accept your contribution.<br/>

2019-02-03 08:47 UTC, magento-engcom-team commented
Hi @vinayshah. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-03 09:02 UTC, sivaschenko commented
@magento-engcom-team give me 2.3-develop instance

2019-02-03 09:02 UTC, magento-engcom-team commented
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-02-03 09:03 UTC, magento-engcom-team commented
Hi @sivaschenko, here is your [Magento instance](https://i-20916-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20916-2-3-develop.instances.magento-community.engineering/admin](https://i-20916-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-02-03 17:26 UTC, sidolov approved these changes

2019-02-03 17:27 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-4098](https://jira.corp.magento.com/browse/ENGCOM-4098) has been created to process this Pull Request

2019-04-09 10:03 UTC, VasylShvorak commented
Hi @vinayshah I was able to reproduce this issue only with code manipulation. Could you provide csv file  example that caused such error to verify PR changes?

2019-04-23 15:08 UTC, sidolov commented
@vinayshah , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-30 15:45 UTC, vinayshah commented
Hello @sidolov @VasylShvorak, the issue has occurred more of due too specific to our extension, The default Magento flow doesn't allow to add a new attribute value, it only adds existing value. To add new value it creates issue. For this, we need to overwrite the complete code instead of simple isset statement.

2019-08-15 20:22 UTC, sidolov requested changes

2019-08-15 20:22 UTC, sidolov commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Type/AbstractType.php
> - * @api
Please, revert annotation removal

2019-08-30 13:38 UTC, sidolov commented
@vinayshah  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-30 13:38 UTC, closed without merging