Fixed #20917 Alignment Issue While Editing Order Data containing Downlodable Products in Admin Section
magento/magento2 pull request #20920
Opened 2019-02-03 09:03 UTC by pankaj-cedcoss

Alignment Issue While Editing Order Data containing Downlodable Products in Admin Section

### Preconditions (*)
1. Magento 2.2
2. php 7.2

### Steps to reproduce (*)
>> login into admin panel 
>> go to Order grid section from Sales > Orders
>> Edit any order containing downladable product with "Links can be purchased separately" enabled.
>> a modal will appear like http://i.imgur.com/MJePtn5.png
>> now click on configure button, another modal will display and issue will appear

### Expected result (*)
![expected_result](https://user-images.githubusercontent.com/13777300/52174743-410ab100-27be-11e9-8615-f7582a5879ce.png)

### Actual result (*)
![actual_result](https://user-images.githubusercontent.com/13777300/52174746-4a941900-27be-11e9-9e69-19d2cdf87662.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-03 09:03 UTC, magento-engcom-team commented
Hi @pankaj-cedcoss. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-04 17:23 UTC, sidolov requested changes

2019-02-04 17:23 UTC, sidolov commented on app/design/adminhtml/Magento/backend/web/css/source/forms/_temp.less
> +    &.downloadable{
Please, move Downloadable product related styles to the corresponded module instead of Backend

2019-02-18 21:49 UTC, sidolov commented
@pankaj-cedcoss , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-02-18 21:49 UTC, closed without merging