Fixed Issue #17802 Magento 2.2.x import error -> attribute_set instead of attribute_set_code message
magento/magento2 pull request #20948
Opened 2019-02-03 11:44 UTC by krishna221993

Fixed Issue #17802  Magento 2.2.x import error -> attribute_set instead of attribute_set_code message

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<17802>: Magento 2.2.x import error -> attribute_set instead of attribute_set_code message

### Manual testing scenarios (*)

1. Login to Magento Admin
2. Navigate to Import Products screen
3. Use Check Data on a CSV file that doesn't have attribute_set_code, but attribute_set instead

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-03 11:44 UTC, magento-engcom-team commented
Hi @krishna221993. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-04-04 21:23 UTC, orlangur requested changes

2019-04-04 21:23 UTC, orlangur commented on app/code/Magento/CatalogImportExport/Model/Import/Product.php
> +        ValidatorInterface::ERROR_INVALID_ATTR_SET => 'Invalid value for Attribute Set column or attribute_set_code header doesn\'t exist. (set doesn\'t exist?)',
This must be a separate error type.

2019-04-19 16:24 UTC, sidolov commented
@krishna221993 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-19 16:24 UTC, closed without merging