focus-not-proper-on-configurable-product-swatches:: focus not proper …
magento/magento2 pull request #20992
Opened 2019-02-05 11:48 UTC by nainesh2jcommerce

…on configurable product swatches

### Description (*)

On configurable product page, swatches not having proper focus 

### Manual testing scenarios (*)

1. go on configurable product
2. click on add to cart button without selecting seatch

### Expected result (*)
![image](https://user-images.githubusercontent.com/18118539/52271124-d5b11280-2968-11e9-8d49-730cd030ebb5.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/18118539/52271521-e6ae5380-2969-11e9-88cd-c72eb64576db.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-05 11:48 UTC, magento-engcom-team commented
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-05 16:02 UTC, dmytro-ch requested changes
Hi @nainesh2jcommerce, thank you for your contribution!
Could you please fix the issues mentioned in the review?

2019-02-05 16:02 UTC, dmytro-ch commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +                box-shadow: 0 0 3px 1px #00699d;
I guess it would be better to use `@focus__color` variable in this case, or even `@focus__box-shadow`.

2019-02-05 16:02 UTC, dmytro-ch commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +        }
Please make sure you add spaces between adjacent selectors on the same level.

2019-02-05 16:02 UTC, dmytro-ch commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +        * {
I guess this selector is too generic.
The issue should be caused by the `.product-options-wrapper .fieldset` element.
Could you please double check and correct me if I'm wrong?
Thank you.

2019-02-06 10:08 UTC, nainesh2jcommerce commented
Hi @dmytro-ch, I have made changes as per review comments above, can you please review.

Thanks!

2019-02-06 10:36 UTC, dmytro-ch commented
@magento-engcom-team give me test instance

2019-02-06 10:36 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-02-06 10:37 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-20992.instances.magento-community.engineering).
Admin access: [https://pr-20992.instances.magento-community.engineering/admin](https://pr-20992.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-06 10:56 UTC, dmytro-ch approved these changes

2019-02-06 10:57 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4145](https://jira.corp.magento.com/browse/ENGCOM-4145) has been created to process this Pull Request

2019-02-13 15:47 UTC, merged