Credit memo issue if used wrong creditmemo id in the url
magento/magento2 pull request #21019
Opened 2019-02-06 12:16 UTC by GovindaSharma

Fatal error page occurs if use wrong creditmemo id passed in url

### Preconditions (*)

2.3 or 2.3 Develop

Php 7.2

### Descriptions (*)

Fatal error page occurs if use wrong creditmemo id passed in url

### Manual testing scenarios (*)

1. Create An Order In Magento

2. Create invoice and creditmemo of that Order

3. View the created  creditmemo

4. Now change the creditmemo id from url(use that id which does not exist) and run the url.

### Expected result (*)

A proper error message should come without any error

### Actual Result (*)

Fatal error page occurs

![screenshot-i-21010-2-3-develop instances magento-community engineering-2019-02-06-17-03-33](https://user-images.githubusercontent.com/25526052/52340867-f182ea00-2a36-11e9-8051-e4f427d5626c.png)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-06 12:16 UTC, magento-engcom-team commented
Hi @GovindaSharma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-06 13:00 UTC, dmytro-ch commented
Hi #GovindaSharma,
thank you for your contribution!
Please combine the current PR (#21019), #21017 and #21018 into one PR in order to make it easier to process these fixes for Magento Community Engineering team.
Thank you!

2019-02-06 16:41 UTC, GovindaSharma commented
Hi @dmytro-ch ,thanks for your review, i have now combined the PR #21018 , #21017 changes in this PR. Please check and update on this.
Thank You

2019-02-08 08:04 UTC, dmytro-ch commented
Hi @GovindaSharma,
there are a couple of test failures with the current solution.

```
1) Magento\Sales\Test\Unit\Controller\Adminhtml\Order\Creditmemo\ViewTest::testExecuteNoCreditMemo
Error: Call to a member function create() on null
/home/travis/build/magento/magento2/app/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/View.php:78
/home/travis/build/magento/magento2/app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/ViewTest.php:242
2) Magento\Sales\Test\Unit\Controller\Adminhtml\Order\Invoice\ViewTest::testExecuteNoInvoice
Error: Call to a member function create() on null
/home/travis/build/magento/magento2/app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/View.php:47
/home/travis/build/magento/magento2/app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Invoice/ViewTest.php:285
3) Magento\Shipping\Test\Unit\Controller\Adminhtml\Order\Shipment\ViewTest::testExecuteNoShipment
Error: Call to a member function setPath() on null
/home/travis/build/magento/magento2/app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/View.php:75
/home/travis/build/magento/magento2/app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/Shipment/ViewTest.php:204
```

Could you please check and update Unit tests according to the latest changes in code?

Thank you!

2019-02-11 04:58 UTC, GovindaSharma commented
hi @dmytro-ch , i have fixed the unit test cases now,please check and let me know
Thank You

2019-02-13 16:07 UTC, dmytro-ch commented
@magento-engcom-team give me test instance

2019-02-13 16:07 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-02-13 16:07 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21019.instances.magento-community.engineering).
Admin access: [https://pr-21019.instances.magento-community.engineering/admin](https://pr-21019.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-13 16:23 UTC, dmytro-ch approved these changes

2019-02-13 16:24 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4251](https://jira.corp.magento.com/browse/ENGCOM-4251) has been created to process this Pull Request

2019-02-18 18:54 UTC, sivaschenko requested changes
Hi @GovindaSharma thanks for the pull request! Can you please keep existing properties and constructor parameters for backward compatibility purpose. Feel free to mark unneeded properties as deprecated

2019-02-18 20:04 UTC, dmytro-ch commented
@sivaschenko, thank you for the review!
I should have noticed that.
I will try pay more attention to the contribution guide requirements in future.

2019-02-22 11:36 UTC, GovindaSharma commented
hi @sivaschenko i have now added the existing properties.please check and update on this
Thank You

2019-03-05 11:27 UTC, sivaschenko requested changes
Thanks for updates @GovindaSharma , please see my code review comments

2019-03-05 11:27 UTC, sivaschenko commented on app/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/View.php
> +        \Magento\Framework\View\Result\PageFactory $resultPageFactory
Please keep the order of existing constructor parameters for backward compatibility purpose

2019-03-05 11:27 UTC, sivaschenko commented on app/code/Magento/Sales/Controller/Adminhtml/Order/CreditmemoLoader.php
> +                $this->messageManager->addErrorMessage(__('This credit memo no longer exists.'));
I think it will be good to use the same message for `NoSuchEntityException` case

2019-04-10 18:00 UTC, sidolov commented
@GovindaSharma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-10 18:00 UTC, closed without merging