Use default product gallery values - ProductVideo module
magento/magento2 pull request #21041
Opened 2019-02-07 11:52 UTC by Nika-Valkyria

### Description (*)
This pull request continues implementation of the "Use Default" feature for product's gallery attributes and contains adjustment of a gallery admin template in ProductVideo module

These changes are dependent on the following pull request:
[Provide possibility to use default value for Media Gallery Entry attributes #21040](https://github.com/magento/magento2/pull/21040)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-07 11:52 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=21041) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21041) before we can accept your contribution.<br/>

2019-02-07 11:52 UTC, magento-engcom-team commented
Hi @Nika-Valkyria. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-07 21:51 UTC, VladimirZaets commented on app/code/Magento/ProductVideo/view/adminhtml/templates/helper/gallery.phtml
> +        <script>
Hi @Nika-Valkyria. Thanks for collaboration. Please move JS code to separate file and use x-magento-init script to initialization

2019-02-07 21:51 UTC, VladimirZaets commented on app/code/Magento/ProductVideo/view/adminhtml/templates/helper/gallery.phtml
> +<div id="<?= $block->getHtmlId() ?>" style="position: relative"
Please use css classes instead of declaring directly style attribute

2019-02-20 19:22 UTC, Nika-Valkyria commented
Hi, @VladimirZaets! Thank you for the feedback. I've made the required changes, can you please review them?
And there are 2 related pull requests, they are linked in the description, can you please view them too?

2019-02-21 04:31 UTC, ihor-sviziev commented
@magento-engcom-team merge #21040

2019-02-21 04:35 UTC, ihor-sviziev commented
@magento-engcom-team combine #21040

2019-02-21 04:35 UTC, magento-engcom-team commented
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

2019-02-21 04:36 UTC, magento-engcom-team commented
@Nika-Valkyria all pull requests have been successfully combined together:

2019-02-21 04:39 UTC, ihor-sviziev commented
Hi @VladimirZaets,
Looks like something went wrong with combining PRs. Could you check it?

2019-02-21 15:25 UTC, sidolov commented
@magento-engcom-team combine 21040

2019-02-21 15:26 UTC, magento-engcom-team commented
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

2019-02-21 15:28 UTC, magento-engcom-team commented
@Nika-Valkyria all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/21040: Provide possibility to use default value for Media Gallery Entry attributes

2019-02-22 06:59 UTC, ihor-sviziev commented
@magento-engcom-team combine 21040 21369

2019-02-22 06:59 UTC, magento-engcom-team commented
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

2019-02-22 07:00 UTC, magento-engcom-team commented
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/21040 : Pull Request state must be the same for target and source pull request

2019-02-22 08:56 UTC, ihor-sviziev commented
@magento-engcom-team combine 21369

2019-02-22 08:56 UTC, magento-engcom-team commented
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

2019-02-22 08:58 UTC, magento-engcom-team commented
@Nika-Valkyria all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/21369: Use default product gallery values - admin theme styles

2019-02-22 08:59 UTC, ihor-sviziev commented
Hi @Nika-Valkyria,
As you force-pushed this PR, changes from https://github.com/magento/magento2/pull/21040 were lost. And we can't automatically add them again.
Could you add changes from https://github.com/magento/magento2/pull/21040 manually?

2019-02-22 14:53 UTC, Nika-Valkyria commented
I will now merge all the changes from #21040 and #21369 to this pull request

2019-03-01 15:10 UTC, ihor-sviziev requested changes
Please review my comments above

2019-03-01 15:10 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php
> +    public function getUserDefaultName()
```suggestion
    public function getUseDefaultName()
```

2019-03-01 15:10 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php
> +    private $useDefaultName = 'product[use_default_media_gallery]';
As we discussed - please move it to template, it's not needed there.

2019-03-01 15:10 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php
> +    public function getUseDefaultHtmlId()
As we discussed - please move it to template file, it's not really needed there

2019-03-01 15:10 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php
> +                if ($image['store_id'] != $this->_getDefaultStoreId()) {
```suggestion
                if ($image['store_id'] !== $this->_getDefaultStoreId()) {
```

2019-03-01 15:10 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/ResourceModel/Product/Gallery.php
> +    public function deleteGallery($valueId, $storeId = null)
It's incorrect. Method named "deleteGallery" should not delete "gallery_values". Please see `deleteGalleryValueInStore` or create new one similar to it.

2019-03-15 16:45 UTC, sidolov commented
@Nika-Valkyria , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-15 16:45 UTC, closed without merging

2020-01-07 13:34 UTC, amenk commented
@Nika-Valkyria are you still interested to work on this PR?

2020-01-07 13:36 UTC, amenk commented on app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery-use-default.js
> +/*
I believe this should be implemented via Knockout to not mix Jquery and Knockout (but I am not sure)

2020-01-07 17:16 UTC, ihor-sviziev commented
@amenk 10 months passed, I believe anyone else could continue.
 Are you interested in creating PR with finalized work?

2020-01-07 18:10 UTC, amenk commented
@ihor-sviziev Any way to say, what still is needed to finish it so we can roughly estimate the effort? Could we post this in bountysource?

2020-03-27 10:10 UTC, ihor-sviziev commented
Hi @amenk ,

I would say that this issue is really hard and it's really hard to estimate it.

We tried to fix it just for our client, but gave up as too many new issues appears there. We decided to change for all media attributes scope to "Global" and this change completely fixed all issues we had.

Sorry can't say if you could post it to bountysource, you can discuss it with people from EngCom team.

2020-03-27 10:30 UTC, amenk commented
Thanks for your feedback.
How did you change all media attributes to global? Can you post that? That would be totally working for us as well.

2020-03-30 10:03 UTC, ihor-sviziev commented
@amenk 
Here is workaround that we used. You need to do it for all "Media Image" attributes (image, small_image, thumbnail, swatch_image, etc.):

**WARNING: This change will delete all attribute values on store view levels, and will keep only global values.**

1. Go to Admin >> Stores >> Attributes >> Product
2. Find your product attibute 
3. Open "Advanced Attribute Properties" 
4. Change "Scope" to "Global"
5. Click "Save Attribute"

2020-09-04 04:32 UTC, grichards commented
Hello @ihor-sviziev .

This workaround does not seem to work as I expect. I modified all "image" attributes to "Global" and then:

1. In All Store Views I add 3 images. One is "small" and "thumbnail". One is "base". One is "featured". I hide the "featured" and "small" / "thumbnail" from product page. I save.
2. I look in the database and see that catalog_product_entity_media_gallery_value has 3 records for the image linked to store_id = 0. So far so good.
3. I switch scope to a different store, and override an attribute not related to images. I save.
4. I look in the database and see that catalog_product_entity_media_gallery_value has 3 NEW records for the image linked to store_id = 1. Now isn't this a problem? If the attributes were Global scope, shouldn't I expect no store specific records to be created?
5. I then switch back to All Store View scope... and I uncheck the "hidden" state from one of the images and save.
6. I check the database... ONLY the store_id=0 record has been modified. Shouldn't I at least have expected all store_ids to be kept in sync if the attribute scope is global?

2020-09-04 06:22 UTC, ihor-sviziev commented
Hi @grichards,
Which Magento version are you using? We hadn't any issues with Magento 2.3.4-p2.

2020-09-04 17:03 UTC, grichards commented
Hello @ihor-sviziev .

This site is 2.3.4.

In your workaround... is that referring to ONLY the images themselves being global in scope... or do you think your workaround is extending to the roles and hidden status of the images as well? My testing indicates the roles and hidden status still get set per store view if you override any attribute in a store view.

Have you looked at catalog_product_entity_media_gallery_value?

SELECT * FROM `catalog_product_entity_media_gallery_value` ORDER BY `store_id` DESC LIMIT 50

Do you see entries for stores other than ID = 0?

G

2020-09-04 17:23 UTC, ihor-sviziev commented
I think you’re right, we found that also image sorting is overrides on the
store view level as well

On Fri, 4 Sep 2020 at 20:03 grichards <notifications@github.com> wrote:

>
>
> Hello @ihor-sviziev <https://github.com/ihor-sviziev> .
>
>
> This site is 2.3.4.
>
>
> In your workaround... is that referring to ONLY the images themselves
> being global in scope... or do you think your workaround is extending to
> the roles and hidden status of the images as well? My testing indicates the
> roles and hidden status still get set per store view if you override any
> attribute in a store view.
>
>
> Have you looked at catalog_product_entity_media_gallery_value?
>
>
> SELECT * FROM catalog_product_entity_media_gallery_value ORDER BY store_id
> DESC LIMIT 50
>
>
> Do you see entries for stores other than ID = 0?
>
>
> G
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/21041#issuecomment-687271908>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOJOUKS3G5ECDEKP6IDIS3SEEMXHANCNFSM4GU4RG5Q>
> .
>
>
>