Backend Product Attribute Date Design is not proper.
magento/magento2 pull request #21067
Opened 2019-02-08 11:35 UTC by speedy008

### Description (*)

Magento 2.3 Develop

### Manual testing scenarios (*)

1. Login to backend > Store > Attribute > Product
2. Under the properties > Attribute Properties > Catalog Input Type for Store Owner (Select Date)
3.Under Advanced Attribute Properties > Default Value Check Date input design.

### Expected Result (*)
![expactedss](https://user-images.githubusercontent.com/33230237/52476120-b4982e00-2bc3-11e9-9b7c-5b33df7ac5f9.png)

### Actual Result Result (*)
![actual-ss](https://user-images.githubusercontent.com/33230237/52476113-acd88980-2bc3-11e9-80aa-9cd284533678.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-08 11:35 UTC, magento-engcom-team commented
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-10 19:22 UTC, dmytro-ch commented
@magento-engcom-team give me test instance

2019-02-10 19:22 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-02-10 19:23 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21067.instances.magento-community.engineering).
Admin access: [https://pr-21067.instances.magento-community.engineering/admin](https://pr-21067.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-10 20:08 UTC, dmytro-ch approved these changes

2019-02-10 20:09 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4195](https://jira.corp.magento.com/browse/ENGCOM-4195) has been created to process this Pull Request

2019-02-12 16:18 UTC, sivaschenko commented
Hi @speedy008 , thanks for the pull request. Actual result looks just fine. What is the issue?

2019-02-12 16:25 UTC, speedy008 commented
@sivaschenko  In backend through out all date input design should be consistence and here calendar button is out side input box.

2019-03-06 12:08 UTC, sivaschenko requested changes
Hi @speedy008 thanks for the pull request! Please see my code review comment.

2019-03-06 12:08 UTC, sivaschenko commented on app/design/adminhtml/Magento/backend/web/css/styles-old.less
> -    .control {
I have a concern regarding backward compatibility aspects of removing these styles. Extensions may relay on these styles. I'd try to find a fix without removing this less block

2019-03-20 15:44 UTC, sidolov commented
@speedy008 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-20 15:44 UTC, closed without merging