Added space above color swatches on product page.
magento/magento2 pull request #21060
Opened 2019-02-08 09:04 UTC by suryakant-krish

### Description (*)

1. This is direct PR because it is small change.
2. Version magento 2.3
### Fixed Issues (if relevant)

1. Added space above color swatches on product page.

### Manual testing scenarios (*)

1. Go to frontend any product detail page look into color swatches. see attched screenshot.
2. Actual Result.
![actual-result](https://user-images.githubusercontent.com/43638601/52468349-793f3480-2bae-11e9-8af8-e68108d29b4c.jpg)
3. Expected Result.
![expected-result](https://user-images.githubusercontent.com/43638601/52468369-8bb96e00-2bae-11e9-88ae-49179328dff4.jpg)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-08 09:04 UTC, magento-engcom-team commented
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-08 17:22 UTC, sidolov requested changes

2019-02-08 17:22 UTC, sidolov commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +				margin-bttom: @indent__s;
Please, fix indentation

2019-02-11 04:41 UTC, suryakant-krish commented
@sidolov,

I have updated indent please verify it.

2019-03-08 15:50 UTC, sidolov requested changes

2019-03-08 15:50 UTC, sidolov commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +		margin-bttom: @indent__s;
It will not work, `margin-bttom` is not a correct css statement

2019-04-10 15:20 UTC, sidolov commented
@suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-10 15:20 UTC, closed without merging