Added space above error message.
magento/magento2 pull request #21074
Opened 2019-02-08 12:48 UTC by suryakant-krish

### Description (*)

1. This is direct PR because it  is small change.
2. Area Frontend. when user group product add to cart without add quantity error message show. 

### Fixed Issues (if relevant)

1. This is direct PR.
2. Go to frontend > Find any group product **Ex** "Set of Sprite Yoga Straps".  > on product page click on add to cart button error message show.
3. Reproduce on Magento 2.3

### Manual testing scenarios (*)

1. Actual Result.
![actual-result](https://user-images.githubusercontent.com/43638601/52479176-c252b100-2bcd-11e9-8fbd-f6e2d1787c28.jpg)

2. Expected Result.
![expected-result](https://user-images.githubusercontent.com/43638601/52479192-d1396380-2bcd-11e9-88c9-47d251d86132.jpg)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-08 12:48 UTC, magento-engcom-team commented
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-08 14:06 UTC, dmytro-ch approved these changes

2019-02-08 14:07 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4181](https://jira.corp.magento.com/browse/ENGCOM-4181) has been created to process this Pull Request

2019-02-08 18:59 UTC, Karlasa commented
@magento-engcom-team give me test instance

2019-02-08 18:59 UTC, magento-engcom-team commented
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

2019-02-08 18:59 UTC, magento-engcom-team commented
Hi @Karlasa, here is your [new Magento instance](https://pr-21074.instances.magento-community.engineering).
Admin access: [https://pr-21074.instances.magento-community.engineering/admin](https://pr-21074.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-08 19:16 UTC, Karlasa requested changes
@suryakant-krish @dmytro-ch 
This fix looks bit too general and will affect a lot of other places that has this class. 
maybe add margin into #validation-message-box and under grouped product module?

2019-02-08 20:18 UTC, dmytro-ch commented
@Karlasa, thank you for the update.

I was also thinking about that but decided that having kind of base `10px` space above this block allows us to make sure there are no additional issues with other blocks inserted before the `product.info.addtocart` block.
Also, there are other rules overriding this value for other product types, e.g. `20px` for configurable products etc.

But yes, I agree that it makes sense to make the changes for grouped products only for this particular case in order to avoid some unexpected behaviour. 

Thnak you!

2019-02-14 11:42 UTC, suryakant-krish commented
@dmytro-ch and @Karlasa

I have updated code only for group product used page layout handle hierarchy.

Please review this and let me know.

2019-02-15 11:45 UTC, sivaschenko commented
@magento-engcom-team give me test instance

2019-02-15 11:46 UTC, magento-engcom-team commented
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

2019-02-15 11:46 UTC, magento-engcom-team commented
Hi @sivaschenko, here is your [new Magento instance](https://pr-21074.instances.magento-community.engineering).
Admin access: [https://pr-21074.instances.magento-community.engineering/admin](https://pr-21074.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-18 20:56 UTC, Karlasa requested changes

2019-02-18 20:56 UTC, Karlasa commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +    .page-product-grouped {
Grouped product specific code should be placed under right module Magento__GroupedProduct in this case.

2019-03-04 07:18 UTC, suryakant-krish commented
@Karlasa,

I have moved code under "Magento__GroupedProduct".

2019-03-04 07:41 UTC, Karlasa commented on app/design/frontend/Magento/luma/Magento_GroupedProduct/web/css/source/_module.less
> +        .box-tocart {
add extra new line above it to fit with coding standards :)

2019-03-04 07:41 UTC, Karlasa commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +
remove these 2 added lines :)

2019-03-04 07:43 UTC, Karlasa commented
@suryakant-krish 
Thanks, just a bit more code clean up and I'm happy 👍

2019-03-04 08:41 UTC, suryakant-krish commented
@Karlasa,

I have updated code as you have mentioned.

2019-03-04 09:01 UTC, Karlasa approved these changes

2019-03-04 09:04 UTC, magento-engcom-team commented
Hi @Karlasa, thank you for the review.
[ENGCOM-4181](https://jira.corp.magento.com/browse/ENGCOM-4181) has been created to process this Pull Request

2019-03-07 09:02 UTC, VasylShvorak commented
✔️ QA passed

2019-03-14 19:47 UTC, merged