Magento/Magento2#5730: Changing sort order in admin doesn't work for …
magento/magento2 pull request #21119
Opened 2019-02-11 04:16 UTC by yuchenacidgreen

…catalog search

- Fix search results default sorting config, remove hard coded sort by 'relevance'

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-11 04:16 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=21119) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21119) before we can accept your contribution.<br/>

2019-02-11 04:16 UTC, magento-engcom-team commented
Hi @yuchenacidgreen. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-11 04:34 UTC, magento-engcom-team commented
@yuchenacidgreen thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-02-11 17:15 UTC, dmytro-ch commented
@magento-engcom-team give me test instance

2019-02-11 17:15 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-02-11 17:16 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21119.instances.magento-community.engineering).
Admin access: [https://pr-21119.instances.magento-community.engineering/admin](https://pr-21119.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-28 11:31 UTC, sivaschenko requested changes
Hi @yuchenacidgreen thanks for the pull request.

I don't think that 
`Stores->Configuration->Catalog->Catalog->Storefront->Product Listing Sort by` setting was designed to set the sort order for search results. Also, there is no way to provide sorting by relevance once the hardcoded sorting is removed.

What do you think about implementing a configuration entry specifically for search results sorting that will include relevance as an option?

2019-03-14 17:15 UTC, sidolov commented
@yuchenacidgreen , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-14 17:15 UTC, closed without merging