Fix magento root package identification for metapackage installation
magento/magento2 pull request #21137
Opened 2019-02-11 14:43 UTC by oleksii-lisovyi

### Description (*)

Fix issue with failing Magento installing process (`php bin/magento setup:install`) for installation via metapackage, because of issue in root package defining.

### Fixed Issues (if relevant)

1. magento/magento2#21136: Magento installation via metapackage: checkExtensions fails, because isMagentoRoot works incorrectly for installation

### Manual testing scenarios (*)

Steps to reproduce could be takes from issue.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-11 14:44 UTC, magento-engcom-team commented
Hi @oleksii-lisovyi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-11 14:51 UTC, ihor-sviziev approved these changes

2019-02-11 14:52 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4211](https://jira.corp.magento.com/browse/ENGCOM-4211) has been created to process this Pull Request

2019-02-12 07:38 UTC, ihor-sviziev commented
Hi @oleksii-lisovyi,
Could you create PR with the same changes to 2.3-develop branch?

2019-02-19 16:05 UTC, ihor-sviziev requested changes
Please squash all changes into single commit and force push your chagnes

2019-02-19 16:05 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testSkeleton/composer.lock
> +    "platform": {
Please revert this changes, It looks incorrect

2019-02-20 09:48 UTC, ihor-sviziev commented
I checked integration tests failures, looks like we have some legacy test there. I'll discuss what to do with it with @buskamuza. For now no action items needed.

2019-03-04 07:04 UTC, ihor-sviziev approved these changes

2019-03-04 07:05 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4211](https://jira.corp.magento.com/browse/ENGCOM-4211) has been created to process this Pull Request

2019-03-27 14:09 UTC, stoleksiy commented
:heavy_check_mark: QA Passed 

**Before:**

![before](https://user-images.githubusercontent.com/44244273/55082607-abe3b480-50aa-11e9-99c8-263ce37b369f.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/55082627-b30ac280-50aa-11e9-8609-4986156e7bec.png)

2019-03-28 13:42 UTC, nmalevanec commented
@oleksii-lisovyi, please check failed integration test Magento\Framework\Composer\ComposerInformationTest::testGetRequiredExtensions with data set "Skeleton Composer" ('testSkeleton')
Failed asserting that an array contains 'intl'.

2019-03-28 15:10 UTC, ihor-sviziev commented
Hi @nmalevanec,
It looks like these tests are too old and incorrect.
I wasn’t able to find you in slack. Could you write me a message and let’s discuss what to do with it?

2019-04-02 11:13 UTC, sivaschenko commented
@oleksii-lisovyi @ihor-sviziev is there a related pull request to 2.3-develop?

2019-04-02 13:10 UTC, oleksii-lisovyi commented
@sivaschenko, here it's: https://github.com/magento/magento2/pull/22116

2019-06-24 10:45 UTC, ihor-sviziev requested changes
Hi @oleksii-lisovyi,

Right now backport looks really different than original PR.
Could you update this PR with changes that were done there?

Thank you!

2019-07-08 18:24 UTC, sidolov commented
@oleksii-lisovyi , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-07-08 18:24 UTC, closed without merging