Disable cron:run when maintenance mode is enabled
magento/magento2 pull request #21181
Opened 2019-02-13 09:33 UTC by kassner

### Description

I believe cron jobs should be disabled while `setup:upgrade` is being run, to avoid concurrent accesses, which can lead to table locks that can make setup upgrade fail, plus we'll be using stale/wrong data for the cron jobs.

Since the maintenance mode makes sure the frontend is inaccessible, avoiding any writes to the database through it, I believe we should disable crons as well, as they have a heavy impact on the database.

### Manual testing scenarios

1. Run `php bin/magento maintenance:enable`;
2. Run `php bin/magento cron:run`;
3. Cron jobs should not run;

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-13 09:33 UTC, magento-engcom-team commented
Hi @kassner. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-13 11:17 UTC, miguelbalparda commented
> Since the maintenance mode makes sure the frontend is inaccessible, **avoiding any writes to the database through it**, I believe we should disable crons as well, as they have a heavy impact on the database.
This is true only for some cases, I'm not sure if this should be included in the core. Maybe create a config instead of assuming this applies to everybody?

2019-02-13 11:21 UTC, ihor-sviziev commented
Hi @miguelbalparda,
Is there any use case when cron jobs should be running during enabled maintenance mode?

2019-02-13 11:24 UTC, miguelbalparda commented
It depends on how people is using maintenance mode. I've seen admins putting the site in that mode just to do changes on prices or CMS pages or even deploying new code changes while on maintenance, which sometimes require crons to be run.

2019-02-13 13:15 UTC, ihor-sviziev commented
So in this case would be better to add some parameter to env.php file, for
instance “disable_cron_running_in_maintenance_mode”. If this parameter
exists and it is set to 1 - than cron jobs should not be running.

What do you think?

On Wed, Feb 13, 2019 at 13:24 Miguel Balparda <notifications@github.com>
wrote:

> It depends on how people is using maintenance mode. I've seen admins
> putting the site in that mode just to do changes on prices or CMS pages or
> even deploying new code changes while on maintenance, which sometimes
> require crons to be run.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/21181#issuecomment-463163060>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AByXUTH7JT77JCGWS4yeJrx-sTsel0sqks5vM_X-gaJpZM4a4-da>
> .
>

2019-02-13 14:08 UTC, miguelbalparda commented
I think that’s no different than disabling Magento_Cron using the bin/magento tool and should have the same effect without adding anything to the core for an use case that’s not super intuitive.

2019-02-13 14:10 UTC, kassner commented
Disabling Magento_Cron with `module:disable` is not the same, as it will prevent future db upgrades while running `setup:upgrade`.

2019-02-13 14:14 UTC, miguelbalparda commented
Which is consistent with the description of this PR regarding no DB writes while in maintenance, achieving virtually the same objective.

2019-02-13 14:19 UTC, ihor-sviziev commented
With disabling cron module we’ll have few issues:
1. We’ll have errors that command cron:run doesn’t exists, these messages
will be sent to email. As for me - it’s not expected
2. Any amount of modules might have dependence on cron module, so we have
to disable all together, it means - not really useful


On Wed, Feb 13, 2019 at 16:15 Miguel Balparda <notifications@github.com>
wrote:

> Which is consistent with the description of this PR regarding no DB writes
> while in maintenance, achieving virtually the same objective.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/21181#issuecomment-463213979>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AByXUe02G8XiaUuiFkTsXc2KzW0V72lBks5vNB3wgaJpZM4a4-da>
> .
>

2019-02-13 14:21 UTC, kassner commented
@miguelbalparda no, as I am enabling maintenance mode just because I want to run `setup:upgrade` without anything else concurrently. I still want to run `Magento_Cron`'s UpgradeData/UpgradeSchema.

2019-02-13 17:11 UTC, miguelbalparda commented
Maintenance windows are very short usually, which means --force can be used to disable Magento_Cron just for the duration of the window without causing much issues. I still don't see why an edge case like this should be considered in the core, the reasoning behind an inclusion should be a broader benefit and I don't see that in this issue. In either case, this should be consulted with an architect IMO.

2019-02-13 18:27 UTC, sivaschenko commented
I think it is a good idea to disable cron by default during maintenance mode as it appears to be the safes approach. I'd add a command option to `maintenance:enable` to keep cron jobs running for those who are confident that cron jobs are not going to be affected during maintenance operations.

2019-02-13 20:15 UTC, ihor-sviziev commented
Hi @kandy @buskamuza,
What do you think about such proposal?

2019-02-13 22:53 UTC, NadiyaS commented on app/code/Magento/Cron/Console/Command/CronCommand.php
>          if (!$this->deploymentConfig->get('cron/enabled', 1)) {
Please pay attention to this configuration. You already may disable cron. Add cron/enabled as 0 to configuration file. There is no special CLI command for this setting for now.

2019-02-13 22:56 UTC, NadiyaS commented
Hi,
First, there may be some possible cases when user enable maintenance mode and want to have cron running. 
Also, there may be cases when you want just to disable cron without maintenance mode.
We already have this possibility. I added comment to the review.
You may add *cron/enabled* as 0 to configuration file (e.g. app/etc/env.php) and cron won't be run.
We did not implement CLI command for this yet.

2019-02-14 08:19 UTC, ihor-sviziev commented
@NadiyaS good catch!
In this case I think would be better to add clip commands `cron:enable` and `cron:disable`. @kassner what do you think?

2019-03-14 13:17 UTC, ihor-sviziev requested changes
Hi,

As we discussed with Architects in `#appdesign` - it's better to introduce `cron:enable` and `cron:disable` CLI commands, that will fit all needs and will not add backward incompatible changes.

@kassner  could you update your PR with these chagnes?

2019-03-28 14:37 UTC, sidolov commented
@kassner , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-28 14:37 UTC, closed without merging