fixed-Discount-Code-improvement-21214
magento/magento2 pull request #21215
Opened 2019-02-14 06:11 UTC by abrarpathan19

### Description (*)

Luma theme Apply Discount Code section design improvement according to shopping cart page Discount Coupon box section. please review link : Shopping Cart page : http://prntscr.com/mkvc7o

### Fixed Issues (if relevant)

1. magento/magento2#21214: Luma theme Apply Discount Code section design improvement

### Manual testing scenarios (*)

Checkout page step "Review & Payments" : http://prntscr.com/mkvcoa
It should be according to the shopping cart page coupon box section.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-14 06:11 UTC, magento-engcom-team commented
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-18 13:18 UTC, sivaschenko requested changes
Hi @abrarpathan19 thanks for the pull request, please take a look at the review notes

2019-02-18 13:18 UTC, sivaschenko commented on app/design/frontend/Magento/luma/web/css/source/_extends.less
> +    .abs-discount-code {
@abrarpathan19 can you please move the fix to Magento_Checkout module of luma theme

2019-03-04 15:12 UTC, sidolov commented
@abrarpathan19 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-05 05:16 UTC, abrarpathan19 commented
@sidolov Thank you :+1:

2019-05-06 10:34 UTC, sivaschenko approved these changes

2019-05-06 10:35 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5070](https://jira.corp.magento.com/browse/ENGCOM-5070) has been created to process this Pull Request

2019-05-06 10:44 UTC, abrarpathan19 commented
@sivaschenko Thanks to approving PR

2019-05-08 08:12 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-24 10:55 UTC, merged