[Backport] Backend: Fixed checkbox alignment
magento/magento2 pull request #21221
Opened 2019-02-14 08:55 UTC by speedy008

### Original Pull Request 
 https://github.com/magento/magento2/pull/19631

### Description (*)

Checkbox alignment issue backend. 
### Fixed Issues (if relevant)

1. magento/magento2#19630: Checkbox alignment issue backend. 

### Manual testing scenarios (*)

1. Login into admin panel > System > Export > checkbox alignment issue "Fields Enclosure".

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-14 08:55 UTC, magento-engcom-team commented
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-14 14:00 UTC, rodrigowebjump reviewed
Hi @speedy008 

Why did you not use the same variable as in the original PR?
What is the reason you modify the test?

2019-02-15 04:36 UTC, speedy008 commented
@rodrigowebjump I have created Back-port PR using porting tool. I will check with Original PR nd update it soon.

2019-02-19 19:43 UTC, rogyar requested changes

2019-02-19 19:43 UTC, rogyar commented on dev/tests/functional/tests/app/Magento/Catalog/Test/Block/Adminhtml/Product/Edit/Section/Options.php
> +    protected function _fill(array $fields, SimpleElement $element = null)
Could you provide more information about this change, please? I'm not sure it should be included as a part of the backport. Correct me if I'm wrong. Thank you

2019-02-20 08:54 UTC, rogyar commented
Thank you for your collaboration. Starting from Feb 19 minor style fixes are considered as "Cleanup" and no longer accepted for 2.2-develop branch.

2019-02-20 08:54 UTC, closed without merging

2019-04-06 22:22 UTC, Ctucker9233 commented
@rogyar Please explain this logic. Is 2.2 at EOL?