Fixed Search term minimum length change MINIMAL_CHARACTER_LENGTH value
magento/magento2 pull request #21350
Opened 2019-02-20 09:04 UTC by ravi-chandra3197

### Description (*)

Fixed Search term minimum length change MINIMAL_CHARACTER_LENGTH value
currently we can search product using the first 1 or 2 character because MINIMAL_CHARACTER_LENGTH is set with value 3
### Fixed Issues (if relevant)

1. magento/magento2#12053: Search term minimum length is static

### Manual testing scenarios (*)

1. N/A
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-20 09:04 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-20 11:28 UTC, miguelbalparda commented
This does not solve the mentioned issue, it's just changing the static value from 3 to 1. I don't see why this should be changed, reason is explained in #12053. Feel free to reopen if you have anything to add or more changes to fix the mentioned issue

2019-02-20 12:23 UTC, ravi-chandra3197 commented
Hello @miguelbalparda
I have update code can you review it.

2019-02-28 12:09 UTC, miguelbalparda approved these changes

2019-02-28 12:10 UTC, magento-engcom-team commented
Hi @miguelbalparda, thank you for the review.
[ENGCOM-4398](https://jira.corp.magento.com/browse/ENGCOM-4398) has been created to process this Pull Request

2019-03-04 10:52 UTC, sivaschenko reviewed
Hi @ravi-chandra3197 thanks for the pull request! Please see my comments review comments

2019-03-04 10:52 UTC, sivaschenko commented on lib/internal/Magento/Framework/Search/Adapter/Mysql/Query/Builder/Match.php
> +        $this->minQueryLength = (int)$this->_ConfigInterface->getValue(
Hi @ravi-chandra3197 I wouldn't reference catalog search configuration path in the framework, can you refactor the fix to move the config reference out of the framework?

2019-03-04 10:53 UTC, sivaschenko requested changes
Hi @ravi-chandra3197 thanks for the pull request! Please see my comments review comments

2019-03-18 15:41 UTC, sidolov commented
@ravi-chandra3197 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-03-18 15:41 UTC, closed without merging