Allow change of AbstractPdf top border
magento/magento2 pull request #21411
Opened 2019-02-22 17:31 UTC by abbatis

When overriding `\Magento\Sales\Model\Order\Pdf\Invoice::newPage()` to your custom module - changing `$this->y = 800` in the method to for example `$this->y=1000` in order to set the header to a higher y-position, the change is later overwritten by `\Magento\Sales\Model\Order\Pdf\AbstractPdf::insertLogo()`

### Description
`\Magento\Sales\Model\Order\Pdf\AbstractPdf::insertLogo()` should say `$top = $this->y` instead of overriding `$this->y` static number `830`.

### Steps to reproduce
1. Override `\Magento\Sales\Model\Order\Pdf\Invoice::newPage()` to your custom module.
2. Change `$this->y = 800` to for example `$this->y = 1000`.
3. Nothing happens, the header stays the same.

See https://github.com/magento/magento2/pull/14000

2019-02-22 17:32 UTC, magento-engcom-team commented
Hi @abbatis. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-25 07:37 UTC, aleron75 approved these changes

2019-02-25 07:38 UTC, magento-engcom-team commented
Hi @aleron75, thank you for the review.
[ENGCOM-4363](https://jira.corp.magento.com/browse/ENGCOM-4363) has been created to process this Pull Request

2019-03-27 14:55 UTC, sivaschenko requested changes
Hi @abbatis thanks for the pull request!

The pull request contains backward incompatible changes (public constant and protected property) that cannot be accepted to a patch release. 

Unfortunately, I cannot currently advise any alternative acceptable solution to enable child classes changing the top border. Looks like that customization will require a change to `insertLogo` method in a child class.

cc @aleron75

2019-03-27 15:52 UTC, abbatis commented
Hi @sivaschenko thanks for your review. 

I don't see why this PR would be backwards incompatible. Could you explain so I can think about a proper solution? Or maybe you have a proper solution in mind that I can implement?

2019-03-28 14:32 UTC, sivaschenko commented
@abbatis the change will result in the fatal error on environments where the class is extendend and child class has a property with the same name but private access level, for example.

More information on backward compatible development: https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#php

More examples: https://www.slideshare.net/SergeyIvaschenko/backward-compatible-development-in-examples

Unfortunately, I don't have a proper solution in mind currently (apart from alternative class implementation)

2019-03-28 16:42 UTC, abbatis commented
@sivaschenko Got it, thanks. Just wondering, would it make any difference if we would replace the `$topBorder` property by a `getTopBorderMargin()` method, something like that?

2019-03-28 16:49 UTC, sivaschenko commented
@abbatis unfortunately, the same case applies to methods and constants

2019-03-28 16:56 UTC, abbatis commented
@sivaschenko So, I could create another class which holds the constant and property, or XML definition maybe? What would be a proper solution?

2019-03-28 17:05 UTC, sivaschenko commented
@abbatis depends on what you would like to resolve. It appears there is no way to resolve the initial case described in the pull request and the client code will need to override `insertLogo` method.

However, you are free to provide new better PDF classes implementation that could be used instead of existing and mark existing as deprecated

2019-03-28 18:12 UTC, abbatis commented
@sivaschenko Ok, will do. Thanks.

2019-05-28 11:10 UTC, VladimirZaets commented
@abbatis Any updates?

2019-06-11 13:01 UTC, abbatis commented
@VladimirZaets Not yet, need some more time. Thank you.

2019-08-13 19:40 UTC, sidolov commented
@abbatis , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-13 19:40 UTC, closed without merging