Backport-issue-195196
magento/magento2 pull request #21437
Opened 2019-02-25 12:03 UTC by Nazar65

### Original PR #19988
 
### Description (*)
Could not load image for customer attribute, error: Base64 is not defined "

### Fixed Issues (if relevant)
1. magento/magento2#19983: Could not load image for customer attribute,

### Manual testing scenarios (*)
1-Create customer attribute type file -> 
```
$eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
        $eavSetup->addAttribute(
            \Magento\Customer\Model\Customer::ENTITY,
            'sample_attribute2',
            [
                'type'         => 'text',
                'label'        => 'Sample Attribute',
                'input'        => 'file',
                'required'     => false,
                'visible'      => true,
                'user_defined' => false,
                'position'     => 999,
                'system'       => 0,
            ]
        );
        $sampleAttribute = $this->eavConfig->getAttribute(Customer::ENTITY, 'sample_attribute');

        // more used_in_forms ['adminhtml_checkout','adminhtml_customer','adminhtml_customer_address','customer_account_edit','customer_address_edit','customer_register_address']
        $sampleAttribute->setData(
            'used_in_forms',
            ['adminhtml_customer','customer_register_address','customer_address_edit','customer_account_edit']

        );
        $sampleAttribute->save();
```
**2. try to upload image on adminhtml customer edit.**

### Expected Result 
No errors in Console, Image uploaded 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-25 12:03 UTC, magento-engcom-team commented
Hi @Nazar65. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-25 12:15 UTC, orlangur approved these changes

2019-02-25 12:19 UTC, orlangur approved these changes

2019-02-25 12:36 UTC, sivaschenko approved these changes

2019-02-25 12:40 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-4366](https://jira.corp.magento.com/browse/ENGCOM-4366) has been created to process this Pull Request

2019-02-27 14:56 UTC, sivaschenko requested changes
Hi @Nazar65 thanks for the backport, during testing, we discovered there is a JS error when creating a new customer in the admin panel on the PR code base, can you please check that.

![image](https://user-images.githubusercontent.com/2028541/53499267-e6eccb00-3a9f-11e9-8ebc-940980415f17.png)

2019-02-27 14:56 UTC, sivaschenko commented on lib/web/mage/adminhtml/tools.js
> -Event.observe(window, 'load', function () {
Can you please move this code change to a separate PR as this is not part of a backport

2019-02-27 15:02 UTC, sivaschenko commented
@magento-engcom-team give me test instance

2019-02-27 15:02 UTC, magento-engcom-team commented
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

2019-02-27 15:02 UTC, magento-engcom-team commented
Hi @sivaschenko, here is your [new Magento instance](https://pr-21437.instances.magento-community.engineering).
Admin access: [https://pr-21437.instances.magento-community.engineering/admin](https://pr-21437.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-02-27 15:11 UTC, sivaschenko commented
@Nazar65 sorry, I don't think your last commit was included during testing, we'll recheck including the last commit

2019-03-01 13:17 UTC, merged