[Sales] Covering the guest order view by integration tests
magento/magento2 pull request #21474
Opened 2019-02-27 14:12 UTC by eduard13

### Description (*)
This PR covers the `Orders and Returns` form, which should be available only for guests and correct data.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-27 14:12 UTC, magento-engcom-team commented
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-28 07:55 UTC, rogyar requested changes

2019-02-28 07:55 UTC, rogyar commented on dev/tests/integration/testsuite/Magento/Sales/Controller/Guest/FormTest.php
> +namespace Magento\Sales\Controller;
Please, correct the namespace. Should be `Magento\Sales\Controller\Guest`

2019-02-28 08:04 UTC, eduard13 commented
@rogyar the mentioned point was adjusted and PR was merged.
Thank you.

2019-02-28 09:08 UTC, rogyar approved these changes

2019-02-28 09:09 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-4394](https://jira.corp.magento.com/browse/ENGCOM-4394) has been created to process this Pull Request

2019-03-04 14:49 UTC, merged