Fix allowing SQL injections in addExpressionFieldToSelect
magento/magento2 pull request #21482
Opened 2019-02-27 16:22 UTC by aario

### Description (*)
The str_replace function used in `addExpressionFieldToSelect` directly adds the string in `$fieldItem` to the query. Here `$expression` must be checked by the developer to not have any dangerous content. But as developers expect magento core functions to prevent sql injection, they are prone to put input parameters directly inside `$fields` which can lead to sql injections. Other function `addFieldToSelect` in the same class ends up with quoted text. But this is not the case with this function.

### Fixed Issues (if relevant)
A similar issue happened in an opensource magento extension MageFan Module-Blog where developers apparently expected passing a search term as `$fieldItem` into this function to be safe which lead to SQL Injection:
https://github.com/magefan/module-blog/issues/228
Although a pull request was proposed there to quote the input parameter within extension code, it is safer for the upstream code of magento to prevent such cases.

### Manual testing scenarios (*)
Trigger an action which leads to call of:
```
Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;:addExpressionFieldToSelect
```
With a `"` as `$fieldItem`. The result is a crash report:
```
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"""), 4)) AS `search_rate` FROM `magefan_blog_post` AS `main_table`
 INNER JOIN ' at line 1, query was: SELECT `main_table`.*, (0               + FORMAT(MATCH (title, meta_keywords, meta_description, identifier, content) AGAINST ("""), 4)) AS `search_rate` FROM `magefan_blog_post` AS `main_table`
 INNER JOIN `magefan_blog_post_store` AS `store_table` ON main_table.post_id = store_table.post_id WHERE (`is_active` = '1') AND (`publish_time` <= '2019-02-27 14:54:43') AND ((`title` LIKE '%\"%') OR (`short_content` LIKE '%\"%') OR (`content` LIKE '%\"%')) AND (store_table.store_id IN('1', 0)) GROUP BY `main_table`.`post_id` ORDER BY search_rate DESC, publish_time DESC
 LIMIT 10
Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"""), 4)) AS `search_rate` FROM `magefan_blog_post` AS `main_table`
 INNER JOIN ' at line 1

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"""), 4)) AS `search_rate` FROM `magefan_blog_post` AS `main_table`
 INNER JOIN ' at line 1, query was: SELECT `main_table`.*, (0               + FORMAT(MATCH (title, meta_keywords, meta_description, identifier, content) AGAINST ("""), 4)) AS `search_rate` FROM `magefan_blog_post` AS `main_table`
 INNER JOIN `magefan_blog_post_store` AS `store_table` ON main_table.post_id = store_table.post_id WHERE (`is_active` = '1') AND (`publish_time` <= '2019-02-27 14:54:43') AND ((`title` LIKE '%\"%') OR (`short_content` LIKE '%\"%') OR (`content` LIKE '%\"%')) AND (store_table.store_id IN('1', 0)) GROUP BY `main_table`.`post_id` ORDER BY search_rate DESC, publish_time DESC
 LIMIT 10
#0 /var/www/html/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(541): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(615): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#6 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /var/www/html/lib/internal/Magento/Framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(778): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(674): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#10 /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(577): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(562): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#12 /var/www/html/lib/internal/Magento/Framework/Data/Collection.php(843): Magento\Framework\Data\Collection\AbstractDb->load()
```
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-27 16:22 UTC, magento-engcom-team commented
Hi @aario. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-27 16:22 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=21482) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21482) before we can accept your contribution.<br/>

2019-02-27 20:00 UTC, okorshenko commented
@magento-engcom-team give me test instance

2019-02-27 20:00 UTC, magento-engcom-team commented
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

2019-02-27 20:00 UTC, magento-engcom-team commented
Hi @okorshenko, here is your [new Magento instance](https://pr-21482.instances.magento-community.engineering).
Admin access: [https://pr-21482.instances.magento-community.engineering/admin](https://pr-21482.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-03-01 06:19 UTC, ihor-sviziev commented
Hi @aario,
Take a look on unit & integration tests failures on Travis. Could you fix them
Also it looks that this patch is really important, so would be great to cover it with some tests

2019-03-04 12:23 UTC, ihor-sviziev requested changes
Please see my prev. comment

2019-03-06 11:32 UTC, aario commented
> Hi @aario,
> Take a look on unit & integration tests failures on Travis. Could you fix them
> Also it looks that this patch is really important, so would be great to cover it with some tests

Will do ASAP.

2019-03-11 12:08 UTC, abbatis commented
https://magento.com/security/news/critical-vulnerability-magestore-store-locator-extension

The fix for this vulnerability depends on this issue as well, right?

2019-03-12 09:02 UTC, ihor-sviziev commented
Hi @aario,
Looks like this change is incorrect because one of integration tests failing.
https://travis-ci.org/magento/magento2/jobs/499362534

Message 
```
Failed asserting that 'SELECT `main_table`.*, SUM('store_id') AS `test_alias` FROM `trv_store` AS `main_table`' contains "SUM(store_id)".
```

It looks like result of this change - incorrect. SQL should be 
```
SELECT `main_table`.*, SUM(`store_id`) AS `test_alias` FROM `trv_store` AS `main_table`
```

2019-03-12 13:21 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Model/ResourceModel/Db/Collection/AbstractCollection.php
> +            $quotedFieldItem =  $this->getConnection()->quote($fieldItem);
Probably there should be something like this:
```suggestion
            $quotedFieldItem =  $this->getConnection()->quoteIdentifier($fieldItem);
```

2019-04-10 18:11 UTC, sidolov commented
@aario , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-10 18:11 UTC, closed without merging