SHQ18-1568 Updating UPS endpoint to use https. Http is no longer reli…
magento/magento2 pull request #21511
Opened 2019-02-28 15:14 UTC by wsajosh

…ably returning rates

This PR changes the UPS (non XML) endpoint from http to https. UPS are no longer returning rates reliably via a http request.

Test by placing any item into the cart with a weight > 0 and ship to a valid state and zip code such as NY 11705

2019-02-28 15:14 UTC, magento-engcom-team commented
Hi @wsajosh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-02-28 15:14 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=21511) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21511) before we can accept your contribution.<br/>

2019-03-01 06:14 UTC, ihor-sviziev commented on app/code/Magento/Ups/Model/Carrier.php
> +    protected $_defaultCgiGatewayUrl = 'https://www.ups.com:80/using/services/rave/qcostcgi.cgi';
looks like `https://www.ups.com:80/using/services/rave/qcostcgi.cgi` - not calid URL. Probably tit should be like this:
```suggestion
    protected $_defaultCgiGatewayUrl = 'https://www.ups.com/using/services/rave/qcostcgi.cgi';
```

2019-03-01 06:31 UTC, ihor-sviziev requested changes
Could you check my prev. comment?

2019-03-04 11:58 UTC, ihor-sviziev approved these changes

2019-03-04 12:00 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4426](https://jira.corp.magento.com/browse/ENGCOM-4426) has been created to process this Pull Request

2019-03-04 12:00 UTC, magento-engcom-team commented
@wsajosh thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-03-27 09:09 UTC, VasylShvorak commented
✔️ QA passed

2019-03-30 21:02 UTC, merged