21372 admin search suggestions toggle not working
magento/magento2 pull request #21522
Opened 2019-03-01 03:10 UTC by Stoyvo

Fix reported bug of broken admin toggle for frontend

### Description (*)
Loads system config value for Enable/Disable search suggestions, add conditional check on search suggestion request.

### Fixed Issues (if relevant)
1. magento/magento2#21372: Admin Search Suggestions Toggle Not Working

### Manual testing scenarios (*)
Scenario 1:
1. Enable Search Suggestions in Admin
2. Enter a search result on frontend (submit it, press enter)
3. Begin entering the same search query
4. Suggestions should appear

Scenario 2:
1. Disable Search Suggestions in Admin
2. Enter a search result on frontend (submit it, press enter)
3. Begin entering the same search query
4. Suggestions should **NOT** appear

### Contribution checklist (*)
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-01 03:10 UTC, magento-engcom-team commented
Hi @Stoyvo. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-05-03 09:11 UTC, rogyar requested changes
Hi @Stoyvo. Could you please check the failing tests

2019-05-17 15:05 UTC, sidolov commented
@Stoyvo , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-05-17 15:05 UTC, closed without merging

2021-01-14 05:32 UTC, Stoyvo commented on app/code/Magento/Search/Block/FormMini.php
> +declare(strict_types=1);
@rogyar What does this strict_types do?