Remove Environment emulation to better performance on sitemap generation
magento/magento2 pull request #21542
Opened 2019-03-01 14:00 UTC by Nazar65

### Description (*)
We dont need to use Environment emulation we just need to add in https://github.com/magento/magento2/blob/a5330a77625445ebc4552eaf3e7c34d44b26d2b2/app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php#L390 this `$this->_storeManager->setCurrentStore($storeId);` 

### Fixed Issues (if relevant)
1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)
Website URL 1: https://my_website.com
Website URL 2: https://my_website.co.uk

Got to Stores->Configuration->Catalog->XML Sitemap->General Settings:
2.Set to Enable, Start Time, Frequency Daily etc...
TIP: I've set to a few minutes before checking!

Website 1 should have images url referencing Website 1 domain = https://my_website.com

1.2 - Same steps for manual generating sitemap

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-01 14:00 UTC, magento-engcom-team commented
Hi @Nazar65. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-01 14:42 UTC, orlangur requested changes
Seems to be a reworked version of https://github.com/magento/magento2/pull/16813 and https://github.com/magento/magento2/pull/19598/files. Could you please remove unneeded dependencies then?

@sidolov @sivaschenko would be really nice if you change the logic as you reviewed older PR.

2019-03-01 15:09 UTC, Nazar65 commented
@orlangur Thanks, for some reason i forgot for this.

2019-03-05 13:10 UTC, sivaschenko requested changes
Hi @Nazar65 thanks for the pull request. The functionality looks fine, however, I don't think we can remove the arguments from construction at this time for backward compatibility purpose. Can you please preserve constructor signatures

2019-03-05 13:45 UTC, orlangur commented
@sivaschenko not really. We cannot change released class signature (@Nazar65 please revert those) but we are free to change the 2.3.2 targeted PR.

2019-03-05 14:11 UTC, sivaschenko approved these changes

2019-03-05 14:12 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-4438](https://jira.corp.magento.com/browse/ENGCOM-4438) has been created to process this Pull Request

2019-03-05 14:26 UTC, orlangur requested changes
@Nazar65 unneeded dependency introduced in https://github.com/magento/magento2/pull/19598/files must be removed.

Please squash into single commit after change.

2019-03-05 14:28 UTC, Nazar65 commented
@orlangur ok i agree with you but what about `backward compatibility` ?

2019-03-05 14:47 UTC, Nazar65 commented
@orlangur done :heavy_check_mark:

2019-03-05 14:51 UTC, sivaschenko commented
@orlangur I see what you mean, yes, those changes are not included in 2.3.1 :+1:

2019-03-05 15:09 UTC, orlangur approved these changes

2019-03-05 15:10 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4438](https://jira.corp.magento.com/browse/ENGCOM-4438) has been created to process this Pull Request

2019-03-05 22:19 UTC, fooman commented
Judging by the manual testing steps this is currently using English as a language only. Emulation also sets different locales, reloads translations and switches the area. This all seems to be removed in this PR.

2019-03-06 07:41 UTC, Nazar65 commented
@magento-engcom-team give me test instance

2019-03-06 07:42 UTC, magento-engcom-team commented
Hi @Nazar65. Thank you for your request. I'm working on Magento instance for you

2019-03-06 07:42 UTC, magento-engcom-team commented
Hi @Nazar65, here is your [new Magento instance](https://pr-21542.instances.magento-community.engineering).
Admin access: [https://pr-21542.instances.magento-community.engineering/admin](https://pr-21542.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-03-06 07:53 UTC, Nazar65 commented
@fooman No, everything works as expected from manual steps, and this works perfect on 2.2.7 without emulation.

2019-03-11 07:26 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-03-11 21:59 UTC, sidolov commented
Hi @Nazar65 , looks like these changes were introduced to fix the bug with sitemap generation in scope of https://github.com/magento/magento2/pull/15689. Could you please verify that initial case not reproducing with provided changes? 
Thank you!

2019-03-12 07:50 UTC, Nazar65 commented
@sidolov Yes,   initial case not reproducing with provided changes

2019-03-12 14:52 UTC, sidolov approved these changes

2019-03-14 19:47 UTC, merged