[2.3]] Database Media Storage - Design Config Save functions to be Database Media Storage aware
magento/magento2 pull request #21675
Opened 2019-03-10 15:13 UTC by gwharton

…renamed

aswell as the local file in pub/media.

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-10 15:13 UTC, magento-engcom-team commented
Hi @gwharton. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-04-22 14:22 UTC, orlangur commented
@aleron75 any update on this?

2019-04-23 05:54 UTC, aleron75 approved these changes

2019-04-23 07:57 UTC, VasylShvorak commented
Hi @gwharton could you resolve merge conflicts?

2019-04-23 20:40 UTC, gwharton commented
OK, sometimes github does things that I really don't understand.

So i used the github "Resolve conflict" feature to resolve the conflicts. This appeared to work ok, but if you look at the commit history, the resolve conflicts also merged all changes from 2.3-develop into my PR since the PR was created. This means the commit for this PR is now massive!!!! Arghh.

Will I really be re-committing all of the changes made in the last month in 2.3-develop back in on itself????? I don't know what to do to get out of this.

2019-04-24 07:19 UTC, aleron75 commented
> If you look at the commit history, the resolve conflicts also merged all changes from 2.3-develop into my PR since the PR was created. 

It means that, since you forked the repo, some changes were merged in the main branch and it's normal that your PR now includes those changes because your fork was not up to date anymore.

2019-04-24 07:39 UTC, gwharton commented
Ok. Thats great. For one moment i thought my pr would be "recommitting" all those changes twice.

2019-04-24 12:54 UTC, orlangur requested changes
Please squash changes into a single commit so that we have perfectly clean history 😉

2019-04-24 13:38 UTC, gwharton commented
@orlangur, perhaps I am doing it wrong, I did try and squash them last night into a single commit, but my squashed commit ended up containing all of the changes from the merge of 2.3-develop back into my branch, which I am sure is not what is wanted.

What is the correct way of doing it, when one of the commits, is a merge of 2.3-develop into my branch.

On previous attempts I would have
```
git checkout branch 
git reset --soft HEAD~XXX
git commit
git push --force origin branch
```

2019-04-24 13:42 UTC, orlangur commented
@gwharton create a new branch from a fresh `2.3-develop` and then `git merge --squash` from the old branch.

2019-04-27 20:00 UTC, sivaschenko requested changes
Hi @gwharton , thanks for the pull request, please see my suggestion in the review comment

2019-04-27 20:00 UTC, sivaschenko commented on app/code/Magento/Theme/Model/Design/Backend/File.php
> +        Database $databaseHelper,
This class is not API, however, let's still try to make this change as backward compatible as possible: could you please add new constructor parameter in a backward compatible way (last optional parameter, property is initialized with object manager if the parameter is not passed)

2019-04-29 09:59 UTC, gwharton commented on app/code/Magento/Theme/Model/Design/Backend/File.php
> +        Database $databaseHelper,
Done as requested.

2019-04-29 10:34 UTC, sivaschenko approved these changes

2019-04-29 10:35 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-4802](https://jira.corp.magento.com/browse/ENGCOM-4802) has been created to process this Pull Request

2019-04-29 11:39 UTC, gwharton commented
Backport PR at #21676 has been updated inline with this parent PR, and is ready to go once this has been processed.

2019-04-29 17:01 UTC, gwharton commented
Not sure whats going on with the travis build. Not sure its anything to do with me. Looks to be failing attempting to fork a process under php 7.2. I've tried rerunning the travis build twice and it fails with same error.

2019-05-07 21:52 UTC, sdzhepa commented
:heavy_check_mark: QA Passed

2019-05-14 15:06 UTC, merged