Refactor \Order\Shipment\AddTrack Controller to use ResultInterface
magento/magento2 pull request #21822
Opened 2019-03-18 14:15 UTC by JeroenVanLeusden

### Description (*)
Refactor \Order\Shipment\AddTrack Controller to use ResultInterface and Repository to save shipment.

### Fixed Issues (if relevant)
1. None I could find.

### Manual testing scenarios (*)
1. Place order.
2. Create shipment without tracking information.
3. Add tracking information to shipment.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-18 14:15 UTC, magento-engcom-team commented
Hi @JeroenVanLeusden. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-18 14:16 UTC, JeroenVanLeusden commented
Will update the tests if necessary when implementation itself is correct.

2019-03-19 14:32 UTC, VladimirZaets approved these changes

2019-03-19 14:34 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4532](https://jira.corp.magento.com/browse/ENGCOM-4532) has been created to process this Pull Request

2019-03-20 09:32 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-03-20 15:33 UTC, sidolov requested changes

2019-03-20 15:33 UTC, sidolov commented on app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/AddTrack.php
> +    public function execute(): ResultInterface
It's a good idea to add strict type to the method but unfortunately, we are not allowed to change public methods signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-03-21 16:27 UTC, Jeroenll commented on app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/AddTrack.php
> +    public function execute(): ResultInterface
@sidolov Removed the return type.

2019-03-22 18:38 UTC, sidolov approved these changes

2019-03-22 18:39 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-4532](https://jira.corp.magento.com/browse/ENGCOM-4532) has been created to process this Pull Request

2019-03-25 12:05 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-03-29 14:50 UTC, merged