Contact us layout in I-pad not proper
magento/magento2 pull request #21896
Opened 2019-03-22 13:22 UTC by amol2jcommerce

### Description (*)

Contact us layout in I-pad not proper

### Preconditions (*)

1. Magento 2.3, 2.2
2. Contact us layout in I-pad not proper

### Steps to reproduce (*)

1. Open contact us form in I-pad

### Expected result (*)
1. If you check the create account form, orders and returns form, advance search form (forms in I-pad views) - it behaves much better in terms of responsive design.

![Contact_Us_1](https://user-images.githubusercontent.com/18118631/54825044-9baa8e80-4cd2-11e9-8dff-3eb6df68d8bb.jpg)

### Actual result (*)
1. If you take a look at iPad resolution - the form is quite small

![Contact_Us_2](https://user-images.githubusercontent.com/18118631/54825074-b11fb880-4cd2-11e9-9e5a-c458e47904e4.jpg)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-22 13:22 UTC, magento-engcom-team commented
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-22 13:55 UTC, Karlasa commented
@magento-engcom-team give me test instance

2019-03-22 13:55 UTC, magento-engcom-team commented
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

2019-03-22 13:56 UTC, magento-engcom-team commented
Hi @Karlasa, here is your [new Magento instance](https://pr-21896.instances.magento-community.engineering).
Admin access: [https://pr-21896.instances.magento-community.engineering/admin](https://pr-21896.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-03-22 13:59 UTC, Karlasa requested changes
This change will make form overflow on mobile devices. 
<img width="760" alt="Screen Shot 2019-03-22 at 15 57 34" src="https://user-images.githubusercontent.com/5417554/54827738-60e92c00-4cbb-11e9-84b5-02a5a7b07abd.png">

2019-03-22 14:02 UTC, amol2jcommerce commented
@magento-engcom-team give me test instance

2019-03-22 14:02 UTC, magento-engcom-team commented
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento instance for you

2019-03-22 14:03 UTC, magento-engcom-team commented
Hi @amol2jcommerce, here is your [new Magento instance](https://pr-21896.instances.magento-community.engineering).
Admin access: [https://pr-21896.instances.magento-community.engineering/admin](https://pr-21896.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-03-22 14:05 UTC, amol2jcommerce commented
Hi @Karlasa Fixed mention issue on mobile devices and update branch.
please review once.

2019-03-22 14:17 UTC, Karlasa requested changes
Why not just? 

`
//
//  Desktop
//  _____________________________________________

.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {
    .contact-index-index .column:not(.sidebar-additional) .form.contact {
        min-width: 600px;
        width: 50%;
    }
}
`
basically as same as other forms under Magento_Customer

2019-03-25 05:28 UTC, amol2jcommerce commented
Hi @Karlasa, I update branch please review.

2019-03-26 07:02 UTC, Karlasa commented
@magento-engcom-team give me test instance

2019-03-26 07:02 UTC, magento-engcom-team commented
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

2019-03-26 07:02 UTC, magento-engcom-team commented
Hi @Karlasa, here is your [new Magento instance](https://pr-21896.instances.magento-community.engineering).
Admin access: [https://pr-21896.instances.magento-community.engineering/admin](https://pr-21896.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-03-26 07:05 UTC, Karlasa approved these changes

2019-03-26 07:06 UTC, magento-engcom-team commented
Hi @Karlasa, thank you for the review.
[ENGCOM-4580](https://jira.corp.magento.com/browse/ENGCOM-4580) has been created to process this Pull Request

2019-03-29 10:45 UTC, VasylShvorak commented
✔️ QA passed

2019-04-05 15:22 UTC, merged