Prevent duplicate variation error during import of configurable products with numerical SKUs
magento/magento2 pull request #21917
Opened 2019-03-25 08:25 UTC by alexander-aleman

### Description (*)

When importing configurable products, the validation process checks if the linked variations contain duplicate SKUs, this is done using: `in_array($option['_super_products_sku'], $skus)`. The problem that occurs is when you have SKUs that when compared non strict are considered equal, in_array returns true e.g. `in_array('1234.10', ['1234.1'])`, when using the strict option e.g. `(in_array('1234.10', ['1234.1'], true)` the result is false. Since SKUs are strings the latter is the expected behaviour.

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

1. Import a configurable product where the SKUs of the variations are numerical and not compared strictly are equal (e.g. 1234.1 and 1234.10)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-25 08:25 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=21917) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21917) before we can accept your contribution.<br/><hr/>**Alexander Aleman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-03-25 08:25 UTC, magento-engcom-team commented
Hi @alexander-aleman. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-25 11:18 UTC, josefbehr approved these changes

2019-03-25 11:19 UTC, magento-engcom-team commented
Hi @josefbehr, thank you for the review.
[ENGCOM-4566](https://jira.corp.magento.com/browse/ENGCOM-4566) has been created to process this Pull Request

2019-03-25 12:00 UTC, orlangur requested changes

2019-03-25 12:00 UTC, orlangur commented on app/code/Magento/ConfigurableImportExport/Test/Unit/Model/Import/Product/Type/ConfigurableTest.php
> +                $this->assertTrue($result);
Did you notice there are more logic in test than in actual method?

Please refactor is as a separate test method.

2019-03-25 12:00 UTC, orlangur commented on app/code/Magento/ConfigurableImportExport/Test/Unit/Model/Import/Product/Type/ConfigurableTest.php
> +            '_product_websites' => 'website_1',
Please put such data out of a test method, data provider maybe.

2019-05-02 13:38 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-14 15:06 UTC, merged