Admin-Order-Create-Set-Save-address-checkbox-true-as-default-#106
magento/magento2 pull request #21932
Opened 2019-03-26 09:18 UTC by krnshah

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#106: Admin Order Create - Save address as default
https://github.com/magento/community-features/issues/106

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-26 09:18 UTC, magento-engcom-team commented
Hi @krnshah. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-26 12:47 UTC, dmytro-ch requested changes
Hi @krnshah,
thank you for your contribution!
Could you please check the CR comment?

2019-03-26 12:47 UTC, dmytro-ch commented on app/code/Magento/Sales/view/adminhtml/templates/order/create/form/address.phtml
> -                   <?php if (!$block->getDontSaveInAddressBook() && $block->getAddress()->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>
I think we should keep at least first part of the condition.
```
!$block->getDontSaveInAddressBook()
```
So we would make sure the saving billing address is turned off, when it is the same as shipping.

2019-04-01 18:07 UTC, dmytro-ch approved these changes

2019-04-01 18:08 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4636](https://jira.corp.magento.com/browse/ENGCOM-4636) has been created to process this Pull Request

2019-04-08 13:33 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-04-11 19:17 UTC, merged