MysqlMq: Use new MessageQueue Config interface, update unit tests
magento/magento2 pull request #21942
Opened 2019-03-26 16:51 UTC by Berdir

### Description (*)
This fixes the deprecated usage of the old ConfigInterface in MysqlMQ

### Fixed Issues (if relevant)

1. magento/magento2#21904:  \Magento\MysqlMq\Model\Driver\Exchange uses deprecated getQueuesByTopic, results in exception

### Manual testing scenarios (*)
See issue, using the MysqlMq adapter for a message queue is currently not working at all.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-26 16:51 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=21942) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21942) before we can accept your contribution.<br/>

2019-03-26 16:51 UTC, magento-engcom-team commented
Hi @Berdir. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-27 10:03 UTC, Berdir commented
Had a look at the failing test, but can't reproduce that locally and don't know how that could be related.

I did have a look at the functional tests and realized for example \Magento\MysqlMq\Model\PublisherConsumerTest is completely skipped right now, which is failing hard if you remove that. I started updating that but I don't know enough about Magento and it would be a lot of work. I started updating the config a bit, but then got stuck. Pushed what I have to:https://github.com/Berdir/magento2/tree/functional-mysql-mq-test-updates

I would suggest to consider merging this (assuming the functional test fail was either random or can be fixed) and look into updating the functional tests after that. Right now, the MysqlMq compontent is completely non-functional.

2019-07-08 04:31 UTC, fooman commented
This is the last Travis message

```
PHP Fatal error:  Uncaught PHPUnit\Framework\Exception: Warning: exec(): Unable to fork [tasklist.exe /fi 'PID eq 8687' /fo CSV /nh 2>&1] in /home/travis/build/magento/magento2/lib/internal/Magento/Framework/Shell.php:58.
/home/travis/build/magento/magento2/dev/tests/integration/framework/bootstrap.php:134
/home/travis/build/magento/magento2/lib/internal/Magento/Framework/Shell.php:58
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php:89
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php:52
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php:127
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php:59
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php:50
  thrown in /home/travis/build/magento/magento2/dev/tests/integration/framework/bootstrap.php on line 134
Fatal error: Uncaught PHPUnit\Framework\Exception: Warning: exec(): Unable to fork [tasklist.exe /fi 'PID eq 8687' /fo CSV /nh 2>&1] in /home/travis/build/magento/magento2/lib/internal/Magento/Framework/Shell.php:58.
/home/travis/build/magento/magento2/dev/tests/integration/framework/bootstrap.php:134
/home/travis/build/magento/magento2/lib/internal/Magento/Framework/Shell.php:58
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php:89
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php:52
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php:127
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php:59
/home/travis/build/magento/magento2/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php:50
```

might be good to re-run the tests on the new testing infrastructure.

2019-07-13 10:48 UTC, nuzil requested changes
Didn't find better way to implement it with current methods available. 
But we also can do a new resolver for minimise code duplication and move those 2 repeatable parts of code there.

2019-07-13 10:48 UTC, nuzil commented on app/code/Magento/MysqlMq/Model/Driver/Bulk/Exchange.php
> +          if ($exchange->getConnection() == 'db') {
You can use this resolver:
Magento\MysqlMq\Model\ConnectionTypeResolver which will allow you to detect Mysql connection type: getConnectionType. Which is basically if NOT a null, then a Mysql connection

2019-07-13 10:48 UTC, nuzil commented on app/code/Magento/MysqlMq/Model/Driver/Exchange.php
> +          if ($exchange->getConnection() == 'db') {
You can use this resolver:
Magento\MysqlMq\Model\ConnectionTypeResolver which will allow you to detect Mysql connection type: getConnectionType. Which is basically if NOT a null, then a Mysql connection

2019-07-29 16:00 UTC, sidolov commented
@Berdir , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-07-29 16:00 UTC, closed without merging