Configurabel products special price bug 10303
magento/magento2 pull request #21959
Opened 2019-03-27 08:21 UTC by nadeefit6

### Description (*)
vendor/magento/module-swatches/view/frontend/web/js/swatch-renderer.js
-            selectorProduct: '.product-info-main',
+            selectorProduct: '.--product-info-main',

### Fixed Issues (if relevant)
1. magento/magento2#10303: Configurabel products special price bug
2. ...

### Manual testing scenarios (*)

1. Create configurable product with simple products
2. Add special Prices to Simple products associated with the configurable product
3. Clear Cache
4. Go to Product detail page
5. Change the configurable option drop-down(Ex:size) and check Price
6. Special Price of simple product should be displayed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-27 08:21 UTC, magento-engcom-team commented
Hi @nadeefit6. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-27 10:41 UTC, orlangur requested changes
Thanks @nadeefit6 for your contribution! Let's wait for issue to be confirmed and then apply necessary changes to PR please.

2019-03-27 10:41 UTC, orlangur commented on app/code/Magento/Paypal/Controller/Express/AbstractExpress/PlaceOrder.php
> +            }
Revert changes in this file.

2019-03-27 10:41 UTC, orlangur commented on app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js
> +            selectorProduct: '.--product-info-main',
Such selector is actually incorrect and violates https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-demarcation.html

Please add appropriate data attributes instead and add here.

2019-04-10 18:50 UTC, sidolov commented
@nadeefit6 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-10 18:50 UTC, closed without merging