Fixed magento swatch option tooltip design issue
magento/magento2 pull request #21995
Opened 2019-03-28 09:02 UTC by vishal-7037

### Description (*)

Fixed Magento swatch option tooltip bottom arrow design issue.

### Fixed Issues (if relevant)

1. magento/magento2#21994: Magento Swatch Tooltip: bottom arrow design issue

### Manual testing scenarios (*)

1. Go to configurable category view page
2. hover on swatch attribute.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-28 09:02 UTC, magento-engcom-team commented
Hi @vishal-7037. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-04-23 14:36 UTC, VladimirZaets approved these changes

2019-04-23 14:37 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4806](https://jira.corp.magento.com/browse/ENGCOM-4806) has been created to process this Pull Request

2019-04-24 07:20 UTC, stoleksiy commented
@magento-engcom-team give me 2.3-develop instance

2019-04-24 07:21 UTC, magento-engcom-team commented
Hi @stoleksiy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-04-24 07:21 UTC, magento-engcom-team commented
Hi @stoleksiy, here is your [Magento instance](https://i-21995-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21995-2-3-develop.instances.magento-community.engineering/admin](https://i-21995-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-04-24 07:31 UTC, stoleksiy commented
Hi @vishal-7037 ! I can not reproduce the issue #21994. 

Result (**Luma**) :
![before(luma)](https://user-images.githubusercontent.com/44244273/56640521-e3c72300-667b-11e9-8fa6-5fca4a109c7a.png)

Result (**Blank**) :
![before(blank)](https://user-images.githubusercontent.com/44244273/56640541-f0e41200-667b-11e9-99d5-17e32656bb3a.png)

Could you please recheck on fresh 2.3-develop instance?!
Thanks!

2019-04-25 20:29 UTC, vishal-7037 commented
@magento-engcom-team give me 2.3-develop instance

2019-04-25 20:29 UTC, magento-engcom-team commented
Hi @vishal-7037. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-04-25 20:30 UTC, magento-engcom-team commented
Hi @vishal-7037, here is your [Magento instance](https://i-21995-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21995-2-3-develop.instances.magento-community.engineering/admin](https://i-21995-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-04-25 20:54 UTC, vishal-7037 commented
Hi, @stoleksiy ,
I've checked in Magento 2.3 vanilla instance now, it is not reproduce here.

But, you can check in issue's conversation. I've replicate this same issue in vanilla Magento 2.3 Instance with Private window of chrome browser.

Thanks.

2019-04-27 19:51 UTC, sivaschenko requested changes
Hi @vishal-7037 @stoleksiy , if the issue is not actual anymore I believe the pull request and the issue itself can be closed

2019-04-30 11:38 UTC, stoleksiy commented
Hi @sivaschenko  @vishal-7037 ! I closed this pull request as the issue #21994 is not actual anymore!
Thanks!

2019-04-30 11:38 UTC, closed without merging