Do not validate length and input rule if attribute value is required but empty
magento/magento2 pull request #22003
Opened 2019-03-28 10:11 UTC by VincentMarmiesse

Hi,

### Description (*)
The EAV text attribute validation continues even if a required attribute is required but has no value.
It raises the error 
```
Argument 2 passed to Magento\Eav\Model\Attribute\Data\Text::validateLength() must be of the type string, null given, called in /var/www/html/vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 80
```
when creating a customer without a required attribute with GraphQL for example.

### Manual testing scenarios (*)
1. Create a required customer attribute
2. Register a new customer with GraphQL request `createCustomer` but without setting this required attribute
3. Magento should return the error `"Attribute" is a required value.`

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-28 10:12 UTC, magento-engcom-team commented
Hi @VincentMarmiesse. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

2019-03-28 13:57 UTC, orlangur requested changes
`@param array|string $value` such value as `null` must not be passed to this method. Please filter it out on higher level.

2019-03-28 14:12 UTC, VincentMarmiesse commented
@orlangur Ok so you want me to change these lines: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Eav/Model/Validator/Attribute/Data.php#L128-L130 right?

We could change it to
```
if (!isset($data[$attributeCode])) {
   continue;
}
```
what do you think?

2019-06-14 12:35 UTC, engcom-dev-Foxtrot commented
@VincentMarmiesse please update PR, or we will close it as inactive.

2019-06-14 12:48 UTC, VincentMarmiesse commented
Hi @engcom-dev-Foxtrot,
I'm not sure what I need to do, I'm waiting for @orlangur advice.

2019-08-13 20:07 UTC, sidolov approved these changes

2019-08-13 20:07 UTC, sidolov commented
> `@param array|string $value` such value as `null` must not be passed to this method. Please filter it out on higher level.

It does not make sense to validate the value that equal to null.

2019-08-13 20:08 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5616](https://jira.corp.magento.com/browse/ENGCOM-5616) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-27 12:55 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:**

![before](https://user-images.githubusercontent.com/51679138/63773032-05167500-c8e3-11e9-8038-f83960582ac8.png)

**After:**

![after](https://user-images.githubusercontent.com/51679138/63773050-0cd61980-c8e3-11e9-9528-6cd8fb50e159.png)

2019-08-27 22:22 UTC, merged