Fix for unable to update products via csv file, when products ids fro…
magento/magento2 pull request #22032
Opened 2019-03-29 12:34 UTC by mtwegrzycki

### Description (*)
It is fix for issue #22028

In query for selecting ids to indexing after import products, I changed "between" into "in",
Before change, when products were updated via csv file import in Admin panel, to indexing process were selected all products from range between the smallest and the biggest products id from csv file. When the ids were from wide range, it caused selecting a huge amount of data and attempt to inserting them to catalog_product_index_price_temp. If data amount was to big, it caused error
After change, for indexing process are selected only products from csv file.

Example:
Before change, when we try to update two products with id 30 and 31, only two products were selected to indexing. 
When products have ids 30 and 50, it caused, that 21 products were selected to indexing (All products with ids between 30 and 50.

After change, in both cases described above, only two products will be selected to indexing.

### Fixed Issues (if relevant)
No related issues found.

### Manual testing scenarios (*)
The same scenario can be applied to reproduce bug and check fix:
1. Prepare csv file to update products (2 products or more). (This csv should contain products with the lowest and the highest id - 1 and 6000)
2. In Admin panel go to: System->Import and choose Product and Add/Update
3. Upload file
4. Check Data
5. Import csv file (error should be displayed now)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-29 12:34 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22032) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22032) before we can accept your contribution.<br/>

2019-04-03 21:41 UTC, orlangur commented on app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Price/Query/BaseFinalPrice.php
> +                $select->where('e.entity_id IN(?)', $entityIds);
@kandy @mslabko @duhon do you remember? Something similar was done in other place. Please share your thoughts.

2019-04-04 21:30 UTC, orlangur commented on app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Price/Query/BaseFinalPrice.php
> +                $select->where('e.entity_id IN(?)', $entityIds);
Yay, I met it accidentally: https://github.com/magento/magento2/pull/19878#discussion_r243217689

2019-04-21 07:32 UTC, mtwegrzycki commented
I can see, that related PR #19878 is closed. Can we remove On hold label? There are any requirements to continue this PR?

2019-04-22 13:09 UTC, orlangur commented
@mtwegrzycki surely, feel free to proceed with suggested in that PR changes.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-04-22 13:10 UTC, orlangur requested changes
@mtwegrzycki surely, feel free to proceed with suggested in that PR changes.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-04-26 12:05 UTC, orlangur commented
@mtwegrzycki there must be two `where` conditions after change (see comment I referred to).

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-04-27 19:30 UTC, mtwegrzycki commented
Okay, I added new commit with second where conditions.

2019-04-29 07:19 UTC, mtwegrzycki commented
I can see, that there any integration errors in Travis. But it does not look like related to my code changes.
Please, let me know, if there are required any additional actions from me.

2019-05-01 16:24 UTC, closed without merging