fix saving inactive admin user, when record doesn't exist in oauth_token table
magento/magento2 pull request #22118
Opened 2019-04-02 14:57 UTC by dxx004

### Description (*)

PR handles thrown exception during saving inactive admin user or saving admin rule with inactive admin user assigned, when record (for the admin user) doesn't exist in `oauth_token` table.

### Fixed Issues (if relevant)

1. ...
2. ...

### Manual testing scenarios (*)

1. in backend - Navigate to System -> Permissions -> All Users
2. Add new *inactive* user, don't assign any role
3. Save
4. Error message "This user has no tokens." is shown, user is not saved

the same error is shown, when trying to assign inactive admin user to admin role and save.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-02 14:57 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22118) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22118) before we can accept your contribution.<br/>

2019-04-02 21:04 UTC, orlangur requested changes
@dxx004 please report an issue so that it can be verified first.

2019-04-02 21:04 UTC, orlangur commented on app/code/Magento/Integration/Plugin/Model/AdminUser.php
> +                //token for admin use doesn't exist in oauth_token table, no action
This exception looks like intentionally not caught before. What are other possibilities of fix?

2019-04-04 12:51 UTC, dxx004 commented
@orlangur , found out it's duplicate issue of this PR https://github.com/magento/magento2/pull/20772 , so closing this one. Thx

2019-04-04 12:51 UTC, closed without merging

2019-04-04 13:06 UTC, orlangur commented
@dxx004 oh, thanks, that's why it is a good idea to search for existing bug report :)