Removed client preference from Magento\ReleaseNotification module
magento/magento2 pull request #22179
Opened 2019-04-05 16:02 UTC by tephereth

### Description (*)
A preference for `ClientInterface` was wrongly present in `Magento\ReleaseNotification` module. This fix is related to the MSI issue: https://github.com/magento-engcom/msi/issues/2128 and to the MSI pull request: https://github.com/magento-engcom/msi/pull/2144

### Fixed Issues (if relevant)
Related to MSI issue: https://github.com/magento-engcom/msi/issues/2128

### Manual testing scenarios (*)
Testable on MSI, see https://github.com/magento-engcom/msi/pull/2144

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [ x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-06 08:11 UTC, orlangur requested changes
Why it is removed and not moved to https://github.com/magento/magento2/blob/2.3-develop/app/etc/di.xml?

How https://github.com/magento/magento2/commit/da443ffb408593bce1ae6971f4701974b0310eba#diff-3c49a41920d4a1473c3cb45ad0cab3ec will work after this change?

2019-04-06 08:50 UTC, tephereth commented
Working on this fix for MSI I've noticed that the `ClientInterface` preference involves many classes of `InventoryDistanceBasedSourceSelection`; first thought was to add type direct in the `di.xml` of the MSI module and `ReleaseNotification` module. But since most of Magento\Framework preferences are anyway stored in the general `etc/di.xml`, I guess the solution that @orlangur suggested is cleaner.

2019-04-06 10:36 UTC, orlangur requested changes
Please squash changes into a single commit so that we have perfectly clean history 😉

2019-04-06 12:49 UTC, tephereth commented
@orlangur, commits squashed

2019-04-06 12:52 UTC, orlangur approved these changes

2019-04-06 12:53 UTC, orlangur commented
Thanks @tephereth! Would be nice to grep for `preference.*framework` in `app/code` to catch all such also.

2019-04-06 12:53 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4693](https://jira.corp.magento.com/browse/ENGCOM-4693) has been created to process this Pull Request

2019-04-08 19:03 UTC, orlangur commented
This actually duplicates https://github.com/magento/magento2/pull/21540

2019-04-08 19:03 UTC, closed without merging