magento/magento2#21232: Custom select attribute code container breaks…
magento/magento2 pull request #22218
Opened 2019-04-08 13:44 UTC by m-a-x-i-m

… javascript on update attributes.

### Description

Added "attributes_" prefiix to id of input fields of attributes in Mass Update Products Attributes page

### Fixed Issues

magento/magento2#21232: Custom select attribute code "container" breaks javascript on update attributes

### Manual testing scenarios

1. Create a custom select attribute with a code of "container"
2. Go to the Catalog->Products and check the box next to at least one product.
3. Click the Action dropdown and select "Update Attributes"
4. Scroll down until you see your container attribute and you will see that it is not disabled

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-08 13:44 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22218) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22218) before we can accept your contribution.<br/><hr/>**Maxim Tkachuk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-04-08 16:24 UTC, orlangur requested changes

2019-04-08 16:24 UTC, orlangur commented on app/code/Magento/Catalog/Test/Mftf/Section/AdminEditProductAttributesSection.xml
> +        <element name="AttributeName" type="text" selector="#attributes_name"/>
Please change all selectors so that they do not violate https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-demarcation.html

2019-04-22 19:09 UTC, sidolov commented
@m-a-x-i-m , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-22 19:09 UTC, closed without merging