Show converted value for validateForRefund error message
magento/magento2 pull request #22211
Opened 2019-04-08 10:51 UTC by kassner

### Description

When refunding an order placed in a different currency then the default one (via admin), the refund validation is not taking into account this difference when showing the error message. The message is formatted with the correct currency, but the amount is wrong.

In my tests, with a product of $1.00 and exchange rate for USD-EUR of 0.88, I was getting `The most money available to refund is €1.00.` instead of `The most money available to refund is €0.88.`

### Manual testing scenarios

1. Place an order with at least 2 units of a product via Admin using a different currency than the default one;
2. Partially invoice this order (1 item only);
3. Create a credit memo for the entire order;

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-09 07:51 UTC, rogyar commented
@magento-engcom-team give me test instance

2019-04-09 07:51 UTC, magento-engcom-team commented
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

2019-04-09 07:52 UTC, magento-engcom-team commented
Hi @rogyar, here is your [new Magento instance](https://pr-22211.instances.magento-community.engineering).
Admin access: [https://pr-22211.instances.magento-community.engineering/admin](https://pr-22211.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-09 08:24 UTC, rogyar commented
Hi @kassner. Thank you for your contribution. I believe we have a sort of bug here. An amount in the error message should be in the base currency (with the base currency symbol). So instead of converting base amount to the actual currency amount, we should just change the currency symbol to the base one. 
If you check the Refund Totals section, you can see that all values in the inputs are processed as base currency values. So if we enter some amount in base currency, it does not make sense to show an error with the amount converted to another currency.
The approach for Refund Shipping is correct in this case. If you put a value that is greater than a shipping cost, you will see an error message with the maximum value (in base currency, which is correct) that you can enter in this field.

2019-04-10 09:45 UTC, kassner commented
@rogyar I updated the code to fix it.

2019-05-27 15:50 UTC, rogyar approved these changes

2019-05-27 15:51 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-5172](https://jira.corp.magento.com/browse/ENGCOM-5172) has been created to process this Pull Request

2019-05-28 10:12 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

**Before:**

![before](https://user-images.githubusercontent.com/44244273/58470371-38156500-814a-11e9-8385-af263a967c5d.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/58470392-42cffa00-814a-11e9-8c36-07abd73b862b.png)

2019-05-28 13:00 UTC, Nazar65 requested changes
https://github.com/magento/magento2/blob/286009fe8e91c4a6463b61440750b4f39b741b87/app/code/Magento/Sales/Model/Order.php#L1793

Hi @kassner thank you for collaboration, such changes is Backward Incompatible, please see ->https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/

> Introduction of a method to a class or interface
> Create a new interface with a new method instead of introducing a method to a class or interface.
> 
> The new interface may take over existing methods from the class if it makes sense to group them together. In this case, you must deprecate corresponding methods in the old interface/class with the @see annotation. The old methods should proxy the calls to the new interface instead of duplicating the logic.
> 
> For an example of an interface with an extracted method see the Magento\Catalog\Api\CategoryListInterface. This interface is responsible for the getList() method, but Magento\Catalog\Api\CategoryRepositoryInterface does not have that method.
> 
> For a PATCH product release, do NOT mark the new interface with @api.
> For a MINOR product release, an architect marks, or approves, the new interface with @api if applicable.

2019-06-05 08:14 UTC, kassner commented
@Nazar65 I changed the PR to not touch `\Magento\Sales\Model\Order`

2019-06-06 06:52 UTC, Nazar65 commented
Hi @rogyar please review.

2019-06-11 15:52 UTC, sidolov approved these changes

2019-06-11 15:53 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5172](https://jira.corp.magento.com/browse/ENGCOM-5172) has been created to process this Pull Request

2019-06-13 12:23 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-06-20 20:48 UTC, merged