Issue#14071
magento/magento2 pull request #22217
Opened 2019-04-08 13:36 UTC by m-a-x-i-m

### Description

Added page size selector for dynamic rows template
which is used in back office product edit page Related Products, Up-Sells, and Cross-Sells lists

### Fixed Issues 

magento#14071: Not able to change a position of last two related products in case of I've 20+ related products.

### Manual testing scenarios

go to BO > Catalog > Products > Edit open "Related Products, Up-Sells, and Cross-Sells" collapsible tab
check page size selector near the pager

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-08 13:37 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22217) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22217) before we can accept your contribution.<br/><hr/>**Maxim Tkachuk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-04-09 07:55 UTC, rogyar commented
Hi @m-a-x-i-m. Please, sign CLA. It's necessary for further PR processing. Thank you

2019-04-19 15:16 UTC, VladimirZaets requested changes
Hi @m-a-x-i-m. Thanks for collaboration. I think the better is to generate options on JS side, instead of hardcode their in template

2019-04-26 14:54 UTC, sidolov commented
@m-a-x-i-m , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-04-26 14:54 UTC, closed without merging