[Backport] MAGETWO-61422 Respect Category Top Navigation Max Depth setting
magento/magento2 pull request #22235
Opened 2019-04-09 07:43 UTC by torhoehn

### Original Pull Request 
 https://github.com/magento/magento2/pull/12640
### Description
The setting `Stores > Configuration > Catalog > Catalog > Category Top Navigation > Maximal Depth` was actually never being used to limit the top menu maximum depth.

Now the setting will be used as a condition for the category collection when it is fetched.

### Fixed Issues
1. magento/magento2#7543: Category Top Navigation / Maximal Depth configuration not working

### Manual testing scenarios
1. Change the setting in the backend
2. Refresh the invalidated cache
3. See that the setting actually is being used

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-09 11:31 UTC, orlangur approved these changes

2019-04-09 11:33 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4716](https://jira.corp.magento.com/browse/ENGCOM-4716) has been created to process this Pull Request

2019-04-10 09:17 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-04-27 08:42 UTC, sivaschenko requested changes
Thanks for the backport @torhoehn ! However, the pull request contains several backward incompatible and not suitable for patch upgrade changes (introduced public functions and constructor parameters)

Considering the above,  wouldn't backport this change to 2.2-develop branch. Please let me know what you think

cc @orlangur

2019-04-27 08:42 UTC, sivaschenko commented on app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php
> +    public function addNavigationMaxDepthFilter()
Adding public methods to API classes in patch releases is prrrohibited by our backward compatibility policy

2019-05-17 15:15 UTC, sidolov commented
@torhoehn , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-05-17 15:15 UTC, closed without merging