[Performance] Fix array merge in loop to speed up static content deploy
magento/magento2 pull request #22248
Opened 2019-04-09 17:39 UTC by ihor-sviziev

### Description (*)
This PR improving static content deploy speed.

For instance i tried to compile Magento/blank theme for 6 different locales (I have all these language packs installed).
```bash
php bin/magento setup:static-content:deploy -f --jobs=2 --area frontend en_US locale2 locale3 locale4 locale5 locale6 --theme Magento/blank
```

Before applying this patch: 109 seconds on my machine.
After applying this patch: 93 seconds on my machine.

If we'll execute for SCD for multiple theme - results should be bigger.

More info about array_merge in loop:
https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-function-used-in-loop

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-10 13:01 UTC, orlangur requested changes
@ihor-sviziev if I remember correctly, we have a rule in recently released coding standard for `array_merge` in loop. Could you please check?

2019-04-10 13:36 UTC, orlangur commented
@ihor-sviziev ok, that's here I saw it: https://github.com/magento/magento-coding-standard/pull/72#issuecomment-481692548

So, standard is just evolving without any connection with reality :)

2019-04-10 13:36 UTC, orlangur approved these changes

2019-04-10 13:38 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4723](https://jira.corp.magento.com/browse/ENGCOM-4723) has been created to process this Pull Request

2019-04-22 13:51 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-04-25 16:24 UTC, sidolov requested changes

2019-04-25 16:24 UTC, sidolov commented on app/code/Magento/Deploy/Package/Processor/PreProcessor/Css.php
> +            $result[] = $this->collectFileMap($path);
An integration test is failing with provided changes: `\Magento\Deploy\DeployTest`
After the short investigation, we found that `$path` var can be the type of array and will break the check `$this->map[$fileName]`.

2019-05-17 15:16 UTC, sidolov commented
Hi @ihor-sviziev , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-07-11 06:41 UTC, closed without merging

2019-07-15 11:53 UTC, orlangur commented
@ihor-sviziev wazzup?)

2019-07-18 06:18 UTC, ihor-sviziev commented
> @ihor-sviziev wazzup?)

There is an issue that really hard to debug. I don't have free time for now.

2020-10-01 08:39 UTC, ihor-sviziev commented
FYI I applied the same change (and fixed it) in the https://github.com/magento/magento2/pull/30153, it already got merged.