Use proper variables for tooltip styles on tablet devices
magento/magento2 pull request #22258
Opened 2019-04-10 07:51 UTC by vovayatsyuk

### Description
There are variables available for tooltip customization. This commit fixes an issue
on tablet devices when trying to use them.

### Manual testing scenarios
 1. Open `Magento/blank/Magento_Checkout/web/css/source/module/checkout/_tooltip.less` file and change the values of the tooltip variables as follows (Usually we do this via theme, but it's for testing purpose only):

    ```less
    @checkout-tooltip-content__background-color: #fff;
    @checkout-tooltip-content__border-color: #f2f5f7;
    @checkout-tooltip-content__active__border-color: @checkout-tooltip-content__border-color;
    ```
 2. Navigate to checkout and chec the new styles of field tooltips
 3. Set the width to `768px` and check them again:

    Without patch | With patch
    --------------|------------
    ![image](https://user-images.githubusercontent.com/306080/55861030-2f5ad680-5b7e-11e9-9f04-92afa963fd2a.png) | ![image](https://user-images.githubusercontent.com/306080/55861154-75179f00-5b7e-11e9-8cee-9935534421df.png)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-10 12:14 UTC, Karlasa commented
@magento-engcom-team give me test instance

2019-04-10 12:14 UTC, magento-engcom-team commented
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

2019-04-10 12:14 UTC, magento-engcom-team commented
Hi @Karlasa, here is your [new Magento instance](https://pr-22258.instances.magento-community.engineering).
Admin access: [https://pr-22258.instances.magento-community.engineering/admin](https://pr-22258.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-10 12:24 UTC, Karlasa requested changes

2019-04-10 12:24 UTC, Karlasa commented on app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_tooltip.less
> +        border-bottom-color: @checkout-tooltip-content__border-color;
@vovayatsyuk Can you wrap them around .lib-css() ? :)

2019-04-10 13:26 UTC, Karlasa approved these changes
👍

2019-04-10 13:27 UTC, magento-engcom-team commented
Hi @Karlasa, thank you for the review.
[ENGCOM-4722](https://jira.corp.magento.com/browse/ENGCOM-4722) has been created to process this Pull Request

2019-04-12 11:09 UTC, stoleksiy commented
:heavy_check_mark: QA Passed 

**Before:**

![before](https://user-images.githubusercontent.com/44244273/56033160-8a323080-5d2c-11e9-94a2-79b738efcc86.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/56033173-928a6b80-5d2c-11e9-98b1-8a990ae32915.png)

2019-04-15 20:55 UTC, merged