#222249 configurable product images wrong sorting fix
magento/magento2 pull request #22287
Opened 2019-04-11 11:07 UTC by Wirson

Configurable Product Gallery Images Out of Order when More than 10 images. Images sort order does not comply with that in admin panel for configurable product. 

### Description (*)
'position' argument was provided as string, thus result of sorting was like: 1, 10, 11, 2, 3, 4, ... .

### Fixed Issues (if relevant)
1. magento/magento2#22249: Configurable Product Gallery Images Out of Order when More than 10 images

### Manual testing scenarios (*)
1. Exact steps to reproduce are extensively provided in related issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-11 11:07 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22287) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22287) before we can accept your contribution.<br/><hr/>**Mateusz Wira** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-04-11 12:59 UTC, orlangur approved these changes

2019-04-15 09:19 UTC, sivaschenko requested changes
Hi @Wirson , thanks for the pull request! Can you please fix the commit authorship in this pull request ( see comment https://github.com/magento/magento2/pull/22287#issuecomment-482070764 )

2019-04-15 12:18 UTC, orlangur reviewed
Please squash changes into a single commit so that we have perfectly clean history 😉

2019-04-15 12:18 UTC, orlangur requested changes
Please squash changes into a single commit so that we have perfectly clean history 😉

2019-04-29 14:44 UTC, sidolov approved these changes

2019-04-29 14:45 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-4844](https://jira.corp.magento.com/browse/ENGCOM-4844) has been created to process this Pull Request

2019-04-29 14:45 UTC, magento-engcom-team commented
@Wirson thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-04-30 11:18 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-05-01 11:08 UTC, merged