Fixed wishlist issue for out of stock item
magento/magento2 pull request #22289
Opened 2019-04-11 17:18 UTC by saphaljha

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2: Fixed wishlist issue for out of stock item

### Manual testing scenarios (*)

1. Add out of stock item into the wishlist

### Expected result (*)

![expected](https://user-images.githubusercontent.com/23274052/55977218-e143f100-5cab-11e9-81dc-1948de4ec9e4.png)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/23274052/55977242-ed2fb300-5cab-11e9-94a5-293a30580a21.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-12 06:32 UTC, dmytro-ch requested changes
Hi @saphaljha,
thank you for your contribution!

There is an integration test failure:
```
1) Magento\Wishlist\Model\WishlistTest::testGetItemCollectionWithDisabledProduct
Failed asserting that an array is empty.
/home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Wishlist/Model/WishlistTest.php:122
```
Could you please take a look?

Please, also squash all commits into a single commit in order to cleanup the history.

Thank you!

2019-04-20 11:28 UTC, saphaljha commented
Hi @dmytro-ch,

I have checked it and then I decided to remove that code, please have a look.

2019-04-28 04:01 UTC, dmytro-ch requested changes
Hi @saphaljha,
currently, the failing tests indicate that there is some issue in the new logic.
Please make sure the changes don't lead to additional issues for some specific cases by checking the failed tests.
Feel free to update the tests that are based on a wrong behavior of the wishlist feature.

Thank you!

2019-04-28 04:01 UTC, dmytro-ch commented on app/code/Magento/Wishlist/Model/ResourceModel/Item/Collection.php
> -            } else {
I don't think we need to remove this condition.
Most of the tests failures seem to be caused by this change.
E.g.
```
1) Magento\GraphQl\Wishlist\WishlistTest::testGetCustomerWishlist
Magento\Framework\Exception\LocalizedException: Cannot specify product.
```

2019-05-01 13:43 UTC, saphaljha commented on app/code/Magento/Wishlist/Model/ResourceModel/Item/Collection.php
> -            } else {
Hello @dmytro-ch , I'll check and update the code soon.

2019-06-14 14:14 UTC, engcom-dev-Foxtrot commented
@saphaljha issue you described is not reproducible. All works fine. We are closing this PR.

2019-06-14 14:14 UTC, closed without merging