[Backport] Turn on edit mode for product repository when adding children
magento/magento2 pull request #22295
Opened 2019-04-12 04:56 UTC by amol2jcommerce

### Original Pull Request 
 https://github.com/magento/magento2/pull/21083
### Description (*)
This should fix the issue with the configurable products not having any options with Bulk and Async API. The product was being cached and its extension attributes were empty when trying to add children to a product via Bulk API.

### Fixed Issues (if relevant)
1. magento/magento2#20366: The parent product doesn't have configurable product options

### Manual testing scenarios (*)
1. Install Magento 2.3 with RabbitMQ
2. Add Sample data
3. Follow https://devdocs.magento.com/guides/v2.3/rest/tutorials/bulk-configurable-product/config-product-intro.html
4. If this fix is not there, when you do the step to add the product children, an error is produced saying that the product does not contain any configurable options.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-12 09:01 UTC, rogyar requested changes

2019-04-12 09:01 UTC, rogyar commented on app/code/Magento/ConfigurableProduct/Model/LinkManagement.php
> + * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
Hi. Could you explain, please, why do we need `@SuppressWarnings` directive here? I understand that we have it in the original PR. However, we don't introduce a new dependency here and using this directive is a bit doubtful.

2019-04-14 22:45 UTC, orlangur approved these changes
@rogyar I believe this is due to new exception classes added.

2019-04-14 22:46 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4754](https://jira.corp.magento.com/browse/ENGCOM-4754) has been created to process this Pull Request

2019-04-17 06:42 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-04-18 17:11 UTC, merged