Fix negative credit memo total when setting shipping refund to 0 where a shipping discount exists
magento/magento2 pull request #22343
Opened 2019-04-15 10:44 UTC by driskell

### Description (*)
1. In Discount total collector, ensure we check for existence of shipping amount using hasBaseShipping Discount so that we match the same check inside Shipping total collector (https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Creditmemo/Total/Shipping.php#L66)

### Fixed Issues (if relevant)
When an order has a shipping discount applied, if you create credit memo against that order's only invoice, and then set the refund shipping amount to 0, you will end up refunding less than the requested amount because the Shipping Discount is still populated, but the Shipping is 0 - meaning total is reduced by the Shipping Discount. This is because the Shipping total sees the 0 shipping and obeys it. However, the Discount total does a boolean check on shipping amount so sees 0 as the same as not present, and thus leaves the shipping discount present when it should've been removed.

### Manual testing scenarios (*)
1. Create new order with shipping discount applied to a positive value shipping and have it fully invoiced
2. View the invoice and create credit memo, set refund shipping to 0 and verify the totals - they are wrong and less than they should be by a value equivalent to the shipping discount
3. Furthermore, set all item quantities to 0 as if you were refunding shipping only, then set shipping refund to 0, and update totals, instead of grand total 0 you will get a negative total.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-17 14:32 UTC, sivaschenko requested changes
Thanks for the pull request @driskell ! Can you please adjust unit tests according to the changes

2019-05-02 08:41 UTC, driskell commented
Thank you @Nazar65 :)

2019-05-10 07:50 UTC, VasylShvorak commented
Hi @driskell could you provide more detailed steps to reproduce this issue: cart price rule configuration and what exactly we should refund to get negative total?
Thank you.

2019-05-10 08:40 UTC, driskell commented
Hi @VasylShvorak 

Any rule that applies a shipping discount. Try creating a coupon for example that applies £5 discount to everything including the shipping amount. Make sure you place an order that has a shipping cost so it can be discounted (so don't do free shipping.) I've updated instructions below for remainder.

# Create new order with shipping discount applied to a positive value shipping and have it fully invoiced
# View the invoice and create credit memo from that invoice, set refund shipping to 0 and click Update Totals - they are wrong and less than they should be by a value equivalent to the shipping discount
# Furthermore, set all item quantities to 0 as if you were refunding shipping only, then set shipping refund to 0, and update totals, instead of grand total 0 you will get a negative total.

2019-05-10 12:31 UTC, VasylShvorak commented
@driskell  There is manual testing scenario that I follow:
- Create Cart Price rule:
-- Rule Information 
 --- Coupon=Specific Coupon
 --- Coupon Code=test1
-- Actions
--- Apply=Fixed amount discount
--- Discount Amount=3
--- Apply to Shipping Amount=Yes
- Create simple product with price=10$
- Create order with product and applied discount
- Create invoice
- Click "Credit Memo" on order page
- Check Refund Totals
- :x: There is no button Update Totals on 2.3-develop
- Try set any number into Refund Shipping field
**Result:**
 Grand Total is not changed on 2.3-develop branch and PR branch
![#22343PrNotFix](https://user-images.githubusercontent.com/26908019/57526584-74695880-7336-11e9-887a-421f99ebf2b6.png)

2019-05-10 13:02 UTC, driskell commented
@VasylShvorak Something rings a bell about that button - I have it on the original 2.2 we had the issue and I remember we reproduced on 2.3. I'll try to take a look.

What was your shipping cost?

2019-05-10 13:02 UTC, driskell commented
@magento-engcom-team give me 2.3-develop instance

2019-05-10 13:02 UTC, magento-engcom-team commented
Hi @driskell. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-05-10 13:03 UTC, magento-engcom-team commented
Hi @driskell, here is your [Magento instance](https://i-22343-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22343-2-3-develop.instances.magento-community.engineering/admin](https://i-22343-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-05-10 13:13 UTC, VasylShvorak commented
@driskell I used default Flat Rate=5$ as Shipping Methods and Check / Money order as Payment Method

2019-05-10 14:19 UTC, driskell commented
@magento-engcom-team give me 2.2-develop instance

2019-05-10 14:19 UTC, magento-engcom-team commented
Hi @driskell. Thank you for your request. I'm working on Magento 2.2-develop instance for you

2019-05-10 14:20 UTC, magento-engcom-team commented
Hi @driskell, here is your [Magento instance](https://i-22343-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22343-2-2-develop.instances.magento-community.engineering/admin](https://i-22343-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-05-10 14:21 UTC, driskell commented
I can't get the credit memo to appear - likely because it only appears for online payments. I'll need some time to retest this on latest develop and use an online payment method.

2019-06-25 21:54 UTC, sidolov commented
@driskell , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-25 21:54 UTC, closed without merging