Qty box visibility issue in wishlist when product is out of stock
magento/magento2 pull request #22381
Opened 2019-04-17 06:30 UTC by ansari-krish

### Description (*)

Magento 2.3.x
Magento 2.2.x

Qty box should not be displayed in the wishlist if an added product is out of stock.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. Set out of stock product display as a front end from admin configuration by below steps
Stores >> Setting >> Configuration >> Catalog >> Inventory >> Display Out of Stock Products	 set Yes
2. Login as a customer in frontend
3. Add out of stock product into wishlist
4. Review the product in My Wish List section in frontend where qty box is displayed for out of stock product.
![Screenshot from 2019 04 17 11 50 01](https://user-images.githubusercontent.com/43400051/56265739-f7b4d700-6107-11e9-8b82-44bae54be820.png)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-17 06:44 UTC, ihor-sviziev approved these changes

2019-04-17 06:45 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4770](https://jira.corp.magento.com/browse/ENGCOM-4770) has been created to process this Pull Request

2019-04-17 08:11 UTC, stoleksiy commented
:heavy_check_mark: QA Passed 

**Before:**

![before](https://user-images.githubusercontent.com/44244273/56271593-84a86200-6101-11e9-855d-40394bdd116e.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/56271615-8d993380-6101-11e9-8f56-5bce8de080d8.png)

2019-04-17 08:34 UTC, kalpmehta requested changes
Any reason why Qty box should not be displayed if the product is not Saleable? There might be a case when customer want to see how many Qty of the product they added to wishlist, even though the product is out of stock.

2019-04-17 09:49 UTC, ansari-krish commented
Hi @kalpmehta,
Thanks for reviewing.
Yes, There might be a case so customer shows Qty box even though the product is out of stock.
But I have not found any condition related to this. When Product is out of stock than "Add to cart" button is not displayed so I have updated the code on based on that condition. When Product is out of stock then also Qty box is in Editable mode, We should remove it or disabled qty box when product is out of stock.
Please let me know your through. If you need to do any change here.
Thank you.

2019-04-17 18:07 UTC, kalpmehta commented
@magento-engcom-team give me test instance

2019-04-17 18:07 UTC, magento-engcom-team commented
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

2019-04-17 18:08 UTC, magento-engcom-team commented
Hi @kalpmehta, here is your [new Magento instance](https://pr-22381.instances.magento-community.engineering).
Admin access: [https://pr-22381.instances.magento-community.engineering/admin](https://pr-22381.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-17 18:19 UTC, kalpmehta commented
@ansari-krish Yes, can you please disable the Comment and Qty fields as it's anyway not editable when the product is not Saleable? Thanks

2019-04-18 05:35 UTC, ansari-krish commented
> @ansari-krish Yes, can you please disable the Comment and Qty fields as it's anyway not editable when the product is not Saleable? Thanks

Hi @kalpmehta,
I have made changes as per your suggestions, Please review it.
Thanks

2019-04-18 05:35 UTC, kalpmehta commented
@magento-engcom-team give me test instance

2019-04-18 05:35 UTC, magento-engcom-team commented
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

2019-04-18 05:36 UTC, magento-engcom-team commented
Hi @kalpmehta, here is your [new Magento instance](https://pr-22381.instances.magento-community.engineering).
Admin access: [https://pr-22381.instances.magento-community.engineering/admin](https://pr-22381.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-18 06:00 UTC, kalpmehta commented on app/code/Magento/Wishlist/view/frontend/templates/item/column/cart.phtml
> +$allowedQty = $block->getMinMaxQty();
@ansari-krish Do you have to change this code for this PR?

2019-04-18 06:03 UTC, ansari-krish commented on app/code/Magento/Wishlist/view/frontend/templates/item/column/cart.phtml
> +$allowedQty = $block->getMinMaxQty();
No

2019-04-18 06:04 UTC, kalpmehta commented on app/code/Magento/Wishlist/view/frontend/templates/item/column/cart.phtml
> +$allowedQty = $block->getMinMaxQty();
Can you please revert it then? thanks!

2019-04-18 06:15 UTC, ansari-krish commented on app/code/Magento/Wishlist/view/frontend/templates/item/column/cart.phtml
> +$allowedQty = $block->getMinMaxQty();
ok

2019-04-18 06:38 UTC, ansari-krish commented on app/code/Magento/Wishlist/view/frontend/templates/item/column/cart.phtml
> +$allowedQty = $block->getMinMaxQty();
git issue is resolved, Please review now.

2019-04-18 06:39 UTC, kalpmehta approved these changes

2019-04-18 06:40 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-4770](https://jira.corp.magento.com/browse/ENGCOM-4770) has been created to process this Pull Request

2019-04-18 08:41 UTC, stoleksiy commented
:heavy_check_mark: QA Passed 

**Result:**

![after1](https://user-images.githubusercontent.com/44244273/56348214-a4f22280-61ce-11e9-8488-fa3f2813c54c.png)

2019-04-20 17:22 UTC, merged