Patch the prototype pollution vulnerability in jQuery < 3.4.0
magento/magento2 pull request #22418
Opened 2019-04-18 19:40 UTC by DanielRuf

This patches the prototype pollution vulnerability in jQuery < 3.4.0.
See https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/

> Minor vulnerability fix: Object.prototype pollution
> jQuery 3.4.0 includes a fix for some unintended behavior when using jQuery.extend(true, {}, ...). If an unsanitized source object contained an enumerable __proto__ property, it could extend the native Object.prototype. This fix is included in jQuery 3.4.0, but patch diffs exist to patch previous jQuery versions.
> 
> Example
> jQuery.extend(true, {},
>   JSON.parse('{"__proto__": {"test": true}}')
> );
> console.log( "test" in {} ); // true
> Note that while jQuery does its best to protect users from security vulnerabilities, jQuery is a DOM manipulation library that will generally do what you tell it to do. In this case, the behavior was likely unexpected, so jQuery.extend will no longer write any properties named __proto__. But guards such as this one are not replacements for good security practices such as user input sanitization.

Patches: https://github.com/DanielRuf/snyk-js-jquery-174006?files=1

Original report: https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-19 09:00 UTC, orlangur requested changes
@DanielRuf it is not so easy to review a minified file, you know :)

Please provide exact steps so that resulting file can be verified.

2019-04-19 09:40 UTC, DanielRuf commented
Hi,

I have only changed the part directly before `,g!==c&&(j&&c&&(n.isPlainObject(c)`.

The blog article by Snyk contains some examples: https://snyk.io/blog/after-three-years-of-silence-a-new-jquery-prototype-pollution-vulnerability-emerges-once-again/

2019-04-19 09:42 UTC, DanielRuf commented
By using jsbeautify or any other beautifier it should be possible to see the single change.

The patch files are also linked by the jQuery team in their blog post about the 3.4.0 release.

2019-04-19 09:47 UTC, orlangur commented
@DanielRuf thanks, this should work as well. I was thinking of applying UglifyJS or whatever tool you used the same way you did it. I didn't think you edited minified file directly :)

Should we specify additional patch in comment maybe?

2019-04-19 09:53 UTC, DanielRuf commented
> Should we specify additional patch in comment maybe?

Can you specify what you mean?
Changimg the first line in the minified file / add a another header comment?

2019-04-19 10:18 UTC, orlangur commented
Another header comment which would be strippable in production mode (copyright-containing comments are probably not strippable).

2019-04-21 19:05 UTC, DanielRuf commented
> Another header comment which would be strippable in production mode (copyright-containing comments are probably not strippable).

Done. Please review the changes.

2019-04-22 10:15 UTC, orlangur requested changes
@DanielRuf, `/*! ` no exclamation mark in patch comment so that it can be stripped.

Diff LGTM:
```
-                for (d in e) a = g[d], c = e[d], g !== c && (j && c && (n.isPlainObject(c) || (b = n.isArray(c))) ? (b ? (b = !1, f = a && n.isArray(a) ? a : []) : f = a && n.isPlainObject(a) ? a : {}, g[d] = n.extend(j, f, c)) : void 0 !== c && (g[d] = c));
+                for (d in e) a = g[d], c = e[d], d !== "__proto__" && g !== c && (j && c && (n.isPlainObject(c) || (b = n.isArray(c))) ? (b ? (b = !1, f = a && n.isArray(a) ? a : []) : f = a && n.isPlainObject(a) ? a : {}, g[d] = n.extend(j, f, c)) : void 0 !== c && (g[d] = c));
```

Please squash into single commit after last change.

2019-04-22 10:32 UTC, DanielRuf commented
Ok, will change it and squash the commits.

2019-04-22 16:18 UTC, DanielRuf commented
> Ok, I will change it and squash the commits.

Done.

2019-04-23 09:35 UTC, orlangur approved these changes

2019-04-23 09:36 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4804](https://jira.corp.magento.com/browse/ENGCOM-4804) has been created to process this Pull Request

2019-05-02 16:47 UTC, DanielRuf commented
Any update? Would be good to have this fixed and as SUPEE patch or link to my patches at https://github.com/DanielRuf/snyk-js-jquery-174006

2019-05-02 18:54 UTC, orlangur commented
@sdzhepa @stoleksiy @VasylShvorak sorry for pinging directly, could you please proceed with this PR?

2019-05-07 20:36 UTC, sdzhepa commented
Hello 
@DanielRuf @orlangur

Thank you for contribution and collaboration!

During testing I faced an issue.
Could you please have a look and clarifiy is it issue with solution or i should use another case for testing?
At this momet it seems as issues is not fixed

**Manual testing scenario:**
1.  Use Examle of code from the description or from article https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/
```
jQuery.extend(true, {},
  JSON.parse('{"__proto__": {"test": true}}')
);
console.log( "test" in {} ); // true
```
2. Use it in some js file in Magento. 
3. I added it to the "app/code/Magento/Catalog/view/frontend/web/js/product/breadcrumbs.js" file, like
```
define([
    'jquery',
    'Magento_Theme/js/model/breadcrumb-list'
], function ($, breadcrumbList) {
    'use strict';

    return function (widget) {
$.extend(true, {},
        JSON.parse('{"__proto__": {"test": true}}')
    );
    console.log( "test" in {} ); // true

        $.widget('mage.breadcrumbs', widget, {
```

3. Cleared all from "var/*" and "pub/static/frontent"
4. Go to Storefront on any product page and open browser console


**Result on 2.3-develop branch:**  true

**Result on branch with fix:**  The same as on 2.3-develop - true

2019-05-07 20:59 UTC, DanielRuf commented
Hi @sdzhepa,

Would be new for me that the patch would not work. I will check it again tomorrow but the replaced part should be correct.

2019-05-08 04:44 UTC, DanielRuf commented
See https://github.com/DanielRuf/snyk-js-jquery-174006/blob/master/jquery-1.12.4.patch and the minified version, these should be the same.

2019-05-08 18:12 UTC, VladimirZaets commented
@magento-engcom-team give me test instance

2019-05-08 18:13 UTC, magento-engcom-team commented
Hi @VladimirZaets. Thank you for your request. I'm working on Magento instance for you

2019-05-08 18:13 UTC, magento-engcom-team commented
Hi @VladimirZaets, here is your [new Magento instance](https://pr-22418.instances.magento-community.engineering).
Admin access: [https://pr-22418.instances.magento-community.engineering/admin](https://pr-22418.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-05-08 20:24 UTC, sdzhepa commented
Hi @DanielRuf 

I tried to test it one more time with a different approach
and still cannot find any effect of this fix on Magento

1. Tested instance on Magento version based on PR branch (preconditions: Minify JavaScript Files = YES)
![22418_1](https://user-images.githubusercontent.com/3409584/57405514-4522e200-71a4-11e9-946e-d4c82af9a432.jpg)

2. Also, I see these changes in file "lib/web/jquery/jquery.min.js" but in the browser, I cannot find these changes
![22418_2](https://user-images.githubusercontent.com/3409584/57405693-b2367780-71a4-11e9-928c-3e1eb93e1782.jpg)


3. Additionally, I tried to test it on local instance in default/develop/production mode. regenerate static, remove all content from "var/", "pub/static", "genereted" etc

But have the same result, the test script always returns TRUE


Could you please advise where I can find result/usages of this fix?

2019-05-09 04:09 UTC, DanielRuf commented
You can try a jQuery 3.4.0 build on codepen as this contains the exact same change.

2019-05-09 04:10 UTC, DanielRuf commented
Your file does not seem to contain the fix.

2019-05-09 04:11 UTC, DanielRuf commented
Seems this is a different jQuery file, see the comment at the top. https://github.com/DanielRuf/magento2/blob/e0cc1c98ebf326183b1e533df52bc97774df8141/lib/web/jquery/jquery.min.js#L1

2019-05-09 04:16 UTC, DanielRuf commented
https://github.com/magento/magento2/search?utf8=✓&q=includes+sizzle&type=

Wait, why do we have jQuery twice?
I will change the unminified file too.

2019-05-09 04:42 UTC, DanielRuf commented
Ok so https://github.com/magento/magento2/commit/98214d73ce4ab6d873786759c804b9994be82f29 removed the minified file and changed the imports and https://github.com/magento/magento2/commit/ebbcccacf73ac9123201c0a8e3aea47b1388add4 added the minified file again.

Not sure why, also the move out of the jquery was probably not the best idea.

I will patch the other file too.
(Interestingly in our instance the lib/jquery/jquery.min.js file was used so the changes from https://github.com/magento/magento2/commit/98214d73ce4ab6d873786759c804b9994be82f29 changed it only in one or a few placss).

We should discuss this in another issue if we should revert the changes and remove the duplicated file(s).

2019-05-09 04:46 UTC, DanielRuf commented
![Screenshot_20190509-064504](https://user-images.githubusercontent.com/827205/57427853-0b92bb00-7226-11e9-9389-cee33e7ba078.jpg)
Makes not much sense to move only one file imo.
Anyway, I will add the required change to the unminifiee file too.

2019-05-09 06:25 UTC, DanielRuf commented
Now it should work also with the unminified version of jQuery.

@sdzhepa @orlangur

2019-05-11 10:36 UTC, orlangur approved these changes

2019-05-11 10:37 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4804](https://jira.corp.magento.com/browse/ENGCOM-4804) has been created to process this Pull Request

2019-05-15 13:44 UTC, VasylShvorak commented
:heavy_check_mark: QA passed
Before:
![#22418Main](https://user-images.githubusercontent.com/26908019/57780023-0951c480-7730-11e9-84cb-5800c6e01b67.png)
After:
![#22418Pr](https://user-images.githubusercontent.com/26908019/57780043-0fe03c00-7730-11e9-91ed-bc17c13abb19.png)

2019-05-23 12:50 UTC, merged