magento/magento2#22317: PR#22321 fix.
magento/magento2 pull request #22444
Opened 2019-04-21 13:08 UTC by p-bystritsky

### Description (*)

magento/magento2#22321 was merged before it was finished.

### Fixed Issues (if relevant)

1. magento/magento2#22317: CodeSniffer should not mark correctly aligned DocBlock elements as code style violation.

### Manual testing scenarios (*)

1. Edit any Magento 2 class - align method params like shown here.
2. Create two aligned param comments for one method (one of them should be a substring of relevant param name).
3. Run static tests.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-21 21:22 UTC, orlangur requested changes

2019-04-21 21:22 UTC, orlangur commented on dev/tests/static/framework/Magento/Sniffs/Annotation/MethodArgumentsSniff.php
> +        foreach (array_keys($paramDefinitions) as $i) {
`array_keys` is not a good idea. Why cannot use previous implementation? If there are gaps in keys, use `foreach` and ignore values.

2019-04-21 21:22 UTC, orlangur commented on dev/tests/static/framework/Magento/Sniffs/Annotation/MethodArgumentsSniff.php
> +        foreach (array_keys($paramDefinitions) as $i) {
Same for all other changed loops.

2019-04-21 21:22 UTC, orlangur commented
@p-bystritsky next time please mark PR as Draft/WiP until it is intended to be merged.

2019-05-02 11:00 UTC, p-bystritsky commented
@orlangur updated.

2019-05-22 07:42 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-24 10:56 UTC, merged