Fixed #22396 config:set fails with JSON values
magento/magento2 pull request #22513
Opened 2019-04-26 16:18 UTC by shikhamis11

Fixed #22396 config:set fails with JSON values

### Preconditions (*)

1. 2.3.1

### Steps to reproduce (*)

1. Try to set a config value for a config option that uses JSON values via the command line cli
2. i.e.: php bin/magento config:sataloginventory/item_options/min_sale_qty "{"32000":2,"0":2}"

### Expected result (*)

1. Config is set to provided value

### Actual result (*)

1. Config is set to empty value.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-26 21:19 UTC, orlangur requested changes
Please add corresponding test case.

2019-04-28 18:02 UTC, shikhamis11 commented
hi @orlangur , I have updated code for unit test Please review.

2019-04-30 21:28 UTC, sidolov approved these changes

2019-04-30 21:29 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5002](https://jira.corp.magento.com/browse/ENGCOM-5002) has been created to process this Pull Request

2019-05-03 08:19 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-03 09:34 UTC, orlangur requested changes
@shikhamis11 please add a new test case similar to issue reported - containing some JSON.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-05-14 08:35 UTC, Nazar65 commented
Hi @shikhamis11 please look at failed unit test 
```
Too few arguments to function Magento\CatalogInventory\Test\Unit\Helper\MinsaleqtyTest::testGetConfigValue(), 2 passed and at least 4 expected
#0 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(Magento\CatalogInventory\Test\Unit\Helper\MinsaleqtyTest))
#1 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#2 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#3 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#4 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#8 /var/www/html/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#9 {main}
```

2019-05-15 08:52 UTC, Nazar65 commented
@shikhamis11 thank you, can you "squash" commit to one ?

2019-05-15 09:03 UTC, shikhamis11 commented
Yes I will

2019-05-21 07:22 UTC, Nazar65 commented
ping @orlangur

2019-05-22 15:06 UTC, sidolov approved these changes

2019-05-22 15:08 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5002](https://jira.corp.magento.com/browse/ENGCOM-5002) has been created to process this Pull Request

2019-05-24 10:56 UTC, merged