[Bakport] Adding product from wishlist not adding to cart showing warning message.
magento/magento2 pull request #22536
Opened 2019-04-29 05:08 UTC by niravkrish

### Original Pull Request 
https://github.com/magento/magento2/pull/19653

### Description (*)

Adding product from wishlist not adding to cart showing warning message.
### Fixed Issues (if relevant)

1. magento/magento2#9155: Adding product from wishlist not adding to cart showing warning message.

### Manual testing scenarios (*)

1. Add a simple product from admin with Minimum Qty Allowed in Shopping Cart 10
2. Login in front end
3. Add product to wishlist
4. Click on wishlist.
5. Now showing allow qty as default in qty field.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-29 09:57 UTC, dmytro-ch commented
@magento-engcom-team give me test instance

2019-04-29 09:57 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-04-29 09:57 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-22536.instances.magento-community.engineering).
Admin access: [https://pr-22536.instances.magento-community.engineering/admin](https://pr-22536.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-04-29 10:35 UTC, dmytro-ch requested changes
Hi @niravkrish,
the current solution does not seem to be working.
The `\Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart` cannot be instantiated due to the redundant constructor params, and namely `\Magento\Catalog\Model\Product\Image\UrlBuilder` which is not available in Magento 2.2.x version.
Please make sure the changes are working and compatible with Magento 2.2.x before creating a PR.

2019-04-30 12:03 UTC, dmytro-ch requested changes
@niravkrish, could you please squash all commits into a single commit after applying the changes in order to clean up history?
Thank you!

2019-04-30 12:03 UTC, dmytro-ch commented on app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Cart.php
> +        array $data = []
Please keep the same order of parameters as for the parent class.

2019-04-30 12:03 UTC, dmytro-ch commented on app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Cart.php
> +    private $productView;
Please add space between property and method.

2019-04-30 12:03 UTC, dmytro-ch commented on app/code/Magento/Wishlist/Block/Customer/Wishlist/Item/Column/Cart.php
> +use Magento\Catalog\Controller\Adminhtml\Product\Initialization\StockDataFilter;
This import does not seem to be used. Please remove.

2019-04-30 12:25 UTC, dmytro-ch approved these changes

2019-04-30 12:27 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4859](https://jira.corp.magento.com/browse/ENGCOM-4859) has been created to process this Pull Request

2019-05-02 08:38 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-03 10:31 UTC, merged

2019-05-10 16:34 UTC, Rrego6 commented
Hi @niravkrish . Thank you for your contribution.  Unfortunately, we needed to revert this fix for the 2.2.9 release, as it includes BIC into a patch release.