Fix issue with attribute codes
magento/magento2 pull request #22559
Opened 2019-04-30 13:17 UTC by Beagon

Fix an issue with attribute codes where if an attribute code has the same name as a MySQL function (e.g: goup, condition etc.) the indexer returns a MySQL syntax error.

### Description (*)
Fixes an issue where the category flat indexer would throw an MySQL syntax error if an attribute_code was equal to a MySQL function.

E.G: If you have a attribute with a code called "group" the following would occur when the catalog flat data indexer tries to run:
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group IS NOT NULL)' at line 5, query was: UPDATE `catalog_product_flat_1_tmp_indexer` AS `et`
 LEFT JOIN `eav_attribute_option_value` AS `t0` ON t0.option_id = et.group AND t0.store_id = 0
 LEFT JOIN `eav_attribute_option_value` AS `ts` ON ts.option_id = et.group AND ts.store_id = 1
SET `et`.`group_value` = IFNULL(ts.value, t0.value)
WHERE (group IS NOT NULL)`

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)
Before patch:
1. Create attribute with attribute code group.
2. Add attribute to attribute set of products.
3. Run Catalog Flat Data indexer. `php bin/magento indexer:reindex catalog_category_flat`
4. See the error appear.

After patch:
1. Create attribute with attribute code group.
2. Add attribute to attribute set of products.
3. Run Catalog Flat Data indexer. `php bin/magento indexer:reindex catalog_category_flat`
4. Everything should have been successfully rebuilt.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-30 13:26 UTC, orlangur requested changes
Hi @Beagon, please do the following: https://github.com/magento/magento2/pull/22113#issuecomment-486414332

2019-04-30 14:01 UTC, Beagon commented
Hi @orlangur,

I've backported the changes from 2.3-dev.

Greetings,

Robin

2019-04-30 14:16 UTC, orlangur approved these changes
Great @Beagon! 👍 Didn't expect it that fast taking into consideration discussion in previous PR)

2019-04-30 14:17 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-4860](https://jira.corp.magento.com/browse/ENGCOM-4860) has been created to process this Pull Request

2019-05-07 08:17 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-07 21:31 UTC, merged