Fix undefined methods 'addClass' and `removeClass` on a PrototypeJS Element
magento/magento2 pull request #22560
Opened 2019-04-30 15:15 UTC by markvds

### Description
This problem was caused by 5a283e3ff9 and reported in #20843. The mentioned commit adds two lines in `js.phtml` with non existing methods: `panel.addClass(activePanelClass);` and `panel.removeClass(activePanelClass);`. Both methods do not exist in PrototypeJS and should have been `addClassName()` and `removeClassName()` respectively.

The incorrect method names cause a Javascript error 'Uncaught TypeError: panel.addClass is not a function' in the console and prevents the Edit Attribute form from saving.

Enabling the Swatches module, as mentioned in the issue, only solves the issue because it replaces the phtml file with its own file.

### Fixed Issues (if relevant)
1. magento/magento2#20843: Uncaught TypeError: panel.addClass is not a function when Swatches are disabled

### Manual testing scenarios
1. Disable Swatches modules (otherwise, the mentioned phtml file will not be used)
2. In admin, go to Stores > Attributes > Product
3. Click any attribute
4. Try to save the attribute
5. Nothing happens without the code change, but the attribute saves fine with the code change

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-30 15:16 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22560) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22560) before we can accept your contribution.<br/>

2019-04-30 15:28 UTC, orlangur requested changes
@markvds please use `jQuery` equivalents instead.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-04-30 15:51 UTC, markvds commented
@orlangur I cannot imagine that it makes the situation any better; it's all surrounded by PrototypeJS code. I think it would even make readibility worse.

2019-04-30 15:53 UTC, orlangur commented
@markvds we don't need to add any new PrototypeJS-related code. Feel free to refactor any additional occurrences in file with jQuery.

2019-05-01 08:41 UTC, barryvdh commented
@markvds Thank you for your PR.

@orlangur I would keep the bugfix PR as minimal as possible to make it clear what the intent and actual fix of this PR is. Also to make it easier to avoid merge conflicts etc.Refactoring the prototype should happen in a seperate PR imho.

2019-05-01 13:27 UTC, orlangur commented
@barryvdh it will be minimal as I suggested since `jQuery` is already injected.

@markvds please apply necessary changes.

2019-05-01 17:28 UTC, jissereitsma commented
My 50 cents: The proposed fix of @markvds is a bugfix. However, the suggestion of @orlangur would lead to a code enhancement. They are different things. I'm not sure if postponing the bugfix is a good idea, waiting for the code enhancement. On the other hand, I'm not sure how much work the refactoring the jQuery code would be. Just my 50 cents.

2019-05-01 22:04 UTC, orlangur requested changes
Initial code was jQuery-style. There is no need to step back. Please replace all `addClassName/removeClassName`.

2019-05-01 22:04 UTC, orlangur commented on app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml
> +            panel.addClassName(activePanelClass);
```suggestion
            jQuery(panel).addClass(activePanelClass);
```

2019-05-01 22:05 UTC, orlangur requested changes
After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-05-02 05:30 UTC, jissereitsma commented
@orlangur You are awesome

2019-05-02 10:01 UTC, markvds commented
I changed the PR. 

@orlangur I finally get your point. You basically say the method name was correct, but the context was wrong. I assumed the context was right but the method name was wrong. It's just a different view on the situation. Understanding your thoughts helps me in future PRs. Thanks for explaining!

2019-05-02 10:20 UTC, orlangur commented
@markvds yep, sorry for confusion, will try to formulate better next time 🤝

2019-05-02 10:20 UTC, orlangur approved these changes

2019-05-02 10:21 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-5020](https://jira.corp.magento.com/browse/ENGCOM-5020) has been created to process this Pull Request

2019-05-02 10:21 UTC, magento-engcom-team commented
@markvds thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-05-03 12:51 UTC, soleksii commented
:heavy_check_mark: QA Passed 

**Before:**

![before](https://user-images.githubusercontent.com/44244273/57138271-eb44a580-6dba-11e9-9d3d-544ffd0465f6.png)

**After:**
![after](https://user-images.githubusercontent.com/44244273/57138432-51c9c380-6dbb-11e9-88f2-c5f9043fae49.png)

2019-05-10 22:17 UTC, merged