fixed issue #22379 Fetching child products of configurable product only returns salable products
magento/magento2 pull request #22634
Opened 2019-05-04 04:15 UTC by GovindaSharma

fixed issue #22379 Fetching child products of configurable product only returns salable products

### Description (*)
fixed issue #22379 Fetching child products of configurable product only returns salable products

### Fixed Issues (if relevant)

1. magento/magento2 #22379: Fetching child products of configurable product only returns salable products

### Manual testing scenarios (*)

Preconditions (*)
    2.3.1

Steps to reproduce (*)

Fetch child products for configurable product using:
$childProducts = $product->getTypeInstance()->getUsedProducts($product);

Expected result (*)

This should return a collection of all child products of a configurable product

Actual result (*)

 Only child products that have stock status "In Stock" are returned.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 07:55 UTC, ronak2ram approved these changes

2019-05-04 07:57 UTC, magento-engcom-team commented
Hi @ronak2ram, thank you for the review.
[ENGCOM-5050](https://jira.corp.magento.com/browse/ENGCOM-5050) has been created to process this Pull Request

2019-05-06 19:37 UTC, dmytro-ch requested changes
@GovindaSharma, could you please provide some details on how the applied fix for the private method 
`loadUsedProducts` can resolve the mentioned issue #22379?

The `loadUsedProducts` is being called by `getUsedProducts` and `getSalableUsedProducts` **deprecated** methods only.

Also, I'm not sure that we should apply the current fix considering the following changes are added on purpose d9111b0cac5d197962b7a098b7111f62a2c779e9 :

> Please note $salableOnly parameter is used for backward compatibility because of deprecated method getSalableUsedProducts

2019-05-22 14:59 UTC, sidolov commented
@GovindaSharma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-05-22 14:59 UTC, closed without merging