Fixed Issue #22087
magento/magento2 pull request #22646
Opened 2019-05-04 06:06 UTC by Surabhi-Cedcoss

Fixed Issue #22087

### Description (*)
  Products Ordered Report - Not grouped by product 

### Manual testing scenarios (*)
   1. In the Magento 2 admin go to Reports -> Products -> Ordered
   2. Select a date range where you know you have sold products spanning across multiple orders
   3. Select 'Show By' year
   4. Hit refresh

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 10:47 UTC, ronak2ram approved these changes

2019-05-04 10:49 UTC, magento-engcom-team commented
Hi @ronak2ram, thank you for the review.
[ENGCOM-5052](https://jira.corp.magento.com/browse/ENGCOM-5052) has been created to process this Pull Request

2019-05-06 09:21 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

**Before:**

![before](https://user-images.githubusercontent.com/44244273/57216729-5d0a3280-6ff9-11e9-8c49-f0cd7dc4cae5.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/57216740-65fb0400-6ff9-11e9-9876-02bd8b908367.png)

2019-05-20 19:55 UTC, sivaschenko requested changes
Hi @Surabhi-Cedcoss , thanks for the pull request!

Sorry, this changes request was created by mistake.

2019-05-20 20:03 UTC, sivaschenko approved these changes

2019-05-20 20:04 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5052](https://jira.corp.magento.com/browse/ENGCOM-5052) has been created to process this Pull Request

2019-06-03 09:25 UTC, nicholasscottfish commented
Hi @sivaschenko, is this PR still under review. The original issue relates to this PR #22806, what is the reason for the build fail do you know?

2019-06-03 15:16 UTC, sivaschenko commented
Hi @nicholasscottfish The status of the PR can be viewed in the right sidebar under the labels section. It is in progress of delivering to mainline. Please ignore Travis build fail - Travis tests are not used anymore.

2019-06-07 22:15 UTC, merged