Fixes issue #13227
magento/magento2 pull request #22650
Opened 2019-05-04 06:23 UTC by atishgoswami

## Description
Recently Viewed contains wrong product url with category path

This PR will:

- Generate the proper product url

## Fixed Issues (if relevant)

#13227 

## Contribution checklist

- [ ] Pull request has a meaningful description of its purpose
- [ ] All commits are accompanied by meaningful commit messages
- [ ] All new or changed code is covered with unit/integration tests (if applicable)
- [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 06:23 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22650) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22650) before we can accept your contribution.<br/>

2019-05-04 06:24 UTC, atishgoswami commented
@magento-engcom-team give me test instance

2019-05-04 06:25 UTC, magento-engcom-team commented
Hi @atishgoswami. Thank you for your request. I'm working on Magento instance for you

2019-05-04 06:25 UTC, magento-engcom-team commented
Hi @atishgoswami, here is your [new Magento instance](https://pr-22650.instances.magento-community.engineering).
Admin access: [https://pr-22650.instances.magento-community.engineering/admin](https://pr-22650.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-05-05 09:33 UTC, rogyar commented on app/code/Magento/Catalog/Model/Product/Url.php
> +                $filterData[UrlRewrite::METADATA]['category_id']
Hi @atishgoswami. Thank you for your contribution.
That's a very good point. If the corresponding configuration is not enabled, the system should not take into account a category ID

2019-05-05 09:34 UTC, rogyar commented
That's a very good point. If the corresponding configuration is not enabled, the system should not take into account a category ID

2019-05-07 19:24 UTC, atishgoswami commented
Seems like were couple unrelated test that seems to be broken. 
Is there a way to re-trigger the travis build?

2019-05-27 15:55 UTC, rogyar commented
Hi @atishgoswami. Sorry for the delayed answer. I believe the failing integration tests are related to the current PR. The system expects URL to have a category in the path but gets direct URL to the project. We need to adjust the tests correspondingly.

2019-05-28 14:16 UTC, orlangur requested changes
Nice! Your PR already includes my notes from https://github.com/magento/magento2/pull/22322/files#r275178147 :)

Please remove redundant parentheses, adopt existing integration tests and add a new one corresponding to described case.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-05-30 08:44 UTC, atishgoswami commented
Sure will do @rogyar and @orlangur

2019-06-17 21:47 UTC, sidolov approved these changes

2019-06-17 21:50 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5300](https://jira.corp.magento.com/browse/ENGCOM-5300) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-18 07:50 UTC, engcom-Delta commented
:heavy_check_mark: QA Passed

2019-06-26 16:36 UTC, merged