Fix swatches for new product widget
magento/magento2 pull request #22661
Opened 2019-05-04 07:30 UTC by sunnykhatri

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#14134: Swatches not showing on homepage New products widget

### Manual testing scenarios (*)

1. Create a new **Catalog New Products List** widget and call that widget on HomPage
2. Add any of configurable product in widget

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 07:30 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22661) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22661) before we can accept your contribution.<br/>

2019-05-21 06:37 UTC, sunnykhatri commented
@magento-engcom-team Any update on this request?
Thanks

2019-05-30 18:48 UTC, sidolov requested changes
Could you please clarify a few moments regarding the provided solution: 
- Why we need new layout handle instead of using existing renderers listing? 
- Can we reuse existing phtml templates to achive the same behavior?

2019-05-30 18:48 UTC, sidolov commented on app/code/Magento/Catalog/Block/Product/Widget/NewWidget.php
> +        EncoderInterface $urlEncoder = null,
Please, add new dependencies at the end of the method.

2019-06-13 20:30 UTC, sidolov commented
@sunnykhatri , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-13 20:30 UTC, closed without merging