#21811 - Rest-API updating product stock_item deletes downloadable_product_links
magento/magento2 pull request #22663
Opened 2019-05-04 07:46 UTC by sanjay-wagento

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#21811: Rest-API updating product stock_item deletes downloadable_product_links

### Manual testing scenarios (*)

1. Create regular downloadable product, upload downloadable content
2. Update product stock_item values using a PUT call. For example:
Rest Url: DOMAIN_URL/rest/V1/products/240-LV04
Method: PUT
Body: `"product": {"sku": "TESTITEM", "status": "1", "name": "Test Name", "price": "11.99", "type_id": "downloadable", "extension_attributes": {"stock_item": {"manage_stock": false}}}}`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-07 04:51 UTC, sanjay-wagento commented
@magento-team , I have reviewed error but I do not understand. Can you please tell me what is the issue?

2019-08-06 20:14 UTC, slavvka commented
@magento run all tests

2019-08-06 20:18 UTC, slavvka requested changes
Hey @sanjay-wagento, thank you for the fix. Please make changes according to my comment

2019-08-06 20:18 UTC, slavvka commented on app/code/Magento/Downloadable/Model/Link/UpdateHandler.php
> +        if (!empty($links)) {
It makes sense to move this condition one line upper to not get list of existing links

2019-08-06 20:18 UTC, slavvka commented on app/code/Magento/Downloadable/Model/Sample/UpdateHandler.php
> +        if (!empty($samples)) {
The same

2019-08-06 20:18 UTC, slavvka commented
And let's wait for the builds

2019-08-06 22:26 UTC, slavvka commented
Hey @sanjay-wagento please look at the static tests, they are failing. Please ignore Database Compare tests for now. Also we need to have these changes covered with automated tests. I think WebApi is the most suitable

2019-08-08 21:01 UTC, slavvka commented
@magento run Database Compare build

2019-08-21 15:37 UTC, sidolov commented
@sanjay-wagento , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-21 15:37 UTC, closed without merging