Fix - #22196 - 200 Response Code When Exception is Thrown During Bootstrap
magento/magento2 pull request #22666
Opened 2019-05-04 08:02 UTC by abbasalis

### Description (*)

Now the application will throw a 500 error instead of 200 response when it terminates during the bootstrap process. 

So, now the error message will be displayed with the 500 response code.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. Do any code change to throw an error during the bootstrap process. 
2. Refresh the page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 08:02 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22666) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22666) before we can accept your contribution.<br/>

2019-06-07 13:57 UTC, phoenix128 requested changes
Hello @abbasalis ,
thank you for your contribution, would you please check my comments?

2019-06-07 13:57 UTC, phoenix128 commented on lib/internal/Magento/Framework/App/Bootstrap.php
> +     * @var ObjectManagerFactory
Should this be `AppInterface` ?
I would also recommend to change from `$app` to `$application`.

2019-06-25 21:45 UTC, sidolov commented
@abbasalis , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-25 21:45 UTC, closed without merging