Handling Currency Converter API Error Responses
magento/magento2 pull request #22698
Opened 2019-05-04 10:28 UTC by mikebox

### Description (*)
The issue #22468 happened because the Currency Converter API throws the error "API Key is required" with status 400. This particular issue has been already handled and fixed in the pull request #22461 by @hailong.

However, if the API throws different errors, which was not handled in the code and that will end up in throwing **Key Errors** or **Undefined Index Errors** like issue #22468. To avoid this in the future, this pull request has been created.

Now the user will be provided with the original error, instead of unidentified index errors.

### Fixed Issues (if relevant)
1. magento/magento2#22468: Error in pulling currency exchange rates from Currency Converter API

### Manual testing scenarios (*)
1. Set store default currency to CAD, and add CAD and USD as allowed currencies.
2. Navigate to Stores -> Currency Rates
3. Select Currency Converter API as Import Service and click Import.
4. It will throw the actual error "API Key is required" instead of an unhandled exception.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 10:28 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22698) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22698) before we can accept your contribution.<br/>

2019-05-24 20:18 UTC, sidolov requested changes

2019-05-24 20:18 UTC, sidolov commented on app/code/Magento/Directory/Model/Currency/Import/CurrencyConverterApi.php
> +                    } elseif (array_key_exists('error', $response) && $response['error']) {
Please, simplify the expression to `!empty($response['error'])`

2019-06-07 21:33 UTC, sidolov approved these changes

2019-06-07 21:33 UTC, sidolov commented
Hi @mikebox  , please, sign CLA, otherwise, we can't process your pull request

2019-06-19 16:08 UTC, sidolov requested changes
Please, cover changes by automated unit tests

2019-07-05 18:45 UTC, sidolov commented
@mikebox , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-07-05 18:45 UTC, closed without merging