fixed issue #7299 V1/carts/mine/billing-address returning %fieldName is a required field.
magento/magento2 pull request #22697
Opened 2019-05-04 10:24 UTC by GovindaSharma

fixed issue #7299 V1/carts/mine/billing-address returning %fieldName is a required field.

### Description (*)
fixed issue #7299 V1/carts/mine/billing-address returning %fieldName is a required field.

### Fixed Issues (if relevant)
fixed issue #7299 V1/carts/mine/billing-address returning %fieldName is a required field.

1. magento/magento2#7299: fixed issue #7299 V1/carts/mine/billing-address returning %fieldName is a required field.

### Manual testing scenarios (*)

Preconditions

   Magento EE 2.1.1
   PHP 7.0.12
   Mysql Ver 14.14 Distrib 5.6.33-79.0, for Linux (x86_64) using 6.2

Steps to reproduce

 Go to the checkout after adding something to the basket
Send a request to the REST endpoint V1/carts/mine/billing-address using the payload below

{"cartId":"190488","address":{"countryId":"GB","regionId":"0","region":"","street":["54 Carnegie Court",""],"company":"","telephone":"0165 4569 8754","fax":"","postcode":"AB1C 2DF","city":"SomeCity","firstname":"Bob","lastname":"White","save_in_address_book":1,"saveInAddressBook":null}}

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-13 16:03 UTC, gakonhd commented
@magento-engcom-team hello, is there any progress on this issue yet ?

2019-05-23 18:51 UTC, sdzhepa commented
@magento-engcom-team give me test instance

2019-05-23 18:51 UTC, magento-engcom-team commented
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

2019-05-23 18:52 UTC, magento-engcom-team commented
Hi @sdzhepa, here is your [new Magento instance](https://pr-22697.instances.magento-community.engineering).
Admin access: [https://pr-22697.instances.magento-community.engineering/admin](https://pr-22697.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-08-06 20:30 UTC, slavvka commented
@magento run all tests

2019-08-07 19:17 UTC, slavvka commented
Hey @GovindaSharma please fix the failing tests - Functional and WebAPI. YOu can ignore Database Compare. Also we need to have all fixes covered with automated tests. WebAPI is appropriate here

2019-08-08 21:03 UTC, slavvka commented
@magento run Database Compare build

2019-08-13 20:59 UTC, sidolov requested changes

2019-08-13 20:59 UTC, sidolov commented on app/code/Magento/Quote/Api/BillingAddressManagementInterface.php
> +     * @param string $cartId The cart ID.
Cart id should be int instead of string.

2019-08-21 17:17 UTC, sidolov commented
@GovindaSharma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-21 17:17 UTC, closed without merging