Property "children" does not have setter in class CategoryInterface #10088
magento/magento2 pull request #22710
Opened 2019-05-04 10:53 UTC by devamitbera

##10088

2019-05-24 20:26 UTC, sidolov submitted a review, later dismissed

2019-05-24 20:26 UTC, sidolov commented on app/code/Magento/Catalog/Api/Data/CategoryInterface.php
> +    public function setChildren($children);
Unfortunately, we are not able to add new methods to the existing interfaces marked as api according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-05-24 20:27 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5163](https://jira.corp.magento.com/browse/ENGCOM-5163) has been created to process this Pull Request

2019-05-24 20:27 UTC, sidolov requested changes
PR contains breaking changes

2019-06-05 07:53 UTC, devamitbera commented
@magento-engcom-team,do you need anything else from my end?

2019-06-07 21:35 UTC, sidolov commented
@devamitbera , please, take a look at review comment.

2019-06-25 21:51 UTC, sidolov commented
@devamitbera , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-25 21:51 UTC, closed without merging

2019-07-19 15:06 UTC, devamitbera commented
@sidolov 

Sorry, I was very.

I wish to continue to work with this issue.

Assigning myself again.