Fix for sitemap directory folder path
magento/magento2 pull request #22715
Opened 2019-05-04 11:07 UTC by limajasachin

Fix for sitemap directory folder path

### Description (*)
changed the directory path to 'pub/' folder for saving sitemap.xml and will be accessible using browser.

### Fixed Issues (if relevant)
1. magento/magento2 #1146: A few issues when you use /pub as DocumentRoot

### Manual testing scenarios (*)

1. Make sure the Magento docroot is set to the pub directory
2. In the backend, go to Marketing => Site Map
3. Click 'Add Sitemap' (small inconsistency between, no space here)
4. Enter 'sitemap.xml' into the Filename field, enter '/' into the Path field
5. Click 'Save & generate'.

Problem: sitemap.xml is created in the pub directory, but the column 'Link for Google' now says: http://example.com/pub/sitemap.xml, which is also incorrect

In this case a solution with a redirect/rewrite in the .htaccess/nginx config file isn't really possible as the path and filename of the sitemap are dynamic.

Solution: with given fix we have made sure that only sitemap.xml in pub folder is accessible directly or nested folder in pub as mentioned in sitemap path while generating from admin.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 11:07 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22715) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22715) before we can accept your contribution.<br/><hr/>**Sachin Limaja** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-05-04 17:32 UTC, Nazar65 commented
Hi @limajasachin but we still have issue with scheduled generated sitemap. Wondering if this fix will be proper with two ways of generating sitemap, schedule and manual

2019-05-08 06:49 UTC, limajasachin commented
Hello,

There is some memory issue giving below error while Travis CI build for php version 7.2

Fatal error: Uncaught PHPUnit\Framework\Exception: Warning: exec(): Unable to fork

Please look into this.

Thanks.

2019-05-08 11:32 UTC, sivaschenko requested changes
Hi @limajasachin thanks for the pull request!

Please ignore the Travis build error, I believe it is not related to the pull request.

It is not clear to me how change of `clearSiteMap` function affects the sitemap generation path and location (issue https://github.com/magento/magento2/issues/1146 description).

Can you please describe how the fix works?

2019-05-08 12:52 UTC, limajasachin commented
Hi @sivaschenko 

This fix always generates sitemap.xml file in "pub/" directory respective to path mentioned in admin configuration. For path "/" it will generate sitemap.xml in "pub/" directory and for custom path like "/web1/" it will generate xml file in "pub/web1/" directory.

As well as path displayed in admin sitemap grid is also generated correctly.
This makes listed path correct for admin user as well.

Thanks.

2019-05-29 21:25 UTC, sivaschenko commented
Hi @limajasachin sorry for late reply and thanks for your patience!

As I can see from the code the directory that was changed is used only for deleting of the file, not for the new file generation. Am I missing anything?

2019-06-25 21:56 UTC, sidolov commented
@limajasachin , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-04 09:11 UTC, josefbehr commented
@limajasachin what is the progress/status on this? You re-opened 7 days ago, but I see no new changes

2019-09-06 16:57 UTC, VladimirZaets commented
@limajasachin , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-09-06 16:57 UTC, closed without merging