Prevent future date in Customer DOB field
magento/magento2 pull request #22722
Opened 2019-05-04 11:17 UTC by vishal-7037

### Description (*)

Prevented future date in Customer DOB field at admin panel

### Fixed Issues (if relevant)

1. magento/magento2#22692: Add New Customer from admin panel - DOB field validation missing for future dates

### Manual testing scenarios (*)

1. Go to magento Admin panel
2. Go to Customer > All customers and Add new customer
3. Add required field values
4. Add Future date as DOB and save customer.

**After Fixed:** 

![magento_datepicker](https://user-images.githubusercontent.com/38535982/57178345-34b0f580-6e8c-11e9-81ec-7ea6a7cc8fe0.jpg)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-04 12:04 UTC, vishal-7037 commented
@magento-engcom-team give me test instance

2019-05-04 12:05 UTC, magento-engcom-team commented
Hi @vishal-7037. Thank you for your request. I'm working on Magento instance for you

2019-05-04 12:06 UTC, magento-engcom-team commented
Hi @vishal-7037, here is your [new Magento instance](https://pr-22722.instances.magento-community.engineering).
Admin access: [https://pr-22722.instances.magento-community.engineering/admin](https://pr-22722.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-05-04 12:29 UTC, vishal-7037 commented
I've tested this changes On Vanilla Magento 2.3 instance  and seems working fine.

![Vanilla_Customer_Dob](https://user-images.githubusercontent.com/38535982/57178984-44cdd280-6e96-11e9-977b-cfa408bf879f.jpg)

Thanks

2019-05-05 18:27 UTC, ronak2ram commented on app/code/Magento/Customer/view/base/ui_component/customer_form.xml
> +
Hi @vishal-7037 
Please remove the extra added line.

2019-05-06 04:16 UTC, vishal-7037 commented
Hi @ronak2ram,

I've committed suggested changes Please review and let me know.

Thanks.

2019-05-06 05:28 UTC, ronak2ram commented
Hi @vishal-7037 
Thanks for the update.

2019-05-06 05:29 UTC, ronak2ram approved these changes

2019-05-06 05:30 UTC, magento-engcom-team commented
Hi @ronak2ram, thank you for the review.
[ENGCOM-5065](https://jira.corp.magento.com/browse/ENGCOM-5065) has been created to process this Pull Request

2019-05-07 12:32 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

**Before:**

![before](https://user-images.githubusercontent.com/44244273/57299456-489f6600-70dd-11e9-8e7e-4e554a01e63c.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/57299469-4fc67400-70dd-11e9-91ad-616497fc9275.png)

2019-05-07 13:47 UTC, Nazar65 commented
Hi @vishal-7037 thank you for you pull request, this is wrong fix, because integration test fails, can you please refactor as in this example. thank you.
![DeepinScreenshot_select-area_20190507164602](https://user-images.githubusercontent.com/2481206/57304313-c2d4e800-70e7-11e9-8384-81469120bc7c.png)

2019-05-07 17:55 UTC, vishal-7037 commented
Hi @Nazar65,

I've updated suggested changes and committed my changes. Please review it and let me know.

Thanks! :)

2019-06-07 22:27 UTC, VladimirZaets commented on app/code/Magento/Customer/view/base/ui_component/customer_form.xml
> +                            <option name="maxDate" xsi:type="string">new Date()</option>
Hi, @vishal-7037. Thanks for collaboration. XML declaration shouldn't contain any code that must be executed.   If we really need it, you can do it in the javascript class related to this component.

2019-06-07 22:28 UTC, VladimirZaets requested changes
Hi, @vishal-7037. Please make changes according to review.

2019-06-26 15:31 UTC, VladimirZaets commented
@vishal-7037 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-06-26 15:31 UTC, closed without merging