Fixed issue  #22409 Configurable products are shown on Select Associated Product modal
magento/magento2 pull request #22725
Opened 2019-05-04 11:37 UTC by mallikaverma

Fixed issue  #22409 Configurable products are shown on Select Associated Product modal

### Description (*)
Fixed issue  #22409 Configurable products are shown on Select Associated Product modal

### Fixed Issues (if relevant)
Fixed issue  #22409 Configurable products are shown on Select Associated Product modal

1. magento/magento2#22409: Configurable products are shown on Select Associated Product modal

### Manual testing scenarios (*)
1.Create a configurable product Test 1 with 2 child products (color = red and color = black for the example)
2. Create a new simple product Test 2 with color = red
3. Open the last created product Test 2 in admin panel and convert it to configurable by adding child products (color = green, color = grey), do not change the value for color attribute while you edit product
4. Open the first configurable product Test 1, remove the child product with color = red, click on 'Add products manually' link in Configurations section

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-06-02 09:47 UTC, davidverholen requested changes

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +    protected $productData;
should be private

also the naming seems off (product data vs. product factory)

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +    protected $collection;
already exists in the parent class
There seems to be no reason to override it here

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +    protected $addFieldStrategies;
already exists in the parent class
There seems to be no reason to override it here

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +    protected $addFilterStrategies;
already exists in the parent class
There seems to be no reason to override it here

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +     * @var StoreInterface
import for StoreInterface is missing (getting undefined class warning)

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +        $this->_configurableType = $configurableType;
this class property does dot exist (field declared dynamically warning)

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +        $this->locator = $locator;
this class property does dot exist (field declared dynamically warning)

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +        $this->request = $request;
this class property does dot exist (field declared dynamically warning)

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +        $this->storeRepository = $storeRepository;
this class property does dot exist (field declared dynamically warning)

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +    protected function _getProduct()
method should be marked private (see [health index details ](https://testing-service.magento-community.engineering/reports/magento/magento2/pull/22725/44f04ea5-239e-437f-858c-906c984910ff/4115/MagentoHealthIndex/report.html)check) and not prefixed with an underscore

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Associated/AssociatedDataProvider.php
> +    protected function getStore()
method should be marked private
(https://testing-service.magento-community.engineering/reports/magento/magento2/pull/22725/44f04ea5-239e-437f-858c-906c984910ff/4115/MagentoHealthIndex/report.html)

2019-06-02 09:47 UTC, davidverholen commented on app/code/Magento/Catalog/Model/Product/Type.php
>      const TYPE_BUNDLE = 'bundle';
these type constants do already exist and should be reused from there
for example: \Magento\Bundle\Model\Product\Type::TYPE_CODE

2019-06-17 21:45 UTC, sidolov commented
@mallikaverma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-17 21:45 UTC, closed without merging