Sku uniqueness
magento/magento2 pull request #22746
Opened 2019-05-06 09:27 UTC by dmanners

This is a migration of the PR https://github.com/magento-engcom/import-export-improvements/pull/119 from the now closed import-export-improvements repo.

Originally by @federivo and @pogster 

**Description**

This PR may replace #102.
In contrast to the original PR I restored the SKU autogeneration in case a product is duplicated. The product copier will copy the original SKU and save the duplicate in a loop until a unique url key is found - if no SKU is autogenerated and no valid SKU is supplied it simply won't save the product.

Since the copier sets "isDuplicate" = true I thought it would be good simple solution to check for that entry before autogenerating a SKU.

**Fixed Issues (if relevant)**

https://github.com/magento-engcom/import-export-improvements/issues/101

**Manual testing scenarios**

- Create product with sku "TEST"
- Create another product with sku "TEST"
- You should receive an error saying that the sku already exists instead of getting your sku modified.
- "Save & Duplicate" the product with sku "TEST"
- The duplicate receives the SKU "TEST-1" and will already be saved.

**Contribution checklist**
- [ ]   Pull request has a meaningful description of its purpose
- [ ]   All commits are accompanied by meaningful commit messages
- [ ]   All new or changed code is covered with unit/integration tests (if applicable)
- [ ]   All automated tests passed successfully (all builds on Travis CI are green)

2019-06-11 18:35 UTC, okorshenko commented
@magento run all tests

2020-03-03 17:52 UTC, ihor-sviziev commented
@magento run all tests

2020-03-03 18:37 UTC, ihor-sviziev commented
@magento run all tests

2020-03-03 19:08 UTC, ihor-sviziev commented
As we discussed with @sidolov in slack - there were some issues, so I’ll move in from on hold to review it again

2020-03-04 09:37 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

2020-03-04 09:49 UTC, ihor-sviziev commented
@magento run Static Tests

2020-03-19 09:18 UTC, ihor-sviziev requested changes
Hi @dmanners,
Sorry that we didn't processed your PR so much time!

I see that on this PR we have too many test failures it means that your changes breaks functionality. Could you do following?
1. review test failures and update your PR accordingly
2. Revert permissions changes on files you've changed
3. Sign Adobe CLA

Thank you so much for your contribution!

2020-04-06 06:23 UTC, ihor-sviziev commented
@dmanners will you be able to update your PR based on feedback above?

2020-04-07 06:51 UTC, dmanners commented
sure @ihor-sviziev either this week or next week I will get around to this.

2020-05-04 06:01 UTC, ihor-sviziev commented
Hi @dmanners,
I see tests still failing after you pushed your last changes. Please check it again

2020-05-18 12:10 UTC, ihor-sviziev commented
Hi @dmanners,
Will you be able to update your PR?

2020-05-19 06:31 UTC, dmanners commented
Hi @ihor-sviziev sadly I have not been able to find the time to work on this.

2020-05-25 11:16 UTC, ihor-sviziev commented
Hi @dmanners,
I am closing this PR now due to inactivity.
Please reopen and update your PR if you wish to continue.
Thank you for the collaboration!

2020-05-25 11:16 UTC, closed without merging