MFTF: Update price column in checkout
magento/magento2 pull request #22815
Opened 2019-05-10 08:36 UTC by magicsunday

### Description (*)
In order to MFTF test the calculated shipping method price, its required to access the desired table price column. This requires the column to contain a identifier.

### Manual testing scenarios (*)
1. See price column in checkout shipping methods table
2. Should contain now a id-attribute

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-11 10:39 UTC, orlangur requested changes
Functional tests must not rely on HTML ID, see [Code Demarcation Standard](https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-demarcation.html). Please add appropriate data attributes instead.

2019-05-13 07:16 UTC, magicsunday commented
I changed it, please take a look at it again.

2019-05-29 19:54 UTC, orlangur requested changes

2019-05-29 19:54 UTC, orlangur commented on app/code/Magento/Checkout/view/frontend/web/template/shipping-address/shipping-method-item.html
> +             'data-table-column': 'label_carrier_' + method.method_code + '_' + method.carrier_code"
Why do we need to duplicate it in both TDs?

`<tr data-container-for="shipping-method"` and using existing `ko-value="method.carrier_code + '_' + method.method_code"` should be sufficient.

2019-06-07 07:44 UTC, closed without merging