Fixed #22774 Can't update totals for credit note
magento/magento2 pull request #22813
Opened 2019-05-10 07:05 UTC by gauravagarwal1001

Fixed #22774 Can't update totals for credit note
### Preconditions (*)
1. Magento Open Source 2.3.1

### Steps to reproduce (*)
1. Select an invoice
2. Click "Credit Memo"
3. Add value to `Refund Shipping `, `Adjustment Refund` or `Adjustment Fee` field

### Expected result
1. Should be able to update totals using the "Update Totals" button

![M2 2 8](https://user-images.githubusercontent.com/2035088/57310996-ba2de300-70e2-11e9-938f-8dcf8c2174e9.png)

### Actual result
1. There is no way to update the total (without changing the quantity and then changing it back again)

![M2 3 1](https://user-images.githubusercontent.com/2035088/57311003-bef29700-70e2-11e9-8848-5ed613305810.png)

2019-05-12 09:15 UTC, swnsma commented
Hi @guarinogabriel,
Thank you for your contribution!

As I can see, you are trying to add changes which had been done in 2.2-develop with commit 451f7b9f317db5a27d3d9c541cc3c1678cc169f5 in scope of issue #11798 and these changes were not Forwardported to 2.3-develop.

May I ask you to create PR with all changes from the 451f7b9f317db5a27d3d9c541cc3c1678cc169f5 ?

2019-05-12 09:17 UTC, swnsma requested changes
Hi @guarinogabriel,
Thank you for your contribution!

As I can see, you are trying to add changes which had been done in 2.2-develop with commit 451f7b9 in scope of issue #11798 and these changes were not Forwardported to 2.3-develop.

May I ask you to create PR with all changes from the 451f7b9 ?

2019-05-12 19:34 UTC, gauravagarwal1001 commented
Hi @swnsma,
I updated all changes of commit 451f7b9.

2019-05-13 18:05 UTC, swnsma requested changes
Hi @gauravagarwal1001 
Thank you for your changes.

Could you please:
1) Dismiss remove of such amount empty lines
2) Check and adjust changes according to static tests build fail.
3) Check and adjust failed functional tests.

2019-05-13 18:05 UTC, swnsma commented on app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/Create/Adjustments.php
> -
Can we avoid such changes?

2019-05-13 18:05 UTC, swnsma commented on app/code/Magento/Sales/view/adminhtml/templates/order/creditmemo/create/totals/adjustments.phtml
> -
Can we avoid such changes?

2019-05-14 05:55 UTC, gauravagarwal1001 commented on app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/Create/Adjustments.php
> -
Sure I removed empty lines.

2019-05-14 05:55 UTC, gauravagarwal1001 commented on app/code/Magento/Sales/view/adminhtml/templates/order/creditmemo/create/totals/adjustments.phtml
> -
Sure I removed empty lines

2019-05-14 09:43 UTC, gauravagarwal1001 commented on app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/Create/Adjustments.php
> -
There must be one blank line after the namespace declaration.

2019-06-04 16:43 UTC, swnsma commented
@gauravagarwal1001,  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-04 16:43 UTC, closed without merging