[Shipping] Adjusting the Contact Us Xpath
magento/magento2 pull request #22823
Opened 2019-05-10 16:39 UTC by eduard13

### Description (*)
This PR adjusts the Xpath for the contact us on shipping details block, as result we should see the contact us link in the tracking information, if the shipping carrier won't be available.

### Fixed Issues (if relevant)
1. magento/magento2#22822: [Shipping] The contact us link isn't showing on order tracking page
2. ...

### Manual testing scenarios (*)
1. Make sure you have enabled the **Contact Us**
`Stores / Configuration / Contacts [General] / Contact Us`
2. Create a new order
3. Create a shipment for the order
3.1 Add the Tracking Number by using **USPS** carrier
4. Click on the _Track Order_ link (from Order page)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-11 09:46 UTC, orlangur requested changes
After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-05-12 08:41 UTC, eduard13 commented
@orlangur thank you, the commits were squashed into a single commit.

2019-05-13 10:23 UTC, dmytro-ch approved these changes

2019-05-13 10:24 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5110](https://jira.corp.magento.com/browse/ENGCOM-5110) has been created to process this Pull Request

2019-05-13 10:25 UTC, dmytro-ch requested changes
Hi @eduard13, could you please also fix the static test failures?

2019-05-13 11:41 UTC, dmytro-ch approved these changes

2019-05-13 11:42 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5110](https://jira.corp.magento.com/browse/ENGCOM-5110) has been created to process this Pull Request

2019-05-14 08:08 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

**Before:**

![before](https://user-images.githubusercontent.com/44244273/57681542-93b6fd00-7638-11e9-83cc-68c871437758.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/57681562-9ade0b00-7638-11e9-8763-5df67cece668.png)

2019-05-22 23:33 UTC, orlangur approved these changes

2019-05-22 23:34 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-5110](https://jira.corp.magento.com/browse/ENGCOM-5110) has been created to process this Pull Request

2019-05-23 19:32 UTC, merged