Customer Account Forgot Password page title fix
magento/magento2 pull request #22821
Opened 2019-05-10 16:15 UTC by textarea

Missing question mark in Customer Account Forgot Password page title, because of this it was missing the translated string.

2019-05-11 10:31 UTC, orlangur requested changes
Please squash changes into a single commit so that we have perfectly clean history 😉

2019-05-11 20:18 UTC, textarea commented
@orlangur please tell me how to do it

2019-05-29 18:39 UTC, sidolov approved these changes

2019-05-29 18:40 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5185](https://jira.corp.magento.com/browse/ENGCOM-5185) has been created to process this Pull Request

2019-05-30 10:24 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-06-03 22:52 UTC, merged