Fixed #22808 php bin/magento catalog:image:resize error if image is missing
magento/magento2 pull request #22847
Opened 2019-05-12 19:16 UTC by amitcedcoss

Fixed #22808 php bin/magento catalog:image:resize error if image is missing

### Preconditions (*)
1. Magento 2.3.1 

### Steps to reproduce (*)
1. Delete manually a product image from pub/media/catalog folder 
2. Execute catalog:image:resize 

### Expected result (*)
1. The system creates the resized images for all products that the images exist and lists the errors.

### Actual result (*)
1. The execution halts immediately at the first missing image. 

![image](https://user-images.githubusercontent.com/20220341/57453750-d7dc8300-726f-11e9-9a9b-f40b3784830c.png)

This doesn't affect on the fly generation of images when browsing the products but it's good to be able to execute and test.

2019-05-13 10:02 UTC, dmytro-ch requested changes
Hi @amitcedcoss,
could you please check and fix the static test failures?

2019-05-13 10:02 UTC, dmytro-ch commented on app/code/Magento/MediaStorage/Service/ImageResize.php
> +            throw new \Exception(PHP_EOL.__("These files does not exists.").PHP_EOL . implode(PHP_EOL, $notFoundImages) );
Please change the text to `'The following files do not exist:'` and add it to the translation file `app/code/Magento/MediaStorage/i18n/en_US.csv`.

2019-05-24 07:04 UTC, amitvishvakarma commented on app/code/Magento/MediaStorage/Service/ImageResize.php
> +            throw new \Exception(PHP_EOL.__("These files does not exists.").PHP_EOL . implode(PHP_EOL, $notFoundImages) );
I had made all changes as you had requested so please check now

2019-05-24 13:47 UTC, dmytro-ch commented
@amitvishvakarma, please note, the tests still fail.
Once the issues are fixed applied, please squash all commits into a single one in order to clean up history.

2019-05-24 14:57 UTC, dmytro-ch commented
Please note, the current PR is on hold.
There is also another solution available. #23005

Thank you!

2019-06-19 13:04 UTC, closed without merging