Fix/inconsistent test names
magento/magento2 pull request #22853
Opened 2019-05-12 21:06 UTC by lbajsarowicz

### Description (*)
Extracted the Tests that were coupled several in one file to separate files.

### Fixed Issues (if relevant)
Not applicable

### Manual testing scenarios (*)
1. `vendor/bin/mftf generate:tests`
2. Enjoy!

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-14 11:46 UTC, peterlohaus commented
@magento-engcom-team give me 2.3-develop instance

2019-05-14 11:46 UTC, magento-engcom-team commented
Hi @peterlohaus. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-05-14 11:47 UTC, magento-engcom-team commented
Hi @peterlohaus, here is your [Magento instance](https://i-22853-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22853-2-3-develop.instances.magento-community.engineering/admin](https://i-22853-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-05-27 13:44 UTC, dmytro-ch commented
Hi @lbajsarowicz,
thank you for your contribution!

Please note, the improvements for MFTF should be provided in the scope of [magento/magento/magento-functional-tests-migration](https://github.com/magento/magento/magento-functional-tests-migration/) repository.
Could you please move the current pull request to the MFTF project?

The current pull request will be closed.

CC: @okolesnyk

2019-05-27 13:51 UTC, lbajsarowicz commented
IMHO This is change to tests coupled with modules, not MFTF itself. If it was related with Testing Framework, I would apply changes to MFTF repository.

2019-06-04 21:23 UTC, okolesnyk approved these changes

2019-06-04 21:46 UTC, okolesnyk commented
Hi @dmytro-ch

Currently we require to move PRs to [magento/magento-functional-tests-migration](https://github.com/magento/magento-functional-tests-migration/) only if they are related to MTF tests conversion.

Changes related to existing MFTF test should go to [magento/magento2](https://github.com/magento/magento2) repo.

2019-06-11 09:50 UTC, lbajsarowicz commented
@okolesnyk Rebased to latest 2.3-develop

2019-06-12 11:50 UTC, dmytro-ch commented
Hi @okolesnyk, thank you for the details! :)

2019-06-12 11:51 UTC, dmytro-ch approved these changes

2019-06-12 11:52 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5268](https://jira.corp.magento.com/browse/ENGCOM-5268) has been created to process this Pull Request

2019-06-12 13:25 UTC, stoleksiy commented
QA not applicable

2019-07-16 14:55 UTC, sivaschenko requested changes
Hi @lbajsarowicz thanks for the pull request, can you please check if you can resolve the issue with one of the tests. 

`Magento\FunctionalTestingFramework.functional.VerifyDefaultControlsOnProductShortDescription` is failing on this pull request.

`Failed asserting that an array is not empty.` error is thrown on step `see element "//div[@id='editorproduct_form_short_description']//span[text()='Paragraph']"`

Here is a screenshot taken by the MFTF:
![image](https://user-images.githubusercontent.com/2028541/61304852-b6ed5c80-a7e1-11e9-85ff-b94de2888c30.png)

2019-07-16 16:35 UTC, lbajsarowicz commented
Sure, I can. I will do some investigation why it happened.

2019-07-18 21:31 UTC, lbajsarowicz commented
Looks like previously this test wasn't even detected by MFTF, after extracting that to separate file, it was ran and... failed even when it was wrong before my changes. I'm merging `2.3-develop` for 4th time now, to solve the conflicts and then fix the issue :-)

2019-07-21 21:34 UTC, sivaschenko approved these changes

2019-07-21 21:35 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5268](https://jira.corp.magento.com/browse/ENGCOM-5268) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-07-21 21:47 UTC, lbajsarowicz commented
Btw. @sivaschenko -  Should be the single blank line at the end of XML files? For PHP it's defined by PSR, but how about XMLs?

2019-07-22 08:40 UTC, engcom-Alfa commented
QA not applicable

2019-07-24 16:55 UTC, sivaschenko commented
@lbajsarowicz I think it's not required for the XML file to end with a blank line

2019-07-25 12:28 UTC, sivaschenko requested changes
Hey @lbajsarowicz the `Magento\FunctionalTestingFramework.functional.VerifyDefaultControlsOnProductShortDescription` is still failing

2019-07-25 12:54 UTC, lbajsarowicz commented
@sivaschenko do you mean that this is failing:
![Screenshot_20190725-145212~2](https://user-images.githubusercontent.com/1639941/61875998-1fc48b00-aeec-11e9-887c-856abab460c5.jpg)

2019-07-26 07:38 UTC, engcom-Foxtrot commented
"On Hold" until Page Builder fix is merged.

2019-07-26 10:42 UTC, sivaschenko commented
The issue is fixed on PB side https://github.com/magento/magento2-page-builder/pull/273 we’ll merge those 2 PRs synchronously

2019-07-26 12:38 UTC, lbajsarowicz commented
@sivaschenko This will cause conflicts. Let me know when you'll merge above mentioned issue, I'll fix it once again.

2019-07-26 13:57 UTC, sivaschenko commented
@lbajsarowicz can you share more details about the conflict. You can fix it straight away as we are going to merge your pr and pr to pagebuilder synchronously

2019-11-15 10:46 UTC, sivaschenko requested changes
Hi @lbajsarowicz can you please update the branch. Thank you!

2019-11-28 10:07 UTC, lbajsarowicz commented
That cannot succeed.
Need to close that ticket and create separate for each module to get this merged.

2019-11-28 10:07 UTC, closed without merging