fix date calculation for report's years interval
magento/magento2 pull request #22868
Opened 2019-05-13 14:04 UTC by polkan-msk

Date->diff returns amount of full years between dates, so when
dateStart = 2018-12-25 and dateEnd = 2019-01-25
$dateStart->diff($dateEnd)->y will be 0, that does not match the code's
logic which expects 1 when year 'from' is not eq to year 'to'

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-13 14:04 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22868) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22868) before we can accept your contribution.<br/><hr/>**Viacheslav Kolosov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-05-13 19:02 UTC, swnsma requested changes
Hi @polkan-msk,

Thank you for your contribution!
Your PR looks really great!

But we need to have green build to process the PR.
Could you please check and fix failed static tests?

2019-05-14 13:37 UTC, swnsma approved these changes
@polkan-msk,
Thank you for your changes.

QA, the main idea of the bug that if you select year period in '01-01-2018 - 14-05-2019' it will show statistic for 2 periods: '01-01-2018 - 14-05-2018' and '01-01-2019 - 14-05-2019'

2019-05-14 13:38 UTC, magento-engcom-team commented
Hi @swnsma, thank you for the review.
[ENGCOM-5113](https://jira.corp.magento.com/browse/ENGCOM-5113) has been created to process this Pull Request

2019-05-14 13:38 UTC, magento-engcom-team commented
@polkan-msk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-05-15 08:14 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-05-23 12:50 UTC, merged