#22479 - product required options prices considered in price index
magento/magento2 pull request #22865
Opened 2019-05-13 12:18 UTC by Wirson

### Description (*)
When products has required options, their prices were summed up in min_price index column. Price take into account in sorting is min_price, thus on category page, products with options were sorted incorrectly.

### Fixed Issues (if relevant)
If product has required options, its price on category page is displayed with required additions. 
1. magento/magento2#22479: Sort by price is not working with custom options as expected in magento 2.3.0 product listing page

### Manual testing scenarios (*)
1. Valid path provided in linked [issue](https://github.com/magento/magento2/issues/22479)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-17 08:42 UTC, swnsma requested changes
Hi @Wirson,
Look like these changes have huge impact for Integration and Functional tests.
Could you please check failed tests?

2019-05-17 10:16 UTC, Wirson commented
> Hi @Wirson,
> Look like these changes have huge impact for Integration and Functional tests.
> Could you please check failed tests?

[test product data](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Catalog/_files/product_simple.php#L117)

2019-05-17 11:52 UTC, swnsma commented
Hi @Wirson,
Thank you for your reply.
I will check this question with Magento Product Owners team.

2019-05-20 19:04 UTC, swnsma commented
Hi @Wirson,

It looks like that prices on POP should be shown as summed value.
The same in tests.

But there is other case. If we will try to set **special price** for any product from your example, **the final price** will be save and shown **without custom option price** on POP.
Could you also check this case?

2019-05-24 09:40 UTC, Wirson commented
Hi @swnsma 

thank you for testing my changes. For the moment I have to give up with special price issue due to insufficient time and no valid solution found so far. I can't figure out working solution for this issue. Please proceed by assigning this ticket further, or close it.

2019-05-24 15:51 UTC, swnsma commented
Hi @Wirson,
Thank you for your reply and for information.
I will close this pull request.
Please feel free to re-open this Pull Request and continue to work with it.

2019-05-24 15:51 UTC, closed without merging