Fixed issue #22875 Billing Agreements page title need to be improved
magento/magento2 pull request #22876
Opened 2019-05-13 23:10 UTC by amitvishvakarma

Fixed #22875 Billing Agreements page title need to be improved

### Preconditions (*)

1. Magento 2.3.x
2. Customer must be logged in.

### Steps to reproduce (*)

1. Login as customer in frontend
2. Now go to Billing Agreements tab

### Expected result (*)

1.Page title must be only : Billing Agreements

### Actual result (*)

1. Page title is showing: Billing Agreements / My Account

2019-05-13 23:10 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22876) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22876) before we can accept your contribution.<br/>

2019-05-14 15:31 UTC, VladimirZaets requested changes
Hi @amitvishvakarma  , please, sign CLA, otherwise, we can't process your pull request

2019-05-17 13:55 UTC, VladimirZaets approved these changes

2019-05-17 13:57 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5125](https://jira.corp.magento.com/browse/ENGCOM-5125) has been created to process this Pull Request

2019-05-20 06:40 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-05-23 21:58 UTC, merged