Fix random fails during parallel SCD execution
magento/magento2 pull request #22886
Opened 2019-05-14 10:11 UTC by ihor-sviziev

### Description (*)
No need to use locks when running in CLI mode, for instance during running `php bin/magneto setup:static-content:deploy`

### Fixed Issues (if relevant)
1. magento/magento2#22880: Static content deploy - Randomly css files not generated

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-14 15:57 UTC, VladimirZaets requested changes
Hi @ihor-sviziev. Thanks for collaboration. Please fix static and unit tests.

2019-05-16 12:13 UTC, ihor-sviziev commented
Hi @VladimirZaets,
Static tests complains about lines that I didn't changed. I think it could be fixed during processing PR.

About unit tests - not sure how I could fix it because unit tests are always running from CLI. Could you point me?

2019-05-24 13:37 UTC, ihor-sviziev commented
Hi @VladimirZaets,
I fixed static tests, but not sure how to fix unit tests for this case.

In theory we should add some dependence to constructor that will have `isCli` method, but in framework we don't have such. 
Also I analyzed all places that I we have currently in magento where used `PHP_SAPI` constant or `php_sapi_name` function - all of them just **not covered** with unit tests, probably because of mentioned issue.

So I see there two options:
1. Remove existing unit tests
2. Introduce some class in Magento Framework that will have isCli method and use it. As for me - that's wrong way.

I don't mind if you'll fix unit tests internally using any different approach

2019-06-21 13:52 UTC, ihor-sviziev commented
Hi @VladimirZaets @sidolov,
Could you point me what to do with this case?

2019-06-27 14:25 UTC, VladimirZaets commented
Hi @ihor-sviziev. Thanks for collaboration. I discussed this case with our architectors and we think that we can remove this unit test

2019-07-18 06:35 UTC, ihor-sviziev commented
> Hi @ihor-sviziev. Thanks for collaboration. I discussed this case with our architectors and we think that we can remove this unit test

Done

2019-08-09 19:47 UTC, VladimirZaets approved these changes

2019-08-09 19:48 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5582](https://jira.corp.magento.com/browse/ENGCOM-5582) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-11 08:23 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-12 14:01 UTC, merged