#22869 - defaulting customer storeId fix
magento/magento2 pull request #22893
Opened 2019-05-14 14:37 UTC by Wirson

### Description (*)
Fix prevent saving default customer storeId if one was not passed in rest request. StoreId is taken from previously loaded customer data if none is provided.

### Fixed Issues (if relevant)
1. magento/magento2#22869: REST: Updating a customer without store_id sets the store_id to default

### Manual testing scenarios (*)
1. use steps provided in issue [description](https://github.com/magento/magento2/issues/22869#issue-443427004)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-14 16:14 UTC, VladimirZaets approved these changes

2019-05-14 16:15 UTC, VladimirZaets requested changes
Hi @Wirson. Thanks for collaboration. Please fix the integration tests.

2019-05-14 16:15 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5116](https://jira.corp.magento.com/browse/ENGCOM-5116) has been created to process this Pull Request

2019-05-17 09:00 UTC, Wirson commented
> Hi @Wirson. Thanks for collaboration. Please fix the integration tests.

No tests failed, several were skipped.

2019-05-17 13:52 UTC, VladimirZaets approved these changes

2019-05-17 13:53 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5116](https://jira.corp.magento.com/browse/ENGCOM-5116) has been created to process this Pull Request

2019-05-20 07:10 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

**Before:**

![before](https://user-images.githubusercontent.com/44244273/58002563-5f838680-7ae7-11e9-92ee-10318ff17fc7.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/58002593-70cc9300-7ae7-11e9-9333-57a4858471ce.png)

2019-05-24 10:56 UTC, merged