#22869 - defaulting customer storeId fix - backport
magento/magento2 pull request #22895
Opened 2019-05-14 15:02 UTC by Wirson

### Description (*)
Backport pull request
Fix prevent saving default customer storeId if one was not passed in rest request. StoreId is taken from previously loaded customer data if none is provided.

### Fixed Issues (if relevant)
1. magento/magento2#22869: REST: Updating a customer without store_id sets the store_id to default

### Manual testing scenarios (*)
1. use steps provided in issue [description](https://github.com/magento/magento2/issues/22869#issue-443427004)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-27 12:35 UTC, dmytro-ch requested changes
Hi @Wirson, could you please merge the latest changes from `2.2-develop` into your working branch, and update it according to original PR.
Please, also fix the integration test if necessary.

Thank you!

2019-05-29 11:16 UTC, Wirson commented
> Hi @Wirson, could you please merge the latest changes from `2.2-develop` into your working branch, and update it according to original PR.
> Please, also fix the integration test if necessary.
> 
> Thank you!

Code updated. I did not remove lines removed in original PR due to failing tests. Just a code style refactor. 
Failing integration tests are only skipped, right now no tests really fail.

2019-05-30 14:18 UTC, dmytro-ch approved these changes

2019-05-30 14:19 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5188](https://jira.corp.magento.com/browse/ENGCOM-5188) has been created to process this Pull Request

2019-05-31 17:21 UTC, merged