Do an empty check instead of isset check on image removed
magento/magento2 pull request #22910
Opened 2019-05-16 07:15 UTC by arnoudhgz

In some cases the 'removed' tag on the image is already set to an empty
string in the data which will be loaded. Therefore the isset check fails
which clears the image roles.

On all other cases where this 'removed' tag is being validated with an
empty or !empty. Therefor it seems safe to apply this here also.

### Manual testing scenarios (*)
1. Upload an image for a product
2. Set the image roles
3. See that the image roles still work
4. Try step 2 and 3 with different combination of image roles.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2019-05-16 12:51 UTC, orlangur requested changes
@arnoudhgz did you manage to figure out stable steps to reproduce?

2019-05-16 13:07 UTC, arnoudhgz commented
@orlangur No I could not, but every other check with `removed` is done with `empty`. Changing this worked in a Vanilla installation and the installation where it was broken.

2019-06-07 21:37 UTC, sidolov approved these changes

2019-06-07 21:38 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5235](https://jira.corp.magento.com/browse/ENGCOM-5235) has been created to process this Pull Request

2019-06-25 12:39 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-06-26 16:37 UTC, merged