[Backport] #22899 Fix the issue with Incorrect return type at getListByCustomerId in PaymentTokenManagementInterface
magento/magento2 pull request #22915
Opened 2019-05-16 11:14 UTC by serhiyzhovnir

### Original PR
https://github.com/magento/magento2/pull/22914

### Description (*)
Fix the issue with Incorrect return type at getListByCustomerId in PaymentTokenManagementInterface.
The Magento\Vault\Model\PaymentTokenManagement implements this interface and this class actually return the list of PaymentTokenSearchResultsInterface interfaces.

### Fixed Issues (if relevant)

1. magento/magento2#22899: Incorrect return type at getListByCustomerId in PaymentTokenManagementInterface

### Manual testing scenarios (*)

1. call getListByCustomerId() method of PaymentTokenManagementInterface interface and you will see that array with PaymentTokenSearchResultsInterface interfaces is returned.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-16 12:16 UTC, ihor-sviziev commented
On hold till https://github.com/magento/magento2/pull/22914 will be processed

2019-05-20 05:22 UTC, ihor-sviziev commented
Hi @serhiyzhovnir,
Could you also add changes from following commit https://github.com/magento/magento2/pull/22914/commits/f1c85d4cc12328412e45ef5d51012798513eb0b2?
It's present in 2.3 PR, but not present in backport

2019-05-20 05:22 UTC, ihor-sviziev requested changes
Hi @serhiyzhovnir,
Could you also add changes from following commit https://github.com/magento/magento2/pull/22914/commits/f1c85d4cc12328412e45ef5d51012798513eb0b2?
It's present in 2.3 PR, but not present in backport

2019-05-20 10:53 UTC, serhiyzhovnir commented
Hi @ihor-sviziev,
I have added the changes from the https://github.com/magento/magento2/commit/f1c85d4cc12328412e45ef5d51012798513eb0b2 commit to this PR.
Thank you!

2019-05-21 06:07 UTC, ihor-sviziev commented
Now changes looks good. Now need just wait till #22914 will be merged

2019-05-29 18:13 UTC, ihor-sviziev approved these changes

2019-05-29 18:14 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5182](https://jira.corp.magento.com/browse/ENGCOM-5182) has been created to process this Pull Request

2019-05-30 07:58 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-05-30 10:11 UTC, merged