Mark Elasticsearch 6 support for synonyms
magento/magento2 pull request #22937
Opened 2019-05-18 13:45 UTC by aapokiiso

### Description (*)

Elasticsearch 6 supports search synonyms in Magento just like previous Elasticsearch versions. Flagging synonyms as supported removes the following warning from Marketing > SEO & Search > Search Synonyms:

> Search synonyms are not supported by the elasticsearch6 search engine. Any synonyms you enter won't be used.

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

1. Go to Marketing > SEO & Search > Search Synonyms in the admin panel.
2. Notice the warning message about missing support for synonyms in Elasticsearch 6. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-20 07:58 UTC, dmytro-ch requested changes
Hi @aapokiiso,

I guess we should also disable this warning message for Elasticsearch 5 in `app/code/Magento/Elasticsearch/etc/search_engine.xml` since we use the same adapter (`Magento\Elasticsearch\Elasticsearch5\SearchAdapter\Adapter`) for both 5th and 6th versions.
As a result, the same Synonyms Preprocessor `Magento\Search\Adapter\Query\Preprocessor\Synonyms` is being used for all the ES versions supported by Magento 2.3.x.

Could you please also check and resolve the functional test failure?

Thank you!

2019-06-03 15:20 UTC, sidolov approved these changes

2019-06-03 15:21 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5201](https://jira.corp.magento.com/browse/ENGCOM-5201) has been created to process this Pull Request

2019-06-04 10:32 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-06-07 03:10 UTC, merged