Fix Issue 22743
magento/magento2 pull request #22944
Opened 2019-05-20 05:08 UTC by ernesthernandez

### Description (*)
New logic introduced in 2.3.1 https://github.com/magento/magento2/commit/2fb6b3b81ada22e1a172272a7eb5454a50a71a2d populates wrong quantity for the bundled products .

See  magento/magento2#22743
### Fixed Issues (if relevant)
1. magento/magento2#22743: M2.3.1: Unable to place order for bundle when child quantity > 1

### Manual testing scenarios (*)
1. Add Test bundle to the shopping cart, making sure to set the child quantity to a value > 1:
2. Proceed to Checkout
3. Select PayPal Express Checkout as the payment method.
Expected result (*)
Customer is redirected back to Magento's Order Success page
Actual result (*)
Error message We found an invalid quantity to invoice item "%1". is displayed.
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-20 05:08 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22944) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22944) before we can accept your contribution.<br/>

2019-05-20 08:41 UTC, VladimirZaets requested changes

2019-05-20 08:41 UTC, VladimirZaets commented on app/code/Magento/Sales/Model/Service/InvoiceService.php
> +        JsonSerializer $serializer
Hi, @ernesthernandez, due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't add required parameters to the constructor. Please revert your changes.

2019-06-03 15:21 UTC, sidolov commented
@ernesthernandez , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-06-03 15:21 UTC, closed without merging