magento/magento2#21232: Custom select attribute code container breaks…
magento/magento2 pull request #22983
Opened 2019-05-23 07:58 UTC by m-a-x-i-m

… javascript on update attributes.

Description
Added "attributes_" prefiix to id of input fields of attributes in Mass Update Products Attributes page

Fixed Issues
#21232: Custom select attribute code "container" breaks javascript on update attributes

Manual testing scenarios
1. Create a custom select attribute with a code of "container"
2. Go to the Catalog->Products and check the box next to at least one product.
3. Click the Action dropdown and select "Update Attributes"
4. Scroll down until you see your container attribute and you will see that it is not disabled

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-23 07:58 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=22983) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22983) before we can accept your contribution.<br/><hr/>**Maxim Tkachuk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-05-23 11:04 UTC, VladimirZaets requested changes
Hi @m-a-x-i-m  , please, sign CLA, otherwise, we can't process your pull request

2019-07-15 18:51 UTC, sidolov commented
@m-a-x-i-m , please, resolve merge conflicts

2019-08-19 18:32 UTC, sidolov commented
@m-a-x-i-m , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-19 18:32 UTC, closed without merging