Add a MessageFormatter Phrase renderer
magento/magento2 pull request #22996
Opened 2019-05-23 17:23 UTC by navarr

This gives us the ability to use ICU MessageFormatter formatting strings (inc. placeholders) for better support of internationalization.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-23 18:31 UTC, navarr commented
Naive performance testing results (testing only the cost of the formatting in different scenarios - data for the comment)

**Cost for non-MessageFormatter strings**:
```
Text: This is a translatable string
Arguments: Array()

MessageFormatter: 2.4036829471588 Avg: 2.4036829471588E-6
strpos: 0.55331492424011 Avg: 5.5331492424011E-7
Speed Difference (over 1000000 iterations): 4.3441498536478 or 0.23019463731443
```

**Cost for MessageFormatter strings**:
```
Text: This is {,plural,=1 {a translatable string} other {some translatable strings}}
Arguments: Array
(
    [0] => 1
)

MessageFormatter: 2.2827291488647 Avg: 2.2827291488647E-6
strpos: 3.03768491745 Avg: 3.03768491745E-6
Speed Difference (over 1000000 iterations): 0.75147002105177 or 1.3307250748345
```

"Speed Difference" is MessageFormatter÷strpos or strpos÷MessageFormatter

All costs are per 1,000,000 operations.  Naive code at: https://gist.github.com/navarr/e4c2b69b0d0fd3ca40b764e771640d11

2019-05-24 13:40 UTC, joni-jones commented on lib/internal/Magento/Framework/Phrase/Renderer/MessageFormatter.php
> +     * @inheritDoc
Please, use `@inheritdoc` instead

2019-05-24 13:40 UTC, joni-jones commented on lib/internal/Magento/Framework/Phrase/Test/Unit/Renderer/MessageFormatterTest.php
> +        $this->objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager($this);
Please, avoid FQCN usage.

2019-05-24 14:11 UTC, ihor-sviziev requested changes
Hi @navarr,
Thank you for contribution! Really good job!

Could you review comments from me and from @joni-jones?

2019-05-24 14:11 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Phrase/Renderer/MessageFormatter.php
> +/**
Could you add `declare(strict_types=1);` there?

2019-05-24 14:11 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Phrase/Test/Unit/Renderer/MessageFormatterTest.php
> +/**
Could you add `declare(strict_types=1);` there?

2019-05-24 17:55 UTC, navarr commented
I've performed the changes as requested 👍

2019-05-27 05:29 UTC, ihor-sviziev approved these changes

2019-05-27 05:30 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5167](https://jira.corp.magento.com/browse/ENGCOM-5167) has been created to process this Pull Request

2019-07-10 18:55 UTC, sdzhepa commented
Hello @navarr 
Thank you for your contribution and collaboration! 

Unfortunately, we are stuck on the testing stage for this PR.
From the code perspective, it looks very good and useful.
And now we need to test it before merging these changes into develop branch.

So, could you please help us with user scenarios/steps and expected result for manual testing?

Thank you in andvance

2019-07-17 08:07 UTC, ihor-sviziev commented
Hi @sdzhepa,

In code we can see examples:
https://github.com/magento/magento2/pull/22996/files#diff-a27e2b7497834215b438835c65ccbf07R45


Even in the issue description here is Japanese example:
> 注文が{orders, plural, =0 {ない} other {#つある}}

For testing you should use this Japanese locale in your magento store, add ja_JP translation to csv file like this:
```
"There are {orders, plural, =0 {no orders} =1 {1 order} other {# orders}}", "注文が{orders, plural, =0 {ない} other {#つある}}"
```

And try to execute following translation with code:
```
echo __("There are {orders, plural, =0 {no orders} =1 {1 order} other {# orders}}", ['orders' => 0]);
echo __("There are {orders, plural, =0 {no orders} =1 {1 order} other {# orders}}", ['orders' => 1]);
echo __("There are {orders, plural, =0 {no orders} =1 {1 order} other {# orders}}", ['orders' => 3]);
echo __("There are {orders, plural, =0 {no orders} =1 {1 order} other {# orders}}", ['orders' => 15]);
```

2019-07-18 12:14 UTC, engcom-Delta commented
@ihor-sviziev Thanks for explanation

2019-07-18 12:14 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-02 07:19 UTC, ihor-sviziev commented
Hi @sivaschenko,
Could you add some info why this PR still wasn't merged?

2019-09-05 03:34 UTC, merged