#22998 : failing order creation with api when no address email is provided
magento/magento2 pull request #23048
Opened 2019-05-29 11:27 UTC by Wirson

### Description (*)
When billing address data is before customer data in order create api JSON payload, the billing address email is not populated. see https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order.php#L997 . Order is empty, so customer email is nowhere to be brought from.

### Fixed Issues (if relevant)
1. magento/magento2#22998 : POST on /orders fails when properties in the body are out of sequence

### Manual testing scenarios (*)
1. use provided JSON payloads but fill it with your data
2. to fail, simply put billing address as first node.

### Questions or comments
I am not sure whether this is the best solution.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-29 14:46 UTC, dmytro-ch requested changes
Hi @Wirson,
thank you for your contribution!

Unfortunately, the current solution is rather a workaround and it does not seem to be solving the real issue.

The issue should have appeared because of the setter methods called by the Webapi Service Input Processor in the same order as the properties are provided in a payload. I would say this is the framework issue and would be better to normalize the data provided in payload etc.

However, in this particluar case, the setter methods are implemented unproperly.
```
\Magento\Sales\Model\Order::setBillingAddress
\Magento\Sales\Model\Order::setShippingAddress
```

Having a logic within a setter method is bad practice.
So I would recommend fixing the issue by refactoring these two methods if it's possible.

Thank you!

2019-05-30 09:32 UTC, Wirson commented
> Hi @Wirson,
> thank you for your contribution!
> 
> Unfortunately, the current solution is rather a workaround and it does not seem to be solving the real issue.
> 
> The issue should have appeared because of the setter methods called by the Webapi Service Input Processor in the same order as the properties are provided in a payload. I would say this is the framework issue and would be better to normalize the data provided in payload etc.
> 
> However, in this particluar case, the setter methods are implemented unproperly.
> 
> ```
> \Magento\Sales\Model\Order::setBillingAddress
> \Magento\Sales\Model\Order::setShippingAddress
> ```
> 
> Having a logic within a setter method is bad practice.
> So I would recommend fixing the issue by refactoring these two methods if it's possible.
> 
> Thank you!

I was going through rest api request processing line by line, and I did not find a way to influence the request from outside webapi or framework module. Also, refactoring setBillingAddress() will not change anything in this matter if there is no email in order object yet. Any clues?

2019-06-19 13:45 UTC, dmytro-ch commented
After performing the internal checks I could not find a better entry point for the fix.
I think we may ignore the **Semantic Version Checker** warning, considering the `beforeSave` public method already exists in the parent class.

2019-06-19 13:45 UTC, dmytro-ch approved these changes

2019-06-19 13:46 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5312](https://jira.corp.magento.com/browse/ENGCOM-5312) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-20 10:07 UTC, engcom-Delta commented
:heavy_check_mark: QA Passed

2019-07-01 12:01 UTC, merged