Issue fix #18264: Wrong special_price in indexer database tables for bundle products.
magento/magento2 pull request #23056
Opened 2019-05-29 15:16 UTC by bizzi

### Description (*)
Issue was already fixed in M2.2.8 but only for Configurable products. Same situation relates to Bundle product prices and it's indexer (SQL). All conditions there are correct, but are not grouped which results with wrong special_price data populating in indexer database tables.  

### Fixed Issues (if relevant)
1. magento/magento2#18264: M2.2.6 : "Order by price" not working in product listing

### Manual testing scenarios (*)

1. Set same regular price for 2-3 bundle products
2. Set same special_price on above products
3. Set different dates in fields `special_price_from` and `special_price_to`, but having one product with special date valid for the day of testing.
4. Assign above products to the same category
5. Open that category page and watch results

#### Results: 
Products are sorted as if they have same (special) price, but displayed price is correct according to dates set in  `special_price_from` and `special_price_to` fields. 
In `catalog_product_index_price` table all three products have set special_price.

### Questions or comments
As I checked the issue is presenting in M2.3-develop as well. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-05-29 15:16 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23056) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23056) before we can accept your contribution.<br/>**2** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: magento-engcom-team<br/>:white_check_mark: StasKozar<br/>:x: aakimov<br/>:x: Amol Chaudhari<br/>:x: SeruyV<br/>:x: svitja<br/>:x: DianaRusin<br/>:x: ameysar<br/>:x: cpartica<br/>:x: ajay-2jcommerce<hr/>**Amol Chaudhari, ajay-2jcommerce** seem not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-05-29 15:54 UTC, Stepa4man commented
Hi, @bizzi. Please first provide this fix for 2.3-develop and sign Contributor License Agreement.
Thank you for your contribution.

2019-05-29 16:44 UTC, Stepa4man requested changes
Hi, @bizzi. Please first provide this fix for 2.3-develop and sign Contributor License Agreement.
Thank you for your contribution.

2019-07-15 18:14 UTC, sidolov commented
@bizzi , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-07-15 18:14 UTC, closed without merging