#23053 : sendfriend verifies product visibility instead of status
magento/magento2 pull request #23118
Opened 2019-06-04 11:00 UTC by Wirson

### Description (*)
Sendfriend feature was verifying product status only. This could cause sending a link for enabled product invisible in catalog and/or search. 

### Fixed Issues (if relevant)
1. magento/magento2#23053: Sendfriend works for products with visibility not visible individually

### Manual testing scenarios (*)
Follow steps provided in #23053

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-04 11:00 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23118) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23118) before we can accept your contribution.<br/>

2019-06-04 11:51 UTC, orlangur requested changes
@Wirson please enforce this case with integration test and sign CLA.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

2019-06-06 10:04 UTC, Wirson commented
@orlangur I added related test case, please review.
Static test returns error:

> FILE: /var/www/html/app/code/Magento/SendFriend/Controller/Product.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 64 | ERROR | [x] There must be exactly one blank line between lines
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

But I do not really get the point

2019-06-07 03:31 UTC, sidolov approved these changes

2019-06-07 03:32 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5228](https://jira.corp.magento.com/browse/ENGCOM-5228) has been created to process this Pull Request

2019-06-07 09:50 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

**Before:**

![before](https://user-images.githubusercontent.com/44244273/59096100-c8aa2d00-8922-11e9-8389-fac10f0ca91d.png)

**After:**

![after](https://user-images.githubusercontent.com/44244273/59096113-cf38a480-8922-11e9-9d7c-1545de9af4b8.png)

2019-06-08 22:22 UTC, merged