Fix for Advanced Search Allows Search using Blank Spaces
magento/magento2 pull request #23127
Opened 2019-06-05 04:19 UTC by AnshuMishra17

### Description (*)
Fix for the Advanced Search issue which allows search by entering only blank spaces in all the fields of the form.

### Fixed Issues (if relevant)
1. magento/magento2#23055: Advanced Search Allows Search using Blank Spaces

### Manual testing scenarios (*)
1. Click on Advanced Search link in the footer
2. Enter only blank spaces in any/all fields
3. Click on Search button

2019-06-06 07:09 UTC, AnshuMishra17 commented
@sidolov @orlangur Please explain me the issue here. I am not able to understand it. why the test applyExpiredCoupon is failing? How it is related to my change.

2019-07-15 18:09 UTC, sidolov requested changes

2019-07-15 18:09 UTC, sidolov commented on app/code/Magento/CatalogSearch/Model/Advanced.php
> +            $value = (is_string($value) ? trim($value) : $value);
Could you please clarify, why we need to trim string twice?

2019-07-30 15:42 UTC, sidolov commented
@AnshuMishra17  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-07-30 15:42 UTC, closed without merging