Catch throwables in mview updating
magento/magento2 pull request #23124
Opened 2019-06-04 15:39 UTC by QuentinFarizonAfrimarket

### Description (*)
Certain type of runtime exception weren't caught during mview updating, which caused some mview to be stuck in "processing" mode.
Refer to https://github.com/magento/magento2/issues/23054 for more detail about the issue.

This modification is very similar to the one made here : https://github.com/magento/magento2/commit/5927a75169aa5eb7a978847d22dbde5dbe3cc5a2

### Fixed Issues (if relevant)
https://github.com/magento/magento2/issues/23054 

### Manual testing scenarios (*)
- make an mview updating crash with a Throwable (not an Exception)
- process ends, mview is still in 'processing' in database
- it is never picked up again 

### Questions or comments
This does not prevent against all types of crashes (like process out of memory or server stop abruptly, so it is only a step in making indexing crons more resilient 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-04 15:39 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23124) <br/>All committers have signed the CLA.

2019-06-04 15:50 UTC, orlangur requested changes
@QuentinFarizonAfrimarket all changes must be applied to `2.3-develop` first.

If they are already fixed there, instead of creating new commits appropriate ones should be backported.

2019-06-04 16:20 UTC, QuentinFarizonAfrimarket commented
Hello @orlangur ok thanks, I have opened the PR on 2.3 also : https://github.com/magento/magento2/pull/23125

2019-07-10 15:26 UTC, VladimirZaets commented
Hi @QuentinFarizonAfrimarket . The branch `2.2-develop` will be closed for contribution from **July 15, 2019**. Please finish all your Pull Requests till this date, otherwise, they will be closed.
Thanks for collaboration.

2019-07-15 10:28 UTC, orlangur commented
@VladimirZaets any idea why https://github.com/magento/magento2/pull/23125 is still not merged having approval since Jun 5th?

2019-07-15 10:51 UTC, QuentinFarizonAfrimarket commented
I was indeed waiting for https://github.com/magento/magento2/pull/23125 to be merged to bring changes here, but with the due date being today I have pushed a version which fixes static tests, in the hope it will be taken in 2.2-develop

2019-07-15 11:28 UTC, orlangur requested changes
Great job @QuentinFarizonAfrimarket! Please re-resolve conflict though :)

2019-07-15 12:50 UTC, QuentinFarizonAfrimarket commented
Sorry, should be better like this :)

2019-07-15 21:36 UTC, orlangur commented
@QuentinFarizonAfrimarket definitely ;) A small thing left, unit test needs to be adjusted.

2019-07-16 22:00 UTC, VladimirZaets commented
Hi @QuentinFarizonAfrimarket.
The next 2.2 release will be the last of functional releases.
Due to it, we are closing 2.2-develop for contribution.
Thanks for collaboration.

2019-07-16 22:00 UTC, closed without merging