[Backport] Customer Account Forgot Password page title fix
magento/magento2 pull request #23148
Opened 2019-06-06 05:03 UTC by krishprakash

### Original Pull Request 
 https://github.com/magento/magento2/pull/22821
Missing question mark in Customer Account Forgot Password page title, because of this it was missing the translated string.

2019-06-06 05:03 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23148) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23148) before we can accept your contribution.<br/>

2019-06-06 05:07 UTC, ronak2ram approved these changes

2019-06-06 08:33 UTC, VasylShvorak commented
:heavy_check_mark: QA passed

2019-06-06 09:55 UTC, orlangur requested changes
@krishprakash original commit author and message must be preserved

2019-06-07 12:22 UTC, krishprakash commented
@orlangur I have updated the PR as suggested by you.
Please have a look and update the PR.
Thank you.

2019-06-07 13:52 UTC, orlangur approved these changes

2019-06-10 07:35 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-06-11 16:48 UTC, merged