[Backport] Issue fixed #22636 arrow toggle not changing only showing to down It should be toggle as every where is working
magento/magento2 pull request #23150
Opened 2019-06-06 05:22 UTC by krishprakash

### Original Pull Request 
 https://github.com/magento/magento2/pull/22644
Issue fixed #22636

### Description (*)
arrow toggle not changing only showing to down It should be toggle as every where is working 

### Manual testing scenarios (*)
1. Login to admin panel
2. Go to store link and click on Tax Rules Available on sub menu
3. Click on add new tax rule and see Additional Settings tab and click on same

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-06-06 05:30 UTC, krishprakash commented
@magento give me test instance

2019-06-06 05:31 UTC, magento-engcom-team commented
Hi @krishprakash. Thank you for your request. I'm working on Magento instance for you

2019-06-06 05:31 UTC, magento-engcom-team commented
Hi @krishprakash, here is your [new Magento instance](https://pr-23150.instances.magento-community.engineering).
Admin access: [https://pr-23150.instances.magento-community.engineering/admin](https://pr-23150.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-06-06 05:37 UTC, krishprakash commented
Fixed issue given instance.

2019-06-06 06:32 UTC, ronak2ram approved these changes

2019-06-06 06:33 UTC, magento-engcom-team commented
Hi @ronak2ram, thank you for the review.
[ENGCOM-5213](https://jira.corp.magento.com/browse/ENGCOM-5213) has been created to process this Pull Request

2019-06-06 07:56 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-06-06 09:54 UTC, orlangur requested changes
@krishprakash original commit author and message must be preserved

2019-06-07 11:13 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23150) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23150) before we can accept your contribution.<br/><hr/>**Prakash Prajapati** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-06-07 14:13 UTC, krishprakash commented
@orlangur I have updated the PR as suggested by you.
Please have a look and update the PR.
Thank you.

2019-06-13 05:30 UTC, krishprakash commented
@orlangur
Is there anything remaining from my end.
If any please let me know.
Otherwise please update the status of PR.
Thanks.

2019-06-22 12:12 UTC, orlangur approved these changes

2019-06-22 12:13 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-5213](https://jira.corp.magento.com/browse/ENGCOM-5213) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-24 08:40 UTC, engcom-Delta commented
:heavy_check_mark: QA Passed

2019-06-26 18:26 UTC, merged