[Backport] Remove timestap from current date when saving product special price from date
magento/magento2 pull request #23152
Opened 2019-06-06 06:05 UTC by krishprakash

### Original Pull Request 
 https://github.com/magento/magento2/pull/21966
### Description (*)
Full timestamp is saved when creating a new product with a special price but without a special price from value.

With this fix, the time is reset so only the date will be saved. This is also in line with the UI where only a date can be selected.

### Fixed Issues (if relevant)
1. None I could find.

### Manual testing scenarios (*)
1. Set configuration on global scope `general/locale/timezone` > `Europe/Amsterdam`.
2. Set configuration on en_US scope `general/locale/timezone` > `America/New_York`.
3. Create new simple product with special price (leave special price from date empty).
4. Product will be saved with a current timestamp using the `Europe/Amsterdam` timezone.
5. Navigate to product on frontend (en_US store), no special price is shown. This is because special price from date is checked against the `America/New_York` timezone. This isn't the case for another five hours.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2019-06-06 09:54 UTC, orlangur requested changes
@krishprakash original commit author must be preserved

2019-06-06 11:04 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23152) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23152) before we can accept your contribution.<br/><hr/>**Prakash Prajapati** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-06-07 14:12 UTC, krishprakash commented
@orlangur I have updated the PR as suggested by you.
Please have a look and update the PR.
Thank you.

2019-06-07 14:14 UTC, krishprakash commented
@orlangur I have updated the PR as suggested by you.
Please have a look and update the PR.
Thank you.

2019-06-07 14:15 UTC, orlangur commented
@krishprakash please sign CLA.

2019-06-10 08:16 UTC, krishprakash commented
> @krishprakash please sign CLA.

Signed the CLA.

2019-06-13 05:30 UTC, krishprakash commented
@orlangur
Is there anything remaining from my end.
If any please let me know.
Otherwise please update the status of PR.
Thanks.

2019-06-22 12:12 UTC, orlangur approved these changes

2019-06-22 12:14 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-5341](https://jira.corp.magento.com/browse/ENGCOM-5341) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-24 10:58 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-06-26 18:26 UTC, merged