Magento_SendFriend module change suggestion
magento/magento2 pull request #23178
Opened 2019-06-08 12:44 UTC by nemke82

The Magento_SendFriend implements the functionality behind the “Email to a Friend” link on a product page, which allows sharing favorite products with others by clicking the link. One of the major bottlenecks here is that Magento recommends the use of the SMTP module to successfully send and inbox inviting email, but that never works. Simply, the module-send-friend is designed to place the FROM with the Customer account or Guest account (if enabled) details. Even with all valid SMTP settings (details) this is most likely going to fail when sending emails to any popular email exchange provider like Google, Yahoo, Hotmail, Yandex or similar. At the end we don't need an SMTP module installed to make this work, just Magento module itself tweaked.

### Description (*)
I've figured that these two lines are controlling this module:
$sender = [
'name' => $this->_escaper->escapeHtml($this->getSender()->getName()),  
'email' => $this->_escaper->escapeHtml($this->getSender()->getEmail()),  
        ];

To explain. I've swapped the 'name' and 'email' places since it is not necessary to have Name field repeated twice. You can freely test this functionality of my adjusted code on my Demo/Test page https://magentocommand.ml/hanna-sweater.html by clicking on the Email icon

### Fixed Issues (if relevant)
To fix this I've updated app/code/Magento/SendFriend/Helper/Data.php and app/code/Magento/SendFriend/Model/SendFriend.php to pull the FROM record properly from the trans_email/ident_support/email (Stores --> Configuration --> Contact Address) section.

### Manual testing scenarios (*)
You can freely test this functionality of my adjusted code on my Demo/Test page https://magentocommand.ml/hanna-sweater.html by clicking on the Email icon

### Questions or comments
If you are using AmazonSES or any other popular service which enforce the policy that the FROM sender needs to be used as a domain name used this would be extremely helpful to avoid usage of the SMTP module. As I've explained previously mostly SMTP module part fails because SPF/DKIM/DMARC fails.

Sample error: 
2019-06-05 17:41:29 1hYZuj-00003b-PW ** x@xxx.xxx R=sendviases T=sessmtp H=xxxxx.com X=TLS1.2:ECDHERSAAES256GCMSHA384:256 CV=no: SMTP error from remote mail server after MAIL FROM:<> SIZE=3446: 501 Invalid MAIL FROM address provided

Once module tweak is added: 
2019-06-05 17:49:32 1hYa2W-00003k-Fp => xx@xxx.com R=sendviases T=sessmtp H=xxxx.com X=TLS1.2:ECDHERSAAES256GCMSHA384:256 CV=no A=ses_login C="250 Ok 0100016b28c2a272-2250b0bf-d310-4e2a-b8c6-615259231294-000000" 
2019-06-05 17:49:32 1hYa2W-00003k-Fp Completed

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-08 12:44 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23178) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23178) before we can accept your contribution.<br/>

2019-06-10 16:20 UTC, lbajsarowicz commented
The overall idea is nice, however! I would create another Sender definition to let shop owner create something like "recommendations@acme.com" with custom name of customer. :-)

2019-08-15 22:04 UTC, sidolov requested changes

2019-08-15 22:04 UTC, sidolov commented on app/code/Magento/SendFriend/Helper/Data.php
> +    public function getSenderEmail($store = null)
Unfortunately, we are not allowed to add new public methods to the classes marked as @api according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-30 13:38 UTC, sidolov commented
@nemke82  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-30 13:38 UTC, closed without merging