Move Quote related Plugins to correct module
magento/magento2 pull request #23174
Opened 2019-06-07 16:21 UTC by sankalpshekhar

### Description (*)

Move plugins to correct module in Magento_Quote
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-07 17:35 UTC, orlangur approved these changes

2019-06-07 17:36 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-5234](https://jira.corp.magento.com/browse/ENGCOM-5234) has been created to process this Pull Request

2019-06-12 09:01 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-06-12 09:57 UTC, ysapiga commented
@sankalpshekhar please fix static tests fail.

2019-06-14 13:57 UTC, sankalpshekhar commented
@ysapiga I don't the static test results are correct, as it referring to get a different name for the plugin.

Had this been an issue, your QA should have failed, which isn't the case.

2019-06-14 14:09 UTC, sivaschenko requested changes
Hi @sankalpshekhar thanks for the contribution! Please take a look at my review comments

2019-06-14 14:09 UTC, sivaschenko commented on app/code/Magento/Quote/etc/webapi_rest/di.xml
> +        <plugin name="authorization" type="Magento\Quote\Model\QuoteRepository\Plugin\Authorization" />
Please add this plugin declaration to an existing `Magento\Quote\Model\QuoteRepository` type node in this file

2019-06-14 14:09 UTC, sivaschenko commented on app/code/Magento/Quote/etc/webapi_soap/di.xml
> +        <plugin name="authorization" type="Magento\Quote\Model\QuoteRepository\Plugin\Authorization" />
Please add this plugin declaration to an existing `Magento\Quote\Model\QuoteRepository` type node in this file

2019-06-14 14:29 UTC, sivaschenko approved these changes
Code review comment and static tests are already fixed internally.

2019-06-14 14:30 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5234](https://jira.corp.magento.com/browse/ENGCOM-5234) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-14 14:59 UTC, sankalpshekhar commented
@sivaschenko  I have made the requested changes, and PR has been updated.

2019-06-16 18:58 UTC, sivaschenko approved these changes

2019-06-16 18:59 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5299](https://jira.corp.magento.com/browse/ENGCOM-5299) has been created to process this Pull Request

2019-06-18 12:29 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-06-21 22:26 UTC, merged