Fixed: wrong argument passing \DateTimeInterval to strtotime instead …
magento/magento2 pull request #23176
Opened 2019-06-07 19:53 UTC by matheusgontijo

### Description
1) `strtotime` receives `string` as the argument
2) `strtotime` functions on `Magento\Framework\Stdlib\DateTime\Timezone:isScopeDateInInterval()` are handling `$dateFrom` and `$dateTo` **ONLY** as `string`. So the assumption here is that **ALL** `$dateFrom` and `$dateTo` will be passed as string.
3) *Issue:* There are certain contexts on Magento where it passes `$dateFrom` and `$dateTo` as `\DateTimeInterface` instead.
4) PHP throws a warning looking like this: `Warning: strtotime() expects parameter 1 to be string, object given in /vendor/magento/framework/Stdlib/DateTime/Timezone.php on line 273`

Solution:

```
if ($dateFrom instanceof \DateTimeInterface) {
    $dateFrom = $dateFrom->format('Y-m-d H:i:s');
}

if ($dateTo instanceof \DateTimeInterface) {
    $dateTo = $dateTo->format('Y-m-d H:i:s');
}
```

Very simple: check if it's a `\DateTimeInterface`, and if it is, convert into a string.
You can also check on the very same class (`Magento\Framework\Stdlib\DateTime\Timezone`) other methods have this `\DateTimeInterface` checking. In case the data type is already a `string` nothing will be done.

### Manual testing scenarios (*)
Stand alone way to reproduce:
```
$timezone = $om->get('Magento\Framework\Stdlib\DateTime\Timezone');

// works
$timezone->isScopeDateInInterval(0, '2019-01-01 00:00:00', '2019-12-31 23:59:59');

// does NOT work
$dateFrom = \DateTime::createFromFormat('Y-m-d H:i:s', '2019-01-01 00:00:00');
$dateTo   = \DateTime::createFromFormat('Y-m-d H:i:s', '2019-12-31 00:00:00');
$timezone->isScopeDateInInterval(0, $dateFrom, $dateTo);

// result: PHP Warning:  strtotime() expects parameter 1 to be string, object given in /var/www/magento2/vendor/magento/framework/Stdlib/DateTime/Timezone.php
```

2019-06-07 19:53 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23176) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23176) before we can accept your contribution.<br/><hr/>**Matheus Gontijo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-06-07 20:42 UTC, orlangur requested changes

2019-06-07 20:42 UTC, orlangur commented on lib/internal/Magento/Framework/Stdlib/DateTime/TimezoneInterface.php
> +     * @param string|\DateTimeInterface|null $dateTo
Places violating previous contract must be fixed instead.

2019-06-07 20:42 UTC, orlangur commented on lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php
> +            $dateTo = $dateTo->format('Y-m-d H:i:s');
Instead of conversion, please add throwing `InvalidArgumentException`.

2019-06-07 21:15 UTC, matheusgontijo commented
@orlangur uhmm I think we could be a little bit more flexible. I don't really think a violation is occurring by just adding `\DateTimeInterface` as an extra data type. It will **not** exclude `string` as a param. There are two other methods that do pretty much the very same thing, on the same class. Please look to `convertConfigTimeToUtc` and `formatDateTime` methods. Breaking compatibility would be changing from `string` to `array` or `\WhatEverClass`, not to `string|\DateTimeInterface`. There are contexts where `\DateTimeInterface` it being passed, it's just not covered...

*Would you please re-consider?* Thank you so much for your efforts.

2019-07-05 11:53 UTC, sivaschenko commented
Hi @matheusgontijo thanks for the pull request!

I'd agree with @orlangur , places where the `DateTimeInterface` is provided instead of `string` should be fixed.

In my opinion, allowing mixed type variables could potentially cause a lot of issues during possible future refactorings or even debugging.

2019-08-13 21:17 UTC, sidolov commented
@matheusgontijo , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-13 21:17 UTC, closed without merging