[Backport] Re-enable XML as request and response types within the SwaggerUI
magento/magento2 pull request #23190
Opened 2019-06-10 06:28 UTC by speedy008

### Original Pull Request 
 https://github.com/magento/magento2/pull/23025

This MR adds the `application/xml` option to the SwaggerUI for requests and responses.

### Description (*)

The Magento WebApi is capable of handling XML as exchange format beside JSON but this format option is not shown/available in the SwaggerUI for requests and responses (only `application/json` is shown).

### Manual testing scenarios (*)

1. Open the SwaggerUI in the browser `/swagger`
2. Select `application/xml` as format for the request parameters AND/OR
3. Select `application/xml` as format for the response data

![Screenshot 2019-05-27 at 17 08 05](https://user-images.githubusercontent.com/366399/58428265-3b551600-80a2-11e9-8ce9-cf0fb55f0097.png)

![Screenshot 2019-05-27 at 17 08 13](https://user-images.githubusercontent.com/366399/58428271-3ee89d00-80a2-11e9-8c4a-535f5a613a7f.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-12 07:53 UTC, dmytro-ch commented
@magento give me test instance

2019-06-12 07:53 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-06-12 07:54 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-23190.instances.magento-community.engineering).
Admin access: [https://pr-23190.instances.magento-community.engineering/admin](https://pr-23190.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-06-12 08:06 UTC, dmytro-ch approved these changes

2019-06-12 08:07 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5265](https://jira.corp.magento.com/browse/ENGCOM-5265) has been created to process this Pull Request

2019-06-13 06:54 UTC, stoleksiy commented
:heavy_check_mark: QA Passed

2019-06-13 08:22 UTC, Nazar65 requested changes

2019-06-13 08:22 UTC, Nazar65 commented on app/code/Magento/Webapi/Model/Rest/Swagger/Generator.php
> +    private const XML_SCHEMA_PARAMWRAPPER = 'request';
Hi @speedy008  Only PHP > 7.1: private const

2019-06-27 15:37 UTC, sidolov requested changes

2019-06-27 15:37 UTC, sidolov commented on app/code/Magento/Webapi/Model/Rest/Swagger/Generator.php
> +    private XML_SCHEMA_PARAMWRAPPER = 'request';
Syntax is incorrect

2019-07-10 15:24 UTC, VladimirZaets commented
Hi @speedy008. The branch `2.2-develop` will be closed for contribution from **July 15, 2019**. Please finish all your Pull Requests till this date, otherwise, they will be closed.
Thanks for collaboration.

2019-07-14 17:52 UTC, sivaschenko approved these changes

2019-07-14 17:53 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5265](https://jira.corp.magento.com/browse/ENGCOM-5265) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-07-15 07:28 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-07-15 12:27 UTC, merged