Load product in default store before duplicating
magento/magento2 pull request #23209
Opened 2019-06-11 14:32 UTC by JeroenVanLeusden

### Description (*)
Duplicating a product will use the current scope data as default values instead of copying it from the original product.

### Fixed Issues (if relevant)
1. magento/magento2#15656: Duplicate product

### Manual testing scenarios (*)
1. Create product with different values in different StoreViews (e.g StoreView UK, NL, DE, ...)
2. Open product and select one StoreView (e.g. UK - not "All StoreViews"!)
3. Click on "Save product & duplicate"

### Questions or comments
Not really happy with reloading the product while we have it already as method parameter. Maybe deprecate the `copy()` method and create a `copyBySku()` method?

Will update tests if implementation is approved by Magento.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-12 10:39 UTC, dmytro-ch requested changes
Hi @JeroenVanLeusden!

> Not really happy with reloading the product while we have it already as method parameter. Maybe deprecate the copy() method and create a copyBySku() method?

I also agree, it would be better to pass the already correct product data as `copy` method parameter.
So we may try to load the product via repository in case the `current_store_id` value of the product is not equal to  `Store::DEFAULT_STORE_ID`, instead of using the Product Builder in the following controller actions: 
- `\Magento\Catalog\Controller\Adminhtml\Product\Duplicate::execute`
- `\Magento\Catalog\Controller\Adminhtml\Product\Save::execute`

The only problem, in my opinion, is that the product entity after loading does not contain all the necessary data. I guess, the bunch of data entries still need to be populated from request.

Thank you!

2019-06-13 13:48 UTC, JeroenVanLeusden commented
Hi @dmytro-ch,

I can refactor the `\Magento\Catalog\Controller\Adminhtml\Product\Save::execute` te be:
```php
if ($redirectBack === 'duplicate') {
    if ($product->getStoreId() === \Magento\Store\Model\Store::DEFAULT_STORE_ID) {
        $product->unsetData('quantity_and_stock_status');
        $productToDuplicate = $product;
    } else {
        $productToDuplicate = $this->productRepository->get(
            $product->getSku(),
            false,
            \Magento\Store\Model\Store::DEFAULT_STORE_ID,
            true
        );
    }

    $newProduct = $this->productCopier->copy($productToDuplicate);
    $this->messageManager->addSuccessMessage(__('You duplicated the product.'));
}
```

Although i'm not sure what you mean with:
> in my opinion, is that the product entity after loading does not contain all the necessary data. I guess, the bunch of data entries still need to be populated from request.

The product is already saved so all the data we need should be there already when fetched using the repository?

Also, I've found no reference to `\Magento\Catalog\Controller\Adminhtml\Product\Duplicate::execute`. Can we deprecate this class?

2019-06-17 14:30 UTC, dmytro-ch commented
@JeroenVanLeusden,
thank you for the update.

The new solution looks correct to me. 

> Although i'm not sure what you mean with:
> 
> > in my opinion, is that the product entity after loading does not contain all the necessary data. I guess, the bunch of data entries still need to be populated from request.
> 
> 
> The product is already saved so all the data we need should be there already when fetched using the repository?

I mean if you compare the results of `$product->getData()` and `$productToDuplicate->getData()` according to your code snippet, you may get the different number of values in resulting array. We just need to make sure the duplicated product does not lose any data.

> Also, I've found no reference to \Magento\Catalog\Controller\Adminhtml\Product\Duplicate::execute.
> Can we deprecate this class?

Sure

2019-06-27 08:13 UTC, JeroenVanLeusden commented
Hi @dmytro-ch,

I've updated the PR, still using the repository to load the product because it duplicates just fine. Are there some additional tests I can do to make sure it's all good?

2019-08-23 15:18 UTC, sidolov approved these changes

2019-08-23 15:19 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5689](https://jira.corp.magento.com/browse/ENGCOM-5689) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-28 07:09 UTC, engcom-Delta commented
Hi @JeroenVanLeusden during testing PR changes I found issue with product duplicate when different URL Key is set for each store view.
**Manual testing scenario:**

- Create more than one store view:
![image](https://user-images.githubusercontent.com/51681379/63831918-5de41d00-c978-11e9-91c9-cb5f1aebd4fe.png)
- Create product
- Edit product for each store view and save:
 - - **Default Store View:**
- - - Product Name=simple1 default
- - - URL Key=simple1-def
- - **Second View:**
- - - Product Name=simple1 second
- - - URL Key=simple1-second
- - **Third View:**
- - - Product Name=simple1 third
- - - URL Key=simple1-third
- - **Notice:** **Create Permanent Redirect for old URL** is checked on each store view when URL key is edited
![image](https://user-images.githubusercontent.com/51681379/63832277-1e6a0080-c979-11e9-810b-d489ebdaa95c.png)
- Open product and select Second View
- Click on "Save product & duplicate"

**Result:**
:x: Product Name value is set to **All Store Views**(e.g., "simple1") value for each store view
![#23209PRDuplicate](https://user-images.githubusercontent.com/51681379/63833012-a7356c00-c97a-11e9-8c82-bdfc51ec9eb8.png)
:heavy_check_mark: URL keys is generated correctly using store view value for it
![#23209PRURLKey](https://user-images.githubusercontent.com/51681379/63833250-3b9fce80-c97b-11e9-8d22-6a4ba6fb5add.png)

Could you take a look?

2019-09-11 06:04 UTC, ihor-sviziev requested changes
Hi @JeroenVanLeusden,

This PR is really closely related to https://github.com/magento/magento2/pull/24505 and looks like changes from this PR could fix issue that described @engcom-Delta.
Could you collaborate with @webkul-paul to fix both these issues?

2019-09-11 06:04 UTC, ihor-sviziev commented on app/code/Magento/Bundle/Controller/Adminhtml/Bundle/Product/Edit/Duplicate.php
> + * @deprecated
Please add description why it became deprecated and add `@see` tag with example what we should use instead

2019-09-11 06:04 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Edit.php
> +     * @deprecated
Please add description why it became deprecated and add `@see` tag with example what we should use instead

2019-09-11 06:04 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Duplicate.php
> + * @deprecated
Please add description why it became deprecated and add `@see` tag with example what we should use instead

2019-09-11 06:04 UTC, ihor-sviziev commented on app/code/Magento/Downloadable/Controller/Adminhtml/Downloadable/Product/Edit/Duplicate.php
> + * @deprecated
Please add description why it became deprecated and add `@see` tag with example what we should use instead

2019-09-16 15:35 UTC, sidolov commented
@JeroenVanLeusden , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-16 15:35 UTC, closed without merging