[Ui] Calling the always action on opening and closing the modal.
magento/magento2 pull request #23234
Opened 2019-06-12 16:48 UTC by eduard13

### Description (*)
This PR fixes the calling of `always` action before opening the **alert** and **confirm** widgets.

### Fixed Issues (if relevant)
1. magento/magento2#23233: Alert widget doesn't trigger always method on showing the message

### Manual testing scenarios (*)
Keep the browser console open.

1. Create a new `alert` widget on frontend. The following simple code can be used:
```js
require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($, alert) {
        'use strict';

        alert({
            title: 'Alert Title',
            content: 'content',
            modalClass: 'alert',
            actions: {
                always: function() {
                    console.log('always triggering');
                }
            }
        });
    });
```

2. Click **OK** button

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-13 05:21 UTC, dmytro-ch requested changes
Hi @eduard13,
could you please check the functional tests failures?
Most likely the issues appeared after the latest changes.

Thank you!

2019-06-13 15:22 UTC, eduard13 commented
Hi @dmytro-ch,
Looks like the `always` for the confirm widget was breaking the tests(even that locally the tests were successfully passing), as there are some places where the always is not correctly used.
So the fix has been a bit changed and applied only for the alert widget. 

Thank you.

2019-06-13 15:42 UTC, dmytro-ch approved these changes

2019-06-13 15:43 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5278](https://jira.corp.magento.com/browse/ENGCOM-5278) has been created to process this Pull Request

2019-06-18 07:38 UTC, engcom-Alfa commented
Hi @eduard13 ! 

I've checked PR changes and need to clarify one question:

I see text "_always triggering_" logged on opening and **twice** right after clicking the **OK** button.

![after](https://user-images.githubusercontent.com/51679138/59662185-1b9ea280-91b5-11e9-8097-40ce83712465.gif)

Is it expected result or not?

Thanks!

2019-06-18 10:22 UTC, eduard13 commented
Hi @engcom-Alfa,
this issue should be fixed now. Could you please try again? There should be just 1 logging after clicking the **OK** button.
Thank you.

2019-06-18 13:39 UTC, dmytro-ch approved these changes

2019-06-18 13:40 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5278](https://jira.corp.magento.com/browse/ENGCOM-5278) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-18 14:14 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed 

**Before:**

![before](https://user-images.githubusercontent.com/51679138/59691860-6982cd00-91ec-11e9-88fc-8977bf93e6d3.gif)

**After:**

![after](https://user-images.githubusercontent.com/51679138/59691873-70a9db00-91ec-11e9-8655-bfff9f3de2f3.gif)

2019-06-27 14:07 UTC, merged

2020-04-18 20:35 UTC, slavvka commented
@eduard13 Unfortunately this fix has been reverted. Feel free to fix the issue in more appropriate way