Fixed #23238 Apply button act like remove button while create new order from admin
magento/magento2 pull request #23250
Opened 2019-06-13 19:51 UTC by gauravagarwal1001

Fixed #23238 Apply button act like remove button while create new order from admin

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Go to Admin -> Create New Order 
3. Select customer and add product
4. Apply valid coupon
5. Now click apply button again

### Expected result (*)
Coupon should not be removed.

### Actual result (*)
![apply button issue](https://user-images.githubusercontent.com/50658701/59430556-301f1b80-8e00-11e9-9404-7db0df5d5116.jpg)

2019-06-14 00:30 UTC, gauravagarwal1001 commented
@magento give me test instance

2019-06-14 00:30 UTC, magento-engcom-team commented
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento instance for you

2019-06-14 00:30 UTC, magento-engcom-team commented
Hi @gauravagarwal1001, here is your [new Magento instance](https://pr-23250.instances.magento-community.engineering).
Admin access: [https://pr-23250.instances.magento-community.engineering/admin](https://pr-23250.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-06-14 07:08 UTC, aleron75 approved these changes

2019-06-14 07:09 UTC, magento-engcom-team commented
Hi @aleron75, thank you for the review.
[ENGCOM-5292](https://jira.corp.magento.com/browse/ENGCOM-5292) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-14 07:50 UTC, engcom-qa-Delta commented
:heavy_check_mark: QA Passed

2019-06-19 18:31 UTC, Den4ik requested changes

2019-06-19 18:31 UTC, Den4ik commented on app/code/Magento/Sales/view/adminhtml/templates/order/create/coupons/form.phtml
> +        <?php endif; ?>
Could be simplified with
`if() {
} else {
}`

2019-06-19 18:36 UTC, Den4ik commented on app/code/Magento/Sales/view/adminhtml/templates/order/create/coupons/form.phtml
> +        <?php endif; ?>
Also may be make sense to do something like coupon form in cart: disabled input + button
![rqlno_2019-06-19_21-33-01](https://user-images.githubusercontent.com/1129623/59791133-171fda00-92da-11e9-9125-1901faa4a214.jpg)

2019-06-19 23:22 UTC, merged