Fix 19293 & 20434 - Create URL rewrites for all product visibilities
magento/magento2 pull request #23275
Opened 2019-06-14 19:17 UTC by dverkade

### Description

- Add URL rewrites when a product it saved, even if the product is set to "Not visible individually".
- Removed mass attribute event, since this is not longer necessary when all URL rewrites are generated for visible and invisible products.
- Deprecated related classes, to be removed in next major release.

### Fixed Issues 
1. magento/magento2#19293: Invisible products do not update url_rewrite properly
2. magento/magento2#20434: Product URL duplicate when changing visibility via mass action

### Manual testing scenarios
1. Add product with visibility "Not visible individually"
2. URL rewrites should be generated and stored in the url_rewrite table

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2019-06-15 13:41 UTC, sivaschenko requested changes
Hi @dverkade thanks for the correct approach investigation facilitation and a pull request!

Please fix the static and integration tests so that this pull request can be processed further.

@akaplya can you please take a look at this pull request and approve the change: URL rewrites will be created for not visible products. See the conversation related to this change in slack

2019-06-18 10:24 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
> + * @deprecated
Could you write some info why it was deprecated and what is/should be used instead? Such info will be really helpful during investigations

2019-06-18 10:24 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
> + * @deprecated
Could you write some info why it was deprecated and what is/should be used instead? Such info will be really helpful during investigations

2019-07-05 18:48 UTC, sidolov commented
@dverkade , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-07-15 11:01 UTC, orlangur commented
Great @dverkade! I didn't expect you will continue work on fixing behavior according to Piotr comment.

2019-09-22 22:24 UTC, orlangur commented
@magento run all tests

2019-09-23 16:19 UTC, sidolov commented
@piotrekkaminski could you please take a look and confirm logic changes? Thank you!

2019-09-26 22:07 UTC, orlangur commented
@sidolov Piotr already approved such logic in https://github.com/magento/magento2/pull/19294#issuecomment-502134714

2019-10-04 16:11 UTC, sidolov approved these changes

2019-10-04 16:12 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-6005](https://jira.corp.magento.com/browse/ENGCOM-6005) has been created to process this Pull Request

2019-10-09 11:24 UTC, engcom-Bravo commented
'Add URL rewrites when a product is saved, even if the product is set to "Not visible individually".' - doesn't work. Even more, once You have swapped the visibility of the product from Not Visible Individually (the product was initially created with) to Catalog, Search no appropriate record about it appears in Url Rewrites grid (table). Without the PR it would appear.

2019-10-09 11:29 UTC, dverkade commented
@engcom-Bravo don't know what you want me to do. The issue has been described and acknowledged. Change in behaviour has been accepted by Magento architects. So this PR needs to be processed and make it into the latest release ASAP. 

There's nothing to do from my side.

2019-10-09 11:51 UTC, engcom-Bravo commented
Excuse me @dverkade if I put out my thoughts not clearly enough. Please look at my updated previous post. Or probably I misunderstand You. So then please tell me if so. But as I see now the PR does not fix what it declares it will fix.

2020-02-06 19:24 UTC, lenaorobei commented
Hi @dverkade. This PR failed QA review. Could you please address comment from @engcom-Bravo?
Thanks.

2020-02-06 20:24 UTC, dverkade commented
@magento give me test instance

2020-02-06 20:24 UTC, magento-engcom-team commented
Hi @dverkade. Thank you for your request. I'm working on Magento instance for you

2020-02-06 20:25 UTC, magento-engcom-team commented
Hi @dverkade, here is your [new Magento instance](https://pr-23275.instances.magento-community.engineering).
Admin access: [https://pr-23275.instances.magento-community.engineering/admin_51fb](https://pr-23275.instances.magento-community.engineering/admin_51fb)
Login: `c6ddbd24` Password: `feafed7054a1`
Instance will be terminated in up to 3 hours.

2020-03-27 13:24 UTC, orlangur commented
I'll check this out locally.

2020-05-27 13:12 UTC, engcom-Charlie commented
Hi @dverkade, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-05-27 13:12 UTC, closed without merging