magento/magento2#10353 : Cant put id or data attribute on <img> tags …
magento/magento2 pull request #23302
Opened 2019-06-18 12:28 UTC by benathomeofchampions

…in the M2 wysiwyg.

Fixes issue whereby an ID attribute is added to an <img> via the WYSIWYG, and a proceeded base64 decode of the ID causes an exception.

This introduces a new method Base64.isBase64() and performs a check before trying to get an widget code from the ID.

### Description (*)
Manually adding an ID attribute to an <img> tag via the WYSIWYG / editor results in the ID being parsed for widget code using the window.atob, which throws an exception if the string is not valid base64.

### Fixed Issues (if relevant)

1. magento/magento2#10353: Cant put id or data attribute on <img> tags in the M2 wysiwyg.

### Manual testing scenarios (*)

1. Edit a page and add an image
2. Save the page
3. Edit the markup and add an ID attribute to the <img>
4. Save the page, without seeing an exception.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-18 12:28 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23302) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23302) before we can accept your contribution.<br/>

2019-06-23 16:02 UTC, torhoehn commented
@benathomeofchampions Please fix failing Functional and Static Tests.

2019-10-04 20:01 UTC, sidolov commented
@magento run all tests

2019-10-04 20:01 UTC, sidolov approved these changes

2019-10-04 20:02 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-6008](https://jira.corp.magento.com/browse/ENGCOM-6008) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-08 10:37 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-10-08 10:39 UTC, engcom-Golf commented
@magento run ALL tests

2019-10-08 10:40 UTC, engcom-Golf commented
@magento run all tests

2019-10-09 06:00 UTC, engcom-Golf commented
Hi @benathomeofchampions could you please sign in new cla ?

2019-10-09 08:08 UTC, engcom-Golf commented on lib/web/mage/adminhtml/wysiwyg/tiny_mce/plugins/magentowidget/editor_plugin.js
>                              widgetCode = Base64.idDecode(attributes.id);
Hi @benathomeofchampions thank you for your contribution, after small fixes where you forgot to add your method in min.js file, we found that tests fail with insert widget in WYSIWYG edit could you please see failed test and fix them? the problem is that when you want to add 2 widgets with catalog product list the second widget is not decoding.
![DeepinScreenshot_select-area_20191009110735](https://user-images.githubusercontent.com/51681547/66463093-1081c200-ea85-11e9-885c-d68b5dd62826.png)

2019-10-09 08:10 UTC, engcom-Golf requested changes
Hi, @benathomeofchampions thank you for pull request, please see my review comments.

2019-12-09 21:06 UTC, krzksz commented
Closing this merge request due to inactivity. Feel free to reopen if you wish to continue working on this issue.

2019-12-09 21:06 UTC, closed without merging