Use class name as type hint instead of self.
magento/magento2 pull request #23300
Opened 2019-06-18 12:21 UTC by dcabrejas

### Description (*)
Use class name as type hint instead of `self`. `self` breaks code generator when a preference is defined.

### Fixed Issues (if relevant)

1. magento/magento2#22769: "Creating a preference for category product indexer breaks setup:di:compile"

### Manual testing scenarios (*)
1. Create a preference for \Magento\Catalog\Model\Indexer\Category\Product\Action\Full in a custom module
2. Run bin/magento setup:di:compile
3. There is no PHP fatal error anymore.

### Questions or comments
I am going to try and work out a solution to the real problem here which should allow us to still use the `self` keyword and use preferences/code generation at the same time. That would be in a different PR though.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-19 09:10 UTC, aleron75 approved these changes

2019-06-19 09:11 UTC, magento-engcom-team commented
Hi @aleron75, thank you for the review.
[ENGCOM-5309](https://jira.corp.magento.com/browse/ENGCOM-5309) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-19 09:11 UTC, magento-engcom-team commented
@dcabrejas thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-06-19 09:30 UTC, orlangur requested changes
This class is perfectly valid, interception mechanism must be fixed instead.

2019-06-20 15:41 UTC, dcabrejas commented
Hi @orlangur 

Please see my comment on the PR description about this being just a fix to the issue users have reported. While I agree more thought is required to provide a generic fix that allows code to typehint self as a return parameter. I believe that can be done as a separate PR.

2019-06-21 02:11 UTC, orlangur commented
@dcabrejas sure.

> That would be in a different PR though.

Please work on such PR and this change is not needed actually.

2019-06-21 13:19 UTC, dcabrejas commented
Hi @sivaschenko 

What is your opinion about this? We discussed this at meet Magento and it was decided this should be fixed in this way.

2019-06-21 14:35 UTC, orlangur commented
Similar poor attempt of "fix" was performed in https://github.com/magento/magento2/pull/21775#issuecomment-477912848.

Again: indexer code MUST NOT be changed, interception mechanism is what actually needs to be fixed.

2019-06-21 14:37 UTC, orlangur commented
@dcabrejas there is even a patch suggestion in https://github.com/magento/magento2/issues/22769#issuecomment-499387177, so, please don't waste our time on hacks instead of proper fixes.

2019-06-21 15:46 UTC, DrewML commented
![image](https://user-images.githubusercontent.com/5233399/59934355-f27a4e00-9410-11e9-9cd7-8b380ad8f714.png)


@orlangur This is an incredibly unprofessional way to conduct yourself, as a contributor, but even more so as a maintainer.

Technical disagreements are fine, but suggesting that another contributor's work is a waste of time is completely out of line. I'd recommend taking a break and re-reviewing the Code of Conduct for this project - https://github.com/magento/magento2/wiki/Magento-Code-of-Conduct

2019-06-22 11:04 UTC, orlangur commented
@DrewML, sorry, I wasn't specific enough and my English may sound not how it was intended to sound to native speaker. I just tried to guide contributor in a right direction to avoid waste of efforts by doing a temporary fix, then a proper one, then reverting initial unneeded change. This can be even a bigger trouble if release occur between such connected pull requests. https://github.com/magento/magento2/pull/23300#issuecomment-504448567 is a good example where we faced with similar changes and elaborated a more universal fix.

I do appreciate every contributor work and trying to help to not waste contributor efforts on changes which could be avoided, this is what I meant by "our wasted time" - we are all on the same boat, there is no distinction between contributors, maintainers or even EngCom team members on this aspect.

Thanks for pointing out, I'll take an additional look into Code of Conduct and do my best to avoid such situations in the future.

@dcabrejas sorry that I didn't pick the right words to convey my point and could decrease your enjoyment of contributing to Magento Open Source. I'm taking part in the Magento Contribution Day today and will reach out to @sivaschenko directly.

2019-06-22 12:16 UTC, sivaschenko commented
@orlangur we have discussed this issue with @dcabrejas  at the Meet Magento UK contribution day. As there is no proved solution for generator fix, and such fix may require a substantial amount of time to implement and tests, we decided to apply a local fix to this file and postpone the generator fix.

In case a pull request will be created, tested and delivered within the current release with the fix described in https://github.com/magento/magento2/pull/23300#issuecomment-504448567 - that solution looks more preferable for me.

2019-06-22 14:55 UTC, orlangur commented
@sivaschenko thanks, seems we are on the same page taking into consideration there is a bunch of time till `2.3.3` contributions freeze. I'll try the patch in action.

2019-08-14 19:59 UTC, sidolov approved these changes

2019-08-14 20:01 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5624](https://jira.corp.magento.com/browse/ENGCOM-5624) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-15 13:38 UTC, joni-jones commented
As @orlangur mentioned, the fix should be on the code generation level (internal ticket MC-17251) but should not change `Magento\Catalog\Model\Indexer\Category\Product\Action\Full` as it's a valid class.

Another note, preferences should not be used for classes, only for interfaces.

2019-08-27 18:11 UTC, merged