magento/magento2#23074: update correct product URL rewrites after changing category url key
magento/magento2 pull request #23309
Opened 2019-06-18 14:30 UTC by sta1r

### Description (*)

In a multi-store website, when a category URL key is updated, we will try to update related product URL rewrites in addition to the category's own URL. However the problem is that sometimes we are not updating all the rewrite rules for all the stores that products belong to.

The problem is that if we simply look up the store id from the `$category`, we will get the store id from the last loop [here](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogUrlRewrite/Model/CategoryUrlRewriteGenerator.php#L127) and miss all the other store ids that the category (and the product) may belong to. Hence we need to once again loop through category store ids when regenerating product rewrite urls.

### Fixed Issues (if relevant)

1. magento/magento2#23074: Magento 2.3.1 - URL rewrite rules are not creating for product after update url key

### Manual testing scenarios (*)

1. Set up a multi-store instance
2. Create a category with one product
3. Go to the category in the admin
4. Update the URL key of category
5. Save the category

URL rewrites will be regenerated for all the stores that the product belongs to.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-18 14:30 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23309) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23309) before we can accept your contribution.<br/>

2019-06-18 15:44 UTC, sta1r commented
@magento give me 2.3-develop instance

2019-06-18 15:45 UTC, magento-engcom-team commented
Hi @sta1r. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-06-18 15:45 UTC, magento-engcom-team commented
Hi @sta1r, here is your [Magento instance](https://i-23309-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23309-2-3-develop.instances.magento-community.engineering/admin](https://i-23309-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-06-19 20:52 UTC, torhoehn requested changes
@sta1r Thanks for contribution! Could you please fix the failing Unit test?

2019-06-20 21:06 UTC, torhoehn approved these changes

2019-06-20 21:08 UTC, magento-engcom-team commented
Hi @torhoehn, thank you for the review.
[ENGCOM-5330](https://jira.corp.magento.com/browse/ENGCOM-5330) has been created to process this Pull Request
:eight_spoked_asterisk: @torhoehn, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-21 10:50 UTC, engcom-Delta commented
:heavy_check_mark: QA Passed

2019-06-21 22:26 UTC, merged