magento/magento-2#23222: setup:upgrade should return failure when app…
magento/magento2 pull request #23310
Opened 2019-06-18 14:49 UTC by ProcessEight

app:config:import failed: Added logic to throw RuntimeException if app:config:import returns failure error code

This PR adds logic which detects if the return code of the app:config:import command returns an error code greater than zero and if so, throws a RuntimeException.

### Description (*)

These CLI commands are used for deployments. If there is an error on deployment, the command should stop. But without an error code we cannot stop. This PR adds the error code.

### Fixed Issues (if relevant)

1. magento/magento2#23222: setup:upgrade should return failure when app:config:import failed 

### Manual testing scenarios (*)

1. Add an Exception to Magento\Deploy\Console\Command\App\ConfigImport\Processor
after Line 114
```php
 if (!$importers || !$this->changeDetector->hasChanges()) {
              throw new \Exception('Test'); // added line
```
2. Run `bin/magento setup:upgrade`
3. Verify that the `bin/magento setup:upgrade` command is terminated by the `RuntimeException`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-19 05:44 UTC, ihor-sviziev requested changes
Hi @ProcessEight,
Could you cover your change with test in order not to make regression there in future?

2019-07-04 10:23 UTC, ihor-sviziev approved these changes

2019-07-04 10:24 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5395](https://jira.corp.magento.com/browse/ENGCOM-5395) has been created to process this Pull Request

2019-07-04 14:38 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-07-05 23:36 UTC, merged