23424: fixed search with 0
magento/magento2 pull request #23427
Opened 2019-06-26 14:20 UTC by jeysmook

### Description (*)
Fixed search with 0

### Fixed Issues (if relevant)
1. #23424 

### Manual testing scenarios (*)
1. Go to admin panel
2. Go to Catalog -> Products
3. Search products by 0

2019-06-26 14:20 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23427) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23427) before we can accept your contribution.<br/>

2019-06-26 15:24 UTC, VladimirZaets requested changes

2019-06-26 15:24 UTC, VladimirZaets commented on app/code/Magento/CatalogSearch/Ui/DataProvider/Product/AddFulltextFilterToCollection.php
> +        if (isset($condition['fulltext']) && 0 !== strlen($condition['fulltext'])) {
Hi, @jeysmook, thanks for collaboration. Please change the condition to `(string)$condition['fulltext'] !== ''`.

2019-06-26 15:24 UTC, VladimirZaets commented on app/code/Magento/Ui/Component/Filters/Type/Search.php
> +        if (0 !== strlen($value)) {
The same here

2019-07-05 10:56 UTC, sivaschenko approved these changes

2019-07-05 10:57 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5402](https://jira.corp.magento.com/browse/ENGCOM-5402) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-07-05 10:57 UTC, magento-engcom-team commented
@jeysmook thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-07-05 11:51 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-07-05 23:36 UTC, merged