Fix alias in grid massaction for eav collections
magento/magento2 pull request #23452
Opened 2019-06-27 15:48 UTC by thomas-kl1

Related to M2.2.x: MAGETWO-96957
Related to M2.3.x: MAGETWO-98617

### Description (*)
Impossible to use the massaction on Vanilla grid with an EAV collection.

### Fixed Issues (if relevant)

1. magento/magento2#23451: MAGETWO-96957 introduce a new bug

### Manual testing scenarios (*)

See related issue #23451

### Questions or comments

As all grids should be built with the ui component, this exception should never happen. However, many third-part extension still use the deprecated grid system.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-27 21:52 UTC, sidolov approved these changes

2019-06-27 21:53 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5367](https://jira.corp.magento.com/browse/ENGCOM-5367) has been created to process this Pull Request

2019-07-24 12:02 UTC, engcom-Foxtrot commented
@thomas-kl1, thank you for collaboration. Can you please provide strong motivation why this PR should be merged? It works fine with Product collection, but it's only because of \Magento\Catalog\Model\ResourceModel\Product\Collection::MAIN_TABLE_ALIAS value. I'm not sure if your solution will work in other cases.

2019-07-27 10:49 UTC, thomas-kl1 commented
Hi @engcom-Foxtrot 
No because it does not exists any public method to retrieve the alias for the mass action ID field.
So anyone who implements a collection with a specific alias cannot use the abstract massaction widget.
I'll be glad to apply changes in the PRs to fix this case. Actually I think the alias argument could be removed, as the alias could be directly concatenate in the field name. What do you think?

2019-09-18 12:01 UTC, thomas-kl1 commented
@sidolov Have you any updates? I've seen a similar PR, I don't know what the best and maintainable solution is. Can you advice?

2019-09-20 16:14 UTC, sidolov requested changes

2019-09-20 16:14 UTC, sidolov commented on app/code/Magento/Backend/Block/Widget/Grid/Massaction/AbstractMassaction.php
> +            $idsSelect->columns($this->getMassactionIdField(), $alias);
Will it work for both cases if we remove alias at all?

2019-09-24 08:39 UTC, thomas-kl1 commented
@magento give me test instance

2019-09-24 08:39 UTC, magento-engcom-team commented
Hi @thomas-kl1. Thank you for your request. I'm working on Magento instance for you

2019-09-24 08:40 UTC, magento-engcom-team commented
Hi @thomas-kl1, here is your [new Magento instance](https://pr-23452.instances.magento-community.engineering).
Admin access: [https://pr-23452.instances.magento-community.engineering/admin](https://pr-23452.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-09-30 19:29 UTC, sidolov approved these changes

2019-09-30 19:31 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5367](https://jira.corp.magento.com/browse/ENGCOM-5367) has been created to process this Pull Request

2019-10-08 19:17 UTC, merged