Issue 23376
magento/magento2 pull request #23470
Opened 2019-06-29 07:11 UTC by sanjay-github

### Description (*)

I have fixed the image upload issue for categories. Whenever an image is uploaded with same name , it will be renamed in target/main directory.

### Fixed Issues (if relevant)

1. #23376 : Category A image replaced by uploading to Category B
### Manual testing scenarios (*)

1. Please upload image with name let's say dummy.jpg in  category A
2. Take another image with the same name and upload the image to another category B.
3. Now observe images of both the categories A & B.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-29 07:11 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23470) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23470) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: sanjay-github<br/>:x: sanjaychaudhary1412

2019-08-19 18:55 UTC, sidolov requested changes

2019-08-19 18:55 UTC, sidolov commented on app/code/Magento/Catalog/Model/ImageUploader.php
> +    public function moveFileFromTmp($tmpImageName, $baseImageName)
Unfortunately, we are not allowed to modify public methods signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-09-03 17:02 UTC, sidolov commented
@sanjay-github , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-03 17:02 UTC, closed without merging