Removed editor from phone and zipcode
magento/magento2 pull request #23494
Opened 2019-06-29 11:26 UTC by kazim-krish

### Description (*)
- Removed editor field of Phone and ZIP from customer grid as it is dependable only on customer billing address. 

### Fixed Issues (if relevant)
1. #23467 : Removed Phone and ZIP field editor from customer grid.

2019-06-29 11:26 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23494) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23494) before we can accept your contribution.<br/>

2019-07-01 13:59 UTC, sivaschenko approved these changes

2019-07-01 14:01 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5378](https://jira.corp.magento.com/browse/ENGCOM-5378) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-07-01 14:01 UTC, magento-engcom-team commented
@kazim-krish thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-07-01 14:10 UTC, sivaschenko requested changes
@kazim-krish thanks for the pull request. Can you please check if any other fields on the customer grid should not be editable as well (take a look at https://github.com/magento/magento2/pull/23505)

2019-07-02 05:01 UTC, kazim-krish commented
@sivaschenko Thanks for helping me. I have removed all other fields on the customer grid that should not be editable. Requested review.

2019-07-02 11:34 UTC, sivaschenko approved these changes

2019-07-02 11:35 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5378](https://jira.corp.magento.com/browse/ENGCOM-5378) has been created to process this Pull Request

2019-07-02 12:31 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-07-05 21:45 UTC, merged