Update Helper.php
magento/magento2 pull request #23530
Opened 2019-07-01 19:13 UTC by WJdeBaas

Remove user-input type-casting.

### Description
Link attributes like "position" should be allowed to be any of the types "integer", "decimal" or "varchar" in custom modules

### Fixed Issues (if relevant)
customization restrictions

2019-07-04 10:31 UTC, aleron75 commented
Hello @WJdeBaas, first of all, thank you for your contribution.

>attributes like "position" should be allowed to be any of the types

please, can you provide a use case for types other than `int`? We are just trying to understand under which circumstances we could need a `varchar` position and how it could be used.

Thank you!

2019-07-04 10:34 UTC, aleron75 commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper.php
> +        Escaper $escaper,
Let's try to make this change as backward compatible as possible, adding new constructor parameter as **last** and **optional**, with property initialized with object manager if the parameter is not passed.

e.g.

    $this->escaper = $escaper ?: ObjectManager::getInstance()->get(Escaper::class);

2019-07-04 12:05 UTC, WJdeBaas commented
Hi Alessandro,

I'll try to explain under which circumstances we could need a varchar
position and how it could be used.

Here's an example: https://www.zandri.nl/catalog/product/view/id/133813

On this page you'll see an exploded view drawing of a scooter carburetor,
where the articles are numbered, but these numbers aren't always typical
integers.
For example: there is 12 en 12-1, and even other drawings can have other
codes like 3a, 3b and 3c for instance.
There are also example where positions are devided with a pipe-symbol (|),
to make it possible to list the same SKU on several different positions in
the drawing.

This functionality has to be migrated to Magento 2, and after some research
and testing I found it's quite easy to reuse and modify parts of the
standard Magento 2 implementations for linked articles like used for
Crosssell and Upsell articles.
But at the moment it's not possible to save divergent values because the
backendcontroller casts the user input, even if the positions' data_type is
declared as a varchar attribute, and the input is saved into the
'catalog_product_link_attribute_varchar' db-table.

In my opinion the variable casting shouldn't be done in the controller, but
in the repository model, where it can check the attributes' type (int,
decimal or varchar), and cast it accordingly just before the data is saved.
I agree with you on the backward compatibility and use the ObjectManager in
case the Escaper class is not passed as a parameter, although the Escaper
class could also be moved the the repository model.

Op do 4 jul. 2019 om 12:35 schreef Alessandro Ronchi <
notifications@github.com>:

> *@aleron75* commented on this pull request.
> ------------------------------
>
> In
> app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper.php
> <https://github.com/magento/magento2/pull/23530#discussion_r300338649>:
>
> > @@ -119,6 +124,7 @@ public function __construct(
>          \Magento\Catalog\Model\Product\Initialization\Helper\ProductLinks $productLinks,
>          \Magento\Backend\Helper\Js $jsHelper,
>          \Magento\Framework\Stdlib\DateTime\Filter\Date $dateFilter,
> +        Escaper $escaper,
>
> Let's try to make this change as backward compatible as possible, adding
> new constructor parameter as *last* and *optional*, with property
> initialized with object manager if the parameter is not passed.
>
> e.g.
>
> $this->escaper = $escaper ?: ObjectManager::getInstance()->get(Escaper::class);
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/23530?email_source=notifications&email_token=ACSGL3HXESWAKW6RA3364VTP5XG6NA5CNFSM4H4VGEL2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5QD7IA#pullrequestreview-257965984>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACSGL3DC37WQP3I6KYDB3ELP5XG6NANCNFSM4H4VGELQ>
> .
>

2019-07-04 12:52 UTC, aleron75 commented
Thank you @WJdeBaas for your explanation, it's clear.

My only concern is whether this change should be part of the core or rather should be part of a customized implementation.

Let me check whether we can involve the core team into this discussion.

My best.

2019-07-04 13:55 UTC, sivaschenko requested changes
Hi @WJdeBaas thanks for the pull request!

Unfortunately, we can allow only `int` type for link position as this is part of the API: https://github.com/magento/magento2/blob/5588999a108619d09835a2eecbc9579a9e6f27af/app/code/Magento/Catalog/Api/Data/ProductLinkInterface.php#L78

To achieve the desired behaviour you need to extend Magento functionality possibly using an extension attribute for `ProductLinkInterface`

2019-07-04 14:39 UTC, WJdeBaas commented
Hi Sergii, Alessandro,

Is it really impossible to apply a minor update to the API to gain more
flexibility  ?
After all, It's "software", not ferroconcrete or titanium ...

    /**
     * Get linked item position
     *
     * @return int|float|string
     */
    public function getPosition();

    /**
     * Set linked item position
     *
     * @param int|float|string $position
     * @return $this
     */
    public function setPosition($position);

Kind regards,
Willem-Jan

Op do 4 jul. 2019 om 15:57 schreef Sergii Ivashchenko <
notifications@github.com>:

> *@sivaschenko* requested changes on this pull request.
>
> Hi @WJdeBaas <https://github.com/WJdeBaas> thanks for the pull request!
>
> Unfortunately, we can allow only int type for link position as this is
> part of the API:
> https://github.com/magento/magento2/blob/5588999a108619d09835a2eecbc9579a9e6f27af/app/code/Magento/Catalog/Api/Data/ProductLinkInterface.php#L78
>
> To achieve the desired behaviour you need to extend Magento functionality
> possibly using an extension attribute for ProductLinkInterface
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/23530?email_source=notifications&email_token=ACSGL3B3LYM4LMLUQVFXNMTP5X6URA5CNFSM4H4VGEL2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5Q2ORI#pullrequestreview-258058053>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACSGL3H7NOSPR75RE66PGYTP5X6URANCNFSM4H4VGELQ>
> .
>

2019-09-23 16:26 UTC, sidolov commented
@WJdeBaas , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-23 16:26 UTC, closed without merging