Option to send email from the stores email address using sendFriend
magento/magento2 pull request #23591
Opened 2019-07-05 22:21 UTC by NetStorm84

### Description (*)
The Magento\SendFriend module sends the email using the email address entered by the user, this can be an issue when using an SMTP server that requires the senders email address to be authenticated. This PR adds the option for the store owner to set the email to be sent from the General Emaill address of the store instead of the submitted email address, the ReplyTo email address is then set to the submitted email address of the user.

### Manual testing scenarios (*)

1. Go to Stores>Configuration>Catalog>Email to a Friend and set `Email is sent from store` to Yes
2. Visit any product page
3. Click Email and sign in/create account if nesscary
4. Fill out the form and click `Send Email`

The email received will have the stores email as the From address and users submitted email as the Reply To address.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2019-07-05 22:21 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23591) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23591) before we can accept your contribution.<br/><hr/>**Dan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-07-05 22:27 UTC, NetStorm84 commented
give me test instance

2019-07-05 22:31 UTC, NetStorm84 commented
@magento give me test instance

2019-07-05 22:31 UTC, magento-engcom-team commented
Hi @NetStorm84. Thank you for your request. I'm working on Magento instance for you

2019-07-05 22:32 UTC, magento-engcom-team commented
Hi @NetStorm84, here is your [new Magento instance](https://pr-23591.instances.magento-community.engineering).
Admin access: [https://pr-23591.instances.magento-community.engineering/admin](https://pr-23591.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-07-08 00:38 UTC, kalpmehta commented on app/code/Magento/SendFriend/Model/SendFriend.php
> +        $this->_transportBuilder->setReplyTo(
If this is coming from the general website user, I think we should validate the email format and escape name field before setting it to Reply-To.

2019-08-23 15:39 UTC, sidolov requested changes

2019-08-23 15:39 UTC, sidolov commented on app/code/Magento/SendFriend/Model/SendFriend.php
> +    public function setReplyTo($sender)
Unfortunately, we are not able to add new public methods to the @api classes according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-23 15:39 UTC, sidolov commented on app/code/Magento/SendFriend/Helper/Data.php
> +    public function getStoreEmail($store = null)
Unfortunately, we are not able to add new public methods to the @api classes according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-23 15:39 UTC, sidolov commented on app/code/Magento/SendFriend/Helper/Data.php
> +    public function isSentFromStore($store = null)
Unfortunately, we are not able to add new public methods to the @api classes according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-09-06 14:26 UTC, sidolov commented
@NetStorm84 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-06 14:26 UTC, closed without merging