Resolved displaying customer full name on admin order detail page
magento/magento2 pull request #23629
Opened 2019-07-09 06:50 UTC by kazim-krish

### Description (*)
#23627 : Fixed displaying customer full name on admin order detail page.

### Fixed Issues (if relevant)
1. #23627 : Fixed displaying customer full name on admin order detail page.

### Manual testing scenarios (*)
1. Registered a new customer will prefix, first name, middle name, last name, and suffix.
2. Placed an order with registered customer and noted that full customer name along with prefix and suffix is rendered on admin order detail page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-09 19:40 UTC, orlangur requested changes
@kazim-krish please get rid of unnecessary spaces in case some of methods return empty string.

Can we reuse some existing logic or create a new class encapsulating it also?

2019-07-11 17:12 UTC, gwharton commented
Shouldn't any proposed issue here respect the Magento Settings 

```
Stores -> Configuration -> Customers -> Customer Configuration -> Name and Address Options -> Show Prefix
Stores -> Configuration -> Customers -> Customer Configuration -> Name and Address Options -> Show Middle Name
Stores -> Configuration -> Customers -> Customer Configuration -> Name and Address Options -> Show Suffix
```

2019-08-14 15:36 UTC, sidolov commented
@kazim-krish , please, see comment from @gwharton

2019-08-16 06:25 UTC, kazim-krish commented
@sidolov @gwharton: How about if Order has customer prefix or customer middle name or customer suffix but Magento Customer Configuration -> Show Prefix or -> Show Middle Name or -> Show Suffix is disabled. If we keep with respect to Magento Customer configuration on admin order detail page, it would not show prefix or middle name or suffix if set off in customer configuration.
Case: Firstly Magento customer configuration to show prefix and middle name are on, the customer has already placed many orders from the frontend (that have a prefix and middle name in address). Later admin user disabled Magento customer configuration to show prefix and middle name. This will restrict current frontend customer to enter a prefix and middle name and also it will not show prefix and middle name to the earlier order placed on the admin order detail page.

2019-08-16 21:09 UTC, sidolov commented
@kazim-krish it's expected behavior if you disable something the user hasn't the ability to use that and it does not matter if such info were collected before.

2019-09-04 17:11 UTC, sidolov requested changes

2019-09-04 17:11 UTC, sidolov commented on app/code/Magento/Sales/Model/Order.php
> +    private function isAllowShowPrefix()
Please, add strict types

2019-09-04 17:11 UTC, sidolov commented on app/code/Magento/Sales/Model/Order.php
> +    private function isAllowShowMiddlename()
Please, add strict types

2019-09-04 17:11 UTC, sidolov commented on app/code/Magento/Sales/Model/Order.php
> +    private function isAllowShowSuffix()
Please, add strict types

2019-09-04 17:11 UTC, sidolov commented on app/code/Magento/Sales/Model/Order.php
> +        return false;
Please, return null instead of false

2019-09-04 17:11 UTC, sidolov commented on app/code/Magento/Sales/Model/Order.php
> +        return false;
Please, return null instead of false

2019-09-04 17:11 UTC, sidolov commented on app/code/Magento/Sales/Model/Order.php
> +        return false;
Please, return null instead of false

2019-09-23 18:28 UTC, sidolov commented
@kazim-krish I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-23 18:28 UTC, closed without merging