Resolved issue for sample file and links for unsalable downloadable products
magento/magento2 pull request #23660
Opened 2019-07-11 06:12 UTC by kazim-krish

# Description (*)
#23638 : Resolved issue for unaccessible sample links and files which are unsalable downloadable products.

### Fixed Issues (if relevant)
1. #23638 : Reviewed salable product condition checks, and removed those condition checks for downloadable products.

### Manual testing scenarios (*)
1. Created a downloadable product with sample links and files.
2. Made the downloadable product unsalable.
3. Reviewed on frontend and noted that sample links are available now.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-14 22:28 UTC, edenduong commented
@magento give me test instance

2019-07-14 22:28 UTC, magento-engcom-team commented
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

2019-07-14 22:29 UTC, magento-engcom-team commented
Hi @edenduong, here is your [new Magento instance](https://pr-23660.instances.magento-community.engineering).
Admin access: [https://pr-23660.instances.magento-community.engineering/admin](https://pr-23660.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-08-07 19:48 UTC, sidolov requested changes

2019-08-07 19:48 UTC, sidolov commented on app/code/Magento/Catalog/view/frontend/templates/product/view/form.phtml
> +            <?php elseif ($_product->getTypeId() == 'downloadable' &&
All changes related to the Downloadable product should be int the Downloadable module instead of Catalog

2019-08-21 17:32 UTC, sidolov commented
@kazim-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-21 17:32 UTC, closed without merging