Moved Zero Subtotal Checkout Payment Settings
magento/magento2 pull request #23679
Opened 2019-07-12 15:17 UTC by textarea

### Description (*)
"Zero Subtotal Checkout" payment method settings disappear if "Offline Payments" module is disabled.

### Fixed Issues (if relevant)
1. magento/magento2#23678: Can't see "Zero Subtotal Checkout" payment method settings if "Offline Payments" module is disabled

### Manual testing scenarios (*)
1. php bin/magento module:disable Magento_OfflinePayments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-12 15:18 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23679) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23679) before we can accept your contribution.<br/><hr/>**Andrea Parmeggiani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-07-15 21:27 UTC, sidolov commented
Hi @textarea  , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

2019-07-16 05:46 UTC, textarea commented
Hi @sidolov , email added. Thanks.

2019-07-16 08:36 UTC, orlangur approved these changes

2019-07-16 08:37 UTC, magento-engcom-team commented
Hi @orlangur, thank you for the review.
[ENGCOM-5452](https://jira.corp.magento.com/browse/ENGCOM-5452) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-07-17 08:12 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-07-19 12:52 UTC, sivaschenko requested changes
Please move the related translation from `OfflinePayments` to `Payment` module as well

2019-07-19 16:23 UTC, textarea commented
Done, thanks.

2019-07-21 21:39 UTC, sivaschenko approved these changes

2019-07-21 21:40 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5452](https://jira.corp.magento.com/browse/ENGCOM-5452) has been created to process this Pull Request

2019-07-22 09:00 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-07-27 14:57 UTC, merged