Resolve "Discount Amount" field is validated after the page load without any action from user in Create New Catalog Rule form issue23777
magento/magento2 pull request #23779
Opened 2019-07-19 06:42 UTC by edenduong

### Description (*)

1. magento/magento2#23777: Resolve "Discount Amount" field is validated after the page load without any action from user in Create New Catalog Rule form

Reason: "Discount Amount" field is validated when page load because it depends on "Apply" fields. It will validate when the apply field change.

Solution: Just add the default value for "Discount Amount" is 0 (Similarly the Action fieldset of "Cart Price Rule")

### Fixed Issues (if relevant)

1. magento/magento2#23777: "Discount Amount" field is validated after the page load without any action from user in Create New Catalog Rule form

### Manual testing scenarios (*)

1. In back end, go to Marketing -> Catalog Price Rule -> Add New Rule
2. Scroll to the Action fieldset
3. See the " Discount Amount" Field

Result:
1. Normal field, no error when page loads.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-19 07:46 UTC, Stepa4man commented
Hi @edenduong  thank you for your contribution.

We already have similar [pull request](https://github.com/magento/magento2/pull/23480) for this issue. 
Not sure that the author will continue work.

I just copy my comment from that PR here:
Adding default value is not actually the best solution. We don't need zero here. Otherwise, we need a user to pay attention to this field. Better find out why validation fires during page rendering instead of validating by hitting the save button?

I see you are a cool contributor and I would appreciate if you'll investigate and provide a better solution here.

Thanks.

2019-07-19 07:47 UTC, Stepa4man submitted a review, later dismissed
Hi @edenduong thank you for your contribution.

We already have similar pull request for this issue.
Not sure that the author will continue work.

I just copy my comment from that PR here:
Adding default value is not actually the best solution. We don't need zero here. Otherwise, we need a user to pay attention to this field. Better find out why validation fires during page rendering instead of validating by hitting the save button?

I see you are a cool contributor and I would appreciate if you'll investigate and provide a better solution here.

Thanks.

2019-07-19 07:48 UTC, Stepa4man requested changes
Please see my comment. Thanks

2019-07-19 07:48 UTC, magento-engcom-team commented
Hi @Stepa4man, thank you for the review.
[ENGCOM-5467](https://jira.corp.magento.com/browse/ENGCOM-5467) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-07-19 07:56 UTC, edenduong commented
@Stepa4man: Thank you for your feedback. I will find other solution :) I suggest the default value for the form because I see in the salerule, it also fill the default 0.

Thank you very much. :)

2019-07-19 08:26 UTC, Stepa4man commented
> @Stepa4man: Thank you for your feedback. I will find other solution :) I suggest the default value for the form because I see in the salerule, it fill the default 0.
> 
> Thank you very much. :)

@edenduong From the user experience adding a predefined value of the most important field in Rule form is not a pretty good solution. 

Sometimes merchant creates a lot of rules one by one manually and this routine could cause some unfilled form fields.
If merchant creates the rule and forget to fill discount amount I believe he would appreciate validation, that this field is empty instead of saving 0 discount accidentally.

Not everything that we have already done in Magento is the best solution:)
That's why we are here! To make Magento great again!

2019-07-19 09:30 UTC, edenduong commented
@Stepa4man:  I have changed the code. Now I think it 's OK :)

Reason: The field "Apply" trigger the onChange event when the page load.

Because field "Apply hasn't no default value. The first value of the select will be displayed

![image](https://user-images.githubusercontent.com/8234209/61525087-f1edcb00-aa41-11e9-9183-32e13fb027a9.png)

 it will trigger the "OnChange" event => callback function run => validate field.

2019-07-20 01:05 UTC, edenduong commented
Hello @Stepa4man :

I have just changed the source code.
When the page loading, I see the function: 

`changed = !utils.compare(rules, this.validation).equal;`

try to log it:

![image](https://user-images.githubusercontent.com/8234209/61572248-b6481500-aac4-11e9-9157-6b517cbea9f0.png)

Because the "discount_amount" in the xml field has the default validate (required-entry) doesn't match with the default  "Apply" field "Apply as percentage of original" (required-entry, validate-number-range 0-100) so that field was validated after the page load. So we should add the  "validate-number-range 0-100" to "discount_amount" default validate. It will match and no-validation anymore :)

2019-07-21 09:04 UTC, Stepa4man commented
@magento give me test instance

2019-07-21 09:04 UTC, magento-engcom-team commented
Hi @Stepa4man. Thank you for your request. I'm working on Magento instance for you

2019-07-21 09:05 UTC, magento-engcom-team commented
Hi @Stepa4man, here is your [new Magento instance](https://pr-23779.instances.magento-community.engineering).
Admin access: [https://pr-23779.instances.magento-community.engineering/admin](https://pr-23779.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-07-21 09:21 UTC, Stepa4man approved these changes
Good job, @edenduong. Thanks for your effort!

2019-07-21 09:22 UTC, magento-engcom-team commented
Hi @Stepa4man, thank you for the review.
[ENGCOM-5467](https://jira.corp.magento.com/browse/ENGCOM-5467) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-07-22 07:10 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-07-27 14:57 UTC, merged