[Fixed] no autofocus in invalid field when collapse is closed
magento/magento2 pull request #23796
Opened 2019-07-19 21:04 UTC by iflam

### Description (*)

If a collapse is open and a field inside displays an error message (i.e. 'Please enter a valid number in this field', the collapsible is opened.
If there are multiple collapsibles to open, the cursor focuses on the first errored input.

### Fixed Issues (if relevant)

1. magento/magento2#23765: No auto focus in the invalid field if the fieldset collapse is closed

### Manual testing scenarios (*)

1. Go to Store->Configuration->Catalog->Inventory
2. Open Collapse "Product Stock Options"
3. Fill "ggggggg" into "Maximum Qty Allowed in Shopping Cart"
4. Close collapse "Product Stock Options" Fieldset
5. Click "Save"
6. Repeat 1-5, but also fill "ggggg" into any other text-input fields.

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-19 21:04 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23796) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23796) before we can accept your contribution.<br/>

2019-08-15 21:44 UTC, VladimirZaets commented on lib/web/mage/backend/validation.js
> +                    $('[data-toggle=dropdown].active').trigger('open.dropdown');
Hi @iflam. Thanks for collaboration. 
Here is you try to get an active dropdown, but we can have a case when we have few active dropdowns on the page, so it isn't fully correct.

2019-08-15 21:46 UTC, VladimirZaets commented on lib/web/mage/backend/validation.js
> +                    let first = true;
Magento support just ES5, `let` variables it is the feature of ES6, so currently we shouldn't use it. Please use `var` instead of `let` or `const`

2019-08-15 21:51 UTC, VladimirZaets commented on lib/web/mage/backend/validation.js
> +                    $('.section-config').each(function(){
Can you please explain what you try to do here?
For my point of view, all that we should do in this case it's find first element (that already did here `$(this.errorList.length && this.errorList[0].element || [])`) and check is this field inside of collapsible panel or not. If yes, check is collapsible panel is opened and if not - open this panel

2019-08-15 21:52 UTC, VladimirZaets requested changes
Hi @iflam. Thanks for collaboration. Please check code review comments.

2019-08-30 13:40 UTC, sidolov commented
@iflam , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-30 13:40 UTC, closed without merging