Fixed #23290 ./bin/magento config:show returns "Configuration for path: '...' doesn't exist" if config value equals to 0 or empty string
magento/magento2 pull request #23806
Opened 2019-07-21 19:14 UTC by shikhamis11

Fixed #23290 ./bin/magento config:show returns "Configuration for path: '...' doesn't exist" if config value equals to 0 or empty string 

### Preconditions (*)
1. Magento 2.3.1
2. Create module `Vendor_Module`
3. Create `etc/config.xml` in created module `Vendor_Module` with new config path `default/vendor_module/general/value` with value `0` or `''` (empty string)

### Steps to reproduce (*)
1. Open magento cli and run command `./bin/magento config:show vendor_module/general/value`

### Expected result (*)
1. Should return `0` or `''` (empty string)

### Actual result (*)
1. Command returns `Configuration for path: "vendor_module/general/value" doesn't exist`

I think it happens because there `<magento_root>/vendor/magento/module-config/Console/Command/ConfigShowCommand.php:153` magento checks if value is empty and if it actualy is the error message is shown. But empty value does not mean that path does not exist. So we should check if path exist in different method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-21 21:39 UTC, shikhamis11 commented
@magento run Static Tests build

2019-08-01 17:53 UTC, shikhamis11 commented
@pmclain , Please review the pull request

2019-08-09 18:17 UTC, sivaschenko requested changes
Hi @shikhamis11 thanks for the pull request! Please see the review comments

2019-08-09 18:17 UTC, sivaschenko commented on app/code/Magento/Config/App/Config/Source/RuntimeConfigSource.php
> +        return $data->getData($path);
For better backward compatibility I'd do the following:
```suggestion
        return $data->hasData($path) ? $data->getData($path) : [];
```
Also please correct the `return` annotation to `@return mixed`

2019-08-09 18:17 UTC, sivaschenko commented on app/code/Magento/Config/Console/Command/ConfigShowCommand.php
> +            if ($configValue == null && empty($configValue)) {
`empty` php function is returning true for both `null` and `0` arguments, so I'd check if `$configValue` is an empty array considering `RuntimeConfigSource::get` implementation
```suggestion
            if (is_array($configValue) && empty($configValue)) {
```

2019-08-12 15:06 UTC, sivaschenko approved these changes

2019-08-12 15:07 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-5599](https://jira.corp.magento.com/browse/ENGCOM-5599) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-12 15:08 UTC, sivaschenko requested changes
@shikhamis11 thanks for updates, code looks fine, the only thing is the tests have to be adjusted to changes

2019-08-27 15:32 UTC, sidolov commented
@shikhamis11 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-27 15:32 UTC, closed without merging