Standardize the array structure for the getAttributes result
magento/magento2 pull request #23818
Opened 2019-07-22 13:28 UTC by thomas-kl1

The scope of this pull request is to fix two issues in the `\Magento\Framework\Model\EntitySnapshot` package. It makes more convenient the results of  `getAttributes`.

### Description (*)
The `getAttributes` method of the `\Magento\Framework\Model\EntitySnapshot\AttributeProviderInterface` has no standardized structure in its available implementations.  
`\Magento\Framework\Model\EntitySnapshot\AttributeProvider` deal with a dictionary where `\Magento\Eav\Model\AttributeProvider` returns a simple list of attribute code.
I have assumed that the results should be a list of field (as described in the methods description).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-15 21:33 UTC, sidolov requested changes

2019-08-15 21:33 UTC, sidolov commented on app/code/Magento/Eav/Model/AttributeProvider.php
> +    public function getAttributes($entityType): array
Unfortunately, we are not allowed to change public method signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-15 21:33 UTC, sidolov commented on lib/internal/Magento/Framework/Model/EntitySnapshot.php
> +    public function registerSnapshot($entityType, $entity): void
Unfortunately, we are not allowed to change public method signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-15 21:33 UTC, sidolov commented on lib/internal/Magento/Framework/Model/EntitySnapshot.php
> +    public function isModified($entityType, $entity): bool
Unfortunately, we are not allowed to change public method signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-15 21:33 UTC, sidolov commented on lib/internal/Magento/Framework/Model/EntitySnapshot/AttributeProvider.php
> +    public function getAttributes($entityType): array
Unfortunately, we are not allowed to change public method signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-15 21:33 UTC, sidolov commented on lib/internal/Magento/Framework/Model/EntitySnapshot/AttributeProviderInterface.php
> +    public function getAttributes($entityType): array;
Unfortunately, we are not allowed to change public method signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-23 18:17 UTC, sidolov approved these changes

2019-08-23 18:19 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5690](https://jira.corp.magento.com/browse/ENGCOM-5690) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-30 17:35 UTC, merged