Fix getCurrentUrl() not respecting store base path
magento/magento2 pull request #23854
Opened 2019-07-24 11:45 UTC by toxix

This is correcting an issue for magento where magentos
\Magento\Framework\Url::getCurrentUrl()
function is not respecting the stores base url.

### Background
$this->_request->getOriginalPathInfo();
In setups, where the stores are
switched with the setting of
  SetEnv MAGE_RUN_TYPE store
  SetEnv MAGE_RUN_CODE de_de
the path that is available in the php request object is in our setup
not including the complete path but only the path after the
storeBaseUrl.

 url in browser: https://example.com/de/shop/hosen/
 host in php: example.com
 path in php: /hosen/
 base url in Magento: https://example.com/de/shop/

Now we running into an issue with the add to compare list links. This
links are generated and the redirect url is set already in the link
itself with the 'uenc' parameter. And this parameter contains a wrong
url: https://example.com/hosen/

After tracing down where this wrong url is comming from, it looks like
in the getCurrentUrl function of magento the base url of the shop is not
respected. Therefor I decided to change this function in a way that is
respecting the store base url if it is set and falls back to server/php
url otherwise.

### additional changes
Additionaly this also refector the url generation in a way, that is not
relying on manualy determine the parts of the url, but using the
zend/php framework for this.

### Feedback
This Fix is not tested with a Multistore setup that is based on Symlinks. I am not 100% sure if the 
`$this->_request->getOriginalPathInfo()` is delivering the correct path in this setups.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-24 11:45 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23854) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23854) before we can accept your contribution.<br/><hr/>**Zeno F. Pensky** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-08-13 16:02 UTC, josefbehr commented
@toxix is there a confirmed bug related to this PR? If not, can you please create one and post steps to reproduce the issue?

2019-08-15 21:39 UTC, sidolov requested changes

2019-08-15 21:39 UTC, sidolov commented on app/code/Magento/Backend/Model/Url.php
> +        \Magento\Store\Model\StoreManagerInterface $storeManager,
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-15 21:39 UTC, sidolov commented on lib/internal/Magento/Framework/Url.php
> +    protected $_storeManager;
Please, avoid usage underscore in the variables name and make the property private

2019-08-15 21:39 UTC, sidolov commented on lib/internal/Magento/Framework/Url.php
> +        \Magento\Store\Model\StoreManagerInterface $storeManager,
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-08-30 13:41 UTC, sidolov commented
@toxix I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-30 13:41 UTC, closed without merging