Replace annoying multi-line warning with short message + context
magento/magento2 pull request #23894
Opened 2019-07-25 21:29 UTC by lbajsarowicz

### Description (*)
When the warning occurs during reindex, the log entry is rather nasty:
```
[2019-07-25 21:03:35] x.WARNING: Attempt to load value of nonexistent EAV attribute '522'                          for entity type 'Magento\Catalog\Api\Data\ProductInterface'. [] []
[2019-07-25 21:03:35] x.WARNING: Attempt to load value of nonexistent EAV attribute '523'                          for entity type 'Magento\Catalog\Api\Data\ProductInterface'. [] []
[2019-07-25 21:03:35] x.WARNING: Attempt to load value of nonexistent EAV attribute '532'                          for entity type 'Magento\Catalog\Api\Data\ProductInterface'. [] []
```
with whitespaces. After changes, it's more valuable, because all the context is passed to context argument, so you can aggregate the warnings by message and attributes separately:
```
[2019-07-25 21:28:35] x.WARNING: Attempt to load value of nonexistent EAV attribute {"attribute_id":"532","entity_type":"Magento\\Catalog\\Api\\Data\\ProductInterface"} []
[2019-07-25 21:29:09] x.WARNING: Attempt to load value of nonexistent EAV attribute {"attribute_id":"532","entity_type":"Magento\\Catalog\\Api\\Data\\ProductInterface"} []
[2019-07-25 21:29:09] x.WARNING: Attempt to load value of nonexistent EAV attribute {"attribute_id":"532","entity_type":"Magento\\Catalog\\Api\\Data\\ProductInterface"} []
```

### Fixed Issues (if relevant)
Not applicable

### Manual testing scenarios (*)
1. Trigger situation where attribute_id is not defined for attributes map
2. Check logs for results

### Questions or comments
General improvement for readability and usability for log handlers like Graylog / ELK.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-05 10:38 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,
Thank you for your contribution! Your changes looks good to me, but static tests became failing. Could you fix them?
Thank you!

2019-08-05 10:39 UTC, lbajsarowicz commented
Static tests are complaining about excessive amount of dependencies, that cannot be fixed with fundamental refactor :(

2019-08-05 10:53 UTC, ihor-sviziev commented
In this case please add it to ignore for this class

On Mon, Aug 5, 2019 at 13:40 Lukasz Bajsarowicz <notifications@github.com>
wrote:

> Static tests are complaining about excessive amount of dependencies, that
> cannot be fixed with fundamental refactor :(
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/23894?email_source=notifications&email_token=AAOJOUKQSVAUKQ774MPJYWDQC77TPA5CNFSM4IG6SUL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3RNQWQ#issuecomment-518183002>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOJOUJZ5MEOJQEGEVZD75LQC77TPANCNFSM4IG6SULQ>
> .
>

2019-08-12 09:23 UTC, ihor-sviziev approved these changes

2019-08-12 09:24 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5593](https://jira.corp.magento.com/browse/ENGCOM-5593) has been created to process this Pull Request

2019-08-19 11:35 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-08-20 20:40 UTC, merged