[Children Ids] #184 - Create a cache to store children ids
magento/magento2 pull request #23910
Opened 2019-07-26 15:31 UTC by PierreLeMaguer

### Fixed Issues (if relevant)

[magento/community-features#183: Improve the performance of the method app/code/Magento/Eav/Model/Config.php::getAttribute](https://github.com/magento/community-features/issues/184)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-26 15:31 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=23910) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23910) before we can accept your contribution.<br/><hr/>**Pierre LE MAGUER** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-07-26 19:53 UTC, kandy commented on app/code/Magento/Catalog/Model/Product/Type/AbstractType.php
> +    protected $_cacheChildrenIds = [];
All new property must be private

2019-07-26 19:56 UTC, kandy commented
PR is adding cache, but missed the cache cleanup that will cause issue

2019-08-14 15:46 UTC, sidolov commented
@PierreLeMaguer , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-04 09:26 UTC, romainruaud commented
I'm reopening this PR (sorry if I'm exceeding my rights on this repository).

@sidolov @kandy can you give us clear directives about what needs to be changed / remain to be done ?

regards

2019-09-04 16:32 UTC, sidolov requested changes
@romainruaud , please, make `protected $_cacheChildrenIds = [];` as private, try to avoid underscores in property name. That's it

2019-09-06 09:32 UTC, PierreLeMaguer commented
Hi @sidolov , the protected property is needed to use it in all child classes.

2019-09-09 21:34 UTC, sidolov commented
@PierreLeMaguer , please, define private property in the each product type class instead of protected. Also, please, sign CLA, otherwise we cannot proceed with the pull request. Thank you.

2019-09-12 06:26 UTC, PierreLeMaguer commented
Hi @sidolov , I changed the property for a private property.
Can you give us the next steps ?
Thanks

2019-09-14 13:51 UTC, sidolov commented
@PierreLeMaguer please, take a look at failed tests, looks like the solution caused the behavior change

2019-10-04 15:18 UTC, sidolov commented
@PierreLeMaguer  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-10-04 15:18 UTC, closed without merging