#23955: Minicart shows HTML when using file upload custom option - fixed
magento/magento2 pull request #23980
Opened 2019-08-01 13:38 UTC by sudheers-kensium

### Description (*)

#23955: Minicart shows HTML when using file upload custom option - fixed

### Fixed Issues (if relevant)

1. magento/magento2#23955: Minicart shows HTML when using file upload custom option

### Manual testing scenarios (*)

1. As an admin, create a product with a custom option with type file upload
2. As a customer, add the product to the cart after having selected a file
3. Open up the mini cart, and expand "See Details" for the recently added product
4. See the custom option label with the filename of the uploaded file

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-12 14:04 UTC, rleshchenko requested changes

2019-08-12 14:04 UTC, rleshchenko commented on app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html
> +                                <span data-bind="html: option.value"></span>
This changes is forbidden due to security reasons. Please contact security team about that

2019-08-13 21:24 UTC, piotrekkaminski commented
@sudheers-kensium  @rleshchenko  From my POV, the problem lies elsewhere - labels should not allow HTML entry in the first place. And the behavior of escaping the output in such a way that it shows HTML instead of rendering it is correct. We are really trying to limit ways to execute XSS from the admin panel to front-end, as well as embed malicious JavaScript in places like this. If you want custom formatting of specific labels, either customize the code or do it using CSS. However for the larger user base, it's safer to not allow this.

2019-09-04 20:12 UTC, sidolov commented
@piotrekkaminski thank you for your answer! @sudheers-kensium  I'm closing this PR because it may introduce security issues in the future. Feel free to open the new PR if you find a safe way to resolve the mentioned issue. Thank you for your collaboration!

2019-09-04 20:12 UTC, closed without merging