No focus to invalid element in "Advance Pricing" => User can not see the error message when Creating Bundle Product (issue 24002)
magento/magento2 pull request #24006
Opened 2019-08-03 13:59 UTC by edenduong

### Description (*)

1. Resolve magento/magento2#24002: No focus to invalid element in "Advance Pricing" => User can not see the error message when Creating Bundle Product

Reason: No code for processing invalid case " in app/code/Magento/Ui/view/base/web/js/modal/modal-component.js

Solution: Write the code to process focusing to the Invalid Element. set `focused(true)`.

### Fixed Issues (if relevant)

1. magento/magento2#24002: No focus to invalid element in "Advance Pricing" => User can not see the error message when Creating Bundle Product

### Manual testing scenarios (*)

1. Go to Backend
2. Create new Bundle Product
3. Go to Advanced Pricing
4. In "Customer Group Price" - Click "Add"
5. Fill 22 in Quantity
6. Click Done

#### Expected result
1. Validate, focus to the "%" element => User can see the message "This is a required field."

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-05 08:47 UTC, edenduong commented
@sivaschenko : I don't know why the static test failed. Could you please give me some advice?

Thank you.

2019-08-08 20:58 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/modal/modal-component.js
> +        _focusInvalid: function (elems, firstRun = true) {
Hi @edenduong, thanks for collaboration. 

Please rename this function, the name with underscore is deprecated.
Please remove the set of default value from the function declaration. It's ES6 feature, but currently, we support just ES5

2019-08-08 21:03 UTC, VladimirZaets requested changes

2019-08-08 21:03 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/modal/modal-component.js
> +            var self = this;
Please bind context to the function instead of use `self` variable. For that, you can use `bind` `call` or `apply` methods

2019-08-08 21:03 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/modal/modal-component.js
> +                window.focusElement = false;
It is a bad approach to use global scope to check some state. You always can get current state directly from an element. Also, approach with `firstRun` variable looks like a hack

2019-08-23 15:02 UTC, sidolov commented
@edenduong , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-23 15:02 UTC, closed without merging