Fix: Add customer_address_id to billing_address
magento/magento2 pull request #24020
Opened 2019-08-05 13:26 UTC by UncleTioma

### Description (*)

`customer_address_id` will not set for new `billing_address`

### Fixed Issues (if relevant)

1. magento/magento2#17705: CustomerAddressId will not set for new billing adress

### Manual testing scenarios (*)

1. Create a new Customer Account
2. Add one Product to Cart
3. Create a New Shipment Address
4. Use Shipment Address as Order Address
5. Check `customer_address_id` with `address_type=billing` in `sales_order_address` 

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-05 13:26 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24020) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24020) before we can accept your contribution.<br/>

2019-08-15 12:19 UTC, miguelbalparda commented
Hi @UncleTioma! Can you check the failing tests please?

2019-08-20 11:34 UTC, UncleTioma commented
> Hi @UncleTioma! Can you check the failing tests please?
Hi @miguelbalparda 
I'm trying to re-run tests, but they cannot finish.
Can you help me with that?

2019-08-27 12:53 UTC, UncleTioma commented
@magento run all tests

2019-08-28 09:39 UTC, Stepa4man commented
@magento run all tests

2019-08-30 17:57 UTC, miguelbalparda approved these changes

2019-08-30 17:58 UTC, magento-engcom-team commented
Hi @miguelbalparda, thank you for the review.
[ENGCOM-5741](https://jira.corp.magento.com/browse/ENGCOM-5741) has been created to process this Pull Request
:eight_spoked_asterisk: @miguelbalparda, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-03 07:53 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-12-09 21:24 UTC, slavvka commented
@magento run all tests

2019-12-09 21:24 UTC, slavvka commented
@engcom-Foxtrot please take a look at static and functional EE tests

2019-12-09 21:26 UTC, slavvka commented
@engcom-Foxtrot and please cover the change with automated test

2020-01-06 21:31 UTC, VladimirZaets requested changes
Hi @UncleTioma. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

2020-01-10 10:42 UTC, engcom-Echo commented
I will take care of test coverage

2020-01-13 12:18 UTC, engcom-Echo commented
Hi @miguelbalparda, all changes covered by unit tests, could you please review

2020-02-06 19:28 UTC, lenaorobei approved these changes

2020-02-06 19:31 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5741](https://jira.corp.magento.com/browse/ENGCOM-5741) has been created to process this Pull Request

2020-02-07 09:46 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-02-14 17:53 UTC, slavvka commented
Need to approve PAT degradation: https://bamboo.corp.magento.com/browse/MCCE24-MCCE24162-1
`Save Order (Admin Create Order): 9.1% (mainline = 11 | team = 12) -> DEGRADATION`
```
SQLs were added to team: 
       UPDATE `quote_address` SET `customer_address_id` = ?, `prefix` = ?, `firstname` = ?, `middlename` = ?, `lastname` = ?, `suffix` = ?, `company` = ?, `street` = ?, `city` = ?, `region_id` = ?, `postcode` = ?, `telephone` = ?, `fax` = ?, `subtotal` = ?, `base_subtotal` = ?, `subtotal_with_discount` = ?, `base_subtotal_with_discount` = ?, `tax_amount` = ?, `base_tax_amount` = ?, `shipping_amount` = ?, `base_shipping_amount` = ?, `shipping_tax_amount` = ?, `base_shipping_tax_amount` = ?, `discount_amount` = ?, `base_discount_amount` = ?, `grand_total` = ?, `base_grand_total` = ?, `shipping_discount_amount` = ?, `base_shipping_discount_amount` = ?, `subtotal_incl_tax` = ?, `discount_tax_compensation_amount` = ?, `base_discount_tax_compensation_amount` = ?, `shipping_discount_tax_compensation_amount` = ?, `shipping_incl_tax` = ?, `base_shipping_incl_tax` = ?, `base_customer_balance_amount` = ?, `customer_balance_amount` = ?, `gift_cards_amount` = ?, `base_gift_cards_amount` = ?, `reward_points_balance` = ?, `base_reward_currency_amount` = ?, `reward_currency_amount` = ? WHERE (address_id=183)
```

2020-02-18 22:14 UTC, slavvka commented
PAT failure ticket is created https://jira.corp.magento.com/browse/MC-31650

2020-02-20 18:47 UTC, naydav commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +        if (!$billing->getCustomerAddressId() && $shipping) {
Could you change sequence of the condition?
`($shipping && !$billing->getCustomerAddressId())`

Thanks

2020-03-02 18:28 UTC, lenaorobei submitted a review, later dismissed

2020-03-02 18:29 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5741](https://jira.corp.magento.com/browse/ENGCOM-5741) has been created to process this Pull Request

2020-03-04 09:47 UTC, engcom-Foxtrot commented
I've investigated the PAT build degradation. Seems like Billing Address is saved twice in \Magento\Sales\Controller\Adminhtml\Order\Create\Save. On 2.4-dev Billing Address object is not modified between \Magento\Framework\Model\ResourceModel\Db\AbstractDb::save calls, so the second transaction is skipped. While on PR branch Adress's hasDataChanges flag is set to true, so we have one more DB transaction. 
Also, if we are creating Billing Address through admin - no customer_address_id is set to Shipping Address (if it is copy of Billing Address).

2020-03-11 20:46 UTC, naydav commented
Hello everyone,
Looks like we need to close the initial issue.
I describe my concern at https://github.com/magento/magento2/issues/17705#issuecomment-596632841
Thanks

2020-09-11 17:04 UTC, sidolov commented
@UncleTioma I'm closing the PR according to the @naydav comment. We should refactor code to avoid usage of `customer_address_id ` field instead of adding it to the address. Feel free to open new PR with refactoring if you want to continue.

2020-09-11 17:04 UTC, closed without merging