Refactor Shipping Address loading for Checkout to improve Performance if multiple addresses are given
magento/magento2 pull request #24026
Opened 2019-08-06 08:37 UTC by suchadean

### Description (*)
Initializing ShippingAddresses in Magento_Checkout is coded in an old way. I just refactored the Code for customer-addresses.js and address-list.js and made use of more faster ways to iterate through the objects. Accessing the underlying Array of the knockout.observableArray and use ".arrayPushAll()" together with ".valueHasMutated()" is way faster than pushing data through "observableArray(newArray)" because we decrease the number of calls made inside knockout.
This way, we gain a significant improvement of loading speed and/or handling of a great amount of data (which we had as an issue for one of our customers)

### Manual testing scenarios (*)
1. We had to load 1.586 (no joke!) addresses for a customer, which resulted in a dying browser multiple times with the old code.
2. with new code the loading time of 1.586 Shipping Addresses takes about 5 seconds

### Questions or comments
Feel free to improve it more!

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-06 08:37 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24026) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24026) before we can accept your contribution.<br/><hr/>**Dean Möller** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-08-07 12:44 UTC, suchadean commented
@magento-engcom-team I can't reproduce why Static, Sample Data, Functional and Database Tests fail. Details say everything is passed... neither did I touch any of that.

2019-08-08 15:14 UTC, VladimirZaets requested changes
Hi @suchadean, thanks for collaboration
Due to builds. I will rerun it. 
Also, we can't use `let` because currently we fully support just ecmascript 5 that doesn't support `let` variables. Please replace it to `var`.

2019-08-23 15:02 UTC, sidolov commented
@suchadean , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-08-23 15:02 UTC, closed without merging