Fixed product back redirect navigate from customer view cart product
magento/magento2 pull request #24089
Opened 2019-08-09 11:38 UTC by ravi-chandra3197

### Description (*)

Fixed product back redirect navigate from customer view cart product
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: N/A

### Manual testing scenarios (*)

1. create new customer
2. create new product
3. add product into cart 
4. Admin -> Customers -> All Customers -> edit customer -> Shopping cart Tab -> click on product row -> from edit product click for back

Expected result (*)
back redirect  edit customer 

Actual result (*)
back redirect catalog/product/index

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-09 11:40 UTC, ravi-chandra3197 commented
@magento give me 2.3-develop instance

2019-08-09 11:40 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-08-09 11:40 UTC, magento-engcom-team commented
Hi @ravi-chandra3197, here is your [Magento instance](https://i-24089-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24089-2-3-develop.instances.magento-community.engineering/admin](https://i-24089-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-08-09 11:45 UTC, ravi-chandra3197 commented
@magento give me 2.3-develop instance

2019-08-09 11:45 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-08-09 11:46 UTC, ravi-chandra3197 commented
@magento give me test instance

2019-08-09 11:46 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento instance for you

2019-08-09 11:46 UTC, magento-engcom-team commented
Hi @ravi-chandra3197, here is your [Magento instance](https://i-24089-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24089-2-3-develop.instances.magento-community.engineering/admin](https://i-24089-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-08-12 19:55 UTC, VladimirZaets requested changes

2019-08-12 19:55 UTC, VladimirZaets commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Edit/Button/Back.php
> +    public function getBackUrl()
Hi, @ravi-chandra3197, due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't create new one public methods. Please make this method private.

2019-08-15 20:44 UTC, VladimirZaets approved these changes

2019-08-15 20:46 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5637](https://jira.corp.magento.com/browse/ENGCOM-5637) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-16 12:27 UTC, engcom-Alfa commented
Hi @ravi-chandra3197 .

During testing we faced the issue

_**Problem:**_ Error  "Invalid security or form key. Please refresh the page." message occurs

**Steps to reproduce:**

1. Create new customer in storefront;
2. Create new product;
3. Add product into cart;
4. Go to Admin -> Customers -> All Customers -> edit customer -> Shopping cart Tab -> click on product ; 
5. From edit product click on "Back" button;

**Actual result:**
![after](https://user-images.githubusercontent.com/51679138/63167527-40d75200-c03a-11e9-8783-605be56274ac.png)

@ravi-chandra3197  Could you take a look?

Thanks!

2019-08-16 12:41 UTC, ravi-chandra3197 commented
@magento give me test instance

2019-08-16 12:41 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento instance for you

2019-08-16 12:42 UTC, magento-engcom-team commented
Hi @ravi-chandra3197, here is your [new Magento instance](https://pr-24089.instances.magento-community.engineering).
Admin access: [https://pr-24089.instances.magento-community.engineering/admin](https://pr-24089.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-08-19 13:28 UTC, krnshah commented
@magento give me test instance

2019-08-19 13:28 UTC, magento-engcom-team commented
Hi @krnshah. Thank you for your request. I'm working on Magento instance for you

2019-08-19 13:29 UTC, magento-engcom-team commented
Hi @krnshah, here is your [new Magento instance](https://pr-24089.instances.magento-community.engineering).
Admin access: [https://pr-24089.instances.magento-community.engineering/admin](https://pr-24089.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-08-28 11:42 UTC, ravi-chandra3197 commented
@magento give me test instance

2019-08-28 11:42 UTC, magento-engcom-team commented
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento instance for you

2019-08-28 11:43 UTC, magento-engcom-team commented
Hi @ravi-chandra3197, here is your [new Magento instance](https://pr-24089.instances.magento-community.engineering).
Admin access: [https://pr-24089.instances.magento-community.engineering/admin](https://pr-24089.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-08-28 11:50 UTC, ravi-chandra3197 commented
Hello @engcom-Alfa 
I have update PR and resolve above issue can you check it. 

> Hi @ravi-chandra3197 .
> 
> During testing we faced the issue
> 
> _**Problem:**_ Error "Invalid security or form key. Please refresh the page." message occurs
> 
> **Steps to reproduce:**
> 
> 1. Create new customer in storefront;
> 2. Create new product;
> 3. Add product into cart;
> 4. Go to Admin -> Customers -> All Customers -> edit customer -> Shopping cart Tab -> click on product ;
> 5. From edit product click on "Back" button;
> 
> **Actual result:**
> ![after](https://user-images.githubusercontent.com/51679138/63167527-40d75200-c03a-11e9-8783-605be56274ac.png)
> 
> @ravi-chandra3197 Could you take a look?
> 
> Thanks!

Hello @engcom-Alfa 
I have updated PR can you check it.

2019-09-03 16:55 UTC, VladimirZaets commented
Hi @ravi-chandra3197. Please fix static tests. Thanks

2019-09-05 04:41 UTC, ravi-chandra3197 commented
> fix static tests

Hello @VladimirZaets 
I have fixed static tests can review it.

2019-09-16 19:05 UTC, sidolov approved these changes

2019-09-16 19:05 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5637](https://jira.corp.magento.com/browse/ENGCOM-5637) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-17 07:14 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-09-20 00:35 UTC, merged