24070 - Allowed multivalue form elements to submit data to website/gr…
magento/magento2 pull request #24094
Opened 2019-08-09 18:35 UTC by ericclaeren

## Example

## Issue

### Proposed solution

### Description (*)
Fix for issue: https://github.com/magento/magento2/issues/24070

When submitting a website, group or store entity form (add/edit), submitted multivalue form elements get filtered and only the last selected element will be posted to the controller.

This posted data
```
fieldname[]: value1
fieldname[]: value2
```
Turns into
```
{
   fieldname[]: value2
}
```

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/24070#issue-478488652 : Website/Group/Store entity form can't be extended with multiple value form element for extension attributes

* Transform fieldnames with multiple [] to an indexed one.
** This: 
```
fieldname[]: value1
fieldname[]: value2
```
** Turns into
```
fieldname[]: value1
fieldname[1]: value2
```

Therefore the names are different and both fields can be converted to a new input to be actually posted to the controller.

I chose not to convert the first fieldname[] to fieldname[0] because altering this, I could not reference to the fieldname within the same set of data and this needed more javascript code. This is not necessary for PHP which receives fieldname[] as 0 and fieldname[1] as 1.

Used let/const because they are supported in IE11 and don't interfere with scope of the function.

### Manual testing scenarios (*)
* Extend the Store.php form block with a multivalue field. See: https://github.com/magento/magento2/issues/24070
** <select name="fieldname[]" multiple="multiple">
* The submitted data in validate-store.js will converted a key/value object
* A new html form will be generated with <input name="" value="" /> of the previous object entries.
* This form is posted to the controller.
* Current postdata fields won't be altered, multivalue fields will be submitted, before only the last element gets posted.

2019-08-09 18:35 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24094) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24094) before we can accept your contribution.<br/><hr/>**Eric Claeren** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-08-09 19:16 UTC, VladimirZaets requested changes

2019-08-09 19:16 UTC, VladimirZaets commented on app/code/Magento/Backend/view/adminhtml/web/js/validate-store.js
> +                const counts = {};
Hi @ericclaeren, thanks for collaboration. 

Please change all `const` and `let` declaration to `var`. Currently, we support just ES5 and we cant use `const` and `let` that was provided in ES6

2019-08-09 19:58 UTC, ericclaeren commented on app/code/Magento/Backend/view/adminhtml/web/js/validate-store.js
> +                const counts = {};
Thank you for the feedback @VladimirZaets. Have changed the variable declarations.

2019-08-12 09:45 UTC, ericclaeren commented
Hi @VladimirZaets, have fixed the variable declarations and ran into js linting errors which I have resolved. Would you mind reviewing my code again? Thanks

2019-08-12 15:48 UTC, VladimirZaets submitted a review, later dismissed
Thanks for fixes.

2019-08-12 15:49 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5604](https://jira.corp.magento.com/browse/ENGCOM-5604) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-12 15:49 UTC, magento-engcom-team commented
@ericclaeren thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-08-14 10:23 UTC, ericclaeren commented
@VladimirZaets The purpose of this change is untested by auto-test.

Although Magento Core has a jasmin JS test for this validate function, there isn't a test for the _saveHandler() method. See: validate-store.test.js. So the whole core JS functionality isn't being tested right now.

2019-08-21 08:21 UTC, ericclaeren commented
@magento-engcom-team The label has been added.

2019-09-20 12:21 UTC, engcom-Delta commented
Hi @ericclaeren seems like issue described by PR wasn't fixed.
**Manual testing scenario:**

- Create Observer for adminhtml_store_edit_form_prepare_form
- Add field with multiselect.

```/**
     * @param Observer $observer
     */
    public function execute(Observer $observer): void
    {
        $block = $observer->getEvent()->getBlock();
        $form = $block->getForm();
        $fieldSettings = [
            'name' => 'store[multiple][]',
            'label' => __('Multiselect field'),
            'value' => '',
            'values' => [
                ['value' => 'value1', 'label' => 'testLabel1'],
                ['value' => 'value2', 'label' => 'testLabel2']

            ],
            'required' => false,
            'disabled' => false,
        ];

        $fieldset = $form->addFieldset('group_multiselect', ['legend' => __('Multiselect fieldset')]);
        $fieldset->addField('multiselectElement', 'multiselect', $fieldSettings);
        $observer->setData('block', $block->setForm($form));
```

- Select all values from multiselect

![#24094PRMultiselect](https://user-images.githubusercontent.com/51681379/65326293-c9a55880-dbb9-11e9-960e-96dc7d8cebc5.png)

- Save form and check headers of postdata.

**Result:**
:x: Only last value from multiselect was sent in POST
![#24094PRPost](https://user-images.githubusercontent.com/51681379/65326363-f0638f00-dbb9-11e9-9ca8-c2535823a5ff.png)

2019-09-23 07:56 UTC, ericclaeren commented
That's really weird, are you sure the correct (patched) validation-store.js code is loaded.

Some screens from my code. The observer is pretty much the same, although my data are store Ids.

**Multiselect**
![image](https://user-images.githubusercontent.com/4748495/65409524-37cf6280-dde8-11e9-95a3-7c9d7b979b51.png)

**console.table(formData)** of validate-store.js
![Screenshot 2019-09-23 at 09 37 15](https://user-images.githubusercontent.com/4748495/65409376-da3b1600-dde7-11e9-854a-3e5e666b0b63.png)

**Request recorded in Google Chrome.**
![Screenshot 2019-09-23 at 09 45 37](https://user-images.githubusercontent.com/4748495/65409436-035ba680-dde8-11e9-9b93-be589144a9d2.png)

Could you explain how you evaluated your code?

2019-09-23 18:35 UTC, sidolov commented
@engcom-Delta please, take a look a comment from @ericclaeren

2019-09-24 13:44 UTC, engcom-Delta commented
@ericclaeren I debug Magento/Backend/Controller/Adminhtml/System/Store/[Save.php](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Backend/Controller/Adminhtml/System/Store/Save.php#L115) and check $_POST variable:
![image](https://user-images.githubusercontent.com/51681379/65516433-af38eb00-dee9-11e9-87a3-b98a65a015ef.png)
Here what I get in console:
![#24094PRConsoleJS](https://user-images.githubusercontent.com/51681379/65516632-0474fc80-deea-11e9-89f9-2ecbbd49819a.png)

And code snippet of my multiselect field:
```
/**
* @param Observer $observer
*/
public function execute(Observer $observer): void
    {
        $block = $observer->getEvent()->getBlock();
        $form = $block->getForm();
        $fieldSettings = [
            'name' => 'store_custom',
            'label' => __('Multiselect field'),

            'values' => [
                ['label' => 'testLabel1', 'value' => 'value1'],
                ['label' => 'testLabel2', 'value' => 'value2']

            ],
            'required' => false,
            'disabled' => false,
        ];

        $fieldset = $form->addFieldset('group_multiselect', ['legend' => __('Multiselect fieldset')]);
        $fieldset->addField('multiselectElement', 'multiselect', $fieldSettings);
        $observer->setData('block', $block->setForm($form));
    }
```

2019-09-24 14:49 UTC, ericclaeren commented
That's really interesting, the format also is different [0] vs []. 

Could you validate if your local codebase in /validate-store.js on line 55 contains `counts[this.name]` = (counts[this.name] || 0) + 1;`?

Have no clue why this is not working and the output differs.

2019-09-25 13:34 UTC, engcom-Delta commented
@ericclaeren I have tested PR branch with appropriate changes in validate-store.js.
Row ```counts[this.name] = (counts[this.name] || 0) + 1;``` is present there.
![#24094PR](https://user-images.githubusercontent.com/51681379/65605646-23d75c80-dfb2-11e9-98dc-d8136e0c1ae1.gif)

2019-09-27 11:42 UTC, ericclaeren commented
Thanks for the feedback, will look into this.

2019-09-27 13:38 UTC, ericclaeren commented
Allright, i'm a bit lost right now. Have tried the exact same steps, copied your code example of the multiple fields in my observer. And have totally different output in chrome debugger as in phpstorm debugger.

Attached you will find my screencast. Any suggestions?
![example](https://user-images.githubusercontent.com/4748495/65773568-da674880-e13c-11e9-9939-ca0ede9a35ed.gif)

2019-10-07 07:02 UTC, ericclaeren commented
@engcom-Delta Have you seen my findings. I'm a bit stuck on why we have a completely different output.

2019-10-16 15:43 UTC, VladimirZaets commented
Hi @ericclaeren. Thanks for collaboration. I will try to investigate why the results are different.

2020-01-02 09:11 UTC, ericclaeren commented
Any news on this issue?

2020-10-01 21:16 UTC, sidolov approved these changes

2020-10-01 21:17 UTC, sidolov commented
@ericclaeren please, sign Adobe CLA

2020-10-01 21:19 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5604](https://jira.corp.magento.com/browse/ENGCOM-5604) has been created to process this Pull Request

2020-10-16 11:21 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
**Result:**
Selected multivalue fields are submitted
![image](https://user-images.githubusercontent.com/51681379/96252060-09579300-0fba-11eb-9cea-492fe7942372.png)
![image](https://user-images.githubusercontent.com/51681379/96252143-2a1fe880-0fba-11eb-84b8-1f7610a1dd05.png)

2020-10-16 11:36 UTC, engcom-Charlie requested changes
@ericclaeren please sign CLA. Otherwise, we can't proceed with your PR.
Thank you.

2020-10-20 07:55 UTC, engcom-Charlie commented
@ericclaeren please look at https://github.com/magento/magento2/pull/24094#pullrequestreview-510388676
Thank you.

2020-10-20 09:46 UTC, engcom-Charlie commented
@magento run all tests

2025-06-02 08:29 UTC, engcom-Dash commented
@magento run all tests

2025-06-03 06:56 UTC, engcom-Dash commented
As code review, testing is already completed on this PR. Also the Adobe CLA is signed now. Moving this PR in Extended Testing.

2025-06-03 13:26 UTC, ericclaeren commented
I'm not able to review this issue, I have not worked on a Magento website in the last 4 years and have no means to test any of the requested features.

2025-06-04 05:50 UTC, engcom-Dash commented
Hello @ericclaeren 

Thank you for your contribution.

We’ve verified that the issue is still reproducible, and we can confirm that the solution proposed in this PR effectively resolves it. We’ll be taking it forward from here and proceeding with the necessary steps to get it merged.

Appreciate your efforts!

Thanks!

2025-06-04 05:53 UTC, engcom-Dash commented
@magento run all tests

2025-06-04 10:37 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Static Tests, Unit Tests

2025-06-04 13:47 UTC, engcom-Dash commented
The consistent test failures for Functional B2B are known Issues and JIRA is raised for them.Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/ec0fbee6f4a35121fcbcac8ef3d21f40/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/f9ea328b-535f-4605-894e-c6271d561d50)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/91ee2b583a5b9b599405f0d4cc881828/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/57c9ebf7-cf9a-457f-86e4-fcfd113d1125)

**Known Issues:**
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)
StoreFrontSimpleProductWithSpecialAndTierDiscountPriceTest : [ACQE-7971](https://jira.corp.adobe.com/browse/ACQE-7971)
OrderWithMultipleConfigurableProductsAdditionalStockTest : [ACQE-8060](https://jira.corp.adobe.com/browse/ACQE-8060)

The consistent test failures for Functional CE is known Issues and JIRA is raised for the same. 

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/7a14a3f03d8eee6c82317625d6f2a878/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/4c6aedaf-3847-4a2b-9d31-4567bcd775e0)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/848d19ce28e8f4b485bb1a15c5f9e8ea/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/916560a3-6d20-4c2b-85ed-881443469aee)

**Known Issues:**
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

The consistent test failure for Functional EE is known Issues and JIRA is raised for the same. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/7d7815d10fa81049299e03f5edb44afc/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/c40d5c17-08a3-4d94-bf6b-1429886b81c6)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/d26ce05b519889ad04a681dc340fa750/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/a6a7e7cd-b8bf-4c00-b377-c635217c8399)

**Known Issues:**
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

**Static Test Failure**
The consistent static test failure is not because of this code changes done in this PR. It is a known issue and has JIRA Opened for the same.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/5de292251065c749128833c2e6ad4b12/Statics/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/50d76f80-410f-46f4-a608-a296e9232dbf)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24094/5d12c6d2f8a016fe3500d4481c40b0a5/Statics/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/e0b1937c-88bf-47e6-ab53-030e97d8f938)

Known Issue:
"use strict" is unnecessary inside of modules: https://jira.corp.adobe.com/browse/AC-14517.

Hence moving this PR in Merge In Progress.

2025-06-10 06:34 UTC, engcom-Dash commented
@magento run all tests

2025-06-18 09:32 UTC, merged