Update Admin Notification ReadMe
magento/magento2 pull request #24129
Opened 2019-08-14 00:40 UTC by diazwatson

### Description (*)

Updates ReadMe for Magento_AdminNotification module.

### Fixed Issues (if relevant)

1. magento/devdocs https://github.com/magento/devdocs/issues/4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-14 05:16 UTC, ihor-sviziev approved these changes

2019-08-14 05:17 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5617](https://jira.corp.magento.com/browse/ENGCOM-5617) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-14 09:14 UTC, engcom-Alfa commented
QA not applicable

2019-08-14 12:15 UTC, jeff-matthews requested changes
Please see minor editorial suggestions.

2019-08-14 12:15 UTC, jeff-matthews commented on app/code/Magento/AdminNotification/README.md
> +Before disable or uninstall this module, please note that Magento_Indexer module depends on this module.
```suggestion
Before disabling or uninstalling this module, note that the Magento_Indexer module depends on this module.
```

2019-08-14 12:15 UTC, jeff-matthews commented on app/code/Magento/AdminNotification/README.md
> +For information about a module installation in Magento 2, see [Enable or disable modules](http://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.html).
```suggestion
For information about module installation in Magento 2, see [Enable or disable modules](http://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.html).
```

2019-08-14 12:15 UTC, jeff-matthews commented on app/code/Magento/AdminNotification/README.md
> +For more information about a layout in Magento 2, see the [Layout documentation](http://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-overview.html).
```suggestion
For more information about layouts in Magento 2, see the [Layout documentation](http://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-overview.html).
```

2019-08-14 12:15 UTC, jeff-matthews commented on app/code/Magento/AdminNotification/README.md
> +You can extend admin notifications using the configuration file in `view/adminhtml/ui_component/notification_area.xml`
```suggestion
You can extend admin notifications using the `view/adminhtml/ui_component/notification_area.xml` configuration file.
```

2019-08-14 12:15 UTC, jeff-matthews commented on app/code/Magento/AdminNotification/README.md
> +For information about a UI component in Magento 2, see [Overview of UI components](http://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html).
```suggestion
For information about UI components in Magento 2, see [Overview of UI components](http://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html).
```

2019-08-15 12:13 UTC, jeff-matthews approved these changes
Thanks @diazwatson!

2019-08-15 12:15 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5617](https://jira.corp.magento.com/browse/ENGCOM-5617) has been created to process this Pull Request

2019-08-15 12:54 UTC, diazwatson commented
Hi @jeff-matthews, thank for taking the time to review this PR.

2019-08-15 16:27 UTC, dshevtsov requested changes

2019-08-15 16:27 UTC, dshevtsov commented on app/code/Magento/AdminNotification/README.md
> +For information about module installation in Magento 2, see [Enable or disable modules](http://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.html).
Change the link to `https://...`

2019-08-15 16:27 UTC, dshevtsov commented on app/code/Magento/AdminNotification/README.md
> +For more information about layouts in Magento 2, see the [Layout documentation](http://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-overview.html).
Change the link to `https://...`

2019-08-15 16:27 UTC, dshevtsov commented on app/code/Magento/AdminNotification/README.md
> +For information about UI components in Magento 2, see [Overview of UI components](http://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html).
Change the link to `https://...`

2019-08-15 17:37 UTC, merged