Update AdvancedSearch ReadMe
magento/magento2 pull request #24176
Opened 2019-08-18 22:58 UTC by diazwatson

### Description (*)

Updates ReadMe for the Magento_AdvancedSearch module.

### Fixed Issues (if relevant)

1. magento/devdocs https://github.com/magento/devdocs/issues/4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-19 05:54 UTC, VladimirZaets approved these changes

2019-08-19 05:56 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5658](https://jira.corp.magento.com/browse/ENGCOM-5658) has been created to process this Pull Request

2019-08-19 12:46 UTC, jeff-matthews requested changes
Thanks for working on these READMEs @diazwatson! I made some minor editorial suggestions.

2019-08-19 12:46 UTC, jeff-matthews commented on app/code/Magento/AdvancedSearch/README.md
> +this functionality by 3rd party search engines.
Suggested rewrite:

> The Magento_AdvancedSearch module introduces advanced search functionality and provides interfaces that allow third-party search engines to implement this functionality.

2019-08-19 12:46 UTC, jeff-matthews commented on app/code/Magento/AdvancedSearch/README.md
> +The module interact with the following layout handles in the `view/frontend/layout` directory:
```suggestion
The module interacts with the following layout handles in the `view/frontend/layout` directory:
```

2019-08-19 12:46 UTC, jeff-matthews commented on app/code/Magento/AdvancedSearch/README.md
> +The module interact with the following layout handles in the `view/adminhtml/layout` directory:
```suggestion
The module interacts with the following layout handles in the `view/adminhtml/layout` directory:
```

2019-08-19 23:10 UTC, diazwatson commented
Thanks to you @jeff-matthews for taking the time to CR this.
Requested changes are now done.

2019-08-20 12:08 UTC, jeff-matthews approved these changes

2019-08-20 12:09 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5658](https://jira.corp.magento.com/browse/ENGCOM-5658) has been created to process this Pull Request

2019-08-23 08:36 UTC, engcom-Alfa commented
QA not applicable

2019-08-27 16:31 UTC, merged