Adminhtml Create Order - Remove unrequired setQty(getQty) call
magento/magento2 pull request #24200
Opened 2019-08-20 11:24 UTC by gwharton

### Description (*)
When adding products to an order in the Adminhtml backend, a call is made to setQty(getQty) on the cart items as they are added. There is a comment in the code that this is to force a dispatch of the 
sales_quote_item_qty_set_after event.

This call is not required as the sales_quote_item_qty_set_after event is fired shortly before this code is processed.

An unintended consequence of calling setQty(getQty) which the original author may not have been aware of (and may be a bug introduced since then) is that a call to setQty(getQty) actually triggers a stockitem validation call for double the quantity, as it treats it as a call to add x items to a stockitem that already has x items in it. I'll raise a separate issue to cover the bug in setQty, but for now, removing this setQty(getQty) call from the admin order seems to have no ill effect as the sales_quote_item_qty_set_after event has already been dispatched.

### Fixed Issues (if relevant)
1. magento/magento2#24191: Placing order in Admin for backordered items shows incorrect backorder message

### Manual testing scenarios (*)
1. Create stock item with 10 in stock, allow backorders with notify. 
2. Make order for 8 items. Verify no backorder message (without this fix, it warns backorder of 6)

1. Create stock item with 10 in stock, allow backorders with notify. 
2. Make order for 12 items. Verify backorder warning for 2 items is displayed. (without this fix, it actually displays 2 messages,  one with warning for 2 items, and one with warning for 12 items)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-20 19:23 UTC, sidolov approved these changes

2019-08-20 19:24 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5673](https://jira.corp.magento.com/browse/ENGCOM-5673) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-23 10:21 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed 

**Before:**
![before](https://user-images.githubusercontent.com/51679138/63585905-d29a0e80-c5a8-11e9-9a71-046680b39e40.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/63585917-d9288600-c5a8-11e9-8b80-5d8e811b17eb.png)

2019-09-04 16:01 UTC, sidolov commented
@gwharton we found that provided fix caused the issue in AdvancedCheckout module. Functional test `Magento\AdvancedCheckout\Test\TestCase\AddProductsToCartBySkuFromBackendTest` is failed with such changes. @engcom-Foxtrot , please, take a look at this fail.

2019-09-04 16:01 UTC, sidolov requested changes
Test is failing

2019-09-05 15:24 UTC, engcom-Foxtrot commented
Hello, @gwharton. Thank you for your contribution. Unfortunately, we have faced an issue with your PR. As you can see [here](https://github.com/magento/magento2/blob/e95cca34b10a50412a433ef26784f73fe65bb7d9/app/code/Magento/Sales/Block/Adminhtml/Order/Create/Items/Grid.php#L133-L137), before Quote Item validation the flag "isSuperMode" is set to false. All previous cheks run with "isSuperMode"  set to true, so  QuoteItem's "message" field is set, but "hasError" field is not (see [here](https://github.com/magento/magento2/blob/e95cca34b10a50412a433ef26784f73fe65bb7d9/app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator.php#L136)). This incorrect behavior leads to getting notice instead of an error on the admin page.
You can reproduce this issue by the following steps:
1. Create a Customer.
2. Create a Product, on the Advanced Inventory tab set Enable Qty Increments to "Yes" and Qty Increments to "2".
3. Go to Sales -> Orders, create new Order.
4. Add the Product to the Order, set it's Quantity to 3.
Expected result:
![error](https://user-images.githubusercontent.com/51681487/64355316-abf8c080-d009-11e9-809e-0b3a6edce2de.png)
Actual result:
![notice](https://user-images.githubusercontent.com/51681487/64355322-aef3b100-d009-11e9-9ffc-e09f9e8cf37b.png)

2019-09-06 12:49 UTC, gwharton commented
OK, I'm going to withdraw this PR as

a) it is obviously more complicated than I thought

and 

b) I'm not knowledgeable enough of the quote mechanism to be able to confidently delve in and make more detailed changes. An initial look confused the hell out of me :)

I'll leave the issue open, so others can jump in.

2019-09-06 12:49 UTC, closed without merging