magento/magento2#21592: Newsletter subscription input box in footer:
magento/magento2 pull request #24263
Opened 2019-08-23 18:44 UTC by afazcar

- fix placeholder in newsletter for portrait mode ipad

### Description (*)

 Add a min-width in the footer block so that the placeholder is always visible.

### Fixed Issues (if relevant)

1. magento/magento2#21592: Newsletter subscription input box in footer: on iPad (9.7"), in portrait mode, placeholder text is not visible

### Manual testing scenarios (*)

tests in resolutions for mobiles

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-23 18:44 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24263) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24263) before we can accept your contribution.<br/><hr/>**afaz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-08-23 18:46 UTC, VladimirZaets commented
Hi @afazcar  , please, sign CLA, otherwise, we can't process your pull request

2019-08-23 18:46 UTC, VladimirZaets requested changes
Hi @afazcar , please, sign CLA, otherwise, we can't process your pull request

2019-09-03 19:06 UTC, VladimirZaets approved these changes

2019-09-03 19:08 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5756](https://jira.corp.magento.com/browse/ENGCOM-5756) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-04 11:33 UTC, engcom-Delta commented
Hi @afazcar Same issue also is present on Blank theme.
![image](https://user-images.githubusercontent.com/51681379/64251295-df135500-cf20-11e9-81c9-bfbaa6d4b5a6.png)


Could you take a look?

2019-09-19 17:26 UTC, sidolov commented
@afazcar  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-19 17:26 UTC, closed without merging