magento/magento2#24266: DHL Mexico isn´t working
magento/magento2 pull request #24271
Opened 2019-08-23 21:36 UTC by sebastianCarry

### Description (*)

Removed unneeded DHL params for MX

### Fixed Issues (if relevant)
1. magento/magento2#24266: DHL Mexico isn´t working

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-23 21:36 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24271) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24271) before we can accept your contribution.<br/>

2019-08-24 03:56 UTC, ihor-sviziev requested changes

2019-08-24 03:56 UTC, ihor-sviziev commented on app/code/Magento/Dhl/Model/Carrier.php
>          if ($this->isDutiable($rawRequest->getOrigCountryId(), $rawRequest->getDestCountryId())) {
Looks like it’s better to adjust this check, or even `isDutiable` method. What do you think?

2019-09-09 15:34 UTC, sidolov commented
@sebastianCarry , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-09 15:34 UTC, closed without merging