Update Magento_AmqpStore ReadMe
magento/magento2 pull request #24276
Opened 2019-08-25 06:06 UTC by diazwatson

### Description (*)

Updates ReadMe for the Magento_AmqpStore module.

### Fixed Issues (if relevant)

1. magento/devdocs https://github.com/magento/devdocs/issues/4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-26 13:09 UTC, jeff-matthews requested changes

2019-08-26 13:09 UTC, jeff-matthews commented on app/code/Magento/AmqpStore/README.md
> +Magento_AmqpStore provides ability to specify store before publish messages with with the Advanced Message Queuing Protocol (AMQP).
```suggestion
Magento_AmqpStore provides the ability to specify a store before publishing messages with the Advanced Message Queuing Protocol (AMQP).
```

2019-08-27 03:07 UTC, jeff-matthews approved these changes

2019-08-27 03:09 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5707](https://jira.corp.magento.com/browse/ENGCOM-5707) has been created to process this Pull Request

2019-08-28 13:38 UTC, engcom-Delta commented
**Notice:** QA not applicable

2019-08-29 15:35 UTC, engcom-Foxtrot commented
@magento run all tests

2019-08-30 19:17 UTC, merged