Update Magento_Authorizenet ReadMe
magento/magento2 pull request #24279
Opened 2019-08-25 07:10 UTC by diazwatson

### Description (*)

Updates ReadMe for the Magento_Authorizenet module.

### Fixed Issues (if relevant)

1. magento/devdocs https://github.com/magento/devdocs/issues/4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-26 13:17 UTC, jeff-matthews requested changes

2019-08-26 13:17 UTC, jeff-matthews commented on app/code/Magento/Authorizenet/README.md
> +The Magento_Authorizenet module is a part of the staging functionality in Magento EE. The module adds the “Configurations” tab and the configuration wizard to the Schedule Update form of a product. Y
```suggestion
The Magento_Authorizenet module is a part of the staging functionality in Magento Commerce. The module adds the “Configurations” tab and the configuration wizard to the Schedule Update form of a product. You can change the Configurable Product attributes in campaigns. These updates are shown on the campaign dashboard.
```

2019-08-26 13:17 UTC, jeff-matthews commented on app/code/Magento/Authorizenet/README.md
> + - `checkout_submit_all_after` event in `Magento\Authorizenet\Observer\SaveOrderAfterSubmitObserver` file.
```suggestion
 - `checkout_submit_all_after` event in the `Magento\Authorizenet\Observer\SaveOrderAfterSubmitObserver` file.
```

2019-08-26 13:17 UTC, jeff-matthews commented on app/code/Magento/Authorizenet/README.md
> + - `checkout_directpost_placeOrder` event in `Magento\Authorizenet\Observer\AddFieldsToResponseObserver` file.
```suggestion
 - `checkout_directpost_placeOrder` event in the `Magento\Authorizenet\Observer\AddFieldsToResponseObserver` file.
```

2019-08-26 13:17 UTC, jeff-matthews commented on app/code/Magento/Authorizenet/README.md
> +For information about an event in Magento 2, see [Events and observers](http://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html#events).
```suggestion
For information about events in Magento 2, see [Events and observers](http://devdocs.magento.com/guides/v2.3/extension-dev-guide/events-and-observers.html#events).
```

2019-08-27 03:07 UTC, jeff-matthews approved these changes

2019-08-27 03:08 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5706](https://jira.corp.magento.com/browse/ENGCOM-5706) has been created to process this Pull Request

2019-08-28 13:36 UTC, engcom-Delta commented
Hi @diazwatson I think module description after **# Magento_Authorizenet module** header is not correct.
Could you take a look?

2019-08-28 13:52 UTC, diazwatson commented
@engcom-Delta many thanks for catching this 👍

2019-09-11 05:55 UTC, ihor-sviziev commented
Hi @jeff-matthews,
Could you review latest changes that were made by @diazwatson?

2019-09-11 12:37 UTC, jeff-matthews approved these changes

2019-09-11 12:38 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5706](https://jira.corp.magento.com/browse/ENGCOM-5706) has been created to process this Pull Request

2019-09-12 08:36 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-12 19:02 UTC, merged