Update Magento_AsynchronousOperations ReadMe
magento/magento2 pull request #24278
Opened 2019-08-25 06:36 UTC by diazwatson

### Description (*)

Updates ReadMe for the Magento_AsynchronousOperations module.

### Fixed Issues (if relevant)

1. magento/devdocs https://github.com/magento/devdocs/issues/4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-26 13:14 UTC, jeff-matthews requested changes

2019-08-26 13:14 UTC, jeff-matthews commented on app/code/Magento/AsynchronousOperations/README.md
> +This component is designed  to provide response for client who launched the bulk operation as soon as possible and postpone handling of operations moving them to background handler.
```suggestion
This component is designed to provide a response for a client that launched the bulk operation as soon as possible and postpone handling of operations moving them to the background handler.
```

2019-08-26 13:14 UTC, jeff-matthews commented on app/code/Magento/AsynchronousOperations/README.md
> +You can extend Magento_AsynchronousOperations module using the following configuration files in `view/adminhtml/ui_component/` directory:
```suggestion
You can extend Magento_AsynchronousOperations module using the following configuration files in the `view/adminhtml/ui_component/` directory:
```

2019-08-27 03:08 UTC, jeff-matthews approved these changes

2019-08-27 03:10 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5708](https://jira.corp.magento.com/browse/ENGCOM-5708) has been created to process this Pull Request

2019-08-28 21:57 UTC, merged