SymLinks cross compatibility between Apache versions
magento/magento2 pull request #24288
Opened 2019-08-26 09:19 UTC by angelo983

### Description (*)

This file change to solve error 500 with Apache 2.4 installed with a default configuration.

### Fixed Issues (if relevant)
Error 500 .htaccess: Option FollowSymLinks not allowed here

### Manual testing scenarios (*)

1. Apache 2.4
2. Magento 2.3

### Questions or comments

Due to security reasons Apache 2.4 comes with FollowSymLinks disabled and SymLinksIfOwnerMatch enabled:
- http://httpd.apache.org/docs/2.2/misc/perf-tuning.html#symlinks
- http://httpd.apache.org/docs/2.4/en/mod/mod_rewrite.html#RewriteRule

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-26 09:21 UTC, angelo983 commented
This pull request replace #23545

2019-08-27 04:06 UTC, ihor-sviziev approved these changes

2019-08-27 04:08 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5709](https://jira.corp.magento.com/browse/ENGCOM-5709) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-27 04:08 UTC, magento-engcom-team commented
@angelo983 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-08-27 17:04 UTC, ihor-sviziev commented
Hi @angelo983,
Looks like you pushed your changes that not related to this PR. Could you force push your branch to latest commit that related to this PR?

2019-08-27 17:05 UTC, ihor-sviziev requested changes

2019-08-27 17:05 UTC, ihor-sviziev commented on app/code/Magento/Checkout/i18n/en_US.csv
> +"Enter your billing address to get a tax estimate.","Enter your billing address to get a tax estimate."
These changes are not related to this PR

2019-08-27 17:06 UTC, angelo983 reviewed
Sometimes GitHub makes me go crazy. Please remove this commit, I will open a new Pull Request with another branch for Label not translated in Summary Estimate Shipping

2019-08-30 04:29 UTC, ihor-sviziev approved these changes

2019-08-30 04:31 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5709](https://jira.corp.magento.com/browse/ENGCOM-5709) has been created to process this Pull Request

2019-08-30 11:14 UTC, rodrigowebjump approved these changes

2019-08-30 11:16 UTC, magento-engcom-team commented
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-5709](https://jira.corp.magento.com/browse/ENGCOM-5709) has been created to process this Pull Request

2019-09-11 12:08 UTC, engcom-Alfa commented
@angelo983 Could you, please, provide more details how to reproduce the issue? Thanks!

2019-09-13 16:27 UTC, angelo983 commented
@engcom-Alfa Install by composer Magento 2.3 in a server with Apache 2.4 standard configuration. Due to security reasons Apache 2.4 comes with FollowSymLinks disabled and SymLinksIfOwnerMatch enabled, so without this changes to .htaccess files you will have immediatly an error in home page too.

2019-09-13 16:30 UTC, ihor-sviziev commented
On which OS are you installing Apache? I tried official docker images with
Apache And mod php - it works fine

On Fri, Sep 13, 2019 at 19:28 Angelo Romano <notifications@github.com>
wrote:

> @engcom-Alfa <https://github.com/engcom-Alfa> Install by composer Magento
> 2.3 in a server with Apache 2.4 standard configuration. Due to security
> reasons Apache 2.4 comes with FollowSymLinks disabled and
> SymLinksIfOwnerMatch enabled, so without this changes to .htaccess files
> you will have immediatly an error in home page too.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/24288?email_source=notifications&email_token=AAOJOUMB4XVOR7UEY4JCFFTQJO5RZA5CNFSM4IPNUS42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6VQ53I#issuecomment-531304173>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOJOUJ46N46ZGJ7M2TG57TQJO5RZANCNFSM4IPNUS4Q>
> .
>

2019-09-13 21:38 UTC, angelo983 commented
I replayed the problem in both CentOs 7 and Debian 9 with Apache 2.4 default config with fastcgi or nginx and php 7.1 or 7.2

2019-09-16 05:12 UTC, ihor-sviziev commented
@engcom-Alfa, could you review comment by @angelo983 and try to reproduce it again?

2019-09-16 07:42 UTC, engcom-Alfa commented
@ihor-sviziev , ok. I will try to reproduce the issue again

2019-10-02 12:36 UTC, ihor-sviziev commented
Hi @engcom-Alfa,
Is there any updates?

2019-10-15 09:36 UTC, engcom-Golf requested changes
Hi, @angelo983 thank you for Pull Request, but we have some troubling with changes.  this config does not default apache configuration, it depends on distributive or Hosting provider configuration like this -> https://wiki.centos-webpanel.com/options-followsymlinks-not-allowed so The way by depending configuration by apache version not correct here. as you can see we have a few functional tests fail with these changes, as symlinks now are broken. Could you please fix the failed test and provide the solution not depending on the apache version?

2019-10-15 09:36 UTC, engcom-Golf commented on .htaccess
> +        Options +SymLinksIfOwnerMatch
This is not default apache configuration for all systems

2019-10-30 07:52 UTC, ihor-sviziev commented
@angelo983  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-10-30 07:52 UTC, closed without merging