Adding out of stock items to wishlist shows success message but fails #21519
magento/magento2 pull request #24300
Opened 2019-08-27 02:26 UTC by Rus0

### Description (*)

Adding verification of stock and catalog flag for showing out of stock products, the wishlist shows the products if they are out of stock with the flag show out of stock.

### Fixed Issues (if relevant)

1. magento/magento2#21519: Adding out of stock items to wishlist shows success message but fails

### Manual testing scenarios (*)

1. Add to wishlist a product without stock. Throws new exception
2. Enable cataloginventory/options/show_out_of_stock
3. Add to wishlist a product without stock. It will add it correctly.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-03 19:19 UTC, sidolov approved these changes

2019-09-03 19:20 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5760](https://jira.corp.magento.com/browse/ENGCOM-5760) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-03 19:21 UTC, sidolov requested changes
@Rus0 , please, take a look at failed tests

2019-09-04 15:08 UTC, Rus0 commented
I am going to upload later today a commit

2019-09-05 16:53 UTC, sidolov approved these changes

2019-09-05 16:54 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5760](https://jira.corp.magento.com/browse/ENGCOM-5760) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-09 08:14 UTC, engcom-Delta commented
Hi @Rus0 Unfortunately, I cannot reproduce issue on 2.3-develop.
**Manual testing scenario:**
- Create product with Stock Status=Out of Stock
- Set Stores->Configuration->Catalog->Inventory->Stock Options->Display Out of Stock Products=Yes
- Create customer and login
- Add product to wishlist

**Result:**
:heavy_check_mark: Product is added to wishlist and success message is shown
![-24300Main png_009](https://user-images.githubusercontent.com/51681379/64514174-cde89080-d2f2-11e9-8c73-51a5d76e9c56.png)

2019-09-09 15:02 UTC, Rus0 commented
Try adding it when it is out of stock and Stores->Configuration->Catalog->Inventory->Stock Options->Display Out of Stock Products = NO

2019-09-17 07:56 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-20 00:34 UTC, merged