Resolved edit configurable product from cart doesn't show selected swatch options #24306
magento/magento2 pull request #24308
Opened 2019-08-27 05:41 UTC by rani-webkul

Resolved edit configurable product from cart doesn't show selected swatch options #24306

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#24306: Edit configurable product from cart doesn't show selected swatch options

### Manual testing scenarios (*)

1. create a configurable product with more than one swatch attribute
2. add product to cart
3. then edit the same from cart

![issue](https://user-images.githubusercontent.com/44425160/63743930-75110500-c8bb-11e9-903b-cc4881f7efb8.png)

2019-08-27 17:15 UTC, VladimirZaets approved these changes

2019-08-27 17:16 UTC, VladimirZaets requested changes
Hi @rani-webkul. Thanks for collaboration. Please check failed builds.

2019-08-27 17:17 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5716](https://jira.corp.magento.com/browse/ENGCOM-5716) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-30 05:55 UTC, rani-webkul commented
Hi @VladimirZaets I think these failed builds are not related to this commit. Could you please check it once?

2019-08-30 08:50 UTC, rani-webkul commented
@magento give me test instance
@magento give me 2.3-develop instance

2019-08-30 08:50 UTC, magento-engcom-team commented
Hi @rani-webkul. Thank you for your request. I'm working on Magento instance for you

2019-08-30 08:50 UTC, magento-engcom-team commented
Hi @rani-webkul, here is your [new Magento instance](https://pr-24308.instances.magento-community.engineering).
Admin access: [https://pr-24308.instances.magento-community.engineering/admin](https://pr-24308.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-08-30 08:53 UTC, rani-webkul commented
@magento give me 2.3-develop instance

2019-08-30 08:53 UTC, magento-engcom-team commented
Hi @rani-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-08-30 08:53 UTC, magento-engcom-team commented
Hi @rani-webkul, here is your [Magento instance](https://i-24308-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24308-2-3-develop.instances.magento-community.engineering/admin](https://i-24308-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-08-31 13:06 UTC, rani-webkul commented
Hi @VladimirZaets, I think these failed builds are not related to this commit. Could you please check it once?

2019-09-04 08:42 UTC, rani-webkul commented
@VladimirZaets Please review again.

2019-09-04 17:29 UTC, sidolov approved these changes

2019-09-04 17:31 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5716](https://jira.corp.magento.com/browse/ENGCOM-5716) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-06 08:31 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:**
![before](https://user-images.githubusercontent.com/51679138/64413212-c0849980-d099-11e9-97c9-ac9d25a666ab.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/64413229-ca0e0180-d099-11e9-8c55-cce96ddef709.png)

2019-09-07 16:12 UTC, merged