resolve CData section too big on Export grid issue 24311
magento/magento2 pull request #24314
Opened 2019-08-27 06:18 UTC by gaurangpadhiyar007

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-27 06:18 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24314) <br/>All committers have signed the CLA.

2019-08-27 12:52 UTC, Stepa4man commented
@magento run all tests

2019-08-27 13:01 UTC, gaurangpadhiyar007 commented
@magento area adminhtml

2019-08-28 12:15 UTC, gaurangpadhiyar007 commented
@magento-cicd2 @magento-admin run area adminhtml

@magento-cicd2 @magento-admin run all tests

2019-09-03 04:37 UTC, gaurangpadhiyar007 commented
@magento run area adminhtml
@magento run all tests

2019-09-03 23:04 UTC, rodrigowebjump commented
Hi @gaurangpadhiyar007 Please, 
Thanks for your contribution.
I kindly ask you to add an appropriate description and tests scenarios to your PR.

Please, do not forget to review the failing tests.

Thanks
Thanks

2019-09-04 07:48 UTC, gaurangpadhiyar007 reviewed
Issue of merging run test solved

2019-09-04 12:21 UTC, gaurangpadhiyar007 commented
@rodrigowebjump
 I have made all changes as per given errors but as I solve them new un-neccessary errors are generating by Automated testing tool, Please test the commit on Magento instance.

2019-09-20 15:58 UTC, sidolov requested changes

2019-09-20 15:58 UTC, sidolov commented on app/code/Magento/ImportExport/Ui/DataProvider/ExportFileDataProvider.php
> +        File $fileIO,
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-10-04 15:21 UTC, sidolov commented
@gaurangpadhiyar007  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-10-04 15:21 UTC, closed without merging