Adding the ability to translate text displayed in the "massActions co…
magento/magento2 pull request #24339
Opened 2019-08-28 12:31 UTC by Daseraf

…nfirm" modal window

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-28 12:31 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24339) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24339) before we can accept your contribution.<br/><hr/>**s.matyavin@mygento.ru** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-08-28 14:52 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/grid/massactions.js
> +                confirmMessage = confirmData.message + ' (' + $t('Records selected: %1').replace('%1', total) + ')';
This text will not be translated. For successful translation, we should have a full string match, in this case translation `'Records selected: 1', 'Records selected: 2', ...` will not be found because we can't provide translation for all value of variables and in general we shouldn't do it. 

In this case, you can translate `Records selected` separately and after that concat it with value from variable.

2019-08-28 14:53 UTC, VladimirZaets requested changes
Hi @Daseraf , please, sign CLA, otherwise, we can't process your pull request

2019-08-29 05:51 UTC, Daseraf commented on app/code/Magento/Ui/view/base/web/js/grid/massactions.js
> +                confirmMessage = confirmData.message + ' (' + $t('Records selected: %1').replace('%1', total) + ')';
You are not completely right.
I give an example of a valid solution:
ru_RU.csv - "`Records selected:% 1", "Records selected:% 1"`
![screenshot-192 168 88 215_8081-2019 08 29-08_49_41](https://user-images.githubusercontent.com/11287957/63913781-0a3a0800-ca3a-11e9-982a-138dc44dce92.png)
As described in devDocs:
[Translate theme strings](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/translations/translate_theory.html#add_strings_js)

2019-08-29 05:56 UTC, Daseraf commented
> Hi @Daseraf , please, sign CLA, otherwise, we can't process your pull request

CLA is signed.

2019-09-03 19:12 UTC, VladimirZaets approved these changes

2019-09-03 19:13 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5758](https://jira.corp.magento.com/browse/ENGCOM-5758) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-03 19:13 UTC, magento-engcom-team commented
@Daseraf thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-09-05 06:27 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-06 15:35 UTC, sdzhepa commented
Hello @Daseraf

As I can see https://github.com/magento/magento2/pull/24339#issuecomment-525723957 you did not sign CLA.

I could be because of emails related to your github user `@Daseraf` and commits are different.
In other words, `s.matyavin@mygento.ru`(email in https://github.com/magento/magento2/pull/24339/commits) is not added to `@Daseraf` github user profile.

Could you please follow the [instruction](https://github.com/magento/magento2/pull/24339#issuecomment-525723957) to resolve this situation?

> **s.matyavin@mygento.ru** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-09-20 15:52 UTC, sidolov commented
@Daseraf  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-20 15:52 UTC, closed without merging