magento/magento2#: “Bad request” is never shown
magento/magento2 pull request #24331
Opened 2019-08-28 08:52 UTC by atwixfirster

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#24330: “Bad request” error message is never shown #

### Manual testing scenarios (*)

**Preconditions**
1. Set `Require Emails Confirmation` option to `Yes` on back-end side

<img width="1536" alt="back-end" src="https://user-images.githubusercontent.com/13585327/63840660-22524e80-c98a-11e9-8ef0-7791c07cf505.png">

**Steps to reproduce**
1. Create new customer

2. You will get a confirmation link in the email

3. Set empty customer id parameter in the confirmation URL.

For example, confirmation URL is

```
http://<MAGENTO-INSTANCE>/customer/account/confirm/?id=XXX&key=3D384de80ffb30003a72d29e5326932547
```

Remove XXX from the provided URL:

```
http://<MAGENTO-INSTANCE>/customer/account/confirm/?id=&key=3D384de80ffb30003a72d29e5326932547
```

4. Open URL in browser

```
http://<MAGENTO-INSTANCE>/customer/account/confirm/?id=&key=3D384de80ffb30003a72d29e5326932547
```

**Expected result:** `Bad request` message is displayed for customer

<img width="634" alt="expected" src="https://user-images.githubusercontent.com/13585327/63840534-e6b78480-c989-11e9-8f92-821a8f36ee35.png">

**Actual result:** `There was an error confirming the account` message is displayed for customer

<img width="627" alt="actual" src="https://user-images.githubusercontent.com/13585327/63840547-ecad6580-c989-11e9-9c1c-efd4be0520f0.png">

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

2019-08-28 11:23 UTC, dmytro-ch commented
@magento give me test instance

2019-08-28 11:23 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-08-28 11:23 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-24331.instances.magento-community.engineering).
Admin access: [https://pr-24331.instances.magento-community.engineering/admin](https://pr-24331.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-08-28 11:29 UTC, dmytro-ch requested changes
@atwixfirster, could you please update the unit test?

2019-08-28 15:06 UTC, atwixfirster commented
> @atwixfirster, could you please update the unit test?

 **fixed**

@dmytro-ch, could you please review?

Thank you!

2019-08-29 16:28 UTC, dmytro-ch approved these changes

2019-08-29 16:29 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5733](https://jira.corp.magento.com/browse/ENGCOM-5733) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-02 08:33 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-02 19:12 UTC, merged