Resolved configurable product image not showing as per selected options #24383
magento/magento2 pull request #24384
Opened 2019-08-31 06:38 UTC by rani-webkul

Resolved configurable product image not showing as per selected options #24383

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#24383: configurable product image not showing as per selected options 

### Manual testing scenarios (*)

1. Create a configurable product with swatches
2. Set image for each associated products
3. Navigate to product page at frontend
4. Select second or third image of main product
5 . Then select any option it's not showing the actual image, it's showing previous image.

### Questions or comments

2019-09-04 05:57 UTC, dmytro-ch commented
@magento give me test instance

2019-09-04 05:57 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-09-04 05:57 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-24384.instances.magento-community.engineering).
Admin access: [https://pr-24384.instances.magento-community.engineering/admin](https://pr-24384.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-09-04 06:12 UTC, dmytro-ch requested changes
Hi @rani-webkul, unfortunately, the issue is still reproducible in your working branch according to the steps to reproduce mentioned in PR description.

2019-09-06 11:15 UTC, rani-webkul commented
@dmytro-ch as I checked, the actual issue is in magento 2.3-develop branch. It's working fine on Magento 2.3.2 version and the issue is, in magento 2.3-develop configurable product selected option image is not showing in any condition.

2019-09-12 13:28 UTC, ihor-sviziev commented
Hi @rani-webkul,

Could you configure product on test instance?

I just tried on https://pr-24384.instances.magento-community.engineering/test.html - it doesn't work : (

2019-09-12 13:32 UTC, ihor-sviziev commented
@rani-webkul sorry for confusing. I mist misunderstood your comment at first.

Looks like issue when none of images are selected for configurable products - blocks this PR. Could you report it?
For now I'll put this PR is on hold until original issue will be fixed.

2019-09-12 13:36 UTC, rani-priya commented
Hi @ihor-sviziev,
could you please let me know, where I can report it?

2019-09-12 13:37 UTC, ihor-sviziev commented
> Hi @ihor-sviziev,
> could you please let me know, where I can report it?

Here: https://github.com/magento/magento2/issues/new/choose :)

2019-09-12 13:44 UTC, rani-priya commented
Hi @ihor-sviziev ,
https://github.com/magento/magento2/issues/24571

2019-09-13 05:31 UTC, ihor-sviziev commented
Thank you for report! We'll keep this Pull Request "on hold" till #24571 will be fixed

2019-09-13 06:27 UTC, ihor-sviziev requested changes
Hi @rani-webkul,

While investigating https://github.com/magento/magento2/issues/24571 - I found that issue with first image was already fixed in https://github.com/magento/magento2/pull/23033, that I was able to reproduce on test instance in https://github.com/magento/magento2/issues/24571.

Could you confirm that this issue was fixed?

2019-09-13 06:30 UTC, rani-priya commented
@ihor-sviziev 
Please look into https://pr-24384.instances.magento-community.engineering/test.html now this commit is working.

Actual issue is https://github.com/magento/magento2/issues/24383

2019-09-13 06:39 UTC, ihor-sviziev commented
> @ihor-sviziev
> Please look into https://pr-24384.instances.magento-community.engineering/test.html now this commit is working.
> 
> Actual issue is #24383

It worked for me even without changes from this PR just because of changes from https://github.com/magento/magento2/pull/23033 (were merged 3 months ago).

I just cheked it on following test instance that was created from 2.3-develop: 
https://i-24571-2-3-develop.instances.magento-community.engineering/test-config.html

Here is video: [test config - Google Chrome 2019-09-13 09-37-39.zip](https://github.com/magento/magento2/files/3608665/test.config.-.Google.Chrome.2019-09-13.09-37-39.zip)

2019-09-16 08:34 UTC, ihor-sviziev commented
Hi @rani-webkul,
Thank you for your contribution!

I'm closing this PR as this issue was already fixed in https://github.com/magento/magento2/pull/23033.

Feel free to add any comments if you have any.

2019-09-16 08:34 UTC, closed without merging