Resolve "New Block" form still show "Store View" field in "Single Store Mode" issue24387
magento/magento2 pull request #24397
Opened 2019-08-31 14:25 UTC by edenduong

### Description (*)

1. Resolve magento/magento2#24387: "New Block" form still show "Store View" field in "Single Store Mode" 

Solution: Add the class to handle the case `$this->storeManager->isSingleStoreMode()
`
### Fixed Issues (if relevant)

1. magento/magento2#24387: "New Block" form still show "Store View" field in "Single Store Mode" 
### Manual testing scenarios (*)

1. Magento 2.3-develop
2. Enable "Single Store Mode"
![image](https://user-images.githubusercontent.com/8234209/64060881-2fc33f00-cbfd-11e9-81ac-1c622f65ff1c.png)
3. Go to backend
4. Content->Blocks
5. Add New Block
=> no Store View field in the form

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-03 10:13 UTC, swnsma requested changes
Please check my comments.

2019-09-03 10:13 UTC, swnsma commented on app/code/Magento/Cms/Ui/Component/Form/Field/StoreView.php
> +use Magento\Framework\View\Element\UiComponentInterface;
In current implementation, this `use` is redundant.

2019-09-03 10:13 UTC, swnsma commented on app/code/Magento/Cms/Ui/Component/Form/Field/StoreView.php
> +class StoreView extends Field
I am not sure if this class should be placed right here.
Could we move this to `Magento\Store\Ui\Component\Form\Field\StoreView`?

2019-09-03 14:15 UTC, edenduong commented
@magento give me test instance

2019-09-03 14:15 UTC, magento-engcom-team commented
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

2019-09-03 14:15 UTC, magento-engcom-team commented
Hi @edenduong, here is your [new Magento instance](https://pr-24397.instances.magento-community.engineering).
Admin access: [https://pr-24397.instances.magento-community.engineering/admin](https://pr-24397.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-09-03 14:22 UTC, edenduong commented
> Please check my comments.

I have changed the source code. Please check it again. Thanks !

2019-09-04 08:01 UTC, swnsma approved these changes

2019-09-04 08:02 UTC, magento-engcom-team commented
Hi @swnsma, thank you for the review.
[ENGCOM-5762](https://jira.corp.magento.com/browse/ENGCOM-5762) has been created to process this Pull Request

2019-09-05 08:39 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-05 22:51 UTC, merged