change  shopping cart to minicart
magento/magento2 pull request #24411
Opened 2019-09-02 13:25 UTC by sunilit42

Fixed issue :- #24409

2019-09-03 05:27 UTC, XxXgeoXxX requested changes
Magento has a lot of additional entities that relevant to this label.
We could not change this label only in one place and skip others.
Please, recheck and update translations, MFTF tests, comment, etc to prevent misunderstanding.

2019-09-03 06:16 UTC, sunilit42 commented
@XxXgeoXxX 

thanks for the review .

I did into translate csv file and I checked into test folder nothing related to this.

2019-09-03 06:57 UTC, XxXgeoXxX commented on app/code/Magento/Checkout/i18n/en_US.csv
> +"Mini Cart","Mini Cart"
This translate has already existed. It can be removed.

2019-09-03 06:58 UTC, XxXgeoXxX approved these changes

2019-09-03 06:59 UTC, magento-engcom-team commented
Hi @XxXgeoXxX, thank you for the review.
[ENGCOM-5752](https://jira.corp.magento.com/browse/ENGCOM-5752) has been created to process this Pull Request
:eight_spoked_asterisk: @XxXgeoXxX, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-04 10:56 UTC, engcom-Delta commented
Hi @sunilit42 There are left few occurrences of "Shopping Cart Sidebar" in the comments:
![image](https://user-images.githubusercontent.com/51681379/64249148-ad4bbf80-cf1b-11e9-8dc4-571efaecfb98.png)



Could you take a look?

2019-09-06 09:48 UTC, sunilit42 commented
> Hi @sunilit42 There are left few occurrences of "Shopping Cart Sidebar" in the comments:
> ![image](https://user-images.githubusercontent.com/51681379/64249148-ad4bbf80-cf1b-11e9-8dc4-571efaecfb98.png)
> 
> Could you take a look?

I did please check it, I did not do for one file because it is related to admin shopping  cart

2019-09-06 10:11 UTC, XxXgeoXxX approved these changes

2019-09-06 10:13 UTC, magento-engcom-team commented
Hi @XxXgeoXxX, thank you for the review.
[ENGCOM-5752](https://jira.corp.magento.com/browse/ENGCOM-5752) has been created to process this Pull Request
:eight_spoked_asterisk: @XxXgeoXxX, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-09 11:54 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-10 11:26 UTC, engcom-Foxtrot commented
@magento run all tests

2019-09-10 13:53 UTC, engcom-Foxtrot commented
@magento run all tests

2019-09-12 14:02 UTC, merged