Fix/24442 images not loaded from media storage
magento/magento2 pull request #24459
Opened 2019-09-05 09:20 UTC by lpouwelse

### Description (*)
#24442 The media storage uses the media directory as base directory in syncing (Files in the storage database doesn't contain media/ as directory prefix).
So i changed the base directory for synchronization to the media directory, and passes the files relative to this base path to the constructor in the get.php
#24446 Error occurs during resizing of wysiwyg images with product/catalog config, so validate if resizing is possible
#24445 One off both path's contains a / so remove slashes before during comparison

### Fixed Issues (if relevant)
1. fixes magento/magento2#24442: Since Magento 2.3 the wysiwyg images are not loaded anymore from media storage database.
2. fixes magento/magento2#24445: var/resource_config.json is regenerated each time an image is requested by get.php (media/wysiswig/image.jpg)
3. fixes magento/magento2#24446: First time wysiwyg image is loaded by media storage, placeholder image is shown.

### Manual testing scenarios (*)
1. Fresh install of magento with sample data
2. Synchronize media files to datase, according the manual (https://docs.magento.com/m2/ce/user_guide/system/media-storage-database.html)
3. Add following record to core_config_data table
    - scope: default
    - scope_id: 0
    - path: web/seo/use_rewrites
    - value: 1
4. Remove an image from media/wysiwyg editor directory
5. Load it on the front-end (according issue #24446) the first time you see a placeholder image( instead of 404 page).  After refreshing you see the image.

### Questions or comments
not applicable

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-24 06:52 UTC, ihor-sviziev commented
Hi @lpouwelse,
I just fixed one small issue in imports that caused issue for all tests, will review this PR once tests will be ran

2019-09-25 06:04 UTC, ihor-sviziev requested changes

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/App/Media.php
> +use Magento\Tests\NamingConvention\true\string;
Hi @lpouwelse,
Could you remove this import? It's coming from static tests, and not correct. Because of it - all tests are failing

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/App/Media.php
> +        \Magento\MediaStorage\Model\File\Storage\Config $config,
Unfortunately replacing constructor arguments - is not backward compatible change. Please keep original arguments as is (even if they're not used anymore) and add new as optional constructor arguments

Please review and do the same for all constructors

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/App/Media.php
> +    private function isAllowedResource($resource)
Would be great to define argument type and return type for new method

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/Model/Cache/Type/MediaStorage.php
> +    public function generateCacheIdUsingContext($prefix)
I didn't get where it's used. Could you point me?

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/Model/File/Storage/Config.php
> -class Config
It's not backward compatible change, please revert this change. If this class is not used - please mark it with tag `@deprecated` with description why it was deprecated and tag `@see` that will describe what should be used instead

2019-09-25 06:04 UTC, ihor-sviziev commented on pub/get.php
> +if (is_readable($mediaAbsPath) && !is_dir($mediaAbsPath)) {
Looks like you changed logic - earlied if `$relativePath` wasn't allowed - was returned 404 page. Now - file will be returned. This is regression.

Could you double check it?

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/App/Media.php
> +        MediaStorageConfig $mediaStorageConfig,
Hi @lpouwelse,
This change is not backward compatible. We can't remove/replace constructor arguments.

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/Model/File/Storage/MediaStorageConfig.php
> +                $this->cache->save($this->serializer->serialize($this->allowedResources), self::CACHE_ID);
Earlier we had locking mechanism during writing cache to the file. It was preventing issues with parallel requests. I think it's missing there

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/Model/File/Storage/MediaStorageConfig.php
> +    protected $cacheFilePath;
All new properties have to be private or public. In this case it's better to change visibility to private

2019-09-25 06:04 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/App/Media.php
> +            if (stripos($this->relativeFileName, $this->productMediaConfig->getBaseMediaPathAddition()) === 0) {
As I understood - we hadn't this check earlier. Why it's needed?

2019-09-25 06:07 UTC, ihor-sviziev commented
Hi @lpouwelse,
I reviewed your PR and added my comments, please review them. 

Also please review tests results, looks like your changes caused regression.

2019-10-10 14:40 UTC, sidolov commented
@lpouwelse I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-10-10 14:40 UTC, closed without merging

2022-01-05 19:31 UTC, lfolco commented
Any chance to re-open this PR and merge it? I'm seeing this issue currently on 2.3.