Require missing "doctrine/instantiator" dependency
magento/magento2 pull request #24542
Opened 2019-09-10 19:16 UTC by ulftietze

Yea, well. If you are gonna use code from "doctrine/instantiator", you may declare that in composer.json.

If you won't add this to the composer.json, following will happen, if you use that MessageQueue Module:
```
Fatal error: Uncaught Error: Class 'Doctrine\Instantiator\Exception\InvalidArgumentException' not found in /var/www/html/vendor/magento/framework-message-queue/MessageValidator.php on line 123

Error: Class 'Doctrine\Instantiator\Exception\InvalidArgumentException' not found in /var/www/html/vendor/magento/framework-message-queue/MessageValidator.php on line 123

Call Stack:
    0.0001     388800   1. {main}() /var/www/html/bin/magerun:0
    0.0410    2203840   2. N98\Magento\Application->run() /var/www/html/bin/magerun:8
    1.9646   47865896   3. N98\Magento\Application->run() phar:///var/www/html/bin/magerun/src/N98/Magento/Application.php:327
    1.9647   47865896   4. N98\Magento\Application->doRun() phar:///var/www/html/bin/magerun/vendor/symfony/console/Application.php:117
    2.0298   49673432   5. N98\Magento\Application->doRun() phar:///var/www/html/bin/magerun/src/N98/Magento/Application.php:237
    2.0300   49673432   6. N98\Magento\Application->doRunCommand() phar:///var/www/html/bin/magerun/vendor/symfony/console/Application.php:185

{"messages":{"error":[{"code":500,"message":"Fatal Error: 'Uncaught Error: Class 'Doctrine\\Instantiator\\Exception\\InvalidArgumentException' not found in \/var\/www\/html\/vendor\/magento\/framework-message-queue\/MessageValidator.php:123\nStack trace:\n#0 \/var\/www\/html\/vendor\/magento\/framework-message-queue\/MessageValidator.php(102): Magento\\Framework\\MessageQueue\\MessageValidator->validatePrimitiveType(Array, 'string', 'neusta.cart-bul...')\n#1 \/var\/www\/html\/vendor\/magento\/framework-message-queue\/MessageValidator.php(67): Magento\\Framework\\MessageQueue\\MessageValidator->validateMessage(Array, 'string', 'neusta.cart-bul...')\n#2 \/var\/www\/html\/vendor\/magento\/framework-message-queue\/Publisher.php(79): Magento\\Framework\\MessageQueue\\MessageValidator->validate('neusta.cart-bul...', Array)\n#3 \/var\/www\/html\/vendor\/magento\/framework-message-queue\/PublisherPool.php(89): Magento\\Framework\\MessageQueue\\Publisher->publish('neusta.cart-bul...', Array)\n#4 \/var\/www\/html\/_modules\/neusta-bulk-add-to-cart\/src\/Model\/Publisher\/BulkAddToCart.php(26): Magento\\Framework\\MessageQueue\\PublisherPool->p' in '\/var\/www\/html\/vendor\/magento\/framework-message-queue\/MessageValidator.php' on line 123","trace":"Trace is not available."}]}}bin/magento some:test  0,52s user 0,10s system 17% cpu 3,560 total
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-11 04:34 UTC, ihor-sviziev requested changes
Hi @ulftietze,
Could you add some steps to reproduce, because I never had this issue and still not clear how to reproduce it?

Thank you

2019-09-16 08:17 UTC, ihor-sviziev approved these changes

2019-09-16 08:18 UTC, ihor-sviziev commented
I just checked - we have refference to this class in following file:
https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/lib/internal/Magento/Framework/MessageQueue/MessageValidator.php#L8

So message queue should not work at all

2019-09-16 08:18 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5845](https://jira.corp.magento.com/browse/ENGCOM-5845) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-16 08:18 UTC, magento-engcom-team commented
@ulftietze thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-09-16 08:23 UTC, ihor-sviziev requested changes
Hi @ulftietze,
I just analyzed it again, probably that's just mistake. There should be used `\InvalidArgumentException`. Could you revert changes in composer.json file and replace throwed extepction to `\InvalidArgumentException`?

2019-09-16 14:45 UTC, ulftietze commented
Hello,

should be done yet. You probably should squash those commits ^^

2019-09-16 17:41 UTC, ihor-sviziev commented
Hi @ulftietze,
Now changes looks good to me.

Unfortunately we can’t squash commits during merging PR due to limitations in the delivery system 😢 

Could you squash all changes you did to single commit?

Thank you!

2019-09-19 12:26 UTC, ihor-sviziev requested changes
Hi @ulftietze,
Now changes looks good to me.

Unfortunately we can’t squash commits during merging PR due to limitations in the delivery system 😢

Could you squash all changes you did to single commit?

Also static tests are failing, please fix them

Thank you!

2019-09-20 13:07 UTC, ihor-sviziev commented
Hi @ulftietze,
Will you be able to squash your changes & fix static tests?

2019-09-22 10:37 UTC, ulftietze commented
Hey,

sorry at the moment i am really busy and can't find time for this. Maybe this week i'll got time for this :)

2019-09-23 18:57 UTC, sidolov approved these changes
Let's proceed with QA activities. I believe @ulftietze will squash the commits soon.

2019-09-23 18:58 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5845](https://jira.corp.magento.com/browse/ENGCOM-5845) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-26 08:29 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:**
![before](https://user-images.githubusercontent.com/51679138/65670317-ce508d80-e04d-11e9-83db-fec2a5ef6ee8.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/65670368-ea542f00-e04d-11e9-8a2f-cae1468da2f2.png)

2019-09-27 23:36 UTC, merged