Fixed downloadable selected links price not added to product main price on cart configure page. #24579
magento/magento2 pull request #24580
Opened 2019-09-13 04:57 UTC by rani-webkul

Fixed downloadable selected links price not added to product main price on cart configure page. #24579

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#24579: downloadable selected links price not added to product main price on cart configure page.

### Manual testing scenarios (*)

1. Create a downloadable product with some downloadable links
2. Select link and add to cart
3. edit that product from cart

### Questions or comments

![downloadable](https://user-images.githubusercontent.com/44425160/64838503-19f84580-d611-11e9-9360-817f89bfdffb.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-13 06:53 UTC, ihor-sviziev requested changes
Hi @rani-webkul,
Please review my comment related to jquery ui change.

Also commit author's email is not related to your GitHub account (you can check that by clicking on icon near commit message, it should be clickable). Could you fix that by adding email to your github account OR changing commit author email & force push?

2019-09-13 06:53 UTC, ihor-sviziev commented on app/code/Magento/Downloadable/view/frontend/web/js/downloadable.js
> +    'jquery/ui',
Why did you changed this line?
It was changed to `jquery-ui-modules/widget` in order to make split jquery UI to separate modules. I believe it's not related to the fix. If so - please revert this change

2019-09-13 06:59 UTC, rani-webkul commented on app/code/Magento/Downloadable/view/frontend/web/js/downloadable.js
> +    'jquery/ui',
Done, Actually it was by mistake.

2019-09-13 07:02 UTC, ihor-sviziev commented
@rani-webkul author email still not related to your github account on 1st commit. 
https://github.com/magento/magento2/pull/24580/commits
![image](https://user-images.githubusercontent.com/1873745/64843344-938e3480-d60d-11e9-80ee-9d6fe28478ba.png)
Please fix that

2019-09-13 08:12 UTC, rani-webkul commented
@ihor-sviziev done

2019-09-13 11:21 UTC, ihor-sviziev commented
Hi @rani-webkul, unfortunately commit still not related to your github account 😢

2019-09-13 11:33 UTC, rani-webkul commented
Hi @ihor-sviziev, Could you please let me know how I can fix this issue?
I'm facing this issue from initial days, and it's due to I have changed my username.

2019-09-13 12:37 UTC, ihor-sviziev commented
@rani-webkul, please check your email in `git config --global user.email`. Looks like there is typo, there is no `@` symbol.
To change it execute following command `git config --global user.email your@email.com` where your@email.com - your email linked to GitHub account

2019-09-13 12:43 UTC, rani-webkul commented
Hi @ihor-sviziev, Thank you.

2019-09-13 13:45 UTC, ihor-sviziev approved these changes

2019-09-13 13:46 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5837](https://jira.corp.magento.com/browse/ENGCOM-5837) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-16 08:19 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-20 00:34 UTC, merged