fixed schedule currency_rates_update cron job not working
magento/magento2 pull request #24590
Opened 2019-09-14 15:21 UTC by brunoroeder

### Description (*)

Fixed the schedule currency_rates_update cron job. 

![Screenshot at Sep 14 12-14-48](https://user-images.githubusercontent.com/405469/64910078-79298900-d6e9-11e9-9230-5c9fcc01906d.png)

### Fixed Issues (if relevant)

1. #23846: Schedule currency_rates_update cron job not working

### Manual testing scenarios (*)

    1. Go to admin panel
    2. Access: Stores > Configuration > General Tab > Currency Setup > Scheduled Import Setting section
    Set values:
       -- Enable -> Set Yes
       -- Service -> Fixer.io
       -- Start Time -> Fill current time + 5 min
       -- Frequency -> Choose Daily
    3. Clear the Magento cache
    4. Run php bin/magento cron:run from command line
    5. The currency_rates_update cron job exists in cron_schedule table

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-16 00:07 UTC, brunoroeder commented
@magento give me test instance

2019-09-16 00:07 UTC, magento-engcom-team commented
Hi @brunoroeder. Thank you for your request. I'm working on Magento instance for you

2019-09-16 00:08 UTC, magento-engcom-team commented
Hi @brunoroeder, here is your [new Magento instance](https://pr-24590.instances.magento-community.engineering).
Admin access: [https://pr-24590.instances.magento-community.engineering/admin](https://pr-24590.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-09-16 19:29 UTC, sidolov requested changes

2019-09-16 19:29 UTC, sidolov commented on app/code/Magento/Directory/Model/Observer.php
> +    public function scheduledUpdateCurrencyRates()
Unfortunately, we are not able to change the public method signature according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-09-23 18:59 UTC, sidolov approved these changes

2019-09-23 19:01 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5934](https://jira.corp.magento.com/browse/ENGCOM-5934) has been created to process this Pull Request

2019-09-24 12:27 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-09-26 01:18 UTC, merged