Added description discount  for each summary(cart, order)
magento/magento2 pull request #24595
Opened 2019-09-14 17:10 UTC by MaxSouza

### Description (*)

Added description discount  for each summary(cart, order)

### Fixed Issues (if relevant)

1. magento/magento2#3594: Discount Description does not get displayed on cart page

### Manual testing scenarios (*)

1. Create a coupon with description
2. Add product to cart and apply coupon
3. Check if discount description is displayed on summary

### Questions or comments

![image](https://user-images.githubusercontent.com/5350377/64911522-2a83eb00-d6f9-11e9-9be1-cb889a59cf21.png)
![image](https://user-images.githubusercontent.com/5350377/64911537-52734e80-d6f9-11e9-9242-2ce0fb362ac6.png)

![image](https://user-images.githubusercontent.com/5350377/64911528-3ec7e800-d6f9-11e9-824f-90dc4eb0fe5e.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-14 17:58 UTC, kalpmehta commented
@magento give me 2.3-develop instance

2019-09-14 17:58 UTC, magento-engcom-team commented
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-09-14 17:59 UTC, magento-engcom-team commented
Hi @kalpmehta, here is your [Magento instance](https://i-24595-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24595-2-3-develop.instances.magento-community.engineering/admin](https://i-24595-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2019-09-14 18:08 UTC, kalpmehta commented
@MaxSouza I don't think this is an issue. Showing shopping cart rule description may not work for everybody. Some merchants are using it for internal purpose, some might have quite bigger description text which cannot fit in the cart totals box. This is more like a workaround for the merchants who want to use description field to display some kind of message near the discount label.

2019-09-14 18:19 UTC, MaxSouza commented
@kalpmehta Can you comment on issue, please?

2019-09-14 18:22 UTC, kalpmehta commented
Sure @MaxSouza. Thank you for your contribution. I will comment on the issue and will also wait for some other reviewer if they think otherwise.

2019-09-16 23:14 UTC, kalpmehta commented
@MaxSouza Can you please fix the space issues and add the tests?

2019-09-16 23:16 UTC, kalpmehta requested changes

2019-09-16 23:16 UTC, kalpmehta commented on app/code/Magento/SalesRule/Model/RulesApplier.php
> +
please remove this empty line

2019-09-16 23:16 UTC, kalpmehta commented on app/code/Magento/SalesRule/Model/RulesApplier.php
> +     * @param \Magento\Framework\Event\ManagerInterface                       $eventManager
Please remove the tabs and extra spaces, follow Magento's formatting

2019-09-16 23:16 UTC, kalpmehta commented on app/code/Magento/SalesRule/Model/RulesApplier.php
> +     * @param  Rule    $rule
please remove extra spaces

2019-09-18 01:09 UTC, MaxSouza commented
@kalpmehta I'm working on tests

2019-09-23 03:02 UTC, kalpmehta commented
@magento give me test instance

2019-09-23 03:02 UTC, magento-engcom-team commented
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

2019-09-23 03:03 UTC, magento-engcom-team commented
Hi @kalpmehta, here is your [new Magento instance](https://pr-24595.instances.magento-community.engineering).
Admin access: [https://pr-24595.instances.magento-community.engineering/admin](https://pr-24595.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-09-23 03:28 UTC, kalpmehta approved these changes

2019-09-23 03:29 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-5926](https://jira.corp.magento.com/browse/ENGCOM-5926) has been created to process this Pull Request

2019-09-23 07:44 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-26 01:18 UTC, merged

2020-04-16 08:37 UTC, aman3103 commented
@magento-engcom-team I don't think this is a good change to show the coupon description in admin also as customer care team then don't have any information about which code is applied as in coupon code field also they don't have way to filter the code using description.