magento/magento2#24337: Creating a product through API doesn't accept…
magento/magento2 pull request #24604
Opened 2019-09-15 12:25 UTC by yrobag

… gallery entries at the same time

### Description (*)
- fixed issue by moving products validation over processing media gallery and change error message for processing media gallery for product without media gallery attribute
- error that was reported in the issue was caused with wrong attribute_set which was provided in the request. If we want to create product with media gallery and provided attribute_set_id that doesn't exist or do not contains gallery attribute we receive error "The product that was requested doesn't exist. Verify the product and try again.".

### Fixed Issues (if relevant)

1. magento/magento2 #24337: Creating a product through API doesn't accept gallery entries at the same time

### Manual testing scenarios (*)
1. Get admin token using REST method (POST) /rest/V1/integration/admin/token
2. Use received token in method (POST) /rest/V1/products and in body use data provided in issue
3. If You use attribute_set_id that doesn't exist you should get error "Invalid product data: Invalid attribute set entity type". 
4. If you use attribute_set_id that exists  but doesn't contain attribute gallery you should receive error "The product that was requested doesn't have gallery attribute. Verify the product and try again.". 
5. If you use  attribute_set_id that exists  and contains attribute gallery, product should create successfully with provided media gallery data". 

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-15 18:00 UTC, kalpmehta requested changes

2019-09-15 18:00 UTC, kalpmehta commented on app/code/Magento/Catalog/Model/ProductRepository/MediaGalleryProcessor.php
> +                __("The product that was requested doesn't have gallery attribute. Verify the product and try again.")
@yrobag Can you please update translations for this as well?

2019-09-27 05:56 UTC, kalpmehta commented
@yrobag Can you please do the requested changes and cover all the tests?

2019-09-30 17:04 UTC, sidolov commented
@yrobag  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-30 17:04 UTC, closed without merging