#24376  update save/load query building logic, check definition of columns us…
magento/magento2 pull request #24609
Opened 2019-09-15 15:30 UTC by pierzakp

…ed in conditions and prepare their values properly

### Description (*)

This PR is proposing changes which are casting condition types according to the column definition type during select/update, which will be improving performance especially on int type indexes, currently, in many cases, it is passed as a string, in result index is not used.

### Fixed Issues (if relevant)

1. magento/magento2#24376: Poor performance on sales order update - string to integer

### Manual testing scenarios (*)

1. turn on query logging, or view in mysql queries being ran
2. update an order
3. look at query
4. entity_id will be int

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-16 13:38 UTC, o-iegorov commented on app/code/Magento/Sales/Model/ResourceModel/EntityAbstract.php
> +        $condition = $this->getConnection()->quoteInto($this->getIdFieldName() . '=?', $idFieldValue);
quoteInto() will return quoted value in any case, value after prepareColumnValue() will be quoted anyway, that makes this value preparation little bit useless.

2019-09-16 15:16 UTC, sidolov requested changes

2019-09-16 15:16 UTC, sidolov commented on lib/internal/Magento/Framework/Model/ResourceModel/AbstractResource.php
> +    protected function _getColumnDefinition($column, $table)
Unfortunately, we are not allowed to add new protected methods to the @api classes according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-09-30 17:04 UTC, sidolov commented
@pierzakp , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2019-09-30 17:04 UTC, closed without merging