magento/magento2#24564: Captcha not shown on contact form
magento/magento2 pull request #24601
Opened 2019-09-14 19:05 UTC by JorgeArmandoBittencourt

- Fixed issue. Remove the <container> tag xml because in content textarea does not have how to render, and the module need this to apply the CAPTCHA.

### Description (*)

1. Removed the <container> tag in xml
2. Replaces $block->getChildHtml("form.additional.info") in to $block->getChildHtml()
3. Add in all pages the CAPTCHA block
4. All contact forms without initialized with XML file will be type contact.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Add a new contact form in admin, not in XML file.
2. Enter in the page and see if is rendered.

### Questions or comments

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-21 11:43 UTC, josefbehr commented
@JorgeArmandoBittencourt please check and fix the failing tests. Why did you rename the block?

2019-11-20 08:11 UTC, Karlasa requested changes

2019-11-20 08:11 UTC, Karlasa commented on app/code/Magento/Captcha/view/frontend/layout/contact_index_index.xml
> +        <referenceBlock name="contactForm">
name should not be removed and kept as container

2019-11-20 08:11 UTC, Karlasa commented on app/code/Magento/Captcha/view/frontend/layout/default.xml
> +        <referenceBlock name="contactForm">
Why it's needed? You can't reference block that have not been created. 
cacheable="false" will disable FPC for all default layouts.

2019-11-20 08:14 UTC, Karlasa commented
@JorgeArmandoBittencourt  Your solution breaks FPC and is hard to understand meaning of why it's needed in first place. Could you improve Manual testing scenarios area because for me it's not clear what you mean by "Add a new contact form in admin". 

Cheers, 
Karla

2019-12-03 17:43 UTC, VladimirZaets commented
@JorgeArmandoBittencourt , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-12-03 17:43 UTC, closed without merging