Fix whats this scroll top
magento/magento2 pull request #24602
Opened 2019-09-14 19:09 UTC by vinidziuba

### Description (*)

Solution : changed the tag for the strong tag and took the href.
### Fixed Issues (if relevant)

1. magento/magento2#24511: Click "What 's this" link scroll to the top of page

### Manual testing scenarios (*)

1. Go to backend
 Store->Configuration->Customer->Persistent Shopping Cart->Enable Persistence to Yes.
2. Go to Frontend, Sign In
3. In Remember me, click "What's this?" link

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-15 18:54 UTC, kalpmehta requested changes
@vinidziuba Please fix all the space issues in the PR

2019-09-15 18:56 UTC, kalpmehta requested changes

2019-09-15 18:56 UTC, kalpmehta commented on app/code/Magento/Persistent/view/frontend/templates/remember_me.phtml
> +
remove the empty line

2019-09-15 18:56 UTC, kalpmehta commented on app/code/Magento/Persistent/view/frontend/templates/remember_me.phtml
> +    <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?= $block->escapeHtmlAttr($rememberMeId) ?>" <?php if ($block->isRememberMeChecked()) : ?> checked="checked" <?php endif
remove the space you added here

2019-09-15 18:56 UTC, kalpmehta commented on app/code/Magento/Persistent/view/frontend/templates/remember_me.phtml
> +            <?= $block->escapeHtml(__('What\'s this?')) ?>
make this in one line like original code

2019-09-15 18:56 UTC, kalpmehta commented on app/code/Magento/Persistent/view/frontend/web/template/remember-me.html
> +        data-bind="checked: isRememberMeCheckboxChecked, attr: {title: $t('Remember Me'), 'data-scope': dataScope}" />
in one line please

2019-09-15 18:56 UTC, kalpmehta commented on app/code/Magento/Persistent/view/frontend/web/template/remember-me.html
> +            data-bind="i18n: 'Check \'Remember Me\' to access your shopping cart on this computer even if you are not signed in.'"></span>
in one line please

2019-09-17 17:43 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24602) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24602) before we can accept your contribution.<br/><hr/>**Vinicius Dziuba** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-09-23 11:30 UTC, vinidziuba reviewed
Okay

2019-09-23 19:06 UTC, sidolov approved these changes

2019-09-23 19:07 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5935](https://jira.corp.magento.com/browse/ENGCOM-5935) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-23 19:07 UTC, magento-engcom-team commented
@vinidziuba thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-09-23 19:41 UTC, kalpmehta approved these changes

2019-09-23 19:42 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-5935](https://jira.corp.magento.com/browse/ENGCOM-5935) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-24 09:39 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-26 01:18 UTC, merged