Update Magento_Backup module ReadMe
magento/magento2 pull request #24614
Opened 2019-09-15 23:11 UTC by diazwatson

### Description (*)

Updates ReadMe for the Magento_Backup module.

### Fixed Issues (if relevant)

1. magento/devdocs https://github.com/magento/devdocs/issues/4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-16 12:44 UTC, jeff-matthews requested changes
Minor editorial suggestions

2019-09-16 12:44 UTC, jeff-matthews commented on app/code/Magento/Backup/README.md
> +The Magento_Backup allows administrators to perform backups and rollbacks. Types of backups include system, database and media backups. This module relies on the Cron module to schedule backups.
```suggestion
The Magento_Backup module allows administrators to perform backups and rollbacks. Types of backups include system, database, and media backups. This module relies on the Cron module to schedule backups.
```

2019-09-16 12:44 UTC, jeff-matthews commented on app/code/Magento/Backup/README.md
> +The Magento_Backup does not affect the storefront.
```suggestion
The Magento_Backup module does not affect the storefront.
```

2019-09-16 15:25 UTC, sidolov approved these changes

2019-09-16 15:26 UTC, sidolov commented
@diazwatson I have made changes mentioned by @jeff-matthews , will proceed with delivery

2019-09-16 15:26 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5850](https://jira.corp.magento.com/browse/ENGCOM-5850) has been created to process this Pull Request

2019-09-16 15:37 UTC, jeff-matthews approved these changes

2019-09-16 15:38 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5850](https://jira.corp.magento.com/browse/ENGCOM-5850) has been created to process this Pull Request

2019-09-17 09:36 UTC, diazwatson commented
Thanks @sidolov @jeff-matthews 👍

2019-09-19 20:41 UTC, merged