Module Layered Navigation fixes
magento/magento2 pull request #24630
Opened 2019-09-17 14:09 UTC by alexeya-ven

### Description (*)
This changes fixes issue #24619 

### Fixed Issues (if relevant)

1. magento/magento2#24619: Elasticsearch category page issues when 1 column layout is used

### Manual testing scenarios (*)

1. Choose category with products and set 1 column design to it (Catalog -> Categories -> Edit Category -> Design -> Layout -> "1 column"
2. Save category
3. Flush cache
4. Open this category on website and change sort order to "Price"
5. Go to page 2

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-17 14:45 UTC, ihor-sviziev approved these changes

2019-09-17 14:46 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5854](https://jira.corp.magento.com/browse/ENGCOM-5854) has been created to process this Pull Request

2019-09-19 14:05 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-09-27 09:43 UTC, engcom-Foxtrot requested changes
Hello, @alexeya-ven.
I don't think we can accept this PR.
First of all, this change would affect not only Elasticsearch, but any other search engine, and that may cause some unpredictable problems in the future.
Secondly, the bug is caused by Magento\LayeredNavigation\Block\Navigation\Category element order: in 1 column layout, it is rendered before \Magento\Catalog\Block\Category\View, while in other layouts render order is reversed.

2019-09-30 05:06 UTC, alexeya-ven commented
Hi @engcom-Foxtrot 
Thanks for reply. Unfortunately, I don't have time to investigate this issue deeper.

2019-09-30 05:06 UTC, closed without merging