Fix Configurable product tier prices follow price display settings for tax #12225
magento/magento2 pull request #24631
Opened 2019-09-17 15:44 UTC by MatthijsBreed

### Description (*)
These changes fix issue #12225 

### Fixed Issues (if relevant)
1. #12225: Tier pricing tax shows only including tax

### Manual testing scenarios (*)
1. Create a configurable product
2. Add tier prices to the related simple products
3. Change price display settings (tax/display/type) to either the 'excluding tax' or 'both' option
4. Flush cache
5. View the product page and select a configuration option
6. Tier prices should now correctly display with or without tax

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-17 15:44 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24631) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24631) before we can accept your contribution.<br/>

2019-09-17 15:59 UTC, lewisvoncken requested changes

2019-09-17 15:59 UTC, lewisvoncken commented on app/code/Magento/ConfigurableProduct/Block/Product/View/Type/Configurable.php
> +                    'priceExTax' => $this->localeFormat->getNumber($tierPrice['price']->getValue('tax')),
please rename priceExTax to priceExclTax

2019-09-19 13:48 UTC, lewisvoncken approved these changes

2019-09-20 05:05 UTC, kalpmehta commented
@MatthijsBreed Please add all the automated tests

2019-10-04 14:58 UTC, sidolov approved these changes

2019-10-04 14:59 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-6003](https://jira.corp.magento.com/browse/ENGCOM-6003) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-04 14:59 UTC, magento-engcom-team commented
@MatthijsBreed thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-10-04 20:54 UTC, kalpmehta approved these changes

2019-10-04 20:55 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-6003](https://jira.corp.magento.com/browse/ENGCOM-6003) has been created to process this Pull Request

2019-10-08 08:24 UTC, engcom-Delta commented
@MatthijsBreed Could you correct price font style to be in consistence with string font style "Buy %1 for %2 each and" ?
![image](https://user-images.githubusercontent.com/51681379/66378887-1a3ff280-e9bd-11e9-828f-13d2ccfb5bb6.png)
Example from 2.3-develop:
![image](https://user-images.githubusercontent.com/51681379/66378995-46f40a00-e9bd-11e9-9e04-21296f274123.png)

2019-10-22 18:36 UTC, VladimirZaets approved these changes

2019-10-22 18:37 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6003](https://jira.corp.magento.com/browse/ENGCOM-6003) has been created to process this Pull Request

2019-10-24 21:37 UTC, sdzhepa commented
@magento give me test instance

2019-10-24 21:37 UTC, magento-engcom-team commented
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

2019-10-25 10:59 UTC, engcom-Delta commented
Hi @MatthijsBreed . Could you fix issue with price display?
![#24631PRNot properDisplay](https://user-images.githubusercontent.com/51681379/67565472-2f8f7d80-f72e-11e9-8005-d73612b92307.jpg)

**Manual testing scenario:**

- Configurable product is created
- Add tier price to the related simple product
- Set Display Product Prices In Catalog=Including and Excluding Tax
- Add Tax rule to have different price for Incl.Tax and Excl. Tax

**Result:**
:x: Tier prices are shown without spaces
:x: Tier prices not include tax type(e.g., Incl.Tax and Excl. Tax)

2019-11-06 17:19 UTC, VladimirZaets commented
@MatthijsBreed, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-11-06 17:19 UTC, closed without merging