Update Magento_Braintree module ReadMe
magento/magento2 pull request #24679
Opened 2019-09-21 00:09 UTC by diazwatson

### Description (*)

Updates ReadMe for the Magento_Braintree module.

### Fixed Issues (if relevant)

1. magento/devdocs https://github.com/magento/devdocs/issues/4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-21 00:22 UTC, pmclain approved these changes

2019-09-21 00:23 UTC, magento-engcom-team commented
Hi @pmclain, thank you for the review.
[ENGCOM-5920](https://jira.corp.magento.com/browse/ENGCOM-5920) has been created to process this Pull Request

2019-09-21 04:37 UTC, kalpmehta commented
@diazwatson I don't see very detailed README.md file in any other module(s). If we add these details in one module's README, we may have to add it to other modules as well going forward to maintain consistency and that might become an overhead. Do you see this README template in any core module that you are following?

2019-09-21 10:23 UTC, diazwatson commented
@kalpmehta have you seen the task description as well as all the PR (already merge) associated to this task? https://github.com/magento/devdocs/issues/4451?

2019-09-21 18:21 UTC, kalpmehta commented
@diazwatson My bad, I missed the devdocs issue conversations. I will go ahead and approve this. I believe @jeff-matthews will have a final review on the content. Thanks for your contribution!

2019-09-22 22:23 UTC, diazwatson commented
No worries, thanks :)

2019-09-23 06:46 UTC, engcom-Delta commented
**Notice:** QA not applicable

2019-09-23 12:24 UTC, jeff-matthews requested changes

2019-09-23 12:24 UTC, jeff-matthews commented on app/code/Magento/Braintree/README.md
> +This module interacts the following layouts and layout handles in the `view/adminhtml/layout` directory:
```suggestion
This module interacts with the following layouts and layout handles in the `view/adminhtml/layout` directory:
```

2019-09-23 19:27 UTC, sidolov commented on app/code/Magento/Braintree/README.md
> +This module interacts the following layouts and layout handles in the `view/adminhtml/layout` directory:
Changes are applied

2019-09-23 19:27 UTC, sidolov approved these changes

2019-09-23 19:28 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5920](https://jira.corp.magento.com/browse/ENGCOM-5920) has been created to process this Pull Request

2019-09-23 19:49 UTC, jeff-matthews approved these changes

2019-09-23 19:50 UTC, magento-engcom-team commented
Hi @jeff-matthews, thank you for the review.
[ENGCOM-5920](https://jira.corp.magento.com/browse/ENGCOM-5920) has been created to process this Pull Request

2019-09-26 01:17 UTC, merged