fixed https://github.com/magento/magento2/issues/24452
magento/magento2 pull request #24733
Opened 2019-09-26 09:20 UTC by MaxRomanov4669

### Description (*)
added enter button event handler and fixed js issue based on PR https://github.com/magento/magento2/pull/24498

### Fixed Issues (if relevant)
1. magento/magento2#24452: Category Admin UI does not save tree changes unless OK button is clicked

### Manual testing scenarios (*)
1. Navigate to Catalog -> Categories
2. Drag a category to a different location in the tree
3. When the warning dialog appears hit enter on the keyboard
4. Note that a no spinner appears and changes are not saved
5. refresh the page and see that your changes were not saved.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-26 09:20 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24733) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24733) before we can accept your contribution.<br/><hr/>**Max Romanov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-09-26 09:29 UTC, VladimirZaets requested changes
Hi @MaxRomanov4669. Thanks for collaboration. According to our rules all code should be covered by tests. Can you please cover your fix by functional test, or at least by JS unit.
If you need some help or guide how to running functional tests locally, please let us know.

2019-09-27 07:34 UTC, MaxRomanov4669 commented
Hi @VladimirZaets . Can you please provide information about functional tests? I do not see any js tests for js script in app/code/Magento/Catalog/view/adminhtml/templates/catalog/category/tree.phtml

2019-09-30 20:31 UTC, sidolov commented
Hi @MaxRomanov4669  please, sign CLA, otherwise, we can't process your pull request

2019-10-02 08:05 UTC, closed without merging