Added identification ID of the provided option type by its sku in the specified store.
magento/magento2 pull request #24762
Opened 2019-09-27 14:20 UTC by magelogger

Description:
1. Added optionTypeSkus private property to the class app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php

2. Added $optionSku parameter to the getExistingOptionTypeId function.

3. Added identification ID of the provided option type by its sku in the specified store.

Fixed Issues
1. magento/magento2#23601: Magento2 Impossible to update custom option value based on custom option SKU

Manual testing scenarios:
1.Create product with Customizable Options
2. Check option_type_id in table catalog_product_option_type_value
3. Export this product
4. Edit in csv file custom options title 
5. Save scv file and import it
6. Check option_type_id in table catalog_product_option_type_value

Expected result:
Value option_type_id is not changed when row is updated

2019-09-30 20:59 UTC, sidolov commented
Hi @magelogger , please, sign CLA, otherwise, we can't process your pull request

2019-10-02 06:13 UTC, aleron75 commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +    private function getExistingOptionTypeId($optionId, $storeId, $optionTypeTitle, $optionSku)
When applicable, I would assign types to function parameters as long as to the return value.
In this case, the method is private and we wouldn't break any backward compatibility. What do you think?

2020-08-03 22:21 UTC, VladimirZaets commented
@magento run all tests

2020-08-03 22:21 UTC, VladimirZaets commented
Hi @magelogger  , please, sign CLA, otherwise, we can't process your pull request

2020-08-03 22:22 UTC, VladimirZaets requested changes
Hi @magelogger  , please, sign CLA, otherwise, we can't process your pull request

2020-08-19 09:14 UTC, engcom-Charlie commented
Hi @magelogger, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-08-19 09:14 UTC, closed without merging