Resolved Issue 24708
magento/magento2 pull request #24773
Opened 2019-09-27 15:10 UTC by drpayyne

### Description (*)
Resolved [Issue 24708](https://github.com/magento/magento2/issues/24708) 

### Fixed Issues (if relevant)
1. magento/magento2#24708: Module Analytics ExportDataHandler.php

### Manual testing scenarios (*)
1. Execute `analytics_collect_data` cron task of Advanced Reporting module
2. Data creation will be generated within Magento document root `var/` folder instead of `tmp/`

### Questions or comments
Please refer Issue linked for more information

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-27 19:26 UTC, sidolov requested changes
Please, take a look at failed tests

2019-09-28 11:27 UTC, drpayyne commented
@sidolov Fixed failing unit tests, but static tests is throwing warnings for usage of `dirname()` and `is_dir()`, both which have been unchanged and already in use prior to my PR.

2019-09-30 20:40 UTC, sidolov approved these changes

2019-09-30 20:41 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-5978](https://jira.corp.magento.com/browse/ENGCOM-5978) has been created to process this Pull Request

2019-10-02 11:38 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2019-10-03 05:12 UTC, kalpmehta commented
@sidolov I am seeing other modules are also using `SYS_TMP` location to save files. E.g. Paypal, RMA. 
@drpayyne Are these files really big? Is the concern here that it would fill up /tmp directory on the server?

2019-10-03 05:22 UTC, drpayyne commented
@kalpmehta I fixed the confirmed issue here: https://github.com/magento/magento2/issues/24708

2019-10-03 12:59 UTC, merged