#22484 - Customer address States are duplicated in backend.
magento/magento2 pull request #24770
Opened 2019-09-27 14:55 UTC by DmitryPirvu

- Added condition before addCountryRegions for avoiding duplication of regions in DB.

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-27 14:55 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=24770) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24770) before we can accept your contribution.<br/>

2019-09-27 19:23 UTC, sidolov requested changes

2019-09-27 19:23 UTC, sidolov commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForAustralia.php
> +        $collection = $this->regionCollectionFactory->create();
According to implementation `$this->regionCollectionFactory` is null here and will cause fatal error. Looks like you missed to inject regionCollectionFactory dependency via constructor

2019-09-27 19:24 UTC, sidolov commented
Hi @DmitryPirvu  , please, sign CLA, otherwise, we can't process your pull request

2019-09-30 20:36 UTC, sidolov requested changes

2019-09-30 20:36 UTC, sidolov commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForAustralia.php
> +        CollectionFactory $regionCollectionFactory
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-10-18 19:25 UTC, VladimirZaets commented
@DmitryPirvu, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-10-18 19:25 UTC, closed without merging