Fix #20332 - address fields sort order fixes
magento/magento2 pull request #24784
Opened 2019-09-30 08:19 UTC by Bartlomiejsz

### Description (*)

This is fix for #20332

### Fixed Issues (if relevant)

1. magento/magento2#20332: Shipping address form City, State/Province, Zip/Postal Code, Country not in right Order in checkout

### Manual testing scenarios (*)

1. Go to any form that contains customer address fields
2. Four fields order should be changed to: **Country, State/Province, City, Zip/Postal Code** 

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-03 17:31 UTC, lenaorobei requested changes
Please address BC comment and pull latest changes from `2.4-develop` branch.

2020-02-03 17:31 UTC, lenaorobei commented on app/code/Magento/Checkout/Block/Checkout/LayoutProcessor.php
> +        $this->options = $options ?: ObjectManager::getInstance()->get(Options::class);
`ObjectManager` is redundant here.

2020-02-25 19:35 UTC, lenaorobei commented
@Bartlomiejsz could you please merge latest changes and address review comment?
Appreciate that!

2020-02-26 10:02 UTC, Bartlomiejsz commented on app/code/Magento/Checkout/Block/Checkout/LayoutProcessor.php
> +        $this->options = $options ?: ObjectManager::getInstance()->get(Options::class);
@lenaorobei done

2020-02-26 10:02 UTC, Bartlomiejsz commented
@lenaorobei done, ready for review

2020-02-26 15:21 UTC, lenaorobei approved these changes

2020-02-26 15:23 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-6990](https://jira.corp.magento.com/browse/ENGCOM-6990) has been created to process this Pull Request

2020-02-27 11:42 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-02-28 22:05 UTC, merged