Resolved Issue #24785
magento/magento2 pull request #24800
Opened 2019-10-01 05:24 UTC by drpayyne

### Description
Resolved issue #24785 

Added a JS method to handle the state of checked links in a downloadable product. The state is now managed and reflected in the label
- `Unselect all` is displayed _only_ when all links are checked
- `Select all` is displayed otherwise

### Fixed Issues
1. magento/magento2#24785: All selected values still display as Select all in downloadable product

### Manual testing scenarios
1. Create a downloadable product in admin _with_ downloadable links which can be purchased separately
2. Go to storefront, add the product to cart with both downloadable links checked
3. Open minicart and edit the product just added
4. Verify state of checked links with the conditions mentioned in the description

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-01 05:27 UTC, drpayyne commented
@magento give me test instance

2019-10-01 05:27 UTC, magento-engcom-team commented
Hi @drpayyne. Thank you for your request. I'm working on Magento instance for you

2019-10-01 05:28 UTC, magento-engcom-team commented
Hi @drpayyne, here is your [new Magento instance](https://pr-24800.instances.magento-community.engineering).
Admin access: [https://pr-24800.instances.magento-community.engineering/admin](https://pr-24800.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-10-01 11:35 UTC, VladimirZaets requested changes
Hi @dryadav. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

2019-10-01 11:42 UTC, drpayyne commented
@VladimirZaets Thank you. Although, I'm confused a bit. What test should I write? I have only added a method in a jQuery widget. :thinking:

2019-10-01 12:08 UTC, VladimirZaets commented
@drpayyne I think in this case we can write a functional test and check what is displayed, or at least  JS unit test, that will check the new method that you created.

If you need documentation how to do it, or some additional information feels free to ask.

2019-10-01 12:12 UTC, drpayyne commented
@VladimirZaets yes, can I have some references or documentations? I've written only PHPUnit tests. Thanks a lot!

2019-10-04 15:40 UTC, sidolov commented
@drpayyne please, refer to Magento devdocs: 
[JavaScript unit testing with Jasmine](https://devdocs.magento.com/guides/v2.3/test/js/jasmine.html)
[Introduction to the Magento Functional Testing Framework](https://devdocs.magento.com/mftf/docs/introduction.html)

2019-10-06 06:42 UTC, drpayyne commented
@sidolov @VladimirZaets Hello, I added an MFTF test to test the changing of the label. Please review my code when you can. And thanks for helping me with the documentation reference.

2019-10-08 18:15 UTC, sidolov approved these changes

2019-10-08 18:17 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-6047](https://jira.corp.magento.com/browse/ENGCOM-6047) has been created to process this Pull Request

2019-10-09 11:51 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:**
![before](https://user-images.githubusercontent.com/51679138/66478980-34a0cb80-eaa4-11e9-8ec4-329caccf327d.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/66479024-4edaa980-eaa4-11e9-8595-8960f63f8ba2.png)

2019-10-15 02:02 UTC, merged