#12524 Custom address attribute shown on frontend
magento/magento2 pull request #24819
Opened 2019-10-02 08:56 UTC by MaxRomanov4669

### Description (*)
added filtration by used_in_forms for address attributes on checkout

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/12524: Custom address attribute shown on frontend

### Manual testing scenarios (*)
1. Create a custom customer_address attribute programmatically
`$eavSetup->removeAttribute('customer_address', 'your_attribute');
        $eavSetup->addAttribute('customer_address', 'your_attribute', array(
            'type' => 'varchar',
            'label' => 'Exact Address ID',
            'input' => 'text',
            'required' => false,
            'unique' => true,
            'system' => 0,
            'global' => ScopedAttributeInterface::SCOPE_WEBSITE,
            'sort_order' => '1'
        ));
$your_attribute = $this->_attributeRepository->get('customer_address', 'your_attribute ');
        $setup->getConnection()
            ->insertOnDuplicate(
                $setup->getTable('customer_form_attribute'),
                [
                    ['form_code' => 'adminhtml_customer_address', 'attribute_id' => your_attribute ->getId()]
                ]
            );
`
2. Fill in the new attribute in a customer (admin panel)
3. login on the storefront and go to checkout

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-04 20:31 UTC, sidolov requested changes
Please, cover changes with automated tests

2019-10-04 20:31 UTC, sidolov commented on app/code/Magento/Customer/Model/Address/CustomAttributesProcessor.php
> +        EavConfig $eavConfig
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2019-10-10 11:54 UTC, MaxRomanov4669 commented
Hi @sidolov , I do no see any tests for app/code/Magento/Customer/Model/Address/CustomAttributesProcessor.php class. Also, method 'filterNotVisibleAttributes' is using only in  app/code/Magento/Customer/Model/Address/CustomerAddressDataFormatter.php line 89

Can you please clarify what tests should I create?

2019-10-10 14:20 UTC, sidolov commented
@MaxRomanov4669 please, cover `filterNotVisibleAttributes` method at least with the unit test

2019-10-21 10:35 UTC, MaxRomanov4669 commented on app/code/Magento/Customer/Model/Address/CustomAttributesProcessor.php
> +        EavConfig $eavConfig
fixed

2019-10-21 10:36 UTC, MaxRomanov4669 commented
@sidolov , please review

2019-10-21 15:52 UTC, sidolov approved these changes

2019-10-21 15:53 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-6142](https://jira.corp.magento.com/browse/ENGCOM-6142) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-25 09:11 UTC, engcom-Bravo commented
Hello @MaxRomanov4669. Thank You for contribution. Currently, on the latest 2.3-develop version we are not able to reproduce the issue Your PR is going to fix.
**Steps to Reproduce**
1. Create a custom customer_address attribute programmatically (As there's described above).
2. Create a customer and set the newly created attribute for his address to be equal "find-me-on-frontend-1". So for now we have got there in the database such a corresponding data:
![addressattribute](https://user-images.githubusercontent.com/51680745/67558700-239cbf00-f720-11e9-973d-e92a91d1a98d.png)
3. Login on the storefront and go to checkout.

**Actual Result**
Our attribute does not appear anywhere on the checkout. Please watch the gif below.
![addressattribute](https://user-images.githubusercontent.com/51680745/67558244-4d091b00-f71f-11e9-9c3d-950ae49d8898.gif)

Could You please confirm You are still able to reproduce the issue on the latest 2.3-develop version. Thank You.

2019-10-25 18:01 UTC, MaxRomanov4669 commented
Hi @engcom-Bravo , you are right. Currently, I am not able to reproduce this bug on latest 2.3-develop. Looks like this was fixed in other PRs

2019-11-01 14:09 UTC, sidolov commented
@MaxRomanov4669 , in this case, I'm closing this PR since the issue is not reproducing right now. 
Thank you for collaboration!

2019-11-01 14:09 UTC, closed without merging