Allow multiple conditions for expired quotes collection
magento/magento2 pull request #24821
Opened 2019-10-02 09:50 UTC by p-bystritsky

### Description (*)

This is a refactoring of magento/magento2/#20777

With Magento\Sales\Cron\CleanExpiredQuotes::setExpireQuotesAdditionalFilterFields() assigning values directly to the attribute and getExpireQuotesAdditionalFilterFields() being protected isn't callable outside the class, hence unable to add more to the existing condition, rather they end up being replaced with the new ones.

### Fixed Issues (if relevant)

-

### Manual testing scenarios (*)

-

### Questions or comments

EE code should also be adapted.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-02 09:58 UTC, engcom-Foxtrot commented
@magento run all test

2019-10-02 16:01 UTC, sivaschenko commented
@p-bystritsky can you please sign the CLA

2019-10-04 09:01 UTC, swnsma requested changes
Hi @p-bystritsky,
Thank you for you review!
Lets discuss your solution under my comment in the code.

2019-10-04 09:01 UTC, swnsma commented on app/code/Magento/Sales/Model/ExpireQuotesFilterFieldsProvider.php
> +class ExpireQuotesFilterFieldsProvider
Do you really believe that we need to have a separated class to collect the filters?
Or could we just add filters as array parameter to the  `app/code/Magento/Sales/Model/ResourceModel/Collection/ExpiredQuotesCollection.php` ?
I can not come with real case when we need a new class.

2019-10-04 12:39 UTC, p-bystritsky commented
Closing this PR due to creation of magento/magento2#24858.

2019-10-04 12:39 UTC, closed without merging