#5891 UI listing drop-down value issue
magento/magento2 pull request #24859
Opened 2019-10-04 12:58 UTC by MaxRomanov4669

### Description (*)
added support comma separeted values for select ui component 

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/5891: UI listing drop-down value issue

### Manual testing scenarios (*)
1. Add to options array value with comma, for example:
Magento\Cms\Model\Page\Source\PageLayout
`public function toOptionArray()
    {
        if ($this->options !== null) {
            return $this->options;
        }

        $configOptions = $this->pageLayoutBuilder->getPageLayoutsConfig()->getOptions();
        $options = [];
        foreach ($configOptions as $key => $value) {
            $options[] = [
                'label' => $value,
                'value' => $key,
            ];
        }

        ///Test
        $options[] = [
            'label' => 'test',
            'value' => 'test, test',
        ];
        ///
        $this->options = $options;
        return $this->options;
    }`
( this is just example you can add similar values to any drop down ui component )
2. For any CMS Page change "Page Layout" value to "test".
3. check the value in the CMS Page grid

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-07 11:14 UTC, ptylek commented
@magento run all tests

2020-08-26 19:44 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/grid/columns/select.js
> +                multiSelectValues = multiSelectValues.map(function (value) {
Can you explain what you try to do here? It's only for converting values to a string?

2020-08-26 19:44 UTC, VladimirZaets requested changes
Hi @MaxRomanov4669. Thanks for collaboration. Please, take a look at my review comments.

2020-09-07 12:44 UTC, gabrieldagama commented
The risk was set to`medium` due to: the suggested changes may impact several modules/areas.

2020-09-11 15:33 UTC, sidolov commented
@MaxRomanov4669 I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-11 15:33 UTC, closed without merging