Correct image params - allow to disable image frame, fix image params hash
magento/magento2 pull request #24866
Opened 2019-10-04 20:24 UTC by unicoder88

### Description (*)

1. Images, generated with "legacy" image generation (generated in backend when image URL is requested), do not respect `product_image_white_borders` [view config](https://github.com/magento/magento2/blob/2.3.2/app/design/frontend/Magento/luma/etc/view.xml#L259) and always have white borders. This is because `false` value does not pass `!empty()` check is [never passed](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Catalog/Helper/Image.php#L216).

    While in Magento 2.3.0 images are generated only when requested, there're extensions that use old classes, for example [Algolia](https://github.com/algolia/algoliasearch-magento-2/blob/1.12.0/Helper/Entity/ProductHelper.php#L706). When new image thumbnail is first time created with "old" generation, image white borders are always set. If the same image thumbnail is first accessed from frontend category page, "new" generation is kicked off and white borders config is respected.

2. Different images - one with frame, and one without frame - result in same hash and the first generated wins:

    - `keep_frame` - before converting https://prnt.sc/peyz9s
    - `keep_frame` - after incorrect converting https://prnt.sc/peyzpr

    This happens because `isset($miscParams['keep_frame']` treats `false` values as "set".

### Manual testing scenarios (*)

1. Edit theme view.xml app/design/frontend/Magento/luma/etc/view.xml:259:
    `<var name="product_image_white_borders">0</var>`
    This is normally overwritten in custom themes.

2. Use a module that uses "legacy" image generation. This can be Algolia, or I prepared a demo module as a showcase - https://github.com/unicoder88/demo-image

3. Upload new product image (JPG) and save, immediately generate image thumbnail. Image is generated with white borders, while should have transparent edges (problem 1 in this PR).

    With demo module, open this URL passing product ID: https://magento2.local/demo_image/thumbnail/make/id/1
  
    https://prnt.sc/pf07ix - image with white borders

4. Open product on frontend. On 2.3.0+ frontend, product thumbnail URL is generated with different classes and correctly respects `product_image_white_borders`, which in theory should make different image thumbnail than in step 3. However, generated image **hash** and thumbnail URL are **same** as in step 3. Normally images with different params should have different hashes. We see white borders on frontend, because thumbnail has already been made  (problem 2 in this PR).

    https://prnt.sc/pf08nt - product in category page, with grayed `<body>` background to highlight thumbnail borders.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2019-10-04 20:27 UTC, sidolov requested changes
Hi @unicoder88 , please, sign CLA, otherwise, we can't process your pull request

2019-10-04 20:32 UTC, unicoder88 commented
Signed Adobe CLA.

2019-10-04 20:33 UTC, sidolov approved these changes

2019-10-04 20:34 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-6013](https://jira.corp.magento.com/browse/ENGCOM-6013) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-11 10:03 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-10-22 20:52 UTC, merged