Create missing directories in imageuploader tree if they don't alread…
magento/magento2 pull request #24878
Opened 2019-10-06 09:47 UTC by hostep

…y exist.

### Description (*)
This is a replacement for https://github.com/magento/magento2/pull/22681
This is partially fixing https://github.com/magento/magento2/issues/22609

I believe we can no longer fully fix https://github.com/magento/magento2/issues/22609 as the bug has existed for too long (2.3.0, 2.3.1, 2.3.2 & 2.3.3 are affected). If people accidentally uploaded images directly in the `pub/media` directory and we fully fix https://github.com/magento/magento2/issues/22609 by changing the storage root, they would no longer be able to access those uploaded images in the wrong directory.

This is a fix which creates those missing directories `pub/media/wysiwyg` or `pub/media/catalog/category` if the image uploader modal is being opened and those directories don't already exists.

Those directories get declared in some xml files (in the `initialMediaGalleryOpenSubpath` node):
- https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Catalog/view/adminhtml/ui_component/category_form.xml#L183
- https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Ui/view/base/ui_component/etc/definition.xml#L149

And then javascript sends those paths in an ajax request using the parameter 'current_tree_path'  after which php then creates those directories if they don't already exist.
It would be great if somebody could take a look at this from a security perspective if this is safe enough, or if some extra security precautions should be taken here to make sure javascript can't willy-nilly create all kinds of unwanted directories? It is probably safe enough due to [that regex checking](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Cms/Helper/Wysiwyg/Images.php#L169-L171), but I'm not 100% sure?

I believe the current code didn't behave like it was originally intended, because [these lines](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Cms/Helper/Wysiwyg/Images.php#L246-L248) are never executed because the `$currentPath` variable only gets set when [that directory already exists](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Cms/Helper/Wysiwyg/Images.php#L240-L242).

I think this problem was probably introduced by some combination of oversights in [MAGETWO-87583](https://github.com/magento/magento2/commit/a083717504f63fd22748fb42d74b63c2906226ef#diff-624b27794e761bd53831eba1ede517bc) and [MAGETWO-87986](https://github.com/magento/magento2/commit/620d37de43bce5d96f59c10628551dd27dad22d1#diff-624b27794e761bd53831eba1ede517bc).

/cc @danmooney2, @davemacaulay, @sidolov

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/22609: Since Magento 2.3 the wysiwyg image uploader incorrectly uses pub/media as storage root

### Manual testing scenarios (*)
1. Setup a vanilla Magento installation
2. Verify that the directories `pub/media/wysiwyg` and `pub/media/catalog/category` don't exist
3. Log into the backend of Magento, and edit a category
4. Open the Content tab, and click the 'Select from Media Gallery' button.
5. Also click the 'Insert Image' button in the content wysiwyg field
6. It is expected the image uploader selects the correct directories even if they previously didn't existed, with this fix this is now happening, and without this fix, it wasn't happening.

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-06 09:53 UTC, hostep commented
Closed and re-opened PR for that CLA check.

2019-10-06 17:30 UTC, hostep commented
While trying to fix the unit tests, I start to feel like some more things needs to get refactored, because this seems to be becoming quite a mess.
The behavior seems to be correct now, but the code is really not ok I think.

I'll wait a bit on feedback before continuing this.

To sumarize what I think is needed here (behavioral-wise):
- The Storage Root should always be 'pub/media'
- The selected directory in the tree should be the one passed in the `current_tree_path` parameter
- If the selected directory (or one of its parents) doesn't exist, it should be created automatically.

2019-10-07 05:32 UTC, kalpmehta requested changes

2019-10-07 05:32 UTC, kalpmehta commented on app/code/Magento/Cms/Helper/Wysiwyg/Images.php
> +                $message = __('The directory %1 is not writable by server.', $currentDir);
Please escape `$currentDir`'s output

2019-10-07 05:32 UTC, kalpmehta commented on app/code/Magento/Cms/Helper/Wysiwyg/Images.php
> +                        $this->_directory->create($currentDir);
Thanks for your concern for security (as mentioned in issue description). I tried to find any security issue with this but couldn't find anything yet. I'm successfully getting "Path is Invalid" when attempting with malicious dir name.

2019-10-07 07:20 UTC, hostep commented on app/code/Magento/Cms/Helper/Wysiwyg/Images.php
> +                $message = __('The directory %1 is not writable by server.', $currentDir);
Escape it for what exactly?

2019-10-07 07:20 UTC, hostep commented
Thanks for the feedback @kalpmehta!
I'll wait a bit with addressing it until I got some other feedback to first see if this is the right approach which I'm taking here.

2019-10-08 05:33 UTC, kalpmehta commented on app/code/Magento/Cms/Helper/Wysiwyg/Images.php
> +                $message = __('The directory %1 is not writable by server.', $currentDir);
@hostep If directory is not writable, script tags can get executed if passed as a variable value. I would recommend escapeHtml method.

2019-10-08 06:55 UTC, hostep commented on app/code/Magento/Cms/Helper/Wysiwyg/Images.php
> +                $message = __('The directory %1 is not writable by server.', $currentDir);
Ok, but this isn't the correct place for adding escaping, right? Should be done when that message is being outputted to the user (which is probably already happening), not in this Helper?
Or have you already tested this and found out that you can inject some executable code in there?

2019-11-13 03:49 UTC, kalpmehta commented on app/code/Magento/Cms/Helper/Wysiwyg/Images.php
> +                $message = __('The directory %1 is not writable by server.', $currentDir);
@hostep You are right. Also, I don't think this can be exploited to affect any other user than the current logged in admin user.

2019-11-13 03:50 UTC, kalpmehta commented
@hostep Do you still want to wait for this PR?

2019-11-13 03:51 UTC, kalpmehta approved these changes

2019-11-13 03:52 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-6275](https://jira.corp.magento.com/browse/ENGCOM-6275) has been created to process this Pull Request

2019-11-19 12:43 UTC, engcom-Alfa commented
@magento run all tests

2019-11-19 13:41 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-11-19 16:09 UTC, sdzhepa commented
@magento restart all tests

2019-11-19 16:11 UTC, sdzhepa commented
@magento run all tests

2019-11-20 12:03 UTC, engcom-Foxtrot commented
@hostep please fix failing tests.

2019-12-01 10:43 UTC, hostep commented
@engcom-Foxtrot, @kalpmehta: sorry for delay, I was away in vacation for the last couple of weeks.
Do I understand it correctly and is the proposed solution considered ok?

In that case, I'll try to update the PR and try to get the tests to become green in the next couple of days/weeks.

2019-12-22 10:14 UTC, hostep commented
Rebased PR on top of latest 2.4-develop, to see what the tests will say.
Will attempt to put some more time into this in the upcoming days/weeks (bit busy in personal life the last few weeks, but I'll see what I can do).

2020-02-09 14:50 UTC, hostep commented
Force pushed some more updates (also rebased again on latest 2.4-develop).
Unit tests should pass now.

I'm still not too happy about this, I feel like the original code was not readable enough and it's still not that much improved I think.

2020-02-17 11:27 UTC, hostep commented
@kalpmehta or somebody else: this can be reviewed again and feedback is welcome :)

2020-03-04 09:55 UTC, ihor-sviziev approved these changes

2020-03-04 09:56 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6275](https://jira.corp.magento.com/browse/ENGCOM-6275) has been created to process this Pull Request

2020-03-04 13:19 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-03-12 04:28 UTC, merged