magento/magento2#24780: Checks like `is customer locked` or `scope` s…
magento/magento2 pull request #24894
Opened 2019-10-07 09:13 UTC by kisroman

…hould happen before the customer will even get a token

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#24780: Checks like `is customer locked` or `scope` should happen before the customer will even get a token

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-17 17:18 UTC, naydav requested changes

2019-10-17 17:18 UTC, naydav commented on app/code/Magento/Customer/Model/ValidateCustomerByShareOption.php
> +            if ((int)$customer->getWebsiteId() !== (int)$websiteId
What about other variants?
Looks like loading of whole customer object only for a couple of fields (website_id, lock_expires) is overhead.

Maybe we can introduce some new "contract" and will use the collection (with `loadData` instead of `load` method) under the hood.

In this case, we will get `CONS` like getting data in a few points/ways but it is very common functionality (will be used very often) and need to take into account performance.

One more way is clearing all of related `tokens` during customer locking.

So, we can communicate with the architecture team and clarify expectations.

2019-10-17 17:18 UTC, naydav commented on app/code/Magento/Customer/Model/ValidateCustomerByShareOption.php
> +                $result = false;
`$result  = true === $this->authentication->isLocked($customerId);`

2019-10-17 17:18 UTC, naydav commented on app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php
> +            $websiteId = $this->storeManager->getStore()->getWebsiteId();
I recommend moving `$websiteId` to input parameters of methods. We should avoid temporal coupling and dependencies on some state of the system.

2019-10-17 17:18 UTC, naydav commented on app/code/Magento/Webapi/composer.json
> +        "magento/module-customer": "*"
My opinion is `magento/module-webapi` *must not* have the *hard* dependency on `module-customer` module.

`magento/module-webapi` can provide some extension point and `module-customer` can use this extension point.

Example:
GraphQl module provede extension point:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/GraphQl/Model/Query/ContextFactory.php#L56-L63

CustomerGraphQl module adds own logic via this extension point:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CustomerGraphQl/Model/Context/AddUserInfoToContext.php#L17
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CustomerGraphQl/etc/graphql/di.xml#L16-L22

2019-10-17 17:18 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/ChangeCustomerPasswordTest.php
> +     * @expectedExceptionMessage The current customer isn't authorized.
I am not sure that a message should be changed. It's not obvious.

If my account was locked but I get a message like `The current customer isn't authorized.` then I can spend a lot of time for understanding what is wrong with my token? But the real reason will be another.

2019-10-24 22:06 UTC, VladimirZaets requested changes
Hi @kisroman. 
Thanks for collaboration.

Please take a look at the review comments.

2019-10-24 22:06 UTC, VladimirZaets commented on app/code/Magento/Customer/Model/ValidateCustomerByShareOption.php
> +            if ((int)$customer->getWebsiteId() !== (int)$websiteId
We use 1 to 1 matching  (customer vs website). We can have a customer with same email on different websites but in DB it's 2 separate records.

According to it, we don't need this check and respectively dependency to customer module

2019-11-11 20:59 UTC, VladimirZaets commented
@kisroman, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-11-11 20:59 UTC, closed without merging