updated abstractSource.php to fix 24698
magento/magento2 pull request #24935
Opened 2019-10-09 07:46 UTC by arushibansal013

getOptionId() should return id/value on basis of label, as of now returning value as well on basis of value only.
This is causing mismatch in some scenario.

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#24698: getOptionId() - parameter input is not specific to option value or option label

### Manual testing scenarios (*)

Have any select type attribute of product with options in below mannner
Have an option with label as "09" and suppose its value assigned by magento is "60".
Now later another option has label "60" whose value assigned is any value by magento.
Now Try to get the option id using getOptionId() method in \module-eav\Model\Entity\Attribute\Source\AbstractSource.php
Expected result : The getOptionId should return optionId or value when we pass option label as parameter.
### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-09 07:54 UTC, kanthy-i95dev approved these changes

2019-12-18 05:10 UTC, arushibansal013 commented
@sidolov Can u help me out in letting me know how can i change semantic version for an EAV module, as of now no version exists.

2020-08-26 19:53 UTC, VladimirZaets requested changes
Hi @arushibansal013. Thanks for collaboration. Can you please resolve conflicts?

2020-09-07 12:46 UTC, gabrieldagama commented
The risk was set to`medium` due to: the suggested changes may impact several modules/areas.

2020-09-11 13:47 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-23 18:04 UTC, sidolov commented
@arushibansal013 could you please take a look at failed tests?

2020-10-01 13:33 UTC, engcom-Foxtrot requested changes

2020-10-01 13:33 UTC, engcom-Foxtrot commented on app/code/Magento/Eav/Model/Entity/Attribute/Source/AbstractSource.php
> +    public function getOptionIdByValue($value)
@arushibansal013 do we realy need this method? As it takes $value and returns $value or null?

2020-10-28 11:18 UTC, engcom-Foxtrot commented
@arushibansal013 I'm closing this pull request due to inactivity. Feel free to reopen.

2020-10-28 11:18 UTC, closed without merging

2022-08-16 15:36 UTC, leissbua commented
Crazy a fix was submitted 3 years ago and the maintainers dont merge it, fooling other EE and CE clients. Made us spend some hours to fix what has been fixed yet, but ignored from the maintainers. 

https://github.com/magento/magento2/pull/24935/commits/33e8fe00601e2e0d08ca324259c7076e9797448e