Fix #24019
magento/magento2 pull request #24947
Opened 2019-10-09 14:15 UTC by korostii

### Description (*)

Update `$this->patchesRegistry` in real-time in order to prevent patches from being applied multiple times.
Consecutively, `\Magento\Framework\Setup\Patch\PatchRegistry::registerPatch()` will recognize that these patches were previously applied through a `$this->patchHistory->isApplied($patchName)` call.

### Fixed Issues (if relevant)

1. magento/magento2#24019: Declarative schema: Patch dependencies can cause a patch to apply twice

### Manual testing scenarios (*)

Please see magento/magento2#24019 for detailed steps.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-09 19:35 UTC, VladimirZaets requested changes
Hi @korostii. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

2019-10-28 18:56 UTC, VladimirZaets approved these changes

2019-10-28 18:57 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6198](https://jira.corp.magento.com/browse/ENGCOM-6198) has been created to process this Pull Request

2019-10-30 07:32 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed 

**Before:**
![before](https://user-images.githubusercontent.com/51679138/67837599-215bab80-faf8-11e9-9cdc-156e58251bf2.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/67837626-2ae51380-faf8-11e9-8b35-d61b34c45b31.png)

2019-11-04 19:59 UTC, merged