magento/magento2#24781: Elasticsearch 6 works with Elasticsearch 5 client on frontend
magento/magento2 pull request #24974
Opened 2019-10-11 07:47 UTC by p-bystritsky

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#24781: Elasticsearch 6 works with Elasticsearch 5 client on frontend

### Manual testing scenarios (*)

1. Open PhpStorm, add breakpoints in:
- Elasticsearch 6.x client: https://github.com/magento/magento2/blob/6d6f11b3ff4dc290c1e53c8822e136547b38f05e/app/code/Magento/Elasticsearch6/Model/Client/Elasticsearch.php#L66
- Elasticsearch 5.x client: https://github.com/magento/magento2/blob/6d6f11b3ff4dc290c1e53c8822e136547b38f05e/app/code/Magento/Elasticsearch/Elasticsearch5/Model/Client/Elasticsearch.php#L71
2. Go to Admin >> Stores >> Configurations >> Catalog >> Catalog >> Search
3. Configure Elasticsearch settings to use "Elasticsearch 6.0+" option
4. Click "Test connection", see that code paused at Elasticsearch 6.x client
5. Save all configs, do reindex
6. Go to any category page, see that code paused at Elasticsearch 6.x client
7. Go to any search page, see that code paused at Elasticsearch 6.x client

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-12 15:06 UTC, ihor-sviziev requested changes
Hi @p-bystritsky,

Your changes looks good to me.
Could you cover your changes with integration test?

2019-10-14 12:26 UTC, p-bystritsky commented
@ihor-sviziev thank you for review.
I have thought about test but have no idea how to implement it.

2019-10-14 12:46 UTC, ihor-sviziev commented
@p-bystritsky i would emulate case that in config we have Elasticsearch 5, then try to get client from `Magento\Elasticsearch\Elasticsearch5\SearchAdapter\ConnectionManager` and check instance of ES5 client, and 2nd test case - with ES6.

What do you think?

2019-10-15 12:13 UTC, p-bystritsky commented
@ihor-sviziev test added, please review.

2019-10-15 12:20 UTC, ihor-sviziev requested changes

2019-10-15 12:20 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/Elasticsearch6/SearchAdapter/ConnectionManagerTest.php
> +    public function testCorrectElasticsearchClient()
Please add one more test case for ES5, just to make sure that we're not returning ES6 client all the time?

2019-10-16 05:03 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/Elasticsearch6/SearchAdapter/ConnectionManagerTest.php
> +    public function testCorrectElasticsearchClient()
Just updated test myself

2019-10-16 10:12 UTC, ihor-sviziev approved these changes

2019-10-16 10:13 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6106](https://jira.corp.magento.com/browse/ENGCOM-6106) has been created to process this Pull Request

2019-10-16 14:47 UTC, engcom-Bravo commented
:heavy_check_mark: QA passed

2019-10-18 00:51 UTC, merged