Fixed #24731 Error message "This element is not expected" with no element.
magento/magento2 pull request #24996
Opened 2019-10-11 18:53 UTC by shikhamis11

Fixed #24731 Error message "This element is not expected" with no element. 

### Preconditions (*)

Magento 2.3.x

### Steps to reproduce (*)

Insert via database this code below in the **cms_page** table in the **custom_layout_update_xml** column.

```
    <reference name="content"></reference>
```

### Expected result (*)

It should be rendered in the CMS Page via admin panel to be removed or edited following the new syntax.

### Actual result (*)

Today, it's not rendered but when I try to save the page shows the syntax error message below.

![Screen Shot 2019-09-25 at 6 15 05 PM](https://user-images.githubusercontent.com/610598/65641689-d4019100-dfc3-11e9-8853-8515133c9df4.png)

![admin-cms-page-error-message](https://user-images.githubusercontent.com/610598/65641675-ce0bb000-dfc3-11e9-9144-758c3907b472.jpg)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-07 07:22 UTC, ihor-sviziev commented
@magento give me 2.4-develop instance

2020-02-07 07:22 UTC, magento-engcom-team commented
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

2020-02-07 07:22 UTC, magento-engcom-team commented
Hi @ihor-sviziev, here is your [Magento instance](https://i-24996-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24996-2-4-develop.instances.magento-community.engineering/admin_3897](https://i-24996-2-4-develop.instances.magento-community.engineering/admin_3897)
Login: `4087434d` Password: `6f04f90050a8`
Instance will be terminated in up to 3 hours.

2020-02-07 07:40 UTC, ihor-sviziev requested changes
Looks like issue is not valid anymore
https://github.com/magento/magento2/issues/24731#issuecomment-583268542
Could you confirm that?

2020-02-08 17:05 UTC, shikhamis11 commented
Hi @ihor-sviziev
thanks for update .. yes based on recent changes of magento 2.3.4 it seems this is no longer an issue .

2020-02-08 17:05 UTC, closed without merging