Fixing #24807 - Changed accordion transition method when closing
magento/magento2 pull request #24994
Opened 2019-10-11 15:44 UTC by gabrieldagama

### Description
When using the code sample from https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_accordion.html for an accordion widget - but setting the animate property to a numeric value - the transition works correctly for individual collapse elements, but when clicking to open a closed element the currently open element closes instantaneously without a transition. 

The reason for it is that the tabs widget has a forceDeactivate call to close the other tabs, the accordion element is based on the tabs and inherited the same behavior. To fix the issue I basically used the function that was already overridden and called the method deactivate instead.

### Fixed Issues
1. magento/magento2#24807: Accordion widget buggy transition

### Manual testing scenarios
1. Add an accordion widget to any page using the code sample from https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_accordion.html
2. Assign a numeric value to the 'animate' option e.g. "animate": {"duration": 600}
3. Open a closed element and observe the transition of both, the accordion that was opened has a force deactivation, so it closes instantly, the one that has been selected opens with the animation.

2019-11-01 12:20 UTC, sivaschenko approved these changes

2019-11-01 12:21 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-6224](https://jira.corp.magento.com/browse/ENGCOM-6224) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-11-01 12:27 UTC, sivaschenko requested changes
Hi @gabrieldagama thanks for the pull request! The author of commits in this pull request is not linked to the github account. Can you please configure your git with the email that matches to your github account email and redo the commits (force push to the same branch to rewrite commits with incrrect authorship)

2019-11-01 13:07 UTC, sivaschenko approved these changes

2019-11-01 13:08 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-6224](https://jira.corp.magento.com/browse/ENGCOM-6224) has been created to process this Pull Request

2019-11-04 10:16 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-11-07 02:02 UTC, merged