Issue 24788
magento/magento2 pull request #25012
Opened 2019-10-12 12:37 UTC by webkul-ratnesh

### Description (*)

With this PR now you can save "Maximum Qty Allowed in Shopping Cart" & "Minimum Qty Allowed in Shopping Cart"  store wise.
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-13 13:55 UTC, dmytro-ch requested changes
As for me, It's a quite disputable case when you need to set the Sale Quantity restrictions on Store View level. Nonetheless, according to the implementation of `\Magento\CatalogInventory\Model\Configuration`, it can be possible.
The only thing I would improve is to allow setting these values on the website level as well.

2019-10-13 13:55 UTC, dmytro-ch commented on app/code/Magento/CatalogInventory/etc/adminhtml/system.xml
> +                <field id="max_sale_qty" translate="label" type="text" sortOrder="4" showInDefault="1" showInWebsite="0" showInStore="1" canRestore="1">
```suggestion
                <field id="max_sale_qty" translate="label" type="text" sortOrder="4" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="1">
```

2019-10-13 13:55 UTC, dmytro-ch commented on app/code/Magento/CatalogInventory/etc/adminhtml/system.xml
> +                <field id="min_sale_qty" translate="label" sortOrder="6" showInDefault="1" showInWebsite="0" showInStore="1" canRestore="1">
```suggestion
                <field id="min_sale_qty" translate="label" sortOrder="6" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="1">
```

2019-10-19 16:58 UTC, dmytro-ch approved these changes

2019-10-19 16:59 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6130](https://jira.corp.magento.com/browse/ENGCOM-6130) has been created to process this Pull Request

2019-10-23 18:10 UTC, sdzhepa commented
Hello @webkul-ratnesh 

Thank you for contribution and collaboration!

Related issue https://github.com/magento/magento2/issues/24788 has been closed. 
Please see more details in the initial issue https://github.com/magento/magento2/issues/24788#issuecomment-545567456

At this moment work on this global solution is in progress in the scope of this task https://github.com/magento/inventory/pull/2297 . All planned work and design is described in this document [Stock and Source Configuration design](https://github.com/magento/inventory/wiki/Stock-and-Source-Configuration-design)

2019-10-23 18:10 UTC, closed without merging

2023-03-07 22:54 UTC, alevashov commented
As I see in Magento ver. 2.4.5-p1 this solution is still not being implemented, which is a shame, because it is needed for the cases of running B2C and B2B stores from the same Magento instance