Fixed: Undefined index store_view_code.
magento/magento2 pull request #25080
Opened 2019-10-16 07:22 UTC by maheshWebkul721

Fixed issue #25069 in this PR

### Description (*)

Import product with custom option without `store_view_code` was giving undefined index. fixed in this PR
### Fixed Issues (if relevant)

1. #25069

### Manual testing scenarios (*)

1. Create product with custom options in file without 'store_view_code' field
2. Start import product.
3. Assigning default store id.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-16 08:58 UTC, pusachev requested changes

2019-10-16 08:58 UTC, pusachev commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +                $options[$name][$k][self::COLUMN_STORE] = '';
Why we need this code? We have this part of code that checks this column  https://github.com/magento/magento2/blob/d15db0ac45cdae53fb43802e358052c0b23b34f4/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1157

2019-10-18 06:25 UTC, maheshWebkul721 commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +                $options[$name][$k][self::COLUMN_STORE] = '';
@pusachev `if (isset($rowData[Product::COL_STORE_VIEW_CODE])) {` this code is to confirm
if `store_view_code` index exists while other that you mention is to check if option store is assigned or not.

2019-10-21 15:19 UTC, pusachev commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +                $options[$name][$k][self::COLUMN_STORE] = '';
@maheshWebkul721 Yes, This part of code correct. But why you set default empty string 
$options[$name][$k][self::COLUMN_STORE] = ''; ? Magento has code that checked column index in this line https://github.com/magento/magento2/blob/d15db0ac45cdae53fb43802e358052c0b23b34f4/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1157

2019-10-21 17:17 UTC, maheshWebkul721 commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +                $options[$name][$k][self::COLUMN_STORE] = '';
@pusachev i already updated that condition in this commit [6ea86bbf765429d233bc9ab8515a9e3eae856af4](https://github.com/magento/magento2/pull/25080/commits/6ea86bbf765429d233bc9ab8515a9e3eae856af4)

2019-10-24 13:29 UTC, pusachev approved these changes

2019-10-24 13:30 UTC, pusachev commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php
> +                $options[$name][$k][self::COLUMN_STORE] = '';
@maheshWebkul721 thanks. All good.

2019-10-30 21:41 UTC, VladimirZaets approved these changes

2019-10-30 21:42 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6213](https://jira.corp.magento.com/browse/ENGCOM-6213) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-31 14:39 UTC, engcom-Alfa commented
Hi @maheshWebkul721. 
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.
Thanks!

2019-11-14 05:26 UTC, maheshWebkul721 commented
@engcom-Alfa please review it, covered changes with unit test.

2019-11-14 10:37 UTC, engcom-Alfa commented
Hi, @VladimirZaets @pusachev. Could you review the latest commits?

2019-11-14 15:53 UTC, VladimirZaets approved these changes

2019-11-14 15:54 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6213](https://jira.corp.magento.com/browse/ENGCOM-6213) has been created to process this Pull Request

2019-11-15 11:02 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed 

**Before:**
![before](https://user-images.githubusercontent.com/51679138/68938971-23846200-07a8-11ea-9674-2bef5e2b7245.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/68938975-297a4300-07a8-11ea-82c2-44a5c10ebe8a.png)

2019-11-19 04:12 UTC, merged