[ProductVideo] Validating the Product Video Url
magento/magento2 pull request #25090
Opened 2019-10-16 11:00 UTC by eduard13

### Description (*)
This PR adds validation for getting the video information, after clicking on `Get Video Information` button.

### Fixed Issues (if relevant)

1. magento/magento2#25088: Get Video Information button doesn't do anything on clicked

### Manual testing scenarios (*)

1. Navigate to new product page
2. Scroll to Images And Videos
3. Click on Add Video
4. Click on Get Video Information

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-16 14:05 UTC, rogyar requested changes

2019-10-16 14:05 UTC, rogyar commented on app/code/Magento/ProductVideo/Test/Mftf/ActionGroup/AdminAssertVideoValidationErrorActionGroup.xml
> +    <actionGroup name="AdminAssertVideoValidationErrorActionGroup">
Please use Assert[Area]Desctiption naming format for action groups (https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html 11.3.5)

2019-10-16 14:05 UTC, rogyar commented on app/code/Magento/ProductVideo/Test/Mftf/Test/AdminValidateUrlOnGetVideoInformationTest.xml
> +        <fillField selector="{{AdminProductNewVideoSection.videoUrlTextField}}"
Please, create a separate action group (like AdminFillProductVideoUrlActionGroup) for filling this field and pass the value as argument.

2019-10-16 14:45 UTC, eduard13 commented
Hi @rogyar, thank you for reviewing it, the requested changes were adjusted.

2019-10-20 12:22 UTC, rogyar approved these changes

2019-10-20 12:23 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-6134](https://jira.corp.magento.com/browse/ENGCOM-6134) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-21 07:58 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-10-23 13:19 UTC, merged