Issueno 25121
magento/magento2 pull request #25123
Opened 2019-10-17 15:14 UTC by webkul-ratnesh

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#25121: While editing options of item in cart, Options not selected at configuration page

### Manual testing scenarios (*)

1. Add configurable product to cart
2. Edit that product from cart to make change sin option.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-17 18:37 UTC, VladimirZaets requested changes
Hi @webkul-ratnesh. Please look at my comments. 
Also, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

2019-10-17 18:37 UTC, VladimirZaets commented on app/code/Magento/Msrp/view/base/web/js/msrp.js
> +        onUpdateMsrpPrice: function onUpdateMsrpPrice(event, priceIndex, prices) {
Please remove double function name declaration

2019-10-17 18:37 UTC, VladimirZaets commented on app/code/Magento/Msrp/view/base/web/js/msrp.js
> +            if (typeof prices[priceIndex] !== 'undefined') {
Please use underscore method _.isUndefined

2019-10-17 18:37 UTC, VladimirZaets commented on app/code/Magento/Msrp/view/base/web/js/msrp.js
> +            if (typeof prices[priceIndex] !== 'undefined') {
Please refactor this construction. 
Nested "if else" blocks are not readable

2019-10-17 18:37 UTC, VladimirZaets commented on app/code/Magento/Msrp/view/base/web/js/msrp.js
> +            if (useDefaultPrice || !this.wasOpened) {
Why do you need to know it was opened or not? Also, you can take this information in real-time instead of having additional state

2019-10-17 18:37 UTC, VladimirZaets commented on app/code/Magento/Msrp/view/base/web/js/msrp.js
> +                this.$popup.find(this.options.msrpPriceElement).html(msrpPrice);
Can we use "text()" instead of "html" in this case?

2019-10-18 05:38 UTC, webkul-ratnesh commented
hello @VladimirZaets 
I will update the suggested code soon.

2019-10-18 07:09 UTC, webkul-ratnesh commented
not proper PR

2019-10-18 07:09 UTC, closed without merging