Fix the problem 'Attribute with the same code already exists'
magento/magento2 pull request #25134
Opened 2019-10-18 04:05 UTC by TomashKhamlai

### Description (*)

Fix the problem 'Attribute with the same code already exists'
in attribute_user_defined_address_custom_attribute_rollback.php
Add signatures and unify style in the naming of variables

### Fixed Issues (if relevant)

1. No

### Manual testing scenarios (*)

1. Try something like this:
```php
    /**
     * Dummy test
     *
     * @magentoApiDataFixture Magento/Customer/_files/customer.php
     * @magentoApiDataFixture Magento/Customer/_files/customer_address.php
     * @magentoApiDataFixture Magento/Customer/_files/attribute_user_defined_address_custom_attribute.php
     */
    public function testCustomAttributeOrWhatever()
    {
        /** @var AddressRepositoryInterface $addressRepositoryInterface */
        $addressRepositoryInterface = Bootstrap::getObjectManager()->get(AddressRepositoryInterface::class);

        $address = $addressRepositoryInterface->getById(1);
        $address
            ->setCustomAttribute('custom_attribute1', 'address1')
            ->setCustomAttribute('custom_attribute2', 'address2'');
        $addressRepositoryInterface->save($address);
        self::assertTrue(true);
    }
```
2. Run it.
3. Run again

#### Expected result:
Any test which uses this fixture works the second time too.

#### Actual result:
The second time you start the test you will have this error:
```
PHP Fatal error:  Uncaught Exception: Exception occurred when running the "\/var\/www\/html\/magento2\/dev\/tests\/integration\/testsuite\/Magento\/Customer\/_files\/attribute_user_defined_address_custom_attribute.php" fixture: 
Attribute with the same code already exists. in /var/www/html/magento2/dev/tests/api-functional/framework/Magento/TestFramework/Annotation/ApiDataFixture.php:114

...

=== Memory Usage System Stats ===
Memory usage (OS):	71.11M (169.31% of 42.00M reported by PHP)
Estimated memory leak:	29.11M (40.94% of used memory)

Process finished with exit code 255
```

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-18 06:36 UTC, swnsma requested changes
Hi @TomashKhamlai,
Thank you for your contribution!
Could you check failed static tests?

2019-10-19 07:28 UTC, swnsma approved these changes

2019-10-19 07:29 UTC, magento-engcom-team commented
Hi @swnsma, thank you for the review.
[ENGCOM-6128](https://jira.corp.magento.com/browse/ENGCOM-6128) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-21 11:08 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-10-23 13:19 UTC, merged