Fixed credit card type number validation error
magento/magento2 pull request #25156
Opened 2019-10-18 21:46 UTC by emirajbbd

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-19 11:29 UTC, dmytro-ch commented
Hi @emirajbbd,
could you please provide information about the issue and steps to reproduce?
Also, some descriptions for the reason of issue and applied solution are welcomed.
Thank you!

2019-10-21 22:28 UTC, emirajbbd commented
**Description:**
When we have PayPal Payments Pro/PayPal Payflow Pro enabled to process Debit or Credit Card and user tries to place an order using his credit card info, it always sends validation error "Please enter a valid credit card type number" though the card was valid.

**Steps to reproduce:**
1. Enable PayPal Payments Pro/PayPal Payflow Pro on the backend
2. Go to checkout payment step
3. Add correct Credit/Debit card info
4. Error message display "Please enter a valid credit card type number"

2019-11-14 18:58 UTC, dmytro-ch requested changes
Hi @emirajbbd , could you please check and fix the static test failures?
Once the changes are applied, please squash all commits into a single one in order to cleanup history.
Thank you!

2019-11-14 18:58 UTC, dmytro-ch commented on app/code/Magento/Payment/view/base/web/js/model/credit-card-validation/validator.js
> +                     if( !!type && type.constructor === Array && type.includes(cardInfo.title)){ // Check if an arry
```suggestion
                    if (!!type && type.constructor === Array && type.includes(cardInfo.title)) { // Check if an array
```

2019-11-30 11:18 UTC, dmytro-ch commented
Hi, @emirajbbd, I'm Closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

2019-11-30 11:18 UTC, closed without merging