Subscribed to Newsletter Label and respective checkbox not aligned pr…
magento/magento2 pull request #25208
Opened 2019-10-22 08:43 UTC by cedarvinda

Subscribed to Newsletter Label and respective checkbox not aligned proper #25207 issue fixed

### Manual testing scenarios (*)

1. Login to admin panel
2. Redirect Customers > All customers and view any customer details
3. Now click in newsletter tab appear in left side
4. And refer screenshot in sctual result

2019-10-22 10:34 UTC, dmytro-ch commented on app/design/adminhtml/Magento/backend/web/css/styles-old.less
> +        .field{
```suggestion

        .field {
```

2019-10-22 10:35 UTC, dmytro-ch commented on app/design/adminhtml/Magento/backend/web/css/styles-old.less
> +               .admin__field-control {
```suggestion

               .admin__field-control {
```

2019-10-22 10:41 UTC, dmytro-ch requested changes

2019-10-22 10:41 UTC, dmytro-ch commented on app/design/adminhtml/Magento/backend/web/css/styles-old.less
> +               .admin__field-label{
```suggestion
               .admin__field-label {
```

2019-10-22 11:58 UTC, dmytro-ch approved these changes

2019-10-22 11:59 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6148](https://jira.corp.magento.com/browse/ENGCOM-6148) has been created to process this Pull Request

2019-10-23 06:46 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-10-26 22:53 UTC, merged