Braintree - Skip generation Client Token if payment method is not active
magento/magento2 pull request #25223
Opened 2019-10-22 16:28 UTC by andrey-legayev

### Description (*)
If Braintree module is enabled 
then requests ClientToken via curl request on every shopping cart and checkout page load
**regardless active/non-active configuration** of payment method.
Curl request takes 0.3-0.5 sec to respond for servers in N.Virginia which is making Shopping Cart and Checkout pages much slower.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Test purchases with Braintree payment method.

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-22 17:52 UTC, dmytro-ch requested changes
Hello @andrey-legayev,
thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
Thank you!

2019-10-22 18:10 UTC, andrey-legayev commented
Sorry, I have no time for it now.

2019-10-23 05:46 UTC, dmytro-ch approved these changes

2019-10-25 10:36 UTC, engcom-Bravo commented
Hello @andrey-legayev. Please cover Your PR with appropriate Auto-Tests. Thank You.

2019-10-25 14:04 UTC, ihor-sviziev commented
Hi @engcom-Bravo,
Could you cover these changes by internal team?

These changes really improves performance of shopping cart/checkout pages. I think that's much better to accept this PR even without covering with any tests rather than wait till author will have a time for covering it with tests.

2019-10-25 15:56 UTC, engcom-Bravo commented
Hi @ihor-sviziev. Ok, I'll find out about it.

2019-10-26 16:17 UTC, andrey-legayev commented
Some details about performance impact:
We added debug logging to our production Magento2 to track how much time is spent on Braintree's getClientToken()
The result is: **0.231 sec on average** for 24 hours of logging.

Token is not used in two cases:
1. if payment method is not active - that's obvious, this is why I submitted this pull request
2. on shopping cart - it's triggered via long chain of calls, but all starts from Estimate Shipping Cost block (which doesn't use Braintree's token)

Would be great to avoid token generation on shopping cart as well.
For now I see it doable only via ajax request.

2019-10-28 07:14 UTC, ihor-sviziev commented
Hi @andrey-legayev,

I just looked on "clientToken" and found that in Admin client token already taken via AJAX.

https://github.com/magento/magento2/blob/890bf891f86d876c1e2651978ba287958467dd9f/app/code/Magento/Braintree/view/adminhtml/web/js/braintree.js#L136-L144

It runs following controller code:
https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/app/code/Magento/Braintree/Controller/Adminhtml/Payment/GetClientToken.php#L59-L75

I think it's good idea to adjust also frontend JS to get it via AJAX, so it will not slow down the page when it's not needed.

2019-10-29 07:22 UTC, engcom-Golf commented
Hi @andrey-legayev thank you for Pull Request i will take care about test coverage.

2019-10-29 09:58 UTC, engcom-Golf commented
:heavy_check_mark: QA Passed

2019-10-29 10:45 UTC, ihor-sviziev commented
Hi @andrey-legayev,
Based on our discussion I reported an issue https://github.com/magento/magento2/issues/25343

2019-10-30 13:23 UTC, merged