Fixed Typo: Changed Function name checkRequredFields to checkRequiredFields
magento/magento2 pull request #25273
Opened 2019-10-24 14:32 UTC by maheshWebkul721

Typo bug fixed in this PR.

### Description (*)

Changed Function name checkRequredFields to checkRequiredFields to fix Typo issue.
### Fixed Issues (if relevant)

1. No Issue Raised.

### Manual testing scenarios (*)

1. Working as expected.
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-25 13:39 UTC, ihor-sviziev requested changes

2019-10-25 13:39 UTC, ihor-sviziev commented on app/code/Magento/Customer/Model/Address/Validator/General.php
>      private function checkRequredFields(AbstractAddress $address)
Hi,

We don't need to introduce new code there.

This is private method, please just rename it, no need to add "deprecated" because no one will use it and there is no ability to execute it outside of this class.

2019-10-28 15:23 UTC, ihor-sviziev approved these changes

2019-10-28 15:24 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6193](https://jira.corp.magento.com/browse/ENGCOM-6193) has been created to process this Pull Request

2019-10-30 00:44 UTC, merged