Adds color conversion to SRGB for images with CMYK palette
magento/magento2 pull request #25277
Opened 2019-10-24 19:44 UTC by krisdante

### Description (*)

Adds color conversion to SRGB for images with CMYK and Unrecognizable color palette

For ImageMagic, when the original image was in CMYK palette, the final image after
resize was kind of "in negative". I decided to force conversion to RGB, but when
converting to RGB from CMYK with IMagixk - colors were not natural.
So I picked SRGB (I found this hint in StackOverflow)

### Fixed Issues (if relevant)

1. magento/magento2#22375  : CMYK images are rendered with inverted colors

### Manual testing scenarios (*)

See the issue for a detailed path to reproduce / test

### Questions or comments

It might be that "normal" RGB images will get converted to SRGB in some cases. I tested a few RGB images and I do not see the quality problem.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-25 08:25 UTC, krisdante commented
Those Exceptions (Code style failing) were there before. I think migrating that is a separate topic and I will do that with another pull request.

2020-03-03 09:38 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

2020-03-03 09:40 UTC, ihor-sviziev requested changes
Hi @krisdante,
Your change looks good to me. Could you cover your changes with unit test?

2020-03-03 09:40 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Image/Adapter/ImageMagick.php
> +    protected function ensureColorspace()
```suggestion
    private function ensureColorspace()
```

2020-03-19 08:59 UTC, ihor-sviziev commented
Hi @krisdante,
Will you be able to update your PR?

2020-03-19 09:25 UTC, krisdante commented
I need to think about it. The tricky part with unit testing that is that you cannot check colours programatically. They will be fine. They are just displayed brokenly to a human eye when wrong colour space conversion will happen. 
The test here was to upload the image attached to this bug, and check if it is looking good in Magento. 
It is really hard to program this as integration test.

2020-03-19 09:26 UTC, krisdante commented
Also merging this before https://github.com/magento/magento2/pull/26036 would be nice.

2020-03-27 06:58 UTC, ihor-sviziev requested changes
> I need to think about it. The tricky part with unit testing that is that you cannot check colours programatically. They will be fine. They are just displayed brokenly to a human eye when wrong colour space conversion will happen.
The test here was to upload the image attached to this bug, and check if it is looking good in Magento.
It is really hard to program this as integration test.


@krisdante yeah, that's good point for sure, but I didn't see any integration tests for image magic, but this would be really good thing if you could write it!
By unit test we could just check that your code was executed and in case if you'll write integration - it will be enough. If you'll have any issues with integration tests - unit test we still could write without any issues.

Also I wrote few comments to existing functionality, please check them

Could you update your PR accordingly?

2020-03-27 06:58 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Image/Adapter/ImageMagick.php
> +
```suggestion
                break;
```

2020-03-27 06:58 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Image/Adapter/ImageMagick.php
> +                return;
I think we could just remove this case.

2020-04-10 12:07 UTC, ihor-sviziev commented
Hi @krisdante,
Will you be able to update your PR?

2020-04-16 12:36 UTC, ihor-sviziev commented
@krisdante  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-04-16 12:36 UTC, closed without merging