Extend password reset token validity on password change page load
magento/magento2 pull request #25279
Opened 2019-10-24 21:59 UTC by fredden

### Description (*)

This avoids a race condition where the password reset token is valid at page load time, but no longer valid at page submission time.

In a scenario where a user begins the password reset flow but is unable to immediately complete the same, clicking the link close to expiry time provides an opportunity for an error message after entering a new password due to the token expiring between page load & form submission.

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

1. Generate password reset email (admin & frontend)
1. Follow link back to Magento
1. Observe password validity in database has been extended/reset

### Questions or comments

I am unsure if this change requires a unit test.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-18 16:49 UTC, sidolov commented
@magento create issue

2020-09-28 10:57 UTC, ihor-sviziev commented
Hi @fredden,
I'm really sorry for long delay with processing your PR. I'll take it and will try to push it forward.

2020-09-28 10:57 UTC, ihor-sviziev commented
@magento run all tests

2020-09-28 13:00 UTC, ihor-sviziev requested changes

2020-09-28 13:00 UTC, ihor-sviziev commented on app/code/Magento/Customer/Controller/Account/CreatePassword.php
> +                // Intentionally ignoring failures here
1. Catching all types exceptions isn't really good thing. I believe we shouldn't catch PDOException here, for instance? Can we catch there only exceptions that we really expect?

2. Empty catch block also not a good thing, usually it just masks the problems. Which failures we expect here? Why should we ignore them? Should we add some message or maybe log them in some case?

2020-09-28 13:00 UTC, ihor-sviziev commented on app/code/Magento/User/Controller/Adminhtml/Auth/ResetPassword.php
> +                // Intentionally ignoring failures here
Basically the same here as for prev. catch block.

2020-09-28 13:00 UTC, ihor-sviziev commented on app/code/Magento/Customer/Controller/Account/CreatePassword.php
> +     * @var \Magento\Customer\Model\ForgotPasswordToken\GetCustomerByToken
Looks like this class already imported, so we can change it to something like this
```suggestion
     * @var GetCustomerByToken
```

2020-09-28 13:00 UTC, ihor-sviziev commented on app/code/Magento/Customer/Controller/Account/CreatePassword.php
> +     * @param \Magento\Customer\Model\ForgotPasswordToken\GetCustomerByToken $getByToken
Seems like all listed arguments are already imported, and some of them are not always an object, so we can update it to this
```suggestion
     * @param Context $context
     * @param Session $customerSession
     * @param PageFactory $resultPageFactory
     * @param AccountManagementInterface $accountManagement
     * @param ConfirmCustomerByToken|null $confirmByToken
     * @param GetCustomerByToken|null $getByToken
```

2020-10-09 09:19 UTC, engcom-Charlie commented
@fredden can you please look at the requested changes and cover your changes by some kind of autotests? Otherwise, we can't proceed with your PR.
Thank you.

2020-10-12 21:27 UTC, sidolov commented
@fredden  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-10-27 21:28 UTC, fredden commented
Please may I have some guidance on how to write good tests to cover this change?

2020-10-27 21:30 UTC, fredden commented
@sidolov I don't have a 'reopen' button; please can you re-open this.

2020-10-28 04:23 UTC, ihor-sviziev commented
@fredden I just reopened this PR by your request. Please update PR by the requested earlier changes.
From the tests perspective - I think the most useful will be here integration tests

2020-10-29 15:47 UTC, ihor-sviziev commented
@sidolov could you explain why this PR was assigend to GraphQL board?

2020-10-29 16:09 UTC, sidolov commented
@ihor-sviziev it's caused by the issue in the app, it's successfully resolved and PRs will be assigned to the correct board

2020-10-30 08:47 UTC, engcom-Charlie commented
@fredden please update PR accordingly to the requested earlier changes and cover your changes by integration test.
Thank you.

2020-11-02 08:53 UTC, engcom-Charlie commented
@fredden could you please cover your changes by integration test?
Thank you.

2020-11-05 08:09 UTC, ihor-sviziev commented
@magento run all tests

2020-11-06 23:35 UTC, fredden commented
@magento run WebAPI Tests

2020-11-07 17:23 UTC, fredden commented
@magento run all tests

2020-11-07 19:42 UTC, fredden commented
@magento run all tests

2020-11-09 04:44 UTC, ihor-sviziev commented
Hi @fredden,
Thank you for covering your changes with integration tests! Could you fix the failing static test (just ignore the coupling between objects in auth test file) and I’ll approve your PR?

2020-11-09 08:07 UTC, fredden commented
@ihor-sviziev the only complaint from the automated testing system is the one you're suggesting I ignore.

> PHP Code Mess has found error(s):
/var/www/html/dev/tests/integration/testsuite/Magento/User/Controller/Adminhtml/AuthTest.php:18	The class AuthTest has a coupling between objects value of 15. Consider to reduce the number of dependencies under 13.

How do you suggest we proceed?

2020-11-09 08:22 UTC, ihor-sviziev commented
@fredden please add such line `@SuppressWarnings(PHPMD.CouplingBetweenObjects)` to the phpdoc block for the classs, example:
https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/dev/tests/integration/framework/Magento/TestFramework/Catalog/Model/Indexer/Category/Product/Action/Full.php#L13-L19

2020-11-10 14:10 UTC, fredden commented
@magento run all tests

2020-11-10 16:21 UTC, ihor-sviziev commented
@magento run Functional Tests EE, WebAPI Tests

2020-11-12 16:52 UTC, fredden commented
@magento run all tests

2020-11-13 07:33 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE

2020-11-13 14:41 UTC, ihor-sviziev approved these changes

2020-11-13 14:42 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8461](https://jira.corp.magento.com/browse/ENGCOM-8461) has been created to process this Pull Request

2020-11-26 12:37 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
**Before:**
:x: Value in `rp_token_created_at` column is not changed after customer open a `Set a New Password` link from reset password email

**After:**
:heavy_check_mark: Value in `rp_token_created_at` column is updated and is equal to the time when customer open a `Set a New Password` link from reset password email
![Peek 2020-11-26 14-36](https://user-images.githubusercontent.com/51681379/100351885-d65ee100-2ff4-11eb-8ac3-bbfcc3a26ee2.gif)

2020-11-27 16:06 UTC, engcom-Delta commented
**Note:** Automation tests are passed

2021-07-16 10:11 UTC, korostii commented
@magento-engcom-team Any progress update here please?

2021-08-20 15:27 UTC, merged