Add lib wrapper for UUID validation.
magento/magento2 pull request #25285
Opened 2019-10-25 05:58 UTC by nikolaevas

### Description (*)
Fix for the async-import project. Move third-party library dependency to core repository.

### Fixed Issues (if relevant)
1. https://github.com/magento/async-import/issues/148 Add lib wrapper for UUID generation/validation #148

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-25 13:36 UTC, ihor-sviziev requested changes

2019-10-25 13:36 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/DataObject/IdentityValidator.php
> +namespace Magento\Framework\DataObject;
1. Please add strict types for this file

2019-10-25 13:36 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/DataObject/IdentityValidatorInterface.php
> +    public function isValid($value);
Please add argument and return types there and in implementation

2019-10-27 14:29 UTC, ihor-sviziev commented
Hi @nikolaevas,
Your changes looks good.
Would be great to cover your changes with some tests. Will you be able to do that?

2019-10-27 17:17 UTC, ihor-sviziev approved these changes

2019-10-27 17:18 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6184](https://jira.corp.magento.com/browse/ENGCOM-6184) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-12-06 20:52 UTC, slavvka commented
The PR is currently under architecture review

2019-12-10 23:35 UTC, slavvka commented
Hey @nikolaevas There is no dependency on Ramsey component in the framework's composer.json. Please add it.

2020-01-08 16:26 UTC, nuzil commented
@slavvka done

2020-01-09 16:40 UTC, slavvka commented
Hey @nuzil could you please fix the static tests?

2020-01-14 09:27 UTC, ihor-sviziev approved these changes

2020-01-14 09:28 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6184](https://jira.corp.magento.com/browse/ENGCOM-6184) has been created to process this Pull Request

2020-01-15 13:05 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-01-16 16:09 UTC, slavvka commented
BIC was approved https://jira.corp.magento.com/browse/MC-23065

2020-02-09 12:05 UTC, merged