Add support to assign attribute_set when creating product attributes …
magento/magento2 pull request #25308
Opened 2019-10-27 11:44 UTC by mgarciaavz

…programatically

### Description (*)
As documented here: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html#add-product-eav-attribute-options-reference, there is no way to target a particular attribute set, so all new attributes are blindly assigned to all the existing attribute sets.

Using this approach, it's possible to add the position `attribute_set` to the attributes array passed to the `addAttribute` method. This new position expects the attribute set name where the new attribute will be added to. 

### Fixed Issues (if relevant)
1. magento/magento2#14793: createAttribute not behaving as expected

### Manual testing scenarios (*)
1. Create a new attribute set (no matter its name). Let's say "**Glassware**"
2. Create a new attribute programatically using the following attributes:
````
$eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'sample_attribute_1',
            [
                'type' => 'text',
                'backend' => '',
                'frontend' => '',
                'label' => 'Sample Attribute 1',
                'input' => 'text',
                'class' => '',
                'source' => '',
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_WEBSITE,
                'visible' => true,
                'required' => true,
                'user_defined' => false,
                'default' => '',
                'searchable' => false,
                'filterable' => false,
                'comparable' => false,
                'visible_on_front' => false,
                'used_in_product_listing' => true,
                'unique' => false,
                'attribute_set' => 'Glassware',
                'group' => 'Content',
            ]
        );
````

### Questions or comments
There are no unit test created for the `addAttribute`, so I'm keeping it as it.

Not sure what to do when the attribute name provided doesn't exist. At this moment, the new attribute won't be added to any attribute set. So, maybe a slightly different approach in order to define a default behaviour for these cases would make sense.

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-27 12:59 UTC, okorshenko commented
Hi @mgarciaavz there is an integration test in place: ```\Magento\Eav\Setup\EavSetupTest``` located in 
```dev/tests/integration/testsuite/Magento/Eav/Setup/EavSetupTest.php```
We can extend this test to cover new behavior

2019-10-27 13:00 UTC, okorshenko commented
@magento give me test instance

2019-10-27 13:00 UTC, magento-engcom-team commented
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

2019-10-27 13:00 UTC, magento-engcom-team commented
Hi @okorshenko, here is your [new Magento instance](https://pr-25308.instances.magento-community.engineering).
Admin access: [https://pr-25308.instances.magento-community.engineering/admin](https://pr-25308.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-10-27 13:47 UTC, okorshenko requested changes

2019-10-27 13:47 UTC, okorshenko commented on app/code/Magento/Eav/Setup/EavSetup.php
> +            $select_args = ['entity_type_id' => $entityTypeId];
```suggestion
            $selectArgs = ['entity_type_id' => $entityTypeId];
```

2019-10-27 13:47 UTC, okorshenko commented on app/code/Magento/Eav/Setup/EavSetup.php
> +
```suggestion
```

2019-10-27 13:47 UTC, okorshenko commented on app/code/Magento/Eav/Setup/EavSetup.php
> +                $select_args['attribute_set_name'] = $attr['attribute_set'];
```suggestion
                $selectArgs['attribute_set_name'] = $attr['attribute_set'];
```

2019-10-27 13:47 UTC, okorshenko commented on app/code/Magento/Eav/Setup/EavSetup.php
> +            $sets = $this->setup->getConnection()->fetchAll($select, $select_args);
```suggestion
            $sets = $this->setup->getConnection()->fetchAll($select, $selectArgs);
```

2019-10-27 13:49 UTC, okorshenko commented
In terms of default behavior, we should throw a ```LocalizedException``` if  ```attribute_set``` name is not valid.

2019-10-30 15:06 UTC, mgarciaavz commented
Hi @okorshenko @slavvka not sure what's the next step, just wanted to mention that the PR is marked as "Needs update", but all changes has already been done, is anything else missing?

Thank you!

2019-10-30 20:33 UTC, slavvka commented
Hey @mgarciaavz. Oleksii also mentioned that we need to have the new behavior covered with ato test https://github.com/magento/magento2/pull/25308#issuecomment-546692353

2019-10-31 09:25 UTC, mgarciaavz commented
Thanks @slavvka, I'll check it out.

2019-11-07 03:56 UTC, mshbb00 reviewed
mgarciaavz:feature/createattribute-attribute-set

2019-11-08 13:33 UTC, mgarciaavz commented
@magento give me test instance

2019-11-08 13:33 UTC, magento-engcom-team commented
Hi @mgarciaavz. Thank you for your request. I'm working on Magento instance for you

2019-11-08 13:34 UTC, magento-engcom-team commented
Hi @mgarciaavz, here is your [new Magento instance](https://pr-25308.instances.magento-community.engineering).
Admin access: [https://pr-25308.instances.magento-community.engineering/admin](https://pr-25308.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2020-06-30 08:01 UTC, engcom-Charlie commented
Hi @mgarciaebo, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-06-30 08:01 UTC, closed without merging