Fix module name identification in AbstractBlock
magento/magento2 pull request #25318
Opened 2019-10-27 13:53 UTC by rodrigowebjump

### Description (*)
Fix automatic identification of module name in AbstractBlock when module namespace is not explicit in template file location

This issue affects all modules starting with word Block

Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'template.phtml' in module: 'Vendor' block's name: 'my-block'

### Manual testing scenarios (*)
1. Create a module starting with name Block ie Vendor/BlockExample
2. Create a custom block that extends \Magento\Framework\View\Element\Template and a template file
3. Create a layout file inserting this block and not explicit module name in template file
4. An exception will be throw due to incorrect module name detection 
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'template.phtml' in module: 'Vendor' block's name: 'my-block'

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-28 14:02 UTC, ihor-sviziev requested changes
Hi @rodrigowebjump,
Could you cover your changes with some test?

2019-10-28 17:34 UTC, rodrigowebjump commented
Hi @ihor-sviziev 

Done 👍

2019-10-29 05:56 UTC, ihor-sviziev approved these changes

2019-10-29 05:57 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6200](https://jira.corp.magento.com/browse/ENGCOM-6200) has been created to process this Pull Request

2019-10-29 16:46 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-11-04 19:58 UTC, merged