TASK || Left Side Back End Menu Design fix #18687
magento/magento2 pull request #25319
Opened 2019-10-27 13:57 UTC by angelgonzalezi4

URL: https://github.com/magento/magento2/issues/18687

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-28 01:46 UTC, kalpmehta approved these changes

2019-10-28 01:47 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-6187](https://jira.corp.magento.com/browse/ENGCOM-6187) has been created to process this Pull Request

2019-10-28 01:49 UTC, kalpmehta commented
Thanks @angelgonzalezi4 for your contribution. I have tested this on one of the website I manage which had this issue for long time, it works like a charm!

2019-10-31 11:20 UTC, dmytro-ch requested changes
Hello @angelgonzalezi4,
could you please also fix the code styling issues reported by Static Test?
Thank you!

2019-10-31 11:20 UTC, dmytro-ch commented on app/design/adminhtml/Magento/backend/Magento_Backend/web/css/source/module/_menu.less
> +                display: inline-flex;
I guess It's better to use the corresponding mixin:
```suggestion
                .lib-vendor-prefix-display(inline-flex);
```

2019-10-31 11:20 UTC, dmytro-ch commented on app/design/adminhtml/Magento/backend/Magento_Backend/web/css/source/module/_menu.less
> +                flex-wrap: wrap;
```suggestion
                .lib-vendor-prefix-flex-wrap(wrap);
```

2019-11-13 03:59 UTC, kalpmehta commented
Hi @angelgonzalezi4, can you please make the changes suggested by @dmytro-ch ? I would love to see this getting merged.

2019-11-13 08:14 UTC, angelgonzalezi4 commented
Until the weekend most probably i cant do It bit i Will try it :S

El mié., 13 nov. 2019 5:00, Kalpesh Mehta <notifications@github.com>
escribió:

> Hi @angelgonzalezi4 <https://github.com/angelgonzalezi4>, can you please
> make the changes suggested by @dmytro-ch <https://github.com/dmytro-ch> ?
> I would love to see this getting merged.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/25319?email_source=notifications&email_token=ANTK6AC43FU7KZEO5DHN6ALQTN3VTA5CNFSM4JFRZGP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED4ZPVY#issuecomment-553228247>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANTK6AENJCUB3URNHD33BPTQTN3VTANCNFSM4JFRZGPQ>
> .
>

2019-11-25 22:15 UTC, VladimirZaets commented
@angelgonzalezi4 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-11-25 22:15 UTC, closed without merging