Correct spelling
magento/magento2 pull request #25328
Opened 2019-10-28 03:56 UTC by ravi-chandra3197

### Description (*)

Correct spelling
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: N/A

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-31 21:01 UTC, rodrigowebjump requested changes

2019-10-31 21:01 UTC, rodrigowebjump commented on app/code/Magento/Sales/Model/ResourceModel/Status/Collection.php
> + * Order status grid collection
Please move this description just before the class name.
See \Magento\Sales\Model\ResourceModel\Order\Invoice.php

2019-11-25 22:13 UTC, VladimirZaets approved these changes

2019-11-25 22:16 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6333](https://jira.corp.magento.com/browse/ENGCOM-6333) has been created to process this Pull Request

2019-11-26 08:29 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-11-27 16:47 UTC, merged