Add Cache-Control header to knockout partials
magento/magento2 pull request #25325
Opened 2019-10-27 17:55 UTC by paveq

### Description (*)
This PR adds Cache-Control headers to knockout partials (.html static content files). Previous PR https://github.com/magento/magento2/pull/8000 did not add this, even though it was discussed.

### Fixed Issues (if relevant)
Without Cache-Control header in same cases when using caching proxies such as Cloudflare to serve files, end user browser does 304 check each time on every page. This highly depends on proxy configuration, but there should not be any reason not to set Cache-Control header.

In this PR we set Cache-Control to public, which is same value for all static content files. There is no need for browser to revalidate these requests, as invalidation is handled by static content versioning.

### Manual testing scenarios (*)
1. Open category page
2. Open browser inspector
3. Verify that returned response to .html static content file has Cache-Control header
4. Open another category page
5. Verify that the same .html file is retrieved from browser disk cache

### Questions or comments
<!---

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [not applicable] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-28 03:02 UTC, rodrigowebjump approved these changes
Hi @paveq Thanks for your contribution

2019-10-28 03:03 UTC, magento-engcom-team commented
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6189](https://jira.corp.magento.com/browse/ENGCOM-6189) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-28 06:43 UTC, ihor-sviziev requested changes
Hi @paveq,
Could you also add this change to nginx.conf.sample to make both installations consistent?

2019-11-01 08:59 UTC, paveq commented
> Hi @paveq,
> Could you also add this change to nginx.conf.sample to make both installations consistent?

This is now added.

2019-11-01 09:00 UTC, ihor-sviziev approved these changes

2019-11-01 09:01 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6189](https://jira.corp.magento.com/browse/ENGCOM-6189) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-11-04 15:05 UTC, engcom-Bravo commented
Hello @paveq. Thank You for Your contribution. Could You please help us a bit with Manual Testing and give us some more details on it so that we can be sure we do everything correctly. For example in "Verify that returned response to .html static content file has Cache-Control header" please specify some concrete .html file. Also "Open another category page" means another page of the same category or a page of some other category? Besides do we need to switch to Developer or to Production mode for executing all of that. There also may be some other details will help us to correctly reproduce the scenario. Thank You in advance.

2019-11-13 07:28 UTC, ihor-sviziev commented
@magento give me test instance

2019-11-13 07:28 UTC, magento-engcom-team commented
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento instance for you

2019-11-13 07:28 UTC, ihor-sviziev commented
@magento give me 2.3-develop instance

2019-11-13 07:28 UTC, magento-engcom-team commented
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

2019-11-13 07:29 UTC, magento-engcom-team commented
Hi @ihor-sviziev, here is your [new Magento instance](https://pr-25325.instances.magento-community.engineering).
Admin access: [https://pr-25325.instances.magento-community.engineering/admin](https://pr-25325.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-11-13 08:03 UTC, ihor-sviziev commented
@engcom-Delta,
**Steps to reproduce:**
1. Open Google Chrome developer tools
2. Navigate to homepage
3. In Google Chrome dev tools looks at any .js file (I checked on domReady.js file), look at "Response Headers" section

**On 2.3-develop:**
❌ Cache-Control header is missin
![image](https://user-images.githubusercontent.com/1873745/68744201-b7b1c600-05fc-11ea-95e0-f2ccfbc6f9e0.png)


**On this PR:**
✔ Cache-Control header is present
![image](https://user-images.githubusercontent.com/1873745/68744139-94871680-05fc-11ea-9d0f-ad40159ecc6a.png)

I just tried to test it and found another issue - https://github.com/magento/magento2/issues/25578.
But anyway you can apply steps to reproduce and apply them to "

2019-11-28 12:48 UTC, engcom-Bravo commented
Thank You, @ihor-sviziev. Before proceeding to full testing, can You tell me please if this fix is supposed to be detected on the local environment. Yes, I see it works on the instances You requested above. But I can't see it working on my local instance. In fact Cache-Control header is present only for the main requested recourse, i.e. for example for the testcategory.html if we talk about category page with testcategory url key. Besides it appears only in developer mode and looks differently meaning it contains more information than just "public".

2019-11-29 14:52 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-12-03 20:23 UTC, merged