Always load ALL child products for a configurable product
magento/magento2 pull request #25351
Opened 2019-10-29 13:35 UTC by princefishthrower

Always load ALL child products for a configurable product (set `skipStockFilter` to 'true')

### Description (*)
This small pull request only changes a passed parameter from false to true. I discovered that the LinkManagement class was returning only children of configurable products that were 'in stock' for a given configurable product. However, the behaviour described for the getChildren() method states that all children should be returned. 

I discovered that the `skipStockFilter` flag was falsely set to `false`, which causing this behavior.

### Fixed Issues
1. Fixes magento/magento2#25287 : LinkManagement::getChildren() returns only children products which are in stock

https://github.com/magento/magento2/issues/25287

### Manual testing scenarios (*)
1. Create a configurable product (for illustration purposes, lets say with SKU '1234') with multiple simple product children
2. Set any number (or even all!) children to 'out of stock'
3. Injecting LinkManagement in any custom code and calling `$this->linkManagement->getChildren('1234')` will now return ALL child products - and subsequent cached calls likewise.

Previous behavior: `$this->linkManagement->getChildren('1234')` returned only in stock children (and subsequent cached calls likewise).

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-29 20:03 UTC, VladimirZaets requested changes
Hi @princefishthrower , please, sign CLA, otherwise, we can't process your pull request.
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

2019-10-30 07:40 UTC, princefishthrower commented
@VladimirZaets - thanks, I've signed the CLA.

For the tests, is there a link or article as to which proper automated tests I should run and how to run them?

2019-12-03 22:29 UTC, VladimirZaets commented
@princefishthrower we run tests automatically, you can check results of the tests in GitHub checks.
In this case, you change the logic, so you should cover this logic with any type of automated tests (unit/functional/integration). You can find guidelines and examples how to write new tests on http://devdocs.magento.com/

2020-02-05 09:32 UTC, engcom-Echo commented
I will take care of test coverage.

2020-02-06 15:55 UTC, engcom-Echo commented
Failure of functional test, not related to the changes in this PR , test failing on 2.4-develop branch
![image](https://user-images.githubusercontent.com/51681435/73953968-d547b080-4909-11ea-8daf-0f037b070571.png)

2020-02-13 08:50 UTC, Nazar65 requested changes

2020-02-13 08:50 UTC, Nazar65 commented on app/code/Magento/ConfigurableProduct/Test/Unit/Model/Product/Type/ConfigurableTest.php
> +        ->method('getLinkField')
```suggestion
            ->method('getLinkField')
```

2020-02-13 08:50 UTC, Nazar65 commented on app/code/Magento/ConfigurableProduct/Test/Unit/Model/Product/Type/ConfigurableTest.php
> +        $storeId = 1;
Could you please move data to dataProvider ?

2020-02-25 09:26 UTC, engcom-Echo commented
Hi @VladimirZaets could you please approve it?

2020-03-12 07:57 UTC, engcom-Echo commented
Hi @VladimirZaets could you please approve it?

2020-05-04 19:47 UTC, engcom-Echo commented
Hi @VladimirZaets could you please approve it?

2020-06-11 20:24 UTC, VladimirZaets commented
@engcom-Echo can you please resolve conflicts?

2020-06-12 14:37 UTC, engcom-Echo commented
@magento run all tests

2020-06-15 10:07 UTC, engcom-Echo commented
Hi @VladimirZaets could you please approve it?

2020-08-27 13:50 UTC, ihor-sviziev submitted a review, later dismissed

2020-08-27 13:51 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8086](https://jira.corp.magento.com/browse/ENGCOM-8086) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-03 11:59 UTC, engcom-Alfa requested changes
Hi @princefishthrower 
Unfortunately, we are not able to reproduce this [issue](https://github.com/magento/magento2/issues/25287) on a fresh 2.4-develop

**Precondition:**

Configurable product with 5 children ( 3 -  In Stock, 2 - Out of Stock)

**Manual testing scenario:**

1. Inject LinkManagement into any custom code (Class `Magento\ConfigurableProduct\Mode\LinkManagement`)
2. Call getChildren() with an SKU of a given configurable product (for example let's say it has 5 child simple products, where 3 are in stock and 2 are out of stock.)

```
// ex. product with sku 'configurable2' is a known configurable product with 5 simple product children
$childProducts = $this->linkManagement->getChildren("configurable2");
echo sizeof($childProducts);
// 5.... (further inspection shows all 5 products)
```

**Actual Result:** :heavy_check_mark: 5. The children array include ALL 5 children of the configurable product
![Screenshot from 2020-09-03 14-58-21](https://user-images.githubusercontent.com/51679138/92112094-f2882300-edf5-11ea-84ff-17b1aedba43c.png)

@princefishthrower Could you take a look?

Thanks!

2020-09-07 14:37 UTC, gabrieldagama commented
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

2020-09-11 06:31 UTC, ihor-sviziev commented
@princefishthrower could you confirm that this issue isn't reproducible anymore or add some additional info in order to reproduce it?
Thank you!

2020-09-17 21:52 UTC, sidolov commented
@princefishthrower , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-17 21:52 UTC, closed without merging