Added backticks to table names in mysql schema reader.
magento/magento2 pull request #25354
Opened 2019-10-29 15:33 UTC by vincenthornikx

Added backticks to table names in mysql schema reader. Otherwise indexes cannot be added to tables whose name coincide with reserved mysql words (e.g. order).

### Description (*)
When using db_schema to add an index to a table the DbSchemaReader class is used to describe the table. If that table name coincides with a reserved mysql keyword this causes errors.

### Manual testing scenarios (*)
1. Use a db_schema.xml to add a new field to the order table. 
2. In the same schema also add an index for that field. 
3. Run php bin/magento setup:upgrade

### Questions or comments
Before this fix this causes an error because mysql rejects the SHOW INDEXES and SHOW CREATE TABLE queries because 'order' is a reserved word. After this fix the changes are processed correctly.

### Contribution checklist (*)
 - [ y ] Pull request has a meaningful description of its purpose
 - [ y ] All commits are accompanied by meaningful commit messages
 - [ y ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ y ] All automated tests passed successfully (all builds are green)

2019-10-29 17:22 UTC, VladimirZaets approved these changes

2019-10-29 17:23 UTC, VladimirZaets requested changes
Hi @vincenthornikx , please, sign CLA, otherwise, we can't process your pull request

2019-10-29 17:24 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6204](https://jira.corp.magento.com/browse/ENGCOM-6204) has been created to process this Pull Request

2019-10-29 17:24 UTC, magento-engcom-team commented
@vincenthornikx thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-10-30 07:33 UTC, vincenthornikx commented
@VladimirZaets I just signed the CLA.

2019-10-31 15:01 UTC, slavvka commented
@magento run all tests

2019-11-11 18:51 UTC, VladimirZaets approved these changes

2019-11-11 18:52 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6204](https://jira.corp.magento.com/browse/ENGCOM-6204) has been created to process this Pull Request

2019-11-13 08:27 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-11-14 14:23 UTC, merged