Fix #25243
magento/magento2 pull request #25359
Opened 2019-10-29 23:02 UTC by korostii

### Description (*)
JS version of `__('Carrier with such method not found: %1, %2', 'one', 'two')` should produce the message of `'Carrier with such method not found: one, two'`

JS component receives a pre-translated message template yet parameters are sent separately:
![JSON sent via ajax response](https://user-images.githubusercontent.com/24894168/67815370-ac0fbc80-fa9e-11e9-9ad8-40129d458aa7.png)
And then the messages.js assumes that resulting `messageObj` property names should match the varNames in the message template string (discounting the first `%` symbol) which happens to be off by one if the varNames are integers. 

Worth mentioning: in most cases they are numbers, however support for string varNames seems to be implied and even relied on, for example there a translated string like the following: `You can check the status of your order by <a href=""%account_url"">logging into your account</a>.`.

Solution: simply decrement varName (as long as it's a number).

### Fixed Issues
1. magento/magento2#25243: Numerical placeholder count in Phrase starts with %1, however JS code assumes %0

### Manual testing scenarios
Please see #25243 for detailed steps.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-09 21:51 UTC, krzksz approved these changes

2019-12-13 13:38 UTC, engcom-Alfa commented
Hi @korostii.
     Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by jasmine test.
Thanks!

2019-12-19 17:09 UTC, korostii commented
Hi @engcom-Alfa so we've looked into these jasmine tests as used by Magento with a colleague of mine, as guided by the [devdocs article](https://devdocs.magento.com/guides/v2.3/test/js/jasmine.html) and we can't seem to figure out if it supports frontend theme tests, at all (and this PR deals with JS used on frontend). 
So for example `grunt spec:backend` does run some tests (some of them failing on a clean Magento), whereas `grunt spec:frontend` doesn't seem to invoke Jasmine, at all:
![Screenshot from 2019-12-19 18-58-13](https://user-images.githubusercontent.com/24894168/71193414-ca21be00-2292-11ea-8c29-da8509404095.png)
![Screenshot from 2019-12-19 19-05-04](https://user-images.githubusercontent.com/24894168/71193417-cdb54500-2292-11ea-84cb-d745ba09cb57.png)

Any hints/directions?

2019-12-20 10:10 UTC, krzksz commented
@korostii You can try `grunt spec:blank` and `grunt spec:luma`.

2020-01-13 11:22 UTC, korostii commented
Hi @krzksz 
We added tests for the `messages.js`, please review.

2020-02-05 11:51 UTC, krzksz requested changes
Thank you for the tests! There are some comments I added that are mainly focused on tests isolation. Also, please change the structure a bit, the idea is that every `describe` and `it` inside them should add up to a somewhat logical sentence, for example:
```
describe('add method', function () {
            it('simple message', function () {
```
will result in a test description of `Magento_Ui/js/model/messages add method simple message` which is not grammatically correct and informative when test passes or fails. Changing that to
```
describe('add method', function () {
            it('adds massage without parameters', function () {
```
would result in `Magento_Ui/js/model/messages add method adds message without parameters` which is more on point in my opinion.

2020-02-05 11:51 UTC, krzksz commented on dev/tests/js/jasmine/tests/app/code/Magento/Ui/frontend/js/model/messages.test.js
> +                expect(obj).toBeDefined();
I don't think this check is necessary, as tests will fail anyway on `var obj = new Constr({` if it cannot be initialized.

2020-02-05 11:51 UTC, krzksz commented on dev/tests/js/jasmine/tests/app/code/Magento/Ui/frontend/js/model/messages.test.js
> +        var obj = new Constr({
A fresh object should be created `beforeEach` otherwise tests won't be isolated and they should be.

2020-02-05 11:51 UTC, krzksz commented on dev/tests/js/jasmine/tests/app/code/Magento/Ui/frontend/js/model/messages.test.js
> +                expect(type).toEqual(returnedObj);
How about just reusing `[messageObject.message]`?

2020-02-05 11:51 UTC, krzksz commented on dev/tests/js/jasmine/tests/app/code/Magento/Ui/frontend/js/model/messages.test.js
> +                expect(obj.hasMessages()).toEqual(true);
Every test here should be isolated and not depend on other tests being executed before or after it.

2020-02-24 13:32 UTC, engcom-Golf commented
HI @krzksz could you please review new changes ?

2020-02-25 06:22 UTC, krzksz submitted a review, later dismissed
Hey, thanks for the update! Unfortunately there is still this thing I mentioned in https://github.com/magento/magento2/pull/25359#pullrequestreview-353596903 which should be taken into account in my opinion.

2020-02-25 09:12 UTC, engcom-Golf commented
@krzksz could you please take a look ?

2020-02-27 08:25 UTC, krzksz approved these changes

2020-02-27 08:26 UTC, magento-engcom-team commented
Hi @krzksz, thank you for the review.
[ENGCOM-6996](https://jira.corp.magento.com/browse/ENGCOM-6996) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-02-27 10:21 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:**
![before](https://user-images.githubusercontent.com/51679138/75434511-54a13080-595a-11ea-99b0-2f58447af96c.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/75434489-4a7f3200-595a-11ea-9024-cddccff88e95.png)

2020-02-28 22:04 UTC, merged