Corrected date format issue for different locale
magento/magento2 pull request #25372
Opened 2019-10-30 13:01 UTC by Digisha-97

Invalid Date Time Format issue for other locale
parterres-contribution  Partner: CommercePundit

### Description (*)

Date Time format is working properly for US only but when we change it to Germany or any other locale. Its throwing error on products save when we are adding values for  **Set Product as New From**. 

Reason it is not changing date format according configured locale.

Currently added solution for it, so now when we will change locale from configuration it will work fine.

Changed the filter method, as here system is not getting proper value to change according to selected locale.

 `$value = $this->_localeDate->formatDateTime($value, \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT, $currentLocaleCode, null, null);`

the value in filter method was not coming proper for other locale. so updated it as above. 

I have checked this fix on **Magento 2.3.2 and 2.3.3**

### Fixed Issues (if relevant)

1. magento/magento2#**24696**: Invalid input datetime format of value in Others locale 2.3.2 #24696

### Manual testing scenarios (*)

1. Change locale to Germany from admin  > Stores > Configuration > General > Locale Options 
    here change **Locale** option to Germany
2. On top right corner admin menu click on Account Settings(admin)
    here change **Interface Locale** to Germany 
3. Navigate to Catalog  > Products 
    Select any product to edit it
    here add value for **Set Product as New From** for product and click on Save button

### Questions or comments

This is my first contribution , so please let me know if I missed anything or any correction require from my  #side.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-31 15:02 UTC, slavvka commented
@magento run all tests

2019-11-14 10:04 UTC, craigcarnell commented
Can this be merged please??

2019-11-14 10:38 UTC, Digisha-97 commented
I am not able to merge it. Merging is blocked.

Regards,

<https://www.commercepundit.com/>

*Digisha Patel, Development Technical Lead*
(O) 079-40399638 / 39
digisha@commercepundit.com


On Thu, Nov 14, 2019 at 3:35 PM Craig Carnell <notifications@github.com>
wrote:

> Can this be merged please??
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/25372?email_source=notifications&email_token=ANQLEPE3L7AETSDTE6STY43QTUPHLA5CNFSM4JGY5FOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEBJC7Y#issuecomment-553816447>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANQLEPC5IJFFNW53MZRFIILQTUPHLANCNFSM4JGY5FOA>
> .
>

2020-08-20 18:08 UTC, sidolov requested changes
@Digisha-97 please, cover changes with automated tests

2020-08-20 18:08 UTC, sidolov commented on lib/internal/Magento/Framework/Stdlib/DateTime/Filter/DateTime.php
> +    public function __construct(\Magento\Framework\Stdlib\DateTime\TimezoneInterface $localeDate, Resolver $localeResolver)
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.4/contributor-guide/backward-compatible-development/)

2020-08-22 12:29 UTC, Digisha-97 commented on lib/internal/Magento/Framework/Stdlib/DateTime/Filter/DateTime.php
> +    public function __construct(\Magento\Framework\Stdlib\DateTime\TimezoneInterface $localeDate, Resolver $localeResolver)
public function __construct(\Magento\Framework\Stdlib\DateTime\TimezoneInterface $localeDate, ?Resolver $localeResolver = null) 
    {
        parent::__construct($localeDate);
        $this->localeResolver = $localeResolver;
     
        $this->_localToNormalFilter = $_localToNormalFilter ?: ObjectManager::getInstance()->create(Resolver::class);

        
[DateTime.zip](https://github.com/magento/magento2/files/5112348/DateTime.zip)
Hi ,

I have updated it. 
but I am not able to push my changes. 
getting below error :
warning: url has no scheme: github.com
fatal: credential url cannot be parsed: github.com

2020-09-04 12:18 UTC, engcom-Echo commented
I will take care of test coverage.

2020-09-04 14:00 UTC, engcom-Echo commented
@magento run all tests

2020-09-04 15:20 UTC, sidolov approved these changes, later dismissed

2020-09-04 15:21 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8133](https://jira.corp.magento.com/browse/ENGCOM-8133) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-07 09:26 UTC, engcom-Echo commented
Hi, @Digisha-97. Continuing to investigate, unfortunately, I could not reproduce the issue on 2.4-develop.
Look to file "lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php".
![image](https://user-images.githubusercontent.com/51681435/92371578-6f701100-f104-11ea-95f8-f83aac189591.png)
Here we already get the current locale. In my opinion, this will be enough.
Instead, using "$ this -> _ localeDate-> formatDateTime ()" will fail, for example, when "$value = 28/11/2020".
![image](https://user-images.githubusercontent.com/51681435/92372270-59af1b80-f105-11ea-929b-856576481540.png)

2020-09-15 08:48 UTC, engcom-Alfa requested changes
Hi @Digisha-97 . 

Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop

**Manual testing scenario:**

1. Change locale to Germany from **admin > Stores > Configuration > General > Locale Options**
and change **Locale** option to **Germany**;
2. On the top right corner admin menu click on Account Settings(admin)
and change Interface Locale to Germany;
3. Navigate to **Catalog > Products;**
4. Select any product to edit it;
5. Add value for Set Product as New From for product and click on the Save button;

**Actual Result:** :heavy_check_mark:  The product with **New From** - **To** values was successfully saved

![Peek 2020-09-15 11-42](https://user-images.githubusercontent.com/51679138/93188088-3ad60800-f749-11ea-83e2-53f87bbd8300.gif)

@Digisha-97 Could you take a look?
Thanks!

2020-09-15 12:16 UTC, Digisha-97 commented
Hi @engcom-Alfa ,

Yes this issue is not coming in magento 2.4

2020-09-15 13:45 UTC, engcom-Echo commented
Hi @Digisha-97 , I'm closing this PR we can't process your pull request.
Please reopen and update if you wish to continue.
Thank you for your collaboration

2020-09-15 13:45 UTC, closed without merging