Update README.md
magento/magento2 pull request #25384
Opened 2019-10-30 18:50 UTC by missione

2019-11-09 10:52 UTC, missione commented
is there anything else i could add?

2019-11-22 20:28 UTC, ptylek requested changes
I am not sure about changing first paragraph. Why did you make this change? Also the text contains errors. Requested changes.

2019-11-22 20:28 UTC, ptylek commented on README.md
> +**Welcome** to your magento 2 installation ! We're glad you chose to install Magento 2.
Unnecessary space after `installation`

2019-11-22 20:28 UTC, ptylek commented on README.md
> +It's an e-commerce platform written in PHP that provides online merchants with a flexible shopping cart system as well as control over the look, functionality, and content of the online store. It als
I think that last sentence shouldn't be `search engines for marketing` but `marketing, search engine optimization, and catalog-management tools`. Also why would you change that paragraph from `Welcome` to `What is Magento 2?`?

2019-11-22 20:28 UTC, ptylek commented on README.md
> +**Welcome** to your magento 2 installation ! We're glad you chose to install Magento 2.
`Magento` should use capital letter

2019-11-27 14:32 UTC, ptylek commented
@missione , I am closing this PR now due to inactivity. Also format is not valid .
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-11-27 14:32 UTC, closed without merging