Fix loose switch comparison when adding links without content types
magento/magento2 pull request #25473
Opened 2019-11-05 11:57 UTC by AydinHassan

### Description (*)

I've refactored the switch to a bunch of `if` blocks because switches perform loose comparisons. So in `switch` version of the code, if `canTypeBeFont` returns false, and `$contentType` is equal to an empty string, then that switch block executes because an empty string and false are deemed to be the same.

This problem has caused issue https://github.com/shipperhq/module-shipper/issues/73.

Due to the fact that a link without a content type is found to be a font, the attributes passed are overwritten.

### Fixed Issues (if relevant)
1. shipperhq/module-shipper#73: Carriers logos are not displayed on shipping step (https://github.com/shipperhq/module-shipper/issues/73)

### Manual testing scenarios (*)
1. Add a link to the page head without a content type and with a custom attribute. Eg `https://github.com/shipperhq/module-shipper/blob/master/src/view/frontend/layout/checkout_index_index.xml#L13`
2. See that the attributes are replaced with `rel="preload" as="font" crossorigin="anonymous"` in the page source

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-05 13:25 UTC, AydinHassan commented
Not sure what happened with the Static Tests here, they seem to be all green when I click through. Also runs fine locally.

2019-11-06 08:44 UTC, rogyar requested changes
Hi @AydinHassan. Thank you for your contribution. It does make sense. I would kindly ask you to reflect the mentioned case ("canTypeBeFont returns false, and $contentType is equal to an empty string") in the [following](https://github.com/magento/magento2/blob/a917ee7ee60b891b785dbdced8ee366a6de6c934/lib/internal/Magento/Framework/View/Test/Unit/Page/Config/RendererTest.php#L20) unit test. It should not take much time.
Also, please, take a look at the failing static tests.

Thank you!

2019-11-06 10:39 UTC, AydinHassan commented
@rogyar I've added a test. Static tests run fine locally. Let's see what the build says.

2019-11-06 13:21 UTC, AydinHassan commented
Database fail looks unrelated

2019-11-06 15:44 UTC, rogyar approved these changes

2019-11-06 15:47 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-6239](https://jira.corp.magento.com/browse/ENGCOM-6239) has been created to process this Pull Request

2019-11-06 15:47 UTC, magento-engcom-team commented
@AydinHassan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-11-06 16:35 UTC, AydinHassan commented
@magento-engcom-team done :)

2019-11-08 15:22 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-11-14 14:23 UTC, merged

2019-11-15 09:51 UTC, AydinHassan commented
Thanks :)