Resolved AdobeStock issue 641
magento/magento2 pull request #25525
Opened 2019-11-08 08:54 UTC by drpayyne

### Description
Resolved https://github.com/magento/adobe-stock-integration/issues/641. Please refer to https://github.com/magento/adobe-stock-integration/pull/670 for more information

### Fixed Issues
-  magento/adobe-stock-integration#641: The licensed label is shown under the image if the row of images has small height

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-10 21:22 UTC, sivaschenko commented
Hi @drpayyne , thanks for the pull request! I think it's better to extend the overlay component from magento2 core and and implement `getStyles` method in AdobeStockImageAdminUi module as these styles are specific to Adobe Stock Integration grid

2019-11-10 21:22 UTC, sivaschenko requested changes
Hi @drpayyne , thanks for the pull request! I think it's better to extend the overlay component from magento2 core and and implement `getStyles` method in AdobeStockImageAdminUi module as these styles are specific to Adobe Stock Integration grid

2019-11-11 04:04 UTC, drpayyne commented
Will do @sivaschenko, thanks!

2019-11-11 17:28 UTC, closed without merging

2019-11-12 04:53 UTC, drpayyne commented
Ported to https://github.com/magento/adobe-stock-integration/pull/670