Remove usage of normalizeDate in favor of convertToMomentFormat
magento/magento2 pull request #25544
Opened 2019-11-09 22:31 UTC by krzksz

### Description (*)

This change removes the usage of `normalizeDate` in favor of `convertToMomentFormat` because it seems to be used more widely. It is also making its implementation more universal based on `normalizeDate` contents.
### Fixed Issues (if relevant)

1. magento/magento2#14568: normalizeDate() and convertToMomentFormat() in misc.js is the same

### Manual testing scenarios (*)

I don't see any.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-11 18:00 UTC, VladimirZaets requested changes
Hi @krzksz. Please take a look at failed tests

2019-11-25 21:42 UTC, VladimirZaets commented on lib/web/mage/utils/misc.js
> -        normalizeDate: function (mageFormat) {
I think we shouldn't remove this method because someone can already use it and we will break customer implementation

2019-11-25 21:42 UTC, VladimirZaets commented
Hi @krzksz. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

2019-11-25 21:43 UTC, krzksz commented
Actually, after working with tests I realized that both input and output data is different for both methods and it is not possible to unify them without breaking compatibility. I'm closing this PR and linked issue.

2019-11-25 21:43 UTC, closed without merging