Fix escape less calc
magento/magento2 pull request #25552
Opened 2019-11-11 10:01 UTC by jasperzeinstra

### Description (*)
We've escaped the content in the calc, this way the calc in the css file will be `calc(100% + 3px)` instead of `calc(103%)`

### Manual testing scenarios (*)
1. Hover over root category in main navigation and inspect the height of the after element being added.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-11 17:58 UTC, VladimirZaets requested changes
Hi @jasperzeinstra. Thanks for collaboration. According documentation ( https://www.w3schools.com/cssref/func_calc.asp ) of culc function current syntax is correct and should work fine

2019-11-12 18:39 UTC, jasperzeinstra commented
@VladimirZaets yes, `calc(100% + 3px)` is fine in CSS, but not in LESS. Because LESS will try to calculate `100% + 3px` and that results in `103%`. You need to wrap this in `~'100% + 3px'`, then LESS will see it as a string and not do the calculation. And then the output will be `calc(100% + 3px)` instead of `calc(103%)`

Here's a screenshot of the currently wrong complied CSS.
<img width="403" alt="Screenshot 2019-11-12 at 19 35 32" src="https://user-images.githubusercontent.com/9214557/68699619-c4de9e80-0583-11ea-8372-df807c15fd90.png">

You can also see that every where calc is being used in LESS file the `~'…'` syntax is being used.

2019-11-12 19:14 UTC, VladimirZaets commented
> @VladimirZaets yes, `calc(100% + 3px)` is fine in CSS, but not in LESS. Because LESS will try to calculate `100% + 3px` and that results in `103%`. You need to wrap this in `~'100% + 3px'`, then LESS will see it as a string and not do the calculation. And then the output will be `calc(100% + 3px)` instead of `calc(103%)`
> 
> Here's a screenshot of the currently wrong complied CSS.
> <img alt="Screenshot 2019-11-12 at 19 35 32" width="403" src="https://user-images.githubusercontent.com/9214557/68699619-c4de9e80-0583-11ea-8372-df807c15fd90.png">
> 
> You can also see that every where calc is being used in LESS file the `~'…'` syntax is being used.

Ok, thanks for the explanation

2019-11-12 19:14 UTC, VladimirZaets approved these changes

2019-11-12 19:16 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6273](https://jira.corp.magento.com/browse/ENGCOM-6273) has been created to process this Pull Request

2019-11-13 13:23 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed 

**Before:**
![before](https://user-images.githubusercontent.com/51679138/68767480-679d2880-0629-11ea-8715-9cd149d4b332.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/68767501-6ff56380-0629-11ea-8a00-04b00cbbd82d.png)

2019-11-25 21:26 UTC, merged