Add null return hint to RouterInterface docblock
magento/magento2 pull request #25651
Opened 2019-11-19 09:31 UTC by marcusirgens

### Description (*)
In the wild, returns null in almost all implementations:
- lib/internal/Magento/Framework/App/Router/Base.php:274
- app/code/Magento/Cms/Controller/Router.php:108
- app/code/Magento/Robots/Controller/Router.php:60
- app/code/Magento/UrlRewrite/Controller/Router.php:89

The exception seems to be
\Magento\Webapi\Controller\Rest\Router\Route::match which returns array|false (!?) and must be fixed,
 as well as \Magento\Webapi\Controller\Rest\Router::match which returns RouterInterface

### Manual testing scenarios (*)
This fix should resolve issues detected by static analysis

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-17 14:01 UTC, ihor-sviziev requested changes
Hi @marcusirgens,
Good finding! Could you fix all places where not null was returned?

2020-02-17 14:32 UTC, ihor-sviziev commented
@magento run all tests

2020-02-24 08:10 UTC, engcom-Echo commented
@magento run all tests

2020-02-25 19:01 UTC, ihor-sviziev commented
Moved to status “to approve” in order to get approval for SVC failure

2020-08-18 16:10 UTC, sidolov commented
@magento create issue

2020-08-25 19:29 UTC, sidolov requested changes
@marcusirgens , @ihor-sviziev I would prefer to throw an exception in case of route does not match. Right now we can see the different implementation with the return type of `null|false` and all client code should handle them to work correctly. With exception approach, it will be clear how to use it - get an object or exception in case if something went wrong.

2020-08-26 06:46 UTC, ihor-sviziev commented
@sidolov I don't agree with such approach. 

In case if you don't have any matched route to the current request - is it exceptional situation? No. something went wrong? Also no. So why we would throw an exception in such case?

In my opinion in such case you have to just return "no results" value, that is "NULL" in programming language.

In addition to what I described above adding throwing an exception should be treated as backward incompatible changes, this is one of the basic interfaces that are working with routing and in case if we'll introduce here any issues - it definitely will be catastrophe. I believe this is a mistake that it's not marked with `@api` tag.

2020-08-26 12:14 UTC, marcusirgens commented
@ihor-sviziev 

> In case if you don't have any matched route to the current request - is it exceptional situation? No. something went wrong? Also no. So why we would throw an exception in such case?

Actually, I disagree: I think  `match` implies that this class can handle the request. I expect a result that I can use from this method, not "null". If we are uncertain if the class can handle the request, I think it makes sense to add a method like `canMatch` or something.

However, this would require a major rewrite of almost all classes implementing `RouterInterface`. I think it might be better to deprecate this routing system entirely.

@sidolov, what do you think? Go for the strongly typed version? Require the return type to be `ActionInterface`? Add a type hint? Keep null? If we decide to make a new RouterInterface, we need a lot more code ;)

2020-08-26 14:57 UTC, sidolov commented
@ihor-sviziev it's the same as `ProductRepository`, following your logic it should return product object or null in case if the product was not found. If method cannot handle the provided request it is an exceptional case because we cannot correctly work with the response. 

@marcusirgens totally agree with you that such changes are not backward compatible and most likely may be delivered to the next minor release, 2.5 for example. So, if you are interested to do that right, we still have time until the next release :)

2020-08-26 19:00 UTC, marcusirgens commented
@sidolov I've opened a discussion in https://github.com/magento/community-features/issues/292 which relates to this issue.

2020-08-31 05:47 UTC, ihor-sviziev commented
@marcusirgens @sidolov ok, I don't mind of refactoring this logic at all, but as for me this PR was targeting to fix incorrect return type on **existing implementation**. And as part of it it doesn't make sense to introduce any exceptions, as they weren't there.

2020-09-07 12:43 UTC, gabrieldagama commented
The risk was set to`low` due to: the suggested changes shouldn't impact other areas.

2020-09-11 06:09 UTC, ihor-sviziev commented
@marcusirgens @sidolov 
As I understood - this PR should be closed and new implementation should be created instead PSR-7 / PSR-15 for HTTP requests?

2020-09-11 09:20 UTC, marcusirgens commented
@ihor-sviziev 
> As I understood - this PR should be closed and new implementation should be created instead PSR-7 / PSR-15 for HTTP requests?

That's a major refactor and a big BC break, though so it at least deserves some discussion.

2020-09-11 09:26 UTC, ihor-sviziev commented
@marcusirgens sure, I don't mind about that discussion, but not clear should we keep this PR till the discussion will be finished or should we just close it?

2020-09-11 10:37 UTC, marcusirgens commented
@ihor-sviziev 
> @marcusirgens sure, I don't mind about that discussion, but not clear should we keep this PR till the discussion will be finished or should we just close it?

Well, the current docblock is still wrong.

2020-09-11 11:36 UTC, ihor-sviziev commented
Ok, so moving back to "to approve" status

2024-10-23 11:10 UTC, engcom-Dash commented
Hello @marcusirgens,

Thanks for your contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks!

2024-10-23 14:50 UTC, closed without merging