fix ordering of plugin list for after plugins
magento/magento2 pull request #25678
Opened 2019-11-21 05:01 UTC by brosenberger

Description (*)

as described in https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html#prioritizing-plugins the order of the after plugin is inversed to the before plugin sorting. currently before and after plugins are not inverse sorted on execution

Manual testing scenarios (*)

add a plugin like the \Magento\Customer\Model\Layout\DepersonalizePlugin which depends on a customer session value
add the plugin with the sort order below 10 (execute beforeGenerateXml before the customer plugin and execute afterGenerateXml after the customer plugin) in order to restore correctly the values within the customer session (needed for page cache segmentation)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

also see closed not finished pull request https://github.com/magento/magento2/pull/19227 for 2.2 release line

2020-03-02 13:05 UTC, ihor-sviziev commented
@magento run all tests

2020-03-03 09:46 UTC, ihor-sviziev requested changes
Hi @brosenberger,
Thank you for your pull request!
According to test failures - looks like your change breaks existing functionality. Few types of tests weren't able to be ran at all (usually it happens because of fatal error during magento installation).

Could you review test failures and adjust your solution?

2020-03-19 08:59 UTC, ihor-sviziev commented
Hi @brosenberger,
Will you be able to update your PR?

2020-03-25 06:03 UTC, brosenberger commented
@ihor-sviziev i am afraid but i am a bit out of time currently to do any fixes

2020-03-25 20:33 UTC, ihor-sviziev commented
Hi @brosenberger,
In this case I'll close this PR as it required additional work. Feel free to re-open it or just create a new one when you'll have some time for that.

Thank you for your contribution!

2020-03-25 20:33 UTC, closed without merging