Unit Test to cover class \Magento\Captcha\CustomerData\Captcha
magento/magento2 pull request #25686
Opened 2019-11-21 14:31 UTC by edenduong

### Description (*)

Unit Test to cover class \Magento\Captcha\CustomerData\Captcha
- Test getSectionData() when user is login and require captcha

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

Covered by Unit Test

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-22 04:03 UTC, lbajsarowicz requested changes

2019-11-22 04:03 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> +     * @var CaptchaHelper | \PHPUnit_Framework_MockObject_MockObject
Unnecessary spaces

2019-11-22 04:03 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> +    public function testGetSectionData()
The test name should be more explanatory, current is too generic.

2019-11-22 06:02 UTC, edenduong commented
Hi @lbajsarowicz: I have changed it. Please check it again.

2019-11-22 13:04 UTC, lbajsarowicz requested changes
Several changes, in my opinion, are still necessary. Not crucial ones, but still something that needs to be done.

2019-11-22 13:04 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> +        $this->customerData = $this->createMock(CustomerData::class);
If you are instantiating mock there and using only for this test, use local variable instead of class property.

2019-11-22 13:04 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> +class CaptchaTest extends \PHPUnit\Framework\TestCase
Import the class.

2019-11-22 13:04 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> + * Class \Magento\Captcha\Test\Unit\CustomerData\CaptchaTest
This line is completely redundant.

2019-11-22 13:04 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> +    private $helper;
It's highly recommended to mark that it's still mock, not the real implementation by renaming the property to `helperMock`

2019-11-22 13:04 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> +    private $customerSession;
Append `Mock` to name to mark that's not real implementation.

2019-11-22 13:04 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Test/Unit/CustomerData/CaptchaTest.php
> +    private $customerData;
Append `Mock` to name to mark that's not real implementation.

2019-11-23 18:31 UTC, lbajsarowicz approved these changes
Now it's fine. Thanks for your contribution!

2019-11-23 18:32 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6322](https://jira.corp.magento.com/browse/ENGCOM-6322) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-11-24 21:59 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-11-26 03:21 UTC, merged