Issue 25268
magento/magento2 pull request #25728
Opened 2019-11-25 09:13 UTC by rajeebkumar-sahoo

resolved issue#25268: order get customer returns null from observer
### Description (*)

This merge request resolves issue#25268 (order get customer returns null from observer)
### Fixed Issues (if relevant)

1. magento/magento2#25268: $order->getCustomer() returns NULL for registered customer

### Manual testing scenarios (*)

Pre-requisite: 
    i. setup:di:compile after getting the new code
    ii. clean the configuration cache after adding event observer

1. Create one observer for event "sales_order_save_after".
2. Place an order with a registered customer account.
3. Try to access customer object from order object within the observer created above.
4. You will be able to get customer data instead of null after this fix.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-25 10:11 UTC, kanthy-i95dev approved these changes

2019-11-26 07:49 UTC, ihor-sviziev requested changes
Unfortunately adding new method to existing functionality will break backward compatibility, more details: https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/

Why do you think order model should have method "getCustomer"?

As for me it shoudn't as it's not his responsibility. It should just contain getCustomerId method or something like this, and it is:
https://github.com/magento/magento2/blob/bff0d385cfc6138b5a75423498bf9e9a88061d79/app/code/Magento/Sales/Model/Order.php#L2744-L2747

If you need to have customer - you can get it from customer repository.

I would mark it as not an issue

2019-12-03 10:14 UTC, ihor-sviziev requested changes
Hi @rajeebkumar-sahoo,
1. First of all - there is a lot not related changes. Could you force push only needed changes?
2. I don't see any difference in order model, looks like you missed to push them

2019-12-16 16:31 UTC, VladimirZaets commented
@rajeebkumar-sahoo , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-12-16 16:31 UTC, closed without merging