Fix item prices not beeing displayed in order summary on checkout
magento/magento2 pull request #25762
Opened 2019-11-26 16:50 UTC by lumnn

### Description (*)

Magento_Tax/checkout/summary/item/details/summary template
does checks if `getRegion(..)` is truish.

getRegion(region) always returns array therefore the above check
always gives same result.

Fixed by changed if expression to check length truthiness.

### Manual testing scenarios (*)

Not sure.

### Questions or comments

Didn't check that on clean Magento install, although with using browser debugger I ensured file is not changed by any module, no mixin applied to that file there is no template updates.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-07 10:58 UTC, krzksz requested changes
Hey @lumnn, thanks for contribution! Please sign the CLA, otherwise we are not able to process this PR. There are also some failing functional tests which you should look into.

2020-05-27 13:22 UTC, engcom-Charlie commented
Hi @lumnn, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-05-27 13:22 UTC, closed without merging

2022-07-14 09:20 UTC, lumnn commented
I do think I did sign that CLA. Can this be merged now?

2022-07-14 09:22 UTC, lumnn commented
https://github.com/magento run all tests

2022-07-14 09:22 UTC, lumnn commented
@magento run all tests