Change tag name
magento/magento2 pull request #25777
Opened 2019-11-27 14:35 UTC by AndreyChorniy

### Description (*)
This PR fixes the unnecessary issue in exeption.log

### Fixed Issues (if relevant)

1. magento/magento2#25738: DOMDocument::loadHTML(): Tag date invalid in Entity

### Manual testing scenarios (*)

1. Create a new customer or Login with an existing (user should be logged in)
2. Place order
3. Go to Order view page  (you can delete exeption.log before)
4. Check exeption.log (It should not contain `DOMDocument::loadHTML(): Tag date invalid in Entity`)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-27 16:45 UTC, rogyar commented
With the current implementation, `DOMDocument` will parse a string as HTML4. So yes, the `<date>` tag is only supported starting from HTML5. I believe this solution makes sense as a hotfix until `libxml_use_internal_errors` is implemented globally in the escaper class.

2019-11-27 16:47 UTC, rogyar requested changes

2019-11-27 16:47 UTC, rogyar commented on app/code/Magento/Catalog/view/frontend/templates/product/listing.phtml
> -$start = microtime(true);
Please, remove this change from the current commit. I believe you have already introduced the same change in another PR.

Thank you.

2019-12-04 08:44 UTC, closed without merging

2019-12-04 08:45 UTC, AndreyChorniy commented
Closed because the new one was created here https://github.com/magento/magento2/pull/25895