#25042 Remove logo dimension parameters from layout files
magento/magento2 pull request #25789
Opened 2019-11-28 12:22 UTC by mfickers

### Description (*)

This PR fixes a problem where a new logo is uploaded in the backend, without specifying width and height parameters. Magento then used the `logo_img_width` and `logo_img_height` block arguments set in the layout file for the Logo block as fallback, possibly distorting the new logo. This is confusing behavior for the user, as the logo should be displayed with its native dimensions if no width and height parameters are explicitly set.

Notice that it is still possible to configure the logo dimension via layout files, using `logo_width` and `logo_height` instead of `logo_img_width` and `logo_img_height` as block arguments. With this changes, the `logo_img_width` and `logo_img_height` block arguments are no longer used by the block.

### Fixed Issues (if relevant)

1. magento/magento2#25042: Store logo inherits height and width from luma logo, if no height and width is provided

### Manual testing scenarios (*)

1. Upload a new logo in the backend (Content > Design > Configuration > Global > Edit > Header > Upload Logo), don't set the height and width fields
2. Clear cache
3. Got to storefront homepage
4. Logo dimension should be native image dimension, not Luma logo dimension

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-29 07:28 UTC, dmytro-ch requested changes
Hello @mfickers, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
At least by unit test in `\Magento\Theme\Test\Unit\Block\Html\Header\LogoTest`.
Thank you!

2019-11-29 11:47 UTC, mfickers commented
I've added unit tests for both image dimension getters of the header logo block.

2019-11-30 08:59 UTC, dmytro-ch approved these changes

2019-11-30 09:01 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6371](https://jira.corp.magento.com/browse/ENGCOM-6371) has been created to process this Pull Request

2019-12-01 21:16 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2019-12-03 17:09 UTC, merged