align terms and conditions checkbox correctly
magento/magento2 pull request #25810
Opened 2019-11-28 15:46 UTC by torhoehn

### Description (*)

This PR will correct the alignment of the terms & conditions checkbox in Checkout.

### Fixed Issues (if relevant)

1. magento/magento2#25801: Alignment of terms & conditions checkbox

### Manual testing scenarios (*)

1. Create and activate Terms & Conditions under Stores -> Settings -> Terms and Conditions with longer checkbox text
2. Enable Terms & Conditions under Stores -> Configuration -> Sales -> Checkout -> Checkout Options
3. On a mobile device go to the second step of the Checkout

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-28 17:52 UTC, dmytro-ch requested changes
Hi @torhoehn, thank you for your contribution!
Could you please also fix the minor issues reported by Static Test?

2019-11-28 17:52 UTC, dmytro-ch commented on app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_checkout-agreements.less
> +                    &::after {
```suggestion
                    &:after {
```

2019-11-28 17:52 UTC, dmytro-ch commented on app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_checkout-agreements.less
> +                            &::after {
```suggestion
                            &:after {
```

2019-11-28 17:52 UTC, dmytro-ch commented on app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_checkout-agreements.less
> +                        &::after {
```suggestion
                        &:after {
```

2019-11-28 17:52 UTC, dmytro-ch commented on app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_checkout-agreements.less
> +                            font-size: @form-field-label-asterisk__font-size;
Could you please use `.lib-font-size` mixin here?

2019-11-30 09:11 UTC, dmytro-ch requested changes
@torhoehn, thank you for the updates.
Unfortunately, there are still failing functional tests. I'm not sure exactly, but the issue might be caused by flexbox usage.
Could you please check the test failures?

2019-11-30 09:11 UTC, dmytro-ch commented on app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_checkout-agreements.less
> +                            font-size: .lib-font-size(@form-field-label-asterisk__font-size);
```suggestion
                            .lib-font-size(@form-field-label-asterisk__font-size);
```

2019-11-30 09:11 UTC, dmytro-ch commented on app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_checkout-agreements.less
> +                            font-size: .lib-font-size(@form-field-label-asterisk__font-size);
Also, the mixins calls should go first, e.g. 
```
&:after {
    .lib-font-size(@form-field-label-asterisk__font-size);
    color: @form-field-label-asterisk__color;
    content: '*';
    margin: @form-field-label-asterisk__margin;
}
```

2019-12-16 16:24 UTC, VladimirZaets commented
@torhoehn, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-12-16 16:24 UTC, closed without merging