Fix catalog page add configurable product to wishlist
magento/magento2 pull request #25840
Opened 2019-11-29 11:01 UTC by mfickers

### Description (*)

When changing a configurable product's options on the catalog page, the wishlist item option iterates over every option for every attribute and every product on the page, repeatedly overwriting the saved value and only remembering the last value on the page.
This fix changes the wishlist option update to only evaluate the single option that triggered the event.
The PR also includes some refactoring of the _updateWishlistData method.

### Fixed Issues (if relevant)

1. magento/magento2#25091: Product option not reflated at my wish list when added from listing page

### Manual testing scenarios (*)

1. Go to a catalog page with several configurable products sharing the same attribute option. For the Magento sample data, this would be for example the women's jackets category.
2. Set the options of any product but the last and add this product to the wishlist.
3. Go to wishlist and click on the just added product
4. The options set on the catalog page should be set on the product detail page

### Questions or comments

Are there situations, where the removed iterations over every option was necessary, that could be negatively affected by this change?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-01 08:22 UTC, krzksz requested changes
Hey @mfickers, thanks for the contribution! Please check the functional test that is failing.

2019-12-01 08:27 UTC, krzksz requested changes

2019-12-01 08:27 UTC, krzksz commented on app/code/Magento/Wishlist/view/frontend/web/js/add-to-wishlist.js
> +                    dataToAdd = $.extend(dataToAdd, self._getElementData(element));
If this `.each` is really unnecessary here then I believe `self` can also be removed in favour of using `this` directly.

2019-12-16 16:22 UTC, VladimirZaets commented
@mfickers, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2019-12-16 16:22 UTC, closed without merging