Add mass action to invalidate indexes via admin
magento/magento2 pull request #25860
Opened 2019-11-30 13:35 UTC by fredden

### Description (*)
This pull request adds the ability for an administrator to mark indexes as invalid via the admin. The indexes will then be run by the normal minutely cron.

### Fixed Issues (if relevant)
I am not aware of any open issues regarding this change.

### Manual testing scenarios (*)
1. Browse to admin -> System -> Tools -> Index Management
1. Select index tickbox
1. Use mass-action drop-down to select 'invalidate index'
1. Click 'submit'
1. Observe index is now marked as invalid

### Questions or comments
I have used the existing permission "Change indexer mode", but can move this to its own permission category if desired.

I copied the 'masschangelog' controller & test to make this action.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-03 17:14 UTC, ihor-sviziev requested changes

2019-12-03 17:14 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +    public function execute()
I believe in the controller itself should be check for ACL. Please add it, otherwise people without needed permission  will be able to execute this controller.

2019-12-03 17:14 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer.php
>                  return $this->_authorization->isAllowed('Magento_Indexer::changeMode');
Please move it to separate ACL, as it’s not change of indexer mode

2019-12-03 17:14 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +        $this->_redirect('*/*/list');
Could you return result object on controller instead?

2019-12-03 17:14 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +                    $model = $this->_objectManager->get(
Please get rid of using object manager here, instead please inject needed object in constructor

2019-12-03 17:14 UTC, ihor-sviziev commented on app/code/Magento/Indexer/etc/acl.xml
> +                        <resource id="Magento_Indexer::changeMode" title="Change indexer mode &amp; invalidate index" translate="title" sortOrder="40" />
Please revert this change and add addition ACL record instead

2019-12-03 17:14 UTC, ihor-sviziev commented on app/code/Magento/Indexer/view/adminhtml/layout/indexer_indexer_list_grid.xml
> +                            <item name="invalidate_index" xsi:type="array">
Will we have confirmation popup?

2019-12-08 23:04 UTC, fredden commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +    public function execute()
Is this not the purpose of the `_isAllowed()` method that's inherited? None of the other controllers in this module explicitly test for permissions. Please can you link an example of checking permissions that I can adapt?

2019-12-08 23:07 UTC, fredden commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +                    $model = $this->_objectManager->get(
This is the method used in the other mass action controllers in this module. Would you like me to change all the controllers here to not use an Object Manager? It makes sense to me to keep these consistent with one another.

2019-12-09 06:12 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +                    $model = $this->_objectManager->get(
Let’s fix only in this class, unfortunately there are still too many such places

2019-12-10 19:06 UTC, fredden commented on app/code/Magento/Indexer/view/adminhtml/layout/indexer_indexer_list_grid.xml
> +                            <item name="invalidate_index" xsi:type="array">
I've added a confirmation step here.

2019-12-10 19:47 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +    public function execute()
Yeah, sorry I just missed it

2019-12-10 19:48 UTC, ihor-sviziev requested changes
Now changes looks good, please fix tests issues

2019-12-10 19:48 UTC, ihor-sviziev commented on app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassInvalidate.php
> +    public function execute()
Yeah, sorry I just missed it

2019-12-17 07:56 UTC, ihor-sviziev approved these changes

2019-12-17 07:56 UTC, ihor-sviziev commented
Static test failure is false positive. Changes approved 👍

2019-12-17 07:57 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6490](https://jira.corp.magento.com/browse/ENGCOM-6490) has been created to process this Pull Request

2019-12-17 11:11 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-01-09 12:04 UTC, engcom-Golf commented
@magento run all tests

2020-01-30 15:49 UTC, slavvka commented
The failure of Sanity check is a known issue. https://jira.corp.magento.com/browse/MTS-852

2020-02-09 00:23 UTC, merged