Fixed #25901
magento/magento2 pull request #25903
Opened 2019-12-04 15:23 UTC by divyajyothi5321

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#25901: Mobile design issues in Minicart Dropdown Dialog

### Manual testing scenarios (*)

1. Add item to cart.
2. Now open minicart dropdown dialog in mobile Portrait and Landscape view.
3. Change the qty and click out of the qty box so that update button will be displayed.
4. After this fix is applied the issue will be fixed as shown in the below screenshots.

![update-cart-expected-result](https://user-images.githubusercontent.com/54176640/70155125-af1e4e00-16d7-11ea-9cd9-ecc0c1bf6aa0.png)

![edit-delete-expected](https://user-images.githubusercontent.com/54176640/70155124-ae85b780-16d7-11ea-8bfe-db4304e80be9.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-06 10:20 UTC, kanthy-i95dev approved these changes

2019-12-07 10:54 UTC, krzksz requested changes
Please use `.media-width` mixin to define media queries and `@indent__` variables.

2019-12-09 10:01 UTC, krzksz requested changes

2019-12-09 10:01 UTC, krzksz commented on app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less
> +    .minicart-items .item-qty {
I believe this can be merged with the one at line 412.

2019-12-09 10:01 UTC, krzksz commented on app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less
> +.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
This can be merged with line 418.

2019-12-09 10:01 UTC, krzksz commented on app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less
> +and (max-device-width: @screen__m) {
This has to use two separate `.media-width`, one for minimum `@screen__xs` and one for minimum `@screen__m` that sets those values back.

2019-12-09 11:58 UTC, krzksz requested changes

2019-12-09 11:58 UTC, krzksz commented on app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less
> +    .minicart-items .product-item-details .details-qty {
Please add an empty line before.

2019-12-09 11:58 UTC, krzksz commented on app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less
> +    .minicart-items .item-qty {
Please add an empty line before.

2019-12-09 11:58 UTC, krzksz commented on app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less
> +and (max-device-width: @screen__m) {
Maybe what I wrote is not clear enough here. I would like you to split this media query into 2 separate ones so we can use `.media-width` is such a way:
```less
.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__xs) {
  // your styles with margin and padding.
}

.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {
  // styles reverting margin and padding for bigger screens.
}
```

2019-12-10 08:57 UTC, krzksz requested changes
Please make the changes I requested.

2019-12-10 09:14 UTC, krzksz requested changes

2019-12-10 09:14 UTC, krzksz commented on app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less
> +and (max-device-width: @screen__m) {
This one is still not addressed.

2019-12-10 09:50 UTC, krzksz approved these changes

2019-12-10 09:51 UTC, magento-engcom-team commented
Hi @krzksz, thank you for the review.
[ENGCOM-6438](https://jira.corp.magento.com/browse/ENGCOM-6438) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-12-10 09:51 UTC, magento-engcom-team commented
@divyajyothi5321 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-12-10 09:53 UTC, krzksz commented
Purely visual change, no tests required.

2019-12-10 13:22 UTC, kanthy-i95dev approved these changes

2019-12-12 09:58 UTC, engcom-Alfa commented
Hi @divyajyothi5321 

Unfortunately, we are not able to reproduce this [issue](https://github.com/magento/magento2/issues/25901) on the fresh 2.4-develop instance

**Actual Result:**
Portrait
![before](https://user-images.githubusercontent.com/51679138/70702207-6289d280-1cd6-11ea-83f4-ee3a948f405c.png)

Landscape
![before2](https://user-images.githubusercontent.com/51679138/70702225-6cabd100-1cd6-11ea-993c-42035ebf5085.png)

Looks like this issue was already fixed in PR [#25206](https://github.com/magento/magento2/pull/25206)

@divyajyothi5321 Could you take a look?

Thanks!

2019-12-12 10:16 UTC, closed without merging