Resolve 25889 catalog rule product indexing
magento/magento2 pull request #25908
Opened 2019-12-04 21:46 UTC by rossmitchell

### Description (*)

Updates the IndexBuilder class to call `fetchItem` on the Collection rather than `foreach`. This prevents the entire collection being loaded at once which significantly speeds up the indexing time

### Fixed Issues (if relevant)

1. magento/magento2#25889: Catalog Rule Product index time increases exponentially as new rules are added

### Manual testing scenarios (*)

1. Install Magento
2. Copy setup/performance-toolkit/profiles/ce/small.xml to a new file
3. Update the file to have 2,000 simple products, 2,000 categories, and 25,000 catalog price rules
4. Generate fixtures using the file
5. Run the Catalog Rule Product index
6. The index should complete in a few minutes rather than an hour

### Questions or comments

Alongside the change mentioned in the ticket, there are a couple of other places in the class that were calling `foreach` on the collection. I've applied the same update to them as well
 
I'm not sure of the best way to put together a test to cover these changes, the behaviour should be the same just faster. If you can give any guidance on what should be included I'll add in tests for this.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-10 06:38 UTC, aleron75 approved these changes

2019-12-10 06:39 UTC, magento-engcom-team commented
Hi @aleron75, thank you for the review.
[ENGCOM-6437](https://jira.corp.magento.com/browse/ENGCOM-6437) has been created to process this Pull Request

2019-12-10 06:39 UTC, magento-engcom-team commented
@rossmitchell thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-12-12 14:10 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed


 With 25,000 catalog price rules (with fix)
```
$ php bin/magento indexer:reindex catalogrule_rule
Catalog Rule Product index has been rebuilt successfully in 00:04:44
Product Price index has been rebuilt successfully in 00:00:02
Catalog Search index has been rebuilt successfully in 00:00:10
```

2019-12-12 16:37 UTC, VladimirZaets requested changes
Hi @rossmitchell. Thanks for collaboration. 
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

2019-12-13 12:24 UTC, rossmitchell commented
Hi @VladimirZaets 

As I mentioned in the opening ticket, I'm not sure how to put together a test for these changes. They shouldn't change any existing behaviour, just they way that records are fetched from the database.

If you can give me some guidance over what sort of tests should be written to cover the changes, I'll add them and update the PR. Thanks

2020-02-07 16:33 UTC, lenaorobei commented
I run Performance build on this branch and got `Create category (Admin Category Management): 10.7% (mainline = 356 | team = 394) -> DEGRADATION`.
You can reproduce this locally by using JMeter and `setup/performance-toolkit/benchmark.jmx` scenario.

2020-02-09 23:55 UTC, rossmitchell commented
Hi @lenaorobei

Thanks for taking a look at this. I'm not sure why this would cause a performance degradation, but I will look into it.

I've not really used JMeter before and I'm having some difficulties running the performance tests locally. I've followed the instructions here https://github.com/magento/magento2/tree/2.3/setup/performance-toolkit and searched through the github issues to try and get these running.

Based on what I've found I put together a script here https://gist.github.com/rossmitchell/8c8df1dc632aa0c9d8a7cb8928882eb8 to setup a magento instance with the sample data and then run the scenario, however I'm not sure how to get the changes compared to the mainline branch.

I'm also seeing failures in the output saying `text expected to contain /You deleted the category./` which when I look at the access logs look to be coming from these requests `"POST /admin/catalog/category/delete/id/${admin_category_id}/ HTTP/1.1"`

Can I ask you to have a quick look at the script that I'm using and see if there is anything obviously wrong with it?

Thanks

2020-05-20 19:53 UTC, mslabko approved these changes

2020-05-20 20:30 UTC, lenaorobei commented
@rossmitchell we are investigating performance failure issue. I will keep you updated.

2020-05-20 20:34 UTC, lenaorobei commented
Internal PAT build https://bamboo.corp.magento.com/browse/MCCE24-MCCE24569-1

2020-05-25 07:02 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Install Magento;
2. Copy _setup/performance-toolkit/profiles/ce/small.xml_ to a new file;
3. Update the file to have 2,000 simple products, 2,000 categories, and (500, 1000, 5000, 25000) catalog price rules;
4. Generate fixtures using the file;
5. Run the Catalog Rule Product index;

 _**With 500 catalog price rules**_

_Before:_
![before500](https://user-images.githubusercontent.com/51679138/82786660-b09e2700-9e6d-11ea-939c-396f43edd756.png)


_After:_
![after500](https://user-images.githubusercontent.com/51679138/82786665-b3991780-9e6d-11ea-9e21-5db11260d925.png)

The value has improved by **33%**

 _**With 1000 catalog price rules**_

_Before:_
![before1000](https://user-images.githubusercontent.com/51679138/82787037-5487d280-9e6e-11ea-98b7-b17ef67fc1bd.png)

_After:_
![after1000](https://user-images.githubusercontent.com/51679138/82787065-5b164a00-9e6e-11ea-9501-99dac7a3d607.png)

The value has improved by **67%**

 _**With 5000 catalog price rules**_

_Before:_
![before5000](https://user-images.githubusercontent.com/51679138/82787163-8862f800-9e6e-11ea-9cd2-22ca03c09f28.png)


_After:_
![after5000](https://user-images.githubusercontent.com/51679138/82787173-8bf67f00-9e6e-11ea-8ab7-850f738b92f5.png)


 _**With 25000 catalog price rules**_

_Before:_
The indexing time was more than 2 hours

_After:_
![after25000](https://user-images.githubusercontent.com/51679138/82787276-ba745a00-9e6e-11ea-86fc-aa5654b84ea2.png)

2020-05-25 07:07 UTC, engcom-Charlie commented
@magento run all tests

2020-05-26 18:03 UTC, lenaorobei commented
As per discussion with @mslabko - perf degradation is expected.
Neds to be approved internally.

2020-05-27 07:56 UTC, engcom-Charlie requested changes
Hi @rossmitchell, could You fix failing tests?

2020-06-30 11:20 UTC, engcom-Charlie commented
Hi @rossmitchell, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2021-09-13 20:38 UTC, torhoehn commented
@lenaorobei Since #25889 still is an open issue, should this PR be really closed? The author already mentioned that he need some guidance. What's the state of the internal approval you mentioned before?

2021-09-15 20:16 UTC, rossmitchell commented
@magento run all tests

2021-11-25 07:19 UTC, ihor-sviziev commented
@magento run all tests

@sidolov, can we re-run the performance tests? Do we still get the performance degradation? If so - please explain in which case?

2021-11-25 15:01 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2021-11-26 06:31 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2021-12-20 12:11 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2021-12-28 07:56 UTC, torhoehn commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2022-01-03 10:08 UTC, engcom-Dash commented
Hi @rossmitchell 

Thanks for your contribution!
I am looking into the build failures.

Thanks

2022-01-03 10:21 UTC, engcom-Dash commented
@magento run all tests

2022-01-03 10:25 UTC, engcom-Dash commented
@magento run all tests

2022-01-03 12:59 UTC, engcom-Dash commented
@magento run all tests

2022-01-05 08:27 UTC, engcom-Dash commented
Following functional and integration test case are failing 
Functional Tests B2B
    AdminCreateCatalogPriceRuleToPercentTest
    AdminCreateCatalogPriceRuleByPercentTest
    AdminCreateCatalogPriceRuleToFixedTest
    AdminEnableAttributeIsUndefinedCatalogPriceRuleTest

Functional Tests CE
    StorefrontConfigurableProductOutOfStockCustomStockTest
    StorefrontGalleryConfigurableProductWithVisualSwatchAttributePrependMediaTest

Integration Tests
   testCustomerGroupExcludeWebsite

All these testcases failure is not related to this PR changes as checked.

2022-01-05 08:32 UTC, engcom-Charlie submitted a review, later dismissed

2022-01-06 07:54 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Tested the PR before and after changes as per [above comments](https://github.com/magento/magento2/pull/25908#issuecomment-633413636).
After more updates re-tested now using same above steps and PR changes successfully resolved the issue as shown in the below screenshot.

<img width="1440" alt="Screenshot 2022-01-05 at 9 39 19 PM" src="https://user-images.githubusercontent.com/51679138/148348476-5f2a3cf0-ce06-44d7-a7c7-40c56af138df.png">

Based on the [above comment](https://github.com/magento/magento2/pull/25908#issuecomment-1005476989) on auto-test failure analysis, moving this PR for _Merge In Progress_.

2022-02-28 17:32 UTC, adifucan approved these changes

2022-03-01 06:23 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2022-03-01 17:46 UTC, adifucan requested changes
This PR breaks some functional scenarios (see functional tests) + integration test

2022-03-01 18:03 UTC, kandy commented on app/code/Magento/CatalogRule/Model/Indexer/IndexBuilder.php
> +        while ($rule = $activeRules->fetchItem()) {
Looks like using fetchItem make an improvement due to the fact that it does not call \Magento\CatalogRule\Model\ResourceModel\Rule\Collection::_afterLoad and it breaks functionality that requires data is loaded in this method

2023-06-09 10:15 UTC, engcom-Hotel commented
Hello @rossmitchell,

Thanks for the contribution!

We request you to please resolve the conflicts of this PR so that we can proceed further with this.

Thanks

2023-07-03 12:17 UTC, engcom-Hotel commented
Moved back to `On Hold` as conflicts needs to be resolve yet.

2023-07-11 12:40 UTC, engcom-Hotel commented
Hello @rossmitchell,

As per this comment https://github.com/magento/magento2/pull/25908#issuecomment-1584334058, we are unable to move further on this PR until the conflicts have been resolved. 

Hence we are closing this PR for now. Please feel free to re-open it whenever you are ready or ask us for the same, we will be happy to re-open it.

Thanks

2023-07-11 12:40 UTC, closed without merging