Resolve issue 25896: Cannot create folder using only letters
magento/magento2 pull request #25904
Opened 2019-12-04 15:52 UTC by edenduong

### Description (*)

1. Consistency between message and behavior when create Non-latin letter folder => Change message to:
`Please rename the folder using only Latin letters, numbers, underscores and dashes.`

This PR was covered by Unit Test.

### Fixed Issues (if relevant)

1. magento/magento2#25896: Cannot create folder using only letters

### Manual testing scenarios (*)

1. On CMS edit page open media gallery
2. Click "Create Folder"
3. Type in "папка"
4. Click "OK"

#### Expected result

1. Consistency between message and behavior. => Change message to:
`Please rename the folder using only Latin letters, numbers, underscores and dashes.`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-05 06:28 UTC, dmytro-ch commented
@magento give me test instance

2019-12-05 06:28 UTC, magento-engcom-team commented
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

2019-12-05 06:29 UTC, magento-engcom-team commented
Hi @dmytro-ch, here is your [new Magento instance](https://pr-25904.instances.magento-community.engineering).
Admin access: [https://pr-25904.instances.magento-community.engineering/admin](https://pr-25904.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-12-05 08:42 UTC, dmytro-ch requested changes
It looks like extending the media browser component `lib/web/mage/adminhtml/browser.js` (`newFolder` function) with frontend validation is complicated. So let's stick to at least proper backend validation messages for now.

2019-12-05 08:42 UTC, dmytro-ch commented on app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php
> +                __('Please rename the folder using only Latin letters, numbers, underscores and dashes.')
Could you please also add the new translation string to `Magento_Cms/i18n/en_US.csv`?

2019-12-10 15:13 UTC, edenduong commented
@dmytro-ch: I have updated the csv file. You can check it again. Thank you !

2019-12-10 19:01 UTC, dmytro-ch approved these changes

2019-12-10 19:02 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6443](https://jira.corp.magento.com/browse/ENGCOM-6443) has been created to process this Pull Request

2019-12-11 10:14 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-12-12 06:32 UTC, merged