Refactor: Add method hints to Tracking Status
magento/magento2 pull request #25954
Opened 2019-12-08 21:28 UTC by lbajsarowicz

### Description (*)
Actually, instead of mentioning the fields in Tracking Status, it's better to provide method hints.

### Fixed Issues (if relevant)
1. Nope.

### Manual testing scenarios (*)
1. Implement Tracking Status in your Carrier method
2. Your IDE should suggest  one of setters / getters.

### Questions or comments
None

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-09 09:58 UTC, ihor-sviziev requested changes

2019-12-09 09:58 UTC, ihor-sviziev commented on app/code/Magento/Shipping/Model/Tracking/Result/Status.php
> + * @method string getCarrier()
all getters could return `null` in case when model isn't filled with data.
```suggestion
 * @method string|null getCarrier()
```

2019-12-09 09:58 UTC, ihor-sviziev commented on app/code/Magento/Shipping/Model/Tracking/Result/Status.php
> + * @method string getCarrierTitle()
```suggestion
 * @method string|null getCarrierTitle()
```

2019-12-09 10:00 UTC, lbajsarowicz commented
@ihor-sviziev You're right.

2019-12-09 11:24 UTC, ihor-sviziev approved these changes

2019-12-09 11:25 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6432](https://jira.corp.magento.com/browse/ENGCOM-6432) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-12-10 14:18 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2019-12-12 06:32 UTC, merged