Hardcode usage of AddressInterface when merging address objects
magento/magento2 pull request #25965
Opened 2019-12-10 06:18 UTC by JeroenVanLeusden

### Description (*)
Hardcode usage of AddressInterface when merging address objects. Extension attributes might cause the `get_class($existingAddressDataObject)` return an interceptor class.

### Fixed Issues (if relevant)
1. Relates to magento/magento2#10583: Checkout place order exception when using a new address.

### Manual testing scenarios (*)
1. Create extension attribute on `\Magento\Customer\Api\Data\AddressInterface`.
2. Create customer account.
3. Create order in adminhtml area.

### Questions or comments
Given error:
> Order saving error: Method's return type must be specified using @return annotation. See Magento\Customer\Model\Data\Address\Interceptor::setData()

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-10 06:56 UTC, dmytro-ch requested changes
Hi @JeroenVanLeusden , thank you for your contribution!
Could you please cover your changes by unit test in `\Magento\Sales\Test\Unit\Model\AdminOrder\CreateTest`?

Thank you!

2019-12-10 06:56 UTC, dmytro-ch commented on app/code/Magento/Sales/Model/AdminOrder/Create.php
> +                \Magento\Customer\Api\Data\AddressInterface::class,
Please avoid FQCN usage.

2019-12-24 11:11 UTC, JeroenVanLeusden commented
Didn't find time to update this yet, will do once I find some.

2020-01-10 09:53 UTC, dmytro-ch commented
Hello @JeroenVanLeusden, I'm closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

2020-01-10 09:53 UTC, closed without merging