Fix 25936
magento/magento2 pull request #25989
Opened 2019-12-11 11:24 UTC by divyajyothi5321

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#25936: Regular Price Label Alignment Issues in Frontend

### Manual testing scenarios (*)

1. Admin->Catalog->Products->Add Product
2. Add Price ex:$20
3. Click on Advanced Pricing and add regular price ex:$10
4. Save the product
5. Open product in frontend 
6. you can see the issue is fixed with this code as shown in the below screenshot.
![regularprice-expectedresult](https://user-images.githubusercontent.com/54176640/70617434-9ca39780-1c36-11ea-908a-8f3f0e2a059d.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-11 11:25 UTC, kanthy-i95dev approved these changes

2019-12-11 13:03 UTC, ptylek commented
@magento give me test instance

2019-12-11 13:03 UTC, magento-engcom-team commented
Hi @ptylek. Thank you for your request. I'm working on Magento instance for you

2019-12-11 13:03 UTC, magento-engcom-team commented
Hi @ptylek, here is your [new Magento instance](https://pr-25989.instances.magento-community.engineering).
Admin access: [https://pr-25989.instances.magento-community.engineering/admin](https://pr-25989.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2019-12-11 13:22 UTC, ptylek requested changes
@divyajyothi5321 Thanks for your contribution. Your solution breaks SKU into two lines, see the photo:
![image](https://user-images.githubusercontent.com/34317830/70624941-ab338400-1c21-11ea-9e34-828dc6882cd6.png)

2019-12-12 19:34 UTC, ptylek requested changes
Your changes break line on price box and sku. Screenshot was taken on ipad.
<img width="236" alt="Screenshot 2019-12-12 at 20 30 29" src="https://user-images.githubusercontent.com/34317830/70742846-c1733a00-1d1e-11ea-83c1-823638ab738f.png">

2019-12-12 19:34 UTC, ptylek commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +
Doesn't make sense. Looks like this:
<img width="344" alt="Screenshot 2019-12-12 at 20 31 02" src="https://user-images.githubusercontent.com/34317830/70742698-63deed80-1d1e-11ea-8113-a30cf694aa12.png">

2019-12-12 19:34 UTC, ptylek commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +
And I guess you want to achieve this:
![image](https://user-images.githubusercontent.com/34317830/70742744-86710680-1d1e-11ea-998d-e3259e90fc7b.png)

2019-12-27 11:14 UTC, ptylek commented
@divyajyothi5321, I am closing this PR now due to inactivity. Please reopen and update if you wish to continue. Thank you for collaboration

2019-12-27 11:14 UTC, closed without merging