Refactor: Add information about the path that is not allowed
magento/magento2 pull request #26009
Opened 2019-12-12 10:24 UTC by lbajsarowicz

### Description (*)
Added missing information about the path that is not allowed.

### Fixed Issues (if relevant)
1. Lack of information about the problematic path 
   ![image](https://user-images.githubusercontent.com/1639941/70704083-9a424b80-1cd1-11ea-9d36-f1a00e2ec764.png)

### Manual testing scenarios (*)
1. Try to initiate Media Storage for file that is outside the allowed directories.
2. The exception with file path should be logged.

### Questions or comments
Nope.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-12 10:58 UTC, lbajsarowicz commented
It's a trap :rofl: 
Will refactor the file to fit the requirements.

2019-12-12 11:00 UTC, dmytro-ch requested changes
Hi @lbajsarowicz, thank you for your contribution!
Could you please cover the changes by unit test in `\Magento\MediaStorage\Test\Unit\App\MediaTest` ?

2019-12-12 12:50 UTC, lbajsarowicz commented
@dmytro-ch Added Unit Test to cover the case.

I'm not satisfied with the fact that wanting to change a single line (add missing information to Exception) I had to fix all the issues introduced previously to the file. I'm also not excited with the fact that adding a single Unit Test check I had to decouple existing Object, to be able to change the hardcoded value.

2019-12-13 21:58 UTC, lbajsarowicz commented
@dmytro-ch Could you help me with Sample Data Tests? I have no idea what's wrong there :-)

2019-12-18 09:30 UTC, dmytro-ch commented
@lbajsarowicz, thank you for your efforts and for performing extensive refactoring.

2019-12-18 09:31 UTC, dmytro-ch approved these changes

2019-12-18 09:32 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6497](https://jira.corp.magento.com/browse/ENGCOM-6497) has been created to process this Pull Request

2019-12-18 12:14 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed 

**Before:**
![before](https://user-images.githubusercontent.com/51679138/71085656-ae3def80-21a0-11ea-8104-f08802ddaf55.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/71085672-b433d080-21a0-11ea-8537-2219de7d44a4.png)

2019-12-19 03:48 UTC, merged