Removes setting domain when domain for cookies empty
magento/magento2 pull request #26035
Opened 2019-12-13 21:00 UTC by krisdante

The previous implementation set the domain for cookies to the current
domain provided in the Request object.
As per RFC - https://tools.ietf.org/html/rfc6265#section-4.1.2.3,
this is the default behavior to use the current domain (and only
current domain) when the domain is not set in setcookie call.
Setting the domain explicitly during setcookie has a side effect
- the cookie is also visible for subdomains.
This visibility is probably not intended.  Current implementation
(before my change) is based on old  RFC (https://tools.ietf.org/html/rfc2109)
when domain shall be prepended with dot to make it visible for subdomains.
If a user wants to include cookie for subdomains - shall provide
the domain in cookie settings.

### Description (*)

I just removed the setting of the default domain when it is not explicitly provided. That will default to RFC so functionally everything shall work the same but without side effects.

### Fixed Issues (if relevant)

1. magento/magento2#17323 : form_key cookie contain leading dot
1. magento/magento2#13505 : Cookie collision with multiple magento instances

### Manual testing scenarios (*)

#### Steps to reproduce

Change the configuration to set the cookie for specific domain
Login in the backend with valid details
Store > Configuration > General
Change the website view to save the configuration for only website wise
Web Default Cookie Settings > Cookie Domain set your website domain (i.e magento.loc)
Set the cookie path to /
Save the configuration
clear cacher and clear browser cookies(for the current domain) and restart the browser

#### Expected result
All Magento cookie should set the only domain without any leading dot but in the form_key cookie I can see it is adding a leading dot (and I don't want to set the cookie for subdomain as well)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-17 22:06 UTC, krisdante commented
One test is still failing because I simply do not understand this test.

2020-10-19 16:00 UTC, ihor-sviziev requested changes
Hi @krisdante,
Could you resolve the conflicts?

I just analyzed your solution - in general it looks good, but it's not backward compatible as potentially it could cause cookie conflict, for instance when you'll have simultaneously 2 cookies set, example:
| Cookie Name | Value | Domain | Expiration date |
| ---------------| -------| ----------| ----------------|
| PHPSESSID | test-value-1 | .www.mydomain.com| 2020-10-20 | 
| PHPSESSID | test-value-2 | www.mydomain.com| 2020-10-30 |

For session cookies I wee there is a could  that should prevent such conflict behavior
https://github.com/magento/magento2/blob/32ed03cad4f2b2abc6ca6e5dc14885cd822c4508/lib/internal/Magento/Framework/Session/SessionManager.php#L564-L582

The same cookie domain used for `form_key` and some other cookies, so it might cause additional issues there.

Any thoughts how it could be fixed?

2020-11-09 09:26 UTC, ihor-sviziev commented
Hi @krisdante,
Will you be able to update your PR with suggested changes?

2020-11-11 22:23 UTC, sidolov commented
@krisdante  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-11-11 22:23 UTC, closed without merging

2020-11-11 22:49 UTC, krisdante commented
Seriously guys. You need to improve. I waited like 6 months for feedback.
Then you were not able to wait even a week for feedback of mine? And closed a ticket.

2020-11-12 07:52 UTC, ihor-sviziev commented
Hi @krisdante,
I'm really sorry for inconvenience. Please feel free to put the comment or just reopen the PR yourself. We just have a policy to close the PR if there is no activity for 2 weeks. 
Closing PR doesn't mean that we won't accept your PR, but in order to have cleaner list of not processed PRs.

2021-02-22 17:49 UTC, mvaisberg commented
Hi @krisdante , finally your PR it is working and do not cause another issue? i am confused about how this was managed

2021-03-06 22:01 UTC, alexvais commented
@ihor-sviziev could you solved that issue too? why this was abandoned?