[Catalog] Cover Component/FilterFactory by Unit Test
magento/magento2 pull request #26042
Opened 2019-12-14 12:07 UTC by edenduong

### Description (*)

[Catalog] Cover Component/FilterFactory by Unit Test

Cover Class `Magento\Catalog\Ui\Component\FilterFactory`

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

**vendor/bin/phpunit app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php**

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-14 14:34 UTC, kalpmehta approved these changes

2019-12-14 14:35 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-6468](https://jira.corp.magento.com/browse/ENGCOM-6468) has been created to process this Pull Request

2019-12-14 20:37 UTC, lbajsarowicz requested changes
You may also `Optimize imports` in your PHPStorm to sort the imports with alphabetic order.

2019-12-14 20:37 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
> +     * @var UiComponentFactory|\PHPUnit_Framework_MockObject_MockObject
Alias `\PHPUnit_Framework_MockObject_MockObject` as `MockObject`

2019-12-14 20:37 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
> +use Magento\Framework\TestFramework\Unit\Helper\ObjectManager as ObjectManagerHelper;
You don't really need to suffix with `Helper`. `ObjectManager` is quite clear.

2019-12-14 20:37 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
> +            ]
You can extract that to private const `STUB_COLOR_OPTIONS` for example.

2019-12-14 20:37 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
> +                            ]
Then refer to that STUB.

2019-12-14 20:37 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
> +        $attributeMock->method('getAttributeCode')->willReturn('color');
Also - extract that to private const `STUB_ATTRIBUTE_CODE`

2019-12-14 20:37 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
> +                        'dataScope' => 'color',
Refer to `STUB_ATTRIBUTE_CODE`

2019-12-14 23:05 UTC, edenduong commented
Hi @lbajsarowicz: Thank you. I have changed the source code. Please check it.

2019-12-15 00:15 UTC, lbajsarowicz requested changes
I haven't expected that kind of stub, but it's also fine.
Last replacement and I'll accept the PR.

2019-12-15 00:15 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Unit/Ui/Component/FilterFactoryTest.php
> +            ->with('color', 'filterSelect', [
`self::STUB_ATTRIBUTE['attribute_code']`

2019-12-15 04:31 UTC, edenduong commented
I have changed it. Please check it again. Thanks @lbajsarowicz

2019-12-17 11:59 UTC, edenduong commented
Could you please take a look? Thanks @lbajsarowicz

2019-12-17 12:25 UTC, lbajsarowicz approved these changes
Thank you for your contribution.

2019-12-17 12:26 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6468](https://jira.corp.magento.com/browse/ENGCOM-6468) has been created to process this Pull Request

2019-12-17 14:30 UTC, engcom-Delta commented
**Notice:** QA not applicable

2019-12-18 02:50 UTC, merged