Refactor: Code refactoring according to standards and rules
magento/magento2 pull request #26049
Opened 2019-12-14 19:11 UTC by andrewbess

### Description (*)

Code refactoring according to standards and rules
I think we should use constants value that correspond standards and rules.
According to Magento db_schema and setup scripts type "VARCHAR" has max length 255.
According to mysql standards, a "TEXT" column with a maximum length of 65,535 (2<sup>16</sup> − 1) characters. The effective maximum length is less if the value contains multibyte characters. Each TEXT value is stored using a 2-byte length prefix that indicates the number of bytes in the value.

### Fixed Issues (if relevant)

1. nope

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-14 20:10 UTC, lbajsarowicz approved these changes
Great catches! :green_heart: 

Fix Unit Tests and Static tests, by the way, you can improve the names of tests that do not say anything about the fail:
![image](https://user-images.githubusercontent.com/1639941/70854010-50668a80-1eb6-11ea-9485-bdee73d8cf50.png)

2019-12-14 20:11 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6473](https://jira.corp.magento.com/browse/ENGCOM-6473) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-12-15 19:54 UTC, lbajsarowicz requested changes

2019-12-15 19:54 UTC, lbajsarowicz commented on app/code/Magento/ImportExport/Model/Import/AbstractEntity.php
> - * @api
I'm afraid you cannot just remove `@api`

2019-12-15 19:54 UTC, lbajsarowicz commented on app/code/Magento/ImportExport/Model/Import/Entity/AbstractEntity.php
> - * @api
I'm afraid you cannot just remove `@api`

2019-12-15 19:54 UTC, lbajsarowicz commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Validator.php
>          $val = $this->string->cleanString($this->_rowData[$attrCode]);
How about extracting that to separate method `isTextValid` that will return the result immediately?

There will be no need to use elseif / else, then. The result of isTextValid will be assigned to $valid (I'd rename that to $isValid)

2019-12-17 19:38 UTC, andrewbess commented
@lbajsarowicz Perhaps, it was bad idea to refactor this part of core Magento.
How do you think?

2019-12-20 12:26 UTC, closed without merging