Grid export issue  task 25963
magento/magento2 pull request #26046
Opened 2019-12-14 14:55 UTC by konarshankar07

### Description (*)

This PR will fix the customer_group column data is not reflected in the exported CSV 
### Fixed Issues (if relevant)

1. magento/magento2#25963: Grid Export rendered data is not reflecting in the exported File, Displayed ID instead of Rendered Label

### Manual testing scenarios (*)

1. Log in to the Magento Admin
2. Click "sales" from the menu on the left
3. Click "order"
4. Click on Export
5. Select CSV/Excel XML

### Expected Result
![image](https://user-images.githubusercontent.com/39480008/70850407-d16e5380-1eaf-11ea-899f-821380b492cb.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-15 07:18 UTC, konarshankar07 commented
I found that we can reuse the `Magento\Sales\Ui\Component\DataProvider\Document` class instead of creating new `Magento\Sales\Ui\Component\DataProvider\Order\Document` which is introduced in this PR because I think it violates DRY principle. We need to name the column for the `customer_group_id` needs to be same for whole application I found some inconsistency in `sales_order_grid` and `sales_invoice_grid`.

2020-01-23 15:31 UTC, novikor commented
Hi, @konarshankar07. Thank you for your contribution.
The problem is reproduced globally while exporting any grid, even custom.

Could you please investigate for a more universal solution?
I am going to check it as well.

2020-01-23 16:32 UTC, novikor submitted a review, later dismissed
I suggest taking a look at `\Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult`.
Also `$document` can be moved to the constructor to create a possibility to provide it via `di.xml` for extensibility purposes.

Moreover, it is OK to modify `\Magento\Framework\View\Element\UiComponent\DataProvider\Document` directly if needed.

2020-01-23 18:49 UTC, konarshankar07 commented
@novikor ... Thanks for the feedback. I'll try to find the universal solution for this issue

2020-01-24 10:09 UTC, novikor commented
@konarshankar07, - If we fail to find the universal solution, the current one is OK as well.
As far as I can see, similar problems for other grids are fixed this way.

Please let me know if you feel some trouble about that and would like to give up :)

2020-01-24 13:41 UTC, novikor commented
Hi, @konarshankar07 !
Well, I dug too deep and created my own PR: https://github.com/magento/magento2/pull/26523

It seems that I cannot review this PR anymore since I am an interested person.
I`ll request @swnsma 's review.

2020-01-27 09:14 UTC, novikor commented
Hi, @konarshankar07 . Please fix the static tests.

2020-01-27 09:18 UTC, konarshankar07 commented
Hello @novikor ,
Sorry for the delay. Sure, I'll fix the static test but did you find any universal solution for this issue?
Thanks

2020-01-27 09:27 UTC, lbajsarowicz requested changes
I've noticed few things to change

2020-01-27 09:27 UTC, lbajsarowicz commented on app/code/Magento/Sales/Ui/Component/DataProvider/Order/Document.php
> +    private static $customerGroupAttributeCode = 'customer_group';
Use `private const CUSTOMER_GROUP_ATTRIBUTE_CODE` instead.

2020-01-27 09:27 UTC, lbajsarowicz commented on app/code/Magento/Sales/Ui/Component/DataProvider/Order/Document.php
> +class Document extends \Magento\Framework\View\Element\UiComponent\DataProvider\Document
Import class with alias.

2020-01-31 10:29 UTC, novikor commented
> Hello @novikor ,
> Sorry for the delay. Sure, I'll fix the static test but did you find any universal solution for this issue?

Hi. Yes, - it is https://github.com/magento/magento2/pull/26523
So, I afraid current PR is not needed anymore if my one is approved.

2020-02-22 09:07 UTC, closed without merging