[Persistent] Cover CustomerData by Unit Test
magento/magento2 pull request #26043
Opened 2019-12-14 13:13 UTC by edenduong

### Description (*)

**Increase Test Coverage**

Cover class: `Magento\Persistent\CustomerData\Persistent`

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

vendor/bin/phpunit app/code/Magento/Persistent/Test/Unit/CustomerData/PersistentTest.php

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-14 14:37 UTC, kalpmehta approved these changes

2019-12-14 14:39 UTC, magento-engcom-team commented
Hi @kalpmehta, thank you for the review.
[ENGCOM-6469](https://jira.corp.magento.com/browse/ENGCOM-6469) has been created to process this Pull Request

2019-12-14 20:04 UTC, lbajsarowicz commented on app/code/Magento/Persistent/Test/Unit/CustomerData/PersistentTest.php
> +        $persistentSessionMock->method('getCustomerId')->willReturn(1);
You should not use magic numbers - that should be private const with a meaningful name - like `STUB_CUSTOMER_ID`

2019-12-14 20:05 UTC, lbajsarowicz commented on app/code/Magento/Persistent/Test/Unit/CustomerData/PersistentTest.php
> +        $this->customerRepositoryMock->method('getById')->with(1)->willReturn($customerMock);
Here you should refer to previously mentioned private const.

2019-12-14 20:09 UTC, lbajsarowicz requested changes

2019-12-14 20:09 UTC, lbajsarowicz commented on app/code/Magento/Persistent/Test/Unit/CustomerData/PersistentTest.php
> +        $this->customerViewHelperMock->method('getCustomerName')->with($customerMock)->willReturn('Adam John');
`Adam John` is another example of magic literal. You should replace that with STUB_CUSTOMER_NAME

2019-12-14 20:09 UTC, lbajsarowicz commented on app/code/Magento/Persistent/Test/Unit/CustomerData/PersistentTest.php
> +     * @var CustomerRepositoryInterface|\PHPUnit_Framework_MockObject_MockObject
Use alias `\PHPUnit_Framework_MockObject_MockObject` as `MockObject`

2019-12-14 20:09 UTC, lbajsarowicz commented on app/code/Magento/Persistent/Test/Unit/CustomerData/PersistentTest.php
> +    public function testGetSectionDataWithNotLogin()
In my personal opinion - the name of test should be more explicit - Optionally use pattern `given / when / then`. `testGetSectionDataWhenCustomerNotLoggedInReturnsEmptyArray`

2019-12-14 22:47 UTC, edenduong commented
Hi @lbajsarowicz: Thank you. I have changed the source code. Please check it.

2019-12-14 23:14 UTC, lbajsarowicz requested changes
Great improvement. One last thing and I'd love to approve such PR.

2019-12-14 23:14 UTC, lbajsarowicz commented on app/code/Magento/Persistent/Test/Unit/CustomerData/PersistentTest.php
> +        $this->customerRepositoryMock->method('getById')->with(1)->willReturn($customerMock);
You've left this unchanged. Replace `1` with `self::STUB_CUSTOMER_ID`

2019-12-14 23:35 UTC, edenduong commented
Hi @lbajsarowicz: Thank you. It should be ok now :)

2019-12-14 23:36 UTC, lbajsarowicz approved these changes
Thank you for your contribution :+1:

2019-12-14 23:37 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6469](https://jira.corp.magento.com/browse/ENGCOM-6469) has been created to process this Pull Request

2019-12-17 10:10 UTC, engcom-Charlie commented
:heavy_check_mark: QA Passed

2019-12-18 02:50 UTC, merged