26064 issuefix
magento/magento2 pull request #26066
Opened 2019-12-16 15:22 UTC by divyajyothi5321

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#26064: Incorrect Error Message While Sharing Wish list more than Specified Email Address Value in Admin Configuration

### Manual testing scenarios (*)

1. Go to frontend and login as Cutomer.
2. Add any product to wish list.
3. Go to My account dashboard -> My Wish list
4. Enter around 20 to 30 email addresses and share wish list.
5. The issue is fixed with this code. Please refer the screenshot.

![wishlist-expected](https://user-images.githubusercontent.com/54176640/70918762-9d2c9b80-2045-11ea-9fed-dac10e147ace.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-17 09:38 UTC, divyajyothi5321 commented
@engcom-Bravo the static check is always failing at the part of the code which we haven't touched, please let us know what action we need to take here.

2019-12-17 10:39 UTC, krzksz requested changes
Hello @divyajyothi5321, thank you for your contribution! Can you please adjust the rest of the code so that static tests pass?

2019-12-17 11:18 UTC, divyajyothi5321 commented
@krzksz I have made text change for the message and it is properly formatted. Can you Please let me know the exact place where I need to make the change to pass the static test.

2019-12-17 19:05 UTC, krzksz requested changes
Static tests ask you to remove `@package Magento\Wishlist\Controller\Index` and add some meaningful description to the class.

2019-12-17 19:05 UTC, krzksz commented on app/code/Magento/Wishlist/Controller/Index/Send.php
> +                    $error = __('Maximum of %1 Emails can be Sent.', $emailsLeft);
Please adjust the wording to `Maximum of %1 emails can be sent.` (letter casing).

2019-12-18 09:24 UTC, divyajyothi5321 commented
@krzksz even after changing the file as per your suggestion, the static test failed once again. could you please review and let us know the fix.

2019-12-18 09:40 UTC, krzksz requested changes
There is one error displayed:
```
PHPStan detected violation(s):
 ------ -------------------------------------------------------------------- 
  Line   app/code/Magento/Wishlist/Controller/Index/Send.php                 
 ------ -------------------------------------------------------------------- 
  325    Method Magento\Wishlist\Controller\Index\Send::getRssLink() should  
         return mixed but return statement is missing.                       
 ------ -------------------------------------------------------------------- 

 [ERROR] Found 1 error 
```
FYI: you can check the error yourself by clicking the **Details** link next to the certain test.

2019-12-23 07:39 UTC, krzksz requested changes

2019-12-23 07:39 UTC, krzksz commented on app/code/Magento/Wishlist/Controller/Index/Send.php
> +                    $error = __('Maximum of %1 Emails can be Sent.', $emailsLeft);
This still should be adjusted.

2019-12-23 10:09 UTC, krzksz approved these changes

2019-12-23 10:10 UTC, krzksz commented
Hey @divyajyothi5321, thank you for the contribution!
According to our Definition of Done, all code changes should be covered by tests.

2019-12-23 10:10 UTC, magento-engcom-team commented
Hi @krzksz, thank you for the review.
[ENGCOM-6518](https://jira.corp.magento.com/browse/ENGCOM-6518) has been created to process this Pull Request

2019-12-24 11:06 UTC, divyajyothi5321 commented
@krzksz how to cover auto testing kindly can you please let me know

2020-01-02 09:37 UTC, engcom-Golf commented
HI @divyajyothi5321 @krzksz all changes covered by unit test, could you please review ?

2020-01-02 10:19 UTC, krzksz approved these changes

2020-01-02 10:20 UTC, magento-engcom-team commented
Hi @krzksz, thank you for the review.
[ENGCOM-6518](https://jira.corp.magento.com/browse/ENGCOM-6518) has been created to process this Pull Request

2020-01-02 11:03 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-01-02 12:40 UTC, engcom-Golf commented
Functional test fails on 2.4-develop branch, fix in -> https://github.com/magento/magento2/pull/26225

2020-01-03 16:22 UTC, merged