Backup missing pub/static.php file #13298
magento/magento2 pull request #26088
Opened 2019-12-18 09:02 UTC by ivan-koliadynskyy

### Description (*)
Filtering files for making backup code bundle implemented with `FilterIterator` in `\Magento\Framework\Backup\Filesystem\Iterator\Filter`. This filter define which files should be skipped, comparing paths with using `strpos`,  `\Magento\Framework\Backup\Filesystem\Iterator\Filter:53`. There is rule to skip `pub/static` folder and in this case `pub/static.php` was skipped too.
According to this update filter will skip files/folders when path is completely the same or if path defined in filtering rule is parent folder.

### Fixed Issues (if relevant)

1. magento/magento2#13298: Backup missing pub/static.php file

### Manual testing scenarios (*)

1. Run CLI command `bin/magento setup:backup --code`
2. Check compressed file generated in `var/backups`
3. File should contain `pub/static.php`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-03 19:56 UTC, ihor-sviziev commented
@magento run all tests

2020-09-18 09:03 UTC, ihor-sviziev requested changes
Hi @ivan-koliadynskyy,

In general you changes looks good to me.
Could you review and my comments and cover your changes with some kind of automated tests?

2020-09-18 09:03 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Backup/Filesystem/Iterator/Filter.php
> +    protected $filters;
Please revert this change as it's not backward compatible. More info https://devdocs.magento.com/contributor-guide/backward-compatible-development/

2020-09-18 09:03 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Setup/BackupRollback.php
>       */
Could you just delete this phpdoc block at all? it's not adding any value.

2020-09-18 09:04 UTC, ihor-sviziev commented
Please also notice that this functionality is deprecated: https://docs.magento.com/user-guide/system/backups.html

2020-10-02 06:28 UTC, ihor-sviziev commented
Hi @ivan-koliadynskyy,
Will you be able to update your PR with requested changes?

2020-10-02 18:51 UTC, sidolov commented
@ivan-koliadynskyy  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-10-02 18:51 UTC, closed without merging