Fixed Issue with tier price 0 when saving product second time
magento/magento2 pull request #26162
Opened 2019-12-23 09:06 UTC by ravi-chandra3197

### Description (*)

Fixed Issue with tier price 0 when saving product second time
### Fixed Issues (if relevant)

1. magento/magento2#25195: Issue with tier price 0 when saving product second time #25195

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-12-23 11:20 UTC, rogyar requested changes
Hi, @ravi-chandra3197. Please, cover your change by an automated test. It's a required step for further PR processing. I would suggest adjusting the [existing unit test](https://github.com/magento/magento2/blob/f2bfadee7b32e72800025f3f74e5ee7b97e7f6db/app/code/Magento/Catalog/Test/Unit/Model/Attribute/Backend/TierPrice/UpdateHandlerTest.php#L22) for this purpose. 

Thank you.

2020-01-07 07:36 UTC, ravi-chandra3197 commented
> Hi, @ravi-chandra3197. Please, cover your change by an automated test. It's a required step for further PR processing. I would suggest adjusting the [existing unit test](https://github.com/magento/magento2/blob/f2bfadee7b32e72800025f3f74e5ee7b97e7f6db/app/code/Magento/Catalog/Test/Unit/Model/Attribute/Backend/TierPrice/UpdateHandlerTest.php#L22) for this purpose.
> 
> Thank you.

Hello @rogyar 
I have added an automated test in the existing unit test.
can review it.

2020-01-07 08:38 UTC, rogyar commented
Hi @ravi-chandra3197.

Thank you for the update. Let me help you with this one a little bit. Asserting the `null` value in the unit tests does not cover the case we are trying to fix here. In order to check our change works as expected, we need to pass an empty array element in the `$update` array upon invoking the [updateValues](https://github.com/magento/magento2/blob/fa416396e8fa14426077bc0de5150d1ca8d9fc45/app/code/Magento/Catalog/Model/Product/Attribute/Backend/TierPrice/UpdateHandler.php#L110) method. After that, we need to make sure that [updateValues](https://github.com/magento/magento2/blob/fa416396e8fa14426077bc0de5150d1ca8d9fc45/app/code/Magento/Catalog/Model/Product/Attribute/Backend/TierPrice/UpdateHandler.php#L128) method returns `true`.
The second assertion should check that we have `false` as a result of [updateValues](https://github.com/magento/magento2/blob/fa416396e8fa14426077bc0de5150d1ca8d9fc45/app/code/Magento/Catalog/Model/Product/Attribute/Backend/TierPrice/UpdateHandler.php#L128) method in case if we are passing `null` as an element of `$valuesToUpdate` parameter.

2020-01-20 09:36 UTC, engcom-Echo commented
I will take care of fix static tests.

2020-01-20 12:25 UTC, Nazar65 commented
@magento run unit tests

2020-01-21 10:00 UTC, engcom-Echo commented
Hi, @rogyar, please review the changes.

2020-01-22 14:02 UTC, rogyar approved these changes

2020-01-22 14:03 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-6647](https://jira.corp.magento.com/browse/ENGCOM-6647) has been created to process this Pull Request

2020-01-23 09:26 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-02-09 16:51 UTC, merged