[Correct oth Menu spacing issue]
magento/magento2 pull request #26238
Opened 2020-01-02 11:37 UTC by hitesh-wagento

### Description (*)
Fixed both Menu spacing issues in the mobile view.

### Fixed Issues (if relevant)

1. magento/magento2#26235: Both Menu spacing should be same

### Manual testing scenarios (*)

1. Go to the mobile view
2. Click on Humber menu

### Expected result

1. Both Menu spacing should be the same
![expected](https://user-images.githubusercontent.com/23443991/71662962-69f24800-2d79-11ea-95dd-8d0f380490d6.jpg)

### Actual result

1. Both Menu spacing different
![actual](https://user-images.githubusercontent.com/23443991/71662964-69f24800-2d79-11ea-8d48-323a46e30cea.jpg)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2020-01-03 03:43 UTC, hitesh-wagento commented
@dmytro-ch 

Can you please guide me how can I resolve Functional Tests error.

Thanks

2020-01-03 06:43 UTC, dmytro-ch commented
Hi @hitesh-wagento,
the functional test error is not relevant to your changes. Please just merge the latest `2.4-develop` and it will solve the problem.
Thank you!

2020-01-03 08:08 UTC, hitesh-wagento commented
Hi @dmytro-ch

Thank you for the reply I have merged 2.4-develop in my branch

Thanks

2020-01-08 11:09 UTC, ptylek commented on app/design/frontend/Magento/blank/web/css/source/_navigation.less
> +                    padding: .8rem 15px;
Please use @submenu__padding-left variable.

2020-01-08 11:09 UTC, ptylek commented on app/design/frontend/Magento/blank/web/css/source/_navigation.less
> +                padding: .8rem 15px;
Please use @submenu__padding-left variable.

2020-01-08 11:10 UTC, ptylek requested changes
Changes requested.

@submenu__padding-left variable has value of 15px and can be found in lib/web/css/source/lib/variables/_navigation.less

2020-01-10 06:50 UTC, hitesh-wagento commented
Hi @ptylek 

I have done changes as per your requirement

Thanks

2020-01-10 08:45 UTC, ptylek requested changes
Hey, @submenu__padding-left is equal to 15px therefore this line and another one should appear as:
`padding: .8rem @submenu__padding-left;`

2020-01-10 09:09 UTC, hitesh-wagento commented
Hi @ptylek 

Sorry for the mistake I have again changed and push my changes

Thanks

2020-01-10 09:15 UTC, ptylek approved these changes
Thanks for your contribution!

2020-01-10 09:16 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-6579](https://jira.corp.magento.com/browse/ENGCOM-6579) has been created to process this Pull Request

2020-01-10 09:55 UTC, dmytro-ch approved these changes

2020-01-10 09:56 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6579](https://jira.corp.magento.com/browse/ENGCOM-6579) has been created to process this Pull Request

2020-01-13 08:09 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-01-17 18:13 UTC, merged