Activated "Pending Reviews" menu item when merchant opens 'Pending Reviews' section
magento/magento2 pull request #26230
Opened 2020-01-02 08:16 UTC by rav-redchamps

### Description (*)

This pull request will activate the "Pending Reviews" menu item when merchant opens admin path 'Marketing > User Content > Pending Reviews'
### Fixed Issues (if relevant)

1. magento/magento2#26229 >: Active menu is not set when opening admin path Marketing > User Content > Pending Reviews

### Manual testing scenarios (*)

1. Go to admin path 'Marketing > User Content > Pending Reviews' & notice that 'Marketing' menu item is now shown as active

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-02 08:22 UTC, rav-redchamps commented
@magento give me test instance

2020-01-02 08:22 UTC, magento-engcom-team commented
Hi @rav-redchamps. Thank you for your request. I'm working on Magento instance for you

2020-01-02 08:23 UTC, magento-engcom-team commented
Hi @rav-redchamps, here is your [new Magento instance](https://pr-26230.instances.magento-community.engineering).
Admin access: [https://pr-26230.instances.magento-community.engineering/admin](https://pr-26230.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2020-01-02 08:25 UTC, rav-redchamps commented
Verified on the test instance. Change works well

2020-01-02 19:31 UTC, dmytro-ch requested changes
Hello @rav-redchamps, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
I think the functional test is preferable in this particular case.
Thank you!

2020-01-06 09:32 UTC, rav-redchamps commented
> Hello @rav-redchamps, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
> I think the functional test is preferable in this particular case.
> Thank you!

I just added the function test. Please feel free to let me know if anything else is required.

2020-01-29 10:32 UTC, engcom-Echo commented
@magento run all tests

2020-02-03 10:57 UTC, dmytro-ch reviewed
Hi @rav-redchamps. Sorry for the late reply and thank you for your patience.
Could you please add at least one assertion to your test which covers the issue fixed in this PR. Currently it does not actually verify whether the menu item is active or not.
Thank you!

2020-02-03 10:57 UTC, dmytro-ch commented on app/code/Magento/Review/Test/Mftf/Test/AdminMarketingPendingReviewsNavigateMenuTest.xml
> +            <testCaseId value="MC-14200"/>
Is this internal ticket id relevant to this test?

2020-02-19 09:24 UTC, engcom-Echo commented
I will take to fix MFTF

2020-02-19 16:31 UTC, dmytro-ch commented
@engcom-Echo, great, thank you! :)

2020-02-19 19:32 UTC, dmytro-ch approved these changes

2020-02-19 19:34 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6938](https://jira.corp.magento.com/browse/ENGCOM-6938) has been created to process this Pull Request

2020-02-20 12:46 UTC, dmytro-ch submitted a review, later dismissed

2020-02-20 12:47 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6938](https://jira.corp.magento.com/browse/ENGCOM-6938) has been created to process this Pull Request

2020-02-20 12:50 UTC, dmytro-ch submitted a review, later dismissed

2020-02-20 12:51 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6938](https://jira.corp.magento.com/browse/ENGCOM-6938) has been created to process this Pull Request

2020-02-20 12:54 UTC, dmytro-ch approved these changes

2020-02-20 12:55 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6938](https://jira.corp.magento.com/browse/ENGCOM-6938) has been created to process this Pull Request

2020-02-24 09:26 UTC, dmytro-ch approved these changes

2020-02-24 09:27 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6938](https://jira.corp.magento.com/browse/ENGCOM-6938) has been created to process this Pull Request

2020-02-24 11:05 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-02-25 08:42 UTC, dmytro-ch approved these changes

2020-02-25 08:43 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6938](https://jira.corp.magento.com/browse/ENGCOM-6938) has been created to process this Pull Request

2020-02-26 21:08 UTC, merged