Product grid has quantity in decimals
magento/magento2 pull request #26362
Opened 2020-01-12 19:57 UTC by gauravagarwal1001

### Preconditions (*)

1. Magento 2.3.3, 2.4-develop

### Steps to reproduce (*)

1. Install
2. Add product
3. Go to products grid

### Expected result (*)

Don't know about you, but we don't sell goods in fractions.

Show product quantity without decimals.

### Actual result (*)

Product quantity with decimals.

![image](https://user-images.githubusercontent.com/1741593/71955802-9a0e7080-31e9-11ea-8362-2f70c7b0789f.png)

2020-01-12 19:57 UTC, gauravagarwal1001 commented
@magento give me test instance

2020-01-12 19:57 UTC, magento-engcom-team commented
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento instance for you

2020-01-12 19:58 UTC, magento-engcom-team commented
Hi @gauravagarwal1001, here is your [new Magento instance](https://pr-26362.instances.magento-community.engineering).
Admin access: [https://pr-26362.instances.magento-community.engineering/admin](https://pr-26362.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2020-01-12 20:00 UTC, gauravagarwal1001 commented
@magento give me 2.4-develop instance

2020-01-12 20:00 UTC, magento-engcom-team commented
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento 2.4-develop instance for you

2020-01-12 20:01 UTC, magento-engcom-team commented
Hi @gauravagarwal1001, here is your [Magento instance](https://i-26362-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26362-2-4-develop.instances.magento-community.engineering/admin](https://i-26362-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

2020-01-12 20:06 UTC, gauravagarwal1001 commented
> https://pr-26362.instances.magento-community.engineering/admin

<img width="1418" alt="Screenshot 2020-01-13 at 1 35 06 AM" src="https://user-images.githubusercontent.com/37572719/72224872-136ce100-35a5-11ea-8d21-50d0164c7b36.png">

2020-01-13 08:55 UTC, rogyar commented
@magento give me test instance

2020-01-13 08:55 UTC, magento-engcom-team commented
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

2020-01-13 08:56 UTC, magento-engcom-team commented
Hi @rogyar, here is your [new Magento instance](https://pr-26362.instances.magento-community.engineering).
Admin access: [https://pr-26362.instances.magento-community.engineering/admin](https://pr-26362.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

2020-01-13 09:03 UTC, rogyar requested changes
Hi @gauravagarwal1001. Thank you for your collaboration. Please, take a look at the failing functional tests. It looks like that some assertions are waiting for the old QTY format. 

Thank you

2020-01-13 11:17 UTC, gauravagarwal1001 commented
> Hi @gauravagarwal1001. Thank you for your collaboration. Please, take a look at the failing functional tests. It looks like that some assertions are waiting for the old QTY format.
> 
> Thank you

Ok, I will check and update.

2020-02-11 22:10 UTC, slavvka commented
@gauravagarwal1001 Thank you for your efforts but this solution isn't correct since you change DB Schema. This issue must be solve at presentation layer depending on the setting if quantities should be whole numbers, Please feel free to create a new PR with a correct solution.

2020-02-11 22:10 UTC, closed without merging

2020-02-14 06:38 UTC, gauravagarwal1001 commented
@slavvka Thanks for suggestion I will create new pr for this issue..