feat(framework): pull HeaderManager beforeSendResponse to back to HttpInterface
magento/magento2 pull request #26405
Opened 2020-01-15 16:21 UTC by damienwebdev

### Description (*)
The HeaderManager depends on a concrete type for its sendResponse method, this causes the `WebapiResponse` not to be interceptable with the HeaderManager. Both the `Magento\Framework\Webapi\Rest\Response` and the `Magento\Framework\App\Response\Http` implement the `\Magento\Framework\App\Response\HttpInterface` and the dependent methods of the `HeaderManager` only depend on `setHeader`  (defined in the interface) so there should be no need for the concrete typing.

This allows further plugin configuration like:

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
<type name="Magento\Framework\Webapi\Rest\Response">
        <plugin name="genericHeaderPlugin" type="Magento\Framework\App\Response\HeaderManager"/>
    </type>
</xml>
```

### Questions or comments
I don't know why the interface is strict, it may be by intention. If it isn't, this shouldn't be a breaking change. No framework code depends on the concretion, but it is possible that an extension is improperly depending on the concrete class.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-15 22:28 UTC, ishakhsuvarov commented
@magento give me test instance

2020-01-15 22:28 UTC, magento-engcom-team commented
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento instance for you

2020-01-15 22:29 UTC, magento-engcom-team commented
Hi @ishakhsuvarov, here is your [new Magento instance](https://pr-26405.instances.magento-community.engineering).
Admin access: [https://pr-26405.instances.magento-community.engineering/admin_dc0e](https://pr-26405.instances.magento-community.engineering/admin_dc0e)
Login: `623f2759` Password: `f1c254fa1381`
Instance will be terminated in up to 3 hours.

2020-02-06 18:39 UTC, damienwebdev commented
@ishakhsuvarov @buskamuza 

Can I get a review on this? I'm fairly certain the failing tests have nothing to do with this code.

2020-08-17 19:22 UTC, sidolov commented
@magento create issue

2020-08-19 06:05 UTC, ihor-sviziev requested changes
Hi @damienwebdev,
Your changes looks good to me. Could you fix failing static tests?

2020-08-19 06:14 UTC, ihor-sviziev requested changes
Hi @damienwebdev,
Your changes looks good to me. Could you fix failing static tests?

2020-08-20 14:28 UTC, ihor-sviziev commented
@magento run Static Tests

2020-08-20 16:51 UTC, ihor-sviziev commented
@magento run all tests

2020-08-21 09:22 UTC, ihor-sviziev requested changes
Hi @damienwebdev,
Will you be able to cover your changes with unit tests?

2020-08-27 09:06 UTC, gabrieldagama requested changes
Hi @damienwebdev @ihor-sviziev 

Adding the `Magento\Framework\App\Response\HttpInterface` as the subject of this plugin doesn't sound correct, the interface doesn't have the `sendResponse()` method declared on it, the plugin declaration is specific to the `Magento\Framework\App\Response\Http` class that has that method. 

If this was a normal class, that would make sense, but because it is a plugin, the fact that the subject doesn't necessarily have the method used on the plugin is ambiguous.

What do you guys think? Thanks.

2020-08-27 12:10 UTC, ihor-sviziev commented
@gabrieldagama make sense!

2020-08-31 11:49 UTC, damienwebdev commented
@ihor-sviziev yes this PR can be closed. But, this discussion leads me to thinking another interface is in order.

2020-08-31 11:49 UTC, closed without merging