#895 Fix for Media Gallery buttons are shifted to the left
magento/magento2 pull request #26413
Opened 2020-01-16 05:48 UTC by diazwatson

### Description (*)

### Fixed Issues (if relevant)

1. https://github.com/magento/adobe-stock-integration/issues/895: [Bug] Media Gallery buttons are shifted to the left

### Manual testing scenarios (*)

1. Login to Admin Panel
2. Open Media Gallery (i.e. Catalog -> Category -> Content -> Select From Media Gallery button)

### Expected result (*)
Media gallery buttons should be aligned to the right

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-16 14:36 UTC, sivaschenko requested changes
Thanks for the pull request @diazwatson ! I think that the styles should be updated in the `app/design/adminhtml/Magento/backend/Magento_Cms/web/css/source/_module.less` (where all exiting media gallery styles are defined) for consistency.

The Media Gallery module is rather a backend module for working with media files that will be used for the NEW media gallery and this particular fix is for the old media gallery.

2020-01-17 22:37 UTC, diazwatson commented
Thanks for the explanation @sivaschenko 👍

2020-01-22 22:00 UTC, sivaschenko approved these changes

2020-01-22 22:01 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-6664](https://jira.corp.magento.com/browse/ENGCOM-6664) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-01-23 09:35 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-01-23 12:37 UTC, engcom-Foxtrot commented
@magento run Static Tests build

2020-02-09 16:51 UTC, merged