issue fixed 26106
magento/magento2 pull request #26448
Opened 2020-01-18 09:10 UTC by sachinguptartpl

### Description (*)

Downloadable Product should be OUT OF STOCK if there are no links just samples saved issue fixed
### Fixed Issues (if relevant)

1. magento/magento2#<26106>: Downloadable Product should be OUT OF STOCK if there are no links just samples saved

### Manual testing scenarios (*)

1. Add sample links only for downloadable product and check the result of graphql 
2. Add original link and sample link also for downloadable product and check the result of graphql 
3. Confirm the result of the GraphQl

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-18 15:38 UTC, lbajsarowicz requested changes
Please find comments attached.

2020-01-18 15:38 UTC, lbajsarowicz commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/StockStatusProvider.php
> +            && $stockStatusByProductType === StockStatusInterface::STATUS_IN_STOCK
Extract to private method `isDownloadableProductInStock` (add also line 50)

2020-01-18 15:38 UTC, lbajsarowicz commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/StockStatusProvider.php
> -        return $productStockStatus === StockStatusInterface::STATUS_IN_STOCK ? 'IN_STOCK' : 'OUT_OF_STOCK';
You removed that line, but there's no value for it when product is not downloadable. So the `return` statement will be always false.

2020-01-21 14:57 UTC, lenaorobei requested changes
This issue should be fixed on the different layer, other than resolver. Please have a look at `getStockStatus`. Need to debug and understand, why it does not return correct information (does not take `saleable` into account).

2020-02-10 16:01 UTC, lenaorobei commented
@sachinguptartpl, closing this PR due to inactivity. Please feel free to reopen if you are up to finishing it.

2020-02-10 16:01 UTC, closed without merging