fixed issue #26288
magento/magento2 pull request #26440
Opened 2020-01-18 06:39 UTC by shubhamkhandelwalrtpl

### Description (*)

missing Throw in copy pasted code is fixed 
### Fixed Issues (if relevant)

1. magento/magento2#<26288>: missing Throw in copy pasted code 

### Manual testing scenarios (*)

There are no testing scenario. 

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-18 14:31 UTC, rogyar commented
Hi @shubhamkhandelwalrtpl. Thank you for your collaboration. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. Could I kindly ask you to cover your fix wit a simple unit test, please? 

Thank you.

2020-01-25 00:52 UTC, lbajsarowicz requested changes
Could you also change `return $found->getItems()[0]` with more reliable replacement like `return current($found->getItems())`? This is more independent from array keys.

2020-01-25 00:52 UTC, lbajsarowicz commented on app/code/Magento/Customer/Model/ForgotPasswordToken/GetCustomerByToken.php
>              //Customer with such token not found.
Actually, you can remove the comments. Code is self-explanatory.

2020-01-25 00:52 UTC, lbajsarowicz commented on app/code/Magento/Customer/Model/ForgotPasswordToken/GetCustomerByToken.php
>                  new Phrase(
You can replace new Phrase with `__(...)`

2020-01-30 09:28 UTC, engcom-Charlie commented
Hi @shubhamkhandelwalrtpl, please sign CLA.

2020-01-30 12:49 UTC, lbajsarowicz approved these changes
Looks OK :-) 
Just minor improvement for readability.

2020-01-30 12:49 UTC, lbajsarowicz commented on app/code/Magento/Customer/Model/ForgotPasswordToken/GetCustomerByToken.php
> +            throw new NoSuchEntityException(__('No such entity with rp_token = %1', $resetPasswordToken));
You can use placeholders in such situaltions:
```php
throw new NoSuchEntityException(
    __('No such entity with rp_token = %token', ['token' => $resetPasswordToken])
);
```

2020-01-30 12:51 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6769](https://jira.corp.magento.com/browse/ENGCOM-6769) has been created to process this Pull Request

2020-01-30 14:56 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

The test is added and passes
![forg_pass_token1](https://user-images.githubusercontent.com/51680745/73460569-61ddf600-4381-11ea-9515-dbdb8cf4091a.png)

2020-01-31 09:28 UTC, lbajsarowicz requested changes
Sign license, please.

2020-02-04 10:17 UTC, rogyar approved these changes

2020-02-04 10:18 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-6769](https://jira.corp.magento.com/browse/ENGCOM-6769) has been created to process this Pull Request

2020-02-04 11:44 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

2020-02-06 08:00 UTC, engcom-Golf commented
HI @shubhamkhandelwalrtpl we cannot process this PR unit you not signed CLA.

2020-03-09 18:44 UTC, lenaorobei commented
Closing this PR since CLA is not signed.
@shubhamkhandelwalrtpl please feel free to reopen if you are going to finish this PR. Thanks.

2020-03-09 18:44 UTC, closed without merging