Fixes showing attributes that don't apply
magento/magento2 pull request #26459
Opened 2020-01-20 12:49 UTC by NetStorm84

### Description (*)
This PR adds a fix for showing attributes that don't apply to the product by checking if the current product type exists in the apply_to array of th attribute

### Fixed Issues (if relevant)
1. magento/magento2 #26458:showing incorrect attributes on frontend

### Manual testing scenarios (*)
1. Create an attribute using code
2. Enter configurable in the 'apply_to' key
3. Enter \Magento\Eav\Model\Entity\Attribute\Source\Boolean::class in the source key
4. Visit a simple product on the front end
5. This attribute should not be listed under Specifications
6. Visit a configurable product on the front end
7. This attribute should be visible on the front end

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-24 20:04 UTC, NetStorm84 commented
Can anyone help me understand why the tests are failing?

2020-01-25 00:32 UTC, lbajsarowicz requested changes
Improve readability of this condition.

2020-01-25 00:32 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Block/Product/View/Attributes.php
> +            (!empty($attribute->getApplyTo()) && in_array($this->getProduct()->getTypeId(), $attribute->getApplyTo())));
This gets too messy, extract these conditions to separate private method explaining what it actually does - for example:
`$attribute->isVisibleOnFront() && !$this->isAttributeExcluded($attribute) && $this->isAttributeVisibleForProduct($attribute, $this->getProduct())`

2020-01-25 00:32 UTC, lbajsarowicz commented
According to Definition of Done - could you provide Integration or Functional tests to cover the change?

2020-01-27 10:57 UTC, lbajsarowicz requested changes
I think that last change to be done : )

2020-01-27 10:57 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Block/Product/View/Attributes.php
> +        \Magento\Eav\Model\Entity\Attribute\AbstractAttribute $attribute
Import class :  )

2020-01-27 10:59 UTC, NetStorm84 commented on app/code/Magento/Catalog/Block/Product/View/Attributes.php
> +        \Magento\Eav\Model\Entity\Attribute\AbstractAttribute $attribute
Sorry, I am not sure what you mean?

2020-01-29 21:27 UTC, closed without merging