Fixed Issue 26389
magento/magento2 pull request #26450
Opened 2020-01-18 09:26 UTC by imrandotftr

### Description (*)

Watermark is breaking product page when size is not set the issue fixed
### Fixed Issues (if relevant)

1. magento/magento2#<26389>: Watermark is breaking product page when size is not set

### Manual testing scenarios (*)

1.     Navigate to theme configuration in Content -> Design -> Configuration -> <some theme> -> Product Image Watermarks
2.     Upload a new watermark. Specify opacity and DO NOT specify Image size

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-18 15:21 UTC, lbajsarowicz commented
@imrandotftr Please accept the CLA and fix Static tests:
```
PHP Code Sniffer detected 2 violation(s): 

FILE: ...l/app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 10 WARNINGS AFFECTING 8 LINES
----------------------------------------------------------------------
 134 | WARNING | [x] Multi-line function call not indented correctly;
     |         |     expected 16 spaces but found 20
 135 | WARNING | [x] Multi-line function call not indented correctly;
     |         |     expected 16 spaces but found 20
 136 | WARNING | [x] Multi-line function call not indented correctly;
     |         |     expected 16 spaces but found 20
 137 | WARNING | [x] Multi-line function call not indented correctly;
     |         |     expected 12 spaces but found 16
 139 | WARNING | [ ] Expected "if (...) {\n"; found "if(...){\n"
 139 | WARNING | [x] Expected 1 space(s) after IF keyword; 0 found
 139 | WARNING | [x] Expected 1 space(s) after closing parenthesis;
     |         |     found 0
 141 | WARNING | [x] Multi-line function call not indented correctly;
     |         |     expected 20 spaces but found 28
 142 | WARNING | [x] Multi-line function call not indented correctly;
     |         |     expected 20 spaces but found 28
 147 | WARNING | [x] Multi-line function call not indented correctly;
     |         |     expected 16 spaces but found 24
----------------------------------------------------------------------
PHPCBF CAN FIX THE 9 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------



Failed asserting that 2 matches expected 0.
```

Don't worry about Functional Tests. Fix will be merged to `2.4-develop` soon for that issue.

2020-01-18 15:31 UTC, lbajsarowicz requested changes
Please find review comments.

2020-01-18 15:31 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php
> -                )
Extract to private method `getWatermarkSize(string $type): string`

2020-01-18 15:31 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php
> +                            )
You already fetched that value - why don't you use `$watermarkSize`?

2020-01-18 15:31 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php
> +                            'x',
Extract to `const` - `private const WATERMARK_SIZE_SEPARATOR`

2020-01-21 19:58 UTC, closed without merging

2020-01-21 19:58 UTC, magento-engcom-team commented
Hi @imrandotftr

Unfortunately, we cannot accept Pull Requests from branches created in `magento2` repository.
Please use your own fork as a base for this Pull Request.

Thank you.