Escape dollar sign for saving content into crontab
magento/magento2 pull request #26462
Opened 2020-01-20 14:15 UTC by Erfans

The crontab contents can contain dollar sign (e.g. $(date)).
The current code does not escape it which transform it to actual values.
In this commit a replacement to escape dollar sign is added to the previous replacements.

an example in crontab could be
`mysqldump db > db-$(date +%F).sql`

### Description (*)

Class `lib/internal/Magento/Framework/Crontab/CrontabManager.php` function `save` already replace couple of special characters '%' and '"'. I added a new entry into the replacement to escape dollar sign as well. i.e. convert `$` to `\$`.

### Manual testing scenarios (*)

1. Add a new entry to crontab with dollar sign, e.g: `mysqldump -uroot  DB >/home/backups/$(date +%F)_db.sql`
1. Run the cron install command in the magento root directory: `bin\magento cron:install`
1. check the content of the crontab. The  `$(date +%F)` is transformed to actual date string. `bin\magento cron:remove` has the same effect as well. 

This pull request should fix the conversion, i.e. after `bin\magento cron:install` the content of the other parts with dollar sign should stay intact. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-21 06:53 UTC, ihor-sviziev requested changes
Hi @Erfans,
Unfortunately steps to reproduce isn't clear how to test it. Could you explain 1st step more detailed?

In general your changes looks good.
Could you cover your changes with unit or integration test, so we'll not brake this functionality in future?

2020-01-24 15:14 UTC, Erfans commented
Hi @ihor-sviziev 

for reproducing step 1: 
1. Login to the machine that M2 is installed on it.
2. Manually modify the crontab (with the user of web server)
e.g.
`crontab -e -uwww-data`
3. insert a new line with a content that contains dollar sign ($)
e.g.
`0 0 * * * mysqldump db > db-$(date +%F).sql`
4. save the crontab
5. install the magento cron job `bin\magento cron:install`
6. check the crontab
`crontab -l -uwww-data`

the `$(date +%F) `  will be transformed to actual date string

for unit test perhaps I can add it in the next week.

2020-01-24 19:05 UTC, ihor-sviziev commented
@Erfans ok, so we’ll wait for test coverage

2020-01-29 08:08 UTC, engcom-Echo commented
I will take care of test coverage.

2020-01-29 10:40 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Crontab/Test/Unit/CrontabManagerTest.php
> +                    ['command' => '{magentoRoot}run.php % cron:run | grep -v "Ran \'jobs\' by schedule"$']
I think it would be better to make some more real case, for instance with `$(date)`

2020-01-29 18:46 UTC, ihor-sviziev approved these changes

2020-01-29 18:47 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6753](https://jira.corp.magento.com/browse/ENGCOM-6753) has been created to process this Pull Request

2020-01-29 18:47 UTC, magento-engcom-team commented
@Erfans thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-01-30 11:08 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-02-09 00:23 UTC, merged