Fixed grid multiselect issue #24400
magento/magento2 pull request #26488
Opened 2020-01-22 07:57 UTC by maheshWebkul721

Grid Multi-Select Column Issue Fixed in this PR

### Description (*)

Fixed issues related to multi-select column.
### Fixed Issues (if relevant)

1. #24400

### Manual testing scenarios (*)

1. All the steps verified that given in the issue #24400
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-23 14:03 UTC, novikor commented
@magento run Static Tests

2020-01-23 15:52 UTC, novikor requested changes
Hi, @maheshWebkul721 . Thank you for your contribution.
Please fix the static tests. 
Currently, build error is not available, however, I have the problem description:

```
Stacktrace
disallowTrailingWhitespace: Illegal trailing whitespace at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
   238 |            var total = this.getIds().length,
   239 |                selected = this.getPageSelections().length;
   240 |            
--------^
   241 |            if (this.isPageSelected() && selected !== total) {
   242 |                return this.selectPage();
```

2020-01-23 19:05 UTC, slavvka commented
Guys, thank you for the identification of the issue. We are working on fixing that.

2020-01-23 20:11 UTC, slavvka commented
Full issue log:
```
disallowTrailingWhitespace: Illegal trailing whitespace at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
   238 |            var total = this.getIds().length,
   239 |                selected = this.getPageSelections().length;
   240 |            
--------^
   241 |            if (this.isPageSelected() &amp;&amp; selected !== total) {
   242 |                return this.selectPage();</failure>
    <failure>requirePaddingNewlinesBeforeKeywords: Keyword `return` should have an empty line above it at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
   245 |            if (this.indetermine() &amp;&amp; selected === total) {
   246 |                return this.selectPage();
   247 |            }
---------------------^
   248 |            return this.isPageSelected() ? this.deselectPage() : this.selectPage();
   249 |        },</failure>
    <failure>disallowTrailingWhitespace: Illegal trailing whitespace at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
   461 |            this.allSelected(allSelected);
   462 |            this.indetermine(totalSelected &amp;&amp; !allSelected);
   463 |            
--------^
   464 |            return this;
   465 |        },
```

2020-01-24 09:01 UTC, novikor commented
Thank you for your collaboration!

чт, 23 янв. 2020 г. в 22:11, Slava Mankivski <notifications@github.com>:

> Full issue log:
>
> disallowTrailingWhitespace: Illegal trailing whitespace at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
>    238 |            var total = this.getIds().length,
>    239 |                selected = this.getPageSelections().length;
>    240 |
> --------^
>    241 |            if (this.isPageSelected() &amp;&amp; selected !== total) {
>    242 |                return this.selectPage();</failure>
>     <failure>requirePaddingNewlinesBeforeKeywords: Keyword `return` should have an empty line above it at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
>    245 |            if (this.indetermine() &amp;&amp; selected === total) {
>    246 |                return this.selectPage();
>    247 |            }
> ---------------------^
>    248 |            return this.isPageSelected() ? this.deselectPage() : this.selectPage();
>    249 |        },</failure>
>     <failure>disallowTrailingWhitespace: Illegal trailing whitespace at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
>    461 |            this.allSelected(allSelected);
>    462 |            this.indetermine(totalSelected &amp;&amp; !allSelected);
>    463 |
> --------^
>    464 |            return this;
>    465 |        },
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/26488?email_source=notifications&email_token=AGHAZILEPPIUVDUS7MV2NHDQ7H2XTA5CNFSM4KKBK362YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJYV4XY#issuecomment-577855071>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGHAZIPIYG6YRC66VMZF3MLQ7H2XTANCNFSM4KKBK36Q>
> .
>

2020-01-27 15:58 UTC, slavvka commented
hey @maheshWebkul721 @novikor We have fixed the issue with static tests https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/26488/a80d343adf054ec702e7edda682c8229/Statics/allure-report-b2b/index.html#suites/3a29d43e5c1686787ff8c2a77e590abb/678be20ee8bc32a5/

2020-02-02 05:06 UTC, shikhamis11 commented
Hi 
I have also provided solution for above issue in my pull request #26626 
Please have a look

2020-02-20 16:42 UTC, novikor submitted a review, later dismissed

2020-02-20 16:47 UTC, magento-engcom-team commented
Hi @novikor, thank you for the review.
[ENGCOM-6944](https://jira.corp.magento.com/browse/ENGCOM-6944) has been created to process this Pull Request
:eight_spoked_asterisk: @novikor, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-02-20 16:48 UTC, novikor commented
Hi, @maheshWebkul721 
Thank you for your contribution.
The PR changes are ready for approval, but tests coverage is required.
Don't you mind to cover the PR by MFTF?
@engcom-Golf

2020-02-24 09:48 UTC, engcom-Golf commented
I'll cover changes with jasmine test

2020-02-24 11:56 UTC, engcom-Golf commented
@novikor done :heavy_check_mark:

2020-02-24 13:54 UTC, novikor submitted a review, later dismissed
Fine!

2020-02-24 13:55 UTC, magento-engcom-team commented
Hi @novikor, thank you for the review.
[ENGCOM-6944](https://jira.corp.magento.com/browse/ENGCOM-6944) has been created to process this Pull Request

2020-02-25 09:11 UTC, engcom-Alfa reviewed
Hi @maheshWebkul721.

During testing, we faced some issues.

### Case 1

1. Open any grid with more than 1 page;
2. Now select some records, on click particular row;
3. Click on Header Checkbox to select all records on the current page;
4. Click on Header Checkbox again to unselect all records on the current page;

**Actual Result:** 
:heavy_multiplication_x: Now you will see that select or deselect action hasn't any reaction

![after1](https://user-images.githubusercontent.com/51679138/75231786-bfb60000-57be-11ea-9f20-5537cd77ae74.gif)

### Case 2

1. Select all records on the current page by clicking the header checkbox;
2. Go to the second page;

**Actual Result:** 
:heavy_multiplication_x: you will see that the header checkbox is selected on all remaining pages

![after2](https://user-images.githubusercontent.com/51679138/75232144-5f738e00-57bf-11ea-910c-7281ba7aeb9f.gif)

@maheshWebkul721 Could you take a look?

Thanks!

2020-02-25 09:14 UTC, engcom-Golf commented on app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js
> +            var total = this.getIds().length,
test

2020-02-25 09:56 UTC, novikor submitted a review, later dismissed

2020-02-25 09:57 UTC, magento-engcom-team commented
Hi @novikor, thank you for the review.
[ENGCOM-6944](https://jira.corp.magento.com/browse/ENGCOM-6944) has been created to process this Pull Request

2020-02-25 10:00 UTC, engcom-Golf submitted a review, later dismissed
Hi @novikor there actually a few issues regarding this changes, that why QA moved this to changes requested.
https://github.com/magento/magento2/pull/26488#pullrequestreview-363973290

2020-02-25 10:08 UTC, maheshWebkul721 commented
@engcom-Golf @novikor i am looking for the [#26488 (review)](https://github.com/magento/magento2/pull/26488#pullrequestreview-363973290) Solution.

2020-02-26 12:12 UTC, maheshWebkul721 commented
@Nazar65 i have updated the code to fix  [#26488 (review)](https://github.com/magento/magento2/pull/26488#pullrequestreview-363973290)

2020-02-26 13:52 UTC, Nazar65 requested changes

2020-02-26 13:52 UTC, Nazar65 commented on app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js
> +            this.allSelected(pageTotal === pageSelected);
There are a lot of jasmine test failures could you please take a look ? i think this may cause an issue

2020-02-28 13:12 UTC, maheshWebkul721 commented
@Nazar65  i have updated the code to fix unit tests.

2020-08-19 17:02 UTC, sidolov submitted a review, later dismissed

2020-08-19 17:03 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-6944](https://jira.corp.magento.com/browse/ENGCOM-6944) has been created to process this Pull Request

2020-08-20 09:02 UTC, engcom-Alfa commented
@magento give me test instance

2020-08-20 09:02 UTC, magento-engcom-team commented
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

2020-08-20 09:03 UTC, magento-engcom-team commented
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-26488.instances.magento-community.engineering).
Admin access: [https://pr-26488.instances.magento-community.engineering/admin_8e78](https://pr-26488.instances.magento-community.engineering/admin_8e78)
Login: `3ad7d9a1` Password: `c71d52aedf26`
Instance will be terminated in up to 3 hours.

2020-08-20 10:39 UTC, engcom-Alfa requested changes
Hi @maheshWebkul721 . 

During testing, we faced the issue.

**Manual testing scenario:**

1. Login to the backend;
2. Create 3 customers (first name, second name, third name);
![Screenshot from 2020-08-20 13-29-36](https://user-images.githubusercontent.com/51679138/90759539-386ac480-e2e9-11ea-8d99-2f70458e9496.png)

3. In the 'Search by keyword' box, enter 'first' and search;
4. In the first column, choose the 'Select All' option;
5. Notice that one record is selected:

![2020-08-20_13-31](https://user-images.githubusercontent.com/51679138/90759711-7bc53300-e2e9-11ea-9468-88d096b0f464.png)

6. Remove the 'first' keyword search by pressing the 'x' icon to the right of it.
7. Notice that it now says that one record is selected,

:heavy_multiplication_x: but visually all records have a checkmark:

![2020-08-20_13-33](https://user-images.githubusercontent.com/51679138/90759905-c777dc80-e2e9-11ea-8776-608ca5276b1a.png)

8. Select Actions => Delete;
9. Notice that it says it will remove 1 record:
![2020-08-20_13-36](https://user-images.githubusercontent.com/51679138/90760179-2a697380-e2ea-11ea-9596-d95982ac4b7a.png)

10. Press OK

**Actual Result:** :heavy_multiplication_x: All products have been removed instead of 1.

![2020-08-20_13-38](https://user-images.githubusercontent.com/51679138/90760359-6ac8f180-e2ea-11ea-9291-d8852b705739.png)

@maheshWebkul721 Could you take a look?

Thanks!

2020-09-07 06:48 UTC, engcom-Hotel commented
@magento run all tests

2020-09-07 15:54 UTC, engcom-Hotel commented
@magento run all tests

2020-09-08 10:21 UTC, gabrieldagama commented
@magento run all test

2020-09-08 10:31 UTC, sivaschenko commented
@magento run all test

2020-09-08 10:31 UTC, sivaschenko commented
@magento run all tests

2020-09-15 11:15 UTC, gabrieldagama commented
Hi @maheshWebkul721, thanks for your contribution. After looking at the issue and the possible solutions we've decided to proceed with this PR https://github.com/magento/magento2/pull/29968 that aims to fix the same issue. 

The approach that was chosen was to preserve the same behavior that we have with filters. So when a search tag is removed from filters the previous selection becomes invalid and it is dismissed. As result, we have the same behavior across multiple functionalities on the grid.

I will be closing this PR but feel free to reopen it anytime.

2020-09-15 11:15 UTC, closed without merging