Add bundle qty and selection qty for calculation tier price
magento/magento2 pull request #26491
Opened 2020-01-22 10:43 UTC by marcinlesko

### Description (*)
Selection qty was hardcoded and passed to `getSelectionFinalTotalPrice` also bundle qty was hardcoded to 0. It caused wrong data type passed in `getTierPrce` method.

### Fixed Issues (if relevant)

1. magento/magento2#22807: Bundles and tier price give unexpected results

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-20 15:57 UTC, sidolov requested changes
@marcinlesko could you please cover changes with automated test?

2020-08-26 07:23 UTC, engcom-Charlie commented
Hi @marcinlesko could you please look through failed WebAPI Tests and cover your changes by an automated test? Otherwise, we can't proceed with your PR.

2020-09-03 12:40 UTC, engcom-Charlie commented
Hi, @marcinlesko I"ll try to continue with your PR.

2020-09-08 07:35 UTC, engcom-Charlie commented
Hi @marcinlesko please look at https://github.com/magento/magento2/issues/22807#issuecomment-688311565, looks like issue doesn't exist anymore. Can you please confirm that?
Thank you.

2020-09-21 13:23 UTC, engcom-Charlie commented
Close because the issue described above was closed.

2020-09-21 13:23 UTC, closed without merging