Fixed issue #23841
magento/magento2 pull request #26494
Opened 2020-01-22 13:47 UTC by maheshWebkul721

Fixed issue #23841

### Description (*)

### Fixed Issues (if relevant)

1.  #23841

### Manual testing scenarios (*)

1. checked with all default eav attribtues.
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-22 19:50 UTC, Stepa4man requested changes
Hi @maheshWebkul721
Thanks for your contribution
Please check my comments and tests.

2020-01-22 19:50 UTC, Stepa4man commented on app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php
> +            if (!$defaultValue) {
Please optimize this code. Nested ifs are looking weird. Why don"t you check it in one if statement?

2020-05-06 07:09 UTC, Stepa4man requested changes
Hi @maheshWebkul721 
Thanks for your contribution

Please add to all changed files
```php
    declare(strict_types=1);
```
You can read more [here](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#1-basic-programming-principles)

2020-05-27 09:43 UTC, engcom-Echo commented
HI @maheshWebkul721 Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests.

2020-05-27 09:43 UTC, engcom-Echo commented
@magento run all tests

2020-06-04 07:32 UTC, engcom-Echo commented
Stepa4man, @maheshWebkul721, thank you for your collaboration. 

Please look [comment](https://github.com/magento/magento2/issues/23841#issuecomment-638648987).

2020-06-19 09:21 UTC, engcom-Echo commented
Hi @maheshWebkul721, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration

2020-06-19 09:21 UTC, closed without merging