Fixed Single Store Mode - Incorrect scope values using at Storefront for Catalog Section
magento/magento2 pull request #26508
Opened 2020-01-23 13:04 UTC by muthu-ziffity

### Description (*)

In category page, In single store mode Show per page section doesn't get the value from admin properly. Now it got fixed in this Pull Request

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/25933

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-24 06:28 UTC, rogyar requested changes
Hi @muthu-ziffity. Thank you for your contribution. As far as I see, the original issue says that this issue is reproducible for all issues that have `showInStore` flag. I'm not sure that fixing one particular occasion solves the problem. 
Also, the single store mode should not affect the area from where we get the configuration. The single store mode only "hides" the possibility to switch scopes in the admin panel.

2020-02-18 15:16 UTC, muthu-ziffity reviewed
I have provided the fix for getting config value globally while single store mode was enabled and added test case for that.

Find below video have the output of fix

![output](https://user-images.githubusercontent.com/32055149/74749123-adecce00-528f-11ea-959e-7cfcec2a86f6.gif)

2020-02-18 15:19 UTC, muthu-ziffity commented
> Hi @muthu-ziffity. Thank you for your contribution. As far as I see, the original issue says that this issue is reproducible for all issues that have `showInStore` flag. I'm not sure that fixing one particular occasion solves the problem.
> Also, the single store mode should not affect the area from where we get the configuration. The single store mode only "hides" the possibility to switch scopes in the admin panel.

Provided a fix for this issue globally. Please review again

2020-02-28 08:13 UTC, muthu-ziffity reviewed
@akaplya @rogyar Please review this

2020-03-01 16:35 UTC, rogyar commented
Hi @muthu-ziffity. I'm putting it on hold for now. This solution should be discussed internally for the final decision. Thank you for your patience.

2020-03-05 14:52 UTC, muthu-ziffity commented
> Hi @muthu-ziffity. I'm putting it on hold for now. This solution should be discussed internally for the final decision. Thank you for your patience.

Ok @rogyar. Awaiting for your final decision of this fix

2020-03-11 17:15 UTC, Stepa4man reviewed
Comment for group code review

2020-03-11 17:15 UTC, Stepa4man commented on lib/internal/Magento/Framework/App/Config.php
> +    public function isSingleStoreMode($scope = ScopeConfigInterface::SCOPE_TYPE_DEFAULT)
Are you sure Framework should be aware of stores qty and such edge cases?

2020-06-25 10:26 UTC, engcom-Charlie commented
Hi @muthu-ziffity, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-06-25 10:26 UTC, closed without merging