Extend exception message
magento/magento2 pull request #26511
Opened 2020-01-23 16:28 UTC by oroskodias

Update exception messages to provide more detailed information on errors

2020-01-23 23:22 UTC, edenduong requested changes
Could you please update the `.csv` file?

2020-01-24 02:51 UTC, oroskodias commented
> Could you please update the `.csv` file?

done

2020-01-24 03:23 UTC, edenduong approved these changes
Thank you for your contribution !

2020-01-24 03:24 UTC, magento-engcom-team commented
Hi @edenduong, thank you for the review.
[ENGCOM-6678](https://jira.corp.magento.com/browse/ENGCOM-6678) has been created to process this Pull Request

2020-01-24 12:55 UTC, ihor-sviziev commented
I believe this could be tested with unit test.

2020-01-24 14:11 UTC, engcom-Echo commented
I will take care of test coverage.

2020-01-27 12:11 UTC, Nazar65 requested changes

2020-01-27 12:11 UTC, Nazar65 commented on app/code/Magento/Multishipping/Test/Unit/Model/Checkout/Type/MultishippingTest.php
> +     * Verefi set shipping items information for address leak
Verify

2020-01-27 12:11 UTC, Nazar65 commented on app/code/Magento/Multishipping/Test/Unit/Model/Checkout/Type/MultishippingTest.php
> +    private function mockShippingAssignment():void
```suggestion
    private function mockShippingAssignment(): void
```

2020-01-27 12:11 UTC, Nazar65 commented on app/code/Magento/Multishipping/Test/Unit/Model/Checkout/Type/MultishippingTest.php
> +        $quoteAddressItemMock =
```suggestion
 $quoteAddressItemMock = $this->getQuoteAddressItemMock(
                                                $quoteItemMock,
                                                $config['productType'], 
                                                $config['infoBuyRequest']
                                                );
```

2020-01-28 09:35 UTC, Nazar65 approved these changes

2020-01-28 13:20 UTC, ihor-sviziev approved these changes

2020-01-28 13:21 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6678](https://jira.corp.magento.com/browse/ENGCOM-6678) has been created to process this Pull Request

2020-01-28 14:51 UTC, edenduong approved these changes

2020-01-28 14:52 UTC, magento-engcom-team commented
Hi @edenduong, thank you for the review.
[ENGCOM-6678](https://jira.corp.magento.com/browse/ENGCOM-6678) has been created to process this Pull Request

2020-01-29 08:49 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:**
![before](https://user-images.githubusercontent.com/51679138/73341260-f31b7280-4284-11ea-8100-8aaed18390ca.png)

**After:**
![after](https://user-images.githubusercontent.com/51679138/73341283-fca4da80-4284-11ea-8197-59ecbd7f449b.png)

2020-02-07 23:15 UTC, merged