issue/26384 Fix store switcher when using different base url on stores
magento/magento2 pull request #26548
Opened 2020-01-27 10:36 UTC by TobiasCodeNull

### Description (*)
When a user switches between stores using the store switcher the request fails if the target store has a different base url than the current. This pull request changes the redirect controller to make the switch request using the targeted store' url instead so the switch is successful. 

### Fixed Issues (if relevant)
1. magento/magento2#26384: Store switcher redirects to homepage for multistore setup with different domains
2. magento/magento2#23755: Store view switcher is wrong , when each store views have different url.

### Manual testing scenarios (*)
1. Have simple Magento 2.4-dev setup with sampledata
2. Create two or more stores with different base url (i.e default.magento.dev and en.magento.dev)
3. Go to a category page of one store
4. Switch between the stores using the store switcher

Result without fix: You end up on the start page, without switched store and not the category on which you were on.
Result with fix: Store is switched and you stay in the same page you were on

### Questions or comments
No automated tests has been created for this pull request

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-31 00:29 UTC, edenduong requested changes
Thank you for your contribution. Please see my comment. And could you please cover your change by Automation Test? Thank you !

2020-01-31 00:29 UTC, edenduong commented on app/code/Magento/Store/Controller/Store/Redirect.php
> +        StoreManagerInterface $storeManager
Please change it to `StoreManagerInterface $storeManager = null` for backward compatible
https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/

2020-01-31 00:29 UTC, edenduong commented on app/code/Magento/Store/Controller/Store/Redirect.php
> +        $this->storeManager = $storeManager;
Please change to`$this->storeManager = $storeManager ?? ObjectManager::getInstance()->get(StoreManagerInterface::class);` for backward compatible
https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/

2020-01-31 17:23 UTC, TobiasCodeNull commented
Simple test made which goes through the controller and make sure that the StoreManager change to the correct store.
Also added the backwards compatibility for the controller.

2020-02-03 00:47 UTC, edenduong requested changes
Hi. Please add `use ...` to your code and add some `const`. Thanks.

2020-02-03 00:47 UTC, edenduong commented on app/code/Magento/Store/Test/Unit/Controller/Store/RedirectTest.php
> +        $this->storeManagerMock = $this->getMockBuilder(\Magento\Store\Model\StoreManagerInterface::class)->getMock();
Please `use Magento\Store\Model\StoreManagerInterface;` in all similar class and use the Alias.

2020-02-03 00:47 UTC, edenduong commented on app/code/Magento/Store/Test/Unit/Controller/Store/RedirectTest.php
> +        $storeToSwitchToCode = 'sv2';
Please add the const `const STUB_STORE_TO_SWITCH_TO_CODE = 'sv2';` and `const STUB_DEFAULT_STORE_VIEW = 'default';`

2020-02-03 00:47 UTC, edenduong commented on app/code/Magento/Store/Test/Unit/Controller/Store/RedirectTest.php
> +     * @var StoreRepositoryInterface|\PHPUnit_Framework_MockObject_MockObject
`PHPUnit_Framework_MockObject_MockObject` should be `PHPUnit\Framework\MockObject\MockObject`

2020-02-03 08:21 UTC, TobiasCodeNull commented
Cleaned up code and added Const values.

2020-02-11 08:39 UTC, edenduong commented
> Cleaned up code and added Const values.

Hi @TobiasCodeNull. Please resolve the confict code. And please use the alias in the DocBlock also.

2020-02-11 08:55 UTC, engcom-Charlie commented
Hi, @edenduong I'll take care of this.

2020-02-11 09:43 UTC, TobiasCodeNull commented
I'll leave this to @engcom-Charlie then

2020-02-12 09:21 UTC, edenduong approved these changes

2020-02-12 09:22 UTC, magento-engcom-team commented
Hi @edenduong, thank you for the review.
[ENGCOM-6869](https://jira.corp.magento.com/browse/ENGCOM-6869) has been created to process this Pull Request

2020-02-12 09:22 UTC, magento-engcom-team commented
@TobiasCodeNull thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-02-27 09:13 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-02-28 22:04 UTC, merged

2020-09-22 22:42 UTC, viktym commented
For Magento versions 2.3.0 - 2.3.5 patch is available in [Magento Quality Patches](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html#mqp) package (MQP)

**MQP Installation**
`$ composer require magento/quality-patches`

**Applying a Patch**
`$ ./vendor/bin/magento-patches apply MDVA-30107`

**Patch Details**
https://support.magento.com/hc/en-us/articles/360049869051