Notice: Undefined index: column
magento/magento2 pull request #26577
Opened 2020-01-29 12:30 UTC by itsazzad

This happens when any core module is replaced

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-29 20:17 UTC, ihor-sviziev requested changes
Hi @itsazzad,
Your changes looks good to me. 
Could you add steps to reproduce of this issue and cover your changes with unit test?

2020-01-30 21:58 UTC, lbajsarowicz approved these changes
Just minor performance request.
Could you cover your changes with Unit Tests and fix static code analysis?

2020-01-30 21:58 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php
> +        if (array_key_exists('column', $tableData)) {
You should use `isset` instead - as it's significantly faster.

2020-01-30 21:59 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6779](https://jira.corp.magento.com/browse/ENGCOM-6779) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-01-30 21:59 UTC, magento-engcom-team commented
@itsazzad thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-01-31 09:26 UTC, lbajsarowicz requested changes
Fix static tests

2020-02-14 07:10 UTC, ihor-sviziev commented
Hi @itsazzad,
Will you be able to update your PR?

2020-02-14 09:25 UTC, itsazzad commented
@ihor-sviziev I will try soon.

2020-03-02 09:52 UTC, ihor-sviziev commented
Hi @itsazzad,
Unfortunately I need to close your PR due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-03-02 09:52 UTC, closed without merging