magento/magento2#26575: REST API rest/all/V1/orders/create does not trigger "inventory_reservations_placement" plugin
magento/magento2 pull request #26576
Opened 2020-01-29 12:28 UTC by atwixfirster

### Description (*)

PR fixes https://github.com/magento/magento2/issues/26575.

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/26575: REST API rest/all/V1/orders/create does not trigger "inventory_reservations_placement" plugin

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-29 12:45 UTC, dmytro-ch commented
Please note, this PR provides backward-incompatible change, due to the different parameter names.

2020-01-29 12:49 UTC, atwixfirster commented
> Please note, this PR provides backward-incompatible change, due to the different parameter names.

Thanks for notice, @dmytro-ch !

Then I've to refactor my fix.

Thanks again!

2020-02-12 23:31 UTC, atwixfirster commented
@dmytro-ch , could you please review a new solution?

THank you!

2020-04-10 12:51 UTC, dmytro-ch requested changes
@atwixfirster, thank you for the updates!
Could you please change the class naming a little bit?

Please note, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes must be covered by auto tests. Could you please cover your case by API functional test?

Thank you!

2020-04-10 12:51 UTC, dmytro-ch commented on app/code/Magento/Sales/Api/OrderPlacementInterface.php
> +interface OrderPlacementInterface
```suggestion
interface PlaceOrderInterface
```

2020-04-10 12:51 UTC, dmytro-ch commented on app/code/Magento/Sales/Model/Service/OrderPlacementService.php
> +use Magento\Sales\Api\Data\OrderInterface;
Please sort imports.

2020-04-10 12:51 UTC, dmytro-ch commented on app/code/Magento/Sales/Model/Service/OrderPlacementService.php
> +class OrderPlacementService implements OrderPlacementInterface
```suggestion
class PlaceOrderService implements PlaceOrderInterface
```

2020-05-01 21:49 UTC, VladimirZaets commented
@atwixfirster , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2020-05-01 21:49 UTC, closed without merging

2020-05-02 20:40 UTC, atwixfirster commented
> @atwixfirster , I am closing this PR now due to inactivity.
> Please reopen and update if you wish to continue.
> Thank you for collaboration

Hi, @VladimirZaets !

Unfortunately,  I do not have access to reopen a PR. Can you please reopen it?

Thanks!

2020-05-02 20:40 UTC, atwixfirster commented on app/code/Magento/Sales/Model/Service/OrderPlacementService.php
> +class OrderPlacementService implements OrderPlacementInterface
**done**

2020-05-02 20:40 UTC, atwixfirster commented on app/code/Magento/Sales/Model/Service/OrderPlacementService.php
> +use Magento\Sales\Api\Data\OrderInterface;
**done**

2020-05-02 20:41 UTC, atwixfirster commented on app/code/Magento/Sales/Api/OrderPlacementInterface.php
> +interface OrderPlacementInterface
**done**