Fixed #26599 Separate delta value for rounding product and shipping tax
magento/magento2 pull request #26600
Opened 2020-01-31 05:40 UTC by willtran

### Description (*)
Fix #26599 

### Manual testing scenarios (*)
1. Reproduce issue 26599
2. Add item to cart and select shipping method with price
3. Shipping price and tax should be consistent regardless of the number of item / price of item in cart

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-14 16:49 UTC, sidolov requested changes
@willtran please, cover changes with automated test

2020-09-17 10:39 UTC, gabrieldagama commented
The risk is set to medium since tax calculation is a critical feature.

2020-09-29 12:03 UTC, engcom-Echo commented
Hi, @willtran. Can you provide more detail for the reproduce this issue? 
Please describe the third step(Shipping price and tax should be consistent regardless of the number of item / price of item in cart) in more detail.

2020-09-29 20:04 UTC, sidolov commented
@willtran  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-29 20:04 UTC, closed without merging