Added integration test for getExistsStoreValueFlag in product model
magento/magento2 pull request #26601
Opened 2020-01-31 07:24 UTC by ochnygosch

### Description (*)

Add integration tests to demonstrate issue magento/magento2#26581

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-01-31 08:25 UTC, edenduong requested changes
Thank you for your contribution. Please check my comment.

2020-01-31 08:25 UTC, edenduong commented on dev/tests/integration/testsuite/Magento/Catalog/Model/ProductTest.php
> +        $descriptionProudct = $this->productRepository->get('store_description');
Please correct the typo: `$descriptionProduct`

2020-01-31 08:25 UTC, edenduong commented on dev/tests/integration/testsuite/Magento/Catalog/Model/ProductTest.php
> +        $storeManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager()->get(\Magento\Store\Model\StoreManagerInterface::class);
Please `use Magento\TestFramework\Helper\Bootstrap;` and `use Magento\Store\Model\StoreManagerInterface;` and replace it by alias

2020-01-31 08:25 UTC, edenduong commented on dev/tests/integration/testsuite/Magento/Catalog/Model/ProductTest.php
> +        $nameProudct = $this->productRepository->get('store_name', false, $store->getId(), true);
Please fix the typo `$nameProduct`

2020-01-31 08:25 UTC, edenduong commented on dev/tests/integration/testsuite/Magento/Catalog/_files/products_different_store_values_rollback.php
> +$registry = \Magento\TestFramework\Helper\Bootstrap::getObjectManager()->get(\Magento\Framework\Registry::class);
Please declare `use` and use the alias

2020-03-02 10:40 UTC, engcom-Echo commented
@magento run all tests

2020-03-03 00:34 UTC, edenduong commented
Hi @ochnygosch: Please fix the static test and the integration test. It should be green.

2020-04-05 10:03 UTC, edenduong commented
Hello @ochnygosch,
After 30 days, I don't get any respond from you and the Automation Test still Fail so I will close this PR. It you want to continue, please reopen the PR.
Thank you !

2020-04-05 10:03 UTC, closed without merging

2020-11-12 06:17 UTC, ochnygosch commented
@magento give me test instance