Removed confusing and unused tab (& accordion) option.
magento/magento2 pull request #26609
Opened 2020-01-31 10:59 UTC by quisse

### Description (*)
Removed confusing and unused tab (& accordion) option.
### Manual testing scenarios (*)

As you can see in following file, the option `"collapse"` isn't used anywhere so it should be removed.  https://github.com/magento/magento2/blob/e6e6725329f75e36380e788e254ad012e8ae0759/lib/web/mage/tabs.js#L1-L352

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-02 06:17 UTC, ihor-sviziev requested changes
Hi @quisse,
Could you sign Adobe CLA and review failing tests, looks like your changes broke some functionality

2020-02-04 19:47 UTC, ihor-sviziev commented
@magento run all tests

2020-02-14 07:14 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Static Tests, Unit Tests

2020-02-25 16:15 UTC, ihor-sviziev submitted a review, later dismissed
Hi @quisse,
Thank you for signing Adobe CLA, however there still some test failures, looks like your changes did some regression.

Could you update your PR?

2020-02-25 16:20 UTC, quisse commented
Hi @ihor-sviziev, yes I will anytime soon, thanks for the reminder. But first I'll need to look in to setting the tests up locally. To be continued...

2020-02-26 19:50 UTC, quisse commented
Fixing or even looking at those tests is way too much hassle.

2020-02-26 19:50 UTC, closed without merging