#26624 Color swatch tooltip arrow position is not proper on the Produ…
magento/magento2 pull request #26625
Opened 2020-02-02 04:49 UTC by tejash-wagento

…ct detail page

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#26624: Color swatch tooltip arrow position is not proper on the Product detail page

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-02 04:50 UTC, tejash-wagento commented
#mm20in

2020-07-28 22:33 UTC, VladimirZaets submitted a review, later dismissed

2020-07-28 22:34 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7909](https://jira.corp.magento.com/browse/ENGCOM-7909) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-07-29 07:35 UTC, engcom-Alfa requested changes
Hi @tejash-wagento . Unfortunately, we are not able to reproduce this [issue](https://github.com/magento/magento2/issues/26624) on fresh 2.4-develop.

On the Product detail page ( **Luma** theme)

**Actual Result:** :heavy_check_mark: Color swatch tooltip arrow position is proper

![Screenshot from 2020-07-29 10-22-57](https://user-images.githubusercontent.com/51679138/88770889-1e751080-d187-11ea-9b89-bbcc3146f035.png)

On the Product detail page ( **Blank** theme)

**Actual Result:** :heavy_check_mark: Color swatch tooltip arrow position is proper

![Screenshot from 2020-07-29 10-30-05](https://user-images.githubusercontent.com/51679138/88770934-2df45980-d187-11ea-88d0-c470d9c380f9.png)

@tejash-wagento Could you take a look?
Thanks!

2020-08-14 13:18 UTC, engcom-Echo commented
Hi @tejash-wagento, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-08-19 20:03 UTC, sidolov commented
@tejash-wagento , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-08-19 20:03 UTC, closed without merging