Fixed #24704 Saving CMS Page Title from REST web API makes content empty
magento/magento2 pull request #26639
Opened 2020-02-02 08:02 UTC by shikhamis11

Fixed #24704 Saving CMS Page Title from REST web API makes content empty

I am not sure if this is a bug or feature. I am trying to update the CMS Page title from POSTMAN. It updates title but also makes content and other fields empty.

### Preconditions (*)

1. At least 1 CMS page
2. Web API auth key

### Steps to reproduce (*)

1. Go to the [postman](https://www.getpostman.com/) and use this URL and body content with PUT method
URL: `http://www.example.com/rest/all/V1/cmsPage/ID` (replace ID with your id (integer)
Body: 
```
{"page":
	{
		"title": "My Title"
	}
}
```

### Expected result (*)

1. Update TITLE and keep all other fields same/unchanged
2. OR only update the field provided.

### Actual result (*)

1. Updates title and makes all other fields (not provided in the body) null.

**How do I update title only or content only? I want to update one field only (title at this stage).** 
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-20 11:35 UTC, sivaschenko requested changes
Hi @shikhamis11 thanks for the pull request! Please see my improvement proposition

2020-02-20 11:35 UTC, sivaschenko commented on app/code/Magento/Cms/Model/PageRepository.php
> +                $page->addData($pageData);
Magento\Cms\Api\Data\PageInterface does not have toArray/addData methods. Can you please use hydrator to extract and add data

2020-02-20 11:36 UTC, sivaschenko commented
@shikhamis11 also, it would be really useful to cover this behaviour with a webapi test

2020-03-09 17:08 UTC, lenaorobei commented
Closing this PR due to inactivity. @shikhamis11, do not hesitate to reopen if you are going to continue working on it.

2020-03-09 17:08 UTC, closed without merging