magento/magento2#23063: Translate product email alert
magento/magento2 pull request #26643
Opened 2020-02-02 08:27 UTC by lavanyadckap

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-02 11:24 UTC, lbajsarowicz requested changes
Please find the comment attached and cover change with Unit / Integration tests.

2020-02-02 11:24 UTC, lbajsarowicz commented on app/code/Magento/ProductAlert/Model/Observer.php
> +                        ($alert->getStoreId())?$alert->getStoreId():$website->getDefaultStore()->getId()
`$alert->getStoreId() ?: $website->getDefaultStore()->getId()`

2020-03-23 12:56 UTC, lbajsarowicz requested changes
Could you apply the suggestion?

2020-06-25 10:44 UTC, engcom-Charlie commented
Hi @lavanyadckap, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-06-25 10:44 UTC, closed without merging