Fixed #18823: Prefix dropdown in checkout doesn't select empty value by defau…
magento/magento2 pull request #26640
Opened 2020-02-02 08:16 UTC by mikebox

Fixed #18823: Prefix dropdown in checkout doesn't select empty value by default if required

### Description (*)
Added a condition to ensure the options provided by the customers start with the separator(;). If the separator exists at the start of the options, adding an empty option in the select.

Additional Notes:
array_filter() removes the empty characters. Removing that might create additional problems of having empty options in the middle. So added a condition to ensure the starting character and act based on that.

### Fixed Issues (if relevant)
1. magento/magento2#18823: Prefix dropdown in checkout doesn't select empty value by default if required

### Manual testing scenarios (*)

1. In Admin Backend go to Stores > Configuration > Customers > Name and Address Options
2. Set "Show Prefix" to "Required"
3. Set "Prefix Dropdown Options" to ";Mr.;Mrs."
4. Save Config
5. Go to your store
6. Add a item to your cart
7. Go to checkout

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-05 19:02 UTC, lenaorobei commented
Related to https://github.com/magento/magento2/pull/20896

2020-02-10 15:57 UTC, lenaorobei commented
As per discussion with PO @mbrinton01, the expected behavior is:
`Mr;Ms;`  - select with `Mr` , `Ms` and `""`
`;Mr;Ms` - select with `""`, `Mr` and `Ms`
`;Mr;Ms;`- select with `""`, `Mr`, `Ms` and `""`

https://github.com/magento/magento2/issues/17861 was configuration issue but not the functional.

2020-02-10 15:57 UTC, lenaorobei commented on app/code/Magento/Customer/Model/Options.php
> +        if (substr($options, 0, 1) === ";") {
Please remove this check.

2020-02-10 15:58 UTC, lenaorobei commented on app/code/Magento/Customer/Model/Options.php
>          $options = array_filter(explode(';', $options));
```suggestion
        $options = explode(';', $options);
```

2020-02-10 15:59 UTC, lenaorobei requested changes
@mikebox please see my comments and consider covering these cases with MFTF tests. Thank you.

2020-02-12 18:14 UTC, swnsma commented
Hi @mikebox @lenaorobei 
Could we use a little bit complex but more obvious approach called 'Dynamic Rows'?
https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/dynamic-row-system-config.html

2020-02-13 17:11 UTC, lenaorobei commented
I like this idea! Let me confirm with @mbrinton01 since it will be a pretty big UI change and I believe we should take care of `suffix` as well.

2020-02-13 21:15 UTC, mbrinton01 commented
I'm fine with this approach as it should return the same experience for the user.

2020-02-21 10:58 UTC, engcom-Echo commented
I will take care of test coverage.

2020-02-26 15:23 UTC, lenaorobei submitted a review, later dismissed

2020-02-26 15:24 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-6991](https://jira.corp.magento.com/browse/ENGCOM-6991) has been created to process this Pull Request

2020-02-28 09:36 UTC, engcom-Alfa reviewed
.

2020-02-28 09:37 UTC, engcom-Alfa requested changes
Hi @mikebox.

During testing, we faced the issue.

**_Problem:_** Prefix dropdown in checkout doesn't select an empty value by default

**Manual testing scenario:**

1. In Admin Backend go to Stores > Configuration > Customers > Name and Address Options;
2. Set "Show Prefix" to "Required";
3. Set "Prefix Dropdown Options" to ";Mr.;Mrs.";
4. Save Config and go to your store;
5. Add an item to your cart and go to checkout;

**Actual Result:** The value "**Mr.**" is selected by default
![after2](https://user-images.githubusercontent.com/51679138/75536718-651adf00-5a1e-11ea-8193-9f65b4ebeb75.gif)

@mikebox Could you take a look?

Thanks!

2020-03-24 14:28 UTC, lenaorobei commented
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

2020-03-24 14:28 UTC, closed without merging