24938: Fix wrong shipping amount in totals for multiple address is used.
magento/magento2 pull request #26662
Opened 2020-02-02 10:10 UTC by pradeep-wagento

### Description (*)
Fix wrong shipping amount in totals when multiple address is selected with different shipping amount.

### Related Pull Requests
https://github.com/magento/magento2/commit/250180b7ee67d75c888dedc4ca99012148f66945

### Fixed Issues (if relevant)
1. magento/magento2#23631: Multishipping checkout, shipping amount is not applied correctly when different on different addresses/items
2. magento/magento2#24938: Wrong shipping amount calculation when checkout with multiple address is used.

### Manual testing scenarios (*)

### Questions or comments
The commit shared in Related pull request  doesn't seems to be as per magento standard. But any how it was merged. Remove those commit, which will be reproduce issue.
Apply the changes for this PR, issue will work and will be as per standard.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-02 16:01 UTC, rogyar requested changes
Hi @pradeep-wagento. Thank you for your collaboration. For improving the overall code quality, could I kindly ask you to fix the [following](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/26662/91ff9b194715d3d5ac4792d11dc6e9e6/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/9a822284d909d036/) static check failures (even if they are not related to your changes directly).

Also, according to the [Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes in a PR should be covered by automated tests. I would suggest extending the [following](https://github.com/magento/magento2/blob/40d9c7e452eaae742f35ea587bbc6f8a2d3fc8d4/app/code/Magento/Tax/Test/Unit/Model/Sales/Total/Quote/ShippingTest.php#L142) unit test.

Thank you!

2020-02-11 07:46 UTC, engcom-Echo commented
I will take care of test coverage.

2020-02-19 08:37 UTC, engcom-Charlie commented
Hi, @pradeep-wagento linked issues aren't reproducible on 2.4-develop. Please check this and provide the correct steps to reproduce on the latest version.

2020-02-22 14:19 UTC, pradeep-wagento commented
@engcom-Charlie 

https://github.com/magento/magento2/commit/250180b7ee67d75c888dedc4ca99012148f66945 doesn't seems to be as per magento standard. But any how it was merged. Remove this commit, which will be reproduce issue.
Apply the changes for this PR, issue will work and will be as per standard.

2020-08-17 19:38 UTC, sidolov commented
Hi @pradeep-wagento , I'm closing the PR since the issue is not reproducing on the 2.4-develop branch. Feel free to reopen PR in case you find additional scenario.

2020-08-17 19:38 UTC, closed without merging