Fix: missing "null" and "false" return type hints in RouterInterface:…
magento/magento2 pull request #26699
Opened 2020-02-04 15:02 UTC by gsomoza

### Description (*)
The core code in FrontController expects a "falsey" value to be returned from routers that don't match a request, but want to delegate to the next router:

```
foreach ($this->_routerList as $router) {
    try {
        $actionInstance = $router->match($request);
        if ($actionInstance) { // <---- return type must evaluate to "false" for loop to continue
            $result = $this->processRequest();
            // ...
        }
    } catch (\Magento\Framework\Exception\NotFoundException $e) {
        // ...
    }
}
```

However this concrete expectation is not reflected in the `\Magento\Framework\App\RouterInterface::match` signature, which currently only allows `ActionInterface` in the docblock. This creates problems with static code analysis like PHPStan.

This pull request:
* Adds the "null" return type hint to the RouterInterface::match()
docblock. This fixes issues with PHPStan and IDE's, and makes
the behaviour more explicit for anyone trying to implement their own routers.
* Fixes the associated unit test to make sure `null`, specifically,
is handled properly in the future, because that's what most (if not all) core routers are actually returning.

### Manual testing scenarios (*)
Not necessary.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-04 15:35 UTC, gsomoza commented
FYI just signed the Adobe CLA @adobe/open-source-office

2020-02-04 22:26 UTC, gsomoza commented
I think SemVer Checker's recommendation to bump on MAJOR might not actually be accurate, for the following reasons:

1. We're only **adding** new return types to (A) an interface's DocBlock, that (B) should have had them all along (based on existing behaviour of core code): if anything, (C) it could be considered a small bugfix, because the two major pieces of code that use this interface in the core are in fact technically **misusing** the interface.
2. The changes are 100% backwards compatible with existing implementations of the interface, even for projects using PHPStan or similar.

If this is considered a bug fix then I'd be happy to submit a backport for 2.3.

2020-03-09 17:02 UTC, lenaorobei requested changes
Hi @gsomoza. This is a problem of leaky abstraction. The interface should not care about implementation details in classes. 

The solution here should be class refactoring. It will be our step towards strict typing.

2020-03-11 10:27 UTC, gsomoza commented
That would be indeed a better fix. Is that refactoring already being worked on or are there plans to start it soon?

2020-03-11 17:27 UTC, lenaorobei commented
I believe this issue is not reported yet so I'm going to create a GitHub issue to address it.

2020-03-11 18:00 UTC, lenaorobei commented
Closing this PR with reference to the issue https://github.com/magento/magento2/issues/27250

2020-03-11 18:00 UTC, closed without merging