Issue Fixed #26726 Qty decimals allowed on configurable product even when setting set to 'no' ..
magento/magento2 pull request #26743
Opened 2020-02-07 03:15 UTC by gauravagarwal1001

Issue Fixed #26726

### Preconditions (*)

1. Magento CE 2.2.10

### Steps to reproduce (*)

1. Add simple product having 'Qty Uses Decimals' = 'No' (default)
2. Add configurable product having 'Qty Uses Decimals' = 'No' (default)
3. Link simple to configurable
4. Go to PDP and add '1.x' (ie 1.5) to cart

### Expected result (*)

1. Behaviour like simple products - floored qty is added to cart

### Actual result (*)

1. Decimal qty is added to cart

2020-02-10 22:34 UTC, sdzhepa commented
@magento run all tests

2020-08-20 15:51 UTC, sidolov requested changes
@gauravagarwal1001 could you please cover changes with MFTF test?

2020-08-26 07:11 UTC, engcom-Charlie commented
Hi, @gauravagarwal1001 could you please cover changes with the MFTF test?
Thank you.

2020-09-03 07:45 UTC, engcom-Charlie commented
Hi @gauravagarwal1001, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-09-03 07:45 UTC, closed without merging