[WIP]: Replace `use PHPUnit_Framework_MockObject_MockObject as MockObject` w…
magento/magento2 pull request #26775
Opened 2020-02-08 19:05 UTC by hws47a

### Description (*)
- Replace `use PHPUnit_Framework_MockObject_MockObject as MockObject` with just import

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-08 19:18 UTC, lbajsarowicz commented
@hws47a Great idea to change that. Please keep in mind that you'll have to fix Static Tests eventually.

2020-02-08 19:20 UTC, hws47a commented
@lbajsarowicz thanks. Yeah, just thought about it. If I will bulk update all of the unit tests, they'll probably fail all together in static tests.

2020-02-08 21:30 UTC, lbajsarowicz commented
@hws47a Wow. The only tests failed are Functional Tests (false negative). I've made them run again and then it should pass. Thanks for your contribution. I'm going to approve PR.

2020-02-08 21:31 UTC, lbajsarowicz approved these changes

2020-02-08 21:32 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6831](https://jira.corp.magento.com/browse/ENGCOM-6831) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-02-08 21:34 UTC, hws47a commented
@lbajsarowicz yeah, I saw it. And it's a little bit too early to approve. It's a draft and WIP.

2020-02-08 23:24 UTC, hws47a commented
Hi @lbajsarowicz, it's now ready. 
And it seems there are no static check errors at all.

2020-02-08 23:47 UTC, lbajsarowicz requested changes
Could you remove spaces around `|` in all modified files?
Also - we need the real class reference next to `MockObject` that is missing in some cases

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/Language/DictionaryTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you also provide `|ReadFactory`?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/Language/DictionaryTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
`|ComponentRegistrar`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/Language/DictionaryTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
`|ConfigFactory`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Acl/Test/Unit/AclResource/ProviderTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
`|ConfigReader`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Acl/Test/Unit/AclResource/ProviderTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
`|TreeBuilder`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Acl/Test/Unit/BuilderTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Acl/Test/Unit/BuilderTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Acl/Test/Unit/BuilderTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Acl/Test/Unit/BuilderTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Acl/Test/Unit/BuilderTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Amqp/Test/Unit/ConfigTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Api/Test/Unit/Code/Generator/EntityChildTestAbstract.php
> +     * @var Io | \PHPUnit\Framework\MockObject\MockObject
Remove space between `|`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Api/Test/Unit/Code/Generator/EntityChildTestAbstract.php
> +     * @var \Magento\Framework\Code\Generator\ClassGenerator | \PHPUnit\Framework\MockObject\MockObject
Remove space around `|`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Api/Test/Unit/Code/Generator/EntityChildTestAbstract.php
> +    /** @var \PHPUnit\Framework\MockObject\MockObject | \Magento\Framework\Code\Generator\DefinedClasses */
Remove space around `|`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Api/Test/Unit/Code/Generator/GenerateMapperTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Api/Test/Unit/Code/Generator/GenerateSearchResultsTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/ActionFlagTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/AreaListTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/AreaListTest.php
> +     * @return \PHPUnit\Framework\MockObject\MockObject
Could you add `|` and the accurate class reference?

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/AreaTest.php
> +     * @var \Magento\Framework\Event\ManagerInterface | \PHPUnit\Framework\MockObject\MockObject
Could you remove space around `|`

2020-02-08 23:47 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Test/Unit/AreaTest.php
> +     * @var \Magento\Framework\ObjectManagerInterface | \PHPUnit\Framework\MockObject\MockObject
Could you remove space around `|`

2020-02-08 23:49 UTC, hws47a commented
@lbajsarowicz have you seen the number of files changed? :)
I have no intension to fix anything else in this PR except just replacing outdated class name.

2020-02-08 23:51 UTC, lbajsarowicz commented
Remove just spaces around `|` as it's just another smell (that should be detected by Static tests actually). Adding missing annotations for original classes could be done in separate PR.

2020-02-09 01:23 UTC, hws47a commented
> Remove just spaces around `|` as it's just another smell (that should be detected by Static tests actually). Adding missing annotations for original classes could be done in separate PR.

@lbajsarowicz  Done

2020-02-09 01:25 UTC, hws47a commented
I already had to fix two conflicts during rebase, so it's better to merge it as soon as possible

2020-02-11 20:24 UTC, ihor-sviziev commented
@hws47a wow. You did really huge work!
Unfortunately such bug PRs is really hard to merge as they all the time has conflicts with other PRs. I think it’s better to split the work to smaller parts that could be quite easy tested and quite quickly delivered.

Am I correct @slavvka @buskamuza @VladimirZaets ?

2020-02-11 20:27 UTC, lbajsarowicz commented
That can be delivered the same way that I delivered MFTF changes (1 per module)

2020-02-11 20:40 UTC, hws47a commented
@lbajsarowicz @ihor-sviziev Thank you for suggestion.
I'll do it.

2020-02-11 20:45 UTC, hws47a commented
@lbajsarowicz @ihor-sviziev I've create one, let's test-drive on it.

2020-02-15 17:45 UTC, ihor-sviziev commented
Hi @hws47a,
This PR already have some conflicts as I said above, I think we can close it, as you’re going to create separate PRs for each module.

2020-02-15 17:45 UTC, closed without merging