Disabled flat: cast $attributeId as (int) in selects
magento/magento2 pull request #26790
Opened 2020-02-10 10:19 UTC by ilnytskyi

### Description (*)

When we disabled flat we noticed that ids are cast as string
```
SELECT `t_d`.`attribute_id`, `e`.`entity_id`
FROM `catalog_product_entity_varchar` AS `t_d`
         INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = t_d.entity_id
         LEFT JOIN `catalog_product_entity_varchar` AS `t_s`
                   ON t_s.attribute_id = t_d.attribute_id AND t_s.entity_id = t_d.entity_id AND t_s.store_id = 8
WHERE (e.entity_id IN
       (209884, 213420, 212364, 212009, 211989, 211710, 210914, 210588, 212316, 212239, 210456, 210453, 213157, 212556,
        212380, 211186, 210984, 210157, 209443, 208989, 169036, 168488, 158426, 211496, 209688, 210951, 203816, 206125,
        203077, 158390, 158397, 158402, 206534, 143843, 149488, 149470, 200116, 193494, 193134, 208259, 151009, 213770,
        213759, 213751, 213735, 213731, 213721, 213270, 212975, 212948, 212917, 212865, 212753, 212729, 212655, 212541))
  AND (t_d.attribute_id IN
       ('73', '87', '88', '89', '109', '110', '111', '119', '122', '133', '148', '177', '180', '184', '210', '220',
        '222'))
  AND (t_d.store_id = IFNULL(t_s.store_id, 0));
```
this fix will change it to be cast like numbers
```
SELECT `t_d`.`attribute_id`, `e`.`entity_id`
FROM `catalog_product_entity_varchar` AS `t_d`
         INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = t_d.entity_id
         LEFT JOIN `catalog_product_entity_varchar` AS `t_s`
                   ON t_s.attribute_id = t_d.attribute_id AND t_s.entity_id = t_d.entity_id AND t_s.store_id = 8
WHERE (e.entity_id IN
       (209884, 213420, 212364, 212009, 211989, 211710, 210914, 210588, 212316, 212239, 210456, 210453, 213157, 212556,
        212380, 211186, 210984, 210157, 209443, 208989, 169036, 168488, 158426, 211496, 209688, 210951, 203816, 206125,
        203077, 158390, 158397, 158402, 206534, 143843, 149488, 149470, 200116, 193494, 193134, 208259, 151009, 213770,
        213759, 213751, 213735, 213731, 213721, 213270, 212975, 212948, 212917, 212865, 212753, 212729, 212655, 212541))
  AND (t_d.attribute_id IN (73, 87, 88, 89, 109, 110, 111, 119, 122, 133, 148, 177, 180, 184, 210, 220, 222))
  AND (t_d.store_id = IFNULL(t_s.store_id, 0));
```

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. See selects generated in `\Magento\Eav\Model\Entity\Collection\AbstractCollection::_loadAttributes` method
2. 

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-10 12:22 UTC, rogyar requested changes
Hi @ilnytskyi. Thank you for your collaboration. Could you take a look at the failing tests, please? 

Also, according to the new [Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by auto-tests. In this particular case, I would suggest extending the existing [unit test](https://github.com/magento/magento2/blob/2d3760edbbf40d26f47ce66c69e89fd2bd4eb3ad/app/code/Magento/Eav/Test/Unit/Model/Entity/Collection/AbstractCollectionTest.php#L13).

Thank you.

2020-02-11 09:10 UTC, ilnytskyi commented
@rogyar added a test 
B2B and EE tests seem to be falling due to problems not related to current cahnges.

2020-02-15 11:55 UTC, rogyar commented
Awesome, thank you

2020-02-15 11:55 UTC, rogyar approved these changes

2020-02-15 11:56 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-6908](https://jira.corp.magento.com/browse/ENGCOM-6908) has been created to process this Pull Request

2020-02-17 08:51 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-02-21 22:22 UTC, merged