Update MockObject class in Magento Framework
magento/magento2 pull request #26823
Opened 2020-02-11 20:44 UTC by hws47a

### Description (*)
Replace outdated PSR-0 `\PHPUnit_Framework_MockObject_MockObject` with current PSR-2 class name `\PHPUnit\Framework\MockObject\MockObject`

### Related Pull Requests
#26775 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-11 23:19 UTC, lbajsarowicz submitted a review, later dismissed
Could you remove spaces around pipe ` | `?

2020-02-13 08:31 UTC, Nazar65 requested changes

2020-02-13 08:31 UTC, Nazar65 commented on lib/internal/Magento/Framework/App/Test/Unit/Config/MetadataConfigTypeProcessorTest.php
> +use \PHPUnit\Framework\MockObject\MockObject as MockObject;
```suggestion
use \PHPUnit\Framework\MockObject\MockObject;
```
Could you please also remove as where this is not necessary ?

2020-02-13 20:28 UTC, hws47a commented
@lbajsarowicz it was already removed. I took the code from the previous PR

2020-02-13 20:28 UTC, hws47a commented
@Nazar65 done

2020-02-13 20:40 UTC, Nazar65 approved these changes

2020-02-17 21:23 UTC, sivaschenko commented
@magento run Static Tests, Unit Tests

2020-02-18 12:05 UTC, sivaschenko requested changes
Hi @hws47a thanks for the pull request! There are multiple static and unit test failures, can you please fix those

2020-02-18 12:23 UTC, sivaschenko commented
@hws47a the pull request intention is great, however, I think it may be hard to fix all the static test for all the 632 files, also it's not comfortable to review and potentially a lot of conflicts can occur during the processing.

I'd recommend dividing this contribution into several PRs ~50 files each. That will make these contributions much easier to process

2020-04-02 16:01 UTC, ihor-sviziev commented
Hi @hws47a,
I'm closing this PR as it contains too many changed files and already have conficts.
Please create separate PRs per module, so it will be much easier to fix the issues and deliver it fast.

Thank you for your contritbution!

2020-04-02 16:01 UTC, closed without merging