TierPriceBox toHtml method should be return with string
magento/magento2 pull request #26863
Opened 2020-02-13 17:21 UTC by tufahu

### Description

`\Magento\ConfigurableProduct\Pricing\Render\TierPriceBox::toHtml` method can return with null (nothing) at missing return statement

```
public function toHtml()
{
        // Hide tier price block in case of MSRP or in case when no options with tier price.
        if (!$this->isMsrpPriceApplicable() && $this->isTierPriceApplicable()) {
            return parent::toHtml();
        }
}

```
It brakes the implemented interface `\Magento\Framework\View\Element\BlockInterface`

```
interface BlockInterface
{
    /**
     * Produce and return block's html output
     *
     * @return string
     */
    public function toHtml();
}

```

2020-02-14 04:35 UTC, ihor-sviziev requested changes
Hi @tufahu,
Your changes looks good.
Could you cover your changes with unit or integration tests?

2020-02-17 14:43 UTC, ihor-sviziev requested changes
@tufahu,
Unit test looks good, but please fix static tests failure.

I see that functional test failure isn't related to this PR.

2020-02-17 19:04 UTC, ihor-sviziev approved these changes

2020-02-17 19:05 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6917](https://jira.corp.magento.com/browse/ENGCOM-6917) has been created to process this Pull Request

2020-02-17 22:06 UTC, tufahu commented
@ihor-sviziev all requests done, thanks for your help.

2020-02-18 08:12 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-02-21 22:21 UTC, merged