Swatches options: eliminate objects instantiation since only their data needed
magento/magento2 pull request #26897
Opened 2020-02-17 13:02 UTC by ilnytskyi

### Description (*)

Removed the need to instantiate new objects from collection in the method
`\Magento\Swatches\Helper\Data::getSwatchesByOptionsId`
since only data used

Objects are created but then on every used a method `->getData`
![Selection_380](https://user-images.githubusercontent.com/3192770/74656038-af35d200-518d-11ea-9ccc-5734d825502d.png)

With this fix we only use data and do not create new objects, that saves a few milliseconds on large collections
![Selection_379](https://user-images.githubusercontent.com/3192770/74656175-ead09c00-518d-11ea-8a73-e2131a237c1a.png)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Render layered navigation on listing
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-17 13:32 UTC, ihor-sviziev commented
@ilnytskyi In general your change looks logical, but it prevents triggering all events, so it might break some customizations. Let's wait for test results

2020-02-17 14:10 UTC, ilnytskyi commented
@ihor-sviziev 
I agree if there is native magneto customization.
To customize that method or collection there are plenty of ways, from plugins to injecting custom factory collection
I will take a look at falling tests

2020-02-17 15:08 UTC, ihor-sviziev requested changes
Please fix failing tests

2020-02-18 11:52 UTC, ihor-sviziev commented on app/code/Magento/Swatches/Test/Unit/Helper/DataTest.php
> +        $swatchMock->expects($this->at(0))->method('offsetGet')->with('type')->willReturn($optionsData[0]['type']);
@ilnytskyi maybe it's better to replace it with `willReturnMap`?

2020-02-18 11:53 UTC, ihor-sviziev commented on app/code/Magento/Swatches/Test/Unit/Helper/DataTest.php
> +        $swatchMock->expects($this->at(0))->method('offsetGet')->with('type')->willReturn($optionsData[0]['type']);
ah, no, it will not work, as values the same. So please leave it as is

2020-02-18 13:31 UTC, ihor-sviziev approved these changes

2020-02-18 13:32 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6922](https://jira.corp.magento.com/browse/ENGCOM-6922) has been created to process this Pull Request

2020-02-19 10:49 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-02-21 22:21 UTC, merged