Fix #26917 Tax rate zip/post range check box alignment issue
magento/magento2 pull request #26932
Opened 2020-02-19 14:34 UTC by srsathish92

### Description (*)
This PR fixed the issue #26917. I added new class in template because I can't able to find any specific field set for that section. Same type of style applied in Customer Module itself which I get a reference from `app/design/adminhtml/Magento/backend/Magento_Customer/web/css/source/_module.less
Line No: 105 to 109`.

### Fixed Issues (if relevant)
1. magento/magento2#26917

### Manual testing scenarios (*)
- GOTO Admin -> Store -> Taxes -> Tax Zones and Rates -> Add new -> Tax rate Zip/Post range
- Checkbox alignment should be in same line

### Questions or comments
If any please let me know the feedback

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-24 08:47 UTC, edenduong commented
@magento give me test instance

2020-02-24 08:47 UTC, magento-engcom-team commented
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

2020-02-24 08:47 UTC, magento-engcom-team commented
Hi @edenduong, here is your [new Magento instance](https://pr-26932.instances.magento-community.engineering).
Admin access: [https://pr-26932.instances.magento-community.engineering/admin_4bbc](https://pr-26932.instances.magento-community.engineering/admin_4bbc)
Login: `6ef873a8` Password: `d50e44fd290f`
Instance will be terminated in up to 3 hours.

2020-02-24 09:17 UTC, edenduong submitted a review, later dismissed
Can you please add the class in the field:
```php
        $fieldset->addField(
            'zip_is_range',
            'checkbox',
            ['name' => 'zip_is_range', 'label' => __('Zip/Post is Range'), 'value' => '1']
        );
```

in `Magento\Tax\Block\Adminhtml\Rate\Form`

I think it would be better. Thank you.

2020-02-24 09:34 UTC, edenduong requested changes
Please check my comment. Thank you !

2020-02-24 11:08 UTC, srsathish92 commented
@edenduong Thanks for the feedback, As per your comments I have updated the changes. can you please review now.

2020-02-24 13:35 UTC, edenduong approved these changes
Thank you for your contribution !

2020-02-24 13:36 UTC, magento-engcom-team commented
Hi @edenduong, thank you for the review.
[ENGCOM-6967](https://jira.corp.magento.com/browse/ENGCOM-6967) has been created to process this Pull Request
:eight_spoked_asterisk: @edenduong, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-02-25 08:13 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-02-26 21:08 UTC, merged