[Ui] Don't trigger grid reload at first page load
magento/magento2 pull request #26984
Opened 2020-02-23 10:40 UTC by Den4ik

### Description (*)

Each page with ui grid contain not filtered grid collection items from load.  
After page load called reload event that load filtered collection via ajax.  
Main idea don't load collection via ajax and apply filters from bookmark on page load.

### Fixed Issues (if relevant)

1. magento/community-features/issues/238: Don't trigger reload of ui listing at page load

### Manual testing scenarios (*)

1. Open sales orders page
2. Look at page source
3. Page already contain items and totalRecords at ui config js

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-23 10:42 UTC, Den4ik commented
@magento give me 2.4-develop instance

2020-02-23 10:43 UTC, magento-engcom-team commented
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

2020-02-23 10:43 UTC, magento-engcom-team commented
Hi @Den4ik, here is your [Magento instance](https://i-26984-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26984-2-4-develop.instances.magento-community.engineering/admin_2304](https://i-26984-2-4-develop.instances.magento-community.engineering/admin_2304)
Login: `aa93c751` Password: `cfaf1f3a9f43`
Instance will be terminated in up to 3 hours.

2020-02-23 10:45 UTC, Den4ik commented
@magento give me test instance

2020-02-23 10:45 UTC, magento-engcom-team commented
Hi @Den4ik. Thank you for your request. I'm working on Magento instance for you

2020-02-23 10:46 UTC, magento-engcom-team commented
Hi @Den4ik, here is your [new Magento instance](https://pr-26984.instances.magento-community.engineering).
Admin access: [https://pr-26984.instances.magento-community.engineering/admin_6de5](https://pr-26984.instances.magento-community.engineering/admin_6de5)
Login: `85ca1fc3` Password: `54dffbc12d9f`
Instance will be terminated in up to 3 hours.

2020-03-27 15:16 UTC, Den4ik commented
@magento give me test instance

2020-03-27 15:16 UTC, magento-engcom-team commented
Hi @Den4ik. Thank you for your request. I'm working on Magento instance for you

2020-03-27 15:17 UTC, magento-engcom-team commented
Hi @Den4ik, here is your [new Magento instance](https://pr-26984.instances.magento-community.engineering).
Admin access: [https://pr-26984.instances.magento-community.engineering/admin_0457](https://pr-26984.instances.magento-community.engineering/admin_0457)
Login: `c3d7e228` Password: `77b4969eac65`
Instance will be terminated in up to 3 hours.

2020-05-28 11:22 UTC, Den4ik commented
@magento give me 2.4-develop instance

2020-05-28 11:23 UTC, magento-engcom-team commented
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

2020-05-28 11:24 UTC, magento-engcom-team commented
Hi @Den4ik, here is your [Magento instance](https://i-26984-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26984-2-4-develop.instances.magento-community.engineering/admin_075a](https://i-26984-2-4-develop.instances.magento-community.engineering/admin_075a)
Login: `7baf676f` Password: `bb065eee9bb0`
Instance will be terminated in up to 3 hours.

2020-05-28 11:35 UTC, Den4ik commented
@magento run all tests

2020-06-15 18:58 UTC, Den4ik commented
@magento give me 2.4-develop instance

2020-06-15 18:58 UTC, magento-engcom-team commented
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

2020-06-15 19:00 UTC, magento-engcom-team commented
Hi @Den4ik, here is your [Magento instance](https://i-26984-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26984-2-4-develop.instances.magento-community.engineering/admin_e83e](https://i-26984-2-4-develop.instances.magento-community.engineering/admin_e83e)
Login: `d0c01603` Password: `332a683b908a`
Instance will be terminated in up to 3 hours.

2020-08-25 14:45 UTC, sidolov requested changes

2020-08-25 14:45 UTC, sidolov commented on app/code/Magento/Ui/Component/Filters/Type/AbstractFilter.php
> +        BookmarkManagementInterface $bookmarkManagement,
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.4/contributor-guide/backward-compatible-development/)

2020-08-25 14:45 UTC, sidolov commented on app/code/Magento/Ui/Component/Filters/Type/Select.php
> +        BookmarkManagementInterface $bookmarkManagement,
Please, inject new dependencies according to our [Backward Compatible Development Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

2020-08-25 14:45 UTC, sidolov commented on app/code/Magento/Ui/Model/BookmarkManagement.php
> +    private function getSearchCriteriaBuilderByNamespace($namespace): void
Please, add strict type

2020-08-25 15:32 UTC, Den4ik commented
@sidolov  yep, thanks. I hope to finish it soon

2020-09-17 10:15 UTC, gabrieldagama commented
@magento run all tests

2020-09-17 10:17 UTC, gabrieldagama commented
Hi @Den4ik, can you address the comments from @sidolov? Please let us know if you need any help.

2020-09-17 19:56 UTC, Den4ik commented
Hi @gabrieldagama I plan continue to work on this feature on next week and change current implementations

2020-09-24 09:25 UTC, gabrieldagama commented
Hi @Den4ik, cool! Thanks for contributing, let me know if you need support on this.

2020-09-28 12:56 UTC, engcom-Echo commented
Hi, @Den4ik are you going to continue progress on that? Thanks!

2020-09-28 12:58 UTC, Den4ik commented
Hi @engcom-Echo 
I'm on it now

2020-10-01 11:53 UTC, Den4ik commented
@magento run all tests

2020-10-01 12:49 UTC, Den4ik commented
@magento run all tests

2020-10-05 10:12 UTC, Den4ik commented
@magento run Unit Tests

2020-10-05 10:55 UTC, sivaschenko commented
@magento run Unit Tests

2020-10-05 10:56 UTC, sivaschenko commented
@Den4ik restarted unit tests after referencing Adobe Stock Integration PR in description: this is required for builds to use ASI code from the PR

2020-10-05 12:03 UTC, Den4ik commented
@magento run Static Tests

2020-10-05 12:03 UTC, Den4ik commented
@magento run Functional Tests CE

2020-10-12 17:18 UTC, gabrieldagama commented
@magento run all tests

2020-10-12 18:31 UTC, Den4ik commented
@gabrieldagama I'll add some fixes tomorrow

2020-10-13 08:54 UTC, gabrieldagama requested changes
@Den4ik just moving this to the right state as you will provide the tests fixes.

2020-10-19 20:57 UTC, Den4ik commented
@magento run Static Tests

2020-10-19 23:11 UTC, Den4ik commented
@magento run all tests

2020-10-23 14:59 UTC, Den4ik commented
@magento run all tests

2020-10-24 00:25 UTC, Den4ik commented
@magento run all tests

2020-10-24 01:44 UTC, Den4ik commented
@magento run all tests

2020-10-24 08:16 UTC, Den4ik commented
@magento give me 2.4-develop instance

2020-10-24 11:54 UTC, Den4ik commented
@magento run all tests

2020-11-19 14:31 UTC, engcom-Foxtrot commented
Hello, @Den4ik. Please fix the MFTF test failures. We cant help you as we have no access to magenius-team repository.

2020-11-19 20:33 UTC, Den4ik commented
> Hello, @Den4ik. Please fix the MFTF test failures. We cant help you as we have no access to magenius-team repository.

Hi @engcom-Foxtrot I hope I'll have time on weekends

2020-11-26 12:26 UTC, Den4ik commented
@magento run Functional Tests

2020-11-26 12:27 UTC, Den4ik commented
@magento run Functional Tests CE

2020-12-08 11:01 UTC, engcom-Foxtrot commented
Hello, @Den4ik. Are you going to continue with this PR?

2020-12-08 11:55 UTC, Den4ik commented
> Hello, @Den4ik. Are you going to continue with this PR?

Yep. I'm still in progress

2020-12-16 21:02 UTC, Den4ik commented
@magento run all tests

2020-12-16 21:07 UTC, Den4ik commented
@magento run all tests

2020-12-23 12:08 UTC, Den4ik commented
@magento run all tests

2021-01-11 12:29 UTC, engcom-Foxtrot commented
Hello, @Den4ik. Would you like to continue with this PR? We may close it due to inactivity.

2021-01-11 19:20 UTC, Den4ik commented
Hi @engcom-Foxtrot Yes, I didn't have time to finish it due to my work, but I'm finally finishing this PR.

2021-01-26 10:15 UTC, engcom-Foxtrot commented
Hello, @Den4ik. We should close this PR due to inactivity. Are you going to proceed with it?

2021-02-01 12:32 UTC, engcom-Foxtrot commented
Hello, @Den4ik.
We are closing this PR as we have no write access to https://github.com/magenius-team/magento2.
We will continue with it in https://github.com/magento/magento2/pull/31919. If you want to push some updates, please do it in https://github.com/magento/magento2/pull/31919.

2021-02-01 12:33 UTC, closed without merging