Coverage checkout email component by jasmine test
magento/magento2 pull request #26983
Opened 2020-02-23 10:00 UTC by mrtuvn

### Description (*)

Current we don't have test for this component so i created new one
### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2020-04-20 17:28 UTC, mrtuvn commented
@magento run all tests

2020-06-22 21:21 UTC, omiroshnichenko commented on dev/tests/js/jasmine/tests/app/code/Magento/Checkout/frontend/js/view/form/element/email.test.js
> +        obj;
Please, move this section, beforeEach, and afterEach in describe section.

2020-06-22 21:22 UTC, omiroshnichenko commented on dev/tests/js/jasmine/tests/app/code/Magento/Checkout/frontend/js/view/form/element/email.test.js
> +            });
These checks could be skipped since they are covered in the parent class

2020-06-22 21:23 UTC, omiroshnichenko requested changes
See comments

2020-06-23 00:51 UTC, mrtuvn commented
@omiroshnichenko thanks for your review
How can i write cover test case for callback checkEmailAvailability

2020-06-23 03:06 UTC, closed without merging