MFTF FIX: Remove Customer by e-mail does not filter by e-mail
magento/magento2 pull request #27000
Opened 2020-02-25 02:34 UTC by lbajsarowicz

### Description (*)
Currently, this Action Group works by coincidence. When there's more than 1 Customer, it's going to remove the first one that is displayed in grid.

### Related Pull Requests

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Create 2 Customers with MFTF
2. Remove 2nd by its e-mail
3. Expect 1st one is untouched.

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-25 14:02 UTC, ihor-sviziev submitted a review, later dismissed

2020-02-25 14:04 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6976](https://jira.corp.magento.com/browse/ENGCOM-6976) has been created to process this Pull Request

2020-03-09 13:44 UTC, lbajsarowicz commented
Bump! Can this be merged?

2020-03-11 10:01 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-03-15 20:11 UTC, slavvka commented
@magento run Functional Tests EE

2020-03-16 05:34 UTC, slavvka commented
@lbajsarowicz Hey, the same EE MFTF test is failing al the time. Looks like it may be related to your code change

2020-03-16 05:35 UTC, slavvka requested changes
Please look at my comment

2020-03-16 08:50 UTC, lbajsarowicz commented
@slavvka but my change is related with admin panel. The test that fails is on front-end. What is more, the failing test is just related with missing cron run :-)

2020-03-16 11:04 UTC, lbajsarowicz commented
@magento run all tests
:man_facepalming: :man_facepalming: :man_facepalming:

2020-03-16 15:40 UTC, slavvka commented
@lbajsarowicz I do understand that it's weird. But I have reran the builds around 10 times and al the time there were failing on your PR :(

2020-03-16 15:43 UTC, lbajsarowicz commented
This is exactly the same as the situation that took place in January.
When I fix 1 Functional Test, others will fail.

2020-03-18 05:21 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2020-03-18 10:53 UTC, lbajsarowicz commented
The failing tests are fixed in separate PR: https://github.com/magento/magento2-page-builder/pull/408

2020-03-19 21:05 UTC, lenaorobei commented
@magento run all tests

2020-03-20 14:16 UTC, lenaorobei approved these changes

2020-03-20 14:18 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-6976](https://jira.corp.magento.com/browse/ENGCOM-6976) has been created to process this Pull Request

2020-03-23 09:27 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-03-23 12:12 UTC, engcom-Echo commented
@magento run all tests

2020-03-23 14:39 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-03-25 17:32 UTC, merged