magento/magento2#22273: M2 catalogrule_product__temp Tables
magento/magento2 pull request #27012
Opened 2020-02-25 16:56 UTC by quisse

### Description (*)
Make sure temporary tables always get cleaned up, even on faillure.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#22273

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-25 20:12 UTC, kandy requested changes
I believe there is a drawback to your fix.
After your changes, the index table will be cleaned up if any exception happens 

Better to modify IndexerTableSwapper class to:
 -  Create a temporary table instead of real  in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogRule/Model/Indexer/IndexerTableSwapper.php#L50
 - or/and cleanup temporary table in class destructor

2020-02-27 02:23 UTC, kandy requested changes

2020-02-27 02:23 UTC, kandy commented on app/code/Magento/CatalogRule/Model/Indexer/IndexerTableSwapper.php
>                  $temporaryTableName,
Can I ask you slightly improve this 
```suggestion
       $this->resourceConnection->getConnection()->createTemporaryTableLike(
            $temporaryTableName,
            $this->resourceConnection->getTableName($originalTableName)
        );
```

2020-02-27 09:02 UTC, quisse commented
The "Database Compare" (for example) build task failed. All reports available show success. Am I missing something? See:

- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27012/c6949b214931a7c9a68034e3765e4038/DatabaseCompare/b2b-skip-db-compare-report.html
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27012/c6949b214931a7c9a68034e3765e4038/DatabaseCompare/ce-db-compare-report.html
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27012/c6949b214931a7c9a68034e3765e4038/DatabaseCompare/ce-skip-db-compare-report.html
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27012/c6949b214931a7c9a68034e3765e4038/DatabaseCompare/ee-db-compare-report.html
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27012/c6949b214931a7c9a68034e3765e4038/DatabaseCompare/ee-skip-db-compare-report.html

2020-04-22 10:52 UTC, hostep commented
What's the status here? Just saw an error:
```
Table 'catalogrule_product__temp8f30230c' doesn't exist, query was: SHOW CREATE TABLE `catalogrule_product__temp8f30230c
```
happening on a shop during `bin/magento setup:upgrade` (shop was upgraded to Magento 2.3.5 yesterday).

Will this PR fix this problem?

2020-07-09 12:57 UTC, quisse commented
@kandy please, any response would be appreciated.

2020-08-05 07:00 UTC, santibm commented
hi, what's the status of this!? it's happening now on two customer sites heavily using catalog rules, @quisse does your fix work?!

2020-08-05 17:43 UTC, engcom-Charlie commented
Hi @quisse, could you please look through failed tests?

2020-08-05 18:12 UTC, quisse commented
@engcom-Charlie Please read previous comment.

2020-08-05 20:52 UTC, kandy submitted a review, later dismissed

2020-08-06 07:49 UTC, engcom-Alfa requested changes
Hi @quisse   .
     Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated test.
Thanks!

2020-08-19 09:12 UTC, engcom-Charlie commented
@magento run all tests

2020-08-26 08:53 UTC, MarienLbc commented
Hello!
As I am facing this issue in my project, I tried this patch on my dev environment and it looks some tables are dropped after catalogrule_rule index execution. FYI tables are : 
- catalogrule_group_website
- catalogrule_product
- ​catalogrule_product_price
I'm taking a look at it :eyeglasses:

2020-08-26 09:13 UTC, quisse commented
- Database Compare fails -> everything has success
- Functional Tests fails -> doesn't seem to be impacted by my change
- Integration Tests fails -> only warnings?
- Sample Data Tests fails -> "No build reports available"
- WebAPI Tests fails -> everything has success

Do you guys know how bad the [DX](https://medium.com/swlh/what-is-dx-developer-experience-401a0e44a9d9) is when trying to contribute to this OS project?

2020-08-26 09:50 UTC, engcom-Charlie commented
Hi @quisse, can you please merge mainline into your branch and re-run tests?
Thank you.

2020-08-26 12:12 UTC, quisse commented
@magento run all tests

2020-08-27 07:45 UTC, quisse commented
@engcom-Charlie Done, but still same test results.

2020-08-27 07:51 UTC, engcom-Charlie commented
@magento run all tests

2020-09-03 19:54 UTC, quisse commented
Same result, over and over...
This makes contributing quite unpleasant imho.

2020-09-17 10:15 UTC, quisse commented
![image](https://media.giphy.com/media/5x89XRx3sBZFC/giphy.gif)

2020-09-18 07:29 UTC, ihor-sviziev commented
@magento run all tests

2020-09-18 08:55 UTC, ihor-sviziev commented
@sidolov could you provide why some builds are failing without reports available?

2020-09-22 15:05 UTC, sidolov commented
```
....Error in fixture: "\/var\/www\/html\/dev\/tests\/integration\/testsuite\/Magento\/CatalogRule\/_files\/rule_apply_as_percentage_of_original_not_logged_user.php".
 Catalog rule indexing failed. See details in exception log.
 #0 /var/www/html/dev/tests/integration/testsuite/Magento/CatalogRule/_files/rule_apply_as_percentage_of_original_not_logged_user.php(43): Magento\CatalogRule\Model\Indexer\IndexBuilder->reindexFull()
#1 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/AbstractDataFixture.php(87): require('/var/www/html/d...')
#2 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/AbstractDataFixture.php(121): Magento\TestFramework\Annotation\AbstractDataFixture->_applyOneFixture()
#3 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(35): Magento\TestFramework\Annotation\AbstractDataFixture->_applyFixtures()
#4 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTestTransactionRequest()
#5 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array()
#6 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(76): Magento\TestFramework\EventManager->fireEvent()
#7 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests()
#8 [internal function]: Magento\TestFramework\Event\Transaction->startTest()
#9 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array()
#10 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(127): Magento\TestFramework\EventManager->fireEvent()
#11 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(407): Magento\TestFramework\Event\PhpUnit->startTest()
#12 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(624): PHPUnit\Framework\TestResult->startTest()
#13 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(772): PHPUnit\Framework\TestResult->run()
#14 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(639): PHPUnit\Framework\TestCase->run()
#15 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(639): PHPUnit\Framework\TestSuite->run()
#16 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(639): PHPUnit\Framework\TestSuite->run()
#17 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(639): PHPUnit\Framework\TestSuite->run()
#18 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(653): PHPUnit\Framework\TestSuite->run()
#19 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(108): PHPUnit\TextUI\TestRunner->run()
#20 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(68): PHPUnit\TextUI\Command->run()
#21 /var/www/html/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#22 {main}
```

2020-09-22 15:13 UTC, ihor-sviziev commented
@sidolov ok, could you also provide info from exception log?

2020-09-22 18:56 UTC, sidolov commented
@ihor-sviziev 
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2_prod.catalogrule_product__tempc886e889' doesn't exist, query was: RENAME TABLE catalogrule_product TO catalogrule_product34959eff,catalogrule_product__tempc886e889 TO catalogrule_product,catalogrule_product_price TO catalogrule_product_price33f11c26,catalogrule_product_price__temp1611874b TO catalogrule_product_price,catalogrule_group_website TO catalogrule_group_website310d948a,catalogrule_group_website__tempbaba801f TO catalogrule_group_website
```

2020-09-22 19:00 UTC, ihor-sviziev requested changes
Hi @quisse,
Seems like your change broke indexation mechanism, you can see the error that appeared here https://github.com/magento/magento2/pull/27012#issuecomment-696916060

Could you review and fix this issue?

2020-09-30 07:26 UTC, engcom-Charlie commented
Hi @quisse, can you please look at https://github.com/magento/magento2/pull/27012#pullrequestreview-493760614? Otherwise, we can't proceed with your PR.
Thank you.

2020-09-30 07:34 UTC, quisse commented
It's almost been **half a year** since I worked on this PR. It took **half a year** to get proper feedback. I've been quite patient from my side. I would appreciate it if you guys now are also patient. I do this in my spare time.

2020-09-30 07:58 UTC, ihor-sviziev commented
Hi @quisse,
👍 Sure, no rush at all

2020-10-17 11:03 UTC, quisse commented
@magento run all tests

2020-10-17 15:59 UTC, quisse commented
@magento run all tests

2020-10-17 16:21 UTC, quisse commented
Updated the solution to be without temporary tables but with a cleanup afterwards because the "temporary" tables are swapped to non temporary tables.
I'm not sure if the destructor call needs to be tested?

2020-10-17 17:12 UTC, quisse commented
@magento run all tests

2020-10-19 08:11 UTC, ihor-sviziev commented
@magento run Integration Tests, Functional Tests B2B

2020-10-19 08:13 UTC, ihor-sviziev commented
@magento run Performance Acceptance Tests

2020-10-19 19:44 UTC, ihor-sviziev commented
Seems like test failures not related to changes from this PR. Let’s wait a bit and restart tests again

2020-10-20 14:37 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Integration Tests

2020-10-20 19:38 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2020-10-20 20:21 UTC, quisse commented
Feels like a lottery, isn't it? 🙈😅

2020-10-20 20:24 UTC, ihor-sviziev commented
There were some fixes in related repositories, so tests should be fixed already

2020-10-21 03:55 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2020-10-21 09:49 UTC, quisse commented
@magento run Functional Tests B2B

2020-10-21 13:18 UTC, ihor-sviziev commented
@quisse could you merge recent changes from 2.4-develop? Maybe that's causing test failures?

2020-10-21 14:56 UTC, ihor-sviziev commented
@magento run all tests

2020-10-22 12:26 UTC, ihor-sviziev approved these changes

2020-10-22 12:28 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8367](https://jira.corp.magento.com/browse/ENGCOM-8367) has been created to process this Pull Request

2020-11-30 22:13 UTC, ihor-sviziev commented
@engcom-Alfa any updates on testing this PR?

2021-02-11 16:05 UTC, jordanngamba approved these changes

2021-04-06 10:49 UTC, stefandoorn commented
This change will still leave temporary tables in case Magento hit a PHP memory limit, which is not that hard in Magento landscape. Maybe the indexer should start by cleaning up old tables, instead of doing it in the destructor.

2021-04-06 12:42 UTC, ihor-sviziev commented
@stefandoorn, that's actually another use case. From my perspective - this solution is good enough to be tested and merged. If you have a better solution - please send a Pull Request, we'll review it

2021-04-07 09:46 UTC, stefandoorn commented
Yeah, sorry, wasn't meant to discard this PR. It's indeed another use case to keep in mind :-)

2021-04-08 19:23 UTC, merged

2021-04-08 19:26 UTC, vzabaznov commented
Hey @quisse, the Performance team took care of your PR. Thank you for your contribution.