magento/magento2#26112: mutation createEmptyCart doesn't throw exception when authorization header is set and token has expired
magento/magento2 pull request #27053
Opened 2020-02-27 13:01 UTC by engcom-Charlie

### Description (*)

Mutation createEmptyCart throws an exception when the authorization header is set and the token has expired and covered by a test.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#26112: mutation createEmptyCart doesn't throw exception when authorization header is set and token has expired

### Manual testing scenarios (*)

Please see https://github.com/magento/magento2/issues/26112

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-11 13:34 UTC, gabrieldagama reviewed
Hi @engcom-Charlie, thanks for the PR! Can you update this PR with the mainline? Also, regards the issue, my understanding is that we may want to return an error to the user in case of an expired/revoked token, at the moment if we set the userId as 0, it would still create the guest cart because of this:
`app/code/Magento/QuoteGraphQl/Model/Resolver/CreateEmptyCart.php`
```
        $maskedQuoteId = (0 === $customerId || null === $customerId)
            ? $this->createEmptyCartForGuest->execute($predefinedMaskedQuoteId)
            : $this->createEmptyCartForCustomer->execute($customerId, $predefinedMaskedQuoteId);
```

Please let me know your thoughts on this, thanks.

2020-08-21 19:17 UTC, sidolov requested changes

2020-08-21 19:17 UTC, sidolov commented on app/code/Magento/Webapi/Model/Authorization/TokenUserContext.php
> +    protected function processRequest(): void
Such change is backward incompatible, please revert

2020-08-21 19:17 UTC, sidolov commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/GetCustomerCartTest.php
>      protected function setUp()
Should have return type void

2020-08-21 19:17 UTC, sidolov commented on app/code/Magento/Webapi/Model/Authorization/TokenUserContext.php
> +    private function validateToken(Token $token): void
I don't see any validation here. Validators should return true or false result according to the checks. Please, inline this code or rename the method.

2025-01-06 10:54 UTC, engcom-Charlie commented
In order to work on this PR, I have tried to reproduce the issue on latest magento 2.4-develop with follow mentioned steps and found that the issue is not reproducible. With the expired customer token, empty cart by using customerCart is not getting created. Hence closing this PR now.

1. Generate Customer token
2. Wait for token expiration
3. Create an empty cart using the expired token, used customerCart as createEmptyCart is deprecated now.
{
  customerCart{
    id
  }
}
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/f5ec3b6e-9ca4-459b-870d-9d7e37db6293" />

2025-01-06 10:54 UTC, closed without merging