Missing "RESTRICT" value to declarative schema foreign constraint
magento/magento2 pull request #27073
Opened 2020-02-28 15:36 UTC by textarea

### Description (*)
Added missing "RESTRICT" value to declarative schema foreign constraint

### Fixed Issues (if relevant)
1. magento/magento2#27072: Missing "RESTRICT" value to declarative schema foreign constraint

### Manual testing scenarios (*)
1. Create a table with a customer_id column that references customer_entity.entity_id column, and you want that Customers cannot be deleted if there are associated records in your table.
2. In your db_schema.xml you cannot set a value "RESTRICT" in onDelete constraint attribute.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-28 15:53 UTC, textarea commented
Sorry, commit #75ff570 should not be here.

2020-02-28 17:30 UTC, dmytro-ch reviewed
Hello @textarea, thank you for your contribution!
Could you please provide some information about the use case, when this type of constraint may be required and why the `NO ACTION` does not satisfy your needs?

2020-02-28 17:36 UTC, textarea commented
Hello @dmytro-ch,
for example we have customers with referenced balance table, based on their actions, if a customer get deleted also his balance history will get deleted.
We want to prevent customer deletion with a linked balance.
Databases support it...
Thanks.
p.s. also misses "SET DEFAULT" value..

2020-03-03 12:24 UTC, dmytro-ch requested changes
Hello @textarea, thank you for the details.
I guess, the `NO ACTION` should be suitable in this case.
Nonetheless, we still can provide `RESTRICT` and `SET DEFAULT` as possible values.

Could you please check the `Database Compare` test failures? There is an issue with the current solution.

Thank you!

2020-04-09 16:15 UTC, textarea commented
Hello  @dmytro-ch ,
I tried to re-run "database compare" test but it failed again, this is the response:
No build reports available
Unfortunately there's no build reports were generated. That may be caused by either infrastructure issues or fatal errors during the build run. Please address this issue to Community Engineering Team members.

i'm sorry but I don't know how to proceed.

2020-04-10 12:24 UTC, dmytro-ch commented
@magento run all tests

2020-06-10 18:11 UTC, dmytro-ch commented
I've tried to re-run the test couple of times, but the issue still present.
The missing build report may indicate that the test environment could not be initialized.

@textarea, could you please try to test your solution by installing the Magneto on a clean database from scratch? There might be an error during the initial installation process.

2020-07-10 06:17 UTC, dmytro-ch commented
Hello @textarea, I'm closing this PR due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

2020-07-10 06:17 UTC, closed without merging