Fixed issue - 27095
magento/magento2 pull request #27096
Opened 2020-02-29 11:09 UTC by dipeshrangani

### Preconditions (*)

1. Magento2.4-develop

### Reference issue (*)
#27095 

### Steps to reproduce (*)

1. Add to cart product
2. Goto mini cart and click on remove product

### Expected result (*)

![button-solution](https://user-images.githubusercontent.com/20924623/75606190-4eed4b80-5b10-11ea-887d-b488f3adf85d.png)

### Actual result (*)

![button-issue](https://user-images.githubusercontent.com/20924623/75606198-5e6c9480-5b10-11ea-9d17-c6c74368d9b9.png)

2020-02-29 14:06 UTC, rogyar commented
Hi @dipeshrangani. Thank you for your contribution. 

According to the [definition of done]()https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. I would suggest covering your fix using MFTF test. The test will check that the following selector `action-primary action-accept` is not present on the page (but `action primary action-accept'`).

Thank you!

2020-02-29 14:07 UTC, rogyar requested changes
Hi @dipeshrangani. Thank you for your contribution. 

According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. I would suggest covering your fix using MFTF test. The test will check that the following selector `action-primary action-accept` is not present on the page (but `action primary action-accept'`).

Thank you!

2020-03-02 07:53 UTC, dipeshrangani commented
@rogyar I have updated requested changes, please review.

2020-03-04 13:34 UTC, rogyar commented
Hi @dipeshrangani. I believe you don't need additional changes to your fix. As I wrote in my recent comment, you need to create an automated MFTF test that tests the new system behavior. You can check [this](https://github.com/magento/magento2/pull/27149) pull request as an example. It contains the fix itself and the automated test that verifies the fix.

2020-03-17 11:48 UTC, engcom-Echo commented
I will take care of test coverage.

2020-03-19 14:08 UTC, engcom-Echo commented
@magento run all tests

2020-03-23 10:50 UTC, rogyar requested changes

2020-03-23 10:50 UTC, rogyar commented on dev/tests/js/jasmine/tests/app/code/Magento/Ui/base/js/modal/confirm.test.js
> +
Could we remove this extra empty line, please?

2020-03-28 09:43 UTC, rogyar commented
@magento run all tests

2020-03-30 06:47 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-04-01 13:04 UTC, rogyar approved these changes

2020-04-01 13:05 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-7241](https://jira.corp.magento.com/browse/ENGCOM-7241) has been created to process this Pull Request

2020-04-07 06:56 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-04-07 11:14 UTC, engcom-Echo commented
@magenro run all tests

2020-04-07 11:32 UTC, engcom-Echo commented
@magento run all tests

2020-04-08 14:15 UTC, engcom-Echo commented
@magento run all tests

2020-04-10 05:55 UTC, engcom-Echo commented
@magento run all tests

2020-04-10 12:35 UTC, engcom-Echo commented
@magento run all tests

2020-04-13 08:51 UTC, rogyar commented
Hi @engcom-Echo. Thank you for the coverage. 

I believe the failing tests are not related to the current PR (they are fluky tests for Adobe Stock Integration).

2020-04-15 13:42 UTC, sivaschenko commented
Adobe Stock Integration tests are stabilized. Updated branch to rerun the tests

2020-04-15 13:43 UTC, sivaschenko commented
@magento run all tests

2020-05-15 06:52 UTC, engcom-Echo commented
Hi, @rogyar could you please approve it again?

2020-05-19 12:50 UTC, rogyar submitted a review, later dismissed

2020-05-19 12:51 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-7241](https://jira.corp.magento.com/browse/ENGCOM-7241) has been created to process this Pull Request

2020-06-17 17:39 UTC, VladimirZaets requested changes
Hi @dipeshrangani. Looks like the issue mentioned in PR is already fixed. Can you please verify it?

2020-06-18 07:33 UTC, engcom-Echo commented
Hi, @dipeshrangani, @VladimirZaets. I checked it again, and now this issue can't reproduce - an issue has been fixed. 

![image](https://user-images.githubusercontent.com/51681435/84990667-284e3180-b14e-11ea-9f32-ca48d1777594.png)

So, I'm closing this PR now due to an issue is fixed.
Please reopen and update if you wish to continue.
Thank you for your collaboration. :+1:

2020-06-18 07:33 UTC, closed without merging