Adding failure callback to ui file uploader
magento/magento2 pull request #27092
Opened 2020-02-29 10:21 UTC by bartoszkubicki

### Description (*)

`Magento_Ui` file uploader works fine, but recently when I have used it for custom file upload, if I had error while uploading file there was no info what happened. After debugging it turned out it was 413 from nginx, and next steps were clear (bumping post, upload and client body size). I think if we have an error we should get info in dev tools console.

`Magento_Downloadable` file uploader in adminhtml is heavily based on this uploader, so whole thing can be investigated and tested while creating downloadable product.
By the way, I had refactored formatting a little bit.

### Manual testing scenarios (*)

1. Open downloadable product form
2. Try to upload huge file exceeding nginx and php limitations (especially `client_max_body_size`)
3. There is no info, uploader just stops working.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-09 15:36 UTC, lenaorobei requested changes
Hi @bartoszkubicki!
Could you please address build failures.

2020-04-02 21:48 UTC, bartoszkubicki commented
@lenaorobei I have fixed some issue, but now I am stuck. Unit tests are marked as failed, but there is no info what exactly failed even if I visit allure report (and I am writing js not php!). 

Functional tests failed because of strange looking communicate - something about browser and selenium - but it doesn't seem to be connected to code changes.

Static tests are failed because of copy-paste in some module I didn't touched. What are we supposed to do with this one?

2020-06-02 20:53 UTC, lenaorobei commented
@bartoszkubicki sorry for the late response. I'm going to update your branch to see new build results. Most likely static failures are related to the es6.

2020-06-02 20:53 UTC, lenaorobei commented
@magento run all tests

2020-07-31 18:20 UTC, lenaorobei commented
@magento run Static Tests

2020-07-31 18:57 UTC, lenaorobei requested changes
Here is the build console log:
```
Error Message
Parsing error: The keyword 'let' is reserved
Stacktrace
line 78, col 13, Error - Parsing error: The keyword &apos;let&apos; is reserved
```

Please avoid the use of ES6 syntax. Thank you.

2020-07-31 19:14 UTC, bartoszkubicki commented
@lenaorobei Is there any reason why anyone should not use es6? Why there is such a statement in static test?

2020-07-31 19:45 UTC, lenaorobei commented
I think @DrewML is the best person to answer this question.

2020-08-14 20:44 UTC, sidolov commented
@magento create issue

2020-08-19 21:15 UTC, lenaorobei commented
Please fins the requested info here https://devdocs.magento.com/guides/v2.4/coding-standards/technical-guidelines.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=ECMAScript#10-javascript-js-application

2020-08-20 06:06 UTC, bartoszkubicki commented
@lenaorobei I was curious why such a standard is kept. ECMA 6 seems to be quite supported in all main browsers.

2020-08-20 15:11 UTC, lenaorobei commented
@bartoszkubicki historically this decision is was made to keep IE compatibility. Now it requires revision and reconsideration, but that's the rule for now.

2020-08-20 22:17 UTC, bartoszkubicki commented
@lenaorobei Didn't know that we are going to deal with such a archeology 
![](https://fwcdn.pl/nph/49468/2018/15430_1.7.jpg)

Corrected.

2020-08-21 13:52 UTC, lenaorobei commented
@magento run all tests

2020-08-25 13:46 UTC, lenaorobei commented
@bartoszkubicki this change caused static build failures https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27092/07579529c64ff7894d0e64a36f65607d/Statics/allure-report-b2b/index.html#suites/0441d6d921f4f55895c022b4645f9e29

2020-08-25 13:46 UTC, lenaorobei commented
@magento run Functional Tests CE

2020-08-25 20:29 UTC, bartoszkubicki commented
@lenaorobei I think I have reverted change causing 'org.eslint.newline-after-var', but I don't know which line causes the second error

2020-08-25 21:26 UTC, lenaorobei commented
@magento run all tests

2020-08-26 14:46 UTC, lenaorobei commented
Static tests continue failing with `org.eslint.no-shadow` rule.
Looks like it ie related to `'event' is already declared in the upper scope` in line 360.
Please refer to https://eslint.org/docs/rules/no-shadow

2020-09-06 18:21 UTC, bartoszkubicki commented
@magento run all tests

2020-09-08 14:24 UTC, lenaorobei commented
@magento run all tests

2020-09-14 09:51 UTC, gabrieldagama commented
@magento run all tests

2020-09-14 13:21 UTC, engcom-Echo commented on app/code/Magento/Ui/view/base/web/js/form/element/file-uploader.js
> +            // no option exists in file uploader for restricting upload chains to single files; this enforces that policy
Line is too long

2020-09-14 21:14 UTC, lenaorobei commented
@magento run all tests

2020-09-16 08:55 UTC, engcom-Echo commented
Hi, @bartoszkubicki. Please note, the new changes should be covered by an appropriate autotest. Can you cover a test for your changes?

2020-09-16 20:58 UTC, bartoszkubicki commented
@engcom-Echo I have never written any tests for js files. Can you show me example? Is it some js unit test?

2020-09-17 05:10 UTC, engcom-Echo commented
@bartoszkubicki  exactly. Example for your case : 
File - app/code/Magento/Ui/view/base/web/js/form/element/file-uploader.js
Test - dev/tests/js/jasmine/tests/app/code/Magento/Ui/base/js/form/element/file-uploader.test.js

2020-10-02 14:46 UTC, gabrieldagama commented
@magento run all tests

2020-10-02 14:47 UTC, gabrieldagama approved these changes

2020-10-02 14:48 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8302](https://jira.corp.magento.com/browse/ENGCOM-8302) has been created to process this Pull Request

2020-10-03 07:32 UTC, bartoszkubicki commented
@gabrieldagama you were faster :) I was going to look at that this weeekend. So everything is ready?

2020-10-05 06:56 UTC, engcom-Hotel commented
@magento run all tests

2020-10-05 10:35 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
**Result** according **[Manual testing scenarios](https://github.com/magento/magento2/pull/27092#issue-381830547)**:
:x: **Before:**
![#27092Main](https://user-images.githubusercontent.com/51681379/95069343-3335cd80-070f-11eb-9c91-bddd387941b0.png)

:heavy_check_mark: **After:**
Additional information about error in dev console
![#27092PR](https://user-images.githubusercontent.com/51681379/95069364-3a5cdb80-070f-11eb-860e-94c254debaad.png)

2020-10-05 10:38 UTC, engcom-Delta commented
**Note:** Functional Tests B2B , Functional Tests CE and Functional Tests EE are failed

2020-10-05 11:01 UTC, gabrieldagama commented
The failing tests are not related to this PR.

2020-10-07 14:49 UTC, engcom-Delta commented
**Note:** Automation tests are passed

2020-10-07 23:18 UTC, merged

2020-10-08 08:27 UTC, bartoszkubicki commented
@lenaorobei Please back-port it to magento 2.3