Resolved Recently viewed products in Luma theme does not fit on scree…
magento/magento2 pull request #27097
Opened 2020-02-29 11:16 UTC by akash2008

### Description (*)
Using the "recently viewed products" widget on mobile will break the viewport and forcing sidescrolling.

The problem is even worse when using translated "add to cart" that make the button longer.

### Related Pull Requests

#27058 
### Fixed Issues (if relevant)

1. magento/magento2#27058 : Recently viewed products in Luma theme does not fit on screen

### Manual testing scenarios (*)

1. Add a new widget for "Recently viewed products"
2. Select Layout update "All pages" and container "Sidebar Main"
3. Visit some products in mobile view until the widget appears in mobile view

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-02 21:15 UTC, ptylek requested changes
Dear @akash2008 , please fix static tests, e.g. empty lines and spaces before curly braces

2020-03-05 07:17 UTC, akash2008 commented
@ptylek  I have updated the change as per request kindly review
Let me know if anything
Thank you

2020-03-05 08:30 UTC, ptylek requested changes
@akash2008 Thanks for fixing tests. I have checked this once again (also visually) and this also happens in Magento/blank theme. Could you also check for `block-viewed-products-grid` class and its width property for mobile and in sidebar? It seems that on mobile scenario width shouldn't split into grid and just be full-width. I checked this with other widgets like compare product or wishlist.

When width is 100% and not split like in normal grid -> maybe just scope it to sidebar? This solution might need some spacing adjustment like in other widgets
![image](https://user-images.githubusercontent.com/34317830/75962228-a9492c00-5ec3-11ea-8624-7cdce9f3ad0f.png)

Your solution breaks elements of other items in sidebar
![image](https://user-images.githubusercontent.com/34317830/75962349-e57c8c80-5ec3-11ea-86e7-1584c640d0c1.png)

Please consider different solution for that issue.

2020-03-05 08:30 UTC, ptylek commented on app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
> +            .product-item-info {
Add empty line before `.product-item-info`

2020-03-19 16:44 UTC, ptylek commented
@akash2008 I will close this PR for now due to inactivity, please reopen if you wish to continue your work.

2020-03-19 16:44 UTC, closed without merging