Resolved issue for Customer address is duplicated after setBillingAddressOnCart GraphQL mutation
magento/magento2 pull request #27107
Opened 2020-02-29 12:25 UTC by Aniket10Nov

### Description (*)

Resolved issue for Customer address is duplicated after setBillingAddressOnCart GraphQL mutation. If the customer set billing address is the same as the shipping address then it won't save as a new address.

### Related Pull Requests

#26884
### Fixed Issues (if relevant)

1. magento/magento2#26884 Customer address is duplicated after setBillingAddressOnCart GraphQL mutation.

### Manual testing scenarios (*)

Do all steps via GQL:

1. Authorize ( generateCustomerToken mutation)
2. Create cart (customerCart query)
3. Add product to cart (addSimpleProductsToCart mutation)
4. Set billing address (setBillingAddressOnCart mutation).
```
Important: save_in_address_book: true
input:{ 
   cart_id:"cart_id"   
   billing_address:{ 
      address:{ 
      ...
         save_in_address_book:true
      }
      same_as_shipping:true
   }
}
```

5. Set shipping method and payment method to the cart.
6. Place order (placeOrder mutation)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-29 14:44 UTC, rogyar requested changes

2020-02-29 14:44 UTC, rogyar commented on app/code/Magento/QuoteGraphQl/Model/Cart/SetBillingAddressOnCart.php
> +        $billingAddress = $this->createBillingAddress($context, $customerAddressId, $addressInput,$sameAsShipping);
Please, make sure you preserve the PSR code style and add whitespace before the argument

2020-03-04 13:29 UTC, rogyar commented
Hi @Aniket10Nov. According to the new [Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html), all new changes should be covered by automated tests. Since we don't have a GraphQl query for checking customer addresses, we are not able to cover this case using an API-functional test. 
But we have a possibility to perform a GraphQl request for setting the quote address and then use the repository or resource model to assert customer addresses using an integration test. Please, refer to the following test as an example.

2020-03-12 15:48 UTC, engcom-Charlie commented
Hi @Aniket10Nov it is M2 core issue, please see https://github.com/magento/magento2/issues/22596.

2020-03-16 14:29 UTC, prabhuram93 commented
Hi @Aniket10Nov , @rogyar! Our internal team has started working on this in the scope of MC-31586

2020-03-26 20:59 UTC, merged

2020-03-26 21:23 UTC, lenaorobei commented
Covered by tests internally.