Fixed DHL shipping #25192
magento/magento2 pull request #27100
Opened 2020-02-29 11:39 UTC by vrajesh-patel1993

### Description (*)

In Non-Document, we don't get the desired Allowed Methods:

### Fixed Issues (if relevant)

1. magento/magento2#25192: DHL Shipping

### Manual testing scenarios (*)

Content-type in the setting of DHL have two options

Document
Non-Document
But while we make a selection of Document we get the desired Allowed methods:

2020-02-29 13:25 UTC, gwharton commented
Product code N is a domestic product. The list of non-doc methods in magento is only used for dutiable international shipments. Domestic shipments ALWAYS use the "doc" allowed methods so it makes no sense to add product code N to non doc. Can you give me source/destination where you are ecpecting product codeN to be offered by DHL?

2020-02-29 13:28 UTC, vrajesh-patel1993 commented
> Product code N is a domestic product. The list of non-doc methods in magento is only used for dutiable international shipments. Domestic shipments ALWAYS use the "doc" allowed methods so it makes no sense to add product code N to non doc. Can you give me source/destination where you are ecpecting product codeN to be offered by DHL?

Hi
I have no any exact source/destination where especting product codeN to be offered by DHL

2020-02-29 13:29 UTC, vrajesh-patel1993 commented
> > Product code N is a domestic product. The list of non-doc methods in magento is only used for dutiable international shipments. Domestic shipments ALWAYS use the "doc" allowed methods so it makes no sense to add product code N to non doc. Can you give me source/destination where you are ecpecting product codeN to be offered by DHL?
> 
> Hi
> I have no any exact source/destination where especting product codeN to be offered by DHL

Let me know if you have have any suggestion on this to make any require changes

2020-02-29 13:31 UTC, gwharton commented
@maddyBoy please provide source/destination countries/regions where you are expecting to be offered code N so i can check.

2020-03-09 15:39 UTC, lenaorobei requested changes
Hi @vrajesh-patel1993. Do you have any updates regarding the question from @gwharton?

2020-03-24 14:25 UTC, lenaorobei commented
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

2020-03-24 14:25 UTC, closed without merging