Fixed issue of duplicate message on whishlist
magento/magento2 pull request #27105
Opened 2020-02-29 12:03 UTC by deep701

### Description (*)
When adding a product from wishlist to cart, alert messages are displaying more than once.
The number of alert messages is equal to the number of custom options.

1) Alert messages will be shown for individual products.
2) Have resolved the issue of number of message equal to the number of custom options. So now only single error message will be shown for particular product even after product has multiple custom options.

### Fixed Issues (if relevant)

1. magento/magento2#26898: Alert Message On Product Page

### Manual testing scenarios (*)
1. Add products with required custom options to the wishlist.
2. Add the product from wishlist to cart.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-29 14:28 UTC, rogyar requested changes
Hi @deep701. Thank you for your collaboration. Please, check my comments below for minor improvements. Also, according to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered using automated tests. I would kindly ask you to cover your fix using MFTF test. 

Thank you!

2020-02-29 14:28 UTC, rogyar commented on app/code/Magento/Catalog/Model/Product/Type/AbstractType.php
> - * @api
Please, do not remove the `@api` directive. It's an important marker for backward compatibility checks.

2020-02-29 14:28 UTC, rogyar commented on app/code/Magento/Catalog/Model/Product/Type/AbstractType.php
> +                        $path = DriverInterface::getParentDirectory($dst);
Please, do not use static calls for non-static methods.

2020-02-29 14:28 UTC, rogyar commented on app/code/Magento/Catalog/Model/Product/Type/AbstractType.php
> +                        if ((empty($src) || empty($dst) || !$uploader->receive($src)) && isset($queueOptions['option'])) {
Please, make sure the line length does not exceed 120 characters.

2020-03-13 07:56 UTC, engcom-Echo commented
I will take care of test coverage.

2020-03-17 11:42 UTC, engcom-Echo commented
These changes badly affect the ability to create an order with the file option in the Admin panel.

![image](https://user-images.githubusercontent.com/51681435/76853014-317ce900-6855-11ea-881f-9e9c151c5ec7.png)

2020-06-09 13:30 UTC, engcom-Echo commented
Hi @deep701, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-06-09 13:30 UTC, closed without merging