fix customer token issue in api (issue#27098)
magento/magento2 pull request #27110
Opened 2020-02-29 12:38 UTC by magecp

### Description (*)

Pass website id in the post to resolve this issue.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27098: Magento CE 2.3.X the swagger interface api named integrationCustomerTokenServiceV1 http scheme valid customer acess details entered and execute still server response is 401

### Manual testing scenarios (*)

1. Open the default Magento Swagger HTTP schemes or use this same API in postman.
2. Open integrationCustomerTokenServiceV1 interface to generate a token for customers.
3. Enter valid customer's details and check the response.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-02-29 14:06 UTC, lbajsarowicz requested changes
Please cover change with API functional test.

2020-02-29 14:09 UTC, lbajsarowicz requested changes
You cannot add required method argument to `@api`

2020-02-29 14:09 UTC, lbajsarowicz commented on app/code/Magento/Customer/Api/AccountManagementInterface.php
> +    public function authenticate($email, $password, $websiteId);
As it's `@api` you cannot add the extra required argument.

2020-06-16 07:14 UTC, engcom-Charlie commented
Hi @magecp, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-06-16 07:14 UTC, closed without merging