#27124: Update wishlist image logic to match logic on wishlist page
magento/magento2 pull request #27125
Opened 2020-03-02 16:50 UTC by mtbottens

### Description (*)

Updates image logic on the "Share wishlist" email to match the image logic in the my account wishlist page.

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

1. magento/magento2#27124: Share Wishlist Email: Image Logic Issue

### Manual testing scenarios (*)

1. Set Stores > Configuration > Sales > Checkout > Shopping Cart > Configurable Product Image = "Product Thumbnail Itself"
2. Add "Olivia 1/4 Zip Light Jacket" (Size = Medium, Color = Black) to wishlist
3. Navigate to wishlist page, and click the share wishlist button
4. Fill in the form
5. Share the wishlist
6. Observe that the wishlist email is using the configurable product image

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-03 09:29 UTC, eduard13 requested changes
Hi @mtbottens, thank you for your contribution. However, for me it looks like the problem isn't related only with the image, but with the product URL as well.
So, may I ask you to update also the URL that leads to product page to auto select the configurable attributes (exactly how we have it on Wishlist page)?

Thank you.

2020-03-03 13:08 UTC, mtbottens commented
Hey @eduard13, I've updated this pull request to handle the links as mentioned.

Thanks!

2020-03-03 21:00 UTC, eduard13 requested changes
Thank you for your updates, could you please check the review notes and update the code based on them?
Also, could you please fix the failing static tests as well?
Thank you.

2020-03-03 21:00 UTC, eduard13 commented on app/code/Magento/Wishlist/Block/Share/Email/Items.php
> +        ItemResolverInterface $itemResolver,
Could you please inject the new constructor dependency with a fallback to the ObjectManger?
https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter

2020-03-03 21:00 UTC, eduard13 commented on app/code/Magento/Wishlist/Block/Share/Email/Items.php
> +    /** @var ItemResolverInterface */
Please move the docblock to a new line.
```suggestion
    /**
     * @var ItemResolverInterface
     */
```

2020-03-03 21:00 UTC, eduard13 commented on app/code/Magento/Wishlist/Block/Share/Email/Items.php
> +        parent::__construct($context, $httpContext, $data, $config, $urlBuilder);
Please make sure that you call the parent construct first.
```suggestion
        parent::__construct($context, $httpContext, $data, $config, $urlBuilder);
        $this->itemResolver = $itemResolver;
```

2020-03-03 21:00 UTC, eduard13 commented on app/code/Magento/Wishlist/Block/Share/Email/Items.php
> +    public function getProductForThumbnail(Item $item) : Product
```suggestion
    public function getProductForThumbnail(Item $item): Product
```

2020-03-04 12:58 UTC, mtbottens commented
@eduard13 Thank you for the code review, I have made the requested changes.

2020-03-04 13:46 UTC, eduard13 requested changes
Thank you for the adjustment.
Could you please also fix these minor recommendations and fix the failing Static Tests?

2020-03-04 13:46 UTC, eduard13 commented on app/code/Magento/Wishlist/Block/Share/Email/Items.php
> +     * @return Product
```suggestion
     * @param Item $item
     *
     * @return Product
```

2020-03-04 13:46 UTC, eduard13 commented on app/code/Magento/Wishlist/Block/Share/Email/Items.php
> +     * @param \Magento\Catalog\Block\Product\Context $context
```suggestion
     * Items constructor.
     *
     * @param \Magento\Catalog\Block\Product\Context $context
```

2020-03-07 19:27 UTC, eduard13 approved these changes

2020-03-07 19:28 UTC, eduard13 commented
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

2020-03-07 19:28 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-7062](https://jira.corp.magento.com/browse/ENGCOM-7062) has been created to process this Pull Request

2020-03-10 08:00 UTC, engcom-Echo commented
@magento run all tests

2020-03-10 10:02 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-03-11 07:16 UTC, engcom-Echo commented
@magento run all tests

2020-03-13 07:51 UTC, engcom-Echo commented
@magento run all tests

2020-03-16 07:18 UTC, engcom-Echo commented
@magento run all tests

2020-03-18 14:24 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-03-19 08:11 UTC, merged