[WIP] Extracting MFTF tests in separate test files
magento/magento2 pull request #27154
Opened 2020-03-04 11:33 UTC by eduard13

### Description (*)

This PR extracts the MFTF tests into separate test files based on the [MFTF Best Practices](https://github.com/magento/magento-functional-tests-migration/wiki/Best-practices) for the following modules:
- Bundle
- Captcha
- Tax

Additionally, it also replaces the admin logging out `<amOnPage url="{{AdminLogoutPage.url}}" stepKey="logout"/>` action by `AdminLogoutActionGroup` action group.

### Related Pull Requests

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-04 12:22 UTC, lbajsarowicz commented
@eduard13 awesome! 
Keep going with other modules!

2020-03-04 19:53 UTC, lbajsarowicz requested changes
Could you also replace all the occurences of `LoginAsAdmin` in changed files to `AdminLoginActionGroup`?

Thanks!

2020-03-04 19:53 UTC, lbajsarowicz commented on app/code/Magento/ConfigurableProduct/Test/Mftf/Test/AdminConfigurableProductAddConfigurationTest.xml
> +            <actionGroup ref="LoginAsAdmin" stepKey="loginAsAdmin"/>
Use `AdminLoginActionGroup` instead.

2020-03-04 19:53 UTC, lbajsarowicz commented on app/code/Magento/ConfigurableProduct/Test/Mftf/Test/AdminConfigurableProductBulkDeleteTest.xml
> +            <actionGroup ref="LoginAsAdmin" stepKey="login"/>
Use `AdminLoginActionGroup` instead

2020-03-04 19:53 UTC, lbajsarowicz commented on app/code/Magento/ConfigurableProduct/Test/Mftf/Test/AdminConfigurableProductDisableAnOptionTest.xml
> +        <actionGroup ref="LoginAsAdmin" stepKey="loginAsAdmin"/>
Use `AdminLoginActionGroup` instead

2020-03-04 20:25 UTC, eduard13 commented
Hi @lbajsarowicz thank you for the suggestions, was planning to do that after finishing with all the modules.
Have the feeling that this process is never ending 😫.
Also planning to rename the test files to match the test that's inside (for those that I'm currently adjusting).

2020-03-04 20:28 UTC, lbajsarowicz commented
Don't change the names unless my PRs related to change Test names is merged, please.

2020-03-04 20:38 UTC, eduard13 commented
Agreed, thank you for letting me know.

2020-03-04 20:39 UTC, lbajsarowicz commented
@eduard13 The PRs I've mentioned:
* https://github.com/magento/magento2/pull/27118
* https://github.com/magento/magento2-page-builder/pull/399
* https://github.com/magento/partners-magento2ee/pull/151
* https://github.com/magento/partners-magento2b2b/pull/54
* https://github.com/magento/inventory/pull/2857

2020-03-09 06:56 UTC, eduard13 commented
Hi @lbajsarowicz, I'd like to proceed with the other modules in a separate PR, in order to provide these changes is a smaller bunches (also if there will be some conflicts, will be easier to manage them). What do you think?
Also, the failing tests don't look to be somehow related with the changes of this PR.

2020-03-09 07:30 UTC, lbajsarowicz commented
@eduard13 doing changes per module is the easiest way of doing major changes. 

My changes to action groups were waiting 7 months for review (single pr) so I split them per module and in 3 months - were merged 😀

The failed tests are not related to your changes

2020-03-15 06:53 UTC, closed without merging