Update MSRP price when dropdown attribute is changed
magento/magento2 pull request #27167
Opened 2020-03-05 04:56 UTC by ashokadewit

### Description 

The MSRP price is changed by triggering `updateMsrpPriceBlock`. This event is triggered in `mage.SwatchRenderer._OnClick` and in `mage.configurable._displayRegularPriceBlock`.

This pull request adds the trigger also to `mage.SwatchRenderer._OnChange`.

The _Onclick method is called when a visual swatch is clicked. The _OnChange method is called when a dropdown is changed.

### Fixed Issues

1. magento/magento2#27166: MSRP price is not updated when using dropdown instead of swatch

### Manual testing scenarios (*)
1. Enable MAP (Stores -> Configuration -> Sales -> Sales -> Minimum Advertised Price -> Enable MAP).
2. Create a configurable product
3. Create variations for two attributes. One of type "swatch", one of type "dropdown".
4. Assign different MSRP for the variations.
5. Go to product on the frontend click the swatches and change the dropdown.
6. Verify that the MSRP is changed when a swatch is clicked and when the dropdown is changed.

2020-03-05 06:28 UTC, ashokadewit commented
@magento give me test instance

2020-03-05 06:28 UTC, magento-engcom-team commented
Hi @ashokadewit. Thank you for your request. I'm working on Magento instance for you

2020-03-05 06:28 UTC, ashokadewit commented
@magento give me test instance

2020-03-05 06:28 UTC, magento-engcom-team commented
Hi @ashokadewit. Thank you for your request. I'm working on Magento instance for you

2020-03-05 06:28 UTC, magento-engcom-team commented
Hi @ashokadewit, here is your [new Magento instance](https://pr-27167.instances.magento-community.engineering).
Admin access: [https://pr-27167.instances.magento-community.engineering/admin_f4f8](https://pr-27167.instances.magento-community.engineering/admin_f4f8)
Login: `4f324de5` Password: `3b8e8e8eaa01`
Instance will be terminated in up to 3 hours.

2020-09-09 16:32 UTC, sidolov commented
Pull request successfully imported into `magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-27167`.

2020-09-14 19:32 UTC, sidolov requested changes
@ashokadewit could you please cover changes with automated test?

2020-09-29 20:05 UTC, sidolov commented
@ashokadewit  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-29 20:05 UTC, closed without merging