Magento 2.3.4 could not get category image name - 27168
magento/magento2 pull request #27178
Opened 2020-03-05 11:48 UTC by RHapani

### Description (*)
Fixed Category Image Url Bug.

### Steps to reproduce (*)

1. Create a Category and add an image to that category.
2. I need to display the category image of few categories based on id in homepage. So i have try to 
use the code in frontend as below,

`$category->getImageUrl()`
`$category->getImage()`

But it returns the tmp path image of that category.

I have even tried using the above codes for getting category image name in 
**vendor/magento/module-catalog/view/frontend/templates/category/image.phtml** but end up with getting wrong result.

### Expected result (*)
1.$category->getImageUrl() - It should return full path of category image({baseUrl}/pub/media/catalog/category/M2CAD.png)

2.$category->getImage()- It should return only the name of category image(M2CAD.png)

### Actual result (*)
1.Both the code returns temporary(tmp) path image of the category ({baseUrl}/pub/media/catalog/tmp/category/M2CAD.png)
2.Couldn't get the filename of the category image separately.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2[#27168](https://github.com/magento/magento2/issues/27168): Magento 2.3.4 could not get category image name

### Manual testing scenarios (*)

1. Get specific category object
2. print $categoryObj->getImageUrl();

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-12 05:32 UTC, miteshdhaduk commented
@lbajsarowicz Why merging is blocked? There is no issue with code customization.

2020-03-12 05:53 UTC, drpayyne commented
Irrespective of the failing tests, isn’t `$usingPathRelativeToBase` redundant here? Wouldn’t directly returning the condition check work?

2020-03-12 16:29 UTC, diazwatson requested changes
Hi @RHapani thanks for your contribution!

This is basically the change @drpayyne is suggesting. Please have a look.

BTW: I have heard this is your first contribution so welcome aboard 🎉!!!

2020-03-12 16:29 UTC, diazwatson commented on app/code/Magento/Catalog/Model/Category/Attribute/Backend/Image.php
> +        $usingPathRelativeToBase = strpos($fileUrl, $baseMediaDir) === 0;
```suggestion
        
```

2020-03-12 16:29 UTC, diazwatson commented on app/code/Magento/Catalog/Model/Category/Attribute/Backend/Image.php
> +        return $usingPathRelativeToBase;
```suggestion
        return strpos($fileUrl, $baseMediaDir) === 0;
```

2020-03-13 10:22 UTC, diazwatson requested changes

2020-03-13 10:22 UTC, diazwatson commented on app/code/Magento/Catalog/Model/Category/Attribute/Backend/Image.php
> +
```suggestion
```

2020-03-13 10:24 UTC, diazwatson approved these changes

2020-03-13 10:26 UTC, magento-engcom-team commented
Hi @diazwatson, thank you for the review.
[ENGCOM-7089](https://jira.corp.magento.com/browse/ENGCOM-7089) has been created to process this Pull Request
:eight_spoked_asterisk: @diazwatson, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-03-13 10:26 UTC, magento-engcom-team commented
@RHapani thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-04-02 11:10 UTC, engcom-Alfa requested changes
Hi @RHapani .
     Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automate test.
Thanks!

2020-05-01 22:12 UTC, closed without merging

2020-05-01 22:12 UTC, VladimirZaets commented
@RHapani , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration