26117: "Current user does not have an active cart" even when he actually has one
magento/magento2 pull request #27187
Opened 2020-03-06 07:31 UTC by engcom-Charlie

### Description (*)

I've changed the error message, also covered change by test. Old message `Current user does not have an active cart` was incorrect because it throws in case of a quote from a request isn't active, while the user can have another active cart.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#26117: "Current user does not have an active cart" even when he actually has one

### Manual testing scenarios (*)

Please see https://github.com/magento/magento2/issues/26117

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-06 17:49 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php
> +            throw new GraphQlNoSuchEntityException(__('This cart isn\'t active.'));
```suggestion
            throw new GraphQlNoSuchEntityException(__('The cart isn\'t active.'));
```

2020-03-06 17:49 UTC, lenaorobei requested changes
Please see my minor comment.

Functional build failures are not related tom this change.

2020-03-10 14:29 UTC, lenaorobei approved these changes

2020-03-10 14:31 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-7074](https://jira.corp.magento.com/browse/ENGCOM-7074) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-03-18 02:53 UTC, merged