resolved consistency error for merged indexer xml files
magento/magento2 pull request #27212
Opened 2020-03-09 16:01 UTC by philippsander

The allowed values in classType should be equal in unmerged and merged indexer.xml files

Allowing only letters and backspaces is wrong, since PHP-namespaces can also contain numbers.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-09 18:02 UTC, lbajsarowicz requested changes

2020-03-09 18:02 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Indexer/etc/indexer_merged.xsd
> +            <xs:pattern value="[a-zA-Z|\\]+[a-zA-Z0-9\\]+"/>
Is `\9ThClass` allowed?
https://regex101.com/r/bu1w2N/1/

2020-03-10 07:40 UTC, philippsander commented
@lbajsarowicz If you change it here you should also change the unmerged files

2020-03-26 08:41 UTC, philippsander commented
@lbajsarowicz 
I honestly don't see what update is needed here.

The pipeline will never be green since it's a global magento2 issue on ALL pull-requests

2020-03-26 08:47 UTC, lbajsarowicz commented
In my opinion, the regex should be: https://regex101.com/r/bu1w2N/2

2020-03-27 16:24 UTC, philippsander commented
@lbajsarowicz I agree, but with my merge request I was just trying to fix consitency error.

changing the regex would be too drastic

2020-03-29 20:25 UTC, lbajsarowicz commented
Actually I sat one longer moment to find out what's the right approach to this regex and we can even extend it:
https://regex101.com/r/bu1w2N/3

2020-08-17 18:18 UTC, sidolov commented
@magento create issue

2020-08-19 20:16 UTC, sidolov approved these changes

2020-08-19 20:17 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8038](https://jira.corp.magento.com/browse/ENGCOM-8038) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-08-31 13:30 UTC, philippsander commented
I don't get how I can push this forward. The checks won't execute.

2020-08-31 13:35 UTC, philippsander reviewed
Works

2020-08-31 17:52 UTC, lbajsarowicz approved these changes
✔️  Green from my side, although the change is not enough in my opinion.

2020-09-07 15:21 UTC, philippsander commented
The checks won't execute.
When will this be merged?

2020-09-07 15:23 UTC, lbajsarowicz commented
@magento run all tests.

2020-09-29 10:24 UTC, engcom-Alfa commented
Hi @lbajsarowicz @sidolov .
Could you put an appropriate label for test coverage?
Thanks!

2020-09-29 10:35 UTC, lbajsarowicz commented
@magento run all tests

2020-09-29 11:21 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a simple module with a vendor name which contains at least one number (ex. Cus2tom2)
2. Add a custom indexer to the module just like on the [devdocs](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing-custom.html)
3. Run in console: `php bin/magento setup:upgrade;`

**Before:** :heavy_multiplication_x: Invalid doc element "indexer" , attribute "class" ...

![Screenshot from 2020-09-29 14-02-19](https://user-images.githubusercontent.com/51679138/94551948-cb8b0880-025e-11eb-9f79-65cde8b634db.png)

**After:** :heavy_check_mark: Normal Upgrade output & module gets properly installed.

![Screenshot from 2020-09-29 14-07-26](https://user-images.githubusercontent.com/51679138/94552100-0856ff80-025f-11eb-9c19-b2ced3cd9f31.png)

2020-09-29 19:25 UTC, engcom-Golf commented
@magento run all tests

2020-09-30 09:29 UTC, engcom-Golf commented
@magento run all tests

2020-09-30 09:30 UTC, engcom-Golf commented
@magento run all tests

2020-11-03 17:07 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8038](https://jira.corp.magento.com/browse/ENGCOM-8038) has been created to process this Pull Request

2021-08-20 15:27 UTC, merged