magento/magento2#26749: Product flat table - Incorrect data
magento/magento2 pull request #27222
Opened 2020-03-10 08:40 UTC by engcom-Charlie

### Description (*)

Fixed product data has been inserted into an incorrect flat table. Covered by test.
### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#26749: Product flat table - Incorrect data

### Manual testing scenarios (*)

Please see https://github.com/magento/magento2/issues/26749

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-10 09:58 UTC, dmytro-ch requested changes
Hello @engcom-Charlie! Could you please also update the unit test?
Thank you!

2020-03-10 10:03 UTC, engcom-Charlie commented
> Hello @engcom-Charlie! Could you please also update the unit test?
> Thank you!

Hello @dmytro-ch, yes I'll do it.

2020-03-23 00:36 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-03-26 14:36 UTC, engcom-Charlie commented
Hello @ihor-sviziev, could You please make a review on this PR?

2020-03-26 16:30 UTC, dmytro-ch reviewed
Hello @engcom-Charlie, sorry for the late reply. I've missed the review request notification for some reason.
The result looks good to me.
Could you please just check the minor CR notice?

Thank you!

2020-03-26 16:30 UTC, dmytro-ch commented on app/code/Magento/Catalog/Model/Indexer/Product/Flat/Action/Row.php
> +        if (!isset($id) || $id === null) {
The `$id === null` condition is redundant in this case isn't it?

2020-03-26 17:28 UTC, dmytro-ch submitted a review, later dismissed

2020-03-26 17:29 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7211](https://jira.corp.magento.com/browse/ENGCOM-7211) has been created to process this Pull Request

2020-04-02 06:03 UTC, engcom-Echo commented
Hi, @engcom-Charlie will resolve conflict.

2020-04-02 11:00 UTC, engcom-Alfa requested changes
Hi @engcom-Charlie. Could you resolve merge conflicts?
Thanks!

2020-05-25 10:42 UTC, engcom-Echo commented
Close PR because this issue has already been fixed: https://github.com/magento/magento2/pull/27365

2020-05-25 10:42 UTC, closed without merging