#27175 Allows the user to enter in zero as a custom price
magento/magento2 pull request #27247
Opened 2020-03-11 15:31 UTC by Bal2018

### Description (*)

When adding a product to the basket , it was not possible to set a custom price of zero.
This was because zero is considered empty by PHP and this didn't pass a condition in the code.
 
### Fixed Issues (if relevant)

1. magento/magento2#27175: Unable to set custom price to 0 within a buy request

### Manual testing scenarios (*)
This can not be tested manually. 
Can only be tested programmatically by first allowing products to be added to the basket with a custom price. And then add a product to the basket with a custom price value of 0. 
See the issue for more information https://github.com/magento/magento2/issues/27175

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-12 14:01 UTC, Bal2018 commented
I was wandering if you could tell me why the code was failing the Functional Tests please.

2020-03-16 08:50 UTC, eduard13 requested changes
Hi @Bal2018, thank you for your contribution, could you please cover this fix by an automated test? You may adjust the following `\Magento\Quote\Test\Unit\Model\Quote\Item\ProcessorTest` with your case.

PS. The failing functional tests aren't related to your changes.
Thank you.

2020-03-16 08:53 UTC, eduard13 commented
@magento run all tests

2020-03-18 12:22 UTC, Bal2018 commented
Am working on the unit test . .. thanks

2020-03-21 19:08 UTC, eduard13 requested changes
Hi @Bal2018, thank you for the test coverage. Could you please review the comments below and fix them? Also, I suggest adding a description for all the methods, to avoid failing static tests.
After fixing, please squash all the commits into a single one, to have clean history.

Thank you.

2020-03-21 19:08 UTC, eduard13 commented on app/code/Magento/Quote/Test/Unit/Model/Quote/Item/ProcessorTest.php
> +    public function testPrepareWithCustomPrice()
Please provide a proper method description and change the method name with its actual case (I'd mention 0 as custom price).
Also, could you please add the return type.
```suggestion
    public function testPrepareWithCustomPrice(): void
```

2020-03-21 19:08 UTC, eduard13 commented on app/code/Magento/Quote/Test/Unit/Model/Quote/Item/ProcessorTest.php
> +            ->willReturn(0.00);
Please move the 0.00 to a constant, to avoid having magic numbers `private const STUB_CUSTOM_PRICE = 0.00`. Please do the same for QTY.

2020-03-23 12:11 UTC, Bal2018 commented on app/code/Magento/Quote/Test/Unit/Model/Quote/Item/ProcessorTest.php
> +            ->willReturn(0.00);
As the custom price and qty are specific to my test I have added them in my method and not made them constants.
I have rebased and there is only one commit showing now 
The code is ready for merge

2020-03-23 13:01 UTC, eduard13 commented on app/code/Magento/Quote/Test/Unit/Model/Quote/Item/ProcessorTest.php
> +    public function testPrepareWithCustomPrice()
Hi @Bal2018, please add the method description here.

2020-03-23 20:21 UTC, eduard13 approved these changes
The failing tests aren't related with these changes.

2020-03-23 20:25 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-7188](https://jira.corp.magento.com/browse/ENGCOM-7188) has been created to process this Pull Request

2020-03-23 20:25 UTC, magento-engcom-team commented
@Bal2018 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-03-26 11:53 UTC, Bal2018 commented
Hi @eduard13,  

Was just wandering why it hadn't been merged ?  Is there something else I need to do ?

2020-03-26 12:02 UTC, eduard13 commented
Hi @Bal2018, we'll let you know if anything will be needed from your side, for now this PR is pending for a new round of tests.
Thank you for patience.

2020-04-06 08:54 UTC, Bal2018 commented
Hello @eduard13  I was wandering when the PR will be ready to merge?

2020-05-07 11:11 UTC, engcom-Charlie commented
Hi @eduard13,
please review integration coverage.

2020-05-07 14:55 UTC, eduard13 submitted a review, later dismissed
Hi @engcom-Charlie, thank you for the coverage, looks good 👍.

2020-05-07 14:56 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-7188](https://jira.corp.magento.com/browse/ENGCOM-7188) has been created to process this Pull Request

2020-05-08 07:35 UTC, engcom-Charlie commented
:heavy_check_mark: QA Passed
**Before :** Add product to quote with buy request with `custom price = 0`, as a result, we have a product with regular price in cart.
**After :** Add product to quote with buy request with `custom price = 0`, as a result, we have a product with price 0 in cart.

2020-05-08 07:47 UTC, engcom-Charlie commented
The failing functional tests are not related to the changes in this pr.

2020-05-08 19:16 UTC, slavvka commented
Set on hold as it is not understood what is a use case here and if it has a value. Waiting for a decision from PO

2020-06-11 17:53 UTC, sdzhepa commented
Closed due to https://github.com/magento/magento2/issues/27175#issuecomment-642837694

2020-06-11 17:53 UTC, closed without merging