Clean expired quotes - Fix out of memory on huge quotes list
magento/magento2 pull request #27260
Opened 2020-03-12 09:07 UTC by ihor-sviziev

### Description (*)
On production we had a lot of expired quotes, and during cron run we were getting fatal error:
```
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /path/to/magento2/vendor/magento/framework/Model/AbstractModel.php on line 359

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

Investigation found that cron job `sales_clean_quotes` fails with out of memory because it tries to load all quote items at once

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-12 11:38 UTC, ihor-sviziev commented
I think it's a good idea to cover these changes with some test, but have no ideas which test will be ok there

2020-03-13 07:43 UTC, lbajsarowicz reviewed
If you wait for my pagination fix, your "for" loop with comment would no longer be needed and could be replaced with while.

2020-03-13 08:01 UTC, ihor-sviziev commented
Yeah, I know, but it works anyway with new and old version, so I decided to
keep it like that.

On Fri, 13 Mar 2020 at 09:43, Lukasz Bajsarowicz <notifications@github.com>
wrote:

> *@lbajsarowicz* commented on this pull request.
>
> If you wait for my pagination fix, your "for" loop with comment would no
> longer be needed
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/27260#pullrequestreview-374098800>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOJOUPJV5HJ6NMCAXFNLADRHHP2JANCNFSM4LGHSQXQ>
> .
>

2020-03-13 09:06 UTC, lbajsarowicz commented
The difference is that with while you continuously get the real amount of entries. With for - you get number of pages once and then iterate

2020-03-24 08:56 UTC, ihor-sviziev commented
Hi @lbajsarowicz,
Could you review my changes again? I covered them with integration test

2020-03-24 10:00 UTC, lbajsarowicz requested changes
Improve readability of Integration Tests, and we're :heavy_check_mark:

2020-03-24 10:00 UTC, lbajsarowicz commented on dev/tests/integration/testsuite/Magento/Sales/Cron/CleanExpiredQuotesTest.php
> +        $this->assertEquals(0, $totalCount);
Extract that to private method `assertQuotesCount(int $expectedCount)`

2020-03-24 10:00 UTC, lbajsarowicz commented on dev/tests/integration/testsuite/Magento/Sales/Cron/CleanExpiredQuotesTest.php
> +        $this->assertEquals(1000, $this->quoteCollectionFactory->create()->getSize());
`$this->assertQuotesCount(1000)`

2020-03-24 10:20 UTC, lbajsarowicz approved these changes
:heavy_check_mark: Great! Thank you for your contribution!

2020-03-24 10:21 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7193](https://jira.corp.magento.com/browse/ENGCOM-7193) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-03 19:53 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Tested with ~ 10000 expired quotes

Run: `php bin/magento cron:run`

**Before:**
![Screenshot from 2020-04-03 16-44-56](https://user-images.githubusercontent.com/51679138/78399599-dccfc100-75fd-11ea-8443-41d2a02cc7de.png)

**After:**
![Screenshot from 2020-04-03 16-59-52](https://user-images.githubusercontent.com/51679138/78399612-e35e3880-75fd-11ea-829e-dee49af7a3e7.png)

2020-04-03 19:55 UTC, ihor-sviziev commented
So maybe it’s better to adjust my integration test with bigger number of
quotes? Could you let me know from which amount it started failing, I’ll
just add it?

On Fri, 3 Apr 2020 at 22:53, Oleksii Stasiv <notifications@github.com>
wrote:

> ✔️ QA Passed
>
> Tested with ~ 10000 expired quotes
>
> Run: php bin/magento cron:run
>
> *Before:*
> [image: Screenshot from 2020-04-03 16-44-56]
> <https://user-images.githubusercontent.com/51679138/78399599-dccfc100-75fd-11ea-8443-41d2a02cc7de.png>
>
> *After:*
> [image: Screenshot from 2020-04-03 16-59-52]
> <https://user-images.githubusercontent.com/51679138/78399612-e35e3880-75fd-11ea-829e-dee49af7a3e7.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/27260#issuecomment-608629036>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOJOULEBBUYFKD4HCOWAW3RKY5FLANCNFSM4LGHSQXQ>
> .
>

2020-04-07 19:48 UTC, engcom-Alfa commented
@ihor-sviziev in my case, it started failing with 5000 expired quotes and more, with memory_limit=128M

2020-04-09 08:28 UTC, ihor-sviziev commented
@engcom-Alfa for now let's leave it as is, as increasing amount of quotes might cause fatal error in integration tests due to out of memory. Why - because there running also other tests that could leave some not cleaned memory

2020-05-22 19:49 UTC, sdzhepa commented
@magento create issue

2020-05-28 07:21 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-06-05 15:43 UTC, merged