#26288  Will now throw an exception when a customer does not exist wh…
magento/magento2 pull request #27269
Opened 2020-03-12 16:46 UTC by Bal2018

…o wants to reset password
 
### Description (*)

When a customer (who does not exist) requests a password reset - Magento will now throw an exception error. 
### Fixed Issues (if relevant)

1. magento/magento2#<26288>: missing Throw in copy pasted code

### Manual testing scenarios (*)
 
1. ...created a customer 
2. ...checked email sent for new customer
3. ...deleted customer details in DB
4. ...from email clicked on "reset password"
5. ...when email entered error message thrown

### Questions or comments 
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-12 23:04 UTC, lbajsarowicz commented
Nice catch. Let me help you with the description, but also I need you to improve code style (Static Tests)

2020-03-12 23:06 UTC, lbajsarowicz requested changes
Please correct the static tests.
Could you also add Unit Tests for that case, to avoid "losing that" in future*?

* Test coverage is part of Definition of Done.

2020-05-07 08:45 UTC, engcom-Echo commented
I will take care of test coverage.

2020-05-07 12:38 UTC, lbajsarowicz requested changes
@engcom-Echo Please review the comments.

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> + */
This annotation is not necessary :-)
You can also use `@covers` if you really need to express anything as class annotation.

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    protected const RESET_PASSWORD = 'resetPassword';
```suggestion
    private const RESET_PASSWORD = 'resetPassword';
```
Unit Tests are not expected to be inherited, use `private` instead

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    protected $searchCriteriaBuilderMock;
```suggestion
    private $searchCriteriaBuilderMock;
```

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    protected $searchCriteriaMock;
```suggestion
    private $searchCriteriaMock;
```

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    protected $customerRepositoryMock;
```suggestion
    private $customerRepositoryMock;
```

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    protected $searchResultMock;
```suggestion
    private $searchResultMock;
```

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    protected $customerMock;
```suggestion
    private $customerMock;
```

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    protected $model;
```suggestion
    private $model;
```

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +     */
```suggestion
```
No annotation needed

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    public function setUp()
```suggestion
    protected function setUp()
```
`setUp` method is `protected`. There is no reason to change it's visibility (refer: `\PHPUnit\Framework\TestCase::setUp`)

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +     */
```suggestion
```
This does not introduce any new information that is already in return type hint.

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +    public function testExecute(): void
This is not valid test method name - please be more descriptive with your method names - for example:
`testExecuteReturnsFalseWhenNoItemsAvailable` or `testExecuteIsNotBeingCalledWhenNoItemsAvailable`

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +            ->willReturn($totalCount);
If it does not matter how many the method is being called, this means it's **stub**, not **mock**. Then you should avoid `->expects()` at all.

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +            ->willReturn($totalCount);
If it does not matter how many the method is being called, this means it's stub, not mock. Then you should avoid ->expects() at all.

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +     */
```suggestion
```
This provides no additional value

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +     */
```suggestion
```
No additional value provided by docblock

2020-05-07 12:38 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Unit/Model/ForgotPasswordToken/GetCustomerByTokenTest.php
> +            ->willReturn($totalCount);
```suggestion
        $this->searchResultMock->method('getTotalCount')->willReturn($totalCount);
```
If it does not matter how many the method is being called, this means it's stub, not mock. Then you should avoid ->expects() at all.

2020-05-07 13:22 UTC, lbajsarowicz approved these changes
Awesome. Thank you!

2020-05-07 13:23 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7527](https://jira.corp.magento.com/browse/ENGCOM-7527) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-05-08 09:11 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-05-08 13:35 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-06-23 11:57 UTC, engcom-Echo commented
@magento run all tests

2020-06-25 07:56 UTC, engcom-Echo commented
@magento run all tests

2020-06-25 13:23 UTC, engcom-Echo commented
@magento run all tests

2020-06-26 07:23 UTC, engcom-Echo commented
@magento run all tests

2020-06-26 07:24 UTC, engcom-Echo commented
@magento run all tests

2020-06-26 07:28 UTC, engcom-Echo commented
Hi @Bal2018  I mistakenly closed PR.

2020-08-27 20:01 UTC, sidolov approved these changes

2020-08-27 20:02 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-7527](https://jira.corp.magento.com/browse/ENGCOM-7527) has been created to process this Pull Request

2020-09-01 06:31 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
**Result:**
No exception error is shown
![image](https://user-images.githubusercontent.com/51681379/91810020-cfaf1080-ec35-11ea-9b28-4f0cd4a76415.png)

2020-09-01 06:31 UTC, engcom-Delta commented
**Note:** Functional Tests EE and Integration Tests are failed

2020-09-01 06:54 UTC, engcom-Echo commented
@magento run all tests

2020-09-04 08:23 UTC, merged