Add "Admin" prefix to Test and ActionGroup
magento/magento2 pull request #27276
Opened 2020-03-13 01:57 UTC by lbajsarowicz

### Description (*)
Renamed both Test and Action Group to contain recommended prefix "Admin".
Also replaced manual actions to Action Groups.

### Related Pull Requests

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
CC: @okolesnyk 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-13 14:52 UTC, dmytro-ch submitted a review, later dismissed

2020-03-13 14:54 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7094](https://jira.corp.magento.com/browse/ENGCOM-7094) has been created to process this Pull Request

2020-03-17 08:48 UTC, engcom-Delta commented
@lbajsarowicz Could you resolve merge conflicts?

2020-03-17 08:53 UTC, engcom-Delta requested changes
@lbajsarowicz Could you resolve merge conflicts?

2020-03-17 09:18 UTC, lbajsarowicz commented
@engcom-Delta Done.

2020-03-17 10:40 UTC, dmytro-ch approved these changes

2020-03-17 10:41 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7094](https://jira.corp.magento.com/browse/ENGCOM-7094) has been created to process this Pull Request

2020-03-24 09:36 UTC, engcom-Delta commented
:heavy_check_mark: QA passed

2020-03-25 17:32 UTC, merged