Implement ActionInterface for /catalog/category/view
magento/magento2 pull request #27297
Opened 2020-03-15 20:58 UTC by lbajsarowicz

### Description (*)
This PR is example for **How to replace Abstract Action class with ActionInterface**

The performance change after:
![image](https://user-images.githubusercontent.com/1639941/76710476-20729180-6708-11ea-8c90-69c9920b4bb1.png)

### Related Pull Requests

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-15 22:28 UTC, lbajsarowicz commented
@magento run all tests

Tests failed due to relation with Magento Commerce. Changes to the plugin in Magento Commerce were introduced and now Tests should pass.

2020-03-15 23:23 UTC, lbajsarowicz commented
@magento run all tests

Adjusted code to follow the Coding Standards in Magento EE

2020-03-16 04:22 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,
According to test failures - looks like your change broke category page.
Please review them and adjust your changes

2020-03-16 09:57 UTC, lbajsarowicz commented
@ihor-sviziev I've introduced `strict_types` to the tests, that caused failures on types juggling.
The easies way is to rollback the `strict_types`. Later on, we need to review these tests and change the call arguments to be correct type.

2020-03-16 10:03 UTC, lbajsarowicz commented
@magento run all tests

@ihor-sviziev I've introduced `strict_types` to the tests, that caused failures on types juggling.
The easies way is to rollback the `strict_types`. Later on, we need to review these tests and change the call arguments to be correct type.

2020-03-16 15:57 UTC, lbajsarowicz commented
@magento run all tests

2020-03-17 20:36 UTC, ihor-sviziev commented
@magento run all tests

2020-03-18 14:20 UTC, lbajsarowicz commented
The issue
```
[2020-03-18 14:18:37] report.CRITICAL: Error: Call to undefined method Magento\Catalog\Controller\Category\View\Interceptor::getResponse() in /var/www/html/.ee/app/code/Magento/CatalogPermissions/Observer/ApplyCategoryPermissionObserver.php:109
Stack trace:
#0 /var/www/html/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(88): Magento\CatalogPermissions\Observer\ApplyCategoryPermissionObserver->execute(Object(Magento\Framework\Event\Observer))
#1 /var/www/html/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogPermissions\Observer\ApplyCategoryPermissionObserver), Object(Magento\Framework\Event\Observer))
#2 /var/www/html/.ee/app/code/Magento/Staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#3 /var/www/html/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('catalog_control...', Array)
#4 /var/www/html/app/code/Magento/Catalog/Controller/Category/View.php(232): Magento\Staging\Model\Event\Manager\Proxy->dispatch('catalog_control...', Array)
#5 /var/www/html/app/code/Magento/Catalog/Controller/Category/View.php(256): Magento\Catalog\Controller\Category\View->_initCategory()
#6 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Category\View->execute()
#7 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('execute', Array)
#8 /var/www/html/lib/internal/Magento/Framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure))
#10 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/html/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(26): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('execute', Array, Array)
#12 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(164): Magento\Catalog\Controller\Category\View\Interceptor->execute()
#13 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(98): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Controller\Category\View\Interceptor))
#14 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#16 /var/www/html/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#22 /var/www/html/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#24 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(260): Magento\Framework\App\Http\Interceptor->launch()
#25 /var/www/html/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#26 {main} [] []
```
is caused by B2B module. Addressing the issue

2020-03-18 14:53 UTC, lbajsarowicz commented
The problem with B2B is much much more complicated.
It's related with "Magic" observer that changes:
1. Category model after loading
2. Replaces the response

I need to redesign whole Observer (`app/code/Magento/CatalogPermissions/Observer/ApplyCategoryPermissionObserver.php`) into 2 plugins.


The funny fact is that this PR was to show how easy is to migrate from `AbstractAction` to `ActionInterface`. I forgot that there are people who do not follow the [most basic Magento rule](https://devdocs.magento.com/guides/v2.3/ext-best-practices/extension-coding/observers-bp.html) when developing Magento B2B.

2020-03-18 23:58 UTC, lbajsarowicz commented
@magento run all tests

2020-03-19 00:17 UTC, lbajsarowicz commented
@magento run all tests

Removed Unit Tests for Observer in EE module.

2020-03-19 01:45 UTC, lbajsarowicz commented
@magento run all tests
1. Added Unit Tests
2. Fixed Static Tests

2020-03-19 08:52 UTC, ihor-sviziev commented
@lbajsarowicz tests still failing, and it's not only one test, so seems like changes breaks functionality

2020-03-19 10:02 UTC, lbajsarowicz commented
I've done big changes to Magento commerce code. Still needs to be adjusted.

2020-03-19 14:40 UTC, lbajsarowicz commented
@magento run all tests

Fixed some more static tests. I'm not sure about the failure that is happening with the redirect - as Xdebug shows me that the default values for categories were changed somehow during the test (looks like 2 tests affecting each other). I'm going to investigate that during the night.

2020-03-19 23:56 UTC, lbajsarowicz commented
@magento run all tests

We need to redesign View controller :-1:

2020-03-20 01:08 UTC, lbajsarowicz commented
@magento run all tests

Changes to EE

2020-03-20 10:20 UTC, lbajsarowicz commented
@magento run all tests
CI took the old version of Commerce code.

2020-03-20 11:32 UTC, lbajsarowicz commented
@lenaorobei / @slavvka 

There's something wrong with CI:
![image](https://user-images.githubusercontent.com/1639941/77159999-c0cd0b00-6aa6-11ea-9762-5d054aefd390.png)

The code:
![image](https://user-images.githubusercontent.com/1639941/77160028-ccb8cd00-6aa6-11ea-9a1d-630f18ab3ec9.png)

2020-03-20 17:12 UTC, lbajsarowicz commented
@magento run all tests

2020-03-21 07:26 UTC, ihor-sviziev approved these changes

2020-03-21 07:27 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7168](https://jira.corp.magento.com/browse/ENGCOM-7168) has been created to process this Pull Request

2020-03-24 09:20 UTC, lbajsarowicz commented
@magento run all tests

2020-03-31 07:28 UTC, ihor-sviziev commented
@magento run all tests

2020-04-07 15:50 UTC, ihor-sviziev requested changes
@lbajsarowicz could you fix static test failure?

2020-04-07 15:50 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Unit/Controller/Category/ViewTest.php
>      protected function setUp()
Could you add return type?
```suggestion
    protected function setUp(): void
```

2020-04-09 21:30 UTC, ihor-sviziev commented
@magento run all tests

2020-04-10 07:16 UTC, ihor-sviziev approved these changes

2020-04-10 07:17 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7168](https://jira.corp.magento.com/browse/ENGCOM-7168) has been created to process this Pull Request

2020-05-12 14:52 UTC, ihor-sviziev commented
Moved to "on hold" for the same reason as described here: https://github.com/magento/magento2/pull/27538#issuecomment-624891873

2020-05-13 23:01 UTC, lbajsarowicz commented
@magento run all tests

2020-05-16 18:41 UTC, lbajsarowicz commented
@magento run all tests

2020-05-26 18:08 UTC, ihor-sviziev commented
@magento run all tests

2020-05-26 18:12 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz ,
We finally have final decision, it clearly described here https://github.com/magento/magento2/pull/27296#pullrequestreview-418541438.

Could you update your PR to make it mergeble again and revert not needed changes, for instance removing strict types?

2020-05-26 18:12 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Unit/Controller/Category/ViewTest.php
> -declare(strict_types=1);
Looks like we should bring it back

2020-05-26 20:08 UTC, lbajsarowicz commented
If anyone else wants to pick this, feel free to take my code and continue.
I won't be available to handle that in next 2 - 3 weeks.

2020-05-26 20:08 UTC, closed without merging