Fix the error that is wrong link title of a downloadable product when enabling "Use Default Value"
magento/magento2 pull request #27295
Opened 2020-03-15 15:51 UTC by tna274

### Description (*)

Fix the error that is wrong link title of a downloadable product when enabling "Use Default Value"

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

1. Create a new downloadable product with a link
2. Choose scope at any store view (https://prnt.sc/rgpgs4)
3. In "Downloadable Information" section, uncheck "Use Default Value" box under link title and change link title then saving product
4. At the same product and scope, enable (check) "Use Default Value" box under link title then saving product

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-16 09:01 UTC, eduard13 requested changes
Hi @tna274, thank you for your contribution, could you please review the minor recommendation?
Could you please also check and fix the failing Static Tests?
Thank you.

2020-03-16 09:01 UTC, eduard13 commented on app/code/Magento/Downloadable/Model/Link/Builder.php
> +        if (isset($this->data['use_default_title']) && $this->data['use_default_title'] == '1') {
What do you think about applying the following minor adjustment?
```suggestion
        $useDefaultTitle = $this->data['use_default_title'] ?? false;
        
        if ($useDefaultTitle) {
```

2020-03-16 15:59 UTC, tna274 commented on app/code/Magento/Downloadable/Model/Link/Builder.php
> +        if (isset($this->data['use_default_title']) && $this->data['use_default_title'] == '1') {
Thanks for your idea.
I will apply your solution, it makes my code neater

2020-03-18 02:24 UTC, tna274 commented
Hi @eduard13 
Could you help me check the functional test. I found some failure test in report but they do not relate to my edited code.
The uncompleted tests relate to cms_block_page and simple product on frontend.

2020-03-18 08:37 UTC, eduard13 submitted a review, later dismissed
Indeed, the failing tests aren't related to these changes.

2020-03-18 08:38 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-7137](https://jira.corp.magento.com/browse/ENGCOM-7137) has been created to process this Pull Request

2020-03-18 08:38 UTC, magento-engcom-team commented
@tna274 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-03-18 12:36 UTC, engcom-Alfa requested changes
Hi, @tna274.

During testing, we faced the issue.

**_Problem:_** Not able to update the **Samples Title** by "**Use Default Value**" checkbox

**Manual testing scenario:**

1. Create a new downloadable product with a link and sample;
2. Save the product;
![screen1](https://user-images.githubusercontent.com/51679138/76959642-aa964200-6922-11ea-92fa-fab77a26f482.png)
3. Choose scope at any store view;
![screenshot2](https://user-images.githubusercontent.com/51679138/76959689-c994d400-6922-11ea-8eb0-95a7c958af47.png)
4. In "Downloadable Information" section, uncheck "**Use Default Value**" boxes under **link** title and **sample** title, and change the values.
5. Save the product;
![screenshot3](https://user-images.githubusercontent.com/51679138/76960315-dbc34200-6923-11ea-9271-23e4dfed9527.png)
6. Now, check "**Use Default Value**" boxes under the link and sample titles;
7. Save the product;

**Actual Result:**
:heavy_multiplication_x:  The default value for the **link title** was saved but for the **sample title** was not.
![screenshot4](https://user-images.githubusercontent.com/51679138/76961298-cd762580-6925-11ea-8bc3-a36f2375bf09.png)

@tna274 Could you take a look?

Thanks!

2020-03-18 13:26 UTC, tna274 commented
Hi @engcom-Alfa 
I did not know that case
OK, I will update it immediately

2020-03-19 01:12 UTC, tna274 commented
Hi @engcom-Alfa
I've been update PR, please check it again.

2020-03-19 05:55 UTC, engcom-Alfa commented
Hi,@eduard13. Could you review the latest changes? Thanks!

2020-03-19 05:57 UTC, eduard13 approved these changes

2020-03-19 05:58 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-7137](https://jira.corp.magento.com/browse/ENGCOM-7137) has been created to process this Pull Request

2020-03-19 07:02 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-03-20 08:57 UTC, engcom-Kilo commented
@magento run Functional Tests B2B, @magento run Functional Tests CE, @magento run Functional Tests EE

2020-03-25 07:34 UTC, engcom-Echo commented
@magento run all tests

2020-04-04 19:32 UTC, merged