#27043 update directory path configuration for CLI when document_root…
magento/magento2 pull request #27312
Opened 2020-03-17 13:00 UTC by vovsky

…_is_pub is not set in env.php

### Description (*)
The following parameter in env.php determines if "pub" will be included in URLs when CLI is used:
```  
 'directories' => [
        'document_root_is_pub' => true
    ]
```
This parameter is not present in env.php by default. This PR adds necessary directory path configuration updates for CLI in case 'document_root_is_pub' is not in env.php.

### Fixed Issues (if relevant)

1. magento/magento2#27043: Logo url contains "/pub" in asynchronous command line generated emails

### Manual testing scenarios (*)
See https://github.com/magento/magento2/issues/27043 for steps

2020-03-17 22:48 UTC, lbajsarowicz requested changes
This change looks interesting. Could you fix the Integration tests and add new tests to cover the goal of your change? (Automated tests coverage is part of Definition of Done: https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html)

2020-03-18 11:56 UTC, vovsky commented
> This change looks interesting. Could you fix the Integration tests and add new tests to cover the goal of your change? (Automated tests coverage is part of Definition of Done: https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html)

@lbajsarowicz Thank you for the review. I would love to fix failing integration tests, however I'm not able to run them locally (Magento\Setup\SchemaReaderTest.testFailOnInvalidColumnDeclaration) and don't understand how it is related to my changes. Any suggestions would be appreciated.

2020-03-19 18:07 UTC, lbajsarowicz commented
@magento run all tests
I'm re-running tests. It's weird, actually, as your changes are not related to Integration Tests DB issues.

2020-04-06 15:45 UTC, thiaramus commented
The internal Magento team is working on this issue right now.

The fix will be based on commits from the author and delivered according to our internal processes. All original commits made by the author will be preserved.

2020-04-15 12:39 UTC, thiaramus commented
Hi @vovsky,

When the webserver is configured to serve the Magento app from the `/pub`, it might be a better choice to use the `document_root_is_pub` parameter in the `env.php`. We are currently working on updating the documentation on this matter.

Thank you.

2020-04-21 14:03 UTC, sdzhepa commented
Hello @vovsky 

Based on https://github.com/magento/magento2/issues/27043#issuecomment-613687993 and https://github.com/magento/magento2/pull/27312#issuecomment-614013163
Documentation has been updated:
- https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-envphp.html#directories
- https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html#3-update-the-envphp-file

This PR can be closed

2020-04-21 14:03 UTC, closed without merging