Set collection if there is not any collection before
magento/magento2 pull request #27313
Opened 2020-03-17 14:52 UTC by Nazar65

### Description (*)

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/160

### Fixed Issues (if relevant)
1.https://github.com/magento/partners-magento2ee/issues/64

### Manual testing scenarios (*)
Login to admin -> Go to catalog -> Category
Under products in category section
Filterable section is available and filtrable

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-17 18:55 UTC, engcom-Golf commented
@magento run all tests

2020-03-17 22:42 UTC, lbajsarowicz requested changes
Please fix the failing Unit Tests and Integration Tests

2020-03-18 06:26 UTC, engcom-Golf commented
> Please fix the failing Unit Tests and Integration Tests
@lbajsarowicz already in progress

2020-03-19 06:06 UTC, engcom-Golf commented
@lbajsarowicz :heavy_check_mark:

2020-03-19 18:04 UTC, lbajsarowicz submitted a review, later dismissed
I recommend using different formatting for the filters block. Also instead of coalescing - use array for filters.

2020-03-19 18:04 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Block/Adminhtml/Category/Tab/Product.php
> +            );
I know that's about the preferences, but I personally hate these line-breaks.
```suggestion
            $collection = $this->_productFactory->create()->getCollection()
                ->addAttributeToSelect('name')
                ->addAttributeToSelect('sku')
                ->addAttributeToSelect('visibility')
                ->addAttributeToSelect('status')
                ->addAttributeToSelect('price')
                ->joinField(
                    'position',
                    'catalog_category_product',
                    'position',
                    'product_id=entity_id',
                    ['category_id' => (int)$this->getRequest()->getParam('id')],
                    'left'
                );
```

2020-03-19 18:05 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7149](https://jira.corp.magento.com/browse/ENGCOM-7149) has been created to process this Pull Request

2020-08-24 16:53 UTC, sidolov requested changes
@Nazar65 please, apply review changes and cover them with automated tests

2020-09-10 10:32 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-11 12:10 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-16 11:39 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-17 13:38 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-21 13:44 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-22 10:48 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-22 13:56 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-22 14:51 UTC, lbajsarowicz commented
@engcom-Foxtrot Without code changes you don't need to run all the tests, but only the failed ones.

2020-09-30 14:32 UTC, engcom-Foxtrot commented
@magento run all tests

2020-10-01 10:16 UTC, engcom-Foxtrot commented
@magento run all tests

2020-10-01 14:14 UTC, engcom-Foxtrot commented
@magento run all tests

2020-10-07 11:46 UTC, lbajsarowicz approved these changes
✔️  Just minor elements to be adjusted (comments).
Except then that - I don't see any issues there.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +            <!-- Create Category -->
You don't need to provide comments, as these are displayed just like other steps.
It's enough that `stepKey` for the actual step is descriptive.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +            <!-- Create Products -->
↑ Same.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +            <!--Login as admin -->
↑ Same.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +        <!-- Check if Filterable Section is available -->
Same as above.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +        <!-- Apply Sku Filter -->
Same as above.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +        <!-- Check Sku Filter correctly applied -->
Same as above.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +        <!-- Reset Product Filters -->
Same as above.

2020-10-07 11:46 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCategoryProductFiltersTest.xml
> +        <!-- Check Products are present in Category -->
Same as above.

2020-10-07 11:47 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7149](https://jira.corp.magento.com/browse/ENGCOM-7149) has been created to process this Pull Request

2020-10-09 10:07 UTC, engcom-Bravo commented
:heavy_check_mark:  QA Passed

Tested together with the related EE PR. The Filterable section is available and all the filters work as expected

2020-10-14 16:16 UTC, gabrieldagama commented
@magento run all tests

2020-10-24 13:59 UTC, gabrieldagama commented
@magento run all tests

2020-10-27 10:12 UTC, gabrieldagama commented
@magento run all tests

2020-10-29 10:31 UTC, gabrieldagama commented
@magento run Semantic Version Checker

2020-11-16 14:10 UTC, gabrieldagama commented
Approval ticket created: https://jira.corp.magento.com/browse/MC-39098

2020-11-16 17:41 UTC, sivaschenko commented
@magento give me test instance

2020-11-18 09:30 UTC, gabrieldagama commented
@magento run all tests

2020-11-18 11:53 UTC, gabrieldagama commented
@magento run Functional Tests B2B

2020-11-19 09:40 UTC, gabrieldagama commented
@magento run all tests

2021-01-06 12:04 UTC, gabrieldagama commented
@magento run all tests

2021-01-25 16:28 UTC, gabrieldagama commented
@magento run all tests

2021-01-26 11:41 UTC, gabrieldagama commented
@magento run all tests

2021-02-19 14:16 UTC, gabrieldagama commented
@magento create issue

2021-02-22 11:32 UTC, engcom-Bravo requested changes
:x: QA failed

Tested together with the related EE PR

There is an unneeded filterable field without name 
![unneeded](https://user-images.githubusercontent.com/51680745/108702748-58867500-7512-11eb-8189-e6bb2426f24d.png)

2021-03-05 11:10 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-27 13:56 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-12 11:04 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-14 12:17 UTC, engcom-Foxtrot commented
@magento run all tests

2023-03-23 18:37 UTC, joshuaswarren commented
@Nazar65 - thank you for your work on this pull request back in 2020! It's actually one of the oldest open pull requests on the Magento 2 repository now, and I'm trying to understand just what's going on with some of these oldest pull requests. I know a lot has happened since in 2020, so I'm curious if you have an opinion on if this pull request still ought to be considered for merging? Are you able to address the changes

2023-11-07 11:59 UTC, closed without merging