MFTF: Fix failing CMS tests due to PageBuilder conflict
magento/magento2 pull request #27325
Opened 2020-03-18 04:29 UTC by lbajsarowicz

### Description (*)
Another day, another flaky tests introduced. Proper change in PageBuilder repository (related PR)

### Related Pull Requests
* https://github.com/magento/magento2-page-builder/pull/408

### Fixed Issues (if relevant)
Failing CI

### Manual testing scenarios (*)
Create PR and wait

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-18 05:06 UTC, lbajsarowicz commented
@magento run all tests

Final, working version of fix.

![image](https://user-images.githubusercontent.com/1639941/76927137-8153c280-68de-11ea-9a05-9798b62ff2da.png)

2020-03-18 07:56 UTC, lbajsarowicz commented
@magento run all tests
Added missing copyright :-)

2020-03-18 10:32 UTC, lbajsarowicz commented
@magento run all tests
I have no idea why it's not building.

2020-03-18 14:11 UTC, lbajsarowicz commented
@magento run all tests
Looks like I've had outdated `develop` branch for PageBuilder

2020-03-18 15:06 UTC, lbajsarowicz commented
@magento run all tests
I'm forcing a restart. That takes too much time.

2020-03-20 00:00 UTC, lbajsarowicz commented
@magento run all tests
Failures are not related with the scope of PR

2020-03-20 19:50 UTC, lbajsarowicz commented
@magento run all tests
Updated branch to restart tests

2020-03-25 18:52 UTC, lenaorobei commented
@magento run all tests

2020-04-02 15:13 UTC, ihor-sviziev commented
@magento run all tests

2020-04-03 14:30 UTC, lenaorobei submitted a review, later dismissed

2020-04-03 14:32 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-7256](https://jira.corp.magento.com/browse/ENGCOM-7256) has been created to process this Pull Request

2020-04-03 16:05 UTC, ihor-sviziev submitted a review, later dismissed

2020-04-03 16:06 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7256](https://jira.corp.magento.com/browse/ENGCOM-7256) has been created to process this Pull Request

2020-04-07 08:24 UTC, engcom-Alfa requested changes
Hi @lbajsarowicz 
Could you resolve merge conflicts?
Thanks!

2020-04-07 15:20 UTC, ihor-sviziev requested changes

2020-04-07 15:20 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Mftf/Test/StoreFrontRecentlyViewedAtStoreViewLevelTest.xml
> +			      <expectedResult type="const">$$createSimpleProduct3.name$$</expectedResult>
@lbajsarowicz Could you fix formatting also here?

2020-04-09 16:13 UTC, lbajsarowicz commented
Of course. Not always Github editor is good solution.

2020-04-10 11:55 UTC, ihor-sviziev approved these changes

2020-04-10 11:56 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7256](https://jira.corp.magento.com/browse/ENGCOM-7256) has been created to process this Pull Request

2020-04-13 08:17 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-04-13 12:20 UTC, engcom-Echo commented
@magento run Functional Tests B2B, Functional Tests CE

2020-04-16 05:02 UTC, merged