MFTF: Customer Subscribes To Newsletter Subscription On StoreFront
magento/magento2 pull request #27334
Opened 2020-03-18 13:52 UTC by DmitryTsymbal

This PR contains MFTF Test for customer's newsletter subscription.

**Steps to reproduce:**
1 - Create a customer
2 - Login on storefront as created customer
3 - Navigate to newsletter page
4 - Subscribe to newsletter
5 - Assert success message

2020-03-18 14:59 UTC, lbajsarowicz requested changes
:hand:  Please review the comments.

2020-03-18 14:59 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Mftf/Section/StorefrontCustomerLoginFormSection.xml
> +    <section name="StorefrontCustomerLoginFormSection">
Why don't you use `StorefrontCustomerSignInFormSection`?

2020-03-18 14:59 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Mftf/ActionGroup/StorefrontCustomerLoginActionGroup.xml
> +    <actionGroup name="StorefrontCustomerLoginActionGroup">
I like the fact that you want to introduce proper naming for actions, but if you want to do so - deprecate old one: `LoginToStorefrontActionGroup`.

2020-03-19 08:29 UTC, DmitryTsymbal commented
Hello @lbajsarowicz , I have re-used existing Action Groups. Could you check it please?
Thanks

2020-03-19 17:32 UTC, lbajsarowicz approved these changes
:heavy_check_mark: Thank you for your contribution

2020-03-19 17:33 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7148](https://jira.corp.magento.com/browse/ENGCOM-7148) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-03-20 13:10 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-03-22 18:04 UTC, engcom-Echo commented
@magento run all tests

2020-03-23 09:14 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-03-25 17:32 UTC, merged