Use Logger implementation based on deployment configuration
magento/magento2 pull request #27379
Opened 2020-03-21 00:57 UTC by kandy

### Use Logger implementation based on deployment configuration

### Manual testing scenarios (*)
 -  Configure Magento to run in production mode
 -  Add `'log' => [ 'type' => \Monolog\Logger::class, 'args' => ['name' => 'test']],` line to app/etc/env.php file
 -  Delete var/log folder
 -  Run bin/magento s:s:d
 -  Test that errors is logged to StdError stream
 -  Test that var/log folder is not exists/empty

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-24 16:40 UTC, lenaorobei requested changes
Hi @kandy,

Thanks for your contribution. Please address static builds failures.

2020-03-25 16:37 UTC, kandy commented
@lenaorobei 
CopyPaste  fail is not related to my code at all
PhpStan fail report that there not exists classes in test  that test error s logging  on loading of  not exists  classes, so I believe we need ignore this errors

2020-03-25 16:39 UTC, lenaorobei commented
@kandy, agree with phpcpd, but for phpstan please add ignore annotation or this file to whitelist.

2020-03-25 16:42 UTC, kandy commented
@lenaorobei Can you point me on documentation how to do it?

2020-04-08 19:33 UTC, lenaorobei commented
@magento run all tests

2020-04-20 20:29 UTC, lenaorobei commented
@kandy are you still up to finishing this PR?

2020-05-19 21:36 UTC, lenaorobei commented
@kandy please address tests failures

2020-05-25 22:07 UTC, kandy commented
@magento run Integration Tests

2020-06-24 21:46 UTC, kandy commented
@magento run Integration Tests

2020-06-25 04:51 UTC, kandy commented
@magento run Integration Tests

2020-06-25 19:06 UTC, kandy commented
@magento run Integration Tests

2020-06-25 21:22 UTC, kandy commented
@magento run Integration Tests

2020-08-17 16:20 UTC, sidolov commented
@magento create issue

2020-08-25 16:04 UTC, lenaorobei commented
@magento run all tests

2020-09-02 18:34 UTC, lenaorobei commented
@kandy are you interested in finalizing this solution?

2020-09-10 00:31 UTC, kandy commented
@magento run Integration Tests

2020-10-02 04:14 UTC, kandy commented
@magento run all tests

2020-10-02 15:00 UTC, kandy commented
@lenaorobei Can I ask you to review this PR, now it's ready for merge

2020-10-05 14:08 UTC, lenaorobei commented
@kandy could you please squash all commits and add a meaningful commit message? Thanks!

2020-10-07 16:27 UTC, kandy commented
@lenaorobei  done

2020-10-15 07:52 UTC, ihor-sviziev commented
@magento run all tests

2020-10-15 13:07 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

2020-10-16 12:58 UTC, ihor-sviziev approved these changes

2020-10-16 13:02 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8350](https://jira.corp.magento.com/browse/ENGCOM-8350) has been created to process this Pull Request

2020-11-11 10:56 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
Was checked case from Manual testing scenarios
**Result:** 
:heavy_check_mark: Errors is logged to StdError stream when run magento commands
:heavy_check_mark: var/log folder is empty
![image](https://user-images.githubusercontent.com/51681379/98803175-061ac000-241d-11eb-9b8c-705cc570de1c.png)
![image](https://user-images.githubusercontent.com/51681379/98803060-e388a700-241c-11eb-9cc6-3ab3390ae62e.png)
![image](https://user-images.githubusercontent.com/51681379/98803376-51cd6980-241d-11eb-8f70-982255a13b4b.png)

2020-11-11 11:10 UTC, engcom-Delta commented
**Note:** Automation tests are passed

2020-11-13 13:35 UTC, merged