Cleanup ObjectManager usage - Magento_Captcha
magento/magento2 pull request #27392
Opened 2020-03-22 20:26 UTC by Bartlomiejsz

### Description (*)

This PR cleanups ObjectManager usage in Magento_Captcha, by removing object manager instantiation from non-api classes

### Related Pull Requests

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-22 22:22 UTC, lbajsarowicz requested changes
Just minor changes to be introduced.

2020-03-22 22:22 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Controller/Refresh/Index.php
>  <?php
We are going to have conflicts in this file, as I changed this also for my PR #27381

2020-03-22 22:22 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Model/Customer/Plugin/AjaxLogin.php
> +        Json $serializer
Could you alias that to `JsonSerializer`? It's unclear when only `Json` is used if it's `Result\Json` or `Serialize\Json` or other `Json`-type element

2020-03-22 22:22 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Model/Customer/Plugin/AjaxLogin.php
> +     * @return AjaxLogin|\Magento\Framework\Controller\Result\Json
Import as `JsonResult` alias

2020-03-22 22:22 UTC, lbajsarowicz commented on app/code/Magento/Captcha/Model/Customer/Plugin/AjaxLogin.php
> +        callable $proceed
`\Closure`

2020-03-23 20:11 UTC, Bartlomiejsz commented
Done @lbajsarowicz, please review

2020-03-23 20:27 UTC, lbajsarowicz commented
Please don't `force-push` in the future, as it's easier to review the changes from recent review.
The PRs are squashed this way or another before merge, so you don't need to worry about too many commits.

2020-05-23 22:36 UTC, Bartlomiejsz commented
Closing for same reason as https://github.com/magento/magento2/pull/27855 - will be recreated for 2.5.0

2020-05-23 22:36 UTC, closed without merging