[Admin] Do not allow HTML tags for product attribute options when type is dropdown or multiple select
magento/magento2 pull request #27417
Opened 2020-03-24 17:08 UTC by vasilii-b

### Description (*)
This PR aims to add a new validation for the options of the product attribute type "Dropdown", "Multiple Select" that checks whenever the option value contains HTML tags.

HTML tags are not useful nor displayed on the storefront for the product attribute options, those the store manager should be aware of it.

### Related Pull Requests
https://github.com/magento/magento2/pull/27371

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)

1. Go to the Admin area
2. Go to Stores -> Attributes -> Product
3. Press the button "Add New Attribute"
4. Fill in the attribute default label
5. Select the "Catalog Input Type for Store Owner" to "Dropdown" or "Multiple Select"
6. In the section "Manage Options (Values of Your Attribute)" below add new options that contain HTML tags like `<span>`, `</strong>`, etc.
7. Press the "Save and Continue Edit" or "Save Attribute" button
8. See the error message
![Error message that says the option contains HTML tags](https://user-images.githubusercontent.com/13456702/77455366-6d3e2280-6e02-11ea-94a8-dc5f533ede98.png)

### Questions or comments
Are the provided Unit and MFTF tests enough or there should be done more?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-24 17:22 UTC, vasilii-b commented
@magento run all tests

2020-04-08 07:44 UTC, rogyar commented
@magento run all tests

2020-04-13 08:36 UTC, rogyar commented
Hi @vasilii-b. Considering the fact that the only static tests were executed we can assume that Magento cannot be installed after the change you've provided (theoretically). I would recommend doing the following for confirming this assumption. 

- Switch to the `2.4-develop` branch
- Pull the latest changes
- Merge your branch into the `2.4-develop` branch
- Run Magento installation with a clean database (via CLI)
- Make sure that Magento is installed successfully

2020-04-13 08:38 UTC, vasilii-b commented
Hi @rogyar,
Thank you so much! I'll give it a try.

2020-08-17 16:24 UTC, sidolov commented
@magento create issue

2020-08-21 19:29 UTC, sidolov approved these changes

2020-08-21 19:29 UTC, sidolov commented on app/code/Magento/Eav/Model/Validator/Attribute/Options.php
> +    const VALIDATION_HTML_TAGS_RULE_PATTERN = '/<[^<]+>/';
Please, make const private

2020-08-21 19:29 UTC, sidolov commented on app/code/Magento/Eav/Model/Validator/Attribute/Options.php
> +    const VALIDATION_HTML_TAGS_RULE_MESSAGE = 'HTML tags are not allowed for the attribute options. '.
Please, make const private

2020-08-21 19:29 UTC, sidolov requested changes
Please, take a look at the review comments

2020-09-11 09:20 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-11 12:20 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-14 10:29 UTC, gabrieldagama commented
@magento run all tests

2020-09-16 11:39 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-18 12:33 UTC, engcom-Foxtrot commented
@magento run all tests

2020-10-13 10:01 UTC, engcom-Foxtrot commented
@magento run all tests

2020-10-29 07:49 UTC, engcom-Foxtrot commented
@magento run all tests

2020-11-02 13:40 UTC, engcom-Charlie commented
### Before changes :heavy_check_mark:
I can create dropdown product attribute with:

- `Visible on Catalog Pages on Storefront` -> Yes
- `Allow HTML Tags on Storefront` -> Yes

And option value with Html tags which visible on PDP
![image](https://user-images.githubusercontent.com/51680850/97872801-4db79280-1d1f-11eb-9d03-3b6eb01a89cb.png)

### After changes :heavy_multiplication_x:
I try to create the same attribute and get the following error
![image](https://user-images.githubusercontent.com/51680850/97874293-75a7f580-1d21-11eb-808b-af1a3723d2bc.png)

@vasilii-b could you please take a look?
Thank you.

2020-11-16 09:39 UTC, engcom-Charlie commented
Hi @vasilii-b, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-11-16 09:39 UTC, closed without merging