Add ACL role ID to category tree cache id
magento/magento2 pull request #27429
Opened 2020-03-25 01:45 UTC by quangdo-aligent

### Description (*)

When an admin user views a product's category tree (by editing a product), the category tree is cached with an ID akin to `CATALOG_PRODUCT_CATEGORY_TREE_0_` (the `$filter` option is not used in the Magento codebase). 

This is not compatible with admin users that have limited Role Scopes. If the first admin user to view a product category tree has access to all websites (e.g. `Administrator`), this then caches the full category tree for all websites. Then the limited admin user will also see this full category tree even if they should be limited to a single website's category tree. Similarly, if the limited admin user views the category tree after the block cache is cleaned, the `Administrator` user will only see a limited category tree.

This pull request adds the admin's user's ACL role ID to the cache ID. This is probably about as performant as we can get.

### Manual testing scenarios (*)

1. Create a new category (and any sub-categories if desired) and assign it to a new website.
2. Assign a few products to the new website.
3. Create a new website-limited admin user with only access to the new website.
4. Clean `block_html` cache and view a product's category tree as an `Administrator` admin user.
5. Log in as the website-limited admin user and view the category tree for any product.
6. Observe that the full category tree is visible.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-25 12:41 UTC, onkz19 reviewed
it's good

2020-04-03 06:47 UTC, aleron75 commented
Hello @quangdo-aligent first of all, thanks for your contribution, this seems to be a nasty bug.

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html), all code must be covered by tests. 

For this specific case, you should cover your fix by automated tests with the scenario which leads to an issue. Tests should fail on the mainline and pass with your fix.

To answer the question _"which kind of tests should I write"_, the answer is:
pick the most lightweight (execution time-wise) test type that will provide sufficient coverage.

In Magento codebase, you already find two kinds of test for this class:
- `\Magento\Catalog\Test\Unit\Ui\DataProvider\Product\Form\Modifier\CategoriesTest`
- `\Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\CategoriesTest`

So my suggestion would be to try with a unit test.

Thank you again!

2020-04-10 07:46 UTC, aleron75 commented
@magento run all tests

2020-04-10 09:39 UTC, aleron75 commented
Hello @quangdo-aligent can you please check why some tests fail?
Thank you!

2020-04-14 06:58 UTC, aleron75 commented
@magento run all tests

2020-04-15 07:04 UTC, aleron75 submitted a review, later dismissed
Hi @quangdo-aligent all tests passed, well done!

2020-04-15 07:05 UTC, magento-engcom-team commented
Hi @aleron75, thank you for the review.
[ENGCOM-7420](https://jira.corp.magento.com/browse/ENGCOM-7420) has been created to process this Pull Request

2020-04-15 10:41 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

This fix is about EE functionality

**Manual testing scenario:**
1. Create new root category with child (`Second level 1` and `second level 2` for ex.);
![Screenshot from 2020-04-15 13-23-37](https://user-images.githubusercontent.com/51679138/79327091-8c6d3300-7f1c-11ea-89bd-fe01a51de591.png)
2. Set created category as root in a new store;
![new](https://user-images.githubusercontent.com/51679138/79327227-ca6a5700-7f1c-11ea-84b4-8a2d5d0acc31.png)

3. Assign a few products to the new website and new category;
4. Create a new website-limited admin user with only access to the new website. (`Website2` in my case);
5. Clean block_html cache and view a product's category tree as an Administrator admin user;
6. Log in as the website-limited admin user and view the category tree for any product.

**Before:** :heavy_multiplication_x:  The categories from Main Website is shown

![before](https://user-images.githubusercontent.com/51679138/79328259-65affc00-7f1e-11ea-89b3-3ebe4578c84f.gif)

**After:** :heavy_check_mark: The categories from Main Website is hidden
![affter](https://user-images.githubusercontent.com/51679138/79328404-a9a30100-7f1e-11ea-8b68-1d55b8a3eff4.gif)

2020-04-24 19:18 UTC, slavvka commented
Please test it compatibility with Magento/Admin_GWS module

2020-04-24 19:19 UTC, slavvka approved these changes

2020-04-24 19:20 UTC, magento-engcom-team commented
Hi @slavvka, thank you for the review.
[ENGCOM-7420](https://jira.corp.magento.com/browse/ENGCOM-7420) has been created to process this Pull Request

2020-04-27 11:18 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

@slavvka Checked for compatibility with `Magento / Admin_GWS` module

**Manual testing scenario:**
1. Create a product, category -> `Default Category/default` and assign it to **Main Website Store**;
2. Create a new root category with child (`Second Category/second_category` for ex.);
![Screenshot from 2020-04-27 13-39-26](https://user-images.githubusercontent.com/51679138/80365815-de08ac80-8890-11ea-9fb2-2d56a717164b.png)
3. Create a new Website, Store, Store view ( `Second Website`, `Second Website Store`, `Second Website Store view`) and set **Second Category** as default;
![screenshot_1](https://user-images.githubusercontent.com/51679138/80365957-190ae000-8891-11ea-93c9-eda39bc4ce55.png)
4. Assign a few products to the new website and new category;
5. Create a new website-limited admin user with only access to the new website. 
:o: **Admin_GWS** functionality
![newwww](https://user-images.githubusercontent.com/51679138/80366104-5d967b80-8891-11ea-858d-916379084870.png)
6. Clean block_html cache and view a product's category tree as an Administrator admin user;
7. Log in as the website-limited admin user and view the category tree for any product.

**Before:** :heavy_multiplication_x:  The categories from Main Website is shown
![Peek 2020-04-27 14-17afaf](https://user-images.githubusercontent.com/51679138/80366413-e7464900-8891-11ea-8fd0-38ebb1fe1fac.gif)

**After:** :heavy_check_mark: The categories from Main Website is hidden
![Peek 2020-04-27 14-01123](https://user-images.githubusercontent.com/51679138/80366276-af3f0600-8891-11ea-8528-19ba1881da1a.gif)

2020-04-27 14:10 UTC, slavvka commented
@engcom-Alfa Thank you

2020-05-12 18:00 UTC, slavvka requested changes
@quangdo-aligent please resolve the conflicts and re-run tests after upgrade to PHP 7.4

2020-05-20 18:29 UTC, slavvka commented
@magento create issue

2020-05-20 18:30 UTC, slavvka approved these changes

2020-05-20 18:32 UTC, magento-engcom-team commented
Hi @slavvka, thank you for the review.
[ENGCOM-7420](https://jira.corp.magento.com/browse/ENGCOM-7420) has been created to process this Pull Request

2020-05-21 11:17 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed
The result the same as in [comment](https://github.com/magento/magento2/pull/27429#issuecomment-619916165)

2020-06-24 09:34 UTC, merged