Refactor/wishlist
magento/magento2 pull request #27494
Opened 2020-03-30 09:14 UTC by dxx004

### Description (*)

This is a part of the process of introducing implementations of `ActionInterface`.

### Related Pull Requests

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-31 08:45 UTC, ihor-sviziev commented
@magento run all tests

2020-03-31 10:45 UTC, ihor-sviziev requested changes
Hi @dxx004,
Could you review and fix static test failures?
Unit test failure seems to me not related to your changes

2020-04-16 12:39 UTC, ihor-sviziev commented
Hi @dxx004,
Will you be able to update your PR with requested changes?

2020-04-21 08:34 UTC, ihor-sviziev commented
@dxx004  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-05-13 13:09 UTC, lbajsarowicz commented
@ihor-sviziev Reopening due to updates.

2020-05-15 06:49 UTC, ihor-sviziev submitted a review, later dismissed

2020-05-15 06:49 UTC, ihor-sviziev commented
Approved and moved to on hold, waiting for architecture decision

2020-05-15 06:50 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7557](https://jira.corp.magento.com/browse/ENGCOM-7557) has been created to process this Pull Request

2020-05-18 12:19 UTC, ihor-sviziev commented
FYI this PR was moved to "oh hold" due to internal discussions, reason the same as there https://github.com/magento/magento2/pull/27538#issuecomment-624891873

2020-05-26 18:17 UTC, ihor-sviziev requested changes
Hi @dxx004 ,
We finally have final decision, it clearly described here https://github.com/magento/magento2/pull/27296#pullrequestreview-418541438.

Could you update your PR by bringing back extending abstract action?

2020-06-10 10:21 UTC, ihor-sviziev commented
@dxx004,
Will you be able to update your PR?

2020-06-16 08:57 UTC, ihor-sviziev commented
@dxx004  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-06-26 09:46 UTC, lbajsarowicz commented
As per @dxx004 request, I'm reopening the PR.
What you need to do is to revert `extends` on `Action` class that was inherited previously.
Additionally, Magento Architects decided to keep the backwards-compatible Constructor, so make sure that the elements in Constructor after rebuilding are in the correct order.

https://github.com/dxx004/magento2/blob/f4744395fa245230386c65d00405dfba665dc868/app/code/Magento/Wishlist/Controller/Shared/Allcart.php#L46-L56

2020-06-26 10:03 UTC, ihor-sviziev commented
@magento run all tests

2020-06-26 12:27 UTC, dxx004 commented
@ihor-sviziev I see some failed tests, but cannot see why that failed. Could you check pls?

2020-06-26 13:36 UTC, ihor-sviziev commented
@lenaorobei @slavvka @naydav could you help to identify why builds fail without any report?

2020-06-26 15:08 UTC, lenaorobei commented
Here is log message:
```
10:13:21 [Build Functional CE] Repositories code generation... 1/8 [==>-----------------]  12% < 1 sec 46.0 MiBPHP Fatal error:  Access level to Magento\Wishlist\Controller\Shared\Allcart::$resultFactory must be protected (as in class Magento\Framework\App\Action\Action) or weaker in /var/www/html/app/code/Magento/Wishlist/Controller/Shared/Allcart.php on line 20 [] []
```

2020-06-29 08:51 UTC, dxx004 commented
@magento run all tests

2020-06-29 10:10 UTC, dxx004 commented
@magento run all tests

2020-06-30 13:24 UTC, dxx004 commented
@magento run all tests

2020-06-30 15:08 UTC, dxx004 commented
@magento run all tests

2020-06-30 21:47 UTC, lbajsarowicz commented
@magento run Functional Tests B2B, Functional Tests EE

2020-07-01 07:55 UTC, ihor-sviziev requested changes

2020-07-01 07:55 UTC, ihor-sviziev commented on app/code/Magento/Wishlist/Controller/Shared/Allcart.php
> +    private $wishlistProvider;
Could you revert all not needed changes, changing property visibility to private, changing properties order?

2020-07-01 07:55 UTC, ihor-sviziev commented on app/code/Magento/Wishlist/Controller/Shared/Allcart.php
> +        WishlistProvider $wishlistProvider
Please revert this change
```suggestion
        WishlistProvider $wishlistProvider,
        ItemCarrier $itemCarrier
```

2020-07-01 07:55 UTC, ihor-sviziev commented on app/code/Magento/Wishlist/Controller/Shared/Allcart.php
> +        $this->wishlistProvider = $wishlistProvider;
Please revert this change
```suggestion
        $this->wishlistProvider = $wishlistProvider;
        $this->itemCarrier = $itemCarrier;
```

2020-07-01 07:55 UTC, ihor-sviziev commented on app/code/Magento/Wishlist/Controller/Shared/Cart.php
> +    private $cart;
Please revert changing property visibility for all properties.

2020-07-01 07:55 UTC, ihor-sviziev commented on app/code/Magento/Wishlist/Test/Unit/Controller/Shared/AllcartTest.php
> +    protected $context;
Please revert changing property position, also would be good to make all property private **in tests**

2020-07-03 09:03 UTC, engcom-Charlie commented
@magento run Unit Tests, Static Tests

2020-07-03 09:59 UTC, engcom-Charlie commented
@magento run all tests

2020-07-03 12:56 UTC, ihor-sviziev approved these changes

2020-07-03 12:57 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7779](https://jira.corp.magento.com/browse/ENGCOM-7779) has been created to process this Pull Request

2020-07-31 11:16 UTC, ihor-sviziev commented
@magento run all tests

2020-07-31 13:33 UTC, ihor-sviziev submitted a review, later dismissed

2020-07-31 13:34 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7779](https://jira.corp.magento.com/browse/ENGCOM-7779) has been created to process this Pull Request

2020-08-11 10:29 UTC, engcom-Alfa requested changes
Hi @dxx004 . During testing, we faced the issue.

**Manual testing scenario:**

1. Login to a customer account and add a product to wishlist.
2. Go to "wishlist" and click "Share wishlist".
3. Enter email, message and send.
4. Logout from customer account.
5. Open a shared wishlist email, Click on "View Product" from email.
6. It landed on the shared wishlist products;
 Click the "Add to Cart" button from any product.

**Actual Result:** :heavy_multiplication_x:  404 error message

![Peek 2020-08-11 13-16](https://user-images.githubusercontent.com/51679138/89886862-fc8f7b00-dbd5-11ea-823b-0252f66ca625.gif)

The problem is that it has been implemented `HttpGetActionInterface` instead `HttpPostActionInterface` in `app/code/Magento/Wishlist/Controller/Shared/Allcart.php`

With `HttpPostActionInterface` everything works as expected.
![Peek 2020-08-11 13-28](https://user-images.githubusercontent.com/51679138/89887223-935c3780-dbd6-11ea-8ff3-c6e75532571d.gif)

@ihor-sviziev @dxx004 Could you take a look?

Thanks!

2020-08-12 09:41 UTC, engcom-Charlie commented
@magento run all tests

2020-08-12 11:35 UTC, ihor-sviziev commented
@engcom-Charlie could you review and fix failing tests?

2020-08-12 13:29 UTC, engcom-Charlie commented
@magento run all tests

2020-08-12 18:43 UTC, engcom-Charlie commented
@ihor-sviziev could you please review this PR?

2020-08-12 19:30 UTC, ihor-sviziev approved these changes

2020-08-12 19:31 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7779](https://jira.corp.magento.com/browse/ENGCOM-7779) has been created to process this Pull Request

2020-08-13 08:18 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Login to a customer account and add a product to wishlist;
2. Go to "wishlist" and click "Share wishlist";
3. Enter email, message and send;
4. Logout from the customer account;
5. Open a shared wishlist email, Click on "View Product" from email;
6. It landed on the shared wishlist products;
 Click on the "Add to Cart" button from any product.

**Actual Result:** :heavy_check_mark: The product was added to cart

![Screenshot from 2020-08-13 11-02-00](https://user-images.githubusercontent.com/51679138/90110797-75b5dc00-dd56-11ea-848e-6f38f57f12bb.png)

 Click on the "Add All to Cart" button

**Actual Result:** :heavy_check_mark: The products were added to cart

![Screenshot from 2020-08-13 11-01-24](https://user-images.githubusercontent.com/51679138/90110941-9f6f0300-dd56-11ea-9aeb-52c426001675.png)

2020-08-14 08:50 UTC, engcom-Alfa commented
@magento create issue

2020-08-24 08:33 UTC, merged