Fix bug 27490: Can't change customer group when placing an admin order
magento/magento2 pull request #27501
Opened 2020-03-30 15:42 UTC by tna274

### Description (*)
Fix bug 27490: Can't change customer group when placing an admin order

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27490: Fix bug 27490: Can't change customer group when placing an admin order

### Manual testing scenarios (*)

1. In Admin System > Configurations > Customers > Customer Configurations > Create New Account Options > Enable Automatic Assignment to Customer Group >> Select YES
2. In Admin Sales > Orders.
3. Select Create New Order
4. Select Create New Customer
5. Under Account Information, change the group.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-30 22:25 UTC, Stepa4man requested changes
Hi @tna274 
Thanks for your contribution.

Please change your code according to [Magento technical guideline ](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#1-basic-programming-principles)

Also please consider refactoring this class.
Instead of introducing new code complexity try to separate implementation for adminhtml and frontend introducing 2 observers and declare them at respective levels via events.xml
To avoid code duplication please use decomposition.

2020-03-30 22:25 UTC, Stepa4man commented on app/code/Magento/Quote/Observer/Frontend/Quote/Address/CollectTotalsObserver.php
> +        $this->state = $state ?: ObjectManager::getInstance()->get(State::class);
Once this PR will be delivered in a major release of Magento we can avoid using BC way of adding new dependencies to the constructor of non **@api** classes.

2020-03-30 22:25 UTC, Stepa4man commented on app/code/Magento/Quote/Observer/Frontend/Quote/Address/CollectTotalsObserver.php
> +                $this->state->getAreaCode() == Area::AREA_ADMINHTML
Please use a strict comparison operator `===` and add `declare(strict_types=1);`

2020-04-03 14:54 UTC, tna274 commented
Hi @Stepa4man 
I have updated my pull request

2020-07-21 10:38 UTC, engcom-Charlie commented
Hi, @tna274 can you please look through failed tests and merge conflicts?

2020-07-30 12:58 UTC, engcom-Kilo commented
@magento run all tests

2020-07-30 13:28 UTC, engcom-Kilo commented
Working with MFTF test.

2020-07-31 10:20 UTC, engcom-Kilo commented
@magento run Magento Health Index

2020-07-31 10:21 UTC, engcom-Kilo commented
@magento run Static Tests

2020-07-31 12:34 UTC, engcom-Kilo commented
Added MFTF test.

2020-07-31 12:40 UTC, engcom-Kilo commented
@magento run Functional Tests B2B

2020-08-03 13:10 UTC, engcom-Kilo commented
@magento run all tests

2020-10-16 13:06 UTC, Stepa4man requested changes
Hi @tna274 
Thanks for your contribution.

Please take a look at my comments.

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Observer/Frontend/Quote/Address/CollectTotalsObserver.php
> +        return $groupId !== null ? true : false;
Why do you need it here? Why don't you just write `return $groupId !== null`?

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Observer/Backend/Quote/Address/CollectTotalsObserver.php
> +        return false;
Please put those long difficult conditions to separate private methods with proper naming and shorten this function to just return statement:
`
return $groupId !== null && !($this->isAdminArea() && $this->isNotLoggedInGroup($groupId));
`
At least like this.

You can think even more to make this code more readable.

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Test/Unit/Observer/Backend/Quote/Address/CollectTotalsObserverTest.php
> +    protected $model;
Please replace all protected properties with private.

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Test/Unit/Observer/Backend/Quote/Address/CollectTotalsObserverTest.php
> +     * @var MockObject
Please add the proper type annotation to all class properties

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Test/Unit/Observer/Backend/Quote/Address/CollectTotalsObserverTest.php
> +        $this->objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager($this);
Please don't use ObjectManager helper, use `new` statement instead.

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Test/Unit/Observer/Backend/Quote/Address/CollectTotalsObserverTest.php
> +            \Magento\Customer\Api\Data\CustomerInterface::class,
Please import all class names.

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Observer/Backend/Quote/Address/CollectTotalsObserver.php
> +                && $groupId == $this->groupManagement->getNotLoggedInGroup()->getId()
Please use strict comparison operator

2020-10-16 13:06 UTC, Stepa4man commented on app/code/Magento/Quote/Test/Unit/Observer/Backend/Quote/Address/CollectTotalsObserverTest.php
> +<?php
Please declare strict types for every php file

2020-11-11 22:23 UTC, sidolov commented
@tna274  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-11-11 22:23 UTC, closed without merging