[Fixed] - Resolve Add Item To Wish-list With Default Value Below 1.
magento/magento2 pull request #27510
Opened 2020-03-31 09:35 UTC by niravkrish

### Description (*)

- I have added minimum saleable quantity as a default qty add to wishlist on add to wishlist button params.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27396: Magento 2.3.4 ad item to wishlist with default value below 1

### Manual testing scenarios (*)

1. Add to wishlist from different page like from homepage, Listing page and details page.
2. Change qty and add to wishlist.

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-31 11:09 UTC, lbajsarowicz requested changes
Please review the comments.

2020-03-31 11:09 UTC, lbajsarowicz commented on app/code/Magento/Wishlist/Helper/Data.php
>          $this->escaper = $escaper ?? ObjectManager::getInstance()->get(Escaper::class);
```suggestion
        $this->escaper = $escaper;
```

2020-03-31 11:09 UTC, lbajsarowicz commented on app/code/Magento/Wishlist/Helper/Data.php
> +        $this->stockItemRepository = $stockItemRepository;
```suggestion
        $this->stockItemRepository = $stockItemRepository ?? ObjectManager::getInstance()->get(StockItemRepository::class);
```

2020-03-31 11:09 UTC, lbajsarowicz commented on app/code/Magento/Wishlist/Helper/Data.php
> +        StockItemRepository $stockItemRepository
Remove backward compatible Object loader for escaper, introduce such for your new dependency.


```suggestion
        Escaper $escaper,
        StockItemRepository $stockItemRepository = null
```

2020-03-31 11:30 UTC, lbajsarowicz commented
Let's wait for tests to pass now :-)
Make sure that Unit Tests and Integration Tests are running :heavy_check_mark: for you

2020-06-10 07:49 UTC, engcom-Kilo commented
@magento run all tests

2020-06-11 09:13 UTC, engcom-Kilo commented
Working with MFTF test

2020-06-12 11:29 UTC, engcom-Kilo commented
@magento run all tests

2020-06-18 09:44 UTC, engcom-Kilo commented
Some anomaly with tests.

2020-06-30 07:42 UTC, engcom-Kilo commented
@magento run all tests

2020-06-30 09:39 UTC, engcom-Kilo commented
@VladimirZaets 
Seems Tests can not be run.
Issue with Tests by Test Server? Or by changes in Pull Request?

2020-07-15 12:23 UTC, engcom-Kilo commented
@magento run all tests

2020-07-22 11:33 UTC, engcom-Kilo commented
@magento run all tests

2020-07-27 09:30 UTC, engcom-Kilo commented
@magento run all tests

2020-07-31 07:51 UTC, engcom-Kilo commented
@magento run all tests

2020-08-10 12:00 UTC, engcom-Kilo commented
@magento run all tests

2020-08-11 11:28 UTC, engcom-Kilo commented
@niravkrish 
Please check failed Tests.

2020-08-21 09:04 UTC, niravkrish commented
hi,

I have checked and find out there are some test cases that failed due to the below reasons.
1) argument incorrect in construct.
Required: $context, $coreRegistry, $customerSession, $wishlistFactory, $storeManager, $postDataHelper, $customerViewHelper, $wishlistProvider, $productRepository, $escaper, **$customerFactory, $customerRepository, $stockItemRepository**

I am not able to understand why **$customerFactory, $customerRepository, $stockItemRepository** arguments are requied.
Report Url:  https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27510/ca393b1e101f18e20e1b8c4c6b8623e0/Statics/allure-report-ce/index.html#suites/93601c67ba881760e9fe6a30b48722dc/7a0d65b07ad7460b/

screenshot: [https://nimb.ws/4CiTWk](https://nimb.ws/4CiTWk)

2) version  checker becomes fail:
should I need to change the version for the module?

Screenshot: [https://nimb.ws/faqkmM](https://nimb.ws/faqkmM)
[https://nimb.ws/Sxcz9o](https://nimb.ws/Sxcz9o)

Kindly suggest me what can I do for this.

Thanks & Regards,
Nirav Patel

2020-11-18 14:20 UTC, lbajsarowicz commented
@niravkrish closing due to inactivity. Please let me know if you still want to work on the issue.

2020-11-18 14:20 UTC, closed without merging