27439 issue configurable product tier price on category page
magento/magento2 pull request #27520
Opened 2020-03-31 18:35 UTC by ProkopovVitaliy

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27439 : "As low as" price display doesn't consider advanced pricing

### Manual testing scenarios (*)

1. Set up tier prices for configurable product
2. Visit the catalog view of the category

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-03 06:12 UTC, rogyar requested changes
Hi @ProkopovVitaliy. Thank you for your contribution. Please, consider covering your changes with automated tests. You may go with a unit test in this case

2020-04-07 05:48 UTC, ProkopovVitaliy commented
Hi @rogyar i covered my changes with unit tests)

2020-04-09 11:06 UTC, rogyar requested changes
Hi @ProkopovVitaliy. Thank you for providing the autotest. Please, check my comments below for minor adjustments

2020-04-09 11:06 UTC, rogyar commented on app/code/Magento/ConfigurableProduct/Pricing/Price/ConfigurablePriceResolver.php
> +    private function hasTierPrice(SaleableInterface $product)
Please, provide the return types where it's possible. It applies also for other methods 
```suggestion
    private function hasTierPrice(SaleableInterface $product): bool
```

2020-04-09 11:06 UTC, rogyar commented on app/code/Magento/ConfigurableProduct/Pricing/Price/ConfigurablePriceResolver.php
> +        return (float) 0;
Please, use return type hinting for the method instead of the type casting. Thank you

2020-04-09 11:06 UTC, rogyar commented on app/code/Magento/ConfigurableProduct/Test/Unit/Pricing/Price/ConfigurablePriceResolverTest.php
> +use Magento\Framework\Exception\LocalizedException;
Please, double-check the fact that we have `LocalizedException` in this test

2020-04-09 11:06 UTC, rogyar commented on app/code/Magento/ConfigurableProduct/Test/Unit/Pricing/Price/ConfigurablePriceResolverTest.php
> +    public function testResolvePriceWithTier($variantPrices, $expectedPrice)
Please, move this test method above the data provider

2020-04-09 11:06 UTC, rogyar commented
Also, please, take a look at the failing static test.

2020-04-10 18:49 UTC, ProkopovVitaliy commented
> Also, please, take a look at the failing static test.

@rogyar all recommendations are fulfilled)

2020-04-12 13:06 UTC, ProkopovVitaliy commented
@rogyar all failing tests fixed  👌

2020-04-15 12:22 UTC, rogyar submitted a review, later dismissed

2020-04-15 12:23 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-7423](https://jira.corp.magento.com/browse/ENGCOM-7423) has been created to process this Pull Request

2020-04-16 09:34 UTC, engcom-Alfa requested changes
Hi, @ProkopovVitaliy 

During testing, we faced the issues

**Manual testing scenario:**
1. Create Configurable product with **text swatch** attribute for example (test1 and test2);
![Screenshot from 2020-04-16 12-16-52](https://user-images.githubusercontent.com/51679138/79438476-3bbd0f00-7fdc-11ea-8511-f582db969106.png)

2. Set tier prices for each virtual products:
**_test1_** for ex.
![Screenshot from 2020-04-16 12-20-57](https://user-images.githubusercontent.com/51679138/79438927-dc133380-7fdc-11ea-8769-3df6fbe1e79b.png)
**_test2_** for ex.
![Screenshot from 2020-04-16 12-21-38](https://user-images.githubusercontent.com/51679138/79438950-e46b6e80-7fdc-11ea-8083-c07f9129e1d3.png)

3. Visit the catalog view of the category;

**Actual Result:**
:heavy_check_mark: The lowest price is correct
![screenshot222](https://user-images.githubusercontent.com/51679138/79439430-812e0c00-7fdd-11ea-8daf-39820fb51da7.png)

4. Click on any swatch options

**Actual Result:** 
:heavy_multiplication_x:  The main price is shown 
![Peek 2020-04-16 12-28](https://user-images.githubusercontent.com/51679138/79439865-01547180-7fde-11ea-97f2-9b15a3040455.gif)

5. Unselect swatch option

**Actual Result:** 
:heavy_multiplication_x: The lowest price shown without `As low as`
![Peek 2020-04-16 12-33](https://user-images.githubusercontent.com/51679138/79440261-745de800-7fde-11ea-9a45-ec437385a256.gif)

@ProkopovVitaliy Could you take a look?
Thanks!

2020-04-20 16:17 UTC, ProkopovVitaliy commented
@rogyar  This swatches based on `app/code/Magento/Swatches/view/base/web/js/swatch-renderer.js `component that also used on product view page.  This component orients and expect tier-price template by selector ` #tier-prices-template`. 

If ` #tier-prices-template` element fond on page, swatch-renderer.js will prints tier prices correct which is what happens on the product view page. 
But  on catalog page this block are missed so it can't print correct information. 

Also as I found out this script is intended only for cases when there is one block on the page, so even adding it to the page it will not work correctly.
_app/code/Magento/Swatches/view/base/web/js/swatch-renderer.js :_
```
           if (typeof result != 'undefined' && result.tierPrices && result.tierPrices.length) {
                if (this.options.tierPriceTemplate) {
                    tierPriceHtml = mageTemplate(
                        this.options.tierPriceTemplate,
                        {
                            'tierPrices': result.tierPrices,
                            '$t': $t,
                            'currencyFormat': this.options.jsonConfig.currencyFormat,
                            'priceUtils': priceUtils
                        }
                    );
                    $(this.options.tierPriceBlockSelector).html(tierPriceHtml).show();
                }
            } else {
                $(this.options.tierPriceBlockSelector).hide();
            }
```

So, do I have to work with this script and fix it in some way or would it be better to recreate new issue and make a special script specifically for the category page?

2020-04-27 09:40 UTC, rogyar commented
Hi @ProkopovVitaliy. You may proceed to work with this PR. Just rename it correspondingly after the fixes are done. If it will fix additional issues, you may create these additional issues and link to the current PR as well.

2020-06-03 19:50 UTC, VladimirZaets commented
Hi @ProkopovVitaliy, any updates on it?

2020-06-30 11:14 UTC, engcom-Charlie commented
Hi @ProkopovVitaliy, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-06-30 11:14 UTC, closed without merging