PhpUnit 8 Migration - AdminNotification
magento/magento2 pull request #27521
Opened 2020-03-31 18:37 UTC by ihor-sviziev

### Description (*)
This PR updates unit tests in AdminNotification module + contains framework fix from https://github.com/magento/magento2/pull/27519

Note: 
We have 2 warnings that can't be fixed because these new methods doesn't exists in phpunit 8:
```
1) Magento\AdminNotification\Test\Unit\Model\System\Message\CacheOutdatedTest::testGetText
Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.

2) Magento\AdminNotification\Test\Unit\Model\System\Message\Media\Synchronization\ErrorTest::testGetText
Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.
```

### Related Pull Requests

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/27500

### Manual testing scenarios (*)
1. Run tests in phpunit 6 (currently in 2.4-develop) using `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/AdminNotification/`
2. Install phpunit 8, run tests using `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/AdminNotification/`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-03-31 19:03 UTC, lbajsarowicz requested changes
In future we can change the scope for Test properties from `protected` to `private`.
I'm not sure if it's for purpose or accidentally, but you've added changes from other PR.

You can put in the description that this PR would work after merging another (however the changes introduced in files related to AdminNotification are backward compatible, so there's no dependency)

2020-03-31 19:03 UTC, lbajsarowicz commented on app/code/Magento/AdminNotification/Test/Unit/Model/System/Message/SecurityTest.php
> +     * @var MockObject
There's missing reference to original class type.

2020-03-31 19:03 UTC, lbajsarowicz commented on app/code/Magento/AdminNotification/Test/Unit/Model/System/Message/SecurityTest.php
> +     * @var MockObject
There's missing reference to original class type.

2020-03-31 19:03 UTC, lbajsarowicz commented on app/code/Magento/AdminNotification/Test/Unit/Model/System/Message/SecurityTest.php
> +     * @var MockObject
There's missing reference to original class type.

2020-03-31 19:03 UTC, lbajsarowicz commented on app/code/Magento/AdminNotification/Test/Unit/Model/System/Message/SecurityTest.php
> +     * @var MockObject
There's missing reference to original class type.

2020-04-01 19:16 UTC, ihor-sviziev commented
@magento run all tests

2020-04-01 20:42 UTC, ihor-sviziev commented
@lbajsarowicz 
I fixed comments that you left. Why I put there one commit from framework - just to make these pull requests independent, as the same commit is there in al PRs - there will not be any conflicts between them and all of these PRs will actually work

2020-04-01 20:46 UTC, lbajsarowicz approved these changes

2020-04-01 20:47 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7243](https://jira.corp.magento.com/browse/ENGCOM-7243) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-01 20:49 UTC, ihor-sviziev commented
@lenaorobei seems like we have false positive in static test

2020-04-01 20:56 UTC, lenaorobei commented
@ihor-sviziev looking into it.

2020-04-01 20:57 UTC, lenaorobei commented on lib/internal/Magento/Framework/TestFramework/Unit/Listener/GarbageCleanup.php
>       * {@inheritdoc}
This is correct finding.
`20 | ERROR | [x] If the @inheritdoc not inline it shouldn’t have braces`

2020-04-01 20:57 UTC, lenaorobei commented on lib/internal/Magento/Framework/TestFramework/Unit/Listener/GarbageCleanup.php
>       * @SuppressWarnings(PHPMD.UnusedFormalParameter)
Missing blank line.

2020-04-01 21:01 UTC, lenaorobei commented
Yes, the 3-rd finding looks like false-positive, but it should disappear when first 2 will be fixed.

2020-04-02 10:55 UTC, engcom-Alfa requested changes
@lenaorobei @lbajsarowicz Could you approve the latest changes?
Thanks!

2020-04-02 10:57 UTC, lbajsarowicz approved these changes
Yes, I reviewed them before and was waiting for tests to pass.
We have all green, so my approval is there.

2020-04-02 10:58 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7243](https://jira.corp.magento.com/browse/ENGCOM-7243) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-02 13:49 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**
PHPUnit v8
php 7.3

**Before:**
![Screenshot from 2020-04-02 16-47-39](https://user-images.githubusercontent.com/51679138/78256809-b3ca0600-7501-11ea-9240-edc9d3dbea6a.png)

**After:**
![Screenshot from 2020-04-02 16-38-14](https://user-images.githubusercontent.com/51679138/78256896-d0fed480-7501-11ea-92ff-caae180c06bf.png)

2020-04-04 19:32 UTC, merged