magento/magento2#27500 Replace deprecated constructs from Cron PHPUnit.
magento/magento2 pull request #27577
Opened 2020-04-04 13:30 UTC by lbajsarowicz

### Description (*)
Part of PHPUnit 8 compatibility process for #27500 

### Related Pull Requests

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-06 06:13 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,

Could you update `setUp` and `tearDown` method return type to be `:void`?
In phpunit 8 I had fatal errors caused by not declared return type.

Could you also confirm that it works fine for you once you'll finish?

2020-04-09 21:26 UTC, ihor-sviziev approved these changes

2020-04-09 21:27 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7296](https://jira.corp.magento.com/browse/ENGCOM-7296) has been created to process this Pull Request

2020-04-15 08:14 UTC, engcom-Alfa commented
QA not applicable

2020-04-15 17:01 UTC, merged