Fix Magento Integrity Dependency test in case to be used not in scope of app/code isntallation.
magento/magento2 pull request #27578
Opened 2020-04-04 14:13 UTC by swnsma

### Description (*)
Provide possibility to run Dependency tests out of Magento repository.
- Fix hard-dependency on word 'Magento' in the module name;
- Fix hard-dependency on location of files under app/code folder to find the plugin.
Also, adjust static tests framework tests.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-04 15:21 UTC, rogyar requested changes

2020-04-04 15:21 UTC, rogyar commented on dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php
> +    /**
Please, add an extra empty line here.

2020-04-04 15:21 UTC, rogyar commented on dev/tests/static/framework/Magento/TestFramework/Dependency/Reader/ClassScanner.php
> +        $scanner = new \Magento\Setup\Module\Di\Code\Reader\FileClassScanner($filePath);
Please, replace the FQN with an import. 
I don't advocate avoiding FQNs, however, if we use imports in other places let's do it in the same way everywhere.

2020-04-08 07:15 UTC, rogyar approved these changes

2020-04-08 07:17 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-7279](https://jira.corp.magento.com/browse/ENGCOM-7279) has been created to process this Pull Request

2020-04-22 11:42 UTC, engcom-Delta commented
**Notice:** QA not applicable

2020-04-25 06:22 UTC, merged