Fix #27523: throw informative errors in setup:db:generate-patch
magento/magento2 pull request #27579
Opened 2020-04-04 14:28 UTC by korostii

### Description (*)
In most cases, if there is indeed a write permission issue, the error does show the complete path to directory which cannot be created:
![Screenshot from 2020-04-04 17-21-06](https://user-images.githubusercontent.com/24894168/78453213-e6f2cd80-7698-11ea-807a-1f858de8cd4c.png)
However, if the requested module *does not exist*, the console command will compile an invalid(incomplete) target path and will show a rather cryptic error message:
![Screenshot from 2020-04-04 17-09-33](https://user-images.githubusercontent.com/24894168/78453241-0b4eaa00-7699-11ea-8745-4e630450314f.png)

### Fixed Issues (if relevant)

1. magento/magento2#27523: CLI Patch Generator: Lack of information what path cannot be created

### Manual testing scenarios (*)
1. Run `php bin/magento setup:db-declaration:generate-patch Vendor_Module SomePatch`, while there isn't any registered modules with name matching `Vendor_Module`
2. You should see an informative error message like `Cannot find a registered module with name "Vendor_Module" `

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-04 15:42 UTC, rogyar requested changes

2020-04-04 15:42 UTC, rogyar commented on app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php
> +    private $componentRegistrar;
Please, add `mock` suffix to the mock properties

```suggestion
    private $componentRegistrarMock;
```

2020-04-04 15:42 UTC, rogyar commented on app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php
> +    private $componentRegistrar;
It also applies to all other mock properties

2020-04-04 15:42 UTC, rogyar commented on app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php
> +     * @var DirectoryList
Please, import `PHPUnit\Framework\MockObject\MockObject;` and use it for documenting properties
```suggestion
     * @var DirectoryList|MockObject
```

2020-04-04 15:42 UTC, rogyar commented on app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php
> +        $read = $this->createMock(\Magento\Framework\Filesystem\Directory\Read::class);
Please, import classes instead of using FQN

2020-04-04 15:42 UTC, rogyar commented on app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php
> +     * @expectedExceptionMessage Not enough arguments
Please, do not use annotations for exceptions. They are not compatible with PHPUnit 8 which is going to be supported soon. Use `$this->expectExceptionMessage(` instead

2020-04-04 15:42 UTC, rogyar commented on app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php
> +     * @expectedExceptionMessage Not enough arguments
The same applies to `@expectedException`

2020-04-08 07:25 UTC, rogyar commented on app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php
> +        $read = $this->createMock(Read::class);
Hi @korostii. Thank you for fixing the issues mentioned earlier. There was a comment from me regarding suffixing mock properties with Mock suffix. The same applies to the variables. This suffix improves code readability by letting know straight away what object we are working on mock or a real instance.

Just a recommendation for the future 😉

2020-04-08 07:26 UTC, rogyar approved these changes

2020-04-08 07:27 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-7280](https://jira.corp.magento.com/browse/ENGCOM-7280) has been created to process this Pull Request

2020-04-09 12:03 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Run: `php bin/magento setup:db-declaration:generate-patch Vendor_Module SomePatch`

**Before:**
![Screenshot from 2020-04-09 14-33-36](https://user-images.githubusercontent.com/51679138/78893048-3a876180-7a73-11ea-82dd-da3003f62d93.png)

**After:**
![Screenshot from 2020-04-09 14-45-45](https://user-images.githubusercontent.com/51679138/78893060-42470600-7a73-11ea-9cbe-76bcdda916bc.png)

2020-05-27 12:55 UTC, engcom-Kilo commented
@magento run all tests

2020-06-02 08:22 UTC, engcom-Kilo commented
Failed Functional Tests B2B, Static Tests, Unit Tests - not related to changes in this Pull Request.

2020-06-23 17:49 UTC, slavvka commented
@magento run all tests

2020-06-23 18:49 UTC, slavvka requested changes
@korostii Please fix the failing tests after upgrade to PHP 7.4:
```
13:04:22 PHP Fatal error:  Declaration of Magento\Developer\Test\Unit\Console\Command\GeneratePatchCommandTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /var/www/html/app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php on line 47
```

2020-07-09 20:02 UTC, korostii commented
> Please fix the failing tests after upgrade to PHP 7.4

Fixed.

2020-07-22 11:08 UTC, engcom-Kilo commented
@magento run all tests

2020-08-27 19:48 UTC, sidolov approved these changes

2020-08-27 19:49 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-7280](https://jira.corp.magento.com/browse/ENGCOM-7280) has been created to process this Pull Request

2020-08-31 06:58 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Run: `php bin/magento setup:db-declaration:generate-patch Vendor_Module SomePatch`

**Before:**
![Screenshot from 2020-04-09 14-33-36](https://user-images.githubusercontent.com/51679138/78893048-3a876180-7a73-11ea-82dd-da3003f62d93.png)

**After:**
![Screenshot from 2020-04-09 14-45-45](https://user-images.githubusercontent.com/51679138/78893060-42470600-7a73-11ea-9cbe-76bcdda916bc.png)

2020-09-02 17:08 UTC, merged