Bulk ACL management for AsynchronousOperations Admin UI
magento/magento2 pull request #27580
Opened 2020-04-04 14:29 UTC by nuzil

### Description (*)
After Migrating of Asynchronous Operations from Magento Commerce to Magento Open Source, looks like part of functionality was extended.

In details:
In magento_bulk table was added user_type, which defines type of the user who created Bulk Operation.

Possible types are:
- Admin
- Integration
- Guest
- Customer

In current implementation all Admin UI components have no idea about user type:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/AsynchronousOperations/view/adminhtml/ui_component/bulk_listing.xml - in default Grid there are NO DataSource is defined, so Admin see the whole operations, but at the same time, he cannot see Details of those operations:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Bulk/Details.php#L52

But at you can see from implementation, 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/AsynchronousOperations/Model/AccessValidator.php#L58

that permissions are checked based on UserID and fully ignoring UserType. Which means, that Admin has access to All transactions or all user types with the same ID.

### Fixed Issues (if relevant)
Current implementation will add: 
* New ACL roles for give possibilities for Admin define permissions for Admin/Integration user to have access only to specific user types operations.
* With restricted user role, Admin will be able to see only operations that are assigned to him, View detailes or Restart them
* Also Admin notifications will be restricted only to allowed.

### Questions or comments
Auto tests still in process, but main implementation can be already reviewed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-26 15:19 UTC, sidolov commented
@magento create issue

2020-08-27 18:21 UTC, sidolov requested changes

2020-08-27 18:21 UTC, sidolov commented on lib/internal/Magento/Framework/Bulk/BulkStatusInterface.php
> +    public function getBulksByUserAndType($userId, $userTypeId);
Adding the new methods to the interface is backward-incompatible change. Please, introduce new interface with this method.

2020-08-27 18:21 UTC, sidolov commented on app/code/Magento/AsynchronousOperations/Model/BulkStatus.php
> +    public function getBulksByUserAndType($userId, $userTypeId)
Should be extracted to the separate class

2020-08-27 18:21 UTC, sidolov commented on app/code/Magento/AsynchronousOperations/Model/BulkOperationsStatus.php
> +    public function getBulksByUserAndType($userId, $userTypeId)
Should be extracted to separate class

2020-08-27 18:21 UTC, sidolov commented on app/code/Magento/AsynchronousOperations/Model/AccessManager.php
> +    public const BULK_LOGGING_ACL_GUESTS
Is it possible to make constants private?

2020-08-27 18:21 UTC, sidolov commented on app/code/Magento/AsynchronousOperations/Model/AccessManager.php
> +    public function isAllowedForBulkUuid($bulkUuid)
I prefer to split this class into three with one method.

2020-09-17 08:03 UTC, engcom-Charlie commented
@nuzil can you please look at the requested changes?
Thank you.

2020-09-21 08:24 UTC, engcom-Charlie commented
Hi @nuzil, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-09-21 08:42 UTC, nuzil commented
Hi @engcom-Charlie 
I'm on it. As you can see I sync up branches only 4 days ago. Its require some time to refactor so many stuff.

2020-09-21 09:46 UTC, gabrieldagama requested changes
Moving the PR to the correct state, as @nuzil mentioned, it is being worked on.

2020-10-16 11:53 UTC, engcom-Charlie commented
Hi, @nuzil will you continue on this PR?
Thank you.

2020-10-30 08:59 UTC, engcom-Charlie commented
Hi @nuzil, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-12-02 12:05 UTC, engcom-Charlie commented
Closed as duplicate https://github.com/magento/magento2/pull/30806.

2020-12-02 12:05 UTC, closed without merging