ISSUE-27500: Fixed unit tests for module Magento_SampleData
magento/magento2 pull request #27598
Opened 2020-04-04 20:54 UTC by andrewbess

### Description (*)

This PR partially updates unit tests in SampleData module
Other tests of this module have been updated in https://github.com/magento/magento2/pull/27481

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27500: Unit Tests incompatible with PHPUnit 8

### Manual testing scenarios (*)

1. Run tests in phpunit 6 (currently in 2.4-develop) using `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/SampleData/`
2. Install phpunit 8, run tests using `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/SampleData/`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-05 02:44 UTC, lbajsarowicz requested changes
Please review the comments. Only minor changes to be introduced.

2020-04-05 02:44 UTC, lbajsarowicz commented on app/code/Magento/SampleData/Test/Unit/Model/DependencyTest.php
> + * Tests for Magento\SampleData\Model\Dependency
If you really want to provide the class - you can use `@covers` annotation

2020-04-05 02:44 UTC, lbajsarowicz commented on app/code/Magento/SampleData/Test/Unit/Model/DependencyTest.php
> +     * @return MockObject
```suggestion
     * @return ReadInterface|MockObject
```

2020-04-05 02:44 UTC, lbajsarowicz commented on app/code/Magento/SampleData/Test/Unit/Model/DependencyTest.php
> +     * @return MockObject
```suggestion
     * @return ReadInterface|MockObject
```

2020-04-05 02:44 UTC, lbajsarowicz commented on app/code/Magento/SampleData/Test/Unit/Model/DependencyTest.php
> +    ): MockObject {
```suggestion
    public function stubComposerJsonReader(array $composerJsonContent): MockObject {
```

2020-04-05 03:43 UTC, lbajsarowicz approved these changes

2020-04-05 03:44 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7263](https://jira.corp.magento.com/browse/ENGCOM-7263) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-05 09:50 UTC, lbajsarowicz submitted a review, later dismissed
:heavy_check_mark: Great job, thank you for your contribution.

2020-04-05 09:52 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7263](https://jira.corp.magento.com/browse/ENGCOM-7263) has been created to process this Pull Request

2020-04-09 09:24 UTC, engcom-Alfa requested changes
Hi @andrewbess 

During testing, we faced the issue

PHPUnit 8

**Run:** `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/SampleData/`

**Actual Result:**
![Screenshot from 2020-04-09 12-20-54](https://user-images.githubusercontent.com/51679138/78879756-01dc8d80-7a5d-11ea-8d76-633b2d1446f6.png)

@andrewbess Could you take a look? 
Thanks!

2020-04-15 17:52 UTC, andrewbess commented
> -c dev/tests/unit/phpunit.xml.dist

Hello @engcom-Alfa 
It has already done earlier in https://github.com/magento/magento2/pull/27481 but still doesn't merged.

2020-04-16 14:48 UTC, slavvka commented
@andrewbess Please resolve the conflict

2020-04-17 12:27 UTC, andrewbess commented
Hello @slavvka 
Done.
Please check.
Thank you in advance.

2020-04-17 14:55 UTC, lbajsarowicz approved these changes
Looks fine for me.

2020-04-17 14:55 UTC, lbajsarowicz commented on app/code/Magento/SampleData/Test/Unit/Model/DependencyTest.php
> + * @covers \Magento\SampleData\Model\Dependency
It's not crucial to provide that, but it's OK if you put effort on adding it :-)

2020-04-17 16:11 UTC, slavvka approved these changes

2020-04-17 16:11 UTC, merged