[Contact] Fix PHPUnit 8 compatibility issues
magento/magento2 pull request #27637
Opened 2020-04-07 04:16 UTC by srsathish92

### Description (*)
This PR fixes the PHPUnit 8 compatibility issues of existing unit tests for Magento_Contact module.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. magento/magento2##27500

### Manual testing scenarios (*)
1. Run tests in phpunit 6 (currently in 2.4-develop) using vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Contact/
2. Install phpunit 8, run tests using vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Contact/

### Questions or comments
If any please let me know your feedback

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-07 05:12 UTC, dmytro-ch requested changes
Hello @srsathish92, thank you for your contribution!
Could you please fix minor CR recommendations.

Thank you!

2020-04-07 05:12 UTC, dmytro-ch commented on app/code/Magento/Contact/Test/Unit/Block/ContactFormTest.php
> + * Test Covers Magento\Contact\Block\ContactForm
```suggestion
 * @covers \Magento\Contact\Block\ContactForm
```

2020-04-07 05:12 UTC, dmytro-ch commented on app/code/Magento/Contact/Test/Unit/Controller/Index/IndexTest.php
>      private $url;
Please add suffix Mock to the stub properties.
```suggestion
    private $urlMock;
```

2020-04-07 05:12 UTC, dmytro-ch commented on app/code/Magento/Contact/Test/Unit/Controller/Index/IndexTest.php
> + * Test covers Magento\Contact\Controller\Index\Index
Please use `@covers` annotation instead
```suggestion
 * @covers \Magento\Contact\Controller\Index\Index
```

2020-04-07 05:12 UTC, dmytro-ch commented on app/code/Magento/Contact/Test/Unit/Controller/Index/PostTest.php
> + * Test covers Magento\Contact\Controller\Index\Post
```suggestion
 * @covers \Magento\Contact\Controller\Index\Post
```

2020-04-07 07:35 UTC, srsathish92 commented
@dmytro-ch Thanks for the feedback, I have fixed as per your recommendations, can you please review now.

2020-04-07 18:06 UTC, dmytro-ch submitted a review, later dismissed
Hi @srsathish92, great job! Thank you for the updates.

2020-04-07 18:07 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7277](https://jira.corp.magento.com/browse/ENGCOM-7277) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-14 10:03 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:**
![Screenshot from 2020-04-14 13-00-12](https://user-images.githubusercontent.com/51679138/79212462-58c4d700-7e50-11ea-8a58-4ac8a4b36ce7.png)

**After:**
![Screenshot from 2020-04-14 13-02-50](https://user-images.githubusercontent.com/51679138/79212485-637f6c00-7e50-11ea-9a39-f176ca4be7fc.png)

2020-04-14 10:05 UTC, lbajsarowicz requested changes
QA team noticed the leftover when it comes to `@expectedException`

2020-04-14 10:05 UTC, lbajsarowicz commented on app/code/Magento/Contact/Test/Unit/Controller/IndexTest.php
>       * @expectedException \Magento\Framework\Exception\NotFoundException
This one should be replaced with `$this->expectException`

2020-04-15 15:10 UTC, lbajsarowicz approved these changes

2020-04-15 15:11 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7277](https://jira.corp.magento.com/browse/ENGCOM-7277) has been created to process this Pull Request

2020-04-15 17:03 UTC, merged