[Variable] Fix PHPUnit 8 compatibility issues
magento/magento2 pull request #27646
Opened 2020-04-07 20:36 UTC by eduard13

### Description (*)
This PR fixes the PHPUnit 8 compatibility issues of existing unit tests for `Magento_Variable` module. Performed minor code refactoring and code style fixes.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)

1. magento/magento2#27500: Unit Tests incompatible with PHPUnit 8

### Manual testing scenarios (*)

1. Run tests with PHPUnit 6: `vendor/phpunit/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Variable/`
2. Install PHPUnit 8 and run the same tests.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-08 12:55 UTC, rogyar requested changes
Hi @eduard13. Thank you for your contribution. 

Please, check the failing tests. Thank you

2020-04-08 16:46 UTC, eduard13 commented
Hi @rogyar, the Static and Unit tests are failing, because I've replaced the outdated method `assertContains` with `assertStringContainsString`. So the tests will be running using phpunit 8, then there shouldn't be any issues.
If I'm not replacing them, then we'll get some warnings on running.
Should I revert these methods' names?
Thank you.

2020-04-09 11:28 UTC, eduard13 commented
Reverted the outdated methods.

2020-04-12 15:41 UTC, rogyar approved these changes

2020-04-12 15:42 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-7314](https://jira.corp.magento.com/browse/ENGCOM-7314) has been created to process this Pull Request

2020-04-15 11:38 UTC, engcom-Alfa commented
QA not applicable

2020-04-15 17:04 UTC, merged