Add Inline Form Key Updater to Page Cache | Fix Issue #13746
magento/magento2 pull request #27647
Opened 2020-04-08 07:01 UTC by nicolasddev

### Description (*)

This fix ensures that form keys are updated on frontend pages as soon as the form_key input field is loaded in order to prevent delays resulting in the "Invalid Form Key. Please refresh the page" error. 

A script tag with a unique ID is being added and executed inline directly after each form_key input ensuring its value is updated as soon as possible.

An internally-developed extension using the same approach is running on one of our customer's production server preventing this issue from occurring. The issue was more frequently encountered on long category pages due to the fact that the HTML had to be downloaded in multiple packets.

**This fix is provided by [MageMontreal](https://magemontreal.com), a [Magento Business Solution Partner](https://partners.magento.com/portal/details/partner/id/2232).**

### Fixed Issue

- magento/magento2#13746: Add to Cart Form wrong Form Key in FPC

### Manual testing scenarios (*)

1. Create a long category page with several visible products
2. Make sure FPC is enabled and visit the page once with a browser
3. Using another browser or incognito, visit the same page which is now cached
4. Try adding a product to cart without waiting for the page to load

### Comments

Before applying this fix, when a long page or a page requiring several resources was opened, the form keys on the page were not updated immediately as the below script hadn't been executed yet.

**Script:** Magento/PageCache/view/frontend/web/js/page-cache.js

As this fix makes sure that the form keys are each updated inline as soon as the content has been downloaded by the browser, the issue doesn't occur anymore.

**Note:** Uses pure JavaScript to ensure that the scripts are executed without having to wait for RequireJS or any dependencies.

### Functional Requirement
Form key input fields must be integrated to the form through the Magento\Framework\View\Element\FormKey block which is best practice, in order to benefit from this fix/improvement.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-04 07:03 UTC, ihor-sviziev commented
Hi @nicolasddev,
First of all thank you so much for your contribution and I'm really sorry that this PR was not processed for long time. Now I'm going to review it and will try to move it forward.

@magento run all tests

2020-09-04 07:12 UTC, ihor-sviziev requested changes

2020-09-04 07:12 UTC, ihor-sviziev commented on app/code/Magento/PageCache/Plugin/Framework/View/Element/InlineFormKeyUpdater.php
> +        return $result.$this->getInlineJavaScript();
Seems like this shouldn't happen in case if FPC is disabled. Am I correct?

2020-09-04 07:12 UTC, ihor-sviziev commented on app/code/Magento/PageCache/view/frontend/templates/inline_form_key_provider.phtml
> +</script>
1. As Magento introduced CSP - we need to use something like this:
https://github.com/magento/magento2/blob/89d3cda99975c0db2967165311184be84d26e9b4/app/code/Magento/Theme/view/frontend/templates/page/js/require_js.phtml#L15

2. Seems like case with missing form_key cookie isn't covered here
https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L120-L123

3. I think we need to remove following code as we basically replacing it with inline implementation https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L300-L303

2020-09-04 07:12 UTC, ihor-sviziev commented on app/code/Magento/PageCache/Plugin/Framework/View/Element/InlineFormKeyUpdater.php
> +        return '<script id="'.$uniqueId.'">document.getElementById("'.$uniqueId.'").previousSibling.value = formKey;</script>';
As Magento introduced CSP, we need to replace this code with something like this:
https://github.com/magento/magento2/blob/89d3cda99975c0db2967165311184be84d26e9b4/app/code/Magento/Theme/view/frontend/templates/page/js/require_js.phtml#L15

2020-09-07 14:40 UTC, gabrieldagama commented
The risk was set to`medium` due to: the suggested changes may affect other areas/modules.

2020-09-22 07:42 UTC, ihor-sviziev commented
Hi @nicolasddev,
Will you be able to update your PR?

2020-09-23 17:59 UTC, sidolov commented
@nicolasddev  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-23 17:59 UTC, closed without merging