Fixed creating shipping labels in part-shipment
magento/magento2 pull request #27672
Opened 2020-04-09 10:33 UTC by NikolasSumrak

Fixed creating package when we ship not all items

### Description (*)
When we use sources, we can create shipment for only one item from order. In this case when we try to create shipping label with shipment ("Create Shipping Label" Checkbox), the system requires to add all products to package (including products, which wasn't added to shipment) and validation fails.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

0. Have configured shipping method with ability to create Shipping Labels
1. Have 2 products with available in 2 or more sources
2. Add to cart and order both products with shipping method from point 0.
3. Create shipment from admin panel: select source and enter qty only for one product (qty for second product should be 0)
4. Click Proceed to Shipment.
5. Check that only one product in Items to Ship
6. Check checkbox "Create Shipping Label" and press "Submit Shipment..."
7. Click "Add Products to Package". In the list there are both products.
8. When we add to package only one product - the next button is disabled.

Expected result:
7. In the list there is only one product
8. The "Next" button is enabled

### Questions or comments

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [*] All new or changed code is covered with unit/integration tests (if applicable)
 - [*] All automated tests passed successfully (all builds are green)

2020-08-14 20:30 UTC, sidolov commented
@magento create issue

2020-08-20 19:19 UTC, sidolov requested changes
@NikolasSumrak could you please cover changes with automated test?

2020-09-17 15:07 UTC, engcom-Hotel commented
@magento run all tests

2020-09-17 15:34 UTC, engcom-Hotel commented
It is complicated to create MFTF for this change, because of the security issue with storing shipment account credentials. Integration test checks that JS code rendered.

2020-09-21 14:31 UTC, gabrieldagama requested changes
Hi @engcom-Hotel, thanks for adding test coverage, please have a look at my comments below.

2020-09-21 14:31 UTC, gabrieldagama commented on dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php
> +     * @magentoDataFixture Magento/GraphQl/Sales/_files/customer_order_with_ups_shipping.php
Can we use a fixture from the Sales module instead? It sounds more appropriate. Like this one `dev/tests/integration/testsuite/Magento/Sales/_files/order_with_shipping_and_invoice.php`

2020-09-21 14:31 UTC, gabrieldagama commented on dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php
> +        $order = $this->orderFactory->create()->loadByIncrementId('100000001');
Instead of using the `orderFactory` here, it would be more appropriate to depend on `OrderRepositoryInterface` instead.

2020-09-21 14:31 UTC, gabrieldagama commented on dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php
> +     * @magentoDataFixture Magento/GraphQl/Sales/_files/customer_order_with_ups_shipping.php
We may even use the fixture from the `Shipping` module `dev/tests/integration/testsuite/Magento/Shipping/_files/track.php` it also creates an order with shipment.

2020-09-22 12:46 UTC, engcom-Hotel commented
@magento run all tests

2020-09-23 10:10 UTC, gabrieldagama submitted a review, later dismissed

2020-09-23 10:11 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8253](https://jira.corp.magento.com/browse/ENGCOM-8253) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-25 08:48 UTC, engcom-Bravo requested changes
Hello @NikolasSumrak 

Looks like the changes provided in this PR do not fix the original issue
The **Save** button is still disabled when only one product is added to package
![save_button](https://user-images.githubusercontent.com/51680745/94246825-e68b0f00-ff24-11ea-99fc-547525ea71d7.png)

2020-09-29 14:06 UTC, engcom-Hotel commented
Hello @NikolasSumrak, could you please check the previous comment and provide additional information for reproducing process or check provided solution.
Thank you.

2020-10-15 06:24 UTC, engcom-Hotel commented
Will check it

2020-10-15 12:27 UTC, engcom-Bravo commented
@gabrieldagama Can you please review the latest changes? Thank you

2020-10-15 12:44 UTC, gabrieldagama approved these changes

2020-10-15 12:47 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8253](https://jira.corp.magento.com/browse/ENGCOM-8253) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-10-16 11:09 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Install Inventory 
2. Configure a Shipping method with the ability to **Create Shipping Label**, UPS for example
3. Create two **Sources** and **Assign** them to one **Stock**
![1_source_stock](https://user-images.githubusercontent.com/51680745/96248425-402aaa80-0fb4-11eb-87d4-2e6676099f97.png)
4. Create two Products, and **Assign** two previously created **Sources** to each of them
![2_products](https://user-images.githubusercontent.com/51680745/96248703-a4e60500-0fb4-11eb-9198-9e7cae51babd.png)
5. **Submit** an order containing previously created Products and selecting UPS _Shipping Method_
![3_submit_order](https://user-images.githubusercontent.com/51680745/96249126-63a22500-0fb5-11eb-8ffe-66e384a45d5d.png)
6. Go to **Ship**. Select **Source**, set **Qty To Deduct** _1_ for one Product and _0_ for the other Product. Click **Proceed to Shipment**
![4_process](https://user-images.githubusercontent.com/51680745/96249394-c98eac80-0fb5-11eb-8dc4-d2d1757477a9.png)
7. Assert that only 1 Product is listed in _Items to Ship_
8. Check **Create Shiping Label** checkbox and click **Submit Shipment**
![cre_ship_label](https://user-images.githubusercontent.com/51680745/96249638-29855300-0fb6-11eb-9949-0d7a5ee05d99.png)
9. Click **Add Products to Package**. Assert that only one product appeared in the list of Products
![фыыуке_щту](https://user-images.githubusercontent.com/51680745/96251004-710cde80-0fb8-11eb-92c7-0054e63a51c1.png)
10 Check the product and click **Add selected Product(s) to Package**
11. Assert that the **Save** button is active and available

**BEFORE APPLYING CHANGES PROVIDED IN THIS PR**
Two products were available in _Create Packages_ window, despite that _0_ quantity has been set
![two products](https://user-images.githubusercontent.com/51680745/96251414-1b850180-0fb9-11eb-89f8-d3bfd616890d.png)
And before Adding both Products to Package, **Save** button was not available
![Peek 2020-10-16 10-47](https://user-images.githubusercontent.com/51680745/96251480-35bedf80-0fb9-11eb-8f4b-2e0458b32dc7.gif)

2020-10-19 12:17 UTC, gabrieldagama commented
@magento run all tests

2020-10-20 08:59 UTC, gabrieldagama commented
@magento run all tests

2020-10-21 20:38 UTC, merged