[MFTF] Use ActionGroup to open products grid page
magento/magento2 pull request #27697
Opened 2020-04-10 15:55 UTC by Usik2203

### Description (*)

This PR uses `AdminOpenProductIndexPageActionGroup` to go to catalog products grid and removes this part of code
 `<amOnPage url="{{AdminProductIndexPage.url}}" stepKey="visitAdminProductPageBundle"/>`
 `<waitForPageLoad stepKey="waitForProductPageLoadBundle"/>`

2020-04-10 18:32 UTC, lbajsarowicz submitted a review, later dismissed
:heavy_check_mark: Thank you for your effort to improve MFTF Tests! Really appreciate that!

2020-04-10 18:33 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7304](https://jira.corp.magento.com/browse/ENGCOM-7304) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-15 09:23 UTC, engcom-Alfa commented
QA not applicable

2020-04-15 11:23 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2020-04-17 22:08 UTC, slavvka commented
@magento run Functional Tests CE

2020-04-18 03:32 UTC, slavvka requested changes
@Usik2203 Please fix MFTF tests. They are constantly failing.

2020-04-18 19:56 UTC, lbajsarowicz commented
Please add Cron Index for `AdminAddingNewOptionsWithImagesAndPricesToConfigurableProductTest` test before `Go to frontend and check image and price`

2020-05-01 21:33 UTC, VladimirZaets commented
Hi @Usik2203, can you please resolve conflicts?

2020-05-28 14:30 UTC, Usik2203 commented
@magento run all tests

2020-05-30 15:47 UTC, Usik2203 commented
@magento run all tests

2020-06-03 09:57 UTC, Usik2203 commented
@magento run all tests

2020-06-03 10:00 UTC, Usik2203 commented
@magento run all tests

2020-06-08 15:48 UTC, Usik2203 commented
@magento run all tests

2020-06-08 17:22 UTC, Usik2203 commented
@magento run Functional Tests B2B Functional Tests CE Functional Tests EE

2020-06-08 17:22 UTC, Usik2203 commented
@magento run Functional Tests B2B Functional Tests CE Functional Tests EE tests

2020-06-08 17:23 UTC, Usik2203 commented
@magento run Functional Tests B2B test

2020-06-08 17:24 UTC, Usik2203 commented
@magento run Functional Tests B2B

2020-06-08 17:25 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE

2020-06-08 19:38 UTC, Usik2203 commented
Hi @slavvka 
I think failed tests are not related with my changes
Thanks

2020-06-22 20:32 UTC, Usik2203 commented
@magento run all tests

2020-06-23 07:11 UTC, Usik2203 commented
@magento run Functional Tests EE

2020-06-23 09:13 UTC, Usik2203 commented
@magento run all tests

2020-06-23 14:22 UTC, lbajsarowicz approved these changes
Well done!

2020-06-23 14:23 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7304](https://jira.corp.magento.com/browse/ENGCOM-7304) has been created to process this Pull Request

2020-07-03 12:36 UTC, engcom-Delta commented
**Notice:** QA not applicable

2020-07-07 17:34 UTC, slavvka commented
@magento run WebAPI tests

2020-07-07 17:35 UTC, slavvka commented
@magento run WebAPI Tests

2020-07-13 05:54 UTC, slavvka commented
@magento run Integration Tests

2020-07-14 09:40 UTC, Usik2203 commented
@magento run all tests

2020-07-14 18:28 UTC, Usik2203 commented
@magento run all tests

2020-07-15 05:43 UTC, slavvka commented
@magento run all tests

2020-07-16 01:38 UTC, merged