#27500 Prepare Payment module Tests for PHPUnit 8
magento/magento2 pull request #27743
Opened 2020-04-11 12:59 UTC by lbajsarowicz

### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Related Pull Requests

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-16 02:10 UTC, slavvka commented
```
18:23:49 PHP Fatal error:  Declaration of Magento\CustomerBalance\Test\Unit\Model\Cart\SalesModel\OrderTest::setUp() must be compatible with Magento\Payment\Test\Unit\Model\Cart\SalesModel\OrderTest::setUp(): void in /var/www/html/app/code/Magento/CustomerBalance/Test/Unit/Model/Cart/SalesModel/OrderTest.php on line 8
```

2020-04-16 07:13 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,
Could you fix the small issue that I found on review and fatal error that @slavvka wrote above?

2020-04-16 07:13 UTC, ihor-sviziev commented on app/code/Magento/Payment/Test/Unit/Helper/DataTest.php
> +
Could you remove this line?

2020-04-17 16:02 UTC, slavvka requested changes
The same inheritance issue:
```
02:43:31 PHP Fatal error:  Declaration of Magento\CustomerBalance\Test\Unit\Model\Cart\SalesModel\OrderTest::setUp() must be compatible with Magento\Payment\Test\Unit\Model\Cart\SalesModel\OrderTest::setUp(): void in /var/www/html/app/code/Magento/CustomerBalance/Test/Unit/Model/Cart/SalesModel/OrderTest.php on line 8
```

2020-04-22 14:09 UTC, slavvka commented
Unit EE, B2B:
```
15:41:16 PHP Fatal error:  Declaration of Magento\CustomerBalance\Test\Unit\Model\Cart\SalesModel\OrderTest::setUp() must be compatible with Magento\Payment\Test\Unit\Model\Cart\SalesModel\OrderTest::setUp(): void in /var/www/html/app/code/Magento/CustomerBalance/Test/Unit/Model/Cart/SalesModel/OrderTest.php on line 8
```

2020-04-23 22:01 UTC, slavvka commented
@magento run all tests

2020-04-23 22:40 UTC, slavvka approved these changes

2020-04-23 22:41 UTC, slavvka approved these changes

2020-04-23 22:42 UTC, merged