#27500 Prepare Vault module Tests for PHPUnit 8
magento/magento2 pull request #27762
Opened 2020-04-11 18:07 UTC by lbajsarowicz

### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Related Pull Requests

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-13 13:54 UTC, ihor-sviziev requested changes

2020-04-13 13:54 UTC, ihor-sviziev commented on app/code/Magento/Vault/Test/Unit/Model/PaymentTokenRepositoryTest.php
> +     * @var \PHPUnit\Framework\MockObject\MockObject
Please import this class

2020-04-13 13:54 UTC, ihor-sviziev commented on app/code/Magento/Vault/Test/Unit/Model/Ui/Adminhtml/TokensConfigProviderTest.php
> +     * @return \PHPUnit\Framework\MockObject\MockObject
Please import this class

2020-04-13 13:54 UTC, ihor-sviziev commented on app/code/Magento/Vault/Test/Unit/Model/Ui/Adminhtml/TokensConfigProviderTest.php
> +     * @return \PHPUnit\Framework\MockObject\MockObject
Please import this class

2020-04-15 06:46 UTC, ihor-sviziev approved these changes

2020-04-15 06:47 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7419](https://jira.corp.magento.com/browse/ENGCOM-7419) has been created to process this Pull Request

2020-04-15 18:42 UTC, merged