#27500 Prepare Integration module Tests for PHPUnit 8
magento/magento2 pull request #27778
Opened 2020-04-11 21:09 UTC by lbajsarowicz

### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Related Pull Requests

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-13 13:09 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2020-04-13 13:18 UTC, ihor-sviziev requested changes

2020-04-13 13:18 UTC, ihor-sviziev commented on app/code/Magento/Integration/Test/Unit/Controller/Adminhtml/IntegrationTest.php
> -            [\Magento\Backend\Model\Layout\Filter\Acl::class, $this->_layoutFilterMock],
Why it was removed?

2020-04-13 13:18 UTC, ihor-sviziev commented on app/code/Magento/Integration/Test/Unit/Model/IntegrationServiceTest.php
> -            Integration::EMAIL => self::VALUE_INTEGRATION_ENDPOINT,
Good catch!

2020-04-16 08:35 UTC, ihor-sviziev commented on app/code/Magento/Integration/Test/Unit/Controller/Adminhtml/IntegrationTest.php
> -            [\Magento\Backend\Model\Layout\Filter\Acl::class, $this->_layoutFilterMock],
Ah, I see it wasn't used

2020-04-16 08:36 UTC, ihor-sviziev approved these changes

2020-04-16 08:37 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7444](https://jira.corp.magento.com/browse/ENGCOM-7444) has been created to process this Pull Request

2020-04-16 14:39 UTC, merged