#27500 Prepare Sitemap module Tests for PHPUnit 8
magento/magento2 pull request #27775
Opened 2020-04-11 20:09 UTC by lbajsarowicz

### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Related Pull Requests

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-13 16:01 UTC, rogyar requested changes
The last easter egg is hiding from you here :)

https://github.com/magento/magento2/blob/c430b263e2115ce32fd76a9bc41e9e16d029d4f2/app/code/Magento/Sitemap/Test/Unit/Model/SitemapTest.php#L215

2020-04-15 12:47 UTC, rogyar commented
Hi @lbajsarowicz. Looks like we have another conflict here as well.

2020-04-15 23:51 UTC, slavvka approved these changes

2020-04-15 23:52 UTC, magento-engcom-team commented
Hi @slavvka, thank you for the review.
[ENGCOM-7436](https://jira.corp.magento.com/browse/ENGCOM-7436) has been created to process this Pull Request

2020-04-15 23:53 UTC, merged