#27500 Prepare Braintree module Tests for PHPUnit 8
magento/magento2 pull request #27803
Opened 2020-04-11 23:00 UTC by lbajsarowicz

### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Related Pull Requests

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-16 04:42 UTC, slavvka commented
```
09:03:13 Fatal error: Class Mock_RequestInterface_a2b28d50 contains 8 abstract methods and must therefore be declared abstract or implement the remaining methods (Magento\Framework\App\RequestInterface::getModuleName, Magento\Framework\App\RequestInterface::setModuleName, Magento\Framework\App\RequestInterface::getActionName, ...) in /var/www/html/vendor/phpunit/phpunit-mock-objects/src/Generator.php(264) : eval()'d code on line 1
```

2020-04-16 08:31 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,
Please fix the issues I found and fatal error that @slavvka mentioned above.

2020-04-16 08:31 UTC, ihor-sviziev commented on app/code/Magento/Braintree/Test/Unit/Gateway/Request/KountPaymentDataBuilderTest.php
> +     * @var SubjectReader|\PHPUnit\Framework\MockObject\MockObject
Please import this class

2020-04-16 08:31 UTC, ihor-sviziev commented on app/code/Magento/Braintree/Test/Unit/Gateway/Request/PaymentDataBuilderTest.php
> +use PHPUnit\Framework\MockObject\MockObject as MockObject;
I see in many classes you have construction like that. Could you replace it by following?
```suggestion
use PHPUnit\Framework\MockObject\MockObject;
```

2020-04-16 08:31 UTC, ihor-sviziev commented on app/code/Magento/Braintree/Test/Unit/Gateway/Request/ThreeDSecureDataBuilderTest.php
> +     * @var SubjectReader|\PHPUnit\Framework\MockObject\MockObject
Please import this class

2020-04-16 08:31 UTC, ihor-sviziev commented on app/code/Magento/Braintree/Test/Unit/Gateway/Request/VoidDataBuilderTest.php
> +     * @var SubjectReader|\PHPUnit\Framework\MockObject\MockObject
Please import this class

2020-04-16 08:31 UTC, ihor-sviziev commented on app/code/Magento/Braintree/Test/Unit/Gateway/Response/ThreeDSecureDetailsHandlerTest.php
> +     * @var SubjectReader|\PHPUnit\Framework\MockObject\MockObject
Please import it

2020-04-16 08:31 UTC, ihor-sviziev commented on app/code/Magento/Braintree/Test/Unit/Model/Paypal/Helper/QuoteUpdaterTest.php
> +    private function updateAddressDataStep(\PHPUnit\Framework\MockObject\MockObject $address, array $addressData): void
Could you import it?

2020-04-16 14:44 UTC, slavvka commented
```
21:19:42 Fatal error: Class Mock_RequestInterface_aa8ba27b contains 8 abstract methods and must therefore be declared abstract or implement the remaining methods (Magento\Framework\App\RequestInterface::getModuleName, Magento\Framework\App\RequestInterface::setModuleName, Magento\Framework\App\RequestInterface::getActionName, ...) in /var/www/html/vendor/phpunit/phpunit-mock-objects/src/Generator.php(264) : eval()'d code on line 1
```

2020-04-17 12:46 UTC, ihor-sviziev approved these changes
✔ Approved 
I did small fix on one file, but everything else looked fine and unit tests were passing on last commit.

2020-04-17 14:43 UTC, merged