Trim data before comparing on sales guest form
magento/magento2 pull request #27840
Opened 2020-04-13 12:54 UTC by themystery404

### Description (*)

Added trimming of the data before comparing Stored billing data with input on Order information page
### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27837: Data in Order information page is not trimming before comparring

### Manual testing scenarios (*)

1. Place order
2. Go to http://example.com/sales/guest/form/
3. Try to find order with additional space in the end of "Billing Last Name" or "Billing ZIP Code"

Another case:
1. Place order with additional space in Billing Last Name
2. Go to http://example.com/sales/guest/form/
3. Try to find order without space in the end of Billing last Name

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-28 07:21 UTC, themystery404 commented
I founded, that order number in form also not trimmed. Added one more commit with trimming for order number in postData.

2020-08-27 20:20 UTC, sidolov requested changes
@themystery404 , please, sign Adobe CLA along with Olga Zakharchuk since the PR contain commits from two accounts.

2020-09-07 14:31 UTC, gabrieldagama commented
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

2020-09-11 15:29 UTC, sidolov commented
@themystery404  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-11 15:29 UTC, closed without merging