Extended message queue consumer configuration with parameters "maxIdl…
magento/magento2 pull request #27850
Opened 2020-04-14 09:26 UTC by Neos2007

Extended message queue consumer configuration with parameters "maxIdleTime", "sleep" and "onlySpawnWhenMessageAvailable". Created logic for checking/handling these parameters during firing/executing queue consumers. Updated unit tests.

### Description (*)
Current pull request extends existed message queue consumers logic and adds support of new consumers configuration parameters: "maxIdleTime", "sleep" and "onlySpawnWhenMessageAvailable". 
PR was created based on ["Improvements to message queue consumer processes"](https://github.com/magento/architecture/blob/master/design-documents/asynchronous-operations/consumer-processes-improvements.md) (Problem 1: not enough options to keep consumers under control).
#### Description new consumers parameters:
*"maxIdleTime"* - Describes max time (in seconds) of waiting for a new message from the queue.
*"sleep"* - Time (in seconds) to sleep before checking if a new message is available in the queue.
*"onlySpawnWhenMessageAvailable"* - (boolean value) identifies that consumer should be spawned only if there are available message in the related queue.

Parameters "maxIdleTime" and "sleep" are currently used only in Magento\Framework\MessageQueue\CallbackInvoker class (so they will be handled only for Consumers which was fired with defined "maxNumberOfMessages" parameter)
Parameter "onlySpawnWhenMessageAvailable" currently checks/validates via ConsumersRunner cron (\Magento\MessageQueue\Model\Cron\ConsumersRunner).

All new parameters for consumers could be configured either via queue_consumer.xml configuration files (as attributes for the consumer node) or via env.php file:
```
    <consumer name="consumer1" queue="queue1" handler="handlerClassOne::handlerMethodOne" consumerInstance="consumerClass1" connection="connection1" maxMessages="200" maxIdleTime="500" sleep="5" onlySpawnWhenMessageAvailable="true"/>

 'consumers' =>[
     'consumer1' => [
        'name' => 'consumer1',
        'queue' => 'queue1',
        'consumerInstance' => 'consumerClass1',
        'handlers' => [
            0 => [
                'type' => 'handlerClassOne',
                'method' => 'handlerMethodOne'
            ],
        ],
        'connection' => 'connection1',
        'maxMessages' => '200',
        'maxIdleTime' => '500',
        'sleep' => '5',
        'onlySpawnWhenMessageAvailable' => true
    ]
]
```

### Manual testing scenarios (*)

For testing could be extended existed consumers configuration (via queue_consumer.xml or via env.php file).
Testing 'onlySpawnWhenMessageAvailable' parameter. 
1. Configure 'onlySpawnWhenMessageAvailable' parameter as "true" for one of the consumers. 
2. Make sure that cron run is allowed for cron consumers in env.php (parameter 'cron_consumers_runner/cron_run' should be set as true or should not be defined, parameter 'cron_consumers_runner/consumers' should be empty or include all consumers).
4. Make sure that all messages related to the consumer queue were processed and there are no new messages. 
3. Disable external triggering of running Magento cron jobs.
4. Kill the PHP (if run) processes that trigger running needed consumer.
5. Run Magento cron CLI command with '--group="consumers"' parameter (php bin/magento  cron:run --group="consumers).
6. Wait 15-20 seconds after executing CLI command and Check currently executed php processes. There should not be a process which runs tested consumer.
7. Publish new messages in the queue that is processed by the tested consumer.
8. Re-run magento CLI cron:run command for "consumers" group.
10. Check currently executed php processes. There should be the php process that executes (starts) your consumer.
You can test consumers behavior with and without  'onlySpawnWhenMessageAvailable' parameter debugging process running consumers via cron (debug \Magento\MessageQueue\Model\Cron\ConsumersRunner::run() method execution).

Testing "maxIdleTime" and "sleep" methods are could be done via the debugging processing consumer process.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-14 19:22 UTC, hostep commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
@Neos2007: awesome for you to start working on this, big thanks for that!

I'm wondering though how this behaves? It will remove a message from the queue if there is one, and it will get rejected and put back in the queue, is that correct?
Will doing so change the order of the messages?

In case you weren't aware, I wrote a proof of concept a while ago, which took a different approach: https://github.com/hostep/magento2/compare/d93d288...poc-consumer-improvements (check the `hasMessages` methods).
I'm not saying my way is better, just wanted to inform you about it. Since I'm not super familiar with message queues and how they work/behave.

Thanks again!

2020-04-15 07:20 UTC, nuzil commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
Hi @hostep 
Its will read mesasge from queue and if there is any set, it will mark message as Unread and system will know that it have to be still processed

2020-04-15 07:31 UTC, nuzil commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
@hostep you are subscribed to all PRs that are related to consumers? :-D

2020-04-15 08:01 UTC, hostep commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
@nuzil: it was completely by accident that I noticed it, no worries, I do have a life (sometimes) 😉 

If a message gets marked as unread, will it be moved at the end of the queue, or will it keep its position in the queue? Changing positions might be unexpected (even though the order in queues is probably not very important, it might be confusing).

2020-04-15 09:10 UTC, Neos2007 commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
@hostep After reading (dequeue) message from the queue it will be just rejected.
So will be applied the same logic as already implemented with poisonPill:
lib/internal/Magento/Framework/MessageQueue/CallbackInvoker.php
`if (false === $this->poisonPillCompare->isLatestVersion($this->poisonPillVersion)) {
                $queue->reject($message);
                // phpcs:ignore Magento2.Security.LanguageConstruct.ExitUsage
                exit(0);
            }`

2020-04-15 19:17 UTC, hostep commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
Thanks for not answering my question 😉 

Anyway, I don't really like the fact that checking if a message is available, manipulates the queue. Since it doesn't look like an atomic action.
What happens when the server crashes/reboots just after `dequeue` and before `reject`, will the message be lost?

2020-04-16 13:21 UTC, nuzil commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
Its not manipulating with messages. If your server may crash any time, I assume you are risking with much more then missed message :-). And in this case with message still nothing will happen.
Also we implementing Framework queue interface, which at same time implements Mysql and Amqp adapters, which also leave open possibility to add another adapters if required.

2020-04-16 13:26 UTC, nuzil submitted a review, later dismissed

2020-04-16 13:27 UTC, magento-engcom-team commented
Hi @nuzil, thank you for the review.
[ENGCOM-7449](https://jira.corp.magento.com/browse/ENGCOM-7449) has been created to process this Pull Request

2020-04-16 13:37 UTC, hostep commented on app/code/Magento/MessageQueue/Model/CheckIsAvailableMessagesInQueue.php
> +    }
Ok thanks for the replies gents!

2020-05-08 10:31 UTC, nuzil approved these changes

2020-05-08 10:33 UTC, magento-engcom-team commented
Hi @nuzil, thank you for the review.
[ENGCOM-7449](https://jira.corp.magento.com/browse/ENGCOM-7449) has been created to process this Pull Request

2020-06-01 15:20 UTC, Neos2007 commented
@magento run all tests

2020-07-14 14:51 UTC, adifucan commented
Hi @Neos2007! What is the status of this PR? Are you going to proceed with it? 
Last builds were green. So why was this PR not merged? Now Semantic Version check fails because of updated xsd schema with new attributes. But it's not a big deal I guess. 
Please, let me know the status of your PR. Thanks!

2020-07-15 00:19 UTC, adifucan requested changes
Please, check my review comment about CallbackInvoker::invoke $sleep variable. No more review comments from my side.
I also tested your solution: `maxIdleTime, sleep, onlySpawnWhenMessageAvailable` options work fine.
I ran all tests against your code and only Semantic Version Checker fails with minor changes because of new options added to xsd schema. I guess it should be approved.
Please, let me know if you need any assistance with your PR. Thanks! Good job!

2020-07-15 00:19 UTC, adifucan commented on lib/internal/Magento/Framework/MessageQueue/CallbackInvoker.php
> +        $sleep = (int) $sleep ?? 1;
Incorrect logic here. Check this out:
```
$foo = (int) null ?? 1;
// $foo is (int) 0
$bar = (int) null ?: 1;
// $bar is (int) 1
```
So all consumers without `sleep` parameter get `0` sleep time and they are constantly asking queue for messages. As a result CPU and other resources of all consumers with `$sleep = null` are overloaded.

Please, refactor it to `$sleep = (int) $sleep ?: 1;`

2020-07-15 17:05 UTC, vzabaznov commented
Hi @Neos2007 
Thank you for your contribution, we found this PR very helpful and we are going to proceed with it by our internal team.
Once we merge it, status of this will be changed to _merged_.
Thanks.

2020-07-16 08:05 UTC, Neos2007 commented on lib/internal/Magento/Framework/MessageQueue/CallbackInvoker.php
> +        $sleep = (int) $sleep ?? 1;
@adifucan I applied changes which you mentioned above.

2020-07-16 15:48 UTC, adifucan approved these changes

2020-07-16 22:06 UTC, vzabaznov approved these changes

2020-07-17 20:34 UTC, merged