Don't load datepicker module until it is actually needed
magento/magento2 pull request #27860
Opened 2020-04-15 07:29 UTC by krzksz

### Description (*)
This PR is a part of my effort to improve Magento 2 frontend performance.

Goal here is to eliminate unnecessary loading of datepicker UI component, which is only needed when the shop has date of birth field enabled.

#### Performance improvement

Tested on Magento 2.4-develop with Luma and sample data. 

- 205 → 202 JS requests (-1.46%).
- 698.40kB → 652.57kB JS transferred (-6.56%).

### Manual testing scenarios (*)

1. Enable date of birth field for customers in admin panel.
2. Verify that `Magento_Ui/js/lib/knockout/bindings/datepicker.js` is not loaded on pages that do not use datepicker (e.g. homepage, category, product etc.).
3. Verify that above file is loaded and datepicker works properly on pages that use it (e.g. customer registration form page).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-15 11:24 UTC, ihor-sviziev requested changes
Hi @krzksz,
Please review failing tests, looks like date format has changed

2020-04-18 16:53 UTC, ihor-sviziev requested changes
Hi @krzksz,
Functional tests still fails due to incorrect date format, please fix it

2020-04-19 08:39 UTC, krzksz commented
@magento give me test instance

2020-04-19 08:39 UTC, magento-engcom-team commented
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

2020-04-19 08:42 UTC, magento-engcom-team commented
Hi @krzksz, here is your [new Magento instance](https://pr-27860.instances.magento-community.engineering).
Admin access: [https://pr-27860.instances.magento-community.engineering/admin_be04](https://pr-27860.instances.magento-community.engineering/admin_be04)
Login: `de96da0c` Password: `f341cfebc4ef`
Instance will be terminated in up to 3 hours.

2020-04-19 11:44 UTC, ihor-sviziev approved these changes
✅ approved 
Failing functional tests for EE isn’t related to changes from this PR

2020-04-19 11:47 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7459](https://jira.corp.magento.com/browse/ENGCOM-7459) has been created to process this Pull Request

2020-04-21 07:47 UTC, krzksz commented
@ihor-sviziev I'm not sure about `Auto-Tests: Not Required` because I had to adjust unit tests in order for the new logic to pass them 🤔

2020-04-21 09:34 UTC, engcom-Alfa commented
Hi @krzksz .
During testing, we faced with one question.

`Magento_Ui/js/lib/knockout/bindings/datepicker.js` loaded on pages that do not use datepicker (e.g. homepage, category, product).

Tested on Magento 2.4-develop with Luma and sample data.

**Actual Result:**
![Peek 2020-04-21 12-29](https://user-images.githubusercontent.com/51679138/79850100-1c532700-83cc-11ea-8eab-0dbae76461fd.gif)

@krzksz Could you take a look?
Thanks!

2020-04-21 09:41 UTC, krzksz commented
@engcom-Alfa Sorry, it was my mistake in the description. The file that should not be loaded is actually `jquery/ui-modules/datepicker.js`, while this binding should be loaded always just as on your screenshot.

2020-04-21 09:44 UTC, engcom-Alfa commented
@krzksz Thank you for the clarification!

2020-04-21 10:15 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Tested on Magento 2.4-develop with Luma and sample data.

**Manual testing scenario:**
1. Enable date of the birth field for customers in admin;
2. Go to Storefront (Home page) and open developer tool

**Before:** :heavy_multiplication_x:` jquery/ui-modules/datepicker.js` loaded on pages that do not use datepicker (e.g. homepage, category, product etc.).
![after](https://user-images.githubusercontent.com/51679138/79853402-aef5c500-83d0-11ea-91e7-f3758ed52a6c.png)

**After:** :heavy_check_mark: ` jquery/ui-modules/datepicker.js` isn't loaded on pages that do not use datepicker (e.g. homepage, category, product etc.)
![Screenshot from 2020-04-21 12-54-27](https://user-images.githubusercontent.com/51679138/79853519-d77dbf00-83d0-11ea-8b79-f7444dd48fdd.png)

3. Go to the Customer registration page;

**Actual Result:**
:heavy_check_mark: `Magento_Ui/js/lib/knockout/bindings/datepicker.js` is loaded and datepicker works properly (tested on _customer registration_ page and _edit customer information page_)
![Screenshot from 2020-04-21 13-10-19](https://user-images.githubusercontent.com/51679138/79854030-7c989780-83d1-11ea-8873-343d1e871929.png)

**Performance improvement:**
212 -> 209 requests (-1.46%)
652kB → 606kB JS transferred (-7.5%).

2020-04-21 14:47 UTC, ptylek approved these changes

2020-04-21 14:48 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-7459](https://jira.corp.magento.com/browse/ENGCOM-7459) has been created to process this Pull Request

2020-04-24 19:38 UTC, DrewML commented on app/code/Magento/Ui/view/base/web/js/lib/knockout/bindings/datepicker.js
> +            require(['moment', 'mage/utils/misc', 'mage/calendar'], function (moment, utils) {
Looks like, if we move the `_.isEmpty(observable)` check outside the `require`, we can avoid loading `moment` and ``mage/utils/misc` in some cases, right?

2020-04-24 19:38 UTC, DrewML approved these changes
Fantastic work! Suggested one additional optimization, but looks great!

2020-06-22 09:36 UTC, engcom-Delta commented
@magento create issue

2020-06-24 06:49 UTC, merged