Improve opendialogurl configuration to be extensible
magento/magento2 pull request #27863
Opened 2020-04-15 11:47 UTC by Nazar65

### Description (*)

### Related Pull Requests
https://github.com/magento/adobe-stock-integration/pull/1186
https://github.com/magento/magento2-page-builder/pull/450

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
N/A
### Manual testing scenarios (*)
Verify that media gallery opened corrects in all cases
1.with AdobeStockIntegration && PageBuilder

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-15 12:13 UTC, Nazar65 commented
Functional Test failing on Page Builder repo on dev branch, as pr linked with PB, they are failing too,
This failure not related to the changes in this pr

2020-04-15 12:51 UTC, sivaschenko requested changes

2020-04-15 12:51 UTC, sivaschenko commented on app/code/Magento/Ui/Component/Form/Element/DataType/Media/OpenDialogUrl.php
> +    public function __construct(string $openDialog = null)
The class name already contains `OpenDialog`
```suggestion
    public function __construct(string $url = null)
```

2020-04-15 12:51 UTC, sivaschenko commented on app/code/Magento/Ui/Component/Form/Element/DataType/Media/OpenDialogUrl.php
> +    public function getOpenDialogUrl(): string
To avoid duplicate naming between class and method
```suggestion
    public function get(): string
```

2020-04-15 12:51 UTC, sivaschenko commented on app/code/Magento/Ui/Component/Form/Element/DataType/Media/Image.php
> +    private $openDialogConfig;
Let's keep consistent naming between class, property and variable to avoid confusion
```suggestion
    private $openDialogUrl;
```

2020-04-15 13:09 UTC, engcom-Golf commented
@magento run all tests

2020-04-15 13:26 UTC, engcom-Golf commented
@magento run all tests

2020-04-15 13:28 UTC, sivaschenko requested changes
Thanks for the update @Nazar65 !

Can we also use the OpenDialogUrl provider in:
* \Magento\Cms\Model\Wysiwyg\Gallery\DefaultConfigProvider::getConfig
* \Magento\Tinymce3\Model\Config\Gallery\Config::getConfig

2020-04-15 13:55 UTC, engcom-Golf commented
@magento run all tests

2020-04-15 14:12 UTC, engcom-Golf commented
@magento run all tests

2020-04-15 15:00 UTC, sivaschenko approved these changes

2020-04-15 15:02 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7433](https://jira.corp.magento.com/browse/ENGCOM-7433) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-15 15:54 UTC, sivaschenko approved these changes

2020-04-15 15:55 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7433](https://jira.corp.magento.com/browse/ENGCOM-7433) has been created to process this Pull Request

2020-04-15 22:16 UTC, slavvka commented
@magento run all tests

2020-04-16 01:43 UTC, slavvka commented
@magento run all tests

2020-04-16 04:36 UTC, slavvka requested changes
@Nazar65 Please fix the failing tests

2020-04-16 06:32 UTC, Nazar65 commented
@magento run all tests

2020-04-16 06:32 UTC, engcom-Golf commented
@magento run all tests

2020-04-16 06:53 UTC, engcom-Golf commented
@magento run all tests

2020-04-16 14:32 UTC, Nazar65 commented
Closing as this changes moved to https://github.com/magento/magento2/pull/27566

2020-04-16 14:32 UTC, closed without merging