\Magento\Framework\Filesystem\Io\File::read() should be able to accept resource in second argument
magento/magento2 pull request #27869
Opened 2020-04-15 16:28 UTC by bnymn

\Magento\Framework\Filesystem\Io\File::read() method is not compatible with the `IoInterface`. This PR aims to make it compatible.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27866: \Magento\Framework\Filesystem\Io\File::read() method is not compatible with \Magento\Framework\Filesystem\Io\IoInterface::read()

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-18 15:11 UTC, lenaorobei commented on lib/internal/Magento/Framework/Filesystem/Test/Unit/Io/FileTest.php
> +    public function read_should_copy_the_source_file_to_the_given_file_resource()
Please follow `camelCase` naming.

2020-08-18 15:11 UTC, lenaorobei commented on lib/internal/Magento/Framework/Filesystem/Test/Unit/Io/FileTest.php
> +    protected function setUp()
Looks like redundant.

2020-08-18 15:12 UTC, lenaorobei requested changes
Please sign CLA and address test failures.

2020-08-26 06:21 UTC, engcom-Charlie commented
Hi @bnymn, please sign CLA and look through failed tests. Otherwise, we can't proceed with your PR.

2020-08-26 07:02 UTC, engcom-Charlie commented
@magento run all tests

2020-08-26 10:20 UTC, engcom-Charlie commented
@magento run all tests

2020-08-26 18:17 UTC, lenaorobei commented
@magento run all tests

2020-08-26 19:36 UTC, lenaorobei commented
@magento run Static Tests

2020-09-02 11:55 UTC, engcom-Charlie commented
Hi, @bnymn can you please fix static tests?
Thank you.

2020-09-02 18:36 UTC, engcom-Charlie commented
@magento run all tests

2020-09-03 14:13 UTC, lenaorobei approved these changes

2020-09-03 14:16 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-8127](https://jira.corp.magento.com/browse/ENGCOM-8127) has been created to process this Pull Request

2020-09-23 10:48 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
**Result:**
Code snippet for testing:
```
$file = ObjectManager::getInstance()->get(File::class);
        if (!is_dir('var/tmp_1')) {
            // dir doesn't exist, make it
            mkdir('var/tmp_1');
        }
        file_put_contents('var/tmp_1/sample_file', 'Some test file');
        $targetHandle = fopen('var/tmp_1/' . rand(), 'w');
        $file->cd('var/tmp_1');
        $result = $file->read('sample_file', $targetHandle);
        $output->writeln($result);

```
**Before:**
:x: $result is `null`
![image](https://user-images.githubusercontent.com/51681379/93985579-f2909880-fd8d-11ea-8ac1-e9604a618d2c.png)

**After:**
:heavy_check_mark: File content is copied to the target path
![image](https://user-images.githubusercontent.com/51681379/93993456-71d69a00-fd97-11ea-963c-52404298cf1b.png)

:heavy_check_mark: File is copied to the target file when second argument is string only: `$result = $file->read('sample_file', 'test');
![image](https://user-images.githubusercontent.com/51681379/94002847-21653980-fda3-11ea-82bc-4c4f5cc1a451.png)

2020-09-24 14:34 UTC, engcom-Delta commented
**Note:** Automation tests are passed

2020-09-25 19:04 UTC, merged