Prevent product gallery elements from blinking when they load
magento/magento2 pull request #27871
Opened 2020-04-16 06:16 UTC by krzksz

### Description (*)
In this PR I would like to improve the loading experience of the gallery on product page. On the attached screenshot you can see that there are small periods of time when:
1. Product image disappears and there is a white space until gallery initializes and its images load.
2. Left arrow is shown and then hidden after gallery loads.
#### Before:
![Gallery loading before changes](https://user-images.githubusercontent.com/829189/79420328-04893680-7fb9-11ea-915b-7448c938c355.gif)
#### After:
![Gallery loading after changes](https://user-images.githubusercontent.com/829189/79420718-c6d8dd80-7fb9-11ea-9763-19def6a5991a.gif)
_Note: There is a loader shown properly for a few frames, it just didn't get captured on the gif._
### Manual testing scenarios (*)

1. Gallery placeholder image is positioned properly (as before) on all supported browsers and resolutions.
2. Gallery works as before when initialized.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-16 08:53 UTC, ihor-sviziev requested changes
Hi @krzksz,
Your changes looks good to me!
Could you review unit & static test failures and update your PR?

2020-04-18 14:07 UTC, krzksz commented
All tests green 💚

2020-04-18 14:08 UTC, ptylek approved these changes

2020-04-18 14:09 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-7456](https://jira.corp.magento.com/browse/ENGCOM-7456) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-18 14:31 UTC, ptylek commented
@krzksz do you think this change could have some additional tests? it seems rather as improvement rather than gallery functionality change and all current tests have passed.

2020-04-18 14:33 UTC, krzksz commented
I think it is impossible to cover this change with anything automatic. There are already some unit tests which failed previously and I had to adjust them so the implementation is untouched.

2020-04-18 14:34 UTC, ptylek commented
@krzksz Thanks!

2020-04-18 16:54 UTC, ihor-sviziev approved these changes

2020-04-18 16:55 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7456](https://jira.corp.magento.com/browse/ENGCOM-7456) has been created to process this Pull Request

2020-04-21 14:21 UTC, krzksz commented
I actually found a better, more flexible way of doing it.

2020-04-21 14:49 UTC, ptylek approved these changes

2020-04-21 14:50 UTC, ptylek commented
> I actually found a better, more flexible way of doing it. Instead of making the image positioned absolutely, it is more stable to position fotorama stage. I'll make adjustments ASAP.

@krzksz nice find!

2020-04-21 14:51 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-7456](https://jira.corp.magento.com/browse/ENGCOM-7456) has been created to process this Pull Request

2020-04-21 19:25 UTC, krzksz commented
@magento run all tests

2020-04-22 07:22 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: white space and left arrow are shown until the gallery is loading
![Peek 2020-04-22 09-54](https://user-images.githubusercontent.com/51679138/79952112-93e38d80-8482-11ea-8532-773075b67431.gif)

After: :heavy_check_mark: 
![Peek 2020-04-22 10-06](https://user-images.githubusercontent.com/51679138/79952159-a78ef400-8482-11ea-9a58-02e21fed676d.gif)

2020-05-22 16:23 UTC, sdzhepa commented
@magento create issue

2020-05-22 18:12 UTC, sdzhepa commented
@magento run all tests

2020-05-26 19:33 UTC, engcom-Echo commented
@magento run all tests

2020-05-27 09:19 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-05-27 21:35 UTC, slavvka commented
@magento run all tests

2020-06-05 15:43 UTC, merged