Fix 24666 disabled modules still included less files
magento/magento2 pull request #27888
Opened 2020-04-17 17:37 UTC by mrtuvn

### Description (*)

This PR bring the patch for fix issue modules disabled still include less files. It's should not included in output final style files. Previously styles still included in output final css styles

### Related Pull Requests

Keep continue works by @Echron after long inactivity in PR 25183

### Fixed Issues (if relevant)

1. magento/magento2#24666: Static content is deploying for disabled modules

### Manual testing scenarios (*)

1. Magento 2.3.4+
2. blank or luma theme
3. Disable a couple module use less styles
4. Run deploy static content

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-17 21:48 UTC, hostep commented
@mrtuvn: thanks for picking this up!
Have you also tried this much simpler solution already: https://github.com/magento/magento2/pull/25183#issuecomment-545508802 ?

It was determined to be a better solution during the contribution day at Magento Live Europe last year. The original pull request was determined to not being the best possible solution. And the core Magento developers who were there said it would not be accepted.

Sorry for not having picked this up myself yet, I simply don't have adequate time at the moment to start figuring out how to make extra tests for that simpler solution.

2020-04-18 02:25 UTC, mrtuvn commented
sure i will take a try on that approach

2020-04-18 15:11 UTC, hostep commented
The failing integration test looks like a problem which [I fixed before](https://github.com/magento/magento2/pull/25296) in scope of this issue you are trying to fix, but seems like part of that fix got reverted again by [MC-31752](https://github.com/magento/magento2/commit/811097da79b9bcd65c2b8e260715aa77f56beaaf) which is slightly annoying. I'll take a quick look to see if we can fix that again ...

2020-04-18 16:00 UTC, hostep commented
Ok done, PR https://github.com/magento/magento2/pull/27892 fixes the failing integration tests in this PR.

2020-04-20 03:26 UTC, mrtuvn commented
Still have some issue with test 
Newsletter + Stagging

2020-04-22 12:13 UTC, ihor-sviziev approved these changes

2020-04-22 12:17 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7466](https://jira.corp.magento.com/browse/ENGCOM-7466) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-22 12:17 UTC, ihor-sviziev commented
Test failures looks not related to changes from this PR

2020-04-22 12:26 UTC, ihor-sviziev requested changes
Hi @mrtuvn,
I just double checked and found that you changed is named "../Decorator/**ModuleOutput**.php", so it should filter by module output, not by enabled module or not.

I think we can't use accept it as is, instead we need to create similar class in the same namespace, but name it as "../Decorator/**ModuleEnabled**.php" and use it as decorator in di.xml.

Could you update your PR? Sorry for confusing you.

2020-04-22 15:28 UTC, mrtuvn commented
Added Decorator Filter modules Enabled with test coverage too

2020-04-23 04:36 UTC, ihor-sviziev submitted a review, later dismissed
Approved. Failing tests are not related to changes from this PR.
I think writing integration test for this feature will be really hard, so I put there label not required. Unfortunately unit test that was added isn’t covering the bug itself

2020-04-23 04:37 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7466](https://jira.corp.magento.com/browse/ENGCOM-7466) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-23 05:54 UTC, mrtuvn commented
@ihor-sviziev can we have some tests case on this ?
minify, merge assets case

2020-04-23 05:59 UTC, ihor-sviziev commented
@mrtuvn 
I think best of all there will fit integration tests, but I don’t see any examples for similar cases. If you could cover it - that would be awesome 👏!

2020-04-23 10:50 UTC, mrtuvn commented
@ihor-sviziev current i'm not sure how to test with integration. 
Just tests with unit in my local and also run some checks in production mode too
If you guys need update in PR please let me know

2020-04-24 12:20 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

### Case 1. Blank theme

**Manual testing scenario:**

1. Setup vanilla 2.4-develop installation;
2. Take a look at the file `app/design/frontend/Magento/blank/Magento_Braintree/web/css/source/_module.less`, notice the selector `.payment-method-braintree` is in there and also notice this selector is in no other file in the Magento source code except for this file in the `Magento_Braintree` module in the
Magento/Blank theme;
3. Now disable that module (and its dependency): `bin/magento module:disable Magento_Braintree Magento_BraintreeGraphQl`
4. Remove potential left over files: `rm -R var/view_preprocessed/* pub/static/*`
5. Run static content deploy: `bin/magento setup:static-content:deploy -f --theme Magento/blank en_US`
6. Look at the generated file `pub/static/frontend/Magento/blank/en_US/css/styles-m.css`

Before: :heavy_multiplication_x: Finding references to the selector `.payment-method-braintree`

**After:** :heavy_check_mark: Not finding a reference to the selector `.payment-method-braintree`


### Case 2. Luma theme

**Manual testing scenario:**

1. Setup vanilla 2.4-develop installation;
2. Take a look at the file `app/design/frontend/Magento/luma/Magento_Multishipping/web/css/source/_module.less` , notice the selector `.multishipping-checkout-success` is in there and also notice this selector is in no other file in the Magento source code except for this file in the `Magento_Multishipping` module in the
Magento/Luma theme;
3. Now disable that module (and its dependency):` bin/magento module:disable Magento_Multishipping`
4. Remove potential left over files: `rm -R var/view_preprocessed/* pub/static/*`
5. Run static content deploy: `bin/magento setup:static-content:deploy -f --theme Magento/luma en_US`
6. Look at the generated file pub/static/frontend/Magento/luma/en_US/css/styles-m.css

Before: :heavy_multiplication_x: Finding references to the selector `.multishipping-checkout-success
`
**After:** :heavy_check_mark: Not finding a reference to the selector `.multishipping-checkout-success`

2020-04-24 13:36 UTC, engcom-Alfa commented
:heavy_check_mark: Also was compared the time of deploying

**Manual testing scenario:**

1. Disable some amount of modules (**10** modules in my case);
2. Run in console: `bin/magento setup:static-content:deploy -f`
3. Check execution time:

**Before:** :heavy_multiplication_x: 
![Screenshot from 2020-04-24 15-33-12](https://user-images.githubusercontent.com/51679138/80218054-567d2c80-8649-11ea-8275-6a66a97e757d.png)


After: :heavy_check_mark: 
![Screenshot from 2020-04-24 16-18-43](https://user-images.githubusercontent.com/51679138/80217364-3a2cc000-8648-11ea-960d-ca43ff127ee3.png)

_Before:_ 87.7c
_After:_ 75.37c

 :heavy_check_mark: Improving deploying performance is ~**16%**

2020-04-27 09:50 UTC, engcom-Echo commented
@magento run Integration Tests

2020-05-12 19:04 UTC, slavvka requested changes
@mrtuvn please resolve the conflicts and re-run the tests after the upgrade to PHP 7.4

2020-05-13 00:58 UTC, mrtuvn commented
@magento run all tests

2020-05-13 14:00 UTC, ihor-sviziev commented
Hi @slavvka ,
Could you give more info about failing unit and static tests? I can’t see any issues in reports

2020-05-14 13:52 UTC, mrtuvn commented
@magento run tests

2020-05-18 11:56 UTC, ihor-sviziev commented
@magento run all tests

2020-05-18 11:59 UTC, engcom-Echo commented
@magento tun all tests

2020-05-18 14:02 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2020-05-18 16:48 UTC, slavvka submitted a review, later dismissed

2020-05-18 16:49 UTC, ihor-sviziev submitted a review, later dismissed

2020-05-18 16:49 UTC, magento-engcom-team commented
Hi @slavvka, thank you for the review.
[ENGCOM-7466](https://jira.corp.magento.com/browse/ENGCOM-7466) has been created to process this Pull Request

2020-05-19 08:20 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

### Case 1. Blank theme

**Manual testing scenario:**

1. Setup vanilla 2.4-develop installation;
2. Take a look at the file `app/design/frontend/Magento/blank/Magento_Braintree/web/css/source/_module.less`, notice the selector `.payment-method-braintree` is in there and also notice this selector is in no other file in the Magento source code except for this file in the `Magento_Braintree` module in the
Magento/Blank theme;
3. Now disable that module (and its dependency): `bin/magento module:disable Magento_Braintree Magento_BraintreeGraphQl`
4. Remove potential left over files: `rm -R var/view_preprocessed/* pub/static/*`
5. Run static content deploy: `bin/magento setup:static-content:deploy -f --theme Magento/blank en_US`
6. Look at the generated file `pub/static/frontend/Magento/blank/en_US/css/styles-m.css`

Before: :heavy_multiplication_x: Finding references to the selector `.payment-method-braintree`

**After:** :heavy_check_mark: Not finding a reference to the selector `.payment-method-braintree`


### Case 2. Luma theme

**Manual testing scenario:**

1. Setup vanilla 2.4-develop installation;
2. Take a look at the file `app/design/frontend/Magento/luma/Magento_Multishipping/web/css/source/_module.less` , notice the selector `.multishipping-checkout-success` is in there and also notice this selector is in no other file in the Magento source code except for this file in the `Magento_Multishipping` module in the
Magento/Luma theme;
3. Now disable that module (and its dependency):` bin/magento module:disable Magento_Multishipping`
4. Remove potential left over files: `rm -R var/view_preprocessed/* pub/static/*`
5. Run static content deploy: `bin/magento setup:static-content:deploy -f --theme Magento/luma en_US`
6. Look at the generated file pub/static/frontend/Magento/luma/en_US/css/styles-m.css

Before: :heavy_multiplication_x: Finding references to the selector `.multishipping-checkout-success
`
**After:** :heavy_check_mark: Not finding a reference to the selector `.multishipping-checkout-success`

2020-05-19 12:47 UTC, engcom-Echo commented
Failed functional tests not related to the changes in this PR

2020-05-22 03:09 UTC, ihor-sviziev commented
Hi @VladimirZaets,
Could you explain why do we need to wait for approval?

2020-05-22 21:31 UTC, VladimirZaets commented
Hi @ihor-sviziev. I have a few minor points that I want to discuss with the team according to this PR.
1. The changes on the framework level
2. Should we deprecate old implementation if we don't use it now
3. And the main point, potentially it can break some extensions on the UI level

2020-05-25 23:13 UTC, mrtuvn commented
Hi guys can we have any updates on this ? @VladimirZaets what can i do now Do i need another tests ? such as integration , mftf

2020-05-26 18:28 UTC, ihor-sviziev commented
Hi @mrtuvn,
As I understood - this change require approval from architecture team, so no action items required from your side for now. Unfortunately approval might be not so fast as we would like to see it

2020-06-07 16:33 UTC, mrtuvn commented
@magento run all tests

2020-06-11 17:23 UTC, ihor-sviziev commented
@magento run all tests

2020-06-12 19:13 UTC, ihor-sviziev submitted a review, later dismissed

2020-06-12 19:14 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7466](https://jira.corp.magento.com/browse/ENGCOM-7466) has been created to process this Pull Request

2020-07-23 13:11 UTC, hostep commented
Hi guys

Anybody knows what the status of this is? Are we close to getting this approved and merged or were there regressions found?

2020-07-23 14:25 UTC, mrtuvn commented
@hostep we still need approve from core team as @VladimirZaets memtioned

2020-07-31 14:26 UTC, VladimirZaets commented
@magento run all tests

2020-08-18 18:10 UTC, mrtuvn commented
@magento run all tests

2020-08-19 16:55 UTC, mrtuvn commented on lib/internal/Magento/Framework/View/Asset/File.php
@ihor-sviziev just clean DocBlock in core framework. To me previously return seem incorrect type

2020-08-19 18:06 UTC, mrtuvn commented
@magento run all tests

2020-08-19 19:51 UTC, mrtuvn commented
@magento run all tests

2020-08-20 02:52 UTC, mrtuvn commented
@magento run Static Tests, Semantic Version Checker

2020-08-20 03:47 UTC, mrtuvn commented
@magento run Semantic Version Checker

2020-08-20 04:27 UTC, mrtuvn commented
@magento run all tests

2020-08-20 06:51 UTC, mrtuvn commented
just updated with newest codebase mainline nothing new changed

2020-08-20 07:58 UTC, ihor-sviziev commented
For reviewed - we need approval for this: https://github.com/magento/magento2/pull/27888#issuecomment-632916238

2020-08-20 08:31 UTC, hostep commented
We briefly tested this PR today on one of our shops in development, results:
- generated `styles-l.css` file is 24 KB smaller
- generated `styles-m.css` file is ~200 KB smaller

We have disabled:
- most core bundled extensions (amazon, dotmailer, klarna, vertex, yotpo)
- MSI modules
- Enterprise modules (because we are using the OS version, but enterprise css is still included in Magento's blank theme)
- 67 other non-essential Magento modules

We still need to test the shop to see if nothing broke, but at first sight it looks really good.

It's a very good improvement, so I'm hoping it will make it's way into the core one day 🙂

2020-08-20 08:44 UTC, mrtuvn commented
good feedback! Hope we can merge this

2020-08-20 18:53 UTC, ihor-sviziev commented
@VladimirZaets @sidolov can we speed up somehow approval process?

2020-09-01 14:54 UTC, mrtuvn commented
updated commit branch with code mainline

2020-09-01 14:57 UTC, ihor-sviziev approved these changes, later dismissed

2020-09-01 14:58 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7466](https://jira.corp.magento.com/browse/ENGCOM-7466) has been created to process this Pull Request

2020-09-01 15:13 UTC, ihor-sviziev commented
@magento run all tests

2020-09-05 04:55 UTC, mrtuvn commented
@magento run Integration Tests

2020-09-05 07:45 UTC, mrtuvn commented
@magento run Functional Tests B2B

2020-09-08 09:54 UTC, mrtuvn commented
@gabrieldagama  can you add risk scope on this for core team can discuss changes on this PR?
@lenaorobei @jameshalsall can you share your think about this changes can affect to core ?

2020-09-08 21:05 UTC, lenaorobei commented
Hi @mrtuvn! Thanks for this great improvement. I'm adding `2.5` milestone since this change may affect customers who are using styles from disabled modules. That's definitely not recommended way of doing things, but potentially can cause some issues.

I also added `High` risk evaluation since it is a framework change.

Anyway, thanks again! We look forward to delivering this improvement ASAP.

2020-09-20 04:21 UTC, ihor-sviziev commented
Hi @mrtuvn 
As approval process might take some time - I think you could rebase your changes when someone request it :)

2020-12-11 15:49 UTC, mrtuvn commented
[![lol](http://img.youtube.com/vi/w-Ng5muAAcg/0.jpg)](http://www.youtube.com/watch?v=w-Ng5muAAcg "")

Dunno why this PR don't have higher priority, Obviously it's issue still there. Milestone 2.5 seem too lates

2020-12-14 08:16 UTC, ihor-sviziev commented
@mrtuvn unfortunately some themes might depends on styles from disabled modules and doing such big change in patch release will be too much. That's why this PR will be targeted to 2.5

2021-01-06 23:17 UTC, mrtuvn commented
@magento run all tests

2021-01-07 01:19 UTC, mrtuvn commented
@magento run Database Compare, Functional Tests B2B, Unit Tests

2021-01-08 07:30 UTC, mrtuvn commented
@magento run Functional Tests B2B
Should i move this to 2.5-develop branch ?

2021-01-08 07:55 UTC, ihor-sviziev commented
@mrtuvn yes, please re-target your PR to 2.5-develop branch

2021-01-08 08:13 UTC, mrtuvn commented
Done! I have created new one here https://github.com/magento/magento2/pull/31593

2021-01-08 08:17 UTC, ihor-sviziev commented
@mrtuvn no, I meant that you could just change target branch for this PR, not creating a new one. But anyway, we can close this one if you wich

2021-01-08 08:19 UTC, mrtuvn commented
Oh i did know that ! Btw let close this

2021-01-08 08:19 UTC, closed without merging

2021-01-08 08:21 UTC, hostep commented
Hi @mrtuvn: could you add a link to this PR in your new PR? So people can find the entire discussion which happened here? Thanks! :)