Fixed Issue 12225: Tier pricing tax shows only including tax
magento/magento2 pull request #27953
Opened 2020-04-23 09:09 UTC by jiten-patel

### Description (*)

### Related Pull Requests

Steps to reproduce (*)
Go to Sales > Tax >Price display settings.
Configure to show the including and excluding tax price.
Go to a configurable product on the frontend with tier pricing.
You will see tier price including tax.
There is no way to change that to excluding price.

### Fixed Issues (if relevant)

1. #12225: Tier pricing tax shows only including tax

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-25 14:29 UTC, sidolov requested changes

2020-08-25 14:29 UTC, sidolov commented on app/code/Magento/Catalog/Pricing/Price/TierPrice.php
> +                    if ($this->scopeConfig->getValue('tax/display/type') == 3) {
Please, use const `\Magento\Tax\Model\Config::DISPLAY_TYPE_BOTH` instead of int, also use strict comparison here.

2020-08-25 14:29 UTC, sidolov commented on app/code/Magento/ConfigurableProduct/Block/Product/View/Type/Configurable.php
> +                    'excl_tax_price' => (is_object($tierPrice['excl_tax_price'])) ? $this->localeFormat->getNumber($tierPrice['excl_tax_price']->getValue()) : $tierPrice['base_price'],
I think it would be better to include `excl_tax_price` to result array only in case when it's not null.

2020-08-25 14:29 UTC, sidolov commented on app/code/Magento/ConfigurableProduct/view/base/templates/product/price/tier_price.phtml
> +                + '<span class="price"> excl. tax ' + priceUtils.formatPrice(item.excl_tax_price, currencyFormat) + '</span>
`excl. tax` should be translated

2020-08-27 05:53 UTC, engcom-Charlie commented
Hi @jiten-patel, can you please look at requested changes
https://github.com/magento/magento2/pull/27953#discussion_r476490511
https://github.com/magento/magento2/pull/27953#discussion_r476493498
https://github.com/magento/magento2/pull/27953#discussion_r476493911
and also check failed tests?

2020-09-09 11:03 UTC, engcom-Charlie commented
Hi @jiten-patel can you please take a look at failed tests?
Looks like after your changes product's options isn't available on configurable PDP.
Thank you.

2020-09-10 10:13 UTC, engcom-Charlie commented
@jiten-patel I'll try to continue with your PR.

2020-09-10 11:02 UTC, engcom-Charlie commented
@magento run all tests

2020-09-14 10:58 UTC, gabrieldagama commented
@engcom-Charlie can you update this branch with the latest mainline and solve conflicts?

2020-09-14 13:44 UTC, engcom-Charlie commented
@magento run all tests

2020-09-14 15:14 UTC, sidolov submitted a review, later dismissed

2020-09-14 15:18 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8202](https://jira.corp.magento.com/browse/ENGCOM-8202) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-15 10:21 UTC, engcom-Alfa requested changes
Hi @jiten-patel .

Could you resolve merge conflicts?
Thanks!

2020-09-16 08:33 UTC, engcom-Charlie commented
@magento run all tests

2020-09-16 09:20 UTC, engcom-Charlie commented
@magento run all tests

2020-09-17 10:06 UTC, gabrieldagama commented
@magento run Functional Tests CE

2020-09-17 10:07 UTC, gabrieldagama approved these changes, later dismissed

2020-09-17 10:08 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8202](https://jira.corp.magento.com/browse/ENGCOM-8202) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-18 07:15 UTC, engcom-Alfa requested changes
Hi @jiten-patel .

During testing, we faced the issue.

The location of the price level elements should be in one line each, as displays on a simple product before the PR changes.

:heavy_check_mark: **Without fix ( Simple Product ) :**

![2020-09-18_10-04](https://user-images.githubusercontent.com/51679138/93567390-3e5ece80-f997-11ea-9255-875eb203c4c3.png)

**With fix:**

 :heavy_multiplication_x: **_Simple Product_**

![2020-09-18_10-00](https://user-images.githubusercontent.com/51679138/93567516-6cdca980-f997-11ea-8834-35ecb4573adc.png)

 :heavy_multiplication_x: **_Configurable Product_**

![2020-09-18_10-01](https://user-images.githubusercontent.com/51679138/93567590-8c73d200-f997-11ea-90d5-51723f1bc886.png)

@jiten-patel Could you change the position of the elements as done on the mainline for Simple Product type?

Thanks!

2020-09-18 12:47 UTC, engcom-Charlie commented
@magento run all tests

2020-09-22 11:00 UTC, gabrieldagama approved these changes

2020-09-22 11:02 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8202](https://jira.corp.magento.com/browse/ENGCOM-8202) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-23 06:23 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

Configurable product with tier pricing

**Manual testing scenario:**

1. Go to Admin -> Sales -> Tax -> Price display settings;
2. Configure to show the including and excluding tax price;
3. Go to a configurable product on the frontend with tier pricing.

**Before:** :heavy_multiplication_x: The tier price only shows the including tax

![2020-09-23_09-20](https://user-images.githubusercontent.com/51679138/93974116-06340300-fd7e-11ea-930d-c53eab2630d0.png)

**After:** :heavy_check_mark: The tier price  shows the excluding  including tax

_Configurable product:_

![2020-09-22_15-13](https://user-images.githubusercontent.com/51679138/93974252-3c718280-fd7e-11ea-9311-870171ad544a.png)

_Simple product:_

![2020-09-22_15-00](https://user-images.githubusercontent.com/51679138/93974283-472c1780-fd7e-11ea-931b-39269e7c9ddb.png)

Also, was tested - including tax, excluding tax on different types of product and everything work as expected.

2020-09-23 07:32 UTC, engcom-Charlie commented
@magento run all tests

2020-09-24 00:58 UTC, merged