Feature bulgarian country regions
magento/magento2 pull request #27957
Opened 2020-04-23 16:51 UTC by nikolalardev

### Description (*)
Adding Bulgarian regions to **directory_country_region** table

### Related Pull Requests

### Manual testing scenarios (*)

1. Install Magento
2. Check table directory_country_region for Bulgarian states.

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-24 07:03 UTC, rogyar requested changes
Hi @nikolalardev. Thank you for your collaboration. Please, check my comments below for some minor adjustments. 

Also, according to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. You may refer to the following PR that shows how to create an MFTF test for a similar case.

https://github.com/magento/magento2/pull/25590

Thank you.

2020-04-24 07:03 UTC, rogyar commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBulgaria.php
> +class AddDataForBulgaria implements DataPatchInterface, PatchVersionInterface
Please, remove the `PatchVersionInterface` dependency. We may omit it in this particular case and remove the redundant `getVersion()` as result.

2020-05-05 13:01 UTC, engcom-Echo commented
I will take care of test coverage.

2020-05-07 14:16 UTC, kalinicham commented
Hi @rogyar could you please approve it?

2020-05-07 14:18 UTC, engcom-Echo commented
Hi @rogyar could you please approve it?

2020-05-11 07:22 UTC, rogyar approved these changes

2020-05-11 07:23 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-7536](https://jira.corp.magento.com/browse/ENGCOM-7536) has been created to process this Pull Request

2020-05-11 07:23 UTC, magento-engcom-team commented
@nikolalardev thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-05-13 07:40 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Go to Admin->Stores->Configuration->General->Store Information

**Actual Result:**
![Screenshot from 2020-05-13 10-31-56](https://user-images.githubusercontent.com/51679138/81784608-ca527c80-9505-11ea-8504-ca13e0a84a49.png)

Go to Checkout process->Shipping

**Actual Result:**
![Screenshot from 2020-05-13 10-35-56](https://user-images.githubusercontent.com/51679138/81784816-19001680-9506-11ea-83ff-c3873ad22110.png)

2020-05-13 17:12 UTC, slavvka commented
@magento create issue

2020-05-21 00:09 UTC, merged