24442 Since Magento 2.3 the wysiwyg images are not loaded anymore fro…
magento/magento2 pull request #27967
Opened 2020-04-24 10:14 UTC by novakivskiy

fix issue https://github.com/magento/magento2/issues/24442, https://github.com/magento/magento2/issues/3135

2020-08-24 21:15 UTC, sidolov requested changes

2020-08-24 21:15 UTC, sidolov commented on app/code/Magento/MediaStorage/App/Media.php
> +    public function isNeedImageResize(string $originalImageName)
Should be private

2020-08-24 21:15 UTC, sidolov commented on app/code/Magento/MediaStorage/App/Media.php
> +    public function isNeedImageResize(string $originalImageName)
Please, add strict return type

2020-08-24 21:15 UTC, sidolov commented on app/code/Magento/MediaStorage/App/Media.php
> +        return preg_replace('|^catalog\/product\/cache\/[\w\d.]+(.*)$|', '$1', $resizedImagePath);
Not sure that's a good idea to hardcode path in the regexp

2020-08-24 21:15 UTC, sidolov commented on app/code/Magento/MediaStorage/Service/ImageResize.php
> +    public function copyFileFromDbStorage(string $originalImageName)
Should be private. 
Please, add return type

2020-08-24 21:15 UTC, sidolov commented on pub/get.php
> +        if (0 === stripos($resource, 'media/' . $allowedResource)) {
Implementation will be broken if the resource will be configured out of `media` folder.

2020-08-31 10:51 UTC, engcom-Charlie commented
Hi @novakivskiy, please sign CLA and look through failed tests and requested changes. Otherwise, we can't proceed with your PR.

2020-09-09 19:22 UTC, sidolov commented
@novakivskiy  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-09 19:22 UTC, closed without merging