ISSUE-27954: Forgot password save user only one column
magento/magento2 pull request #27972
Opened 2020-04-24 13:33 UTC by sheepfy

Fixed issue https://github.com/magento/magento2/issues/27954

2020-08-29 12:45 UTC, aleron75 commented
Hello @sheepfy thanks for your contribution, it's very appreciated.

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing_dod.html), all code must be covered by tests. 

For this specific case, this fix should be covered by automated tests with the scenario which leads to an issue. 
Tests should fail on the mainline and pass with this fix.

To answer the question "which kind of tests should we write", I would go with a lightweight unit test.

2020-09-21 07:17 UTC, ihor-sviziev requested changes
Hi @sheepfy,
Could you update your solution as it was requested here? https://github.com/magento/magento2/pull/27972#issuecomment-683285733

2020-09-21 08:03 UTC, sheepfy commented
> Hi @sheepfy,
> Could you update your solution as it was requested here? [#27972 (comment)](https://github.com/magento/magento2/pull/27972#issuecomment-683285733)


Hi, so, to be clear for me, you want me to implement unit tests for "ProductResource:: updateColumn" function ? 
If that so, i can do it untill the end of this week

2020-09-21 08:30 UTC, ihor-sviziev commented
@sheepfy I think yes + fix failing unit tests should be enough.

2020-09-24 09:56 UTC, engcom-Charlie commented
Hi, @sheepfy could you please fix static and unit tests?
Thank you.

2020-09-24 21:57 UTC, sheepfy commented
Hi, i’ll do my best do finish the test untill the end of the week, if not , i’ll let you know

> On 24 Sep 2020, at 12:56, Vadim Malesh <notifications@github.com> wrote:
> 
> ﻿
> Hi, @sheepfy could you please fix static and unit tests?
> Thank you.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-09 09:22 UTC, engcom-Charlie commented
Hi, @sheepfy do you have any updates?
Thank you.

2020-10-12 11:26 UTC, engcom-Charlie commented
Hi, @sheepfy please fix static and unit tests. Otherwise, we can't proceed with your PR.
Thank you.

2020-10-19 11:26 UTC, engcom-Charlie commented
Hi, @sheepfy I'll continue with your PR.

2020-10-21 09:03 UTC, engcom-Charlie commented
@magento run all tests

2020-10-21 11:55 UTC, ihor-sviziev requested changes
Hi @sheepfy @engcom-Charlie,
I just reviewed this PR again and see that class where updateColumn method was adde - it is marked as `@api`, so adding there new methods is not allowed and that's why SVC check currently fails.

Also the customer model stored in EAV, so it will be more logical to make "updateAttribute" method that will save the only needed attribute, it doesn't matter if it stored in the main table `customer_entity` or in some of EAV tables.

I do understand that it will be huge refactoring , so instead of going to this direction - I could suggest two options:
1. move the `updateColumn` method to separate model `ClearAccountConfirmation`, similar to `ConfirmCustomerByToken`. It would just update confirmation field to null using resource model. The only one concern I have here - earlier `$customer->setConfirmation(null)` was executed and it basically changed the object, while now it's not changed.

2. In the account management model I see quite similar case:
https://github.com/magento/magento2/blob/68770fcefd93b8f2806fd60356efc318f91d2598/app/code/Magento/Customer/Model/AccountManagement.php#L579-L582

https://github.com/magento/magento2/blob/68770fcefd93b8f2806fd60356efc318f91d2598/app/code/Magento/Customer/Model/AccountManagement.php#L1617-L1626
Seems like this flag allow to skip the address validation process, and basically it will fix original issue.

What to you thing about those two suggestions? I'm ok with implementing both of them

2020-10-21 11:55 UTC, ihor-sviziev commented on app/code/Magento/Customer/Model/ResourceModel/Customer.php
> +    public function updateColumn($customerId, $column, $value)
```suggestion
    public function updateColumn(int $customerId, string $column, string $value)
```

2020-10-21 11:55 UTC, ihor-sviziev commented on app/code/Magento/Customer/Model/ResourceModel/Customer.php
> +     */
```suggestion
    /**
     * Update one column in customer_entity table
     *
     * @param int $customerId
     * @param string $column
     * @param string $value
     * @return $this
     */
```

2020-10-21 12:21 UTC, engcom-Charlie commented
@ihor-sviziev totally agree with you.
As for me, the second suggestion about the flag would be better.
@sheepfy what do you think?

2020-10-23 08:47 UTC, engcom-Charlie commented
@sheepfy I'll continue with your PR.

2020-10-23 09:11 UTC, engcom-Charlie commented
@magento run all tests

2020-10-23 09:23 UTC, ihor-sviziev commented
@engcom-Charlie thank you! now looks much better!

2020-10-26 10:19 UTC, ihor-sviziev approved these changes

2020-10-26 10:26 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8388](https://jira.corp.magento.com/browse/ENGCOM-8388) has been created to process this Pull Request

2020-10-26 10:26 UTC, magento-engcom-team commented
@sheepfy thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-10-26 10:33 UTC, sheepfy commented
Hello, thanks for inviting me into the Community Contributors team.
And sorry for the late reply and not continuing with the PR. Since first
time a created and till now, things changed and i didn't have time to go on.



On Mon, 26 Oct 2020 at 12:26, Magento Community Engineering <
notifications@github.com> wrote:

> @sheepfy <https://github.com/sheepfy> thank you for contributing. Please
> accept Community Contributors team invitation here
> <https://github.com/orgs/magento/invitation> to gain extended permissions
> for this repository.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/27972#issuecomment-716455196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEFIULNANL2CH7J66DLJBM3SMVFFXANCNFSM4MQDKD6Q>
> .
>

2020-10-29 11:57 UTC, engcom-Bravo commented
This PR fixes an issue for Magento Enterprise Edition 

:heavy_check_mark: QA Passed

### Manual testing scenario:
1. Go to Store->Configuration->Customer->Customer Configuration
2. Enable 'Require Emails Confirmation'
3. On Admin go to Customers->All customers and Add New Customer with address
4. Add some kind of validation to address fields in the Database (limit length for city name)
`UPDATE customer_eav_attribute SET validate_rules='{"input_validation":1,"min_text_length":0,"max_text_length":2}'
WHERE attribute_id=(SELECT attribute_id FROM eav_attribute WHERE entity_type_id=2 AND attribute_code='city');`
5. Go to frontend
6. Click Sign In
7. Click Forgot Your Password?
8. Fill fields and click Reset My Password
9. Open the email and click Set a New Password

**Before** applying changes provided in this PR, the Customer has been redirected to _Forgot Your Password_
![Before PR](https://user-images.githubusercontent.com/51680745/97565147-6574db00-19ee-11eb-94d4-1dbb6c91e916.png)

**After** switching to the PR, the Customer is redirected to _Set a New Password_
![After PR](https://user-images.githubusercontent.com/51680745/97565307-aec52a80-19ee-11eb-92db-0de6f0a71821.png)

2020-11-09 14:22 UTC, merged