Checkout: Placing an order using the enter key causes a redirect to t…
magento/magento2 pull request #27986
Opened 2020-04-25 12:05 UTC by dhairya-shah

Tis pull request is for solve issue number 27925

### Description (*)
Checkout page reload when press enter key on "Purchase Order Numer" field in purchase Order payment method.

### Fixed Issues (if relevant)
[#27925](https://github.com/magento/magento2/issues/27925) : Checkout: Placing an order using the enter key causes a redirect to the checkout

### Manual testing scenarios (*)

1. Add a product to the cart and proceed to the checkout
2. Enter your shipping details and proceed to "Review & Payments"
3. Select "Purchase Order" as your payment of choice
4. Enter a random "Purchase Order Number"
5. Press enter while the focus is still on the "Purchase Order Numer" field.
6. Now the order should be placed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-27 19:19 UTC, sdzhepa commented
Hello @dhairya-shah 

During internal review and triage, the Expected result was changed.  https://github.com/magento/magento2/issues/27925#issuecomment-620179453
In general, order should not place in this case - such action could be not obvious for the customer.

**Expected Result**
- The order should NOT be placed and after push "Enter" button
- The page should not be reloading

2020-04-29 13:41 UTC, rogyar commented
Hi @dhairya-shah. After implementing adjustments mentioned by @sdzhepa. I would kindly ask you to do the following: 

- Sign Adobe CLA. It's a required procedure for further PR processing. 
- Cover your changes using an MFTF test. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html), all changes should be covered by autotests. 

Thank you!

2020-04-30 15:10 UTC, sdzhepa commented
@dhairya-shah 

After additional discussion based on https://github.com/magento/magento2/issues/27925#issuecomment-620425099

The Issue has been re-triaged and was decided to return the previous Expected Result. More details https://github.com/magento/magento2/issues/27925#issuecomment-621895783

I will update the expected result.

Sorry for any inconveniences

2020-05-04 19:41 UTC, VladimirZaets requested changes
Hi @dhairya-shah , thanks for collaboration. Please take a look at review comments below

2020-05-04 19:41 UTC, VladimirZaets commented on app/code/Magento/OfflinePayments/view/frontend/web/js/view/payment/method-renderer/purchaseorder-method.js
> +            var self = this;
Please use bind/call instead of declare `self` variables.

2020-05-04 19:41 UTC, VladimirZaets commented on app/code/Magento/OfflinePayments/view/frontend/web/js/view/payment/method-renderer/purchaseorder-method.js
> +            if (keyCode == '13'){
Please use the mapper to get event code `magento2ce/app/code/Magento/Ui/view/base/web/js/lib/key-codes.js`

2020-05-04 19:41 UTC, VladimirZaets commented on app/code/Magento/OfflinePayments/view/frontend/web/template/payment/purchaseorder-form.html
> +        <form id="purchaseorder-form" class="form form-purchase-order" data-role="purchaseorder-form" onSubmit="return false;">
Do we really need  `onSubmit="return false;`?

2020-05-27 10:54 UTC, engcom-Charlie commented
Hi @dhairya-shah, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-05-27 10:54 UTC, closed without merging