1245/delete asset file from storage
magento/magento2 pull request #27994
Opened 2020-04-26 12:02 UTC by coderimus

### Description (*)
While working on one of the ASI issues I found one bug and the way we can improve some part of the MediaGallery.

This PR provides:

1. Bugfix for the `\Magento\MediaGallery\Model\ResourceModel\DeleteAssetsByPaths::execute`. Images, located at the `/` folder of the media stored in the data storage with a `/` while during deleted those kinds of images the execute method gets a path without it so images can not be deleted.

For example, we download an image to the root media gallery folder and its path will be  `/download.jpg`. If we want to delete it the `$path` parameter of the `\Magento\MediaGallery\Model\ResourceModel\DeleteAssetsByPaths::execute` will be `download.jpg` and asset will not be deleted.

2. Refactoring to the MediaGallery plugin responsible for image or folder delete functionality. I removed deprecated classes and start to use recommended. Adjust Unit tests for the current MediaGallery functionality. They were good but I have to combine them and add changes required to the current implementation.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-26 19:20 UTC, sivaschenko approved these changes

2020-04-26 19:21 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7489](https://jira.corp.magento.com/browse/ENGCOM-7489) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-04-27 09:00 UTC, sivaschenko commented
@coderimus can you please add the testing scenario for QA to be able to check the changes

2020-04-27 09:13 UTC, coderimus commented
@sivaschenko QA steps added. Please, validate.

2020-04-27 12:25 UTC, engcom-Bravo requested changes
:x: QA Failed

The Deleted image reappears in Megia Gallery

2020-04-27 12:43 UTC, sivaschenko commented
The issue with deleted image reappearing should be addressed by https://github.com/magento/adobe-stock-integration/pull/1279

2020-04-27 15:17 UTC, coderimus commented
@sivaschenko I provide changes for getting a related path for images uploaded to the root of the media directory. Please, review.

2020-04-27 15:20 UTC, sivaschenko approved these changes

2020-04-27 15:21 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7489](https://jira.corp.magento.com/browse/ENGCOM-7489) has been created to process this Pull Request

2020-04-27 15:26 UTC, sivaschenko commented on app/code/Magento/MediaGallery/Plugin/Wysiwyg/Images/Storage.php
> +            $this->deleteMediaAssetByPath->execute([$this->getMediaDirectoryRelativePath($path)]);
```suggestion
            $this->deleteMediaAssetByPath->execute([$this->filesystem->getDirectoryRead(DirectoryList::MEDIA)->getRelativePath($path)]);
```

2020-04-27 15:28 UTC, sivaschenko requested changes
Thanks for updates @coderimus ! I don't think the path corrections should be applied when the directory is deleted. Can you please take a look at my correction suggestion and check this case

2020-04-27 15:35 UTC, coderimus commented
@sivaschenko requested changes added. Please, review.

2020-04-27 15:46 UTC, sivaschenko approved these changes

2020-04-27 15:47 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7489](https://jira.corp.magento.com/browse/ENGCOM-7489) has been created to process this Pull Request

2020-04-28 06:42 UTC, engcom-Golf commented
:heavy_check_mark: QA Passed  images deleted from physical storage, folder deleted from physical storage and from the media_gallery_asset
**Note** Tested with linked PR on AdobeStock repository https://github.com/magento/adobe-stock-integration/pull/1279

2020-04-28 13:53 UTC, sivaschenko submitted a review, later dismissed

2020-04-28 13:55 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7489](https://jira.corp.magento.com/browse/ENGCOM-7489) has been created to process this Pull Request

2020-04-28 13:58 UTC, sivaschenko approved these changes

2020-04-29 00:56 UTC, merged