fixed negative  children_count after deleting categories
magento/magento2 pull request #28044
Opened 2020-04-29 15:59 UTC by ProkopovVitaliy

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27969: children_count can become negative after deleting categories

### Manual testing scenarios (*)

1.Log in into admin backend
2.Navigate to Catalog -> Categories
3.Click "Add Subcategory"
4.Fill category name with "Parent 1", Save
5.Click "Add Subcategory"
6.Fill category name with "Child 1", Save
7.Click "Add Subcategory"
8.Fill category name with "Child 2", Save
9.Click "Add Subcategory"
10.Fill category name with "Child 3", Save. At this point this category should have level = 5
11.Click on "Child 1" category
12.Delete category

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-04-30 10:52 UTC, engcom-Echo commented
I will take care of test coverage.

2020-05-04 18:33 UTC, VladimirZaets approved these changes

2020-05-04 18:34 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7513](https://jira.corp.magento.com/browse/ENGCOM-7513) has been created to process this Pull Request

2020-05-05 11:33 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1.Log in into admin backend
2.Navigate to Catalog -> Categories
3.Click "Add Subcategory"
4.Fill category name with "Parent 1", Save
5.Click "Add Subcategory"
6.Fill category name with "Child 1", Save
7.Click "Add Subcategory"
8.Fill category name with "Child 2", Save
9.Click "Add Subcategory"
10.Fill category name with "Child 3", Save. At this point this category should have level = 5
11.Click on "Child 1" category
12.Delete category
13. See `catalog_category_entity` table

**Before:**  :heavy_multiplication_x: `children_count` for remaining categories have negative meanings
![screenshotqwerty](https://user-images.githubusercontent.com/51679138/81061429-028e0580-8edd-11ea-8f43-b7497cf6c461.png)

**After:** :heavy_check_mark: children_count for remaining categories are valid 
![screenshotqwerty2](https://user-images.githubusercontent.com/51679138/81061571-408b2980-8edd-11ea-9a95-50843e1a2e98.png)

Also tested with few roots categories and Childs.

2020-05-26 11:47 UTC, ProkopovVitaliy commented
@magento run all tests

2020-05-28 08:08 UTC, ProkopovVitaliy commented
@magento run all tests

2020-06-01 08:26 UTC, ProkopovVitaliy commented
@VladimirZaets I think failing tests are not related to the changes presented in the current PR 🤔.

2020-06-01 15:33 UTC, VladimirZaets commented
@ProkopovVitaliy I reran tests to be sure, thanks

2020-06-10 04:35 UTC, ProkopovVitaliy commented
@magento run all tests

2020-06-11 11:56 UTC, engcom-Echo commented
@magento run all tests

2020-06-12 04:33 UTC, ProkopovVitaliy commented
@magento run Unit Tests

2020-06-12 04:33 UTC, ProkopovVitaliy commented
@magento run Static Tests

2020-06-12 05:33 UTC, ProkopovVitaliy commented
@magento run Unit Tests

2020-06-21 07:46 UTC, ProkopovVitaliy commented
@magento run Static Tests

2020-06-21 07:47 UTC, ProkopovVitaliy commented
@magento run Unit Tests

2020-06-22 05:38 UTC, dmytro-ch requested changes

2020-06-22 05:38 UTC, dmytro-ch commented on app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Category/AggregateCountTest.php
> +    public function setUp()
Hello @ProkopovVitaliy,
could you please add a return type definition here for compatibility with PHPUnit 8?
```suggestion
    public function setUp(): void
```

2020-06-22 06:10 UTC, ProkopovVitaliy commented
@magento run all tests

2020-06-22 08:14 UTC, dmytro-ch approved these changes

2020-06-22 08:17 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7513](https://jira.corp.magento.com/browse/ENGCOM-7513) has been created to process this Pull Request

2020-06-22 14:11 UTC, engcom-Delta commented
**Notice:** QA not applicable
New commits are connected to tests

2020-06-24 03:04 UTC, merged