Fix issue button used action-primary class changed color if click
magento/magento2 pull request #28083
Opened 2020-05-02 21:55 UTC by mrtuvn

### Description (*)

Continue works by @neerajchand after long inactivity in PR 27560

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#27095: In Floating cart delete pop-up, When user click on out side of OK button than button color is changed

### Manual testing scenarios (*)

1. Magento 2.3.4+
2. Theme luma
3. Add any products to cart
4. Remove product added
5. Click outside of modal confirm remove

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-04 03:59 UTC, edenduong commented
@magento give me test instance

2020-05-04 03:59 UTC, magento-engcom-team commented
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

2020-05-04 04:00 UTC, magento-engcom-team commented
Hi @edenduong, here is your [new Magento instance](https://pr-28083.instances.magento-community.engineering).
Admin access: [https://pr-28083.instances.magento-community.engineering/admin_3c9c](https://pr-28083.instances.magento-community.engineering/admin_3c9c)
Login: `77939bf5` Password: `cf97839cf64e`
Instance will be terminated in up to 3 hours.

2020-05-04 04:06 UTC, edenduong commented
Hi @mrtuvn :

Could you please solve this issue? I see it has small white color at the OK button when click outside

![image](https://user-images.githubusercontent.com/8234209/80935531-38f15500-8df7-11ea-8d4a-73233ce4312a.png)

2020-05-04 04:07 UTC, edenduong requested changes
Hi @mrtuvn :

Could you please solve this issue? I see it has small white color at the OK button when click outside

![image](https://user-images.githubusercontent.com/8234209/80935531-38f15500-8df7-11ea-8d4a-73233ce4312a.png)

2020-05-04 05:04 UTC, mrtuvn commented
> Hi @mrtuvn :
> 
> Could you please solve this issue? I see it has small white color at the OK button when click outside
> 
> ![image](https://user-images.githubusercontent.com/8234209/80935531-38f15500-8df7-11ea-8d4a-73233ce4312a.png)

i think this is default of magento ! Do you meaning the white small bar in the top and bottom of button Ok ? It's is box-shadow applied to button

2020-05-04 06:31 UTC, edenduong commented
Hi @mrtuvn :

Please see:
Before:
![image](https://user-images.githubusercontent.com/8234209/80940986-71029300-8e0b-11ea-9166-ff29497c1460.png)

After click out side:

![image](https://user-images.githubusercontent.com/8234209/80941017-8677bd00-8e0b-11ea-8dfd-8f5eaed1e432.png)

2020-05-04 07:27 UTC, mrtuvn commented on app/design/frontend/Magento/luma/web/css/source/_buttons.less
>              &:active {
@edenduong this line apply box shadow for every button doesn't have class primary. In luma theme you can see every button will have white space on top
After this change can affect to all button. I'm not sure about reason of this rule here

2020-05-04 08:19 UTC, edenduong commented
@magento give me test instance

2020-05-04 08:20 UTC, magento-engcom-team commented
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

2020-05-04 08:23 UTC, magento-engcom-team commented
Hi @edenduong, here is your [new Magento instance](https://pr-28083.instances.magento-community.engineering).
Admin access: [https://pr-28083.instances.magento-community.engineering/admin_c201](https://pr-28083.instances.magento-community.engineering/admin_c201)
Login: `5002a46e` Password: `4de8913c24ea`
Instance will be terminated in up to 3 hours.

2020-05-04 13:56 UTC, edenduong approved these changes
Thank you for your contribution !

2020-05-04 13:57 UTC, magento-engcom-team commented
Hi @edenduong, thank you for the review.
[ENGCOM-7510](https://jira.corp.magento.com/browse/ENGCOM-7510) has been created to process this Pull Request

2020-05-05 09:03 UTC, ptylek approved these changes

2020-05-05 09:04 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-7510](https://jira.corp.magento.com/browse/ENGCOM-7510) has been created to process this Pull Request

2020-05-06 12:52 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Magento 2.4-develop (**Luma** theme)

**Manual testing scenario:**

1. Add any products to the cart;
2. Click on remove button in mini-cart;
3. Click outside of modal confirm remove;

**Before:** :heavy_multiplication_x: 

![Peek 2020-05-06 14-36](https://user-images.githubusercontent.com/51679138/81178726-566a1e80-8fb1-11ea-92b7-c9b45c047602.gif)

**After:** :heavy_check_mark: 

![Peek 2020-05-06 14-45](https://user-images.githubusercontent.com/51679138/81178779-6a158500-8fb1-11ea-9b58-a1607f5ef7bf.gif)

The same results and with the **Blank** theme

2020-05-07 08:46 UTC, engcom-Charlie commented
The failing functional tests are not related to the change in this pr.

2020-05-21 15:12 UTC, merged