Implement missing sortOrder for Plugins in PageCache module
magento/magento2 pull request #28127
Opened 2020-05-06 19:32 UTC by lbajsarowicz

### Description (*)
During work with #27270 I noticed that there is no way to inject plugin optimizing the Layout output, by default when there is no `sortOrder` - it's assumed to be `0`, so you need to use negative value for your plugin (eg. `-10`)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-06 23:17 UTC, slavvka commented
@magento run all tests

2020-05-07 15:41 UTC, ihor-sviziev commented
Looks like something was wrong during running the tests, just restarted

2020-05-07 15:43 UTC, ihor-sviziev commented
Hi @lbajsarowicz,
I think would be better to add these changes to https://github.com/magento/magento2/pull/27270 and remove negative sort order there. What  do you think?

2020-05-07 15:50 UTC, lbajsarowicz commented
@ihor-sviziev I'm afraid this is going to freeze the original PR either way.

2020-05-08 07:19 UTC, ihor-sviziev commented
Wow. more than 160 failed mftf tests. Looks like false positive. But to be sure let's re-run tests again 
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2020-05-08 10:59 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,
Please review failing functional tests. Looks like your change introduced quite big amount of test failures.

2020-05-08 12:19 UTC, lbajsarowicz commented
OK, let's give up with that for a moment, that is by-design the issue of Magento that has to be addressed across the platform.

2020-05-08 12:19 UTC, closed without merging