Fixed the problem with products create/update via REST API requests when request body data is sent as "xml"
magento/magento2 pull request #28140
Opened 2020-05-07 18:05 UTC by Neos2007

Fixed the problem with products create/update via REST API requests when request body data is sent as "xml"

### Description (*)
After updating Magento to v. 2.3.5 there is no more possibility to send REST API requests for creating/updating products with "xml" request body. Every request leads to a response with an error: "Decoding error: Unable to unserialize value. Error:..."
The problem appeared after adding the class "Magento\Catalog\Model\Product\Webapi\ProductOutputProcessor" which additionally processes product data during preparing API response.
This class uses deserializer class ("Magento\Framework\Webapi\Rest\Request\DeserializerInterface"  inherited class instance) for the processing (converting) request body (interface injected in the constructor).
Different deserializer class configured (via di.xml) for REST and SOAP scopes: "Magento\Framework\Webapi\Rest\Request\Deserializer\Json" (for REST) and  Magento\Framework\Webapi\Rest\Request\Deserializer\XML (for SOAP).
https://github.com/magento/magento2/commit/f58ddb5b2996d4069a0c79bf693d7f92bbb2e5e5#diff-8f3c9c53a4d283c4a677a3bfd544a363R40
Such configuration leads to parsing errors in product REST API requests when product request data sent as XML because   ProductOutputProcessor will always use Json deserializer for converting request body data without checking origin request content-type (which could be XML). 
For fixing this I have implemented custom deserializer class for products rest requests:
*Magento\Catalog\Model\Product\Webapi\Rest\RequestTypeBasedDeserializer*
This class first checks content-type for request body and then, using deserializer factory, get needed deserializer instance and use it for converting request body data.

-->

### Manual testing scenarios (*)
**Test on Magento version 2.3.5 or using 2.4-develop branch**
1. Sent product create/update request with XML request body and "Content-Type: application/xml" header. 
**Example:** 
```
curl --location --request POST 'https://magento-site/rest/all/V1/products' \
--header 'Authorization: Bearer someencodedtoken' \
--header 'Content-Type: application/xml' \
--data-raw '<?xml version='\''1.0'\'' encoding='\''UTF-8'\''?>
<products>
    <product>
        <sku>TRAKTOR_KONTROL_BAG_1</sku>
        <name>TRAKTOR_KONTROL_BAG_1</name>
        <weight>22</weight>
        <attribute_set_id>4</attribute_set_id>
        <status>2</status>
      </product>
</products>
```
2. Got an error in response with the text: "Decoding error: Unable to unserialize value. Error:..." 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-08 06:28 UTC, ihor-sviziev commented
@magento create issue

2020-05-08 06:34 UTC, ihor-sviziev commented
Hi @Neos2007,
Could you report the issue with all exact steps to reproduce? Does this issue appears only on catalog, or somewhere else?

2020-05-08 07:24 UTC, Neos2007 commented
@ihor-sviziev the problem related and reproducible only for the product create/update requests because of logic "Magento\Catalog\Model\Product\Webapi\ProductOutputProcessor" (as I mentioned in the ticket description) class which was added in Magento v. 2.3.5.

2020-05-08 08:31 UTC, ihor-sviziev requested changes
Hi @Neos2007,
I just reviewed your changes - and commit https://github.com/magento/magento2/commit/f58ddb5b2996d4069a0c79bf693d7f92bbb2e5e5#diff-d0dca5b5a6dc36b5f088d8d9c9630db6R56 where this class was introduced.

Could you explain, why do you think it's good idea to create new class RequestTypeBasedDeserializer that will be available only in Catalog rather than updating `ProductOutputProcessor` class to use `DeserializerFactory` to retrieve correct object and then execute `deserialize` method on it? Seems like issue just inside only one class, I don't think we actually have any benefit from introducing new class.

Could you also sign Adobe CLA, otherwise we can't accept your PR 😢

2020-05-08 08:56 UTC, Neos2007 commented
@ihor-sviziev I moved this logic in separate deserializer class because determining needed deserializer (XML, JSON) must be done only for rest requests. But "ProductOutputProcessor" class used also in SOAP requests and it requires to be injected XML parser.

And also I have some problems with sign Adobe CLA. I Signed it. But status was not changed (I tried to close and reopen PR after I signed).

2020-05-08 08:59 UTC, ihor-sviziev commented
@Neos2007 could you write me in Slack? It will be easier to figure out why it fails

2020-05-08 10:04 UTC, ihor-sviziev submitted a review, later dismissed
Looks good! Approved ✔

Would be good to cover such case with API Functional test, but as we discussed with @Neos2007 - they're not supporting XML in REST api 😢
https://github.com/magento/magento2/blob/d551d1e3f70f8ae09c4de6958125f22b855d5569/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php#L79

2020-05-08 10:05 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7530](https://jira.corp.magento.com/browse/ENGCOM-7530) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-05-08 10:13 UTC, nuzil reviewed
I love it! 
Thanks @ihor-sviziev for fast processing. Quite critical issue currently.

2020-05-08 10:17 UTC, ihor-sviziev commented
@magento create issue

2020-05-08 10:23 UTC, ihor-sviziev commented
I've reported an issue to provide an ability to run XML in API Functional tests
https://github.com/magento/magento2/issues/28156

2020-05-08 18:47 UTC, slavvka commented
@Neos2007 @ihor-sviziev @nuzil PO decided to deliver it to `2.4.0` if it is completed (with testing) within a week. Please note that I changed a base to `2.4.0-develop` so it should be retested. Also keep in mind that today or tomorrow there will be merged support for PHP 7.4 and lots of files will be changed so it need to be compatible with it.

2020-05-09 07:04 UTC, ihor-sviziev commented
@magento run all tests

2020-05-12 03:53 UTC, ihor-sviziev commented
@magento run all tests

2020-05-12 10:49 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Sent product create request with XML request body and "Content-Type: application/xml" header.
![Screenshot from 2020-05-12 13-35-29](https://user-images.githubusercontent.com/51679138/81674502-f9111a00-9455-11ea-975e-b5afdf0651d6.png)

**Before:** 
:heavy_multiplication_x:  Got an error: "**Decoding error: Unable to unserialize value. Error:...**"
![Screenshot from 2020-05-08 16-10-15](https://user-images.githubusercontent.com/51679138/81674604-22ca4100-9456-11ea-9c1f-c047f6b27f87.png)

**After:**
:heavy_check_mark: 200 Response. The product was successfully created. 
![Screenshot from 2020-05-12 13-35-47](https://user-images.githubusercontent.com/51679138/81674720-4f7e5880-9456-11ea-919e-660baa3198a6.png)

2. Sent product update request with XML request body (add `<price>321</price>` for ex.)

**After:** :heavy_check_mark: The product was successfully updated. 

![Screenshot from 2020-05-12 13-37-34](https://user-images.githubusercontent.com/51679138/81674843-818fba80-9456-11ea-9656-3929f80ff002.png)

3. Create another product with JSON request body and "Content-Type: application/json" header.
![Screenshot from 2020-05-12 13-47-07](https://user-images.githubusercontent.com/51679138/81675221-23170c00-9457-11ea-8fed-97e9ff3511f5.png)

**After:** The product was successfully created.

2020-05-12 21:20 UTC, slavvka requested changes
@Neos2007 Please merge the latest mainline and re-run tests

2020-05-15 13:24 UTC, Neos2007 commented
@magento run all tests

2020-05-15 19:29 UTC, ihor-sviziev requested changes
Hi @Neos2007,
Please fix compatibility issues with phpunit 9

2020-05-18 12:29 UTC, ihor-sviziev requested changes

2020-05-18 12:29 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Unit/Model/Product/Webapi/Rest/RequestTypeBasedDeserializerTest.php
> +    public function setUp()
```suggestion
    public function setUp(): void
```

2020-05-18 12:29 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Unit/Model/Product/Webapi/Rest/RequestTypeBasedDeserializerTest.php
> +    private function prepareXmlDeserializer()
```suggestion
    private function prepareXmlDeserializer(): DeserializerXml
```

2020-05-18 12:29 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Unit/Model/Product/Webapi/Rest/RequestTypeBasedDeserializerTest.php
> +    private function prepareJsonDeserializer()
```suggestion
    private function prepareJsonDeserializer(): DeserializerJson
```

2020-05-18 12:29 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Unit/Model/Product/Webapi/Rest/RequestTypeBasedDeserializerTest.php
> +    public function getDeserializerDataProvider()
```suggestion
    public function getDeserializerDataProvider(): array
```

2020-05-18 12:29 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Test/Unit/Model/Product/Webapi/Rest/RequestTypeBasedDeserializerTest.php
> +    ) {
```suggestion
    public function testDeserialize(
        string $body,
        string $contentType,
        DeserializerInterface $deserializer,
        array $expectedResult
    ): void {
```

2020-05-18 12:43 UTC, ihor-sviziev commented
Hi @Neos2007,
Could you update your PR with changes I've listed above or provide write access for maintainers, so I'll be able to update your branch myself?

2020-05-19 18:32 UTC, nuzil commented
Hi @ihor-sviziev, done

2020-05-19 18:35 UTC, ihor-sviziev commented
@magento run all tests

2020-05-20 03:45 UTC, ihor-sviziev approved these changes

2020-05-20 03:47 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7530](https://jira.corp.magento.com/browse/ENGCOM-7530) has been created to process this Pull Request

2020-05-20 09:54 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed
The results the same as in [comment](https://github.com/magento/magento2/pull/28140#issuecomment-627265785)

2020-05-22 14:30 UTC, sdzhepa approved these changes

2020-05-22 14:32 UTC, magento-engcom-team commented
Hi @sdzhepa, thank you for the review.
[ENGCOM-7530](https://jira.corp.magento.com/browse/ENGCOM-7530) has been created to process this Pull Request

2020-05-28 02:51 UTC, merged