Invalidate product index after change product position in the category
magento/magento2 pull request #28150
Opened 2020-05-08 06:36 UTC by aleksinoleg

### Description (*)

Dispatching event "catalog_category_change_products" if there are products with updated position while saving the category

### Fixed Issues (if relevant)

1. magento/magento2#28149: Changing product position in the category has no effect on the front-end

### Manual testing scenarios (*)

1. Go to admin panel -> catalog -> inventory -> categories
2. Click on any category with the products and visible on the front-end
3. On the "Products in Category" tab change position of some product (do not delete or add any product from/to category)
4. Click the "Save" button

**Expected result**
1. Product indexes are invalidated
2. After running cron jobs "indexer_reindex_all_invalid" and "indexer_update_all_views" product position on the category page is changed on the frontend.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-08 06:42 UTC, ihor-sviziev commented
Hi @aleksinoleg,
Could you sign Adobe CLA and cover this case with MFTF test?

2020-05-08 06:43 UTC, ihor-sviziev requested changes
Hi @aleksinoleg,
Could you sign Adobe CLA and cover this case with MFTF test?

2020-05-08 06:43 UTC, aleksinoleg commented
Will reopen it again

2020-05-08 06:44 UTC, ihor-sviziev commented
Just requesting my changes again in order to have correct PR status

2020-05-08 06:44 UTC, ihor-sviziev requested changes
Hi @aleksinoleg,
Could you sign Adobe CLA and cover this case with MFTF test?

2020-05-08 07:16 UTC, aleksinoleg commented
I have no ability to cover these changes by tests. Could somebody help me with that?

2020-05-08 07:57 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/ResourceModel/Category.php
> -        $this->_attributes = [];
That was static test that property was declared dynamically and actually never used.

2020-05-13 13:50 UTC, ihor-sviziev commented
@engcom-Charlie could you help with covering this change with mftf test?

2020-05-13 13:58 UTC, engcom-Charlie commented
Hi @ihor-sviziev, yes sure.

2020-05-14 13:02 UTC, engcom-Charlie commented
@magento run all tests

2020-05-14 16:53 UTC, engcom-Charlie commented
The issue was only in the case indexer `catalog_category_product` => `UPDATE BY SCHEDULE`
We change product position on a category page but indexer was still valid(incorrect).
But if we run reindex as result we have correct sorting on front.
So I think that checking indexer status after changing positions will be enough.

@ihor-sviziev, What do You think?

2020-05-14 17:08 UTC, ihor-sviziev commented
@engcom-Charlie looks good. Test were failing on 2.4-develop branch ?

2020-05-14 17:53 UTC, ihor-sviziev approved these changes

2020-05-14 17:54 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7554](https://jira.corp.magento.com/browse/ENGCOM-7554) has been created to process this Pull Request

2020-05-14 17:54 UTC, magento-engcom-team commented
@aleksinoleg thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-05-15 10:47 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a category with a few simple products;
2. Set all indexes mode to "Update by Schedule" (Admin->System->Index Management);
![Screenshot from 2020-05-15 12-33-13](https://user-images.githubusercontent.com/51679138/82035557-56040e80-96a8-11ea-8724-5257ebfb63e8.png)
3. Go to Admin -> Catalog -> Inventory -> Categories;
4. Click on any category with the products and visible on the front-end;
5. On the "Products in Category" tab change position of some product (do not delete or add any product from/to category)
![screenshot_11](https://user-images.githubusercontent.com/51679138/82034507-f1947f80-96a6-11ea-860a-0c74219f2ddf.png)
6. Go to Storefront -> Category with products;

**Before:**

:heavy_multiplication_x:  All indexes are still valid

![Screenshot from 2020-05-15 12-30-05](https://user-images.githubusercontent.com/51679138/82035187-dbd38a00-96a7-11ea-81aa-d089f0cf51dd.png)

:heavy_multiplication_x: The product position on the category page on the frontend is not changed.

![Screenshot from 2020-05-15 12-24-26](https://user-images.githubusercontent.com/51679138/82035219-e8f07900-96a7-11ea-8015-d1102b9214f0.png)

**After:**

:heavy_check_mark:  Product indexes are invalidated;

![Screenshot from 2020-05-15 13-21-21](https://user-images.githubusercontent.com/51679138/82042343-64efbe80-96b2-11ea-8816-1ab5ea1cf937.png)

:heavy_check_mark:  After running cron jobs "indexer_reindex_all_invalid" and "indexer_update_all_views" product position on the category page is changed on the frontend.

![Screenshot from 2020-05-15 13-37-17](https://user-images.githubusercontent.com/51679138/82042357-69b47280-96b2-11ea-9fff-e45e73df3765.png)

2020-05-21 00:09 UTC, merged