changed attributes populated from module-catalog instead of module-ca…
magento/magento2 pull request #28151
Opened 2020-05-08 06:52 UTC by ProkopovVitaliy

…talog-search

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#26002: When category selected from top level navigation, attributes populated from module-catalog-search instead of module-catalog 

### Manual testing scenarios (*)

1.Install Magento
2.Add a log entry in /var/www/html/magento23/vendor/magento/module-catalog-search/Model/Layer/Filter/Attribute.php near line 81 (first line in _getItemsData() method
3.In the default LUMA store select Men -> Tops -> Jackets

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-08 07:34 UTC, srsathish92 commented
@ProkopovVitaliy Given fix not working for swatches with layered navigation. I have tried the same earlier in this PR #28058. can you please check failure functional test, May be it will help.

Additional Info: Its throw errors on lib/internal/Magento/Framework/Data/Collection.php: Line No: 408

2020-05-08 07:39 UTC, ProkopovVitaliy commented
@srsathish92 Thanks for the info, I didn't pay attention to it.

I will check and fix it.

2020-05-09 02:36 UTC, orlangur requested changes

2020-05-09 02:36 UTC, orlangur commented on app/code/Magento/CatalogSearch/etc/di.xml
> -    <virtualType name="categoryFilterList" type="Magento\Catalog\Model\Layer\FilterList">
What was the purpose of such declaration at all?

2020-07-21 10:22 UTC, engcom-Charlie commented
Hi @ProkopovVitaliy, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-07-21 10:22 UTC, closed without merging