Update Issue and PR templates
magento/magento2 pull request #28168
Opened 2020-05-08 18:51 UTC by sdzhepa

### Description (*)
This PR contains 2 improvements/updates

#### 1. Updated Issue related templates
Added section that allows a reporter to set initial Severity during issue reporting as it described on DevDoc  [Who and how can define severity and priority](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#who-and-how-can-define-severity-and-priority) 
```
Issue reporters can provide their own evaluation for severity by selecting a checkbox in the Issue description.
```

#### 2. Improve Pull Request templates
Added keyword to the section Fixed Issue
```
Fixes magento/magento2#<issue_number>
```
This keyword should improve automatically linking PR -> Issue, according to GitHub documentation [Linking a pull request to an issue using a keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

2020-05-08 23:37 UTC, sdzhepa commented
@magento run all test

2020-05-08 23:43 UTC, sdzhepa commented
@magento run all tests

2020-05-09 02:34 UTC, orlangur requested changes

2020-05-09 02:34 UTC, orlangur commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
"without workaround" maybe?

2020-05-09 02:34 UTC, orlangur commented on .github/PULL_REQUEST_TEMPLATE.md
> +1. Fixes magento/magento2#<issue_number>
👍

2020-05-11 15:45 UTC, sdzhepa commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
Fixed, thank you

2020-05-12 14:58 UTC, ihor-sviziev approved these changes
Approved ✔
Test failures are definitely not related to changes in this PR.

2020-05-12 14:59 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7537](https://jira.corp.magento.com/browse/ENGCOM-7537) has been created to process this Pull Request

2020-05-12 18:25 UTC, okorshenko approved these changes

2020-05-12 18:26 UTC, magento-engcom-team commented
Hi @okorshenko, thank you for the review.
[ENGCOM-7537](https://jira.corp.magento.com/browse/ENGCOM-7537) has been created to process this Pull Request

2020-05-13 07:42 UTC, engcom-Alfa commented
QA not applicable

2020-05-13 09:53 UTC, engcom-Charlie commented
Failed functional tests not related to changes from this PR.

2020-05-21 00:09 UTC, merged