Allows JSON unserializing to be associative or object
magento/magento2 pull request #28192
Opened 2020-05-11 19:43 UTC by jajajaime

### Description (*)

Allows a developer to pass an optional boolean argument when unserializing a JSON string, so it can be returned as object or associative. Keeps associative as default for backwards compatibility.

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

1. Create code that unserializes json string while passing the extra argument of false

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2020-05-12 14:41 UTC, ihor-sviziev commented
I remember we had some architecture discussions in https://github.com/magento/architecture/pull/254, https://github.com/magento/magento-coding-standard/pull/91 and 
 previously in https://github.com/magento/architecture/pull/161.

AFAIK no real decision was done yet. @lenaorobei do we have any updates on that?

2020-05-16 05:18 UTC, orlangur requested changes

2020-05-16 05:18 UTC, orlangur commented on lib/internal/Magento/Framework/Serialize/Serializer/Json.php
> +    public function unserialize($string, $assoc = true)
Such change is not allowed: https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/

Let's first find out whether we need such functionality at all.

2020-05-18 12:20 UTC, ihor-sviziev commented
@orlangur please explain why you moved this PR to "on hold" status.

2020-05-18 15:14 UTC, lenaorobei commented
Unfortunately, we cannot accept this PR since it violates backward compatibility policy.

There were some discussions regarding introduction new JSON contract, but there is no resolution yet. Please see details here https://github.com/magento/architecture/pull/254

2020-05-18 15:14 UTC, closed without merging

2020-05-18 15:39 UTC, jajajaime commented
@lenaorobei is this because of "Adding parameters in public methods"? If so, I think it should be on a case by case basis, as creating a new class or interface would create more work for devs to switch to the new one in this case.

2020-06-01 04:52 UTC, orlangur commented
@jajajaime backward compatibility policy is mandatory, no exception.

> when unserializing a JSON string, so it can be returned as object or associative

Please create a proposal in architecture repo first to describe why it needs to be returned as object.