Replace hard-coded list of category attributes
magento/magento2 pull request #28216
Opened 2020-05-13 20:36 UTC by fredden

### Description
`Magento\Catalog\Model\Category\DataProvider::getFieldsMap()` had a hard-coded list of category attributes. This pull request replaces this with a list generated from cache. The cache is built from reading `view/adminhtml/ui_component/category_form.xml` files, so this dynamically generated list includes all category attributes, not only those in the hard-coded list.

### Fixed Issues
1. Fixes #13440 - Adding custom attribute to category doesn't show store specific value

### Manual testing scenarios
See issue #13440 for reproduction steps, expected result, and actual result.

### Questions or comments
I have not yet updated any tests, however I have tested this locally.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-05 16:04 UTC, FredericMartinez commented
It works in `2.3.5-p1`
Thanks @fredden

2020-07-10 13:51 UTC, marvinhinz commented
@magento run all tests

2020-07-10 14:05 UTC, thampe commented
This Looks good, I also tested it in `2.35-p1`.

2020-07-10 14:44 UTC, marvinhinz commented
@magento-engcom-team any idea why there are no build reports?

2020-07-13 14:55 UTC, marvinhinz commented
@magento run all tests

2020-07-13 17:54 UTC, fredden commented
@magento run all tests

2020-07-27 18:38 UTC, fredden commented
@magento run all tests

2020-08-17 17:19 UTC, lenaorobei commented
@magento run all tests

2020-08-17 17:21 UTC, lenaorobei commented on app/code/Magento/Catalog/Model/Category/DataProvider.php
> +        $this->uiConfigFactory = $uiConfigFactory;
To keep backward compatibility let's add nullable argument.

2020-08-17 17:24 UTC, lenaorobei commented on app/code/Magento/Catalog/Model/Category/DataProvider.php
> +            if (empty($fieldsMap[$group])) {
I believe we can remove this along with assignment in the line 674.

2020-08-17 17:25 UTC, lenaorobei requested changes
Please see review comments. 

Looks like the fix should be applied to commerce repo. You can easily open commerce PR and link this this one through PR description.

2020-08-21 17:14 UTC, fredden commented on app/code/Magento/Catalog/Model/Category/DataProvider.php
> +            if (empty($fieldsMap[$group])) {
Technically we can remove this and the assignment on 674. I'd prefer to keep these however, as I feel like this method is more explicit in intent: showing clearly that empty groups are omitted on purpose.

The PHP manual also suggests that implicit array creation is discouraged. (Emphasis is mine.)

https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying

> If $arr doesn't exist yet, it will be created, so this is also an alternative way to create an array. **This practice is however discouraged** because if $arr already contains some value (e.g. string from request variable) then this value will stay in the place and [] may actually stand for string access operator. **It is always better to initialize a variable by a direct assignment.**

2020-08-21 17:37 UTC, fredden commented on app/code/Magento/Catalog/Model/Category/DataProvider.php
> +        $this->uiConfigFactory = $uiConfigFactory;
As far as I know, Magento's stance on extension is to prefer [composition over inheritance](https://devdocs.magento.com/guides/v2.4/ext-best-practices/extension-coding/common-programming-bp.html#composition-over-inheritance). If a third party has extended this model via a preference (which is documented as "[a method of last resort](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/di-xml-file.html#override-a-method-using-preference-nodes)"), then keeping their extension up to date with changes here is a necessary cost to using such a technique. I do not see any benefit in using a nullable argument here.

My objections aside, I do not know how to create this object if not via dependency injection. (I have no experience with the Object Manager as "[Magento prohibits the direct use of the `ObjectManager`](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/object-manager.html)" and any existing usages "[are not tacit endorsements of using the `ObjectManager` directly.](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/object-manager.html#usage-rules)" I understand this exists as an internal implementation detail of Magento's dependency injection system.)
How should I create this `virtualType` if not supplied via dependency injection?
https://github.com/magento/magento2/blob/8b7d949bf1cb67d7b98379fb30b6721ec7b92b37/app/code/Magento/Ui/etc/di.xml#L339-L343

2020-08-21 17:47 UTC, fredden commented
Thanks for looking at this @lenaorobei. I've addressed both of your code comments; please see my explanations/question and let me know if you would like me to make any changes.

> Looks like the fix should be applied to commerce repo. You can easily open commerce PR and link this this one through PR description.

I don't understand this, sorry. This code (hard-coded list of attributes) exists in this version (`community` / Open Source) of Magento, so should be fixed here. I have already opened a pull request for `enterprise` / Commerce version and provided a link in the description for this pull request, and linked to this from that. Is there special syntax that should be used to "link" these? I think I followed the template supplied when creating both of these pull requests.

2020-08-21 19:55 UTC, lenaorobei commented on app/code/Magento/Catalog/Model/Category/DataProvider.php
> +        $this->uiConfigFactory = $uiConfigFactory;
You are absolutely right about composition over inheritance principle. However, constructor modification is considered as a braking change. As a workaround, we recommend adding new optional parameter to the constructor at the end of the arguments list.

Please refer to the [Backward compatible development guide](https://devdocs.magento.com/contributor-guide/backward-compatible-development/) and section about `Adding a constructor parameter`.

2020-08-21 20:00 UTC, lenaorobei commented on app/code/Magento/Catalog/Model/Category/DataProvider.php
> +            if (empty($fieldsMap[$group])) {
In this case I'd prefer creating array variable to collect needed data and if it is not empty, write this data to `$fieldsMap[$group]`.

2020-08-21 20:08 UTC, lenaorobei commented
@magento run all tests

2020-08-21 20:10 UTC, lenaorobei commented
@fredden thanks for explanation. My bad, I missed the link to `commerce` PR.

I've formatted PR description by adding `Related Pull Requests` section. This will allow our infrastructure to run builds respecting changes in both repositories. You can find this in build details.

<img width="1148" alt="Screen Shot 2020-08-21 at 3 08 36 PM" src="https://user-images.githubusercontent.com/17548019/90930463-47707600-e3c0-11ea-8932-9953ae4b255f.png">

2020-08-21 20:17 UTC, lenaorobei commented
In addition to that I believe we need to cover newly introduces changes with integration test.

2020-08-26 22:58 UTC, fredden commented
Can I please get some help writing suitable tests for this change?

2020-08-26 22:58 UTC, fredden commented
@magento run all tests

2020-08-26 23:01 UTC, fredden commented
@magento run all tests

2020-08-27 17:00 UTC, lenaorobei commented on app/code/Magento/Catalog/Model/Category/DataProvider.php
> +            if (count($fields)) {
```suggestion
            if (!empty($fields)) {
```

2020-08-27 17:05 UTC, lenaorobei commented
I recommend looking at `Magento\Catalog\Model\Category\DataProviderTest` as an example.

Please note also that Integration build failed and needs to be addressed https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28216/24348333bfd24d15a02ce17ab5aabbc7/Integration/allure-report-ce/index.html#suites/1a47ad2d0b8dde3b8bc5178a8df7e3fb/8fa7f03a7c7e6e9c/

The same for Static build https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28216/2370b22c2e6f31410ec42677e0b5a155/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/e670dd9849cb50d8/

2020-09-16 11:41 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-22 09:35 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-22 14:25 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-25 16:10 UTC, lenaorobei approved these changes

2020-10-01 09:10 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create new module with Setup InstallData.php
2. Install new category attribute following Magento's current category attribute array.
[magento-bug2.txt](https://github.com/magento/magento2/files/1681035/magento-bug2.txt)
3. Add view/adminhtml/ui_component/category_form.xml for above attribute
[magento-bug.txt](https://github.com/magento/magento2/files/1681033/magento-bug.txt)
4. php bin/magento setup:upgrade
5. Set different values per scope level using store switcher

**Before:**
:heavy_multiplication_x:  Can't see [Store View] label under attribute label.
:heavy_multiplication_x:  Can't see different values per scope level (global, website, store)

![2020-10-01_12-03](https://user-images.githubusercontent.com/51679138/94789833-1bdca480-03de-11eb-9a07-8e39b1d0743e.png)

**After:** 
:heavy_check_mark: [Store View] label under attribute label.
:heavy_check_mark: Able to see different values per scope level (global, website, store)

![2020-10-01_12-06](https://user-images.githubusercontent.com/51679138/94790176-9b6a7380-03de-11eb-9245-b5c89e8d81bd.png)
_On Storefront:_
![Peek 2020-10-01 11-33](https://user-images.githubusercontent.com/51679138/94790194-a0c7be00-03de-11eb-9f2b-8ef70829f6f0.gif)

_On Admin panel:_ 
![Peek 2020-10-01 12-08](https://user-images.githubusercontent.com/51679138/94790548-1a5fac00-03df-11eb-95a5-9a3fc88a95bd.gif)

2020-10-01 13:37 UTC, engcom-Foxtrot commented
@magento run all tests

2020-10-02 08:46 UTC, engcom-Foxtrot commented
@magento run all tests

2020-10-07 20:18 UTC, merged