Prefix dropdown in checkout doesn't select empty value by default if required
magento/magento2 pull request #28238
Opened 2020-05-15 08:24 UTC by engcom-Charlie

### Description (*)

### Related Pull Requests
Fixes #18823

### Fixed Issues (if relevant)

1. magento/magento2#18823:Prefix dropdown in checkout doesn't select empty value by default if required

### Manual testing scenarios (*)

Please see #18823

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-15 08:26 UTC, engcom-Charlie commented
@magento run all tests

2020-05-16 05:14 UTC, orlangur requested changes
Let's first try to understand whether logic change is valid and only then apply necessary changes.

2020-05-16 05:14 UTC, orlangur commented on dev/tests/integration/testsuite/Magento/Customer/Model/OptionsTest.php
> +        $this->assertCount($expectedCount, $options);
Excessive assert, please remove.

2020-05-16 05:14 UTC, orlangur commented on dev/tests/integration/testsuite/Magento/Customer/Model/OptionsTest.php
> + * @magentoDbIsolation enabled
We don't need interaction with a real DB to check this logic, please convert to unit test.

2020-05-16 05:14 UTC, orlangur commented on dev/tests/integration/testsuite/Magento/Customer/Model/OptionsTest.php
> +    private const STUB_EXPECTED_VALUES = ['v1' => 'v1', 'v2' => 'v2'];
Such test data is totally unreadable, please inline all constants and if you need some value in two places just create a variable in-place.

2020-05-16 05:14 UTC, orlangur commented on app/code/Magento/Customer/Model/Options.php
> +            $value = $this->escaper->escapeHtml(trim($value)) ?: ' ';
Why do we need a space value?

2020-05-16 05:14 UTC, orlangur commented on app/code/Magento/Customer/Model/Options.php
>              $result = array_merge([' ' => ' '], $result);
Well, I don't understand the logic after such change. In optional field we add empty value, but in required field we allow empty value. How empty value can be valid for a required field?

Does it really works this way in registration?

https://github.com/magento/magento2/issues/18823#issuecomment-433606725

2020-05-17 18:26 UTC, engcom-Charlie commented
Hi @orlangur, thank you for review, in the required field we add empty value only for it will be shown by default but we can't place an order with this on checkout or create a customer with blank value.

2020-05-18 14:07 UTC, engcom-Charlie commented
@magento run all tests

2020-05-29 04:59 UTC, orlangur commented
@engcom-Charlie thanks, need to check this behavior in action.

2020-06-26 14:20 UTC, engcom-Charlie commented
Hi @orlangur, do You've any updates?

2020-07-06 16:03 UTC, engcom-Charlie commented
Hi @ihor-sviziev,
can You please review this PR?

2020-07-10 21:19 UTC, VladimirZaets submitted a review, later dismissed

2020-07-10 21:21 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7825](https://jira.corp.magento.com/browse/ENGCOM-7825) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-07-15 08:01 UTC, engcom-Alfa requested changes
Hi @engcom-Charlie .

During testing, we faced the issue.

**Manual testing scenario:**

1. In Admin Backend go to Stores > Configuration > Customers > Name and Address Options;
2. Set "Show Prefix" to "Required";
3. Set "Prefix Dropdown Options" to ";Mr;Mrs;"
4. Save Config;
5. Go to your store;
6. Add an item to your cart;
7. Go to checkout;

As per [comment](https://github.com/magento/magento2/pull/26640#issuecomment-584193529), the expected behavior is:

`;Mr;Ms;`- select with `""`, `Mr`, `Ms` and `""`

but, **Actual Result:** :heavy_multiplication_x: `;Mr;Ms;`- select with `""`, `Mr`, `Ms`

![2020-07-15_10-46](https://user-images.githubusercontent.com/51679138/87519504-5f026380-c68a-11ea-9dbe-3b80b28fcc9a.png)

@engcom-Charlie Could you take a look?

Thanks!

2020-07-21 12:24 UTC, engcom-Charlie commented
@magento run all tests

2020-07-21 19:05 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-07-28 12:10 UTC, engcom-Charlie commented
Hi @ihor-sviziev, can You please review this PR?

2020-07-28 13:01 UTC, ihor-sviziev approved these changes

2020-07-28 13:02 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7825](https://jira.corp.magento.com/browse/ENGCOM-7825) has been created to process this Pull Request

2020-07-29 07:05 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. In Admin Backend go to Stores > Configuration > Customers > Name and Address Options;
2. Set "Show Prefix" to "Required";
3. Set "Prefix Dropdown Options" to "`;Mr;Mrs`"
4. Save Config;
5. Go to your store;
6. Add an item to your cart;
7. Go to checkout;

**Before:** :heavy_multiplication_x: Instead of having the empty value selected by default it will be always the first value selected.

![2020-07-29_09-46](https://user-images.githubusercontent.com/51679138/88766333-83793800-d180-11ea-8408-ccfa8d46e4f4.png)

**After:** :heavy_check_mark: The empty value in the drop-down prefix was selected by default.

![2020-07-29_09-54](https://user-images.githubusercontent.com/51679138/88766901-80cb1280-d181-11ea-8c20-d19814f4a02b.png)

**Case 2. Set Prefix  to** **"**`Mr;Mrs;`**"**

**After:** :heavy_check_mark: Empty value at the end of the list

![2020-07-29_09-58](https://user-images.githubusercontent.com/51679138/88767543-765d4880-d182-11ea-82b7-dd4bd2407ff2.png)

**Case 3. Set Prefix  to** **"**`;Mr;Ms;`**"**

**After:** :heavy_check_mark: Empty value at the beginning and end of the list

![2020-07-29_10-03](https://user-images.githubusercontent.com/51679138/88767872-e5d33800-d182-11ea-810d-8e4357ffd5af.png)

_Note:_ As per [comment](https://github.com/magento/magento2/pull/26640#issuecomment-584193529), the expected behavior is:

`Mr;Ms;`  - select with `Mr` , `Ms` and `""`
`;Mr;Ms` - select with `""`, `Mr` and `Ms`
`;Mr;Ms;`- select with `""`, `Mr`, `Ms` and `""`

2020-08-13 16:38 UTC, merged