#26637: Fixing issue with Invalid customer id
magento/magento2 pull request #28247
Opened 2020-05-17 00:03 UTC by srenon

### Description (*)

Invalid customer ID issue coming on the checkout while placing the order. This issue comes randomly for the customers who are logged in on the website. This issue is related to the customer quote, the table quote_address stays empty for this quote.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#23618: Invalid address id at check out

### Manual testing scenarios (*)

1. Disable guest checkout
2. While still logged out, add an item to your cart (has this issue with downloadable product)
3. Then click checkout
4. On the log in screen. Log in with a customer that already has a save cart and billing info

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-05 12:37 UTC, ihor-sviziev requested changes
Hi @srenon,
Could you apply suggested change with simplification and cover your change with any type of automated tests?

2020-10-05 12:37 UTC, ihor-sviziev commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +        }
```suggestion
        $quote->setCustomerIsGuest(!$quote->getCustomer()->getId());
```

2020-10-05 12:37 UTC, ihor-sviziev commented
@magento run all tests

2020-10-05 12:49 UTC, ihor-sviziev commented
Seems like this PR also fixes #23908

2020-10-19 07:34 UTC, engcom-Hotel commented
@magento run all tests

2020-10-19 07:36 UTC, engcom-Hotel commented on app/code/Magento/Quote/Model/QuoteManagement.php
> +        }
Has been updated.

2020-10-19 16:46 UTC, ihor-sviziev commented
@engcom-Hotel tests still failing, could you check it ?

2020-10-20 08:55 UTC, engcom-Hotel commented
@ihor-sviziev will check it.

2020-10-20 19:37 UTC, ihor-sviziev commented
@magento run all tests

2020-10-21 13:19 UTC, ihor-sviziev requested changes
Moving to correct status. Tests should be adjusted.

2020-10-21 13:59 UTC, engcom-Hotel commented
Hello @srenon
Could you please provide more detailed steps to reproduce the issue?
Thank you.

2020-10-22 06:47 UTC, engcom-Hotel commented
@magento run all tests

2020-11-03 07:54 UTC, engcom-Hotel commented
Hello @srenon.
Please respond to my previous comment. Otherwise, PR could be closed due to inactivity.
Thank you.

2020-11-03 15:09 UTC, JKetelaar commented
Still facing this issue, though with this PR it's fixed - so please do not close it...

2020-11-04 11:08 UTC, engcom-Hotel commented
@JKetelaar could you please provide detailed steps to reproduce the issue?
Thank you.

2020-11-10 11:28 UTC, engcom-Hotel commented
Hello @srenon,
Closing the issue due to inactivity.
Please feel free to reopen it.
Thanks.

2020-11-10 11:28 UTC, closed without merging

2021-04-12 13:46 UTC, groomershop-mt commented
In our case this commits also don't  fix problem at Magento 2.4.2.

2021-05-10 09:38 UTC, barryvdh commented
@groomershop-mt  did you apply this patch?