Multiple arguments in module:status command
magento/magento2 pull request #28250
Opened 2020-05-18 05:17 UTC by chandru-199

### Description (*)

As of now `module:status` command accepts only one parram. But 'module:enable` and `module:disable` accepts multiple module names as argument. So, in same way `module:status` command also can accept multiple module names as argument.

### Related Pull Requests
NA

### Manual testing scenarios (*)

1. Run `module:status` command with multiple module names. ex `module:status module1 module2`.
2. We will get cli output in following pattern.
`module1 : Module is enabled`
`module2 : Module is disabled`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-19 04:48 UTC, chandru-199 commented
@magento run all tests

2020-05-19 06:00 UTC, chandru-199 commented
@magento run all tests

2020-06-24 16:39 UTC, chandru-199 commented
@magento run Static Tests

2020-07-29 09:56 UTC, ihor-sviziev commented
@magento run all tests

2020-07-29 13:14 UTC, ihor-sviziev requested changes
Hi @chandru-199,
Could you fix static test failures?

2020-07-30 08:43 UTC, engcom-Charlie commented
@magento run all tests

2020-07-30 08:45 UTC, chandru-199 commented
@ihor-sviziev : sure.

2020-07-30 08:47 UTC, chandru-199 commented
Thank you @engcom-Charlie for you static test fix.

2020-07-30 12:16 UTC, ihor-sviziev requested changes
Looks like we have few small issues. Please check them.

Everything else looks good to me

2020-07-30 12:16 UTC, ihor-sviziev commented on setup/src/Magento/Setup/Console/Command/ModuleStatusCommand.php
> +            return 0;
```suggestion
            return Cli::RETURN_SUCCESS;
```

2020-07-30 12:16 UTC, ihor-sviziev commented on setup/src/Magento/Setup/Console/Command/ModuleStatusCommand.php
> +        return 0;
```suggestion
        return Cli::RETURN_SUCCESS;
```

2020-07-30 12:52 UTC, engcom-Charlie commented
@magento run all tests

2020-07-31 09:33 UTC, ihor-sviziev approved these changes

2020-07-31 09:34 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7925](https://jira.corp.magento.com/browse/ENGCOM-7925) has been created to process this Pull Request

2020-07-31 10:01 UTC, engcom-Alfa commented
@magento create issue

2020-07-31 10:38 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

Run `module:status` command with multiple module names. ex `php bin/magento module:status Magento_Version Magento_Wishlist`.

**Before:** :heavy_multiplication_x: Too many arguments....

![Screenshot from 2020-07-31 13-26-53](https://user-images.githubusercontent.com/51679138/89026519-8a937800-d331-11ea-8aa2-3341358d52f8.png)


**After:** :heavy_check_mark: We got CLI output in the following pattern.
`Magento_Version : Module is disabled`
`Magento_Wishlist : Module is enabled` 

![Screenshot from 2020-07-31 13-24-17](https://user-images.githubusercontent.com/51679138/89026338-34bed000-d331-11ea-8121-e2c5bf943f61.png)

**Case 2. With one non-existent module**

Run `module:status` command with multiple module names. ex `php bin/magento module:status Magento_Version Magento_Test`.

**After:** :heavy_check_mark: We got CLI output in the following pattern.

![Screenshot from 2020-07-31 13-25-15](https://user-images.githubusercontent.com/51679138/89027343-fe825000-d332-11ea-9c78-f5643101801b.png)

2020-08-08 06:57 UTC, merged