Base Price Storage model fix.
magento/magento2 pull request #28281
Opened 2020-05-19 11:41 UTC by wassuupp

Fix V1/products/base-prices endpoint to update prices for Catalog Price Mode - Website

### Description (*)
V1/products/base-prices endpoint does not work with Catalog Price Mode - Website
Function was added to affect prices for all store views inside changed website

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-20 13:41 UTC, wassuupp commented
@magento run all tests

2020-06-03 21:12 UTC, nuzil requested changes
Can you also cover this fix with tests?

2020-06-03 21:12 UTC, nuzil commented on app/code/Magento/Catalog/Model/Product/Price/BasePriceStorage.php
> +        try {
I would not add here try / catch. Cause if such attribute do not exists, exception will be much earlier, already on $this->getPricePersistence() method

2020-06-03 21:12 UTC, nuzil commented on app/code/Magento/Catalog/Model/Product/Price/BasePriceStorage.php
> +            $formattedPrices = $this->applyWebsitePrices($formattedPrices);
So lets put this together with previous part

2020-06-03 21:12 UTC, nuzil commented on app/code/Magento/Catalog/Model/Product/Price/BasePriceStorage.php
> +                continue;
I would throw here an exception directly without allowing user to even save any prices

2020-06-23 00:54 UTC, VladimirZaets commented
@wassuupp , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

2020-06-23 00:54 UTC, closed without merging

2020-07-15 10:04 UTC, nuzil commented
@VladimirZaets  ... wait a sec, I will push him :-D