CreditMemo service might ignore allowZeroGrandTotal
magento/magento2 pull request #28284
Opened 2020-05-19 16:39 UTC by amenk

When creating credit memos via the orderService, allowZeroGrandTotal is ignored

See also https://github.com/magento/magento2/pull/16005

Show me the test results :)

2020-05-19 16:45 UTC, amenk commented
Still it is not possible to use

            // orderRefunder =  \Magento\Sales\Api\RefundOrderInterface
            $this->orderRefunder->execute(
                $id,
                [],
                true
            );


Because of \Magento\Sales\Model\Order\Validation\CanRefund::isTotalPaidEnoughForRefund

2020-05-20 09:11 UTC, amenk commented
There is a lot of logic duplication between CreditMemos and Order, not sure how to refactor this properly, help appreciated

2020-05-20 12:38 UTC, amenk commented
We probably have a workaround: Instead of creating 0-value credit memos we can use $order->cancel(), still it is strange that via backend we can create a 0-value credit memo but not via the service

2020-05-27 14:45 UTC, edenduong requested changes
Hi @amenk ,

Thank you for your contribution. I see the logic is correct. Could you please cover your changes with Unit Test ? Thank you very much.

2020-05-27 14:50 UTC, amenk commented
This seems to need some more work. Would be nice if someone else could jump in

I will not follow this bug anymore because we decided for another approach without invoices and credit memos for 0 totals

2020-06-08 00:53 UTC, edenduong commented
@amenk: Thank you. I will close this Pull Request. If someone continue to work, he/she can create new Pull request.

2020-06-08 00:53 UTC, closed without merging

2021-02-19 10:00 UTC, amenk commented
Does anybody know if this problem still appears?