Fix current tree path preselected folder on MediaGallery, after reopen instance
magento/magento2 pull request #28297
Opened 2020-05-20 11:32 UTC by Nazar65

DEPENED ON https://github.com/magento/magento2/pull/28219
### Description (*)

### Fixed Issues (if relevant)

1. https://github.com/magento/adobe-stock-integration/issues/1335:Requested default folder is not selected on opening media gallery (current_tree_path parameter)
### Manual testing scenarios (*)
1. Open media gallery from the category image field
2. Open media gallery from the WYSIWYG

### Expected result (*)
1. catalog/category directory is selected by default
2. WYSIWYG directory is selected by default
### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-20 14:29 UTC, gabrieldagama requested changes

2020-05-20 14:29 UTC, gabrieldagama commented on app/code/Magento/Cms/view/adminhtml/web/js/folder-tree.js
> +                pathId =  window.MediabrowserUtility.pathId.replace(',,', '--');
From our investigation it looks like the `,,` on the pathId (which comes from current_tree_path) just exists when we open the gallery from the uploader button, follow the request example:
`https://magento.local/admin/cms/wysiwyg_images/index/target_element_id/E5U0XX4/store/0/type/image/?isAjax=true&current_tree_path=Y2F0YWxvZy9jYXRlZ29yeQ,,`

But when we open from wysiwyg the problem isn't there:

`https://magento.local/admin/cms/wysiwyg_images/index/current_tree_path/d3lzaXd5Zw--/target_element_id/category_form_description/store/0/type/image/?isAjax=true`

It is probably related to the way the url parameters is being set, can we review the uploader button and fix it to not replace the `-` character? By doing that this replace can be removed.

2020-05-20 14:29 UTC, gabrieldagama commented on app/code/Magento/Cms/view/adminhtml/web/js/folder-tree.js
> +                        paths[i] = window.MediabrowserUtility.pathId.replace(',,', '--');
By fixing the uploader button url we will be able to remove this replace as well.

2020-05-20 14:29 UTC, gabrieldagama commented on app/code/Magento/Cms/view/adminhtml/web/js/folder-tree.js
> +            _decodePathId = function (val) {
Here we should replace the characters first and decode later. Exactly the opposite that the encodePathId is doing.

2020-05-20 15:41 UTC, Nazar65 commented
@magento run all tests

2020-05-20 15:44 UTC, Nazar65 commented
@magento run all tests

2020-05-21 09:12 UTC, Nazar65 commented
@magento run all tests

2020-05-21 10:19 UTC, Nazar65 commented
@magento run all tests

2020-05-21 14:00 UTC, Nazar65 commented
@magento run all tests

2020-05-28 06:29 UTC, Nazar65 commented
@mzgento run all tests

2020-05-28 06:46 UTC, Nazar65 commented
@magento run all tests

2020-05-28 19:15 UTC, Nazar65 commented
@magento run all tests

2020-05-29 06:32 UTC, Nazar65 commented
@magento run all tests

2020-06-01 08:02 UTC, Nazar65 commented
@magento run all tests

2020-06-10 06:36 UTC, Nazar65 commented
@magento run all tests

2020-06-23 12:48 UTC, Nazar65 commented
@magento run all tests

2020-06-23 12:56 UTC, Nazar65 commented
@magento run all tests

2020-06-23 16:13 UTC, Nazar65 commented
looks like the "page builder" tests affected, need to recheck failed tests

2020-09-07 10:51 UTC, gabrieldagama commented
The risk was set to `low` due to: the changes applied to this PR affect just a specific area on the admin.

2020-09-16 12:50 UTC, engcom-Golf commented
@magento run all tests

2020-11-11 22:29 UTC, sidolov commented
@Nazar65  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-11-11 22:29 UTC, closed without merging