Refactoring create product with several websites and check url rewrites test
magento/magento2 pull request #28391
Opened 2020-05-27 13:57 UTC by kate-kyzyma

### Description (*)
 AdminCreateProductWithSeveralWebsitesAndCheckURLRewritesTest is refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Run the StorefrontLoginWithIncorrectCredentialsTest in the local environment and verified the test runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-27 13:58 UTC, dmytro-ch commented
@magento run all tests

2020-05-28 09:34 UTC, dmytro-ch requested changes
Hello @kate-kyzyma, well done! The overall result looks good to me.
Could you please apply minor improvements?
Thank you!

2020-05-28 09:34 UTC, dmytro-ch commented on app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminSubmitCategoriesPopupActionGroup.xml
> +            <description>Clicks on Done on the search categories popup.</description>
```suggestion
            <description>Clicks the "Done" button on the Search Categories popup.</description>
```

2020-05-28 09:34 UTC, dmytro-ch commented on app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AssertAdminStoreValueIsSetForUrlRewriteActionGroup.xml
> +            <description>Validates that the proper Store Value is used for URL Rewrite.</description>
```suggestion
            <description>Verifies that the proper Store Value is used for URL Rewrite.</description>
```

2020-05-28 09:34 UTC, dmytro-ch commented on app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AssertAdminStoreValueIsSetForUrlRewriteActionGroup.xml
> +        <see selector="{{AdminUrlRewriteIndexSection.gridCellByColumnRowNumber('1', 'Store View')}}" userInput="{{storeValue}}" stepKey="seeStoreValueForCategoryId"/>
```suggestion
        <see selector="{{AdminUrlRewriteIndexSection.gridCellByColumnRowNumber('1', 'Store View')}}"
                  userInput="{{storeValue}}" stepKey="seeStoreValueForCategoryId"/>
```

2020-05-28 12:13 UTC, dmytro-ch commented
@magento run all tests

2020-06-02 08:12 UTC, dmytro-ch commented
@magento run all tests

2020-06-02 10:06 UTC, dmytro-ch approved these changes

2020-06-02 10:07 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7606](https://jira.corp.magento.com/browse/ENGCOM-7606) has been created to process this Pull Request

2020-06-03 13:59 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-06-05 15:42 UTC, merged