Replacing deprecated add success method
magento/magento2 pull request #28402
Opened 2020-05-28 09:27 UTC by gokulra92

### Description (*)

Replaced deprecated method "addSuccess()" with "addSuccessMessage()".

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-22 09:46 UTC, gokulra92 commented
@magento run all tests

2020-06-27 12:29 UTC, edenduong commented
@magento run all tests

2020-08-18 19:41 UTC, sidolov commented
@magento create issue

2020-08-19 11:18 UTC, VladimirZaets requested changes
Hi @gokulra92. Thanks for collaboration. Please take a look at my review comments

2020-08-19 11:18 UTC, VladimirZaets commented on app/code/Magento/Integration/Controller/Adminhtml/Integration/Delete.php
>                              $this->escaper->escapeHtml($integrationData[Info::DATA_NAME])
addSuccessMessage works a little bit differently way then addSuccess method. By default, it escapes all HTML. So, please check that message is correct and also you can remove  additional escape `$this->escaper->escapeHtml`

2020-08-19 11:18 UTC, VladimirZaets commented on app/code/Magento/Integration/Controller/Adminhtml/Integration/Save.php
>                          'The integration \'%1\' has been saved.',
The same here

2020-08-19 11:18 UTC, VladimirZaets commented on app/code/Magento/Integration/Controller/Adminhtml/Integration/TokensDialog.php
> +        $this->messageManager->addSuccessMessage($successMsg);
the same here

2020-08-19 11:18 UTC, VladimirZaets commented
@magento run all tests

2020-08-27 06:17 UTC, engcom-Charlie commented
Hi gokulra92, can you please look through the requested changes https://github.com/magento/magento2/pull/28402#pullrequestreview-470357277 and check failed tests?
Thank you.

2020-09-02 10:42 UTC, engcom-Charlie commented
Hi, @gokulra92 there is a lot of changed files that caused too many failures. I would recommend separating these changes to separate PRs. For example, you can replace deprecated methods per module.
What do you think?

2020-09-02 20:22 UTC, sidolov commented
@gokulra92  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-02 20:22 UTC, closed without merging