Performance colorpicker
magento/magento2 pull request #28400
Opened 2020-05-28 07:29 UTC by krzksz

### Description (*)
This is just another performance PR, which focuses on loading only the needed dependencies. This time I am optimizing color picker component and its `spectrum` and `tinycolor` dependencies.

Loading mentioned modules dynamically saves us 2 JavaScript requests and 123,6kB (28,3kB gzipped) from downloading and parsing.

This change is covered by unit tests that had to be adjusted to take asynchronous dependencies loading into account.

### Manual testing scenarios (*)

1. Verify that `spectrum.js` and `tinycolor.js` are no longer loaded by default.
2. Verify that above modules are loaded and color picker works as expected when used (see comment above to find out how to add it).

### Questions or comments
While making sure this change doesn't break anything I found out that `colorPicker` binding is not used anywhere in Magento. The easiest way to get it is to for example add it to `app/code/Magento/Catalog/view/adminhtml/ui_component/category_form.xml`:
```xml
<field name="color_picker_test">
    <argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="component" xsi:type="string">Magento_Ui/js/form/element/color-picker</item>
            <item name="template" xsi:type="string">ui/form/field</item>
            <item name="elementTmpl" xsi:type="string">ui/form/element/color-picker</item>
            <item name="label" xsi:type="string">Background Color (hex)</item>
            <item name="labelVisible" xsi:type="boolean">true</item>
            <item name="visible" xsi:type="boolean">true</item>
            <item name="dataType" xsi:type="string">text</item>
            <item name="formElement" xsi:type="string">input</item>
            <item name="source" xsi:type="string">category_form</item>
        </item>
    </argument>
</field>

```
and test it in category edit form.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-28 07:31 UTC, rogyar commented
@magento run all tests

2020-05-29 07:40 UTC, krzksz commented
@magento run all tests

2020-05-30 16:34 UTC, krzksz commented
@magento run Static Tests,Unit Tests

2020-05-30 17:41 UTC, krzksz commented
@magento run Static Tests,Unit Tests

2020-05-30 18:16 UTC, krzksz commented
@magento run all tests

2020-06-01 15:09 UTC, danmooney2 submitted a review, later dismissed

2020-06-02 11:55 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

1. Verify that **spectrum.js** and **tinycolor.js** are no longer loaded by default.

**Before:**   :heavy_multiplication_x: `spectrum.js `and `tinycolor.js` are loaded by default

![Screenshot from 2020-06-02 13-33-08](https://user-images.githubusercontent.com/51679138/83516551-f13a1800-a4df-11ea-8d0c-e6a8e7306aed.png)

**After:** :heavy_check_mark: `spectrum.js` and `tinycolor.js` are no longer loaded by default.

![Screenshot from 2020-06-02 13-52-16](https://user-images.githubusercontent.com/51679138/83516748-5261eb80-a4e0-11ea-9981-295a1ed1854c.png)

2. Verify that the above modules are loaded and color picker works as expected when used.

For example add:

```xml
<field name="color_picker_test">
    <argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="component" xsi:type="string">Magento_Ui/js/form/element/color-picker</item>
            <item name="template" xsi:type="string">ui/form/field</item>
            <item name="elementTmpl" xsi:type="string">ui/form/element/color-picker</item>
            <item name="label" xsi:type="string">Background Color (hex)</item>
            <item name="labelVisible" xsi:type="boolean">true</item>
            <item name="visible" xsi:type="boolean">true</item>
            <item name="dataType" xsi:type="string">text</item>
            <item name="formElement" xsi:type="string">input</item>
            <item name="source" xsi:type="string">category_form</item>
        </item>
    </argument>
</field>

```

 to `app/code/Magento/Catalog/view/adminhtml/ui_component/category_form.xml`

Go to `Admin->Catalog->Categories`

**Actual Result:** :heavy_check_mark: Modules are loaded and color picker works as expected

![Peek 2020-06-02 14-38](https://user-images.githubusercontent.com/51679138/83517127-03688600-a4e1-11ea-9b52-f39ecc0df5cb.gif)

2020-06-02 16:00 UTC, slavvka requested changes
@krzksz All JS Unit tests are failing here with exit code 90 for all editions:
```
07:21:14 Running "spec" task
07:21:14 
07:21:14 Running "connect:blank" (connect) task
07:21:14 (node:7) ExperimentalWarning: The http2 module is an experimental API.
07:21:14 Started connect web server on http://localhost:8000
07:21:14 
07:21:14 Running "jasmine:blank" (jasmine) task
07:21:15 Testing Jasmine specs via PhantomJS
07:21:15 
07:21:16 
07:21:16 log: JQMIGRATE: Migrate is installed with logging active, version 1.4.1
07:21:17 
07:21:17 log: Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site.
07:21:18  mage/requirejs/statistician
07:21:18    "collect" method
07:21:22      - merges passed object's keys with array under localStorage's "all" namespace......✓
07:21:27      - removes duplicated entries......✓
07:21:27    "utilize" method
07:21:27      - stores passed string to array under localStorage's "used" namespace......✓
07:21:27      - removes duplicated entries......✓
07:21:27    "getAll" method
07:21:27      - returns JSON.parsed content of localStorage's "all" namespace......✓
07:21:27    "getUsed" method
07:21:27      - returns JSON.parsed content of localStorage's "used" namespace......✓
07:21:27    "getUnused" method
07:21:27      - compares results of getAll and getUsed methods and returns the difference......✓
07:21:27    "clear" method
07:21:28      - clears "used" and "all" namespaces of localStorage......✓
07:21:28  mage/template
07:21:28    - compiles template function when only selector is passed......✓
07:21:28    - renders template when both selector and data are passed......✓
07:21:28    - compiles template with string passed only......✓
07:21:29    - renders template with string and data passed......✓
07:21:29  extended text module
07:21:29    - exports reference to the module......✓
07:21:29    - caches original load method......✓
07:21:34    - loads external files......X
07:21:34      Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. (1)
07:21:39    - loads internal files......X
07:21:39      Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. (1)
07:21:39  jsbuild module
07:21:40    - caches original load method......✓
07:21:45    - loads external files......X
07:21:45      Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. (1)
07:21:50    - loads internal files......X
07:21:50      Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. (1)
07:21:50  mixins module
07:22:00    - does not affect modules without mixins...
07:22:00 Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.
07:22:00 
07:22:00 Aborted due to warnings.
07:22:00 
07:22:00 
07:22:00 Execution Time (2020-06-02 05:21:13 UTC-7)
07:22:00 spec           716ms  ▇ 2%
07:22:00 jasmine:blank  45.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
07:22:00 Total 46.3s
07:22:00 
```

2020-06-02 16:01 UTC, slavvka commented
@magento create issue

2020-06-03 08:53 UTC, engcom-Echo commented
@magento run all tests

2020-06-04 13:52 UTC, engcom-Echo commented
@magento run all tests

2020-06-26 12:43 UTC, engcom-Echo commented
@magento run all tests

2020-08-05 15:36 UTC, engcom-Echo commented
@magento run all tests

2020-08-07 08:44 UTC, engcom-Echo commented
@magento run all tests

2020-08-07 14:17 UTC, engcom-Echo commented
@magento run all tests

2020-08-18 19:41 UTC, sidolov commented
@magento create issue

2020-08-19 17:32 UTC, sidolov submitted a review, later dismissed
QA note: please, make sure JS bundling and minification works as expected after the fix.

2020-08-19 17:33 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8035](https://jira.corp.magento.com/browse/ENGCOM-8035) has been created to process this Pull Request

2020-09-02 10:56 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

1. Verify that **spectrum.js** and **tinycolor.js** are no longer loaded by default.

**Before:**   :heavy_multiplication_x: `spectrum.js `and `tinycolor.js` are loaded by default

![2020-09-02_12-33](https://user-images.githubusercontent.com/51679138/91972816-e469d200-ed23-11ea-8f51-e296db573571.png)

**After:** :heavy_check_mark: `spectrum.js` and `tinycolor.js` are no longer loaded by default.

![Screenshot from 2020-06-02 13-52-16](https://user-images.githubusercontent.com/51679138/83516748-5261eb80-a4e0-11ea-9981-295a1ed1854c.png)

2. Verify that the above modules are loaded and color picker works as expected when used.

For example add:

```xml
<field name="color_picker_test">
    <argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="component" xsi:type="string">Magento_Ui/js/form/element/color-picker</item>
            <item name="template" xsi:type="string">ui/form/field</item>
            <item name="elementTmpl" xsi:type="string">ui/form/element/color-picker</item>
            <item name="label" xsi:type="string">Background Color (hex)</item>
            <item name="labelVisible" xsi:type="boolean">true</item>
            <item name="visible" xsi:type="boolean">true</item>
            <item name="dataType" xsi:type="string">text</item>
            <item name="formElement" xsi:type="string">input</item>
            <item name="source" xsi:type="string">category_form</item>
        </item>
    </argument>
</field>

```

 to `app/code/Magento/Catalog/view/adminhtml/ui_component/category_form.xml`

Go to `Admin->Catalog->Categories`

**Actual Result:** :heavy_check_mark: Modules are loaded and color picker works as expected

![Screenshot from 2020-09-02 12-46-55](https://user-images.githubusercontent.com/51679138/91972906-07948180-ed24-11ea-83af-2b4c65c741e4.png)

and **JS bundling** and **minification** works as expected 

![2020-09-02_13-26](https://user-images.githubusercontent.com/51679138/91972987-2561e680-ed24-11ea-97f6-4184a2162bd9.png)

2020-09-03 14:05 UTC, engcom-Echo commented
Hi @krzksz. Please, look at failed tests. I think it has to do with a change.

2020-09-09 15:22 UTC, krzksz commented
@magento run Functional Tests B2B,Functional Tests EE

2020-09-13 12:14 UTC, rogyar commented
Hi @krzksz. Could you take a look at the failing functional tests, please? It looks like there are some issues with the color picker for Page Builder.

Thank you!

2020-10-08 12:11 UTC, engcom-Foxtrot commented
@krzksz can you please check Page Builder test failures? You can reproduce it by inserting code:
`<field name="enable_test" sortOrder="1" formElement="select">
            <settings>
                <dataType>text</dataType>
                <label translate="true">Background Color (hex) Enabler</label>
            </settings>
            <formElements>
                <select>
                    <settings>
                        <options>
                            <option name="0" xsi:type="array">
                                <item name="value" xsi:type="string">Enabled</item>
                                <item name="label" xsi:type="string" translate="true">Enabled</item>
                            </option>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string">Disabled</item>
                                <item name="label" xsi:type="string" translate="true">Disabled</item>
                            </option>
                        </options>
                    </settings>
                </select>
            </formElements>
        </field>

        <field name="color_picker_test" sortOrder="2">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="component" xsi:type="string">Magento_Ui/js/form/element/color-picker</item>
                    <item name="template" xsi:type="string">ui/form/field</item>
                    <item name="elementTmpl" xsi:type="string">ui/form/element/color-picker</item>
                    <item name="label" xsi:type="string">Background Color (hex)</item>
                    <item name="labelVisible" xsi:type="boolean">true</item>
                    <item name="visible" xsi:type="boolean">true</item>
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="source" xsi:type="string">category_form</item>
                    <item name="disabledValues" xsi:type="array">
                        <item name="Disabled" xsi:type="string">Disabled</item>
                    </item>
                </item>
            </argument>
            <settings>
                <imports>
                    <link name="setDisabled">ns = ${ $.ns }, index = enable_test:value</link>
                </imports>
            </settings>
        </field>`

2020-10-08 12:16 UTC, engcom-Foxtrot requested changes
@krzksz can you please check Page Builder test failures? You can reproduce it by inserting code:
```xml
        <field name="enable_test" sortOrder="1" formElement="select">
            <settings>
                <dataType>text</dataType>
                <label translate="true">Background Color (hex) Enabler</label>
            </settings>
            <formElements>
                <select>
                    <settings>
                        <options>
                            <option name="0" xsi:type="array">
                                <item name="value" xsi:type="string">Enabled</item>
                                <item name="label" xsi:type="string" translate="true">Enabled</item>
                            </option>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string">Disabled</item>
                                <item name="label" xsi:type="string" translate="true">Disabled</item>
                            </option>
                        </options>
                    </settings>
                </select>
            </formElements>
        </field>
        <field name="color_picker_test" sortOrder="2">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="component" xsi:type="string">Magento_Ui/js/form/element/color-picker</item>
                    <item name="template" xsi:type="string">ui/form/field</item>
                    <item name="elementTmpl" xsi:type="string">ui/form/element/color-picker</item>
                    <item name="label" xsi:type="string">Background Color (hex)</item>
                    <item name="labelVisible" xsi:type="boolean">true</item>
                    <item name="visible" xsi:type="boolean">true</item>
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="source" xsi:type="string">category_form</item>
                    <item name="disabledValues" xsi:type="array">
                        <item name="Disabled" xsi:type="string">Disabled</item>
                    </item>
                </item>
            </argument>
            <settings>
                <imports>
                    <link name="setDisabled">ns = ${ $.ns }, index = enable_test:value</link>
                </imports>
            </settings>
        </field>
```

2020-11-19 09:16 UTC, engcom-Hotel commented
@magento run all tests

2020-11-19 16:14 UTC, engcom-Hotel commented
@magento run all tests

2020-11-23 07:27 UTC, engcom-Hotel commented
@magento run all tests

2020-11-23 14:53 UTC, engcom-Hotel commented
Will check tests.

2020-11-26 10:40 UTC, engcom-Hotel commented
@magento run all tests

2020-11-26 13:01 UTC, engcom-Hotel commented
@magento run all tests

2020-11-27 07:39 UTC, engcom-Hotel commented
@magento run all tests

2020-11-27 10:47 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-01-29 08:10 UTC, engcom-Hotel commented
@magento run Semantic Version Checker

2021-01-29 08:33 UTC, engcom-Hotel commented
@magento run Semantic Version Checker

2021-01-29 08:34 UTC, engcom-Hotel commented
@magento run all tests

2021-01-29 08:43 UTC, engcom-Hotel commented
@magento run all tests

2021-01-29 09:58 UTC, engcom-Hotel commented
@magento run all tests

2021-01-29 12:36 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE

2021-01-29 14:19 UTC, engcom-Hotel commented
@magento run all tests

2021-01-31 02:36 UTC, mrtuvn commented
@magento run Functional Tests EE, Functional Tests B2B

2021-02-01 09:42 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Functional Tests B2B

2021-02-01 10:30 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Functional Tests B2B

2021-02-01 12:32 UTC, engcom-Hotel commented
@magento run all tests

2021-02-01 14:35 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-01 16:09 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-02 07:20 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-02 08:04 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-02 14:27 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-15 14:50 UTC, ptylek approved these changes

2021-02-15 14:50 UTC, ptylek commented
@engcom-Foxtrot Hey, can we proceed here?

2021-02-15 14:51 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-8035](https://jira.corp.magento.com/browse/ENGCOM-8035) has been created to process this Pull Request

2021-02-16 09:34 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

1. Verify that **spectrum.js** and **tinycolor.js** are no longer loaded by default.

**Before:**   :heavy_multiplication_x: `spectrum.js `and `tinycolor.js` are loaded by default

![2020-09-02_12-33](https://user-images.githubusercontent.com/51679138/91972816-e469d200-ed23-11ea-8f51-e296db573571.png)

**After:** :heavy_check_mark: `spectrum.js` and `tinycolor.js` are no longer loaded by default.

![Screenshot from 2020-06-02 13-52-16](https://user-images.githubusercontent.com/51679138/83516748-5261eb80-a4e0-11ea-9981-295a1ed1854c.png)

2. Verify that the above modules are loaded and color picker works as expected when used.

For example add:

```xml
<field name="color_picker_test">
    <argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="component" xsi:type="string">Magento_Ui/js/form/element/color-picker</item>
            <item name="template" xsi:type="string">ui/form/field</item>
            <item name="elementTmpl" xsi:type="string">ui/form/element/color-picker</item>
            <item name="label" xsi:type="string">Background Color (hex)</item>
            <item name="labelVisible" xsi:type="boolean">true</item>
            <item name="visible" xsi:type="boolean">true</item>
            <item name="dataType" xsi:type="string">text</item>
            <item name="formElement" xsi:type="string">input</item>
            <item name="source" xsi:type="string">category_form</item>
        </item>
    </argument>
</field>

```

 to `app/code/Magento/Catalog/view/adminhtml/ui_component/category_form.xml`

Go to `Admin->Catalog->Categories`

**Actual Result:** :heavy_check_mark: Modules are loaded and color picker works as expected

![Screenshot from 2020-09-02 12-46-55](https://user-images.githubusercontent.com/51679138/91972906-07948180-ed24-11ea-83af-2b4c65c741e4.png)

and **JS bundling** and **minification** works as expected 

![Screenshot from 2021-02-16 11-32-16](https://user-images.githubusercontent.com/51679138/108044372-da762a00-704a-11eb-9d04-00013e772117.png)

2021-02-22 12:15 UTC, gabrieldagama commented
@magento run all tests

2021-02-23 08:05 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE

2021-02-25 10:05 UTC, gabrieldagama commented
@magento give me test instance with edition b2b

2021-02-25 12:02 UTC, engcom-Alfa requested changes
Hi @krzksz .
During testing, we faced the issue.
 
**_Precondition:_**
Magento 2.4 with Page Builder.

**Manual testing scenario:**
1. Go to **_Admin -> Content -> Pages_** and open any page for edit;
2. Expand the **_Content_** tab and click on the **Edit with Page Builder** button;
3. Add **_Row_** layout and **_Banner_** element for example;
4. Click on the Edit button;
5. Expand the **_Background_** tab and select any colour;
6. Now change the color again by inserting the value into the color picker.

**Actual Result:** :heavy_multiplication_x: The color was not automatically changed in the two fields

![Peek 2021-02-25 13-40](https://user-images.githubusercontent.com/51679138/109150528-a9e06f80-7771-11eb-9988-d360c3a23997.gif)

If  you press the Enter button the fields get the same values.

**Actual Result without PR changes:** :heavy_check_mark: The color automatically changed in the two fields

![Peek 2021-02-25 13-43](https://user-images.githubusercontent.com/51679138/109150718-ee6c0b00-7771-11eb-83c1-83a0cffdc811.gif)

@krzksz  Could you take a look?
Thanks!

2021-02-26 15:21 UTC, engcom-Hotel commented
Not sure that it is an issue. It is even more logical that until applying a new value the old value still old.
Probably need to discuss it with the PO.

2021-03-13 13:32 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE,

2021-03-15 01:38 UTC, Leland commented
Any chance of this getting a merge? We're approaching the PR's year anniversary 😬

2021-03-15 02:37 UTC, mrtuvn commented
Seem owner of PR really busy right now. Some regression problem is other reason of this blocker

2021-03-15 05:06 UTC, mrtuvn commented
Failed test
app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreatePartialInvoiceForOrderWithVirtualProductOnCustomStockTest.xml

Broken test app/code/Magento/PageBuilder/Test/Mftf/Test/AdminPageBuilderCommonTest/EditPanelColorPickerUpdatesFromFieldInputTest.xml

2021-03-18 11:54 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE,

2021-03-30 17:14 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-04-10 04:20 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-04-21 11:36 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-04-23 13:43 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-04-23 21:59 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-04-23 21:59 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-04-27 12:04 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-16 02:16 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-07-02 01:41 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-07-13 16:43 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2021-07-13 17:16 UTC, mrtuvn commented
Hi @krzksz can you rebase branch to current recently code

2021-07-14 07:53 UTC, krzksz commented
@magento run Functional Tests B2B, Functional Tests EE

2021-07-14 13:31 UTC, mrtuvn commented
@magento run all tests

2021-07-15 01:40 UTC, mrtuvn commented
magento run Static Tests, Semantic Version Checker, Sample Data Tests EE, Sample Data Tests B2B, Integration Tests, Functional Tests EE, Functional Tests B2B

2021-07-15 08:53 UTC, mrtuvn commented
@magento run Static Tests, Functional Tests EE, Integration Tests

2021-07-15 13:30 UTC, mrtuvn commented
Look like static fails come from pagebuilder module
Other fails not related with this change
CC: @gabrieldagama . I found some broken related wysiwyg tinymce4

2021-07-20 05:02 UTC, mrtuvn commented
@magento run all tests

2021-07-20 07:58 UTC, mrtuvn commented
@magento run Semantic Version Checker, Sample Data Tests EE, Sample Data Tests B2B
cc: @gabrieldagama seem some broken/fails test come from page builder module

2021-07-29 11:41 UTC, mrtuvn commented
@magento run Static Tests, Functional Tests CE

2021-08-04 13:41 UTC, mrtuvn commented
@magento run Integration Tests

2021-08-04 16:14 UTC, mrtuvn commented
@magento run all tests

2021-08-06 06:28 UTC, mrtuvn commented
@magento run Static Tests, Functional Tests EE, Integration Tests, Functional Tests B2B, Sample Data Tests EE, Sample Data Tests B2B, Semantic Version Checker

2021-08-06 07:14 UTC, mrtuvn commented
@krzksz can you rebase your branch ?

2021-09-19 04:50 UTC, mrtuvn commented
@magento run Static Tests, Functional Tests EE

2021-11-17 06:35 UTC, engcom-Charlie commented
@magento run all tests

2021-11-17 14:15 UTC, Leland commented
I'm excited for this PR to hit its 2 year anniversary <3

2021-11-17 14:30 UTC, mrtuvn commented
krz no longer working on this. So i think this pull request will inactive for a while

2021-11-18 06:38 UTC, engcom-Charlie commented
@magento run all tests

2021-11-18 06:40 UTC, engcom-Charlie commented
Hi @krzksz 

Thank you for your contribution!

I am looking into the build failure.

Thank you!

2021-11-25 09:04 UTC, engcom-Charlie commented
@magento run all tests

2021-11-30 10:07 UTC, engcom-Charlie commented
Currently not looking into this PR as I am in between some other priority tasks. Will resume work on this once done with current work.

2021-12-16 08:04 UTC, engcom-Charlie commented
@magento run all tests

2021-12-21 07:39 UTC, engcom-Charlie commented
@magento run all tests

2022-03-23 14:30 UTC, engcom-Charlie commented
@magento run all tests

2022-03-23 14:30 UTC, engcom-Charlie commented
@magento run all tests

2022-03-29 13:09 UTC, engcom-Charlie commented
@magento run all tests

2022-03-30 12:37 UTC, engcom-Charlie commented
@magento run all tests

2022-04-08 09:12 UTC, engcom-Charlie commented
As the build failure is showing errors in few outdated files after merging latest code too, closing this PR. All the code committed in this PR is covered in https://github.com/magento/magento2/pull/34142 PR.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51680850/162387336-9f7886c8-74e9-43b4-8c0e-14339bd88bb8.png">

Thank you!

2022-04-08 09:12 UTC, closed without merging