Validation added in dynamic rows when pages changed
magento/magento2 pull request #28412
Opened 2020-05-28 16:48 UTC by Mohamed-Asar

### Description (*)
Dynamic rows validate only the current page input elements. it does n't validate all the page's inputs.
I Restricted the user to fill all the inputs before changing pages

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28397

### Manual testing scenarios (*)

1. Go to product edit page & click advanced pricing.
2. In customer group price dynamic rows, add 20 rows, don't fill one or more required input fields
3. click add button it does n't allow to go next page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-29 05:24 UTC, Mohamed-Asar commented
@magento run all tests

2020-05-31 12:42 UTC, Mohamed-Asar commented
@magento run Static Tests, Integration Tests, Functional Tests EE, Functional Tests B2B

2020-08-19 11:09 UTC, VladimirZaets requested changes
Hi @Mohamed-Asar. Thanks for collaboration. Please take a look at my review comments

2020-08-19 11:09 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows.js
> +                } else {
You don't need `else` statement if you need just move out of the function. Please remove else statement.

2020-08-19 11:09 UTC, VladimirZaets commented on app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows.js
> +            if (typeof elem === 'undefined') {
Please use underscore library to check the type of elements

2020-08-23 11:46 UTC, Mohamed-Asar commented
@VladimirZaets made those changes. please review

2020-08-24 10:18 UTC, Mohamed-Asar commented
@magento run all tests

2020-09-02 20:22 UTC, sidolov submitted a review, later dismissed

2020-09-02 20:23 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8125](https://jira.corp.magento.com/browse/ENGCOM-8125) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-04 13:49 UTC, engcom-Alfa requested changes
Hi @Mohamed-Asar .
Could you cover the changes with auto tests?

Thanks!

2020-09-07 14:42 UTC, gabrieldagama commented
The risk was set to`medium` due to: the suggested changes may affect other modules that use dynamic-rows.

2020-09-23 09:40 UTC, engcom-Golf commented
Hi @Mohamed-Asar. 
Thank you for your collaboration.
Could you please address static build failures and consider covering expected behavior with an auto test?

2020-09-23 18:00 UTC, sidolov commented
@Mohamed-Asar  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-23 18:00 UTC, closed without merging