Fix Downloadable product after refund
magento/magento2 pull request #28413
Opened 2020-05-28 17:48 UTC by ProkopovVitaliy

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28388. Downloadable product is available in My Download Products tab after it has been partially refunded

### Manual testing scenarios (*)

1. Create order with a download product and a product, requiring shipping, (e.g. simple product) is created.
2. The downloadable product is available in My Downloadable Products tab.
3. Open this order page in Admin.
4. Perform a partial refund for the downloadable product (the other product is not refunded).
5. Go to My Downloadable Products tab.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-05-28 17:50 UTC, ProkopovVitaliy commented
@magento run all tests

2020-05-29 06:02 UTC, ProkopovVitaliy commented
@magento run all tests

2020-06-03 16:39 UTC, VladimirZaets requested changes
Hi @ProkopovVitaliy. Thanks for collaboration. Can you please fix failed tests? Also, can you please cover this functionality by functional or integration tests?

2020-06-09 14:19 UTC, engcom-Kilo commented
@magento run all tests

2020-06-09 18:28 UTC, ProkopovVitaliy commented
@magento run Functional Tests EE

2020-06-10 07:47 UTC, engcom-Kilo commented
Working with MFTF test.

2020-06-10 13:07 UTC, engcom-Kilo commented
@magento run all tests

2020-06-10 16:19 UTC, ProkopovVitaliy commented
@magento run Unit Tests

2020-06-10 16:20 UTC, ProkopovVitaliy commented
@magento run Functional Tests B2B

2020-06-12 21:32 UTC, VladimirZaets approved these changes

2020-06-12 21:33 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7679](https://jira.corp.magento.com/browse/ENGCOM-7679) has been created to process this Pull Request

2020-06-16 10:56 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Has a Simple product;
2. Has a Downloadable product;
3. Has a customer in Storefront;

**Manual testing scenario:**

1. Create order with a download product and a product, requiring shipping, (e.g. simple product) is created;
2. Create a full invoice for the order;
3. Go to Storefront-> My Account -> My Downloadable Products 

**Actual Result:** :heavy_check_mark: The downloadable product can be downloaded.

![screenshot_66](https://user-images.githubusercontent.com/51679138/84765642-35e1ab00-afd8-11ea-8c77-3cad062c9d08.png)
 
4. Perform a partial refund (credit memo) for the downloadable product (the other product is not refunded).

![Screenshot from 2020-06-16 13-27-21](https://user-images.githubusercontent.com/51679138/84765744-56aa0080-afd8-11ea-8508-4953391258a4.png)

5. Go to Storefront-> My Account -> My Downloadable Products again

**Before:** :heavy_multiplication_x: After a refund, the Downloadable product still can be downloaded.

![screenshot_65](https://user-images.githubusercontent.com/51679138/84765900-98d34200-afd8-11ea-803f-4bd6bfc82597.png)

**After:** :heavy_check_mark:  The Downloadable product cannot be downloaded.

![Screenshot from 2020-06-16 13-27-39](https://user-images.githubusercontent.com/51679138/84765972-b7393d80-afd8-11ea-9293-16cc20152173.png)

Also tested with different stores, combinations with different types of products

2020-06-16 11:22 UTC, engcom-Kilo commented
@magento run all tests

2020-06-16 14:09 UTC, engcom-Kilo commented
Failed Functional Tests EE not related to the changes in this PR

2020-06-24 01:19 UTC, slavvka commented
@magento run all tests

2020-06-24 05:14 UTC, ProkopovVitaliy commented
@magento run Functional Tests B2B

2020-06-24 16:09 UTC, slavvka commented
@magento run all tests

2020-06-24 18:28 UTC, slavvka requested changes
@ProkopovVitaliy @engcom-Kilo @engcom-Alfa Guys, please take a close look at failing MFTF tests since they are failing when trying to deliver almost constantly. Something in the changes seems to make them more flaky

2020-06-25 10:08 UTC, engcom-Kilo commented
@magento run all tests

2020-06-26 12:56 UTC, engcom-Kilo commented
@magento run Functional Tests B2B

2020-07-03 08:09 UTC, engcom-Kilo commented
@magento run Functional Tests B2B

2020-07-03 10:05 UTC, engcom-Kilo commented
@magento run all tests

2020-07-22 11:04 UTC, engcom-Kilo commented
@magento run all tests

2020-08-03 13:15 UTC, engcom-Kilo commented
@magento run all tests

2020-08-10 07:50 UTC, engcom-Kilo commented
@magento run all tests

2020-08-14 13:56 UTC, engcom-Kilo commented
@magento run Functional Tests CE

2020-08-14 13:57 UTC, engcom-Kilo commented
@magento run Functional Tests B2B

2020-08-15 08:49 UTC, engcom-Kilo commented
@magento run all tests

2020-08-21 19:46 UTC, sidolov approved these changes

2020-08-21 19:46 UTC, sidolov commented on app/code/Magento/Downloadable/Test/Unit/Observer/SetLinkStatusObserverTest.php
> +        $this->itemsFactory->expects($this->any())
It's better to use atLeastOnce instead.

2020-08-21 19:46 UTC, sidolov commented on app/code/Magento/Downloadable/Test/Unit/Observer/SetLinkStatusObserverTest.php
> +        $linkItemCollection->expects($this->any())
It's better to use atLeastOnce instead.

2020-08-21 19:47 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-7679](https://jira.corp.magento.com/browse/ENGCOM-7679) has been created to process this Pull Request

2020-08-31 08:19 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Has a Simple product;
2. Has a Downloadable product;
3. Has a customer in Storefront;

**Manual testing scenario:**

1. Create order with a download product and a product, requiring shipping, (e.g. simple product) is created;
2. Create a full invoice for the order;
 
3. Perform a partial refund (credit memo) for the downloadable product (the other product is not refunded).

![Screenshot from 2020-06-16 13-27-21](https://user-images.githubusercontent.com/51679138/84765744-56aa0080-afd8-11ea-8508-4953391258a4.png)

4. Go to Storefront-> My Account -> My Downloadable Products again

**Before:** :heavy_multiplication_x: After a refund, the Downloadable product still can be downloaded.

![123](https://user-images.githubusercontent.com/51679138/91698615-aa5dcc00-eb7b-11ea-81d4-062f55e2b531.png)

**After:** :heavy_check_mark:  The Downloadable product cannot be downloaded.

![2020-08-31_10-30](https://user-images.githubusercontent.com/51679138/91698635-b184da00-eb7b-11ea-92f4-6d15a232196e.png)

Also tested with different stores, combinations with different types of products

2020-09-02 17:08 UTC, merged