MFTF: Refactoring admin url rewrite multiple storeviews product import with config turned off test
magento/magento2 pull request #28457
Opened 2020-06-01 11:22 UTC by kate-kyzyma

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)
AdminUrlRewriteMultipleStoreviewsProductImportWithConfigTurnedOffTest is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run AdminUrlRewriteMultipleStoreviewsProductImportWithConfigTurnedOffTest in the local environment and verified the test runs successfully.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-01 11:24 UTC, dmytro-ch commented
@magento run all tests

2020-06-07 22:53 UTC, lbajsarowicz commented on app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminChangeCategoryNameOnStoreViewLevelActionGroup.xml
> +        <uncheckOption selector="{{AdminCategoryBasicFieldSection.categoryNameUseDefault}}" stepKey="uncheckUseDefaultValueENStoreView"/>
`stepKey` contains misleading information about the store view which is not actually the case in scope of the ActionGroup : )

2020-06-09 06:39 UTC, kate-kyzyma commented
Hi @lbajsarowicz 
Thanks for reviewing my test. I have fixed the issue.

2020-06-11 08:30 UTC, kate-kyzyma commented
@magento run all tests

2020-06-11 10:16 UTC, lbajsarowicz submitted a review, later dismissed
:heavy_check_mark: Great job!

2020-06-11 10:17 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7666](https://jira.corp.magento.com/browse/ENGCOM-7666) has been created to process this Pull Request

2020-06-16 07:44 UTC, engcom-Alfa requested changes
Hi @kate-kyzyma . Could you resolve merge conflicts? 
Thanks!

2020-06-16 11:10 UTC, kate-kyzyma commented
Hi @engcom-Alfa 
I have resolved the merge conflict.

Thanks.

2020-06-16 14:03 UTC, lbajsarowicz approved these changes
:heavy_check_mark: Great job, thank you for your contribution.

2020-06-16 14:04 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7666](https://jira.corp.magento.com/browse/ENGCOM-7666) has been created to process this Pull Request

2020-06-17 07:38 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-06-17 07:42 UTC, engcom-Charlie commented
@magento run all tests

2020-06-19 05:22 UTC, merged