Fix setup upgrade command re enables caches
magento/magento2 pull request #28491
Opened 2020-06-03 13:34 UTC by AbdulRahmanAbouzaid

### Description (*)

Fix re-enables all frontend caches after running setup:upgrade command including the disabled one BY Return them back to their old state before running setup:upgrade.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28186

### Manual testing scenarios (*)

1.Disable one of/all frontend caches [ layout, block_html and full_page] (for example: run `bin/magento cache:disable layout`).
2. run `bin/magento setup:uprade`.
3. Run `bin/magento cache:status` and you can find that layout cache disabled.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-03 13:38 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-06-04 11:12 UTC, AbdulRahmanAbouzaid commented
@magento run Unit Tests, WebAPI Tests, Sample Data Tests EE, Sample Data Tests B2B, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-06-04 12:07 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-06-04 14:12 UTC, AbdulRahmanAbouzaid commented
@magento run Static Tests

2020-06-04 14:43 UTC, AbdulRahmanAbouzaid commented
@magento run Integration Tests

2020-06-05 18:00 UTC, AbdulRahmanAbouzaid commented
@magento run Functional Tests B2B

2020-07-09 08:50 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-19 11:03 UTC, VladimirZaets commented
@magento run all tests

2020-08-19 11:03 UTC, VladimirZaets approved these changes

2020-08-19 11:04 UTC, magento-engcom-team commented
Hi @VladimirZaets, thank you for the review.
[ENGCOM-8029](https://jira.corp.magento.com/browse/ENGCOM-8029) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-08-19 11:11 UTC, engcom-Alfa commented
@VladimirZaets Could you put an appropriate label for test coverage?

2020-08-26 12:02 UTC, ihor-sviziev commented
@engcom-Alfa I believe it requires automatic test, but not sure how to test CLI commands correctly

2020-08-27 09:36 UTC, ihor-sviziev requested changes

2020-08-27 09:36 UTC, ihor-sviziev commented on setup/src/Magento/Setup/Model/Installer.php
> +        }
It seems to me really bad to enable caches and disable them again. I think it's better to calculate what caches need to be re-enabled, and enable only needed

2020-08-27 09:37 UTC, ihor-sviziev commented
@AbdulRahmanAbouzaid could you also cover your changes with some kind of test?

2020-08-27 10:19 UTC, ihor-sviziev commented
@magento run all tests

2020-08-27 10:30 UTC, ihor-sviziev commented
@magento run all tests

2020-08-27 10:32 UTC, ihor-sviziev commented on setup/src/Magento/Setup/Model/Installer.php
> +        }
Just fixed it myself

2020-08-27 11:21 UTC, ihor-sviziev commented
@magento run all tests

2020-08-27 13:36 UTC, AbdulRahmanAbouzaid commented
@ihor-sviziev thanks for your updates. Is there any other changes should be made?

2020-08-27 13:39 UTC, ihor-sviziev requested changes
Hi @AbdulRahmanAbouzaid,
Could you cover your changes with any type of automated tests in order to prevent appearing this issue in future?

2020-08-27 14:02 UTC, AbdulRahmanAbouzaid commented
@ihor-sviziev I'll check this

2020-09-02 18:54 UTC, engcom-Charlie commented
Hi @AbdulRahmanAbouzaid, do you have any updates about test coverage?
Thank you.

2020-09-07 12:53 UTC, gabrieldagama commented
The risk was set to `medium` due to: the suggested changes may affect a critical area.

2020-09-08 07:24 UTC, engcom-Charlie commented
@AbdulRahmanAbouzaid I'll try to continue with your PR.

2020-09-10 14:58 UTC, AbdulRahmanAbouzaid commented
@engcom-Charlie Thank you. 
Sorry for the late reply. I tried to cover this with test but i couldn't

2020-09-16 08:47 UTC, engcom-Charlie commented
@magento run all tests

2020-09-16 13:02 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2020-09-16 13:03 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8029](https://jira.corp.magento.com/browse/ENGCOM-8029) has been created to process this Pull Request

2020-09-17 12:19 UTC, ihor-sviziev commented
@magento run all tests

2020-09-23 13:57 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

The cache status has not been changed after performing Upgrade

### Manual testing scenario
1. Disable _block_html_ _full_page_ _layout_ using the following command
```bin/magento cache:disable block_html full_page layout```
2. Run ```bin/magento cache:status``` and assert that following are set to _0_
```layout: 0```
```block_html: 0```
```full_page: 0 ```
3. Upgrade magento instance using ```bin/magento setup:upgrade```
4. Check the cache status using  ```bin/magento cache:status```

### Actual Result
The previously disabled caches are still in _Disabled_ status (0)
```
Current status:
                        config: 1
                        layout: 0
                    block_html: 0
                   collections: 1
                    reflection: 1
                        db_ddl: 1
               compiled_config: 1
                           eav: 1
         customer_notification: 1
            config_integration: 1
        config_integration_api: 1
                     full_page: 0
             config_webservice: 1
                     translate: 1
```
### Before switching to PR 
```
Current status:
                        config: 1
                        layout: 1
                    block_html: 1
                   collections: 1
                    reflection: 1
                        db_ddl: 1
               compiled_config: 1
                           eav: 1
         customer_notification: 1
            config_integration: 1
        config_integration_api: 1
                     full_page: 1
             config_webservice: 1
                     translate: 1
```

2020-09-24 00:58 UTC, merged