Rewrote Magento\Framework\DB\Adapter\Pdo\Mysql->isTableExists
magento/magento2 pull request #28516
Opened 2020-06-04 15:42 UTC by jonashrem

### Description (*)
During heavier load on newer productive Magento2 installations (2.3 with MSI or 2.3.4+), we noticed increased execution time was spent in `SHOW TABLE STATUS` queries to MySQL. Analyzing this further, we found that these queries seemed to occur in higher frequency than in earlier Magento versions. This can be problematic, since the MySQL server uses an exclusive file system lock and a call to readdir() to answer them. Because of this, these calls can be slow. We also found that one web request can result in multiple calls of `SHOW TABLE STATUS` for the same tables, which seems very wasteful and inefficient.

In more detailed analysis of some of our customers, we found instances where `SHOW TABLE STATUS` queries were executed nearly 100 times when requesting a single category page with 48 products.

Looking at the code of the MySQL adapter, we identified several places that use the function `showTablesStatus()`, among them `isTableExists()`.
With this patch, we eliminate the calls of `SHOW TABLE STATUS` for the common case of checking table existence.

#### Implementation details
In our implementation of `isTableExists()`, we use information from the INFORMATION_SCHEMA.TABLES table, which is provided without expensive file system operations and proved to be significantly faster in our tests (see below for details). Additionally, we use the already existing DDL cache to store a positive table existence, resulting in even fewer database calls.

According to the official MySQL documentation[[link]](https://dev.mysql.com/doc/refman/5.7/en/information-schema-introduction.html), using the views from INFORMATION_SCHEMA is actually recommended over using SHOW queries, since this has some advantages. INFORMATION_SCHEMA views are read-only and respect the access rights of the database user, so it should be readily available on supported MySQL platforms.

The raw performance advantages of using INFORMATION_SCHEMA over `SHOW TABLES STATUS` can easily be measured with MySQL itself. We’ve used MySQL 5.7.30 on Ubuntu 18.04, with `datadir` running on a high performance NVME SSD (Samsung PM1725b).
We’ve run 10 concurrent clients each executing 1,000,000 statements in a Magento database with demo data, once with the query `SHOW TABLES STATUS LIKE ‘catalog_product_entity’;` and once with our statement `SELECT COUNT(1) AS tbl_exists FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = ‘catalog_product_entity’ AND TABLE_SCHEMA = DATABASE();`.

Between these queries, we measured a difference of *slightly over factor 10* in the execution time, favoring our solution with INFORMATION_SCHEMA. See below for details.
We assume the difference is even bigger when having more concurrent clients or slower hardware. As MySQL’s “SHOW TABLE STATUS” implementation is reading the whole directory, file system locking can have a stronger effect as well as which file system is used.

Our performance measurements:
- create the files test1.sql and test2.sql with 1.000.000 rows of the statements to test.
- run these commands
  - `time seq 1 10 | parallel -j 10 bash -c 'mysql < test1.sql > /dev/null’`
  - `time seq 1 10 | parallel -j 10 bash -c 'mysql < test2.sql > /dev/null’`

Results:
For `SHOW TABLE STATUS`:
```
# time seq 1 10 |  parallel  -j 10 bash -c ' mysql   < test1.sql  > /dev/null’ 

real	85m21.374s
user	3m5.500s
sys	1m40.317s
```
For `INFORMATION_SCHEMA`:
```
time seq 1 10 |  parallel  -j 10 bash -c ' mysql   < test2.sql > /dev/null 

real	8m5.184s
user	1m54.587s
sys	1m11.687s
```

### Manual testing scenarios (*)
To see the impact our patch has, load the same set of pages on the frontend with and without the patch on any Magento instance (with real or demo data). The difference can be seen when analyzing the amount of SQL queries sent to the database and the time spent processing them. Here’s an easy way to do this:

Using [Slow Query Log](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html), you can make MySQL actually log all queries by setting the threshold to 0 seconds:

```
SET @@GLOBAL.long_query_time = 0; SET @@GLOBAL.slow_query_log = 1;
```
After you’ve opened the selected set of frontend pages, deactivate it again:
```
SET @@GLOBAL.slow_query_log = 0;
```
Now, using `pt-query-digest` from the Percona Toolkit on the slow query log file, you get an analysis of the logged queries, with queries grouped by type, their average and cumulative run time, and other information. Make sure to use two different log files so that they can easily be compared between M2 with and without our patch.

In the analysis, you will usually see `SHOW TABLE STATUS` queries appearing in the top queries (this depends a bit on the module configuration and of course on which and how many pages you accessed for this test), meaning they're taking quite a good percentage of total execution time.

Please see these extracts from the `pt-query-digest` output for an example, which we created when simply opening the single category page “Men > Tops” from the demo data (`https://$BASEURL/men/tops-men.html?product_list_limit=36`).

Analysis of SQL queries run, *unpatched* Magento:
```
# Profile
# Rank Query ID                         Response time Calls R/Call V/M   I
# ==== ================================ ============= ===== ====== ===== =
#    1 0xAADD55611E492BA965AF2F067A0...  0.0099 34.3%    22 0.0004  0.00 SELECT catalog_product_index_eav search_tmp_?ed?d?dcc?b?_? cataloginventory_stock_status
#    2 0x7009A071F49236A84A57562D461...  0.0050 17.2%     1 0.0050  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price review_entity_summary review_entity cataloginventory_stock_status search_tmp_?ed?d?dccc?_?
#    3 0x8085D806F3631D0D30FE5C20326...  0.0036 12.5%     3 0.0012  0.00 SHOW TABLE STATUS
#    4 0x13262D434B03958CB4F62EC706B...  0.0011  3.9%     1 0.0011  0.00 INSERT SELECT search_tmp_?ed?d?dcc?b?_? catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#    5 0x2F9EDAB00084ED0A7EE1463DBA4...  0.0009  3.1%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
[...]
```
You can see that queries of the type `SHOW TABLE STATUS` are the third most expensive queries with 12.5% of the total execution time inside the database and 3 calls in total just for this single page load.

*Patched* Magento, opening the same category page:
```
# Profile
# Rank Query ID                         Response time Calls R/Call V/M   I
# ==== ================================ ============= ===== ====== ===== =
#    1 0xAADD55611E492BA965AF2F067A0...  0.0105 29.9%    22 0.0005  0.00 SELECT catalog_product_index_eav search_tmp_?ed?cf?f?c?a?_? cataloginventory_stock_status
#    2 0x8EA4DF263A535F59EAC6ED75B20...  0.0073 20.7%    24 0.0003  0.00 SELECT catalog_product_entity catalog_product_super_link catalog_product_website catalog_product_entity_int cataloginventory_stock_status
#    3 0x7009A071F49236A84A57562D461...  0.0050 14.2%     1 0.0050  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price review_entity_summary review_entity cataloginventory_stock_status search_tmp_?ed?cf?f?e?b?_?
#    4 0x13262D434B03958CB4F62EC706B...  0.0015  4.3%     1 0.0015  0.00 INSERT SELECT search_tmp_?ed?cf?f?c?a?_? catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#    5 0xCB3E7FA2C499AC0B69ACCD06C21...  0.0012  3.4%     2 0.0006  0.00 SELECT catalog_product_index_price search_tmp_?ed?cf?f?c?a?_?
#    6 0x2F9EDAB00084ED0A7EE1463DBA4...  0.0009  2.7%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
#    7 0x593763BE686057BEA87DB0BC232...  0.0008  2.4%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
#    8 0x23B42F57B465E32E1732E4070E9...  0.0008  2.2%    72 0.0000  0.00 SELECT inventory_stock
#    9 0x11C6E1A6D7347EEAF29EBEA1350...  0.0008  2.2%     1 0.0008  0.00 SELECT catalog_product_index_eav cataloginventory_stock_status cata [...]

2020-06-04 15:59 UTC, jonashrem commented
@magento run all tests

2020-06-04 17:16 UTC, jonashrem commented
@magento run Static Tests

2020-06-04 17:19 UTC, jonashrem commented
@magento run Functional Tests CE
@magento run Functional Tests EE

2020-06-04 17:20 UTC, jonashrem commented
@magento run Functional Tests EE

2020-06-04 17:20 UTC, jonashrem commented
@magento run Functional Tests B2B

2020-06-04 18:01 UTC, jonashrem commented
@magento run all tests

2020-06-04 19:35 UTC, jonashrem commented
@magento run Functional Tests B2B

2020-06-04 19:36 UTC, jonashrem commented
@magento run Functional Tests CE

2020-06-04 19:38 UTC, jonashrem commented
@magento run Static Tests

2020-06-04 19:52 UTC, jonashrem commented
@magento run Integration Tests

2020-06-04 21:51 UTC, jonashrem commented
@magento run Integration Tests

2020-06-04 22:14 UTC, jonashrem commented
@magento run Integration Tests

2020-06-05 06:30 UTC, aleron75 submitted a review, later dismissed

2020-06-05 06:31 UTC, aleron75 commented
The failing integration test doesn't seem related to this PR.
The affected method is used in a lot of tests so to me this satisfies test coverage.
Thus I approved this PR.

2020-06-05 06:32 UTC, magento-engcom-team commented
Hi @aleron75, thank you for the review.
[ENGCOM-7622](https://jira.corp.magento.com/browse/ENGCOM-7622) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-06-07 19:48 UTC, jonashrem commented
@magento run Integration Tests

2020-06-09 16:05 UTC, jonashrem commented
We tested the failing Integration test on 2.3.5-p1 and it didn't fail there, so I agree that this isn't related to our change.

2020-06-19 07:14 UTC, ihor-sviziev requested changes
Integration test fails, even after restarting few times. Looks like your change caused regression in some specific case - image resize command fails in case if DB storage used.

@jonashrem could you try to run following test locally? https://github.com/magento/magento2/blob/40a787632f36ca67f8fff8c451e1e8d1bdbaf9f6/dev/tests/integration/testsuite/Magento/MediaStorage/Console/Command/ImageResizeCommandTest.php#L120-L124

2020-06-19 14:24 UTC, jonashrem commented
@magento give me 2.4-develop instance

2020-06-19 14:24 UTC, magento-engcom-team commented
Hi @jonashrem. Thank you for your request. I'm working on Magento 2.4-develop instance for you

2020-06-19 14:26 UTC, magento-engcom-team commented
Hi @jonashrem, here is your [Magento instance](https://i-28516-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28516-2-4-develop.instances.magento-community.engineering/admin_6f30](https://i-28516-2-4-develop.instances.magento-community.engineering/admin_6f30)
Login: `0f11a9f8` Password: `4e5687cd5838`
Instance will be terminated in up to 3 hours.

2020-06-19 15:04 UTC, jonashrem commented
@ihor-sviziev thanks for the review.

We tested this integrationtest locally on 2.3.5-p1 before.

We now did another local test on our PR directly, but also couldn't reproduce this error.

Can you check we run the test correctly or do we need to do some special Magento settings here (for preparing DB Storage for example)?

We cloned our instance, did `composer install` and run the test.

```
dev/tests/integration # ../../../vendor/bin/phpunit --testdox testsuite/Magento/MediaStorage/Console/Command/ImageResizeCommandTest.php
PHPUnit 9.1.5 by Sebastian Bergmann and contributors.

Warning:       Using a custom test suite loader is deprecated

Image Resize Command (Magento\MediaStorage\Console\Command\ImageResizeCommand)
 ✔ Run resize with missing file
 ✔ Execute with zero byte image
 ✔ Database storage missing file

Time: 00:19.762, Memory: 111.00 MB

OK (3 tests, 3 assertions)

=== Memory Usage System Stats ===
Memory usage (OS):      141.02M (129.38% of 109.00M reported by PHP)
Estimated memory leak:  32.02M (22.71% of used memory)
```

```
dev/tests/integration # git remote -v                                                                                                          
origin  https://github.com/jonashrem/magento2.git (fetch)
origin  https://github.com/jonashrem/magento2.git (push)
```

```
dev/tests/integration # git branch
  2.4-develop
* faster-isTableExists
```

```
dev/tests/integration # cat etc/install-config-mysql.php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

return [
    'db-host' => 'localhost',
    'db-user' => 'db-user-4',
    'db-password' => '*',
    'db-name' => 'db-4',
    'db-prefix' => '',
    'backend-frontname' => 'backend',
    'admin-user' => \Magento\TestFramework\Bootstrap::ADMIN_NAME,
    'admin-password' => \Magento\TestFramework\Bootstrap::ADMIN_PASSWORD,
    'admin-email' => \Magento\TestFramework\Bootstrap::ADMIN_EMAIL,
    'admin-firstname' => \Magento\TestFramework\Bootstrap::ADMIN_FIRSTNAME,
    'admin-lastname' => \Magento\TestFramework\Bootstrap::ADMIN_LASTNAME,
//    'amqp-host' => 'localhost',
//    'amqp-port' => '5672',
//    'amqp-user' => 'guest',
//    'amqp-password' => 'guest',
];

```

2020-06-19 15:04 UTC, jonashrem commented
@magento run Integration Tests

2020-06-22 06:10 UTC, ihor-sviziev commented
@engcom-Golf @engcom-Charlie could you help to understand why integration tests fails on CI, while successfully executes locally?

2020-06-25 15:16 UTC, jonashrem commented
@engcom-Golf @engcom-Charlie @ihor-sviziev how is the status here? Is there anything, we can do to help in regard of this integration tests or the PR?

As I understand, the cloud instances provided by the m2-assistant bot don't come with ssh access to manually run the rests.

2020-06-30 11:49 UTC, engcom-Charlie commented
@magento run all tests

2020-07-02 09:53 UTC, jonashrem commented
@engcom-Charlie did you find out anything?

2020-07-02 10:03 UTC, engcom-Charlie commented
Unfortunately, I don't have an idea at the moment.

2020-07-02 14:14 UTC, ihor-sviziev commented
@slavvka @lenaorobei @naydav could you help to understand why integration test fails on CI, while on local machine it passes?

2020-07-06 16:35 UTC, lenaorobei commented
I found following error in logs
```
Magento\MediaStorage\Console\Command\ImageResizeCommandTest::testDatabaseStorageMissingFile
PHPUnit\Framework\Exception: Error in fixture: "\/var\/www\/html\/dev\/tests\/integration\/testsuite\/Magento\/MediaStorage\/_files\/product_with_missed_image.php".
 SQLSTATE[HY000]: General error: 1412 Table definition has changed, please retry transaction, query was: SELECT `e`.* FROM `media_storage_directory_storage` AS `e` WHERE (name = 'a') AND (path = 'tmp/catalog/product/m')
```

2020-07-06 21:20 UTC, leeps commented
Thank you, @lenaorobei, that helped!
We will look into this issue and get back to you all within a few days.

2020-07-15 12:59 UTC, jonashrem commented
@magento run Integration Tests

2020-07-15 18:07 UTC, jonashrem commented
Hmm, quite confusing.

Changing the order of tests doesn't help, fallback to old behavior on non hit doesn't help (#29153) and removing the new cache doesn't help as well (#29152).

2020-07-19 06:45 UTC, jonashrem commented
We are still working on this through. So do not close this, please.

2020-07-19 06:58 UTC, ihor-sviziev commented
Sure, no problem

On Sun, 19 Jul 2020 at 09:46, Jonas Hünig <notifications@github.com> wrote:

> We are still working on this through. So do not close this, please.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/28516#issuecomment-660597619>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOJOULOR5ZVWTFSP7WYKLTR4KJC5ANCNFSM4NSX33OQ>
> .
>

2020-07-19 14:28 UTC, jonashrem commented
Btw. is it possible, to get PHP Settings (like phpinfo or php --i and MySQL Settings "show variables \G" to compare with our environment?

2020-07-20 15:50 UTC, jonashrem commented
@magento run all tests

2020-07-26 04:31 UTC, ihor-sviziev commented
@jonashrem @engcom-Charlie maybe there should be some isolation enabled / disabled for failing test?

2020-07-26 16:58 UTC, jonashrem commented
@jonashrem @engcom-Charlie  thanks for the Hint. Do you have details how to enable this?

2020-07-27 07:29 UTC, engcom-Charlie commented
@jonashrem you can see details here https://devdocs.magento.com/guides/v2.4/test/integration/annotations.html

2020-07-27 10:20 UTC, Vinai commented
@ihor-sviziev Hi Ihor, good idea.
`@magentoDbIsolation` is automatically enabled when a test uses a `@magentoDataFixture` annotation so it would only be possible to explicitly disable DB isolation it for the test.

The `@magentoAppIsolation enabled` annotation on the other hand will cause the test framework to re-initialize the Magento app after the test, so it won't have an effect on the test itself, only on following tests.

I think you likely are right, but it is some other test that is missing one of these annotations. The tricky thing is figuring out which test is breaking test isolation and causing the failure of `Magento\MediaStorage\Console\Command\ImageResizeCommandTest::testDatabaseStorageMissingFile`

FYI, @jonashrem asked me to spend some time and try to find the cause, so I'm trying to bisect the testsuite to isolate the failure combination.
However, this requires a test environment where the error can be reproduced, which in turn requires fixing some other errors that happen when the whole suite is run in a local environment. It's a slow process, but maybe it will turn up something.

2020-07-27 10:57 UTC, ihor-sviziev commented
@Vinai FYI https://warden.dev/ works pretty good for many people ;)

2020-07-27 11:03 UTC, Vinai commented
@ihor-sviziev I love warden and use it a lot, but the last time I checked the integration test suite didn't complete there either.

2020-08-03 20:26 UTC, jonashrem commented
@magento run all tests

2020-08-03 23:35 UTC, jonashrem commented
@magento run Integration Tests

2020-08-03 23:48 UTC, jonashrem commented
ok. Disabled the Isolation actually helps, but now another test (/MediaStorage/Helper/File/Storage/DatabaseTest) is failing only for B2B edition (just running the test again to make sure it's realy related to the change).

Very confusing. Is there anything special with B2B? @ihor-sviziev ?

The exact same test runs fine on CE and EE.

2020-08-04 01:39 UTC, jonashrem commented
@magento run all tests

2020-08-04 08:24 UTC, jonashrem commented
Ok. Never mind. With changing both tests, the test run through.

@ihor-sviziev 

Is this fine for merging or do you need us, to make changes to Magento until the test pass with Isolation enabled ( As I see, there are already multiple tests with disabled isolation)

2020-08-04 08:41 UTC, ihor-sviziev approved these changes
Good job! Approved! ✔

2020-08-04 08:41 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/MediaStorage/Helper/File/Storage/DatabaseTest.php
> +     * @magentoDbIsolation disabled
Note for QA: Need to make sure this test is not leaving any data in DB after test run.

2020-08-04 08:41 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/MediaStorage/Console/Command/ImageResizeCommandTest.php
> +     * @magentoDbIsolation disabled
Note for QA: Need to make sure this test is not leaving any data in DB after test run.

2020-08-04 08:43 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7622](https://jira.corp.magento.com/browse/ENGCOM-7622) has been created to process this Pull Request

2020-08-18 19:30 UTC, sidolov commented
@magento create issue

2020-08-26 09:44 UTC, jonashrem commented
@ihor-sviziev @sidolov 

As I can't see the internal ticket. Is there anything left, we can do, to help the processing of this PR?

2020-08-26 09:46 UTC, ihor-sviziev commented
The PR is waiting for QA process, it’s public info. No actions required
from your side

On Wed, 26 Aug 2020 at 12:44 Jonas Hünig <notifications@github.com> wrote:

>
>
> @ihor-sviziev <https://github.com/ihor-sviziev> @sidolov
> <https://github.com/sidolov>
>
>
> As I can't see the internal ticket. Is there anything left, we can do, to
> help the processing of this PR?
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/28516#issuecomment-680776218>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOJOUIKIMJYLS3RR4PHSN3SCTKPFANCNFSM4NSX33OQ>
> .
>
>
>

2020-08-26 09:49 UTC, jonashrem commented
Ok. Thanks

2020-08-28 09:11 UTC, engcom-Charlie commented
@magento run all tests

2020-08-28 10:21 UTC, jonashrem commented
@magento  run Functional Tests CE

2020-08-28 11:30 UTC, jonashrem commented
@magento run Functional Tests B2B

2020-09-08 21:35 UTC, magento-engcom-team commented
Pull request successfully imported to branch `imported-magento-magento2-28516` in the `magento-engcom/magento2ce` repository.

2020-09-09 11:01 UTC, ihor-sviziev approved these changes

2020-09-09 11:02 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7622](https://jira.corp.magento.com/browse/ENGCOM-7622) has been created to process this Pull Request

2020-09-11 14:43 UTC, sidolov commented
Note for QA: the solution should be verified with cases when tables have been changed in DB.

Example: 
1. Check table exists for the first time (cache is generated)
2. Remove or rename a table
3. Check table presence once again. 

I suspect that we will get an error since the result is cached but the actual table was removed.

2020-09-11 14:47 UTC, jonashrem commented
> Note for QA: the solution should be verified with cases when tables have been changed in DB.
> 
> Example:
> 
>     1. Check table exists for the first time (cache is generated)
> 
>     2. Remove or rename a table
> 
>     3. Check table presence once again.
> 
> 
> I suspect that we will get an error since the result is cached but the actual table was removed.

One renaming and dropping tables, the cache will be cleared ( https://github.com/magento/magento2/blob/b597c7a0a80072a73a4914b1d80644a57445cb46/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2721 and https://github.com/magento/magento2/blob/b597c7a0a80072a73a4914b1d80644a57445cb46/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2616 ), so both should be fine.

2020-09-28 15:06 UTC, engcom-Echo commented
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x:
![image](https://user-images.githubusercontent.com/51681435/94449878-40096d00-01b5-11eb-88da-9ea84ee10e32.png)

**After:** :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/51681435/94449951-531c3d00-01b5-11eb-878d-abd0d4e3bcbb.png)

2020-09-30 19:38 UTC, merged