Simplify version constraint for the php-amqplib/php-amqplib package, …
magento/magento2 pull request #28585
Opened 2020-06-05 15:17 UTC by hostep

…now that the php extension sockets is considered required for Magento.

### Description (*)
As requested in https://github.com/magento/magento2/issues/27200 by @melnikovi, here's a pull request which simplifies the version constraint on the `php-amqplib/php-amqplib` package now that the php extension `sockets` is considered required for Magento 2.

Version 2.7 of `php-amqplib/php-amqplib` didn't require the `sockets` extension, but since version 2.8.1 it became required.

This prevents developers from accidentally updating the `composer.lock` file inside this github repo as well as inside projects where it changes the version of `php-amqplib/php-amqplib` based on if they have the `sockets` extension installed or not, which can be quite annoying to deal with.

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/27200

### Manual testing scenarios (*)
1. Have a PHP installation where the `sockets` extension is not installed
2. Try to install Magento using composer after this fix, it should no longer work.

### Questions or comments
I'm not entirely sure, but should we also define `ext-sockets` in the `composer.json` file of Magento 2? I'm a bit confused about [the comment](https://github.com/magento/devdocs/pull/6922#issuecomment-605032752) from @dobooth if the list of extensions in devdocs is generated from the `composer.json` file, or from all composer dependencies?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-05 15:19 UTC, hostep commented
Not really needed to run any tests here I believe, since the `composer.lock` file contains no real changes, so no dependencies are being changed here.

2020-06-05 19:02 UTC, ihor-sviziev submitted a review, later dismissed

2020-06-05 19:02 UTC, ihor-sviziev commented
@magento run all tests

2020-06-05 19:03 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7626](https://jira.corp.magento.com/browse/ENGCOM-7626) has been created to process this Pull Request

2020-06-05 19:04 UTC, ihor-sviziev commented
@hostep i think we don’t need to add dependency to sockets extension as magento actually not depends on it directly, only through library

2020-06-12 15:33 UTC, lenaorobei commented
Commit was cherry-picked and merge to 2.4.0 is in progress.

2020-06-16 07:17 UTC, engcom-Alfa requested changes
Hi, @hostep. Could you resolve merge conflicts?

2020-06-16 07:37 UTC, hostep commented
@engcom-Alfa: since @lenaorobei already merged this in the release branch for 2.4.0, there is no need anymore for this PR, right? We can probably close it?

2020-06-16 14:45 UTC, lenaorobei commented
@hostep thanks for this contribution! Yes, it was delivered to 2.4.0.

2020-06-16 14:45 UTC, closed without merging