#274 Admin Global Search: Search categories
magento/magento2 pull request #28588
Opened 2020-06-05 15:46 UTC by FredericMartinez

### Description (*)
Global search in backend can search into products, orders, customers, pages and config sections.
Now we can search categories too.

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/community-features/issues/274

### Manual testing scenarios (*)
1. Login into backend
2. Create a test category "Try to find me"
3. Use global search (in header to right, next to admin account setting)
4. Enter "to find"
5. You will see in autocomplete list our new fresh category, link is valid and redirect to the edit form

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

2020-06-05 15:46 UTC, FredericMartinez commented
@magento give me test instance

2020-06-05 15:46 UTC, magento-engcom-team commented
Hi @FredericMartinez. Thank you for your request. I'm working on Magento instance for you

2020-06-05 15:48 UTC, magento-engcom-team commented
Hi @FredericMartinez, here is your [new Magento instance](https://pr-28588.instances.magento-community.engineering).
Admin access: [https://pr-28588.instances.magento-community.engineering/admin_d843](https://pr-28588.instances.magento-community.engineering/admin_d843)
Login: `6e383ff3` Password: `6b137e49e023`
Instance will be terminated in up to 3 hours.

2020-06-05 15:57 UTC, FredericMartinez commented
It works like expected
![28588_1](https://user-images.githubusercontent.com/13019288/83897542-002a0000-a756-11ea-943a-3bcfde267ca4.png)
![28588_2](https://user-images.githubusercontent.com/13019288/83897547-015b2d00-a756-11ea-9452-836ed425c83c.png)

2020-06-05 19:43 UTC, okorshenko commented
@magento run Unit Tests

2020-06-05 20:56 UTC, Stepa4man commented
@magento give me test instance

2020-06-05 20:56 UTC, magento-engcom-team commented
Hi @Stepa4man. Thank you for your request. I'm working on Magento instance for you

2020-06-05 21:11 UTC, Stepa4man commented
Hey, @okorshenko 
What do you think if we ask the product owner about it?
It's definitely a good improvement. I am really happy about it.
But... I'm not sure about UI of this solution. 

My concern here about the following:
Global search doesn't search at the admin panel doesn't really search anything, it just redirects admin user to grid page of particular entity type, and submits a search with the requested string there.
But for Category, we don't have a grid and search there. So @FredericMartinez implemented search action directly on the global search level. Which does its job, but just doesn't match the basic concept of this tool.

2020-06-05 21:14 UTC, Stepa4man commented
Hi @FredericMartinez 
Thanks for your contribution.

I want to ask you to cover implemented functionality by tests according to [DOD](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html)

Also please  add to all changed (created) php files
```php
    declare(strict_types=1);
```
You can read more [here](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#1-basic-programming-principles)

2020-06-05 21:31 UTC, Stepa4man requested changes
@FredericMartinez 
Please check out my comments.
I know you just implemented it as \Magento\CatalogSearch\Model\Search\Catalog
But it's quite an old class, If you have doubts about how to write code you can read [this documentation](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html)

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
Please use searchCriteriaBuilderFactory here

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +                ->setValue('%' . $this->getQuery() . '%')
Please use `sprintf` here

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +                'id' => 'category/1/' . $category->getId(),
Please use sprintf here

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +    protected $string;
Please use a private access modifier

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +    protected $_adminhtmlData = null;
Please don't user underscore in property name it's an outdated approach

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +        \Magento\Framework\Stdlib\StringUtils $string
Please import all classes

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +     * Initialize dependencies.
Not sure if we need comment here.

2020-06-05 21:31 UTC, Stepa4man commented on app/code/Magento/CatalogSearch/Model/Search/Category.php
> +class Category extends \Magento\Framework\DataObject
Please import parent class

2020-06-05 21:44 UTC, okorshenko commented
Hi @Stepa4man 
That's interesting PR. Let's review it with PO on Monday. I will send you an invitation for next triage session

2020-06-08 12:17 UTC, FredericMartinez commented
@Stepa4man Thanks you for your review.

I understand all your comments about style codings
But, my Magento example are: `Magento\Backend\Model\Search\Customer`

You can find almost a copy/paste from this class with a category filter instead of a customer filter.

Actually, I hesitated to write the class properly, but I assume to have the same old code style.
Indeed, when you will rewrite Magento\Backend\Model\Search\Customer and all the other Admin Global Search classes, you will be able to clean them all at one time, my PR included.

My point was to contributed as it, it works like the old stylish classes and I can get my git patch from this PR in my projects.

Thanks for your time @Stepa4man & @okobchenko 
Have a nice week.

2020-06-10 06:38 UTC, Stepa4man commented
Hi @FredericMartinez, I understand your point but you should also understand us.
Yes, we definitely have some legacy code that requires cleaning up. But this is not the reason to deliver a new bad quality code. We have [Magento coding standards](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html)  and [DoD](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) and PR can be merged only if it follows these documents.
Thanks.

2020-07-27 13:24 UTC, engcom-Kilo commented
Working on this .

2020-07-30 09:35 UTC, engcom-Kilo commented
Added correction for code.

2020-07-30 09:36 UTC, engcom-Kilo commented
Added MFTF test.

2020-07-30 09:37 UTC, engcom-Kilo commented
@magento run all tests

2020-08-31 11:07 UTC, engcom-Hotel commented
Hello @Stepa4man could you please review PR changes.
Thank you.

2020-09-14 16:06 UTC, sidolov approved these changes

2020-09-14 16:07 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8204](https://jira.corp.magento.com/browse/ENGCOM-8204) has been created to process this Pull Request

2020-09-21 06:28 UTC, engcom-Hotel commented
@magento run all tests

2020-09-22 09:33 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

Magento 2.4-develop
Sample Data 

**Manual testing scenario:**

1. Login into backend;
2. Use global search (in the header to right, next to admin account setting)
3. Enter "Luma Yoga"

**Before:**  :heavy_multiplication_x: We don't see the specified category in the search list

![2020-09-22_12-22](https://user-images.githubusercontent.com/51679138/93865347-d679f200-fcce-11ea-8c9e-e073b942aa06.png)

**After:** :heavy_check_mark: we see in the autocomplete list our new fresh category, a link is valid and redirects to the edit form

![2020-09-22_12-19](https://user-images.githubusercontent.com/51679138/93865747-66b83700-fccf-11ea-9d33-e7df18b9edf5.png)

![Peek 2020-09-22 12-33](https://user-images.githubusercontent.com/51679138/93866018-d0d0dc00-fccf-11ea-95e7-7a4a8d648a48.gif)

2020-09-22 11:31 UTC, engcom-Hotel commented
@magento run all tests

2020-09-24 08:49 UTC, engcom-Hotel commented
@magento run all tests

2020-10-02 13:07 UTC, merged