MFTF: Admin Deletes Customer's Wishlist Item Test
magento/magento2 pull request #28632
Opened 2020-06-09 10:15 UTC by DmitryTsymbal

This PR contains a test for deleting items from customer wishlist as Admin user.

**Steps to reproduce:**

1 - Add a created product into wishlist as a customer
2 - Login as admin user
3 - Find created customer on grid
4 - Find added wishlist item
5 - Delete wishlist item
6 - Perform assertions

2020-06-09 10:16 UTC, dmytro-ch commented
@magento run all tests

2020-06-10 06:30 UTC, lbajsarowicz requested changes
I see two elements that make this test flaky. Please take a look and adjust these 👍

2020-06-10 06:30 UTC, lbajsarowicz commented on app/code/Magento/Customer/Test/Mftf/Section/AdminCustomerWishlistSection.xml
> +        <element name="deleteButton" type="text" selector=".even > td:nth-child(7) > a:nth-child(1)"/>
This is very flaky way to find the element. 
If there is no other option, even selecting by label is more appropriate

2020-06-10 06:30 UTC, lbajsarowicz commented on app/code/Magento/Wishlist/Test/Mftf/Test/AdminDeleteCustomerWishListItemTest.xml
> +            </createData>
Please bear in mind that tests might be run in "on schedule" indexing mode

2020-06-10 19:36 UTC, DmitryTsymbal commented on app/code/Magento/Customer/Test/Mftf/Section/AdminCustomerWishlistSection.xml
> +        <element name="deleteButton" type="text" selector=".even > td:nth-child(7) > a:nth-child(1)"/>
Refactored

2020-06-10 19:36 UTC, DmitryTsymbal commented on app/code/Magento/Wishlist/Test/Mftf/Test/AdminDeleteCustomerWishListItemTest.xml
> +            </createData>
Added cron cli

2020-06-12 06:58 UTC, lbajsarowicz commented
@magento run all tests

I'm going to review the PR in an hour or two

2020-06-12 07:02 UTC, lbajsarowicz approved these changes
:heavy_check_mark: Well done! Thank you for contribution.

2020-06-12 07:04 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7674](https://jira.corp.magento.com/browse/ENGCOM-7674) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-06-15 07:53 UTC, engcom-Alfa commented
@magento create issue

2020-06-15 08:58 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

2020-06-15 09:02 UTC, engcom-Charlie commented
@magento run all tests

2020-06-18 19:24 UTC, slavvka commented
@magento run all tests

2020-06-19 05:22 UTC, merged