change error to code is reserved key instead of code already exists
magento/magento2 pull request #28663
Opened 2020-06-10 12:13 UTC by AbdulRahmanAbouzaid

### Description (*)

Change error message caused by creating product attribute with `product_type` and `type_id` codes to be more descriptive.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28479

### Manual testing scenarios (*)

1. Go to `Stores` > `Attributes` > `Product`
2. Create new attribute with `product_type` or `type_id` code

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2020-06-10 12:31 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-24 20:07 UTC, lenaorobei requested changes
Let's move reserved attributes to the private constant.

Please consider covering this change with MFTF test.

2020-08-27 22:42 UTC, AbdulRahmanAbouzaid commented
@lenaorobei changes and test provided. Can you please review it again?

2020-08-27 22:43 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-27 22:50 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-28 11:19 UTC, AbdulRahmanAbouzaid commented
@magento run Functional Tests CE

2020-08-28 14:22 UTC, lenaorobei commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php
> +            if (in_array($attributeCode, static::RESERVED_CODES)) {
Let's simplify logic in this condition. The same `in_array` is being called twice. 
Please use `self` instead of `static` for constant access.

2020-08-29 19:34 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-29 19:37 UTC, AbdulRahmanAbouzaid commented
@lenaorobei Changes provided

2020-08-30 18:53 UTC, AbdulRahmanAbouzaid commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2020-08-31 00:13 UTC, AbdulRahmanAbouzaid commented
@magento run Functional Tests B2B

2020-08-31 11:44 UTC, AbdulRahmanAbouzaid commented
@magento run Functional Tests CE

2020-08-31 20:19 UTC, AbdulRahmanAbouzaid commented
@magento run Functional Tests EE

2020-08-31 20:27 UTC, lenaorobei commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php
> +        if (in_array($attributeCode, self::RESERVED_CODES)) {
```suggestion
        if (in_array($attributeCode, self::RESERVED_CODES, true)) {
```

2020-08-31 20:29 UTC, lenaorobei commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php
> +    const RESERVED_CODES = ['product_type', 'type_id'];
```suggestion
   private const RESERVED_ATTRIBUTE_CODES = ['product_type', 'type_id'];
```

2020-08-31 20:36 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-31 21:22 UTC, lenaorobei commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php
> +        if (in_array($attributeCode, self::RESERVED_CODES, true)) {
```suggestion
        if (in_array($attributeCode, self:: RESERVED_ATTRIBUTE_CODES, true)) {
```

2020-09-01 14:12 UTC, lenaorobei commented on app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php
> +        if (in_array($attributeCode, self:: RESERVED_ATTRIBUTE_CODES, true)) {
```suggestion
        if (in_array($attributeCode, self::RESERVED_ATTRIBUTE_CODES, true)) {
```

2020-09-01 18:50 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-09-01 20:49 UTC, lenaorobei commented
Please see Integration and Static builds failures. Looks like they were caused by your changes.

2020-09-07 12:41 UTC, gabrieldagama commented
The risk was set to`low` due to: the suggested changes shouldn't impact other areas.

2020-09-07 13:34 UTC, engcom-Echo commented
Hi @AbdulRahmanAbouzaid. Can you please fix "Static test"?

2020-09-10 14:20 UTC, AbdulRahmanAbouzaid commented
@magento run Static Tests

2020-09-10 14:21 UTC, lenaorobei commented
@magento run all tests

2020-09-10 15:30 UTC, lenaorobei approved these changes, later dismissed

2020-09-10 15:32 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-8178](https://jira.corp.magento.com/browse/ENGCOM-8178) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-10 23:23 UTC, AbdulRahmanAbouzaid commented
@magento run Functional Tests CE

2020-09-18 12:28 UTC, engcom-Alfa requested changes
Hi @AbdulRahmanAbouzaid .

Could you add this phrase `Code (%1) is a reserved key and cannot be used as attribute code.` to the translation file?
Thanks!

2020-09-18 21:07 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-09-18 21:08 UTC, AbdulRahmanAbouzaid commented
@engcom-Alfa phrase added to the translation file

2020-09-21 14:57 UTC, lenaorobei approved these changes

2020-09-22 06:44 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to Stores > Attributes > Product;
2. Create new attribute with _**product_type**_ or _**type_id**_ code;

**Before:** :heavy_multiplication_x: Either of following messages appear `An attribute with this code already exists.` OR `An attribute with the same code (product_type) already exists`.

![Screenshot from 2020-09-18 14-16-10](https://user-images.githubusercontent.com/51679138/93850883-bd197b80-fcb7-11ea-852b-2a781fa9edcf.png)

**After:** :heavy_check_mark: Attribute is not saved. Error message is shown

:heavy_check_mark: text: Code "`product_type`" is a reserved key and cannot be used as an attribute code.

![Screenshot from 2020-09-18 15-18-47](https://user-images.githubusercontent.com/51679138/93851046-171a4100-fcb8-11ea-8d75-63358a22d5de.png)

:heavy_check_mark: text: Code "`type_id`" a reserved key and cannot be used as attribute code.

![Screenshot from 2020-09-18 15-20-04](https://user-images.githubusercontent.com/51679138/93851093-2ef1c500-fcb8-11ea-8153-00675e75e121.png)

2020-09-22 06:59 UTC, engcom-Echo commented
@magento run all tests

2020-09-23 06:19 UTC, engcom-Echo commented
@magento run all tests

2020-09-24 00:58 UTC, merged