magento/28577_undeclared_webapi_dependency-fix
magento/magento2 pull request #28666
Opened 2020-06-10 15:13 UTC by sasha19957099

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2020-06-10 15:20 UTC, sasha19957099 commented
@magento run all tests

2020-06-12 16:23 UTC, danielrenaud requested changes

2020-06-12 16:23 UTC, danielrenaud commented on composer.lock
> +            "version": "1.10.7",
We don't want to update dependencies as a part of this change.
You can use `composer update -lock` to only update composer.lock hash without updating dependencies

2020-06-16 20:00 UTC, sasha19957099 commented
@magento run all tests

2020-06-16 20:52 UTC, danielrenaud approved these changes

2020-06-17 04:39 UTC, sasha19957099 commented
@magento run all tests

2020-06-17 06:27 UTC, sasha19957099 commented
@magento run all tests

2020-06-17 19:15 UTC, sasha19957099 commented
@magento run all tests

2020-06-17 20:33 UTC, danielrenaud commented
Manual testing not needed since this doesn't touch functionality. Automated tests will be enough

2020-06-17 21:33 UTC, danielrenaud approved these changes

2020-06-19 03:27 UTC, merged

2020-10-07 15:08 UTC, ihor-sviziev commented on dev/tests/static/testsuite/Magento/Test/Integrity/_files/dependency_test/whitelist/redundant_dependencies_webapi.php
> +];
Hi @sasha19957099 @danielrenaud,
Could you explain why this file was added? Seems like test shouldn't fail anymore as it has declared dependency on web api module. An I wrong?