clear errors when apply new filters
magento/magento2 pull request #28687
Opened 2020-06-11 13:42 UTC by AbdulRahmanAbouzaid

### Description (*)

Clear error when applying new filters instead of still displaying it **which is the wrong behavior** as mentioned in this [comment](https://github.com/magento/magento2/issues/8538#issuecomment-610846049)
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#8538

### Manual testing scenarios (*)

1. Create a new store view (call it "Second Store View" for example);
2. Log in to Admin -> Catalog -> Products;
3. Set up and apply a filter for the newly created store view;
![image](https://user-images.githubusercontent.com/51679138/78762028-0b49f500-798c-11ea-90ba-d98869350881.png)
4. Now, go to Admin->Stores->All Stores;
5. Delete the created before "Second Store View" store view;
6. Go to Admin->Catalog->Products again;
7.  Set up and apply a new filter and the error message will be disappeared.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-11 13:44 UTC, AbdulRahmanAbouzaid commented
@magento give me test instance

2020-06-11 13:44 UTC, magento-engcom-team commented
Hi @AbdulRahmanAbouzaid. Thank you for your request. I'm working on Magento instance for you

2020-06-11 13:56 UTC, AbdulRahmanAbouzaid commented
@magento run all test

2020-06-11 13:57 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-24 20:09 UTC, lenaorobei requested changes
Thanks for this fix. Please add MFTF test to cover expected behavior.

2020-08-26 23:02 UTC, AbdulRahmanAbouzaid commented
@lenaorobei I've provided the mftf using [AdminGridFilterDeleteAndVerifyErrorMessageTest](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Ui/Test/Mftf/Test/AdminGridFilterDeleteAndVerifyErrorMessageTest.xml) 
Can you review it please?

2020-08-27 16:58 UTC, lenaorobei requested changes
Thanks a lot!

Please see minor review comments and suggestions.

2020-08-27 16:58 UTC, lenaorobei commented on app/code/Magento/Ui/Test/Mftf/Test/AdminGridFilterRemoveErrorMessageBeforeApplyFilters.xml
> +            <testCaseId value="MC-142721"/>
```suggestion

```

2020-08-27 16:58 UTC, lenaorobei commented on app/code/Magento/Ui/Test/Mftf/Test/AdminGridFilterRemoveErrorMessageBeforeApplyFilters.xml
> +            <description value="Test log in to uI and Remove Error Message Before Apply Filters"/>
```suggestion
            <description value="Test Login to Admin UI and Remove Error Message Before Apply Filters"/>
```

2020-08-27 16:58 UTC, lenaorobei commented on app/code/Magento/Ui/Test/Mftf/Test/AdminGridFilterRemoveErrorMessageBeforeApplyFilters.xml
> +            <group value="uI"/>
```suggestion
            <group value="ui"/>
```

2020-08-27 16:58 UTC, lenaorobei commented on app/code/Magento/Ui/Test/Mftf/Test/AdminGridFilterRemoveErrorMessageBeforeApplyFilters.xml
> +            <group value="mtf_migrated"/>
```suggestion
```

2020-08-27 16:58 UTC, lenaorobei commented on app/code/Magento/Ui/Test/Mftf/Test/AdminGridFilterRemoveErrorMessageBeforeApplyFilters.xml
> +            <magentoCLI command="config:set system/backup/functionality_enabled 1" stepKey="setEnableBackupToYes"/>
I believe this is redundant.

2020-08-27 16:58 UTC, lenaorobei commented on app/code/Magento/Ui/Test/Mftf/Test/AdminGridFilterRemoveErrorMessageBeforeApplyFilters.xml
> +            <magentoCLI command="config:set system/backup/functionality_enabled 0" stepKey="setEnableBackupToNo"/>
Same here.

2020-08-27 17:30 UTC, AbdulRahmanAbouzaid commented
@magento run all tests

2020-08-27 21:03 UTC, lenaorobei commented
@magento run Functional Tests EE

2020-08-28 14:23 UTC, lenaorobei approved these changes

2020-08-28 14:24 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-8098](https://jira.corp.magento.com/browse/ENGCOM-8098) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-03 12:07 UTC, engcom-Oscar commented
:heavy_check_mark: QA Passed

Tested according manual scenario described in ticket 

### Before :heavy_multiplication_x: 
Error message persists after a new filter is submitted


### After :heavy_check_mark:
Error message disappeared.

2020-09-09 05:26 UTC, engcom-Charlie commented
@magento run all tests

2020-09-10 19:47 UTC, merged