Use MenuCategoryData to generate array in TopMenu plugin to allow extension via plugins
magento/magento2 pull request #28715
Opened 2020-06-13 19:48 UTC by fredden

### Description
Following [discussion on Magento Community Engineering Slack instance](https://magentocommeng.slack.com/archives/CBSL1DF8B/p1592055254155800), it has become clear that the `private` method `Magento\Catalog\Plugin\Block\Topmenu::getCategoryAsArray()` should be abstracted to allow extension via plugin (as inheritance (via preference) is to be discouraged). It appears that an existing class provides most of the functionality required. This pull request changes `getCategoryAsArray()` to use this existing external class (with `public` method) to allow this data to be augmented via plugin on the latter.

### Related Pull Requests
*None known*

### Fixed Issues
*None known*

### Manual testing scenarios
See also discussion on Slack (link above).

1. Attempt to add an item to output of `getCategoryAsArray()` from external code (third party extension)

### Questions or comments
I have not yet adjusted any tests, however this should not result in any change in functionality.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-13 22:56 UTC, lbajsarowicz requested changes
Injection of `Observer` to `Plugin` is not the best idea at all.
If you need the logic reusable across these two - just create separate class that provides Interface you need.

2020-06-15 08:08 UTC, fredden commented
`MenuCategoryData` isn't an observer, but a model in the wrong namespace. I've now moved it to 'Model'.

2020-08-18 19:36 UTC, sidolov commented
@magento create issue

2020-09-08 17:56 UTC, fredden commented
@magento run all tests

2020-10-29 22:06 UTC, fredden commented
@magento run all tests

2020-11-17 00:34 UTC, fredden commented
@magento run all tests

2020-11-18 14:25 UTC, lbajsarowicz commented
@magento run all tests

2020-11-19 12:56 UTC, fredden commented
@magento run all tests

2021-04-27 13:51 UTC, fredden commented
@magento run all tests

2021-08-04 12:01 UTC, fredden commented
@magento run all tests

2021-11-26 17:41 UTC, fredden commented
@magento run all tests

2021-11-26 18:37 UTC, fredden commented
@magento run all tests

2021-11-27 12:38 UTC, fredden commented
@magento run all tests

2022-10-21 10:30 UTC, fredden commented
@magento run all tests

2022-11-04 11:54 UTC, fredden commented
@magento run all tests

2024-02-05 22:47 UTC, fredden commented
@magento run all tests

2025-08-24 17:33 UTC, fredden commented
@magento run all tests

2025-11-20 13:14 UTC, lbajsarowicz commented
@fredden Are you willing to proceed with pushing this PR?

2025-11-21 18:15 UTC, fredden commented
@lbajsarowicz I have merged in the latest changes from the destination branch. Was there something else that you think needs to be done here?

2025-11-21 18:16 UTC, fredden commented
@magento run all tests

2025-12-10 05:47 UTC, engcom-Hotel commented
@magento run all tests

2025-12-11 10:29 UTC, engcom-Hotel requested changes
Hello @fredden,

Thank you for your contribution!

Please fix the failed static and integration tests.

Also refer to the below review comment.

Thank you

2025-12-11 10:29 UTC, engcom-Hotel commented on app/code/Magento/Catalog/Model/MenuCategoryData.php
> +namespace Magento\Catalog\Model;
Updating namespace might be a breaking change for the third party extensions or modules directly referencing `Magento\Catalog\Observer\MenuCategoryData` will break.

Leave the class empty in observer namespace by extending this class.

2025-12-16 21:40 UTC, fredden commented on app/code/Magento/Catalog/Model/MenuCategoryData.php
> +namespace Magento\Catalog\Model;
This seems fair. I have added a class as suggested in 80a8a30282279ae1983c9a1787c8ddb1c9285f9e.

2025-12-17 09:27 UTC, engcom-Hotel requested changes
Hello @fredden,

Thank you for making the changes!

The static and integration are still failing. Please fix those as well.

Thank you

2025-12-17 13:12 UTC, fredden commented
@magento run all tests

2025-12-17 14:48 UTC, fredden commented
@magento run all tests

2025-12-17 18:08 UTC, fredden commented
@magento run all tests

2025-12-17 22:49 UTC, fredden commented
@magento run all tests

2025-12-18 09:00 UTC, engcom-Hotel requested changes
Hello @fredden,

Thank you for updating the PR!

We are still seeing some static test failure. Please resolve them.

2025-12-18 10:20 UTC, fredden commented
@engcom-Hotel Please can you review these failures internally? There are two automated checks which are currently failing: "Magento Health Index" and "Static Tests".

## Magento Health Index

<img width="955" height="238" alt="Screenshot_2025-12-18_10-13-31" src="https://github.com/user-attachments/assets/ba2c16fc-5d58-40ff-b2e4-10d1530699b6" />

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28715/90f7639e613950ea7dca8b428245ff33/MagentoHealthIndex/report.html

From what I can tell, this check is complaining that there is some use of [PHP superglobals](https://www.php.net/manual/en/language.variables.superglobals.php) in `app/code/Magento/Catalog/Model/MenuCategoryData.php`. I can't see any such usage. Please can you show me what line number(s) this check is complaining about?

## Static Tests

<img width="949" height="271" alt="Screenshot_2025-12-18_10-13-43" src="https://github.com/user-attachments/assets/249fbf62-0dc8-462c-bba1-4742cdffaf41" />

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28715/d138deaa4d4f9ca484b509aaeb06c891/Statics/report-sanity-ce.html

This check seems to be complaining about some use of a "forbidden word" in `dev/tools/Magento/Tools/DatabaseCompare/etc/leftovers/ee/config.php`, however that file does not exist in the tree for this repository. See https://github.com/magento/magento2/tree/e88e1119cc5a32e71e5c911109f9cf33e0617ebd/dev/tools where there is no `Magento` directory.

What do you expect me to do about this check failure?

2025-12-22 12:42 UTC, engcom-Hotel commented on app/code/Magento/Catalog/Model/MenuCategoryData.php
> +        $currentCategory = $this->registry->registry('current_category');
> ## Magento Health Index
> <img alt="Screenshot_2025-12-18_10-13-31" width="955" height="238" src="https://private-user-images.githubusercontent.com/334786/528032418-ba2c16fc-5d58-40ff-b2e4-10d1530699b6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY0MDc0NTIsIm5iZiI6MTc2NjQwNzE1MiwicGF0aCI6Ii8zMzQ3ODYvNTI4MDMyNDE4LWJhMmMxNmZjLTVkNTgtNDBmZi1iMmU0LTEwZDE1MzA2OTliNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyMlQxMjM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDhmN2NkOTBlYWNmZDgxNDFmOGEzNDdkZWNiZGU0NTAzOTk0MDU0YWEwMzMyMzcyZjczZDRkZDZjYTY1Zjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bOixqUQgmqP7BY_oVbga9f7nBfqcDkbjKLozyPyT7Qg">
> https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28715/90f7639e613950ea7dca8b428245ff33/MagentoHealthIndex/report.html
> 
> From what I can tell, this check is complaining that there is some use of [PHP superglobals](https://www.php.net/manual/en/language.variables.superglobals.php) in `app/code/Magento/Catalog/Model/MenuCategoryData.php`. I can't see any such usage. Please can you show me what line number(s) this check is complaining about?

The static analysis tool is flagging the use of `Magento\Framework\Registry` as global state usage. The Registry pattern is deprecated in Magento 2.

I guess as a solution `hasActive()` method correctly uses the Layer resolver to get the current category:
`$currentCategory = $catalogLayer->getCurrentCategory();`

2025-12-27 12:24 UTC, fredden commented on app/code/Magento/Catalog/Model/MenuCategoryData.php
> +        $currentCategory = $this->registry->registry('current_category');
@engcom-Hotel please can you work to get this error resolved in the source file: https://github.com/magento/magento2/blob/2.4.9-alpha3/app/code/Magento/Catalog/Observer/MenuCategoryData.php#L63 (in a different pull request / internally).
I would prefer not to make such changes in this pull request as that is scope creep. Please can you ensure that the codebase adheres to the current coding standards. Situations like this generate significant friction for contributors.

2026-01-27 12:14 UTC, engcom-Hotel commented
Hello @fredden,

Please resolve the conflicts of this PR.

Thank you

2026-02-12 06:19 UTC, engcom-Hotel commented
@magento run Static Tests

2026-02-12 07:25 UTC, engcom-Hotel commented
@magento run Magento Health Index

2026-04-27 14:10 UTC, engcom-Charlie commented
@magento run all tests

2026-04-28 06:38 UTC, engcom-Charlie commented
Hi @fredden,

Thank you for your contribution!

I have fixed the static test failures. To move forward with this PR, we need the MHI to be fixed in this PR. Should I go ahead and take care of that?

2026-04-28 09:21 UTC, fredden commented
> I have fixed the static test failures. To move forward with this PR, we need the MHI to be fixed in this PR. Should I go ahead and take care of that?

No, the "MHI" (which I'm choosing to read as "Magento Health Index") check failure should NOT be fixed here. It is complaining about code that is NOT being changed in this pull request. See https://github.com/magento/magento2/pull/28715#discussion_r2649114472 where I asked for this to be fixed in a separate pull request by your team; you have added this check but have not done the necessary work to make your existing codebase comply with the rules being imposed. When the actual issue is resolved, the check will pass here.
Making changes to how the registry is used is out of scope for this pull request and will only confuse matters if included.

2026-05-14 04:47 UTC, engcom-Charlie commented
In order to proceed further on this PR the MHI needs to be fixed. Since there is no activity on [this](https://github.com/magento/magento2/pull/28715#issuecomment-4332932111) we are closing the PR now. Please feel free to reopen on any other further updates.

2026-05-14 04:47 UTC, closed without merging