Filename Collisions with downloadable products
magento/magento2 pull request #28726
Opened 2020-06-15 12:47 UTC by engcom-Charlie

### Description (*)

Fixed and covered by test.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#13915

### Manual testing scenarios (*)
See #13915

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-15 12:47 UTC, engcom-Charlie commented
@magento run all tests

2020-06-15 14:44 UTC, engcom-Charlie commented
@magento run all tests

2020-06-15 15:10 UTC, engcom-Charlie commented
@magento run all tests

2020-06-15 15:25 UTC, engcom-Charlie commented
@magento run all tests

2020-06-16 07:03 UTC, engcom-Charlie commented
@magento run all tests

2020-07-06 06:32 UTC, eduard13 requested changes
Hi @engcom-Charlie, thank you for the fix. 
Looks like there are couple of constantly failing [DB tests](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28726/36eed8f64eaebfe44841fd91c8661f11/DatabaseCompare/ce-skip-sd-db-compare-report.html) (all Sample Data checks).

Additionally, as a suggestion, may we have more meaningful commit messages?
Thank you.

2020-08-12 12:35 UTC, Nazar65 requested changes

2020-08-12 12:35 UTC, Nazar65 commented on app/code/Magento/Downloadable/Helper/File.php
> +use Magento\Framework\Filesystem\Driver\File as FileDriver;
Please use interface for that Magento\Framework\Filesystem\DriverInterface; and inject Magento\Framework\Filesystem\Driver\File via di configuration

2020-08-26 17:25 UTC, sidolov commented
@engcom-Charlie  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-08-26 17:25 UTC, closed without merging