28628 price range wildcards
magento/magento2 pull request #28745
Opened 2020-06-16 13:57 UTC by gallyamov

### Description (*)

This is for #28628

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28628

### Manual testing scenarios (*)

Check fixed issue for testing steps and expected results.

### Questions or comments

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-16 13:58 UTC, gallyamov commented
@magento run all tests

2020-06-16 14:54 UTC, gallyamov commented
@magento run all tests

2020-06-16 17:03 UTC, danielrenaud commented
@gallyamov please make sure api-functional tests are updated to reflect this change, and that this change is covered by api-functional tests for GraphQl perspective. There are already some tests that should be failining now with this change, so they should be updated with new behavior

2020-06-16 17:15 UTC, danielrenaud requested changes
Looks good, just need to update api-functional tests and make all builds pass

2020-06-16 17:15 UTC, danielrenaud commented on app/code/Magento/Elasticsearch/SearchAdapter/Aggregation/Builder/Dynamic.php
>              $resultData[$rangeName] = array_merge(['value' => $rangeName], $value);
This line is causing static failure due to array_merge in loop. can it be refactored to avoid that?

2020-06-17 11:21 UTC, gallyamov commented
@magento run all tests

2020-06-17 21:57 UTC, danielrenaud approved these changes

2020-06-27 17:50 UTC, merged