ISSUE-27475 - Prevent unnecessary product loads during rule validation
magento/magento2 pull request #28764
Opened 2020-06-17 17:15 UTC by zaximus84

### Description (*)
When Magento\Rule\Model\Condition\AbstractCondition::validate attempts to validate an entity during rule processing, it does a full load of the entity if the attribute being evaluated is not present in the entity's data array (checked with hasData). For shopping cart price rules, this results in a product being fully loaded multiple times if it doesn't have a value for that attribute in the database.

Magento\SalesRule\Model\Plugin\QuoteConfigProductAttributes ensures that all attributes which might be needed by shopping cart price rules are loaded on the cart products, so in theory, a hasData result of false always means the product doesn't have data for that attribute. $model->load($model->getId()) won't help. The model needs a record of the original data load attempt, even if there was no data for a given attribute.

This PR enhances the attribute value load process in the eav collection abstract to ensure that selected attributes are present in the post-load data array, even if there was no value in the database (in which case the value is set as null).

As an example, let's say we just created the attribute "some_attribute" and it has no default value. No products have been edited to assign a value yet. This is what happens when a product collection is loaded:
`
$productCollection->addAttributeToSelect('some_attribute')->load();
$produdctCollection->getFirstItem()->hasData('some_attribute'); //false
$productCollection->getFirstItem()->getData(); //null
`
This is what will happen with the changes in this PR:
`
$productCollection->addAttributeToSelect('some_attribute')->load();
$produdctCollection->getFirstItem()->hasData('some_attribute'); //true
$productCollection->getFirstItem()->getData(); //null
`

Because "some_attribute" is a key in the data array, it's clear that the attribute value was loaded. In Magento\Rule\Model\Condition\AbstractCondition::validate, hasData will be true, and the product will not be unnecessarily loaded again.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#27475

### Manual testing scenarios (*)
See preconditions, steps to reproduce, and expected result in [https://github.com/magento/magento2/issues/27475](https://github.com/magento/magento2/issues/27475)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-23 17:52 UTC, swnsma requested changes
Hi @zaximus84!

Thank you for your contribution!
I appreciate your PR and think that this is a great thing that is going to deliver.

However, there are a few things I need to ask you:
1) Please check my code suggestion. I believe that this is one of the performance vulnerable places and we need to fight with each function call.
2) I do not like the idea that we will have only this approach for collections. Could you check if we can add the same behavior (set null for missed attributes) also during entities load (I can suggest starting from \Magento\Eav\Model\ResourceModel\ReadHandler::execute)?
3) Also, Magento Definition of Done requires to cover each PR with some kind of autotests. Could you cover new changes with tests?
I believe, adjust certain scenario, which is going to be fixed in current PR - should be enough (\Magento\Eav\Test\Unit\Model\Entity\Collection\AbstractCollectionTest)

2020-06-23 17:52 UTC, swnsma commented on app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php
> +        foreach ($this->_itemsById as $items) {
I hope we could simplify the code a little but
```
$selectAttributesCodes = array_keys($this->_selectAttributes);
foreach ($this->_itemsById as $items) {
    foreach ($items as $item) {
        foreach (array_diff($selectAttributesCodes, array_keys($item->getData())) as $attributeCode) {
            $item->setData($attributeCode, null);
        }
    }
}
```

2020-06-24 06:50 UTC, swnsma commented
@magento run all tests

2020-06-24 19:09 UTC, swnsma commented
@magento run all tests

2020-06-26 15:16 UTC, swnsma commented
@magento run all tests

2020-06-26 15:17 UTC, swnsma commented
@magento run all tests

2020-07-21 09:54 UTC, engcom-Charlie commented
Hi @zaximus84, could you please look through failed tests?

2020-08-05 08:04 UTC, engcom-Charlie commented
Hi @zaximus84, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-08-05 08:04 UTC, closed without merging