Refactor - cleanup unnecessary around plugins
magento/magento2 pull request #28767
Opened 2020-06-17 20:23 UTC by lewisvoncken

after:
    
            \Magento\GroupedProduct\Helper\Product\Configuration\Plugin\Grouped::afterGetOptions
            \Magento\ConfigurableProduct\Helper\Product\Configuration\Plugin::afterGetOptions
            \Magento\AdvancedSearch\Model\Indexer\Fulltext\Plugin\CustomerGroup::afterSave
            \Magento\Catalog\Model\Indexer\Product\Price\Plugin\CustomerGroup::afterSave
            \Magento\CatalogSearch\Model\Attribute\SearchWeight::afterSave
            \Magento\CatalogUrlRewrite\Model\Category\Plugin\Category\Remove::afterDelete
            \Magento\ConfigurableProduct\Model\Entity\Product\Attribute\Group\AttributeMapper\Plugin::afterMap
            \Magento\ConfigurableProduct\Plugin\Model\ResourceModel\Product::afterDelete
            \Magento\Customer\Model\Plugin\CustomerFlushFormKey::afterExecute
            \Magento\GroupedProduct\Model\ResourceModel\Product\Link\RelationPersister::afterDeleteProductLink
            \Magento\Theme\Model\Indexer\Design\Config\Plugin\Store::afterSave
            \Magento\Theme\Model\Indexer\Design\Config\Plugin\Website::afterSave
    
    before:
    
            \Magento\CatalogInventory\Plugin\MassUpdateProductAttribute::beforeExecute

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27912

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-17 20:24 UTC, lewisvoncken commented
@magento run all tests

2020-06-19 07:22 UTC, ihor-sviziev commented
@magento run all tests

2020-06-19 07:59 UTC, ihor-sviziev requested changes

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/AdvancedSearch/Test/Unit/Model/Indexer/Fulltext/Plugin/CustomerGroupTest.php
> +    public function afterSaveDataProvider(): array
This is data provider, please update place where it is used

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/CatalogInventory/Plugin/MassUpdateProductAttribute.php
> +    public function beforeExecute(Save $subject)
We don't really need to change arguments for "save", so it's better to use `void` return type here and not use return statement at all 
```suggestion
    public function beforeExecute(Save $subject): void
```

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/CatalogInventory/Plugin/MassUpdateProductAttribute.php
> +            return [];
```suggestion
```

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/CatalogInventory/Plugin/MassUpdateProductAttribute.php
> +            return [];
```suggestion
```

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/CatalogInventory/Plugin/MassUpdateProductAttribute.php
> +            return [];
```suggestion
```

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/CatalogSearch/Model/Attribute/SearchWeight.php
>          $isNew = $attribute->isObjectNew();
I think after save it will be always "false", probably that's why we had there "around" plugin. Could you double check it?

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Plugin/Model/ResourceModel/Product.php
>          $configurableProductIds = $this->configurable->getParentIdsByChild($product->getId());
not sure this still will be available after deleting product. Please double check it

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/GroupedProduct/Model/ResourceModel/Product/Link/RelationPersister.php
>          $subject->load($link, $linkId, $subject->getIdFieldName());
I think it will not work after deleting

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/Theme/Model/Indexer/Design/Config/Plugin/Store.php
>          $isObjectNew = $subject->getId() == 0;
Looks liike this will be always false, as object already saved and have id

2020-06-19 07:59 UTC, ihor-sviziev commented on app/code/Magento/Theme/Model/Indexer/Design/Config/Plugin/Website.php
>          $isObjectNew = $subject->getId() == 0;
Looks liike this will be always false, as object already saved and have id

2020-07-10 11:00 UTC, ihor-sviziev commented
Hi @lewisvoncken,
Will you be able to update your PR?

2020-07-17 06:44 UTC, ihor-sviziev commented
@lewisvoncken  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-07-17 06:44 UTC, closed without merging