Fix shipping address id getter misspelling
magento/magento2 pull request #28810
Opened 2020-06-19 10:24 UTC by kodubovik

### Description (*)

Fixed a shipping address id getter misspelling in the sales order address save handler. Misspelt getter caused unneeded requests to the database on each order save which might create deadlocks.

### Manual testing scenarios (*)
This bug can not be validated manually as there're no effects visible on the front-end.
The fix includes Unit tests to validate that address save handler does not execute save attribute method when it's not needed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-19 10:32 UTC, kodubovik commented
@magento run all tests

2020-06-19 11:28 UTC, ihor-sviziev commented
@kodubovik good catch!
I think it could be checked with adding breakpoint with xdebug.

2020-06-19 11:38 UTC, ihor-sviziev requested changes
Could you remove phpdoc block for Address class, as static tests complaining about it?

2020-06-22 09:11 UTC, kodubovik commented
@magento run all tests

2020-06-22 16:14 UTC, ihor-sviziev approved these changes

2020-06-22 16:17 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7723](https://jira.corp.magento.com/browse/ENGCOM-7723) has been created to process this Pull Request

2020-06-22 16:18 UTC, magento-engcom-team commented
@kodubovik thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-07-02 10:51 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
Was checked cases with place order as guest, place order as registered customer with same/different billing and shipping address, checkout with multiple addresses.

2020-07-03 10:51 UTC, engcom-Delta commented
@magento create issue

2020-07-09 03:12 UTC, merged