Fix for empty category field values in REST calls
magento/magento2 pull request #28828
Opened 2020-06-22 12:48 UTC by victorlap

### Description (*)
When using either rest/all/V1/categories or rest/all/V1/categories?rootCategoryId=2 the name and product_count fields are empty for all categories in the tree. This does not happen when using a store code like default without a rootCategoryId as GET param, like this: rest/default/V1/categories

### Related Pull Requests
This is a resubmit of #23587

### Manual testing scenarios (*)
Use Magento installatie with a category tree and place a REST API call to 'rest/all/V1/categories'.

This will result in empty field values for name and product_count.

When using a storecode like default instead of all in the endpoint call, the fields will be filled in the data that we get back from the API endpoint.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-22 13:52 UTC, rogyar commented
@magento run all tests

2020-06-22 13:54 UTC, rogyar commented
Hi @victorlap. Thank you for your collaboration. Are you able to reproduce this issue for the current 2.4-develop mainline? I'm asking because this change has been previously rejected because of inability to reproduce this issue. 

If you still think that your change fixes the issue, please cover it with unit or API-functional test.

Thank you!

2020-06-22 14:49 UTC, victorlap commented
@magento give me 2.4-develop instance

2020-06-22 14:49 UTC, magento-engcom-team commented
Hi @victorlap. Thank you for your request. I'm working on Magento 2.4-develop instance for you

2020-06-22 14:51 UTC, magento-engcom-team commented
Hi @victorlap, here is your [Magento instance](https://i-28828-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28828-2-4-develop.instances.magento-community.engineering/admin_b4a6](https://i-28828-2-4-develop.instances.magento-community.engineering/admin_b4a6)
Login: `f32fd406` Password: `e384f48b3139`
Instance will be terminated in up to 3 hours.

2020-06-22 15:04 UTC, victorlap commented
Hi @rogyar ,

This is currently happening on a magento 2.3 install. And this patch fixes the issue. I will try to see if I can create a test for it, but I am unknown to the magento test suite so it might take a while.

2020-08-14 20:20 UTC, sidolov commented
@magento create issue

2020-09-14 19:26 UTC, sidolov requested changes
@victorlap could you please cover changes with auto tests?

2020-09-17 10:41 UTC, gabrieldagama commented
Risk set to low since the changes may not affect other areas.

2020-09-21 09:34 UTC, engcom-Charlie commented
@victorlap can you please cover your changes by WebAPI test?
Thank you.

2020-09-23 08:23 UTC, engcom-Charlie commented
@victorlap I'll take care of test coverage.

2020-09-23 09:22 UTC, engcom-Charlie commented
I check on your PR `rest/all/V1/categories`
![image](https://user-images.githubusercontent.com/51680850/93992938-d6ddc000-fd96-11ea-83f5-5625af2fbedc.png)
when using `rest/all/V1/categories?rootCategoryId=2`
![image](https://user-images.githubusercontent.com/51680850/93993034-efe67100-fd96-11ea-8279-5e1f9f019d67.png)
But if I use `default` instead of `all` all works fine. Looks like your PR doesn't fix the issue.
@victorlap can you please take a look?

2020-09-29 20:05 UTC, sidolov commented
@victorlap I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-29 20:05 UTC, closed without merging