Discount  applying on Shipping Amount for the rule 'Buy X get Y free (discount amount is Y)'
magento/magento2 pull request #28839
Opened 2020-06-22 17:36 UTC by engcom-Echo

### Description (*)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26723

### Manual testing scenarios (*)

1. See magento/magento2#26723

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-22 17:37 UTC, engcom-Echo commented
@magento run all tests

2020-06-23 08:31 UTC, ihor-sviziev requested changes
Hi @engcom-Echo,
Could you cover your changes with some types of tests?

2020-06-23 11:10 UTC, engcom-Echo commented
@magento run all tests

2020-06-23 18:35 UTC, bradleybrecher commented
@magento give me 2.3.5-p1 instance

2020-06-23 18:35 UTC, magento-engcom-team commented
Hi @bradleybrecher. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

2020-06-23 18:36 UTC, magento-engcom-team commented
Hi @bradleybrecher, here is your [Magento instance](https://i-28839-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28839-2-3-5-p1.instances.magento-community.engineering/admin_b5c8](https://i-28839-2-3-5-p1.instances.magento-community.engineering/admin_b5c8)
Login: `f3937c7c` Password: `93183be11336`
Instance will be terminated in up to 3 hours.

2020-06-24 07:24 UTC, ihor-sviziev requested changes

2020-06-24 07:24 UTC, ihor-sviziev commented on app/code/Magento/SalesRule/Model/Validator.php
> +    private function getDiscountQtyAllItemsBuyXGetYAction($quote, $rule)
Can we define argument & return types here?

2020-06-24 07:24 UTC, ihor-sviziev commented on app/code/Magento/SalesRule/Model/Validator.php
> +            $x = $rule->getDiscountStep();
could you use more clear names here?

2020-06-24 11:46 UTC, engcom-Echo commented
@magento run all tests

2020-06-25 07:03 UTC, engcom-Echo commented
@magento run all tests

2020-06-25 07:08 UTC, ihor-sviziev commented on app/code/Magento/SalesRule/Model/Validator.php
> +            $x = $rule->getDiscountStep();
As we discussed - it's buy X get Y, so x and y just named as is and is't ok.

2020-06-25 10:29 UTC, ihor-sviziev approved these changes

2020-06-25 10:33 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7746](https://jira.corp.magento.com/browse/ENGCOM-7746) has been created to process this Pull Request

2020-06-26 10:04 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
**Manual testing scenario:**
- Create simple product with Price=89$
- Create Cart Price Rules

 
![image](https://user-images.githubusercontent.com/51681379/85844643-bad47d80-b7ab-11ea-8cb1-eeb27cff9c18.png)
![image](https://user-images.githubusercontent.com/51681379/85844737-e2c3e100-b7ab-11ea-8355-3faa48c04850.png)

- Go to storefront
- Add 3 simple products to cart
- Go to Shopping Cart page

**Before:**
:heavy_check_mark: Third product is free
:x: Shipping for third product is remain and added to Order Total. Discount include only product price(89$)
![image](https://user-images.githubusercontent.com/51681379/85845127-72698f80-b7ac-11ea-8e08-fbfa5e41b02d.png)

**After:**
:heavy_check_mark: Third product is free
:heavy_check_mark: Shipping for third product is free and discount include product price(89$) + shipping price(5$)
![image](https://user-images.githubusercontent.com/51681379/85845719-5d413080-b7ad-11ea-8a54-b0ede01adc4d.png)

2020-06-26 14:07 UTC, engcom-Kilo commented on app/code/Magento/SalesRule/Model/Validator.php
> +                    $allQtyDiscount = $this->getDiscountQtyAllItemsBuyXGetYAction($quote, $rule);
Seems not need apply discount to Shipping, 
if Shipping method Handling type is "Per Order" or "Fixed" (fixed shipping price for Order).

![Configuration___Settings___Stores___Magento_Admin](https://user-images.githubusercontent.com/60192090/85866072-81ae0480-b7cf-11ea-9b92-00c33e912cd0.jpg)
![Shopping_Cart](https://user-images.githubusercontent.com/60192090/85866082-84a8f500-b7cf-11ea-8505-1de29fc41483.jpg)

2020-06-26 14:09 UTC, engcom-Kilo commented
@engcom-Echo 
Seems not need apply discount to Shipping,
if Shipping method Handling type is "Per Order" or "Fixed" (fixed shipping price for Order).


![Configuration___Settings___Stores___Magento_Admin](https://user-images.githubusercontent.com/60192090/85866072-81ae0480-b7cf-11ea-9b92-00c33e912cd0.jpg)
![Shopping_Cart](https://user-images.githubusercontent.com/60192090/85866082-84a8f500-b7cf-11ea-8505-1de29fc41483.jpg)

2020-06-30 09:31 UTC, engcom-Kilo commented on app/code/Magento/SalesRule/Model/Validator.php
> +                    $allQtyDiscount = $this->getDiscountQtyAllItemsBuyXGetYAction($quote, $rule);
Checked
Your changes are correct.

2020-07-16 00:52 UTC, merged