Cover form email component in checkout page with jasmine test
magento/magento2 pull request #28842
Opened 2020-06-23 03:27 UTC by mrtuvn

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-28 02:12 UTC, mrtuvn commented
@magento run all tests

2020-07-17 15:40 UTC, mrtuvn commented
@magento run all tests

2020-07-26 04:00 UTC, ihor-sviziev requested changes

2020-07-26 04:00 UTC, ihor-sviziev commented on dev/tests/js/jasmine/tests/app/code/Magento/Checkout/frontend/js/view/form/element/email.test.js
> +                    entity_Id: 1
I think it should be like this:
```suggestion
                    entity_id: 1
```
Is it mistake?

2020-07-26 12:58 UTC, mrtuvn commented on dev/tests/js/jasmine/tests/app/code/Magento/Checkout/frontend/js/view/form/element/email.test.js
> +                    entity_Id: 1
https://github.com/magento/magento2/blob/2.4-develop/dev/tests/js/jasmine/tests/app/code/Magento/Vault/view/frontend/web/js/view/payment/method-renderer/vault.test.js#L48
This file still use entity_Id

2020-07-26 12:59 UTC, mrtuvn commented on dev/tests/js/jasmine/tests/app/code/Magento/Checkout/frontend/js/view/form/element/email.test.js
> +                    entity_Id: 1
But i think use entity_id is more make sense than entity_Id

2020-07-26 13:00 UTC, mrtuvn commented
@magento run tests

2020-07-26 13:04 UTC, mrtuvn commented
@magento run tests

2020-07-26 13:04 UTC, mrtuvn commented
@magento run all tests

2020-07-26 14:51 UTC, mrtuvn commented
@omiroshnichenko can you review this

2020-07-27 09:32 UTC, ihor-sviziev commented on dev/tests/js/jasmine/tests/app/code/Magento/Checkout/frontend/js/view/form/element/email.test.js
> +                    entity_Id: 1
Could you check what we have on the frontend? If it's entity_Id - let's leave it test as is, if it's entity_id - let's update the test

2020-07-29 08:20 UTC, ihor-sviziev commented
@magento run Integration Tests

2020-07-29 13:13 UTC, ihor-sviziev approved these changes

2020-07-29 13:14 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7913](https://jira.corp.magento.com/browse/ENGCOM-7913) has been created to process this Pull Request

2020-07-30 08:30 UTC, engcom-Alfa commented
QA not applicable

2020-08-01 09:19 UTC, merged