Issue 28656 inline translation rest api
magento/magento2 pull request #28856
Opened 2020-06-23 18:12 UTC by zaximus84

### Description (*)
When inline translation is enabled for the storefront, it should be limited to the frontend where HTML is rendered. However, making an API call to /rest/V1/integration/admin/token with bad credentials while inline translation is enabled results in inline translation markup around the error message in the API response.

Since inline translation markup is only useful in the adminhtml and frontend areas, this PR adds an area check in addition to the existing configuration checks before rendering inline translation markup.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#28656

### Manual testing scenarios (*)
1. Go to admin
2. Stores > Settings > Configuration
3. In the left panel, expand Advanced and choose Developer
4. Expand selector the Translate Inline section
5. Set Enabled for Storefront to Yes
6. Click on save config
7. Try to login to admin as a user using API-
    POST - {Baseurl}/rest/V1/integration/admin/token
    Body - {"username": "","password": ""}
8. Confirm the response does not contain inline translation markup (a <span>)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-06-24 19:00 UTC, swnsma requested changes
Hi @zaximus84!
Please check my suggestions.
Also, please check failed tests.

2020-06-24 19:00 UTC, swnsma commented on lib/internal/Magento/Framework/Translate/Inline.php
> +    private function isAreaAllowed()
```suggestion
    private function isAreaAllowed(): bool
```

2020-06-24 19:00 UTC, swnsma commented on lib/internal/Magento/Framework/Translate/Inline.php
> +        \Magento\Framework\App\State $appState,
```suggestion
        \Magento\Framework\App\State $appState = null,
```

2020-06-24 19:00 UTC, swnsma commented on lib/internal/Magento/Framework/Translate/Inline.php
> +        $this->appState = $appState;
```suggestion
        $this->appState = $appState ?: \Magento\Framework\App\ObjectManager::getInstance()
               ->(\Magento\Framework\App\State::class);
```

2020-06-24 19:09 UTC, swnsma commented
@magento run all tests

2020-06-26 15:18 UTC, swnsma commented
@magento run all tests

2020-06-30 11:39 UTC, engcom-Charlie commented
@magento run all tests

2020-07-01 08:26 UTC, engcom-Charlie commented
Hi @zaximus84, can You please fix failed tests and look through requested changes?

2020-07-07 11:12 UTC, engcom-Charlie commented
@magento run all tests

2020-07-07 17:34 UTC, swnsma commented
@magento run all tests

2020-07-08 12:10 UTC, engcom-Charlie commented
@magento run all tests

2020-07-13 12:57 UTC, swnsma approved these changes

2020-07-13 12:58 UTC, magento-engcom-team commented
Hi @swnsma, thank you for the review.
[ENGCOM-7829](https://jira.corp.magento.com/browse/ENGCOM-7829) has been created to process this Pull Request

2020-07-14 09:16 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to Admin-> Stores -> Configuration -> Advanced -> Developer -> Translate Inline;
2. Set **Enabled for Storefront** to **Yes** and Save;
3. Clean cache;
4. Go to Storefront -> Sign In

Actual Result: :heavy_check_mark:  Inline translate for Storefront is enabled

![Screenshot from 2020-07-14 12-02-12](https://user-images.githubusercontent.com/51679138/87407285-9f9aa800-c5ca-11ea-8c7e-c1b03c1e727c.png)

5. Try to login to admin as a user using API-
**POST** - `{Baseurl}/rest/V1/integration/admin/token`
Body - {"username": "","password": ""}

**Before:** :heavy_multiplication_x: Result from rest API:

![2020-07-14_11-03](https://user-images.githubusercontent.com/51679138/87407519-f1433280-c5ca-11ea-84b5-bb4e00e7a85d.png)

**After:** :heavy_check_mark: Inline translation only affects frontend side and the response does not contain inline translation markup

```
{
  "message": "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.",
}
```

2020-07-23 08:57 UTC, merged