Fix for communication.xml Handlers merging processs
magento/magento2 pull request #28926
Opened 2020-06-29 21:12 UTC by matiashidalgo

### Description (*)
This changes fixes the "handler" merging process into communication.xml files which currently overrides all the handlers with the last one created, ignoring it's different names as expected. Issue found during custom handler development for MCOM module where there was already a handler for a message.

### Manual testing scenarios (*)
1. Develop a module which defines two handlers, with different names, for a same request on communication.xml
2. Check config after flush cache, it will only includes the last handler specified.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-13 20:23 UTC, sidolov commented
@magento create issue

2020-08-18 15:07 UTC, lenaorobei requested changes
Thanks for fixing it.

Could you please add integration test to cover this?

2020-08-18 15:07 UTC, lenaorobei commented
@magento run all tests

2020-08-19 14:39 UTC, matiashidalgo commented
> Thanks for fixing it.
> 
> Could you please add integration test to cover this?

Hi @lenaorobei since this is a fix to Framework I can not find any example of an Integration test, would you mind to point me out to an example of this and tell me which module I'm supposed to use for place my integration test?

2020-08-19 16:57 UTC, lenaorobei commented
Sure! Please see example `dev/tests/integration/testsuite/Magento/Framework/Communication/ConfigTest.php`.

I also noticed that Static Tests build failed. Here is the report https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28926/f2b73dfd3095f563cfde67e1f874d8e1/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/dccf717ef048c46e/

Looks like this particular case needs to be suppressed, because default parameters are different.

2020-08-21 19:47 UTC, lenaorobei commented
@magento run all tests

2020-08-21 19:54 UTC, matiashidalgo commented
> Sure! Please see example `dev/tests/integration/testsuite/Magento/Framework/Communication/ConfigTest.php`.
> 
> I also noticed that Static Tests build failed. Here is the report https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28926/f2b73dfd3095f563cfde67e1f874d8e1/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/dccf717ef048c46e/
> 
> Looks like this particular case needs to be suppressed, because default parameters are different.

Thank you a lot for pointing me to the right place, I've found the reason which makes the integration test not detect this issues so now it is covered.

About the static code error, I didn't found how to fix it, can you help me once again and point me out where this can be fixed?

2020-08-24 13:13 UTC, lbajsarowicz commented
@magento run all tests

2020-08-24 14:20 UTC, matiashidalgo commented
@magento run all tests

2020-08-24 14:21 UTC, lbajsarowicz commented
@matiashidalgo Perfect timing! I was just sending the recommendations to you.

2020-08-24 15:49 UTC, cherryz23 commented
Got it, thanks.

Sent from my Apple Watch

2020-08-24 18:57 UTC, matiashidalgo commented
@lenaorobei @lbajsarowicz I can't find the issue on this failed tests, can you check?

2020-08-24 19:16 UTC, lenaorobei commented
It might be caused by outdated branch.

@magento run all tests

2020-09-02 15:25 UTC, matiashidalgo commented
@lenaorobei any idea why this is still failing?

2020-09-02 16:58 UTC, lenaorobei commented
Builds fail on installation step.
```
07:00:47 [DBC DBC-SD-Tests-EE] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\Config\SchemaLocatorInterface in /var/www/magento2ce-upgraded/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:50
07:00:47 [DBC DBC-SD-Tests-EE] Stack trace:
07:00:47 [DBC DBC-SD-Tests-EE] #0 /var/www/magento2ce-upgraded/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
07:00:47 [DBC DBC-SD-Tests-EE] #1 /var/www/magento2ce-upgraded/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
07:00:47 [DBC DBC-SD-Tests-EE] #2 /var/www/magento2ce-upgraded/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
07:00:47 [DBC DBC-SD-Tests-EE] #3 /var/www/magento2ce-upgraded/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
07:00:47 [DBC DBC-SD-Tests-EE] #4 /var/www/magento2ce-upgraded/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Develop in /var/www/magento2ce-upgraded/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```

2020-09-09 10:15 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-09 10:28 UTC, lbajsarowicz reviewed
@engcom-Foxtrot Please take a look at the comments.

2020-09-09 10:28 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader.php
> +     * phpcs:disable Generic.CodeAnalysis.UselessOverridingMethod
`phpcs:ignore` works on documented scope - eg. if you add `phpcs:ignore` to the class - it's being ignored in whole class, if it's applied to method - it's applied to method only.

2020-09-09 10:28 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Communication/Config/Reader/XmlReader.php
> +    }
Whatever was hardcoded there, can't this be done with `di.xml` arguments?

2020-09-10 07:31 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-10 07:33 UTC, engcom-Foxtrot commented
@lbajsarowicz created a virtual type instead of real class.

2020-09-11 11:59 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-16 17:14 UTC, lenaorobei commented
@magento run all tests

2020-09-17 20:42 UTC, lenaorobei approved these changes, later dismissed

2020-09-18 17:41 UTC, lbajsarowicz commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2020-09-18 17:42 UTC, lbajsarowicz approved these changes, later dismissed
✔️  I see no more issues with the code.

2020-09-18 17:43 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8232](https://jira.corp.magento.com/browse/ENGCOM-8232) has been created to process this Pull Request

2020-09-30 07:47 UTC, engcom-Delta requested changes
Hi @matiashidalgo . I have tested PR changes and looks like issue is not fixed
**Manual testing scenario:**

- Add to env.php records:
```
'cron_consumers_runner' => [
        'cron_run' => true,
        'max_messages' => 20000,
        'consumers' => [
            'product_action_attribute.update',
        ]
    ],
```
- Add additional handlers for request into app/code/Magento/Catalog/etc/communication.xml
```
<topic name="product_action_attribute.update" request="Magento\AsynchronousOperations\Api\Data\OperationInterface">
        <handler name="product_action_attribute.update" type="Magento\Catalog\Model\Attribute\Backend\Consumer" method="process" />
        <handler name="product_action_attribute.update1" type="Magento\Catalog\Model\Attribute\Backend\Consumer1" method="process" />
    </topic>
```

- Add logger into handler
- - For Consumer.php:
`$this->logger->info('Original consumer runs.');`
- - For Consumer1.php:
`$this->logger->info('Second consumer runs.');`

- Go to Products grid
- Select some products using checkbox
- Choose Actios->Update Attributes
- Update Product Name and Price
- Click Save
- Run `cron:run` twice
- Open log file( in my case system.log )

**Result:**
:x: Log contains record `Original consumer runs.` only from first handler `product_action_attribute.update`. 
![image](https://user-images.githubusercontent.com/51681379/94656526-d9956380-0308-11eb-95de-195a2c0238bf.png)

Could you take a look if steps are correct or something is missed?

2020-10-13 19:53 UTC, matiashidalgo commented
@engcom-Delta Thanks for your test, but it is actually incorrect, when you run a consumer it took as reference queue_consumer.xml file, and it works fine if you add a line like this one:
`<consumer name="product_action_attribute.update.two" queue="product_action_attribute.update" connection="db" maxMessages="5000" consumerInstance="Magento\Framework\MessageQueue\Consumer" handler="Magento\Catalog\Model\Attribute\Backend\ConsumerTwo::process" />`
to the file **app/code/Magento/Catalog/etc/queue_consumer.xml**, despite it works it doesn't have nothing to do with communication.xml merging process, so such test will not prove that our changes fix the issue.

Please do let me know if you have any question about it.

2020-10-22 14:50 UTC, lbajsarowicz commented
@engcom-Delta Could you take a look at the answer from @matiashidalgo ?

2020-10-28 07:59 UTC, engcom-Delta commented
@lbajsarowicz @@matiashidalgo sorry for delay. I checked scenario according [comment](https://github.com/magento/magento2/pull/28926#issuecomment-707971913) and seems like only consumer `product_action_attribute.update.two` was run as it was included last
**Manual testing scenario:**
- Add to env.php records:
```
'cron_consumers_runner' => [
        'cron_run' => true,
        'max_messages' => 20000,
        'consumers' => [
            'product_action_attribute.update',
            'product_action_attribute.update.two',
        ]
    ],
```
- Add additional consumer into app/code/Magento/Catalog/etc/queue_consumer.xml
```
<consumer name="product_action_attribute.update.two" queue="product_action_attribute.update" connection="db" maxMessages="5000" consumerInstance="Magento\Framework\MessageQueue\Consumer" handler="Magento\Catalog\Model\Attribute\Backend\Consumer1::process" />
```

- Add logger into handler
- - For Consumer.php:
`$this->logger->info('Original consumer runs.');`
- - For Consumer1.php:
`$this->logger->info('Second consumer runs.');`

- Go to Products grid
- Select some products using checkbox
- Choose Actios->Update Attributes
- Update Product Name and Price
- Click Save
- Run `cron:run` twice
- Open log file

**Result:**
:x: Log contains record `Second consumer runs.` from last included consumer `product_action_attribute.update.two` 
![#28926PRLogs](https://user-images.githubusercontent.com/51681379/97407835-f1f69f00-1903-11eb-9919-1f6aa9a9c14f.png)

Could you provide manual testing scenario that helps verify your changes?

2020-11-13 09:59 UTC, engcom-Charlie commented
@matiashidalgo I suppose that you fixed the next scenario:
1. Create sample `ModuleA` with `communication.xml`
```
<topic name="product_action_attribute.update" request="Magento\AsynchronousOperations\Api\Data\OperationInterface">
    <handler name="handler.moduleA" type="Magento\Catalog\Model\Attribute\Backend\Consumer" method="process" />
</topic>
```
2. Create sample `ModuleB` with `communication.xml`
```
<topic name="product_action_attribute.update" request="Magento\AsynchronousOperations\Api\Data\OperationInterface">
    <handler name="handler.moduleB" type="Magento\Catalog\Model\Attribute\Backend\Consumer" method="process" />
</topic>
```
3. Clean cache `config`
4. Make the following
```
$reader = ObjectManager::getInstance()->create(\Magento\Framework\Communication\Config\Reader\XmlReader::class);
$result = $reader->read();
```

**Before changes**
we can see only one handler for `product_action_attribute.update` topic

**After changes**
for `product_action_attribute.update` topic we can see previously created handlers

- `handler.moduleA`
- `handler.moduleB`

2020-11-13 13:36 UTC, matiashidalgo commented
> @matiashidalgo I suppose that you fixed the next scenario:
> 
> 1. Create sample `ModuleA` with `communication.xml`
> 
> ```
> <topic name="product_action_attribute.update" request="Magento\AsynchronousOperations\Api\Data\OperationInterface">
>     <handler name="handler.moduleA" type="Magento\Catalog\Model\Attribute\Backend\Consumer" method="process" />
> </topic>
> ```
> 
> 1. Create sample `ModuleB` with `communication.xml`
> 
> ```
> <topic name="product_action_attribute.update" request="Magento\AsynchronousOperations\Api\Data\OperationInterface">
>     <handler name="handler.moduleB" type="Magento\Catalog\Model\Attribute\Backend\Consumer" method="process" />
> </topic>
> ```
> 
> 1. Clean cache `config`
> 2. Make the following
> 
> ```
> $reader = ObjectManager::getInstance()->create(\Magento\Framework\Communication\Config\Reader\XmlReader::class);
> $result = $reader->read();
> ```
> 
> **Before changes**
> we can see only one handler for `product_action_attribute.update` topic
> 
> **After changes**
> for `product_action_attribute.update` topic we can see previously created handlers
> 
> * `handler.moduleA`
> * `handler.moduleB`

Exactly, this is a correct test @engcom-Charlie

2020-11-13 13:43 UTC, engcom-Charlie commented
@matiashidalgo could you please resolve the merge conflict?
Thank you.

2020-11-13 13:46 UTC, matiashidalgo commented
> @matiashidalgo could you please resolve the merge conflict?
> Thank you.

Conflicts resolved! @engcom-Charlie Thank you too!

2020-11-13 13:46 UTC, engcom-Charlie commented
@magento run all tests

2020-11-16 12:13 UTC, gabrieldagama commented
@magento run all tests

2020-11-17 14:29 UTC, gabrieldagama commented
@magento run Functional Tests CE, WebAPI Tests

2020-11-17 16:46 UTC, matiashidalgo commented
@magento run Functional Tests CE

2020-11-17 19:54 UTC, matiashidalgo commented
@engcom-Charlie @gabrieldagama all checks passed now. 

Please do let me know if something else is needed from me.

2020-11-18 09:33 UTC, gabrieldagama approved these changes
Hi @matiashidalgo, thanks for your contribution, the changes look good to me!

2020-11-18 09:34 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8232](https://jira.corp.magento.com/browse/ENGCOM-8232) has been created to process this Pull Request

2020-11-18 14:22 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
Was checked case from Manual testing scenarios
:x: Before:
![#28926Main](https://user-images.githubusercontent.com/51681379/99541966-25d05c00-29ba-11eb-860f-506fc1b4944f.png)

:heavy_check_mark: After:
![#28926PR](https://user-images.githubusercontent.com/51681379/99541975-2a951000-29ba-11eb-982f-39ccf66af634.png)

2020-11-18 14:28 UTC, engcom-Delta commented
**Note:** Automation tests are passed

2020-12-10 12:42 UTC, merged