Fix return type in getCustomerIsGuest method.
magento/magento2 pull request #28920
Opened 2020-06-29 12:54 UTC by luisdev1

**Description**

The method "**_getCustomerIsGuest_**" returned a value of type string ("0" or "1") making the comparison of this method within the **_CheckCartCheckoutAllowance_** class always return true, because the comparison is Boolean.

**Manual testing**

Send a GraphQl request with the mutations "_setShippingAddressesOnCart_" or "_setPaymentMethodOnCart_", testing with the logged in customer or not, and follow the behavior of the **_CheckCartCheckoutAllowance_** class of the "**execute**" method.

2020-06-30 15:10 UTC, luisdev1 commented
@magento give me test instance
@magento give me 2.4-develop instance
@magento run all tests

2020-06-30 15:11 UTC, magento-engcom-team commented
Hi @luisdev1. Thank you for your request. I'm working on Magento instance for you

2020-06-30 15:12 UTC, magento-engcom-team commented
Hi @luisdev1, here is your [new Magento instance](https://pr-28920.instances.magento-community.engineering).
Admin access: [https://pr-28920.instances.magento-community.engineering/admin_5421](https://pr-28920.instances.magento-community.engineering/admin_5421)
Login: `3516da4e` Password: `7dd0942aa3e1`
Instance will be terminated in up to 3 hours.

2020-06-30 18:08 UTC, luisdev1 commented
@magento WebAPI Tests

2020-07-25 23:30 UTC, luisdev1 commented
@lbajsarowicz @eduard13 Can you check this correction? Thank you so much friends.

2020-07-25 23:32 UTC, lbajsarowicz reviewed
There is an easier way, in my opinion.

2020-07-25 23:32 UTC, lbajsarowicz commented on app/code/Magento/QuoteGraphQl/Model/Cart/CheckCartCheckoutAllowance.php
> +        if (false === (bool)$quote->getCustomerIsGuest()) {
Why not easier:
```suggestion
        if (!$quote->getCustomerIsGuest()) {
```

2020-07-25 23:38 UTC, luisdev1 commented
@lbajsarowicz Yes you are right! Thank you very much, I updated the pull request.

2020-07-25 23:39 UTC, lbajsarowicz commented
@magento run all tests

Just for formal purposes.

2020-07-25 23:50 UTC, lbajsarowicz submitted a review, later dismissed
That is a minor change that does not need additional automated tests to be written.

2020-07-25 23:51 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7884](https://jira.corp.magento.com/browse/ENGCOM-7884) has been created to process this Pull Request

2020-07-25 23:51 UTC, magento-engcom-team commented
@luisdev1 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-07-25 23:59 UTC, luisdev1 commented
@lbajsarowicz Thanks for the assistance and follow-up!

2020-08-13 20:24 UTC, sidolov commented
@magento create issue

2020-08-18 15:04 UTC, lenaorobei requested changes
I think that this approach is not the proper way of handling such issues. As per contract interface method `getCustomerIsGuest` returns `bool`. In case if contract is broken somewhere, we need to identify this place and fix there.

2020-09-01 21:18 UTC, lenaorobei commented
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

2020-09-01 21:18 UTC, closed without merging

2020-09-10 15:56 UTC, luisdev1 commented
@lenaorobei Hello Lena Orobei! You all right?

I believe that maybe I can keep this change, because it is a validation of only true or false (1 or 0 is what is being returned by the method as the string type), however the "if" placed in the code contemplates the situation. What do you think about this?

2020-09-10 16:18 UTC, lenaorobei commented
Hi @luisdev1. I think we need to to keep strict comparison where it is possible.
Such changes may lead to destructive security violations.

2020-09-10 16:35 UTC, lbajsarowicz commented
@lenaorobei This does not resolve the issue reported by OP.
@luisdev1  Could you create an issue that describes the use-cases when you get `"0"` and `"1"` and assign directly to @lenaorobei to address that internally?

2020-09-10 16:36 UTC, luisdev1 commented
I understand @lenaorobei . The method is found in the Quote class.

Would it be the case that we add a conversion in the return of the method?

File: app/code/Magento/Quote/Model/Quote.php
Line: 705

public function getCustomerIsGuest ()
{
     return (bool) $ this -> _ getData (self :: KEY_CUSTOMER_IS_GUEST);
}