magento/magento2#28957: GraphQl. Mutation: customerOrders query and gift_message attribute
magento/magento2 pull request #28958
Opened 2020-07-01 13:55 UTC by atwixfirster

…ft_message attribute

### Description (*)

PR fixes https://github.com/magento/magento2/issues/28957

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento228957: GraphQl. Mutation: customerOrders query and gift_message attribute

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-01 14:17 UTC, atwixfirster commented
@magento run all tests

2020-07-01 21:12 UTC, atwixfirster commented
@magento run Database Compare

2020-07-01 21:12 UTC, atwixfirster commented
@magento run WebAPI Tests

2020-07-01 21:13 UTC, atwixfirster commented
@magento run Unit Tests

2020-07-01 21:13 UTC, atwixfirster commented
@magento Static Tests

2020-07-01 21:55 UTC, atwixfirster commented
@magento run Semantic Version Checker

2020-07-01 21:55 UTC, atwixfirster commented
@magento run Functional Tests B2B

2020-07-01 21:56 UTC, atwixfirster commented
@magento run Sample Data Tests EE  Sample Data Tests CE Sample Data Tests B2B Magento Health Index

2020-07-03 10:54 UTC, dmytro-ch requested changes
Hello @atwixfirster, thank you for your contribution.
The overall changes look good to me.
Could you please cover this case by an appropriate functional test?

2020-10-06 12:06 UTC, sivaschenko commented
Hi @nrkapoor , what is the reason for putting this PR on hold? Should it be processed according to priority or any additional actions are required?

2020-10-06 13:32 UTC, sivaschenko commented
`customerOrders` query is `deprecated`: https://github.com/magento/magento2/blob/8b1d1184e67f31268a38cb8ec281e6c48b33d43d/app/code/Magento/SalesGraphQl/etc/schema.graphqls#L5

Need to check if the issue is reproducible with `customer orders` and update the issue and PR testing steps accordingly

2022-05-06 13:51 UTC, cpartica requested changes

2022-05-06 13:51 UTC, cpartica commented on app/code/Magento/GiftMessageGraphQl/Model/Resolver/Order/GiftMessage.php
> +        if (!$orderGiftMessage->getGiftMessageId()) {
I think this change needs a test

2022-05-25 06:23 UTC, engcom-Alfa commented
We raised internal PR- https://github.com/magento-gl/magento2ce/pull/290 along with this PR commits, covering the automation tests and resolved PR comments.
Once Internal PR will get merged will notify here

2022-05-30 19:50 UTC, merged