WIP Scheduled price rule time zone correction
magento/magento2 pull request #28973
Opened 2020-07-02 16:04 UTC by AntonEvers

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-02 16:08 UTC, AntonEvers commented
@magento run Unit Tests
@magento run Static Tests

2020-07-03 09:32 UTC, AntonEvers commented
@magento run all tests

2020-07-03 19:26 UTC, AntonEvers commented
@magento run all tests

2020-07-16 11:04 UTC, AntonEvers commented
@magento run all tests

2020-08-14 20:24 UTC, sidolov commented
@magento create issue

2020-08-19 19:01 UTC, sidolov requested changes
Please, cover your changes with any kind of automated tests.

2020-08-19 19:01 UTC, sidolov commented on app/code/Magento/CatalogRule/Model/Indexer/IndexBuilder.php
> +            $scopeTz = new \DateTimeZone(
Please, use framework TimeZone and DateTime object instead of generic PHP.

2020-08-21 14:58 UTC, AntonEvers commented on app/code/Magento/CatalogRule/Model/Indexer/IndexBuilder.php
> +            $this->doReindexByIds([$id]);
This is the main change in this file, the rest is removal of unused private methods (containing also duplicate code) after this change and adding of imports.

2020-08-21 14:59 UTC, AntonEvers commented on app/code/Magento/CatalogRule/Model/Indexer/IndexBuilder.php
> +            $scopeTz = new \DateTimeZone(
I have removed the entire method, as it appears to be duplicate code. Instead I have done this: https://github.com/magento/magento2/pull/28973/files#r474752002

2020-08-21 14:59 UTC, AntonEvers commented
@magento run all tests

2020-08-26 06:52 UTC, engcom-Charlie commented
Hi, @AntonEvers could you please merge conflict and cover changes with the automated tests?
Thank you.

2020-09-09 13:27 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-10 10:29 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-11 12:06 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-11 13:03 UTC, AntonEvers commented
> Hi, @AntonEvers could you please merge conflict and cover changes with the automated tests?
> Thank you.

Hi @engcom-Foxtrot, I think we are good to go right? I cannot add tests, as I only removed code. So the tests that are already in place should cover the scenarios that need testing.

There are no conflicts anymore. If anything more needs to be done on this PR, please let me know.

2020-09-16 11:40 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-17 07:40 UTC, engcom-Foxtrot commented
Hello, @AntonEvers. Thank you for collaboration. 

> So the tests that are already in place should cover the scenarios that need testing.
In this case, such scenarios should be permanently failing on the 2 .4-develop branch without your fix, but they are not. So we don't have any scenario that covers your fix.

2020-10-01 11:00 UTC, engcom-Foxtrot commented
Hello, @AntonEvers. Would you like to continue with this PR?

2020-12-29 14:54 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-05 16:21 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-08 15:25 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-11 12:28 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-12 13:14 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-12 16:07 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-13 11:56 UTC, engcom-Foxtrot commented
@magento run all tests

2021-02-01 16:00 UTC, gabrieldagama requested changes
Hi @engcom-Foxtrot, let's try to use the framework TimeZone and DateTime object instead of generic PHP.

2021-02-12 14:32 UTC, engcom-Foxtrot commented
> Hi @engcom-Foxtrot, let's try to use the framework TimeZone and DateTime object instead of generic PHP.

I didn't find any suitable way to do it. Created issue https://github.com/magento/magento2/issues/31968.

2021-02-18 14:28 UTC, gabrieldagama approved these changes

2021-02-18 14:29 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8785](https://jira.corp.magento.com/browse/ENGCOM-8785) has been created to process this Pull Request

2021-02-19 14:41 UTC, gabrieldagama commented
@magento run all tests

2021-02-19 15:28 UTC, engcom-Bravo requested changes
:x: QA Failed

Switched to the PR and Performed the steps from the Manual Testing scenario
After the last step, still, only one row is displayed in the SQL query
![after](https://user-images.githubusercontent.com/51680745/108524526-cabf4580-72d7-11eb-9836-3847ae57eb03.png)

2021-03-05 14:00 UTC, engcom-Bravo commented
Further investigation discovered that the previous comment https://github.com/magento/magento2/pull/28973#pullrequestreview-594297440 is actually the Expected behavior

:heavy_check_mark: QA Passed

### Manual testing scenario
1. Set time zone to Europe/Amsterdam
2. Set indexers to scheduled
3. Deleta all present Catalog Price Rules
4. Create a Catalog Price Rule for 50% off on all products, but disabled
5. Schedule the price rule to be enabled at a minute or so in the future using catalog staging
6. Wait until catalog stating rules are active and indexer is up to date
7. Run this query: `SELECT DISTINCT from_time, to_time FROM catalogrule_product;`
8. It should output only one row, after all, the rule is applied on all product at the same time.
9. Install [app.zip](https://github.com/magento/magento2/files/4868883/app.zip)
10. Run `bin/magento reindex:product 10`
11. Run this query: `SELECT DISTINCT from_time, to_time FROM catalogrule_product;`

**Actual Result**
Only one row is displayed in the SQL query
![after](https://user-images.githubusercontent.com/51680745/108524526-cabf4580-72d7-11eb-9836-3847ae57eb03.png)

2021-03-18 17:18 UTC, merged