fix Invisible products do not update url_rewrite properly
magento/magento2 pull request #29069
Opened 2020-07-10 10:09 UTC by engcom-Charlie

### Description (*)

Fixed and covered by test

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#19293

### Manual testing scenarios (*)

1.see #19293

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-10 10:09 UTC, engcom-Charlie commented
@magento run all tests

2020-07-10 10:50 UTC, engcom-Charlie commented
@magento run all tests

2020-07-10 11:30 UTC, engcom-Charlie commented
@magento run all tests

2020-07-14 06:11 UTC, ihor-sviziev requested changes

2020-07-14 06:11 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
> + * @deprecated Url rewrites will be created for products with all visibility types.
I think this comment isn't clear that this observer will be never called. Also not clear where url rewrites will be created. I thing we need to add something like this:
```suggestion
 * @deprecated Class is not used anymore. Url rewrites will be created for products with all visibility types.
 * @see \Magento\CatalogUrlRewrite\Observer\ProductProcessUrlRewriteSavingObserver
```

2020-07-14 06:11 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
> + * @deprecated Url rewrites will be created for products with all visibility types.
```suggestion
 * @deprecated Class isn't used anymore. Url rewrites will be created for products with all visibility types.
 * @see \Magento\CatalogUrlRewrite\Observer\ProductProcessUrlRewriteSavingObserver
```

2020-07-14 06:11 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php
> +            ?: ObjectManager::getInstance()->get(ProductUrlPathGenerator::class);
backward compatibility policy is not needed for observers, I think we can make this argument not optional

2020-07-14 06:11 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGeneratorTest.php
>              function ($url) {
Can we define argument and return types here?

2020-07-14 06:13 UTC, ihor-sviziev commented
Also please review failed tests, looks like some additional tests should be adjusted

2020-07-21 13:19 UTC, ihor-sviziev commented
@magento run all tests

2020-07-22 15:21 UTC, ihor-sviziev commented
@engcom-Charlie tests still failing, please check it

2020-07-29 06:18 UTC, ihor-sviziev reviewed
@engcom-Charlie tests still failing, please check it

2020-07-29 06:18 UTC, ihor-sviziev requested changes
@engcom-Charlie tests still failing, please check it

2020-08-14 13:14 UTC, ihor-sviziev commented
@engcom-Charlie will you be able to update your PR?

2020-08-17 05:51 UTC, ihor-sviziev commented
@engcom-Charlie  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-08-18 13:10 UTC, engcom-Hotel commented
@magento run all tests

2020-08-19 05:56 UTC, ihor-sviziev requested changes
@engcom-Charlie @engcom-Hotel 
My review comments still actual, please update the PR https://github.com/magento/magento2/pull/29069#pullrequestreview-447810292

2020-08-19 07:19 UTC, engcom-Charlie commented
@ihor-sviziev can you please look through again? I've done it on by https://github.com/magento/magento2/pull/29069/commits/67a691e773a9b6003149885c2afcf6ee133f0816

2020-08-19 08:02 UTC, ihor-sviziev commented
@engcom-Charlie yeah, now I resolved all the issues I found, but still tests fails, please review them

2020-08-19 08:11 UTC, engcom-Charlie commented
@ihor-sviziev we will fix failed tests.

2020-08-19 10:16 UTC, engcom-Hotel commented
@magento run all tests

2020-08-25 10:33 UTC, ihor-sviziev commented
@magento WebAPI Tests, Integration Tests

2020-08-25 10:34 UTC, ihor-sviziev commented
@magento run WebAPI Tests, Integration Tests

2020-08-27 03:55 UTC, ihor-sviziev commented
@magento run WebAPI Tests, Integration Tests

2020-08-31 10:54 UTC, engcom-Hotel commented
@magento run Integration Tests

2020-09-01 07:33 UTC, engcom-Hotel commented
@magento run integration tests

2020-09-01 07:34 UTC, engcom-Hotel commented
@magento run Integration Tests

2020-09-01 09:21 UTC, engcom-Hotel commented
@magento run Integration Tests

2020-09-02 08:55 UTC, engcom-Hotel commented
@magento run all tests

2020-09-04 07:06 UTC, engcom-Hotel commented
@magento run all tests

2020-09-10 12:04 UTC, engcom-Hotel commented
@magento run all tests

2020-09-11 08:10 UTC, gabrieldagama commented
@magento run all tests

2020-09-11 12:11 UTC, engcom-Hotel commented
@magento run all tests

2020-09-14 06:13 UTC, engcom-Hotel commented
@magento run WebAPI Tests, Functional Tests

2020-09-14 06:13 UTC, engcom-Hotel commented
@magento run WebAPI Tests, Functional Tests

2020-09-15 05:51 UTC, engcom-Hotel commented
@magento run all tests

2020-09-17 06:31 UTC, engcom-Hotel commented
@magento run all tests

2020-09-22 07:41 UTC, ihor-sviziev commented
@engcom-Charlie @engcom-Hotel any updates?

2020-09-22 17:26 UTC, engcom-Hotel commented
@magento run all tests

2020-09-23 06:50 UTC, engcom-Hotel commented
@magento run Static Tests

2020-09-23 11:09 UTC, ihor-sviziev commented
@magento run WebAPI Tests, Functional Tests

2020-09-23 11:11 UTC, ihor-sviziev commented
@magento run Integration Tests

2020-09-24 10:11 UTC, ihor-sviziev commented
@sidolov @gabrieldagama could you add some info why integration & web api tests are failing? There is no info in the reports

2020-09-24 20:20 UTC, sidolov commented
```
...........Error in fixture: "\/var\/www\/html\/app\/code\/Magento\/InventoryConfigurableProductIndexer\/Test\/_files\/product_configurable_multiple.php".
 URL key for specified store already exists.
 #0 /var/www/html/app/code/Magento/UrlRewrite/Model/Storage/AbstractStorage.php(87): Magento\UrlRewrite\Model\Storage\DbStorage->doReplace()
#1 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\UrlRewrite\Model\Storage\AbstractStorage->replace()
#2 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->___callParent()
#3 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/html/dev/tests/integration/tmp/sandbox--76ccf56fc1cd540134f59b4069e60caaa4132cb3976271c3398ab8e1c4c45409/generated/code/Magento/UrlRewrite/Model/Storage/DbStorage/Interceptor.php(50): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->___callPlugins()
#5 /var/www/html/app/code/Magento/CatalogStaging/Model/Url/Storage.php(56): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->replace()
#6 /var/www/html/app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php(72): Magento\CatalogStaging\Model\Url\Storage->replace()
#7 /var/www/html/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(88): Magento\CatalogUrlRewrite\Observer\ProductProcessUrlRewriteSavingObserver->execute()
#8 /var/www/html/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#9 /var/www/html/app/code/Magento/Staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#10 /var/www/html/dev/tests/integration/tmp/sandbox--76ccf56fc1cd540134f59b4069e60caaa4132cb3976271c3398ab8e1c4c45409/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch()
#11 /var/www/html/lib/internal/Magento/Framework/Model/AbstractModel.php(829): Magento\Staging\Model\Event\Manager\Proxy->dispatch()
#12 /var/www/html/app/code/Magento/Catalog/Model/Product.php(973): Magento\Framework\Model\AbstractModel->afterSave()
#13 /var/www/html/dev/tests/integration/tmp/sandbox--76ccf56fc1cd540134f59b4069e60caaa4132cb3976271c3398ab8e1c4c45409/generated/code/Magento/Catalog/Model/Product/Interceptor.php(248): Magento\Catalog\Model\Product->afterSave()
#14 /var/www/html/lib/internal/Magento/Framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave()
#15 /var/www/html/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute()
#16 /var/www/html/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#17 /var/www/html/app/code/Magento/Staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#18 /var/www/html/dev/tests/integration/tmp/sandbox--76ccf56fc1cd540134f59b4069e60caaa4132cb3976271c3398ab8e1c4c45409/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch()
#19 /var/www/html/lib/internal/Magento/Framework/EntityManager/EventManager.php(51): Magento\Staging\Model\Event\Manager\Proxy->dispatch()
#20 /var/www/html/app/code/Magento/Staging/Model/Operation/Create.php(138): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent()
#21 /var/www/html/lib/internal/Magento/Framework/EntityManager/EntityManager.php(96): Magento\Staging\Model\Operation\Create->execute()
#22 /var/www/html/app/code/Magento/Catalog/Model/ResourceModel/Product.php(764): Magento\Framework\EntityManager\EntityManager->save()
#23 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save()
#24 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent()
#25 /var/www/html/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/html/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback()
#27 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave()
#28 /var/www/html/lib/internal/Magento/Framework/App/Cache/FlushCacheByTags.php(69): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#29 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave()
#30 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#31 /var/www/html/dev/tests/integration/tmp/sandbox--76ccf56fc1cd540134f59b4069e60caaa4132cb3976271c3398ab8e1c4c45409/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(194): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins()
#32 /var/www/html/app/code/Magento/Catalog/Model/ProductRepository.php(823): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save()
#33 /var/www/html/app/code/Magento/Catalog/Model/ProductRepository.php(572): Magento\Catalog\Model\ProductRepository->saveProduct()
#34 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ProductRepository->save()
#35 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ProductRepository\Interceptor->___callParent()
#36 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}()
#37 /var/www/html/dev/tests/integration/tmp/sandbox--76ccf56fc1cd540134f59b4069e60caaa4132cb3976271c3398ab8e1c4c45409/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(41): Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins()
#38 /var/www/html/app/code/Magento/InventoryConfigurableProductIndexer/Test/_files/product_configurable_multiple.php(67): Magento\Catalog\Model\ProductRepository\Interceptor->save()
#39 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/AbstractDataFixture.php(87): require('/var/www/html/a...')
#40 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/AbstractDataFixture.php(121): Magento\TestFramework\Annotation\AbstractDataFixture->_applyOneFixture()
#41 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(35): Magento\TestFramework\Annotation\AbstractDataFixture->_applyFixtures()
#42 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTestTransactionRequest()
#43 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array()
#44 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(76): Magento\TestFramework\EventManager->fireEvent()
#45 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests()
#46 [internal function]: Magento\TestFramework\Event\Transaction->startTest()
#47 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array()
#48 /var/www/html/dev/tests/int [...]

2020-09-25 07:42 UTC, ihor-sviziev commented
Hi @engcom-Charlie @engcom-Hotel I believe now it will be much easier to understand where the issue is.

2020-09-28 08:10 UTC, engcom-Hotel commented
@magento run Integration Tests

2020-09-28 10:53 UTC, engcom-Hotel commented
@magento run all tests

2020-09-28 14:38 UTC, gabrieldagama commented
@magento run Integration Tests,WebAPI Tests

2020-09-28 20:41 UTC, engcom-Hotel commented
@magento run Integration Tests,WebAPI Tests

2020-09-29 06:17 UTC, engcom-Hotel commented
@magento run all tests

2020-09-29 08:54 UTC, gabrieldagama commented
@magento run all tests

2020-09-29 13:06 UTC, engcom-Hotel commented
@magento run Integration Tests,WebAPI Tests

2020-09-30 06:37 UTC, ihor-sviziev requested changes
Hi @engcom-Charlie @engcom-Hotel 
seems like these changes are causing regression issues as you have to add some specific url key, but it will not be added also in the custom extensions -> websites will become broken.
Do we have any other option in order NOT to add these URL keys?

2020-09-30 12:39 UTC, engcom-Hotel commented
@magento run Integration Tests

2020-10-01 07:02 UTC, engcom-Hotel commented
@magento run Integration Tests, WebAPI Tests

2020-10-02 09:25 UTC, engcom-Hotel commented
I have reviewed the provided solution and found that it causes a critical issue with url_key for invisible products. It is not suitable and too risky to make such changes. PR will be closed.
Please feel free to reopen it back if you disagree or have an alternative solution.
Thank you.

2020-10-02 13:18 UTC, closed without merging