Introduce SearchAssets service
magento/magento2 pull request #29071
Opened 2020-07-10 11:55 UTC by Nazar65

### Description (*)

This service is responsible for search media assets by searchCriteria filters

### Related Pull Requests
https://github.com/magento/adobe-stock-integration/pull/1587

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1502: add asset filter to category grid

### Manual testing scenarios (*)
1.Open Category grid page by link `admin/media_gallery_catalog/category/index`
2. Expand Filters tab
3. Start typing asset titile in Asset filter input

![Screenshot_2020-07-10 Categories Magento Admin](https://user-images.githubusercontent.com/2481206/87150062-0d3c9080-c2ba-11ea-8b8a-2359f153d198.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-10 11:55 UTC, Nazar65 commented
@magento run all tests

2020-07-10 12:04 UTC, sivaschenko requested changes
Thanks for the pull request @Nazar65 ! Please see my comments

2020-07-10 12:04 UTC, sivaschenko commented on app/code/Magento/MediaGalleryApi/Api/SearchAssetsInterface.php
> +     * @return AssetInterface[]
let's return the assets search result interface for the consistency with other search services

2020-07-10 12:04 UTC, sivaschenko commented on app/code/Magento/MediaGalleryApi/Api/SearchAssetsInterface.php
> + * @api
please remove the api annotation

2020-07-10 12:04 UTC, sivaschenko commented on app/code/Magento/MediaGallery/Model/ResourceModel/SearchAssets.php
> +    private function getAssetsData(SearchCriteriaInterface $searchCriteria): SearchResultInterface
please extract SeachCriteria processing to a separate ResourceModel class (while the main service implementation class can be in the Model namespace)

2020-07-13 10:52 UTC, Nazar65 commented
@magento run all tests

2020-07-13 11:01 UTC, Nazar65 commented
@magento run all tests

2020-07-13 11:28 UTC, Nazar65 commented
@magento run all tests

2020-07-13 11:47 UTC, sivaschenko approved these changes

2020-07-13 11:48 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7827](https://jira.corp.magento.com/browse/ENGCOM-7827) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-07-14 06:58 UTC, lbajsarowicz commented
Nice feature, @Nazar65 :clap:

2020-07-14 08:15 UTC, Nazar65 commented
@magento run all tests

2020-07-14 14:58 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

Test scenario on cucumber studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4951024

2020-07-16 01:37 UTC, merged