Single store mode incorrect scope values in plp fix
magento/magento2 pull request #29091
Opened 2020-07-13 14:36 UTC by muthu-ziffity

### Description (*)

In the category page, In single store mode Show per page section doesn't get the value from admin properly. Now it got fixed in this Pull Request

### Fixed Issue

1. Fixes magento/magento2#25933

### Reference for the fix

![pageView](https://user-images.githubusercontent.com/32055149/87314909-741fab00-c541-11ea-8809-1fb579a5073d.gif)

2020-07-14 06:54 UTC, lbajsarowicz requested changes
Thank you for your contribution. Please review the comments.

2020-07-14 06:54 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Config.php
>   */
Just remove that redundant annotation

2020-07-14 06:54 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Config.php
> +     */
`const` does not require annotations. This annotation does not bring any value.

2020-07-14 06:54 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Config.php
> +    public $isSingleStoreModeEnabled;
1. That should not be public property (change to private)
2. Add PHPDoc for the property

2020-07-14 06:54 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Config.php
> +     * @return mixed
Return type of all `is...` methods should be `bool`

2020-07-14 06:54 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/App/Config.php
> +        return $scope;
The method does not return information whether it's `Single Store Mode` or not.

2020-07-14 07:02 UTC, muthu-ziffity commented
@lbajsarowicz  Thanks for reviewing my PR. I will update those mentioned changes and let you know to check again

2020-08-05 07:41 UTC, engcom-Charlie commented
Hi @muthu-ziffity, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-08-05 07:41 UTC, closed without merging