magento/partners-magento2b2b#137: Add Company to Customers Now Online…
magento/magento2 pull request #29170
Opened 2020-07-16 12:45 UTC by rsaint20

… grid - Added MFTF action group to CE > UI Admin grid

### Description (*)

Added MFTF Actiongroup in CE in Ui module

- AdminAddColumnToAdminGridActionGroup
- AdminOpenColumnActionDropDownForAdminGridActionGroup

### Related Pull Requests

 #https://github.com/magento/partners-magento2b2b/pull/146

### Fixed Issues (if relevant)

1. Fixes magento/partners-magento2b2b#137

### Manual testing scenarios (*)

1. Navigate Admin -> Customers -> Now Online
2. Check if Company column is not displayed
3. Click Columns >  Check Company checkbox
4. Check Company Column is displayed between Lastname and Email column
5. Check if Company Column is sortable
6. Click Filters
7. Check if there is Company filter
8. Type company name
9. Click Apply Filter or  press enter
10. Result should display only the filtered values

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-17 13:10 UTC, dhaecker requested changes

2020-07-17 13:10 UTC, dhaecker commented on app/code/Magento/Ui/Test/Mftf/ActionGroup/AdminAddColumnToAdminGridActionGroup.xml
> +        <click selector="{{AdminGridColumnsControls.columns}}" stepKey="reOpenAdminGridColumnControlsColumn"/>
change stepKey to `closeAdminGridColumnControls`

2020-07-17 13:10 UTC, dhaecker commented on app/code/Magento/Ui/Test/Mftf/ActionGroup/AdminOpenColumnActionDropDownForAdminGridActionGroup.xml
> +    <actionGroup name="AdminOpenColumnActionDropDownForAdminGridActionGroup">
now that i'm reading your b2b test, i'm seeing that this actiongroup should be deleted. sorry for being wrong before! :(
please delete the file & move the 2 actions into `AdminAddColumnToAdminGridActionGroup` as the first 2 steps

2020-07-20 13:02 UTC, dhaecker approved these changes

2020-07-21 13:06 UTC, joanhe approved these changes

2020-07-29 21:29 UTC, merged