Always use canonical urls in the sitemap
magento/magento2 pull request #29184
Opened 2020-07-17 08:38 UTC by AntonEvers

### Description (*)

In Magento 2.3.3, a commit (https://github.com/magento/magento2/commit/e7c2e1f89a91f358548ac2527599684cb1ec8ea8) was introduced by @Vaha that make the sitemap use canonical urls for products, if the configuration option `catalog/seo/product_use_categories` is set to Yes.

This SEO setting, has an effect on `\Magento\Catalog\Model\Product\Url::getUrl` so it has a lot wider effect than just the sitemap.

Canonical URL tags on PDPs, however, don't take this setting into account and always produce urls without category paths. And rightfully so because otherwise we would be serving duplicate content.

The sitemap, I would argue, should direct search engines to the canonical url directly. Always. Not only based on this generic configuration setting. 

This PR aims to make the sitemap behave in a similar way to the canonical url generation.

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-17 08:39 UTC, AntonEvers commented
@magento run all tests

2020-07-18 15:16 UTC, lbajsarowicz requested changes
Please find another way to avoid `/category/` links as MySQL `LIKE` is going to kill the performance.

2020-07-18 15:16 UTC, lbajsarowicz commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +            . ' AND url_rewrite.target_path NOT LIKE "%/category/%"'
That might kill the performance. 
Isn't there any other way to get rid of these URLs?

2020-07-18 15:16 UTC, lbajsarowicz commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +     * @deprecated 100.4.0 unused
That are private properties, you can remove them without notice.

2020-07-18 15:16 UTC, lbajsarowicz commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +     * @deprecated 100.4.0 unused
That are private properties, you can remove them without notice.

2020-07-18 15:16 UTC, lbajsarowicz commented on app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php
> +     * @deprecated 100.4.0 unused
That are private properties, you can remove them without notice.

2020-07-19 09:35 UTC, hostep commented
@AntonEvers: will this fix the "first problem" of https://github.com/magento/magento2/issues/23363 ?

2020-07-20 08:07 UTC, AntonEvers commented
> @AntonEvers: will this fix the "first problem" of #23363 ?

@hostep before this PR:
```xml
<url>
<loc>https://magento2.test/category/product.html</loc>
<lastmod>2020-07-20T08:00:46+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>1.0</priority>
</url>
```

After this PR:
```xml
<url>
<loc>https://magento2.test/product.html</loc>
<lastmod>2020-07-20T08:00:46+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>1.0</priority>
</url>
```

So this indeed fixes  #23363

2020-07-20 08:08 UTC, AntonEvers commented
@magento run all tests

2020-07-23 07:48 UTC, AntonEvers commented
@magento run all tests

2020-08-06 13:37 UTC, AntonEvers commented
@magento run all tests

2020-08-06 13:39 UTC, AntonEvers commented
@magento run all tests

2020-08-06 16:05 UTC, AntonEvers commented
@lbajsarowicz Functional Tests EE fails are not caused by this PR

2020-08-20 15:35 UTC, sidolov requested changes
@AntonEvers could you please cover changes with automated tests?

2020-08-21 13:27 UTC, engcom-Charlie commented
@magento run all tests

2020-08-25 18:27 UTC, sidolov submitted a review, later dismissed

2020-08-25 18:28 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8071](https://jira.corp.magento.com/browse/ENGCOM-8071) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-08-25 18:32 UTC, sidolov commented
The new behavior should be clarified with PO since it affects SEO.

2020-08-25 18:46 UTC, hostep commented
@sidolov: please make sure the PO also reads all comments in https://github.com/magento/magento2/pull/23129 & https://github.com/magento/magento2/issues/23363 before forming an opinion.

Thanks!

2020-10-08 19:56 UTC, sivaschenko commented
Approval Request: https://jira.corp.magento.com/browse/MC-38323

2021-03-10 14:47 UTC, JoostWan commented
@AntonEvers Thanks for this fix. It's working fine but not for all products. In the case of our client there a some products with the wrong url in the sitemap with category paths. I checked the URL's in the database and the products with the wrong URL has 301 redirects in table `url_rewrite`. When i added some log to `public function getCollection($storeId)` the URL is good. But over here the URL is different with the categorie paths https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sitemap/Model/Sitemap.php#L462.

2021-05-07 14:21 UTC, sivaschenko commented
Approved in MC-38323

2021-06-25 13:13 UTC, merged