29200: Fix issue with non parsable time non UTC timezone
magento/magento2 pull request #29201
Opened 2020-07-19 15:20 UTC by sergeynezbritskiy

### Description (*)
Fix behavior of \Magento\Framework\Stdlib\DateTime\Timezone::date() method when working with date strings, non parsable by  \IntlDateFormatter class

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29200

### Manual testing scenarios (*)
1.Configure Magento instance to some non UTC locale, e.g. Go Magento admin -> Stores -> Settings -> General -> General -> Locale Options and set Timezone to some non UTC timezone, e.g. *Central Standard Time (America/Chicago)*
2. Get an instance of \Magento\Framework\Stdlib\DateTime\Timezone class
3. Call method with any time string, which can't be parsed by \IntlDateFormatter, e.g. *19th July 2020 9:30:00*, *Monday 08:00* etc.
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$timezone = $objectManager->create(\Magento\Framework\Stdlib\DateTime\Timezone::class);
$dateTime = $timezone->date('19th July 2019 09:30:00','en_US', 'en_US', true);
var_dump($dateTime);
```
## Expected result (*)
Returned datetime object should match to time in argument and affected by timezone. E.g. the result of the code snipped above should be like:
```
class DateTime#638 (3) {
  public $date => string(26) "2020-07-19 09:30:00.000000"
  public $timezone_type => int(3)
  public $timezone => string(15) "America/Chicago"
}
```
## Actual result (*)
1. Returned datetime object is actually for UTC timezone, but marked as for specific timezone, e.g.
```
class DateTime#638 (3) {
  public $date => string(26) "2020-07-19 04:30:00.000000" // UTC time
  public $timezone_type => int(3)
  public $timezone => string(15) "America/Chicago" //marked as Chicago time
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-20 13:37 UTC, sergeynezbritskiy commented
@magento run all tests

2020-07-23 19:46 UTC, sergeynezbritskiy commented
@magento run Functional Tests B2B

2020-07-23 20:14 UTC, sergeynezbritskiy commented
@magento run all tests

2020-07-24 07:24 UTC, sergeynezbritskiy commented
@magento run Functional Tests CE

2020-07-24 10:19 UTC, sergeynezbritskiy commented
@magento run Functional Tests CE

2020-07-24 11:52 UTC, sergeynezbritskiy commented
@magento run Functional Tests CE

2020-07-24 20:15 UTC, sergeynezbritskiy commented
@magento run Functional Tests CE

2020-07-26 19:04 UTC, sergeynezbritskiy commented
@magento run all tests

2020-08-17 16:23 UTC, lenaorobei requested changes
Hi @sergeynezbritskiy,

Could you please check failed tests? Looks like it was caused by your changes.

Thanks.

2020-08-26 06:15 UTC, engcom-Charlie commented
Hi @sergeynezbritskiy,
Could you please check failed tests? Otherwise, we can't proceed with your PR.
Thank you.

2020-09-01 16:58 UTC, gabrieldagama commented
Hi @sergeynezbritskiy, I believe the behavior on this may be correct. After some investigation, the function is actually returning a converted time for the `America/Chicago` timezone, so, the function assumes that the string that is being provided as the date is on `UTC` timezone and makes the conversion to the one provided by the system. That is why you get a result with 5 hours before (`America/Chicago` is 5 hours earlier than `UTC`).

You would have the same behavior with `DateTime` class on PHP unless timezone is provided on constructor.
```
<?php

$tz = new DateTimeZone('America/Chicago');

$date = new DateTime('19th July 2019 09:30:00');
$date->setTimezone($tz);
echo $date->format('l F j Y g:i:s A I')."\n";
```

So, following these steps DateTime assumes that the string provided is on `UTC` and then converts it to the requested timezone, the same for the method provided by the framework. I guess if you want to have the date provided already being on the correct timezone, you must create the `DateTime` object with the timezone on it's constructor.

Please let me know your thoughts on this.

2020-09-03 07:18 UTC, sergiynezbritskiy commented
> the function assumes that the string that is being provided as the date is on `UTC` timezone and makes the conversion to the one provided by the system

Hi @gabrieldagama thanks for looking on this issue. This is not possible to provide for some time strings.
Let me show you what is wrong on some another example.
I have an offline store in Tbilisi (Georgia) and there are working hours set in admin for this store. And need to provide customer with an information, if the store is currently open or closed. If  we skip the details and nuances, the code looks like this:
```
//this line returns DateTime object with timezone Asia/Tbilisi as expected, but represents  time equal to 4:30, which is not expected
$opensAt = $this->timezone->date('Monday 08:30');
//the same, Timezone Asia/Tbilisi but time - 14:00 (UTC)
$closesAt = $this-timezone->date('Monday 18:00');
// timezone Asia/Tbilisi, represents current time in Tbilisi
$currentTime = $this->timezone->date();
return $currentTime >= $opensAt && $currentTime < $closesAt;
```
I do really assume that all 3 object will be in the same timezone, but obviously no. Actually they are all in the same timezone, but time in `$opensAt` and `$closesAt` is shifted to UTC timezone (in my case 4 hours diff).
So in terms of test cases, when I have timezone `Asia/Tbilisi` and run next code:
```
    $time = $this->timezone->date('Monday 08:00');
    var_dump($time);
```
I expect to see something like this:
```
class DateTime#1 (3) {
  public $date => string(26) "2020-09-07 08:00:00.000000"
  public $timezone_type => int(3)
  public $timezone => string(12) "Asia/Tbilisi"
}
```
What I actually get, is similar to:
```
class DateTime#1 (3) {
  public $date => string(26) "2020-09-07 04:00:00.000000"
  public $timezone_type => int(3)
  public $timezone => string(12) "Asia/Tbilisi"
}
```

2020-09-09 16:17 UTC, gabrieldagama commented
Hi @sergeynezbritskiy, thanks for replying! 

I've tested the code snippet that you've sent with `Asia/Tbilisi` timezone on a Vanilla Magento installation, the UTC time when I ran this was `16:07` and I've got the following results:

```
object(DateTime)#716 (3) {
  ["date"]=>
  string(26) "2020-09-14 12:30:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(12) "Asia/Tbilisi"
}
object(DateTime)#710 (3) {
  ["date"]=>
  string(26) "2020-09-14 22:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(12) "Asia/Tbilisi"
}
object(DateTime)#713 (3) {
  ["date"]=>
  string(26) "2020-09-09 20:07:00.901150"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(12) "Asia/Tbilisi"
}
```

As you can see in the results, all the times are in the same timezone and at all of them, we have the result being UTC + 4 hours, which matches the behavior described before. As I said, Magento considers the string that is being sent on the `date` function is on UTC and makes the conversion to the store timezone. 

I guess this is a expected behavior, can you perform some tests on a Vanilla instance of Magento? Thank you!

2020-09-23 08:27 UTC, engcom-Charlie commented
Hi @sergeynezbritskiy, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

2020-09-23 08:27 UTC, closed without merging