Fix unit tests with PHPUnit 9 errors
magento/magento2 pull request #29244
Opened 2020-07-23 11:28 UTC by AntonEvers

### Description (*)

Most of the failing tests are due to:
- Depending on setUp logic in dataProviders, while dataProvider code is called before setUp
- Trying to mock non-existing methods with createPartialMock which is prohibited in PHPUnit 9

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-23 12:09 UTC, AntonEvers commented
@magento run all tests

2020-07-23 12:13 UTC, AntonEvers commented
@ihor-sviziev can I ask for your review on this? Starting from today I saw a lot of failing tests.

2020-07-23 14:45 UTC, ihor-sviziev submitted a review, later dismissed

2020-07-23 14:47 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7874](https://jira.corp.magento.com/browse/ENGCOM-7874) has been created to process this Pull Request

2020-07-24 08:15 UTC, engcom-Alfa commented
QA not applicable

2020-07-25 12:43 UTC, lbajsarowicz commented on app/code/Magento/Quote/Test/Unit/Model/Quote/Address/Total/SubtotalTest.php
> +            ->disableArgumentCloning()
**YAGNI** If original code is not performing any `clone` then you don't need to provide these methods.

2020-07-25 12:44 UTC, lbajsarowicz commented on app/code/Magento/Quote/Test/Unit/Model/Quote/Address/Total/SubtotalTest.php
> +            ->disallowMockingUnknownTypes()
**YAGNI** If original code is not performing any `clone` then you don't need to provide these methods.

2020-07-25 12:44 UTC, lbajsarowicz commented on app/code/Magento/Quote/Test/Unit/Model/Quote/Address/Total/SubtotalTest.php
> +            ->disallowMockingUnknownTypes()
**YAGNI** If original code is not performing any `clone` then you don't need to provide these methods.

2020-07-25 12:44 UTC, lbajsarowicz commented on app/code/Magento/Sales/Test/Unit/Model/Order/CreditmemoFactoryTest.php
> +            ->disallowMockingUnknownTypes()
**YAGNI** If original code is not performing any `clone` then you don't need to provide these methods.

2020-07-25 12:44 UTC, lbajsarowicz commented on lib/internal/Magento/Framework/Pricing/Test/Unit/Adjustment/CollectionTest.php
> +            [['adj1', 'adj2', 'adj3', 'adj4'], ['adj3', 'adj1', 'adj2', 'adj4']],
Is that change necessary? :-)

2020-07-25 12:46 UTC, lbajsarowicz requested changes
Thank you for your contribution. My only concern is the code that is probably not necessary (You Ain't Gonna Need It). I really appreciate that you want to improve PHPUnit tests!

2020-07-27 07:58 UTC, AntonEvers commented
Thanks @lbajsarowicz for reviewing this. All comments are processed.

2020-07-27 07:58 UTC, AntonEvers commented
@magento run all tests

2020-07-27 08:29 UTC, lbajsarowicz commented
We need to wait for Tests to pass, and then I'm going to approve the PR.

2020-07-27 12:28 UTC, ihor-sviziev approved these changes

2020-07-27 12:29 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7874](https://jira.corp.magento.com/browse/ENGCOM-7874) has been created to process this Pull Request

2020-07-28 08:41 UTC, engcom-Alfa commented
QA not applicable

2020-07-28 08:50 UTC, lbajsarowicz approved these changes
:heavy_check_mark: Thanks!

2020-07-28 08:51 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7874](https://jira.corp.magento.com/browse/ENGCOM-7874) has been created to process this Pull Request

2020-07-30 11:40 UTC, engcom-Alfa commented
@magento create issue

2020-08-01 09:18 UTC, merged