Bundle products options input validation
magento/magento2 pull request #29256
Opened 2020-07-24 10:10 UTC by michalderlatka

### Description (*)
Validates input for radio and select type options. 

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes magento/magento2#26110

### Manual testing scenarios (*)
Follow instructions from related issue

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-24 10:10 UTC, michalderlatka commented
@magento run all tests

2020-07-24 11:27 UTC, michalderlatka commented
@magento run all tests

2020-07-24 18:43 UTC, cpartica requested changes

2020-07-24 18:43 UTC, cpartica commented on app/code/Magento/Bundle/Model/Product/Type.php
> +    protected function validateRadioAndSelectOptions($optionsCollection, $options): void
don't add protected, use private

2020-07-24 18:43 UTC, cpartica commented on app/code/Magento/Bundle/Model/Product/Type.php
> +                if (($option->getType() == 'radio' || $option->getType() == 'select') &&
that is a big condition, can you move that to a method with a meaningful name?

2020-07-24 18:43 UTC, cpartica commented on app/code/Magento/Bundle/Model/Product/Type.php
> +     * @param \Magento\Bundle\Model\ResourceModel\Option\Collection $optionsCollection
do "use Magento\Bundle\Model\ResourceModel\Option\Collection" and only use "Collection"

2020-07-24 18:43 UTC, cpartica commented on app/code/Magento/Bundle/Model/Product/Type.php
> +     * Validate Options for Radio and Select input types
add some kind of a test for this, either unit or integration, or webapi

2020-07-25 12:36 UTC, lbajsarowicz commented
Hi @michalderlatka . Nice to see another contributor from Poland.
Please review the Maintainer comments and feel free to share your thoughts.

2020-07-30 10:40 UTC, michalderlatka commented
@magento run all tests

2020-08-03 05:19 UTC, michalderlatka commented
@magento run static tests

2020-08-03 17:01 UTC, cpartica approved these changes

2020-08-03 17:23 UTC, cpartica commented
@magento run all tests

2020-08-03 18:07 UTC, cpartica requested changes
Some static fails, but also some possible performance problems:

PHP Code Sniffer detected 2 violation(s): 

FILE: /var/www/html/app/code/Magento/Bundle/Model/Product/Type.php
----------------------------------------------------------------------
FOUND 1 ERROR AND 4 WARNINGS AFFECTING 5 LINES
----------------------------------------------------------------------
  398 | WARNING | [ ] Function's nesting level (6) exceeds 5;
      |         |     consider refactoring the function
  535 | ERROR   | [x] Tags visual alignment must be consistent
 1194 | WARNING | [ ] Empty FUNCTION statement detected
 1212 | WARNING | [ ] array_merge(...) is used in a loop and is a
      |         |     resources greedy construction.
 1393 | WARNING | [ ] array_merge(...) is used in a loop and is a
      |         |     resources greedy construction.
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

The following files incorrectly reuse fixtures:
/var/www/html/dev/tests/integration/testsuite/Magento/Bundle/_files/product_with_multiple_options_radio_select.php
/var/www/html/dev/tests/integration/testsuite/Magento/Bundle/_files/product_with_multiple_options_radio_select_rollback.php
Please use Magento\TestFramework\Workaround\Override\Fixture\Resolver::requireDataFixture
Failed asserting that 2 matches expected 0.

2020-08-03 18:37 UTC, cpartica commented on app/code/Magento/Bundle/Model/Product/Type.php
> -     * @return \Magento\Bundle\Model\ResourceModel\Option\Collection
SVC is failing because of this, but I will approve it, it's a false positive

2020-08-03 18:37 UTC, cpartica commented on app/code/Magento/Bundle/Model/Product/Type.php
> -     * @return \Magento\Bundle\Model\ResourceModel\Option\Collection
SVC is failing because of this, but I will approve it, it's a false positive

2020-08-05 12:54 UTC, michalderlatka commented
@magento run all tests

2020-08-05 18:57 UTC, michalderlatka commented
@magento run Functional Tests B2B

2020-08-10 20:46 UTC, cpartica approved these changes

2020-08-10 20:49 UTC, cpartica commented
@magento run Functional Tests B2B

2020-08-10 20:49 UTC, cpartica commented
@magento run Functional Tests EE

2020-08-11 19:33 UTC, merged