Unit Test / Deprecate / ObjectManager Helper
magento/magento2 pull request #29272
Opened 2020-07-25 22:48 UTC by lbajsarowicz

### Description (*)
During the **Magento 1** to **Magento 2** migration, the rush around forced them to make some compromises. Last month we finally said Good Bye to Magento 1, but we still fight against the legacy of it.

One of the **Ancient Artifacts** is `\Magento\Framework\TestFramework\Unit\Helper\ObjectManager` which purpose was to mock all the dependencies that were not necessary to mock for specific Unit Tests. That enabled developers to introduce ugly classes with a few of dependencies.

In my personal 2020 is about the time to stop this ridiculous practice and give up with using ObjectManager for instantiating classes under test and replace that with `new` keyword in Unit Tests.

#### Reason behind it

1. Need for mocking all the dependencies will make Developer think twice before introducing another few of dependencies.
1. Introducing new backwards-incompatible dependency to the class will result in Unit Tests failure, thus will point out Developer that he introduced the backwards-incompatible change.
1. ObjectManager hides the ugly complexity of Magento classes.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
PR makes an ugly world of Magento Unit Tests a slightly better place.

### Manual testing scenarios (*)
N/A

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-25 22:55 UTC, lbajsarowicz commented
@magento run all tests

2020-07-25 23:08 UTC, lbajsarowicz commented
@magento run all tests

2020-07-26 03:52 UTC, ihor-sviziev requested changes
@lbajsarowicz looks good! Could you double check why static test fails?

2020-07-26 07:30 UTC, lbajsarowicz commented
@magento run all tests

The **Static Tests** were failing due to reference to non-existing classes.

2020-07-26 18:45 UTC, ihor-sviziev approved these changes

2020-07-26 18:46 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7886](https://jira.corp.magento.com/browse/ENGCOM-7886) has been created to process this Pull Request

2020-07-28 12:04 UTC, engcom-Delta commented
**Notice:** QA not applicable

2020-07-31 07:39 UTC, lbajsarowicz commented
@magento run Integration Tests

2020-07-31 11:16 UTC, engcom-Delta commented
@magento create issue

2020-08-13 16:37 UTC, merged