Incorrect order status label in sales update emails sent from the admin for non-default store views issue29263
magento/magento2 pull request #29273
Opened 2020-07-26 02:45 UTC by edenduong

### Description (*)

Fix issue below:

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29263: Incorrect order status label in sales update emails sent from the admin for non-default store views 

### Manual testing scenarios (*)

1. In the admin:
    * Go to “Stores > All Stores”, click on “Create Store View”, fill in the required values, set the status to “Enabled” and click on the "Save Store View” button.
    * Go to “Stores > Order Status”, click on the “Pending” status, enter the following data under “Store View Specific Labels”, and click on the “Save Status” button.
        * Default Store View: “Pending (default)”
        * New Store View: “Pending (secondary)”
2. In the frontend:
    * Select the new store view in the store view switcher.
    * Add a product to the cart.
    * Complete the checkout using the “Check / Money order” payment method.
3. In the admin:
    * Go to “Sales > Orders”, and click on the newly created order.
    * On this order view page, enter a comment, click on the “Notify Customer by Email” checkbox and click on the "Submit Comment” button.

**=> An order update email is sent containing “Pending (secondary)” as the order status.**

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-26 08:58 UTC, edenduong commented
@magento run all tests

2020-07-26 10:00 UTC, edenduong commented
I  changed `public function getStatusFrontendLabel(?string $code)`  to `public function getStatusFrontendLabel(?string $code, int $storeId = null)`. We need the $storeId params. Please consider the Semantic Version Checker.

2020-07-26 13:50 UTC, rogyar commented
Hi @edenduong. Thank you for the fix. 
Changing the signature of `getStatusFrontendLabel` might be considered as a backward-incompatible change. However, the fix looks really useful, sending it for further approval.

2020-07-29 18:16 UTC, aadmathijssen commented
Hi @edenduong, thanks for the PR! I think this should fix the issue I reported.

There still seems to be another related issue with the `getStoreLabel` method however: for the case that no store specific status label exists for the `$storeId` parameter, the standard `__` translation function is used; this function ignores the value of `$storeId`. In order to fix that, we could use environment emulation when `$storeId` is not the current store id.

2020-08-11 06:59 UTC, swnsma commented
Hi @edenduong!
The 3'rd param is really looks useful.
However, can we implement it in backward-compatible way (e.g. introduce new method with 3 params and deprecate old one with 2)?

2020-08-25 19:03 UTC, sidolov requested changes
Please, use suggested way how to avoid backward-incompatible changes described in [comment](https://github.com/magento/magento2/pull/29273#issuecomment-671766629)

2020-08-25 19:03 UTC, sidolov commented on app/code/Magento/Sales/Model/Order/Config.php
> +    public function getStatusFrontendLabel(?string $code, int $storeId = null): ?string
Unfortunately, we cannot change the signature of the public method in a class marked as @api.

2020-09-12 13:43 UTC, edenduong commented
Thank you. I think I should create new public method and @deprecated the old method.

2020-09-14 08:25 UTC, engcom-Echo commented on app/code/Magento/Sales/Model/Order.php
> +declare(strict_types=1);
This is correct but there is a big risk. For example, "public function getCustomerName ()" will be fail. I think this change doesn't relate to this PR.

2020-09-22 08:49 UTC, engcom-Echo commented
@magento run all tests

2020-09-22 11:31 UTC, engcom-Echo commented
@magento run all tests

2020-09-23 10:20 UTC, gabrieldagama approved these changes, later dismissed

2020-09-23 10:21 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8254](https://jira.corp.magento.com/browse/ENGCOM-8254) has been created to process this Pull Request

2020-09-24 07:37 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. In the admin:
    * Go to “Stores > All Stores”, click on “Create Store View”, fill in the required values, set the status to “Enabled” and click on the "Save Store View” button.
    * Go to “Stores > Order Status”, click on the “Pending” status, enter the following data under “Store View Specific Labels”, and click on the “Save Status” button.
        * Default Store View: “Pending (default)”
        * New Store View: “Pending (second)”
2. In the frontend:
    * Select the new store view in the store view switcher.
    * Add a product to the cart.
    * Complete the checkout using the “Check / Money order” payment method.
3. In the admin:
    * Go to “Sales > Orders”, and click on the newly created order.
    * On this order view page, enter a comment, click on the “Notify Customer by Email” checkbox and click on the "Submit Comment” button.

**Before:** :heavy_multiplication_x: An order update email is sent containing “Pending (default)” as the order status.

![2020-09-24_09-42](https://user-images.githubusercontent.com/51679138/94114876-998a3880-fe51-11ea-90ca-d7cdedb77ec7.png)

**After:** :heavy_check_mark: An order update email is sent containing “Pending (second)” as the order status.

![2020-09-24_09-55](https://user-images.githubusercontent.com/51679138/94114924-ab6bdb80-fe51-11ea-843c-7c9ba45a0f69.png)

Also was checked with different types of statuses, on different websites, without specific labels, and everything works as expected.

2020-09-24 10:21 UTC, engcom-Echo commented
Need approval. Added a new public method instead of the old.

2020-10-06 12:57 UTC, sivaschenko commented
Approval request: https://jira.corp.magento.com/browse/MC-38232

2020-12-31 08:48 UTC, swnsma approved these changes

2020-12-31 08:49 UTC, magento-engcom-team commented
Hi @swnsma, thank you for the review.
[ENGCOM-8254](https://jira.corp.magento.com/browse/ENGCOM-8254) has been created to process this Pull Request

2020-12-31 12:39 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

The result is the same as in the [comment](https://github.com/magento/magento2/pull/29273#issuecomment-698172943).

2021-01-05 11:45 UTC, engcom-Charlie commented
Needs to approve since the public method has been added to `Magento/Sales/Model/Order/Config`.

2021-01-05 13:12 UTC, sivaschenko commented
@edenduong @engcom-Charlie adding the new public method for the `Magento/Sales/Model/Order/Config` was not approved. OMS functionality is highly customizable area and the chance that someone extended the Config class is very high.

Can we extract logic related to status labels to a separate class and use in the Order model?

2021-03-25 09:27 UTC, swnsma commented
Hi @sivaschenko,
As far as I can see, the customisation was done in backward-compatible way. 

@edenduong, would you share your plans about future of the PR?

2022-04-08 12:59 UTC, engcom-Alfa commented
Hi @edenduong , Thanks for your contribution and collaboration!

As per the linked issue's [last comment](https://github.com/magento/magento2/issues/29263#issuecomment-847561365), the fix is already done. You may cross check bug fix in latest Magento `2.4-develop` version, in case of any more issues, feel free to report bugs/PR.
Thanks!

2022-04-08 12:59 UTC, closed without merging