Resolve Can not export Coupon Code to CSV issue29277
magento/magento2 pull request #29278
Opened 2020-07-26 15:16 UTC by edenduong

### Description (*)

Resolve Can not export Coupon Code to CSV

The problem is the controller action can not handle POST request (because it does not implement  POST Interface)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29277: Can not export Coupon Code to CSV

### Manual testing scenarios (*)

1. Go to backend, Marketing->Cart Price Rules
2. Create new rule, select auto generate coupon , generate coupon
3. In the grid, choose some coupon (must select by checkbox)
4. Click Export CSV

![image](https://user-images.githubusercontent.com/8234209/88482640-ce325e80-cf8c-11ea-94a5-30fe714d6af6.png)

#### Expected result 

1. Export Successfully

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-26 20:43 UTC, lbajsarowicz commented
@magento run all tests

2020-07-26 20:43 UTC, lbajsarowicz commented
@edenduong Could you provide MFTF test for that scenario, please?

2020-07-28 00:26 UTC, edenduong commented
> @edenduong Could you provide MFTF test for that scenario, please?

I will try to add Integration or MFTF test. THank you ! :)

2020-07-28 14:30 UTC, edenduong commented
@lbajsarowicz : I have just cover my changes by Integration Test. Thanks !

2020-07-28 14:32 UTC, lbajsarowicz commented
@magento run all tests

After getting the tests :heavy_check_mark: , I'll approve the PR.

2020-07-29 06:18 UTC, edenduong commented
@magento run all tests

2020-08-13 08:35 UTC, gabrieldagama commented
@magento run Functional Tests B2B

2020-08-19 18:21 UTC, sidolov requested changes

2020-08-19 18:21 UTC, sidolov commented on dev/tests/integration/testsuite/Magento/SalesRule/Controller/Adminhtml/Promo/Quote/ExportCoupons/ExportCouponsController.php
> +abstract class ExportCouponsController extends AbstractBackendController
Please, avoid usage of abstract classes and inheritance

2020-08-26 06:34 UTC, engcom-Charlie commented
Hi @edenduong can you please look through at requested changes https://github.com/magento/magento2/pull/29278#discussion_r473233310?
Thank you.

2020-09-07 08:36 UTC, engcom-Charlie commented
Hi, @edenduong I'll try to continue with your PR.

2020-09-07 08:44 UTC, engcom-Charlie commented
@magento run all tests

2020-09-07 20:17 UTC, sidolov approved these changes

2020-09-07 20:19 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8153](https://jira.corp.magento.com/browse/ENGCOM-8153) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-08 07:11 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to backend, Marketing->Cart Price Rules;
2. Create new rule, select auto generate coupon , generate coupon;
3. In the grid, choose some coupon (must select by checkbox);
4. Click Export CSV or XML;

**Before :** :heavy_multiplication_x: 404 Error. Page not found.

![Screenshot from 2020-09-08 09-36-40](https://user-images.githubusercontent.com/51679138/92444412-845bab80-f1bb-11ea-87ae-2f7f6cffbfe6.png)

**After:** :heavy_check_mark: Coupon codes were successfully exported

![Peek 2020-09-08 10-03](https://user-images.githubusercontent.com/51679138/92444515-abb27880-f1bb-11ea-9a7c-3609394d9d38.gif)

2020-09-09 20:00 UTC, merged