#1618: Duplicated items in Used in Entities filters
magento/magento2 pull request #29290
Opened 2020-07-27 09:54 UTC by joweecaquicla

### Description (*)

Prevent simultaneous requests when user types search key in `ui-select`.
### Related Pull Requests

_N/A_
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1618

### Manual testing scenarios (*)

1. Go to Content - Media Gallery
2. Click Filters
3. Expand, for example, Used in Pages filter
4. Start typing page into Page Title field

### Questions or comments

_N/A_
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-07-27 09:55 UTC, joweecaquicla commented
@magento run all tests

2020-07-27 11:22 UTC, sivaschenko requested changes
Thanks for the pull request @joweecaquicla ! Please see my comments

2020-07-27 11:22 UTC, sivaschenko commented on app/code/Magento/Ui/view/base/web/js/form/element/ui-select.js
> +            filterRateLimitMethod: 'notifyWhenChangesStop',
I don't think these defaults changes are necessary, also this is backward incompatible change

2020-07-27 11:22 UTC, sivaschenko commented on app/code/Magento/Ui/view/base/web/js/form/element/ui-select.js
> +            if (searchKey !== this.lastSearchKey || currentPage === 1) {
to be honest I think we can even simplify this condition
```suggestion
            if (currentPage === 1) {
```

2020-07-27 12:22 UTC, joweecaquicla commented
@magento run all tests

2020-07-28 14:06 UTC, sivaschenko approved these changes

2020-07-28 14:07 UTC, sivaschenko commented
@chalov-anton please test together with https://github.com/magento/adobe-stock-integration/pull/1655

2020-07-28 14:07 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7902](https://jira.corp.magento.com/browse/ENGCOM-7902) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-07-28 14:57 UTC, sivaschenko commented
ui-select functionality is covered by various MFTF tests

2020-07-29 15:04 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

Tested together with Adobe Stock PR - https://github.com/magento/adobe-stock-integration/pull/1655
The original issue is not reproducible.

Added a scenario to regression scope - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/5021347

2020-07-29 15:34 UTC, sivaschenko commented
@magento run Functional Tests CE,Integration Tests

2020-08-01 09:18 UTC, merged