Fix urlFilterApplier for filter values as array
magento/magento2 pull request #29367
Opened 2020-08-03 11:46 UTC by Nazar65

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

https://github.com/magento/adobe-stock-integration/issues/1704: The asset can not be checked in Assets filter

### Manual testing scenarios (*)
. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled
4. Uploaded image 

### Steps to reproduce (*)
1. Create a new Product and add the previously uploaded image to its Content
2. Go to **Content - Media Gallery**
3. Select the previously used image by clicking on it
4. Click "three dots", select **View Details**
5. The Used In Detail displays _Used in: Products(1)_ link. Click on _Products(1)_ link
(user is redirected to Products grid)
6. Click **Filters**
7. Dropdown **Asset** filter and type image name 
(image is found)
8. Try to check the image checkbox

### Expected result (*)
The image checkbox is checked, the image is added to Asset filter

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-03 11:46 UTC, Nazar65 commented
@magento run all tests

2020-08-04 13:29 UTC, rogyar commented
@magento run Functional Tests B2B

2020-08-05 08:30 UTC, Nazar65 commented
@magento run all tests

2020-08-05 08:33 UTC, Nazar65 commented
@magento run all tests

2020-08-05 09:51 UTC, Nazar65 commented
@magento run all tests

2020-08-05 19:57 UTC, Nazar65 commented
@magento run all tests

2020-08-05 20:01 UTC, Nazar65 commented
@magento run all tests

2020-08-06 08:27 UTC, sivaschenko requested changes
Thanks for the PR @Nazar65 ! Please see my comments

Also, considering the complexity - can you please extract the `url-filter-applier` changes to a separate pull request.

2020-08-06 08:27 UTC, sivaschenko commented on app/code/Magento/Ui/view/base/web/js/grid/url-filter-applier.js
> +            delete options['filters[asset_id]'];
Please remove the `asset_id` hardcode

2020-08-06 08:27 UTC, sivaschenko commented on app/code/Magento/Ui/view/base/web/js/grid/url-filter-applier.js
> +                this.selectComponent().options(options);
I'd prefer to call `loadOptions` if the component is select if possible

2020-08-06 08:27 UTC, sivaschenko commented on app/code/Magento/Ui/view/base/web/js/grid/url-filter-applier.js
> +            selectComponentName: null,
The filter may not be a select, please adjust the logic accordingly
```suggestion
            filterComponentName: null,
```

2020-08-06 11:31 UTC, Nazar65 commented
@magento run all tests

2020-08-06 12:06 UTC, Nazar65 commented
@magento run all tests

2020-08-06 21:48 UTC, Nazar65 commented
@magento run all tests

2020-08-07 12:14 UTC, sivaschenko approved these changes

2020-08-07 12:19 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7976](https://jira.corp.magento.com/browse/ENGCOM-7976) has been created to process this Pull Request

2020-08-07 13:00 UTC, sivaschenko commented
@Nazar65 please create a PR with `ce-etalon.json` update in https://github.com/magento/partners-magento2-infrastructure and link both PRs to each other as related

2020-08-07 14:12 UTC, Nazar65 commented
@magento run all tests

2020-08-07 14:58 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

- 1: 
 The Asset filter is applied. The asset name is displayed
![Selection_061](https://user-images.githubusercontent.com/45624059/89658729-905fff00-d8d7-11ea-8d1f-60f560f85fc7.png)

- 2: 
The assets can be checked 
![Peek 2020-08-07 17-53](https://user-images.githubusercontent.com/45624059/89658268-0021ba00-d8d7-11ea-9760-0fe64ee4513d.gif)

- 3: 
the long tag name is shortened by three dots
![long_tag_name](https://user-images.githubusercontent.com/45624059/89656279-06fafd80-d8d4-11ea-9983-59e3b0cedcab.png)

- 4:
`media-gallery:sync` and `media-content:sync` work correctly

- 5:
Used in is not displayed for images that are not used anywhere
![used_in](https://user-images.githubusercontent.com/45624059/89655614-0b72e680-d8d3-11ea-928a-c6381b588081.png)

All the cases are covered by Manual Testing Scenarios

2020-08-10 19:57 UTC, Nazar65 commented
@magento run all tests

2020-08-10 20:00 UTC, sivaschenko approved these changes

2020-08-10 20:01 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7976](https://jira.corp.magento.com/browse/ENGCOM-7976) has been created to process this Pull Request

2020-08-12 11:08 UTC, merged