Check if single store mode is enabled
magento/magento2 pull request #29391
Opened 2020-08-05 08:19 UTC by adamzero1

### Description (*)
Check if single store mode is enabled, not just if there is a single store. Allowing you to select the store you wish to place the order under.

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)
1. Set up Magento with single store (store code `default`, website code `default`)
2. Configure web server so that when in the admin the `MAGE_RUN_CODE` is `admin`
3. Disable single store mode in the admin.
4. Configure a payment method to be enabled at admin level, but disabled for the `default` website
5. In the Magento admin, begin creating an order.
  - new customer
  - add product (if possible see below)
6. Payment methods should contain the one that is enabled at admin level and not at website level.

### Questions or comments
This issue is hard to completely show/explain, as it heavily dependant on store setup. For example:
- if not products are enabled for the admin, (only at website level) you will be unable to select products to add the order.
- Even though single store mode is disabled, you aren't presented with the option to select the store you wish to place the order for.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-05 08:58 UTC, adamzero1 commented
@magento run all tests

2020-08-05 12:06 UTC, hostep commented
Hi @adamzero1 

Could you add the same fix to https://github.com/magento/magento2/blob/2.4.0/app/code/Magento/Tax/Block/Adminhtml/Rate/Form.php#L303 as well?
I accidentally bumped into that one today, Tax Rates don't show the Tax Titles when you only have one storeview.
This is kind of related to your PR, but not sure, so if you feel like this doesn't fit in this PR, feel free to tell me so, I can then try to pick this up later myself.

Thanks!

2020-08-05 12:42 UTC, adamzero1 commented
@magento run all tests

2020-08-05 12:43 UTC, adamzero1 commented
no worries @hostep I've added this in.

2020-08-08 11:46 UTC, swnsma commented
@magento run all tests

2020-08-08 11:47 UTC, swnsma commented
@magento create issue

2020-08-19 08:32 UTC, VladimirZaets requested changes
Hi @adamzero1. Thanks for collaboration. Please take a look at failed builds

2020-08-26 06:27 UTC, engcom-Charlie commented
Hi @adamzero1,

Could you please check failed tests? Looks like it was caused by your changes.

Thanks.

2020-09-03 19:16 UTC, sidolov commented
@adamzero1  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-03 19:16 UTC, closed without merging