#1703: The deleted tags are not removed from Tags drop-down until the web page is refreshed
magento/magento2 pull request #29400
Opened 2020-08-05 11:19 UTC by yolouiese

### Need to verify (*)
- deleted tags have been removed after clicking save

### Description (*)
Replaced the outdated keywords after new image details have been saved

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1703: The deleted tags are not removed from Tags drop-down until the web page is refreshed

### Manual testing scenarios (*)
1. Select the uploaded image by clicking on it
2. Click "three dots", select Edit
3. Add three new Tags, for example. Click Save
4. Click "three dots" again, and select Edit
5. Remove the previously added Tags by clicking on the cross (x) near them
6. Click Save
7. Click "three dots" again, and select Edit

2020-08-05 11:20 UTC, yolouiese commented
@magento run all tests

2020-08-05 13:14 UTC, sivaschenko requested changes
Thanks for the pull request @yolouiese , can you please cover this case with MFTF test

2020-08-11 10:51 UTC, sivaschenko requested changes
Thanks for updates @yolouiese ! Please see my comments

2020-08-11 10:51 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js
> +        removeCached: function (id, tags) {
I would simply remove cached image and rely on reloading from the backend to make sure frontend and backend are on the same page

2020-08-11 10:51 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryVerifyUpdatedTagsTest.xml
> +        <actionGroup ref="AdminEnhancedMediaGalleryImageDetailsEditActionGroup" stepKey="editImage"/>
I think `AdminEnhancedMediaGalleryViewImageDetails` should be executed before this step

2020-08-11 10:51 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryVerifyUpdatedTagsTest.xml
> +        <actionGroup ref="AdminEnhancedMediaGalleryVerifyImageKeywordsActionGroup" stepKey="verifyMetadataKeywords">
Can you please also verify the removal of the keyword

2020-08-11 17:15 UTC, yolouiese commented
@magento run all tests

2020-08-12 10:13 UTC, yolouiese commented
@magento run all tests

2020-08-13 14:35 UTC, sivaschenko commented
@magento run all tests

2020-08-14 09:04 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryEditDetailsSection.xml
> +        <element name="removeSelectedKeyword" type="button" selector="//span[contains(text(), '{{selectedKeywords}}')]/following-sibling::button[@data-action='remove-selected-item']" parameterized="t
I believe only one keyword can be specified here
```suggestion
        <element name="removeSelectedKeyword" type="button" selector="//span[contains(text(), '{{keyword}}')]/following-sibling::button[@data-action='remove-selected-item']" parameterized="true"/>
```

2020-08-14 09:09 UTC, sivaschenko requested changes
Thanks for updates @yolouiese ! Please see my comments on the naming. I think it can be improved a bit to make the action groups easier to reuse

2020-08-14 09:09 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryEditAssetRemoveKeywordActionGroup.xml
> +            <argument name="selectedKeywords"/>
I'd change the name and specify a type to make it more clear how to use this action group
```suggestion
            <argument name="keyword" type="string"/>
```

2020-08-14 09:09 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyRemovedImageKeywordsActionGroup.xml
> +    <actionGroup name="AdminEnhancedMediaGalleryVerifyRemovedImageKeywordsActionGroup">
```suggestion
    <actionGroup name="AssetAdminEnhancedMediaGalleryAssetDetailsKeywordsAbsentActionGroup">
```

2020-08-14 09:09 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyRemovedImageKeywordsActionGroup.xml
> +            <argument name="keywords"/>
```suggestion
            <argument name="keywords" type="string"/>
```

2020-08-14 09:09 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyRemovedImageKeywordsActionGroup.xml
> +            <description>Verifies removed image keywords on the View Details panel</description>
```suggestion
            <description>Verifies that the passed comma-separated list of keywords are not present on the View Details panel</description>
```

2020-08-14 12:06 UTC, yolouiese commented
@magento run all tests

2020-08-14 14:08 UTC, sivaschenko approved these changes

2020-08-14 14:09 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8015](https://jira.corp.magento.com/browse/ENGCOM-8015) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-08-17 16:23 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

Tags successfully removed
![Peek 2020-08-17 19-21](https://user-images.githubusercontent.com/60198022/90419243-f9592b00-e0be-11ea-9261-1a2508b4623d.gif)

Manual testing [scenario](https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/5064888)

2020-08-19 10:43 UTC, merged