1523: Switching between Views does not change the selected folder. [Media Gallery]
magento/magento2 pull request #29411
Opened 2020-08-05 17:22 UTC by joweecaquicla

### Description (*)

This PR will implement the fix to change the selected folder when switching views in Media Gallery.

### Related Pull Requests

N/A
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1523

### Manual testing scenarios (*)

1. Go **Content** - Pages click **Add New Page**
2. Expand **Content** click **Show / Hide Editor**, **Insert Image**...
3. Create a main folder named _folder_ for example and select it
4. Click on **Default View** dropdown
5. Click **Save View As**..., and click **Save all changes** ( ➡️ )
 _now you have a New View with the selected folder_
7. Close the Media Gallery and go to **Catalog - Categories**
8. Expand Content and click Select from Gallery
_folder is selected_
10. Try to switch between **New View** and **Default View**
11. The folder selected for that view must be highlighted/selected,
 i.e.: If **New View** is selected, _folder_ should be selected,
**Catalog/category** folder is selected if the **Default view** is selected

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-05 17:23 UTC, joweecaquicla commented
@magento run all tests

2020-08-06 08:00 UTC, sivaschenko requested changes
Thanks for the PR @joweecaquicla ! Please see my comments

Can you please cover this case with an MFTF test

Also please check the static tests https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/29411/a3de7a89d23fb2784c34d24facce7d29/Statics/allure-report-b2b/index.html#categories/0a4a9c930701952d758f01ac4e2bb450/6a07c842b5a5c7f8/

2020-08-06 08:00 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
> +                this.clearFiltersHandle();
the else condition can be omitted if the `return;' is added after this line

2020-08-06 08:00 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
> +            return !_.isUndefined(currentFilterPath) && currentFilterPath !== ''
I think `catalog/category` comparison should also be removed (cc @Nazar65 )

2020-08-06 20:17 UTC, joweecaquicla commented
@magento run all tests

2020-08-07 09:50 UTC, sivaschenko requested changes
Thanks for updates @joweecaquicla ! The implementation looks good! Can you please check the failed tests

2020-08-07 15:10 UTC, joweecaquicla commented
@magento run all tests

2020-08-07 15:15 UTC, joweecaquicla commented
@magento run all tests

2020-08-07 19:01 UTC, joweecaquicla commented
@magento run Database Compare, Functional Tests CE, Functional Tests EE

2020-08-13 16:23 UTC, sivaschenko commented
@magento run all tests

2020-08-13 16:24 UTC, sivaschenko submitted a review, later dismissed

2020-08-13 16:25 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8008](https://jira.corp.magento.com/browse/ENGCOM-8008) has been created to process this Pull Request

2020-08-14 10:01 UTC, Nazar65 commented on app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
> +            return !_.isUndefined(currentFilterPath) && currentFilterPath !== ''
this comparisons needed to cover behavior with pres elected folders, for example when bookmark applied and we open media gallery from category category folder should be presented only if the bookmarks not available

2020-08-14 10:02 UTC, Nazar65 requested changes

2020-08-14 10:02 UTC, Nazar65 commented on app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
> -                && currentFilterPath !== 'catalog/category';
I think this changes should be reverted

2020-08-14 11:03 UTC, engcom-Lima requested changes
:x: QA Failed
**Case 1**
**Steps to Reproduce:**
1. Go to Catalog -> Categories
2. Select any Category
3. Expand "Content" section
4. Click on the "Select from Gallery" button
5. Delete the "catalog" folder
6. Close the window
7. Click on the "Select from Gallery" button again 

**Expected Result:**  The "catalog/category" folder is created, expanded and selected
**Actual Result:** The "catalog/category" folder is created but not expanded and not selected
![Peek 2020-08-14 13-20](https://user-images.githubusercontent.com/60198022/90240114-5049d080-de31-11ea-87c3-d15ccfb48612.gif)

**Case 2**
**Steps to Reproduce:**
1. Go to Catalog -> Categories
2. Select any Category
3. Expand "Content" section
4. Click on the "Select from Gallery" button
5. Select different from the "catalog" folder
6. Close the window
7. Click on the "Select from Gallery" button again 

**Expected Result:** The selected folder should not change
**Actual Result:** The selected folder is changed.
![Peek 2020-08-14 13-35](https://user-images.githubusercontent.com/60198022/90241243-517bfd00-de33-11ea-9f6e-836bcc47b16c.gif)

**Case 3**
**Steps to Reproduce:**
1. Go to Catalog -> Categories
2. Select any Category
3. Expand "Content" section
4. Click on the "Select from Gallery" button
5. Select different from the "catalog" folder
6. Close the window
7. Click on the "Select from Gallery" button again 
**Expected Result:** The "Active Filter" applied to the previously selected directory 
**Actual Result:** The "Active Filter" applied to wrong directory
![Screenshot_95](https://user-images.githubusercontent.com/60198022/90241896-a2402580-de34-11ea-9ddf-24f61e3cf201.png)

**Case 4**
**Steps to Reproduce:**
1. Go to Catalog -> Categories
2. Select any Category
3. Expand "Content" section
4. Click on the "Select from Gallery" button
5. Delete the "catalog" folder
6. Close the window
7. Click on the "Select from Gallery" button again 

**Expected Result:** The "Delete Folder" button is active 
**Actual Result:**  The "Delete Folder" button is graduated gray 
![Screenshot_96](https://user-images.githubusercontent.com/60198022/90242899-876eb080-de36-11ea-819e-c1995c286a4a.png)

**Case 5**
**Steps to Reproduce:**
1. Go to Content -> Media Gallery
2. Click on the "Upload Image" button
3. Select any image 
4. Press "Enter" or click "Open" button 

**Expected Result:** Image uploaded successfully. No errors
**Actual Result:** Endless loading of the page after trying to add image in Standalone Media Gallery. 
![Screenshot_93](https://user-images.githubusercontent.com/60198022/90239024-93a33f80-de2f-11ea-85a9-7ac3ddffed05.png)

2020-08-18 13:34 UTC, sivaschenko commented
@magento run all tests

2020-08-18 13:38 UTC, sivaschenko commented
@engcom-Lima the implementation has been updated:
Case 1: Expected behaviour, if the filter was dropped/selected and media gallery was reopened on the same page - the filter state should be presereved
Case 2: Fixed
Case 3: Fixed
Case 4: Expected behaviour (same as case 1)
Case 5: Fixed

2020-08-18 17:28 UTC, sivaschenko commented
@magento run all tests

2020-08-24 16:57 UTC, sivaschenko commented
@magento run all tests

2020-08-24 19:12 UTC, sivaschenko commented
@magento run Static Tests

2020-08-25 11:00 UTC, sivaschenko commented
@magento run Static Tests

2020-08-25 12:27 UTC, sivaschenko commented
@magento run Static Tests

2020-08-25 13:02 UTC, sivaschenko approved these changes

2020-08-25 13:03 UTC, sivaschenko commented
@magento run all tests

2020-08-25 13:05 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8008](https://jira.corp.magento.com/browse/ENGCOM-8008) has been created to process this Pull Request

2020-08-26 09:41 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

The folder is selected and deselected correctly while switching Views

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1054245/scenarios/5131805

2020-08-27 08:11 UTC, merged