#1709: Modified date is not updated when Editing image Tags the second time
magento/magento2 pull request #29424
Opened 2020-08-06 13:39 UTC by jmonteros422

### Description (*)

This PR fixes issue #1709 with the media_gallery_asset's updated_at field not being updated if changes are made on the keyword tags. Unit test is adjusted as well.

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1709: Modified date is not updated when Editing image Tags the second time

### Manual testing scenarios (*)

1. Go to **Content - Media Gallery**
2. Click **Search Adobe Stock** and Save an image Preview
3. Wait for two minutes :hourglass:  
4. Select the previously saved preview image
5. Click "three dots", select **Edit**
6. Remove some of the Tags, add a new Tag... Click **Save**
7. Click "three dots", select **View Details**
8. Verify that the _Modified_ date has been updated
9. Wait for two minutes :hourglass:  
10. Click "three dots", select **Edit*
11. Remove some of the Tags, add a new Tag... Click **Save**
12. Click "three dots", select **View Details**
13. Verify that the _Modified_ date has been updated

### Questions or comments

Need to verify if approach is correct.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-06 13:40 UTC, jmonteros422 commented
@magento run all tests

2020-08-07 11:14 UTC, sivaschenko submitted a review, later dismissed

2020-08-07 11:17 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7973](https://jira.corp.magento.com/browse/ENGCOM-7973) has been created to process this Pull Request

2020-08-07 15:53 UTC, chalov-anton requested changes
:x: QA Failed

The issue is still reproducible. Modified Date is not updated when editing image Tags

2020-08-07 15:56 UTC, swnsma requested changes
Hi @jmonteros422!
Thank you for your contribution!

Could you introduce and Integration Test with data saving to check that 'updated_at' column is updated after save.

2020-08-10 05:51 UTC, jmonteros422 commented
> Hi @jmonteros422!
> Thank you for your contribution!
> 
> Could you introduce and Integration Test with data saving to check that 'updated_at' column is updated after save.

Thank you for the review! Okay!

2020-08-10 05:54 UTC, jmonteros422 commented
> ❌ QA Failed
> 
> The issue is still reproducible. Modified Date is not updated when editing image Tags

Hi @chalov-anton , Thank you for the QA, Can you retry modifying the tags after a browser refresh. I am only able to reproduce this because of related issue #29400 . Let me know of the results. Thanks!

2020-08-10 11:32 UTC, sivaschenko approved these changes
Thanks for the reivew @swnsma 

The modified date change is going to be covered with the MFTF test as part of https://github.com/magento/magento2/pull/29452

The base modified functionality is already covered with the MFTF test.

2020-08-10 11:33 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-7973](https://jira.corp.magento.com/browse/ENGCOM-7973) has been created to process this Pull Request

2020-08-12 11:08 UTC, merged