Fix ui-select options plaveholders for url-filter-applier
magento/magento2 pull request #29429
Opened 2020-08-06 21:21 UTC by Nazar65

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1694: Used In Link: Asset title is not displayed in the applied filters section. Asset filter does not have the selected value

### Manual testing scenarios (*)
1. Create a new Product and add the previously uploaded image to its Content
2. Go to **Content - Media Gallery**
3. Select the previously used image by clicking on it
4. Click "three dots", select **View Details**
5. The Used In Detail displays _Used in: Products(1)_ link. Click on _Products(1)_ link
(user is redirected to Products grid)
6. Click **Filters**
7. Dropdown **Asset** filter and type image name 
(image is found)
8. Try to check the image checkbox

### Expected result (*)
The image checkbox is checked, the image is added to Asset filter
### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-06 21:48 UTC, Nazar65 commented
@magenot run all tests

2020-08-06 21:49 UTC, Nazar65 commented
@magento run all tests

2020-08-10 19:58 UTC, Nazar65 commented
@magento run all tests

2020-08-10 20:33 UTC, Nazar65 commented
@magento run all tests

2020-08-11 08:20 UTC, Nazar65 commented
@magento run all tests

2020-08-11 08:32 UTC, Nazar65 commented
@magento run all tests

2020-08-11 09:43 UTC, Nazar65 commented
@magento run all tests

2020-08-11 11:24 UTC, Nazar65 commented
@magento run all tests

2020-08-11 11:41 UTC, Nazar65 commented
@magento run all tests

2020-08-13 13:59 UTC, Nazar65 commented
@magento run all tests

2020-08-14 08:02 UTC, Nazar65 commented
@magento run all tests

2020-08-14 08:30 UTC, Nazar65 commented
@magento run all tests

2020-08-14 09:00 UTC, sivaschenko requested changes
Thanks for the pull request @Nazar65 ! Please see my comment, the Asset filter readability can be improved with some refactoring.

Also please cover the View details links with MFTF test verifying the filter labels

2020-08-14 09:00 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Ui/Component/Listing/Filters/Asset.php
> +        if (!isset($this->filterData[$this->getName()])) {
please extract `getAssetIds` method to reduce the complexity

2020-08-14 12:04 UTC, Nazar65 commented
@magento run all tests

2020-08-14 12:06 UTC, Nazar65 commented
@magento run all tests

2020-08-14 13:16 UTC, Nazar65 commented
@magento run all tests

2020-08-14 13:39 UTC, Nazar65 commented
@magento run all tests

2020-08-17 07:10 UTC, Nazar65 commented
@magento run all tests

2020-08-17 12:47 UTC, sivaschenko approved these changes

2020-08-17 12:48 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8019](https://jira.corp.magento.com/browse/ENGCOM-8019) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-08-17 13:18 UTC, Nazar65 commented
@magento run all tests

2020-08-17 13:19 UTC, sivaschenko approved these changes

2020-08-17 13:20 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8019](https://jira.corp.magento.com/browse/ENGCOM-8019) has been created to process this Pull Request

2020-08-17 19:55 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed
Corresponding grid is opened with the entities filtered by the image (asset), Asset filter is set and displayed correctly
![Screenshot_107](https://user-images.githubusercontent.com/60198022/90422772-03315d00-e0c4-11ea-8310-bb87afac8d6b.png)

![Screenshot_108](https://user-images.githubusercontent.com/60198022/90422833-1c3a0e00-e0c4-11ea-9406-c5cdba0cd505.png)

![Screenshot_109](https://user-images.githubusercontent.com/60198022/90422915-3a077300-e0c4-11ea-9421-e8999aeb4ee2.png)

![Screenshot_110](https://user-images.githubusercontent.com/60198022/90422951-50adca00-e0c4-11ea-87c3-3aba08fe6b09.png)

Tag added to second image in Edit mode
![Peek 2020-08-17 19-55](https://user-images.githubusercontent.com/60198022/90423141-a1252780-e0c4-11ea-9ce4-f3023d1cffdd.gif)

2020-08-19 10:43 UTC, merged