[MFTF]Add new ActionGroup
magento/magento2 pull request #29459
Opened 2020-08-10 17:19 UTC by Usik2203

This PR created new `AdminClickButtonAddTaxRuleActionGroup` for clicking button Add New button for creating new Tax Rule

2020-08-10 17:20 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

2020-08-11 13:34 UTC, Usik2203 commented
@magento run  Functional Tests B2B

2020-08-19 08:40 UTC, eduard13 requested changes
Could you rename the action group please?
Thank you.

2020-08-19 08:40 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/ActionGroup/AdminClickButtonAddTaxRuleActionGroup.xml
> +    <actionGroup name="AdminClickButtonAddTaxRuleActionGroup">
```suggestion
    <actionGroup name="AdminClickAddTaxRuleButtonActionGroup">
```

2020-08-19 08:42 UTC, eduard13 requested changes
.

2020-08-19 12:14 UTC, Usik2203 commented
@magento run all tests

2020-08-19 12:15 UTC, Usik2203 commented on app/code/Magento/Tax/Test/Mftf/ActionGroup/AdminClickButtonAddTaxRuleActionGroup.xml
> +    <actionGroup name="AdminClickButtonAddTaxRuleActionGroup">
**Done**

2020-08-20 08:17 UTC, eduard13 approved these changes

2020-08-20 08:18 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8040](https://jira.corp.magento.com/browse/ENGCOM-8040) has been created to process this Pull Request

2020-08-20 10:41 UTC, engcom-Alfa commented
QA not applicable

2020-08-20 21:45 UTC, merged