[MFTF] Add ActionGroup for clicking edit link on customer grid
magento/magento2 pull request #29460
Opened 2020-08-10 18:01 UTC by Usik2203

This PR add `AdminCustomerClickFirstRowEditLinkActionGroup` to clicking edit link for first row on customer grid

2020-08-10 18:01 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

2020-08-11 13:35 UTC, Usik2203 commented
@magento run Functional Tests B2B

2020-08-11 16:04 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

2020-08-11 20:30 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

2020-08-12 17:09 UTC, sidolov commented
@magento create issue

2020-08-18 10:47 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

2020-08-19 08:15 UTC, eduard13 requested changes
Could you please rename the action group as suggested?
Thank you.

2020-08-19 08:15 UTC, eduard13 commented on app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminCustomerClickFirstRowEditLinkActionGroup.xml
> +    <actionGroup name="AdminCustomerClickFirstRowEditLinkActionGroup">
```suggestion
    <actionGroup name="AdminClickFirstRowEditLinkOnCustomerGridActionGroup">
```

2020-08-19 12:09 UTC, Usik2203 commented
@magento run all tests

2020-08-19 12:15 UTC, Usik2203 commented on app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminCustomerClickFirstRowEditLinkActionGroup.xml
> +    <actionGroup name="AdminCustomerClickFirstRowEditLinkActionGroup">
**Done**

2020-08-20 12:17 UTC, eduard13 approved these changes

2020-08-20 12:18 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8043](https://jira.corp.magento.com/browse/ENGCOM-8043) has been created to process this Pull Request

2020-08-21 07:15 UTC, engcom-Alfa commented
QA not applicable

2020-08-21 07:34 UTC, engcom-Charlie commented
@magento run all tests

2020-08-24 08:32 UTC, merged