[BUG] Admin order create validate vat confirm box
magento/magento2 pull request #29466
Opened 2020-08-11 07:10 UTC by Swahjak

Was broken with commit https://github.com/magento/magento2/commit/faa5f9a572ac1ea44750936bd9dc51c20513269d#diff-47459785dc7008bc9145a9609c9c7f6c and never fixed.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-11 13:05 UTC, VladimirZaets requested changes
Hi @Swahjak, thank for collaboration. Please, sign CLA, otherwise, we can't process your pull request and please take a look to my review comment

2020-08-11 13:05 UTC, VladimirZaets commented on app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js
> +                            self.accountGroupChange();
Please bind context instead of using `self` variable.

2020-08-11 18:54 UTC, Swahjak commented
@magento run all tests

2020-08-18 17:05 UTC, sidolov commented
@magento create issue

2020-08-25 10:36 UTC, gabrieldagama requested changes
Hi @Swahjak, thanks for your pull request! It looks good! All our PR must be covered with tests, would you be able to cover this with a test? I believe MFTF tests would be enough to make sure the functionality works.

Let me know if you are available for it. Thanks.

2020-09-07 12:41 UTC, gabrieldagama commented
The risk was set to`low` due to: the suggested changes shouldn't impact other areas.

2020-09-15 08:34 UTC, engcom-Hotel commented
Hello @Swahjak, I can help with MFTF. Could you please provide steps for reproducing.

2020-09-16 09:11 UTC, Swahjak commented
@engcom-Hotel sorry for my absence. I've been busy. I've never worked with MFTF and to be honest I'm currently not in a position to get started on it, so thank you for your help. I have updated the pull requests description to better reflect the steps to reproduce this issue.

2020-09-24 11:52 UTC, engcom-Hotel commented
@magento run all tests

2020-09-25 13:40 UTC, engcom-Hotel commented
@magento Functional Tests B2B, Functional Tests CE

2020-09-30 13:41 UTC, gabrieldagama approved these changes

2020-09-30 13:42 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8287](https://jira.corp.magento.com/browse/ENGCOM-8287) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-30 13:42 UTC, magento-engcom-team commented
@Swahjak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-10-01 12:13 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

1. Go to _Stores - Configuration - General - General - Country Options_. Set **Default Country** - _Germany_
2. Expand _Store Information_, select **Country** - Germany. Select any **Region/State**
3. Enter a valid German **VAT Number**. **Validate VAT Number**
4. **Save Config**
5. Go to _Stores - Tax Rules_ click **Add New Tax Rule** 
6. Click **Add New Tax Rate**. Set the following values:
- **Country** - _United Kingdom_
- **Zip/Post is Range** - checkbox _Checked_
- **Range From** - _1_
- **Range To** - _99999999_
- **Rate Percent** - _10_

5. Go to Cusromer - 


5. Go to _Stores - Configuration - Customers - Customer Configuration - Create New Account Options_ 
6. Set the following values:
- **Enable Automatic Assignment to Customer Group** - _Yes_
- **Default Group** - _Newgroup_
- **Group for Valid VAT ID - Intra-Union** - _Retailer_
- **Validation Error Group** - _General_
- **Validate on Each Transaction** - _Yes_
**Save Config** clear Magento Cache
7.

2020-10-02 13:07 UTC, merged