#1712: Remove DataObject usage from OpenDialogUrl provider
magento/magento2 pull request #29491
Opened 2020-08-12 12:02 UTC by joweecaquicla

### Description (*)

This PR will remove DataObject usage from OpenDialogUrl provide, add new plugin and modified the integration test.
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1712: Remove DataObject usage from OpenDialogUrl provider

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-12 12:03 UTC, joweecaquicla commented
@magento run all tests

2020-08-12 14:15 UTC, joweecaquicla commented
@magento run all tests

2020-08-13 09:52 UTC, sivaschenko requested changes
Thanks for the pull request @joweecaquicla ! Please see my comments

2020-08-13 09:52 UTC, sivaschenko commented on app/code/Magento/Ui/Component/Form/Element/DataType/Media/OpenDialogUrl.php
>          if ($this->openDialogUrl) {
Please keep the constructor for ability to initialize `openDialogUrl` property

2020-08-13 09:52 UTC, sivaschenko commented on app/code/Magento/MediaGalleryIntegration/composer.json
> +        "magento/module-ui": "*"
Please create a pull request to https://github.com/magento/partners-magento2-infrastructure with an update to composer etalon (see https://github.com/magento/partners-magento2-infrastructure/pull/19 for example)

2020-08-14 09:10 UTC, sivaschenko approved these changes

2020-08-14 09:11 UTC, sivaschenko commented
@magento run all tests

2020-08-14 09:11 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8010](https://jira.corp.magento.com/browse/ENGCOM-8010) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-08-17 14:32 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed
If Enhanced Media Gallery disabled:
![Screenshot_105](https://user-images.githubusercontent.com/60198022/90407649-65cc2e00-e0af-11ea-9818-adf9e6f2fec3.png)
If Enhanced Media Gallery enabled:
![Screenshot_106](https://user-images.githubusercontent.com/60198022/90407697-75e40d80-e0af-11ea-977d-4d1a9f8d146e.png)
All cases are manually covered

2020-08-18 10:11 UTC, sivaschenko commented
@magento run all tests

2020-08-19 10:43 UTC, merged