Fix used in entities of the same type are displayed separately in delete warning
magento/magento2 pull request #29490
Opened 2020-08-12 09:57 UTC by Nazar65

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1749

### Manual testing scenarios (*)
1. Add an image from media gallery to a category
2. Add another image from media gallery to a category
3. Try to delete both images together from the media gallery
4. See the delete confirmation popup

**Counts of asset usages should be aggregated by entity type: `Categories(2)` - only one `Categories` item should be displayed in the warning message**

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-12 09:58 UTC, engcom-Golf commented
@magento run all tests

2020-08-12 11:27 UTC, Nazar65 commented
@magento run all tests

2020-08-12 16:59 UTC, sivaschenko requested changes
Thanks for the pull request @Nazar65 ! Please take a look at my comment

2020-08-12 16:59 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js
> +                message += count !== Object.keys(usedIn).length ?  ', ' : '.';
I think it would be better readable if the object will be converted to an array and then rendered using `.join(', ') + '.'`

2020-08-12 17:01 UTC, sivaschenko commented
Main affected functionality is covered by MFTF tests

2020-08-13 09:35 UTC, Nazar65 commented
@magento run all tests

2020-08-13 09:40 UTC, sivaschenko approved these changes

2020-08-13 09:41 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8004](https://jira.corp.magento.com/browse/ENGCOM-8004) has been created to process this Pull Request

2020-08-13 12:09 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

Counts of asset usages is aggregated by entity type
![Screenshot_84](https://user-images.githubusercontent.com/60198022/90131631-1d420700-dd75-11ea-8f07-82cc59b85045.png)

2020-08-15 06:22 UTC, merged