Fix Parameter Tokenizer omitting first char of key
magento/magento2 pull request #29542
Opened 2020-08-14 12:02 UTC by marvinhinz

### Description (*)
\Magento\Framework\Filter\Template\Tokenizer\Parameter has to use a do-while-loop. not a while loop. Else the first char is ignored because $this->next() set the pointer to the second char before getting the first char. (copied from @bernd-reindl)

### Fixed Issues (if relevant)
1. Fixes magento/magento2#29185 

### Manual testing scenarios (*)
1. Create Custom Directive (for me typo3url with link parameter eg. {{typo3_link url='imprint'}}
2. Use it in template (eg. email footer) 
3. Debug the new custom directive process($value, array $parameters, ?string $html) function
4. Take a look at the $parameters array.
5. It should contain `url => "imprint`" but is actually `rl => "imprint"`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-14 12:02 UTC, marvinhinz commented
@magento run all tests

2020-08-14 13:08 UTC, lbajsarowicz requested changes
According to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) could you provide automatic tests to cover the change?

2020-08-21 06:15 UTC, engcom-Charlie commented
@magento run all tests

2020-08-21 06:18 UTC, engcom-Charlie commented
@magento run all tests

2020-08-21 11:14 UTC, lbajsarowicz approved these changes
✔️  All green from my side.

2020-08-21 11:19 UTC, magento-engcom-team commented
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8056](https://jira.corp.magento.com/browse/ENGCOM-8056) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-16 10:41 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create Custom Directive as described in [devdocs](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email-migration.html#create-a-custom-directive);
2. Add created before directive to any CMS page ( `{{lifetime should_bold="1"}}` in my case);
3. Open cms page with the custom directive;

**Before:** :heavy_multiplication_x: $parameters of method "process($value, array $parameters, ?string $html): string" have a parameter "hould_bold"

![2020-09-16_13-22](https://user-images.githubusercontent.com/51679138/93326802-113cdf80-f822-11ea-942f-0e48ab5fbc15.png)

:heavy_multiplication_x: and the parameter was not applied

![2020-09-16_13-25](https://user-images.githubusercontent.com/51679138/93326886-3598bc00-f822-11ea-9ef6-8efc4aa438c2.png)

**After:** :heavy_check_mark: $parameters of method "process($value, array $parameters, ?string $html): string" should have a parameter "should_bold"

![2020-09-16_13-29](https://user-images.githubusercontent.com/51679138/93326953-519c5d80-f822-11ea-8d8e-1e3fbd7e0044.png)

:heavy_check_mark: and the parameter was applied

![2020-09-16_13-30](https://user-images.githubusercontent.com/51679138/93326994-5f51e300-f822-11ea-9389-8c4ff08ea036.png)

2020-09-18 01:48 UTC, merged