Use Object Cache for Category Links to avoid redundant calls
magento/magento2 pull request #29565
Opened 2020-08-15 21:43 UTC by lbajsarowicz

### Description (*)
Having **52** products in cart, I get 156 requests to the database:
![image](https://user-images.githubusercontent.com/1639941/90322159-f7715980-df50-11ea-9484-de7dee34d3f4.png)
This PR goal is to reduce this to **52**.

This is a part of #29376 process.

### Related Pull Requests

### Fixed Issues (if relevant)
1. Continuation of #29376

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-15 21:43 UTC, lbajsarowicz commented
@magento run all tests

2020-08-16 05:08 UTC, ihor-sviziev requested changes
@lbajsarowicz seems like your changes broke some functionality, as integration and web api tests are failing. Could you check it?

2020-08-16 08:00 UTC, WinstonN commented
> @lbajsarowicz seems like your changes broke some functionality, as integration and web api tests are failing. Could you check it?

Why don't YOU fix it? Why don't YOU pitch in and lend your knowledge to the COMMUNITY!!!??? Why must the COMMUNITY DO EVERYTHING?

2020-08-16 08:04 UTC, lbajsarowicz commented
@magento run WebAPI Tests, Integration Tests

Thanks @ihor-sviziev . Looks like I haven't covered the situation when during a single runtime the data is changed. I just covered that situation by adding Object Cache cleanup method.

2020-08-17 05:30 UTC, ihor-sviziev commented
@lbajsarowicz integration tests still failing, please review them

2020-08-18 17:12 UTC, sidolov commented
@lbajsarowicz , @ihor-sviziev it's a good idea to store some values in cache and don't make a lot of requests, such approach can significantly improve performance but I personally like the approach when caching object (in case with interface and preference) or caching plugin is implemented, it will provide ability for developers to disable cache in some extra cases. For example, right now we see several failures of integration tests due to cache, with caching object or plugin we will be able to redefine the preference with object without cache or disable the plugin.

2020-08-18 17:12 UTC, sidolov commented
@magento create issue

2020-08-18 18:59 UTC, lbajsarowicz commented
@sidolov The hell around introducing new classes (including constructor dependencies) and effort to do it in a backwards-compatible manner is too big for "quick fixes" that I'm trying to do (low-hanging fruits). 

We should ask one of the teams who don't really care about backwards-compatibility - eg. Security Team, to introduce that the way you ask.

I'm going to improve this approach, as "it does the job it should", but any further work in that area without redesign does not makes sense at all. Look how poor the modified class looks like, and you'd understand why I don't want to play with it more than I need.

2020-09-05 08:16 UTC, ihor-sviziev commented
Hi @lbajsarowicz ,
Will you be able to fix failing tests ?

2020-09-05 09:28 UTC, lbajsarowicz commented
@ihor-sviziev I just scheduled that for next weekend.

2020-09-16 13:07 UTC, ihor-sviziev commented
@lbajsarowicz  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-09-16 13:07 UTC, closed without merging