magento/adobe-stock-integration#1760: Media Gallery page and Category grid page opened successfully if "Enhanced Media Gallery" disabled
magento/magento2 pull request #29632
Opened 2020-08-18 12:10 UTC by jmonteros422

### Description (*)

This PR will fixes issue magento/adobe-stock-integration#1760

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1760: Media Gallery page and Category grid page opened successfully if "Enhanced Media Gallery" disabled 

### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Enhanced Media Gallery Disabled 
### Steps to reproduce (*)

1. Open `https://yourdomain.com/admin/media_gallery_catalog/category/index` link
2. Then open `https://yourdomain.com/admin/media_gallery/media/index` link in new tab

### Expected result (*)

404 page

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-18 12:10 UTC, jmonteros422 commented
@magento run all tests

2020-08-18 14:07 UTC, sivaschenko requested changes
Thanks for the PR @jmonteros422 ! Can you please revert the changes for the Category grid page, only the Media Gallery page should not be acccesible.

Can you please also cover the changes by MFTF tests: 404 page should be returned trying to access media gallery by URL if it's disabled

2020-08-19 09:06 UTC, jmonteros422 commented
@magento run all tests

2020-08-19 10:59 UTC, sivaschenko requested changes
Thanks for the updates @jmonteros422 ! Please see my comments

2020-08-19 10:59 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryDisabledTest.xml
> +            <group value="media_gallery_ui"/>
Please intorduce a new `media_gallery_ui_disabled` suite that will not enable the new media gallery (that suite does not need any before/after actions actually)

2020-08-19 10:59 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/ActionGroup/AssertAdminStandaloneMediaGalleryPageIs404ActionGroup.xml
> +<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Please introduce this action group as `app/code/Magento/Backend/Test/Mftf/ActionGroup/AssertAdminPageIs404ActionGroup.xml`

2020-08-19 12:13 UTC, jmonteros422 commented
@magento run all tests

2020-08-19 18:50 UTC, sivaschenko requested changes
Thanks for updates @jmonteros422 ! Please see my comments

2020-08-19 18:50 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryDisabledTest.xml
> +            <actionGroup ref="AdminMediaGalleryEnhancedEnableActionGroup" stepKey="disableEnhancedMediaGallery"/>
There is no need to disable media gallery as it is disabled by default

2020-08-19 18:50 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryDisabledTest.xml
> +            <actionGroup ref="AdminOpenStandaloneMediaGalleryActionGroup" stepKey="openStandaloneMediaGallery"/>
opening media gallery is actually part of the test, not the precondition

2020-08-19 18:50 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/ActionGroup/AssertAdminPageIs404ActionGroup.xml
> +    <actionGroup name="AssertAdminPageIs404ActionGroup">
please move the action group to Backend module (see the exact path in the comment from previous review)

2020-08-20 16:58 UTC, jmonteros422 commented
@magento run all tests

2020-08-24 11:51 UTC, sivaschenko commented
@magento run Functional Tests EE

2020-08-24 11:51 UTC, sivaschenko approved these changes

2020-08-24 11:52 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8064](https://jira.corp.magento.com/browse/ENGCOM-8064) has been created to process this Pull Request

2020-08-25 08:40 UTC, chalov-anton commented
:heavy_check_mark: QA Passed

If thee _New Media Gallery_ is **disabled**, the https://yourdomain.com/admin/media_gallery/media/index link leads to _404 Page not found_

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/5106786

2020-08-26 12:51 UTC, merged