Covered mftf for issue #27350
magento/magento2 pull request #29708
Opened 2020-08-21 05:27 UTC by saphaljha

### Description (*)
I have covered MFTF

### Related Pull Requests
#27602 

## Fixed Issues (if relevant)

1. Fixes magento/magento2#27350

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-21 09:41 UTC, saphaljha commented
@magento run all tests

2020-08-21 14:59 UTC, BarnyShergold requested changes
Failing tests needs to be fixed

2020-08-21 14:59 UTC, BarnyShergold commented on app/code/Magento/Sales/Test/Mftf/Section/AdminInvoiceItemsSection.xml
> +        <element name="bundleItem" type="text" selector="table > tbody > tr:nth-child(n) > td.col-product > div.option-value"/>
This looks to be causing a Functional test to fail

2020-08-21 15:34 UTC, saphaljha commented on app/code/Magento/Sales/Test/Mftf/Section/AdminInvoiceItemsSection.xml
> +        <element name="bundleItem" type="text" selector="table > tbody > tr:nth-child(n) > td.col-product > div.option-value"/>
Hello @BarnyShergold,

Yes, test will be always failed because it needs the **bundleItem** ("bundleItem" is new element on invoice view page) but as the PR #27602 (Check screenshot for of this PR more clarification) haven't merge yet so this will be always be failed, once this PR will merge test will be passed.

Thanks to let me know if you have any other question.

2020-08-22 09:44 UTC, lbajsarowicz requested changes
Please review the issues I've noticed in your test.

2020-08-22 09:44 UTC, lbajsarowicz commented on app/code/Magento/Bundle/Test/Mftf/Test/StorefrontBundlePlaceOrderWithMultipleOptionsSuccessTest.xml
> +        <!-- Actions before test execution -->
These annotations are redundant - > The syntax of XML is clear about the roles there :-)
Especially considering the fact that comments are also displayed in the test output.

2020-08-22 09:44 UTC, lbajsarowicz commented on app/code/Magento/Bundle/Test/Mftf/Test/StorefrontBundlePlaceOrderWithMultipleOptionsSuccessTest.xml
> +        <!-- Actions after test execution -->
↑ Same as above.

2020-08-22 09:44 UTC, lbajsarowicz commented on app/code/Magento/Bundle/Test/Mftf/Test/StorefrontBundlePlaceOrderWithMultipleOptionsSuccessTest.xml
> +        <amOnPage url="{{BundleProduct.sku}}.html" stepKey="goToStorefront"/>
↑ This is flaky! You should use Action Group that opens the Product page based on Product object provided, not SKU. `SKU != Product's URL_PATH`

2020-08-22 09:44 UTC, lbajsarowicz commented on app/code/Magento/Sales/Test/Mftf/Section/AdminInvoiceItemsSection.xml
> +        <element name="bundleItem" type="text" selector="table > tbody > tr:nth-child(n) > td.col-product > div.option-value"/>
That selector is flaky. Please use any unique identifier on a page as an anchor.

2020-08-22 15:09 UTC, saphaljha commented on app/code/Magento/Sales/Test/Mftf/Section/AdminInvoiceItemsSection.xml
> +        <element name="bundleItem" type="text" selector="table > tbody > tr:nth-child(n) > td.col-product > div.option-value"/>
Hello @lbajsarowicz ,
Thank you for review, I have updated all the points as per your suggestion.
Please review again.

2020-08-22 15:14 UTC, lbajsarowicz commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-08-23 12:41 UTC, lbajsarowicz commented
@saphaljha Could you make sure that amended selectors are correct, please?

2020-08-23 15:04 UTC, saphaljha commented
> @saphaljha Could you make sure that amended selectors are correct, please?

Yes, but after merging this PR #27602

2020-08-23 16:15 UTC, lbajsarowicz commented
After reviewing the failure reports, I'm pretty sure that the selector I asked you to change to be unique across the Panel fails. Could you confirm why?

2020-08-24 05:36 UTC, saphaljha commented
I would like you to check this pull request and issue, in this issue you will see that on new invoice page the bundle items are not showing as expected, so I have created the MFTF for this pull request. so after merging the below pull request this test will success.
https://github.com/magento/magento2/pull/27602

hope this is clear.

2020-08-31 12:55 UTC, engcom-Charlie commented
Hi @saphaljha, unfortunately, we can't proceed with your PR with test coverage for separate PR. We can only proceed with one PR with fix and test coverage.
Thank you for your collaboration.

2020-09-03 11:43 UTC, engcom-Charlie commented
Hi @saphaljha, I've applied your MFTF to PR with a fix. So I close this PR.

2020-09-03 11:43 UTC, closed without merging