[MFTF] Used In information is not displayed after the entity was deleted
magento/magento2 pull request #29711
Opened 2020-08-21 12:26 UTC by Nazar65

deleted with mftf tests

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1774: Used In information is not displayed after the entity was deleted

### Manual testing scenarios (*)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-21 12:27 UTC, engcom-Golf commented
@magento run all tests

2020-08-21 14:53 UTC, BarnyShergold requested changes

2020-08-21 14:53 UTC, BarnyShergold commented on app/code/Magento/MediaGalleryUi/Test/Mftf/ActionGroup/AssertAdminEnhancedMediaGalleryUsedInSectionNotDisplayedActionGroup.xml
> +            <description>Assert thats used in section not displayed in vew details.</description>
Typos in messages

```suggestion
            <description>Assert that's used in section not displayed in view details.</description>
```

2020-08-21 14:54 UTC, Nazar65 commented
@magento run all tests

2020-08-24 11:56 UTC, sivaschenko requested changes
It would be good to add similar tests for other entities (product, block, page) to cover all the observers

2020-08-25 12:05 UTC, Nazar65 commented
@magento run all tests

2020-08-25 12:21 UTC, Nazar65 commented
@magento run all tests

2020-08-25 14:25 UTC, Nazar65 commented
@magento run all tests

2020-08-25 18:32 UTC, Nazar65 commented
@magento run all tests

2020-08-26 12:25 UTC, sivaschenko approved these changes

2020-08-27 08:11 UTC, merged