#29704 :- Submit search button in form-mini should be disabled until minimum search length is reached
magento/magento2 pull request #29724
Opened 2020-08-24 09:32 UTC by konarshankar07

### Description (*)

This PR will fix the issue with the submit search button is not respecting the minimum search length
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29704

### Manual testing scenarios (*)

1. Focus on form-mini search box.
2. Type one or two alphanumeric characters in search box.

### Expected Result 
![image](https://user-images.githubusercontent.com/39480008/91028225-cb259f00-e61a-11ea-8f09-88cd6e0ae191.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-24 09:32 UTC, konarshankar07 commented
@magento run all tests

2020-08-24 09:42 UTC, rogyar commented
@magento give me test instance

2020-08-24 09:42 UTC, magento-engcom-team commented
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

2020-08-24 09:43 UTC, magento-engcom-team commented
Hi @rogyar, here is your [new Magento instance](https://pr-29724.instances.magento-community.engineering).
Admin access: [https://pr-29724.instances.magento-community.engineering/admin_34a9](https://pr-29724.instances.magento-community.engineering/admin_34a9)
Login: `ab5342ec` Password: `6759de2048d1`
Instance will be terminated in up to 3 hours.

2020-08-24 09:50 UTC, rogyar commented
Hi @konarshankar07. Thank you for the fix. 

I'm just curious, how hard do you think will be to spread the same fix for the submit by "return" button? With your fix, the button stays disabled but it's still possible to submit the search query by pressing the "return" button. If this part of the fix will be complicated, feel free to create a separate PR. If the mentioned fix is easy to implement, it would be great to have it as a part of this PR. 

In any case, I would ask you to cover this fix by a simple MFTF test.  

Thank you!

2020-08-25 08:36 UTC, konarshankar07 commented
@magento run all tests

2020-08-25 10:10 UTC, gabrieldagama requested changes
Hi @konarshankar07, thanks for the pull request, it looks great! Please follow some small suggestions below:

2020-08-25 10:10 UTC, gabrieldagama commented on app/code/Magento/Search/Test/Mftf/Test/StorefrontVerifySearchButtonDisabledTillMinimumSearchLengthHit.xml
> +<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Can we add the `Test` suffix here to follow the convention?

2020-08-25 10:10 UTC, gabrieldagama commented on app/code/Magento/Search/Test/Mftf/Test/StorefrontVerifySearchButtonNotDisabledAfterMinimumSearchLengthHit.xml
> +    <test name="StorefrontVerifySearchButtonNotDisabledAfterMinimumSearchLengthHit">
Can we add the `Test` suffix here to follow the convention?

2020-08-25 10:10 UTC, gabrieldagama commented on app/code/Magento/Search/Test/Mftf/ActionGroup/AssertStorefrontVerifySearchButtonIsNotDisabledActionGroup.xml
> +    <actionGroup name="AssertStorefrontVerifySearchButtonIsNotDisabledActionGroup">
```suggestion
    <actionGroup name="AssertStorefrontVerifySearchButtonIsEnabledActionGroup">
```

2020-08-25 11:39 UTC, konarshankar07 commented
@magento run all tests

2020-08-25 14:30 UTC, gabrieldagama approved these changes
Thanks for the updates @konarshankar07. The failed tests aren't related to this PR.

2020-08-25 14:31 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8067](https://jira.corp.magento.com/browse/ENGCOM-8067) has been created to process this Pull Request

2020-08-25 15:43 UTC, konarshankar07 commented
Thanks @gabrieldagama  for the review
Can you please remove the `Auto-test: Not covered` label?

2020-08-25 15:43 UTC, konarshankar07 commented
@magento run Functional Tests CE test

2020-08-25 15:44 UTC, gabrieldagama commented
@magento run Functional Tests CE

2020-08-25 15:44 UTC, konarshankar07 commented
@magento run Functional Tests CE

2020-08-27 13:54 UTC, rogyar approved these changes

2020-08-27 13:55 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8067](https://jira.corp.magento.com/browse/ENGCOM-8067) has been created to process this Pull Request

2020-08-31 10:13 UTC, engcom-Oscar commented
:heavy_check_mark: QA Passed

2020-09-04 14:00 UTC, engcom-Echo commented
@magento run all tests

2020-09-07 05:11 UTC, konarshankar07 commented
@magento run WebAPI Tests

2020-09-07 23:19 UTC, merged