Add Regions for Uruguay.
magento/magento2 pull request #29722
Opened 2020-08-23 23:00 UTC by barbanet

### Description (*)
Regions for Uruguay will be added with this PR. Regions are using the ISO 3166-2 code (the regions table can be check here [https://en.wikipedia.org/wiki/ISO_3166-2:UY](https://en.wikipedia.org/wiki/ISO_3166-2:UY))

### Manual testing scenarios (*)
1. Once you finish the installation the country should show you Regions on shipping estimation, checkout or when you edit the customer address form.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-23 23:11 UTC, BarnyShergold commented
@magento run all tests

2020-08-24 10:48 UTC, BarnyShergold requested changes
Ensure all tests are passing as well as requested changes

2020-08-24 10:48 UTC, BarnyShergold commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForUruguay.php
> +    private function getDataForUruguay()
Missing return type on prototype

2020-08-24 10:48 UTC, BarnyShergold commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForUruguay.php
> +    public static function getDependencies()
Missing return type on prototype

2020-08-24 10:48 UTC, BarnyShergold commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForUruguay.php
> +    public function getAliases()
Missing return type on prototype

2020-08-24 10:48 UTC, BarnyShergold commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForUruguay.php
> + * Class AddDataForUruguay
Add better class description - has to be more than just this or tests fail

2020-08-24 10:48 UTC, BarnyShergold commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForUruguay.php
> +        );
MUST return $this

2020-08-24 15:29 UTC, sidolov commented
@magento create issue

2020-08-25 04:46 UTC, barbanet commented
Thank you @BarnyShergold for all those recommendations. I'll take care ASAP.

2020-09-03 11:04 UTC, engcom-Echo commented
Hi, @barbanet. Could you please check failed tests and recommendations? 

Thank you.

2020-09-07 09:34 UTC, engcom-Echo commented
@magento run all tests

2020-09-07 12:23 UTC, engcom-Echo commented
Hi  @barbanet. Can you fix "Static Tests"?
Failed functional tests not related to the changes in this PR

2020-09-07 12:40 UTC, gabrieldagama commented
The risk was set to`low` due to: the suggested changes shouldn't impact other areas.

2020-09-11 13:26 UTC, engcom-Echo commented
@magento run all tests

2020-09-22 09:11 UTC, BarnyShergold approved these changes, later dismissed

2020-09-22 09:12 UTC, magento-engcom-team commented
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8244](https://jira.corp.magento.com/browse/ENGCOM-8244) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-23 08:42 UTC, engcom-Bravo commented
Hello @BarnyShergold 

Can you please add an appropriate label for _test coverage_?

Thank you

2020-09-23 09:13 UTC, engcom-Bravo requested changes
Hello @BarnyShergold

Can you please add an appropriate label for test coverage?

Thank you

2020-09-24 12:38 UTC, BarnyShergold approved these changes

2020-09-24 12:40 UTC, magento-engcom-team commented
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8244](https://jira.corp.magento.com/browse/ENGCOM-8244) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-09-25 09:41 UTC, engcom-Bravo commented
:heavy_check_mark:  QA Passed

Regions are added for Uruguay country 

See the result BEFORE switching to the PR
![29722_before](https://user-images.githubusercontent.com/51680745/94251902-e04c6100-ff2b-11ea-893b-93d5645a7940.png)

and AFTER switching to the PR
![29722_after1](https://user-images.githubusercontent.com/51680745/94251972-f823e500-ff2b-11ea-8553-cd1570bb70d4.png)

List of regions
![29722_after2](https://user-images.githubusercontent.com/51680745/94252004-007c2000-ff2c-11ea-8c48-a931892560b7.png)

Storefront
![29722_storefront](https://user-images.githubusercontent.com/51680745/94252021-070a9780-ff2c-11ea-8bc2-9f9c4fc8b9b2.png)

:heavy_check_mark: Successfully submitted order and created shipment to Uruguay

2020-09-30 02:12 UTC, merged