Add font weight heavy variable
magento/magento2 pull request #29773
Opened 2020-08-27 11:29 UTC by mrtuvn

### Description (*)

Small additional to core lib. Add font weight heavy for reuse

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-27 11:40 UTC, ihor-sviziev commented
@mrtuvn maybe it's good idea to add all common weight names? https://developer.mozilla.org/uk/docs/Web/CSS/font-weight#Common_weight_name_mapping

2020-08-27 12:03 UTC, mrtuvn commented
good point!. I have updated in my PR

2020-08-27 12:09 UTC, ihor-sviziev requested changes

2020-08-27 12:09 UTC, ihor-sviziev commented on lib/web/css/source/lib/variables/_typography.less
> +@font-weight__thin: 200;
from the table: 

Value | Common weight name
-- | --
200 | Extra Light (Ultra Light)



```suggestion
@font-weight__extralight: 200;
```

2020-08-27 12:35 UTC, ihor-sviziev approved these changes

2020-08-27 12:35 UTC, ihor-sviziev commented
@magento run all tests

2020-08-27 12:36 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8085](https://jira.corp.magento.com/browse/ENGCOM-8085) has been created to process this Pull Request

2020-08-27 14:54 UTC, sidolov commented
@magento create issue

2020-09-01 19:37 UTC, ptylek approved these changes

2020-09-01 19:38 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-8085](https://jira.corp.magento.com/browse/ENGCOM-8085) has been created to process this Pull Request

2020-09-01 19:42 UTC, ihor-sviziev approved these changes

2020-09-01 19:43 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8085](https://jira.corp.magento.com/browse/ENGCOM-8085) has been created to process this Pull Request

2020-10-12 09:55 UTC, engcom-Alfa commented
@magento create issue

2020-10-12 11:38 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

possible to use new font-weight variable values

2020-10-13 11:17 UTC, merged