magento/magento2#29775: Full page cache does not use customer group id to build a cache identifier
magento/magento2 pull request #29781
Opened 2020-08-27 16:00 UTC by pmarjan

### Description (*)

Full page cache now id added with a customer group id when building the cache identifier.
Therefor, two different GET requests that have the same payload, but do have different Authorization bearers, will now have two different cache entries.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/29775

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-08-29 13:15 UTC, rogyar requested changes
Hi @pmarjan. Thank you for your collaboration. Good job. 
Please, check my suggestions below. Also, I would ask you to cover your solution with API-functional test. 

Thank you!

2020-08-29 13:15 UTC, rogyar commented on app/code/Magento/CustomerGraphQl/Controller/HttpRequestProcessor/CustomerProcessor.php
> +    protected $graphQlContext;
Please, use private scope for the properties. Introducing a possibility of extension by overriding is not recommended. You may use [recently created services](https://github.com/magento/magento2/blob/24b4dcd99161875957040ff83f53c20389461676/app/code/Magento/MediaGallery/Model/Directory/Command/DeleteByPaths.php#L19) as examples for good practices.

2020-08-29 13:15 UTC, rogyar commented on app/code/Magento/CustomerGraphQl/Controller/HttpRequestProcessor/CustomerProcessor.php
> +     * Customer constructor.
I would suggest removing this comment from DocBlock since it's redundant and only adds extra line to the code. Thank you.
```suggestion
```

2020-08-29 13:15 UTC, rogyar commented on app/code/Magento/CustomerGraphQl/Controller/HttpRequestProcessor/CustomerProcessor.php
> +            if ($this->graphQlContext->getUserType() == UserContextInterface::USER_TYPE_CUSTOMER) {
Please, use a strict comparison here as well
```suggestion
            if ($this->graphQlContext->getUserType() === UserContextInterface::USER_TYPE_CUSTOMER) {
```

2020-08-29 13:24 UTC, pmarjan commented
@rogyar 
thank you for the feedback!

So far this PR serves as a concept - should be proven at least with manual testing scenarios against Varnish and Fastly.

Then, a verification would be needed against the usage of loading the customer via the Repository - is this to add performance drag, then, other options will have to be looked at.

Then, yes, some improvements are needed, like that if statement on line 67 can be more accurate, also API-functional test is planned to be added, and certainly I will look up any notices and suggestions.

Thanks!

2020-10-08 03:28 UTC, nrkapoor commented
@magento run all tests

2022-02-15 07:53 UTC, engcom-Charlie commented
Hi @pmarjan,

Thank you for your contribution!

The issue which have been taken care in this PR its been closed after concluding by [this](https://github.com/magento/magento2/issues/29775#issuecomment-847125069) comment. 

Hence as per the comment, we are closing this PR. Please reopen and update if you have some other input to continue.

Thank you!

2022-02-15 07:53 UTC, closed without merging