Prevent flushing same tags several times
magento/magento2 pull request #29885
Opened 2020-09-03 12:20 UTC by siimm

### Description (*)
If a product is saved in admin - changed name, price, stock, weight, added category to product. Then after indexing, the same tags are flushed several times.
Here is an example of default Magento behaviour on cleaning cache tags during indexing (different arrays belong to different indexers cleaning the cache):
```
root@c119d6a06fcb:/var/www/m2clean$  bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1

Array
(
)

Array
(
)

Array
(
    [0] => cat_p_1
    [1] => cat_c_2
    [2] => cat_c_1
    [3] => cat_c_2
    [4] => cat_c_3
    [5] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_c_2
    [2] => cat_c_1
    [3] => cat_c_2
    [4] => cat_c_3
    [5] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_c_2
    [2] => cat_c_1
    [3] => cat_c_2
    [4] => cat_c_3
    [5] => cat_c_1
)

Array
(
    [0] => cat_p_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_c_2
    [5] => cat_c_1
    [6] => cat_c_2
    [7] => cat_c_3
    [8] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_c_2
    [5] => cat_c_1
    [6] => cat_c_2
    [7] => cat_c_3
    [8] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_p_1
    [5] => cat_c_2
    [6] => cat_c_1
    [7] => cat_c_2
    [8] => cat_c_3
    [9] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_p_1
    [5] => cat_c_2
    [6] => cat_c_1
    [7] => cat_c_2
    [8] => cat_c_3
    [9] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_p_1
    [5] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [8] => cat_c_2
    [9] => cat_c_3
    [10] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_p_1
    [5] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [8] => cat_c_2
    [9] => cat_c_3
    [10] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_p_1
    [5] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [8] => cat_c_2
    [9] => cat_c_3
    [10] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_p_1
    [5] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [8] => cat_c_2
    [9] => cat_c_3
    [10] => cat_c_1
)

Array
(
    [0] => cat_p_1
    [1] => cat_p_1
    [2] => cat_p_1
    [3] => cat_p_1
    [4] => cat_p_1
    [5] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [8] => cat_c_2
    [9] => cat_c_3
    [10] => cat_c_1
)
```

Here is the same output with the changes applied:
```
root@c119d6a06fcb:/var/www/m2clean$  bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1
Array
(
)

Array
(
)

Array
(
    [0] => cat_p_1
    [1] => cat_c_2
    [2] => cat_c_1
    [4] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [1] => cat_c_2
    [2] => cat_c_1
    [4] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [1] => cat_c_2
    [2] => cat_c_1
    [4] => cat_c_3
)

Array
(
    [0] => cat_p_1
)

Array
(
    [0] => cat_p_1
    [4] => cat_c_2
    [5] => cat_c_1
    [7] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [4] => cat_c_2
    [5] => cat_c_1
    [7] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [5] => cat_c_2
    [6] => cat_c_1
    [8] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [5] => cat_c_2
    [6] => cat_c_1
    [8] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [9] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [9] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [9] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [9] => cat_c_3
)

Array
(
    [0] => cat_p_1
    [6] => cat_c_2
    [7] => cat_c_1
    [9] => cat_c_3
)

```

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Observe the output of \Magento\Framework\Indexer\CacheContext::getIdentities during indexer run, same tags are flushed up to 10 times per one indexer instance
2. ...

### Questions or comments
Together with https://github.com/magento/magento2/pull/29699 it will probably reduce the amount of cache flushing significatly

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-03 14:19 UTC, sidolov commented
@magento create issue

2020-09-03 19:18 UTC, rogyar commented
Hi @siimm. Thank you for your collaboration. Nice catch! 
Could I ask you to cover your change with a simple unit test, please? The unit test will assert that the method returns only unique values. 

Thank you!

2020-09-04 08:32 UTC, siimm commented
Hi @rogyar, attached a minimalistic test case to this PR
https://github.com/magento/magento2/pull/29885/commits/f17148f902309ddfd6868b17b7183099222084d8

2020-09-04 16:16 UTC, lenaorobei commented
@magento run all tests

2020-09-06 18:38 UTC, BarnyShergold requested changes

2020-09-06 18:38 UTC, BarnyShergold commented on lib/internal/Magento/Framework/Indexer/Test/Unit/CacheContextTest.php
> +
Extra Blank line is causing test fails

2020-09-06 18:38 UTC, BarnyShergold commented on lib/internal/Magento/Framework/Indexer/CacheContext.php
> +        return array_unique(array_merge($identities, array_unique($this->tags));
Missing a closing parenthesis, should be ))); 
Cause of most of the test failures

2020-09-07 14:46 UTC, gabrieldagama commented
The risk was set to`medium` due to: the suggested changes may affect other areas/modules.

2020-09-08 14:29 UTC, lenaorobei commented
@magento run all tests

2020-09-17 12:16 UTC, ihor-sviziev commented
@magento run all tests

2020-09-21 14:34 UTC, rogyar approved these changes, later dismissed

2020-09-21 14:35 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8237](https://jira.corp.magento.com/browse/ENGCOM-8237) has been created to process this Pull Request

2020-09-22 09:04 UTC, BarnyShergold approved these changes, later dismissed

2020-09-22 09:05 UTC, magento-engcom-team commented
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8237](https://jira.corp.magento.com/browse/ENGCOM-8237) has been created to process this Pull Request

2020-09-28 10:59 UTC, engcom-Bravo commented
:x: QA Failed

Hello @siimm 
Looks like the changes provided in this PR do not solve the original issue. I'm getting the same Output before and after switching to the PR
![cat1](https://user-images.githubusercontent.com/51680745/94424367-c6608780-0192-11eb-991d-d078d86c4d35.png)

Please, see the Manual treating scenario 
1. Go to **System** - **Index Management**
2. **Select All** _Indexers_  and change the _Actions_ to **Update by Schedule**
3. Go to **Catalog** - **Categories**, and change the _Category Name_ for at least two Categories, for example
4. Go to **Catalog** - **Products** and change the _Price, Quantity, Weight_ for at least two Products
5. Run `bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`
6. Observe the output of `\Magento\Framework\Indexer\CacheContext::getIdentities`

2020-09-28 11:01 UTC, engcom-Bravo requested changes
:x: QA Failed

Hello @siimm 
Looks like the changes provided in this PR do not solve the original issue. I'm getting the same Output before and after switching to the PR
![cat1](https://user-images.githubusercontent.com/51680745/94424367-c6608780-0192-11eb-991d-d078d86c4d35.png)

Please, see the Manual testing scenario 
1. Go to **System** - **Index Management**
2. **Select All** _Indexers_  and change the _Actions_ to **Update by Schedule**
3. Go to **Catalog** - **Categories**, and change the _Category Name_ for at least two Categories, for example
4. Go to **Catalog** - **Products** and change the _Price, Quantity, Weight_ for at least two Products
5. Run `bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`
6. Observe the output of `\Magento\Framework\Indexer\CacheContext::getIdentities`

2020-10-05 06:33 UTC, siimm commented
@engcom-Bravo 
Did you check the values what the **getIdentities** method returns? - from the screenshot I can assume the values were inspected inside of the method itself - the $ids variable is hinting that.

2020-10-05 14:32 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

Further investigation discovered that the changes provided in this PR, fix the original issue
### Manual Testing scenario
1. Go to **System** - **Index Management**
2. **Select All** _Indexers_  and change the _Actions_ to **Update by Schedule**
3. Go to **Catalog** - **Categories**, and change the _Category Name_ for at least two Categories, for example
4. Go to **Catalog** - **Products** and change the _Price, Quantity, Weight_ for at least two Products
5. Run `bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`
6. Observe the return of `\Magento\Framework\Indexer\CacheContext::getIdentities`

**BEFORE** applying changes
![before](https://user-images.githubusercontent.com/51680745/95092696-a00d8f80-0730-11eb-935f-0e7aff8056bd.png)

**AFTER** switching to the PR
![after](https://user-images.githubusercontent.com/51680745/95092750-ad2a7e80-0730-11eb-9592-e35589600715.png)

2020-10-06 07:48 UTC, engcom-Bravo commented
@rogyar @BarnyShergold Can you please review the PR again?

2020-10-06 12:55 UTC, rogyar commented on lib/internal/Magento/Framework/Indexer/Test/Unit/CacheContextTest.php
> +    public function testUniqueTags($tagsData, $expected)
Just a recommendation for the future to use type hinting whenever it's possible. It's a very useful habit in PHP 7.x

2020-10-06 12:55 UTC, rogyar approved these changes

2020-10-06 12:56 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8237](https://jira.corp.magento.com/browse/ENGCOM-8237) has been created to process this Pull Request

2020-10-07 23:18 UTC, merged