[WIP] #1795: [MFTF] Unskip AdminMediaGalleryCatalogUiUsedInProductFilterTest
magento/magento2 pull request #29909
Opened 2020-09-04 14:27 UTC by joweecaquicla

### Description (*)

Unskipped `AdminMediaGalleryCatalogUiUsedInProductFilterTest` and will run MFTF builds to check and confirm that the test is stable.
### Related Pull Requests

N/A
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1795

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-04 14:27 UTC, joweecaquicla commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-09-04 15:51 UTC, joweecaquicla commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-09-04 18:36 UTC, joweecaquicla commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-09-07 16:30 UTC, joweecaquicla commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-09-09 08:57 UTC, sivaschenko approved these changes, later dismissed

2020-09-09 08:58 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8167](https://jira.corp.magento.com/browse/ENGCOM-8167) has been created to process this Pull Request

2020-09-10 15:44 UTC, gabrieldagama commented
@magento run all tests

2020-09-10 15:50 UTC, gabrieldagama requested changes
Hi @joweecaquicla, thanks for your contribution, can you have a look on my comments below?

2020-09-10 15:50 UTC, gabrieldagama commented on app/code/Magento/MediaGalleryCatalogUi/Test/Mftf/Test/AdminMediaGalleryCatalogUiUsedInProductFilterTest.xml
>          <actionGroup ref="AdminAssertMediaGalleryFilterPlaceHolderGridActionGroup" stepKey="assertFilterApplied">
Please clear the product grid filter after asserting that the product was found, this may be causing other tests to fail.

2020-09-10 16:47 UTC, joweecaquicla commented
@magento run all tests

2020-09-10 19:58 UTC, sivaschenko approved these changes

2020-09-10 19:59 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8167](https://jira.corp.magento.com/browse/ENGCOM-8167) has been created to process this Pull Request

2020-09-10 20:00 UTC, sivaschenko commented
The failed AdminMediaGalleryAssertUsedInLinkPagesGridTest appears to be randomly failing, will be skipped and fixed in the scope of a separate issue

2020-09-11 08:02 UTC, gabrieldagama commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

2020-09-11 13:03 UTC, sivaschenko commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

2020-09-12 18:42 UTC, sivaschenko commented
AdminMediaGalleryCatalogUiVerifyUsedInLinkProductGridTest and AdminMediaGalleryCatalogUiUsedInCategoryFilterTest have failed on this PR, created a separate ticket to stabilize them https://github.com/magento/adobe-stock-integration/issues/1830

2020-09-12 18:42 UTC, sivaschenko commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

2020-09-14 19:03 UTC, merged