[MFTF] add new  AdminDeleteTaxRateActionGroup
magento/magento2 pull request #29929
Opened 2020-09-07 13:21 UTC by Usik2203

This PR introducing new `AdminDeleteTaxRateActionGroup`

2020-09-07 13:21 UTC, Usik2203 commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-09-07 13:54 UTC, eduard13 requested changes
Hi @Usik2203 could you please check my comments bellow?
Thank you for your contribution.

2020-09-07 13:54 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/ActionGroup/AdminDeleteTaxRateActionGroup.xml
> +            <description>Goes to the Admin Tax Rate grid page. Deletes the provided Tax Rate Code.</description>
In my opinion the description doesn't reflect the ActionGroup behavior, additionally we have more actions (filter, selectFirstRow, delete) here than is supposed to.

2020-09-07 13:54 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/ActionGroup/AdminDeleteTaxRateActionGroup.xml
> +        <click selector="{{AdminTaxRateFormSection.ok}}" stepKey="clickOk"/>
Also, I would rather reuse the section `AdminMainActionsSection` and `AdminConfirmationModalSection` elements defined in Backend module than use a separate buttons defined in scope of each module.

2020-09-07 13:54 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/ActionGroup/AdminDeleteTaxRateActionGroup.xml
> +        <waitForPageLoad stepKey="waitForTaxRuleSearch"/>
I would split the grid searching into several ActionGroups, this way we'll have a more granular and reusable action groups:
- ClearFiltersAdminDataGridActionGroup
- Filter by RateCode
- AdminSelectFirstGridRowActionGroup - you may move it to Backend or Ui module, as it's a general ActionGroup and may be reused in any other module
- Delete the Tax Rate

2020-09-07 14:38 UTC, Usik2203 commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-09-07 14:39 UTC, eduard13 commented
The risk was set to `low` due to: the suggested changes shouldn't affect other areas.

2020-09-07 19:24 UTC, Usik2203 commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-09-08 07:11 UTC, Usik2203 commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-09-08 13:26 UTC, sidolov commented
@magento create issue

2020-09-09 12:47 UTC, Usik2203 commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-09-11 19:30 UTC, Usik2203 commented
@magento run all tests

2020-09-13 19:08 UTC, eduard13 approved these changes
The failing tests are randomly failing and don't seem to be somehow related with this PR

2020-09-13 19:09 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8192](https://jira.corp.magento.com/browse/ENGCOM-8192) has been created to process this Pull Request

2020-09-14 22:36 UTC, merged