[WIP]  fix incorrect image size when rendition is inserted
magento/magento2 pull request #29979
Opened 2020-09-10 14:28 UTC by engcom-Golf

### Description (*)

Fixes issue that image uploader displays incorrect image size when rendition is inserted from media gallery
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes adobe-stock-integration#1806

### Manual testing scenarios (*)

#### Preconditions:
1. Use old media gallery - No
2. Media Gallery Renditions Configured
#### Steps to test:
1. Open category page
2. Open content section
3. Insert Image from media gallery
4. Insert image with high resolution and file size
5. Ensure that image resolution and size responds to rendition image

2020-09-10 20:33 UTC, sivaschenko requested changes
Thanks for the PR @engcom-Golf ! Please see my comment.

Also can you please add an MFTF test covering the fix

2020-09-10 20:33 UTC, sivaschenko commented on app/code/Magento/Cms/Model/Wysiwyg/Images/GetInsertImageContent.php
> +    public function getImageSize(string $path): int
Please move these public methods to the introduced controller (as private methods).

2020-09-11 10:12 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
> +                    'onInsertUrl' => $this->urlInterface->getUrl('media_gallery_renditions/image/oninsert'),
The issue with this approach is that it makes MediaGalleryUi module dependent on Renditions. It's better to have the reversed dependency.

Let's keep the plugin in Renditions module and move the introduced controller to MediaGalleryUi for this purpose

2020-09-11 12:01 UTC, engcom-Golf commented
@magento run all tests

2020-09-11 12:42 UTC, engcom-Golf commented
@magento run all tests

2020-09-11 13:44 UTC, sivaschenko requested changes
Thanks for updates @engcom-Golf ! Please see my comments

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/Cms/Model/Wysiwyg/Images/GetInsertImageContent.php
> +use Magento\Framework\Filesystem\File\WriteInterface;
Please remove the unused imports

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryRenditions/Test/Mftf/Test/AdminMediaGalleryInsertLargeImageFileSizeTest.xml
> +            <description value="Admin user should see correct image file size after rendition"/>
Please add stories tag, value: "User inserts image rendition to the content"

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryRenditions/Test/Mftf/Test/AdminMediaGalleryInsertLargeImageFileSizeTest.xml
> +            <severity value="MAJOR"/>
```suggestion
            <severity value="AVERAGE"/>
```

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryRenditions/Test/Mftf/Test/AdminMediaGalleryInsertLargeImageFileSizeTest.xml
> +        <actionGroup ref="AdminSaveCategoryFormActionGroup" stepKey="saveCategoryForm"/>
It looks like an unnecessary step

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Data/AdminEnhancedMediaGalleryImageData.xml
> +    <entity name="LargeImage" type="image">
I don't think new entity is needed. `ImageUpload` can be used (it's referencing the same file)

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Controller/Adminhtml/Image/OnInsert.php
> +        $path = $this->getInsertImageContent->execute(
That is actually a content (that is some cases may be just a path). Please correct naming on backend and frontent
```suggestion
        $content = $this->getInsertImageContent->execute(
```

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Controller/Adminhtml/Image/OnInsert.php
> +        $size = $data['force_static_path'] ? $this->getImageSize($path) : 0;
I think it's better to use `$data['filename']` for retrieving the file path for getting more information

2020-09-11 13:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Controller/Adminhtml/Image/OnInsert.php
> +    private function getImageSize(string $path): int
considering the amount of business logic, I'd extract it to a `Magento\MediaGalleryUi\Model\GetInsertData` model.

I'd have a public method in this model with the following interface:
public function execute(
        string $encodedFilename,
        bool $forceStaticPath,
        bool $renderAsTag,
        ?int $storeId = null
    ): \Magento\MediaGalleryUi\Model\InsertDataInterface

`InsertDataInterface` should be an extensible interface (extending `\Magento\Framework\Api\ExtensibleDataInterface`) implemented by `\Magento\MediaGalleryUi\Model\InsertData` that should handle extension attributes

2020-09-14 07:55 UTC, engcom-Golf commented
@magento run all tests

2020-09-14 08:47 UTC, engcom-Golf commented
@magento run all tests

2020-09-14 09:02 UTC, engcom-Golf commented
@magento run all tests

2020-09-14 11:23 UTC, sivaschenko requested changes
Hi @engcom-Golf , thanks for updates! Please see my comments

2020-09-14 11:23 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUiApi/Api/GetInsertImageDataInterface.php
> +interface GetInsertImageDataInterface extends ExtensibleDataInterface
```suggestion
interface InsertAssetDataInterface extends ExtensibleDataInterface
```

2020-09-14 11:23 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUiApi/Api/GetInsertImageDataInterface.php
> +    public function getImageContent(
This method should be part of the service, it shouldn't be present in data transfer object https://en.wikipedia.org/wiki/Data_transfer_object

2020-09-14 11:23 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Controller/Adminhtml/Image/OnInsert.php
> +        $type = $data['force_static_path'] ? $this->getInsertImageData->getMimeType($content) : '';
Size and type retrieving logic should be moved to `getInsertImageData` service.

The service should retrieve all required data and create an `InsertImageData` (`insertImageDataFactory->create(['data' => ['content' => ..., 'size' => ..., ...]])`) and return the `InsertImageData` to the conroller.

2020-09-14 11:23 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Controller/Adminhtml/Image/OnInsert.php
> +        return $this->resultJsonFactory->create()->setData(['content' => $content, 'size' => $size, 'type' => $type]);
The controller should retrieve all the infromation from the data transfer objectЖ
```suggestion
        return $this->resultJsonFactory->create()->setData(
        [
            'content' => $insertImageData->getContent(), 
            'size' => $insertImageData->getSize(), 
            'type' => $insertImageData->getType()
        ]
        );
```

2020-09-14 13:23 UTC, engcom-Golf commented
@magento run Static Tests, Functional Tests CE

2020-09-14 15:44 UTC, sivaschenko requested changes
Perfect @engcom-Golf ! Probably the final comments from me are regarding interfaces:

I this the data interface should be moved to the implementation module and the service interface is not needed currently.

2020-09-14 15:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Model/InsertImageData.php
> +    public function setExtensionAttributes(?InsertImageDataExtensionInterface $extensionAttributes): void
I don't see the use case when we should allow calling `setExtensionAttributes` passing `null` argument
```suggestion
    public function setExtensionAttributes(InsertImageDataExtensionInterface $extensionAttributes): void
```

2020-09-14 15:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUiApi/Api/GetInsertImageDataInterface.php
> +interface GetInsertImageDataInterface
I don't think this interface is necessary

2020-09-14 15:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUiApi/Api/Data/InsertImageDataInterface.php
> +        ?\Magento\MediaGalleryUiApi\Api\InsertImageDataExtensionInterface $extensionAttributes
```suggestion
        \Magento\MediaGalleryUiApi\Api\InsertImageDataExtensionInterface $extensionAttributes
```

2020-09-14 15:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUiApi/Api/Data/InsertImageDataInterface.php
> +namespace Magento\MediaGalleryUiApi\Api\Data;
Let's move this interface to the suggested namespace
```suggestion
namespace Magento\MediaGalleryUi\Model;
```

2020-09-14 15:44 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Model/InsertImageData/GetInsertImageData.php
> +        return $this->getPubDirectory()->isExist($path) ? $this->mime->getMimeType($absoluteFilePath) : '';
I'd check if path exists before event building absolute path
```suggestion
        return $this->getPubDirectory()->isExist($path) ? $this->mime->getMimeType($this->getPubDirectory()->getAbsolutePath($path)) : '';
```

2020-09-15 07:03 UTC, engcom-Golf commented
@magento run all tests

2020-09-15 11:19 UTC, engcom-Golf commented
@magento run all tests

2020-09-15 13:49 UTC, engcom-Golf commented
@magento run Functional Tests CE

2020-09-15 13:52 UTC, engcom-Golf commented
@magento give me test instance

2020-09-15 20:42 UTC, engcom-Golf commented
@magento run all tests

2020-09-16 06:57 UTC, engcom-Golf commented
@magento run all tests

2020-09-16 10:42 UTC, sivaschenko approved these changes

2020-09-16 10:43 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8217](https://jira.corp.magento.com/browse/ENGCOM-8217) has been created to process this Pull Request

2020-09-16 11:58 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

Correct image size is displayed before saving the Category

See the result **before** switching to the PR
![before29979](https://user-images.githubusercontent.com/51680745/93334083-00459b80-f82d-11ea-9535-884f66b21699.png)

and the result **after** switching to the PR 
![after29979](https://user-images.githubusercontent.com/51680745/93334091-050a4f80-f82d-11ea-91e0-0ea10064dd71.png)

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1507933/scenarios/5200023

2020-09-18 01:47 UTC, merged