#1832: Rename renditions stores config fieldset and add comments
magento/magento2 pull request #30044
Opened 2020-09-14 17:25 UTC by joweecaquicla

### Description (*)

This PR will introduce the modifications to renditions stores config fieldset. 
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1832

### Manual testing scenarios (*)

1. Go to Stores -> Configuration -> Advanced -> System
2. "Media Gallery Renditions" should now be "Media Gallery Image Size"
3. Expand "Media Gallery Image Size"
4. Comments should be displayed (see attached screenshot)

![Screen Shot 2020-09-15 at 1 24 22 AM](https://user-images.githubusercontent.com/23549533/93118039-3e8a7000-f6f2-11ea-851d-549f4cc6122f.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-14 17:25 UTC, joweecaquicla commented
@magento run all tests

2020-09-14 18:01 UTC, sivaschenko requested changes
Thanks for the pull request @joweecaquicla ! Please see my comment

2020-09-14 18:01 UTC, sivaschenko commented on app/code/Magento/MediaGalleryRenditions/etc/adminhtml/system.xml
>                      <label>Max Width</label>
Please rename the fields and add field comments according to mockup
```suggestion
                    <label>Maximum Width</label>
```

2020-09-14 18:20 UTC, joweecaquicla commented
@magento run all tests

2020-09-14 18:46 UTC, sivaschenko approved these changes

2020-09-14 18:48 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8207](https://jira.corp.magento.com/browse/ENGCOM-8207) has been created to process this Pull Request

2020-09-15 08:50 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

**Before** switching to the PR
![1](https://user-images.githubusercontent.com/51680745/93188195-5d682100-f749-11ea-8941-ae7e25872cbd.png)

**After** switching to the PR
![2](https://user-images.githubusercontent.com/51680745/93188263-72dd4b00-f749-11ea-9a8e-9d1d3841549a.png)

Rendition is covered in several manual testing scenarios. For example in - https://studio.cucumber.io/projects/131313/test-plan/folders/1507933/scenarios/5183135

2020-09-15 12:00 UTC, joweecaquicla commented
@magento run all tests

2020-09-18 01:47 UTC, merged