[WIP] #1827: Improve AdminMediaGalleryUploadCategoryImageTest
magento/magento2 pull request #30042
Opened 2020-09-14 16:50 UTC by joweecaquicla

### Description (*)

This PR will introduce the improved/modified `AdminMediaGalleryUploadCategoryImageTest`.
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1827

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-14 16:51 UTC, joweecaquicla commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-09-15 12:21 UTC, sivaschenko requested changes
Thanks for  the pull request @joweecaquicla ! Please see my comment

2020-09-15 12:21 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryUploadCategoryImageTest.xml
> +        <conditionalClick selector="{{AdminMediaGalleryFolderSection.folderArrow(catalog)}}"
Can you please move this conditional click to an action group (i.e.  `AdminMediaGalleryExpandFolder`)

2020-09-15 13:48 UTC, joweecaquicla commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2020-09-16 10:47 UTC, sivaschenko approved these changes

2020-09-16 10:48 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8218](https://jira.corp.magento.com/browse/ENGCOM-8218) has been created to process this Pull Request

2020-09-18 14:27 UTC, merged