Don't use $rate as an object (it is an array)
magento/magento2 pull request #30052
Opened 2020-09-15 11:41 UTC by flancer64

### Description (*)
`$rate` is an array and it does not contain `id` item. We can use rate's `code` item as part of `id` for HTML nodes.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-15 19:21 UTC, Stepa4man commented
@magento run all tests

2020-09-15 19:26 UTC, Stepa4man requested changes
Hi @flancer64 
Thanks for your contribution

Could you, please take a look at my comments?

2020-09-15 19:26 UTC, Stepa4man commented on app/code/Magento/Sales/view/adminhtml/templates/order/totals/tax.phtml
> +                ?>
Please, don't hold logic in the template. Can you put this to view Model?

2020-09-15 19:26 UTC, Stepa4man commented on app/code/Magento/Sales/view/adminhtml/templates/order/totals/tax.phtml
> +                <tr id="rate-<?= /* @noEscape */ $rateId ?>"
Why should we keep **$rateId** as the name of the variable?

2020-09-16 05:49 UTC, flancer64 commented
Hello, @Stepa4man .

Sorry, I cannot "_move logic from template to view Model_". I don't know what a _right_ logic should be here. I've just fixed the bug. Someone  wrote this:
```
$rate->getId()
```

for array `$rate`. It interrupts templates rendering. 

I'm sorry again, but I have no answer to question "_Why should we keep $rateId as the name of the variable?_" :( You shouldn't. It just my own choice.

Please, feel free to reject this pull request if it doesn't match your rules.

2020-09-23 13:47 UTC, engcom-Golf commented
Hi, @flancer64, are you able to continue with this pull request?
As a unique value, you can use tax_id field and if it is still necessary you can move logic to view model and use in this template.
Instructions can be found by the following link [View models](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/view-models.html)

Also could you please cover your code changes with an MFTF test? You can use the following [Magento Functional Testing Framework Guide](https://devdocs.magento.com/mftf/docs/introduction.html) to get acquainted with it.
If you have any additional questions or appointments feel free to ask, I will try to help,

Thank you!

2020-09-23 15:50 UTC, flancer64 commented
@engcom-Golf , I cannot use `tax_id`. There was no such field under debugger in the structure. I don't know why this field was omitted on rate data selection from DB but it was:

![image](https://user-images.githubusercontent.com/5052385/94036845-6900bb00-fdcd-11ea-9d05-4a92b41e7164.png)

I agree that the better way is to use `tax_id` field here instead of `code` but we need to fix code that selects data from DB first. I'm sorry, but It's too deep for me, I don't have so much free time to check side effects. I've created this "dirty fix" and it's pretty enough for me and my projects.

2020-09-23 16:02 UTC, flancer64 commented
Maybe we can use `position` field or even 'foreach' loop index here.

2020-09-28 14:18 UTC, engcom-Golf commented
@flancer64, please look at \Magento\Tax\Model\ResourceModel\Calculation::getCalculationProcess method. There should be an ability to add rate id to the output array.

2020-09-29 04:36 UTC, flancer64 commented
Thanks, @engcom-Golf . This is the way.

This SQL is composed to select rates data in `\Magento\Sales\Block\Adminhtml\Order\Totals\Tax::getFullTaxInfo`:
```sql
SELECT
	`main_table` .*
FROM
	`sales_order_tax` AS `main_table`
WHERE
	(main_table.order_id = 1234)
ORDER BY
	`process` ASC
``` 
so, we can use `sales_order_tax.tax_id` as identifier for tax items.

2020-09-29 07:09 UTC, engcom-Golf commented
@magento run all tests

2020-09-29 10:33 UTC, engcom-Golf commented
Hi, @flancer64, thank you for your changes, but as we can see from failed tests, this approach is not acceptable. I have made some investigations and found that rates are taken not only from the database. So tax_id can be not present in rates array. Suppose we can use 'for each' loop index, as you have proposed before.

2020-09-29 16:24 UTC, flancer64 commented
> Suppose we can use 'for each' loop index, as you have proposed before.

@engcom-Golf , done.

2020-09-29 18:01 UTC, engcom-Golf commented
@magento run all tests

2020-10-19 07:31 UTC, Stepa4man approved these changes

2020-10-19 07:32 UTC, magento-engcom-team commented
Hi @Stepa4man, thank you for the review.
[ENGCOM-8353](https://jira.corp.magento.com/browse/ENGCOM-8353) has been created to process this Pull Request

2020-10-28 15:11 UTC, ihor-sviziev commented
Seems like this PR fixes https://github.com/magento/magento2/issues/30094.

We also have another PR https://github.com/magento/magento2/pull/30516 that fixes this issue.

2020-11-05 07:14 UTC, engcom-Delta requested changes
@flancer64 sorry for delay
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. 

Could you add automation test that cover your changes?

2020-11-05 07:20 UTC, flancer64 commented
@engcom-Delta , I'm sorry, I couldn't.

2020-11-05 07:37 UTC, ihor-sviziev commented
Hi @flancer64,

I just analyzed another solution that we have - seems like array index solution potentially might cause ID duplication, as in some other place on the page might be same id `rate-1`, or `rate-0`. I believe using random string is better and this approach is used in https://github.com/magento/magento2/pull/30516.

I'm closing this PR as we just have better solution for the same issue in https://github.com/magento/magento2/pull/30516.

Thank you so much for your contribution!

2020-11-05 07:37 UTC, closed without merging