[WIP] #1833: Add ability to disable renditions functionality to stores configuration
magento/magento2 pull request #30057
Opened 2020-09-15 15:32 UTC by joweecaquicla

### Description (*)

This PR will introduce the ability to disable renditions functionality to stores configuration and additional conditions to rendition-related classes.
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1833

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-16 08:21 UTC, joweecaquicla commented
@magento run all tests

2020-09-16 11:07 UTC, sivaschenko requested changes
Thanks for the pull request @joweecaquicla ! Please see my  comments

2020-09-16 11:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryRenditions/Model/Config.php
>      private const XML_PATH_ENABLED = 'system/media_gallery/enabled';
This constant is no longer needed and can be removed

2020-09-16 11:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryRenditions/Model/Config.php
> +    public function isMediaGalleryRenditionsEnabled(): bool
New method introduction is not necessary, `isEnabled` method should be now based on `system/media_gallery_renditions/enabled` value

2020-09-16 11:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryRenditions/Plugin/SetRenditionPath.php
> +        if (!$this->config->isEnabled() || !$this->config->isMediaGalleryRenditionsEnabled()) {
no change is needed here

2020-09-16 15:51 UTC, joweecaquicla commented
@magento run all tests

2020-09-16 16:24 UTC, sivaschenko commented
@magento run all tests

2020-09-16 20:55 UTC, sivaschenko approved these changes, later dismissed

2020-09-16 20:56 UTC, sivaschenko commented
Introduction of Media Gallery Renditions  functionality is approved in https://jira.corp.magento.com/browse/MC-37383 (SVC is approved)

2020-09-16 20:56 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8223](https://jira.corp.magento.com/browse/ENGCOM-8223) has been created to process this Pull Request

2020-09-17 10:08 UTC, engcom-Bravo requested changes
:x: QA Failed

When the **Enable Image Optimization** is set to **No**, Config is Saved and Cache is cleared
![endis_im_optim_no](https://user-images.githubusercontent.com/51680745/93456581-8d98f680-f8e6-11ea-998f-55cc431e6f21.png)
Still, the rendition images are inserted into newly created Page, Category...
The Expected behaviour is to insert original image sizes.

2020-09-17 10:50 UTC, sivaschenko commented
@joweecaquicla looks like the update for `\Magento\MediaGalleryRenditions\Model\Config` is missing.

private const XML_PATH_ENABLED = 'system/media_gallery/enabled'

should be changed to 

private const XML_PATH_ENABLED = 'system/media_gallery_renditions/enabled'

2020-09-17 11:16 UTC, joweecaquicla commented
@magento run all tests

2020-09-17 11:19 UTC, sivaschenko commented
@magento run all tests

2020-09-17 11:20 UTC, sivaschenko approved these changes

2020-09-17 11:21 UTC, magento-engcom-team commented
Hi @sivaschenko, thank you for the review.
[ENGCOM-8223](https://jira.corp.magento.com/browse/ENGCOM-8223) has been created to process this Pull Request

2020-09-17 12:10 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

**Enable Image Optimization** option is added under _Stores - Configuration - Advanced - System - Media Gallery Renditions_ 
![endis_im_optim](https://user-images.githubusercontent.com/51680745/93467920-e8d2e500-f8f6-11ea-90e6-3f23cdb0a59a.png)

The default value is **Yes**

When the value is set to Yes, the images added to the content are optimized to the size set in _Maximum Width_ and _Maximum Height_ fields

When the value is set to **No**, the original image size is inserted into the Content of an Entity

When **No** and **Yes** values are changed, and `bin/magento queue:consumers:start media.gallery.renditions.update` is performed, the images that have already been inserted with original size, are NOT reduced or enlarged.

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1507933/scenarios/5219418

2020-09-17 12:10 UTC, engcom-Bravo reviewed
:heavy_check_mark: QA Passed

**Enable Image Optimization** option is added under _Stores - Configuration - Advanced - System - Media Gallery Renditions_ 
![endis_im_optim](https://user-images.githubusercontent.com/51680745/93467920-e8d2e500-f8f6-11ea-90e6-3f23cdb0a59a.png)

The default value is **Yes**

When the value is set to Yes, the images added to the content are optimized to the size set in _Maximum Width_ and _Maximum Height_ fields

When the value is set to **No**, the original image size is inserted into the Content of an Entity

When **No** and **Yes** values are changed, and `bin/magento queue:consumers:start media.gallery.renditions.update` is performed, the images that have already been inserted with original size, are NOT reduced or enlarged.

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1507933/scenarios/5219418

2020-09-17 14:23 UTC, sivaschenko commented
@magento run all tests

2020-09-18 15:56 UTC, joweecaquicla commented
@magento run all tests

2020-09-18 16:14 UTC, sidolov commented
@sivaschenko SVC failures must be approved.

2020-09-21 14:40 UTC, sivaschenko commented
Introduction of Media Gallery Renditions functionality is approved in https://jira.corp.magento.com/browse/MC-37383 (SVC failure is approved)

2020-09-23 12:32 UTC, merged