ASI-1452: implement the exif writer
magento/magento2 pull request #30072
Opened 2020-09-16 13:20 UTC by coderimus

### Description (*)

This PR provides the EXIF writer and several improvements. Currently, this PR is a draft PR.

### Related Pull Requests

### Fixed Issues (if relevant)

[Create JPEG Exif writer for MediaGalleryMetadata module](https://github.com/magento/adobe-stock-integration/issues/1452)

### Manual testing scenarios (*)

Upload an image to the Media Gallery and check that EXIF data updated.

### Questions or comments

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-17 13:07 UTC, sivaschenko requested changes
Thanks for the pull request @coderimus ! Please see my comments

2020-09-17 13:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryMetadata/Model/File/AddMetadata.php
> +            throw new LocalizedException(
ValidatorException is thrown in case a specific writer is refusing to process specific metadata/file. This exception should be suppressed to allow other writers to proceed

2020-09-17 13:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/Model/UpdateAsset/SaveMetadataToFile.php
> +            throw new LocalizedException(
Loggin the exception is enough, the following actions should not be skipped in case of exception on this stage

2020-09-17 13:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryMetadata/Model/Jpeg/Segment/WriteExif.php
> +                $exifSegments [$key] = $segment;
I don't see the need to collect `$exifSegments` if only one segment is used for writing (the same case can be corrected for iptc writer)
```suggestion
                return  $this->addExifMetadata->execute($file, $metadata, $segment);
```

2020-09-17 13:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryMetadata/Model/AddExifMetadata.php
> +        $exifData =  $segment ? $segment->getData() : [];
$segment->getData() is string

2020-09-17 13:07 UTC, sivaschenko commented on app/code/Magento/MediaGalleryMetadata/Model/AddExifMetadata.php
> +        $this->writeFile($file->getPath(), $newExifData);
if you are able to update segment data without writing to file it's better to return the content to `WriteExif`. See `\Magento\MediaGalleryMetadata\Model\AddXmpMetadata::execute` for example

2020-09-23 12:12 UTC, sivaschenko commented
Hi @coderimus , how are you doing? Are you still working on this PR?

2020-09-23 12:14 UTC, coderimus commented
@sivaschenko 
Sorry for the delay. Has some urgent tasks to close. Plan to return to it in 2 days. Please, if possible let it be assigned on me. I really want to finalize it. Thank you!

2022-10-13 15:08 UTC, ishakhsuvarov commented
Hi @coderimus 

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:08 UTC, closed without merging