Fix stateful object TransportBuilder being shared by DI
magento/magento2 pull request #30106
Opened 2020-09-18 14:23 UTC by tdgroot

### Description (*)
Fix stateful object `TransportBuilder` being shared by DI, allowing for major production bugs to happen.

If, for some reason, the inner state of `TransportBuilder` is not reset, it will be dirty when it is used by the next client (`Magento\Sales\Model\Order\Email\SenderBuilder` is a client). Currently the `TransportBuilder` is being reused when sending e-mails asynchronously in the background (`sales_email/general/async_sending`), which can lead to mails being sent to additional e-mail adresses added by previous clients, which is **_very_** undesirable!

This comes down to a qualitative risk analysis:
**Likelihood of it happening**: Unlikely
**Impact when it happens**: High

We should prevent this risk by setting the DI `shared` property to **false** for the class `Magento\Framework\Mail\Template\TransportBuilder`.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
- #30105: Risk: statefulness of TransportBuilder

### Manual testing scenarios (*)
1. Enable asynchronous sending
2. Create 2 or 3 orders
3. Run cron
4. All order confirmations e-mails should be sent

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-18 17:55 UTC, ihor-sviziev commented
@magento run all tests

2020-09-21 06:44 UTC, ihor-sviziev requested changes
Hi @tdgroot,
According to failing integration tests - seems like your solution currently breaks some functionality.
Also I see that this builder is used with factory - so new instance will be created:
https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Sales/Model/Order/Email/Sender.php#L129-L137

1. Could you specify exact steps to reproduce of your issue? Do you have this issue in some magento functionality or in some custom module?
2. Could you fix test failures?

2020-09-21 20:51 UTC, sidolov commented
@tdgroot could you please update the PR according to the @ihor-sviziev comments? Thanks!

2020-10-06 20:30 UTC, sidolov commented
@tdgroot , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-10-06 20:30 UTC, closed without merging