Cleaned up duplicate variable assignments in the same line
magento/magento2 pull request #30120
Opened 2020-09-20 13:49 UTC by bgorski

### Description (*)
This is a simple cleanup of two assignments to the same variable occurring in the same line.
Created by using the following regex:
 (\$.*) \= \1 = (with space before to exclude things like self::$loader = $loader = new \Composer\Autoload\ClassLoader(); and with space after to make sure it's an assignment and not anything else like ===)
And replacing with:
 $1 = (also with space before and after to keep the formatting right)

### Related Pull Requests
https://github.com/magento/magento2/pull/28085

### Fixed Issues (if relevant)
-

### Manual testing scenarios (*)
none required

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-20 13:50 UTC, bgorski commented
@magento run all tests

2020-09-21 06:36 UTC, ihor-sviziev commented
@magento run all tests

2020-09-21 08:50 UTC, ihor-sviziev requested changes
Hi @bgorski,
Could you fix the failing static tests for changed files?

Thank you!

2020-09-21 11:07 UTC, bgorski commented
@magento run Static Tests

2020-09-21 12:26 UTC, bgorski commented
@magento run Static Tests

2020-09-21 13:30 UTC, bgorski commented
@magento run Static Tests

2020-09-21 14:56 UTC, ihor-sviziev commented
@magento run all tests

2020-09-21 15:06 UTC, sidolov commented
@magento create issue

2020-09-21 19:41 UTC, ihor-sviziev approved these changes

2020-09-21 19:42 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8242](https://jira.corp.magento.com/browse/ENGCOM-8242) has been created to process this Pull Request

2020-09-30 02:11 UTC, merged