Base price storage website price mode1
magento/magento2 pull request #30126
Opened 2020-09-21 10:16 UTC by wassuupp

Fix V1/products/base-prices endpoint to update prices for Catalog Price Mode - Website

### Description (*)
V1/products/base-prices endpoint does not work with Catalog Price Mode - Website
Function was added to affect prices for all store views inside changed website

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-21 15:05 UTC, sidolov commented
@magento create issue

2020-09-22 00:03 UTC, BarnyShergold commented
@magento run all tests

2020-09-22 09:02 UTC, BarnyShergold requested changes
Failing tests need to be addressed and fixed

2020-09-22 09:02 UTC, BarnyShergold commented on app/code/Magento/Catalog/Model/Product/Price/BasePriceStorage.php
> +    private function applyWebsitePrices($formattedPrices)
Missing return type

2020-09-28 12:33 UTC, wassuupp commented on app/code/Magento/Catalog/Model/Product/Price/BasePriceStorage.php
> +    private function applyWebsitePrices($formattedPrices)
added

2020-09-28 13:12 UTC, wassuupp commented
@magento run all tests

2020-10-05 07:16 UTC, engcom-Charlie commented
@wassuupp could you please fix failed Static and Unit tests?
Thank you.

2020-10-07 07:43 UTC, engcom-Charlie commented
@wassuupp please fix failed Static and Unit tests? Otherwise, we can't proceed with your PR.
Thank you.

2020-10-07 20:25 UTC, sidolov commented
@wassuupp  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2021-01-21 16:38 UTC, nuzil commented
I will proceed with this one

2021-01-22 07:43 UTC, nuzil commented
@magento run all tests

2021-02-08 00:24 UTC, wassuupp commented
@magento run all tests

2021-02-15 15:37 UTC, BarnyShergold commented
@magento run functional tests b2b

2021-02-15 15:38 UTC, BarnyShergold commented
@magento run Functional Tests B2B

2021-02-16 11:03 UTC, BarnyShergold commented
@wassuupp - The tests keep failing - please can you check these and see if there is any reason why you changes maybe affecting this

2021-02-21 18:24 UTC, wassuupp commented
@magento run all tests

2021-02-21 20:38 UTC, wassuupp commented
@magento run Unit Tests

2021-02-22 07:36 UTC, wassuupp commented
@magento run all tests

2021-03-04 07:50 UTC, wassuupp commented
@magento run all tests

2021-03-04 15:17 UTC, nuzil commented
Closing as there are full mess in source branch. New one is coming

2021-03-04 15:17 UTC, closed without merging