#1843: Media Gallery grid is scrolled down when text doesn't pass the validation on Edit Image page
magento/magento2 pull request #30141
Opened 2020-09-22 09:34 UTC by yolouiese

### Description (*)
This PR fixes the scrolling feature of the page when the Media Gallery edit modal is opened and the validation script is triggered.

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1843: Media Gallery grid is scrolled down when text doesn't pass the validation on Edit Image page

### Manual testing scenarios (*)
**Preconditions**
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Several images added to Media Gallery

**Steps to reproduce**
1. Go to Content - Media Gallery, select the first image from the grid
2. Click "three dots" and select Edit
3. Type not valid symbol into New Tag field, asterisk (*) for example
4. Click Save
5. Observe the behavior of the Media Gallery, behind the Edit Image window

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-22 09:34 UTC, yolouiese commented
@magento run all tests

2020-09-22 14:22 UTC, yolouiese commented
@magento run all tests

2020-09-23 10:24 UTC, sivaschenko requested changes
Thanks for the PR @yolouiese ! Please see my comment

2020-09-23 10:24 UTC, sivaschenko commented on app/code/Magento/MediaGalleryUi/view/adminhtml/requirejs-config.js
> +                'Magento_MediaGalleryUi/js/lib/mage/validation-mixin': true
Can we avoid mixin creation and fix the issue either in `mage/validator` directory or adjusting validation usage on Media Gallery side

2020-09-24 13:07 UTC, yolouiese commented
@magento run all tests

2020-11-11 22:34 UTC, sidolov commented
@yolouiese  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-11-11 22:34 UTC, closed without merging