Return correct type
magento/magento2 pull request #30160
Opened 2020-09-23 11:18 UTC by kassner

### Description

`Boolean` and `bool` aren't the same thing for static analysis tools.

### Manual testing scenarios

1. Overwrite `\Magento\Framework\Logger\Monolog` with a class that you own;
2. Run `psalm` against your class;
3.
```
ERROR: UndefinedDocblockClass - app/code/Vendor/Module/Model/Logger.php:15:16 - Docblock-defined class or interface Magento\Framework\Logger\Boolean does not exist (see https://psalm.dev/200)
        return parent::addRecord($level, $message, $context);
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-23 11:23 UTC, ihor-sviziev commented
@magento run all tests

2020-09-23 18:29 UTC, ihor-sviziev requested changes
Hi @kassner ,
Could you also fixe the static test for changed file? Thank you!

2020-09-25 08:07 UTC, kassner commented
Error seems to be unrelated to my change, so I am not sure which approach is desired.

2020-09-25 08:43 UTC, ihor-sviziev commented
@magento run Static Tests

2020-09-25 08:45 UTC, ihor-sviziev commented
@magento run all tests

2020-09-25 09:49 UTC, ihor-sviziev approved these changes

2020-09-25 09:50 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8271](https://jira.corp.magento.com/browse/ENGCOM-8271) has been created to process this Pull Request

2020-09-30 02:11 UTC, merged