Fix docblock annotation for PublisherInterface message
magento/magento2 pull request #30180
Opened 2020-09-24 07:03 UTC by kolaente

### Description (*)

The message on the publisher interface's `publish` method currently has a docblock annotation of `array|object`. However, since this type can be anything other than array or object as long as it's defined in the `communication.xml` this docblock annotation creates confusion. The docblock annotation is therefore wrong. This PR fixes that.

### Related Pull Requests

### Manual testing scenarios (*)

Since this is a doc change, I'm not sure if there's any manual testing scenarios? Please tell me if I'm wrong.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-24 09:16 UTC, rogyar requested changes
Hi @kolaente. Please, sign Adobe CLA. So we can proceed with processing the PR.

Thank you

2020-09-24 09:22 UTC, kolaente commented
@rogyar Done!

2020-09-24 16:33 UTC, sidolov commented
@magento create issue

2020-09-28 12:36 UTC, rogyar submitted a review, later dismissed

2020-09-28 12:37 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8277](https://jira.corp.magento.com/browse/ENGCOM-8277) has been created to process this Pull Request

2020-09-28 12:50 UTC, engcom-Alfa commented
QA not applicable

2020-09-28 13:34 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-28 16:17 UTC, sidolov commented
Static tests are failed.

2020-09-29 11:07 UTC, engcom-Foxtrot commented
@kolaente param type should be specified. Please use "mixed".

2020-09-29 11:34 UTC, engcom-Foxtrot commented on lib/internal/Magento/Framework/MessageQueue/PublisherInterface.php
> +     * @param $data
```suggestion
     * @param mixed $data
```

2020-09-29 11:35 UTC, engcom-Foxtrot requested changes

2020-09-29 11:35 UTC, engcom-Foxtrot commented on lib/internal/Magento/Framework/MessageQueue/PublisherInterface.php
> +     * @param $data
```suggestion
     * @param mixed $data
```

2020-09-29 14:26 UTC, kolaente commented on lib/internal/Magento/Framework/MessageQueue/PublisherInterface.php
> +     * @param $data
Done!

2020-09-29 14:28 UTC, kolaente commented
@engcom-Foxtrot @sidolov Should be fixed now.

2020-09-30 14:40 UTC, engcom-Foxtrot commented
@magento run all tests

2020-09-30 14:40 UTC, engcom-Foxtrot approved these changes

2020-10-01 12:39 UTC, engcom-Foxtrot commented
@sidolov fixed.

2020-10-02 13:06 UTC, merged