30179: resetPassword mutation returns generic error
magento/magento2 pull request #30230
Opened 2020-09-29 12:02 UTC by sudheers-kensium

[GraphQL] resetPassword mutation returns generic error

### Description (*)

While implementing resetPassword functionality into PWA, an engineer ran into a problem that resulted in this generic error response: Cannot set the customer's password. It took digging through the exception log to discover the provided password didn't meet the minimum password requirements, which was not in the error message.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30179: [GraphQL] resetPassword mutation returns generic error

### Manual testing scenarios (*)

1. Execute requestPasswordResetEmail mutation and extract token from email
2. Execute resetPassword mutation with a weak password in newPassword field

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-09-29 17:22 UTC, rogyar requested changes
Hi @sudheers-kensium thank you for providing the fix. Could you, please, cover the fix with an API-functional test (or modify an existing one). Basically, the test will check that for different errors, different messages will be returned. 

Thank you!

2020-09-30 16:12 UTC, prabhuram93 requested changes

2020-09-30 16:12 UTC, prabhuram93 commented on app/code/Magento/CustomerGraphQl/Model/Resolver/ResetPassword.php
> +            throw new GraphQlInputException(__('The password must be at least 8 characters long, minimum of 3 different classes of characters: Lower Case, Upper Case, Digits, Special Characters.'), $
@sudheers-kensium we try not add new phrases. $e->getMessage() should bubble up the exceptions from the api, which will be more meaningful and is the scope of this bug. $this->customerAccountManagement->resetPassword throws Input Exceptions, you can catch them in the resolver to give meaningful error responses back. For example, I see a bunch of meaningful validations here \Magento\Customer\Model\AccountManagement::checkPasswordStrength
Once you're able to get those messages, you can cover a couple in api functional tests, just to make sure the validation errors are being thrown.

2020-10-04 20:45 UTC, prabhuram93 commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/ResetPasswordTest.php
> +    public function testNewPasswordCheckCharactersStrenth()
minor fix, type here for Strength.

2020-10-04 20:46 UTC, prabhuram93 approved these changes

2020-10-08 08:29 UTC, rogyar approved these changes

2020-10-08 08:32 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8321](https://jira.corp.magento.com/browse/ENGCOM-8321) has been created to process this Pull Request

2020-10-09 11:26 UTC, nrkapoor commented
@magento run all tests

2020-10-10 20:14 UTC, merged