Improve dependency tests
magento/magento2 pull request #30331
Opened 2020-10-03 21:30 UTC by swnsma

### Description (*)
Resolve issues of running Dependency Tests for not Github installation.
Add Tests Coverage for \Magento\TestFramework\Dependency\Route\RouteMapper.
Fix failed tests when Route Id and Front Name can be different in routes.xml

2020-10-03 21:38 UTC, swnsma commented
@magento create issue

2020-10-04 11:51 UTC, swnsma commented
@magento run all tests

2020-10-07 14:25 UTC, ihor-sviziev commented
@swnsma could you add more details for your changes?

2020-10-07 14:37 UTC, swnsma commented
Hi @ihor-sviziev

1. Change searching of module folder and files from 'app/code' to it's real location for Route Mapper.
2. Change searching module name based on its path (like app/code/Magento/Module) to it's real name, independently from the path for DeclarativeSchemaDependencyProvider.
3. Add tests coverage for Route Mapper.
4. Fix route mapper to search dependency by route front name (for `getUrl` method it does not matter if you pass front name or router id).
5. Fix Dependency Test: now it starts to collect DB configs from modules folder instead of using pattern (app/code/*/*/etc/db_schema_whitelist.json).

2020-10-07 14:55 UTC, ihor-sviziev requested changes

2020-10-07 14:55 UTC, ihor-sviziev commented on dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php
>                      ]
```suggestion
                    [
                        self::SCHEMA_ENTITY_TABLE => [
                            $tableName => $tableDeclaration,
                        ]
                    ]
```

2020-10-07 14:55 UTC, ihor-sviziev commented on dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php
> +            $dbSchemaWhitelist = (array)json_decode(file_get_contents($file->getFullPath()));
https://www.php.net/manual/en/function.json-decode.php
![image](https://user-images.githubusercontent.com/1873745/95345707-b1d36c00-08c3-11eb-9a31-dfed3698ff9d.png)

```suggestion
            $dbSchemaWhitelist = json_decode(file_get_contents($file->getFullPath()), true);
```

2020-10-07 14:55 UTC, ihor-sviziev commented on dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php
> +            $dbSchemaWhitelist = (array)json_decode(file_get_contents($file->getFullPath()));
```suggestion
            $dbSchemaWhitelist = json_decode(file_get_contents($file->getFullPath()), true);
```

2020-10-07 19:51 UTC, ihor-sviziev commented
@magento run all tests

2020-10-07 21:56 UTC, ihor-sviziev requested changes
Hi @swnsma ,
Static tests are failing, could you check why?

2020-10-08 06:37 UTC, swnsma commented
@magento run Static Tests

2020-10-08 07:32 UTC, swnsma commented
@magento run all tests

2020-10-09 21:23 UTC, ihor-sviziev commented
@magento run all tests

2020-10-10 16:04 UTC, ihor-sviziev requested changes
@swnsma tests still failing, please fix them

2020-10-10 18:34 UTC, swnsma commented
Hi @ihor-sviziev,
Fix for failed test is in security repo PR (please see related PRs).
So I can not fix in in current repository.

2020-10-12 07:49 UTC, ihor-sviziev commented
@magento run all tests

2020-10-12 12:20 UTC, ihor-sviziev commented
@sidolov @slavvka could you help with running tests with related Pull Request? Seems like it doesn't work by now.

2020-10-12 12:21 UTC, ihor-sviziev commented
@magento run WebAPI Tests, Functional Tests B2B, Functional Tests EE, Functional Tests CE

2020-10-12 14:51 UTC, sidolov commented
@ihor-sviziev it was an issue with PR format, I have changed it, and builds should work

2020-10-12 15:15 UTC, ihor-sviziev commented
@magento run Static Tests

2020-10-12 15:17 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Functional Tests B2B

2020-10-12 17:31 UTC, ihor-sviziev commented
@magento run Functional Tests CE

2020-10-12 17:32 UTC, ihor-sviziev approved these changes

2020-10-12 17:33 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8330](https://jira.corp.magento.com/browse/ENGCOM-8330) has been created to process this Pull Request

2020-10-15 10:42 UTC, engcom-Bravo commented
QA not applicable

2020-10-15 14:37 UTC, swnsma commented
Hi, @ihor-sviziev!

There is not only bug fixing but also tests coverage. Should be Award 'Test coverage' added?

2020-11-16 10:43 UTC, ihor-sviziev requested changes
Hi @swnsma ,
Could you resolve conflict?

2020-11-23 12:25 UTC, engcom-Foxtrot commented
@magento run all tests

2020-12-07 14:36 UTC, ihor-sviziev commented
@magento run all tests

2020-12-17 10:03 UTC, swnsma commented
@magento run all tests

2020-12-18 08:41 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2020-12-18 11:36 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2020-12-20 16:16 UTC, swnsma commented
@magento run Functional Tests B2B

2020-12-21 08:10 UTC, ihor-sviziev commented
@engcom-Foxtrot tests are passing now ✔

2021-03-03 20:52 UTC, swnsma commented
Hi @engcom-Foxtrot,

Is there anything else should be done in this PR?

2021-03-03 20:52 UTC, swnsma commented
@magento run all tests

2021-03-04 08:01 UTC, ihor-sviziev commented
@swnsma I think this PR is stuck because we still have not processed higher priority PRs

2021-03-05 06:58 UTC, ihor-sviziev commented
@magento run Database Compare, Functional Tests EE, Static Tests, WebAPI Tests

2021-03-05 11:52 UTC, ihor-sviziev commented
@sidolov @gabrieldagama could you tell why the static tests are failing?

2021-03-21 19:12 UTC, swnsma commented
@magento run  Functional Tests EE, Static Tests, WebAPI Tests

2021-03-22 09:33 UTC, ihor-sviziev requested changes
@swnsma, it looks like the dependency test you were fixing is failing, so behavior has changed. Please double-check that.

2021-04-16 10:03 UTC, swnsma commented
@magento run all tests

2021-04-18 14:04 UTC, swnsma commented
@magento run all tests

2021-04-18 17:45 UTC, ihor-sviziev commented
@magento run all tests

2021-09-11 09:16 UTC, swnsma commented
@magento run all tests

2021-09-12 13:13 UTC, swnsma commented
@magento run all tests

2024-10-23 11:35 UTC, engcom-Dash commented
Hello @swnsma,

Thank you for your contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks again!

2024-11-07 10:05 UTC, engcom-Dash commented
Closing this PR since it has not been updated in a while. Please feel free to reopen if needed.

2024-11-07 10:05 UTC, closed without merging