Allow to cache search results
magento/magento2 pull request #30340
Opened 2020-10-05 07:54 UTC by alinalexandru

### Description (*)
Starting version 2.2.4, search result page can be cached, but varnish vcl has a rule to not cache the page.

### Manual testing scenarios (*)
1. Configure magento to use varnish for FPC
2. Do a search with one of the top 100 searches (default value), or set `Number of top search results to cache` to 0 (this will set to cache all the results)
3. Do the same query, to see if you hit the cache.

Actual result:
- The search page is not cached.

Expected result:
- The search page should be delivered from cache

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-06 12:33 UTC, rogyar requested changes
Hi @alinalexandru. Thank you for your collaboration. From my point of view, we cannot allow all `/catalogsearch` pages to be cached by Varnish since this behavior goes against the idea of "Cacheable Search Terms". If we allow caching 100 popular items it applies only to the limited amount of pages.

https://github.com/magento/magento2/blob/c1cbd005dd2980c82641afb4dd86484ae12397bf/app/code/Magento/CatalogSearch/Controller/Result/Index.php#L108

If we allow Varnish to cache `/catalogsearch` URLs, it may affect not only "popular" search terms but all search pages. Considering the fact that we may have an infinite number of different catalog search queries in the URL, it may be a good way to overflow the Varnish storage.

Please, correct me if I'm wrong.

2020-10-06 18:24 UTC, alinalexandru commented
@rogyar
Removing this line tells Varnish that it **can** cache the page if Magento allows it by sending corresponding headers.
If that condition is there, Varnish **will not** cache that page, no matter what Magento tells Varnish to do.

Magento will be in charge to decide if that page can be cached or not. In the current implementation, the search result page can be cached only if it's a popular search and it doesn't have any other get parameters. 

You can see what happens if the page **should not** be cached:
- https://github.com/magento/magento2/blob/c1cbd005dd2980c82641afb4dd86484ae12397bf/app/code/Magento/CatalogSearch/Controller/Result/Index.php#L167
- https://github.com/magento/magento2/blob/c1cbd005dd2980c82641afb4dd86484ae12397bf/lib/internal/Magento/Framework/App/Response/Http.php#L156

2020-10-09 07:48 UTC, alinalexandru commented
@rogyar 
What's your feedback regarding what I have wrote?
Is there something that I am missing?

2020-10-12 13:41 UTC, rogyar commented
Hi @alinalexandru. Not it totally makes sense. Thanks a lot for the explanation and examples.

2020-10-12 13:41 UTC, rogyar commented
@magento run all tests

2020-10-12 16:22 UTC, rogyar approved these changes

2020-10-12 16:23 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8329](https://jira.corp.magento.com/browse/ENGCOM-8329) has been created to process this Pull Request

2020-10-12 16:23 UTC, magento-engcom-team commented
@alinalexandru thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2020-10-16 07:00 UTC, engcom-Alfa commented
@magento create issue

2020-10-16 07:40 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

### Case 1

**Manual testing scenario:**

1. Configure magento to use varnish for FPC
2. Do a search with one of the top 100 searches (default value), or set Number of top search results to cache to 0 (this will set to cache all the results)
3. Do the same query, to see if you hit the cache.

**Before:** :heavy_multiplication_x: The search page is not cached.

![Peek 2020-10-16 10-22](https://user-images.githubusercontent.com/51679138/96226353-2892f800-0f9b-11eb-9cee-9a73e96dcc53.gif)

**After:** :heavy_check_mark:  The search page was delivered from the cache

![2020-10-16_09-44](https://user-images.githubusercontent.com/51679138/96226467-5a0bc380-0f9b-11eb-944a-f1ed74c36c38.png)

![Peek 2020-10-16 10-20](https://user-images.githubusercontent.com/51679138/96226457-537d4c00-0f9b-11eb-88a2-7cea2f025ff2.gif)

### Case 2

**Manual testing scenario:**

1. Configure magento to use varnish for FPC
2. Go to Admin -> Stores -> Configuration -> Catalog -> Catalog -> Catalog Search and ser **Number of top search results to cache** to **2** (this will set to cache 2 terms)
3. Do the same query, to see if you hit the cache.

After: :heavy_check_mark: Only 2 search queries were cached, all subsequent queries are not

2020-10-21 20:37 UTC, merged