Fixed Redirect to the store view when trying to save attribute on product creation page
magento/magento2 pull request #30400
Opened 2020-10-10 07:19 UTC by shikhamis11

#30362: Fixed Redirect to the store view when trying to save attribute on product creation page

Preconditions (*)

Magento 2.4-develop
Steps to reproduce (*)

    Go to Catalog -> Products -> Add New Product
    Click on the "Add Attribute" button (Upper right corner)
    Click on the "Create New Attribute" button
    Close the opened window
    Click on the "Create New Attribute" button again
    Close the opened window
    Click on the "Create New Attribute" button again
    Enter "Attribute Label", set type to drop-down and add two values -> Save

Expected result (*)

No redirect. Attribute is saved.
Actual result (*)
https://user-images.githubusercontent.com/30689417/95333312-48e4f780-08b5-11eb-884d-a2100962d1e7.gif
Redirect to the Home Page if trying to save a attribute on product creation page. Attribute isn`t saved

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-10 07:56 UTC, shikhamis11 commented
@magento give me test instance

2020-10-10 08:26 UTC, shikhamis11 commented
@magento run all tests

2020-10-10 08:30 UTC, vijay-wagento commented
#dmcdindia2020

2020-10-10 13:12 UTC, rogyar requested changes
Hi @shikhamis11. Thank you for your collaboration. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by autotests. Could I ask you to cover you fix by an MFTF test, please? 

Thank you!

2020-10-12 12:04 UTC, shikhamis11 commented
hi @rogyar 
Thanks for the review .
wanted to confirm , do you want me to create add MFTF test coverage with this scenario ? 

Go to Catalog -> Products -> Add New Product
Click on the "Add Attribute" button (Upper right corner)
Click on the "Create New Attribute" button
Close the opened window
Click on the "Create New Attribute" button again
Close the opened window
Click on the "Create New Attribute" button again
Enter "Attribute Label", set type to drop-down and add two values -> Save

2020-10-15 16:30 UTC, rogyar commented
Hi @shikhamis11. Yes, that's right. Not literally all the steps. For example, you may use a fixture for product creation instead of adding it, etc. See the following example that shows fixtures in action

https://github.com/magento/magento2/blob/2c8b12adc2b35d1ed701c7b018b0b8cee4b665ce/app/code/Magento/Catalog/Test/Mftf/Test/AdminCheckConfigurableProductPriceWithDisabledChildProductTest.xml#L28

https://github.com/magento/magento2/blob/2c8b12adc2b35d1ed701c7b018b0b8cee4b665ce/app/code/Magento/Catalog/Test/Mftf/Test/AdminCheckConfigurableProductPriceWithDisabledChildProductTest.xml#L60

Hope it's helpful

2020-10-16 14:47 UTC, engcom-Hotel commented
Will help with tests.

2020-10-19 10:40 UTC, engcom-Hotel commented
Hi @shikhamis11 . I can't add MFTF to your changes. Could you please allow changes to a pull request branch using the following steps:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork
Thank you.

2020-10-19 11:16 UTC, shikhamis11 commented
@engcom-Hotel, there is no option for me to allow edits from maintainers , may be It's because I am using the fork repository of my organisation

2020-10-20 08:44 UTC, engcom-Hotel commented
Hello @shikhamis11 .
Please review the test and add it then.
[MFTF_coverage_has_been_added_.zip](https://github.com/magento/magento2/files/5407461/MFTF_coverage_has_been_added_.zip)
Thank you.

2020-10-21 11:32 UTC, shikhamis11 commented
@engcom-Hotel I have added MFTF test provided by you 
Thanks

2020-10-22 06:35 UTC, engcom-Hotel commented
@magento run all tests

2020-10-22 12:18 UTC, engcom-Hotel commented
Hello @shikhamis11 .
Could you please update the title of the test to make Stories + title combination unique.
Thank you.

2020-10-23 09:57 UTC, shikhamis11 commented
@magento run all tests

2020-10-27 10:16 UTC, rogyar commented
@shikhamis11. Thank you for providing the test. Just a suggestion. Next time, please, use action groups only for creating an MFTF test. It's part of the best practices and allows us to create reusable test actions instead of hardcoding them into the test body.

Thank you!

2020-10-27 10:16 UTC, rogyar approved these changes

2020-10-27 10:42 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8395](https://jira.corp.magento.com/browse/ENGCOM-8395) has been created to process this Pull Request

2020-10-27 12:08 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Go to Catalog -> Products -> Add New Product
2. Click on the "Add Attribute" button (Upper right corner)
3. Click on the "Create New Attribute" button
4. Close the opened window
5. Click on the "Create New Attribute" button again
6. Close the opened window
7. Click on the "Create New Attribute" button again
8. Enter "Attribute Label", set the type to drop-down and add two values -> Save

Actual Result:
The Attribute is created and added to the Product. No error messages appear in dev console
![attribute_created](https://user-images.githubusercontent.com/51680745/97299594-d9cc4480-185d-11eb-8fdc-3a26b51141b9.png)
![Peek 2020-10-27 14-04](https://user-images.githubusercontent.com/51680745/97299614-e18be900-185d-11eb-9af6-c1a71339517b.gif)

2020-11-09 10:38 UTC, gabrieldagama commented
@magento run all tests

2020-11-13 13:34 UTC, merged