Fixed #29698 [2.3.5-p2] Total due is not updated when order is completed with canceled items
magento/magento2 pull request #30401
Opened 2020-10-10 07:39 UTC by amitvishvakarma

Fixed #29698
### Preconditions (*) 

Magento 2.3.5-p2
Doesn`t reproducible on 2.4-develop

### Steps to reproduce (*)
1.Place an order with items where the quantity is more than 1
2.Create an invoice & shipment for the order partially
3.Cancel the rest of the order items by canceling the order

### Expected result (*)
1.Total due should be 0 since the order status is 'complete'
2.Grand total and other relevant fields should also reflect the price difference

### Actual result (*)
1.Total due shows the remaining unpaid amount even though the order status is 'complete'
2.Grand total remains same

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-10 08:30 UTC, vijay-wagento commented
#dmcdindia2020

2020-10-10 13:19 UTC, rogyar requested changes
Hi @amitvishvakarma. Thank you for providing the fix. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by autotests. Could I ask you to cover your changes with an MFTF or integration test, please? 

Thank you!

2020-10-19 07:47 UTC, engcom-Charlie commented
Hi @amitvishvakarma  could you please cover your changes with an MFTF or integration test?
Thank you!

2020-10-23 09:35 UTC, engcom-Charlie commented
We are closing this PR because
> Magento is focusing development efforts on v2.4, so we are no longer accepting pull requests to the v2.3, v2.2, v2.1, and v2.0 release lines.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules) for more details

Thank you for your collaboration.

2020-10-23 09:35 UTC, closed without merging