29217: Fixed -  Prefix and Suffix Translation
magento/magento2 pull request #30413
Opened 2020-10-10 09:29 UTC by solwininfotech

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29217  Prefix and Suffix Translation

### After Fixing Code (*)

After Fix:

Checkout Page
![checkout_page](https://user-images.githubusercontent.com/16253886/95651557-dc623680-0b08-11eb-836f-c1b7d3164847.png)

Account Details Edit Page
![address-edit-page](https://user-images.githubusercontent.com/16253886/95651564-e84df880-0b08-11eb-8bf0-dccbd0a699bf.png)

Create Account page
![registration-page](https://user-images.githubusercontent.com/16253886/95651572-f4d25100-0b08-11eb-87b5-babaa688ad8c.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-10 09:34 UTC, solwininfotech commented
@magento give me test instance

2020-10-10 09:35 UTC, solwininfotech commented
#dmcdindia2020

2020-10-10 09:36 UTC, solwininfotech commented
@magento run all tests

2020-10-10 10:26 UTC, solwininfotech commented
@magento give me test instance

2020-10-10 13:37 UTC, rogyar requested changes

2020-10-10 13:37 UTC, rogyar commented on app/code/Magento/Customer/Block/Address/Renderer/DefaultRenderer.php
> +                if(in_array($attributeCode,['prefix','suffix'])) {
Please, make sure you use a proper indentation for your code

2020-10-10 13:37 UTC, rogyar commented
Hi @solwininfotech. Thank you for your contribution. Please, check my comments above as well as the failing static tests. 

Thank you!

2020-10-12 04:46 UTC, solwininfotech commented
Hi @rogyar 
Thank you for reviewing it, I am working on your sugession.

2020-10-12 12:55 UTC, solwininfotech commented
@magento run all tests

2020-10-13 12:05 UTC, solwininfotech commented
@magento run all tests

2020-10-13 12:25 UTC, solwininfotech commented
@rogyar,  changes that have been done and pushed.

2020-10-17 11:35 UTC, rogyar commented
Hi @solwininfotech. Please, check the failing static tests
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30413/e4cd3306770880fb95b2e6a9459b2b61/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/352209e68147c7d7/

2020-10-20 12:02 UTC, solwininfotech commented
@magento run Static Tests

2020-10-21 09:50 UTC, solwininfotech commented
@magento run Static Tests

2020-10-21 10:05 UTC, solwininfotech commented
@magento run Static Tests

2020-10-21 11:13 UTC, solwininfotech commented
@magento run all tests

2020-10-22 17:27 UTC, solwininfotech commented
@rogyar, Static test is passed now, I have checked for failed tests, it shows failed in other files which are not updated in this commit. 
Please help.

2020-10-27 08:17 UTC, rogyar approved these changes
Not sure we will be able to cover it with autotests somehow

2020-10-27 08:28 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8391](https://jira.corp.magento.com/browse/ENGCOM-8391) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-10-27 16:36 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario
1.From admin panel, go to Stores -> Configuration -> Customers -> Customer Configuration -> Name and Address Options.  Set the following options:
- Show Prefix = Required
- Prefix Dropdown Options = Ms.;Mr.;Mrs. (Use Semicolon (;) to separate values)
- Show Suffix = Required
- Suffix Dropdown Options = Jr.;Sr.;MD.(Use Semicolon (;) to separate values)
![name_address options](https://user-images.githubusercontent.com/51680745/97331172-be733080-1881-11eb-9ee1-b5336169c68b.png)
2. Install German language pack 
3. Add the following `"Mr.","Herr" "Ms.","Frau"` to the de_DE.csv file like this:
![storm_de](https://user-images.githubusercontent.com/51680745/97331324-eebacf00-1881-11eb-866c-24939c10e735.png)
4. Create a new Store view
5. Go to Stores - Configuration, change the Scope to the previously created Storeview
6. Change the Locale to _German (Germany)_
![locale_config](https://user-images.githubusercontent.com/51680745/97331937-9801c500-1882-11eb-9067-b5a347c68e0a.png)
7. Go to Storefront and switch to the previously created German Storeview
8. Add any product to Cart and click Proceed to Checkout 
9. Observe the _Namenspräfix_ dropdown

**Before** applying changes provided in this PR
![mrms](https://user-images.githubusercontent.com/51680745/97332553-40178e00-1883-11eb-9d12-2c93cbf02404.png)

**After** switching to the PR
![mrms_after](https://user-images.githubusercontent.com/51680745/97332623-50c80400-1883-11eb-9cfb-84c660a08bef.png)

2022-11-24 17:06 UTC, merged