Remove incorrect use important in swatches option text
magento/magento2 pull request #30454
Opened 2020-10-12 15:11 UTC by mrtuvn

### Description (*)

Developers will not able re-define styles in swatch option text when core file defined important
Here is example

`.catalog-product-view .swatch-option.text.selected {
    background-color: black;
}`

will not able apply when core magento defined important 

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-12 15:15 UTC, mrtuvn commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
>          }
unneccesary define z-index

2020-10-12 19:43 UTC, ptylek requested changes
@mrtuvn Can you please add manual testing scenarios so QA can check if `selected` styling for swatch option text works properly after the change? Looks ok, but would wait for static tests to complete.

2020-10-13 01:57 UTC, mrtuvn commented
i have updated manual testing scenarios

2020-10-13 06:13 UTC, ptylek commented
@magento run Static Tests

2020-10-13 12:14 UTC, mrtuvn commented
@magento run Database Compare, Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests, Magento Health Index, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B, Unit Tests, WebAPI Tests

2020-10-13 23:48 UTC, mrtuvn commented
@magento run Semantic Version Checker

2020-10-14 06:38 UTC, ptylek approved these changes
Thanks @mrtuvn. Needs manual testing to check if `selected` styling for swatch option text stays the same as before change.

2020-10-14 06:39 UTC, magento-engcom-team commented
Hi @ptylek, thank you for the review.
[ENGCOM-8341](https://jira.corp.magento.com/browse/ENGCOM-8341) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-10-15 07:55 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1 .Create custom style less file for reproduce approach add style to swatch option text;
2. Path file can be _app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_extend.less_
3. In file **_extend.less** add style like description 
ex:
```less
body .swatch-attribute .swatch-option.text.selected { background-color: black; }
```
4. Run cache clean and deploy static content
5. Go to a category with a product on Storefront;

**Before:** :heavy_multiplication_x: Background color is still white

![Peek 2020-10-15 09-45](https://user-images.githubusercontent.com/51679138/96093255-9aecd500-0ed4-11eb-8340-faf67da43f4d.gif)

**After:** :heavy_check_mark: Background color is black

![Peek 2020-10-15 09-47](https://user-images.githubusercontent.com/51679138/96093347-b22bc280-0ed4-11eb-87da-8cf5a40fe634.gif)

### Scenario 2

No customise styles

**After:** :heavy_check_mark: Selected swatch option have background-color white

![Peek 2020-10-15 10-36](https://user-images.githubusercontent.com/51679138/96093469-d9828f80-0ed4-11eb-8a69-13d2255c67d4.gif)

2020-10-15 08:05 UTC, engcom-Alfa commented
@magento create issue

2020-10-16 13:36 UTC, merged