Frontend area layout xml improvements.
magento/magento2 pull request #30539
Opened 2020-10-19 08:50 UTC by sanganinamrata

### Description (*)

Remove `class="Magento\Framework\View\Element\Template"` from frontend layout xml files, as `"Magento\Framework\View\Element\Template"` is the default class taken by Magento.

### Related Pull Requests

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-19 09:05 UTC, rogyar commented
@magento run all tests

2020-10-19 18:14 UTC, sidolov commented
@magento create issue

2020-10-21 08:20 UTC, rogyar commented
@magento run Integration Tests

2020-10-27 10:11 UTC, rogyar commented
@magento run all tests

2023-09-19 08:23 UTC, fredden approved these changes

2023-09-19 08:23 UTC, fredden commented on app/code/Magento/Theme/view/frontend/layout/default.xml
> +      <attribute name="id" value="html-body"/>
This change looks accidental / unintentional.

2024-02-09 09:30 UTC, engcom-Delta commented
Hi @sanganinamrata, Thanks for your contribution.Please resolve the conflicts to move ahead on this PR

2024-02-12 06:08 UTC, engcom-Delta requested changes
Please resolve the conflicts

2024-11-07 09:44 UTC, engcom-Dash commented
Hello @sanganinamrata,

Thanks for the contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks.

2024-12-02 10:03 UTC, engcom-Dash commented
Hello @sanganinamrata,

This is a reminder to resolve the conflicts.

Thanks!

2024-12-13 10:09 UTC, engcom-Dash commented
Closing this PR since it has not been updated in a while. Please feel free to reopen it if needed.

2024-12-13 10:09 UTC, closed without merging