Updated string with Static key.
magento/magento2 pull request #30579
Opened 2020-10-21 09:26 UTC by ejaz-alam

#30545 
Update string with the static key in function.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-21 09:26 UTC, ejaz-alam commented
@magento run all tests

2020-10-21 11:29 UTC, ejaz-alam commented
@rogyar please review this.

2020-10-21 13:20 UTC, ihor-sviziev requested changes

2020-10-21 13:20 UTC, ihor-sviziev commented on app/code/Magento/Quote/Model/Quote/Address.php
> +    const CACHED_ITEMS_ALL = 'cached_items_all';
Could you make this constant private in order to make your change backward compatible?
```suggestion
    private const CACHED_ITEMS_ALL = 'cached_items_all';
```

2020-10-21 13:27 UTC, ihor-sviziev commented
@magento run all tests

2020-10-21 17:07 UTC, ihor-sviziev approved these changes

2020-10-21 17:09 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8364](https://jira.corp.magento.com/browse/ENGCOM-8364) has been created to process this Pull Request

2020-10-22 08:21 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Checked functionality associated with adding products to the cart, creating orders and everything works as previous ( expected).

2020-10-24 13:48 UTC, merged