Fix issue with products GET request being cached despite category positions change
magento/magento2 pull request #30636
Opened 2020-10-24 06:47 UTC by Zifius

"in" condition not tested

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30467

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-24 11:11 UTC, rogyar commented
@Zifius please, feel free to ping me if you need any help with that.

2020-11-03 20:29 UTC, cpartica commented
@Zifius  your fix looks good, you should open the PR and complete a test.
I think there's some integration tests done on tags as inspiration

2020-11-03 20:29 UTC, cpartica requested changes

2020-11-03 20:29 UTC, cpartica commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php
> +        if (isset($args['filter'])) {
you only need some tests, fix looks good

2020-11-09 15:57 UTC, Zifius commented
Thanks @cpartica, unfortunately community slack doesn't keep the history of our 1to1 chat, so the question is would you prefer changing \Magento\GraphQl\Catalog\ProductSearchTest::testSortByPosition() (https://github.com/magento/magento2/blob/2.4-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductSearchTest.php#L1114) which seems to be testing exactly this functionality but currently passing (I suppose the test is incomplete or incorrect, but need to debug it to see what's really going on there) or creating a new test?

2020-11-12 14:28 UTC, rogyar commented
Just from my point of view, I would suggest adjusting an existing test case instead of introducing a new one with a very similar purpose. 

Not sure my assumption makes sense. But the existing test might work and the reason for that is utilizing disk/Redis cache for FPC instead of Varnish. But I might be wrong.

2020-11-23 19:12 UTC, cpartica commented
> Just from my point of view, I would suggest adjusting an existing test case instead of introducing a new one with a very similar purpose.
> 
> Not sure my assumption makes sense. But the existing test might work and the reason for that is utilizing disk/Redis cache for FPC instead of Varnish. But I might be wrong.

Yes we can't test Varnish yet, but we sure can do disk builtin cache with the help of integration tests

2020-11-26 21:09 UTC, Zifius commented
Thank you @rogyar and @cpartica both for the replies. I've now created the test

2020-11-26 21:48 UTC, Zifius commented
@magento run WebAPI Tests

2020-11-27 10:04 UTC, rogyar commented
@magento run WebAPI Tests

2020-11-30 09:01 UTC, engcom-Charlie commented
@magento run all tests

2020-11-30 14:15 UTC, Zifius commented
@magento run Integration Tests

2020-11-30 19:32 UTC, Zifius commented
@magento run all tests

2020-12-01 13:24 UTC, rogyar approved these changes
Approved. The failing functional tests are not related to the current changeset.

2020-12-01 13:25 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8504](https://jira.corp.magento.com/browse/ENGCOM-8504) has been created to process this Pull Request

2020-12-01 17:56 UTC, cpartica approved these changes

2020-12-04 14:42 UTC, merged