29901: GraphQL mutation uptdateCartItems return data is incorrect when removing multiple items
magento/magento2 pull request #30648
Opened 2020-10-26 04:59 UTC by sudheers-kensium

GraphQL mutation uptdateCartItems return data is incorrect when removing multiple items

### Description (*)

1. Add a set of items to cart (minimum 2)
2. Using the graphQL mutation updateCartItems set multiple or all of the item quantities to 0

query

``mutation {
  updateCartItems(
    input: {
      cart_id: {{cartID}}",
      cart_items: [
        {
          cart_item_id: 1
          quantity: 0
        },
        {
          cart_item_id: 2
          quantity: 0
        },
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          name
        }
        quantity
      }
      prices {
        grand_total{
          value
          currency
        }
      }
    }
  }
}
``
3. Expected cart data where all items that were set to a quantity of 0 to be removed

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29901

### Manual testing scenarios (*)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-26 05:00 UTC, sudheers-kensium commented
@magento run all tests

2020-10-26 07:22 UTC, sudheers-kensium commented
@magento run Functional Tests CE

2020-10-26 08:32 UTC, sudheers-kensium commented
@magento run Functional Tests EE

2020-10-26 10:42 UTC, sudheers-kensium commented
@magento run Functional Tests B2B

2020-10-26 13:24 UTC, sudheers-kensium commented
@magento run Functional Tests EE

2020-10-26 18:46 UTC, rogyar requested changes
Hi @sudheers-kensium. Thanks for your contribution. That a solid piece of work. Please, check my suggestions below. 
It's strongly recommended to keep best practices even when we are working with the fixtures. In the future, we will need to support them as a part of the codebase. 

Thank you!

2020-10-26 18:46 UTC, rogyar commented on app/code/Magento/QuoteGraphQl/Model/Resolver/UpdateCartItems.php
> +            $cart = $this->getCartForUser->execute($maskedCartId, $context->getUserId(), $storeId);
Could we try to achieve the same result without an additional database query? I mean, we already have all the details about the shopping cart. Most likely, we don't need an additional DB fetch, but the recalculation process that happens upon the DB fetch.

2020-10-26 18:46 UTC, rogyar commented on dev/tests/integration/testsuite/Magento/Checkout/_files/quote_with_multiple_items.php
> +$quote->save();
Please, avoid using deprecated methods in the code.

2020-10-26 18:46 UTC, rogyar commented on dev/tests/integration/testsuite/Magento/Checkout/_files/quote_with_multiple_items.php
> +$quote->save();
Please, avoid using deprecated methods in the code.

2020-10-26 18:46 UTC, rogyar commented on dev/tests/integration/testsuite/Magento/Checkout/_files/quote_with_multiple_items_saved.php
> +$quoteIdMask->save();
Please, avoid using deprecated methods in the code.

2020-10-26 18:46 UTC, rogyar commented on dev/tests/integration/testsuite/Magento/Checkout/_files/quote_with_multiple_items_saved_rollback.php
> +$quoteIdMask->delete($quote->getId());
Please, avoid using deprecated methods in the code.

2020-10-26 18:46 UTC, rogyar commented on dev/tests/integration/testsuite/Magento/Checkout/_files/quote_with_multiple_items.php
> +<?php
If we create new fixtures for GraphQL api-functional tests, I would strongly recommend using a dedicated place (directory) for that. Please, check the following fixtures as the example 

https://github.com/magento/magento2/tree/a5a98dfa56cac8cdb60e15568c10578f522be3f3/dev/tests/integration/testsuite/Magento/GraphQl/Quote/_files

(please, take a look at the files path)

2020-10-28 10:27 UTC, sudheers-kensium commented
@magento run all tests

2020-10-28 12:41 UTC, sudheers-kensium commented
@magento run all tests

2020-10-28 13:55 UTC, sudheers-kensium commented
@magento run all tests

2020-10-28 16:29 UTC, sudheers-kensium commented
@magento run Functional Tests B2B

2020-10-29 05:22 UTC, sudheers-kensium commented
@magento run Functional Tests B2B

2020-10-29 10:12 UTC, sudheers-kensium commented
@magento run Functional Tests B2B

2020-10-30 10:38 UTC, sudheers-kensium commented
@magento run Functional Tests B2B

2020-11-04 12:54 UTC, rogyar approved these changes

2020-11-04 12:55 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8423](https://jira.corp.magento.com/browse/ENGCOM-8423) has been created to process this Pull Request

2021-11-17 12:13 UTC, engcom-Alfa commented
Hi @rogyar & @sudheers-kensium 
Thanks for your contribution and collaboration!
I have tried to reproduce this issue and seems to be not reproducible. Kindly cross-check below steps I followed please!

1. Created a cart using GraphQL request.
2. Added 3 products with 2 quantity each as shown in the below screenshot.
<img width="1440" alt="Products added to Cart" src="https://user-images.githubusercontent.com/51679138/142193999-8676795d-b271-43df-852c-9fcb355bb6a4.png">
3. Updated the cart with zero quantity for 2 of the products among 3, and the screenshot is below
<img width="1440" alt="update to cart" src="https://user-images.githubusercontent.com/51679138/142194306-4dc3aa5e-5134-4894-8459-06a282ec53cb.png">
4. GraphQL queried that retrieves the cart products and list.
<img width="1440" alt="cart after updating" src="https://user-images.githubusercontent.com/51679138/142194431-c0915160-bdd0-4ba1-bffc-2507d66d66cc.png">

As defined in the [issue description](https://github.com/magento/magento2/issues/30220#issue-710370985), didn't notice any issue as such. Zeroed quantity is successfully ignored in the cart queried response.
Tested it in the 2.4-develop Magento instance, and I request you to kindly check if the issue is still existing. Since the issue was noticed many months back, it might have fixed with other PRs.

2021-11-17 12:14 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2021-11-23 06:54 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2021-11-24 14:55 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2022-04-14 10:36 UTC, engcom-Alfa commented
This issue is in the discussion, will be processed soon.
Thanks for your patience @rogyar & @sudheers-kensium

2022-08-24 11:00 UTC, engcom-Alfa commented
Hi @sudheers-kensium & @rogyar 
Thanks for your collaboration and contribution here.

Based on the [above-comment ](https://github.com/magento/magento2/pull/30648#issuecomment-971522834)and [today's comment update in issue](https://github.com/magento/magento2/issues/29901#issuecomment-1225561582), we are currently closing this PR ticket.
In case, if you find the same issue in the Magento code `2.4-develop` version, please re-update the _steps to reproduce_ here, or if there is any configurations or anything required to done to reproduce it. Or you may report a new PR as well. Based on that, we will re-consider it.

Thanks

2022-08-24 11:00 UTC, closed without merging