Initialize authentication popup modal only when needed
magento/magento2 pull request #30647
Opened 2020-10-25 09:29 UTC by krzksz

### Description (*)
This PR is somehow an evolution of the https://github.com/magento/magento2/pull/27686 in which I have found that it is not possible to completely skip initialization of authentication popup. That said, by adding this additional check, we are able to save a lot of CPU time for all of the shops that have guest checkout enabled.

Here are the profiles of before:
![auth-popup-before](https://user-images.githubusercontent.com/829189/97103431-c29a2500-16ac-11eb-8b4a-2508b5eef31d.png)
and after:
![auth-popup-after](https://user-images.githubusercontent.com/829189/97103435-c8900600-16ac-11eb-8a75-bb105d228b85.png)

### Manual testing scenarios (*)

1. `setModalElement` function is no longer called when guest checkout is enabled.
2. Authentication popup still shows properly when guest user tries to go to the checkout but guest checkout is disabled.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-25 11:10 UTC, mrtuvn commented
Nice works. This pr will make magento more become better place

2020-10-25 11:13 UTC, krzksz commented
@magento run all tests

2020-10-25 14:01 UTC, mrtuvn commented
Can you add minimal dependency js like closed PR 27686. Seem current authen-popup require seem a lot another components

2020-10-25 17:13 UTC, ihor-sviziev approved these changes
Seems like your changes causing regression. Could you review test failures and adjust your code accordingly?

2020-10-25 17:13 UTC, ihor-sviziev requested changes
Seems like your changes causing regression. Could you review test failures and adjust your code accordingly?

2020-10-25 17:36 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8387](https://jira.corp.magento.com/browse/ENGCOM-8387) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-10-27 19:23 UTC, sidolov commented
@magento create issue

2020-10-28 10:10 UTC, ihor-sviziev commented
@magento run all tests

2020-10-28 13:36 UTC, krzksz commented
@magento run Functional Tests CE,Static Tests,Unit Tests

2020-10-28 15:08 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Unit Tests

2020-10-29 07:21 UTC, krzksz commented
It seems we are on a good path. There are still some tests which try to login customer using hidden authentication popup instead of actual forms because of duplicated ID, but I'll try to adjust the selectors to fix that.

2020-10-29 07:48 UTC, ihor-sviziev commented
@krzksz that's actually really good catch!

2020-11-17 13:13 UTC, engcom-Charlie commented
@krzksz could you please fix failed tests?
Thank you.

2020-11-20 14:17 UTC, engcom-Charlie commented
@magento run all tests

2020-11-23 09:17 UTC, engcom-Charlie commented
@magento run all tests

2020-11-23 10:22 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-11-23 14:10 UTC, ihor-sviziev commented on app/code/Magento/Checkout/Test/Mftf/Section/CheckoutShippingGuestInfoSection.xml
> +        <element name="email" type="input" selector="#customer-email-fieldset #customer-email"/>
that's pretty stupid to looking for ID in the ID.
can we use some class?

2020-11-24 08:44 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-11-24 13:45 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-11-25 09:16 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-11-25 15:15 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-11-26 11:24 UTC, engcom-Charlie commented
@magento run Functional Tests EE, Functional Tests B2B

2020-11-27 08:46 UTC, engcom-Charlie commented
@magento run Functional Tests EE, Functional Tests B2B

2020-11-27 10:59 UTC, engcom-Charlie commented
@magento run Functional Tests EE, Functional Tests B2B

2020-11-27 12:41 UTC, engcom-Charlie commented
@magento run Functional Tests EE, Functional Tests B2B

2020-11-27 15:19 UTC, engcom-Charlie commented
@magento run all tests

2020-11-29 17:21 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests B2B

2020-11-29 21:06 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests B2B

2020-11-30 06:15 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests B2B

2020-11-30 08:51 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests B2B

2020-11-30 18:06 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-01 08:08 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-01 12:26 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-01 16:43 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-02 11:07 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-02 13:10 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-02 15:13 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-02 18:22 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-02 21:46 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-03 10:02 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2020-12-03 13:44 UTC, ihor-sviziev approved these changes
Finally, everything is green! 🎉

2020-12-03 13:45 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8387](https://jira.corp.magento.com/browse/ENGCOM-8387) has been created to process this Pull Request

2020-12-03 14:01 UTC, engcom-Charlie commented
@ihor-sviziev Looks like changes are covered by the js unit test. Can we set the label `Auto-Tests: Covered` to this PR?
What do you think?

2020-12-04 19:34 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
Was checked cases from **Manual testing scenarios**:
**Before:**
:x: `setModalElement` function is called when guest checkout is enabled
![#30647Main](https://user-images.githubusercontent.com/51681379/101206257-8f698f00-3677-11eb-9706-421be8a2875f.png)


**After:**
:heavy_check_mark: `setModalElement` function is no longer called when guest checkout is enabled
![#30647PrProfiler](https://user-images.githubusercontent.com/51681379/101206296-9abcba80-3677-11eb-9698-efb395c1f4b9.png)
:heavy_check_mark: Authentication popup shows properly when guest user tries to go to the checkout but guest checkout is disabled.
![Peek 2020-12-04 14-13](https://user-images.githubusercontent.com/51681379/101206449-ce97e000-3677-11eb-8a65-024dd2398c73.gif)
:heavy_check_mark: Authentication popup shows properly when guest user tries place order with downloadable product and `Disable Guest Checkout if Cart Contains Downloadable Items=Yes`
![Peek 2020-12-04 14-07](https://user-images.githubusercontent.com/51681379/101206831-639ad900-3678-11eb-824d-2fc509329660.gif)

2020-12-04 20:06 UTC, engcom-Delta commented
**Note:** Automation tests are passed

2020-12-21 18:52 UTC, sidolov approved these changes

2020-12-21 18:53 UTC, magento-engcom-team commented
Hi @sidolov, thank you for the review.
[ENGCOM-8387](https://jira.corp.magento.com/browse/ENGCOM-8387) has been created to process this Pull Request

2021-01-08 10:18 UTC, gabrieldagama commented
@magento run al tests

2021-01-08 10:19 UTC, gabrieldagama commented
@magento run all tests

2021-01-08 12:22 UTC, gabrieldagama commented
Hi, @engcom-Charlie can you check the failed tests on this PR? It seems to be constantly failing.

2021-01-08 13:23 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-01-08 15:05 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-01-11 11:08 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-01-11 12:04 UTC, engcom-Charlie commented
@magento run all tests

2021-01-12 07:04 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-01-12 10:13 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-01-12 14:11 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-01-12 21:31 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
Result is same as in [comment](https://github.com/magento/magento2/pull/30647#issuecomment-738976134)

2021-01-12 21:31 UTC, engcom-Delta commented
**Note:** Functional Tests B2B are failed

2021-01-13 09:53 UTC, engcom-Charlie commented
@magento run all tests

2021-01-13 14:13 UTC, ihor-sviziev approved these changes

2021-01-13 14:14 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8387](https://jira.corp.magento.com/browse/ENGCOM-8387) has been created to process this Pull Request

2021-01-14 09:44 UTC, engcom-Delta commented
**Note:** No new changes since last check https://github.com/magento/magento2/pull/30647#issuecomment-759028728
Automation tests are passed

2021-02-22 17:26 UTC, gabrieldagama commented
@magento run all tests

2021-03-02 14:16 UTC, gabrieldagama commented
@magento run all tests

2021-03-04 10:55 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2021-03-05 07:22 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2021-03-13 13:31 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-03-18 11:25 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-03-18 12:49 UTC, gabrieldagama requested changes
Hi @engcom-Foxtrot it seems this PR is failing tests constantly and has conflicts, can you have a look on it?

2021-03-20 03:38 UTC, mrtuvn commented on app/code/Magento/Customer/view/frontend/web/js/view/authentication-popup.js
>              }
should we compare with authenticationPopup.modalWindow === null instead ?

2021-04-21 13:00 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-22 07:26 UTC, ihor-sviziev commented
@engcom-Foxtrot  still failing,...

2021-04-22 10:29 UTC, mrtuvn commented
Can i create seperate PR for this

2021-04-23 13:09 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-23 13:09 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-24 00:56 UTC, mrtuvn commented
@engcom-Foxtrot can you update/fix for conflicts file

2021-04-26 11:54 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-06 09:01 UTC, ihor-sviziev commented
@engcom-Foxtrot tests still failing :(

2021-05-12 11:12 UTC, engcom-Foxtrot commented
@magento run Functional Tests CE, Functional Tests CE, Functional Tests B2B

2021-05-13 14:06 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-14 06:46 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-14 11:28 UTC, engcom-Foxtrot commented
@magento run Functional Tests CE, Functional Tests B2B, WebAPI Tests

2021-05-14 16:07 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-05-15 02:36 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-05-16 09:29 UTC, ihor-sviziev approved these changes

2021-05-16 09:33 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8387](https://jira.corp.magento.com/browse/ENGCOM-8387) has been created to process this Pull Request

2021-07-22 08:11 UTC, Den4ik approved these changes

2021-07-22 08:13 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-8387](https://jira.corp.magento.com/browse/ENGCOM-8387) has been created to process this Pull Request

2021-08-19 08:59 UTC, engcom-Charlie commented
@magento run all tests

2021-08-20 13:28 UTC, engcom-Charlie commented
Thank you for your contribution @krzksz. 

Manual scenarios are working as expected but one test case from Functional test CE is still failing. 

:x: QA not Passed

**Manual testing scenarios**:

**Before:**
:x: `setModalElement` function is called when guest checkout is enabled

![image](https://user-images.githubusercontent.com/51680850/130238949-dae08946-fa36-4ba0-a4de-1347208ca15f.png)

**After:**
:heavy_check_mark: `setModalElement` function is no longer called when guest checkout is enabled

![image](https://user-images.githubusercontent.com/51680850/130239040-8a180d1a-c2da-47d3-a322-9db8bb22708f.png)

:heavy_check_mark: Authentication popup shows properly when guest user tries to go to the checkout with guest checkout is disabled.

![image](https://user-images.githubusercontent.com/51680850/130239209-19c96cf8-55a0-41cc-9138-1c0b742c1412.png)


https://user-images.githubusercontent.com/51680850/130239324-530d7119-5ce9-49ca-8d8d-96b34b2b0ac9.mp4

2021-08-21 04:28 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests CE

2021-09-01 12:46 UTC, engcom-Charlie commented
Hi @krzksz, thank you for your contribution.

As per review comments and testing one of the test case from this PR which is StoreFrontCheckVatIdAtAccountCreateWithMultishipmentTest is broken.

I am working on it.

Thank you!

2021-09-01 14:01 UTC, engcom-Charlie commented
@magento run all tests

2021-09-02 08:17 UTC, engcom-Charlie commented
@magento run all tests

2021-09-02 12:15 UTC, engcom-Charlie commented
Thanks for everyone's contribution!!

As per your review comments, I have merged magento2/2.4-develop into this PR branch.

I have tested all MFTF test cases which are getting covered in this PR. All are working fine before and after merge.

The above failed test cases are not part of this PR and also the PR changes are not causing the failure of above test cases so moving this PR in testing.

2021-09-02 13:13 UTC, ihor-sviziev commented
Hi @engcom-Charlie, the Functional Tests CE and Functional Tests EE are still failing after restarting...
It looks like some issue is still there. Isn't it?

2021-09-07 10:52 UTC, mrtuvn commented
branch seem too old for automate tasks. I think update code branch may help

2021-09-07 10:55 UTC, Den4ik commented
@magento run all tests

2021-09-19 04:49 UTC, mrtuvn commented
@magento run all tests

2021-09-21 13:35 UTC, mrtuvn commented
@magento run Functional Tests CE, Functional Tests B2B

2021-09-29 07:00 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have an Magento installed with sample data


**Manual testing scenario:**

1. Set the Store>Confgiration>Sales>Checkout> Checkout Options > _Allow Guest Checkout - Yes_

2. Front end> Don't customer login; just add product to cart and proceed to checkout
 
3. Validate the setModalElement even has been called or no


**Before:** :heavy_multiplication_x: _setModalElement_ event was getting called when the guest checkout is enabled

![image](https://user-images.githubusercontent.com/51679138/135215355-57b13994-935f-4192-94d4-c62a69e44a48.png)


**After:** :heavy_check_mark:  _setModalElement_ event is  not getting called when the guest checkout is enabled

![image](https://user-images.githubusercontent.com/51679138/135215570-64eb519e-4224-4e75-8e5e-d6009425671f.png)


Additionally tested below scenarios with the PR fix code:
1. Set Guest checkout Yes: Logged in as a existing customer from the checkout page and able to place the order.
2. Set Guest checkout Yes: Just provided the shopping address with a non existing mail address from the checkout page and able to place the order.
3. Set Guest checkout No: Tried to checkout without logging in, received the popup to login first and then able to place the order.

Since this PR has the fix relevant to avoid the unused even from the request, and it has no impact on other features as such, no additional regression is required apart from above listed cases.

2022-10-19 16:58 UTC, ishakhsuvarov commented
Moving to `extended testing` to get merge conflicts resolved.

2022-10-31 09:07 UTC, engcom-Echo commented
@magento run all tests

2022-10-31 11:47 UTC, engcom-Echo commented
@magento run Functional Tests EE, Functional Tests B2B

2022-11-02 06:01 UTC, engcom-Echo commented
@magento run Functional Tests EE, Functional Tests B2B

2022-11-02 09:47 UTC, engcom-Echo commented
@magento run Functional Tests EE, Functional Tests B2B

2022-11-02 11:53 UTC, engcom-Echo commented
@magento run Functional Tests EE, Functional Tests B2B

2022-11-03 04:36 UTC, engcom-Echo commented
@magento run Functional Tests EE, Functional Tests B2B

2022-11-03 06:32 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2022-11-10 06:16 UTC, engcom-Echo commented
Seems like bot moved this PR from `Merge in Progress` to `Ready for Testing`. Moving back to `merge in progress`.

2022-12-22 22:53 UTC, merged

2022-12-23 05:02 UTC, ihor-sviziev commented
Finally! This or got 2 birthdays and almost 1 month, and only then merged!