Hide unneccesary authenticate popup block
magento/magento2 pull request #30646
Opened 2020-10-25 01:16 UTC by mrtuvn

### Description (*)

Default layout magento have render authenticate-popup block in all pages. When it's active modal will show for user can login/create account
In checkout we don't need this popup so we can safe hide it or even remove it. For backward compatible we should hide it instead completely remove it

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-25 22:19 UTC, mrtuvn commented
@magento run all tests

2020-10-26 17:18 UTC, rogyar commented
Hi @mrtuvn. Thanks for your fix. I thought it has been removed a long time ago :)  
Could you cover this change with an MFTF test, please? The test will add a product to the shopping cart, go to the checkout and make sure that there's no authentication popup selector present on the page. 

Thank you!

2020-11-14 04:06 UTC, mrtuvn commented
@magento run all tests

2020-11-14 04:56 UTC, mrtuvn commented
@rogyar can you give me a review

2020-11-14 06:18 UTC, mrtuvn commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-11-14 22:36 UTC, mrtuvn commented
@magento run all tests

2020-11-18 14:59 UTC, rogyar requested changes

2020-11-18 14:59 UTC, rogyar commented on app/code/Magento/Checkout/Test/Mftf/Test/StorefrontCheckoutVerifyAuthenticatePopupNotVisible.xml
> +        <amOnPage url="$$createSimpleProduct.custom_attributes[url_key]$$.html" stepKey="navigateToSimpleProductPage"/>
Great job. The last thing I would ask you to do is to utilize the existing action groups for such actions. 

https://github.com/magento/magento2/blob/0262f1428561f5c329a50bfbd62714fa58e175be/app/code/Magento/Catalog/Test/Mftf/ActionGroup/StorefrontOpenProductPageActionGroup.xml#L10

Thank you!

2020-11-18 15:16 UTC, mrtuvn commented
@rogyar Updated PR as your suggestions

2020-11-22 13:23 UTC, rogyar commented
@magento run all tests

2020-11-26 00:26 UTC, mrtuvn commented
@magento run Integration Tests, Functional Tests CE, Functional Tests B2B, Functional Tests EE

2020-11-29 16:32 UTC, rogyar commented
Hi @mrtuvn there's something wrong with removing entities after the test execution. Could you try to swap removing product and category in the `after` section, please?

2020-11-30 01:28 UTC, mrtuvn commented
@rogyar updated my PR for mftf test

2020-11-30 05:52 UTC, mrtuvn commented
@magento run all tests

2020-11-30 08:08 UTC, mrtuvn commented
Got broken issue with mftf "Entity with a CreateDataKey of createProduct could not be found"
Any reason why this happen @rogyar @engcom-Charlie @engcom-Alfa

2020-12-01 13:16 UTC, rogyar commented on app/code/Magento/Checkout/Test/Mftf/Test/StorefrontCheckoutVerifyAuthenticatePopupNotVisibleTest.xml
> +            <argument name="productUrl" value="$$createProduct.custom_attributes[url_key]$$"/>
I believe the possible reason for that -  we use `$$createProduct` but in the "before" section we use `createSimpleProduct` as a key.

2020-12-02 01:13 UTC, mrtuvn commented
@magento run all tests

2020-12-02 01:13 UTC, mrtuvn commented
merged 2.4-develop branch + rebased

2020-12-04 08:50 UTC, rogyar approved these changes

2020-12-04 08:51 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8513](https://jira.corp.magento.com/browse/ENGCOM-8513) has been created to process this Pull Request

2020-12-04 14:48 UTC, mrtuvn commented
@magento run Functional Tests CE, Functional Tests B2B

2021-07-25 04:53 UTC, mrtuvn commented
@magento run all tests

2021-07-25 06:55 UTC, mrtuvn commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-07-26 07:07 UTC, mrtuvn commented
i think this one may resolve impact with performance for checkout page. Also improve customer checkout experience. Can we consider increase to P3 priority ?
@gabrieldagama @rogyar

2021-08-11 02:14 UTC, mrtuvn commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-08-18 15:26 UTC, mrtuvn commented
Closed this one because nobody care about this and slow to process. Another ticket PR already do this instead for me

2021-08-18 15:26 UTC, closed without merging