[Reorder] #30686 - Allow developers to filter order items for reorder
magento/magento2 pull request #30687
Opened 2020-10-28 12:28 UTC by PierreLeMaguer

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/30686

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-28 16:18 UTC, BarnyShergold commented
@magento run all tests

2020-10-28 16:21 UTC, BarnyShergold commented
@PierreLeMaguer - It would be useful, as this may not be your only PR in this code area, to add a small description of the change made and how you envisage developers utilising the change - I'm assuming you'd expect them to create a plugin on your new method and manipulate the return? Good for searching at a later date

2020-10-28 16:46 UTC, PierreLeMaguer commented
hello @BarnyShergold , thanks for the review. I add a small description to the PR area.

2020-10-28 17:41 UTC, BarnyShergold requested changes
The Reorder.php is causing a fail on two B2B static tests. Not sure why but this is for existing code. Will need to be addressed.

Once functional tests have completed check for errors.

2020-10-28 17:41 UTC, BarnyShergold commented on app/code/Magento/Sales/Helper/Reorder.php
> +    public function canReorderItem($item, $product)
Missing return type on prototype

2020-10-29 07:47 UTC, PierreLeMaguer commented
Hello @BarnyShergold ,

I pushed a new commit to fix static tests.

I checked the functional tests : no error here https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30687/33fbb0a2d1da4801a0d5971f86715e31/Functional/allure-report-ee/index.html#behaviors but one error here https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30687/c3bb69a2652167d4e479a67f5eaee4cf/Functional/allure-report-ce/index.html on the test  Magento\FunctionalTestingFramework.functional\MediaGalleryUiSuite  ... Not sure that it's linked to my PR.

2020-10-29 08:35 UTC, mbvb1223 commented
> Hello @BarnyShergold ,
> 
> I pushed a new commit to fix static tests.
> 
> I checked the functional tests : no error here https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30687/33fbb0a2d1da4801a0d5971f86715e31/Functional/allure-report-ee/index.html#behaviors but one error here https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30687/c3bb69a2652167d4e479a67f5eaee4cf/Functional/allure-report-ce/index.html on the test Magento\FunctionalTestingFramework.functional\MediaGalleryUiSuite ... Not sure that it's linked to my PR.

It seems the same my issue.
I also got an error 
`Magento\FunctionalTestingFramework.functional\MediaGalleryUiSuite`
 `https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4951848: Used in pages link`

2020-10-29 10:49 UTC, PierreLeMaguer commented
@magento run all tests

2020-10-29 15:21 UTC, BarnyShergold commented
@magento run Functional Tests CE

2020-11-02 12:00 UTC, BarnyShergold commented
@magento run Functional Tests B2B

2020-11-02 12:00 UTC, BarnyShergold commented
@magento run Integration Tests

2020-11-02 16:03 UTC, BarnyShergold commented
@magento run Functional Tests B2B

2020-11-04 16:54 UTC, mbvb1223 commented
@magento run Functional Tests B2B

2020-11-05 08:30 UTC, romainruaud commented
can you please guy tag this PR with "Partner : Smile" ? 

I used to be able to do so previously but it seems it's not the case anymore.

Regards

2020-11-07 13:47 UTC, PierreLeMaguer commented
@magento run Functional Tests B2B

2020-11-13 19:58 UTC, PierreLeMaguer commented
Hello @BarnyShergold , is it ok now ?
Also, is it possible to add the label Parter: Smile ?
Thanks

2020-11-17 17:23 UTC, BarnyShergold approved these changes
All tests have passed! I've added Smile

2020-11-17 17:24 UTC, magento-engcom-team commented
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8470](https://jira.corp.magento.com/browse/ENGCOM-8470) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-12-16 08:09 UTC, PierreLeMaguer commented
@BarnyShergold any news about this PR ? Does it lack anything ?

2021-02-16 11:00 UTC, BarnyShergold commented
@PierreLeMaguer I did some checking and currently the feedback is - "This PR is prioritised as P4, we are not able to process P4 PRs currently"

2024-10-28 11:36 UTC, engcom-Dash commented
@magento run all tests

2024-10-30 11:42 UTC, engcom-Dash commented
Hello @PierreLeMaguer,

Thanks for your contributions!

Moving this PR to on hold since it’s a feature request and we need PO approval for it. Once we get approval, we will proceed accordingly.

Thanks.

2024-12-03 09:40 UTC, engcom-Dash commented
> Hello @PierreLeMaguer,
> 
> Thanks for your contributions!
> 
> Moving this PR to on hold since it’s a feature request and we need PO approval for it. Once we get approval, we will proceed accordingly.
> 
> Thanks.

Hello @PierreLeMaguer,

Thanks for your contributions!

We've received feedback from the PO, and the requested functionality—overriding the reorder feature in customizations—wasn't intended to work that way. As a result, we can't proceed further with this PR.

Thank you again for your understanding and for your contribution!

2024-12-03 09:40 UTC, closed without merging