#30473 fixed image url for category if url rewrite are disabled
magento/magento2 pull request #30689
Opened 2020-10-28 14:22 UTC by ProkopovVitaliy

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30473

### Manual testing scenarios (*)

1. Turn off url rewrite
2. Set image for category
3. Execute query:
```
{
  category(id: 38){
    name
    image
  }
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-28 14:28 UTC, ProkopovVitaliy commented
@magento run all tests

2020-10-29 11:34 UTC, coderimus commented
@magento run Functional Tests EE

2020-10-29 18:47 UTC, cpartica requested changes

2020-10-29 18:47 UTC, cpartica commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Image.php
> +        $baseUrl = $store->getBaseUrl(UrlInterface::URL_TYPE_WEB);
I think we just need some tests for this

2020-11-03 05:25 UTC, merged