Use oauth_nonce, oauth_version and oauth_timestamp in signature gener…
magento/magento2 pull request #30693
Opened 2020-10-28 16:20 UTC by Jakhotiya

…ation

Using \Magento\Framework\Oauth\Oauth class for Oauth header generation causes "This signature is Invalid error." That happens because _validateSignature uses  oauth_nonce, oauth_version and oauth_timestamp in signature generation but buildAuthorizationHeader does not use them in signature generation. Hence signatures don't match.
 This pull request fixes that by using oauth_nonce, oauth_version and oauth_timestamp  in oauth signature generation

2020-10-28 16:27 UTC, BarnyShergold requested changes
Thanks for your first contribution @Jakhotiya !

Please can you add a proper header description to the PR as required? You can take a look at https://github.com/magento/magento2/pull/30639 for an example. Your current one seems cut-off at the start.

Also you will need to sign the Adobe CLA as this is your first submission

2020-10-28 16:33 UTC, Jakhotiya commented
@BarnyShergold Thank you for feedback. I've signed Adobe CLA. Also added description and header.

Can this also be backported since older versions have same issue.

2020-10-28 17:34 UTC, BarnyShergold approved these changes
That's a great update. I'm only a Maintainer / reviewer - however this fix will only be allowed on the 2.3 (although it's also on 2.4 so QA may want to merge this into 2.4-develop)

It can't be backported to 2.2, 2.1 or 2.0 as these are now unsupported branches.

2020-10-29 16:50 UTC, sidolov commented
Hi @Jakhotiya , please, re-create the PR to 2.4-develop branch, we are not able to accept changes to 2.3 branch

2020-10-29 16:50 UTC, closed without merging