Developer Experience: Make `getAdditionalConfig` extensible
magento/magento2 pull request #30718
Opened 2020-10-30 00:08 UTC by lbajsarowicz

### Description (*)
Currently when you need to add some extra data to Configurable Swatches, you need either:
- Inherit class and add your custom elements
- Plugin end decode the data before adding your

Example from Extension Vendor code:
![image](https://user-images.githubusercontent.com/1639941/97645076-4311aa80-1a4c-11eb-9633-b85eff30e3b8.png)

To avoid such situations, I introduced the change that enables us to put our own data in Swatch config without unnecessary hassle.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-30 00:09 UTC, lbajsarowicz commented
@magento run all tests

I don't remember if I can add a new `public` method to this specific class.

2020-10-30 12:53 UTC, lbajsarowicz commented
@magento run all tests

2020-10-30 13:19 UTC, ihor-sviziev commented
Looks good. Moving to "on hold" as it will wait for 2.5

2020-11-04 15:12 UTC, sidolov commented
@magento create issue

2020-11-25 14:53 UTC, lbajsarowicz commented
@magento run all tests

2021-01-08 14:09 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,
Could you re-target your PR to 2.5-develop branch?

2021-01-08 17:14 UTC, lbajsarowicz commented
@magento run all tests

2021-01-29 12:43 UTC, ihor-sviziev commented
@magento run Functional Tests CE

2021-01-29 12:44 UTC, ihor-sviziev approved these changes

2024-09-30 12:07 UTC, engcom-Dash commented
Hi @lbajsarowicz 

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:

Install fresh Magento 2.4-develop
Steps to reproduce
- Create a plugin for app/code/Magento/ConfigurableProduct/Block/Product/View/Type/Configurable.php::getAdditionalConfig()
- Observe that the plugin code executes as expected.
Before: ✖️
Since we can't create a plugin for a private method, it will not be triggered anyway.
After: ✔️
Plugin is triggered.
<img width="1783" alt="image" src="https://github.com/user-attachments/assets/26ae393f-c2a1-4161-9d62-29f20238a06d">

Builds are failed. Hence moving it to Extended Testing.

2024-09-30 12:08 UTC, engcom-Dash commented
@magento run all tests

2024-10-01 09:23 UTC, engcom-Dash commented
@magento run all tests

2024-10-30 11:23 UTC, engcom-Dash commented
Moving this PR to on hold since we are not picking up any PRs against the 2.5-develop branch right now. Once we pick it up, we will move it to the appropriate status.

2025-09-03 16:48 UTC, closed without merging