Module & Theme less optimization for cross browser compatibility.
magento/magento2 pull request #30728
Opened 2020-10-30 17:45 UTC by pratiksangani

### Description (*)

Updated core modules & theme less design with Magento default Flex layout less mixins. Reference taken from `<Magento2>/lib/web/css/source/lib/_utilities.less:409 Flex layout mixins` and my Magento 2 theme development experience. Using these provided mixins, the design will work on cross-browser platform properly. I've also removed some redundant code from some direct less styles, as they were already been covered by less mixins.

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30729: Module & Theme less optimization for cross browser compatibility.

2020-10-30 17:45 UTC, pratiksangani commented
@magento create issue

2020-10-30 17:46 UTC, pratiksangani commented
@magento run all tests

2020-10-30 18:31 UTC, pratiksangani commented
@ihor-sviziev Will you please proceed this PR?

2020-10-31 17:03 UTC, ihor-sviziev commented
@magento run all tests

2020-10-31 17:03 UTC, ihor-sviziev approved these changes

2020-11-02 10:30 UTC, ihor-sviziev requested changes
Hi @pratiksangani,
Could you fix failing static tests?

2020-11-02 16:51 UTC, mrtuvn requested changes

2020-11-02 16:51 UTC, mrtuvn commented on app/design/adminhtml/Magento/backend/Magento_Customer/web/css/source/_module.less
>          float: left;
default param .lib-vendor-prefix-display() is flex so you don't need to more specific except you want to try inline flex such as .lib-vendor-prefix-display(inline-flex)

2020-11-02 16:51 UTC, mrtuvn commented on app/design/adminhtml/Magento/backend/web/css/source/_actions.less
we don't have to specific flex and row in here when call .lib-vendor-prefix

2020-11-02 17:03 UTC, mrtuvn commented on app/design/adminhtml/Magento/backend/web/css/source/_actions.less
And the rest changes fine with me

2020-11-03 17:22 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8416](https://jira.corp.magento.com/browse/ENGCOM-8416) has been created to process this Pull Request

2020-11-10 13:05 UTC, digiltd commented
Is there still a need to prefix all the flex stuff these days?

Granted there will be some cases where IE11 or Safari installed before 2015 needs to be supported, though if you are building for those browsers, flexbox prefixes are the least of your concerns :)

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox#Status_in_browsers

2020-11-10 16:23 UTC, ihor-sviziev commented
@digiltd good point! 
@pratiksangani could you explain which compatibility you would like to fix? Seems like we safely could remove these vendor prefixes

2020-11-11 09:03 UTC, digiltd commented
@ihor-sviziev I think `appearance` still warrants a prefix, though only `-webkit-` and `-moz-` as Edge and IE use the `-webkit-` prefix

https://caniuse.com/css-appearance

2020-11-17 08:26 UTC, ihor-sviziev requested changes
Hi @pratiksangani,
Could you revert all changes and leave the only changes for `appearance`?

2020-12-07 15:23 UTC, ihor-sviziev commented
@pratiksangani  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-12-07 15:23 UTC, closed without merging