Pass string value to PHP functions which expect a string parameter.
magento/magento2 pull request #30764
Opened 2020-11-03 18:29 UTC by dfelton

### Description (*)

Helps prepare file for `declare(strict_types=1);`. 

When the source for a `Magento\Eav\Model\Entity\Attribute\Source\Boolean` attribute was being processed, the following would occur if strict_types was turned on:

- Line 535 would throw: `strlen() expects parameter 1 to be string, int given` (since values are int values `0` and `1`)
- Line 537 would throw: `strtolower() expects parameter 1 to be string, object given` (since it was passing it an object of `\Magento\Framework\Phrase`)

### Manual testing scenarios (*)

None performed. Given the nature of the logic though we know that [strlen()](https://www.php.net/strlen) expects a string value as does [strtolower()](https://www.php.net/strtolower). Without `declare(strict_types=1)` turned on, this casting occurs automatically. With it on, a `\TypeError` is thrown. Explicitly casting to string prior to passing values to these two functions resolves this.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-03 18:30 UTC, dfelton commented
@magento run all tests

2020-11-03 19:09 UTC, dfelton commented
Note on failed static test: 

```
PHP Code Sniffer detected 1 violation(s): 

FILE: ...code/Magento/ImportExport/Model/Import/Entity/AbstractEntity.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
  20 | WARNING | Abstract classes MUST NOT be marked as public @api.
 541 | WARNING | Empty CATCH statement detected
----------------------------------------------------------------------



Failed asserting that 1 matches expected 0.
```

These two would have been failing prior to PR, as both these are as they were beforehand.

2020-11-04 15:05 UTC, sidolov commented
@magento create issue

2020-11-05 15:50 UTC, ihor-sviziev requested changes
Hi @dfelton,
Could you declare strict types for this file?

2020-11-05 20:55 UTC, dfelton commented
@ihor-sviziev At this time, I cannot confirm that this is the only change necessary in order for this file to support strict types. I stumbled upon this situation while having to fix some third party code in a project of mine. The third party code extended this function, then called its parent (this method).

I needed to then implement a fix in *their* code. In order too have the original Magento logic still be executed, while not calling the broken code, I had copy/pasted Magento's function into my own class. It was during this effort, because my own class had strict types enabled, that I discovered this.

For example.

```php
class Magento
{
  public function getAttributeOptions()
  {
     // native logic...
    return $options;
  }
}
```

```php
class ThirdPartyBuggyCode extends Magento
{
  public function getAttributeOptions()
  {
     $options = parent::getAttributeOptons();
     // buggy code logic...
    return $options;
  }  
}
```

```php

declare(strict_types=1);

class MyFixAppliedToThirdPartyCode extends ThirdPartyBuggyCode
{
  public function getAttributeOptions()
  {
     $options = $this->_getAttributeOptons();
     // fixed logic of third party vendor...
    return $options;
  }

  private function _getAttributeOptions()
  {
    // copied native magento logic so I don't have to call parent
    // oops! discovered Magento's logic doesn't work with strict types here, applied fix
    return $options;
  }
}
```

Does this make sense?

Anyhow, if you would still like me to apply strict types to this file, it will require additional time and effort from me to ensure the rest of the file is ready for strict types. I am willing to do so, but I must also state that I don't know when I will have the capacity to  get to the rest of the work that (may) be involved for this.

2020-11-06 05:23 UTC, ihor-sviziev commented
@dfelton the idea behind it - if you’ll do strict types and we’ll just run all tests - we might see if some issue there or no

2020-11-06 18:45 UTC, dfelton commented
@ihor-sviziev Ah, simple enough. Thank you for clarifying.

2020-11-06 19:33 UTC, dfelton commented
@magento run all tests

2020-11-07 06:05 UTC, ihor-sviziev requested changes
Hi @dfelton,
Seems like declaring strict types also breaks in some other cases. Could you check test failures and adjust the code in order to pass tests?

2020-11-08 21:31 UTC, dfelton commented
@ihor-sviziev Yes I'd be happy to. I'll have to get to this when I have some down time. Hopefully I can get to it in the next few weeks here as I'm in the middle of crunch time on my current full-time project.

2020-12-07 15:19 UTC, ihor-sviziev commented
Hi @dfelton,
Will you be able to update your PR with suggested changes?

2020-12-10 08:59 UTC, ihor-sviziev commented
@dfelton  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2020-12-10 08:59 UTC, closed without merging