MC-30626: Custom Option with Percent price is converted to a currency twice
magento/magento2 pull request #30807
Opened 2020-11-05 16:23 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26432

### Manual testing scenarios (*)

See: magento/magento2#26432

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-05 16:25 UTC, engcom-Echo commented
@magento run all tests

2020-11-06 08:42 UTC, engcom-Echo commented
@magento run all tests

2020-11-10 12:15 UTC, engcom-Kilo requested changes

2020-11-10 12:15 UTC, engcom-Kilo commented on app/code/Magento/Catalog/Pricing/Price/CustomOptionPrice.php
> +    public function getCustomRoundAmount($amount, $context = [])
There is no getCustomRoundAmount in CustomOptionPriceInterface. Please consider to find other solution.

2020-11-10 12:15 UTC, engcom-Kilo commented on app/code/Magento/Catalog/Test/Mftf/Test/StorefrontCheckCustomOptionPriceDifferentCurrencyTest.xml
> +        <seeElement selector="{{StorefrontProductInfoMainSection.productAttributeOptionsCheckbox(ProductOptionCheckbox.title, '12.3')}}" stepKey="checkPriceProductOptionUSD"/>
Please create ActionGroup for this action.

2020-11-11 09:35 UTC, engcom-Echo commented
@magento run all tests

2020-11-11 09:46 UTC, engcom-Echo commented
@magento run all tests

2020-11-11 11:05 UTC, engcom-Echo commented
@magento run all tests

2020-11-12 11:14 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2020-11-12 15:51 UTC, engcom-Echo commented
@magento run all tests

2020-11-13 13:14 UTC, engcom-Echo commented
@magento run all tests

2020-11-18 10:32 UTC, ihor-sviziev approved these changes

2020-11-18 10:33 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8475](https://jira.corp.magento.com/browse/ENGCOM-8475) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-11-19 10:17 UTC, gabrieldagama approved these changes

2020-11-19 10:18 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8475](https://jira.corp.magento.com/browse/ENGCOM-8475) has been created to process this Pull Request

2020-11-19 11:23 UTC, victorpetryk requested changes

2020-11-19 11:23 UTC, victorpetryk commented on app/code/Magento/Catalog/Test/Mftf/Test/StorefrontCheckCustomOptionPriceDifferentCurrencyTest.xml
> +            <magentoCLI command="config:set currency/options/allow EUR,USD" stepKey="setCurrencyAllow"/>
Could you use the existing entity for this?
```
<magentoCLI command="config:set {{SetAllowedCurrenciesConfigForUSD.path}} {{SetAllowedCurrenciesConfigForUSD.value}},{{SetAllowedCurrenciesConfigForEUR.value}}" stepKey="setAllowedCurency"/>

2020-11-19 11:23 UTC, victorpetryk commented on app/code/Magento/Catalog/Test/Mftf/Test/StorefrontCheckCustomOptionPriceDifferentCurrencyTest.xml
> +            <magentoCLI command="config:set currency/options/allow USD" stepKey="setCurrencyAllow"/>
Same here:
```
<magentoCLI command="config:set {{SetAllowedCurrenciesConfigForUSD.path}} {{SetAllowedCurrenciesConfigForUSD.value}}" stepKey="setAllowedCurency"/>

2020-11-19 11:23 UTC, victorpetryk commented on app/code/Magento/Catalog/Test/Mftf/ActionGroup/StorefrontAssertCustomOptionCheckboxByPriceActionGroup.xml
> +    <actionGroup name="StorefrontAssertCustomOptionCheckboxByPriceActionGroup">
If the action group is making an assertion, then use the following format: Assert{Admin or Storefront}{Functionality}ActionGroup.xml.

2020-11-19 11:23 UTC, victorpetryk commented on app/code/Magento/Catalog/Test/Mftf/ActionGroup/StorefrontAssertCustomOptionCheckboxByPriceActionGroup.xml
> +            <argument name="price" type="string"/>
Action group arguments SHOULD specify default values.

2020-11-19 11:23 UTC, victorpetryk commented on app/code/Magento/Catalog/Block/Product/View/Options/AbstractOptions.php
> +            ): $customOptionPrice->getCustomAmount($value['pricing_value'], null, $context);
Please add space between ):

2020-11-19 12:58 UTC, engcom-Echo commented
@magento run all tests

2020-11-19 13:28 UTC, engcom-Echo commented
@magento run all tests

2020-11-20 09:20 UTC, victorpetryk approved these changes

2020-11-20 10:05 UTC, ihor-sviziev approved these changes

2020-11-20 10:06 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8475](https://jira.corp.magento.com/browse/ENGCOM-8475) has been created to process this Pull Request

2020-11-23 12:23 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From Admin, create a _Simple Product_ with a base price of _100_, and a  **Custom option** which adds _50%_ to the base price 
![cust_option](https://user-images.githubusercontent.com/51680745/99960354-453dff00-2d95-11eb-868e-14dc6a421198.png)
2. Go to _Stores - Configuration - General - Currency Setup_ and assert that _Euro_ is checked in **Allowed Currencies**
![euro_allowed](https://user-images.githubusercontent.com/51680745/99960669-ce553600-2d95-11eb-9b32-64a95853b5a7.png)
3. Go to _Stores - Currency Rates_ and set _Rate_, for example, _2 EUR_ to _1 USD_
![rates](https://user-images.githubusercontent.com/51680745/99960874-255b0b00-2d96-11eb-8371-329d60abd11f.png)
4. Go to Storefront, and open the previously created Simple Products page 
5. Change the Stores currency to _EUR - Euro_
![web_curr](https://user-images.githubusercontent.com/51680745/99961195-a87c6100-2d96-11eb-92d1-22ebab95be83.png)
6. Check the _Custom option_ calculation

**BEFORE** applying changes provided in this PR, the Custom options was calculated wrong: Base price + Custom option price + Custom option price one more time
![before_currency](https://user-images.githubusercontent.com/51680745/99961310-dc578680-2d96-11eb-94c4-bb6f6038eb70.png)

**AFTER** switching to the PR, the Custom option price is calculated correctly, only once
![after_currency](https://user-images.githubusercontent.com/51680745/99961504-3ce6c380-2d97-11eb-950d-0cd5f9ed9ef2.png)

The order can be placed successfully and all the prices are displayed correctly in order Details
![order_total](https://user-images.githubusercontent.com/51680745/99961641-6e5f8f00-2d97-11eb-8918-825785a29151.png)

2020-11-24 08:01 UTC, ihor-sviziev commented
@engcom-Bravo seems like you missed to move this PR forward?

2020-11-26 11:04 UTC, engcom-Echo commented
@magento run Integration Tests

2020-11-26 11:05 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2020-11-26 11:08 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-30807`.

2020-11-26 15:04 UTC, engcom-Foxtrot commented
@magento run all tests

2020-11-28 07:02 UTC, merged