GraphQL - ConfigurableCartItem added to Cart returns wrong thumbnail image
magento/magento2 pull request #30817
Opened 2020-11-06 13:19 UTC by shikhamis11

fixes issue:#28573

If you add a ConfigurableCartItem to the Cart and then Query the Cart, this returns the Thumbnail of the Parent Product instead of the Variant that was selected.

**Query**

```
query CartQuery($cartId: String!) {
  cart(cart_id: $cartId) {
    ...Cart
  }
}

fragment Cart on Cart {
  items {
    id
    quantity
    product {
      id

      thumbnail {
        label
        url
      }
    }
    ... on ConfigurableCartItem {
      configurable_options {
        id
        option_label
        value_label
      }
    }
  }
}
{code}
**Variables**
{code:java}
{
  "cartId": "w74YbL1jbhlrdS95vWQM1mktppa9M3wI"
}
{code}
**Result**
{code:java}
{
  "data": {
    "cart": {
      "items": <
        {
          "id": "241",
          "quantity": 1,
          "product": {
            "id": 1410,
            "thumbnail": {
              "label": "Olivia 1/4 Zip Light Jacket",
              "url": "https://carlos-233-3h6p5qa-a6terwtbk67os.demo.magentosite.cloud/media/catalog/product/cache/ca63cacbf9a8041003a3fd3abbbfe421/w/j/wj12-blue_main.jpg" Should be the Thumbnail for Purple Variant
            }
          },
          "configurable_options": [
            {
              "id": 93,
              "option_label": "Color",
              "value_label": "Purple"
            },
            {
              "id": 162,
              "option_label": "Size",
              "value_label": "XS"
            }
          ]
        }
      >
    }
  }
}

```
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-06 13:20 UTC, shikhamis11 commented
@magento run all tests

2020-11-09 05:09 UTC, shikhamis11 commented
@magento run Static Tests

2020-11-09 07:01 UTC, shikhamis11 commented
@magento run all tests

2020-12-01 21:54 UTC, cpartica requested changes

2020-12-01 21:54 UTC, cpartica commented on app/code/Magento/ConfigurableProductGraphQl/Model/Resolver/ProductResolver.php
> +        $product = $this->productRepository->get($cartItem->getSku());
this is going to have a big performance problem for loading each product in the cart
it is best to use either data loader which can load all of them (we already do that in catalog)

`Magento\Catalog\Model\Product\Configuration\Item\ItemResolverInterface::getFinalProduct`
Considering that getFinalProduct doesn't add a new query
`$finalProduct = $this->itemResolver->getFinalProduct($cartItem);`

2020-12-01 21:54 UTC, cpartica commented on app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls
> +    configured_variant: ProductInterface @doc(description: "Product details of the cart item") @resolver(class: "\\Magento\\ConfigurableProductGraphQl\\Model\\Resolver\\ProductResolver")
this also needs tests

2020-12-07 08:24 UTC, shikhamis11 commented
@magento run all tests

2021-01-13 12:00 UTC, shikhamis11 commented
@magento run all tests

2021-01-13 12:11 UTC, shikhamis11 commented on app/code/Magento/ConfigurableProductGraphQl/Model/Resolver/ProductResolver.php
> +        $product = $this->productRepository->get($cartItem->getSku());
I tried with ` $finalProduct = $this->itemResolver->getFinalProduct($cartItem);`  
This provides all information related parent Items only same as `CartItemInterface.product` object except `ProductInerface.thumbnail` object as per set on backend configuration ` checkout/cart/configurable_product_image` either `parent` or `itself`

2021-01-28 03:40 UTC, shikhamis11 commented
Closing this as there is another PR

2021-01-28 03:40 UTC, closed without merging