MC-38105: Unable to set native session handler that is different from the one define in php.ini
magento/magento2 pull request #30866
Opened 2020-11-10 14:02 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#24717

### Manual testing scenarios (*)

See: magento/magento2#24717

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-10 14:07 UTC, engcom-Echo commented
@magento run all tests

2020-11-11 10:16 UTC, engcom-Echo commented
@magento run all tests

2020-11-11 12:24 UTC, ihor-sviziev commented
@magento run WebAPI Tests

2020-11-11 12:28 UTC, ihor-sviziev requested changes
For now the only one improvement is needed

2020-11-11 12:28 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/Framework/Session/SessionManagerTest.php
> +                if ($option == 'session.save_handler' && $value == 'user') {
```suggestion
                if ($option === 'session.save_handler' && $value === 'user') {
```

2020-11-11 12:35 UTC, engcom-Echo commented
> For now the only one improvement is needed.
> 
> Also tests were failing, let's check results again after restart

Thanks. I think that the failure of the tests will be repeated and we need to change the solution.

2020-11-11 12:50 UTC, ihor-sviziev commented
@engcom-Echo pls just merge latest changes from 2.4-develop. I believe these failures related to recent changes

2020-11-12 12:09 UTC, engcom-Echo commented
@magento run all tests

2020-11-12 12:21 UTC, engcom-Echo commented
@magento run all tests

2020-11-12 12:23 UTC, engcom-Echo commented
@magento run all tests

2020-11-12 15:18 UTC, engcom-Echo commented
@magento run all tests

2020-11-13 10:44 UTC, engcom-Echo commented
@magento run all tests

2020-11-13 14:38 UTC, ihor-sviziev approved these changes

2020-11-13 14:39 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8460](https://jira.corp.magento.com/browse/ENGCOM-8460) has been created to process this Pull Request

2020-11-16 13:43 UTC, victorpetryk approved these changes

2020-11-17 12:09 UTC, engcom-Kilo commented
@magento import pull request to https://github.com/magento-tsg/magento2ce

2020-11-17 12:10 UTC, engcom-Kilo approved these changes

2020-11-17 12:12 UTC, magento-engcom-team commented
@engcom-Kilo the pull request successfully imported.

2020-11-18 10:45 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed
Was checked case from Manual testing scenarios 
:x: **Before:**
main.CRITICAL: Warning: SessionHandler::read(): open(127.0.0.1:11211/sess_0imeeaqmnvemdg4e3h57tat0ik, O_RDWR) failed: No such file or directory (2) in../vendor/magento/framework/Session/SaveHandler/Native.php on line 22 {"exception":"[object] (Exception(code: 0): Warning: SessionHandler::read(): open(127.0.0.1:11211/sess_0imeeaqmnvemdg4e3h57tat0ik, O_RDWR) failed: No such file or directory (2) in ../vendor/magento/framework/Session/SaveHandler/Native.php on line 22 at ../vendor/magento/framework/App/ErrorHandler.php:61)"} []
:heavy_check_mark: **After:**
No errors on homepage and in Admin on backend

2020-11-20 18:05 UTC, merged