set correct remaining available discount amount when applying fixed p…
magento/magento2 pull request #30953
Opened 2020-11-17 14:38 UTC by sky-hub

…rice cart rules to bundle products

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/30952

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-18 21:19 UTC, eduard13 commented
@magento run all tests

2020-11-18 21:28 UTC, eduard13 requested changes
Hi @sky-hub, thank you for the following fix. According to the [Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html#automated-tests), all changes have to be covered by some automated tests. Would you be kind covering the fixed case by a test? 
You may write a simple [MFTF test](https://devdocs.magento.com/mftf/docs/introduction.html) that will pass through the Precondition steps and will check the cart discount.

Thank you.

2020-11-19 07:50 UTC, sky-hub commented
@eduard13, sure. I will get back with a comment when tests are implemented.

Cheers

2020-11-21 12:43 UTC, sky-hub commented
@eduard13 I had a look in the MTFT testing and I ran into a dead end.

It seems there is already a MTFT Test for bundle products in `app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartPriceRuleForBundleProductTest.xml` but apparently even this test is skipped due to some issue: 
`<skip><issueId value="MQE-2288" /></skip>`.

At this point I do not know if I should update this test, and if I do update it what is the reason behind that issue that marks the test as skipped. Do you think you can help here?

PS: Please note that my experience with MTFT is very limited.

2020-11-22 19:02 UTC, eduard13 commented
@sky-hub ahh, got your point. Based on the commit's message, it looks like there were some issues running the test on Chrome 85 version. As far as I can see, the existing test applies on `Percent of product price discount`, which in my opinion should also be the case for this PR (I haven't checked this case), however you may create a new one that checks the `Fixed amount discount` test case (having the same test case as the issue states). 

What do you think?
Thank you.

2020-11-22 19:02 UTC, eduard13 commented
@magento run Integration Tests, Functional Tests B2B

2020-11-22 19:36 UTC, sky-hub commented
@eduard13 , sounds good to me.
I'll implement a test as you suggested and get back to you when it's done

2020-11-24 11:23 UTC, sky-hub commented
@eduard13 , test implemented.
Please let me know if there is anything else I can help with.

2020-11-24 12:47 UTC, eduard13 requested changes
Hi @sky-hub, thank you for the test coverage. I've left couple of comments, could you please review them?
Feel free to reach me if additional questions arise.

Thanks.

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +        <waitForPageLoad stepKey="waitForProductPageLoad1"/>
Please try to re-use the existing ActionGroups as much as possible. In this case, we have the `StorefrontOpenProductPageActionGroup` that receives the product url as a parameter.

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +        <see selector="{{AdminCartPriceRulesSection.messages}}" userInput="You saved the rule." stepKey="seeSuccessMessage"/>
I'd create a new ActionGroup that is going to create a new Cart Rule, based on our needs. As arguments, you'll have all the hardcoded inputs from this test:
- ruleName
- websites
- customerGroups
- apply
- discountAmount

This way, we'll be able to re-use this action group in some other tests.
Thank you.

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +        <waitForPageLoad time="30" stepKey="waitForAddBundleProductPageLoad"/>
Could you please double check if you're able to use any of existing ActionGroups that is supposed to add a Bundle product to cart?
Thank you.

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +        <waitForPageLoad stepKey="waitForDetailsOpen"/>
Same here: `StorefrontCartPageOpenActionGroup`

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +
Please remove all the empty rows.
```suggestion
```

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +            <!-- Make Attribute 'sku' accessible for Promo Rule Conditions -->
Also, remove all the comments please, they are unnecessary.

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +            <description value="Checking Fixed Amount Cart Price Rule"/>
Can we extend the title and description here by adding a more meaningful information on what does this test do?

2020-11-24 12:47 UTC, eduard13 commented on app/code/Magento/SalesRule/Test/Mftf/Test/StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest.xml
> +    <test name="StorefrontCartFixedAmountWholeCartDiscountForBundleProductTest">
What do you think if we rename the test as following?
```suggestion
    <test name="StorefrontAssertFixedCartDiscountAmountForBundleProductTest">
```

2020-11-24 12:48 UTC, eduard13 commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2020-11-24 15:33 UTC, eduard13 commented
Additionally, could you please review the failed Functional Tests, as they might be related to your changes?
Thank you.

2020-11-25 09:01 UTC, engcom-Hotel commented
@magento run all tests

2020-11-25 10:50 UTC, engcom-Hotel commented
@magento run all tests

2020-11-26 10:40 UTC, engcom-Hotel commented
@magento run all tests

2020-11-26 13:11 UTC, engcom-Hotel commented
Functional Tests CE

2020-11-26 16:23 UTC, sky-hub commented
@eduard13 , feedback implemented.

2020-11-26 21:11 UTC, eduard13 commented
@magento run all tests

2020-11-27 08:07 UTC, sky-hub commented
@magento run Integration Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

2020-11-27 10:23 UTC, sky-hub commented
@magento run Functional Tests B2B

2020-11-27 13:17 UTC, eduard13 approved these changes
Good job 👍

2020-11-27 13:17 UTC, eduard13 commented
The failed test doesn't seem to be related with the current PR.

2020-11-27 13:18 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8493](https://jira.corp.magento.com/browse/ENGCOM-8493) has been created to process this Pull Request

2020-11-27 14:53 UTC, engcom-Hotel commented
@magento run all tests

2020-11-30 08:21 UTC, engcom-Hotel commented
@magento run all tests

2020-11-30 08:48 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Install Magento 2.4 with sample data;
2. Create cart rule with fixed amount discount  for whole cart (Ex: 50$);
3. Add a bundle product to cart (Example: http://local.magento2.com/sprite-yoga-companion-kit.html)
4. Navigate to checkout/cart page and check discount.

**Before:** :heavy_multiplication_x: Cart discount is 18.85$

![2020-11-30_09-44](https://user-images.githubusercontent.com/51679138/100587469-46bd7900-32f9-11eb-9783-6939214541dc.png)

**After:** :heavy_check_mark: Cart discount is 50$

![2020-11-30_10-06](https://user-images.githubusercontent.com/51679138/100587532-5c32a300-32f9-11eb-8082-22567629e94a.png)

Also was checked with **fixed amount discount** and everything works as expected.

2020-11-30 09:29 UTC, engcom-Hotel commented
@magento run all tests

2020-11-30 16:57 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2020-12-01 10:48 UTC, engcom-Hotel commented
@magento run all tests

2020-12-01 17:42 UTC, engcom-Hotel commented
@magento run all tests

2020-12-02 18:34 UTC, engcom-Hotel commented
@magento run all tests

2020-12-03 11:14 UTC, engcom-Hotel commented
@magento run Functional Tests CE

2020-12-10 12:42 UTC, merged