$product is Product model or DataObject
magento/magento2 pull request #31005
Opened 2020-11-22 15:00 UTC by dfelton

### Description (*)

Updates the phpdoc to better reflect the potential object type.

\Magento\Catalog\Ui\Component\Listing\Columns\Thumbnail::prepareDataSource() is an example of where the first argument passed to \Magento\Catalog\Helper\Image::init() is not actually an instance of \Magento\Catalog\Model\Product, but rather, just an instance of \Magento\Framework\DataObject.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

This is only an update of the PHP doc in (what I believe) is not a class where the PHP Doc is parsed out by any tools. No testing done.

### Questions or comments

In my current project, I had built a `beforeInit()` plugin to `\Magento\Catalog\Helper\Image::init()`. The signature of my `beforeInit()` plugin specified that the second argument to the plugin must be an object of `\Magento\Catalog\Model\Product`. This then broke the product grid page of the admin because [\Magento\Catalog\Ui\Component\Listing\Columns\Thumbnail::prepareDataSource()](https://github.com/magento/magento2/blob/f55f4117d2a87e5a29efd58fbb14fb4c4cd60bee/app/code/Magento/Catalog/Ui/Component/Listing/Columns/Thumbnail.php#L55) does not pass a product model, but rather simply an instance of `\Magento\Framework\DataObject`.

To provide to developers better context into the possible object types passed to this non-type-hinted method, I think an updated phpdoc is appropriate.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-22 20:09 UTC, dfelton commented
@magento run all tests

2020-11-24 17:03 UTC, gabrieldagama commented
@magento create issue

2021-01-15 14:13 UTC, ihor-sviziev requested changes
Hi @dfelton,
It seems to me that the issue you're referencing is the opposite - in the https://github.com/magento/magento2/blob/f55f4117d2a87e5a29efd58fbb14fb4c4cd60bee/app/code/Magento/Catalog/Ui/Component/Listing/Columns/Thumbnail.php#L55, we should have the product model, not the data object.
Could you update your PR in order to fix that?

2021-04-14 06:24 UTC, ihor-sviziev commented
Hi @dfelton,
I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2021-04-14 06:24 UTC, closed without merging