MC-33499: Grid Filter not working for Scheduled Export when selected any kind of Entity Type
magento/magento2 pull request #31060
Opened 2020-11-25 15:58 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/partners-magento2ee#361

### Manual testing scenarios (*)

1. See: magento/partners-magento2ee#361

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-25 15:58 UTC, engcom-Echo commented
@magento run all tests

2020-12-30 15:27 UTC, engcom-Echo commented
@magento run all tests

2021-01-14 07:21 UTC, engcom-Echo commented
@magento run all tests

2021-01-14 14:04 UTC, engcom-Echo commented
@magento run all tests

2021-01-17 22:13 UTC, engcom-Echo commented
@magento run all tests

2021-01-18 08:22 UTC, engcom-Echo commented
@magento run all tests

2021-01-18 09:43 UTC, engcom-Echo commented
@magento run all tests

2021-01-19 08:20 UTC, zakdma requested changes

2021-01-19 08:20 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> + * Class AttributeGridCollection
Please provide meaningful description for class

2021-01-19 08:20 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +        $value = (string)$condition['like'];
You should check that condition['like'] really exists. You should pass all not like conditions

2021-01-19 08:20 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +        $value = trim(trim($value, "'"), "%");
You can provide set of trimmed chars as second parameter of trim. No need to call it twice
https://www.php.net/manual/ru/function.trim.php

2021-01-19 08:20 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +            $this->_items = array_reverse($this->_items, true);
This is redundant and make performance hit
Better create anonymous function for sorting and pass order to it using use statement.

2021-01-19 08:20 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +        $this->_orderField = $field;
_orderField is not declared
Actually setOrder should not do sorting immediately but store sorting fields in $this->_orders
The same for addFieldToFilter
Actually filtering and sorting should perform in load (or loadData) method

2021-01-19 08:20 UTC, zakdma commented on app/code/Magento/ImportExport/Block/Adminhtml/Export/Filter.php
> +        $attributeGridCollection = $this->attributeGridCollectionFactory->create();
It is better to do this in controller and pass prepared collection to block.

2021-01-20 13:41 UTC, engcom-Echo commented
@magento run all tests

2021-01-20 15:21 UTC, zakdma requested changes

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +
Remove redundant empty line

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Block/Adminhtml/Export/Filter.php
> +        return $collection;
add empty line before return

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +     * @return int
Redundant @return annotation

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +     * @param string $field
Redundant @param and @return annotations

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +     * @param false $printQuery
Redundant @param and @return annotations

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +                $this->setFlag('isFilter', true);
I suppose it should be moved after $this->_filters loop

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +    public function load($printQuery = false, $logQuery = false)
Please extract filter code and sort code in separate private methods

2021-01-20 15:21 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +            return $sortOrder === self::SORT_ORDER_ASC ? $cmp : -$cmp;
please add empty line before return

2021-01-21 13:16 UTC, engcom-Echo commented
@magento run all tests

2021-01-25 09:52 UTC, zakdma approved these changes

2021-01-26 07:01 UTC, engcom-Echo commented
@magento run all tests

2021-01-26 16:33 UTC, engcom-Echo commented
@magento run all tests

2021-01-27 09:52 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-01-27 09:54 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31060`.

2021-01-27 10:40 UTC, zakdma requested changes

2021-01-27 10:40 UTC, zakdma commented on app/code/Magento/ImportExport/Model/ResourceModel/Export/AttributeGridCollection.php
> +            $value = str_replace('\\','',$value);
That is not enough/ Please refer to \Magento\Framework\DB\Helper\AbstractHelper::escapeLikeValue that used to escape values for like condition
You should create separate private method unescapeLikeCondition($condition) where do all the job
1) Trim ' and % as you did
2) Replace \_ to _
3) Replace \% to %

2021-01-27 12:39 UTC, engcom-Echo commented
@magento run all tests

2021-01-27 13:34 UTC, zakdma approved these changes

2021-01-28 11:51 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-01-28 11:53 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31060`.

2021-01-28 16:39 UTC, engcom-Echo commented
@magento run all tests

2021-01-29 17:59 UTC, merged