MC-37807: Link to a file of a Product with Customizable Option(File) is not available throughout a multishipping checkout process
magento/magento2 pull request #31066
Opened 2020-11-26 09:21 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#

### Manual testing scenarios (*)

Steps to Reproduce:

1. Go to the Storefront as the created Customer
2. Add the created Product to the Shopping Cart (Qty = 2), uploading a valid file
3. Open the mini-cart
4. Click the “View and Edit Cart” link
5. Click the “Check Out with Multiple Addresses” link
6. Select shipping addresses on the “Ship to Multiple Addresses”
7. Click the “Go to Shipping Information” button
8. Select Flat Rate - Fixed Shipping Method for the each address
9. Click the “Continue to Billing Information” button
10. Select “Check / Money order” Payment Method
11. Click the “Go to Review Your Order” button

**Expected results:**
There should be a link, enabling file downloading, throughout entire multishipping checkout process (name of the file)

 **Actual results:**
There is no link enabling file downloading throughout entire multishipping checkout process (name of the file)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-27 11:00 UTC, engcom-Echo commented
@magento run all test

2020-11-27 13:12 UTC, engcom-Echo commented
@magento run all test

2020-11-27 15:22 UTC, engcom-Echo commented
@magento run all test

2020-11-27 15:23 UTC, engcom-Echo commented
@magento run all tests

2020-11-27 16:52 UTC, zakdma requested changes

2020-11-27 16:52 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Multishipping/Block/Checkout/OverviewTest.php
> +    protected $block;
Do you really need this be protected? Make it private if possible

2020-11-27 16:52 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Multishipping/Block/Checkout/OverviewTest.php
> +    protected $objectManager;
Do you really need this be protected? Make it private if possible

2020-11-27 16:52 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Multishipping/Block/Checkout/OverviewTest.php
>      protected function setUp(): void
Add @inheritDoc annotation

2020-11-27 16:52 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Multishipping/Block/Checkout/OverviewTest.php
> +        $this->quote = $this->objectManager->get(Quote::class);
Please use  ...Factory to create objects.
Same for next 2 lines

2020-11-27 16:52 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Multishipping/Block/Checkout/OverviewTest.php
> +        $product = $this->product->load('1');
Have to use ProductRepository to get product instance by ID

2020-11-30 08:28 UTC, engcom-Echo commented
@magento run all tests

2020-11-30 11:46 UTC, engcom-Kilo approved these changes

2020-11-30 14:27 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Create a Simple Product with **Customizable Option** type - **File**
![cust_opt_type_file](https://user-images.githubusercontent.com/51680745/100619741-3e2f6780-3326-11eb-9786-aad7e163d64f.png)
2. Go to Storefront and Sign In as Customer
3. Open the previously crated products page and Upload a valid file
![valid_file_upload](https://user-images.githubusercontent.com/51680745/100620225-d75e7e00-3326-11eb-96d8-f4bcb35cc938.png)
4. Add the previously created product to the Cart in a **Quantity of 2 items**
5. Click on mini cart and click **View and Edit Cart**
6. Click **Check Out with Multiple Addresses**
7.  Select different addresses in **Ship to Multiple Addresses** window
![1_Ship to multiple](https://user-images.githubusercontent.com/51680745/100620688-6075b500-3327-11eb-8a27-61cd0fe3e3fa.png)
_Note that the link to the image files are valid_
8. Click **Go to Shipping Information**
9. Observe the links to the file in **Select Shipping Method**
![2_sel_ship_meth](https://user-images.githubusercontent.com/51680745/100621068-d8dc7600-3327-11eb-9232-11f695316c8e.png)
_Note that the link to the image files are valid_
10. Click **Continue to Billing Information**
11. Click **Go to Review Your Order**
12. Observe the links to the files in **Review Order** window
![3_place_order](https://user-images.githubusercontent.com/51680745/100621290-2953d380-3328-11eb-83ca-2492cb3816cc.png)
_Note that the links are valid and redirect to downloading the previously uploaded image_

**BEFORE** applying changes provided in this PR, only text with image name was displayed 
![before](https://user-images.githubusercontent.com/51680745/100621630-92d3e200-3328-11eb-97ed-8e3e83830239.png)

**AFTER** switching to the PR, the text is a link that redirects to file downloading. The links are valid through the whole multi shipping process.
The order could be Placed successfully.

2020-11-30 14:29 UTC, engcom-Bravo commented
@magento create issue

2020-12-10 09:32 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2020-12-10 09:35 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2020-12-10 09:36 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2020-12-10 10:03 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2020-12-10 10:05 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31066`.

2020-12-12 07:59 UTC, merged