reset count flag is not taken to account when setting qty
magento/magento2 pull request #31085
Opened 2020-11-28 03:04 UTC by devzer01

### Description (*)
when using the rest api and updating an item in the cart with a new qty the qty in cart is + to qty in the candidate even when the reset count flag is set to true. 

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-11-28 03:41 UTC, devzer01 commented
@magento run all tests

2020-11-28 05:10 UTC, devzer01 commented
@magento run Functional Tests CE

2020-11-29 16:07 UTC, rogyar requested changes
Hi @devzer01. Thank you for your collaboration. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html), all changes must be covered with auto-tests. I would ask you to cover this case with an API-functional test that will use the `reset_count` flag and check the result. 

Thank you!

2020-12-02 04:02 UTC, devzer01 commented
yes will do thanks for the feedback

2020-12-02 16:41 UTC, sidolov commented
@magento create issue

2022-10-13 15:01 UTC, ishakhsuvarov commented
Hi @devzer01 

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:01 UTC, closed without merging