Refactoring of ProductsQtyReturnAfterOrderCancelTest
magento/magento2 pull request #31097
Opened 2020-11-30 14:58 UTC by AnnaAPak

### Description (*)
A new test has been created according to the best practices followed by MFTF.
The old "ProductsQtyReturnAfterOrderCancelTest" has been deprecated.

### Manual testing scenarios (*)
1. Create a product
2. Place an order with the products created (qty to order=4)
3. Create a partial invoice (qty to invoice=1)
4. Create a shipment
5. Cancel  the order
6. Check if product qty is correct

2020-11-30 15:00 UTC, AnnaAPak commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-11-30 17:49 UTC, rogyar requested changes
Good job! Please, check my suggestions

2020-11-30 17:49 UTC, rogyar commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminInvoiceWIthUpdatedProductQtyActionGroup.xml
> +    <actionGroup name="AdminInvoiceWIthUpdatedProductQtyActionGroup" extends="AdminCreateInvoiceActionGroup">
Please, check the naming 
```suggestion
    <actionGroup name="AdminInvoiceWithUpdatedProductQtyActionGroup" extends="AdminCreateInvoiceActionGroup">
```

2020-11-30 18:06 UTC, AnnaAPak commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminInvoiceWIthUpdatedProductQtyActionGroup.xml
> +    <actionGroup name="AdminInvoiceWIthUpdatedProductQtyActionGroup" extends="AdminCreateInvoiceActionGroup">
Corrected, thank you.

2020-11-30 18:06 UTC, AnnaAPak commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-12-02 13:24 UTC, rogyar approved these changes
The failing tests are not related to the current changeset

2020-12-02 13:25 UTC, magento-engcom-team commented
Hi @rogyar, thank you for the review.
[ENGCOM-8506](https://jira.corp.magento.com/browse/ENGCOM-8506) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2020-12-02 16:05 UTC, sidolov commented
@magento create issue

2020-12-03 11:39 UTC, engcom-Bravo commented
Checked the Manual Scenario provided in the PR-s description
1. Create a product
2. Place an order with the products created (qty to order=4)
3. Create a partial invoice (qty to invoice=1)
4. Create a shipment
5. Cancel  the order
6. Check if product qty is correct

The Total Canceled amount is correct. 99$ product price * 3qty = 297$
![canceled](https://user-images.githubusercontent.com/51680745/101013211-9ce62280-356c-11eb-963c-76ec7164fda8.png)

Moving the PR to Extended Testing column as this is a Refactoring PR

2020-12-08 13:36 UTC, engcom-Hotel commented
@magento run all tests

2020-12-08 17:11 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2020-12-22 00:37 UTC, merged