Change isDeferEnabled() to public function
magento/magento2 pull request #31149
Opened 2020-12-03 14:06 UTC by Tjitse-E

### Description (*)
It would be nice it `\Magento\Theme\Controller\Result\JsFooterPlugin::isDeferEnabled` was a public method, so we can use plugins to modify the outcome. 

A use case for this would be to maybe disable defer JS on specific pages, this could be easily done then with an after plugin on `\Magento\Theme\Controller\Result\JsFooterPlugin::isDeferEnabled`

### Fixed Issues (if relevant)
None 

### Manual testing scenarios (*)
None

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-03 15:25 UTC, sidolov commented
@magento create issue

2020-12-04 08:41 UTC, rogyar requested changes
Hi @Tjitse-E. I like the idea but the implementation might be improved. I believe we don't want to have a plugin for the plugin though :) 

What I suggest is moving all the business logic from this plugin to a separate class (`DeferJsFiles` with the only one public `execute` method). Then invoke the new class in the current plugin. Then you may extend the new `DeferJsFiles` with plugins in any way you want. 

Hope it makes sense.

2020-12-06 14:03 UTC, Tjitse-E commented
@rogyar that sounds like a good idea. I'll make the changes.

What about also moving the entire plugin from the 'Controller' folder to the 'Plugin' folder? It seems odd that a plugin resides in the Controller folder.

2020-12-09 12:19 UTC, rogyar commented
Hi @Tjitse-E. I believe it's a good idea, thanks.

2021-04-23 12:25 UTC, ihor-sviziev commented
We have similar issue with AMP module, as AMP version is suppose to have scripts in the head section

2021-04-28 09:10 UTC, Tjitse-E commented
@ihor-sviziev  haven't started with the changes yet, hopefully I can handle this next month.

2021-04-28 09:48 UTC, ihor-sviziev commented
@Tjitse-E FYI there is a dirty workaround. If you'll use something like `<script data-skip="text/x-magento-template">...</script>` - it won't move this script to before body end

2022-10-13 15:10 UTC, ishakhsuvarov commented
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:10 UTC, closed without merging