200 Response Code When Exception is Thrown During Bootstrap #30847
magento/magento2 pull request #31159
Opened 2020-12-04 06:59 UTC by devamitbera

#30847

2020-12-04 08:41 UTC, ihor-sviziev requested changes

2020-12-04 08:41 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/App/Bootstrap.php
> +                header('HTTP/1.1 503 Service Temporarily Unavailable');
1. I believe it should be 500 error, right?
2. In case if that's developer mode I think we need to send this status header also.

2020-12-04 08:42 UTC, ihor-sviziev commented
@devamitbera could you also sign the Adobe CLA?

2020-12-07 15:32 UTC, ihor-sviziev commented
Hi @devamitbera,
Thank you for signing Adobe CLA. Could you also review my suggestions in https://github.com/magento/magento2/pull/31159#discussion_r535926455 and update your PR accordingly?

2020-12-07 15:33 UTC, ihor-sviziev commented
@magento run all tests

2020-12-07 15:57 UTC, devamitbera commented
Hi @ihor-sviziev 

I will update the changes tomorrow.

Thanks

2020-12-09 10:15 UTC, devamitbera commented
Hi @ihor-sviziev 

Changes done.Please check.

2020-12-09 10:25 UTC, ihor-sviziev requested changes

2020-12-09 10:25 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/App/Bootstrap.php
>          if ($this->isDeveloperMode()) {
Can we add single such block here and remove it in those 2 places below?
```suggestion
        if (!headers_sent()) {
            header('HTTP/1.1 500 Internal Server Error');
        }

        if ($this->isDeveloperMode()) {
```

2020-12-09 18:52 UTC, ihor-sviziev commented
@magento run all tests

2020-12-10 08:52 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2020-12-10 08:53 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2020-12-10 08:54 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8531](https://jira.corp.magento.com/browse/ENGCOM-8531) has been created to process this Pull Request

2020-12-14 09:15 UTC, engcom-Alfa requested changes
Hi @devamitbera.

Could you resolve merge conflicts?
Thanks!

2020-12-14 09:30 UTC, engcom-Alfa commented
@devamitbera 
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.

**Actual Reslt:** :heavy_check_mark: An error message is displayed and a 500 response code is returned.

Look like this issue has already been fixed by commit fd8749f6.

@devamitbera Could you take a look?
Thanks!

2020-12-14 17:08 UTC, devamitbera commented
Hi @engcom-Alfa
Yes, seem the issue has been fixed at https://github.com/magento/magento2/commit/fd8749f6ecea40dcd759b1bf76cb68695737fadf

I think you can  Close  my PR as it is  ready fixed https://github.com/magento/magento2/commit/fd8749f6ecea40dcd759b1bf76cb68695737fadf

2020-12-15 07:26 UTC, ihor-sviziev commented
@devamitbera thx for confirmation. I'm closing this PR.

2020-12-15 07:26 UTC, closed without merging