MC-36425: “Select Shipping Method” page of Multishipping Checkout is corrupted if a Customer use “go back” browser button to return to the page
magento/magento2 pull request #31156
Opened 2020-12-03 15:53 UTC by engcom-Kilo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/30268

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/30268

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-03 15:54 UTC, engcom-Kilo commented
@magento run all tests

2020-12-03 18:59 UTC, engcom-Kilo commented
@magento run all tests

2020-12-04 08:43 UTC, rogyar commented on app/code/Magento/Multishipping/Test/Mftf/Test/StorefrontCreateOrderWithMultishippingAfterReturningToCartTest.xml
> +            <magentoCLI command="config:set {{DisableFreeShippingMethod.path}} {{DisableFreeShippingMethod.value}}" stepKey="disableFreeShipping"/>
That's so awesome that we don't clean cache after setting a config via CLI anymore (it's invalidated automatically in this case). 

Great job!

2020-12-04 13:08 UTC, engcom-Kilo commented
@magento run all tests

2020-12-07 11:25 UTC, zakdma requested changes

2020-12-07 11:25 UTC, zakdma commented on app/code/Magento/Multishipping/Test/Mftf/Test/StorefrontCreateOrderWithMultishippingAfterReturningToCartTest.xml
> +            <testCaseId value="MC-39583"/>
Please add MC-39583 as **has tests** link to task
Please specify test Path in MC-39583 zephyr
Please add **Expected result** for steps in MC-39583 zephyr

2020-12-07 11:25 UTC, zakdma commented on app/code/Magento/Multishipping/Test/Mftf/Test/StorefrontCreateOrderWithMultishippingAfterReturningToCartTest.xml
> +        <actionGroup ref="LoginToStorefrontActionGroup" stepKey="loginToStorefrontAccount">
Please add logout in **after** section but before customer delete

2020-12-07 11:25 UTC, zakdma commented on app/code/Magento/Multishipping/Test/Mftf/Test/StorefrontCreateOrderWithMultishippingAfterReturningToCartTest.xml
> +            <argument name="Customer" value="$$customer$$"/>
Please dont use $$. Use single $ instead

2020-12-07 11:50 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2020-12-07 11:53 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31156`.

2020-12-07 12:20 UTC, zakdma commented
@magento run all tests

2020-12-07 13:58 UTC, zakdma approved these changes

2020-12-07 14:19 UTC, zakdma commented
@magento run all tests

2020-12-07 15:12 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario 
1. Go to the Storefront as the created Customer
2. Add the created Product (2pcs) to the Shopping Cart
3. Open the mini-cart
4. Click the {color:#0747a6}“View and Edit Cart”{color} link
5. Click the “{color:#0747a6}Check Out with Multiple Addresses”{color} link
6. Select shipping addresses
7. Click the “Go to Shipping Information” button
8. Select Flat Rate shipping method
9. Click the “Continue to Billing Information” button
10. Click the "Add or remove gift cards" link on the “Billing Information” page
11. Wait until the “Shopping Cart” page is loaded completely
12. Click the “go back” browser button (left arrow)
13. Click the {color:#0747a6}”Back to Shipping Information” link on the “Billing Information” page

**BEFORE** applying changes provided in the PR, the web page was not fully loaded, and an Exception appeared
![pr_before](https://user-images.githubusercontent.com/51680745/101367690-13f22280-38af-11eb-9a28-e98f80f1bece.png)

**AFTER** switching to the PR, the page is fully loaded with no errors 
![pr_after](https://user-images.githubusercontent.com/51680745/101367934-3a17c280-38af-11eb-9b49-c18cd135351f.png)

The order can be placed successfully

2020-12-07 17:56 UTC, zakdma commented
@magento run Functional Tests EE, Integration Tests

2020-12-07 22:17 UTC, zakdma commented
@magento run Functional Tests B2B

2020-12-08 05:19 UTC, zakdma commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2020-12-08 07:48 UTC, zakdma commented
@magento run Functional Tests B2B, Functional Tests EE

2020-12-09 10:34 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2020-12-09 10:37 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31156`.

2020-12-09 10:54 UTC, zakdma commented
@magento run all tests

2020-12-09 12:00 UTC, zakdma commented
@magento run Functional Tests CE

2020-12-14 08:22 UTC, zakdma commented
Changes was delivered in scope of internal ticket MC-36425

2020-12-14 08:22 UTC, closed without merging