Invalid combination of tabs and spaces in phpstan.neon
magento/magento2 pull request #31165
Opened 2020-12-04 11:03 UTC by DmitryFurs

### Description (*)

The [phpstan.neon](https://github.com/magento/magento2/blob/2.4.1/dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon) file contains both spaces and tabs for different lines. But one line contains both characters. In our case, this line is a comment, and it is ignored during parsing, but this is denied by [nette/neon](https://github.com/nette/neon/blob/v3.2.1/src/Neon/Decoder.php#L229) parser. In addition, for code consistency, it must be brought to a common style.

### Related Pull Requests

https://github.com/magento/magento2/commit/4e045c7c291658e4843aca93077d00791ed8b9ea#diff-b47a177d03a63c60ce971880ec7d61c2ba5bb7126f3ec0357f97059e4db4f859
https://github.com/magento/magento2/commit/19b636e90432066692b3ad9f9a27d2eca4879d45#diff-b47a177d03a63c60ce971880ec7d61c2ba5bb7126f3ec0357f97059e4db4f859

### Manual testing scenarios (*)

1. Open [phpstan.neon](https://github.com/magento/magento2/blob/2.4.1/dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon) file in PhpStorm with [NEON support](https://plugins.jetbrains.com/plugin/7060-neon-support) plugin
2. It is highlighted with errors
![image](https://user-images.githubusercontent.com/1055999/101156294-70e4a300-3639-11eb-99f1-947be58fddd2.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-04 14:07 UTC, ihor-sviziev requested changes
good catch.
Can we add it to the .editorconfig file?

2020-12-04 14:08 UTC, ihor-sviziev commented
@magento run Static Tests

2020-12-04 15:07 UTC, DmitryFurs commented
@ihor-sviziev it looks like this is already covered by the [global rules](https://github.com/magento/magento2/blob/2.4.1/.editorconfig#L6-L7)
```neon
[*]
...
indent_size = 4
indent_style = space
...
```

2020-12-06 19:25 UTC, ihor-sviziev commented
@magento run all tests

2020-12-07 07:49 UTC, ihor-sviziev commented
@magento run WebAPI Tests

2020-12-07 14:19 UTC, ihor-sviziev approved these changes

2020-12-07 14:21 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8527](https://jira.corp.magento.com/browse/ENGCOM-8527) has been created to process this Pull Request

2020-12-10 07:37 UTC, engcom-Alfa commented
@magento create issue

2020-12-10 07:44 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: Invalid combination of tabs and spaces 

![Screenshot from 2020-12-10 09-35-43](https://user-images.githubusercontent.com/51679138/101736543-4462d800-3acc-11eb-98dd-090b46bce760.png)

**After:** :heavy_check_mark: 

![Screenshot from 2020-12-10 09-43-09](https://user-images.githubusercontent.com/51679138/101736588-5b092f00-3acc-11eb-8981-249f421364c2.png)

2020-12-22 00:37 UTC, merged