Update `data-price-amount` on reload price
magento/magento2 pull request #31200
Opened 2020-12-08 08:21 UTC by NickdeK

This resolved the issue reported in #31199 and updates the `data-price-amount` correctly on configurable product changes.

### Description (*)
Update the `data-price-amount` in the `reloadPrice` function that is used to render the updated prices on the configurable product page.

### Related Pull Requests
None

### Fixed Issues (if relevant)
1. Fixes magento/magento2#31199

### Manual testing scenarios (*)
1. Go to a configurable product where the price changes when options are changed
2. On page load the data-price-amount on the span's with class price-wrapper are set correctly
3. Change the options so the price(s) change on the page
4. The `data-price-amount` should be updated correctly.

### Questions or comments
None

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-10 12:57 UTC, ptylek commented
@magento run all tests

2021-01-21 08:09 UTC, ihor-sviziev requested changes
Hi @NickdeK,
Could you cover your change with some test?

2021-02-26 08:30 UTC, ihor-sviziev commented
@NickdeK, will you be able to add test coverage?

2021-03-02 15:19 UTC, NickdeK commented
@ihor-klymchuk I intended to create some tests, but I'm pretty swamped right now to do so. I'm unfamiliar with writing tests for Magento and need to read up on that.

2021-04-22 07:14 UTC, NickdeK commented
@ihor-klymchuk I've finally found some time to try and write a test but I'm unable to. The [Magento Devdocs](https://devdocs.magento.com/guides/v2.4/test/js/jasmine.html) are not helpful at all. I can't figure out how `beforeEach` works, what it's for and how to mock a price update.

I'm giving up on writing a test for this PR. If someone else can write a test for this that would be great.

2022-06-09 15:09 UTC, closed without merging

2022-06-14 19:41 UTC, ihor-sviziev commented
Hi @NickdeK,
Looks I missed your comments because you mentioned not me 😔
In case if it's too complicated to add a test coverage - I think we can leave it w/o test coverage.

Could you please clarify, does it causes any issues in the functionality in Magento? Or it's needed for your own customization? What is the use case, as now it looks like a pretty low priority

2022-06-14 21:53 UTC, NickdeK commented
Hi @ihor-sviziev. I'm not sure how I didn't mention you, it seems that I did when looking back at the comments.

As I recall this doesn't effect any functionality in Magento, but developers who use or want to use the `data` attribute should have access to correct price data or the whole `data` attribute should be removed all together. Use cases for this data attribute could be price related custom components/scripts, this can range from custom price renderers to Analytics scripts that consume prices in customer flows.

I closed the PR because I was cleaning up my pull requests that where stale. Feel free to do whatever you think is best for the project.

2022-06-14 21:57 UTC, ihor-sviziev commented
@NickdeK,
Thank you for quick update and for your contribution!
It does make sense, but still, looks as pretty low priority. Let’s leave this PR closed for now. Maybe later we’ll find more important issue that could be fixed by these changes.