Allow use unitless in mixin lib-line-height
magento/magento2 pull request #31279
Opened 2020-12-14 18:41 UTC by mrtuvn

### Description (*)

Before this PR magento not properly set line-height with unitless value

.lib-line-height(1) => output line-height: 0.1rem;
Expected result => output line-height: 1;

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Go to theme less file. Example app/design/frontend/Magento/blank/Magento_Theme/web/css/source/_module.less
2. Add style
body .page-title {.lib-line-height(1.5);}
3. Run setup static and clear cache
4. Inspect page title element in page by browser to view result styles

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-14 18:41 UTC, mrtuvn commented
@magento run all tests

2020-12-14 18:58 UTC, mrtuvn commented
@magento run all tests

2020-12-16 14:36 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2020-12-17 04:24 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests EE

2020-12-18 06:52 UTC, mrtuvn commented
@magento run all tests

2020-12-18 11:36 UTC, mrtuvn commented
@magento run WebAPI Tests, Unit Tests

2021-01-13 01:27 UTC, Leland commented on lib/web/css/source/lib/_typography.less
>  }
My local environments need a tune up before I can test this, but this looks promising! Can you make sure to add some comments explaining what all these booleans are doing? No future dev will be able to make heads or tails of these, speaking from experience looking at M2 LESS 😆

2021-01-13 01:29 UTC, Leland requested changes
.

2021-01-13 11:47 UTC, mrtuvn commented
@magento run all tests

2021-01-14 13:48 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests CE

2021-01-14 16:28 UTC, Leland approved these changes
LGTM 🤘

2021-01-15 00:50 UTC, mrtuvn commented
rebased code branch by mainline branch

2021-01-15 01:08 UTC, mrtuvn commented
@magento run all tests

2021-01-16 11:13 UTC, mrtuvn commented
@magento run all tests

2021-01-18 15:02 UTC, mrtuvn commented
@magento run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2021-01-19 02:45 UTC, mrtuvn commented
@magento run all tests

2021-01-19 16:10 UTC, mrtuvn commented
@magento run all tests

2021-01-20 12:48 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2021-01-21 14:57 UTC, mrtuvn commented
Rebased code

2021-01-23 03:15 UTC, mrtuvn commented
rebased code
@magento run all tests

2021-01-23 13:42 UTC, mrtuvn commented
@magento run Functional Tests B2B, Functional Tests CE

2024-04-16 09:54 UTC, engcom-Bravo commented
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

2024-04-16 09:54 UTC, closed without merging