[MFTF] Adding AdminSelectAttributeSetOnEditProductPageActionGroup
magento/magento2 pull request #31287
Opened 2020-12-15 10:29 UTC by AnnaAPak

### Description (*)
Adding AdminSelectAttributeSetOnEditProductPageActionGroup

2020-12-15 10:30 UTC, AnnaAPak commented
@magento run Functional Tests B2B, Functional Tests EE

2020-12-15 16:06 UTC, sidolov commented
@magento create issue

2020-12-15 16:58 UTC, AnnaAPak commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-12-16 09:24 UTC, eduard13 requested changes
Hi @AnnaAPak could you please check the minor comment that I left?
Thank you.

2020-12-16 09:24 UTC, eduard13 commented on app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminSelectAttributeSetOnEditProductPageActionGroup.xml
> +                         The Edit Product Page should be opened prior to Action Group execution</description>
I would refactor this part. As for `The Edit Product Page should be opened prior to Action Group execution` sentence, I think that is extra. Usually, you are checking the ActionGroup implementation before using it.

```suggestion
            <description>Selects the specified value from the Attribute Set dropdown on the opened product edit page.</description>
```

2020-12-17 09:36 UTC, AnnaAPak commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-12-17 12:48 UTC, AnnaAPak commented
@eduard13  can you please take a look one more time? Thank you.

2020-12-17 12:50 UTC, eduard13 commented
@magento run all tests

2020-12-18 08:01 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE

2020-12-18 10:56 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE

2020-12-21 06:16 UTC, eduard13 approved these changes

2020-12-21 08:18 UTC, engcom-Alfa commented
QA not applicable

2020-12-23 05:06 UTC, merged