Fix issue #24635: Use of undefined constant GLOB_BRACE in dependency …
magento/magento2 pull request #31296
Opened 2020-12-16 08:19 UTC by vidyli

2020-12-16 08:23 UTC, ihor-sviziev commented
@vidyli could you add to the PR description the following line?
> Fixes https://github.com/magento/magento2/issues/24635

@magento run all tests

2020-12-16 09:49 UTC, ihor-sviziev commented
@magento run Static Tests, Unit Tests

2020-12-16 10:43 UTC, ihor-sviziev commented
@vidyli Seems like some changes should be done also on EE or/and B2B repositories.
I see you don't have access to them, so we'll ask someone from the internal team to check it

2020-12-16 14:14 UTC, engcom-Golf commented
@magento run all tests

2020-12-16 14:59 UTC, gabrieldagama commented
@magento run all tests

2020-12-16 16:21 UTC, ihor-sviziev commented
@engcom-Golf the tests still failing

2020-12-16 16:27 UTC, engcom-Golf commented
I see. Requires changes to infrastructure repo. Will address it. On Dec 16, 2020 6:21 PM, Ihor Sviziev <notifications@github.com> wrote:
@engcom-Golf the tests still failing

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-17 10:20 UTC, engcom-Golf commented
@magento run all tests

2020-12-17 13:55 UTC, ihor-sviziev requested changes

2020-12-17 13:55 UTC, ihor-sviziev commented on composer.lock
> +                "mirrors": [
@vidyli,
oh... we shouldn't have mirrors section in the composer.lock files.
Could you configure your composer to not use mirrors and run the `composer update` command?

2020-12-17 14:08 UTC, ihor-sviziev commented
@engcom-Golf thx for help!

2020-12-18 04:18 UTC, ihor-sviziev commented
@magento run all tests

2020-12-18 06:47 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Unit Tests

2020-12-18 11:02 UTC, engcom-Golf commented
@magento run all tests

2020-12-18 14:48 UTC, ihor-sviziev commented
@engcom-Golf any thoughts on why unit tests are failing?

2020-12-20 17:09 UTC, fredden requested changes

2020-12-20 17:09 UTC, fredden commented on composer.json
> +        "allure-framework/allure-phpunit": "~1.3.0",
Version 1.3.0 doesn't contain the fix for the bug you're trying to fix here.
```suggestion
        "allure-framework/allure-phpunit": "~1.3.1",
```

2020-12-22 09:40 UTC, ihor-sviziev commented
@magento run all tests

2020-12-22 10:42 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Unit Tests

2020-12-22 12:37 UTC, ihor-sviziev requested changes
Hi @vidyli,
Could you check why the unit tests are failing?

2020-12-23 12:11 UTC, fredden approved these changes

2020-12-23 12:47 UTC, ihor-sviziev requested changes
Unit tests still failing. Please check why and fix that

2021-01-05 08:59 UTC, ihor-sviziev commented
@magento run WebAPI Tests, Unit Tests, Functional Tests B2B

2021-01-14 14:51 UTC, ihor-sviziev commented
@magento run WebAPI Tests, Unit Tests, Functional Tests B2B

2021-01-14 14:52 UTC, ihor-sviziev commented
@magento run all tests

2021-01-14 15:00 UTC, ihor-sviziev commented
Hi @engcom-Golf,
Could you help with the `Pull Request not mergeable` issue on tests?
Thank you

2021-01-15 08:56 UTC, engcom-Golf commented
@magento run all tests

2021-01-24 11:28 UTC, ihor-sviziev approved these changes

2021-01-24 11:29 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8698](https://jira.corp.magento.com/browse/ENGCOM-8698) has been created to process this Pull Request

2021-01-24 11:29 UTC, magento-engcom-team commented
@vidyli thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2021-03-31 05:42 UTC, ihor-sviziev requested changes
Could you resolve conflicts?

2021-04-06 16:20 UTC, gabrieldagama commented
Hi @vidyli, can you update your branch and resolve the conflicts?

Thanks!

2021-04-07 04:30 UTC, ihor-sviziev commented
@magento run all tests

2021-04-07 05:56 UTC, ihor-sviziev commented
Hi @engcom-Golf,
Could you resolve conflicts in the related PRs as the author doesn't have access to these repositories?

2021-04-09 13:39 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-13 11:19 UTC, ihor-sviziev commented
Hi @engcom-Foxtrot,
Could you update this dependency to at least 1.4.0 https://packagist.org/packages/allure-framework/allure-phpunit#1.4.0, as this is a requirement for updating another extension in https://github.com/magento/magento2/pull/32614 ?

2021-04-14 06:12 UTC, ihor-sviziev commented
@engcom-Foxtrot, tests still failing :(

2021-04-14 10:24 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-15 09:16 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-15 11:41 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-04-15 11:50 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-04-15 13:57 UTC, ihor-sviziev approved these changes

2021-04-15 13:57 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-04-15 13:58 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8698](https://jira.corp.magento.com/browse/ENGCOM-8698) has been created to process this Pull Request

2021-04-19 05:58 UTC, ihor-sviziev commented
@engcom-oscar, could you take this issue in testing, as it's blocking the https://github.com/magento/magento2/pull/32614?

2021-04-21 09:28 UTC, ihor-sviziev commented
I added label project php8, as we have dependency on this PR there.

2021-04-23 10:45 UTC, sivaschenko commented
@ihor-sviziev removed "Project: PHP8" label to merge this PR together with other PRs from high priority board

2021-04-28 08:28 UTC, merged