Update Magento_Bundle ReadMe
magento/magento2 pull request #31304
Opened 2020-12-16 15:17 UTC by korovitskyi

### Description (*)

Update README.md file for Magento_Bundle module.

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/devdocs magento/devdocs#4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-17 13:00 UTC, rogyar requested changes
Hi @korovitskyi. Great job! Please, check my suggestions below

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +Before disabling or uninstalling this module, note that the following modules depends on this module:
```suggestion
Before disabling or uninstalling this module, note that the following modules depend on this module:
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +For information about module installation in Magento 2, see [Enable or disable modules](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.html).
```suggestion
For information about module enabling or disabling in Magento 2, see [Enable or disable modules](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.html).
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +    - `store_id` is a bundle product store id.
```suggestion
    - `store_id` is a bundle product store ID.
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +    - `collection` is bundle collection of selection before count prices of it (`\Magento\Bundle\Model\ResourceModel\Selection\Collection` class).
```suggestion
    - `collection` is bundle collection of selection before price calculation (`\Magento\Bundle\Model\ResourceModel\Selection\Collection` class).
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +    - `entity_field` is a entity id column (`\Zend_Db_Expr` class)
```suggestion
    - `entity_field` is a entity ID column (`\Zend_Db_Expr` class)
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +    - `website_field` is a website id column (`\Zend_Db_Expr` class)
```suggestion
    - `website_field` is a website ID column (`\Zend_Db_Expr` class)
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +    - `store_field` is a default store id column (`\Zend_Db_Expr` class)
```suggestion
    - `store_field` is a default store ID column (`\Zend_Db_Expr` class)
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +For information about an event in Magento 2, see [Events and observers](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/events-and-observers.html#events).
```suggestion
For information about the event system in Magento 2, see [Events and observers](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/events-and-observers.html#events).
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +- add a child to bundle product to specified Bundle option by the product sku or product.
```suggestion
- add a child to bundle product to specified Bundle option by the product SKU or product.
```

2020-12-17 13:00 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +- get all children for Bundle product.
Please, consider using a lower-cased version of the "bundle" product everywhere (you use both versions)
```suggestion
- get all children for bundle product.
```

2020-12-17 15:49 UTC, korovitskyi commented
Hi @rogyar.
Thanks for review.
Changes was added.

2020-12-23 15:37 UTC, sidolov commented
@magento combine 31307 31324 31328 31335 31338 31421 31426 31429 31434

2020-12-23 15:37 UTC, magento-engcom-team commented
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

2020-12-23 15:46 UTC, sidolov commented
@magento combine 31307 31324 31328 31335 31338 31421 31426 31429 31434

2020-12-23 15:46 UTC, magento-engcom-team commented
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

2020-12-23 15:47 UTC, magento-engcom-team commented
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/31307 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31324 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31328 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31335 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31338 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31421 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31426 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31429 : Pull Request state must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/31434 : Pull Request state must be the same for target and source pull request

2020-12-23 15:48 UTC, sidolov commented
@magento combine 31307 31324 31328 31335

2020-12-23 15:48 UTC, magento-engcom-team commented
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

2020-12-23 15:51 UTC, sidolov commented
@magento combine 31307

2020-12-23 15:51 UTC, magento-engcom-team commented
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

2020-12-23 15:56 UTC, magento-engcom-team commented
Hi @korovitskyi
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/31307 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

2020-12-23 15:59 UTC, sidolov commented
@korovitskyi could you please merge all PRs related to the changes to readme.md files to one PR? 
https://github.com/magento/magento2/pull/31324
https://github.com/magento/magento2/pull/31328
https://github.com/magento/magento2/pull/31335
https://github.com/magento/magento2/pull/31338
https://github.com/magento/magento2/pull/31421
https://github.com/magento/magento2/pull/31426
https://github.com/magento/magento2/pull/31429
https://github.com/magento/magento2/pull/31434
https://github.com/magento/magento2/pull/31307

2020-12-24 09:37 UTC, korovitskyi commented
@sidolov this PR was updated.

2020-12-28 08:52 UTC, engcom-Charlie commented
@magento run all tests

2021-01-11 14:20 UTC, dobooth requested changes
Hi @korovitskyi  Thanks for these updates. We don't bold the module names in docs. Please remove the bolding.

2021-01-13 08:59 UTC, korovitskyi commented
Hi, @dobooth.
Thanks for the review.
Changes were added.

2021-01-13 09:11 UTC, engcom-Charlie commented
@magento run all tests

2021-01-13 10:41 UTC, rogyar requested changes
Hi @korovitskyi. Just a couple of minor suggestions and we are good to go. 

Thanks!

2021-01-13 10:41 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +`Pricing/` - the directory that contain solutions for bundle product price.
```suggestion
`Pricing/` - the directory that contains solutions for the bundle product price.
```

2021-01-13 10:41 UTC, rogyar commented on app/code/Magento/Bundle/README.md
> +    - `product` - a product with set final price (`\Magento\Catalog\Model\Product` class).
```suggestion
    - `product` - a product with the final price set (`\Magento\Catalog\Model\Product` class).
```

2021-01-13 10:53 UTC, korovitskyi commented
Hi, @yagator. 
Thanks for the review. 
Changes were added.

2021-08-02 08:14 UTC, ihor-sviziev commented
@rogyar, could you review?

2021-10-13 20:43 UTC, sidolov commented
@korovitskyi I'm closing the PR since the source code is not available.

2021-10-13 20:43 UTC, closed without merging