Update Magento_BundleImportExport ReadMe
magento/magento2 pull request #31324
Opened 2020-12-17 16:11 UTC by korovitskyi

### Description (*)

Update README.md file for Magento_BundleImportExport module.

### Fixed Issues (if relevant)

1. magento/devdocs magento/devdocs#4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-18 08:15 UTC, swnsma requested changes
Hi @korovitskyi!
Thank you for your contribution!
Please check my notices.

2020-12-18 08:15 UTC, swnsma commented on app/code/Magento/BundleImportExport/README.md
> +**Magento_BundleImportExport** module enables you to implements bundle products import/export functionality.
```suggestion
**Magento_BundleImportExport** module enables you to operate import/export functionality with bundle products.
```

2020-12-18 08:15 UTC, swnsma commented on app/code/Magento/BundleImportExport/README.md
> +This module is designed to extend existing functionality of **Magento_CatalogImportExport** module by adding new product type.
```suggestion
This module is designed to extend the existing functionality of the **Magento_CatalogImportExport** module by adding a new product type.
```

2020-12-18 08:15 UTC, swnsma commented on app/code/Magento/BundleImportExport/README.md
> +Before disabling or uninstalling this module, note that the following modules depend on this module:
```suggestion
Before disabling or uninstalling this module, please consider the following dependencies:
```

2020-12-18 08:15 UTC, swnsma commented on app/code/Magento/BundleImportExport/README.md
> +Extension developers can interact with the Magento_CatalogImportExport module. For more information about the Magento extension mechanism, see [Magento plug-ins](http://devdocs.magento.com/guides/v2.
```suggestion
Extension developers can interact with the Magento_CatalogImportExport module. For more information about the Magento 2 extension mechanism, see [Magento plugins](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html).
```

2020-12-18 08:15 UTC, swnsma commented on app/code/Magento/BundleImportExport/README.md
> +[The Magento dependency injection mechanism](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/depend-inj.html) enables you to override the functionality of the Magento_CatalogImportExport m
```suggestion
[The Magento 2 dependency injection mechanism](http://devdocs.magento.com/guides/v2.4/extension-dev-guide/depend-inj.html) allows you to override the functionality of the Magento_CatalogImportExport module.
```

2020-12-18 08:15 UTC, swnsma commented on app/code/Magento/BundleImportExport/README.md
> +For information about enabling or disabling a module in Magento 2, see [Enable or disable modules](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.html)
```suggestion
Please find here [how to enable or disable modules in Magento 2](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-enable.html).
```

2020-12-18 08:29 UTC, korovitskyi commented
Hi, @swnsma !
Thanks for review.
Changes was added.

2020-12-18 10:45 UTC, swnsma approved these changes

2020-12-18 11:02 UTC, engcom-Delta commented
**Note:** QA not applicable

2020-12-18 12:18 UTC, engcom-Delta commented
@magento run all tests

2020-12-18 14:48 UTC, engcom-Delta commented
**Note:** Functional Tests B2B are failed

2020-12-20 02:18 UTC, orlangur requested changes
Nice @korovitskyi! After changes are applied, please squash the commits.

2020-12-20 02:18 UTC, orlangur commented on app/code/Magento/BundleImportExport/README.md
> +**Magento_BundleImportExport** module enables you to operate implements bundle products import/export functionality with bundle products.
"to operate implements" sounds awkward, as I see it was recommended to replace "implements" word with "operate"

2020-12-20 02:18 UTC, orlangur commented on app/code/Magento/BundleImportExport/README.md
> +This module is designed to extend the existing functionality of the **Magento_CatalogImportExport** module by adding a new product type.
"by supporting a bundle product type" maybe?

2020-12-20 02:18 UTC, orlangur commented on app/code/Magento/BundleImportExport/README.md
> +Extension developers can interact with the Magento_CatalogImportExport module. For more information about the Magento 2 extension mechanism, see [Magento plugins](https://devdocs.magento.com/guides/v
Wrong module copy-paste error

2020-12-20 02:18 UTC, orlangur commented on app/code/Magento/BundleImportExport/README.md
> +[The Magento dependency injection mechanism](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/depend-inj.html) enables you to override the functionality of the Magento_CatalogImportExport
Wrong module copy-paste error again

2020-12-21 08:39 UTC, engcom-Charlie commented
@magento run all tests

2020-12-23 15:39 UTC, magento-engcom-team commented
Hi @korovitskyi
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/31304 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

2020-12-23 15:50 UTC, magento-engcom-team commented
Hi @korovitskyi
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/31304 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

2020-12-24 09:43 UTC, closed without merging