magento/magento2#31206: Selected shipping method does not contain val…
magento/magento2 pull request #31322
Opened 2020-12-17 15:20 UTC by sasha19957099

### Description (*)
Added values to GraphQL schema price_excl_tax price_incl_tax for Selected shipping method 

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/31206

### Manual testing scenarios (*)
1.Enable the shipping method flatrate and set its price to 10
2. Configure a default tax class for shipping that's not 0%. My example is 21%
3. Set tax/calculation/shipping_includes_tax to "Including Tax"
4. Set tax/cart_display/shipping to "Including Tax"
5. Set tax/display/shipping to "Including Tax"
6. Create a Cart through GraphQl
7.Add a product to your cart through GraphQl
8.Set a Shipping Address on your cart through GraphQl
9. Set flatrate/flatrate as your shipping method through GraphQl using the following query.

mutation setShippingMethodsOnCart($cartId: String!) {
  setShippingMethodsOnCart(input: {cart_id: $cartId, shipping_methods: [{carrier_code: "flatrate", method_code: "flatrate"}]}) {
    cart {
      shipping_addresses {
        selected_shipping_method {
          amount {
            currency
            value
          }
          price_excl_tax {
            currency
            value
          }
          price_incl_tax {
            currency
            value
          }
        }
        available_shipping_methods{
          amount {
            currency
            value
          }
          price_excl_tax {
            currency
            value
          }
          price_incl_tax {
            currency
            value
          }
        }
      }
    }
  }
}

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-17 15:22 UTC, sasha19957099 commented
@magento run all tests

2021-03-12 07:59 UTC, victorchiriac89 commented
Any news over this, when will it be included?

2021-04-26 17:02 UTC, cpartica approved these changes

2021-04-26 19:56 UTC, cpartica commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
>      amount: Money!
here amount should be deprecated

2021-04-26 21:15 UTC, cpartica commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
>      amount: Money!
amount should either be removed or renamed to display_price

2021-04-26 21:18 UTC, cpartica approved these changes

2021-04-26 21:18 UTC, cpartica commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    price_excl_tax: Money!
amount and prices can't be used interchangeably
amount should either be removed or renamed to display_price
or price should be change to amount resulting in
amount_excl_tax: Money!
amount__incl_tax: Money!

2021-08-04 05:42 UTC, mzeis commented
@cpartica Will this be fixed in 2.4.3? Thank you!

2021-09-15 08:53 UTC, sasha19957099 commented
@magento run Functional Tests B2B

2021-11-24 10:38 UTC, engcom-Alfa requested changes
Hi @sasha19957099 Thanks for your contribution and collaboration!
As I have checked the issue, it is reproducible in 2.4-develop.
There are Merge conflicts in this PR request, in order to process it further the conflicts should be resolved. Kindly resolve it and re update please!

2021-12-10 10:59 UTC, engcom-Lima commented
@magento run all tests

2021-12-10 13:01 UTC, engcom-Lima commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,Static Tests

2021-12-10 15:21 UTC, engcom-Lima commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,Static Tests

2021-12-14 07:00 UTC, engcom-Lima commented
@magento rull all tests

2021-12-14 07:01 UTC, engcom-Lima commented
@magento run all tests

2021-12-14 12:33 UTC, engcom-Lima commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,Static Tests

2021-12-14 13:05 UTC, engcom-Lima commented
@magento run all tests

2021-12-16 06:03 UTC, engcom-Lima commented
@magento run all tests

2021-12-16 09:11 UTC, engcom-Lima commented
@magento run Functional Tests B2B,Functional Tests CE,Integration Tests

2021-12-16 10:59 UTC, engcom-Lima commented
@magento run Functional Tests B2B,Integration Tests

2021-12-16 13:55 UTC, engcom-Lima commented
@magento run Integration Tests

2021-12-16 16:05 UTC, engcom-Lima commented
@magento run Integration Tests

2021-12-17 04:52 UTC, engcom-Lima commented
@magento run Integration Tests

2021-12-17 09:11 UTC, engcom-Lima commented
Hi @cpartica, after resolving the conflicts and running the latest build there were some static failures which were addressed.
Can you please review the changes again?
Thanks

2022-04-25 15:49 UTC, ishakhsuvarov approved these changes

2022-04-26 09:52 UTC, engcom-Alfa commented
@magento run all tests

2022-04-26 12:39 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2022-04-26 15:03 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2022-04-27 06:04 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE

2022-04-27 11:17 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE

2022-04-27 12:29 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

This PR was requested for changes as per the[ above comment](https://github.com/magento/magento2/pull/31322#pullrequestreview-814709478), and the fix has already covered with GraphQL auto-test case.
Hence no further QA investigation required and hence moving it ahead!

2022-05-05 11:01 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2022-05-06 10:04 UTC, engcom-Charlie commented
As the build is green now and as per this [comment](https://github.com/magento/magento2/pull/31322#issuecomment-1110942520) PR is QA passed so moving it to Merge in Progress.

Thank you!

2022-06-11 14:22 UTC, merged