Fix issue with logging each cookie as separate context
magento/magento2 pull request #31334
Opened 2020-12-18 08:47 UTC by aleksinoleg

### Description (*)
When the number of cookies becomes more than 50 the warning log is written: "Unable to send the cookie. Maximum number of cookies would be exceeded." And each cookie is converting to a separate log context. And in the case of using the Graylog app, it is converting to a separate field.
By this pull request, the $_COOKIE array is converting to a string and writing as 'cookie' context while writing the log

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

1. Exceed the number of cookies > 50
2. Watch the log

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-18 08:49 UTC, aleksinoleg commented
This PR is https://github.com/magento/magento2/pull/31259 variant for 2.4

2020-12-18 08:52 UTC, ihor-sviziev commented
@magento run all tests

2020-12-18 09:13 UTC, ihor-sviziev requested changes

2020-12-18 09:13 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php
> +                )
We don't really need to have array_merge here. Could you remove it?

2020-12-18 10:07 UTC, ihor-sviziev commented
@magento run all tests

2020-12-18 10:08 UTC, ihor-sviziev commented
Finally, someone will fix that! 👍

We also were having this issue - we're sending logs to some Elasticsearch based tool, and it was hunting because of too many fields (each key is sent as a separate key). Also, it doesn't have any value for sending all cookies as separate values, so PR, in general, looks good to me.

2020-12-18 12:39 UTC, ihor-sviziev approved these changes

2020-12-21 16:28 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8557](https://jira.corp.magento.com/browse/ENGCOM-8557) has been created to process this Pull Request

2020-12-28 09:50 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario 
1. Open web browser Firefox
2. Navigate to `about:config`
3. Find `dom.storage.enabled` option and change to _false_
4. Open Storefront in a new tab
5. Duplicate the tab, open the same page in another tab
6. Duplicate the tabs several times (3-4 new tabs)
7. Open `debug.log`  file from _./var/log_ folder 
8. Find the text _"main.WARNING: Unable to send the cookie. Maximum number of cookies would be exceeded"_

**BEFORE** switching to the PR
![unable_to send_coockie](https://user-images.githubusercontent.com/51680745/103205422-330a3000-4902-11eb-8ba3-7c1300530733.png)

**AFTER** applying changes from the PR,
![unable_to send_coockie_after](https://user-images.githubusercontent.com/51680745/103205586-8f6d4f80-4902-11eb-8af9-df681af63bef.png)

2020-12-28 09:52 UTC, engcom-Bravo commented
@magento create an issue

2020-12-28 09:54 UTC, engcom-Bravo commented
@magento create issue

2021-01-06 17:32 UTC, merged