Updated dependency for php8 update
magento/magento2 pull request #31383
Opened 2020-12-22 03:55 UTC by konarshankar07

### Description (*)

This PR will update the packages related to php8 compatibility

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31347
2. Fixes magento/magento2#31346
3. Fixes magento/magento2#31345
4. Fixes magento/magento2#31344
5. Fixes magento/magento2#31343
6. Fixes magento/magento2#31342
7. Fixes magento/magento2#31341
8. Fixes magento/magento2#31340

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-04 10:26 UTC, sivaschenko commented
@magento run all tests

2021-01-04 10:37 UTC, coderimus requested changes
Hello @konarshankar07 
Thank you for the work you have done in the scope of the PHP8 compatibility. 👍

Please, take a look at my comment about the `minimum-stability`.

2021-01-04 10:37 UTC, coderimus commented on composer.json
> +    "minimum-stability": "dev"
We must avoid using the dev as a `minimum-stability`. Please, change.

2021-01-04 11:04 UTC, sivaschenko requested changes
Thanks for the pull request @konarshankar07 ! Can you please take a look at my comment

2021-01-04 11:04 UTC, sivaschenko commented on composer.json
> +    "minimum-stability": "dev"
I don't think the minimum stability should be dropped to dev. Is that required for some reason?

2021-01-04 15:17 UTC, sivaschenko commented
@magento run all tests

2021-01-04 16:44 UTC, konarshankar07 commented
Hello @sivaschenko  @coderimus 
Minimum stability is set to dev for the elasticsearch/elasticsearch update 
Thanks

2021-01-04 17:22 UTC, sivaschenko commented
@konarshankar07 I see, elasticsearch 7.11 is not yet published. Let's update the elasticsearch version later, when 7.11 will be available on packagist https://packagist.org/packages/elasticsearch/elasticsearch to keep all the dependencies stable.

2021-01-05 04:41 UTC, konarshankar07 commented
@sivaschenko 
Should we downgrade the elasticsearch for now or we need to wait for the release?

2021-01-05 06:52 UTC, coderimus commented
@konarshankar07 in our case we have to not to have any dev stability packages and taken into account the next 2 aspects we need to downgrade it to the stable one:
- 7.11 release will not be soon and, possibly, during this time we will have other packages updated and, maybe, new conflicts, so it is better to have PHP8 compatible system now :) to unblock Magento 3rd party vendors to upgrade their packages if needed.
- I think that the upgrade of the ES should be another complex task because ES is one of the critical packages which is responsible for data. It will need not only to upgrade version but also revied from the security perspective.
cc @sivaschenko

2021-01-05 07:17 UTC, konarshankar07 commented
@coderimus 
Thanks for the response. What do you suggest to move forward with this PR?

2021-01-05 13:33 UTC, sivaschenko requested changes
Hi @konarshankar07 , please see a summary of changes required for the PR to move forward

2021-01-05 13:33 UTC, sivaschenko commented on composer.json
> +        "elasticsearch/elasticsearch": "~7.11.0",
Let's revert the elasticsearch version change

2021-01-05 13:33 UTC, sivaschenko commented on composer.json
> +    "minimum-stability": "dev"
this line should be removed

2021-01-06 04:52 UTC, konarshankar07 commented
@sivaschenko 
Thanks for the suggestion and I have reverted the elasticsearch update and removed the minimum stability.

2021-01-06 04:52 UTC, konarshankar07 commented
@magento run all tests

2021-01-06 07:58 UTC, coderimus commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Sample Data Tests CE , Static Tests, Unit Tests, WebAPI Tests

2021-01-06 09:32 UTC, coderimus commented
@sivaschenko @konarshankar07 I have things to discuss:

1. I think we have to have PHP 8 instead of PHP 7.4 on our test builds. And we have to modify the composer `required section`: "php": "~7.3.0||~7.4.0|| ~8.0.0", 

![image](https://user-images.githubusercontent.com/5318512/103752740-c59d8400-5012-11eb-80c1-6b66d7c8dd55.png)


2. I think we should raise a discussion about having the `laminas/laminas-code` 4.x.x in our project instead of the 3.x.x. From my perspective, having the 4.x.x is better because:
- 4.x.x will have support for all new PHP8 features
- It has PHP 7.4 as minimum supported version
- of course fixes and improvements according to the CHANGE.log
- having major version is good for future releases

This 4.0.0 version has some BC breaks and I think that they will not affect us or if so we will fix them :)

What do you think?

2021-01-06 10:22 UTC, konarshankar07 commented
Hello @coderimus 
yes, I agree with you but it should be covered in different PR and its part of https://github.com/magento/magento2/issues/31081 issue

2021-01-06 13:30 UTC, coderimus commented
@konarshankar07 thank you for details and link PHP 8 upgrade issue 👍 Now I have a more clear vision of the whole process.

From my perspective, the PHP 8 version set to the required section of the composer.json should be done in the scope of this issue because without it we are not able to say that updated versions, Magento core code and 3rd party vendors included to the package are really compatible. Because here the PHP version is a conductor and dependencies are followers. Also, the `laminas/laminas-code` has a new version with fixes, updates for the PHP 8 which makes having 3.x.x version is not required, as for me.

I can suggest next:
- set PHP 8 requirement to the composer.json
- check result
- update `laminas/laminas-code` to the 4.x.x (fix BIC things)
- update all other libraries if not done in step 2

With this flow, I think, we will have PHP 8 compatibility upgrade consistently. Otherwise, we provide not the php8 dependency upgrade but the simple dependency upgrade :)

What do you think about this?

2021-01-06 13:38 UTC, sivaschenko commented
Hi @coderimus @konarshankar07

We will not be able to run tests on PHP 8 until all dependencies are updated. Let's do this step by step.
I think it would be better to update laminas components to the minimal version compatible with PHP 8 in the scope of PHP 8 compatibility project, to avoid additional work and BIC.

2021-01-06 13:45 UTC, coderimus commented
Hi @sivaschenko @konarshankar07 

@sivaschenko thank you for the update strategy explanation. Got your point and agreed with it. Let's proceed as you suggested.

2021-01-06 13:52 UTC, sivaschenko commented
@konarshankar07 can you please check if the failed tests can be fixed.

I.e. it looks like lib/internal/Magento/Framework/composer.json should be updated as well to fix static tests

2021-01-07 05:34 UTC, konarshankar07 commented
@magento run all tests

2021-01-10 13:51 UTC, konarshankar07 commented
@magento run all tests

2021-01-19 06:12 UTC, konarshankar07 commented
@magento run all tests

2021-01-27 07:27 UTC, coderimus commented
@magento run all tests

2021-01-29 07:00 UTC, konarshankar07 commented
@magento run all tests

2021-01-29 14:12 UTC, konarshankar07 commented
@magento run Static Tests

2021-02-08 03:30 UTC, konarshankar07 commented
@magento run all tests

2021-02-08 13:32 UTC, konarshankar07 commented
@magento run all tests

2021-02-09 05:06 UTC, konarshankar07 commented
@magento run all tests

2021-02-17 06:42 UTC, closed without merging