Fix wrong render script string cookie
magento/magento2 pull request #31386
Opened 2020-12-22 08:37 UTC by mrtuvn

### Description (*)

Correct mistake in core

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31385

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-22 11:43 UTC, mrtuvn commented
@magento run all tests

2020-12-22 13:46 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2020-12-22 13:47 UTC, ihor-sviziev commented
Seems like MHI failure is false positive

2020-12-22 14:09 UTC, ihor-sviziev requested changes
Could you cover your changes with any kind of automated test?

2020-12-23 03:12 UTC, mrtuvn commented
@magento give me 2.4-develop instance

2020-12-23 05:57 UTC, mrtuvn commented
@magento run all tests

2020-12-23 06:01 UTC, mrtuvn commented
@magento run all tests

2020-12-23 09:05 UTC, mrtuvn commented
@magento run Semantic Version Checker, Magento Health Index, Integration Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

2020-12-23 12:55 UTC, bubasuma commented
Hi @mrtuvn,
This issue was fixed in 2.4.2 and is not reproducible in 2.4-develop.
Please refer to commit https://github.com/magento/magento2/commit/d04e4d505aced753aedadf1f3593ef5420825857

2020-12-23 12:58 UTC, mrtuvn commented
Hmm seem it's not work when i check in latest code branch

2020-12-23 13:21 UTC, bubasuma reviewed
@mrtuvn 
It's strange. I cannot reproduce it in 2.4-develop.

2020-12-23 13:21 UTC, bubasuma commented on app/code/Magento/Cookie/Test/Mftf/Test/StorefrontVerifyUnsecureCookieTest.xml
> +            <magentoCLI command="config:set web/unsecure/base_url https://{$hostname}/" stepKey="setUnsecureBaseURL"/>
Please pay attention to the description of the test case. it says "Verify that cookie are not secure on storefront over **http**". Please add another test if you want to cover different scenario. As I see you probably want to test the scenario when https is configured but use_in_frontend is set 0.

2020-12-23 13:21 UTC, bubasuma commented on app/code/Magento/Cookie/Test/Mftf/Test/StorefrontVerifySecureCookieTest.xml
> -            <magentoCLI command="config:set web/unsecure/base_url http://{$hostname}/" stepKey="setUnsecureBaseURL"/>
could you please explain why you removed these steps? aren't they suppose to revert the settings set in the "before" tag?

2020-12-23 13:48 UTC, mrtuvn commented
I will revert change in mftf and find another way for this scenario

2020-12-23 15:37 UTC, ihor-sviziev commented
@mrtuvn seems like @bubasuma mean that this issue was already fixed in 2.4-develop. Could you check that?

2020-12-23 16:04 UTC, mrtuvn commented
When try again one more i can't  reproduce problem in 2.4-develop branch so i will close this!

2020-12-23 16:04 UTC, closed without merging