[MFTF] Updating with AdminFilterTaxRateByCodeActionGroup
magento/magento2 pull request #31454
Opened 2020-12-24 13:15 UTC by AnnaAPak

### Description (*)
Tests have been updated with AdminFilterTaxRateByCodeActionGroup

2020-12-24 13:16 UTC, AnnaAPak commented
magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2020-12-24 13:16 UTC, AnnaAPak commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2020-12-24 14:06 UTC, AnnaAPak commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2020-12-24 14:12 UTC, AnnaAPak commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2021-01-04 08:22 UTC, eduard13 commented
@magento run all tests

2021-01-04 09:20 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/UpdateLargeTaxRateEntityTest.xml
> -        <click selector="{{AdminTaxRateGridSection.search}}" stepKey="clickSearch2"/>
We should preserve the `clickSearch2` reference.

2021-01-04 10:35 UTC, AnnaAPak commented
@magento run all tests

2021-01-04 19:47 UTC, eduard13 approved these changes
The failing tests aren't related to these changes.

2021-01-04 19:49 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8594](https://jira.corp.magento.com/browse/ENGCOM-8594) has been created to process this Pull Request

2021-01-05 07:02 UTC, engcom-Alfa commented
QA not applicable

2021-01-05 14:16 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-15 10:23 UTC, gabrieldagama requested changes
Hi @AnnaAPak, can you have a look at the conflicts? Thank you!

2021-01-17 21:05 UTC, AnnaAPak commented
@magento run all tests

2021-01-21 10:50 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-21 22:11 UTC, engcom-Foxtrot commented
@magento run all tests

2021-01-22 07:53 UTC, eduard13 commented
@magento run Functional Tests B2B , Functional Tests CE, Functional Tests EE

2021-01-22 14:14 UTC, eduard13 approved these changes
The failed tests don't seem to be related with the failed functional tests

2021-01-22 14:16 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8594](https://jira.corp.magento.com/browse/ENGCOM-8594) has been created to process this Pull Request

2021-02-05 13:49 UTC, merged