Adding AdminClearFiltersOnGridActionGroup
magento/magento2 pull request #31452
Opened 2020-12-24 11:37 UTC by AnnaAPak

### Description (*)
Adding AdminClearFiltersOnGridActionGroup

2020-12-24 11:38 UTC, AnnaAPak commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2021-01-04 08:48 UTC, eduard13 requested changes
Hi @AnnaAPak, could you please check my minor suggestions below? Please don't forget to rename the ActionGroup file name as well.

Thank you.

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Backend/Test/Mftf/ActionGroup/AdminClearFiltersOnGridActionGroup.xml
> +    <actionGroup name="AdminClearFiltersOnGridActionGroup">
I'd rename it like this. What do you think?
```suggestion
    <actionGroup name="AdminClearGridFiltersActionGroup">
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminUpdateTopCategoryUrlWithNoRedirectTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickOnResetButton1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickOnResetButton1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminUpdateTopCategoryUrlWithRedirectTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickOnResetButton1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickOnResetButton1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Email/Test/Mftf/Test/AdminEmailTemplatePreviewTest.xml
> +            <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clearFilters"/>
```suggestion
            <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clearFilters"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Email/Test/Mftf/Test/AdminEmailTemplatePreviewWithDirectivesTest.xml
> +            <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clearFilters"/>
```suggestion
            <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clearFilters"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateDefaultsTaxRuleTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRateAllPostCodesTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRateAllPostCodesTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRateLargeRateTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRateSpecificPostcodeTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRateWiderZipCodeRangeTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRateZipCodeRangeTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRuleWithCustomerAndProductTaxClassTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRuleWithNewAndExistingTaxRateAndCustomerAndProductTaxClassTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRuleWithNewTaxClassesAndTaxRateTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminCreateTaxRuleWithZipRangeTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminDeleteTaxRuleTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminDeleteTaxRuleTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminUpdateDefaultTaxRuleTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminUpdateDefaultTaxRuleTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminUpdateTaxRuleWithCustomClassesTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminUpdateTaxRuleWithCustomClassesTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminUpdateTaxRuleWithFixedZipUtahTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/AdminUpdateTaxRuleWithFixedZipUtahTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/DeleteTaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/Update01TaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/Update01TaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/Update100TaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/Update100TaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/Update1299TaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/Update1299TaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/UpdateAnyRegionTaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/UpdateAnyRegionTaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/> 
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/UpdateDecimalTaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/UpdateDecimalTaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/UpdateLargeTaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters1"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters1"/>
```

2021-01-04 08:48 UTC, eduard13 commented on app/code/Magento/Tax/Test/Mftf/Test/UpdateLargeTaxRateEntityTest.xml
> +        <actionGroup ref="AdminClearFiltersOnGridActionGroup" stepKey="clickClearFilters2"/>
```suggestion
        <actionGroup ref="AdminClearGridFiltersActionGroup" stepKey="clickClearFilters2"/>
```

2021-01-04 10:49 UTC, AnnaAPak commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2021-01-04 15:23 UTC, AnnaAPak commented
@magento run Functional Tests CE

2021-01-05 07:23 UTC, eduard13 commented
@magento run all tests

2021-01-06 07:56 UTC, eduard13 approved these changes

2021-01-06 07:57 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8604](https://jira.corp.magento.com/browse/ENGCOM-8604) has been created to process this Pull Request

2021-01-06 08:56 UTC, engcom-Alfa commented
QA not applicable

2021-01-13 08:26 UTC, engcom-Charlie commented
@magento create issue

2021-01-14 13:33 UTC, merged