Fixed conflicting styles for product image container in different listings at the same page
magento/magento2 pull request #31473
Opened 2020-12-28 11:33 UTC by tangar76

### Description (*)

This pull requests solves problem when there are two product listing blocks on the same page. Both blocks have at list one common product. And listings have different image sizes for product image.

### Related Pull Requests

Can't find related pull requests.

### Fixed Issues (if relevant)

Can't find related issue.

### Manual testing scenarios (*)

1. Open product "Crown Summit Backpack" (SKU 24-MB03) to assign up-sell products. Add at list one up-sell product. One of the assigned products must be "Fusion Backpack" (SKU 24-MB02). Save changes.
2. Create widget "Catalog Product List" via Magento Admin. Assign widget to store view you test. Layout updates settings: display on "Specified page"; page "Catalog Product View"; container "Main Content Top". Widget Options - select at least two product via SKU. One of products must be "Fusion Backpack" (SKU 24-MB02). Save widget.
3. Clear Magento 2 cache.
4. Open product page for "Crown Summit Backpack" (SKU 24-MB03) at store front.

![image](https://user-images.githubusercontent.com/13131588/103211368-af0b7480-4910-11eb-9169-a37f163e40ca.png)

With old code you can see that "Fusion Backpack" has smaller image than it should.

This pull request fixes it.  "Fusion Backpack" will get same size as "Affirm Water Bottle".

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-04 18:40 UTC, sidolov commented
@magento create issue

2021-01-05 10:44 UTC, gabrieldagama commented
@magento run all tests

2021-01-05 10:52 UTC, gabrieldagama requested changes
Hi @tangar76, thanks for your contribution! Can you have a look at my comment below?

Also, we must cover all changes with automated tests, probably the most suitable here would be MFTF test.

Thanks!

2021-01-05 10:52 UTC, gabrieldagama commented on app/code/Magento/Catalog/view/frontend/templates/product/image_with_borders.phtml
> +$containerId = uniqid($block->getProductId());
I believe we should create a function on `Magento\Catalog\Block\Product\Image` to generate the containerId instead of adding it to template.

2021-01-08 11:46 UTC, engcom-Charlie commented
Hello @tangar76, Could you please look at https://github.com/magento/magento2/pull/31473#discussion_r551856974?
Thank you.

2021-01-11 12:16 UTC, engcom-Charlie commented
Hello @tangar76, please look at https://github.com/magento/magento2/pull/31473#discussion_r551856974. Otherwise, we can't proceed with your PR.
Thank you.

2021-01-11 14:16 UTC, tangar76 commented
@engcom-Charlie container id logic moved from template to block

2021-01-14 14:01 UTC, gabrieldagama commented
@magento run all tests

2021-01-14 14:07 UTC, gabrieldagama commented
@magento run all tests

2021-01-14 14:07 UTC, gabrieldagama requested changes
Hi @tangar76, thanks for moving the logic to the block, can you have a look at my comment below? Also, can you cover these changes with automated tests? MFTF may be suitable here!

Thanks!

2021-01-14 14:07 UTC, gabrieldagama commented on app/code/Magento/Catalog/Block/Product/Image.php
> +    public function getContainerId()
Please add the return type string to the function signature.

2021-01-18 07:50 UTC, tangar76 commented
@gabrieldagama , I've added type return type for method getContainerId in product image renderer block.

Unfortunately this pull request has to be postponed. I can't cover it with MFTF test anytime soon. I will return to it in near future.

2021-01-19 14:28 UTC, gabrieldagama commented
@tangar76 No worries, thanks for contributing!

@engcom-Charlie can you help handle the test coverage on this one?

Thanks!

2021-01-21 10:13 UTC, engcom-Charlie commented
@tangar76 @gabrieldagama  I'll take care of the test coverage.

2021-01-21 11:01 UTC, engcom-Charlie commented
@magento run all tests

2021-01-21 15:29 UTC, engcom-Charlie commented
@magento run all tests

2021-01-21 18:58 UTC, engcom-Charlie commented
@magento run all tests

2021-01-25 15:00 UTC, engcom-Charlie commented
@magento run all tests

2021-02-18 14:36 UTC, gabrieldagama approved these changes

2021-02-18 14:37 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8786](https://jira.corp.magento.com/browse/ENGCOM-8786) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-02-18 14:37 UTC, magento-engcom-team commented
@tangar76 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2021-02-19 12:08 UTC, engcom-Bravo commented
:heavy_check_mark: QA PAssed

### Manual Testing Scenario
1. Install Sample Data
2. From Admin Panel, Go to _Catalog - Products_ and open product "Crown Summit Backpack" (SKU 24-MB03) 
3. Expand **Related Products, Up-Sells, and Cross-Sells** and add several _Up-Sell Products_ using **Add Up-Sell Products**.
One of the assigned products must be "Fusion Backpack" (SKU 24-MB02).
![crown_uppsell](https://user-images.githubusercontent.com/51680745/108501083-68efe300-72b9-11eb-9dc1-387ed7ae9f6c.png)
4. Go to _Content - Widgets_ and click **Add Widget**
5. Set the following settings:
- Catalog Product List 
- Assign widget to store view 
- Layout updates settings: 
     - display on "Specified page"; 
     - page "Catalog Product View"; 
     - container "Main Content Top".
5. Switch to _Widget Options_ and set **Condition** _SKU  **is one of**  24-MB02,24-UG06_
![widget_condition](https://user-images.githubusercontent.com/51680745/108501974-bae53880-72ba-11eb-92a0-feb14aa7c7ee.png)
6. **Save** Widget, perform `bin/magento indexer:reindex; bin/magento cache:clean`
7. Go to Storefront and open the "Crown Summit Backpack" (SKU 24-MB03) products page

**BEFORE** applying changes provided in the PR, the product images had different sizes 
![before](https://user-images.githubusercontent.com/51680745/108502283-3fd05200-72bb-11eb-8d19-84cf5c79340e.png)

**AFTER** switching to the PR, the product images have the same sizes
![after](https://user-images.githubusercontent.com/51680745/108502344-55de1280-72bb-11eb-8ec7-89e9c6ef71b9.png)

Added more than two products
![multiple](https://user-images.githubusercontent.com/51680745/108502736-ee749280-72bb-11eb-9acb-38f5ba3ac2ab.png)

2021-02-22 11:14 UTC, engcom-Charlie commented
Moved in `To Approve` since **SVC** falls with error:
the public method has been added to `Magento\Catalog\Block\Product\Image`.

2021-08-08 17:39 UTC, template-provider commented
+1
I would like to see this merged ... what is the problem?

2022-04-22 09:34 UTC, engcom-Alfa commented
@magento run all tests

2022-04-22 09:50 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have Magento latest code installed with Sample data

**Manual testing scenario:**

1. Open product "Crown Summit Backpack" (SKU 24-MB03) to assign up-sell products. Add at list one up-sell product. One of the assigned products must be "Fusion Backpack" (SKU 24-MB02). Save changes.
2. Create widget "Catalog Product List" via Magento Admin. Assign widget to store view you test. Layout updates settings: display on "Specified page"; page "Catalog Product View"; container "Main Content Top". Widget Options - Set the Condition to Weight-1. Save widget.
3. Open the Fusion Backpack's edit product page, set the product weight to 1 and save. Also pickup any other 1/2 more products and set the weight to 1.
4. Clear Magento 2 cache.
5. Open product page for "Crown Summit Backpack" at store front.

**Before:** :heavy_multiplication_x: One line description about what was happening prior
![image](https://user-images.githubusercontent.com/51679138/164682030-b48a0ffa-d1f7-4606-a898-55403ea0be0a.png)

**After:** :heavy_check_mark:  One line description about the is the outcome after fix
![image](https://user-images.githubusercontent.com/51679138/164682079-2cb9f218-c20a-47eb-9360-70d0d736458d.png)

Additionally tested by adding a couple of more products to fall under the Widget list.
Also noticed another product also affected with image size and corrected after the fix. Below are the screenshots with more products.

Before the PR fix:
![image](https://user-images.githubusercontent.com/51679138/164682478-a0495c88-2437-4abe-832f-1af947e6b374.png)

After the PR fix:
![image](https://user-images.githubusercontent.com/51679138/164682567-7afaa092-4524-4297-9620-6b852331d4ba.png)

2022-04-22 14:35 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests, Semantic Version Checker

2022-04-26 13:01 UTC, engcom-Charlie commented
@magento create issue

2022-04-26 13:12 UTC, engcom-Charlie commented
Raised internal approval request JIRA [ticket](https://jira.corp.magento.com/browse/MC-43361) for MVC test failure. Waiting for the approvals.

2022-06-22 12:39 UTC, engcom-Alfa commented
@magento run all tests

2022-06-22 12:40 UTC, engcom-Alfa commented
As we have got code updates later the QA validations, we have to re-test the scenario once. Re-considered for testing.
Will update here shortly!

2022-06-23 09:08 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker, Static Tests, WebAPI Tests

2022-06-23 11:31 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE

2022-06-23 11:32 UTC, engcom-Alfa commented
@magento run Static Tests

2022-06-23 15:43 UTC, engcom-Alfa commented
Re-retested again, and QA passed where the report remains same as mentioned in [above-comment](https://github.com/magento/magento2/pull/31473#issuecomment-1106286872).
Due to automation job failures, moving to _Extended Testing_.

2022-06-24 07:00 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker, Static Tests

2022-06-27 13:43 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker, Static Tests

2022-06-28 14:04 UTC, engcom-Charlie commented
@magento run all tests

2022-06-29 09:52 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker, Static Tests

2022-06-29 10:44 UTC, engcom-Charlie commented
@magento run all tests

2022-06-30 06:52 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker

2022-07-01 09:59 UTC, engcom-Charlie commented
In order to proceed with this PR, merged the latest code and run the build.

Gone through the build failures.

**For functional test failures:**  The tests which are failing in build are not part of this PR or not failing because of any change.  Also all the failing functional tests are working fine on local PR environment. 
![image](https://user-images.githubusercontent.com/51680850/176872771-659b0ffc-b0bb-4607-94c9-eee71c327784.png)


**For Semantic Version Checker**: As mentioned in above comment for SVC failure raised approval jira ticket. 

Until we get the approval, moving this PR in Pending Approval.

Thank you!

2022-10-21 11:58 UTC, engcom-Charlie commented
Raised new internal approval request JIRA [ticket](https://jira.corp.adobe.com/browse/AC-6876) for MVC test failure. Waiting for the approvals.

2022-11-07 09:03 UTC, engcom-Charlie commented
@magento run all tests

2023-02-25 17:57 UTC, mrtuvn commented
looks like this stale does not get enough attention

2023-02-28 05:54 UTC, engcom-Charlie commented
The remarks we got today in the approval [jira](https://jira.corp.adobe.com/browse/AC-6876) is: "The initial issue can be resolved by adding ViewModel instead of the new method. Canceling the request, the solution should be re-implemented."

As per above the approval jira is cancelled and this PR needs reimplementation. Hence moving it to Change Requested status.

Thank you!

2023-06-09 11:25 UTC, engcom-Charlie commented
To take care the Semantic version checker failure, I am  working on the new implementation with ViewModel as mentioned in above [comment](https://github.com/magento/magento2/pull/31473#issuecomment-1447624720).

Thank you!

2023-07-26 13:57 UTC, engcom-Lima commented
@magento run all tests

2023-07-27 06:02 UTC, engcom-Charlie commented
It seems that bot has moved this PR to Ready for testing hence moving it back to Changes Requested.

Thank you!

2023-08-07 05:46 UTC, engcom-Charlie commented
It seems that bot has moved this PR to Ready for testing hence moving it back to Changes Requested.

Thank you!

2023-08-09 15:18 UTC, engcom-Charlie commented
Implemented the fix for the issue using View model as request in internal approval [jira](https://github.com/magento/magento2/pull/31473#issuecomment-1447624720).

2023-08-09 15:20 UTC, engcom-Charlie commented
@magento run all tests

2023-08-10 05:50 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2023-08-10 06:44 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2023-08-10 06:45 UTC, engcom-Charlie commented
@magento give me test instance

2023-08-10 09:58 UTC, engcom-Charlie commented
@magento run all tests

2023-08-11 07:50 UTC, engcom-Charlie commented
@magento run all tests

2023-08-11 11:31 UTC, engcom-Charlie commented
@magento run all tests

2023-09-01 07:04 UTC, engcom-Charlie commented
@magento give me 2.4-develop instance

2023-09-01 10:21 UTC, engcom-Charlie commented
@magento run all tests

2023-09-04 06:07 UTC, engcom-Charlie commented
@magento run all tests

2023-09-13 13:22 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2023-09-14 13:43 UTC, engcom-Charlie commented
Hi @tangar76,

There are many failures in the build, it will be helpful if you have a look into them. Can you please check them.

Thank you!

2023-09-25 09:56 UTC, engcom-Charlie commented
Hi @tangar76,

As per above [comment](https://github.com/magento/magento2/pull/31473#issuecomment-1719481216), there are too many failures in this PR. Kindly have a look into this. Till then we are closing this PR. 

Please feel free to reopen once it get updated or let us know to reopen when you are working on it.

Thank you!

2023-09-25 09:56 UTC, closed without merging