100% Discount cart rule results in Tax invoiced #30853
magento/magento2 pull request #31556
Opened 2021-01-05 16:49 UTC by engcom-Hotel

### Description (*)
https://github.com/magento/magento2/issues/30853

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/30853

### Manual testing scenarios (*)

1. https://github.com/magento/magento2/issues/30853

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-05 16:50 UTC, engcom-Hotel commented
@magento run all tests

2021-01-06 07:13 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE

2021-01-06 09:29 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-01-06 12:21 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-01-06 16:35 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-01-08 07:23 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-01-13 10:27 UTC, gabrieldagama commented
@magento give me 2.4 instance with edition ee

2021-01-20 20:12 UTC, barryvdh commented
I've applied this fix but it's still generating Invoices with incorrect values on 2.3.6. Also with 99% discount.

2021-03-02 14:44 UTC, gabrieldagama requested changes

2021-03-02 14:44 UTC, gabrieldagama commented on app/code/Magento/Sales/Model/Order/Invoice/Total/Tax.php
> +        $invoice->setBaseGrandTotal($baseGrandTotal);
Such a solution would just work if the Tax totals is the last to run, but depending on sort order is not great, I recommend looking at `\Magento\Sales\Model\Order\Invoice\Total\Shipping` line 41 and 42, that is where the shipping cost is bein added to the grand total.

2021-03-25 13:58 UTC, engcom-Foxtrot commented
The solution should be fully reworked. The issue seems to be caused by tax, discount, and discount_tax_compensation_amount incorrect calculation.

2021-03-31 11:28 UTC, gabrieldagama commented
@magento run all tests

2021-03-31 13:30 UTC, gabrieldagama commented
@magento run WebAPI Tests, Functional Tests B2B

2021-05-04 14:19 UTC, hostep commented
Before this gets merged, please confirm that this is still needed on the latest `2.4-develop` branch, because I think it doesn't anymore: https://github.com/magento/magento2/issues/30853#issuecomment-831977096

2022-08-04 10:12 UTC, engcom-Alfa commented
Hi All, thanks for your contribution over here!

Checked the linked Github issue [#30853](https://github.com/magento/magento2/issues/30853), and it has already been fixed with the help of internal Jira ticket by the internal team.

We have the older commit links of this ticket here - https://github.com/magento/magento2/commit/533ec2eb46c91b79b7a99ba4a6a164e2f6e3d7f1

Hence, closing this PR currently.
In case of any further clarifications on this, please do comment in the same ticket.
If you feel like, require to do more changes/modifications/fixes coverage, you may report a new PR as well.

Thanks!

2022-08-04 10:12 UTC, closed without merging