Console Commands Optimization
magento/magento2 pull request #31614
Opened 2021-01-12 00:56 UTC by kirmorozov

### Description (*)

Put some resource-intensive constructors behind Proxy class.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. bin/magento
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2021-01-12 00:57 UTC, kirmorozov commented
@magento run all tests

2021-01-12 02:17 UTC, kirmorozov commented
@magento run `Functional Tests CE`,`Semantic Version Checker`

2021-01-12 03:52 UTC, kirmorozov commented
@magento run Semantic Version Checker

2021-01-12 03:53 UTC, kirmorozov commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2021-01-12 07:50 UTC, ihor-sviziev requested changes
Hi @kirmorozov,
In general, your changes look good in terms of the 2.4-develop branch. However, I have one small comment, could you review and fix it?


For the 2.5-develop branch, we already have an amazing PR https://github.com/magento/magento2/pull/29355 that is supposed to permanently fix this issue for all places at once, so such changes should be probably removed.

2021-01-12 07:50 UTC, ihor-sviziev commented on app/code/Magento/MediaStorage/etc/di.xml
> +            <argument name="appState" xsi:type="object">Magento\Framework\App\State</argument>
Should it have a Proxy suffix as well? If no - please remove it

2021-01-12 17:52 UTC, gabrieldagama commented
Hi @kirmorozov, thanks for contributing! Can you provide some extra information on execution time improvement? Ideally, we need to see the difference between your solution and vanilla Magento.

Can you provide that information?

Thanks!

2021-01-13 09:37 UTC, ihor-sviziev commented
Hi @gabrieldagama,
The idea behind this PR is not to create instances of the commands with all their dependencies (unfortunately, some classes have quite heavy constructors that that slowing down all the CLIs) until needed. That's what proxies do for us.

As I said above - the permanent fix will be implementing CLI command loader, but for 2.4.x it's not suitable https://github.com/magento/magento2/pull/29355

2021-01-14 17:18 UTC, gabrieldagama commented
Hi @ihor-sviziev, we were discussing this PR at the Public Community Triage meeting. We understand the goal with applying proxies to the commands, but as you mentioned there, it probably doesn't make sense to accept such changes now and revert them when 2.5 gets released, mostly because it will cause BiC one more time.

We decided to close this PR for now in favor of the CommandLoader implementation on #29355.

@kirmorozov Thanks for contributing!

2021-01-14 17:18 UTC, closed without merging

2021-01-14 22:54 UTC, kirmorozov commented
@gabrieldagama you are referencing something in future, that does not work now, and maybe will never work.

2021-01-19 14:42 UTC, gabrieldagama commented
Hi @kirmorozov,

Yes, you are right, the PR #29355 is aimed at `2.5` scope instead. Replacing the `CommandList` with `CommandLoader` may be a challenge but it seems a more definitive solution. What we were discussing at the Public Community Triage meeting is that bringing a temporary solution for a noncritical problem and having to revert it on the next minor release is not recommended.

Hope that makes sense, thanks again.