Graphql products query returns only ids for select or multiselect fields
magento/magento2 pull request #31622
Opened 2021-01-12 14:59 UTC by shikhamis11

### Description (*)
```
Query productDetail($url_key: String) {
  productDetail: products(filter: {url_key: {eq: $url_key}}) {
    items {
      name
      url_key
      gender
    }
  }
}
```

variables:

{
  "url_key": "dual-handle-cardio-ball"
}

Actual result (*)

the response only returns the value ids.

```
{
  "data": {
    "productDetail": {
      "items": [
        {
          "name": "Dual Handle Cardio Ball",
          "url_key": "dual-handle-cardio-ball",
          "gender": "5507,5508,5511"
        }
      ]
    }
  }
}
```
for showing additional custom attributes we have added `custom_attributes` field 
for Example 
```
{
  products(filter: { sku: { eq: "simple001" } }) {
    items {
      name
      url_key
      custom_attributes {
        code
        value
      }    
    }
  }
}
```

output will be like 

```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "simple001",
          "url_key": "simple001",
          "custom_attributes": [
            {
              "code": "color",
              "value": null
            },
            {
              "code": "manufacturer",
              "value": null
            },
            {
              "code": "test_attribute",
              "value": "t1, t2, t3"
            }
          ]
        }
      ]
    }
  }
}
```

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28200

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-12 15:00 UTC, shikhamis11 commented
@magento run all tests

2021-01-13 05:19 UTC, shikhamis11 commented
@magento run Unit Tests

2021-01-13 11:45 UTC, shikhamis11 commented
@magento run all tests

2021-02-05 19:15 UTC, hanxiangwu commented
Hi there, we are experiencing the same issue for our store, so do you guys know what is the fix? Thanks

2021-03-06 08:34 UTC, theshreyas commented
> Hi there, we are experiencing the same issue for our store, so do you guys know what is the fix? Thanks

Try this [quickfix module](https://github.com/theshreyas/magento-2-quickies/tree/main/Graphql/DynamicAttributesGraphql)

2021-03-18 16:31 UTC, gabrieldagama commented
Prioritized as P3 due to possible changes on approach, more information here: https://github.com/magento/architecture/pull/456

2021-11-05 02:18 UTC, cpartica commented
@magento run all tests

2021-11-10 14:52 UTC, shikhamis11 commented
@magento run all tests

2022-05-06 13:29 UTC, cpartica requested changes

2022-05-06 13:29 UTC, cpartica commented on app/code/Magento/CatalogGraphQl/etc/schema.graphqls
> +    custom_attributes: [CustomAttribute] @doc(description: "An array of custom product attributes.") @resolver(class: "Magento\\CatalogGraphQl\\Model\\Resolver\\Product\\CustomAttributes")
this conflicts with https://github.com/magento/magento2-pwa/blob/main/CatalogGraphQlAux/etc/schema.graphqls#L23

2022-05-23 10:58 UTC, engcom-Charlie commented
@cpartica, as you mentioned in JIRA [comment](https://jira.corp.magento.com/browse/AC-2796), that we need an approved schema for this one, and alignment with the pwa metapackage schema. This will take time and moving it to 2.4.6.

Hence moving this PR to on Hold, until the further updates on JIRA.

2022-10-21 09:08 UTC, engcom-Charlie commented
As mentioned in above [comment](https://github.com/magento/magento2/pull/31622#issuecomment-1134524247), we are doing follow up with team. We are waiting for the PO's input on the same. Once will get the clarity on that, we will proceed further on this.

Thank you!

2022-11-03 06:43 UTC, engcom-Charlie commented
As per latest updates on [JIRA](https://jira.corp.adobe.com/browse/AC-2796), internal GraphQL team will going to work on this issue in separate epic, which they will try to deliver in scope of 2.4.7. until then keeping the PR in same status.

Thank you!

2023-01-10 05:59 UTC, engcom-Charlie commented
As per above [comment](https://github.com/magento/magento2/pull/31622#issuecomment-1301703892) moving this PR On hold until it gets deliver.

Thank you!

2023-06-26 15:00 UTC, maaarghk commented
@gabrieldagama @cpartica now the next release is 2.4.7, this can be unheld?

2025-06-19 12:05 UTC, engcom-Dash commented
As mentioned in this [JIRA AC-2796](https://jira.corp.adobe.com/browse/AC-2796) the fix has been delivered. Also please find the documentaion for graphql of selecting products's custom attribute https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/#filter-custom_attributesv2-of-a-product. 

![image](https://github.com/user-attachments/assets/548637b2-aeed-40b1-8233-553aed7f83e5)

The changes done in this PR are deprecated and not needed because V2 of Custom Attributes schema got introduced.

Hence closing this PR.

2025-06-19 12:05 UTC, closed without merging