Moving array access for CAPTCHA _.isEmpty check
magento/magento2 pull request #31636
Opened 2021-01-13 14:00 UTC by MellenIO

When upgrading to 2.3.6 from 2.3.5-p2, a new CAPTCHA zone "payment_processing_request" is added.

If a customer has an existing session (from 2.3.5-p2 or prior), and tries to access checkout with their existing session data, checkout will fail to load because the check to see if `captchaData[formId]` exists is not a valid function call.
`_.isEmpty()` only returns a boolean value, so it cannot be enumerated like an array. Array access syntax has been moved in to the check, rather than outside it.

### Description (*)
This change allows a `_.isEmpty()` check in the `defaultCaptcha.js` file to complete successfully, resolving issues with the checkout failing to load or infinitely loading after upgrading.
### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A - no reported issue for this yet?

### Manual testing scenarios (*)
1. Create an instance prior to 2.3.6 (eg: 2.3.5-p2)
2. Load the /checkout route in a valid way (eg: add to basket, create an account, click "go to checkout")
3. Observe the `captcha` key of the `mage-cache-storage` local storage key. There should **not** be an entry for `payment_processing_request`
4. Upgrade to 2.3.6 or another version that **does** include the fix introduced via [MC-36200](https://github.com/magento/magento2/commit/d31085aea48f151e0359ccc3c72d3585da3e96a1)
5. Load the `/checkout` route with the same session as before
6. Observe an infinite load on the checkout page and errors in the console along the lines of:

```
defaultCaptcha.js:60 Uncaught TypeError: Cannot read property 'timestamp' of undefined
    at UiClass.checkCustomerData (defaultCaptcha.js:60)
    at UiClass.<anonymous> (defaultCaptcha.js:43)
    at Function.each (jquery.js:382)
    at UiClass.initialize (defaultCaptcha.js:38)
    at UiClass.initialize (wrapper.js:109)
    at UiClass._super (wrapper.js:106)
    at UiClass.initialize (loginCaptcha.js:21)
    at UiClass.initialize (wrapper.js:109)
    at new UiClass (class.js:49)
    at Object.initComponent (layout.js:137)
```

7. Apply patch
8. Attempt to load `/checkout` again
9. Observe checkout loads as expected

### Questions or comments
I'm not sure if an issue is needed for this PR, but happy to make one if one is needed. This will also need to be backported to 2.3.6.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-13 16:56 UTC, sidolov commented
@magento create issue

2021-01-14 12:51 UTC, ihor-sviziev commented
@MellenIO looks good but feels like a duplicate of https://github.com/magento/magento2/issues/30537 https://github.com/magento/magento2/pull/30602 that were closed due to inability to reproduce the issue. I hope this time it's reproducible.
@magento run all tests

2021-01-14 15:05 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Functional Tests EE

2021-01-14 20:29 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Functional Tests EE

2021-01-15 08:23 UTC, MellenIO commented
> @MellenIO looks good but feels like a duplicate of #30537 #30602 that were closed due to inability to reproduce the issue. I hope this time it's reproducible.

It should be reproducible as I ran in to this error when upgrading a client. #30537 sounds similar but had a different bug compared to myself, but I wonder if this is just a change between 2.4.x and 2.3.x?

2021-01-15 08:54 UTC, ihor-sviziev approved these changes

2021-01-15 08:56 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8630](https://jira.corp.magento.com/browse/ENGCOM-8630) has been created to process this Pull Request

2021-01-18 08:08 UTC, ihor-sviziev commented
Functional Tests EE

2021-01-18 08:08 UTC, ihor-sviziev commented
@magento run Functional Tests EE

2021-01-21 15:44 UTC, engcom-Delta requested changes
Hi @MellenIO  Could you clarify what issue should be fixed by PR?
When customer registers and login on frontend,  `payment_processing_request` is present in `mage-cache-storage local` storage key on 2.4-develop
![image](https://user-images.githubusercontent.com/51681379/105371125-f97cca00-5c0c-11eb-97b5-b2fb5ec40a32.png)

And there is not clear what issue is caused by typo in `captchaData)[formId]` as JS `not` operator turn undefined value of `captchaData)[formId]` into `true`
![image](https://user-images.githubusercontent.com/51681379/105372185-01893980-5c0e-11eb-88c7-170481b6c2c7.png)

Also issue https://github.com/magento/magento2/issues/30537 is reproducible on PR branch
![image](https://user-images.githubusercontent.com/51681379/105374317-3c8c6c80-5c10-11eb-92f8-cfd9e775bf5e.png)

2021-01-22 08:22 UTC, engcom-Hotel commented
@magento run Functional Tests EE

2021-01-22 08:26 UTC, MellenIO commented
@engcom-Delta did you create the customer & visit checkout on a version without the fix introduced in [MC-36200](https://github.com/magento/magento2/commit/d31085aea48f151e0359ccc3c72d3585da3e96a1)?

If you create the customer & then try to checkout in a prior version, you should have the key missing in your cache storage. What version did you initially upgrade from/to?

> And there is not clear what issue is caused by typo in captchaData)[formId] as JS not operator turn undefined value of captchaData)[formId] into true

If you don't have a key in your cache storage that Magento expects, the code will crash because `_.isEmpty(var)` will **not** return an array, but rather a boolean. From my testing in Firefox & Chrome's web consoles, doing any form of `booleanValue[arrayKey]` will give you `undefined`, which is a falsey value.

2021-01-22 12:12 UTC, engcom-Hotel commented
@magento run Functional Tests EE

2021-01-22 14:24 UTC, engcom-Hotel commented
@magento run Functional Tests EE

2021-01-22 16:55 UTC, ihor-sviziev approved these changes

2021-01-22 16:57 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8630](https://jira.corp.magento.com/browse/ENGCOM-8630) has been created to process this Pull Request

2021-01-25 18:54 UTC, engcom-Delta commented
:heavy_check_mark: QA passed
Was checked case described in [Manual testing scenarios](https://github.com/magento/magento2/pull/31636#issue-554206572)
**Result:**
**Before:**
:x: An infinite load on the checkout page and errors in the console
![Screenshot from 2021-01-25 20-17-38](https://user-images.githubusercontent.com/51681379/105750543-8ac1a880-5f4d-11eb-8ccf-355afc95f0f3.png)


**After:**
:heavy_check_mark: Checkout page is available, no errors in console
![Screenshot from 2021-01-25 20-27-57](https://user-images.githubusercontent.com/51681379/105750463-754c7e80-5f4d-11eb-818a-0203377f6d41.png)

2021-01-25 20:54 UTC, engcom-Delta commented
**Note:** Automation tests are passed

2021-02-05 13:49 UTC, merged