Magento_Cms: avoid using deprecated escape* methods from AbstractBlock
magento/magento2 pull request #31678
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 09:23 UTC, ihor-sviziev commented
@magento run all tests

2021-02-01 12:57 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Static Tests, Integration Tests

2021-02-02 07:54 UTC, ihor-sviziev requested changes

2021-02-02 07:54 UTC, ihor-sviziev commented on app/code/Magento/Cms/view/adminhtml/templates/url_filter_applier.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\Backend\Block\Template $block
 * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 07:54 UTC, ihor-sviziev commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content/uploader.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Uploader $block
 * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 07:54 UTC, ihor-sviziev commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content/files.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files $block
 * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 07:54 UTC, ihor-sviziev commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content.phtml
> +  * @var \Magento\Framework\Escaper $escaper
```suggestion
  * @var \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content $block
  * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 21:14 UTC, sergeynezbritskiy commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content.phtml
> +  * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-02 21:14 UTC, sergeynezbritskiy commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content/files.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-02 21:14 UTC, sergeynezbritskiy commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content/uploader.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-02 21:14 UTC, sergeynezbritskiy commented on app/code/Magento/Cms/view/adminhtml/templates/url_filter_applier.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-03 08:02 UTC, ihor-sviziev requested changes

2021-02-03 08:02 UTC, ihor-sviziev commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content/uploader.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Uploader $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-06 20:16 UTC, sergeynezbritskiy commented on app/code/Magento/Cms/view/adminhtml/templates/browser/content/uploader.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-07 15:52 UTC, ihor-sviziev commented
@magento run all tests

2021-02-08 08:02 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-02-08 10:04 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-02-19 11:04 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2023-02-19 20:25 UTC, closed without merging