Magento_ConfigurableProduct: avoid using deprecated escape* methods f…
magento/magento2 pull request #31676
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 09:22 UTC, ihor-sviziev commented
@magento run all tests

2021-02-02 08:05 UTC, ihor-sviziev requested changes

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/composite/fieldset/configurable.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Composite\Fieldset\Configurable $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/attributes_values.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\AttributeValues $block
 * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/bulk.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\Bulk $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/select_attributes.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\SelectAttributes $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/summary.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\Summary $block
 * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/super/config.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config $block
 * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/super/matrix.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/super/wizard.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/product/configurable/affected-attribute-set-selector/js.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\ConfigurableProduct\Block\Product\Configurable\AttributeSelector $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/base/templates/product/price/final_price.phtml
>  /** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
```suggestion
/**
 * @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel
 * @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel
 */
$priceModel = $block->getPriceType('regular_price');
```

2021-02-02 08:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/view/frontend/templates/product/view/type/options/configurable.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable $block
 * @var \Magento\Framework\Escaper $escaper
```

2021-02-02 21:17 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/frontend/templates/product/view/type/options/configurable.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-02 21:18 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/base/templates/product/price/final_price.phtml
>  /** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
fixed

2021-02-02 21:19 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/product/configurable/affected-attribute-set-selector/js.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-02 21:19 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/super/wizard.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-02 21:20 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/super/matrix.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-02 21:23 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/composite/fieldset/configurable.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-02 21:23 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/attributes_values.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-02 21:23 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/bulk.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-02 21:23 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/select_attributes.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-02 21:23 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/summary.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-02 21:23 UTC, sergeynezbritskiy commented on app/code/Magento/ConfigurableProduct/view/adminhtml/templates/catalog/product/edit/super/config.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-02-03 08:05 UTC, ihor-sviziev commented
@magento run all tests

2021-02-03 08:46 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2021-02-03 13:47 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Database Compare

2021-02-04 11:22 UTC, gabrieldagama commented
@magento run all tests

2021-02-04 11:27 UTC, gabrieldagama commented
@magento run all tests

2021-02-04 15:20 UTC, ihor-sviziev commented
@magento run Database Compare

2021-02-04 15:20 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2023-02-19 20:25 UTC, closed without merging