Magento_CheckoutAgreements: avoid using deprecated escape* methods fr…
magento/magento2 pull request #31679
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 09:23 UTC, ihor-sviziev commented
@magento run all tests

2021-02-01 12:55 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Static Tests, Semantic Version Checker, Database Compare

2021-02-02 07:54 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2021-02-02 07:56 UTC, ihor-sviziev requested changes

2021-02-02 07:56 UTC, ihor-sviziev commented on app/code/Magento/CheckoutAgreements/view/frontend/templates/multishipping_agreements.phtml
>   * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
```suggestion
/**
 * @var \Magento\CheckoutAgreements\Block\Agreements $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
```

2021-02-02 07:56 UTC, ihor-sviziev commented on app/code/Magento/CheckoutAgreements/view/frontend/templates/agreements.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\CheckoutAgreements\Block\Agreements $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-02 21:12 UTC, sergeynezbritskiy commented
Hi @ihor-sviziev I've applied your suggestions, but somehow the label `Progress: needs update` was not removed

2021-02-02 21:25 UTC, sergeynezbritskiy commented on app/code/Magento/CheckoutAgreements/view/frontend/templates/multishipping_agreements.phtml
>   * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
fixed

2021-02-03 08:06 UTC, ihor-sviziev commented
@magento run all tests

2021-02-03 08:46 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2021-02-03 09:39 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Database Compare

2021-02-03 13:46 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Database Compare,

2021-02-03 13:46 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-02-03 13:47 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-02-08 10:13 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Database Compare, Integration Tests

2021-02-08 13:20 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-02-09 13:24 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2021-02-19 11:01 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2023-02-19 20:25 UTC, closed without merging