Magento_Contact: avoid using deprecated escape* methods from Abstract…
magento/magento2 pull request #31675
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 09:22 UTC, ihor-sviziev commented
@magento run all tests

2021-02-02 08:06 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Static Tests

2021-02-03 08:47 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Static Tests

2021-02-03 08:50 UTC, ihor-sviziev requested changes

2021-02-03 08:50 UTC, ihor-sviziev commented on app/code/Magento/Contact/view/frontend/templates/form.phtml
>  /** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */
```suggestion
/**
 * @var \Magento\Contact\Block\ContactForm $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Contact\ViewModel\UserDataProvider $viewModel
 */
```

2021-02-06 20:12 UTC, sergeynezbritskiy commented on app/code/Magento/Contact/view/frontend/templates/form.phtml
>  /** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */
fixed

2021-02-07 15:51 UTC, ihor-sviziev commented
@magento run all tests

2021-02-08 08:02 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2021-02-08 10:05 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-02-19 11:03 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2023-02-19 20:25 UTC, closed without merging