Magento_Cookie: avoid using deprecated escape* methods from AbstractB…
magento/magento2 pull request #31674
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 09:21 UTC, ihor-sviziev commented
@magento run all tests

2021-02-02 08:07 UTC, ihor-sviziev commented
@magento run all tests

2021-02-03 08:49 UTC, ihor-sviziev commented
@magento run all tests

2021-02-03 08:50 UTC, ihor-sviziev requested changes

2021-02-03 08:50 UTC, ihor-sviziev commented on app/code/Magento/Cookie/view/frontend/templates/html/notices.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\Cookie\Block\Html\Notices $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-06 20:09 UTC, sergeynezbritskiy commented on app/code/Magento/Cookie/view/frontend/templates/html/notices.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-07 15:50 UTC, ihor-sviziev commented
@magento run all tests

2021-02-08 08:03 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

2021-02-08 10:06 UTC, ihor-sviziev requested changes
Please fix the failing unit tests

2021-02-11 14:41 UTC, sergeynezbritskiy commented
> Please fix the failing unit tests

fixed

2021-02-11 14:44 UTC, sergeynezbritskiy commented on app/code/Magento/Cookie/view/frontend/templates/html/notices.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-12 05:58 UTC, ihor-sviziev commented
@magento run all tests

2021-02-17 08:10 UTC, ihor-sviziev commented
@magento run Database Compare

2021-02-17 10:35 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-02-17 10:36 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8776](https://jira.corp.magento.com/browse/ENGCOM-8776) has been created to process this Pull Request

2021-02-19 10:57 UTC, ihor-sviziev commented
@magento run Database Compare

2023-02-19 20:25 UTC, closed without merging