Magento_Review: avoid using deprecated escape* methods from AbstractB…
magento/magento2 pull request #31688
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 09:01 UTC, ihor-sviziev commented
@magento run all tests

2021-02-08 10:42 UTC, ihor-sviziev requested changes

2021-02-08 10:42 UTC, ihor-sviziev commented on app/code/Magento/Review/view/frontend/templates/helper/summary_short.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var \Magento\Review\Block\Product\ReviewRenderer $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-08 10:42 UTC, ihor-sviziev commented on app/code/Magento/Review/view/frontend/templates/product/view/list.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
```suggestion
/**
 * @var Magento\Review\Block\Product\View\ListView $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
```

2021-02-11 13:55 UTC, sergeynezbritskiy commented on app/code/Magento/Review/view/frontend/templates/helper/summary_short.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-11 13:55 UTC, sergeynezbritskiy commented on app/code/Magento/Review/view/frontend/templates/product/view/list.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
fixed

2021-02-12 05:56 UTC, ihor-sviziev commented
@magento run all tests

2021-02-17 10:46 UTC, ihor-sviziev commented
@magento run Functional Tests EE, WebAPI Tests

2021-02-18 10:47 UTC, ihor-sviziev requested changes
Please resolve conflicts

2021-03-08 18:34 UTC, sergeynezbritskiy commented on app/code/Magento/Review/view/frontend/templates/product/view/list.phtml
>  /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
trigger removing "Progress: needs update" label

2021-03-09 08:05 UTC, ihor-sviziev commented
@magento run all tests

2021-03-10 07:42 UTC, ihor-sviziev commented
@magento run Database Compare, Functional Tests B2B

2021-03-10 13:59 UTC, ihor-sviziev commented
@magento run Database Compare, Functional Tests B2B

2021-03-11 08:18 UTC, ihor-sviziev commented
@magento run Database Compare, Functional Tests B2B

2021-03-11 12:34 UTC, ihor-sviziev commented
@magento run Database Compare

2021-03-11 12:35 UTC, ihor-sviziev approved these changes

2021-03-11 12:36 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8926](https://jira.corp.magento.com/browse/ENGCOM-8926) has been created to process this Pull Request

2023-02-19 20:25 UTC, closed without merging