Magento_Paypal: avoid using deprecated escape* methods from AbstractB…
magento/magento2 pull request #31693
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 08:59 UTC, ihor-sviziev commented
@magento run all tests

2021-02-08 10:34 UTC, ihor-sviziev requested changes

2021-02-08 10:34 UTC, ihor-sviziev commented on app/code/Magento/Paypal/view/adminhtml/templates/billing/agreement/view/tab/info.phtml
> +/**
```suggestion

/**
```

2021-02-08 10:34 UTC, ihor-sviziev commented on app/code/Magento/Paypal/view/adminhtml/templates/system/config/api_wizard.phtml
>   * @see \Magento\Paypal\Block\Adminhtml\System\Config\ApiWizard
```suggestion
```

2021-02-08 10:34 UTC, ihor-sviziev commented on app/code/Magento/Paypal/view/adminhtml/templates/system/config/bml_api_wizard.phtml
>   * @see \Magento\Paypal\Block\Adminhtml\System\Config\BmlApiWizard
```suggestion
```

2021-02-08 10:34 UTC, ihor-sviziev commented on app/code/Magento/Paypal/view/adminhtml/templates/system/config/payflowlink/info.phtml
>   * @see \Magento\Paypal\Block\Adminhtml\System\Config\Payflowlink\Info
```suggestion
```

2021-02-08 10:34 UTC, ihor-sviziev commented on app/code/Magento/Paypal/view/adminhtml/templates/system/config/payflowlink/advanced.phtml
>   * @var $block \Magento\Paypal\Block\Adminhtml\System\Config\Payflowlink\Advanced
```suggestion
 * @var \Magento\Paypal\Block\Adminhtml\System\Config\Payflowlink\Advanced $block
```

2021-02-11 14:06 UTC, sergeynezbritskiy commented on app/code/Magento/Paypal/view/adminhtml/templates/system/config/api_wizard.phtml
>   * @see \Magento\Paypal\Block\Adminhtml\System\Config\ApiWizard
fixed

2021-02-11 14:06 UTC, sergeynezbritskiy commented on app/code/Magento/Paypal/view/adminhtml/templates/system/config/bml_api_wizard.phtml
>   * @see \Magento\Paypal\Block\Adminhtml\System\Config\BmlApiWizard
fixed

2021-02-12 05:57 UTC, ihor-sviziev commented
@magento run all tests

2021-02-17 10:38 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Functional Tests EE

2021-02-18 10:46 UTC, ihor-sviziev requested changes
Please resolve conflicts

2021-03-08 18:29 UTC, sergeynezbritskiy commented on app/code/Magento/Paypal/view/adminhtml/templates/system/config/payflowlink/advanced.phtml
>   * @var $block \Magento\Paypal\Block\Adminhtml\System\Config\Payflowlink\Advanced
fixed

2021-03-08 18:31 UTC, sergeynezbritskiy commented
> Please resolve conflicts

Hello @ihor-sviziev, fixed

2021-03-09 08:05 UTC, ihor-sviziev commented
@magento run all tests

2021-03-09 10:43 UTC, ihor-sviziev commented
@magento run Database Compare, Functional Tests B2B

2021-03-10 07:42 UTC, ihor-sviziev commented
@magento run Database Compare

2021-03-10 07:42 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-03-10 07:43 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8914](https://jira.corp.magento.com/browse/ENGCOM-8914) has been created to process this Pull Request

2023-02-19 20:25 UTC, closed without merging