Magento_Email: avoid using deprecated escape* methods from AbstractBlock
magento/magento2 pull request #31706
Opened 2021-01-16 16:09 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 08:56 UTC, ihor-sviziev commented
@magento run all tests

2021-01-21 12:46 UTC, ihor-sviziev requested changes
Please check and fix the failing unit tests

2021-01-21 19:52 UTC, sergeynezbritskiy commented
@magento run all tests

2021-01-22 10:06 UTC, ihor-sviziev requested changes

2021-01-22 10:06 UTC, ihor-sviziev commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +    private $block;
Please fix phpdoc block here, it's not the mock

2021-01-22 10:06 UTC, ihor-sviziev commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +    private $escaper;
```suggestion
    private $escaperMock;
```

2021-01-22 10:06 UTC, ihor-sviziev commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +        $this->escaper = $this->createMock(Escaper::class);
```suggestion
        $this->escaperMock = $this->createMock(Escaper::class);
```

2021-01-22 10:06 UTC, ihor-sviziev commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +        $context->method('getEscaper')->willReturn($this->escaper);
```suggestion
        $contextMock = $this->createMock(Context::class);
        $contextMock->method('getEscaper')->willReturn($this->escaperMock);
```

2021-01-22 10:06 UTC, ihor-sviziev commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +        $this->block = new Sender($context);
```suggestion
        $this->block = new Sender($contextMock);
```

2021-01-22 10:06 UTC, ihor-sviziev commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +        $this->escaper->expects($this->any())->method('escapeHtml')->with($templateSenderEmail)
```suggestion
        $this->escaperMock->expects($this->any())->method('escapeHtml')->with($templateSenderEmail)
```

2021-01-22 10:06 UTC, ihor-sviziev commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +        $this->escaper->expects($this->any())->method('escapeHtml')->with($templateSenderEmail)
```suggestion
        $this->escaperMock->expects($this->any())->method('escapeHtml')->with($templateSenderEmail)
```

2021-01-22 12:07 UTC, ihor-sviziev commented
@magento run all tests

2021-01-30 09:43 UTC, sergiynezbritskiy commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +    private $block;
Fixed

2021-01-30 09:43 UTC, sergiynezbritskiy commented on app/code/Magento/Email/Test/Unit/Block/Adminhtml/Template/Render/SenderTest.php
> +        $this->block = new Sender($context);
Fixed

2021-01-30 09:44 UTC, sergeynezbritskiy commented
Hi @ihor-sviziev I've added the changes you requested, please proceed with the review of this PR
Regards

2021-01-30 09:46 UTC, sergeynezbritskiy commented
@magento run Functional Tests B2B, Functional Tests EE

2021-01-30 11:03 UTC, ihor-sviziev approved these changes

2023-02-19 20:25 UTC, closed without merging