Magento_Integration: avoid using deprecated escape* methods from Abst…
magento/magento2 pull request #31702
Opened 2021-01-16 16:08 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 08:56 UTC, ihor-sviziev commented
@magento run all tests

2021-01-22 12:10 UTC, ihor-sviziev requested changes

2021-01-22 12:10 UTC, ihor-sviziev commented on app/code/Magento/Integration/view/adminhtml/templates/integration/activate/permissions.phtml
> + * @var \Magento\Framework\Escaper $escaper
```suggestion
 * @var \Magento\Framework\Escaper $escaper
```

2021-01-22 12:10 UTC, ihor-sviziev commented on app/code/Magento/Integration/view/adminhtml/templates/integration/activate/permissions/tab/webapi.phtml
> + * @var \Magento\Framework\Escaper $escaper
here also duplicated escaper

2021-01-22 12:10 UTC, ihor-sviziev commented on app/code/Magento/Integration/view/adminhtml/templates/integration/popup_container.phtml
> + * @var \Magento\Framework\Escaper $escaper
and here

2021-01-22 12:10 UTC, ihor-sviziev commented on app/code/Magento/Integration/view/adminhtml/templates/integration/tokens_exchange.phtml
> + * @var \Magento\Framework\Escaper $escaper
and here

2021-01-22 14:30 UTC, sergeynezbritskiy commented on app/code/Magento/Integration/view/adminhtml/templates/integration/activate/permissions.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-01-22 14:30 UTC, sergeynezbritskiy commented on app/code/Magento/Integration/view/adminhtml/templates/integration/activate/permissions/tab/webapi.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-01-22 14:30 UTC, sergeynezbritskiy commented on app/code/Magento/Integration/view/adminhtml/templates/integration/popup_container.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-01-22 14:30 UTC, sergeynezbritskiy commented on app/code/Magento/Integration/view/adminhtml/templates/integration/tokens_exchange.phtml
> + * @var \Magento\Framework\Escaper $escaper
fixed

2021-01-22 16:57 UTC, ihor-sviziev commented
@magento run all tests

2021-01-22 17:08 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-01-29 12:53 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, WebAPI Tests

2021-02-19 11:04 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2023-02-19 20:25 UTC, closed without merging