Magento_Framework: avoid using deprecated escape* methods from Abstra…
magento/magento2 pull request #31719
Opened 2021-01-16 16:11 UTC by sergeynezbritskiy

…ctBlock

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-18 07:42 UTC, ihor-sviziev commented
@magento run all tests

2021-01-18 12:08 UTC, ihor-sviziev requested changes

2021-01-18 12:08 UTC, ihor-sviziev commented on dev/tests/integration/testsuite/Magento/Framework/View/_files/test_template.phtml
> + * @var \Magento\Framework\Escaper $escaper
It looks like this is not needed

2021-01-21 08:40 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Framework/View/_files/test_template.phtml
> + * @var \Magento\Framework\Escaper $escaper
Has been removed.

2021-01-21 08:48 UTC, ihor-sviziev commented
@magento run all tests

2021-01-21 12:31 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-01-21 13:06 UTC, engcom-Hotel commented
@magento run Functional Tests CE, Functional Tests EE, Static Tests

2021-01-22 08:14 UTC, engcom-Hotel commented
@magento run Functional Tests CE, Functional Tests EE

2021-01-22 13:49 UTC, engcom-Hotel commented
@magento run Functional Tests CE

2023-02-19 20:25 UTC, closed without merging