Magento_Theme: avoid using deprecated escape* methods from AbstractBlock
magento/magento2 pull request #31712
Opened 2021-01-16 16:09 UTC by sergeynezbritskiy

### Description (*)

Avoid using deprecated escape* methods from AbstractBlock

### Related Pull Requests

https://github.com/magento/magento2/pull/31610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-18 08:00 UTC, ihor-sviziev requested changes

2021-01-18 08:00 UTC, ihor-sviziev commented on app/code/Magento/Theme/view/adminhtml/templates/browser/content/files.phtml
> +\<?php
Please revert this line
```suggestion
<?php
```

2021-01-18 08:22 UTC, sergeynezbritskiy commented on app/code/Magento/Theme/view/adminhtml/templates/browser/content/files.phtml
> +\<?php
reverted

2021-01-18 08:23 UTC, ihor-sviziev commented
@magento run all tests

2021-01-18 15:56 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-01-29 12:48 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-02-01 07:48 UTC, ihor-sviziev commented
@magento run Functional Tests EE

2021-02-09 13:51 UTC, ihor-sviziev requested changes
could you resolve conflict?

2021-02-11 12:27 UTC, sergeynezbritskiy commented
> could you resolve conflict?

done

2021-02-12 05:54 UTC, ihor-sviziev commented
@magento run all tests

2021-02-17 08:09 UTC, ihor-sviziev commented
@magento run Database Compare, Database Compare

2021-02-17 08:09 UTC, ihor-sviziev commented
@magento run WebAPI Tests

2021-02-17 10:33 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-02-17 10:34 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8659](https://jira.corp.magento.com/browse/ENGCOM-8659) has been created to process this Pull Request

2021-02-19 10:57 UTC, ihor-sviziev commented
Database Compare

2021-02-19 10:58 UTC, ihor-sviziev commented
@magento run Database Compare

2023-02-19 20:25 UTC, closed without merging