[ReadMe] updated readMe file for EavGraphQl-EncryptionKey modules
magento/magento2 pull request #31787
Opened 2021-01-20 16:04 UTC by korovitskyi

### Description (*)

Update README.md file for modules:
- Magento_EavGraphQl;
- Magento_Elasticsearch;
- Magento_Elasticsearch6;
- Magento_Elasticsearch7;
- Magento_Email;
- Magento_EncryptionKey.
### Fixed Issues (if relevant)

1. magento/devdocs magento/devdocs#4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-06-12 18:08 UTC, bgorski commented
@magento run all tests

2021-06-12 18:34 UTC, bgorski requested changes
Thank you for your contribution! I added a few comments to the newly introduced content, please review and make adjustments, but the overall effect looks good!

2021-06-12 18:34 UTC, bgorski commented on app/code/Magento/EavGraphQl/README.md
> +Magento_EavGraphQl module extends Magento_GraphQl and Magento_Eav modules to provides type and resolver information for  GraphQL API.
Please fix double space before the "GraphQL" word and change "to provides" either to "and provides" or "to provide".

2021-06-12 18:34 UTC, bgorski commented on app/code/Magento/Elasticsearch/README.md
> +Magento_Elasticsearch module allows using Elastic search engine for the product searching capabilities.
Please rephrase to "using the Elasticsearch search engine", "Using the Elasticsearch engine" or something similar as the service is called Elasticsearch (not "Elastic" or "Elastic search").
Please also add a note that although it provides logic used by other modules implementing newer versions of Elasticsearch, this module by itself only adds support for Elasticsearch v5

2021-06-12 18:34 UTC, bgorski commented on app/code/Magento/EncryptionKey/README.md
> +#Magento_EncryptionKey module
Please include the Extensibility section (https://github.com/magento/devdocs/wiki/Magento-module-README.md#extensibility) with the Layout subsection containing an information that this module introduces a new layout handle - `adminhtml_crypt_key_index`

2021-06-25 11:07 UTC, korovitskyi commented
Hi, @bgorski .
The changes were added.
Thank you for the review.

2021-07-08 12:05 UTC, bgorski requested changes

2021-07-08 12:05 UTC, bgorski commented on app/code/Magento/EavGraphQl/README.md
> +Magento_EavGraphQl module extends Magento_GraphQl and Magento_Eav modules to provides type and resolver information for GraphQL API.
There's still a typo in "provides" - should be "provide"

2021-07-08 12:05 UTC, bgorski commented on app/code/Magento/Elasticsearch/README.md
> +Magento_Elasticsearch module allows using the Elasticsearch engine for the product searching capabilities.
Please add a note that although it provides logic used by other modules implementing newer versions of Elasticsearch, this module by itself only adds support for Elasticsearch v5

2021-07-08 12:06 UTC, bgorski commented
@korovitskyi you missed two things, though, so I re-added those parts of those comments. Please handle those as well. Thanks! We're getting closer!

2021-08-02 14:34 UTC, korovitskyi commented
Hi, @bgorski .
This PR was reopened at https://github.com/magento/magento2/pull/33661.
I have trouble with the fork, so it was needed to recreate it.
Thank you for the review.

2021-08-02 14:34 UTC, closed without merging