Fix some nested extends have been ignored at output
magento/magento2 pull request #31793
Opened 2021-01-21 10:26 UTC by mrtuvn

### Description (*)

In this PR beside update lessjs to more update version. Also i add new group media (backward compatible) Allow groups styles selectors for reuseable

Why i do that
From less doc `extending does not match selectors inside a nested @media declaration:`
Reference => http://lesscss.org/features/#extend-feature (open in new tab)
Idea is group common in same media! Previous extends of magento selectors may not same in media, Some selector nested call to another selector may be ignored

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

CC: @ihor-sviziev @Leland @krzksz  @ptylek @Jordaneisenburger @godban

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-21 17:59 UTC, gabrieldagama commented
@magento run all tests

2021-01-22 10:19 UTC, ihor-sviziev commented
I'm pretty sure functional and web API tests can't be failing because of CSS changes. Also, test results look not related
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2021-01-22 10:19 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes form this PR.

2021-01-22 10:20 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8684](https://jira.corp.magento.com/browse/ENGCOM-8684) has been created to process this Pull Request

2021-01-22 14:26 UTC, mrtuvn commented
For compatible i don't bring media-common mixin to blank theme only apply for luma

2021-01-22 16:00 UTC, mrtuvn commented
@magento run all tests

2021-01-22 17:02 UTC, ihor-sviziev requested changes
Please review and fix the failing static tests

2021-01-23 03:12 UTC, mrtuvn commented
@magento run all tests

2021-01-23 09:02 UTC, mrtuvn commented
@magento run all tests

2021-01-25 08:45 UTC, ihor-sviziev approved these changes

2021-01-25 08:46 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8684](https://jira.corp.magento.com/browse/ENGCOM-8684) has been created to process this Pull Request

2021-01-25 11:42 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a custom theme that extends Magento/luma;
2. Create an **`_extend.less`** file in the custom theme;
3. Add various styles to each group with the same selectors and specificity;
4. Recompile CSS with either Grunt;

**Before:** :heavy_multiplication_x: some block-title rule styles are missing

![2021-01-25_13-37](https://user-images.githubusercontent.com/51679138/105701145-8c21af80-5f12-11eb-9698-5143e553a110.png)

**After:** :heavy_check_mark: All styles are applied

![Screenshot from 2021-01-25 12-25-06](https://user-images.githubusercontent.com/51679138/105701252-b2dfe600-5f12-11eb-817d-21f86ee24e09.png)

Also was checked styles on default themes and everything works as expected.

**_Luma:_** :heavy_check_mark: 
![Screenshot from 2021-01-25 13-32-49](https://user-images.githubusercontent.com/51679138/105701370-e28eee00-5f12-11eb-9656-bcb0d25ca3be.png)

**_Blank:_** :heavy_check_mark: 
![Screenshot from 2021-01-25 13-33-28](https://user-images.githubusercontent.com/51679138/105701439-f5a1be00-5f12-11eb-811a-a27119e70633.png)

2021-01-25 11:58 UTC, ihor-sviziev commented
@engcom-Alfa, could you provide the following info, similar to how it showed in the original ticket?
1. diff of the new version between the server-side compilation vs. grunt based compilation (in this PR)
2. diff of the old version vs. new version on the server-side compilation

2021-01-25 15:29 UTC, engcom-Alfa commented
@ihor-sviziev 
1. diff of the old version vs. new version on the server-side compilation - **_Luma_** theme
**Results:** :heavy_check_mark: The two files are identical - [diff](https://www.diffchecker.com/ZZ3PlI7O/)
2. diff of the new version between the server-side compilation vs. grunt based compilation (with PR changes) - **_Luma_** theme
**Results:** there are quite a few differences - [diff](https://www.diffchecker.com/y9Kvj5ZH/)

@mrtuvn @ihor-sviziev Could you take a look?
Thanks!

2021-01-25 15:31 UTC, ihor-sviziev commented
@mrtuvn seems like issue isn't fixed. Could you take a look?

2021-01-25 16:45 UTC, mrtuvn commented
results will be difference since when use (server-side compilation) magento use less 2.5.3(as package wikimedia/lessphp use) but if we use grunt based compilation (less require by package.json.sample) will 2.7.3

2021-01-25 19:49 UTC, ihor-sviziev commented
@mrtuvn @engcom-Alfa i think in this case we should unlink the issue, as it's not fully fixed and create a new issue for that (grunt based compilation has bribed my account page). What do you thing?

2021-01-26 03:30 UTC, mrtuvn commented
i'm not sure only have page customer account. Maybe another page but we not notice it

2021-01-26 07:53 UTC, engcom-Alfa commented
@mrtuvn All spaces for some reason occur when Magento is in default mode. But when I recompiled in the developer mode, everything got better. Here is the result: [diff](https://www.diffchecker.com/EZFtqHSv/).

2021-01-26 08:37 UTC, mrtuvn commented
In my opinion seem grunt only have big difference than default less compile
order of some mixins (relate .abs- default abstract styles)

Some difference in color string can acceptable 
Line height value decimal precision seem related with configuration option (but ok to me)

2021-01-26 10:17 UTC, mrtuvn commented
@magento run all tests

2021-01-26 10:21 UTC, mrtuvn commented
CC: @krzksz can you take a look at this change ?

2021-01-26 14:02 UTC, ihor-sviziev commented
@magento run Functional Tests EE, Functional Tests CE

2021-01-26 14:03 UTC, ihor-sviziev approved these changes

2021-01-26 14:04 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8684](https://jira.corp.magento.com/browse/ENGCOM-8684) has been created to process this Pull Request

2021-01-26 15:19 UTC, mrtuvn commented
@magento run all tests

2021-01-27 02:11 UTC, mrtuvn commented
@magento run WebAPI Tests, Integration Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-01-27 06:55 UTC, engcom-Alfa commented
@ihor-sviziev Could you review the latest changes? Thanks!

2021-01-27 07:04 UTC, ihor-sviziev approved these changes

2021-01-27 07:05 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8684](https://jira.corp.magento.com/browse/ENGCOM-8684) has been created to process this Pull Request

2021-01-27 08:34 UTC, engcom-Alfa commented
Hi @mrtuvn .

Here are the test results with the latest changes:

- **_Server Side Compilation_** _(with fix)_ & **_Grunt_** _(with fix)_ `styles-m` - :heavy_check_mark: No difference found (**[diff](https://www.diffchecker.com/TX21rj0z/)**)
-  **_Server Side Compilation_** _(with fix)_ & **_Grunt_** _(with fix)_ `styles-l` - :heavy_check_mark: No difference found (**[diff](https://www.diffchecker.com/LfDdOeE0/)**)
- **_Server Side Compilation_** _(mainline)_ & **_Server Side Compilation_** _(with fix)_ `styles-m` - :heavy_multiplication_x: Found several differences (**[diff](https://www.diffchecker.com/uZZx6AG6/)**)
- **_Server Side Compilation_** _(mainline)_ & **_Server Side Compilation_** _(with fix)_ `styles-l` - :heavy_multiplication_x: Found several differences (**[diff](https://www.diffchecker.com/mQRAfmE5/)**)

@mrtuvn Could you take a look?
Thanks!

2021-01-27 08:48 UTC, engcom-Alfa requested changes
Hi @mrtuvn .

Here are the test results with the latest changes:

- **_Server Side Compilation_** _(with fix)_ & **_Grunt_** _(with fix)_ `styles-m` - :heavy_check_mark: No difference found (**[diff](https://www.diffchecker.com/TX21rj0z/)**)
-  **_Server Side Compilation_** _(with fix)_ & **_Grunt_** _(with fix)_ `styles-l` - :heavy_check_mark: No difference found (**[diff](https://www.diffchecker.com/LfDdOeE0/)**)
- **_Server Side Compilation_** _(mainline)_ & **_Server Side Compilation_** _(with fix)_ `styles-m` - :heavy_multiplication_x: Found several differences (**[diff](https://www.diffchecker.com/uZZx6AG6/)**)
- **_Server Side Compilation_** _(mainline)_ & **_Server Side Compilation_** _(with fix)_ `styles-l` - :heavy_multiplication_x: Found several differences (**[diff](https://www.diffchecker.com/mQRAfmE5/)**)

@mrtuvn Could you take a look?
Thanks!

2021-01-27 08:58 UTC, mrtuvn commented
I think new difference can acceptable as main archivement we want both workflow should visual same
Before i think they not be the same. If run by grunt we can't trust the final results. They difference than result by php less compile

2021-01-27 09:33 UTC, ihor-sviziev approved these changes
@engcom-Alfa, I checked the diff between the mainline and with a fix - seems like that was an issue that some styles were missing.
✔ approved from my side

2021-01-27 12:00 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

### Case 1. Grunt compilation

**Manual testing scenario:**

1. Create a custom theme that extends Magento/luma;
2. Create an **`_extend.less`** file in the custom theme;
3. Add various styles to each group with the same selectors and specificity;
4. Recompile CSS with either Grunt;

**Before:** :heavy_multiplication_x: some block-title rule styles are missing

![2021-01-25_13-37](https://user-images.githubusercontent.com/51679138/105701145-8c21af80-5f12-11eb-9698-5143e553a110.png)

**After:** :heavy_check_mark: All styles are applied

![Screenshot from 2021-01-25 12-25-06](https://user-images.githubusercontent.com/51679138/105701252-b2dfe600-5f12-11eb-817d-21f86ee24e09.png)

### Case 2. Server-side less compilation

**Manual testing scenario:**

1. Normal magento use by run commands
2. Run: `setup:upgrade && setup:static-content:deploy`
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-guide/css_quick_guide_mode.html

**After:** :heavy_check_mark: All styles are applied

![Screenshot from 2021-01-27 13-26-36](https://user-images.githubusercontent.com/51679138/105987605-2ca8d880-60a7-11eb-8359-357669a7a417.png)

### Case 3. Less frontend compilation (backend config)

1. Enable developer mode (lessjs compile not work in production);
2. Enable Client side compilation in Advanced Configuration
(Stores > Configuration > Advanced > Developer
Frontend Development Workflow => Workflow type : Client side less compilation);
3. Save and clear cache config admin;

**After:** :heavy_check_mark: All styles are applied

![Screenshot from 2021-01-27 13-33-25](https://user-images.githubusercontent.com/51679138/105987765-6b3e9300-60a7-11eb-9603-22ddcea42699.png)

:heavy_check_mark: No differences were found with the different compilation types

- **_Server Side Compilation_** _(with fix)_ & **_Grunt_** _(with fix)_ `styles-m` - :heavy_check_mark: No difference found (**[diff](https://www.diffchecker.com/TX21rj0z/)**)
-  **_Server Side Compilation_** _(with fix)_ & **_Grunt_** _(with fix)_ `styles-l` - :heavy_check_mark: No difference found (**[diff](https://www.diffchecker.com/LfDdOeE0/)**)

The styles have been checked on different pages with samples and everything is working properly.
And on mobile browsing also everything works well.

![Screenshot from 2021-01-27 13-34-16](https://user-images.githubusercontent.com/51679138/105988205-ffa8f580-60a7-11eb-8bf0-6c160f0d04ef.png)

2021-01-30 17:33 UTC, merged

2022-02-13 13:07 UTC, Inevix commented
hey guys

### General

Selectors of referenced files of styles shouldn't be included to output css files. This fix brakes previous logic. 
Let me explain my point.

### Env

Build: default deploying (`setup:static-content:deploy`)
Theme: clear theme which extends Magento Blank Theme

### Before

When we had the directive `reference` for `_extend.less` files:
<img width="1454" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/28815318/153753473-e482e7c0-b6db-43c3-a68a-e8136003ebc7.png">

We had **194** matches of `abs` selectors which extended in `styles-m.css` file
<img width="1495" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/28815318/153753502-82d28cdb-e844-4ce9-aabc-a1e08e503f2a.png">

And **36** matches in `styles-l.css`:
<img width="1495" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/28815318/153753549-e480bb60-4055-4cda-8267-e1fbf3fa716f.png">

styles-m.css had size: **53.2kb**.

### After

When this fix has been applied and the directive `reference` was removed, we have different result.

Fix:
<img width="1455" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/28815318/153753664-ca1fcb02-adf5-4dce-af0f-16fd35d2554a.png">

We have **323** matches of `abs` selectors which **NOT ONLY extended** in `styles-m.css` file
<img width="1495" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/28815318/153753702-d5d589ba-c5c8-4c9e-846c-a3b379333914.png">

And **45** matches in `styles-l.css`:
<img width="1495" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/28815318/153753720-d3ba71ab-7663-4661-8c5a-779abf30e6cd.png">

styles-m.css have size: **53.9kb** (was **53.2.kb**)
<img width="1495" alt="Pasted Graphic 9" src="https://user-images.githubusercontent.com/28815318/153753754-1da5e278-1018-4f2f-9ac7-5dc49056a405.png">

### Explanation

> Selectors of referenced files of styles shouldn't be included to output css files. This fix brakes previous logic.

### With reference (before this commit)

If I move `_extend.less` file to new clear theme and write my own abs selector `.abs-custom-bg` but without using it:
<img width="1454" alt="Pasted Graphic 12" src="https://user-images.githubusercontent.com/28815318/153753905-8637d652-6df4-4730-b7e6-b235565e6e0a.png">

I don't have any matches with the selector:
<img width="1495" alt="Pasted Graphic 13" src="https://user-images.githubusercontent.com/28815318/153753991-cd14e1a1-6365-46b6-b9ca-bfbe8858f8f4.png">

Even I extend the selector for any selectors in any less file without the directive `reference`, e.g. `_extend.less`:
<img width="1458" alt="Pasted Graphic 14" src="https://user-images.githubusercontent.com/28815318/153754033-f16c5423-1846-4425-8ad6-d0292bc61b3f.png">

I don't have matches with the abs selector but I have applied styles via `&:extend`:
<img width="1495" alt="Pasted Graphic 17" src="https://user-images.githubusercontent.com/28815318/153754037-5e069387-8dd0-4cfb-9576-8bfc01cf43c8.png">

### Without reference (after this commit)

I write my own abs selector without using it:
<img width="1453" alt="Pasted Graphic 19" src="https://user-images.githubusercontent.com/28815318/153754104-16eb6f86-5456-490c-9c6c-e835156a70c8.png">

But this selector compiled to output css as simple selector of any less files:
<img width="1495" alt="Pasted Graphic 18" src="https://user-images.githubusercontent.com/28815318/153754120-be49a4a2-b68c-4f17-a920-bf9d8638cad9.png">

And when I extend it in any files:
<img width="1453" alt="Pasted Graphic 20" src="https://user-images.githubusercontent.com/28815318/153754136-65497b26-bb51-4bb3-9f75-abbff8e8b8bd.png">

I have both selectors:
<img width="1495" alt="Pasted Graphic 21" src="https://user-images.githubusercontent.com/28815318/153754144-eb68e294-baf6-4a3e-95ce-6842caaab747.png">

### Summary

The logic of creating helper selectors have been destroyed to use `abs` selectors (not all) when you need it in any files but not compile **ALL** abs selectors to the output css file.

Most of production projects don't use Grunt as a tool of deploying styles. It has to work with the default deploying process of magento as expected. Please rollback changes.

cc: @ihor-sviziev

2022-02-13 15:52 UTC, ihor-sviziev commented
@mrtuvncouod you please look at @Inevix comment?

2022-02-14 10:18 UTC, Inevix commented
@ihor-sviziev @mrtuvn
I've investigated the issue which has to be fixed in this PR and I have some points and solution for you.

### Points

1. Selectors in referenced files expect that they have to be extended in **OTHER NOT REFERENCED** files. Don't use `extend` in the same referenced file.
2. Grunt doesn't compile `extend` selectors even without wrappers, such as: `media-common` or media mixins.
3. Before making some fix, see any examples which already exist in this file or in any same files.
4. Use `mixin` instead of `extend` in the referenced file.

### Example

Right way:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/28815318/153842285-778c5c84-ccc0-4c3c-b9ec-083c8411e7c8.png">

Wrong way:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/28815318/153842516-f7022e81-ffc0-4468-a0b3-2a791d92274f.png">
 
### Solution

Add `reference` to import of `_extends.less`.

Imports of the file really might be removed from `styles-m` and `styles-l files`:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/28815318/153844139-555432a2-c1de-41cc-9928-ce8c8839259d.png">

Change the code of `extend` for `.abs-block-title`:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/28815318/153844576-e638ff97-6713-42db-8361-fdc8abd6fd70.png">

To a new mixin:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/28815318/153844888-62298079-e172-4abb-80b9-a7663d12e119.png">

### Result

Default deploy:
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/28815318/153845129-1e3cf599-3008-418b-aa3b-0fa0ec70ea1b.png">

Grunt:
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/28815318/153845235-86c8fb3c-7667-4d27-907f-bcb698a11cd8.png">

2022-02-14 10:40 UTC, ihor-sviziev commented
@Inevix, if you already did research, could you please send a Pull Request with suggested changes?
Thank you!

2022-02-14 10:44 UTC, Inevix commented
> @Inevix, if you already did research, could you please send a Pull Request with suggested changes? Thank you!

Can you explain to me how to do that in right way please? I didn't use to contribute.

2022-02-14 15:14 UTC, serhii-chernenko commented
> @Inevix, if you already did research, could you please send a Pull Request with suggested changes? Thank you!

@ihor-sviziev done:
https://github.com/magento/magento2/pull/35101