magento/magento2#31779:Cart Price rule not working as expected for joined mutation for configurable options update - changed key for validator
magento/magento2 pull request #31838
Opened 2021-01-26 12:37 UTC by sasha19957099

### Description (*)
Changed key in sales rules validator to avoid incorrect cached results

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/31779

### Manual testing scenarios (*)
1. use the latest magento with the sample data
2. add to cart 1 product (WJ01-S-Yellow)
3. make sure you have active cart price rule (for example 20% OFF Ever $200-plus purchase!* with magento sampledata )
4. Run query
`
mutation UpdateConfigurableOptions(
  $cartId: String!
  $cartItemId: Int!
  $parentSku: String!
  $variantSku: String!
  $quantity: Float!
) {
  addConfigurableProductsToCart(
    input: {
      cart_id: $cartId
      cart_items: [
        {
          data: { quantity: $quantity, sku: $variantSku }
          parent_sku: $parentSku
        }
      ]
    }
  ) {
    cart {
      id
      total_quantity
      available_payment_methods {
        code
        title
      }
      prices {
        grand_total {
          value
          currency
        }
      }
    }
  }
  removeItemFromCart(input: { cart_id: $cartId, cart_item_id: $cartItemId }) {
    cart {
      id
      total_quantity
      available_payment_methods {
        code
        title
      }
      prices {
        grand_total {
          value
          currency
        }
      }
    }
  }
}

variables
{
  "cartId":"HrDsuEYzcAfHDtP7Cy09Vhf0gbI0VgVU",
  "cartItemId":13,
  "parentSku":"WJ01",
  "variantSku":"WJ01-S-Red",
  "quantity":2
}
`
### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-26 16:04 UTC, sasha19957099 commented
@magento run all tests

2021-01-27 11:26 UTC, sasha19957099 commented
@magento run all tests

2021-01-27 12:34 UTC, sasha19957099 commented
@magento run all tests

2021-01-28 14:58 UTC, cpartica requested changes

2021-01-28 14:58 UTC, cpartica commented on app/code/Magento/SalesRule/Model/Validator.php
> +    public function init($websiteId, CartInterface $quote): self
I'm afraid we can't do this in a patch release. no protected and especially public methods modification. Won't be able to approve SVC
At most we could add an optional parameter which is CartInterface $quote = null
Also don't change the return type, leave self out

2022-04-01 11:45 UTC, engcom-Charlie commented
Hi @sasha19957099,

Thank you for your contribution!

In reproduction steps of this issue, you are using addConfigurableProductsToCart mutation.

As per [dev docs](https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-configurable-products.html) it is recommended of using [addProductsToCart mutation](https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-cart.html) rather than addConfigurableProductsToCart mutation.

Hence before proceeding with this PR, in discussion with the PO for the same. Till that time moving this PR to On Hold.

Thank you!

CC: @cpartica

2022-04-08 07:06 UTC, engcom-Charlie commented
As per @cpartica confirmation we need to process it ahead so moving this PR back to Changes Requested.

Thank you!

2022-04-12 09:33 UTC, engcom-Charlie commented
Hi @sasha19957099,

Thank you for your contribution!

As per the review comments, we can not go with the given solution in this PR as its making modifications in public methods.

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/51680850/162929293-60bc18ff-a370-40a4-8baf-67a2a3d4db48.png">

Do you want to propose any other solution for the linked issue.

Thank you!

2022-04-27 06:40 UTC, engcom-Charlie commented
As we didn't got any reply on above [comment](https://github.com/magento/magento2/pull/31838#issuecomment-1096447219), due to inactivity, closing this PR now.

Please reopen and update if you wish to continue.

Thank you for your contribution!

2022-04-27 06:40 UTC, closed without merging