Admin Place Order not working as expected.
magento/magento2 pull request #31841
Opened 2021-01-26 15:45 UTC by engcom-Kilo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31786

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/31786

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-26 15:53 UTC, engcom-Kilo commented
@magento run all tests

2021-01-26 15:55 UTC, engcom-Kilo commented
@magento run all tests

2021-01-27 17:36 UTC, engcom-Kilo commented
@magento run all tests

2021-01-28 07:32 UTC, engcom-Kilo commented
@magento run all tests

2021-01-28 10:23 UTC, engcom-Kilo commented
@magento run all tests

2021-01-28 11:58 UTC, engcom-Kilo commented
@magento run all tests

2021-01-29 10:45 UTC, zakdma approved these changes

2021-01-29 12:17 UTC, engcom-Kilo commented
@magento run all tests

2021-02-01 16:32 UTC, zakdma requested changes

2021-02-01 16:32 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminCreateOrderFormShippingAddressActionGroup.xml
> +    <actionGroup name="AssertAdminCreateOrderFormShippingAddressActionGroup">
Please rewrite this AG to support other address fields
Example for billing address assert made by @engcom-Echo
https://github.com/magento/magento2/blob/09aec3d4a855d8cbfd4f1806da6d5eac596e02ca/app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminBillingAddressFieldsOnOrderCreateFormActionGroup.xml

2021-02-02 11:42 UTC, engcom-Kilo commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminCreateOrderFormShippingAddressActionGroup.xml
> +    <actionGroup name="AssertAdminCreateOrderFormShippingAddressActionGroup">
Added additional fields.

2021-02-02 11:43 UTC, engcom-Kilo commented
@magento run all tests

2021-02-02 14:43 UTC, engcom-Kilo commented
@magento run all tests

2021-02-02 14:50 UTC, engcom-Kilo commented
@magento run all tests

2021-02-02 15:24 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminCreateOrderFormShippingAddressActionGroup.xml
> +    <actionGroup name="AssertAdminCreateOrderFormShippingAddressActionGroup">
@nmalevanec wjat about
<argument name="province" type="string" defaultValue=""/>

2021-02-02 16:25 UTC, engcom-Kilo commented
@magento run all tests

2021-02-02 16:25 UTC, engcom-Kilo commented
@magento run all tests

2021-02-02 16:26 UTC, engcom-Kilo commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminCreateOrderFormShippingAddressActionGroup.xml
> +    <actionGroup name="AssertAdminCreateOrderFormShippingAddressActionGroup">
Added

2021-02-03 10:54 UTC, zakdma approved these changes

2021-02-03 11:00 UTC, dmitriyprime commented
@magento I am working on this

2021-02-03 15:43 UTC, dmitriyprime commented
:heavy_check_mark: QA passed
Was checked case from Manual testing scenario

2021-02-04 08:54 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-04 08:56 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31841`.

2021-02-05 09:21 UTC, merged