MC-37657: A saved VAT Number is not displayed when placing an order by Admin on a Customer behalf
magento/magento2 pull request #31850
Opened 2021-01-27 09:47 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31846

### Manual testing scenarios (*)

1. See: magento/magento2#31846

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-27 09:47 UTC, engcom-Echo commented
@magento run all tests

2021-01-27 11:53 UTC, engcom-Echo commented
@magento run WebAPI Tests

2021-01-27 14:48 UTC, zakdma requested changes

2021-01-27 14:48 UTC, zakdma commented on app/code/Magento/Customer/Test/Mftf/Data/CustomerData.xml
> +    <entity name="Customer_With_Vat_Number" type="customer">
Could you extend one of the existing datasets and just change/add your address with VAT?
For example: Simple_US_Customer

2021-01-27 14:48 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminFieldsFilledDefaultBillingAddressActionGroup.xml
> +    <actionGroup name="AssertAdminFieldsFilledDefaultBillingAddressActionGroup">
Please rename to
AssertAdminBillingAddressFieldsOnOrderCreateFormActionGroup

2021-01-27 14:48 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminFieldsFilledDefaultBillingAddressActionGroup.xml
> +            <argument name="vatNumber" type="string" defaultValue="U1234567891"/>
Please add all address fields like country, region and others
Check both possibilities for region (dropdown an plain text field)

2021-01-27 14:48 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/Test/AdminCheckingFieldsFilledFromDefaultBillingAddressCustomerInNewOrderTest.xml
> +            <testCaseId value="MC-40646"/>
Add zephyr test to appropriate test cycle

2021-01-27 14:48 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/Test/AdminCheckingFieldsFilledFromDefaultBillingAddressCustomerInNewOrderTest.xml
> +            <group value="Sales"/>
group name should be camelCase
add customer group

2021-01-28 09:56 UTC, engcom-Echo commented
@magento run all tests

2021-01-29 11:16 UTC, zakdma approved these changes

2021-01-29 11:16 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/Test/AdminCheckingFieldsFilledFromDefaultBillingAddressCustomerInNewOrderTest.xml
> +            <deleteData createDataKey="createCustomer" stepKey="deleteCustomer"/>
Data operations should be before any UI operations
In this case move logoutOfAdmin at the bottom of **after** section

2021-02-03 13:46 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-03 13:48 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31850`.

2021-02-10 16:27 UTC, merged