The country / region of mail sent from the admin panel is translated into the admin locale.
magento/magento2 pull request #31875
Opened 2021-01-28 10:50 UTC by engcom-Charlie

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26521
### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-28 10:51 UTC, engcom-Charlie commented
@magento run all tests

2021-01-29 07:19 UTC, eduard13 requested changes
Thank you @engcom-Charlie for the fix, please review the below comment and please note that the following Unit Test has also to be adjusted
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Test/Unit/Model/Order/Address/RendererTest.php

2021-01-29 07:19 UTC, eduard13 commented on app/code/Magento/Customer/Block/Address/Renderer/DefaultRenderer.php
> +                    ->getName(isset($addressAttributes['locale']) ? $addressAttributes['locale'] : null);
Lets use the null coalescing operator
```suggestion
                    ->getName($addressAttributes['locale'] ?? null);
```

2021-01-29 08:29 UTC, engcom-Charlie commented
@magento run all tests

2021-01-29 14:03 UTC, eduard13 approved these changes
Good job 👍

2021-01-29 16:38 UTC, engcom-Bravo commented
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Create two new Stores and Store views, name them _English_ and _Japanese_
![stores](https://user-images.githubusercontent.com/51680745/106300756-87853000-625f-11eb-8594-3a3a23e35008.png)
2. Go to _Stores - Configuration - General - Locale Options_
3. Set English United States **Locale** for the English store view **Scope**, and Japan **Locale** for the Japanese Store view **Scope**
4. Go to **Admin Account Settings** and change the **Interface Locale** to Japan
5. From the Storefront, open English store
6. Place an order specifying the customer address country, United States
7. From Admin Panel, go to _Sales - Orders_ and open the previously created order
8. Click **Send Email**

**BEFORE** applying changes provided in the PR, the country was displayed in Japanese symbols
![country_translate](https://user-images.githubusercontent.com/51680745/106301987-0cbd1480-6261-11eb-93e1-2a54c0992fc5.png)

**AFTER** switching to the PR, the country is displayed in English language
![country_translate_after](https://user-images.githubusercontent.com/51680745/106302064-22cad500-6261-11eb-9788-5c05ecc79026.png)

2021-02-18 13:05 UTC, merged