Fixed Importing: non-default multiple value separator can't be used in custom multiple select attribute
magento/magento2 pull request #31878
Opened 2021-01-28 13:02 UTC by engcom-Charlie

### Description (*)

Fixed issue, covered by the test, refactor test

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#23156

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-01-28 13:03 UTC, engcom-Charlie commented
@magento run all tests

2021-02-02 11:54 UTC, gabrieldagama requested changes
Hi @engcom-Charlie, thanks for working on this. The changes look good, please follow a small suggestion.

Thanks!

2021-02-02 11:54 UTC, gabrieldagama commented on app/code/Magento/CatalogImportExport/Model/Import/Product/Validator.php
> +                $values = $separator === ','
Let's replace this `','` with a private constant, probably call it `DEFAULT_GLOBAL_MULTI_VALUE_SEPARATOR`, to easier readability.

2021-02-02 12:40 UTC, engcom-Charlie commented
@magento run all tests

2021-02-02 14:54 UTC, engcom-Charlie commented
@magento run all tests

2021-02-02 18:57 UTC, engcom-Charlie commented
@magento run all tests

2021-02-25 16:08 UTC, gabrieldagama approved these changes

2021-02-25 16:09 UTC, magento-engcom-team commented
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8819](https://jira.corp.magento.com/browse/ENGCOM-8819) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-02-26 10:53 UTC, engcom-Bravo requested changes
:x: QA Failed

After Checking Data, no errors appear. But after trying to **Import**, an _Undefined index_ error appears
![undefined](https://user-images.githubusercontent.com/51680745/109291298-7a913780-7831-11eb-9302-dfdc7e0d14ce.png)

2021-02-26 11:10 UTC, engcom-Charlie commented
@magento run all tests

2021-03-16 10:32 UTC, therool commented
Hello,
wouldn't it be just enough to change the method "parseMultipleValues" visibility to public in https://github.com/magento/magento2/blob/592c792621e6df4ad3d8de326cb5bd7a005583c7/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L3132 so it can be called directly ("public function parseMultipleValues($labelRow)") and just alter the "multipleselect" attribute type validation on https://github.com/magento/magento2/blob/592c792621e6df4ad3d8de326cb5bd7a005583c7/app/code/Magento/CatalogImportExport/Model/Import/Product/Validator.php#L230 from "$values = $this->context->parseMultiselectValues($rowData[$attrCode]);" to "$values = $this->context->parseMultipleValues($rowData[$attrCode]);")

2021-05-19 08:01 UTC, ihor-sviziev commented
@therool, unfortunately, that would be a backward-incompatible change.

2021-05-19 08:20 UTC, ihor-sviziev requested changes
Please resolve conflicts

2021-05-27 09:54 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-27 13:35 UTC, ihor-sviziev approved these changes

2021-05-27 13:36 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8819](https://jira.corp.magento.com/browse/ENGCOM-8819) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-05-28 05:32 UTC, ihor-sviziev commented
Functional Tests B2B failure looks not related to changes in this PR.

2021-05-28 12:04 UTC, engcom-Foxtrot commented
@magento run Functional Tests B2B

2021-06-25 12:01 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-07-05 08:07 UTC, engcom-Alfa commented
**Before Test - Found no issue :** Tried reproducing the issue prior testing PR fixes in 2.4-develop; No issue noticed. Below are the steps executed!


1. Created the attribute with the name customMultiSelectProdAttri2 in the Admin : Stores > products > Create New Attribute. Below is the configured screenshot.
     ![image](https://user-images.githubusercontent.com/51679138/124438343-af8c3880-dd95-11eb-9173-fb7456ed8295.png)

2. Navigated to Store > Attribute Set > Add Attribute Set - Created the attribute set _custonAttributeSet1_ ; utilized above created attribute. Below is the screenshot used.
     ![image](https://user-images.githubusercontent.com/51679138/124438456-d6e30580-dd95-11eb-852c-4d3b6be20a10.png)

3. Created a simple product using above created attribute type. Below is the product screenshot.

4. Navigated to Admin : System > Export > Select Entity Type - Products > Continue & Downloaded the CSV file.


**Note:** _Used the above steps to pre set the data and the same downloaded file is used to import again replacing with the new product data._
> **The downloaded file has additional_attributes by default:**
> additional_attributes
> customMultiSelectProdAttri2=option2|option3



5. Used the above downloaded csv file and replaced with new product data where set the additional info like:
additional_attributes
customMultiSelectProdAttri2=option2|option3


6. Navigated to the Admin: System > Import > Select Entity Type - Products; Import Behavior - Add/Update; Multiple Value Separator - ||| ; and then click check data button


**As per the reported issue, Should get the error while importing csv file; But no issue identified, check data succeeded as shown in the below screenshot.**

2021-07-20 17:39 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2021-09-08 12:15 UTC, engcom-Charlie commented
Hi @engcom-Alfa,

I have tried to reproduce this issue on 2.4-develop branch and its still reproducible.

I can able to reproduce the issue by the steps mentioned in [your comments](https://github.com/magento/magento2/pull/31878#issuecomment-873899639). Below are the errors I am getting.

![image](https://user-images.githubusercontent.com/51680850/132507241-b69b2330-5135-4b29-95b4-4ec32b4fec1b.png)

Please let me know if you need any other information.

Thank you!

2021-09-08 12:53 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2021-09-08 13:15 UTC, engcom-Alfa commented
> Hi @engcom-Alfa,
> 
> I have tried to reproduce this issue on 2.4-develop branch and its still reproducible.
> 
> I can able to reproduce the issue by the steps mentioned in [your comments](https://github.com/magento/magento2/pull/31878#issuecomment-873899639). Below are the errors I am getting.
> 
> ![image](https://user-images.githubusercontent.com/51680850/132507241-b69b2330-5135-4b29-95b4-4ec32b4fec1b.png)
> 
> Please let me know if you need any other information.
> 
> Thank you!

Thanks @engcom-Charlie for re checking it. Yeah, I re tried today after your updates, able to reproduce using the same steps!

2021-09-08 14:26 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Should have a Magento latest instance with sample data


**Manual testing scenario:**

Follow the same steps defined in [my last comment](https://github.com/magento/magento2/pull/31878#issuecomment-873899639).


**Before:** :heavy_multiplication_x: Data check to import the CSV file was getting failed
 ![image](https://user-images.githubusercontent.com/51679138/132527926-d1a7aef9-34f2-4818-b006-6aac831f1510.png)


**After:** :heavy_check_mark:  Data check to import the CSV file is getting successful.
 ![image](https://user-images.githubusercontent.com/51679138/132528015-7c6effd5-0701-4b40-917d-663ad19387ab.png)

2021-09-08 16:37 UTC, engcom-Alfa commented
Forwarding it for extended testing since a automation test job is getting failed continuously. Kind request to update the ticket with the fixes of failures @engcom-Charlie

2021-09-23 13:50 UTC, engcom-Charlie commented
Hi @engcom-Alfa,

The failing test case is for Currency Converter API configuration. 

Its failing because its not able to retrieve the currency rate from other website api. None of the code changes made in this PR are responsible for this so moving this issue further.

Thank you!

2021-10-21 15:06 UTC, merged