Documentation part 1
magento/magento2 pull request #31938
Opened 2021-02-02 15:08 UTC by ProkopovVitaliy

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-02 17:51 UTC, gabrieldagama commented
Hi @ProkopovVitaliy, thanks for contributing! Can you add a reference to the issue on DevDocs as done by other PRs with the same purpose?

Thanks!

2021-02-03 08:04 UTC, ProkopovVitaliy commented
> Hi @ProkopovVitaliy, thanks for contributing! Can you add a reference to the issue on DevDocs as done by other PRs with the same purpose?
> 
> Thanks!

Done )

2021-02-09 17:08 UTC, VladimirZaets commented
@magento run Performance Acceptance Tests

2021-03-21 20:17 UTC, bgorski requested changes

2021-03-21 20:17 UTC, bgorski commented on app/code/Magento/Msrp/README.md
> +Before disabling or uninstalling this module, note that the following modules depends on this module:
I don't think we should have a list here. The list is not complete and external changes (e.g. adding new core/3rd party modules to the main package) might also require updating the list here.

2021-03-21 20:17 UTC, bgorski commented on app/code/Magento/Msrp/README.md
> +- `msrp_display_actual_price_type` -Display Actual Price
Please add a mention about irreversibility of this and about the fact that if they're not removed when the module is removed/disabled, it would trigger errors (those attributes use models from the Magento_Msrp module)

2021-03-21 20:17 UTC, bgorski commented on app/code/Magento/Multishipping/README.md
> +Extension developers can interact with the Magento_Msrp module. For more information about the Magento extension mechanism, see [Magento plug-ins](https://devdocs.magento.com/guides/v2.4/extension-de
Please correct the module name in this line

2021-03-21 20:17 UTC, bgorski commented on app/code/Magento/MysqlMq/README.md
> +## Installation
Please also add information about the recurring script populating the queue table to this section

2021-03-21 20:17 UTC, bgorski commented on app/code/Magento/Multishipping/README.md
> +### Events
Please add all the events dispatched by the module to this section

2021-03-21 20:21 UTC, bgorski commented
@ProkopovVitaliy, thank you for your contribution! I requested a few changes - most importantly events dispatched by the multishipping module. It's important to describe how modules work (like which events they listen to), but it's also very important to mention all the hooks they provide to developers. But overall the PR looks good!

2021-03-22 13:07 UTC, ProkopovVitaliy commented
@bgorski Thank you for your comment. 

I implemented your recommendations.

2021-03-22 13:21 UTC, bgorski approved these changes
@ProkopovVitaliy thank you! Approving the PR.

2021-03-22 13:22 UTC, magento-engcom-team commented
Hi @bgorski, thank you for the review.
[ENGCOM-8959](https://jira.corp.magento.com/browse/ENGCOM-8959) has been created to process this Pull Request

2021-03-23 08:54 UTC, engcom-Oscar commented
@magento create issue

2021-03-23 11:49 UTC, engcom-Foxtrot commented
@magento run all tests

2021-03-23 20:42 UTC, bgorski commented
@magento run Functional Tests B2B, Functional Tests EE, Unit Tests, WebAPI Tests

2021-04-11 20:11 UTC, merged