MC-40702: Order currency is used instead of bas currency in the shipping label for form
magento/magento2 pull request #31957
Opened 2021-02-03 09:38 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31891

### Manual testing scenarios (*)

1. See magento/magento2#31891

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-03 09:38 UTC, engcom-Echo commented
@magento run all tests

2021-02-03 09:59 UTC, yvaliya commented
@engcom-Echo I think it won't resolve the actual issue mentioned #31891 because currency code isn't an issue. As I mentioned in the issue description, shipping carriers are treating the received amount as a base amount. So instead of changing the currency code, we need to change the amount displayed in the custom amount input field to the base amount of each item.

@zakdma @victorpetryk Please see the possible solution in #31941 instead.

2021-02-03 11:33 UTC, zakdma requested changes

2021-02-03 11:33 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php
> +        $expectedCurrencyCode = '<span class="customs-value-currency">
This check is too unstable. Any change in formatting will break test
I Suggest extract value and check it
```
$template = '/<span class="customs-value-currency">\s*?(?<currency>[A-Za-z]+)\s*?<\/span>/';
$matches = [];
preg_match($template, $text, $matches);
$currency = $matches['currency'] ?? null;
assert...
```

2021-02-03 11:33 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Shipping/_files/shipping_with_carrier_data_different_currency_code.php
> +$productRepository = $objectManager->create(ProductRepositoryInterface::class);
please use get() for product repository

2021-02-03 11:33 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Shipping/_files/shipping_with_carrier_data_different_currency_code.php
> +    'number' => '987654321'
add comma

2021-02-03 12:23 UTC, engcom-Echo commented
@magento run all tests

2021-02-04 09:30 UTC, engcom-Echo commented
@magento run Functional Tests CE

2021-02-04 09:40 UTC, zakdma approved these changes

2021-02-04 12:10 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed
Tested by next scenario:
Additional currency added (UAH) and set as base currency
Online shipping method enabled ( DHL)
Order placed in USD
Shipping label created for order's shipping in admin
:x: **Before:**
![Screenshot from 2021-02-04 12-48-14](https://user-images.githubusercontent.com/60198413/106890786-7d957e00-66f2-11eb-8753-2cfec474023c.png)

:heavy_check_mark: **After:**
![Screenshot from 2021-02-04 13-49-13](https://user-images.githubusercontent.com/60198413/106890954-bc2b3880-66f2-11eb-8c16-798ac6823019.png)

2021-02-11 11:23 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-11 11:25 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31957`.

2021-02-12 07:19 UTC, merged