Replace repetitive actions with Action Groups in AdminDeleteSimpleProductTest
magento/magento2 pull request #31963
Opened 2021-02-03 14:42 UTC by kate-kyzyma

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-03 14:43 UTC, kate-kyzyma commented
@magento run all tests

2021-02-16 16:31 UTC, dmytro-ch requested changes
Hello @kate-kyzyma, could you please check and fix the issue reported by `Semantic Version Checker`?

2021-02-16 16:31 UTC, dmytro-ch commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontProductNotOnSearchPageActionGroup.xml
> +
```suggestion
```

2021-02-16 16:31 UTC, dmytro-ch commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontProductNotOnSearchPageActionGroup.xml
> +
```suggestion
```

2021-02-16 16:31 UTC, dmytro-ch commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontNoResultsMessageOnSearchPageActionGroup.xml
> +
```suggestion
```

2021-02-16 16:31 UTC, dmytro-ch commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontNoResultsMessageOnSearchPageActionGroup.xml
> +
```suggestion
```

2021-02-16 16:31 UTC, dmytro-ch commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontProductNotOnSearchPageActionGroup.xml
> +    <actionGroup name="AssertStorefrontProductNotOnSearchPageActionGroup">
```suggestion
    <actionGroup name="AssertStorefrontProductIsMissingOnSearchResultPageActionGroup">
```

2021-02-17 08:15 UTC, kate-kyzyma commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontProductNotOnSearchPageActionGroup.xml
> +
Fixed

2021-02-17 08:15 UTC, kate-kyzyma commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontProductNotOnSearchPageActionGroup.xml
> +
Fixed

2021-02-17 08:15 UTC, kate-kyzyma commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontNoResultsMessageOnSearchPageActionGroup.xml
> +
Fixed

2021-02-17 08:15 UTC, kate-kyzyma commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontNoResultsMessageOnSearchPageActionGroup.xml
> +
Fixed

2021-02-17 08:17 UTC, kate-kyzyma commented on app/code/Magento/CatalogSearch/Test/Mftf/ActionGroup/AssertStorefrontProductNotOnSearchPageActionGroup.xml
> +    <actionGroup name="AssertStorefrontProductNotOnSearchPageActionGroup">
Fixed

2021-02-17 08:21 UTC, kate-kyzyma commented
Hello @dmytro-ch!
I have fixed the mentioned issues. Please, check.

2021-02-17 08:21 UTC, kate-kyzyma commented
@magento run Semantic Version Checker

2021-02-17 08:24 UTC, kate-kyzyma commented
@magento run Semantic Version Checker

2021-02-23 14:34 UTC, kate-kyzyma commented
@magento run all tests

2021-02-24 11:21 UTC, dmytro-ch commented
@magento run Static Tests, WebAPI Tests, Functional Tests B2B, Functional Tests EE

2021-02-24 12:42 UTC, dmytro-ch commented
@magento run Static Tests

2021-02-24 13:44 UTC, dmytro-ch commented
@magento run Static Tests, Functional Tests B2B,

2021-02-25 09:31 UTC, dmytro-ch commented
@magento run Functional Tests B2B, Functional Tests EE

2021-03-15 07:41 UTC, kate-kyzyma commented
@magento run Functional Tests B2B, Functional Tests EE

2021-03-17 07:43 UTC, kate-kyzyma commented
@magento run all tests

2021-03-17 12:15 UTC, kate-kyzyma commented
@magento run Functional Tests B2B, Functional Tests EE

2021-03-18 07:39 UTC, kate-kyzyma commented
@magento run Functional Tests B2B

2021-03-18 13:56 UTC, dmytro-ch commented
@magento run Functional Tests B2B

2021-04-08 06:23 UTC, kate-kyzyma commented
@magento run all tests

2021-04-09 10:42 UTC, kate-kyzyma commented
@magento run Functional Tests EE, WebAPI Tests

2021-04-13 11:07 UTC, kate-kyzyma commented
@magento run Functional Tests EE

2021-04-15 06:45 UTC, kate-kyzyma commented
@magento run all tests

2021-04-26 11:50 UTC, dmytro-ch commented
@magento run Integration Tests

2021-04-27 10:05 UTC, dmytro-ch approved these changes

2021-04-27 10:06 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-9048](https://jira.corp.magento.com/browse/ENGCOM-9048) has been created to process this Pull Request

2021-08-13 05:15 UTC, eduard13 commented
@magento create issue

2021-08-13 05:15 UTC, eduard13 approved these changes

2021-08-13 05:16 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9048](https://jira.corp.magento.com/browse/ENGCOM-9048) has been created to process this Pull Request

2021-08-13 08:48 UTC, engcom-Charlie commented
✔️ QA Passed

The provided MFTF test case is working fine and green in build. Please find the Allure report for the same.

![image](https://user-images.githubusercontent.com/51680850/129330759-55836a9f-4bb1-4794-916d-4e3eb501ab56.png)

![image](https://user-images.githubusercontent.com/51680850/129330777-3d05eca6-c2a4-46a5-9ced-9b6115614c6c.png)

2021-10-23 15:04 UTC, merged