Github #31984: fix for array offset bug during some 404s (PHP 7.4)
magento/magento2 pull request #31985
Opened 2021-02-08 04:03 UTC by erfanimani

### Description (*)

Fixes "Trying to access array offset on value of type bool" when accessing certain non existing category paths for known products, on PHP 7.4.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31984

### Manual testing scenarios (*)

1. On PHP 7.4, make a GET request to {nonexistentcategory}/{product_url} (where product_url is an existing saleable product)
2. Ensure status code is 404, not 500

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-08 13:24 UTC, ihor-sviziev requested changes
Hi @erfanimani,
Could you cover your changes with any type of automated tests?

2021-02-08 13:27 UTC, erfanimani commented
@ihor-sviziev I'm thinking it might be hard to isolate this particular issue as it's nested within a few private method calls, but I'll have a look tomorrow — thanks for the feedback

2021-02-12 05:01 UTC, erfanimani commented
Hi @ihor-sviziev, I can't create unit tests as the SUT contains only private/protected methods. I can create a MFTF test that reproduces the error (although sometimes it won't, depending on PHP error reporting and PHP version), and simply returns a 404 not found if successful. I'm not sure how relevant a test like that would be for the future. What's your opinion?

See the original issue for steps to reproduce.

2021-02-12 05:50 UTC, ihor-sviziev commented
I don’t think mftf test sis suitable here. 
@engcom-Charlie do you feel we can cover this change with some unit / integration test? If so - could you share your thoughts how to do that?

2021-02-12 08:31 UTC, engcom-Charlie commented
@ihor-sviziev I think can try via unit test by using reflection.
Smth like this https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Paypal/Test/Unit/Model/Payflow/Service/GatewayTest.php#L206

2021-02-12 09:59 UTC, ihor-sviziev commented
TBH I have a feeling that this logic should be extracted to a separate model and tested separately. What do you think?

2021-03-02 11:42 UTC, ihor-sviziev requested changes
Hi @erfanimani,
Could you cover your changes with the unit test, as suggested in https://github.com/magento/magento2/pull/31985#issuecomment-778054763 ?

2021-03-03 06:23 UTC, erfanimani commented
Thanks @ihor-sviziev, I'll try and update the PR.

2021-03-05 07:42 UTC, erfanimani commented
@ihor-sviziev, please see the updated PR. I believe I've got 100% test coverage of the method that was changed. Feedback is appreciated.

Thanks.

2021-03-05 07:43 UTC, erfanimani commented
Oops, closed the PR by accident. Reopened.

2021-03-05 07:56 UTC, ihor-sviziev commented
@magento run Unit Tests, Static Tests

2021-03-05 11:49 UTC, ihor-sviziev requested changes

2021-03-05 11:49 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Test/Unit/Model/Storage/DynamicStorageTest.php
> +    private $urlRewriteFactory;
Please add "Mock" suffix to all mocks
```suggestion
    private $urlRewriteFactoryMock;
```

2021-03-05 11:49 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Test/Unit/Model/Storage/DynamicStorageTest.php
> +    ) {
Let's define object types 
```suggestion
    public function testFindProductRewriteByRequestPath(
        array $data,
        $productFromDb,
        string? $categorySuffix,
        $categoryFromDb,
        bool $canBeShownInCategory,
        array? $expectedProductRewrite
    ): void {
```

2021-03-05 11:49 UTC, ihor-sviziev commented on app/code/Magento/CatalogUrlRewrite/Test/Unit/Model/Storage/DynamicStorageTest.php
> +     * @param $expectedProductRewrite
please define expected types for params

2021-03-05 16:25 UTC, erfanimani commented
Thanks for the feedback @ihor-sviziev, I've updated the PR with your suggestions.

2021-03-05 18:37 UTC, ihor-sviziev commented
@magento run all tests

2021-03-06 06:39 UTC, ihor-sviziev commented
@magento run  Integration Tests

2021-03-06 06:40 UTC, ihor-sviziev approved these changes

2021-03-06 06:42 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8884](https://jira.corp.magento.com/browse/ENGCOM-8884) has been created to process this Pull Request

2021-04-23 13:44 UTC, dmitriyprime commented
:heavy_check_mark:  **QA passes**

:x: **Before:**
![before](https://user-images.githubusercontent.com/17761633/115880104-064ecb00-a453-11eb-9de6-e79232bce463.png)

:heavy_check_mark: **After**
![after](https://user-images.githubusercontent.com/17761633/115880181-1d8db880-a453-11eb-8941-b4d938f932d0.png)

2021-04-26 22:56 UTC, merged