MC-40777: Cannot save product in store view scope without Magento_Catalog::edit_product_design
magento/magento2 pull request #31998
Opened 2021-02-09 08:12 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31973

### Manual testing scenarios (*)

1. See magento/magento2#31973

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-09 08:12 UTC, engcom-Echo commented
@magento run all tests

2021-02-09 10:45 UTC, engcom-Echo commented
@magento run all tests

2021-02-10 10:55 UTC, zakdma requested changes

2021-02-10 10:55 UTC, zakdma commented on app/code/Magento/Catalog/Model/Product/Authorization.php
> +        ?RequestInterface $request = null
Dont think you should use Request inside model.
Please change implementation to not involve request to model.

2021-02-12 08:12 UTC, engcom-Echo commented
@magento run all tests

2021-02-15 15:28 UTC, engcom-Echo commented
@magento run all tests

2021-02-16 13:41 UTC, zakdma requested changes

2021-02-16 13:41 UTC, zakdma commented on app/code/Magento/Catalog/Model/Product/Authorization.php
> +            if ($attribute->getBackendType() == 'datetime' && empty($newValue)) {
Please change second condition to $newValue === null

2021-02-16 13:41 UTC, zakdma commented on dev/tests/integration/testsuite/Magento/Catalog/_files/product_simple_with_design_attributes.php
> +$productRepository = $objectManager->create(ProductRepositoryInterface::class);
Please use get()

2021-02-16 13:46 UTC, engcom-Echo commented
@magento run all tests

2021-02-16 16:34 UTC, zakdma approved these changes

2021-02-17 10:35 UTC, dmitriyprime commented
@magento I am working on this

2021-02-17 13:43 UTC, dmitriyprime commented
:heavy_minus_sign:  QA failed
If administrator with restricted role changes on Schedule Design Update tab not only Schedule Update From field but for example New Theme or New Layout fields or both he/she cannot save product after changing some product attributes (for example product name) on specific store view.

2021-02-18 10:59 UTC, engcom-Echo commented
@magento run all tests

2021-02-18 12:30 UTC, zakdma approved these changes

2021-02-18 13:45 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 

:x: **Before:**

![Screenshot from 2021-02-18 15-20-31](https://user-images.githubusercontent.com/60198413/108365849-5bc2ed80-7200-11eb-9f7b-9bc0666aeb12.png)

:heavy_check_mark: **After:**

![Screenshot from 2021-02-18 15-44-40](https://user-images.githubusercontent.com/60198413/108365868-61b8ce80-7200-11eb-8fb6-d7ab3221cbd2.png)

2021-02-24 12:03 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-24 12:06 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31998`.

2021-03-03 07:42 UTC, merged