MC-40013: Payment Methods radio-buttons disappear after a "Create New Order" page in Admin panel is reload
magento/magento2 pull request #32107
Opened 2021-02-11 09:44 UTC by victorpetryk

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32106

### Manual testing scenarios (*)

see magento/magento2#32106

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-11 09:44 UTC, victorpetryk commented
@magento run all tests

2021-02-11 13:01 UTC, victorpetryk commented
@magento run all tests

2021-02-11 15:30 UTC, victorpetryk commented
@magento run all tests

2021-02-11 16:40 UTC, zakdma requested changes

2021-02-11 16:40 UTC, zakdma commented on app/code/Magento/Sales/view/adminhtml/templates/order/create/billing/method/form.phtml
> +                    <?php if ($_methodsCount > 1): ?>
Should cover these changes with MFTF test

2021-02-11 23:56 UTC, victorpetryk commented
@magento run all tests

2021-02-12 08:48 UTC, zakdma requested changes

2021-02-12 08:48 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/Section/AdminOrderFormPaymentSection.xml
> +        <element name="paymentLabelWithRadioButton" type="text" selector="#order-billing_method_form .admin__control-radio+label"/>
Can we use parametrized selector to check payment radio by name

2021-02-12 08:48 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/ActionGroup/AssertAdminPaymentMethodRadioButtonExistsOnCreateOrderPageActionGroup.xml
> +        <seeElement selector="{{AdminOrderFormPaymentSection.paymentLabelWithRadioButton}}" stepKey="seeLabelWithRadioButton"/>
Can we check particular payment radio by payment method name?

2021-02-12 08:48 UTC, zakdma commented on app/code/Magento/Sales/Test/Mftf/Test/AdminCheckingPaymentMethodRadioButtonPresentAfterReloadOrderPageTest.xml
> +        <actionGroup ref="AssertAdminPaymentMethodRadioButtonExistsOnCreateOrderPageActionGroup" stepKey="assertPaymentRadioButtonIsPresent"/>
Can we check both payment methods exists?

2021-02-12 10:41 UTC, victorpetryk commented
@magento run all tests

2021-02-12 13:16 UTC, zakdma approved these changes

2021-02-12 14:19 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 
:x: **Before:**
![Screenshot from 2021-02-12 16-04-20](https://user-images.githubusercontent.com/60198413/107779471-101aca80-6d4e-11eb-9a26-d0bef818af4d.png)

:heavy_check_mark: **After:**
![Screenshot from 2021-02-12 16-18-23](https://user-images.githubusercontent.com/60198413/107779493-15781500-6d4e-11eb-9b4f-05e5b9101199.png)

2021-02-12 15:50 UTC, victorpetryk commented
@magento run Functional Tests B2B

2021-02-15 08:42 UTC, victorpetryk commented
@magento run all tests

2021-02-17 14:16 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-17 14:19 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:20 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:24 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-17 14:28 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:29 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:33 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-17 14:36 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:37 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:48 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-17 14:50 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32107`.

2021-02-18 09:58 UTC, merged