Api framework graphql interfaces mark
magento/magento2 pull request #32101
Opened 2021-02-10 16:30 UTC by mrtuvn

### Description (*)

Mark GraphQL interfaces as api

lib/internal/Magento/Framework/GraphQl/Config/ConfigElementFactoryInterface.php
lib/internal/Magento/Framework/GraphQl/Config/ConfigElementInterface.php
lib/internal/Magento/Framework/GraphQl/Config/Element/FieldInterface.php
lib/internal/Magento/Framework/GraphQl/Config/Element/OutputFieldInterface.php
lib/internal/Magento/Framework/GraphQl/Config/Element/TypeInterface.php
lib/internal/Magento/Framework/GraphQl/Config/Element/UnionInterface.php
lib/internal/Magento/Framework/GraphQl/ConfigInterface.php
lib/internal/Magento/Framework/GraphQl/Query/ErrorHandlerInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributesInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/SearchCriteria/ArgumentApplierInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/BatchRequestItemInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/BatchResolverInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/BatchServiceContractResolverInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/ContextInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/IdentityInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/ResolveRequestInterface.php
lib/internal/Magento/Framework/GraphQl/Query/Resolver/TypeResolverInterface.php
lib/internal/Magento/Framework/GraphQl/Query/ResolverInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/SchemaGeneratorInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/Type/Entity/MapperInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/Type/Enum/DataMapperInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/Type/InputTypeInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/Type/Output/ElementMapper/FormatterInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/Type/OutputTypeInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/Type/WrappedTypeInterface.php
lib/internal/Magento/Framework/GraphQl/Schema/TypeInterface.php
lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader/TypeMetaReaderInterface.php

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32028

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-12 07:39 UTC, eduard13 commented
@magento run all tests

2021-02-13 03:27 UTC, mrtuvn commented
@magento run Database Compare, Functional Tests B2B, Static Tests

2021-02-14 02:52 UTC, mrtuvn commented
@magento run Static Tests, Functional Tests B2B, Database Compare

2021-02-15 05:33 UTC, eduard13 commented
@magento run Static Tests, Functional Tests B2B, Database Compare

2021-02-17 14:32 UTC, eduard13 approved these changes

2021-02-17 14:36 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8782](https://jira.corp.magento.com/browse/ENGCOM-8782) has been created to process this Pull Request

2021-02-18 14:42 UTC, eduard13 commented
@magento run Database Compare

2021-02-18 17:21 UTC, mrtuvn commented
@magento run all tests

2021-02-18 18:42 UTC, mrtuvn commented
@magento run all tests

2021-02-18 19:10 UTC, mrtuvn commented
@sivaschenko interfaces mark (non-api) in my description seem got issue when add api annotation
related with problem Magento\Test\Integrity\PublicCodeTest->testAllPHPClassesReferencedFromPublicClassesArePublic()

2021-02-20 07:45 UTC, mrtuvn commented
update + fix static
@magento run all tests

2021-02-20 10:13 UTC, mrtuvn commented
@magento run WebAPI Tests

2021-04-03 01:46 UTC, mrtuvn commented
Re-targeted PR branch to 2.4-develop as internal discussed with @gabrieldagama

2021-04-03 15:10 UTC, mrtuvn commented
@magento run all tests

2021-04-03 21:07 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-04-04 16:20 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-04-05 07:39 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-04-05 09:02 UTC, engcom-Oscar commented
Hi @mrtuvn !
Looks like you missed lib/internal/Magento/Framework/GraphQl/Query/Resolver/BatchServiceContractResolverInterface.php.
Please recheck.

2021-04-05 09:31 UTC, mrtuvn commented
Nice catch! I will update

2021-04-05 11:13 UTC, mrtuvn commented
cc: @engcom-Oscar corrected my mistakes

2021-04-05 16:15 UTC, mrtuvn commented
@magento run all tests

2021-04-05 21:58 UTC, mrtuvn commented
@magento run Unit Tests, Functional Tests B2B

2021-04-06 22:58 UTC, mrtuvn commented
@magento run Functional Tests EE, Functional Tests B2B

2021-04-14 01:48 UTC, mrtuvn commented
@gabrieldagama should this PR target to branch api-changes-develop

2021-04-15 10:39 UTC, gabrieldagama requested changes

2021-04-15 10:39 UTC, gabrieldagama commented on lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader/TypeMetaReaderInterface.php
> +    public function read(\GraphQL\Type\Definition\Type $typeMeta): ?array;
Please, do not change the return type of this function. This is backward incompatible and may create other problems.

2021-04-15 11:09 UTC, mrtuvn commented
@magento run all tests

2021-04-15 14:30 UTC, mrtuvn commented
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests B2B, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2021-04-15 22:06 UTC, mrtuvn commented
@magento run all tests

2021-04-16 11:39 UTC, mrtuvn commented
@magento run all tests

2021-04-16 14:23 UTC, mrtuvn commented
@magento run all tests

2021-04-17 04:08 UTC, mrtuvn commented
@magento run all tests

2021-04-21 09:36 UTC, mrtuvn commented
@magento run all tests

2021-04-22 12:02 UTC, mrtuvn commented
@magento run all tests

2021-04-22 12:03 UTC, mrtuvn commented
cc @@gabrieldagama  updated PR branch

2021-04-24 00:59 UTC, mrtuvn commented
@magento run all tests

2021-04-26 22:51 UTC, mrtuvn commented
@magento run all tests

2021-04-29 03:42 UTC, mrtuvn commented
@magento run all tests

2021-04-29 22:44 UTC, mrtuvn commented
@magento run Unit Tests, Static Tests, Integration Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

2021-04-30 10:09 UTC, gabrieldagama commented
@mrtuvn, please ignore the failures, for now, they are related to the fact that `api-changes-develop` is not up to date with `2.4-develop`, it will be fixed soon.

2021-05-05 13:14 UTC, gabrieldagama approved these changes

2021-05-06 09:21 UTC, gabrieldagama commented
@magento import code to https://github.com/magento-engcom/magento2ce

2021-05-06 09:23 UTC, magento-engcom-team commented
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32101`.

2021-05-06 12:40 UTC, merged