MC-40651: A Configuration of a Configurable Product is reset when editing it in the Wish List
magento/magento2 pull request #32120
Opened 2021-02-11 15:54 UTC by SmVladyslav

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32119

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-11 16:05 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-11 16:08 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32120`.

2021-02-12 07:49 UTC, SmVladyslav commented
@magento run all tests

2021-02-12 13:27 UTC, zakdma requested changes

2021-02-12 13:27 UTC, zakdma commented on app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontUpdateConfigurableProductAttributeOptionFromWishlistTest.xml
> +            </createData>
Please always perform
```
<magentoCron groups="index" stepKey="reindexInvalidatedIndices"/>
```
after new product attribute added

2021-02-12 13:45 UTC, SmVladyslav commented on app/code/Magento/Wishlist/Test/Mftf/Test/StorefrontUpdateConfigurableProductAttributeOptionFromWishlistTest.xml
> +            </createData>
Fixed

2021-02-12 13:45 UTC, SmVladyslav commented
@magento run all tests

2021-02-12 15:38 UTC, SmVladyslav commented
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

2021-02-15 08:41 UTC, SmVladyslav commented
@magento run Functional Tests B2B

2021-02-16 10:28 UTC, zakdma approved these changes

2021-02-16 14:11 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 
:x: **Before:**

(/) A Customer is redirected to the editing Product page
 (x) The displayed price is =As low as $100.00
 (x) The option “black + $100.00” is not pre-selected in the “Color” drop-down

:heavy_check_mark: **After:**

 A Customer redirected to the editing Product page
* The displayed price  = $200.00
* The option “black </ins> +100$ pre-selected in the “Color” drop-down
![Screenshot from 2021-02-16 16-10-08](https://user-images.githubusercontent.com/60198413/108074083-7adf4500-7071-11eb-8b00-09343ffcc53f.png)

2021-02-17 14:14 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-17 14:17 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:18 UTC, magento-engcom-team commented
@zakdma, an error occurred during the Pull Request import.

2021-02-17 14:24 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-02-17 14:26 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32120`.

2021-02-18 09:58 UTC, merged