Marked classes and interfaces as API part 2
magento/magento2 pull request #32132
Opened 2021-02-12 07:17 UTC by ProkopovVitaliy

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32056

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-12 07:18 UTC, ProkopovVitaliy commented
@magento run all tests

2021-02-12 11:41 UTC, ProkopovVitaliy commented
@magento run test Static Tests, Functional Tests CE

2021-02-12 11:42 UTC, ProkopovVitaliy commented
@magento run tests Static Tests, Functional Tests CE

2021-02-12 11:42 UTC, ProkopovVitaliy commented
@magento run Static Tests, Functional Tests CE

2021-02-22 09:40 UTC, eduard13 requested changes
@ProkopovVitaliy please mark the non-public types as `api` as well, which should fix the Static Tests.
Thank you.

2021-02-22 09:40 UTC, eduard13 commented
magento run Database Compare

2021-02-24 15:15 UTC, eduard13 commented
@magento run Database Compare

2021-03-02 15:13 UTC, eduard13 commented
Hi @ProkopovVitaliy will you be able to update this PR, in order to fix the Static Tests?

2021-03-03 12:02 UTC, ProkopovVitaliy commented
@magento run Static Tests

2021-03-03 12:02 UTC, ProkopovVitaliy commented
@magento run Static Tests

2021-03-03 12:36 UTC, ProkopovVitaliy commented
@magento run all tests

2021-03-04 06:16 UTC, eduard13 requested changes
Thank you @ProkopovVitaliy for fixing the Static Tests, could you please also fix these minor things I've mentioned below?

2021-03-04 06:16 UTC, eduard13 commented on app/code/Magento/Customer/Block/Adminhtml/Edit/GenericButton.php
>   * @package Magento\Customer\Block\Adminhtml\Edit
Let's remove the `@package` annotation.
```suggestion
```

2021-03-04 06:16 UTC, eduard13 commented on lib/internal/Magento/Framework/Console/Cli.php
> + * @api
Usually, the `@api` annotation should be followed by other annotations, like `@SuppressWarnings`. Lets remove the `@inheritdoc` and move `@SuppressWarnings` at the end, separated by a new line.

2021-03-04 06:16 UTC, eduard13 commented on app/code/Magento/Catalog/Controller/Adminhtml/Product.php
> + * @api
Lets move the `@SuppressWarnings` at the end, and `@api` should follow class description.

2021-03-04 06:16 UTC, eduard13 commented
@magento run Functional Tests B2B, Database Compare

2021-03-09 06:49 UTC, ProkopovVitaliy commented
@magento run all tests

2021-03-09 07:43 UTC, eduard13 commented
@magento run Database Compare

2021-03-09 11:00 UTC, eduard13 commented
@magento run Database Compare, Functional Tests B2B

2021-03-09 14:39 UTC, eduard13 commented
@magento run Database Compare, Functional Tests B2B

2021-03-10 06:17 UTC, eduard13 commented
@magento run Database Compare, Functional Tests B2B

2021-03-15 07:04 UTC, ProkopovVitaliy commented
@magento run all tests

2021-03-15 14:05 UTC, ProkopovVitaliy commented
@magento run WebAPI Tests

2021-03-15 17:53 UTC, eduard13 approved these changes
Good job 👍

2021-03-15 17:54 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8930](https://jira.corp.magento.com/browse/ENGCOM-8930) has been created to process this Pull Request

2021-05-28 09:57 UTC, gabrieldagama commented
Hi @ProkopovVitaliy can you recreate this PR to the api-changes-develop branch instead? Just make sure to create a new branch from this one and cherry pick your commit.

Thanks!

2021-06-11 11:48 UTC, gabrieldagama commented
Closed in favor of https://github.com/magento/magento2/pull/33222

2021-06-11 11:48 UTC, closed without merging