Mark Framework interfaces as API part 9
magento/magento2 pull request #32151
Opened 2021-02-13 04:10 UTC by mrtuvn

### Description (*)

Marked following interfaces as API

lib/internal/Magento/Framework/View/File/FileList/CollateInterface.php
lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/SecurityProcessorInterface.php
lib/internal/Magento/Framework/View/Layout/Argument/UpdaterInterface.php
lib/internal/Magento/Framework/View/Layout/Condition/VisibilityConditionInterface.php
lib/internal/Magento/Framework/View/Layout/GeneratorInterface.php
lib/internal/Magento/Framework/View/Layout/LayoutCacheKeyInterface.php
lib/internal/Magento/Framework/View/Layout/ProcessorInterface.php
lib/internal/Magento/Framework/View/Layout/ReaderInterface.php
lib/internal/Magento/Framework/View/Model/PageLayout/Config/BuilderInterface.php
lib/internal/Magento/Framework/View/Page/Config/RendererInterface.php
lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Compiler/AttributeInterface.php
lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Compiler/CdataInterface.php
lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Compiler/CommentInterface.php
lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Compiler/Directive/DirectiveInterface.php
lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Compiler/Element/ElementInterface.php
lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Compiler/TextInterface.php
lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/ResultInterface.php
lib/internal/Magento/Framework/View/TemplateEngineInterface.php
lib/internal/Magento/Framework/View/Xsd/Media/TypeDataExtractorInterface.php
lib/internal/Magento/Framework/Webapi/CustomAttribute/PreprocessorInterface.php
lib/internal/Magento/Framework/Webapi/CustomAttribute/ServiceTypeListInterface.php
lib/internal/Magento/Framework/Webapi/Rest/Request/DeserializerInterface.php

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32036

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-14 02:53 UTC, mrtuvn commented
@magento run all tests

2021-02-18 14:45 UTC, mrtuvn commented
Rebased 2.5-develop branch

2021-02-18 15:18 UTC, eduard13 commented
@magento run all tests

2021-02-18 17:27 UTC, mrtuvn commented
Public type 'Magento\Framework\View\Model\PageLayout\Config\BuilderInterface' references following non-public types:
\Magento\Framework\View\PageLayout\Config
Seems add `api ` annotation got issue fail static tests
Magento\Test\Integrity\PublicCodeTest->testAllPHPClassesReferencedFromPublicClassesArePublic()
CC: @sivaschenko

2021-02-19 06:53 UTC, eduard13 commented
@mrtuvn, looks like we'll have to mark them as api as well.

2021-02-20 07:19 UTC, mrtuvn commented
Fixed static

2021-02-20 07:20 UTC, mrtuvn commented
Fixed static
@magento run all tests

2021-02-22 10:54 UTC, eduard13 requested changes
Hi @mrtuvn, please review the below minor comment, and can you please declare the strict types for all the classes as well?

Thank you.

2021-02-22 10:54 UTC, eduard13 commented on lib/internal/Magento/Framework/View/Page/Config/RendererInterface.php
>   * @package Magento\Framework\View\Page\Config
Please let remove the `package` annotation, as not being needed.

2021-02-23 03:11 UTC, mrtuvn commented
@magento run all tests

2021-02-23 08:27 UTC, mrtuvn commented
@magento run all tests

2021-02-23 15:18 UTC, mrtuvn commented
@magento run Functional Tests CE

2021-02-24 15:14 UTC, eduard13 commented
@magento run Functional Tests CE

2021-02-25 07:08 UTC, eduard13 approved these changes

2021-02-25 07:09 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8813](https://jira.corp.magento.com/browse/ENGCOM-8813) has been created to process this Pull Request

2021-04-03 01:40 UTC, mrtuvn commented
Re-targeted PR branch to 2.4-develop as internal discussed with @gabrieldagama

2021-04-03 15:10 UTC, mrtuvn commented
@magento run all tests

2021-04-03 21:05 UTC, mrtuvn commented
@magento run Functional Tests B2B, Integration Tests

2021-04-13 09:44 UTC, gabrieldagama commented
@magento import code to https://github.com/magento-engcom/magento2ce

2021-04-13 09:47 UTC, magento-engcom-team commented
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32151`.

2021-04-13 15:10 UTC, merged