Mark various interfaces as api
magento/magento2 pull request #32157
Opened 2021-02-14 17:29 UTC by mrtuvn

### Description (*)

The following interfaces marked as API

app/code/Magento/Msrp/Pricing/MsrpPriceCalculatorInterface.php
app/code/Magento/Newsletter/Model/SubscriptionManagerInterface.php
app/code/Magento/PageCache/Model/Spi/PageCacheTagsPreprocessorInterface.php
app/code/Magento/Payment/Api/Data/PaymentAdditionalInfoInterface.php
app/code/Magento/Payment/Model/Method/Online/GatewayInterface.php
app/code/Magento/Payment/Model/Method/TransparentInterface.php
app/code/Magento/Paypal/Helper/Shortcut/ValidatorInterface.php
app/code/Magento/Paypal/Model/Billing/Agreement/MethodInterface.php
app/code/Magento/Paypal/Model/IpnInterface.php
app/code/Magento/Paypal/Model/Payflow/Service/Response/Handler/HandlerInterface.php
app/code/Magento/Paypal/Model/Payflow/Service/Response/ValidatorInterface.php
app/code/Magento/Quote/Api/ChangeQuoteControlInterface.php
app/code/Magento/Quote/Model/Cart/BuyRequest/BuyRequestDataProviderInterface.php
app/code/Magento/Quote/Model/Product/QuoteItemsCleanerInterface.php
app/code/Magento/Quote/Model/Quote/Address/CustomAttributeListInterface.php
app/code/Magento/Quote/Model/Quote/Address/Total/CollectorInterface.php
app/code/Magento/Quote/Model/Quote/Address/Total/ReaderInterface.php
app/code/Magento/Quote/Model/Quote/Item/CartItemProcessorInterface.php
app/code/Magento/Quote/Model/ValidationRules/QuoteValidationRuleInterface.php
app/code/Magento/QuoteGraphQl/Model/Cart/BuyRequest/BuyRequestDataProviderInterface.php
app/code/Magento/QuoteGraphQl/Model/Cart/Payment/AdditionalDataProviderInterface.php
app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressesOnCartInterface.php
app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingMethodsOnCartInterface.php
app/code/Magento/QuoteGraphQl/Model/CartItem/DataProvider/CustomizableOptionValueInterface.php
app/code/Magento/QuoteGraphQl/Model/CartItem/DataProvider/Processor/ItemDataProcessorInterface.php

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32020

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-15 15:25 UTC, BarnyShergold commented
@magento run all tests

2021-02-16 10:56 UTC, BarnyShergold commented
@magento run Functional Tests B2B

2021-02-16 10:57 UTC, BarnyShergold commented
@magento run Static Tests

2021-02-16 10:57 UTC, BarnyShergold commented
@magento run Database Compare

2021-02-16 14:26 UTC, BarnyShergold commented
@magento run Static Tests

2021-02-16 14:27 UTC, BarnyShergold commented
@magento run Database Compare

2021-02-17 14:52 UTC, BarnyShergold requested changes
The Database Compare & Static Tests keep failing but I can't see why what you've added would cause these issues. Can you check?

2021-02-17 15:20 UTC, mrtuvn commented
Seem false positive change

2021-02-17 17:45 UTC, mrtuvn commented
@magento run Static Tests

2021-02-18 07:08 UTC, engcom-Hotel commented
@magento run all tests

2021-02-18 12:26 UTC, engcom-Hotel commented
@magento run Functional Tests EE

2021-02-18 14:22 UTC, engcom-Hotel commented
@magento run all tests

2021-02-18 14:24 UTC, engcom-Hotel commented
@magento run all tests

2021-02-18 17:22 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-02-19 07:55 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-19 10:20 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-19 13:21 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-02-19 15:56 UTC, BarnyShergold approved these changes

2021-02-19 15:57 UTC, magento-engcom-team commented
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8800](https://jira.corp.magento.com/browse/ENGCOM-8800) has been created to process this Pull Request

2021-02-20 08:04 UTC, mrtuvn commented
Fix static
@magento run all tests

2021-02-20 08:56 UTC, mrtuvn commented
Fix static
@magento run all tests

2021-02-20 10:09 UTC, mrtuvn commented
Fix static
@magento run all tests

2021-02-20 14:38 UTC, mrtuvn commented
@magento run WebAPI Tests, Semantic Version Checker, Functional Tests EE

2021-02-21 02:16 UTC, mrtuvn commented
@magento run Semantic Version Checker

2021-02-21 06:43 UTC, mrtuvn commented on app/code/Magento/Payment/Model/Method/Online/GatewayInterface.php
>  {
Replace deprecated interface

2021-02-21 08:16 UTC, mrtuvn commented
@magento run all tests

2021-02-21 12:03 UTC, mrtuvn commented
@magento run Static Tests, Unit Tests

2021-02-21 14:03 UTC, mrtuvn commented
@magento run Static Tests

2021-02-21 14:57 UTC, mrtuvn commented
@magento run WebAPI Tests, Unit Tests, Semantic Version Checker, Integration Tests,Functional Tests EE, Functional Tests CE, Functional Tests B2B, Database Compare,Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

2021-02-22 02:52 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-02-22 13:50 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2021-04-03 01:47 UTC, mrtuvn commented
Re-targeted PR branch to 2.4-develop as internal discussed with @gabrieldagama

2021-04-03 02:42 UTC, mrtuvn commented
@magento run all tests

2021-04-03 06:23 UTC, mrtuvn commented
@magento run Integration Tests, Functional Tests CE, Functional Tests EE

2021-05-05 16:30 UTC, gabrieldagama approved these changes

2021-05-06 12:48 UTC, gabrieldagama commented
@magento import code to https://github.com/magento-engcom/magento2ce

2021-05-06 12:51 UTC, magento-engcom-team commented
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32157`.

2021-06-01 13:00 UTC, merged