[32017] Marked Directory, Downloadable, Eav and Elasticsearch interfaces as API
magento/magento2 pull request #32161
Opened 2021-02-15 13:47 UTC by Usik2203

### Description (*)

This PR fixes https://github.com/magento/magento2/issues/32017
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32017

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-15 13:47 UTC, Usik2203 commented
@magento run all tests

2021-02-15 14:27 UTC, coderimus requested changes
Hi @Usik2203 thank you for the adjustments. Please, check my comments about the empty lines. Everything else good 👍

2021-02-15 14:27 UTC, coderimus commented on app/code/Magento/Eav/Model/ResourceModel/Attribute/DefaultEntityAttributes/ProviderInterface.php
> + *
Please, remove an empty line after the @api

2021-02-15 14:27 UTC, coderimus commented on app/code/Magento/Eav/Model/Entity/Setup/PropertyMapperInterface.php
> + *
Please, remove an empty line after the @api

2021-02-15 14:27 UTC, coderimus commented on app/code/Magento/Eav/Model/Entity/Attribute/Backend/BackendInterface.php
> + *
Please, remove an empty line after the @api

2021-02-15 14:27 UTC, coderimus commented on app/code/Magento/Eav/Model/Entity/Attribute/AttributeInterface.php
> + *
Please, remove an empty line after the @api

2021-02-15 14:57 UTC, Usik2203 commented
@magento run all tests

2021-02-15 14:58 UTC, Usik2203 commented
Hi @coderimus 
I have applied your recommendations .
Thanks !

2021-02-16 11:26 UTC, coderimus approved these changes

2021-02-16 11:27 UTC, coderimus commented
@Usik2203 thank you for the adjustments 👍

2021-02-16 11:27 UTC, magento-engcom-team commented
Hi @coderimus, thank you for the review.
[ENGCOM-8763](https://jira.corp.magento.com/browse/ENGCOM-8763) has been created to process this Pull Request

2021-02-25 16:06 UTC, Usik2203 commented
@magento run all tests

2021-04-13 13:07 UTC, gabrieldagama commented
Closed in favour of https://github.com/magento/magento2/pull/32726

2021-04-13 13:07 UTC, closed without merging