[32059] Update classes and interfaces and mark them as API part 3
magento/magento2 pull request #32184
Opened 2021-02-16 12:02 UTC by Usik2203

### Description (*)

This PR fixes https://github.com/magento/magento2/issues/32059
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32059

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-16 12:02 UTC, Usik2203 commented
@magento run all tests

2021-02-16 14:30 UTC, BarnyShergold commented
@magento run Unit Tests,WebAPI Tests

2021-02-16 16:32 UTC, Usik2203 commented
@magento run all tests

2021-02-19 12:02 UTC, eduard13 commented
@magento run Database Compare, Functional Tests B2B, Functional Tests EE, Semantic Version Checker, Unit Tests

2021-02-22 07:38 UTC, eduard13 commented
@magento run Database Compare, Functional Tests B2B, Semantic Version Checker, Unit Tests

2021-02-25 16:17 UTC, Usik2203 commented
@magento run Semantic Version Checker, Unit Tests

2021-02-26 06:20 UTC, eduard13 requested changes
hi @Usik2203, could you please check what's reason of Unit Test failing?

2021-02-26 15:18 UTC, Usik2203 commented
@magento run all tests

2021-02-26 15:27 UTC, eduard13 commented on app/code/Magento/Catalog/Model/Config.php
> +    public function getSourceOptionId($source, string $value)
@Usik2203 lets revert this change.
```suggestion
    public function getSourceOptionId($source, $value)
```

2021-02-26 15:30 UTC, Usik2203 commented
@magento run all tests

2021-02-26 16:19 UTC, eduard13 commented
@magento run Magento Health Index

2021-02-26 20:13 UTC, eduard13 commented
@magento run Functional Tests B2B

2021-03-02 19:40 UTC, eduard13 approved these changes

2021-03-02 19:42 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-8879](https://jira.corp.magento.com/browse/ENGCOM-8879) has been created to process this Pull Request

2021-04-13 15:13 UTC, Usik2203 commented
Closed in favour of https://github.com/magento/magento2/pull/32738

2021-04-13 15:13 UTC, closed without merging