Fixed #32203 Catalog Widget. Select with product conditions displays…
magento/magento2 pull request #32204
Opened 2021-02-17 14:39 UTC by evgeniykapelko

… incorrect attributes.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32203

### Manual testing scenarios (*)

1. see magento/magento2#32203

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-17 14:40 UTC, evgeniykapelko commented
@magento run all tests

2021-02-17 14:49 UTC, evgeniykapelko commented
@magento run all tests

2021-02-17 15:08 UTC, BarnyShergold requested changes

2021-02-17 15:08 UTC, BarnyShergold commented on app/code/Magento/CatalogWidget/Model/Rule/Condition/Product.php
> +    protected $_isUsedForRuleProperty = 'is_used_for_promo_rules';
This is a static value. You should use a constant for this. For a start it is more efficient.

2021-02-17 15:08 UTC, BarnyShergold commented on app/code/Magento/CatalogWidget/Model/Rule/Condition/Product.php
>          foreach ($productAttributes as $attribute) {
As the method loadAttributeOptions() is being functionally changed, the testsuite test for the method should be updated to take into consideration the attribute can now affect the output.

2022-10-13 15:03 UTC, ishakhsuvarov commented
Hi @evgeniykapelko 

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:03 UTC, closed without merging