Replace repetitive actions with Action Groups in AdminConfigurableProductLongSkuTest
magento/magento2 pull request #32225
Opened 2021-02-19 12:23 UTC by kate-kyzyma

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-19 12:24 UTC, kate-kyzyma commented
@magento run all tests

2021-02-23 12:32 UTC, dmytro-ch requested changes

2021-02-23 12:32 UTC, dmytro-ch commented on app/code/Magento/ConfigurableProduct/Test/Mftf/ActionGroup/AssertAdminChildProductDataOnParentProductEditPageActionGroup.xml
> +            <description>Proper Child product data (name, sku, price) are shown on the Configurable Product edit page.</description>
```suggestion
            <description>Verify the proper child product data (name, sku, price) is shown on the Configurable Product edit page.</description>
```

2021-02-23 12:33 UTC, dmytro-ch commented
Hello @kate-kyzyma, could you please check and fix the issues reported by Semantic Version Checker?

2021-02-23 14:48 UTC, kate-kyzyma commented
@magento run all tests

2021-02-24 07:59 UTC, kate-kyzyma commented
@magento run all tests

2021-02-24 11:17 UTC, dmytro-ch commented
@magento run Functional Tests EE, Static Tests

2021-02-24 12:40 UTC, dmytro-ch commented
@magento run Static Tests

2021-02-24 13:46 UTC, dmytro-ch commented
@magento run Functional Tests EE

2021-02-25 09:29 UTC, dmytro-ch commented
@magento run Static Tests

2021-03-10 08:53 UTC, kate-kyzyma commented
@magento run all tests

2021-03-10 15:14 UTC, dmytro-ch approved these changes

2021-03-10 15:15 UTC, magento-engcom-team commented
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8917](https://jira.corp.magento.com/browse/ENGCOM-8917) has been created to process this Pull Request

2024-01-19 10:02 UTC, engcom-Delta commented
@kate-kyzyma, Please remove the conflicts on the PR

2024-01-19 10:03 UTC, engcom-Delta requested changes
Remove the existing conflicts

2024-10-23 11:19 UTC, engcom-Dash commented
Closing this PR since it has not been updated for a long time. Please feel free to reopen it if needed.

2024-10-23 11:19 UTC, closed without merging