Error messages are not shown in frontend
magento/magento2 pull request #32246
Opened 2021-02-22 17:10 UTC by sheepfy

cloneObj = { ...obj }   this is equivalent to $classA = clone $classB; in php.

This snippet : 
            // Force to clean obsolete messages
            if (!_.isEmpty(this.messages().messages)) {
                customerData.set('messages', {});
            }

is clearing the variable "this.messages" because there is a memory reference between them, defined at line `this.messages = customerData.get('messages'). .....`

2021-02-23 17:33 UTC, gabrieldagama commented
Hi @sheepfy,

Thanks for contributing, can you provide more details on the problem that we are fixing here? Steps to reproduce this issue would be helpful!

Thanks!

2021-02-23 17:34 UTC, gabrieldagama requested changes
Changing state.

2021-02-24 08:51 UTC, sheepfy commented
@gabrieldagama  i was able to notice this issue with the following configuration: Simple product with min qty = 5, qty increment = 2. Go to product page, click add to cart. Error message is not shown.

After debugging, i noticed that the messages are retrieved from customerData. And next line is removing the customerData messages. This will also remove the values from the variable `this.messages` which is later on called in template.

I did found these only on Google Chrome browser.

![image](https://user-images.githubusercontent.com/17467949/108974483-2c8ffe80-768e-11eb-845f-b9119942a4d4.png)

2021-02-26 10:26 UTC, sheepfy commented
@gabrieldagama please note that i have changes the spread operator `...` with `Object.assign` because if you use some 3rd party js optimisation , FE r.js , r.js will throw some Esprisma parsing error for that spread operator

"Error: Error: Parse error using esprima for file: /var/www/folder/revisions/release-server-number/pub/static/frontend/path/path/lang_Lang/Magento_Theme/js/view/messages.js"

https://esprima.org/demo/parse.html?code=const%20a%20%3D%20%7B%20foo%3A%20%27bar%27%20%7D%3B%0Aconst%20b%20%3D%20%7B%20...a%20%7D%3B

2021-03-04 07:47 UTC, closed without merging

2021-03-04 08:54 UTC, sheepfy commented
my mistake with this PR. 
No need bothering with this one