MC-23989: Mini cart missing when you edit inline welcome message for guest and use special characters
magento/magento2 pull request #32251
Opened 2021-02-23 09:35 UTC by engcom-Echo

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

Fixes: https://github.com/magento/magento2/issues/32250

### Manual testing scenarios (*)

1. See: https://github.com/magento/magento2/issues/32250

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-23 09:35 UTC, engcom-Echo commented
@magento run all tests

2021-02-23 13:24 UTC, engcom-Echo commented
@magento run all tests

2021-02-23 15:46 UTC, zakdma requested changes

2021-02-23 15:46 UTC, zakdma commented on app/code/Magento/Theme/view/frontend/templates/html/header.phtml
> +              data-bind="html: "<?= $escaper->escapeHtml($welcomeMessage) ?>"></span>
This solution looks unreliable. Please tru to leave quotes as was but change escaper method to escapeHtmlAttribute
Please add tests to cover changes

2021-03-03 07:53 UTC, zakdma commented
@magento run all tests

2021-03-03 07:54 UTC, zakdma approved these changes

2021-03-03 10:55 UTC, zakdma commented
@magento run Database Compare, Functional Tests B2B, Functional Tests EE

2021-03-04 08:15 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-03-04 08:17 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32251`.

2021-03-04 12:09 UTC, zakdma commented
@magento run all tests

2021-03-04 12:10 UTC, zakdma approved these changes

2021-03-04 14:33 UTC, zakdma commented
@magento run Functional Tests B2B

2021-03-04 17:11 UTC, zakdma commented
@magento run Functional Tests B2B

2021-03-05 11:11 UTC, zakdma commented
@magento run all tests

2021-03-09 11:02 UTC, zakdma commented
@magento import code to https://github.com/magento-tsg/magento2ce

2021-03-09 11:07 UTC, magento-engcom-team commented
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32251`.

2021-03-11 21:51 UTC, merged