Category content upload media minify#31633
magento/magento2 pull request #32398
Opened 2021-03-09 08:32 UTC by gixid192

### Description (*)
The current regex syntax uses literal space (blank character) which leads to the elimination when applying minification process.

The fix simply changes blank character to `\s`, which is whitespace in regex rule/syntax.

### Fixed Issues (if relevant)
Fixes magento/magento2#31633

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-09 08:33 UTC, gixid192 commented
@magento run all tests

2021-03-09 09:37 UTC, ihor-sviziev requested changes
Hi @gixid192,
Could you cover your changes with any type of automated test?

2021-03-09 10:07 UTC, gixid192 commented
Hi @ihor-sviziev 

I was wondering if I should write tests for this PR.
My code isn't new, `blank to \s`, the change is pretty much the same as before.

Do you think that it is necessary to write tests on this case?

2021-03-09 10:12 UTC, ihor-sviziev commented
@gixid192 It's obvious that this code isn't new, but it was breaking in some cases. According to [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html) - all code changes must be covered by automated tests. This is needed to make sure we'll not re-introduce it again in the future.

2021-03-10 01:11 UTC, gixid192 commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests

2021-03-10 03:36 UTC, gixid192 commented
@magento run Functional Tests EE

2021-03-10 06:10 UTC, gixid192 commented
@ihor-sviziev The tests are all green now. So I assume the code is correct.

In case you still want a test for this PR, could you suggest a way? I mean, the error only happens when source is minified, how to test this, what kind of this test is this called? Also, as the whitespace and \s are all most the same, what should I write a test to differentiate those 2? I don't have much experience writing test so any help would be great.

2021-03-10 07:15 UTC, ihor-sviziev commented
Hi @gixid192,
Yeah, I just analyzed your changes one more time, and it will be too hard to get it automatically tested somehow. I believe the only manual testing is possible here. I'm approving your PR.

2021-03-10 07:15 UTC, ihor-sviziev approved these changes

2021-03-10 07:16 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8912](https://jira.corp.magento.com/browse/ENGCOM-8912) has been created to process this Pull Request

2021-03-15 11:24 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 

-  Enable built-in JS Minification (production mode) ( `bin/magento config:set dev/js/minify_files 1` )

- DIsable old media gallery ( Stores -> Configuration -> System -> Media Gallery and set **Enable Old Media Gallery** to **No**)

### Steps to reproduce (*)
1. Go to Admin -> Catalog -> Categories -> Content -> Select from Gallery
2. Open the context menu for any image (3 dots) and select "Edit"
3. Enter image title, description, add keywords
4. Click "Save"

:x: **Before:**
Image details are not saved. `Uncaught TypeError: Cannot read property 'call' of undefined` in jquery.validate
There are JS console errors when media gallery is opened:
`Uncaught SyntaxError: Invalid regular expression: missing /` validate-image-title.min.js:1 
`Uncaught SyntaxError: Invalid regular expression: missing /` validate-image-description.min.js:1 
![Screenshot from 2021-03-15 12-03-56](https://user-images.githubusercontent.com/60198413/111146021-a16d9e80-8591-11eb-8bc2-b083bfc956ec.png)

:heavy_check_mark: **After:**
Image details are saved without successfully.
![Screenshot from 2021-03-15 13-23-00](https://user-images.githubusercontent.com/60198413/111146153-c82bd500-8591-11eb-8546-eebf85885d21.png)

2021-03-18 12:51 UTC, merged