Add WEBP Support by default
magento/magento2 pull request #32400
Opened 2021-03-09 10:41 UTC by in-session

Webp should already be set up by default

2021-03-09 10:48 UTC, ihor-sviziev requested changes
Hi @in-session,
Could you sign Adobe CLA and update the nginx config sample as well?
https://github.com/magento/magento2/blob/2.4-develop/nginx.conf.sample

2021-03-09 11:30 UTC, hostep commented
Maybe add the new avif image format as well? It's not [supported by many browsers yet](https://caniuse.com/avif), but will be in the future ...

Some extension developers are already starting to implement it:
- https://www.yireo.com/blog/2020-12-29-magento2-webp-becomes-next-gen
- https://www.jajuma.de/en/jajuma-develop/extensions/ultimate-image-optimizer-extension-for-magento-2
- ...

2021-03-09 11:31 UTC, ihor-sviziev commented
Yeah, make sense for sure

On Tue, 9 Mar 2021 at 13:30, Pieter Hoste <notifications@github.com> wrote:

> Maybe add the new avif image format as well? It's not supported by many
> browsers yet <https://caniuse.com/avif>, but will be in the future ...
>
> Some extension developers are already starting to implement it:
>
>    - https://www.yireo.com/blog/2020-12-29-magento2-webp-becomes-next-gen
>    -
>    https://www.jajuma.de/en/jajuma-develop/extensions/ultimate-image-optimizer-extension-for-magento-2
>    - ...
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/32400#issuecomment-793751206>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOJOUPSC3FMNIV6FVXL67DTCYBETANCNFSM4Y3JOOMA>
> .
>

2021-03-09 11:53 UTC, ihor-sviziev commented
@magento run all tests

2021-03-09 12:06 UTC, hostep commented
Maybe also avif sequences? https://github.com/h5bp/server-configs-apache/pull/251

https://github.com/h5bp/server-configs-apache/ is my go to project for verifying apache config settings, maybe double check webp as well? (sorry lack of time here for proper review)

2021-03-09 12:08 UTC, in-session commented
Ok let me check i will add also some other like opentype fonts

2021-03-09 12:20 UTC, in-session commented
> Maybe also avif sequences? [h5bp/server-configs-apache#251](https://github.com/h5bp/server-configs-apache/pull/251)
> 
> https://github.com/h5bp/server-configs-apache/ is my go to project for verifying apache config settings, maybe double check webp as well? (sorry lack of time here for proper review)

Have you some information about nginx?
`location ~* \.(ico|jpg|jpeg|png|gif|svg|webp|avif|avifs`

or

`location ~* \.(ico|jpg|jpeg|png|gif|svg|webp|avif|avifs?`

2021-03-09 12:25 UTC, ihor-sviziev commented
@in-session I believe it's better to use `location ~* \.(ico|jpg|jpeg|png|gif|svg|webp|avif|avifs`  as it will be just simpler to read

2021-03-09 13:44 UTC, in-session commented
Ok I think that is good for now

Added Media + Static
- svgz
- webp
- avif
- avifs

Removed Media + Static
- swf

Added Static
- webmanifest
- font/truetype
- font/opentype

Maybe someone can go through the nginx.conf.sample again?

2021-03-09 14:06 UTC, ihor-sviziev requested changes
Could you check my comments and then squash all your commits to single one?

2021-03-09 14:06 UTC, ihor-sviziev commented on pub/static/.htaccess
> +    <FilesMatch \.(ico|gif|png|jpg|jpeg|svg|svgz|webp|avif|avifs?)$>
I believe the `?` at the end is useless in this case as you listed both `avif` and `avifs` in the list:
```suggestion
    <FilesMatch \.(ico|gif|png|jpg|jpeg|svg|svgz|webp|avif|avifs)$>
```

2021-03-09 14:06 UTC, ihor-sviziev commented on pub/static/.htaccess
> +    <FilesMatch .*\.(ico|jpg|jpeg|png|gif|svg|webp|avif|avifs?|js|css|eot|ttf|otf|woff|woff2|html|json|webmanifest)$>
```suggestion
    <FilesMatch .*\.(ico|jpg|jpeg|png|gif|svg|webp|avif|avifs|js|css|eot|ttf|otf|woff|woff2|html|json|webmanifest)$>
```

2021-03-09 14:19 UTC, ihor-sviziev requested changes
Could you squash all your changes to single commit?

2021-03-09 14:50 UTC, in-session commented
> Could you squash all your changes to single commit?
It seems like I can't do that.

2021-03-10 07:19 UTC, ihor-sviziev commented
@in-session here is a good example of how you can squash all commits: https://www.internalpointers.com/post/squash-commits-into-one-git
Please note that after all your changes, you need to force push your changes.

In case of any questions - please reach me at EngCom Slack.

2021-03-11 08:18 UTC, ihor-sviziev commented
Let's leave it not squashed.
@magento run all tests

2021-03-11 12:19 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-03-11 12:19 UTC, ihor-sviziev approved these changes

2021-03-11 12:21 UTC, ihor-sviziev approved these changes

2021-03-11 12:21 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8925](https://jira.corp.magento.com/browse/ENGCOM-8925) has been created to process this Pull Request

2021-03-11 12:21 UTC, magento-engcom-team commented
@in-session thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2021-03-12 09:24 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-03-12 21:39 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-03-15 08:49 UTC, engcom-Oscar commented
@engcom-Foxtrot can you please check this PR, it require dev-experience.

2021-03-16 13:08 UTC, engcom-Foxtrot commented
QA passed

2021-03-16 13:39 UTC, engcom-Oscar commented
@magento create issue

2021-03-19 12:03 UTC, engcom-Foxtrot commented
@magento run all tests

2021-04-11 20:11 UTC, merged