Simplify setup wizard: remove angular, combine all data on one page, etc
magento/magento2 pull request #32475
Opened 2021-03-14 14:40 UTC by hws47a

### Description (*)

Simplify setup wizard code:
- remove angular
- combine landing+license on the same page
- remove other unused files

This could be one of the steps to remove laminas MVC or other dependencies used only for setup scripts and not necessary after removing main Setup Wizard logic

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

Open setup wizard `/setup/` and check that both landing and license pages are the same as before

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-14 15:00 UTC, hws47a commented
@magento run all tests

2021-03-15 08:26 UTC, ihor-sviziev commented
@hws47a looks really good! Less code, fewer dependencies, more simple solutino is definitely a good thing! Let me know when I can start reviewing it.

@magento run Functional Tests B2B, Unit Tests

2021-03-15 09:21 UTC, hws47a commented
@ihor-sviziev you can start, it doesn’t seem that any checks are failing because of my changes.

2021-03-15 09:36 UTC, sivaschenko commented
@magento run Unit Tests

2021-03-15 09:42 UTC, sivaschenko requested changes
Thanks for the pull request @hws47a ! Please see my review comments.

2021-03-15 09:42 UTC, sivaschenko commented on setup/src/Magento/Setup/Controller/Index.php
> +    public function __construct(
Please add the method phpdoc

2021-03-15 09:42 UTC, sivaschenko commented on setup/src/Magento/Setup/Controller/Index.php
> +    public function indexAction(): ViewModel
I'd also add `declare(strict_types=1);` to this file

2021-03-15 09:42 UTC, sivaschenko commented on setup/pub/scripts/main.js
> +function showSection(section) {
Please add the copyrights section

2021-03-15 20:02 UTC, hws47a commented
@sivaschenko all three fixed

2021-03-15 20:02 UTC, hws47a commented
@magento run all tests

2021-03-16 05:14 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-03-16 10:39 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-03-16 15:38 UTC, hws47a commented
@ihor-sviziev all passed 🙌

2021-03-16 15:40 UTC, ihor-sviziev approved these changes

2021-03-16 15:41 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8932](https://jira.corp.magento.com/browse/ENGCOM-8932) has been created to process this Pull Request

2021-03-16 18:35 UTC, hws47a commented
@magento run all tests

2021-03-16 20:54 UTC, ihor-sviziev approved these changes

2021-03-17 20:13 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Integration Tests

2021-03-17 22:59 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-03-18 18:08 UTC, sivaschenko commented
@magento create issue

2021-03-18 18:10 UTC, merged