Fix #32336 - Checkout Shipping form cache don't get empty
magento/magento2 pull request #32516
Opened 2021-03-17 07:46 UTC by Bartlomiejsz

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32336

### Manual testing scenarios (*)

Please check fixed issue for testing scenario

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-17 07:46 UTC, Bartlomiejsz commented
@magento run all tests

2021-03-21 20:10 UTC, Bartlomiejsz commented
@magento run all tests

2021-03-21 22:36 UTC, Bartlomiejsz commented
@magento run Functional Tests EE

2021-04-28 21:05 UTC, Den4ik requested changes
Hi @Bartlomiejsz Thanks for your contribution.
Please look at my comments.

2021-04-28 21:05 UTC, Den4ik commented on app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js
> +                    checkoutData.setShippingAddressFromData(shippingAddrsData);
As I see result looks like revert changes for "MC-38048: Incorrect default country displayed on shipping page when store view is changed in cart. Part 2" https://github.com/magento/magento2/commit/d59ad58d924f50350908ae504bbff46ebdef59d6
As result we revert issue with store view change. Could you please recheck it.
Special thanks for mftf.

2022-10-13 15:10 UTC, ishakhsuvarov commented
Hi @Bartlomiejsz 

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:10 UTC, closed without merging