Catch throwable errors during model save (rollback)
magento/magento2 pull request #32558
Opened 2021-03-20 00:13 UTC by Sekiphp

### Description (*)
When you 

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-20 10:22 UTC, Sekiphp commented
@magento run all tests

2021-03-21 19:12 UTC, swnsma commented
@magento create issue

2021-03-21 19:14 UTC, swnsma requested changes
Hi @Sekiphp!
Thank you for your contribution!
According to our Definition of Done, all new changes should be covered with corresponding auto-tests.
May I ask you to add unit-tests coverage for this specific case?

2021-05-04 23:18 UTC, Sekiphp commented
@swnsma I tried to add unit test, but I usually using another testing framework and I had problem to make this test working. Can you please give me some suggestion what to edit/fix in this tests? Thank you!

2021-06-24 11:00 UTC, ihor-sviziev commented
@magento run all tests

2022-10-13 15:17 UTC, ishakhsuvarov commented
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:17 UTC, closed without merging

2023-02-19 23:21 UTC, Sekiphp commented
@ishakhsuvarov Can you please reopen this pull request? Automated tests are already written....