#32367 GraphQL: Order item should contain parent sku
magento/magento2 pull request #32588
Opened 2021-03-24 15:16 UTC by khrystynastolbova

### Description (*)

 Order item contain parent_sku

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32367

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-25 09:42 UTC, khrystynastolbova commented
@magento run all tests

2021-03-26 05:30 UTC, eduard13 commented
@magento run WebAPI Tests, Unit Tests, Integration Tests

2021-03-26 05:39 UTC, eduard13 requested changes
Hi @khrystynastolbova, thank you for the provided implementation. Could you please also provide a test case for a bundle and configurable product as parent products?

Thank you.

2021-03-31 13:54 UTC, khrystynastolbova commented
@magento run all tests

2021-04-30 15:03 UTC, eduard13 commented
@magento run Functional Tests B2B, Integration Tests

2021-05-10 13:55 UTC, cpartica approved these changes

2021-05-11 15:46 UTC, eduard13 commented
@magento run WebAPI Tests, Semantic Version Checker, Magento Health Index

2021-05-11 17:25 UTC, eduard13 approved these changes
Great job 👏 .

2021-05-11 17:26 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9081](https://jira.corp.magento.com/browse/ENGCOM-9081) has been created to process this Pull Request

2021-05-11 21:03 UTC, khrystynastolbova commented
@magento run WebAPI Tests, Semantic Version Checker, Magento Health Index

2021-05-11 23:36 UTC, cpartica requested changes

2021-05-11 23:36 UTC, cpartica commented on app/code/Magento/SalesGraphQl/etc/schema.graphqls
> +    parent_sku: String @doc(description: "The SKU of parent product. For simple product parent_sku is null.")
parent_sku should only be included into product types that have a parent_sku as part of a fragment with use of interfaces
example is `type BundleOrderItem implements OrderItemInterface `
referenced in
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/BundleGraphQl/etc/schema.graphqls#L94

so far we have BundleOrderItem, DownloadableOrderItem, GiftCardOrderItem
In your case you have to modify the BundleOrderItem, and we probably need to create one for ConfigurableOrderItem as well

2021-05-19 11:39 UTC, khrystynastolbova commented on app/code/Magento/SalesGraphQl/etc/schema.graphqls
> +    parent_sku: String @doc(description: "The SKU of parent product. For simple product parent_sku is null.")
Hi @cpartica I moved 'parent_sku' to BundleOrderItem. What about ConfigurableOrderItem? Should I add this type? Could you provide a scheme for this?

2021-05-19 14:19 UTC, eduard13 commented on app/code/Magento/SalesGraphQl/etc/schema.graphqls
> +    parent_sku: String @doc(description: "The SKU of parent product. For simple product parent_sku is null.")
Hi @khrystynastolbova, I believe you should be able to add the needed type that implements OrderItemInterface, similar as we have for `BundleOrderItem`, `DownloadableOrderItem` in scope of `ConfigurableProductGraphQl`'s schema.
```
type ConfigurableOrderItem implements OrderItemInterface {
...
}
```
cc. @cpartica

2021-05-20 09:09 UTC, khrystynastolbova commented on app/code/Magento/SalesGraphQl/etc/schema.graphqls
> +    parent_sku: String @doc(description: "The SKU of parent product. For simple product parent_sku is null.")
Hi @eduard13. I added ConfigurableOrderItem type. Please check

2021-05-21 22:08 UTC, cpartica commented on app/code/Magento/SalesGraphQl/etc/schema.graphqls
> +    parent_sku: String @doc(description: "The SKU of parent product. For simple product parent_sku is null.")
that is correct. all product types that need parent sku must have the same type of schema. I think you got it!

2021-05-26 06:43 UTC, khrystynastolbova commented
@magento run WebAPI Tests, Semantic Version Checker, Magento Health Index

2021-05-27 13:39 UTC, khrystynastolbova commented
@magento run WebAPI Tests

2021-05-28 00:07 UTC, Den4ik commented
@magento run all tests

2021-05-28 05:43 UTC, eduard13 commented
@magento run Functional Tests B2B, Functional Tests CE

2021-06-16 09:29 UTC, khrystynastolbova commented
@magento run Functional Tests B2B, Functional Tests CE

2021-06-16 11:44 UTC, Den4ik commented
@magento run all tests

2025-02-11 13:26 UTC, engcom-Bravo commented
Hi @khrystynastolbova,


Adobe Commerce Engineering team started working on this issue. We will reach out to you if we need more information and you will get notified once the issue is fixed. Please leave comments for any further questions.

Thank you!

2025-02-19 06:59 UTC, engcom-Bravo commented
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7917 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-7917&type=commits

Based on the Jira ticket, the target version is 2.4.8.

Thanks

2025-02-19 06:59 UTC, closed without merging