Feature/gtag update
magento/magento2 pull request #32623
Opened 2021-03-29 23:34 UTC by mkadsv

### Description (*)

What Has Changed:
- Google Adwords: added gtag.js library instead of analytics.js library
- Google Adwords: "Conversion ID" field is required (updated UI to display required) and is a string input instead of Int
- Google Adwords: All other fields are optional, updated ui to display optional
- Google Analytics: added gtag.js library instead of analytics.js library
- Google Analytics: Ability to use Google Analytics 4 properties or Universal Analytics Properties by adding a drop down menu to select the account type and Updated "Account Number" to "Measurement Id" if "Google Analytics" is selected and "Tracking Id" if "Universal Analytics" is selected.
- Google Analytics: Anonymize IP will always be true for Google Analytics account type
-  Google Analytics: Removing "add to cart" event because it was being triggered simultaneously with "purchase" event.

Why:
- gtag.js is is used instead of analytics.js to be able to support both legacy "Universal Analytics users and the new Google Analytics 4 property. It allows for easier configuration with Google Ads for conversion tracking.
- The "Tracking ID" input field and "Measurement ID" input field in Google Analytics must be a string since the syntax has changed. (GA-XXXX and UA-XXXX)
- The "Conversion ID" input field in Google Adwords must be a string since the syntax has changed (AW-XXXXX).
- The Add to Cart Event was removed since it was not being triggered correctly.

### Manual testing scenarios (*)

1. If user enables Google Analytics module, they can select from a drop down menu of "Google Analytics 4" or "Universal Analytics".
2. Google Analytics: There will be "page_view" events triggered when a user views any frontend store page 
3. Google Analytics: There will be "purchase" events triggered when a user completes a checkout and lands on success page. 
4. Google Analytics: There will be no add_to_cart event.
5. Google Adwords: when a user completes a purchase there will be a conversion event that occurs.

### Questions or comments

It was noted in the developer guide to not utilize a module inside another module however, since Google Adwords and Google Analytics are tightly coupled and designed to work together. We must break this rule or else the module will not work correctly with Google Analytics and Google Ads as the provider has intended.

### Contribution checklist (*)
 - [* ] Pull request has a meaningful description of its purpose
 - [ *] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [* ] All automated tests passed successfully (all builds are green)

2021-03-30 21:32 UTC, mkadsv commented
@magento run all tests

2021-03-30 23:34 UTC, mkadsv commented
@magento run Magento Health Index

2021-03-30 23:38 UTC, mkadsv commented
@magento give me 2.4-develop instance

2021-03-31 00:14 UTC, mkadsv commented
@magento run all tests

2021-04-01 06:04 UTC, mkadsv commented
@magento run all tests

2021-04-02 18:24 UTC, mkadsv commented
@magento run all tests

2021-04-06 00:10 UTC, mkadsv commented
@magento run all tests

2021-07-16 08:56 UTC, gabrieldagama commented
Hi @mkadsv, can you update your PR branch with the latest 2.4-develop code? Once that is done, can you re-run the tests? In order to proceed with your PR all the tests must be green.

2021-08-16 02:01 UTC, bgorski commented
@magento run all tests

2021-08-22 10:17 UTC, bgorski commented
@magento run all tests

2021-08-22 11:18 UTC, bgorski requested changes
@mkadsv thank you for your contribution! I reviewed it and had a few comments - please take a look. 
Apart from changes requested in comments, please ensure that all your PHP functions have PHP7-style type hints for all parameters and returns, not only docblock annotations.
Additionally, please review your `@api` annotation use and inlude it only if necessary. If I remember correctly, the practical implication of this is that it may not be possible to include bugfixes or improvements to those classes in the same release line (e.g 2.4)

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAdwords/etc/adminhtml/system.xml
> +                    <label>Conversion ID (required)</label>
Please remove `(required)` from here. The convention in Magento is to use validation for this (which you did).

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAdwords/etc/adminhtml/system.xml
> +                    <label>Conversion Language (optional)</label>
Please remove `(optional)` from here. The convention in Magento is not to use label for marking if a field is required or optional. 
If you want to provide more information about a field, like when you'd want to use it and what for, consider utilizing `<comment>` or `<tooltip>` nodes for this purpose.

The same comment applies for all the other fields in this file which were marked as optional in the label.

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAdwords/view/frontend/templates/code.phtml
> +if ($helper->isGoogleAdwordsConfigurable()) {
A few comments here:
1. Please use an alternative syntax for control structures when working with PHP inside of phtml files. So instead of:
```
<?php if ($something) { ?>
html here
<?php } ?>
```
use 
```
<?php if ($something) : ?>
html here
<?php endif ?>
```
This greatly improves readability of html files and is a standard practice in Magento 2.
2. Please include a @var annotation for the `$block` variable
3. Please consider escaping output or marking with `@noEscape` (I think that in both cases escaping would be good)
4. From what I see, you have a top-level PHP `if` statement that allows outputting the script tag and a second-level JS if that is responsible for the only content of that script. So if the 1st if evaluates to true and the 2nd one to false, it would result in an empty script here.

Looks to me that this file should look similarly to this:
```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\GoogleAdwords\Block\Code $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\GoogleAdwords\Helper\Data $helper */
$helper = $block->getHelper();
?>

<?php if ($helper->isGoogleAdwordsConfigurable() && $helper->isGoogleAdwordsActive()) : ?>
    <?php $conversionId = $this->escapeHtml($helper->getConversionId()); ?>
    <?php $conversionLabel = $this->escapeHtml($helper->getConversionLabel()); ?>
    <script>
        gtag('event', 'conversion', {'send_to': '<?= $conversionId ?>' + '/' + '<?= $conversionLabel ?>'});
    </script>
<?php endif ?>
```

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAdwords/view/frontend/templates/head.phtml
> +$helper = $block->getHelper();
Please see my comments above about annotations, escaping and syntax for control structures - they apply here as well.

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/Helper/Data.php
> +        if ($this->isGoogleAnalytics4Account()) {
Please use a null coalescing operator instead

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/Helper/Data.php
> +    public function isGoogleAnalytics4Account()
Please improve formatting of this (and the function below this one as well)

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/Helper/Data.php
> +        if ($this->isGoogleAnalytics4Account()) {
else is not required here. You can go with just `if` or consider a ternary operator.

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/Model/Config/Source/DefaultYes.php
> +        return [
What's the point of having a select field with only one possible value to select?

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/Test/Unit/Block/GaTest.php
> +        echo json_encode($expectedResult);
I think this `echo`, and the `echo` a few lines below was left here by mistake. Please remove them.

2021-08-22 11:18 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/etc/adminhtml/system.xml
> +</config>
new line missing

2021-08-23 10:01 UTC, Den4ik requested changes

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Block/Head.php
> + * @since 100.0.2
Why you marked this class as `@api`. I think marking class as `@api` should be approved by architect team.
**cc** @gabrieldagama

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Block/Head.php
> + * Google AdWords Code block
Please remove this comment because it's don't contains any useful information. If you want to add some information about class you may add it before class declaration. Copyright block should not contain additional information.

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Block/Head.php
> +    protected $_googleAdwordsData;
Currently Magento don't use underscore at variables and property names

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/view/frontend/layout/checkout_onepage_success.xml
> +      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
Please revert auto reformating

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/view/frontend/templates/code.phtml
> +}
I believe that we can use `if` construction in PHP instead of js.

```
<?php if($helper->isGoogleAdwordsActive()): ?>
    gtag('event', 'conversion', {'send_to': '<?= $helper->getConversionId() ?>' + '/' + '<?= $helper->getConversionLabel() ?>'});
<?php endif ?>
```

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Block/Head.php
> +<?php
All new classes should have strict type declaration.
`declare(strict_types=1);`

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> +    const DEVELOPER_ID = 'dYjhlMD';
I'm not sure that we should use hardcoded developer id

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Helper/Data.php
>      }
Removing of methods is backward incompatible. Please mark it as @deprecated instead.

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> -    }
Removing of methods is backward incompatible. Please mark it as `@deprecated` instead.

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> +        return (string)$this->scopeConfig->getValue(
Is it really needed to change return type here?

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> +    }
Introducing new methods is backward incompatible and could be released as `MINOR` update

https://devdocs.magento.com/contributor-guide/backward-compatible-development/#php

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAdwords/Test/Unit/Helper/DataTest.php
> -    }
Please mark it as `@deprecated` instead of removing

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAnalytics/Block/Ga.php
> -    }
@gabrieldagama, I think that removing of deprecated methods is ok, but wants to know what Magento team thinking about this

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAnalytics/Model/Config/Source/AccountType.php
> + */
Same as for `app/code/Magento/GoogleAdwords/Block/Head.php`

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAnalytics/Model/Config/Source/DefaultYes.php
> + */
Same as for `app/code/Magento/GoogleAdwords/Block/Head.php`

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAnalytics/Test/Unit/Block/GaTest.php
> -    }
Please mark it as `@deprecated` instead of removing

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAnalytics/etc/adminhtml/system.xml
> -                    <label>Account Number</label>
Removing of fields is backward incompatible and could be released with `MAJOR` update

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAnalytics/view/frontend/layout/default.xml
> +                   template="Magento_GoogleAnalytics::ga.phtml"/>
This file contain only reformatting and should be reverted

2021-08-23 10:01 UTC, Den4ik commented on app/code/Magento/GoogleAnalytics/view/frontend/web/js/google-analytics.js
> +        var DEVELOPER_ID = 'dYjhlMD';
I'm not sure that we should use hardcoded developer id

2021-09-06 12:10 UTC, engcom-Charlie commented
Thank you for everyone's contribution!

@mkadsv , I will work on review comments.

Thank you!

2021-10-13 17:55 UTC, mkadsv commented
@engcom-Charlie thank you for handling the review comments. What is the status so far? If needed I can address the remaining updates needed?

2021-10-14 06:28 UTC, engcom-Charlie commented
Hi @mkadsv,

Thank you for your contribution!

Unfortunately, we are not able to proceed with this issue yet. If you want take care of the review changes you can proceed.

Thank you!

2021-10-22 04:25 UTC, mkadsv commented on app/code/Magento/GoogleAdwords/Block/Head.php
> +<?php
added

2021-10-22 04:46 UTC, mkadsv commented on app/code/Magento/GoogleAdwords/Block/Head.php
> +    protected $_googleAdwordsData;
removed underscore from _googleAdwordsData

2021-10-28 14:18 UTC, Den4ik commented
@magento run all tests

2021-11-09 01:46 UTC, bgorski requested changes
There are still several outstanding change requests. Please address all remaining comments. Thanks!

2021-11-16 22:23 UTC, mkadsv commented
@magento run all tests

2021-11-29 17:06 UTC, mkadsv commented
Hello @bgorski & @Den4ik, any updates on the PR review?

2021-11-29 18:35 UTC, bgorski commented
@mkadsv I didn't have the chance to review yet - sorry! I'll probably be able to do that on Saturday or Sunday.

2021-11-29 18:39 UTC, Den4ik commented
@mkadsv  thanks for the work. I'll check this PR in a few days

2021-11-29 19:36 UTC, bgorski commented
@magento run all tests

2021-12-06 11:26 UTC, bgorski commented
@magento run Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests B2B, Integration Tests, Functional Tests EE, Functional Tests B2B

2021-12-06 19:47 UTC, bgorski requested changes
@mkadsv I re-opened a few convos that I feel are not resolved. Besides what's already commented on, I don't have any comments. The code is looking better, thanks!
However, I see that a lot of automated tests are failing, could you fix them as well?

2021-12-06 19:47 UTC, bgorski commented on app/code/Magento/GoogleAdwords/etc/adminhtml/system.xml
> +                    <label>Conversion ID (required)</label>
Removing the "resolved" mark on this - it's not resolved yet.

2021-12-06 19:47 UTC, bgorski commented on app/code/Magento/GoogleAdwords/Block/Head.php
> +<?php
While @Den4ik added this comment on a single class level, this should apply to all new classes. 

Also, adding `declare(strict_types=1);` on all classes (not only new ones) would also be a plus since a lot of them get considerable changes, although I wouldn't say it's required - up to you.

2021-12-06 19:47 UTC, bgorski commented on app/code/Magento/GoogleAdwords/Helper/Data.php
> +        return (string)$this->scopeConfig->getValue(
Is this resolved? There's no answer here and the type remained changed.

2021-12-06 19:47 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/Model/Config/Source/DefaultYes.php
> +        return [
This is not resolved yet - no answer.

2021-12-16 16:33 UTC, bgorski commented
@magento run all tests

2022-01-12 22:19 UTC, mkadsv commented
@magento run all tests

2022-01-13 21:24 UTC, mkadsv commented
@bgorski & @Den4ik - Hello there, happy new year! The reason why some tests are still failing is because I was told to not remove outdated methods but instead to annotate them as deprecated [(reference to deprecation annotation comment)](https://github.com/magento/magento2/pull/32623#discussion_r693821340). I did this for the unit tests as well. Is this okay?

All comments have been addressed.

2022-01-14 09:32 UTC, Den4ik commented
Hi @mkadsv.
Thanks for the comment.
It's correct to deprecate old methods instead of removing them

2022-01-15 13:13 UTC, bgorski commented
However, according to the Magento 2 Coding Standard, use of `trigger_error()` is discouraged (https://github.com/magento/magento-coding-standard/blob/v17/Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php#L139). So while it may be tempting to use it, we should limit ourselves to just the `@deprecated` annotation. This way tests will pass (unless there are other reasons for them not to). There's more business value in having tests even for deprecated methods for as long as they're not entirely removed, than in having a more visible deprecation.

@mkadsv can you remove lines of code that use `trigger_error()` please?

2022-01-21 16:36 UTC, sidolov commented
@magento run all tests

2022-01-21 17:04 UTC, mkadsv commented
@bgorski - as per slack convo, I have removed `trigger_error` functions since they are not compatible with Magento 2 Coding Standard.
I'm looking into the other unit tests failures

2022-01-24 15:22 UTC, sidolov commented
@magento run all tests

2022-01-29 16:44 UTC, bgorski commented on app/code/Magento/GoogleAnalytics/Block/Ga.php
> -    }
@sidolov Gabriel is not part of the team anymore, could you answer @Den4ik's question?

2022-01-29 18:09 UTC, bgorski commented
@magento run Integration Tests, Sample Data Tests B2B, Sample Data Tests EE

2022-02-04 10:36 UTC, bgorski commented
@magento run Sample Data Tests B2B, Sample Data Tests EE

2022-02-16 08:46 UTC, bgorski commented
@magento run Sample Data Tests B2B, Sample Data Tests EE

2022-03-14 14:50 UTC, bgorski commented
@magento run all tests

2022-03-14 20:16 UTC, bgorski commented
Not sure why it has been set to Progress: Review. Should be Progress: Needs Update. Setting the correct status now.

2022-04-26 07:24 UTC, oefterdal commented
Any progress on this issue?

2022-05-28 13:22 UTC, sidolov commented
Feature merged on scope of https://github.com/magento/magento2/pull/35376

2022-05-28 13:23 UTC, closed without merging