Fixed assertDefinitionEqual column type test
magento/magento2 pull request #32624
Opened 2021-03-30 06:30 UTC by Nuranto

Solves #32309

`Magento\Framework\Setup\Declaration\Schema\Declaration\ValidationRules\IncosistentReferenceDefinition` has a method `assertDefinitionEqual` that check foreign keys consistency.

The bug was : 

```
        if ($column->getType() !== $referenceColumn->getType()) {
            return true;
        }
```

If the type of foreign key and reference column, it should return false.

Note that the class is not named correctly `IncosistentReferenceDefinition` instead of `IncosistentReferenceDefinition`, but I did not fixed that since I'm not sure about your retrocompatibility policy regarding class name change.

2021-03-30 07:48 UTC, Nuranto commented
@magento run all tests

2021-03-30 10:12 UTC, Nuranto commented
@magento run Functional Tests EE

2021-04-08 16:33 UTC, gabrieldagama commented
Hi @Nuranto, can you provide some steps to reproduce this issue? 

Thanks

2021-04-09 06:32 UTC, Nuranto commented
Hi @gabrieldagama,

Create a table with a FK that has a wrong type, for instance : 

```
<table name="dummy_table" resource="default" engine="innodb" comment="Dummy Table">
                <column xsi:type="int" name="dummy_id" unsigned="true" nullable="false" identity="true" comment="ID" />

                <column xsi:type="decimal" name="product_id" unsigned="true" nullable="false" default="0" comment="Product ID" />

                <constraint xsi:type="primary" referenceId="PRIMARY">
                        <column name="dummy_id" />
                </constraint>

                <constraint xsi:type="foreign" referenceId="DUMMY_FK" 
                        table="dummy_table" column="product_id" 
                        referenceTable="catalog_product_entity" referenceColumn="entity_id" 
                        onDelete="CASCADE" />
        </table>
```

Before fix, you'll have, during `setup:upgrade` : 

```
SQLSTATE[HY000]: General error: 1005 Can't create table `magento2`.`dummy_table` (errno: 150 "Foreign key constraint is incorrectly formed")
```

After the fix, you'll have : 

```
Column definition "product_id" and reference column definition "entity_id" are different in tables "dummy_table" and "catalog_product_entity"
```

2021-04-13 11:17 UTC, swnsma requested changes
Hi @Nuranto!

Thank you for your contribution!

May I ask you to add unit tests which will cover this scenario and (as result) we could prevent similar 'typo' issues in future?
Similar tests could be found: framework/Setup/Test/Unit/Declaration/Schema/ValidationRules

2021-05-06 13:08 UTC, engcom-Foxtrot commented
Hello, @Nuranto. Unfortunately, I'm closing and re-creating this PR, as I was not able to push the test coverage to webcooking:32309 branch. Please feel free to push any updates to https://github.com/magento/magento2/pull/32959.

2021-05-06 13:08 UTC, closed without merging