Mark classes and interfaces as API part 6
magento/magento2 pull request #32681
Opened 2021-04-06 23:24 UTC by mrtuvn

### Description (*)

Marked the following classes and interfaces as API

Magento\Checkout\Model\Type\Onepage
Magento\Framework\Image\AdapterFactory
Magento\Catalog\Model\Config
Magento\Customer\Model\CustomerRegistry
Magento\Quote\Setup\QuoteSetup
Magento\Ui\Component\Control\Container
Magento\Catalog\Model\Layer\Filter\Item

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32675

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-04-07 07:08 UTC, ihor-sviziev commented
@magento run all tests

2021-04-07 07:09 UTC, ihor-sviziev requested changes

2021-04-07 07:09 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Layer/Filter/Item.php
> + * Class \Magento\Catalog\Model\Layer\Filter\Item
Please remove this line, it's absolutely useless

2021-04-07 07:09 UTC, ihor-sviziev commented on app/code/Magento/Checkout/Model/Type/Onepage.php
> + * Class \Magento\Checkout\Model\Type\Onepage
Please remove this line, it's absolutely useless

2021-04-07 14:08 UTC, ihor-sviziev commented
@magento run all tests

2021-04-08 01:33 UTC, mrtuvn commented
@magento run Unit Tests

2021-04-08 02:51 UTC, ihor-sviziev requested changes
Please fix failing unit tests

2021-04-08 07:35 UTC, mrtuvn commented
Seem we have issue in this line after add strict_type
https://github.com/magento/magento2/blob/3f89f034f1b9792f66b3364623ee4a512a286e58/app/code/Magento/Catalog/Model/Config.php#L403

2021-04-08 09:33 UTC, ihor-sviziev commented
@mrtuvn I believe it's better to revert adding strict  type for this file if it's introducing some issues

2021-04-08 09:34 UTC, ihor-sviziev requested changes

2021-04-08 09:34 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Config.php
> +declare(strict_types=1);
```suggestion
```

2021-04-08 10:00 UTC, mrtuvn commented on app/code/Magento/Catalog/Model/Config.php
> +declare(strict_types=1);
i have reverted that too

2021-04-08 10:00 UTC, mrtuvn commented
@magento run all tests

2021-04-08 11:11 UTC, ihor-sviziev approved these changes

2021-04-08 11:13 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8994](https://jira.corp.magento.com/browse/ENGCOM-8994) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-04-10 22:10 UTC, mrtuvn commented
@magento run Functional Tests CE

2021-04-13 09:28 UTC, gabrieldagama commented
@magento import pr to magento-engcom/magento2ce

2021-04-13 09:31 UTC, gabrieldagama commented
@magento import pr to https://github.com/magento-engcom/magento2ce

2021-04-13 09:32 UTC, gabrieldagama commented
@magento import code to https://github.com/magento-engcom/magento2ce

2021-04-13 09:32 UTC, magento-engcom-team commented
@gabrieldagama the pull request successfully imported.

2021-04-13 09:33 UTC, magento-engcom-team commented
@gabrieldagama, an error occurred during the Pull Request import.

2021-04-13 09:34 UTC, magento-engcom-team commented
@gabrieldagama, an error occurred during the Pull Request import.

2021-04-13 15:10 UTC, merged