Replace repetitive actions with Action Groups in NewProductsListWidgetTest
magento/magento2 pull request #32702
Opened 2021-04-09 13:44 UTC by kate-kyzyma

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-04-09 13:45 UTC, kate-kyzyma commented
@magento run all tests

2021-04-12 06:20 UTC, kate-kyzyma commented
@magento run Functional Tests EE

2021-04-14 08:22 UTC, eduard13 requested changes
Hi @kate-kyzyma, could you please check the minor suggestions below?

Thank you for your input.

2021-04-14 08:22 UTC, eduard13 commented on app/code/Magento/Cms/Test/Mftf/ActionGroup/AdminExpandContentSectionActionGroup.xml
> +        <waitForPageLoad stepKey="waitForSeoSection"/>
```suggestion
        <waitForPageLoad stepKey="waitForContentSection"/>
```

2021-04-14 08:22 UTC, eduard13 commented on app/code/Magento/Cms/Test/Mftf/ActionGroup/AdminExpandSeoSectionActionGroup.xml
> +        <waitForPageLoad stepKey="waitForContentSection"/>
```suggestion
        <waitForPageLoad stepKey="waitForSeoSection"/>
```

2021-04-14 08:22 UTC, eduard13 commented on app/code/Magento/Widget/Test/Mftf/Test/NewProductsListWidgetTest.xml
> +        <actionGroup ref="SaveCmsPageActionGroup" stepKey="clickSaveCmsPage" />
```suggestion
        <actionGroup ref="SaveCmsPageActionGroup" stepKey="clickSaveCmsPage"/>
```

2021-04-14 08:23 UTC, eduard13 commented
@magento create issue

2021-04-15 06:23 UTC, kate-kyzyma commented
Hi @eduard13!

I have fixed mentioned issues. Please, check.

2021-04-15 06:23 UTC, kate-kyzyma commented
@magento run all tests

2021-04-15 06:57 UTC, closed without merging