Enhanced counter-label to show item or items
magento/magento2 pull request #32722
Opened 2021-04-13 10:19 UTC by ZIPITRO

### Description (*)
Adding one item to your cart gives you 1 items in cart
![luma-2 4-develop-1-item](https://user-images.githubusercontent.com/22952492/114537287-b3a72f00-9c5a-11eb-86c2-265699e11319.png)

Adding more items in your cart it gives 2 items in cart
![luma-2 4-develop-2-items](https://user-images.githubusercontent.com/22952492/114537308-b86be300-9c5a-11eb-8069-8897af2d6b97.png)

Issue 29920(which is closed) didn't fix the counter label.

By enhancing the KO* code in minicart.phtml you can have 1 item or 2 items

### Related Pull Requests

### Fixed Issues (if relevant)
1. magento/magento2/#29920

### Manual testing scenarios (*)
1. Add product to cart
2. Counter label shows items instead of item
3. Add another product to cart
4. Counter label shows items, which is good

### Questions or comments
In the vanilla Luma theme its not shown, but with custom templates, the label is used.

2021-04-13 10:31 UTC, ZIPITRO commented
@magento give me test instance

2021-04-13 10:41 UTC, ZIPITRO commented
Fixed the label

1 item
![2 4-develop-fix-ok-item](https://user-images.githubusercontent.com/22952492/114540128-d9820300-9c5d-11eb-88a0-88d2dfdd4cb7.png)
2 items
![2 4-develop-fix-ok-items](https://user-images.githubusercontent.com/22952492/114540150-de46b700-9c5d-11eb-85ec-563356c91996.png)

2021-04-13 10:42 UTC, ZIPITRO commented
@magento run all tests

2021-04-13 13:29 UTC, ZIPITRO commented
@magento run Functional Tests EE

2021-04-13 14:17 UTC, mrtuvn commented
i thought this problem already fixed in other ticket ? Why it's still reveal again
https://github.com/magento/magento2/pull/29923/files

2021-04-13 14:34 UTC, ZIPITRO commented
> i thought this problem already fixed in other ticket ? Why it's still reveal again
> https://github.com/magento/magento2/pull/29923/files

Hi! Cause the counter label never got fixed and would like to see this fixed

2021-04-13 20:15 UTC, ZIPITRO commented
@magento run WebAPI Tests

2021-04-14 01:17 UTC, mrtuvn commented
Ahh i see you right! But seem current it's never show in frontend

2021-04-14 07:08 UTC, ZIPITRO commented
> Ahh i see you are right! But seem current your code change it's never show in frontend visible for user!

Morning! Thanks for your reply! True, not in Luma and many more templates, but in Argento for example they use this label theme site : argentotheme.com, would be good to see it fixed.

2021-04-14 08:23 UTC, mrtuvn commented
@magento run WebAPI Tests, Functional Tests EE

2021-04-14 10:38 UTC, ZIPITRO commented
WebAPI Tests failed : Error in fixture: "\/var\/www\/html\/dev\/tests\/integration\/testsuite\/Magento\/CatalogStaging\/_files\/disabled_simple_product_staged_for_changes.php".
 URL key for specified store already exists. Something in de develop branch that needs to be updated?

2021-04-14 10:52 UTC, mrtuvn commented
Maybe it's not related with your changes

2021-04-14 11:11 UTC, ZIPITRO commented
@mrtuvn Will check, thanks for answering! I suppose its not related to my changes, but will check :-)

2021-04-14 12:13 UTC, ZIPITRO commented
@magento run WebAPI Tests

2021-04-14 14:25 UTC, ZIPITRO commented
There was 1 error:

1) Magento\Catalog\Api\ProductRepositoryInterfaceTest::testCreateWithNonDefaultStoreWebsite
SoapFault: Backend fetch failed

/var/www/html/vendor/laminas/laminas-soap/src/Client.php:1032
/var/www/html/vendor/laminas/laminas-soap/src/Client/Common.php:54
/var/www/html/vendor/laminas/laminas-soap/src/Client.php:1165
/var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Soap.php:55
/var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:180
/var/www/html/dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductRepositoryInterfaceTest.php:1544
/var/www/html/dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductRepositoryInterfaceTest.php:395

ERRORS!

Don't get it, this has in my opinion not much to do with this ko adjustment, will update branch help you think?

2021-04-14 19:31 UTC, ZIPITRO commented
@magento run WebAPI Tests

2021-04-14 22:49 UTC, mrtuvn commented
Can you change markup alignment of if (ko) block ? Current the last if block seem not alignment with the first

2021-04-15 06:09 UTC, ZIPITRO commented
> Can you change markup alignment of if (ko) block ? Current the last if block seem not alignment with the first

Morning, sure I will change that, no problem!

2021-04-15 08:39 UTC, mrtuvn commented
@magento run all tests

2021-04-15 11:25 UTC, ZIPITRO commented
@magento run Integration Tests,Functional Tests EE,Functional Tests B2B

2021-04-15 14:38 UTC, ZIPITRO commented
@mrtuvn I fixed the alignment, not all checks did succeed, something I need to do? Thanks! Have a great day!

2021-04-15 16:54 UTC, ZIPITRO commented
@magento run Functional Tests B2B

2021-04-15 21:01 UTC, mrtuvn commented
@magento run Integration Tests, Functional Tests EE

2021-04-15 22:51 UTC, mrtuvn commented
@magento run Integration Tests, Functional Tests B2B

2021-04-16 09:20 UTC, ihor-sviziev commented
@mrtuvn looks good to me, but it should be p3 or even p4 prio

2021-04-16 14:28 UTC, mrtuvn commented
already set P3 prior
@magento run Integration Tests

2021-04-17 04:07 UTC, mrtuvn commented
@magento run Integration Tests

2021-04-18 10:17 UTC, ZIPITRO commented
> @magento run Integration Tests

Thanks for your help!

2021-04-28 09:32 UTC, mrtuvn commented
Seem all good at my view

2021-04-28 09:46 UTC, ihor-sviziev approved these changes

2021-04-28 09:47 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9053](https://jira.corp.magento.com/browse/ENGCOM-9053) has been created to process this Pull Request

2021-05-19 12:00 UTC, Den4ik approved these changes

2021-05-19 12:03 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9053](https://jira.corp.magento.com/browse/ENGCOM-9053) has been created to process this Pull Request

2021-09-17 05:05 UTC, vovayatsyuk requested changes
How about reducing code duplication and change one line only?

`<!-- ko i18n: getCartParam('summary_count') > 1 ? 'items' : 'item' --><!-- /ko --> `

2021-09-17 10:20 UTC, Den4ik commented
> How about reducing code duplication and change one line only?
> 
> `<!-- ko i18n: getCartParam('summary_count') > 1 ? 'items' : 'item' --><!-- /ko --> `

@vovayatsyuk You were missed that `0` value is not rendering. Your suggestion will render `0` value

2021-09-17 10:29 UTC, Den4ik approved these changes

2021-09-17 10:30 UTC, Den4ik commented
@magento run all tests

2021-09-17 10:31 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9053](https://jira.corp.magento.com/browse/ENGCOM-9053) has been created to process this Pull Request

2021-09-17 10:39 UTC, ihor-sviziev approved these changes

2021-09-17 10:40 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9053](https://jira.corp.magento.com/browse/ENGCOM-9053) has been created to process this Pull Request

2021-09-17 10:49 UTC, vovayatsyuk approved these changes

2024-01-15 06:17 UTC, engcom-Delta commented
Hi @ZIPITRO, Please clear the conflicts to move further in this PR

2024-01-15 10:09 UTC, vovayatsyuk commented
Hi,

[My advice](https://github.com/magento/magento2/pull/32722#pullrequestreview-757065593) wasn't correct, sorry. We need to keep old code here:

```html
<!-- ko if getCartParam('summary_count') == 1 -->
    <!-- ko i18n: 'item' --><!-- /ko -->
<!-- /ko -->
<!-- ko if getCartParam('summary_count') > 1 -->
    <!-- ko i18n: 'items' --><!-- /ko -->
<!-- /ko -->
```

The new code won't work correctly (see the sandbox: https://regex101.com/r/AcRmVL/1) because Magento collects js phrases using [regex patterns](https://github.com/magento/magento2/blob/HEAD/app/code/Magento/Translation/etc/di.xml#L77C1-L83): 

```xml
<item name="i18n_translation" xsi:type="string"><![CDATA[~(?:i18n\:|_\.i18n\()\s*(["'])(.*?)(?<!\\)\1~]]></item>
```

2024-02-08 06:26 UTC, engcom-Delta commented
Hi @ZIPITRO , Thanks for your contribution.Please resolve the conflicts to move ahead on this PR

2024-02-12 11:18 UTC, engcom-Delta requested changes
Please resolve the conflicts on this PR

2024-10-23 11:13 UTC, engcom-Dash commented
Closing this PR since it has not been updated for a long time. Please feel free to reopen it if needed.

2024-10-23 11:13 UTC, closed without merging