Reinstate disposition header for email messages
magento/magento2 pull request #32720
Opened 2021-04-12 18:28 UTC by fredden

### Description (*)
This pull request reverts the work-around introduced temporarily as part of #25076 and changes the minimum required version of upstream package `laminas/lamnias-mail` to fix the actual problem identified in #25076. External package has already been updated to fix the bug in https://github.com/magento/magento2/commit/5498e7613e51288184f1c1e5a6368544efa4b7bb.

### Related Pull Requests

- Not strictly a pull request, but related commit that was added without a pull request: https://github.com/magento/magento2/commit/6976aabdfdab91a9d06e412c2ed619538ed034b6 / see https://github.com/magento/magento2/issues/25076#issuecomment-558339798

### Fixed Issues (if relevant)
- Fixes https://github.com/magento/magento2/issues/25076
- Fixes https://github.com/magento/magento2/issues/29258

### Manual testing scenarios (*)
1. Generate an email from Magento (eg, new user welcome, sale order success)
2. Observe headers in email

### Questions or comments
*None*

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-04-12 18:29 UTC, fredden commented
@magento run all tests

2021-04-13 06:15 UTC, ihor-sviziev requested changes

2021-04-13 06:15 UTC, ihor-sviziev commented on composer.json
> +        "laminas/laminas-mail": "^2.11.0",
Hi @fredden,
Could you update laminas/laminas-mail in the Magento framework to fix static test failure:
https://github.com/magento/magento2/blob/2cbb4e6557139340cbeb5c0773fb078f41cfcc6e/lib/internal/Magento/Framework/composer.json#L31
Thank you!

2021-04-13 21:07 UTC, fredden commented
@magento run all tests

2021-04-14 06:09 UTC, ihor-sviziev requested changes
In general, looks good, but now the conflict appeared, also there still static test failures caused by different dependencies in the b2b and/or ee versions. Could you check that?

2021-04-14 22:36 UTC, fredden commented
@magento run all tests

2021-04-14 22:39 UTC, fredden commented
@magento run static tests

2021-04-14 22:39 UTC, fredden commented
@magento run Static Tests

2021-04-15 18:02 UTC, fredden commented
@magento run Static Tests

2021-04-15 18:06 UTC, fredden commented
@magento run all tests

2021-04-15 21:56 UTC, ihor-sviziev commented
@magento run Integration Tests, WebApi Tests

2021-04-15 21:56 UTC, ihor-sviziev commented
@magento run WebAPI Tests

2021-04-16 03:20 UTC, ihor-sviziev approved these changes

2021-04-16 03:21 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-04-16 03:21 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9023](https://jira.corp.magento.com/browse/ENGCOM-9023) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-04-19 06:02 UTC, ihor-sviziev commented
@magento run Integration Tests

2021-04-19 10:40 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 

:x: **Before:**
"Content-Disposition: inline" header is not present at all.

:heavy_check_mark: **After:**
![Screenshot from 2021-04-19 13-38-54](https://user-images.githubusercontent.com/60198413/115223674-bd2a0e80-a114-11eb-94c3-953b1b1614c9.png)

2021-04-27 06:30 UTC, ihor-sviziev commented
Moved back to the correct status.

2021-05-05 14:14 UTC, ihor-sviziev commented
Moving back to "accept" status. It looks like it was moved by some mistake.

2021-05-05 18:02 UTC, fredden commented
@magento run all tests

2021-05-06 05:25 UTC, ihor-sviziev commented
Moving back to "accept" status. It looks like it was moved by some mistake.

2021-05-06 08:52 UTC, ihor-sviziev commented
@magento run Functional Tests CE

2021-05-06 08:53 UTC, ihor-sviziev commented
@sidolov @sivaschenko @gabrieldagama,
The bot is constantly moving this PR from "accept" to "ready for testing". Could you take a look into it?

2021-06-04 16:22 UTC, ihor-sviziev requested changes
@fredden, could you resolve the merge conflict? 
That's the reason this PR isn't going forward.

Thank you!

2021-06-08 07:38 UTC, ihor-sviziev commented
@magento run all tests

2021-06-09 03:46 UTC, ihor-sviziev approved these changes

2021-06-09 03:47 UTC, ihor-sviziev commented
The changes were only in the hash parameter of composer.lock file, so it won’t affect the functionality. Moving back to accept status

2021-06-09 03:47 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9023](https://jira.corp.magento.com/browse/ENGCOM-9023) has been created to process this Pull Request

2021-09-07 14:00 UTC, engcom-Alfa commented
Hi @ihor-sviziev , @fredden 
Thanks for the contribution!
I tried to reproduce utilizing outlook and could not successfully reproduce the case.
Trying to work on MS Exchange server, and will post here for any further updates!

2021-09-08 07:36 UTC, engcom-Alfa commented
Hi @fredden, @ihor-sviziev 
Thanks for the collaboration & contribution!

:x: QA not Passed

Disposition header is missing in the welcome/sales notification mails

**Manual Scenario Steps**

1. Set the mail magepal gmail smtp in Magento installed instance.
2. Do create a new customer/ place an order.
3. 3. Check the mail body in the web-outlook.


**:heavy_check_mark: Expected result After Fix** 
- Content-disposition should be included


**:x: Actual result After Fix** 
- Content-disposition still not included
- ![image](https://user-images.githubusercontent.com/51679138/132466305-28310906-1e66-46d4-803a-2b7ae2507fbe.png)

Additionally I am unable to test with MS Exchange Server, but anyhow, I am unable to see the Content-Disposition in the mail DOM.

2021-09-08 08:50 UTC, ihor-sviziev commented
@engcom-Alfa, are you sure that this too shows the original email headers?

2021-09-08 10:15 UTC, engcom-Alfa commented
Hi @ihor-sviziev Thanks for discussing with me more on this issue. That helped me in taking decision!

2021-09-08 10:40 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Should have a Magento instance installed with mailing configured

**Manual testing scenario:**

1. Do create a new customer/ place an order.

2. Check the mail body in the web-outlook (show original).


**Before:** :heavy_multiplication_x: Content-disposition was missing

**After:** :heavy_check_mark:  Content-disposition is visible as shown in below screenshot.
- ![image](https://user-images.githubusercontent.com/51679138/132491956-79d49419-ad3f-49e2-bdca-8a24c9afefd5.png)


There is no other additional testing is required and there is no impact on any other feature as well.

2021-09-13 18:55 UTC, sdzhepa commented
@magnto run all tests

2021-09-13 18:58 UTC, sidolov commented
@magnto run all tests

2021-09-13 18:58 UTC, sidolov commented
@magento run all tests

2021-09-14 13:55 UTC, ihor-sviziev commented
@magento run all tests

2021-09-14 13:55 UTC, ihor-sviziev commented
@sidolov, could you move this PR to "accept" again?

2021-09-14 17:56 UTC, sdzhepa approved these changes

2021-09-16 15:07 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2021-10-07 16:18 UTC, sidolov commented
@fredden could you please resolve merge conflict? Thanks!

2021-10-07 17:39 UTC, fredden commented
@magento run all tests

2021-10-14 10:14 UTC, engcom-Alfa commented
@magento run all tests

2021-10-18 10:12 UTC, engcom-Alfa commented
@magento run Functional Tests CE, Functional Tests EE, Static Tests, Unit Tests, WebAPI Tests

2021-10-18 12:28 UTC, engcom-Alfa commented
@magento run Functional Tests CE, Functional Tests EE, Static Tests, Unit Tests

2021-10-18 14:15 UTC, engcom-Alfa commented
@magento run Static Tests

2021-10-18 15:12 UTC, engcom-Alfa commented
@magento run Static Tests

2021-10-18 15:17 UTC, engcom-Alfa commented
@magento run Static Tests

2021-10-18 15:23 UTC, engcom-Alfa requested changes
@fredden thanks for your contribution and collaboration!
The testing has be done as per [above-comment](https://github.com/magento/magento2/pull/32720#issuecomment-915123737).
There are some merge conflicts needs to be corrected. Hence moving it to _Changes Requested_
Kind request to resolve conflicts; Thanks in advance!

2021-10-18 16:32 UTC, ihor-sviziev commented
@andrewbess any thoughts on why static tests are failing?

2021-10-21 06:08 UTC, ihor-sviziev commented
@magento run all tests

2021-10-21 20:56 UTC, ihor-sviziev commented
@fredden
FYI the changes from this PR were already merged to 2.4-develop branch in https://github.com/magento/magento2/commit/4a125b0b887e7f2cf380dbc3eae122eb736447eb except the latest merge commit. As a result, the pull request wasn't marked as merged.
@sidolov will work on it to mark it as fully merged

2021-10-24 04:27 UTC, merged