Load resizable jquery-ui chunk for knockout resizable binding only when actually used
magento/magento2 pull request #32756
Opened 2021-04-15 13:25 UTC by martasiewierska

### Description (*)

Resizable knockout binding is hardly us on the frontend, it also does not work there (see https://github.com/magento/magento2/issues/32753) As we are constantly often struggling to reduce unused javascript and improve performance metrics for our shops I would like to add this small step to remove not used javascript.

### Manual testing scenarios (*)

1. Create empty page without any other component that require _jquery/ui-modules/resizable.js_
2. Check if _jquery/ui-modules/resizable.js_ file is not loaded in Network tab (no js bundling)
3. Create test UIComponent with resizable knockout binding
4. Check if _jquery/ui-modules/resizable.js_ file is loaded in Network tab (no js bundling)

### Questions or comments

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [x ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ x] All automated tests passed successfully (all builds are green)

2021-04-15 13:43 UTC, ptylek commented
Looks good to me. Let's wait for test results.
@magento run all tests

2021-04-15 21:43 UTC, mrtuvn commented
@magento run Functional Tests B2B,  Functional Tests CE, Functional Tests EE

2021-04-16 09:34 UTC, ihor-sviziev commented
@mrtuvn, I believe it would be too hard to cover these changes with any test. I prefer not to cover it. What do you think?

2021-04-16 09:34 UTC, ihor-sviziev requested changes

2021-04-16 09:34 UTC, ihor-sviziev commented on app/code/Magento/Ui/view/base/web/js/lib/knockout/bindings/resizable.js
> +                if($.fn.resizable) {
```suggestion
                if ($.fn.resizable) {
```

2021-04-16 09:59 UTC, ihor-sviziev commented
@magento run all tests

2021-04-16 11:46 UTC, mrtuvn commented
ihor Ok let's see final test

2021-04-16 14:06 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests

2021-04-17 20:18 UTC, ptylek commented
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

2021-04-19 06:00 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2021-04-19 11:09 UTC, ihor-sviziev approved these changes

2021-04-19 11:23 UTC, ptylek approved these changes

2021-04-27 11:29 UTC, dmitriyprime commented
:heavy_check_mark:  QA passed

2021-05-05 14:12 UTC, ihor-sviziev commented
Moving this PR back to "accept" status...

2021-06-25 13:13 UTC, merged