[MFTF] add StorefrontGiftMessageForOrderOnCheckoutCartPageTest
magento/magento2 pull request #32792
Opened 2021-04-20 10:26 UTC by Usik2203

### Description (*)

This PR adds `StorefrontGiftMessageForOrderOnCheckoutCartPageTest` 
1. allow gift message for order
2. add product to cart 
3. go to cart page
4. input gift message for order 
5. check gift message  on checkout cart page

2021-04-20 10:27 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE, Functional Tests B2B

2021-04-22 16:47 UTC, gabrieldagama commented
@magento create issue

2021-04-22 16:51 UTC, gabrieldagama requested changes

2021-04-22 16:51 UTC, gabrieldagama commented on app/code/Magento/GiftMessage/Test/Mftf/Test/StorefrontGiftMessageForOrderOnCheckoutCartPageTest.xml
> +        <actionGroup ref="StorefrontFieldGiftMessageCartFormActionGroup" stepKey="fillGiftMessageFields"/>
Can we add few more steps to place the order and check the messages are shown on the admin?

2021-04-26 12:14 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE, Functional Tests B2B

2021-04-29 12:24 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE, Functional Tests B2B

2021-04-29 12:24 UTC, Usik2203 commented
@magento give me 2.4-develop instanc

2021-04-29 12:25 UTC, Usik2203 commented
@magento give me 2.4-develop instance

2021-05-12 07:08 UTC, Usik2203 commented
@magento run Functional Tests CE , Functional Tests EE, Functional Tests B2B

2021-05-28 10:51 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-31 07:52 UTC, Usik2203 commented
@magento run all tests

2021-06-22 12:24 UTC, Usik2203 commented
@magento run all tests

2021-09-01 07:33 UTC, engcom-Charlie commented
Hi @Usik2203,

Thanks for your contribution!

I am working on the requested changes mentioned by @gabrieldagama

2021-09-01 10:48 UTC, engcom-Charlie commented
@gabrieldagama, It seems that the test case has been modified as per your review comments by adding few Action groups and Section in test case. 

The modified test case is running fine so moving it for review.

2021-10-14 19:02 UTC, sidolov commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2021-10-15 17:32 UTC, sidolov commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2021-10-18 17:49 UTC, sidolov commented
@magento run Functional Tests EE

2021-10-20 20:43 UTC, sidolov approved these changes

2021-11-04 21:06 UTC, merged