Do not trigger url rewrites re-generation for all store views
magento/magento2 pull request #32808
Opened 2021-04-21 16:19 UTC by ihor-sviziev

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-04-21 16:19 UTC, ihor-sviziev commented
@magento run all tests

2021-04-22 07:10 UTC, ihor-sviziev commented
@magento run Functional Tests EE, WebAPI Tests

2021-04-22 16:27 UTC, gabrieldagama commented
Hi @ihor-sviziev, thanks for contributing! Can you provide more details on the impact of this fix? Thanks!

2021-04-23 22:45 UTC, ihor-sviziev commented
@magento run all tests

2021-04-23 23:23 UTC, ihor-sviziev commented
Hi @gabrieldagama,
I updated the PR description

2021-04-24 13:14 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-04-27 21:04 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-04-29 16:34 UTC, gabrieldagama commented
@magento run Functional Tests B2B

2021-05-05 19:19 UTC, Den4ik commented
@magento create issue

2021-05-05 19:27 UTC, Den4ik commented
@ihor-sviziev Thanks for collaboration and detailed description.
Do we really need save group 2 times at https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/Config/Importer/Processor/Create.php#L187-L193 ?

2021-05-06 03:15 UTC, ihor-sviziev commented
@Den4ik, in theory, we might change it, but I don't know why it was done in this way and wonder if it would cause some regression. Also, potentially, there might be similar code in some other piece or custom extension with the same behavior. My current changes fix all cases at once, so should cover all cases

2021-05-06 09:49 UTC, Den4ik commented
@ihor-sviziev May be we could little bit research and if it's possible reduce count of save calls that will have a positive effect on performance?

2021-05-06 10:21 UTC, ihor-sviziev commented
@Den4ik, in general, it's a good idea to do such research and get rid of such pieces. But in the case of fixing this issue - that's not relevant  - I won't break any functionality.

2021-05-06 10:36 UTC, Den4ik approved these changes
:heavy_check_mark: Approve. All looks good for me.
As we discussed in Slack research should be done as separate work.

2021-05-06 10:37 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9074](https://jira.corp.magento.com/browse/ENGCOM-9074) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-09-24 10:27 UTC, engcom-Alfa commented
Hi @ihor-sviziev , @Den4ik 
Thanks for the collaboration & contribution!

:x: QA not Passed

_URL Re-Write regenerates for all the store views_

**Execution steps followed as below**

1. Installed a Magento freshly having PR changes, so by default l have 1 website, 1 store group, 1 store view.
2. Created a 3 categories inside default category and one product for better analysis. Noted the below URL Re Writes table and the data of the table is below:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MANJUN~1.KS/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MANJUN~1.KS/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl63
	{color:#303030;
	font-family:"\0022Open Sans\0022";
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	background:white;
	mso-pattern:white none;}
.xl64
	{color:#303030;
	font-family:"\0022Open Sans\0022";
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	background:whitesmoke;
	mso-pattern:whitesmoke none;}
.xl65
	{color:#303030;
	font-family:"\0022Open Sans\0022";
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	background:#E5F7FE;
	mso-pattern:#E5F7FE none;}
.xl66
	{border:.5pt solid windowtext;}
-->
</style>
</head>

<body link="#1155CC" vlink="#1155CC">



ID | Store View | Request Path | Target Path | Redirect Type
-- | -- | -- | -- | --
1 | Main Website      Main Website Store      Default Store View | no-route | cms/page/view/page_id/1 | No
2 | Main Website      Main Website Store      Default Store View | home | cms/page/view/page_id/2 | No
3 | Main Website      Main Website Store      Default Store View | enable-cookies | cms/page/view/page_id/3 | No
4 | Main Website      Main Website Store      Default Store View | privacy-policy-cookie-restriction-mode | cms/page/view/page_id/4 | No
5 | Main Website      Main Website Store      Default Store View | mks1.html | catalog/category/view/id/3 | No
6 | Main Website      Main Website Store      Default Store View | mks1/mks2.html | catalog/category/view/id/4 | No
7 | Main Website      Main Website Store      Default Store View | mks1/mks3.html | catalog/category/view/id/5 | No
8 | Main Website      Main Website Store      Default Store View | mksprod1.html | catalog/product/view/id/1 | No
9 | Main Website      Main Website Store      Default Store View | mks1/mks3/mksprod1.html | catalog/product/view/id/1/category/5 | No
10 | Main Website      Main Website Store      Default Store View | mks1/mksprod1.html | catalog/product/view/id/1/category/3 | No



</body>

</html>


3. Ran the command _php bin/magento app:config:dump scopes_
4. Created a DB dump
5. Created a new store with new website and store view, setting the same default category. Checked the new store domain is able to open in the front end as shown in the below screenshot.
![image](https://user-images.githubusercontent.com/51679138/134649520-fe43259a-3e12-4b8b-8736-4124457778e2.png)
Where the default main store had the domain with the url _local.prurlrewriteafter.com_, and now the additional store is with _local.prurlrewriteafter.fr_. Both stores front end are working fine.

6. Noted the updated URL Re Write table again and the relevant table data is below
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MANJUN~1.KS/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MANJUN~1.KS/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl63
	{border:.5pt solid windowtext;}
.xl64
	{color:#303030;
	font-family:"\0022Open Sans\0022";
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	background:white;
	mso-pattern:white none;}
.xl65
	{color:#303030;
	font-family:"\0022Open Sans\0022";
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	background:whitesmoke;
	mso-pattern:whitesmoke none;}
.xl66
	{color:#303030;
	font-family:"\0022Open Sans\0022";
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:.5pt solid windowtext;
	background:#E5F7FE;
	mso-pattern:#E5F7FE none;}
-->
</style>
</head>

<body link="#1155CC" vlink="#1155CC">



ID | Store View | Request Path | Target Path | Redirect Type
-- | -- | -- | -- | --
1 | Main Website      Main Website Store      Default Store View | no-route | cms/page/view/page_id/1 | No
2 | Main Website      Main Website Store      Default Store View | home | cms/page/view/page_id/2 | No
3 | Main Website      Main Website Store      Default Store View | enable-cookies | cms/page/view/page_id/3 | No
4 | Main Website      Main Website Store      Default Store View | privacy-policy-cookie-restriction-mode | cms/page/view/page_id/4 | No
5 | Main Website      Main Website Store      Default Store View | mks1.html | catalog/category/view/id/3 | No
6 | Main Website      Main Website Store      Default Store View | mks1/mks2.html | catalog/category/view/id/4 | No
7 | Main Website      Main Website Store      Default Store View | mks1/mks3.html | catalog/category/view/id/5 | No
8 | Main Website      Main Website Store      Default Store View | mksprod1.html | catalog/product/view/id/1 | No
9 | Main Website      Main Website Store      Default Store View | mks1/mks3/mksprod1.html | catalog/product/view/id/1/category/5 | No
10 | Main Website      Main Website Store      Default Store View | mks1/mksprod1.html | catalog/product/view/id/1/category/3 | No
11 | FrenchWebsite      FrenchStore      FrenchStoreView | mks1.html | catalog/category/view/id/3 | No
12 | FrenchWebsite      FrenchStore      FrenchStoreView | mks1/mks2.html | catalog/category/view/id/4 | No
13 | FrenchWebsite      FrenchStore      FrenchStoreView | mks1/mks3.html | catalog/category/view/id/5 | No
14 | FrenchWebsite      FrenchStore      FrenchStoreView | no-route | cms/page/view/page_id/1 | No
15 | FrenchWebsite      FrenchStore      FrenchStoreView | home | cms [...]

2021-09-24 10:28 UTC, engcom-Alfa requested changes
Based on the above comment, moving it back to to _Request Changes_

2021-10-11 14:55 UTC, engcom-Charlie commented
Hi @ihor-sviziev,

Thank you for your contribution!

I am trying to understand and reproduce this issue on my local. Followed below steps but I am getting the same results on 2.4 develop and PR branch.

1. Setup  fresh magento instance
2. Added 2 new sub categories under Default Category. Created 2 products under one sub category and 1 in other. Eg.(Electronics and Cloths are sub categories and lamp, geyser are products under Electronics and t-shirt product is under cloths) 
3. Checked url_rewrite table: total 12 records were present.
4. Execute php bin/magento app:config:dump scopes command 
5. Took Db dump at this stage
6. Added one website, store and view against default category
7. Checked the url_rewrite table again. Now total 18 records were present
8. Executed php bin/magento app:config:dump scopes again
9. Applied the DB dump back to Magento instance from the step 5.
10. Executed php bin/magento setup:upgrade, At this, it asked about “do you want to continue with creating the website” of step 7 , I have opted for Yes option
11. Tried to browse the site again, its accessible and checked url_rewrite table again. Its having 18 records 
12. Executed  php bin/magento app:config:import cmd : Got nothing to import message here

On both the branches ie. on 2.4 develop and on this PR branch, url_rewrite_ids of few records are getting changed after step 9 on, so can you please confirm once and give us some more information on this.

Thank you in advance!

2021-10-11 16:48 UTC, ihor-sviziev commented
Please ping me in slack for further details

On Mon, 11 Oct 2021 at 17:55 Indrani ***@***.***> wrote:

> Hi @ihor-sviziev <https://github.com/ihor-sviziev>,
>
> Thank you for your contribution!
>
> I am trying to understand and reproduce this issue on my local. Followed
> below steps but I am getting the same results on 2.4 develop and PR branch.
>
>    1. Setup fresh magento instance
>    2. Added 2 new sub categories under Default Category. Created 2
>    products under one sub category and 1 in other. Eg.(Electronics and Cloths
>    are sub categories and lamp, geyser are products under Electronics and
>    t-shirt product is under cloths)
>    3. Checked url_rewrite table: total 12 records were present.
>    4. Execute php bin/magento app:config:dump scopes command
>    5. Took Db dump at this stage
>    6. Added one website, store and view against default category
>    7. Checked the url_rewrite table again. Now total 18 records were
>    present
>    8. Executed php bin/magento app:config:dump scopes again
>    9. Applied the DB dump back to Magento instance from the step 5.
>    10. Executed php bin/magento setup:upgrade, At this, it asked about
>    “do you want to continue with creating the website” of step 7 , I have
>    opted for Yes option
>    11. Tried to browse the site again, its accessible and checked
>    url_rewrite table again. Its having 18 records
>    12. Executed php bin/magento app:config:import cmd : Got nothing to
>    import message here
>
> On both the branches ie. on 2.4 develop and on this PR branch,
> url_rewrite_ids of few records are getting changed after step 9 on, so can
> you please confirm once and give us some more information on this.
>
> Thank you in advance!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/32808#issuecomment-940104457>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOJOUMHRSG6W4O6ADQPDPLUGL3H5ANCNFSM43KV2QRQ>
> .
>

2021-10-12 12:56 UTC, engcom-Charlie commented
Hi @ihor-sviziev, Thanks for the information over slack.

@engcom-Alfa, I have tried to reproduce the issue on 2.4 develop with below steps. Some URL rewrites for categories on  stores were re-generated in DB and hence issue is reproducible.

	1.	Setup fresh magento instance
	2.	Added 2 new sub categories under Default Category. Created 2 products under one sub category and 1 in other. Eg.(Electronics and Cloths are sub categories and lamp, geyser are products under Electronics and t-shirt product is under cloths)
	3.	Added 2 websites, 2 stores and 2 store views.
	4.	Checked url_rewrite table: total 24 records were present.
	
![image](https://user-images.githubusercontent.com/51680850/136959630-f79f7ec7-f019-4511-bb2f-436f507f53f5.png)

	5.	Execute php bin/magento app:config:dump scopes command
	6.	Took Db dump at this stage
	7.	Added one website(Spanish), store and view against default category
	8.	Checked the url_rewrite table again. Now total 30 records were present
	
![image](https://user-images.githubusercontent.com/51680850/136959678-1b7a6169-9501-4354-b676-9915024f824e.png)

	9.	Executed php bin/magento app:config:dump scopes again
	10.	Applied the DB dump back to Magento instance from the step 6. 
	11.	Executed php bin/magento setup:upgrade, At this, it asked about “do you want to continue with creating the website Spanish” of step 7 , I have opted for Yes option
	
![image](https://user-images.githubusercontent.com/51680850/136959818-f380f2e9-6f1b-4de1-a8b5-e8e6d9e66c48.png)

	12.	Checked url_rewrite table again. Its having 30 records. Here, check that the url_rewrite_ids of url rewrites were changed. You can see new ids for old records. This is the issue. 

![image](https://user-images.githubusercontent.com/51680850/136959859-6a963829-cc39-43c9-aae9-b7a61e1c99ac.png)


After doing php bin/magento setup:upgrade, the URL rewrites for categories should not be re-generated in this scenario. As the issue exists on mainline so moving this PR further.

Thank you!

2021-10-18 15:28 UTC, engcom-Alfa commented
> Hi @ihor-sviziev, Thanks for the information over slack.
> 
> @engcom-Alfa, I have tried to reproduce the issue on 2.4 develop with below steps. Some URL rewrites for categories on  stores were re-generated in DB and hence issue is reproducible.
> 
> ```
> 1.	Setup fresh magento instance
> 2.	Added 2 new sub categories under Default Category. Created 2 products under one sub category and 1 in other. Eg.(Electronics and Cloths are sub categories and lamp, geyser are products under Electronics and t-shirt product is under cloths)
> 3.	Added 2 websites, 2 stores and 2 store views.
> 4.	Checked url_rewrite table: total 24 records were present.
> ```
> 
> ![image](https://user-images.githubusercontent.com/51680850/136959630-f79f7ec7-f019-4511-bb2f-436f507f53f5.png)
> 
> ```
> 5.	Execute php bin/magento app:config:dump scopes command
> 6.	Took Db dump at this stage
> 7.	Added one website(Spanish), store and view against default category
> 8.	Checked the url_rewrite table again. Now total 30 records were present
> ```
> 
> ![image](https://user-images.githubusercontent.com/51680850/136959678-1b7a6169-9501-4354-b676-9915024f824e.png)
> 
> ```
> 9.	Executed php bin/magento app:config:dump scopes again
> 10.	Applied the DB dump back to Magento instance from the step 6. 
> 11.	Executed php bin/magento setup:upgrade, At this, it asked about “do you want to continue with creating the website Spanish” of step 7 , I have opted for Yes option
> ```
> 
> ![image](https://user-images.githubusercontent.com/51680850/136959818-f380f2e9-6f1b-4de1-a8b5-e8e6d9e66c48.png)
> 
> ```
> 12.	Checked url_rewrite table again. Its having 30 records. Here, check that the url_rewrite_ids of url rewrites were changed. You can see new ids for old records. This is the issue. 
> ```
> 
> ![image](https://user-images.githubusercontent.com/51680850/136959859-6a963829-cc39-43c9-aae9-b7a61e1c99ac.png)
> 
> After doing php bin/magento setup:upgrade, the URL rewrites for categories should not be re-generated in this scenario. As the issue exists on mainline so moving this PR further.
> 
> Thank you!

Hi @ihor-sviziev and @engcom-Charlie , Thanks for collaboration and coming back with proper steps to reproduce it! I am able to work on it now!

2021-10-19 10:13 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed


**Manual testing scenario:**

1. Setup fresh Magento instance

2. Add 2 new sub categories under Default Category. Create 2 products under one created sub category and 1 product in other. 

3. Added 2 websites, 2 stores and 2 store views. Make sure newly created both stores are working fine with their frontend website links.

4. Check _url_rewrite_ table in the database.

5. Execute _php bin/magento app:config:dump scopes_ command

6. Take a DB dump at this stage

7. Add one more new store website(Spanish), store and store view using default category, make sure it is also working

8. Check the _url_rewrite_ table in the DB again. Now total records count will be more (comparing step 4)! Make note of all records.

9. Execute _php bin/magento app:config:dump scopes_ again

10. Apply the DB dump back to Magento instance from the step 6.

11. Execute the _php bin/magento setup:upgrade_ command, At this, it asks about “_do you want to continue with creating the website Spanish_” of step 7; opt for Yes.

12. Check _url_rewrite_ table again. Make note of all records.

13. Compare url_rewrite_ids of _url rewrite_ noted table records from step 8 and step12. (Using diff checker tools would give more clarity)


**Before:** :heavy_multiplication_x: New _url_rewrite_ids_ were getting generated to old records

![image](https://user-images.githubusercontent.com/51679138/137888707-abedb17a-cda3-4b53-a3e0-44d98903f6f4.png)


**After:** :heavy_check_mark:  New _url_rewrite_ids_ are not getting generated to old records, they are retained as it is!

![image](https://user-images.githubusercontent.com/51679138/137888844-695d52d1-eafe-4f81-9024-8d826f8d4968.png)


It is a specific case were the DB dump is involved when we are having multi store views, and has no impact on other features, and hence no additional regression is required on this.

2021-10-28 02:10 UTC, merged