Correct spelling of variables for customer address
magento/magento2 pull request #32815
Opened 2021-04-22 12:40 UTC by fredden

### Description
These two templates are often overridden in child themes. Whenever they're copied over for modification, our code reviews tend to pick up the incorrect spelling of these variables. Let's get these fixed here so we don't have to keep fixing them locally.

### Related Pull Requests

*None*

### Fixed Issues (if relevant)
*None*

### Manual testing scenarios (*)
There are no functional changes in this pull request, so only limited testing will be necessary.
1. Do customer addresses display correctly in the account area of the front end?

### Questions or comments
*None*

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2021-04-22 12:43 UTC, fredden commented
@magento run all tests

2021-04-22 13:04 UTC, ihor-sviziev requested changes

2021-04-22 13:04 UTC, ihor-sviziev commented on app/code/Magento/Customer/view/frontend/templates/address/book.phtml
> +        <?php if ($address = $block->getDefaultBilling()): ?>
It's better not to re-use same variable name 2 times for different values
```suggestion
        <?php if ($defaultBillingaddress = $block->getDefaultBilling()): ?>
```

2021-04-22 13:04 UTC, ihor-sviziev commented on app/code/Magento/Customer/view/frontend/templates/address/book.phtml
> +        <?php if ($address = $block->getDefaultShipping()): ?>
```suggestion
        <?php if ($defaultShippingAddress = $block->getDefaultShipping()): ?>
```

2021-04-22 16:04 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes from this PR.

2021-04-22 16:05 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9031](https://jira.corp.magento.com/browse/ENGCOM-9031) has been created to process this Pull Request

2021-04-22 16:14 UTC, gabrieldagama commented
@magento create issue

2021-11-26 17:43 UTC, fredden commented
@magento run all tests

2022-10-21 11:20 UTC, fredden commented
@magento run all tests

2022-11-04 12:09 UTC, fredden commented
@magento run all tests

2024-09-26 13:48 UTC, engcom-Dash commented
QA is not required for this change since it only updates the variable name.

Builds are failing so moving it to extended testing.

2024-09-26 13:48 UTC, engcom-Dash commented
@magento run all tests

2024-09-27 08:12 UTC, engcom-Dash commented
@magento run all tests

2024-09-27 11:47 UTC, engcom-Dash commented
Moving to merge in progress.
<img width="1789" alt="image" src="https://github.com/user-attachments/assets/f985b574-49cd-432a-b33e-526560e18285">

2025-02-17 11:20 UTC, merged