Import/Export - Fix 'entity values are mixed' exception when no valid data
magento/magento2 pull request #32904
Opened 2021-04-29 15:53 UTC by fredden

### Description
The Import/Export module can operate in two modes: skip errors, stop on error. When configured to skip errors, the import will proceed irrespective of the validation result. When there is no data to import, a exception "entity values are mixed" is thrown. This pull request solves the problem by failing validation in this case.

### Related Pull Requests

### Fixed Issues
1. Fixes https://github.com/firegento/FireGento_FastSimpleImport2/issues/109

### Manual testing scenarios
1. Create an import file with only invalid data (eg, SKUs that don't exist, invalid customer address fields, malformed customer email addresses)
1. Configure the Magento importer to skip validation errors
1. Import the file
1. Without this pull request: validation passes, but the import fails with a message that "entity values are mixed"
1. With this pull request: validation fails with a message saying that "There are no valid rows to import."

### Questions or comments
*none*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-04-29 16:04 UTC, fredden commented
@magento run all tests

2021-04-29 16:09 UTC, gabrieldagama commented
@magento create issue

2021-05-05 21:33 UTC, fredden commented
@magento run all tests

2021-05-07 11:18 UTC, ihor-sviziev requested changes
Please check failing integration tests

2021-05-07 20:36 UTC, Den4ik requested changes
Hi @fredden! Thanks for your contribution.
I believe that extending of `isErrorLimitExceeded` for both situations: `skip` or `stop` errors is better solution.

2021-05-09 13:50 UTC, fredden commented
> I believe that extending of `isErrorLimitExceeded` for both situations: `skip` or `stop` on errors is better solution.

@Den4ik the `ProcessingErrorAggregator` (where `isErrorLimitExceeded()` is found) does not appear to have access to the total row count. How do you suggest this information should be obtained?

2021-05-09 13:53 UTC, fredden commented
@magento run all tests

2021-05-09 17:44 UTC, Den4ik requested changes
> @Den4ik the ProcessingErrorAggregator (where isErrorLimitExceeded() is found) does not appear to have access to the total row count. How do you suggest this information should be obtained?

@fredden You were right and your solution look clear.

2021-05-09 17:44 UTC, Den4ik commented on app/code/Magento/ImportExport/Model/Import.php
> +            $this->addLogComment(__('There are no valid rows to import.'));
```suggestion
            $this->addLogComment(__('There are no valid rows to import.'));
            return false
```

2021-05-09 17:47 UTC, Den4ik commented
@magento run Functional Tests B2B

2021-05-10 20:54 UTC, fredden commented
@magento run all tests

2021-05-11 03:34 UTC, ihor-sviziev commented
@magento run Functional Tests B2B
Looks good to me

2021-05-11 08:28 UTC, Den4ik commented
@magento run Functional Tests B2B

2021-05-11 11:43 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-05-12 00:10 UTC, Den4ik commented
@magento run Functional Tests B2B

2021-05-12 06:04 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests looks not related to changes from this PR.

2021-05-12 06:05 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9084](https://jira.corp.magento.com/browse/ENGCOM-9084) has been created to process this Pull Request

2021-05-12 06:26 UTC, Den4ik commented
@magento run Functional Tests B2B

2021-05-12 12:23 UTC, Den4ik approved these changes
✅ Approved.

Agree with @ihor-sviziev, failed test looks like not related. But one more time

2021-05-12 12:24 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9084](https://jira.corp.magento.com/browse/ENGCOM-9084) has been created to process this Pull Request

2021-05-12 12:24 UTC, Den4ik commented
@magento run Functional Tests B2B

2021-06-22 09:49 UTC, Den4ik commented
@magento run Functional Tests B2B

2022-10-21 11:22 UTC, fredden commented
@magento run all tests

2022-11-04 12:10 UTC, fredden commented
@magento run Functional Tests B2B

2022-12-21 10:50 UTC, engcom-Lima commented
@magento run Functional Tests B2B

2023-06-21 09:32 UTC, engcom-Lima commented
@magento run all tests

2023-06-23 11:11 UTC, engcom-Lima reviewed
Hi @fredden , 

Thanks for the collaboration & contribution!

### :x: QA not Passed

Still, I am getting the same error before and after the PR changes "_Additional data: <div class="messages"><div class=" message message-error error"><div data-ui-id="messages-message-error" >Error in data structure: entity values are mixed</div></div></div>_"

**Manual Scenario Steps**
1. Create an import file with only invalid data (eg, SKUs that don't exist, invalid customer address fields, malformed customer email addresses)
2. Configure the Magento importer to skip validation errors
3. Import the file

**:heavy_check_mark: Expected result After Fix** _Validation fails with a message saying that "There are no valid rows to import."_

**:x: Actual result After Fix** 
<img width="1395" alt="Screenshot 2023-06-23 at 1 17 21 PM" src="https://github.com/magento/magento2/assets/60198022/da69138e-e46d-4075-947b-1026b5674f9f">

Kindly recheck it. If we are missing anything please inform us. 

Thanks

2023-06-28 15:22 UTC, fredden commented
@engcom-Lima please can you confirm what data type you were trying to import, and how the data was invalid? The changes in this pull request should prevent you from getting to the 'import' step when triggered.

2023-07-04 08:23 UTC, engcom-Hotel commented
@magento run all tests

2023-07-05 06:03 UTC, engcom-Hotel approved these changes

2023-07-06 06:19 UTC, engcom-Lima commented
@magento run all tests

2023-07-06 09:28 UTC, engcom-Lima commented
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:*

1. Create an import file with only invalid data (eg, SKUs that don't exist, invalid customer address fields, malformed customer email addresses)
2. Configure the Magento importer to skip validation errors
3. Import the file

**Before:** :heavy_multiplication_x: Import button was displayed.

<img width="1460" alt="Screenshot 2023-07-06 at 12 40 30 PM" src="https://github.com/magento/magento2/assets/60198022/2459adc6-eb5e-4d35-a093-477fb01b16f0">

**Getting error after importing "_Additional data:Error in data structure: entity values are mixed_":**
<img width="1500" alt="Screenshot 2023-06-23 at 4 31 02 PM" src="https://github.com/magento/magento2/assets/60198022/a0ac9d3e-69af-47f2-aef4-07c5065d6e4c">

**After:** :heavy_check_mark:  Now working fine.
_**Import button disappeared because of invalid data**_
<img width="1334" alt="Screenshot 2023-07-06 at 12 40 48 PM" src="https://github.com/magento/magento2/assets/60198022/d53e0e42-d78b-488a-b9d5-5a7a30f77bbc">

<img width="1336" alt="Screenshot 2023-07-06 at 12 58 16 PM" src="https://github.com/magento/magento2/assets/60198022/00a69d58-ccee-49d5-962e-eba12888dce5">
<img width="1327" alt="Screenshot 2023-07-06 at 12 57 06 PM" src="https://github.com/magento/magento2/assets/60198022/76eab9c1-0150-449e-b457-7fb8153475a6">


Builds are failed. Hence, moving this PR to **Extended Testing.**

2023-07-10 02:25 UTC, engcom-Echo commented
@magento run Integration Tests, Functional Tests EE,Functional Tests CE,Functional Tests B2B

2023-07-10 04:14 UTC, engcom-Echo commented
@magento run Integration Tests

2023-07-10 04:25 UTC, engcom-Echo commented
Functional Tests CE, Functional Tests EE and Functional Tests B2B failures are different on last two run on same commit.
Functional Tests CE
Run1
<img width="1329" alt="image" src="https://github.com/magento/magento2/assets/51681435/e48837e8-0ef5-43b9-93ba-65a438c3953e">

Run2
<img width="1310" alt="image" src="https://github.com/magento/magento2/assets/51681435/e71ca6a9-5659-4466-b5d7-0cbbfc12cdaf">


Functional Tests EE
Run1
<img width="1310" alt="image" src="https://github.com/magento/magento2/assets/51681435/52033685-44b5-49bf-8d93-a9a11610f30b">

Run2
<img width="1364" alt="image" src="https://github.com/magento/magento2/assets/51681435/9e615c4c-0b92-475f-aea6-c84d1508f4f0">

Functional Tests B2B
Run1
<img width="1311" alt="image" src="https://github.com/magento/magento2/assets/51681435/3124a496-adb0-4618-ba4d-8586f3d7096c">

Run2
<img width="1347" alt="image" src="https://github.com/magento/magento2/assets/51681435/5551026a-4599-4c91-afaf-1d82bdd88acc">

2023-07-10 06:09 UTC, engcom-Echo commented
@magento run all tests

2023-07-10 08:00 UTC, engcom-Echo commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

2023-07-10 12:13 UTC, engcom-Echo commented
**Integration Tests** failure is not related to PR.
**Functional Tests CE, Functional Tests EE, Functional Tests B2B** failures are different on last two run on same commit.
**Functional Tests CE**
Run1
<img width="1398" alt="image" src="https://github.com/magento/magento2/assets/51681435/aabdec70-a7d8-4e1f-bc8c-336f4acb46d3">

Run2
<img width="1309" alt="image" src="https://github.com/magento/magento2/assets/51681435/9ee3f576-b1bb-4d10-91d7-3a12e35764be">

**Functional Tests EE**
Run1
<img width="1265" alt="image" src="https://github.com/magento/magento2/assets/51681435/91cf191d-35e8-423e-a77f-f92a945c833e">

Run2
<img width="1440" alt="image" src="https://github.com/magento/magento2/assets/51681435/f260736c-03e7-48d9-9ece-c935cb1c310b">

**Functional Tests B2B**
Run1
<img width="1421" alt="image" src="https://github.com/magento/magento2/assets/51681435/8bae7119-28ab-476e-913c-816e6efa3e03">

Run2
<img width="1384" alt="image" src="https://github.com/magento/magento2/assets/51681435/c0f31b4d-3dc6-41de-88c8-7f3cbf4a1f1f">

Hence moving it to `Merge In Progress`

2023-08-31 01:54 UTC, merged