magento/magento2#32309: IncosistentReferenceDefinition wrong check result
magento/magento2 pull request #32959
Opened 2021-05-06 13:04 UTC by engcom-Foxtrot

Re-creation of https://github.com/magento/magento2/pull/32624 as I was unable to push test coverage to original PR.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32309

### Manual testing scenarios (*)

1. Open db_schema.xml and change type for some column with a foreign key (for example, open `app/code/Magento/User/etc/db_schema.xml`, change `user_id` column type to `float`, and remove identity attribute).
2. Run `bin/magento setup:upgrade`.
3. Upgrade should fail with message `Column definition "some_column" and reference column definition "some_other_column" are different in tables "some_table" and "some_other_table"
`

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-05-07 06:25 UTC, ihor-sviziev commented
@magento run all tests

2021-05-07 09:46 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2021-05-07 20:44 UTC, Den4ik requested changes
@engcom-Foxtrot Thanks for the PR.
Looks like I see the typo in function name.

2021-05-07 20:44 UTC, Den4ik commented on dev/tests/setup-integration/testsuite/Magento/Setup/ValidationRulesTest.php
> +    public function testFailOnIncosistentReferenceTypeDefinition()
Did you mean Inco**n**sistent?

2021-05-08 09:26 UTC, swnsma commented on dev/tests/setup-integration/testsuite/Magento/Setup/ValidationRulesTest.php
> +    public function testFailOnIncosistentReferenceTypeDefinition()
```suggestion
    public function testFailOnInconsistentReferenceTypeDefinition()
```

2021-05-12 11:06 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-12 13:40 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-05-12 15:06 UTC, ihor-sviziev approved these changes

2021-05-12 15:07 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9086](https://jira.corp.magento.com/browse/ENGCOM-9086) has been created to process this Pull Request

2021-05-12 16:38 UTC, Den4ik approved these changes
✅ Approved

Thanks for contribution

2021-05-12 16:39 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9086](https://jira.corp.magento.com/browse/ENGCOM-9086) has been created to process this Pull Request

2021-05-12 17:05 UTC, swnsma approved these changes

2021-05-12 17:07 UTC, magento-engcom-team commented
Hi @swnsma, thank you for the review.
[ENGCOM-9086](https://jira.corp.magento.com/browse/ENGCOM-9086) has been created to process this Pull Request

2021-05-12 22:06 UTC, Den4ik commented
@engcom-Foxtrot Just found another one name typo. Could you please rename folder `incosistence_reference_type_definition` and change it in `ValidationRulesTest.php`

2021-05-13 10:46 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-13 10:56 UTC, engcom-Foxtrot commented
@magento run all tests

2021-05-13 13:38 UTC, Den4ik commented
@magento run Functional Tests B2B, Functional Tests EE

2021-05-13 13:39 UTC, Den4ik approved these changes
✅ Approved

2021-05-13 13:41 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9086](https://jira.corp.magento.com/browse/ENGCOM-9086) has been created to process this Pull Request

2021-05-13 18:03 UTC, Den4ik commented
@magento run Functional Tests B2B, Functional Tests EE

2021-05-13 20:12 UTC, ihor-sviziev approved these changes

2021-05-13 20:13 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9086](https://jira.corp.magento.com/browse/ENGCOM-9086) has been created to process this Pull Request

2021-05-17 08:07 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 
1. Open db_schema.xml and change type for some column with a foreign key (for example, open `app/code/Magento/User/etc/db_schema.xml`, change `user_id` column type to `float`, and remove identity attribute).
2. Run `bin/magento setup:upgrade`.
3. Upgrade should fail with message `Column definition "some_column" and reference column definition "some_other_column" are different in tables "some_table" and "some_other_table"

:x: **Before:**
![Screenshot from 2021-05-17 10-28-37](https://user-images.githubusercontent.com/60198413/118453610-15e2cc00-b700-11eb-807f-83875b36ca7e.png)

:heavy_check_mark: **After:**
![Screenshot from 2021-05-17 10-32-38](https://user-images.githubusercontent.com/60198413/118453632-1e3b0700-b700-11eb-954f-c5616515aaab.png)

2021-06-25 13:13 UTC, merged