Support for multiple store views per group
magento/magento2 pull request #33032
Opened 2021-05-18 13:32 UTC by sanderjongsma

### Description (*)
At the moment only the first storeview from the group is supported to use for customer login. This commit will add all store views to the select options.

### Manual testing scenarios (*)
1. Set `Store View To Login To` to `Manual Selection` in Stores -> Configuration -> Customers -> Login as Customer
2. A store view dropdown will appear in the customer view in the backend: 
![image](https://user-images.githubusercontent.com/2726055/118659506-aba85500-b7ed-11eb-9df4-4c618e87735d.png)
3. Without this pull request the drop down will only add the first store view to the dropdown: 
![image](https://user-images.githubusercontent.com/2726055/118659803-ed390000-b7ed-11eb-93c8-c9b62248694d.png)
4. After this pull request the drop down will have all the store views: 
![image](https://user-images.githubusercontent.com/2726055/118660054-21142580-b7ee-11eb-9fa8-0e1595132619.png)

### Contribution checklist (*)
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [ x ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ x ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-05-18 13:37 UTC, sanderjongsma commented
@magento run all tests

2021-05-18 16:16 UTC, gabrieldagama commented
@magento create issue

2021-05-19 06:05 UTC, ihor-sviziev requested changes
Hi @sanderjongsma,
Thank you so much for the fix! Your changes look good to me.

Could you sign the Adobe CLA and fix failing functional tests? 
Note: The unit and Web API test failures look like false positives.

2021-05-19 07:16 UTC, sanderjongsma commented
I signed the Adobe CLA, do I need to trigger a new action or something? I will take a look to failing tests.

2021-05-19 09:55 UTC, ihor-sviziev commented
Hi @sanderjongsma,
I closed and re-opened PR, and now CLI check shows it is passing.
@magento run Unit Tests, WebAPI Tests

2021-05-19 11:50 UTC, Den4ik commented
@magento run WebAPI Tests, Unit Tests, Functional Tests EE, Functional Tests B2B, Functional Tests CE

2021-05-20 20:28 UTC, Den4ik commented
@sanderjongsma Could you check and update Functional Tests. Looks like failed tests related to changes in PR

2021-05-25 12:43 UTC, engcom-Foxtrot requested changes
The pop-up message is incorrect. User should not choose any Store View, only Store. Please see https://github.com/magento/magento2/issues/29101.

2021-05-25 14:35 UTC, Den4ik commented
@engcom-Foxtrot Thanks for the link. Then  it would be correct to update user interface because it's confuse when you see `Store View` and selecting `Store`

2021-05-28 10:37 UTC, Den4ik commented
After discussion close this PR due to https://github.com/magento/magento2/issues/33094

2021-05-28 10:37 UTC, closed without merging