32913 set url key for page before validation
magento/magento2 pull request #33043
Opened 2021-05-19 09:24 UTC by SilinMykola

### Description (*)
This PR based on [32913](https://github.com/magento/magento2/issues/32913) issue.
If merchant didn't set url_key, Magento will validate page, will set url_key and will save page.
The page before save is validated but the url key will set after validation.
I added plugin that generates url key for page before validation.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32913

### Manual testing scenarios (*)
1. Create a new CMS page
2. Set the title to "Catalog"
3. Try to save the CMS page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-05-19 09:26 UTC, SilinMykola commented
@magento run all tests

2021-05-19 11:52 UTC, andrewbess commented
Hello @SilinMykola 
Thank you for your contribution.

However, your fix has cyclomatic dependencies.
The module Magento_CmsUrlRewrite has already dependent on module Magento_Cms.
Your fix makes the module Magento_Cms addicted to the module Magento_CmsUrlRewrite ([see this link](https://github.com/magento/magento2/pull/33043/files#diff-1676b046be24448cd1386a29cbf880876570e5cc88db51f4fb141461450e08dbR10)).
I think it would be better to move your plugin to another place (e.x. into the module Magento_CmsUrlRewrite).

Also, it helps you to fix static and integration tests.

Thank you in advance.

2021-05-19 11:53 UTC, andrewbess requested changes
Hello @SilinMykola 
Thank you for your contribution.
Please take a look at my last comment.

Thank you in advance.

2021-05-19 16:21 UTC, SilinMykola commented
@magento run all tests

2021-05-20 12:15 UTC, andrewbess commented
@magento run Functional Tests B2B

2021-05-21 06:46 UTC, andrewbess approved these changes

2021-05-21 06:47 UTC, magento-engcom-team commented
Hi @andrewbess, thank you for the review.
[ENGCOM-9092](https://jira.corp.magento.com/browse/ENGCOM-9092) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-05-25 08:57 UTC, engcom-Oscar commented
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 

:x: **Before:**
![Screenshot from 2021-05-25 11-48-19](https://user-images.githubusercontent.com/60198413/119469790-5d94d380-bd50-11eb-9dd5-365794905602.png)


:heavy_check_mark: **After:**
![Screenshot from 2021-05-25 11-49-10](https://user-images.githubusercontent.com/60198413/119469809-61c0f100-bd50-11eb-99a7-b7e095794ee4.png)

2021-06-16 11:04 UTC, merged