Divide eav cache per website
magento/magento2 pull request #33061
Opened 2021-05-23 10:44 UTC by vshcheglov

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#10978

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-05-23 11:10 UTC, vshcheglov commented
@magento give me 2.5-develop instance

2021-05-26 08:03 UTC, rikwillems commented
This PR misses a change to `vendor/magento/module-catalog/Model/Config.php` which extends the patched file `vendor/magento/module-eav/Model/Config.php` and results in DI errors.

2021-05-26 08:06 UTC, rikwillems commented
I just added a suggestion to the PR.

2021-05-26 09:55 UTC, rikwillems commented
@vshcheglov please see my two PRs to yours. The current implementation is not working for me without these changes.

2021-05-27 05:19 UTC, vshcheglov commented
> @vshcheglov please see my two PRs to yours. The current implementation is not working for me without these changes.

Yeah, I missed some changes. Thank you!

2021-06-01 16:33 UTC, danielrussob commented
@magento give me 2.5-develop instance

2021-06-01 16:33 UTC, danielrussob commented
@magento give me test instance

2021-06-01 16:40 UTC, aleron75 commented
@magento run all tests

2021-06-01 16:49 UTC, danielrussob commented
I have reproduced the issue on vanilla magento 2.5 instance

2021-06-01 17:01 UTC, aleron75 commented
Hello @vshcheglov!

Thanks for your contribution.

Due to [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html#automated-tests), all code must be covered by tests.

For this specific case, this fix should be covered by automated tests with the scenario which leads to an issue: tests should fail on the mainline and pass with this fix.

A good candidate would be extending the `\Magento\Eav\Test\Unit\Model\ConfigTest` unit test.

Thank you!

2021-06-01 17:05 UTC, danielrussob commented
@magento give me test instance

2021-06-01 20:38 UTC, aleron75 commented
One last thing @vshcheglov: generally only features and tasks with BIC are allowed to be introduced into the `2.5-develop` branch. 

All the bugfix should be delivered to the `2.4-develop` branch;  all fixes delivered to `2.4-develop` will be automatically ported to `2.5-develop`.

So, please, submit this bugfix to the `2.4-develop` branch.

Thanks.

2021-06-29 07:34 UTC, Nazar65 commented
Hi @vshcheglov  do we need to do the same with child's products for configurable, it also uses same cache for front and back, and also store here : -> https://github.com/magento/magento2/blob/0a05fa3da4c645926af0e6d8dea1c81d819be8fc/app/code/Magento/ConfigurableProduct/Model/Product/Type/Configurable.php#L1436

2021-07-04 11:17 UTC, vshcheglov commented
@aleron75 
> So, please, submit this bugfix to the 2.4-develop branch.

patch-2 branch is based on 2.5-develop branch so we should not merge it to 2.4

I prepared a new branch based on 2.4.develop branch but don't see any ability to change patch-2 branch to a new branch.
How to deal with it? I can create a new pull request with a new branch.

@Nazar65 
> Hi @vshcheglov do we need to do the same with child's products for configurable, it also uses same cache for front and back, and also store here : ->

I am not sure that it is related to the current issue.

2021-10-25 18:43 UTC, sidolov requested changes

2021-10-25 18:43 UTC, sidolov commented on app/code/Magento/Eav/Model/Config.php
> +    private function getWebsiteId()
Please, add return type

2021-12-21 02:02 UTC, vshcheglov commented
Added a pull request with additional changes based on 2.4-develop branch being merged to it.
https://github.com/magento/magento2/pull/34856

2021-12-21 02:05 UTC, closed without merging