32460 GraphQL: add category_url_path to ProductAttributeFilterInput
magento/magento2 pull request #33090
Opened 2021-05-27 13:11 UTC by khrystynastolbova

### Description (*)

Add category_url_path to ProductAttributeFilterInput
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32460

### Manual testing scenarios (*)

```
{
  products(filter:{
    category_url_path : {eq:"category-1/category-1-2"}
  }) {
    total_count
    items {
      name
      sku
    }
  }
}
```
<img width="1129" alt="Screenshot 2021-05-27 at 16 11 10" src="https://user-images.githubusercontent.com/79088059/119831681-2f58f480-bf06-11eb-9d74-60fb8eb345e9.png">

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-05-27 13:17 UTC, khrystynastolbova commented
@magento run all tests

2021-05-28 12:26 UTC, khrystynastolbova commented
@magento run all tests

2021-07-08 14:08 UTC, khrystynastolbova commented
@magento run all tests

2021-11-23 13:16 UTC, khrystynastolbova commented
@magento run all tests

2022-08-16 12:46 UTC, paales commented
@cpartica @khrystynastolbova Any reason why this is blocked? We currently have to do an additional roundtrip to get this working.

2023-04-04 12:25 UTC, engcom-Hotel commented
@magento run all tests

2023-04-04 15:25 UTC, engcom-Hotel requested changes
@khrystynastolbova It seems the build failures are due to code changes. Please take care of them.

2023-04-10 07:34 UTC, engcom-Charlie commented
@magento run all tests

2023-04-10 14:13 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2023-04-10 14:24 UTC, engcom-Charlie commented
Hi @khrystynastolbova,

Thank you for your contribution!

I am working on the test failures.

Thank you!

2023-04-10 17:05 UTC, engcom-Charlie commented
@magento run all tests

2023-04-11 05:57 UTC, engcom-Charlie commented
@magento run WebAPI Tests

2023-04-11 11:34 UTC, engcom-Charlie commented
@magento run WebAPI Tests

2023-04-11 12:05 UTC, engcom-Charlie commented
@magento run all tests

2023-04-11 12:06 UTC, engcom-Charlie commented
Implemented fix for web API and Static test failures.

2023-04-12 06:09 UTC, engcom-Charlie commented
Newly implemented wep API test and the failing static tests are passing now. The Functional CE failed test case is seems to be flakey. Hence moving this PR to Testing now.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/51680850/231366320-e9ed1106-812a-402e-8f1f-2904fb7c73ed.png">

Thank you!

2023-04-12 09:08 UTC, engcom-Lima commented
@ magento give me 2.4-develop instance

2023-04-12 09:09 UTC, engcom-Lima commented
@magento give me 2.4-develop instance

2023-04-12 09:17 UTC, engcom-Lima commented
@magento give me test instance

2023-04-12 12:57 UTC, engcom-Lima reviewed
Hi @reporter, @reviewer

Thanks for the collaboration & contribution!

:x: QA not Passed

Products in the child categories are not displaying in the response.

**Manual Scenario Steps**

1. Create subcategory under default. (say A)
2. Create 2 subcategories under A(Child). For ex- A ->B,A-> C
3. Add products to each subcategories.
4. Execute below graphQL query:
```
{
  products(filter:{
    category_url_path : {eq:"category-1/category-1-2"}
  }) {
    total_count
    items {
      name
      sku
    }
  }
}
```


**:heavy_check_mark: Expected result After Fix**  Product should be displayed of sub subcategory(child category)


**:x: Actual result After Fix** Products were not getting displayed from child category. Getting  error as "message": "No category with the provided `category_url_path` was found",
<img width="1377" alt="Screenshot 2023-04-12 at 4 23 24 PM" src="https://user-images.githubusercontent.com/60198022/231453709-d4121467-de92-4796-9c16-ee92cafd1198.png">
**Video for your reference:** https://shared-assets.adobe.com/link/66c20a5d-2db7-4d44-7627-1c83ed423e38

2023-04-12 15:09 UTC, paales commented
@engcom-Lima the result of your query is to be expected. The query you meant to do was `Clothing/Test1` and `Clothing/Sports`, right?

2023-04-13 05:55 UTC, engcom-Lima commented
@magento give me test instance

2023-04-13 09:18 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
Run below graphQL query:
```
{
  products(filter:{
    category_url_path : {eq:"category-1/category-1-2"}
  }) {
    total_count
    items {
      name
      sku
    }
  }
}

``` 
**Before:** :heavy_multiplication_x: 
<img width="1321" alt="Screenshot 2023-04-12 at 3 21 08 PM" src="https://user-images.githubusercontent.com/60198022/231712179-eba350f0-45e8-4f4f-92d0-43949c5389be.png">


**After:** :heavy_check_mark:  
<img width="1297" alt="Screenshot 2023-04-12 at 3 23 45 PM" src="https://user-images.githubusercontent.com/60198022/231712366-e66fd305-0331-43f1-b93e-5f600efd5512.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/60198022/231712598-24cec232-0eed-497e-9b48-3a91027c8658.png">

Referring to the comment https://github.com/magento/magento2/pull/33090#issuecomment-1504714267 .Moving to Merge in Progress.

2023-04-20 07:25 UTC, engcom-Charlie commented
@magento run all tests

2023-04-20 13:12 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2025-02-17 11:20 UTC, merged