Updated monolog/monolog to 2.26.1
magento/magento2 pull request #33226
Opened 2021-06-12 10:51 UTC by konarshankar07

### Description (*)

Updated monolog/monolog to 2.26.1

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32868

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-06-12 10:51 UTC, konarshankar07 commented
@magento run all tests

2021-06-12 11:16 UTC, konarshankar07 commented
@magento run all tests

2021-06-15 08:04 UTC, konarshankar07 commented
@magento run Static Tests

2021-06-19 10:40 UTC, sivaschenko commented on composer.json
> +        "monolog/monolog": "~1.26.1",
@konarshankar07 Thanks for the contribution! Can the library be updated by updating the composer.lock file only?

2021-06-19 10:41 UTC, sivaschenko commented
Are there any partner contributors voluteers to collaborate on this PR and create corresponding EE PR to fix static tests?

2021-06-19 12:44 UTC, sivaschenko requested changes
Thanks for the pull request @konarshankar07 ! Please see my comment

2021-06-19 12:44 UTC, sivaschenko commented on composer.json
> +        "monolog/monolog": "~1.26.1",
Let's update monolog to the latest available version
```suggestion
        "monolog/monolog": "^2.2",
```

2021-06-19 13:14 UTC, sivaschenko commented
Removed "help wanted" label, as @drpayyne has joined to help on the commerce repo side

2021-06-19 13:16 UTC, sivaschenko commented
This pull request depends on the MFTF changes (update of the same library)

2021-06-19 15:01 UTC, sivaschenko commented
EE pull request added to the related: https://github.com/magento/partners-magento2ee/pull/555

This pull request will be ready to merge once changes from https://github.com/magento/magento2-functional-testing-framework/pull/832 are released

2021-06-25 09:33 UTC, sivaschenko commented
@magento run all tests

2021-06-30 01:16 UTC, jilu1 commented
@sivaschenko 
Is branch konarshankar07:update/package-monolog-1.26.1 ready with monolog upgrade? I got failed build http://10.234.231.143:8080/job/Functional-Tests-CE/4100/.

2021-07-01 10:05 UTC, sivaschenko requested changes
Hi @konarshankar07 , can you please update the codebase for the latest monolog version.

Currently the tests are failing with error:

```
PHP Fatal error:  Declaration of Magento\Framework\Logger\Handler\Base::write(array $record) must be compatible with Monolog\Handler\StreamHandler::write(array $record): void in /var/www/html/lib/internal/Magento/Framework/Logger/Handler/Base.php on line 81
```

2021-07-01 10:05 UTC, sivaschenko commented on lib/internal/Magento/Framework/composer.json
> +        "monolog/monolog": "~1.26.1",
```suggestion
        "monolog/monolog": "^2.2",
```

2021-07-02 04:27 UTC, konarshankar07 commented
@magento run all tests

2021-07-15 19:08 UTC, hostep commented
Would love to see this happen, as monolog v2 comes with a [new datetime format that includes timezone information](https://github.com/Seldaek/monolog/commit/76a91c672213a17cb0de82f20e7a28c6f014eacf).

I was just researching this topic accidentally before running into this PR, because I think it could be very helpful in reading log files and I always get confused about the timestamps in Magento log files because it's currently not clear what timezone they are representing.

Alternatively, if this upgrade would take too much time to get approved, we could change the second parameter of the LineFormatter object that is created [over here](https://github.com/magento/magento2/blob/ab591597f860fdee5572d3894c649100e42d884c/lib/internal/Magento/Framework/Logger/Handler/Base.php#L54) to `Y-m-d\TH:i:sP`. That would also solve my need.

Just FYI 🙂

2021-07-16 20:59 UTC, andrewbess commented
Hello @hostep 
We are actively working on updating the monolog to version 2.3.1 in new PRs.
This PR will be closed because of contributor doesn't continue working on this PR.
New PRs:
https://github.com/magento/magento2/pull/33497
https://github.com/magento/magento2-functional-testing-framework/pull/854

2021-07-21 09:54 UTC, sivaschenko commented
Closing in favour to finalized https://github.com/magento/magento2/pull/33497

2021-07-21 09:54 UTC, closed without merging