32977 Fixed text area for Customizable Options on the Checkout Cart Page
magento/magento2 pull request #33256
Opened 2021-06-16 09:21 UTC by AZiniukhin

### Description (*)

I created a solution in the file ( Magento/Checkout/view/frontend/templates/cart/item/default.phtml ). 
For the correct display of the text, need to add one or more AllowedTags ( ['span', 'a'] ) to the function call 
( $block->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a'] ) by analogy with 
( $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ). 
If this is not done, then the formation of the text will take place without the pregmach function called on line 117 of the file 
( lib/internal/Magento/Framework/Escaper.php ) which leads to incorrect display of text.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32977

### Manual testing scenarios (*)

1. Create a simple product in the admin panel.
2. Create two customizable options both with text area option with 350 characters allowed.
3. On the product page enter less than 55 characters in one text area and more than 55 in the other both with spaces and line breaks.
<img width="535" alt="Screenshot 2021-06-16 at 12 14 57" src="https://user-images.githubusercontent.com/26867833/122192919-bf061900-ce9c-11eb-83c7-212868a7a3dc.png">
4. Add the item to your cart and go to the cart page. You will see the correct text display.
<img width="919" alt="Screenshot 2021-06-16 at 12 19 21" src="https://user-images.githubusercontent.com/26867833/122193385-1c9a6580-ce9d-11eb-84ff-fe31b04ed3aa.png">

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-06-16 10:36 UTC, AZiniukhin commented
@magento run all tests

2021-06-16 13:15 UTC, ihor-sviziev requested changes
Could you cover your fix with some kind of automated test?

2021-06-25 07:54 UTC, AZiniukhin commented
@magento run all tests

2021-06-25 10:06 UTC, Den4ik commented
@magento run Unit Tests, Functional Tests EE

2021-06-25 10:09 UTC, AZiniukhin commented
The test added, please check @ihor-sviziev

2021-06-25 10:25 UTC, Den4ik requested changes
@AZiniukhin Thanks for contribution.
Please look at my comment. What do you think?

2021-06-25 10:25 UTC, Den4ik commented on dev/tests/integration/testsuite/Magento/Checkout/_files/cart_with_simple_product_and_custom_option_text_area.php
> +            $value = 'Test product simple with
I believe that heredoc syntax looks more clear

2021-06-25 10:25 UTC, Den4ik commented on dev/tests/integration/testsuite/Magento/Checkout/Block/Cart/Item/RendererTest.php
> +        $this->assertMatchesRegularExpression('/Test product simple with
I believe that heredoc syntax looks more clear

2021-06-25 10:52 UTC, AZiniukhin commented
@Den4ik 
I added heredoc syntax. Please check.

2021-06-25 10:54 UTC, Den4ik commented
@magento run all tests

2021-06-26 11:20 UTC, Den4ik approved these changes
✅ Approved
Changes looks good for me. @AZiniukhin Thanks for contribution.

2021-07-01 13:02 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed


**Preconditions:**

> 1. Create a product created with 2 customizable options. The options should be with text areas that accepts minimum 350 characters.


**Manual testing scenario:**
> 
> 1. Front end - Checkout the same product with both the text area customizable options filled. (Note: Text area options should be filled with new line as well; Ex is in below screenshot)
>     ![image](https://user-images.githubusercontent.com/51679138/124127857-d7c81e80-da99-11eb-8128-76e4ee47ac52.png)
> 
> 2. Proceed to Checkout page and validate the product content.


**Before:** :heavy_multiplication_x: <br /> text was getting appeared in the page

> ![image](https://user-images.githubusercontent.com/51679138/124128042-034b0900-da9a-11eb-92b5-371800013142.png)


**After:** :heavy_check_mark:  One line description about the is the outcome after fix

> ![image](https://user-images.githubusercontent.com/51679138/124128116-19f16000-da9a-11eb-8d27-31edf2b6b108.png)

2021-07-29 11:05 UTC, merged