Fix apply mage events due race condition
magento/magento2 pull request #33277
Opened 2021-06-18 00:53 UTC by mrtuvn

### Description (*)

When the code in lib/mage/mage.js (row 93) is executed before the body tag is created. If the body tag doesn't exist, the $('body') return undefined and the event handler for the event 'contentUpdated' is not created.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32068

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-06-19 13:19 UTC, ihor-sviziev commented
Looks reasonable.
@magento run all tests

2021-06-20 00:52 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-06-21 07:37 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests look not related to changes from this PR.

2021-06-21 07:39 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9126](https://jira.corp.magento.com/browse/ENGCOM-9126) has been created to process this Pull Request

2021-06-22 10:09 UTC, Den4ik approved these changes
✅ Good job.
@mrtuvn Thanks for your work

2021-06-22 10:10 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9126](https://jira.corp.magento.com/browse/ENGCOM-9126) has been created to process this Pull Request

2021-06-23 07:10 UTC, tanghongtanghong commented on lib/web/mage/mage.js
> -    $('body').on('contentUpdated', function () {
test

2021-06-23 07:10 UTC, tanghongtanghong commented on lib/web/mage/mage.js
> +    $('html').on('contentUpdated', 'body', function () {
特特

2021-06-25 12:01 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2021-06-26 04:30 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-06-26 14:48 UTC, Den4ik commented
@magento run Functional Tests EE

2021-07-22 03:38 UTC, mrtuvn commented
@magento run Functional Tests EE

2021-08-05 11:59 UTC, engcom-Hotel commented
:x: QA not Passed

Hello @mrtuvn,

We have checked this issue with the below steps:
Step 1: Use advance javascript bundling using below command:
php -f bin/magento config:set dev/js/enable_js_bundling 1
Step 2: Clean the cache
Step 3: Tried to open the Homepage (Theme : Luma)
Step 4: Apply the breakpoint in mage.js on L88 ($('html').on('contentUpdated', 'body', function () {)
Step 5: Hard refresh the page 17 times.

Note: Out of 10 times, almost 4 times the breakpoint was not hit. I am attaching a video for reference.


https://user-images.githubusercontent.com/51681618/128343670-b5671ca4-9520-4afa-8952-793e553bf8ea.mov

Thanks

2021-09-06 09:53 UTC, ihor-sviziev commented
@mrtuvn, could you check the QA results?

2021-09-25 12:38 UTC, mrtuvn commented
@magento run all tests

2021-09-26 01:17 UTC, mrtuvn commented
@magento run Integration Tests

2021-11-05 06:54 UTC, ihor-sviziev approved these changes

2021-11-05 06:55 UTC, ihor-sviziev commented
Hi @engcom-Hotel,
Could you double-check if this issue reproducing with recent changes?

2021-11-05 06:55 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9126](https://jira.corp.magento.com/browse/ENGCOM-9126) has been created to process this Pull Request

2022-01-12 13:52 UTC, engcom-Dash commented
❌ QA not Passed

**Manual Scenario Steps**

Step 1: Use advance javascript bundling using below command:
bin/magento config:set dev/js/enable_js_bundling 1
Step 2: Clean the cache
Step 3: Tried to open the Homepage (Theme : Luma)
Step 4: Apply the breakpoint in mage.js on L88 (document).on('contentUpdated', 'body', function () {
Step 5: Hard refresh the page many times.

**:heavy_check_mark: Expected result After Fix** 
-  Breakpoint will hit on every page reload

**:x: Actual result After Fix** 
-  Breaking point is not hitting every time

Attached is the screen recording for reference

2022-01-12 14:17 UTC, engcom-Alfa requested changes
As per [above-comment](https://github.com/magento/magento2/pull/33277#issuecomment-1011068148), still seeing the updated changes are not successfully solving the issue, moving it to _Changes Requested_.

2022-03-08 07:13 UTC, engcom-Lima commented
Hi @mrtuvn, @ihor-sviziev
I have double checked the fix and it is working fine.
As per the [documentation](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html), JS bundling will only work in the **Production Mode**

Steps followed to verify the issue:-

1. Install fresh 2.4-develop instance of Magento
2. Enable JS bundling by following this [documentation](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html) (Skip step 3 of minifying the JS files)
3.  Clean the cache
4. Open the Homepage (Theme : Luma)
5. Apply the breakpoint in mage.js (lib/mage/mage.js) on Line - 88 
```(document).on('contentUpdated', 'body', function () {```
6. Hard refresh the page many times.

**Result:**
Of all the 10 times, the breakpoint was hit every single time.

Based on this moving this PR to **Merge in Progress**

2022-05-18 13:36 UTC, merged