Add attributes for fonts preload
magento/magento2 pull request #33279
Opened 2021-06-18 10:43 UTC by in-session

Reference: https://web.dev/optimize-lcp/#preload-important-resources

```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <font src="fonts/Luma-Icons.woff2" type="font/woff2" />
    </head>
</page>
```
Output:
```
<link rel="preload" as="font" crossorigin="anonymous"  type="font/woff2" href="..../Luma-Icons.woff2" />
```

2021-06-18 12:58 UTC, in-session commented
@magento run all tests

2021-06-18 14:31 UTC, mrtuvn commented
https://github.com/magento/magento2/blob/2.4-develop/app/design/frontend/Magento/luma/Magento_Theme/layout/default_head_blocks.xml
also i think you can update for type font here too

2021-06-19 03:28 UTC, mrtuvn commented
Can you cover changes with some kind of automation test related with file change ? Maybe unit test will suitable for such case
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Test/Unit/Page/Config/RendererTest.php#L402
Thanks you

2021-06-20 00:56 UTC, mrtuvn commented
@magento run all tests

2021-06-22 10:19 UTC, Den4ik requested changes
@in-session Thanks for contribution. Please look at my comments.

Also please cover changes with unit test.
**PS.** `\Magento\Framework\View\Test\Unit\Page\Config\RendererTest::dataProviderRenderAssets`

2021-06-22 10:19 UTC, Den4ik commented on lib/internal/Magento/Framework/View/Page/Config/Renderer.php
> +            return 'rel="preload" as="font" crossorigin="anonymous" ' . $attributes;
As I see in https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Page/Config/Renderer.php#L326-L341 `$attributes` could be `null`

2021-06-24 16:46 UTC, fredden commented
Hi @in-session. We came across this pull request in the Public Triage meeting. Please can you add some more information to the pull request description. We think this looks like a good improvement, but testing this will be tricky without prior knowledge of what you're changing. Ideally the description will help anyone understand the problem that this pull request solves and the impact on the website.

2022-10-13 15:17 UTC, ishakhsuvarov commented
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:17 UTC, closed without merging