33337: eliminated laminas-i18n and laminas-filter dependency
magento/magento2 pull request #33362
Opened 2021-06-26 16:06 UTC by korovitskyi

### Description (*)

Eliminated laminas-i18n and laminas-filter dependency
Also it was created the private `filter` method to proceed with the native logic process.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33337

### Manual testing scenarios (*)

-----

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-06-26 16:07 UTC, korovitskyi commented
@magento run all tests

2021-06-29 13:47 UTC, Den4ik requested changes
@korovitskyi Thanks for your contribution.
Could you please check my comments.

Also if I'm correct we should create PR to `platform-health` branch. @sivaschenko, correct me if I'm wrong.

2021-06-29 13:47 UTC, Den4ik commented on app/code/Magento/Checkout/Model/Cart/RequestQuantityProcessor.php
> +                }
I believe that we can move this part into separate private method. In my opinion code will looks more clear

2021-06-29 13:47 UTC, Den4ik commented on app/code/Magento/Checkout/Model/Cart/RequestQuantityProcessor.php
> +     * @param float|int|array $quantity
is `$quantity` could be the string?

2021-06-29 13:47 UTC, Den4ik commented on composer.lock
> +    "plugin-api-version": "1.1.0"
Please use composer v2

2021-07-01 08:29 UTC, korovitskyi commented
@magento run all tests

2021-07-01 08:32 UTC, korovitskyi commented
Hi, @Den4ik .
The changes were added.
Also was changed the PR branch to `platform-health`.
Thank you for the review.

2021-07-05 09:11 UTC, Den4ik commented
@korovitskyi Please resolve merge conflict

2021-07-05 09:26 UTC, Den4ik commented
All looks ok for me. I'll approve after fixing merge conflict and rerun tests

2021-07-05 09:47 UTC, korovitskyi commented
@magento run all tests

2021-07-05 09:48 UTC, korovitskyi commented
Hi, @Den4ik .
The conflicts have been reloved.

2021-07-06 11:55 UTC, Den4ik commented
@magento run Functional Tests EE, Unit Tests

2021-07-07 21:24 UTC, Den4ik approved these changes
✅ Approved.
@korovitskyi Good job 👍

2021-07-08 07:07 UTC, eduard13 approved these changes

2021-07-19 16:08 UTC, andrewbess commented
Hello @korovitskyi 
Could you please resolve merge-conflict.
Thank you in advance.

2021-07-19 19:59 UTC, andrewbess commented
@magento run all tests

2021-07-19 21:12 UTC, Den4ik commented
@magento run all tests

2021-07-19 21:12 UTC, Den4ik commented
@korovitskyi Please pay attention to https://github.com/magento/magento2/pull/33362#issuecomment-882863229

2021-07-20 07:35 UTC, Den4ik commented
@magento run all tests

2021-07-20 07:57 UTC, andrewbess commented
Closed due to opening new it https://github.com/magento/magento2/pull/33529

2021-07-20 07:57 UTC, closed without merging