Remove casting to int on increment ID which can be prefixed by a string
magento/magento2 pull request #33369
Opened 2021-06-28 09:50 UTC by sippsolutions

### Description (*)
- Remove casting to int on increment ID which can be prefixed by a string

### Manual testing scenarios (*)
1. Configure a string prefix to invoice increment IDs
2. Submit an order
3. Create an invoice
4. Go to customer account -> orders -> invoice -> print invoice
5. The increment ID should be there, but is "0" for numbers prefixed with a string

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2021-06-30 01:41 UTC, mrtuvn commented
Thanks for contribute! Can you add some screenshot show problem?

2021-06-30 13:10 UTC, ihor-sviziev requested changes
Hi @sippsolutions,
Could you add escaping for the string, and cover it with some type of automated test?

2021-07-22 10:35 UTC, ihor-sviziev requested changes

2021-07-22 10:35 UTC, ihor-sviziev commented on app/code/Magento/Sales/view/frontend/templates/order/print/invoice.phtml
> +        <strong><?= $block->escapeHtml(__('Invoice #')) ?><?= $_invoice->getIncrementId() ?></strong>
We still need to have escaping here.
```suggestion
        <strong><?= $block->escapeHtml(__('Invoice #')) ?><?= $block->escapeHtml($_invoice->getIncrementId()) ?></strong>
```

2021-08-27 18:05 UTC, ihor-sviziev commented
@magento run all tests

2021-08-27 19:19 UTC, ihor-sviziev requested changes
Now the changes looks good to me. Could you cover your changes with some test?

2021-08-30 12:07 UTC, sippsolutions commented
Hi @ihor-sviziev, as the only change is in a phtml-File, I don't think this is coverable with tests. I tested it in a live instance though.

2021-08-30 12:36 UTC, ihor-sviziev requested changes
Could you fix the failing integration tests?
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33369/51783dfe9bd8db7201749b7c7fe0d1cd/Integration/console-error-logs.html

I think fixing the integration test will automatically add the test coverage for this PR

2021-09-01 09:11 UTC, ihor-sviziev commented
@magento run Integration Tests, Static Tests

2021-09-01 20:56 UTC, ihor-sviziev commented
@magento run all tests

2021-09-01 21:18 UTC, ihor-sviziev commented
@magento run all tests

2021-09-02 03:11 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-09-02 03:26 UTC, ihor-sviziev approved these changes

2021-09-02 03:27 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9208](https://jira.corp.magento.com/browse/ENGCOM-9208) has been created to process this Pull Request

2021-10-27 11:51 UTC, engcom-Alfa commented
@magento create issue

2021-10-27 12:06 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a fresh Magento installation 2.4-develop


**Manual testing scenario:**

1. Configure a string prefix to invoice increment IDs

2. Place an order from front end
 
3. Create invoice from admin

4. Frontend: Go to customer account -> orders -> invoice -> print invoice

5. Check the invoice number


**Before:** :heavy_multiplication_x: Invoice ID used to be 0

![image](https://user-images.githubusercontent.com/51679138/139061947-43c6bbce-8c4c-4baf-b3b9-469a08b4fd3b.png)


**After:** :heavy_check_mark:  Invoice Id is printed correctly keeping prefix with string

![image](https://user-images.githubusercontent.com/51679138/139062030-362d8821-3be1-4597-b856-7412664fddfc.png)

Since it is a issue with a custom changes in the invoice related code, there is no additional testing or regression is required.

2021-11-21 02:33 UTC, merged