33040 add is subscription enabled checking to new action controller
magento/magento2 pull request #33375
Opened 2021-06-28 16:37 UTC by SilinMykola

### Description (*)
I added config settings check to NewAction subscriber controller to prevent subscription customer if in config subscription is disabled

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33040

### Manual testing scenarios (*)
1. Open frontend page with subscription form.
2. Disabled subscription in configuration and clear cache.
3. Back to frontend page (not reload) and subscribe.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-06-28 16:38 UTC, SilinMykola commented
@magento run all tests

2021-06-29 04:25 UTC, eduard13 requested changes
Hi @SilinMykola thank you for your contribution. Could you please review the below suggestion? Also, please consider covering the fix by some automated tests (integration tests would be suitable for such cases).

Thank you.

2021-06-29 04:25 UTC, eduard13 commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +        return (bool)$this->_objectManager->get(ScopeConfigInterface::class)
We should avoid using objectManager. Please inject and use \Magento\Newsletter\Model\Config::isActive instead.

2021-06-29 04:25 UTC, eduard13 commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +    public const XML_PATH_IS_SUBSCRIPTION_ENABLED = 'newsletter/general/active';
This won't be needed after implementing the below suggestion.

2021-06-30 06:10 UTC, eduard13 commented
@magento run all tests

2021-09-01 14:54 UTC, SilinMykola commented
@magento run all tests

2021-09-02 07:03 UTC, SilinMykola commented
@magento run Functional Tests B2B, Integration Tests

2021-09-03 05:47 UTC, SilinMykola commented
@magento run Integration Tests

2021-09-03 08:36 UTC, eduard13 requested changes
Please check my suggestions below

2021-09-03 08:36 UTC, eduard13 commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +     * @param NewsletterConfig $newsletterConfig
Please add the new dependency at the end and exactly how it is added the `EmailValidator`.

2021-09-03 08:36 UTC, eduard13 commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +    protected function validateEmailAvailable(string $email)
Please revert it, since it's BIC
```suggestion
    protected function validateEmailAvailable($email)
```

2021-09-03 08:36 UTC, eduard13 commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +    protected function validateIsSubscriptionEnabled(): bool
I'm not sure that it worth declaring a new method for this purpose, I'd add `isActive` check straight into that condition.

2021-09-03 08:36 UTC, eduard13 commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +    protected function validateEmailFormat(string $email)
Revert this change
```suggestion
    protected function validateEmailFormat($email)
```

2021-09-03 08:36 UTC, eduard13 commented on app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php
> +            $this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
Please move `validateIsSubscriptionEnabled` at the end and correctly format the multiline if condition. Check [this article](https://pear.php.net/manual/en/rfc.cs-enhancements.splitlongstatements.php) for more info.
```suggestion
        if ($this->validateIsSubscriptionEnabled() &&
            $this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
```

2021-09-03 10:34 UTC, SilinMykola commented
@magento run all tests

2021-10-04 11:54 UTC, eduard13 approved these changes

2021-10-04 11:55 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9238](https://jira.corp.magento.com/browse/ENGCOM-9238) has been created to process this Pull Request

2021-10-04 12:05 UTC, SilinMykola commented
@magento run all tests

2021-10-05 17:31 UTC, SilinMykola commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-10-06 06:30 UTC, SilinMykola commented
@magento run Functional Tests B2B

2021-10-06 09:12 UTC, SilinMykola commented
@magento run Functional Tests B2B

2021-10-06 14:15 UTC, SilinMykola commented
@magento run Functional Tests B2B

2021-10-06 20:08 UTC, SilinMykola commented
@magento run Functional Tests B2B

2024-01-09 14:56 UTC, engcom-Delta commented
@SilinMykola , Please clear the conflicts in the Pr to move ahead

2024-01-09 17:33 UTC, SilinMykola commented
@magento run all tests

2024-01-09 17:34 UTC, SilinMykola commented
@engcom-Delta hi! Thank you for your response! I fixed the conflicts and ran the tests.

2024-01-09 19:39 UTC, SilinMykola commented
@magento run all tests

2024-01-10 08:52 UTC, SilinMykola commented
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B

2024-01-10 18:11 UTC, SilinMykola commented
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B

2024-01-12 07:50 UTC, SilinMykola commented
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B

2024-01-12 16:53 UTC, engcom-Delta commented
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Open frontend, the newsletter subscription in the page bottom should be visible
2. Open backend, disable the newsletter functionality (Stores > Configuration > Customers > Newsletter > General 
    Options > Enabled -> set to "No".
4. Clear cache to make configuration change active
5. Switch to the frontend (don't reload or the newsletter subscription form will disappear)
6. Enter any email and click on "Subscribe"
7. Verify the message "Thank you for your subscription" and backend if the email is subscribed.


**Before:** :heavy_multiplication_x: 


<img width="1427" alt="Screenshot 2024-01-12 at 7 10 20 PM" src="https://github.com/magento/magento2/assets/51681379/7a13ee33-d8cf-4573-8863-796be6baf957">

<img width="1425" alt="Screenshot 2024-01-12 at 7 21 29 PM" src="https://github.com/magento/magento2/assets/51681379/b024147d-0c95-49d9-9638-9a093cd8b409">

<img width="1414" alt="Screenshot 2024-01-12 at 7 22 17 PM" src="https://github.com/magento/magento2/assets/51681379/5061ec17-acd9-4eac-bac7-6518a750ac23">

<img width="1434" alt="Screenshot 2024-01-12 at 7 22 32 PM" src="https://github.com/magento/magento2/assets/51681379/6cf43f04-60ed-438d-b081-9f7a9ec208ef">
 
<img width="1361" alt="Screenshot 2024-01-12 at 10 02 32 PM" src="https://github.com/magento/magento2/assets/51681379/64e58915-a611-4abc-a005-7791f2c9a9f4">

<img width="1432" alt="Screenshot 2024-01-12 at 10 02 50 PM" src="https://github.com/magento/magento2/assets/51681379/5a28938f-8e9f-4908-91ea-40e692e7dfd8">

<img width="1440" alt="Screenshot 2024-01-12 at 10 03 14 PM" src="https://github.com/magento/magento2/assets/51681379/fd490357-8037-4f0c-b043-518ccd6d7b34">


**After:** :heavy_check_mark:  


<img width="1428" alt="Screenshot 2024-01-12 at 10 12 39 PM" src="https://github.com/magento/magento2/assets/51681379/29971e0d-353f-457b-a1d5-e3a6e10b1225">

<img width="1429" alt="Screenshot 2024-01-12 at 10 13 10 PM" src="https://github.com/magento/magento2/assets/51681379/deda4fe0-22f6-46da-9ee7-65264f82b60d">

<img width="1432" alt="Screenshot 2024-01-12 at 10 13 20 PM" src="https://github.com/magento/magento2/assets/51681379/dfa9e7d6-547e-4153-8e2d-0f57841a6cfe">

<img width="1421" alt="Screenshot 2024-01-12 at 10 14 03 PM" src="https://github.com/magento/magento2/assets/51681379/d2b378d8-431d-4725-b2d8-92f320554cc5">

<img width="1431" alt="Screenshot 2024-01-12 at 10 14 10 PM" src="https://github.com/magento/magento2/assets/51681379/8e699895-ea1d-427a-97ac-e6ecf29b4595">

<img width="1360" alt="Screenshot 2024-01-12 at 10 15 00 PM" src="https://github.com/magento/magento2/assets/51681379/84404b3b-7e17-4cd5-9a43-d5d3ae29e94b">

<img width="1434" alt="Screenshot 2024-01-12 at 10 17 23 PM" src="https://github.com/magento/magento2/assets/51681379/68b70a4e-fedf-4f3a-8afb-1aa06dedc206">

<img width="1439" alt="Screenshot 2024-01-12 at 10 24 59 PM" src="https://github.com/magento/magento2/assets/51681379/ddce612f-4a76-4b67-ad53-10af7b3912e6">


Builds are failed. Hence, moving this PR to **Extended Testing.**

2024-02-24 14:20 UTC, merged