33338: Remove usage of laminas\mvc from Setup Wizard page
magento/magento2 pull request #33397
Opened 2021-07-01 11:34 UTC by karyna-tsymbal-atwix

Eliminate usage of laminas/mvc from Setup Wizard static page.

Detected more dependencies in other places except Wizard page. Further investigation required to complete the elimination of laminas/mvc as specified in https://github.com/magento/magento2/issues/33338 

### Manual testing scenarios (*)
Setup Wizard page looks the same as before introduced changes.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-01 11:48 UTC, andrewbess commented
Hello @karyna-tsymbal-atwix 
Thank you for your PR.
It looks well to me.
I will continue with the tests and will add them ASAP.
After that, I will approve this PR.

2021-07-01 11:49 UTC, andrewbess requested changes
It requires to add tests

2021-07-01 13:28 UTC, ihor-sviziev commented on setup/view/magento/setup/index.phtml
>  // phpcs:disable Magento2.Templates.ThisInTemplate
Looks like this could be removed

2021-07-02 11:18 UTC, sivaschenko commented
@karyna-tsymbal-atwix please pay attention that the Platform Health project target branch is `platform-health`

2021-07-25 19:23 UTC, andrewbess commented
@magento give me test instance

2021-07-25 19:34 UTC, andrewbess commented
@magento run all tests

2021-07-25 19:37 UTC, andrewbess approved these changes
Hello @karyna-tsymbal-atwix 
Your changes are approved.
The MFTF tests will be added separately because it requires additional efforts.
Thank you for your job.

2021-07-26 08:36 UTC, Den4ik approved these changes

2021-07-26 08:40 UTC, Den4ik commented
@magento Functional Tests EE, Functional Tests B2B, Functional Tests CE

2021-07-26 08:47 UTC, eduard13 approved these changes

2021-07-26 09:47 UTC, andrewbess commented
The external currency service still unavailable.
<img width="1588" alt="503-in-console" src="https://user-images.githubusercontent.com/10788564/126967405-e490f5fa-e6c2-4f2d-94f4-196a04ec820a.png">
<img width="1353" alt="api-server-status" src="https://user-images.githubusercontent.com/10788564/126967421-53a0f6c4-cc7c-4591-b47d-a31203b42e0b.png">
So, functional tests cannot be passed successfully.

This PR will be merged a little bit later

cc @Den4ik

2021-07-26 13:02 UTC, merged