33378 GraphQL: create an entry in 'customer_log' after generate customer token
magento/magento2 pull request #33409
Opened 2021-07-02 14:51 UTC by khrystynastolbova

…mer token

### Description (*)

Create an entry in 'customer_log' after generate customer token.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33378

### Manual testing scenarios (*)

1. Check 'customer_log'  db table
2. Genarate customer token
```
mutation {
	generateCustomerToken(
        email: "roni_cost@example.com"
        password: "roni_cost3@example.com"
    ) {
        token
    }
}
```
3. Check 'customer_log' db table again. The field 'last_login_at' for this customer was updated.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-05 05:32 UTC, ihor-sviziev commented
@magento run all tests

2021-07-05 05:45 UTC, eduard13 requested changes
Thank you @khrystynastolbova for fixing this one. Could you please review the minor suggestions below?

2021-07-05 05:45 UTC, eduard13 commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/LoggerTest.php
> +    protected $logger;
```suggestion
    private $logger;
```

2021-07-05 05:45 UTC, eduard13 commented on app/code/Magento/CustomerGraphQl/etc/graphql/events.xml
> +<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
```suggestion
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
```

2021-07-05 05:45 UTC, eduard13 commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/LoggerTest.php
> +    private function getQuery(string $email = 'customer@example.com', string $password = 'password') : string
```suggestion
    private function getQuery(string $email = 'customer@example.com', string $password = 'password'): string
```

2021-07-05 05:48 UTC, ihor-sviziev requested changes
Here is one more improvement

2021-07-05 05:48 UTC, ihor-sviziev commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/LoggerTest.php
> +    public function testGenerateCustomerValidToken()
```suggestion
    public function testGenerateCustomerValidToken(): void
```

2021-07-05 09:28 UTC, khrystynastolbova commented
@ihor-sviziev and @eduard13, Thanks for your review and suggestions! I will make changes.
Maybe it would be better to move the logger test to GenerateCustomerTokenTest.php file and there add tearDown function to remove the customer log record? Because this test is failing
<img width="1610" alt="Screenshot 2021-07-05 at 12 16 34" src="https://user-images.githubusercontent.com/79088059/124449701-5ff53f00-dd8c-11eb-9a4b-0b99dc8cd475.png">

2021-07-05 12:08 UTC, khrystynastolbova commented
Please check my recent changes

2021-07-05 12:09 UTC, khrystynastolbova commented
@magento run all tests

2021-07-12 13:41 UTC, eduard13 requested changes
Good job. Could you apply these minor suggestions as well?

2021-07-12 13:41 UTC, eduard13 commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php
> +            $connection = $resource->getConnection(ResourceConnection::DEFAULT_CONNECTION);
```suggestion
            /** @var ResourceConnection $resource */
            $resource = Bootstrap::getObjectManager()->get(ResourceConnection::class);
            /** @var AdapterInterface $connection */
            $connection = $resource->getConnection(ResourceConnection::DEFAULT_CONNECTION);
```

2021-07-12 13:41 UTC, eduard13 commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php
> +
```suggestion
```

2021-07-12 13:42 UTC, eduard13 commented
@magento run Functional Tests EE, Functional Tests B2B

2021-07-20 05:30 UTC, eduard13 commented
@magento run Functional Tests EE, Functional Tests B2B

2021-07-20 15:47 UTC, eduard13 approved these changes

2021-07-20 15:48 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9157](https://jira.corp.magento.com/browse/ENGCOM-9157) has been created to process this Pull Request

2021-07-20 16:09 UTC, eduard13 commented
@magento run Functional Tests B2B

2021-07-26 07:39 UTC, khrystynastolbova commented
Hi @eduard13. Thanks for your review! I have applied your suggestions.

2021-08-30 06:34 UTC, eduard13 commented
@magento run all tests

2021-08-30 08:19 UTC, eduard13 requested changes
Hi @khrystynastolbova, could you please check the reason of failing Unit Tests builds?
Thank you.

2021-11-23 13:29 UTC, khrystynastolbova commented
@magento run all tests

2021-12-29 05:11 UTC, engcom-Lima commented
@magento run all tests

2021-12-30 05:55 UTC, engcom-Lima commented
@magento run Functional Tests CE

2021-12-30 07:17 UTC, engcom-Lima commented
@magento run Functional Tests CE

2021-12-30 09:04 UTC, engcom-Lima commented
@magento run Functional Tests CE

2021-12-30 10:25 UTC, engcom-Lima commented
@magento run Functional Tests CE

2021-12-30 12:34 UTC, engcom-Lima commented
Hi @eduard13 the tests are now passed, moving this PR to Pending Review

2021-12-30 17:25 UTC, eduard13 approved these changes
Looks good for me 👍
Thanks for your input @khrystynastolbova

2021-12-30 17:26 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9157](https://jira.corp.magento.com/browse/ENGCOM-9157) has been created to process this Pull Request

2022-01-04 08:52 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento lastest instance installed
2. Have one customer created for front end login as well


**Manual testing scenario:**

1. Make a note of customer last login time from _customer_log_ DB table (Customer id can be found in the _customer_entity_ table under _entity_id_ column).

2. Do get the customer token with GraphQL request
 
3. Re validate the customer last login is updated in the DB table.


**Before:** :heavy_multiplication_x: The last_login_at column data was not getting updated to the latest GraphQL login


**After:** :heavy_check_mark: The last_login_at column data was is getting updated to the latest GraphQL login


There is already a regression au-test has bee updated along with the PR changes, and hence no additional regression is required.

2022-06-10 14:22 UTC, ishakhsuvarov commented
@magento run all tests

2022-06-11 14:22 UTC, merged

2022-10-31 14:30 UTC, vishaljpatil commented
Hello @khrystynastolbova,

Can you please let us know about updating "last_logout_at" on customer revoke token using graphql (revokeCustomerToken).

On revoke token also customer log table "last_logout_at" column not updating.