Update code prepare for jquery new version
magento/magento2 pull request #33410
Opened 2021-07-02 14:55 UTC by mrtuvn

### Description (*)

Another collection files update for prepare for new version jquery

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-03 19:07 UTC, sivaschenko requested changes
Thanks for the pull request @mrtuvn ! Please see my comments

2021-07-03 19:07 UTC, sivaschenko commented on app/code/Magento/Catalog/view/adminhtml/web/catalog/product-attributes.js
> +                    self.iframe = $('#create_new_attribute_container').attr({
It looks like the iframe element is not referenced but created here, so I don't think this change is correct

2021-07-03 19:07 UTC, sivaschenko commented on lib/web/fotorama/fotorama.js
> +            (dir === 'vertical' ? 13 : 12) : (dir === 'vertical' ? 5 : 4)
Please do not edit built-in 3rd party libraries code

2021-07-03 19:09 UTC, sivaschenko commented
@mrtuvn please open the pull requests related to the Platform Health project (that includes JQuery upgrade) to `platform-health` branch and mark them with "Project: Platform Health" label. That will help to process them faster.

2021-07-04 17:30 UTC, sivaschenko approved these changes

2021-07-04 17:30 UTC, sivaschenko commented
@magento run all tests

2021-07-04 17:31 UTC, sivaschenko commented
Covered by existing functional tests

2021-07-05 05:35 UTC, ihor-sviziev approved these changes

2021-07-05 06:45 UTC, Den4ik approved these changes

2021-07-12 16:49 UTC, merged