#19710 Magento 2.3 images cache generation generates wrong hash for s…
magento/magento2 pull request #33413
Opened 2021-07-02 17:29 UTC by Nuranto

Solves #19710 

Issue description : when "product_image_white_borders" is set to 0 in the `view.xml` of a theme, the generated resized images are not generated with the correct hash.

2021-07-02 17:30 UTC, Nuranto commented
@magento run all tests

2021-07-03 08:16 UTC, Nuranto commented
@magento run Unit Tests

2021-07-03 10:28 UTC, Nuranto commented
@magento run all tests

2021-07-03 13:02 UTC, Nuranto commented
Sorry, I don't have EE, so I cannot fix this failing test

2021-07-05 06:43 UTC, Den4ik requested changes
@Nuranto Thanks for the contribution. Please look at my comments

2021-07-05 06:43 UTC, Den4ik commented on app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php
> +    public function build(array $imageArguments, int $scopeId = null, /*Theme*/ $theme = null): array
Please use type declaration instead of doc block + update function doc block

2021-07-05 06:43 UTC, Den4ik commented on app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php
> +    private function overwriteDefaultValues(array $imageArguments, /*Theme*/ $theme = null): array
Please use type declaration instead of doc block + update function doc block

2021-07-05 06:43 UTC, Den4ik commented on app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php
> +    private function hasDefaultFrame(/*Theme*/ $theme = null): bool
Please use type declaration instead of doc block + update function doc block

2021-07-05 06:59 UTC, Nuranto commented
@Den4ik Hi !

I did first (see first commit), but it won't pass the tests because it doesn't always use Theme model, but string or DataObject instead.

See : https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33413/b2043a21d971735134939d4ba827ab50/Unit/console-error-logs.html

And to be honest I didn't/don't had/have time to rewrite those tests accordingly.

2021-07-05 07:17 UTC, Den4ik commented
@Nuranto I see and looks unit tests should be updated too based on fixes

2021-07-15 10:17 UTC, Den4ik commented
@Nuranto Thanks for your contribution. I'm close this PR prior to https://github.com/magento/magento2/pull/33439 with fixed unit tests.

2021-07-15 10:17 UTC, closed without merging