[MFTF] Add product to the Cart if Backorders are allowed on Product level and Product Qty<=0
magento/magento2 pull request #33431
Opened 2021-07-06 14:39 UTC by AnnaAPak

### Description (*)
This is to check if Product can be added to the Cart if Backorders are allowed on Product level and Product Qty<=0

### Manual testing scenarios (*)
1. Login as Admin
2. Open the Edit Product page->Advanced Inventory
3. Set the "Backorders" select value to "Allow Qty Below 0"
4. Set product Qty to <0
5. Save product
6. Open the Product on the Storefront
7. Click the "Add to Cart" button
8. Assert that the Product is in the Cart

2021-07-06 14:40 UTC, AnnaAPak commented
@magento run all tests

2021-07-06 15:19 UTC, AnnaAPak commented
@magento run all tests

2021-07-07 15:21 UTC, shikhamis11 commented
@magento run Unit Tests, Functional Tests EE

2021-07-15 10:36 UTC, Den4ik approved these changes
✅ Approved.
Looks good for me

2021-07-15 10:36 UTC, Den4ik commented
@magento run Functional Tests EE

2021-07-15 10:37 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9150](https://jira.corp.magento.com/browse/ENGCOM-9150) has been created to process this Pull Request

2021-07-16 08:57 UTC, eduard13 approved these changes

2021-07-16 08:58 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9150](https://jira.corp.magento.com/browse/ENGCOM-9150) has been created to process this Pull Request

2021-07-17 07:37 UTC, shikhamis11 commented on app/code/Magento/Catalog/Test/Mftf/Test/StorefrontAddProductWithBackordersAllowedOnProductLevelToCartTest.xml
> +        <actionGroup ref="NavigateToCreatedProductEditPageActionGroup" stepKey="openEditBundleProduct">
@AnnaAPak Thank you for the pull request.
It looks good. 

I would like you to change the `stepKey` to more relevant. You can make it `openEditCreatedProduct` or `openEditSimpleProduct`

2021-07-17 07:39 UTC, shikhamis11 requested changes
https://github.com/magento/magento2/pull/33431/files#r671635660

2021-07-19 15:23 UTC, AnnaAPak commented
@magento run all tests

2021-07-19 15:24 UTC, AnnaAPak commented
@shikhamis11 requested changes have been added. Can you please review? Thanks.

2021-07-20 05:09 UTC, shikhamis11 commented
@magento run Unit Tests, Functional Tests EE, Functional Tests B2B

2021-07-20 10:46 UTC, shikhamis11 commented
@magento run Functional Tests B2B

2021-07-20 18:29 UTC, shikhamis11 approved these changes

2021-07-20 18:33 UTC, magento-engcom-team commented
Hi @shikhamis11, thank you for the review.
[ENGCOM-9150](https://jira.corp.magento.com/browse/ENGCOM-9150) has been created to process this Pull Request

2021-07-30 10:09 UTC, engcom-Charlie commented
@magento create issue

2021-07-30 12:52 UTC, engcom-Charlie commented
:heavy_check_mark: QA Passed

The newly created auto tests are valid.

The test case is working fine. Please find the Allure report for the same.

![image](https://user-images.githubusercontent.com/51680850/127655547-5990f1ba-4011-4311-86e9-beec090db735.png)

2021-08-20 15:27 UTC, merged