Fixes #33430
magento/magento2 pull request #33432
Opened 2021-07-06 15:49 UTC by AntonEvers

### Description (*)

fix the exceptions mentioned in https://github.com/magento/magento2/issues/33430

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33430

### Manual testing scenarios (*)

1. Install Magento as 2.4-develop
2. run `vendor/bin/phpmd app/code ansi dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml`

You should see no execution errors or warnings, just phpmd violations

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-07 07:47 UTC, ihor-sviziev commented
@magento run all tests

2021-07-07 08:50 UTC, ihor-sviziev commented
@magento run Unit Tests

2021-07-07 09:19 UTC, ihor-sviziev commented
@magento run WebAPI Tests

2021-07-07 09:41 UTC, ihor-sviziev approved these changes

2021-07-07 09:48 UTC, ihor-sviziev commented
I did QA for this PR:

**Before these changes applied:**
❌ 

<details>
<summary>Click to toggle the output</summary>

```
vendor/bin/phpmd app/code ansi dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 113

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 113
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 113

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 113
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 113
...
Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142
PHP Notice:  Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142

Notice: Undefined offset: 0 in /var/www/html/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/CookieAndSessionMisuse.php on line 142
...

ERROR while parsing /var/www/html/app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/DownloadableLinkDataProvider.php
----------------------------------------------------------------------------------------------------------------------
The parser has reached an invalid state near line "35" in file "/var/www/html/app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/DownloadableLinkDataProvider.php". Please check the following conditions: Mandatory expression expected.

ERROR while parsing /var/www/html/app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/SuperAttributeDataProvider.php
--------------------------------------------------------------------------------------------------------------------
The parser has reached an invalid state near line "35" in file "/var/www/html/app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/SuperAttributeDataProvider.php". Please check the following conditions: Mandatory expression expected.

ERROR while parsing /var/www/html/app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/SuperGroupDataProvider.php
----------------------------------------------------------------------------------------------------------------
The parser has reached an invalid state near line "35" in file "/var/www/html/app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/SuperGroupDataProvider.php". Please check the following conditions: Mandatory expression expected.
...
```
</details>


**After changes applied:**
✔ The only VIOLATIONs are shown, no warning, errors, notices

<details>
<summary>Click to toggle the output</summary>

```
$ vendor/bin/phpmd app/code ansi dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml

FILE: /var/www/html/app/code/Magento/AdminNotification/Controller/Adminhtml/System/Message/ListAction.php
---------------------------------------------------------------------------------------------------------
 11   | VIOLATION | The class Magento\AdminNotification\Controller\Adminhtml\System\Message\ListAction does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface

FILE: /var/www/html/app/code/Magento/AdvancedSearch/Controller/Adminhtml/Search/System/Config/TestConnection.php
----------------------------------------------------------------------------------------------------------------
 15   | VIOLATION | The class Magento\AdvancedSearch\Controller\Adminhtml\Search\System\Config\TestConnection does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface

FILE: /var/www/html/app/code/Magento/Analytics/Controller/Adminhtml/Subscription/Retry.php
------------------------------------------------------------------------------------------
 19   | VIOLATION | The class Magento\Analytics\Controller\Adminhtml\Subscription\Retry does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface
FILE: /var/www/html/app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Bulk/Retry.php
-----------------------------------------------------------------------------------------------
 19   | VIOLATION | The class Magento\AsynchronousOperations\Controller\Adminhtml\Bulk\Retry does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface

FILE: /var/www/html/app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Index/Index.php
------------------------------------------------------------------------------------------------
 9    | VIOLATION | The class Magento\AsynchronousOperations\Controller\Adminhtml\Index\Index does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface

FILE: /var/www/html/app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Notification/Dismiss.php
---------------------------------------------------------------------------------------------------------
 16   | VIOLATION | The class Magento\AsynchronousOperations\Controller\Adminhtml\Notification\Dismiss does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface

FILE: /var/www/html/app/code/Magento/AwsS3/Driver/AwsS3.php
-----------------------------------------------------------
 36   | VIOLATION | The class AwsS3 has a coupling between objects value of 14. Consider to reduce the number of dependencies under 13.

FILE: /var/www/html/app/code/Magento/AwsS3/Test/Mftf/Helper/MockTestLogger.php
------------------------------------------------------------------------------
 19   | VIOLATION | Avoid unused parameters such as '$context'.
 24   | VIOLATION | Avoid unused parameters such as '$message'.
 24   | VIOLATION | Avoid unused parameters such as '$context'.
 29   | VIOLATION | Avoid unused parameters such as '$context'.
 34   | VIOLATION | Avoid unused parameters such as '$context'.
 39   | VIOLATION | Avoid unused parameters such as '$message'.
 39   | VIOLATION | Avoid unused parameters such as '$context'.
 44   | VIOLATION | Avoid unused parameters such as '$message'.
 44   | VIOLATION | Avoid unused parameters such as '$context'.
 49   | VIOLATION | Avoi [...]

2021-07-07 09:49 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-07-07 12:44 UTC, ihor-sviziev commented
@sivaschenko, can it be added to the Platform Health project?

2021-07-07 12:45 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-07-07 19:09 UTC, Den4ik requested changes
@AntonEvers Thanks for PR. Please update composer v2 for update

2021-07-07 19:09 UTC, Den4ik commented on composer.lock
> +    "plugin-api-version": "1.1.0"
Please use composer v2

2021-07-07 19:44 UTC, ihor-sviziev commented on composer.lock
> +    "plugin-api-version": "1.1.0"
I don't think it is important

2021-07-07 19:52 UTC, Den4ik commented
@ihor-sviziev All PRs to platform-health updated with composer v2

2021-07-12 10:54 UTC, sivaschenko commented
Should be merged after https://github.com/magento/magento2/pull/33225

2021-07-15 10:20 UTC, Den4ik commented
@AntonEvers Please resolve merge conflict

2021-07-23 12:13 UTC, ihor-sviziev requested changes
Hi @AntonEvers,
Could you resolve the conflict and double-check your changes after the https://github.com/magento/magento2/pull/33569 was merged?

2021-07-23 12:30 UTC, andrewbess requested changes
Hello @AntonEvers 
Thank you for your contribution.
Could you please resolve merge conflicts.
Thank you in advance.

2021-07-26 08:05 UTC, andrewbess commented
@magento run all tests

2021-07-26 08:08 UTC, AntonEvers commented
Merge conflict resolved. Results after merge are OK:

```
Æ 2021-07-26 09:44:14 CEST magento2 git phpmd → vendor/bin/phpmd app/code ansi dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml

FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AdminNotification/Controller/Adminhtml/System/Message/ListAction.php
--------------------------------------------------------------------------------------------------------------------------------
 11   | VIOLATION | The class Magento\AdminNotification\Controller\Adminhtml\System\Message\ListAction does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AdvancedSearch/Controller/Adminhtml/Search/System/Config/TestConnection.php
---------------------------------------------------------------------------------------------------------------------------------------
 15   | VIOLATION | The class Magento\AdvancedSearch\Controller\Adminhtml\Search\System\Config\TestConnection does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Analytics/Controller/Adminhtml/Subscription/Retry.php
-----------------------------------------------------------------------------------------------------------------
 19   | VIOLATION | The class Magento\Analytics\Controller\Adminhtml\Subscription\Retry does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Bulk/Retry.php
----------------------------------------------------------------------------------------------------------------------
 19   | VIOLATION | The class Magento\AsynchronousOperations\Controller\Adminhtml\Bulk\Retry does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Index/Index.php
-----------------------------------------------------------------------------------------------------------------------
 9    | VIOLATION | The class Magento\AsynchronousOperations\Controller\Adminhtml\Index\Index does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AsynchronousOperations/Controller/Adminhtml/Notification/Dismiss.php
--------------------------------------------------------------------------------------------------------------------------------
 16   | VIOLATION | The class Magento\AsynchronousOperations\Controller\Adminhtml\Notification\Dismiss does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AwsS3/Driver/AwsS3.php
----------------------------------------------------------------------------------
 29   | VIOLATION | The class AwsS3 has a coupling between objects value of 14. Consider to reduce the number of dependencies under 13.


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AwsS3/Test/Mftf/Helper/MockTestLogger.php
-----------------------------------------------------------------------------------------------------
 19   | VIOLATION | Avoid unused parameters such as '$context'.
 24   | VIOLATION | Avoid unused parameters such as '$message'.
 24   | VIOLATION | Avoid unused parameters such as '$context'.
 29   | VIOLATION | Avoid unused parameters such as '$context'.
 34   | VIOLATION | Avoid unused parameters such as '$context'.
 39   | VIOLATION | Avoid unused parameters such as '$message'.
 39   | VIOLATION | Avoid unused parameters such as '$context'.
 44   | VIOLATION | Avoid unused parameters such as '$message'.
 44   | VIOLATION | Avoid unused parameters such as '$context'.
 49   | VIOLATION | Avoid unused parameters such as '$message'.
 49   | VIOLATION | Avoid unused parameters such as '$context'.
 54   | VIOLATION | Avoid unused parameters such as '$message'.
 54   | VIOLATION | Avoid unused parameters such as '$context'.
 59   | VIOLATION | Avoid unused parameters such as '$level'.
 59   | VIOLATION | Avoid unused parameters such as '$message'.
 59   | VIOLATION | Avoid unused parameters such as '$context'.


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/AwsS3/Test/Unit/Driver/AwsS3Test.php
------------------------------------------------------------------------------------------------
 68   | VIOLATION | The method getAbsolutePathDataProvider() has 100 lines of code. Current threshold is set to 100. Avoid really long methods.


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/App/Action/Context.php
------------------------------------------------------------------------------------------
 25   | VIOLATION | The class Magento\Backend\App\Action\Context uses sessions or cookies while not being a part of HTML Presentation layer


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/App/Response/Http/FileFactory.php
-----------------------------------------------------------------------------------------------------
 14   | VIOLATION | The class Magento\Backend\App\Response\Http\FileFactory uses sessions or cookies while not being a part of HTML Presentation layer


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/Controller/Adminhtml/Ajax/Translate.php
-----------------------------------------------------------------------------------------------------------
 11   | VIOLATION | The class Magento\Backend\Controller\Adminhtml\Ajax\Translate does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/Controller/Adminhtml/Auth/DeniedIframe.php
--------------------------------------------------------------------------------------------------------------
 9    | VIOLATION | The class Magento\Backend\Controller\Adminhtml\Auth\DeniedIframe does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/Controller/Adminhtml/BackendApp/Redirect.php
----------------------------------------------------------------------------------------------------------------
 13   | VIOLATION | The class Magento\Backend\Controller\Adminhtml\BackendApp\Redirect does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/Controller/Adminhtml/Cache/MassDisable.php
--------------------------------------------------------------------------------------------------------------
 17   | VIOLATION | The class Magento\Backend\Controller\Adminhtml\Cache\MassDisable does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/Controller/Adminhtml/Cache/MassEnable.php
-------------------------------------------------------------------------------------------------------------
 17   | VIOLATION | The class Magento\Backend\Controller\Adminhtml\Cache\MassEnable does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/Controller/Adminhtml/Cache/MassRefresh.php
--------------------------------------------------------------------------------------------------------------
 12   | VIOLATION | The class Magento\Backend\Controller\Adminhtml\Cache\MassRefresh does not restrict processed HTTP methods by implementing a Http*Method name*ActionInterface


FILE: /Users/evers/web/AntonEvers/magento2/app/code/Magento/Backend/Controller/Adminhtml/Denied.php
------------------------------------------------------------------------------------------- [...]

2021-07-26 09:57 UTC, andrewbess commented
Hello @AntonEvers 
Thank you for resolving merge conflicts.
Functional tests cannot be passed successfully because external currency service still unavailable.
<img width="1588" alt="503-in-console" src="https://user-images.githubusercontent.com/10788564/126970464-ad03c2f3-4170-4ab9-a923-537bbaaf86a2.png">
<img width="1353" alt="api-server-status" src="https://user-images.githubusercontent.com/10788564/126970484-18d197e2-bc6f-4e98-8195-ed9fce8280d0.png">
This PR will be merged a little bit later.

2021-07-26 09:57 UTC, ihor-sviziev approved these changes

2021-07-26 10:11 UTC, andrewbess approved these changes
app

2021-07-26 10:12 UTC, merged