Do not filter customer orders by current store ID in GraphQL
magento/magento2 pull request #33451
Opened 2021-07-09 15:38 UTC by pawel-siejba

Do not filter customer orders by current store ID in GraphQL

### Description (*)

In Venia, for globally shared customer accounts it is expected to see all orders assigned to the account, not only the ones from the current store. This is also how it worked in Luma.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33450

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-09 15:44 UTC, pawel-siejba commented
@magento run all tests

2021-07-12 08:52 UTC, pawel-siejba commented
@magento run all tests

2021-07-15 10:44 UTC, Den4ik requested changes
@pawel-siejba Please look at my comment.

**CC** @gabrieldagama @ihor-sviziev

2021-07-15 10:44 UTC, Den4ik commented on app/code/Magento/SalesGraphQl/Model/Resolver/CustomerOrders/Query/OrderFilter.php
> +        int $userId
I'm not sure that removing argument from public method is a good idea.
I believe that we can make `$storeId` nullable or provide new method and deprecate current that more preferable

2021-07-27 09:02 UTC, pawel-siejba commented
@magento run all tests

2021-07-28 17:26 UTC, cpartica approved these changes

2021-07-28 17:26 UTC, cpartica commented on app/code/Magento/SalesGraphQl/Model/Resolver/CustomerOrders.php
> +            $searchResult = $this->getSearchResult($args, (int)$userId);
The behavior should be with a filter in the orders
by default we shouldn't filter by store code but I think there's use cases when we should.

Luma doesn't have that capability to provide a filter and we should make GQL more flexible

could you also implement the filter and leaving by default the behavior you just implemented because is consistent with Luma?

2021-07-28 17:26 UTC, cpartica commented on app/code/Magento/SalesGraphQl/Model/Resolver/CustomerOrders.php
> +            $searchResult = $this->getSearchResult($args, (int)$userId);
I consulted with my peers on this topic and it seems we want to be more flexible on this functionality 
but there's reasoning to split this as a followup story and merge this as it is

2021-07-29 09:51 UTC, Den4ik approved these changes

2021-07-29 09:52 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9166](https://jira.corp.magento.com/browse/ENGCOM-9166) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-07-30 08:03 UTC, engcom-Hotel commented
@magento run all tests

2021-08-02 09:23 UTC, engcom-Hotel commented
Hello @pawel-siejba,

We have tested the below scenarios for this fix:
1. If "Share Customer Accounts" is set to "Global", orders placed on same-store should visible in response - **Passed**
2. If "Share Customer Accounts" is set to "Global", orders placed on multiple stores by a user, should be visible in response - **Passed**.
3. If "Share Customer Accounts" is set to "Per Website", orders place on multiple stores by a user should not be visible - **Failed**.

I have a suggestion on this fix, that if "Share Customer Accounts" is set to "Global" and header named "Store" present in the request then, orders should display for that store only and if it is not present then all orders should display in response.

Thanks

2021-09-06 08:44 UTC, engcom-Hotel requested changes
As per my comment on [link](https://github.com/magento/magento2/pull/33451#issuecomment-890872218), moving this PR in changes requested.

2021-09-07 10:58 UTC, Den4ik commented
@pawel-siejba could you check the QA results?

2021-12-29 04:16 UTC, engcom-Bravo commented
@magento run all tests

2021-12-29 07:24 UTC, engcom-Bravo commented
@magento run all tests

2021-12-29 09:43 UTC, engcom-Bravo commented
@magento run all tests

2021-12-29 12:43 UTC, engcom-Bravo commented
@magento run Functional Tests CE

2022-08-18 07:11 UTC, engcom-Charlie commented
Hi @engcom-Alfa,

As per associated [JIRA](https://jira.corp.adobe.com/browse/AC-723) comment from @cpartica, we have introduced a flag which can switch between the website and store. Please check it with the current version and close this ticket if this was fixed.

Hence moving it to Testing.

Thank you!

2022-08-23 13:21 UTC, engcom-Lima commented
@magento run Magento Health Index

2022-08-24 10:47 UTC, engcom-Lima commented
@magento run Magento Health Index

2022-08-24 11:04 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**

- Fresh 2.4-develop should be installed.
- Create multistore views.
- Customer account shared globally

**Manual testing scenario:**

1. Place orders from different store views.
2. Run below graphql query to get all the order details from various stores:

```
query{ 
  customer
  { 
    orders 
    { items 
      { number 
      } 
    } 
  } 
}
```

**Before:** :heavy_multiplication_x: See only orders from the currently selected store(Store header)
![Screenshot from 2022-08-24 16-18-48](https://user-images.githubusercontent.com/60198022/186402966-514c256e-2688-44c8-9e84-f014c8ca4c94.png)

**After:** :heavy_check_mark:  See all orders from other store views as well
![Screenshot from 2022-08-24 16-25-06](https://user-images.githubusercontent.com/60198022/186403008-7c5fda77-19bf-4912-997d-78e41d4f3fd6.png)

**Additional scenanrio:**
Tested with multiple websites.

Some checks are failed hence, moving it to Extended Testing.

2022-08-24 17:52 UTC, engcom-Charlie commented
@magento run Magento Health Index

2022-08-26 04:59 UTC, engcom-Charlie commented
It seems that bot moved the PR in Changes Requested column so moving back to Extended Testing.

Thank you!

2022-09-08 12:35 UTC, engcom-Lima commented
@magento run Magento Health Index

2022-09-14 06:41 UTC, engcom-Lima commented
@magento run Magento Health Index

2022-09-19 12:22 UTC, engcom-Lima commented
@magento run Magento Health Index

2022-09-27 13:23 UTC, engcom-Charlie commented
We have did investigation on the feature mentioned by @cpartica in [JIRA](https://jira.corp.adobe.com/browse/AC-723).

As he mentioned, we found out that the internal team have introduced a flag in committed [revision](https://github.com/magento/magento2/search?q=commit%3A+ace41d1&type=commits) which can switch between the website and store which actually resolving the issue raised in this PR.

**scope: ScopeTypeEnum @doc(description: "Specifies the scope to search for customer orders. The Store request header identifies the customer's store view code. The default value of STORE limits the search to the value specified in the header. Specify WEBSITE to expand the search to include all customer orders assigned to the website that is defined in the header, or specify GLOBAL to include all customer orders across all websites and stores."),**

query{
  customer
  {
    orders(scope:GLOBAL)
    { items
      { number
      }
    }
  }
}

We have also tested the above scope flag and its working fine in latest magento 2.4-develop. Now globally shared customer accounts can see all orders assigned to the account, not only the ones from the current store; as we pass above scope.

As the purpose of the PR has been already taken care hence closing this PR.

Thank you!

2022-09-27 13:23 UTC, closed without merging