33465 Varnish cache adding top menu category ids to all page cache tags
magento/magento2 pull request #33468
Opened 2021-07-12 15:25 UTC by Jitheesh

### Description (*)
https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php#L88

Magento is using type comparison for determining varnish cache is enabled or not. But it returns false even if varnish is enabled.

This is because of following comparison; "2" === 2

Based on following code, I think it expected to skip adding tags for a top menu block
` $isEsiBlock = $block->getTtl() > 0;
                    if ($isVarnish && $isEsiBlock) {
                        continue;
                    }`

For Topmenu block we have TTL value so that $isEsiBlock become true and with my fix, $isVarnish will also become true.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33465

### Manual testing scenarios (*)

1. Enable varnish cache and make sure it is running
2. Open home page or any CMS page example: /about-us
3. Check Magento cache Tags.
4. Cache tags won't include top category IDs after merging this PR

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-12 16:34 UTC, hostep commented
Auwch, this was initially implemented correctly by https://github.com/magento/magento2/commit/b59dc722059f3a87716a41dc0f5ae62ec297fb69, but then reverted partially by https://github.com/magento/magento2/commit/1778c0f73570f19f9f368a18ff0808a6177f96e2

@gabrieldagama: is there news from the Fastly module around this, maybe they fixed something at their end to get their module working with this change?

2021-07-13 01:51 UTC, mrtuvn commented
another pr supprised me with reverted code. Can't wait to hear any news from fastly

2021-07-13 05:46 UTC, Jitheesh commented
Looks like these issues are also related 

- #30128
- #29806
- #25670

To replicate this issue try following steps

- Open a CMS page and make sure it is delivered from cache
- Edit price and stock status of a single product from top level category
- Run indexers
- Validate PURGE requests sent by Magento, it will contains tags like cat_c_<categoryid>
- Refresh CMS page, it will served from server instead of cache

2021-07-13 06:55 UTC, mrtuvn commented
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/PageCache/Observer/ProcessLayoutRenderElement.php#L123
Seem we not check type here too

2021-07-13 07:10 UTC, ihor-sviziev commented
Maybe it worth fixing the following code as well (convert to int)? https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php#L88

2021-07-13 07:22 UTC, mrtuvn commented
Found this one :)
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/PageCache/Observer/ProcessLayoutRenderElement.php#L123

2021-07-13 09:07 UTC, ihor-sviziev requested changes
Could you fix the following code as well (convert to int)? https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php#L88

2021-07-13 09:15 UTC, hostep commented
@ihor-sviziev: I don't think that is necessary. If the `getType` method always returns an int, why would we then need to cast it again to an int?

2021-07-13 09:18 UTC, ihor-sviziev commented
@hostep, unfortunately, we already had a case when conversion to int was reverted for some reason,  and I don't want to get it back. The missing return type can't guarantee that we will have int. I think it's better to add such conversion where it's used to make sure this issue won't appear again.

2021-07-13 09:25 UTC, hostep commented
Hmm you might have a point, I just quickly investigated the Fastly module's code

https://github.com/fastly/fastly-magento2/blob/707ffb3779a1d3c7921b81a88a69c5613490a702/Observer/FlushAllCacheObserver.php#L61

Their `Config::FASTLY` constant is not an `int` but a `string`: https://github.com/fastly/fastly-magento2/blob/707ffb3779a1d3c7921b81a88a69c5613490a702/Model/Config.php#L48

But this is a terrible bug in Fastly's code, Magento says in the documentation that the return type of the `getType()` method should be an int and they ignore that.

So either Fastly needs to rewrite a bunch of their code, or Magento needs to accomodate for that and since Magento Cloud is always using that Fastly module, Adobe will probably not accept this PR as is.
So we'll probably need to take @ihor-sviziev's advice. And don't cast to an `int` in the `getType()` method unfortunately, and maybe also need to change the phpdoc to `@return int|string` for that method?

Let's try to pull in @vvuksan from the Fastly module team: what do you think about this?

2021-07-13 10:09 UTC, Jitheesh commented
> Could you fix the following code as well (convert to int)?
> 
> https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php#L88

Instead of converting to int, can we skip  type comparison ? ie change === to ==

2021-07-13 10:09 UTC, mrtuvn commented
Maybe we can check vanish enable like this 

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/PageCache/Observer/ProcessLayoutRenderElement.php#L123

2021-07-13 11:23 UTC, ihor-sviziev commented
> > Could you fix the following code as well (convert to int)?
> > https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php#L88
> 
> Instead of converting to int, can we skip type comparison ? ie change === to ==

TBH I don't think it's a good option, as not strict comparison might cause additional not expected issues.

2021-07-13 12:18 UTC, Jitheesh commented
> > > Could you fix the following code as well (convert to int)?
> > > https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php#L88
> > 
> > 
> > Instead of converting to int, can we skip type comparison ? ie change === to ==
> 
> TBH I don't think it's a good option, as not strict comparison might cause additional not expected issues.

In this case, should we update other places reported by @mrtuvn  https://github.com/magento/magento2/blob/6e47ef392be785ad72e46eefbd00e9bd1ef40866/app/code/Magento/PageCache/Observer/ProcessLayoutRenderElement.php#L123

2021-07-13 12:18 UTC, ihor-sviziev commented
@Jitheesh, yes, please

2021-07-13 12:57 UTC, ihor-sviziev commented
@magento run all tests

2021-07-13 15:37 UTC, vvuksan commented
@hostep if something needs to be fixed in the Fastly module please open up an issue and we'll take a look.

2021-07-13 16:03 UTC, hostep commented
@vvuksan: I'm not using the Fastly module, so I'm not interested in reporting bugs.
I'm just getting you involved because a bug was introduced in core Magento to prevent another bug to happen in the Fastly module, by this commit: https://github.com/magento/magento2/commit/1778c0f73570f19f9f368a18ff0808a6177f96e2 (it would have been better to fix this in the Fastly module than to revert that change in core Magento which introduced the problem that this PR is trying to fix).
If you are interested in this, please read through the entire thread, I think the info is clear enough to understand what is going on.

2021-07-15 13:12 UTC, mrtuvn commented
@magento run Unit Tests, Functional Tests B2B

2021-07-16 03:16 UTC, mrtuvn commented
Hi @Jitheesh Can you recheck Unit Tests

2021-07-16 03:18 UTC, mrtuvn commented
@magento run Unit Tests

2021-07-20 15:07 UTC, ihor-sviziev commented
FYI I reported an issue to Fastly extension https://github.com/fastly/fastly-magento2/issues/466

2021-07-23 04:30 UTC, tanghongtanghong commented on app/code/Magento/PageCache/Model/Config.php
> -     * @return int
看

2021-08-03 20:04 UTC, ihor-sviziev commented
Update: Fastly has updated their module in https://github.com/fastly/fastly-magento2/pull/469.
I think we can introduce conversion to int inside the getType method. What do you think?

2021-08-04 00:29 UTC, mrtuvn commented
That is quick change from fastly. Now from magento end i think update will be quick with less file changed

2021-08-04 04:01 UTC, mrtuvn commented
Now  i think we have free to change from magento side

2021-08-04 04:17 UTC, ihor-sviziev requested changes
Hi @Jitheesh,
Fastly has fixed an issue on their side.
Could you add the conversion to int to the getType method, and remove in other places?

2021-08-04 05:20 UTC, ihor-sviziev commented
Great! Thank you!

2021-08-04 05:20 UTC, ihor-sviziev commented
@magento run all tests

2021-08-04 09:38 UTC, mrtuvn commented
@Jitheesh, Can you check unit test fail case related when change file app/code/Magento/PageCache/Observer/ProcessLayoutRenderElement.php

2021-08-31 12:12 UTC, engcom-Bravo commented
@Jitheesh @ihor-sviziev and @mrtuvn  Thanks for your contribution!
@Jitheesh I am working on the requested changes.

2021-09-01 11:04 UTC, engcom-Bravo commented
@magento run all tests

2021-09-01 13:37 UTC, engcom-Bravo commented
Hi @mrtuvn

I have updated the PR with requested changes.
Can you please review PR.

2021-09-01 13:48 UTC, ihor-sviziev commented
Looks like false positives. Let's try to re-run them

@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

2021-09-01 20:54 UTC, ihor-sviziev approved these changes

2021-09-01 20:56 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9207](https://jira.corp.magento.com/browse/ENGCOM-9207) has been created to process this Pull Request

2021-10-04 08:41 UTC, ihor-sviziev commented
@engcom-Alfa, any updates about testing of this PR?

2021-10-11 05:01 UTC, engcom-Alfa commented
> @engcom-Alfa, any updates about testing of this PR?

I am picking it now, and will update soon here.
Thanks for your patience!

2021-10-13 13:00 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Install a Magento with sample data
2. Install Varnish cache and make sure it is configured to Magento


**Manual testing scenario:**

1. Open the frontend and be in home page.

2. Inspect the page and be in network tab of the developer tool in the browser
 
3. Refresh the page and check the response headers' _cache tags_ parameters

4. Repeat the same steps by navigating to About-us or any other CMS page


**Before:** :heavy_multiplication_x: cat_c were getting included in the Cache-tags

![image](https://user-images.githubusercontent.com/51679138/137137210-6659d5f8-c50f-48c4-bf62-2bc03b04700c.png)


**After:** :heavy_check_mark:  cat_c are getting excluded in the Cache-tags

![image](https://user-images.githubusercontent.com/51679138/137137381-6319e2c5-e553-4372-9228-d507a93ad2eb.png)

Since it is relevant to getting the response from cache and so there is no additional testing is requited as part of regression.

2021-11-12 21:19 UTC, merged

2022-01-27 14:48 UTC, kestraly commented
In the PR - Changes made to app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php  https://github.com/magento/magento2/commit/f9b9ec1b2348970b49e18f3e7544424886b642b5 seems slow down loading times to uncached levels of speed at 1.5s with this change in place. 

I'm wondering if it's a combination of using Redis for FPC for this instance or not, so I'll do some experimenting.

 Reverting back to the original method of != in that file brings cached pages back down to 200ms.