Improve requirejs load files
magento/magento2 pull request #33483
Opened 2021-07-14 13:47 UTC by mrtuvn

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-14 14:21 UTC, ihor-sviziev commented
FYI it's partly duplicates https://github.com/magento/magento2/pull/30647

2021-07-14 14:23 UTC, ihor-sviziev commented
@magento run all tests

2021-07-15 03:15 UTC, mrtuvn commented
@magento run Static Tests, Integration Tests, Functional Tests CE, Functional Tests EE

2021-07-21 06:02 UTC, ihor-sviziev commented
@magento run all tests

2021-07-21 11:05 UTC, mrtuvn commented
@magento run all tests

2021-07-21 14:20 UTC, mrtuvn commented
@magento run all tests

2021-07-22 03:39 UTC, mrtuvn commented
@magento run Functional Tests B2B

2021-07-22 08:12 UTC, Den4ik commented
@magento run Unit Tests, Functional Tests EE, Functional Tests B2B

2021-07-22 08:49 UTC, Den4ik commented
@mrtuvn Could you please check failed unit tests

2021-07-22 13:26 UTC, eduard13 requested changes
Hi @mrtuvn, can you please separate the RequireJs upgrade as a separate PR and do all the rest of improvements separately later?

Thank you.

2021-07-22 13:28 UTC, mrtuvn commented
Sure! Will revert that

2021-07-22 15:35 UTC, mrtuvn commented
@magento run all tests

2021-07-22 17:54 UTC, eduard13 commented
@mrtuvn, looks like it got a bit messed up right now. Could you please open a new PR with RequireJS upgrade only?
Thank you.

2021-07-23 00:24 UTC, mrtuvn commented
@magento run all tests

2021-07-23 11:44 UTC, Den4ik commented
@mrtuvn I'm not sure that we should include PRs to 2.4-develop branch into "Related Pull Requests" section because as I'm correct they are merging for running the tests and looks like it's the reason for failed static tests.
@sivaschenko Is I correct?

2021-07-23 11:49 UTC, Den4ik commented
https://github.com/magento/magento2/pull/33541

2021-07-23 12:05 UTC, eduard13 commented
@Den4ik as far as I know, relating PRs doesn't work within the same repository. We can link CE - EE, but not CE - CE. So that section doesn't have any effect in this case. However, I might be wrong.

@mrtuvn could you please open a **new** PR with RequireJS upgrade only ⚠️ ?

2021-07-23 12:08 UTC, mrtuvn commented
@magento run Static Tests, Functional Tests B2B, Functional Tests CE

2021-07-23 12:11 UTC, mrtuvn commented
@Den4ik related PR functional seem not working as expected. But thank for let me know that
@eduard13 i have created in another seperate PR

2021-07-23 21:52 UTC, Den4ik commented
@magento run Functional Tests B2B

2021-07-24 09:45 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-07-24 14:46 UTC, mrtuvn commented
@magento run all tests

2021-07-25 01:48 UTC, mrtuvn commented
@magento run Functional Tests CE, Static Tests

2021-07-25 03:59 UTC, mrtuvn commented
Squash commits
@magento run all tests

2021-07-25 04:05 UTC, mrtuvn commented
Squash commits + rebase branch
@magento run all tests

2021-07-25 07:01 UTC, mrtuvn commented
@magento run Functional Tests EE

2021-08-02 13:21 UTC, mrtuvn commented
@magento run all tests

2021-08-09 01:16 UTC, mrtuvn commented
@magento run WebAPI Tests, Functional Tests EE, Functional Tests CE

2021-08-09 05:06 UTC, ihor-sviziev commented
@magento run Functional Tests CE

2021-08-18 04:19 UTC, ihor-sviziev approved these changes

2021-08-18 04:20 UTC, ihor-sviziev commented
@sidolov, this PR reduces amount of loaded files and improving frontend performance. I think priority should be increased to P2

2021-08-18 04:20 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9184](https://jira.corp.magento.com/browse/ENGCOM-9184) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-08-18 07:09 UTC, mrtuvn commented
Just find one file 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L10-L72

component `consoleLogger` always requested by default

2021-08-18 08:45 UTC, ihor-sviziev commented
@mrtuvn TBH I think we can remove it after https://github.com/magento/magento2/pull/32244

2021-08-19 13:11 UTC, Den4ik approved these changes

2021-08-19 13:12 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9184](https://jira.corp.magento.com/browse/ENGCOM-9184) has been created to process this Pull Request

2021-08-26 05:56 UTC, ihor-sviziev commented
@sidolov, since this change improves frontend performance, I suggest increasing priority to P2.

2021-08-26 14:56 UTC, sidolov commented
@mrtuvn , @ihor-sviziev do we have performance measurements for provided changes? Thanks!

2021-12-01 07:48 UTC, mrtuvn commented
@magento run all tests

2021-12-02 06:07 UTC, mrtuvn commented
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

2021-12-06 15:19 UTC, mrtuvn commented
@magento run all tests

2021-12-06 23:16 UTC, mrtuvn commented
@magento run Unit Tests

2022-05-11 15:55 UTC, ihor-sviziev requested changes

2022-05-11 15:55 UTC, ihor-sviziev commented on app/code/Magento/PageCache/view/frontend/web/js/page-cache.js
> +
looks like it should be for `el`
```suggestion
                    var iframeHostName;

                    // prevent cross origin iframe content reading
                    if ($(el).prop('tagName') === 'IFRAME') {
                        iframeHostName = $('<a>').prop('href', $(el).prop('src'))
                            .prop('hostname');

                        if (window.location.hostname !== iframeHostName) {
                            return [];
                        }
                    }

```

2022-05-11 23:55 UTC, mrtuvn commented on app/code/Magento/PageCache/view/frontend/web/js/page-cache.js
> +
Updated as your suggestion

2022-05-11 23:59 UTC, mrtuvn commented
@magento run all tests

2022-09-17 10:16 UTC, mrtuvn commented
@magento run all tests

2022-09-17 15:14 UTC, mrtuvn commented
@magento run all tests

2022-09-18 01:11 UTC, mrtuvn commented
@magento run Integration Tests, Unit Tests

2023-03-16 15:14 UTC, mrtuvn commented
@magento run all tests

2023-03-17 00:04 UTC, mrtuvn commented
@magento run Static Tests, Unit Tests

2023-05-24 07:25 UTC, engcom-Hotel commented
Hello @mrtuvn,

I can see the PR is in the Draft status. Can you please let us know if is there anything pending in this PR?

Thanks

2023-06-01 14:50 UTC, mrtuvn commented
Sorry but current i don't have enought spare time for continue with this. Feel free for all to create new PR for this if interested

2023-06-05 11:51 UTC, engcom-Hotel commented
> Sorry but current i don't have enough spare time for continue with this. Feel free for all to create new PR for this if interested

2023-06-05 11:53 UTC, engcom-Hotel commented
Hello @mrtuvn,

As per your comment [here](https://github.com/magento/magento2/pull/33483#issuecomment-1572203286), we are closing this PR:

> Sorry but current i don't have enough spare time for continue with this. Feel free for all to create new PR for this if interested

Whenever you want to resume on this PR, you can reopen it or ask us to reopen.

Thanks

2023-06-05 11:53 UTC, closed without merging