Add caching for product attributes used in sales rules
magento/magento2 pull request #33537
Opened 2021-07-20 14:07 UTC by ihor-sviziev

### Description (*)
This PR improves response time & reduces load to DB while fetching list of carts using WebAPI:
```bash
curl --location -g --request GET 'https://www.magento24.test/index.php/rest/default/V1/carts/search?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][condition_type]=gt&searchCriteria[sortOrders][0][field]=updated_at&searchCriteria[sortOrders][0][direction]=DESC&searchCriteria[currentPage]=1&searchCriteria[pageSize]=50&searchCriteria[filter_groups][0][filters][0][value]=2021-06-25+12%3A00%3A00' \
--header 'Authorization: Bearer ibvfeew3inotn2u1gu573qd3ndbunu8k'
```

![image](https://user-images.githubusercontent.com/1873745/126337701-f221226c-2d66-4260-991a-d8b87834379b.png)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-20 14:08 UTC, ihor-sviziev commented
@magento run all tests

2021-07-21 05:55 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE, Unit Tests

2021-07-21 08:40 UTC, ihor-sviziev commented
@magento run Functional Tests B2B

2021-07-22 09:05 UTC, Den4ik requested changes
Hi @ihor-sviziev. I believe that we can little bit improve changes with caching attribute codes

2021-07-22 09:05 UTC, Den4ik commented on app/code/Magento/SalesRule/Model/Plugin/QuoteConfigProductAttributes.php
> +    }
```suggestion
    private function getActiveAttributeCodes(): array
    {
        if ($this->activeAttributeCodes === null) {
            $this->activeAttributeCodes = array_column($this->ruleResource->getActiveAttributes(), 'attribute_code');
        }

        return $this->activeAttributeCodes;
    }
```

2021-07-22 09:05 UTC, Den4ik commented on app/code/Magento/SalesRule/Model/Plugin/QuoteConfigProductAttributes.php
> +    private $activeAttributes;
```suggestion
    private $activeAttributeCodes;
```

2021-07-22 09:05 UTC, Den4ik commented on app/code/Magento/SalesRule/Model/Plugin/QuoteConfigProductAttributes.php
>          return $attributeKeys;
```suggestion
        return array_merge($attributeKeys, $this->getActiveAttributeCodes());
```

2021-07-22 09:23 UTC, ihor-sviziev commented on app/code/Magento/SalesRule/Model/Plugin/QuoteConfigProductAttributes.php
> +        $attributes = $this->getActiveAttributes();
```suggestion
        $attributes = $this->getActiveAttributeCodes();
```

2021-07-22 09:25 UTC, ihor-sviziev commented
@magento run all tests

2021-07-22 09:29 UTC, ihor-sviziev commented
@magento run all tests

2021-07-22 11:33 UTC, ihor-sviziev commented
@magento run Functional Tests EE, Unit Tests

2021-07-22 14:09 UTC, Den4ik approved these changes
✅ Approved.
@ihor-sviziev Thanks for the work

2021-07-22 14:10 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9159](https://jira.corp.magento.com/browse/ENGCOM-9159) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-08-25 04:40 UTC, engcom-Alfa commented
@magento create issue

2021-08-25 04:43 UTC, engcom-Alfa commented
@magento create issue

2021-08-25 05:07 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento 2 instance with sample data.
2. It would be good, if we have got a few days old instance in which we have already performed some activity.



**Manual testing scenario:**

1. Get the admin token using POST request /rest/default/V1/integration/admin/token to collect authorization token

2. Request a GET call, utilizing a above Authorization code using URI http://local.magento2.com/index.php/rest/default/V1/carts/search?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][condition_type]=gt&searchCriteria[sortOrders][0][field]=updated_at&searchCriteria[sortOrders][0][direction]=DESC&searchCriteria[currentPage]=1&searchCriteria[pageSize]=50&searchCriteria[filter_groups][0][filters][0][value]=2021-06-25
 
3. Validate the GET response time



**Before:** :heavy_multiplication_x: The response time was more comparatively.

![image](https://user-images.githubusercontent.com/51679138/130729670-c25445d2-c4f3-4609-8362-590b011711fc.png)


**After:** :heavy_check_mark:  The response time has been reduced 25%

![image](https://user-images.githubusercontent.com/51679138/130729752-e504e0a7-07fe-402c-8cf1-e478f59063a2.png)


Even there is no huge difference in the response load time before and after fix, the given fix at last reduces the response time certain extent and has no impact on the response data.
There is no additional regression required in this case since it is related to the WebAPI request load time.

2021-10-08 18:55 UTC, sidolov commented
@magento run all tests

2021-10-10 17:53 UTC, Den4ik commented
@magento run all tests

2021-10-11 07:03 UTC, ihor-sviziev commented
@magento run all tests

2021-10-17 07:00 UTC, Den4ik commented
Hi @sidolov When it could be merged?

2021-10-21 15:06 UTC, merged