#33387: fix GraphQl products query layered navigation category child
magento/magento2 pull request #33547
Opened 2021-07-21 06:30 UTC by korovitskyi

### Description (*)
It was investigated the category grid page -> category filters. There we check the category filter by current category ID and children. 
In the same way, was added a point to `\Magento\CatalogGraphQl\Model\Resolver\Products\Query\Search` to modify the aggregation category by searchable category ID. As for me, it is the best point, as we must know if request queries have been filtered by category_id and know ID value(s).
Reopen by https://github.com/magento/magento2/pull/33520.
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33387

### Manual testing scenarios (*)
Send request and the count of categories should be 4:
```
query { 
  products(filter: {category_id: {eq: "21"}}) {
    aggregations {
      attribute_code
      count
      label
      options { 
        count
        label
        value 
      } 
    }
  } 
}
```

```
query { 
  products(filter: {category_id: {in: ["21"]}}) {
    aggregations {
      attribute_code
      count
      label
      options { 
        count
        label
        value 
      } 
    }
  } 
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-21 08:07 UTC, andrewbess requested changes
Hello @korovitskyi 
Thank you for your contribution.
Could you please add some fixes?
Thank you in advance

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ResolveCategoryAggregation.php
> +     * @return Aggregation
Hello @korovitskyi 
Could you please merge tags to the common block?
Remove redundant line.

```suggestion
     * @param array $categoryFilter
     * @param Bucket[] $bucketList
     * @return Aggregation
```

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ResolveCategoryAggregation.php
> +
Please remove redundant line

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ResolveCategoryAggregation.php
> +
Please remove redundant lines

```suggestion
        $resolvedCategoryBucket = $this->bucketFactory->create(
            [
                'name' => self::CATEGORY_BUCKET,
                'values' => $resolvedValues
            ]
        );
```

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ResolveCategoryAggregation.php
> +     * @throws NoSuchEntityException
Hello @korovitskyi 
Could you please merge tags to the common block?
Remove redundant lines.

```suggestion
     * @param int $searchableCategoryId
     * @param AggregationValueInterface[] $aggregationValues
     * @return AggregationValueInterface[]
     * @throws NoSuchEntityException
```

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ResolveCategoryAggregation.php
> +        $stareId = (int) $this->storeManager->getStore()->getId();
Hello @korovitskyi 
Perhaps this is typo ($stareId should be named $storeId)

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ResolveCategoryAggregation.php
> +            }
Hello @korovitskyi 
Could you please fix it according to PSR-12 requirements and examples https://www.php-fig.org/psr/psr-12/ (see p.5.1)

```suggestion
            if (
                !in_array($childCategoryId, $validChildIdList)
                ||. in_array($childCategoryId, $this->resolvedChildrenIds)
            ) {
                continue;
            }
```

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/ResolveCategoryAggregation.php
> +     * Check is valid searchable category children.
Hello @korovitskyi
This method not only checks, but returns list of categories, right?
This summary can confuse.
Could you please fix it?

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/Search.php
> +        $this->resolveCategoryAggregation = $resolveCategoryAggregation;
Hello @korovitskyi 
These changes are backward incompatible.
Could you please fix it.

2021-07-21 08:07 UTC, andrewbess commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/Search.php
>       */
```suggestion
     * @param array $args
     * @param ResolveInfo $info
     * @param ContextInterface $context
     * @return SearchResult
     * @throws GraphQlInputException
     */
```

2021-07-25 09:50 UTC, korovitskyi commented
Hi, @andrewbess .
Changes were added.
Thank you for the review.

2021-09-07 13:00 UTC, engcom-Charlie commented
Hi @korovitskyi,

Thanks for your contribution!

As per your [comment](https://github.com/magento/magento2/pull/33547#issuecomment-886175666), you have implemented the review changes so moving it for review.

2021-10-26 23:51 UTC, merged