32866: Updated php-amqplib/php-amqplib to the latest version 3.0.0
magento/magento2 pull request #33551
Opened 2021-07-21 10:27 UTC by anzin

### Description (*)

I've updated php-amqplib/php-amqplib to the latest version 3.0.0

list usages the library in the codebase:

\Magento\AmqpStore\Plugin\AsynchronousOperations\MassConsumerEnvelopeCallback **compatible**
\Magento\AmqpStore\Plugin\Framework\Amqp\Bulk\Exchange **compatible**
\Magento\Framework\Amqp\Config **compatible**
\Magento\Framework\Amqp\Exchange **compatible**
\Magento\Framework\Amqp\Queue **not compatible in 3.0.0 removed  PhpAmqpLib\Exception\AMQPProtocolConnectionException**
\Magento\Framework\Amqp\Bulk\Exchange **compatible**
\Magento\Framework\Amqp\Connection\Factory **compatible**
\Magento\Framework\Amqp\Test\Unit\TopologyInstallerTest **compatible**
\Magento\Framework\Amqp\Test\Unit\Bulk\ExchangeTest **compatible**
\Magento\Framework\Amqp\Test\Unit\Connection\FactoryTest **compatible**
\Magento\Framework\Amqp\Test\Unit\Topology\BindingInstallerTest **compatible**
\Magento\Framework\Amqp\Test\Unit\Topology\ExchangeInstallerTest **compatible**
\Magento\Framework\Amqp\Test\Unit\Topology\QueueInstallerTest **compatible**
\Magento\Framework\Amqp\Test\Unit\Topology\BindingInstallerType\ExchangeTest **compatible**
\Magento\Framework\Amqp\Test\Unit\Topology\BindingInstallerType\QueueTest **compatible**
\Magento\Framework\Amqp\Topology\BindingInstaller **compatible**
\Magento\Framework\Amqp\Topology\BindingInstallerInterface **compatible**
\Magento\Framework\Amqp\Topology\ExchangeInstaller **compatible**
\Magento\Framework\Amqp\Topology\QueueInstaller **compatible**
\Magento\Framework\Amqp\Topology\BindingInstallerType\Exchange **compatible**
\Magento\Framework\Amqp\Topology\BindingInstallerType\Queue **compatible**
\Magento\Framework\MessageQueue\Bulk\Rpc\Publisher **compatible**

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32866

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-21 10:37 UTC, anzin commented
@magento run all tests

2021-07-21 12:20 UTC, anzin commented
@magento run Unit Tests, Functional Tests B2B

2021-07-22 04:13 UTC, eduard13 approved these changes

2021-07-22 08:28 UTC, Den4ik requested changes
Hi @anzin 
Thanks for your contribution. Please look at my comment

2021-07-22 08:28 UTC, Den4ik commented on lib/internal/Magento/Framework/Amqp/Queue.php
> +        } catch (AMQPTimeoutException $exception) {
As I see `basic_get` could throw not only described in phpdoc `AMQPTimeoutException` exception. I believe that we should use `Exception` here

2021-07-22 09:34 UTC, anzin commented
@magento run all tests

2021-07-23 05:02 UTC, eduard13 requested changes
@anzin, could you please create a similar PR in EE repo?
Thank you.

2021-07-23 08:40 UTC, anzin commented
Hello @eduard13 I created a similarly PR in EE repo: https://github.com/magento/partners-magento2ee/pull/567

Thank you.

2021-07-23 08:58 UTC, anzin commented
@magento run all tests

2021-07-23 09:07 UTC, eduard13 commented
@magento run all tests

2021-07-23 11:27 UTC, anzin commented
@magento run Unit Tests , Functional Tests B2B, Functional Tests EE

2021-07-23 11:33 UTC, Den4ik commented
Changes looks good for me. Failed tests should not be related to changes. But waiting current rerun

2021-07-23 14:05 UTC, andrewbess commented
@magento run all tests

2021-07-23 15:31 UTC, eduard13 approved these changes

2021-07-23 15:55 UTC, andrewbess commented
@magento run Functional Tests EE, Functional Tests B2B

2021-07-23 17:41 UTC, andrewbess commented
@magento run Functional Tests EE

2021-07-23 20:15 UTC, andrewbess commented
@magento run Functional Tests EE, Functional Tests B2B

2021-07-23 21:48 UTC, Den4ik approved these changes
Failed tests looks as not related to changes

2021-07-24 04:32 UTC, andrewbess commented
@magento run Functional Tests B2B

2021-07-24 06:41 UTC, andrewbess commented
@magento run Functional Tests B2B

2021-07-24 09:47 UTC, andrewbess commented
@magento run Functional Tests B2B

2021-07-24 12:31 UTC, andrewbess commented
@magento run Functional Tests B2B

2021-07-24 14:21 UTC, andrewbess commented
Unambiguously, failed tests is not related to changes.
But it will be merged only after passing all tests.

2021-07-24 14:21 UTC, andrewbess commented
@magento run Functional Tests B2B

2021-07-24 14:23 UTC, andrewbess approved these changes
Hello @anzin 
Thank you for your contribution.
Great job

2021-07-25 00:16 UTC, andrewbess commented
Currently, service currconv.com is not available.
<img width="1389" alt="service-currconv-com-not-available" src="https://user-images.githubusercontent.com/10788564/126883804-73ae52ee-a99d-4617-9d76-794c044a2382.png">
There is only one error in functional tests.
So, this PR and related can be merged.

2021-07-25 06:50 UTC, merged