CE-33707: Fixed deprecated methods for PHPUnit v9.3.0
magento/magento2 pull request #33710
Opened 2021-08-06 19:20 UTC by karyna-tsymbal-atwix

### Description (*)
This PR fixes CE project codebase compatibility problems with the PHPUnit v.9.3.0.
See changes here: [PHPUnit 9.3.0 ChangeLog](https://github.com/sebastianbergmann/phpunit/blob/9.3.0/ChangeLog-9.3.md#configuration-of-code-coverage-and-logging-in-phpunitxml)

In this PR was changed 90 files where the main problem was using at() matcher that has been deprecated.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/576
https://github.com/magento/partners-magento2b2b/pull/579

### Related Issues
1. magento/magento2#33707

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-08-07 05:09 UTC, ihor-sviziev commented
@magento run all tests

2021-08-07 17:03 UTC, ihor-sviziev commented
@magento run Functional Tests EE, Functional Tests B2B, Functional Tests CE, Integration Tests, WebAPI Tests, Static Tests

2021-08-08 04:55 UTC, ihor-sviziev commented on app/code/Magento/Quote/Test/Unit/Model/QuoteManagementTest.php
> -        $this->expectException('Magento\Framework\Exception\StateException');
AFAIK It was intentionally done in order not use ::class due to performance reasons - on big data sets it's noticeable when php unit tries additionally lookup for exception class.
@lbajsarowicz, am I correct?

2021-08-09 05:24 UTC, ihor-sviziev requested changes
In general, your changes look good to me. Could you check failing tests?

2021-08-11 11:20 UTC, andrewbess approved these changes
This is an intermediate approval.
All requested changes will be fixed in parent PR.

2021-08-11 11:22 UTC, merged