Improvement/ce 33336 eliminate laminas soap from core code
magento/magento2 pull request #33789
Opened 2021-08-13 08:00 UTC by anzin

### Description (*)
This PR (pull request) provides the eliminating `laminas/laminas-soap` composer dependency from the system.

**Need to close** : https://github.com/magento/magento2/pull/33660

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/574

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33336

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-08-13 08:02 UTC, anzin commented
@magento run all tests

2021-08-13 08:40 UTC, anzin commented
@magento run all tests

2021-08-13 10:41 UTC, ihor-sviziev requested changes

2021-08-13 10:41 UTC, ihor-sviziev commented on app/code/Magento/Webapi/Api/Data/ClientInterface.php
> + * @see       https://github.com/laminas/laminas-server for the canonical source repository
Copying lamias components to Magento isn't a really good idea.
More tails here https://github.com/magento/magento2/pull/33373#discussion_r676573460
I still didn't get any answer.

2021-08-16 08:25 UTC, anzin commented
@magento run all tests

2021-08-16 09:20 UTC, anzin commented
@magento run all tests

2021-08-16 11:47 UTC, anzin commented
@magento run Functional Tests B2B

2021-08-16 14:10 UTC, anzin commented
@magento run Unit Tests

2021-08-16 15:01 UTC, anzin commented
@magento run Functional Tests B2B

2021-08-17 07:08 UTC, anzin commented
@magento run Functional Tests B2B

2021-08-17 08:42 UTC, anzin commented
@magento run Unit Tests, Static Tests

2021-08-17 09:42 UTC, anzin commented
@magento run Unit Tests, Static Tests

2021-08-17 11:19 UTC, Den4ik commented
@anzin Could you check EE and B2B unit tests

2021-08-17 11:42 UTC, anzin commented
@magento run all tests

2021-08-17 13:34 UTC, anzin commented
@magento run  Functional Tests B2B

2021-08-17 15:30 UTC, anzin commented
@magento run Functional Tests B2B

2021-08-17 19:24 UTC, anzin commented
@magento run Functional Tests B2B

2021-08-19 09:08 UTC, anzin commented
@magento run all tests

2021-08-19 10:41 UTC, anzin commented
@magento run all tests

2021-08-19 11:28 UTC, Den4ik commented
@anzin I see same failed Unit test that related to changes. Could you lease check it

2021-08-19 14:43 UTC, anzin commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2021-08-19 14:47 UTC, anzin commented
@magento run  Semantic Version Checker

2021-08-19 19:50 UTC, anzin commented
@magento run Unit Tests, Functional Tests B2B, Functional Tests CE

2021-08-19 22:56 UTC, anzin commented
@magento run Functional Tests B2B, Functional Tests CE

2021-08-20 06:57 UTC, anzin commented
@magento run Functional Tests B2B, Functional Tests CE

2021-08-25 07:58 UTC, anzin commented
@magento run all tests

2021-08-25 09:51 UTC, anzin commented
@magento run WebAPI Tests

2021-08-26 00:50 UTC, anzin commented
@magento run Static Tests

2021-10-15 21:16 UTC, andrewbess commented
The laminas/laminas-soap composer dependency currently is compatible with PHP 8.1
https://packagist.org/packages/laminas/laminas-soap#2.10.0
The PR closed due to this reason

2021-10-15 21:16 UTC, closed without merging