ISSUE-33802: ensure that deployment config will reload its data, if t…
magento/magento2 pull request #33803
Opened 2021-08-15 14:58 UTC by sergeynezbritskiy

ensure that deployment config will reload its data, if the key was not found

### Description (*)
Reset DeploymentConfig data if the requested configuration doesn't exist in cached data 

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33802

### Manual testing scenarios (*)
1. Described in magento/magento2#33802

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-08-15 16:03 UTC, sergeynezbritskiy commented
@magento run all tests

2021-08-15 16:38 UTC, sergeynezbritskiy commented
@magento run all tests

2021-08-16 08:01 UTC, sergeynezbritskiy commented
@magento run all tests

2021-08-16 13:28 UTC, sergeynezbritskiy commented
@magento run Functional Tests B2B

2021-08-17 16:56 UTC, sergeynezbritskiy commented
@magento run Functional Tests B2B

2021-08-18 17:10 UTC, sergeynezbritskiy commented
@magento run Functional Tests B2B

2021-08-19 09:33 UTC, sergeynezbritskiy commented
@magento run Functional Tests B2B

2021-08-19 09:34 UTC, sergeynezbritskiy commented
Every run fails due to different failures, what's going on here ?

2021-09-02 08:55 UTC, BorisovskiP commented
Hey @sergeynezbritskiy, we added your changes as a patch and in our case this indeed fixes the issue.

2021-09-02 08:56 UTC, oneserv-heuser commented
@sergeynezbritskiy @BorisovskiP we did the same and can also confirm this

2021-10-01 19:49 UTC, tniebergall commented
@sergeynezbritskiy thank you for this fix, we had the same issue during an upgrade vom 2.4.2-p1 to 2.4.3

2021-10-04 12:59 UTC, ihor-sviziev approved these changes

2021-10-04 13:00 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9239](https://jira.corp.magento.com/browse/ENGCOM-9239) has been created to process this Pull Request

2021-10-07 09:01 UTC, engcom-Alfa commented
@magento give me test instance

2021-10-07 09:59 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed


**Manual testing scenario:**

1. Installed a fresh Magento2.4-develop instance, and make sure that is working fine

2. Delete the database completely and re-create the same database name (That will be empty database as database deleted & re created)
 
3. Remove the file /app/etc/env.php

4. Re-install the with the database creation command i.e. `php bin/magento setup:install --backend-frontname="admin" --session-save="files" --db-host="localhost" --db-name="magento24develop" --db-user="root" --db-password="" --base-url="http://local.magento24develop.com/" --base-url-secure="https://local.magento24develop.com/" --admin-user="admin" --admin-password="admin123" --admin-email="admin@admin.com" --admin-firstname="Admin" --admin-lastname="Admin"`


**Before:** :heavy_multiplication_x: Getting an error Connection default not defined while executing the installation command

![image](https://user-images.githubusercontent.com/51679138/136362092-d04650a7-0481-45bd-acd7-00e560d8d535.png)



**After:** :heavy_check_mark:  Successfully installing using the command

![image](https://user-images.githubusercontent.com/51679138/136361721-6da424ea-d7d7-4b86-9980-899989263adb.png)


Worked on the install with the PR changes updates. Magento features are working fine. Since the issue is relevant to the installation setup and has no impact on any other features of it, so no additional regression is required.

2021-10-25 18:24 UTC, sidolov approved these changes

2022-04-07 07:08 UTC, Sanjay-100 commented
> heavy_check_mark QA Passed
> 
> **Manual testing scenario:**
> 
> 1. Installed a fresh Magento2.4-develop instance, and make sure that is working fine
> 2. Delete the database completely and re-create the same database name (That will be empty database as database deleted & re created)
> 3. Remove the file /app/etc/env.php
> 4. Re-install the with the database creation command i.e. `php bin/magento setup:install --backend-frontname="admin" --session-save="files" --db-host="localhost" --db-name="magento24develop" --db-user="root" --db-password="" --base-url="http://local.magento24develop.com/" --base-url-secure="https://local.magento24develop.com/" --admin-user="admin" --admin-password="admin123" --admin-email="admin@admin.com" --admin-firstname="Admin" --admin-lastname="Admin"`
> 
> **Before:** heavy_multiplication_x Getting an error Connection default not defined while executing the installation command
> 
> ![image](https://user-images.githubusercontent.com/51679138/136362092-d04650a7-0481-45bd-acd7-00e560d8d535.png)
> 
> **After:** heavy_check_mark Successfully installing using the command
> 
> ![image](https://user-images.githubusercontent.com/51679138/136361721-6da424ea-d7d7-4b86-9980-899989263adb.png)
> 
> Worked on the install with the PR changes updates. Magento features are working fine. Since the issue is relevant to the installation setup and has no impact on any other features of it, so no additional regression is required.

I have already one magento setup now I just change the new database 
steps I did
- fresh copy Magento 2.3
- blank dtabase
- deleted env.php
- then run setup the command 


set Disabling Maintenance Mode:

In ResourceConnection.php line 148:
                                       
  Connection "default" is not defined

2022-06-06 09:19 UTC, ihor-sviziev commented
Hi @sergeynezbritskiy,
Could you please resolve the conflict?

2022-06-29 13:14 UTC, cmuench commented
I created a patch file for Magento 2.4.4 with the changes of this PR.
No warranty.
The patch fixed the issue in my CI pipelines.

https://gist.github.com/cmuench/de27258f0b4ccb8df3dee2e8507e935d

2022-09-14 11:57 UTC, norgeindian commented
Has anybody by chance already a patch file for 2.4.5?

2022-09-16 12:22 UTC, ihor-sviziev commented
@magento run all tests

2022-09-16 14:24 UTC, ihor-sviziev commented
@magento run Static Tests, Unit Tests

2022-09-17 10:48 UTC, ihor-sviziev requested changes

2022-09-17 10:48 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/App/DeploymentConfig.php
> +    /**
```suggestion
    /**
     * Returns flat data by key
     *
```

2022-09-17 10:48 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/App/DeploymentConfig.php
> +    /**
```suggestion
    /**
     * Returns data by key
     *
```

2022-09-17 10:49 UTC, ihor-sviziev commented
@magento run all tests

2022-09-18 05:27 UTC, ihor-sviziev approved these changes

2022-09-19 11:44 UTC, engcom-Alfa commented
@magento run all tests

2022-09-19 13:24 UTC, engcom-Lima commented
@magento run Functional Tests CE , Functional Tests EE

2022-09-19 15:11 UTC, engcom-Lima commented
@magento run Functional Tests CE , Functional Tests B2B , Integration Tests

2022-09-20 06:25 UTC, engcom-Lima commented
✔️ QA Passed

**Manual testing scenario:**

1. Installed a fresh Magento2.4-develop instance, and make sure that is working fine
2. Delete the database completely and re-create the same database name (That will be empty database as database deleted & re created)
3. Remove the file app/etc/env.php
4. Re-install the with the database creation command i.e. `php bin/magento setup:install --backend-frontname="admin" --session-save="files" --db-host="localhost" --db-name="****" --db-user="root" --db-password="" --base-url="****" --base-url-secure="https://local.magento24develop.com/" --admin-user="admin" --admin-password="admin123" --admin-email="admin@admin.com" --admin-firstname="Admin" --admin-lastname="Admin"`

Before: ✖️ Getting an error Connection default not defined while executing the installation command
<img width="1506" alt="Screenshot 2022-09-19 at 5 35 23 PM" src="https://user-images.githubusercontent.com/60198022/191182437-7eb41b69-b4ad-46ce-870e-6d00a0ec69a3.png">

After: ✔️ Successfully installing using the command
<img width="1475" alt="Screenshot 2022-09-19 at 5 39 07 PM" src="https://user-images.githubusercontent.com/60198022/191182553-77532e4e-40cb-4190-a60f-6ee7f1dee093.png">

No additional manual testing is required.

2022-10-19 16:40 UTC, ishakhsuvarov commented
@magento run all tests

2022-10-20 19:06 UTC, ishakhsuvarov commented
Moving to `Extended testing` to evaluate failing buiulds

2022-10-28 07:21 UTC, engcom-Lima commented
@magento run Functional Tests EE, Integration Tests, WebAPI Tests

2022-10-28 09:24 UTC, engcom-Lima commented
@magento run Functional Tests EE, Integration Tests

2022-10-28 11:36 UTC, engcom-Lima commented
@magento run Integration Tests

2022-10-31 06:19 UTC, engcom-Echo commented
@magento run all tests

2022-10-31 08:14 UTC, engcom-Echo commented
@magento run Integration Tests, Functional Tests CE, Functional Tests EE

2022-10-31 10:02 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2022-11-24 17:05 UTC, merged