Fixed bugs and add improvements for Newsletter Queue
magento/magento2 pull request #33849
Opened 2021-08-18 12:40 UTC by Usik2203

### Description 
This PR fixes bugs and add improvements  for  Newsletter Queue functionality

### Preconditions
1. For correct testing you should have more then 20 subscribers in `newsletter_subscriber` table
2. Create new **Newsletter Templates** in **Marketing->Newsletter Templates** 
3. Create new **Newsletter Queue** 

https://user-images.githubusercontent.com/13517181/129901984-3874092d-06de-4142-9a2d-f350befdb1fc.mov

## Issue case 1
#### Actual result
1. Run `bin/magento cron:run --group=default` ,` newsletter_send_all` cron job should run **Newsletter Queue**
2. You will see that **20 emails were sent** but we still have **Not Sent** status 

<img width="1000" alt="Screenshot 2021-08-18 at 16 37 28" src="https://user-images.githubusercontent.com/13517181/129908126-2b8d7983-f593-4d3f-bbdb-a7ff432420c0.png">

3. I don't see any actions except **Preview**

<img width="1308" alt="Screenshot 2021-08-18 at 16 44 20" src="https://user-images.githubusercontent.com/13517181/129909241-93fa3e6b-ba5b-4e1d-8638-710ecd47a009.png">

#### Result after fix 
Was fixed by appliing next changes https://github.com/magento/magento2/pull/33849/files#diff-1d2d0f2340ff4fc3e0907e98b2ccd1a21a35c777c503907bc3c12f0223eaeb8eR254

Correct status was set, i can see **Pause**, **Cancel** , **Preview**  actions for queue

<img width="1000" alt="Screenshot 2021-08-18 at 16 48 58" src="https://user-images.githubusercontent.com/13517181/129910001-217db172-51a7-4ffe-b95e-1d97dfbab48d.png">

## Issue case 2
1. After **Issue case 1** was fixed next issue was reproduced  
#### Actual result

All data were removed from Newsletter Queue after clicking **Save and Resume** button

https://user-images.githubusercontent.com/13517181/129911385-51cd3ae5-a676-4649-90f7-0176550e2f92.mov

<img width="200" alt="Screenshot 2021-08-18 at 16 59 08" src="https://user-images.githubusercontent.com/13517181/129911701-33a68d3b-22d9-4215-8fd9-866bcaadde2d.png">

#### Result after fix 
Was fixed by appliing next changes  https://github.com/magento/magento2/pull/33849/files#diff-f4e00fe342edaab019fbb62abfa0c2b8f5d7a2f179bd5880e4c217d57bbb7883R232 

Data was saved correctly  all data present 

https://user-images.githubusercontent.com/13517181/129914043-f9a78778-f169-481c-b907-1b6a7dad6057.mov

## Issue case 3
#### Actual result
1. **Save and Resume** button always display  even while creating new  **Newsletter Queue**  

<img width="1348" alt="Screenshot 2021-08-18 at 17 04 30" src="https://user-images.githubusercontent.com/13517181/129912812-9b35f002-548a-4811-b7e0-13098b50bac7.png">

#### Result after fix 
Was fixed by appliing next changes  https://github.com/magento/magento2/pull/33849/files#diff-d337328a9078b6f37102b714ffa5460b365c7ede7b97ca644bf2f0b8fe15b0dcR138

1. **Save and Resume** button displays  only if  **Newsletter Queue**  has status **Pause** 

https://user-images.githubusercontent.com/13517181/129914610-f2be7644-a867-40f8-af93-0424de400b15.mov

### Resolved issues:
1. [x] resolves magento/magento2#36612: Fixed bugs and add improvements for Newsletter Queue

2021-08-18 12:43 UTC, Usik2203 commented
@magento run all tests

2021-08-19 12:25 UTC, Den4ik requested changes

2021-08-19 12:25 UTC, Den4ik commented on app/code/Magento/Newsletter/Model/Queue.php
> +        $this->save();
Why do we still use deprecated method in core?

2022-08-03 13:41 UTC, engcom-Charlie commented
@magento give me test instance

2022-08-04 11:08 UTC, engcom-Charlie commented
@magento give me test instance

2022-08-05 10:01 UTC, engcom-Charlie commented
@magento run all tests

2022-08-05 12:08 UTC, Den4ik commented
@engcom-Charlie Will you help with updating PR?

2022-08-05 13:48 UTC, engcom-Charlie commented
Hi @Den4ik,

Yeah, will work on the review comments and on build failures.

Thank you!

2022-08-05 19:48 UTC, Den4ik commented
@engcom-Charlie That's great 👍

2022-08-08 13:06 UTC, engcom-Charlie commented
@magento run all tests

2022-08-09 06:29 UTC, engcom-Charlie commented
@magento run Unit Tests ,Integration Tests

2022-08-09 09:11 UTC, engcom-Charlie commented
@magento run Functional Tests CE test

2022-08-09 09:12 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2022-08-09 10:22 UTC, engcom-Charlie commented
Hi @Den4ik,

Thank you for your contribution!

With respect to your review comment, currently magento have no service contract/repository implementation for this module. Hence for this PR we have to consider the provided approach only but we will surly convey your thought to the core team and the PO. But for this PR we have to go with the given approach.

Apart from that if you please go ahead and complete the review process so that we can proceed it further to Ready For Testing.

Meanwhile I am looking into the build failures.

Thank you!

2022-08-09 12:22 UTC, engcom-Charlie commented
@magento give me test instance

2022-08-09 12:33 UTC, engcom-Charlie commented
@magento run all tests

2022-08-09 13:31 UTC, Den4ik commented
@magento give me 2.4-develop instance

2022-08-10 07:23 UTC, engcom-Charlie commented
Fixed all test failures apart from functional test failure. 

AdminEditCustomerWithAssociatedNewsletterQueueTestCest.xml is the functional test which is currently failing.
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/51680850/183839844-a4d8f8a1-e81f-4c52-a8d5-b05f1215ed54.png">

After analysis found that, the mentioned test is not failing because of changes made in PR or not part of the PR changes. It's related to the WYSIWYG editor.

@Den4ik, requesting you to review the PR so that we can move further for testing. Moving it to Review In Progress.

Thank you!

2022-09-06 13:59 UTC, Den4ik approved these changes
✅ Approved

2022-09-06 14:00 UTC, Den4ik commented
@engcom-Charlie You may proceed with this PR.
@Usik2203 Thanks for your work

2022-09-07 09:56 UTC, engcom-Lima commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2022-09-07 12:28 UTC, engcom-Lima commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2022-09-08 06:08 UTC, engcom-Lima commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2022-09-08 09:46 UTC, engcom-Lima commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2022-09-08 14:20 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions**

1. For correct testing you should have more then 20 subscribers in newsletter_subscriber table
2. Create new Newsletter Templates in Marketing->Newsletter Templates
3. Create new Newsletter Queue

**Manual testing scenario:**
1. Run bin/magento cron:run --group=default , newsletter_send_all cron job should run Newsletter Queue
2. You will see that 20 emails were sent but we still have Not Sent status
3. Check other option available other than preview -ex pause (issue 1)
4. Pause and click queue ->Save and resume and check data available or not.
5. Save and Resume button always display even while creating new Newsletter Queue

**Before:** :heavy_multiplication_x: Mentioned issues were reproduced.
<img width="1383" alt="Screenshot 2022-09-07 at 5 30 02 PM" src="https://user-images.githubusercontent.com/60198022/189145134-9ecc8cd9-1323-4cf6-853c-12bd1c3459ad.png">

**After:** :heavy_check_mark:  Resolved all the issues.
<img width="1512" alt="Screenshot 2022-09-07 at 5 46 03 PM" src="https://user-images.githubusercontent.com/60198022/189145388-6fa25c8f-f751-478f-9982-6d9f8ca7a344.png">
<img width="1512" alt="Screenshot 2022-09-07 at 5 45 16 PM" src="https://user-images.githubusercontent.com/60198022/189145632-81988640-8e9e-4798-bdd3-18b612d9ab85.png">

<img width="1512" alt="Screenshot 2022-09-07 at 5 45 16 PM" src="https://user-images.githubusercontent.com/60198022/189146591-af73803f-9b12-402e-9863-c256c35776ec.png">

Checks are failed. Hence, moving this PR to **Extended testing**

Thanks

2022-10-14 11:17 UTC, engcom-Charlie commented
@magento run all tests

2022-10-17 07:03 UTC, engcom-Charlie commented
@magento run all tests

2022-10-17 11:16 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Integration Tests

2022-10-18 09:08 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2022-11-09 09:37 UTC, engcom-Echo commented
@magento run all tests

2022-11-09 12:50 UTC, engcom-Echo commented
@magento run all tests

2022-11-10 04:15 UTC, engcom-Echo commented
@magento run all tests

2022-11-10 07:56 UTC, engcom-Echo commented
@magento run Integration Tests, Functional Tests EE

2022-11-11 08:25 UTC, engcom-Echo commented
For SVC approval we have raised internal [JIRA](https://jira.corp.adobe.com/browse/AC-7008). Hence we are moving it to pending approval.

2022-12-15 07:20 UTC, engcom-Lima commented
@magento create issue

2023-01-13 05:11 UTC, engcom-Echo commented
@magento run all tests

2023-01-13 13:11 UTC, engcom-Echo commented
@magento run Functional Tests CE

2023-01-16 05:21 UTC, engcom-Echo commented
Functional Tests B2B, Functional Tests EE,Functional Tests CE Failures are related to Currency Converter API.
Hence Moving to `Merge In Progress`

2023-03-02 14:33 UTC, merged