Fix unable to remove parameter override for a webapi route
magento/magento2 pull request #33844
Opened 2021-08-18 09:21 UTC by gowrizrh

### Description (*)
This PR contains the changes to fix #33843 - the `force` attribute in a `webapi.xml` is ignored in certain cases.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33843

### Manual testing scenarios (*)
1. Redefine a route parameter override in a new `webapi.xml`
2. Verify the webapi config with something like the `n98 dev:console` 

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-08-18 10:33 UTC, gowrizrh commented
@magento run all tests

2021-08-18 13:02 UTC, gowrizrh commented
@magento run Unit Tests

2021-08-18 14:01 UTC, gowrizrh commented
@magento run all tests

2021-08-19 14:10 UTC, Den4ik requested changes
@gowrizrh Thanks for contribution.
Please look at suggested changes

2021-08-19 14:10 UTC, Den4ik commented on app/code/Magento/Webapi/Model/Config/Converter.php
> +            $force = filter_var($forceNode ? $forceNode->nodeValue : false, FILTER_VALIDATE_BOOLEAN);
```suggestion
            $force = $forceNode ? filter_var($forceNode->nodeValue, FILTER_VALIDATE_BOOLEAN) : false;
```

2021-08-19 14:14 UTC, Den4ik commented
@magento run all tests

2021-08-19 19:14 UTC, Den4ik approved these changes
✅ Approved.

Looks good for me

2021-08-19 19:15 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9186](https://jira.corp.magento.com/browse/ENGCOM-9186) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-09-09 08:45 UTC, engcom-Hotel commented
@magento run all tests

2021-09-09 12:17 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Static Tests

2021-09-10 07:45 UTC, engcom-Hotel requested changes
Hello @gowrizrh,

Thanks for the contribution!

Some of the tests are failing, please look into this. And Also I am unable to reproduce the issue. Can you please help us with the exact commands or steps in order to reproduce the issue?

Thanks

2021-09-16 12:00 UTC, Den4ik commented
@engcom-Hotel In fact failed static test is not related to this PR because it's failed on different function. I believe that we should not mix fixes of issues with not related fixes.
But as fast solution @gowrizrh could you please add phpcs ignore?

2021-09-16 12:12 UTC, gowrizrh commented
Sure, I'll post ways to reproduce and also add phpcs ignore and update it shortly.

2021-09-27 06:49 UTC, engcom-Charlie commented
Hi @gowrizrh,

Thank you for your contribution!

Can you provide any information on this [comment](https://github.com/magento/magento2/pull/33844#issuecomment-920847490)

Thank you!

2021-09-28 05:57 UTC, gowrizrh commented
We can reproduce this using [n98-magerun2](https://github.com/netz98/n98-magerun2) which is a cli tool for Magento.

1. Install vanilla Magento 2.4.3
2. Create an example module and define a `webapi.xml`
3. Attempt to override the `/V1/customers` core webapi route using the following code

```
<!-- Vendor/Module/etc/webapi.xml -->

    <route url="/V1/customers" method="POST">
        <data>
            <parameter name="customer.extension_attributes.company_attributes.company_id" force="false">%company_id%</parameter>
        </data>
    </route>
```

**Note that our intention is to make the force attribute false. `force="false"`**

Run `bin/magento setup:upgrade`

Now using `n98-magerun2` fire up the dev console using `bin/n98-magerun2 dev:console`

Once it's available, we can inspect what's stored in the merged xml file. You should be able to run the following piece of code in the shell / REPL

```
$config = $di->create(\Magento\Webapi\Model\ConfigInterface::class);

$customer_route_config = $config->getServices()['routes']['/V1/customers']
```

The `$customer_route_config` should contain an array of configs that is created for the route `/V1/customers`, the route config should contain `parameters` which is another array of just configurations. Basically, the `force` field will never be `false` even though we define it as `false` in our example earlier.


```
 [
     "POST" => [
       "secure" => false,
       "service" => [
         "class" => "Magento\Customer\Api\AccountManagementInterface",
         "method" => "createAccount",
       ],
       "resources" => [
         "anonymous" => true,
       ],
       "parameters" => [
         "customer.extension_attributes.company_attributes.company_id" => [
           "force" => true, <------ THIS SHOULD BE FALSE
           "value" => "%company_id%",
         ],
       ],
     ],
   ]
```

2021-09-28 07:22 UTC, gowrizrh commented
@magento run all tests

2021-09-28 14:51 UTC, gowrizrh commented
@Den4ik @engcom-Charlie i'm not sure why these tests would report failure in github, i can see that no tests have failed in any of the test suites.

![image](https://user-images.githubusercontent.com/40108018/135111458-c21a8e8f-729f-41d3-afc1-57295f827157.png)

2021-09-29 10:33 UTC, engcom-Charlie commented
Hi @gowrizrh,

I have checked the Allure report from the Details link and few tests are failing from Functional Tests EE and Static Test.

Functional EE
![image](https://user-images.githubusercontent.com/51680850/135252035-28a389c5-f640-4eed-8207-91f6371fe3e6.png)

Static Test
![image](https://user-images.githubusercontent.com/51680850/135252041-22bbbc87-81fe-4c63-97ea-fd5049ab5b75.png)

Can you please recheck it.

Thank you!

2021-09-29 10:44 UTC, gowrizrh commented
it looks like the phpcs change wasn't pushed to GH in my last comment. however i have no idea what the Functional EE test failure is.

i'll be just rerunning all tests.

2021-09-29 10:44 UTC, gowrizrh commented
@magento run all tests

2021-10-01 01:18 UTC, gowrizrh commented
@engcom-Charlie 

this time it says it has failed `Functional Tests EE` however i cannot see any errors in the build report. these automated builds are not very stable at all.

![image](https://user-images.githubusercontent.com/40108018/135550968-d314e8d3-e1e6-4579-9a8c-ea4e7bda6baa.png)

2021-10-01 05:55 UTC, engcom-Charlie commented
Hi @gowrizrh,

Yeah, Perhaps there is some issue for now. 

Functional Tests EE are showing failed but when I am checking the detail report, there is no single test failure. All the Functional EE tests are successfully passed so moving this issue further.

![image](https://user-images.githubusercontent.com/51680850/135572386-3b3961e5-33ec-44a3-bb26-1bdda4027e6e.png)


Thank you!

2021-10-08 08:06 UTC, engcom-Alfa commented
@magento run Functional Tests EE

2021-10-08 09:38 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Should have Magento 2.4-develop installed.
2. Install n98-magerun2


**Manual testing scenario:**

1. Create a new simple custom module in the Magento.

2. Create a new simple webapi.xml along with its relevant simple interfaces and classes under same created custom module.
 
3. Make sure your module and API working fine.

4. Update the webapi.xml with the <route method="POST" ; if it is already not a POST method; Since it is new one, it will having you own URI, and that should be fine. Update the data in the same file as like below
`<data>
            <parameter name="customer.extension_attributes.company_attributes.company_id" force="false">%company_id%</parameter>
</data>`
Note: Here, the _force_ is set to _false_ (It should be set to false only!)

5. Using _n98-magerun2_ fire up the dev console using command _php bin/n98-magerun2.phar_ dev:console or _bin/n98-magerun2 dev:console_ (It opens the SHELL script console to run further commands)

6. Run the command 1: $config = _$di->create(\Magento\Webapi\Model\ConfigInterface::class);_

7. Run the command 2: _$customer_route_config = $config->getServices()['routes']['`<API URI>`']_
    API URI ex is: /V1/customers ; It will be as same as defined in the webapi.xml file

8. Check the response of the second command.


**Before:** :heavy_multiplication_x: Was unable to remove the paramater override for webapi route and was getting response always "force" => false

![image](https://user-images.githubusercontent.com/51679138/136533392-64e6cc49-c67b-47c5-8d02-18f8cdf171cf.png)


**After:** :heavy_check_mark:  Able to remove the paramater override for webapi route and getting response according to the set force either to false/true

![image](https://user-images.githubusercontent.com/51679138/136533232-eadc9343-21c4-4218-b7f6-24a789f32783.png)


Tested by setting the _force_ to _false_ and also for _true_; We are getting the response accordingly. There is no other additional testing is required since it is related to API response specific to a case and functionally all works fine. Hence no additional regression is required too!

2021-10-08 09:47 UTC, engcom-Alfa commented
As per the [last comment](https://github.com/magento/magento2/pull/33844#issuecomment-938498923) - QA Passed; Also the Functional tests are getting passed as per the [above - comment](https://github.com/magento/magento2/pull/33844#issuecomment-931930993).
Hence moving it to _merge in progress_.

2021-10-21 15:06 UTC, merged