Update jQuery.validate library
magento/magento2 pull request #33871
Opened 2021-08-20 11:50 UTC by eduard13

### Description (*)
This PR aims to update the jQuery.validate library to the latest `1.19.3` version and keep supporting the current version of jQuery.metadata library.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33853

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-08-20 12:01 UTC, eduard13 commented
@magento run all tests

2021-08-20 19:02 UTC, ihor-sviziev commented on lib/web/jquery/jquery.validate.js
> -            creditcard: "Please enter a valid credit card number.",
I think removing credit card that’s something not expected

2021-08-23 10:51 UTC, eduard13 commented
@magento run all tests

2021-08-24 11:28 UTC, eduard13 commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests

2021-08-25 06:26 UTC, ihor-sviziev requested changes
Please fix static test failure

2021-08-25 06:38 UTC, eduard13 commented
@magento run Static Tests

2021-08-25 08:28 UTC, eduard13 commented
@magento run Static Tests

2021-08-25 09:17 UTC, ihor-sviziev commented
Static tests are passing
@magento run all test

2021-08-25 09:19 UTC, ihor-sviziev commented
@magento run all tests

2021-08-25 09:32 UTC, eduard13 commented
@magento run all tests

2021-08-25 12:38 UTC, andrewbess approved these changes
Hello @eduard13 
Thank you for your contribution.
Changes approved.
Waiting for builds

2021-08-25 12:39 UTC, ihor-sviziev approved these changes

2021-08-25 16:54 UTC, merged