Fix array_merge in loop
magento/magento2 pull request #33904
Opened 2021-08-25 12:14 UTC by ihor-sviziev

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-08-25 12:17 UTC, ihor-sviziev commented
@magento run all tests

2021-08-25 18:46 UTC, andrewbess requested changes
Hello @ihor-sviziev 
Thank you for your contribution.
Great job.
Could you please update branch?
Thank you in advance.

2021-08-25 19:36 UTC, dudzio12 approved these changes

2021-08-26 03:36 UTC, tanghongtanghong commented on setup/src/Magento/Setup/Module/Di/App/Task/Operation/ApplicationCodeGenerator.php
> -use Magento\Framework\App\Bootstrap;
test

2021-08-27 06:07 UTC, ihor-sviziev commented
@magento create issue

2021-08-27 08:18 UTC, Den4ik approved these changes
@ihor-sviziev Good job 👍

2021-08-27 08:19 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9203](https://jira.corp.magento.com/browse/ENGCOM-9203) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-11-03 13:48 UTC, engcom-Alfa commented
Hi @ihor-sviziev Thanks for your collaboration and contribution!
As part of QA process, I will be just require the steps to execute the to validate the performance improvements.
Could you please help me providing detailed steps to reproduce the case?

2021-11-03 13:50 UTC, ihor-sviziev commented
Hi @engcom-Alfa,
This is a performance improvement for the code generation step. It should positively affect the `setup:di:compile` time on magneto installations with a lot of extensions

2021-11-09 14:10 UTC, engcom-Alfa commented
Hi @ihor-sviziev , @tanghongtanghong , @andrewbess , @Den4ik , @dudzio12 
Thanks for the collaboration & contribution!

:x: QA not Passed

**_di:compile_** command performance needs to be reduced 

**Manual Scenario Steps**

1. Installed a fresh Magento 2.4-develop and installed a couple of extensions eg- Braintree and SMTP
2. Upgraded the Magento and make sure that the extensions are installed properly.
3. Executed the di:compile command and noted the execution time.


**:heavy_check_mark: Expected result After Fix** 
- Currently the execution time of the command taking 40 seconds with the extensions; Expected to reduce the execution time ~10% at least.


**:x: Actual result After Fix** 
- After applying the PR changes; the execution time is being same as ~40 seconds;
  <img width="1440" alt="Screenshot 2021-11-09 at 4 55 05 PM" src="https://user-images.githubusercontent.com/51679138/140938815-0270efd8-a60d-4823-8a18-6544fc2d3fa2.png">

Kindly take a look at above details and recommend if there is any information will help by any chance please!

2021-11-09 14:11 UTC, engcom-Alfa requested changes
Requesting changes if required as per above comment
Thanks

2021-11-10 13:21 UTC, Den4ik commented
@engcom-Alfa It's don't provide huge performance increase, but this PR decrease count of merge function calls that is good point for me.

![2021-11-10-16-18-49@2x](https://user-images.githubusercontent.com/1129623/141120568-e887f488-9ef5-4917-801b-eaf630ae6359.jpg)

2022-01-06 12:11 UTC, engcom-Dash commented
> @engcom-Alfa It's don't provide huge performance increase, but this PR decrease count of merge function calls that is good point for me.
> 
> ![2021-11-10-16-18-49@2x](https://user-images.githubusercontent.com/1129623/141120568-e887f488-9ef5-4917-801b-eaf630ae6359.jpg)

Hi @Den4ik  
In order to count the total number of functions call which tool you are using. Could you please suggest so that we can use the same.

2022-01-06 12:12 UTC, ihor-sviziev commented
@engcom-Dash, this is https://www.blackfire.io/

2022-01-06 12:12 UTC, Den4ik commented
Hi @engcom-Dash 
It's blackfire https://blackfire.io/

2022-01-12 07:25 UTC, engcom-Dash commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Run the blackfire profiler on magento2.4-develop with command ‘blackfire run bin/magento se:di:co’
2. Run the blackfire profiler on PR barnch with command ‘blackfire run bin/magento se:di:co’
3. compare both the profile on blackfire.
 
**Before:** :heavy_multiplication_x:   The count of array merge function is high

<img width="465" alt="Screenshot 2022-01-11 at 5 28 17 PM" src="https://user-images.githubusercontent.com/60198592/149080024-2325ce8d-db23-4c5b-bd78-14f1288a9e7c.png">

**After:** :heavy_check_mark:  The count of array merge function has been significantly reduced.

<img width="445" alt="Screenshot 2022-01-11 at 5 27 29 PM (1)" src="https://user-images.githubusercontent.com/60198592/149080231-22cf22be-ba38-4277-b432-f19d2d8f894c.png">

FYI .. To Configure blackfire in system follow the below link:
https://blackfire.io/docs/up-and-running/installation

2022-03-08 10:32 UTC, engcom-Charlie commented
It seems that bot moved this PR to Changes Requested from  Merge in Progress, so moving it back.

Thank you!

2022-04-22 18:15 UTC, merged