Add regions for Belarus
magento/magento2 pull request #33922
Opened 2021-08-26 14:53 UTC by DmitryFurs

### Description

Add regions for Belarus

### Manual testing scenarios

1. Install Magento
2. Check table directory_country_region for Belarus regions.

### Questions or comments

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33924: Add regions for Belarus

2021-08-26 18:52 UTC, shikhamis11 commented
@magento create issue

2021-08-26 18:53 UTC, shikhamis11 commented
@magento run all tests

2021-08-27 05:32 UTC, shikhamis11 requested changes

2021-08-27 05:32 UTC, shikhamis11 commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +            ['BY', 'BY-BR', 'Bresckaja voblasć'],
@DmitryFurs thank you for the Pull Request. It seems you have added state names in the Belarusian language. By default can add these in English?

2021-08-27 06:06 UTC, DmitryFurs commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +            ['BY', 'BY-BR', 'Bresckaja voblasć'],
@shikhamis11 is it ok to use values from column **Subdivision name (en)**?
https://en.wikipedia.org/wiki/ISO_3166-2:BY#Current_codes

The standard does not provide values in English, only romanization values https://www.iso.org/obp/ui/#iso:code:3166:BY

2021-08-27 08:04 UTC, bgorski commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +            ['BY', 'BY-BR', 'Bresckaja voblasć'],
From what I see in other data patches adding regions, they are actually added in native languages of those countries

2021-08-27 08:38 UTC, bgorski commented
@magento run Database Compare

2021-08-27 08:45 UTC, shikhamis11 commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +            ['BY', 'BY-BR', 'Bresckaja voblasć'],
@bgorski Thank you for the clarification. It seems fine here as well.

2021-08-27 10:01 UTC, bgorski requested changes

2021-08-27 10:01 UTC, bgorski commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +    public function apply()
A few comments here:
1. Please don't use `@inheritdoc` annotation - it doesn't exist. There's only the inline `{@inheritdoc}` annotation, but it's only for the long description. Usage for inheriting tags from a parent class annotation is not correct. See https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html. The same comment applies to other methods from this class
2. Please return $this as this is what `\Magento\Framework\Setup\Patch\PatchInterface::apply()` is annotated to return.
3. Please add return types in your methods (PHP7-way, not only annotations)

2021-08-27 10:52 UTC, DmitryFurs commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +    public function apply()
@bgorski updated, for the `getDependencies()` and `getAliases()` methods, the annotation was wrapped in curved brackets, no patch was found with its own description of these methods.

2021-08-27 11:11 UTC, bgorski commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +    public function apply()
@DmitryFurs  sorry for not expressing myself more clearly. I was trying to describe the issue with `@inheritdoc` (which doesn't exist so shouldn't be used) and added `{@inheritdoc}` as a reference for what exists and what it's for (long desc only), but I wasn't trying to suggest that you should use `{@inheritdoc}` here as a standalone tag. While it's okay to leave it here, you should also always include `@param` and `@return` tags as well (in case of `getDependencies()` and `getAliases()` methods only `@return` tags of course as they get no params). 

Consider the following example - the `\Magento\Framework\Setup\Patch\PatchInterface::getAliases()` has the following docblock:
```
/**
     * Get aliases (previous names) for the patch.
     *
     * @return string[]
     */
    public function getAliases();
```
What `{@inheritdoc}` will inherit is this:
```
Get aliases (previous names) for the patch.
```
but what it won't inherit is 
```
@return string[]
```
so this is what you have to add yourself in your `getAliases()`:
```
/**
     * {@inheritdoc}
     *
     * @return string[]
     */
    public function getAliases(): array
    {
        // code here
    }
```

2021-08-27 11:15 UTC, bgorski commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +    public function apply()
Also, I know that the core code introduces a lot of incorrectly used `{@inheritdoc}` tags and also some nonexistent `@inheritdoc` tags, so one might think that it's okay to include them in the same way. It's not. At some point in the future they will all have to be fixed.

2021-08-27 11:22 UTC, DmitryFurs commented on app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelarus.php
> +    public function apply()
@bgorski thank you for the clarification, the pull request has been updated.

2021-08-27 11:29 UTC, bgorski approved these changes
@DmitryFurs thanks for the PR and all the fixes you made on it! Looks great, clicking Approve now.

2021-08-27 11:30 UTC, magento-engcom-team commented
Hi @bgorski, thank you for the review.
[ENGCOM-9204](https://jira.corp.magento.com/browse/ENGCOM-9204) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-08-27 11:36 UTC, bgorski commented
@magento run all tests

2021-08-27 11:39 UTC, shikhamis11 commented
@magento give me test instance

2021-08-27 11:59 UTC, DmitryFurs commented
@bgorski @shikhamis11 it may be worth moving the item **Horad Minsk** to the beginning or end of the list so that the options are grouped more correctly. What do you think?

![image](https://user-images.githubusercontent.com/1055999/131123985-8ddc2b83-0751-43e9-9974-9abc27ade768.png)

2021-08-27 12:07 UTC, shikhamis11 commented
> @bgorski @shikhamis11 it may be worth moving the item **Horad Minsk** to the beginning or end of the list so that the options are grouped more correctly. What do you think?
> 
> ![image](https://user-images.githubusercontent.com/1055999/131123985-8ddc2b83-0751-43e9-9974-9abc27ade768.png)

no, I don’t think It is required. It's more important to have it in alphabetical order from (A to Z)

2021-08-27 13:37 UTC, shikhamis11 commented
@magento run Integration Tests, Functional Tests B2B

2021-08-27 16:08 UTC, shikhamis11 approved these changes

2021-08-27 16:10 UTC, magento-engcom-team commented
Hi @shikhamis11, thank you for the review.
[ENGCOM-9204](https://jira.corp.magento.com/browse/ENGCOM-9204) has been created to process this Pull Request
:eight_spoked_asterisk: @shikhamis11, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-08-30 06:40 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Should have latest Magento installed.

**Manual testing scenario:**

1. Login to the front end and navigate to My account - add/ edit address; Select country _Belarus_ and followed by try to select states belonging to Belarus.

2. Login as admin and navigate to Store> Configuration> Store Information; Select country _Belarus_ and followed by try to select states belonging to Belarus.


**Before:** :heavy_multiplication_x: State names were not displaying belonging to the Belarus country
   ![image](https://user-images.githubusercontent.com/51679138/131295723-a7ac2e5c-230e-45b0-80df-cde11269c1fa.png)


**After:** :heavy_check_mark:  State names of Belarus country are getting displayed in the state dropdown options appropriately
   ![image](https://user-images.githubusercontent.com/51679138/131296163-d3bd11b3-d4b7-4285-a266-7727525bda50.png)


There is no additional testing/ regression is required since it is relevant to updating an state names belonging to one country.

2021-09-01 08:39 UTC, Den4ik approved these changes

2021-09-01 08:40 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9204](https://jira.corp.magento.com/browse/ENGCOM-9204) has been created to process this Pull Request

2021-09-23 15:54 UTC, merged