33916: CE eliminated calls deprecated methods of the phpunit/phpunit
magento/magento2 pull request #33932
Opened 2021-08-27 11:48 UTC by anzin

### Description (*)
I've eliminate calls deprecated methods of the phpunit/phpunit, now it provokes warning, but it will provoke error in future.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/599
https://github.com/magento/partners-magento2b2b/pull/585
https://github.com/magento/adobe-stock-integration/pull/1864

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33916

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-08-27 12:08 UTC, anzin commented
@magento run Unit Tests

2021-08-27 13:01 UTC, anzin commented
@magento run all tests

2021-08-27 13:02 UTC, BarnyShergold requested changes
A superb PR - not just removing all the deprecated methods but refactoring and cleaning up the DOCBLOCKS & return types on prototypes.

I only found 2 things suggested to change.

But - as you have done such a great job cleaning up the classes and adding things that are now best practice, can I ask - should not all "protected" methods be changed to "private"?

Same thing goes for class variables?
EG 
protected $objectManagerHelper;

to 

private $objectManagerHelper;

2021-08-27 13:02 UTC, BarnyShergold commented on app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php
> +        $this->_attribute
Single method call so should be on one line

2021-08-27 13:02 UTC, BarnyShergold commented on app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php
> +        $this->_attribute
Single method call so should be on one line

2021-08-27 16:50 UTC, anzin commented
@magento run WebAPI Tests, Functional Tests EE

2021-08-30 06:50 UTC, anzin commented
@magento run WebAPI Tests, Functional Tests EE

2021-08-30 09:30 UTC, anzin commented
@magento run  Functional Tests EE

2021-08-30 17:46 UTC, anzin commented on app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php
> +        $this->_attribute
Hello @BarnyShergold, thanks for your review, I corrected the code according to the recommendations, please check if everything well.

Thank you.

cc @andrewbess

2021-08-31 07:16 UTC, anzin commented
@magento run all tests

2021-08-31 09:11 UTC, anzin commented
@magento run Functional Tests CE

2021-08-31 10:58 UTC, BarnyShergold commented on app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php
> +        $this->_attribute
This one doesn't seem to show up as fixed?

2021-08-31 11:59 UTC, anzin commented
@magento run all tests

2021-08-31 13:39 UTC, anzin commented
@magento run Functional Tests CE

2021-08-31 15:33 UTC, andrewbess approved these changes

2021-08-31 15:34 UTC, eduard13 approved these changes

2021-08-31 20:01 UTC, merged