[MFTF] AdminAddNewDefaultBillingShippingCustomerAddressTest refactoring
magento/magento2 pull request #33999
Opened 2021-09-06 08:18 UTC by AnnaAPak

### Description (*)
The test is refactored according to the best practices

2021-09-06 08:20 UTC, AnnaAPak commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

2021-09-07 11:21 UTC, Den4ik requested changes
@AnnaAPak Thanks for work on tests.
Please look at my comments

2021-09-07 11:21 UTC, Den4ik commented on app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminClickEditLinkForDefaultBillingAddressActionGroup.xml
> +
Please add new line at the end of file

2021-09-07 11:21 UTC, Den4ik commented on app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminFillAndSaveCustomerlAddressInformationActionGroup.xml
> +</actionGroups>
Please add new line at the end of file

2021-09-08 08:23 UTC, AnnaAPak commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

2021-09-08 09:26 UTC, eduard13 commented on app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminAssertCustomerDefaultShippingAddressAgainstEntityActionGroup.xml
> +            <description>Asserts that Customer's Default Billing Address matches the specified Address entity</description>
```suggestion
            <description>Asserts that Customer's Default Shipping Address matches the specified Address entity</description>
```

2021-09-08 09:26 UTC, eduard13 requested changes
Please check the above suggestion

2021-09-10 08:57 UTC, AnnaAPak commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

2021-09-24 09:00 UTC, engcom-Charlie commented
@magento run all tests

2021-09-24 11:23 UTC, engcom-Charlie commented
It seems that all the review comment's have been taken care and rectified, so moving it further.

Thank you!

2021-10-13 05:24 UTC, eduard13 approved these changes

2021-10-13 05:26 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9251](https://jira.corp.magento.com/browse/ENGCOM-9251) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-10-14 12:10 UTC, Den4ik approved these changes

2021-10-14 12:11 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9251](https://jira.corp.magento.com/browse/ENGCOM-9251) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-11-04 21:06 UTC, merged