Greatly improve performance on dockerized Magento instances (mainly on mac) by caching subsequent glob calls
magento/magento2 pull request #33998
Opened 2021-09-06 07:52 UTC by thlassche

### Description (*)
This pull request introduces an in-memory cache for glob system calls. On systems where file I/O is slow (for example Docker for Mac), glob system calls can be quite slow. This pull requests caches the same glob calls and returns a cached result if possible. In my testing this reduced the glob calls on the category listings from ~8K to ~1.6K.

Blackfire comparison:

<img width="544" alt="Screenshot 2021-09-06 at 09 51 21" src="https://user-images.githubusercontent.com/2959888/132180261-047d2cb6-e2bd-43ae-afac-02a18b09b4e7.png">

### Related Pull Requests
None

### Fixed Issues (if relevant)
None
1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
1. Profile any page before this diff is applied
2. Apply diff and reprofile
3. See a reduction in `glob()` calls

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2021-09-06 08:05 UTC, ihor-sviziev commented
@magento run all tests

2021-09-06 08:17 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Filesystem/Glob.php
> +    protected static $cache = [];
It looks like it should be private cache

```suggestion
    private static $cache = [];
```

Also, wonder if we should have a mechanism for removing the cache...
Will see after test results

2021-09-06 08:18 UTC, thlassche commented
@magento run all tests

2021-09-06 09:00 UTC, ihor-sviziev commented
It might significantly improve performance not only on dockerized environments but also on the ec2 instances or any server using network file storage as magento storage.

2021-09-06 13:20 UTC, andrewbess approved these changes

2021-09-06 13:21 UTC, magento-engcom-team commented
Hi @andrewbess, thank you for the review.
[ENGCOM-9214](https://jira.corp.magento.com/browse/ENGCOM-9214) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-09-06 14:16 UTC, ihor-sviziev approved these changes

2021-09-06 14:17 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9214](https://jira.corp.magento.com/browse/ENGCOM-9214) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-09-06 14:20 UTC, ihor-sviziev commented
I think we don't need to cover it with any test as it will be not so easy.

2021-09-07 11:11 UTC, Den4ik approved these changes

2021-09-07 11:13 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9214](https://jira.corp.magento.com/browse/ENGCOM-9214) has been created to process this Pull Request

2021-09-08 11:01 UTC, engcom-Hotel commented
@magento run all tests

2021-09-08 11:09 UTC, engcom-Hotel commented
@magento create issue

2021-09-08 11:13 UTC, engcom-Hotel commented
@magento create issue

2021-09-08 11:15 UTC, engcom-Hotel commented
@magento give me 2.4-develop instance

2021-09-08 12:39 UTC, engcom-Hotel commented
@magento give me 2.4-develop instance

2021-09-08 12:51 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-09-08 14:34 UTC, onlinebizsoft commented
> It might significantly improve performance not only on dockerized environments but also on the ec2 instances or any server using network file storage as magento storage.

What do you mean by "magento storage"? You mean "media storage"? @ihor-sviziev

2021-09-08 14:37 UTC, ihor-sviziev commented
@onlinebizsoft, I think it's not only media folder, but also where magento code is located.

2021-09-08 14:40 UTC, engcom-Hotel requested changes
Hello @thlassche,

Some tests are failing for e.g. Functional Tests B2B, Functional Tests CE, Functional Tests EE. Please look into this.

2021-09-08 14:42 UTC, ihor-sviziev commented
@engcom-Hotel, the service that responsible for the currency API doesn't work. Here is confirmation: https://github.com/magento/magento2/pull/34021#issuecomment-915258946

2021-09-08 14:45 UTC, onlinebizsoft commented
> @onlinebizsoft, I think it's not only media folder, but also where magento code is located.

Interesting! Im not sure how glob is used and called in Magento. I thought Magento files would be loaded in OPcache memory already

2021-09-08 14:52 UTC, engcom-Hotel commented
> @engcom-Hotel, the service that responsible for the currency API doesn't work. Here is confirmation: [#34021 (comment)](https://github.com/magento/magento2/pull/34021#issuecomment-915258946)

Thanks for the clarification @ihor-sviziev

2021-09-08 15:00 UTC, engcom-Hotel commented
✔️ QA Passed

Hello @thlassche,

Thanks for the contribution!

**Preconditions**
Magento 2.4-develop branch

**Manual testing scenario**
1. Run profiler on Magento 2.4-develop with sample data installed.
2. Run profiler on this PR fix with sample data installed. 
3. Compare results.

![image](https://user-images.githubusercontent.com/51681618/132534109-63dd334c-0135-4514-a8bb-1fe999bd841b.png)

2021-09-10 14:31 UTC, onlinebizsoft commented
> ✔️ QA Passed
> 
> Hello @thlassche,
> 
> Thanks for the contribution!
> 
> **Preconditions**
> Magento 2.4-develop branch
> 
> **Manual testing scenario**
> 
>     1. Run profiler on Magento 2.4-develop with sample data installed.
> 
>     2. Run profiler on this PR fix with sample data installed.
> 
>     3. Compare results.
> 
> 
> ![image](https://user-images.githubusercontent.com/51681618/132534109-63dd334c-0135-4514-a8bb-1fe999bd841b.png)

Just reduce few ms?!!

2021-09-10 14:37 UTC, thlassche commented
> > ✔️ QA Passed
> 
> > 
> 
> > Hello @thlassche,
> 
> > 
> 
> > Thanks for the contribution!
> 
> > 
> 
> > **Preconditions**
> 
> > Magento 2.4-develop branch
> 
> > 
> 
> > **Manual testing scenario**
> 
> > 
> 
> >     1. Run profiler on Magento 2.4-develop with sample data installed.
> 
> > 
> 
> >     2. Run profiler on this PR fix with sample data installed.
> 
> > 
> 
> >     3. Compare results.
> 
> > 
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/51681618/132534109-63dd334c-0135-4514-a8bb-1fe999bd841b.png)
> 
> 
> 
> Just reduce few ms?!!

It depends a lot on what is currently in the cache and what is not. The first load of uncached pages will benefit way more.

2021-09-20 11:21 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-09-24 14:45 UTC, Den4ik commented
@magento run all test

2021-09-24 14:45 UTC, Den4ik commented
@magento run all tests

2021-11-21 02:33 UTC, merged