decouple product view gallery images config from Gallery Block
magento/magento2 pull request #3401
Opened 2016-02-14 09:16 UTC by davidverholen

Last week we had the Problem, that we wanted to add some additional image types (picture tag for different viewports) to the Product View Gallery Images.

Since the creation of the Data array for the json configuration is hardcoded in the block, we had to implement a Plugin.
https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Block/Product/View/Gallery.php#L58

Although it also works with a Plugin, I thought it would be nicer if this configuration is decoupled from the Gallery Block, since this configuration also depends on the template having the images defined in the view.xml

2016-03-16 18:57 UTC, davidverholen commented
a better approach would maybe be to set a flag in the view xml for "use as gallery image". Not sure about this. Are there any ideas yet?

I think it's not good to rely on the view.xml definitions in core modules as you can't be sure that the image definition exists in the theme

2017-03-25 15:36 UTC, vrann commented
@davidverholen can you please merge this branch with the latest develop?

2017-03-26 07:25 UTC, davidverholen commented
@vrann just rebased it on the current develop

2017-04-13 08:30 UTC, ishakhsuvarov requested changes

2017-04-13 08:30 UTC, ishakhsuvarov commented on app/code/Magento/Catalog/Block/Product/View/Gallery.php
> +        \Magento\Catalog\Model\Product\Gallery\ImagesConfigFactoryInterface $imagesConfigFactory,
Unfortunately, due to backwards compatibility policy, we can not accept changes which change constructor signature by introducing a new required parameter.
You may fix it like:
```php
use Magento\Framework\App\ObjectManager;
...
public function __construct(
    \New\Dependency $newDependency = null
) {
    $this->newDependency = $newDependency ?: ObjectManager::getInstance()->get(\New\Dependency::class)
}
```

2017-04-13 08:30 UTC, ishakhsuvarov commented on app/code/Magento/Catalog/Model/Product/Gallery/ImagesConfigFactory.php
> +    protected $_dataCollectionFactory;
We do not encourage inheritance-based API, please make this property private. Additionally, naming convention with underscores is considered legacy, please rename this property.

2017-04-13 08:30 UTC, ishakhsuvarov commented on app/code/Magento/Catalog/Block/Product/View/Gallery.php
> +        \Magento\Framework\Json\EncoderInterface $jsonEncoder,
We encourage use of `\Magento\Framework\Serialize\Serializer\Json` for json serialization.

2017-04-13 08:30 UTC, ishakhsuvarov commented on app/code/Magento/ProductVideo/Block/Product/View/Gallery.php
> +        \Magento\Catalog\Model\Product\Gallery\ImagesConfigFactoryInterface $imagesConfigFactory,
Please inject with the `ObjectManager` as described above.

2017-04-13 08:57 UTC, ishakhsuvarov commented
@davidverholen Thanks for the PR, looks pretty good to me.
Please resolve the conflict, check review comments and Travic CI fails. If it's all good I am going to proceed with the merge asap, so that no new conflicts arise.
Thank you for your collaboration!

2017-04-13 11:40 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=3401) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=3401) before we can accept your contribution.<br/>

2017-04-13 12:04 UTC, davidverholen commented
@ishakhsuvarov thx for the review!

I just implemented most change requests, but I had to keep the Json Encoder I think since it's part of the original constructor.

2017-04-13 14:01 UTC, ishakhsuvarov approved these changes

2017-04-13 14:01 UTC, ishakhsuvarov commented
@davidverholen Thanks, we are going to continue with review and merge

2017-07-20 11:29 UTC, ishakhsuvarov commented
@davidverholen 
Please sign the CLA for this PR, we can not proceed until it's signed.
Also, if you don't mind, please check the "Allow edits from maintainers" checkbox on this PR, so that I could push back some coding style fixes and develop merge I have made for your branch.

2017-07-20 13:09 UTC, davidverholen commented
@ishakhsuvarov  I tried to sign the CLA, not sure if it worked. It redirected me to the CLA page, I signed in and then it reloaded the page with the box in the middle beeing empty. After some time, I was redirected back to this pr but it's still "yellow" in the pr checks

2017-07-20 13:14 UTC, ishakhsuvarov commented
@davidverholen 
Looks like you have been working on it with someone else or with a different account. That may be the cause.

2017-07-20 13:25 UTC, bragento commented
@ishakhsuvarov good point, there is one commit I made with our company account

2017-07-21 21:35 UTC, merged

2019-03-16 19:31 UTC, Ctucker9233 commented
@magento-team Can this be backported to 2.2?