Fixed the welcome message contains single quote character
magento/magento2 pull request #34061
Opened 2021-09-12 12:25 UTC by khoimm92

### Description (*)

This PR is fixed for the issue, that if we put the single quote character to the header welcome message config, it will lead the frontend to have a bunch of console errors:

> Uncaught SyntaxError: Unable to process binding "ifnot: function(){return customer().fullname }"
Message: Unable to parse bindings.

### Manual testing scenarios (*)

1. From Admin, navigate to Content -> Design -> Configuration
2. Select a theme and Edit
3. In the edit page, expand the Header setting, put the `Welcome Text`, like "Welcome Khoi's store!"
4. Clear cache, then go to frontend, you'll see a JS error, and some JS functions not working because of this issue.

### Questions or comments
Maybe we need to bind the message as a text, instead of HTML binding, like:

> data-bind="text: '<?= $escaper->escapeHtmlAttr($welcomeMessage) ?>'"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-12 12:28 UTC, khoimm92 commented
@magento run all tests

2021-09-14 02:39 UTC, mrtuvn commented
imho should be text in that point

2021-09-16 08:58 UTC, BarnyShergold commented
@magento run all tests

2021-09-16 08:59 UTC, BarnyShergold commented
@khoimm92 - You need to sign the Adobe CLA as part of this PR review - you only ever need to do this once.

2021-09-17 01:06 UTC, khoimm92 commented
@magento run all tests

2021-09-17 08:52 UTC, BarnyShergold commented
@magento run Static Tests

2021-09-20 09:18 UTC, BarnyShergold commented
@khoimm92 - You will need to fix the Static test on this - not sure why they passed before!

2021-09-21 09:20 UTC, BarnyShergold commented
@khoimm92 - You also need to sign the Adobe CLA

2021-09-23 13:43 UTC, BarnyShergold commented
@magento run all tests

2021-09-24 14:31 UTC, Den4ik requested changes
@khoimm92 Please fix failed static tests

2021-09-24 16:01 UTC, mrtuvn commented
![wt](https://user-images.githubusercontent.com/1908873/134705907-b78dd2d8-f321-4f49-bedd-ee983476c4d3.png)
html not allowed

2021-09-24 16:43 UTC, khoimm92 commented
Thanks @mrtuvn, let me change that.
@BarnyShergold @Den4ik I got it. Also, my fix did not cover the case putting the double quote. Let me have a tweak for this.

2021-10-07 14:23 UTC, BarnyShergold commented
@khoimm92 - We've not had an update or change on this PR for 2 weeks. Can you let us know when you will complete changes or we'll have to close the PR for inactivity - cheers

2021-12-31 07:13 UTC, engcom-Bravo commented
@magento run all tests

2021-12-31 12:23 UTC, engcom-Bravo commented
@magento run all tests

2021-12-31 14:55 UTC, engcom-Bravo commented
@magento run all tests

2022-01-02 03:38 UTC, engcom-Bravo commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2022-01-03 08:21 UTC, engcom-Bravo commented
@magento run all tests

2022-01-03 10:48 UTC, engcom-Bravo commented
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

2022-01-03 16:17 UTC, engcom-Bravo commented
@magento run all tests

2022-01-04 01:49 UTC, Den4ik requested changes
@khoimm92 Please fix failed Static Tests

2022-01-04 04:01 UTC, engcom-Bravo commented
@magento run all tests

2022-01-04 06:09 UTC, engcom-Bravo commented
@magento run Functional Tests CE,Functional Tests B2B

2022-04-25 15:48 UTC, ishakhsuvarov approved these changes

2022-04-26 09:52 UTC, engcom-Alfa commented
@magento run all tests

2022-04-26 12:37 UTC, engcom-Alfa commented
@magento Functional Tests B2B, Functional Tests CE, Functional Tests EE

2022-04-26 12:37 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2022-04-27 06:00 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2022-04-27 10:39 UTC, engcom-Alfa commented
https://github.com/magento run Functional Tests B2B, Functional Tests EE

2022-04-27 10:39 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE

2022-04-27 12:18 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have Magento 2.4-develop latest code installed


**Manual testing scenario:**

1. Admin login> Content> Configuration> Header section> Edit the Welcome Message to something like `"Welcome XYZ"` (Here, double quotes is a part of message). Save the configurations.

2. Open the front end customer side, and valid the message JS errors in Console as well.

**Before:** :heavy_multiplication_x: There was a JS Syntax error in the console and as well as message was not displayed.
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/51679138/165513609-8b13c2a6-9b72-4ff4-ad03-37502decd0b6.png">

**After:** :heavy_check_mark: Message is displayed accordingly and JS Syntax error is not existing anymore.
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/51679138/165513702-6a43d4f6-3f63-4703-b4b1-edd746499725.png">

It is a specific case affecting functional and home presentation, will be added with the regression test case covering a few more input types as well.

2022-04-27 12:19 UTC, engcom-Alfa commented
Since a couple of jobs are getting failed continuously even after multiple tries, moving this PR ticket to Extended Testing column for further investigation.

2022-05-06 14:34 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2022-05-06 14:37 UTC, engcom-Charlie commented
It seems bot moved this PR from Extended Testing to Ready for testing after assignment, so moved it back to Extended Testing.

2022-05-11 06:33 UTC, engcom-Charlie commented
Since the build is green now and as per this above [comment](https://github.com/magento/magento2/pull/34061#issuecomment-1110931454) PR is QA passed so moving it to Merge in Progress.

Thank you!

2022-05-11 20:29 UTC, Den4ik commented
@engcom-Charlie  did you test it with another characters that require slash. For example, double quotes?

2022-05-11 20:33 UTC, Den4ik requested changes
Hey @khoimm92 
Could you check my comment

2022-05-11 20:33 UTC, Den4ik commented on app/code/Magento/Theme/Block/Html/Header.php
> +        $this->_data['welcome'] = str_replace("'", "\'", $this->_data['welcome']);
I believe that use off `addslashes` is more preferable here

2022-05-12 06:47 UTC, engcom-Charlie commented
> @engcom-Charlie did you test it with another characters that require slash. For example, double quotes?

Hi @Den4ik,

Sure, will look into your review comments.

Thank you!

2022-05-12 12:02 UTC, engcom-Charlie commented
Hi @Den4ik,

I have mode the modification suggested by you. addslashes() is working well for all combinations of welcome message. Committed and pushed the code.

Moving this PR to Ready for Testing now.

Thank you!

2022-05-12 12:03 UTC, engcom-Charlie commented
@magento run all tests

2022-05-13 10:56 UTC, engcom-Lima commented
@magento run all tests

2022-05-16 05:41 UTC, engcom-Lima commented
@magento run Integration Tests Static Tests

2022-05-16 05:45 UTC, engcom-Lima commented
@magento run Integration Tests,Static Tests

2022-05-16 12:31 UTC, engcom-Lima commented
@magento run Integration Tests,Static Tests

2022-05-16 14:08 UTC, engcom-Lima commented
@magento create issue

2022-05-17 07:39 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Install the fresh Magento 2.4-develop instance.
2. Have a few products already created in the instance

**Manual testing scenario:**

1. Login to Admin, navigate to Content -> Design -> Configuration
2. Select a theme and Edit
3. In the edit page, expand the Header setting, put the Welcome Text, like "Welcome to our's store!"
4. Clear cache, then go to frontend and open the console

**Before:** :heavy_multiplication_x: Getting JS error, and some JS functions not working because of this issue.

![jserror](https://user-images.githubusercontent.com/60198022/168755149-7d3f3200-f153-47e9-a931-b2b1bd9b14fb.png)

**After:** :heavy_check_mark:  There was no js error found in the console after PR changes.
![Screenshot from 2022-05-13 16-39-03](https://user-images.githubusercontent.com/60198022/168755278-e3f1e633-3ef0-40e4-a430-bd5dae19a53a.png)

Tried to use different type of symbols and validated if any error visible in the front-end.

2022-05-18 09:23 UTC, engcom-Charlie commented
@magento run Integration Tests, Static Tests

2022-05-20 13:22 UTC, engcom-Charlie commented
After making [these](https://github.com/magento/magento2/pull/34061#issuecomment-1124906069) changes was getting below static test failure. 

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/51680850/169536876-e10f6a42-3e42-4a30-bc45-e1a1acf7680d.png">

Implemented the fix for the same and pushed the code base.

Thank you!

2022-05-20 13:23 UTC, engcom-Charlie commented
@magento run all tests

2022-05-23 06:06 UTC, engcom-Lima commented
@magento run all tests

2022-05-23 10:31 UTC, engcom-Lima commented
@magento run Unit Tests, Static Tests, Semantic Version Checker

2022-05-23 11:10 UTC, engcom-Lima commented
@magento run Static Tests

2022-05-23 11:11 UTC, engcom-Lima commented
@magento give me test instance

2022-05-24 07:06 UTC, engcom-Charlie commented
@magento run Static Tests, Semantic Version Checker, Unit Tests

2022-05-24 08:45 UTC, engcom-Charlie commented
@magento run all tests

2022-05-24 09:16 UTC, Den4ik requested changes
Hi @engcom-Charlie 
Thanks for your update. Please look at my comment

2022-05-24 09:16 UTC, Den4ik commented on app/code/Magento/Theme/Block/Html/Header.php
> +        $this->_escaper = $escaper;
Property declared at line 22 don't has underscore.
Please don't use underscored variables and properties.

2022-05-26 05:01 UTC, engcom-Charlie commented
Hi @Den4ik,

Thank you for reviewing the changes.

I have modified the implementation as per your suggested changes and pushed the code.

Thank you!

2022-05-26 05:02 UTC, engcom-Charlie commented
@magento run all tests

2022-05-26 12:28 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Semantic Version Checker, Unit Tests

2022-05-30 13:35 UTC, engcom-Charlie commented
@magento run all tests

2022-05-30 13:38 UTC, engcom-Charlie commented
Fixed the build failure. Implemented the fix for unit test and pushed the code for the same.

Moving it to Testing now.

Thank you!

2022-05-31 06:25 UTC, engcom-Alfa commented
@magento run Functional Tests EE, Integration Tests, Semantic Version Checker

2022-06-01 06:29 UTC, engcom-Lima commented
@magento run Semantic Version Checker

2022-06-01 07:42 UTC, engcom-Lima commented
@magento run Semantic Version Checker

2022-06-01 09:56 UTC, engcom-Lima commented
Tested this PR, working fine but Semantic Version Checker is failed. Hence, raising [JIRA](https://jira.corp.magento.com/browse/MC-43367) approval for svc failure.

2022-08-08 11:56 UTC, engcom-Charlie commented
It seems that bot moved the PR from Pending Approval to Changes Requested. Moving it back.

Thank you!

2022-08-31 07:41 UTC, merged