code cleanup: Remove impossible invoice condition
magento/magento2 pull request #34072
Opened 2021-09-14 08:33 UTC by ilnytskyi

### Description (*)

As the invoiceService declared to always return InvoiceInterface
```
$this->invoiceService->prepareInvoice($order, $invoiceItems);
```
in
https://github.com/ilnytskyi/magento2/blob/6df210e6e40c1e853137cf365bc390f6721d7011/app/code/Magento/Sales/Model/Service/InvoiceService.php#L148

This check is not needed
```
if (!$invoice)
```

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. create invoice
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-14 09:43 UTC, BarnyShergold commented on app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/Save.php
> -            if (!$invoice) {
Won't this cause an issue now with the testExecuteNotValidPost() test? - need to see

2021-09-14 15:22 UTC, ilnytskyi commented
@magento run all tests

2021-09-15 10:05 UTC, Den4ik requested changes
@ilnytskyi Please fix failed static test

2021-09-15 10:20 UTC, ilnytskyi commented
@magento run all tests

2021-09-15 15:08 UTC, ilnytskyi commented
@magento run all tests

2021-09-15 19:09 UTC, ilnytskyi commented
@magento run Integration Tests

2021-09-15 19:10 UTC, ilnytskyi commented
@magento run Functional Tests B2B

2021-09-16 05:47 UTC, ihor-sviziev approved these changes

2021-09-16 05:48 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9220](https://jira.corp.magento.com/browse/ENGCOM-9220) has been created to process this Pull Request

2021-09-16 08:26 UTC, Den4ik approved these changes

2021-09-16 08:27 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9220](https://jira.corp.magento.com/browse/ENGCOM-9220) has been created to process this Pull Request

2021-09-16 08:53 UTC, BarnyShergold approved these changes

2021-09-16 08:55 UTC, magento-engcom-team commented
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9220](https://jira.corp.magento.com/browse/ENGCOM-9220) has been created to process this Pull Request

2022-05-20 07:19 UTC, ilnytskyi commented
up

2022-07-31 13:36 UTC, ilnytskyi commented
up

2022-10-28 21:33 UTC, merged

2024-01-25 08:30 UTC, andrewbess commented
This PR is already merged