Fixed #30520
magento/magento2 pull request #34094
Opened 2021-09-16 11:47 UTC by elisei

### Description
Orders with payment_review and state status other than "fraud" are visible on the store frontend as "processing".

### Fixed Issues
1. Fixes magento/magento2#30520

### Manual testing scenarios (*)
1. Implement a customized payment method that will reach the status of payment_review.
2. Make the purchase using this method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-16 11:48 UTC, elisei commented
@magento run all tests

2021-09-16 12:26 UTC, elisei commented
@magento run all tests

2021-09-16 14:20 UTC, elisei commented
@magento run Functional Tests EE

2021-09-16 16:48 UTC, elisei commented
@magento run Static Tests

2021-09-16 17:30 UTC, elisei commented
@magento run Static Tests

2021-09-17 09:13 UTC, BarnyShergold commented
@elisei - It looks like there is an extra empty line at line 131/132 in the file - if you remove this then the static tests should then pass. I'm not sure why this is only coming up now as you didn't change the code there!

2021-09-17 09:29 UTC, BarnyShergold commented
I found the issue but not sure why it has not caused a problem before.

On the 21st May a private method was removed from the class : https://github.com/magento/magento2/commit/5af7f5afe2422543ae543d9dd21370dd0e49e665#diff-afd7df9cf4ca0da0103aaad00b7c2672cd585ebfcce41f621cdb0f7e298d58ba

This was done without removing an empty line. I suggest you just make the correction.

2021-09-17 09:52 UTC, Den4ik commented
@magento run all tests

2021-09-17 09:55 UTC, Den4ik requested changes
@elisei Thanks for your work.
I've just checked your changes and see that `$maskStatusesMapping` is unused property.
Could you please recheck changes.

Also as mentioned @BarnyShergold  I have removed extra line for fixing static tests.

2021-09-17 10:01 UTC, Den4ik commented
As I see correct way for fix issue located here https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/etc/di.xml#L1030-L1039

2021-09-17 12:59 UTC, elisei commented
@BarnyShergold and @Den4ik

Thank you very much for your support, this pull was recycled from another of mine in 2020 and looking at the Den4ik indication I have a question.

Wouldn't it be more interesting to apply in the STATUS_FRAUD its rewrite in the frontend to maybe even the PAYMENT_REVIEW and in the STATE_PAYMENT_REVIEW simply remove?

2021-09-17 13:27 UTC, Den4ik commented
@elisei I believe that we should use correct state `STATE_PAYMENT_REVIEW` instead of removing it.

2021-09-17 13:33 UTC, elisei commented
@Den4ik 
That's exactly what I'm proposing, just remove it from the function leaving it visible as it really is in the frontend.

However, I believe that STATUS_FRAUD should not be viewed in its real status, and my suggestion here is to make it visible on the frontend as STATE_PAYMENT_REVIEW

2021-09-17 13:38 UTC, Den4ik commented
I think it's question for Product Manager.
@gabrieldagama Could you assist to address this question to Product Manager?

2022-10-13 15:18 UTC, ishakhsuvarov commented
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

2022-10-13 15:18 UTC, closed without merging