Php8 compatibility/fixes for integration tests p1
magento/magento2 pull request #34095
Opened 2021-09-16 12:39 UTC by anzin

### Description (*)

Stabilize Integration Tests to be compatible both with PHP7 and PHP8.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#34020

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-16 12:47 UTC, eduard13 commented
@magento run Integration Tests with env PHP 8.0

2021-09-16 14:01 UTC, andrewbess commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health

2021-09-16 14:36 UTC, eduard13 commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health

2021-09-16 15:06 UTC, anzin commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health

2021-09-16 20:37 UTC, anzin commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health

2021-09-17 08:05 UTC, Den4ik commented
@andrewbess do we have documentation for `magento run ` command with options like `env`, `extensions`?

2021-09-17 08:12 UTC, eduard13 commented
@Den4ik only what's described here https://devdocs.magento.com/contributor-guide/contributing.html#customize-deployed-instances.

2021-09-17 08:19 UTC, Den4ik commented
@eduard13 Thanks. I missed this part of documentation

2021-09-17 11:23 UTC, anzin commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health

2021-09-17 13:28 UTC, eduard13 commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health

2021-09-22 07:53 UTC, andrewbess commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health without extensions magento-commerce/magento2-page-builder, magento-commerce/magento2-page-builder-ee, magento-commerce/adobe-stock-integration, magento-commerce/adobe-ims

2021-09-22 11:11 UTC, karyna-tsymbal-atwix commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health without extensions magento-commerce/magento2-page-builder, magento-commerce/magento2-page-builder-ee, magento-commerce/adobe-stock-integration, magento-commerce/adobe-ims

2021-09-22 13:49 UTC, andrewbess commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health without extensions magento-commerce/magento2-page-builder, magento-commerce/magento2-page-builder-ee, magento-commerce/adobe-stock-integration, magento-commerce/adobe-ims

2021-09-22 16:41 UTC, anzin commented
@magento run Integration Tests with env PHP 8.0 with extensions magento-commerce/security-package-b2b:platform-health without extensions magento-commerce/magento2-page-builder, magento-commerce/magento2-page-builder-ee, magento-commerce/adobe-stock-integration, magento-commerce/adobe-ims

2021-09-23 11:18 UTC, andrewbess commented
@magento run all tests with extensions magento-commerce/security-package-b2b:platform-health

2021-09-23 20:00 UTC, andrewbess commented
@magento run Static Tests

2021-09-24 04:28 UTC, Den4ik commented
Looking into this PR. I believe that Failed "Copy/Past" check with B2B could be ignored.

2021-09-24 10:38 UTC, andrewbess commented
@magento run Static Tests, Unit Tests, Integration Tests

2021-09-24 12:03 UTC, Den4ik requested changes
Please look at my review comments

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Customer/Model/AccountManagement.php
>                  )
Both solutions trigger fatal error on PHP 8 and warning on PHP 7.4 because `call_user_func_array` extract array elements and use them as arguments for `array_merge`.

I suggest to use
```
return $validationResults->setIsValid(false)->setMessages($this->getEavValidator()->getMessages());
```

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Customer/Model/AccountManagement.php
>                  )
Another one point:
`$this->getEavValidator()->getMessages()` is always array.
I suggest to use `$this->getEavValidator()->hasMessages()` in `if` condition

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Newsletter/Model/Queue.php
> +use InvalidArgumentException;
I believe that it should be `Magento\Framework\Exception\InvalidArgumentException` because https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Newsletter/Controller/Adminhtml/Queue/Save.php#L90 controller detect only `LocalizedException`s

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Newsletter/Model/Queue.php
> +            throw new InvalidArgumentException('Start date should be of type string or null');
With `Magento\Framework\Exception\InvalidArgumentException` it should be `Phrase` 

```suggestion
            throw new InvalidArgumentException(__('Invalid start date value.'));
```

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Paypal/Model/Cart.php
> +        $this->addDiscount(abs((float) $this->_salesModel->getBaseDiscountAmount()));
Why did you use space after type casting here but don't use it at `app/code/Magento/Paypal/Model/Express/Checkout.php`.
I believe that no-space style is more clear

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Quote/Model/ResourceModel/Quote.php
> +            // In PHP > 8, comparing the arrays [0] != ['*'] returned false
PHP < 8 return `false`

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Usps/Model/Carrier.php
> +                    });
I don't see any reasons of changing old logic because both results give equal result on PHP 7 and PHP 8

2021-09-24 12:03 UTC, Den4ik commented on app/code/Magento/Usps/Model/Carrier.php
> +                    });
I don't see any reasons of changing old logic because both results give equal result on PHP 7 and PHP 8

2021-09-24 12:03 UTC, Den4ik commented on dev/tests/integration/testsuite/Magento/Newsletter/Controller/Adminhtml/NewsletterQueueTest.php
> +        $this->expectExceptionMessage('Start date should be of type string or null');
Please look at the review comment for `app/code/Magento/Newsletter/Model/Queue.php`

2021-09-24 12:03 UTC, Den4ik commented on lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php
> +                return $this->_stmt->execute();
Could you please explain this implementation

2021-09-24 15:41 UTC, anzin commented on app/code/Magento/Usps/Model/Carrier.php
> +                    });
Hello @ Den4ik , thanks for your review, there are exceptions when result are different  on PHP 7 and PHP 8 ,this functional emulates an old behavior. 
Check this array `[3 => 24.85, 2 => 24.85, 23 => 37.35, 55 => 39.95, 56 => 39.95, 57 => 52.45, 13 => 19.95, 27 => 19.95, 25 => 32.45, 1 => 8.85, 22 => 16.85, 17 => 12.35, 28 => 5.8, 16 => 5.6, 42 => 5.6, 4 => 8.85, 6 => 4.33, 7 => 4.12]`  it is real parameter.

<img width="1052" alt="Screenshot 2021-09-24 at 18 31 30" src="https://user-images.githubusercontent.com/30952336/134702070-78f260e3-6b0e-4d00-8770-c786b8b3550e.png">
**The order of the keys is different.**

Thank you.

2021-09-24 15:41 UTC, anzin commented on app/code/Magento/Usps/Model/Carrier.php
> +                    });
Please check previous comment.

2021-09-24 16:11 UTC, Den4ik commented on app/code/Magento/Usps/Model/Carrier.php
> +                    });
> Note:
> If two members compare as equal, they retain their original order. Prior to PHP 8.0.0, their relative order in the sorted > array was undefined.

It looks like php core bug that we trying to emulate :)

2021-09-27 10:31 UTC, andrewbess commented
@magento run all tests

2021-09-27 10:43 UTC, andrewbess commented on app/code/Magento/Quote/Model/ResourceModel/Quote.php
> +            // In PHP > 8, comparing the arrays [0] != ['*'] returned false
Hello @Den4ik 
The comparisons for [0] != ['*'] have different results for PHP < 8 and PHP >= 8.
Please check https://3v4l.org/NIAsR

2021-09-27 10:56 UTC, andrewbess commented
@magento run all tests

2021-09-27 11:00 UTC, andrewbess commented
@magento run all tests with env PHP 8.0

2021-09-27 11:21 UTC, Den4ik commented on app/code/Magento/Quote/Model/ResourceModel/Quote.php
> +            // In PHP > 8, comparing the arrays [0] != ['*'] returned false
@andrewbess yep.
Just fix PHP comments because PHP 7- return false

2021-09-28 17:58 UTC, xmav commented
@magento run all tests

2021-09-29 12:05 UTC, anzin commented
@magento run all tests

2021-09-30 13:02 UTC, andrewbess commented
@magento run all tests with env PHP 8.0

2021-09-30 13:02 UTC, andrewbess commented
@magento run all tests

2021-10-01 00:41 UTC, merged