php8 compatibility/fix integration test Magento_Swatches module
magento/magento2 pull request #34153
Opened 2021-09-24 08:20 UTC by SilinMykola

### Description (*)
Fix integration test `Magento/Swatches/Controller/Adminhtml/Product/AttributeTest.php `

### Related Issues
1. magento/magento2#34020

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-24 08:22 UTC, andrewbess commented
@magento run all tests

2021-09-24 20:59 UTC, Den4ik requested changes
Please look at review comment

2021-09-24 20:59 UTC, Den4ik commented on app/code/Magento/Swatches/Model/Plugin/EavAttribute.php
> +                    );
I believe it should be `LocalizedException`

2021-09-27 14:04 UTC, SilinMykola commented
@magento run all tests

2021-09-29 14:19 UTC, andrewbess commented
@magento run all tests

2021-09-29 14:19 UTC, andrewbess commented
@magento run all tests with env PHP 8.0

2021-09-29 16:54 UTC, merged