add additional logic to check ICU version.
magento/magento2 pull request #34156
Opened 2021-09-24 15:04 UTC by Bashev

### Description (*)
With this pull request add additional check for minimum version of INTL_ICU to verify compatibility with all currencies. 

### Related Pull Requests

### Fixed Issues (if relevant)

Fixes #33798
Fixes #33856
Fixes #33910
Fixes #34139

### Manual testing scenarios (*)

1. Go to random product page. 
2. See prices. 
3. If prices is greater than 0.00 and have currency, test passed.

### Questions or comments

To verify is this issue exists on your environment, check version of your ICU. If version is below 60. you may see zero prices on catalog and product pages. Issue exists on the environment. (@ihor-sviziev describes issue and steps to reproduce and verify it in #33966 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-24 15:06 UTC, ihor-sviziev commented
@magento run all tests

2021-09-24 15:12 UTC, ihor-sviziev commented
@Bashev would love to check where the issue reproducing, I was able to test the only on 50.2 and 65.1.
That was my guess, that issue not reproducing after version 60. Would love to see some confirmation + test results on different ICU lib versions

2021-09-24 15:15 UTC, Bashev commented
@magento run all tests

2021-09-24 19:27 UTC, Bashev commented
@magento run all tests

2021-09-24 21:10 UTC, Bashev commented
@magento run Unit Tests

2021-09-24 22:30 UTC, Bashev commented
@magento run Unit Tests

2021-09-24 23:42 UTC, Bashev commented
@magento run Adobe CLA Signed? WebAPI Tests Static Tests

2021-09-24 23:43 UTC, Bashev commented
@magento run Static Tests

2021-09-25 05:46 UTC, Bashev commented
@magento run all tests

2021-09-25 08:17 UTC, Bashev commented
@magento run Static Tests

2021-09-25 08:59 UTC, Bashev commented
@magento run Unit Tests, Integration Tests

2021-09-25 11:03 UTC, Bashev commented
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Database Compare

2021-09-25 16:23 UTC, Bashev commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, WebAPI Tests

2021-09-25 19:15 UTC, Bashev commented
@magento run Functional Tests EE, Semantic Version Checker

2021-09-27 06:13 UTC, ihor-sviziev requested changes

2021-09-27 06:13 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    const MIN_INTL_ICU_VERSION = '60.0';
```suggestion
    private const MIN_INTL_ICU_VERSION = '60.0';
```

2021-09-27 06:13 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    public function getCode(): ?string
Please revert
```suggestion
    public function getCode()
```

2021-09-27 06:13 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    public function getCurrencyCode(): ?string
```suggestion
    public function getCurrencyCode()
```

2021-09-27 06:13 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    private function formatCurrency(float $price, array $options): string
Please revert
```suggestion
    private function formatCurrency(string $price, array $options): string
```

2021-09-27 06:13 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +     * @param float $price
```suggestion
     * @param string $price
```

2021-09-27 06:13 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    public function saveRates(array $rates): Currency
```suggestion
    public function saveRates($rates)
```

2021-09-27 06:19 UTC, Bashev commented
@magento run all tests

2021-09-27 06:29 UTC, ihor-sviziev requested changes

2021-09-27 06:29 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    public function getOutputFormat(): string
```suggestion
    public function getOutputFormat()
```

2021-09-27 06:29 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    public function getOutputFormat(): string
```suggestion
    public function getOutputFormat()
```

2021-09-27 06:29 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency.php
> +    public function getCurrencySymbol(): string
```suggestion
    public function getCurrencySymbol()
```

2021-09-27 07:01 UTC, ihor-sviziev commented
@magento run all tests

2021-09-27 11:52 UTC, Bashev commented
@magento run all tests

2021-09-27 13:53 UTC, Bashev commented
@magento run Functional Tests CE, Functional Tests B2B

2021-09-28 09:52 UTC, Bashev commented
@magento run Functional Tests CE, Functional Tests EE

2021-09-28 12:00 UTC, Bashev commented
@magento run Functional Tests EE

2021-09-29 08:16 UTC, ihor-sviziev commented
@Bashev, your changes look good, but still, did you do some tests on the different ICU lib versions? Could you share some results?

2021-09-29 09:19 UTC, Bashev commented
My test script running from magento home dir.

```
cat - <<'EOF' | php
<?php
require __DIR__ . '/app/bootstrap.php';

class TestMyClass extends \Magento\Framework\App\Http implements \Magento\Framework\AppInterface
{
    public function launch()
    {
        echo 'ICU Version: ' . INTL_ICU_VERSION . PHP_EOL;
        $formatter = new \NumberFormatter('bg_BG', \NumberFormatter::CURRENCY);
        $formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');

        /** @var \Magento\Directory\Model\Currency $currency */
        $currency = $this->_objectManager->create(\Magento\Directory\Model\Currency::class);
        echo 'Result with NumberFormatter (expected without currency symbol): ' . $formatter->formatCurrency(15.70, 'BGN') . PHP_EOL;
        echo 'Result with this PR: ' . $currency->formatTxt(15.70) . PHP_EOL;
        return $this->_response;
    }
}

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
/** @var \Magento\Framework\App\Http $app */
$app = $bootstrap->createApplication('TestMyClass');
$bootstrap->run($app);
?>
EOF
```
1. ICU Version: 65.1
✔ Result with NumberFormatter (expected without currency symbol): 15,70 
✔ Result with this PR: 15,70 лв.

2. ICU Version: 50.2
❌ Result with NumberFormatter (expected without currency symbol): 15,70 лв.
✔ Result with this PR: 15,70 лв.

3. ICU Version: 60.3
✔ Result with NumberFormatter (expected without currency symbol): 15,70 
✔ Result with this PR: 15,70 лв.

2021-09-29 09:25 UTC, Bashev commented
Same with `fa_IR`.

```
cat - <<'EOF' | php
<?php
require __DIR__ . '/app/bootstrap.php';

class TestMyClass extends \Magento\Framework\App\Http implements \Magento\Framework\AppInterface
{
    public function launch()
    {
        echo 'ICU Version: ' . INTL_ICU_VERSION . PHP_EOL;
        $formatter = new \NumberFormatter('fa_IR', \NumberFormatter::CURRENCY);
        $formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');

        /** @var \Magento\Directory\Model\Currency $currency */
        $currency = $this->_objectManager->create(\Magento\Directory\Model\Currency::class);
        echo 'Result without PR: ' . $formatter->formatCurrency(15.70, 'BGN') . PHP_EOL;
        echo 'Result with this PR: ' . $currency->formatTxt(15.70) . PHP_EOL;
        return $this->_response;
    }
}

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
/** @var \Magento\Framework\App\Http $app */
$app = $bootstrap->createApplication('TestMyClass');
$bootstrap->run($app);
?>
EOF
```

1. ICU Version: 50.2
❌ Result with NumberFormatter (expected without currency symbol): ‎BGN۱۵٫۷۰
✔ Result with this PR: 15,70 лв.

2. ICU Version: 60.3
✔ Result with NumberFormatter (expected without currency symbol): ‎۱۶
✔ Result with this PR: 15,70 лв.

3. ICU Version: 65.1
✔ Result with NumberFormatter (expected without currency symbol): ‎۱۵٫۷۰
✔ Result with this PR: 15,70 лв.

2021-09-29 09:56 UTC, ihor-sviziev approved these changes

2021-09-29 09:57 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9235](https://jira.corp.magento.com/browse/ENGCOM-9235) has been created to process this Pull Request

2021-09-29 23:31 UTC, dhorytskyi commented
@Bashev Unfortunately, the issue is not fully fixed in all ICU 60+. I checked it with different ICU versions using this script:
```
foreach (['en_US', 'de_DE', 'ar_AE'] as $locale) {
    $formatter = new \NumberFormatter($locale, NumberFormatter::CURRENCY);
    $formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
    foreach (['USD', 'EUR', 'AED'] as $currency) {
        echo 'Locale: ' . $locale . ' Currency: ' . $currency . ' ' . $formatter->formatCurrency(9.9, $currency) . PHP_EOL;
    }
}
```

ICU Version <=55
```
Locale: en_US Currency: USD $9.90
Locale: en_US Currency: EUR €9.90
Locale: en_US Currency: AED AED9.90
Locale: de_DE Currency: USD 9,90 $
Locale: de_DE Currency: EUR 9,90 €
Locale: de_DE Currency: AED 9,90 AED
Locale: ar_AE Currency: USD US$ ٩٫٩٠
Locale: ar_AE Currency: EUR € ٩٫٩٠
Locale: ar_AE Currency: AED د.إ.‏ ٩٫٩٠
```

ICU Version >=57 <=66
```
Locale: en_US Currency: USD 9.90
Locale: en_US Currency: EUR 9.90
Locale: en_US Currency: AED 9.90
Locale: de_DE Currency: USD 9,90 
Locale: de_DE Currency: EUR 9,90 
Locale: de_DE Currency: AED 9,90 
Locale: ar_AE Currency: USD ٩٫٩٠ 
Locale: ar_AE Currency: EUR ٩٫٩٠ 
Locale: ar_AE Currency: AED ٩٫٩٠ 
```

ICU Version >=67 <=69 (the latest)
```
Locale: en_US Currency: USD 9.90
Locale: en_US Currency: EUR €9.90
Locale: en_US Currency: AED AED 9.90
Locale: de_DE Currency: USD 9,90 $
Locale: de_DE Currency: EUR 9,90 
Locale: de_DE Currency: AED 9,90 AED
Locale: ar_AE Currency: USD ٩٫٩٠ US$
Locale: ar_AE Currency: EUR ٩٫٩٠ €
Locale: ar_AE Currency: AED ٩٫٩٠ 
```

Starting from ICU version 67 the issue is present again when currency code is used different from the default for the specified locale.

2021-09-29 23:47 UTC, dhorytskyi commented
Due to the instability of the ICU library when the currency symbol is unset, I think it's better to apply approach from the previous PR, but put it in formatTxt function and use it when formatTxt is called with display = \Magento\Framework\Currency::NO_SYMBOL.

https://github.com/magento/magento2/pull/33966/files#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R499-R501

2021-09-30 04:01 UTC, Bashev commented
I'll try to add logic in canUseNumberFofmatter method based on output of function instead of version check.

I presume if result have no currency symbol in the result, this is enough to know, we can use NumberFormatter

2021-09-30 07:57 UTC, ihor-sviziev commented
@dhorytskyi @Bashev ,
The issue with that solution that replace doesn't work fine in the case of fa_IR locale and USD currency:
```
cat - <<'EOF' | php
<?php

try {
    $reflector = new \ReflectionExtension('intl');
    ob_start();
    $reflector->info();
    $output = strip_tags(ob_get_clean());
    preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);
    $icuVersion = trim($matches[1]);
} catch (\ReflectionException $e) {
    $icuVersion = null;
}
echo 'ICU Version: ' . $icuVersion . PHP_EOL;


$formatter = new NumberFormatter('fa_IR', NumberFormatter::CURRENCY);
echo 'Original pattern: ' . $formatter->getPattern() . PHP_EOL;
echo 'Original result: ' . $formatter->formatCurrency(0, "USD") . PHP_EOL;

$formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
echo 'Pattern with replaced currency symbol: ' . $formatter->getPattern() . PHP_EOL;
echo 'Result with changed currency symbol: ' . $formatter->formatCurrency(0, "USD") . PHP_EOL;

$formatter->setPattern( str_replace('¤','', $formatter->getPattern() ) );
echo 'Pattern with pattern: ' . $formatter->getPattern() . PHP_EOL;
echo 'Result with the changed pattern: ' . $formatter->formatCurrency(0, "USD") . PHP_EOL;

EOF
```

![image](https://user-images.githubusercontent.com/1873745/135411226-ece332a1-525e-4170-9d42-540daeafa5f2.png)

I thought about getting the "Zero" symbol and try to replace it with the `%s` as well but looks like we don't have access to the number formatter object in that context.
Any thoughts?

2021-09-30 21:24 UTC, Bashev commented
Tested with ICU
- 50.2
- 65.1
- 69.1

btw, 2.4.3 with 69.1 works properly without fix. I presume this is because used currency is default as @dhorytskyi explain above.

2021-09-30 21:24 UTC, Bashev commented
@magento run all tests

2021-09-30 22:38 UTC, Bashev commented
@magento run all tests

2021-10-01 22:27 UTC, Den4ik commented
@magento run all tests

2021-10-02 14:34 UTC, Bashev commented
@magento run all tests

2021-10-02 16:17 UTC, Bashev commented
@magento run all tests

2021-10-02 18:29 UTC, Bashev commented
@magento run all tests

2021-10-02 20:26 UTC, Bashev commented
@magento run Integration Tests

2021-10-02 22:09 UTC, Bashev commented
@magento run all tests

2021-10-04 04:41 UTC, engcom-Alfa commented
@magento give me 2.4-develop instance

2021-10-06 11:31 UTC, engcom-Alfa commented
Hi @Bashev and @ihor-sviziev 
Thanks for your contribution and collaboration!

I have gone through the PR and all relevant issues linked to it, tried to reproduce functionally in multiple ways and it is not getting reproduced in Magento 2.4-develop.

If we go through the comments of this [Issue](https://github.com/magento/magento2/issues/33910), it clears that the problem behind the issue is because of ICU version that is with <60 version. So the issue reproducible in AWS EC2 instance only.
Hence I will not be able to reproduce in my system.
Kindly let me know if there is any way to do as such!

cc: @sdzhepa

2021-10-06 11:39 UTC, Bashev commented
@engcom-Alfa same behavior is available on versions > 66.1 described in this comment by @dhorytskyi https://github.com/magento/magento2/pull/34156#issuecomment-930620874

2021-10-06 13:19 UTC, engcom-Alfa commented
> @engcom-Alfa same behavior is available on versions > 66.1 described in this comment by @dhorytskyi [#34156 (comment)](https://github.com/magento/magento2/pull/34156#issuecomment-930620874)

Yes Correct! But here the _php 7.4.24_ (the latest version of php) also using ICU version 66 only!
_Php 8_ is using _ICU 68_ version and that is not supported by _Magento2_! According to me the configurations will become incompatible.
Well, still trying an alternative to reproduce the issue!

2021-10-06 13:30 UTC, engcom-Alfa commented
@magento give me test instance

2021-10-06 13:32 UTC, ihor-sviziev commented
Hi @adifucan,
We, together with @Bashev, are working on the fix for the changes you were committing as part of the [MCP-288](https://github.com/magento/magento2/commit/c640062d97c47966e0b027f42a86774d62c4a42c).
We tried to contact you on Slack but didn't get any response from you.

More details:
https://github.com/magento/magento2/pull/33966
https://github.com/magento/magento2/pull/34156

Now we think that 2nd option is better, but I'm not sure about the performance of this change

Could you review it and give your feedback? Thank you!

2021-10-06 13:39 UTC, ihor-sviziev commented
@engcom-Alfa,
as we said before, it's not related to the PHP version, but to the ICU library. It might be PHP 7.4 with ICU library 50.2 or 68.0. That depends on the OS requirements and the way how you're installing PHP (probably if you're installing from source - you'll  get the latest available version)

2021-10-07 05:17 UTC, adifucan commented
Hi @ihor-sviziev @Bashev! The current approach in this PR where **Intl::NumberFormatter** is NOT used if there is a currency symbol or currency code leads to performance degradation because **Zend_Currency** is used instead. 
I believe it fixes the issue but it brings back degradation because in ~90% of cases **Zend_Currency** will be used because in most cases we do have currency symbol or code. I'll get back with numbers of performance measurements later but I see that Performance-Acceptance-Tests build is already red.

@dhorytskyi Am I correct that from ICU v.57 till ICU v.66 the issue can be fixed as the behaviour of the library is more predictable? If so, why can't we check for ICU version in **\Magento\Directory\Model\Currency::canUseNumberFormatter** like @Bashev proposed initially?
```
if (INTL_ICU_VERSION < 57 || INTL_ICU_VERSION > 66) {
    return false;
}
```

2021-10-14 19:17 UTC, Bashev commented
closed fixed in https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde
@ihor-sviziev thx for support

2021-10-14 19:17 UTC, closed without merging