[WIP] Php8 compatibility/fix static tests to be php8 compatible
magento/magento2 pull request #34192
Opened 2021-09-29 12:24 UTC by karyna-tsymbal-atwix

### Description (*)
Stabilisation of Static Tests to be compatible both with PHP7 and PHP8.

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes magento/magento2#34188

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-30 07:52 UTC, karyna-tsymbal-atwix commented on dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Framework/Api/ExtensibleInterfacesTest.php
> +                preg_match('/\[\s\<\w+?>\s([?]?[\w]+)/s', $methodParameters[0]->__toString(), $matches);
**PHP 8**
Parameter #0 [ <required> ?Magento\MediaGalleryApi\Api\Data\KeywordExtensionInterface $extensionAttributes ]

**PHP 7**
Parameter #0 [ <required> Magento\MediaGalleryApi\Api\Data\KeywordExtensionInterface or NULL $extensionAttributes ]

2021-09-30 11:36 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests with env PHP 8.0

2021-09-30 11:38 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests

2021-09-30 12:54 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests

2021-09-30 13:02 UTC, andrewbess commented
@magento run Static Tests with env PHP 8.0

2021-09-30 18:20 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests

2021-10-01 06:34 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests

2021-10-01 07:17 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests

2021-10-01 07:18 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests with env PHP 8.0

2021-10-01 10:57 UTC, andrewbess commented
@magento run all tests with env PHP 8.0

2021-10-01 10:57 UTC, andrewbess commented
@magento run all tests

2021-10-02 07:52 UTC, xmav requested changes

2021-10-02 07:52 UTC, xmav commented on dev/tests/static/testsuite/Magento/Test/Integrity/Di/CompilerTest.php
> +                // phpcs:ignore Magento2.Performance.ForeachArrayMerge
Could you please try to rewrite it using example from - https://github.com/magento/magento-coding-standard/issues/20

2021-10-02 07:52 UTC, xmav commented on dev/tests/static/testsuite/Magento/Test/Integrity/Di/CompilerTest.php
> +                // phpcs:ignore Magento2.Performance.ForeachArrayMerge
Could you please try to rewrite it using example from - https://github.com/magento/magento-coding-standard/issues/20

2021-10-02 07:52 UTC, xmav commented on dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Framework/Api/ExtensibleInterfacesTest.php
> +                preg_match('/\[\s\<\w+?>\s([?]?[\w]+)/s', $methodParameters[0]->__toString(), $matches);
Could you please revise this check to be sure it works as expected ? With this regex `/\[\s\<\w+?>\s([?]?[\w]+)/s` we will have just first part of FQCN in $matches[1]. that mean that any parameter type will be considered correct as \Magento != \Mageno\Module\Api\Data\SomeExtensionInterface

2021-10-04 13:38 UTC, karyna-tsymbal-atwix commented
@magento run Static Tests with env PHP 8.0

2021-10-04 15:25 UTC, xmav approved these changes

2021-10-04 15:38 UTC, merged