[WIP] Fix reflection isBuiltin() method for PHP8 compatibility
magento/magento2 pull request #34206
Opened 2021-09-30 12:18 UTC by karyna-tsymbal-atwix

### Description (*)
Fix for the issue with `ReflectionType::isBuiltin()` method for all occurrences in the CE repository

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes magento/magento2#34194: Check and update codebase to avoid fatal error for ReflectionType::isBuiltin()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-30 12:25 UTC, karyna-tsymbal-atwix commented
@magento run all tests

2021-10-01 06:46 UTC, karyna-tsymbal-atwix commented
@magento run all tests with env PHP 8.0

2021-10-04 19:21 UTC, xmav requested changes

2021-10-04 19:21 UTC, xmav commented on lib/internal/Magento/Framework/GetParameterClassTrait.php
> +        if ($parameterType !== null && method_exists($parameterType, 'isBuiltin') === false) {
We need more testing here. While magento code will continue to use PHP7.4 syntax we should be able to work with code which is PHP8 specific. In future someone may develop extension with PHP8 as minimal version(and PHP8 syntax in it). Magento should properly work with such extensions.
Please explore dev/tests/integration/testsuite/Magento/Framework/ObjectManager to see if we can add tests that will be executed only with PHP8. Would be great to see that magento can properly work with code with union types (i.e generate code, instantiate objects etc)

2021-10-06 23:39 UTC, xmav commented
Please resolve conflicts. This PR could be  delivered (with green tests) as step for a future work
Lets address my last comment as part of future work in https://github.com/magento/magento2/issues/34263

2021-10-11 11:25 UTC, karyna-t commented
@magento run all tests

2021-10-11 11:26 UTC, karyna-t commented
@magento run all tests with env PHP 8.0

2021-10-12 06:33 UTC, karyna-t commented
@magento run all tests

2021-10-12 06:33 UTC, karyna-tsymbal-atwix commented
@magento run all tests with env PHP 8.0

2021-10-12 10:52 UTC, karyna-t commented
@magento run Unit tests

2021-10-12 13:55 UTC, xmav approved these changes

2021-10-12 13:55 UTC, andrewbess approved these changes

2021-10-12 13:58 UTC, merged

2022-10-27 14:35 UTC, Vormillion commented
@karyna-tsymbal-atwix 
This "fix" is causing issues with running PHPMD after composer install without running di:compile. We are running quick checks on "clean" Magento before we will proceed with docker image build so running di:compile is slowing down whole CI process.