Fixed round and abs function to be compatible with php8
magento/magento2 pull request #34234
Opened 2021-10-04 09:29 UTC by anzin

### Description (*)

Fixed abs() and round() function to be compatible both with PHP7 and PHP8.

### Related Pull Requests

### Fixed Issues (if relevant)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-04 12:32 UTC, ihor-sviziev commented on app/code/Magento/CatalogInventory/Model/ResourceModel/Stock/Item.php
> +                $data['qty'] = new \Zend_Db_Expr($ifNullSql . '-' . abs((int) $object->getQtyCorrection()));
i guess it might be float in some cases

2021-10-04 12:32 UTC, ihor-sviziev commented on app/code/Magento/Dhl/Model/Carrier.php
> +                $nodePiece->addChild('Depth', (string) round((int) $params['length']));
can it be float in some cases?

2021-10-04 12:32 UTC, ihor-sviziev commented on app/code/Magento/Usps/Model/Carrier.php
> +                (int) $this->_carrierHelper->convertMeasureWeight(
i guess it should be float everywhere

2021-10-05 07:31 UTC, anzin commented
@magento run all tests

2021-10-05 15:52 UTC, anzin commented
@magento run Static Tests

2021-10-05 17:05 UTC, anzin commented
@magento run Static Tests

2021-10-05 17:59 UTC, anzin commented
@magento run all tests

2021-10-05 20:07 UTC, anzin commented
@magento run Functional Tests B2B

2021-10-07 10:46 UTC, ihor-sviziev approved these changes

2021-10-11 08:37 UTC, anzin commented
@magento run all tests

2021-10-11 11:23 UTC, eduard13 approved these changes

2021-10-11 11:26 UTC, eduard13 reviewed
@anzin could you please check the failed Static Tests?

2021-10-11 11:28 UTC, Den4ik commented on app/code/Magento/Paypal/Model/Api/AbstractApi.php
> +     * @param int    $i
Additional spaces look little bit strange for me. Do we have official recommendations for this case?

2021-10-11 11:31 UTC, Den4ik requested changes

2021-10-11 11:31 UTC, Den4ik commented on lib/internal/Magento/Framework/View/Layout/Data/Structure.php
> +            $offset = (int)abs((int) $offsetOrSibling) * ($after ? 1 : -1);
```suggestion
            $offset = abs((int) $offsetOrSibling) * ($after ? 1 : -1);
```

2021-10-11 11:56 UTC, anzin commented on lib/internal/Magento/Framework/View/Layout/Data/Structure.php
> +            $offset = (int)abs((int) $offsetOrSibling) * ($after ? 1 : -1);
Hello @Den4ik, thanks for your review I corrected the code according to your recommendations. Please check if everything well.

Thank you.

2021-10-11 11:57 UTC, anzin commented
@magento run Static Tests

2021-10-11 14:05 UTC, anzin commented
@magento run Static Tests

2021-10-11 15:02 UTC, anzin commented
@magento run Static Tests

2021-10-11 15:32 UTC, eduard13 commented on app/code/Magento/AdvancedSearch/Test/Unit/Model/ResourceModel/IndexTest.php
> +    public function testGetPriceIndexData($testData): void
```suggestion
    /**
     * @param array $testData
     * @dataProvider providerForTestPriceIndexData
     *
     * @return void
     */
    public function testGetPriceIndexData(array $testData): void
```

2021-10-11 15:32 UTC, eduard13 commented on dev/tests/integration/testsuite/Magento/CurrencySymbol/Controller/Adminhtml/System/Currency/SaveRatesTest.php
> +    public function testSaveWithNullRates()
```suggestion
    public function testSaveWithNullRates(): void
```

2021-10-11 16:27 UTC, anzin commented
@magento run Static Tests

2021-10-11 18:04 UTC, anzin commented
@magento run Static Tests

2021-10-11 18:59 UTC, anzin commented
@magento run all tests

2021-10-11 21:23 UTC, anzin commented
@magento run Functional Tests EE, Unit Tests

2021-10-12 07:46 UTC, anzin commented
@magento run Unit Tests, Static Tests

2021-10-12 09:12 UTC, anzin commented
@magento run Unit Tests, Static Tests

2021-10-12 10:19 UTC, anzin commented
@magento run all tests

2021-10-12 12:19 UTC, anzin commented
@magento run WebAPI Tests

2021-10-13 08:09 UTC, anzin commented
@magento run all tests with env PHP 8.0

2021-10-13 12:35 UTC, andrewbess approved these changes

2021-10-13 17:16 UTC, anzin commented
@magento run WebAPI Tests with env PHP 8.0

2021-10-13 23:44 UTC, xmav commented
@magento run WebAPI Tests

2021-10-14 11:20 UTC, andrewbess commented
@magento run all tests with env PHP 8.0

2021-10-14 11:20 UTC, andrewbess commented
@magento run all tests

2021-10-14 11:26 UTC, Den4ik approved these changes
Looks ok

2021-10-14 17:18 UTC, xmav commented
@magento run Functional Tests CE

2021-10-14 22:57 UTC, merged