Fix for #31870
magento/magento2 pull request #34252
Opened 2021-10-05 15:58 UTC by rmsundar1

### Description (*)

- \Magento\ConfigurableProduct\Model\Plugin\ProductRepositorySave::beforeSave before plugin not returning all the original params. This PR fixed and return all the function param as per the documentation.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31870

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-05 16:01 UTC, rmsundar1 commented
@magento give me test instance

2021-10-05 18:01 UTC, rmsundar1 commented
@magento run unit test

2021-10-05 18:02 UTC, rmsundar1 commented
@magento run all tests

2021-10-06 13:03 UTC, ihor-sviziev requested changes

2021-10-06 13:03 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +        $result = [$product, $saveOptions];
It looks like we're not expecting to change any arguments for the "save" method, so I think it's better to replace the return type with "void" and don't change the method arguments.

2021-10-06 13:06 UTC, ihor-sviziev requested changes
Could you also write some integration tests that will test that options are getting saved with the `ProductRepository::save` method after your change?

2021-10-06 14:45 UTC, rmsundar1 commented
> Could you also write some integration tests that will test that options are getting saved with the `ProductRepository::save` method after your change?

@ihor-sviziev This plugin is doing validation and not changing data in the object, so I hope you meant the unit tests here, please confirm.

2021-10-06 14:48 UTC, ihor-sviziev commented
@rmsundar1 if I got correctly - the original method save was all the time getting the false value for save options and wasn't doing so. The issue wasn't in the plug-in itself, but in the integration of plug-in and the original code. In order to prevent such issue in future - it's better to add integration test coverage for the case of saving options via repository

2021-10-07 10:43 UTC, Den4ik requested changes

2021-10-07 10:43 UTC, Den4ik commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +        $result = [$product, $saveOptions];
I'm agree with @ihor-sviziev. In fact we could remove unused params in plugin

2021-10-07 14:00 UTC, rmsundar1 commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +        $result = [$product, $saveOptions];
@Den4ik @ihor-sviziev This argument is not been used in the \Magento\Catalog\Model\ProductRepository::save function itself, should we remove that param from the interface itself?

2021-10-07 18:19 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +        $result = [$product, $saveOptions];
Ohhh. Interesting... in this case, why it's actually needed and what the issue you have?

2021-10-07 20:23 UTC, Den4ik commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +        $result = [$product, $saveOptions];
@rmsundar1 We could not remove unused parameter from repository in patch release because it's BIC. Plugin cleanup is good point for PR

2021-10-08 11:05 UTC, ihor-sviziev requested changes

2021-10-08 11:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +        ) {
```suggestion
        $extensionAttributes = $product->getExtensionAttributes();
        if (null !== $extensionAttributes && $product->getTypeId() === Configurable::TYPE_CODE) {
```

2021-10-08 11:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Test/Unit/Model/Plugin/ProductRepositorySaveTest.php
> -    public function testBeforeSaveWithLinks(): void
why was it removed?

2021-10-08 12:09 UTC, rmsundar1 commented on app/code/Magento/ConfigurableProduct/Test/Unit/Model/Plugin/ProductRepositorySaveTest.php
> -    public function testBeforeSaveWithLinks(): void
@ihor-sviziev This case is already covered in `testBeforeSaveWithLinksWithDuplicateAttributes` function. Now ConfigurableProductLinks and ConfigurableProductOptions are mandatory to perform validation and  `testBeforeSaveWithLinks ` function is not passing enough argument to validate the exact case. So I removed that

2021-10-08 13:14 UTC, rmsundar1 commented
@magento run all tests

2021-10-19 09:41 UTC, ihor-sviziev commented
@magento run all tests

2021-10-19 10:48 UTC, ihor-sviziev commented
@magento run all tests

2021-10-20 05:33 UTC, rmsundar1 commented
@ihor-sviziev I am unable to view the report in Static tests report. I could see below thing in the report page. Could you help me out

> Unfortunately there's no build reports were generated. That may be caused by either infrastructure issues or fatal errors during the build run. Please address this issue to Community Engineering Team members.

2021-10-20 07:08 UTC, ihor-sviziev commented
@magento run all tests

2021-10-20 10:55 UTC, Den4ik requested changes
Hi @rmsundar1. Thanks for work on this PR.
Could you please check comment below

2021-10-20 10:55 UTC, Den4ik commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +            if (!empty($configurableLinks) && !empty($configurableOptions)) {
Previous behaviour allow one of variables `$configurableLinks` or `$configurableOptions` could be empty. Changes disallow that. By this way some of WebAPI tests are failed. Could you please check and fix this tests.

2021-10-20 11:05 UTC, ihor-sviziev commented on app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php
> +            if (!empty($configurableLinks) && !empty($configurableOptions)) {
```suggestion
            if (!empty($configurableLinks) || !empty($configurableOptions)) {
```

2021-10-20 13:54 UTC, rmsundar1 commented
@magento run all tests

2021-10-20 19:29 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests look not related to changes from this PR.

2021-10-20 19:30 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9267](https://jira.corp.magento.com/browse/ENGCOM-9267) has been created to process this Pull Request

2021-10-21 06:01 UTC, ihor-sviziev commented
@magento run Functional Tests B2B, Functional Tests EE

2021-10-21 15:56 UTC, Den4ik approved these changes

2021-10-21 15:57 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9267](https://jira.corp.magento.com/browse/ENGCOM-9267) has been created to process this Pull Request

2021-10-27 12:36 UTC, engcom-Alfa commented
Hi @rmsundar1 , @Den4ik and @ihor-sviziev 
Thanks for your collaboration and contribution!
According to this [review discussion](https://github.com/magento/magento2/pull/34252#discussion_r723232598), the PR code just has an code improvement and it is not affecting any functional changes in the system neither fixing the [above described issue](https://github.com/magento/magento2/pull/34252#issue-1016500670).
Please confirm me if my understanding is incorrect!
Thanks in advance!

2021-10-27 15:41 UTC, Den4ik commented
Hi @engcom-Alfa 
It's not just code improvements. Issue could be faced in custom plugins that execute after `app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php` and expect to receive second param `$saveOptions`

2021-10-29 15:42 UTC, engcom-Alfa commented
> Hi @engcom-Alfa It's not just code improvements. Issue could be faced in custom plugins that execute after `app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php` and expect to receive second param `$saveOptions`

Please provide me exact steps to reproduce the issue.

2021-11-02 12:45 UTC, rmsundar1 commented
Hi @engcom-Alfa,
Create a Before plugin for [ProductRepositoryInterface](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Api/ProductRepositoryInterface.php#L26) with sortOrder value as 30 or some higher number and try to read the 2nd argument value in the execution. 

Expected result: 2nd argument $saveOptions should be available

Actual result: 2nd argument $saveOptions is getting ommitted

https://github.com/magento/magento2/issues/31870

2021-12-16 09:56 UTC, engcom-Alfa commented
Hi @rmsundar1 and @ihor-sviziev 
I have tried to reproduce it and no issue is observed. Kindly check the [steps-followed here](https://github.com/magento/magento2/issues/31870#issuecomment-995588464).
Let me know if there is any change in my execution.

2021-12-24 10:05 UTC, ihor-sviziev commented
@engcom-Alfa, any updates on testing?

2022-01-03 15:21 UTC, engcom-Alfa commented
> @engcom-Alfa, any updates on testing?

Yes as [commented above](https://github.com/magento/magento2/pull/34252#issuecomment-995613961), again placing all the details below: Please take a look and let me know how can we reproduce it.

As I have re-verified again, the $saveoptions is not getting omitted!
Please refer below steps that I have followed, and kindly let me know if anything needs to be added/changed.

**Using existing model:**

1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40 as shown in below screenshot
<img width="1440" alt="Screenshot 2021-12-16 at 2 35 39 PM" src="https://user-images.githubusercontent.com/51679138/146342268-de8f4333-ed36-466e-b754-c4d59da8b067.png">

2. Placed the var_dump line of code in the configurableProduct>Model>Plugin>ProductRepositorySave.php file as shown in below screenshot.
<img width="1440" alt="Screenshot 2021-12-16 at 2 35 52 PM" src="https://user-images.githubusercontent.com/51679138/146342552-a8d2576b-9f26-43b8-aa13-4157d481ce4e.png">

3. Placed the var_dump line of code in Catalog>Model>ProductRepository.php file as shown in below screenshot.
<img width="1440" alt="Screenshot 2021-12-16 at 2 36 05 PM" src="https://user-images.githubusercontent.com/51679138/146342881-38addc56-b503-4012-b68c-63a80396f7d8.png">

4. Tried to add the configurable product through API request and found the $saveoptions has a value
 set to bool(false) as shown in the below screenshot.
<img width="1440" alt="Screenshot 2021-12-16 at 2 35 17 PM" src="https://user-images.githubusercontent.com/51679138/146343086-df019070-df81-42ef-8cd2-bba065de42d8.png">



**Using new custom plugin:**
5. Instead of that, created new plugin as shown in below 2 screenshots.
<img width="1440" alt="Screenshot 2021-12-16 at 2 37 00 PM" src="https://user-images.githubusercontent.com/51679138/146343810-483fb1d5-9986-4113-bd67-8d7ede705149.png">

<img width="1440" alt="Screenshot 2021-12-16 at 2 38 30 PM" src="https://user-images.githubusercontent.com/51679138/146343859-810f6d08-9932-4c87-888a-c13fc08ae96a.png">

Still I am getting the same output as mentioned in the step 4 screenshot @rmsundar1

2022-01-04 03:27 UTC, rmsundar1 commented
@engcom-Alfa  Can you try passing `true` as second argument values, in your case looks like the default value(i.e., `false`) of the second argument is been used.

2022-01-07 13:24 UTC, engcom-Alfa commented
> @engcom-Alfa Can you try passing `true` as second argument values, in your case looks like the default value(i.e., `false`) of the second argument is been used.

Hi @rmsundar1 thanks for your reply! I have retried with the below steps:

1. Placed the $save_options = true and var_dump lines of code in the _configurableProduct>Model>Plugin>ProductRepositorySave.php_ file as shown in below screenshot.
![image](https://user-images.githubusercontent.com/51679138/148547374-bda231ed-104d-4c97-9620-74955289bd02.png)

2. Placed the echo var_dump lines of code in the _configurableProduct>Model>Plugin>ProductRepositorySave.php_ file as shown in below screenshot.
![image](https://user-images.githubusercontent.com/51679138/148547534-d6407af3-30c8-42cb-b1b6-618d4464416e.png)

3. Executed the Create Configurable product API request and noticed the below output as shown in screenshot
![image](https://user-images.githubusercontent.com/51679138/148547851-98889e7b-af47-42c3-b6e3-8d5a0d4b8159.png)

As you suggested to pass _true_ as second argument values, I have just considered in the way mentioned in step 1 above. Kindly let me know if you meant something different please ?
If we see the third step output screenshot, we are seeing _false_ output from _ProductRepositorySave.php:save_ method. is that the issue we are trying to solve in this PR? Should it return _true_ after the PR changes?

2022-01-10 06:19 UTC, rmsundar1 commented
> If we see the third step output screenshot, we are seeing false output from ProductRepositorySave.php:save method. is that the issue we are trying to solve in this PR? Should it return true after the PR changes?

@engcom-Alfa Yes correct.

2022-01-10 13:53 UTC, engcom-Alfa commented
Hi @rmsundar1, @Den4ik and @ihor-sviziev 
Thanks for the collaboration & contribution!

:x: QA not Passed

_ProductRepository::save method is loosing second argument value_

**Manual Scenario Steps**
As mentioned in above [comment1](https://github.com/magento/magento2/pull/34252#issuecomment-1004164935) and [comment2](https://github.com/magento/magento2/pull/34252#issuecomment-1007404615) followed same steps (we can refer same above screenshots too)
1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40
2. Placed the $save_options = true and var_dump lines of code in the configurableProduct>Model>Plugin>ProductRepositorySave.php file
3. Placed the var_dump line of code in Catalog>Model>ProductRepository.php file
4. Tried to add the configurable product through API request


**:heavy_check_mark: Expected result After Fix** 
- Expected API response return values like:
`Inside before save -bool(true)
Inside save method--bool(true)`


**:x: Actual result After Fix** 
- API response has the return values like:
`Inside before save -bool(true)
Inside save method--bool(false)`

2022-01-10 13:54 UTC, engcom-Alfa requested changes
Based on the above-comment requesting to cross check again please!

2022-10-18 13:01 UTC, ihor-sviziev commented
@engcom-Alfa, your testing results don't look logical to me. It looks like some other plugin might cause a similar issue. Did you test it based on Magento Open Source?

2022-10-20 17:38 UTC, ishakhsuvarov commented
Moving to `Extended Testing` to get tested again.

2022-11-10 07:44 UTC, engcom-Charlie commented
@engcom-Lima, as per [this](https://github.com/magento/magento2/pull/34252#issuecomment-1285918262) comment, please have a look at this.

2022-11-28 09:26 UTC, engcom-Echo commented
Hi @rmsundar1, @Den4ik and @ihor-sviziev 
Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

_ProductRepository::save method is loosing second argument value_

**Manual Scenario Steps**
1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40
2. Passed save_options = true and var_dump() in Catalog>Model>ProductRepository.php
4. Tried to add the configurable product through API request


**:heavy_check_mark: Expected result After Fix** 
- Expected API response return values like:
`Inside before save -bool(true)
Inside save method--bool(true)`


**:heavy_check_mark: Actual result After Fix** 
- API response has the return values like:
`Inside before save -bool(true)
Inside save method--bool(false)`

2022-11-28 09:34 UTC, engcom-Echo commented
Hi @rmsundar1, @Den4ik and @ihor-sviziev 
Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

_ProductRepository::save method is loosing second argument value_

**Manual Scenario Steps**
1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40
2. Passed save_options = true and var_dump() in Catalog>Model>ProductRepository.php
![image](https://user-images.githubusercontent.com/51681435/204242392-9f8242b5-814a-4371-a9bf-c0897ac21735.png)

3. Tried to add the configurable product through API request
![image](https://user-images.githubusercontent.com/51681435/204242635-3cb25a17-6a77-48e1-9eee-32c2e69f743d.png)


**Before:** :heavy_multiplication_x: 
![image](https://user-images.githubusercontent.com/51681435/204243040-4e35356e-3f81-4e78-84c8-8ecb9c9bfda0.png)



**After:** :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/51681435/204241983-2cbd9463-d025-437d-bf08-17c4a02af10e.png)

2022-11-29 04:14 UTC, engcom-Echo commented
@magento run all tests

2022-11-29 06:36 UTC, engcom-Echo commented
@magento run WebAPI Tests,Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

2022-12-03 20:20 UTC, merged