Use tmp folder from Magento installation to prevent path collisions
magento/magento2 pull request #34272
Opened 2021-10-07 11:19 UTC by alinalexandru

### Description (*)

Use `tmp` folder relative to magento installation, instead of using the system tmp.
`SYS_TMP` is defined `\Magento\Framework\Filesystem\DirectoryList`, but  `\Magento\Framework\App\Filesystem\DirectoryList` is used in `\Magento\Analytics\Model\ExportDataHandler`, so it means we can us `TMP` constant.
In this way, every magento2 installation will not interfere with each other.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29373

### Manual testing scenarios (*)

I see 2 ways to do manual test, as cron cleans everything during execution
1. Follow the steps from https://github.com/magento/magento2/issues/29373#issuecomment-885023346
2. Comment the `finaly` block from `\Magento\Analytics\Model\ExportDataHandler`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-07 11:23 UTC, alinalexandru commented
@magento run all tests

2021-10-07 12:52 UTC, ihor-sviziev commented
@magento run all tests

2021-10-07 15:14 UTC, alinalexandru commented
@magento run all tests

2021-10-07 18:17 UTC, ihor-sviziev requested changes
Please fix failing static tests

2021-10-07 18:45 UTC, alinalexandru commented
@magento run Static Tests

2021-10-07 19:29 UTC, alinalexandru commented
@ihor-sviziev Fixed

2021-10-07 20:15 UTC, ihor-sviziev commented
@magento run all tests

2021-10-07 21:15 UTC, Den4ik requested changes
Hi @alinalexandru 
Thanks for PR. Please look at my comment

2021-10-07 21:15 UTC, Den4ik commented on app/code/Magento/Analytics/Model/ExportDataHandler.php
> +            if (isset($tmpDirectory) && $tmpDirectory instanceof WriteInterface) {
`$tmpDirecory` always will be `WriteInterface` and check `$tmpDirectory instanceof WriteInterface` is unnecessary

2021-10-08 09:27 UTC, alinalexandru commented
@Den4ik Fixed it

2021-10-08 09:58 UTC, alinalexandru commented
@magento run all tests

2021-10-08 13:29 UTC, ihor-sviziev approved these changes

2021-10-08 13:30 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9245](https://jira.corp.magento.com/browse/ENGCOM-9245) has been created to process this Pull Request

2021-10-10 17:54 UTC, Den4ik approved these changes
✅ Looks good for me. All tests passed

2021-10-10 17:55 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9245](https://jira.corp.magento.com/browse/ENGCOM-9245) has been created to process this Pull Request

2021-11-03 21:33 UTC, sidolov commented
@magento convert to patch for 2.4.3

2021-11-03 21:35 UTC, sidolov commented
@magento convert to patch for 2.4.3

2021-11-03 22:11 UTC, sidolov commented
@magento convert to patch for 2.4.3

2021-11-03 22:11 UTC, m2-github-services commented
@sidolov changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-2.4.3

2021-11-03 22:12 UTC, m2-github-services commented
@sidolov changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-2.4.3

2021-11-10 19:14 UTC, slavvka commented
@magento run all tests

2021-11-12 14:00 UTC, Den4ik commented
@magento run Functional Tests EE

2022-05-13 10:25 UTC, engcom-Lima commented
Hi @alinalexandru , @Den4ik , @ihor-sviziev Thanks for your contribution and collaboration .
Tried reproducing the issue in 2.4-develop version before testing the given PR fix code referring PR description/ comments.
Issue is not reproducible and below is the information on this:

**Pre Conditions**
1. Installed two magento instances with 2.4-develop version in my local with sample data.
2. Used PHP 7.4.29 version in my ubuntu system.

**Reproducible steps**
1. Followed the given steps in first magento instance [ issue comment](https://github.com/magento/magento2/issues/29373#issuecomment-885023346)
2. Repeated same steps in 2nd Magento instance as well.
3. Commented the `finally` block from `\Magento\Analytics\Model\ExportDataHandler` in both the instances.
4. Cross checked the given path `/tmp/analytics/tmp/` in the local system .

**Observation** - Analytics folder was not found in the given path `/tmp/analytics/tmp/`

**Kindly let me know based on what factors files will get generated in given path, So, that we can proceed further in our testing.**

2022-06-03 11:26 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Should use the local system in which we should have all Magento instance relevant installed.
2. We should have 2 Magento latest versioned instances in the same system to test.


**Manual testing scenario:**

1. There are code changes done in 2 of the php files [commented here](https://github.com/magento/magento2/issues/29373#issuecomment-885023346), we should do the same code changes in both the instances of our Magento local code.
2. Download the `n98-magerun2-latest.phar` file from [here](https://files.magerun.net/).
3. Rename the file `n98-magerun2-latest.phar` to `n98-magerun2.phar`.
4. Copy the downloaded file inside both the local Magento instances' root folder.
5. Run the command `php -d upload_tmp_dir=/tmp n98-magerun2.phar sys:cron:run analytics_collect_data` from the Magento root folder of both instances one by one.

**Before:** :heavy_multiplication_x: The responded command used to return the folder path from both the instances which is a common local system TEMP folder.
<img width="762" alt="image" src="https://user-images.githubusercontent.com/51679138/171844896-4e849860-4c5a-45b4-b7ac-0478296c6de9.png">


**After:** :heavy_check_mark: The responded command returns the folder path from both the instances which is q unique var/ folder of each Magento instance only.
![image](https://user-images.githubusercontent.com/51679138/171844939-9b8f7496-eb75-4142-9ae3-145cde95771c.png)


Since it is a specific case where the reporting folder has been changed, and so no additional regression test case are required for this case.
Note: I think, it is good to have the Magento doc to be updated with this information, even i couldn't find any info relevant to it as of now.

2022-06-11 14:22 UTC, merged