this always overrid function param
magento/magento2 pull request #34283
Opened 2021-10-08 12:11 UTC by taoufiqaitali

### Description (*)

this always overrid function param
code should not be commented
### Related Pull Requests

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-10 18:01 UTC, Den4ik requested changes

2021-10-10 18:01 UTC, Den4ik commented on app/code/Magento/CatalogInventory/Model/StockManagement.php
> +        }
@taoufiqaitali Thanks for PR. Could you check why this changes was implemented?
`MAGETWO-48153: Cannot save product with assignment to more than one website`

2021-10-28 16:32 UTC, sidolov commented
@taoufiqaitali could you please provide a scenario which is affected by current issue? Thanks!

2021-11-04 16:22 UTC, sdzhepa commented
@taoufiqaitali could you please provide a scenario which is affected by current issue? Thanks!

2021-11-18 17:27 UTC, sidolov commented
@taoufiqaitali , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

2021-11-18 17:27 UTC, closed without merging