Fixed different ways use of $useConfig on category save
magento/magento2 pull request #34357
Opened 2021-10-16 02:49 UTC by Den4ik

### Description (*)

Category save use `$useConfig` config checkboxes for some attributes. We have 2 ways of creating category:
1. Catalog->Category
2. Catalog->Products->Create/Edit Product->New Category

Catalog->Category page use attribute codes as input name
Catalog->Products->Create/Edit Product->New Category use attribute codes as values.
As result it's not work correctly in `\Magento\Catalog\Model\Category\Attribute\Backend\Sortby::validate`

This PR partially rollback changes made in https://github.com/magento/magento2/pull/34343

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Save category from Catalog->Categories
2. Debug `\Magento\Catalog\Model\Category\Attribute\Backend\Sortby::validate` and verify that `$postDataConfig` is array of attribute codes
3. Save category from product edit page
4. Debug `\Magento\Catalog\Model\Category\Attribute\Backend\Sortby::validate` and verify that `$postDataConfig` is array of attribute codes

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-16 02:51 UTC, Den4ik commented
@magento run all tests with env PHP 8.0

2021-10-16 18:30 UTC, eduard13 requested changes

2021-10-16 18:30 UTC, eduard13 commented on app/code/Magento/Catalog/Ui/DataProvider/Product/Form/NewCategoryDataProvider.php
> +    public function getData(): array
Please revert this, as its a BIC change.

2021-10-16 18:30 UTC, eduard13 commented on app/code/Magento/Catalog/Ui/DataProvider/Product/Form/NewCategoryDataProvider.php
> +    public function getMeta(): array
Same here

2021-10-16 19:50 UTC, andrewbess requested changes

2021-10-16 19:50 UTC, andrewbess commented on app/code/Magento/Catalog/Ui/DataProvider/Product/Form/NewCategoryDataProvider.php
> +    public function getData(): array
Hello @Den4ik 
Thank you for your job.
Could you please revert return type because this is BIC
Thank you in advance.

2021-10-16 19:50 UTC, andrewbess commented on app/code/Magento/Catalog/Ui/DataProvider/Product/Form/NewCategoryDataProvider.php
> +    public function getMeta(): array
Hello @Den4ik 
Thank you for your job.
Could you please revert return type because this is BIC
Thank you in advance.

2021-10-17 06:51 UTC, Den4ik commented
@magento run all tests with env PHP 8.0

2021-10-17 06:51 UTC, Den4ik commented
@eduard13 @andrewbess Thanks for review. BIC rolled back.

2021-10-17 07:09 UTC, ihor-sviziev commented
@Den4ik can these changes be covered with test?

2021-10-17 10:40 UTC, Den4ik commented
As I know it's already covered by functional tests that was failed.
I'll check it.

2021-10-17 20:37 UTC, Den4ik commented
@magento run Functional Tests B2B, Unit Tests, WebAPI Tests with env PHP 8.0

2021-10-18 09:22 UTC, andrewbess approved these changes

2021-10-18 12:01 UTC, Den4ik commented
As I see failed tests is not related to changes

2021-10-18 12:04 UTC, andrewbess commented
> As I see failed tests is not related to changes

Hello @Den4ik 
We know about it.
Don't worry about it.
Thank you for your attention here

2021-10-18 22:43 UTC, merged