Fix static errors for previously delivered code (phpstan)
magento/magento2 pull request #34351
Opened 2021-10-15 10:50 UTC by SilinMykola

### Description (*)
I removed `\Magento\Framework\App\Action\Title` class calls from Unit tests

### Related Pull Requests

### Related Issues (if relevant)
1. magento/magento2#34056
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-15 10:51 UTC, SilinMykola commented
@magento run all tests

2021-10-15 10:51 UTC, SilinMykola commented
@magento run all tests with env PHP 8.0

2021-10-15 11:21 UTC, SilinMykola commented
@magento run all tests with env PHP 8.0

2021-10-15 11:21 UTC, SilinMykola commented
@magento run all tests

2021-10-15 15:06 UTC, andrewbess approved these changes

2021-10-15 15:59 UTC, eduard13 approved these changes

2021-10-15 18:54 UTC, xmav commented
please check build failures

2021-10-15 19:16 UTC, andrewbess commented
> please check build failures

Hello @xmav 
It fixed in https://github.com/magento/magento2/pull/34354

2021-10-15 19:30 UTC, andrewbess approved these changes

2021-10-15 21:07 UTC, xmav commented
Could we combine it with #34354 ?

2021-10-19 09:57 UTC, ihor-sviziev requested changes
Please fix static test failures or combine with other PR

2021-10-19 11:25 UTC, SilinMykola commented
> Please fix static test failures or combine with other PR

@ihor-sviziev we fixed this static test in combined PR. PLease check [PR](https://github.com/magento/magento2/pull/34369)

2021-10-21 03:13 UTC, xmav commented
@magento run Static Tests

2021-10-21 04:49 UTC, xmav requested changes

2021-10-21 04:49 UTC, xmav commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/AddCommentTest.php
>          $this->contextMock->expects($this->any())
Please remove 'getTitle'  from `->setMethods(['getRequest', 'getResponse', 'getObjectManager', 'getTitle'])` in code above

2021-10-21 04:49 UTC, xmav commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/CancelTest.php
> -            ->getMock();
Please remove 'getTitle'  from 
```
->setMethods(
                [
                    'getRequest',
                    'getResponse',
                    'getObjectManager',
                    'getTitle',
                    'getSession',
                    'getHelper',
                    'getActionFlag',
                    'getMessageManager',
                    'getResultRedirectFactory'
                ]
            )
```

2021-10-21 04:49 UTC, xmav commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/UpdateQtyTest.php
> -        $titleMock = $this->getMockBuilder(\Magento\Framework\App\Action\Title::class)
Please remove `getTitle` from 
```
 ->setMethods(
                [
                    'getRequest',
                    'getResponse',
                    'getObjectManager',
                    'getTitle',
                    'getSession',
                    'getHelper',
                    'getActionFlag',
                    'getMessageManager',
                    'getResultRedirectFactory'
                ]
            )
```

2021-10-21 04:49 UTC, xmav commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/VoidActionTest.php
> -        $titleMock = $this->getMockBuilder(\Magento\Framework\App\Action\Title::class)
Please remove `getTitle` from 
```
 ->setMethods(
                [
                    'getRequest',
                    'getResponse',
                    'getObjectManager',
                    'getTitle',
                    'getSession',
                    'getHelper',
                    'getActionFlag',
                    'getMessageManager',
                    'getResultRedirectFactory'
                ]
            )
```

2021-10-21 04:49 UTC, xmav commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Invoice/AddCommentTest.php
> -            ->getMock();
Please remove  ` ->addMethods(['getTitle'])`

2021-10-21 04:49 UTC, xmav commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Invoice/NewActionTest.php
> -            ->getMock();
Please remove `addMethods(['getTitle'])`

2021-10-21 04:49 UTC, xmav commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Invoice/VoidActionTest.php
> -
Please remove `->addMethods(['getTitle'])`

2021-10-21 10:19 UTC, SilinMykola commented
@magento run all tests

2021-10-21 10:19 UTC, SilinMykola commented
@magento run all tests with env PHP 8.0

2021-10-21 10:19 UTC, SilinMykola commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Invoice/VoidActionTest.php
> -
fixed

2021-10-21 10:20 UTC, SilinMykola commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Invoice/NewActionTest.php
> -            ->getMock();
fixed

2021-10-21 10:20 UTC, SilinMykola commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Invoice/AddCommentTest.php
> -            ->getMock();
fixed

2021-10-21 10:20 UTC, SilinMykola commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/VoidActionTest.php
> -        $titleMock = $this->getMockBuilder(\Magento\Framework\App\Action\Title::class)
fixed

2021-10-21 10:20 UTC, SilinMykola commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/UpdateQtyTest.php
> -        $titleMock = $this->getMockBuilder(\Magento\Framework\App\Action\Title::class)
fixed

2021-10-21 10:20 UTC, SilinMykola commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/CancelTest.php
> -            ->getMock();
fixed

2021-10-21 10:20 UTC, SilinMykola commented on app/code/Magento/Sales/Test/Unit/Controller/Adminhtml/Order/Creditmemo/AddCommentTest.php
>          $this->contextMock->expects($this->any())
fixed

2021-10-21 10:31 UTC, andrewbess approved these changes

2021-10-22 00:38 UTC, merged