Use the translated tax rate title if it exists in the applied_taxes g…
magento/magento2 pull request #34360
Opened 2021-10-16 12:25 UTC by hostep

…raphql data.

### Description (*)
When requesting the applied tax information from the current cart, the tax rate titles weren't getting translated when those translations were filled in into the backend of Magento.
This PR fixes that.

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/30281

### Manual testing scenarios (*)
1. Have some sort of GraphQL tool installed (Altair GraphQL Client for example)
2. Start from a clean Magento installation
3. Make sure you have at least 2 storeviews, storeview codes I'm going to use: 'en' (English) & 'nl' (Dutch)
4. In the backend, go to Stores > Tax Rates and create 2 rates:
<img width="950" alt="Screenshot 2021-10-16 at 14 39 18" src="https://user-images.githubusercontent.com/85479/137587806-55bad8dd-35be-4630-b1c9-b53cf7589cf9.png">
5. For the second Tax Rate, make sure to also fill in translated Tax Titles (don't do this for the first one!):
<img width="932" alt="Screenshot 2021-10-16 at 14 41 28" src="https://user-images.githubusercontent.com/85479/137588556-3360d11f-5179-464e-9ae4-4db3b8bfeb30.png">
6. Go to Stores > Tax Rules and create 2 rules:
<img width="1213" alt="Screenshot 2021-10-16 at 14 42 45" src="https://user-images.githubusercontent.com/85479/137587890-7cec9922-0637-48ad-af49-3c0419efac4e.png">
7. Create 2 simple products, use SKUs: 'Product One' and 'Product Two', assign the first one to the 'Taxable Goods 1' tax class and the second to 'Taxable Goods 2', give them both a price of 100.
<img width="1083" alt="Screenshot 2021-10-16 at 14 46 01" src="https://user-images.githubusercontent.com/85479/137588036-da7fbfa2-3d7c-4c6f-b19d-fa44106b8aa3.png">
8. Reindex all indexers, flush all caches

9. In the GraphQL tool, configure it with the correct url `https://base_url/graphql`, modify the HTTP headers so it sends `Store: en`, and then execute the following mutations/queries:

```graphql
mutation createCart {
  createEmptyCart(input: { cart_id: "test_id_with_32_characters_12345" })
}

mutation addProductsToCart {
  addProductsToCart(
    cartId: "test_id_with_32_characters_12345"
    cartItems: [{ quantity: 1, sku: "Product One" },{ quantity: 1, sku: "Product Two" }]
  ) {
    cart {
      items {
        product {
          name
          sku
        }
        quantity
      }
    }
  }
}

mutation setShippingAddress {
  setShippingAddressesOnCart(
    input: {
      cart_id: "test_id_with_32_characters_12345"
      shipping_addresses: [
        {
          address: {
            firstname: "Bob"
            lastname: "Roll"
            company: "Magento"
            street: ["Magento Pkwy", "Main Street"]
            city: "Austin"
            region: "CA"
            postcode: "78758"
            country_code: "US"
            telephone: "8675309"
            save_in_address_book: false
          }
        }
      ]
    }
  ) {
    cart {
      shipping_addresses {
        region {
          code
          label
        }
        country {
          code
          label
        }
      }
    }
  }
}

query getCart {
  cart(cart_id: "test_id_with_32_characters_12345") {
    items {
      quantity
      product {
        name
        sku
        price_tiers {
          quantity
          final_price {
            value
          }
        }
      }
      prices {
        price {
          value
        }
      }
    }
    prices {
      applied_taxes {
        label
        amount {
          value
        }
      }
    }
    shipping_addresses {
      country {
        code
        label
      }
      region {
        code
        label
      }
    }    
  }
}
```

10. Inspect the results of the final query. The `applied_taxes` output should look like this:

```graphql
        "applied_taxes": [
          {
            "label": "Tax Rate One",
            "amount": {
              "value": 10
            }
          },
          {
            "label": "Tax Rate Two English",
            "amount": {
              "value": 20
            }
          }
        ]
```

11. Now repeat the last query with the HTTP header set to: `Store: nl` and now the `applied_taxes` output should look like this:

```graphql
        "applied_taxes": [
          {
            "label": "Tax Rate One",
            "amount": {
              "value": 10
            }
          },
          {
            "label": "Tax Rate Two Dutch",
            "amount": {
              "value": 20
            }
          }
        ]
```

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-16 12:27 UTC, hostep commented
@magento run all tests

2021-10-16 15:30 UTC, hostep commented
I was going to try to look into improving the [current](https://github.com/magento/magento2/blob/2.4.3-p1/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/CartTotalsTest.php) [quote](https://github.com/magento/magento2/blob/2.4.3-p1/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/CartTotalsTest.php) graphql functional tests, because they don't take those Tax titles into account yet, but I'm running into https://github.com/magento/magento2/issues/32252 on my local machine unfortunately :(

2021-10-17 11:03 UTC, hostep commented
Okay, managed to get ssl verification on my local environment working by using [mkcert](https://github.com/FiloSottile/mkcert).

Added an additional functional test with a tax rate title that now gets tested and it works on my local.

@magento run all tests

2021-10-17 11:10 UTC, hostep commented
@magento run all tests

2021-10-17 21:47 UTC, hostep commented
@magento run Unit Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

2021-10-18 17:19 UTC, slavvka commented
@magento run all tests

2021-10-18 19:41 UTC, hostep commented
The failures have nothing to do with the changes from the PR. They are just random.

(Also: shouldn't we think about the global climate/energy crisis and try to avoid running the same long and expensive tests so many times even if they failed previously on non-issues and keep on re-running them tells nothing about the quality of this PR? You guys should really spend more time in trying to make these tests more stable and if you can't make them stable for some reason, then disable the unstable ones even if that decreases the test coverage, it's going to make all contributors/reviewers lives much easier)

2021-10-19 10:01 UTC, ihor-sviziev commented
@magento run Functional Tests B2B , Functional Tests CE

2021-10-21 09:39 UTC, ihor-sviziev approved these changes

2021-10-21 09:40 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9273](https://jira.corp.magento.com/browse/ENGCOM-9273) has been created to process this Pull Request

2021-10-26 18:43 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2021-10-27 04:38 UTC, engcom-Alfa commented
@magento run Functional Tests B2B

2021-10-27 10:10 UTC, engcom-Alfa commented
Hi @hostep , @ihor-sviziev 
Thanks for the collaboration & contribution!

:x: QA not Passed

Cart query always returns Tax Identifier value instead of Tax Title in the _applied_taxes_ field

**Manual Scenario Steps**

1. In a clean Magento instance, created a 2 stores along with that I had one default main website (default one is : _local.prtest.com_; 1 store is- _local.prtest.uk_ and second store - _local.prtest.nl_)
2. Made sure all the store websites are working fine.
3. In the backend, Stores > Tax Rates and created 2 rates: as shown in below screenshot.
![image](https://user-images.githubusercontent.com/51679138/139038349-350e60c0-4219-4ed5-a08c-9038cb489667.png)

4. For the second Tax Rate, also filled in translated Tax Titles (didn't do this for the first one!):
![image](https://user-images.githubusercontent.com/51679138/139038586-3c729c5c-b9ab-48c9-b711-b80671b009f9.png)


5. Stores > Tax Rules and created 2 rules:
6. Created 2 simple products, use SKUs: 'Product One' and 'Product Two', assigned the first one to the 'Taxable Goods 1' tax class and the second to 'Taxable Goods 2', with price 100 to both.
7. Re-indexed all indexers, flushed all caches
8. Executed all the below GraphQL requests one after other sequentially. (Used the default base URL - _local.prtest.com_)

req 1- 
`mutation createCart {
  createEmptyCart(input: { cart_id: "test_id_with_32_characters_12345" })
}`

req 2-
`mutation addProductsToCart {
  addProductsToCart(
    cartId: "test_id_with_32_characters_12345"
    cartItems: [{ quantity: 1, sku: "Product One" },{ quantity: 1, sku: "Product Two" }]
  ) {
    cart {
      items {
        product {
          name
          sku
        }
        quantity
      }
    }
  }
}`

req 3-
`mutation setShippingAddress {
  setShippingAddressesOnCart(
    input: {
      cart_id: "test_id_with_32_characters_12345"
      shipping_addresses: [
        {
          address: {
            firstname: "Bob"
            lastname: "Roll"
            company: "Magento"
            street: ["Magento Pkwy", "Main Street"]
            city: "Austin"
            region: "CA"
            postcode: "78758"
            country_code: "US"
            telephone: "8675309"
            save_in_address_book: false
          }
        }
      ]
    }
  ) {
    cart {
      shipping_addresses {
        region {
          code
          label
        }
        country {
          code
          label
        }
      }
    }
  }
}`

req 4-
`query getCart {
  cart(cart_id: "test_id_with_32_characters_12345") {
    items {
      quantity
      product {
        name
        sku
        price_tiers {
          quantity
          final_price {
            value
          }
        }
      }
      prices {
        price {
          value
        }
      }
    }
    prices {
      applied_taxes {
        label
        amount {
          value
        }
      }
    }
    shipping_addresses {
      country {
        code
        label
      }
      region {
        code
        label
      }
    }    
  }
}`


**:heavy_check_mark: Step 8 response - Expected result After Fix** 
 The _applied_taxes_ output should look like this -
  `"applied_taxes": [
          {
            "label": "Tax Rate One",
            "amount": {
              "value": 10
            }
          },
          {
            "label": "Tax Rate Two Def",
            "amount": {
              "value": 20
            }
          }
        ]`


**:heavy_check_mark: Step 8 response - Actual result After Fix** 
- It is same as above mentioned expected result; Prior to the fix - issue was - In the place of _label: Tax Rate Two Def_; we were getting _label: Tax Rate Two_


9. But the still the execution continues with uk and nl stores: Repeat the same above 8 steps for **local.prtest.uk** or **local.prtest.nl**

**:heavy_check_mark: Step 9 response - Expected result After Fix** 
 The _applied_taxes_ output should look like this -
  `"applied_taxes": [
          {
            "label": "Tax Rate One",
            "amount": {
              "value": 10
            }
          },
          {
            "label": "Tax Rate Two English",
            "amount": {
              "value": 20
            }
          }
        ]`


**:x: Step 9 response - Actual result After Fix** 
- As per the above expectation- In the place of _label: Tax Rate Two English_; we are getting _label: Tax Rate Two Def_
![image](https://user-images.githubusercontent.com/51679138/139044645-4a115547-655f-4397-aed1-f58d322fad98.png)


**Here the observation is:** With the store level request also, we are getting the label with default tax

2021-10-27 10:11 UTC, engcom-Alfa requested changes
Based on the above comment, moving back to Changes Requested

2021-10-27 11:22 UTC, ihor-sviziev commented
@hostep @engcom-Alfa, could you cover the case that you've found with the web API tests as well?

2021-10-27 19:10 UTC, hostep commented
@engcom-Alfa: thanks very much for testing.

Before I put some more time into this, can you confirm that with all your `getCart` queries, you added a HTTP header: `Store: xxxx` where `xxxx` is the storeview code?

Also a screenshot of your website/store/storeview setup would be appreciated

2021-11-02 08:32 UTC, hostep commented
Hi @engcom-Alfa, do you have an update on the questions I asked you? Thanks! 🙂

2021-11-16 20:46 UTC, hostep commented
Hi @engcom-Alfa: do you have an update for me please? Thanks!

2021-12-23 19:53 UTC, engcom-Alfa commented
Hi @hostep Apologies for the delayed response. Soon I will get back to you on this completely! Thanks

2022-01-04 08:24 UTC, engcom-Lima commented
Hi @hostep,
Discussed with @engcom-Alfa about setting the Store value in header.
Issue is reproducible prior the PR changes and fixed in this PR hence moving it in Ready for Testing column.

2022-01-04 14:34 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Utilising [above-steps](https://github.com/magento/magento2/pull/34360#issuecomment-952760173) and including the header values(store_id=en/nl) [as discussed above](https://github.com/magento/magento2/pull/34360#issuecomment-1004609739) in the requests, the PR is verified and working fine.
There is no additional regression is required as part of testing since it is relevant to GraphQL and moreover the auto-tests have been covered on this.

2022-03-29 19:54 UTC, merged