Change server config files for php8 compatibility
magento/magento2 pull request #34392
Opened 2021-10-20 07:42 UTC by SilinMykola

### Description (*)
Change server config files `.htaccess` for php8 compatibility.

### Related Pull Requests

### Related Issues (if relevant)
1. Fixes magento/magento2#34358

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-20 07:43 UTC, SilinMykola commented
@magento run WebAPI Tests with env PHP 8.0

2021-10-20 07:43 UTC, SilinMykola commented
@magento run WebAPI Tests

2021-10-20 09:30 UTC, andrewbess commented
@magento run all tests with env PHP 8.0

2021-10-20 09:30 UTC, andrewbess commented
@magento run all tests

2021-10-20 10:31 UTC, Den4ik requested changes
HI @SilinMykola. Thanks for PR. Please look at comments below

2021-10-20 10:31 UTC, Den4ik commented on pub/.htaccess
> +    php_value max_execution_time 600
Are you sure that max execute time should be 600 sec?

2021-10-20 11:02 UTC, SilinMykola commented on pub/.htaccess
> +    php_value max_execution_time 600
@Den4ik ok, I'll change like in nginx config.

2021-10-20 11:07 UTC, SilinMykola commented
@magento run all tests with env PHP 8.0

2021-10-20 11:07 UTC, SilinMykola commented
@magento run all tests

2021-10-20 14:09 UTC, xmav requested changes

2021-10-20 14:09 UTC, xmav commented on pub/media/.htaccess
>  <IfModule mod_php5.c>
PHP5.X is not supported. Feel free to remove

2021-10-20 14:09 UTC, xmav commented on pub/static/.htaccess
>  <IfModule mod_php5.c>
PHP5.X is not supported. Feel free to remove

2021-10-20 14:09 UTC, xmav commented on pub/.htaccess
> +    php_flag suhosin.session.cryptua off
suhosin ext is not available for PHP8. Please remove

2021-10-20 14:09 UTC, xmav commented on pub/.htaccess
> +    php_value max_execution_time 18000
Let's use same value as in nginx -> 600 for now.

2021-10-20 14:13 UTC, xmav commented on pub/.htaccess
> +    php_value max_execution_time 18000
oh. 600 is for setup/*
Ok. let it be 18000 but that value definitely need review

2021-10-20 15:44 UTC, SilinMykola commented on pub/media/.htaccess
>  <IfModule mod_php5.c>
fixed

2021-10-20 15:44 UTC, SilinMykola commented on pub/static/.htaccess
>  <IfModule mod_php5.c>
fixed

2021-10-20 15:44 UTC, SilinMykola commented on pub/.htaccess
> +    php_flag suhosin.session.cryptua off
fixed

2021-10-20 15:48 UTC, xmav commented
@magento run WebAPI Tests with env PHP 8.0

2021-10-20 17:59 UTC, andrewbess approved these changes

2021-10-20 18:21 UTC, ihor-sviziev approved these changes

2021-10-20 18:29 UTC, eduard13 approved these changes

2021-10-20 19:10 UTC, Den4ik approved these changes

2021-10-20 20:19 UTC, hostep commented on pub/.htaccess
> +    php_value max_execution_time 600
With more and more long running processes moving to async message queues, it makes sense to lower the max_execution_time in my opinion. Why should a request via the webserver have the ability to take 5 hours to run?
600 (10 minutes) is a much more sensible value.

But it falls out of scope of this PR to change it, since we would also then need to change the [`.user.ini`](https://github.com/magento/magento2/blob/2.4-develop/pub/.user.ini) file

2021-10-20 20:40 UTC, xmav commented on pub/.htaccess
> +    php_value max_execution_time 600
my guess that's it is coming from old times when we had "sync" import\export in Admin UI. Trying to confirm that we don't have similar places anymore(before decreasing value)

2021-10-21 02:15 UTC, merged

2021-10-21 02:16 UTC, xmav commented on pub/.htaccess
> +    php_value max_execution_time 600
`max_execution_time` decrease will be covered in another ticket