Update `pelago/emogrifier` to version 6.0.0
magento/magento2 pull request #34396
Opened 2021-10-21 08:29 UTC by anzin

### Description (*)

Updated `pelago-emogrifier` composer dependencies to be compatible with PHP 8.1.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/638

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34374

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-21 08:32 UTC, anzin commented
@magento run all tests

2021-10-21 08:33 UTC, anzin commented
@magento run all tests with env PHP 8.0

2021-10-21 10:27 UTC, andrewbess approved these changes

2021-10-21 11:49 UTC, anzin commented
@magento run Functional Tests B2B

2021-10-22 01:04 UTC, xmav requested changes

2021-10-22 01:04 UTC, xmav commented on composer.json
>          "laminas/laminas-mail": "^2.9.0",
Could you please update this one too ?

2021-10-22 08:36 UTC, Den4ik commented
@magento run all tests with env PHP 8.0

2021-10-22 08:40 UTC, anzin commented
@magento run all tests

2021-10-22 08:41 UTC, anzin commented
@magento run all tests with env PHP 8.0

2021-10-22 09:50 UTC, anzin commented
@magento run Unit Tests

2021-10-22 10:03 UTC, anzin commented
@magento run WebAPI Tests

2021-10-22 13:37 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests look not related to changes from this PR.

2021-10-22 13:57 UTC, Den4ik approved these changes

2021-10-22 15:06 UTC, merged