Don't try to update with an empty price
magento/magento2 pull request #34403
Opened 2021-10-21 15:04 UTC by RikvdHeijden

When trying to update a product price according to the tier price, skip the product update when no tier price is found. 
### Description (*)
When no tier price was found the system still tried to update the price with an object of 
```
{
    'prices': {
        'finalPrice': {
            'amount': NaN
        }
    }
};
```
This caused configurable product display prices for configurations that add to the product price to reset on qty changes.

### Manual testing scenarios (*)
- Create a configurable product with an child product that has a different price
- Configure this product in the frontend. The displayed price should change to reflect the simple product's price.
- Change the quantity. Before this change this reset the product price back to the default price. After this change it should persist the correct price.

### Contribution checklist (*)
 - [ x] Pull request has a meaningful description of its purpose
 - [ x] All commits are accompanied by meaningful commit messages
 - [ x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ?] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35753: Configurable option tiered price reverts to lowest price

2021-10-21 15:05 UTC, RikvdHeijden commented
@magento give me 2.4-develop instance

2021-10-21 15:14 UTC, RikvdHeijden commented
@magento give me test instance

2021-10-21 15:37 UTC, RikvdHeijden commented
@magento run all tests

2021-10-26 06:45 UTC, engcom-Alfa commented
@magento create issue

2021-10-29 07:51 UTC, RikvdHeijden commented
@magento give me 2.4-develop instance

2021-10-29 07:53 UTC, RikvdHeijden commented
@magento give me 2.3-develop instance

2022-03-07 15:33 UTC, RikvdHeijden commented
@magento give me 2.4-develop instance

2022-04-14 20:55 UTC, ishakhsuvarov commented
@magento run all tests

2023-03-01 10:56 UTC, eduard13 commented
@magento give me 2.4-develop instance

2023-04-10 18:27 UTC, engcom-Hotel commented
@magento run WebAPI Tests, Functional Tests B2B

2023-04-10 18:29 UTC, engcom-Hotel requested changes
Hello @RikvdHeijden,

There are some conflicts in the build please resolve them and cover the code changes with some automated tests.

Thanks

2023-04-19 08:07 UTC, closed without merging