Replace repetitive actions with Action Groups in AdminCreateDuplicateCategoryTest and AdminCreateDuplicateProductTest
magento/magento2 pull request #34410
Opened 2021-10-22 13:10 UTC by kate-kyzyma

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)
Tests are refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run test locally

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34414: Replace repetitive actions with Action Groups in AdminCreateDuplicateCategoryTest and AdminCreateDuplicateProductTest

2021-10-22 13:11 UTC, kate-kyzyma commented
@magento run all tests

2021-10-22 13:18 UTC, kate-kyzyma commented
@magento run all tests

2021-10-24 11:56 UTC, shikhamis11 commented
@magento create issue

2021-10-24 11:59 UTC, shikhamis11 requested changes

2021-10-24 11:59 UTC, shikhamis11 commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCreateDuplicateCategoryTest.xml
> +        <actionGroup ref="AssertMessageInAdminPanelActionGroup" stepKey="assertErrorMessage">
keep original stepKey i.e `seeErrorMessage` in `actionGroup` to avoid semantic version failure

2021-10-25 06:45 UTC, kate-kyzyma commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCreateDuplicateCategoryTest.xml
> +        <actionGroup ref="AssertMessageInAdminPanelActionGroup" stepKey="assertErrorMessage">
Hi, @shikhamis11!

The issue is fixed. Please, check.

2021-10-25 06:45 UTC, kate-kyzyma commented
@magento run all tests

2021-10-25 11:56 UTC, kate-kyzyma commented
@magento run Functional Tests B2B

2021-10-26 06:42 UTC, kate-kyzyma commented
@magento run Functional Tests B2B

2021-10-26 06:46 UTC, kate-kyzyma commented
@magento run Functional Tests B2B

2021-10-28 13:50 UTC, kate-kyzyma commented
@magento run Functional Tests B2B

2021-10-29 09:25 UTC, shikhamis11 approved these changes

2021-10-29 09:26 UTC, magento-engcom-team commented
Hi @shikhamis11, thank you for the review.
[ENGCOM-9317](https://jira.corp.magento.com/browse/ENGCOM-9317) has been created to process this Pull Request
:eight_spoked_asterisk: @shikhamis11, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-11-05 15:47 UTC, merged