Allow caller to decide if to use stock filter for configurable product children collection
magento/magento2 pull request #34459
Opened 2021-10-27 21:31 UTC by fredden

### Description
Sometimes a merchant wants to show all possible options for a configurable product, including those which are currently out of stock. Currently there is no option for a developer to get this list with existing functionality. This pull request adds a parameter to allow developers to make this decision. The default value for this new parameter matches existing behaviour.

### Related Pull Requests

*None*

### Fixed Issues (if relevant)
None yet, please create if required.

### Manual testing scenarios
1. No changes should be witnessed after merging this pull request as the default functionality is being maintained.
2. A developer may now list children of a configurable product which are not available for sale.

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2022-10-21 11:25 UTC, fredden commented
@magento run all tests

2022-11-04 12:14 UTC, fredden commented
@magento run all tests

2025-02-20 11:52 UTC, engcom-Hotel commented
@magento run all tests

2025-02-21 07:48 UTC, engcom-Hotel requested changes
Hello @fredden,

Thanks for the contribution!

Please fix the failed static test and add an automated test in accordance to [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

2025-02-22 14:43 UTC, fredden commented
@magento run all tests

2025-02-22 14:44 UTC, fredden commented
@engcom-Hotel I have updated this pull request. I am sure that the tests passed when I opened this more than three years ago.

2025-02-24 06:36 UTC, engcom-Hotel requested changes
Hello @fredden,

Thanks for updating the PR!

We are still having some [static test failures](https://github.com/magento/magento2/pull/34459/checks?check_run_id=37650740756) on the PR, please fix those and also add an automated test for this fix.

Thanks

2025-02-24 09:29 UTC, fredden commented
@engcom-Hotel it is not my place to change copyright information. It's also out of scope for this pull request. If you require the copyright information to be different, please adjust this in a separate pull request.

2025-02-25 07:37 UTC, engcom-Hotel commented
Hello @fredden,

I agree with your concern but in order to process the PR, we need a green build. And for the copyright static test failure, you just need to make the below changes in the file:

```
Copyright [year code created] Adobe 
All Rights Reserved.
```

So please do the needful and also please add the automated test.

Thanks

2025-03-01 18:31 UTC, fredden commented
Changing copyright is out of scope for this pull request. I do not represent neither Magento Inc nor Adobe; changing the copyright between these two companies is not something that I'm willing to do. @engcom-Hotel, please raise a separate pull request to address this change if it's important to you.

I have looked at the existing unit tests for this class. From what I can tell, the `getSalableUsedProducts` method has no tests and the `getUsedProducts` method has only the most basic test and does not have proper / full coverage of the existing behaviour. @engcom-Hotel, I recommend that you raise a new issue in your internal Jira instance asking for tests to be reviewed for this class. If you can offer a suggestion for how you would like the functionality being added here to be tested, please do share that here and we can review if such a change is feasible / within the scope of this pull request. Rewriting all the tests for this class is not in scope here.

2025-03-18 05:48 UTC, engcom-Charlie commented
Hi @fredden,

Thank you for your contribution!

In order to proceed further on this PR, we need a green build and currently the static test is failing for the copyright issue. As per the process, we have to provide the fix in the same PR. Can we go ahead and do the needful. We will look into the review comments and the test failures too in the same PR.

Please let us know, till then moving this PR to On Hold.

2025-04-23 06:29 UTC, engcom-Charlie commented
Hi @fredden,

As mentioned in [previous](https://github.com/magento/magento2/pull/34459#issuecomment-2731745872) comment, we need to take care the review comments and test failures in the same PR.  We are closing this PR until we will get any reply from the above comment. Please feel free to reopen if you are willing to work on it.

Thank you!

2025-04-23 06:29 UTC, closed without merging