#34394 Primary DI configuration is not merged properly
magento/magento2 pull request #34457
Opened 2021-10-27 14:23 UTC by kandy

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/34394
2. Fixes https://github.com/magento/magento2/issues/34464

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-27 14:24 UTC, kandy commented
@magento run Integration Tests

2021-10-27 14:25 UTC, kandy commented
@magento run Functional Tests CE

2021-10-27 14:56 UTC, ihor-sviziev commented
I think it's better to run all tests and review all the results.
PS: original links were 
- https://github.com/magento/magento2/pull/34457/checks?check_run_id=4023533363 
- https://github.com/magento/magento2/pull/34457/checks?check_run_id=4023533562
@magento run all tests

2021-10-28 06:54 UTC, ihor-sviziev requested changes
Hi @kandy,
Could you review the test failures and adjust your solution accordingly?

2021-10-28 14:16 UTC, Den4ik commented
As I see most failed tests completely not related to PR changes.
Let's try rerun after update from 2.4-develop branch.

2021-10-28 14:16 UTC, Den4ik commented
@magento run all tests

2021-10-28 18:23 UTC, ihor-sviziev commented
@Den4ik as you see - they are related

2021-10-28 19:15 UTC, Den4ik commented
@ihor-sviziev yep, same Tests failed again, but, for example, failed static tests looks little bit strange

2021-11-17 07:20 UTC, DmitryFurs commented
Here is an additional code snippet that contains a duplicate of the arguments associated with the initial problem. In order to add a `$scp` variable to the dictionary, in the `Magento_Csp` module, we need to repeat the arguments from `app/etc/di.xml`.

`app/etc/di.xml` - https://github.com/magento/magento2/blob/2.4-develop/app/etc/di.xml#L1919-L1926
`Magento_Csp` - https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Csp/etc/di.xml#L77-L85

2022-01-26 05:29 UTC, kandy commented
Looks like this solution can be applied

2022-01-26 05:29 UTC, closed without merging

2022-01-26 14:43 UTC, DmitryFurs commented
@kandy will this be fixed in the upcoming 2.4.4 release? Thanks!