Update expires_at column type from table admin_user_expiration in ord…
magento/magento2 pull request #34462
Opened 2021-10-28 09:04 UTC by SinpietruAdrian

### Description
  New admin account is disabled after a login attempt is made if the account's expiration date is greater than 2038. This is fixed by updating the expires_at column type from the admin_user_expiration table to datetime.

### Fixed Issues
https://github.com/magento/magento2/issues/34463

### Manual testing scenarios 
Create an admin user with an Expiration Date greater than 2038 and attempt a login to the admin area with this newly created user.

2021-10-28 09:16 UTC, hostep commented
FYI, this is a similar fix as https://github.com/magento/magento2/pull/22718 that solved a similar problem with the year 2037/2038 in coupon codes as described [over here](https://github.com/magento/magento2/issues/18183#issuecomment-423746395)

2021-10-28 09:25 UTC, SinpietruAdrian commented
@magento run all tests

2021-10-28 09:58 UTC, ihor-sviziev commented
@SinpietruAdrian @hostep,
Good catch!
It looks like we should migrate **all** fields with "timestamp" to the "datetime".
What do you think?

2021-10-28 12:51 UTC, hostep commented
@ihor-sviziev: yeah probably, I guess. But should it happen in scope of this PR?
I "only" find 146 occurrences in the entire codebase 😛

2021-10-28 13:38 UTC, ihor-sviziev commented
@hostep, as to me it looks like a quite simple fix. It's better to fix all places at once than fixing all places separately

2021-10-29 08:42 UTC, hostep commented
@ihor-sviziev: I've just briefly discussed this with Adrian (a colleague of mine) during our daily standup, and we decided that it is out of scope of this PR to change all the fields in the entire codebase, because there could be unwanted consequences due to how timezones are handled. In this particular case, the timezone is not that important.

I've opened a new issue to investigate all other usages of those timestamp fields in the codebase: https://github.com/magento/magento2/issues/34478

Is this ok for you guys?

2021-10-29 10:06 UTC, ihor-sviziev requested changes
Hi @SinpietruAdrian,
Could you sign the adobe CLA?

2021-11-02 10:41 UTC, SinpietruAdrian commented
I've signed the CLA, closed/reopened the PR but it's still failing. Anything else I should do?

2021-11-02 11:49 UTC, ihor-sviziev commented
Hi @SinpietruAdrian,
Please add your commit author's email to your github account.

2022-01-04 04:09 UTC, engcom-Bravo commented
@SinpietruAdrian Please sign CLA. We could not merge PR without that

2022-01-20 09:13 UTC, engcom-Lima commented
Hi @SinpietruAdrian ,

Thank you for your contribution!

We are not able to proceed further on this PR as you have not signed the Adobe CLA yet. Hence closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution!

2022-01-20 09:13 UTC, closed without merging

2022-09-13 13:55 UTC, hostep commented
Looks like this got fixed by core devs in: https://github.com/magento/magento2/commit/97f85b9de2e95e61e77359f2e255acb9bf989e32 (which is included in Magento 2.4.5)