Remove redundant COUNT() call for 1st page of results
magento/magento2 pull request #34484
Opened 2021-10-29 22:20 UTC by lbajsarowicz

### Description (*)
Magento is performing lots of redundant DB calls. 

The Category Edit page is one of the examples. If you are on the 1st page, it does not make sense to calculate the last page and redirect to the 1st one... Because you are on the 1st one.

The results of this optimization are huge, based on the Category Edit Page with ~2k categories, 12.5M products.
![image](https://user-images.githubusercontent.com/1639941/139507376-1970bc82-5f8f-43e2-91a3-7eacfa156537.png)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-10-29 22:52 UTC, lbajsarowicz commented
@magento run all tests

2021-10-30 05:48 UTC, ihor-sviziev requested changes
Hi @lbajsarowicz,
Great improvement! I guess for large data sets it might be really noticeable. Do you have some measurements?
Could you cover this change with a simple unit test?

2021-10-30 09:26 UTC, lbajsarowicz commented
@ihor-sviziev  Of course, Unit Tests are coming in another commit.

@OlgaVasyltsun Quick hint for you: When you are creating a new plugin, like `\Magento\Theme\Plugin\Data\Collection`:
1. It's more helpful when you are navigating through the plugins when name of a plugin contains `Plugin` suffix
2. I strongly recommend naming the plugins by their role, not the class they override. Why? It's simple:
    * It helps to keep Single Responsibility in the class, as lazy developers won't add other logic into the same controller,
    * A single plugin can be applied to different classes, based on the Interface passed in `$subject`.

Of course, these are only hints.

2021-10-30 09:44 UTC, lbajsarowicz commented
@magento run unit tests

2021-10-30 12:10 UTC, ihor-sviziev commented
@magento run all tests

2021-10-31 06:03 UTC, ihor-sviziev approved these changes

2021-10-31 06:04 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9318](https://jira.corp.magento.com/browse/ENGCOM-9318) has been created to process this Pull Request

2021-10-31 10:47 UTC, Den4ik commented on app/code/Magento/Theme/Test/Unit/Plugin/CollectionTest.php
> +    /** @var MockObject|Collection */
```suggestion
    /**
     * @var Collection|MockObject
     */
```

2021-10-31 10:48 UTC, Den4ik requested changes
Hi @lbajsarowicz.
Thanks for this PR. Could you please add/update doc blocks in tests file.

2021-10-31 11:12 UTC, ihor-sviziev commented on app/code/Magento/Theme/Test/Unit/Plugin/CollectionTest.php
> +    /** @var MockObject|Collection */
I don't think it's important

2021-10-31 12:47 UTC, lbajsarowicz commented
@Den4ik You mean, I need to replace 1-line PHPDoc with multi-line? If using a single line PHPDoc is invalid, we should start with change to the Magento Coding Standards first, shouldn't we?

2021-10-31 12:55 UTC, lbajsarowicz commented
@magento run all tests

2021-10-31 18:13 UTC, Den4ik commented
@magento run Functional Tests EE, Functinal Tests B2B

2021-10-31 18:15 UTC, Den4ik commented
@magento run Functional Tests EE, Functional Tests B2B

2021-10-31 18:21 UTC, Den4ik commented
@lbajsarowicz,
1. I'm not part of Magento Core
2. My requires is not important, but as you mentioned it's not mean that you should ignore some code style rules.
I'm really appreciate your contribution to Magento.

2021-10-31 18:30 UTC, ihor-sviziev approved these changes

2021-10-31 18:31 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9318](https://jira.corp.magento.com/browse/ENGCOM-9318) has been created to process this Pull Request

2021-11-01 06:34 UTC, Den4ik approved these changes

2021-11-01 06:35 UTC, magento-engcom-team commented
Hi @Den4ik, thank you for the review.
[ENGCOM-9318](https://jira.corp.magento.com/browse/ENGCOM-9318) has been created to process this Pull Request

2021-11-01 13:48 UTC, ihor-sviziev commented
These are false-positive test failures :( 
@magento run Functional Tests B2B, Functional Tests EE

2021-11-01 15:05 UTC, kandy approved these changes

2021-11-01 15:11 UTC, kandy commented
@lbajsarowicz fully agree with your comment. 
The only thing that is blocking them to implement it directly in code is they need to disable it for rest/soap area for some reason. 
I also do not catch why it is not implemented in the grid block

2021-11-01 20:47 UTC, ihor-sviziev commented
magento run Functional Tests EE, Functinal Tests B2B

2021-11-01 20:48 UTC, ihor-sviziev commented
@magento run Functional Tests EE, Functinal Tests B2B

2021-11-02 13:18 UTC, ihor-sviziev commented
@magento run Functional Tests EE, Functional Tests B2B

2021-11-03 08:06 UTC, ihor-sviziev commented
@magento run Functional Tests EE, Functional Tests B2B

2021-11-04 07:41 UTC, ihor-sviziev commented
@magento convert to patch for 2.4.3

2021-11-04 07:41 UTC, ihor-sviziev commented
@magento convert to patch for 2.3.7

2021-11-04 07:42 UTC, m2-github-services commented
@ihor-sviziev changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-2.4.3

2021-11-04 07:45 UTC, ihor-sviziev commented
Hi @lbajsarowicz,
Could you create a new PR for the following changes to port convert them to a quality patch?

2021-11-04 13:21 UTC, Den4ik commented
@sidolov, I believe that we could move it to "Merge in Progress".

2021-11-04 17:17 UTC, sidolov commented
@magento convert to patch for 2.3.7

2021-11-04 19:03 UTC, sidolov commented
@magento convert to patch for 2.4.3

2021-11-04 19:41 UTC, sidolov commented
@magento convert to patch for 2.4.3

2021-11-04 19:41 UTC, m2-github-services commented
@sidolov changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-34484-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-34484-2.4.3

2021-11-04 19:42 UTC, m2-github-services commented
@sidolov changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-34484-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-34484-2.4.3

2021-11-04 19:42 UTC, sidolov commented
@magento convert to patch for 2.3.7

2021-11-04 19:43 UTC, m2-github-services commented
@sidolov an error occurred during the patch generation.
Failure can be caused by the incompatible with base branch changes.
To replicate the issue try to apply patch locally using `git am` command.

2021-11-04 19:43 UTC, m2-github-services commented
@sidolov changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-34484-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-34484-2.4.3

2021-11-08 12:18 UTC, ihor-sviziev commented
@magento convert to patch for 2.4.3

2021-11-08 12:19 UTC, m2-github-services commented
@ihor-sviziev changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-34484-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-34484-2.4.3

2021-12-09 18:40 UTC, merged