Replace repetitive actions with Action Groups in AdminCheckInactiveAndNotIncludeInMenuCategoryAndSubcategoryIsNotVisibleInNavigationTest and AdminCheckInactiveCategoryAndSubcategoryIsNotVisibleInNavigationMenuTest
magento/magento2 pull request #34522
Opened 2021-11-03 11:39 UTC by kate-kyzyma

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)
Test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-11-03 11:39 UTC, kate-kyzyma commented
@magento run all tests

2021-11-05 16:02 UTC, sidolov requested changes
@kate-kyzyma could you please take a look on SVC failure? Remove node can be replaced with a comment with the same stepKey

2021-11-08 07:42 UTC, kate-kyzyma commented
@magento run Semantic Version Checker

2021-11-08 08:12 UTC, eduard13 commented on app/code/Magento/Catalog/Test/Mftf/Test/AdminCheckInactiveAndNotIncludeInMenuCategoryAndSubcategoryIsNotVisibleInNavigationTest.xml
> +        <actionGroup ref="AdminCategoriesOpenCategoryActionGroup" stepKey="openCategory">
Please use the same stepKey
```suggestion
        <actionGroup ref="AdminCategoriesOpenCategoryActionGroup" stepKey="selectCategory">
```

2021-11-08 08:42 UTC, kate-kyzyma commented
@magento run all tests

2021-11-08 14:17 UTC, kate-kyzyma commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2021-11-08 14:57 UTC, kate-kyzyma commented
@magento run all tests

2021-11-09 07:20 UTC, eduard13 commented
@magento run Functional Tests B2B, Integration Tests

2021-11-09 09:36 UTC, kate-kyzyma commented
@magento run all tests

2021-11-09 14:33 UTC, kate-kyzyma commented
@magento run Functional Tests B2B, Functional Tests EE

2021-11-10 05:46 UTC, eduard13 approved these changes

2021-11-10 05:47 UTC, magento-engcom-team commented
Hi @eduard13, thank you for the review.
[ENGCOM-9337](https://jira.corp.magento.com/browse/ENGCOM-9337) has been created to process this Pull Request

2021-11-21 02:33 UTC, merged