Fix adding an option with label '0'
magento/magento2 pull request #34578
Opened 2021-11-08 14:34 UTC by mbijnsdorp

### Description (*)
When adding an option to an attribute programmatically via `\Magento\Eav\Model\Entity\Attribute\OptionManagement::add`, it's not possible to use the label '0' for the option.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-11-08 14:35 UTC, mbijnsdorp commented
@magento run all tests

2021-11-09 06:57 UTC, mbijnsdorp commented
@magento run Functional Tests B2B

2021-11-09 10:04 UTC, ihor-sviziev requested changes
Hi @mbijnsdorp,
Your changes look good to me.
Could you cover your changes with some automated tests?

2021-11-09 15:43 UTC, mbijnsdorp commented
Hi @ihor-sviziev,
I'm inexperienced when it comes to writing tests. I could adjust the label of the add method https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Eav/Test/Unit/Model/Entity/Attribute/OptionManagementTest.php#L68, but that wouldn't make it very obvious. Would you suggest a similar method to that one?

2021-11-09 19:09 UTC, eduard13 commented
Hi @mbijnsdorp, thank you for your contribution. The existing test you mentioned, is a good place to cover your case. I'd suggest adding a simple dataProvider, that will provide different options labels to the `add` method. Something like in the following Unit Test.

https://github.com/magento/magento2/blob/f3e8f25987c7748d432cbe9d0fa2c54ff2a097bb/app/code/Magento/Customer/Test/Unit/Block/Widget/NameTest.php#L179-L211

Please let me know if you have any questions.

Thank you.

2021-11-10 15:50 UTC, mbijnsdorp commented
Hi @eduard13, thank you for the pointers. I've updated the test with a data provider based on the given example. Please let me know if it requires any other changes.

2021-11-10 15:51 UTC, mbijnsdorp commented
@magento run all tests

2021-11-10 21:36 UTC, mbijnsdorp commented
@magento run Unit Tests

2021-11-11 06:40 UTC, mbijnsdorp commented
@magento run all tests

2021-11-11 08:56 UTC, ihor-sviziev commented
@magento run Functional Tests CE, Functional Tests EE

2021-11-11 08:56 UTC, ihor-sviziev requested changes
Hi @eduard13 @mbijnsdorp,
Could you cover the case with the "update" method?

2021-11-11 09:07 UTC, mbijnsdorp commented
Hi @ihor-sviziev, I see there's no test for that method at all yet. I'll try to get started on it later today

2021-11-11 18:30 UTC, mbijnsdorp commented
@magento run Unit Tests

2021-11-12 07:13 UTC, mbijnsdorp commented
@magento run all tests

2021-11-12 07:49 UTC, ihor-sviziev commented on app/code/Magento/Eav/Model/Entity/Attribute/OptionManagement.php
> +        $label = trim((string) $option->getLabel());
```suggestion
        $label = trim((string)$option->getLabel());
```

2021-11-12 07:49 UTC, ihor-sviziev commented on app/code/Magento/Eav/Model/Entity/Attribute/OptionManagement.php
> +        $label = trim((string) $option->getLabel());
```suggestion
        $label = trim((string)$option->getLabel());
```

2021-11-12 07:49 UTC, ihor-sviziev commented on app/code/Magento/Eav/Test/Unit/Model/Entity/Attribute/OptionManagementTest.php
> +    public function testAdd($label)
```suggestion
    public function testAdd(string $label): void
```

2021-11-12 07:49 UTC, ihor-sviziev commented on app/code/Magento/Eav/Test/Unit/Model/Entity/Attribute/OptionManagementTest.php
> +     * @dataProvider optionLabelDataProvider
```suggestion
     * @param string $label
     * @dataProvider optionLabelDataProvider
```

2021-11-12 07:49 UTC, ihor-sviziev commented on app/code/Magento/Eav/Test/Unit/Model/Entity/Attribute/OptionManagementTest.php
> +    public function testUpdate($label)
```suggestion
    public function testUpdate(string $label): void
```

2021-11-12 07:49 UTC, ihor-sviziev commented on app/code/Magento/Eav/Test/Unit/Model/Entity/Attribute/OptionManagementTest.php
> +     * @dataProvider optionLabelDataProvider
```suggestion
     * @param string $label
     * @dataProvider optionLabelDataProvider
```

2021-11-12 07:50 UTC, ihor-sviziev commented
@magento run all tests

2021-11-12 08:07 UTC, mbijnsdorp commented
@ihor-sviziev Could you also add the partner Youwe label?

2021-11-12 10:02 UTC, ihor-sviziev commented
@sidolov @sivaschenko, could you check why the partner label wasn't applied?

2021-11-12 13:45 UTC, ihor-sviziev approved these changes
@mbijnsdorp, great job! Thank you for your contribution!
✔ Approved

2021-11-12 13:46 UTC, magento-engcom-team commented
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9343](https://jira.corp.magento.com/browse/ENGCOM-9343) has been created to process this Pull Request

2021-11-12 13:46 UTC, magento-engcom-team commented
@mbijnsdorp thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2021-11-12 18:14 UTC, sidolov commented
@ihor-sviziev label wasn't added because @mbijnsdorp is not a part of Youwe team on the GitHub

2022-01-12 07:27 UTC, engcom-Dash commented
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Add the code to add product attribute manually with label ‘0’ (screenshot below) 

<img width="790" alt="Screenshot 2022-01-12 at 12 41 04 PM" src="https://user-images.githubusercontent.com/60198592/149082672-ca92324b-f225-4b08-907d-e2eb10990580.png">

2. Run the code on the magento server 
 
**Before:** :heavy_multiplication_x:   Exception is throwing with message ‘The attribute option label is empty. Enter the value and try again.’

<img width="1082" alt="Screenshot 2022-01-12 at 12 44 01 PM" src="https://user-images.githubusercontent.com/60198592/149081373-ef907bea-8017-4e69-bd71-2c6844dc7259.png">


**After:** :heavy_check_mark:  The code run successfully without expection.

2022-02-01 16:05 UTC, merged