[Framework] Replace ZF1 email validator with Laminas
magento/magento2 pull request #34722
Opened 2021-11-26 09:20 UTC by Den4ik

### Description (*)

This PR replace usage of ZF1 email validator with Laminas library

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-11-26 09:21 UTC, Den4ik commented
@magento run all tests

2021-11-26 09:52 UTC, ihor-sviziev commented
@Den4ik it is a backward incompatible change. I think we should create a separate interface and implementation for that. What do you think about it?

2021-11-26 10:40 UTC, Den4ik commented
> @Den4ik it is a backward incompatible change. I think we should create a separate interface and implementation for that. What do you think about it?

@ihor-sviziev Totally agree with you and already working on it

2021-11-26 11:27 UTC, andrewbess requested changes
Hello @Den4ik 
Thank you for your contribution
Please see my comments
Also, please remove redundant strings from copyrights
Thank you in advance.

2021-11-26 11:27 UTC, andrewbess commented on lib/internal/Magento/Framework/Validator/EmailAddress.php
> +use Laminas\Validator\EmailAddress as LaminasEmailAddress;
Hello @Den4ik 
I think it should be EmailAddressValidator

```suggestion
use Laminas\Validator\EmailAddress as EmailAddressValidator;
```

What do you think about this?

2022-08-08 12:34 UTC, ihor-sviziev commented
I closed this PR due to inactivity. Feel free to reopen if you wish to continue

2022-08-08 20:02 UTC, Den4ik commented
> @Den4ik it is a backward incompatible change. I think we should create a separate interface and implementation for that. What do you think about it?

@ihor-sviziev I have checked dependencies and don't see possible fast solutions of using new interface due to usage at constructors of classes marked as `@api`. For example, https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Validator.php

I believe that it could be skipped in this case by architect approval.

cc @sidolov

2022-08-08 20:03 UTC, Den4ik commented
@magento run all tests

2022-08-17 09:43 UTC, Den4ik commented
Close this PR due to multiple requirement of multiple changes for `@api` marked classes.
This thing will could be implemented when Magento will plan 2.5 release, but unfortunately it's not make sense for now

2022-08-17 09:43 UTC, closed without merging