fix #34759 : check whether persistent cart is enabled in Data Helper
magento/magento2 pull request #34760
Opened 2021-12-05 11:22 UTC by cmtickle

### Description (*)

Resolves issue with disabling persistent cart highlighted in #34759 

### Related Pull Requests

(I'll raise the same PR to 2.4)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34759

### Manual testing scenarios (*)

1. Apply this fix
2. Disable Persistent Cart via admin.
3. Monitor for database calls triggered by Magento\Persistent\Observer\CheckExpirePersistentQuoteObserver
4. The database should not be called.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2021-12-05 12:19 UTC, andrewbess requested changes
Hello @cmtickle 
Thank you for your contribution
Please check my comments
Thank you in advance

2021-12-05 12:19 UTC, andrewbess commented on app/code/Magento/Persistent/Helper/Data.php
> +    protected $storeManager;
I think it is bad idea to use `protected` for new properties.
Let's use `private` here.

```suggestion
    private $storeManager;
```

2021-12-05 12:19 UTC, andrewbess commented on app/code/Magento/Persistent/Helper/Data.php
> +     * @param \Magento\Store\Model\StoreManagerInterface $storeManager
I think we need to use new parameter as optional

```suggestion
     * @param \Magento\Store\Model\StoreManagerInterface|null $storeManager
```

2021-12-05 12:19 UTC, andrewbess commented on app/code/Magento/Persistent/Helper/Data.php
> +	\Magento\Store\Model\StoreManagerInterface $storeManager
Please see my comments above and https://github.com/magento/magento2/pull/34761#discussion_r762552255
```suggestion
	\Magento\Framework\Escaper $escaper,
	\Magento\Store\Model\StoreManagerInterface $storeManager = null
```

2021-12-05 12:19 UTC, andrewbess commented on app/code/Magento/Persistent/Helper/Data.php
> +	$this->storeManager = $storeManager;
Please see my comments above and #34761 (comment)

```suggestion
        $this->_escaper = $escaper;
        $this->storeManager = $storeManager ?? \Magento\Framework\App\ObjectManager::getInstance()
                ->get(\Magento\Store\Model\StoreManagerInterface::class);
```

2021-12-05 12:22 UTC, andrewbess commented
@magento run all tests

2021-12-05 14:25 UTC, cmtickle commented
@magento run all tests

2021-12-06 06:09 UTC, ihor-sviziev commented
@magento run all tests

2021-12-07 08:07 UTC, cmtickle commented
I'll progress this after #34761 to avoid further duplication of effort.

2022-07-24 13:38 UTC, closed without merging