Fixed php 8.1 deprecations to pass Integration Tests
magento/magento2 pull request #34774
Opened 2021-12-08 11:07 UTC by anzin

### Description (*)
Fixed deprecations function php 8.1 to pass Integration Tests

### Related Pull Requests

### Related Issues (if relevant)
1. magento/magento2#34569

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-12-08 17:16 UTC, xmav approved these changes

2021-12-08 22:31 UTC, andrewbess requested changes
Hello @anzin 
Thank you for your contribution
Please check my comment
Thank you in advance.

2021-12-08 22:31 UTC, andrewbess commented on app/code/Magento/Cms/Block/Adminhtml/Wysiwyg/Images/Tree.php
> +        if ($currentTreePath && strlen($currentTreePath)) {
Hello @anzin 
I think we need to check `$currentTreePath` on null, because '0' in condition is false.

```suggestion
        if ($currentTreePath !== null && strlen($currentTreePath)) {
```

2021-12-08 22:35 UTC, andrewbess commented
@magento run Static Tests

2021-12-08 23:21 UTC, andrewbess commented
@magento run Static Tests

2021-12-08 23:22 UTC, andrewbess approved these changes
Hello @anzin 
Thank you for your contribution
Approved ✔️

2021-12-08 23:23 UTC, magento-engcom-team commented
Hi @andrewbess, thank you for the review.
[ENGCOM-9362](https://jira.corp.magento.com/browse/ENGCOM-9362) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2021-12-09 00:01 UTC, xmav commented
pending delivery https://github.com/magento-commerce/magento2ce/pull/7295

2021-12-09 15:06 UTC, merged