Excluded disabled images from grapqhl response
magento/magento2 pull request #34897
Opened 2021-12-28 11:25 UTC by nidhigupta13-ey

### Description (*)

Fixed the issue for getting only those media gallery images which are not disabled for a product in graphql request response.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34342

### Manual testing scenarios (*)

1. Checked when there are no images assigned to a product:
<img width="1722" alt="no_images_in_product" src="https://user-images.githubusercontent.com/93646392/147560520-4eb1bc17-0158-4659-86ad-ade30a39aa44.png">

2. Checked when both the images are disabled:
<img width="1769" alt="both_images_are_disabled" src="https://user-images.githubusercontent.com/93646392/147560577-1117c45e-55cf-41c4-8441-dc5a038fc90b.png">

3. Checked when both the images are enabled:
<img width="1683" alt="both_images_not_disabled" src="https://user-images.githubusercontent.com/93646392/147560631-13f8fefb-fa7b-42da-84c8-d26065f16931.png">

4. Checked when one image is enabled and one is disabled:
<img width="1693" alt="one_image_is_disabled" src="https://user-images.githubusercontent.com/93646392/147560668-003a47c8-ba76-48c0-a8d5-91d298101695.png">

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2025-12-16 06:56 UTC, engcom-Hotel commented
@magento run all tests

2025-12-17 12:28 UTC, engcom-Hotel commented
Hello @nidhigupta13-ey,

Thank your the contribution!

As the related issue has been categorised as a `feature request`, so we have sent an approval email to the PO. Meanwhile we are moving this PR on hold.

Thank you

2026-01-23 04:52 UTC, engcom-Hotel commented
Hello @nidhigupta13-ey,

We have received Product Owner approval for this pull request and will now proceed with further processing.

Thank you

@magento run all tests

2026-01-23 05:14 UTC, engcom-Hotel commented
@magento run all tests

2026-01-23 09:01 UTC, engcom-Hotel requested changes
Hello @nidhigupta13-ey,

Thank you for your contribution!

Please have a look into the below review comments:

1. The filtering logic is placed after the model is set but before `video_content` processing, which is inconsistent. If an entry is disabled, it should be filtered early, not mid-processing.
2. Some automated tests are failing due to the PR changes please fix those.
3. Add some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done#definition-of-done-1).

2026-01-23 09:01 UTC, engcom-Hotel commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Product/MediaGallery.php
> +                array_pop($mediaGalleryEntries);
Here `array_pop()` removes the last element of the array, not the element at `$key` which is actually disabled. 

If the disabled image is at index `0` and there are `5` images, this will incorrectly remove image at index `4`

2026-01-23 09:01 UTC, engcom-Hotel commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Product/MediaGallery.php
> +            if($mediaGalleryEntries[$key]['disabled'] == 1) {
**Recommendation:** Use `===` instead of `==`

2026-02-10 05:22 UTC, engcom-Hotel commented
Hello @nidhigupta13-ey,

Have you got a chance to look into this https://github.com/magento/magento2/pull/34897#pullrequestreview-3696461562?

Thank you

2026-02-26 04:52 UTC, engcom-Dash commented
@magento run all tests

2026-02-26 21:03 UTC, engcom-Dash commented
> Hello @nidhigupta13-ey,
> 
> Thank you for your contribution!
> 
> Please have a look into the below review comments:
> 
> 1. The filtering logic is placed after the model is set but before `video_content` processing, which is inconsistent. If an entry is disabled, it should be filtered early, not mid-processing.
> 2. Some automated tests are failing due to the PR changes please fix those.
> 3. Add some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done#definition-of-done-1).

@engcom-Hotel  @nidhigupta13-ey, since this PR has been pending for quite some time, I will take care of the review comments.

2026-02-26 21:07 UTC, engcom-Dash commented
@magento run all tests

2026-03-01 20:46 UTC, engcom-Dash commented
@engcom-Hotel I have addressed the suggested review comments. Could you please review the changes so we can proceed further with this PR.

2026-03-02 13:09 UTC, engcom-Hotel requested changes
Hello @engcom-Dash,

Thank you for making the changes!

A small review comment below, please look into this as well.

Thank you

2026-03-02 13:09 UTC, engcom-Hotel commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Product/MediaGallery.php
> +            if ((int)($entryData['disabled'] ?? 0) === 1) {
Use `isDisabled(): bool` as a proper service contract method.

2026-03-03 10:06 UTC, engcom-Dash commented
@magento run all tests

2026-03-03 16:26 UTC, engcom-Dash commented
@engcom-Hotel I have addressed the suggested review comments. Could you please review the changes so we can proceed further with this PR.

2026-03-05 06:34 UTC, engcom-Hotel approved these changes

2026-03-06 10:50 UTC, engcom-Bravo commented
@magento run all tests

2026-03-06 14:21 UTC, engcom-Bravo commented
Hi @nidhigupta13-ey,


Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Checked when there are no images assigned to a product:
- Checked when both the images are disabled:
- Checked when both the images are enabled:
- Checked when one image is enabled and one is disabled:



**Before:** :heavy_multiplication_x:

<img width="1440" height="636" alt="Screenshot 2026-03-06 at 4 08 41 pm" src="https://github.com/user-attachments/assets/05cd4a95-8554-4123-914a-cf2e2d1cba6e" />





**After:** :heavy_check_mark: 


<img width="1440" height="636" alt="Screenshot 2026-03-06 at 4 16 15 pm" src="https://github.com/user-attachments/assets/317cf7b3-1a7d-4f10-b49f-093c2ba38b3f" />



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2026-03-09 09:14 UTC, engcom-Dash commented
@magento run all tests

2026-03-09 16:16 UTC, engcom-Dash commented
The consistent failures in Functional CE, B2B,EE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

CE
Build1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34897/11eff1cff3a13dcfc6406224f534a885/Functional/allure-report-ce/index.html#categories
<img width="1197" height="446" alt="image" src="https://github.com/user-attachments/assets/fc72031b-4d19-42ac-a911-47acae53d68d" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34897/66384d65bb96a6cc5b9f00680099be84/Functional/allure-report-ce/index.html#categories
<img width="1149" height="234" alt="image" src="https://github.com/user-attachments/assets/a45dd2b2-fde7-4062-9805-b065a38df309" />

EE
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34897/f03e4688e655caad1fc6934b9765ada6/Functional/allure-report-ee/index.html#categories
<img width="1181" height="480" alt="image" src="https://github.com/user-attachments/assets/19a0366a-66f7-4353-b0c1-bf7a01f25dbf" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34897/472940904c6c4e285de3c60c5d06062b/Functional/allure-report-ee/index.html#categories
<img width="1171" height="314" alt="image" src="https://github.com/user-attachments/assets/0fd10831-3e89-49e5-9d4d-5de3e42db310" />


B2B
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34897/790b6132a8bb22c1f6d5b7fa20bc15c8/Functional/allure-report-b2b/index.html#categories
<img width="1168" height="498" alt="image" src="https://github.com/user-attachments/assets/d5c97ed7-7a54-481b-8ac4-5fbf580f6f45" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34897/0428e2d02ba3e1deb75d048925ef85c2/Functional/allure-report-b2b/index.html#categories
<img width="1184" height="396" alt="image" src="https://github.com/user-attachments/assets/944b38ac-1be6-45c6-821c-f9386cdf443c" />

Known Issue
AsyncOrderWithAsyncStockReservationTest [ACQE-9450](https://jira.corp.adobe.com/browse/ACQE-9450)
AssertSuccessMessageAppearsAfterAddingProductToCartThatContainsOutOfStockProductTest [ACQE-9359](https://jira.corp.adobe.com/browse/ACQE-9359)

Hence, Moving this PR to Merge In Progress

2026-03-27 13:51 UTC, merged