Add --skip-up-to-date option to setup:upgrade
magento/magento2 pull request #35116
Opened 2022-02-17 16:59 UTC by AntonEvers

### Description (*)

Add --skip-up-to-date option to setup:upgrade which skips schema and data install/update depending on setup:db:status.

### Related Pull Requests

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. `bin/magento setup:upgrade --skip-up-to-date --keep-generated`  should NOT RUN upgrades if DB is already up to date
2. Run mysql query `DELETE FROM `patch_list` WHERE `patch_name` = 'Magento\Swatches\Setup\Patch\Data\ConvertAdditionalDataToJson';`
3. `bin/magento setup:upgrade --skip-up-to-date --keep-generated`  should RUN upgrades because the DB is no longer up to date

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-02-17 17:08 UTC, AntonEvers commented
@magento run all tests

2022-02-24 12:02 UTC, AntonEvers commented
@magento run all tests

2022-02-24 15:31 UTC, AntonEvers commented
@magento run all tests

2022-03-01 07:27 UTC, fooman commented
Could the same end result be achieved like so

```
if (setup:db:status) {
    setup:upgrade
}
```
?

Without the need for an extra flag?

I believe that is what [Deployer Plus](https://github.com/jalogut/magento2-deployer-plus) has been doing for a few years now.

2022-03-02 14:14 UTC, AntonEvers commented
Hi @fooman,

It is different from what you describe.

```php
if (!setup:db:status) {
    setup:upgrade
} else {
    app:config:import
}
```

We will call that "deployer-plus".
We will call this PR, "no-db-upgrade"

Take a look at `Magento\Setup\Console\Command\UpgradeCommand:: execute()`.

| Method | deployer-plus | no-db-upgrade |
| :------- | --------------| --------|
| updateModulesSequence | No | Yes |
| validateSearchEngine | No | Yes |
| removeUnusedTriggers | No | Yes |
| app:config:import | Yes | Yes |

Especially **updateModulesSequence** is important here, I think you can live without **validateSearchEngine** and **removeUnusedTriggers**.

`\Magento\Setup\Model\Installer::updateModulesSequence` can be necessary to change the order of modules in `app/etc/config.php` after you add a dependency sequence in a module's `module.xml`. That might be needed after a code change in a module, when you introduce a new dependency, but no DB changes. 
You will need to change the order in which modules depend on each other. Without running setup:upgrade you will not run `\Magento\Setup\Model\Installer::updateModulesSequence` and you will not change the order of modules in config.php.
You do need to run `\Magento\Setup\Model\Installer::updateModulesSequence` but you do not need to run DB schema and data install/update commands in that case. And there we have no solution at the moment. An alternative would be to create a new CLI command which exclusively runs `\Magento\Setup\Model\Installer::updateModulesSequence` and run that together with app:config:import if you don't need module upgrades. I found this PR less complex.

2022-03-02 18:11 UTC, fredden commented
Updating the module sequence is a development task, not something that should be done during deployment. The deployment process should compile and deploy a known-state, not make configuration changes (ie, write to `app/etc/config.php`).

Deployer-plus actually doesn't run `setup:upgrade` at all (nor does Capistrano), instead it runs `setup:db-schema:upgrade` then `setup:db-data:upgrade`, but only if `setup:db:status` says that there are database changes required.

https://github.com/jalogut/magento2-deployer-plus/blob/a8c4432a68a4ac442541f250577e6049abaed52b/recipe/magento_2_2/database.php#L36-L41

https://github.com/davidalger/capistrano-magento2/blob/3d32c7d654bd9221f67e20c27fc4e62503bdd73d/lib/capistrano/tasks/deploy.rake#L86-L87

Perhaps the change that's needed here is to convert ece-tools to use `setup:db-schema:upgrade` and `setup:db-data:upgrade`  instead of `setup:upgrade`.

https://github.com/magento/ece-tools/blob/b4ea5e111aeadb6d1d06e4a9983288eb73bd91ca/scenario/deploy.xml#L105
https://github.com/magento/ece-tools/blob/b4ea5e111aeadb6d1d06e4a9983288eb73bd91ca/src/Step/Deploy/InstallUpdate/Update/Setup.php#L55
https://github.com/magento/ece-tools/blob/b4ea5e111aeadb6d1d06e4a9983288eb73bd91ca/src/Util/UpgradeProcess.php#L88

Do you have any information about what tasks are taking a long time when you run `setup:upgrade` locally? Perhaps those tasks can / should be optimised / fixed.

2022-03-02 21:20 UTC, fooman commented
@AntonEvers thanks for getting back to me. I believe a committed app/etc/config.php should help with the module order. If you run `bin/magento module:enable Fooman_Example` the sequence gets written to file. If for some reason the module sequence changed running  `bin/magento module:enable Fooman_Example && bin/magento module:enable Fooman_Example` will do the same.

However maybe this points to a need for a separate command to check module sequence?

2022-03-03 08:34 UTC, AntonEvers commented
@fooman absolutely, a committed config.php with the right sequence will also remove the need for running updateModulesSequence. My experience is that we cannot consistently rely on a manually updated config.php file, so an automated check will be useful. I am thinking about including the sequence check in the `setup:db:status` command.
After all `setup:db:status` should determine if you should run `setup:upgrade`. It would fit within that definition. Only the semantics are in the way because of the `:db:` part in `setup:db:status`. 
And it might be loosely backward incompatible to start checking config.php during that command as it might change deployment behavior. So indeed better to create a new command for it, or add it as an optional part of `setup:db:status` by use of a flag.

2022-03-11 10:56 UTC, BarnyShergold requested changes
@AntonEvers  Based on discussions on the internal ticket MCLOUD-8511 and that skipping setup:upgrade could cause other issues (such as not running recurring scripts) and that the solution would actually slow down deployments, can this PR be closed?

2022-03-30 14:06 UTC, hostep commented
@AntonEvers:

> My experience is that we cannot consistently rely on a manually updated config.php file, so an automated check will be useful. I am thinking about including the sequence check in the setup:db:status command.

This already exists, by the command `bin/magento module:config:status` (introduced in Magento 2.3.3 by https://github.com/magento/magento2/pull/22733 😉 ), just FYI

2022-04-01 13:22 UTC, AntonEvers commented
@hostep, @fooman and @BarnyShergold with the current code base I would say that it is not beneficial indeed to skip `setup:upgrade` after all. Because of @BarnyShergold 's reaction I evaluated all recurring scripts to see what we are dealing with. Here is my outcome:

| File | Responsibility | Expected Duration | Safe to Skip |
|:--- |:--- |:--- |:--- |
| `\Dotdigitalgroup\Email\Setup\Recurring` |  |  |  |
| `\Magento\ComposerRootUpdatePlugin\Setup\RecurringData` |  |  |  |
| `\Magento\GoogleShoppingAds\Setup\Recurring` |  |  |  |
| `\Magento\Amqp\Setup\Recurring ` |  |  |  |
| `\Magento\Bundle\Setup\Recurring ` |  |  |  |
| `\Magento\CatalogInventory\Setup\Recurring ` |  |  |  |
| `\Magento\CatalogUrlRewrite\Setup\Recurring ` |  |  |  |
| ` \Magento\Catalog\Setup\Recurring ` |  |  |  |
| `\Magento\ConfigurableProduct\Setup\Recurring ` |  |  |  |
| `\Magento\ConfigurableSampleData\Setup\RecurringData ` |  |  |  |
| `\Magento\Cron\Setup\Recurring ` |  |  |  |
| `\Magento\Customer\Setup\RecurringData ` |  |  |  |
| `\Magento\Indexer\Setup\Recurring ` |  |  |  |
| `\Magento\Integration\Setup\Recurring ` |  |  |  |
| `\Magento\MysqlMq\Setup\Recurring ` |  |  |  |
| `\Magento\ProductAlert\Setup\Recurring ` |  |  |  |
| `\Magento\Reports\Setup\Recurring` |  |  |  |
| `\Magento\SalesArchive\Setup\Recurring ` |  |  |  |
| `` |  |  |  |
| `` |  |  |  |
| `` |  |  |  |

2022-04-01 13:47 UTC, closed without merging