Updating Event Argument
magento/magento2 pull request #35144
Opened 2022-02-25 16:00 UTC by manavluhar

### Description (*)
Updating event argument for sales_order_state_change_before event

### Fixed Issues (if relevant)
1. Fixes magento/magento2#26789

### Manual testing scenarios (*)
1. place an observer on sales_order_state_change_before and try to get the data from the actual object

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-02-25 16:01 UTC, manavluhar commented
@magento run all tests

2022-02-28 10:41 UTC, manavluhar commented
@magento run Static Tests, Functional Tests B2B

2022-02-28 13:53 UTC, manavluhar commented
@magento run all tests

2022-03-01 07:22 UTC, fooman commented on app/code/Magento/Sales/Model/Service/OrderService.php
> +            ['order' => $this, 'transport' => $transport, 'transportObject' => $transport]
```suggestion
            ['order' => $this, 'transport' => $transport, 'order_object' => $order]
```
To address the concern in the reported issue the order object should be made available via the event.

2022-03-02 05:34 UTC, manavluhar commented
@magento run all tests

2022-03-02 06:45 UTC, manavluhar commented
@magento run all tests

2022-03-02 06:47 UTC, manavluhar commented
@magento run all tests

2022-03-02 07:38 UTC, manavluhar commented
@magento run Static Tests

2022-03-02 07:40 UTC, manavluhar commented
@magento run all tests

2022-03-03 13:28 UTC, manavluhar commented
@magento run all tests

2022-03-03 17:52 UTC, manavluhar commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2022-03-04 22:03 UTC, manavluhar commented
@magento run Functional Tests EE

2022-03-05 14:50 UTC, manavluhar commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2022-03-14 12:46 UTC, manavluhar commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2022-04-06 07:44 UTC, manavluhar commented
@magento run Functional Tests EE

2022-04-06 12:38 UTC, manavluhar commented
@magento run all tests

2022-04-06 20:36 UTC, manavluhar commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2022-04-07 17:10 UTC, manavluhar commented
@magento run Functional Tests CE

2022-04-08 17:08 UTC, manavluhar commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2022-04-08 20:05 UTC, manavluhar commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2022-04-12 19:15 UTC, manavluhar commented
@magento run all tests

2022-04-13 19:16 UTC, manavluhar commented
@magento run all tests

2022-04-13 19:18 UTC, manavluhar commented
@magento run all tests

2022-04-13 22:36 UTC, manavluhar commented
@fooman Can you please review this Pull Request again?

2022-04-13 22:37 UTC, manavluhar commented
@magento run all tests

2022-04-14 09:24 UTC, manavluhar commented
@fooman🙌 Can you please review this  PR?

2022-04-14 09:47 UTC, fooman commented
@manavluhar Code looks okay to me, but I am currently not part of the maintainer team which will need to also take a look. One thing which is not accurate is the comment

```
        /**
        * Event argument `transport` is @deprecated. Use `transportObject` instead.
        */
```

I do not see anything being deprecated so I would remove the comment completely.

2022-04-14 09:48 UTC, fooman requested changes

2022-04-14 09:48 UTC, fooman commented on app/code/Magento/Sales/Model/Service/OrderService.php
> +        */
```suggestion
```

2022-04-14 09:58 UTC, manavluhar commented
> @manavluhar Code looks okay to me, but I am currently not part of the maintainer team which will need to also take a look. One thing which is not accurate is the comment
> 
> ```
>         /**
>         * Event argument `transport` is @deprecated. Use `transportObject` instead.
>         */
> ```
> 
> I do not see anything being deprecated so I would remove the comment completely.

Thank you for the review Sir, can you please approve your review so this pull request can proceed further?

2022-04-14 09:59 UTC, manavluhar commented
@magento run all tests

2022-05-13 09:47 UTC, manavluhar commented
@magento run all tests

2022-05-13 09:52 UTC, manavluhar commented
@fooman can you please review this pr?

2022-05-13 11:33 UTC, fooman commented
@manavluhar looks good to me but you would need someone from the maintainer group give the go-ahead to move this PR along.

2022-05-13 11:34 UTC, fooman approved these changes

2022-05-16 06:40 UTC, manavluhar commented
@magento run all tests

2022-05-16 16:33 UTC, manavluhar commented
@magento run all tests

2022-05-18 06:13 UTC, engcom-Lima commented
@magento run Functional Tests B2B, Integration Tests

2022-05-18 12:48 UTC, engcom-Lima commented
@magento run Integration Tests

2022-06-06 13:49 UTC, engcom-Lima commented
@magento give me 2.4-3-p1 B2b instance

2022-06-06 14:41 UTC, engcom-Lima commented
@magento give me 2.4.3-p1 with B2b instance

2022-06-07 14:45 UTC, engcom-Charlie commented
@magento run all tests

2022-06-09 08:42 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2022-06-10 11:27 UTC, engcom-Charlie commented
Hi @manavluhar,

Thank you for your contribution!

**In order to reproduce the issue and test the solution, I have implemented below code base.:**

1. Added sales_order_state_change_before“ event-observer entry in app/code/Magento/Sales/etc/events.xml
2. Created custom observer for above event
3. Created new custom controller and load Order and OrderService object in it. Load the order and called $orderService->setState function.
4. Added debugger points in controller and in observer, in order to reproduce the issue.
5. Found that we are not getting Order object’s data. Hence issue is reproducible.
![image](https://user-images.githubusercontent.com/51680850/173054766-3f69b08b-52ad-4729-aba6-91b1fe558f7d.png)

:heavy_check_mark: QA Passed
6. Added the PR changes and observed that after PR solution we are getting Order object data correctly.
![image](https://user-images.githubusercontent.com/51680850/173054578-c8b37192-ed96-448d-8c0e-591a5bf316b8.png)

Also tested all states of order from order grid in admin. 

Since the issue is fix and the build is green moving it for merging.

Thank you!

2022-06-11 14:22 UTC, merged