Set default collation to utf8mb4
magento/magento2 pull request #35174
Opened 2022-03-10 10:28 UTC by sippsolutions

### Description (*)
MySQL 8 interprets utf8 to utf8mb3, which is deprecated:
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-24.html
https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2022-03-10 10:28 UTC, sippsolutions commented
@magento run all tests

2022-03-17 15:06 UTC, Den4ik commented
Hi @sippsolutions
Thanks for this PR.
Could you please fix failed tests

2022-05-22 20:47 UTC, sippsolutions commented
@Den4ik did you see my changes? the tests are intended to fail.

2022-05-24 09:10 UTC, Den4ik commented
Hi @sippsolutions 
Sorry for delay. I don't see any commits after my message.
Unit and Static tests failed on changed file

2022-05-25 07:02 UTC, sippsolutions commented
Hi @Den4ik,
the failing database compare tests _cannot_ be fixed as they state that there are differences in the database structure.
If you look at the changes I made you can see that I changed the default collation for database tables. It is _intended_ that the database structure differs.

2022-05-25 07:07 UTC, Den4ik commented
Hi @sippsolutions 
I didn't say about db tests. Only static and unit tests failed for changed file.
I believe that some one from core team could help with this fixes off you don't have time for fix that

2022-06-13 11:49 UTC, sippsolutions commented
@Den4ik that would be awesome :)

2022-09-12 23:51 UTC, Den4ik commented
@sippsolutions Could you resolve merge conflict?

2022-09-14 19:53 UTC, hostep commented
This might be a bit more complex than what it sounds like.

See https://github.com/OpenMage/magento-lts/pull/1036 where an attempt is made to apply a similar change to Magento 1, it contains a bunch of interesting information in the comments.

2023-08-08 10:22 UTC, Quazz commented
https://github.com/magento/magento2/blob/0a834cce01c3d924d450c9a71123d9ac6de68b62/lib/internal/Magento/Framework/DB/Ddl/Table.php#L238

Would also need changes, otherwise you'll get mismatched collations which will kill your performance.

2023-10-16 06:58 UTC, engcom-Hotel commented
@magento create issue

2023-10-16 07:00 UTC, engcom-Hotel requested changes
Hello @sippsolutions,

Thanks for the contribution!

In order to process further this PR please resolve the conflicts.

Meanwhile, we are moving this PR `On Hold`.

Thanks

2023-10-25 09:16 UTC, engcom-Hotel commented
Hello @sippsolutions,

Have you got chance to check this [comment](https://github.com/magento/magento2/pull/35174#pullrequestreview-1679245011)?

Thanks

2023-10-30 12:09 UTC, sippsolutions commented
@engcom-Hotel done

2023-10-31 17:16 UTC, engcom-Hotel commented
@magento give me 2.4-develop instance

2023-10-31 17:16 UTC, engcom-Hotel commented
@magento run all tests

2023-11-02 06:56 UTC, engcom-Hotel requested changes
Hello @sippsolutions,

Thanks for the contribution!

Please fix the integration tests failures. It seems they are due to the PR changes.

Thanks

2023-11-07 07:26 UTC, engcom-Hotel commented
@sippsolutions we are picking up this PR for fixes.

2023-11-07 09:36 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-07 10:51 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-07 13:15 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-08 06:20 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-13 09:27 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-13 12:59 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-14 08:26 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-14 11:23 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-15 06:20 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-15 10:12 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-15 12:11 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-11-15 14:01 UTC, engcom-Hotel commented
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Magento Health Index, Semantic Version Checker, Static Tests, Unit Tests, WebAPI Tests

2023-11-16 07:01 UTC, engcom-Hotel commented
@magento run Static Tests

2023-11-16 08:31 UTC, engcom-Hotel commented
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Semantic Version Checker, Unit Tests, WebAPI Tests

2023-11-16 10:23 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2023-11-17 06:53 UTC, engcom-Hotel commented
@magento run WebAPI Tests

2023-11-17 09:47 UTC, engcom-Hotel commented
The failed tests seem falky to me. Please refer the below screenshot for reference:

**Functional Tests CE**
![image](https://github.com/magento/magento2/assets/51681618/e11f33c3-fea8-4783-92d9-4b7775e9f138)

![image](https://github.com/magento/magento2/assets/51681618/25120217-f15f-40ea-a7b8-5d6fef6867ab)

**Functional Tests B2b**
![image](https://github.com/magento/magento2/assets/51681618/cb5171db-60ea-4c4e-bc6a-bd7be6d3f242)

![image](https://github.com/magento/magento2/assets/51681618/46d09485-0a73-45a4-a01c-785b11032df1)

**Functional Tests EE**
![image](https://github.com/magento/magento2/assets/51681618/14f4a489-3000-4ab2-9f2c-475ef1676b48)

![image](https://github.com/magento/magento2/assets/51681618/c129eecb-5d37-45eb-b98b-bbd6339785a0)

For the `Database Compare` test failure we need to raise an approval ticket. Hence moving this PR further.

Thanks

2023-12-06 08:46 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2023-12-06 12:42 UTC, Den4ik commented
@engcom-Hotel failed db tests related to changes. I'll check it locally

2023-12-10 21:22 UTC, Den4ik commented
@magento run Functional Tests CE, Functional Tests EE

2023-12-18 08:43 UTC, engcom-Hotel commented
Hello @Den4ik,

Are you still working on this PR for Database compare test failures?

Moving this PR to the changes requested.

Thanks

2023-12-26 14:19 UTC, andrewbess commented
Hello @Den4ik @engcom-Hotel 

The `Database Compare` tests work good.
It compares database structure before fixes and after it.
So, the DB structure will be different after these fixes.

@engcom-Hotel please create approval ticket in the internal Jira to move it further.

Thank you in advance.

2023-12-26 16:20 UTC, andrewbess commented
Hello @sippsolutions 
Thank you for your collaboration.
Changes look good for me ✔️.
Let's wait for passing functional tests.

2023-12-26 16:24 UTC, Den4ik approved these changes
Functional tests passed in previous runs.
Checked DB tests and it looks ok

2023-12-27 16:10 UTC, andrewbess approved these changes
Approved

2023-12-27 16:12 UTC, andrewbess commented
@magento run all tests

2024-01-02 13:36 UTC, engcom-Delta commented
@magento run all tests

2024-01-25 11:43 UTC, engcom-Hotel commented
@magento run all tests

2024-01-30 07:13 UTC, engcom-Hotel commented
@magento run Functional Tests CE, Functional Tests B2B

2024-01-30 10:03 UTC, engcom-Bravo commented
Hi,

Internal team has started working on this issue. Most of the code changes are complete. We are trying to get conclusion over DBC failure and are in discussion with PO. 

Thanks.

2024-02-01 06:51 UTC, engcom-Hotel commented
As per this comment https://github.com/magento/magento2/pull/35174#issuecomment-1916483549, we are moving this issue `On hold`.

We will update you here about the progress.

Thanks

2024-06-03 08:16 UTC, engcom-Bravo commented
Hi,

All the required changes are done and working with Engineering Manager to speed up. Delivery is aligned for Oct Release.

Thanks.

2024-09-23 19:25 UTC, hostep commented
@engcom-Bravo: what would be the status here? Is everything still in order for the October release? (I guess that means Magento 2.4.8-beta1?)

2024-10-08 13:52 UTC, engcom-Bravo commented
Hi @hostep @sippsolutions,

Unfortunately this did not make it to 2.4.8-beta1 release. The implementation is close to completion now and will be followed by extensive testing based on its large scope. We will keep you updated on the progress. Appreciate your patience!

Thanks.

2024-10-15 07:47 UTC, glo71317 requested changes
Need to perform the upgrade with pr changes from Adobe commerce lower version

2024-10-15 07:47 UTC, glo71317 commented on dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/revisions/old_diff/InstallSchema.php
> +// phpcs:ignoreFile
Why we are ignoring file, try to resolve this

2024-10-15 07:47 UTC, glo71317 commented on dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule1/revisions/base_update/InstallSchema.php
Why we are ignoring file, try to resolve this

2024-10-24 16:03 UTC, glo71317 commented
> Need to perform the upgrade with pr changes from Adobe commerce lower version

Please ignore my comment above. This was intended for internal team. Apologies for any confusion that it may have caused.

2024-10-31 11:59 UTC, merged

2025-02-06 15:41 UTC, ksenia-zlotin commented
@engcom-Bravo Is there an update on a target release version for this change?