Added missing interface for Quote\Address\Item
magento/magento2 pull request #35296
Opened 2022-04-13 08:34 UTC by ilnytskyi

### Description (*)

When working on customization that include both quote_item and quote_address_item (e.g. multishipping) it's impossible to work under one interface. `\Magento\Quote\Model\Quote\Item\AbstractItem` must be used instead. So quote_address_item can be also marked as `\Magento\Quote\Api\Data\CartItemInterface`
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-04-13 08:34 UTC, ilnytskyi commented
@magento run all tests

2022-04-13 20:45 UTC, manavluhar requested changes
Hey, @ilnytskyi I doubt about the approval of this Pull Request, Also to take this further, you must need to update your PR by implementing the needful methods, which comes under \Magento\Quote\Api\Data\CartItemInterface. You can refer to the implementation at \Magento\Quote\Model\Qoute\Item.

2024-12-05 14:37 UTC, engcom-Dash commented
> Hey, @ilnytskyi I doubt about the approval of this Pull Request, Also to take this further, you must need to update your PR by implementing the needful methods, which comes under \Magento\Quote\Api\Data\CartItemInterface. You can refer to the implementation at \Magento\Quote\Model\Qoute\Item.

@ilnytskyi: Thanks for your contributions! Could you please address this review comment? Also, if possible, please elaborate on the issue in more detail; that would be appreciated. Thanks.

2024-12-13 10:12 UTC, engcom-Dash commented
> > Hey, @ilnytskyi I doubt about the approval of this Pull Request, Also to take this further, you must need to update your PR by implementing the needful methods, which comes under \Magento\Quote\Api\Data\CartItemInterface. You can refer to the implementation at \Magento\Quote\Model\Qoute\Item.
> 
> @ilnytskyi: Thanks for your contributions! Could you please address this review comment? Also, if possible, please elaborate on the issue in more detail; that would be appreciated. Thanks.

Hello @ilnytskyi,

This is a reminder: Could you please take a look at this https://github.com/magento/magento2/pull/35296#issuecomment-2520499912

Thanks.

2025-01-02 11:07 UTC, engcom-Dash commented
Hello @ilnytskyi,

This is a reminder: Could you please take a look at this https://github.com/magento/magento2/pull/35296#issuecomment-2520499912

Thanks.

2025-01-10 08:41 UTC, engcom-Dash commented
Closing this PR as it has not been updated for a while. Please feel free to reopen it if needed.

2025-01-10 08:41 UTC, closed without merging