[35302] Fixed error while running  `sales_clean_orders cron
magento/magento2 pull request #35303
Opened 2022-04-13 15:30 UTC by Usik2203

### Description (*)

This PR fixes  `SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (magento2.salesrule_customer, CONSTRAINT SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID FOREIGN KEY (rule_id) REFERENCES salesrule (rule_id) ON DELETE CASCADE), query was: INSERT INTO salesrule_customer () VALUES ()` error which was reported in https://github.com/magento/magento2/issues/35302 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35302

### Actual result
I don't see reported error 
<img width="570" alt="Screenshot 2022-04-13 at 18 29 17" src="https://user-images.githubusercontent.com/13517181/163216179-c64626fb-2446-4c90-bafa-7ba7f4d2c2f4.png">

2022-04-13 15:31 UTC, Usik2203 commented
@magento run all tests

2022-04-14 06:36 UTC, ihor-sviziev requested changes
Hi @Usik2203,
Could you please cover your changes with automated test?

2022-04-14 06:37 UTC, ihor-sviziev commented
This issue looks pretty critical, so I put priority P2

2022-04-22 11:12 UTC, closed without merging

2022-04-22 11:52 UTC, ihor-sviziev commented
Why was it closed?

2022-04-22 12:00 UTC, Usik2203 commented
Hello @ihor-sviziev 
I noticed merge contflict for my PR after checking i see that changes already was delivered by next commit https://github.com/magento/magento2/commit/0a5c099d9036a403a5660fdd7605ef5b110136cc 
Thank you!

2022-04-22 12:17 UTC, ihor-sviziev commented
@Usik2203 thx for the clarification!