Fix Magento Bulk API fpr PUT / DELETE requests
magento/magento2 pull request #35347
Opened 2022-04-21 10:16 UTC by nuzil

### Description (*)
Since Magento 2.4.4 and 2.4.3-p2 releases, whole processing of BULK API requests for PUT and DETELE is not possible anymore.

This Pull requests fixes this issue.

### Fixed Issues (if relevant)
Issue is the following: 
If you will try to execute any Bulk API requests by using PUT or DELETE methods, for endpoints which contain parameter in URL's. Example: 

`{{URL}}rest/async/bulk/V1/products/bySku`

Then request will throw an error: 

```
[2022-04-20 05:56:43] report.CRITICAL: TypeError: Argument 1 passed to Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver::resolveBulkItemParams() must be of the type array, string given, called in /app/anpwi2ppmb6vw/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php on line 128 and defined in /app/anpwi2ppmb6vw/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php:182
```

### Manual testing scenarios (*)
1. Execute any Rest Api Buld request. For example for endpoint: `{{URL}}rest/async/bulk/V1/products/bySku`.
2. You have to receive 200 code back.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-04-21 10:18 UTC, nuzil commented
@magento run all tests

2022-04-22 05:59 UTC, Den4ik commented
@magento run WebAPI Tests

2022-04-22 10:57 UTC, Den4ik requested changes
@nuzil Thanks for your work. Fix work perfectly.
Do you have time for adding unit tests?

2022-04-25 09:30 UTC, Den4ik approved these changes
@sidolov I believe that we can deliver it without tests or may be some one from Magento Core has time for implementing the tests

2022-04-25 09:31 UTC, Den4ik commented
**PS** QA passed

2022-04-26 11:39 UTC, engcom-Hotel commented
@magento create issue

2022-04-27 06:33 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE

2022-04-27 07:10 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE

2022-04-27 10:13 UTC, engcom-Alfa commented
@magento run Functional Tests B2B, Functional Tests EE

2022-04-27 11:49 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

**Preconditions:**

1. Install the fresh Magento 2.4-develop instance.
2. Have a few products already created in the instance

**Manual testing scenario:**

1. Execute the bulk PUT request `{{ServerEndpoint}}/rest/async/bulk/V1/products` with below payload.
`[
    {
        "product": {
            "sku": "SimpleProd01",
            "name": "SimpleProd01"
        }
    },
    {
        "product": {
            "sku": "SimpleProd02",
            "name": "SimpleProd02"
        }
    }
]`
2. Validate the response has a proper 202 response code with data acknowledged.
 
3. Execute the bulk DELETE request `{{ServerEndpoint}}/rest/async/bulk/V1/products/bySku` with below payload.
`[
    {
        "sku": "SimpleProd01"
    }
]`

4. Validate the response has a proper 202 response code with data acknowledged.


**Before:** :heavy_multiplication_x: Responded with error 500 message
![image](https://user-images.githubusercontent.com/51679138/165511706-6f965912-412e-489a-86b0-242915733ee0.png)


**After:** :heavy_check_mark: Responded with _202 Accepted_ code and data
![image](https://user-images.githubusercontent.com/51679138/165511598-e8faf53e-a8fe-418a-a5ac-c9e4e4df829f.png)



It is specific to API calls and has no more additional testing to be done as part of regression.

2022-04-28 08:26 UTC, nuzil commented
Hi @Den4ik 
My initial idea was to make at least a patch. (there are no branch for patches yet).
We can add Api-functional tests, I guess they will be more valuable.
I just cannot guarantee that I will do it fast

2022-04-30 06:37 UTC, Den4ik commented
> Hi @Den4ik 
> 
> My initial idea was to make at least a patch. (there are no branch for patches yet).
> 
> We can add Api-functional tests, I guess they will be more valuable.
> 
> I just cannot guarantee that I will do it fast

@nuzil I'm agree with you and waiting branch for patches too.
@sidolov  when we have branch for mqp patches for 2.4?

2022-05-11 13:42 UTC, engcom-Charlie commented
Hi @nuzil & @Den4ik,

Thank you for your contribution!

I will look into the Web API test creation for this PR.

Thank you!

2022-05-12 12:04 UTC, RonanCapitaine commented
Hi @engcom-Charlie and @nuzil 

I tested this patch on my side on a 2.4.3-p2 and it's not working.
If you check the code, variable is just move. The logical is the same and the bug is still here :

```
TypeError: Argument 1 passed to Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver::resolveBulkItemParams() must be of the type array, string given, called in /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php on line 129 and defined in /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php:184
Stack trace:
#0 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php(129): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolveBulkItemParams('bySku', 'Magento\\Catalog...', 'save')
#1 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/module-webapi-async/Controller/Rest/AsynchronousRequestProcessor.php(100): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolve()
#2 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\WebapiAsync\Controller\Rest\AsynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#3 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#5 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/fastly/magento2/Model/FrontControllerPlugin.php(128): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /Users/rcapitaine/Workspace/Sites/primeauvelo/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#9 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /Users/rcapitaine/Workspace/Sites/primeauvelo/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#11 /Users/rcapitaine/Workspace/Sites/primeauvelo/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#12 /Users/rcapitaine/Workspace/Sites/primeauvelo/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#13 {main}
```

Thank you,
Ronan

2022-05-12 15:45 UTC, engcom-Charlie commented
Hi @RonanCapitaine,

As mentioned in above [comment](https://github.com/magento/magento2/pull/35347#issuecomment-1110906431), the solution is working fine. Kindly cross check once again.

If issue still exists for you, kindly provide your steps to reproduce it.

Thank you!

2022-05-12 15:56 UTC, RonanCapitaine commented
Hi @engcom-Charlie,

QA passed probably on 2.4-develop on your side.
But it seems not working on 2.4.3-p2. I used the exact same steps like you to reproduce it.

The description of the bug is : `Since Magento 2.4.4 and 2.4.3-p2 releases, whole processing of BULK API requests for PUT and DETELE is not possible anymore.` So I guess 2.4.3-p2 has to be considered ?

Thank you for your help!

2022-05-12 21:10 UTC, RonanCapitaine commented
Eratum, it seems to work in 2.4.3-p2 if we also applied patch MDVA-40896 
[MDVA-40896_EE_2.4.3_COMPOSER_v1.patch.txt](https://github.com/magento/magento2/files/8682603/MDVA-40896_EE_2.4.3_COMPOSER_v1.patch.txt)

Thank you guys

2022-05-18 14:49 UTC, engcom-Charlie commented
Working on some other task, will resume the work on Web API test creation soon.

Thank you!

2022-05-25 13:09 UTC, engcom-Charlie commented
This issue has been taken care in internal [JIRA](https://jira.corp.magento.com/browse/ACP2E-763) ticket. Hence closing the PR.

Thank you!

2022-06-05 10:11 UTC, hostep commented
[Commits with ACP2E-763 seems to have landed recently](https://github.com/magento/magento2/search?q=ACP2E-763&type=commits), unfortunately no clean merge commit was created.

So this PR can probably get closed now?

2022-06-06 06:46 UTC, engcom-Charlie commented
As mentioned in above [comment](https://github.com/magento/magento2/pull/35347#issuecomment-1137218449) This issue has been taken care in internal [JIRA](https://jira.corp.magento.com/browse/ACP2E-763) ticket. Hence closing this PR now.

Thank you!

2022-06-06 07:27 UTC, closed without merging

2023-01-26 21:33 UTC, dodyryda reviewed
nope..