Fix Passing null to parameter #1 ($string) of type string
magento/magento2 pull request #35441
Opened 2022-05-06 14:18 UTC by nazarklovanych

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35380

### Manual testing scenarios (*)

Install fresh (vanilla) Magento instance
1.1 composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <install-directory-name>
1.2 run install with AMQP: e.g. bin/magento setup:install --base-url="http://magento-ce.test/" --base-url-secure="https://magento-ce.test/" --use-secure-admin=1 --use-rewrites=1 --use-secure=1 --db-host="127.0.0.1" --db-name=magento_ce --db-user=root --db-password=root --backend-frontname=admin --admin-firstname=admin --admin-lastname=admin --admin-email=admin@magento-ce.test --admin-user=admin --admin-password=admin123 --language=en_US --currency=EUR --timezone=Europe/Berlin --amqp-host=localhost --amqp-port=5672 --amqp-user=admin --amqp-password=admin --amqp-virtualhost=magento_ce --elasticsearch-host=localhost --elasticsearch-port=9207 --session-save=redis --session-save-redis-host=localhost --session-save-redis-port=6379 --session-save-redis-db=0 --cache-backend=redis --cache-backend-redis-server=localhost --cache-backend-redis-port=6379 --cache-backend-redis-db=1 --page-cache=redis --page-cache-redis-server=localhost --page-cache-redis-port=6379 --page-cache-redis-db=2 --cleanup-database
Start MQ consumer like: bin/magento queue:consumer:start async.operations.all

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-05-06 14:19 UTC, nazarklovanych commented
@magento run all tests

2022-05-11 10:04 UTC, karyna-tsymbal-atwix commented
Hello @nazarklovanych
Could you please fix failed static tests?
Thank you in advance.

2022-05-13 08:12 UTC, nazarklovanych commented
@magento run all tests

2022-05-13 12:02 UTC, nuzil commented
Great stuff! Thanks :-)

2022-05-18 19:27 UTC, ishakhsuvarov commented
@magento run all tests

2022-05-19 08:18 UTC, glo71317 commented
@magento run Functional Tests CE

2022-05-19 10:48 UTC, glo71317 commented
@magento run Functional Tests CE

2022-05-19 12:17 UTC, glo71317 commented
@magento run Functional Tests CE

2022-05-19 15:13 UTC, ishakhsuvarov approved these changes

2022-06-06 10:29 UTC, engcom-Alfa commented
Hi @[nazarklovanych](https://github.com/nazarklovanych), @Den4ik and @ishakhsuvarov Thanks for your contribution and collaboration.
We have reproduced the issue using below steps:

**Pre-Conditions:**
1. Should have PHP 8.1 running.
2. Should have RabbitMQ installed and enabled.
3. Should have Redis installed and enabled.

**Steps:**
1. Install fresh (vanilla) Magento instance using a command: `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <install-directory-name>`
2. Run install with AMQP: e.g. `bin/magento setup:install --base-url="http://magento-ce.test/" --base-url-secure="https://magento-ce.test/" --use-secure-admin=1 --use-rewrites=1 --use-secure=1 --db-host="127.0.0.1" --db-name=magento_ce --db-user=root --db-password=root --backend-frontname=admin --admin-firstname=admin --admin-lastname=admin --admin-email=admin@magento-ce.test --admin-user=admin --admin-password=admin123 --language=en_US --currency=EUR --timezone=Europe/Berlin --amqp-host=localhost --amqp-port=5672 --amqp-user=admin --amqp-password=admin --amqp-virtualhost=magento_ce --elasticsearch-host=localhost --elasticsearch-port=9207 --session-save=redis --session-save-redis-host=localhost --session-save-redis-port=6379 --session-save-redis-db=0 --cache-backend=redis --cache-backend-redis-server=localhost --cache-backend-redis-port=6379 --cache-backend-redis-db=1 --page-cache=redis --page-cache-redis-server=localhost --page-cache-redis-port=6379 --page-cache-redis-db=2 --cleanup-database`
3. Above 2 commands will successfully execute, and then follow by the next command: `bin/magento queue:consumer:start async.operations.all`
4. Validate the outcome of the command

**Observation:**
We are getting the error as mentioned expected issue shown in below screenshot.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/51679138/172143741-d9c4488c-d7d2-4426-abf4-821693c77225.png">

In order to take the ticket thru further process to merge, we have to re-test with the file changes in this PR. So, as we can see there are **Merge conflicts** in the PR branch, **kindly resolve the merge conflicts**.
Thanks in advance!

2022-06-06 10:29 UTC, engcom-Alfa requested changes
Because of the [above-comment](https://github.com/magento/magento2/pull/35441#issuecomment-1147299905), requested for changes

2022-06-07 14:31 UTC, engcom-Charlie commented
Hi @engcom-Alfa,

I have merged latest 2.4-develop into this PR branch and resolved all the conflicts. 

You can proceed with testing.

Thank you!

2022-06-20 13:57 UTC, engcom-Alfa commented
@magento run all test

2022-06-20 14:00 UTC, engcom-Alfa commented
@magento run all tests

2022-06-20 14:05 UTC, engcom-Alfa commented
:heavy_check_mark: QA Passed

Executed with the steps as shown in [above-comment](https://github.com/magento/magento2/pull/35441#issuecomment-1147299905).

**Before:** :heavy_multiplication_x: We were getting an error as mentioned in the same [above-comment](https://github.com/magento/magento2/pull/35441#issuecomment-1147299905).

**After:** :heavy_check_mark: Consumer stars running without any errors as such.

No additional regression testing required to be added since it is relevant to the command failure fix with particular PHP version.

2022-06-21 07:23 UTC, engcom-Alfa commented
@magento run Functional Tests EE

2022-06-22 05:36 UTC, engcom-Alfa commented
@magento run Functional Tests EE

2022-06-22 12:58 UTC, engcom-Alfa commented
Even after multiple tried "Functional Tests EE" job is getting failed! Hence moving the PR to _Extended Testing_.

2022-06-22 13:06 UTC, engcom-Charlie commented
@magento run Functional Tests EE

2022-06-23 07:35 UTC, engcom-Charlie commented
As the build is successful now, moving this PR to Merge in Progress.

Thank you!

2022-08-08 00:15 UTC, merged