Admin user can call arbitrary Module class's constructor via Cart Pri…
magento/magento2 pull request #35588
Opened 2022-06-07 13:55 UTC by SergeyP18

…ce Rule #35135

Redefined the check of the using class

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-06-23 12:00 UTC, ihor-sviziev commented
Hi @SergeyP18,
You created 2 PRs with different list of changes for fixing the same issue - https://github.com/magento/magento2/pull/35588 and https://github.com/magento/magento2/pull/35589.

Could you explain which one we should review?

2023-05-11 10:34 UTC, engcom-Hotel requested changes
Hello @SergeyP18,

Thanks for the contribution!

After looking into the code changes, it seems that the issue is fixed and merged with the 2.4-develop branch. Can you please try to resolve the conflicts, so that we can move further with this PR?

Thanks

2024-09-16 10:07 UTC, engcom-Dash commented
Hello @SergeyP18, 

Thank you for your contribution!

Can you please resolve the conflicts in order to proceed further.

Thank you!

2024-09-30 12:56 UTC, engcom-Dash commented
Closing this PR due to no response to the last [comment](https://github.com/magento/magento2/pull/35588#issuecomment-2352496328). Feel free to reopen it.

2024-09-30 12:56 UTC, closed without merging