Format category url_key and url_path attributes to the correct pattern on rest api
magento/magento2 pull request #35605
Opened 2022-06-10 19:41 UTC by texboy

### Description (*)
Added code to format url key and path when creating a category via rest api.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35577

### Manual testing scenarios (*)

1. Call the REST API Endpoint to create a new Category: (with a valid authorization)
POST https://{shop-url}/rest/V1/categories
````
{
	"category": {
		"parent_id": 2,
		"name": "NewTest Cat (100)",
		"is_active": true,
		"include_in_menu": true,
		"custom_attributes": [
			{
				"attribute_code": "url_key",
				"value": "new test Cat (100)!"
			}
		]
	}
}
````
2. The response should contain the url_key with no special characters and a normalized the string:
````
 {
            "attribute_code": "url_key",
            "value": "new-test-cat-100"
        },
        {
            "attribute_code": "url_path",
            "value": "new-test-cat-100"
        }
````

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-06-10 19:42 UTC, texboy commented
@magento run Unit Tests

2022-06-10 19:42 UTC, texboy commented
@magento run all tests

2022-06-13 12:52 UTC, texboy commented
@magento run Static Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

2022-06-14 17:26 UTC, texboy commented
@magento run all tests

2022-06-14 20:20 UTC, ihor-sviziev requested changes
Hi @texboy,
Your solution looks like a workaround for the issue. The reason is that it actually works fine in the admin, and there definitely a code that should handle it.
Could you please debug and analyze how the url key and url path are getting processed there?
PS: solution for the url key looks ok, but not for the url path, as path also contains the suffix and even the parent category paths

2022-06-15 12:20 UTC, texboy commented
@magento run Integration Tests

2022-06-15 14:11 UTC, texboy commented
@magento run Integration Tests

2022-10-20 17:41 UTC, ishakhsuvarov commented
Closing this PR for now as it did not pass code review successfully and has not been upodated since. 

Please feel free to reopen should you still want to continue working on this.

2022-10-20 17:41 UTC, closed without merging