Resolve product price rounding issue when tax applied
magento/magento2 pull request #35730
Opened 2022-07-06 12:35 UTC by ravi-chandra3197

### Description (*)

 Resolve product price rounding issue when tax applied #18025
### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#18025: 

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-07-06 12:37 UTC, ravi-chandra3197 commented
@magento run all tests

2022-11-15 09:19 UTC, ravi-chandra3197 commented
@magento run all tests

2025-12-02 17:41 UTC, engcom-Hotel commented
@magento run all tests

2025-12-03 06:46 UTC, engcom-Hotel requested changes
Hello @ravi-chandra3197,

Thank you for the contribution!

Please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1). Also fix the indentation of the code.

Also look into the below review comment.

2025-12-03 06:46 UTC, engcom-Hotel commented on app/code/Magento/Tax/Model/Calculation/AbstractCalculator.php
> +
In the updated logic we assigning  `$roundPrice = $price;` in line number 411 and calling `$this->calculationTool->round($roundPrice);` on `$roundPrice` without having `$delta` into it. 

This might be happen that delta is never included in the rounding calculation.

2025-12-19 05:30 UTC, engcom-Charlie commented
@magento run all tests

2025-12-19 10:04 UTC, engcom-Charlie commented
@magento run all tests

2025-12-19 15:54 UTC, engcom-Charlie commented
@magento run all tests

2025-12-19 15:57 UTC, engcom-Charlie commented
> Hello @ravi-chandra3197,
> 
> Thank you for the contribution!
> 
> Please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1). Also fix the indentation of the code.
> 
> Also look into the below review comment.

@engcom-Hotel, I have implemented the review comments also unit test is present for the tax calculation,  I have fixed the failed one also fixed all the static test failure. Moving it to Review.

2025-12-21 11:12 UTC, engcom-Charlie commented
@magento run Integration Tests, Semantic Version Checker, Static Tests, Unit Tests, WebAPI Tests

2025-12-22 04:15 UTC, engcom-Charlie commented
@magento run all tests

2025-12-22 06:30 UTC, engcom-Charlie commented
Fixed testRenderAmountMinimalProductWithTierPricesShouldShowMinTierPriceWithTaxes integration test, requesting for review.

2025-12-22 07:39 UTC, engcom-Hotel approved these changes

2025-12-23 09:40 UTC, engcom-Bravo commented
@magento run all tests

2025-12-23 12:20 UTC, engcom-Bravo commented
Hi @ravi-chandra3197,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to Reproduce**

1.  Set _Configuration > Tax > Calculation Settings_ to following:
![tax_calculation_settings](https://user-images.githubusercontent.com/5977769/45406384-682dde00-b677-11e8-85ec-e1400d2bc6ec.png)
2. Set  _Configuration > Tax > Price Display Settings_ to _Including Tax_



**Before:** :heavy_multiplication_x: 


<img width="1316" height="579" alt="Screenshot 2025-12-23 at 3 12 36 pm" src="https://github.com/user-attachments/assets/4c980216-0e52-4be4-8f69-fd5149ccb22d" />



**After:** :heavy_check_mark: 



<img width="1316" height="579" alt="Screenshot 2025-12-23 at 3 16 07 pm" src="https://github.com/user-attachments/assets/98e4a6be-b11d-4223-a6ee-237a2ab4895a" />





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-12-26 10:15 UTC, engcom-Charlie commented
@magento run all tests

2025-12-29 05:58 UTC, engcom-Charlie commented
@magento run all tests

2025-12-29 12:08 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Integration Tests, WebAPI Tests

2025-12-29 14:48 UTC, engcom-Charlie commented
The latest build is successful, hence moving this PR to Merge in Progress.

<img width="941" height="562" alt="image" src="https://github.com/user-attachments/assets/1bd79015-2cb6-403f-bd50-015327ed6b84" />

2026-01-09 08:51 UTC, merged