feat: Add option to clear \Magento\Framework\Filesystem\Glob cache
magento/magento2 pull request #35742
Opened 2022-07-07 16:14 UTC by pmzandbergen

Fixing issue #35741

Added function to clear static cache

2022-07-12 13:32 UTC, manavluhar commented
@magento run all Tests

2025-08-04 14:41 UTC, engcom-Hotel commented
@magento run all tests

2025-08-04 14:50 UTC, engcom-Hotel requested changes
Hello @pmzandbergen,

Thanks for the contribution!

The code changes seems good to us, but please add some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

2025-08-04 14:50 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Filesystem/Glob.php
> +     * Clear the cache.
Consider adding the below documentation, you can update accordingly. Its just a suggestion.
```suggestion
     * Clear the static cache for glob patterns.
     * This method should be used primarily in testing environments
     * or long-running processes where file system changes occur
     * between glob() calls and fresh results are required.
```

2025-08-20 08:00 UTC, engcom-Dash commented
Hello @pmzandbergen 

I wanted to check if you are working on the automated test coverage. If not, Can I take care of them? Just let me know what works best for you.

2025-08-20 08:02 UTC, pmzandbergen commented
> Hello @pmzandbergen
> 
> I wanted to check if you are working on the automated test coverage. If not, Can I take care of them? Just let me know what works best for you.

I'll add tests this week, thx!

2025-10-27 05:20 UTC, engcom-Dash commented
Hello @pmzandbergen ,
Just wanted to check if you had a chance to work on the automated test coverage you mentioned earlier. Please let me know if you’re still planning to add them or if I can help with that

2025-10-27 15:20 UTC, pmzandbergen commented
> Hello @pmzandbergen , Just wanted to check if you had a chance to work on the automated test coverage you mentioned earlier. Please let me know if you’re still planning to add them or if I can help with that

Sorry, always busy 😬. I've added a test.

2025-10-28 05:28 UTC, engcom-Hotel commented
@magento run all tests

2025-10-28 10:45 UTC, engcom-Hotel requested changes
Hello @pmzandbergen,

Please fix the failed static tests, other failed tests seems flaky to me.

Thank you

2025-10-28 10:46 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2025-10-28 19:57 UTC, pmzandbergen commented
> Hello @pmzandbergen,
> 
> Please fix the failed static tests, other failed tests seems flaky to me.
> 
> Thank you

Updated (copyright)

2025-10-29 10:33 UTC, engcom-Hotel commented
@magento run all tests

2025-10-30 09:40 UTC, engcom-Hotel approved these changes
Thank you @pmzandbergen for making the changes. Approving this PR for further processing.

2025-11-02 10:15 UTC, hostep commented on lib/internal/Magento/Framework/Filesystem/Glob.php
> + * Copyright 2025 Adobe
Copyright year should be 2016 instead of 2025, since this file was introduced back then [according to the git history](https://github.com/magento/magento2/commits/6318973264ee6242736aeef3d3088eb1e12e7260/lib/internal/Magento/Framework/Filesystem/Glob.php).

2025-11-02 14:30 UTC, hostep approved these changes

2025-11-03 06:03 UTC, engcom-Dash commented
@magento run all tests

2025-11-04 10:20 UTC, engcom-Dash commented
@magento run all tests

2025-11-04 11:32 UTC, engcom-Dash commented
Hi @pmzandbergen 
Thanks for the collaboration & contribution!

✔️ QA Passed

Preconditions:
Install fresh Magento 2.4-develop

Manual testing scenarios
- Create a Custom module.
- In the execute function of the controller file, we have written the code below:
<img width="963" height="536" alt="image" src="https://github.com/user-attachments/assets/f9417c39-0a5b-4e00-a518-1fe7bb7f883d" />

Before: ✖️
<img width="883" height="445" alt="image" src="https://github.com/user-attachments/assets/26c1b6f3-7872-45a5-8ff8-71a9b4493253" />


Both $cache and $cache3 returned the same output, indicating that the static cache was not being cleared.

After: ✔️
<img width="837" height="450" alt="image" src="https://github.com/user-attachments/assets/2900c80a-afdf-47db-a878-73bd9562e1f0" />


$cache and $cache3 now return different outputs, confirming that the static cache is being cleared as expected.

Build are failing hence moving this Pr for Extended Testing

2025-11-04 14:55 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, WebAPI Tests

2025-11-05 11:49 UTC, engcom-Dash commented
The consistent failures in Functional B2B are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

B2B

Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/35742/a063c3a45533f34be01f54cfa44bd9c6/Functional/allure-report-b2b/index.html#categories
<img width="964" height="728" alt="image" src="https://github.com/user-attachments/assets/cd5d82a0-eacc-4f24-92a5-dd7d25d7f84c" />


Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/35742/c3e466d1177a95f759ecbd204afc6a4a/Functional/allure-report-b2b/index.html#categories
<img width="908" height="446" alt="image" src="https://github.com/user-attachments/assets/85b534b4-7f56-471b-a019-22913a15e31a" />
Known Issue
StorefrontPersistentCartCheckoutAfterSessionExpireLoginAndOrderTest:[ACQE-8907](https://jira.corp.adobe.com/browse/ACQE-8907)

Hence, Moving this PR Merge In Progress

2025-11-19 17:37 UTC, merged