Issue #34545 PHP Version error do not send a proper code error
magento/magento2 pull request #35797
Opened 2022-07-22 08:26 UTC by artskirk

### Description (*)

If the PHP version is not the one needed by Magento 2, we only get a message and a return code 200. I have added an appropriate HTTP response code 503.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34545

### Manual testing scenarios (*)

1. Increment current PHP version identifier to reproduce the issue:
    
![Capture-1](https://user-images.githubusercontent.com/57759456/180396531-d07240d7-8c37-4ffd-b4e8-e4ed0215fa0e.PNG)

2. Open Magento in browser
   
   
![Capture-2](https://user-images.githubusercontent.com/57759456/180396948-394151dc-93f5-492f-aa80-2b1d237725ea.PNG)

**Expected result**
The browser could return an appropriate HTTP response code such as a 503

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-07-22 08:36 UTC, ihor-sviziev requested changes

2022-07-22 08:36 UTC, ihor-sviziev commented on app/bootstrap.php
> +        http_response_code(503);
Please move this line just before "exit(1);"

2022-07-22 08:38 UTC, ihor-sviziev commented
@artskirk, could you please clarify, in case when this issue happening, the response is getting cached in Varnish and after your changes - it's not, right?

2022-07-26 08:34 UTC, artskirk commented
> @artskirk,
> 
> 1. could you please clarify, in case when this issue happening, the response is getting cached in Varnish and after your changes - it's not, right? 
> 2. Could you sign the Adobe CLA? 


1.  Yes, it's not cached.
2. CLA is signed.

2022-07-26 10:34 UTC, ihor-sviziev commented
@magento run all tests

2022-07-26 15:04 UTC, ihor-sviziev approved these changes

2022-08-31 07:41 UTC, merged