Issue #35796 Reindex failed and catalog_product_price have a status Reindex required main.CRITICAL: Warning: Undefined array key 5 in /var/www/magento/vendor/magento/module-bundle/Model/ResourceModel/Indexer/Price/DisabledProductOptionPriceModifier.php on line 117
magento/magento2 pull request #35827
Opened 2022-07-27 08:04 UTC by artskirk

### Description (*)

Added the additional undefined index checking to prevent the following error:
```
bin/magento indexer:reindex catalog_product_price
Product Price index process error during indexation process:
Warning: Undefined array key 45 in /var/www/html/m2d/app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price/DisabledProductOptionPriceModifier.php on line 124
```

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35796

### Manual testing scenarios (*)

1. Create bundle product
2. In bundle product go to tab "Product in Websites" & uncheck the Websites.
3. Click save & close.
4. In CLI enter bin/magento indexer:reindex catalog_product_price

**Expected result:** Reindex success and catalog_product_price have a status ready.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-07-27 08:41 UTC, ihor-sviziev requested changes

2022-07-27 08:41 UTC, ihor-sviziev commented on app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price/DisabledProductOptionPriceModifier.php
>          }
Looks like the issue coming from not declaring the empty array for the entity id. I would suggest adding it.
```suggestion
        $this->websiteIdsOfProduct[$entityId] = [];
        foreach ($connection->fetchCol($select) as $websiteId) {
            $this->websiteIdsOfProduct[$entityId][] = (int)$websiteId;
        }
```

2022-07-27 08:41 UTC, ihor-sviziev commented on app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price/DisabledProductOptionPriceModifier.php
> +        return $this->websiteIdsOfProduct[$entityId] ?? [];
```suggestion
        return $this->websiteIdsOfProduct[$entityId];
```

2022-07-27 08:42 UTC, ihor-sviziev commented
Hi @artskirk,
Could you please review my suggestion and add test coverage for this case?

2022-07-27 08:51 UTC, artskirk commented
> Hi @artskirk, Could you please review my suggestion and add test coverage for this case?

yes, I will

2022-07-27 08:58 UTC, artskirk commented
@ihor-sviziev I have checked your suggested solution, it's work as expected. I will cover it with unit tests.

2022-07-27 12:35 UTC, ihor-sviziev commented
@artskirk, please make sure that the unit test you wrote will fail w/o your changes and will pass after.

2022-07-27 12:37 UTC, artskirk commented
@magento run Unit Tests

2022-10-20 17:48 UTC, ishakhsuvarov commented
Tests have not been fixed for a long time, hence closing this PR for now.

Please feel free to reopen if you wish to revisit this.

2022-10-20 17:48 UTC, closed without merging