Issue #35808 PHP8.1 type bugfix
magento/magento2 pull request #35842
Opened 2022-07-29 09:08 UTC by artskirk

### Description (*)

There is an issue with types in \Magento\GroupedProduct\Model\Product\Type\Grouped class, in method _prepareProduct. A variable can be set as false, and is then used in a foreach, so I have update it to array type.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35808

### Manual testing scenarios (*)

Call \Magento\GroupedProduct\Model\Product\Type\Grouped::__prepareProduct method

**Expected result**

The following issue have to be fixed:

`.CRITICAL: Exception: Warning: foreach() argument must be of type array|object, bool given in /var/www/html/vendor/magento/module-grouped-product/Model/Product/Type/Grouped.php on line 391 `

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-08-01 06:55 UTC, ihor-sviziev requested changes
hi @artskirk,
Could you please cover your changes with any type of automated tests?

2024-10-15 09:41 UTC, engcom-Hotel commented
@magento run all tests

2024-10-15 10:02 UTC, engcom-Hotel commented
Hello @artskirk,

Have you got a chance to check the review comment made by @ihor-sviziev [here](https://github.com/magento/magento2/pull/35842#pullrequestreview-1056819998)?

Thanks

2024-10-15 15:05 UTC, ihor-sviziev commented
@engcom-Hotel I think covering this case would be pretty hard, so I would accept it as is since it's pretty low-risk change.

2024-10-15 15:05 UTC, ihor-sviziev commented
@magento run all tests

2024-10-15 15:06 UTC, ihor-sviziev approved these changes

2024-10-23 07:54 UTC, engcom-Dash commented
@magento run all tests

2024-10-23 09:00 UTC, engcom-Dash commented
Manual testing is not required since this change ensures that $associatedProducts is always an array when used in the foreach loop.

Builds are failed, hence moving it to Extended Testing.

2024-10-23 09:01 UTC, engcom-Dash commented
@magento run all tests

2024-10-23 11:46 UTC, engcom-Dash commented
Got the green build so moving it to merge in progress.
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/811b859a-8532-4463-b76c-042eca80c727">

2025-05-08 10:09 UTC, engcom-Dash commented
@magento run all tests

2025-05-19 07:57 UTC, merged