Update deprecated escape methods for frontend template of magento cat…
magento/magento2 pull request #35874
Opened 2022-08-03 22:20 UTC by slymbo

### Description (*)

Update deprecated **'Escape Methods'** for frontend template of Magento Catalog Module
### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

### Questions or comments

### Contribution checklist (*)
 

- [ ] Pull request has a meaningful description of its purpose

 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-08-05 11:00 UTC, Den4ik commented
@magento run all tests

2022-08-05 19:49 UTC, Den4ik requested changes
@slymbo Thanks for your contribution.
Please sign Adobe CLA and check failed static and unit tests

2022-08-11 10:28 UTC, slymbo commented
@magento run all tests

2024-11-07 10:01 UTC, engcom-Dash commented
Hello @slymbo,

Thanks for the contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks.

2024-12-02 10:06 UTC, engcom-Dash commented
Hello @slymbo,

This is a reminder to resolve the conflicts.

Thanks!

2024-12-13 10:11 UTC, engcom-Dash commented
Hello @slymbo,

This is a reminder to resolve the conflicts.

Thanks!

2025-01-02 11:05 UTC, engcom-Dash commented
Closing this PR since it has not been updated in a while. Please feel free to reopen it if needed.

2025-01-02 11:05 UTC, closed without merging