Database Prefix not included in SearchResultApplier.php
magento/magento2 pull request #35966
Opened 2022-08-17 13:40 UTC by richie-v

- When using database prefixes for tables, the sort by name and sort by price function on the category page is not working anymore
- Instead of using hard-coded table names, get the correct table name.
- This should work for both tables with prefixes and without them.

Test scenario:
- Added a database prefix in env.php. 
- Change table names to include prefix. 
- Go to a category page
- Sort by name

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-08-17 13:56 UTC, richie-v commented
@magento give me test instance

2022-08-17 14:02 UTC, richie-v commented
@magento run all tests

2022-08-17 14:51 UTC, richie-v commented
@magento run Static Tests

2022-08-17 16:55 UTC, richie-v commented
@magento run Static Tests

2022-08-17 17:47 UTC, richie-v commented
@magento run all tests

2023-05-11 10:46 UTC, engcom-Hotel requested changes
Hello @richie-v,

Please resolve the conflicts, so that we can move further with this PR for review.

Thanks

2024-09-16 11:03 UTC, engcom-Dash commented
hello @richie-v,

Closing this PR due to no response on conflict resolution. Please reopen if needed.

Thanks.

2024-09-16 11:03 UTC, closed without merging