Issue-33519. Added logic for grouping alerts by store
magento/magento2 pull request #35996
Opened 2022-08-22 15:18 UTC by topanok

### Description (*)
Added logic for grouping alerts by store. The problem was that when sorting collection items, the store ID of the last item of current user is always add to the email object. This fix also fixed the situation with PriceAlerts, because the logic is used by everyone.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33519

### Manual testing scenarios (*)
1. Setup Multiple Stores/websites in Magento
2. Create 2 different Stock Alert Email Templates for each store (Marketing - Communications - Email Templates - Add New Template)
3. Enable Product Alerts and Apply the newly created templates for each Store
4. Stores - Configuration - Catalog - Catalog - Product Alerts - Stock Alert Email Template - Set the new template created for new Store view scope , "Allow Alert When Product Comes Back in Stock" - Yes
Default Scope: Product Alerts Run Settings - Give the Start time and Save Configuration
Change the Scope of Store View to another Store view and apply other newly created template and save the configuration
5. Reindex and clear cache
6. Admin - Add a new Product - Set the Product to Out Of Stock and Save
7. Front-end - New Store website (for ex: France website) - Sign in as customer - Product Details page - Click on "Notify me when this product is in stock"
8. Open the same Product in different Store (for ex: Germany website) - Sign in as same customer - Product Details page - Click on "Notify me when this product is in stock"
9. Admin - Edit the same product and Set the stock status to "In Stock" and Save
10. Run the Cron > php bin/magento cron:run
11. Verify emails of both the Stores(You should receive two emails from both Stores with different email templates)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-08-22 16:22 UTC, topanok commented
@magento run all tests

2022-08-22 16:51 UTC, topanok commented
@magento run all tests

2022-08-29 11:56 UTC, topanok commented
@magento run all tests

2022-08-29 13:11 UTC, topanok commented
@magento run all tests

2022-08-30 19:12 UTC, topanok commented
@magento run Functional Tests B2B, Functional Tests EE

2022-09-18 08:52 UTC, topanok commented
@magento run all tests

2022-09-21 19:47 UTC, topanok commented
@magento run Integration Tests, WebAPI Tests

2022-09-21 19:49 UTC, topanok commented
@magento run Integration Tests, WebAPI Tests

2022-09-22 06:51 UTC, topanok commented
@magento run all tests

2022-09-22 13:04 UTC, topanok commented
@magento run Integration Tests, Functional Tests B2B

2022-09-22 18:48 UTC, topanok commented
@magento run Functional Tests B2B

2022-12-06 20:28 UTC, topanok commented
https://github.com/magento run all tests

2022-12-06 20:29 UTC, topanok commented
@magento run all tests

2022-12-11 10:33 UTC, topanok commented
@magento run Integration Tests, WebAPI Tests, Unit Tests, Functional Tests CE, Functional Tests B2B

2022-12-11 10:35 UTC, topanok commented
@magento run all tests

2022-12-12 13:02 UTC, topanok commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2022-12-13 09:58 UTC, topanok commented
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

2023-01-12 14:39 UTC, topanok commented
@magento run all tests

2023-01-20 11:48 UTC, topanok commented
@magento run all tests

2023-01-24 13:21 UTC, topanok commented
@magento run all tests

2023-01-31 13:21 UTC, topanok commented
https://github.com/magento run all tests

2023-01-31 13:21 UTC, topanok commented
@magento run all tests

2023-02-09 11:24 UTC, topanok commented
@magento run all tests

2023-02-10 09:43 UTC, topanok commented
@magento run all tests

2023-02-14 11:21 UTC, topanok commented
@magento run all tests

2023-02-25 10:42 UTC, topanok commented
@magento run all tests

2023-03-15 09:14 UTC, topanok commented
@magento run all tests

2023-03-20 11:31 UTC, topanok commented
@magento run all tests

2023-05-15 10:29 UTC, engcom-Hotel commented
@magento run all tests

2023-05-16 09:44 UTC, engcom-Hotel commented
@magento run all tests

2023-05-16 13:31 UTC, topanok commented
@magento run Functional Tests B2B, Functional Tests EE

2023-05-17 07:40 UTC, topanok commented
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

2023-05-17 13:25 UTC, engcom-Hotel requested changes
Hello @topanok,

Thanks for the contribution!

Changes looks good to us for this PR, but please cover the changes with some automated tests as part of the [definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1)

Thanks

2023-05-17 18:27 UTC, topanok commented
> engcom-Hotel
I can't run Sample Data Tests B2B
Sample Data Tests CE 
Sample Data Tests EE 
tests.
You can see the message - Failed to run the builds. Please try to re-run them later.

2023-05-18 05:21 UTC, engcom-Hotel commented
@topanok you can ignore that for now.

2023-05-24 11:13 UTC, engcom-Echo commented
@topanok Thank you for your contribution.
can you please confirm if you are working on above [comment](https://github.com/magento/magento2/pull/35996#pullrequestreview-1430698809).

2023-05-24 11:27 UTC, topanok commented
> 

Yes! What do I need to do? You can see that all tests without sample data have been completed.

2023-05-24 12:37 UTC, engcom-Echo commented
> > 
> 
> @engcom-Echo Yes! What do I need to do? You can see that all tests without sample data have been completed.

Can you please cover PR changes with appropriate automated test coverage like Unit Test / Integration Test

2023-05-30 06:07 UTC, engcom-Echo commented
@topanok can you please confirm if you are working on above [comment](https://github.com/magento/magento2/pull/35996#issuecomment-1561051959)?

2023-05-30 07:18 UTC, topanok commented
@engcom-Echo Yes, I'm working on it.

2023-06-14 06:24 UTC, engcom-Echo commented
Hi @topanok,

Did you get a chance to work on above [comment](https://github.com/magento/magento2/pull/35996#issuecomment-1567896602)?

2023-06-16 08:23 UTC, topanok commented
> Hi @topanok,
> 
> Did you get a chance to work on above [comment](https://github.com/magento/magento2/pull/35996#issuecomment-1567896602)?

Hi @engcom-Echo . A bit busy right now, but I'm working on tests as well

2023-06-28 14:53 UTC, engcom-Hotel commented
Hello @topanok,

Thanks for the response!

As you have mentioned that you will be working on the test coverage, we are moving this issue `On Hold`.

Also, I need to mention that, there is an open issue related to triggering emails for stock and price alerts, please refer to the below issue:

https://github.com/magento/magento2/issues/35602

The above issue is already confirmed. The above issue might be connected with this PR.

Thanks

2023-07-03 08:20 UTC, topanok commented
Hello @engcom-Echo. I wrote a test, you can see in the last commit

2023-07-03 08:21 UTC, topanok commented
@magento run all tests

2023-07-03 11:31 UTC, engcom-Echo commented
moving to `Pending Review` as automated test coverage is added.

2023-07-05 11:41 UTC, engcom-Hotel commented
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

2023-07-05 14:41 UTC, engcom-Hotel commented
Hello @topanok,

Thanks for adding the tests. But as per my comment here https://github.com/magento/magento2/pull/35996#issuecomment-1611595125, there is an existing issue due to which we are not able to get the Price Alert emails:

https://github.com/magento/magento2/issues/35602

We need to keep this PR `On Hold`. We will pick this up again whenever that issue has been resolved.

Thanks

2023-08-08 13:44 UTC, engcom-Charlie commented
As per [this](https://github.com/magento/magento2/pull/35996#issuecomment-1621904068), moving to Waiting Related PRs.

Thank you!

2023-10-02 07:34 UTC, topanok commented
> As per [this](https://github.com/magento/magento2/pull/35996#issuecomment-1621904068), moving to Waiting Related PRs.
> 
> Thank you!

Hello! Any updates?

2023-10-04 07:36 UTC, engcom-Hotel commented
Hello @topanok,

As per the JIRA related to the issue https://github.com/magento/magento2/issues/35602, the status is still in implementation.

We will update you accordingly on the status of that issue.

Thanks

2023-10-18 05:50 UTC, engcom-Charlie commented
It seems that bot has moved this PR to Changes Requested hence moving it back to Waiting Related PRs.

2023-10-21 13:00 UTC, topanok commented
@magento run all tests

2023-12-04 05:49 UTC, engcom-Charlie commented
It seems that bot has moved this PR to Changes Requested hence moving it back to Waiting Related PRs.

2023-12-26 10:45 UTC, andrewbess commented
@magento run all tests

2023-12-26 15:21 UTC, topanok commented
@magento run Functional Tests CE, Functional Tests B2B

2024-02-06 08:09 UTC, engcom-Hotel commented
As per this issue comment https://github.com/magento/magento2/issues/35602#issuecomment-1928965021, the issue is more reproducible.

Hence moving this PR back to `Pending Review`.

Thanks

2024-02-06 08:13 UTC, engcom-Hotel commented
@magento run all tests

2024-02-07 07:11 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2024-02-07 12:14 UTC, engcom-Hotel requested changes
Hello @topanok,

Thanks for the contribution!

Code changes seem good to me, please make the changes below as suggested.

Failed tests seem flaky to me.

Thanks

2024-02-07 12:14 UTC, engcom-Hotel commented on dev/tests/integration/framework/Magento/TestFramework/Mail/TransportInterfaceMock.php
>      public function sendMessage()
We can have a return type here as `void` maybe
```suggestion
    public function sendMessage() : void
```

2024-02-07 12:14 UTC, engcom-Hotel commented on dev/tests/integration/framework/Magento/TestFramework/Mail/TransportInterfaceMock.php
> +    public function getSentMsgCount()
Same here

2024-02-07 12:14 UTC, engcom-Hotel commented on dev/tests/integration/framework/Magento/TestFramework/Mail/TransportInterfaceMock.php
> +    public function resetSentMsgCount($count = 0)
and here

2024-02-07 12:14 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2024-02-09 06:43 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2024-02-13 09:30 UTC, engcom-Echo commented
@magento run all tests

2024-02-14 03:38 UTC, engcom-Hotel commented
@magento run all tests

2024-02-14 05:56 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2024-02-14 09:02 UTC, engcom-Hotel approved these changes

2024-02-29 14:19 UTC, engcom-Delta commented
@topanok, We have tried to reproduce and test this issue but we are not getting any product stock alert email.

Steps to reproduce:

1.Setup Multiple Stores/websites in Magento
2.Create 2 different Stock Alert Email Templates for each store (Marketing - Communications - Email Templates - Add New Template)
3.Enable Product Alerts and Apply the newly created templates for each Store
4.Stores - Configuration - Catalog - Catalog - Product Alerts - Stock Alert Email Template - Set the new template created for new Store view scope , "Allow Alert When Product Comes Back in Stock" - Yes
Default Scope: Product Alerts Run Settings - Give the Start time and Save Configuration
5.Change the Scope of Store View to another Store view and apply other newly created template and save the configuration
6.Reindex and clear cache
7Admin - Add a new Product - Set the Product to Out Of Stock and Save
8.Front-end - New Store website (for ex: France website) - Sign in as customer - Product Details page - Click on "Notify me when this product is in stock"
9.Open the same Product in different Store (for ex: Germany website) - Sign in as same customer - Product Details page - Click on "Notify me when this product is in stock"
10.Admin - Edit the same product and Set the stock status to "In Stock" and Save
11.Run the Cron > php bin/magento cron:run
12.Verify emails of both the Stores

<img width="1433" alt="Screenshot 2024-02-28 at 6 49 58 PM" src="https://github.com/magento/magento2/assets/51681379/3f213823-0253-4172-bc8a-af71929ce3ba">
<img width="1424" alt="Screenshot 2024-02-28 at 6 50 22 PM" src="https://github.com/magento/magento2/assets/51681379/b64ea347-4022-4211-92fa-ea99e960a6bc">
<img width="1440" alt="Screenshot 2024-02-28 at 6 51 03 PM" src="https://github.com/magento/magento2/assets/51681379/a3073a1c-0227-4bfe-b852-6655f0191daf">
<img width="1440" alt="Screenshot 2024-02-28 at 6 51 52 PM" src="https://github.com/magento/magento2/assets/51681379/1bf08909-0eb1-4aed-abf4-7226cd4c6cdc">
<img width="1419" alt="Screenshot 2024-02-28 at 6 52 55 PM" src="https://github.com/magento/magento2/assets/51681379/87020564-4a4b-44b7-9b0c-7f6ee51076bf">
<img width="1440" alt="Screenshot 2024-02-28 at 6 53 50 PM" src="https://github.com/magento/magento2/assets/51681379/1dcbc34b-04ff-4a63-864f-2918a1dc9965">
<img width="1362" alt="Screenshot 2024-02-28 at 6 54 50 PM" src="https://github.com/magento/magento2/assets/51681379/ac9db062-03df-4bfd-9986-50fb6071d628">
<img width="1421" alt="Screenshot 2024-02-28 at 6 55 25 PM" src="https://github.com/magento/magento2/assets/51681379/5fe3d19c-aae5-4ffc-baee-3ec1f52f39d1">
<img width="1429" alt="Screenshot 2024-02-28 at 6 55 32 PM" src="https://github.com/magento/magento2/assets/51681379/58517584-c890-42aa-9aae-f359087f006d">
<img width="1359" alt="Screenshot 2024-02-28 at 6 55 45 PM" src="https://github.com/magento/magento2/assets/51681379/15efdcd2-8505-4bac-8f2b-6440f20db5c9">
<img width="1428" alt="Screenshot 2024-02-28 at 6 55 57 PM" src="https://github.com/magento/magento2/assets/51681379/4ea61284-59cb-4940-88a8-8882f75a626b">
<img width="1408" alt="Screenshot 2024-02-28 at 6 56 06 PM" src="https://github.com/magento/magento2/assets/51681379/369d14b3-792f-4e87-b505-2cfbd86c9628">
<img width="1407" alt="Screenshot 2024-02-28 at 6 57 19 PM" src="https://github.com/magento/magento2/assets/51681379/f3261859-137c-4b7f-9165-1b6f4ef1b9b3">
<img width="1432" alt="Screenshot 2024-02-28 at 6 56 40 PM" src="https://github.com/magento/magento2/assets/51681379/6ef9b468-4a59-44ec-a9b8-adc16603fde1">
<img width="286" alt="Screenshot 2024-02-28 at 7 08 44 PM" src="https://github.com/magento/magento2/assets/51681379/c1d73223-3cb7-40ad-8cb3-99a2b77762ec">


Kindly suggest if something is missing

2024-02-29 18:30 UTC, topanok commented
@engcom-Delta Hello! Mail server configured? Can you get any email like password reset?

2024-03-04 10:25 UTC, engcom-Delta commented
> @engcom-Delta Hello! Mail server configured? Can you get any email like password reset? And wait until midnight)) <img alt="Снимок экрана 2024-02-29 в 20 32 32" width="986" src="https://private-user-images.githubusercontent.com/61389203/309035527-110f1368-7307-45ef-adde-6a5163f786b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDgxMjcsIm5iZiI6MTcwOTU0NzgyNywicGF0aCI6Ii82MTM4OTIwMy8zMDkwMzU1MjctMTEwZjEzNjgtNzMwNy00NWVmLWFkZGUtNmE1MTYzZjc4NmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEwMjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjZkMWJiOWJkYzEyMThkOTdiNDkwMDBiMjdhZjI5OGYzNDAxNTEzZjI2OGYzODllOTdkMzVkNjZjYTI4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mbL5YgOKMYMujdZQCHCdeTKlYbQg9-sRxaiYlbbPf7A">


@topanok, Yes Mail server configured and i am getting password reset email but not the alert once till now

2024-03-04 12:21 UTC, topanok commented
@engcom-Delta Perhaps this is related to the time of sending letters, which you have set to midnight, and the one-time start of the cron did not work. Start the cron in constant operation with the `php bin/magento cron:install` command and wait for the letter after midnight or change the sending time to the nearest one. I hope you cleared the config cache after saving?

2024-03-04 15:25 UTC, topanok commented
@engcom-Delta I checked the functionality. Everything works if the cron is running. Namely... The time set in the admin is responsible for starting the cron, which adds operations to the queue. After that, the cron works, which performs the scheduled operations. It turns out that the command from the message above (`php bin/magento cron:install`) should fix the situation. But you won't get notifications until midnight. 
If you do not receive anything, then subscribe to the product again, because something may have gone wrong due to the disabled cron. This is partly my fault for writing the wrong command to run kron. Sorry!)

2024-03-07 14:58 UTC, engcom-Delta commented
> @engcom-Delta I checked the functionality. Everything works if the cron is running. Namely... The time set in the admin is responsible for starting the cron, which adds operations to the queue. After that, the cron works, which performs the scheduled operations. It turns out that the command from the message above (`php bin/magento cron:install`) should fix the situation. But you won't get notifications until midnight. If you do not receive anything, then subscribe to the product again, because something may have gone wrong due to the disabled cron. This is partly my fault for writing the wrong command to run kron. Sorry!)

@topanok, That's okay and my cron is working fine but we are not getting the alert mails and some more PRs are on hold due to that. May i know in which version of magento it is working for you and more details if any.

Thanks,

2024-03-26 14:10 UTC, engcom-Delta commented
@topanok Waiting for your reply on the PR to move ahead.

2024-03-26 18:46 UTC, topanok commented
> @topanok Waiting for your reply on the PR to move ahead.

Hello. Tested on the same branch as PR and Magento version dev-2.4-develop. Please show what you have in the `product_alert_stock` table in the marked columns. 
<img width="1209" alt="Снимок экрана 2024-03-26 в 20 18 51" src="https://github.com/magento/magento2/assets/61389203/f5fd6dd6-cb97-4888-8296-74b2d26b3aea">

2024-03-27 08:36 UTC, topanok commented
> @topanok Waiting for your reply on the PR to move ahead.

Hello! I raised the magento instance yesterday to test everything again. Here are the results. As you can see, the letters have arrived and you can see it in the magento database. So I can assume that you have some problems with the environment. Maybe ask someone for help. 

<img width="1440" alt="Снимок экрана 2024-03-27 в 10 30 53" src="https://github.com/magento/magento2/assets/61389203/a82b79c1-6d06-4f28-ba55-3ed4fdc3e5b8">
<img width="1210" alt="Снимок экрана 2024-03-27 в 10 30 30" src="https://github.com/magento/magento2/assets/61389203/2efe682e-3a76-4db2-87b0-b1cb00485eec">

2024-03-27 09:19 UTC, engcom-Delta commented
Hi @topanok , Thanks for your reply. We are also using 2.4 develop. I have checked the table product_alert_stock. Adding the screenshot for the same.

<img width="912" alt="Screenshot 2024-03-27 at 11 54 10 AM" src="https://github.com/magento/magento2/assets/51681379/20e3a78e-19b3-4ad8-8ff3-dd03187b8016">

2024-03-27 09:21 UTC, engcom-Delta commented
Issue related to product alert stock is https://github.com/magento/magento2/issues/35602 is reopened and this is a blocker to test this PR.

So moving this PR to Waiting related PRs.

2024-03-27 09:26 UTC, topanok commented
> Hi @topanok , Thanks for your reply. We are also using 2.4 develop. I have checked the table product_alert_stock. Adding the screenshot for the same.
> 
> <img alt="Screenshot 2024-03-27 at 11 54 10 AM" width="912" src="https://private-user-images.githubusercontent.com/51681379/317195516-20e3a78e-19b3-4ad8-8ff3-dd03187b8016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzE1MTUsIm5iZiI6MTcxMTUzMTIxNSwicGF0aCI6Ii81MTY4MTM3OS8zMTcxOTU1MTYtMjBlM2E3OGUtMTliMy00YWQ4LThmZjMtZGQwMzE4N2I4MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYTk0MjlmNTk0ZGExNWZlNzRiNDJmNTZmZmI0M2VkYjA1MDgzYjNjMjlkOTNmM2I3YWRiZTQ4NmZlMTExMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLEXuWUPaLvXxXm587vYa-YwnF79H73QKyFPBCkLwf4">

It looks like you don't have cron running or you don't have mail sent configured. As you can see from my previous post, everything was working fine for me. So maybe get someone else to test it. I don't know how to help you.

2024-03-27 10:23 UTC, engcom-Delta commented
> > Hi @topanok , Thanks for your reply. We are also using 2.4 develop. I have checked the table product_alert_stock. Adding the screenshot for the same.
> > <img alt="Screenshot 2024-03-27 at 11 54 10 AM" width="912" src="https://private-user-images.githubusercontent.com/51681379/317195516-20e3a78e-19b3-4ad8-8ff3-dd03187b8016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzE1MTUsIm5iZiI6MTcxMTUzMTIxNSwicGF0aCI6Ii81MTY4MTM3OS8zMTcxOTU1MTYtMjBlM2E3OGUtMTliMy00YWQ4LThmZjMtZGQwMzE4N2I4MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYTk0MjlmNTk0ZGExNWZlNzRiNDJmNTZmZmI0M2VkYjA1MDgzYjNjMjlkOTNmM2I3YWRiZTQ4NmZlMTExMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLEXuWUPaLvXxXm587vYa-YwnF79H73QKyFPBCkLwf4">
> 
> It looks like you don't have cron running or you don't have mail sent configured. As you can see from my previous post, everything was working fine for me. So maybe get someone else to test it. I don't know how to help you.


Hi @topanok , As mentioned in the below comment we are not getting product alert email as of now when cron is running and email alert has set , so we have reopened the issue.We will wait till the issue is resolved to test this PR.

https://github.com/magento/magento2/pull/35996#issuecomment-2022289510

2024-03-29 09:28 UTC, topanok commented
> > > Привіт@topanok, Дякуємо за Ваш відповідь. Ми також використовуємо 2.4 development. Я перевірив таблицю product_alert_stock. Додавання скріншота для того ж.
> > > <img alt="Скріншот 27.03.2024 об 11 54 10 ранку" width="912" src="https://private-user-images.githubusercontent.com/51681379/317195516-20e3a78e-19b3-4ad8-8ff3-dd03187b8016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzE1MTUsIm5iZiI6MTcxMTUzMTIxNSwicGF0aCI6Ii81MTY4MTM3OS8zMTcxOTU1MTYtMjBlM2E3OGUtMTliMy00YWQ4LThmZjMtZGQwMzE4N2I4MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYTk0MjlmNTk0ZGExNWZlNzRiNDJmNTZmZmI0M2VkYjA1MDgzYjNjMjlkOTNmM2I3YWRiZTQ4NmZlMTExMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLEXuWUPaLvXxXm587vYa-YwnF79H73QKyFPBCkLwf4">
> > 
> > 
> > Схоже, у вас не запущено cron або не налаштовано надсилання пошти. Як ви бачите з мого попереднього допису, у мене все працювало нормально. Тому, можливо, попросіть когось іншого перевірити це. Я не знаю, як вам допомогти.
> 
> Привіт@topanok, Як зазначено в коментарі нижче, наразі ми не отримуємо сповіщення електронною поштою про продукт, коли запущено cron і встановлено сповіщення електронною поштою, тому ми повторно відкрили проблему. Ми зачекаємо, доки проблему не буде вирішено, щоб перевірити цей PR.
> 
> [#35996 (коментар)](https://github.com/magento/magento2/pull/35996#issuecomment-2022289510)

You can wait, but I won't do anything. It's not my problem that you can't test. I'm already fed up with this pull request, which is already 1.5 years old.

2024-03-29 09:29 UTC, topanok commented
> > > Hi @topanok , Thanks for your reply. We are also using 2.4 develop. I have checked the table product_alert_stock. Adding the screenshot for the same.
> > > <img alt="Screenshot 2024-03-27 at 11 54 10 AM" width="912" src="https://private-user-images.githubusercontent.com/51681379/317195516-20e3a78e-19b3-4ad8-8ff3-dd03187b8016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzE1MTUsIm5iZiI6MTcxMTUzMTIxNSwicGF0aCI6Ii81MTY4MTM3OS8zMTcxOTU1MTYtMjBlM2E3OGUtMTliMy00YWQ4LThmZjMtZGQwMzE4N2I4MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYTk0MjlmNTk0ZGExNWZlNzRiNDJmNTZmZmI0M2VkYjA1MDgzYjNjMjlkOTNmM2I3YWRiZTQ4NmZlMTExMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLEXuWUPaLvXxXm587vYa-YwnF79H73QKyFPBCkLwf4">
> > 
> > 
> > It looks like you don't have cron running or you don't have mail sent configured. As you can see from my previous post, everything was working fine for me. So maybe get someone else to test it. I don't know how to help you.
> 
> Hi @topanok , As mentioned in the below comment we are not getting product alert email as of now when cron is running and email alert has set , so we have reopened the issue.We will wait till the issue is resolved to test this PR.
> 
> [#35996 (comment)](https://github.com/magento/magento2/pull/35996#issuecomment-2022289510)

You can wait, but I won't do anything. It's not my problem that you can't test. I'm already fed up with this pull request, which is already 1.5 years old.

2024-10-17 11:29 UTC, engcom-Hotel commented
Hello @topanok,

The issue that was preventing us from receiving alert emails has been resolved. We can now move forward with this PR. However, we kindly request that you resolve the conflicts.

Thanks

2024-11-18 10:43 UTC, engcom-Hotel commented
Hello @topanok,

This is a reminder to resolve the conflicts of this PR. Please do the needful so that we can proceed further with this.

Thanks

2024-11-25 10:53 UTC, engcom-Hotel commented
Hello @topanok,

A gentle reminder to resolve the conflicts on this PR.

Thanks

2024-12-09 07:43 UTC, engcom-Hotel commented
Hello @topanok,

We have noticed that this PR has not been updated for a while. Therefore, we are closing it for now.

Please let us know when you are ready to work on it again, and we will be happy to reopen the PR.

Thank you for your valuable contribution!

2024-12-09 07:43 UTC, closed without merging