Update the Fixer.Io api endpoint and method of submitting the api key.
magento/magento2 pull request #36077
Opened 2022-09-02 13:19 UTC by richard-parnaby-king

### Description (*)
Fixer.io has changed the api endpoint and method of submitting the api key. Utilising Fixer.io to update currency rates results in an invalid api key error message. This PR updates the api endpoint and method of submitting the api key.

### Manual testing scenarios (*)
Go to Stores > Currency Rates , select Fixer.io as service and click on "Import". An error will appear.

### Questions or comments
I haven't added unit tests or any other test, there seems to be very little automatic tests that exist for this part in Magento and I don't want to spend the time in to write everything out from scratch, I don't have the energy or time for that, so if this is required, it would be appreciated if an Adobe employee could help out with that.

### Contribution checklist (*)
- [ ]  Pull request has a meaningful description of its purpose
- [ ]  All commits are accompanied by meaningful commit messages
- [ ]  All new or changed code is covered with unit/integration tests (if applicable)
- [ ]  README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
- [ ]  All automated tests passed successfully (all builds are green)

2022-09-02 13:19 UTC, richard-parnaby-king commented
@magento run all tests

2022-09-02 14:02 UTC, richard-parnaby-king commented
@magento run Static Tests

2022-09-05 06:54 UTC, ihor-sviziev commented
Hi @richard-parnaby-king,
Thank you for your contribution!
I'm closing this PR as a duplicate of https://github.com/magento/magento2/pull/35984 that was created earlier

2022-09-05 08:43 UTC, richard-parnaby-king commented
@ihor-sviziev That pull request does not solve the issue. The fixer api requires the access key to be submitted as part of a custom header, not as part of the url query string, which is what this pull request resolves.

2022-09-05 09:39 UTC, ihor-sviziev requested changes

2022-09-05 09:39 UTC, ihor-sviziev commented on app/code/Magento/Directory/Model/Currency/Import/FixerIo.php
> +    public const API_KEY_CONFIG_PATH = 'currency/fixerio/api_key';
Let's make it private due to backward compatibility reasons
```suggestion
    private const API_KEY_CONFIG_PATH = 'currency/fixerio/api_key';
```

2022-09-05 09:39 UTC, ihor-sviziev commented
@magento run all tests

2022-09-05 12:01 UTC, ihor-sviziev requested changes
@richard-parnaby-king please review and fix failing tests

2022-09-05 13:49 UTC, Den4ik requested changes
I believe that use of access key should be also removed at lines 114-115

```
url = str_replace(
            ['{{ACCESS_KEY}}', '{{CURRENCY_FROM}}', '{{CURRENCY_TO}}'],
            [$accessKey, $currencyFrom, $currenciesStr],
            self::CURRENCY_CONVERTER_URL
);
```

2022-09-06 10:46 UTC, richard-parnaby-king commented
@ihor-sviziev

Some of these tests do not revolve around the functionality of this pull request, for example there is a failing test for the Aws S3 remote filestorage component. 

Looking at the failing tests the only one concerning the FixerIo module is failing this test: testFetchRates (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Directory/Test/Unit/Model/Currency/Import/FixerIoTest.php)

The error message is:
```
Expectation failed for method name is "getValue" when invoked zero or more times
Parameter 0 for invocation #1 Magento\Framework\App\Config\ScopeConfigInterface::getValue('currency/fixerio/api_key', 'store', null) does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'currency/fixerio/timeout'
+'currency/fixerio/api_key'
```

Which is this bit of code:
```
        $this->scopeConfig->method('getValue')
            ->withConsecutive(
                ['currency/fixerio/api_key', 'store'],
                ['currency/fixerio/timeout', 'store']
            )
            ->willReturnOnConsecutiveCalls('api_key', 100);
```

Do I need to fix this or does it sit with the core team? If I need to fix it, what is the expected functionality?

2022-09-07 14:32 UTC, ihor-sviziev commented
@magento run all tests

2022-09-07 14:36 UTC, ihor-sviziev commented
@richard-parnaby-king, please fix the related tests only. For instance, the one you said fails because of changes.

2022-09-09 12:03 UTC, richard-parnaby-king commented
@magento run Unit Tests

2022-09-09 15:47 UTC, richard-parnaby-king commented
https://github.com/magento run Unit Tests

2022-09-09 15:48 UTC, richard-parnaby-king commented
@magento run Unit Tests

2022-09-09 16:49 UTC, richard-parnaby-king commented
https://github.com/magento run Unit Tests

2022-09-09 16:50 UTC, richard-parnaby-king commented
@magento run Unit Tests

2022-09-09 19:46 UTC, richard-parnaby-king commented
@magento run all tests

2022-09-12 10:01 UTC, richard-parnaby-king commented
@magento run All Tests

2022-09-12 11:53 UTC, richard-parnaby-king commented
@ihor-sviziev Failing tests are unrelated to this PR.

2022-09-13 05:46 UTC, ihor-sviziev commented
@magento run Functional Tests EE, WebAPI Tests

2022-09-13 05:47 UTC, ihor-sviziev approved these changes

2022-09-13 06:06 UTC, Den4ik approved these changes

2022-09-15 11:52 UTC, engcom-Lima commented
@magento run Functional Tests EE

2022-09-15 11:52 UTC, engcom-Lima commented
@magento give me 2.4-develop instance

2022-09-15 12:01 UTC, engcom-Lima commented
@magento give me test instance

2022-09-15 13:24 UTC, engcom-Lima commented
Hi @richard-parnaby-king 

Thanks for your contribution and collaboration.

I have tried to reproduce the issue ,it is reproducible to me below is the screenshot for your reference:
<img width="1512" alt="Screenshot 2022-09-15 at 5 39 06 PM" src="https://user-images.githubusercontent.com/60198022/190413960-400fbb57-9282-4073-a91a-5b070589f993.png">

But after applying PR changes I am getting error in UI as well as in logs as below:
**IN LOGS:**
```
[2022-09-15T11:51:32.612615+00:00] main.CRITICAL: Error: Call to undefined method Magento\Framework\HTTP\LaminasClient::getHeaders() in /opt/homebrew/var/www/magento2/app/code/Magento/Directory/Model/Currency/Import/FixerIo.php:176
Stack trace:
#0 /opt/homebrew/var/www/magento2/app/code/Magento/Directory/Model/Currency/Import/FixerIo.php(121): Magento\Directory\Model\Currency\Import\FixerIo->getServiceResponse('https://api.api...')
#1 /opt/homebrew/var/www/magento2/app/code/Magento/Directory/Model/Currency/Import/FixerIo.php(81): Magento\Directory\Model\Currency\Import\FixerIo->convertBatch(Array, 'INR', Array)
#2 /opt/homebrew/var/www/magento2/app/code/Magento/CurrencySymbol/Controller/Adminhtml/System/Currency/FetchRates.php(87): Magento\Directory\Model\Currency\Import\FixerIo->fetchRates()
#3 /opt/homebrew/var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\CurrencySymbol\Controller\Adminhtml\System\Currency\FetchRates->execute()
```
**IN UI:**
<img width="1512" alt="Screenshot 2022-09-15 at 6 23 26 PM" src="https://user-images.githubusercontent.com/60198022/190414921-2bb9c7f6-fec3-477b-95bd-1ce6e319b0be.png">

I have tested it in local as well in git cloud instance as well but issue is same.

Since PR is not working fine. I am moving this PR to **Changes requested**.

Thanks

2022-09-15 13:28 UTC, engcom-Lima requested changes
Hi @richard-parnaby-king 

Thanks for your contribution and collaboration.

I have tried to reproduce the issue ,it is reproducible to me below is the screenshot for your reference:
<img width="1512" alt="Screenshot 2022-09-15 at 5 39 06 PM" src="https://user-images.githubusercontent.com/60198022/190413960-400fbb57-9282-4073-a91a-5b070589f993.png">

But after applying PR changes I am getting error in UI as well as in logs as below:
**IN LOGS:**
```
[2022-09-15T11:51:32.612615+00:00] main.CRITICAL: Error: Call to undefined method Magento\Framework\HTTP\LaminasClient::getHeaders() in /opt/homebrew/var/www/magento2/app/code/Magento/Directory/Model/Currency/Import/FixerIo.php:176
Stack trace:
#0 /opt/homebrew/var/www/magento2/app/code/Magento/Directory/Model/Currency/Import/FixerIo.php(121): Magento\Directory\Model\Currency\Import\FixerIo->getServiceResponse('https://api.api...')
#1 /opt/homebrew/var/www/magento2/app/code/Magento/Directory/Model/Currency/Import/FixerIo.php(81): Magento\Directory\Model\Currency\Import\FixerIo->convertBatch(Array, 'INR', Array)
#2 /opt/homebrew/var/www/magento2/app/code/Magento/CurrencySymbol/Controller/Adminhtml/System/Currency/FetchRates.php(87): Magento\Directory\Model\Currency\Import\FixerIo->fetchRates()
#3 /opt/homebrew/var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\CurrencySymbol\Controller\Adminhtml\System\Currency\FetchRates->execute()
```
**IN UI:**
<img width="1512" alt="Screenshot 2022-09-15 at 6 23 26 PM" src="https://user-images.githubusercontent.com/60198022/190414921-2bb9c7f6-fec3-477b-95bd-1ce6e319b0be.png">

I have tested it in local as well in git cloud instance as well but issue is same.

Since PR is not working fine. I am moving this PR to **Changes requested**.

Thanks

2022-09-16 12:01 UTC, ihor-sviziev commented
@magento run all tests

2022-09-16 12:02 UTC, ihor-sviziev requested changes

2022-09-16 12:02 UTC, ihor-sviziev commented on app/code/Magento/Directory/Test/Unit/Model/Currency/Import/FixerIoTest.php
> +            ->willReturnSelf();
Maybe we should check if method setHeaders was executed with correct params?

2022-09-20 09:34 UTC, richard-parnaby-king commented
@magento give me test instance

2022-09-20 09:48 UTC, richard-parnaby-king commented
@magento give me test instance

2022-09-20 09:58 UTC, richard-parnaby-king commented
@magento give me test instance

2022-09-20 10:54 UTC, richard-parnaby-king commented
@magento give me test instance

2022-09-20 11:05 UTC, richard-parnaby-king commented
@magento give me test instance

2022-10-20 17:55 UTC, ishakhsuvarov commented
Looks like requested changes were not implemented or discussed in a long time, hence I am closing this PR for now.

Please feel free to reopen if there is any additional work done on this.

2022-10-20 17:55 UTC, closed without merging