Added notice styling and traslatable string in default templates for CMS home and no-route
magento/magento2 pull request #36126
Opened 2022-09-10 11:58 UTC by jq91

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-09-13 00:00 UTC, Den4ik commented
@jq91 Please sign CLA

2022-09-15 13:48 UTC, jq91 commented
@Den4ik CLA already signed.

2022-09-19 19:54 UTC, Den4ik commented
@magento run all tests

2022-09-20 11:08 UTC, Den4ik requested changes
@jq91 Please look at my comment

2022-09-20 11:08 UTC, Den4ik commented on app/code/Magento/Cms/view/frontend/templates/default/home.phtml
> +    <div><?= __('There was no Home CMS page configured or found.'); ?></div>
Output should be escaped with by `$escaper->escapeHtml()`

2022-09-20 11:08 UTC, Den4ik commented on app/code/Magento/Cms/view/frontend/templates/default/no-route.phtml
> +    <div><?= __('There was no 404 CMS page configured or found.'); ?></div>
Output should be escaped with by `$escaper->escapeHtml()`

2022-09-21 08:29 UTC, jq91 commented
@Den4ik escapeHtml() has been added
https://github.com/magento/magento2/pull/36126/commits/982e16f520c7581cb8fb71022c0a503a09918e36

2022-11-09 21:18 UTC, Den4ik commented
@magento run all tests

2022-11-12 05:46 UTC, Den4ik commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Sample Data Tests B2B, Unit Tests

2022-11-18 07:04 UTC, jq91 commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2024-03-13 20:24 UTC, closed without merging