Issue 35925: Internal Server Error in /V1/creditmemo/refund API Endpoint
magento/magento2 pull request #36180
Opened 2022-09-22 17:41 UTC by rogerdz

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35925

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-09-22 17:43 UTC, rogerdz commented
@magento run all tests

2022-09-23 00:52 UTC, edenduong requested changes
Thank you for your contribution. Could you please check my comment.

2022-09-23 00:52 UTC, edenduong commented on app/code/Magento/Sales/Model/Service/CreditmemoService.php
> - * Class CreditmemoService
I think we should not remove the Class CreditmemoService in comment. You can add description below the class comment.

2022-09-23 00:52 UTC, edenduong commented on app/code/Magento/Sales/Model/Service/CreditmemoService.php
> +            throw new \Magento\Framework\Exception\LocalizedException(
Change to `Magento\Framework\Exception\NoSuchEntityException`

2022-09-23 04:38 UTC, edenduong requested changes

2022-09-23 04:38 UTC, edenduong commented on app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php
> +        $creditMemoMock->expects($this->atLeastOnce())->method('getOrderId')->willReturn(true);
it should be int instead of boolean

2022-09-23 04:38 UTC, edenduong commented on app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php
> +        $creditMemoMock->expects($this->once())->method('getOrderId')
it should be int instead of boolean

2022-09-23 04:38 UTC, edenduong commented on app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php
> +        $creditMemo->method('getOrderId')
it should be int instead of boolean

2022-09-23 14:19 UTC, rogerdz commented on app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php
> +        $creditMemo->method('getOrderId')
Thank @edenduong, I added new commit

2022-09-23 14:20 UTC, rogerdz commented
@magento run all tests

2022-09-26 00:21 UTC, edenduong approved these changes

2022-09-26 11:16 UTC, engcom-Lima commented
@magento run Functional Tests B2B, Functional Tests EE

2022-09-26 13:12 UTC, engcom-Lima commented
@magento run Functional Tests B2B

2022-09-27 07:11 UTC, engcom-Lima commented
@magento run Functional Tests EE

2022-09-27 09:15 UTC, engcom-Lima commented
@magento run Functional Tests EE

2022-09-27 13:19 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
- Retrieve auth token from the admin endpoint /V1/integration/admin/
- Send request of below payload using post method and endpoint as `/rest/default/V1/creditmemo/refund`. 
**Payload:**
```
{
    "creditmemo": "",
    "offlineRequested": true
}
```

**Before:** :heavy_multiplication_x: Getting 500 error in response.
<img width="1078" alt="Screenshot 2022-09-26 at 4 06 09 PM" src="https://user-images.githubusercontent.com/60198022/192536297-e8f296a5-5db7-490a-a5b6-c513d5f8aad0.png">

**In logs:**
<img width="1503" alt="Screenshot 2022-09-26 at 4 06 57 PM" src="https://user-images.githubusercontent.com/60198022/192536565-ec0934dd-d603-4225-aa9c-3625b69933c7.png">


**After:** :heavy_check_mark:  Getting 400 error as expected.
<img width="1086" alt="Screenshot 2022-09-26 at 4 30 03 PM" src="https://user-images.githubusercontent.com/60198022/192537057-8335194f-63e9-4766-843c-09682bfd2f84.png">

As automation is covered no additional manual test case is required.

2022-10-28 21:33 UTC, merged