Issue 35923: Internal Server Error in /V1/products/{sku}/links API En…
magento/magento2 pull request #36198
Opened 2022-09-25 15:07 UTC by rogerdz

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35923

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-09-25 15:07 UTC, rogerdz commented
@magento run all tests

2022-09-25 15:09 UTC, rogerdz commented
@magento run all tests

2022-09-25 23:15 UTC, bgorski requested changes
There's one message that needs to be adjusted. Apart from that, please check all the failing tests and determine if they're failing because of your code. I took a quick look and looks like only this static test is failing because of your changes:

```
FILE: /var/www/html/app/code/Magento/Catalog/Model/ProductLink/Repository.php
------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------
 64 | WARNING | Motivation behind the added @deprecated tag MUST be explained. @see tag MUST be used with reference to
    |         | new implementation when code is deprecated and there is a new alternative.
------------------------------------------------------------------------------------------------------------------------
```

Because you touched the repository class, fixing the test would be your job. If you don't know what to put in the `@see` tag, you can put something like `@see \Magento\Catalog\Model\ResourceModel\Product\Link::saveProductLinks()` because the deprecation (that happened years ago with the switch from 2.0.* to 2.1.0) was about the fact that previously in order to persist product links it was required to initialize all links on a product before the save on that product could occur. So let's point to that. Although the sniff is about providing an alternative, in this case no alternative is required. The way it's all working now for years is the alternative.

2022-09-25 23:15 UTC, bgorski commented on app/code/Magento/Catalog/Model/ProductLink/Repository.php
> +            throw new NoSuchEntityException(__('The linked products sku is invalid. Verify the data and try again.'));
The wording of this exception doesn't seem right since the SKU returned by the function is singular. Also, SKU should be all caps because it's an acronym. Please fix.

2022-09-26 02:16 UTC, rogerdz commented on app/code/Magento/Catalog/Model/ProductLink/Repository.php
> +            throw new NoSuchEntityException(__('The linked products sku is invalid. Verify the data and try again.'));
thank @bgorski , I added new commit

2022-09-26 02:16 UTC, rogerdz commented
@magento run all tests

2022-09-27 13:54 UTC, bgorski commented
@magento run Integration Tests

2022-09-28 11:37 UTC, bgorski commented
@magento run Integration Tests

2022-09-28 13:45 UTC, bgorski reviewed
Approved - thank you for the contribution!

2022-09-28 13:45 UTC, bgorski approved these changes

2022-09-30 10:19 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Retrieve auth token from the admin endpoint `/V1/integration/admin/`
2. Request PUT endpoint: `/rest/default/V1/products/{sku}/links` with payload:

```
{
    "entity": {}
}
```
**Before:** :heavy_multiplication_x:  Getting 500 internal server error in response and error as show in screenshot:

**Response:**
<img width="1086" alt="Screenshot 2022-09-30 at 3 37 43 PM" src="https://user-images.githubusercontent.com/60198022/193248297-709a4530-b1ef-40d3-9071-41b941d4cf61.png">

**Logs:**
<img width="1509" alt="Screenshot 2022-09-30 at 3 33 53 PM" src="https://user-images.githubusercontent.com/60198022/193248193-c09b6df2-d743-47fc-8d03-b82c14cd79b6.png">


**After:** :heavy_check_mark:  Getting 400 error as expected.
<img width="1069" alt="Screenshot 2022-09-30 at 3 35 59 PM" src="https://user-images.githubusercontent.com/60198022/193248157-13e3427e-ad6a-45ff-9eb7-092d5dc611fd.png">

No additional manual test case is required as PR is related to error in response of rest api and also, automation is covered.

2022-10-28 21:33 UTC, merged