Issue 36203: Category url rewrites is not SEO friendly in multi store…
magento/magento2 pull request #36228
Opened 2022-10-03 07:07 UTC by rogerdz

… webiste

### Description (*)

### Related Pull Requests

https://github.com/magento/magento2/commit/87e41afd6ac51be7968fe8687cf132a9dbd008df
logic in $this->setCategoryStoreId($category) gives error

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36203

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-10-03 07:07 UTC, rogerdz commented
@magento run all tests

2022-10-04 08:37 UTC, rogerdz commented
@magento run all tests

2022-10-04 15:43 UTC, rogerdz commented
@magento run all tests

2022-11-23 17:13 UTC, rogerdz commented
@magento run all tests

2025-12-23 08:42 UTC, engcom-Hotel commented
@magento run all tests

2025-12-23 13:29 UTC, engcom-Hotel requested changes
Hello @rogerdz,
Thank you for your contribution!

Please have a look into the failed unit test, it seems it is failing due the PR changes.

2026-01-16 09:13 UTC, engcom-Dash commented
@magento run all tests

2026-01-19 13:06 UTC, engcom-Dash commented
Hello @rogerdz,
Thank you for your contribution!

@engcom-Hotel,
Thanks for the review.

I’ve checked the failed unit test, and it appears the failure is caused by changes that are already present in the 2.4-develop branch. As a result, the test is failing because the same behavior is being applied more than once.
<img width="3840" height="1962" alt="image" src="https://github.com/user-attachments/assets/bd07c569-7fa5-4d6b-844f-88fdcc02a6a8" />

Since the requested changes are already available in the target branch, this PR is no longer required, and I believe we can go ahead and close it.

Thank you.

2026-01-19 16:22 UTC, hostep commented
The same line was indeed introduced by https://github.com/magento/magento2/commit/96c6f2452b86ad52164df9236daf4e970d568e0a a few months after this PR got opened and this fix got released in Magento 2.4.7.

I agree we can close this. Thank you for the effort @rogerdz!

2026-01-19 16:22 UTC, closed without merging