Issue 35838: Customer is logged in but showing 404 error in frontend.
magento/magento2 pull request #36263
Opened 2022-10-10 15:26 UTC by rogerdz

### Description (*)

Remove referrer in url when current page 404, after  customer login will redirect to Customer dashboard

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35838

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-10-10 15:27 UTC, rogerdz commented
@magento run all tests

2022-10-12 03:13 UTC, edenduong requested changes
Thank you for your contribution.
Could you please check my comment.

2022-10-12 03:13 UTC, edenduong commented on app/code/Magento/Customer/Model/Url.php
> +     *  Check if Referrer url is no route url
Redundant 1 Space character after *

2022-10-12 03:13 UTC, edenduong commented on app/code/Magento/Customer/Model/Url.php
> +            'web/default/no_route',
It is better if declare `private const XML_PATH_WEB_DEFAULT_NO_ROUTE = 'web/default/no_route'`

2022-10-13 15:09 UTC, rogerdz commented
@magento run all tests

2022-10-13 15:10 UTC, rogerdz commented on app/code/Magento/Customer/Model/Url.php
> +            'web/default/no_route',
Thank you for your advice, I added change to new commit

2022-10-13 23:50 UTC, edenduong approved these changes

2022-12-19 07:31 UTC, engcom-Lima commented
@magento give me 2.4-develop instance

2022-12-19 09:10 UTC, engcom-Lima commented
@magento give me test instance

2022-12-19 10:01 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Go to frontend.
2. Add /customer/account/loginPost/ in your magento url.
3. Now click on sign In
4. Give login id and password.

**Before:** :heavy_multiplication_x: Customer is logged in but getting 404 error in FE.

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/60198022/208398472-4592ee54-42d7-4d12-bde0-4d0b07234bcd.png">

**After:** :heavy_check_mark:  Now redirecting it to cutomer dashboard page.

<img width="1251" alt="Screenshot 2022-12-19 at 2 52 52 PM" src="https://user-images.githubusercontent.com/60198022/208398273-205dedf3-af32-4a1f-ba0d-938208f9ba19.png">

**Additionally tested scenerios:**
1. Created order from the customer page.
2. Added two products to the compare list.

No additional manual test case is required as a part of regression, as this issue is related to URL.

Builds are failed hence, moving to extended testing.

2022-12-20 07:19 UTC, engcom-Echo commented
@magento run all tests

2022-12-20 11:48 UTC, engcom-Echo commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2022-12-20 15:18 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2022-12-21 05:23 UTC, engcom-Echo commented
Function Test B2B failures are different on last two run.
Run1
![image](https://user-images.githubusercontent.com/51681435/208827859-e5835f04-ea79-4851-b3b7-417f2d47ccc2.png)

Run2
![image](https://user-images.githubusercontent.com/51681435/208827838-90c18768-c17d-4c7b-a6d9-ab57502c2eee.png)

Hence Moving to `Merge In Progress`.

2024-03-21 09:46 UTC, engcom-Charlie commented
Before merge, sending it to testing again as it got move to merge after testing more than a [year](https://github.com/magento/magento2/pull/36263#issuecomment-1360873717) ago.

2024-04-05 09:38 UTC, engcom-Delta commented
@magento run all tests

2024-04-05 11:23 UTC, engcom-Delta commented
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

1.Go to frontend.
2.Add /customer/account/loginPost/ in your magento url.
3.Now click on sign In
4.Give login id and password.


**Before:** :heavy_multiplication_x: 


<img width="1440" alt="Screenshot 2024-04-05 at 2 50 50 PM" src="https://github.com/magento/magento2/assets/51681379/f83e4ca4-9210-4a02-b293-a741100dcc57">

<img width="1440" alt="Screenshot 2024-04-05 at 2 51 18 PM" src="https://github.com/magento/magento2/assets/51681379/c2ef924c-f246-4150-a8ba-0daa309816c3">

<img width="1439" alt="Screenshot 2024-04-05 at 2 51 42 PM" src="https://github.com/magento/magento2/assets/51681379/39069875-382e-46e1-a9c7-206700a913fe">

<img width="1440" alt="Screenshot 2024-04-05 at 2 51 56 PM" src="https://github.com/magento/magento2/assets/51681379/61dc7a05-5a3e-47c5-a344-cda3858e009a">

<img width="1440" alt="Screenshot 2024-04-05 at 2 52 48 PM" src="https://github.com/magento/magento2/assets/51681379/5cb59cdd-7c58-4b58-9b04-a38ae66e68b3">



**After:** :heavy_check_mark:  


<img width="1440" alt="Screenshot 2024-04-05 at 3 01 37 PM" src="https://github.com/magento/magento2/assets/51681379/9f89629f-e9eb-4cf2-8ecd-9ae30e636999">

<img width="1440" alt="Screenshot 2024-04-05 at 3 02 07 PM" src="https://github.com/magento/magento2/assets/51681379/b6f8cd29-1427-499f-a3d3-c303c7d8780e">

<img width="1440" alt="Screenshot 2024-04-05 at 3 02 27 PM" src="https://github.com/magento/magento2/assets/51681379/dc28bec4-f92e-4255-8212-d0c2bb0147b9">

<img width="1440" alt="Screenshot 2024-04-05 at 3 02 44 PM" src="https://github.com/magento/magento2/assets/51681379/3a12d7ac-b421-42ef-8f68-90aa1bdf27dc">



Builds are failed. Hence, moving this PR to **Extended Testing.**

2024-05-16 07:27 UTC, engcom-Echo commented
@magento run  Functional Tests EE, Functional Tests CE,Functional Tests B2B

2024-05-16 13:44 UTC, engcom-Echo commented
Functional Tests EE, Functional Tests CE,Functional Tests B2B build failure are different on last two run on same commit also it contain some known failures.

Functional Tests EE
Run1
<img width="1263" alt="36263-ee" src="https://github.com/magento/magento2/assets/51681435/932b5dde-17f4-4f3b-9ea8-33d3369fabb2">

Run2
<img width="1312" alt="36263-ee2" src="https://github.com/magento/magento2/assets/51681435/49d8f159-d17c-4fe8-81e8-d190e5084553">

Functional Tests CE
Run1
<img width="1408" alt="36263-ce" src="https://github.com/magento/magento2/assets/51681435/6aa43274-e92a-4cf5-a077-51db3ba73e81">
Run2
<img width="1437" alt="36263-ce2" src="https://github.com/magento/magento2/assets/51681435/5830ab22-23ec-4ab9-9362-defaad5c978d">

Functional Tests B2B
Run1
<img width="1369" alt="36263-b2b" src="https://github.com/magento/magento2/assets/51681435/90189186-92c8-4b27-bb6f-bb30dfe277d6">
Run2
<img width="1409" alt="36263-b2b2" src="https://github.com/magento/magento2/assets/51681435/3c5fa925-1018-4382-8843-5ae8e3aac757">

Hence moving it to `merge in progress`.

2024-05-28 15:06 UTC, merged