Improve performance of indexer when many attribute options
magento/magento2 pull request #36306
Opened 2022-10-16 16:33 UTC by fredden

### Description
When there are many product attribute options, the indexer takes a long time to complete. This change improves performance so that the indexing process is much quicker.

I've performed a stand-alone performance analysis between the two approaches here, and I can confirm that with 100,000 values in the `$options` array, the `foreach` approach takes around **5.527919 seconds**, whereas the `array_intersect_key` approach takes around **0.012552** seconds to produce identical results.

The real-world task that triggered this investigation (and resulted in this code change) was on a Magento 2.3.6 website with 10,000 options; reindexing before the change took around 5 minutes, and after the change the same took around 40 seconds.

### Manual testing scenarios

<details><summary>Example speed comparison script</summary>

```php
<?php

// Variables
$rounds = 10;
$optionCount = 100_000;

// Set up
$options = [];
$attributeValues = [];

for ($i = 0; $i < $optionCount; $i++) {
    $options[$i] = [
        'label' => "label $i",
        'value' => $i,
    ];

    $attributeValues[] = $i;
}

// helper for consistently-formatted numbers
function out($label, $value) {
    printf("%s\t%f\n", $label, $value);
}

// ---------------------
echo "\n\nMETHOD 1\n\n";
$timers = [];
for ($i = 0; $i < $rounds; $i++) {
    $attributeLabels = [];

    $start = microtime(true);

    foreach ($options as $option) {
        if (\in_array($option['value'], $attributeValues)) {
            $attributeLabels[] = $option['label'];
        }
    }

    $stop = microtime(true);
    $duration = $stop - $start;
    $timers[] = $duration;

    out($i, $duration);
}
out('avg', array_sum($timers) / count($timers));

// ---------------------
echo "\n\nMETHOD 2\n\n";
$timers = [];
for ($i = 0; $i < $rounds; $i++) {
    $start = microtime(true);

    $options2 = array_intersect_key($options, array_flip($attributeValues));
    $attributeLabels2 = array_column($options2, 'label');

    $stop = microtime(true);
    $duration = $stop - $start;
    $timers[] = $duration;

    out($i, $duration);
}
out('avg', array_sum($timers) / count($timers));

// ---------------------
if ($attributeLabels === $attributeLabels2) {
    echo "\n\nidentical end result\n";
} else {
    echo "\n\ndifferent end result\n";
}
```
</details>

Given there are no functionality changes in this pull request, the website should behave identically before & after the change. The main difference is in the speed of a full reindex when there are product attributes with far too many options.

The unit tests already confirm that these functions behave as expected. (Yes, I've checked that the unit tests cover these functions and behave as expected.)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2022-10-16 16:35 UTC, fredden commented
@magento run all tests

2022-10-17 09:21 UTC, fredden commented
@magento run Functional Tests B2B

2022-10-17 09:31 UTC, ihor-sviziev requested changes
@fredden, the interesting thing is that combination array_flip + foreach + isset does actually a bit better job and keeps the code more readable and understandable.

```


METHOD 1

0	4.845446
1	4.854851
2	4.852236
3	4.902424
4	4.873140
5	4.859711
6	4.904485
7	4.881590
8	4.900148
9	4.885073
avg	4.875910


METHOD 2

0	0.006829
1	0.008224
2	0.008115
3	0.008126
4	0.008648
5	0.007781
6	0.008253
7	0.008068
8	0.008447
9	0.007989
avg	0.008048


METHOD 3

0	0.007264
1	0.007498
2	0.007950
3	0.006896
4	0.007372
5	0.007233
6	0.007825
7	0.006998
8	0.007407
9	0.007240
avg	0.007368


identical end result
```

```php
<?php

// Variables
$rounds = 10;
$optionCount = 100_000;

// Set up
$options = [];
$attributeValues = [];

for ($i = 0; $i < $optionCount; $i++) {
    $options[$i] = [
        'label' => "label $i",
        'value' => $i,
    ];

    $attributeValues[] = $i;
}

// helper for consistently-formatted numbers
function out($label, $value) {
    printf("%s\t%f\n", $label, $value);
}

// ---------------------
echo "\n\nMETHOD 1\n\n";
$timers = [];
for ($i = 0; $i < $rounds; $i++) {
    $attributeLabels = [];

    $start = microtime(true);

    foreach ($options as $option) {
        if (\in_array($option['value'], $attributeValues)) {
            $attributeLabels[] = $option['label'];
        }
    }

    $stop = microtime(true);
    $duration = $stop - $start;
    $timers[] = $duration;

    out($i, $duration);
}
out('avg', array_sum($timers) / count($timers));

// ---------------------
echo "\n\nMETHOD 2\n\n";
$timers = [];
for ($i = 0; $i < $rounds; $i++) {
    $start = microtime(true);

    $options2 = array_intersect_key($options, array_flip($attributeValues));
    $attributeLabels2 = array_column($options2, 'label');

    $stop = microtime(true);
    $duration = $stop - $start;
    $timers[] = $duration;

    out($i, $duration);
}
out('avg', array_sum($timers) / count($timers));

// ---------------------
echo "\n\nMETHOD 3\n\n";
$timers = [];
for ($i = 0; $i < $rounds; $i++) {
    $attributeLabels3 = [];

    $start = microtime(true);
    $attributeValues = array_flip($attributeValues);

    foreach ($options as $option) {
        if (isset($attributeValues[$option['value']])) {
            $attributeLabels3[] = $option['label'];
        }
    }

    $stop = microtime(true);
    $duration = $stop - $start;
    $timers[] = $duration;

    out($i, $duration);
}
out('avg', array_sum($timers) / count($timers));


// ---------------------
if ($attributeLabels === $attributeLabels2 && $attributeLabels === $attributeLabels3) {
    echo "\n\nidentical end result\n";
} else {
    echo "\n\ndifferent end result\n";
}
```

2022-10-17 09:31 UTC, ihor-sviziev commented on app/code/Magento/Elasticsearch/Model/Adapter/BatchDataMapper/ProductDataMapper.php
> +        $attributeLabels = array_column($options, 'label');
```suggestion
        $attributeValues = array_flip($attributeValues);
        foreach ($options as $option) {
            if (isset($attributeValues[$option['value']])) {
                $attributeLabels[] = $option['label'];
            }
        }
```

2022-10-17 15:04 UTC, fredden commented on app/code/Magento/Elasticsearch/Model/Adapter/BatchDataMapper/ProductDataMapper.php
> +        $attributeLabels = array_column($options, 'label');
Thanks for looking into this and for the suggestion. I've updated the pull request to incorporate this change.

2022-10-17 15:04 UTC, fredden commented
@magento run all tests

2022-10-17 15:19 UTC, ihor-sviziev commented
@magento run all tests

2022-10-18 04:58 UTC, ihor-sviziev commented on app/code/Magento/Elasticsearch/Model/Adapter/BatchDataMapper/ProductDataMapper.php
> +
I believe we should revert this change as well. It doesn't make sense together with foreach
```suggestion
```

2022-10-20 08:15 UTC, ihor-sviziev commented
@magento run all tests

2022-10-26 10:03 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests look not related to changes from this PR.

2022-10-27 09:43 UTC, engcom-Lima commented
Hi @fredden ,

Thanks for your contribution and collaboration.

I have a query related to this PR. I have created a Magento setup and used Large profile for performance tool . I have almost 1063 attributes and 55 sets of products attribute sets.
When I ran indexer `bin/magento indexer:reindex catalog_product_attribute` it took 22:55 time before PR.
**Below is PR for your reference:**
<img width="1094" alt="Screenshot 2022-10-27 at 2 47 50 PM" src="https://user-images.githubusercontent.com/60198022/198249979-1fdde10a-73af-4e32-a4b0-3f02e47e403b.png">

 After taking this PR I took 15 mins.
**Screenshot:**
<img width="1133" alt="Screenshot 2022-10-27 at 2 13 37 PM" src="https://user-images.githubusercontent.com/60198022/198250065-d788eb85-c761-4a30-a046-efec1dcc8735.png">

According to the above [comment](https://github.com/magento/magento2/pull/36306#issue-1410542721) , indexer should complete less 1 min but it is not happening to my system. Please provide information if I am wrong.

Thanks

2022-10-27 16:47 UTC, fredden commented
Thanks for testing this @engcom-Lima. A 7-minute reduction in time seems like success to me. The referenced comment says: "reindexing before the change took around 5 minutes, and after the change the same took around 40 seconds." which is a 4-minute reduction in time; you're seeing better results than this. However, comparing these two results is not fair, because the two websites are very different. The speed difference that you have described is proof that this pull request improves the indexer speed.

2022-10-28 12:25 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Create large amount of data using performance fixtures.
2. Run `bin/magento indexer:reindex catalog_product_attribute` and record the time of completion.

**Before:** :heavy_multiplication_x: 
![image](https://user-images.githubusercontent.com/60198022/198586247-cb2826d5-d20c-4850-861e-cea29fb40d44.png)

**After:** :heavy_check_mark:  
![image](https://user-images.githubusercontent.com/60198022/198586322-d3b795d1-9cd4-4193-a42e-9dbed409f3ea.png)

Since it is not affecting functionality no additional manual test case is required.

2022-10-28 12:27 UTC, engcom-Lima commented
@magento create issue

2022-11-17 07:28 UTC, engcom-Hotel commented
Hello,

It seems that the issue is already taken care in this commit: https://github.com/magento/magento2/commit/859e614504da7473dc5023fff94b0c5ffbcf2a9e

Hence we are closing this PR.

Thanks

2022-11-17 07:28 UTC, closed without merging

2022-11-17 09:09 UTC, fredden commented
It looks like the commits in this pull request haven't been merged into the `2.4-develop` branch, but the contents of these has been merged in with different commit hashes. @engcom-Hotel please can you help me understand why this pull request wasn't merged via GitHub?

2022-11-17 10:36 UTC, engcom-Hotel commented
Hello @fredden,

As seen in the commit link here https://github.com/magento/magento2/commit/859e614504da7473dc5023fff94b0c5ffbcf2a9e, It looks like your changes from this PR got merged itself with the development branch. 

As it is already merged with the mainline branch, we have closed this.

Thanks