ESI blocks should be internal links
magento/magento2 pull request #36534
Opened 2022-11-25 18:56 UTC by JeroenBoersma

Rework - cherry pick off https://github.com/magento/magento2/pull/33048

Use the Base URL instead of the Base link URL when creating ESI links. Should be an internal reference.

### Description (*)
Magento default uses the `link` type which resolves the `base_link_url` which works when public facing urls, but not for internal references such as Varnish ESI requests, this is why we should use the `base_url`.

The link URL can result in 302 redirects which makes it impossible to load the ESI blocks.

### Manual testing scenarios (*)
1. Create a Magento store with a different `link url` and `base url`
2. Enable Varnish caching
3. The ESI blocks will now link to the base url instead of link url, and thereby no longer generate a 302 redirect to the base url

### Questions or comments
We have a multistore setup where the internal base url which differs from the public facing link url.
After this setup, all ESI blocks where no longer loaded, and the access log was displaying 302 redirects to the "base_url"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33059: ESI blocks should be internal links

2022-11-29 08:07 UTC, JeroenBoersma commented
@magento run all tests

2023-03-28 10:05 UTC, engcom-Hotel commented
@magento run all tests

2023-03-31 15:57 UTC, engcom-Hotel requested changes
Hello @JeroenBoersma,

It seems the build failures are due to the code changes. Request you to please resolve them.

Thanks

2023-04-04 06:53 UTC, JeroenBoersma commented
So, after 2 years + mainline changes you dare me with a simple "It seems the build failures are due to the code changes. Request you to please resolve them." Looked into that... Looks to me a error in the testing suite!

For instance: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36534/9698ee7d2d1fcb3304bec3013fc92e4b/Unit/console-error-logs.html

```
1) Magento\Reports\Test\Unit\Model\ResourceModel\Order\CollectionTest::testGetDateRangeFirstPart with data set #2 ('7d', '', '', '0 0 6 22:59:59')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'0 0 6 22:59:59'
+'0 0 6 23:59:59'
```

LGTM, also unrelated to my code, no urls involved.

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36534/9698ee7d2d1fcb3304bec3013fc92e4b/Unit/allure-report-ee/index.html#categories/8f0831c1d06562890f5ec21062dae309/ed9b8e00d0e2f336/

![image](https://user-images.githubusercontent.com/1163348/229711150-2038b49f-07c0-4eeb-9f24-c2ad7316311c.png)


EE: All of this to me is impossible to me to test "Unknown test"...

So, let me know if you have a valid report for me to work on!

2023-04-04 07:37 UTC, JeroenBoersma commented
@magento  run all tests

2023-04-10 09:35 UTC, engcom-Charlie commented
@magento run all tests

2023-04-11 06:17 UTC, engcom-Charlie commented
@magento run WebAPI Tests

2023-04-12 07:46 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2023-04-12 11:19 UTC, engcom-Charlie commented
Hi @JeroenBoersma,

Thank you for your contribution!

Can you please check once the functional test failures. Same tests are getting failed on each build. 

Functional CE:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36534/ba4a25982a869b97ecbe578dfe264f99/Functional/allure-report-ce/index.html#categories

Function B2B:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36534/289aac8bd00bd2e178e93e4468ffc25d/Functional/allure-report-b2b/index.html#categories

Functional EE: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36534/6bfdfe163e48df95d737f715a44b982f/Functional/allure-report-ee/index.html

Thank you!

2023-04-20 09:44 UTC, engcom-Echo commented
@magento run all tests

2023-04-24 04:17 UTC, engcom-Echo commented
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

2023-04-27 05:33 UTC, engcom-Echo commented
@magento run tests

2023-04-27 05:33 UTC, engcom-Echo commented
@magento run all tests

2023-05-03 09:21 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests look not related to changes from this PR.

2023-05-04 07:39 UTC, engcom-Lima commented
@magento run all tests

2023-05-12 10:47 UTC, engcom-Lima requested changes
Hi @JeroenBoersma ,

Thanks for your contribution and collaboration.

:x: QA not Passed

After taking PR changes still we are getting 302 redirect issue.

**Manual Scenario Steps**

Enable the Varnish from the configuration `Stores >> Configuration >> Advanced >> System >>Full Page cache >> Select Varnish from dropdown of Caching Application`
Create Magento store with a different link url and base url
<img width="1388" alt="image" src="https://github.com/magento/magento2/assets/60198022/2f7fbee9-38bc-45a1-8723-84837c921e0d">
Go to Frontend using Baseurl `http://local.catalogpr.com/` and click on **Search Term**

**:heavy_check_mark: Expected result After Fix**  It should not give 302 

**:x: Actual result After Fix** 
<img width="1384" alt="Screenshot 2023-05-04 at 1 00 45 PM" src="https://github.com/magento/magento2/assets/60198022/9137cbfb-974c-48fd-94d3-cd8e5e16b777">

Kindly check the issue and provide us information if we are missing anything. Also, please look into the build failures.

Thanks

2023-05-12 10:47 UTC, engcom-Lima requested changes
Hi @JeroenBoersma ,

Thanks for your contribution and collaboration.

:x: QA not Passed

After taking PR changes still we are getting 302 redirect issue.

**Manual Scenario Steps**

1. Enable the Varnish from the configuration `Stores >> Configuration >> Advanced >> System >>Full Page cache >> Select Varnish from dropdown of Caching Application`
2. Create Magento store with a different link url and base url
<img width="1388" alt="image" src="https://github.com/magento/magento2/assets/60198022/2f7fbee9-38bc-45a1-8723-84837c921e0d">
3. Go to Frontend using Baseurl `http://local.catalogpr.com/` and click on **Search Term**


**:heavy_check_mark: Expected result After Fix**  It should not give 302 

**:x: Actual result After Fix** 
<img width="1384" alt="Screenshot 2023-05-04 at 1 00 45 PM" src="https://github.com/magento/magento2/assets/60198022/9137cbfb-974c-48fd-94d3-cd8e5e16b777">

Kindly check the issue and provide us information if we are missing anything. Also, please look into the build failures.

Thanks

2023-05-16 13:38 UTC, JeroenBoersma commented
Finally some visual feedback I can work with... I do think when I first created the MR there was something else :/

I will check this out this week so we can proceed!

2023-05-29 06:14 UTC, engcom-Charlie commented
Hi @JeroenBoersma,

As per you [comment](https://github.com/magento/magento2/pull/36534#issuecomment-1549693253), did you get a chance to look into the failures.

Thank you!

2023-05-30 06:12 UTC, engcom-Charlie commented
Hi @JeroenBoersma,

Let us know when you are ready to work on it again, and we will be happy to re-open it. Closing it for now. 

Thank you for your contribution!

2023-05-30 07:56 UTC, JeroenBoersma commented
wow, this is how fast you can move apparently nowadays... i just didn't have the time yet as its more complex than I anticipated... is it just the tests... is it valid... etcetera :-p

2023-05-30 09:09 UTC, engcom-Charlie commented
Hi @JeroenBoersma,

Kindly have a look on above [comments](https://github.com/magento/magento2/pull/36534#pullrequestreview-1424246013) as well as the build failures.

If you are going to work on them, let me know I will reopen it and make it as draft. 

Thank you!

2023-05-30 09:36 UTC, engcom-Charlie commented
Hi @JeroenBoersma,

We have changed  this PR to draft and moved it in On hold, once the implementation is done let us know..we will change it to Open.

Thank you!

2023-05-30 15:31 UTC, JeroenBoersma commented
Pulling hair as the 302 redirect on those locations are expected..

If you enter `catalogsearch/result` without a query parameter it should redirect to the homepage...

`\Magento\CatalogSearch\Controller\Result\Index::execute`
```php
// ...
if ($queryText != '') {
// ...
} else {
    $this->getResponse()->setRedirect($this->_redirect->getRedirectUrl());
}
// ...
```

Will do a clean reinstall again and try to make a screencast or something :thinking: 

// edit -> added again and changed "en to and"

2023-05-30 16:07 UTC, JeroenBoersma commented
it runs successful with m2 with sampledata... re-running integration test suite to see if that differs

2023-05-30 19:05 UTC, JeroenBoersma commented
@magento give me test instance

2023-05-30 19:49 UTC, JeroenBoersma commented
Hi all, I think I followed all steps and to make sure we are looking at the same I asked Magento to create a test instance...

What I did:

Preparations:
- create test instance
- login in admin
- create second storeview
- add storecode to urls (as I don't know howto switch between stores otherwise)
- disable "checkboxes" for "use system"
- for the second store disable the checkboxes for "use website"
- set full page caching method to "varnish"
- clear caches
 
Pre-Tests:
- click around
- switch stores

Tests:
- search something
- click "search terms" in footer
- click a search term :heavy_check_mark: 
- remove search term from url :heavy_check_mark: -> redirect to home
- switch to second store: repeat last steps :heavy_check_mark: 

----

Please let me know what else I need to test, because I'm left clueless...
You can also try it if the environment is still up - it's as ready as it was moments ago...

--- 
Screenshots popular

![image](https://github.com/magento/magento2/assets/1163348/7521c5d4-33b3-4cbf-b46b-1d8cfe3d1240)

![image](https://github.com/magento/magento2/assets/1163348/42e643d5-8d93-45ea-a04c-00fdc78022b5)


Redirect home

![image](https://github.com/magento/magento2/assets/1163348/b9a66025-5a17-4974-8dd9-6fbb84cce19c)

![image](https://github.com/magento/magento2/assets/1163348/39820a44-ddc2-40ad-add1-165cd1089ade)

2023-05-30 19:51 UTC, JeroenBoersma commented
![image](https://github.com/magento/magento2/assets/1163348/b336be67-4b53-487a-8c47-68a2c799080b)

2023-05-30 20:09 UTC, JeroenBoersma commented
The only thing I could imagine... but that's maybe a little out of scope...

For some reason the referer url becomes the same as the current url... 

I manually set the referer url to the same url...

```shell
curl -v -H 'Referer: https://970675b44a1a96561e839ee9bc46b0bb.instances-prod.magento-community.engineering/default/catalogsearch/result/' https://970675b44a1a96561e839ee9bc46b0bb.instances-prod.magento-community.engineering/default/catalogsearch/result/
```

`\Magento\Store\App\Response\Redirect::_getUrl`
```php
$refererUrl = $this->_request->getServer('HTTP_REFERER');
$encodedUrl = $this->_request->getParam(ActionInterface::PARAM_NAME_URL_ENCODED)
    ?: $this->_request->getParam(ActionInterface::PARAM_NAME_BASE64_URL);

if ($encodedUrl) {
    $refererUrl = $this->_urlCoder->decode($encodedUrl);
} else {
    $url = (string)$this->_request->getParam(self::PARAM_NAME_REFERER_URL);
    if ($url) {
        $refererUrl = $url;
    }
}

if (!$this->_isUrlInternal($refererUrl)) {
    $refererUrl = $this->_storeManager->getStore()->getBaseUrl();
} else {
    $refererUrl = $this->normalizeRefererUrl($refererUrl);
}

return $refererUrl;
```

The referer is returned if set...

The result of curl:

```
> GET /default/catalogsearch/result/ HTTP/2
> Host: 970675b44a1a96561e839ee9bc46b0bb.instances-prod.magento-community.engineering
> user-agent: curl/7.81.0
> accept: */*
> referer: https://970675b44a1a96561e839ee9bc46b0bb.instances-prod.magento-community.engineering/default/catalogsearch/result/
> 
< HTTP/2 302 
< date: Tue, 30 May 2023 20:05:24 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< location: https://970675b44a1a96561e839ee9bc46b0bb.instances-prod.magento-community.engineering/default/catalogsearch/result/
< server: Apache/2.4.57 (Ubuntu)
< x-powered-by: PHP/8.1.18
< pragma: no-cache
< cache-control: max-age=0, must-revalidate, no-cache, no-store
< expires: Mon, 30 May 2022 20:05:24 GMT

```

---
this is actually a bug, but I don't think that the result will be any different without this code applied...

2023-05-30 20:14 UTC, JeroenBoersma commented
This last comment is easy to test, I disabled my one line of code and the same thing happens when curled...

```shell
curl -vk -H 'Referer: https://magento.magento2.localhost/catalogsearch/result/' https://magento.magento2.localhost/catalogsearch/result/

> GET /catalogsearch/result/ HTTP/2
> Host: magento.magento2.localhost
> user-agent: curl/7.81.0
> accept: */*
> referer: https://magento.magento2.localhost/catalogsearch/result/

< HTTP/2 302 
< server: nginx/1.25.0
< date: Tue, 30 May 2023 20:13:28 GMT
< content-type: text/html; charset=UTF-8
< set-cookie: PHPSESSID=66cb485cd7dd176d24acaa1b96e389b3; expires=Tue, 30 May 2023 21:13:28 GMT; Max-Age=3600; path=/; domain=magento.magento2.localhost; secure; HttpOnly; SameSite=Lax
< location: https://magento.magento2.localhost/catalogsearch/result/

```

2023-05-30 20:26 UTC, JeroenBoersma commented
ok, finally got the result I was looking for... took me a while

2023-05-30 20:27 UTC, JeroenBoersma commented
ok, got the same result, but also not related to this change....

this also happens when my change isn't applied...

2023-05-30 20:29 UTC, JeroenBoersma commented
so, investigating this will become a recap with new bugs :rofl:

2023-05-30 20:43 UTC, JeroenBoersma commented
Found the bug you accidentally ran into which is hidden in

`\Magento\Store\App\FrontController\Plugin\RequestPreprocessor::aroundDispatch`
```php
// ...
$baseUrl = $this->_storeManager->getStore()->getBaseUrl(
    \Magento\Framework\UrlInterface::URL_TYPE_WEB,
    $this->_storeManager->getStore()->isCurrentlySecure()
);
if ($baseUrl) {
    // phpcs:disable Magento2.Functions.DiscouragedFunction
    $uri = parse_url($baseUrl);
    if (!$this->getBaseUrlChecker()->execute($uri, $request)) {
        $redirectUrl = $this->_url->getRedirectUrl(
            $this->_url->getDirectUrl(ltrim($request->getPathInfo(), '/'), ['_nosid' => true])
        );
        $redirectCode = (int)$this->_scopeConfig->getValue(
            'web/url/redirect_to_base',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        ) !== 301 ? 302 : 301;

        $response = $this->_responseFactory->create();
        $response->setRedirect($redirectUrl, $redirectCode);
        $response->setNoCacheHeaders();
        return $response;
    }
}
// ...
```

- this checks if the base url matches, of coarse we have set a different link url
- not something related perse to my MR or I was intending to fix
- but here we are... 2 years lator :rofl: 

### next possible steps
- disable changing link urls for default, only allow on store, storeview so the admin isn't affected
- or, only check for redirect on frontend - means moving the plugin to frontend/di.xml
- check against link urls instead of base url

2023-05-30 21:25 UTC, JeroenBoersma commented
I will close the MR as I think just disabling redirects in this case also solves the purpose and save everyone from spending to much time on this...

![image](https://github.com/magento/magento2/assets/1163348/31cc4205-0cda-422c-a9a3-e83e70b2b76c)

2023-05-30 21:25 UTC, closed without merging