Add int type to $maxAge in the PageCache Kernel
magento/magento2 pull request #36600
Opened 2022-12-13 13:43 UTC by duboiss

### Description (*)
```php
    /**
     * Save cache record
     *
     * @param string $data
     * @param string $identifier
     * @param array $tags
     * @param int|bool|null $lifeTime
     * @return bool
     */
    public function save($data, $identifier, array $tags = [], $lifeTime = null);
```
Because `$lifeTime` parameter of `save()` method can't be a string.
https://github.com/magento/magento2/blob/ea0cf6395753078e45af8c4a5ddc1ea2c4d91092/lib/internal/Magento/Framework/Cache/FrontendInterface.php#L38

This would help people who override the class not to get phpstan errors but more importantly to get better typing.

2022-12-29 20:35 UTC, Den4ik requested changes
@duboiss Please sign CLA

2024-10-15 13:07 UTC, engcom-Dash commented
@magento run all tests

2024-10-24 09:58 UTC, engcom-Dash commented
It looks like the Adobe CLA is signed, so I’m moving it back to pending review.

2024-10-24 12:56 UTC, engcom-Dash commented
@magento run all tests

2025-12-24 08:56 UTC, engcom-Hotel commented
@magento run all tests

2025-12-24 09:08 UTC, engcom-Hotel requested changes

2025-12-24 09:08 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/App/PageCache/Kernel.php
> +                    (int) $maxAge
Suggestion: Cast this on assignment, casting at the point of extraction makes the type conversion more explicit and easier to trace.

2026-01-05 06:27 UTC, engcom-Dash commented
@magento run all tests

2026-01-07 11:25 UTC, engcom-Dash commented
@magento run all tests

2026-01-07 18:01 UTC, engcom-Dash commented
@magento run all tests

2026-01-08 09:53 UTC, engcom-Dash commented
@magento run all tests

2026-01-09 05:49 UTC, engcom-Dash commented on lib/internal/Magento/Framework/App/PageCache/Kernel.php
> +                    (int) $maxAge
Now I have cast the variable during the initialization.

2026-01-09 05:51 UTC, engcom-Dash commented
@engcom-Hotel 
I’ve updated the PR based on the review comments. Kindly review the latest changes so we can proceed further.

2026-01-09 12:59 UTC, Den4ik approved these changes
✅ Looks good for me.

2026-01-09 14:06 UTC, engcom-Hotel approved these changes

2026-01-13 07:09 UTC, engcom-Dash commented
@magento run all tests

2026-01-13 10:53 UTC, engcom-Dash commented
Hello @duboiss ,

Thanks for the contribution!

✔️ **QA Passed**

**Preconditions:**
Install a fresh Magento 2.4-develop.

**Manual Testing Scenarios**
Manual testing is not applicable for this change, as it only just code improvements.

Builds are failed. Hence, moving this PR to Extended Testing.

2026-01-13 10:56 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Unit Tests

2026-01-13 19:31 UTC, engcom-Dash commented
@magento create issue

2026-01-14 09:46 UTC, engcom-Dash commented
The consistent failures in Functional CE, B2B,EE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

CE
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36600/7caebde76cf9685a60430dfa1e0e53ae/Functional/allure-report-ce/index.html#categories
<img width="1713" height="194" alt="image" src="https://github.com/user-attachments/assets/36d63b23-dda4-4bc0-8373-d98c07f3fba3" />
Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36600/4b70f47f4c032c32d50d89c1e771f1ab/Functional/allure-report-ce/index.html#categories
<img width="1699" height="332" alt="image" src="https://github.com/user-attachments/assets/fde04764-5a64-4485-a307-bd48f04f7f8b" />


EE
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36600/0b0cad19d86a38c2ad1f7f146379bd0b/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1688" height="234" alt="image" src="https://github.com/user-attachments/assets/62b9a851-3b5e-4839-b75c-dfadaedef152" />
Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36600/0b663c75cf6afbfc39edd5e5ee6bc723/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1683" height="294" alt="image" src="https://github.com/user-attachments/assets/9fc77798-c817-4f74-926c-edeab8dfb46a" />

B2B
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36600/94384f98940351adb0003431fc6f36bb/Functional/allure-report-b2b/index.html#categories
<img width="1694" height="279" alt="image" src="https://github.com/user-attachments/assets/6b357525-bed4-4cda-8a66-74555acf73f4" />
Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36600/341467b33f31d780fa5867790708f6f4/Functional/allure-report-b2b/index.html#categories
<img width="1703" height="260" alt="image" src="https://github.com/user-attachments/assets/6cfcf917-a5b5-44f5-b313-de543ac6ea5b" />

Known Issue
AdminCannotAccessStockImagesWithWrongCredentialsTest [ACQE-9092](https://jira.corp.adobe.com/browse/ACQE-9092)

Hence, Moving this PR to Merge In Progress

2026-01-16 11:20 UTC, merged