Internal server error on Category graphQl query for redirect code field
magento/magento2 pull request #36693
Opened 2023-01-02 08:54 UTC by Vasudev-22

### Description (*)

1. redirect_code filed will not accept as null ,because in graphQl the field was set a mandatory with integer value.
2. If redirect_code is null in category graphQl, then it will return as Zero.
redirect_code Int!
Contains 0 when there is no redirect error. A value of 301 indicates the URL of the requested resource has been changed permanently, while a value of 302 indicates a temporary redirect.

### Related Pull Requests
Fixes for https://github.com/magento/magento2/issues/36675

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36675

### Manual testing scenarios (*)

![category_graphql](https://user-images.githubusercontent.com/104893739/210210498-61b210af-daa2-4363-9607-c470e26b5b64.png)

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-01-02 08:54 UTC, Vasudev-22 commented
@magento run all tests

2023-01-08 10:30 UTC, swnsma commented
@magento run all tests

2023-01-08 13:01 UTC, swnsma commented
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

2023-01-08 16:24 UTC, swnsma requested changes
Hi @Vasudev-22,

Thank you for your contribution!
Please check my suggestion.

According to [definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/), changes should be covered by auto-tests.
I may suggest changes in \Magento\GraphQl\CatalogUrlRewrite\RouteTest.

2023-01-08 16:24 UTC, swnsma commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
> +            if (empty($node['redirect_code'])) {
```suggestion
            if (!isset($node['redirect_code'])) {
```

2023-01-09 06:17 UTC, Vasudev-22 commented
@magento run all tests

2023-01-09 14:54 UTC, swnsma commented
Hi @Vasudev-22,

Thank you for your changes!

According to [definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/), changes should be covered by auto-tests.
I may suggest changes in \Magento\GraphQl\CatalogUrlRewrite\RouteTest.

2023-01-25 07:50 UTC, engcom-Delta commented
@magento run all tests

2023-01-25 15:54 UTC, engcom-Delta commented
@Vasudev-22 

Thank you for your contribution!

The functional test failures in B2B and CE are different from the last two run.
B2B : run1
<img width="935" alt="Screenshot 2023-01-25 at 8 54 16 PM" src="https://user-images.githubusercontent.com/51681379/214604847-7d5d28c6-b49a-434c-93f4-9a2c8a7a1ee4.png">
run2
<img width="1074" alt="Screenshot 2023-01-25 at 5 47 28 PM" src="https://user-images.githubusercontent.com/51681379/214607959-12997201-40ed-41f7-8f2b-f8eb22d75fa4.png">

CE : run1
<img width="883" alt="Screenshot 2023-01-25 at 9 20 21 PM" src="https://user-images.githubusercontent.com/51681379/214610104-9cb07ab1-d3da-4b6a-b937-114afbae24cf.png">

run2
<img width="932" alt="Screenshot 2023-01-25 at 9 14 41 PM" src="https://user-images.githubusercontent.com/51681379/214608491-6435715b-dc66-4949-b96b-f254cd54b61c.png">

Hence, moving this PR to Ready for Testing

Thanks.

2023-01-25 21:53 UTC, swnsma approved these changes

2023-01-27 06:48 UTC, engcom-Lima commented
@magento run Functional Tests B2B, Functional Tests CE

2023-01-27 09:48 UTC, engcom-Lima commented
@magento run Functional Tests CE

2023-01-27 10:55 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop` with Sample data.

**Manual testing scenario:**
-> _Run below graphQL query and check the response:_
```
{
	categories(filters: {}, pageSize: 1, currentPage: 2) {
		total_count
		items {
			available_sort_by
			uid
			level
			name
			path
			children_count
			canonical_url
			children_count
			custom_layout_update_file
			default_sort_by
			description
			display_mode
			filter_price_range
			image
			include_in_menu
			is_anchor
			landing_page
			level
			meta_description
			meta_keywords
			meta_title
			name
			path
			path_in_store
			position
			product_count
			redirect_code
			relative_url
			type
			uid
			url_key
			url_path
			url_suffix
			children {
				uid
				level
				name
				path
				children_count
				children {
					uid
					level
					name
					path
				}
			}
		}
		page_info {
			current_page
			page_size
			total_pages
		}
	}
}
```
**Before:** :heavy_multiplication_x: Getting internal server error in the response.
<img width="1376" alt="Screenshot 2023-01-27 at 12 23 10 PM" src="https://user-images.githubusercontent.com/60198022/215058016-4a08ed63-1128-4cd6-bb27-73d99eadaaad.png">


**After:** :heavy_check_mark:  Now it is working fine.
<img width="1354" alt="Screenshot 2023-01-27 at 12 40 37 PM" src="https://user-images.githubusercontent.com/60198022/215058059-6f4ac27c-de10-4cbd-ab1a-e81d03633100.png">

**Additionally tested:**

- Tested without sample data.
- Removed products and verified the error coming or not in the response.
- Removed category and verified the error coming or not in the response.

No need of additional test cases is required as part of regression.

As per [above comment ](https://github.com/magento/magento2/pull/36693#issuecomment-1403836193)failed testcases not related to the PR. Hence, moving this PR to Merge in progress.

2023-01-31 17:39 UTC, engcom-Charlie commented
It seems bot moved this PR from Merge in Progress to Ready for Testing hence moving it back.

2023-02-14 15:09 UTC, merged