Issue where filtering by date if there is a module that adds extra columns and has the created_at
magento/magento2 pull request #36711
Opened 2023-01-07 00:39 UTC by alucardatem

### Description (*)
Issue where filtering by date if there is a module that adds extra columns and has the created_at as well, it ends up with error on filtering

error: 
```main.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT COUNT(*) FROM `sales_order_grid` AS `main_table`
 LEFT JOIN `braintree_transaction_details` ON braintree_transaction_details.order_id = main_table.entity_id
 RIGHT JOIN `sales_order` ON main_table.entity_id = sales_order.entity_id WHERE  (((`created_at` >= '2022-11-01 00:00:00'))) AND (((`created_at` <= '2022-11-04 23:59:59')))```

change was proposed also in the security patches - in MDVA-38346 on git

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-02-12 15:06 UTC, Den4ik requested changes

2023-02-12 15:06 UTC, Den4ik commented on app/code/Magento/Sales/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php
> +            $fieldName = "main_table.".$subject->getConnection()->quoteIdentifier($field);
Could you please format code with spaces
```suggestion
            $fieldName = "main_table." . $subject->getConnection()->quoteIdentifier($field);
```

2023-02-12 15:07 UTC, Den4ik commented
@magento run all tests

2023-02-12 17:06 UTC, Den4ik requested changes
@alucardatem Thanks for your work on this PR.
Could you please fix failed Integrations tests

2023-02-13 09:25 UTC, alucardatem commented
Sure thing. Will do.

On Sun, 12 Feb 2023, 17:06 Denis Kopylov, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @alucardatem <https://github.com/alucardatem> Thanks for your work on
> this PR.
> Could you please fix failed Integrations tests
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/magento/magento2/pull/36711#pullrequestreview-1294749429>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAG3Y4FXH4VRVS7RP3QUBALWXEKA3ANCNFSM6AAAAAATTS7WPE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-28 06:19 UTC, engcom-Echo commented
@magento run all tests

2023-06-13 13:47 UTC, alucardatem commented
@magento run all tests

2023-06-29 16:59 UTC, alucardatem commented
#magento run Database Compare, Functional Tests CE, Integration Tests, Magento Health Index, Sample Data Tests CE, 
Semantic Version Checker, Static Tests, Unit Tests

2023-06-29 17:03 UTC, closed without merging

2024-05-13 06:42 UTC, khoimm92 commented
This issue persists on the latest version.

2024-06-10 20:17 UTC, alucardatem commented
@khoimm92 beyter apply that as a patch as since tests not running or i do not know how to make them run properly this will never get fixed