Replace YYYY in the copyright line by the current year
magento/magento2 pull request #36754
Opened 2023-01-19 08:21 UTC by amenk

Follow up for #5004

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-01-19 08:21 UTC, amenk commented
@magento run all tests

2023-01-19 17:23 UTC, ihor-sviziev requested changes

2023-01-19 17:23 UTC, ihor-sviziev commented on app/code/Magento/Theme/Block/Html/Footer.php
> +        return $this->replaceCurrentYear(__($this->_copyright));
```suggestion
        return $this->replaceCurrentYear((string)__($this->_copyright));
```

2023-01-19 17:23 UTC, ihor-sviziev commented on app/code/Magento/Theme/Block/Html/Footer.php
> +    private function replaceCurrentYear($text)
```suggestion
    private function replaceCurrentYear(string $text): string
```

2023-01-19 17:26 UTC, ihor-sviziev commented
@amenk, could you please cover this change with a unit test?

2023-01-19 17:29 UTC, amenk commented
Okay, need to find some time.
Also we should at a note on the config entry in the admin panel for the Copyright line to document this feature.

2023-01-20 07:31 UTC, amenk commented
@magento run all tests

2023-01-21 14:34 UTC, ihor-sviziev commented on app/code/Magento/Theme/Block/Html/Footer.php
> +     * Replace YYYY by the current year
```suggestion
     * Replace YYYY with the current year
     *
     * @param string $text
```

2023-01-21 14:34 UTC, ihor-sviziev commented on app/code/Magento/Theme/Test/Unit/Block/Html/FooterTest.php
>      protected function setUp(): void
```suggestion
    /**
     * @var Config
    private $scopeConfig;
    
    protected function setUp(): void
```

2023-01-21 14:36 UTC, ihor-sviziev commented
@magento run all tests

2023-01-22 10:44 UTC, ihor-sviziev approved these changes

2023-01-25 07:35 UTC, engcom-Lima commented
@magento run Functional Tests B2B

2023-01-25 07:36 UTC, engcom-Lima commented
@magento create issue

2023-01-25 11:15 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. Go to Content >> Design >> Configuration >> Edit (Global)>> Footer and Set copyright string to Copyright 2013-{YYYY} in the design config
2. Clear caches
3. Check the frontend footer.

**Before:** :heavy_multiplication_x: Current year was not displaying in the footer of frontend.
<img width="1508" alt="Screenshot 2023-01-25 at 11 11 44 AM" src="https://user-images.githubusercontent.com/60198022/214542605-758285bc-f6b4-4ad1-8900-19d913f8bd6c.png">


**After:** :heavy_check_mark:  Now displaying after taking PR changes.
<img width="1393" alt="Screenshot 2023-01-25 at 11 19 12 AM" src="https://user-images.githubusercontent.com/60198022/214542580-913c512b-5f1b-4078-981b-bdd508203ef9.png">

**Additionally tested:**

- Changed the theme and verified the footer.
- Created order from guest and customer.
- Invoice,shipped and credit memo of the order from the admin.

No additional manual test case is required as part of regression.

Build is failed hence, moving this PR to extended testing.

2023-01-27 03:26 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2023-01-27 06:21 UTC, engcom-Echo commented
Functional Tests B2B failure are different on last two run.
Run1
![image](https://user-images.githubusercontent.com/51681435/215018784-bd276722-3340-41ff-a834-a0d9ffd97d28.png)

Run2
![image](https://user-images.githubusercontent.com/51681435/215018755-18e299f3-5f2b-4b6c-8e7a-eea93d76d129.png)

Hence moving to `Merge In Progress`.

2023-01-30 11:59 UTC, fredden approved these changes

2023-01-31 05:26 UTC, engcom-Lima commented
Looking like bot moved to Ready for Testing. Hence, moving back to Merge in progress.

2023-03-07 15:29 UTC, engcom-Charlie commented
It seems that bot moved this PR from Merge in Progress to Ready for Testing on assignment, hence moving it back.

Thank you!

2023-03-31 19:08 UTC, merged