Fix `Call to a member function getId() on int`
magento/magento2 pull request #36769
Opened 2023-01-23 16:41 UTC by convenient

```
Call to a member function getId() on int
Exception in vendor/magento/module-customer/Block/Adminhtml/Edit/Tab/Newsletter.php:421
```

The definition for `getCustomerId` always casts it as an `int` so doing `$customer->getId()` on it is destined to fail.

We had some custom code which called `getStatusChangedDate` when viewing a customer within the admin panel, which highlighted this call does not work.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-01-23 16:41 UTC, convenient commented
@magento run all tests

2023-01-24 17:19 UTC, convenient commented
@magento run all tests

2023-01-25 06:44 UTC, convenient commented
@magento run Functional Tests EE, Functional Tests B2B

2023-01-25 10:34 UTC, convenient commented
@magento run Functional Tests B2B

2023-01-26 10:51 UTC, convenient commented
@magento run Functional Tests B2B

2023-02-01 17:31 UTC, hws47a requested changes
Hi @convenient!

Thank you for your contribution. 

The change looks good but unfortunately it cannot be approved until it meet [Definition of Done criteria](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1)
> All changes must be covered by automated tests if possible.

You can write a simple test in `app/code/Magento/Customer/Test/Unit/Block/Adminhtml/Edit/Tab/NewsletterTest.php` similar to `testInitFormWithCustomerFormData` (but much simpler) to cover `getStatusChangedDate()` method.

Let me know if you need any help.

2023-03-02 15:50 UTC, convenient commented
@magento run all tests

2023-03-03 16:55 UTC, convenient commented
@magento run static tests, unit tests

2023-03-03 20:10 UTC, convenient commented
@magento run static tests

2023-03-04 06:39 UTC, convenient commented
@magento run all tests

2023-03-05 07:59 UTC, convenient commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2023-03-05 11:09 UTC, convenient commented
@magento run Functional Tests B2B, Functional Tests EE

2023-03-05 16:23 UTC, convenient commented
@magento run Functional Tests B2B, Functional Tests EE

2023-03-06 09:14 UTC, convenient commented
@magento run Functional Tests B2B, Functional Tests EE

2023-03-06 15:23 UTC, convenient commented
@magento run Functional Tests B2B

2023-03-07 04:35 UTC, convenient commented
@magento run Functional Tests B2B

2023-03-07 06:43 UTC, convenient commented
@magento run Functional Tests B2B

2023-03-07 09:13 UTC, convenient commented
@magento run Functional Tests B2B

2023-03-08 09:22 UTC, convenient commented
@magento run Functional Tests B2B

2023-03-08 14:31 UTC, convenient commented
@magento run Functional Tests B2B

2023-03-08 16:53 UTC, convenient commented
@magento run Functional Tests B2B

2023-03-09 09:02 UTC, convenient commented
Hey @hws47a 

Test added, that flaky `Functional Tests B2B` job is a massive pain! 😓

2023-03-27 09:14 UTC, engcom-Charlie commented
Hi @convenient,

Thank you for the contribution!

It seems that the new automation test has been added. Hence requesting for the review.

Thank you!

2023-03-28 06:51 UTC, engcom-Hotel approved these changes
The changes look good. Hence approving the PR.

2023-03-29 05:36 UTC, engcom-Lima commented
@magento run all tests

2023-04-19 08:30 UTC, engcom-Echo commented
:heavy_check_mark: QA Passed
Fix Call to a member function getId() on int

**Manual testing scenario:**
1. Create custom module and call `getStatusChangedDate` https://github.com/magento/magento2/blob/6729b6e01368248abc33300208eb292c95050203/app/code/Magento/Customer/Block/Adminhtml/Edit/Tab/Newsletter.php#L415-L424

**Before:** :heavy_multiplication_x: 
<img width="739" alt="Screenshot 2023-04-19 at 1 58 22 PM" src="https://user-images.githubusercontent.com/51681435/233016146-13749936-d49e-462f-8251-cbc447672e44.png">

<img width="1310" alt="Screenshot 2023-04-19 at 1 08 50 PM" src="https://user-images.githubusercontent.com/51681435/233015863-79713ae8-b930-4542-b8f1-672e9f41d06a.png">

**After:** :heavy_check_mark:  
No error is seen.
<img width="715" alt="Screenshot 2023-04-19 at 1 51 57 PM" src="https://user-images.githubusercontent.com/51681435/233016280-9aa117e0-2c75-4a1e-9afa-120128dfdf7f.png">

There are build failures Hence moving to `Extended Testing`

2023-04-19 08:31 UTC, engcom-Echo commented
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

2023-04-19 09:44 UTC, hws47a commented on app/code/Magento/Customer/Test/Unit/Block/Adminhtml/Edit/Tab/NewsletterTest.php
> +        $this->assertEquals('', $this->model->getStatusChangedDate());
It seems like the test only covers the case where `getChangeStatusAt` returns `''` and therefore `getStatusChangedDate()===''`. 
Could you please also cover a case with not-empty data?

2023-04-19 10:36 UTC, engcom-Echo commented
Functional Tests B2B failure are different on last two run on same commit.
Run1
<img width="1404" alt="36769-B2B" src="https://user-images.githubusercontent.com/51681435/233047393-59ff0268-82cb-4fa5-8dbf-e6a1bc38b136.png">

Run2
<img width="1161" alt="36769-B2B2" src="https://user-images.githubusercontent.com/51681435/233047412-8a2a3d31-af0f-458b-a5be-66cdf444a607.png">

Hence moving to `Merge In Progress`

2023-04-20 09:42 UTC, engcom-Echo commented
@magento run all tests

2023-04-20 10:07 UTC, hws47a commented on app/code/Magento/Customer/Test/Unit/Block/Adminhtml/Edit/Tab/NewsletterTest.php
> +                ['Nov 22, 2023, 1:00:00 AM','Nov 22, 2023, 1:00:00 AM']
To make sure that formatDate is run, it's better to make expected value different to `getChangeStatusAt`

2023-04-20 10:07 UTC, hws47a commented on app/code/Magento/Customer/Test/Unit/Block/Adminhtml/Edit/Tab/NewsletterTest.php
> +        $this->localeDateMock->method('formatDateTime')->willReturn($statusDate);
And ensure that the `getChangeStatusAt` value is provided to the formatDate
```suggestion
        $this->localeDateMock->method('formatDateTime')->with($statusDate)->willReturn($statusDate);
```

2023-04-20 10:48 UTC, engcom-Echo commented
@magento run all tests

2023-04-20 10:52 UTC, engcom-Charlie commented
@magento run all tests

2023-04-20 10:56 UTC, hws47a approved these changes

2023-04-20 10:58 UTC, engcom-Echo commented
@magento run all tests

2023-04-20 11:07 UTC, Indraniks commented
@magento run all tests

2023-04-20 13:10 UTC, engcom-Echo commented
@magento run all tests

2023-04-21 05:01 UTC, engcom-Echo commented
@magento run WebAPI Tests,Functional Tests CE

2023-05-14 00:19 UTC, merged