[WIP] Set price on quote item instead of base_price
magento/magento2 pull request #36878
Opened 2023-02-16 17:35 UTC by hostep

### Description (*)
For some unknown reason, a quote item's price gets incorrectly set to the base_price instead of the price.
Which means that if you have multiple currencies in one website on the frontend, both price & base_price are in the base currency. We would expect the price to be in the other currency and not the base currency.

The comment above seems to indicate this was done on purpose, but I have no idea why.

This is a WIP PR, just to try to run the tests and see if they reveal anything interesting that might get broken by this change.

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)
TODO

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-02-16 17:36 UTC, hostep commented
@magento run all tests

2023-02-16 22:58 UTC, hostep commented
None of the failing tests seem to indicate a problem so far, they are all flaky results I think:
- Functional Tests B2B:
  - MC-73: Admin should be able to create a cart price rule of type Buy X get Y free: `Waited for 60 secs but text '-$123.00' still not found`
  - MC-62: Admin should be able to create a cart price rule of type Fixed amount discount: `Waited for 60 secs but text '-$20.00' still not found`
- Functional Tests CE:
  - MC-40397: Checking vat id field at account create page with 'Check Out with Multiple Addresses': `element not interactable (Session info: chrome=103.0.5060.114)`
- Integration Tests:
  - Magento\Company\LoggingTest::testEditCompanyActionLogging: `Failed asserting that '2023-02-16 18:26:59' contains "2023-02-16 18:27".`
- Functional Tests EE:
  - No idea, takes too long, has been running for almost 3 hours now, I need to get some sleep

Just to be sure, let's try to run these again to be sure ...

@magento run Functional Tests B2B, Functional Tests CE, Integration Tests, Functional Tests EE

2023-02-17 06:32 UTC, hostep commented
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests, Functional Tests EE

2023-02-17 11:04 UTC, hostep commented
Only Functional Tests B2B is failing now with:
```Failed asserting that any element by '//*[@id='cart-totals']//tr[@class='grand totals']//td//span[@class='price']' on page /checkout/cart/
Elements: 
+ <span> $10.00
contains text '$15.00'
```

&

```
stale element reference: element is not attached to the page document
  (Session info: chrome=103.0.5060.114)
```


Let's try that one again

@magento run Functional Tests B2B

2023-02-17 11:05 UTC, hostep commented
@magento run Functional Tests B2B

2023-02-17 13:42 UTC, hostep commented
Since all tests passed, can we assume that nothing broke by doing this change?
Or does it mean that there were no tests specific for this and there can be issues after this change?

2023-10-12 19:33 UTC, hostep commented
Rebased on latest `2.4-develop`, tested and verified, updated description with how to test. I'm unable to figure out how to write a quick unit test for this in less than 10 minutes. So if somebody could give some pointers or be of assistance or add a test to the PR, feel free to do so.

2023-10-12 19:34 UTC, hostep commented
@magento run all tests

2023-10-17 11:14 UTC, engcom-Hotel commented
@magento create issue

2025-05-16 05:33 UTC, engcom-Hotel commented
@magento run all tests

2025-05-16 09:33 UTC, engcom-Hotel requested changes
Thanks @hostep for the contribution!

The PR changes looks good to me. 

For automated test, let me ask the internal team member to add the same. @engcom-Dash please do the needful.

Thanks

2025-05-20 07:23 UTC, engcom-Dash commented
@magento run all tests

2025-05-21 06:52 UTC, engcom-Dash commented
@magento run all tests

2025-05-21 10:39 UTC, engcom-Dash commented
@magento run all tests

2025-05-21 10:42 UTC, engcom-Dash commented
@magento run Database Compare

2025-05-21 10:52 UTC, hostep commented
If anyone wonders about the changes from [this commit](https://github.com/magento/magento2/pull/36878/commits/030917f2975484d2d0d9cc38787ec734a055bb78), here's some context:

![Screenshot 2025-05-21 at 12 51 52](https://github.com/user-attachments/assets/326e58b0-c2ca-498d-b174-41327296c5b2)

2025-05-22 04:50 UTC, engcom-Dash commented
Helllo @hostep & @engcom-Hotel,

As discussed in the slack chat, I have added [commit](https://github.com/magento/magento2/pull/36878/commits/030917f2975484d2d0d9cc38787ec734a055bb78) to address the minicart item price issue.

Also @engcom-Hotel I can see a Unit Test has been already added for the  updateItemTaxInfo() in the app/code/Magento/Tax/Test/Unit/Model/Sales/Total/Quote/CommonTaxCollectorTest.php. let me know anything more needed from my side. 

I feel the failing tests are not related to the changes done in this PR. Could you please review the PR. ?

2025-05-22 10:52 UTC, engcom-Hotel approved these changes

2025-05-23 10:12 UTC, engcom-Bravo commented
Hi @hostep,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**


- Have 2 storeviews
- Configure "Stores > Configuration > General > Currency Setup" so that one of the 2 storeviews use different currency then the "default" values
- Check in backoffice under "Stores > Currency > Currency Rates" that the 2 currencies aren't exactly the same rate, if they are the same, manually add some dummy exchange rate
- Create a new product, give it a price of 100
- Reindex, flush caches
- In frontend, visit the product on the 2 different storeviews, you should see 2 different prices and currencies if all goes well.
- On the storeview where the currency isn't the same as the "default" value, put the product in the cart
- Now inspect the database, the table quote_item, the columns price and base_price
- It's expected that the values aren't the same, the base_price should contain 100, the price should contain the value from the other currency.



**Before:** :heavy_multiplication_x:


<img width="1430" alt="Screenshot 2025-05-23 at 2 24 15 pm" src="https://github.com/user-attachments/assets/d827b782-192d-4afd-bf81-445d90808566" />

<img width="963" alt="Screenshot 2025-05-23 at 2 24 39 pm" src="https://github.com/user-attachments/assets/4c7a4963-015c-48c1-b53e-0ff34b89f953" />

**After:** :heavy_check_mark: 

<img width="963" alt="Screenshot 2025-05-23 at 2 33 44 pm" src="https://github.com/user-attachments/assets/7980198d-36eb-46a4-90e5-323b7b597b17" />


<img width="1438" alt="Screenshot 2025-05-23 at 2 34 04 pm" src="https://github.com/user-attachments/assets/c24e3257-5cba-40d9-918c-2e65d419ffb3" />





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-05-26 05:55 UTC, engcom-Dash commented
@magento run all tests

2025-05-26 08:29 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

2025-05-26 11:41 UTC, engcom-Dash commented
The consistent test failures for **Functional B2B** are known Issues and JIRA is raised for them. other failures are inconsistent. They neither part of PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36878/e4bde7874855d027f9d8c4220c73fc02/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/1e22914a-bec6-4b42-9d86-4255a8f19d16)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36878/da1f67b4887c0adaa8bd6017295705a3/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/dba14096-014b-47c0-9da7-6c2c0d64dec6)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)
StoreFrontSimpleProductWithSpecialAndTierDiscountPriceTest : [ACQE-7971](https://jira.corp.adobe.com/browse/ACQE-7971)
OrderWithMultipleConfigurableProductsAdditionalStockTest : [ACQE-8060](https://jira.corp.adobe.com/browse/ACQE-8060)

The consistent test failures for **Functional CE** is known Issues and JIRA is raised for the same. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36878/5527c791ed8bf06538803928839a79ad/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/af5d2300-8933-47ac-b039-0f2cb8c9e48a)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36878/3e031a592b5e8d8c57cfe0d958a15ad4/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="1425" alt="Screenshot 2025-05-26 at 4 54 42 PM" src="https://github.com/user-attachments/assets/75877b54-00b6-425d-8e97-e061e2acf743" />

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)


The consistent test failure for **Functional EE** is known Issues and JIRA is raised for the same. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36878/255e35f84ceff7356b9c9eb88d46cd09/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/649ecabf-b7d7-4e2b-aecd-bd9d212a1ee7)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36878/3c029fbe3b815bb56edca9ba9a4350c7/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/6934d76c-1487-4495-ac5c-4ecd33766258)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

Hence moving this PR in Merge In Progress.

2025-07-02 13:10 UTC, merged