Issue 31043: Elastic Search interferes with the default sort order of products (changing newest first to oldest first)
magento/magento2 pull request #36900
Opened 2023-02-21 14:41 UTC by rogerdz

### Description (*)

Add sorting condition by product id desc

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31043

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-02-21 14:49 UTC, rogerdz commented
@magento run all tests

2023-02-22 02:20 UTC, rogerdz commented
@magento  run all tests

2023-02-22 06:09 UTC, rogerdz commented
@magento give me test instance

2023-02-22 07:50 UTC, rogerdz commented
@magento run all tests

2023-02-22 07:59 UTC, Viper9x commented
@magento give me test instance

2023-02-22 09:33 UTC, Viper9x commented
@magento give me test instance

2023-02-22 10:42 UTC, Viper9x commented
I confirmed this PR resolved issue #31043. Special thanks to @rogerdz for providing the fix.

2023-02-23 01:52 UTC, rogerdz commented
@magento run all tests

2023-02-23 06:12 UTC, rogerdz commented
@magento run Functional Tests B2B, Functional Tests CE , Functional Tests EE

2023-02-25 08:26 UTC, rogerdz commented
@magento run all tests

2025-01-29 20:04 UTC, Den4ik commented
@rogerdz Could you please resolve conflict?

2025-05-21 13:38 UTC, engcom-Hotel commented
Hello @rogerdz,

We request you to please resolve the conflicts on this PR, so that we can proceed further with this. Meanwhile moving this PR `On Hold`.

Thanks

2025-05-22 07:55 UTC, rogerdz commented
@magento run all tests

2025-05-28 06:02 UTC, engcom-Hotel commented
@magento run all tests

2025-05-28 12:01 UTC, engcom-Hotel requested changes
Hello @rogerdz,

The changes seems good to us, but please refer to the below review comments:
- It seems some automated tests are failing due to the changes
- Consider making the default sort order configurable if different deployments require different behaviors.
- Add/modify an integration test to assert search results default to descending order by entity_id.
- Update the comment above the line to specify "newest first" for clarity.

2025-06-10 15:42 UTC, engcom-Hotel commented
Hello @rogerdz,

Have you got a chance to look into this PR?

Thanks

2025-06-10 16:29 UTC, rogerdz commented
Hi @engcom-Hotel, 

Yes, I’ve seen it, but I’m currently tied up with something else. I haven’t had a chance to go through it properly yet.

2025-06-23 07:35 UTC, engcom-Hotel commented
Hello @rogerdz,

Gentle reminder on the review comments on this PR [here](https://github.com/magento/magento2/pull/36900#pullrequestreview-2874733260).

Thanks

2025-07-07 09:17 UTC, engcom-Dash commented
@magento run all tests

2025-07-09 05:22 UTC, engcom-Dash commented
Hello @rogerdz,

I wanted to check if you are working on the automated test coverage & the functional test failures. If not, Can I take care of them? Just let me know what works best for you. 

Also, please note that [As mentioned in the above review comment point 2](https://github.com/magento/magento2/pull/36900#pullrequestreview-2874733260) We should add a store configuration for sort order keeping default value as Ascending to maintain backward compatibility. For automated test we are going to add functional Test which will be handling the scenario for desc order.

Please let me know if I can proceed with the changes or not?

Thanks!

2025-07-09 07:24 UTC, engcom-Dash commented
Hello @rogerdz,

I am taking care of the review comments. Thanks!

2025-07-09 08:00 UTC, engcom-Dash commented
@magento run all tests

2025-07-09 10:21 UTC, engcom-Dash commented
@magento run all tests

2025-07-09 12:54 UTC, engcom-Dash commented
Hello @engcom-Hotel I have fixed all the failed automated test because of the changes done in PR. Also added automated test to verify the descending sort order functionality. Also taken care of the review comments. The 4th point is not included in the changes becuase that is no longer applicable since we are fetching the value from configuration.

Could you please review the changes ? Moving this PR for review.

Thanks!

2025-07-09 14:18 UTC, engcom-Hotel commented
@magento run all tests

2025-07-10 09:31 UTC, engcom-Hotel approved these changes

2025-07-11 09:49 UTC, engcom-Bravo commented
@magento run all tests

2025-07-11 10:33 UTC, engcom-Bravo commented
Hi @rogerdz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Create a category in Magento with several products in it, all have the position in the category set to the value 1
- Go to category page


**Before:** :heavy_multiplication_x: 

<img width="1348" height="674" alt="Screenshot 2025-07-11 at 3 12 32 pm" src="https://github.com/user-attachments/assets/835c06be-2c4f-4ffd-adb9-dc128c3f0e9b" />

<img width="1348" height="674" alt="Screenshot 2025-07-11 at 3 12 43 pm" src="https://github.com/user-attachments/assets/95911753-e2fb-4e39-99f8-2eebd285902f" />




**After:** :heavy_check_mark: 

<img width="1377" height="123" alt="Screenshot 2025-07-11 at 3 18 19 pm" src="https://github.com/user-attachments/assets/52da18e1-2394-427b-9d76-6107b5ee9eb8" />
<img width="1348" height="674" alt="Screenshot 2025-07-11 at 3 18 04 pm" src="https://github.com/user-attachments/assets/58c579f8-e7ff-450b-bfeb-fec1450bbc59" />








Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-07-14 09:15 UTC, engcom-Dash commented
Since we have introduced a new store configuration, SVC is failing because of it hence created internal approval [JIRA](https://jira.corp.adobe.com/browse/AC-15135) for the same.

SVC: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/d2058a4e8bad2a103834a381c079f900/SemanticVersionChecker/report-magento2.html

<img width="1702" height="898" alt="Screenshot 2025-07-14 at 2 26 01 PM" src="https://github.com/user-attachments/assets/ff9cc4d3-a00e-4ca7-8ca2-2673c5ef6473" />

hence moving this PR in Pending Approval.

2025-07-14 10:16 UTC, Den4ik requested changes
Hi @rogerdz 
Could you please review my comment

2025-07-14 10:16 UTC, Den4ik commented on app/code/Magento/Catalog/Model/Config/Source/SortOrder.php
> +            ['value' => 'DESC', 'label' => __('Descending')],
In my opinion constant usage `Select::SQL_ASC` or `Collection::SORT_ORDER_ASC` is more preferable

2025-08-21 10:36 UTC, engcom-Dash commented
@magento run all tests

2025-08-21 12:36 UTC, engcom-Dash commented
We have received all the required approvals on [JIRA](https://jira.corp.adobe.com/browse/AC-15135). Hence moving this PR to changes requested to address the review comments.

2025-08-22 10:07 UTC, engcom-Dash commented
@magento run all tests

2025-08-22 12:53 UTC, engcom-Dash commented
Hello @Den4ik & @engcom-Hotel, I have updated the PR with requested changes.Could you please review the changes. The failing functional Tests are not related to the changes done in this PR.

Moving this PR to Pending review.

Thanks

2025-08-25 00:24 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Semantic Version Checker

2025-08-25 05:11 UTC, Den4ik approved these changes
Hi @rogerdz, @engcom-Dash 
Thanks for update. Changes looks good for me.
Failed Functional Tests seems are not related to changes.
Semantic Version check failed due to new element in system.xml

2025-08-25 08:02 UTC, engcom-Dash commented
As the testing of this PR is already done, moving this PR to Extended Testing to further procced on this PR.

2025-08-25 08:44 UTC, engcom-Dash commented
@magento run all tests

2025-08-25 11:12 UTC, engcom-Dash commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2025-08-25 14:07 UTC, engcom-Dash commented
The consistent failures in Functional B2B are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes
 
Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/571e2866b5710188bd6fef735eea8f67/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2474" height="878" alt="image" src="https://github.com/user-attachments/assets/e2546cee-15d1-471c-ae7e-9c7f49168e9e" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/4ddc88672fb4dbae1ed2befe496c33cd/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2788" height="1302" alt="image" src="https://github.com/user-attachments/assets/722f4563-c8dc-4552-8263-32e243dfa051" />

Known Issues: 
AdminStagingDashboardProvideAbilityToViewEditForUpdatesWithCartPriceRuleTest [ACQE-8610](https://jira.corp.adobe.com/browse/ACQE-8610)
ViewportSwitcherMobileHTMLThroughBlockContentTypeTest [ACQE-8608](https://jira.corp.adobe.com/browse/ACQE-8608)
BlockRenderHTMLThroughBlockContentTypeTest [ACQE-8609](https://jira.corp.adobe.com/browse/ACQE-8609)
AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

The consistent failures in Functional CE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/214b8a8e9bd9615bdc7ccb0e4b1ea2cf/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2646" height="624" alt="image" src="https://github.com/user-attachments/assets/b8630706-0bd4-480b-8b01-70dd44ddf3d2" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/9bf822d97550e60e56d29b8b5754583d/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2598" height="632" alt="image" src="https://github.com/user-attachments/assets/99e3a010-8e73-4fc1-ac2b-fbd980d884d3" />

Known Issues: 
StorefrontDeleteSimpleAndVirtualProductFromMiniShoppingCartTest [ACQE-8560](https://jira.corp.adobe.com/browse/ACQE-8560)
ViewportSwitcherMobileHTMLThroughBlockContentTypeTest [ACQE-8608](https://jira.corp.adobe.com/browse/ACQE-8608)
BlockRenderHTMLThroughBlockContentTypeTest [ACQE-8609](https://jira.corp.adobe.com/browse/ACQE-8609)

The consistent failures in Functional EE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/b8952f3941cbfbeff483c92f05aaa68c/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2856" height="1362" alt="image" src="https://github.com/user-attachments/assets/453bbbff-1185-4e7f-9327-4d5d629f942a" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/ead899ab5ba8999ce32a9bd6d6302537/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2694" height="874" alt="image" src="https://github.com/user-attachments/assets/9ab7c09e-620f-49f6-a837-b9829bd6f592" />

Known Issues: 
AdminStagingDashboardProvideAbilityToViewEditForUpdatesWithCartPriceRuleTest [ACQE-8610](https://jira.corp.adobe.com/browse/ACQE-8610)
ViewportSwitcherMobileHTMLThroughBlockContentTypeTest [ACQE-8608](https://jira.corp.adobe.com/browse/ACQE-8608)
BlockRenderHTMLThroughBlockContentTypeTest [ACQE-8609](https://jira.corp.adobe.com/browse/ACQE-8609)
AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

2025-08-25 14:10 UTC, engcom-Dash commented
Also, We have received all the required approval on the [JIRA](https://jira.corp.adobe.com/browse/AC-15135). Hence moving this PR in **Merge In Progress**.

2025-10-07 14:11 UTC, engcom-Dash commented
@magento run all tests

2025-11-19 17:37 UTC, merged