Feature/php8.1 constructor property promotion wee graph ql
magento/magento2 pull request #36975
Opened 2023-03-06 17:48 UTC by leonhelmus

### Description (*)

Replace allmost all properties with constructor property promotion in module wee graph ql:
https://stitcher.io/blog/constructor-promotion-in-php-8

* Readable code
* Make Magento less complex by removing properties which take up a lot of lines.
* Imported all classes to make code more readable.
I think the code would be a lot cleaner if all modules start using constructor promotions, since of 2.4.6 php 7.4 is dropped we can now make use of it. So let's start on it right now :).

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-03-06 17:48 UTC, leonhelmus commented
@magento run all tests

2023-05-25 08:40 UTC, ihor-sviziev approved these changes

2023-05-25 08:45 UTC, ihor-sviziev requested changes

2023-05-25 08:45 UTC, ihor-sviziev commented on app/code/Magento/WeeeGraphQl/Model/Resolver/FixedProductTax.php
> +        private TaxHelper $taxHelper
```suggestion
        private readonly Data $weeeHelper,
        private readonly TaxHelper $taxHelper
```

2023-05-25 08:45 UTC, ihor-sviziev commented on app/code/Magento/WeeeGraphQl/Model/Resolver/Quote/FixedProductTax.php
> +        private TaxHelper $taxHelper
```suggestion
        private readonly Data $weeeHelper,
        private readonly TaxHelper $taxHelper
```

2023-05-25 08:45 UTC, ihor-sviziev commented on app/code/Magento/WeeeGraphQl/Model/Resolver/StoreConfig.php
> +        private TaxHelper $taxHelper
```suggestion
        private readonly Data $weeeHelper,
        private readonly TaxHelper $taxHelper
```

2023-05-25 08:50 UTC, ihor-sviziev commented
@magento run all tests

2023-05-30 07:18 UTC, ihor-sviziev approved these changes
✔ Approved.

Failing tests look not related to changes from this PR.

2024-09-25 09:20 UTC, engcom-Dash commented
@magento run all tests

2024-09-25 11:37 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE

2024-09-25 11:53 UTC, engcom-Dash commented
Hello @leonhelmus 

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:
Install fresh Magento 2.4-develop

Steps to reproduce
- Set up FPT(Fixed Product Taxes)
- Fixed Product Taxes should be visible in products Graphql response.
- Store config details for FPT should be visible in respective GraphQL response.

Before: ✖️
N/A

After: ✔️
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/be96ce00-631c-4153-889e-6eacd4d46b0d">
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/33b355a6-2631-4892-8821-2a8446b41dc0">

Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

2024-09-25 11:55 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE

2024-09-25 13:18 UTC, engcom-Dash commented
@magento run Adobe CLA Signed

2024-09-25 13:19 UTC, engcom-Dash commented
Hello @leonhelmus, please sign CLA.

2024-09-25 13:28 UTC, leonhelmus commented
@engcom-Dash I have now signed a CLA

2024-09-26 07:09 UTC, engcom-Dash commented
@magento run all tests

2024-09-26 07:11 UTC, engcom-Dash commented
@magento run all tests

2024-10-03 10:59 UTC, engcom-Dash commented
@magento run all tests

2024-10-04 10:16 UTC, engcom-Dash commented
@magento run Integration Tests, Functional Tests EE, Functional Tests CE

2024-10-04 13:26 UTC, engcom-Dash commented
Moving to merge in progress.
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/e1b0c27b-99ea-4cdf-9b22-43507c282f9f">

2024-10-29 08:32 UTC, engcom-Dash commented
@magento create issue

2025-02-24 07:34 UTC, merged