Chore: WEEE - Replace Block Escaping with Escaper
magento/magento2 pull request #37044
Opened 2023-03-09 01:26 UTC by pykettk

### Description (*)
Refactors the `Magento_Weee` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2023-03-09 01:42 UTC, pykettk commented
@magento create issue

2023-03-10 17:18 UTC, andrewbess approved these changes
Hello @pykettk 
Thank you for your contribution

2023-03-15 05:50 UTC, engcom-Lima commented
@magento run all tests

2023-03-17 23:58 UTC, leonhelmus requested changes
I think it would be nice if you import that you also import the other ones with a readable name.

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/items/price/row.phtml
> +declare(strict_types=1);
missing new line above copyright

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/items/price/row.phtml
> +/** @var $_weeeHelper Data */
please swap $_weeeHelper with Data in some EDI this does not work.

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/items/price/row.phtml
> +/** @var $_weeeHelper Data */
I would use a alias instead Data. The alias could be WeeeHelper.

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/items/price/unit.phtml
>  /** @var $_weeeHelper \Magento\Weee\Helper\Data */
Maybe resolve this one as well since you did in previous as well :)

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/order/create/items/price/total.phtml
> +$_weeeHelper = $this->helper(Data::class);
Maybe resolve this one as well since you did in previous as well :)

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/order/create/items/price/total.phtml
> +$_weeeHelper = $this->helper(Data::class);
import Data as a alias instead

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/order/create/items/price/unit.phtml
>                  <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($_item) as $tax) : ?>
import this one just like the first template.

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/renderer/tax.phtml
>  /** @var \Magento\Framework\Json\Helper\Data $jsonHelper */
import this variable.

2023-03-17 23:58 UTC, leonhelmus commented on app/code/Magento/Weee/view/adminhtml/templates/renderer/tax.phtml
>  /** @var \Magento\Directory\Helper\Data $directoryHelper */
import this variable.

2023-03-18 09:43 UTC, pykettk commented
@leonhelmus I will not be making these changes. My only concern was to replace the deprecated functionality. While I _have_ tidied up some of the files, that is entirely secondary.

2023-03-18 10:10 UTC, leonhelmus commented
Alright 👍,  than it looks fine to me.

2023-03-18 10:10 UTC, leonhelmus approved these changes

2023-08-17 18:21 UTC, closed without merging