Improve enabledFlat check when there are a lot of categories
magento/magento2 pull request #37185
Opened 2023-03-10 14:47 UTC by igorwulff

For the menu block the call to `if ($this->flatState->isAvailable()) {` can cost up to 20ms if more then 1k of categories are loaded. This can be optimized by keeping track of the isAvailable return value depending on the used storeId.

A similar approach is done in `vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php` 

This is a minor improvement, but still worthwhile in my opinion.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-03-10 14:50 UTC, igorwulff commented
@magento run all tests

2023-03-10 15:20 UTC, igorwulff commented
@magento run all tests

2023-03-18 16:30 UTC, leonhelmus requested changes

2023-03-18 16:30 UTC, leonhelmus commented on app/code/Magento/Catalog/Model/Category.php
> +    private function isEnabledFlat()
Missing strict type return argument.

2023-03-18 16:30 UTC, leonhelmus commented on app/code/Magento/Catalog/Model/Category.php
> +    private static $flatEnabled = [];
please strict type this class property.

2023-03-29 07:30 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Category.php
> +    private static $flatEnabled = [];
```suggestion
    private static array $flatEnabled = [];
```

2023-03-29 07:30 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Category.php
> +    private function isEnabledFlat()
```suggestion
    private function isEnabledFlat(): bool
```

2023-04-04 10:02 UTC, ihor-sviziev commented
@magento run all tests

2023-04-04 11:34 UTC, ihor-sviziev requested changes
Please review and fix failing tests

2023-04-24 06:45 UTC, engcom-Delta commented
@magento run all tests

2023-04-24 08:51 UTC, engcom-Delta commented
@magento create issue

2023-04-24 09:41 UTC, engcom-Delta commented
@magento run  all tests

2023-04-24 12:24 UTC, ihor-sviziev commented on app/code/Magento/Catalog/Model/Category.php
> +     * @see 227208e9
what is it? Do you feed everyone will understand it?

2023-04-25 02:55 UTC, engcom-Delta commented
@magento run all tests

2023-04-25 07:23 UTC, engcom-Delta commented
@magento run Integration Tests

2023-07-03 11:43 UTC, engcom-Hotel requested changes
Hello @igorwulff,

Thanks for the contribution and collaboration!

The code changes seem fine for us, but could you please check the failed tests.

Thanks

2023-07-10 10:20 UTC, engcom-Charlie commented
@magento run all tests

2023-07-10 15:25 UTC, engcom-Charlie commented
@magento run Functional Tests EE, Functional Tests B2B, Integration Tests, Unit Tests

2023-07-12 10:01 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Integration Tests, Unit Tests

2023-07-19 07:36 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Integration Tests, Unit Tests

2023-07-19 13:31 UTC, engcom-Charlie commented
Hi @igorwulff,

Thank you for your contribution!

Can you please have a look into the failing tests.

Thank you!

2023-07-20 03:07 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2023-07-24 12:49 UTC, engcom-Charlie commented
@magento run Unit Tests

2023-07-25 05:39 UTC, engcom-Charlie commented
@magento run Integration Tests

2023-07-25 07:55 UTC, engcom-Charlie commented
@magento run Unit Tests, Integration Tests

2023-07-27 13:24 UTC, engcom-Charlie commented
@magento run Unit Tests, Integration Tests

2023-07-28 06:12 UTC, engcom-Charlie commented
Hi @igorwulff,

I have fixed few unit test and integration test failures. 

There are still few remaining from unit as well as integration tests. Can you please have a look into them in order to move this PR further.

Thank you!

2023-07-28 06:23 UTC, engcom-Charlie commented
@magento run all tests

2023-08-07 14:27 UTC, engcom-Charlie commented
Hi @igorwulff,

Can you please have a look into [this](https://github.com/magento/magento2/pull/37185#issuecomment-1655088889) comment.

Thank you!

2023-08-21 14:18 UTC, engcom-Charlie commented
Hi @igorwulff,

Thank you for your contribution!

As mentioned in [this](https://github.com/magento/magento2/pull/37185#issuecomment-1655088889) comment, there are some static test failures which need to be fixed. 

To move this PR ahead, can you please have a look at them as mentioned in [comment](https://github.com/magento/magento2/pull/37185#issuecomment-1667965104). Till then we are closing this PR. Please feel free to reopen for any updates or improvements or let us know we will be happy to reopen it.

Thank you!

2023-08-21 14:18 UTC, closed without merging