Fix shipping total amount calculation for multishipping addresses
magento/magento2 pull request #37272
Opened 2023-03-20 13:27 UTC by ilnytskyi

### Description (*)

When Quote contains more than one shipping address, the total collector updates shipping amount for address given in `$quote->getShippingAddress()` instead of passed via `$shippingAssignment`

### Related Pull Requests

### Fixed Issues (if relevant)

### Manual testing scenarios (*)

1. Create a quote
2. Add additional shipping address with items
3. Leave address given via `$quote->getShippingAddress()` with virtual items only
4. Collect quote totals
5. The address given via `$quote->getShippingAddress()` has fields `shipping_amount` and `base_shipping_amount` equal 0.

### Questions or comments

Currently that address would contain **shipping_amount** and **base_shipping_amount** greater than zero but `shipping_incl_tax` equals zero that is wrong for multishipping quotes
![Selection_066](https://user-images.githubusercontent.com/3192770/226353890-c263433e-e4ad-4c2e-b63c-ec02d6cadb88.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-03-20 13:28 UTC, ilnytskyi commented
@magento run all tests

2023-03-20 18:13 UTC, ilnytskyi commented
@magento run all tests

2023-03-21 07:55 UTC, ilnytskyi commented
Failling tests seem not related to changes

2023-03-23 13:22 UTC, engcom-Bravo commented
@magento create issue

2023-05-12 09:02 UTC, engcom-Hotel commented
Hello @ilnytskyi,

Thanks for the contribution!

Please have a look at the comment here https://github.com/magento/magento2/issues/37283#issuecomment-1545416572 and let us know if we have missed anything in order to reproduce the issue.

Thanks

2023-05-31 06:12 UTC, engcom-Charlie commented
Hi @engcom-Hotel,

As per this [comment](https://github.com/magento/magento2/issues/37283#issuecomment-1552441002), moving this PR in Review now as the issue is confirmed.

Thank you!

2023-07-19 07:04 UTC, engcom-Hotel commented
@magento run all tests

2023-07-19 17:43 UTC, engcom-Hotel requested changes
Hello @ilnytskyi,

Thanks for the contribution!

It seems some builds are failing due to PR changes. We request you to please look into those and please cover the PR changes with some automated tests.

Thanks

2023-07-20 05:19 UTC, ilnytskyi commented
@magento run all tests

2023-07-20 05:22 UTC, ilnytskyi commented
@engcom-Hotel it looks like the build failing due to merge of the main branch. I do not see any failing tests related to checkout or multishipping

2023-08-07 13:47 UTC, ilnytskyi commented
@magento run all tests

2023-11-06 17:59 UTC, ilnytskyi commented
@magento run all tests

2024-01-23 09:40 UTC, ilnytskyi commented
up

2024-09-12 08:49 UTC, engcom-Dash commented
@magento run all tests

2024-09-16 11:23 UTC, engcom-Dash commented
Hello @ilnytskyi,

No file changes are visible in this PR, so it will be closed for now. Please reopen if there are any updates or if something was missed.

Thanks.

2024-09-16 11:23 UTC, closed without merging

2024-09-16 12:03 UTC, ilnytskyi commented
@engcom-Dash dont know how, but my changes already in 2.4-develop branch - https://github.com/magento/magento2/blame/2.4-develop/app/code/Magento/Tax/Model/Sales/Total/Quote/Shipping.php#L41 so probalby merged within other PR