magento/magento2#35934: Internal Server Error in special-price API Endpoint
magento/magento2 pull request #37294
Opened 2023-03-24 14:23 UTC by serbynskyi

### Description (*)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35934

### Manual testing scenarios (*)
1. Retrieve auth token from the admin endpoint /V1/integration/admin/
2. Send post request to below endpoints with the payload:
Payload:
{"prices": "[]"}

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-03-24 14:31 UTC, serbynskyi commented
@magento run all tests

2023-03-25 13:13 UTC, serbynskyi commented
@magento run all tests

2023-03-28 21:43 UTC, hostep commented on lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php
> +                        )
Injecting a dynamic value in a translatable string will make it very hard to translate it.
I would suggest doing something like this instead:

`new Phrase('The value "%fieldName" must be an array.', ['fieldName' => $data]);`

2023-03-28 22:01 UTC, serbynskyi commented
@magento run all tests

2023-03-28 22:02 UTC, serbynskyi commented on lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php
> +                        )
Yes, I agree. The pull request is updated.

2023-03-30 13:18 UTC, serbynskyi commented
@magento run all tests

2023-05-15 11:37 UTC, engcom-Hotel commented
@magento run all tests

2023-05-17 13:43 UTC, engcom-Hotel requested changes
Hello @serbynskyi,

Thanks for the contribution!

Please fix the Integration and web API test failures.

Thanks

2023-05-17 13:43 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php
> +                } else {
Please add some automated tests with a negative scenario where we are not passing the array.

2023-05-22 08:05 UTC, engcom-Echo commented
@magento run all tests

2023-05-23 13:04 UTC, engcom-Echo commented
@serbynskyi 
Thank you for your contribution!
While going through the PR, I have found that original scope of the issue was to fix for special-prices but seems the fix is causing regression issue. 
Can you please have a look at the [integration](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37294/3212539b087f18a6eb01db7713fb28d6/Integration/console-error-logs.html) and [Web API](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37294/1567502496cdf95eecf0573bbbe24481/WebApi/console-error-logs.html) test failures those seems to be due the PR changes.

In Order to move PR further build should be green.

2023-05-24 11:09 UTC, engcom-Echo commented
@serbynskyi we are moving this PR `On Hold` based on [comment](https://github.com/magento/magento2/pull/37294#issuecomment-1559293865). Let us know when you are ready to work on it again, and we will be happy to move it back further. Thank you for your contribution.

2023-05-30 06:22 UTC, engcom-Echo commented
Since it needs changes as per above [comment](https://github.com/magento/magento2/pull/37294#issuecomment-1559293865) maving it to Draft state.

2023-05-30 06:23 UTC, engcom-Echo commented
@serbynskyi Since it needs changes as per above [comment](https://github.com/magento/magento2/pull/37294#issuecomment-1559293865) maving it to Draft state.

2023-06-14 06:21 UTC, engcom-Echo commented
As mentioned in above [comment](https://github.com/magento/magento2/pull/37294#issuecomment-1559293865) since there are regression issues caused by PR changes as we as there are some build failures closing this PR for now.

Please feel free to reopen for any update.

Thank you

2023-06-14 06:21 UTC, closed without merging