feat(catalog): faster category product count
magento/magento2 pull request #37350
Opened 2023-04-08 19:11 UTC by damienwebdev

Previously, in the admin panel, computing the CategoryTree UI (the left-hand element of the page that loads when you try to view the categories of your store) was wildly slow for the root scope when there were many `is_anchor` categories. This was due to several bugs:

1: Use of a missing index: `catalog_category_product_index` that is now defunct and always empty. It was replaced by `catalog_category_product_index_store*`. However, this table did not exist for the `store0`. This diff both adds that missing table and changes the collection to use the new tables.

2. A bad computation of the `rootCategoryIds` for the root store, causing a bad join condition against the temporary category recursion table resulting in the resulting index table (catalog_category_product_index_store0) always being empty.

3. An exceedingly slow private method (getProductsCountFromCategoryTable) which should not have been merged in the first place given how slow it is. I have removed this method. Removing this does cause a small UX bug when the index is empty: the category page will show 0 products before an index has run. It's either this or perform the computation on every page refresh. I see this an acceptable break, given how slow it is to attempt to compute these values manually.

### Related Pull Requests
Fixes: https://github.com/magento/magento2/pull/35216
Fixes: https://github.com/magento/magento2/pull/35417

### Fixed Issues (if relevant)
Fixes: https://github.com/magento/magento2/issues/34109
Fixes: https://github.com/magento/magento2/issues/34111

### Manual testing scenarios (*)
1. Attempt to view admin panel on root scope with many anchor categories (each with many products) ~4000 categories and ~4000 products. 
2. Wait until the end of time.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-04-09 05:50 UTC, ihor-sviziev commented
Hi @damienwebdev,
Do you have some benchmarks before and after your changes?

2023-04-09 10:54 UTC, damienwebdev commented
@ihor-sviziev this will be a function of the size of your database. 

It's the difference between Θ(1) database queries and Θ(n) database queries. In my local env with a fairly large database this took 120s. Afterwards, it took ~2s.

Is there a representative dataset with a large number of products/categories that I can use to generate a before/after profile?

Or, is there a way to generate such a set such that others can replicate the behavior?

2023-04-10 00:37 UTC, damienwebdev commented
Just to also take this a strp further, 

I was thinking about following: https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/generate-data.html?lang=en

However, 

https://github.com/magento/magento2/blob/2.4-develop/setup/src/Magento/Setup/Fixtures/CategoriesFixture.php#L140

Pretty much guarantees a small number of anchor categories which means that even the "extra large" profile will not discover this.
                    

2023-04-10 12:53 UTC, damienwebdev commented on app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php
> +        $categoryTable = $this->tableMaintainer->getMainTable($this->getProductStoreId());
Given that these tables are dynamic, in the event the index table for the store does not exist, we should just return an associative array of `$categoryId => 0`

2023-04-10 14:30 UTC, ihor-sviziev commented
@magento run all tests

2023-04-11 07:13 UTC, ihor-sviziev requested changes
Hi @damienwebdev,
I see there is a huge list of test failures. Could you please take a look?

2023-04-11 11:44 UTC, damienwebdev commented
https://github.com/magento run all tests

2023-04-11 11:44 UTC, damienwebdev commented
@magento run all tests

2023-04-11 11:45 UTC, damienwebdev commented on app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php
> +        $categoryTable = $this->tableMaintainer->getMainTable($this->getProductStoreId());
I've handled this.

2023-04-11 12:29 UTC, ihor-sviziev commented
@magento run Static Tests

2023-04-11 12:31 UTC, damienwebdev commented
@ihor-sviziev ty for the static fixes, I had no idea what to do.

2023-04-11 12:34 UTC, damienwebdev commented
@ihor-sviziev it looks like some of the database tests are correctly failing (there's a diff between what used to be there and what is there now). How do we "accept" this difference? What team needs to do that approval?

2023-04-12 20:48 UTC, ihor-sviziev commented
@magento run all tests

2023-04-13 08:55 UTC, ihor-sviziev requested changes
@damienwebdev looks like your change broke tests, so probably will break some functionality, please review failures and fix them

2023-04-25 11:26 UTC, engcom-Echo commented
Hi @damienwebdev,
Thanks for you contribution.

It seems that many of the test are failing due the PR changes. In order to move to the PR further all test should get passed.
Can you please have a look on them.

Thank you.

2023-05-11 09:13 UTC, engcom-Charlie commented
Hi @damienwebdev,

Thank you for your contribution!

As per [this](https://github.com/magento/magento2/pull/37350#issuecomment-1521627492) comment, it seems that there are many test failures because of the PR change. Can you please look into them. Till then we are closing this PR.

Please fell free to reopen or let us know when you are ready to work on it again, and we will be happy to re-open it.

Thank you!

2023-05-11 09:13 UTC, closed without merging