Fix overrides.xml
magento/magento2 pull request #37371
Opened 2023-04-13 23:35 UTC by duhon

Без этого фикса невозможно использовать overrides.xml который декларативно изменяет конфигурацию маженто тестов

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. создать любой маженто модуль с web-api тестами и файлом overrides.xml (чтобы заглушить вечно падающие мажентвоские тесты)
2. запустить все апи тесты и убедиться что overrides.xml был проигнорировал тестовым фреймворком

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-11-17 19:00 UTC, duhon commented
@magento run all tests

2023-11-17 19:02 UTC, duhon commented
@engcom-Hotel ping

2023-11-22 21:41 UTC, duhon commented
@magento run all tests

2024-03-06 20:24 UTC, duhon commented
@engcom-Hotel ping

2024-03-07 11:31 UTC, engcom-Hotel commented
@magento run all tests

2024-03-07 11:40 UTC, engcom-Hotel requested changes
Hello @duhon,

Thanks for the contribution!

Please fix the failed automated test.

Thanks

2024-08-22 09:55 UTC, engcom-November commented
@magento create issue

2024-08-28 07:30 UTC, engcom-Hotel commented
@magento run all tests

2024-08-29 06:50 UTC, engcom-Hotel commented
We are internally discussing this PR. Till the time, we are moving this on hold.

2024-09-09 14:03 UTC, duhon commented
The crash is not related to my pull request; my code does not affect the eval functionality. This is a problem with the test itself, which I don’t have access to.

2024-10-09 12:26 UTC, engcom-Hotel commented
@magento run all tests

2024-11-18 10:50 UTC, engcom-Hotel commented
Hello @duhon,

We have noticed that this PR has not been updated for a period of long time. Hence we are closing this PR for now.

Let us know when you are ready to work on it again, and we will be happy to re-open it. Thank you for your contribution!

Thanks

2025-02-13 23:04 UTC, duhon commented
The PR was ready to merge, what a reason for the closure, I waited for you to merge

2025-02-17 04:41 UTC, engcom-Hotel commented
@magento run all tests

2025-02-17 06:53 UTC, engcom-Hotel commented
Hello @duhon,

Thanks for reaching us!

As we talked about [here](https://github.com/magento/magento2/pull/37371#pullrequestreview-1922215074) and slack as well, we need a green build to continue with the PR. As the PR is failing `Preliminary Checks`, we are unable to proceed with this.

We request you to please resolve the failed test.

Thanks

2025-02-21 04:27 UTC, duhon commented
Give me access to your test Preliminary Checks and I will fix it

2025-02-21 04:31 UTC, duhon commented
> Hello @duhon,
> 
> Thanks for reaching us!
> 
> As we talked about [here](https://github.com/magento/magento2/pull/37371#pullrequestreview-1922215074) and slack as well, we need a green build to continue with the PR. As the PR is failing `Preliminary Checks`, we are unable to proceed with this.
> 
> We request you to please resolve the failed test.
> 
> Thanks

The answer [here](https://github.com/magento/magento2/pull/37371#issuecomment-2338216765).
Give me access to your test `Preliminary Checks` and I will fix it.

2025-03-06 13:25 UTC, engcom-Hotel commented
@magento run all tests

2025-03-20 07:40 UTC, engcom-Hotel commented
Hello @duhon,

We are currently discussing the PR failures internally. We will update you soon on this, meanwhile moving this PR on hold.

Thanks for the patience.

2025-03-25 12:56 UTC, engcom-Hotel commented
@magento run all tests

2025-03-25 13:20 UTC, duhon commented
@magento run all tests

2025-03-25 13:27 UTC, duhon commented
@magento run all tests

2025-03-26 07:31 UTC, engcom-Hotel requested changes
Hello @duhon,

Thanks for the contribution!

The changes looks good to us, but please fix the failed static tests after that we are good to go I think.

Thanks

2025-04-10 08:53 UTC, engcom-Charlie commented
@magento run all tests

2025-04-10 09:38 UTC, engcom-Charlie commented
@magento run all tests

2025-04-10 09:48 UTC, engcom-Charlie commented
@magento run all tests

2025-04-10 13:59 UTC, engcom-Charlie commented
@magento run Functional Tests EE, Integration Tests, WebAPI Tests

2025-04-11 06:51 UTC, engcom-Charlie commented
@magento run all tests

2025-04-11 09:19 UTC, engcom-Charlie commented
@magento run all tests

2025-04-11 12:29 UTC, engcom-Charlie commented
@engcom-Hotel, I have fixed the static test failures hence moving it to Pending Review.

2025-04-14 05:23 UTC, engcom-Hotel commented
@magento run all tests

2025-04-14 10:35 UTC, engcom-Hotel commented
@magento run Functional Tests B2B,Functional Tests CE, Functional Tests EE

2025-04-14 10:35 UTC, engcom-Hotel approved these changes

2025-04-23 08:10 UTC, engcom-Dash commented
We are not able to reproduce the issue on 2.4-develop branch. Please find comment: https://github.com/magento/magento2/issues/39090#issuecomment-2823424339. Hence Moving this PR on hold for now.

2025-05-20 04:16 UTC, engcom-Dash commented
Hi @duhon,

As per our conversation on Slack and https://github.com/magento/magento2/pull/37371#issuecomment-2823432317 , the issue is not reproducible on the 2.4-develop branch. Therefore, we are closing this PR for now.

Please feel free to reopen it if you have additional information or if the issue persists.

Thanks for your contribution!

2025-05-20 04:16 UTC, closed without merging