Unpack object arguments as named parameters
magento/magento2 pull request #37411
Opened 2023-04-21 17:24 UTC by ilnytskyi

### Description (*)

Just a code clean up that uses PHP 8.1 feature of unpacking array with named params.
So `array_values` call is not needed anymore. Probably improve overrall performance by 0.01 :D as many objects will instantiate faster

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

Named argumaents are actualy a bit faster based on simple check for instantiatin 100 000 objects like this
https://pastebin.com/DGdBwwzN
![Selection_177](https://user-images.githubusercontent.com/3192770/233696916-d869609a-6375-49be-8b48-0fc1295b9fb5.png)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-04-21 17:24 UTC, ilnytskyi commented
@magento run all tests

2023-04-22 08:00 UTC, ilnytskyi commented
OMG wow why would unit test check config with not existing parameters for requested type and allow test to pass?
`\Magento\Framework\ObjectManager\Test\Unit\Factory\Fixture\Compiled\SimpleClassTesting::__construct`

Shouldn't OM work this way that it reads config from `di.xml` and/or resolves based on reflection then just passes the unpack arguments to `new $instance(...$args)`.
I you defined extra arguments in `di.xml`  looks like they are ignored now, but this test failure would confirm that di compilation must fail for this case due to invalid `di.xml`. This way `di.xml`  becomes stricter.

```
There were 2 errors:

1) Magento\Framework\ObjectManager\Test\Unit\Factory\CompiledTest::testCreateSimple
Error: Unknown named parameter $value_array

2) Magento\Framework\ObjectManager\Test\Unit\Factory\CompiledTest::testCreateSimpleConfiguredArguments
Error: Unknown named parameter $value_array
```

2023-04-24 08:33 UTC, ihor-sviziev requested changes
Please fix failing tests

2023-04-24 09:32 UTC, ihor-sviziev commented
@ilnytskyi I think it was working like that in the pre-php8 era, so it kept like that due to compatibility reasons (earlier it was working by argument position, not by argument name, and you might have the wrong argument name).
So I think that was a hack, that we should remove to get performance benefit.

2023-04-24 16:11 UTC, ilnytskyi commented
@magento run all tests

2023-04-25 08:07 UTC, ihor-sviziev requested changes

2023-04-25 08:07 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/ObjectManager/Test/Unit/Factory/CompiledTest.php
> +        $this->config->expects($this->any())
```suggestion
        $this->config
```

2023-04-25 08:07 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/ObjectManager/Test/Unit/Factory/CompiledTest.php
> +        $this->config->expects($this->any())
```suggestion
        $this->config
```

2023-04-25 08:07 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/ObjectManager/Test/Unit/Factory/CompiledTest.php
> +    public function testCreateInvalidSimple()
```suggestion
    public function testCreateInvalidSimple(): void
```

2023-04-25 08:07 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/ObjectManager/Test/Unit/Factory/CompiledTest.php
> +    private function getInvalidSimpleConfig()
```suggestion
    private function getInvalidSimpleConfig(): array
```

2023-04-25 08:12 UTC, ihor-sviziev commented
@magento run all tests

2023-05-08 07:17 UTC, ihor-sviziev commented
@magento run Functional Tests EE, Integration Tests, WebAPI Tests

2023-05-08 15:40 UTC, ihor-sviziev approved these changes

2024-09-24 09:12 UTC, engcom-Dash commented
@magento run all tests

2024-09-24 12:24 UTC, engcom-Dash commented
Hi @ilnytskyi 

Thanks for the contribution!

✔️ QA Passed
Preconditions:

Install fresh Magento 2.4-develop

Steps to reproduce
- Follow the description.
- Run the following commands:
  bin/magento setup
  bin/magento s:d:c
  bin/magento c:f
(All commands should run successfully.)

Before: ✖️
N/A

After✔️:
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/13147489-42bc-4c18-b1d9-3c2a1a083760">

 Execution of Array Values and Named Values.
<img width="899" alt="image" src="https://github.com/user-attachments/assets/b3b58e70-500f-4645-900a-744721a35636">

Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

2024-09-24 12:25 UTC, engcom-Dash commented
@magento run Unit Tests, Functional Tests EE, Functional Tests B2B

2024-09-24 13:15 UTC, engcom-Dash commented
@magento run all tests

2024-09-25 04:27 UTC, engcom-Dash commented
@magento run Functional Tests B2B

2024-09-25 07:15 UTC, engcom-Dash commented
Functional test B2B failures are different in the last two runs. Additionally, the build failure contains one known issue.

Run 1:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37411/e9afb79fa478da24ca41fbaa67d7ff8a/Functional/allure-report-b2b/index.html#categories/39002bb4b823f2d59e22404a186a7115/893c875ee0add438/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/bcbbfc83-b30b-4d05-9f2b-0ff9c1ef5abc">

Run 2:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37411/796611e6a5f111b2d24956a7a4aa81f7/Functional/allure-report-b2b/index.html#categories/8204e1939c11cfc5dade2a6cfc331ffe/ca132cb54a1bbf19/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/a677cf43-755f-42bd-b92d-93810d222b79">

So moving it to merge in progress.

2024-10-03 11:12 UTC, engcom-Dash commented
@magento create issue

2025-12-15 13:18 UTC, engcom-Charlie commented
As there are conflicts in the PR, moving it back to Extended Testing.

2025-12-16 08:20 UTC, engcom-Dash commented
@magento run all tests

2025-12-17 07:32 UTC, engcom-Dash commented
@magento run all tests

2025-12-17 10:15 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE, Unit Tests

2025-12-17 13:10 UTC, engcom-Dash commented
Resolved the PR conflicts and moved it back to Merge in Progress.

2025-12-23 16:16 UTC, merged

2026-01-05 07:30 UTC, igorwulff commented on lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Production.php
> +            if (!empty($arguments) && (array_key_exists($paramName, $arguments))) {
The removal of isset makes this if statement slower. Isset as a language construct is faster then array_key_exists and if isset is true, PHP won't check array_key_exists. Not sure how much it actually matters performance wise.

2026-01-05 07:30 UTC, igorwulff commented on lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php
> +        if (!empty($arguments) && (array_key_exists($paramName, $arguments))) {
The removal of isset makes this if statement slower. Isset as a language construct is faster then array_key_exists and if isset is true, PHP won't check array_key_exists. Not sure how much it actually matters performance wise.