Fixed issue Add to Wishlist with product custom option file upload not working Magento 2.4.6 #37437
magento/magento2 pull request #37448
Opened 2023-05-01 08:21 UTC by rostilos

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37437
### Manual testing scenarios (*)

1. Create a simple product
2. Add a custom option file and text
3. Options should be required.
![234768126-aedf846c-916e-4ef7-912b-19825ddb1d54](https://user-images.githubusercontent.com/85498741/235427755-fee75a79-9531-4688-84e2-e5f49e515427.png)
4. Now go to the front end, log in customer, and open the product page.
5. Upload file and add text value
6. Now click on add to wishlist

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-05-01 08:22 UTC, rostilos commented
@magento run all tests

2023-05-01 13:10 UTC, rostilos commented
@magento run Functional Tests B2B

2023-05-05 14:15 UTC, rostilos commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2023-05-10 06:28 UTC, rostilos commented
@magento run Functional Tests B2B, Integration Tests

2023-05-19 11:36 UTC, engcom-Hotel commented
@magento give me test instance

2023-05-19 11:53 UTC, engcom-Hotel commented
@magento run all tests

2023-05-19 12:01 UTC, engcom-Hotel commented
@magento give me 2.4-develop instance

2023-05-19 13:44 UTC, engcom-Hotel requested changes
Hello @rostilos,

Thanks for the contribution!

The changes seem good to me. But I believe we can cover the changes with some automated tests for e.g. MFTF. 

Thanks

2023-05-22 23:30 UTC, rostilos commented
@magento run all tests

2023-05-22 23:35 UTC, rostilos commented
@engcom-Hotel Added test coverage for this fix.
Test case when item has 3 customizable options. This was done for the reason of not creating a new entity in the test, but to use an existing one ( The bug is reproduced even when there are 3 customizable options, since the cause is the same, you can double-check this )

2023-05-23 06:19 UTC, rostilos commented
@magento run Database Compare, Functional Tests CE

2023-05-23 07:48 UTC, rostilos commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests

2023-05-23 11:35 UTC, engcom-Echo commented
@magento run Functional Tests EE,Functional Tests B2B

2023-05-23 13:31 UTC, rostilos commented
I could be wrong, but it seems to me that the failed tests do not refer to edits from the PR.

2023-05-23 14:45 UTC, engcom-Echo commented
Failing test are not related to PR

2023-05-23 15:39 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE

2023-05-24 05:28 UTC, engcom-Hotel commented
@magento run Functional Tests EE

2023-05-24 07:05 UTC, engcom-Hotel approved these changes
Hello @rostilos,

Build failures seems flaky to me. Hence approving the PR.

Thanks

2023-05-24 11:55 UTC, engcom-Lima commented
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Create a simple product
- Add a custom option file and text
- Options should be required.
- Now go to the front end, log in customer, and open the product page.
- Upload file and add text value
- Now click on add to wishlist

**Before:** :heavy_multiplication_x: Two products got added in the wishlist.

<img width="1444" alt="Screenshot 2023-05-24 at 4 52 00 PM" src="https://github.com/magento/magento2/assets/60198022/ab1405fd-fdb5-4a2f-9894-c2a1770b6c59">


**After:** :heavy_check_mark:  Now only one product is added in the wishlist.

<img width="1417" alt="Screenshot 2023-05-24 at 4 53 31 PM" src="https://github.com/magento/magento2/assets/60198022/b34b5f08-49b8-4e35-8ba6-cb240774dfb4">

Build is failed. Hence, moving this PR to **Extended Testing**

2023-05-24 12:22 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2023-05-24 14:45 UTC, engcom-Echo commented
Functional Tests B2B build failure are different on last two run on same commit.
Run1 
<img width="1336" alt="image" src="https://github.com/magento/magento2/assets/51681435/906435fb-7bfa-43e0-a48a-228defcd8881">

Run2
<img width="1440" alt="image" src="https://github.com/magento/magento2/assets/51681435/587f9e48-fb92-4427-ae7d-0a1f5576c1f6">

Hence moving it to `Merge In Progress`

2023-07-11 14:37 UTC, engcom-Echo commented
@magento run all tests

2023-07-12 02:03 UTC, engcom-Echo commented
@magento run all tests

2023-07-13 05:06 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2023-07-17 06:17 UTC, rostilos commented
@engcom-Echo I've noticed a certain oddity. I see that the edits have been merged into the dev branch ( https://github.com/magento/magento2/commit/eaf24b2526798a085e5fec46da97fdfb9f58ec3f?diff=split ) , but the edit history of this PR is empty

2023-07-31 07:17 UTC, engcom-Charlie commented
> @engcom-Echo I've noticed a certain oddity. I see that the edits have been merged into the dev branch ( [eaf24b2?diff=split](https://github.com/magento/magento2/commit/eaf24b2526798a085e5fec46da97fdfb9f58ec3f?diff=split) ) , but the edit history of this PR is empty

Hi @rostilos,

This PR is already merged in [d4a9791](https://github.com/magento/magento2/commit/d4a9791d0f589ee1006beba25c240a39a59d50e9). As after adding this this PR into mainline PR, we have added few commits of merging 2.4-dev into this, that is the reason it is still showing as in Open status. 

Thank you!

2025-02-17 11:20 UTC, merged