Auto select https if port is 443 and not protocol is detected
magento/magento2 pull request #37499
Opened 2023-05-14 14:03 UTC by DEADSEC-SECURITY

Summary:
Fixes solution 1 of Issue 37490 by defaulting to protocol https if no protocol is given in the hostname and the port given is 443

Issues:
https://github.com/magento/magento2/issues/37490

Testing:
Tested on 2.4-develop on AWS EC2 instance with AWS Opensearch domain running version 1.3

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Partially fixes magento/magento2#37490

### Manual testing scenarios (*)

1. Create a fresh instance, in opensearch params use port 443 and don't provide a protocol in hostname, the resulting hostname should have protocol https instead of the original default to http

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2023-05-14 14:18 UTC, DEADSEC-SECURITY commented
@magento run all tests

2023-05-23 12:43 UTC, engcom-Hotel commented
Hello @DEADSEC-SECURITY,

Thanks for the contribution!

But in order to proceed further please sign the Adobe CLA. Please check the build failures for more details.

Thanks

2023-05-23 12:48 UTC, DEADSEC-SECURITY commented
> Hello @DEADSEC-SECURITY,
> 
> Thanks for the contribution!
> 
> But in order to proceed further please sign the Adobe CLA. Please check the build failures for more details.
> 
> Thanks

I already signed the CLA.

2023-05-24 05:32 UTC, engcom-Hotel commented
@magento run all tests

2023-06-03 16:03 UTC, hostep commented
> I already signed the CLA.

There is a long standing bug with Adobe's CLA check here on github. To fix it, you need to close the PR, and a couple of seconds later re-open it again. From then on, it should work. This is only needed for your first PR to this repo here. Kind of annoying, but it's an easy fix 🙂

2023-06-04 14:54 UTC, DEADSEC-SECURITY commented
that worked @hostep

2023-06-06 12:05 UTC, engcom-Hotel requested changes
Hello @DEADSEC-SECURITY,

Please have a look on my suggestions below and also please cover the changes with some automated tests.

Thanks

2023-06-06 12:05 UTC, engcom-Hotel commented on app/code/Magento/OpenSearch/Model/SearchClient.php
> +            if (!empty($options['port']) && $options['port'] == '443') {
Suggest you to implement strict check here like below:

`$options['port'] === '443'`

2023-06-08 11:13 UTC, DEADSEC-SECURITY commented
> Hello @DEADSEC-SECURITY,
> 
> Please have a look on my suggestions below and also please cover the changes with some automated tests.
> 
> Thanks

Hi @engcom-Hotel I'm new to the Magento codebase and PHP is not the main language so if you could point me out to docs on how to creates tests I would appreciate.

2023-09-18 20:37 UTC, closed without merging