#27504 fix joinprocessor behavior with consecutive calls
magento/magento2 pull request #37550
Opened 2023-05-27 09:38 UTC by fgerodez

### Description (*)

When a JoinProcessor is called multiple times during a request the join definitions are only applied the first time. Subsequent calls will leave the collections unmodified.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27504

### Contribution checklist (*)
 - [* ] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [*] All new or changed code is covered with unit/integration tests (if applicable)
 - [*] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [*] All automated tests passed successfully (all builds are green)

2023-05-27 09:42 UTC, fgerodez commented
@magento run all tests

2023-06-06 14:22 UTC, engcom-Hotel commented
@magento run all tests

2024-01-22 12:53 UTC, andrewbess commented
@magento run all tests

2024-01-22 15:37 UTC, andrewbess requested changes
Hello @fgerodez
Thank you for your contribution
Could you please check my suggestion and fix copyright?
Thank you in advance.

2024-01-22 15:37 UTC, andrewbess commented on dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php
> +<?php
```suggestion
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
```

2024-03-22 15:10 UTC, andrewbess commented
@magento run all tests

2024-03-22 17:00 UTC, andrewbess commented
@magento run WebAPI Tests, Functional Tests CE, Functional Tests EE

2024-09-12 09:47 UTC, engcom-Dash commented
@magento run all tests

2024-09-13 09:37 UTC, engcom-Dash commented
@magento run all tests

2024-09-16 13:09 UTC, engcom-Dash commented
Hello @fgerodez,

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:

Install fresh Magento 2.4-develop
Steps to reproduce
According to the issue description.
Before: ✖️ 
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/6a44772f-bd9c-4914-994f-c086137dd316">

After: ✔️

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/7651066c-2c93-4a53-aa45-1d1530840e17">

Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

2024-09-16 13:09 UTC, engcom-Dash commented
@magnto run all tests

2024-09-17 06:22 UTC, engcom-Dash commented
@magento run all tests

2024-09-17 11:43 UTC, engcom-Dash commented
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2024-09-17 17:35 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE

2024-09-18 06:09 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE

2024-09-18 08:16 UTC, engcom-Dash commented
Failing tests seem flaky and these are known issues. Therefore, I am moving the PR to Merge in Progress.

**Build Result**
Functional Tests B2B
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/0fbdcdfa9a31d12cd376388d3b612236/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/0fbdcdfa9a31d12cd376388d3b612236/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/cd4f35f8bf8051b7b4becdc429888efd/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/cd8bdfe4b424a3437cc015897f021949/Functional/allure-report-b2b/index.html

Known issue :
StorefrontCheckoutProcessForQuoteWithoutNegotiatedPricesTestCest: [#AC-6801](https://jira.corp.adobe.com/browse/ACQE-6801)
StorefrontPrintListItemsFromRequisitionListTest: [#AC-12166](https://jira.corp.adobe.com/browse/AC-12166)

2025-01-03 06:10 UTC, engcom-Charlie commented
Hi @fgerodez and @andrewbess,

Thank you for the contribution!

As the review is pending, moving it back to Pending review.

Thank you!

2025-01-06 05:31 UTC, engcom-Hotel commented
@magento run all tests

2025-01-06 07:58 UTC, engcom-Hotel requested changes
Hello @fgerodez,
Thanks for the contribution!

Please fix the failed automated tests, specifically static test, and look into the review comments below.

Thanks

2025-01-06 07:58 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php
> +     * @var \Magento\Framework\ObjectManagerInterface
This qualifier can be replaced with an import. Import the ObjectManagerInterface and use it as below:
```suggestion
     * @var ObjectManagerInterface
```

2025-01-06 07:58 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php
> +        $this->objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();
Same here
```suggestion
        $this->objectManager = Bootstrap::getObjectManager();
```

2025-01-06 07:58 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php
> +            ->getMockForAbstractClass();
The `getMockForAbstractClass` method has been deprecated, please use alternate method.

2025-01-06 07:58 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php
> +            ->getMockForAbstractClass();
The `getMockForAbstractClass` method has been deprecated, please use alternate method.

2025-01-06 14:48 UTC, engcom-Dash commented
@magento run all tests

2025-01-07 06:55 UTC, engcom-Dash commented
> Hello @fgerodez, Thanks for the contribution!
> 
> Please fix the failed automated tests, specifically static test, and look into the review comments below.
> 
> Thanks

@engcom-Hotel: I have implemented the suggested changes and fixed the integration failures. Moving it back to Pending Review.

NOTE: The failed integration tests are not related to the PR changes and can also be seen in other PRs.

2025-01-07 09:55 UTC, engcom-Hotel approved these changes

2025-01-07 12:29 UTC, engcom-Dash commented
@magento run Integration Tests, Functional Tests EE

2025-01-08 06:47 UTC, engcom-Dash commented
@magento run all tests

2025-01-09 07:00 UTC, engcom-Dash commented
@magento run all tests

2025-01-09 10:14 UTC, engcom-Dash commented
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2025-01-09 13:39 UTC, engcom-Dash commented
The Functional B2B, CE and Integration test failures are inconsistent or known issues in the last two builds and seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

**Integration Tests**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/b8d3b143ee2d4461466eaecbc06cc161/Integration/console-error-logs.html
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/3f898035-54a9-4a04-b7d1-3bc6ec0fecca" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/e55d6635f7dbd475f5ca236ceeb1a535/Integration/console-error-logs.html
<img width="1771" alt="image" src="https://github.com/user-attachments/assets/cf72d58b-5c02-42f3-a177-a8d60b82718b" />

Known Issue:
[AC-13584](https://jira.corp.adobe.com/browse/AC-13584)

**Functional Tests B2B**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/96b61a594a1ae1c7207fe8403c36d94a/Functional/allure-report-b2b/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/36fcf222bef58cb7/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/7aecb378-0536-4d95-b3ea-5f039addf505" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/d07cd9fc1b64f9dd7ff8631e39bb5c04/Functional/allure-report-b2b/index.html#categories/bfde7a9fcff9e79ffbe443fe2e9ee992/fa198996fe557e5/
<img width="1781" alt="image" src="https://github.com/user-attachments/assets/97d268ee-f8a9-45b6-999c-4d0eb1c7b257" />

Known Issue:
EndToEndB2CLoggedInUserTest: [ACQE-7387](https://jira.corp.adobe.com/browse/ACQE-7387)

**Functional Tests CE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/3cae302f7a40c3a2881c4787e7dd82c5/Functional/allure-report-ce/index.html#categories/75b40a63f79830217aae704c6d6af940/110526e17ad16bfb/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/0e8fa75f-4b97-4aec-9476-457dabe5773d" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/feee1c963f5bf6397afbd7fba47476db/Functional/allure-report-ce/index.html#categories/e93c564a2dcd5e30ee0e0e811a828c2b/811cd8516b0a14be/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/1d46d8a4-d8f2-45f9-b33a-5f660fd7cccb" />

Known Issue:
StoreFrontAddOutOfStockProductToShoppingCartTest: [ACQE-6818](https://jira.corp.adobe.com/browse/ACQE-6818)

2025-02-17 11:20 UTC, merged