Fixed issue .ui-state-focus missing from main navigation in 2.4.5 and 2.4.6
magento/magento2 pull request #37571
Opened 2023-06-02 16:06 UTC by rostilos

### Description (*)

The bug was reproduced because the updated version of jquery-ui menu widget now adds the "ui-state-active" class instead of "ui-state-focus" to the element with focus. When the jquery-ui library was updated (somewhere between version 2.4.3 and 2.4.5) these edits were added but the styles were not changed. 
In this PR, the selectors for the "ui-state-focus" class have been replaced by "ui-state-active" because the "ui-state-focus" class is no longer added to the menu item with focus in the menu functionality of the jquery-ui library widget

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37300

### Manual testing scenarios (*)

1. Install a vanilla Magento version 2.4.5 - 2.4.6
2. Open developer tools and inspect a submenu item in the main navigation to watch classes
3. Using keyboard tab to the main menu then use arrow keys to navigate to submenu items
4. When focus is on a menu/submenu item a class should be added of "ui-state-focus" ( Also the menu item with focus must be visually marked )
### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-06-02 16:06 UTC, rostilos commented
@magento run all tests

2023-06-02 16:25 UTC, rostilos commented
@magento run all tests

2023-06-27 15:16 UTC, schizek commented
@rostilos I don't think just styling the `ui-state-active` class will work here since `active` and `focus` have different meanings.  In this case, if you put focus on a child menu item, the parent item is still "active", so the styles would apply to both which will be an issue.  Ideally the `ui-state-focus` class would return so that could be styled separately from `ui-state-active`.

2023-07-10 14:41 UTC, rostilos commented
@schizek 
A jquery-ui menu widget is used for the menu functionality. The current version's widget functionality contains a method that adds a ui-state-active class for active menu items, and for items in focus ( jQuery UI Menu 1.13.1 ) :
![2023-07-10_17-38](https://github.com/magento/magento2/assets/85498741/51a63abf-f0b6-44a7-8fb8-ee27f90a52ee)
Is it really necessary to rewrite the root functionality of a third-party widget if it's only about the class name?
In previous versions of the widget, this method actually added the ui-state-focus class to the element in focus ( jQuery UI Menu - v1.10.4) : 
![2023-07-10_17-39](https://github.com/magento/magento2/assets/85498741/3dea164f-ca99-41d3-be9f-3a1486e5af0c)

And yes, both the parent component and the child component are given the same class. This may not be correct, but is it worth rewriting the core functionality with a plugin to do this? If this is an acceptable option, I can do it this way as it was in an older version, just clarifying.

2023-10-25 09:15 UTC, engcom-Hotel commented
@magento run all tests

2023-10-25 14:46 UTC, engcom-Hotel requested changes
Hello @rostilos,

Thanks for the contribution!

Please review my comment below.

Thanks

2023-10-25 14:46 UTC, engcom-Hotel commented on lib/web/css/source/lib/_navigation.less
> +                    .ui-state-active {
We can change the class name in backward backward-compatible way like the below:

.ui-state-active, .ui-state-focus

2023-10-31 09:00 UTC, engcom-Echo commented
@rostilos 

We have verify PR changes and follow steps for verification mentioned [here](https://github.com/magento/magento2/pull/37571#issue-1738458295). But the PR changes does not fix the issue.

Please have a look at below video and let us know if we have missed anything here

https://github.com/magento/magento2/assets/51681435/afee46ff-3730-499c-94cf-901cf029571a

2023-11-02 06:34 UTC, engcom-Echo commented
@rostilos moving it on hold on the basis of above [comment](https://github.com/magento/magento2/pull/37571#issuecomment-1786782904)

2023-11-15 05:45 UTC, engcom-Echo commented
@rostilos did you get a chance to have a look on [comment](https://github.com/magento/magento2/pull/37571#issuecomment-1786782904)

2023-11-15 07:40 UTC, rostilos commented
@engcom-Echo Yes, I have looked at it, and will try to fix it as soon as possible, can't spare the time right now, but will give an update soon. Thanks

2023-12-26 06:05 UTC, engcom-Echo commented
@rostilos did you get a chance to have a look on https://github.com/magento/magento2/pull/37571#issuecomment-1786782904?

2024-01-02 04:54 UTC, engcom-Echo commented
As PR need some work to be done based on https://github.com/magento/magento2/pull/37571#issuecomment-1786782904 Moving this PR in draft state.

2024-01-18 06:08 UTC, engcom-Echo commented
@rostilos We are closing this PR for now as it require some changes based on [comment](https://github.com/magento/magento2/pull/37571#issuecomment-1786782904)
Once you are ready please feel free to reopen.

2024-01-18 06:08 UTC, closed without merging