Lazy load data source data for list UI components
magento/magento2 pull request #37576
Opened 2023-06-04 06:11 UTC by kuafucode

### Description (*)
If a page has listing UI component, the data source collection of the component is loaded and added to the page DOM in the generated component js tag. However this data collection is never rendered and always refreshed via ajax immediately after page load. It is waste of resource and slows down initial page load. 

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37190

### Manual testing scenarios (*)

1. open any admin listing page that is built using uiCompnennt, e.g. customers listing page

### Questions or comments

I think this is a quite exciting performance improvement for many admin pages that has listing component. In my local testing, the TTFB imporved from about 570ms - 420ms

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2023-06-04 14:13 UTC, kuafucode commented
@magento run all tests

2023-06-06 14:33 UTC, engcom-Hotel commented
@magento run all tests

2023-06-09 09:30 UTC, ihor-sviziev requested changes
I suggest removing else condition for better readability.
Please review and fix failing tests

2023-06-09 09:30 UTC, ihor-sviziev commented on app/code/Magento/Ui/Component/Listing.php
> +        }
```suggestion
        // Only load data in an ajax (json) request for better performance
        if ($this->getContext()->getAcceptType() == 'json') {
            return ['data' => $this->getContext()->getDataProvider()->getData()];
        }

        // build out default array keys to revent null erros, in case some module expects this
        return ['data' => ['items' => [], 'totalRecords' => 0]];
```

2023-10-05 11:40 UTC, ihor-sviziev commented
Hi @kuafucode,
Will you be able to fix failing tests?

2023-10-30 12:53 UTC, ihor-sviziev commented
@magento run all tests

2023-10-31 19:15 UTC, ihor-sviziev requested changes
Please review and fix failing tests

2023-11-04 21:26 UTC, kuafucode commented
the test is not running and not showing which test case failed, let me try again

2023-11-04 21:26 UTC, kuafucode commented
@magento run all tests

2023-11-14 18:25 UTC, kuafucode commented
Was able to locate the failed test case, the current PR breaks 'recently viewed' widget. In stead of making the change to `Magento\Ui\Component\Listing\Columns\Listing`, I should move this change into lower component `Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider`.

I'm also thinking of introducing a lazy loading flag to data provide class via ui xml, instead of relying content format in request which is not semantic.

ps. I'm a bit suprised to find out the  'recently viewed' widget config is provided by `Magento\Catalog\Ui\DataProvider\Product\Listing\DataProvider` , IMO it can be fully provided in the ui xml config section

2024-10-17 09:01 UTC, engcom-Dash commented
> Was able to locate the failed test case, the current PR breaks 'recently viewed' widget. In stead of making the change to `Magento\Ui\Component\Listing\Columns\Listing`, I should move this change into lower component `Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider`.
> 
> I'm also thinking of introducing a lazy loading flag to data provide class via ui xml, instead of relying content format in request which is not semantic.
> 
> ps. I'm a bit suprised to find out the 'recently viewed' widget config is provided by `Magento\Catalog\Ui\DataProvider\Product\Listing\DataProvider` , IMO it can be fully provided in the ui xml config section

Hello @kuafucode,

I wanted to follow up on your comment regarding the changes needed for the 'recently viewed' widget and the lazy loading flag. Will you be implementing these updates? If not, please let us know how we should proceed.

Thanks!

2024-11-04 06:59 UTC, engcom-Dash commented
Closing this PR since it has not been updated for a period of 14 days. Please feel free to reopen it if needed.

2024-12-07 14:25 UTC, kuafucode commented
@engcom-Dash please reopen, I'm picking up this work again.

2024-12-09 08:21 UTC, engcom-Dash commented
> @engcom-Dash please reopen, I'm picking up this work again.

@kuafucode- I am reopening this PR. Please review and address the  https://github.com/magento/magento2/pull/37576#issuecomment-1810885747 so we can proceed. Thank you!

2024-12-18 04:53 UTC, engcom-Dash commented
@kuafucode: As discussed over Slack, I'm putting it on hold for now. Once you are done with the implementation, please let us know. We'll pick it up and proceed with the necessary steps. Thanks.

2025-01-06 12:52 UTC, engcom-Dash commented
Hello @kuafucode,

This is a reminder to please address this https://github.com/magento/magento2/pull/37576#issuecomment-2418967790.

Thanks!

2025-01-20 15:17 UTC, engcom-Charlie commented
Hi @kuafucode,

Did you get a chance to look into [this](https://github.com/magento/magento2/pull/37576#issuecomment-2418967790).

Thank you!

2025-02-20 08:00 UTC, engcom-Charlie commented
Hi @kuafucode,

Did you get a chance to look into this [comment](https://github.com/magento/magento2/pull/37576#issuecomment-2418967790)?

Thank you!

2025-03-20 08:51 UTC, closed without merging

2025-03-20 08:51 UTC, engcom-Charlie commented
Hi @ryansunxl,

Did you get a chance to look into [this](https://github.com/magento/magento2/pull/37576#issuecomment-2418967790) change. Currently I am closing this PR, please feel free to reopen it once done with the required implementation.