Avoid lots of uncessary exceptions during layout XML merge loading
magento/magento2 pull request #37570
Opened 2023-06-02 14:02 UTC by amenk

### Description

* Introduce a new function (for B/C compat we don't overwrite the protected _loadXmlString) to load and not throw an exception
* Use it in extract handlers -> no need to catch the exception any more

### Related Pull Requests

See also: https://github.com/justbetter/magento2-sentry/issues/113

### Fixed Issues (if relevant)
No magento issue created.

### Manual testing scenarios (*)
1. Install the sentry plugin
2. Have some invalid XML there
3. Exception is reported, even it is not necessary

### Reason

When using tools like Sentry, because of there inner workings, such exceptions still might be reported. While this is not exactly the root cause, it's always cleaner to not throw an exception and immediately catch it, if invalid cases can happen often.

This might even improve performance a bit and improves developer's experience.

### Remarks

There seems some invalid XML at that place in the code happen quite often - it might be also interesting to check if that can be avoided.

This is a simple, trivial change to the code and should not break anything, so hopefully this can get triaged quickly and without to much back-and-forth about the testing procedure :-)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [not applicable] All new or changed code is covered with unit/integration tests (if applicable)
 - [not applicable] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [waiting] All automated tests passed successfully (all builds are green)

2023-06-05 08:22 UTC, amenk commented
@magento run all tests

2025-04-25 10:05 UTC, engcom-Hotel commented
@magento run all tests

2025-04-25 13:19 UTC, engcom-Hotel requested changes
Hello @amenk,

Thanks for the contribution!

Please fix the failed static test and also let us know of we can reproduce this original issue without using any 3rd party extensions. 

Also please let us know which kind of exceptions are not generating after this fix.

Thanks

2025-04-25 13:29 UTC, amenk commented
Almost two years later I am a bit out of context of this.

The issue was mostly visible with the sentry plugin.

Feel free to take over and fix the static tests ... :-) Thank you!

2025-04-30 10:03 UTC, engcom-Dash commented
Hi @amenk ,

We attempted to reproduce the exception in Magento by applying some code level tweaks.
 
We observed that $this->updates[] property used in extractHandlers() method was consistently returning empty array[]. This is because initially it is set as empty and not getting updated anywhere prior to the extractHandlers() call.
 
To simulate the issue we pushed some invalid xml into  $this->updates[] and verified the behaviour against the changes introduced in the PR.
 
On Magento 2.4-develop (Before applying the PR changes) We encountered the following exception:
 
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/269efb73-d8d6-4360-9b2f-98054acad382" />

After PR changes there were no exceptions were observed.

However, since _loadXmlString is invoked in multiple places in the file, there is possibility that similar exception could arise in other scenarios in the future.
 
However changes in the PR looks good to avoid the unnecessary exceptions during xml merge loading hence we can proceed with the PR. I am taking care of the failing static test cases.

Thank you!

2025-04-30 10:13 UTC, engcom-Dash commented
@magento run all tests

2025-04-30 12:22 UTC, engcom-Dash commented
@magento create issue

2025-04-30 12:24 UTC, engcom-Dash commented
@engcom-Hotel I have fixed static test cases. Could you please review it?

Thanks

2025-05-02 06:49 UTC, engcom-Hotel requested changes
Hello @engcom-Dash,

Please refer to the below review comments.

Thanks

2025-05-02 06:49 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/View/Model/Layout/Merge.php
> +     * @return \SimpleXMLElement
The @return annotation here does not align with its possible return values. `simplexml_load_string` can return false if the XML is invalid as well

2025-05-02 06:49 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/View/Model/Layout/Merge.php
> +    protected function _safeLoadXmlString($xmlString)
Add strict type declarations to _safeLoadXmlString

2025-05-02 08:02 UTC, engcom-Dash commented
@magento run all tests

2025-05-02 10:13 UTC, engcom-Dash commented on lib/internal/Magento/Framework/View/Model/Layout/Merge.php
> +     * @return \SimpleXMLElement
added @return \SimpleXMLElement | false in return type

2025-05-02 10:14 UTC, engcom-Dash commented on lib/internal/Magento/Framework/View/Model/Layout/Merge.php
> +    protected function _safeLoadXmlString($xmlString)
added strict type declaration

2025-05-02 10:15 UTC, engcom-Dash commented
@engcom-Hotel suggested changes has been made hence moving this back to pending review. could you please reviwe it once ?

2025-05-05 02:38 UTC, engcom-Hotel commented
@magento run all tests

2025-05-05 05:06 UTC, engcom-Hotel approved these changes

2025-05-05 09:06 UTC, engcom-Dash commented
@magento run all tests

2025-05-05 11:58 UTC, engcom-Dash commented
@amenk Thank you for the contirbution & collaboration!

<h3>✔️  QA Passed </h3>

Preconditions:
Install fresh magento 2.4-develop

Steps to reproduce:
Please refer comment https://github.com/magento/magento2/pull/37570#issuecomment-2841465709

Before:  ❌ 

<img width="1458" alt="Screenshot 2025-05-05 at 2 33 12 PM" src="https://github.com/user-attachments/assets/e255d156-36f8-43f0-9766-859ec5312850" />


After: ✔️ 

No warnings & error were logged/observed after switching to the PR Branch.

Build is Green hence moving this PR in Merge in Progress

![image](https://github.com/user-attachments/assets/bbbcd043-217d-4b85-8259-c33c643745ee)

2025-05-05 12:10 UTC, amenk commented
@engcom-Dash Thank you for finalizing this!

2025-06-26 06:32 UTC, merged