customer Orders query shipment comments created_at is returned in +0 timezone not in store configured timezone
magento/magento2 pull request #37642
Opened 2023-06-20 12:05 UTC by Kannakiraj123

### Description (*)
This pull request (PR) will be change created_at date to local timezone format date in customer order query
   

### Related Pull Requests
 I added function to change created_at date to local timezone format date.

### Fixed Issues (if relevant)

1. Fixes #36947 

### Manual testing scenarios (*)
1. Create order
2. Call customer Orders query and check created_at, order_date  field from orders
3. Result is that the time from both admin order view page and query be the same and in our configured timezone

<img width="1399" alt="Screenshot 2023-06-20 at 5 14 57 PM" src="https://github.com/magento/magento2/assets/88073031/e531f40b-3755-4c83-bb1b-6ec94b2bd96d">

<img width="494" alt="Screenshot 2023-06-20 at 5 14 41 PM" src="https://github.com/magento/magento2/assets/88073031/e2177be3-aacf-4fee-8d21-e2d366de20f8">

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-06-20 12:05 UTC, Kannakiraj123 commented
@magento run all tests

2023-06-21 08:52 UTC, Kannakiraj123 commented
@magento run all tests

2023-06-22 06:44 UTC, Kannakiraj123 commented
@magento run all tests

2023-09-14 00:56 UTC, engcom-Hotel commented
@magento run all tests

2023-09-14 01:02 UTC, engcom-Hotel commented
@magento run all tests

2023-09-14 05:39 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests

2023-09-14 07:19 UTC, engcom-Hotel requested changes
Hello @Kannakiraj123,

Thanks for the contribution!

As part of the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please cover the changes with some automated tests.

It seems the build failures are due to PR changes, 2 consecutive build runs generate the same failures for eg:
Integration Test Failures:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37642/57cdd3994f3d01648fd8b948238415f4/Integration/console-error-logs.html

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37642/9bc23ef2e0b2f9f08101a252a1280025/Integration/console-error-logs.html

WebApi Tests:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37642/cfba89fccf9b7e6a7cfd15e02df92968/WebApi/console-error-logs.html

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37642/9a1ee6305a17424e3c5767e83bdd0af3/WebApi/console-error-logs.html

Please fix those as well

2023-09-25 10:48 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests, WebAPI Tests

2023-09-26 17:48 UTC, engcom-Charlie commented
@magento run Functional Tests CE, Functional Tests B2B, WebAPI Tests

2023-10-04 06:31 UTC, engcom-Charlie commented
Hi @Kannakiraj123,

Thank you for your contribution!

It seems that you are working on this PR, are you going o take care of build failures as well as automation test coverage. Please confirm once.

Thank you!

2023-10-04 07:02 UTC, Kannakiraj123 commented
@magento run WebAPI Tests

2023-10-04 08:38 UTC, Kannakiraj123 commented
@magento run all tests

2023-10-04 13:35 UTC, engcom-Echo commented
@magento run WebAPI Tests,Functional Tests EE,Functional Tests CE

2023-10-05 08:04 UTC, engcom-Hotel requested changes
Hello @Kannakiraj123,

Thanks for the contribution!

Please have a look into the review points.

Thanks

2023-10-05 08:04 UTC, engcom-Hotel commented on app/code/Magento/SalesGraphQl/Model/Formatter/Order.php
> +        Converter $converter
Adding new parameter in this way is backward incompatible, please go through with the below document for reference:

https://developer.adobe.com/commerce/contributor/guides/code-contributions/backward-compatibility-policy/#adding-a-constructor-parameter

Please fix the same in other places as well.

2023-10-10 08:42 UTC, engcom-Echo commented
@magento run all test

2023-10-10 08:42 UTC, engcom-Echo commented
@magento run all tests

2023-10-10 10:19 UTC, engcom-Echo commented
@magento run Integration Tests,Functional Tests CE

2023-10-12 07:18 UTC, engcom-Hotel commented
@magento run Integration Tests

2023-10-12 10:06 UTC, engcom-Hotel approved these changes

2023-10-18 13:55 UTC, engcom-Delta commented
Hi @Kannakiraj123, @engcom-Hotel ,

Thanks for the collaboration & contribution!

### :x: QA not Passed    
                                    
Customer Orders query shipment comments created_at is returned in +0 timezone not in store configured timezone

**Manual Scenario Steps**

Configure your store with a timezone different from +0
Create a Shipment with a comment
Verify the comment created_at in the normal view phtml in the website
Call customer Orders query and check created_at field from shipment comment

**:heavy_check_mark: Expected result After Fix** 

 The time from both view and query be the same and in our configured timezone

**:x: Actual result After Fix** 

Timezone
<img width="1428" alt="Screenshot 2023-10-18 at 7 22 09 PM" src="https://github.com/magento/magento2/assets/51681379/5f305c8b-c336-43a5-bd45-8c7be7afc33b">

Order detail in admin 
<img width="1440" alt="Screenshot 2023-10-18 at 6 55 19 PM" src="https://github.com/magento/magento2/assets/51681379/e271e989-860b-491d-a4d0-1ad50784d55c">

Order in Graphql
<img width="1311" alt="Screenshot 2023-10-18 at 7 03 19 PM" src="https://github.com/magento/magento2/assets/51681379/da3e2d60-1f09-4aa9-ade2-a68cde8a8028">

2023-10-18 14:09 UTC, engcom-Delta requested changes
The time from view is right in our timezone, and in query it is in +0 timezone

2023-11-03 21:08 UTC, engcom-Delta commented
Hi @Kannakiraj123,
Thanks for your contribution. 

As per the issue linked to this https://github.com/magento/magento2/issues/36947 we are facing multiple issues which were not identified earlier, Please check comment added by the contributor on the issue :  https://github.com/magento/magento2/issues/36947#issuecomment-1773333104.

Steps to reproduce followed to test the PR as follows.

Configure store with a timezone different from +0

<img width="1428" alt="new" src="https://github.com/magento/magento2/assets/51681379/643b51a7-47e1-4c7d-a018-e4758cc016cd">

Create a Shipment with a comment

<img width="1435" alt="new1" src="https://github.com/magento/magento2/assets/51681379/a1b522c1-aa0c-4d3c-a1f0-64cc1e8ba46a">

Verify the comment created_at in the normal view phtml in the website

<img width="1300" alt="new2" src="https://github.com/magento/magento2/assets/51681379/148a6d24-9c3e-41e2-a77a-274cde2049b4">

Call customer Orders query and check created_at field from shipment comment

<img width="1257" alt="new3" src="https://github.com/magento/magento2/assets/51681379/cfe89c15-74e7-4471-8046-c98d1799a9c6">

We found out that we are facing issue with everywhere where timezone is present and after taking the PR changes we were not able to get the timezone fixed in any scenario.

Let us know the scenarios for which the PR is made as there are some conflicts present related to the PR and the linked issue and confirm if we have keep the PR on hold

Thanks,

2023-11-06 11:12 UTC, engcom-Delta commented
Due to the below additional issue and conflicts present in the linked issue and the PR we are moving it to on hold status

https://github.com/magento/magento2/pull/37642#issuecomment-1793107311

2023-11-14 15:04 UTC, engcom-Delta commented
Hi @Kannakiraj123 , @engcom-Hotel 

Thanks for the collaboration & contribution!

### :x: QA not Passed

Customer Orders query shipment comments created_at is returned in +0 timezone still not in store configured timezone

**Manual Scenario Steps**

1.  Configure your store with a timezone different from +0
2. Create a Shipment with a comment
3. Verify the comment created_at in the normal view phtml in the website
4. Call customer Orders query and check created_at field from shipment comment

**:heavy_check_mark: Expected result After Fix** 

Customer Orders query shipment comments created_at is returned in +0 timezone should be in store configured timezone

**:x: Actual result After Fix** 

Configured store with a timezone different from +0

<img width="1434" alt="Screenshot 2023-11-14 at 8 13 08 PM" src="https://github.com/magento/magento2/assets/51681379/420579c5-f284-45dc-b3e9-9a1d58a9342a">

Created a Shipment with a comment

<img width="1425" alt="Screenshot 2023-11-14 at 8 21 48 PM" src="https://github.com/magento/magento2/assets/51681379/736e05fc-886d-4054-ab6a-bc811b5b5277">

Verify the comment created_at in the normal view phtml in the website

<img width="1440" alt="Screenshot 2023-11-14 at 8 22 06 PM" src="https://github.com/magento/magento2/assets/51681379/86ea292d-7ce8-4b81-a992-116b67514608">

<img width="1439" alt="Screenshot 2023-11-14 at 8 22 26 PM" src="https://github.com/magento/magento2/assets/51681379/d670f155-eb8b-4f84-8b67-9c5ea2f06f91">

<img width="1440" alt="Screenshot 2023-11-14 at 8 23 14 PM" src="https://github.com/magento/magento2/assets/51681379/76de589d-241b-4611-bbff-552aa49178cc">

Called customer Orders query and check created_at field from shipment comment

<img width="1440" alt="Screenshot 2023-11-14 at 8 25 00 PM" src="https://github.com/magento/magento2/assets/51681379/8d00eec2-ee18-4e23-a659-45ef84307394">


Hence moving it to Changes requested.

2023-11-14 15:07 UTC, engcom-Delta requested changes
The time from view is right in our timezone, and in query it is in +0 timezone

2023-11-21 13:22 UTC, engcom-Delta commented
As the basic functionality for the PR is not working , moving this to on hold status. PFB the comment

https://github.com/magento/magento2/pull/37642#issuecomment-1810409304

2023-12-06 15:01 UTC, engcom-Delta commented
Hi @Kannakiraj123 , As the the PR is not fulfilling the basic functionality we are closing this PR as of now. Adding the comments below.
https://github.com/magento/magento2/pull/37642#issuecomment-1810409304

Feel free to reopen this PR in future if required.

2023-12-06 15:01 UTC, closed without merging