[Fixed: #31396] Data/Schema Patches getAliases() not working as expected
magento/magento2 pull request #37682
Opened 2023-06-28 10:57 UTC by MatthijsBreed

### Description (*)
This PR fixed next issues #31396 #23031

This PR is a continuation of work in PR 31635 (https://github.com/magento/magento2/pull/31635) to account for every patch alias that might be already applied and to persist any new patch aliases

### Fixed Issues (if relevant)
#31396 #23031

### Testing Scenario
**1.** Create new Data Patch and apply via `bin/magento setup:upgrade`

**2.** See that patch is added to `patch_list` in the database

**3.** Rename Data Patch file

**4.** Re-run `bin/magento setup:upgrade`

**5.** See that the new patch name is added to `path_list` but the apply() function has not been called

2023-06-28 10:57 UTC, MatthijsBreed commented
@magento run all tests

2023-07-20 13:52 UTC, sippsolutions requested changes

2023-07-20 13:52 UTC, sippsolutions commented on lib/internal/Magento/Framework/Setup/Test/Unit/Patch/PatchApplierTest.php
> +use phpDocumentor\Reflection\Types\True_;
this can be removed, or not?
```suggestion
```

2023-07-20 13:52 UTC, sippsolutions commented on lib/internal/Magento/Framework/Setup/Patch/PatchApplier.php
> +     * Checks if patch should be applied by already applied patch alias names
```suggestion
     * Check if patch should be applied by already applied patch alias names
```

2023-07-20 13:52 UTC, sippsolutions commented on lib/internal/Magento/Framework/Setup/Patch/PatchApplier.php
> +                    $shouldApply = false;
variable assigning is not necessary, you can use `return` directly

2023-07-20 16:24 UTC, MatthijsBreed commented
@magento run all tests

2023-07-20 16:35 UTC, MatthijsBreed commented
@magento run Unit Tests

2023-07-20 20:48 UTC, MatthijsBreed commented
@sippsolutions , thank you for your feedback.

I have checked all failing tests, but after the last commit, the only tests that are failing are urelated functionalities, are these blocking for this PR or is there another way to resolve them?

Unit Tests fail on 'Magento\CatalogGraphQl\Test\Unit\DataProvider\Product\SearchCriteriaBuilderTest::testBuild'

Functional tests fail on "Magento\AcceptanceTest\_InventorySingleModeSuite_0_G\Backend\StorefrontValidateVisualSwatchAbsenceOfAttributeWhenProductStocksOutTestCest::StorefrontValidateVisualSwatchAbsenceOfAttributeWhenProductStocksOutTest" and "Magento\AcceptanceTest\_default\Backend\AdminApplyChangePriceForConfigurableProductWithAssignedSimpleProductsTestCest::AdminApplyChangePriceForConfigurableProductWithAssignedSimpleProductsTest"

Webapi tests fail on 'Magento\GraphQl\Catalog\ProductSearchTest::testFilterProductsBySingleCategoryId'

2023-09-14 01:03 UTC, engcom-Hotel commented
@magento run all tests

2023-09-14 05:44 UTC, engcom-Hotel commented
@magento run Integration Tests, Functional Tests CE

2023-09-14 07:23 UTC, engcom-Hotel commented
@magento run Integration Tests, Functional Tests CE

2023-09-14 15:00 UTC, engcom-Hotel requested changes
Hello @MatthijsBreed,

Thanks for the collaboration!

Please check the review comment.

Thanks

2023-09-14 15:00 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Setup/Patch/PatchApplier.php
> +                $shouldApply = false;
Can we use a break statement after this, so that it will not iterate further?

2023-09-15 09:07 UTC, MatthijsBreed commented on lib/internal/Magento/Framework/Setup/Patch/PatchApplier.php
> +                $shouldApply = false;
Hi @engcom-Hotel ,
Thank you for the feedback.
Function has been refactored to use early return

2023-09-18 05:46 UTC, engcom-Hotel commented
@magento run all tests

2023-09-18 05:51 UTC, engcom-Hotel commented
@magento run all tests

2023-09-18 09:35 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE,  Integration Tests, Unit Tests

2023-09-18 11:22 UTC, engcom-Hotel approved these changes
Hello @MatthijsBreed,

Thanks for the contribution!

Code changes look good to me and failed tests seem flaky.

Hence approving this PR.

2023-09-26 06:10 UTC, engcom-Echo commented
@magento run all tests

2023-09-27 06:20 UTC, engcom-Echo commented
@MatthijsBreed,

We are not able to reproduce the issue.
Can you please confirm the issue still exist on 2.4-develop?

To Reproduce the issue we have followed below steps.

1. Create new Data Patch and apply via `bin/magento setup:upgrade`
2. See that patch is added to `patch_list` in the database
3. Rename Data Patch file and add old name to aliases
4. Re-run `bin/magento setup:upgrade`
5. Patch gets applied successfully.

Also please refer to this [abc8e696](https://github.com/magento/magento2/commit/abc8e696).

Lets us know if you are still facing the issue on 2.4-develop with detailed steps. 

Moving it to `on hold`

2023-09-27 08:30 UTC, MatthijsBreed commented
@engcom-Echo 

The reproduction steps you described you described are the problem this PR aims to solve.
The commit you linked is only a check for possibly writing duplicate aliases to the database AFTER the patch has been applied.

Current (incorrect) situation:
- Create a patch called 'A' with no aliases
- Run `bin/magento setup:upgrade`, patch A gets applied and 'A' is added to the `patch_list` table
- Rename patch A to 'B'
- Add 'A' to the aliases 
- Run `bin/magento setup:upgrade` again, patch A gets applied again and 'B' is added to the `patch_list` table

Desired situation:
- Create a patch called 'A' with no aliases
- Run `bin/magento setup:upgrade`, patch A gets applied and 'A' is added to the `patch_list` table
- Rename patch A to 'B'
- Add 'A' to the aliases 
- Run `bin/magento setup:upgrade` again, patch A is not applied and 'B' is added to the `patch_list` table

Please see the PR description and the issues linked therein

2023-09-27 11:50 UTC, engcom-Echo commented
@MatthijsBreed 

I have followed the step mentioned [here](https://github.com/magento/magento2/pull/37682#issuecomment-1736944595) 

Before PR
1. Create a patch called 'ExampleDataPatch' with no aliases
```
class ExampleDataPatch implements DataPatchInterface
{
    /**
     * @var ModuleDataSetupInterface
     */
    private $moduleDataSetup;


    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(
        ModuleDataSetupInterface $moduleDataSetup,
        LoggerInterface $logger
    ) {
        $this->moduleDataSetup = $moduleDataSetup;
        $this->logger = $logger;
    }
    
    public function apply()
    {
        $this->moduleDataSetup->startSetup();
        $this->logger->info('ExampleSchemaPatch: Apply method executed.');
        $this->moduleDataSetup->endSetup();
    }
    
    public static function getDependencies()
    {
        return [];
    }
    
    public function getAliases()
    {
        return [];
    }
}
```
3. Run `bin/magento setup:upgrade`, patch ExampleDataPatch gets applied and 'ExampleDataPatch' is added to the patch_list table
5. Rename patch ExampleDataPatch file and class name to 'ChangedExampleDataPatch'
6. Add 'ExampleDataPatch' to the aliases 
```
public function getAliases()
    {
        return [
            ExampleDataPatch::Class
        ];
    }
```
7. Run `bin/magento setup:upgrade` again, patch ExampleDataPatch gets applied again verfied from log file and 'ChangedExampleDataPatch' is added to the patch_list table
<img width="823" alt="Screenshot 2023-09-27 at 5 02 40 PM" src="https://github.com/magento/magento2/assets/51681435/a843c038-e4d1-4eec-baf4-1bc0d16f2554">

After PR Changes
1. Follow step 1-6 as above case
2. Run `bin/magento setup:upgrade` again, patch ExampleDataPatch not applied again verfied from log file. But `ChangedExampleDataPatch` is not added to the `patch_list` table
<img width="1028" alt="Screenshot 2023-09-27 at 5 06 43 PM" src="https://github.com/magento/magento2/assets/51681435/fe573ea4-8865-4138-af4b-181d391da716">

Let us know if we have missed anything here.

2023-10-04 13:53 UTC, engcom-Echo commented
@MatthijsBreed can you please have a look at [comment](https://github.com/magento/magento2/pull/37682#issuecomment-1737240535) and suggest if we are missing anything here?

2023-10-10 10:23 UTC, engcom-Echo commented
@MatthijsBreed did you get time to have a look at [comment](https://github.com/magento/magento2/pull/37682#issuecomment-1737240535) ?

2023-10-16 05:59 UTC, engcom-Charlie commented
Hi @MatthijsBreed,

Thank you for your contribution!

As mentioned [here](https://github.com/magento/magento2/pull/37682#issuecomment-1737240535), please have a look and let us know if we are missing anything. 

Till then closing this PR. Please feel free to reopen it as you want to update further.

Thank you!

2023-10-16 05:59 UTC, closed without merging