Re-add the compound unique index to catalog_product_index_price_tmp
magento/magento2 pull request #37701
Opened 2023-07-03 13:25 UTC by nicka101

Addresses #37700

### Description (*)
Adds a composite unique constraint back to catalog_product_index_price_tmp (and by extension catalog_product_index_price_temp), to make the join used in [deleteOutdatedData](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Indexer/Product/Price/AbstractAction.php#L440) performant on large stores

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes magento/magento2#37700

### Manual testing scenarios (*)
1. Reindex catalog_product_price on a catalog with a very large number of prices and Magento 2.4.5+

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-07-03 13:27 UTC, nicka101 commented
@magento run all tests

2023-07-03 15:56 UTC, nicka101 commented
@magento run Functional Tests B2B

2023-07-06 18:40 UTC, nicka101 commented
@magento run all tests

2023-07-11 17:57 UTC, kandy commented
Hi @nicka101 
Adding this index will slow down inserting data to the table. 

So, can I recommend implementing other ways to resolve this issue?
Instead of joining temporary table to main table as it done in [deleteOutdatedData](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Indexer/Product/Price/AbstractAction.php#L440)
method, we can just select ids from temporary table and intersect it from ids of current butch

or similar changes to delete queries, like

   
        $query = $select->delete('main_table',
        [
            'main_table.entity_id IN (?)', $entityIds, \Zend_Db::INT_TYPE,/
             'main_table.entity_id not in ( select id from  'tmp_table' entity_id IN (?) and tmp_table.customer_group_id  = $customer_group_id and tmp_table.website_id = $website_id)',
             'main_table.customer_group_id  = $customer_group_id'
             'main_table.website_id = $website_id',
           
        );

2023-09-14 07:45 UTC, engcom-Hotel requested changes
Hello @nicka101,

Thanks for the contribution!

I agree with the @kandy [here](https://github.com/magento/magento2/pull/37701#issuecomment-1631254141), we need to think of some other way to resolve this issue.

This solution contains backward incompatibility changes.

Thanks

2023-09-25 13:33 UTC, engcom-Hotel commented
Hello @nicka101,

Thank you for your contribution!

As we have been unable to get any reply from your side for a long time, we are closing this PR for now. 

Whenever you are ready to take this up please free to reopen it or ask us to reopen the same. We will be happy to do that.

Thanks again!

2023-09-25 13:33 UTC, closed without merging

2024-07-30 12:22 UTC, dudzio12 commented
Well, the downtime for inserts is FAR more marginal than speed up on delete query. I understand it is not ideal, but having those indexes is a real improvement.