PageCache/AccessList: Add CIDR support
magento/magento2 pull request #37809
Opened 2023-07-27 15:08 UTC by tdgroot

### Description (*)

When accepting purge requests within a network, it's easier to just supply a CIDR range. 

### Related Pull Requests

None.

### Fixed Issues (if relevant)

None.

### Manual testing scenarios (*)

1. Go to **Advanced -> System -> Full Page Cache -> Varnish Configuration**)
2. Configure a CIDR range like `172.16.0.1/24`
3. Value should be valid and saved

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

2025-05-30 03:55 UTC, engcom-Hotel commented
@magento run all tests

2025-05-30 12:16 UTC, engcom-Hotel commented
@magento create issue

2025-05-30 12:39 UTC, engcom-Hotel commented
Hello @tdgroot,

Thanks for the contribution!

But as this is feature enhancement, we need a PO confirmation to proceed with this PR. We have started the process for the same. Meanwhile we are moving this PR `On Hold`.

Thanks

2025-06-02 04:43 UTC, engcom-Hotel commented
@magento run all tests

2025-06-03 13:42 UTC, engcom-Hotel commented
Hello @tdgroot,

We have received an approval for this PR for further evaluation. Hence moving it to appropriate bucket.

Thanks

2025-06-03 13:43 UTC, engcom-Hotel requested changes
Hello @tdgroot,

Thank you for your contribution to add CIDR notation support to PageCache access lists. This is a valuable enhancement that would allow for more flexible IP-based access control.

However, the PR currently only modifies the validation pattern without implementing the actual CIDR functionality. For full CIDR support, we need changes in:

- The component that performs IP matching against the access list
- A utility method to properly compare an IP against a CIDR range

Thanks

2025-06-03 13:43 UTC, engcom-Hotel commented on app/code/Magento/PageCache/Model/System/Config/Backend/AccessList.php
> +        if (!is_string($value) || !preg_match('/^[\w\s\.\-\,\:(\/\d+)?]+$/', $value)) {
1. The pattern places `(\/\d+)?` inside a character class `([...])`, which means these are treated as individual characters rather than a sequence.
2. The pattern remains overly permissive and would validate strings like "this is: a more / or less, valid string.... oh, lets add numbers 12345" which aren't valid IP addresses or CIDR notations

2025-06-07 06:24 UTC, hostep commented
> However, the PR currently only modifies the validation pattern without implementing the actual CIDR functionality. For full CIDR support, we need changes in:
> 
> The component that performs IP matching against the access list
> A utility method to properly compare an IP against a CIDR range

That's not really true, the only place where we use this configuration value is over here: https://github.com/magento/magento2/blob/7da46f5266db579ed999dd2de9219640cea17e36/app/code/Magento/PageCache/Model/Varnish/VclGenerator.php#L164
Which is used to output the access list into the VCL file that Magento generates for Varnish.
Varnish already supports CIDR notation in ACL's, so there is no need for extra matching  or parsing.

One thing that I'm not sure about, but maybe @tdgroot can clarify, is that the Varnish docs say to put the IP address in double quotes and the CIDR part outside of those quotes: https://varnish-cache.org/docs/trunk/users-guide/vcl-example-acls.html#acls
In this Magento code, the CIDR part would be included inside the double quotes. I have no idea if this will cause issues or will just work as expected?

2025-06-07 06:24 UTC, hostep commented on app/code/Magento/PageCache/Model/System/Config/Backend/AccessList.php
> +        if (!is_string($value) || !preg_match('/^[\w\s\.\-\,\:(\/\d+)?]+$/', $value)) {
The extra CIDR validation regex should indeed be moved outside of the character class, so should become something like this: `^[\w\s\.\-\,\:]+(\/\d+)?$`
Good remark!

2025-06-24 13:28 UTC, engcom-Hotel commented
Thanks for the inputs on this PR @hostep!

I agree with your point. @tdgroot have you got a chance to look into this PR?

Thanks

2025-07-14 06:32 UTC, engcom-Hotel commented
Hello @tdgroot,

Did you get a chance to look into this PR?

Thanks

2025-07-25 06:50 UTC, glo24157 commented
@tdgroot We may disregard the below review comment from this link https://github.com/magento/magento2/pull/37809#pullrequestreview-2892432998:

> However, the PR currently only modifies the validation pattern without implementing the actual CIDR functionality. For full CIDR support, we need changes in:
> 
>     * The component that performs IP matching against the access list
> 
>     * A utility method to properly compare an IP against a CIDR range

But we request you to please go through with the [other review comments](https://github.com/magento/magento2/pull/37809#discussion_r2123856809) as well as @hostep comment here https://github.com/magento/magento2/pull/37809#issuecomment-2951941758.

Thanks

2025-08-21 11:23 UTC, engcom-Hotel commented
Hello @tdgroot,

Gentle reminder for this PR.

2025-08-24 15:21 UTC, tdgroot commented
@engcom-Hotel I updated the PR with requested changes :)

2025-08-24 15:22 UTC, tdgroot commented
@hostep 
> I have no idea if this will cause issues or will just work as expected?

From my side, I have not experienced any issues with just putting these types of values as-is in the config.

2025-08-24 15:24 UTC, tdgroot commented on app/code/Magento/PageCache/Model/System/Config/Backend/AccessList.php
> +        if (!is_string($value) || !preg_match('/^[\w\s\.\-\,\:(\/\d+)?]+$/', $value)) {
Updated. The suffix is now outside of the character class and the regex is now applied for each item in the CSV list. Instead of accepting any `/\d+`, it is now limited from 0-32.

2025-08-25 00:21 UTC, engcom-Hotel commented
@magento run all tests

2025-08-25 10:30 UTC, engcom-Hotel requested changes
Hello @tdgroot,

Thanks for making the changes!

There are still some static test failures, please fix those. Other failures seems flaky to me.

Thanks

2025-09-08 09:23 UTC, engcom-Hotel commented
Hello @tdgroot,

Gentle reminder for the static test failure fixes.

Thanks

2025-09-29 07:28 UTC, engcom-Charlie commented
@magento run all tests

2025-09-29 09:32 UTC, engcom-Charlie commented
@magento run all tests

2025-09-29 11:35 UTC, engcom-Charlie commented
@magento run all tests

2025-10-06 10:35 UTC, engcom-Charlie commented
@magento run all tests

2025-10-06 14:18 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2025-10-07 06:09 UTC, engcom-Charlie commented
I have fixed all the static test failures, moving it to review again.

2025-10-07 09:49 UTC, engcom-Hotel approved these changes

2025-10-08 08:50 UTC, engcom-Bravo commented
@magento run all tests

2025-10-08 11:32 UTC, engcom-Bravo commented
Hi @tdgroot,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Manual testing scenarios**

- Go to Advanced -> System -> Full Page Cache -> Varnish Configuration
- Configure a CIDR range like 172.16.0.1/24
- Value should be valid and saved



**Before:** :heavy_multiplication_x:

<img width="1439" height="637" alt="Screenshot 2025-10-08 at 2 12 44 pm" src="https://github.com/user-attachments/assets/c86cb661-e39b-47ba-8439-6dd17dda5e70" />




**After:** :heavy_check_mark:


<img width="2608" height="3072" alt="Configuration-Settings-Stores-Magento-Admin-10-08-2025_02_19_PM" src="https://github.com/user-attachments/assets/b63f2509-6d70-44b5-b1b6-13447b7691ed" />




Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-10-08 12:46 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, WebAPI Tests

2025-10-09 12:09 UTC, engcom-Charlie commented
Few Functional B2B, EE and CE failures in recent 2 builds are not consistent. They are neither part of this PR nor failing because of the PR changes, seems to be flaky. The consistent once are known issues hence moving it to Merge In Progress.

**Functional B2B: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37809/b46792f8f79789f47d0f5252d4f44669/Functional/allure-report-b2b/index.html#categories
<img width="1037" height="553" alt="image" src="https://github.com/user-attachments/assets/78405f5f-1cc2-40ee-8f9b-1b4ce2b8bef3" />

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37809/54f64a76950f197112a7a5be56ff0d4d/Functional/allure-report-b2b/index.html#categories/39d2dfa67879cc2330ab48837fcc9a69/552cf7be275f72ba/
<img width="1153" height="539" alt="image" src="https://github.com/user-attachments/assets/33f6f9be-087a-4a66-a99b-4a334814a847" />

**Functional CE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37809/280d82586ce776949380cc37509dd54b/Functional/allure-report-ce/index.html#categories/39d2dfa67879cc2330ab48837fcc9a69/503c1569de7685a8/
<img width="1169" height="319" alt="image" src="https://github.com/user-attachments/assets/5e6d6f4a-bb1a-4532-9844-388f576e93bb" />

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37809/e5536f7d07e188433c76f75a1a4e9b05/Functional/allure-report-ce/index.html#categories/39d2dfa67879cc2330ab48837fcc9a69/a3314de085c9558c/
<img width="986" height="394" alt="image" src="https://github.com/user-attachments/assets/9bf3b1a9-562b-471d-bd57-b84aeffb52d4" />

**Functional EE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37809/3e148d881a5ec2d65f14fd60123f41b0/Functional/allure-report-ee/index.html#categories
<img width="1148" height="415" alt="image" src="https://github.com/user-attachments/assets/7c30f219-8bb2-4e43-a724-441728bfbe42" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37809/70cd03d4a607d8bdb79df6d03d333af6/Functional/allure-report-ee/index.html#categories/3418275ac42b7ca8566f7871b42bcde6/1c61058d681db22b/
<img width="1107" height="560" alt="image" src="https://github.com/user-attachments/assets/22b0818f-cff9-4e8d-82f3-353b786aaf7a" />

**Known Issues:**
- [ACQE-8846](https://jira.corp.adobe.com/browse/ACQE-8846):StorefrontGuestCreateOrderWithConfigurableProductCustomStockTest
- [ACQE-8852](https://jira.corp.adobe.com/browse/ACQE-8852):StorefrontReviewAndPaymentPageWithSimpleProductCustomStockTest
- [ACQE-8845](https://jira.corp.adobe.com/browse/ACQE-8845):StorefrontGuestCreateOrderWithBundleProductCustomStockTest
- [ACQE-8847](https://jira.corp.adobe.com/browse/ACQE-8847):StorefrontGuestCreateOrderWithGroupedProductCustomStockTest
- [ACQE-8655](https://jira.corp.adobe.com/browse/ACQE-8655):AdminRmaSettingsConfigurationTest

2025-11-04 06:39 UTC, merged