37607 rest configurable products SKU childrenendpoint missing media gallery entries
magento/magento2 pull request #37862
Opened 2023-08-08 12:03 UTC by JettyRohanAditya

media_gallery_entries field is missing from configurable-products/sku/children RestEndpoint

### Description (*)

media_gallery_entries field is missing in rest endpoint, Linkmanagement.php is the file for the rest endpoint.
That function is missing code for getting media_gallery_entries.
Created a custom factory for storing and displaying the media_gallery_entries. 

### Related Pull Requests

https://github.com/magento/magento2/issues/37607

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37607

### Manual testing scenarios (*)

### Steps to reproduce
1. Create a new configurable product and add configurations with unique product images.
2. Make a request in postman using the /configurable-products/{sku}/children.
### Changes made:-
**Created custom Factory for media_gallery_entries.**

\Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryInterfaceFactory $myModelFactory

**Created a custom function for setting media gallery entries into the factory and retrieved data from it.**

public function getMediaEntries($images){    $media = $this->myModelFactory->create();    $mediaGalleryEntries=[];    foreach ($images as $image) {        $media->setId($image["value_id"]);        $media->setMediaType($image["media_type"]);        $media->setLabel($image["label"]);        $media->setPosition($image["position"]);       $media->setDisabled($image["disabled"]);       $media->setFile($image["file"]);        $mediaGalleryEntries[]=$media->getData();    }    return $mediaGalleryEntries;} 

 **Line where we are getting all the media gallery entries from** 

$images= (array)$child->getMediaGallery('images'); 

**Line responsible for retrieving media gallery entries from the custom factory and giving them in result payload**

$attributes['media_gallery_entries'] = $this->getMediaEntries($images);

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-08-23 05:35 UTC, JettyRohanAditya commented
@magento run all tests

2023-08-23 08:31 UTC, JettyRohanAditya commented
@magento run all tests

2023-09-14 09:33 UTC, engcom-Hotel commented
@magento run all tests

2023-09-14 09:53 UTC, engcom-Hotel commented
@magento run all tests

2023-09-15 07:29 UTC, engcom-Hotel requested changes
Hello @JettyRohanAditya,

Thanks for the contribution!

Please review the comments below and add some automated tests to cover the PR changes.

Thanks

2023-09-15 07:29 UTC, engcom-Hotel commented on app/code/Magento/ConfigurableProduct/Model/LinkManagement.php
> +    //private $mediaGalleryProcessor;
I think we can remove it from here as it is of no use

2023-09-15 07:29 UTC, engcom-Hotel commented on app/code/Magento/ConfigurableProduct/Model/LinkManagement.php
> +//        \Magento\Catalog\Api\Data\ProductInterface $productInterface,
I think we can remove it from here as it is of no use

2023-09-15 07:29 UTC, engcom-Hotel commented on app/code/Magento/ConfigurableProduct/Model/LinkManagement.php
> +//        $this->productInterface=$productInterface;
I think we can remove it from here as it is of no use

2023-09-18 12:30 UTC, engcom-Echo commented
@magento run all tests

2023-09-19 03:02 UTC, engcom-Echo commented
@magento run all tests

2023-09-19 05:27 UTC, engcom-Echo commented
@magento run all tests

2023-09-19 07:03 UTC, engcom-Hotel requested changes

2023-09-19 07:03 UTC, engcom-Hotel commented on app/code/Magento/ConfigurableProduct/Model/LinkManagement.php
> +        \Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryInterfaceFactory $myModelFactory
Adding Params in this way may be backward incompatible, set them null as default and use objectmanager to initialize those later. Please refer to the `$this->attributeFactory` initialization for reference.

2023-09-19 09:51 UTC, engcom-Echo commented
@magento run all tests

2023-09-19 11:40 UTC, engcom-Echo commented
@magento run all tests

2023-09-20 05:13 UTC, engcom-Echo commented
@magento run all tests

2023-09-20 06:09 UTC, engcom-Echo commented
@magento run all tests

2023-09-20 06:26 UTC, engcom-Echo commented
@magento run all tests

2023-09-20 07:35 UTC, engcom-Echo commented
@magento run static tests

2023-09-20 08:12 UTC, engcom-Echo commented
@magento run all tests

2023-09-20 08:50 UTC, engcom-Echo commented
@magento run all tests

2023-09-20 10:24 UTC, engcom-Echo commented
@magento run Functional Tests CE

2023-09-21 05:32 UTC, engcom-Hotel commented
@magento run all tests

2023-09-21 07:49 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

2023-09-21 11:00 UTC, engcom-Hotel commented
Build fails seems flaky to me, the failures are different in 2 consecutive runs.

**B2B**
![image](https://github.com/magento/magento2/assets/51681618/c4c3d203-b927-464f-a8ff-d9d3f10d16c6)

![image](https://github.com/magento/magento2/assets/51681618/c801c011-c171-4b47-8cea-7ab600becad1)

**CE**
![image](https://github.com/magento/magento2/assets/51681618/c1c7d308-065d-499d-9c4a-354d64bdc778)

![image](https://github.com/magento/magento2/assets/51681618/d6d7a840-9752-45ba-80b2-343bf09a4cd0)

**EE**
![image](https://github.com/magento/magento2/assets/51681618/89dbdf0d-b690-4e4c-ba6d-0fc66e5cd969)

![image](https://github.com/magento/magento2/assets/51681618/a4f8784e-1740-4461-8250-f3a6fc8b225f)

Hence moving this PR further.

Thanks

2023-09-21 11:01 UTC, engcom-Hotel approved these changes

2023-10-03 10:06 UTC, engcom-Hotel commented
@magento run all tests

2023-10-03 10:11 UTC, engcom-Hotel commented
@magento give me test instance

2023-10-03 12:38 UTC, engcom-Delta commented
### :heavy_check_mark: QA Passed
 
**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**
- Postman should be configured with magento2
 
**Manual testing scenario:**

	1	Create a new configurable product
	2	Add configurations with unique product images
	3	Make a request in postman using the /configurable-products/{sku}/children


**Before:** :heavy_multiplication_x: 
before 37862
 
 
**After:** :heavy_check_mark:  
 after 37862
 

Builds are failed. Hence, moving this PR to Extended Testing.

2023-10-04 01:54 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2023-10-04 04:52 UTC, engcom-Echo commented
Functional Tests B2B failure are different on last two run on same commit.

Run1
<img width="1440" alt="Screenshot 2023-10-04 at 10 13 12 AM" src="https://github.com/magento/magento2/assets/51681435/fc64c990-ffb1-4784-9b2f-9fc2d992b5e5">

Run2
<img width="1440" alt="Screenshot 2023-10-04 at 10 13 19 AM" src="https://github.com/magento/magento2/assets/51681435/5b7c4d3a-6c10-4c34-8cff-5f2328305de0">

Hence moving it to `merge in progress`

2023-10-04 06:05 UTC, engcom-Echo commented
Functional Tests B2B failure are different on last two run on same commit.

Run1
<img width="1440" alt="Screenshot 2023-10-04 at 10 13 12 AM" src="https://github.com/magento/magento2/assets/51681435/fc64c990-ffb1-4784-9b2f-9fc2d992b5e5">

Run2
<img width="1440" alt="Screenshot 2023-10-04 at 10 13 19 AM" src="https://github.com/magento/magento2/assets/51681435/5b7c4d3a-6c10-4c34-8cff-5f2328305de0">

Hence moving it to `merge in progress`

2023-10-20 13:42 UTC, merged