Turn CommandList into `@api` to ensure backwards compatibility
magento/magento2 pull request #37901
Opened 2023-08-21 07:03 UTC by engcom-Echo

### Description (*)
This PR is copy of [29762](https://github.com/magento/magento2/pull/29762). As in original PR target branch was 2.5-develop we have modified to point to 2.4-develop.

~In my personal opinion using `CommandListInterface` is invalid way of adding new Commands to interface.
It is because Constructor is not a part of Interface (Service Contract), thus it is not "guaranteed" part of Interface.~

~Using `CommandList` is against Magento rules, thus it's implementation is not guaranteed and can change in backwards-incompatible way.~

~I'm extending the `CommandList` with `@api` to ensure developers that this class won't change backwards-incompatible way and this way - they can either add new classes using:~
- ~Argument injection to `CommandList` class~
- ~Plugin on `getCommands` on `CommandListInterface`.~

~I'd love to get your feedback there.~

After discussion with @kandy I decided to add the `__construct()` to the API.

Answering the main concerns: https://3v4l.org/8ug8i
![image](https://user-images.githubusercontent.com/1639941/91346291-ea6e2900-e7e0-11ea-950f-f81854ed8735.png)

As it affects you (community) I need your 👍🏻 or comments to pass the change:
![image](https://user-images.githubusercontent.com/1639941/91346340-fd80f900-e7e0-11ea-9ae4-74a197221b4e.png)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Thanks

- @jissereitsma for inspiration

### Resolved issues:
1. [x] resolves magento/magento2#31102: Include Constructor to be a part of `CommandListInterface` API, extend inline documentation

2023-08-21 07:17 UTC, engcom-Echo commented
@magento run all tests

2023-08-21 07:19 UTC, engcom-Hotel approved these changes
This PR is the reference of the PR https://github.com/magento/magento2/pull/29762, we have just changed the target branch to 2.4-develop from 2.5-develop.

Hence approving this PR to move forward.

Thanks

2023-08-21 13:14 UTC, ihor-sviziev approved these changes

2023-08-29 07:19 UTC, engcom-Hotel commented
Hello @lbajsarowicz,

Thanks for the contribution!

:heavy_check_mark: QA Passed

As in this PR, the changes are related to making the `lib/internal/Magento/Framework/Console/CommandList.php` class a `Public Interface` by adding the `@api` annotation and adding the return type for `getCommands()` as `array`.

There is nothing to reproduce in this issue but it is a good to have feature. Hence moving this PR further process.

Due to SVC failure, moving this PR for approval.

Thanks

2023-08-29 07:20 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Unit Tests

2023-08-29 07:43 UTC, engcom-Hotel commented
Created an approval [JIRA](https://jira.corp.adobe.com/browse/AC-9408) from approval of SVC failure.

2024-01-19 08:03 UTC, engcom-Hotel commented
@magento run Semantic Version Checker

2025-04-14 05:35 UTC, engcom-Hotel commented
@magento run all tests

2025-04-28 14:38 UTC, engcom-Hotel requested changes
Hello @lbajsarowicz,

Please have a look into the below review comment. The change has been suggested by the internal team due to BiC.

Thanks

2025-04-28 14:38 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Console/CommandList.php
> +    public function getCommands(): array
Please remove this return type as this change is Backward incompatible.

2025-04-29 08:49 UTC, jissereitsma commented on lib/internal/Magento/Framework/Console/CommandList.php
> +    public function getCommands(): array
Doesn't it make sense to slowly add in type hinting like this? PHP 5.3 is quite some time ago. And you can always add stronger typing to a class without breaking the interface. As I see it, nothing is breaking backward compatibility here?

2025-04-30 15:19 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Console/CommandList.php
> +    public function getCommands(): array
Hello @jissereitsma, I guess this change breaks compatibility with existing code that:

- Calls getCommands() and expects a return type other than an array.
- Extends or implements the `CommandList` class or `CommandListInterface` without updating overridden/implemented methods.

2025-05-06 07:55 UTC, engcom-Dash commented
@magento run all tests

2025-05-06 10:26 UTC, engcom-Dash commented
@lbajsarowicz as per our discussion over Slack, I worked on the review comments & failed static cases. @engcom-Hotel Could you please review it?

Thanks!

2025-05-06 11:03 UTC, jissereitsma commented on lib/internal/Magento/Framework/Console/CommandList.php
> +    public function getCommands(): array
I'm not sure whether these arguments make sense. Yes, indeed somebody could create a DI plugin and return a string from the `getCommands()` method. But that will break the entire Magento CLI anyway! The same way counts for rewriting the `CommandList` class or `CommandListInterface` interface. So, the choice is between opting for the possibility that somebody has hacked the Magento core to an extend where the CLI does not work properly anymore, or sticking to modern-day PHP standards. I would opt for the future instead.

2025-05-06 11:08 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Console/CommandList.php
> +    public function getCommands(): array
> Calls getCommands() and expects a return type other than an array.
It was always returning an erray, so no code can expect it

>  Extends or implements the CommandList class or CommandListInterface without updating overridden/implemented methods.

Technically you’re right, but if we’ll treat all changes as this - we can’t add return types to anywhere --> we’ll never have strict types

Since this class was previously not marked as API, we can still change its interface.
But after merging this PR, we can’t. So I suggest adding the return type now

2025-05-06 12:25 UTC, ihor-sviziev commented
@engcom-Dash, we still have not resolved discussion https://github.com/magento/magento2/pull/37901#discussion_r2063806703, let's agree on the final version before moving to review

2025-05-07 04:50 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Console/CommandList.php
> +    public function getCommands(): array
Hello @ihor-sviziev & @jissereitsma,

Let me discuss this with the internal team.

Thanks

2025-05-08 07:34 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Console/CommandList.php
> +    public function getCommands(): array
Hello @ihor-sviziev & @jissereitsma,

We got reply from the internal team, according to them adhering to BIC checks should remain the standard unless there is a highly compelling justification to deviate from it. In this instance, I don't find the justification sufficiently convincing.

2025-05-12 02:54 UTC, engcom-Hotel commented
@magento run all tests

2025-05-12 12:24 UTC, engcom-Hotel approved these changes

2025-05-12 12:31 UTC, lbajsarowicz approved these changes

2025-05-14 07:37 UTC, engcom-Dash commented
@magento run all tests

2025-05-14 11:57 UTC, engcom-Dash commented
Hello @lbajsarowicz,

Thanks for the contribution!

<h3> ✔️  QA Passed </h3>
As mentioned over here https://github.com/magento/magento2/pull/37901#issuecomment-1696902261 the changes are related to making the lib/internal/Magento/Framework/Console/CommandList.php class a Public Interface by adding the @api annotation.

Builds are failed hence moving this PR to Extended Testing

Thanks!

2025-05-14 13:08 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker

2025-05-15 07:56 UTC, engcom-Dash commented
Due to SVC failure, Updated the [JIRA AC-9408](https://jira.corp.adobe.com/browse/AC-9408) with the recent MINOR SVC failure details and asked for the approval. 

Once we get all the required approvals we will proceed further with this PR.

For now moving this PR in Pending Approval.

2025-09-10 08:15 UTC, engcom-Dash commented
Since [JIRA AC-9408](https://jira.corp.adobe.com/browse/AC-9408) has been approved, moving this PR from Pending Approval to Extended Testing.

2025-09-10 08:16 UTC, engcom-Dash commented
@magento run all tests

2025-09-10 12:26 UTC, engcom-Dash commented
@magento run all tests

2025-09-11 04:47 UTC, engcom-Dash commented
@magento run Unit Tests

2025-09-11 10:36 UTC, engcom-Dash commented
The consistent failures in Functional B2B are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

Build 1 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/8fc407449b0b6c10536a6b101a236181/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1437" height="609" alt="image" src="https://github.com/user-attachments/assets/f58485b7-551e-4e9e-ac4a-5530815b0e2a" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/b7f5b143ef3997e24fcc0bcbb7e20a54/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741
<img width="1441" height="513" alt="image" src="https://github.com/user-attachments/assets/be6a001a-ca72-4875-a1cc-66d50d72777f" />

Known Issue
AdminVerifyBehaviorOfDefaultStatusForProcessingStateTest [ACQE-8689](https://jira.corp.adobe.com/browse/ACQE-8689)
StorefrontCheckTaxAddingValidVATIdTest  [ACQE-8701](https://jira.corp.adobe.com/browse/ACQE-8701)
StorefrontCreatePurchaseOrderFromNegotiableQuoteTest  [ACQE-8645](https://jira.corp.adobe.com/browse/ACQE-8645)

The consistent failures in Functional EE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/ce1e2e73a8c596d90d859fa9c180bef5/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1450" height="694" alt="image" src="https://github.com/user-attachments/assets/9a57a764-e714-444c-9acf-bb9c5494b571" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/8f65eab18a9a27290a759f2063aba77b/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1421" height="476" alt="image" src="https://github.com/user-attachments/assets/6bfe8705-2031-4fb9-a35b-cdd501c53b4f" />

Known Issue

AdminMassOrdersReleasePendingOrderTest [ACQE-8641](https://jira.corp.adobe.com/browse/ACQE-8641)
AdminVerifyBehaviorOfDefaultStatusForProcessingStateTest [ACQE-8689](https://jira.corp.adobe.com/browse/ACQE-8689)
StorefrontCheckTaxAddingValidVATIdTest [ACQE-8701](https://jira.corp.adobe.com/browse/ACQE-8701)


The consistent failures in Functional CE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

Build1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/e34915e789786383704a3408b24d6aad/Functional/allure-report-ce/index.html#categories/d52f54183a27cd1914dd108203055fcd/75b28b3bb764b96a/
<img width="1422" height="391" alt="image" src="https://github.com/user-attachments/assets/9f405a9c-c50c-4642-af02-6866a00e7235" />


Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/296cf4bdda3d0ca7e74989d2234ca295/Functional/allure-report-ce/index.html#categories/bdbf199525818fae7a8651db9eafe741
<img width="1427" height="538" alt="image" src="https://github.com/user-attachments/assets/c6ba1262-3f6f-41ee-886c-ff1722fe62e1" />

Known Issue
AdminVerifyBehaviorOfDefaultStatusForProcessingStateTest [ACQE-8689](https://jira.corp.adobe.com/browse/ACQE-8689)
StorefrontCheckTaxAddingValidVATIdTest [ACQE-8701](https://jira.corp.adobe.com/browse/ACQE-8701)

SVC Failure 
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/afbccb62be8a8fee97544b5c80734eb2/SemanticVersionChecker/report-magento2.html
<img width="1710" height="849" alt="image" src="https://github.com/user-attachments/assets/5f0caaba-081d-49ed-81a1-22710a4a4f14" />

Build 2 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37901/5141cce77d726d2bd6683123983fe9ef/SemanticVersionChecker/report-magento2.html
<img width="1710" height="806" alt="image" src="https://github.com/user-attachments/assets/7a7a69d5-feb8-47df-9d5f-99f8f9833c41" />

SVC Jira Approved 
[JIRA AC-9408](https://jira.corp.adobe.com/browse/AC-9408)

Hence, Moving this PR to Merge In Progress

2025-11-20 13:09 UTC, lbajsarowicz commented
Any updates here?

2025-11-20 15:18 UTC, merged

2025-11-20 17:45 UTC, ihor-sviziev commented
it was finally merged! 🥳

2025-11-20 17:59 UTC, lbajsarowicz commented
@ihor-sviziev It took 5 years since I created the original PR ( https://github.com/magento/magento2/pull/29762 ).

Such a - technically - minor change.