Resolved 37820 console error in email preview
magento/magento2 pull request #37933
Opened 2023-08-29 09:47 UTC by Aditya-Prakash-Talluru

### Description (*)

Console error in Email preview in the Magento admin resolved the error
### Related Pull Requests

[#37820](https://github.com/magento/magento2/issues/37820)

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/37820

### Manual testing scenarios (*)

Login to backend (Admin)

Nav to Admin>Marketing>Email Templates>click preview
Open developer options and you can able to find a error in the console.

<img width="1431" alt="Screenshot 2023-08-29 at 3 13 08 PM" src="https://github.com/magento/magento2/assets/139533953/97f5ba02-82d5-4783-9b61-85662160b104">

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-08-29 09:48 UTC, Aditya-Prakash-Talluru commented
@magento run all tests

2025-06-27 09:16 UTC, engcom-Hotel commented
@magento run all tests

2025-06-27 12:56 UTC, engcom-Hotel requested changes
Hello @Aditya-Prakash-Talluru,

Thanks for the contribution!

Please fix the failed static tests, other tests seems flaky to me.

Thanks

2025-06-30 05:15 UTC, engcom-Dash commented
Hello @Aditya-Prakash-Talluru  I wanted to check if you are working on the static failures & automated test coverage. If not, Can I take care of them? Just let me know what works best for you.

2025-07-01 07:34 UTC, engcom-Dash commented
Hello @Aditya-Prakash-Talluru  I am taking care of the static failures. Thank you!

2025-07-01 07:56 UTC, engcom-Dash commented
@magento run all tests

2025-07-01 10:09 UTC, engcom-Dash commented
@magento run Unit Tests

2025-07-01 11:27 UTC, engcom-Dash commented
@engcom-Hotel I have fixed the failing static test cases. I feel other failing test cases are not related to this PR hence moving this PR for review.

2025-07-02 10:51 UTC, engcom-Hotel approved these changes

2025-07-03 05:57 UTC, engcom-Bravo commented
@magento run all tests

2025-07-03 11:21 UTC, engcom-Bravo commented
Hi @Aditya-Prakash-Talluru,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Login to backend (Admin)
- Nav to Admin>Marketing>Email Templates>click preview
- Open developer options and you can able to find a error in the console.



**Before:** :heavy_multiplication_x: 

<img width="1431" alt="Screenshot 2025-07-03 at 11 28 35 am" src="https://github.com/user-attachments/assets/2e7d4067-bd0d-448b-a258-4b98386fa138" />



**After:** :heavy_check_mark: 



<img width="1431" alt="Screenshot 2025-07-03 at 11 37 11 am" src="https://github.com/user-attachments/assets/3f139907-57cc-4cb8-983a-88aaeae8d405" />





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-07-04 06:26 UTC, engcom-Dash commented
@magento run all tests

2025-07-04 10:29 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Unit Tests

2025-07-07 05:15 UTC, engcom-Dash commented
The consistent Functional B2B Tests failure is known issue and Jira has been raised for the same. Other failures are inconsistent and flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37933/b1d214f89f1bfdcbcf2644d17f525932/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/fe4d69bd-c028-4197-bc28-c197f0e307e2)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37933/de344afc3921608dd31c444a62bf52d4/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/19abab89-eefe-4fe2-9a05-79e1185335cd)

Known Issue: StorefrontProductNoLongerVisibleInWishlistOnceUserUnassignedFromCompanyTest [ACQE-8287](https://jira.corp.adobe.com/browse/ACQE-8287)

Hence moving this PR in Merge In Progress.

2025-08-04 06:11 UTC, merged