Store ID is not updated w/ address renderer w/ orders
magento/magento2 pull request #37932
Opened 2023-08-29 09:09 UTC by thomas-kl1

### Description (*)

\Magento\Sales\Model\Order\Address\Renderer::format allows to format order address. Internally, the method retrieve the order store ID and update the current store ID. This produces strange behavior if used in a context with a different store as the current store is not set to its previous value at the end of the execution of the method.
The class \Magento\Customer\Model\Address\Config is used within the format method in order to resolve the address format to use accordingly to the order store. This class allows to set the store context thanks to \Magento\Customer\Model\Address\Config::setStore. However this method was not called. Here we call it and reverse the value to its original state at the end of the execution, in order to prevent weird behavior.
With this solution, the current store in the manager is not altered and the global context is preserved.
Previously, when the method \Magento\Customer\Model\Address\Config::getFormatByCode was called, by the method format, the store was resolved at the first call : 

-> \Magento\Customer\Model\Address\Config::getFormatByCode
--> \Magento\Customer\Model\Address\Config::getFormats
---> \Magento\Customer\Model\Address\Config::getStore

```php
public function getStore()
{
    if ($this->_store === null) {
        $this->_store = $this->_storeManager->getStore();
    }
    return $this->_store;
}
```

I guess that's why there was a $this->storeManager->setStore($orderStore); in \Magento\Sales\Model\Order\Address\Renderer::format. 
This MR aims to remove the usage of $this->storeManager->setStore which may produce indesirable side-effects and use proper method available in the \Magento\Customer\Model\Address\Config API.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-08-29 09:37 UTC, thomas-kl1 commented
@magento run all tests

2023-08-29 12:38 UTC, thomas-kl1 commented
@magento run all tests

2023-08-30 16:35 UTC, 93kamikaze commented
@magento run all tests

2023-09-01 08:07 UTC, thomas-kl1 commented
Unit tests needs to be reworked as they don't test expected results but internal implementation 🤡

2024-01-19 09:11 UTC, thomas-kl1 commented
@magento run all tests

2024-01-26 18:30 UTC, andrewbess requested changes
Hello @thomas-kl1 
Thank you for your contribution
Please check [this guide](https://developer.adobe.com/commerce/contributor/guides/code-contributions/). We need to avoid removing|changing protected properties in the @api classes.
This is main reason of the tests failures.
Could you please check failures, documentation and fix your PR?
Thank you in advance.

2024-01-28 08:16 UTC, andrewbess requested changes
Hello @thomas-kl1 
Thank you for your fast reaction and fixes.
However, let's not touch the class properties and the constructor PHPDocs.
Let's try ti fix only format method.
Also, please check my comment for getLocaleByStoreId method PHPDocs.
Thank you in advance.

2024-01-28 08:16 UTC, andrewbess commented on app/code/Magento/Sales/Model/Order/Address/Renderer.php
> -     * @return string
Looks like it is unnecessary removing
Please don't remove PHPDocs like this.

2024-02-02 05:32 UTC, engcom-Echo commented
@magento create issue

2024-02-07 05:58 UTC, engcom-Echo commented
@magento run all tests

2024-02-08 07:03 UTC, engcom-Echo commented
@magento run all tests

2024-02-12 05:52 UTC, engcom-Echo commented
@magento run all tests

2024-02-12 07:45 UTC, engcom-Echo commented
@magento run all tests

2024-02-12 11:43 UTC, engcom-Echo commented
@thomas-kl1 Can you please have look on build failure of [Integration Tests](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37932/9142b459e91aeb74533c7fa8a4b19ade/Integration/console-error-logs.html) seems to be caused by PR changes.

2024-02-12 18:35 UTC, thomas-kl1 commented
@magento run all tests

2024-02-12 18:36 UTC, thomas-kl1 commented
@magento run all tests

2024-02-12 21:58 UTC, thomas-kl1 commented
\Magento\Customer\Model\Metadata\AddressMetadata::getAttributeMetadata
`$attribute = $this->attributeMetadataDataProvider->getAttribute(AddressMetadataInterface::ENTITY_TYPE_ADDRESS, $attributeCode);`

\Magento\Customer\Model\AttributeMetadataDataProvider::getAttribute
`return $this->eavConfig->getAttribute($entityType, $attributeCode);`

\Magento\Eav\Model\Config::initSystemAttributes
```
$attributeCollection = $this->_universalFactory->create($entityType->getEntityAttributeCollection());
$websiteId = $attributeCollection instanceof Collection ? $this->getWebsiteId($attributeCollection) : 0;
```
        

\Magento\Eav\Model\ResourceModel\Attribute\Collection::getWebsite
```
if ($this->_website === null) {
    $this->_website = $this->_storeManager->getStore()->getWebsite();
}
return $this->_website;
```

So we should override the getWebsite method in the following class:
\Magento\Customer\Model\ResourceModel\Address\Attribute\Collection
and use the result of \Magento\Customer\Model\Address\Config::getStore instead

2024-02-12 22:14 UTC, thomas-kl1 commented
@magento run all tests

2024-02-12 22:53 UTC, thomas-kl1 commented
@magento run all tests

2024-02-13 09:01 UTC, thomas-kl1 commented
@magento run all tests

2024-02-13 10:16 UTC, thomas-kl1 commented
@magento run all tests

2024-02-13 11:53 UTC, thomas-kl1 commented
@magento run all tests

2024-02-13 21:43 UTC, thomas-kl1 commented
@magento run all tests

2024-02-13 23:29 UTC, thomas-kl1 commented
@magento run all tests

2024-02-13 23:35 UTC, thomas-kl1 commented
@magento run all tests

2024-02-13 23:36 UTC, thomas-kl1 commented
I'll squash the commits tomorrow, right now I'm on my phone 😅

2024-02-14 09:49 UTC, thomas-kl1 commented
@magento run all tests

2024-02-14 10:54 UTC, thomas-kl1 commented
@magento run all tests

2024-02-26 07:38 UTC, engcom-Echo commented
@magento run all tests

2024-02-26 10:01 UTC, engcom-Echo commented
@magento run all tests

2024-02-27 12:03 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2024-02-27 13:12 UTC, engcom-Hotel approved these changes

2024-02-27 13:46 UTC, andrewbess approved these changes
Hello @thomas-kl1 
Thank you for your contribution.
Fixes look nice for me
Approved

2024-02-27 13:47 UTC, andrewbess commented
@magento run Functional Tests B2B

2024-02-28 08:03 UTC, andrewbess commented
@magento run Functional Tests B2B

2024-02-28 10:05 UTC, andrewbess commented
As for me the failure B2B MFTF tests are not related on these changes.

2024-03-04 12:00 UTC, engcom-Echo commented
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**
 We have followed steps from [comment](https://github.com/magento/magento2/issues/38412#issuecomment-1931577790)

**Before:** :heavy_multiplication_x: 
<img width="933" alt="Screenshot 2024-03-04 at 5 18 28 PM" src="https://github.com/magento/magento2/assets/51681435/834d6ef2-f7d0-4cfb-89d2-c8d10f837a82">

**After:** :heavy_check_mark:  
<img width="1038" alt="Screenshot 2024-03-04 at 5 20 12 PM" src="https://github.com/magento/magento2/assets/51681435/10085a7d-52ba-4574-aafe-207be1d37a78">

Builds are failed. Hence, moving this PR to **Extended Testing.**

2024-03-04 12:05 UTC, engcom-Echo commented
@magento run Functional Tests B2B

2024-03-05 03:08 UTC, engcom-Echo commented
@magento run all tests

2024-03-05 05:21 UTC, engcom-Echo commented
@magento run Integration Tests,Functional Tests B2B,WebAPI Tests

2024-03-05 07:17 UTC, engcom-Echo commented
**Integration Tests** failure are not related to PR changes is known flaky failure.
**Functional Tests B2B** failure are different on last two run on same commit.
Run1
<img width="1440" alt="Screenshot 2024-03-05 at 12 45 30 PM" src="https://github.com/magento/magento2/assets/51681435/ca7b7f96-2d89-487d-9869-2be0beed7ff9">

Run2
<img width="1427" alt="Screenshot 2024-03-05 at 12 45 34 PM" src="https://github.com/magento/magento2/assets/51681435/f35ee293-e79b-4a2e-996f-1bbd98f975cf">

Hence Moving it to `Merge In Progress`

2024-04-09 08:58 UTC, thomas-kl1 commented
any update @engcom-Echo when it's going to be merged?

2024-05-08 04:41 UTC, engcom-Echo commented
> any update @engcom-Echo when it's going to be merged?

Its already in the process of merging we will update once it it mereged.

2024-05-16 19:44 UTC, merged