Allowed Countries does not work correctly
magento/magento2 pull request #38182
Opened 2023-11-15 00:08 UTC by zhovnirigor

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38181

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-11-21 10:44 UTC, zhovnirigor commented
@magento run all tests

2023-11-21 13:19 UTC, zhovnirigor commented
@magento run all tests

2023-11-21 15:18 UTC, zhovnirigor commented
@magento run all tests

2023-11-22 00:29 UTC, zhovnirigor commented
@magento run all tests

2024-09-03 10:33 UTC, Axel29 commented
The fix doesn't seem to work for me on Magento 2.4.5-p8.

From what I can see, the address has the wrong store ID (the one from the customer instead of the current store ID), which makes the configuration fetched with wrong values.

I guess it has something to do with the `\Magento\Customer\Model\ResourceModel\AddressRepository::save` method which does this: `$addressModel->setStoreId($customerModel->getStoreId());` where the customer is being loaded and thus his associated store is fetched.

2025-10-27 08:15 UTC, engcom-Hotel commented
Hello @zhovnirigor,

Please resolve the conflicts and also please refer to this https://github.com/magento/magento2/pull/38182#issuecomment-2326175517.

Meanwhile moving this PR on hold.

Thank you

2025-11-11 06:44 UTC, engcom-Hotel commented
Hello @zhovnirigor,

Gentle reminder to resolve the conflicts of this PR so that we can proceed further with this.

Thank you

2025-12-02 17:45 UTC, engcom-Hotel commented
@magento run all tests

2025-12-03 11:25 UTC, engcom-Hotel requested changes
Hello @zhovnirigor,

Thank you for the collaboration!

Please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done#definition-of-done-1) and also look into the below review comments.

2025-12-03 11:25 UTC, engcom-Hotel commented on app/code/Magento/Customer/Model/Address/Validator/Country.php
>          ?Escaper $escaper = null
```suggestion

?Escaper $escaper = null
StoreManagerInterface $storeManager = null,
```

2025-12-03 11:25 UTC, engcom-Hotel commented on app/code/Magento/Customer/Model/Address/Validator/Country.php
> +        $this->storeManager = $storeManager;
Use ObjectManager to initialise the object to maintain backward compatibility.

2025-12-03 11:25 UTC, engcom-Hotel commented on app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/CountryWithWebsites.php
> -                if ($customerId) {
The removed code checked for parent_id parameter and loaded customer-specific website. This may have been intentional for admin address editing. Need to verify if this change affects admin panel functionality.

2026-01-12 13:12 UTC, engcom-Hotel commented
Hello @zhovnirigor,

We have noticed that this PR has not been updated for a while. Therefore, we are closing it for now.

Please let us know when you are ready to work on it again, and we will be happy to reopen the PR.

Thank you for your valuable contribution!

2026-01-12 13:12 UTC, closed without merging