WP: Fix issue #31396
magento/magento2 pull request #38239
Opened 2023-12-01 14:13 UTC by thomas-kl1

### Description (*)
Currently the aliases are useless and have no meaningful usage in codebase.

### Related Pull Requests
- https://github.com/magento/magento2/pull/37682

### Fixed Issues (if relevant)
1. Fixes magento/magento2#31396

### Manual testing scenarios (*)

1. Add a patch with aliases
2. None of the aliases must exists in db
3. Run setup:upgrade
4. The patch and its aliases are added to patch_list table

1. Add a patch with aliases
2. Any of its aliases must exists in db
3. Run setup:upgrade
4. The patch is not ran because it's already applied previously by one of its aliases

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-12-01 14:17 UTC, thomas-kl1 commented
@magento run all tests

2023-12-01 17:04 UTC, thomas-kl1 commented
@magento run all tests

2023-12-01 19:43 UTC, thomas-kl1 commented
@magento run all tests

2023-12-06 13:57 UTC, thomas-kl1 commented
@magento run all tests

2023-12-06 20:44 UTC, thomas-kl1 commented
Functional tests failures are not related to the PR.
Unit test must be updated accordingly.

2023-12-06 20:55 UTC, thomas-kl1 commented
@magento run all tests

2023-12-06 23:22 UTC, thomas-kl1 commented
@magento run all tests

2024-01-18 13:30 UTC, thomas-kl1 commented
@magento run all tests

2024-04-09 08:59 UTC, thomas-kl1 commented
@magento run all tests

2024-04-26 10:01 UTC, thomas-kl1 commented
@magento run all tests

2025-05-06 12:38 UTC, thomas-kl1 commented
@magento run all tests

2025-06-30 08:58 UTC, engcom-Hotel reviewed
Hello @thomas-kl1,

Thanks for the contribution!

In this PR, you have attached this [PR](https://github.com/magento/magento2/pull/37682) as a related pull request. As the related pull request is closed due [this](https://github.com/magento/magento2/pull/37682#issuecomment-1737240535), we have closed the same. 

Can we remove the above PR from this PR, so that we can move forward with this PR? Please update us on this, meanwhile we are moving this PR `On Hold`.

Thanks

2025-06-30 11:58 UTC, thomas-kl1 commented
@engcom-Hotel I've updated this PR description and removed the reference.

2025-07-01 02:18 UTC, engcom-Hotel commented
@magento run all tests

2025-07-01 08:40 UTC, engcom-Hotel requested changes
Hello @thomas-kl1,

Thanks for making the changes. Please fix the failed automated tests.

Thanks

2025-07-01 08:48 UTC, thomas-kl1 commented
@engcom-Hotel 

Regarding static test failures, it's related to the copyright header change, I'll check, could you give the new copyright to apply please?
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38239/079f4563d120ab5795fb65006c654d26/Statics/console-error-logs.html

Units tests failure are not related to this PR and seems related to RMA changes (not in scope of this PR):
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38239/5da9f12d3970de433b743d636689530d/Unit/console-error-logs.html

Webapi tests, I dont see how it's related to this PR change 🤔 

Functional tests, I dont see how it's related to this PR change 🤔

2025-07-01 20:18 UTC, thomas-kl1 commented
@magento run all tests

2025-07-02 10:49 UTC, engcom-Hotel approved these changes

2025-07-07 11:11 UTC, engcom-Charlie commented
Hi @thomas-kl1,

Thank you for your contribution!

I have followed below steps in order to reproduce the test the PR.

### :heavy_check_mark: QA Passed

**_Before PR_**  :heavy_multiplication_x: 
1. Create a patch called 'ExampleDataPatch' with no aliases
```
class ExampleDataPatch implements DataPatchInterface
{
    /**
     * @var ModuleDataSetupInterface
     */
    private $moduleDataSetup;


    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(
        ModuleDataSetupInterface $moduleDataSetup,
        LoggerInterface $logger
    ) {
        $this->moduleDataSetup = $moduleDataSetup;
        $this->logger = $logger;
    }
    
    public function apply()
    {
        $this->moduleDataSetup->startSetup();
        $this->logger->info('ExampleSchemaPatch: Apply method executed.');
        $this->moduleDataSetup->endSetup();
    }
    
    public static function getDependencies()
    {
        return [];
    }
    
    public function getAliases()
    {
        return [];
    }
}
```
3. Run `bin/magento setup:upgrade`, patch ExampleDataPatch gets applied and 'ExampleDataPatch' is added to the patch_list table
5. Rename patch ExampleDataPatch file and class name to 'ChangedExampleDataPatch'
6. Add 'ExampleDataPatch' to the aliases 
```
public function getAliases()
    {
        return [
            ExampleDataPatch::Class
        ];
    }
```
7. Run `bin/magento setup:upgrade` again, patch ExampleDataPatch gets applied again verified it from log file and 'ChangedExampleDataPatch' is added to the patch_list table
<img width="722" alt="image" src="https://github.com/user-attachments/assets/6fd7683b-8b6f-41b7-bf4c-cc86e5b9dc81" />
<img width="850" alt="image" src="https://github.com/user-attachments/assets/7065a1c5-ed16-48e5-ab7a-f169eed8fd66" />



**_After PR Changes_** :heavy_check_mark: 

1. Followed step 1-6 as above
2. Run `bin/magento setup:upgrade` again, patch ExampleDataPatch didn't get applied again verified from log file and `ChangedExampleDataPatch` is getting added to the `patch_list` table. 
<img width="755" alt="image" src="https://github.com/user-attachments/assets/fe4f0e8e-beac-42ec-b589-62e1f5c11fe0" />
<img width="770" alt="image" src="https://github.com/user-attachments/assets/0a745e1e-eb28-46dc-98df-3b2237a54e4e" />

As the build is failing, moving this PR to Extended Testing.

2025-07-07 11:12 UTC, engcom-Charlie commented
@magento run all tests

2025-07-08 04:39 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2025-07-08 08:52 UTC, thomas-kl1 commented
@engcom-Charlie the integration tests failures are not related to these changes.

2025-07-09 05:12 UTC, engcom-Charlie commented
@magento run all tests

2025-07-10 04:18 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

2025-07-10 06:44 UTC, engcom-Charlie commented
The Functional B2B in recent 2 builds have one common failure and its a known issue. The rest are neither part of PR nor affected by PR changes.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38239/965d2598a51e2d0368da7fff85e5e50e/Functional/allure-report-b2b/index.html#categories

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/156640f6-be5d-44d0-b888-8740d4a1e635" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38239/b68be97fd9a9ffd4638e21cddcf4f033/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/9a053d1c29d42d2b/

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/7d010153-44dd-4dcb-a20e-623cd34d95c7" />

**Known Issue:**
[ACQE-8287](https://jira.corp.adobe.com/browse/ACQE-8287): StorefrontProductNoLongerVisibleInWishlistOnceUserUnassignedFromCompanyTest

The Functional CE failures are not consistent in recent 2 builds. The rest are neither part of PR nor affected by PR changes, seems to be flaky. Hence moving this PR to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38239/800b0099885f5877ec1d695c6f0fb73f/Functional/allure-report-ce/index.html#categories/1a0b192d5a64d4dd09e28ae8fc5f85a9/f5feee72e4f291fc/

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/6396572c-ec53-49e5-aa4f-bd5682991d27" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38239/3e81af210aa85ebe41370fa39b7dcdb7/Functional/allure-report-ce/index.html#categories

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/be6dbf15-6152-4532-a5c0-c301b37e6b34" />

2025-08-04 06:11 UTC, merged