#36947 Fixed timezone of order_date field returned from graphql customerOrders query
magento/magento2 pull request #38264
Opened 2023-12-10 18:12 UTC by Bartlomiejsz

### Description (*)

The PR changes `order_date` field in `customerOrders` query to return date using store timezone instead of UTC.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36947

### Manual testing scenarios (*)

1. Configure your store with a timezone different from +0
2. Create a Shipment with a comment
3. Verify the comment created_at in the normal view phtml in the website
4. Call customer Orders query and check created_at field from shipment comment

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-12-10 18:21 UTC, Bartlomiejsz commented
@magento run all tests

2024-12-12 07:00 UTC, engcom-Hotel reviewed
Hello @Bartlomiejsz,

Kindly resolve the PR conflicts so we can proceed with further processing. In the meantime, we are moving this PR to "On Hold."

Thanks

2024-12-16 11:57 UTC, engcom-Hotel commented
Hello @Bartlomiejsz,

Have you had a chance to look into this https://github.com/magento/magento2/pull/38264#pullrequestreview-2497966812?

Thanks

2024-12-16 13:09 UTC, Bartlomiejsz commented
Hello @engcom-Hotel,

Not yet, I will take care of it today or tomorrow at the latest

Best regards

2024-12-16 20:23 UTC, Bartlomiejsz commented
Hello @engcom-Hotel, conflicts resolved

2024-12-17 06:18 UTC, engcom-Hotel commented
@magento run all tests

2024-12-17 09:20 UTC, engcom-Hotel requested changes
Hello @Bartlomiejsz,

Thanks for the contribution!

Please fix the failed tests, specifically webAPI test and static test. It seem they are failing due to PR changes.

Also please cover the changes with some automated tests in accordance to [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

2024-12-17 10:23 UTC, Bartlomiejsz commented
@magento run all tests

2024-12-17 14:53 UTC, Bartlomiejsz commented
@magento run all tests

2024-12-18 09:42 UTC, engcom-Hotel requested changes
Hello @Bartlomiejsz,

Please fix the static test failures and take a look into my review comments below.

Thanks

2024-12-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/SalesGraphQl/Model/Formatter/Order.php
> +    private TimezoneInterface $timezone;
Add doc-block as follows:

```suggestion
/**
     * @var TimezoneInterface $timezone
     */
    private TimezoneInterface $timezone;
```

2024-12-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/SalesGraphQl/Model/Resolver/CreditMemo/CreditMemoComments.php
> +    private TimezoneInterface $timezone;
Add here as well

2024-12-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/SalesGraphQl/Model/Resolver/Invoices.php
> +    private TimezoneInterface $timezone;
Same here

2024-12-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/SalesGraphQl/Model/Resolver/Shipments.php
> +    private TimezoneInterface $timezone;
Same here

2024-12-18 09:43 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Functional Tests B2B

2024-12-19 06:58 UTC, engcom-Dash commented
@magento run all tests

2024-12-19 11:39 UTC, engcom-Dash commented
@magento run all tests

2024-12-19 13:10 UTC, engcom-Dash commented
> Hello @Bartlomiejsz,
> 
> Please fix the static test failures and take a look into my review comments below.
> 
> Thanks

@engcom-Hotel: I have fixed it. Moving it back to pending review.

cc: @Bartlomiejsz

2024-12-20 11:18 UTC, engcom-Hotel approved these changes

2024-12-23 04:51 UTC, engcom-Bravo commented
@magento run all tests

2024-12-23 07:51 UTC, engcom-Bravo commented
Hi @Bartlomiejsz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Configure your store with a timezone different from +0
- Create a Shipment with a comment
- Verify the comment created_at in the normal view phtml in the website
- Call customer Orders query and check created_at field from shipment comment


**Before:** :heavy_multiplication_x: 

<img width="1418" alt="Screenshot 2024-12-23 at 10 03 37 am" src="https://github.com/user-attachments/assets/bd274af3-cb0f-4408-bff5-25530ca398d3" />



<img width="1418" alt="Screenshot 2024-12-23 at 10 03 17 am" src="https://github.com/user-attachments/assets/5fafcf08-16d7-4716-bafc-07f15eaf6960" />





**After:** :heavy_check_mark: 

<img width="1418" alt="Screenshot 2024-12-23 at 10 03 37 am" src="https://github.com/user-attachments/assets/bd274af3-cb0f-4408-bff5-25530ca398d3" />

<img width="1418" alt="Screenshot 2024-12-23 at 10 23 08 am" src="https://github.com/user-attachments/assets/9a51f232-641b-4af4-9020-6345a4757cb9" />


Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2024-12-23 09:07 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2024-12-23 12:23 UTC, engcom-Dash commented
@magento run Functional Tests CE

2024-12-23 14:52 UTC, engcom-Dash commented
The Functional B2B test failures seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

EndToEndB2CLoggedInUserTestCest: This failure can also be seen in other PRs ([see here](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39004/4d1c3d53f61d35b83e974b6a26f7633f/Functional/allure-report-b2b/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/e0a5ba7e9bc3639b/))

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38264/72d60e414b51069b100a672815652a22/Functional/allure-report-b2b/index.html#categories/55e0aa33671c7658b2cdf6bcb3eb80e1/ea01e971fa54cbc1/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/a7d09590-c386-477f-90ff-6123a5cbaa45" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38264/bad027bfbf0c5af8ce66245974aa7dd6/Functional/allure-report-b2b/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/af11cf8e146f160f/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/63a67ae2-f160-44d6-ac77-3d1268e11727" />

2025-01-07 15:54 UTC, merged