Duplicate cache fpc for same page with same query
magento/magento2 pull request #38270
Opened 2023-12-12 03:35 UTC by rogerdz

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38269

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-12-12 03:35 UTC, rogerdz commented
@magento run all tests

2023-12-12 03:47 UTC, rogerdz commented
@magento run all tests

2023-12-12 05:47 UTC, rogerdz commented
@magento run all tests

2023-12-12 05:49 UTC, rogerdz commented
@magento run all tests

2023-12-12 16:06 UTC, rogerdz commented
@magento run Integration Tests, WebAPI Tests

2024-08-21 11:56 UTC, engcom-Hotel commented
@magento run all tests

2024-08-22 10:19 UTC, engcom-Hotel requested changes
Hello @rogerdz,

Thanks for the contribution!

Please check the build failures, it seems they are failing due to code changes.

Thanks

2024-08-22 16:00 UTC, rogerdz commented
@magento run all tests

2024-08-23 01:57 UTC, rogerdz commented
@magento run Static Tests

2024-08-23 07:00 UTC, rogerdz commented
@magento run Static Tests

2024-08-23 08:23 UTC, rogerdz commented
@magento run all tests

2024-08-23 15:04 UTC, rogerdz commented
@magento run all tests

2024-08-26 01:28 UTC, rogerdz commented
@magento run Unit Tests, Static Tests, Magento Health Index, Integration Tests, Functional Tests EE, Functional Tests B2B

2024-08-26 01:40 UTC, rogerdz commented
@magento run all tests

2024-08-26 05:15 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Magento Health Index

2024-09-02 09:42 UTC, engcom-Charlie commented
@magento run all tests

2024-09-02 11:43 UTC, engcom-Charlie commented
Hi @rogerdz,

Thank you for working on Unit test failure. In order to move further on this PR, build should be green; can you please have a look into Magento Health Index failure.

2024-09-05 07:25 UTC, rogerdz commented
@magento run all tests

2024-09-05 09:43 UTC, rogerdz commented
@magento run all tests

2024-09-05 10:05 UTC, rogerdz commented
@magento run all tests

2024-09-05 15:17 UTC, rogerdz commented
Hi @engcom-Charlie, 
I fixed all test, Functional Tests fail seem not related my code

2024-09-09 05:00 UTC, engcom-Charlie commented
@magento run all tests

2024-09-09 09:16 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

2024-09-10 05:54 UTC, engcom-Hotel commented
@magento run all tests

2024-09-10 10:39 UTC, engcom-Hotel requested changes
Hello @rogerdz,

The changes seems good to me but please fix the below review comments.

Thanks

2024-09-10 10:39 UTC, engcom-Hotel commented on app/code/Magento/PageCache/Model/App/Request/Http/IdentifierForSave.php
> +    private function reconstructUrl($url)
```suggestion
    private function reconstructUrl(string $url): array
```

2024-09-10 10:39 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/App/PageCache/Identifier.php
> +    private function reconstructUrl($url)
```suggestion
    private function reconstructUrl(string $url): array
```

2024-09-10 10:39 UTC, engcom-Hotel commented on app/code/Magento/PageCache/Test/Unit/Model/App/Request/Http/IdentifierForSaveTest.php
> +    public function testGetValueWithQuery(): void
```suggestion
    /**
 * Test get identifier for save value with query parameters.
 *
 * @return void
 */
    public function testGetValueWithQuery(): void
```

2024-09-10 10:39 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/App/Test/Unit/PageCache/IdentifierTest.php
> +
```suggestion
/**
 * Test get identifier for save value with query parameters.
 *
 * @return void
 */
```

2024-09-11 16:50 UTC, rogerdz commented
@magento run all tests

2024-09-12 05:03 UTC, rogerdz commented
@magento run all tests

2024-09-12 07:44 UTC, engcom-Hotel approved these changes

2024-09-13 08:39 UTC, engcom-Bravo commented
@magento run all tests

2024-09-13 10:57 UTC, engcom-Bravo commented
Hi @rogerdz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**


As per the Description.


**Before:** :heavy_multiplication_x: 

<img width="1437" alt="Screenshot 2024-09-13 at 14 00 06" src="https://github.com/user-attachments/assets/68d6609d-c958-4057-9a1a-c46a110dc39b">


**After:** :heavy_check_mark: 


<img width="1437" alt="Screenshot 2024-09-13 at 14 16 31" src="https://github.com/user-attachments/assets/ae226583-a176-4c08-9eb3-b882f9279b08">



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

2024-09-13 11:37 UTC, engcom-Charlie commented
@magento run all tests

2024-09-16 06:29 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE

2024-09-16 08:40 UTC, engcom-Charlie commented
The Functional B2B test failures are not consistent in recent 2 builds. They are neither part of PR now failing because of PR changes. Seems to be flaky, hence moving it to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/f751c6d7e59f68f664f9240db0474fcf/Functional/allure-report-b2b/index.html#categories/16b25a50b4a8b68f5548cdba82ebd5f8/65d76e88635b8175/

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/9bb4b8f5-bc1a-43fd-8776-a61a50091d85">


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/c84d5d0c039fd077a616edb568dd271b/Functional/allure-report-b2b/index.html#categories

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/87dbff3b-2bd8-4bab-be93-0df763cef4b5">

2024-10-30 05:01 UTC, engcom-Charlie commented
We have seen PAT failures in mainline PR after merging this PR into that. Hence for further analysis; for now moving this PR to Extended testing.

2024-11-25 11:39 UTC, engcom-Dash commented
@magento run all tests

2024-11-25 16:20 UTC, engcom-Dash commented
@magento run Static Tests, Functional Tests CE, Functional Tests B2B, Functional Tests EE

2024-11-26 06:58 UTC, engcom-Dash commented
The Functional B2B and CE test failures seem flaky and some of these failures are known issues. They are neither part of PR now failing because of PR changes. Hence moving it to Merge in Progress.

**Known Issues:**
MultiShippingWithCreationNewCustomerAndAddressesDuringCheckoutTest: [ACQE-7229](https://jira.corp.adobe.com/browse/ACQE-7229)
StorefrontReuseCouponCodeAfterOrderCanceledTest: [ACQE-7230](https://jira.corp.adobe.com/browse/ACQE-7230)
VerifyDefaultWYSIWYGToolbarOnProductTest: [ACQE-7227](https://jira.corp.adobe.com/browse/ACQE-7227)

**Functional Tests B2B** 
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/95b9984bc468ba92a21b2e99d9e1191e/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1787" alt="image" src="https://github.com/user-attachments/assets/76146c8e-d2be-45fe-964e-33e25c665e38">

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/439533c23bc0fa30bcd92ba6c99a9194/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/bf19acc6-c1b9-44eb-8fe7-99869c0838ce">


**Functional Tests CE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/4a790f66b688e1fb03a7fe28cdca61a9/Functional/allure-report-ce/index.html#categories/6d7e37752c3cc83cb3d2063131f608bb/190a9b2622ef3f4/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/416c1c5d-6935-4660-8b2e-903109143655">

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/dc0707fb0b4f81610a28b9acfd370cfe/Functional/allure-report-ce/index.html#categories/6d7e37752c3cc83cb3d2063131f608bb/5ba8ed3be74fdf64/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/d06e2f10-7da9-426c-9923-59fe8c79f733">

2025-01-07 07:50 UTC, engcom-Dash commented
Moving back to the changes requested, as there are conflicts in the files

2025-01-07 11:12 UTC, engcom-Dash commented
Hello @rogerdz,

Thanks for the contributions!

There are conflicts in the files. Could you please take a look and resolve them? Meanwhile, I am putting it on hold. Once the conflicts are resolved, we will proceed further.

Thanks again!

2025-02-10 10:56 UTC, engcom-Charlie commented
Hi @rogerdz,

Did you get a chance to look into the conflicts as mentioned [here](https://github.com/magento/magento2/pull/38270#issuecomment-2575021371). Currently, we are closing this PR, once its done please feel free to reopen.

Thank you!

2025-03-05 04:00 UTC, rogerdz commented
@magento run all tests

2025-03-05 04:01 UTC, rogerdz commented
Hi @engcom-Charlie

2025-03-05 13:33 UTC, engcom-Charlie commented
@magento run all tests

2025-03-06 10:45 UTC, engcom-Charlie commented
@magento run all tests

2025-03-07 07:23 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2025-03-10 09:54 UTC, engcom-Charlie commented
Hi @rogerdz,

The addressed [issue](https://github.com/magento/magento2/issues/38269) in this PR seems to be not exists anymore. 

The issue is not reproducible after trying below steps as mentioned in description in Magento2 repository.

1. Install fresh Magento **`2.4-develop`**
2. Install Sample data
3. Check FPC is set in magento instance
4. Enable developer mode
5. Clear the cache.
6. Sent below CURL request one after other, all gave the same result in magento 2 repository

- http://magento.local/gear/bags.html?activity=20
- http://magento.local/gear/bags.html?activity=20&style_bags=28
- http://magento.local/gear/bags.html?activity=20&performance_fabric=1&style_bags=28

All above URLs giving HIT. As, the issue is no more exits now, hence closing this PR for now. Please feel free to reopen it for any further updates.

<img width="1440" alt="Screenshot 2025-03-10 at 3 19 20 PM" src="https://github.com/user-attachments/assets/38cfd9e9-d8f2-4de5-a415-8255210edd4d" />

2025-03-10 14:55 UTC, rogerdz commented
Hi @engcom-Charlie ,
Issue still reproducible in my local 
![image](https://github.com/user-attachments/assets/b26023f3-8116-47f1-b961-87e62535a1c6)
Your test is not correct, please check https://github.com/magento/magento2/issues/38269#issuecomment-1862568163

2025-03-11 11:25 UTC, engcom-Charlie commented
> Hi @rogerdz,
> 
> The addressed [issue](https://github.com/magento/magento2/issues/38269) in this PR seems to be not exists anymore.
> 
> The issue is not reproducible after trying below steps as mentioned in description in Magento2 repository.
> 
> 1. Install fresh Magento **`2.4-develop`**
> 2. Install Sample data
> 3. Check FPC is set in magento instance
> 4. Enable developer mode
> 5. Clear the cache.
> 6. Sent below CURL request one after other, all gave the same result in magento 2 repository
> 
> * http://magento.local/gear/bags.html?activity=20
> * http://magento.local/gear/bags.html?activity=20&style_bags=28
> * http://magento.local/gear/bags.html?activity=20&performance_fabric=1&style_bags=28
> 
> All above URLs giving HIT. As, the issue is no more exits now, hence closing this PR for now. Please feel free to reopen it for any further updates.
> 
> <img alt="Screenshot 2025-03-10 at 3 19 20 PM" width="1440" src="https://private-user-images.githubusercontent.com/51680850/420852718-38cfd9e9-d8f2-4de5-a415-8255210edd4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2OTE4NTgsIm5iZiI6MTc0MTY5MTU1OCwicGF0aCI6Ii81MTY4MDg1MC80MjA4NTI3MTgtMzhjZmQ5ZTktZDhmMi00ZGU1LWE0MTUtODI1NTIxMGVkZDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzExVDExMTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDdlMTk1ODcxOTJkMGRjNzJhNTU4ZjQ5NzA4ZGZmMzAzMzcyNzVhZDllODNhYzZjZDJjOWU5ODJhZTJiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y4FQ3IfRmbiEjt46isWRK-ulPEK8kS3dl67jSxGcDvg">

It seems that I have tried to reproduce the issue with PR code itself hence got this result.

The issue is reproducible on Magento2 repository and working fine on PR instance.

### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento 2.4-develop
- Install Sample data

**Steps to reproduce**
- Check FPC is set in magento instance
- Enable developer mode
- Clear the cache.


**Before:** :heavy_multiplication_x: 
Result on below CURL requests on magento 2.4-develop
```
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: MISS
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: HIT
curl -I --location-trusted 'http://magento.local/gear/bags.html?style_bags=24&activity=8' | grep -i X-Magento-Cache-Debug: MISS
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24&' | grep -i X-Magento-Cache-Debug: MISS
```


<img width="1343" alt="Screenshot 2025-03-11 at 4 25 39 PM" src="https://github.com/user-attachments/assets/7421603f-e238-414b-a9c1-19f5508505db" />




**After:** :heavy_check_mark: 
```
Result on below CURL requests on PR branch
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: MISS
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: HIT
curl -I --location-trusted 'http://magento.local/gear/bags.html?style_bags=24&activity=8' | grep -i X-Magento-Cache-Debug: HIT
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24&' | grep -i X-Magento-Cache-Debug: HIT
```


<img width="1267" alt="Screenshot 2025-03-11 at 4 50 54 PM" src="https://github.com/user-attachments/assets/ca0601b8-57bf-4376-b87a-2ae98e8c3e94" />

The build is successful. Hence, moving this PR to **Merge in Progress**.

<img width="914" alt="image" src="https://github.com/user-attachments/assets/1fbf00a6-f63c-4197-bb2e-a0d40f733d6d" />


Thanks.

2025-04-25 14:52 UTC, merged