Internal Server Error in /V1/order/{orderId}/ship API Endpoint
magento/magento2 pull request #38282
Opened 2023-12-13 17:20 UTC by rogerdz

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35931

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2023-12-13 17:20 UTC, rogerdz commented
@magento run all tests

2025-06-10 03:07 UTC, engcom-Hotel commented
@magento run all tests

2025-06-10 07:30 UTC, engcom-Hotel requested changes
Hello @rogerdz,

Thanks for the contribution!

Please look into the failed tests it seems multiple tests are failing due to this change.

Thanks

2025-06-10 09:27 UTC, rogerdz commented
@magento run all tests

2025-06-10 16:20 UTC, rogerdz commented
@magento run all tests

2025-06-11 03:54 UTC, rogerdz commented
@magento run all tests

2025-07-28 08:57 UTC, engcom-Dash commented
@magento run all tests

2025-07-31 07:13 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2025-07-31 13:32 UTC, engcom-Dash commented
@engcom-Hotel I have verified the failing functional Test cases are not because of this PR changes. They are inconsistent and seems to be flaky. Also the integration failures observed on the other PRs too.

[B2B Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/cb11bc844bf0e408499d45e3fd89a1c2/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d) [B2B Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/2997b5ef7d59f91606238da6f0896ab3/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d)

[CE Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/729c0d150abd8546da2712455feee3ce/Functional/allure-report-ce/index.html#categories/bdbf199525818fae7a8651db9eafe741) [CE Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/12e0a25a4eb36ec7462cd8ee739da722/Functional/allure-report-ce/index.html#categories/bdbf199525818fae7a8651db9eafe741)

[EE Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/8daa1c1bd5c2d1293347bb261352eec3/Functional/allure-report-ee/index.html#categories/bdbf199525818fae7a8651db9eafe741) [EE Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/6980d5d9d422cae289fc64df370d2113/Functional/allure-report-ee/index.html#categories/bdbf199525818fae7a8651db9eafe741)

Known Issues: 
https://jira.corp.adobe.com/browse/AC-15240
https://jira.corp.adobe.com/browse/ACQE-8335
https://jira.corp.adobe.com/browse/AC-15248

Could you please review this PR?

2025-08-01 06:37 UTC, engcom-Hotel commented
@magento run all tests

2025-08-04 05:36 UTC, engcom-Hotel commented
@magento run all tests

2025-08-04 12:50 UTC, engcom-Hotel commented
@magento run Functional Tests CE, Functional Tests EE, Integration Tests

2025-08-04 12:52 UTC, engcom-Hotel requested changes
Hello @rogerdz @engcom-Dash,

Thanks for making the changes!

The failed tests seems flaky to me, hence re-ran the build to double sure. There is one small review comment below, please have a look into it.

Thanks

2025-08-04 12:52 UTC, engcom-Hotel commented on app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php
> +    private const PROCESSOR_PATH = "/^\\/V\\d+/";
The change from `public` to `private` for the PROCESSOR_PATH constant could potentially impact code that directly references this constant.

2025-08-11 05:51 UTC, rogerdz commented
@magento run all tests

2025-08-11 05:52 UTC, rogerdz commented on app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php
> +    private const PROCESSOR_PATH = "/^\\/V\\d+/";
I have updated

2025-08-11 08:23 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

2025-08-11 08:30 UTC, engcom-Hotel approved these changes
Hello @rogerdz,

Thanks for making the changes. Failed tests seems flaky to me hence approving this PR for further processing.

2025-08-14 10:23 UTC, engcom-Bravo commented
@magento run all tests

2025-08-14 10:58 UTC, engcom-Bravo commented
Hi @rogerdz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Retrieve auth token from the admin endpoint /V1/integration/admin/
- Request endpoint: POST : //yourstore/rest/V1/order/{orderId}/ship

Payload:
{
"items": "[]"
}


**Before:** :heavy_multiplication_x: 

<img width="913" height="667" alt="Screenshot 2025-08-14 at 3 46 02 pm" src="https://github.com/user-attachments/assets/574c6a63-4563-4130-a384-a28d70a37282" />






**After:** :heavy_check_mark: 



<img width="913" height="667" alt="Screenshot 2025-08-14 at 3 51 24 pm" src="https://github.com/user-attachments/assets/8b2fb1d0-6f81-428c-9c3e-3d69c2134746" />



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-08-18 05:22 UTC, engcom-Dash commented
@magento run all tests

2025-08-18 08:29 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2025-08-18 11:03 UTC, engcom-Dash commented
One consistent failure in **Functional B2B** is a known issue and JIRA is open for the same. The other failures are inconsistent. They neither related to the PR nor failing because of the PR changes done in this PR.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/390a524141700a3e81a9d2055dac981f/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2556" height="992" alt="image" src="https://github.com/user-attachments/assets/b76b05f8-96be-471b-95ff-7d317a47d664" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/814dba79a8f15202acc3da31e14c3463/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2564" height="396" alt="image" src="https://github.com/user-attachments/assets/24611121-4640-40c7-bdc4-7e47146b0f29" />

**Known Issue:** AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

One consistent failure in **Functional CE** is a known issue and JIRA is open for the same. The other failures are inconsistent. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/c461e1f7a752e5e524095d64cc218222/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2210" height="560" alt="image" src="https://github.com/user-attachments/assets/38200417-b6f2-42d7-a163-8b9010df8503" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/b731b6d89c69656a5b98cd1fcf73980d/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2564" height="672" alt="image" src="https://github.com/user-attachments/assets/1d405fa6-85aa-4de3-b959-55157a6d898c" />

**Known Issue:** StorefrontDeleteSimpleAndVirtualProductFromMiniShoppingCartTest [ACQE-8560](https://jira.corp.adobe.com/browse/ACQE-8560)

One consistent failure in **Functional EE** is a known issue and JIRA is open for the same. The other failures are inconsistent. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/28822aedb6cff37a8f023587589b6b24/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2198" height="792" alt="image" src="https://github.com/user-attachments/assets/7e429570-fd2a-48b9-88a0-6e57dfd45da7" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38282/68b680371bd6bc5c254d395d83435ec4/Functional/allure-report-ee/index.html#categories/494aa5610e07373f0a3ae73eacf3dae2/d481c5e983197d22/

<img width="2554" height="390" alt="image" src="https://github.com/user-attachments/assets/7c87f52e-f134-461d-a0f1-abef346f404d" />

**Known Issue:** AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

Hence moving this PR in Merge In Progress.

2025-09-15 06:18 UTC, merged