Fix for scope bug in Catalog URL resource
magento/magento2 pull request #38394
Opened 2024-01-29 13:15 UTC by pmzandbergen

### Description (*)
Fallback to default scope for the `is_active` category attribute is not working as expected on Url Resource Model. This commit adds a fallback to default scope if there is no value defined on the store scope.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38393

### Manual testing scenarios (*)
1. Create 3 categories
2. Disable one category on the default scope
3. Disable another category on the store scope
4. Execute `\Magento\Catalog\ResourceModel\Url::getCategories(..)`
5. Validate the values of `is_active` on the returned data objects

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-01-30 11:12 UTC, andrewbess commented
@magento run all tests

2024-01-31 10:12 UTC, andrewbess commented
Hello @pmzandbergen 
Thank you for your contribution
But we need to check this changes history

2024-07-16 13:45 UTC, pmzandbergen commented
Any update? :)

2024-11-14 08:24 UTC, engcom-Hotel commented
@magento run all tests

2024-11-14 12:09 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Static Tests

2024-11-14 12:31 UTC, engcom-Hotel commented
We have created a Guild issue for this PR here:

https://github.com/magento-commerce/quality-guild/issues/82

Hence moving this PR `On Hold` for now. We will proceed with this as per the discussion in the guild.

Thanks

2024-11-14 12:33 UTC, pmzandbergen commented
> We have created a Guild issue for this PR here:
> 
> https://github.com/magento-commerce/quality-guild/issues/82
> 
> Hence moving this PR `On Hold` for now. We will proceed with this as per the discussion in the guild.
> 
> Thanks

Unfortunately I don't have access to the Magento Commerce repository. I'll wait patiently.

2025-04-03 15:00 UTC, engcom-Hotel commented
We have received go-ahead on this PR from the internal team, hence we are moving it to appropriate bucket.

Thanks

2025-04-03 15:01 UTC, engcom-Hotel commented
@magento run all tests

2025-04-04 06:13 UTC, engcom-Hotel requested changes
Hello @pmzandbergen,

Thanks for the collaboration!

The changes seems good to us, but I guess we can add an automated test for this fix in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

So please do the needful.

Thanks

2025-04-04 06:36 UTC, pmzandbergen commented
> Hello @pmzandbergen,
> 
> 
> 
> Thanks for the collaboration!
> 
> 
> 
> The changes seems good to us, but I guess we can add an automated test for this fix in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).
> 
> 
> 
> So please do the needful.
> 
> 
> 
> Thanks

Will do after holiday 🏝️

2025-04-21 05:48 UTC, engcom-Hotel commented
Hello @pmzandbergen,

Have you got a chance to look into this PR for further progress?

Thanks

2025-04-21 08:29 UTC, pmzandbergen commented
> Hello @pmzandbergen,
> 
> 
> 
> Have you got a chance to look into this PR for further progress?
> 
> 
> 
> Thanks

Yes, tests will be committed tomorrow.

2025-04-22 17:51 UTC, pmzandbergen commented
@engcom-Hotel my apologies, busy with after-holiday tasks. I'll finish the tests and commit them tomorrow (23th, CEST).

2025-04-23 05:14 UTC, engcom-Hotel commented
Sure, @pmzandbergen. I understand. Thank you for the update.

2025-04-23 06:13 UTC, pmzandbergen commented
@engcom-Hotel an integration test has been added.

2025-04-24 11:01 UTC, engcom-Hotel commented
@magento run all tests

2025-04-25 07:25 UTC, engcom-Hotel requested changes
Hello @pmzandbergen,

Thanks for making the changes as per the review comment. but please use parameterized fixture format, as the format used for creating fixtures is deprecated. Also  please fix the static test failures and review comment below.

Thanks

2025-04-25 07:25 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php
> +        $this->assertTrue((bool) $categories[3]->getIsActive());
The test uses `assertTrue` and `assertFalse` with a cast to (bool). While this works, using `assertSame` ensures stricter type checking and avoids potential issues with unexpected data types.

2025-04-28 04:37 UTC, engcom-Hotel commented
@magento run all tests

2025-04-28 08:25 UTC, engcom-Hotel requested changes
Hello @pmzandbergen,

Please have a look into the below review comment and also fix the failed static tests.

Thanks

2025-04-28 08:25 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php
> +        $categoryIds = array_combine($fixtureNames, array_map(function (string $fixtureName): int {
Here error `Illegal array key type array` might arises because the `array_combine` function is used with `$fixtureNames` as keys and the result of `array_map` as values. However, the `array_map` callback returns an array, which is not valid as array keys.

Replacing the `array_combine` function with a foreach loop to ensure that `$categoryIds` is constructed with valid scalar keys.

```
$categoryIds = [];
foreach ($fixtureNames as $fixtureName) {
    $categoryIds[$fixtureName] = (int) $this->fixtures->get($fixtureName)->getId();
}
```

2025-04-28 10:59 UTC, engcom-Hotel commented
@magento run all tests

2025-04-28 13:18 UTC, engcom-Hotel requested changes
Hello @pmzandbergen,

We are still having a static test failure related to copyright. Please use copyright as below.

Thanks

2025-04-28 13:18 UTC, engcom-Hotel commented on dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php
> + */
```suggestion
/**
 * Copyright 2025 Adobe
 * All Rights Reserved.
 */
```

2025-04-29 05:21 UTC, engcom-Hotel commented
@magento run all tests

2025-04-29 09:41 UTC, engcom-Hotel approved these changes

2025-05-07 08:41 UTC, engcom-Dash commented
@magento run all tests

2025-05-07 11:16 UTC, engcom-Dash commented
@pmzandbergen Thank you for contribution & collaboration!

<h3> ✔️  QA Passed </h3>

Preconditions:
Install Fresh Magento 2.4-develop

Steps to reproduce:
1. Create 2 categories. 
2. Disable one category on the default scope (Category ID: 560)
3. Disable another category on the store scope (Category ID: 551)
4. Created a custom script to execute \Magento\Catalog\ResourceModel\Url::getCategories(..)
    
<img width="425" alt="Screenshot 2025-05-07 at 4 40 15 PM" src="https://github.com/user-attachments/assets/7bad2d32-5833-4705-9dbd-b340d6aa6b99" />


<h4> Before: ❌  </h4>

The returned data object of categories was not having "is_active" key in the category (ID 560) disabled at default scope because the following condition was invalid and it was not falling back to the default scope.
`$isActiveExpr = $connection->getCheckSql('c.value_id > 0', 'c.value', 'c.value');
`

<img height="400" width="433" alt="Screenshot 2025-05-07 at 4 08 27 PM" src="https://github.com/user-attachments/assets/1eab6a7a-02d6-43eb-94f3-dd4518681926" />

<h4> After:  ✔️  </h4>
On PR branch it fallbacks to the default scope and "is_active" key gets added on the category disabled at default scope.

<img height="400" width="444" alt="Screenshot 2025-05-07 at 4 19 50 PM" src="https://github.com/user-attachments/assets/3fafd339-22b3-476d-b084-8ca7e2114b25" />

Also verified the SQL Query in order to validate the changes

![image](https://github.com/user-attachments/assets/5ff49a7d-d1b1-483c-aa30-2d7f676632dc)

Builds are failed hence moving this PR in Extended Testing

2025-05-07 11:27 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE

2025-05-07 13:57 UTC, engcom-Dash commented
One of the consistent **Functional B2B** test failure is a **known issue** and JIRA is present for the same. Other test failures are inconsistent and seems to be flaky. They are not related to this PR nor part of PR. Hence moving this PR in **Merge In Progress**.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38394/8465e3cfae06f7063a6f95d847c9414f/Functional/allure-report-b2b/index.html#categories/dd1aec766b2934fec7e9751b4078a7fe/a965cd4ef73e5cf8/

![image](https://github.com/user-attachments/assets/398ea554-3feb-412c-8814-f2d0eb58eb8a)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38394/056a89fafc5ea494686ae7a582bec8f9/Functional/allure-report-b2b/index.html#categories/2d77c243b99b20b245f50650375f7fbf/e1d773e66b3ef8a0/

![image](https://github.com/user-attachments/assets/26ca5212-844b-4304-bf63-bb2423ece4a0)

**Known Issue:** AdminDeleteCatalogPriceRuleEntityFromConfigurableProductTest [ACQE-7945](https://jira.corp.adobe.com/browse/ACQE-7945)

2025-06-26 06:32 UTC, merged