Fix/downloadable domains parameter
magento/magento2 pull request #38409
Opened 2024-02-01 17:43 UTC by YevhenZvieriev

### Description
### Update to the bin/magento downloadable:domains:add and bin/magento downloadable:domains:remove commands

Upon reviewing the usage of the `bin/magento downloadable:domains:add` and `bin/magento downloadable:domains:remove` commands, it was noticed that when these commands are invoked without passing a parameter, nothing happens, and the user receives an unclear outcome.

In this Pull Request, a new feature has been added to display an error message if the parameter is missing. Users will now receive a clear notification that they forgot to pass a parameter when invoking these commands.

### Changes

- Added a check for the presence of the parameter for the `bin/magento downloadable:domains:add` and `bin/magento downloadable:domains:remove` commands.
- Displayed an appropriate error message if the parameter is missing.

These changes enhance the user experience and prevent the unintended execution of commands without passing the required parameter.

**Before:**

![Screenshot from 2024-02-01 18-33-54](https://github.com/magento/magento2/assets/43544955/7ec7ef05-909b-43f8-bff9-4c272c313b0d)

**After:**

![Screenshot from 2024-02-01 18-35-24](https://github.com/magento/magento2/assets/43544955/bc783497-5ba1-4e8a-a6e9-3fb17e9db1ea)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-02-01 17:44 UTC, YevhenZvieriev commented
@magento run all tests

2024-02-10 22:45 UTC, andrewbess requested changes
Hello @YevhenZvieriev 
Thank you for your contribution
Could you please fix code to fix the static test failures
Thank you in advance

2024-02-11 10:13 UTC, YevhenZvieriev commented
@magento run all tests

2024-02-11 11:19 UTC, YevhenZvieriev commented
@magento run all tests

2024-02-11 13:08 UTC, YevhenZvieriev commented
Hi, @andrewbess 

After my prior [commit](https://github.com/magento/magento2/pull/38409/commits/8cbd20469dfa9554c59fce2d25855e6761c74c40), I get an error in the static tests reports

```
 No build reports available

Unfortunately there's no build reports were generated. That may be caused by either infrastructure issues or fatal errors during the build run. Please address this issue to Community Engineering Team members.```

2024-02-11 13:20 UTC, YevhenZvieriev commented
@magento run all tests

2024-02-11 15:47 UTC, YevhenZvieriev commented
@magento run all tests

2024-02-11 16:47 UTC, YevhenZvieriev commented
@magento run all tests

2024-02-11 17:33 UTC, YevhenZvieriev commented
@magento run all tests

2024-02-11 18:12 UTC, YevhenZvieriev commented
Hello @andrewbess 

After fixing the static test issues, the code is now passing every static test. Kindly take a moment to review the revised version of the PR.

2024-10-24 10:02 UTC, engcom-Dash commented
@magento run all tests

2024-10-24 12:48 UTC, engcom-Dash commented
@magento run all tests

2025-10-23 08:26 UTC, engcom-Hotel commented
Hello @YevhenZvieriev,

Thank you for your contribution!

Please resolve the merge conflicts in this PR when you get a chance, so that we can proceed with this PR.

Meanwhile moving this PR on hold.

Thanks

2025-10-23 18:56 UTC, YevhenZvieriev commented
Hi @engcom-Hotel,

I've resolved the merge conflicts.

Let me know if anything else is needed.

Thanks a lot!

2025-10-24 06:45 UTC, engcom-Hotel commented
@magento run all tests

2025-10-24 08:31 UTC, engcom-Hotel requested changes
Hello @YevhenZvieriev,

Thank you for your contribution!

The current configuration defines the `domains` parameter as optional. This produces `--help` output with square brackets (indicating optional). 

But the PR adds validation that requires at least one domain, creating a mismatch between the command definition and its actual behavior.

Please update the `configure()` method to make the arguement required.

2025-10-24 19:24 UTC, YevhenZvieriev commented
Hi @engcom-Hotel,

 I’ve updated both commands to make the domains argument required, ensuring consistency between the command definition and its actual behavior.

Additionally, I fixed a minor typo in the argument description ('Domains name' --> 'Domain names').

Please review the changes when you have a moment.

Thank you!

2025-10-27 07:33 UTC, engcom-Hotel commented
@magento run all tests

2025-10-28 11:37 UTC, engcom-Hotel commented
Hello @YevhenZvieriev,

Currently we are discussing this PR with the PO, meanwhile moving this PR on hold. We will update you soon on this.

Thank you

2025-11-13 06:46 UTC, engcom-Hotel commented
Hello @YevhenZvieriev,

We got approval to proceed with this PR from PO. We are picking this for further review.

Thank you

2025-11-13 06:46 UTC, engcom-Hotel commented
@magento run all tests

2025-11-14 10:44 UTC, engcom-Hotel commented
@magento run all tests

2025-11-17 08:18 UTC, engcom-Hotel commented
@magento run all tests

2025-11-17 11:47 UTC, engcom-Hotel requested changes
Hello @YevhenZvieriev,

Thank you for your contribution!

Please have a look into the below review comments and also check the failed automated tests, it seems they are failing due to the PR changes.

Thank you

2025-11-17 11:47 UTC, engcom-Hotel commented on app/code/Magento/Downloadable/Console/Command/DomainsAddCommand.php
> +        DownloadManager $downloadManager
Adding new parameter in constructor is BiC change, requesting you to mark it as `null` and use ObjectManager to initialise it.

2025-11-17 11:47 UTC, engcom-Hotel commented on app/code/Magento/Downloadable/Console/Command/DomainsRemoveCommand.php
> +        DownloadManager $downloadManager
Adding new parameter in constructor is BiC change, requesting you to mark it as `null` and use ObjectManager to initialise it.

2026-01-08 16:39 UTC, engcom-Dash commented
Hello @YevhenZvieriev,
Just following up to check if you had a chance to review the comments and investigate the failed automated tests mentioned earlier.

This PR has been pending for quite some time, and we’re currently unable to proceed further without your updates. Please let us know so we can further proceed.

Thanks!

2026-01-19 13:08 UTC, engcom-Dash commented
Hello @YevhenZvieriev,

We appreciate your contribution!

Since we haven't received a response from you for an extended period, we are closing this PR for now.
Whenever you're ready to resume work on this, please feel free to reopen it or request us to do so. 
We'll be more than happy to assist you.

Thanks once again!

2026-01-19 13:08 UTC, closed without merging