Update Filter.php  to allow {{block template="Magento_Module::path/to/template.phtml"}}  and setting \Magento\Framework\View\Element\Template as default class
magento/magento2 pull request #38469
Opened 2024-02-25 05:17 UTC by JDavidVR

### Description (*)
Besides:
{{block id="static_cms_block" }}
{{block id="1" }}
{{block class='\Magento\Theme\Block\Html\Footer' name='test.block' template='Magento_Theme::html/footer.phtml'}}

It also allows: 
{{block template='Magento_Module::html/footer.phtml'}}

setting as default block: \Magento\Framework\View\Element\Template

like  layout.xml is doing:  https://developer.adobe.com/commerce/frontend-core/guide/layouts/xml-instructions/#block

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-02-25 11:35 UTC, mrtuvn commented
can you describe more about the reason of this update ? and also add some test case for coverage your changes

2024-02-25 11:57 UTC, andrewbess commented
Hello @JDavidVR 
Thank you for your contribution.
Could you please sing Adobe CLA?
Thank you in advance.

2024-02-25 13:49 UTC, JDavidVR commented
@andrewbess I've already signed the Adobe CLA

Not sure why it is not updated

<img width="731" alt="image" src="https://github.com/magento/magento2/assets/4760084/cf182a07-3df3-4117-b9d7-9d5db3d0d191">

<img width="737" alt="image" src="https://github.com/magento/magento2/assets/4760084/2ba8236c-70dd-4174-b9e9-a655f12790e3">

2024-02-25 13:56 UTC, JDavidVR commented
@mrtuvn this change allows to call templates files in cms_pages & cms_blocks

For ex. `{{block template='Magento_Module::template/file.phtml'}}` instead of `{{block class= ' \Magento\Framework\View\Element\Template' template='Magento_Module::template/file.phtml'}}`

<img width="1180" alt="image" src="https://github.com/magento/magento2/assets/4760084/add1fdbb-3871-4593-a9f4-6c74690ff7fc">


this change is inspired on how layout.xml is working:

<img width="817" alt="image" src="https://github.com/magento/magento2/assets/4760084/f64009b8-1bf6-42c8-86f0-b3cced05f16e">

2024-02-25 15:12 UTC, andrewbess commented
@magento run all tests

2024-02-27 11:10 UTC, engcom-Hotel commented
@magento create issue

2026-05-05 07:39 UTC, engcom-Hotel commented
@magento run all tests

2026-05-05 15:42 UTC, engcom-Hotel commented
Hello @JDavidVR,

Thank you for your contribution!

As the PR has been categorized as a feature request, we have sent an email to our PO for an approval. Whenever we received a reply from them, we will pick this accordingly.

Meanwhile we are moving this PR on hold.

Thank you

2026-05-06 10:50 UTC, engcom-Hotel commented
Hello @JDavidVR,

We have received an approval from the PO to proceed further with this PR. Hence moving again this PR in Review in progress for further analysis.

Thank you

2026-05-06 11:19 UTC, engcom-Hotel requested changes
Hello @JDavidVR,

Thank you for your contribution!

The changes looks good to us, but please fix the static test failure and minor review comment below.

Thank you

2026-05-06 11:19 UTC, engcom-Hotel commented on app/code/Magento/Email/Model/Template/Filter.php
> +            $block = $this->_layout->createBlock(\Magento\Framework\View\Element\Template::class, null, ['data' => $blockParameters]);
Inline FQN instead of `use` alias. Use alias here

2026-05-11 07:46 UTC, engcom-Hotel commented
@magento run all tests

2026-05-11 09:32 UTC, engcom-Hotel requested changes
Hello @JDavidVR,

It seems there are multiple failures due to the recent changes. Please have a look into the failed tests for more information.

Thank you

2026-05-14 05:54 UTC, engcom-Charlie commented
@magento run all tests

2026-05-14 10:38 UTC, engcom-Charlie commented
@magento run all tests

2026-05-15 06:15 UTC, engcom-Charlie commented
@magento run all tests

2026-05-15 10:58 UTC, engcom-Charlie commented on app/code/Magento/Email/Model/Template/Filter.php
> +            $block = $this->_layout->createBlock(\Magento\Framework\View\Element\Template::class, null, ['data' => $blockParameters]);
@engcom-Hotel using same class alias creating issues in the PR.

2026-05-15 11:13 UTC, engcom-Charlie commented
Fixed the class conflict issue. All test failures have been resolved.

2026-05-15 11:14 UTC, engcom-Charlie commented
@magento run all tests

2026-05-15 13:27 UTC, engcom-Charlie commented
> Hello @JDavidVR,
> 
> It seems there are multiple failures due to the recent changes. Please have a look into the failed tests for more information.
> 
> Thank you

@engcom-Hotel I have fixed the test failures, moving it to review again.

2026-05-18 05:56 UTC, engcom-Hotel commented
@magento run all tests

2026-05-18 11:50 UTC, engcom-Hotel approved these changes

2026-05-21 05:18 UTC, engcom-Charlie commented
@magento run all tests

2026-05-22 09:03 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2026-06-04 05:00 UTC, engcom-Charlie commented
@magento run all tests

2026-06-04 05:13 UTC, engcom-Charlie commented
Hi @JDavidVR,

Thank you for your contribution!

### :heavy_check_mark: QA Passed

**Preconditions:**

- Install clean magento instance

**Steps to reproduce**
	1. Open Marketing → Communications → Email Templates in Admin
	2. Edit/Add a template (e.g. “New Account”).
	3. Add: {{block template="Magento_Theme::html/footer.phtml"}} in Template Content section
	4. Preview the email.

**Before:** :heavy_multiplication_x:
Blank footer → {{block template="..."}} is not rendered (or not saved/processed correctly)
<img width="1289" height="210" alt="image" src="https://github.com/user-attachments/assets/63b514e1-82b6-4c24-91ea-69c1efe8df09" />


**After:** :heavy_check_mark: 
Footer with "Help Us Keep Magento Healthy - Report All Bugs" → Magento_Theme::html/footer.phtml is rendered

<img width="1186" height="212" alt="image" src="https://github.com/user-attachments/assets/60e96ce5-490f-476f-a726-6810b57844ba" />

Moving this PR to Extended testing to look into build stability.

2026-06-04 10:03 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2026-06-04 12:45 UTC, engcom-Charlie commented
Few of the Functional failures are not consistent in recent 2 builds. They are neither failing because of the PR nor part of the PR, consider to be flaky. The consistent failures are known issues hence moving this PR to Merge in Progress.

**Functional B2B- Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38469/10d6e66297f89b1eaad7bdc3e28f2e9d/Functional/allure-report-b2b/index.html#categories
<img width="1180" height="711" alt="image" src="https://github.com/user-attachments/assets/08c2fdea-654b-455b-89e9-9a0302295b6c" />


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38469/22a8d584043ccac7058112cc116e9551/Functional/allure-report-b2b/index.html#categories/2aeb69a059ea48f60e544be29fa2d34d/4e450b0e7e96c512/
<img width="1164" height="702" alt="image" src="https://github.com/user-attachments/assets/c4dbb445-1d41-4d07-9c76-c6677317c123" />



**Functional CE- Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38469/68203450166055838e940082720e5037/Functional/allure-report-ce/index.html#categories
<img width="1190" height="516" alt="image" src="https://github.com/user-attachments/assets/202230ff-66f5-4edc-9c07-ab11a343e521" />


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38469/570e00d4d44377cab58757b45a71fcde/Functional/allure-report-ce/index.html#categories/801bb10e8e37dae0d4988d0fd030c8fe/7dfa51d7670aeead/
<img width="1190" height="434" alt="image" src="https://github.com/user-attachments/assets/d8173f05-95ed-4bb8-aa1c-abe4efb9e42e" />


**Functional EE- Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38469/d832bb98d93adf5d4a54c9c41975491a/Functional/allure-report-ee/index.html#categories/64a3d29f53666d708ea7ecc82bb1e59f/68781cbd863a87e0/
<img width="1178" height="489" alt="image" src="https://github.com/user-attachments/assets/bc37171c-850d-4648-a155-7a7333d3b39a" />


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38469/2952061cd799dce27db51635921d7632/Functional/allure-report-ee/index.html#categories/41917c49d250684006e62f8553d238ec/7f9faf0410a0223f/
<img width="1193" height="405" alt="image" src="https://github.com/user-attachments/assets/35777d62-59bd-4568-9c82-fea88b1950ad" />

**Known Issues:**
[ACQE-10585](https://jira.corp.adobe.com/browse/ACQE-10585): AdminAdobeStockLocalizationTest
[ACQE-9640](https://jira.corp.adobe.com/browse/ACQE-9640): StockStatusChangedForConfigurableProductOnTestStockAndTestWebsiteTest
[ACQE-10301](hhttps://jira.corp.adobe.com/browse/ACQE-10301): StorefrontBundleProductChangeStockStatusCustomStockCustomWebsiteTest
[ACQE-9895](https://jira.corp.adobe.com/browse/ACQE-9895): StorefrontVerifyProductReviewInCustomerAccountTest
[ACQE-10249](https://jira.corp.adobe.com/browse/ACQE-10249): StorefrontCheckTermsAndConditionIsPresentInPaymentPageTest
[ACQE-9802](https://jira.corp.adobe.com/browse/ACQE-9802): AdminSettingCustomerPhoneNumberTest
[ACQE-9976](https://jira.corp.adobe.com/browse/ACQE-9976): StorefrontVerifyThatInformationAboutViewingComparisonWishlistIsPersistedUnderLongTermCookieTest
[ACQE-9629](https://jira.corp.adobe.com/browse/ACQE-9629): AdminUserSetStatusForEachSourceItemTest

2026-06-05 06:49 UTC, merged