Check if OpenGraph can show price
magento/magento2 pull request #38510
Opened 2024-03-11 14:21 UTC by barryvdh

### Description (*)
This checks if the price can be shown

### Manual testing scenarios (*)
- Create a plugin which hides the price, or use https://github.com/karliuka/m2.ProductAvailable
- Check that the price is hidden
- Check that without this change, the price is still visible in the OG tag.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-03-11 14:24 UTC, barryvdh commented
@magento run all tests

2024-03-12 11:04 UTC, engcom-Hotel commented
@magento create issue

2024-05-03 07:27 UTC, barryvdh commented
@magento run WebAPI Tests

2025-05-15 05:30 UTC, engcom-Hotel commented
@magento run all tests

2025-05-15 10:39 UTC, engcom-Hotel requested changes
Hello @barryvdh,

Thanks for the contribution!

Please fix the failed static tests, other failed tests seems flaky to me.

Thanks

2025-05-15 11:02 UTC, barryvdh commented
> Hello @barryvdh,
> 
> Thanks for the contribution!
> 
> Please fix the failed static tests, other failed tests seems flaky to me.
> 
> Thanks

Do you mean this error?
![Screenshot 2025-05-15 at 13 01 24](https://github.com/user-attachments/assets/bc657234-c236-4ceb-9fb4-326c61a5ff58)

That doesn't seem relevant to my PR, or do you need me to fix the rest of the template?

2025-05-15 11:06 UTC, engcom-Hotel commented
Hello @barryvdh,

I agree that the failures are not related to your changes, but we need a green build to proceed further with this.

Thanks

2025-05-15 11:18 UTC, barryvdh commented
https://github.com/magento run static tests

2025-05-15 11:19 UTC, barryvdh commented
@magento run static tests

2025-05-15 12:30 UTC, barryvdh commented
@magento run all tests

2025-05-15 14:20 UTC, barryvdh commented
@magento  run all tests

2025-05-16 05:53 UTC, engcom-Hotel requested changes
Hello @barryvdh,

Thanks for the making the changes, one more small change is required as suggested below.

Please do the needful.

Thanks

2025-05-16 05:53 UTC, engcom-Hotel commented on app/code/Magento/Catalog/view/frontend/templates/product/view/opengraph/general.phtml
> + * Copyright 2025 Adobe
```suggestion
 * Copyright 2011 Adobe
```

2025-05-16 06:15 UTC, barryvdh commented
@magento run all tests

2025-05-16 11:57 UTC, barryvdh commented
@engcom-Hotel all good now?

2025-05-19 04:57 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

2025-05-19 05:34 UTC, engcom-Hotel approved these changes

2025-05-20 10:18 UTC, engcom-Bravo commented
@magento run all tests

2025-05-20 12:12 UTC, engcom-Bravo commented
Hi @barryvdh,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Create a plugin which hides the price, or use https://github.com/karliuka/m2.ProductAvailable
- Check that the price is hidden
- Check that without this change, the price is still visible in the OG tag


**Before:** :heavy_multiplication_x: 

<img width="1429" alt="Screenshot 2025-05-20 at 3 51 28 pm" src="https://github.com/user-attachments/assets/a1b0b791-3cf7-4ad0-8471-7f0bdc28743d" />



<img width="1435" alt="Screenshot 2025-05-20 at 1 01 16 pm" src="https://github.com/user-attachments/assets/2463aac0-4f1a-428d-8f85-734fcd0b7af3" />





**After:** :heavy_check_mark: 

price is not visible in the OG tag.



<img width="1429" alt="Screenshot 2025-05-20 at 3 51 28 pm" src="https://github.com/user-attachments/assets/eedf5a6c-2ce3-446f-a7b8-573e7a31f586" />








<img width="1359" alt="Screenshot 2025-05-20 at 3 49 38 pm" src="https://github.com/user-attachments/assets/8b8e8e6a-c179-4970-a1c8-f1e1cc895653" />






Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-05-23 06:25 UTC, engcom-Dash commented
@magento run all tests

2025-05-23 08:45 UTC, engcom-Dash commented
@magento run Unit Tests, Functional Tests B2B, Functional Tests EE, Functional Tests CE

2025-05-23 11:33 UTC, engcom-Dash commented
The consistent test failures for **Functional B2B** are known Issues and JIRA is raised for them. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38510/5ca8272b8857988043cdae955df852d5/Functional/allure-report-b2b/index.html#categories/ba729ce87e7059ef4466d4300850777a/722ee95bc7de6136/

<img width="1434" alt="Screenshot 2025-05-23 at 4 25 56 PM" src="https://github.com/user-attachments/assets/0c88def0-f895-49b1-bbdf-2167cec73bae" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38510/d10ae97404e2930646afc457cebd1ed2/Functional/allure-report-b2b/index.html#categories/ba729ce87e7059ef4466d4300850777a/15276744294c5a42/

<img width="1424" alt="Screenshot 2025-05-23 at 4 26 30 PM" src="https://github.com/user-attachments/assets/4ecce945-de76-4e74-9944-87f4e7b9f579" />

**Known Issues:**
OrderWithMultipleConfigurableProductsAdditionalStockTest :  [ACQE-8060](https://jira.corp.adobe.com/browse/ACQE-8060)
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)
StoreFrontSimpleProductWithSpecialAndTierDiscountPriceTest : [ACQE-7971](https://jira.corp.adobe.com/browse/ACQE-7971)

The consistent test failure for **Functional CE** is known Issues and JIRA is raised for the same. 

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38510/ca591881f4de4023cba453a622039d61/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/431ab2d5-4ed4-473b-a679-c2526ae85c00)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38510/2a15ee83cd96cf22a4fa170076e4bd6f/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/6a269474-c2e7-49ef-b210-665bc977f926)

**Known Issues:**
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

2025-05-23 11:40 UTC, engcom-Dash commented
The consistent test failure for **Functional EE** is known Issues and JIRA is raised for the same. Other failure is inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38510/b780ede4c5d83a4438f07e581d47f592/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/ce7bcbff-4509-4542-a5fe-49de22e9731c)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38510/86e60bf286aaad1ca64bf0bcaaadb5e3/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/966ad043-de91-43ea-a632-dc40fc7d9d79)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

Hence moving this PR in Merge In Progress.

2025-06-17 06:34 UTC, engcom-Dash commented
@magento run all tests

2025-06-26 11:02 UTC, merged