Remove scope resolver usage
magento/magento2 pull request #38554
Opened 2024-03-27 21:20 UTC by thomas-kl1

### Description (*)
Admin URL settings is global and shouldn't be loaded depending of the current store.

2024-04-02 11:03 UTC, engcom-Hotel commented
@magento create issue

2024-04-09 08:56 UTC, thomas-kl1 commented
I've noticed this issue while I was looking for current store resolution in the code trace stack.
The scope resolution is done too early.

2024-04-09 08:59 UTC, thomas-kl1 commented
@magento run all tests

2024-09-17 10:55 UTC, engcom-Hotel commented
@magento run all tests

2024-09-17 13:01 UTC, engcom-Hotel requested changes
Hello @thomas-kl1,

Thanks for the contribution!

It seems the tests are failing due to code changes, please fix them and also cover the changes with some automated tests.

Thanks

2024-09-18 13:14 UTC, engcom-Dash commented
@magento run all tests

2024-09-19 06:13 UTC, engcom-Dash commented
Fixed failing unit test cases so moving this back to pending review.

2024-09-20 06:25 UTC, engcom-Hotel approved these changes

2024-09-23 11:43 UTC, engcom-Dash commented
Hello @thomas-kl1 ,

Thank you for your contribution!

I wanted to let you know that I can’t proceed with testing your changes at the moment because I’m facing an issue. When using the admin custom URL, it redirects to a 404 page. Once this issue is resolved, I’ll be able to test your changes.

Just wanted to keep you in the loop. 

Thanks again!

2025-03-19 11:40 UTC, engcom-Dash commented
@thomas-kl1  I have pushed a commit to resolve the conflicts. I am able to test the changes after adding custom admin URL  and custom admin path. The default scope is used now

Storefront:

<img width="1704" alt="image" src="https://github.com/user-attachments/assets/adb5237a-0d2f-47a6-8d5c-e3ad7ba85e74" />

Admin (With custom path & URL):

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/82eb5f4f-add0-4d98-99c7-f385a865ab84" />

Thanks

2025-03-19 11:41 UTC, engcom-Dash commented
@magento run all tests

2025-03-20 05:14 UTC, engcom-Dash commented
@thomas-kl1 Thank you for contribution!

**:heavy_check_mark: QA Passed**

Preconditions:
Install fresh magento 2.4-develop

Steps to reproduce
According to the PR description.

Before:
As per PR description the store scope was getting passed to the admin URL and it should not be loaded depending on the current store.

After: The default scope is used now for custom admin URL 

Storefront:

<img width="1704" alt="image" src="https://github.com/user-attachments/assets/adb5237a-0d2f-47a6-8d5c-e3ad7ba85e74" />

Admin (With custom path & URL):

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/82eb5f4f-add0-4d98-99c7-f385a865ab84" />

Some of the test cases are failing hence moving this PR to Extended Testing.

Thank You!

2025-03-20 08:44 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

2025-03-20 13:23 UTC, engcom-Dash commented
@magento run all tests

2025-03-21 05:40 UTC, engcom-Dash commented
@magento run all tests

2025-03-21 08:20 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

2025-03-21 11:26 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2025-03-21 14:29 UTC, engcom-Dash commented
In the recent builds for functional EE & CE the constant test case failures are known issues and JIra issues are logged for the same. 

Functional EE:

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38554/a5b229d6e24c7a99a26ff816562a0fe4/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="1432" alt="Screenshot 2025-03-21 at 7 29 40 PM" src="https://github.com/user-attachments/assets/63c2c5b7-726d-4590-80bf-4b5e3b647b9f" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38554/6c94fed22d12a39ebc67829f048151f1/Functional/allure-report-ee/index.html#categories

<img width="1420" alt="Screenshot 2025-03-21 at 7 29 04 PM" src="https://github.com/user-attachments/assets/2ca94822-1700-41f9-afdd-28c0b9be2e75" />

Functional CE:

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38554/bd4a19a31973e4fc56646dd63e2911d2/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="1423" alt="Screenshot 2025-03-21 at 7 40 57 PM" src="https://github.com/user-attachments/assets/e89c4924-00d9-4435-b693-5491846b5b6e" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38554/cf116c7e77dd34c9914c2fa24ba33e12/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="1427" alt="Screenshot 2025-03-21 at 7 42 27 PM" src="https://github.com/user-attachments/assets/0bc73c63-6c32-4365-ae3e-07cbeccae49c" />

**Known Issues:**

StorefrontVerifySearchTermEntityRedirectTest: [ACQE-7705](https://jira.corp.adobe.com/browse/ACQE-7705)
AdminUserApplyToSeveralSimpleProductsMassActionUnAssignProductSourcesOnProductsGridToUnAssignAllAssignedSourcesTest: [ACQE-7706](https://jira.corp.adobe.com/browse/ACQE-7706)
AdminValidateSimpleProductWithCustomOptionsDragNDropPerPageTest: [ACQE-7707](https://jira.corp.adobe.com/browse/ACQE-7707)

Keeping the PR in ET for the consistent test case failures for Functional B2B.

2025-05-20 18:19 UTC, merged