Add explanatory titles to cache management buttons
magento/magento2 pull request #38598
Opened 2024-04-09 15:52 UTC by YevhenZvieriev

### Description
This Pull Request adds explanatory titles to cache management buttons on the Cache Management page. The added titles provide users with a better understanding of the functionality of each button, making their interaction with the cache management buttons more intuitive. These changes improve the user experience and provide a better understanding of the functionality of cache management buttons on the Magento admin page, because at first glance it is not clear what the difference between these two buttons is.

### Changes

Added explanatory titles to the `"Flush Cache Storage"`  and  `"Flush Magento Cache"` buttons.

The title for the `Flush Cache Storage` button when you move the cursor over it now explains that it performs similar actions as the `bin/magento cache:flush` command:

![Screenshot from 2024-04-09 18-30-36](https://github.com/magento/magento2/assets/43544955/08e69324-fe98-4e07-b993-73e84ecbfdc3)

The title for the `Flush Magento Cache` button when you move the cursor over it now explains that it performs actions similar to the `bin/magento cache:clean` command:

![Screenshot from 2024-04-09 18-39-43](https://github.com/magento/magento2/assets/43544955/5b5a9f02-f648-4ea5-b598-4de5a0f1058e)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-04-09 15:54 UTC, YevhenZvieriev commented
@magento run all tests

2024-04-10 10:08 UTC, YevhenZvieriev commented
@magento run all tests

2024-04-10 13:50 UTC, engcom-Hotel commented
@magento create issue

2024-04-11 21:02 UTC, YevhenZvieriev commented
@magento run all tests

2024-07-02 13:03 UTC, hostep commented
I don't think this is a good idea, the admin interface is often used by people who have no idea what `bin/magento` command is or how they can use it, so these extra titles might confuse them.

If you can find some well written description in English that can explain the difference between the buttons better, without using too many technical terms, then I think it would be better then mentioning developer specific jargon.

But that's just my opinion.

2025-10-27 13:55 UTC, engcom-Hotel commented
@magento run all tests

2025-10-27 22:37 UTC, hostep commented
@engcom-Hotel, @YevhenZvieriev: doesn't [my previous comment](https://github.com/magento/magento2/pull/38598#issuecomment-2203104519) make sense to you guys? This interface is often used by non-technical users, I really wouldn't put technical jargon in this UI if I were you...

2025-10-28 09:00 UTC, engcom-Hotel commented
Hello @YevhenZvieriev,

I agree with @hostep for this https://github.com/magento/magento2/pull/38598#issuecomment-2203104519. 

Can you please update the PR for the admin panel users, which helps them in knowing the actual difference between both the buttons? Meanwhile we are moving this PR `On Hold`.

Thank you

2025-11-11 06:45 UTC, engcom-Hotel commented
Hello @YevhenZvieriev,

Gentle reminder for this PR.

Thank you

2025-11-11 10:17 UTC, YevhenZvieriev commented
Hello, @engcom-Hotel,

I have updated the titles to make them clearer for admin users who might not be familiar with CLI commands. The new titles now explain the difference between the buttons in simple, user-friendly language.

Please review the changes when you have a chance. Thanks!

2025-12-12 09:48 UTC, engcom-Hotel commented
Thank you @YevhenZvieriev for the updates.

We are picking this PR for review.

2025-12-12 09:48 UTC, engcom-Hotel commented
@magento run all tests

2025-12-12 12:32 UTC, engcom-Hotel requested changes
Hello @YevhenZvieriev,

Please fix the failed static tests.

Thank you

2025-12-12 13:13 UTC, YevhenZvieriev commented
@magento run all tests

2025-12-12 14:07 UTC, YevhenZvieriev commented
Hi, @engcom-Hotel 

The static test issues have been resolved

Please let me know if anything else is required

Thank you

2025-12-15 05:59 UTC, engcom-Hotel commented
@magento run all tests

2025-12-15 10:57 UTC, engcom-Hotel approved these changes

2025-12-17 13:00 UTC, engcom-Bravo commented
Hi @YevhenZvieriev,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Before:** :heavy_multiplication_x: 

<img width="1316" height="572" alt="Screenshot 2025-12-17 at 2 22 47 pm" src="https://github.com/user-attachments/assets/97bdc64b-4c0b-49bd-b097-f69d5ddd8ed5" />



<img width="1345" height="574" alt="Screenshot 2025-12-17 at 2 22 58 pm" src="https://github.com/user-attachments/assets/93889144-5b30-4dda-932f-b727e5273c8d" />





**After:** :heavy_check_mark: 

<img width="1345" height="574" alt="Screenshot 2025-12-17 at 2 27 01 pm" src="https://github.com/user-attachments/assets/ec69f81f-fc32-409b-986a-edaf6475b627" />



<img width="1351" height="574" alt="Screenshot 2025-12-17 at 2 27 17 pm" src="https://github.com/user-attachments/assets/4424f692-3334-43db-bb6b-512f84295e3c" />








Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-12-17 13:21 UTC, engcom-Dash commented
@magento run all tests

2025-12-18 06:37 UTC, engcom-Dash commented
@magento run all tests

2025-12-18 11:02 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests, Static Tests

2025-12-18 22:59 UTC, engcom-Dash commented
The consistent failures in static tests are known issues and JIRA is open for the same. 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38598/06b9c532599bd0a1948c2bf737efb98b/Statics/report-sanity-ce.html
<img width="917" height="240" alt="image" src="https://github.com/user-attachments/assets/c81335f2-31d4-4010-a1ac-184540d44500" />
Known Issue
dev/tools/Magento/Tools/DatabaseCompare/etc/leftovers/ee/config.php:
TargetRule  [AC-16215](https://jira.corp.adobe.com/browse/AC-16215)

2025-12-23 16:16 UTC, merged