Shipping price showing different in printed pdf
magento/magento2 pull request #38595
Opened 2024-04-09 12:00 UTC by DhruvBasan

### Description (*)
In Stores -> Configuration -> Sales -> Tax -> In the "Display Shipping Price" tab, we can specify whether to show shipping prices including or excluding tax. As seen in screenshot 1, I've set the "Display Shipping Price" option to "Including Tax." Consequently, in screenshot 2, the shipping price is displayed including tax on the sales-order_invoice-view page. However, when we print the order in PDF format from this page, the shipping price is shown as excluding tax, which is incorrect. It should be displayed as per tax configuration and similar to the sales-order_invoice-view page because we are printing the page. You can view the printed PDF in screenshot 3.

**Screenshot-1:**
![image](https://github.com/magento/magento2/assets/124759248/bf38ce41-1445-4d4c-b3c4-0830c5ac661d)

**Screenshot-2:**
![image](https://github.com/magento/magento2/assets/124759248/ee7781d4-f833-4d0f-813f-d8ec5d3d970a)

**Screenshot-3:**
![image](https://github.com/magento/magento2/assets/124759248/c9b3eb06-81e3-41e0-a1ce-762f81f45143)

### Manual testing scenarios (*)
1:  Navigate to  Admin->Store->Sales->Tax and Select the option as shown in screenshot 4 &5
**Screenshot-4:**
![image](https://github.com/magento/magento2/assets/124759248/e99c3c0e-b620-4686-8c78-054d90f35ce5)

**Screenshot 5:**
![image](https://github.com/magento/magento2/assets/124759248/4c3cd2cb-2c17-4f98-b65d-b61b105c721e)

2: create a one tax rule you can see the screenshot 6 i have created one tax rule with 25% tax rate
**Screenshot-6:**
![image](https://github.com/magento/magento2/assets/124759248/6ccdda47-b72f-4a23-a2bc-8822c91259d1)

3:Now order one product from the frontend 
4:Now navigate to admin side and create a invoice of that order 
5:Now, navigate to Sales -> Invoice and view the invoice you created. 
6:now print the order from invoice page as you can see the diffrence of the shipping price in the sales-order_invoice-view page and in the pdf as depricated in screenshot 2 & 3.

### Expected result (*)
The shipping charges should be shown the same way they are displayed on the sales-order_invoice-view page since we are printing the page.

### Actual result (*)
The shipping charges are displayed differently on the PDF compared to the sales order invoice view page

### Aditional information 
 The file public_html/app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php is responsible for the content seen in the printed PDF. The logic for displaying shipping charges is found in lines 607 to 610 of this file. However, there is no logic implemented to show shipping charges according to the configuration settings. On the other hand, in public_html/app/code/Magento/Sales/view/adminhtml/templates/order/invoice/create/form.phtml, the logic is implemented to fetch the configuration and then display the shipping charges accordingly on the sales-order_invoice-view page. You can see the logic of form.phtml in Screenshot 7, where shipping charges are displayed according to the configuration. However, in AbstractPdf.php, there is no such logic implemented, and only the shipping price excluding tax is shown, as depicted in Screenshot 8.
 
 **Screenshot 7:**
![image](https://github.com/magento/magento2/assets/124759248/21138f5a-f79d-41b0-9140-d03c72aa2d8b)

**Screenshot-8:**
![image](https://github.com/magento/magento2/assets/124759248/95976512-ea35-4e52-a07e-be2336963461)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38608: Shipping price showing diffrent in printed pdf

2024-04-09 12:16 UTC, DhruvBasan commented
@magento run all tests

2024-04-10 13:53 UTC, engcom-Hotel commented
@magento create issue

2024-05-30 05:40 UTC, engcom-Hotel commented
@magento run all tests

2024-05-30 12:36 UTC, engcom-Hotel requested changes
Hello @DhruvBasan,

Thanks for the contribution!

Please check the below review comments, for Backward compatibility, please mark the newly added parameters to null in constructor and  use ObjectManager to initialize those.

Also please check the failed tests, it seems they are failing due to code changes.

Thanks

2024-05-30 12:36 UTC, engcom-Hotel commented on app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php
> +    protected $taxHelper;
Make this variable as `private`

2024-05-30 12:36 UTC, engcom-Hotel commented on app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php
> +        TaxHelper $taxHelper,
Make this `null` by default to maintain backward compatibility.

2024-05-30 12:36 UTC, engcom-Hotel commented on app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php
> +        $this->taxHelper = $taxHelper;
Use the ObjectManager to initialize this variable.

2024-05-30 12:36 UTC, engcom-Hotel commented on app/code/Magento/Sales/Model/Order/Pdf/Creditmemo.php
> +        \Magento\Tax\Helper\Data $taxHelper,
Make this `null` by default

2024-05-30 12:36 UTC, engcom-Hotel commented on app/code/Magento/Sales/Model/Order/Pdf/Creditmemo.php
> +            $taxHelper,
initialize $taxHelper with ObjectManager

2024-05-31 10:23 UTC, engcom-Charlie commented
Hi @DhruvBasan,

Thank you for your contribution!

To proceed this PR further, we need green build. Can you please have a look into Functional CE, Static, Unit, Integration, SVC test failures.


Thank you!

2024-06-03 06:17 UTC, engcom-Charlie commented
Hi @DhruvBasan,

Thank you for your contribution!

Did you get time to work on the changes.

Thank you!

2024-06-03 10:29 UTC, DhruvBasan commented
@engcom-Hotel  @engcom-Charlie I have made the changes to the files as per your suggestions. Kindly review them.

2024-06-04 05:41 UTC, engcom-Hotel commented
@magento run all tests

2024-06-04 08:33 UTC, engcom-Hotel requested changes
Thanks @DhruvBasan, for quick workaround, but it seems the failed tests are due to code changes. I Request you to please fix them.

Thanks

2024-06-11 06:54 UTC, engcom-Charlie commented
Hi @DhruvBasan,

Thank you for your contribution!

Did you get time to work on the build failures.

Thank you!

2024-06-18 08:35 UTC, engcom-Bravo commented
Hello,

Internal team has started to work on it

Thanks.

2024-07-05 07:35 UTC, engcom-Bravo commented
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11798 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11798&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

2024-07-05 07:35 UTC, closed without merging