Accessibility: WAI-ARIA roles nesting wrong in menu
magento/magento2 pull request #38617
Opened 2024-04-14 15:44 UTC by mirianfalconi

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35889

### Manual testing scenarios (*)

1. Open the Lighthouse and do the Accessibily analysis **without** this PR 

![Screenshot from 2024-04-14 11-52-16](https://github.com/magento/magento2/assets/13924647/7816dffd-ce95-424c-92c3-d398ff97ad05)

2. Open the Lighthouse and do the Accessibily analysis **with** this PR 

![Screenshot from 2024-04-14 11-56-37](https://github.com/magento/magento2/assets/13924647/7c3d368c-57d4-47ae-a953-4b680c7d1aa6)

2024-04-14 15:52 UTC, mirianfalconi commented
@magento run all tests

2024-05-09 16:36 UTC, Franciscof-Serfe commented on app/code/Magento/Theme/Block/Html/Topmenu.php
> +            $html .= '<a href="' . $child->getUrl() . '" ' . $outermostClassCode . ' role="menuitem"><span>' . $this->escapeHtml(
```suggestion
            $html .= '<a href="' . $child->getUrl() . '" '
            . $outermostClassCode
            . ' role="menuitem"><span>'
            . $this->escapeHtml(
```

To fix coding standard:

FILE: /var/www/html/app/code/Magento/Theme/Block/Html/Topmenu.php
-------------------------------------------------- --------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-------------------------------------------------- --------------------
 249 | WARNING | Line exceeds 120 characters; contains 129 characters

2024-05-13 13:51 UTC, mirianfalconi commented
@magento run all tests

2024-05-13 20:20 UTC, mirianfalconi commented
@magento run all tests

2024-09-11 13:50 UTC, Franciscof-Serfe commented
@magento give me test instance

2024-09-11 14:24 UTC, Franciscof-Serfe commented
![image](https://github.com/user-attachments/assets/dab063be-62b6-4159-bf5a-3a26e6df3cf9)

2025-06-30 08:51 UTC, engcom-Hotel commented
@magento run all tests

2025-06-30 11:38 UTC, engcom-Hotel requested changes
Hello @mirianfalconi,

Thanks for the collaboration!

The changes seems good to us. But please fix the failed static tests.

Thanks

2025-07-01 15:47 UTC, mirianfalconi commented
@magento I'm working on it

2025-07-01 19:50 UTC, mirianfalconi commented
@magento run all tests

2025-07-02 19:07 UTC, mirianfalconi commented
@magento run all tests

2025-07-02 19:25 UTC, mirianfalconi commented
@magento run all tests

2025-07-03 08:24 UTC, engcom-Hotel approved these changes

2025-07-07 09:36 UTC, engcom-Bravo commented
@magento create issue

2025-07-07 09:56 UTC, engcom-Bravo commented
Hi @mirianfalconi,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Open the Lighthouse and do the Accessibily analysis


**Before:** :heavy_multiplication_x: 


<img width="1431" alt="Screenshot 2025-07-07 at 3 00 45 pm" src="https://github.com/user-attachments/assets/3fdf5097-9fe5-4558-a87d-2a98315a60d1" />











**After:** :heavy_check_mark: 


<img width="1431" alt="Screenshot 2025-07-07 at 3 21 05 pm" src="https://github.com/user-attachments/assets/2fb528ed-12fd-4243-bbac-e1c98eec80ed" />




Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-07-08 07:40 UTC, engcom-Dash commented
@magento run all tests

2025-07-09 05:23 UTC, engcom-Dash commented
@magento run all tests

2025-07-09 10:19 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests, WebAPI Tests

2025-07-09 13:05 UTC, engcom-Dash commented
The consistent **Functional B2B** Tests failure is known issue and Jira has been raised for the same. Other failures are inconsistent and flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38617/303e929bf9415c637363a3102324ffc8/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/aa8bd970-5ff1-4a55-93e1-e2e673f3923c)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38617/4979a069a59cfa0051c3748ef715e0fc/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/fcd8aa47-306e-46b6-9dd5-e050f509b130)

Known Issue: StorefrontProductNoLongerVisibleInWishlistOnceUserUnassignedFromCompanyTest [ACQE-8287](https://jira.corp.adobe.com/browse/ACQE-8287)

Hence moving this PR in Merge In Progress.

2025-07-28 08:30 UTC, engcom-Charlie commented
@magento run all tests

2025-07-28 08:32 UTC, engcom-Charlie commented
The PR was giving failures on copyright in mainline PR, hence moving it to Extended Testing.

2025-07-28 08:33 UTC, engcom-Charlie commented
Updated the copyright year.

2025-07-28 08:33 UTC, engcom-Charlie commented
@magento run all tests

2025-07-28 08:47 UTC, engcom-Charlie commented
@magento run all tests

2025-07-28 20:26 UTC, mirianfalconi commented
@magento run all tests

2025-07-29 05:05 UTC, engcom-Charlie commented
@magento run all tests

2025-07-29 08:49 UTC, engcom-Charlie commented
@magento run all tests

2025-07-29 13:08 UTC, engcom-Charlie commented
@magento run Static Tests

2025-07-30 05:00 UTC, engcom-Charlie commented
@magento run all tests

2025-07-30 09:34 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2025-07-30 14:26 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests, WebAPI Tests

2025-07-31 05:50 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2025-07-31 09:10 UTC, engcom-Charlie commented
One Functional B2B test failure is consistent in recent 2 builds and its a known issue. Rest of the failures are neither part of PR now failing because of this PR changes.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38617/82ee0fb5e04e040b6bae3946521c9ed0/Functional/allure-report-b2b/index.html#categories

<img width="1160" height="291" alt="image" src="https://github.com/user-attachments/assets/3c265d74-2ead-4ce8-85f8-3fc33ef4872f" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38617/88c8c380c3f3135b8679bb88b0357812/Functional/allure-report-b2b/index.html#categories/6759f0a4e1529a056bf838dd27da1967/7ef1d58bcc955c23/

<img width="1152" height="538" alt="image" src="https://github.com/user-attachments/assets/d62975e9-af1e-4384-9217-f1e21298ede3" />

**Known Issue:**
[ACQE-8335](https://jira.corp.adobe.com/browse/ACQE-8335): AdminChangeAllCustomersGroupViaGridTest

The Integration failure is a known issue. Hence moving this PR to Merge in Progress.

**Known issue:** 
[AC-15240](https://jira.corp.adobe.com/browse/AC-15240)

2025-08-04 06:11 UTC, merged