Enabling Individual Editing of Shipping and Billing Addresses from the Customer Dashboard
magento/magento2 pull request #38677
Opened 2024-04-30 01:58 UTC by Franciscof-Serfe

### Description (*)
We propose an enhancement to the Magento customer dashboard's address management functionality. 
Currently, when adding an address, it defaults to both billing and shipping. However, distinguishing between them becomes confusing for clients, as editing one address impacts both. **_This native workflow requires generating a new address to differentiate between default shipping or billing_**. Our enhancement streamlines this process by **_allowing direct individual editing of billing and shipping addresses,_** thereby simplifying the user experience for logged-in clients.

Video 1: "Native Magento Flow: Editing Billing and Shipping Addresses"
[NativeMagento.webm](https://github.com/magento/magento2/assets/115582581/d9851c8a-8966-4a3a-90b1-6cb4315edece)

Video 2: "Improvement Proposal: Individual Editing of Billing and Shipping Addresses"
[addressImprovement.webm](https://github.com/magento/magento2/assets/115582581/30996b4a-0e13-4ca8-bcd3-1c8f5b01eaf2)

### Manual testing scenarios (*)

1. Navigate to the customer dashboard.
2. Add a new address and verify that it defaults to both billing and shipping.
3. Edit the address and observe that both billing and shipping are affected.
4. Apply this pull request's changes and verify that individual editing of billing and shipping addresses is possible without affecting the other.

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-04-30 02:06 UTC, Franciscof-Serfe commented
@magento I'm working on it
@magento report the issue
@magento run all tests

2024-04-30 02:10 UTC, Franciscof-Serfe commented
@magento create issue

2024-04-30 15:14 UTC, Franciscof-Serfe commented
@magento run all tests

2024-06-21 03:03 UTC, Franciscof-Serfe commented
@magento run all tests

2024-08-12 19:07 UTC, Franciscof-Serfe commented
@magento run all tests

2024-08-13 15:01 UTC, Franciscof-Serfe commented
**PR status update:** 
The branch is updated

1. Semantic version checker failure. 
Should I modify the commits message to adjust this pipe or are no actions required from my side?

2. Functional Tests falling, the changes added are not related.

**Test:** 
* Create new user from /customer/account/create/ 
* Add new address. The first will be added to both billing and shipping addresses and you can edit each other individually.
**VIDEO:**
[TestingFlow.webm](https://github.com/user-attachments/assets/08429f19-3dbe-4959-8a99-1926b9c85827)


@ihor-sviziev , @engcom-Bravo , @engcom-Delta Can you move forward with this? Thanks.

2025-04-11 06:22 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe,

Kindly resolve the PR conflicts so we can proceed with further processing. In the meantime, we are moving this PR to "On Hold."

Thanks

2025-04-11 15:27 UTC, Franciscof-Serfe commented
@magento give me 2.4-develop instance

2025-04-15 14:03 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-15 14:10 UTC, Franciscof-Serfe commented
Hi @engcom-Hotel, 
This PR has been updated for merging. I apologize for the delay on my part. 

The test status review is available in this comment:   
https://github.com/magento/magento2/pull/38677#issuecomment-2286474971 

Please let me know if you need any further action from me. 
Regards, 
Fran

2025-04-15 15:48 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-15 18:11 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-15 20:48 UTC, markshust requested changes
May be a little typo here?

2025-04-15 20:48 UTC, markshust commented on app/code/Magento/Customer/view/frontend/templates/address/book.phtml
> +                    <address>g
Is this `g` expected to be here?

2025-04-15 21:05 UTC, Franciscof-Serfe commented on app/code/Magento/Customer/view/frontend/templates/address/book.phtml
> +                    <address>g
Yhep. Thanks

2025-04-15 21:07 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-16 09:40 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe,

Thanks for the contribution!

Since this PR contains a new feature, we are marking this PR as a `Feature Request` and sent a mail to PO for the approval. Please allow us time, till we get the approval. In the meantime we are moving this PR `On Hold`.

Thanks

2025-04-16 12:07 UTC, Franciscof-Serfe commented
Hi @engcom-Hotel ,
Just to clarify — Why is this PR considered a new feature?

I’d see something like adding profile pictures to customer accounts or address validation as a new feature. But in this case, the **"Change Billing Address" and "Change Shipping Address" buttons already existed**. This PR simply fixes them so they work as expected.

Thanks for reviewing and helping to clarify this.

Best regards,
Francisco

2025-04-17 19:50 UTC, markshust commented
@engcom-Hotel I agree with @Franciscof-Serfe, this is a UI improvement so things work as expected, not a new feature.

2025-04-21 09:49 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe @markshust,

Since this PR enhances an existing feature of Magento and is not a bug, we have classified it as a `feature request`. The related [issue](https://github.com/magento/magento2/issues/38678#issuecomment-2090691912) has also been marked as a feature request.

This change will impact the user experience, which is why we require PO approval to proceed further.

Rest assured, we are actively working on this PR and will provide you with updates shortly.

Thanks

2025-04-21 13:42 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-25 01:47 UTC, Franciscof-Serfe commented
@magento run static tests

2025-04-25 03:48 UTC, Franciscof-Serfe commented
@magento run static test

2025-04-25 10:26 UTC, Franciscof-Serfe commented
@magento run all test

2025-04-25 13:22 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-27 15:16 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-28 14:17 UTC, Franciscof-Serfe commented
@magento run all tests

2025-04-30 05:34 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe,

The approval on this feature request has been received from the PO. Hence moving further with the PR.

Thanks

2025-04-30 05:37 UTC, engcom-Hotel commented
@magento run all tests

2025-04-30 15:15 UTC, engcom-Hotel requested changes
Hello @Franciscof-Serfe,

Thanks for the contribution!

Please refer to the below review comments, and it seems some functional tests are failing due to this change, please fix them as well.

Also please add some automated test for this PR change.

Thanks

2025-04-30 15:15 UTC, engcom-Hotel commented on app/code/Magento/Customer/Block/Address/Edit.php
> +        $queryParams = ['_secure' => true];
I guess we can simplified this section as follows:

```
$queryParams = ['_secure' => true];

// Consolidate $defaultShipping and $defaultBilling conditions
if ($defaultShipping == 1) {
    $queryParams['default_shipping'] = 1;
}
if ($defaultBilling == 1) {
    $queryParams['default_billing'] = 1;
}

// Add 'id' parameter only if the address is not both default billing and shipping
if (!$this->getAddress()->isDefaultBilling() || !$this->getAddress()->isDefaultShipping()) {
    $queryParams['id'] = $this->getAddress()->getId();
}

// URL construction remains in a single block
$postURL = $this->_urlBuilder->getUrl(
    'customer/address/formPost',
    $queryParams
);
```

Just a sample code, just check the condition before implementing the same.

2025-04-30 15:15 UTC, engcom-Hotel commented on app/code/Magento/Customer/Block/Address/Edit.php
> +    public function getSaveUrl($defaultShipping = 0, $defaultBilling = 0)
Maintain backward compatibility for the getSaveUrl method by deprecating the old method and introducing a new one

2025-05-02 00:49 UTC, Franciscof-Serfe commented
@magento run all tests

2025-05-08 06:34 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe,

It seems the automated tests are still failing due to the changes please check those as well and please add some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

2025-05-08 12:26 UTC, Franciscof-Serfe commented
Hi @engcom-Hotel , 
 Sorry for the delay. I'm aware of the pending fixes. 
I’ll get back to finishing this contribution as soon as I have some time available.

Regards,
Francisco

2025-05-21 13:25 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe,

Have you got a chance to look into the remaining failures?

Thanks

2025-06-10 15:34 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe,

Have you got a chance to look into this PR?

Thanks

2025-06-10 15:38 UTC, Franciscof-Serfe commented
Hi @engcom-Hotel , 
 I will try to make time this week to review and update this MR.

Regards, 
Francisco

2025-06-23 07:36 UTC, engcom-Hotel commented
Hello @Franciscof-Serfe,

Gentle reminder to look into this PR.

Thanks

2025-07-09 13:33 UTC, engcom-Dash commented
@magento run all tests

2025-07-10 07:36 UTC, engcom-Dash commented
@magento run all tests

2025-07-10 11:53 UTC, engcom-Dash commented
Hello @Franciscof-Serfe,

We’ve noticed that the current changes are causing some functional test failures. Additionally, the multi-checkout address functionality  is breaking due to the modifications introduced in the PR. Also the changes are not working with Magento Enterprise Edition.
 
Could you please take a look and address the issue. Till then we’re marking this PR as a draft and moving it to on hold status. Once you're able to revisit and fix the issues, feel free to mark it as ready for review again.

Thanks!

2025-08-11 05:04 UTC, engcom-Dash commented
Hi @Franciscof-Serfe 

We appreciate your contribution and the effort you've put into this pull request. We waited for an extended period for the functional issues to be addressed.

As a result, we are closing this PR for now. If you’d like to revisit and fix the functional failures, please feel free to reopen the PR with the necessary updates.

Thanks again for your contributions!

2025-08-11 12:36 UTC, markshust commented
@engcom-Dash can you reopen this issue and assign it to me? I can take it in.

2025-08-11 12:42 UTC, engcom-Dash commented
Hello @markshust,

I have reopened this PR. you can resume your work on this.

Thanks!

2025-11-06 07:47 UTC, engcom-Dash commented
Hello @markshust,

We appreciate your contribution!

Since we haven't received a response from you for an extended period, we are closing this PR for now.

Whenever you're ready to resume work on this, please feel free to reopen it or request us to do so. We'll be more than happy to assist you.

Thanks once again!

2025-11-06 07:47 UTC, closed without merging