Update Store.php
magento/magento2 pull request #38717
Opened 2024-05-13 21:05 UTC by thomas-kl1

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-05-14 08:56 UTC, thomas-kl1 commented
@magento run Unit Tests

2024-05-14 12:12 UTC, thomas-kl1 commented
@magento run all tests

2024-05-14 20:18 UTC, thomas-kl1 commented
@magento run all tests

2024-05-14 21:42 UTC, thomas-kl1 commented
Failures are not related to current changes.

2025-05-15 05:30 UTC, engcom-Hotel commented
@magento run all tests

2025-05-15 10:58 UTC, engcom-Hotel requested changes
Hello @thomas-kl1,

Thanks for the collaboration!

Please fix the failed static test, other failures seems flaky to me. Also update or add unit tests to cover scenarios where `isCurrentlySecure()` is called for different store scopes.

Thanks

2025-05-15 11:01 UTC, thomas-kl1 commented
@engcom-Hotel it says that copyright must be updated, could you tell me which one should I use?

2025-05-15 11:09 UTC, engcom-Hotel commented
Hello @thomas-kl1,

Currently the copyright is showing something like below:

```
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
```

We need to update it something as below:

```
/**
* Copyright [Year file created] Adobe
* All Rights Reserved.
*/
```

2025-05-16 14:31 UTC, thomas-kl1 commented
@magento run all tests

2025-05-21 13:37 UTC, engcom-Hotel commented
Hello @thomas-kl1,

As per this https://github.com/magento/magento2/pull/38717#pullrequestreview-2843251085, please update/add the Unit test as well.

Thanks

2025-05-26 10:56 UTC, engcom-Dash commented
Hello @thomas-kl1 

I wanted to check if you are working on the automated unit test coverage. If not, Can I take care of them? Just let me know what works best for you.

Thanks!

2025-05-26 11:59 UTC, thomas-kl1 commented
Hello @engcom-Dash 
Feel free to contribute the unit test as I've didn't started! 
Thanks for proposing!

Regards,

2025-05-27 08:00 UTC, engcom-Dash commented
@magento run all tests

2025-05-27 10:45 UTC, engcom-Dash commented
Hello @engcom-Hotel  As per review comment, I have updated the Unit tests for the changes done in this PR. Please review the changes.

Thanks!

2025-05-28 06:54 UTC, engcom-Hotel approved these changes

2025-05-28 09:10 UTC, engcom-Dash commented
@magento run all tests

2025-05-28 12:12 UTC, engcom-Dash commented
@magento create issue

2025-05-28 13:25 UTC, engcom-Dash commented
@thomas-kl1  Thank you for the contribution & collaboration!

<h3> ✔️  QA Passed</h3>

Before:

`$secureBaseUrl = $this->_config->getValue(self::XML_PATH_SECURE_BASE_URL, ScopeInterface::SCOPE_STORE);`
`$secureFrontend = $this->_config->getValue(self::XML_PATH_SECURE_IN_FRONTEND, ScopeInterface::SCOPE_STORE);
`

After:

`$secureBaseUrl = $this->_config->getValue(self::XML_PATH_SECURE_BASE_URL, ScopeInterface::SCOPE_STORE, $this->getId());`
`$secureFrontend = $this->_config->getValue(self::XML_PATH_SECURE_IN_FRONTEND, ScopeInterface::SCOPE_STORE, $this->getId());
`

By looking at the code changes, it make sense that Instead of relying on Magento's global context to determine the current store, it explicitly passes the store ID ($this->getId()) to the getValue() method to avoid global context resolution. By passing the store ID directly, Magento skips the logic to resolve the current store leads to performance improvement.

Some of the builds are failing hence moving this PR in Extended Testing.

2025-05-29 05:49 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2025-05-29 09:17 UTC, engcom-Dash commented
The consistent test failures for **Functional B2B** are known Issues and JIRA is raised for them.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38717/5e68b04fbb3659bc7ef7cf69169d53ee/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/f77795f9-3120-48ac-b376-9d9ecd83980b)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38717/25576e9260329ebaaccd3de4746bcc47/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/8222e0eb-c1ec-4314-9b11-d3329a9cfcf8)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)
StoreFrontSimpleProductWithSpecialAndTierDiscountPriceTest : [ACQE-7971](https://jira.corp.adobe.com/browse/ACQE-7971)
OrderWithMultipleConfigurableProductsAdditionalStockTest : [ACQE-8060](https://jira.corp.adobe.com/browse/ACQE-8060)

The consistent test failures for **Functional CE** is known Issues and JIRA is raised for the same. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38717/c5c3d6de76be2d1ddb6ea5ea07a179c4/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/1f97e11a-43d6-4004-ae63-bf36252c87e5)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38717/1a55e2d062de177195a446db652b185d/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/d012a7e3-757f-4f14-af70-b5113dc2c6a6)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

The consistent test failure for **Functional EE** is known Issues and JIRA is raised for the same. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1:https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38717/3e0678658d81029dec691947a3884348/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/9044453e-36fb-4e58-9178-9f0433f0cbff)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38717/f8e698cc42082ecd836fb8c863c29bb6/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/cc37daa7-05c0-422a-b8e8-a6432e6266b2)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

Hence moving this PR in Merge In Progress.

2025-06-26 11:02 UTC, merged