Compatible with colinmollenhour/php-redis-session-abstract v1.6.0
magento/magento2 pull request #38729
Opened 2024-05-16 04:36 UTC by TuVanDev

This pull request resolves the compatibility issues with `colinmollenhour/php-redis-session-abstract` [v1.6.0](https://github.com/colinmollenhour/php-redis-session-abstract/releases/tag/v1.6.0).
More details will be added to the description soon.

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38728 

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-05-16 04:49 UTC, TuVanDev commented
@magento run all tests

2024-05-16 07:15 UTC, hostep commented
Hmm, let's hold on a bit and see what the response is from https://github.com/colinmollenhour/php-redis-session-abstract/issues/58, I'm pretty sure the change will be reverted, maybe they'll release a 2.0.0 with this change, and then we can implement this fix ...

2024-05-16 19:20 UTC, haroonsulahri commented
I have been facing the same issue recently on my site when I updated her composer then I started getting this error while running the compilation command.

2024-05-21 09:29 UTC, hostep commented
So, since version 1.7.0 of `colinmollenhour/php-redis-session-abstract` has been released (which has the same code as 1.5.5) and version 2.0.0 now is the same as 1.6.0, this PR should be updated and the constraints in the `composer.json` files should be changed to `^2.0` here:
- https://github.com/magento/magento2/blob/c89312182ef2e747b47348e9cd1f1148ba7af078/composer.json#L41
- https://github.com/magento/magento2/blob/c89312182ef2e747b47348e9cd1f1148ba7af078/lib/internal/Magento/Framework/composer.json#L26

@TuVanDev: could you do this? Thanks!

2024-05-23 11:45 UTC, TuVanDev commented
Thanks @hostep 

I've updated the `colinmollenhour/php-redis-session-abstract` dependency package to the latest version, `2.0`.

To the maintainers: Since the `Magento\Framework\Session\SaveHandler\Redis\Config` and `Magento\Setup\Model\ConfigOptionsList\Session` classes have not been updated for years, this PR may encounter failed tests due to the existing code. Unfortunately, I don't currently have the time to address this issue, so I would greatly appreciate it if someone could assist me with resolving it. Thank you!

2024-05-23 11:48 UTC, hostep commented
Thanks @TuVanDev, can you also update the title of the PR with the correct version? And maybe remove the patch instructions from the description, it's not longer relevant as a quick fix now that v1.7 is out. Thank you!

2024-05-29 05:51 UTC, engcom-Hotel commented
@magento run all tests

2024-05-29 11:28 UTC, engcom-Hotel requested changes
Hello @TuVanDev,

Thanks for the collaboration!

Please check the below review comment and also the automated tests failures. It seems the failures are due to code changes, mainly static test failures.

Thanks

2024-05-29 11:28 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Session/SaveHandler/Redis/Config.php
> +    public function getRetries()
Please add the return type for this method.

2024-06-09 08:50 UTC, TuVanDev commented
@hostep I've updated the title to match the new version of `colinmollenhour/php-redis-session-abstract`. Regarding the patches, I believe it is definitely helpful for someone who would like to apply the connection retries before it becomes available in the Magento codebase, so I'll keep it as it is.

Thanks for suggestions.

2024-06-09 09:04 UTC, TuVanDev commented on lib/internal/Magento/Framework/Session/SaveHandler/Redis/Config.php
> +    public function getRetries()
Hi @engcom-Alfa , this method is similar to other methods in the Config class. If we add the return type to this method, we should also add the return types to other methods for code consistency.
```
    /**
     * @inheritdoc
     */
    public function getPassword()
    {
        return $this->deploymentConfig->get(self::PARAM_PASSWORD);
    }
    /**
     * @inheritdoc
     */
    public function getTimeout()
    {
        return $this->deploymentConfig->get(self::PARAM_TIMEOUT);
    }

    /**
     * @inheritdoc
     */
    public function getRetries()
        {
        return $this->deploymentConfig->get(self::PARAM_RETRIES);
    }
```
I understand that the changes in this pull request may result in failed tests, as the classes `Magento\Framework\Session\SaveHandler\Redis\Config` and `Magento\Setup\Model\ConfigOptionsList\Session` have not been updated for years. Unfortunately, I don't currently have the time to address this issue, so I would greatly appreciate it if someone could assist me with resolving it.

2024-06-17 10:51 UTC, engcom-Hotel commented
Hello @TuVanDev,

Please resolve the conflicts of this PR, so that we can move further with this.

Meanwhile marking this PR as draft.

Thanks

2024-06-20 06:44 UTC, engcom-Bravo commented
Hello,

 Internal Team will pick this PR sooner and will work on the failures and ensure the compatibility of library with latest version.


Thanks.

2024-09-03 15:23 UTC, merged