Fix typo
magento/magento2 pull request #38809
Opened 2024-06-06 15:20 UTC by artttj

### Description (*)

Fix the typo in the PHPDoc comment for:

```
\Magento\ConfigurableProduct\Block\Product\View\Type::_getAdditionalConfig()
```

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-06-06 15:22 UTC, artttj commented
@magento run all tests

2024-06-06 15:43 UTC, artttj commented
@magento run all tests

2024-08-05 12:30 UTC, artttj commented
@magento run all tests

2024-08-30 16:37 UTC, artttj commented
@magento run all tests

2025-06-27 09:15 UTC, engcom-Hotel commented
@magento run all tests

2025-06-27 12:59 UTC, engcom-Hotel requested changes
Hello @artttj,

Thanks for the contribution!

As I can see in this PR, you have tried to fix some typos but we have some static test failures. We request you to fix those. 

Other failures seems flaky to me.

Thanks

2025-06-30 08:29 UTC, engcom-Dash commented
Hello @artttj 

I wanted to check if you are working on the static failures. If not, Can I take care of them? Just let me know what works best for you.

2025-07-01 08:11 UTC, engcom-Dash commented
Hello @artttj  I am taking care of the changes. Thank You!

2025-07-01 08:15 UTC, engcom-Dash commented
@magento run all tests

2025-07-01 10:41 UTC, engcom-Dash commented
@engcom-Hotel I have fixed the static failures. Other failures are not related to this PR changes hence moving this PR for review.

2025-07-02 10:50 UTC, engcom-Hotel approved these changes

2025-07-02 10:53 UTC, artttj commented
> @engcom-Hotel I have fixed the static failures. Other failures are not related to this PR changes hence moving this PR for review.

Thanks for resolving, I appreciate it!

2025-07-04 10:07 UTC, engcom-Bravo commented
Hi @artttj,


Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-07-04 10:10 UTC, engcom-Bravo commented
@magento create issue

2025-07-04 10:54 UTC, engcom-Dash commented
@magento run all tests

2025-07-07 05:17 UTC, engcom-Dash commented
@magento run all tests

2025-07-07 11:05 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2025-07-07 13:11 UTC, engcom-Dash commented
The consistent **Functional B2B** Tests failure is known issue and Jira has been raised for the same. Other failures are inconsistent and flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38809/1112b7f0a864e9f9477c9307b2efd19b/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/91f7a00b-c22c-4746-a487-7fc84c986731)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38809/308fb65189ccbeb2751f3ff22143f866/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/63894907-03d9-4b03-9b8d-5d272d265655)

Known Issue: StorefrontProductNoLongerVisibleInWishlistOnceUserUnassignedFromCompanyTest [ACQE-8287](https://jira.corp.adobe.com/browse/ACQE-8287)

The **Functional EE** failures are inconsistent and flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38809/b7e6412fff40d0e4e1eb49b640aed50f/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/d397b399-a2c4-4646-b6fd-845ce2057a64)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38809/bf65c242189680c6b719e0b707abea40/Functional/allure-report-ee/index.html#categories/bdbf199525818fae7a8651db9eafe741

![image](https://github.com/user-attachments/assets/dc31119a-d46d-4581-97e6-3bc5bce06002)

Hence moving this PR in Merge In Progress.

2025-07-08 07:53 UTC, engcom-Dash commented
@magento run all tests

2025-07-09 05:28 UTC, engcom-Dash commented
@magento run all tests

2025-07-09 09:02 UTC, engcom-Dash commented
Hi @artttj ,

Thank you for your contribution! I just wanted to let you know that your pull request is now in the merge in progress stage. From this point onward, our team will take care of the remaining steps.

No further action is required from your end.

Thanks!

2025-08-07 18:24 UTC, merged