Fix issue when compiling statics with multiple jobs
magento/magento2 pull request #38842
Opened 2024-06-19 08:21 UTC by mrodespin

Patch to fix open Magento issue https://github.com/magento/magento2/issues/38799

2024-07-09 12:47 UTC, jellesiderius commented
Can confirm that this fixes my issues.

2024-07-12 11:50 UTC, monteshot commented
@magento run all tests

2024-08-20 12:20 UTC, ihor-sviziev approved these changes

2024-08-20 12:44 UTC, engcom-Hotel requested changes
Hello @mrodespin,

Thanks for the collaboration!

Please refer to my review comment below.

Thanks

2024-08-20 12:44 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php
> +            if (!empty($this->_config['port'])) {
Can we add a check here if the port is not already set with localhost then only perform this action:
```suggestion
            if (!empty($this->_config['port']) && strpos($this->_config['host'], ':') === false) {
```

2024-08-21 15:08 UTC, ihor-sviziev approved these changes

2024-08-22 06:26 UTC, engcom-Bravo commented
@magento run all tests

2024-08-22 07:30 UTC, engcom-Hotel approved these changes

2024-08-22 09:40 UTC, engcom-Bravo commented
Hi @mrodespin,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**


- Go to env.php
- Set the port information to the host in the db connection. e.g. db['connection']['default']['host'] = 'localhost:3306'
- Execute ./magento.sh setup:static-content:deploy


**Before:** :heavy_multiplication_x: 


<img width="1410" alt="Screenshot 2024-08-22 at 12 23 47" src="https://github.com/user-attachments/assets/bdc8918b-807c-48cd-94d8-70c2b4f9f9d6">



**After:** :heavy_check_mark: 


<img width="1410" alt="Screenshot 2024-08-22 at 13 32 33" src="https://github.com/user-attachments/assets/52e4bbd4-7f75-4490-bc75-d63c92ce2f19">



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

2024-08-25 11:41 UTC, engcom-Charlie commented
@magento run all tests

2024-08-26 06:04 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2024-08-26 09:04 UTC, engcom-Charlie commented
The Functional B2B and EE failures in recent 2 builds are known issues and not related to the PR changes hence moving this PR to Merge In Progress.

**Functional B2B**
**Run 1:**  
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38842/1848ea78770547fa01e0c248208b0494/Functional/allure-report-b2b/index.html#categories/e89a2ef77b192fa659586970627a6e4a/3fee4ef775faff28/

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/034d7e7c-f44d-4f72-993d-023041125b8f">


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38842/fb6fb189ab0db3ae415a94d68f159b02/Functional/allure-report-b2b/index.html#categories/e89a2ef77b192fa659586970627a6e4a/f6d6cdc83faabb49/

<img width="1241" alt="image" src="https://github.com/user-attachments/assets/50bb08b5-08bd-42be-aed6-5e4d6a45cb23">


**Functional EE**
**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38842/193e47cecbabff724bf8865e273822b9/Functional/allure-report-ee/index.html#categories

<img width="1254" alt="image" src="https://github.com/user-attachments/assets/f65a5177-60a3-42c9-bce3-44355b78ff69">

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38842/0923be2ff0cf4098bebd1a906fdf7cf7/Functional/allure-report-ee/index.html#categories/5c3e33efaf655a884aa27c9147cb6ca1/17474efe84ca217c/

<img width="1253" alt="image" src="https://github.com/user-attachments/assets/599db9cd-7f4a-49ec-90ea-2ca95fadc3f2">


**Known issues :**
EE: StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)
B2B: AdminCreateDraftQuoteFromQuoteGridPageTest: [#ACQE-6309](https://jira.corp.adobe.com/browse/ACQE-6309)

2024-09-05 13:38 UTC, merged