Clean eav set cache after Set save or Set delete
magento/magento2 pull request #38864
Opened 2024-06-23 17:32 UTC by MaximGns

### Description (*)
Clean specific eav cache after an attribute set is update or deleted

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38827

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-06-24 06:18 UTC, MaximGns commented
@magento run tests

2024-06-24 14:09 UTC, MaximGns commented
@magento run tests

2024-06-30 12:41 UTC, MaximGns commented
@magento run tests

2024-07-04 18:09 UTC, MaximGns commented
@magento run tests

2024-07-04 18:56 UTC, hostep commented
@magento run all tests

2024-07-06 08:39 UTC, MaximGns commented
> @magento run all tests
> 
> (@MaximGns, I think you forgot the `all` keyword)

Damn... 😆

2025-12-19 06:41 UTC, engcom-Hotel commented
@magento run all tests

2025-12-22 12:20 UTC, engcom-Hotel requested changes
Hello @MaximGns,

Thank you for your contribution!

Please refer to the below review comments and also fix the failed static tests. Other failures seems flaky to me.

2025-12-22 12:20 UTC, engcom-Hotel commented on app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Set.php
> +     * @param null|int|string $setId
Add method description

2025-12-22 12:20 UTC, engcom-Hotel commented on app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Set.php
> +            $this->eavConfig->getCache()->remove($this->getCacheKey($object->getEntityId()));
I guess it should be `$object->getId()` instead of `$object->getEntityId()`

2026-01-20 13:05 UTC, engcom-Dash commented
@magento run all tests

2026-01-21 10:09 UTC, engcom-Dash commented
@magento run all tests

2026-01-21 18:30 UTC, engcom-Dash commented
@magento run Unit Tests

2026-01-21 18:33 UTC, engcom-Dash commented
> Hello @MaximGns,
> 
> Thank you for your contribution!
> 
> Please refer to the below review comments and also fix the failed static tests. Other failures seems flaky to me.

@engcom-Hotel  I’ve addressed the suggested review comments in the PR and fixed the static test failure related to cyclomatic complexity.

Could you please review the updated changes so we can proceed further?

2026-01-22 07:08 UTC, engcom-Hotel approved these changes
Failed test seems flaky to me. Hence approving the PR.

2026-01-23 10:23 UTC, engcom-Bravo commented
Hi @MaximGns,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Use the product bulk api.
- Create product with required attributes from the attribute set.
- Add new attribute to the used attribute set and save
- Import the product again using the bulk api having the new attribute in the payload




**Before:** :heavy_multiplication_x: 

<img width="1358" height="629" alt="Screenshot 2026-01-23 at 3 41 44 pm" src="https://github.com/user-attachments/assets/21b8727d-24bf-4a78-b28e-60ef9728f5b2" />


<img width="979" height="629" alt="Screenshot 2026-01-23 at 3 42 08 pm" src="https://github.com/user-attachments/assets/e5d6a64a-7ba0-4966-962e-01295a72794e" />



**After:** :heavy_check_mark: 


<img width="1320" height="640" alt="Screenshot 2026-01-23 at 3 49 07 pm" src="https://github.com/user-attachments/assets/c4005c18-b3fe-4842-9fd4-082d6cac35d3" />
<img width="908" height="640" alt="Screenshot 2026-01-23 at 3 49 34 pm" src="https://github.com/user-attachments/assets/695a7e39-b97d-4c0c-83a9-481fe1b22383" />





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

2026-01-27 05:38 UTC, engcom-Dash commented
@magento run all tests

2026-01-27 09:58 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2026-01-27 10:07 UTC, engcom-Dash commented
@magento run Unit Tests

2026-01-27 17:32 UTC, engcom-Dash commented
The consistent failures in Functional CE, B2B,EE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

CE
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38864/ddfec84eed0374fb247bea7529da90c8/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1644" height="316" alt="image" src="https://github.com/user-attachments/assets/6e54870c-787c-4d20-b5df-24c011779d36" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38864/2ddb2ba0ef7d9f266730a739c69ff0c5/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1651" height="192" alt="image" src="https://github.com/user-attachments/assets/8f9a30d4-c7a2-44fd-bcfa-c46549c88788" />

EE
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38864/f13b6d22cac315a4a96312f06cb10711/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1648" height="220" alt="image" src="https://github.com/user-attachments/assets/eb1e1506-3111-4e7c-801e-5bbc335fe1e7" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38864/fe9186f8bc5511d6d7d4e274a53fd097/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1660" height="147" alt="image" src="https://github.com/user-attachments/assets/885899a8-6426-4f90-adba-fb337f886217" />


B2B
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38864/dc31d2d223d8f92c0658a916a03a6e7e/Functional/allure-report-b2b/index.html#categories/b7007f03643f5636222c64635a0feb74/7f38e874c83eb35d/
<img width="1647" height="306" alt="image" src="https://github.com/user-attachments/assets/ddd207aa-0296-4ff8-b6ca-87e41b852ff2" />


Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38864/b6cb3b4a842087cd631e120f320eb862/Functional/allure-report-b2b/index.html#categories/b7007f03643f5636222c64635a0feb74/aa70ad9b8732facb/
<img width="1652" height="289" alt="image" src="https://github.com/user-attachments/assets/06354f0c-79c4-4447-a76d-68f8718bcae0" />

Unit Test 
[AC-16360](https://jira.corp.adobe.com/browse/AC-16360)

Known Issue
AdminCannotAccessStockImagesWithWrongCredentialsTest [ACQE-9092](https://jira.corp.adobe.com/browse/ACQE-9092)

Hence, Moving this PR to Merge In Progress

2026-02-10 16:48 UTC, merged