fix: Use Object Manager for ModeConfigured
magento/magento2 pull request #38886
Opened 2024-06-27 12:21 UTC by pmzandbergen

Fixing #38875 (AC-12299)

### Description (*)
Use Object Manager to create objects.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38875 (AC-12299)

### Manual testing scenarios (*)
N/A

### Questions or comments
Created this PR @glo24157 , feel free to modify or include with your changes. Also see comments at https://github.com/magento/magento2/commit/1b21cb81126d67b01bd01b4a39b7d1801dc68d0b

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-06-27 12:28 UTC, pmzandbergen commented
@magento run all tests

2024-07-08 12:02 UTC, Den4ik requested changes
Hi @pmzandbergen 
Thanks for contribution. Please rolling back type casting for `$reportOnly` argument

2024-07-08 12:02 UTC, Den4ik commented on app/code/Magento/Csp/Model/Mode/ConfigManager.php
> +            'reportOnly' => $reportOnly,
```suggestion
            'reportOnly' => (bool)$reportOnly,
```

2024-07-08 12:09 UTC, Den4ik commented
@magento run all tests

2024-07-08 17:54 UTC, Den4ik commented
@magento run Unit Tests

2024-07-09 17:50 UTC, Den4ik commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2024-07-11 09:44 UTC, Den4ik commented
@magento run Unit Tests, Functional Tests CE

2024-07-15 14:06 UTC, Den4ik commented
@magento run all tests

2024-07-16 13:40 UTC, pmzandbergen commented
> Please rolling back type casting for $reportOnly argument

@Den4ik do you want me to roll back the type casting (and why)? The failing tests don't seem to be relevant to this change.

2024-07-16 20:18 UTC, Den4ik commented
Failed tests seems are not related and looks strange that they are failed. Let's try one more time and compare results of failed tests

2024-07-16 20:19 UTC, Den4ik commented
@magento run all tests

2024-07-18 13:35 UTC, Den4ik commented
@magento run Unit Tests

2024-07-18 13:40 UTC, Den4ik requested changes
@pmzandbergen Could you please review my comment

2024-07-18 13:40 UTC, Den4ik commented on app/code/Magento/Csp/Model/Mode/ConfigManager.php
> +        $this->modeConfiguredFactory = $modeConfiguredFactory;
Could you please update new constructor parameter based on [Backward compatibility documentation](https://developer.adobe.com/commerce/contributor/guides/code-contributions/backward-compatibility-policy/#adding-a-constructor-parameter)

2024-07-18 15:09 UTC, pmzandbergen commented
@magento run all tests

2024-07-19 14:21 UTC, Den4ik commented
@magento run Unit Tests

2024-09-10 14:22 UTC, engcom-Dash commented
@magento run all tests

2024-09-10 14:52 UTC, Den4ik commented on app/code/Magento/Csp/Model/Mode/ConfigManager.php
> +            'reportUri' => !empty($reportUri) ? (string) $reportUri : null,
```suggestion
            'reportUri' => !empty($reportUri) ? (string)$reportUri : null
```

2024-09-10 14:53 UTC, Den4ik commented
@magento run all tests

2024-09-10 17:46 UTC, Den4ik commented
@magento run Unit Tests

2024-09-11 05:58 UTC, engcom-Dash commented
@magento run all tests

2024-09-11 09:05 UTC, Den4ik approved these changes
✅ Approved.
Changes looks ok for me.
Failed tests each time is different and don't related to the changes.

2024-09-19 12:23 UTC, engcom-Dash commented
@magento run all tests

2024-09-19 14:03 UTC, engcom-Dash commented
Hello @pmzandbergen 

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:

Install fresh Magento 2.4-develop
Steps to reproduce

- Create a new plugin on method: Magento\Csp\Model\Mode\Data\ModeConfigured::isReportOnly()
- Set a breakpoint in the plugin's method or use the die keyword.
- Access the homepage URL or admin page URL.

Before: ✖️
homepage loads without triggering the plugin.
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/be6c6e9c-b20b-4c4b-9198-c68e894a66a8">

After: ✔️
Plugin is triggered.
<img width="1782" alt="image" src="https://github.com/user-attachments/assets/570784e6-41be-473c-b184-e3c9ed08ce60">

Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

2024-09-20 10:44 UTC, engcom-Dash commented
@magento run all tests

2024-09-20 13:59 UTC, engcom-Dash commented
I have a green build (all tests passed), so I'm moving it to Merge in Progress.

<img width="1776" alt="image" src="https://github.com/user-attachments/assets/6aeb775d-6f35-4ffb-8502-fe6e0b743834">

2024-11-25 13:57 UTC, engcom-Dash commented
We have seen static failures in mainline PR after merging this PR into that. Hence for now moving this PR to Extended testing.

2024-11-25 14:01 UTC, engcom-Dash commented
@magaento run all tests

2024-11-25 14:02 UTC, engcom-Dash commented
@magento run all tests

2024-11-26 05:43 UTC, engcom-Dash commented
@magento run Functional Tests CE, Functional Tests B2B

2024-11-26 09:18 UTC, engcom-Dash commented
The Functional B2B and CE test failures seem flaky and some of these failures are known issues. They are neither part of PR now failing because of PR changes. Hence moving it to Merge in Progress.

**Functional Tests B2B**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38886/6f2db52807a3c708a0be9960115b0689/Functional/allure-report-b2b/index.html#categories/3a3a8306986cbb01e5245b23e6e5b238/715420361f789b7/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/8ed173c2-5d9b-47d1-87cf-0d04d27a6db0">

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38886/37b223604492bd6d8496120f6e64de42/Functional/allure-report-b2b/index.html#categories/3a3a8306986cbb01e5245b23e6e5b238/1b73508e9f000b5f/
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/16a4119c-433c-499e-8cfe-a44efa567f37">

Known Issues:
MultiShippingWithCreationNewCustomerAndAddressesDuringCheckoutTest: [ACQE-7229](https://jira.corp.adobe.com/browse/ACQE-7229)
StoreFrontAddOutOfStockProductToShoppingCartTestCest: [ACQE-6818](https://jira.corp.adobe.com/browse/ACQE-6818)
StorefrontReuseCouponCodeAfterOrderCanceledTest: [ACQE-7230](https://jira.corp.adobe.com/browse/ACQE-7230)

**Functional Tests CE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38886/42b5eb56906513fe5eea7fe14dd341e3/Functional/allure-report-ce/index.html#categories/6d7e37752c3cc83cb3d2063131f608bb/93d477020fb48965/
<img width="1787" alt="image" src="https://github.com/user-attachments/assets/e9c4398e-bc74-4d9a-86a8-a265ba56835f">

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38886/974ba1a9f4df8f43176d877447c86fcf/Functional/allure-report-ce/index.html#categories/6d7e37752c3cc83cb3d2063131f608bb/7b4b2f91ca0a480a/
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/800d9589-d257-4279-9f9d-0f6374c5b6f3">

Known Issue: 
VerifyDefaultWYSIWYGToolbarOnProductTest: [ACQE-7227](https://jira.corp.adobe.com/browse/ACQE-7227)

2024-12-24 15:16 UTC, merged