Insufficient Attribute Error Details During Product Import in Magento 2
magento/magento2 pull request #38918
Opened 2024-07-11 20:39 UTC by PieterCappelle

When importing products into Magento 2, I frequently encounter `errors` related to product attributes. However, the error messages provided by the system lack specific information about which attribute has caused the error. This insufficient detail makes it challenging to identify and rectify the issue promptly.

### Current Error Message:
The current error messages are vague and do not specify the exact attribute that is causing the issue. An example of such an error message might be:
```
The attribute option label is empty. Enter the value and try again.
Admin store attribute option label "%1" is already exists.'
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-07-12 05:49 UTC, PieterCappelle commented
@magento run all tests

2024-07-16 11:05 UTC, engcom-Hotel commented
@magento create issue

2024-10-18 07:44 UTC, engcom-Hotel commented
@magento run all tests

2024-10-18 11:11 UTC, engcom-Hotel requested changes
Hello @PieterCappelle,

Thanks for the contribution!

The changes look good to me, but please address the build failures. It seems they are caused by the PR changes, particularly the Static and WebAPI tests.

Thanks

2024-10-19 13:09 UTC, PieterCappelle commented
Could you provide some guidance on identifying the specific errors that need to be addressed? It appears that the issues in the test results might be related to other underlying problems, or perhaps they're being caused by dependencies on other components. Any advice on how to isolate and resolve these errors would be greatly appreciated.

2024-10-19 16:02 UTC, hostep commented
@PieterCappelle: you can click the 'Details' link next to the 'Static Tests' & 'Web API Tests' at the bottom of this page, then click further on 'Console Error logs' and you should see the failures in more detail.
One is about a trailing whitespace introduced on line 67, and the others are about tests that need to be updated if I understand it correctly.

2024-11-12 09:23 UTC, engcom-Charlie commented
@magento run all tests

2024-11-12 12:22 UTC, engcom-Charlie commented
@magento run all tests

2024-11-13 06:42 UTC, engcom-Charlie commented
@magento run Functional Tests EE, Integration Tests, WebAPI Tests

2024-11-20 06:29 UTC, engcom-Charlie commented
@magento run all tests

2024-11-20 09:37 UTC, engcom-Charlie commented
@magento run all tests

2024-11-20 13:11 UTC, engcom-Charlie commented
Implemented fix for Web API and Static test failure. Moving the PR to Extended Testing as the build is failing.

2024-11-20 13:12 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Static Tests

2024-11-21 06:05 UTC, engcom-Charlie commented
@magento run all tests

2024-11-21 07:19 UTC, engcom-Charlie commented
@magento run all tests

2024-11-21 09:21 UTC, engcom-Charlie commented
@engcom-Hotel The Static and Web API test failures has been fixed hence requesting for review.

Thank you!

2024-11-21 10:49 UTC, engcom-Hotel commented
@magento run all tests

2024-11-21 13:51 UTC, engcom-Hotel requested changes
Thanks @engcom-Charlie, for fixing the failures.

Just one more review point remains. Please address it, and then we’ll be good to go.

2024-11-21 13:51 UTC, engcom-Hotel commented on app/code/Magento/Eav/Model/Entity/Attribute/OptionManagement.php
> +                    $$attribute->getAttributeCode()
I think it is a typo here:
```suggestion
                    $attribute->getAttributeCode()
```

2024-11-21 13:57 UTC, PieterCappelle commented
@magento run all tests

2024-11-22 06:03 UTC, engcom-Charlie commented
> Thanks @engcom-Charlie, for fixing the failures.
> 
> Just one more review point remains. Please address it, and then we’ll be good to go.

Hi @engcom-Hotel, as the reviewed point has been covered, moving it to Review again

2024-11-22 06:33 UTC, engcom-Hotel approved these changes
Thanks @PieterCappelle for resolving the review comments. Approving this PR for further processing.

Thanks

2024-11-29 10:20 UTC, engcom-Bravo commented
Hi @PieterCappelle,

Thanks for your Contribution!!.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.



<img width="1440" alt="Screenshot 2024-11-29 at 10 21 14" src="https://github.com/user-attachments/assets/98de22a0-dba4-4d99-a9a1-eea8e9ef25c1">


We are getting exact error saying that the particular attribute causing this issue.Could you please let us know if we are missing anything.


Thanks.

2024-11-29 14:36 UTC, PieterCappelle commented
The error shown in your screenshot differs from the modified error message. This specific error only occurs when using PHP's import function directly. The interface-based import includes additional try/catch blocks that handle errors differently.

2024-12-02 10:24 UTC, engcom-Charlie commented
> The error shown in your screenshot differs from the modified error message. This specific error only occurs when using PHP's import function directly. The interface-based import includes additional try/catch blocks that handle errors differently.

Hi @PieterCappelle,

Thank you for your contribution!

In order to proceed further on this PR, it will be really helpful if you provide some manual steps to reproduce this issue. Can you please elaborate more on how you are using php's import function or which script to get this error. 

Thank you!

2024-12-10 09:04 UTC, engcom-Charlie commented
Hi @PieterCappelle,

Can you please provide your input on [this](https://github.com/magento/magento2/pull/38918#issuecomment-2511135101) till then moving this PR to On Hold.

Thank you!

2025-01-20 15:07 UTC, engcom-Charlie commented
Hi @PieterCappelle,

Did you get a chance to look into [this](https://github.com/magento/magento2/pull/38918#issuecomment-2530878561) comment.

Thank you!

2025-02-20 07:58 UTC, engcom-Charlie commented
Hi @PieterCappelle,

As we dint get input on [this](https://github.com/magento/magento2/pull/38918#issuecomment-2511135101) in order to reproduce the issue, closing this PR now.

Please feel free to reopen it if you have any updates.

Thank you!

2025-02-20 07:58 UTC, closed without merging