Fix Warning: Undefined array key "filters"
magento/magento2 pull request #38996
Opened 2024-08-02 08:59 UTC by thomas-kl1

### Description (*)
Fresh Install, when a new user does not have played with bookmarks yet, this silenced error is logged.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-08-03 15:44 UTC, thomas-kl1 commented
@magento run all tests

2024-08-06 11:09 UTC, engcom-Hotel commented
@magento create issue

2024-09-18 06:51 UTC, engcom-Hotel commented
@magento run all tests

2024-09-18 09:57 UTC, engcom-Hotel commented
@magento run Static Tests

2024-09-18 10:56 UTC, engcom-Hotel requested changes
Hello @thomas-kl1,
Thanks for the contribution!

Please add the doc block as suggested below.

Thanks

2024-09-18 10:56 UTC, engcom-Hotel commented on app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php
> +     */
```suggestion
     */*
 * @param array $existingConfig The existing configuration
 * @param array $currentConfig The current configuration
 * @return bool True if positions have changed, false otherwise
 */
```

2024-09-18 13:57 UTC, engcom-Hotel commented
@magento run all tests

2024-09-19 06:10 UTC, engcom-Charlie commented
It seems that review changes has been covered so moved it back to review

2024-09-20 06:59 UTC, engcom-Hotel approved these changes

2024-09-25 05:45 UTC, engcom-Bravo commented
@magento run all tests

2024-09-25 07:51 UTC, engcom-Bravo commented
Hi @thomas-kl1,


Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

A lot of "Fix Warning: Undefined array key "filters" errors pop in the logs when using the Admin views (ui grids).


**Before:** :heavy_multiplication_x: 


` main.CRITICAL: Exception: Warning: Undefined array key "filters" in /usr/local/var/www/magentok/magento2/app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php on line 250 in /usr/local/var/www/magentok/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:62`


**After:** :heavy_check_mark: 


There will be No Error in the Logs.

Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

2024-09-25 09:33 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

2024-09-26 05:03 UTC, engcom-Charlie commented
@magento run Functional Tests EE

2024-09-26 06:37 UTC, engcom-Charlie commented
@magento run all tests

2024-09-26 10:51 UTC, engcom-Charlie commented
@magento run Semantic Version Checker, Functional Tests B2B, Functional Tests CE

2024-09-26 13:05 UTC, engcom-Charlie commented
Functional B2B and CE failures in recent 2 builds are not consistent. They are not related to PR or not failing because of PR changes, seems to be flaky. Hence moving this PR to Merge in Progress.

**Functional B2B: Run1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/43f32231cb1a5e50d3ad4a58a1e1e303/Functional/allure-report-b2b/index.html#categories

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/8c290def-f8be-4ff2-8fcb-3517e7b5a4d9">

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/a464976bc37b6cb5b82b31a51a9949bf/Functional/allure-report-b2b/index.html#categories

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/7a102af4-a989-4029-8d5e-c57b391b3857">


**Functional CE: Run1:**

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/88db4508464058e6323f57d14f892641/Functional/allure-report-ce/index.html#categories

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/dfe8732a-9368-4307-af05-d43ccdc4c7ea">



**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/c5ea7735164fde9706863e259a29c0fa/Functional/allure-report-ce/index.html#categories

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/998f146c-1e3a-41ec-ab8a-be181de61c9a">

2024-10-21 22:30 UTC, thomas-kl1 commented
Hello @engcom-Charlie , any idea if there's a chance this PR pass with next release?

2024-10-23 06:43 UTC, engcom-Charlie commented
> Hello @engcom-Charlie , any idea if there's a chance this PR pass with next release?

Hi @thomas-kl1, 

We are trying to get it merge soon. We will notify you here once it will get merge.

2024-11-01 15:51 UTC, merged

2024-12-02 09:56 UTC, Calvin495 commented
@engcom-Charlie 
This fix is not in Magento 2.4.7-p1. Is there an official patch available for this fix?

2024-12-02 09:57 UTC, thomas-kl1 commented
Hello @Calvin495 you can use the diff and apply it as a patch.

2024-12-02 10:25 UTC, Calvin495 commented
@thomas-kl1 

Thanks. That was the last resort :)

Is this fix included in 2.4.7-p2?

2024-12-02 10:37 UTC, thomas-kl1 commented
This fix has been merged on November 1st, the 2.4.7-p2 has been released on August 9th. 😄 

For now the fix is only in the develop branch and is not part of any release yet.

2024-12-02 11:11 UTC, Calvin495 commented
@thomas-kl1 

Thanks