Task/38939 docblock change
magento/magento2 pull request #39001
Opened 2024-08-02 16:17 UTC by Mohamed-Asar

### Description (*)
Doc block change ->  \Magento\ProductAlert\Model\Stock::deleteCustomer

### Related Pull Requests

### Fixed Issues (if relevant)
#38939

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-12-16 06:51 UTC, engcom-Hotel commented
@magento run all tests

2024-12-16 10:18 UTC, engcom-Hotel commented
@magento run Static Tests

2024-12-16 12:22 UTC, engcom-Hotel commented
@magento run Functional Tests CE, Unit Tests

2024-12-16 12:28 UTC, engcom-Hotel requested changes
Hello @Mohamed-Asar,

Thanks for the contribution!

Please address the failed tests, particularly the static tests. Other tests seems flaky to me.

Thanks

2024-12-16 12:37 UTC, Mohamed-Asar commented
@magento run all tests

2024-12-16 15:07 UTC, Mohamed-Asar commented
Hello @engcom-Hotel,

Static test issues are fixed. please review

2024-12-17 07:18 UTC, engcom-Hotel approved these changes

2024-12-18 11:03 UTC, engcom-Dash commented
@magento run all tests

2024-12-18 13:02 UTC, engcom-Dash commented
Manual testing is not required here, as this PR is only updating the doc block. Since the builds are failing, moving it to Extended Testing.

2024-12-18 14:22 UTC, engcom-Dash commented
@magento run all tests

2024-12-19 06:09 UTC, engcom-Dash commented
@magento run Static Tests, Functional Tests EE, Functional Tests B2B

2024-12-19 11:17 UTC, engcom-Dash commented
The Functional B2B and CE test failures are inconsistent in the last two builds and seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

**Functional Tests B2B**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39001/39f7e0d337978493cb28b0605a762071/Functional/allure-report-b2b/index.html#categories/7441e147742cc9294f4ce2a0b5090c42/bc9ba123a8c7a22a/
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/be219cac-ecff-444b-987d-bbdb1016b000" />


Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39001/a321f77a7aa41f73df83581ad79483ec/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/bd021f6ba00492d7/
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/53ce68bf-605b-4ca4-adf6-da4caae86438" />

**Functional Tests EE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39001/724cb0f8267827a590bb263bd624c20c/Functional/allure-report-ee/index.html#categories/bdbf199525818fae7a8651db9eafe741
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/b2c13065-edd0-46d7-b544-d7d55373802c" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39001/04a4e3a25981ab94acb9e3764d3b1ec0/Functional/allure-report-ee/index.html#categories/089c34e15cffa054c840ca8e9a9dd97a/2d6b6b5e158f745f/
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/8b7a4b46-a992-4e08-bdb9-4e43843e42cd" />

2025-01-07 15:54 UTC, merged