ISSUE-38593 - Fix to save middle name in the quote for quest
magento/magento2 pull request #39067
Opened 2024-08-20 03:32 UTC by srsathish92

### Description (*)
Fix to save the customer's middle name in the quote/order table for the guest checkout

### Related Pull Requests
NA

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38593

### Manual testing scenarios (*)
1. Place guest order with middle name.
2. Verify the quote table whether the "customer_middlename" column is filled or not.

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-12-13 06:17 UTC, engcom-Hotel commented
@magento run all tests

2024-12-13 09:48 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Integration Tests

2024-12-16 08:30 UTC, engcom-Hotel requested changes
Hello @srsathish92,

Thanks for the collaboration!

The changes look good to us. However, please include automated tests covering the changes as per the [Definition of Done (DoD)](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

Thanks

2024-12-17 06:44 UTC, engcom-Dash commented
> Hello @srsathish92,
> 
> Thanks for the collaboration!
> 
> The changes look good to us. However, please include automated tests covering the changes as per the [Definition of Done (DoD)](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).
> 
> Thanks

I'm working on it.

cc: @srsathish92

2024-12-18 04:50 UTC, engcom-Dash commented
@magento run all tests

2024-12-18 07:45 UTC, engcom-Dash commented
@magento run all tests

2024-12-18 08:29 UTC, engcom-Dash commented
@magento run Static Tests

2024-12-18 09:57 UTC, engcom-Dash commented
@magento run Static Tests, Functional Tests B2B

2024-12-18 10:48 UTC, engcom-Dash commented
@engcom-Hotel: I have covered the changes with unit tests. Additionally, I have fixed the static failures, so I am moving it back to pending review.

2024-12-18 14:13 UTC, engcom-Hotel approved these changes

2024-12-19 04:21 UTC, engcom-Bravo commented
@magento run all tests

2024-12-19 09:13 UTC, engcom-Bravo commented
Hi @srsathish92,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Place guest order with middle name.
- Verify the quote table whether the "customer_middlename" column is filled or not.



**Before:** :heavy_multiplication_x: 

<img width="683" alt="Screenshot 2024-12-19 at 10 02 10 am" src="https://github.com/user-attachments/assets/fdfa30da-2551-4821-af2d-49ec5b2b68c3" />






**After:** :heavy_check_mark: 

<img width="683" alt="Screenshot 2024-12-19 at 10 08 40 am" src="https://github.com/user-attachments/assets/e68e61cf-e579-4eb1-af39-f6c3b19629d6" />



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2024-12-19 12:10 UTC, engcom-Dash commented
@magento run Integration Tests, Functional Tests EE, Functional Tests B2B

2024-12-19 14:39 UTC, engcom-Dash commented
The Functional B2B test failure is inconsistent in the last two builds and seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/438b375dbcb807c78bd5913427b45fe3/Functional/allure-report-b2b/index.html#categories/7441e147742cc9294f4ce2a0b5090c42/2117aaff39bc5c43/
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/e96dd802-5ce4-4910-8eea-d25b5c62cf3d" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/ba6f5b6b90a68a4aa089aae9ecc1b512/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/b266ec312127147f/
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/85da80d2-5c24-493e-8f87-f66a4f448fa7" />

2025-01-08 09:17 UTC, engcom-Charlie commented
As the PR is having conflicts, moving it to Extended Testing.

2025-01-08 10:55 UTC, engcom-Dash commented
@magento run all tests

2025-01-09 07:00 UTC, engcom-Dash commented
@magento all tests

2025-01-09 07:00 UTC, engcom-Dash commented
@magento run all tests

2025-01-09 10:11 UTC, engcom-Dash commented
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests CE

2025-01-09 13:59 UTC, engcom-Dash commented
The Functional CE, EE and Integration test failures are inconsistent or known issues in the last two builds and seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

**Integration Tests**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/00e88de9855f87b0344ac5c9a3c2ff55/Integration/console-error-logs.html
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/54876810-aee9-49ae-a18d-fc1919bfafdb" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/20ecb2fb12b79ffcea95f901cf5dd19e/Integration/console-error-logs.html
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/309c57cd-04d5-4a09-88eb-dc8827435f06" />

Known Issue:
[AC-13584](https://jira.corp.adobe.com/browse/AC-13584)

**Functional Tests CE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/ed1a85389eb50587b7c0a63c60cb23f8/Functional/allure-report-ce/index.html#categories/75b40a63f79830217aae704c6d6af940/949221b1e68f9003/
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/8b16c05d-1cc1-41ef-8b5e-2150505a5153" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/5a9f52b1d296a7c6ebfd32a10e18646a/Functional/allure-report-ce/index.html#categories/e93c564a2dcd5e30ee0e0e811a828c2b/b231fcb0ae617645/
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/faefab41-207b-4c5e-96a8-e618fcb5f885" />

Known Issues:
StorefrontCreateCustomerWithInvalidDataTest: [AC-13608](https://jira.corp.adobe.com/browse/AC-13608)
StoreFrontAddOutOfStockProductToShoppingCartTest: [ACQE-6818](https://jira.corp.adobe.com/browse/ACQE-6818)

**Functional Tests EE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/58e8a25158f1a7df6eec0c3320ac2989/Functional/allure-report-ee/index.html#categories/248597673789965e9aa9f3e68e4329b7/6e7bae3c5c99780f/
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/5f36dc9b-277a-4032-b281-ad02153a0950" />

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39067/22e90edd145dd4e214a7fcb5c3e9bfae/Functional/allure-report-ee/index.html#categories/75b40a63f79830217aae704c6d6af940/5c7498f2b504e4a0/
<img width="1787" alt="image" src="https://github.com/user-attachments/assets/e80fb2a0-9d94-45a8-858d-00ccd4cdf36a" />

2025-02-17 11:20 UTC, merged