[PHPDOC] Fix bad phpdoc for Magento\Framework\Message\ManagerInterface
magento/magento2 pull request #39153
Opened 2024-09-10 12:39 UTC by dimitriBouteille

### Description (*)

This PR fix the bad phpdoc for `\Magento\Framework\Message\ManagerInterface` and remove all duplicate phpdoc in `\Magento\Framework\Message\Manager` (use inheritdoc syntaxe).

Actually all `add*Message` functions (addErrorMessage,  addSuccess, addWarningMessage, ...) accept a `string` value in `$message` variable. 

This PR allows to pass either a `\Magento\Framework\Phrase` or a `string`.

Here is an example where the type `\Magento\Framework\Phrase` is used :

https://github.com/magento/magento2/blob/0cfe4a36b72cde1ecd9613b70bac0d34a2f8f1ed/app/code/Magento/Checkout/Controller/Cart/Delete.php#L38

For example, with PHPSTAN is very complicated to setup the project with level 5 or higher :(

![Capture d’écran du 2024-09-10 14-39-16](https://github.com/user-attachments/assets/f4b97df2-a5a7-4115-9611-255a0fa66373)

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

Setup PHPSTAN with level 5 or higher and run check.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39593: [PHPDOC] Fix bad phpdoc for Magento\Framework\Message\ManagerInterface

2024-09-10 12:40 UTC, dimitriBouteille commented
@magento run all tests

2024-12-16 06:50 UTC, engcom-Hotel commented
@magento run all tests

2024-12-16 10:17 UTC, engcom-Hotel commented
@magento run Static Tests

2024-12-16 12:14 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

2024-12-16 12:19 UTC, engcom-Hotel requested changes
Hello @dimitriBouteille,

Thanks for the contribution!

The changes look good to us. However, please address the failed tests, particularly the static tests.

Thanks

2024-12-18 09:45 UTC, engcom-Charlie commented
@magento run all tests

2024-12-18 11:37 UTC, engcom-Charlie commented
@magento run all tests

2024-12-19 07:36 UTC, engcom-Charlie commented
@magento run all tests

2024-12-19 09:30 UTC, engcom-Charlie commented
@magento run all tests

2024-12-19 12:51 UTC, engcom-Charlie commented
@magento run all tests

2024-12-20 08:21 UTC, engcom-Charlie commented
@engcom-Hotel, I have fixed the static test failures. Requesting for the review.

Thank you!

2024-12-20 09:28 UTC, dimitriBouteille commented
Hi @engcom-Charlie 

I see the MR in `Progress: needs update`, do I need to do something else?

2024-12-20 10:26 UTC, engcom-Charlie commented
> Hi @engcom-Charlie
> 
> I see the MR in `Progress: needs update`, do I need to do something else?

Hi @dimitriBouteille,

The bot assigned Progress: needs update label to this PR because there was a review change requested [here](https://github.com/magento/magento2/pull/39153#pullrequestreview-2506034221). I have taken care of static test failures now so removing the same.

2024-12-20 11:34 UTC, engcom-Hotel requested changes
Hello @dimitriBouteille,

Please refer to my review comment below.

Thanks

2024-12-20 11:34 UTC, engcom-Hotel commented on lib/internal/Magento/Framework/Message/Manager.php
> +        $this->exceptionMessageFactory = $exceptionMessageFactory ?: $exceptionMessageLookupFactory;
To make this change backward compatible, please use ObjectManager to initialize `$exceptionMessageLookupFactory`

2024-12-23 10:25 UTC, engcom-Charlie commented
@magento run all tests

2024-12-31 11:03 UTC, engcom-Charlie commented
@magento run all tests

2025-01-02 06:48 UTC, engcom-Charlie commented
@engcom-Hotel the review comments has been taken care and I have fixed the static test failures too hence requesting for the review.

2025-01-06 05:36 UTC, engcom-Hotel commented
@magento run all tests

2025-01-06 08:08 UTC, engcom-Hotel approved these changes

2025-01-07 11:49 UTC, engcom-Charlie commented
No manual testing is required here, as only the bad doc blocks are getting updated here. Currently moving this PR to Extended Testing as the build is failing.

2025-01-08 05:37 UTC, engcom-Charlie commented
@magento run all tests

2025-01-09 09:01 UTC, engcom-Charlie commented
@magento run all tests

2025-01-09 12:02 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2025-01-09 15:36 UTC, engcom-Charlie commented
The Integration test failures are the known issues.
[Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/8f82610ed279d42193cdd7ead5209cfd/Integration/console-error-logs.html) and [Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/8f82610ed279d42193cdd7ead5209cfd/Integration/console-error-logs.html)

**Known Issue:**
[AC-13584](https://jira.corp.adobe.com/browse/AC-13584)

One of the test failure of Functional CE in the recent 2 builds is not consistent and the consistent one is a known issue. The failures are neither part of this PR nor failing because of the PR changes. Hence moving this PR to Merge in progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/49fc9286695b52064ef79467cb7082cb/Functional/allure-report-ce/index.html#categories/e93c564a2dcd5e30ee0e0e811a828c2b/d58fef795b7f04e7/
<img width="964" alt="image" src="https://github.com/user-attachments/assets/dca07373-d2f7-4150-b337-e439bfa35728" />


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/94391ff564ee797fd51baccb033093cc/Functional/allure-report-ce/index.html#categories

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/d423f655-e3d3-470b-9a7c-31c7f086c68a" />


Known Issue:
[AC-13608](https://jira.corp.adobe.com/browse/AC-13608): StorefrontCreateCustomerWithInvalidDataTest

2025-01-31 11:58 UTC, ihor-sviziev commented
@magento create issue

2025-01-31 13:31 UTC, ihor-sviziev requested changes
Based on discussion in https://github.com/magento/magento2/pull/39572#pullrequestreview-2586329086 and https://github.com/magento/magento2/pull/39572#issuecomment-2627298859
we agreed to use a `\Stringable` interface.

Let's update this PR to make it more consistent in all places

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 13:31 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/ManagerInterface.php
> +     * @param string|\Magento\Framework\Phrase $message
```suggestion
     * @param string|\Stringable $message
```

2025-01-31 15:23 UTC, dimitriBouteille commented
@ihor-sviziev Done :rocket:

2025-01-31 16:27 UTC, ihor-sviziev approved these changes

2025-02-03 09:06 UTC, ihor-sviziev commented
@magento run all tests

2025-02-03 09:08 UTC, ihor-sviziev requested changes

2025-02-03 09:08 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +        ?ExceptionMessageLookupFactory $exceptionMessageLookupFactory = null
@dimitriBouteille, I just wonder why it's needed.

2025-02-03 09:08 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
and this?

2025-02-03 09:11 UTC, dimitriBouteille commented on lib/internal/Magento/Framework/Message/Manager.php
> +        ?ExceptionMessageLookupFactory $exceptionMessageLookupFactory = null
I don't kown, is not my code 😂

2025-02-03 09:14 UTC, engcom-Charlie commented
As @ihor-sviziev started reviewing the PR again, moving it back to Changes Requested from Merge in Progress.

2025-02-03 09:24 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +        ?ExceptionMessageLookupFactory $exceptionMessageLookupFactory = null
@engcom-Charlie could you please explain this?

2025-02-03 11:24 UTC, dimitriBouteille commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
Same, not my code 😂

https://github.com/magento/magento2/pull/39153/commits/c8abbb92ac1b581d388ce1875e5e925b4249187f

2025-02-11 11:51 UTC, engcom-Charlie commented on lib/internal/Magento/Framework/Message/Manager.php
> +        ?ExceptionMessageLookupFactory $exceptionMessageLookupFactory = null
@ihor-sviziev on prior implementation, in https://github.com/magento/magento2/pull/39153/commits/0c33ab925541ca1cc1ab68c1bfaf92fe97ba58ae, PR was showing [static](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/88de68b01ca0359a43b11b6cac8973b3/Statics/console-error-logs.html) test failures which we have conveyed in [here](https://github.com/magento/magento2/pull/39153#pullrequestreview-2506034221). We have fixed them in [here](https://github.com/magento/magento2/commit/c8abbb92ac1b581d388ce1875e5e925b4249187f)

2025-02-11 11:52 UTC, engcom-Charlie commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
@ihor-sviziev, as per [this](https://github.com/magento/magento2/pull/39153#pullrequestreview-2517351517) review comment, I have implemented these changes.

2025-02-11 12:08 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
Ok, I looked on it deeper - and see that it was added to fix the following static test failure:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/25b42fa255012f82d219680ffcfcce6b/Statics/console-error-logs.html
```
PHP Code Sniffer detected 1 violation(s): 

FILE: /var/www/html/lib/internal/Magento/Framework/Message/Manager.php
------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------
 24 | WARNING | Visibility must be declared on all constants if your project supports PHP 7.1 or later
 91 | ERROR   | Class ExceptionMessageLookupFactory needs to be requested in constructor, otherwise compiler will not
    |         | be able to find and generate this class
------------------------------------------------------------------------------------------------------------------------
```

---
I reviewed the static test - and it try to detect auto-generated factory and complain about it. And it looks just like the class name.
Ref to static test https://github.com/magento/magento-coding-standard/blob/d7ece6da506db4fadaa63c7ae31d15f1d9ff1443/Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php#L92


---
However, in this specific case, the class ExceptionMessageLookupFactory actually NOT auto-generated, it's located in https://github.com/magento/magento2/blob/d253a44cee2ac9b3d433bb1b2d86ed3000e40a4f/lib/internal/Magento/Framework/Message/ExceptionMessageLookupFactory.php#L9.

So that, this is a false-positive, that has to be ignored, and the changes has to be reverted.

```suggestion
        $this->exceptionMessageFactory = $exceptionMessageFactory ?: ObjectManager::getInstance()
            ->get(ExceptionMessageLookupFactory::class);
```

@engcom-Charlie could you please fix that?

2025-02-11 12:10 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +        ?ExceptionMessageLookupFactory $exceptionMessageLookupFactory = null
As desribed in https://github.com/magento/magento2/pull/39153/files#r1950728162, this change should be reverted.

```suggestion
        ?ExceptionMessageFactoryInterface $exceptionMessageFactory = null
```

2025-02-11 13:11 UTC, engcom-Charlie commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
@ihor-sviziev thank you for this input. I aggre with false positive case of isClassAutogenerated but fhe function validateRequestedClass() also check for isConstructorParameter().  what do you think about this.

2025-02-11 13:51 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
The constructor asking for the interface, while this class requires a specific factory, that implements that interface - as for me - as to me, in this specific case, all is good, we can ignore it.

2025-02-12 10:02 UTC, engcom-Charlie commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
Okay @ihor-sviziev. I have reverted c8abbb9. Please review it, I will proceed further after the build result.

2025-02-12 10:03 UTC, engcom-Charlie commented
@magento run all tests

2025-02-12 11:13 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +        ExceptionMessageFactoryInterface $exceptionMessageFactory = null
Let's revert this change:
```suggestion
        ?ExceptionMessageFactoryInterface $exceptionMessageFactory = null
```

2025-02-12 11:13 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Message/Manager.php
> +                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
@engcom-Charlie, I see you also removed `?` from the beginning of the constructor argument, which isn't correct.

Also, I think we need to ignore the line on which static test failed, e.g. this should work:
```php
        $this->exceptionMessageFactory = $exceptionMessageFactory ?: ObjectManager::getInstance()
            ->get(ExceptionMessageLookupFactory::class); // phpcs:ignore
```

2025-02-13 06:24 UTC, engcom-Charlie commented
@magento run all tests

2025-02-13 08:44 UTC, engcom-Charlie commented
@magento run Integration Tests, Functional Tests CE, Functional Tests EE

2025-02-13 08:47 UTC, ihor-sviziev approved these changes

2025-02-14 06:49 UTC, engcom-Charlie commented
The review changes have been implemented and approved hence moving it to Ready for Testing.

2025-02-14 06:53 UTC, engcom-Charlie commented
No manual testing is required here, as only the bad doc blocks are getting updated. Currently moving this PR to Extended Testing as the build is failing.

2025-02-14 06:55 UTC, engcom-Charlie commented
@magento run WebAPI Tests

2025-02-14 07:59 UTC, engcom-Charlie commented
@magento run all tests

2025-02-14 14:20 UTC, engcom-Charlie commented
@magento run Integration Tests

2025-02-17 07:20 UTC, engcom-Charlie commented
@magento run all tests

2025-02-17 10:49 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

2025-02-17 13:25 UTC, engcom-Charlie commented
Hi @dimitriBouteille,

As I am working on the build stabilization activity of this PR, requesting you to please don't merge latest codebase in this PR.  If any input needed from your end will let you know.

Thank you!

2025-02-17 13:25 UTC, engcom-Charlie commented
@magento run all tests

2025-02-18 04:50 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

2025-02-18 08:39 UTC, engcom-Charlie commented
One of the **Functional B2B** test failure is inconsistent in the last two builds, it seem to be flaky and the other one is a known issue. They neither part of PR nor failing because of the PR changes. 

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/6b368458733182aecc9a07f0fcf2b7a6/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/d01814eab6700437/

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/7604870d-4728-4481-bff5-569e89f03648" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/b8a9c797d4d64520188c53b5cfae1e14/Functional/allure-report-b2b/index.html#categories
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/6e20b0fd-23d3-4069-99e2-323c9ca7ed8f" />

**Known Issue:**
StorefrontAssertAsLowAsLabelTest: [ACQE-7389](https://jira.corp.adobe.com/browse/ACQE-7389)

One of the **Functional CE** test failure is inconsistent in the last two builds, it seem to be flaky . They neither part of PR nor failing because of the PR changes. Hence moving it to Merge In Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/81d5a862903c6903ed35b5ab74dc7190/Functional/allure-report-ce/index.html#categories
<img width="918" alt="image" src="https://github.com/user-attachments/assets/bdff955e-e3a6-4ab1-9ef7-dec443a064dd" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/3e5cd018f3060fafd0c32d7d158f7fc2/Functional/allure-report-ce/index.html#categories

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/8fa00ef0-0f7d-432a-9a95-76552e440f19" />

2025-04-02 23:52 UTC, merged