Disable captcha storefont config still load captcha js files
magento/magento2 pull request #39154
Opened 2024-09-10 17:39 UTC by rogerdz

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32987

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-09-10 17:40 UTC, rogerdz commented
@magento run all tests

2024-09-11 02:13 UTC, rogerdz commented
@magento run all tests

2025-02-18 04:11 UTC, engcom-Hotel commented
@magento run all tests

2025-02-18 09:42 UTC, engcom-Hotel requested changes
Hello @rogerdz,

Thank you for the contribution!

Please address the review comments mentioned below.Additionally it appears that the failed integration and static tests are caused by the changes in this PR. 

Kindly resolve those as well.

2025-02-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php
> +    public function afterGetTemplate(
Please specify return type declaration.

2025-02-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php
> +        $result
Please add parameter type declaration.

2025-02-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php
> +    private function isLoggedIn()
Please specify return type declaration.

2025-02-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php
> +     * Remove template when loggin or disable captcha storefront
Correct the type from `loggin` to `login`

2025-02-18 09:42 UTC, engcom-Hotel commented on app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php
> +        HelperCaptcha $helper,
Use [readonly](https://php.watch/versions/8.1/readonly#constructor-readonly) property here

2025-02-25 09:09 UTC, engcom-Hotel commented
We are picking this PR for further processing.

2025-02-25 09:15 UTC, rogerdz commented
> Hello @rogerdz,
> 
> Thank you for the contribution!
> 
> Please address the review comments mentioned below.Additionally it appears that the failed integration and static tests are caused by the changes in this PR.
> 
> Kindly resolve those as well.

not yet, please fix your composer repo first
![image](https://github.com/user-attachments/assets/45148a41-e30a-4ce5-9f68-3105365d008f)

2025-02-25 12:20 UTC, engcom-Hotel commented
Hello @rogerdz,

This is a known issue and there is an ongoing discussion on this [here](https://magentocommeng.slack.com/archives/C7KB93M32/p1736933306053669). Please refer to this chat for further information.

In the meantime, do you want us to continue with this PR, or should we wait for the composer-related issue to be fixed and then you continue to work on this issue?

Thanks

2025-02-25 16:20 UTC, rogerdz commented
> do you want us to continue with this PR

Yes, thank you.

2025-02-26 11:28 UTC, engcom-Hotel commented
@magento run all tests

2025-02-26 15:38 UTC, engcom-Hotel commented
@magento run Static Tests

2025-02-27 06:04 UTC, engcom-Hotel commented
@magento run all tests

2025-02-27 16:50 UTC, engcom-Hotel commented
@magento run all tests

2025-02-28 08:25 UTC, engcom-Hotel commented
@magento run Integration Tests, Static Tests

2025-02-28 13:08 UTC, engcom-Hotel commented
@magento run all tests

2025-02-28 17:11 UTC, ihor-sviziev requested changes
I believe the captcha module should not affect customer functionality. It is better to adjust the original functionality rather than introduce new plugins.

2025-02-28 17:11 UTC, ihor-sviziev commented on app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php
> +    }
I guess this check should be in the original class `\Magento\Customer\Block\Account\AuthenticationPopup`, or in the template file `Magento_Customer::account/authentication-popup.phtml`.

2025-02-28 17:11 UTC, ihor-sviziev commented on app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php
> +        if ($this->isLoggedIn() || (!$this->helper->getConfig('enable') && $recaptchaType === null)) {
I guess the logic about enabled form for custom login should be added at place, where we configure captcha fields in the customer login form.

I checked - currently it's configured using layout XML, so I guess it has to be moved from XML to some PHP code that will add needed parameters.

I guess it should be something like this:

https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Checkout/Block/Onepage.php#L78-L85
https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Paypal/etc/frontend/di.xml#L197-L203
https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Paypal/Block/PayLater/LayoutProcessor.php#L20-L68

2025-03-05 15:24 UTC, engcom-Hotel commented
@magento run all tests

2025-03-05 16:47 UTC, engcom-Hotel commented
@magento run all tests

2025-03-05 19:20 UTC, hostep commented on app/code/Magento/Customer/Block/Account/AuthenticationPopup.php
> +        HttpContext $httpContext = null
Can we update this type so it's explicitly nullable, this is a requirement for PHP 8.4 to not get deprecation errors.
So change `HttpContext` to `?HttpContext` please. Thanks! :)

2025-03-06 12:04 UTC, engcom-Hotel commented
@magento run all tests

2025-03-07 15:04 UTC, ihor-sviziev commented on app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php
> +    public function process($jsLayout): array
```suggestion
    public function process(array $jsLayout): array
```

2025-03-07 15:04 UTC, ihor-sviziev commented on app/code/Magento/Customer/Block/Account/AuthenticationPopup.php
> +        }
The logic you've just added is related to the captha extension, as it's added in that module in https://github.com/magento/magento2/blob/df37b871ebd2a7e23ae6dec8c084855a65fbcab1/app/code/Magento/Captcha/view/frontend/layout/default.xml#L10-L27

I would suggest doing the following:
1. add layoutProcessors as optional array option to constructor
2. Adjust getJsLayout function to something like this
```suggestion
        foreach ($this->layoutProcessors as $processor) { 
            $this->jsLayout = $processor->process($this->jsLayout); 
        }
```
This will make code as close as possible to https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Checkout/Block/Onepage.php#L78-L85
3. In the Capcha extension, create own layout processor for AuthenticationPopup and **add** all needed parameters through this class + remove the configuration code from layout.xml

**OR**
Do some plugin for this specific method in the captcha extension, and add needed parameters based on the configuration

2025-03-07 15:04 UTC, ihor-sviziev commented on app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php
> +        }
I would suggest adding needed parameters rather than removing them (move from layout.xml), similar to 
https://github.com/magento/magento2/blob/b25fc6f39f584d527745b9d0149c5018c6854d9d/app/code/Magento/Paypal/Block/PayLater/LayoutProcessor.php#L70-L105

2025-03-07 15:04 UTC, ihor-sviziev commented on app/code/Magento/Customer/Block/Account/AuthenticationPopup.php
> +        ) && !$this->isLoggedIn()) {
I don't think it can be related to whether the customer logged in or not. I would expect that this entire block won't be rendered then, but that's a separate issue.

2025-03-07 15:08 UTC, ihor-sviziev commented on app/code/Magento/Captcha/etc/frontend/di.xml
> +                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\CaptchaLayoutProcessor</item>
I guess from the capthca module perspective, it's more "CheckoutLayoutProcessor" than "CaptchaLayoutProcessor".

2025-03-10 14:36 UTC, engcom-Hotel commented on app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php
> +    public function process($jsLayout): array
Add `array` here showing error in PHPStorm because the interface doesn’t have this declaration. The error shown in PHPStorm is as follows:
![image](https://github.com/user-attachments/assets/82e47aa9-90d0-457d-b3ee-78d26aa11e98)

2025-03-10 14:58 UTC, engcom-Hotel commented
@magento run all tests

2025-03-11 06:16 UTC, engcom-Hotel commented
@magento run Functional Tests EE, Functional Tests B2B

2025-03-11 17:43 UTC, ihor-sviziev requested changes

2025-03-11 17:43 UTC, ihor-sviziev commented on app/code/Magento/Captcha/view/frontend/layout/default.xml
> +
I guess we can remove this file now, and the result will be the same as the child element configured in the PHP file now, right?

2025-03-11 17:43 UTC, ihor-sviziev commented on app/code/Magento/Captcha/view/frontend/layout/checkout_index_index.xml
> +
I guess we can remove this file now, and the result will be the same as the child element configured in the PHP file now, right?

2025-03-11 17:43 UTC, ihor-sviziev commented on app/code/Magento/Captcha/view/frontend/layout/checkout_index_index.xml
> +
same here, it's not adding any value

2025-03-11 17:43 UTC, ihor-sviziev commented on app/code/Magento/Captcha/etc/frontend/di.xml
> +                <item name="checkout_processor" xsi:type="object">Magento\Captcha\Block\CheckoutLayoutProcessor</item>
In terms of checkout onepage block, it's more related to captaha, so let's change the name here
```suggestion
                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\CheckoutLayoutProcessor</item>
```

2025-03-11 17:43 UTC, ihor-sviziev commented on app/code/Magento/Captcha/etc/frontend/di.xml
> +                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\Checkout\LayoutProcessor</item>
The current name of the class is quite confusing:
- it's almost the same as  `Magento\Captcha\Block\CheckoutLayoutProcessor`, the differnce is the only one bachslash
- It's not linked anyhow to customer and to authentication popup
So I'm suggesting renaming the class/namespace + update it in di.xml to have something like this
```suggestion
                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\Customer\AuthenticationPopup\LayoutProcessor</item>
```

2025-03-11 17:43 UTC, ihor-sviziev commented on app/code/Magento/Customer/Block/Account/AuthenticationPopup.php
> +        ?HttpContext $httpContext = null,
this parameter isn't used anymore, pls remove

2025-03-11 17:43 UTC, ihor-sviziev commented on app/code/Magento/Customer/Model/Form.php
> +
Pls revert this change
```suggestion

```

2025-03-13 11:24 UTC, engcom-Hotel commented
@magento run all tests

2025-03-18 09:41 UTC, ihor-sviziev commented on app/code/Magento/Customer/Block/Account/AuthenticationPopup.php
> +
```suggestion
```

2025-03-18 09:41 UTC, ihor-sviziev approved these changes

2025-03-18 09:47 UTC, engcom-Hotel commented
Hello @ihor-sviziev,

Thanks for approving the PR. Moving it to `ready for testing` bucket.

@magento run all tests

2025-03-19 09:52 UTC, engcom-Bravo commented
Hi @rogerdz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Disable captcha on frontend admin



**Before:** :heavy_multiplication_x: 

<img width="1440" alt="Screenshot 2025-03-19 at 12 03 37 pm" src="https://github.com/user-attachments/assets/34c65825-1365-448c-bcfe-a58bed4870f7" />





**After:** :heavy_check_mark: 


<img width="1440" alt="Screenshot 2025-03-19 at 12 11 43 pm" src="https://github.com/user-attachments/assets/4f075603-2ddc-4f90-bd7d-9227d2105e53" />








Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-03-21 06:19 UTC, engcom-Dash commented
@magento run all tests

2025-03-21 08:50 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

2025-03-21 12:57 UTC, engcom-Dash commented
Some test failures for the recent two builds for functional CE are consistent and there are the known issues and the Jira raised for the same.  The one test case is flaky in functional CE.

**Functional CE:**

Build 1 : https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39154/066b6436deb394f71afa4d57ad0a2a87/Functional/allure-report-ce/index.html#categories/90ca0ef92eda6ba1448271cd45952684/b58cb19297139441/

<img width="1394" alt="Screenshot 2025-03-21 at 5 53 15 PM" src="https://github.com/user-attachments/assets/3acc1ff5-ec91-4f48-9b38-6ad52b7f6b01" />

Build 2 : https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39154/a4ce46a465c1bfecbd239290d4c06e41/Functional/allure-report-ce/index.html#categories/8f0831c1d06562890f5ec21062dae309/6e213b8f581a59da/

<img width="1213" alt="Screenshot 2025-03-21 at 5 55 56 PM" src="https://github.com/user-attachments/assets/177e3f6f-047c-443b-904a-cd8684bf279e" />

Known Issues:

StorefrontVerifySearchTermEntityRedirectTest: [ACQE-7705](https://jira.corp.adobe.com/browse/ACQE-7705)
AdminUserApplyToSeveralSimpleProductsMassActionUnAssignProductSourcesOnProductsGridToUnAssignAllAssignedSourcesTest: [ACQE-7706](https://jira.corp.adobe.com/browse/ACQE-7706)
AdminValidateSimpleProductWithCustomOptionsDragNDropPerPageTest: [ACQE-7707](https://jira.corp.adobe.com/browse/ACQE-7707)

**Functional EE :**

The consistent failed test case has JIRA raised. Other failures are flaky.
  
Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39154/33d8bde72938ffd875c6b9e5beb5bd51/Functional/allure-report-ee/index.html#categories/8f0831c1d06562890f5ec21062dae309/48c84f74356a6d73/

![image](https://github.com/user-attachments/assets/b9259931-c8df-4b02-969f-0e153c8836d2)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39154/4e2d21703365e1728d1f8332ed013c06/Functional/allure-report-ee/index.html#categories/8f0831c1d06562890f5ec21062dae309/165f0ea25c23621/

![image](https://github.com/user-attachments/assets/f968f512-c4b6-4614-ba8f-fbfc2a8f17dc)

**Known Issues:** 

StorefrontVerifySearchTermEntityRedirectTest: [ACQE-7705](https://jira.corp.adobe.com/browse/ACQE-7705)

**Functional B2B:**

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39154/06c37500ed20912981fb065563990b34/Functional/allure-report-b2b/index.html#categories

<img width="1334" alt="Screenshot 2025-03-27 at 2 18 28 PM" src="https://github.com/user-attachments/assets/560ca01f-2c2e-4817-98e1-bc7c6bbfb2b0" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39154/090abadc6d59013cffc1a8703b764398/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/1d071de1-27a2-497b-a3a3-033a754ce30b)

**Known Issues:** 

StorefrontVerifySearchTermEntityRedirectTest: [ACQE-7705](https://jira.corp.adobe.com/browse/ACQE-7705)

The below two failing test cases are handled in the same JIRA.

StorefrontMergingShoppingCartsWithExistingCompanyCustomerCartTest - [ACQE-7568](https://jira.corp.adobe.com/browse/ACQE-7568)
StorefrontMergingShoppingCartsFromCheckoutShippingPageTest - [ACQE-7568](https://jira.corp.adobe.com/browse/ACQE-7568)

2025-04-29 18:55 UTC, merged