Fix bad \Magento\Sales\Model\Order\Email\Container\Template::$id property
magento/magento2 pull request #39150
Opened 2024-09-10 09:01 UTC by dimitriBouteille

### Description (*)

This PR fix the bad phpdoc for `\Magento\Sales\Model\Order\Email\Container\Template::$id`, actually `$id` is type `int` but in reality is `string`.

![Capture d’écran du 2024-09-10 10-56-41](https://github.com/user-attachments/assets/b045b8a0-aafb-4db4-b262-b7f214e8ec3a)

For example, with PHPSTAN is very complicated to setup the project with level 5 or higher :( 

![Capture d’écran du 2024-09-10 10-58-47](https://github.com/user-attachments/assets/7b4cdc05-c577-4f82-987f-e2f84d2c6517)

**Workaround**

Add `@phpstan-ignore-next-line` before call `setTemplateId` :(

![Capture d’écran du 2024-09-10 11-00-08](https://github.com/user-attachments/assets/4752222a-db8d-4348-b6b3-69a6b213e2dd)

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

Setup PHPSTAN with level 5 or higher and run check.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-09-10 09:02 UTC, dimitriBouteille commented
@magento run all tests

2024-09-10 11:04 UTC, engcom-Hotel commented
@magento create issue

2024-10-11 12:48 UTC, orlangur commented
Hi @dimitriBouteille! Is there some ongoing big effort at the moment to adopt PhpStan at certain level or something?

Generally, everywhere in Magento `int` in PHPDoc always assumes numeric string as well, please check https://github.com/magento/magento2/pull/26930#pullrequestreview-405588483 which we raised before on this. We can make some decision on how we're going to deal with this in general but changing PHPDoc at some random place is definitely not a way to do.

2024-10-14 13:51 UTC, dimitriBouteille commented
Hi @orlangur Thanks for your feedback :)

Today, if I want to set up PHPStan with level 5 (even worth testing a higher level) it is very complicated because the Magento code is not clean, a good part of the PHPDoc is not correct ... 

The best solution to implement PHPStan today is to go through [bitExpert/phpstan-magento](https://github.com/bitExpert/phpstan-magento) and add several ignores in PHPStan. Ignoring rules is stupid, especially when the goal is to ensure the quality of the code.

![Capture d’écran du 2024-10-14 15-39-35](https://github.com/user-attachments/assets/19d98288-541c-4a7f-9eac-b9f9e24951af)

I know that Magento has been around for a while and typing with PHP was complicated, but now with the arrival of PHP 8.x, we should still improve the typing. The idea is to improve PHPDoc because less cumbersome than modifying the code by adding the strict type (e.g : returns type, arguments type, ...).

Decisions made some time ago are one thing, but knowing how to evolve with your time to improve the code is better :heart: 

Finally, I’m not sure that adding `int` from everywhere is a better solution than doing a real typing as I propose with these different PR: https://github.com/magento/magento2/pulls?q=is%3Aopen+is%3Apr+author%3AdimitriBouteille+phpdoc

2025-01-17 08:03 UTC, engcom-Hotel commented
@magento run all tests

2025-01-17 11:35 UTC, engcom-Hotel requested changes
Hello @dimitriBouteille,

Thanks for the contribution!

Please fix the static test failures.

Thanks

2025-01-20 07:36 UTC, engcom-Charlie commented
@magento run all tests

2025-01-20 09:42 UTC, engcom-Charlie commented
Hi @engcom-Hotel,

I have fixed the static test failure. Requesting for review again.

Thank you!

2025-01-21 09:52 UTC, engcom-Hotel approved these changes

2025-01-22 11:04 UTC, engcom-Charlie commented
Manual testing is not required here, as this PR is only updating the doc block. Since the builds are failing, moving it to Extended Testing.

2025-01-22 11:05 UTC, engcom-Charlie commented
@magento run all tests

2025-01-22 13:19 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE

2025-01-23 11:01 UTC, engcom-Charlie commented
One of the Functional B2B test is not consistent in recent 2 builds. The other failing test is a known issue. The failure is neither related to PR nor part of this PR.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39150/1f3e88135fbe06c09f5f7978ab3e22fb/Functional/allure-report-b2b/index.html#categories/988933238a2456b9ee17504aca2226e3/81d53ac848616c13/
<img width="959" alt="image" src="https://github.com/user-attachments/assets/20685fe7-7a15-40d3-9e6c-1e25626d20d1" />

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39150/e13caf98f24f728547ce8509f8927ff9/Functional/allure-report-b2b/index.html#categories

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/23850eac-f6d2-418c-a596-63e6d84d5ed2" />

The Functional EE test failure is neither related to PR nor part of this PR. Its a known failure. Hence moving this PR to Merge in Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39150/cec8fb588ac457b943a9c3ad78a40683/Functional/allure-report-ee/index.html#categories
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/0df2ba3d-9c24-4b84-9f38-8bf8cf9e6a73" />

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39150/cc6af5e36e3896eb108fce2432b803b3/Functional/allure-report-ee/index.html#categories

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/7a4f6c5a-0c08-479d-aad4-7feae5dc9328" />

**Known Issue:**
[ACQE-7460](https://jira.corp.adobe.com/browse/ACQE-7460): CheckingOfPreviewingRegistryUpdateEmailTest

2025-02-17 11:20 UTC, merged