[PHPDOC] Fix bad phpdoc Magento\Eav\Model\ResourceModel\Entity\Attribute\Collection
magento/magento2 pull request #39155
Opened 2024-09-11 07:42 UTC by dimitriBouteille

### Description (*)

This PR fix the bad phpdoc for `\Magento\Eav\Model\ResourceModel\Entity\Attribute\Collection`.

- `joinLeft`: 
   - The first argument can be `string` or `array<string, array>`
   - The 3th argument can be `string` or `array<string>`
 

Here is an example where the type `array` is used :

https://github.com/magento/magento2/blob/d06337ad4d7a5a783030368a8d49aa70da6a5fca/app/code/Magento/Eav/Model/AttributeRepository.php#L114-L118

For example, with PHPSTAN is very complicated to setup the project with level 5 or higher :(

![Capture d’écran du 2024-09-11 09-42-35](https://github.com/user-attachments/assets/025dc925-675e-4145-8da7-dbf85163504d)

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

Setup PHPSTAN with level 5 or higher and run check.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-09-11 07:43 UTC, dimitriBouteille commented
@magento run all tests

2025-10-21 20:20 UTC, lbajsarowicz approved these changes
✅ The change seems to be good.

2025-10-21 20:20 UTC, lbajsarowicz commented
@magento run all tests

2025-11-26 06:55 UTC, engcom-Hotel commented
@magento run all tests

2025-11-26 09:05 UTC, engcom-Hotel requested changes
Hello @dimitriBouteille,

Thank you the collaboration!

Please fix the failed static tests. Other failures seems flaky to me.

2025-12-05 08:05 UTC, engcom-Dash commented
Hello @dimitriBouteille,
Thank you for your contribution. I am taking care of the static tests failure.

2025-12-05 08:08 UTC, engcom-Dash commented
@magento run all tests

2025-12-05 08:08 UTC, dimitriBouteille commented
Hi @engcom-Dash Thanks you !

2025-12-05 10:42 UTC, engcom-Dash commented
@magento run Unit Tests

2025-12-05 18:42 UTC, engcom-Dash commented
@engcom-Hotel I’ve resolved the static test failure. Kindly review so we can move ahead with this PR.

2025-12-08 09:58 UTC, engcom-Hotel approved these changes

2025-12-09 09:34 UTC, engcom-Dash commented
@magento run all tests

2025-12-09 11:08 UTC, engcom-Dash commented
@magento create issue

2025-12-09 13:30 UTC, engcom-Dash commented
Hello @dimitriBouteille

Thanks for the contribution!

✔️ QA Passed

Preconditions:
Install a fresh Magento 2.4-develop.

Manual Testing Scenarios

1. Set up PHPStan in the local environment.
2. Run the analysis command:

`vendor/bin/phpstan analyse /opt/homebrew/var/www/magento2community/magento2/app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/Collection.php`

Before PR Changes
<img width="3180" height="560" alt="image" src="https://github.com/user-attachments/assets/6cbb9b14-d8b6-4d96-ad72-04ba1bcdc045" />
After PR Changes
<img width="3222" height="522" alt="image" src="https://github.com/user-attachments/assets/e3991ff9-a4ee-4d2d-b0d5-14a0bd3e40f6" />

Some Functional Builds are Failing, hence moving this PR for Extended Testing

2025-12-10 08:58 UTC, engcom-Dash commented
@magento run all tests

2025-12-10 13:50 UTC, engcom-Dash commented
The consistent failures in Functional CE, B2B,EE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

**CE**
Build1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39155/f5c42ffb6e009404e5328e1d7dbbdd77/Functional/allure-report-ce/index.html#categories/bdbf199525818fae7a8651db9eafe741
<img width="1598" height="484" alt="image" src="https://github.com/user-attachments/assets/0331ad52-eca7-473a-9cba-05f39c407ae5" />

Build2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39155/c7334ff5502544d383f75acb35cc295d/Functional/allure-report-ce/index.html#categories
<img width="1567" height="393" alt="image" src="https://github.com/user-attachments/assets/f148e496-d740-46f6-babb-35c910cf2143" />


**EE**
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39155/9529ceeb8a1cfb38151f2baa1ad64236/Functional/allure-report-ee/index.html#categories
<img width="1571" height="534" alt="image" src="https://github.com/user-attachments/assets/d1e34426-a5cf-46cf-bd8e-fe2c9e829d79" />

Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39155/c4b27f7e016425e0548934be3ab95793/Functional/allure-report-ee/index.html#categories
<img width="1594" height="544" alt="image" src="https://github.com/user-attachments/assets/3eb7e21a-a471-4a4f-a554-a34b4ed60b1c" />


**B2B**
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39155/7e8ef46a4cb8c82980c36b79ad7355bc/Functional/allure-report-b2b/index.html
<img width="1575" height="464" alt="image" src="https://github.com/user-attachments/assets/115853bf-a43e-49c6-bcbc-0d6a0a38167a" />
Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39155/5cf140095e3da7da4bc810b6ffc9deb0/Functional/allure-report-b2b/index.html
<img width="1573" height="428" alt="image" src="https://github.com/user-attachments/assets/b25f0313-ad59-45d7-95dd-7b6a18c8cb1a" />

**Known Issues**
ApplyTaxesAndFptForSimpleProductWithCanadianPstOriginTest [AC-16096](https://jira.corp.adobe.com/browse/AC-16096)
StorefrontFPTTaxInformationInShoppingCartForCustomerPhysicalQuoteTest [ACQE-9074](https://jira.corp.adobe.com/browse/ACQE-9074)
StorefrontFPTTaxDiscountInShoppingCartTest [AC-16096](https://jira.corp.adobe.com/browse/AC-16096)
StorefrontFPTTaxInformationInShoppingCartForGuestPhysicalQuoteTest [AC-16096](https://jira.corp.adobe.com/browse/AC-16096)
AddingSeveralFPTToSimpleProductTest [AC-16096](https://jira.corp.adobe.com/browse/AC-16096)
AdminFPTIncludingAndExcludingTaxVisibleOnNegotiableQuotePageTest [AC-16096](https://jira.corp.adobe.com/browse/AC-16096)
AdminFPTVisibleOnNegotiableQuotePageTest [AC-16096](https://jira.corp.adobe.com/browse/AC-16096)

Hence, Moving this PR to Merge In Progress

2025-12-16 06:25 UTC, merged