Allow Lighthouse scan to reach 100% Accessibility on Homepage
magento/magento2 pull request #39164
Opened 2024-09-12 13:20 UTC by Serfe-com

### Description (*)
We adjust the rendering of the menu and small adjustment on the contrast for the page to allow to hit 100% on accessibility on the home, PDP y PLP on Luma

### Related Pull Requests
[38617](https://github.com/magento/magento2/pull/38617)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39054
2. Fixes magento/magento2#35889

### Manual testing scenarios (*)

1. Load the website on the homepage with Luma
2. Trigger a lighthouse scan enabling the accessibility scan.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-09-12 13:32 UTC, Serfe-com commented
@magento add to contributors team

2024-09-12 13:33 UTC, Serfe-com commented
@magento I am working on this

2024-09-12 13:33 UTC, Serfe-com commented
@magento I am working on this

2024-09-12 13:45 UTC, Serfe-com commented
@magento run all tests

2024-09-12 14:05 UTC, Serfe-com commented
https://github.com/magento run all tests

2024-09-17 14:30 UTC, Franciscof-Serfe commented
@magento give me 2.4-develop instance
@magento run all tests

2024-09-18 17:18 UTC, Serfe-com commented
@magento run all tests

2024-10-14 14:39 UTC, Franciscof-Serfe commented
@magento give me 2.4-develop instance
@magento run all tests

2024-10-16 19:18 UTC, Franciscof-Serfe commented
@magento  give me 2.4-develop instance

2025-02-19 06:25 UTC, engcom-Hotel commented
@magento run all tests

2025-02-19 13:03 UTC, engcom-Hotel requested changes
Hello @Serfe-com,

Thanks for the contribution!

Please fix the failed static tests.

Thanks

2025-02-19 13:41 UTC, Franciscof-Serfe commented
@magento run all tests

2025-02-19 18:39 UTC, hostep requested changes

2025-02-19 18:39 UTC, hostep commented on app/code/Magento/Theme/view/frontend/templates/html/sections.phtml
> + * Copyright 2024 Adobe
Year in copyright header should be the year the file was first added in git, so in this case 2014 instead of 2024

2025-02-19 18:39 UTC, hostep commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +//  * Copyright 2024 Adobe
Year in copyright header should be the year the file was first added in git, so in this case 2017 instead of 2024

2025-02-19 18:39 UTC, hostep commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +                    //  ToDo: improve .lib-background-gradient() to support diagonal gradient;
this extra `;` at the end isn't needed I believe, can you remove it again?

2025-02-19 21:10 UTC, hostep commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +//  * Copyright 2024 Adobe
@Serfe-com: this one as well please, it looks like you reverted it back to 2024 in your last commit, thanks! :)

2025-02-20 06:19 UTC, engcom-Hotel commented
@magento run all tests

2025-02-20 10:46 UTC, engcom-Hotel requested changes
Hello @Serfe-com,

There are some [static test](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39164/aa5e6370fdc6bcfcb0a23af60447b59f/Statics/console-error-logs.html) failures, please fix those.

And look into this r[eview comment](https://github.com/magento/magento2/pull/39164#discussion_r1962378038) made by @hostep.

Thanks

2025-02-20 14:28 UTC, Franciscof-Serfe commented
@magento run all tests

2025-02-20 15:25 UTC, Serfe-com commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +                    //  ToDo: improve .lib-background-gradient() to support diagonal gradient;
I'm adding it to avoid getting this Static error:

```
PHP Code Sniffer detected 1 violation(s): 

FILE: /var/www/html/app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
--------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------
 187 | WARNING | Style definitions must end with a semicolon
 187 | WARNING | Expected 1 space after colon in style definition; newline found
--------------------------------------------------------------------------------------------------
```

Seems that the coding standard rule is not understanding the comment.

Adding it back so static tests pasess.

2025-02-20 17:05 UTC, hostep commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +                    //  ToDo: improve .lib-background-gradient() to support diagonal gradient;
Why have you added this semicolon back?

2025-02-20 17:22 UTC, Serfe-com commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +                    //  ToDo: improve .lib-background-gradient() to support diagonal gradient;
See https://github.com/magento/magento2/pull/39164#discussion_r1963793533

2025-02-20 17:58 UTC, Franciscof-Serfe commented
@magento run all tests

2025-02-20 19:39 UTC, Serfe-com commented
@magento run all tests

2025-02-20 20:17 UTC, Serfe-com commented
https://github.com/magento run all tests

2025-02-20 21:39 UTC, Serfe-com commented
@magento run all tests

2025-02-21 06:45 UTC, hostep commented on app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
> +                    //  ToDo: improve .lib-background-gradient() to support diagonal gradient;
Okay, indeed, seems like a bug in coding standards unfortunately :(

2025-02-24 06:06 UTC, engcom-Hotel commented
@magento run all tests

2025-02-24 09:27 UTC, engcom-Hotel approved these changes

2025-02-24 16:45 UTC, hostep approved these changes

2025-02-26 06:46 UTC, engcom-Bravo commented
@magento run all tests

2025-02-26 07:53 UTC, engcom-Bravo commented
Hi @Serfe-com,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Load the website on the homepage with Luma
- Trigger a lighthouse scan enabling the accessibility scan.



**Before:** :heavy_multiplication_x: 

<img width="1440" alt="Screenshot 2025-02-26 at 11 56 27 am" src="https://github.com/user-attachments/assets/0ce07c29-6a3f-4f85-a67d-d6f91249f056" />







**After:** :heavy_check_mark: 

<img width="1440" alt="Screenshot 2025-02-26 at 12 28 42 pm" src="https://github.com/user-attachments/assets/54c720f7-0846-4d1c-9108-cab4f6d800d3" />





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-03-06 08:27 UTC, engcom-Dash commented
@magento run all tests

2025-03-06 10:50 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests EE

2025-03-07 07:29 UTC, engcom-Dash commented
For Functional B2B the consistent test failure is the known issue and Jira raised for the same. Hence moving this PR to Merge in Progress.


**Build 1:**
Function Tests B2B: [https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39164/16bce3e6831e77179906ff3f93fed8c1/Functional/allure-report-b2b/index.html#categories/45dbe0d46e96664d663d093b248a272b/a09f89b84515f9bf/](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39164/16bce3e6831e77179906ff3f93fed8c1/Functional/allure-report-b2b/index.html#categories/45dbe0d46e96664d663d093b248a272b/a09f89b84515f9bf/)

![image](https://github.com/user-attachments/assets/275d5e90-7b05-43d4-ac6a-096cdaba1e26)

**Build 2:**
Functional Tests B2B: [https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39164/3cc4d7ab0fe5ad32fa3affac5070c15e/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39164/3cc4d7ab0fe5ad32fa3affac5070c15e/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d)

<img width="1424" alt="Screenshot 2025-03-28 at 4 28 47 PM" src="https://github.com/user-attachments/assets/bc7b5d4d-a15f-4c69-ad93-5ca6cf9be79c" />

Known Issue: AdminValidateMixedNestedCategoryInWidgetTest [ACQE-7641](https://jira.corp.adobe.com/browse/ACQE-7641)

2025-03-18 14:45 UTC, Franciscof-Serfe commented
Hi Team, @engcom-Bravo @engcom-Dash @engcom-Hotel,  

Would it be appropriate to label this PR as https://github.com/magento/magento2/labels/Progress%3A%20ready%20for%20testing if it has already been tested?  

I've noticed that in other PRs, the https://github.com/magento/magento2/labels/Progress%3A%20accept label is applied after the *Ready for Testing* stage.  

Could you confirm if this is the correct status?  

Thank you!  

Best regards,  
Francisco

2025-03-19 10:41 UTC, engcom-Dash commented
Hi @Franciscof-Serfe We were facing some challenges with bot. I have updated the correct labels now. Thank You!!

2025-04-16 11:05 UTC, merged

2025-11-26 08:01 UTC, mikakoi commented
Noticed a small problem with the pr. The pr removes data-role="content" from the content elements, but the tabs.js uses by default a selector [data-role=content] to hide the content elements when they're not active. The end result is not pretty
<img width="828" height="516" alt="image" src="https://github.com/user-attachments/assets/27c64c53-ac8d-4038-893d-49954ddd5808" />