feat: disable the setup route by default for nginx
magento/magento2 pull request #39228
Opened 2024-09-30 23:03 UTC by SamJUK

### Description (*)
Add access control to the `/setup/` route within the default nginx configuration. 
With a default of deny all.

### Fixed Issues (if relevant)
1. Closes: #39227 

### Manual testing scenarios (*)
Test on BOTH a new uninstantiated instance, as well as a preinstalled instance. 

1. Navigate to `/setup/` expect to see a 403/401 error
2. Add your IP Address to the nginx config & reload
3. Navigate to `/setup/` expect to see the setup page.

### Questions or comments
Happy for this to be closed another way (eg removal of the route all together). 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-10-11 20:23 UTC, SamJUK commented
@magento run all tests

2025-05-14 04:32 UTC, engcom-Hotel commented
@magento run all tests

2025-05-14 06:58 UTC, engcom-Hotel requested changes
Hello @SamJUK,

Thank you for your contribution!

The changes look good for Nginx users. However, I have noticed that this issue is also reproducible for Apache users. For consistency, could we also address this issue for Apache users?

Although there is no sample file for Apache as there is for Nginx, could we consider providing a fix or suggestion for Apache users when creating a virtual host for their Magento instance?

Thank you.

2025-05-14 10:15 UTC, SamJUK commented
@engcom-Hotel 

I am not overly familiar with Apache, but I've pushed a change to the `setup/.htaccess` file. Which aligns with how the access control is implemented for the `app` / `var` folders, and should cover Apache on default installs.

2025-05-15 05:00 UTC, engcom-Hotel commented
@magento run all tests

2025-05-15 11:01 UTC, engcom-Hotel approved these changes

2025-05-16 09:51 UTC, engcom-Bravo commented
Hi @SamJUK,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**


Navigate to https://site.com/setup/



**Before:** :heavy_multiplication_x: 


<img width="1440" alt="Screenshot 2025-05-16 at 2 29 25 pm" src="https://github.com/user-attachments/assets/c0ff88be-cb9b-426b-b5a7-6b15b6814f63" />



**After:** :heavy_check_mark: 



<img width="1440" alt="Screenshot 2025-05-16 at 3 17 22 pm" src="https://github.com/user-attachments/assets/fd4141f7-e754-4da4-ab2c-d02dde35fd9c" />



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-05-19 05:19 UTC, engcom-Dash commented
@magento run all tests

2025-05-19 10:13 UTC, engcom-Dash commented
@magento run all tests

2025-05-19 12:53 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2025-05-19 14:50 UTC, engcom-Dash commented
One of the consistent test failure for Functional B2B is known Issues and JIRA is raised for them. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39228/8b57a632dc6d5a15bc9b938495750d18/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/94946482-a1c4-49d8-a709-9f68d7382345)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39228/31ea62ca34431ab1a47457dc1efe3f00/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/fad20c46-9f9a-4b19-acc8-183dd612e998)

**Known Issue** : [StoreFrontSimpleProductWithSpecialAndTierDiscountPriceTest ACQE-7971](https://jira.corp.adobe.com/browse/ACQE-7971 )

Consistent test failure for Functional CE is known Issues and JIRA is raised for them.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39228/ec3ab5e68893b3dcd944ee063acf24e0/Functional/allure-report-ce/index.html#categories/1ebe0280aba7ee40465acd3f13b81139/6274427d1be0a9f1/

![image](https://github.com/user-attachments/assets/a29d971d-30b5-48ee-8f9e-6b9ad6a2603a)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39228/0d1d32a59b49011bd15aeafe3e541c92/Functional/allure-report-ce/index.html#categories/1ebe0280aba7ee40465acd3f13b81139/829832ca4fd9c463/

![image](https://github.com/user-attachments/assets/661b54bd-421c-421d-a0f3-2fb057b06a03)

**Known Issue:** [StorefrontEnsureThatAccordionAnchorIsVisibleOnViewportOnceClickedTest ACQE-7683](https://jira.corp.adobe.com/browse/ACQE-7683)

Failures in Functional EE are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39228/d7b2797e97996e82c4635c3ab31a465c/Functional/allure-report-ee/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/d5d6bbf6037cf326/

![image](https://github.com/user-attachments/assets/ae4d86cb-f7fd-471d-b9eb-eaabe1daf5b9)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39228/045b291bde6acf3e98bc7faa72841dbb/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/723c4d76-f771-431d-8a43-c12845512a58)

Hence moving this PR to Merge In Progress.

2025-06-26 06:32 UTC, merged