Copyedit: change "coping" to "copying"
magento/magento2 pull request #39307
Opened 2024-10-28 20:28 UTC by ckd

### Description (*)

Minor copyedit to correct spelling of "copying"

### Related Pull Requests
n/a

### Fixed Issues (if relevant)
n/a

### Manual testing scenarios (*)
n/a

### Questions or comments
n/a

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [X] All automated tests passed successfully (all builds are green)

2024-10-29 11:03 UTC, engcom-Hotel commented
@magento create issue

2025-02-12 11:26 UTC, ihor-sviziev approved these changes

2025-02-17 04:47 UTC, engcom-Hotel commented
@magento run all tests

2025-02-17 07:37 UTC, engcom-Hotel requested changes
Hello @ckd,

Thanks for the contribution!

The changes seem good to us but please fix the static test failures.

Also I want to suggest to fix a typo in the below line as well (startegt to strategy):

https://github.com/magento/magento2/blob/0057e06e480fc1df332f71971bdafae9a8d5ebde/app/code/Magento/ImportExport/Model/Import.php#L82

2025-02-18 22:41 UTC, ckd commented
Hi @engcom-Hotel! Added the additional typo correction to the PR, but the static test failures seem to be upstream and unrelated to this change

2025-02-19 06:17 UTC, engcom-Hotel commented
@magento run all tests

2025-02-19 12:23 UTC, engcom-Hotel requested changes
Thanks @ckd, for making the changes.

But we are still having static test failures. Please fix those.

2025-02-19 13:19 UTC, ckd commented
@engcom-Hotel those failures are out of scope for this PR, they need to be fixed upstream

2025-02-20 07:35 UTC, engcom-Hotel commented
Hello @ckd, we can see the [copywrite failures](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/ffb434edae3d0c24255e2e83a3b01bf7/Statics/console-error-logs.html) on the files in this PR. You just need to make the changes in the file as follows:

```
Copyright [year code created] Adobe 
All Rights Reserved.
```

2025-02-20 17:20 UTC, ckd commented
ah hah! there we go

2025-02-21 08:51 UTC, engcom-Hotel commented
@magento run all tests

2025-02-21 09:02 UTC, engcom-Hotel requested changes
Hello @ckd,

Please correct the year as per the below review comment.

Thanks

2025-02-21 09:02 UTC, engcom-Hotel commented on app/code/Magento/ImportExport/Model/Import.php
> + * Copyright 2013 Adobe
The file has been created in 2011, so please make 2011 instead of 2013

2025-02-21 16:04 UTC, ckd commented on app/code/Magento/ImportExport/Model/Import.php
> + * Copyright 2013 Adobe
Hah, we were so close! But the year has been updated

2025-02-24 06:08 UTC, engcom-Hotel commented
@magento run all tests

2025-02-24 09:33 UTC, engcom-Hotel commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Unit Tests

2025-02-24 09:36 UTC, engcom-Hotel requested changes
Hello @ckd,

Thanks for fixing the issues!

But we are still having some static test failures. Please fix those and then run all tests to verify.

Thanks

2025-02-26 11:30 UTC, engcom-Hotel commented
Hello @ckd,

We are picking this PR for further processing.

Thanks

2025-02-26 11:36 UTC, engcom-Hotel commented
@magento run all tests

2025-02-26 15:28 UTC, engcom-Hotel commented
@magento run Static Tests

2025-02-27 06:59 UTC, engcom-Hotel approved these changes

2025-02-28 09:10 UTC, engcom-Bravo commented
Hi @ckd,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


Thanks.

2025-03-04 05:20 UTC, engcom-Dash commented
@magento run all tests

2025-03-04 09:32 UTC, del10131 commented
@magento run all tests

2025-03-04 09:33 UTC, engcom-Dash commented
@magento run all tests

2025-03-04 13:01 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE

2025-03-05 10:48 UTC, engcom-Dash commented
Few test failures in recent 2 builds for functional CE are not consistent. For Functional B2B the consitent test failure is the known issue and Jira raised for the same. Hence moving this PR to Merge in Progress

Build 1: 
Functional Tests B2B: [https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/e460afd8d6a37b08d8a9c594bb5fbaba/Functional/allure-report-b2b/index.html#categories/45dbe0d46e96664d663d093b248a272b/6928e81e6c8450d2/
](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/e460afd8d6a37b08d8a9c594bb5fbaba/Functional/allure-report-b2b/index.html#categories/45dbe0d46e96664d663d093b248a272b/6928e81e6c8450d2/)

![image](https://github.com/user-attachments/assets/e8ce71f4-d121-485b-bf0c-d1f59221de0c)

Build 2:
Functional Tests B2B: [https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/eccb216ff0aa7c354ca445f7d101fdf3/Functional/allure-report-b2b/index.html#categories/45dbe0d46e96664d663d093b248a272b/4f01d090add31805/](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/eccb216ff0aa7c354ca445f7d101fdf3/Functional/allure-report-b2b/index.html#categories/45dbe0d46e96664d663d093b248a272b/4f01d090add31805/)
![image](https://github.com/user-attachments/assets/7f921b91-e594-4a06-9304-424e9f379c46)

Build 1:
Functiona Tests CE: [https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/fd46e1d9d69254dadaabc1dfb9a0903b/Functional/allure-report-ce/index.html#categories/a644910ae0cb11e839a98baa21929b76/b2f13416764bbc1f/](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/fd46e1d9d69254dadaabc1dfb9a0903b/Functional/allure-report-ce/index.html#categories/a644910ae0cb11e839a98baa21929b76/b2f13416764bbc1f/)

![image](https://github.com/user-attachments/assets/bfb8045f-c20c-429b-8dda-e4eb29bf6076)

Build 2:
Functiona Tests CE: [https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/e7e360d534b06b7bd6e8a670311d2c1b/Functional/allure-report-ce/index.html#categories/c5e17feaf80ce819bae3628b8541c514/20be3b24b1e79581/](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39307/e7e360d534b06b7bd6e8a670311d2c1b/Functional/allure-report-ce/index.html#categories/c5e17feaf80ce819bae3628b8541c514/20be3b24b1e79581/)

![image](https://github.com/user-attachments/assets/648c00dd-4b8c-41c8-b7e4-515f2668c056)


Known Issue: AdminValidateMixedNestedCategoryInWidgetTest [https://jira.corp.adobe.com/browse/ACQE-7641](url)

2025-04-02 23:52 UTC, merged