increase minimum password length
magento/magento2 pull request #39319
Opened 2024-11-02 12:20 UTC by torhoehn

### Description (*)
PCI 4.0 requires a minimal password length of 12 characters, so it has to be changed from 7 to 12.

### Manual testing scenarios (*)

1. Change password of an existing admin account.
2. It should fail to change the password if less than 12 characters are used.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-11-02 14:18 UTC, Morgy93 commented
This one needs to be changed as well: https://github.com/magento/magento2/blob/2.4-develop/lib/web/mage/validation.js#L688

2024-11-02 17:11 UTC, torhoehn commented
> This one needs to be changed as well: https://github.com/magento/magento2/blob/2.4-develop/lib/web/mage/validation.js#L688

Thanks for pointing out, I changed that file as well.


I will leave this PR as simple as it is, to hopefully get it merged fast. I will create another PR one on top of it, to make the values configurable (https://github.com/magento/community-features/issues/333).

2024-11-04 08:22 UTC, sprankhub commented
@torhoehn, you also need to update the error message mentioned by @Morgy93 earlier.

2024-11-04 08:56 UTC, ihor-sviziev commented
I do agree that is has to be improved for admin users, but should it be also enforced for clients?

2024-11-04 13:57 UTC, torhoehn commented
> @torhoehn, you also need to update the error message mentioned by @Morgy93 earlier.

Ah sorry, I will change that as well.

> I agree that it needs to be improved for admin users, but should it also be enforced for clients?

I will check that. But to keep it as simple as possible I would like to create another PR for that, because I don't know how many changes will be needed for that.

2024-11-04 14:00 UTC, sprankhub approved these changes

2024-11-05 11:04 UTC, engcom-Hotel commented
@magento create issue

2024-11-07 20:46 UTC, torhoehn commented
@magento run all tests

2024-11-15 11:05 UTC, engcom-Hotel commented
@magento run all tests

2024-11-15 11:09 UTC, engcom-Hotel requested changes
Hello @torhoehn,

Thanks for the collaboration!

I think we can cover this change with an automated test, so please do the needful and also please fix the failed tests.

Thanks

2024-11-15 19:47 UTC, torhoehn commented
https://github.com/magento run all tests

2024-11-15 19:47 UTC, torhoehn commented
@magento run all tests

2024-11-15 21:26 UTC, torhoehn commented
@magento run all tests

2024-11-16 09:45 UTC, torhoehn commented
@magento run all tests

2024-11-18 11:57 UTC, ihor-sviziev commented
@torhoehn 
> @ihor-sviziev I will check that. But to keep it as simple as possible I would like to create another PR for that, because I don't know how many changes will be needed for that.


Does it mean, that these changes are applied only for admin users, right? If so - then fine. 
I just wonder about asking for a secure passwords for clients who buy on the websites - such a change here might significantly reduce conversion.

2024-11-19 10:39 UTC, ihor-sviziev commented
@magento run all tests

2024-11-20 08:23 UTC, engcom-Hotel commented
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Static Tests, Unit Tests, WebAPI Tests

2024-11-20 10:22 UTC, engcom-Hotel commented
@magento run Static Tests

2024-11-20 11:20 UTC, engcom-Hotel commented
@magento run Database Compare

2024-11-20 14:23 UTC, engcom-Hotel requested changes
Hello @torhoehn,

Thanks for the collaboration!

The changes seems good to me but please fix the failed static tests. Other failed tests seems flaky to me.

Thanks

2024-11-21 19:46 UTC, torhoehn commented
@engcom-Hotel Are you sure that the static tests depends on my change? I changed the file but the test fails in line 643 which I didn't touch.

2024-11-21 20:04 UTC, torhoehn commented
@engcom-Hotel

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/e2665884321236cc68820a770c5457d1/Statics/allure-report-b2b/index.html
I changed the validation.js, but later than the mentioned line here.

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/e2665884321236cc68820a770c5457d1/Statics/console-error-logs.html
I didn't touch any Copyright or inheritdoc. What needs to be changed here?

2024-11-22 06:48 UTC, engcom-Hotel commented
Hello @torhoehn,

This is part of the latest Adobe Copyright guidelines and it is now covered by static test analysis. So from now on we need to update the copyright as below in the updated files:

```
Copyright [year code created] Adobe 
All Rights Reserved.
```
Please do the needful.

Thanks

2024-11-22 07:31 UTC, torhoehn commented
@magento run all tests

2024-11-22 15:05 UTC, hostep commented
@torhoehn: the year in the copyright header should be the year when the file was first created, so 2024 is wrong, you should check the git history for each file to find the correct year. For example, the file `app/code/Magento/User/Model/UserValidationRules.php` got created in 2015, `lib/web/mage/validation.js` in 2014, ...

2024-11-24 12:15 UTC, torhoehn commented
@hostep Thank you, I changed it accordingly.

2024-11-25 06:23 UTC, engcom-Hotel commented
@magento run all tests

2024-11-25 08:36 UTC, engcom-Hotel commented
@magento Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests, WebAPI Tests

2024-11-25 09:03 UTC, engcom-Hotel commented
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests, WebAPI Tests

2024-11-25 10:12 UTC, engcom-Hotel requested changes
Hello @torhoehn,

Some automated tests are still failing. Please fix those.

Thanks

2024-11-25 20:54 UTC, torhoehn commented
@magento run all tests

2024-11-26 07:41 UTC, torhoehn commented
@magento run all tests

2024-11-26 16:05 UTC, torhoehn commented
@engcom-Hotel Could you please check if all tests regarding CE are solved?

2024-11-27 06:56 UTC, engcom-Hotel commented
@magento run all tests

2024-11-27 09:35 UTC, engcom-Hotel commented
Hello @torhoehn,

We can still see some failures on the PR. Please click on `Details` to see the issues in automated builds.

We also want to inform you that, as this is a feature request, we are currently in discussion with the Product Owner (PO) to determine the next steps for processing this PR. In the meantime, we are moving this PR to the `On Hold` status.

Thanks

2024-11-28 12:45 UTC, torhoehn commented
@magento run all tests

2024-11-28 21:40 UTC, torhoehn commented
@magento run all tests

2024-12-02 19:54 UTC, torhoehn commented
@magento run all tests

2024-12-03 10:17 UTC, engcom-Hotel requested changes
Hello @torhoehn,

We have go-ahead on this PR from the PO. So we have picked this PR for review. As part of the review process we have seen the below error due to the code changes:

![image](https://github.com/user-attachments/assets/49aa33f8-900b-441b-926f-18f6cf6b414c)

Please look into this and resolve the same. The SS is from the Jenkins.

Thanks

2024-12-03 10:21 UTC, torhoehn commented
@engcom-Hotel Can you please guide me to find the relevant file that needs to be changed?

2024-12-04 20:10 UTC, torhoehn commented
@engcom-Hotel E.g. I didn't find any string in the project that contains `Installing Magento...`. Are you sure that the installation is part of the actual codebase of this repository?

2024-12-10 06:44 UTC, engcom-Hotel commented
Hello @torhoehn,

I will get back to you on this, please allow me some time.

Thanks

2024-12-18 10:25 UTC, engcom-Hotel commented
@magento run all tests

2024-12-20 04:27 UTC, engcom-Hotel commented
Hello @torhoehn,

We are in discussion with the internal team regarding this PR. We will get back to you soon on this. Meanwhile, we are moving this PR `On Hold`.

Thanks

2025-01-07 08:13 UTC, avoelkl commented
Whats the status of this?

PCI 4.0 will be required from 1.4.2025 on. Can we expect this change in the next release on February 11, 2025?
Patch release for 2.4.7, 2.4.6, 2.4.5, and 2.4.4

2025-01-16 13:40 UTC, engcom-Hotel commented
@magento run all tests

2025-01-23 12:10 UTC, engcom-Hotel commented
@magento run all tests

2025-01-28 07:39 UTC, engcom-Hotel commented
@magento run all tests

2025-01-28 11:40 UTC, engcom-Hotel commented
@magento run WebAPI Tests

2025-01-28 14:40 UTC, engcom-Hotel commented
@magento run WebAPI Tests

2025-01-29 06:54 UTC, engcom-Hotel commented
@magento run Integration Tests, Static Tests

2025-01-29 09:18 UTC, engcom-Hotel commented
@magento run Static Tests, WebAPI Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2025-01-29 09:22 UTC, engcom-Hotel commented
@magento run all tests

2025-01-29 15:07 UTC, engcom-Hotel commented
@magento run Functional Tests CE

2025-01-30 07:25 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests, WebAPI Tests

2025-01-30 10:55 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Static Tests, WebAPI Tests

2025-01-31 09:44 UTC, engcom-Hotel commented
Functional Test B2B and EE are failing with the below test:

MAGETWO-94107: Checking of Previewing Registry Update Email: The failure is a known issue and it is not related to this PR change. The JIRA for the same is https://jira.corp.adobe.com/browse/ACQE-7460

![image](https://github.com/user-attachments/assets/b416b9c4-f532-4ee5-ba17-50e393f7b19f)

Also, the WebAPI test seems flaky to us. Hence moving further with this PR.

Thanks

2025-01-31 09:45 UTC, engcom-Hotel approved these changes

2025-02-03 05:20 UTC, engcom-Bravo commented
@magento run all tests

2025-02-03 11:32 UTC, engcom-Bravo commented
Hi @torhoehn,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**


- Change password of an existing admin account.
- It should fail to change the password if less than 12 characters are used.


**Before:** :heavy_multiplication_x: 

`The password must be at least 7 characters in length and must include at least one alphabetic and at least one numeric character
`



**After:** :heavy_check_mark: 


`PCI 4.0 passwords must be a minimum of 12 characters long, including a mix of uppercase and lowercase letters, numbers, and special characters`

<img width="1348" alt="Screenshot 2025-02-03 at 11 38 35 am" src="https://github.com/user-attachments/assets/4aef727d-5398-4d9f-bade-f86de73b01c1" />





<img width="522" alt="Screenshot 2025-02-03 at 11 40 20 am" src="https://github.com/user-attachments/assets/c8386b62-d1bb-478b-8671-8926ecaa6240" />









Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-02-04 06:32 UTC, engcom-Charlie commented
@magento run all tests

2025-02-04 15:12 UTC, engcom-Hotel commented
@magento run Unit Tests, Static Tests, Integration Tests, Functional Tests EE, Functional Tests B2B, Functional Tests CE

2025-02-05 10:30 UTC, engcom-Hotel commented
@magento run Unit Tests, Static Tests, Integration Tests, Functional Tests EE, Functional Tests B2B, Functional Tests CE

2025-02-07 11:22 UTC, engcom-Hotel commented
@magento run Integration Tests

2025-02-07 17:09 UTC, engcom-Hotel commented
@magento run all tests

2025-02-10 06:21 UTC, engcom-Hotel commented
@magento run all tests

2025-02-10 11:13 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2025-02-10 16:46 UTC, engcom-Hotel commented
The failed functional tests are different in 2 consecutive runs, hence seems flaky to us. Please refer to the below screenshot:

### Functional Test CE
[Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/795fc3a8f378e5b4e4259961562eb447/Functional/allure-report-ce/index.html#categories/e2c2381ea67856a9a7942c832e38e790/5ee36e82bce23b14/)
![image](https://github.com/user-attachments/assets/096e2d1d-3be1-4299-bca7-8680796dacff)

[Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/6bae1fc2224c0e624cd3ce4141db0f05/Functional/allure-report-ce/index.html#categories)
![image](https://github.com/user-attachments/assets/1d6296bd-379c-453c-a0d3-3152c539fdf4)

### Functional Test B2B
[Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/64aeb88b2fa66289141e6ef12ad5e252/Functional/allure-report-b2b/index.html#categories)

![image](https://github.com/user-attachments/assets/c000ef73-ef33-4c8f-b11e-086c70db3b47)

[Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/e98c720902ee99c0ae1a50adf726ebfe/Functional/allure-report-b2b/index.html#categories/8e8b0916f0102b4ac39740ea56c5cb93/8aeaac434db7b358/)

![image](https://github.com/user-attachments/assets/5606052c-0c50-4629-858b-63802fa7c4ab)


### Static Test failure
For Static test failure, we have raised an approval JIRA: https://jira.corp.adobe.com/browse/AC-13895

2025-02-11 07:04 UTC, engcom-Hotel commented
@magento run Unit Tests

2025-02-13 08:23 UTC, engcom-Hotel commented
@magento run Unit Tests

2025-02-13 09:33 UTC, engcom-Hotel commented
@magento run Unit Tests

2025-02-17 07:13 UTC, engcom-Hotel commented
@magento run all tests

2025-02-18 04:58 UTC, engcom-Charlie commented
@magento run all tests

2025-02-18 16:23 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

2025-02-21 05:22 UTC, engcom-Charlie commented
@magento run all tests

2025-02-21 10:20 UTC, engcom-Charlie commented
@magento run all tests

2025-02-21 12:48 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2025-02-21 18:09 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2025-02-24 05:47 UTC, engcom-Charlie commented
The Functional CE and EE test failures are not consistent in recent 2 builds. The failures are neither related to PR nor part of this PR.

**Functional CE**
**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/14d7eaf285907946221dbe513bf0b107/Functional/allure-report-ce/index.html#categories
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/92350997-3ec6-4968-8a3e-b09dc48a023c" />


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/2aac4463e121be43e4e62c9f28e7783d/Functional/allure-report-ce/index.html#categories

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/8069f302-59e9-42f3-85ca-7ab820a92f44" />

**Functional EE**
**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/857ccf3c51b35390da28ab3b4ed2ce26/Functional/allure-report-ee/index.html#categories

<img width="1128" alt="image" src="https://github.com/user-attachments/assets/d62ae2c5-0d1b-4f0d-a791-4f039de0905d" />

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/27564117678871934702a7438e158e4f/Functional/allure-report-ee/index.html#categories

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/3c24542d-6365-44a8-bacb-3876177f4c38" />

**Functional B2B**

One of the Functional B2B test is not consistent in recent 2 builds. The other failing tests are known issues. The failures are neither related to PR nor part of this PR.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/eb8713aaf894c42fa4a8cf491ec08408/Functional/allure-report-b2b/index.html#categories

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/e6b4f4f9-4849-462e-88ea-067c9a761366" />


**Run 2**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39319/1c3a01b7d390704dcfe5461632a2230b/Functional/allure-report-b2b/index.html#categories/ff086893d1b2f6d93d2b926c3d303ab7/c0205ab6b87ad11b/

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/5e7ca293-639d-4eac-8145-c1eeebbcc32f" />

**Known Issues:**
[AC-13447](https://jira.corp.adobe.com/browse/AC-13447): StorefrontQuoteCanBeRenamedUntilLockedTest
[ACQE-7594](https://jira.corp.adobe.com/browse/ACQE-7594): AdminQuoteLevelPercentDiscountNotRemovedWhenDiscountCanBeDistributedTest

2025-02-24 05:49 UTC, engcom-Charlie commented
Considering the approval JIRA for Static test failure as mentioned [here](https://github.com/magento/magento2/pull/39319#issuecomment-2648640667), moving this PR to Merge in Progress now,

2025-02-26 04:51 UTC, engcom-Charlie commented
@magento run all tests

2025-03-07 09:17 UTC, engcom-Hotel commented
@magento run all tests

2025-03-07 12:13 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static tests, WebAPI Tests

2025-03-10 07:20 UTC, engcom-Hotel commented
Moving it back to `Changes Requested` due to some failures in the automated builds.

2025-03-10 07:24 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

2025-03-10 10:46 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2025-03-18 09:31 UTC, engcom-Hotel commented
As the PR is already been tested, we can refer to this comment for testing comment: https://github.com/magento/magento2/pull/39319#issuecomment-2630690526

Moving this PR in extended testing as Functional B2B is still failing.

@magento run Functional Tests B2B

2025-03-18 12:01 UTC, engcom-Hotel commented
@magento run Functional Tests B2B

2025-03-20 07:35 UTC, engcom-Hotel commented
Functional B2B failures seems does not related to this PR changes. Please refer to the below JIRA's where these failures will address:

[NO TESTCASEID]StorefrontVerifySearchTermEntityRedirectTest : https://jira.corp.adobe.com/browse/ACQE-7705
B2B-4518: https://jira.corp.adobe.com/browse/ACQE-7568
B2B-4476: https://jira.corp.adobe.com/browse/ACQE-7568

For `Static test` failure, we already have an approval. Hence moving this PR to `Merge in progress`.

Thanks

2025-03-25 11:54 UTC, engcom-Charlie commented
Currently we are getting PAT failures on the mainline PR while trying to merge this PR. In order to proceed with this change, we need to make some updates on infrastructure and other repositories too. I have created internal [JIRA](https://jira.corp.adobe.com/browse/ACPT-2065) for the same. 

Once its done, I will resume the work on this PR. Till then moving it to On Hold.

2025-08-27 17:55 UTC, hostep commented
It looks like Magento internal devs fixed this in a completely different (some may say over-engineered) way in [ACP2E-4044: [QUANS]Admin Password Policy Does Not Meet PCI DSS 4.0 Compliance (Minimum 12 Characters)](https://github.com/magento/magento2/commit/0cbb3afb85e04cad8ddaa13627caaeac3ced19f8)

So I guess we can close this PR here ... ? Thanks for the effort @torhoehn!

2025-09-02 06:52 UTC, engcom-Charlie commented
Hi @torhoehn,

As per [this](https://github.com/magento/magento2/pull/39319#issuecomment-3229184919), the feature which is getting addressed in this PR has been delivered in other way, so can we close this PR.

2025-09-09 05:57 UTC, engcom-Charlie commented
Thank you for your contribution @torhoehn. As mentioned [above](https://github.com/magento/magento2/pull/39319#issuecomment-3244021287) since the password length feature has been taken care, closing this PR. Please feel free to reopen for any further query.

2025-09-09 05:57 UTC, closed without merging