Developer Experience: Quote AbstractItem code style (SwiftOtter's SOP-348)
magento/magento2 pull request #39331
Opened 2024-11-05 14:05 UTC by lbajsarowicz

### Description (*)

This Pull Request fixes misleading method declarations for Abstract Item methods.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-11-05 14:06 UTC, lbajsarowicz commented
@magento run all tests

2024-11-07 13:35 UTC, engcom-Hotel commented
@magento create issue

2024-12-12 06:57 UTC, engcom-Hotel reviewed
Hello @lbajsarowicz,

Thanks for your contribution!

Kindly resolve the conflicts on this PR, so we can proceed with the review. Meanwhile moving this PR `On Hold`.

Thanks

2024-12-12 11:54 UTC, lbajsarowicz commented
@magento run all tests

2024-12-12 11:55 UTC, lbajsarowicz commented
@engcom-Hotel Fixed.

2024-12-13 08:59 UTC, engcom-Hotel requested changes
Hello @lbajsarowicz,

Thanks for the contribution!

The changes seems good to me, but please fix the static test failures.

2024-12-13 10:20 UTC, lbajsarowicz commented
@magento run all tests

2024-12-16 10:43 UTC, engcom-Hotel approved these changes

2024-12-19 06:11 UTC, engcom-Dash commented
@magento run all tests

2024-12-19 11:25 UTC, engcom-Dash commented
Manual testing is not required here, as this PR only updates the docblock and improves the code style. Since the builds are failing, moving it to Extended Testing.

2024-12-19 11:29 UTC, engcom-Dash commented
@magento run Semantic Version Checker, Integration Tests, Functional Tests EE, Functional Tests B2B

2024-12-19 13:43 UTC, engcom-Dash commented
Raised internal approval [Jira](https://jira.corp.adobe.com/browse/AC-13543) for the SVC failure. Moving this PR to Pending Approval now. We will proceed ahead on this once will get all the required approvals.
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/8fce46dd-d5cf-43d8-9172-6fe803489528" />

2025-03-07 15:39 UTC, bhennesAdv commented
Hello,

Up for updated comment. What is needed for this to move forward ?

Regards,
Baptiste

2025-04-28 10:49 UTC, engcom-Dash commented
Hi @bhennesAdv, Approvals on [JIRA](https://jira.corp.adobe.com/browse/AC-13543) are needed because of SVC Failures. We will let you know once we will get all required approvals on the JIRA. Thank you for your patience.

2025-07-15 06:46 UTC, engcom-Dash commented
@magento run all tests

2025-08-12 11:30 UTC, engcom-Dash commented
Hello @lbajsarowicz,

The SVC check in failing in build because of the return type changed for the getMessage() from array to string[]. 
<img width="3412" height="472" alt="image" src="https://github.com/user-attachments/assets/f1e655b6-f2a5-4ab7-9c71-c1d672fa2bda" />

To prevent this failure can we revert it to array as $_messages are declared as type array so that we can proceed with this PR.

2025-08-12 12:16 UTC, engcom-Dash commented
@magento run all tests

2025-08-18 08:43 UTC, engcom-Dash commented
@magento run all tests

2025-08-18 11:22 UTC, engcom-Dash commented
Moving this PR to Extended Testing as the SVC is no longer failing because the change has been reverted which was causing a Major SVC failure. Hence an Approval JIRA is not needed now.

2025-08-18 11:39 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2025-08-19 05:15 UTC, engcom-Dash commented
One consistent failure in **Functional B2B** is a known issue and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39331/b755a1656268b7e3b596d7d03ee57d0d/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2202" height="636" alt="image" src="https://github.com/user-attachments/assets/62cef1ca-baff-400b-bc9a-d36077c6c7f9" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39331/d8f4a6d297b1c187fb4fe7032d102f04/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2198" height="638" alt="image" src="https://github.com/user-attachments/assets/bd1f9662-4260-4484-acce-e301b783815a" />

Known Issue: AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

One consistent failure in **Functional CE** is a known issue and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39331/bc701f274b9d6981b1733d1fe8ed3328/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2200" height="410" alt="image" src="https://github.com/user-attachments/assets/7ed343d8-f68f-4d7a-a433-9587fd34063d" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39331/ddcdc8f9d726a69750ddb57c7cbd9126/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2206" height="658" alt="image" src="https://github.com/user-attachments/assets/dcb3b7f0-6ac0-4f0c-8f9d-044530d17bff" />

Known Issue: StorefrontDeleteSimpleAndVirtualProductFromMiniShoppingCartTest [ACQE-8560](https://jira.corp.adobe.com/browse/ACQE-8560)

One consistent failure in **Functional EE** is a known issue and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39331/eabf61c82de72d719fe51cc8bf477cd2/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2478" height="532" alt="image" src="https://github.com/user-attachments/assets/07b0292c-559e-4201-9dd5-043e1c1804bf" />

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39331/1ef014d49f9fa89fa9a149ffda4f693b/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

<img width="2206" height="638" alt="image" src="https://github.com/user-attachments/assets/9f5f78e0-2efc-4fb9-869d-c5d677908372" />

Known Issue: AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

Hence moving this PR in Merge In Progress.

2025-09-23 10:10 UTC, engcom-Dash commented
@magento run all tests

2025-10-13 06:00 UTC, merged