magento/magento2#38891: Hidden dropdown in grids with select action (…
magento/magento2 pull request #39371
Opened 2024-11-15 13:49 UTC by lucafuser

### Description (*)

 Small css fix to display correctly the action dropdown inside admin grids.

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38891

### Manual testing scenarios (*)

Scenario 1:
1. Go to Content > Elements > Pages
2. Add new page
3. In Grid overview click on Select in the "Actions" column

Scenario 2:
1. Go to Customer > All Customer > Edit customer
2. In Address management, add new address
3. In address grid overview click on Select in the "Actions" column

### Questions or comments

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-11-15 13:49 UTC, lucafuser commented
@magento run all tests

2024-12-17 22:15 UTC, lucafuser commented
@magento run all tests

2025-02-18 04:13 UTC, engcom-Hotel commented
@magento run all tests

2025-02-18 09:15 UTC, engcom-Hotel requested changes
Hello @lucafuser,

Thanks for the contribution!

Please fix the failed static test.

Thanks

2025-02-18 13:08 UTC, lucafuser commented
@magento run all tests

2025-02-18 14:02 UTC, lucafuser commented
@magento run all tests

2025-02-18 17:30 UTC, lucafuser commented
> Hello @lucafuser,
> 
> Thanks for the contribution!
> 
> Please fix the failed static test.
> 
> Thanks

Done

2025-02-19 06:20 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Integration Tests

2025-02-19 12:26 UTC, engcom-Hotel approved these changes

2025-02-20 07:59 UTC, engcom-Bravo commented
Hi @lucafuser,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

 Scenario 1:


- Go to Content > Elements > Pages
- Add new page
- In Grid overview click on Select in the "Actions" column

Scenario 2:

- Go to Customer > All Customer > Edit customer
- In Address management, add new address
- In address grid overview click on Select in the "Actions" column



**Before:** :heavy_multiplication_x: 

<img width="1327" alt="Screenshot 2025-02-20 at 12 56 43 pm" src="https://github.com/user-attachments/assets/45765e8e-740e-42ce-aeb6-2fa81319f7f5" />
<img width="1327" alt="Screenshot 2025-02-20 at 12 58 21 pm" src="https://github.com/user-attachments/assets/fe5660fb-dd2c-4ded-8935-405e5971ddd2" />




**After:** :heavy_check_mark: 

<img width="1327" alt="Screenshot 2025-02-20 at 1 02 39 pm" src="https://github.com/user-attachments/assets/063e1e4c-96ca-4c8d-b63d-84dc54526776" />


<img width="1327" alt="Screenshot 2025-02-20 at 1 03 08 pm" src="https://github.com/user-attachments/assets/6f3662f8-e5dd-4209-beb8-421a43da6a04" />




Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-02-20 09:58 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2025-02-26 13:40 UTC, engcom-Charlie commented
Two of of the **Functional B2B** test failure are inconsistent in the last two builds, it seem to be flaky and the other one is a known issue. They neither part of PR nor failing because of the PR changes.  Hence moving this PR to Merge in Progress

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39371/690e50e35b2727adaa2d5cbe0cd273a6/Functional/allure-report-b2b/index.html#categories

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/dc133338-d9f3-4284-b3c5-647356985a19" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39371/1845940579e675fdb754ce42561dc09a/Functional/allure-report-b2b/index.html#categories/ff086893d1b2f6d93d2b926c3d303ab7/a236388780dfe915/

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/14cae23d-74ef-4adc-9e55-46a0dd164392" />


**Known Issue:**
AdminQuoteLevelPercentDiscountNotRemovedWhenDiscountCanBeDistributedTest: [ACQE-7594](https://jira.corp.adobe.com/browse/ACQE-7594)

2025-03-05 08:48 UTC, merged