Fixed Magento reorder order id issue
magento/magento2 pull request #39399
Opened 2024-11-25 07:07 UTC by magentoabu

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39089

### Manual testing scenarios (*)

1. Open any order, click reorder
2. Submit the order.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-11-26 05:48 UTC, magentoabu commented
@magento run all tests

2024-11-27 05:24 UTC, magentoabu commented
@magento run Static Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2025-01-16 11:56 UTC, engcom-Hotel commented
@magento run all tests

2025-01-17 11:39 UTC, engcom-Hotel requested changes
Hello @magentoabu,

Thanks for the contribution!

Please sign the CLA as it is required to process the PR further. Till the time we are moving this PR `On Hold`.

2025-01-17 11:50 UTC, magentoabu commented
> Hello @magentoabu,
> 
> Thanks for the contribution!
> 
> Please sign the CLA as it is required to process the PR further. Till the time we are moving this PR `On Hold`.
> 
> Thanks

CLA signed, please proceed further

2025-01-18 09:47 UTC, magentoabu commented
@magento run Static Tests

2025-01-21 03:46 UTC, engcom-Hotel commented
Hello @magentoabu,

It is still showing as unsigned. Please have a look at the cross mark in front of the `Adobe CLA Signed?` test.

Thanks

2025-01-30 11:21 UTC, magentoabu commented
@magento run all tests

2025-01-31 08:03 UTC, engcom-Hotel requested changes
Hello @magentoabu,

Thanks for the contribution!

Please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

And also look into the below review comment.

Thanks

2025-01-31 08:03 UTC, engcom-Hotel commented on app/code/Magento/Sales/Model/AdminOrder/Create.php
> + * Copyright 2015 Adobe
It should be `2011` only as the file has been created in 2011 only

2025-01-31 13:17 UTC, magentoabu commented on app/code/Magento/Sales/Model/AdminOrder/Create.php
> + * Copyright 2015 Adobe
fixed

2025-02-04 07:26 UTC, engcom-Hotel commented
@magento run all tests

2025-02-04 10:20 UTC, engcom-Hotel commented
Hello @magentoabu, 

As mentioned [here](https://github.com/magento/magento2/pull/39399#pullrequestreview-2585913258), please also add automated test.

Thanks

2025-02-21 11:35 UTC, engcom-Hotel commented
Hello @magentoabu,

Just a friendly reminder to add an automated test for this PR.

Thanks

2025-02-21 12:56 UTC, magentoabu commented
@engcom-Hotel I'm working on it

2025-03-10 10:33 UTC, engcom-Charlie commented
Hi @magentoabu,

Thank you for your contribution!

Can I take care of the automation test coverage here?

2025-03-11 13:28 UTC, magentoabu commented
@magento run Unit Tests, WebAPI Tests, Integration Tests, Functional Tests B2B, Functional Tests EE, Functional Tests CE

2025-03-17 06:59 UTC, engcom-Charlie commented
It seems that review changes has been taken care hence moving it for Pending Review.

2025-03-18 08:24 UTC, engcom-Hotel commented
@magento run all tests

2025-03-18 11:58 UTC, engcom-Hotel requested changes
Hello @magentoabu,

Thanks for making the changes. I guess the integration test is failing due to the PR Changes. Please look into this.

Thanks

2025-03-21 14:01 UTC, engcom-Charlie commented
@magento run all tests

2025-03-24 13:28 UTC, engcom-Charlie commented
@magento run all tests

2025-03-24 15:02 UTC, Den4ik approved these changes
✅ Approved
Changes looks good for me.
All logical changes made in https://github.com/magento/magento2/pull/37298/ reverted.

Failed Functional Tests are not related to changes in R

2025-03-25 06:55 UTC, engcom-Charlie commented
Fixed the integration test failure.

2025-03-25 13:45 UTC, engcom-Hotel approved these changes

2025-03-26 08:27 UTC, engcom-Bravo commented
@magento run all tests

2025-03-26 10:05 UTC, engcom-Bravo commented
Hi @magentoabu,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Open any order, click reorder
- Submit the order.



**Before:** :heavy_multiplication_x: 

<img width="1436" alt="Screenshot 2025-03-26 at 1 50 51 pm" src="https://github.com/user-attachments/assets/66033be5-09bb-4892-b1ea-b2fd44ab372d" />







**After:** :heavy_check_mark: 

**order number with unique 8 digits.**

<img width="1436" alt="Screenshot 2025-03-26 at 2 01 40 pm" src="https://github.com/user-attachments/assets/9b40b5d1-883f-4a89-8cb9-80aec552feee" />






Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-03-28 06:56 UTC, engcom-Charlie commented
@magento run all tests

2025-03-28 09:55 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

2025-03-28 12:57 UTC, engcom-Charlie commented
The consistent test failure of Functional B2B is a known issue. Hence moving this PR to Merge in Progress.

**Build 1:**  
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39399/889b809ab8d69e88f7938b9020e26bdb/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/ff428befbea0a9b0/
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/c20b404c-f33c-4da6-818e-2c854e9ae9e5" />

**Build 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39399/5735671a4ab8fbf0b570fd1e2059b9a8/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/fa4e07a5eed0251d/

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/9a2e452e-bc08-4284-863b-96332ee80a56" />


**Known Issue:**
[ACQE-7751](https://jira.corp.adobe.com/browse/ACQE-7751) : CatalogPriceRuleAndCustomerGroupMembershipArePersistedUnderLongTermCookieTest

2025-07-04 11:31 UTC, merged

2026-03-05 13:13 UTC, Den4ik commented
Hi @engcom-Charlie,
What is planned release version that will contain this fix?

2026-03-06 08:54 UTC, engcom-Charlie commented
> Hi @engcom-Charlie, What is planned release version that will contain this fix?

Hi @Den4ik, this PR got merged and delivered in https://github.com/magento/magento2/commit/0db88bc4c5e6fffdd8174d45be5f61ac0ebce0cc in 2.4.9-alpha2 version