Page heading null issue fixed
magento/magento2 pull request #39398
Opened 2024-11-25 06:54 UTC by magentoabu

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39092

### Manual testing scenarios (*)

1. Create a new cms page without title
2. Template do not crash if there's no page title.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-11-26 05:54 UTC, magentoabu commented
@magento run all tests

2024-11-27 05:27 UTC, magentoabu commented
@magento run Static Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

2025-01-28 11:08 UTC, magentoabu commented
@magento run all tests

2025-01-30 12:32 UTC, magentoabu commented
@magento run all tests

2025-02-05 06:47 UTC, engcom-Hotel commented
@magento run all tests

2025-02-05 10:26 UTC, engcom-Hotel requested changes
Hello @magentoabu,

Thanks for the contribution!

The changes seem good to us but please fix the failed automated tests. Also please cover the changes with some automated tests.

Thanks

2025-02-21 11:36 UTC, engcom-Hotel commented
Hello @magentoabu,

Have you got a chance to look into the review comments on this PR?

Thanks

2025-02-21 12:56 UTC, magentoabu commented
@engcom-Hotel I'm working on it

2025-03-02 21:07 UTC, Den4ik requested changes
Hi @magentoabu 
Did you have a chance to fix static tests?

2025-03-05 14:35 UTC, magentoabu commented
@magento run all tests

2025-03-06 10:40 UTC, magentoabu commented
@Den4ik static test fixed

2025-03-06 11:06 UTC, magentoabu commented
@engcom-Hotel This issue is only occurs if the cms page is created without heading, so its not possible to create cms page without heading in admin, the only way is create cms block using script or patch, i don't think automation tests is needed for this PR

2025-03-07 10:33 UTC, engcom-Hotel approved these changes
Hello @magentoabu,

After going through the issue again and the fix, I guess you are correct. We can move further with this PR.

Thanks

2025-03-07 11:13 UTC, Den4ik approved these changes
@magentoabu Looks good for me

2025-03-10 10:24 UTC, engcom-Dash commented
@magento run all tests

2025-03-10 12:43 UTC, engcom-Dash commented
@magentoabu Thank you for collaboration & contribution!

:heavy_check_mark: QA Passed

Preconditions:
Install Fresh Magento 2.4-develop

Steps to reproduce:
Create a CMS page without title using script/patch

Before:
As per PR description, in Php 8.2 passing null to **trim()** throws **Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string**

![image](https://github.com/user-attachments/assets/6d35c581-29c5-44b5-b128-004a8355ecf7)

![image](https://github.com/user-attachments/assets/4bb16461-4a91-4b64-b89c-4fbc9f2d720d)

After: 
![image](https://github.com/user-attachments/assets/645bedae-4726-41c0-b21d-c50fd3dbcb3e)

![image](https://github.com/user-attachments/assets/94359477-80dc-4e7d-915c-8da848f18093)

Functional Tests EE are failing hence moving this PR to Extended Testing.

Thank you.

2025-03-10 12:48 UTC, engcom-Dash commented
@magento run Functional Tests EE

2025-03-10 15:46 UTC, engcom-Dash commented
As all the checks have been successfully completed and are in green state, moving this PR to Merge in Progress.

Thank You.

2025-04-02 23:52 UTC, merged

2025-04-23 12:21 UTC, phaniseela commented
thank you Abbas!