#29654 Object Cache for Category Links
magento/magento2 pull request #39420
Opened 2024-12-02 10:46 UTC by lbajsarowicz

### Description (*)

Just continuation of https://github.com/magento/magento2/pull/29565/

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-12-02 10:46 UTC, lbajsarowicz commented
@magento run all tests

2025-01-17 11:43 UTC, engcom-Hotel commented
@magento run all tests

2025-01-17 13:49 UTC, engcom-Hotel requested changes
Hello @lbajsarowicz,

Thanks for the contribution!

Please fix the failed static tests, other failed tests seem flaky to me. And also please look into the below review comment.

Thanks

2025-01-17 13:49 UTC, engcom-Hotel commented on app/code/Magento/Catalog/Model/ResourceModel/Product/CategoryLink.php
> +     *
Please complete the comment signature 
```suggestion
     *
     ** @param string|null $cacheKey
```

2025-02-05 10:19 UTC, engcom-Charlie commented
@magento run all tests

2025-02-05 11:25 UTC, engcom-Charlie commented
@magento run all tests

2025-02-05 13:23 UTC, engcom-Charlie commented
@magento run all tests

2025-02-06 10:54 UTC, engcom-Charlie commented
@magento run Integration Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

2025-02-06 13:50 UTC, engcom-Charlie commented
@magento run all tests

2025-02-07 08:59 UTC, engcom-Charlie commented
@magento run all tests

2025-02-10 06:54 UTC, engcom-Charlie commented
@magento run all tests

2025-02-10 10:26 UTC, engcom-Charlie commented
Hi @lbajsarowicz,

Can you please have a look into build failures. The tests are failing because of the new change made in codebase in this PR.

Integration: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39420/bc6fa6523b8b56cee580104706917ec3/Integration/console-error-logs.html

2025-03-10 10:21 UTC, engcom-Charlie commented
@magento run all tests

2025-03-10 14:27 UTC, engcom-Charlie commented
Hi @lbajsarowicz,

In order to move further on this PR, we need the green build. As mentioned [here](https://github.com/magento/magento2/pull/39420#issuecomment-2647562697) kindly fix the integration test failures. Till then we are closing this PR. Please feel free to reopen once you are done with the required implementation or let us know to reopen it.

2025-03-10 14:27 UTC, closed without merging

2026-07-09 22:09 UTC, lbajsarowicz commented
Superseded by #40972. That revision fixes the root cause of the integration failures that led to this closure: the memoization cache went stale when products were assigned via **category save** (`Category::_saveCategoryProducts()`), which bypassed the invalidation inside `CategoryLink`. The new PR invalidates on that path too, implements `ResetAfterRequestInterface`, and the previously failing test classes pass locally (30 tests, 0 failures).