Performance - Optimize getSpecificOptions triggered by all getAttributeText calls
magento/magento2 pull request #39476
Opened 2024-12-13 10:32 UTC by anthony-blackbird

### Description (*)
When performing a call to `$product->getAttributeText('my_attribute')` to output the text value of the attribute, it always trigger a call to database. I introduce a memoization to save the previously calculated result and avoid to call database each time for the same combination $storeId / $attributeId / $optionId

### Related Pull Requests

### Fixed Issues (if relevant)
1. Fixes magento/magento2#36174

### Manual testing scenarios (*)
1. Go to a page where getAttributeText is used depending of your templates files (category page, product page), for example, use `getAttributeText('color')`
2. If you have two or more products having the exact same color, only one call will be made to database
3. You can notice it by using Blackfire or a log in the newly introduced method `loadSpecificOptions`

### Questions or comments

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-12-13 10:40 UTC, anthony-blackbird commented
@magento run all tests

2024-12-13 11:14 UTC, anthony-blackbird commented
@magento run all tests

2024-12-14 15:45 UTC, anthony-blackbird commented
@magento run all tests

2024-12-15 09:48 UTC, anthony-blackbird commented
@magento run Functional Tests CE

2024-12-15 09:49 UTC, anthony-blackbird commented
@magento run Functional Tests B2B

2024-12-15 17:45 UTC, anthony-blackbird commented
@magento run Functional Tests CE

2024-12-16 10:12 UTC, anthony-blackbird commented
@magento run Functional Tests B2B

2024-12-16 12:47 UTC, anthony-blackbird commented
@magento run Functional Tests B2B,Semantic Version Checker,Static Tests

2024-12-16 14:32 UTC, anthony-blackbird commented
While the PR is processed, I suggest this package I developed, compatible with Magento 2.4.x.

It also introduces a cache layer for these specific options loaded. I might add it to my PR if Magento Team is interested too. More details on the readme : https://github.com/blackbird-agency/magento-eav-optimize

2024-12-16 16:02 UTC, anthony-blackbird commented
@magento run Static Tests

2024-12-16 16:57 UTC, anthony-blackbird commented
@magento run all tests

2024-12-17 14:54 UTC, anthony-blackbird commented
@magento run all tests

2024-12-18 10:17 UTC, anthony-blackbird commented
@magento run all tests

2024-12-18 10:17 UTC, anthony-blackbird commented
@magento run all tests

2024-12-19 19:31 UTC, anthony-blackbird commented
@magento run all tests

2024-12-29 09:06 UTC, anthony-blackbird commented
@magento run all tests

2025-01-16 11:23 UTC, engcom-Hotel commented
@magento run all tests

2025-01-16 14:18 UTC, engcom-Hotel requested changes
Hello @anthony-blackbird,

Thanks for the contribution!

Please look into the failed tests specifically static, Integration and WebAPI tests.

Thanks

2025-01-20 08:43 UTC, anthony-blackbird commented
@magento run Static Tests

2025-02-03 14:51 UTC, engcom-Charlie commented
@magento run all tests

2025-02-03 14:58 UTC, engcom-Charlie commented
@magento run all tests

2025-02-04 09:35 UTC, engcom-Charlie commented
Hi @anthony-blackbird,

Can you please look into [Integration](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39476/f122d69bfdb5d89f5a44f16dceef24b9/Integration/console-error-logs.html), [WebAPI](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39476/a669cf59f3597f206f3f77170d2dd83e/WebApi/console-error-logs.html) tests failures. 

Thank you!

2025-02-04 09:36 UTC, engcom-Charlie commented
@magento run Functional Tests CE

2025-02-20 06:50 UTC, engcom-Charlie commented
Hi @anthony-blackbird,

In order to proceed further the build should be green and the [mentioned](https://github.com/magento/magento2/pull/39476#issuecomment-2633354539) test failures should get resolved. Currently we are closing this PR, please feel free to reopen it once you done with the changes or let us know to reopen it.

Thank you!

2025-02-20 06:50 UTC, closed without merging