Grouped product frontend quantity validation added and code refactor
magento/magento2 pull request #39480
Opened 2024-12-15 05:26 UTC by Mohamed-Asar

### Description (*)
Grouped Product Frontend Quantity validation added

### Related Pull Requests

### Fixed Issues (if relevant)
1. #39479 
2. #39142

### Manual testing scenarios (*)

1.Create a Grouped Product and associate it with child products.
2. Set the following quantity properties for one of the child products:
    - Minimum Qty Allowed in Shopping Cart: 2
    - Maximum Qty Allowed in Shopping Cart: 10
    - Qty Increments: 2
 3.Open the Product Detail Page (PDP) of the Grouped Product and test invalid quantities for the selected child product (e.g., 1, 3, or 11) to confirm that invalid inputs are restricted.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-12-18 07:08 UTC, Mohamed-Asar commented
@magento run all tests.

2024-12-18 07:09 UTC, Mohamed-Asar commented
@magento run all tests

2024-12-28 12:59 UTC, Mohamed-Asar commented
@magento run all tests

2024-12-30 05:59 UTC, Mohamed-Asar commented
@magento run all tests

2024-12-30 13:04 UTC, Mohamed-Asar commented
@magento run all tests

2024-12-31 09:33 UTC, Mohamed-Asar commented
@magento run all tests

2025-01-23 06:53 UTC, engcom-Hotel commented
@magento run all tests

2025-01-23 10:50 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Static Tests, Unit Tests

2025-01-23 10:51 UTC, engcom-Hotel requested changes
Hello @Mohamed-Asar,

Thanks for the contribution!

Please find below the review comments.

Thanks

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +use Magento\CatalogInventory\Api\StockRegistryInterface;
interface StockRegistryInterface has been deprecated. Please use alternate.

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +        StockRegistryInterface $stockRegistry
Use `readonly` instead. Please refer to [this](https://github.com/magento/magento2/blob/3428ebc3802a26fae9be542163579cefaa7967fa/app/code/Magento/Tax/Model/Plugin/AddTaxesExtensionAttribute.php#L46).

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +    public function getData($productId, $websiteId): array
The parameter's type declaration is missing. Please add.

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +        $params['minAllowed'] = (float)$stockItem->getMinSaleQty();
`getMinSaleQty` is returning the `float` value. No need to typecast here.

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +            $params['maxAllowed'] = (float)$stockItem->getMaxSaleQty();
Same here

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/GroupedProduct/ViewModel/ValidateQuantity.php
> +        Json $serializer,
Use `readonly` constructor parameter.

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/GroupedProduct/ViewModel/ValidateQuantity.php
> +    public function getQuantityValidators($productId, $websiteId): string
Please add parameter's type declaration.

2025-01-23 10:51 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Block/Plugin/ProductView.php
> +        QuantityValidator $productQuantityValidator
Use ObjectManager to initialize as this change is BiC.

2025-01-23 16:34 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +use Magento\CatalogInventory\Api\StockRegistryInterface;
@engcom-Hotel The alternative for that interface is the MSI module. However, some users might have the MSI module disabled, can i use that ?

2025-01-23 16:37 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +        StockRegistryInterface $stockRegistry
done.

2025-01-23 16:38 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +    public function getData($productId, $websiteId): array
done

2025-01-23 16:38 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +        $params['minAllowed'] = (float)$stockItem->getMinSaleQty();
removed the typecast

2025-01-23 16:38 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +            $params['maxAllowed'] = (float)$stockItem->getMaxSaleQty();
removed the typecast

2025-01-23 16:38 UTC, Mohamed-Asar commented on app/code/Magento/GroupedProduct/ViewModel/ValidateQuantity.php
> +        Json $serializer,
done

2025-01-23 16:39 UTC, Mohamed-Asar commented on app/code/Magento/GroupedProduct/ViewModel/ValidateQuantity.php
> +    public function getQuantityValidators($productId, $websiteId): string
done

2025-01-23 16:39 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Block/Plugin/ProductView.php
> +        QuantityValidator $productQuantityValidator
done

2025-01-24 06:20 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +use Magento\CatalogInventory\Api\StockRegistryInterface;
Yes @Mohamed-Asar you can use that. BTW its now recommended to disable the MSI module.

2025-01-24 06:22 UTC, engcom-Hotel commented
Moving back to `Changes requested` as 1 [review comment](https://github.com/magento/magento2/pull/39480#discussion_r1926716718) still needs to be worked on.

2025-01-24 08:40 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +use Magento\CatalogInventory\Api\StockRegistryInterface;
@engcom-Hotel MSI module is not included in this repo. how do i proceed ?

2025-01-27 06:07 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +use Magento\CatalogInventory\Api\StockRegistryInterface;
Please refer to this repo: https://github.com/magento/inventory

2025-01-28 06:39 UTC, engcom-Hotel commented
@magento run all tests

2025-01-30 07:14 UTC, Mohamed-Asar commented
@engcom-Hotel  Not able to install MSI module, facing the below issue 

![image](https://github.com/user-attachments/assets/095c6de7-7658-42a4-8e6e-d6df2e12fa8b)

This issue occurs due to recent changes, which was already discussed [here](https://magentocommeng.slack.com/archives/C7KB93M32/p1736933306053669), i will proceed once the issue resolved

2025-01-31 06:42 UTC, engcom-Hotel commented
Sure @Mohamed-Asar, until we are moving the PR `On Hold`.

Thanks

2025-03-05 07:31 UTC, Mohamed-Asar commented
> @engcom-Hotel Not able to install MSI module, facing the below issue
> 
> ![image](https://private-user-images.githubusercontent.com/56036656/408021324-095c6de7-7658-42a4-8e6e-d6df2e12fa8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExNjAwOTksIm5iZiI6MTc0MTE1OTc5OSwicGF0aCI6Ii81NjAzNjY1Ni80MDgwMjEzMjQtMDk1YzZkZTctNzY1OC00MmE0LThlNmUtZDZkZjJlMTJmYThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA1VDA3Mjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTY1MmMyYjAzMDEwODk5NTliMGRhNWFmZTQ5YTQ4ODA5MDIxY2NkMWEwN2E2ZDQzMDFjZTI4Mjg2NjdhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pBQEk4_yozeFulXYVPw_SSN2n20u96kq60zbNo_s8DI)
> 
> This issue occurs due to recent changes, which was already discussed [here](https://magentocommeng.slack.com/archives/C7KB93M32/p1736933306053669), i will proceed once the issue resolved

@engcom-Hotel This issue was fixed by internal team, i will start working on the changes and let you know

2025-03-07 10:21 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Model/Product/QuantityValidator.php
> +use Magento\CatalogInventory\Api\StockRegistryInterface;
@engcom-Hotel I used MSI and remvoed the deprecated methods, please review

2025-03-07 10:22 UTC, Mohamed-Asar commented
@magento run all tests

2025-03-10 08:37 UTC, Mohamed-Asar commented
@magento run all tests

2025-03-11 06:14 UTC, engcom-Hotel commented
@magento run all tests

2025-03-14 05:58 UTC, engcom-Hotel commented
@magento run all tests

2025-03-26 06:51 UTC, engcom-Hotel commented
@magento run all tests

2025-04-02 13:20 UTC, engcom-Hotel requested changes
Hello @Mohamed-Asar,

Thanks for updating the PR as per the review comment!

It seems some tests are still failing due to the changes. Please look into those.

Thanks

2025-04-03 12:22 UTC, Mohamed-Asar commented
@magento run all tests

2025-04-03 13:46 UTC, Mohamed-Asar commented
> Hello @Mohamed-Asar,
> 
> Thanks for updating the PR as per the review comment!
> 
> It seems some tests are still failing due to the changes. Please look into those.
> 
> Thanks

@engcom-Hotel Do i need to add the depency in composer.json for this modules( [Magento\InventoryConfigurationApi, Magento\InventorySalesApi]) ? and also these modules are not on this repo, so how can i proceed, do i need to mention in root composer.json and the module composer.json ?

2025-04-07 07:51 UTC, engcom-Hotel commented
@magento run Static Tests

2025-04-07 09:37 UTC, engcom-Hotel commented
Hello @Mohamed-Asar,

I guess you need to mention the dependencies in the `composer.json` of `magento/module-catalog-inventory` module here:
https://github.com/Mohamed-Asar/magento2/blob/559d0f8314f93b4aa59562d1a171329242dcffdb/app/code/Magento/CatalogInventory/composer.json#L7-L16

Thanks

2025-04-07 10:29 UTC, Mohamed-Asar commented
@engcom-Hotel i added before, static test failed due to composer dependency issued, please see this [commit](https://github.com/magento/magento2/pull/39480/commits/baeb177a3bdf99a46a8744ee943f6146c291df9b)

![Screenshot from 2025-04-07 15-56-58](https://github.com/user-attachments/assets/5d397f91-db08-4c15-94c3-a22ab5b14cfd)

2025-04-07 14:12 UTC, engcom-Hotel commented
@Mohamed-Asar I suggest you to please go through with this documentation: https://developer.adobe.com/commerce/php/architecture/modules/dependencies/

I think we need to add them back.

Thanks

2025-04-07 16:07 UTC, Mohamed-Asar commented
@magento run all tests

2025-04-08 11:17 UTC, Mohamed-Asar commented
@engcom-Hotel I’ve added the module dependency in the CatalogInventory module's composer.json, but the static tests are still failing. It seems we need to add the dependency in the root composer.json file. Would it be okay if I go ahead and add it there as well? Please let me know your suggestion.

Also, I noticed that the following [MFTF test](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Test/Mftf/Test/AdminAddInStockProductToTheCartTest.xml) is consistently failing. I reviewed the test case and found that it sets min_qty as 4, but tries to add only 1 quantity to the cart—expecting the product to be added successfully.

However, in this PR, I’ve included min_qty validation, which is why the test is failing. Would it be okay if I update the test case accordingly?

Thanks!

2025-04-09 06:40 UTC, engcom-Hotel commented
Hello @Mohamed-Asar,

Regarding the MFTF test failure, yes please update the test. As you resolved the bug related to validation which was not in place previously it might happen some existing tests fails. So generally we need to fix those.

And regarding the composer dependency static test failure we will get back to you soon on this.

Thanks

2025-04-09 07:26 UTC, Mohamed-Asar commented
@magento run all tests

2025-04-09 11:58 UTC, Mohamed-Asar commented
Hi @engcom-Hotel

I fixed the mftf test case for min qty validation

2025-04-14 05:39 UTC, engcom-Hotel commented
Hello @Mohamed-Asar,

Thanks for fixing the MFTF test, for the dependency failures, we are in discussion with the internal team. Hence moving it to `On Hold` bucket for now.

Thanks

2025-04-16 06:22 UTC, engcom-Hotel commented
Hello @Mohamed-Asar,

As per the internal discussion, we should not make the dependencies of the modules which are not part of the repo. So I think we can move to our previous approach ie `Magento\CatalogInventory\Api\StockRegistryInterface`. 

So please do the needful and let us know whenever this PR is ready for review. 

Thanks

2025-04-16 07:25 UTC, Mohamed-Asar commented
@magento run all tests

2025-04-16 11:45 UTC, Mohamed-Asar commented
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests, Static Test

2025-04-16 14:48 UTC, Mohamed-Asar commented
@magento run Static Tests, Functional Tests B2B

2025-04-17 05:05 UTC, Mohamed-Asar commented
> Hello @Mohamed-Asar,
> 
> As per the internal discussion, we should not make the dependencies of the modules which are not part of the repo. So I think we can move to our previous approach ie `Magento\CatalogInventory\Api\StockRegistryInterface`.
> 
> So please do the needful and let us know whenever this PR is ready for review.
> 
> Thanks

@engcom-Hotel I reverted the MSI Changes, please review

2025-04-21 11:47 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Static Tests

2025-04-25 10:09 UTC, engcom-Hotel commented
@magento run all tests

2025-04-28 08:35 UTC, engcom-Hotel commented
@magento run all tests

2025-04-28 15:01 UTC, engcom-Hotel requested changes
Hello @Mohamed-Asar,
Thanks for the contribution!

Please have a look into the below review comment and fix the failed tests.

Thanks

2025-04-28 15:01 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Block/Plugin/ProductView.php
> +        QuantityValidator $productQuantityValidator
not done yet, still cant see ObjectManager usages

2025-04-28 15:01 UTC, engcom-Hotel commented on app/code/Magento/CatalogInventory/Test/Unit/Model/Product/QuantityValidatorTest.php
> +class QuantityValidatorTest extends TestCase
Covering some edge case tests to ensure the code behaves correctly under unusual or extreme conditions. This could include scenarios like:

- `getMinSaleQty`, `getMaxSaleQty`, or `getQtyIncrements` returning null or invalid values.
- Testing with a `productId` or `websiteId` that does not exist in the stock registry.

2025-04-28 15:24 UTC, Mohamed-Asar commented
@engcom-Hotel Failed static test is not related to this PR, can i fix that ? 
![image](https://github.com/user-attachments/assets/cab97f8e-b7a4-4017-85b9-aba4ad08998f)

2025-04-28 15:40 UTC, Mohamed-Asar commented on app/code/Magento/CatalogInventory/Block/Plugin/ProductView.php
> +        QuantityValidator $productQuantityValidator
@engcom-Hotel i tried that, but the static test failed due to the object being initialized as null, so I had to revert the changes.

![image](https://github.com/user-attachments/assets/e42770c4-e34c-43c5-b45b-478d798174b7)

2025-04-30 15:21 UTC, engcom-Hotel commented
Yes please @Mohamed-Asar, let us know of you are facing any difficulty in resolving the same.

2025-05-21 13:22 UTC, engcom-Hotel commented
Hello @Mohamed-Asar,

If you are facing issue in resolving the static test failures, then we can check the possibilities of creating JIRA for the approval.

Please let us know.

Thanks

2025-05-23 10:40 UTC, Mohamed-Asar commented
@magento run all tests

2025-05-23 15:26 UTC, Mohamed-Asar commented
> Hello @Mohamed-Asar, Thanks for the contribution!
> 
> Please have a look into the below review comment and fix the failed tests.
> 
> Thanks

@engcom-Hotel  If i added null i'm getting this error thats why i reverted it 

![image](https://github.com/user-attachments/assets/76e0ac80-5e90-498e-8c75-4ef2fc0568ae)

2025-05-23 15:26 UTC, Mohamed-Asar commented
> Hello @Mohamed-Asar,
> 
> If you are facing issue in resolving the static test failures, then we can check the possibilities of creating JIRA for the approval.
> 
> Please let us know.
> 
> Thanks

@engcom-Hotel  Let me check and provide you an update by Monday

2025-05-23 15:32 UTC, Mohamed-Asar commented
@magento run all tests

2025-05-26 06:53 UTC, Mohamed-Asar commented
> Hello @Mohamed-Asar,
> 
> If you are facing issue in resolving the static test failures, then we can check the possibilities of creating JIRA for the approval.
> 
> Please let us know.
> 
> Thanks

@engcom-Hotel Those failed test case is not related to this pr, its better if we create a separate issue and fix it, please check with internal team for the approval

2025-05-27 05:44 UTC, engcom-Hotel commented
@magento run all tests

2025-05-27 11:23 UTC, engcom-Hotel approved these changes

2025-05-28 06:05 UTC, engcom-Bravo commented
Hi @Mohamed-Asar,

Thanks for your Contribution!!.

Could you please resolve the Conflicts to proceed further.

Thanks.

2025-05-28 08:05 UTC, Mohamed-Asar commented
@engcom-Bravo I fixed the conflicts, please check

2025-05-29 04:16 UTC, engcom-Hotel commented
@magento run all tests

2025-05-29 09:05 UTC, engcom-Hotel approved these changes

2025-05-30 08:34 UTC, engcom-Bravo commented
Hi @Mohamed-Asar,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Create a Grouped Product and associate it with child products.
- Set the following quantity properties for one of the child products:

    - Minimum Qty Allowed in Shopping Cart: 2
    - Maximum Qty Allowed in Shopping Cart: 10
    - Qty Increments: 2

- .Open the Product Detail Page (PDP) of the Grouped Product and test invalid quantities for the selected child product (e.g., 1, 3, or 11) to confirm that invalid inputs are restricted.



**Before:** :heavy_multiplication_x: 

<img width="1382" alt="Screenshot 2025-05-30 at 12 13 47 pm" src="https://github.com/user-attachments/assets/a3c0b8cc-8b70-4b64-b984-5e9ce03c0177" />

<img width="1212" alt="Screenshot 2025-05-30 at 12 18 42 pm" src="https://github.com/user-attachments/assets/3b464bd4-2588-4e28-bab5-cddf90cb9701" />




**After:** :heavy_check_mark: 


<img width="1380" alt="Screenshot 2025-05-30 at 1 50 03 pm" src="https://github.com/user-attachments/assets/f22b09fd-bac3-4de5-bf6b-da8b211c1fc0" />



<img width="1399" alt="Screenshot 2025-05-30 at 1 52 18 pm" src="https://github.com/user-attachments/assets/c1eab1c3-fa8d-404a-a9e9-3697f9bafeb9" />






Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-05-30 10:27 UTC, engcom-Dash commented
@magento run all tests

2025-06-02 06:28 UTC, engcom-Dash commented
@magento run all tests

2025-06-02 09:29 UTC, engcom-Dash commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests, Unit Tests

2025-06-02 12:02 UTC, engcom-Dash commented
The consistent test failures for Functional B2B are known Issues and JIRA is raised for them.
Build 1:  https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/9ca147ac593cebfa8bb15cddfc34b291/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/1396a319-bd8d-4ef7-8d65-bfd2f66a0bb4)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/24ce85251ad7e859543698323eef8b45/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/564b17ed-0273-430a-be9d-7958bc752630)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)
StoreFrontSimpleProductWithSpecialAndTierDiscountPriceTest : [ACQE-7971](https://jira.corp.adobe.com/browse/ACQE-7971)
OrderWithMultipleConfigurableProductsAdditionalStockTest : [ACQE-8060](https://jira.corp.adobe.com/browse/ACQE-8060)

The consistent test failures for Functional CE is known Issues and JIRA is raised for the same.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/ea2a8bbe902a91cd403d34cc0f1413f7/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/80d6e5d1-9bf3-437c-bb5f-76cd57f482b4)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/c6141d1ffdcb2b88bd9059b81502ebd3/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/d265228b-f591-4992-97cb-d5bdb66f7468)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)


The consistent test failure for Functional EE is known Issues and JIRA is raised for the same. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/213c9121f0385ecc0ad9b0794b6719f8/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/8aad553c-77d3-4ce2-ae6f-6aa169888d39)

Build 2:https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/60b1d7f04550acbc39bb8209e303e64c/Functional/allure-report-ee/index.html#categories/34dd2aa3ce3269b0c73667a1e007a61f/7ad1551983068770/

![image](https://github.com/user-attachments/assets/77e3da25-487e-4391-9a3b-0f33ff5e77b0)

Known Issues:
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

2025-06-03 07:16 UTC, engcom-Dash commented
**Static Test Failure**
The consistent static test failures are not because of this code changes done in this PR. It is a known issue and has JIRA Opened for the same. 

Other static failures are flaky and not related to the code changes done in this PR.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/43110624267407c65a6507ecbcbc124b/Statics/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/2419f95f-87dd-4303-b814-705c706c7bf2)

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39480/d51b13f03f999556b38d522aca9eae1f/Statics/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

![image](https://github.com/user-attachments/assets/c9872ae8-3f93-4cde-baff-f31796c13b65)


Known Issue:
"use strict" is unnecessary inside of modules: https://jira.corp.adobe.com/browse/AC-14517.


Hence moving this PR in Merge In Progress.

2025-07-02 13:10 UTC, merged