Wishlist validation added for gropued product
magento/magento2 pull request #39497
Opened 2024-12-20 05:06 UTC by Mohamed-Asar

### Description (*)
Validation added for grouped while add child products to wishlist

### Fixed Issues (if relevant)

1. Fixes #39496 

### Manual testing scenarios (*)

1.Open grouped product PDP,  Fill invalid inputs
2. Click add to wishlist

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2025-04-25 10:07 UTC, engcom-Hotel commented
@magento run all tests

2025-04-25 13:10 UTC, engcom-Hotel commented
@magento run Unit Tests, Static Tests

2025-04-28 05:42 UTC, engcom-Hotel requested changes
Hello @Mohamed-Asar,

Thanks for the contribution!

The code changes seems good the us, but please fix the failed static tests and validate that the new logic correctly identifies valid and invalid quantities.

Suggesting test cases as below:

- Single input.qty element with valid data.
- Single input.qty element with invalid data.
- Multiple input.qty elements with a mix of valid and invalid data.

2025-05-21 13:33 UTC, engcom-Hotel commented
Hello @Mohamed-Asar,

Have you got a chance to look into the review comments?

Thanks

2025-05-23 12:11 UTC, Mohamed-Asar commented
@engcom-Hotel  Better we can merge this pr after this [PR](https://github.com/magento/magento2/pull/39480)

Let me check and fix the failed tests

2025-06-10 15:36 UTC, engcom-Hotel commented
Hello @Mohamed-Asar,

Gentle reminder for this PR!

Thanks

2025-06-10 15:48 UTC, Mohamed-Asar commented
@engcom-Hotel i have started working on it. will let you know once done

2025-06-10 15:58 UTC, Mohamed-Asar commented
@magento run all tests

2025-06-11 06:47 UTC, Mohamed-Asar commented
@engcom-Hotel Fixed the static tests failures, please review

2025-06-23 07:32 UTC, engcom-Hotel commented
@magento run all tests

2025-06-23 09:57 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests, Unit Tests

2025-06-23 09:58 UTC, engcom-Hotel approved these changes
Hello @Mohamed-Asar,

Thanks for making the changes!

The other failures seems flaky to me, hence re-ran the tests. Approving this PR for further processing.

Thanks

2025-06-24 06:25 UTC, engcom-Bravo commented
@magento run all tests

2025-06-24 12:02 UTC, engcom-Bravo commented
Hi @Mohamed-Asar,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

1. Create a Grouped Product and associate it with child products.
2. Set the following quantity properties for one of the child products:

-    Minimum Qty Allowed in Shopping Cart: 2
-    Maximum Qty Allowed in Shopping Cart: 10
-    Qty Increments: 2

3. Open grouped product PDP, Don't fill any Qty or fill any invalid inputs like(-1, 3, 11)
4. Click add to wishlist




**Before:** :heavy_multiplication_x: 


<img width="1373" alt="Screenshot 2025-06-24 at 3 17 28 pm" src="https://github.com/user-attachments/assets/80b7cffe-da01-4b8b-b1bb-fe52a3b4c3d0" />





<img width="1373" alt="Screenshot 2025-06-24 at 3 18 19 pm" src="https://github.com/user-attachments/assets/3190480d-e8d8-4287-b5e6-0ad3dbd67281" />




**After:** :heavy_check_mark: 



<img width="1373" alt="Screenshot 2025-06-24 at 3 52 51 pm" src="https://github.com/user-attachments/assets/a501356b-4928-4fec-801c-5e37659ac7fe" />






<img width="1373" alt="Screenshot 2025-06-24 at 3 53 03 pm" src="https://github.com/user-attachments/assets/cf051bd1-304b-4fb2-b4f9-d8496e87fb5b" />





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-06-25 11:12 UTC, engcom-Charlie commented
@magento run all tests

2025-07-01 07:34 UTC, engcom-Charlie commented
@magento run all tests

2025-07-01 10:17 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Static Tests, Unit Tests

2025-07-02 10:32 UTC, engcom-Charlie commented
@magento run all tests

2025-07-03 06:30 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests EE, Static Tests, Unit Tests

2025-07-03 06:45 UTC, engcom-Charlie commented
@magento run all tests

2025-07-03 10:42 UTC, engcom-Charlie commented
@magento run all tests

2025-07-03 13:44 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Unit Tests

2025-07-07 06:53 UTC, engcom-Charlie commented
@magento run all tests

2025-07-07 11:46 UTC, engcom-Charlie commented
@magento run all tests

2025-07-08 04:42 UTC, engcom-Charlie commented
@magento run Functional Tests B2B

2025-07-09 05:12 UTC, engcom-Charlie commented
@magento run all tests

2025-07-10 09:46 UTC, engcom-Charlie commented
@magento run all tests

2025-07-14 11:48 UTC, engcom-Charlie commented
@magento run all tests

2025-07-25 12:36 UTC, engcom-Charlie commented
Hi @Mohamed-Asar,

While looking into build failure, we have found that, unit test is failing because of the PR changes with the below error. Can you please have a look into this.

<img width="708" height="230" alt="image" src="https://github.com/user-attachments/assets/2ea80f9e-19cb-456f-9abc-28556d58df6e" />

Thank you!

2025-07-28 06:20 UTC, Mohamed-Asar commented
@engcom-Charlie could you please let me know, how can i run the above the test and see the error

2025-07-28 06:42 UTC, engcom-Charlie commented
Hi @Mohamed-Asar,

In order to run javascript unit test (here, add-to-wishlist.test.js), you can follow [this](https://developer.adobe.com/commerce/testing/guide/js/) document.

2025-08-05 06:58 UTC, engcom-Charlie commented
Hi @Mohamed-Asar, have you had a chance to look into the failures mentioned in [here](https://github.com/magento/magento2/pull/39497#issuecomment-3117627437).

2025-08-07 10:32 UTC, Mohamed-Asar commented
@engcom-Charlie Not yet, i'll let you know once i fixed

2025-08-11 04:52 UTC, engcom-Charlie commented
> @engcom-Charlie Not yet, i'll let you know once i fixed

Sure @Mohamed-Asar, till then moving this PR to On hold.

2025-09-03 06:05 UTC, engcom-Charlie commented
Hi @Mohamed-Asar, did you get a chance to look into the mentioned failure.

2025-09-09 13:01 UTC, engcom-Charlie commented
@Mohamed-Asar, in order to move this PR further, the build should be stable. As mentioned [above](https://github.com/magento/magento2/pull/39497#issuecomment-3117627437), the unit test is failing because of the PR change. Currently, I am closing this PR, please feel free to reopen once you done with the changes.

2026-07-08 17:07 UTC, Mohamed-Asar commented
@engcom-Charlie / @engcom-Hotel  could you please re-open the PR ?

2026-07-09 12:48 UTC, engcom-Charlie commented
Sure @Mohamed-Asar. Please have a look into the failures in the PR as mentioned [above](https://github.com/magento/magento2/pull/39497#issuecomment-3270640638)

2026-07-09 12:57 UTC, Mohamed-Asar commented
@engcom-Charlie Thanks, I will check and fix it.

2026-07-09 14:42 UTC, Mohamed-Asar commented
@magento run all tests

2026-07-10 07:48 UTC, engcom-Charlie commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

2026-07-10 10:56 UTC, engcom-Charlie commented
Thank you @Mohamed-Asar for fixing the unit test failures. 

After fixing, checked the PR issue and its working fine.
**Before:** :heavy_multiplication_x: 
<img width="1836" height="1486" alt="image" src="https://github.com/user-attachments/assets/2d6d57e8-deeb-4a48-8523-9fd3640f6e1b" />


**After:** :heavy_check_mark: 
<img width="2192" height="1246" alt="image" src="https://github.com/user-attachments/assets/4fc4ae7d-1bd3-40c5-8c2b-2a9e3040d30a" />

The functional test failures are the known issues. Hence moving this PR to Merge in Progress.

**Functional B2B: Run 1**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39497/0e2567d2a936e912fd3b0e2000858cba/Functional/allure-report-b2b/index.html#categories

<img width="2506" height="1364" alt="image" src="https://github.com/user-attachments/assets/458e5cfe-b926-4684-b1eb-819e590b1940" />


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39497/4411a3cc8a4cfad38892fe39a1d47c5c/Functional/allure-report-b2b/index.html#categories

<img width="2386" height="1370" alt="image" src="https://github.com/user-attachments/assets/bb91d0c9-5230-4551-b06f-a84aac1f556c" />

**Functional CE: Run 1**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39497/688d9960836d1ac3fff1380c1e4b2cbb/Functional/allure-report-ce/index.html#categories

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39497/818ec47a1709a76123ea0eb25ba85165/Functional/allure-report-ce/index.html#categories

<img width="2394" height="1194" alt="image" src="https://github.com/user-attachments/assets/3cbcc77c-a926-4fed-81bb-c3d0bd3cd5fa" />

**Functional EE: Run 1**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39497/87e7ad9933411f97328bdc01f3dd6f24/Functional/allure-report-ee/index.html#categories/bdbf199525818fae7a8651db9eafe741

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39497/e6fa486c1ff5eb6733398ec5c9f742e6/Functional/allure-report-ee/index.html#categories

<img width="2358" height="1240" alt="image" src="https://github.com/user-attachments/assets/8c89e2d4-bdd1-4dfe-a7af-d286740f2dbd" />

2026-07-28 12:06 UTC, merged