#39382: Fix incorrect image display for directories with identical names but different case
magento/magento2 pull request #39502
Opened 2024-12-21 16:45 UTC by bhushan-cs

### Description (*)
This pull request addresses an issue where files uploaded to a specific directory in the Media Gallery are also visible in directories with similar names but different case.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#39382

### Manual testing scenarios (*)
1. OS - Ubuntu
2. Navigate to Content > Media Gallery
3. Create a folder under wysiwyg "Testing"
4. Upload an image in the newly created folder.
5. Select wysiwyg folder and try to create another folder named "testing"
6. Image uploaded to "Testing" folder should not show in "testing" folder.

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

2024-12-21 16:56 UTC, bhushan-cs commented
@magento run all tests

2025-02-21 18:43 UTC, bhushan-cs commented
@magento run all tests

2025-08-05 06:03 UTC, engcom-Hotel commented
@magento run all tests

2025-08-05 13:37 UTC, engcom-Hotel requested changes
Hello @bhushan-cs,

Thanks for the contribution!

The code changes seems good to us, but please refer to the below review comments:

1. Add some automated tests for case-sensitive path filtering.
2. Add code comments explaining the BINARY requirement.

2025-08-06 11:39 UTC, bhushan-cs commented
Hello @engcom-Hotel,

Thank you for the feedback!

I have addressed both review comments:
1. Automated Tests Added
I've implemented comprehensive test coverage for case-sensitive path filtering:
Unit Tests: `app/code/Magento/MediaGalleryUi/Test/Unit/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryTest.php`
Integration Tests: `app/code/Magento/MediaGalleryUi/Test/Integration/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryIntegrationTest.php`
2. Code Comments Added
Added inline comments which explains why BINARY comparison prevents incorrect file visibility across case-variant directories.

Please let me know if you need any adjustments to the tests or documentation!

2025-08-07 05:09 UTC, engcom-Hotel commented
@magento run all tests

2025-08-07 09:38 UTC, engcom-Hotel requested changes
Hello @bhushan-cs,

Please fix the failed static test, other tests seems flaky to me.

2025-08-07 09:38 UTC, engcom-Hotel commented on app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
> +        $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
Suggestion: Consider to add fallback behaviour with error handling:
```suggestion
       try {
    $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
} catch (\Exception $e) {
    // Log error and fallback to non-BINARY comparison
    $this->logger->error('BINARY regex failed, falling back: ' . $e->getMessage());
    $collection->getSelect()->where('path REGEXP ? ', '^' . $value . '/[^\/]*$');
}
```

2025-08-07 09:38 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2025-08-08 10:12 UTC, bhushan-cs commented on app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
> +        $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
Hello @engcom-Hotel,

The static test is giving warning on Magento copywriter comment. Do we have to change it to B2B copywriter comment?
```php
* Copyright 2019 Adobe
* All Rights Reserved.
 ```
 

> Suggestion: Consider to add fallback behaviour with error handling:

Great suggestion! I agree that adding error handling makes the solution more robust. I've added a few small modifications:
```php
try {
    $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
} catch (\Exception $e) {
    // Log the error for debugging but continue with case-insensitive fallback
    // Note: This fallback means directory filtering will not be case-sensitive
    $this->logger->error('MediaGallery Directory Filter: BINARY REGEXP not supported, using case-insensitive fallback: ' . $e->getMessage());
    $collection->getSelect()->where('path REGEXP ? ', '^' . $value . '/[^\/]*$');
}
```
I was not sure how to edit the code suggestion to add my changes.

2025-08-11 10:20 UTC, engcom-Hotel commented on app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
> +        $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
> The static test is giving warning on Magento copywriter comment. Do we have to change it to B2B copywriter comment?

You need to refer the files which is mentioned in the failed test, for example, consider the following screenshot:

<img width="2014" height="516" alt="image" src="https://github.com/user-attachments/assets/41a98b29-d664-48df-a20a-acf79aba1018" />

The above screenshot is from the below static test failure:

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/fa70983fcf29df8efaba5329f6467951/Statics/report-sanity-ce.html

2025-08-11 10:21 UTC, engcom-Hotel commented on app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
> +        $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
> I was not sure how to edit the code suggestion to add my changes.

You can directly edit this file from your local in the same branch, and commit as usual.

2025-08-11 10:23 UTC, engcom-Dash commented
Hi @bhushan-cs 

Just checking in to see if you're currently working on the changes. If not, I’m happy to take care of them to help move things forward. Let me know what works best for you.

Thanks!

2025-08-11 10:34 UTC, bhushan-cs commented on app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
> +        $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
Thanks for the guidance. Let commit the changes.

2025-08-11 10:35 UTC, bhushan-cs commented
Hi @engcom-Dash,

I was in process of pushing the requested changes. Do I have to assign the issue to me again?

2025-08-11 10:46 UTC, bhushan-cs commented
@magento run all tests

2025-08-11 13:26 UTC, bhushan-cs commented
@magento run all tests

2025-08-12 06:20 UTC, engcom-Hotel commented
Hello @bhushan-cs,

It seems the PR has been ready for review, hence picking it for the same.

Thanks

2025-08-12 06:21 UTC, engcom-Hotel commented
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

2025-08-12 13:02 UTC, engcom-Hotel requested changes
Hello @bhushan-cs,

Thanks for working on the changes!

The failed tests seems flaky to me, hence re-running the tests. Also please refer to the below review comments.

Thanks

2025-08-12 13:02 UTC, engcom-Hotel commented on app/code/Magento/MediaGalleryUi/Test/Unit/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryTest.php
> + * Copyright 2019 Adobe
```suggestion
 * Copyright 2025 Adobe
```

2025-08-12 13:02 UTC, engcom-Hotel commented on app/code/Magento/MediaGalleryUi/Test/Integration/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryIntegrationTest.php
> + * Copyright 2019 Adobe
```suggestion
 * Copyright 2025 Adobe
```

2025-08-12 13:02 UTC, engcom-Hotel commented on app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
> +    public function __construct(LoggerInterface $logger)
Make logger parameter optional with ObjectManager fallback for backward compatibility

2025-08-12 13:19 UTC, bhushan-cs commented on app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
> +    public function __construct(LoggerInterface $logger)
I've made the suggested change

2025-08-12 13:22 UTC, bhushan-cs commented
@magento run all tests

2025-08-13 05:31 UTC, bhushan-cs commented
@magento run Static Tests, Unit Tests

2025-08-13 05:33 UTC, engcom-Hotel commented
@magento run all tests

2025-08-13 14:38 UTC, engcom-Hotel commented
@magento run all tests

2025-08-14 05:38 UTC, engcom-Hotel commented
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2025-08-14 10:43 UTC, engcom-Hotel commented
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2025-08-19 05:21 UTC, bhushan-cs commented
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

2025-08-19 10:41 UTC, engcom-Hotel approved these changes
Failed tests seems flaky to me, hence approving the PR.

2025-10-23 10:01 UTC, engcom-Bravo commented
@magento run all tests

2025-10-23 11:16 UTC, engcom-Bravo commented
Hi @bhushan-cs,

hanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Manual testing scenarios**

- OS - Ubuntu
- Navigate to Content > Media Gallery
- Create a folder under wysiwyg "Testing"
- Upload an image in the newly created folder.
- Select wysiwyg folder and try to create another folder named "testing"
- Image uploaded to "Testing" folder should not show in "testing" folder.


**Before:** :heavy_multiplication_x:

<img width="1419" height="653" alt="Screenshot 2025-10-23 at 2 58 51 pm" src="https://github.com/user-attachments/assets/edb42656-3ffd-46ad-893f-aa81cd8a1a8e" />






**After:** :heavy_check_mark:



<img width="1422" height="589" alt="Screenshot 2025-10-23 at 3 41 07 pm" src="https://github.com/user-attachments/assets/17d0c207-7007-48e3-99d2-5bc72c07a873" />



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

2025-10-24 06:11 UTC, engcom-Dash commented
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

2025-10-27 06:59 UTC, engcom-Dash commented
@magento run all tests

2025-10-27 10:11 UTC, engcom-Dash commented
The consistent failures in Functional CE, EE, and B2B are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes.

CE
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/05e881c5e7539c08039ee2ab543b04a0/Functional/allure-report-ce/index.html#categories/f4d0095a9a43652d955b7145d894756e/efd5d7aa22b36c09/
<img width="1473" height="322" alt="image" src="https://github.com/user-attachments/assets/2736a18f-56c7-4fe3-a685-0fdd3868b23f" />
Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/177804d41e175c6c590b62e81aa7eb22/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
<img width="1210" height="324" alt="image" src="https://github.com/user-attachments/assets/0e137d0c-c2b9-4da4-b28c-cb41dd3a3cf4" />


EE
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/84fdb4dc2fdaa602df9591edd4e47741/Functional/allure-report-ee/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/b77ef5b418e7caab/
<img width="1475" height="330" alt="image" src="https://github.com/user-attachments/assets/d677729c-47da-44cc-bdb6-dbdba11e8c2d" />
Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/1d69fe8471ea1e4dafe1573dd36d0827/Functional/allure-report-ee/index.html
<img width="1485" height="422" alt="image" src="https://github.com/user-attachments/assets/4366bf02-6e64-4522-8d79-bb7ac8119250" />

B2B
Build 1
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/2c87266b45ee6b3d1335b3b504751421/Functional/allure-report-b2b/index.html
<img width="1469" height="462" alt="image" src="https://github.com/user-attachments/assets/3d9e13a3-be68-44bc-85a9-a1da4177170e" />
Build 2
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/f341587196bf8c87a77d1ba44263a411/Functional/allure-report-b2b/index.html
<img width="1476" height="585" alt="image" src="https://github.com/user-attachments/assets/5ddd40fc-e74a-41fe-8fe3-103fe970feef" />

Known Issue
StorefrontPersistentCartCheckoutAfterSessionExpireLoginAndOrderTest [ACQE-8907](https://jira.corp.adobe.com/browse/ACQE-8907)

Hence, Moving this PR Merge In Progress

2025-11-20 15:18 UTC, merged