CLI App Event Subscribers
magento/magento2 pull request #4298
Opened 2016-04-25 18:03 UTC by gsomoza

Add the possibility to attach EventSubscribers to the Magento CLI application directly from components. This allows components to listen to Symfony Console events in order to trigger custom behaviour.

This PR was made to support the following initiative: https://github.com/magento-hackathon/MagentoMigrations

## How it works
The PR uses a `SubscriberManager` class during the application's bootstrap process. This class receives an array of `subscribers` during instantiation, so it can be configured easily in one or more component's `di.xml` file:

```xml
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\Console\SubscriberManager">
        <arguments>
            <argument name="subscribers" xsi:type="array">
                <item name="upgradeSubscriber" xsi:type="string">MagentoHackathon\MagentoMigrations\Cli\Subscriber\UpgradeSubscriber</item>
            </argument>
        </arguments>
    </type>
</config>
```

A sample subscriber would look as follows:
```php
<?php
namespace MagentoHackathon\MagentoMigrations\Cli\Subscriber;

use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\Console\Event\ConsoleCommandEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

/**
 * Class UpgradeSubscriber
 *
 * @author Gabriel Somoza <gabriel.somoza@cu.be>
 */
final class UpgradeSubscriber implements EventSubscriberInterface
{
    /**
     * getSubscribedEvents
     * @return array
     */
    public static function getSubscribedEvents()
    {
        return [
            ConsoleEvents::COMMAND => 'onCommand',
        ];
    }

    /**
     * afterSetupUpgrade
     * @return void
     */
    public function onCommand(ConsoleCommandEvent $event)
    {
        if ($event->getCommand()->getName() === 'setup:upgrade') {
            // do something before this commands run
        }
    }
}
```

2016-04-25 18:08 UTC, gsomoza commented
@freakphp @nhp @zbych - and thanks for the help @antonkril.

I'm sure there will have to be additions. For starters: I wasn't sure whether to add unit tests because I couldn't find any existing unit tests for this part of the code. If you point me in the right direction then I'll do that. And for the rest: open to comments / suggestions.

2016-04-26 16:13 UTC, gsomoza commented
Found the tests :)

2016-05-06 13:55 UTC, mazhalai commented
@gsomoza looks like there are still some static test failures: https://travis-ci.org/magento/magento2/jobs/125887880#L657

2016-05-06 20:44 UTC, gsomoza commented
Ah, never got back to this. I'll fix it as soon as I can.

2016-05-14 20:51 UTC, piotrekkaminski commented
@gsomoza any luck with that? Travis fails on code style checks seemingly in the code you committed. Can you check and update the PR?

2016-05-17 03:13 UTC, gsomoza commented
Made some changes & refactored a bit, please review again. 

Looks like tests are failing on something else at the moment?

2016-05-23 12:56 UTC, gsomoza commented
Can someone trigger the Travis-CI build please? Would like to see if the fails are a one-time unrelated thing (as it seems) or really some errors on my code.

2016-05-23 15:30 UTC, Vinai commented
I've triggered a rebuild. However, the PR needs to be rebased onto the current develop branch (or you can merge).
When you are ready, updating the PR will automatically trigger another rebuild.

2016-05-25 17:53 UTC, gsomoza commented
A lot of the tests that failed don't seem to be related to my changes... anything else you need from me regarding this?

2016-05-26 20:11 UTC, Vinai commented
Thanks! I think the travis build is broken again. Hope it will be fixed again, quickly. I don't have any details, but for now I can't think of anything. Lets wait until the travis build works again.

2016-06-14 16:15 UTC, gsomoza commented
Are there any updates on the Travis build issues? Or can I subscribe to some ticket so I can get notified when Travis is working again? If there's no ticket for that I'd be happy to create one.

2016-06-25 15:16 UTC, gsomoza commented
@Vinai any updates on this?

2016-06-25 15:43 UTC, Vinai commented
I have no insight, sorry. Maybe @mazhalai can say more?

2016-08-25 17:45 UTC, piotrekkaminski commented
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/CLI-App-Event-Subscribers/idi-p/45140).

2016-08-26 07:28 UTC, gsomoza commented
What's the status of this @piotrekkaminski ? Is there anything waiting on me, or anything I can do to help?

2017-02-03 23:49 UTC, gsomoza commented
@piotrekkaminski @Vinai FYI rebased so we can maybe merge this if all is OK? the failing tests don't seem to be related to my code.

2017-06-08 10:04 UTC, ishakhsuvarov commented
@gsomoza Please try updating again. Currently there should be no issues with the Travis CI builds.

2017-06-09 12:15 UTC, gsomoza commented
I'll make the update hopefully within the next week or so. Thanks.

2017-06-26 09:52 UTC, gsomoza commented
@ishakhsuvarov updated and all is green

2017-07-29 03:59 UTC, okorshenko commented
Hi @gsomoza 
Thank you for your contribution. Looks like this is not finished implementation. The class `Magento\Framework\Console\SubscriberManager` does not exist. 

1. How can the developer subscribe on the event?
2. How will this feature work in case of installation? The configuration should be provided by the module, but during the installation process, modules configuration will be unavailable on some stages. I don't see how this feature resolves this issue. Could you please clarify this.

Also I have some other comment about existing implementation, but let's start from basics.

Thank you

2017-08-01 06:58 UTC, gsomoza commented
Hi @okorshenko - I have a local version of `\Magento\Framework\Console\SubscriberManager` that's basically working but I didn't include it in this PR because it's part of a bigger set of changes and I thought maybe we could merge these small ones first. 

If you think it belongs here (and I'd understand that, cause I forgot to update the description) then I'll merge and push - but that may take me quite long time so I'd prefer if we could approach it on small chunks like these.. let me know what you prefer.

2017-08-01 15:14 UTC, okorshenko commented
Hi @gsomoza 
Thank you for the response. Unfortunately we can not accept not shippable implementation. In case you will drop the other part of the feature, this code will be useless. 
We can merge it only if it works.
I will provide additional comments via code review

2017-08-01 15:21 UTC, gsomoza commented
Ok, I'll look into adding the subscriber as well.

2017-08-01 15:23 UTC, okorshenko requested changes

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer.php
> +        $this->eventManager->trigger(new AfterSchemaWasInstalled($this, $setup, $this->context));
please, remove $this from the argument. We are return null from the method getTarget. The interface of this class is dirty and we don't want to spread it across the system through event arguments

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer.php
> +        $this->eventManager->trigger(new AfterDataWasInstalled($this, $setup, $this->context));
see the previous comment. Remove $this from the argument list

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer.php
> +            $event = new BeforeModuleIsProcessed($this, $setup, $moduleContext, $type);
see the previous comment. Remove $this from the argument list

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer.php
> +            if ($event->propagationIsStopped()) {
remove this if statement. The event should notify the system that something happened, but it should not terminate the entire process. Also, this does not work for asynchronous events. 
If you would like to terminate the process, we should introduce another extension point for that, but not events.

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer.php
> +    public function getObjectManager()
why do we need this method in the interface? Please, remove this method. This interface should not provide such methods

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer/Event/AbstractInstallerEvent.php
> +
Please, add Magento licence to all new files

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer/Event/AfterDataWasInstalled.php
> +class AfterDataWasInstalled extends AbstractInstallerEvent
please, remove `Was` from the class name

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer/Event/AfterSchemaWasInstalled.php
> +class AfterSchemaWasInstalled extends AbstractInstallerEvent
please, remove `Was` from the class name

2017-08-01 15:23 UTC, okorshenko commented on setup/src/Magento/Setup/Model/Installer/Event/BeforeModuleIsProcessed.php
> +class BeforeModuleIsProcessed extends AbstractInstallerEvent
We need to re-work on this event name. The current name does not reflect the application event enough.

2017-08-11 19:58 UTC, okorshenko commented
Hi @gsomoza 
Do we have some progress on this PR? Do you need some help?

2017-08-14 08:21 UTC, gsomoza commented
@okorshenko I haven't been able to do this yet, but it's at the top of my list for as soon as I have a chance to do any open source work. 

You're certainly welcome to help implement `SubscriberManager`, apply any of the small changes requested in the review (assuming that's what you meant), or anything else you may have in mind. I'd love to see this effort come to fruition so we can start building plugins that hook to the setup app.

2017-08-14 15:21 UTC, okorshenko commented
Hi @gsomoza 
I added this PR to Up For Grabs project. Closing this PR for now. We will reopen it when ready for next interaction of code review.

2017-08-14 15:21 UTC, closed without merging

2017-08-14 15:23 UTC, gsomoza commented
Works for me, I'll reopen when I'm ready with the changes. 👍