Make filtering aware of product visibility and fixe an issue with in_array check
magento/magento2 pull request #6035
Opened 2016-08-07 16:09 UTC by allanpaiste

Fixes the issue that was caused by two factors: 

1. Visibility attribute was not indexed in EAV
2. Visibility filter was never applied due to a in_array check that compared int and string values which resulted in false-negative check.

Addresses issue: https://github.com/magento/magento2/issues/5670

2016-08-11 15:07 UTC, v-r commented on app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php
> +        if (!is_array($condition) || !in_array((string)key($condition), ['from', 'to'])) {
we can use strict flag: like in_array(key($condition), ['from', 'to'], true)

2016-08-12 13:53 UTC, allanpaiste commented on app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php
> +        if (!is_array($condition) || !in_array((string)key($condition), ['from', 'to'])) {
true that. was not aware of the 3rd argument :)

2016-09-29 10:58 UTC, tkacheva commented
@allanpaiste please look into issues with your PR

2016-09-29 15:11 UTC, mombrea commented on app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php
> +        if (!is_array($condition) || !in_array((string)key($condition), ['from', 'to'])) {
I can confirm that the suggested change by @v-r along with this pull request do solve the problem. We need this fix which we've made on our local install. @allanpaiste any chance you can update this one line and submit the PR again? I could make a new request but I'd just be copying your work!

2016-09-29 18:42 UTC, allanpaiste commented on app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php
> +        if (!is_array($condition) || !in_array((string)key($condition), ['from', 'to'])) {
changed & pushed. I don't mind if my work gets copied as long as Magento gets better :)

2016-09-29 19:09 UTC, allanpaiste commented on app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php
> +        if (!is_array($condition) || !in_array((string)key($condition), ['from', 'to'])) {
Okay it seems that the build fails with pretty cryptic error. Considerign that develop branch itself is all in red, I would rather wait the PR target to go to be back in green before looking into that one. 

Considering the narrow scope of the change I really doubt that it's caused by this branch.

2016-11-02 08:14 UTC, shuaiZend commented
@allanpaiste  i used 2.1.2,when i replace AbstractEav.php from https://github.com/magento/magento2/pull/6035/files

and flush cache, and reindex..

`[root@199 magento2]# bin/magento index:reindex
Design Config Grid index has been rebuilt successfully in 00:00:02
Customer Grid index has been rebuilt successfully in 00:00:02
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '254-99-1-4' for key 'PRIMARY', query was: INSERT INTO `catalog_product_index_eav_idx` SELECT DISTINCT  `pid`.`entity_id`, `pid`.`attribute_id`, `pid`.`store_id`, IFNULL(pis.value, pid.value) AS `value` FROM (SELECT DISTINCT  `s`.`store_id`, `s`.`website_id`, `dd`.`attribute_id`, COALESCE(ds.value, dd.value) AS `value`, `cpe`.`entity_id` FROM `store` AS `s`
 LEFT JOIN `catalog_product_entity_int` AS `dd` ON dd.store_id = 0
 LEFT JOIN `catalog_product_entity_int` AS `ds` ON ds.store_id = s.store_id AND ds.attribute_id = dd.attribute_id AND ds.entity_id = dd.entity_id
 LEFT JOIN `catalog_product_entity_int` AS `d2d` ON d2d.store_id = 0 AND d2d.entity_id = dd.entity_id AND d2d.attribute_id = 97
 LEFT JOIN `catalog_product_entity_int` AS `d2s` ON d2s.store_id = s.store_id AND d2s.attribute_id = d2d.attribute_id AND d2s.entity_id = d2d.entity_id
 LEFT JOIN `catalog_product_entity` AS `cpe` ON cpe.entity_id = dd.entity_id WHERE (s.store_id != 0) AND ((ds.value IS NOT NULL OR dd.value IS NOT NULL)) AND (COALESCE(d2s.value, d2d.value) = 1)) AS `pid`
 LEFT JOIN `catalog_product_entity_int` AS `pis` ON pis.entity_id = pid.entity_id AND pis.attribute_id = pid.attribute_id AND pis.store_id = pid.store_id WHERE (pid.attribute_id IN('99')) AND (IFNULL(pis.value, pid.value) IS NOT NULL) AND (NOT(pis.value IS NULL AND pis.value_id IS NOT NULL))
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:03`

how to fix it?

2017-02-14 14:53 UTC, maghamed commented
Hi @allanpaiste 

How does current fix could address issue [#5670](https://github.com/magento/magento2/issues/5670), if Layered Navigation uses CatalogSearch Fulltext index and there are dedicated filters for visibility there specified in search_request.xml file
`<filter xsi:type="termFilter" name="visibility_filter" field="visibility" value="$visibility$"/>`

2017-02-16 12:44 UTC, maghamed requested changes

2017-02-16 12:44 UTC, maghamed commented on app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Eav/AbstractEav.php
> +        $attribute = $this->_eavConfig->getAttribute(\Magento\Catalog\Model\Product::ENTITY, 'visibility');
It's better to use constant from Public Service Contract API 
\Magento\Catalog\Api\Data\ProductAttributeInterface::ENTITY_TYPE_CODE

2017-02-16 12:44 UTC, maghamed commented on app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Eav/AbstractEav.php
> +        $this->_prepareIndex($entityIds, $attribute->getAttributeId());
why do we have additional call for _prepareIndex? if we had one before in chaining call.

This code looks awkward for me, as we have:

$this->_prepareIndex()->_prepareRelationIndex()->_prepareIndex($entityIds, $attribute->getAttributeId())->_removeNotVisibleEntityFromIndex();

The fact that we should to call the same method twice says about code smell

2017-02-17 22:11 UTC, mombrea commented on app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Eav/AbstractEav.php
> +        $this->_prepareIndex($entityIds, $attribute->getAttributeId());
The additional call to _prepareIndex is necessary for this to work. Removing it results in the same incorrect visibility behavior.

2017-02-18 16:26 UTC, closed without merging