Replace EE License Placeholder text with filename
magento/magento2 pull request #6385
Opened 2016-08-29 16:41 UTC by navarr

Resolves #5528

2016-10-13 09:51 UTC, orlangur commented on COPYING.txt
> +Please see LICENSE_EE.txt for the full text of the MEE License or visit http://magento.com/legal/terms/enterprise.
I don't think referring to a file which is actually missing in CE repository is correct.

Is there any problem with adding this file to CE repository also? It does not seem to me to bring any confusion as each module [defines](https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/composer.json#L26) applicable licenses.

2016-10-13 09:51 UTC, orlangur requested changes

2016-10-13 09:51 UTC, orlangur commented on COPYING.txt
> +Please see LICENSE_EE.txt for the full text of the MEE License or visit http://magento.com/legal/terms/enterprise.
I don't think referring to a file which is actually missing in CE repository is correct.

Is there any problem with adding this file to CE repository also? It does not seem to me to bring any confusion as each module [defines](https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/composer.json#L26) applicable licenses.

2016-10-17 12:44 UTC, navarr commented
I am personally uncomfortable adding the LICENSE which as of now is only available in software that is supposed to be kept private to the repository.

I would not want to open myself nor my employer up to any sort of legal issue related to revealing things we shouldn't.

2016-10-25 18:35 UTC, navarr commented on COPYING.txt
> +Please see LICENSE_EE.txt for the full text of the MEE License or visit http://magento.com/legal/terms/enterprise.
I am personally uncomfortable adding the LICENSE which as of now is only available in software that is supposed to be kept private to the repository.

I would not want to open myself nor my employer up to any sort of legal issue related to revealing things we shouldn't.

2017-03-22 17:25 UTC, woosley-mg commented
@navarr Wanted to comment on this directly, since I strongly support this change.  Because it will introduce another diff bomb (every file reporting a change), I'd prefer to defer this until the end of the year, when we will likely package it as a separate release.  Great work, and looking forward to never having to update this again!

2017-03-23 10:51 UTC, orlangur commented
@vrann do you mean some response in internal discussion? Here we finished our conversation with PR author as he is really not in charge of adding new license file to repo :)

2017-03-23 14:02 UTC, vrann commented
@orlangur exactly.

2017-04-12 19:01 UTC, vrann commented
@navarr can you please merge with the latest develop? I'm ready to accept it

2017-04-13 04:20 UTC, merged

2017-04-13 04:25 UTC, magento-team commented
@navarr thank you for your contribution to Magento 2 project