Update ViewAction.php
magento/magento2 pull request #6742
Opened 2016-09-25 07:46 UTC by vrgfa

In flles 
magento/module-sales/view/adminhtml/ui_component/sales_order_view_creditmemo_grid.xml
magento/module-sales/view/adminhtml/ui_component/sales_order_view_invoice_grid.xml
magento/module-sales/view/adminhtml/ui_component/sales_order_view_shipment_grid.xml

the following snippet is used:
        <actionsColumn name="actions" class="Magento\Sales\Ui\Component\Listing\Column\ViewAction">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="indexField" xsi:type="string">entity_id</item>
                    <item name="viewUrlPath" xsi:type="string">sales/order_creditmemo/view</item>
                    <item name="urlEntityParamName" xsi:type="string">creditmemo_id</item>
                </item>
            </argument>
        </actionsColumn>

however, unlike "viewUrlPath" and  "urlEntityParamName"  the item named "indexField" is not implemented in the code of Magento\Sales\Ui\Component\Listing\Column\ViewAction

It is needed when adding a custom table the same way as credmemo, invoice and shipment grids with a an index field other than "entity_id"

2016-09-25 07:46 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=6742) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=6742) before we can accept your contribution.<br/>

2017-05-17 17:19 UTC, orlangur requested changes

2017-05-17 17:19 UTC, orlangur commented on app/code/Magento/Sales/Ui/Component/Listing/Column/ViewAction.php
> +                                    $urlEntityParamName => $item[$indexField]
Why need such flexibility? Please provide a valid use case.

2017-06-06 14:17 UTC, orlangur commented
Closing for now due to no response from author.

2017-06-06 14:17 UTC, closed without merging