fix #6961
magento/magento2 pull request #6971
Opened 2016-10-12 13:43 UTC by razbakov

2016-10-12 13:43 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=6971) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=6971) before we can accept your contribution.<br/>

2016-10-13 10:03 UTC, orlangur requested changes

2016-10-13 10:03 UTC, orlangur commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Image.php
> +                '_type' => \Magento\Framework\UrlInterface::URL_TYPE_MEDIA
This code is not even syntactically correct: https://travis-ci.org/magento/magento2/jobs/167057903#L825

Did you mean array here?

2016-10-13 15:51 UTC, razbakov commented on app/code/Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Image.php
> +                '_type' => \Magento\Framework\UrlInterface::URL_TYPE_MEDIA
oh, yes, sorry

2017-02-15 16:37 UTC, orlangur approved these changes

2017-03-22 22:55 UTC, merged

2017-03-22 23:10 UTC, vrann commented
@razbakov Thank you for the contribution!