Fix trailing slash used a product URL suffix
magento/magento2 pull request #7041
Opened 2016-10-16 16:02 UTC by sitepodmatt

In reference to issue #7040

2016-10-16 16:02 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=7041) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=7041) before we can accept your contribution.<br/>

2016-10-16 19:16 UTC, redelschaap approved these changes
This fixes an issue I had with URLs with trailing slashes.

2016-10-22 21:49 UTC, Ctucker9233 commented
Please merge.

2016-12-02 10:02 UTC, sitepodmatt commented
Is there any ETA on merging this?

2017-02-15 13:07 UTC, orlangur requested changes

2017-02-15 13:07 UTC, orlangur commented on app/code/Magento/UrlRewrite/Controller/Router.php
> +            UrlRewrite::REQUEST_PATH => ltrim($requestPath, '/'),
Would be nice to cover such an important case with integration test also.

2017-02-15 13:15 UTC, hostep commented
I recently added the same PR, but it was rejected: https://github.com/magento/magento2/pull/8319, I wasn't aware there was already a similar PR, sorry about that.

@orlangur: maybe talk with @okorshenko & @miakusha before proceeding?

2017-02-15 13:38 UTC, orlangur commented
Thanks for reference, @hostep, I was not aware of your PR as well.

Then this PR should be rejected for similar reasons and integration test should be written for new trimming slashes behavior when saving.

> I'd recommend trim values provided in admin UI before saving to DB (new behavior)

Import should not be forgotten also.

2017-03-07 14:25 UTC, onepack commented
This saved me! But it only works when I put the change in the vendor/magento directory and not in app/code/magento.
Can anyone explain why?

2017-03-07 14:48 UTC, orlangur commented
@onepack it's because of composer autoload precedence. Just override core classes properly instead of in place editing. Here is some quickly googled link: http://stackoverflow.com/a/39424354

For this kind of issue better use Stack Overflow directly.

2017-03-07 15:15 UTC, onepack commented
@orlangur Thank you! Indeed, this belongs to Stack overflow.

2017-03-07 16:09 UTC, ulftietze approved these changes

2017-03-23 19:29 UTC, vrann commented
see #8319

2017-05-18 20:49 UTC, vrann commented
@sitepodmatt please see the discussion here: #8319

This fix dos not take into account the current use-case:
redirect: "test" => "contact"
http://magento.loc/test/ => http://magento.loc/contact

In order to make the complete fix next cases should be supported:

|#|redirect|behaviour|
|---|---|---|
|1|"test" => "contact"|http://magento.loc/test/ => http://magento.loc/contact|
|2|"test" => "contact"|http://magento.loc/test => http://magento.loc/contact|
|3|"test/" => "contact/"|http://magento.loc/test/ => http://magento.loc/contact/|
|4|"test/" => "contact/"|http://magento.loc/test => http://magento.loc/contact/|

2017-05-18 20:49 UTC, closed without merging

2017-05-19 07:07 UTC, redelschaap commented
@vrann I disagree with you that http://magento.loc/test/ should redirect to http://magento.loc/contact when a redirect "test" => "contact" has been set. And many SEO experts would share that opinion with me, as /test/ is a completely different URL than /test from SEO perspective. /test should be able to redirect to (or load) a different URL than /test/.

If Magento wants still this behaviour, I think it should be a config setting to support whatever the store owner prefers - SEO optimization or convenience.

2017-05-19 19:44 UTC, vrann commented
@redelschaap configuration makes sense, otherwise, the change will be backward incompatible

2017-05-19 20:35 UTC, vrann commented
@redelschaap Thanks to @pboisvert I read this article https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html which suggest a) both "test/" and "test" always serve same content b) have one redirected to another with 301 c) be consistent on which one getting redirected

If we apply these suggestions to URL rewrites, the current behavior redirecting "test/" and "test" to the content seems aligned with the requirements. Requests "test" and "test/" should not be redirected to the different urls.  Do you agree?

2017-05-19 21:07 UTC, tdgroot commented
FWIW, I think every suffix should be supported and configurable. There shouldn't be a forced behavior how Magento redirects the requests.

To make your life easier; just don't use a prefix. It's readable and SEO-friendly. It also keeps you from this troubling conversation.

2017-05-20 11:56 UTC, redelschaap commented
@vrann I agree with the article, but theoretically `/test` and `/test/` are two totally different URLs, so in theory they should be able to serve different content and/or to redirect or to two different URLs. I also agree with @tdgroot in that every suffix should be supported and configurable.

Also, URLs ending with a `/` traditionally indicated a folder which could have one or more child pages or folders. URLs ending without a `/` (or with an file extension) indicated a page which was last in the chain of structure, which could not conain more pages or folders. We have clients with existing websites (and SEO history) where folders (categories and CMS pages) end with a `/`. They want to maintain that behaviour, to keep their SEO status on those pages. I know we can (manually) redirect those URLs, but that costs a percentage of the SEO status.

It would indeed improve usablility and maybe even conversions if `/test` would redirect to `/test/` when the suffix is set to `/` (or vice versa). One should not be forced to use one or the other, though.

2017-05-22 20:00 UTC, vrann commented
@redelschaap if we agree that the article makes sense, the default scheme of url rewrite resolution should be that both "test" and "test/" are redirected to the same page.

The fallback scheme might be to have the possibility to configure "test/" pointing at a different location if that is done on the purpose. So that if the rule is defined for either one, "test" or "test/", both requests will be redirected to the same resource; if the rule is defined for both of them, it will match exactly the needed resource. 

It sounds like larger PR with more logic. I would argue that the use-case is limited to legacy systems with the rewrites configured not in an optimal way, though if you observe big demand on it, it makes sense to have such PR.