Emogrifier update to 1.1.0
magento/magento2 pull request #7110
Opened 2016-10-20 16:42 UTC by Bartlomiejsz

Fixes #6946 and #4737

2016-10-23 20:14 UTC, orlangur requested changes

2016-10-23 20:14 UTC, orlangur commented on composer.json
> +        "pelago/emogrifier": "1.1.0",
Don't forget to commit changed `composer.lock` ;)

2016-10-25 20:00 UTC, Bartlomiejsz commented on composer.json
> +        "pelago/emogrifier": "1.1.0",
Yes, you're right, thanks :)

2016-11-01 19:35 UTC, orlangur approved these changes

2017-02-15 16:34 UTC, orlangur approved these changes

2017-03-25 14:11 UTC, vrann commented
@Bartlomiejsz please update the code with the latest develop branch

2017-04-20 14:37 UTC, Bartlomiejsz commented
@vrann, @orlangur I'm closing it, I've created new PR from the develop branch: #9327

2017-04-20 14:37 UTC, closed without merging

2017-04-20 14:56 UTC, orlangur commented
@Bartlomiejsz ok, let's go this way now, but generally it's better to force push into the same branch after you rebased against latest mainline ;)

2017-04-20 14:57 UTC, Bartlomiejsz commented
@orlangur ok, next time I will remember :)