fix for: ReferenceError: v is not defined and improved regex
magento/magento2 pull request #7133
Opened 2016-10-21 15:00 UTC by klict

Hello,

this is a small fix for uncaught ReferenceError: v is not defined ;

You guys were executing function test on variable v but i think you should use variable value since variable v is not defined anywhere.

Also my team leader has improved your the regex for "validate-clean-url" and "validate-url".

credit for regex @redelschaap.

2016-10-22 15:02 UTC, redelschaap commented
Note for my improved regex: [RFC 1035 section 2.3.4](http://www.freesoft.org/CIE/RFC/1035/9.htm) states that each part of a domain name can contain up to 63 characters, which means also the TLD extension can technically contain 63 charachters. The regex checks whether the DNS part of the URL contains valid parts and is not restricted to the set of TLD's of the original regex.

2016-10-23 03:14 UTC, sitepodmatt commented
Does this work with http://unicode.org/faq/idn.html?

2016-10-23 08:11 UTC, redelschaap commented
As a matter of fact it doesn't. But I have only improved the DNS part, so neither does the original.

These regex patterns do the trick. Since it's very hard to check for all allowed charachters in the path, query and fragment parts (for example, Chinese or Arabic letters are allowed too), it checks the three parts for whitespace characters only.

@klict Can you please change the regex patterns in your commit?

**validate-url**
```
return /^((http|https|ftp):\/\/)(([A-Z0-9][A-Z0-9_-]{1,62}\.)+([A-Z]{2,63}(\.[A-Z]{2,63})?))(:(\d+))?(\/[^\?#\s]*)?(\?[^#\s]*)?(#[^\s]*)?$/i.test(value);
```

**validate-clean-url**
```
return utils.isEmptyNoTrim(value) || /^((http|https|ftp):\/\/)?(([A-Z0-9][A-Z0-9_-]{1,62}\.)+([A-Z]{2,63}(\.[A-Z]{2,63})?))(:(\d+))?(\/[^\?#\s]*)?(\?[^#\s]*)?(#[^\s]*)?$/i.test(value);
```

2016-10-23 08:17 UTC, redelschaap requested changes
It didn't check for the path, query and fragment parts correctly, my bad!

2016-10-23 08:17 UTC, redelschaap commented on app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js
> +                return utils.isEmptyNoTrim(value) || /^((http|https|ftp):\/\/)?(([A-Z0-9][A-Z0-9_-]{1,62}\.)+([A-Z]{2,63}(\.[A-Z]{2,63})?)$)(:(\d+))?\/?/i.test(value);
It didn't check for the path, query and fragment parts correctly, my bad!

Correct return value:
````
                 return utils.isEmptyNoTrim(value) || /^((http|https|ftp):\/\/)?(([A-Z0-9][A-Z0-9_-]{1,62}\.)+([A-Z]{2,63}(\.[A-Z]{2,63})?))(:(\d+))?(\/[^\?#\s]*)?(\?[^#\s]*)?(#[^\s]*)?$/i.test(value);
````

2016-10-23 08:17 UTC, redelschaap commented on app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js
> +                return (/^((http|https|ftp):\/\/)(([A-Z0-9][A-Z0-9_-]{1,62}\.)+([A-Z]{2,63}(\.[A-Z]{2,63})?)$)(:(\d+))?\/?/i).test(value);
It didn't check for the path, query and fragment parts correctly, my bad!

Correct return value:
````
                 return /^((http|https|ftp):\/\/)(([A-Z0-9][A-Z0-9_-]{1,62}\.)+([A-Z]{2,63}(\.[A-Z]{2,63})?))(:(\d+))?(\/[^\?#\s]*)?(\?[^#\s]*)?(#[^\s]*)?$/i.test(value);
````

2017-03-25 14:09 UTC, vrann commented
@klict please update the code with the latest mainline

2017-06-07 22:12 UTC, okorshenko commented
Source branch has been removed. Closing this PR.

2017-06-07 22:12 UTC, closed without merging