Fix import history dependant needs session before injected
magento/magento2 pull request #7325
Opened 2016-11-05 02:27 UTC by torreytsui

Related issues:
https://github.com/magento/magento2/issues/4568
https://github.com/magento/magento2-sample-data/issues/19

# Suggested fix

Break the dependency chain by proxy so that the session requirement will only be required right before it is necessary.

# Cause of issue

`\Magento\ImportExport\Model\History` depends on `\Magento\Backend\Model\Auth\Session` which require session ready on construction.

While this requirement is likely to be satisfied in most cases on frontend, it is not the case when we run `bin/magento setup:upgrade`

**Dependency Hierarchy**

```
\Magento\ConfigurableSampleData\Setup\Installer
   |
  \Magento\ConfigurableSampleData\Model\Product
     |
    \Magento\ImportExport\Model\Import
       |
      \Magento\ImportExport\Model\History
          |
         \Magento\Backend\Model\Auth\Session
```

```
#0  unknown() called at [/src/m2/vendor/magento/framework/Session/SessionManager.php:169]
#1  Magento\Framework\Session\SessionManager->start() called at [/src/m2/var/generation/Magento/Backend/Model/Auth/Session/Interceptor.php:167]
#2  Magento\Backend\Model\Auth\Session\Interceptor->start() called at [/src/m2/vendor/magento/framework/Session/SessionManager.php:130]
#3  Magento\Framework\Session\SessionManager->__construct() called at [/src/m2/vendor/magento/module-backend/Model/Auth/Session.php:88]
#4  Magento\Backend\Model\Auth\Session->__construct() called at [/src/m2/var/generation/Magento/Backend/Model/Auth/Session/Interceptor.php:14]
#5  Magento\Backend\Model\Auth\Session\Interceptor->__construct() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93]
#6  Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89]
#7  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [/src/m2/vendor/magento/framework/ObjectManager/ObjectManager.php:71]
#8  Magento\Framework\ObjectManager\ObjectManager->get() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126]
#9  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53]
#10 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82]
#11 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [/src/m2/vendor/magento/framework/ObjectManager/ObjectManager.php:71]
#12 Magento\Framework\ObjectManager\ObjectManager->get() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126]
#13 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53]
#14 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82]
#15 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [/src/m2/vendor/magento/framework/ObjectManager/ObjectManager.php:71]
#16 Magento\Framework\ObjectManager\ObjectManager->get() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126]
#17 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53]
#18 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82]
#19 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [/src/m2/vendor/magento/framework/ObjectManager/ObjectManager.php:71]
#20 Magento\Framework\ObjectManager\ObjectManager->get() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126]
#21 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53]
#22 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82]
#23 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [/src/m2/vendor/magento/framework/ObjectManager/ObjectManager.php:71]
#24 Magento\Framework\ObjectManager\ObjectManager->get() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126]
#25 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53]
#26 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [/src/m2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82]
#27 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [/src/m2/vendor/magento/framework/ObjectManager/ObjectManager.php:57]
#28 Magento\Framework\ObjectManager\ObjectManager->create() called at [/src/m2/setup/src/Magento/Setup/Model/Installer.php:931]
#29 Magento\Setup\Model\Installer->createSchemaDataHandler() called at [/src/m2/setup/src/Magento/Setup/Model/Installer.php:1245]
#30 Magento\Setup\Model\Installer->getSchemaDataHandler() called at [/src/m2/setup/src/Magento/Setup/Model/Installer.php:841]
#31 Magento\Setup\Model\Installer->handleDBSchemaData() called at [/src/m2/setup/src/Magento/Setup/Model/Installer.php:796]
#32 Magento\Setup\Model\Installer->installDataFixtures() called at [/src/m2/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php:74]
#33 Magento\Setup\Console\Command\UpgradeCommand->execute() called at [/src/m2/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257]
#34 Symfony\Component\Console\Command\Command->run() called at [/src/m2/vendor/symfony/console/Symfony/Component/Console/Application.php:874]
#35 Symfony\Component\Console\Application->doRunCommand() called at [/src/m2/vendor/symfony/console/Symfony/Component/Console/Application.php:195]
#36 Symfony\Component\Console\Application->doRun() called at [/src/m2/vendor/magento/framework/Console/Cli.php:96]
#37 Magento\Framework\Console\Cli->doRun() called at [/src/m2/vendor/symfony/console/Symfony/Component/Console/Application.php:126]
#38 Symfony\Component\Console\Application->run() called at [/src/m2/bin/magento:23]
```

2016-11-05 02:27 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=7325) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=7325) before we can accept your contribution.<br/>

2017-03-24 01:41 UTC, vrann commented
@torreytsui Thank you for the contribution. Please check comments in the review

2017-03-24 01:42 UTC, vrann requested changes

2017-03-24 01:42 UTC, vrann commented on app/code/Magento/ImportExport/Model/History.php
> +        \Magento\Backend\Model\Auth\Session\Proxy $authSession,
Proxy should never be requested directly from the constructor. Instead, you should configure DI via di.xml to substitute Proxy for the authSession parameter.

2017-05-19 17:55 UTC, vrann commented
@torreytsui please see the comment to the code. It is based on http://devdocs.magento.com/guides/v2.1/coding-standards/technical-guidelines/technical-guidelines.html

Please reopen PR once fixed.

2017-05-19 17:55 UTC, closed without merging

2018-04-07 16:38 UTC, ahmed-oz commented
run this command
`php bin/magento sampledata:reset`
then run the upgrade