Travis should run the static tests against PHP 7
magento/magento2 pull request #7558
Opened 2016-11-24 20:58 UTC by dverkade

Travis should be changed so that static tests will be runned against PHP 7 as well. 

See for instance this build: https://travis-ci.org/magento/magento2/builds/178637640
Static tests pass against PHP 7 but fail against PHP 5.6. So there is difference between the two versions and we should build en pass static test for both PHP versions.

2016-11-30 15:34 UTC, orlangur commented
> So there is difference between the two versions and we should build en pass static test for both PHP versions.

Nope. We need only one static tests job but it must be PHP7 obviously due to performance reasons.

> See for instance this build: https://travis-ci.org/magento/magento2/builds/178637640

We test Magento code here, not phpcs or Travis CI environment-specific oddities. Looking at corresponding change https://github.com/magento/magento2/pull/7166/files#diff-2b5067e3a6c0d21915ae0431519dcc76R30 I don't see any value brought by phpcs (phpcs bug?).

2016-11-30 15:53 UTC, dverkade commented
Hi @orlangur 

> Nope. We need only one static tests job but it must be PHP7 obviously due to performance reasons.

There is definately a difference between the two. The "ForbiddenFunctions" sniff in PHPCS is loaded automatically by getting all the deprecated functions in PHP. The problem we are running into is that there is a function "mysql"  which is deprecated in PHP 5.6, so the build fails for PHP 5.6. In PHP 7 this function is no longer in PHP. So you want to check the PHPCS on all supported versions of PHP in order to make sure that deprecated functions are not used.

2016-11-30 16:50 UTC, orlangur commented
> The problem we are running into is that there is a function "mysql" which is deprecated in PHP 5.6, so the build fails for PHP 5.6

Please show me a deprecated function call in Magento code revealed by this report.

> So you want to check the PHPCS on all supported versions of PHP in order to make sure that deprecated functions are not used.

No, if we _really_ want to check different PHP versions compatibility, something like https://github.com/wimg/PHPCompatibility should be used which produces consistent results for any PHP version.

>  In PHP 7 this function is no longer in PHP. 

In such case we would see Fatal Error running under PHP7. So, while we maintain compatibility with latest stable PHP version it's enough to run static tests under it only.

2016-11-30 16:51 UTC, orlangur requested changes
_

2016-11-30 16:54 UTC, orlangur requested changes

2016-11-30 16:54 UTC, orlangur commented on .travis.yml
> -    - php: 7.0
Please change to 5.6 instead if removal.

2016-11-30 17:23 UTC, joshuaadickerson commented
Why would you use CS alone? That should produce warnings/notices. The tests should be run on each PHP version which would produce errors. Code smell is not something that breaks a website. A broken test is.

Run all tests in all supported environments or consider that you have 0% (or a percentage less) test coverage for those environments.

2016-12-01 10:11 UTC, orlangur commented
Because static tests DO NOT run the code of system under test.

If they produce different results on different environments, they MUST be fixed to produce consistent results and NOT enabled for all possible environments.

Here I can see that phpcs under PHP 5.6 produces a false positive which does not seem to be a Magento code problem.

2017-03-21 02:17 UTC, vrann commented
@dverkade If this PR is still actual, please sync with the latest develop

2017-03-21 06:01 UTC, orlangur commented
@vrann, this PR suggests to run static tests against both PHP 5.6 and PHP 7 while it is not necessary. As to me it shall be rejected.

Cc: @okorshenko

2017-03-23 16:21 UTC, maghamed commented
Here I have to agree with @orlangur we no need two environments for running static tests, because static tests by their nature shouldn't run code under the test.
Moreover taking into account that Magento 2.2. drops support of PHP 5.6 we have one additional  valid reason for not running static tests against PHP 5.6.

What should be dropped from Travis config is support of PHP 5.6 
php:
  - 5.6.29
  - 7.0

2017-03-23 16:22 UTC, vrann commented
@dverkade static tests should run against one PHP version, 7.0 is the one which makes the most sense to support. Please submit new PR with such update.

2017-03-23 16:22 UTC, closed without merging