Check return value for getProduct() in getPrice().
magento/magento2 pull request #7794
Opened 2016-12-14 14:09 UTC by pbaylies

If getProduct() returns a NULL value then this code will generate a PHP warning and potentially crash the page; let's not do that, and check our return values before we try to call methods on them.

2017-01-10 20:36 UTC, antonkril requested changes
Please consider saving results of getCustomOption() and getProduct() calls. Also please address static test feedback.

2017-01-10 20:52 UTC, antonkril approved these changes

2017-01-10 20:52 UTC, antonkril commented on app/code/Magento/ConfigurableProduct/Model/Product/Type/Configurable/Price.php
> +        if ( !empty( $product ) ) {
This check is not required

2017-03-08 21:22 UTC, vrann commented
@pbaylies Thank you for contribution. Can you please fix following code styles issues:

```
FILE: ...e/Magento/ConfigurableProduct/Model/Product/Type/Configurable/Price.php
--------------------------------------------------------------------------------
FOUND 6 ERROR(S) AFFECTING 3 LINE(S)
--------------------------------------------------------------------------------
 42 | ERROR | Expected 0 spaces after opening bracket; 1 found
 42 | ERROR | Expected 0 spaces before closing bracket; 1 found
 44 | ERROR | Expected 0 spaces after opening bracket; 1 found
 44 | ERROR | Expected 0 spaces before closing bracket; 1 found
 46 | ERROR | Expected 0 spaces after opening bracket; 1 found
 46 | ERROR | Expected 0 spaces before closing bracket; 1 found
--------------------------------------------------------------------------------
```

2017-03-08 22:36 UTC, pbaylies commented
@vrann I can't reproduce this; I don't see any extra spaces at the end of those lines on my committed file.

2017-03-13 14:41 UTC, vrann commented
@pbaylies 

these lines
```
if ( !empty( $product ) ) {
if ( !empty( $simpleProductOption ) ) {
if ( !empty( $simpleProduct ) ) {
```
should look like this:
```
if (!empty($product)) {
if (!empty($simpleProductOption)) {
if (!empty($simpleProduct)) {
```

2017-03-13 14:49 UTC, pbaylies commented
@vrann Done, thanks!

2017-03-14 01:16 UTC, vrann commented
@pbaylies Thank you!

2017-03-14 05:10 UTC, merged

2017-03-14 17:40 UTC, vrann commented
@pbaylies merged!