Prevent LogicException for not extending \Magento\Framework\App\Helper\AbstractHelper
magento/magento2 pull request #7807
Opened 2016-12-15 07:11 UTC by jimmydg

Prevent LogicException for not extending \Magento\Framework\App\Helper\AbstractHelper

2016-12-15 07:11 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=7807) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=7807) before we can accept your contribution.<br/>

2016-12-16 08:25 UTC, jimmydg commented
I don't understand why the CI is failing, can someone explain why it's failing?

2017-01-10 20:27 UTC, antonkril commented
@jimmydg, the CI failure is not related to your PR

2017-01-10 20:31 UTC, antonkril requested changes
The issue should be fixed on TemplateEngine level. It should check for helperInterface, not AbstractHelper.

2017-03-06 16:43 UTC, vrann commented
@jimmydg Thank you for the contribution. There are outstanding comments from the previous reviewers. Is there any chance you can fix them?

2017-03-23 13:24 UTC, vrann commented
@jimmydg this PR requires more work to do, please finish it and submit a new PR. Thanks!

2017-03-23 13:24 UTC, closed without merging