Add bin/magento commands to list store/website data
magento/magento2 pull request #7982
Opened 2016-12-28 19:17 UTC by convenient

### Proposal

I used commands in n98-magerun to output a list of store data and website data, nothing that can't be achieved by connecting to the database and doing a few `SELECT` statements but the magerun wrapper was very helpful in Magento 1.

I'd like to have these commands back in use for Magento 2

| magerun command  | proposed magento2 command  |
|---|---|
| magerun sys:store:list  |  bin/magento store:list |
| magerun sys:website:list  |  bin/magento store:website:list |

### Naming things

>There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton
> http://martinfowler.com/bliki/TwoHardThings.html 

I think the `website:list` command should live in the same place as the `store:list` command because both entities are part of the `Mage/Store` module.  Any commands in the `Mage/Store` module should be prefixed with `store`. However, this gives us the odd naming hierarchical structure in the command names listed, listing a website has to include the word `store` or break convention.

If anyone has any suggestions I'm all ears, I've gone for option 1 by default.

 | option  | list stores  | list websites|
|---|---|---|
| Option 1  |  bin/magento store:list | bin/magento store:website:list |
| Option 2 |  bin/magento store:list:store | bin/magento store:list:website |
| Option 3 |  bin/magento store:list | bin/magento website:list |

### A comment on my code

I'm not sure if this is the correct standard for creating new CLI commands. I copied the approach from the sample data module. If this method is outdated shout out.

### Example usage and output

```
$ bin/magento store:website:list
+----+------------------+--------------+-------+------------+------------+
| ID | Default Group Id | Name         | Code  | Sort Order | Is Default |
+----+------------------+--------------+-------+------------+------------+
| 0  | 0                | Admin        | admin | 0          | 0          |
| 1  | 1                | Main Website | base  | 0          | 1          |
| 2  | 2                | Other Site   | other | 0          | 0          |
+----+------------------+--------------+-------+------------+------------+

$ bin/magento store:list
+----+------------+----------+--------------------+---------+------------+-----------+
| ID | Website ID | Group ID | Name               | Code    | Sort Order | Is Active |
+----+------------+----------+--------------------+---------+------------+-----------+
| 0  | 0          | 0        | Admin              | admin   | 0          | 1         |
| 1  | 1          | 1        | Default Store View | default | 0          | 1         |
| 2  | 2          | 2        | Other Store View   | other   | 0          | 1         |
+----+------------+----------+--------------------+---------+------------+-----------+
```

2016-12-29 09:03 UTC, hostep commented
Just FYI, these command also exist in [n98/magerun2](https://github.com/netz98/n98-magerun2), but contain less detailed output then what you are suggesting:

```bash
$ vendor/bin/n98-magerun2 sys:website:list


  Magento Websites


+----+------+
| id | code |
+----+------+
| 1  | base |
+----+------+

$ vendor/bin/n98-magerun2 sys:store:list
+----+------+
| id | code |
+----+------+
| 1  | nl   |
| 3  | fr   |
+----+------+


```

So if this PR is accepted, I think it's best if these commands then are removed from n98/magerun2, since otherwise we will have 2 commands to do the same thing.
Let's include @ktomk in here as well.

2016-12-29 09:08 UTC, convenient commented
@hostep From a purely outsider point of view, I'm wondering whether any of the commands in n98-magerun2 should have any bearing on what is baked into the magento core. 

Eg, there are many third party apps that handle layered navigation but magento still includes their own one.

Furthermore, if the core `bin/magento` commands do what I need then I'm wondering if there would be much value in having magerun2 installed on production servers for example.

I do like magerun a lot and have contributed to the v1 version, but am just not sure where the divide in logic goes now that a lot of the core deployment steps are baked into `bin/magento`

Also I know the tests are failing for this PR, will review.

2016-12-29 09:23 UTC, hostep commented
Well, n98-magerun2 works by inheriting all the commands from `bin/magento` and then adding a few more on top of them. So my concern is not with the commands baked into `bin/magento`, I just wanted to make sure the maintainers of n98-magerun2 were aware of your PR.

The upside of the n98-magerun2 command, is that new (and useful) features are implemented much faster then in Magento core. It wouldn't surprise me that this PR is going to take a couple of months to be included into core Magento, while if you would create a PR to enhance the feature in n98-magerun2, it will probably be released in a new version in less then a month time. And you could then use it on all Magento 2 versions and not only on the very last one.

I do agree with you that some features from n98-magerun2 might as well be ported over to core Magento for users who don't want to use n98-magerun2, but then those users will have to wait a long time until it happens I'm afraid.

In the end, it all boils down to what the maintainers from Magento and n98-magerun2 agree upon on where certain features should be implemented I think.

Just my 2 cents :)

2016-12-29 09:39 UTC, convenient commented
@hostep All valid points regarding M2 turnaround time etc. However, I'd at least want to _try_ and make the magento 2 code a better place to be rather than building scaffolding on top of it.

Thanks for highlighting this to me, I wasn't aware of how magerun2 worked and that does seem like an area for conflict.

2016-12-29 16:45 UTC, convenient commented
## Failing test

Here's my attempt at stopping the suite from failing, but I'm not really sure what's going on.
https://github.com/magento/magento2/pull/7982/commits/11ee118f14f6ebf29a9a436e888b36f9b1d86e3a

The only other core module to include commands like this that I can see is the sample data module, the dependencies for that module don't look remarkably different from the `Magento\Store\Api\StoreRepositoryInterface` dependency I require but clearly I'm missing something.

If anyone can review the integration test failures and point out whats going on i'd be thankful, I cannot replicate the failure locally.

2017-01-07 21:33 UTC, antonkril requested changes

2017-01-07 21:33 UTC, antonkril commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> +class StoreListCommand extends Command
Have you tried to run these commands when magento is not installed? Please check this case.  Requesting StoreManager in constructor might lead to DB calls.

2017-01-09 20:22 UTC, convenient commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> +class StoreListCommand extends Command
@antonkril Damn fine point you make there. The additions I made threw an exception when I ran `bin/magento` without any parameters at all on an uninstalled instance.

I couldn't see any precedence for conditional loading of console classes, so I rolled my own as a proof of concept. Is there a preferred way to handle this kind of thing or is my solution acceptable?

Please review, thank you.

2017-01-16 21:24 UTC, convenient commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> +class StoreListCommand extends Command
@antonkril Any thoughts on the above? :)

2017-01-17 15:34 UTC, buskamuza commented
Hi @convenient ,

there are several ways of registering Magento CLI commands. The one used in Sample Data is to allow the commands appear **before** the application is installed. This is an exceptional case. Usually, commands from the modules register the commands via `di.xml` configuration for `Magento\Framework\Console\CommandListInterface`. You can see an example in Sample Module - https://github.com/magento/magento2-samples/tree/master/sample-module-command or in one of the core commands (e.g., https://github.com/magento/magento2/blob/develop/app/code/Magento/Cron/etc/di.xml#L29-L37). I'd recommend this approach, as it provides the same support as you implemented, just on the framework level.

2017-01-17 15:42 UTC, buskamuza commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> + * @package Magento\Store\Console\Command
Please add more details in the description of the classes. Also, `@package` is not necessary.

2017-01-17 20:26 UTC, convenient commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> + * @package Magento\Store\Console\Command
phpdoc updated in commit a9ca0045d50d5a94e0f83fe7c9ef293e7957438e 

The format for this updated doc is in a format consistent with [app/code/Magento/Cron/Console/Command/CronCommand.php](https://github.com/magento/magento2/blob/develop/app/code/Magento/Cron/Console/Command/CronCommand.php#L21)

2017-01-17 21:15 UTC, convenient commented
Thank you for explaining all that @buskamuza.

I guess my big mistake was using the `SampleData` module as an example of how to add core commands. From what you're saying I picked one of the modules that is purpose built to act differently. For my own learning and out of curiosity are there any other modules like this? I don't think so as I can only find the `SampleData` module having a `cli_commands.php` file.

I've fixed this, tested locally, and have pushed up the changed. Travis is showing all green too. Just waiting on codacy.

Many thanks

2017-02-10 17:32 UTC, buskamuza requested changes
The implementation looks good. But there are couple necessary changes:
1. See new comment in the code
2. Please implement tests

2017-02-10 17:32 UTC, buskamuza commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> +        $table = $this->getHelperSet()->get('table');
Please wrap the logic in `try-catch` and specify return codes for success and failure explicitly. See an example in https://github.com/magento/magento2/blob/develop/app/code/Magento/Deploy/Console/Command/SetModeCommand.php#L108
The same for another test

2017-02-10 17:35 UTC, convenient commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> +        $table = $this->getHelperSet()->get('table');
Will do 👍

2017-02-11 11:35 UTC, convenient commented
@buskamuza @vrann 

I've rebased so just to be clear what i've done
- Added new scripts for listing websites and stores
- Added a tests for each command class
- Each script will return non-zero on error, supporting the verbosity flag.
- Tests passing.

Is that everything you need?

2017-02-15 19:13 UTC, vrann requested changes

2017-02-15 19:13 UTC, vrann commented on app/code/Magento/Store/Console/Command/WebsiteListCommand.php
> +            $output->writeln('<error>' . $e->getMessage() . '</error>');
Similar catch logic is already implemented in the CLI entry point script in bin/magento. I would suggest not to duplicate similar code here. The one difference which I see is that this code will output exception message regardless of verbosity. Can this be done using exact exception types for the cases where you want to output exceptions?

One problem which I see is that the return code is just returned from the execute method. CLI framework will consider that this is valid result of the command and will end process successfully.

2017-02-15 19:13 UTC, vrann commented on app/code/Magento/Store/Console/Command/StoreListCommand.php
> +            $output->writeln('<error>' . $e->getMessage() . '</error>');
same comment about catching logic here

2017-02-15 19:14 UTC, vrann commented
@convenient Than you, I've added 2 comments. Can you please take a look.

2017-02-15 19:16 UTC, vrann commented on app/code/Magento/Store/Console/Command/WebsiteListCommand.php
> +            $output->writeln('<error>' . $e->getMessage() . '</error>');
Oh, just checked comments from previous reviewers. Let me sync up with them.

2017-02-15 19:17 UTC, vrann approved these changes

2017-02-15 19:22 UTC, vrann commented
@convenient nevermind previous comment, all looks good. Apparently this is new convention in CLI framework to require wrapping in try catch for each command.

2017-02-15 20:51 UTC, convenient commented
@vrann Thanks for the updates, you gave me a scare there with so many emails ;)

2017-02-18 03:36 UTC, merged