Type cast
magento/magento2 pull request #8077
Opened 2017-01-09 14:45 UTC by deriknel

Bug Report: https://github.com/magento/magento2/issues/8076

Typecast the `$this->_getAllowedCurrencies()` in the Allow.php and DefaultCurrency.php under Config/Currency to fix this error:

`Something went wrong while saving this configuration: Warning: in_array() expects parameter 2 to be array, string given in /var/www/clean-m2-ee/vendor/magento/module-config/Model/Config/Backend/Currency/DefaultCurrency.php on line 30`

2017-01-09 14:45 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=8077) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=8077) before we can accept your contribution.<br/>

2017-01-10 13:10 UTC, antonkril requested changes
_getAllowedCurrencies() should be fixed instead.

2017-01-10 13:29 UTC, deriknel commented
Thanks @antonkril  for your feedback. I have updated the method as requested.

2017-01-10 13:40 UTC, antonkril approved these changes

2017-01-24 10:10 UTC, antonkril approved these changes

2017-02-13 14:23 UTC, maghamed approved these changes

2017-02-25 01:15 UTC, merged

2017-02-25 01:41 UTC, okorshenko commented
@deriknel thank you for your contribution and bug fix