Throw exception for invalid template in dev mode
magento/magento2 pull request #8119
Opened 2017-01-12 18:30 UTC by convenient

In developer mode php notices/warnings etc are promoted to being exceptions. This means the developer is a bit more diligent with cleaning up any messes as they occur. This does not seem to apply to layout declarations with invalid templates.

I noticed this error on a Magento 1 client which is filled with "Not valid template file", I checked in M2 and this error seems to persist. Developer mode does not promote invalid template errors to being an exception.

This change should make sure developers do not lead any dead templates in their layout.xml. It seems like an easy win to me.

2017-03-01 21:58 UTC, vrann requested changes

2017-03-01 21:58 UTC, vrann commented on lib/internal/Magento/Framework/View/Element/Template.php
> +                throw new \InvalidArgumentException($errorMessage);
Please use ``\Magento\Framework\Exception\ValidatorException`` instead

2017-03-01 22:01 UTC, vrann commented
@convenient Thanks for the contribution, it definitely makes sense to output exception rather way for the developer so there is insensitive to fix it.

Added comment to the code review, please process.

2017-03-02 14:49 UTC, convenient commented
Updates pushed, @vrann Is that alright mate?

2017-03-02 19:56 UTC, vrann approved these changes

2017-03-02 19:57 UTC, vrann commented
@convenient perfect, thanks!

2017-03-02 20:08 UTC, convenient commented
Awesome thanks @vrann. 

I wonder how much screaming there is going to be
>Boo the latest magento version breaks when using developer mode what happened?

![The greater good!](http://i.imgur.com/oFeYNpD.gif)

2017-03-02 20:42 UTC, vrann commented
@convenient wait, what was the intent of PR? Checking ``\Magento\Framework\View\Element\Template\File\Validator::isValid`` method, it will check only for template being in the right location. Have you meant to throw the exception in case if a template has syntax errors?


```
public function isValid($filename)
    {
        $filename = str_replace('\\', '/', $filename);
        if (!isset($this->_templatesValidationResults[$filename])) {
            $this->_templatesValidationResults[$filename] =
                ($this->isPathInDirectories($filename, $this->_compiledDir)
                    || $this->isPathInDirectories($filename, $this->moduleDirs)
                    || $this->isPathInDirectories($filename, $this->_themesDir)
                    || $this->_isAllowSymlinks)
                && $this->getRootDirectory()->isFile($this->getRootDirectory()->getRelativePath($filename));
        }
        return $this->_templatesValidationResults[$filename];
    }
```

2017-03-02 20:44 UTC, vrann commented
@convenient or is that exactly what happens when you leave the dead template in the layout? Yeah, then we might hear boos :) (in developer mode only)

2017-03-02 20:59 UTC, convenient commented
I meant the latter. I'm wondering how many dead templates exist in m2 websites today, quietly logging away never being cleaned up. 

We'll find out when this is released and the developers start to complain I guess.

2017-03-11 00:25 UTC, merged

2017-03-11 00:28 UTC, okorshenko commented
@convenient thank you for your contribution