Update Options.php
magento/magento2 pull request #8130
Opened 2017-01-13 13:25 UTC by redelschaap

Prevent special charachters (like ü or ß) from being inserted as HTML encoded entities (like &uuml; or &szlig;) in widget input fields.

2017-03-01 21:27 UTC, vrann requested changes
Can you accompany pull request with the unit tests, please?

2017-03-01 21:27 UTC, vrann commented on app/code/Magento/Widget/Block/Adminhtml/Widget/Options.php
> +        $data['value'] = html_entity_decode( $data['value'] );
- Please use \Magento\Framework\Escaper::escapeHtmlAttr instead of native PHP library
- there is extra space after "(", please remove

2017-03-01 21:28 UTC, vrann commented
@redelschaap Thank you for the contribution! Left couple comments in the code review.

2017-03-07 09:26 UTC, redelschaap commented on app/code/Magento/Widget/Block/Adminhtml/Widget/Options.php
> +        $data['value'] = html_entity_decode( $data['value'] );
The `\Magento\Framework\Escaper::escapeHtmlAttr` function doesn't give the desired result. `html_entity_decode` is used by Magento core elsewhere. See https://github.com/magento/magento2/search?utf8=✓&q=html_entity_decode&type=Code. I have removed the extra spaces.

2017-03-13 14:49 UTC, vrann commented on app/code/Magento/Widget/Block/Adminhtml/Widget/Options.php
> +        $data['value'] = html_entity_decode( $data['value'] );
Thank you, looks good

2017-03-13 14:49 UTC, vrann approved these changes

2017-03-14 05:10 UTC, merged

2017-03-14 15:58 UTC, vrann commented
@redelschaap merged! Appreciate your support.

2017-03-16 20:09 UTC, redelschaap commented
Great! Thanks!

2017-05-17 07:42 UTC, sereban commented
@vrann @redelschaap 
Why you assume that the data['value'] always will be a string?
What will happens in case of multiselect?

2017-05-17 07:47 UTC, redelschaap commented
Than that value is serialized, so it will be a string on that point. Right @vrann?