Update DataProvider.php
magento/magento2 pull request #8217
Opened 2017-01-20 14:35 UTC by redelschaap

Some template files from extensions cause the js-translation.json file to contain an empty array. The try-catch block prevents this and will just exclude that specific file from the loaded language strings, since it's almost impossible to debug which file is causing this.

2017-02-03 17:00 UTC, vrann requested changes
Can you please log the Exception, so that the issue with the improper template will be flagged to the developer

2017-02-03 17:01 UTC, vrann commented
@redelschaap Thanks for contribution, please see comment above

2017-02-06 11:33 UTC, redelschaap commented
I've made some changes.

2017-02-06 21:20 UTC, vrann commented on app/code/Magento/Translation/Model/Js/DataProvider.php
> +                    throw new \Exception(sprintf('Error while translating phrase "%s" in file %s.',
Please use \Magento\Framework\LocalizedException (or create subclass of it)

2017-02-06 21:22 UTC, vrann commented
@redelschaap Thanks! Added one more comment. And please fix static test failed in Travis.

2017-02-07 09:12 UTC, redelschaap commented
I updated the code. I cannot fix the issue in Travis since those issues are out of the scope of my adjustments.

2017-02-07 22:06 UTC, vrann approved these changes

2017-02-07 22:08 UTC, vrann commented
@redelschaap changes look good.
This static test failure indicates wrong formatting in the catch clause:
```
FILE: ...magento/magento2/app/code/Magento/Translation/Model/Js/DataProvider.php
--------------------------------------------------------------------------------
FOUND 3 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
 114 | ERROR | Opening parenthesis of a multi-line function call must be the
     |       | last content on the line
 115 | ERROR | Only one argument is allowed per line in a multi-line function
     |       | call
 115 | ERROR | Closing parenthesis of a multi-line function call must be on a
     |       | line by itself
--------------------------------------------------------------------------------
```
Can you please fix those?

2017-02-08 13:41 UTC, redelschaap commented
Made the adjustments, Travis still failed but that is out of my scope:

```
1) Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/home/travis/build/magento/magento2/app/code/Magento/Translation/Model/Js/DataProvider.php:14	The class DataProvider has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.
```

2017-02-08 17:38 UTC, vrann commented
@redelschaap thanks, that was everything needed

2017-02-11 15:50 UTC, merged

2017-02-12 04:11 UTC, okorshenko commented
@redelschaap thank you for your contribution to Magento 2 project. Your PR is successfully merged to develop branch