Fix product option files not copying to order dir.
magento/magento2 pull request #8462
Opened 2017-02-08 08:46 UTC by evktalo

Copy product option file to order directory from quote also when media storage is set to file system, not just database.

Also rename _rootDirectory variable to _mediaDirectory, since that's what it is.

2017-02-26 20:52 UTC, okorshenko requested changes

2017-02-26 20:52 UTC, okorshenko commented on app/code/Magento/Catalog/Model/Product/Option/Type/File.php
> +    public function setCustomOp
this code looks broken. @evktalo could you please review this code and fix it, so that i can proceed with acceptance of this PR. Thank you

2017-03-15 21:17 UTC, okorshenko commented
Hi @evktalo could you please fix unit tests so that we can process this PR?

2017-03-31 09:19 UTC, evktalo commented
Yes, I will work on fixing the tests. Thank you!

2017-04-02 18:07 UTC, okorshenko commented
@evktalo I will the the tests on our side and will proceed with PR acceptance. Thank you!

2017-04-13 04:20 UTC, merged

2017-04-13 04:24 UTC, magento-team commented
@evktalo thank you for your contribution