Fix for https://github.com/magento/magento2/issues/8287
magento/magento2 pull request #8474
Opened 2017-02-08 18:59 UTC by ericrisler

Added missing __() wrap on execption. Without it a new exception is thrown: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\Exception\InputException::__construct() must be an instance of Magento\Framework\Phrase, string given

Fix for https://github.com/magento/magento2/issues/8287

2017-02-08 18:59 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=8474) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=8474) before we can accept your contribution.<br/>

2017-02-08 22:02 UTC, okorshenko requested changes
@ericrisler thank you for your contribution. Your PR fixes the issue but I'd recommend alternative solution.

The issue itself goes from https://github.com/magento/magento2/blob/develop/app/code/Magento/Quote/Model/Quote/Validator/MinimumOrderAmount/ValidationMessage.php#L46

If error message is configured the method returns it as is. I would recommend return Phrase object from the method \Magento\Quote\Model\Quote\Validator\MinimumOrderAmount\ValidationMessage::getMessage() in all cases. In this way, we don't need to wrap method result second time. Plus, the method itself will have strict return type which is better from code design perspective. 

СС: @sidolov

2017-02-10 23:48 UTC, okorshenko approved these changes

2017-02-11 15:50 UTC, merged

2017-02-12 04:15 UTC, okorshenko commented
@ericrisler thank you for your contribution. We merged your PR with some adjustments

2017-05-07 11:06 UTC, warperharper commented
This doesn't resolve the issue for me. Add one item to cart OK. Second item fails if value is below minimum amount. If value over minimum amount is added to cart, you can add more items, but you cannot delete items if removing them brings the value below minimum. 2.1.6

2017-05-10 13:06 UTC, mzenner1 commented
I'm having the same issue as @warperharper.  I can add one item just fine.  After that, I can't add anything else to my cart or even remove the existing item.  My minimum order amount is $60.  I added something to my cart that was $2.50.  Magento 2.1.6.

Please fix this guys.  My client needs the minimum order amount

2017-05-22 20:14 UTC, ifeltsweet commented
Still broken on 2.1.6. The change doesn't seem to be merged into the code.

2017-08-29 17:28 UTC, ifeltsweet commented
Still broken in 2.1.8... O_O

2017-08-29 19:08 UTC, okorshenko commented
Fix will be available in 2.2

2017-10-13 19:55 UTC, Ctucker9233 commented
@okorshenko Any plans to backport seeing as how this was an issue with 2.1?