Make "is_required" and "is_visible" properties of telephone, company and fax attributes of addresses configurable
magento/magento2 pull request #8519
Opened 2017-02-11 16:42 UTC by avstudnitz

Fixes #1691.
We added configuration for telephone, fax and company fields in configuration:
![grafik](https://cloud.githubusercontent.com/assets/662059/22855420/a57cb556-f080-11e6-8f1b-770695ee88ba.png)
You can set them to be optional, required, or not shown at all. All necessary forms have been adjusted.

2017-02-11 16:42 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=8519) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=8519) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: avstudnitz<br/>:x: pixelhed

2017-02-11 18:04 UTC, Igloczek requested changes

2017-02-11 18:04 UTC, Igloczek commented on app/code/Magento/Customer/view/frontend/templates/widget/company.phtml
> +</div>
Will be nice to improve formatting in templates 😉  Copy-paste code bellow.

```phtml
<div class="field company <?php echo $block->isRequired() ? 'required' : '' ?>">
    <label for="company" class="label">
        <span>
            <?php echo $block->escapeHtml(__('Company')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('company')
            );
        ?>
        <input type="text"
               name="company"
               id="company"
               value="<?php echo $block->escapeHtmlAttr($block->getCompany()) ?>"
               title="<?php echo $block->escapeHtmlAttr(__('Company')) ?>"
               class="input-text <?php echo $_validationClass ?? '' ?>"
         >
    </div>
</div>
```
PS. Remember about new line at the end of file.

2017-02-11 18:04 UTC, Igloczek commented on app/code/Magento/Customer/view/frontend/templates/widget/fax.phtml
> +</div>
```phtml
<div class="field fax <?php echo $block->isRequired() ? 'required' : '' ?>">
    <label for="fax" class="label">
        <span>
            <?php echo $block->escapeHtml(__('Fax')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('fax')
            );
        ?>
        <input type="text"
               name="fax"
               id="fax"
               value="<?php echo $block->escapeHtmlAttr($block->getFax()) ?>"
               title="<?php echo $block->escapeHtmlAttr(__('Fax')) ?>"
               class="input-text <?php echo $_validationClass ?? '' ?>"
        >
    </div>
</div>
```

2017-02-11 18:04 UTC, Igloczek commented on app/code/Magento/Customer/view/frontend/templates/widget/telephone.phtml
> +</div>
```phtml
<div class="field telephone <?php echo $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?php echo $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('fax')
            );
        ?>
        <input type="text"
               name="telephone"
               id="telephone"
               value="<?php echo $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?php echo $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?php echo $_validationClass ?? '' ?>"
        >
    </div>
</div>
```

2017-02-11 18:38 UTC, hostep commented
Nice work @avstudnitz!

Just something I have to think about, take a look at this code:
https://github.com/magento/magento2/blob/7c81c1dbeaea2cb7c3aed644580f48bbbdb226e9/app/code/Magento/Checkout/Block/Checkout/LayoutProcessor.php#L323-L339
I think you'll need to figure something out, to add the `required-entry` validation of those 3 billing address fields in there, based on the chosen configuration?

(not 100% sure about this though)

2017-02-11 19:13 UTC, avstudnitz commented
@hostep In our tests it set the correct validation on the checkout without modifying anything, based on the attribute settings. so I think this is not necessary.

2017-02-11 22:22 UTC, fooman commented
Nice work - I believe if you want to increase your chances of a quick merge I suggest taking a look at making the constructor changes here https://github.com/magento/magento2/pull/8519/files#diff-abecee6a6fc7dfb7ec46099d0ffec980R55 use an optional parameter similar to how @dmanners has been doing here https://github.com/magento/magento2/pull/8481/files#diff-ab7a66b8a18582a01b9661fe9270486aR51

2017-02-23 04:12 UTC, vrann commented
@avstudnitz Thank you for the contribution! I'm verifying it at the moment.
Can you please take a look at the failing Travis tests?

2017-02-23 04:21 UTC, vrann commented on app/code/Magento/Customer/Model/Address/AbstractAddress.php
> + * @method string getFax()
nice!

2017-02-23 06:48 UTC, avstudnitz commented
@vrann Yes, will do that over the weekend. It's the unit tests, right?

2017-02-23 13:01 UTC, vrann commented
@avstudnitz actually nevermind issues in the unit tests (Travis), it was fast fix and I just did it.
Verifying the functionality and will let you know is there anything need to be changed.

2017-02-23 13:37 UTC, vrann commented
@avstudnitz from the review perspective all the changes looks good and the functionality works perfectly.

2017-02-23 13:39 UTC, avstudnitz commented
Great to hear @vrann!

2017-02-25 01:15 UTC, merged

2017-02-25 01:30 UTC, okorshenko commented
@avstudnitz thank you for your contribution. PR is merged