Replace Zend_Mail (ZF1) with Zend\Mail (ZF2)
magento/magento2 pull request #8608
Opened 2017-02-19 23:19 UTC by schmengler

This PR probably needs more work, at least more testing, I cannot believe that it is so easy.

Opening for review and acceptance tests. If it's working I plan to refactor the code a bit (see TODO comments) - feedback appreciated!

2017-02-21 17:22 UTC, orlangur commented
> needs more work, at least more testing, I cannot believe that it is so easy

True, true... One integration test is failing, another one caused fatal error :) Check [Travis CI](https://travis-ci.org/magento/magento2/builds/203273924).

Note that refactoring should be performed in such a way that all existing customizations relying on `Magento_Framework` and not `Zend_Mail` directly work as before (just like integration tests, people will not be happy getting such errors after upgrade).

Will share my thoughts on the code a bit later.

2017-02-21 17:56 UTC, schmengler commented
> True, true... One integration test is failing, another one caused fatal error :) Check Travis CI.

I've seen it, but could not look into the details yet. I tried to take care not to change the `Magento_Framework` behavior, and it's possible that tests are only failing because mocks have to be changed.

I'm waiting for your feedback on the code now!

2017-02-22 07:09 UTC, orlangur requested changes

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Message.php
> + * @todo composition instead of inheritance for better testability
Do it now and expose only necessary public methods.

Otherwise people may rely on Zend implementation rather then on narrowed interface and we will continue to have problems like Fatal Error with absent  `getBodyHtml`.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Message.php
> +        $this->encoding = $charset;
Rename constructor argument accordingly and use `setEncoding` method of `\Zend\Mail\Message` instead (currently `$this->getHeaders()->setEncoding($encoding);` is missed).

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Message.php
> +    public function setMessageType($type)
Please preserve order of methods to simplify checking of correspondence during review (getBody -> getBody, setBody -> setBody etc).

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Message.php
> +            $body = self::htmlMimeFromString($body);
Method name must begin with verb, I suggest `createHtmlMimeFromString`.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Message.php
> -        return $this->messageType == self::TYPE_TEXT ? $this->getBodyText() : $this->getBodyHtml();
Calls of `getBodyHtml` must be fixed all over the code, this is why we saw Fatal Error on Travis. Integration tests do not use mocks usually.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Test/Unit/MessageTest.php
> +        $this->markTestSkipped('obsolete ZF 1 test');
Test must be reworked within this pull request.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Test/Unit/Template/TransportBuilderTest.php
> +        $this->messageMock->method('getHeaders')->willReturn(new Headers());
`Headers` class must be mocked as well.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Test/Unit/TransportTest.php
> +            new \Magento\Framework\Mail\Message()
`Message` class must be mocked here.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Transport.php
> +
Useless new line and `phpcs` does not enforce it yet.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Transport.php
> +class Transport extends \Zend\Mail\Transport\Sendmail implements \Magento\Framework\Mail\TransportInterface
Do aggregation instead of inheritance.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Transport.php
> +        if (!$message instanceof \Zend\Mail\Message) {
I don't think we should keep classes inherited from `Zend` classes in the system.

Just create necessary instance of `\Zend\Mail\Message` in `sendMessage` method instead.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Message.php
> + * - add a ZendMailDecorator interface with getZendMail() method for usage in \Magento\Framework\Mail\Transport
Please no. To me it looks like `\Zend\Mail\Message` has all necessary setters already.

2017-02-22 07:09 UTC, orlangur commented on lib/internal/Magento/Framework/Mail/Message.php
> + * - deprecate setMessageType(), implement a HtmlMessage decorator instead
I don't think such decorator would be really valuable. Do we have some needed cases not covered with current text/html types implementation?

2017-02-22 07:12 UTC, orlangur commented
@schmengler, thanks for your efforts, implementation in general looks quite clean and minimalistic (just does what is really necessary).

Please make sure all builds are green before next review iteration.

2017-03-16 02:52 UTC, okorshenko commented
Hi @schmengler 
Are you going to proceed this with PR?

2017-03-16 16:19 UTC, schmengler commented
@okorshenko yes as soon as I find some time for it

2017-03-17 14:45 UTC, okorshenko commented
@schmengler thank you. Please let us know when you  will be ready. Thank you

2017-03-18 20:45 UTC, schmengler commented on lib/internal/Magento/Framework/Mail/Message.php
> -        return $this->messageType == self::TYPE_TEXT ? $this->getBodyText() : $this->getBodyHtml();
Fortunately `getBodyHtml` is only used in integration tests. I'm trying to fix them

2017-03-18 22:46 UTC, schmengler commented on lib/internal/Magento/Framework/Mail/Message.php
> + * - deprecate setMessageType(), implement a HtmlMessage decorator instead
The problem with the current implementation is that you have to call `setMessageType()` before `setBody()`. I'm now considering changing the `MessageInterface` interface. As it should be used via `TransportBuilder`, it should not have serious impact.

- The current signatures `setBody(mixed $body)` and `mixed getBody()` are not meaningful. Either "mixed" must be replaced with "string" or we are leaking the zend abstraction.
- The interface does not allow multitype mails (this is the needed case not covered. Something that Magento always has been lacking of)

One idea is, replacing `setMessageType()`, `setBody()` and `getBody()` with:

- `setBodyHtml(string $html)`
- `setBodyText(string $text)`
- `string getBodyText()`
- `string getBodyHtml()`

This allows text mails, HTML mails, and multitype mails, does not require calling them in any specific order and does not reveal anything of the underlying Zend mail component.

2017-03-18 22:58 UTC, schmengler commented on lib/internal/Magento/Framework/Mail/Message.php
> + * - deprecate setMessageType(), implement a HtmlMessage decorator instead
Another advantage is that this resembles the old zf1 implementation, so 3rd party code is actually less likely to break even though we have to change an `@api` interface

2017-03-18 23:59 UTC, schmengler commented
Because it's hidden now in the "outdated" review, here again my concerns about the message interface:

The problem with the current implementation is that you have to call `setMessageType()` before `setBody()`. I'm now considering changing the `MessageInterface` interface. As it should be used via `TransportBuilder`, it should not have serious impact.

- The current signatures `setBody(mixed $body)` and `mixed getBody()` are not meaningful. Either "mixed" must be replaced with "string" or we are leaking the zend abstraction.
- The interface does not allow multitype mails (this is the needed case not covered. Something that Magento always has been lacking of)

One idea is, replacing `setMessageType()`, `setBody()` and `getBody()` with:

- `setBodyHtml(string $html)`
- `setBodyText(string $text)`
- `string getBodyText()`
- `string getBodyHtml()`

This allows text mails, HTML mails, and multitype mails, does not require calling them in any specific order and does not reveal anything of the underlying Zend mail component.

Another advantage is that this resembles the old zf1 implementation, so 3rd party code is actually less likely to break even though we have to change an `@api` interface

I already added one method `getRawMessage()` because otherwise it would not be possible to have a Zend transport implementation by only using the message interface and not the underlying Zend message, so the PR will cause a BC break anyways. But IMHO it's a minor one and it is necessary to get the mail interfaces right.

2017-03-19 00:13 UTC, schmengler commented
And while we are at it, shouldn't `TransportInterface` look like this:

```
    function sendMessage(MessageInterface $message);
```

instead of 

```
    function sendMessage()
```

?

I don't understand, why the "Transport" implementation receives the message in the constructor.

And thus we have the `TransportBuilder` class, which actually builds a message.

2017-03-19 00:38 UTC, schmengler commented on lib/internal/Magento/Framework/Mail/Test/Unit/TransportTest.php
> +            new \Magento\Framework\Mail\Message()
I disagree. It's part of the same component and not using external resources. To test handling of an incomplete message, we create a real message without "to" header. A stub just complicates things and a mock will make unnecessary assumptions about the implementation details.

2017-07-10 22:38 UTC, okorshenko commented
Hi @schmengler 
Just FYI: we stabilized this branch and working on the testing of new changes.

2017-07-12 16:50 UTC, merged

2018-12-19 12:54 UTC, 0m3r commented
What about getHeaders and setHeaders for \Magento\Mail\Message? 

I want to set headers like a in-reply-to, message-id, references etc.

2019-03-30 18:06 UTC, klein0r commented
Is there a reason why this has been included into 2.2.8?

2019-04-01 23:41 UTC, orlangur commented
@klein0r yep, backward compatibility is the reason.