Remove Zend_Json from the unit test in the CustomerImportExport module
magento/magento2 pull request #8706
Opened 2017-02-28 09:25 UTC by dmanners

Since Zend Framework1 is EOF then we should start to move away from it.

This PR removes the usage of Zend_Json in the CustomerImportExport module.

2017-02-28 09:47 UTC, orlangur requested changes
Cool! 👍 

But, it can be removed from all tests at once, I observe 38 occurrences of `Zend_Json` in `*Test.php`.

Just to decrease the overhead of multiple pull requests processing ;)

2017-02-28 09:51 UTC, dmanners commented
Hi @orlangur I have been working through module by module simply so that I can encapsulate the changes. I dont just want to do a find an replace on the full code base and then try to fix all the problems. For me smaller changes like this is actually how you get a monolith moving in the right direction.

2017-02-28 10:01 UTC, orlangur commented
@dmanners, ok, you can go your way, no offense.

> just want to do a find an replace on the full code base and then try to fix all the problems

That's exactly how I like to do it :) Most likely there would be no problem with tests, otherwise some of them could be left untouched (like this: https://github.com/orlangur/magento2/commit/77a6b51dd619786911d2cce564f0399367f2f301). Fix as much problems as possible all over the code + leave some tricky cases for further atomic implementation. The thing which would make me sad is fixing tests manually which can be done automatically and only once.

2017-02-28 10:01 UTC, orlangur approved these changes

2017-02-28 10:07 UTC, dmanners commented
@orlangur dont worry no offence taken. I just started this by stripping out Zend_Json overall places and then had to scale it back step by step. These things take time.

2017-03-01 19:31 UTC, vrann approved these changes

2017-03-08 13:30 UTC, merged

2017-03-08 13:47 UTC, ishakhsuvarov commented
@dmanners We have now merged your PR to the `develop` branch. Thank you for your contribution!