Remove zend json from email
magento/magento2 pull request #8707
Opened 2017-02-28 09:52 UTC by dmanners

Since Zend Framework1 is EOF then we should start to move away from it.

This PR removes the usage of Zend_Json in the Email module.

2017-02-28 09:54 UTC, orlangur requested changes
Typo "serilizer", besides that LGTM 👍

2017-03-01 15:39 UTC, maghamed approved these changes

2017-03-01 15:39 UTC, maghamed commented on app/code/Magento/Email/Test/Unit/Model/TemplateTest.php
> +    private $serilizerMock;
@dmanners  could you please fix this type

2017-03-03 14:17 UTC, orlangur approved these changes

2017-03-09 04:26 UTC, vrann commented
@dmanners Thank you for the contribution!

2017-03-10 23:21 UTC, closed without merging

2017-03-11 00:41 UTC, Ctucker9233 commented
@okorshenko Why Closed and not Merged?

2017-03-11 09:53 UTC, orlangur commented
@Ctucker9233 nice catch, there is typo in mainline currently due to not merged last commit of this PR: https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Test/Unit/Model/TemplateTest.php#L90

For PRs which did not become Merged automatically would be nice to have an automated check that all changes came to mainline (so that PR can be safely closed when we have all changes but some commit hashes are different).

2017-03-11 21:50 UTC, Ctucker9233 commented
@orlangur Agreed. I just thought I'd ask because all previous comments and updates made it look like it was good to go and then it's suddenly closed with no explanation.

2017-03-14 23:22 UTC, okorshenko commented
@Ctucker9233  this PR is shown closed on GitHub but not merged, because the contributor did rebase of the branch and commit hashes changed. If we missed some commits from this PR, please, create additional PR to resolve the issue. Thank you

2017-03-15 07:02 UTC, orlangur commented
@okorshenko in fact, not :) This was the case in another PR but not here.

In https://github.com/magento/magento2/commits/develop/app/code/Magento/Email/Test/Unit/Model/TemplateTest.php we can see https://github.com/magento/magento2/commit/ce261ee0f554306528cd4763902c5c89710f70c3 has the same hash as in this PR.

> For PRs which did not become Merged automatically would be nice to have an automated check that all changes came to mainline (so that PR can be safely closed when we have all changes but some commit hashes are different).

This could sound as an overkill, simpler check could be - check if first commit from PR has the same hash in mainline. If not - rebase occured, if yes - need to check if all commits were added to mainline.

Additional PR created.