Improvement: Added Finally Block to Error Handling
magento/magento2 pull request #8716
Opened 2017-02-28 15:09 UTC by DavidLambauer

The Error Handling is related to the Try/Catch Block above. Due to the finally block, it is more clear that the error handling belongs to the Try/Catch statement. 

This Commit is just an improvement and doesn't change the behavior of the method.

2017-02-28 15:31 UTC, orlangur requested changes
This will not work under HHVM: https://github.com/facebook/hhvm/issues/5162

See http://devdocs.magento.com/guides/v2.1/architecture/tech-stack.html
> Magento is compatible with but not supported for:
> HHVM 3.9 PHP interpreter

2017-03-01 15:55 UTC, maghamed requested changes

2017-03-01 15:55 UTC, maghamed commented on app/code/Magento/Store/Controller/Store/SwitchAction.php
> +                return;
not supported by HHVM https://3v4l.org/LZ0Mq
that's why it's implemented as a flag in Magento codebase

2017-03-01 15:56 UTC, maghamed commented
agreed with @orlangur , current implementation is more reliable taking HHVM support into account

2017-03-01 15:57 UTC, closed without merging