Fix method named class being interpreted as a class
magento/magento2 pull request #8782
Opened 2017-03-03 13:09 UTC by AydinHassan

`PhpScanner` incorrectly interprets a method named `class` (valid PHP) as an actual class.

2017-03-03 13:09 UTC, AydinHassan commented on setup/src/Magento/Setup/Module/Di/Code/Scanner/PhpScanner.php
> +                && $tokens[$tokenIterator - 1][0] != T_DOUBLE_COLON && $tokens[$tokenIterator - 2][0] != T_FUNCTION
`- 2` as the immediate previous token is whitespace.

2017-03-03 14:31 UTC, AydinHassan commented
Ah I forgot Magento still runs on PHP 5. Should I just skip the unit test on anything less that 7?

2017-03-03 16:18 UTC, AydinHassan commented
Hmm - looks like a few other things can't deal with a method named `class` either. I will take a closer look when I get some more time.

2017-03-24 12:38 UTC, kschroeder commented on setup/src/Magento/Setup/Test/Unit/Module/Di/Code/Reader/ClassesScannerTest.php
> +        $this->assertCount(6, $actual);
I ran into this same issue (also because of the ::class thing) on #8965.  If it *is* the same thing then this test should remain with a count of 5.

2017-05-16 17:37 UTC, orlangur requested changes

2017-05-16 17:37 UTC, orlangur commented on setup/src/Magento/Setup/Test/Unit/Module/Di/Code/Scanner/PhpScannerTest.php
> +        if (version_compare(PHP_VERSION, '7.0.0', '<')) {
PHP < 7 is not supported anymore, just sync with `develop` branch.

2017-06-08 10:10 UTC, ishakhsuvarov commented
@AydinHassan Please sync with the latest `develop` and check the review comments if you wish to continue work on this Pull Request.
Thanks.

2017-06-08 10:15 UTC, AydinHassan commented
Hi @ishakhsuvarov i'm not interested in working on this anymore, so it can just be closed.

2017-06-08 10:16 UTC, ishakhsuvarov commented
@AydinHassan Closing per your comment.
Thank you for collaboration.

2017-06-08 10:16 UTC, closed without merging