Update AbstractModel.php
magento/magento2 pull request #8796
Opened 2017-03-06 06:57 UTC by redelschaap

PHP's function `in_array` returns `TRUE` when evaluating a needle `0` against a list of strings, which is a known issue. In my case I got an exception because a small integer was used to construct a new `DateTime` object. Calling the function in strict mode fixes this. See also http://stackoverflow.com/questions/13846769/php-in-array-0-value.

2017-03-22 17:09 UTC, maghamed approved these changes

2017-03-22 21:33 UTC, maghamed commented
@redelschaap  could you please make a pull request into develop branch , because for a while we don't process PRs into other branches

2017-03-22 21:34 UTC, maghamed requested changes
please make Pull Request into Develop branch

2017-03-23 13:35 UTC, redelschaap commented
I've created a new PR to the develop branch. See #8991.

2017-03-23 13:36 UTC, closed without merging