imagento/magento2#8515: Downloadable product is available for downloa…
magento/magento2 pull request #8917
Opened 2017-03-16 17:17 UTC by nazarpadalka

- Set expired status of downloaded product during change order status to canceled.

### Description
Resolve issue with possibility to download downloadable product after order was canceled

### Fixed Issues (if relevant)
https://github.com/magento/magento2/issues/8515
1. magento/magetno2#8515: Downloadable product is available for download even if order state is set canceled.

### Manual testing scenarios
1. Create an order for a downloadable product.
2. Set order state to STATE_CANCELED programatically.
3. Goto customer account dashboard, it list the order as 'canceled'.
4. Now goto "My Downloadable Products" and check if possible to download downloadable product

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-03-16 17:17 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=8917) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=8917) before we can accept your contribution.<br/><hr/>**Nazar Padalka** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-03-16 17:18 UTC, nazarpadalka commented
We will provide test for covering this case

2017-03-16 22:38 UTC, ishakhsuvarov commented
Hi @nazarpadalka 
We kindly ask you to sign our Contributor License Agreement (CLA) before we can proceed with accepting your contribution. To sign successfully please make sure, that email in the commit is present in your github account.

Thank you

2017-03-17 14:04 UTC, pangteypiyush commented
Thanks !!

2017-03-20 14:36 UTC, ishakhsuvarov commented
Hi @nazarpadalka 
> We will provide test for covering this case

Are you still working on it?

2017-03-20 14:52 UTC, nazarpadalka commented
@ishakhsuvarov 
my coworker still working on this, we will make new PR for tests separately

2017-03-20 16:58 UTC, ishakhsuvarov commented
@nazarpadalka It is the best practice to deliver tests simultaneously.
Just let us know when you are done.

Thank you

2017-03-21 00:10 UTC, KravetsAndriy commented
@ishakhsuvarov Hello. Sorry for long response, currently I have a trip.
So, integration test is ready (https://github.com/KravetsAndriy/magento2/commit/18f92cc11ca465d49489253c15ce7ccc710fd1b7), but unfortunately we forgot to fix permissions to allow me to commit in Nazar's develop branch. Tomorrow we will sort out this and I guess, that we can process this PR. Cheers

2017-03-21 08:04 UTC, nazarpadalka commented
@ishakhsuvarov we already added tests to PR, please let us know if need some else.
Thanx

2017-03-21 08:17 UTC, KravetsAndriy commented
@ishakhsuvarov Want to confirm, that old branch version did not pass that test. 
Also I have suggestion to refactor that observer to reach possibility to write uni-tests. But seems like Magento 2 has more prioritised issues.

2017-03-21 09:17 UTC, ishakhsuvarov requested changes

2017-03-21 09:17 UTC, ishakhsuvarov commented on dev/tests/integration/testsuite/Magento/Downloadable/Model/Observer/SetLinkStatusObserverTest.php
> +        if ($orderItems = $order->getAllItems()) {
Looks like assertions will be unreachable in case if order would not have items, therefore making the test green false-positively.

2017-03-21 09:17 UTC, ishakhsuvarov commented on dev/tests/integration/testsuite/Magento/Downloadable/Model/Observer/SetLinkStatusObserverTest.php
> +    protected function prepareOrder()
Why didn't you just use the `order_with_downloadable_product` fixture which is pretty similar?

2017-03-21 09:18 UTC, ishakhsuvarov commented
@KravetsAndriy Thank you very much!
Looks pretty good, however I have added a few comments, please check them.

2017-03-21 09:24 UTC, KravetsAndriy commented on dev/tests/integration/testsuite/Magento/Downloadable/Model/Observer/SetLinkStatusObserverTest.php
> +    protected function prepareOrder()
@ishakhsuvarov It has some difference between this and order_with_downloadable_product fixture. For some reason (probably its an isolation) my test was not able to retrieve order links with specific ID I setup.

2017-03-21 10:27 UTC, ishakhsuvarov commented
@KravetsAndriy Please look into the static test failure on Travis CI

2017-03-21 11:58 UTC, KravetsAndriy commented
@ishakhsuvarov will fix this in the evening. Thanks

2017-03-21 23:22 UTC, KravetsAndriy commented
- Added fixture and rollback for it to represent order downloadable product which has available link and related product option.
- Removed over-dependency from _SetLinkStatusObserverTest_ method.
- Fixed change request.

2017-03-22 07:42 UTC, ishakhsuvarov commented
@KravetsAndriy Thank you for the fixes.

2017-03-22 07:42 UTC, ishakhsuvarov approved these changes

2017-03-22 07:49 UTC, KravetsAndriy commented
@ishakhsuvarov , thank you too! This one took some extra time, since it was first contribute. Now we look for new issues to take and I think, that we will decrease time, spent on formal stuff like we did.

2017-03-23 22:25 UTC, merged

2017-03-24 08:00 UTC, ishakhsuvarov commented
@nazarpadalka @KravetsAndriy PR is merged into the `develop` branch.
Thank you for collaboration.

2017-03-24 08:04 UTC, KravetsAndriy commented
@ishakhsuvarov Thanks you too!

2017-03-24 10:09 UTC, nazarpadalka commented
@ishakhsuvarov Thanx you