Reduced the use of ObjectManager
magento/magento2 pull request #8951
Opened 2017-03-20 21:39 UTC by Hansschouten

### Description
This pull request replaces a number of calls to the ObjectManager by constructor dependency injection.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-03-20 23:07 UTC, maghamed requested changes

2017-03-20 23:07 UTC, maghamed commented on app/code/Magento/Sales/Model/AdminOrder/Create.php
> +    protected $localeFormat;
all new properties added should be private.
Inheritance based APIs are highly discouraged

2017-03-20 23:07 UTC, maghamed commented on app/code/Magento/Theme/Model/View/Design.php
> +    protected $localeResolver;
same as above, use private

2017-03-21 16:41 UTC, ishakhsuvarov commented
@Hansschouten Please check the unit test failures on Travis CI.
Thanks!

2017-06-15 11:36 UTC, ishakhsuvarov commented
@Hansschouten Closing this PR because of inactivity.
Please reopen and sync with the latest `develop` branch if you would like to continue.
Thanks!

2017-06-15 11:36 UTC, closed without merging