Remove context aggregation validation (see Issue #6114)
magento/magento2 pull request #8955
Opened 2017-03-21 09:58 UTC by Vinai

Remove the context aggregation validation step as it enforces increased coupling between a child class and the parent class dependencies.

### Description
Please see issue #6114 for a complete description of the issue.

### Fixed Issues (if relevant)
1. magento/magetno2#6114: Compilation enforces coupling to parent class Context contents

### Manual testing scenarios
1. See the "Steps to reproduce" description in Issue #6114 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-03-24 16:00 UTC, maghamed requested changes
left a comment into the initial GitHub issue  - https://github.com/magento/magento2/issues/6114#issuecomment-289064461

2017-04-21 15:28 UTC, maghamed commented
Hi @Vinai  sorry for delay. 
I was in a rush with Imagine preparation and mine PTO after it. 
Do you have a time to get back to this PR?

2017-04-23 18:00 UTC, Vinai commented
Rebased and all checks passed.

2017-04-24 07:55 UTC, maghamed approved these changes

2017-04-30 14:40 UTC, merged

2017-04-30 14:50 UTC, magento-team commented
@Vinai thank you for your contribution. Your Pull Request has been successfully merged