Remove superfluous realpath call
magento/magento2 pull request #9025
Opened 2017-03-27 12:01 UTC by tkn98

Calling realpath is not necessary for __DIR__

Refs:

- http://php.net/manual/language.constants.predefined.php

(Previously reported against wrong base branch in #5518)

2017-03-27 12:01 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9025) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9025) before we can accept your contribution.<br/><hr/>**Tom Klingenberg** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-03-27 12:13 UTC, okorshenko requested changes

2017-03-27 12:13 UTC, okorshenko commented on pub/index.php
> -    require realpath(__DIR__) . '/../app/bootstrap.php';
It make sense to change the code in the following way:
`realpath(__DIR__ . '/../app/bootstrap.php')`
in this case we will get `/root/folder/app/bootstrap.php` insead of `/root/folder/pub/../app/bootstrap.php`

2017-03-27 12:14 UTC, okorshenko commented
@tkn98 could you please sign CLA? Thank you

2017-03-27 12:52 UTC, tkn98 commented on pub/index.php
> -    require realpath(__DIR__) . '/../app/bootstrap.php';
On closer look I'd say that your suggestion is not necessary. Require deals fine with such paths, it does not need any further assistance, or do you have a scenario at hand where that is not the case. I don't know of any nor can I imagine one.

2017-03-27 13:57 UTC, tkn98 commented
@okobchenko: reg. CLA: Wrong author-email was in the commit, that's why the CLA was shown not-signed. I have signed that long ago, should come green then, updated the commits author.

2017-03-27 14:08 UTC, tkn98 commented
@okobchenko: reg. CLA: (update: now fixed) Wrong author-email was in the commit, that's why the CLA was shown not-signed. I have signed that long ago, should come green then, updated the commits author.

2017-03-27 14:27 UTC, orlangur commented on pub/index.php
> -    require realpath(__DIR__) . '/../app/bootstrap.php';
Passing whole string to `realpath` is a bad idea from debugging perspective, see http://stackoverflow.com/a/21035675.

I saw a lot `realpath` call all over the code, but for `__FILE__` or `__DIR__` it seems useless.

2017-03-27 16:39 UTC, okorshenko approved these changes

2017-03-31 12:16 UTC, okorshenko commented
@tkn98 thank you for your contribution. Your changes successfully merged https://github.com/magento/magento2/commit/485adc5b9c245cd67a99255b2d2da324263deb50#diff-4aa58a2cf6c6b39adfc4e63689aea3c0

2017-03-31 12:16 UTC, closed without merging