Generalize fix from GitHub issue #7000
magento/magento2 pull request #9029
Opened 2017-03-27 19:24 UTC by scottsb

Issue #7000 fixed a particular case where the PayPal payment method renderer would cause a JavaScript crash when trying to use unavailable address information.

However, there are other edge cases where this still occurs (such as when a registered user doesn't have a default shipping address set). This generalizes the fix to use a try/catch, which avoids having to test for every single possibility in the conditional. **Any time** that we can't retrieve the necessary address information, the best option is to simply return an empty object to PayPal, as this now does.

2017-03-27 19:24 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9029) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9029) before we can accept your contribution.<br/>

2017-03-29 08:15 UTC, joni-jones commented
Hi, @scottsb, thanks for contribution. Could you cover your fix with [js test](http://devdocs.magento.com/guides/v2.1/test/js/jasmine.html)?
I think it would be useful to cover the next few cases:

- the address does not contain some properties - test covers the negative scenario
- address contains all properties - test covers the positive scenario

2017-03-29 19:41 UTC, scottsb commented
I will add this test, but it will probably be a few a couple weeks before I can get to it.

2017-03-30 09:58 UTC, YevSent requested changes
Changes should be covered by js test.

2017-04-20 10:26 UTC, ishakhsuvarov commented
Hi @scottsb 
Are you still interested in this PR? Any help needed?

2017-04-20 12:59 UTC, scottsb commented
@ishakhsuvarov, I am still interested in doing this, but we are heads down on a new launch with a tight deadline, so I won't be able to get back to this until after we launch.

2017-04-20 13:01 UTC, ishakhsuvarov commented
@scottsb Thank you for the update. Let us know if you need any help.

2017-06-13 17:16 UTC, okorshenko commented
Hi @scottsb thank you for your contribution. Please, create new PR once ready. Closing due to inactivity

2017-06-13 17:16 UTC, closed without merging