Fix wrong usage of namespaces for the Cli class
magento/magento2 pull request #9060
Opened 2017-03-30 09:59 UTC by adragus-inviqa

Not cool, M2. Not. Cool.

Relates to https://github.com/magento/magento2/issues/9058.

2017-03-30 10:44 UTC, AydinHassan commented
I'm not sure this is necessary, `bin/magento` is not namespaced, so it would work: https://3v4l.org/WCqpl.

I think #9058 is related to `2.1` where `Cli` is referenced relatively but is not imported: https://github.com/magento/magento2/blob/2.1/bin/magento. This seems to be fixed in `develop`

2017-03-30 12:34 UTC, orlangur requested changes

2017-03-30 12:34 UTC, orlangur commented on bin/magento
> +    $application = new \Magento\Framework\Console\Cli('Magento CLI');
Try `Alt+Enter` + `Import Class` in PhpStorm ;)

Hope to see `T_NAMESPACE_SEPARATOR` banned anywhere besides `namespace` and `use` statements someday...

2017-03-31 00:00 UTC, adragus-inviqa commented
@AydinHassan - you're right. I just chaged the `master` version, though. Needless now, I guess. But I still don't like not having a leading slash. Less expressive.

2017-03-31 00:00 UTC, closed without merging