Solve issues with API
magento/magento2 pull request #9124
Opened 2017-04-04 12:25 UTC by paales

### Description
I'm implementing a new API service layer (GraphQL) that intensively uses the API retrospection classes and noticed that there are some inconsistencies in the API

- Some comment sort orders aren't correct, fixed for `ProductAttributeMediaGalleryEntryInterface`, `ConfigurableProductManagementInterface`.
- Replaced di injections and argument types of `SearchCriteria` with `SearchCriteriaInterface`

2017-04-10 13:26 UTC, ishakhsuvarov requested changes

2017-04-10 13:26 UTC, ishakhsuvarov commented on generated/.htaccess
> -Deny from all
What is the reason to remove `Deny` from the `generated` direcotry?

2017-04-10 15:24 UTC, paales commented on generated/.htaccess
> -Deny from all
That, uhm, shouldn't be removed..  deleted the generated folder out of habit I think.

2017-04-10 15:28 UTC, paales commented on generated/.htaccess
> -Deny from all
@ishakhsuvarov Changed the PR.

2017-04-11 09:53 UTC, ishakhsuvarov approved these changes

2017-04-11 09:55 UTC, ishakhsuvarov commented
@paales Did you use `Replace in Path` or created some automated tool to achieve the purpose?

2017-04-12 21:06 UTC, paales commented
Hi @ishakhsuvarov 

I did a find and replace at some point. The functionality was validated as it generates a complete schema of all the complete service layer in GraphQL and the endpoints now work as expected :)

2017-04-13 09:35 UTC, ishakhsuvarov commented
Hi @paales 
We are still in the process of review, as potentially this PR may cause backwards compatibility issue for some of the 3rd party extensions. We will keep you updated.
Thanks.

2017-04-13 15:07 UTC, paales commented
Understandable :)

2017-04-15 12:49 UTC, vrann commented
@paales I've been researching GraphQL for Magento myself and found it very promising for the next generation of the APIs. Would be curious to see your perspective on this subject! If there is anything you want to share, we can connect via slack.

2017-04-18 09:23 UTC, paales commented
Hi @vrann, sure! I've send you a message on Slack (on the super secret Magento chat)

2017-04-19 06:00 UTC, merged

2017-04-19 06:10 UTC, magento-team commented
@paales thank you for your contribution