[Cms] Added a getByIdentifier() method to the BlockRepository
magento/magento2 pull request #9163
Opened 2017-04-07 10:59 UTC by enrico69

2017-04-07 11:06 UTC, adragus-inviqa commented
So you never tried loading a block via its identifier? Try it. [It already works](https://github.com/magento/magento2/blob/5640494293ed26876700bb7c5f9578132bc5b0e6/app/code/Magento/Cms/Model/ResourceModel/Block.php#L108-L112).

2017-04-10 13:11 UTC, ishakhsuvarov requested changes

2017-04-10 13:11 UTC, ishakhsuvarov commented on app/code/Magento/Cms/Api/BlockRepositoryInterface.php
> +    public function getByIdentifier($blockIdentifier, $storeId);
Unfortunately, due to backwards compatibility policy, currently we can not add any new methods to the interfaces, specially the ones marked with the `@api` annotation. You may extract this method to a separate interface/class, if it is really needed.

2017-04-10 13:26 UTC, enrico69 commented on app/code/Magento/Cms/Api/BlockRepositoryInterface.php
> +    public function getByIdentifier($blockIdentifier, $storeId);
What do you suggest? Should I simply remove this part from the interface and let the implementation in the model ( `app/code/Magento/Cms/Model/ResourceModel/Block.php` ) ?

2017-04-10 13:40 UTC, adragus-inviqa commented on app/code/Magento/Cms/Api/BlockRepositoryInterface.php
> +    public function getByIdentifier($blockIdentifier, $storeId);
Actually, your PR is redundant, as `Magento\Cms\Api\BlockRepositoryInterface::getById('my-block-identifier')` already works. As is `Magento\Cms\Api\BlockRepositoryInterface::getById(12)`, too. 

The resource model I showed you is just the place where the logic decides which route to go: identifier or numeric id? Again, try it yourself.

2017-04-10 13:48 UTC, enrico69 commented on app/code/Magento/Cms/Api/BlockRepositoryInterface.php
> +    public function getByIdentifier($blockIdentifier, $storeId);
Yes but there is also this point, given by the user _convenient_

> Might be useful to be aware of #6570 and #7417 in which identifier is not enough to update cms blocks by identifier when that identifier is shared across multiple stores.

2017-04-12 21:00 UTC, enrico69 reviewed
Done

2017-05-21 12:51 UTC, enrico69 commented
@ishakhsuvarov changes are completed.

2017-06-14 20:49 UTC, okorshenko commented
Hi @enrico69 
Thank you for your contribution. Unfortunately, we can not accept this PR. I agree with the point of @adragus-inviqa . Looks like this will be duplication of the functionality.
Thank you for your efforts.

2017-06-14 20:49 UTC, closed without merging