Explace the direct usage of Zend_Json with a call to the Json Help class
magento/magento2 pull request #9344
Opened 2017-04-21 14:31 UTC by dmanners

### Description
Since Zend1 is at EOL we should replace any usage of it's elements. For this case we are removing Zend_Json #9236 

### Fixed Issues (if relevant)

1. magento/magento2#9236: Issue title

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-04-21 15:16 UTC, ishakhsuvarov requested changes

2017-04-21 15:16 UTC, ishakhsuvarov commented on app/code/Magento/Widget/view/adminhtml/templates/instance/edit/layout.phtml
> +        WidgetInstance.addPageGroup(<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($pageGroup) ?>);
This class is deprecated.
Please change to `\Magento\Framework\Serialize\Serializer\Json`

2017-05-20 11:35 UTC, ishakhsuvarov approved these changes

2017-06-01 20:45 UTC, merged

2017-06-01 20:50 UTC, magento-team commented
@dmanners thank you for your contribution