Update tax.js so that "Display Zero Tax Subtotal = No" works
magento/magento2 pull request #9371
Opened 2017-04-24 08:25 UTC by raivisdejus

Making comparison less strict as tax value from this.getPureValue() when empty is 0.000 so that "Display Zero Tax Subtotal = No" works 

### Description

Making comparison less strict as tax value from this.getPureValue() when empty is 0.000 

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

Tested manually:
1. Set Display Zero Tax Subtotal = NO
2. Open cart

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-04-24 08:25 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9371) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9371) before we can accept your contribution.<br/>

2017-05-02 03:59 UTC, ishakhsuvarov requested changes
Please check the cause, why strict comparison does not work and try fixing the root cause of the issue.
Thank you

2017-05-02 03:59 UTC, ishakhsuvarov commented on app/code/Magento/Tax/view/frontend/web/js/view/checkout/cart/totals/tax.js
> +            if (this.getPureValue() == 0) {
This change makes the logic less robust, we should avoid using non-strict comparison even though JS allows this.

2017-05-07 05:48 UTC, raivisdejus commented
Correct fix for the issue proposed in new pull request -> https://github.com/magento/magento2/pull/9538

2017-05-07 05:48 UTC, closed without merging