Update AttributeRepository.php
magento/magento2 pull request #9387
Opened 2017-04-25 07:44 UTC by redelschaap

Fixes a bug in case `$attribute->getOption()` returns NULL when it does not have any options. When NULL is given to `AttributeRepository::getOptionArray`, PHP complains about a TypeError.

2017-04-28 09:15 UTC, ishakhsuvarov requested changes
Service contract for `\Magento\Customer\Api\Data\AttributeMetadataInterface::getOptions` (which is the `$attribute` in this case) states that the only possible return type is `OptionInterface[]`. It is better to check why is it `null` in the specific case and fix it.

2017-04-28 09:15 UTC, ishakhsuvarov commented on app/code/Magento/Customer/Ui/Component/Listing/AttributeRepository.php
> +            $attributeOptions = $attribute->getOption();
Original code used `$attribute->getOptions()` did you mean it?

2017-04-28 09:15 UTC, ishakhsuvarov commented on app/code/Magento/Customer/Ui/Component/Listing/AttributeRepository.php
> +                AttributeMetadataInterface::OPTIONS => is_array($attributeOptions) ? $this->getOptionArray($attributeOptions) : [],
This line is too long. Magento code style standard requires lines to be no longer then 120 characters.

2017-04-28 09:35 UTC, redelschaap commented on app/code/Magento/Customer/Ui/Component/Listing/AttributeRepository.php
> +            $attributeOptions = $attribute->getOption();
No, don't know how it got there

2017-04-28 09:37 UTC, redelschaap commented on app/code/Magento/Customer/Ui/Component/Listing/AttributeRepository.php
> +                AttributeMetadataInterface::OPTIONS => is_array($attributeOptions) ? $this->getOptionArray($attributeOptions) : [],
Updated.

2017-04-28 09:42 UTC, redelschaap commented
Updated the code with your change requests.

2017-04-28 09:44 UTC, ishakhsuvarov commented
@redelschaap Please check the general comment as well:
> Service contract for \Magento\Customer\Api\Data\AttributeMetadataInterface::getOptions (which is the $attribute in this case) states that the only possible return type is OptionInterface[]. It is better to check why is it null in the specific case and fix it.

I am not sure this is the most optimal fix at the moment

2017-04-28 11:13 UTC, redelschaap commented
I think this fix is optimal, because we have a situation where that method does not return an array of `OptionInterface`s, but `NULL` instead. I don't remember what exactly caused it, but it the `option` property of that object was never filled and thus `NULL`.

2017-04-30 14:43 UTC, ishakhsuvarov commented
@redelschaap Service contract claims that no `NULL` value should be returned. Could you please check the case you have encountered? We may need to fix that as it may affect much more client code.

2017-05-04 16:07 UTC, redelschaap commented
@ishakhsuvarov That's the theory, practice shows otherwise ;). I can't reproduce the bug right now as we're working towards the launch of the website.

Where do you suggest this should be fixed?

2017-05-08 09:26 UTC, ishakhsuvarov commented
@redelschaap I would suggest finding exact case, where it reproduces, and fixing the reason why `null` is returned.

2017-05-08 12:31 UTC, redelschaap commented
Well in my case an extension was responsible, that I do know. You can't say "it's the extension's fault, they should fix it", when Magento's core makes it possible to leave the `options` property `NULL`.

2017-06-15 13:29 UTC, ishakhsuvarov commented
@redelschaap Closing this PR for now. Please reopen if this issue occurs again with the reproducible steps. We will definitely look for ways to solve the problem.
Thank you for collaboration.

2017-06-15 13:29 UTC, closed without merging