Update Template.php
magento/magento2 pull request #9401
Opened 2017-04-26 00:38 UTC by thiagolima-bm

This update enable the use of loop into template files. Allowing the user iterate through collections

Manual testing scenarios

consider $template as Magento\Email\Model\Template
the email template as follows
$value = "
{{var order.increment_id}}

{{loop order.all_visible_items delimiter=,}}
{
'sku': '{{var item.sku}}',
'name': '{{var item.name}}',
'price': {{var item.price}},
'quantity': {{var item.ordered_qty}}
}
{{/loop}}

{{var order.customer_id}}

{{loop things.collection delimiter=,}}
{
'name': '{{var item.name}}',
'lastname': '{{var item.lastname}}',
'age': '{{var item.age}}',
}
{{/loop}}
";
$template->setTemplateText($value);
$template = new Magento\Email\Model\Template(new Magento\Framework\Model\Context)
$template->setTemplateText($value);
$thing_1 = new Varien_Object();
$thing_1->setName('Richard');
$thing_1->setAge(24);

$thing_2 = new Varien_Object();
$thing_2->setName('Jane');
$thing_2->setAge(12);

$thing_3 = new Varien_Object();
$thing_3->setName('Spot');
$thing_3->setLastName('The Dog');
$thing_3->setAge(7);

$collection_of_things = new Varien_Data_Collection();
$collection_of_things
    ->addItem($thing_1)
    ->addItem($thing_2)
    ->addItem($thing_3);

$things = new Varien_Object();
$things->setData('collection', $collection_of_things);

echo $template->getProcessedTemplate(array('order' => $order, 'things' => $things))

2017-04-26 01:32 UTC, bap14 commented
What would the output of this look like?  Is it possible to utilize an inline-template call within the loop to customize the display of items?

2017-04-26 07:01 UTC, adragus-inviqa commented on lib/internal/Magento/Framework/Filter/Template.php
> +                if (is_array($objectArrayData) || $objectArrayData instanceof Varien_Data_Collection) {
You should allow more than arrays and object collections in here.
You should use `is_array($data) || ($data instanceof Traversable)`.

2017-04-26 07:04 UTC, adragus-inviqa commented
Ah, yes - `Varien_Data` and `Varien_Data_Collection`. Good times, good times.

2017-04-26 11:44 UTC, thiagolima-bm commented
@bap14 Lets suppose that you have the fallowing template:
 
`Increment ID: {{var order.increment_id}} <br>
        
        <ul>
            {{loop order.all_visible_items delimiter=<br>}}
                <li>
                    sku: {{var item.sku}}<br>
                    name: {{var item.name}}<br>
                    price: {{var item.price}}<br>
                    quantity: {{var item.ordered_qty}}<br>
                </li>
            {{/loop}}               
        </ul>
        
        
        Customer Email: {{var order.customer_email}}
        
        <ul>
            {{loop things.collection delimiter=}}
                <li>name: {{var item.name}}, lastname: {{var item.lastname}}, age: {{var item.age}}</li>
            {{/loop}}
        </ul>`
The output would be:
` Increment ID: 000000001 <br>
        
        <ul>
            
                <li>
                    sku: WS03-XS-Red<br>
                    name: Iris Workout Top-XS-Red<br>
                    price: 0.0000<br>
                    quantity: <br>
                </li>
                           
        </ul>
        
        
        Customer Email: roni_cost@example.com
        
        <ul>
            
                <li>name: Richard, lastname: , age: 24</li>
            
                <li>name: Jane, lastname: , age: 12</li>
            
                <li>name: Spot, lastname: , age: 7</li>
            
        </ul>
`

2017-04-26 11:46 UTC, thiagolima-bm commented
@adragus-inviqa I have fixed that. Sorry! M1 is still running in my brain hehe

2017-04-27 06:42 UTC, orlangur commented
Hi guys, I see a lot of thumbs up here which means Community is really in need of such functionality, but...

Do you _really_ think it's a good idea to expand some custom templating language? For example, Twig is a pretty mature technology, has pretty similar syntax and [`loop` out-of-the-box](https://twig.sensiolabs.org/doc/2.x/tags/for.html).

There is even some attempt https://github.com/kalenjordan/magento-twigmail to introduce Twig support in email templates for Magento 1 :)

2017-04-27 09:04 UTC, thiagolima-bm commented
@orlangur I would say so but, I do know how much effort will be needed. At least my PR does not affect the actual M2 behaviour. :)

2017-04-27 13:15 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                if (is_array($objectArrayData) || $objectArrayData instanceof Varien_Data_Collection) {
Applied :)

2017-05-02 08:35 UTC, ishakhsuvarov commented
Hi
I generally like the idea of the changes proposed, however I would encourage you to look into some additional features which may be added to the`loop`. Current implementation may solve just a single problem which is iteration of the specified collection.
Real life usage may require more versatility to the solution such as access to the information on array keys. Link provided above has some information on that. 
If you would like to continue work on this PR we could come up with the minimum list of capabilities for such feature.

Thanks

2017-05-02 10:38 UTC, thiagolima-bm commented
@ishakhsuvarov Hey, I would like to continue.

2017-06-20 22:30 UTC, okorshenko commented
Hi @thiagolima-bm do you have any progress on that or should we close this PR?

2017-07-03 20:44 UTC, thiagolima-bm commented
@okorshenko Yes. The use of arrays is available too.

2017-07-05 11:55 UTC, thiagolima-bm commented
@ishakhsuvarov Updated.

2017-07-05 14:02 UTC, orlangur commented
@thiagolima-bm, thanks for considering Twig 👍 I don't think it would require too much efforts but will not insist until I have some proof-of-concept in my hand :)

Sorry for not answering for a long time, I had something to say but somehow lost this thread and then forgot.

What do you think about making your implementation more Twig-like instead of custom syntax?

So, instead of
```
{{loop order.all_visible_items}}
    <li>
        row number: {{var item.itemCount}}<br>
        sku: {{var item.sku}}<br>
        name: {{var item.name}}<br>
        price: {{var item.price}}<br>
        quantity: {{var item.ordered_qty}}<br>
    </li>
{{/loop}}        
```
I think it would be better to partially implement capabilities of https://twig.sensiolabs.org/doc/2.x/tags/for.html

```
{{for item in order.all_visible_items}}
    <li>
        row number: {{var loop.index}}<br>
        sku: {{var item.sku}}<br>
        name: {{var item.name}}<br>
        price: {{var item.price}}<br>
        quantity: {{var item.ordered_qty}}<br>
    </li>
{{/for}}
```
I think it's enough to implement subset of Twig features consisting of `{{for`, `loop.index`, `loop.first`, `loop.last` and `loop.length`. In such case we will make learning curve steeper for many developers and will avoid headache if we ever replace custom email templates with Twig or similar engine.

Also, would be really nice to place sample syntax in `filterFor` method PHPDoc.

Please share your thoughts.

2017-07-07 16:16 UTC, thiagolima-bm commented
@ishakhsuvarov @orlangur 

Running this code:
`Increment ID: {{var order.increment_id}} <br>
        
        <ul>
            {{for item in order.all_visible_items}}
                <li>
                    index: {{var loop.index}}
                    sku: {{var item.sku}}
                    name: {{var item.name}}
                    price: {{var item.price}}
                    quantity: {{var item.ordered_qty}}
                </li>
            {{/for}}               
        </ul>
        
        Customer Email: {{var order.customer_email}}
        
        <ul>
            {{for thing in things}}
                <li>{{var loop.index}} name: {{var thing.name}}, lastname: {{var thing.lastname}}, age: {{var thing.age}}</li>
            {{/for}}
        </ul>`

The result would be:
`Increment ID: 000000001 <br>     
<ul>
    <li>
        index: 1
        sku: WS03-XS-Red
        name: Iris Workout Top-XS-Red
        price: 0.0000
        quantity: 
    </li>
</ul>
        
Customer Email: roni_cost@example.com
        
<ul>
    <li>1 name: Richard, lastname: , age: 24</li>
    <li>2 name: Jane, lastname: , age: 12</li>
    <li>3 name: Spot, lastname: , age: 7</li>
</ul>`

2017-07-15 15:26 UTC, thiagolima-bm commented
@ishakhsuvarov @orlangur @okorshenko The changes were made.

2017-08-03 21:07 UTC, alankent commented
Just a comment referring back to Twig, we are not likely to be adopting Twig any time soon. We looked at Twig during M2.0 but decided against it based on feedback we got. Basically the consistent feedback was port every template or none - don't have a mix of PHTML and Twig templates. We agreed. So incorporating Twig would be a massive undertaking with significant impact. It's not likely to happen any time soon.

2017-08-04 11:41 UTC, orlangur commented
@alankent yeah, Twig support together with PHTML was in core for some time in dev releases and then it was decided that "There can be only one" so that Twig was dropped from core but template engine switching mechanism was left intact.

However, here we are not talking about Twig VS PHTML, it's all about HTML templates used in emails which use one more template syntax and not following any specification. This is something that really does not smell good (unlike PHTML which is totally OK if used properly), looks pretty Twig-like and can be replaced by Twig with no significant impact (as usual: introduce Twig instead of home-brewed HTML templates in 2.3 deprecating the latter, then in 2.4 we can leave only one proper template syntax for email templates).

2017-08-04 17:39 UTC, okorshenko requested changes

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +    const LOOP_PATTERN = '/{{for(.*? )(in)(.*?)}}(.*?){{\/for}}/si';
Please, use named groups in order to avoid access by indexes.
Something like /`{{for(?P<loopItem>.*? )(in)(?P<loopData>.*?)}}(?P<loopBody>.*?){{\/for}}/si`

Also, we need to adjust the expression itself

This line is still valid by regexp: `{{for in }} sku: {{var item.sku}}<br>name: {{var item.name}}<br> {{/for}}`
Please, cover this expressions by the unit test. Try all possible options. Also, this test will be a documentaiton for this feature: How to write loops in temaplte files.

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +                if (sizeof($construction) < 5) {
what is a magic number 5? Let's fix expressions and this validation. Please, don't use magic numbers for validation.

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +                    $indexCount = 1;
let's start index from `0`

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +                    foreach ($objectArrayData as $k => $objectData) {
why do we need `$k` variable?

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +                $full_text_to_replace = $construction[0];
please use CamelCase style for variable names

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +                $vName = preg_replace('/\s+/', '', $construction[1]);
should it be a `$varName` or `$loopItem`?

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +                        $loop->setData('loop');
why do we need this empty value in the data object?

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +                        $this->templateVars['loop'] = $loop;
why do we need this template var?

2017-08-04 17:39 UTC, okorshenko commented on lib/internal/Magento/Framework/Filter/Template.php
> +    protected function filterFor($value)
Please, cover this method with the integration test

2017-08-05 16:48 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                        $this->templateVars['loop'] = $loop;
In order the the the index value. e.g.: {{var loop.index}}. Line 424 will be removed.

2017-08-05 16:49 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                        $loop->setData('loop');
In order the the the index value. e.g.: {{var loop.index}}. Line 424 will be removed.

2017-08-05 16:50 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                    foreach ($objectArrayData as $k => $objectData) {
is not needed. Will be removed.

2017-08-05 16:50 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                    $indexCount = 1;
ok

2017-08-05 16:51 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                $vName = preg_replace('/\s+/', '', $construction[1]);
I am doing some refactoring

2017-08-05 16:51 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                $full_text_to_replace = $construction[0];
Ok.

2017-08-05 17:35 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +                if (sizeof($construction) < 5) {
Ok

2017-08-05 17:35 UTC, thiagolima-bm commented on lib/internal/Magento/Framework/Filter/Template.php
> +    protected function filterFor($value)
ok

2017-08-09 08:06 UTC, thiagolima-bm commented
@okorshenko I would say that is all set.

2017-08-09 08:36 UTC, orlangur commented
@thiagolima-bm please assure Travis CI build is green (currently unit, integration and static tests jobs are red).

2017-08-11 09:12 UTC, thiagolima-bm commented
@orlangur I do not know what is happening, but when I run these tests in my machice, everything works fine.

Integration tests works fine.
But, somehow, when running unit tests  
Fatal error: Cannot declare class Magento\Framework\Filter\Test\Unit\TemplateTest, because the name is already in use in /home/travis/build/magento/magento2/vendor/magento/framework/Filter/Test/Unit/TemplateTest.php on line 373

2017-08-11 09:27 UTC, orlangur commented
`vendor/magento/framework/Filter/Test/Unit/TemplateTest.php` you should not commit anything into `vendor` folder, test is placed in https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Filter/Test/Unit/TemplateTest.php

2017-08-11 10:41 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9401) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9401) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: thiagolima-bm<br/>:x: thiagolimaufrj

2017-08-11 11:09 UTC, thiagolima-bm commented
Thanks, @orlangur! All set.

2017-08-11 15:45 UTC, okorshenko commented
Hi @thiagolima-bm could you please look at failed static tests?

2017-08-11 21:57 UTC, okorshenko commented
Fixed on our side

2017-08-11 21:57 UTC, okorshenko approved these changes

2017-08-21 09:07 UTC, thiagolima-bm commented
Ok!

2017-08-21 18:40 UTC, merged

2017-10-24 09:13 UTC, thiagolima-bm commented
@okorshenko somehow, my contributor label is missing :(

2017-10-24 09:22 UTC, orlangur commented
Hi @thiagolima-bm, as we already discussed in scope of another PR, this is not something Magento can handle on its side.

Please make sure all emails used for commits: https://github.com/magento/magento2/pull/9401/commits are associated with your current account.