#7988 Pull Request
magento/magento2 pull request #9484
Opened 2017-05-03 08:39 UTC by arshadpkm

### Description
Issue #7988 Typo changed also added comments for each index, getters and setters.

### Fixed Issues (if relevant)
1. magento/magento2#7988: Typo in variable name: billingAddressFromData vs. billingAddressFormData 

### Manual testing scenarios
1. Not applicable

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-05-03 08:40 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9484) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9484) before we can accept your contribution.<br/>

2017-05-03 08:47 UTC, adragus-inviqa commented
I'm not sure comments add much value here. Comments usually don't. I'd rather you take them out.

What happens if the logic changes and the values are not taken from local storage? You'd have to update the comments, too. Suddently, you have two things to maintain.

2017-05-03 08:59 UTC, okorshenko requested changes

2017-05-03 08:59 UTC, okorshenko commented on app/code/Magento/Checkout/view/frontend/web/js/checkout-data.js
> +            'selectedShippingAddress': null, // Selected shipping address pullled from local storage (Persistence)
1. remove space between // and Selected (fix all cases)
2. replace local storage (Persistence) and  local storage --> persistence storage

2017-05-03 08:59 UTC, okorshenko commented on app/code/Magento/Checkout/view/frontend/web/js/checkout-data.js
> +         * Setting the selected shipping address pulled from local storage
add . at the end of the comment. (all cases)

2017-05-03 09:14 UTC, arshadpkm commented on app/code/Magento/Checkout/view/frontend/web/js/checkout-data.js
> +            'selectedShippingAddress': null, // Selected shipping address pullled from local storage (Persistence)
Updated in my new commit

2017-05-03 09:24 UTC, okorshenko approved these changes

2017-05-03 11:07 UTC, adragus-inviqa commented
If you're going to do it, at least fix the `pullled` typo.

2017-05-08 13:23 UTC, ishakhsuvarov commented
Hi @arshadpkm 
Please sync your branch with the latest `develop` and fix merge conflicts
Thanks!

2017-05-10 07:19 UTC, arshadpkm commented
@ishakhsuvarov Fixed merge conflicts

2017-06-13 02:02 UTC, okorshenko commented
Hi @arshadpkm thank you for your contribution. Your Pull Request has been merged.

2017-06-13 02:02 UTC, closed without merging