Zend_Wildfire deprecated, Firephp outdated, magento/magento2#9239 and magento/magento2#9241
magento/magento2 pull request #9622
Opened 2017-05-13 15:37 UTC by SolsWebdesign

Zend_Wildfire was deprecated from ZendFramework 2.0. Some parts of FirePhp are now used in Zend\Log\Writer but the FirePhp library itself is outdated and does not work in the latest Firefox anymore. These files, Firebug and FirebugTest, can be removed.

### Description
Zend_Wildfire was deprecated from ZendFramework 2.0. Some parts of FirePhp are now used in Zend\Log\Writer but the FirePhp library itself is outdated and does not work in the latest Firefox anymore. These files, Firebug and FirebugTest, can be removed.

### Fixed Issues (if relevant)

1. magento/magento2#9239 : Upgrade ZF components. Zend_Controller
2. magento/magento2#9241 : Upgrade ZF components. Zend_Wildfire

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-05-13 15:38 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9622) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9622) before we can accept your contribution.<br/>

2017-05-13 16:34 UTC, ishakhsuvarov requested changes
Since all usages of the `Zend_Controller` and `Zend_Wildfire` are removed please remove these dependencies from `composer.json` and `composer.lock`

2017-05-13 16:36 UTC, ishakhsuvarov approved these changes

2017-05-16 18:01 UTC, merged

2017-05-16 18:10 UTC, magento-team commented
@SolsWebdesign Thank you for the contribution