[MAGETWO-54158]:+ Corrected ACL rules for the sendfriend module and s…
magento/magento2 pull request #9628
Opened 2017-05-13 21:44 UTC by jspoe

### Description

Added an acl.xml to the send-friend module
Added upgrade data script for backward compatibility for ACL-roles that were already selected for users.

Changed the acl.xml for the backend module
Added upgrade data script for backward compatibility for ACL-roles that were already selected for users.

### Fixed Issues (if relevant)

1. magento/magento2#MAGETWO-54158: ACL not defined for Magento_Backend::web

### Manual testing scenarios

1. Install Magento latest develop version
2. Go to Admin side
3. Click "System > User Roles"
4. Click "Add new Role" enter Role name
5. In left side choose Role Resources and check "Dashboard", "Web Section", "Email to a friend", "Currency Setup", "Store E-mail addresses"
6. Save Role
7. Click "System > All Users"
8. Click "Add new User"
9. Enter data in required fields
10. In left side click "User Role" and choose early created role.
11. Click "Save"
12. Sign out and Log in using credentials of new user
13. Click "Stores > Configuration"

Expected result:
All the tabs that were selected in the role should be visible

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-05-13 21:44 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9628) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9628) before we can accept your contribution.<br/><hr/>**Johan Spoelstra** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-05-20 09:32 UTC, ishakhsuvarov requested changes

2017-05-20 09:32 UTC, ishakhsuvarov commented on app/code/Magento/Config/Setup/UpgradeData.php
> +    protected function upgradeAcl(ModuleDataSetupInterface $setup)
Is there any reason for this method is protected?  Looks like private is more suitable in this case.

2017-05-20 09:32 UTC, ishakhsuvarov commented on app/code/Magento/Config/Setup/UpgradeData.php
> +    /**
`{@inheritdoc}` is sufficient in this case.

2017-05-20 09:32 UTC, ishakhsuvarov commented on app/code/Magento/Config/Setup/UpgradeData.php
> +     * @param ModuleDataSetupInterface $setup
Would be nice to add a comment which explains background under this action.

2017-05-20 09:32 UTC, ishakhsuvarov commented on app/code/Magento/Config/etc/acl.xml
> +                            <resource id="Magento_Backend::advanced" title="Advanced Section" translate="title" sortOrder="90" />
Did you consider introducing these resources in the `Backend/etc/acl.xml`?

2017-05-20 09:32 UTC, ishakhsuvarov commented on app/code/Magento/SendFriend/Setup/UpgradeData.php
> +    protected function upgradeAcl(ModuleDataSetupInterface $setup)
Please consider making this method private

2017-05-29 07:18 UTC, ishakhsuvarov commented
Hi @jspoe 
Would you like to continue work on this PR or should someone else pick it up?

2017-05-29 07:44 UTC, jspoe commented
Hi @ishakhsuvarov 

Thank you for your feedback!
I will pickup the requested changes in a couple of days. Should not take a lot of time.

2017-06-08 09:58 UTC, ishakhsuvarov commented
@jspoe Thanks, we will proceed with review shortly.

2017-06-13 09:31 UTC, ishakhsuvarov approved these changes

2017-06-14 10:46 UTC, ishakhsuvarov commented
@jspoe It looks like these changes introduce some unwanted dependencies between the modules in question. We will look into possible solution and let you know how we can fix it.

2017-06-14 11:49 UTC, jspoe commented
Yes I understand. It is either part of the Magento_Config module or the Magento_Backend module.
It should not be both. Then there is also the part of the setup script where there is a (small) dependency for to map the roles for backward compatibility.

Please let me know as soon as possible if I can fix this in a better way for you.

2017-06-14 13:15 UTC, ishakhsuvarov commented
@jspoe Looks like the best solution in this case would be to move upgrade scripts to the specifically created modules, something like SendfriendAcl or SendfriendAuthorization, which would have correct dependencies and would allow other modules to be disabled/removed safely.
Would you like to continue on that, since it is some more work to do, or do you want someone else to pick up?
Thanks!

2017-06-14 13:33 UTC, jspoe commented
Hi @ishakhsuvarov,

I agree, and I will pick up the requests myself if possible.
I will push a change as soon as I can.

Thanks!

2017-06-14 13:34 UTC, ishakhsuvarov commented
@jspoe Thank you

2017-06-29 08:47 UTC, ishakhsuvarov commented
@jspoe I am closing this PR for now due to inactivity. Please feel free to update and reopen whenever you wish to continue work on it.
Thank you!

2017-06-29 08:47 UTC, closed without merging