Feature/join file method transport builder
magento/magento2 pull request #9747
Opened 2017-05-23 21:06 UTC by enrico69

Added a new method to the transport build to make joining a file to an email easier.

### Description
Added a method joinFile() to the class Magento\Framework\Mail\Template\TransportBuilder to add some abstraction and making easier to join a file from the transport builder.

### Manual testing scenarios

An example of testing is to send the user agreement in a pdf file joined to the invoice. 
Override the class Magento\Sales\Model\Order\Email\SenderBuilder and call, at line 52, this code:
`$this->transportBuilder->joinFile($directory, $fileName, $fileType, $joinedFileName);` like this
`$this->transportBuilder->joinFile('var', 'EULA.pdf', 'application/pdf', 'EULA.pdf');`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-05-24 06:19 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +    public function joinFile($directory, $fileName, $fileType, $joinedFileName)
I think would be better to:
1. Rename method to attackFile
2. Combine directory & filename to one parameter - filepath
3. Make auto-filling of file type (or define some default value)
4. Make auto-filling of attacked file (by default should be the same)

2017-05-24 06:45 UTC, enrico69 commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +    public function joinFile($directory, $fileName, $fileType, $joinedFileName)
Ok thank you for your opinion. I am going to make these modifications today.

2017-05-24 06:52 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +    public function joinFile($directory, $fileName, $fileType, $joinedFileName)
I think you could wait for answer from magento team, maybe they decide to do another changes.

2017-05-24 09:14 UTC, korostii commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +    public function joinFile($directory, $fileName, $fileType, $joinedFileName)
You almost made my head explode right there.
I think you've meant to write "attachFile", haven't you?

2017-05-26 21:12 UTC, fooman commented
@enrico69 thanks for your pull request.

One issue which would need addressing as part of this pull request is that the current 
`Magento\Framework\Mail\MessageInterface`
does not include the method createAttachment(). It currently works because the class that is instantiated `\Zend_Mail` does have it - it however would break on implementations that fulfil the interface but do not have a createAttachment method with the same parameters. 

As  `Magento\Framework\Mail\MessageInterface` is part of the `@api` we will either need to bump it's version number and/or create a new enhanced MessageInterface.

I'll get someone from the Magento side to chime in on the best way forward.

2017-05-29 16:09 UTC, ihor-sviziev commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +    public function joinFile($directory, $fileName, $fileType, $joinedFileName)
@korostii yes, fixed my typo

2017-06-23 04:52 UTC, fooman commented
Okay so the way to approach the introduction of this new interface is outlined [here](http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#introduction-of-a-method-to-a-class-or-interface).

2017-07-02 09:05 UTC, enrico69 commented
Modifications done.

2017-11-23 12:08 UTC, vkublytskyi requested changes
@enrico69 Thank you for this contribution and sorry for a long time without response.

Possibility to attach a file to a mail message is really needed feature. However, as these changes modify existing API and introduce new one, such changes should be designed more carefully to not introduce backward incompatible changes and to have a usable API as a result. Please see my comments regarding implementation.

If you are still interested in this PR please resolve backward compatibility issues and  conflicts with changed Magento code.

2017-11-23 12:08 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Mail/ExtendedMessageInterface.php
> +interface ExtendedMessageInterface extends MessageInterface
The name of the interface is too abstract. It may cause an issue if in future new methods should be added to Message. Please reflect purpose of the interface in a name (e.g. `AttachmentMessageInterface`)

2017-11-23 12:08 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +        ExtendedMessageInterface $message,
This change is not allowed as is backward incompatible. If some 3rd party module has own implementation of MessageInterface it will not be accepted by this class anymore.

2017-11-23 12:08 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +            TemplateTypesInterface::TYPE_TEXT => ExtendedMessageInterface::TYPE_TEXT,
Unnecessary changes. Constants are defined at `Magento\Framework\Mail\MessageInterface` so it's better to use more high-level abstraction if possible.

2017-11-23 12:08 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +        $file = new File();
Avoid direct class creation with `new` operator in Magento 2. Use `Magento\Framework\Filesystem\Directory\ReadFactory::create` instead.

2017-11-23 12:08 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php
> +    public function attachFile($fileName, $fileType, $joinedFileName)
`Magento\Framework\Mail\Template\TransportBuilder` is also marked with an `@api` annotation so we should avoid changing its contract.
Probably the best approach to implement this feature would implement a decorator for `Magento\Framework\Mail\Template\TransportBuilder`:
1. Create new class that `extends` `Magento\Framework\Mail\Template\TransportBuilder` (Magento 2 not recommends use class inheritance but in this case seems this is most suitable approach). Class name should reflects class purpose (e.g. `AttachmentTransportBuilder`)
2. This class should accept an instance of `Magento\Framework\Mail\Template\TransportBuilder` in a constructor and delegate all methods calls to it.
3. Define `attachFile` method in the decorator. Instead of modifying own `message` property work directly with a property of decorated object (`$this->decorated->message->createAttachement`). It will be accessible as is `protected` and decorator is a child of decorated class.
4. You may add logic in the constructor and check that message in the decorated object is an instance of message with attachment and throws `\InvalidArgumentException` otherwise.

2017-11-23 12:08 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Mail/Transport.php
> +    public function __construct(\Magento\Framework\Mail\ExtendedMessageInterface $message, $parameters = null)
Modification of constructor is not allowed as this is backward incompatible change. Please see http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/. Change of argument type to more strict is equal to removing all argument and introduction of new one.

2017-11-23 16:42 UTC, enrico69 commented
Ok I am going to check that.

2017-12-25 09:59 UTC, enrico69 commented
In progress

2017-12-26 15:03 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/magento2?pullRequest=9747) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9747) before we can accept your contribution.<br/>**6** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: okorshenko<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: sidolov<br/>:white_check_mark: nmalevanec<br/>:white_check_mark: miguelbalparda<br/>:white_check_mark: RomaKis<br/>:x: slopukhov<br/>:x: duhon

2018-01-18 07:20 UTC, ihor-sviziev commented
@enrico69 let us know once you finish it or if you need any help

2018-01-21 16:35 UTC, enrico69 commented
Hi @ihor-sviziev 
Sorry, the job is (supposed to be) done in the commit [6cafef1](https://github.com/magento/magento2/pull/9747/commits/6cafef1e5e18d86f1badd83ed7052d22f6fccb34) .

I tried to follow your recommandations as much as possible.

2018-01-26 21:29 UTC, okorshenko commented
Hi @enrico69 
could you please cleanup the branch so that we can proceed with this PR.

2018-01-28 21:06 UTC, enrico69 commented
Ho @okobchenko 

Honestly I am not sure what do now. I did my modifications after trying to update my branch which was veryyy absolete. All my work is in [6cafef1](https://github.com/magento/magento2/pull/9747/commits/6cafef1e5e18d86f1badd83ed7052d22f6fccb34)

2018-01-29 15:48 UTC, okorshenko commented
Hi @enrico69 
Please checkout 2.3-develop branch from magento/magento2 repository. Apply the changes from your commit. Please, do not use `root` as a an author of commit. Use your github account. Force push your local changes to `enrico69:feature/join-file-method-transport-builder`

2018-01-29 17:47 UTC, enrico69 commented
Hi @okorshenko 
OK I will do that asap.

2018-02-12 13:46 UTC, enrico69 commented
Hi @okorshenko 

That's done.

2018-02-12 15:58 UTC, magento-engcom-team commented
@enrico69 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-04-02 08:52 UTC, vkublytskyi approved these changes

2018-04-02 08:53 UTC, vkublytskyi commented on lib/internal/Magento/Framework/Mail/Template/AttachmentTransportBuilder.php
> +    protected $transportBuilder;
Better to declare as private properties

2018-04-02 08:55 UTC, magento-engcom-team commented
Hi @vkublytskyi, thank you for the review.
[MAGETWO-70492](https://jira.corp.magento.com/browse/MAGETWO-70492) has been created to process this Pull Request

2018-04-04 11:26 UTC, TomashKhamlai commented on lib/internal/Magento/Framework/Mail/Template/AttachmentTransportBuilder.php
> + * Copyright © 2013-2017 Magento, Inc. All rights reserved.
Please correct the copyright. Tests failed with error:
`Copyright is missing or has wrong format`

2018-04-04 11:26 UTC, TomashKhamlai commented on lib/internal/Magento/Framework/Mail/AttachmentMessageInterface.php
> + * Copyright © 2013-2017 Magento, Inc. All rights reserved.
Please correct the copyright. Tests failed with error:
`Copyright is missing or has wrong format`

2018-04-18 10:12 UTC, sidolov commented
Hi @enrico69 , I verified your solution and found that we updated `zendframework/zend-mail` package to the new version. Unfortunately your implementation not compatible with latest changes. You may implement a new solution or close this PR. 
Thank you for your contribution!

2018-04-23 06:26 UTC, sidolov commented
Hi @enrico69 , I'm closing this PR for now, if you implement the new solution, feel free to reopen this PR or create new. Thank you for collaboration!

2018-04-23 06:26 UTC, closed without merging