Fix memory leak for images resize command.
magento/magento2 pull request #9858
Opened 2017-06-06 11:50 UTC by Koc

### Description
We have large catalog with many products and 2Gb memory limit is not enough to resize all of the images. I've removed storing loaded products inside identity map and it helps a lot.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-06-06 11:51 UTC, Koc commented
I can also add progressbar to indicate resizing progress if this acceptable

2017-06-06 12:07 UTC, mslabko commented
Hi @Koc ,
For mainline this issue already fixed - https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/ProductRepository.php#L311-L312 
I think it make sense to port existing solution to 2.1, does it work for you?

2017-06-06 12:17 UTC, Koc commented
@mslabko I haven't tested this yet but looks like it should works. Agree, it is better backport it to 2.1. But who  should do it: am I in this PR or somewho from Magento's team can?

2017-06-06 12:33 UTC, ishakhsuvarov commented
@Koc I am pretty sure you can work on this, if you wish

2017-06-23 20:37 UTC, okorshenko requested changes

2017-06-23 20:37 UTC, okorshenko commented on app/code/Magento/Catalog/Api/ProductRepositoryInterface.php
> +    public function cleanCache();
it is not allowed change @api interfaces in patch releases. Unfortunately, we can not accept this change.

2017-06-23 20:37 UTC, okorshenko commented on app/code/Magento/Catalog/Console/Command/ImagesResizeCommand.php
> +                $this->productRepository->cleanCache();
this method is out of RepositoryInterface, so we can not call it directly. As a workaround, we can check if method_exists and call it. In this case the fix will be BC

2017-06-25 10:23 UTC, Koc commented on app/code/Magento/Catalog/Api/ProductRepositoryInterface.php
> +    public function cleanCache();
I will try backport another implementation from develop brahcn.

2017-07-18 19:15 UTC, okorshenko commented
Closing this PR due to inactivity. provided changes do not follow Backward compatibility policy. 
Thank you @Koc for your effort

2017-07-18 19:15 UTC, closed without merging